### PR TITLE
feat: [IDP-1426]: Adding IDP stage in pipeline

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54597)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger codeformat

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/registrar/IdpStepRegistrar.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Niew_IM0O2MaF02HQJr:-Niew_IM0O2MaF02HQJs:bph5kcf) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/registrar/IdpStepRegistrar.java#L38)):*
> ```Java
>     engineSteps.put(InitializeTaskStep.STEP_TYPE, InitializeTaskStepV2.class);
>     engineSteps.put(IDPStageStepPMS.STEP_TYPE, IDPStageStepPMS.class);
>     engineSteps.put(NGSpecStep.STEP_TYPE, NGSpecStep.class);
> ```

You can remove this NGSpecStep. Because its already coming fro the NGCommonUtilStepsRegistrar.getEngineSteps().



_Code quote:_
```Java
engineSteps.put(NGSpecStep.STEP_TYPE, NGSpecStep.class);
```

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/filtercreator/IDPStageFilterCreator.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-NiewhnBEmoNEqd75cpP:-NiewhnBEmoNEqd75cpQ:bdb1qn3) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/filtercreator/IDPStageFilterCreator.java#L41)):*
> ```Java
> import io.harness.pms.pipeline.filter.PipelineFilter;
> import io.harness.pms.sdk.core.filter.creation.beans.FilterCreationContext;
> import io.harness.pms.yaml.*;
> ```

Avoid * imports. Checkstyle would also fail.

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 135 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Niey2qy3H8RamXWDuSm:-Niey2qy3H8RamXWDuSn:bidmxl2) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L135)):*
> ```Java
>     BuildStatusUpdateParameter buildStatusUpdateParameter =
>         obtainBuildStatusUpdateParameter(ctx, stageNode, executionSource);
>     return IntegrationStageStepParametersPMS.getStepParameters(
> ```

Create IDPStageStepParametersPMS like you created IDPStageNode. you can simply extend the class IntegrationStageStepParametersPMS. follow what IACM did for IACMIntegrationStageStepParametersPMS.

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 321 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Nif-Pmw5qYvgz6ud_q_:-Nif-Pmw5qYvgz6ud_qa:bi5upn5) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L321)):*
> ```Java
>   }
>   private IntegrationStageNode getIntegrationStageNode(IDPStageNode stageNode) {
>     IntegrationStageConfig currentStageConfig = (IntegrationStageConfig) stageNode.getStageInfoConfig();
> ```

@devesh-harness I see that we have created the IDPStageNode but there are some utils that work on the IntegrationStageNode and you need to use them. So you are again creating the IntegrationStageNode from the IDPStageNode. 

I think it would be better if you make the IDPStageNode extent the IntegrationStageNode. Then the same utils would work for your IDPStageNode directly by type-casting.

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 36 of 40 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54597)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 135 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Niey2qy3H8RamXWDuSm:-NijrB_S9V3TBOhp3RD4:b6w1y2i) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L135)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Create IDPStageStepParametersPMS like you created IDPStageNode. you can simply extend the class IntegrationStageStepParametersPMS. follow what IACM did for IACMIntegrationStageStepParametersPMS.
</blockquote></details>

Pls do this in the next PR as discussed offline.
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 321 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Nif-Pmw5qYvgz6ud_q_:-NijrFLD7q8kjmJctKUf:b-t3gc2l) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L321)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@devesh-harness I see that we have created the IDPStageNode but there are some utils that work on the IntegrationStageNode and you need to use them. So you are again creating the IntegrationStageNode from the IDPStageNode. 

I think it would be better if you make the IDPStageNode extent the IntegrationStageNode. Then the same utils would work for your IDPStageNode directly by type-casting.
</blockquote></details>

As discussed oflline, pls handle this in the next pr.
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPStageStepPMS.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-NijrZIv9UZnKXElxpG9:-NijrZIv9UZnKXElxpGA:b-iwvdl7) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPStageStepPMS.java#L70)):*
> ```Java
>         "Executing IDP stage with params accountId {} projectId {} [{}]", accountId, projectIdentifier, stepParameters);
> 
>     IntegrationStageStepParametersPMS integrationStageStepParametersPMS =
> ```

nit: pls use IDPStageStepParameters in next PR.
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/yamlschema/IDPYamlSchemaResource.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Nik2Ay65UowMaYcCYvk:-Nik2Ay65UowMaYcCYvl:b-518ml2) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/yamlschema/IDPYamlSchemaResource.java#L53)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> public class IDPYamlSchemaResource implements YamlSchemaResource {
> ```

Remove this class. Its is not needed. Now we have the static schema so schema would come from the git.
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/yamlschema/IDPYamlSchemaService.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Nik2NBo1BF4gmapB5OG:-Nik2NBo1BF4gmapB5OH:b-s0zrq4) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/yamlschema/IDPYamlSchemaService.java#L11)):*
> ```Java
> import io.harness.ci.app.intfc.StageYamlSchemaService;
> 
> public interface IDPYamlSchemaService extends StageYamlSchemaService {}
> ```

Not needed. delete this class. 
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/yamlschema/IDPYamlSchemaServiceImpl.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/54597#-Nik2RSE4cV7yxXi0Xru:-Nik2RSE4cV7yxXi0Xrv:b-s0zrq4) ([raw file](https://github.com/harness/harness-core/blob/ec1a0020ecd6415fd2da1533f1c5f341aa102737/idp-service/src/main/java/io/harness/idp/pipeline/stages/yamlschema/IDPYamlSchemaServiceImpl.java#L46)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public class IDPYamlSchemaServiceImpl implements IDPYamlSchemaService {
> ```

Not needed. delete this class.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 16 of 18 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54597)* status: 40 file(s) to review. 1 of 2 approvals obtained.

**Review by jyotiraval — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]

**Review by vikyathharekal — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger review

**Comment by devesh-harness** [comment]
trigger uts

**Pull request merged**
