### PR TITLE
[fix]: [CDS-41652]: fixing validation for timeout on approval

### PR DESCRIPTION
**Pull request by lasdox**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36268)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36268)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36268)* status: :shipit: complete! ✓

___
*[`400-rest/src/test/java/software/wings/sm/states/ApprovalStateTest.java` line 791 at r1](https://reviewable.io/reviews/harness/harness-core/36268#-N98JNCfEoP98zvwrI8h:-N98JNCfEoP98zvwrI8i:bpzdzhr) ([raw file](https://github.com/harness/harness-core/blob/3490298f67dae9480970b557290a77d55ac3bad1/400-rest/src/test/java/software/wings/sm/states/ApprovalStateTest.java#L791)):*
> ```Java
>     final Map<String, Object> properties = new HashMap<>();
>     properties.put("timeoutMillis", "-543423");
>     assertThatThrownBy(() -> approvalState.parseProperties(properties)).isInstanceOf(InvalidRequestException.class);
> ```

You can add the assert for the message too.

**Review by srinivaswings — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36268)* status: :shipit: complete! ✓

**Review by srinivaswings — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36268)* status: :shipit: complete! ✓

**Pull request merged**
