### PR TITLE
techdebt: [PL-24569]: NG Audits Module and Notifications Module Code Reorganisation

### PR DESCRIPTION
**Pull request by ankit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32164)

### CODE REVIEW

**Review by karansiwach360 — DISMISSED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32164)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 7 of 32 files at r1, 492 of 492 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32164)* status: 492 file(s) to review. 1 of 2 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 32 files at r1, 492 of 492 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32164#-:-N-vt_KE1zdPem2aiJHx:bnfp4nl)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32164#-:-N-vvZJMByaBi4oXo6Qg:bnfp4nl)* status: :shipit: complete! ✓

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 7 of 32 files at r1, 492 of 492 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32164#-:-N-w1shIEGRx9AWJoM_W:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
