### PR TITLE
feat: [CCM-9901]: RBAC for Cloud Asset Governance

### PR DESCRIPTION
**Pull request by sahibaCCM**
## Describe your changes
Cloud Asset Governance Access Control.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)

### CODE REVIEW

**Comment by sahibaCCM** [comment]
trigger messagecheck

**Comment by sahibaCCM** [comment]
trigger messagecheck

**Comment by sahibaCCM** [comment]
trigger ss -X

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 810 at r2](https://reviewable.io/reviews/harness/harness-core/40168#-NH-0Ral1SOWKxQvfskf:-NH-0Ral1SOWKxQvfskg:b-v8n4lf) ([raw file](https://github.com/harness/harness-core/blob/b6304b65099fce80f5fbd97d44d17b5cdd92e42f/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L810)):*
> ```YAML
>         - ccm_loadBalancer_view
>         - ccm_overview_view
>         - ccm_policy_enforcement_view
> ```

Add view permissions in privileged-roles.yml as well.

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1265 at r2](https://reviewable.io/reviews/harness/harness-core/40168#-NH-1j6i0pYo8sQsFUbn:-NH-1j6i0pYo8sQsFUbo:b-jj9ugb) ([raw file](https://github.com/harness/harness-core/blob/b6304b65099fce80f5fbd97d44d17b5cdd92e42f/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1265)):*
> ```YAML
>   - identifier: ccm_policy_edit
>     name: Edit a CCM Governance Policy
>     status: ACTIVE
> ```

We can change the permission status to STAGING for now.
You can refer to this doc: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812887/Permissions+Management

**Review by svmav — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by svmav — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168#-:-NH9XSsO2bp9Z5EHC4Nm:bnfp4nl)* status: :shipit: complete! ✓

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: Some of the checks are too old. 1 change requests. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/40168#-NHP98C503UMOXVcrrTn:-NHP98C503UMOXVcrrTo:b-a9b7ri) ([raw file](https://github.com/harness/harness-core/blob/8c65af7cc01e1bd0164fedc7670bbb0c84a461c4/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L55)):*
> ```YAML
>       - ccm_loadBalancer_view
>       - ccm_folder_view
>       - ccm_loadBalancer_view
> ```

ccm_loadBalancer_view is duplicate. Please test locally or in PR env before review.



_Code quote:_
```YAML
ccm_loadBalancer_view
```

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: Some of the checks are too old. 1 change requests. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/40168#-NHP98C503UMOXVcrrTn:-NHP9sTT2LMEsJL6PY7T:b-x9hzfk) ([raw file](https://github.com/harness/harness-core/blob/8c65af7cc01e1bd0164fedc7670bbb0c84a461c4/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L55)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

ccm_loadBalancer_view is duplicate. Please test locally or in PR env before review.
</blockquote></details>

Also increment version no.

**Review by Jimit09Gandhi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/40168#-NHPAcCnEb1y16MhJkKB:-NHPAcCnEb1y16MhJkKC:b-cae6to) ([raw file](https://github.com/harness/harness-core/blob/8c65af7cc01e1bd0164fedc7670bbb0c84a461c4/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L114)):*
> ```YAML
>     permissionKey: deploymentfreeze
>   - identifier: CCM_GOVERNANCE
>     permissionKey: policy
> ```

Please rename permissionKey to specific name like ccmGovernancePolicy. Policy is generic.

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1269 at r4](https://reviewable.io/reviews/harness/harness-core/40168#-NHYD8Yv6KJ4X78bg_Fv:-NHYD8Yv6KJ4X78bg_Fw:b3abw42) ([raw file](https://github.com/harness/harness-core/blob/c4ea248f4dc3bf1e642c85f647ab7e59cc910f50/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1269)):*
> ```YAML
>     allowedScopeLevels:
>       - account
>   - identifier: ccm_policy_view
> ```

Please split these permissions to use different resource types. Having one singular resource type would cause issues in the UI. 
These can be grouped under Governance in the UI

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/40168#-NHYDVFv9ZEbL2m6xDuA:-NHYDVFv9ZEbL2m6xDuB:b8lpupt) ([raw file](https://github.com/harness/harness-core/blob/c4ea248f4dc3bf1e642c85f647ab7e59cc910f50/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L113)):*
> ```YAML
>   - identifier: DEPLOYMENTFREEZE
>     permissionKey: deploymentfreeze
>   - identifier: CCM_GOVERNANCE
> ```

Please register this in the platform service as well, custom resource group would not be able to consume this permission otherwise.

**Review by svmav — COMMENTED** [review]
> Reviewed 4 of 1794 files at r6, 2 of 1791 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40168)* status: 0 of 1 approvals obtained. Waiting on team(s): sto.

**Comment by sahibaCCM** [comment]
trigger codebasehash

**Pull request closed without merging**
