### PR TITLE
feat: [CDS-34084]: Support Remote backend configuration

### PR DESCRIPTION
**Pull request by jelenaHarness**
## Describe your changes

Support adding remote repo for Terraform backend configuration. 
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)

### CODE REVIEW

**Comment by jelenaHarness** [comment]
trigger publish-delegate

**Comment by jelenaHarness** [comment]
trigger publish-delegate

**Comment by jelenaHarness** [comment]
trigger publish-delegate

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1358 at r4](https://reviewable.io/reviews/harness/harness-core/35780#-N88jcJRBsrmnJpfivEQ:-N88jcJSA4mvvMrgdhA4:b-3n5h8r) ([raw file](https://github.com/harness/harness-core/blob/54716ac049dbd4f47192616287f1c370bdafd968/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1358)):*
> ```Java
>   private Map<String, String> extractBackendConfigs(ExecutionContext context, FileMetadata fileMetadata) {
>     Map<String, Object> rawBackendConfigs = null;
>     if (featureFlagService.isEnabled(TERRAFORM_REMOTE_BACKEND_CONFIG, context.getAccountId())) {
> ```

nit: condition can be optimized (if FF isNotEnabled or storeType==LOCAL_STORE_TYPE)

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 732 at r4](https://reviewable.io/reviews/harness/harness-core/35780#-N88mMS566YD9FMkLoKM:-N88mMS566YD9FMkLoKN:b-2ojcjs) ([raw file](https://github.com/harness/harness-core/blob/54716ac049dbd4f47192616287f1c370bdafd968/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L732)):*
> ```Java
>       List<NameValuePair> inlineBackendConfig = getBackendConfig().getInlineBackendConfig();
>       ensureNoDuplicateVars(inlineBackendConfig);
>       areVariablesValid = areVariablesValid && areKeysMongoCompliant(inlineBackendConfig);
> ```

Can inlineBackendConfig be null at this point?

**Review by markoharness — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 4 of 5 files at r3, 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)* status: 0 of 1 approvals obtained.

**Comment by jelenaHarness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1358 at r4](https://reviewable.io/reviews/harness/harness-core/35780#-N88jcJRBsrmnJpfivEQ:-N88r9aI4QW5AnovZxkh:bwxqxmm) ([raw file](https://github.com/harness/harness-core/blob/54716ac049dbd4f47192616287f1c370bdafd968/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1358)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

nit: condition can be optimized (if FF isNotEnabled or storeType==LOCAL_STORE_TYPE)
</blockquote></details>

The key is different, the second one is if the feature flag is not enabled, to preserve the old implementation

**Comment by jelenaHarness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 732 at r4](https://reviewable.io/reviews/harness/harness-core/35780#-N88mMS566YD9FMkLoKM:-N88roP26wI8FRGKedYt:b-bnmt1p) ([raw file](https://github.com/harness/harness-core/blob/54716ac049dbd4f47192616287f1c370bdafd968/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L732)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Can inlineBackendConfig be null at this point?
</blockquote></details>

yes, added a check

**Comment by jelenaHarness** [comment]
trigger ti3

**Review by markoharness — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 4 of 5 files at r3, 21 of 22 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)* status: :shipit: complete! ✓

**Comment by jelenaHarness** [comment]
trigger codebasehash

**Review by archit-harness — DISMISSED** [review]
> Reviewed 9 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 22 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)* status: 1 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
Approving from Delegate compatibility point of view

**Comment by yogesh-chauhan** [comment]
trigger codebasehash

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 4 of 5 files at r3, 19 of 22 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35780)* status: :shipit: complete! ✓

**Pull request merged**
