### PR TITLE
feat: [CDS-38371]: Pre flight checks for Service v2

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
While calculating internally referred entities, also check for Service ( apart from connectors )
We check for all connectors that are referred by the given service. 

`Ideally, we should also check for all secrets referred by those connectors also, but this PR does not include that change`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34937)

### CODE REVIEW

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34937)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34937)* status: :shipit: complete! ✓

___
*[`878-ng-common-utilities/src/main/java/io/harness/pms/rbac/InternalReferredEntityExtractor.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/34937#-N66bQtC1wCtiHAT2cAm:-N66bQtD17qL7jEK__Fo:b-syhgee) ([raw file](https://github.com/harness/harness-core/blob/b5977490f3a911d0f1149d79dc0999d4d250b99b/878-ng-common-utilities/src/main/java/io/harness/pms/rbac/InternalReferredEntityExtractor.java#L53)):*
> ```Java
>         EntityReferencesDTO entityReferencesDTO =
>             getResponseWithRetry(entitySetupUsageClient.listAllReferredUsagesBatch(
>                                      accountIdentifier, entityDetail, entry.getKey(), EntityType.SECRETS),
> ```

Isnt here current connectors are getting secrets already?



_Code quote:_
```Java
accountIdentifier, entityDetail, entry.getKey(), EntityType.SE
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34937)* status: 1 change requests. 1. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/pms/rbac/InternalReferredEntityExtractor.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/34937#-N66bQtC1wCtiHAT2cAm:-N66c8CG4qtDF6mibhWS:bmtkvg7) ([raw file](https://github.com/harness/harness-core/blob/b5977490f3a911d0f1149d79dc0999d4d250b99b/878-ng-common-utilities/src/main/java/io/harness/pms/rbac/InternalReferredEntityExtractor.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Isnt here current connectors are getting secrets already?
</blockquote></details>

We are getting secrets referred by Connectors (which are directly used in the pipeline)
However, for the given service, we only fetch the connectors referred by that service ( and not secrets referred by those connectors )

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34937)* status: :shipit: complete! ✓

**Pull request merged**
