### PR TITLE
[fix]: [CDS-38592]: Add support for git account level in CF endpoint

### PR DESCRIPTION
**Pull request by nassergonzalez**
## Describe your changes
[harness-core/AwsResourceServiceImpl.java at f643180e375ffa9f98ea264c84566a03807857ba · harness/harness-core](https://github.com/harness/harness-core/blob/f643180e375ffa9f98ea264c84566a03807857ba/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L125)  

The baseNgAccess was generated using the values from the AWS connector ref. The problem is that if that connector was created at org level, the projectID was dropped, which means that when we were able to retrieve the connectorinfo at [harness-core/AwsResourceServiceImpl.java at f643180e375ffa9f98ea264c84566a03807857ba · harness/harness-core](https://github.com/harness/harness-core/blob/f643180e375ffa9f98ea264c84566a03807857ba/125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java#L139)  it will be missing the projectID

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34165)

### CODE REVIEW

**Review by vlica-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34165)* status: :shipit: complete! ✓

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34165)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/34165#-N47xAuf5tzmcWJ0MVZf:-N47xAuf5tzmcWJ0MVZg:bro3egn) ([raw file](https://github.com/harness/harness-core/blob/980ee9202fd60a3a946dabbb9417e733aa4eee79/120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java#L77)):*
> ```Java
>         IdentifierRefHelper.getIdentifierRef(awsConnectorRef, accountIdentifier, orgIdentifier, projectIdentifier);
> 
> <<<<<<< HEAD
> ```

Conflict

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34165)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34165)* status: :shipit: complete! ✓

**Review by vlica-harness — APPROVED** [review]

**Pull request merged**
