### PR TITLE
feat: [FFM-2986]: Upgrading to the FF Java Server SDK version 1.1.4

### PR DESCRIPTION
**Pull request by milos85vasic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32319)

### CODE REVIEW

**Review by enver-bisevac — DISMISSED** [review]

**Comment by diptiman-adak** [comment]
Need to run `bazel run @unpinned_maven//:pin` and update main_maven_install.json file

**Review by enver-bisevac — APPROVED** [review]

**Comment by diptiman-adak** [comment]
trigger messagecheck

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32319)* status: :shipit: complete! ✓

**Comment by milos85vasic** [comment]
trigger messagecheck

**Pull request merged**
