### PR TITLE
feat: [CDS-34827]: Add error message to execution response

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Added the error message from execution to the execution response

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33852)

### CODE REVIEW

**Review by ershadalim — APPROVED** [review]

**Comment by Fernando-Dourado** [comment]
trigger ti0

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33852)* status: 1 file(s) to review. 1 change requests. 

___
*[`bazelrc.common` line 9 at r9](https://reviewable.io/reviews/harness/harness-core/33852#-N3t3cCtAdcjwhcoBzqd:-N3t3cCu0497RbF5MMNs:b-mchryo) ([raw file](https://github.com/harness/harness-core/blob/02b61b723834849d7b3c9f2d3d44176c753d365f/bazelrc.common#L9)):*
> ```
> build --host_javabase=@local_jdk//:jdk
> 
> build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
> ```

do we need that?

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33852)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 2 files at r8, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33852)* status: :shipit: complete! ✓

**Pull request merged**
