### PR TITLE
fix: [PL-20470]: check domain whitelist against account being logged into

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
While checking for domain whitelisting, we should check against the allowed domains for the account into which the user is being logged in. As of now, the domains are checked against the default account instead of the account being logged into.

Testing:
Test for user/password authentication method. For OAuth, it will be handled in a separate gateway PR.
- Whitelist a domain in the default account for a user:
1. [login with whitelisted email] Login without specifying account id in the link with a non-allowed domain-> login succeeds.
2. [login with non-whitelisted email] Login without specifying account id in the link with a non-allowed domain-> login fails.
3. [login with whitelisted email] Login using deep link of a different account(without domain whitelisting) -> login succeeds
4. [login with non-whitelisted email] Login using deep link of a different account(without domain whitelisting) -> login succeeds

- Whitelist a domain in a non-default account for a user:
1. [login with whitelisted email] Login without specifying account id in the link with a non-allowed domain-> login succeeds.
2. [login with non-whitelisted email] Login without specifying account id in the link with a non-allowed domain-> login succeeds.
3. [login with whitelisted email] Login using deep link of a different account(without domain whitelisting) -> login succeeds
4. [login with non-whitelisted email] Login using deep link of a different account(without domain whitelisting) -> login succeeds
5. [login with whitelisted email] Login using deep link of the account with domain whitelisting -> login succeeds
6. [login with non-whitelisted email] Login using deep link of the account with domain whitelisting -> login fails

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45307)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger ut1, ut6, ut2, ut4

**Comment by tiwaritejas** [comment]
trigger ut1, ut3, ut7, ut6

**Review by pbarapatre10 — APPROVED** [review]
Please test with SAML and 2FA enabled case, thanks

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45307#-:-NQxSf07125ien-L1NSt:b5rl8ta)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45307)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45307)* status: Some of the checks are too old.

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45307)* status: 1 file(s) to review.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45307)* status: :shipit: complete! ✓

**Pull request merged**
