### PR TITLE
feat: [PIE-7539]: Add policy evaluation outcome in stepResponse

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyOutcome.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/42429#-NLVMnyu6GYD635Li96P:-NLVMnyu6GYD635Li96Q:b2jythy) ([raw file](https://github.com/harness/harness-core/blob/127c8ada4833a19cf7de428c371562476f46f7d8/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyOutcome.java#L22)):*
> ```Java
> @Builder
> @OwnedBy(PIPELINE)
> @RecasterAlias("io.harness.utils.PolicyOutcome")
> ```

we should not change this. This will affect backward compatibility. 
cc - @archit-harness

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 35 files at r1, 1 of 1 files at r2, 24 of 24 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: 39 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PolicyOutcome.java` line 22 at r4](https://reviewable.io/reviews/harness/harness-core/42429#-NLVMnyu6GYD635Li96P:-NLVV4-v8lCu_3fYWZRU:b9cq81d) ([raw file](https://github.com/harness/harness-core/blob/127c8ada4833a19cf7de428c371562476f46f7d8/878-ng-common-utilities/src/main/java/io/harness/utils/PolicyOutcome.java#L22)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

we should not change this. This will affect backward compatibility. 
cc - @archit-harness 
</blockquote></details>

I've reverted the changes in recaster aliases.

**Review by archit-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: 40 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: 30 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 35 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: 24 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 20 of 24 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: :shipit: complete! ✓

**Review by namanvermah — APPROVED** [review]
> Reviewed 5 of 35 files at r1, 1 of 1 files at r2, 20 of 24 files at r3, 4 of 4 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 24 files at r3, 4 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 35 files at r1, 1 of 1 files at r2, 19 of 24 files at r3, 4 of 4 files at r4, 6 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42429)* status: :shipit: complete! ✓

**Pull request merged**
