### PR TITLE
[fix]: [DEL-2523]: Delegate connection ratio API returned invalid values

### PR DESCRIPTION
**Pull request by raghuAtWings**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30999)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger MessageMetadata-message_metadata

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30999)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
