### PR TITLE
[fix]: [SRM-11069]: fixing failed pipeline status

### PR DESCRIPTION
**Pull request by deepak-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36177)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36177)

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36177)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/36177#-N97DQBm-clLizg0wT5d:-N97DQBm-clLizg0wT5e:b-610mkg) ([raw file](https://github.com/harness/harness-core/blob/e6a1b01052cd137d1dbebe2a1a083e4c047a5e2f/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java#L129)):*
> ```Java
>                                   .analysisStatus(analysisStatus)
>                                   .isFinalState(true)
>                                   .isTerminated(analysisStatus.isTerminated())
> ```

how would the current state know if it's terminated status or not ? We aren't looking at the deployment analysis result in this. The decision for isTerminated has to happen in verificationJobInstance logProgress method after looking at the analysis
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisStatus.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/36177#-N97DuBQ7hR69dDi6mMA:-N97DuBR3uIVrenaSceB:b-qwmjv3) ([raw file](https://github.com/harness/harness-core/blob/e6a1b01052cd137d1dbebe2a1a083e4c047a5e2f/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/beans/AnalysisStatus.java#L43)):*
> ```Java
> 
>   public boolean isTerminated() {
>     return this.equals(AnalysisStatus.TERMINATED);
> ```

why this ? We aren't using something like this for other statuses no ?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/CanaryTimeSeriesAnalysisStateExecutor.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/36177#-N97EFma-kRkqAqNC-pi:-N97EFma-kRkqAqNC-pj:bklvir9) ([raw file](https://github.com/harness/harness-core/blob/e6a1b01052cd137d1dbebe2a1a083e4c047a5e2f/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/CanaryTimeSeriesAnalysisStateExecutor.java#L29)):*
> ```Java
> 
>   @Override
>   public AnalysisState handleSuccess(CanaryTimeSeriesAnalysisState analysisState) {
> ```

Based on the discussion yesterday, this should not be needed. Let us discuss offline and get back on this.

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36177)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 143 at r3](https://reviewable.io/reviews/harness/harness-core/36177#-N97r-dXA78T3uVrfv9m:-N97r-dXA78T3uVrfv9n:biwq1zj) ([raw file](https://github.com/harness/harness-core/blob/606d78694e8d2d4bf8d58ec89615805f60b5fcec/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L143)):*
> ```Java
>         hPersistence.createUpdateOperations(AnalysisOrchestrator.class)
>             .set(AnalysisOrchestratorKeys.analysisStateMachineQueue, Collections.EMPTY_LIST);
>     hPersistence.save(analysisStateMachines);
> ```

Will we end up in a race condition here ? Is it possible that some other thread comes and picks up the first state machine as we are marking things as terminated ? 



_Code quote:_
```Java
    List<AnalysisStateMachine> analysisStateMachines = orchestrator.getAnalysisStateMachineQueue();
    analysisStateMachines.forEach(analysisStateMachine -> analysisStateMachine.setStatus(AnalysisStatus.TERMINATED));
    Query<AnalysisOrchestrator> orchestratorQuery =
        hPersistence.createQuery(AnalysisOrchestrator.class)
            .filter(AnalysisOrchestratorKeys.verificationTaskId, verificationTaskId);
    UpdateOperations<AnalysisOrchestrator> updateOperations =
        hPersistence.createUpdateOperations(AnalysisOrchestrator.class)
            .set(AnalysisOrchestratorKeys.analysisStateMachineQueue, Collections.EMPTY_LIST);

    hPersistence.save(analysisStateMachines);
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java` line 197 at r3](https://reviewable.io/reviews/harness/harness-core/36177#-N97rD-29SRi6iW-mBfM:-N97rD-29SRi6iW-mBfN:bmstdxw) ([raw file](https://github.com/harness/harness-core/blob/606d78694e8d2d4bf8d58ec89615805f60b5fcec/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java#L197)):*
> ```Java
>     Instant endTime;
>     boolean isFinalState;
>     boolean isTerminated;
> ```

[Minor]: Rename this to `shouldTerminate` since it has not been terminated yet 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 309 at r3](https://reviewable.io/reviews/harness/harness-core/36177#-N97rzP60i0b_Gi5i0j9:-N97rzP7BJLNdqkHxmnD:b1upu8v) ([raw file](https://github.com/harness/harness-core/blob/606d78694e8d2d4bf8d58ec89615805f60b5fcec/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L309)):*
> ```Java
>                 .count()
>             == verificationTaskCount
>         || verificationJobInstance.getProgressLogs().stream().filter(progressLog -> progressLog.isTerminated()).count()
> ```

you can do `verificationJobInstance.getProgressLogs().stream().anyMatch(progressLog.isTerminated() == true)`

**Review by praveensugavanam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36177#-:-N98FkIw-5fnm3mzm_yW:bnfp4nl)* status: :shipit: complete! ✓

**Review by praveensugavanam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36177)* status: :shipit: complete! ✓

**Pull request merged**
