### PR TITLE
[feat]: [PL-25584]: ng ldap group sync operation

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 678 at r3](https://reviewable.io/reviews/harness/harness-core/35145#-N6rBJcf1aT4ulI0R1Dz:-N6rBJcf1aT4ulI0R1E-:bjcuztw) ([raw file](https://github.com/harness/harness-core/blob/2577538b5a36f2debb40c0f6984150dd12b956f4/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L678)):*
> ```Java
> 
>   @Override
>   @FeatureRestrictionCheck(FeatureRestrictionName.SAML_SUPPORT)
> ```

This needs to be fixed

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 24 files at r1, 19 of 19 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/contracts/src/main/java/io/harness/ldap/resource/NGLdapResource.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/35145#-N6qwuLwBJyaUZ663E31:-N6qwuLwBJyaUZ663E32:beda93o) ([raw file](https://github.com/harness/harness-core/blob/e5cc9098e45aaa03f2d3d5cfe34a9b9084e1fac8/120-ng-manager/modules/ldap/contracts/src/main/java/io/harness/ldap/resource/NGLdapResource.java#L145)):*
> ```Java
> 
>   @GET
>   @Path("/sync-sso-group")
> ```

it should be named sync-group

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/contracts/src/main/java/io/harness/ldap/resource/NGLdapResource.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/35145#-N6qwuLwBJyaUZ663E31:-N6rRXfW5P3sPfwZ3P_7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5cc9098e45aaa03f2d3d5cfe34a9b9084e1fac8/120-ng-manager/modules/ldap/contracts/src/main/java/io/harness/ldap/resource/NGLdapResource.java#L145)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

it should be named sync-group
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/35145#-N6rAWUcCih5yTMkrf6L:-N6rRZLm-zjXEScoUdzf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41e545c77030c48200d285e91139e96035747168/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L54)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

break down this method into multiple small methods
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 678 at r3](https://reviewable.io/reviews/harness/harness-core/35145#-N6rBJcf1aT4ulI0R1Dz:-N6rRbgx1JhLwrpTRbrE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2577538b5a36f2debb40c0f6984150dd12b956f4/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L678)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This needs to be fixed 
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by ujjawal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: 26 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/35145#-N7FWVsh2wlNoxUoFac_:-N7FWVsh2wlNoxUoFaca:bg5vtpu) ([raw file](https://github.com/harness/harness-core/blob/8928d177b0724f6dbb5cbf6a026bfd837a367ccf/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L65)):*
> ```Java
>   }
> 
>   private void reconcileUserGroupWithLdapGroup(
> ```

Please add more precise logs in this method. As it will help us in debugging

**Comment by pbarapatre10** [comment]
trigger ft1

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: 26 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/35145#-N7FWVsh2wlNoxUoFac_:-N7Fs2AlAS0kawoJD_Ni:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8928d177b0724f6dbb5cbf6a026bfd837a367ccf/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/NGLdapGroupSyncHelper.java#L65)):*
<details><summary><i>Previously, ujjawal-harness (Ujjawal Prasad) wrote…</i></summary><blockquote>

Please add more precise logs in this method. As it will help us in debugging
</blockquote></details>

Done.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 8 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: 26 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 24 files at r1, 10 of 19 files at r2, 1 of 4 files at r4, 8 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145#-:-N7GfWHm0jLSjjvGzew5:bnfp4nl)* status: 1. unresolved discussions.

**Review by ujjawal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: :shipit: complete! ✓

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145#-:-N7Gffo46T1Z7boZ55Fy:bnfp4nl)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java` line 130 at r6](https://reviewable.io/reviews/harness/harness-core/35145#-N7HpgSG81vs5G2pT-tX:-N7HpgSG81vs5G2pT-tY:bjbnb0o) ([raw file](https://github.com/harness/harness-core/blob/00b8dae55578193c4bffdd9961bb8aed45e967c1/950-delegate-tasks-beans/src/main/java/software/wings/beans/TaskType.java#L130)):*
> ```Java
>   NG_LDAP_SEARCH_GROUPS(TaskGroup.LDAP),
>   NG_LDAP_TEST_CONN_SETTINGS(TaskGroup.LDAP),
>   NG_LDAP_GROUPS_SYNC(TaskGroup.LDAP),
> ```

please test with older delegate. you should see an error that the this task is not supported. Also please add this enum in the end.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 24 files at r1, 7 of 19 files at r2, 1 of 4 files at r4, 6 of 8 files at r5, 2 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 5 of 24 files at r1, 7 of 19 files at r2, 1 of 4 files at r4, 6 of 8 files at r5, 2 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35145)* status: :shipit: complete! ✓

**Pull request merged**
