### PR TITLE
[feat]: [CVS-9003]: added sorting of txn/metric pairs & resolved duplicate counts

### PR DESCRIPTION
**Pull request by kapil-harness**
…unts

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
Screenshot 2022-01-28 at 9 05 17 PM

**Review by kjoshi12345 — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/DeploymentTimeSeriesAnalysisService.java, line 27 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWc2TkBrIyU4Xb9ACk:-MuWc2TkBrIyU4Xb9ACl:b-b7y780) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/DeploymentTimeSeriesAnalysisService.java#L27)):*
> ```Java
>   TransactionMetricInfoSummaryPageDTO getMetrics(String accountId, String verificationJobInstanceId,
>       DeploymentTimeSeriesAnalysisFilter deploymentTimeSeriesAnalysisFilter, PageParams pageParams);
>   List<TransactionMetricInfo> getMetricsWithoutFiltersAndPagination(String accountId, String verificationJobInstanceId);
> ```

we can just call it getTransactionMetricInfo
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/BuilderFactory.java, line 207 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWchCO-BQpDJVo7CQW:-MuWchCO-BQpDJVo7CQX:b-k5do1w) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/test/java/io/harness/cvng/BuilderFactory.java#L207)):*
> ```Java
>   }
> 
>   public VerificationJobInstanceBuilder verificationJobInstanceBuilderWithMultipleCVConfigs() {
> ```

we don't want to have specific methods like this in builder factory. You can use default builder and override only cvConfigMap in test.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java, line 126 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWdVI91t52Kuz-0oTq:-MuWdVI91t52Kuz-0oTr:b-q9i22a) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java#L126)):*
> ```Java
>     envIdentifier = builderFactory.getContext().getEnvIdentifier();
>     FieldUtils.writeField(deploymentTimeSeriesAnalysisService, "nextGenService", nextGenService, true);
>     FieldUtils.writeField(verificationJobInstanceAnalysisService, "deploymentTimeSeriesAnalysisService",
> ```

why this override?
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java, line 838 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWdkmL6SGXggyLVhfM:-MuWdkmL6SGXggyLVhfN:b-3xibzl) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java#L838)):*
> ```Java
>   private VerificationJobInstance createVerificationJobInstanceWithMultipleCVConfigs(VerificationJob verificationJob) {
>     return builderFactory.verificationJobInstanceBuilderWithMultipleCVConfigs()
>         .deploymentStartTime(Instant.now())
> ```

please use fix start time instead of Instant.now(), we want fix input in our tests for reproduction and reducing flakiness.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/DeploymentTimeSeriesAnalysisService.java, line 27 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWc2TkBrIyU4Xb9ACk:-MuWhHu2-dOTaQWequMk:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/DeploymentTimeSeriesAnalysisService.java#L27)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we can just call it getTransactionMetricInfo
</blockquote></details>

done
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java, line 126 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWdVI91t52Kuz-0oTq:-MuWieQn7qCSIB1rzD71:b-s0066s) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java#L126)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why this override?
</blockquote></details>

without this override we get a specific error like "cannot mock NextGenService" hence this is required.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java, line 838 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWdkmL6SGXggyLVhfM:-MuWib7JACtpYOAraHGl:bpid3bq) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java#L838)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please use fix start time instead of Instant.now(), we want fix input in our tests for reproduction and reducing flakiness. 
</blockquote></details>

its not required so removed it.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/BuilderFactory.java, line 207 at r2](https://reviewable.io/reviews/harness/harness-core/30326#-MuWchCO-BQpDJVo7CQW:-MuWicMk43kNRAQKLRd0:b-oicyv6) ([raw file](https://github.com/harness/harness-core/blob/09585d5239604c6e994855d7988c08cc984a9ecd/300-cv-nextgen/src/test/java/io/harness/cvng/BuilderFactory.java#L207)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we don't want to have specific methods like this in builder factory. You can use default builder and override only cvConfigMap in test.
</blockquote></details>

removed it.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)* status: 1 change requests. 4. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)* status: 1 change requests. 4. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)* status: 4. unresolved discussions.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326#-:-MuageBZACNJsl5znfgv:bnfp4nl)* status: 1. unresolved discussions.

**Review by kjoshi12345 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30326)* status: :shipit: complete! ✓

**Pull request closed without merging**
