### PR TITLE
techdebt: [CDS-77744]: Optimise nodeExecution calls for expression playground

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
Changes done:
- Removed the call to fetch all nodes but rather bring only leaf nodes and that too if that step, stage has expressions.

How it will help us?
- Will reduce the memory footprint of pipeline-service
- The data transfer from mongo will be reduced.

Testing done
- Created a pipeline with a strategy on stage and some stage expression on stage variables. 
        -- It is resolving as expected
- Created a pipeline with normal stage and step, along with some strategy on another step.
       -- Resolving as expected.
  

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52841)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 1107 at r1](https://reviewable.io/reviews/harness/harness-core/52841#-NeIkY7b9QMooW5IwZ3H:-NeIkY7b9QMooW5IwZ3I:b-9lqsgk) ([raw file](https://github.com/harness/harness-core/blob/0a582c0d0aaf9a076bc0b8f664c5558387d61e6f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L1107)):*
> ```Java
>   public CloseableIterator<NodeExecution> fetchAllLeavesUsingPlanExecutionId(
>       String planExecutionId, Set<String> fieldsToBeIncluded) {
>     Criteria criteria = Criteria.where(NodeExecutionKeys.planExecutionId)
> ```

Add comment for which index is being used.
Also executionStats in comments

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52841)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]

**Comment by sahilhindwani-harness** [comment]
trigger review

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
