### PR TITLE
techdebt: [CDS-39619]: Service Override and Infrastructure Def audit trail support

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36682)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
Changes are in Progress

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36682)

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/EnvironmentEventHandler.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/36682#-NBGjqBN96i2Pd_Oc1vK:-NBGjqBN96i2Pd_Oc1vL:b-f2ft4h) ([raw file](https://github.com/harness/harness-core/blob/9e787791d2a8f5cea9c473199b98b69791471c53/120-ng-manager/src/main/java/io/harness/ng/core/outbox/EnvironmentEventHandler.java#L53)):*
> ```Java
>   private final AuditClientService auditClientService;
> 
>   private final String OLD_YAML = "oldYaml";
> ```

nit: lets make these static



_Code quote:_
```Java
private final String OLD_YAML
```

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36682)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentCreateEvent.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/36682#-NBH-QQMCeWyQ8tAQcj9:-NBH-QQMCeWyQ8tAQcjA:bzat380) ([raw file](https://github.com/harness/harness-core/blob/9e787791d2a8f5cea9c473199b98b69791471c53/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentCreateEvent.java#L34)):*
> ```Java
>   private String orgIdentifier;
>   private String projectIdentifier;
>   private InfrastructureEntity infrastructure;
> ```

Shouldn't we also add ServiceOverrideEntity here?

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 218 at r3](https://reviewable.io/reviews/harness/harness-core/36682#-NBH5q9a78cGxyVguJ3L:-NBH5q9a78cGxyVguJ3M:b-qkvwzr) ([raw file](https://github.com/harness/harness-core/blob/9e787791d2a8f5cea9c473199b98b69791471c53/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L218)):*
> ```Java
> 
>   @Override
>   public boolean deleteAllInEnv(
> ```

@yogesh-chauhan do we need to audit these calls also (I mean the methods which are getting called only in downstream type deletion like here?



_Code snippet:_
```Java
  private void processDownstreamDeletions(
      String accountId, String orgIdentifier, String projectIdentifier, String environmentIdentifier) {
    processQuietly(()
                       -> infrastructureEntityService.forceDeleteAllInEnv(
                           accountId, orgIdentifier, projectIdentifier, environmentIdentifier));
    processQuietly(
        () -> clusterService.deleteAllFromEnv(accountId, orgIdentifier, projectIdentifier, environmentIdentifier));
    processQuietly(()
                       -> serviceOverrideService.deleteAllInEnv(
                           accountId, orgIdentifier, projectIdentifier, environmentIdentifier));
  }
```

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36682)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36682)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/EnvironmentEventHandler.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/36682#-NBGjqBN96i2Pd_Oc1vK:-NBHtOYpCz26sb6rglAy:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9e787791d2a8f5cea9c473199b98b69791471c53/120-ng-manager/src/main/java/io/harness/ng/core/outbox/EnvironmentEventHandler.java#L53)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: lets make these static
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentCreateEvent.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/36682#-NBH-QQMCeWyQ8tAQcj9:-NBHtQd73fe0vUkgzcIV:bdd4t65) ([raw file](https://github.com/harness/harness-core/blob/9e787791d2a8f5cea9c473199b98b69791471c53/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/EnvironmentCreateEvent.java#L34)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Shouldn't we also add ServiceOverrideEntity here?
</blockquote></details>

@tchaurasiya ServiceOverrideEntity is not present in EnvironmentCreateEvent class because we are showing the audit logs of Service Override inside Env Update only 
same for Infrastructure

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 218 at r3](https://reviewable.io/reviews/harness/harness-core/36682#-NBH5q9a78cGxyVguJ3L:-NBLKe9UER98B2K3y2aE:b-upaovp) ([raw file](https://github.com/harness/harness-core/blob/9e787791d2a8f5cea9c473199b98b69791471c53/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L218)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

@yogesh-chauhan do we need to audit these calls also (I mean the methods which are getting called only in downstream type deletion like here?
</blockquote></details>

I think its okay to skip because when a project is deleted, its very clear that its children will also be deleted.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36682)* status: :shipit: complete! ✓

**Pull request merged**
