### PR TITLE
feat: [PL-25258]: git sdk changes

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33364)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364#-:-N2UQPTq7po0tsH3bW8y:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364#-:-N2Uq3DQEn-UhCrRtV2X:bnfp4nl)* status: :shipit: complete! ✓

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/33364#-N2W75ul8r0N2z8I8ZlY:-N2W75ul8r0N2z8I8ZlZ:b-gicmqo) ([raw file](https://github.com/harness/harness-core/blob/1f475d9b522ba6ed0d4ad187f54e159e4a43279b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L177)):*
> ```Java
> 
>     if (isFailureResponse(updateFileResponse.getStatusCode())) {
>       log.error("Git SDK updateFile Failure: {}", updateFileResponse);
> ```

Is the log context will have scope details?
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 182 at r2](https://reviewable.io/reviews/harness/harness-core/33364#-N2W7CFp-K1fGvUGPOBv:-N2W7CFp-K1fGvUGPOBw:blr0gwj) ([raw file](https://github.com/harness/harness-core/blob/1f475d9b522ba6ed0d4ad187f54e159e4a43279b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L182)):*
> ```Java
>     }
> 
>     return ScmUpdateFileGitResponse.builder().gitMetaData(getGitMetaData(updateFileResponse.getGitMetaData())).build();
> ```

what is this getGitMetaData() method does, as it is already taking gitMetadata as input.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 182 at r2](https://reviewable.io/reviews/harness/harness-core/33364#-N2W7CFp-K1fGvUGPOBv:-N2W83d5E5JtIrUzMwl7:b-id1n5d) ([raw file](https://github.com/harness/harness-core/blob/1f475d9b522ba6ed0d4ad187f54e159e4a43279b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L182)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

what is this getGitMetaData() method does, as it is already taking gitMetadata as input.
</blockquote></details>

one is java pojo and other is grpc proto. Thus it does the mapping.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/33364#-N2W75ul8r0N2z8I8ZlY:-N2W89jh-vRNhelkqU3s:b-3qbhru) ([raw file](https://github.com/harness/harness-core/blob/1f475d9b522ba6ed0d4ad187f54e159e4a43279b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L177)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Is the log context will have scope details?
</blockquote></details>

It would depend. Currently, it will have if consumer service does it otherwise not. We already have separate ticket to focus on logging: https://harness.atlassian.net/browse/PL-25049

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 182 at r2](https://reviewable.io/reviews/harness/harness-core/33364#-N2W7CFp-K1fGvUGPOBv:-N2W8je06U6QeQvsJziL:b-xekm5j) ([raw file](https://github.com/harness/harness-core/blob/1f475d9b522ba6ed0d4ad187f54e159e4a43279b/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L182)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

one is java pojo and other is grpc proto. Thus it does the mapping.
</blockquote></details>

Then please change this method name to mapper or something like that, it's really confusing

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 182 at r2](https://reviewable.io/reviews/harness/harness-core/33364#-N2W7CFp-K1fGvUGPOBv:-N2WBpMZCx3i2rcaIkEj:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/28b0bd8ec4ec736bffda4e0f247899826963344e/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L182)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Then please change this method name to mapper or something like that, it's really confusing
</blockquote></details>

done

**Review by bhavya181 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364#-:-N2WYneb85nDrIiKXkz0:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger ti3

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364#-:-N2ZzsQ65j_PtHGR9Slm:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by depanshu-dhiman — APPROVED** [review]

**Review by kapil-harness — APPROVED** [review]
> Reviewed 12 of 15 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33364)* status: :shipit: complete! ✓

**Pull request merged**
