### PR TITLE
fix: [CDS-73216]: adding changes for updating sort order for pipeline views

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes

Execution
image

Pipelines

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)

### CODE REVIEW

**Comment by ankittiwari-harness** [comment]
trigger uts

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 291 at r1](https://reviewable.io/reviews/harness/harness-core/49981#-NZPKUvTERlERyyetxzN:-NZPKUvTERlERyyetxzO:b-3yu732) ([raw file](https://github.com/harness/harness-core/blob/71b75143c6562f33f6633a56086faa4916725680/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L291)):*
> ```Java
>                 .ascRangeField(PlanExecutionSummaryKeys.isChildPipeline)
>                 .collation(
>                     Collation.builder().locale(CollationLocale.ENGLISH).strength(CollationStrength.SECONDARY).build())
> ```

Here sorting is there for status, so i don't think it needs collation
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/49981#-NZPKiNl7UY9ji88b-XU:-NZPKiNl7UY9ji88b-XV:b1sa805) ([raw file](https://github.com/harness/harness-core/blob/71b75143c6562f33f6633a56086faa4916725680/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L140)):*
> ```Java
>                  .ascRangeField(PipelineEntityKeys.identifier)
>                  .collation(
>                      Collation.builder().locale(CollationLocale.ENGLISH).strength(CollationStrength.SECONDARY).build())
> ```

I dont think here collation is needed

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)* status: :shipit: complete! ✓

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 291 at r1](https://reviewable.io/reviews/harness/harness-core/49981#-NZPKUvTERlERyyetxzN:-NZQ7dsL0zIWcZH6qHXz:bg7c1g5) ([raw file](https://github.com/harness/harness-core/blob/71b75143c6562f33f6633a56086faa4916725680/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L291)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Here sorting is there for status, so i don't think it needs collation
</blockquote></details>

handed in rev
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/49981#-NZPKiNl7UY9ji88b-XU:-NZQ7fiLB5p8nzkwSfS5:b-cn6cdr) ([raw file](https://github.com/harness/harness-core/blob/71b75143c6562f33f6633a56086faa4916725680/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L140)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I dont think here collation is needed
</blockquote></details>

handled in rev

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49981)* status: :shipit: complete! ✓

**Comment by ankittiwari-harness** [comment]
trigger review

**Pull request merged**
