### PR TITLE
feat: [PIE-9395]: added unit tests

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46442)

### CODE REVIEW

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 8 of 51 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46442)* status: 51 file(s) to review. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/SCMGitAccessToProviderMapper.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/46442#-NTloj705nDrRPk2IH1Q:-NTloj705nDrRPk2IH1R:bh1fpu1) ([raw file](https://github.com/harness/harness-core/blob/e9deab8a7e31dc4431ceef24529d17f6d313442d/952-scm-java-client/src/main/java/io/harness/impl/scm/SCMGitAccessToProviderMapper.java#L69)):*
> ```Java
> 
>   private String getToken(SecretRefData tokenRef) {
>     return scmGitProviderHelper.getToken(tokenRef);
> ```

We don't have nay null check(may have been handled either in the method called or the method calling this method), nor any other functionality over here in this method we can remove this method and use "scmGitProviderHelper.getToken(tokenRef)" in the place where this method is being called.

**Comment by shalini-agr** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/SCMGitAccessToProviderMapper.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/46442#-NTloj705nDrRPk2IH1Q:-NTlvTDMDaB2W8V2lFII:b-3qbjpb) ([raw file](https://github.com/harness/harness-core/blob/e9deab8a7e31dc4431ceef24529d17f6d313442d/952-scm-java-client/src/main/java/io/harness/impl/scm/SCMGitAccessToProviderMapper.java#L69)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

We don't have nay null check(may have been handled either in the method called or the method calling this method), nor any other functionality over here in this method we can remove this method and use "scmGitProviderHelper.getToken(tokenRef)" in the place where this method is being called.
</blockquote></details>

abstracted this out in a method so that in the future if we want to modify anything in the way we get token, we can just do it in one place.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 51 of 51 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46442)* status: 43 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
