### PR TITLE
[feat]: [CDS-59517]: validator framework for overrides v2

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

have added the request validators for service override v2 apis

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47327)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47327)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorService.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUe7HBR4Q1Ps9wE0a8L:-NUe7HBR4Q1Ps9wE0a8M:b539eya) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorService.java#L23)):*
> ```Java
> 
>   @NonNull String generateServiceOverrideIdentifier(@NonNull NGServiceOverridesEntity serviceOverridesEntity);
> ```

nit,

ValidatorService generating things..sounds odd.

Either make it just ServiceOverrideService or move this method in a diff. service.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUe8phyEbQ2FCmJRZgV:-NUe8phz5qrq5_JPLAvw:b-udiy26) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java#L62)):*
> ```Java
>   }
> 
>   public void validateEnvironmentRBAC(@NotNull Environment environment) {
> ```

I see many public methods without override annnotation. Is this really meant for public use or private and visible for testing?

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47327)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvironmentNGAccessControlCheckHelper.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUe9oN563mMSvkLWSJM:-NUe9oN563mMSvkLWSJN:b-irhyjv) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvironmentNGAccessControlCheckHelper.java#L63)):*
> ```Java
>                              .resourceScope(resourceScope)
>                              .resourceType(ENVIRONMENT)
>                              .build());
> ```

nit: you can use List.of(item1, item2) to return an immutable list here

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvironmentNGAccessControlCheckHelper.java` line 70 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUc0ZP6CtyaJECm-wVg:-NUc0ZP76f_rMAw0K5--:b-ejcqxt) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvironmentNGAccessControlCheckHelper.java#L70)):*
> ```Java
>   private Map<String, String> getEnvironmentAttributesMap(String environmentType) {
>     Map<String, String> environmentAttributes = new HashMap<>();
>     environmentAttributes.put("type", environmentType);
> ```

lets extract this out as a constant

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvServiceOverrideValidator.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUc0nkWBNMMY7DxiU7p:-NUc0nkWBNMMY7DxiU7q:b-6f3idh) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/EnvServiceOverrideValidator.java#L23)):*
> ```Java
> 
>   @Override
>   public String generateServiceOverrideIdentifier(NGServiceOverridesEntity serviceOverridesEntity) {
> ```

validator is generating the identifier also, do we need to re-name the class or have a new class ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUeARDh1u5B8P4SxF3I:-NUeARDh1u5B8P4SxF3J:b-kb434m) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java#L101)):*
> ```Java
>     try {
>       if (isNotEmpty(requestDTO.getProjectIdentifier())) {
>         Preconditions.checkArgument(isNotEmpty(requestDTO.getOrgIdentifier()),
> ```

do we need to use preconditions and then catch the exception thrown ? can we not just have a simple check and throw invalidRequestException ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java` line 95 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUeAbK_-jNeLGHiZ8-Q:-NUeAbK_-jNeLGHiZ8-R:bak4pq) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java#L95)):*
> ```Java
>     if (dto.getSpec() == null) {
>       throw new InvalidRequestException("Override spec is not provided in request");
>     }
> ```

eventually, can we move to schema validation instead of these checks ?

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorService.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUe7HBR4Q1Ps9wE0a8L:-NUeb0Fw16A9G-CV-oPW:b-vskbje) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorService.java#L23)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit,

ValidatorService generating things..sounds odd.

Either make it just ServiceOverrideService or move this method in a diff. service.
</blockquote></details>

Its main work to make some decision based on request parameters.
Moving only generating name code out was causing same pattern classes to be duplicated.
As of now i renamed the class. If later we find more extensibility is required, we can move that logic easily.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47327)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUe8phyEbQ2FCmJRZgV:-NUecTwW9CMuXUV4UbxP:bygu01l) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java#L62)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

I see many public methods without override annnotation. Is this really meant for public use or private and visible for testing?
</blockquote></details>

Thanks Vaibhav, Some refactoring was remaining on my side ,have done that.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java` line 95 at r3](https://reviewable.io/reviews/harness/harness-core/47327#-NUeAbK_-jNeLGHiZ8-Q:-NUehf-N-FcrjQdNLSUg:bq5b4tw) ([raw file](https://github.com/harness/harness-core/blob/4a431de3d370f09e9e7254a3ce2466067938e933/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/ServiceOverrideValidatorServiceImpl.java#L95)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

eventually, can we move to schema validation instead of these checks ?
</blockquote></details>

There is no yaml involved here, are suggesting javax validation?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47327)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47327)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
trigger review

**Pull request merged**
