### PR TITLE
fix: [DEL-4588]: API to fetch watcher/Delegate version from ring

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
This change is to introduce a public api (without auth) to fetch Delegate and Watcher version from ring.
There has been ask from multiple folks to figure out delegate/watcher version in any environment.
To avoid DB call in every rest api call, introduced a cache with 5min TTL, we can fetch ring information once in every 5mins.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35984)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35984)

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35984)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/35984#-N8ZFsMBEgOVutoTSB-n:-N8ZFsMC-3hPtueHRuwv:b-boqd8a) ([raw file](https://github.com/harness/harness-core/blob/a1729b8dc49fba36db48128c07ef26e9f847a18d/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L49)):*
> ```Java
>   public List<String> getDelegateVersionsForRing(String ringName, boolean skipCache) {
>     if (!skipCache) {
>       DelegateRing ring = delegateRingCache.getIfPresent(ringName);
> ```

I think your cache will never get populated this way. You either need to provide a CacheLoader while building the cache, or use `get()` with mapping function which would automatically load on cache miss. You would also probably going to need a separate cache for watcher versions.
___
*[`400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/35984#-N8ZG9rSD1ddllUX_XBo:-N8ZG9rT9qxUgPcxFpWt:b-pdoo1z) ([raw file](https://github.com/harness/harness-core/blob/a1729b8dc49fba36db48128c07ef26e9f847a18d/400-rest/src/main/java/io/harness/delegate/service/intfc/DelegateRingService.java#L19)):*
> ```Java
>   List<String> getDelegateVersions(String accountId);
> 
>   List<String> getDelegateVersionsForRing(String ringName, boolean skipCache);
> ```

I think it's OK to remove the boolean and have both of these methods to always use Cache as long as delegate/watcher check timeout is greater than cache expiry. It's not critical for us that delegate updates to the ring version as soon as ring is changed. It's ok to have 5-10min delay (or even longer like few hours, doesn't really matter).

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35984)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/35984#-N8ZFsMBEgOVutoTSB-n:-N8ZH8je-Dkp2FIILgZB:b-1r05su) ([raw file](https://github.com/harness/harness-core/blob/a1729b8dc49fba36db48128c07ef26e9f847a18d/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateRingServiceImpl.java#L49)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think your cache will never get populated this way. You either need to provide a CacheLoader while building the cache, or use `get()` with mapping function which would automatically load on cache miss. You would also probably going to need a separate cache for watcher versions.
</blockquote></details>

Ok, just relized you cache Ring object, not string. So that's fine, no separate cache needed, but I still think it's better to load cache values automatically and always use cache.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35984)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35984)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35984)* status: :shipit: complete! ✓

**Pull request merged**
