### PR TITLE
feat: [CDS-38470]: NG Infra/clusters casade delete upon project/env deletion

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
- hard delete infra/cluster entities when env is deleted
- hard delete infra/cluster entities when project is deleted
- fix bug wrt serialization of allowSimulatenousDeployments flag
- remove cluster update API since that is not needed
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34232)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34232)* status: 12 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDefinitionConfig.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/34232#-N4O4cDT44Uw6b4pN3fk:-N4O4cDU9KFfDH4RtMfI:b-bolrsw) ([raw file](https://github.com/harness/harness-core/blob/8588814a9f38e0d62b1eacbe65718c9f2a975b7b/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDefinitionConfig.java#L61)):*
> ```Java
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) String description;
>   Map<String, String> tags;
>   @ApiModelProperty(dataType = SwaggerConstants.BOOLEAN_CLASSPATH) ParameterField<Boolean> allowSimultaneousDeployments;
> ```

yaml serialisation will not work because yaml contains a boolean not a Parameter field. hence, converted to boolean since this field is a fixed one

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34232)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/34232#-N4QZH959Nto8ipcxUYb:-N4QZH959Nto8ipcxUYc:blgqisu) ([raw file](https://github.com/harness/harness-core/blob/f9e98945d737ad04308bd5b1f0ef3ef7247beeda/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L207)):*
> ```Java
>     return Failsafe.with(transactionRetryPolicy).get(() -> transactionTemplate.execute(status -> {
>       DeleteResult deleteResult = infrastructureRepository.delete(criteria);
>       return deleteResult.wasAcknowledged() && deleteResult.getDeletedCount() > 0;
> ```

Synced and decided that unless an exception is thrown from the API, we will consider the deletion as successful. processQuietly will handle this.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 220 at r2](https://reviewable.io/reviews/harness/harness-core/34232#-N4QZreg4602gxLZid3C:-N4QZreg4602gxLZid3D:bbcb7rz) ([raw file](https://github.com/harness/harness-core/blob/f9e98945d737ad04308bd5b1f0ef3ef7247beeda/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L220)):*
> ```Java
>     return Failsafe.with(transactionRetryPolicy).get(() -> transactionTemplate.execute(status -> {
>       DeleteResult deleteResult = infrastructureRepository.delete(criteria);
>       if (!deleteResult.wasAcknowledged() || deleteResult.getDeletedCount() < 1) {
> ```

For project with no infra, we should not throw exception here

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34232)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/34232#-N4QZH959Nto8ipcxUYb:-N4Qj7Wy-Gr3Z_Mkx5GD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9e98945d737ad04308bd5b1f0ef3ef7247beeda/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L207)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Synced and decided that unless an exception is thrown from the API, we will consider the deletion as successful. processQuietly will handle this.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 220 at r2](https://reviewable.io/reviews/harness/harness-core/34232#-N4QZreg4602gxLZid3C:-N4QkyX_1F2JJLClYpec:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9e98945d737ad04308bd5b1f0ef3ef7247beeda/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L220)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

For project with no infra, we should not throw exception here
</blockquote></details>

Done.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34232)* status: :shipit: complete! ✓

**Pull request merged**
