### PR TITLE
feat: [PL-32392]: change invite email templates

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
change invite email templates

This doc contains the screenshots of current mail templates https://docs.google.com/document/d/1uSJKvpdJrZNXgIiyeLTfMwCC0WyyPU3WdM3-LSJMWyk

tested locally all the templates both in CG and NG, these are the templates - 

**invite mail -**

Screenshot 2023-05-15 at 8 23 09 PM

**SSO AutoAccept enabled -** 

Screenshot 2023-05-15 at 8 23 26 PM

**2FA autoAccept Enabled-**

Screenshot 2023-05-15 at 8 23 45 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47873)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger feature-build

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1236 at r1](https://reviewable.io/reviews/harness/harness-core/47873#-NVhnnkBAWu1tHLEdNbo:-NVhnnkC7SHotxNz49KD:b-r0xydl) ([raw file](https://github.com/harness/harness-core/blob/a9b5e4b2780260fae63624f21f679f4aac5d15a4/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1236)):*
> ```Java
> 
>     SSOSettings ssoSettings = getSSOSettings(account);
>     model.put("ssoUrl", checkGetDomainName(account, ssoSettings.getUrl()));
> ```

Why are we removing sso Url?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47873)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1236 at r1](https://reviewable.io/reviews/harness/harness-core/47873#-NVhnnkBAWu1tHLEdNbo:-NVho8Ra9AVn1uiopum1:b-1da6wn) ([raw file](https://github.com/harness/harness-core/blob/a9b5e4b2780260fae63624f21f679f4aac5d15a4/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1236)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Why are we removing sso Url?
</blockquote></details>

kapil said its not required in mail.

**Review by rashminandasahoo — APPROVED** [review]

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47873)* status: 7 file(s) to review. 1. unresolved discussions.

**Comment by bhavya181** [comment]
trigger uts

**Review by shashank-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47873)* status: 3 file(s) to review.

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger ut2

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47873)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
