### PR TITLE
fix:[SRM-14267]: Log feedback bug fixes.

### PR DESCRIPTION
**Pull request by naveen-harness**
## Describe your changes

- Fetch serviceIdentifier and envIdentifier from verificationJobInstance as these won't be sent by UI. 
- Fix logfeedback list params
- Use DeploymentLogFeedbackState in handleFinalStatuses

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45098)

### CODE REVIEW

**Comment by naveen-harness** [comment]
trigger messagecheck

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45098)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/LogFeedbackServiceImplTest.java` line 330 at r3](https://reviewable.io/reviews/harness/harness-core/45098#-NQd57HJ8p83TvuDOguM:-NQd57HJ8p83TvuDOguN:b-7vckk) ([raw file](https://github.com/harness/harness-core/blob/730683a6befc9f704cf2a6c0ee5fa9b38135bce5/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/LogFeedbackServiceImplTest.java#L330)):*
> ```Java
>                                                  .description("feedback as high risk");
> 
>     when(verificationJobInstanceService.getVerificationJobInstance("abcd")).thenReturn(verificationJobInstance);
> ```

Looks like its getting used in all the tests. We can put this in the @Before method

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45098)* status: :shipit: complete! ✓

**Review by naveen-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45098)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/LogFeedbackServiceImplTest.java` line 330 at r3](https://reviewable.io/reviews/harness/harness-core/45098#-NQd57HJ8p83TvuDOguM:-NQdhsoO1izEl8c1MOQl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/730683a6befc9f704cf2a6c0ee5fa9b38135bce5/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/LogFeedbackServiceImplTest.java#L330)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Looks like its getting used in all the tests. We can put this in the @Before method
</blockquote></details>

Done.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45098)* status: :shipit: complete! ✓

**Pull request merged**
