### PR TITLE
feat: [CDC-16681]: Create NG entities post mapping

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30405)

### CODE REVIEW

**Comment by puthrayaharness** [comment]
trigger messagecheck

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30405)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 163 at r1](https://reviewable.io/reviews/harness/harness-core/30405#-MuoSo8Y2E1Z8bweS-uJ:-MuoSo8Y2E1Z8bweS-uK:b-zhkqkf) ([raw file](https://github.com/harness/harness-core/blob/c75effbf0d722a8ea99171fef42c877eae2f6aea/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L163)):*
> ```Java
>     for (NGYamlFile file : ngYamlFiles) {
>       try {
>         if (file.getYaml() instanceof ConnectorDTO) {
> ```

instead of if-else here, can we follow the same approach like discovery, mapping? Ask every entity that is producing some yaml to save the corresponding object?

**Comment by puthrayaharness** [comment]
___
*[100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java, line 163 at r1](https://reviewable.io/reviews/harness/harness-core/30405#-MuoSo8Y2E1Z8bweS-uJ:-Mv2R5Zz4MYcvHmW4QL0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c75effbf0d722a8ea99171fef42c877eae2f6aea/100-migrator/src/main/java/io/harness/ngmigration/service/DiscoveryService.java#L163)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

instead of if-else here, can we follow the same approach like discovery, mapping? Ask every entity that is producing some yaml to save the corresponding object?
</blockquote></details>

Done.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 7 of 11 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30405)* status: :shipit: complete! ✓

**Review by vaibhav-si — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30405)* status: :shipit: complete! ✓

**Comment by puthrayaharness** [comment]
trigger ti4

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30405)* status: :shipit: complete! ✓

**Pull request merged**
