### PR TITLE
[fix]: [CDS-72124]: Fixing nextNode not being set when stepGroup is inside stepGroup and that is child of parallel node

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Issue: StepGroups not being executed when they are nextNode of another stepGroup and these both stepGroups are child of another stepGroup. And there is a parallel node above all these stepGroups.

Cause: 

- While adding the nextStepAdvisor(Or OnSuccessAdvisor) while planCreation. We check if the current node is a child of parallel or not. If its child of parallel then we do not add the nextStepAdvisor because the parallel node will take care of running all of its children. But its true when the step/stepGroup is direct child of parallel.
- While checking if the current node(StepGroup) is child of parallel, we were considering it as parallel's child even if its not direct child of parallel. So in that case the stepGroup(child of another stepGroup) node was not adding the nextStepAdvisor.

Changes: While checking if the current node is child of parallelNode. We were only checking if there is one parallel parent of that node. The fix is that we are now checking that parallel is the direct parent of current node.(Not grand parent)

Impact: This change impacts adding the nextStepAdvisor and OnSuccessAdvisors during the planCreation. When there is a parallel node and it has a stepGroup child. So the stepGroup's children will have the notnull nextStepAdvisors because they are not the direct children of parallel.

Testing: Tested the below cases in a pipeline

- StepGroup as child of parallel. And stepGroup has a 2 stepGroups as its children. So the first inner stepGroup will have the nextStepAdvisor after the planCreation. So the 2nd stepGroup will be executed after completing first inner stepGroup.
- StepGroup as child of parallel. And stepGroup has a 3 children stepGroups1, step1, stepGroup2 as its children. So the first inner stepGroup1 will have the nextStepAdvisor for the step1. step1 will have nextNode advisor for stepGroup2. So the step1 and stepGroup2 are executed after stepGroup1.
- 2 StepGroups as children of parallel. So the first stepGroup will not add the nextStepAdvisor as the stepGroups are direct children of parallel.
- 2 steps as children of parallel. So the first stepGroup will not add the nextStepAdvisor as the stepGroups are direct children of parallel.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49384)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49384)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49384)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49384)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49384)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
