### PR TITLE
techdebt: [DEL-5679]: Remove direct dependencies on 960-api-services

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Stop having direct dependencies on 960-api-services:module target.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)

### CODE REVIEW

**Review by mdmilic — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: :shipit: complete! ✓

**Review by Raghav-Murali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: 7 file(s) to review. 

___
*[`900-git-sync-sdk/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/42580#-NLhDNM1DVm4h9yhVnXg:-NLhDNM1DVm4h9yhVnXh:bnt8zig) ([raw file](https://github.com/harness/harness-core/blob/05041023cfa00a4693af72ccb4df76c31d1cf8d4/900-git-sync-sdk/BUILD.bazel#L6)):*
> ```Starlark
> # https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
> 
> load("@rules_java//java:defs.bzl", "java_binary", "java_library")
> ```

So there is already a `java_library` rule present in the Build file below even without loading the rule ?
___
*[`900-git-sync-sdk/BUILD.bazel` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/42580#-NLhDsgi3IkCdGxgVIPy:-NLhDsgi3IkCdGxgVIPz:b6iso31) ([raw file](https://github.com/harness/harness-core/blob/05041023cfa00a4693af72ccb4df76c31d1cf8d4/900-git-sync-sdk/BUILD.bazel#L80)):*
> ```Starlark
>         "@maven//:org_springframework_spring_context",
>         "@maven//:org_springframework_spring_core",
>         "@maven//:org_springframework_spring_tx",
> ```

Curious to know how all these maven dependencies were not present before but got added now ?

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: 1. unresolved discussions. 

___
*[`900-git-sync-sdk/BUILD.bazel` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/42580#-NLhDsgi3IkCdGxgVIPy:-NList1b9WhpOtGVTd-o:b32v57) ([raw file](https://github.com/harness/harness-core/blob/05041023cfa00a4693af72ccb4df76c31d1cf8d4/900-git-sync-sdk/BUILD.bazel#L80)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Curious to know how all these maven dependencies were not present before but got added now ?
</blockquote></details>

+1

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: 3. unresolved discussions. 

___
*[`900-git-sync-sdk/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/42580#-NLhDNM1DVm4h9yhVnXg:-NLtBit_CBwo3AJgpVuI:b-gri76n) ([raw file](https://github.com/harness/harness-core/blob/05041023cfa00a4693af72ccb4df76c31d1cf8d4/900-git-sync-sdk/BUILD.bazel#L6)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

So there is already a `java_library` rule present in the Build file below even without loading the rule ?
</blockquote></details>

this one its not clear to me how it works without listing the import - i just made it explicit
___
*[`900-git-sync-sdk/BUILD.bazel` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/42580#-NLhDsgi3IkCdGxgVIPy:-NLtBMZfEEdQZNQood2K:b-kmurtj) ([raw file](https://github.com/harness/harness-core/blob/05041023cfa00a4693af72ccb4df76c31d1cf8d4/900-git-sync-sdk/BUILD.bazel#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

These dependencies were there earlier too -- just coming indirectly from other targets. Now, we are trimming targets and adding specifically what we need.

**Review by mdmilic — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: 3. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: 3. unresolved discussions.

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: Some of the checks are too old. 3. unresolved discussions.

**Review by Raghav-Murali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42580)* status: Some of the checks are too old.

**Pull request merged**
