### PR TITLE
fix: [CDS-48078]: pod cleanup container step

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
We are adding more capabilities for run step in Pipeline container step. 
We have introduced 3 delegate tasks to help us in life cycle of a pod creation and execution run step in a new pod. 
The delegate tasks here are not going to be used soon since we plan to GA this after a month or so. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger feature-build

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 14 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqey8PBwb7XlfaBAro:-NIqey8PBwb7XlfaBArp:btkg3i4) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L132)):*
> ```Java
>   public StepResponse finalizeExecutionWithSecurityContext(Ambiance ambiance, StepParameters stepParameters,
>       PassThroughData passThroughData, ThrowingSupplier responseDataSupplier) throws Exception {
>     Object o = responseDataSupplier.get();
> ```

should we read as object here?



_Code quote:_
```Java
Object o = responseDataSupplier.get();
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepCleanupHelper.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqf05h7gPiuBM_xZ78:-NIqf05h7gPiuBM_xZ79:b-661s1r) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepCleanupHelper.java#L53)):*
> ```Java
> @Singleton
> @Slf4j
> public class ContainerStepCleanupHelper {
> ```

owner annotation
___
*[`scripts/api/internal/fetch-spec.sh` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqfOaZ9rpUfEs7B0Lp:-NIqfOaZ9rpUfEs7B0Lq:b-btjn1y) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/scripts/api/internal/fetch-spec.sh#L3)):*
> ```Shell
> #!/bin/sh
> # Copyright 2022 Harness Inc. All rights reserved.
> # Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
> ```

will this cause any issue?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqey8PBwb7XlfaBAro:-NIsQI3A-h38SYRLfNPz:b-trzznt) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L132)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we read as object here?
</blockquote></details>

yeah we need to read it as object before downcasting as `.get` can throw exception too and i dont want to end in class cast
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepCleanupHelper.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqf05h7gPiuBM_xZ78:-NIsQQrE1p-hDGr4hrcA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepCleanupHelper.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

owner annotation
</blockquote></details>

Done.
___
*[`scripts/api/internal/fetch-spec.sh` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqfOaZ9rpUfEs7B0Lp:-NIsQRLDBAACdA3fRmOD:b-zdpp49) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/scripts/api/internal/fetch-spec.sh#L3)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

will this cause any issue?
</blockquote></details>

checked other shell script - its the same

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqey8PBwb7XlfaBAro:-NIzuWhzEu6e5MA8Aqic:b3l1j3x) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L132)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

yeah we need to read it as object before downcasting as `.get` can throw exception too and i dont want to end in class cast
</blockquote></details>

I dont see usage of O result plus if we ThrowingSupplier is an interface, we should give expected object type in the method itself, check other steps as well
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/41276#-NIzvCMF6C0-Q-lDrUt1:-NIzvCMF6C0-Q-lDrUt2:b-r711us) ([raw file](https://github.com/harness/harness-core/blob/282a5324d947d4a7b43b45e8a2f9018fdcdc16fa/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L144)):*
> ```Java
>     StepElementParameters stepParameters1 = (StepElementParameters) stepParameters;
>     ContainerStepInfo containerStepInfo = (ContainerStepInfo) stepParameters1.getSpec();
>     Object response = responseSupplier.get();
> ```

Same for this, Instead of object it should be ResponseData



_Code quote:_
```Java
responseSupplier.get();
```

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/41276#-NIqey8PBwb7XlfaBAro:-NJ7cayz-N4JKFR__bdT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68b7820e4e965c7a9d9c982a1f36e75c422a1132/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L132)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I dont see usage of O result plus if we ThrowingSupplier is an interface, we should give expected object type in the method itself, check other steps as well
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java` line 144 at r4](https://reviewable.io/reviews/harness/harness-core/41276#-NIzvCMF6C0-Q-lDrUt1:-NJ7cbX9DMFBv5YFmC2l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/282a5324d947d4a7b43b45e8a2f9018fdcdc16fa/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStep.java#L144)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Same for this, Instead of object it should be ResponseData
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 11 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 11 of 12 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 1 file(s) to review.

**Review by mankrit-singh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276#-:-NJ9NCdxEXFeT2wjrTlr:bnfp4nl)* status: 1 file(s) to review.

**Review by arpit3107 — DISMISSED** [review]
> Reviewed 13 of 13 files at r1, 3 of 3 files at r2, 15 of 15 files at r3, 2 of 2 files at r4, 12 of 12 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: :shipit: complete! ✓

**Review by RajBaviskar — APPROVED** [review]

**Review by arpit3107 — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 3 file(s) to review.

**Review by RajBaviskar — APPROVED** [review]

**Review by sribalij — APPROVED** [review]
> Reviewed 13 of 13 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41276)* status: 4 file(s) to review.

**Pull request merged**
