### PR TITLE
[feat]: [CDS-39691]: Redesigned active service deployments api

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35170)

### CODE REVIEW

**Comment by Abhishek-CDC** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35170)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 357 at r2](https://reviewable.io/reviews/harness/harness-core/35170#-N6TMMKIBYS6vg9mJYtJ:-N6TMMKIBYS6vg9mJYtK:b7uc8zz) ([raw file](https://github.com/harness/harness-core/blob/a944f691fd7cd2f7e428249beaca2ce2ca47a4d5/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L357)):*
> ```Java
>   @GET
>   @Path("/getActiveServiceDeployments")
>   @ApiOperation(value = "Get list of Artifact, Environment and Pipeline for Active Service Deployments",
> ```

"Get Information about artifacts for a particular service, deployed to different environments"
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1858 at r2](https://reviewable.io/reviews/harness/harness-core/35170#-N6TYtmGBgA8HeC9k0G5:-N6TYtmGBgA8HeC9k0G6:b-jre6js) ([raw file](https://github.com/harness/harness-core/blob/a944f691fd7cd2f7e428249beaca2ce2ca47a4d5/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1858)):*
> ```Java
>     Pair<List<String>, Map<String, BuildAndEnvironmentInfo>> deploymentInfo = getBuildAndEnvironmentInfo(query);
> 
>     List<String> pipelineExecutionIdList = deploymentInfo.getKey();
> ```

what happens when are no pipeline executions ? we should make sure there are no NPEs

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 357 at r2](https://reviewable.io/reviews/harness/harness-core/35170#-N6TMMKIBYS6vg9mJYtJ:-N6fjV_S862Z8PWrvrt3:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a944f691fd7cd2f7e428249beaca2ce2ca47a4d5/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L357)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

"Get Information about artifacts for a particular service, deployed to different environments"
</blockquote></details>

Done

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1858 at r2](https://reviewable.io/reviews/harness/harness-core/35170#-N6TYtmGBgA8HeC9k0G5:-N6fjYcTEiCAMRGKO6KN:b4lk9iy) ([raw file](https://github.com/harness/harness-core/blob/a944f691fd7cd2f7e428249beaca2ce2ca47a4d5/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1858)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what happens when are no pipeline executions ? we should make sure there are no NPEs
</blockquote></details>

Done.
Have changed the traversal and to address this.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35170)* status: :shipit: complete! ✓

**Pull request merged**
