### PR TITLE
feat:[PIE-6486]: Add new entity for git file cache

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40462)

### CODE REVIEW

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by adivishy1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40462)* status: 2 file(s) to review.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40462)* status: 2 file(s) to review. 1 change requests. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/40462#-NHSgw1L6q8HueiEdX_a:-NHSgw1L6q8HueiEdX_b:bj0phn) ([raw file](https://github.com/harness/harness-core/blob/9f1954ab951425d7a9c9b469f840edb8997304e2/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java#L63)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(CompoundMongoIndex.builder()
>                  .name("accountIdentifier_gitProvider_repoName_ref_completeFilepath_unique_idx")
> ```

I think this is the cache key index, if yes didn't we discuss we can create one hash as well and have unique index on it?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/40462#-NHSgw1L6q8HueiEdX_a:-NHSo9aV3Gg4ZTuMuY3m:b-dk636i) ([raw file](https://github.com/harness/harness-core/blob/9f1954ab951425d7a9c9b469f840edb8997304e2/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think this is the cache key index, if yes didn't we discuss we can create one hash as well and have unique index on it?
</blockquote></details>

Ya, actually then we discussed further on it and felt its bit over-do at the moment and we can come back to it later if required. More details at: https://harness.slack.com/archives/C029WEBAMR8/p1668712553801179?thread_ts=1668583982.614539&cid=C029WEBAMR8

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40462)* status: :shipit: complete! ✓

**Pull request merged**
