### PR TITLE
fix: [PIE-7682]: include field name in the error when there are unresolved expressions

### PR DESCRIPTION
**Pull request by shalini-agr**
**Issue:** In case of unresolved expressions, error message only shows the expressions but not the field name 
**Fix:** In ExpressionEvaluatorUtils, send the key along with list of expressions in the exception. This is only phase 1 of the solution. In the next phase, we will also include the fully qualified path of the field in the error message.

Error message in case of below yaml:
policySets:
  - <+pipeline.variables.v3>
  - <+pipeline.variables.v4>

Screenshot 2023-01-19 at 12 39 31 PM

timeout: <+pipeline.variables.v1> + <+pipeline.variables.v2>
Screenshot 2023-01-19 at 12 41 10 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42779)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/exception/UnresolvedExpressionsException.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/42779#-NM8BQ--2hkMApULrCVI:-NM8BQ-0-CxA0X7jbIlV:b-8ausm4) ([raw file](https://github.com/harness/harness-core/blob/ff972c9facab5c0b8847b283ad1e23017bee8478/980-commons/src/main/java/io/harness/exception/UnresolvedExpressionsException.java#L59)):*
> ```Java
>   }
> 
>   private static String prepareExpressionsAndFieldsString(String key, List<String> expressions) {
> ```

Add a comment explaining what this function does.

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java` line 284 at r1](https://reviewable.io/reviews/harness/harness-core/42779#-NM8BVJx3C_iDMn-VZPR:-NM8BVJx3C_iDMn-VZPS:bd2ej2a) ([raw file](https://github.com/harness/harness-core/blob/ff972c9facab5c0b8847b283ad1e23017bee8478/980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java#L284)):*
> ```Java
>           return updateExpressionsInternal(v, functor, depth - 1, cache);
>         } catch (UnresolvedExpressionsException ex) {
>           throw new UnresolvedExpressionsException((String) k, new ArrayList<>(ex.fetchExpressions()));
> ```

Add a comment as to why we are throwing back again and let's add an example if possible.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42779)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/UnresolvedExpressionsException.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/42779#-NM8BQ--2hkMApULrCVI:-NM8U3QcDrwjUUi9BrsU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff972c9facab5c0b8847b283ad1e23017bee8478/980-commons/src/main/java/io/harness/exception/UnresolvedExpressionsException.java#L59)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a comment explaining what this function does.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java` line 284 at r1](https://reviewable.io/reviews/harness/harness-core/42779#-NM8BVJx3C_iDMn-VZPR:-NM8U5d5BGHGsOuyHxK2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff972c9facab5c0b8847b283ad1e23017bee8478/980-commons/src/main/java/io/harness/expression/ExpressionEvaluatorUtils.java#L284)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a comment as to why we are throwing back again and let's add an example if possible.
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42779)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42779)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42779)* status: :shipit: complete! ✓

**Pull request merged**
