### PR TITLE
fix:[PL-37994] bumping upthe jre version for delegate

### PR DESCRIPTION
**Pull request by bharatgoelharness**
## Describe your changes
Upgrading jre for delegate and watcher
Test cases https://harness.atlassian.net/wiki/spaces/DEL/pages/21398585932/Delegate+JRE+upgrade+to+11.0.19+7
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48424)

### CODE REVIEW

**Comment by bharatgoelharness** [comment]
trigger uts

**Comment by bharatgoelharness** [comment]
> > Reviewed 28 of 28 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/48424)_ status: 28 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`dockerization/delegate/Dockerfile-delegate-non-root-openjdk-ubi-multi-arch` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/48424#-NWNpthR2FKVzY1Z6IHa:-NWNpthR2FKVzY1Z6IHb:bev5ddq) ([raw file](https://github.com/harness/harness-core/blob/c0fb7393337071b71e2c4aa826bbbf021bf52457/dockerization/delegate/Dockerfile-delegate-non-root-openjdk-ubi-multi-arch#L43)):_
> 
> > ```
> > USER 1001
> > COPY --chown=1001 --from=adoptopenjdk/openjdk11:jre-11.0.14_9-ubi-minimal /opt/java/openjdk/ ./jdk-11.0.14+9-jre/
> > COPY --chown=1001 --from=adoptopenjdk/openjdk11:jre-11.0.19_7-ubi-minimal /opt/java/openjdk/ ./jdk-11.0.19+7-jre/
> > ```
> 
> Any reason not to remove the old JRE? The delegate would be started with new JRE anyway and we will only release this image after the upgrade has gone through. Also, start.sh is capable of downloading missing JRE if needed (e.g. in case of rollbacks)

Yes we can remove it.
Initially i was thinking of releasing the delegate image with manager but we can release the delegate image at the last and we can have only jre 11.0.19 baked in at that time.

**Comment by bharatgoelharness** [comment]
trigger ut8

**Comment by bharatgoelharness** [comment]
trigger uts

**Comment by bharatgoelharness** [comment]
@mdmilic I have removed the chnages of legacy images for now.
First we will publish manager, delegate and immutable delegate.
We will publish legacy delegate after above is done.

**Comment by bharatgoelharness** [comment]
trigger uts

**Comment by bharatgoelharness** [comment]
trigger ut1

**Comment by bharatgoelharness** [comment]
trigger ut3

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48424)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Comment by bharatgoelharness** [comment]
trigger ut3

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 24 of 28 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48424)* status: :shipit: complete! ✓

**Comment by bharatgoelharness** [comment]
trigger uts

**Comment by bharatgoelharness** [comment]
trigger uts

**Comment by bharatgoelharness** [comment]
trigger ut1

**Comment by bharatgoelharness** [comment]
trigger ut3

**Review by AnupamIO — APPROVED** [review]
> Reviewed 24 of 28 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48424)* status: 1 file(s) to review.

**Comment by bharatgoelharness** [comment]
trigger uts

**Pull request merged**
