### PR TITLE
feat: [CDS-76796]: support cli options for terragrunt on delegate side

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes

The purpose of this PR is support CLI Options for terragrunt command
Commands which will support CLI options are: INIT, WORKSPACE, PLAN, APPLY, DESTROY.
Each of these commands is supporting different CLI Options, based on the command. But from the customer/UI we take the command and CLI option. For example command=PLAN, CLI Option = "-lock-timeout=10s" and then we pass this for CLI.

Example of global options:
Screenshot 2023-09-01 at 18 02 38

Example of CLI options specific for init:
Screenshot 2023-09-01 at 18 03 24

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52346)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger uts_JDK11

**Comment by USB-05** [comment]
trigger uts

**Comment by vlica-harness** [comment]
trigger uts

**Comment by USB-05** [comment]
trigger uts

**Comment by vlica-harness** [comment]
trigger uts_JDK11

**Review by yogesh-chauhan — APPROVED** [review]

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 7 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52346)* status: 11 file(s) to review. 

___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntV2Contants.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/52346#-NdTzbBQ1WZkB20Cau1C:-NdTzbBQ1WZkB20Cau1D:b1zy5w3) ([raw file](https://github.com/harness/harness-core/blob/cc410481c2230efa3ae834f44f532a9e30460551/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntV2Contants.java#L10)):*
> ```Java
> package io.harness.terragrunt.v2;
> 
> public class TerragruntV2Contants {
> ```

we miss @OwnedBy

**Comment by vlica-harness** [comment]
trigger uts_JDK11

**Comment by vlica-harness** [comment]
trigger ut6

**Comment by vlica-harness** [comment]
trigger ut8

**Comment by vlica-harness** [comment]
trigger ut6

**Review by tmacari-harness — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52346)* status: 3 file(s) to review.

**Comment by vlica-harness** [comment]
trigger review

**Pull request merged**
