### PR TITLE
feat: [PL-39275]: SEND METRICS TO SEGMENT Ng-manager changes

### PR DESCRIPTION
**Pull request by sahibaHarness**
## Describe your changes

Send metrics to segment[Amplitude] & Prometheus to monitor Active projects on accounts. This has to be done to monitor stickiness of feature
Pasted Graphic 8
Pasted Graphic 6

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53494)

### CODE REVIEW

**Comment by sahibaHarness** [comment]
trigger uts

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53494)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 998 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrMFa-9jcNimcKVcpl:-NfrMFa05p_oQOeMQiNv:b41hd1e) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L998)):*
> ```Java
>         .scheduleWithFixedDelay(injector.getInstance(CDLicenseDailyReportTask.class), 0, 3, TimeUnit.HOURS);
>     injector.getInstance(Key.get(ScheduledExecutorService.class, Names.named("taskPollExecutor")))
>         .scheduleWithFixedDelay(injector.getInstance(ActiveProjectMetricsRunnable.class), 0, 24, TimeUnit.HOURS);
> ```

can be named better e.g. ActiveProjectMetricsPublisherTask
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrMupd8TV0AUZqStSb:-NfrMupd8TV0AUZqStSc:bj4r1y8) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L696)):*
> ```Java
>     ProjectionOperation projectionStage =
>         project().and(MONGODB_ID).as(ProjectKeys.accountIdentifier).andInclude(ProjectsPerAccountCountKeys.count);
>     Map<String, Integer> result = new HashMap<>();
> ```

add decent spacing in this logic, its very unreadable
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrNNXBA8dzjo7iWUyW:-NfrNNXBA8dzjo7iWUyX:b1x1dfv) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java#L39)):*
> ```Java
>     long endTime = System.currentTimeMillis();
>     long startTime = endTime - (24 * 60 * 60 * 1000);
>     log.info("Starting ActiveProjectMetricsRunnable Job");
> ```

add a newline after this, again it is unreadability 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrNiEv3lLWPp6Ak27_:-NfrNiEv3lLWPp6Ak27a:bmepppx) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java#L64)):*
> ```Java
>         } while (true);
>       } catch (Exception ex) {
>         log.error("Error occurred while sending metrics for active projects to segment: ", ex);
> ```

add some account details so that its easier to debug later

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53494)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrNNXBA8dzjo7iWUyW:-NfuCVkBCkfrCWOWIltL:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java#L39)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

add a newline after this, again it is unreadability
</blockquote></details>

done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrNiEv3lLWPp6Ak27_:-NfuCIsV3UFgfrKJ0wya:blapd6q) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java#L64)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

add some account details so that its easier to debug later
</blockquote></details>

If the failure occurs here then it's going to be for a batch of 100 accounts. do we really want to add them all here?

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53494)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrMupd8TV0AUZqStSb:-NfuC_KM3qAoNfoAK_-9:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L696)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

add decent spacing in this logic, its very unreadable
</blockquote></details>

okay

**Comment by sahibaHarness** [comment]
trigger uts

**Review by sahibaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53494)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 998 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrMFa-9jcNimcKVcpl:-NfzBzX406sU2Ycj-3ua:b-bp37mq) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L998)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

can be named better e.g. ActiveProjectMetricsPublisherTask
</blockquote></details>

Changing the name to AccountMetricsPublisherTask
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/53494#-NfrNiEv3lLWPp6Ak27_:-NfzBtLcBGovcCnaHSs9:b-yn1o38) ([raw file](https://github.com/harness/harness-core/blob/081204255a70105750357016c025084d126b2dfd/120-ng-manager/src/main/java/io/harness/ng/core/scheduler/projectMetricsJob/ActiveProjectMetricsRunnable.java#L64)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why not? If it fails then how would you know for which accounts has it failed for.
</blockquote></details>

okay, adding list of account ids

**Pull request closed without merging**
