### PR TITLE
feat: [FFM-4127] Send entity crud events for service changes

### PR DESCRIPTION
**Pull request by conormurray95**
## Describe your changes
As part of the feature flags SRM integration we associate flags with services in our db. 
To allow us to cleanup any of these associations when a service is deleted we need entity crud events like the ones that are sent for projects/envs/accounts/pipelines/secrets/connectors etc.
To support this I had to change the constructor from the annotation method to the explicitly defined constructor, add the standard `publishEvent` method and then call it from the create/update/upsert/delete methods.

## Similar events
[EnvironmentService publishEvent function](https://github.com/harness/harness-core/blob/develop/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L489) 
[EnvironmentService publishEvent onDelete ](https://github.com/harness/harness-core/blob/develop/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L281)

## Testing
I've tested this locally and can see and process the redis entitycrud messages when I create/edit/delete services.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36104)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36104)

**Comment by conormurray95** [comment]
Hey @yogesh-chauhan @namanvermah @hingerabhinav github kindly suggested you as reviewers for this pr :-) , if theres anyone else or a slack room I should ping into please let me know, thanks!

**Review by davejohnston — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36104)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36104)* status: Some of the checks are too old. 1 change requests. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/36104#-N90ZgtM-Fu_OiqwalXk:-N90ZgtM-Fu_OiqwalXl:b-bzvj7m) (no related file):*
There are other method which we should consider
- bulkCreate
- forceDeleteAllInProject

___
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 328 at r1](https://reviewable.io/reviews/harness/harness-core/36104#-N90ZzWBCzTKVdxOa5Ys:-N90ZzWBCzTKVdxOa5Yt:b276t06) ([raw file](https://github.com/harness/harness-core/blob/f1785e14b707d018b944513b3b877045036b28a3/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L328)):*
> ```Java
>               .build());
>     } catch (EventsFrameworkDownException e) {
>       log.error("Failed to send event to events framework environment Identifier: {}", identifier, e);
> ```

is this log message correct ? It says environment identifier

**Comment by conormurray95** [comment]
> _[a discussion](https://reviewable.io/reviews/harness/harness-core/36104#-N90ZgtM-Fu_OiqwalXk:-N90ZgtM-Fu_OiqwalXl:b-bzvj7m) (no related file):_ There are other method which we should consider
> 
> * bulkCreate
> * forceDeleteAllInProject


I've added in the publishEvent calls for each service listed in the `bulkCreate` method

For `forceDeleteAllInProject` it looks like the other entities don't send any events when this is called e.g. environment entity [here](https://github.com/harness/harness-core/blob/develop/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L305). I presume that's because the entire project is being deleted when this is called and any cleanup should happen based on the project delete entity events. 


> is this log message correct ? It says environment identifier

Good catch I've updated it to be service identifier

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 394 at r2](https://reviewable.io/reviews/harness/harness-core/36104#-N91t5CI5fdIqSLulgty:-N91t5CI5fdIqSLulgtz:b-c05ful) ([raw file](https://github.com/harness/harness-core/blob/e94a6ea3689ce3e587076c40ee1bff77f473079a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L394)):*
> ```Java
>             serviceEntity.getProjectIdentifier(), serviceEntity.getIdentifier(),
>             EventsFrameworkMetadataConstants.CREATE_ACTION);
>       }
> ```

just fyi, this expects that the consumer can deal with duplicate create events

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36104)* status: :shipit: complete! ✓

**Pull request merged**
