### PR TITLE
[feat]: [CDS-41879]: dashboard displays incorrect artifact

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39955)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 2210 at r1](https://reviewable.io/reviews/harness/harness-core/39955#-NGYMFzwDJ4uqWHiZ3oR:-NG_AeSF2D_cFmt5FhZZ:b-1whbfy) ([raw file](https://github.com/harness/harness-core/blob/600296d2981354dd464887f927f0f7d6b22adbda/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L2210)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, why do we remove userDataSpecification for the azure web app? 
</blockquote></details>

There were 2 reasons: 1) at the beginning when the webApp service is created it had no UserDataSpecification. Once a startup command is added the userDataSpecification is created. When user removes the startUp command we are left with the userDataSpecification which has "" as data, where it should actually be null, but nulls not allowed here. This causes issue later on with further updating this item. 2) The logic for updating azure webApp config already works well when startup command is null, as that is the initial value, whereas for "" we see the issue reported by the bug I fixed.

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java` line 2210 at r3](https://reviewable.io/reviews/harness/harness-core/39955#-NGub1YA5IOMaKbH6wDG:-NGub1YB46c_RRBhfOVJ:bp3l0hj) ([raw file](https://github.com/harness/harness-core/blob/ac5321883836c8c8cc454e27d08e8de97dd400b8/400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java#L2210)):*
> ```Java
>     String persistedUserDataSpecId = wingsPersistence.save(userDataSpecification);
>     UserDataSpecification persistedUserDataSpec =
>         wingsPersistence.get(UserDataSpecification.class, persistedUserDataSpecId);
> ```

Minor - can we use saveAndGet here, instead of two queries we will have only one. 



_Code quote:_
```Java
public UserDataSpecification upsertUserDataSpecification
```

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGudflXAh248mvc9YMe:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGv4FVpAEIJ6ptiRGgq:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGv7-UO-bWYpsH1rAsY:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGv7CL67HOZKnNfQxTU:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGv7hBE-7grEwZAVMfQ:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGvG1zp-ZiP7WWxkhu9:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGvGIbhBB7PjHlQdqvJ:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGvH7N4EHOn0tSo4JR1:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955#-:-NGvHhWc4dYpcKBgz-90:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39955)* status: 1 file(s) to review.

**Pull request closed without merging**
