### PR TITLE
feat: [CCM-15040]: Add permissions for CCM Commitment Orchestrator in Access Control

### PR DESCRIPTION
**Pull request by sandyydk**
## Describe your changes

RBAC changes for CCM Commitment Orchestrator

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)

### CODE REVIEW

**Comment by sandyydk** [comment]
trigger messagecheck

**Review by iamanmolm — DISMISSED** [review]

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1728 at r2](https://reviewable.io/reviews/harness/harness-core/55215#-Nio-QFm7M1iwDe9YM_F:-Nio-QFm7M1iwDe9YM_G:bwho4ah) ([raw file](https://github.com/harness/harness-core/blob/ceddb5c9257aaea69976f1bee3c128e2de17c8fa/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1728)):*
> ```YAML
>       - account
>   - identifier: ccm_commitment_orch_edit
>     name: Setup CCM Commitment Orchestration
> ```

Change ccm_commitment_orch_edit to commitmentOrch at all places. Permissions Identifier should be same Permission Ket defined in resourceTypes.yml

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 154 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-Nioc8M4BvVZiJCt9cMo:-Nioc8M4BvVZiJCt9cMp:bbxj3pw) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L154)):*
> ```YAML
>   - identifier: CCM_RECOMMENDATIONS
>     permissionKey: recommendations
>   - identifier: CCM_COMMITMENT_ORCH
> ```

Should we not rename CCM_COMMITMENT_ORCH to CCM_COMMITMENT_ORCHESTRATOR to make it readable and meaningful in context?
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-NiocAbt79A-5KDm_b5z:-NiocAbt79A-5KDm_b6-:b-qurft0) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L155)):*
> ```YAML
>     permissionKey: recommendations
>   - identifier: CCM_COMMITMENT_ORCH
>     permissionKey: commitmentOrch
> ```

Should we not rename commitmentOrch to commitmentOrchestrator ?
Same in other places

**Comment by sandyydk** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)_ status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 154 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-Nioc8M4BvVZiJCt9cMo:-Nioc8M4BvVZiJCt9cMp:bbxj3pw) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L154)):_
> 
> > ```yaml
> >   - identifier: CCM_RECOMMENDATIONS
> >     permissionKey: recommendations
> >   - identifier: CCM_COMMITMENT_ORCH
> > ```
> 
> Should we not rename CCM_COMMITMENT_ORCH to CCM_COMMITMENT_ORCHESTRATOR to make it readable and meaningful in context?
> 
> _[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-NiocAbt79A-5KDm_b5z:-NiocAbt79A-5KDm_b6-:b-qurft0) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L155)):_
> 
> > ```yaml
> >     permissionKey: recommendations
> >   - identifier: CCM_COMMITMENT_ORCH
> >     permissionKey: commitmentOrch
> > ```
> 
> Should we not rename commitmentOrch to commitmentOrchestrator ? Same in other places

Was thinking it's pretty huge already. Commitment and CCM itself makes it pretty clear was my thinking

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-NiocAbt79A-5KDm_b5z:-NioeZx2-i6LIRajtVn1:bissa5n) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L155)):*
<details><summary><i>Previously, sandyydk (Sandeep Bhat) wrote…</i></summary><blockquote>

Was thinking it's pretty huge already. Commitment and CCM itself makes it pretty clear was my thinking
</blockquote></details>

maybe can u help provide more context on what does Commitment Orchestrator mean. I will leave it upto you folks to decide but be consistent. Even if it large that should be okay as also think about that customers using API should be able to interpret it.

**Comment by sandyydk** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)_ status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-NiocAbt79A-5KDm_b5z:-NioeZx2-i6LIRajtVn1:bissa5n) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L155)):_
> 
> Previously, sandyydk (Sandeep Bhat) wrote…
> > Was thinking it's pretty huge already. Commitment and CCM itself makes it pretty clear was my thinking
> 
> maybe can u help provide more context on what does Commitment Orchestrator mean. I will leave it upto you folks to decide but be consistent. Even if it large that should be okay as also think about that customers using API should be able to interpret it.

Got it. If it would be helpful I can name it `CCM_COMMITMENT_ORCHESTRATOR`. Does this sound fine? It's also referred to as "Commitments" in the UI.

**Comment by sandyydk** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)_ status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/55215#-NiocAbt79A-5KDm_b5z:-NioeZx2-i6LIRajtVn1:bissa5n) ([raw file](https://github.com/harness/harness-core/blob/4f17c19ef1cd37beec15765c31ff9f652e42414f/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L155)):_
> 
> Previously, sandyydk (Sandeep Bhat) wrote…
> > Was thinking it's pretty huge already. Commitment and CCM itself makes it pretty clear was my thinking
> 
> maybe can u help provide more context on what does Commitment Orchestrator mean. I will leave it upto you folks to decide but be consistent. Even if it large that should be okay as also think about that customers using API should be able to interpret it.

Commitment Orchestrator orchestrates purchase and exchanges of Reserved Instances and Savings Plans in AWS helping customers save cloud cost in the long run.

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55215)* status: :shipit: complete! ✓

**Pull request merged**
