### PR TITLE
feat: [CDS-45554]: Support for deploying artifacts from the Azure art…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…ifacts repo in SSH/winRM deployments

## Describe your changes

Added support for Azure artifacts for both SSH and Winrm. Also, addedd support for ssh copy artifact while for the Winrm we are throwing exception (WinRmCopyCommandHandler:92). 
We have created new task type  TaskType.COMMAND_TASK_NG_WITH_AZURE_ARTIFACT to keep backwards compatibility because we are changing TaskParameters by adding new implementation for SshWinRmArtifactDelegateConfig. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger recency messagecheck

**Review by acasian-harness — CHANGES_REQUESTED** [review]
@bojanmicovic please add proper PR description. Also, for WinRM copy, are we handling it properly by throwing error?

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NKS4m8S20thkUWwfhN9:boc3suj)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/TaskDataFactory.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS2m1S6vC8XA4VOJAA:-NKS2m1S6vC8XA4VOJAB:bs3ghik) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/TaskDataFactory.java#L27)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.CDP)
> public class TaskDataFactory {
> ```

this is to generic name, it is applied only to command task, nit can be renamed to `CommandTaskDataFactory`
___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 1953 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS36hx4iBmkPjd0sNX:-NKS36hx4iBmkPjd0sNY:bs2fl7l) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1953)):*
> ```Java
>     mapBinder.addBinding(TaskType.FETCH_INSTANCE_SCRIPT_TASK_NG).toInstance(FetchInstanceScriptTaskNG.class);
>     mapBinder.addBinding(TaskType.COMMAND_TASK_NG).toInstance(CommandTaskNG.class);
>     mapBinder.addBinding(TaskType.COMMAND_TASK_NG_WITH_AZURE_ARTIFACT).toInstance(CommandTaskNG.class);
> ```

can we reuse the same delegate task?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactsHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS3JRy2g8kFstG-u5u:-NKS3JRy2g8kFstG-u5v:b-6zof59) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactsHelper.java#L51)):*
> ```Java
>     if (isBlank(artifactFileName)) {
>       throw new InvalidRequestException(
>           "No file available for downloading the package " + azureArtifactDelegateConfig.getPackageName());
> ```

hint with explanation
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AzureArtifactCommandUnitHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS3ScG1bkowW9Av7Zh:-NKS3ScG1bkowW9Av7Zi:b-6zof59) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AzureArtifactCommandUnitHandler.java#L73)):*
> ```Java
>     try (InputStream inputStream = azureArtifactsDownloadHelper.downloadArtifactByUrl(downloadUrl, authHeader)) {
>       if (inputStream == null) {
>         throw new InvalidArtifactServerException(
> ```

hint with explanation
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/shell/ArtifactDownloadHandlerTest.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS4NWVD4YI1uBTI0wa:-NKS4NWVD4YI1uBTI0wb:b635pvo) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/test/java/io/harness/delegate/task/shell/ArtifactDownloadHandlerTest.java#L124)):*
> ```Java
>                                                         .build();
>     when(secretDecryptionService.decrypt(any(AzureArtifactsTokenDTO.class), any())).thenReturn(azureArtifactsTokenDTO);
>     //    when(encryptionService.decrypt(any(AwsConfig.class), any(), anyBoolean()))
> ```

let's removed those unused commented lines

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/TaskDataFactory.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS2m1S6vC8XA4VOJAA:-NKS5IahAT9mV7j0Ut2W:bo9lm7t) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/TaskDataFactory.java#L27)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

this is to generic name, it is applied only to command task, nit can be renamed to `CommandTaskDataFactory`
</blockquote></details>

And also please add UT for it

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKSJ98o7rTHaDVs5NhK:-NKSJ98o7rTHaDVs5NhL:b-z208i8) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L138)):*
> ```Java
>       new URI(azureDevopsUrl);
>     } catch (URISyntaxException e) {
>       throw new InvalidArtifactServerException("Azure DevOps URL is invalid");
> ```

minor: can we include the url in the exception message

**Review by bojanmicovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)* status: 21 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 1953 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS36hx4iBmkPjd0sNX:-NKTV5glAwgxUaQEzJqt:bgmjq34) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1953)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

can we reuse the same delegate task?
</blockquote></details>

This was discussed, and because of backwards compatibility we decided to go with a new task type.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactsHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS3JRy2g8kFstG-u5u:-NKTVERc7fBGJs9KEgH8:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactsHelper.java#L51)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

hint with explanation
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AzureArtifactCommandUnitHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS3ScG1bkowW9Av7Zh:-NKTVFc_B-BrG10cYDEY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/AzureArtifactCommandUnitHandler.java#L73)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

hint with explanation
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKSJ98o7rTHaDVs5NhK:-NKTVGjrBAsMWqDdu3lU:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L138)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

minor: can we include the url in the exception message
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/shell/ArtifactDownloadHandlerTest.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS4NWVD4YI1uBTI0wa:-NKTVIEc1hmxnPxtfivW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/930-delegate-tasks/src/test/java/io/harness/delegate/task/shell/ArtifactDownloadHandlerTest.java#L124)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

let's removed those unused commented lines
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/TaskDataFactory.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS2m1S6vC8XA4VOJAA:-NKTV2qx67iLQrbOsUqd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/TaskDataFactory.java#L27)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

And also please add UT for it
</blockquote></details>

Done.

**Review by bojanmicovic — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NKTYTyw4v01QwcUOh-n:bb6un1j)* status: 21 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 9 of 18 files at r1, 9 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)* status: 12 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 4 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 1953 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS36hx4iBmkPjd0sNX:-NKTWS4HDKoCU70RysIc:b-jgeh08) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1953)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

This was discussed, and because of backwards compatibility we decided to go with a new task type.
</blockquote></details>

i got it, i meant `CommandTaskNG` , can we re-use it with `TaskType.COMMAND_TASK_NG_WITH_AZURE_ARTIFACT` or we need a new delegate task on top of `CommandTaskNG`



_Code quote:_
```Java
CommandTaskNG
```

**Comment by bojanmicovic** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 1953 at r1](https://reviewable.io/reviews/harness/harness-core/39555#-NKS36hx4iBmkPjd0sNX:-NKX6XJ1EmysUJQOkTdU:bqi0qb4) ([raw file](https://github.com/harness/harness-core/blob/76fa12cbc4e84a7676a07d7522f1353a8eedfe8a/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1953)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i got it, i meant `CommandTaskNG` , can we re-use it with `TaskType.COMMAND_TASK_NG_WITH_AZURE_ARTIFACT` or we need a new delegate task on top of `CommandTaskNG`
</blockquote></details>

When it comes to framework perspective, it is not a problem, and also I think it is not braking any good coding practises.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 5 of 9 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)* status: :shipit: complete! ✓

**Review by ivan-83 — DISMISSED** [review]
LGTM with minor comments. Overall lot of work was done here, good job.  

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NKZToYg9qu_UshzCLau:b9rx7w5)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactsHelper.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZTLr_7B66EQdoaa3R:-NKZTLr_7B66EQdoaa3S:b-azbmuq) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactsHelper.java#L43)):*
> ```Java
>     AzureArtifactsInternalConfig azureArtifactsInternalConfig = toInternalConfig(
>         azureArtifactDelegateConfig, getDecryptedToken(azureArtifactDelegateConfig, secretDecryptionService));
>     List<AzureArtifactsPackageFileInfo> files = azureArtifactsRegistryService.listPackageFiles(
> ```

If azureArtifactDelegateConfig.getPackageType() == NUGET we don't need this listPackageFiles API call, right? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZMusb1hcoWFqkvla4:-NKZMusb1hcoWFqkvla5:b-ggm7kk) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L75)):*
> ```Java
>           azureArtifactsUrl, azureArtifactDelegateConfig, azureArtifactDelegateConfig.getVersion());
>     } else {
>       throw new InvalidRequestException("Invalid package type submitted, expected maven or nuget.");
> ```

Minor - maybe "expected zip, war, jar" not maven as package type in the log msg
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZPnvI2BsZ3J8O9kly:-NKZPnvI2BsZ3J8O9klz:bmma2ut) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L97)):*
> ```Java
>         artifactId = parts[1];
>       }
>     }
> ```

Is it possible that the package name is blank? Maybe throw an exception in that case. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZNR6j7fpqOGDinsjx:-NKZNR6j7fpqOGDinsjy:b1k0hv6) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L99)):*
> ```Java
>     }
>     return url
>         + format("_apis/packaging/feeds/%s/maven/%s/%s/%s/%s/content?api-version=5.1-preview.1", feed, groupId,
> ```

Minor -  create constant for "api-version=5.1-preview.1"  they change API version not so often but change. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 114 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZQFla4TknyLIcJdKN:-NKZQFlb0h0CluExOe79:b1k0hv6) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L114)):*
> ```Java
>     String packageName = azureArtifactDelegateConfig.getPackageName();
>     return url
>         + format("_apis/packaging/feeds/%s/nuget/packages/%s/versions/%s/content?api-version=5.1-preview.1", feed,
> ```

Minor -  create constant for "api-version=5.1-preview.1"  they change API version not so often but change. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 129 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZOhtUCQCg7E2qS2JX:-NKZOhtUCQCg7E2qS2JY:b-w9e6tp) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L129)):*
> ```Java
>         return azureDevopsUrl;
>       }
>     } catch (InvalidArtifactServerException e) {
> ```

Here if the Azure URL is invalid we fail back on the original azureDevopsUrl, should we throw an exception here?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java` line 143 at r4](https://reviewable.io/reviews/harness/harness-core/39555#-NKZMPbY7YIctO9ciUVD:-NKZMPbZCHgsmTq72nvT:b-xaq1m3) ([raw file](https://github.com/harness/harness-core/blob/4265bc6b10b891337a582e6cab0e7a35a184b88e/930-delegate-tasks/src/main/java/io/harness/delegate/utils/AzureArtifactsUtils.java#L143)):*
> ```Java
> 
>   private enum AzureArtifactPackageType {
>     MAVEN("maven"),
> ```

Minor - maven is not package type, NuGet yes.

**Comment by bojanmicovic** [comment]
1. Is it new task type? (If yes, no need to answer 2 then)
Yes
2. Did you add a new class which is added in kryo serialization if yes then do not use that class in any of the delegate task payload till it makes to delegate release
Yes
3. Did you make changes to the code in a backward-compatible manner?
Yes
4. will the new version of the delegate receive old version task and process?
Yes
5. If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes
6. Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
No
7. If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes
8. if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes
9. Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648](https://harness.atlassian.net/browse/DEL-3648): Move to name based kryo serializer for delegate/manager communication
No
10. Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
Yes

**Comment by bojanmicovic** [comment]
trigger ft1 ft2

**Review by mdmilic — DISMISSED** [review]
Approve delegate codeowned file changes. 

> Reviewed 1 of 18 files at r1, 1 of 9 files at r2, 1 of 3 files at r3, 2 of 7 files at r4, 3 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NLLepz21TLmquF6qCUb:buoj6rg)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NLLlQ3y2ip6n3dwAaus:bnfp4nl)* status: 8 file(s) to review.

**Review by acasian-harness — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 7 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NLM7iORDu_QDJJ1DNTP:bnfp4nl)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by mdmilic — APPROVED** [review]
approving delegate codeowned and build files

> Reviewed 4 of 6 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NLukDbBBe--ENQOxBnl:bqm79x0)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by bojanmicovic** [comment]
trigger ft1 ft2

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39555#-:-NLutOxt1wxbHcLg70JQ:bnfp4nl)* status: 7 file(s) to review.

**Pull request merged**
