### PR TITLE
[fix]: [PIE-8516]: Remove __default__ from fqn during pipeline update

### PR DESCRIPTION
**Pull request by namanvermah**
The value of branch in git context is "__default__ " during pipeline update for inline pipelines (this is an old git sync concept). This value needs to be treated as empty string for our purpose in the FQN for pipeline

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44267)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44267)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by ankittiwari-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/44267#-NOy8SRiD1hutQYG1cDH:-NOy8SRiD1hutQYG1cDI:b-wxrwuw) ([raw file](https://github.com/harness/harness-core/blob/c7445cb6c084ba11f55e620f4acd19acf29e2e5a/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L168)):*
> ```Java
>         String branchInRequest = GitAwareContextHelper.getBranchInRequest();
>         pipelineAsyncValidationService.createRecordForSuccessfulSyncValidation(createdEntity,
>             Objects.equals(branchInRequest, GitAwareContextHelper.DEFAULT) ? "" : branchInRequest, governanceMetadata,
> ```

nit: Why are we using Object.equals for this, adding a new import.
can't we directly use 



_Code snippet:_
```Java
GitAwareContextHelper.DEFAULT.equals(branchInRequest) 
```

**Review by ankittiwari-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44267)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44267)* status: 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/44267#-NOy8SRiD1hutQYG1cDH:-NP1L6Pu8JVId0quGSQ5:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c7445cb6c084ba11f55e620f4acd19acf29e2e5a/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L168)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

nit: Why are we using Object.equals for this, adding a new import.
can't we directly use 


</blockquote></details>

Done

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44267)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44267)* status: :shipit: complete! ✓

**Pull request merged**
