### PR TITLE
fix: [DEL-3317]: Shell Script Delegates - stop modifying the configuration files during restarts

### PR DESCRIPTION
**Pull request by jennyjames21**
…ation files during restarts

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 139 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-Mys3juJ-55AsYeWyagN:-Mys3juJ-55AsYeWyagO:bqd5ec4) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L139)):*
> ```FreeMarker
> if ! `grep verificationServiceUrl config-delegate.yml > /dev/null`; then
>   echo "verificationServiceUrl: ${managerHostAndPort}/verification/" >> config-delegate.yml
> elif [[ "$(grep verificationServiceUrl config-delegate.yml | cut -d ' ' -f 2)" != "${managerHostAndPort}/verification/" ]]; then
> ```

do we need then here?

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: :shipit: complete! ✓

**Review by brettzu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: :shipit: complete! ✓

___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 144 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-MyxYOhHAfb-tbYVdNMB:-MyxYOhIBh0_GsLfiVFv:bocce1p) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L144)):*
> ```FreeMarker
> if ! `grep cvNextGenUrl config-delegate.yml > /dev/null`; then
>   echo "cvNextGenUrl: ${managerHostAndPort}/cv/api/" >> config-delegate.yml
> elif [[ "$(grep cvNextGenUrl config-delegate.yml | cut -d ' ' -f 3)" != "${managerHostAndPort}/cv/api/" ]]; then
> ```

Why -f 3? It should also be -f 2.
___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 198 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-MyxYnwP7MontY1fxuGi:-MyxYnwP7MontY1fxuGj:brm9rng) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L198)):*
> ```FreeMarker
> if ! `grep grpcServiceEnabled config-delegate.yml > /dev/null`; then
>   echo "grpcServiceEnabled: $GRPC_SERVICE_ENABLED" >> config-delegate.yml
> elif [[ "$(grep grpcServiceEnabled config-delegate.yml | cut -d ' ' -f 2)" != "${grpcServiceEnabled}" ]]; then
> ```

This is wrong. Should be != "$GRPC_SERVICE_ENABLED"
___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 204 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-MyxYytb32MZZApMZM1p:-MyxYytb32MZZApMZM1q:b-pzuxtd) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L204)):*
> ```FreeMarker
> if ! `grep grpcServiceConnectorPort config-delegate.yml > /dev/null`; then
>   echo "grpcServiceConnectorPort: $GRPC_SERVICE_CONNECTOR_PORT" >> config-delegate.yml
> elif [[ "$(grep grpcServiceConnectorPort config-delegate.yml | cut -d ' ' -f 2)" != "${grpcServiceConnectorPort}" ]]; then
> ```

Also wrong. Should be != "$GRPC_SERVICE_CONNECTOR_PORT"

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 144 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-MyxYOhHAfb-tbYVdNMB:-MyzZlcP7ZTLcH4WmPEg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L144)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

Why -f 3? It should also be -f 2.
</blockquote></details>

Done.
___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 198 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-MyxYnwP7MontY1fxuGi:-MyzZjS16g_sh_TOW0l4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L198)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

This is wrong. Should be != "$GRPC_SERVICE_ENABLED"
</blockquote></details>

Done.
___
*[400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, line 204 at r2](https://reviewable.io/reviews/harness/harness-core/31081#-MyxYytb32MZZApMZM1p:-MyzZjr5E5ysvOdq34p9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef59149094aee90d3e50b6752fb440d87f55b861/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L204)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

Also wrong. Should be != "$GRPC_SERVICE_CONNECTOR_PORT"
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
trigger tin1

**Review by brettzu — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger ti1

**Review by brettzu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
Time stamp for config-delegate.yml not updated on upgraded 
image

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger ti1

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31081)* status: :shipit: complete! ✓

**Pull request merged**
