### PR TITLE
feat: [cds-46416]: rbac for env variables

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Have added rbac check for secret type of variables.
Verfied by adding a secret type of environment variable.
image

image

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41963)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 271 at r2](https://reviewable.io/reviews/harness/harness-core/41963#-NKBwJ0QB1tUmdMPrymg:-NKBwJ0QB1tUmdMPrymh:b-rot3b6) ([raw file](https://github.com/harness/harness-core/blob/7f61477568110b28d86f56610818f853500f42d2/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L271)):*
> ```Java
>         servicePartResponse.getNgServiceConfig(), null, null, ambiance, SERVICE_CONFIG_FILES_SWEEPING_OUTPUT);
>   }
>   private List<NGVariable> getNGVariables(Map<String, Map<String, Object>>... map) {
> ```

argument is not a map, its a list of maps. Or we can generically call it "args.." or something

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/41963#-NKH1PsI6vSkht8FigBy:-NKH1PsJ6lzqqwwoYReD:b-4k7upj) ([raw file](https://github.com/harness/harness-core/blob/7f61477568110b28d86f56610818f853500f42d2/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L82)):*
> ```Java
>         serviceConfig.getNgServiceV2InfoConfig().getServiceDefinition().getServiceSpec().getVariables();
> 
>     check(ambiance, serviceVariables);
> ```

we should call this also ```checkForAccessOrThrow```

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/41963#-NKH1PsI6vSkht8FigBy:-NKHFkBfBCn2IKUPWGYH:bfw6f7l) ([raw file](https://github.com/harness/harness-core/blob/7f61477568110b28d86f56610818f853500f42d2/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepsHelper.java#L82)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should call this also ```checkForAccessOrThrow```
</blockquote></details>

We are already checking in case of services,above this method

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 248 at r4](https://reviewable.io/reviews/harness/harness-core/41963#-NKs3aKjC57X_LVnmIGF:-NKs3aKjC57X_LVnmIGG:b-tzvqsi) ([raw file](https://github.com/harness/harness-core/blob/53d3b838e428a254f007fd041bb1171d5063d928/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L248)):*
> ```Java
>       envToEnvVariables.put(environment.getIdentifier(), NGVariablesUtils.getMapOfVariables(variables));
>       secretNGVariables.addAll(
>           variables.stream().filter(SecretNGVariable.class ::isInstance).collect(Collectors.toList()));
> ```

lets make sure this does not cause NPE

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 258 at r4](https://reviewable.io/reviews/harness/harness-core/41963#-NKs3g0R3X9tXgR6FXZp:-NKs3g0R3X9tXgR6FXZq:b-m1mge6) ([raw file](https://github.com/harness/harness-core/blob/53d3b838e428a254f007fd041bb1171d5063d928/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L258)):*
> ```Java
>             parameters.getEnvToSvcOverrideInputs().get(environment.getIdentifier()));
> 
>         svcOverrideVariables = ngServiceOverrides.getServiceOverrideInfoConfig().getVariables();
> ```

we need to add these also to `secretNGVariables`

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 351 at r4](https://reviewable.io/reviews/harness/harness-core/41963#-NKs3s3l-XOAcFgF-Rkz:-NKs3s3l-XOAcFgF-Rl-:b-a6k7vr) ([raw file](https://github.com/harness/harness-core/blob/53d3b838e428a254f007fd041bb1171d5063d928/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L351)):*
> ```Java
>       List<NGVariable> ngVariables = new ArrayList<>();
>       ngVariables.addAll(emptyIfNull(ngEnvironmentConfig.getNgEnvironmentInfoConfig()
>                                          .getVariables()
> ```

if variables are null, will this not throw NPE ?

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 248 at r4](https://reviewable.io/reviews/harness/harness-core/41963#-NKs3aKjC57X_LVnmIGF:-NKv8q_l5tBmN-muvdvs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53d3b838e428a254f007fd041bb1171d5063d928/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L248)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets make sure this does not cause NPE
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 258 at r4](https://reviewable.io/reviews/harness/harness-core/41963#-NKs3g0R3X9tXgR6FXZp:-NKv94t73d2VR_vgP_4u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53d3b838e428a254f007fd041bb1171d5063d928/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L258)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we need to add these also to `secretNGVariables`
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 271 at r2](https://reviewable.io/reviews/harness/harness-core/41963#-NKBwJ0QB1tUmdMPrymg:-NKv97a33XDZSTq9nLEq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7f61477568110b28d86f56610818f853500f42d2/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L271)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

argument is not a map, its a list of maps. Or we can generically call it "args.." or something
</blockquote></details>

Done.

**Comment by vivekkarnatiharness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 351 at r4](https://reviewable.io/reviews/harness/harness-core/41963#-NKs3s3l-XOAcFgF-Rkz:-NKv9Akf92O13-UDDnQC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/53d3b838e428a254f007fd041bb1171d5063d928/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L351)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if variables are null, will this not throw NPE ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41963)* status: :shipit: complete! ✓

**Pull request merged**
