### PR TITLE
feat: [CDS-39624]: Support Expression for cloud provider in Cloud formation steps

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36311)

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java` line 227 at r1](https://reviewable.io/reviews/harness/harness-core/36311#-N9m1c3G19IrsR4fzdKO:-N9m1c3G19IrsR4fzdKP:b-9zsi1e) ([raw file](https://github.com/harness/harness-core/blob/3e31d26f697d482fa8802d3ddf9edd6feba8d5ca/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java#L227)):*
> ```Java
>         awsConfig = getAwsConfig(awsConfigId);
>       }
>     } else if (isInfraCloudProviderAsExpression()) {
> ```

add feature flag too
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/36311#-N9m1QiI3mcAMDX-9dQG:-N9m1QiI3mcAMDX-9dQH:b-adf1km) ([raw file](https://github.com/harness/harness-core/blob/3e31d26f697d482fa8802d3ddf9edd6feba8d5ca/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java#L251)):*
> ```Java
>     }
>     SettingAttribute settingAttribute =
>         settingsService.getSettingAttributeByName(context.getAccountId(), renderedExpression);
> ```

can you check if at other places we use name or id in expression?

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/36311#-N9m1QiI3mcAMDX-9dQG:-NA5wpcF8IZ3qBFM7UMh:bh8lctw) ([raw file](https://github.com/harness/harness-core/blob/707d4ea7ed1fc2abd9340c59192d68a3b13299e7/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java#L251)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

can you check if at other places we use name or id in expression?
</blockquote></details>

yes, in the examples I saw use the id

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java` line 227 at r1](https://reviewable.io/reviews/harness/harness-core/36311#-N9m1c3G19IrsR4fzdKO:-NA5wwpkBGTfkpmGeVm1:beygwad) ([raw file](https://github.com/harness/harness-core/blob/707d4ea7ed1fc2abd9340c59192d68a3b13299e7/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationState.java#L227)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

add feature flag too
</blockquote></details>

it was added.

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36311)* status: :shipit: complete! ✓

**Pull request merged**
