### PR TITLE
feat: [CDS-75126]: change in error message for harness approval activity addition through api

### PR DESCRIPTION
**Pull request by sourabh-awashti**
## Describe your changes
 change in error message for harness approval activity addition through api
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50944)

### CODE REVIEW

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/50944#-NaAgS6d-a8LVKX-rLXr:-NaAgS6d-a8LVKX-rLXs:b-rf3zu0) ([raw file](https://github.com/harness/harness-core/blob/d7a13646007600114494fab8cda8ee258029e569/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L162)):*
> ```Java
>     } else if (instance.getType() != ApprovalType.HARNESS_APPROVAL) {
>       throw new InvalidRequestException(
>           String.format("Approval Activity can not be added for Approval step of type : %s", instance.getType()));
> ```

I think we should also say that this is supported only for Harness Approval

**Comment by sourabh-awashti** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/50944#-NaAgS6d-a8LVKX-rLXr:-NaAiqpY3P5jJ-NxAhDv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d7a13646007600114494fab8cda8ee258029e569/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L162)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think we should also say that this is supported only for Harness Approval 
</blockquote></details>

done

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by naman-goenka — DISMISSED** [review]

**Review by archit-harness — DISMISSED** [review]

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/50944#-NaAgS6d-a8LVKX-rLXr:-NaBMhPf8nO81GaAW_Mv:bsxvgb) ([raw file](https://github.com/harness/harness-core/blob/d7a13646007600114494fab8cda8ee258029e569/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java#L162)):*
<details><summary><i>Previously, sourabh-awashti wrote…</i></summary><blockquote>

done
</blockquote></details>

We should not say "added" because in future, different callers might be calling it

maybe just say

"
Operation not permitted for harness approval step ... 
"

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50944)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50944)* status: :shipit: complete! ✓

**Pull request merged**
