### PR TITLE
fix: [CDS-40991]: jira step hung, no error, no update

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36483)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36483)

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36483)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionMonitorHandler.java` line 242 at r1](https://reviewable.io/reviews/harness/harness-core/36483#-N9lOcehE7P-ObxfbpLs:-N9lOcehE7P-ObxfbpLt:b12gr6t) ([raw file](https://github.com/harness/harness-core/blob/4d85ea1852fb436f6283bf835e9cd11712facb4b/400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionMonitorHandler.java#L242)):*
> ```Java
>   }
> 
>   private void checkIfStateExecutionIsStartingOrRunningWithoutResponse(
> ```

Add a unit test to this method, you can use the annotation VisibleForTesting to simplify the case.
___
*[`400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java` line 2187 at r1](https://reviewable.io/reviews/harness/harness-core/36483#-N9lP5DOEMUFJtl5M5Gp:-N9lP5DOEMUFJtl5M5Gq:bo638i9) ([raw file](https://github.com/harness/harness-core/blob/4d85ea1852fb436f6283bf835e9cd11712facb4b/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L2187)):*
> ```Java
> 
>     StateExecutionData stateExecutionData = stateExecutionMap.get(stateExecutionInstance.getDisplayName());
>     if (stateExecutionData != null) {
> ```

If possible, try add unit test here too.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36483)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36483)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36483)* status: :shipit: complete! ✓

**Pull request merged**
