### PR TITLE
feat: [PL-30603]: Reindexing only specific modules using srcsGlob

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
* If indexSrcsGlob specified, then always re-index those files
* Use harness symbols first then fallback to maven targets to overcome harness modules in maven workspace
* Save index to file only if really updated
* if both indexSrcsGlob and overrideIndex NOT specified and index already exists, then don't update it. This is very expensive operation and the default one, so if you really want to update entire index, you need to specify overrideIndex option

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)

### CODE REVIEW

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/41988#-NKF5suO4Q9FCzDfmCOK:-NKF5suO4Q9FCzDfmCOL:b9a8opp) ([raw file](https://github.com/harness/harness-core/blob/354958d205ba1476af6167070f516274e9e6a656/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L164)):*
> ```Java
>   @NonNull
>   private SymbolDependencyMap initDependencyMap() throws IOException, ClassNotFoundException {
>     if (indexFileExists() && options.hasOption("overrideIndex") && options.hasOption("indexSourceGlob")) {
> ```

Let's update initDependencyMap with overrideIndex too and if overrideIndex is given, we should just erase and create.



_Code quote:_
```Java
&& options.hasOption("overrideIndex") 
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/41988#-NKF6Ll-EY3LDHySosub:-NKF6Ll-EY3LDHySosuc:b-u23j3n) ([raw file](https://github.com/harness/harness-core/blob/354958d205ba1476af6167070f516274e9e6a656/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L220)):*
> ```Java
>         logger.error("No build dependency found for {}", importStatement);
>       }
>     }
> ```

This ensured we don't create an empty build file when sources are present. This comes handy when recursive option is set - any reason to change this?



_Code quote:_
```Java
    // Create build for the package.
    Set<String> sourceFiles = getSourceFiles(workspace().resolve(path));
    if (sourceFiles.isEmpty()) {
      return Optional.empty();
    }
```

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/41988#-NKF5suO4Q9FCzDfmCOK:-NKKQSkd4RfVxOpTLNw9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/354958d205ba1476af6167070f516274e9e6a656/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L164)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Let's update initDependencyMap with overrideIndex too and if overrideIndex is given, we should just erase and create.
</blockquote></details>

Done.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/41988#-NKF6Ll-EY3LDHySosub:-NKFB-qe6IPFp4MywtLI:b-o80her) ([raw file](https://github.com/harness/harness-core/blob/354958d205ba1476af6167070f516274e9e6a656/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L220)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

This ensured we don't create an empty build file when sources are present. This comes handy when recursive option is set - any reason to change this?
</blockquote></details>

Not removed just moved up to fail fast if no sources.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41988)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger messagecheck

**Pull request merged**
