### PR TITLE
feat: [PL-22565]: Add accountIdentifier in User Resource APIs

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31737)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31737)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java, line 135 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKfgl710fckRxUFo-:-MyxKfgl710fckRxUFo0:bo37wm3) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java#L135)):*
> ```Java
>   public ResponseDTO<InviteDTO>
>   getInviteWithToken(@Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @QueryParam(
>                          "accountIdentifier") String accountIdentifier,
> ```

We can use ACCOUNT_KEY constant instead of hardcoding "accountIdentifier"
___
*[120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java, line 318 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKjplCBPiDsCz3LHS:-MyxKjplCBPiDsCz3LHT:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java#L318)):*
> ```Java
>   public ResponseDTO<Optional<InviteDTO>>
>   delete(@Parameter(description = ACCOUNT_PARAM_MESSAGE, required = true) @QueryParam(
>              "accountIdentifier") String accountIdentifier,
> ```

same as above
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 161 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKqbL6hjqOI6MPC1B:-MyxKqbL6hjqOI6MPC1C:bs5f4re) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L161)):*
> ```Java
>       })
>   public ResponseDTO<TwoFactorAuthSettingsInfo>
>   getTwoFactorAuthSettingsInfo(@Parameter(description = "Account Identifier", required = true) @QueryParam(
> ```

should use the given constant as used at other places instead of "Account Identifier"



_Code quote (from 120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java):_
```Java
ACCOUNT_PARAM_MESSAGE
```
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 470 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKwkF0mWA-rU-czK8:-MyxKwkF0mWA-rU-czK9:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L470)):*
> ```Java
>       })
>   public ResponseDTO<UserInfo>
>   updateUserInfo(@Parameter(description = "Account Identifier", required = true)
> ```

same
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 490 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKxjk-KXLetSkriA5:-MyxKxjk-KXLetSkriA6:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L490)):*
> ```Java
>       })
>   public ResponseDTO<PasswordChangeResponse>
>   changeUserPassword(@Parameter(description = "Account Identifier", required = true) @QueryParam(
> ```

same
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 507 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKyTN4g_Q2NJUT_XJ:-MyxKyTN4g_Q2NJUT_XK:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L507)):*
> ```Java
>   @FeatureRestrictionCheck(FeatureRestrictionName.TWO_FACTOR_AUTH_SUPPORT)
>   public ResponseDTO<UserInfo>
>   updateTwoFactorAuthInfo(@Parameter(description = "Account Identifier", required = true) @QueryParam(
> ```

same
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 524 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKz5A84davcWif9on:-MyxKz5A84davcWif9oo:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L524)):*
> ```Java
>   @FeatureRestrictionCheck(FeatureRestrictionName.TWO_FACTOR_AUTH_SUPPORT)
>   public ResponseDTO<UserInfo>
>   disableTFA(@Parameter(description = "Account Identifier", required = true) @QueryParam(
> ```

same

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31737)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java, line 135 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKfgl710fckRxUFo-:-MyxPs_J90ZP6f9rlYRM:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java#L135)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We can use ACCOUNT_KEY constant instead of hardcoding "accountIdentifier"
</blockquote></details>

Done
___
*[120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java, line 318 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKjplCBPiDsCz3LHS:-MyxPv5o3W9Pp5UZ6tT8:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java#L318)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 161 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKqbL6hjqOI6MPC1B:-MyxPyWK9FPC_wQ7Ahyi:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L161)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should use the given constant as used at other places instead of "Account Identifier"
</blockquote></details>

Done
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 470 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKwkF0mWA-rU-czK8:-MyxQ-C4AP9EmguIECXM:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L470)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 490 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKxjk-KXLetSkriA5:-MyxQ0Y42CSJUe1qbqLT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L490)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 507 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKyTN4g_Q2NJUT_XJ:-MyxQ1jf07ZAL6JDLGzX:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L507)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done
___
*[123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, line 524 at r1](https://reviewable.io/reviews/harness/harness-core/31737#-MyxKz5A84davcWif9on:-MyxQ2aM75B3O33RELBl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a88ea050302e7d7f2b1ff0cd4f3ee6181d53df8/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L524)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31737#-:-MyxSXxX0YfpcjKokq_o:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31737)* status: :shipit: complete! ✓

**Pull request merged**
