### PR TITLE
[feat]: [SEI-1683]: - Register SEI resources, permissions and scopes on harness 

### PR DESCRIPTION
**Pull request by ashish-levelops**
## Describe your changes
https://harness.atlassian.net/wiki/spaces/LEV/pages/21417754907/SEI+on+Harness+User+Experience#SEI-Resources
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52688)

### CODE REVIEW

**Comment by ashish-levelops** [comment]
trigger commonchecks

**Comment by ashish-levelops** [comment]
trigger messagecheck

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
trigger checkstylecodeformat

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
trigger checkstylecodeformat

**Comment by ashish-levelops** [comment]
trigger checkstylecodeformat

**Comment by ashish-levelops** [comment]
trigger ut6

**Comment by ashish-levelops** [comment]
trigger checkstylecodeformat

**Comment by ashish-levelops** [comment]
trigger uts

**Comment by ashish-levelops** [comment]
trigger ut4

**Comment by ashish-levelops** [comment]
trigger ut7

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52688)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1691 at r5](https://reviewable.io/reviews/harness/harness-core/52688#-NeEIbOE8qsRolAigl_5:-NeEIbOE8qsRolAigl_6:ber3lyk) ([raw file](https://github.com/harness/harness-core/blob/c5ef22f92f2673b077b71bc0130a6839d54b2812/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1691)):*
> ```YAML
>     includedInAllRoles: false
>     allowedScopeLevels:
>       - account
> ```

I think we concluded that allowedScopeLevels will be same for entity for all CRUD operations.
___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImplTest.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/52688#-NeEJA0W1uUkYMJInEZk:-NeEJA0W1uUkYMJInEZl:b-bwsiij) ([raw file](https://github.com/harness/harness-core/blob/c5ef22f92f2673b077b71bc0130a6839d54b2812/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImplTest.java#L23)):*
> ```Java
>   @Test
>   @Category(UnitTests.class)
>   public void test() {
> ```

Give test name to be meaningful.

**Review by ashish-levelops — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52688)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1691 at r5](https://reviewable.io/reviews/harness/harness-core/52688#-NeEIbOE8qsRolAigl_5:-NeEKiLV6hfxn-p5aCcI:b-2ndb92) ([raw file](https://github.com/harness/harness-core/blob/c5ef22f92f2673b077b71bc0130a6839d54b2812/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1691)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think we concluded that allowedScopeLevels will be same for entity for all CRUD operations.
</blockquote></details>

Good catch, missed this one, added now
___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImplTest.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/52688#-NeEJA0W1uUkYMJInEZk:-NeEKpBP4N6m8bY08iAR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5ef22f92f2673b077b71bc0130a6839d54b2812/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImplTest.java#L23)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Give test name to be meaningful.
</blockquote></details>

Done.

**Comment by ashish-levelops** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52688)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImplTest.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/52688#-NeEJA0W1uUkYMJInEZk:-NeEV4rK0G-VCkkM3kha:b-80t3c3) ([raw file](https://github.com/harness/harness-core/blob/c5ef22f92f2673b077b71bc0130a6839d54b2812/platform-service/modules/resource-group-service/src/test/java/io/harness/resourcegroup/resourceclient/sei/SEIConfigurationSettingsResourceImplTest.java#L23)):*
<details><summary><i>Previously, ashish-levelops (ashish-levelops) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

cc @manish-manchanda @ashishsanodia-harness

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 5 of 11 files at r2, 1 of 1 files at r3, 4 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52688)* status: :shipit: complete! ✓

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1691 at r5](https://reviewable.io/reviews/harness/harness-core/52688#-NeEIbOE8qsRolAigl_5:-NeEVLHpCCJPkZfEaSPY:b-80t3c3) ([raw file](https://github.com/harness/harness-core/blob/c5ef22f92f2673b077b71bc0130a6839d54b2812/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1691)):*
<details><summary><i>Previously, ashish-levelops (ashish-levelops) wrote…</i></summary><blockquote>

Good catch, missed this one, added now
</blockquote></details>

cc @manish-manchanda @ashishsanodia-harness

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52688#-:-NeEVR2c1Xv45Ci2OS9i:bnfp4nl)* status: :shipit: complete! ✓

**Comment by ashish-levelops** [comment]
trigger ut7

**Pull request merged**
