### PR TITLE
feat: [PL-25060]: add validation on Filepath

### PR DESCRIPTION
**Pull request by bhavya181**
Two validations has been added on filepath - 
1. file should have .yaml or .yml extension
2. file path should contain harness directory.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33349)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QxXDQ8CFbqww72I5s:-N2QxXDQ8CFbqww72I5t:b-m3cthm) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L44)):*
> ```Java
>       filePath = filePath.substring(1);
>     }
>     if (filePath.endsWith(FILE_PATH_SEPARATOR)) {
> ```

I think we discussed right that we can get away with these checks as these can be handled by git providers itself

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QxGGG2yX4KpdVUeu-:-N2QxGGG2yX4KpdVUeu0:b-m3cthm) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L41)):*
> ```Java
>       throw new InvalidRequestException(NULL_FILE_PATH_ERROR_MESSAGE);
>     }
>     if (filePath.startsWith(FILE_PATH_SEPARATOR)) {
> ```

I think we discussed right that we can get away with these checks as these can be handled by git providers itself

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QymWHEXKrw0EQlJBy:-N2QymWHEXKrw0EQlJBz:bq21e3s) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L51)):*
> ```Java
> 
>   private static void validateFilePathIsInHarnessDirectory(String filePath) {
>     if (!filePath.startsWith(HARNESS_DIRECTORY)) {
> ```

can you just check in our current code where we such kind of checks? I am bit doubtful that .startsWith() does some regex and passes some false cases as well.
@deepakpatankar do you remember that these checks used to fail for us?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QxGGG2yX4KpdVUeu-:-N2QzluA-ndJyyvurrv9:bcrp9p2) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we discussed right that we can get away with these checks as these can be handled by git providers itself
</blockquote></details>

this is not a check, I am just removing starting and ending slash for checking .harness and .yaml extension.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QxXDQ8CFbqww72I5s:-N2QzzPG0Dg4MJB5qEec:b-8xet40) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L44)):*
>this is not a check, I am just removing starting and ending slash for checking .harness and .yaml extension.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349)* status: 2 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QxGGG2yX4KpdVUeu-:-N2RmbaO7InpRAkqbUIi:b-xs37t0) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L41)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

this is not a check, I am just removing starting and ending slash for checking .harness and .yaml extension.
</blockquote></details>

as discussed I have put check here only
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QymWHEXKrw0EQlJBy:-N2Rmh3D7dsKrSAtQcR3:bwxcz01) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can you just check in our current code where we such kind of checks? I am bit doubtful that .startsWith() does some regex and passes some false cases as well.
@deepakpatankar do you remember that these checks used to fail for us?
</blockquote></details>

I checked earlier method is doing split, not "starts with", I think it will work in all cases.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33349#-N2QymWHEXKrw0EQlJBy:-N2S-1QD4B23jomxGfu_:b-47aegn) ([raw file](https://github.com/harness/harness-core/blob/2e50d6572b6a37b7a3150cfcfb82f0caab64ec02/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L51)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I checked earlier method is doing split, not "starts with", I think it will work in all cases.
</blockquote></details>

Sure. Resolving for now. Please try with some examples such as : ".harnessharness" etc.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349#-:-N2S-DJYD52rcy9jeIM-:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349#-:-N2VmAvu2rVvjw-6mhm5:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/33349#-N2WEFE9A50GpmnKXzGy:-N2WEFEA-RHpAHVuxmgx:bjric3c) ([raw file](https://github.com/harness/harness-core/blob/767db848aa80d546ce6578dfdafa8a21be330a3a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L19)):*
> ```Java
>   public static final String FILE_PATH_SEPARATOR = "/";
>   public static final String HARNESS_DIRECTORY_PATH = ".harness/";
>   public static final String FILE_PATH_INVALID_HINT = "Please check the requested filepath if it is valid.";
> ```

Please check if the requested file path is valid

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/33349#-N2WEFE9A50GpmnKXzGy:-N2WExj-A3y4PYHuGqkl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/767db848aa80d546ce6578dfdafa8a21be330a3a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L19)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Please check if the requested file path is valid
</blockquote></details>

Done.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33349#-:-N2WYxts94FuxhKwk_B1:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
