### PR TITLE
fix: [CDS-68526]: Improving error message for cron triggers when validatio…

### PR DESCRIPTION
**Pull request by Y0709**
…n fails due to interval between triggers being less than 5 minutes

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47317)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by vcalasansh — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47317)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 750 at r2](https://reviewable.io/reviews/harness/harness-core/47317#-NUZt58289OdIkSrtZ-T:-NUZt58289OdIkSrtZ-U:bekvry0) ([raw file](https://github.com/harness/harness-core/blob/478c763b12997e8c118ade8d36ff2629b482255f/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L750)):*
> ```Java
>                 + " minutes. The next two execution times when this trigger is supposed to be fired are "
>                 + firstExecutionTime.toLocalTime().toString() + " and " + secondExecutionTime.toLocalTime().toString()
>                 + " which do not have a difference of " + MIN_INTERVAL_MINUTES + " minutes between them.");
> ```

The grammar for the error message doesn't look right to me. 
` The next two execution times when this trigger is supposed to be fired are `

Can you verify from docs team or internet. We have received tickets for correcting such grammar. 

my suggestion it should read like: 
`The next two execution times when this trigger is suppose to fire are`.

Note: This is a non-blocking comment.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47317)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger commonchecks

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger codebasehash

**Comment by Y0709** [comment]
trigger pmd

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47317)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger pmd

**Comment by Y0709** [comment]
trigger messagecheck

**Comment by Y0709** [comment]
trigger messagecheck

**Comment by Y0709** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
