### PR TITLE
fix: [CI-5959]: 100 builds per day for free users

### PR DESCRIPTION
**Pull request by harshjain12**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39296)

### CODE REVIEW

**Comment by harshjain12** [comment]
trigger messagecheck

**Review by jamie-harness — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39296)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39296)* status: :shipit: complete! ✓

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/39296#-NFP9UK-07rT8ksyfUGK:-NFP9UK04phx8kAko74Z:bh9jmok) ([raw file](https://github.com/harness/harness-core/blob/80edd75b9f8afbd8ab8de50886b3d9d236fe2971/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L265)):*
> ```Java
>     if (licensesWithSummaryDTO != null && licensesWithSummaryDTO.getEdition() == Edition.FREE) {
>       if (level != null && serviceName.equalsIgnoreCase(SERVICE_NAME_CI)
>           && level.getStepType().getStepCategory() == StepCategory.STAGE && (status == QUEUED)) {
> ```

Before calling license, can we check if its for stage event? Plus status queued is correct ?



_Code quote:_
```Java
level.getStepType().getStepCategory() == StepCategory.STAGE && (status == QUEUED
```
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/39296#-NFP9rowB8Tjtb_bQhNW:-NFP9rowB8Tjtb_bQhNX:bmevdv9) ([raw file](https://github.com/harness/harness-core/blob/80edd75b9f8afbd8ab8de50886b3d9d236fe2971/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java#L223)):*
> ```Java
>     String logPrefix = getLogPrefix(ambiance);
>     CIStagePlanCreationUtils.validateFreeAccountStageExecutionLimit(
>         accountExecutionMetadataRepository, ciLicenseService, AmbianceUtils.getAccountId(ambiance));
> ```

shouldnt stage validation be enough?

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39296)* status: :shipit: complete! ✓

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/39296#-NFP9UK-07rT8ksyfUGK:-NFPBISG1_JuHT1oewuh:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/80edd75b9f8afbd8ab8de50886b3d9d236fe2971/332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java#L265)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Before calling license, can we check if its for stage event? Plus status queued is correct ?
</blockquote></details>

discussed offline

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39296)* status: :shipit: complete! ✓

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/39296#-NFP9rowB8Tjtb_bQhNW:-NFPCBTU6erf5huvFgUX:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/80edd75b9f8afbd8ab8de50886b3d9d236fe2971/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java#L223)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt stage validation be enough?
</blockquote></details>

discussed offline

**Pull request merged**
