### PR TITLE
fix: [CDS-81910]: Fix case of Barrier steps inside nested looping strategies

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
In this PR, we add support for barrier steps that are within nested looping strategies.

Previously, when barrier position expansion for strategy kicked in, we were directly removing the dummy barrier position. This means we were assuming that only one strategy expansion would be needed for every dummy position. This is not the case if we have multiple nested strategy blocks (think about a step-group-with-strategy within a stage-with-strategy).

To address this issue, we are now storing the full chain of nested strategySetupIds that are parents of a Barrier Node. Whenever one of these strategies kicks in for spawning its children, we are updating the map `BarrierExecutionInstance.SetupInfo.strategyConcurrencyMap` with the number of iterations of this strategy. 

In this way, we can calculate how many barrier positions we are supposed to have after all strategies are expanded, and only after reaching this number of expanded barrier do we remove the dummy barrier position. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54261)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/54261#-Nh56pJw3IMUuKYVyNxZ:-Nh56pJw3IMUuKYVyNx_:bkxgimu) ([raw file](https://github.com/harness/harness-core/blob/258c3e94c15cce1f6e4b1594ab6929572aa0226b/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L52)):*
> ```Java
>       PlanCreatorConstants.STAGE_FAILURE_STRATEGIES, PlanCreatorConstants.STAGE_ID,
>       PlanCreatorConstants.STEP_GROUP_FAILURE_STRATEGIES, PlanCreatorConstants.STEP_GROUP_ID,
>       PlanCreatorConstants.STRATEGY_ID, PlanCreatorConstants.STRATEGY_NODE_TYPE, PlanCreatorConstants.YAML_VERSION);
> ```

nit: can we rename this to NEAREST_STRATEGY_ID?

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 13 files at r2, 10 of 11 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54261)* status: Some of the checks are too old. 18 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 13 files at r2, 10 of 11 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54261)* status: Some of the checks are too old. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/event/BarrierWithinStrategyExpander.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/54261#-Nh57GEx3pI3jvYZclSz:-Nh57GEx3pI3jvYZclT-:b2nhj9y) ([raw file](https://github.com/harness/harness-core/blob/258c3e94c15cce1f6e4b1594ab6929572aa0226b/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/event/BarrierWithinStrategyExpander.java#L145)):*
> ```Java
>   }
> 
>   private boolean shouldKeepDummyPosition(BarrierPositionInfo.BarrierPosition dummyPosition,
> ```

Let

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54261)* status: :shipit: complete! ✓

**Pull request merged**
