### PR TITLE
fix: [PL-32736]: upgrade org.eclipse.jetty libraries to fix vulns

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Upgrading the following libraries

1. org.eclipse.jetty.http2:http2-common from 9.4.48.v20220622 -> 9.4.51.v20230217
2. org.eclipse.jetty.http2:http2-hpack from 9.4.48.v20220622 -> 9.4.51.v20230217
3. org.eclipse.jetty.http2:http2-server from 9.4.48.v20220622 -> 9.4.51.v20230217
4. org.eclipse.jetty.websocket:websocket-api from 9.4.48.v20220622 -> 9.4.51.v20230217
5. org.eclipse.jetty.websocket:websocket-client from 9.4.48.v20220622 -> 9.4.51.v20230217
6. org.eclipse.jetty.websocket:websocket-common from 9.4.48.v20220622 -> 9.4.51.v20230217
7. org.eclipse.jetty.websocket:websocket-server from 9.4.48.v20220622 -> 9.4.51.v20230217
8. org.eclipse.jetty.websocket:websocket-servlet from 9.4.48.v20220622 -> 9.4.51.v20230217
9. org.eclipse.jetty:jetty-alpn-openjdk8-server from 9.4.48.v20220622 -> 9.4.51.v20230217
10. org.eclipse.jetty:jetty-alpn-server from 9.4.48.v20220622 -> 9.4.51.v20230217
11. org.eclipse.jetty:jetty-client from 9.4.48.v20220622 -> 9.4.51.v20230217
12. org.eclipse.jetty:jetty-continuation from 9.4.48.v20220622 -> 9.4.51.v20230217
13. org.eclipse.jetty:jetty-http from 9.4.48.v20220622 -> 9.4.51.v20230217
14. org.eclipse.jetty:jetty-io from 9.4.48.v20220622 -> 9.4.51.v20230217
15. org.eclipse.jetty:jetty-security from 9.4.48.v20220622 -> 9.4.51.v20230217
16. org.eclipse.jetty:jetty-server from 9.4.48.v20220622 -> 9.4.51.v20230217
17. org.eclipse.jetty:jetty-servlet from 9.4.48.v20220622 -> 9.4.51.v20230217
18. org.eclipse.jetty:jetty-servlets from 9.4.48.v20220622 -> 9.4.51.v20230217
19. org.eclipse.jetty:jetty-util from 9.4.48.v20220622 -> 9.4.51.v20230217
20. org.eclipse.jetty:jetty-webapp from 9.4.48.v20220622 -> 9.4.51.v20230217
21. org.eclipse.jetty:jetty-xml from 9.4.48.v20220622 -> 9.4.51.v20230217

**Tests done**

end to end k8 cg deployment
end to end k8 ng deployment
end to end k8 ng deployment with delegate which doesn't have this change

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46911)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger ut2

**Comment by raghuAtWings** [comment]
trigger ut5

**Comment by raghuAtWings** [comment]
trigger ut9

**Comment by raghuAtWings** [comment]
trigger ut5

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
trigger ss

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46911)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
