### PR TITLE
[feat]: [CDS-71224]: Fixing the redis-queue-time metric graph for PMS events

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Fixing the redis-queue-time metric graph for PMS events.
Related DOC: https://harness.atlassian.net/wiki/spaces/PIPE/pages/21404647460/01+June-2023+Load-test#Action-items%3A.1

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48821)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48821)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/48821#-NXE9TMk89cc24fSM0SC:-NXE9TMk89cc24fSM0SD:bid5vx2) ([raw file](https://github.com/harness/harness-core/blob/ee5c368f96be357491faa79873ae2129b5f46ca4/884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java#L23)):*
> ```Java
> 
>   @Override
>   public void handleEvent(NotifyEventProto event, Map<String, String> metadataMap, long timeSpentInQueue) {
> ```

as of now this timeStamp is message timestamp when it was created, so i don't think we should change this and same for others, you can add comment or change variable to reflect it i don't see anyone using.

Because sending timeInqueue down the line doesn't help them

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48821)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/48821#-NXE9TMk89cc24fSM0SC:-NXEKtkADsAkwbwbV012:bqnvbu5) ([raw file](https://github.com/harness/harness-core/blob/ee5c368f96be357491faa79873ae2129b5f46ca4/884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as of now this timeStamp is message timestamp when it was created, so i don't think we should change this and same for others, you can add comment or change variable to reflect it i don't see anyone using.

Because sending timeInqueue down the line doesn't help them
</blockquote></details>

Ok. I am passing one more parameter readTs along with messageTimestamp. So that everything is available. The time taken in queue as well as message timeStamp.

**Comment by brijeshdhakar** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/48821#-NXE9TMk89cc24fSM0SC:-NXE_Vr6-xlzfT5-fCXD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee5c368f96be357491faa79873ae2129b5f46ca4/884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java#L23)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Ok. I am passing one more parameter readTs along with messageTimestamp. So that everything is available. The time taken in queue as well as message timeStamp.
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48821)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/sdk/execution/events/PmsCommonsBaseEventHandler.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/48821#-NXEabcy6utdWZRTt63m:-NXEabcy6utdWZRTt63n:bta456i) ([raw file](https://github.com/harness/harness-core/blob/fc46d12bf02bf1ecb5c20d2fa51761ea2e7ac1b4/953-yaml-commons/src/main/java/io/harness/pms/sdk/execution/events/PmsCommonsBaseEventHandler.java#L17)):*
> ```Java
> @TargetModule(HarnessModule._884_PMS_COMMONS)
> public interface PmsCommonsBaseEventHandler<T> {
>   void handleEvent(T event, Map<String, String> metadataMap, long messageTimeStamp, long readTs);
> ```

nit: add comments what each value of timestamp refers to

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger codebasehash

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48821)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/sdk/execution/events/PmsCommonsBaseEventHandler.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/48821#-NXEabcy6utdWZRTt63m:-NXF170rBoq02ZoDhKnW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fc46d12bf02bf1ecb5c20d2fa51761ea2e7ac1b4/953-yaml-commons/src/main/java/io/harness/pms/sdk/execution/events/PmsCommonsBaseEventHandler.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: add comments what each value of timestamp refers to
</blockquote></details>

done

**Pull request merged**
