### PR TITLE
[feat]: [PL-26203]: adding yaml expression evaluator and secret functor

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
Evaluator and functor needed for schell script resolution for custom secret manager - ng
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36564)

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-WPAg6GZHB1sXbgZ1:-NA-WPAg6GZHB1sXbgZ2:buuri2i) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L71)):*
> ```Java
>       return yamlField.getNode().getField(CONNECTOR_ROOT_FIELD);
>     } catch (IOException e) {
>       log.info("Connector root field is not present in " + yaml);
> ```

log.error()

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-WPAg6GZHB1sXbgZ1:-NA-WRLJ150LR6skXRmS:buq1xsw) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log.error()
</blockquote></details>

also log the exception here

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-WfQzEfn_bAVcPWxV:-NA-WfQzEfn_bAVcPWxW:bw5k931) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L39)):*
> ```Java
>   public static final String SECRETS_PREFIX = "secrets";
>   public static final String YAML_EXPRESSION_CONNECTOR_PREFIX = "__yamlExpression.connector";
>   public static final String CONNECTOR_ROOT_FIELD = "connector";
> ```

any reason why all the above fields are public? specially functorToken.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-X6wi3tu7dC1zqB9Q:-NA-X6wi3tu7dC1zqB9R:bowwwrl) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L38)):*
> ```Java
>     // Check child first
>     if (currentElementMap.containsKey(expression)) {
>       return currentElementMap.get(expression);
> ```

nit: we could write it as "return currentElementMap.getOrDefault(expression,null);"

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-X6wi3tu7dC1zqB9Q:-NA-XGg46nOj8C16X_5k:b-bmvcts) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L38)):*
> nit: we could write it as "return currentElementMap.getOrDefault(expression,null);"

it would allow us not to check the key first in the if statement

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-XfTD886dip-nExH1:-NA-XfTD886dip-nExH2:b-jz8wvq) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L58)):*
> ```Java
> 
>     if (EmptyPredicate.isNotEmpty(valueMap)) {
>       fqnToValueMap.put(String.join(".", fqnList), valueMap);
> ```

can we create constant for the separator

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-Y6XVDAsXbINxyH_M:-NA-Y6XVDAsXbINxyH_N:b-qy74ux) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L77)):*
> ```Java
>       if (EmptyPredicate.isEmpty(arrayElement.getIdentifier())
>           && EmptyPredicate.isNotEmpty(arrayElement.getArrayUniqueIdentifier())) {
>         contextMap.put(arrayElement.getArrayUniqueIdentifier(), arrayElement.getField("value").getNode().asText());
> ```

constant ^

**Review by meenakshi-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564#-:-NA-o0V6DH-G6p9K33DD:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by shreyas-harness** [comment]
> _[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-WPAg6GZHB1sXbgZ1:-NA-WPAg6GZHB1sXbgZ2:buuri2i) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L71)):_
> 
> > ```java
> >       return yamlField.getNode().getField(CONNECTOR_ROOT_FIELD);
> >     } catch (IOException e) {
> >       log.info("Connector root field is not present in " + yaml);
> > ```
> 
> log.error()

Done

**Comment by shreyas-harness** [comment]
> _[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-Y6XVDAsXbINxyH_M:-NA-Y6XVDAsXbINxyH_N:b-qy74ux) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L77)):_
> 
> > ```java
> >       if (EmptyPredicate.isEmpty(arrayElement.getIdentifier())
> >           && EmptyPredicate.isNotEmpty(arrayElement.getArrayUniqueIdentifier())) {
> >         contextMap.put(arrayElement.getArrayUniqueIdentifier(), arrayElement.getField("value").getNode().asText());
> > ```
> 
> constant ^

Done

**Comment by shreyas-harness** [comment]
> _[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-WPAg6GZHB1sXbgZ1:-NA-WPAg6GZHB1sXbgZ2:buuri2i) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L71)):_
> 
> > ```java
> >       return yamlField.getNode().getField(CONNECTOR_ROOT_FIELD);
> >     } catch (IOException e) {
> >       log.info("Connector root field is not present in " + yaml);
> > ```
> 
> log.error()

Done

**Comment by shreyas-harness** [comment]
> _[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-XfTD886dip-nExH1:-NA-XfTD886dip-nExH2:b-jz8wvq) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L58)):_
> 
> > ```java
> >     if (EmptyPredicate.isNotEmpty(valueMap)) {
> >       fqnToValueMap.put(String.join(".", fqnList), valueMap);
> > ```
> 
> can we create constant for the separator

Done

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)* status: 6 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-X6wi3tu7dC1zqB9Q:-NA-z0-l0mieYg--c11t:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

> nit: we could write it as "return currentElementMap.getOrDefault(expression,null);"

it would allow us not to check the key first in the if statement
</blockquote></details>

Done

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)* status: 3. unresolved discussions.

**Review by meenakshi-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)* status: 3. unresolved discussions.

**Review by shreyas-harness — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)* status: 4. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/36564#-NA-WfQzEfn_bAVcPWxV:-NA-zykb3qn4fHSgjGMQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/73f9f9954c39cb9bfdfb230b05f3bcf1ad4563c8/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

any reason why all the above fields are public? specially functorToken.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)* status: :shipit: complete! ✓

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36564)* status: :shipit: complete! ✓

___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA08ys19s9tUf9JVn00:-NA08ys19s9tUf9JVn01:b41428u) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L30)):*
> ```Java
> @OwnedBy(PL)
> @Value
> @Builder
> ```

we have a constructor and a builder both -- are both needed? Generally builders are required to chain creation when we have a long of optional arguments (DTO type objects). 



_Code quote:_
```Java
@Builder
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA05Sq85Sesj_XxxjG-:-NA05Sq85Sesj_XxxjG0:bdi90to) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L77)):*
> ```Java
> 
>   @Override
>   public Object resolve(Object o, boolean skipUnresolvedExpressionsCheck) {
> ```

nit: General convention is to put your public functions first, followed by protected and then private
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA06Wra2pwlIk_iqTQ7:-NA06Wra2pwlIk_iqTQ8:bzed1tq) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L77)):*
> ```Java
> 
>   @Override
>   public Object resolve(Object o, boolean skipUnresolvedExpressionsCheck) {
> ```

Please add javadoc to the public method
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA0A6yn2SgabKF2efMx:-NA0A6yn2SgabKF2efMy:bac4t4y) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L78)):*
> ```Java
>   @Override
>   public Object resolve(Object o, boolean skipUnresolvedExpressionsCheck) {
>     ExpressionMode expressionMode = skipUnresolvedExpressionsCheck ? ExpressionMode.RETURN_NULL_IF_UNRESOLVED
> ```

add unit tests for unresolved cases



_Code quote:_
```Java
    ExpressionMode expressionMode = skipUnresolvedExpressionsCheck ? ExpressionMode.RETURN_NULL_IF_UNRESOLVED
                                                                   : ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED;
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA08wfY9EzGLliKaaOZ:-NA08wfY9EzGLliKaaO_:b-b1nfmi) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L27)):*
> ```Java
> @OwnedBy(PL)
> @Value
> @Builder
> ```

did we need a builder pattern here? Looks like there is only argument yamlRootField, could just have been a simple constructor



_Code quote:_
```Java
@Builder
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA06K_44FY44NFaung8:-NA06K_44FY44NFaung9:bi9q2mi) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L32)):*
> ```Java
>   YamlField rootYamlField;
>   private final String FQN_DELIMITER = ".";
>   private final String VALUE_FIELD_NAME = "value";
> ```

Mark these constants static



_Code quote:_
```Java
  private final String FQN_DELIMITER = ".";
  private final String VALUE_FIELD_NAME = "value";
```
___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA0Bdft5RTpGWvi5BHb:-NA0Bdft5RTpGWvi5BHc:b5mtxe) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java#L67)):*
> ```Java
>   }
> 
>   private Map<String, Object> getValueFromArray(
> ```

Add test cases for Array types / primitive and objects both.



_Code quote:_
```Java
 private Map<String, Object> getValueFromArray(
```
___
*[`878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA01tQtAqqcWBowCxso:-NA01tQtAqqcWBowCxsp:bs9b1x6) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java#L37)):*
> ```Java
>    Other use cases might need new yaml string creation as well but the above acts as a simple example for most cases.
>    */
>   private String yamlBeforeScript = "---\n"
> ```

mark these constants final



_Code quote:_
```Java
ring 
```
___
*[`878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA02YfR8wzsfeYVFHcH:-NA02YfR8wzsfeYVFHcI:b-b6c85c) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java#L37)):*
> ```Java
>    Other use cases might need new yaml string creation as well but the above acts as a simple example for most cases.
>    */
>   private String yamlBeforeScript = "---\n"
> ```

nit: constants like these are generally capitalized to differentiate from regular variables - YAML_BEFORE_SCRIPT
___
*[`878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA02FeG8AITMIdPh8eP:-NA02FeG8AITMIdPh8eQ:b-uyxty2) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java#L66)):*
> ```Java
>       + "      type: String\n";
> 
>   StringBuilder scriptStringBuilder = new StringBuilder("        script: ");
> ```

you probably need to re-create this in each test right? otherwise for each test, you would might keep appending to the same variable. Just double check and probably just create a local variable inside the getYaml function



_Code quote:_
```Java
StringBuilder scriptStringBuilder = new StringBuilder("        script: ");
```
___
*[`878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA02kZD2hv16ePFT7l3:-NA02kZD2hv16ePFT7l4:b2tgchn) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java#L68)):*
> ```Java
>   StringBuilder scriptStringBuilder = new StringBuilder("        script: ");
> 
>   public String getYaml(String script) {
> ```

move to the end of the file after tests and mark it private? 



_Code quote:_
```Java
  public String getYaml(String script) {
    return yamlBeforeScript + scriptStringBuilder.append(script).toString() + yamlAfterScript;
  }
```

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/36564#-NA05Sq85Sesj_XxxjG-:-NA0ao6hCBt9iMo2IYD2:b32v57) ([raw file](https://github.com/harness/harness-core/blob/a6455863f6680b0c5aed7c8c6f79cee419d9a2b6/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java#L77)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: General convention is to put your public functions first, followed by protected and then private
</blockquote></details>

+1

**Pull request merged**
