### PR TITLE
feat: [PL-27456]: Adding ability to run parsejars script

### PR DESCRIPTION
**Pull request by gn-harness**
Adding ability to run parsejars script to update package to maven dependency.

This is required to create Maven index file for the build cleaner to function properly.

Primary change is in the WORKSPACE file, where we have added reference to contrib_rules_jvm. Other changes are just a result of pinning the maven / updating maven-manifest.json and updating documentation.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37281)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37281)

**Comment by piyush-harness** [comment]
*[`WORKSPACE` line 5034 at r1](https://reviewable.io/reviews/harness/harness-core/37281#-NBQiTnd5k23fhdGQf22:-NBQiTnd5k23fhdGQf23:ba68ngg) ([raw file](https://github.com/harness/harness-core/blob/5f1a920815f79e15e4014c86ed863015cc24f9b1/WORKSPACE#L5034)):*
> ```Starlark
>             "commons-logging:commons-logging",
>         ],
>         group = "com.amazonaws",
> ```

Why this movement is needed?

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37281)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`tools/build-cleaner/README.md` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37281#-NBQitBb949WOLluBQbu:-NBQitBb949WOLluBQbv:burt9pe) ([raw file](https://github.com/harness/harness-core/blob/5f1a920815f79e15e4014c86ed863015cc24f9b1/tools/build-cleaner/README.md#L52)):*
> ```Markdown
>     2) For resolving the maven targets, we have checked-in ~/main-manifest.json file, which has mapping from java
>        package to maven target.
>         1) This file is generated using parse-jars script, which parses maven jars listed in the
> ```

Do we need to follow 3 steps mentioned here to introduce new dependency? If yes can we provide a script wrapping all of them

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37281)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`WORKSPACE` line 5034 at r1](https://reviewable.io/reviews/harness/harness-core/37281#-NBQiTnd5k23fhdGQf22:-NBQjsC-9xTti_IjKAG-:b-om2dey) ([raw file](https://github.com/harness/harness-core/blob/5f1a920815f79e15e4014c86ed863015cc24f9b1/WORKSPACE#L5034)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this movement is needed?
</blockquote></details>

This was auto updated while pinning.
___
*[`tools/build-cleaner/README.md` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37281#-NBQitBb949WOLluBQbu:-NBQji_VCPA-DuDboALY:b9wnvfo) ([raw file](https://github.com/harness/harness-core/blob/5f1a920815f79e15e4014c86ed863015cc24f9b1/tools/build-cleaner/README.md#L52)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Do we need to follow 3 steps mentioned here to introduce new dependency? If yes can we provide a script wrapping all of them
</blockquote></details>

Yes, I think that is a good idea. I was already asking Diptiman ideas to enforce it - lets discuss this offline separately.

**Comment by gn-harness** [comment]
trigger ti3

**Review by diptiman-adak — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37281)* status: 3 file(s) to review. 2. unresolved discussions.

**Pull request merged**
