### PR TITLE
feat: [CCM-9314]: Recommendation Workflows

### PR DESCRIPTION
**Pull request by trunapushpa**
### UI Mocks

- Please refer to [this figma file](https://www.figma.com/file/WRbavNjd0Hxk3SxYOgWKD0/Recommendations?node-id=4580%3A56104)

### Recommendation Jira

Please refer to these docs:
- [Recommendation Jira database changes](https://harness.atlassian.net/wiki/spaces/CE/pages/21227275549/Recommendation+Jira+Database+changes)
- [Recommendation Jira Integration](https://harness.atlassian.net/wiki/spaces/CE/pages/21212529245/Recommendation+Jira+Integration)

### Recommendation States

- Please refer to this doc: [Recommendation States](https://harness.atlassian.net/wiki/spaces/CE/pages/21227013696/Recommendation+States)

### Jira Creation
```
curl --location --request POST 'http://localhost:7340/ccm/api/recommendation/jira/create?accountIdentifier=kmpySmUISimoRrJL6NL73w' \
--header 'Content-Type: application/json' \
--data-raw '{
    "recommendationId": "60f0e214c88166ff5d4b940d",
    "resourceType": "NODE_POOL",
    "connectorRef": "account.TrunaJira",
    "projectKey": "TJI",
    "issueType": "Task",
    "fields": {
        "summary": "Rightsize GKE Nodepool free-ng-manager",
        "description": "||*Nodepool name*|free-ng-manager|\n||*Cluster name*|ce-prod-cluster-primary|\n||*Region*|us-west1|\n||*Current Instance Family*|e2-highmem-8|\n||*Potential Monthly Savings*|*$2,197.77*|\n||*Recommendation Link*|[https://app.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ce/recommendations/node/60f23167c88166ff5d5c06aa/name/free-ng-manager/details|https://app.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ce/recommendations/node/60f23167c88166ff5d5c06aa/name/free-ng-manager/details]|"
    }
}'
```
Jira ticket created: https://harness.atlassian.net/browse/TJI-104057

### Add resource to ignoreList
```
curl --location --request POST 'http://localhost:7340/ccm/api/recommendation/ignore-list/add?accountIdentifier=kmpySmUISimoRrJL6NL73w' \
--header 'Content-Type: application/json' \
--data-raw '{
    "WORKLOAD": ["accesscontrol-service"]
}'
```

### Remove resource from ignoreList
```
curl --location --request POST 'http://localhost:7340/ccm/api/recommendation/ignore-list/remove?accountIdentifier=kmpySmUISimoRrJL6NL73w' \
--header 'Content-Type: application/json' \
--data-raw '{
    "WORKLOAD": ["accesscontrol-service"]
}'
```

### Mark recommendation as applied
```
curl --location --request POST 'http://localhost:7340/ccm/api/recommendation/overview/mark-applied?accountIdentifier=kmpySmUISimoRrJL6NL73w&recommendationId=60f0e214c88166ff5d4b940d'
```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39401)

### CODE REVIEW

**Review by svmav — COMMENTED** [review]
> Reviewed 16 of 68 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39401)* status: Some of the checks are too old. 53 file(s) to review. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/TimescaleDBMigrationList.java` line 177 at r3](https://reviewable.io/reviews/harness/harness-core/39401#-NJ3XirY5Hys8i8r_Nsn:-NJ3XirZ7ErbyQau4s9L:b3yiwtm) ([raw file](https://github.com/harness/harness-core/blob/28aed806262a393e3276c2c009a83050419020c9/390-db-migration/src/main/java/io/harness/migrations/TimescaleDBMigrationList.java#L177)):*
> ```Java
>         .add(Pair.of(76, BaseTimeScaleDBMigration.class))
>         .add(Pair.of(77, AddInfraIdsToDeploymentsEnvIdsToInfraTable.class))
>         .add(Pair.of(78, CeRecommendationTableAddJiraColumn.class))
> ```

Can we check if we can do this migration from ce-nextgen?

**Review by svmav — COMMENTED** [review]
> Reviewed 1 of 25 files at r1, 50 of 68 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39401)* status: Some of the checks are too old. 0 of 1 approvals obtained.

**Review by nikunj-badjatya — DISMISSED** [review]
> Reviewed 1 of 25 files at r1, 58 of 68 files at r2, 1 of 2 files at r3, 5 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39401)* status: :shipit: complete! ✓

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 23 of 23 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39401)* status: :shipit: complete! ✓

**Pull request merged**
