### PR TITLE
feat: [PL-25727]: config as code more granualar perms

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solution

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)

### CODE REVIEW

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BAltv1-ofrvnbXblX:-N5BAltv1-ofrvnbXblY:b-aymypl) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java#L64)):*
> ```Java
>     try {
>       appId = yamlHelper.getAppId(accountId, filePath);
>     } catch (Exception e) {
> ```

Whether we can throw and catch only some specific exception.

This way we might end up setting appId=Global app id for all the cases

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBJU8ArRgngJz85di:-N5BBJU8ArRgngJz85dj:blbyli2) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java#L119)):*
> ```Java
>         break;
>       default:
>         if (filePath.contains(PATH_DELIMITER + SERVICES_FOLDER + PATH_DELIMITER)) {
> ```

What type is handled here ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1101 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBfmY-JwBS17J8nYm:-N5BBfmY-JwBS17J8nYn:byoo0pi) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1101)):*
> ```Java
>                       auditHelper.setAuditContext(currentAuditHeader);
>                       List changeList = getChangesForZipFile(accountId, fileInputStream, null);
>                       List originalChanges = new ArrayList<>(changeList);
> ```

I think this throws NPE if changeList is null

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBrMw9i2Fcyubc5cX:-N5BBrMw9i2Fcyubc5cY:b-bztaoj) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1107)):*
> ```Java
>                                                 String filePath = ((GitFileChange) fileChange).getFilePath();
>                                                 try {
>                                                   yamlAuthHandler.authorizeDelete(filePath, accountId);
> ```

Why are we authorizing delete ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1116 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BC90R-afEykrG6mRA:-N5BC90R-afEykrG6mRB:b-e6slfs) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1116)):*
> ```Java
>                                               .collect(toList());
> 
>                       ListUtils.removeAll(changeList, unauthorizedFiles);
> ```

Rather than mutating the list changeList,, can we create a separate list.

In the next line if someone assumes that changeList contains all the changes then his assumption won't hold true

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BAltv1-ofrvnbXblX:-N5GI4LH8R9NjYU1vqjD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java#L64)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Whether we can throw and catch only some specific exception.

This way we might end up setting appId=Global app id for all the cases
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBJU8ArRgngJz85di:-N5GI5Ro6ZAHU7I_WR3Q:bydtdvh) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java#L119)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

What type is handled here ?
</blockquote></details>

if service folder is there in list i am checking for service perms and same for env
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1101 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBfmY-JwBS17J8nYm:-N5GIYfwCM0cC6SmylXW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1101)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

I think this throws NPE if changeList is null
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBrMw9i2Fcyubc5cX:-N5GIZ8-DuG66U9DN5QH:bn6jskc) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1107)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Why are we authorizing delete ?
</blockquote></details>

delete should also be authrozied in similar manner, right?
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1116 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BC90R-afEykrG6mRA:-N5GImjnA3Lt8zM9khKS:b-v0bxvl) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1116)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Rather than mutating the list changeList,, can we create a separate list.

In the next line if someone assumes that changeList contains all the changes then his assumption won't hold true
</blockquote></details>

thats why i created originalchangelist

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 6 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: Some of the checks are too old. 34 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBJU8ArRgngJz85di:-N5YsFqiCT-Id8Qp1uGn:b-sak0d7) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/resources/yaml/YamlAuthHandler.java#L119)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

if service folder is there in list i am checking for service perms and same for env
</blockquote></details>

But service is already checked above in case SERVICE:

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579)* status: Some of the checks are too old. 34 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/34579#-N5BBrMw9i2Fcyubc5cX:-N5YsTaTDa2pe9HLoGin:bnxzx41) ([raw file](https://github.com/harness/harness-core/blob/611cbf36860a59e77da85c67eb2e01400fb37355/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1107)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

delete should also be authrozied in similar manner, right?
</blockquote></details>

But this is upser call and we are calling authorizeDelete, should we call authorizeUpsert

**Review by DeepakPatankar — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34579#-:-N5Ysct_1YqjeHAZxIRj:bnfp4nl)* status: Some of the checks are too old. 34 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
