### PR TITLE
feat: [IDP-82]: Added events framework support for User ingestion in IDP

### PR DESCRIPTION
**Pull request by SarvJ1**
## Describe your changes
Added events framework support for User ingestion in IDP
Currently for any events corresponding to User and User groups are hitting one endpoint,
Which will re-trigger the Harness processor in Backstage.
Current setup is a batch processing setup where we check if the account where IDP enabled has an event and setup a cron job which runs every 10 mins which will then hit the endpoint for accounts which have an event.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)

### CODE REVIEW

**Comment by SarvJ1** [comment]
trigger messagecheck

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 20 of 21 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 21 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/user/BUILD.bazel` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRc1djF0Uph9CoqRf1L:-NRc1djF0Uph9CoqRf1M:bwutl6p) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/src/main/java/io/harness/idp/user/BUILD.bazel#L8)):*
> ```Starlark
> load("//:tools/bazel/harness.bzl", "java_library")
> load("//:tools/bazel/GenTestRules.bzl", "run_tests")
> load("//:tools/bazel/macros.bzl", "run_analysis")
> ```

nit: We don't need these



_Code quote:_
```Starlark
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis")
```
___
*[`idp-service/src/main/java/io/harness/idp/user/beans/entity/UserEventEntity.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRc2-0QBUZjFeMTQirN:-NRc2-0QBUZjFeMTQirO:b-f0yl2m) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/src/main/java/io/harness/idp/user/beans/entity/UserEventEntity.java#L27)):*
> ```Java
> @Data
> @Builder
> @FieldNameConstants(innerTypeName = "UserEventValue")
> ```

`UserEventsKeys`?



_Code quote:_
```Java
UserEventValue
```
___
*[`idp-service/src/main/java/io/harness/idp/user/repositories/UserEventRepositoryCustom.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRc2h-GCdkF583KgMe_:-NRc2h-GCdkF583KgMea:b-ealss9) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/src/main/java/io/harness/idp/user/repositories/UserEventRepositoryCustom.java#L12)):*
> ```Java
> import io.harness.idp.user.beans.entity.UserEventEntity;
> 
> public interface UserEventRepositoryCustom {
> ```

nit: @OwnedBy(HarnessTeam.IDP)
___
*[`idp-service/src/main/java/io/harness/idp/user/repositories/UserEventRepositoryCustomImpl.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRc2idzCEc6OyoOg1Vz:-NRc2idzCEc6OyoOg1W-:b-ealss9) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/src/main/java/io/harness/idp/user/repositories/UserEventRepositoryCustomImpl.java#L21)):*
> ```Java
> import org.springframework.data.mongodb.core.query.Update;
> 
> @AllArgsConstructor(access = AccessLevel.PRIVATE, onConstructor = @__({ @Inject }))
> ```

nit: @OwnedBy(HarnessTeam.IDP)
___
*[`idp-service/src/main/java/io/harness/idp/user/service/UserRefreshServiceImpl.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/45736#-NRbUwi6119SXisfe5OR:-NRc3Dvz5wpwEaaqx443:b32v57) ([raw file](https://github.com/harness/harness-core/blob/f8198615adfd4a8ee7b4891499ac182955eea661/idp-service/src/main/java/io/harness/idp/user/service/UserRefreshServiceImpl.java#L27)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Instead of filtering once we get the rows from DB, let's filter at the DB level only to return one row as we have unique identifier on accountIdentifier in this backstageNamespace collection
</blockquote></details>

+1

**Comment by SarvJ1** [comment]
trigger ut7

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 21 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/modules/clients/src/main/java/io/harness/clients/BackstageResourceClient.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRdOtyS-8yt48j_h40Q:-NRdOtyS-8yt48j_h40R:bgfkx8m) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/modules/clients/src/main/java/io/harness/clients/BackstageResourceClient.java#L28)):*
> ```Java
>   String CATALOG_API = "{accountIdentifier}/idp/api/catalog";
>   String LAYOUT_API = "{accountIdentifier}/idp/api/layout";
>   String HARNESS_REFRESH_API = "{accountIdentifier}/idp/api/harness/provider";
> ```

Un-related to your code changes. We can actually introduce a base_path containing "{accountIdentifier}/idp/api/" and then derive the other paths by prefixing it.
Ex.
String BASE_PATH = "{accountIdentifier}/idp/api/";
String CATALOG_API = BASE_PATH + "catalog"

**Comment by SarvJ1** [comment]
trigger ut7

**Comment by SarvJ1** [comment]
trigger ut3

**Review by SarvJ1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 27 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/user/beans/entity/UserEventEntity.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/45736#-NRbUn9bBUQYUQmi33SE:-NRkyhspEmPWtFd7Yz9U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8198615adfd4a8ee7b4891499ac182955eea661/idp-service/src/main/java/io/harness/idp/user/beans/entity/UserEventEntity.java#L36)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

It is better to have createdAt and updatedAt fields for audit purpose
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/user/beans/entity/UserEventEntity.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRc2-0QBUZjFeMTQirN:-NRkygQi2iD6lq0LcQGA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/src/main/java/io/harness/idp/user/beans/entity/UserEventEntity.java#L27)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

`UserEventsKeys`?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/user/jobs/UserSyncJob.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/45736#-NRbVPUtDUtxP5ocMWZw:-NRkyih93nd08gnT7e94:b-d0k9xo) ([raw file](https://github.com/harness/harness-core/blob/f8198615adfd4a8ee7b4891499ac182955eea661/idp-service/src/main/java/io/harness/idp/user/jobs/UserSyncJob.java#L68)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

What is the response that we get from backstage ? Just empty response with 200 Ok in case of success scenario ?
</blockquote></details>

Its just status 200 currently,No need of response
___
*[`idp-service/src/main/java/io/harness/idp/user/service/UserRefreshServiceImpl.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/45736#-NRbUwi6119SXisfe5OR:-NRkytMrESmQacZ4x2dy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8198615adfd4a8ee7b4891499ac182955eea661/idp-service/src/main/java/io/harness/idp/user/service/UserRefreshServiceImpl.java#L27)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by SarvJ1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 27 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/modules/clients/src/main/java/io/harness/clients/BackstageResourceClient.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/45736#-NRdOtyS-8yt48j_h40Q:-NRkyxmaAC_cpSP1vT1L:b-qzyuse) ([raw file](https://github.com/harness/harness-core/blob/1c9306ce5c97608d7520f74732c652fd15895d1a/idp-service/modules/clients/src/main/java/io/harness/clients/BackstageResourceClient.java#L28)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Un-related to your code changes. We can actually introduce a base_path containing "{accountIdentifier}/idp/api/" and then derive the other paths by prefixing it.
Ex.
String BASE_PATH = "{accountIdentifier}/idp/api/";
String CATALOG_API = BASE_PATH + "catalog"
</blockquote></details>

Will add this after auth has been handled

**Review by devesh-harness — APPROVED** [review]
> Reviewed 15 of 21 files at r1, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 12 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 4. unresolved discussions. 

___
*[`idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceService.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/45736#-NRppCarAqEHdDVwGTxN:-NRppCarAqEHdDVwGTxO:begibkw) ([raw file](https://github.com/harness/harness-core/blob/d60af8301eb9dbd1015f62a2a610b1242adf5bec/idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceService.java#L20)):*
> ```Java
>   NamespaceEntity saveAccountIdNamespace(String accountIdentifier);
>   List<String> getAccountIds();
>   Boolean getAccountIdpStatus(String accountIdentifier);
> ```

nit: Would prefer some name like `isIdpEnabled()` or `isIdpEnabledForAccount()`



_Code quote:_
```Java
getAccountIdpStatus
```

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: 4. unresolved discussions.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 15 of 21 files at r1, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45736)* status: :shipit: complete! ✓

**Pull request merged**
