### PR TITLE
feat: [CDS-53347]: License API for listing all services

### PR DESCRIPTION
**Pull request by ivan-83**
Added API for listing all services needed for licenses and filtering active services.

Created the new endpoint because this API is only related to cd licenses not to other modules.
If I add this endpoint to the existing license API resource we need to force other module owners to implement it but they don't need this API.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)

### CODE REVIEW

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)* status: 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java` line 162 at r3](https://reviewable.io/reviews/harness/harness-core/43784#-NOAXVy29Mn_tZypw4jn:-NOAXVy29Mn_tZypw4jo:b-fna55v) ([raw file](https://github.com/harness/harness-core/blob/a736ab647ccd648b8243d146004139f16b37dfd6/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java#L162)):*
> ```Java
>   }
> 
>   public Criteria createCriteriaForListingAllServices(
> ```

maybe we can put a comment that it will list services across all projects/organizations etc

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)* status: :shipit: complete! ✓

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageResource.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/43784#-NOAXBa-AKhOrbtPRvTp:-NOC6lzE8hJeXTdhpD_N:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a736ab647ccd648b8243d146004139f16b37dfd6/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageResource.java#L83)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to expose this API to openAPI ?
If we don't want customers to use it. If its only supposed to be used by our UI, swagger should be good enough
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java` line 162 at r3](https://reviewable.io/reviews/harness/harness-core/43784#-NOAXVy29Mn_tZypw4jn:-NOC6npN4j7mduGyOcjP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a736ab647ccd648b8243d146004139f16b37dfd6/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java#L162)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe we can put a comment that it will list services across all projects/organizations etc 
</blockquote></details>

Done.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43784)* status: :shipit: complete! ✓

**Pull request merged**
