### PR TITLE
[feat]: [CDS-69697]: Improved Error message incase of Failed Update operations on git with OAUTH configured.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Here is the new message:
Screenshot 2023-06-23 at 4 09 59 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49577)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger ut0

**Comment by senjucanon2** [comment]
trigger uts

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/49577#-NYak_i83JzTTloKhqM7:-NYak_i83JzTTloKhqM8:b98khsg) ([raw file](https://github.com/harness/harness-core/blob/92c0ced3b92735fd63700d2f207b00bc7bf278b6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java#L55)):*
> ```Java
>             ErrorMessageFormatter.formatMessage(
>                 ScmErrorHints.INVALID_CREDENTIALS + ScmErrorHints.OAUTH_ACCESS_FAILURE, errorMetadata),
>             ErrorMessageFormatter.formatMessage(UPDATE_FILE_FAILED + ScmErrorExplanations.INVALID_CONNECTOR_CREDS
> ```

we should make it into 2 points, first point for checking creds and second point for ouath hint

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49577)* status: 9 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/49577#-NYak_i83JzTTloKhqM7:-NYbtWPX6N-gSaOyFMJP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/92c0ced3b92735fd63700d2f207b00bc7bf278b6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubUpdateFileScmApiErrorHandler.java#L55)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we should make it into 2 points, first point for checking creds and second point for ouath hint
</blockquote></details>

Done.

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 5 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49577)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49577)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
