### PR TITLE
feat:[GTM-789]: plg telemetry project fix project events

### PR DESCRIPTION
**Pull request by tiwaritejas**
Added the correct userId and groupId in the Platform instrumentation calls

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31605)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31605)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 192 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuInfVAL4s-w6D5fFN:-MyuInfVAL4s-w6D5fFO:b88jppc) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L192)):*
> ```Java
>           }
>         }
>         String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

userId is different from email. Rename variable.
Constant io.harness.security.SecurityContextBuilder#EMAIL should be used instead of "email".
If Principal is not UserPrincipal or ServiceAccountPrincipal, in JWTClaims hash map "email" key will not be present and will result in null value. Is this expected?
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 383 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuKzhQ1LTkjfSUjsgl:-MyuKzhQ1LTkjfSUjsgm:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L383)):*
> ```Java
>                   .delete(accountIdentifier, orgIdentifier, projectIdentifier, connectorIdentifier);
>           if (!isDefaultBranchConnector) {
>             String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

Same here
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 392 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL0Yk8xrtimdZS2Ew:-MyuL0Yk8xrtimdZS2Ex:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L392)):*
> ```Java
>             publishEvent(accountIdentifier, orgIdentifier, projectIdentifier, connectorIdentifier, connector.getType(),
>                 EventsFrameworkMetadataConstants.DELETE_ACTION);
>             String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

Same here
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java, line 128 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL1fHDFzNu5xo5qLv:-MyuL1fHDFzNu5xo5qLw:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L128)):*
> ```Java
>       setupOrganization(Scope.of(accountIdentifier, organizationDTO.getIdentifier(), null));
>       log.info(String.format("Organization with identifier %s was successfully created", organization.getIdentifier()));
>       String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

Same here
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java, line 358 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL26W7GKJ-ujBNMQ0:-MyuL26W7GKJ-ujBNMQ1:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L358)):*
> ```Java
>         log.info(String.format("Organization with identifier %s was successfully deleted", organizationIdentifier));
>         outboxService.save(new OrganizationDeleteEvent(accountIdentifier, OrganizationMapper.writeDto(organization)));
>         String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

Same here
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, line 167 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL4M00GN36Okv-Bv6:-MyuL4M00GN36Okv-Bv7:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L167)):*
> ```Java
>       log.info(String.format("Project with identifier %s and orgIdentifier %s was successfully created",
>           project.getIdentifier(), projectDTO.getOrgIdentifier()));
>       String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

Same here
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, line 556 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL4u25cH3iedNTD7B:-MyuL4u25cH3iedNTD7C:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L556)):*
> ```Java
>         outboxService.save(
>             new ProjectDeleteEvent(deletedProject.getAccountIdentifier(), ProjectMapper.writeDTO(deletedProject)));
>         String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> ```

Same here
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLC1b5e1deVwNM5su:-MyuLC1b5e1deVwNM5sv:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java#L99)):*
> ```Java
>     try {
>       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
>     } catch (Exception e) {
> ```

Why catching exception in UT?
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java, line 112 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLa7G89rfsKOMz83D:-MyuLa7G89rfsKOMz83E:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java#L112)):*
> ```Java
>     try {
>       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
>     } catch (Exception e) {
> ```

Why catching exception in UT?
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/OrganizationInstrumentationHelperTest.java, line 74 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLcAeE8DS8JJ6exuG:-MyuLcAf6aF3ndD9IoNd:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/OrganizationInstrumentationHelperTest.java#L74)):*
> ```Java
>     try {
>       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
>     } catch (Exception e) {
> ```

Why catching exception in UT?
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ProjectInstrumentationHelperTest.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLdB13R8bDopbzX_E:-MyuLdB13R8bDopbzX_F:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ProjectInstrumentationHelperTest.java#L81)):*
> ```Java
>     try {
>       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
>     } catch (Exception e) {
> ```

Why catching exception in UT?

**Comment by tiwaritejas** [comment]
trigger authorcheck
trigger checkstyle

**Comment by tiwaritejas** [comment]
trigger compile
trigger AeriformCheck
trigger codeformat
trigger messagecheck
trigger recency
trigger buildnum
trigger dockerizationcheck
trigger authorcheck
trigger checkstyle
trigger pmd
trigger ti0trigger ti1
trigger ti2
trigger ti3
trigger ti4
trigger ft1
trigger ft2
trigger codebasehash

**Comment by tiwaritejas** [comment]
trigger ti2

**Comment by tiwaritejas** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/31605)_ status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 192 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuInfVAL4s-w6D5fFN:-MyuInfVAL4s-w6D5fFO:b88jppc) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L192)):_
> 
> > ```java
> >           }
> >         }
> >         String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> userId is different from email. Rename variable. Constant io.harness.security.SecurityContextBuilder#EMAIL should be used instead of "email". If Principal is not UserPrincipal or ServiceAccountPrincipal, in JWTClaims hash map "email" key will not be present and will result in null value. Is this expected?
> 
> _[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 383 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuKzhQ1LTkjfSUjsgl:-MyuKzhQ1LTkjfSUjsgm:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L383)):_
> 
> > ```java
> >                   .delete(accountIdentifier, orgIdentifier, projectIdentifier, connectorIdentifier);
> >           if (!isDefaultBranchConnector) {
> >             String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> Same here
> 
> _[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 392 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL0Yk8xrtimdZS2Ew:-MyuL0Yk8xrtimdZS2Ex:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L392)):_
> 
> > ```java
> >             publishEvent(accountIdentifier, orgIdentifier, projectIdentifier, connectorIdentifier, connector.getType(),
> >                 EventsFrameworkMetadataConstants.DELETE_ACTION);
> >             String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> Same here
> 
> _[120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java, line 128 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL1fHDFzNu5xo5qLv:-MyuL1fHDFzNu5xo5qLw:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L128)):_
> 
> > ```java
> >       setupOrganization(Scope.of(accountIdentifier, organizationDTO.getIdentifier(), null));
> >       log.info(String.format("Organization with identifier %s was successfully created", organization.getIdentifier()));
> >       String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> Same here
> 
> _[120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java, line 358 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL26W7GKJ-ujBNMQ0:-MyuL26W7GKJ-ujBNMQ1:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L358)):_
> 
> > ```java
> >         log.info(String.format("Organization with identifier %s was successfully deleted", organizationIdentifier));
> >         outboxService.save(new OrganizationDeleteEvent(accountIdentifier, OrganizationMapper.writeDto(organization)));
> >         String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> Same here
> 
> _[120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, line 167 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL4M00GN36Okv-Bv6:-MyuL4M00GN36Okv-Bv7:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L167)):_
> 
> > ```java
> >       log.info(String.format("Project with identifier %s and orgIdentifier %s was successfully created",
> >           project.getIdentifier(), projectDTO.getOrgIdentifier()));
> >       String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> Same here
> 
> _[120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, line 556 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL4u25cH3iedNTD7B:-MyuL4u25cH3iedNTD7C:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L556)):_
> 
> > ```java
> >         outboxService.save(
> >             new ProjectDeleteEvent(deletedProject.getAccountIdentifier(), ProjectMapper.writeDTO(deletedProject)));
> >         String userId = SourcePrincipalContextBuilder.getSourcePrincipal().getJWTClaims().get("email");
> > ```
> 
> Same here
> 
> _[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLC1b5e1deVwNM5su:-MyuLC1b5e1deVwNM5sv:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java#L99)):_
> 
> > ```java
> >     try {
> >       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
> >     } catch (Exception e) {
> > ```
> 
> Why catching exception in UT?
> 
> _[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java, line 112 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLa7G89rfsKOMz83D:-MyuLa7G89rfsKOMz83E:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java#L112)):_
> 
> > ```java
> >     try {
> >       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
> >     } catch (Exception e) {
> > ```
> 
> Why catching exception in UT?
> 
> _[120-ng-manager/src/test/java/io/harness/telemetry/helpers/OrganizationInstrumentationHelperTest.java, line 74 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLcAeE8DS8JJ6exuG:-MyuLcAf6aF3ndD9IoNd:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/OrganizationInstrumentationHelperTest.java#L74)):_
> 
> > ```java
> >     try {
> >       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
> >     } catch (Exception e) {
> > ```
> 
> Why catching exception in UT?
> 
> _[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ProjectInstrumentationHelperTest.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLdB13R8bDopbzX_E:-MyuLdB13R8bDopbzX_F:b9p485u) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ProjectInstrumentationHelperTest.java#L81)):_
> 
> > ```java
> >     try {
> >       verify(telemetryReporter, times(1)).sendTrackEvent(any(), any(), any(), any(), any(), any(), any());
> >     } catch (Exception e) {
> > ```
> 
> Why catching exception in UT?

- Added a userId resolver function in InstrumentationHelper.java to get userId according to the Principal
- Removed the try catch from UT

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31605)* status: 12 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 192 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuInfVAL4s-w6D5fFN:-MzZNIQu1ZxvfCk_MTrd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L192)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

userId is different from email. Rename variable.
Constant io.harness.security.SecurityContextBuilder#EMAIL should be used instead of "email".
If Principal is not UserPrincipal or ServiceAccountPrincipal, in JWTClaims hash map "email" key will not be present and will result in null value. Is this expected?
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 383 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuKzhQ1LTkjfSUjsgl:-MzZNJL11jkBchfjZnU8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L383)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java, line 392 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL0Yk8xrtimdZS2Ew:-MzZNJlk92P3hPX9eS8R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L392)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java, line 128 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL1fHDFzNu5xo5qLv:-MzZNKawD7N7-JiVJ3YP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L128)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java, line 358 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL26W7GKJ-ujBNMQ0:-MzZNL-Z-AHC70O1MarE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L358)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, line 167 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL4M00GN36Okv-Bv6:-MzZNLNyBCMg2Fkooh4y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L167)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, line 556 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuL4u25cH3iedNTD7B:-MzZNLmZ5YHMOtTwt1E1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L556)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java, line 99 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLC1b5e1deVwNM5su:-MzZNMEE7GbC62VuEmUe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java#L99)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why catching exception in UT?
</blockquote></details>

Done.
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java, line 112 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLa7G89rfsKOMz83D:-MzZNMhxAs8FffkQzTsU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelperTest.java#L112)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why catching exception in UT?
</blockquote></details>

Done.
___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/OrganizationInstrumentationHelperTest.java, line 74 at r2](https://reviewable.io/reviews/harness/harness-core/31605#-MyuLcAeE8DS8JJ6exuG:-MzZNNhV4gYPKa6-M80S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/980b51170f138dba2e510fc4afe4ca6e6739cfc0/120-ng-manager/src/test/java/io/harness/telemetry/helpers/OrganizationInstrumentationHelperTest.java#L74)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why catching exception in UT?
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31605)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/test/java/io/harness/telemetry/helpers/InstrumentationHelperTest.java, line 24 at r8](https://reviewable.io/reviews/harness/harness-core/31605#-MzZThfxEMjHaTzWWynm:-MzZThfy5bsDG8mJmlxt:b8jpel0) ([raw file](https://github.com/harness/harness-core/blob/9b4a513c4c43c3e1bf86d1585984623810f09f57/120-ng-manager/src/test/java/io/harness/telemetry/helpers/InstrumentationHelperTest.java#L24)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testGetUserId() {
>     assertNotNull(instrumentationHelper.getUserId());
> ```

Just checking not null is of not much help. For each case there should be a test case.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 10 files at r5, 3 of 6 files at r6, 5 of 6 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31605)* status: :shipit: complete! ✓

**Pull request merged**
