### PR TITLE
fix: [CDS-78880]: Render json array type of variables without parser

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- If a variable is an array of json string with an expression then the expression engine would resolve an hashmap object type. The fix will not support this type of string without using json parse. 
- Before
before
- After 
after

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52621)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52621)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java` line 528 at r1](https://reviewable.io/reviews/harness/harness-core/52621#-NdnJgU6-83jT7NaLRu0:-NdnJgU6-83jT7NaLRu1:bqz8nxh) ([raw file](https://github.com/harness/harness-core/blob/4655bbe210640b443b16a8f2d7fb558690694fdc/980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java#L528)):*
> ```Java
>     assertThat(evaluator.resolve("<+var7>", true)).isEqualTo("[{\"stu\":\"abc\"},{\"u\":{\"vw\":\"xyz\"}}]");
>     assertThat(evaluator.resolve("<+var8>", true))
>         .isEqualTo("[{\"lmn\":\"pqr\"},{\"stu\":\"abc\"},{\"u\":{\"vw\":\"def\"}}]");
> ```

Can you add this test in below method as well?

it has script FF enabled thus we wanted to see it should work same

testValidNestedExpressionsForResolveAndEvaluateWithConcatenateWithScriptFlag

**Comment by rohitk-h** [comment]
*[`980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java` line 528 at r1](https://reviewable.io/reviews/harness/harness-core/52621#-NdnJgU6-83jT7NaLRu0:-NdnL7vw8ohVfnSBqevB:b-83qg0m) ([raw file](https://github.com/harness/harness-core/blob/4655bbe210640b443b16a8f2d7fb558690694fdc/980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java#L528)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you add this test in below method as well?

it has script FF enabled thus we wanted to see it should work same

testValidNestedExpressionsForResolveAndEvaluateWithConcatenateWithScriptFlag
</blockquote></details>

Update test.

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger smartchecks

**Comment by rohitk-h** [comment]
trigger messagecheck

**Review by shalini-agr — APPROVED** [review]

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by rohitk-h** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]

**Pull request merged**
