### PR TITLE
feat: [IDP-256]: Plugins list and detailed info API

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)

### CODE REVIEW

**Review by sathish-soundarapandian — COMMENTED** [review]
> Reviewed 11 of 24 files at r1, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 24 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 484 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfIAAzE_FdFffkAA84:-NQfIAAzE_FdFffkAA85:b-kim2a2) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L484)):*
> ```YAML
>         - AppConfig
>     parameters: []
>   /v1/plugins-info:
> ```

How about just /v1/plugins ? We can rename all instances of plugins-info to just plugins.

GET /v1/plugins
GET /v1/plugins/{identifier}

Tag - PluginResource
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 486 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfIjjKBlYS9HH9yKGu:-NQfIjjKBlYS9HH9yKGv:bromxdj) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L486)):*
> ```YAML
>   /v1/plugins-info:
>     get:
>       summary: Your GET endpoint
> ```

Let's add correct data here. Even whatever is there in the description, it can be same here.
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 498 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfJIbk9UfjnfJuoo1X:-NQfJIbk9UfjnfJuoo1Y:b-mn1wb1) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L498)):*
> ```YAML
>       parameters:
>         - $ref: '#/components/parameters/AccountHeader'
>   '/v1/plugins-info/{pluginId}':
> ```

We need only GET api ? For insert, update, delete - how are we planning ?
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 874 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfJaUsCY4FHVmXcjj0:-NQfJaUsCY4FHVmXcjj1:bdttr7n) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L874)):*
> ```YAML
>           x-stoplight:
>             id: 6opetnwiiai53
>     PluginInfoResponse:
> ```

Let's check once if there are any adhoc metadata associated with each plugin which we might need to store in DB and expose through API
___
*[`idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfK1Cu8J1lQKzGNKMg:-NQfK1Cu8J1lQKzGNKMh:bs6zo21) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java#L35)):*
> ```Java
> @Entity(value = "accountPlugin", noClassnameStored = true)
> @FieldNameConstants(innerTypeName = "AccountPluginEntityKeys")
> @Document("accountPlugin")
> ```

Just plugin will be good ?
___
*[`idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfK67G4ESiiN38M5KY:-NQfK67G4ESiiN38M5KZ:b-uu5cht) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java#L44)):*
> ```Java
>   private String accountIdentifier;
>   private boolean enabled;
>   private String config;
> ```

As mentioned in the earlier comments, let's see if there are some adhoc data associated with each plugin and store it in the DB
___
*[`idp-service/src/main/java/io/harness/idp/plugin/beans/PluginInfoEntity.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfMG9461W_m0igsUoU:-NQfMG9461W_m0igsUoV:b-912thv) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/beans/PluginInfoEntity.java#L32)):*
> ```Java
> @Persistent
> @OwnedBy(HarnessTeam.IDP)
> public class PluginInfoEntity implements PersistentEntity {
> ```

Bit concerned on the DB data model. Can you share the DB schema design explaining the relation and use-case of these two entities ?
___
*[`idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfKhlF2uoS-Cuaxe6W:-NQfKhlF2uoS-Cuaxe6X:b-awqbll) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java#L29)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> @Slf4j
> public class PluginInfoApiImpl implements PluginInfoApi {
> ```

These are called from Ui right ? We need nextGenManagerAuth and AccessControlCheck for the APIs
___
*[`idp-service/src/main/java/io/harness/idp/plugin/utils/FileUtils.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfLRTj6auao58Pyy5e:-NQfLRTj6auao58Pyy5f:b59fkkr) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/utils/FileUtils.java#L23)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> @UtilityClass
> public class FileUtils {
> ```

Let's move these to common package. Even onboarding package has FileUtils. Ideally that also needs to refactored to use the commons package.
Let's merge both and refactor.
___
*[`idp-service/src/main/resources/configs/harness-ci-cd.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfLzI35XB-Cl0NqxCi:-NQfLzI35XB-Cl0NqxCj:b-oxgbi6) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/resources/configs/harness-ci-cd.yaml#L1)):*
> ```YAML
> proxy:
> ```

How these are used in the application runtime ?

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 27 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 484 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfIAAzE_FdFffkAA84:-NQgp9PdBjjPwIM-n-Ad:b744oni) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L484)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

How about just /v1/plugins ? We can rename all instances of plugins-info to just plugins.

GET /v1/plugins
GET /v1/plugins/{identifier}

Tag - PluginResource
</blockquote></details>

/v1/plugins is already taken  - PluginMetadataResource. Hence used /v1/plugins-info
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 486 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfIjjKBlYS9HH9yKGu:-NQgzuoS1Nk0gze1UgAg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L486)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Let's add correct data here. Even whatever is there in the description, it can be same here.
</blockquote></details>

Done.
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 498 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfJIbk9UfjnfJuoo1X:-NQgy4CtDvFbwJwFoCfE:bo95c7k) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L498)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

We need only GET api ? For insert, update, delete - how are we planning ?
</blockquote></details>

Plugin enable/disable, update are already taken by Devesh in this PR 
https://github.com/harness/harness-core/pull/45179/files#diff-80959136db61faf5358a3034f9e6e42ca5cfd301cc6c292874a2229bb94e49eaR464 
___
*[`idp-service/src/main/java/io/harness/idp/plugin/beans/PluginInfoEntity.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfMG9461W_m0igsUoU:-NQgpaz-EvweZeu7ich3:b-rxmh6d) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/beans/PluginInfoEntity.java#L32)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Bit concerned on the DB data model. Can you share the DB schema design explaining the relation and use-case of these two entities ?
</blockquote></details>

https://harness.atlassian.net/wiki/spaces/IDP/pages/21347566604/Plugin+DB+Schema 
___
*[`idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfK1Cu8J1lQKzGNKMg:-NQh0y0L6truhYxIucN5:b-2kgfsk) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java#L35)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Just plugin will be good ?
</blockquote></details>

removed this entity and used AppConfigEntity

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 27 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfKhlF2uoS-Cuaxe6W:-NQhhKle3wYfSBLjZl7g:b-69uz97) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java#L29)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

These are called from Ui right ? We need nextGenManagerAuth and AccessControlCheck for the APIs
</blockquote></details>

this will be done from the settings-ui so only admins will have access

**Review by sathish-soundarapandian — COMMENTED** [review]
> Reviewed 1 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 27 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfKhlF2uoS-Cuaxe6W:-NQiACuKBhE7RNBJX2b7:bqccj1w) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java#L29)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

this will be done from the settings-ui so only admins will have access
</blockquote></details>

Ideally all backend APIs exposed to FE needs to be protected. Else we are leaving APIs to be allowed without authentication

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 28 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 874 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfJaUsCY4FHVmXcjj0:-NQiOMaPBPM90I0LG3rU:b-z752i5) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L874)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Let's check once if there are any adhoc metadata associated with each plugin which we might need to store in DB and expose through API
</blockquote></details>

few things are yet to be decided, have included known things for now
___
*[`idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfKhlF2uoS-Cuaxe6W:-NQiObqb5eBG1AIbD1_W:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/resources/PluginInfoApiImpl.java#L29)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Ideally all backend APIs exposed to FE needs to be protected. Else we are leaving APIs to be allowed without authentication
</blockquote></details>

done
___
*[`idp-service/src/main/resources/configs/harness-ci-cd.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfLzI35XB-Cl0NqxCi:-NQiOe3J80ZTkBlLw-W5:b8140px) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/resources/configs/harness-ci-cd.yaml#L1)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

How these are used in the application runtime ?
</blockquote></details>

these are some static configs available for all the accounts
___
*[`idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfK67G4ESiiN38M5KY:-NQiOsjl4zmn2UPJL3Cg:b-2kgfsk) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/beans/AccountPluginEntity.java#L44)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

As mentioned in the earlier comments, let's see if there are some adhoc data associated with each plugin and store it in the DB
</blockquote></details>

removed this entity and used AppConfigEntity
___
*[`idp-service/src/main/java/io/harness/idp/plugin/utils/FileUtils.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfLRTj6auao58Pyy5e:-NQiOY4R8QtGQ02jNGnN:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/utils/FileUtils.java#L23)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Let's move these to common package. Even onboarding package has FileUtils. Ideally that also needs to refactored to use the commons package.
Let's merge both and refactor.
</blockquote></details>

done

**Review by sathish-soundarapandian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 28 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/resources/configs/harness-ci-cd.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQfLzI35XB-Cl0NqxCi:-NQiQZE719vdYLILKL2l:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/resources/configs/harness-ci-cd.yaml#L1)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

these are some static configs available for all the accounts
</blockquote></details>

Ok

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 9 of 24 files at r1, 5 of 6 files at r3, 10 of 14 files at r4, 7 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 20 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 502 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQenCUt9nLvvsGsJhNd:-NQenCUt9nLvvsGsJhNe:bujakmm) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L502)):*
> ```YAML
>       - schema:
>           type: string
>         name: pluginId
> ```

can we define this under parameters and $ref it here?



_Code quote:_
```YAML
pluginId
```
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 512 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQenQfU0w21cvp8RLcj:-NQenQfU0w21cvp8RLck:b-ulixtg) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L512)):*
> ```YAML
>         '200':
>           $ref: '#/components/responses/PluginDetailedInfoResponse'
>       operationId: get-plugins-info-pluginId
> ```

`get-plugins-info-plugin-id` is recommended. 



_Code quote:_
```YAML
pluginId
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 35 at r6](https://reviewable.io/reviews/harness/harness-core/45213#-NQiSXWlAjOwF-K0z4Bu:-NQiSXWm7cI8BAZ6tnpi:b-wxxovh) ([raw file](https://github.com/harness/harness-core/blob/64d173fa03cd64fea257d1105830add21896ea8c/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L35)):*
> ```Java
> 
>   @Override
>   public Map<String, Boolean> getAllPluginIdsMap(String accountIdentifier) {
> ```

Found similar code in Devesh's PR. Looks like duplicate effort.
___
*[`idp-service/src/main/java/io/harness/idp/plugin/BUILD.bazel` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQeoLnq2ggq4I9mZcOY:-NQeoLnq2ggq4I9mZcOZ:b-qsqr3v) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/src/main/java/io/harness/idp/plugin/BUILD.bazel#L8)):*
> ```Starlark
> load("//:tools/bazel/harness.bzl", "java_library")
> load("//:tools/bazel/GenTestRules.bzl", "run_tests")
> load("//:tools/bazel/macros.bzl", "run_analysis")
> ```

nit: These might not be needed



_Code quote:_
```Starlark
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis")
```
___
*[`idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java` line 21 at r6](https://reviewable.io/reviews/harness/harness-core/45213#-NQiVbPE047FLGEN7z3L:-NQiVbPE047FLGEN7z3M:bacwgba) ([raw file](https://github.com/harness/harness-core/blob/64d173fa03cd64fea257d1105830add21896ea8c/idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java#L21)):*
> ```Java
> @UtilityClass
> public class PluginDetailedInfoMapper {
>   public PluginDetailedInfo toDTO(PluginInfoEntity pluginInfoEntity, AppConfig appConfig, String staticConfig) {
> ```

As discussed offline, can we use PluginInfo inside PluginDetailedInfo and add the additional fields on top of it?

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 20 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 502 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQenCUt9nLvvsGsJhNd:-NQj80Wx6hFG4Hj5PIyP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L502)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

can we define this under parameters and $ref it here?
</blockquote></details>

Done.
___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 512 at r3](https://reviewable.io/reviews/harness/harness-core/45213#-NQenQfU0w21cvp8RLcj:-NQj80w74anx5Ssmvy_E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb9ed6c20b064b3b7482057029c821ace132b72e/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L512)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

`get-plugins-info-plugin-id` is recommended. 
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 35 at r6](https://reviewable.io/reviews/harness/harness-core/45213#-NQiSXWlAjOwF-K0z4Bu:-NQj8D0Z4Dsde4DZ9hHj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/64d173fa03cd64fea257d1105830add21896ea8c/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L35)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Found similar code in Devesh's PR. Looks like duplicate effort.
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java` line 21 at r6](https://reviewable.io/reviews/harness/harness-core/45213#-NQiVbPE047FLGEN7z3L:-NQj84lZ6nkscJZ4wXrm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/64d173fa03cd64fea257d1105830add21896ea8c/idp-service/src/main/java/io/harness/idp/plugin/mappers/PluginDetailedInfoMapper.java#L21)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

As discussed offline, can we use PluginInfo inside PluginDetailedInfo and add the additional fields on top of it?
</blockquote></details>

done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 3 of 24 files at r1, 6 of 14 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45213)* status: :shipit: complete! ✓

**Pull request merged**
