### PR TITLE
feat: [CDS-86172]: Adding Module Name on the basis on steps in the pipeline

### PR DESCRIPTION
**Pull request by ayushitiwari024**
## Describe your changes

**Issue:** Customer with a CI stage with a STO step couldn't view the pipeline in the STO execution page. The criteria that was followed was on the stage basis i.e that pipelines will be shown on the execution pages of the modules who are part of that pipeline as a stage.

**Implementation:**

 1. In **ExecutionHelper**, we **fetch all the planNodes from the plan** which is later passed on the nodeLookupService(modulesThatSupportStepTypes **function** which **accepts** planNodeList and **returns** the **set of string** that support these steps in the planNodes). 

2. We then add a data member **stepModules** to the plan and then **set this data membe**r with the value returned by the above mentioned function.

3. We **append** the above **stepModules** from plan to the modules variable in ExecutionSummaryCreateEventHandler which stores all the modules depending on the stage basis(**older logic**).

**Testing:**

CI stage with STO steps:  both in CI and STO---->>> ci, sto, iacm(my func) ---->>>> ci, sto, iacm, pms

Custom stage with a  run inside a step group------>>>> iacm, sto, ci(my func) --------->> iacm, ci, sto , pms

Custom stage with a  plugin inside a step group------->>>>  iacm, ci(my func) ------->>> iacm, ci, pms

Custom stage with a  AwsCdkRollback inside a step group ----->>>> cd(my func) ------->>>> pms, cd

Custom stage with a  git clone inside a step group------->>>>  iacm, ci(my func) ----->>>>. iacm, ci, pms

Custom stage with CD steps ----->>> cd(my func) ---->>> cd, pms

CD stage with CD steps only ---->>>> cd(my func) ---->> cd, pms

CD stage with some common step(like shell script)------>>> empty list(my func) ------>  cd

Custome stage with common step(i.e shell script)----->> empty list(my func)--->>> pms

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56230)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
Changes looks good. Please add UTS

**Review by archit-harness — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56230)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/56230#-NkxVBFv9_eNZNcRE9kG:-NkxVBFv9_eNZNcRE9kH:b9qrsx4) ([raw file](https://github.com/harness/harness-core/blob/ec3fa91339d358812f55fd8a55cd8e16ed046daa/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java#L73)):*
> ```Java
>     }
> 
>     Map<String, Set<String>> mapispartOfPalleteTrue = new LinkedHashMap<>();
> ```

can we rename this variable better?

**Review by ayushitiwari024 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56230)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/56230#-NkxVBFv9_eNZNcRE9kG:-NkxfviV40dLlfyir0ll:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ec3fa91339d358812f55fd8a55cd8e16ed046daa/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename this variable better?
</blockquote></details>

Done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/56230#-NkxrjgaAKQ4WQ9vigS7:-NkxrjgaAKQ4WQ9vigS8:b-d388mm) ([raw file](https://github.com/harness/harness-core/blob/269fbd52b9400423504870ddd27f83e488d5d3cb/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java#L68)):*
> ```Java
>   public Set<String> modulesThatSupportStepTypes(List<Node> planNodeList) {
>     // We get the supportedSdkSteps corresponding to all the modules
>     Map<String, Set<SdkStep>> map = pmsSdkInstanceService.getSdkSteps();
> ```

Can we rename this variable too?

**Review by ayushitiwari024 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56230)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/56230#-NkxrjgaAKQ4WQ9vigS7:-Nkxy4zO06GP222qoCDq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/269fbd52b9400423504870ddd27f83e488d5d3cb/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/NodeTypeLookupServiceImpl.java#L68)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we rename this variable too?
</blockquote></details>

Done

**Comment by ayushitiwari024** [comment]
trigger smartchecks

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger smartchecks

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger ut7

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56230)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 6 of 8 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56230)* status: 1. unresolved discussions.

**Comment by ayushitiwari024** [comment]
trigger review

**Pull request merged**
