### PR TITLE
[feat]: [IDP-226]: Error Scenarios for git integrations

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46758)

### CODE REVIEW

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/46758#gh-1175299266:-NTrlpGd25gEGuFN3UZ8:b3zwvet) ([raw file](https://github.com/harness/harness-core/blob/345404f6a684f03ad39c039901710709ef7de5b7/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java#L58)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Question - Any specific reason on why we don't want to allow this mode ? i.e GitHub ApiAccess with token based.
SSH - it makes sense to not allow that as the integrations cannot be set in backstage.
</blockquote></details>

Backstage only supports Github App based API access
 cc @devesh-harness

**Comment by sathish-soundarapandian** [comment]
> _[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/46758#gh-1175299266:-NTrlpGd25gEGuFN3UZ8:b3zwvet) ([raw file](https://github.com/harness/harness-core/blob/345404f6a684f03ad39c039901710709ef7de5b7/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java#L58)):_
> 
> Previously, sathish-soundarapandian (Sathish) wrote…
> Backstage only supports Github App based API access cc @devesh-harness

Our GitHub Connector API access with token will be just set as token in backstage and ideally it should work.
Let's validate it once - Create a valid github connector with api access using token in some environment and try onboarding flow.

**Comment by sathish-soundarapandian** [comment]
> > _[`idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/46758#gh-1175299266:-NTrlpGd25gEGuFN3UZ8:b3zwvet) ([raw file](https://github.com/harness/harness-core/blob/345404f6a684f03ad39c039901710709ef7de5b7/idp-service/src/main/java/io/harness/idp/gitintegration/processor/impl/GithubConnectorProcessor.java#L58)):_
> > Previously, sathish-soundarapandian (Sathish) wrote…
> > Backstage only supports Github App based API access cc @devesh-harness
> 
> Our GitHub Connector API access with token will be just set as token in backstage and ideally it should work. Let's validate it once - Create a valid github connector with api access using token in some environment and try onboarding flow.

Just had a discussion with @devesh-harness and it should be fine. Let's not add explicit error check for apiAccess with token based. SSH - we are good to throw error.

**Review by sathish-soundarapandian — APPROVED** [review]

**Review by vikyathharekal — APPROVED** [review]

**Comment by sarthakkasat** [comment]
trigger review

**Pull request merged**
