### PR TITLE
fix: [CDS-45156]: Fix exception when deployToAll env is selected

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
With introduction of environment group, users can select to deploy to all environments at once. When this option is selected the pipeline doesn't resolve all environments and thus fails deploy. The PR is to fix this use case. 

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39077)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by meenaravichandran1 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39077)* status: :shipit: complete! ✓

**Review by henry-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39077)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/39077#-NErcscWCr5iO2kFvBmQ:-NErcscWCr5iO2kFvBmR:bue0qc7) ([raw file](https://github.com/harness/harness-core/blob/2bdbe44e092297727ac59ecd6033e2ced1e7bf58/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java#L96)):*
> ```Java
>         }
>         EnvironmentYamlV2 envV2Yaml = envV2Yamls.stream()
>                                           .filter(e -> e.getEnvironmentRef().getValue().equals(env.getIdentifier()))
> ```

nitpick: is it possible that env ref is null? and so `getValue()` throws an NPE?

**Review by anshul-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39077)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/39077#-NErcscWCr5iO2kFvBmQ:-NEripEz6Zp0sr1p80Fw:bo068q7) ([raw file](https://github.com/harness/harness-core/blob/2bdbe44e092297727ac59ecd6033e2ced1e7bf58/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java#L96)):*
<details><summary><i>Previously, henry-harness (henry leong) wrote…</i></summary><blockquote>

nitpick: is it possible that env ref is null? and so `getValue()` throws an NPE?
</blockquote></details>

envRef is envIdentifiers they cannot be null.

**Review by henry-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39077)* status: :shipit: complete! ✓

**Pull request merged**
