### PR TITLE
[fix]: [CDS-53895]: not allowing saving serviceRef as empty string ( service v2 )

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45008)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/test/java/io/harness/validator/NGRegexValidatorConstantsTest.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/45008#-NQFVJSd5itpdV6-9v1c:-NQFVJSd5itpdV6-9v1d:b-bkuvuo) ([raw file](https://github.com/harness/harness-core/blob/46f6f2548bf99a1400e9e39f4596020f0b5982c6/970-ng-commons/src/test/java/io/harness/validator/NGRegexValidatorConstantsTest.java#L86)):*
> ```Java
>     assertTrue(nonEmptyStringPattern.matcher(" ABC").matches());
>     assertTrue(nonEmptyStringPattern.matcher("ABC ").matches());
>     assertTrue(nonEmptyStringPattern.matcher("ABC ").matches());
> ```

are these 2 tests same ?
Can we also add test for account.serviceref etc, also underscores etc



_Code quote (from 970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java):_
```Java
^(?=\\s*\\S).*$
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45008)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`970-ng-commons/src/test/java/io/harness/validator/NGRegexValidatorConstantsTest.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/45008#-NQFVJSd5itpdV6-9v1c:-NQG7mSK4KkpWaku44v4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/46f6f2548bf99a1400e9e39f4596020f0b5982c6/970-ng-commons/src/test/java/io/harness/validator/NGRegexValidatorConstantsTest.java#L86)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are these 2 tests same ?
Can we also add test for account.serviceref etc, also underscores etc
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java` line 276 at r2](https://reviewable.io/reviews/harness/harness-core/45008#-NQFVi9fEKv4HdGxp_9g:-NQG7nXgAxqemZgdYu2U:bmi9dnz) ([raw file](https://github.com/harness/harness-core/blob/46f6f2548bf99a1400e9e39f4596020f0b5982c6/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java#L276)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should not block variable creation as such
I think you meant to do this in DeploymentStageFilterJsonCreatorV2 ?
</blockquote></details>

Sorry forgot in hurry. Thanks.
i already made that change in last pr
io.harness.cdng.creator.filters.DeploymentStageFilterJsonCreatorV2#addFiltersFromServiceV2

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45008)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45008)* status: :shipit: complete! ✓

**Pull request merged**
