### PR TITLE
feat: [CCM-7328]: Updated the k8s connector yaml for k8s AutoSopping

### PR DESCRIPTION
**Pull request by riyasyash**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33235)

### CODE REVIEW

**Comment by riyasyash** [comment]
trigger messagecheck

**Comment by riyasyash** [comment]
trigger messagecheck

**Review by shalinlk — DISMISSED** [review]

**Review by navaneeth — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33235)* status: Some of the checks are too old.

**Review by navaneeth — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33235)* status: :shipit: complete! ✓

**Review by shalinlk — DISMISSED** [review]

**Review by navaneeth — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33235)* status: Some of the checks are too old.

**Review by shalinlk — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33235)* status: Some of the checks are too old.

**Pull request merged**
