### PR TITLE
fix: [CDS-53891]: Avoiding unnecessary Git Fetch Task for Kustomize and Openshift

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
For the following config (Kusotmize/ Openshift manifest without pathches/ params files), we were unnecessary calling a Git Fetch task to fetch the patches/params file even though it was not required. In this PR I have optimised the execution flow and will call K8s Task directly if no override files are applied.

### Kustomize
Screenshot 2023-03-03 at 10 07 04 AM

### Openshift
Screenshot 2023-03-03 at 10 09 57 AM
Screenshot 2023-03-03 at 12 22 28 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44652)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44652)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 472 at r2](https://reviewable.io/reviews/harness/harness-core/44652#-NPau_IGBb1aI8fuiSFw:-NPau_IGBb1aI8fuiSFx:b-42pdn2) ([raw file](https://github.com/harness/harness-core/blob/52ae6572ef2d1cdd6e46baa8f09e157934e294f5/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L472)):*
> ```Java
> 
>     if ((ManifestStoreType.isInGitSubset(storeConfig.getKind())
>             && isNotEmpty(getParameterFieldValue(openshiftManifestOutcome.getParamsPaths())))
> ```

nit: maybe this check should be put in separate method as is used later with the same logic



_Code quote:_
```Java
// in case of OpenShift Template
```

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44652)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 472 at r2](https://reviewable.io/reviews/harness/harness-core/44652#-NPau_IGBb1aI8fuiSFw:-NPazJWG5OThtLSEwTLa:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/52ae6572ef2d1cdd6e46baa8f09e157934e294f5/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L472)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: maybe this check should be put in separate method as is used later with the same logic
</blockquote></details>

Done

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44652)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44652)* status: :shipit: complete! ✓

**Pull request merged**
