### PR TITLE
feat: [SRM-15244]: Modify SRMAnalysisStepExecutionDetail collection t…

### PR DESCRIPTION
**Pull request by karansaraswat19**
…o have necessary details which we currently have in Activity

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51326)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51326)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/SRMAnalysisStepExecutionDetail.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NayS9MxD_X1YZQqCEb4:-NayS9MxD_X1YZQqCEb5:b-xtatej) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/SRMAnalysisStepExecutionDetail.java#L82)):*
> ```Java
>   @FdIndex Long reportNotificationIteration;
> 
>   String pipelineName;
> ```

we need pipelineName as well for report



_Code quote:_
```Java
 String pipelineName;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/SRMAnalysisStepExecutionDetail.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NayTJBXDoxCXDUWB3yy:-NayTJBXDoxCXDUWB3yz:btyih0h) ([raw file](https://github.com/harness/harness-core/blob/30f444d4194f74facce3312f9e028a4a4ea8c9ed/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/SRMAnalysisStepExecutionDetail.java#L87)):*
> ```Java
>   String stageId;
>   String artifactType;
>   String artifactTag;
> ```

can you add tests for these new fields



_Code quote:_
```Java
  String serviceIdentifier;
  String envIdentifier;
  @NotNull private String projectIdentifier;
  @NotNull private String orgIdentifier;

  @FdSparseIndex String planExecutionId;
  String pipelineId;
  String pipelineName;
  String stageStepId;
  String stageId;
  String artifactType;
  String artifactTag;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NaySrT42Qbh8xsf-J4G:-NaySrT42Qbh8xsf-J4H:b-6w8lsz) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java#L105)):*
> ```Java
>             .orgIdentifier(serviceEnvironmentParams.getOrgIdentifier())
>             .accountId(serviceEnvironmentParams.getAccountIdentifier())
>             .monitoredServiceIdentifier(monitoredServiceIdentifier)
> ```

why did we remove this? we need this



_Code quote:_
```Java
.monitoredServiceIdentifier(monitoredServiceIdentifier)
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NaySuYV026dE_OpC-nG:-NaySuYV026dE_OpC-nH:b9xxmzh) ([raw file](https://github.com/harness/harness-core/blob/30f444d4194f74facce3312f9e028a4a4ea8c9ed/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java#L251)):*
> ```Java
>   private String getStepName(String monitoredServiceIdentifier) {
>     return "SRM Step Analysis of " + monitoredServiceIdentifier;
>   }
> ```

stepname is what user added as a step Name, stepElementParameters.getName()



_Code quote:_
```Java
  private String getStepName(String monitoredServiceIdentifier) {
    return "SRM Step Analysis of " + monitoredServiceIdentifier;
  }
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NayTC4X9ZoHgExzht0B:-NayTC4X9ZoHgExzht0C:bmlhyg5) ([raw file](https://github.com/harness/harness-core/blob/30f444d4194f74facce3312f9e028a4a4ea8c9ed/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java#L169)):*
> ```Java
>       String executionDetailId = srmAnalysisStepService.createSRMAnalysisStepExecution(ambiance,
>           changeEventDTO.getMonitoredServiceIdentifier(), serviceEnvironmentParams, metadata.getAnalysisDuration(),
>           null);
> ```

Optional.empty()

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51326)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/SRMAnalysisStepExecutionDetail.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NayS9MxD_X1YZQqCEb4:-NazCzzp7P4K2UiAgfar:b-gfit4q) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/SRMAnalysisStepExecutionDetail.java#L82)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

we need pipelineName as well for report
</blockquote></details>

It is still there
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/51326#-NaySrT42Qbh8xsf-J4G:-NazD61D7f2KGqcfkwzh:b69btum) ([raw file](https://github.com/harness/harness-core/blob/ec47e84257a103a732058a427a4bb7a467b5bdb0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/services/impl/SRMAnalysisStepServiceImpl.java#L105)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why did we remove this? we need this
</blockquote></details>

it was being initialized twice, removed one

**Comment by karansaraswat19** [comment]
trigger uts

**Comment by karansaraswat19** [comment]
trigger uts

**Comment by karansaraswat19** [comment]
trigger uts

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51326#-:-Nb-fm7PEqCAqVpdmnnB:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
