### PR TITLE
Revert "[CDS-0]: logs for expanded json"

### PR DESCRIPTION
**Pull request by namanvermah**
Reverts harness/harness-core#48410

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48440)

### CODE REVIEW

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48440)* status: :shipit: complete! ✓

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48440)* status: :shipit: complete! ✓

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by ankittiwari-harness** [comment]
trigger uts

**Comment by namanvermah** [comment]
trigger review

**Comment by namanvermah** [comment]
trigger ut2

**Pull request merged**
