### PR TITLE
feat:[CDS-81891]: add support to send notifications on enabling freeze

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Add support to send notifications:
1. When the freeze is enabled, this is a new type of notification, so user has to first select that type and enable notifications for that. Then whenever the freeze is enabled(irrespective of active/in-active) notification will be sent for that.
2. When a freeze which is created/updated is enabled and currently active, we were previously sending notification only if the freeze was in future, now we will support sending notification if the freeze is currently active as well.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54391)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1, 8 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54391)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 331 at r3](https://reviewable.io/reviews/harness/harness-core/54391#-NhQ-HzfEgzLa7D7Dt8D:-NhQ-HzfEgzLa7D7Dt8E:biwzzt) ([raw file](https://github.com/harness/harness-core/blob/36c737dda5c02673c9245e7dc825d773be0e5f08/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L331)):*
> ```Java
>       freezeConfigEntity = freezeConfigEntityOptional.get();
>     }
>     notificationHelper.sendNotification(freezeConfigEntity.getYaml(), true, true, true, null, accountId, "", "", false);
> ```

can you add a a null check here.
It is possible for freezeConfigEntity to be null. Existing issue i think
___
*[`125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/54391#-NhQ0Lv76zIG4y54kMv1:-NhQ0Lv76zIG4y54kMv2:b-53x7on) ([raw file](https://github.com/harness/harness-core/blob/36c737dda5c02673c9245e7dc825d773be0e5f08/125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java#L76)):*
> ```Java
>           String templateId = getNotificationTemplate(wrapper.getType(), freezeEvent);
>           if (freezeEvent.getType().equals(FreezeEventType.FREEZE_WINDOW_ENABLED) && !freezeWindowNotification) {
>             continue;
> ```

qq: freezeWindowNotification and freezeEnabledNotification when true, we don't sed the notification

**Comment by sourabh-awashti** [comment]
@RishabhGupta34 what is the expected behaviour when freeze has been enabled and currently active, then should we send both the notification or only enabled one?? according to current logic, notification will go only for enabled one

**Comment by RishabhGupta34** [comment]
> @RishabhGupta34 what is the expected behaviour when freeze has been enabled and currently active, then should we send both the notification or only enabled one?? according to current logic, notification will go only for enabled one

If freeze is enabled and currently active we will send a notification that it's active, also if the user has also selected the new notification type for is enabled, we will send a notification for that as well.

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger ut2

**Review by sourabh-awashti — APPROVED** [review]
LGTM

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger ut8

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger ut0, ut2

**Review by sourabh-awashti — APPROVED** [review]
LGTM

**Comment by RishabhGupta34** [comment]
trigger ut0, messagecheck

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54391)* status: 17 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54391)* status: 17 file(s) to review.

**Comment by abhinavmittal-harness** [comment]
trigger review

**Pull request merged**
