### PR TITLE
feat: [PIE-4028]: Separate Resource interface from Resource Implement…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…ation

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 19 files at r1, 19 of 22 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)* status: 31 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`100-migrator/BUILD.bazel` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/35268#-N6rNiRJ4tMakgnRlQPE:-N6rNiRJ4tMakgnRlQPF:b-m27nif) ([raw file](https://github.com/harness/harness-core/blob/b852dc1e4e3f13d94f9022632f8d3068558d7aae/100-migrator/BUILD.bazel#L36)):*
> ```Starlark
>         "//460-capability:module",
>         "//800-pipeline-service:module",
>         "//800-pipeline-service/contracts:module",
> ```

is this needed?



_Code quote:_
```Starlark
//800-pipeline-service/contracts:module"
```
___
*[`800-pipeline-service/contracts/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/35268#-N6rNo3D6IoUYjCu6Cq5:-N6rNo3D6IoUYjCu6Cq6:b-m9xs8r) ([raw file](https://github.com/harness/harness-core/blob/b852dc1e4e3f13d94f9022632f8d3068558d7aae/800-pipeline-service/contracts/BUILD.bazel#L13)):*
> ```Starlark
>         "//:lombok",
>         "//800-pipeline-service/modules/orchestration-steps:module",
>         "//800-pipeline-service/modules/orchestration-visualization:module",
> ```

should not use complete internal modules, just its contract if needed



_Code quote:_
```Starlark
        "//800-pipeline-service/modules/orchestration-steps:module",
        "//800-pipeline-service/modules/orchestration-visualization:module",
```
___
*[`800-pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/35268#-N6rODrG5LoOGXv4SaxM:-N6rODrG5LoOGXv4SaxN:bkh6ia9) ([raw file](https://github.com/harness/harness-core/blob/b852dc1e4e3f13d94f9022632f8d3068558d7aae/800-pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResourceImpl.java#L42)):*
> ```Java
> import java.util.Map;
> import javax.validation.constraints.NotNull;
> import javax.ws.rs.core.HttpHeaders;
> ```

remove httHeaders as well



_Code quote:_
```Java
HttpHeaders
```
___
*[`884-pms-commons/src/main/java/io/harness/pms/rbac/PipelineRbacPermissions.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/35268#-N6rOa6k-I-dA02MVlzL:-N6rOa6k-I-dA02MVlzM:b-hl1la9) ([raw file](https://github.com/harness/harness-core/blob/b50c75b037a6fb92460aac9f2d902a5659d876b5/884-pms-commons/src/main/java/io/harness/pms/rbac/PipelineRbacPermissions.java#L15)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> public interface PipelineRbacPermissions {
> ```

why it needs to be moved?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)* status: 31 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/contracts/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/35268#-N6rNo3D6IoUYjCu6Cq5:-N6rShIC5Y1U1TdzdVCB:bu2mqhj) ([raw file](https://github.com/harness/harness-core/blob/b852dc1e4e3f13d94f9022632f8d3068558d7aae/800-pipeline-service/contracts/BUILD.bazel#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should not use complete internal modules, just its contract if needed
</blockquote></details>

Have added only those which are required by contracts packages

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)* status: 31 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`100-migrator/BUILD.bazel` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/35268#-N6rNiRJ4tMakgnRlQPE:-N6rSofG8f9IIt8-OsfP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b852dc1e4e3f13d94f9022632f8d3068558d7aae/100-migrator/BUILD.bazel#L36)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

This is required for PmsClient.java. It depends on PipelineSaveResponse which exists in contracts package
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)* status: 31 file(s) to review. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/contracts/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/35268#-N6rNo3D6IoUYjCu6Cq5:-N6rbq0VEixL-CWzFLl_:b-8w8wen) ([raw file](https://github.com/harness/harness-core/blob/b852dc1e4e3f13d94f9022632f8d3068558d7aae/800-pipeline-service/contracts/BUILD.bazel#L13)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

What about visualisation module
</blockquote></details>

discussed will be done in another pr

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 19 files at r1, 12 of 22 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)* status: 9 file(s) to review.

**Review by hextechpal — APPROVED** [review]
> Reviewed 6 of 19 files at r1, 13 of 22 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35268)* status: 8 file(s) to review.

**Pull request merged**
