### PR TITLE
feat: [PIE-5360]: added APIs to mark the step as fail and success

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37705)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 18 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 15 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37705)

**Comment by shalini-agr** [comment]
trigger authorcheck

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 7 of 20 files at r1, 10 of 12 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37705)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37705)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 44 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZT7LOASG35G68f4HS:-NCZT7LOASG35G68f4HT:bmfeurb) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L44)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> @Api("/pipeline/waitStep")
> ```

Do we really need pipeline in the path?
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 53 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZTDyY0dxwwtsBWl3s:-NCZTDyY0dxwwtsBWl3t:b-ih9mzb) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L53)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> @Tag(name = "Wait Step", description = "This contains APIs related to wait step of Pipelines")
> ```

Do you want this to expose to customers right now? (Exposing to customers means a part of our public APi docs)

If not, remove Tag annotation from here.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZeNmY5blgVdrweDvj:-NCZeNmY5blgVdrweDvk:b-dup3bq) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L75)):*
> ```Java
>   @POST
>   @Path("/{nodeExecutionId}")
>   @ApiOperation(value = "Marks the wait step as fail or success", nickname = "markWaitStep")
> ```

Wait Step (keep W and S capital) as nouns
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 91 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZfnCg0eHMHrEPvJno:-NCZfnCg0eHMHrEPvJnp:b-oopbci) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L91)):*
> ```Java
>       @NotNull @Parameter(description = PipelineResourceConstants.PROJECT_PARAM_MESSAGE, required = true) @QueryParam(
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId,
>       @PathParam("nodeExecutionId") String nodeExecutionId, @Body WaitStepRequestDto waitStepRequestDto);
> ```

I think you would need RequestBody openApi annotation here
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 93 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZetWKAjVxJb-PXvQr:-NCZetWKAjVxJb-PXvQs:b-ky0ekf) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L93)):*
> ```Java
>       @PathParam("nodeExecutionId") String nodeExecutionId, @Body WaitStepRequestDto waitStepRequestDto);
>   @GET
>   @Path("/getWaitStepExecutionDetails/{nodeExecutionId}")
> ```

waitStep already part of path param, don't repeat

also since GET method is used, no need of get in path param.

Directly start from  "executionDetails"

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37705)* status: 22 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 44 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZT7LOASG35G68f4HS:-NCZydiH8HPFLV1ctZuU:b76zee2) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L44)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Do we really need pipeline in the path?
</blockquote></details>

No, removing it from the path
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 53 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZTDyY0dxwwtsBWl3s:-NCZyjhzAYuribhx7j4J:b-563x1a) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L53)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Do you want this to expose to customers right now? (Exposing to customers means a part of our public APi docs)

If not, remove Tag annotation from here.
</blockquote></details>

commenting this line for now, will add back when we remove the FF
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZeNmY5blgVdrweDvj:-NCZynet-Sjy_gSFRUXC:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L75)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Wait Step (keep W and S capital) as nouns
</blockquote></details>

done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 91 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZfnCg0eHMHrEPvJno:-NCZyoxu3SC_OtJyekXh:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L91)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

I think you would need RequestBody openApi annotation here
</blockquote></details>

done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java` line 93 at r5](https://reviewable.io/reviews/harness/harness-core/37705#-NCZetWKAjVxJb-PXvQr:-NCZyplJByQRDOCWa3X9:b-7rl0jd) ([raw file](https://github.com/harness/harness-core/blob/455553fbdbe82d41ee98319270b4a35e9e56feb7/pipeline-service/contracts/src/main/java/io/harness/pms/wait/WaitStepResource.java#L93)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

waitStep already part of path param, don't repeat

also since GET method is used, no need of get in path param.

Directly start from  "executionDetails"
</blockquote></details>

done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 5 of 20 files at r1, 8 of 12 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37705)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37705)* status: :shipit: complete! ✓

**Pull request merged**
