### PR TITLE
fix: [CDS-83655]: handle conditional and looping jexl operators in concatenated expressions

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** While checking logs for fallback for concatenation, we found a user scenario, where they were using conditional computation in one of their expressions. This wasn't supported by concatenation. 
Eg: `<+if ((<+pipeline.variables.foo> == "null") || (empty(<+pipeline.variables.foo>))) {"csml";} else {<+pipeline.variables.foo>;}>`

**Changes:** Add handling for conditional and looping computations in expressions with concatenation. 

**Testing:** Added unit tests and tested user scenarios locally.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55276)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger gitleaks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55276)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55276)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ut7

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 294 at r3](https://reviewable.io/reviews/harness/harness-core/55276#-NjQkm1YAvFk_E08jGaD:-NjQkm1Z3MFju0bROkF2:b-d2ppkd) ([raw file](https://github.com/harness/harness-core/blob/1ee51501bcf91206abeb7a2b1267d6475e34d2a0/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L294)):*
> ```Java
>   private boolean checkConditionalOrLoopOperators(StringBuffer s, int currentPos) {
>     String leftSubString = s.substring(0, currentPos + 1);
>     Set<String> jexlKeywordOperators = Set.of("if", "else", "for", "while", "do");
> ```

Should we keep it as static constant?

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 297 at r3](https://reviewable.io/reviews/harness/harness-core/55276#-NjQkpmU8DbgwJNKVljy:-NjQkpmU8DbgwJNKVljz:b2jvr7y) ([raw file](https://github.com/harness/harness-core/blob/1ee51501bcf91206abeb7a2b1267d6475e34d2a0/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L297)):*
> ```Java
>     int minLength = 2;
>     int maxLength = 5;
>     for (int i = 0; i < leftSubString.length(); i++) {
> ```

Can we add description as to what it is doing?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55276)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 294 at r3](https://reviewable.io/reviews/harness/harness-core/55276#-NjQkm1YAvFk_E08jGaD:-NjQlie7026XeIsmv7m-:bv3alkq) ([raw file](https://github.com/harness/harness-core/blob/1ee51501bcf91206abeb7a2b1267d6475e34d2a0/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L294)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we keep it as static constant?
</blockquote></details>

This set is relevant to this method only, so, shouldn't be needed to keep a static constant for the class, right?
___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 297 at r3](https://reviewable.io/reviews/harness/harness-core/55276#-NjQkpmU8DbgwJNKVljy:-NjQm81g0b_xKlz1lz4V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1ee51501bcf91206abeb7a2b1267d6475e34d2a0/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L297)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add description as to what it is doing?
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 294 at r3](https://reviewable.io/reviews/harness/harness-core/55276#-NjQkm1YAvFk_E08jGaD:-NjQqYoL5EC917KzwN0P:b2ll8iw) ([raw file](https://github.com/harness/harness-core/blob/1ee51501bcf91206abeb7a2b1267d6475e34d2a0/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L294)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

This set is relevant to this method only, so, shouldn't be needed to keep a static constant for the class, right?
</blockquote></details>

Yes, ideally was thinking that if anytime we need this set, we can get it via instance variable therefore ensuring that we don't create this set always.
It should not affect much but for sets which are static by definition should be kept static.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55276)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55276)* status: 2 file(s) to review.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
