### PR TITLE
fix: [CVS-9120]: allow for slo custom health

### PR DESCRIPTION
**Pull request by anjanBalgovind**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30755)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30755)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java, line 492 at r1](https://reviewable.io/reviews/harness/harness-core/30755#-Mvvjo9w8-I7PL2Gn4Cw:-Mvvjo9w8-I7PL2Gn4Cx:b49jj0n) ([raw file](https://github.com/harness/harness-core/blob/109a755768190df5e524656b2f12e064e5b76adc/300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java#L492)):*
> ```Java
>         .to(StackdriverDataCollectionInfoMapper.class)
>         .in(Scopes.SINGLETON);
>     dataSourceTypeDataCollectionSLIInfoMapperMapBinder.addBinding(DataSourceType.CUSTOM_HEALTH)
> ```

can you please add a test so that we don't miss it for any DataSourceType?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CustomHealthSourceSpecTransformer.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/30755#-MvvoXCT7KlZMEUPc_k5:-MvvoXCU4oGdgiizv7uB:b-yz3xdq) ([raw file](https://github.com/harness/harness-core/blob/109a755768190df5e524656b2f12e064e5b76adc/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CustomHealthSourceSpecTransformer.java#L31)):*
> ```Java
>     cvConfigGroup.forEach(customHealthCVConfig -> {
>       customHealthCVConfig.getMetricDefinitions().forEach(definition -> {
>         SLIDTO slidto = definition.getSli() != null ? definition.getSli() : SLIDTO.builder().enabled(false).build();
> ```

we should not add the null check. Default case is handled in the getter already.
io.harness.cvng.core.entities.AnalysisInfo#getSli

We should also add a test covering this.

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CustomHealthSourceSpecTransformer.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/30755#-MvvoXCT7KlZMEUPc_k5:-MvyBVBp0Zdj2vfIaGcu:bm6anc0) ([raw file](https://github.com/harness/harness-core/blob/109a755768190df5e524656b2f12e064e5b76adc/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CustomHealthSourceSpecTransformer.java#L31)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should not add the null check. Default case is handled in the getter already.
io.harness.cvng.core.entities.AnalysisInfo#getSli

We should also add a test covering this.
</blockquote></details>

@kjoshi12345 without this null check saving SLO for custom health resulted in a NPE. And getSLI is coming from HealthSourceMetricDefinition and not AnalysisInfo

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30755)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CustomHealthSourceSpecTransformer.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/30755#-MvvoXCT7KlZMEUPc_k5:-MvyENOv8B8De3suvK3f:biffi59) ([raw file](https://github.com/harness/harness-core/blob/109a755768190df5e524656b2f12e064e5b76adc/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CustomHealthSourceSpecTransformer.java#L31)):*
<details><summary><i>Previously, anjanBalgovind (Anjan Balgovind) wrote…</i></summary><blockquote>

@kjoshi12345 without this null check saving SLO for custom health resulted in a NPE. And getSLI is coming from HealthSourceMetricDefinition and not AnalysisInfo
</blockquote></details>

yes my bad. We should not allow null from the ui. UI should send false if it is not enabled. 
We can also add preconditions here.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30755)* status: :shipit: complete! ✓

**Pull request merged**
