### PR TITLE
feat: [CDS-41263]: secret output variables support for shell script/custom approval

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. Support output vars to be given as secret type
2. Sanitise the usage of these vars in execution logs and UI 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 4 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36521)

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 7 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: 7 file(s) to review. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3q5yB6b4kn32uloZn:-NA3q5yB6b4kn32uloZo:bxfiiwa) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java#L43)):*
> ```Java
>   @NotNull ParameterField<Timeout> retryInterval;
>   Map<String, Object> outputVariables;
>   Set<String> secretOutputVariables;
> ```

jsonignore or something to remove from the inputs tab
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperService.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3r6whCenGzjYxm_e2:-NA3r6whCenGzjYxm_e3:bbp59ah) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperService.java#L66)):*
> ```Java
>       Object value = ((ParameterField<?>) outputVariables.get(name)).getValue();
>       if (EmptyPredicate.isNotEmpty(secretOutputVariables) && secretOutputVariables.contains(name)) {
>         String encodedValue = EncodingUtils.encodeBase64(
> ```

we can move this logic to functor. anyone using the functor can make use of it.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3rlGkArIm3m60g3K8:-NA3rlGkArIm3m60g3K9:b2nhpjj) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L111)):*
> ```Java
> 
>   @Override
>   public List<String> getOutputVars(Map<String, Object> outputVariables, Set<String> secretOutputVariables) {
> ```

UTs
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3rd2_2Yy4HM0L_w1M:-NA3rd2_2Yy4HM0L_w1N:bmrxw36) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L122)):*
> ```Java
>           ParameterField<?> parameterFieldValue = (ParameterField<?>) val;
>           if (parameterFieldValue.getValue() == null) {
>             throw new InvalidRequestException(String.format("Output variable [%s] value found to be null", key));
> ```

null -> empty

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 7 of 14 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger codebasehash

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/36521#-NBBUvmsBt6t3_JRXDrn:-NBBUvmtEVVG8vh6oobI:b-uswsu0) ([raw file](https://github.com/harness/harness-core/blob/f34d3c09dc84b6b2d413302610d89ab6ebc71ece/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java#L52)):*
> ```Java
>   @Override
>   public SpecParameters getViewJsonObject() {
>     this.secretOutputVariables = null;
> ```

Better to clone and then set this to null so that it doesn't affect this.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/shellscript/ShellScriptStepParameters.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/36521#-NBBWApc6GfwYdc9uIaY:-NBBWApc6GfwYdc9uIaZ:b-5h08c7) ([raw file](https://github.com/harness/harness-core/blob/f34d3c09dc84b6b2d413302610d89ab6ebc71ece/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/shellscript/ShellScriptStepParameters.java#L52)):*
> ```Java
>   @Override
>   public SpecParameters getViewJsonObject() {
>     this.secretOutputVariables = null;
> ```

same here.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: 2 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3q5yB6b4kn32uloZn:-NBBokv_EgnxJumhH69_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java#L43)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

jsonignore or something to remove from the inputs tab
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/36521#-NBBUvmsBt6t3_JRXDrn:-NBBolSA9a-HZv8rC9RW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f34d3c09dc84b6b2d413302610d89ab6ebc71ece/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/custom/CustomApprovalSpecParameters.java#L52)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Better to clone and then set this to null so that it doesn't affect this.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/shellscript/ShellScriptStepParameters.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/36521#-NBBWApc6GfwYdc9uIaY:-NBBomJu4wNfGxO4U7nN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f34d3c09dc84b6b2d413302610d89ab6ebc71ece/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/shellscript/ShellScriptStepParameters.java#L52)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperService.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3r6whCenGzjYxm_e2:-NBBonKf6ZhYFFnBjiQK:bke2cfz) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperService.java#L66)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

we can move this logic to functor. anyone using the functor can make use of it.
</blockquote></details>

will create a techdebt for it
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3rlGkArIm3m60g3K8:-NBBoqn66hXnnzYcj0cN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L111)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

UTs
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/36521#-NA3rd2_2Yy4HM0L_w1M:-NBBorNbD3oNvF_OozJy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b74d57debfb2b8fb876b98dda8e778f2d743fdc/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptHelperServiceImpl.java#L122)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

null -> empty
</blockquote></details>

Done.

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained.

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: 4. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36521)* status: 4. unresolved discussions.

**Pull request merged**
