### PR TITLE
fix: [CDS-46295]: use mongo count queries instead of loading all instances

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
`CDPipelineEndEventHandler` emits a telemetry event containing 2 count values:
- Count of service instances
- Count of distinct active services

Currently, we are loading all service instances in memory and then calculating these counters as explained below:

// Loading all instances
> List<InstanceDTO> serviceInstances = cdPipelineInstrumentationHelper.getServiceInstancesInInterval(
        accountId, orgId, projectId, currentTS - searchingPeriod, currentTS);

// telemetry event 1
> cdPipelineInstrumentationHelper.sendCountOfServiceInstancesEvent(
        pipelineId, identity, accountId, accountName, orgId, projectId, serviceInstances);

// telemetry event 2
> cdPipelineInstrumentationHelper.sendCountOfDistinctActiveServicesEvent(
        pipelineId, identity, accountId, accountName, orgId, projectId, serviceInstances);
-----------------------------------------------------------------------
**input** -> accountId, orgId, projectId, startTS, endTS
if orgId & projectId empty -> get all instances using accountId, startTS and endTS
else  -> get all instances for accountId, orgID, projectId, startTS, endTS
**output** -> list of all instances, `list-A`

**telemetry event 1 uses size of `list-A`**

-----------------------------------------------------------------------
**input** -> accountId, orgId, projectId, startTS, endTS
if listA is empty, get list of all instances from above and pass to next step
else pass `list-A` to get calculate `list-B`:
_create list of distinct orgID-projectID-serviceId tuples `list-B`_
**output** -> length of `list-B`

**telemetry event 2 uses size of `list-B`**

-----------------------------------------------------------------------

This change replaces this logic by using direct mongo queries to calculate these counters.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39930)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/39930#-NGW3BvEEllWApFo69iQ:-NGW3BvEEllWApFo69iR:bhe9q7m) ([raw file](https://github.com/harness/harness-core/blob/f49ddca98eaf2c2ca6de123db9783f354fee25f3/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java#L68)):*
> ```Java
> 
>     long countOfDistinctActiveServiceInstances =
>         cdPipelineInstrumentationHelper.getCountOfDistinctActiveServiceInstancesInInterval(
> ```

this method should be called 
"countOfDistinctActiveServices" because it is counting services and not service instances

**Comment by yogesh-chauhan** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 470 at r1](https://reviewable.io/reviews/harness/harness-core/39930#-NGWAq_bEBHwLemBb7K0:-NGWAq_bEBHwLemBb7K1:b7lpglc) ([raw file](https://github.com/harness/harness-core/blob/f49ddca98eaf2c2ca6de123db9783f354fee25f3/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L470)):*
> ```Java
>   @Override
>   public long countDistinctActiveServiceInstancesDeployedInInterval(
>       String accountId, String orgId, String projectId, long startTS, long endTS) {
> ```

since we already know org and project, should they not be a part of "filter" rather than group by ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39930)* status: 3 file(s) to review. 0 of 1 approvals obtained.

**Comment by abhinavsingh1196** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/39930#-NGW3BvEEllWApFo69iQ:-NGWPQ9W16AB466OxAuA:brythj3) ([raw file](https://github.com/harness/harness-core/blob/f49ddca98eaf2c2ca6de123db9783f354fee25f3/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java#L68)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this method should be called 
"countOfDistinctActiveServices" because it is counting services and not service instances
</blockquote></details>

renamed

**Comment by abhinavsingh1196** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 470 at r1](https://reviewable.io/reviews/harness/harness-core/39930#-NGWAq_bEBHwLemBb7K0:-NGWPW8W0X7fgilHcdAN:b-gfv11) ([raw file](https://github.com/harness/harness-core/blob/f49ddca98eaf2c2ca6de123db9783f354fee25f3/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L470)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

since we already know org and project, should they not be a part of "filter" rather than group by ?
</blockquote></details>

yes, I have modified the query to make it simpler

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39930)* status: :shipit: complete! ✓

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r2, 5 of 6 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39930)* status: :shipit: complete! ✓

**Comment by AnshuH** [comment]
trigger igpCheckStyle

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39930)* status: :shipit: complete! ✓

**Pull request merged**
