### PR TITLE
[fix]: [PL-31451]: Adds migration to regenerate acls for default viewer roles in all scopes

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds migration to regenerate acls for default viewer roles in all scopes. This will run one time migration for accounts having FF `PL_REGENERATE_ACL_FOR_DEFAULT_VIEWER_ROLE` enabled

Tests:
- Manually deleted acl from local and verified it's regeneration after migration
- Added unit tests to verify acls generated

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47329)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47329)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/47329#-NU_GLn5AImJVhN3qYLf:-NU_GLn5AImJVhN3qYLg:b761d3j) ([raw file](https://github.com/harness/harness-core/blob/74300fd2ef12711068fb5f3d15fa6d3ce1aed94c/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java#L119)):*
> ```Java
>                             .is(USER_GROUP)
>                             .and(RoleAssignmentDBOKeys.roleIdentifier)
>                             .is(getRoleIdentifier(scopeLevel))
> ```

Add filter for resource group as well. This is to ensure we only process default viewer role assignments.
We can use NGConstants 
DEFAULT_ACCOUNT_LEVEL_RESOURCE_GROUP_IDENTIFIER
DEFAULT_ORGANIZATION_LEVEL_RESOURCE_GROUP_IDENTIFIER
DEFAULT_PROJECT_LEVEL_RESOURCE_GROUP_IDENTIFIER

**Comment by ashishsanodia-harness** [comment]
trigger ss

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/47329#-NU_GLn5AImJVhN3qYLf:-NUaQBSr-DNubCdVndp-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74300fd2ef12711068fb5f3d15fa6d3ce1aed94c/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java#L119)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add filter for resource group as well. This is to ensure we only process default viewer role assignments.
We can use NGConstants 
DEFAULT_ACCOUNT_LEVEL_RESOURCE_GROUP_IDENTIFIER
DEFAULT_ORGANIZATION_LEVEL_RESOURCE_GROUP_IDENTIFIER
DEFAULT_PROJECT_LEVEL_RESOURCE_GROUP_IDENTIFIER
</blockquote></details>

Done.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47329)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/47329#-NUagGXz7XF5sJzPdkwT:-NUagGY-5INw-O_KFR9r:b-7u124h) ([raw file](https://github.com/harness/harness-core/blob/6fc5c3378da7624f6d0939e716f02e43bfc1b179/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java#L94)):*
> ```Java
>     Set<String> targetAccounts = featureFlagService.getAccountIds(PL_REGENERATE_ACL_FOR_DEFAULT_VIEWER_ROLE);
> 
>     for (String account : targetAccounts) {
> ```

We can run as Migration then we can add sleep of 3-5 mins after processing one account or convert this into job  to avoid any load on the system. The job can be run once in 24 hrs and removed in subsequent release.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/47329#-NUagGXz7XF5sJzPdkwT:-NUfAJeW5NTzukZziw6W:b-pujd8n) ([raw file](https://github.com/harness/harness-core/blob/6fc5c3378da7624f6d0939e716f02e43bfc1b179/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/DefaultViewerRoleAssignmentMigration.java#L94)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We can run as Migration then we can add sleep of 3-5 mins after processing one account or convert this into job  to avoid any load on the system. The job can be run once in 24 hrs and removed in subsequent release.
</blockquote></details>

converted one time migration to scheduled job which runs in every 24Hrs

**Comment by ashishsanodia-harness** [comment]
trigger ut8

**Comment by AnshuH** [comment]
trigger ut0 ut1

**Comment by AnshuH** [comment]
trigger uts

**Comment by AnshuH** [comment]
trigger ti8

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47329)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationService.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/47329#-NUk8s0KBdrwfwnvkZTQ:-NUk8s0KBdrwfwnvkZTR:b2d049a) ([raw file](https://github.com/harness/harness-core/blob/767c5a8ec0734094feeb2bf8e3447a06fe712cec/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationService.java#L44)):*
> ```Java
>     Random random = new Random();
>     int delay = random.nextInt(15) + 15;
>     defaultViewerRoleACLCreationJobFuture =
> ```

Change 2 to run 1440.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationService.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/47329#-NUk8s0KBdrwfwnvkZTQ:-NUljTvjE3vr1SawKSL8:b-ngskf9) ([raw file](https://github.com/harness/harness-core/blob/767c5a8ec0734094feeb2bf8e3447a06fe712cec/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationService.java#L44)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Change 2 to run 1440.
</blockquote></details>

good catch. missed during local testing. Fixed it

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut2

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut0

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 1 of 3 files at r4, 3 of 6 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47329)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47329)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationJob.java` line 132 at r11](https://reviewable.io/reviews/harness/harness-core/47329#-NV8-FxCA6RkPm-fKIvD:-NV8-FxCA6RkPm-fKIvE:b5bd320) ([raw file](https://github.com/harness/harness-core/blob/1a9e76fed64ce8cea37a7018ef2f0cac36b654cd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationJob.java#L132)):*
> ```Java
>   private CloseableIterator<RoleAssignmentDBO> runQueryWithBatch(String scopeIdentifier, ScopeLevel scopeLevel) {
>     Pattern startsWithScope = Pattern.compile("^" + scopeIdentifier);
>     Criteria criteria = Criteria.where(RoleAssignmentDBOKeys.scopeIdentifier)
> ```

Check which index is used and change the order of properties in query if needed.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut0, trigger ut2

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationJob.java` line 132 at r11](https://reviewable.io/reviews/harness/harness-core/47329#-NV8-FxCA6RkPm-fKIvD:-NVDJMu86Pfocdj68BLF:b70qptl) ([raw file](https://github.com/harness/harness-core/blob/1a9e76fed64ce8cea37a7018ef2f0cac36b654cd/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/worker/DefaultViewerRoleACLCreationJob.java#L132)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Check which index is used and change the order of properties in query if needed.
</blockquote></details>

Yes, It is using principalIndex because regex is being used for scope Identifier in query



_Code snippet:_
```Java
CompoundMongoIndex.builder()
                 .name("principalIndex")
                 .field(RoleAssignmentDBOKeys.principalType)
                 .field(RoleAssignmentDBOKeys.principalScopeLevel)
                 .field(RoleAssignmentDBOKeys.principalIdentifier)
                 .field(RoleAssignmentDBOKeys.scopeIdentifier)
                 .build()
```

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47329#-:-NVFm_pz1010S04taV63:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
