### PR TITLE
feat: [PL-39413]: Added support for usage type and usage data in EntityUsageActivityDetail

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Currently, the entity usage framework does not capture any details about the usage type and usage-specific data.
This PR introduces EntityUsageDetail which consists of an enum "EntityUsageType" and an abstract class "EntityUsageData". 
This way for each entity usage, along with the referredByEntity, we can also capture the usage context. 
For eg- 
A secret gets used in a pipeline execution. The current NGActivity class can enable us to capture only the referredByEntity type as a "Pipeline". But, in order to capture the exact usage context i.e. "Pipeline Execution" as well as the usage specific data (like execution ID, etc.) we will need the usage details that this PR introduces. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49178)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Review by nishantsaini20 — DISMISSED** [review]

**Comment by tiwaritejas** [comment]
trigger ut0,ut1

**Comment by piyush-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/49178#-NXzoC2nBryV6HTxkJnT:-NXzoC2nBryV6HTxkJnU:b-ryal2i) ([raw file](https://github.com/harness/harness-core/blob/0174e6479f1b0f237fc8e48fdde7f8b0823bbbef/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L16)):*
> ```Java
>     EntityUsageData usageData = getUsageData(detail);
>     return EntityUsageDetail.builder()
>         .usageType(EntityUsageType.valueOf(detail.getEventType().name()))
> ```

Enums implemented without go live functionality will fail if used across micro-services on different versions, We have seen these issues in past where One micro-service introduces an enum and other service has not yet got the code and it fails. So either we should use String or look ModuleType implementation to use enums in backward/forward compatible way.

**Comment by AnshuH** [comment]
trigger recency

**Comment by AnshuH** [comment]
trigger recency

**Comment by tiwaritejas** [comment]
trigger uts

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49178)* status: 17 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/49178#-NXzoC2nBryV6HTxkJnT:-NZ-k6an0fh2qks9t5OH:b-15iq50) ([raw file](https://github.com/harness/harness-core/blob/0174e6479f1b0f237fc8e48fdde7f8b0823bbbef/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageEventDetailProtoTORestMapper.java#L16)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Enums implemented without go live functionality will fail if used across micro-services on different versions, We have seen these issues in past where One micro-service introduces an enum and other service has not yet got the code and it fails. So either we should use String or look ModuleType implementation to use enums in backward/forward compatible way.
</blockquote></details>

We are now using a string instead of an enum here. Please check. Thanks!

**Comment by piyush-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/49178#-NZ2B9WU9iI_b9MoX92W:-NZ2B9WU9iI_b9MoX92X:b-67noe3) ([raw file](https://github.com/harness/harness-core/blob/4d54804f252e9b78ab4bc8057425a639d6d24b75/970-ng-commons/src/main/java/io/harness/ng/core/entityusageactivity/EntityUsageDetailDeserializer.java#L23)):*
> ```Java
>       throws IOException {
>     JsonNode parentJsonNode = jsonParser.getCodec().readTree(jsonParser);
>     JsonNode typeNode = parentJsonNode.get("usageType");
> ```

Do necessary null checks in this method

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 2 of 14 files at r1, 9 of 14 files at r2, 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49178)* status: 17 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): del-team.

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49178)* status: 17 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 14 files at r1, 9 of 14 files at r2, 6 of 6 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49178)* status: Waiting on team(s): del-team.

**Comment by tiwaritejas** [comment]
trigger uts

**Review by AnupamIO — APPROVED** [review]

**Pull request merged**
