### PR TITLE
feat: [PIE-6735]: We should have a failure strategy which is a delega…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…te disconnect

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42657)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
*[`980-commons/src/main/java/io/harness/eraro/FailureType.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/42657#-NLyS7PC7unxIetIKeTd:-NLyS7PC7unxIetIKeTe:b2b3fir) ([raw file](https://github.com/harness/harness-core/blob/3e0d0e90c06b929aa8629967c83761b17eb67750/980-commons/src/main/java/io/harness/eraro/FailureType.java#L28)):*
> ```Java
>   INPUT_TIMEOUT_FAILURE(""),
>   APPROVAL_REJECTION(""),
>   DELEGATE_RESTART("");
> ```

Why are we calling this restart? Do we deterministically know that the failure is because of delegare_restart and not some connection issue?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42657)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`980-commons/src/main/java/io/harness/eraro/FailureType.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/42657#-NLyS7PC7unxIetIKeTd:-NLyW7iF8n7ZXFqPFBT0:bnn1wh5) ([raw file](https://github.com/harness/harness-core/blob/3e0d0e90c06b929aa8629967c83761b17eb67750/980-commons/src/main/java/io/harness/eraro/FailureType.java#L28)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why are we calling this restart? Do we deterministically know that the failure is because of delegare_restart and not some connection issue?
</blockquote></details>

The name is as per this ticket - https://harness.atlassian.net/browse/PIE-6735

**Comment by prashantsharma04** [comment]
trigger ti1

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42657)* status: 12 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42657)* status: Waiting on team(s): sto.

**Pull request merged**
