### PR TITLE
[fix]: [PL-25519]: fix the IndexOutOfBound exception

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33578)

### CODE REVIEW

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33578#-:-N3Xs4IN4fFgg7Kfw734:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33578#-:-N3XsNjX6q61HbNLocAH:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/scim/NGScimGroupServiceImplTest.java` line 160 at r2](https://reviewable.io/reviews/harness/harness-core/33578#-N3YIy734iyDsh1RxNPL:-N3YIy734iyDsh1RxNPM:b-v2q71m) ([raw file](https://github.com/harness/harness-core/blob/8cddae7d8cb837e84a64a6a782f38eb84feeb952/120-ng-manager/src/test/java/io/harness/ng/scim/NGScimGroupServiceImplTest.java#L160)):*
> ```Java
>   @Owner(developers = PRATEEK)
>   @Category(UnitTests.class)
>   public void testSearchGroupByName2() {
> ```

Please provide a name that tells what this test is doing.

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33578)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/scim/NGScimGroupServiceImplTest.java` line 160 at r2](https://reviewable.io/reviews/harness/harness-core/33578#-N3YIy734iyDsh1RxNPL:-N3YNcNRAB3UDwfPT5aI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8cddae7d8cb837e84a64a6a782f38eb84feeb952/120-ng-manager/src/test/java/io/harness/ng/scim/NGScimGroupServiceImplTest.java#L160)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Please provide a name that tells what this test is doing.
</blockquote></details>

Done.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/33578)

**Pull request closed without merging**
