### PR TITLE
[fix]: [PIE-7641]: Fix multideploymentSpawner step if both services a…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42643)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42643)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 441 at r1](https://reviewable.io/reviews/harness/harness-core/42643#-NLtjOWsBZ_t4Jr5Uz3q:-NLtjOWsBZ_t4Jr5Uz3r:br8cn04) ([raw file](https://github.com/harness/harness-core/blob/c649d249b17753e4180c9fdd8ed245038cf404e6/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L441)):*
> ```Java
> 
>   private boolean shouldDeployInParallel(EnvironmentsMetadata metadata) {
>     return metadata == null || (metadata.getParallel() != null && metadata.getParallel());
> ```

If metadata is null, deploy in parallel is true?

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42643)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 441 at r1](https://reviewable.io/reviews/harness/harness-core/42643#-NLtjOWsBZ_t4Jr5Uz3q:-NLtlfCT0O0jhKP4uTt8:bj2tdsg) ([raw file](https://github.com/harness/harness-core/blob/c649d249b17753e4180c9fdd8ed245038cf404e6/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L441)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

yes, if metadata is not given then we treat it as parallel.
This is from product
</blockquote></details>

nit, maybe add this in the comments for future readers in future PRs.

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 441 at r1](https://reviewable.io/reviews/harness/harness-core/42643#-NLtjOWsBZ_t4Jr5Uz3q:-NLtnYnE7H9zwkL500ks:bt1x0qp) ([raw file](https://github.com/harness/harness-core/blob/c649d249b17753e4180c9fdd8ed245038cf404e6/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L441)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, maybe add this in the comments for future readers in future PRs.
</blockquote></details>

Sure, will add

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 441 at r1](https://reviewable.io/reviews/harness/harness-core/42643#-NLtjOWsBZ_t4Jr5Uz3q:-NLtzKWJ7anvpHA7kljM:b5h3qel) ([raw file](https://github.com/harness/harness-core/blob/c649d249b17753e4180c9fdd8ed245038cf404e6/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L441)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Sure, will add
</blockquote></details>

nit: Boolean.TRUE == metadata.getParallel()

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42643)* status: 2 file(s) to review. 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42643)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42643)* status: :shipit: complete! ✓

**Pull request merged**
