### PR TITLE
[fix]: [PIE-7695]: Pre flight should only check for input set validators

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43191)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43191)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/43191#-NN0S_RY0ASzTtRnQss1:-NN0S_RY0ASzTtRnQss2:b3b4ym9) ([raw file](https://github.com/harness/harness-core/blob/6afcff3068e0f1db633fe10819da4c8df33d62dc/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java#L161)):*
> ```Java
>   Map<FQN, String> getInvalidFQNsInInputSetFromTemplateConfig(YamlConfig templateConfig, YamlConfig inputSetConfig) {
>     return getInvalidFQNsInInputSetFromTemplateConfig(templateConfig, inputSetConfig, false);
>   }
> ```

can we directly call lower method from callers? remove this small method creation



_Code quote:_
```Java
  Map<FQN, String> getInvalidFQNsInInputSetFromTemplateConfig(YamlConfig templateConfig, YamlConfig inputSetConfig) {
    return getInvalidFQNsInInputSetFromTemplateConfig(templateConfig, inputSetConfig, false);
  }
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43191)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/43191#-NN0S_RY0ASzTtRnQss1:-NN0XmD6EQsvMqn4Xkxv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6afcff3068e0f1db633fe10819da4c8df33d62dc/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java#L161)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we directly call lower method from callers? remove this small method creation
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43191)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43191)* status: :shipit: complete! ✓

**Pull request merged**
