### PR TITLE
[feat]: [SRM-13977]: added migration script to move ELK to NextGenHealthSourceSpec.

### PR DESCRIPTION
**Pull request by n00bitax**
…lthSourceSpec.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)

### CODE REVIEW

**Comment by n00bitax** [comment]
trigger messagecheck

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 614 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPd7ps2-t5bLeihx1iL:-NPd7ps2-t5bLeihx1iM:b-uh99zj) ([raw file](https://github.com/harness/harness-core/blob/b8267fed1283a4934d7ac695bbb8b3b7dfc3dfe5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L614)):*
> ```Java
>       "To silent ignore org.modelmapper.MappingException inside state machine executor", HarnessTeam.SPG),
>   PL_AUDIT_LOG_STREAMING_ENABLED("Enables AuditLogStreaming tab on AuditTrails page in account scope", HarnessTeam.PL),
>   SRM_ELK_LOGS_V2("Will enable Elasticsearch logs v2 health source in SRM", HarnessTeam.CV),
> ```

Have we confirmed that this FF is not being used anywhere
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPd85MNDtQEO5Sacx36:-NPd85MNDtQEO5Sacx37:b-wretfn) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L23)):*
> ```Java
> 
> @Slf4j
> public class UpdateELKCVConfigToV2 extends CVNGBaseMigration {
> ```

nit: NextGenLogCVConfig instead of V2
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPdALIA2mRUlmRZ-6-f:-NPdALIBATVMqOX44eKG:b-s61805) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L36)):*
> ```Java
>       log.info("starting UpdateELKCVConfigToV2 migration for cvConfigId: " + cvConfig.getFullyQualifiedIdentifier());
>       NextGenLogCVConfig nextGenLogCVConfig = getNextGenLogCVConfigFromELKCVConfig(cvConfig);
>       hPersistence.insertIgnoringDuplicateKeys(nextGenLogCVConfig);
> ```

Should we add some check to ensure the record has been inserted before deleting the older cv config

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 614 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPd7ps2-t5bLeihx1iL:-NPfC1OP9qXFypKajK7E:bg8p2nk) ([raw file](https://github.com/harness/harness-core/blob/b8267fed1283a4934d7ac695bbb8b3b7dfc3dfe5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L614)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Have we confirmed that this FF is not being used anywhere
</blockquote></details>

yes we will merge it together with UI changes.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPd85MNDtQEO5Sacx36:-NPf6T1m8tPrAqKhEzHh:bae0nj4) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L23)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

nit: NextGenLogCVConfig instead of V2
</blockquote></details>

changed v2 to nextgencvconfig
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPdALIA2mRUlmRZ-6-f:-NPf6XKE-GMnrDFr1sS4:b-b9rprm) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L36)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Should we add some check to ensure the record has been inserted before deleting the older cv config
</blockquote></details>

added another check with count > 1  && nextgencvconfig exists for a particular cv-config ID.

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPdALIA2mRUlmRZ-6-f:-NPpG3Q372MTdVdk26Ju:bcu2n05) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L36)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

added another check with count > 1  && nextgencvconfig exists for a particular cv-config ID.
</blockquote></details>

Why count > 1? Should it not be > 0 for ElkCvConfig?

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPdALIA2mRUlmRZ-6-f:-NPpRn3A3nyA_jp8nuJS:bou90cq) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L36)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Why count > 1? Should it not be > 0 for ElkCvConfig?
</blockquote></details>

we are querying explicitly for  NextGenLogCVConfig(filter by the new class) for the particular ID, the count will be exactly one right?



_Code quote (from srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToNextGenCVConfig.java):_
```Java
 NextGenLogCVConfig
```

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPdALIA2mRUlmRZ-6-f:-NPpYcws0VwezyUILIpa:b-7giwkn) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L36)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

we are querying explicitly for  NextGenLogCVConfig(filter by the new class) for the particular ID, the count will be exactly one right?
</blockquote></details>

      Query<ELKCVConfig> elkCVConfigCountQuery = hPersistence.createQuery(ELKCVConfig.class)
                                                     .disableValidation()
                                                     .filter("identifier", cvConfig.getFullyQualifiedIdentifier())
                                                     .filter("productName", cvConfig.getProductName());
      // Check if the current CVConfig needs to be cleaned up.
      if (elkCVConfigCountQuery.count() > 1) {

 I am referring to this. Here we are querying for the older cv config class with id, it should be 1. Am I missing something here?

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44129#-NPdALIA2mRUlmRZ-6-f:-NPpnel5CTYYuF-YS5_I:bg60fog) ([raw file](https://github.com/harness/harness-core/blob/97bdea4ebf3b4f3fda274dbdf974692f545e0c54/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateELKCVConfigToV2.java#L36)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

      Query<ELKCVConfig> elkCVConfigCountQuery = hPersistence.createQuery(ELKCVConfig.class)
                                                     .disableValidation()
                                                     .filter("identifier", cvConfig.getFullyQualifiedIdentifier())
                                                     .filter("productName", cvConfig.getProductName());
      // Check if the current CVConfig needs to be cleaned up.
      if (elkCVConfigCountQuery.count() > 1) {

 I am referring to this. Here we are querying for the older cv config class with id, it should be 1. Am I missing something here?
</blockquote></details>

discussed and updated the changes

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44129)* status: :shipit: complete! ✓

**Pull request merged**
