### PR TITLE
fix: [CDS-41416]: skip manifest rendering for

### PR DESCRIPTION
**Pull request by achyuth-harness**
K8s Apply Step in NG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36082)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36082)

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 1 of 1 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36082)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2398 at r3](https://reviewable.io/reviews/harness/harness-core/36082#-N8wKXtx4qwF6wSD5wBd:-N8wKXtx4qwF6wSD5wBe:b8eoc3g) ([raw file](https://github.com/harness/harness-core/blob/9e615db75335d723c632cf4d54751362e485f292/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2398)):*
> ```Java
>       case K8S_MANIFEST:
>         List<FileData> manifestFiles = readFilesFromDirectory(manifestFilesDirectory, filesList, executionLogCallback);
>         if (skipRendering) {
> ```

Shouldn't be skipRendering applied to all types of manifest?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36082)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2398 at r3](https://reviewable.io/reviews/harness/harness-core/36082#-N8wKXtx4qwF6wSD5wBd:-N91WAHi-VmXx6I9mzxI:b-tm2h7q) ([raw file](https://github.com/harness/harness-core/blob/9e615db75335d723c632cf4d54751362e485f292/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2398)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't be skipRendering applied to all types of manifest?
</blockquote></details>

as discussed offline, we will have a separate ticket for this

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36082)* status: :shipit: complete! ✓

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36082)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger codebasehash

**Pull request merged**
