### PR TITLE
feat: [PL-40139]: Remove the service name prefix from DW metrics

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

In this PR the service name prefix is removed from all DW metrics and instead the service name is added as a label. This allows us to create a single dashboard for all the DW services.

Tested it locally.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50834)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50834#-:-N_qfQtw2OhPIt0IajnY:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50834)* status: 13 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/aggregator/AggregatorStackDriverMetricsPublisherImpl.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/50834#-N_rFxWt4ErxFS0K_OaL:-N_rFxWu-xWsF5umtvX5:bd5el3z) ([raw file](https://github.com/harness/harness-core/blob/f2c3b92aca6533f4024b90802e35a029c6297590/access-control/service/src/main/java/io/harness/accesscontrol/aggregator/AggregatorStackDriverMetricsPublisherImpl.java#L31)):*
> ```Java
>   private final String namespace = System.getenv("NAMESPACE");
>   private final String containerName = System.getenv("CONTAINER_NAME");
>   private final String serviceName = "serviceName";
> ```

How will this translate to access control service?

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50834)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/aggregator/AggregatorStackDriverMetricsPublisherImpl.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/50834#-N_rFxWt4ErxFS0K_OaL:-N_tUBX43qioBaK_C_bj:b8hekvw) ([raw file](https://github.com/harness/harness-core/blob/f2c3b92aca6533f4024b90802e35a029c6297590/access-control/service/src/main/java/io/harness/accesscontrol/aggregator/AggregatorStackDriverMetricsPublisherImpl.java#L31)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

How will this translate to access control service?
</blockquote></details>

Good catch, updated it. Thanks

**Review by raghuAtWings — APPROVED** [review]

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50834#-:-Na6293NBBVuscj1wBbi:bnfp4nl)* status: 1 file(s) to review.

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger ut7

**Pull request merged**
