### PR TITLE
feat: [PLG-1684]: Created API to transition accounts between sales le…

### PR DESCRIPTION
**Pull request by allenthom**
API to update Account to be sales-led or product-led

## Checklist
- [ X] I've documented the changes in the PR description.
- [ X] I've tested this change either in PR or local environment.
- [ X] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39472)

### CODE REVIEW

**Comment by allenthom** [comment]
trigger messagecheck

**Comment by allenthom** [comment]
trigger ft2

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39472)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39472)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/39472#-NFsr-o96J6cxKmj4gkD:-NFsr-oA4M9ZpPV-TwYn:b-hms0o5) ([raw file](https://github.com/harness/harness-core/blob/fd930b180fa5546354fd3d50da3332ca175a6ced/400-rest/src/main/java/software/wings/resources/AccountResource.java#L290)):*
> ```Java
>   public RestResponse<Boolean> updateIsProductLed(@PathParam("accountId") @NotEmpty String accountId,
>       @QueryParam("isProductLed") @DefaultValue("false") boolean isProductLed) {
>     return new RestResponse<>(accountService.updateIsProductLed(accountId, isProductLed));
> ```

Since this API calls admin account resource, then we need to verify if this user is Harness Support user

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39472)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by allenthom** [comment]
trigger ti0

**Comment by allenthom** [comment]
trigger ti1

**Review by hekimoglu010 — APPROVED** [review]

**Review by Xin-Harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39472)* status: 1 file(s) to review.

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39472)* status: :shipit: complete! ✓

**Pull request merged**
