### PR TITLE
feat: [CODE-1186]: Pipeline Service changes for gitx support with harness code

### PR DESCRIPTION
**Pull request by deepak-harness**
## Describe your changes
Since connector ref can be null for the internal harness code usecase:
1. remove any null check
2. Added default file path for the harness code
3. change default to empty connector ref(Since protobuf can't be null we used empty string). May be we will change it to default in scm for default connector dto 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger uts

**Review by abhinav-harness — DISMISSED** [review]

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 5 file(s) to review. 1 change requests. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9iIWXEPk2l6XN45Yw:-Nl9iIWXEPk2l6XN45Yx:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java#L62)):*
> ```Java
>             format("Connector of given type : %s isn't supported", scmConnector.getConnectorType()));
>     }
>   }
> ```

line spacing missing

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9iw0DAvmcN38UBcIz:-Nl9jIWbEujmB39kbWmu:b33ttgw) ([raw file](https://github.com/harness/harness-core/blob/0fc83d263e24bb515028ae7f81262b244cfd53b1/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L156)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do you think instead of considering null as default value for harness connector ref, we should define a keyword for such cases? may be something like : __default__harness_connector__. Now, we would just rely on this ref for all references to default Harness code connector, instead of relying on null.
</blockquote></details>

"__default__harness__connector__" this is what I wrote, reviewable just beautified it.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 5 file(s) to review. 1 change requests. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9jUQ4-AVZ8Gt_xcpt:-Nl9jUQ4-AVZ8Gt_xcpu:b-wrm50m) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L65)):*
> ```Java
>     String connectorRef =
>         getRequestParamFromContext(GitSyncApiConstants.CONNECTOR_REF, pathParameters, queryParameters);
>     if (DEFAULT.equals(connectorRef)) {
> ```

we shouldn't touch this file. This is an old legacy file, don't know what may break.

**Review by deepak-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9iPbn6Cn0_a_xtvLw:-NlMqSvt90Ft0tF0vTSm:bsqhdpq) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java#L57)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we also move this method to GitClientHelper just like other getComplete.. methods for different git providers. Then anyone wants to use, it will be used from a central place.
</blockquote></details>

I tried that first. But the ScmConnector and HarnessConnectorDTO are part of 954 module while git helper is part of 960. Importing the lower module will be an issue and moving these connector to upper level(I don't even know where it will fit) will lead to lot of changes.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9iw0DAvmcN38UBcIz:-NlMqvQCETgQvA9M0RE-:b-mup7c2) ([raw file](https://github.com/harness/harness-core/blob/0fc83d263e24bb515028ae7f81262b244cfd53b1/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L156)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

"__default__harness__connector__" this is what I wrote, reviewable just beautified it.
</blockquote></details>

We had a discussion also about this. Here is the reasoning behind the null:
Since many of the SCM APIs are customer facing like list repo, list branches, raise PR etc and customer need to provide the connector ref. Keeping it null/empty string gives an impression that Harness code is default behaviour here in contrast having some random string which makes it an after thought. Also, having default_harness_connector will make it as reserved keyword for the connector refs. 
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9jUQ4-AVZ8Gt_xcpt:-NlMrj6U9aainyhKSv-U:b-vir77z) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't touch this file. This is an old legacy file, don't know what may break.
</blockquote></details>

Can you suggest another way of setting the connector ref as empty in case it is not set in contrast to default. Otherwise making changes to multiple places to send empty string to scm in case it is set as default makes for more error prone.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9iPbn6Cn0_a_xtvLw:-NlPuEp9CTlyRvxiGIwd:b-oi4u0i) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java#L57)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

I tried that first. But the ScmConnector and HarnessConnectorDTO are part of 954 module while git helper is part of 960. Importing the lower module will be an issue and moving these connector to upper level(I don't even know where it will fit) will lead to lot of changes.
</blockquote></details>

We should see how its being done for other connector use-cases. If they are possible to do, so should be this one. It has to be central to avoid any issues later on. 
If still unresolved, we can jump on call and check together.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9iw0DAvmcN38UBcIz:-NlPvT1o0b6t5pCQ9-_Q:b5e0x9v) ([raw file](https://github.com/harness/harness-core/blob/0fc83d263e24bb515028ae7f81262b244cfd53b1/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L156)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We had a discussion also about this. Here is the reasoning behind the null:
Since many of the SCM APIs are customer facing like list repo, list branches, raise PR etc and customer need to provide the connector ref. Keeping it null/empty string gives an impression that Harness code is default behaviour here in contrast having some random string which makes it an after thought. Also, having default_harness_connector will make it as reserved keyword for the connector refs.
</blockquote></details>

So, we have currently gitx settings which replaces null with default connector. So, if someone wants to use default connector (which they themselves set in some gitx setting), then they just don't supply the field and automatically the connector is picked from the setting. The harness code connector will start to fail in such cases.
Also, I'm particularly not very comfortable to default it to harness code connector. IMO, we should explore some reserved keyword pattern if required, but it should be definite in nature whenever someone wants to use Harness Code Connector. I understand the counter points to it, but somehow still want to see if something can be done here.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9jUQ4-AVZ8Gt_xcpt:-NlPw25H2m3lp6EU2LXH:bwta5aw) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L65)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Can you suggest another way of setting the connector ref as empty in case it is not set in contrast to default. Otherwise making changes to multiple places to send empty string to scm in case it is set as default makes for more error prone.
</blockquote></details>

Don't set it empty. Simple check for Null or DEFAULT string wherever you need to handle.
Also coming back to your earlier point around issues having "reserved" keyword for harness code connector. If you see, here we used to put "__default__" as param value whenever empty param was passed, so effectively this became a reserved keyword for us. I'm not saying that this is the best way to do things, but choosing a particular unique complex keyword should be possible to handle our use-case. We haven't faced any concerns around using '__default__' also till date, its been there since like 2-3 years or so.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56516)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/56516#-Nl9jUQ4-AVZ8Gt_xcpt:-NlPwdUIC_FWydstrDHI:buplsuu) ([raw file](https://github.com/harness/harness-core/blob/4bec0b10614ae16ce18ea363443c45b16ce9cd48/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Don't set it empty. Simple check for Null or DEFAULT string wherever you need to handle.
Also coming back to your earlier point around issues having "reserved" keyword for harness code connector. If you see, here we used to put "__default__" as param value whenever empty param was passed, so effectively this became a reserved keyword for us. I'm not saying that this is the best way to do things, but choosing a particular unique complex keyword should be possible to handle our use-case. We haven't faced any concerns around using '__default__' also till date, its been there since like 2-3 years or so.
</blockquote></details>

'_ _ default _ _' *

**Pull request closed without merging**
