### PR TITLE
feat: [PL-25267]: integrated method to fetch complete file url

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Method to fetch complete fileUrl for github, bitbucket cloud and bitbucketServer
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33855)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_vzFh2ODfy3nN_N_k:-N3_vzFi6DKOp8f5GC7S:b-j8swd3) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L53)):*
> ```Java
> 
>   public String getFileUrl(Scope scope, String connectorRef, String repoName, String branchName, String filePath) {
>     ScmConnector scmConnector = gitSyncConnectorHelper.getScmConnectorForGivenRepo(
> ```

don't we have the scm connector already with us where we want to fetch the file path?

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/utils/FilePathUtils.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_wVs3E9AJr2-gXx0e:-N3_wVs48XNvQ6iU2weN:b-es3plb) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/980-commons/src/main/java/io/harness/utils/FilePathUtils.java#L70)):*
> ```Java
> 
>   public static String removeStartingAndEndingSlash(String path) {
>     if (isEmpty(path)) {
> ```

if path="", then its a valid use-case. We should return "".

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_wwd85oX9VWvITRo9:-N3_wwd85oX9VWvITRoA:bq0qw2x) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java#L17)):*
> ```Java
>   public static void validateGetFileUrlParams(GitConnectionType connectionType, String branchName, String filePath) {
>     if (GitConnectionType.ACCOUNT.equals(connectionType)) {
>       throw new InvalidRequestException("Could not create file path with account type connector.");
> ```

sorry, didn't get this part, can you please elaborate

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xDK8BYj8swEvikzI:-N3_xDK8BYj8swEvikzJ:bgdw38o) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L151)):*
> ```Java
>     String orgName = GitClientHelper.getGitOwner(url, true);
>     String[] parts = new String[0];
>     if (orgName.equals("scm")) {
> ```

please declare constants

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xQfu-nTOLzXLdOH8:-N3_xQfu-nTOLzXLdOH9:b-oo2qgb) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L161)):*
> ```Java
>       return GitRepositoryDTO.builder().org(parts[0]).build();
>     } else {
>       throw new InvalidRequestException("Bitbucket server repoUrl is not valid.");
> ```

whats the use-case when we land here? The error doesn't convey it exactly

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33855)* status: 13 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_vzFh2ODfy3nN_N_k:-N3cICDC7p49q2rIjeZV:bjtbva1) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitFilePathHelper.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

don't we have the scm connector already with us where we want to fetch the file path?
</blockquote></details>

We will call this methos from HarnessToGitHelperSvc, there we only have connectorRef not scmConnector.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xQfu-nTOLzXLdOH8:-N3cIXG01VrWFr8hPvIx:b5e7kzj) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L161)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the use-case when we land here? The error doesn't convey it exactly
</blockquote></details>

if somehow the repourl is wrong, then we will not able to find out org and repoName, that's why the error is saying repoUrl is inavalid, we can call thi method for diff use cases.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xMf98-GkPoCEQ3zP:-N3cIo8rCeBnlVzYfYlS:bsr8w11) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L171)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if we failed, then we should throw an exception from here right?
</blockquote></details>

yes, we can, but I thought in this flow, we should nit throw any errors.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_wwd85oX9VWvITRo9:-N3cJCUE8gdoMLgbvAWp:bvdpqbn) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

sorry, didn't get this part, can you please elaborate
</blockquote></details>

With account type connector, we do not have repoName with us, then how will we create a fileUrl without repoName?

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33855#-:-N3cQ5-Z-__MfXTKV4dN:bnfp4nl)* status: 13 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xQfu-nTOLzXLdOH8:-N3cQlwX3j2CwupDWNWN:b5eob2n) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L161)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

if somehow the repourl is wrong, then we will not able to find out org and repoName, that's why the error is saying repoUrl is inavalid, we can call thi method for diff use cases.
</blockquote></details>

Got it. Can we just make it more user friendly : "Provided bitbucket server repository URL isn't valid" or something even better, just bit more language and not using "repoUrl"

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xMf98-GkPoCEQ3zP:-N3cR1bsD7DIViwo21ii:b-3ub9hd) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L171)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

yes, we can, but I thought in this flow, we should nit throw any errors.
</blockquote></details>

But shouldn't we otherwise it will return a wrong url, right?

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_wwd85oX9VWvITRo9:-N3cRCi02xrTc7vTu1xV:b-uvl5ns) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java#L17)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

With account type connector, we do not have repoName with us, then how will we create a fileUrl without repoName?
</blockquote></details>

repo name should be coming as input to us, right? We don't have an option to not return a url. We always have to return url.

Just like in connectionUrl use-case, we put a check if input repo doesn't match for repo in repo-level connector, then we throw error. Same we should do here.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33855)* status: 13 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_wwd85oX9VWvITRo9:-N3cS6LK2w-gPw3ANdBQ:bijnjni) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/utils/ScmConnectorHelper.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

repo name should be coming as input to us, right? We don't have an option to not return a url. We always have to return url.

Just like in connectionUrl use-case, we put a check if input repo doesn't match for repo in repo-level connector, then we throw error. Same we should do here.
</blockquote></details>

That check is already there, again it';s a generic method, which should not depend on or use case, that we always have repoNmae, therefore just a check has been added for precaution.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33855)* status: 13 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xDK8BYj8swEvikzI:-N3cTkbO1YkJnPQhqmOt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L151)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please declare constants
</blockquote></details>

Done.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xQfu-nTOLzXLdOH8:-N3cTlaD41PxHXoBm5wd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L161)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Got it. Can we just make it more user friendly : "Provided bitbucket server repository URL isn't valid" or something even better, just bit more language and not using "repoUrl"
</blockquote></details>

Done.
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_xMf98-GkPoCEQ3zP:-N3cTmD6DwTfvEQhl2Kn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L171)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

But shouldn't we otherwise it will return a wrong url, right?
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/utils/FilePathUtils.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/33855#-N3_wVs3E9AJr2-gXx0e:-N3cTn6fCnWk2QKXPD9v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fa750d83275a8d57668f2c2b8d453ac04668c1f/980-commons/src/main/java/io/harness/utils/FilePathUtils.java#L70)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if path="", then its a valid use-case. We should return "".
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 13 of 74 files at r2, 6 of 9 files at r3, 59 of 59 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33855#-:-N3czEkK53bZXAKJRPW4:bnfp4nl)* status: 83 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by bhavya181** [comment]
Has opened another pr for same changes https://github.com/harness/harness-core/pull/33971

**Pull request closed without merging**
