### PR TITLE
fix: [CDS-36613]: User group expression inside pipeline approval step

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33009)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger pmd

**Comment by Fernando-Dourado** [comment]
trigger codeformat

**Comment by Fernando-Dourado** [comment]
trigger checkstyle

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33009)* status: Some of the checks are too old.

**Pull request merged**
