### PR TITLE
fix: [CDS-37284]: Adding ServiceV2 plancreator

### PR DESCRIPTION
**Pull request by archit-harness**
PR contains following changes - 

- Creating serviceSection plan node and its corresponding plan creator changes
- Creating service step v2 plan node and its corresponding plan creator changes

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 14 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorV2.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33498#-N2pw8egCSfNZ4XbtBVn:-N2pw8egCSfNZ4XbtBVo:b-fdhrqr) ([raw file](https://github.com/harness/harness-core/blob/332a1435ea8094086bd1a77d262b24a6fcf6f20c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorV2.java#L51)):*
> ```Java
> public class ServicePlanCreatorV2 extends ChildrenPlanCreator<NGServiceV2InfoConfig> {
>   @Inject KryoSerializer kryoSerializer;
>   @Inject EnforcementValidator enforcementValidator;
> ```

nit: these can be private
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorV2.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/33498#-N2pwC81EucSL0ttGaoi:-N2pwC81EucSL0ttGaoj:b-lcl23z) ([raw file](https://github.com/harness/harness-core/blob/332a1435ea8094086bd1a77d262b24a6fcf6f20c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorV2.java#L56)):*
> ```Java
>   public LinkedHashMap<String, PlanCreationResponse> createPlanForChildrenNodes(
>       PlanCreationContext ctx, NGServiceV2InfoConfig config) {
>     LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap = new LinkedHashMap<>();
> ```

nit: this can be final

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 16 of 18 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 18 files at r1, 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/33498#-N2uwMzY6Pkd6BE4wVEz:-N2uwMzY6Pkd6BE4wVF-:b-2to05g) ([raw file](https://github.com/harness/harness-core/blob/9a5936d13810c57838401a10c997ef204028d429/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L96)):*
> ```Java
>   public VisitableChildren getChildrenToWalk() {
>     List<VisitableChild> children = new ArrayList<>();
>     children.add(VisitableChild.builder().value(serviceConfig).fieldName("serviceConfig").build());
> ```

serviceConfig == null, we will handle later ?

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33498)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorV2.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/33498#-N2pwKNAA5RTHn1HINRF:-N2pwKNAA5RTHn1HINRG:b-d2tip8) ([raw file](https://github.com/harness/harness-core/blob/332a1435ea8094086bd1a77d262b24a6fcf6f20c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorV2.java#L64)):*
> ```Java
> 
>     YamlField serviceField = ctx.getCurrentField();
>     YamlField serviceDefField = serviceField.getNode().getField(YamlTypes.SERVICE_DEFINITION);
> ```

just to confirm, the service ref has been replaced by the service entity using yaml updates, by this point ?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/33498#-N2px0asC44sO3HukHTK:-N2px0asC44sO3HukHTL:b-wptc26) ([raw file](https://github.com/harness/harness-core/blob/332a1435ea8094086bd1a77d262b24a6fcf6f20c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L100)):*
> ```Java
>       children.add(VisitableChild.builder().value(service).fieldName("service").build());
>     }
>     children.add(VisitableChild.builder().value(infrastructure).fieldName("infrastructure").build());
> ```

infrastructure == null, we will handle later ?

**Pull request merged**
