### PR TITLE
fix: [CDS-38676]: fix instances with wrong infra mapping

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36760)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36760)

**Comment by vikyathharekal** [comment]
trigger ti0, ti2, ti3

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36760)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/mappers/InstanceMapper.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/36760#-NAId0924ZhjAhhvy1vQ:-NAId0924ZhjAhhvy1vR:b-xg5kyb) ([raw file](https://github.com/harness/harness-core/blob/9837db2c447bcda886ddfb1ceec2086a2d100d7f/126-instance/src/main/java/io/harness/mappers/InstanceMapper.java#L63)):*
> ```Java
>   public Instance toEntity(InstanceDTO instanceDTO) {
>     return Instance.builder()
>         .id(instanceDTO.getUuid())
> ```

what if the uuid is not set in `instanceDTO`.
Check the flow where we are creating a new instance entity, validate if the mongo framework is still generating a new uuid for the document

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36760)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/mappers/InstanceMapper.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/36760#-NAId0924ZhjAhhvy1vQ:-NAIlYU7CnSydSMjJ-23:bwyaxjr) ([raw file](https://github.com/harness/harness-core/blob/9837db2c447bcda886ddfb1ceec2086a2d100d7f/126-instance/src/main/java/io/harness/mappers/InstanceMapper.java#L63)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

what if the uuid is not set in `instanceDTO`.
Check the flow where we are creating a new instance entity, validate if the mongo framework is still generating a new uuid for the document
</blockquote></details>

Verified locally. Mongo has generated UUID for all documents.

**Review by shubham-in10se — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36760)* status: :shipit: complete! ✓

**Pull request merged**
