### PR TITLE
techdebt: [PL-29872]: Break cycle between text/resolver and expression

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes
Broke cycle between 980-commons expression and text resolver. Primary change is to create a expression/common folder with a couple of files moved from expression folder. Also a few constants have been extracted out from EngineExpressionEvaluator.java which were leading to cycles.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)

### CODE REVIEW

**Review by mdmilic — APPROVED** [review]
> Reviewed 40 of 40 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: 40 file(s) to review. 1 of 2 approvals obtained.

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: 40 file(s) to review. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/40781#-NI3eDjhEm1tJudhbqHl:-NI3eDjhEm1tJudhbqHm:boegp7n) ([raw file](https://github.com/harness/harness-core/blob/a0c872f2f55026f9428f26239f31b4939c4dcc62/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L8)):*
> ```Java
>  */
> 
> package io.harness.text.resolver;
> ```

Since StringReplacer.java was the only file in text folder outside the resolver sub-folder, we can also get away with the resolver sub-folder and have all 3 files within text folder as well ?

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 39 of 40 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: 1 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 39 of 40 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: :shipit: complete! ✓

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: 1. unresolved discussions. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/40781#-NI3eDjhEm1tJudhbqHl:-NI6E8uE-Uoxl_uWzPo0:bnh2b26) ([raw file](https://github.com/harness/harness-core/blob/a0c872f2f55026f9428f26239f31b4939c4dcc62/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L8)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Since StringReplacer.java was the only file in text folder outside the resolver sub-folder, we can also get away with the resolver sub-folder and have all 3 files within text folder as well ?
</blockquote></details>

I wanted to do that too - but moving other files out of the package name was leading to quite a few changes - so I just took the shortcut

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 39 of 40 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: 1. unresolved discussions.

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: 1. unresolved discussions.

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed 39 of 40 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40781)* status: :shipit: complete! ✓

**Pull request merged**
