### PR TITLE
fix: [PL-22152]: fix for pr creation while using proj level connnetor

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java, line 177 at r1](https://reviewable.io/reviews/harness/harness-core/30300#-MuRWhIL5bSTIQSXv2--:-MuRWnl68IHfZHBXNER0:b-ofmhh3) ([raw file](https://github.com/harness/harness-core/blob/cae0dec0b5ab6d040ab22bd89faf5fd25e2fdf5f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L177)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

But there can be more than one yamlgitconfigs 
</blockquote></details>

Oh there will be only one for a repo

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by bhavya181** [comment]
https://harness.atlassian.net/browse/PL-22154 This issue is also fixed in this pr.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java, line 192 at r3](https://reviewable.io/reviews/harness/harness-core/30300#-MuVl5w55i5O4wi3ZFGC:-MuVl5w55i5O4wi3ZFGD:byk9dep) ([raw file](https://github.com/harness/harness-core/blob/1472985200a3d71701807a7c37b011e04c869a87/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L192)):*
> ```Java
>   }
> 
>   public Optional<ConnectorResponseDTO> getConnectorFromDefaultBranchElseFromGitBranch(String accountId,
> ```

this is the same logic that @deepakpatankar wrote yesterday. Please move this to some util and commonly use it everywhere.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java, line 213 at r3](https://reviewable.io/reviews/harness/harness-core/30300#-MuVm3i_AkRqpREOsTXD:-MuVm3ia30jYCXnUhqSl:b-f6xqto) ([raw file](https://github.com/harness/harness-core/blob/1472985200a3d71701807a7c37b011e04c869a87/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L213)):*
> ```Java
>   private Optional<ConnectorResponseDTO> getConnectorFromRepoBranch(String accountId, String orgIdentifier,
>       String projectIdentifier, String identifier, String connectorRepo, String connectorBranch) {
>     GitEntityInfo oldGitEntityInfo = GitContextHelper.getGitEntityInfo();
> ```

I see lot of places that connectorRepo and connectorBranch is passed as null. So, lets put a check that if one of them is null, then we just return empty directly. We don't need to do any further ops here.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java, line 192 at r3](https://reviewable.io/reviews/harness/harness-core/30300#-MuVl5w55i5O4wi3ZFGC:-MuVnR1rA6bfCeZ19Jlf:bwcznfv) ([raw file](https://github.com/harness/harness-core/blob/1472985200a3d71701807a7c37b011e04c869a87/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L192)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is the same logic that @deepakpatankar wrote yesterday. Please move this to some util and commonly use it everywhere.
</blockquote></details>

It's a helper class only.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java, line 213 at r3](https://reviewable.io/reviews/harness/harness-core/30300#-MuVm3i_AkRqpREOsTXD:-MuVqBcf3kbXNKu4aMKg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1472985200a3d71701807a7c37b011e04c869a87/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L213)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see lot of places that connectorRepo and connectorBranch is passed as null. So, lets put a check that if one of them is null, then we just return empty directly. We don't need to do any further ops here.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: 1 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30300)* status: :shipit: complete! ✓

**Pull request merged**
