### PR TITLE
fix: [PL-43800]: Add a config to enable/disable account deletion job

### PR DESCRIPTION
**Pull request by sahibaHarness**
## Describe your changes
Disable AccountDeletionJob in CG Manager

Tested for:
The job is no longer getting registered with the default config
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57147)

### CODE REVIEW

**Comment by sahibaHarness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57147)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 827 at r1](https://reviewable.io/reviews/harness/harness-core/57147#-Nmizj0s18MsM_4hliyb:-Nmizj0s18MsM_4hliyc:b-50a1ib) ([raw file](https://github.com/harness/harness-core/blob/8454da1081b8dda0ca0c7445c89066ccf9a25980/360-cg-manager/config.yml#L827)):*
> ```YAML
> maxAccountsToDeleteInParallel: 6
> runAccountDeletionOnWeekdays: ${RUN_ACCOUNT_DELETION_ON_WEEKDAYS:-false}
> disableAccountDeletionJobRegister: ${DISABLE_ACCOUNT_DELETION_JOB_REGISTER:-false}
> ```

default value should be true.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57147)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 827 at r1](https://reviewable.io/reviews/harness/harness-core/57147#-Nmizj0s18MsM_4hliyb:-Nmj-4yt94c8NBX5F3Ev:b-36r0fp) ([raw file](https://github.com/harness/harness-core/blob/8454da1081b8dda0ca0c7445c89066ccf9a25980/360-cg-manager/config.yml#L827)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

default value should be true.
</blockquote></details>

Lets name it enable job.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57147)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/harness/harness-core/57147#-Nmj02x41XcxK1flw3qT):*
Rename in PR title and description.
___
*[`360-cg-manager/config.yml` line 827 at r1](https://reviewable.io/reviews/harness/harness-core/57147#-Nmizj0s18MsM_4hliyb:-Nmj08mj5NC_HT5YcrbB:b-71kwl5) ([raw file](https://github.com/harness/harness-core/blob/8454da1081b8dda0ca0c7445c89066ccf9a25980/360-cg-manager/config.yml#L827)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Lets name it enable job.
</blockquote></details>

Change  enableAccountDeletionJobRegister to enableAccountDeletionJob

**Review by shashank-harness — APPROVED** [review]
LGTM

**Comment by sahibaHarness** [comment]
trigger uts

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57147)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57147)* status: 3 file(s) to review.

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Comment by sahibaHarness** [comment]
trigger ut8

**Comment by sahibaHarness** [comment]
trigger ut7

**Pull request merged**
