### PR TITLE
techdebt: [CDS-45935]: Add Unit Tests for Gitops Service Dashboard

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
Unit Tests for Gitops Service Dashboard

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40958)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Review by manavjot-harness — APPROVED** [review]

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40958)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/40958#-NIDdrpE9gZGGduhV4r_:-NIDdrpE9gZGGduhV4ra:b-wx5q3e) ([raw file](https://github.com/harness/harness-core/blob/6b3863b08b5c98b02f398b5f7e0f07b336d15ed2/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L104)):*
> ```Java
> 
>   private List<GitOpsInstance> prepareInstanceSync(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, List<GitOpsInstanceRequest> gitOpsInstanceRequestList) {
> ```

Can we have this method inside GitopsInstanceSyncServiceImpl?

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40958)* status: 4 file(s) to review.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40958)* status: 4 file(s) to review. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/40958#-NIDdrpE9gZGGduhV4r_:-NIDfJN9C_2oRuAlGsrh:b-j8glzl) ([raw file](https://github.com/harness/harness-core/blob/6b3863b08b5c98b02f398b5f7e0f07b336d15ed2/120-ng-manager/src/main/java/io/harness/ng/instancesync/resources/GitOpsInstanceSyncResource.java#L104)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Agree, we should move it there. 
</blockquote></details>

sure, will address this in a follow-up PR

**Pull request merged**
