### PR TITLE
fix: [PL-29425]: Error code for invalid/expired token should be Forbidden (401)

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
Currently error if an expired/invalid token is used to make an API call, the call fails will error code of bad request i.e. 400. In case of expired/invalid token the error code should be 401.
NOTE: With the change in this PR the error message will get changed to `Token is not valid.` or `Token expired.`. This is because for error code `INVALID_TOKEN` or `EXPIRED_TOKEN` the error message is static.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39425)

### CODE REVIEW

**Review by rathodmeetsatish — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39425)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/39425#-NFsKbOv5_P-Xda6XdW0:-NFsKbOv5_P-Xda6XdW1:bw4lwca) ([raw file](https://github.com/harness/harness-core/blob/c6d46601da492301f01c66f04514bf5dd0634dfc/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L215)):*
> ```Java
>     if (!(isOldApiKeyToken(splitToken) || isNewApiKeyToken(splitToken))) {
>       String message = "Token length not matching for API token";
>       log.warn(message);
> ```

now that we are logging as error in logAndThrowTokenException logging it as warning wont be necessary
similarly in other places

**Review by shashank-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39425)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39425)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/39425#-NFsKbOv5_P-Xda6XdW0:-NFw-YdJ0c_SkHJ4PgMU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c6d46601da492301f01c66f04514bf5dd0634dfc/965-api-key-filter/src/main/java/io/harness/security/NextGenAuthenticationFilter.java#L215)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

now that we are logging as error in logAndThrowTokenException logging it as warning wont be necessary
similarly in other places
</blockquote></details>

Done.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39425)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39425#-:-NFwKl3bEfiqJ2b9FdkZ:bnfp4nl)* status: :shipit: complete! ✓

**Comment by nishantsaini20** [comment]
trigger codeformat

**Comment by nishantsaini20** [comment]
trigger ti0

**Comment by nishantsaini20** [comment]
trigger ti1

**Comment by nishantsaini20** [comment]
trigger ti2

**Comment by nishantsaini20** [comment]
trigger ti3

**Comment by nishantsaini20** [comment]
trigger ti4

**Pull request merged**
