### PR TITLE
fix: [DEL-3712]: Fix graphql for listing delegate heartbeat as String instead of Integer

### PR DESCRIPTION
**Pull request by Xin-Harness**
…stead of integer

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32107)

### CODE REVIEW

**Comment by Xin-Harness** [comment]
trigger messagecheck

**Comment by Xin-Harness** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
*[400-rest/src/main/resources/graphql/public/delegateMutatation.graphql, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/32107#-N-1eo7y6Lbi6CJjamDs:-N-1eo7y6Lbi6CJjamDt:bmilvz8) ([raw file](https://github.com/harness/harness-core/blob/61076bb6cfb26ab7b1be151f846bf87fcf2729cd/400-rest/src/main/resources/graphql/public/delegateMutatation.graphql#L81)):*
> ```GraphQL
>   status: String
>   lastHeartBeat: Long @deprecated(reason: "Use lastHeartbeat.")
>   lastHeartbeat: Int
> ```

Correct format is DateTime, if not long. 
lastHeartbeat: DateTime

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32107)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/graphql/public/delegateMutatation.graphql, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/32107#-N-1eo7y6Lbi6CJjamDs:-N-426bl-K2w1XikAY6D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/61076bb6cfb26ab7b1be151f846bf87fcf2729cd/400-rest/src/main/resources/graphql/public/delegateMutatation.graphql#L81)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Correct format is DateTime, if not long. 
lastHeartbeat: DateTime
</blockquote></details>

Done.

**Comment by Xin-Harness** [comment]
Before the change:
image
After the change:
image

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32107)* status: 1. unresolved discussions.

**Pull request merged**
