### PR TITLE
[feat]: [PL-24872]: Improving Unit Tests for ADO

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32636)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32636)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/32636#-N0l0w699Mcyb8-HdxGC:-N0l0w6A12rLx88p5x3e:bt4fmoc) ([raw file](https://github.com/harness/harness-core/blob/c342b6d644894fb784ced64452843c80d06d08a9/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L83)):*
> ```Java
>       default:
>         throw new UnknownEnumTypeException(
>             "AzureRepo Auth Type", gitAuthType == null ? null : gitAuthType.getDisplayName());
> ```

why did you remove this null check ? What happens if gitAuthType is null

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32636)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32636)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by ashishsanodia-harness — DISMISSED** [review]

**Review by rathodmeetsatish — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32636)* status: 6 file(s) to review. 1 change requests. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/adapter/AzureRepoToGitMapper.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/32636#-N12D8eP7G5-dtYTIVyi:-N12D8eP7G5-dtYTIVyj:b59hbgf) ([raw file](https://github.com/harness/harness-core/blob/6a27f23e8a0e3f1c4bddc4019861fa9397e345da/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/adapter/AzureRepoToGitMapper.java#L33)):*
> ```Java
>     final String validationRepo = azureRepoConnectorDTO.getValidationRepo();
>     if (authType == null) {
>       throw new InvalidRequestException("Azure Repo DTO Auth Type value is null");
> ```

change the message remove null from the message as you have done for others

**Pull request closed without merging**
