### PR TITLE
[feat]: [PIE-6382]: Moving pipeline related settings under the category PMS

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

 Moving pipeline related settings under the category PMS from CORE.
Also added the migration to update the setting overrides as well.

Impact: Settings will be updated. So need to check that all settings are untouched except from `mandate_webhook_secrets_for_github_triggers` and `mandate_custom_webhook_authorization`. Also these 2 settings have only category update.

Testing: Tested in local that settingsConfiguration collection entries updated on the ng-manager start. And migration updated the entries for the above two setting identifiers.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42294)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42294)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NGWebhookMendateSettingsCategoryUpdateMigration.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/42294#-NL487kO62je36hrX1kc:-NL487kP4C89cZLyEz41:b-pxuntd) ([raw file](https://github.com/harness/harness-core/blob/78fac1fb1e6b1fbcffb065fd0bc4eee4177fcfac/120-ng-manager/src/main/java/io/harness/ng/core/migration/NGWebhookMendateSettingsCategoryUpdateMigration.java#L23)):*
> ```Java
>   public void migrate() {
>     List<String> settingIdentifiers =
>         List.of("mandate_webhook_secrets_for_github_triggers", "mandate_custom_webhook_authorization");
> ```

Can you wrap this try catch, so if any exception comes, we can search for that log
___
*[`120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreMigrationDetails.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/42294#-NL48-Vo9vrYPdxVyGTo:-NL48-Vo9vrYPdxVyGTp:b7fwl28) ([raw file](https://github.com/harness/harness-core/blob/78fac1fb1e6b1fbcffb065fd0bc4eee4177fcfac/120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreMigrationDetails.java#L54)):*
> ```Java
>         .add(Pair.of(9, AddOnDelegateFieldToCustomSecretManagerConnector.class))
>         .add(Pair.of(10, DisableBuiltInHarnessSMSettingsMigration.class))
>         .add(Pair.of(11, NGWebhookMendateSettingsCategoryUpdateMigration.class))
> ```

Add this to NGCoreBackgroundMigrationDetails as background true should be fine as we don't want app startup to wait for this migration

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42294)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NGWebhookMendateSettingsCategoryUpdateMigration.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/42294#-NL487kO62je36hrX1kc:-NL4_S7k18qlb0W5sz2V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/78fac1fb1e6b1fbcffb065fd0bc4eee4177fcfac/120-ng-manager/src/main/java/io/harness/ng/core/migration/NGWebhookMendateSettingsCategoryUpdateMigration.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you wrap this try catch, so if any exception comes, we can search for that log
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreMigrationDetails.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/42294#-NL48-Vo9vrYPdxVyGTo:-NL4_TfX63gFEHO-Q98G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/78fac1fb1e6b1fbcffb065fd0bc4eee4177fcfac/120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreMigrationDetails.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add this to NGCoreBackgroundMigrationDetails as background true should be fine as we don't want app startup to wait for this migration
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42294)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42294)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger codeformat

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42294)* status: :shipit: complete! ✓

**Pull request merged**
