### PR TITLE
feat: [PLG-2110]: Implement CI Build Credit get credit APIs

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Describe your changes
This PR lay the foundation of retrieve CI build credit through API. 
Separate the logic into separate PR for code review, expect more to come in the separate PR.
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46069)

### CODE REVIEW

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46069)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — CHANGES_REQUESTED** [review]
@Xin-Harness don't you think there are too many TODOs in this PR, you can take some time and complete those in this PR itself, just a suggestion.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46069#-:-NSG0O0I-TAM2HpFY2VN:bwqijuc)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/mappers/module/CICreditObjectMapper.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/46069#-NSG-s3s8uDo0WycCdOP:-NSG-s3s8uDo0WycCdOQ:b-gno6lj) ([raw file](https://github.com/harness/harness-core/blob/8195c03c43ae2d9781ee5204da4675392e9b3423/930-ng-license-manager/src/main/java/io/harness/credit/mappers/module/CICreditObjectMapper.java#L22)):*
> ```Java
>   @Override
>   public CICreditDTO toDTO(CICredit credit) {
>     return CICreditDTO.builder().build();
> ```

why are we not populating the relevant fields here?
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/mappers/module/CICreditObjectMapper.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/46069#-NSG-yiq-hQ54ONTePz9:-NSG-yiq-hQ54ONTePzA:b-gno6lj) ([raw file](https://github.com/harness/harness-core/blob/8195c03c43ae2d9781ee5204da4675392e9b3423/930-ng-license-manager/src/main/java/io/harness/credit/mappers/module/CICreditObjectMapper.java#L27)):*
> ```Java
>   @Override
>   public CICredit toEntity(CICreditDTO creditDTO) {
>     return CICredit.builder().build();
> ```

why are we not populating the relevant fields here?

**Review by neelam-harness — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46069)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/resource/CreditResource.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/46069#-NSDiqw85FU3UH9XpA9D:-NSDiqw85FU3UH9XpA9E:blwb3y2) ([raw file](https://github.com/harness/harness-core/blob/8195c03c43ae2d9781ee5204da4675392e9b3423/930-ng-license-manager/src/main/java/io/harness/credit/resource/CreditResource.java#L66)):*
> ```Java
> 
>   /**
>    * this works
> ```

Nit  Remove the comment. 
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/resource/CreditResource.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/46069#-NSDizZk0S0xMtr4A0Tl:-NSDizZl6q1EKYDBCcMC:b-2bt7vh) ([raw file](https://github.com/harness/harness-core/blob/8195c03c43ae2d9781ee5204da4675392e9b3423/930-ng-license-manager/src/main/java/io/harness/credit/resource/CreditResource.java#L76)):*
> ```Java
>   }
> 
>   // TODO: add kryo registration in next PR, don't forget
> ```

Nit Maybe just add a link to the jira ticket for better tracking :) 
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/CreditService.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/46069#-NSHNDJqDxoWj4Rk8YS7:-NSHNDJqDxoWj4Rk8YS8:b-8a2lcd) ([raw file](https://github.com/harness/harness-core/blob/8195c03c43ae2d9781ee5204da4675392e9b3423/930-ng-license-manager/src/main/java/io/harness/credit/services/CreditService.java#L20)):*
> ```Java
>   List<CreditDTO> getCredits(String accountIdentifier);
> 
>   // todo: change the return type to creditDTO and signature to CreditRequest in the future
> ```

Nit add jira ticket

**Review by neelam-harness — DISMISSED** [review]
Overall :lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46069#-:-NSHNawb9_LlzQwnPt8F:b-ltmtb0)* status: 3 file(s) to review. 1 change requests.

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46069)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/mappers/module/CICreditObjectMapper.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/46069#-NSG-s3s8uDo0WycCdOP:-NSHx6J60-Ka0iYU-eUr:b-u19ve) ([raw file](https://github.com/harness/harness-core/blob/8195c03c43ae2d9781ee5204da4675392e9b3423/930-ng-license-manager/src/main/java/io/harness/credit/mappers/module/CICreditObjectMapper.java#L22)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why are we not populating the relevant fields here?
</blockquote></details>

It is because CreditObjectMapper includes all the parents fields, however CICreditObjectMapper doesn't have any specific field so far.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46069)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
