### PR TITLE
feat: [CDS-38235]: Implement MergePR step

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- This step will consume outcome from CreatePR step and help merge the PR. 
- The change is to create the step on the CD service. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)

### CODE REVIEW

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/GitOpsMergePRStepPlanCreatorV2.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/34233#-N4OWBJE5VXGRByD5f5F:-N4OWBJE5VXGRByD5f5G:bn86m4x) ([raw file](https://github.com/harness/harness-core/blob/3972e4ee8632313a6cd3657184c0ccf8fc3d8b2a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/GitOpsMergePRStepPlanCreatorV2.java#L1)):*
> ```Java
> package io.harness.cdng.creator.plan.steps;
> ```

Add License info
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRBaseStepInfo.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/34233#-N4OWFg083ROf9NX1Y-V:-N4OWFg083ROf9NX1Y-W:bn86m4x) ([raw file](https://github.com/harness/harness-core/blob/3972e4ee8632313a6cd3657184c0ccf8fc3d8b2a/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRBaseStepInfo.java#L2)):*
> ```Java
> package io.harness.cdng.gitops;
> ```

Add License info
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/34233#-N4OWHbG7PGLB7w-qC6_:-N4OWHbG7PGLB7w-qC6a:bkhs87l) ([raw file](https://github.com/harness/harness-core/blob/3972e4ee8632313a6cd3657184c0ccf8fc3d8b2a/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L1)):*
> ```Java
> package io.harness.cdng.gitops;
> ```

Add license Info

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/GitOpsMergePRStepPlanCreatorV2.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/34233#-N4OWBJE5VXGRByD5f5F:-N4P0-AI4R0ONfSNJfbk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3972e4ee8632313a6cd3657184c0ccf8fc3d8b2a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/GitOpsMergePRStepPlanCreatorV2.java#L1)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add License info
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRBaseStepInfo.java` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/34233#-N4OWFg083ROf9NX1Y-V:-N4P-y5U4IXpuiuDMN51:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3972e4ee8632313a6cd3657184c0ccf8fc3d8b2a/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRBaseStepInfo.java#L2)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add License info
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/34233#-N4OWHbG7PGLB7w-qC6_:-N4P-ysG-mCJSkyTW2jz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3972e4ee8632313a6cd3657184c0ccf8fc3d8b2a/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L1)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add license Info
</blockquote></details>

Done.

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/34233#-N4PzYPU5RgNnXIuOSr2:-N4PzYPU5RgNnXIuOSr3:b-uuwjng) ([raw file](https://github.com/harness/harness-core/blob/e92eac2aa929f10dc868c85b588a5a7c7b54c228/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L34)):*
> ```Java
>       StepSpecTypeConstants.GITOPS_CREATE_PR),
> 
>   @JsonProperty(StepSpecTypeConstants.GITOPS_CREATE_PR)
> ```

Change it to Merge_PR



_Code quote:_
```Java
  @JsonProperty(StepSpecTypeConstants.GITOPS_CREATE_PR)
```

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/34233#-N4PzYPU5RgNnXIuOSr2:-N4U3hFn07zW8u_IiENq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e92eac2aa929f10dc868c85b588a5a7c7b54c228/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L34)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Change it to Merge_PR
</blockquote></details>

Done.

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 4 of 16 files at r1, 9 of 18 files at r2, 7 of 9 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger ti1

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 16 files at r1, 7 of 18 files at r2, 4 of 5 files at r4, 13 of 16 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233#-:-N4bD130B5yn4Tmha-Vm:bnfp4nl)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 7 of 18 files at r2, 4 of 5 files at r4, 13 of 16 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34233)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`970-ng-commons/src/main/java/io/harness/EntityType.java` line 36 at r9](https://reviewable.io/reviews/harness/harness-core/34233#-N4y2gBh2MCUed__YbWA:-N4y2gBh2MCUed__YbWB:beuc0hz) ([raw file](https://github.com/harness/harness-core/blob/c2e105eeb83ada2138ee5b41fcf3b9094962970e/970-ng-commons/src/main/java/io/harness/EntityType.java#L36)):*
> ```Java
>   GITOPS_CREATE_PR(
>       ModuleType.CD, EntityTypeConstants.GITOPS_CREATE_PR, IdentifierRef.class, EntityYamlRootNames.GITOPS_CREATE_PR),
>   GITOPS_MERGE_PR(
> ```

this should be added in the end of the enum list

**Comment by rohitk-h** [comment]
*[`970-ng-commons/src/main/java/io/harness/EntityType.java` line 36 at r9](https://reviewable.io/reviews/harness/harness-core/34233#-N4y2gBh2MCUed__YbWA:-N522HlqAJgiZYO4HFlk:bg4pklo) ([raw file](https://github.com/harness/harness-core/blob/c2e105eeb83ada2138ee5b41fcf3b9094962970e/970-ng-commons/src/main/java/io/harness/EntityType.java#L36)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should be added in the end of the enum list
</blockquote></details>

closing loop on the thread. 970-ng-commons/src/main/proto/io/harness/eventsframework/schemas/entity/entity_type.proto file had changed that led to the failed PR check. This the one that is being used in the delegate. The Step value is added correctly at the bottom in this file. 
Recommended to change the 970-ng-commons/src/main/java/io/harness/EntityType.java file for inte micro svc communication between pipeline and CDNG since we are no longer version dependent.

**Pull request merged**
