### PR TITLE
feat: [CDS-38748]:  WinRm: Implement changes on delegate side - copy handler

### PR DESCRIPTION
**Pull request by bojanmicovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35810)

### CODE REVIEW

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35810)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ConfigFileMetaData.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/35810#-N8Oeukr3fFahcqw2zoK:-N8Oeukr3fFahcqw2zoL:bgt708t) ([raw file](https://github.com/harness/harness-core/blob/e3092d4ad3b6957c25df84bc378bb1d12e083548/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ConfigFileMetaData.java#L29)):*
> ```Java
>   private boolean encrypted;
>   private String activityId;
>   private String content;
> ```

for NG, we are using `ConfigFileParameters` which already has the content method. The existing configfilemetadata has attributes that are missleading to NG, like activityId and so on.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmCopyCommandHandler.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/35810#-N8OgOG3BfT6q-DNff6X:-N8OgOG3BfT6q-DNff6Y:bpjo2wh) ([raw file](https://github.com/harness/harness-core/blob/e3092d4ad3b6957c25df84bc378bb1d12e083548/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmCopyCommandHandler.java#L117)):*
> ```Java
>         configFile.setFileSize(fileData.getBytes(StandardCharsets.UTF_8).length);
>       }
>       ConfigFileMetaData configFileMetaData = ConfigFileMetaData.builder()
> ```

Let's use `ConfigFileParameters` instead
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/35810#-N8OhU67Bm3ZzEcSDPiG:-N8OhU67Bm3ZzEcSDPiH:b-tiq4r6) ([raw file](https://github.com/harness/harness-core/blob/e3092d4ad3b6957c25df84bc378bb1d12e083548/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L59)):*
> ```Java
> 
>   @Override
>   public byte[] getConfigFileBytes(ConfigFileMetaData configFileMetaData) {
> ```

at the time those executors were refactored and moved to proper modules, we didn't knew that we are going to use a different entity for storing config file metadata.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 10 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35810)

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmCopyCommandHandler.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/35810#-N8OgOG3BfT6q-DNff6X:-N8XmlNIAZ1mlcGrxJ9G:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e3092d4ad3b6957c25df84bc378bb1d12e083548/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmCopyCommandHandler.java#L117)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

Let's use `ConfigFileParameters` instead
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/35810#-N8OhU67Bm3ZzEcSDPiG:-N8Xmp955YNXhpbyh1jW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e3092d4ad3b6957c25df84bc378bb1d12e083548/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L59)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

at the time those executors were refactored and moved to proper modules, we didn't knew that we are going to use a different entity for storing config file metadata.
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ConfigFileMetaData.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/35810#-N8Oeukr3fFahcqw2zoK:-N8XmsB913F7eVMDcpuQ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e3092d4ad3b6957c25df84bc378bb1d12e083548/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ConfigFileMetaData.java#L29)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

for NG, we are using `ConfigFileParameters` which already has the content method. The existing configfilemetadata has attributes that are missleading to NG, like activityId and so on.
</blockquote></details>

Done

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35810)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35810)* status: :shipit: complete! ✓

**Pull request merged**
