### PR TITLE
[feat]: [CDS-33522]: Azure NG model refactoring

### PR DESCRIPTION
**Pull request by alebuh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32238)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32238)* status: :shipit: complete! ✓

**Comment by markoharness** [comment]
trigger ti0

**Comment by markoharness** [comment]
trigger ti3

**Review by markoharness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32238)* status: :shipit: complete! ✓

**Review by markoharness — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 32 of 32 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32238)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 32 of 32 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32238)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 32 of 32 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32238)* status: :shipit: complete! ✓

**Pull request merged**
