### PR TITLE
[feat]: [CDS-41950]: do not copy docker registry artifact

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36609)

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmArtifactHelper.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4n7mX4w97xou8Gmt5:-NA4n7mX4w97xou8Gmt6:bnby0r3) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmArtifactHelper.java#L86)):*
> ```Java
>       ArtifactoryArtifactOutcome artifactoryArtifactOutcome = (ArtifactoryArtifactOutcome) artifactOutcome;
>       connectorDTO = getConnectorInfoDTO(artifactoryArtifactOutcome.getConnectorRef(), ngAccess);
>       return DockerRegistryArtifactDelegateConfig.builder()
> ```

this is artifactory related, not docker. Docker is a different source type. You can put ArtifactoryDockerArtifactDelegateConfig
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/FileBasedAbstractScriptExecutorNG.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4nNXM2Tf-6A5b9ZXf:-NA4nNXN-D4gX2-qW7cg:bxa0h6r) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/FileBasedAbstractScriptExecutorNG.java#L65)):*
> ```Java
>           "Unsupported artifact type provided: %s", context.getArtifactDelegateConfig().getArtifactType().name()));
>     }
>     if (context.getArtifactDelegateConfig() instanceof DockerRegistryArtifactDelegateConfig) {
> ```

as discussed, we needed to have a marker interface and check here, not on specific type. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/FileBasedAbstractScriptExecutorNG.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4nXqV7AgVFLCHIsxy:-NA4nXqV7AgVFLCHIsxz:b-lnoz7f) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/FileBasedAbstractScriptExecutorNG.java#L66)):*
> ```Java
>     }
>     if (context.getArtifactDelegateConfig() instanceof DockerRegistryArtifactDelegateConfig) {
>       log.info("Will not copy artifact for docker registry artifact type.");
> ```

change the log message to `Artifactory docker registry found, skipping copy artifact`
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/FileBasedAbstractScriptExecutorNG.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4npQmE2BbC8Elsc03:-NA4npQmE2BbC8Elsc04:b6d9iye) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/FileBasedAbstractScriptExecutorNG.java#L68)):*
> ```Java
>       log.info("Will not copy artifact for docker registry artifact type.");
>       logCallback.saveExecutionLog(
>           "Copy step finished with no action for docker registry artifact type", LogLevel.INFO);
> ```

we don't have copy step, only command unit. Remove that log.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/ArtifactoryCommandUnitHandler.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4oMYo1B6d_-5hUwXf:-NA4oMYo1B6d_-5hUwXg:bow74kl) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/ArtifactoryCommandUnitHandler.java#L71)):*
> ```Java
>     } else {
>       logCallback.saveExecutionLog(color(
>           format("%s artifact with identifier: %s will not be downloaded, as repository format not of type generic",
> ```

remove that else, no need to print that
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4oTZI5qOP1zl0L-rM:-NA4oTZI5qOP1zl0L-rN:b-ylfu5k) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L87)):*
> ```Java
>     } else if (artifactDelegateConfig instanceof DockerRegistryArtifactDelegateConfig) {
>       log.info("Will not copy artifact for docker registry artifact type.");
>       logCallback.saveExecutionLog(
> ```

same as for ssh
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4om013A3-BneUf3cF:-NA4om02E5WDpwZSuN8R:b-u6ogpm) ([raw file](https://github.com/harness/harness-core/blob/48ca098842f2d5ce9493f11d92d4787159f28a02/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java#L74)):*
> ```Java
>       final List<ExecutionCapability> capabilities, ExpressionEvaluator maskingEvaluator) {
>     if (SshWinRmArtifactType.ARTIFACTORY.equals(artifactDelegateConfig.getArtifactType())) {
>       ArtifactoryArtifactDelegateConfig artifactoryDelegateConfig =
> ```

have you tested this?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/DockerRegistryArtifactDelegateConfig.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4oqgYExsBOo2TOcvJ:-NA4oqgYExsBOo2TOcvK:bpgz271) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/DockerRegistryArtifactDelegateConfig.java#L24)):*
> ```Java
>   @NonFinal @Expression(ALLOW_SECRETS) String artifactPath;
>   @NonFinal @Expression(ALLOW_SECRETS) String artifactDirectory;
>   String repositoryFormat; // its value is "docker"
> ```

remove that comment
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SkipCopyArtifactDelegateConfig.java` line 2 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4otqZ-cjwMeEWxZ_a:-NA4otqZ-cjwMeEWxZ_b:b-tt959v) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SkipCopyArtifactDelegateConfig.java#L2)):*
> ```Java
> package io.harness.delegate.task.ssh.artifact;
> ```

owned by and also you need to register this class in delegate kryo
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SshWinRmArtifactDelegateConfig.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4p5NBEccQq79XdiKw:-NA4p5NBEccQq79XdiKx:b-wfzip8) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SshWinRmArtifactDelegateConfig.java#L21)):*
> ```Java
>   String getIdentifier();
>   SshWinRmArtifactType getArtifactType();
>   ConnectorInfoDTO getConnectorDTO();
> ```

why is that here? we have artifacts without connectors
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SshWinRmArtifactDelegateConfig.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4p9Xf4OAj6qW_PYKD:-NA4p9Xf4OAj6qW_PYKE:b80gtfq) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SshWinRmArtifactDelegateConfig.java#L22)):*
> ```Java
>   SshWinRmArtifactType getArtifactType();
>   ConnectorInfoDTO getConnectorDTO();
>   List<EncryptedDataDetail> getEncryptedDataDetails();
> ```

why those are moved here?

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4om013A3-BneUf3cF:-NA4um3lAQ9Cv7VPfFj-:bbzzb7h) ([raw file](https://github.com/harness/harness-core/blob/48ca098842f2d5ce9493f11d92d4787159f28a02/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/CommandTaskParameters.java#L74)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

have you tested this?
</blockquote></details>

yes, but if you think this can introduce some potential issues, I can write this more safely.



_Code quote (from 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/ArtifactoryCommandUnitHandler.java):_
```Java
format("%s artifact with identifier: %s will not be downloaded, as repository format not of type generic",
```
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SshWinRmArtifactDelegateConfig.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4p9Xf4OAj6qW_PYKD:-NA4wxAN3P2_t4zCEzoZ:b-3pd092) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/SshWinRmArtifactDelegateConfig.java#L22)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why those are moved here?
</blockquote></details>

Wanted to simplify mapping to DelegateTaskParameters, but this might not be the best approach. Rewriting it.

**Comment by vladimir-peric** [comment]
Is it new task type? > No

Did you add a new class which is added in kryo serialization? > Yes
if yes then do not use that class in any of the delegate task payload till it makes to delegate release. > This is related to newly added feature, which is under FF and will be relased later.

Did you make changes to the code in a backward-compatible manner?
will the new version of the delegate receive old version task and process? > Yes

If new version of the manager receives response for the old task will it be able to handle it successfully? > Yes

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager No

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay > Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay > Yes

Did you remove an enum → this is not backward compatible yet: > No

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side. > No

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 9 of 10 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmArtifactHelper.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/36609#-NA4n7mX4w97xou8Gmt5:-NA5HcGeBJkTlXPGpl__:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/4370a01419a553d96df4322a3ce462ae1655f431/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshWinRmArtifactHelper.java#L86)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

this is artifactory related, not docker. Docker is a different source type. You can put ArtifactoryDockerArtifactDelegateConfig
</blockquote></details>

ok
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 113 at r6](https://reviewable.io/reviews/harness/harness-core/36609#-NA5Hpup6D4O6goUjIWH:-NA5Hpup6D4O6goUjIWI:b-tbxgv7) ([raw file](https://github.com/harness/harness-core/blob/7e4b98efce01d9788a0d3acaefef2a35901fd62f/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L113)):*
> ```Java
>       }
>       if (context.getArtifactDelegateConfig() instanceof SkipCopyArtifactDelegateConfig
>               && ((SkipCopyArtifactDelegateConfig) context.getArtifactDelegateConfig()).skipCopyStep()) {
> ```

do we need that additional check? type should be enough, no? Also before returning the result, we need to put `executor.getLogCallback().saveExecutionLog("Command finished with status " + result, LogLevel.INFO, result);`
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 86 at r6](https://reviewable.io/reviews/harness/harness-core/36609#-NA5I4PO9CpBUxdXcxVP:-NA5I4PO9CpBUxdXcxVQ:b-3r7kvb) ([raw file](https://github.com/harness/harness-core/blob/7e4b98efce01d9788a0d3acaefef2a35901fd62f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L86)):*
> ```Java
>       return handleJenkinsArtifact((JenkinsArtifactDelegateConfig) artifactDelegateConfig, copyCommandUnit);
>     } else if (artifactDelegateConfig instanceof SkipCopyArtifactDelegateConfig
>         && ((SkipCopyArtifactDelegateConfig) artifactDelegateConfig).skipCopyStep()) {
> ```

again, do we need that additional method check skipCopyStep() ?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/ArtifactoryDockerArtifactDelegateConfig.java` line 38 at r6](https://reviewable.io/reviews/harness/harness-core/36609#-NA5ICCB5SI74oYDnT7V:-NA5ICCB5SI74oYDnT7W:b-irakzx) ([raw file](https://github.com/harness/harness-core/blob/7e4b98efce01d9788a0d3acaefef2a35901fd62f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/artifact/ArtifactoryDockerArtifactDelegateConfig.java#L38)):*
> ```Java
> 
>   @Override
>   public boolean skipCopyStep() {
> ```

do we need that method? Type should be enough

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 113 at r6](https://reviewable.io/reviews/harness/harness-core/36609#-NA5Hpup6D4O6goUjIWH:-NA5Iorr9G7OBqNdPB-s:b-8suw3j) ([raw file](https://github.com/harness/harness-core/blob/7e4b98efce01d9788a0d3acaefef2a35901fd62f/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L113)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

do we need that additional check? type should be enough, no? Also before returning the result, we need to put `executor.getLogCallback().saveExecutionLog("Command finished with status " + result, LogLevel.INFO, result);`
</blockquote></details>

ok, didn't understand you on previous comment, pushing an update.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 3 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 87 at r8](https://reviewable.io/reviews/harness/harness-core/36609#-NA5LZR03Dw0qzj9Keig:-NA5LZR03Dw0qzj9Keih:b-escv1t) ([raw file](https://github.com/harness/harness-core/blob/a4c1ca7632dfba549b21f8bb3023c4139cf8738c/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L87)):*
> ```Java
>     } else if (artifactDelegateConfig instanceof SkipCopyArtifactDelegateConfig) {
>       log.info("Artifactory docker registry found, skipping copy artifact.");
>       logCallback.saveExecutionLog("Command finished with status " + SUCCESS, LogLevel.INFO, SUCCESS);
> ```

ok @vladimir-peric we need that only once, in SshCopy handler. pls remove it from here

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger codebasehash

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 6 of 10 files at r5, 2 of 2 files at r6, 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609#-:-NA5jVyd9gWltg0BN1Fw:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609#-:-NA5jzpW3K_Cg9Tyfphr:bnfp4nl)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609#-:-NA5kg1m-WGOJyYDBG5p:bnfp4nl)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 6 of 10 files at r5, 1 of 2 files at r6, 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: 1 file(s) to review. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 113 at r6](https://reviewable.io/reviews/harness/harness-core/36609#-NA5Hpup6D4O6goUjIWH:-NA5mpWV2iKT3K-UB0vQ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/7e4b98efce01d9788a0d3acaefef2a35901fd62f/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L113)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

ok, didn't understand you on previous comment, pushing an update.
</blockquote></details>

Done

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 8 of 10 files at r5, 1 of 1 files at r7, 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36609)* status: :shipit: complete! ✓

**Pull request merged**
