### PR TITLE
[feat]: [PL-28310]: adding validation for NG Gcp secret manager

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
Adding validation for google secret manager. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38307)

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 348 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDW_NK_E4NvluhIPYO8:-NDW_NK_E4NvluhIPYO9:b-iom7wi) ([raw file](https://github.com/harness/harness-core/blob/c0b3b70963fd64b2a1b710ddd32ffdacad489e04/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L348)):*
> ```Java
>         ProjectName projectName = ProjectName.of(projectId);
>         // Get all secrets.
>         SecretManagerServiceClient.ListSecretsPagedResponse pagedResponse = client.listSecrets(projectName);
> ```

Why is it required to fetch and iterate over all the secrets? Why can't we try fetching just one secret assuming its already present?
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 364 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDWZWGUAgdSkRX1Tn4w:-NDWZWGUAgdSkRX1Tn4x:brtt6m) ([raw file](https://github.com/harness/harness-core/blob/c0b3b70963fd64b2a1b710ddd32ffdacad489e04/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L364)):*
> ```Java
>   }
> 
>   private void validateUserInput(GcpSecretsManagerConfig gcpSecretsManagerConfig) {
> ```

Why this validation is required in connectivity test? These validation should already be covered when the connector is getting created.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDWaKku4F58_0OVxVNN:-NDWaKku4F58_0OVxVNO:b-f8cv5w) ([raw file](https://github.com/harness/harness-core/blob/c0b3b70963fd64b2a1b710ddd32ffdacad489e04/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L333)):*
> ```Java
> 
>   @Override
>   public boolean validateSecretManagerConfiguration(String accountId, EncryptionConfig encryptionConfig) {
> ```

Add UT for this.

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 333 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDWaKku4F58_0OVxVNN:-NE4j-w12GHL_Q3zNNTj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/531fb2bb248b4576183930592b43440f125ff387/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L333)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add UT for this.
</blockquote></details>

Done.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 348 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDW_NK_E4NvluhIPYO8:-NE4j0jg1KXVaSHnonZB:b-t97lls) ([raw file](https://github.com/harness/harness-core/blob/531fb2bb248b4576183930592b43440f125ff387/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L348)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why is it required to fetch and iterate over all the secrets? Why can't we try fetching just one secret assuming its already present?
</blockquote></details>

We dont know which secret the user would have. So we iterate over all secrets and do no operation on them. 
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 364 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDWZWGUAgdSkRX1Tn4w:-NE4jBTr4379Kgm2qsNZ:b-o2fisc) ([raw file](https://github.com/harness/harness-core/blob/531fb2bb248b4576183930592b43440f125ff387/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L364)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why this validation is required in connectivity test? These validation should already be covered when the connector is getting created.
</blockquote></details>

Its not needed. Have removed it.

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 348 at r1](https://reviewable.io/reviews/harness/harness-core/38307#-NDW_NK_E4NvluhIPYO8:-NE525fg0kTu2AetRmH6:bogig45) ([raw file](https://github.com/harness/harness-core/blob/531fb2bb248b4576183930592b43440f125ff387/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L348)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

We dont know which secret the user would have. So we iterate over all secrets and do no operation on them. 
</blockquote></details>

This is same how its being done in CG. Used the same approach here.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java` line 273 at r2](https://reviewable.io/reviews/harness/harness-core/38307#-NE530_e4Ehc9KbBgmdZ:-NE530_e4Ehc9KbBgmd_:b-od8bmh) ([raw file](https://github.com/harness/harness-core/blob/1f05e91267b735b3e24b91eda0550c3406418e1c/890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java#L273)):*
> ```Java
>   @Category(UnitTests.class)
>   public void test_whenThereAreNoSecretsShouldPass() {
>     gcpSecretsManagerEncryptor.validateSecretManagerConfiguration(accountId, gcpSecretsManagerConfig);
> ```

Not asserting anything?
___
*[`890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java` line 284 at r2](https://reviewable.io/reviews/harness/harness-core/38307#-NE537Z92p2L-x5NmNDQ:-NE537Z92p2L-x5NmNDR:b-od8bmh) ([raw file](https://github.com/harness/harness-core/blob/1f05e91267b735b3e24b91eda0550c3406418e1c/890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java#L284)):*
> ```Java
>     secrets.add(Secret.newBuilder().build());
>     when(listSecretsPagedResponse.iterateAll()).thenReturn(secrets);
>     gcpSecretsManagerEncryptor.validateSecretManagerConfiguration(accountId, gcpSecretsManagerConfig);
> ```

Not asserting anything?

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java` line 273 at r2](https://reviewable.io/reviews/harness/harness-core/38307#-NE530_e4Ehc9KbBgmdZ:-NE5Fi8C2m2B3_5iexXu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f05e91267b735b3e24b91eda0550c3406418e1c/890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java#L273)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Not asserting anything?
</blockquote></details>

Done.
___
*[`890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java` line 284 at r2](https://reviewable.io/reviews/harness/harness-core/38307#-NE537Z92p2L-x5NmNDQ:-NE5FiM7BrqbPAAMHFx9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f05e91267b735b3e24b91eda0550c3406418e1c/890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java#L284)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Not asserting anything?
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38307)* status: :shipit: complete! ✓

**Pull request merged**
