### PR TITLE
[feat]: [CDS-59190]: support url encoding in HTTP step

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
https://github.com/harness/harness-core/pull/47467
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47496)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 754 at r1](https://reviewable.io/reviews/harness/harness-core/47496#-NUvCtf8CqJY2rvl9JuT:-NUvCtf8CqJY2rvl9JuU:bxgzljd) ([raw file](https://github.com/harness/harness-core/blob/8f4b003ed7e698f6cbf509cb6cd947cc500ffc9c/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L754)):*
> ```Java
>   CI_ENABLE_DLC("Enable docker layer caching", HarnessTeam.CI),
>   CI_USE_S3_FOR_DLC("Use S3 bucket for DLC cache", HarnessTeam.CI),
>   CDS_ENCODE_HTTP_STEP_URL("Enables teh encoding of HTTP Step URL is it si not allready encoded", HarnessTeam.CDP);
> ```

typo in "teh"

**Comment by yogesh-chauhan** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 754 at r1](https://reviewable.io/reviews/harness/harness-core/47496#-NUvCtf8CqJY2rvl9JuT:-NUvCvuf-li5hXpNVIh5:b-v7fnvw) ([raw file](https://github.com/harness/harness-core/blob/8f4b003ed7e698f6cbf509cb6cd947cc500ffc9c/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L754)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

typo in "teh"
</blockquote></details>

some other typos as well

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47496)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47496)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 754 at r1](https://reviewable.io/reviews/harness/harness-core/47496#-NUvCtf8CqJY2rvl9JuT:-NUvGl-m3eCSbxtXZJBx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8f4b003ed7e698f6cbf509cb6cd947cc500ffc9c/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L754)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

some other typos as well
</blockquote></details>

Done

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47496)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger uts

**Review by vcalasansh — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47496)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by tmacari-harness** [comment]
trigger uts

**Review by vcalasansh — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47496)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
