### PR TITLE
[feat]: [CDS-39827]: Api support for all template crud and listing apis

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35588)

### CODE REVIEW

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35588)* status: 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/35588#-N7VUwvs7xIxBwFmb8LC:-N7VUwvs7xIxBwFmb8LD:b-23t9wz) (no related file):*
@utkarshchoubey-harness did we verify descriptions and name for all the query and path parameters as well with @rashminandasahoo ?

Do check name and descriptions of request and response payloads of the APIs as well. Those should be appropriate and shouldn't have DTO in the name.

___
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 240 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N7VTEQJ7BR5PYwABJST:-N7VTEQJ7BR5PYwABJSU:bwfvwpr) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L240)):*
> ```Java
>   @Path("/updateStableTemplate/{templateIdentifier}/{versionLabel}")
>   @ApiOperation(value = "Updating stable template label", nickname = "updateStableTemplate")
>   @Operation(operationId = "updateStableTemplate", summary = "Update stable Template Label",
> ```

@rashminandasahoo can we change this to `update stable version of template`



_Code quote:_
```Java
Update stable Template Label
```
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N7VTX6cEfFT6ld6TLC0:-N7VTX6cEfFT6ld6TLC1:byk7zjl) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L274)):*
> ```Java
>   @Path("/update/{templateIdentifier}/{versionLabel}")
>   @ApiOperation(value = "Updating existing template label", nickname = "updateExistingTemplateLabel")
>   @Operation(operationId = "updateExistingTemplateLabel", summary = "Update the Template Label",
> ```

Let's change Label to Version
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N7VU2ItCRT1BHxiW2dK:-N7VU2ItCRT1BHxiW2dL:b-hkxugq) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L352)):*
> ```Java
>   @ApiOperation(value = "Deletes multiple template versionLabels of a particular template identifier",
>       nickname = "deleteTemplateVersionsOfIdentifier")
>   @Operation(operationId = "deleteTemplateVersionsOfIdentifier", summary = "Delete Template Version Labels",
> ```

@rashminandasahoo can we change it to `Delete multiple template versions`?



_Suggestion:_
```Java
Delete Template Version Labels
```

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35588)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 240 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N7VTEQJ7BR5PYwABJST:-N83n4984dsIH0PoxoPY:bg3b90l) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L240)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

@rashminandasahoo can we change this to `update stable version of template`
</blockquote></details>

Update Stable Template Version
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N7VTX6cEfFT6ld6TLC0:-N83nD6p7RqjTi1LK9OW:brme4ly) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L274)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Let's change Label to Version
</blockquote></details>

Update Template Version

operationId change it to version -> updateExisitingTemplateVersion
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N83oQ4Y2zJl-1T0Hwdd:-N83oQ4Y2zJl-1T0Hwde:bb1pzq6) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L319)):*
> ```Java
>   @Path("/{templateIdentifier}/{versionLabel}")
>   @ApiOperation(value = "Deletes template versionLabel", nickname = "deleteTemplateVersionLabel")
>   @Operation(operationId = "deleteTemplateVersionLabel", summary = "Delete Template Version Label",
> ```

Delete Template Version 



_Code quote:_
```Java
Delete Template Version 
```
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/35588#-N7VU2ItCRT1BHxiW2dK:-N83nUX4-K_IhIFVoGzS:b-5reqt7) ([raw file](https://github.com/harness/harness-core/blob/936b7aa81f94ce1786c628e01d849a38fb66c621/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L352)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

@rashminandasahoo can we change it to `Delete multiple template versions`?
</blockquote></details>

Make it Hidden 
 
and change it to 
Delete Template Versions

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35588)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/35588#-N7VUwvs7xIxBwFmb8LC:-N8N2sMK8NSNjmyi-pN7:b-896fix) (no related file):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

@utkarshchoubey-harness did we verify descriptions and name for all the query and path parameters as well with @rashminandasahoo ?

Do check name and descriptions of request and response payloads of the APIs as well. Those should be appropriate and shouldn't have DTO in the name.
</blockquote></details>

Done.

___

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35588)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35588#-:-N8N6hZM8FjZ8HO2ZI0m:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35588)* status: :shipit: complete! ✓

**Pull request merged**
