### PR TITLE
[fix]: [CDS-36417]: added null checks

### PR DESCRIPTION
**Pull request by prabu-kr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32315)

### CODE REVIEW

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32315)* status: :shipit: complete! ✓

**Comment by prabu-kr** [comment]
trigger messagecheck

**Comment by prabu-kr** [comment]
trigger messagecheck

**Review by poojaSinghal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32315)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/sm/states/collaboration/JiraCreateUpdate.java, line 192 at r2](https://reviewable.io/reviews/harness/harness-core/32315#-N0-_JyCEQLr4SdLfmVz:-N0-_JyCEQLr4SdLfmW-:b59glcs) ([raw file](https://github.com/harness/harness-core/blob/665ba8911e8f3f5ad5865292a41a08e9ee6151ea/400-rest/src/main/java/software/wings/sm/states/collaboration/JiraCreateUpdate.java#L192)):*
> ```Java
>     if (areRequiredFieldsTemplatized) {
>       createMeta = jiraHelperService.getCreateMetadata(jiraConnectorId, null, project, accountId, context.getAppId(),
>           getTimeoutMillis() != null ? getTimeoutMillis() : JIRA_TASK_TIMEOUT_MILLIS);
> ```

can you pull this out in a separate line I see this 3 times in the same method



_Code quote:_
```Java
getTimeoutMillis() != null ? getTimeoutMillis() : JIRA_TASK_TIMEOUT_MILLIS);
```

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32315)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32315#-:-N0-bbuaAokyxtf-ZHUb:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
