### PR TITLE
fix: [CDS-34613]: Fix K8s post-deployment rollback issues

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
**Background**:
The affected customer's workflow consisted of a K8s Apply step (deploying some ConfigMaps/PVs etc.), followed by a K8s Rolling Step (deploying their managed resources). 
The following issues were identified when post production rollback was triggered from the service instances dashboard:
- Rollback was being skipped with the message:  "No failed release found. Skipping rollback."
- **Instances Deployed** field on the workflow execution screen was **None** (despite actual rollback being executed or being skipped)

**Root Causes**:

- Instances Deployed: Instance data is not being passed from RollbackTaskHandler to the manager.
- Skipped Rollback: Multiple K8sExecutions set up within the same workflow were leading to the wrong K8sExecutionContext being passed to the manager (with releaseNumber NULL - from K8s Apply Step). This was leading to the rollback being skipped.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Review by srinivaswings — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 6 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Review by srinivaswings — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 6 of 9 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 5 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31307)* status: :shipit: complete! ✓

**Pull request merged**
