### PR TITLE
feat:[CDS-54086]: Add validation to avoid ClassCastException

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
* When YAML has a reference to an invalid connector it throws a ClassCastException.
* Now we identify the wrong setting and provide a better message

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44366)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44366)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44366)* status: Some of the checks are too old.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44366)* status: Some of the checks are too old.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44366)* status: Some of the checks are too old.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44366)* status: Some of the checks are too old.

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Comment by mbatchelor** [comment]
trigger smartchecks

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Comment by Fernando-Dourado** [comment]
trigger smartchecks

**Pull request merged**
