### PR TITLE
feat: [CDS-51736]: Added the Bamboo Build support

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44444)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPVo_640QdaGhBcgNoN:-NPVo_640QdaGhBcgNoO:b189ft2) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java#L88)):*
> ```Java
>   }
> 
>   @POST
> ```

this change is not backward compatible, right ?

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44444)* status: 54 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPVo_640QdaGhBcgNoN:-NPVpTYpC4SfapFUgUDt:bqgylk4) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java#L88)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this change is not backward compatible, right ?
</blockquote></details>

@yogesh-chauhan These changes is not yet consumed by UI, it is still inprogress from UI side.
To support runtime variable, I have updated the APIs and asked the UI to make necessary changes as well

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPVo_640QdaGhBcgNoN:-NPVw7BzCuA-VAHccKsP:b-rwkdx0) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java#L88)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

@yogesh-chauhan These changes is not yet consumed by UI, it is still inprogress from UI side.
To support runtime variable, I have updated the APIs and asked the UI to make necessary changes as well
</blockquote></details>

Ideally we should hide these APIs from open api until we finalise our development

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/bamboo/BambooBuildStepNode.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPVxL-rEOclHRttRT15:-NPVxL-rEOclHRttRT16:bnovbxl) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/125-cd-nextgen/src/main/java/io/harness/cdng/bamboo/BambooBuildStepNode.java#L36)):*
> ```Java
> @JsonTypeName(StepSpecTypeConstants.BAMBOO_BUILD)
> @TypeAlias("BambooBuildStepNode")
> @OwnedBy(PIPELINE)
> ```

should be owned by CDC

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/main/java/io/harness/beans/EntityReference.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/44444#-NPW0Hsp4xvipL0uSPmu:-NPW0Hsp4xvipL0uSPmv:b-l2d77f) ([raw file](https://github.com/harness/harness-core/blob/b8267fed1283a4934d7ac695bbb8b3b7dfc3dfe5/970-ng-commons/src/main/java/io/harness/beans/EntityReference.java#L20)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @ApiModel(value = "EntityReference",
>     subTypes = {IdentifierRef.class, InputSetReference.class, NGTemplateReference.class}, discriminator = "type")
> ```

is this intentional ?

**Comment by yogesh-chauhan** [comment]
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/HsqsClientConstants.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPW0bh1B_2GdNfxDcaE:-NPW0bh1B_2GdNfxDcaF:b-l2d77f) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/HsqsClientConstants.java#L11)):*
> ```Java
> 
> public final class HsqsClientConstants {
>   public static final String QUEUE_SERVICE_ENV_NAMESPACE = "queueEnvNamespace";
> ```

is this intentional ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 13 of 48 files at r1, 39 of 39 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44444)* status: 54 file(s) to review. 0 of 2 approvals obtained.

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44444)* status: 54 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java` line 88 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPVo_640QdaGhBcgNoN:-NPW1ar6D6ZeY31dAGLn:bgg575v) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/bamboo/BambooArtifactResource.java#L88)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Ideally we should hide these APIs from open api until we finalise our development
</blockquote></details>

Yes, UI changes are also getting merged this release
___
*[`970-ng-commons/src/main/java/io/harness/beans/EntityReference.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/44444#-NPW0Hsp4xvipL0uSPmu:-NPW1wAXB9oWk4jSub10:b-25iyok) ([raw file](https://github.com/harness/harness-core/blob/b8267fed1283a4934d7ac695bbb8b3b7dfc3dfe5/970-ng-commons/src/main/java/io/harness/beans/EntityReference.java#L20)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional ?
</blockquote></details>

Rebase has caused the changes
___
*[`clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/HsqsClientConstants.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/44444#-NPW0bh1B_2GdNfxDcaE:-NPW20AzAYweLVIJkjGx:b-x5mefi) ([raw file](https://github.com/harness/harness-core/blob/e16203a49131d6af4c1d4556ff5cb847f71d966f/clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model/HsqsClientConstants.java#L11)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional ?
</blockquote></details>

Code formatting caused the issue

**Review by vtxorxwitty — APPROVED** [review]
> Reviewed 13 of 48 files at r1, 36 of 39 files at r2, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44444)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44444)* status: 6 file(s) to review.

**Review by vtxorxwitty — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44444#-:-NPqcYfU4OkN-lvgKx3r:bnfp4nl)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Pull request merged**
