### PR TITLE
feat: [CDS-39673]: use applyTemplatesv2 api in pipeline CRUD flow

### PR DESCRIPTION
**Pull request by inderschera**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)

### CODE REVIEW

**Comment by inderschera** [comment]
trigger ft2

**Review by poojaSinghal — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 9 Issues 
* Code issue 8 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35190)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 547 at r4](https://reviewable.io/reviews/harness/harness-core/35190#-N8THU0BEw8ccEFTcENX:-N8THU0BEw8ccEFTcENY:b-3duhjm) ([raw file](https://github.com/harness/harness-core/blob/ae9cafe534d6e7270d0d86e2846fa44f1485dea5/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L547)):*
> ```Java
> 
>   @POST
>   @Path("/applyTemplates/v2")
> ```

change order of api



_Code quote:_
```Java
("/applyTemplates/v2")
```
___
*[`930-ng-core-clients/src/main/java/io/harness/template/remote/TemplateResourceClient.java` line 61 at r4](https://reviewable.io/reviews/harness/harness-core/35190#-N8THWEC9vFJWhlDLt56:-N8THWEC9vFJWhlDLt57:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/ae9cafe534d6e7270d0d86e2846fa44f1485dea5/930-ng-core-clients/src/main/java/io/harness/template/remote/TemplateResourceClient.java#L61)):*
> ```Java
>       @Body TemplateApplyRequestDTO templateApplyRequestDTO);
> 
>   @POST(TEMPLATE_ENDPOINT + "applyTemplates/v2")
> ```

same here



_Code quote:_
```Java
@POST(TEMPLATE_ENDPOINT + "applyTemplates/v2")
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/35190#-N8TJb8S1eOd-Mpie-4j:-N8TJb8T8va1vl2_fZUj:bd5dfjy) ([raw file](https://github.com/harness/harness-core/blob/ae9cafe534d6e7270d0d86e2846fa44f1485dea5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L100)):*
> ```Java
>         } else if (e.getMetadata() instanceof ValidateTemplateInputsResponseDTO) {
>           throw new NGTemplateResolveExceptionV2(
>               TEMPLATE_RESOLVE_EXCEPTION_MSG, USER, (ValidateTemplateInputsResponseDTO) e.getMetadata());
> ```

Check with naidu and vaibhav on as you are changing error response in existing API



_Code quote:_
```Java
        } else if (e.getMetadata() instanceof ValidateTemplateInputsResponseDTO) {
          throw new NGTemplateResolveExceptionV2(
              TEMPLATE_RESOLVE_EXCEPTION_MSG, USER, (ValidateTemplateInputsResponseDTO) e.getMetadata());
```

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 547 at r4](https://reviewable.io/reviews/harness/harness-core/35190#-N8THU0BEw8ccEFTcENX:-N8YheBA6vuTpauTqoc-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae9cafe534d6e7270d0d86e2846fa44f1485dea5/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L547)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

change order of api
</blockquote></details>

Done.
___
*[`930-ng-core-clients/src/main/java/io/harness/template/remote/TemplateResourceClient.java` line 61 at r4](https://reviewable.io/reviews/harness/harness-core/35190#-N8THWEC9vFJWhlDLt56:-N8YhfCJBVdssLMcbFln:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae9cafe534d6e7270d0d86e2846fa44f1485dea5/930-ng-core-clients/src/main/java/io/harness/template/remote/TemplateResourceClient.java#L61)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/35190#-N8TJb8S1eOd-Mpie-4j:-N8hLHeK34KnPFxBtCP1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae9cafe534d6e7270d0d86e2846fa44f1485dea5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Check with naidu and vaibhav on as you are changing error response in existing API
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35190)* status: :shipit: complete! ✓

**Pull request merged**
