### PR TITLE
[feat]: [PL-27093]: Improve Error Handling for NG ldap

### PR DESCRIPTION
**Pull request by shashank-harness**
Signed-off-by: Shashank Singh <shashank.singh@harness.io>

## Describe your changes
We have added 3 more scenarios for Error Handling which will send Exceptions with HInts.

- Ldap Connection Settings
- Ldap User Query
- Ldap Group Query

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37042)

**Comment by shashank-harness** [comment]
trigger messagecheck

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
trigger codebasehash

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/37042#-NB3L_Gi-Xr3XWI3n5iA:-NB3L_Gi-Xr3XWI3n5iB:b5rqy1w) ([raw file](https://github.com/harness/harness-core/blob/9c6cf4218291ea8765f0b06f38ed6343a0b874a7/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L151)):*
> ```Java
>     LdapTestResponse ldapTestResponse = delegateTaskResponse.getLdapTestResponse();
> 
>     if (FAILURE == ldapTestResponse.getStatus() && null != ldapTestResponse.getMessage()) {
> ```

minor should we test for ldapTestResponse to be != null ? 



_Code quote:_
```Java
if (FAILURE == ldapTestResponse.
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger ti2

**Comment by pbarapatre10** [comment]
trigger codebasehash

**Comment by pbarapatre10** [comment]
trigger pmd

**Comment by shashank-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/37042#-NB3L_Gi-Xr3XWI3n5iA:-NB5wLnuEnz5bh7oed4J:b-9js03d) ([raw file](https://github.com/harness/harness-core/blob/9c6cf4218291ea8765f0b06f38ed6343a0b874a7/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L151)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor should we test for ldapTestResponse to be != null ? 
</blockquote></details>

That would happen only when there is a delegate exception. That is already handled before we even come to this call.
So, not needed.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 76 at r5](https://reviewable.io/reviews/harness/harness-core/37042#-NB67fUC2-Y6_dqn8K3V:-NB67fUC2-Y6_dqn8K3W:b-lyv7mj) ([raw file](https://github.com/harness/harness-core/blob/2e6e4729279f28992fa31e7ce84e7382affdc3e4/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L76)):*
> ```Java
> import lombok.AllArgsConstructor;
> import lombok.extern.slf4j.Slf4j;
> import org.jetbrains.annotations.NotNull;
> ```

This import does'nt look right

**Comment by piyush-harness** [comment]
*[`950-delegate-tasks-beans/src/main/java/software/wings/helpers/ext/ldap/LdapSearch.java` line 188 at r5](https://reviewable.io/reviews/harness/harness-core/37042#-NB68-Wy73xEd0v3MWqk:-NB68-Wy73xEd0v3MWql:b-hrgj20) ([raw file](https://github.com/harness/harness-core/blob/2e6e4729279f28992fa31e7ce84e7382affdc3e4/950-delegate-tasks-beans/src/main/java/software/wings/helpers/ext/ldap/LdapSearch.java#L188)):*
> ```Java
>       } catch (Exception e) {
>         log.error("Error querying second time to LDAP server with old logic ", e);
>         throw e;
> ```

This will stop all other Group Sync if one query fails

**Review by piyush-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 76 at r5](https://reviewable.io/reviews/harness/harness-core/37042#-NB67fUC2-Y6_dqn8K3V:-NB6UkqMBimWISXBNCeF:bvpeo2n) ([raw file](https://github.com/harness/harness-core/blob/2e6e4729279f28992fa31e7ce84e7382affdc3e4/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L76)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This import does'nt look right
</blockquote></details>

Removed. Done.

**Comment by shashank-harness** [comment]
*[`950-delegate-tasks-beans/src/main/java/software/wings/helpers/ext/ldap/LdapSearch.java` line 188 at r5](https://reviewable.io/reviews/harness/harness-core/37042#-NB68-Wy73xEd0v3MWqk:-NB6UqB6A0ugvB7fnM00:b-qretv8) ([raw file](https://github.com/harness/harness-core/blob/2e6e4729279f28992fa31e7ce84e7382affdc3e4/950-delegate-tasks-beans/src/main/java/software/wings/helpers/ext/ldap/LdapSearch.java#L188)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This will stop all other Group Sync if one query fails
</blockquote></details>

its handled in catch statement from caller end

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37042)* status: :shipit: complete! ✓

**Comment by piyush-harness** [comment]
trigger codebasehashcheck

**Comment by piyush-harness** [comment]
trigger codebasehash

**Pull request merged**
