### PR TITLE
[fix]: [CDS-45418]: Adding tags and capabilities information in cf rollback objects

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes

We would have to do a migration, which will set required properties to autogenerated rollback states.
If FF is enabled then we will also filter by custom stack name and region (which is unique per stack).

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)

### CODE REVIEW

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: :shipit: complete! ✓

**Review by vlica-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: :shipit: complete! ✓

**Review by vlica-harness — DISMISSED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java` line 51 at r4](https://reviewable.io/reviews/harness/harness-core/39139#-NFO-vRc7MSiRV49UK1i:-NFO-vRc7MSiRV49UK1j:b-8pxako) ([raw file](https://github.com/harness/harness-core/blob/3e2c1466bace34618d2ce890226d74d1391d7605/390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java#L51)):*
> ```Java
>     log.info(String.format("%s Starting migration for accountId: %s", LOG_PREFIX, accountId));
> 
>     List<Workflow> workflows = WorkflowAndPipelineMigrationUtils.fetchAllWorkflowsForAccount(
> ```

Should we use an iterator? Customers would have too many workflows for memory.



_Code quote:_
```Java
fetchAllWorkflowsForAccount
```

**Review by sainath-b — DISMISSED** [review]

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 1 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java` line 51 at r4](https://reviewable.io/reviews/harness/harness-core/39139#-NFO-vRc7MSiRV49UK1i:-NFOWIlv0_YTRK2wwwFE:b-hcgi8o) ([raw file](https://github.com/harness/harness-core/blob/3e2c1466bace34618d2ce890226d74d1391d7605/390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java#L51)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Should we use an iterator? Customers would have too many workflows for memory.
</blockquote></details>

Done, fetching them with page requests with size 1000

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 1 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 3 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 6 of 9 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139#-:-NFOj84--JeoTSYzMWUu:bnfp4nl)* status: 3 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java` line 2 at r7](https://reviewable.io/reviews/harness/harness-core/39139#-NFOo7Ys8pmxw0iKzhm2:-NFOo7Ys8pmxw0iKzhm3:b-u4n5sy) ([raw file](https://github.com/harness/harness-core/blob/3268e267a7ced3af0b1bc13e27da6395e0f4e46f/390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

nit: copyright year should be 2022
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 472 at r7](https://reviewable.io/reviews/harness/harness-core/39139#-NFOo-BZ0CFuqmXJbYgt:-NFOo-BZ0CFuqmXJbYgu:b7uncdi) ([raw file](https://github.com/harness/harness-core/blob/3268e267a7ced3af0b1bc13e27da6395e0f4e46f/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L472)):*
> ```Java
>       "FF to enable verbose logging for the manager process when secret gets evaluated", HarnessTeam.DEL),
>   CI_MFE_ENABLED("Feature flag is needed to test/control the microfrontend architecture for CI UI", HarnessTeam.CI),
>   CF_ROLLBACK_CUSTOM_STACK_NAME;
> ```

We need to add description and team for FF

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java` line 2 at r7](https://reviewable.io/reviews/harness/harness-core/39139#-NFOo7Ys8pmxw0iKzhm2:-NFOpap-1PfPwfYVFOxc:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3268e267a7ced3af0b1bc13e27da6395e0f4e46f/390-db-migration/src/main/java/io/harness/migrations/all/SetPropertiesToCloudformationRollbackStackSteps.java#L2)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: copyright year should be 2022
</blockquote></details>

Done
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 472 at r7](https://reviewable.io/reviews/harness/harness-core/39139#-NFOo-BZ0CFuqmXJbYgt:-NFOpfcBD0qAu82TJYog:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3268e267a7ced3af0b1bc13e27da6395e0f4e46f/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L472)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We need to add description and team for FF
</blockquote></details>

Done

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139#-:-NFOqhSF0j3aeZTu-58r:bnfp4nl)* status: 4 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 5 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 5 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by tmacari-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139)* status: 5 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39139#-:-NFSfvhtEauqRwtU3x4L:bnfp4nl)* status: 5 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Comment by tmacari-harness** [comment]
trigger codebasehash

**Pull request merged**
