### PR TITLE
feat: [CDS-77507]: Added Open API for getting individual schema

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added Open Api to fetch Individual Schemas

Sample Response 
```
{
    "data": {
        "title": "TasSwapRollbackStepNode",
        "type": "object",
        "required": [
            "identifier",
            "name",
            "type"
        ],
        "properties": {
            "description": {
                "type": "string",
                "desc": "This is the description for TasSwapRollbackStepNode"
            },
            "enforce": {
                "$ref": "#/definitions/pipeline/common/PolicyConfig"
            },
            "failureStrategies": {
                "oneOf": [
                    {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/pipeline/common/FailureStrategyConfig"
                        }
                    },
                    {
                        "type": "string",
                        "pattern": "^<\\+input>$",
                        "minLength": 1
                    }
                ]
            },
            "identifier": {
                "type": "string",
                "pattern": "^[a-zA-Z_][0-9a-zA-Z_]{0,127}$"
            },
            "name": {
                "type": "string",
                "pattern": "^[a-zA-Z_0-9-.][-0-9a-zA-Z_\\s.]{0,127}$"
            },
            "strategy": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/pipeline/common/StrategyConfig"
                    },
                    {
                        "type": "string",
                        "pattern": "^<\\+input>$",
                        "minLength": 1
                    }
                ]
            },
            "timeout": {
                "type": "string",
                "pattern": "^(([1-9])+\\d+[s])|(((([1-9])+\\d*[mhwd])+([\\s]?\\d+[smhwd])*)|(.*<\\+.*>(?!.*\\.executionInput\\(\\)).*)|(^$))$"
            },
            "type": {
                "type": "string",
                "enum": [
                    "SwapRollback"
                ]
            },
            "when": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/pipeline/common/StepWhenCondition"
                    },
                    {
                        "type": "string",
                        "pattern": "^<\\+input>$",
                        "minLength": 1
                    }
                ]
            }
        },
        "$schema": "http://json-schema.org/draft-07/schema#",
        "allOf": [
            {
                "if": {
                    "properties": {
                        "type": {
                            "const": "SwapRollback"
                        }
                    }
                },
                "then": {
                    "properties": {
                        "spec": {
                            "$ref": "#/definitions/pipeline/steps/cd/TasSwapRollbackStepInfo"
                        }
                    }
                }
            }
        ],
        "definitions": {
            "pipeline": {
                "common": {
                    "PolicyConfig": {
                        "title": "PolicyConfig",
                        "type": "object",
                        "required": [
                            "policySets"
                        ],
                        "properties": {
                            "policySets": {
                                "oneOf": [
                                    {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "^<\\+input>((\\.)((executionInput\\(\\))|(allowedValues|default|regex)\\(.+?\\)))*$",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "description": {
                                "desc": "This is the description for PolicyConfig"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "FailureStrategyConfig": {
                        "title": "FailureStrategyConfig",
                        "type": "object",
                        "required": [
                            "onFailure"
                        ],
                        "properties": {
                            "onFailure": {
                                "$ref": "#/definitions/pipeline/common/OnFailureConfig"
                            },
                            "description": {
                                "desc": "This is the description for FailureStrategyConfig"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "OnFailureConfig": {
                        "title": "OnFailureConfig",
                        "type": "object",
                        "required": [
                            "action",
                            "errors"
                        ],
                        "properties": {
                            "action": {
                                "$ref": "#/definitions/pipeline/common/FailureStrategyActionConfig"
                            },
                            "errors": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "Unknown",
                                        "AllErrors",
                                        "Authentication",
                                        "Connectivity",
                                        "Timeout",
                                        "Authorization",
                                        "Verification",
                                        "DelegateProvisioning",
                                        "PolicyEvaluationFailure",
                                        "InputTimeoutError",
                                        "ApprovalRejection",
                                        "DelegateRestart",
                                        "UserMarkedFailure"
                                    ]
                                }
                            },
                            "description": {
                                "desc": "This is the description for OnFailureConfig"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "FailureStrategyActionConfig": {
                        "title": "FailureStrategyActionConfig",
                        "type": "object",
                        "required": [
                            "type"
                        ],
                        "discriminator": "type",
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "Ignore",
                                    "Retry",
                                    "MarkAsSuccess",
                                    "Abort",
                                    "StageRollback",
                                    "StepGroupRollback",
                                    "PipelineRollback",
                                    "ManualIntervention",
                                    "ProceedWithDefaultValues",
                                    "MarkAsFailure",
                                    "RetryStepGroup"
                                ]
                            },
                            "description": {
                                "desc": "This is the description for FailureStrategyActionConfig"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "StrategyConfig": {
                        "title": "StrategyConfig",
                        "type": "object",
                        "properties": {
                            "matrix": {
                                "oneOf": [
                                    {
                                        "$ref": "#/definitions/pipeline/common/ParameterFieldMatrixConfigInterface"
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "^<\\+input>((\\.)((executionInput\\(\\))|(allowedValues|default|regex)\\(.+?\\)))*$",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "parallelism": {
                                "oneOf": [
                                    {
                                        "type": "integer",
                                        "format": "int32",
                                        "minimum": 0
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "repeat": {
                                "$ref": "#/definitions/pipeline/common/HarnessForConfig"
                            },
                            "description": {
                                "desc": "This is the description for StrategyConfig"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "allOf": [
                            {
                                "oneOf": [
                                    {
                                        "required": [
                                            "repeat"
                                        ]
                                    },
                                    {
                                        "required": [
                                            "parallelism"
                                        ]
                                    },
                                    {
                                        "required": [
                                            "matrix"
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    "ParameterFieldMatrixConfigInterface": {
                        "title": "ParameterFieldMatrixConfigInterface",
                        "type": "object",
                        "properties": {
                            "defaultValue": {
                                "$ref": "#/definitions/pipeline/common/MatrixConfigInterface"
                            },
                            "executionInput": {
                                "type": "boolean"
                            },
                            "expression": {
                                "type": "boolean"
                            },
                            "expressionValue": {
                                "type": "string"
                            },
                            "inputSetValidator": {
                                "$ref": "#/definitions/pipeline/common/InputSetValidator"
                            },
                            "jsonResponseField": {
                                "type": "boolean"
                            },
                            "responseField": {
                                "type": "string"
                            },
                            "typeString": {
                                "type": "boolean"
                            },
                            "value": {
                                "$ref": "#/definitions/pipeline/common/MatrixConfigInterface"
                            },
                            "description": {
                                "desc": "This is the description for ParameterFieldMatrixConfigInterface"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "MatrixConfigInterface": {
                        "title": "MatrixConfigInterface",
                        "type": "object",
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "properties": {
                            "description": {
                                "desc": "This is the description for MatrixConfigInterface"
                            }
                        }
                    },
                    "InputSetValidator": {
                        "title": "InputSetValidator",
                        "type": "object",
                        "properties": {
                            "parameters": {
                                "type": "string"
                            },
                            "validatorType": {
                                "type": "string",
                                "enum": [
                                    "ALLOWED_VALUES",
                                    "REGEX"
                                ]
                            },
                            "description": {
                                "desc": "This is the description for InputSetValidator"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "HarnessForConfig": {
                        "title": "HarnessForConfig",
                        "type": "object",
                        "properties": {
                            "end": {
                                "oneOf": [
                                    {
                                        "type": "integer",
                                        "format": "int32",
                                        "minimum": 0
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "items": {
                                "oneOf": [
                                    {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "maxConcurrency": {
                                "oneOf": [
                                    {
                                        "type": "integer",
                                        "format": "int32",
                                        "minimum": 0
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "partitionSize": {
                                "oneOf": [
                                    {
                                        "type": "integer",
                                        "format": "int32",
                                        "minimum": 0
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "start": {
                                "oneOf": [
                                    {
                                        "type": "integer",
                                        "format": "int32",
                                        "minimum": 0
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "times": {
                                "oneOf": [
                                    {
                                        "type": "integer",
                                        "format": "int32",
                                        "minimum": 0
                                    },
                                    {
                                        "type": "string",
                                        "pattern": "(<\\+.+>.*)",
                                        "minLength": 1
                                    }
                                ]
                            },
                            "unit": {
                                "type": "string",
                                "enum": [
                                    "Percentage",
                                    "Count"
                                ]
                            },
                            "description": {
                                "desc": "This is the description for HarnessForConfig"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "allOf": [
                            {
                                "oneOf": [
                                    {
                                        "required": [
                                            "times"
                                        ]
                                    },
                                    {
                                        "required": [
                                            "items"
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    "StepWhenCondition": {
                        "title": "StepWhenCondition",
                        "type": "object",
                        "required": [
                            "stageStatus"
                        ],
                        "properties": {
                            "condition": {
                                "type": "string",
                                "pattern": "^(?!<\\+input>.*\\.executionInput\\(\\)(.*)$)"
                            },
                            "stageStatus": {
                                "type": "string",
                                "enum": [
                                    "Success",
                                    "Failure",
                                    "All"
                                ]
                            },
                            "description": {
                                "desc": "This is the description for StepWhenCondition"
                            }
                        },
                        "$schema": "http://json-schema.org/draft-07/schema#"
                    },
                    "StepSpecType": {
                        "title": "StepSpecType",
                        "type": "object",
                        "discriminator": "type",
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "properties": {
                            "description": {
                                "desc": "This is the description for StepSpecType"
                            }
                        }
                    }
                },
                "steps": {
                    "cd": {
                        "TasSwapRollbackStepInfo": {
                            "title": "TasSwapRollbackStepInfo",
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pipeline/common/StepSpecType"
                                },
                                {
                                    "type": "object",
                                    "required": [
                                        "upsizeInActiveApp"
                                    ],
                                    "properties": {
                                        "delegateSelectors": {
                                            "oneOf": [
                                                {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                },
                                                {
                                                    "type": "string",
                                                    "pattern": "(<\\+.+>.*)",
                                                    "minLength": 1
                                                }
                                            ]
                                        },
                                        "upsizeInActiveApp": {
                                            "oneOf": [
                                                {
                                                    "type": "boolean"
                                                },
                                                {
                                                    "type": "string"
                                                }
                                            ]
                                        }
                                    }
                                }
                            ],
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "type": "object",
                            "required": [
                                "upsizeInActiveApp"
                            ],
                            "properties": {
                                "delegateSelectors": {
                                    "oneOf": [
                                        {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        {
                                            "type": "string",
                                            "pattern": "(<\\+.+>.*)",
                                            "minLength": 1
                                        }
                                    ]
                                },
                                "upsizeInActiveApp": {
                                    "oneOf": [
                                        {
                                            "type": "boolean"
                                        },
                                        {
                                            "type": "string"
                                        }
                                    ]
                                },
                                "description": {
                                    "desc": "This is the description for TasSwapRollbackStepInfo"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by mankrit-singh** [comment]
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 662 at r2](https://reviewable.io/reviews/harness/harness-core/51913#-NcSpsoA2RStzKcU5Az-:-NcVTf8y3JIllhVdjQae:bakkdj5) ([raw file](https://github.com/harness/harness-core/blob/310b1a5175a877b12f8841fdaa54a313670b4af9/pipeline-service/contracts/openapi/v1/openapi.yaml#L662)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we dont need org/project id
</blockquote></details>

If the entity (pipeline) is scoped to project then ideally org / project should be present. Also, without this in the path, there would be significant ingress changes to support this 1 api separately

**Review by mankrit-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 687 at r2](https://reviewable.io/reviews/harness/harness-core/51913#-NcSq-sc6xayKsSNDwVJ:-NcVU1UG9ueHW6q77oPH:b-k97f4l) ([raw file](https://github.com/harness/harness-core/blob/310b1a5175a877b12f8841fdaa54a313670b4af9/pipeline-service/contracts/openapi/v1/openapi.yaml#L687)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

Yes, this is how account ID is passed when x-api-key is not used (ie. while using Bearer Token)
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2201 at r2](https://reviewable.io/reviews/harness/harness-core/51913#-NcSq4Dl-YFcBgf5zHP8:-NcVU8Gj81S9ew9GTRVZ:bes2ct5) ([raw file](https://github.com/harness/harness-core/blob/310b1a5175a877b12f8841fdaa54a313670b4af9/pipeline-service/contracts/openapi/v1/openapi.yaml#L2201)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are changing id for all?
</blockquote></details>

Stoplight does this sometimes, it won't matter

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 4 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java` line 39 at r5](https://reviewable.io/reviews/harness/harness-core/51913#-Ncat6z25qpsNC5NiE5t:-Ncat6z25qpsNC5NiE5u:b-ghpwn0) ([raw file](https://github.com/harness/harness-core/blob/8adb771ab99ba35e5e111d4a38162e059d35cd4a/pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java#L39)):*
> ```Java
> @Slf4j
> public class SchemasApiImpl implements SchemasApi {
>   private final StaticSchemaParserFactory staticSchemaParserFactory;
> ```

we should be using some static schema service here. The service should internally handle everything related to factory and how to manage stuff

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913#-:-NcazAhnAmyCC0zUSOgy:bnfp4nl)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 677 at r3](https://reviewable.io/reviews/harness/harness-core/51913#gh-1303851013:-Ncaz4ep54gq1KKrdpl9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd7b675232f6934460ce345eb9c1d9569469e95c/pipeline-service/contracts/openapi/v1/openapi.yaml#L677)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

you can use the common parameter for this (see any other API in pipeline service for ref)
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java` line 39 at r5](https://reviewable.io/reviews/harness/harness-core/51913#-Ncat6z25qpsNC5NiE5t:-Ncaz6FR7LdxYz53yErg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8adb771ab99ba35e5e111d4a38162e059d35cd4a/pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should be using some static schema service here. The service should internally handle everything related to factory and how to manage stuff
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/51913#gh-1303851651:-Ncaz7EYDsvAoL3FIX1E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd7b675232f6934460ce345eb9c1d9569469e95c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L96)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

is this still needed?
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/51913#-Ncb2FsQ0PPCZt2h4F6y:-Ncb2FsQ0PPCZt2h4F6z:b-pyu2tg) ([raw file](https://github.com/harness/harness-core/blob/e5517d143ea46a9e352ac7a8d7f49ad4916af464/pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java#L37)):*
> ```Java
>   @Override
>   public Response getIndividualStaticSchema(
>       String harnessAccount, String nodeGroup, String nodeType, String nodeGroupDifferentiator) {
> ```

use enums here

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 5 file(s) to review. 2. unresolved discussions.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51913)* status: 5 file(s) to review. 3. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/51913#-Ncb2FsQ0PPCZt2h4F6y:-NcfXobk8Qa_6c848Rj4:b-vx3ps2) ([raw file](https://github.com/harness/harness-core/blob/e5517d143ea46a9e352ac7a8d7f49ad4916af464/pipeline-service/service/src/main/java/io/harness/pms/schema/SchemasApiImpl.java#L37)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use enums here
</blockquote></details>

Done. Added enums in API, 
Will add enums in the parser

**Review by mankrit-singh — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger ut7

**Comment by utkarshchoubey-harness** [comment]
trigger ut0

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
