### PR TITLE
fix: [CDS-79588]: handle binaryResponseData

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53025)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger messagecheck

**Comment by tmacari-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53025#-:-NegO0gq6FtJTKQUQ6yE:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java` line 257 at r2](https://reviewable.io/reviews/harness/harness-core/53025#-NegMvnp8TiEhUy1Is8q:-NegMvnp8TiEhUy1Is8r:b-1gp9qw) ([raw file](https://github.com/harness/harness-core/blob/f739a3e0272c2ea973bbff7925e3f9584e52a940/pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java#L257)):*
> ```Java
>       updatedResponseList.addResponse(PluginCreationResponseWrapper.newBuilder()
>                                           .setStepInfo(responseV2.getStepInfo())
>                                           .setShouldSkip(responseV2.getShouldSkip())
> ```

QQ: What does `shouldSkip` refer to?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53025)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java` line 257 at r2](https://reviewable.io/reviews/harness/harness-core/53025#-NegMvnp8TiEhUy1Is8q:-NegTzyL-INFRsJt8Lgf:b-8ooxxh) ([raw file](https://github.com/harness/harness-core/blob/f739a3e0272c2ea973bbff7925e3f9584e52a940/pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java#L257)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

QQ: What does `shouldSkip` refer to?
</blockquote></details>

it will not create a ContainerDefinitionInfo is step should be skipped.
Look at io/harness/steps/container/utils/ContainerStepV2DefinitionCreator.java:58  and io/harness/cdng/plugininfoproviders/AwsCdkRollbackPluginInfoProvider.java:49

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53025)* status: 1. unresolved discussions.

**Comment by tmacari-harness** [comment]
trigger review

**Pull request merged**
