### PR TITLE
[feat]: [PIE-8244]: Adopting new SPEC for matrix strategy with YAML V1

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)

### CODE REVIEW

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 14 of 21 files at r1, 14 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: 29 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: 36 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 21 files at r1, 8 of 15 files at r2, 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: 18 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/test/java/io/harness/steps/matrix/MatrixConfigServiceTest.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQW6E72SrKmCyJLDkE:-NPQW6E72SrKmCyJLDkF:bcbfisx) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/878-ng-common-utilities/src/test/java/io/harness/steps/matrix/MatrixConfigServiceTest.java#L33)):*
> ```Java
> 
> public class MatrixConfigServiceTest extends NGCommonUtilitiesTestBase {
>   @Inject MatrixConfigService matrixConfigService;
> ```

do you need the injected service? can it be category test?
___
*[`878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1Test.java` line 32 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWA9T7E105yCcgIoE:-NPQWA9T7E105yCcgIoF:brnseaw) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1Test.java#L32)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class MatrixConfigServiceV1Test extends NGCommonUtilitiesTestBase {
> ```

can it be category test?
___
*[`878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/StrategyStepV1Test.java` line 46 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWCtO1Ci4zNXhXtiL:-NPQWCtO1Ci4zNXhXtiM:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/StrategyStepV1Test.java#L46)):*
> ```Java
> import org.mockito.Mock;
> 
> public class StrategyStepV1Test extends NGCommonUtilitiesTestBase {
> ```

same as above
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 36 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWRrK9V-rcTnLguMY:-NPQWRrK9V-rcTnLguMZ:b-3vz1le) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L36)):*
> ```Java
> 
> @Singleton
> public class MatrixConfigServiceHelper {
> ```

add team annotation
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWUDx5lO3xaiDDBYg:-NPQWUDx5lO3xaiDDBYh:bldvllk) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L70)):*
> ```Java
>   }
> 
>   public StrategyInfo expandJsonNode(List<String> keys, Map<String, AxisConfig> axes,
> ```

add comments
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 152 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWZKi3QTFA8xmHp5c:-NPQWZKi3QTFA8xmHp5d:b-hoy8xo) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L152)):*
> ```Java
>   }
> 
>   private boolean shouldExclude(List<ExcludeConfig> exclude, Map<String, String> currentCombinationRef) {
> ```

what should it exclude?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWaXD9tETSeCO50bz:-NPQWaXD9tETSeCO50c-:b-22a7cx) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L174)):*
> ```Java
>   }
> 
>   private void handleAxes(String key, Map<String, String> currentCombinationRef, Map<String, AxisConfig> primitiveAxes,
> ```

comments missing
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 197 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWbomCDKxpjD4cpy8:-NPQWbomCDKxpjD4cpy9:b-sq5xc6) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L197)):*
> ```Java
>   }
> 
>   private void handleExpression(String key, Map<String, String> currentCombinationRef, Map<String, AxisConfig> axes,
> ```

comments add
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyAbstractStepParameters.java` line 12 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWd-u6lyor6Eh-Yrs:-NPQWd-u6lyor6Eh-Yrt:b121nxv) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyAbstractStepParameters.java#L12)):*
> ```Java
> import io.harness.pms.sdk.core.steps.io.StepParameters;
> 
> public class StrategyAbstractStepParameters implements StepParameters {}
> ```

team annotation missing
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStepParameters.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWfDk0OSggwwbWkQG:-NPQWfDk0OSggwwbWkQH:b6zaofh) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStepParameters.java#L19)):*
> ```Java
> @Data
> @Builder
> public class StrategyStepParameters extends StrategyAbstractStepParameters {
> ```

team annotation
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWgLOC-4oeDrl_D7X:-NPQWgLOC-4oeDrl_D7Y:b-483tb4) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1.java#L24)):*
> ```Java
> 
> @Singleton
> public class MatrixConfigServiceV1 implements StrategyConfigServiceV1 {
> ```

annotation plus add comments to methods
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyConfigServiceV1.java` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWjXLEeLpmSLsGmEh:-NPQWjXLEeLpmSLsGmEi:blrje9g) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyConfigServiceV1.java#L18)):*
> ```Java
> import java.util.Optional;
> 
> public interface StrategyConfigServiceV1 {
> ```

annotation
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyStepParametersV1.java` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWlBA-ymalBp1f7PM:-NPQWlBA-ymalBp1f7PN:blrje9g) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyStepParametersV1.java#L20)):*
> ```Java
> @Data
> @Builder
> public class StrategyStepParametersV1 extends StrategyAbstractStepParameters {
> ```

annotation
___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/strategy/v1/StrategyConfigPlanCreatorV1Test.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWnZd0ij6uxtJZQB5:-NPQWnZd0ij6uxtJZQB6:b-mdc1fx) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/strategy/v1/StrategyConfigPlanCreatorV1Test.java#L55)):*
> ```Java
> import org.mockito.MockitoAnnotations;
> 
> public class StrategyConfigPlanCreatorV1Test extends PmsSdkCoreTestBase {
> ```

annotation, category test?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: 20 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/test/java/io/harness/steps/matrix/MatrixConfigServiceTest.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQW6E72SrKmCyJLDkE:-NPQmuOJATq79abmvwmv:b-kou3tj) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/878-ng-common-utilities/src/test/java/io/harness/steps/matrix/MatrixConfigServiceTest.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do you need the injected service? can it be category test?
</blockquote></details>

Done. Not needed. Added AllArgsConstructor in the class.
___
*[`878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1Test.java` line 32 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWA9T7E105yCcgIoE:-NPQn1cD9PT1CKzVhPNW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1Test.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can it be category test?
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/StrategyStepV1Test.java` line 46 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWCtO1Ci4zNXhXtiL:-NPQn9HG3GuW_RIS74RI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/878-ng-common-utilities/src/test/java/io/harness/steps/matrix/v1/StrategyStepV1Test.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.



_Code quote:_
```Java
StrategyStepV1Test
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 36 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWRrK9V-rcTnLguMY:-NPQnWScBDVdzUy9ia6_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add team annotation
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWUDx5lO3xaiDDBYg:-NPQo5sr-2qLnd3AqRDY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 152 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWZKi3QTFA8xmHp5c:-NPQoDUL9fIvzZ5Zf4v2:b-qfrtxe) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L152)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what should it exclude?
</blockquote></details>

Checking if the currentCombinationRef should be excluded. Added the comment.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWaXD9tETSeCO50bz:-NPQp6G19H_BEMUlUVld:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L174)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comments missing
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 197 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWbomCDKxpjD4cpy8:-NPQp6frEmeobdM8TIz6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

comments add
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyAbstractStepParameters.java` line 12 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWd-u6lyor6Eh-Yrs:-NPQpTyiBUAu0YgVvOTx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyAbstractStepParameters.java#L12)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

team annotation missing
</blockquote></details>

Done
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStepParameters.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWfDk0OSggwwbWkQG:-NPQpbyjAI-Ctoj-bbz2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStepParameters.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

team annotation
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWgLOC-4oeDrl_D7X:-NPQq1xzEmpbQDRipprD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/MatrixConfigServiceV1.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

annotation plus add comments to methods
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyConfigServiceV1.java` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWjXLEeLpmSLsGmEh:-NPQq7CX1T6IpE1f7vaV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyConfigServiceV1.java#L18)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

annotation
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyStepParametersV1.java` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWlBA-ymalBp1f7PM:-NPQqH3c6HP15ixHjbwS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/v1/StrategyStepParametersV1.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

annotation
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/strategy/v1/StrategyConfigPlanCreatorV1Test.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/44331#-NPQWnZd0ij6uxtJZQB5:-NPQqR-t6e-PHBd1_0xG:b-phoxmf) ([raw file](https://github.com/harness/harness-core/blob/9f9000ac9b26470f0d414a03b18db4109c9de086/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/strategy/v1/StrategyConfigPlanCreatorV1Test.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

annotation, category test?
</blockquote></details>

we need to inject the kryoSerialiser so it can not be Category test. I think we can create one testRule to inject kryo and generally used classes. So that rule can be used instead of this. But that can be done later in other PRs.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 21 files at r1, 3 of 15 files at r2, 5 of 7 files at r4, 6 of 10 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: 10 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: 10 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 10 files at r6, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331)* status: Waiting on team(s): sto.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 21 files at r1, 10 of 15 files at r2, 7 of 7 files at r4, 6 of 10 files at r6, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44331#-:-NPRXMMd-k-oGm8oZFOv:bnfp4nl)* status: Waiting on team(s): sto.

**Review by r0610205 — APPROVED** [review]

**Pull request merged**
