### PR TITLE
[feat]:[pl-29066]: adding repo filter for pipeline listing

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
1. Added repo filter for pipeline listing, tested out the filter repo logic via postman for pipeline listing in gitx project
2. For adding repo and branch filter in case of deployments and execution, this is already present and from the UI when the summary api gets called, we need populate the repo as well

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: :shipit: complete! ✓

**Review by senjucanon2 — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: :shipit: complete! ✓

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEnoQRT0ycb2nZCmOgT:-NEnoQRT0ycb2nZCmOgU:bpnkv8l) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L210)):*
> ```Java
>           JsonUtils.readTree(pipelineFilter.getModuleProperties().toJson()), "filters", criteria);
>     }
>     if (pipelineFilter.getRepoName() != null && EmptyPredicate.isNotEmpty(pipelineFilter.getRepoName())) {
> ```

pipelineFilter.getRepoName() != null 
this condition is not required if you are using isNotEmpty



_Code quote:_
```Java
pipelineFilter.getRepoName() != null
```

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEnoQRT0ycb2nZCmOgT:-NEnp1b4EAwx-8zMeAPD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L210)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

pipelineFilter.getRepoName() != null 
this condition is not required if you are using isNotEmpty
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEnivYW-L_Vb66SxhSZ:-NEnivYW-L_Vb66SxhS_:b-5cw1cb) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L107)):*
> ```Java
>                  .field(PipelineEntityKeys.accountId)
>                  .field(PipelineEntityKeys.orgIdentifier)
>                  .field(PipelineEntityKeys.projectIdentifier)
> ```

Please add screenshot of explain query to the PR if this index is really required



_Code quote:_
```Java
        .add(CompoundMongoIndex.builder()
                 .name("accountId_orgId_projectId_repo")
                 .field(PipelineEntityKeys.accountId)
                 .field(PipelineEntityKeys.orgIdentifier)
                 .field(PipelineEntityKeys.projectIdentifier)
                 .field(PipelineEntityKeys.repo)
                 .build())
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEoDXU9C-klnnpJ3tts:-NEoDXU9C-klnnpJ3ttt:bgypicd) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L139)):*
> ```Java
>   Boolean notifyOnlyMe;
>   String branch;
>   String repo;
> ```

Do we really need it?



_Code quote:_
```Java
  String branch;
  String repo;
```

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: 1 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEoDXU9C-klnnpJ3tts:-NEoLMQuAQpyWVbeHRDH:bumwflb) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L139)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Do we really need it?
</blockquote></details>

we will need repo for sure and we can take the branch from gitEntity info
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEnivYW-L_Vb66SxhSZ:-NEoLdOIA3Uw46hAwIcS:b-v84l3j) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L107)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please add screenshot of explain query to the PR if this index is really required
</blockquote></details>

this is the query run db.getCollection("pipelinesPMS").find({ accountId: "kmpySmUISimoRrJL6NL73w", orgIdentifier: "default", projectIdentifier: "GitX_Remote" , repo:"testRepo"}).explain("executionStats")

and the

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: 8 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEnivYW-L_Vb66SxhSZ:-NEox_TkCUyNqPN38juU:bucudv7) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java#L107)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

this is the query run db.getCollection("pipelinesPMS").find({ accountId: "kmpySmUISimoRrJL6NL73w", orgIdentifier: "default", projectIdentifier: "GitX_Remote" , repo:"testRepo"}).explain("executionStats")

and the


</blockquote></details>

upon updating to sorting index, here is the executionStats, now its picking up the newly added index and working as expected

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/38952#-NEoDXU9C-klnnpJ3tts:-NEotPGX3AbdUFJjYCeE:be19l4b) ([raw file](https://github.com/harness/harness-core/blob/e7b5253dd0c3537d2b7c234b93e0ed0ccc2886f0/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L139)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we will need repo for sure and we can take the branch from gitEntity info
</blockquote></details>

removed the branch as well, as we can take this also from gitEntity

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 4 of 6 files at r4, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: 1 change requests. 1. unresolved discussions.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 4 of 6 files at r4, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 4 of 6 files at r4, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38952)* status: :shipit: complete! ✓

**Pull request merged**
