### PR TITLE
[feat]: [CDS-85139]: set cd running stages to fetch from execution info

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- For formatting running stages set, since CD stages running in execution phase would have service step completed, hence we will have cd metadata saved in stage execution info. 
- Flow is similar to finished stages for now, but a separate handling can be added for specific type of stages if required in future.
- Running looping cd stages didn't have module info populated in stage nodes. Updated our check.
- Upcoming looping stages were being saved with <+strategy.identifierPostfix>. But it wasn't the case in layout nodes for this stage.
- Coverage:
a. (running stages): when upcoming stage has all cd stages, no cd stages, cd with generic stage, stages with execution identifier absent, when stage execution info call fails, when stage execution info returns partial map.
b. (future/running CD looping stages): covered logic of parsing CD stages. Removed looping identifier when saving looping cd stages to plan creation.

- Testing: 
a. [CD Stage with approval in execution phase and infra as expression when running should have expressions resolved in notifications](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21563637966/Improved+harness+approval+notifications#:~:text=13-,1%20Cd%20stage,-%2C%20followed%20by%20CD)
b. [Parallel CD Stages with approval in execution phase and expressions when running should have expressions resolved in notifications](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21563637966/Improved+harness+approval+notifications#:~:text=15-,Approval%20stage,-%E2%86%92%20parallel%20CD%20stages) - when upcoming should have expressions 
c. [Looping CD Stages with approval in execution phase and expressions when running should have expressions resolved in notifications](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21563637966/Improved+harness+approval+notifications#:~:text=16-,Approval%20stage,-%E2%86%92%20parallel%20CD%20stages) - when upcoming should have expressions
d. Approval stages
e. Custom stage with approval

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56459)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger ut1, ut3

**Review by abhinavmittal-harness — DISMISSED** [review]
LGTM

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56459#-:-NlMSkna5Ov8qVOug0bt:bb6ywmx)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger review

**Comment by naman-goenka** [comment]
trigger uts

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56459)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
trigger ut8, ut9

**Review by puthrayaharness — APPROVED** [review]

**Comment by naman-goenka** [comment]
trigger review

**Pull request merged**
