### PR TITLE
feat: [PL-30072]: Reduce data loaded by listAllAccounts using projection

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
listAllAccounts is loading all fields for account object, created different methods with project to list all accounts, so that data loaded in memory is low.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1166 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICohNE6ZepTbi-ZCFx:-NICohNE6ZepTbi-ZCFy:b-nrq6o7) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1166)):*
> ```Java
> 
>   @Override
>   public Query<Account> getAllAccountWithDefaultsQuery() {
> ```

getBasicAccountQuery()
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1175 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICp6vz5oTYoFa8K9Uq:-NICp6vz5oTYoFa8K9Ur:b-f7ba5t) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1175)):*
> ```Java
> 
>   @Override
>   public List<Account> listAllAccountWithDefaultsWithLicenseInfo() {
> ```

Do we need this method?
Also, can we remove all methods which fetch complete Account object to prevent people from using it in future.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1186 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICowh08g2WXNbd3M1S:-NICowh08g2WXNbd3M1T:b-145jio) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1186)):*
> ```Java
> 
>   @Override
>   public Query<Account> getAllAccountWithDefaultsWithEncryptedLicenseInfoQuery() {
> ```

getBasicAccountWithLicenseInfoQuery()
___
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 264 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICpaa750a5uKpSonZ2:-NICpaa750a5uKpSonZ3:b-7b48j2) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L264)):*
> ```Java
>   boolean isImmutableDelegateEnabled(String accountId);
> 
>   boolean checkIfMultipleAccountsExists();
> ```

doMultipleAccountsExist()
___
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 266 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICpYf44cFzeDEO8c7b:-NICpYf44cFzeDEO8c7c:b-2sqsw9) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L266)):*
> ```Java
>   boolean checkIfMultipleAccountsExists();
> 
>   List<AccountDTO> listAllAccountsDTO();
> ```

getAllAccounts()

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 3 of 14 files at r4, 15 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: 21 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1166 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICohNE6ZepTbi-ZCFx:-NID2AxiA5Qi4LHyKBSu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1166)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getBasicAccountQuery()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1175 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICp6vz5oTYoFa8K9Uq:-NID2Coe64N84KPBwgOY:b-ygmlfl) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1175)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need this method?
Also, can we remove all methods which fetch complete Account object to prevent people from using it in future.
</blockquote></details>

It includes projection, the query which loads whole account object is listAllAccounts() that has been removed
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1186 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICowh08g2WXNbd3M1S:-NID2N2yCYv8UqCd8kln:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1186)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getBasicAccountWithLicenseInfoQuery()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 264 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICpaa750a5uKpSonZ2:-NID2NXy9ZpH78uPEpya:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L264)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

doMultipleAccountsExist()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/intfc/AccountService.java` line 266 at r3](https://reviewable.io/reviews/harness/harness-core/40930#-NICpYf44cFzeDEO8c7b:-NID2NofED2rqfpfwrM-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d5decb491c7e41f597a4e2dd89d75329296738/400-rest/src/main/java/software/wings/service/intfc/AccountService.java#L266)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getAllAccounts()
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, 1 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: 21 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1105 at r5](https://reviewable.io/reviews/harness/harness-core/40930#-NID3Dd1BuJf1vTpiE6T:-NID3Dd1BuJf1vTpiE6U:b-aqysax) ([raw file](https://github.com/harness/harness-core/blob/a11753f426ce74b4e5cb622c9fc844094282de96/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1105)):*
> ```Java
> 
>   @Override
>   public Query<Account> getAllAccountsQuery() {
> ```

Should we have this method? It will load all accounts with all info
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1131 at r5](https://reviewable.io/reviews/harness/harness-core/40930#-NID3SrJ4Ft9rgGtzNOp:-NID3SrJ4Ft9rgGtzNOq:b-kq4n3p) ([raw file](https://github.com/harness/harness-core/blob/1926dec9adbf672aa9af8591fa8c70f3ad6a23cd/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1131)):*
> ```Java
> 
>   @Override
>   public List<Account> listAllAccountWithDefaultsWithoutLicenseInfo() {
> ```

getBasicAccountsWithoutLicenseInfo()
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1141 at r5](https://reviewable.io/reviews/harness/harness-core/40930#-NID3e8h5gSYsdZBj99g:-NID3e8h5gSYsdZBj99h:b3xfq6f) ([raw file](https://github.com/harness/harness-core/blob/1926dec9adbf672aa9af8591fa8c70f3ad6a23cd/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1141)):*
> ```Java
> 
>   @Override
>   public List<Account> listAllAccountWithDefaultsWithLicenseInfo() {
> ```

getBasicAccountsWithLicenseInfo

What do you think if we have 1 method

getAccountsWithBasicInfo(boolean includeLicenseInfo)

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: 36 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1105 at r5](https://reviewable.io/reviews/harness/harness-core/40930#-NID3Dd1BuJf1vTpiE6T:-NIDBC6z1auKq9DIzxMw:bkogmhr) ([raw file](https://github.com/harness/harness-core/blob/a11753f426ce74b4e5cb622c9fc844094282de96/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1105)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we have this method? It will load all accounts with all info
</blockquote></details>

iterator will be used on this query, but what will we do for those classes which require all accounts with all info, maybe instead of query we can return iterator only.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1131 at r5](https://reviewable.io/reviews/harness/harness-core/40930#-NID3SrJ4Ft9rgGtzNOp:-NIDBYcYE-DboFgfq6iH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1926dec9adbf672aa9af8591fa8c70f3ad6a23cd/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1131)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getBasicAccountsWithoutLicenseInfo()
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1141 at r5](https://reviewable.io/reviews/harness/harness-core/40930#-NID3e8h5gSYsdZBj99g:-NIDB_BWDaKO87R46Bb3:bb77hcx) ([raw file](https://github.com/harness/harness-core/blob/1926dec9adbf672aa9af8591fa8c70f3ad6a23cd/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1141)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getBasicAccountsWithLicenseInfo

What do you think if we have 1 method

getAccountsWithBasicInfo(boolean includeLicenseInfo)
</blockquote></details>

changed it, but this methods has changes in 21 files.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 19 of 21 files at r6, 2 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: 36 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930#-:-NIHdcxD82l7xWed1V6Q:bnfp4nl)* status: 36 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 13 of 16 files at r5, 19 of 21 files at r6, 2 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40930)* status: :shipit: complete! ✓

**Pull request merged**
