### PR TITLE
feat: [CDS-2993]: K8s release history interface

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
K8s declarative rollback requires a new release history implementation ([Spec here](https://harness.atlassian.net/wiki/spaces/CDP/pages/21075394834/Kubernetes+Declarative+Rollback)).

This change contains a new interface which will expose both the old & new implementation of k8s release history.
A separate PR will integrate this interface in the CG/NG K8s request handlers based on a FF. FF will be created to mitigate any risk since this change requires significant refactors across CG/NG.

- Existing Release/ReleaseHistory entities have been named as `Legacy` and will be removed along with the FF later.
- A handler takes care of some computations which were otherwise present in the request handlers.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Vulnerability 5 Vulnerabilities 
 * Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37222)

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 22 of 54 files at r1, 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 32 file(s) to review. 0 of 1 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sReleaseConstants.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/37222#-NBNbe3l9YtppDuQmEVT:-NBNbe3l9YtppDuQmEVU:bjibm2z) ([raw file](https://github.com/harness/harness-core/blob/d5f9a84b733cca1ddd3fbc83c177267e5dae6116/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sReleaseConstants.java#L26)):*
> ```Java
>   public static final Map<String, String> RELEASE_HARNESS_SECRET_TYPE =
>       Map.of(RELEASE_SECRET_TYPE_KEY, RELEASE_SECRET_TYPE_VALUE);
>   public static final Map<String, String> RELEASE_HARNESS_SECRET_LABELS =
> ```

nit: these names are a bit confusing ( i.e not clear if they are a map ), maybe append _MAP etc

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandler.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/37222#-NBN_hsG6MUqCUNz77E_:-NBN_hsG6MUqCUNz77Ea:b-e02091) ([raw file](https://github.com/harness/harness-core/blob/d5f9a84b733cca1ddd3fbc83c177267e5dae6116/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandler.java#L22)):*
> ```Java
>   IK8sReleaseHistory getReleaseHistory(KubernetesConfig kubernetesConfig, String releaseName) throws Exception;
>   IK8sRelease createRelease(String name, int number);
>   void saveRelease(KubernetesConfig kubernetesConfig, K8sReleasePersistDTO releasePersistDTO) throws Exception;
> ```

nit: add notnull annotations

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHelper.java` line 51 at r3](https://reviewable.io/reviews/harness/harness-core/37222#-NBO11xq73TJuLtDcGJw:-NBO11xq73TJuLtDcGJx:bmrnan4) ([raw file](https://github.com/harness/harness-core/blob/d5f9a84b733cca1ddd3fbc83c177267e5dae6116/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHelper.java#L51)):*
> ```Java
>   }
> 
>   String generateName(String releaseName, int releaseNumber) {
> ```

nit: this might be more readable 
``` String.join(RELEASE_NAME_DELIMITER, RELEASE_KEY, releaseName, releaseName);```

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandlerImpl.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/37222#-NBO0lPN9k7Gc4JGN-ES:-NBO0lPN9k7Gc4JGN-ET:bqqrzn7) ([raw file](https://github.com/harness/harness-core/blob/d5f9a84b733cca1ddd3fbc83c177267e5dae6116/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandlerImpl.java#L57)):*
> ```Java
>   @Override
>   public IK8sRelease createRelease(String name, int number) {
>     String status = K8sLegacyRelease.Status.InProgress.name();
> ```

should we move out the Status enum to somewhere else ?

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandlerImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/37222#-NBO3Mlc1_ZJHN8SFhoM:-NBO3Mlc1_ZJHN8SFhoN:b-ek04wq) ([raw file](https://github.com/harness/harness-core/blob/d5f9a84b733cca1ddd3fbc83c177267e5dae6116/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandlerImpl.java#L75)):*
> ```Java
> 
>   @Override
>   public void saveRelease(KubernetesConfig kubernetesConfig, K8sReleasePersistDTO releasePersistDTO) throws Exception {
> ```

Exception 'java.lang.Exception' is never thrown in the method

**Comment by abhinavsingh1196** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandlerImpl.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/37222#-NBO0lPN9k7Gc4JGN-ES:-NBSF8YH6l3Fz-90ByIe:bdjklgr) ([raw file](https://github.com/harness/harness-core/blob/d5f9a84b733cca1ddd3fbc83c177267e5dae6116/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHandlerImpl.java#L57)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we move out the Status enum to somewhere else ?
</blockquote></details>

Thanks for pointing this out, moved it to the parent interface since we plan to remove legacy code after some time

**Comment by yogesh-chauhan** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/IK8sRelease.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTBySb1HseHqU8fWib:-NBTByScCZCIUWYKB4eS:bqm8y18) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/IK8sRelease.java#L24)):*
> ```Java
>     Succeeded,
>     Failed;
>   }
> ```

nit: we should follow enum naming conventions i.e all capital letter
https://howtodoinjava.com/java/enum/enum-tutorial/#:~:text=In%20Java%2C%20constants%20are%20defined,same%20as%20static%20final%20constants).

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 23 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 2 change requests. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 10 of 54 files at r1, 13 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 2 change requests. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sLegacyReleaseHandlerImpl.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTMlCdCFF_9oyadT0R:-NBTMlCdCFF_9oyadT0S:b-tggc9m) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sLegacyReleaseHandlerImpl.java#L29)):*
> ```Java
> @Singleton
> public class K8sLegacyReleaseHandlerImpl implements K8sReleaseHandler {
>   @Inject K8sTaskHelperBase k8sTaskHelperBase;
> ```

nit: can be private final

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sLegacyReleaseHandlerImpl.java` line 32 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTO4Ih3x0Q6JBW9VQQ:-NBTO4Ih3x0Q6JBW9VQR:b-14mdjn) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sLegacyReleaseHandlerImpl.java#L32)):*
> ```Java
> 
>   @Override
>   public IK8sReleaseHistory getReleaseHistory(KubernetesConfig kubernetesConfig, String releaseName) throws Exception {
> ```

nit: would be better if we add specific IOException in mehod signature.

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sLegacyReleaseHandlerImpl.java` line 45 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTPYzB1slsB-8nEjTi:-NBTPYzB1slsB-8nEjTj:bfyewwv) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sLegacyReleaseHandlerImpl.java#L45)):*
> nit: would be better if we add specific IOException in mehod signature.

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 3 change requests. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHelper.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTWLuX2B4wPhxfCKPW:-NBTWLuZ1joX07Mv7BDh:bsz3q0y) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/930-delegate-tasks/src/main/java/io/harness/helpers/k8s/releasehistory/K8sReleaseHelper.java#L37)):*
> ```Java
> public class K8sReleaseHelper {
>   String createSetBasedArg(String key, Set<String> values) {
>     return String.format(RELEASE_LABEL_QUERY_SET_FORMAT, key, String.join(SECRET_LABEL_DELIMITER, values));
> ```

nit: String.join() accepts non null argument, lets validate or add @NotNull for Set<String> values

**Comment by yogesh-chauhan** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZNFZDcYZy2KxxXFa:-NBTZNFZDcYZy2KxxXFb:b-vxs6cf) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L64)):*
> ```Java
>       }
>     } catch (IOException ex) {
>       log.error("Failed to extract resources from release.", ex);
> ```

should we not fail in this case ?

**Comment by yogesh-chauhan** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 88 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZjNUAnFN9fkvPlm_:-NBTZjNUAnFN9fkvPlma:bcsnizv) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L88)):*
> ```Java
>       }
>     } catch (IOException e) {
>       log.error("Failed to set resources in release", e);
> ```

 should we not fail in this case ?

**Comment by yogesh-chauhan** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 101 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZrhe7YCL5ut2gMlF:-NBTZrhe7YCL5ut2gMlG:bobbbhp) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L101)):*
> ```Java
>       releaseMeta.setLabels(labels);
>       releaseSecret.setMetadata(releaseMeta);
>       return this;
> ```

this is redundant since below line also returns ```this```



_Code quote:_
```Java
return this;
```

**Comment by abhinavsingh1196** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBSMhtY0ycV1lmhjkZ8:-NBUXRcE-G6VGCdxWGAD:b-d28tgv) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L43)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't be this field as enum as well? 
</blockquote></details>

yes, I removed all the redundant fields. The releaseSecret is the only source of truth now.

**Comment by abhinavsingh1196** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 94 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBSNAPl0Nu7kD3oab1f:-NBUXanOCHMwaDNqG5Bf:bdv89gc) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L94)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't this method update and local field?
</blockquote></details>

Not applicable anymore.

**Comment by abhinavsingh1196** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZNFZDcYZy2KxxXFa:-NBUXftx3xs82kLGwCfc:bat6jg6) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L64)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not fail in this case ?
</blockquote></details>

updated, now we're throwing an exception here.

**Comment by abhinavsingh1196** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java` line 88 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZjNUAnFN9fkvPlm_:-NBUXqXw-05z3GjAQSAS:bat6jg6) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8sRelease.java#L88)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

 should we not fail in this case ?
</blockquote></details>

updated, now we're throwing an exception here.

**Comment by abhinavsingh1196** [comment]
Closing this since I rebased this incorrectly, and all my commits got applied again. Will raise a new PR with the latest revision.
cc: @yogesh-chauhan @tchaurasiya @abosii-harness

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/IK8sRelease.java` line 24 at r8](https://reviewable.io/reviews/harness/harness-core/37222#-NBXFXAH5Wngg_KT8t2M:-NBXFXAH5Wngg_KT8t2N:b-ih9u6n) ([raw file](https://github.com/harness/harness-core/blob/f89e65048c0e087b3c44371912a76b15cf44db42/960-api-services/src/main/java/io/harness/k8s/releasehistory/IK8sRelease.java#L24)):*
> ```Java
>     IN_PROGRESS,
>     SUCCEEDED,
>     FAILED;
> ```

Will be reverting these enum values back to { InProgress, Succeeded, Failed }, to maintain backward compatibility.

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 25 of 64 files at r6, 3 of 615 files at r7, 611 of 611 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 38 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 54 files at r1, 1 of 13 files at r2, 5 of 32 files at r4, 1 of 1 files at r5, 1 of 64 files at r6, 571 of 611 files at r8, 3 of 35 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 47 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8SLegacyReleaseHistory.java` line 40 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZ68E0Zcdrvh--x_N:-NBTZ68E0Zcdrvh--x_O:b-fzinhv) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8SLegacyReleaseHistory.java#L40)):*
> ```Java
>       return releaseHistory.getLatestRelease();
>     }
>     return null;
> ```

probably better to use an optional

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 11 of 64 files at r6, 2 of 615 files at r7, 26 of 611 files at r8, 13 of 35 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 29 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 64 files at r6, 2 of 615 files at r7, 13 of 611 files at r8, 12 of 35 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 12 file(s) to review. 3 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 64 files at r6, 1 of 35 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 5 file(s) to review. 3 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistoryHelper.java` line 44 at r10](https://reviewable.io/reviews/harness/harness-core/37222#-NB_r5w896qqyahQexMa:-NB_r5w896qqyahQexMb:b-mk32lq) ([raw file](https://github.com/harness/harness-core/blob/3f100381fb8e672eb11a1b55f0b7470d9072c50a/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistoryHelper.java#L44)):*
> ```Java
>             .skip(RELEASE_HISTORY_LIMIT)
>             .map(release -> String.valueOf(release.getReleaseNumber()))
>             .collect(Collectors.toList());
> ```

nice use of streams :) 
___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/IK8sRelease.java` line 31 at r10](https://reviewable.io/reviews/harness/harness-core/37222#-NB_pvBp002TyBZE8nL4:-NB_pvBp002TyBZE8nL5:bc68vu6) ([raw file](https://github.com/harness/harness-core/blob/3f100381fb8e672eb11a1b55f0b7470d9072c50a/960-api-services/src/main/java/io/harness/k8s/releasehistory/IK8sRelease.java#L31)):*
> ```Java
>   List<KubernetesResource> getResourcesWithSpecs();
>   List<KubernetesResourceId> getResourceIds();
>   IK8sRelease setReleaseData(@NotNull List<KubernetesResource> resources, @NotNull boolean isPruningEnabled);
> ```

this is a primitive boolean, cannot be null 
___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 38 at r10](https://reviewable.io/reviews/harness/harness-core/37222#-NB_rQkSBwfvKbkNp81u:-NB_rQkSBwfvKbkNp81v:b-btphmj) ([raw file](https://github.com/harness/harness-core/blob/3f100381fb8e672eb11a1b55f0b7470d9072c50a/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L38)):*
> ```Java
> @UtilityClass
> public class K8sReleaseSecretHelper {
>   public static String createSetBasedArg(@NotNull String key, @NotNull Set<String> values) {
> ```

just fyi: Utility class already marks methods and fields as static https://projectlombok.org/features/experimental/UtilityClass
___
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 83 at r10](https://reviewable.io/reviews/harness/harness-core/37222#-NB_t5tV7MLs6sA5cZt9:-NB_t5tWD3Mxc6iMUPLa:b-e8tqve) ([raw file](https://github.com/harness/harness-core/blob/3f100381fb8e672eb11a1b55f0b7470d9072c50a/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L83)):*
> ```Java
>       objectMeta.putLabelsItem(labelKey, labelValue);
>       release.setMetadata(objectMeta);
>     }
> ```

if metadata is null, should we create it and put the label ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 64 files at r6, 4 of 35 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 2 change requests. 2. unresolved discussions.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java` line 83 at r10](https://reviewable.io/reviews/harness/harness-core/37222#-NB_t5tV7MLs6sA5cZt9:-NBdEZJn0_da-Q7NxoV7:b-qb1shd) ([raw file](https://github.com/harness/harness-core/blob/3f100381fb8e672eb11a1b55f0b7470d9072c50a/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseSecretHelper.java#L83)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if metadata is null, should we create it and put the label ?
</blockquote></details>

Done. It doesn't apply to the current workflow (since it will be called just after creating the secret with those predefined labels). But overall the function behaviour is more true to its name.

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistoryHelper.java` line 44 at r10](https://reviewable.io/reviews/harness/harness-core/37222#-NB_r5w896qqyahQexMa:-NBdFFXB3y_ABYyNhVTh:b-ve3yvb) ([raw file](https://github.com/harness/harness-core/blob/3f100381fb8e672eb11a1b55f0b7470d9072c50a/960-api-services/src/main/java/io/harness/k8s/releasehistory/K8sReleaseHistoryHelper.java#L44)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nice use of streams :) 
</blockquote></details>

:smile:

**Comment by abhinavsingh1196** [comment]
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8SLegacyReleaseHistory.java` line 40 at r5](https://reviewable.io/reviews/harness/harness-core/37222#-NBTZ68E0Zcdrvh--x_N:-NBdFbC-EAkrMhrPiZ57:b9yztmp) ([raw file](https://github.com/harness/harness-core/blob/c36b0f2a4f5936b66966b5aac25dac9cf6929dff/970-api-services-beans/src/main/java/io/harness/k8s/model/releasehistory/K8SLegacyReleaseHistory.java#L40)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

probably better to use an optional
</blockquote></details>

didn't use Optional because method returns interface type and it led to incompatible return types 
(Optional<IK8sRelease> expected, but found Optional<K8sRelease>/Optional<K8sLegacyRelease>)

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 2 change requests. 3. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: 2 change requests. 2. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 54 files at r1, 14 of 64 files at r6, 1 of 615 files at r7, 31 of 35 files at r9, 2 of 2 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: :shipit: complete! ✓

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 6 of 54 files at r1, 2 of 32 files at r4, 23 of 64 files at r6, 4 of 615 files at r7, 610 of 611 files at r8, 31 of 35 files at r9, 2 of 2 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 54 files at r1, 23 of 64 files at r6, 4 of 615 files at r7, 610 of 611 files at r8, 31 of 35 files at r9, 2 of 2 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37222#-:-NBkSusZ3SuwfKaxGtOB:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
