### PR TITLE
[fix]: [PL-43569]: update scopeInfo filter to handle DefaultOrganization annotated resources

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlgK_0j7hXfDAq7NML1:-NlgK_0j7hXfDAq7NML2:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java#L164)):*
> ```Java
>       @RequestBody(required = true,
>           description = "Details of the Project to create") @NotNull @Valid ProjectRequest projectDTO) {
>     Optional<ScopeInfo> scopeInfo = scopeResolverService.getScopeInfo(accountIdentifier, orgIdentifier, null);
> ```

Why this change?
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ProjectService.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlgKhrvAZm3zwxChS5j:-NlgKhrvAZm3zwxChS5k:b-osfai6) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/ProjectService.java#L78)):*
> ```Java
>   boolean restore(String accountIdentifier, ScopeInfo scopeInfo, String orgIdentifier, String identifier);
> 
>   Map<String, Integer> getProjectsCountPerOrganization(String accountIdentifier, List<String> parentUniqueIds);
> ```

Lets discuss this change once

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlgLE3YBOoz27uWyqgT:-NlgLE3YBOoz27uWyqgU:b-vark47) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L52)):*
> ```Java
> @Slf4j
> @Provider
> public class ScopeInfoFilter implements ContainerRequestFilter, ContainerResponseFilter {
> ```

Lets review the change in this file today over a call

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlgLOT2AhnJjHYi-oiI:-NlgLOT3-17cpQdFIlyk:b-wpc8t7) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L57)):*
> ```Java
>       Set.of("/organizations", "/aggregate/organizations", "/projects", "/aggregate/projects");
> 
>   public static final Set<String> defaultOrgMatchingPathRequests = Set.of("/projects/", "/aggregate/projects/");
> ```

Can we remove DefaultOrganization annotation?

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlgLOT2AhnJjHYi-oiI:-NlgUnPBEVn0Yy9pjgkt:b-r31hpx) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L57)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we remove DefaultOrganization annotation?
</blockquote></details>

No, we are delegating scope resolution to ResourceLayer where the orgIdentifier will be considered `default`

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlvvGA3CepezTppZiv3:-NlvvGA4BDD8l9RUQarl:b-iwj0kz) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java#L37)):*
> ```Java
> 
>   public boolean isPresent(
>       String accountIdentifier, @OrgIdentifier String orgIdentifier, @ProjectIdentifier String projectIdentifier) {
> ```

These @OrgIdentifier and @ProjectIdentifier annotations can also be removed as it was being used by @DefaultOrganization

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlvvlpn0cPuNxPgzvon:-Nlvvlpn0cPuNxPgzvoo:b-iwj0kz) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L72)):*
> ```Java
> 
>   public void createHarnessSecretManager(
>       String accountIdentifier, @OrgIdentifier String orgIdentifier, @ProjectIdentifier String projectIdentifier) {
> ```

These @OrgIdentifier and @ProjectIdentifier annotations can also be removed as it was being used by @DefaultOrganization

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlvvr0cEpNksFrU7HYk:-Nlvvr0cEpNksFrU7HYl:b-iwj0kz) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L117)):*
> ```Java
> 
>   private boolean isHarnessSecretManagerPresent(
>       String accountIdentifier, @OrgIdentifier String orgIdentifier, @ProjectIdentifier String projectIdentifier) {
> ```

These @OrgIdentifier and @ProjectIdentifier annotations can also be removed as it was being used by @DefaultOrganization

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 317 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlvw4U7D_mnRSNdGUkt:-Nlvw4U7D_mnRSNdGUku:b-9uzgka) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L317)):*
> ```Java
>   @Override
>   public Optional<Project> get(
>       String accountIdentifier, @OrgIdentifier String orgIdentifier, @ProjectIdentifier String projectIdentifier) {
> ```

@OrgIdentifier and @ProjectIdentifier annotations can also be removed from all places where we removed @DefaultOrganization, as it was being used by @DefaultOrganization

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 1 of 7 files at r2, 9 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlvvGA3CepezTppZiv3:-Nlwd8mwAWRtN-10ozz9:bveeis0) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java#L37)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

These @OrgIdentifier and @ProjectIdentifier annotations can also be removed as it was being used by @DefaultOrganization
</blockquote></details>

@ashishsanodia-harness If these are not used by Enforcement framework and were used only in context of default org, lets remove these annotations
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlweJ7G5HNbgnuFv8KB:-NlweJ7G5HNbgnuFv8KC:b-ifhks0) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java#L320)):*
> ```Java
>               "This is the updated Project. Please provide values for all fields, not just the fields you are updating")
>       @NotNull @Valid ProjectRequest projectDTO) {
>     projectDTO.getProject().setVersion(isNumeric(ifMatch) ? parseLong(ifMatch) : null);
> ```

Why this is removed?
___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlwei9R9Z1fUB_BfZt2:-Nlwei9R9Z1fUB_BfZt3:bch9mt) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L109)):*
> ```Java
>         }
> 
>         if (isDefaultOrganizationAnnotatedResourceRequest(
> ```

Can we remove all this logic?
___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 211 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlwekzJ2cO5DA8oo5Qu:-NlwekzJ2cO5DA8oo5Qv:bch9mt) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L211)):*
> ```Java
>   }
> 
>   private boolean isDefaultOrganizationAnnotatedResourceRequest(ContainerRequestContext requestContext,
> ```

Can we remove all this logic?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlwenbM4Wig23XmHZyM:-NlwenbM4Wig23XmHZyN:bqp4twl) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L56)):*
> ```Java
>       Set.of("/organizations", "/aggregate/organizations", "/projects", "/aggregate/projects");
> 
>   //  public static final Set<String> defaultOrgMatchingPathRequests = Set.of("/projects/", "/aggregate/projects/");
> ```

Let's not have commented out code. We should delete it

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java` line 37 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlvvGA3CepezTppZiv3:-NlxB4G9D2uK_J3F5_m-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@ashishsanodia-harness If these are not used by Enforcement framework and were used only in context of default org, lets remove these annotations
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlvvlpn0cPuNxPgzvon:-NlxB6eK7lExuPFVfyAX:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L72)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

These @OrgIdentifier and @ProjectIdentifier annotations can also be removed as it was being used by @DefaultOrganization
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlvvr0cEpNksFrU7HYk:-NlxB8ba7mSxRAGHvVzj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L117)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

These @OrgIdentifier and @ProjectIdentifier annotations can also be removed as it was being used by @DefaultOrganization
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 317 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlvw4U7D_mnRSNdGUkt:-NlxBAARCNXiBi8wPHkb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L317)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

@OrgIdentifier and @ProjectIdentifier annotations can also be removed from all places where we removed @DefaultOrganization, as it was being used by @DefaultOrganization
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java` line 320 at r1](https://reviewable.io/reviews/harness/harness-core/56817#-NlweJ7G5HNbgnuFv8KB:-NlxBF_UCd9lPK4N4EGf:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/9b4d648de8f61c260fa9868f34e9708cd05078ed/120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectResource.java#L320)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this is removed?
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlwenbM4Wig23XmHZyM:-NlxBMoC8jaeAwz2fzYM:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L56)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Let's not have commented out code. We should delete it
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-Nlwei9R9Z1fUB_BfZt2:-NlxBONSAPh9jeQNRYVC:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L109)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we remove all this logic?
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 211 at r4](https://reviewable.io/reviews/harness/harness-core/56817#-NlwekzJ2cO5DA8oo5Qu:-NlxBQNcCJdJlGWEFsuk:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/be7eb1af167f2d42addf10daf8ba4694b3ab694a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L211)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we remove all this logic?
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 9 files at r5, 1 of 1 files at r6, 3 of 7 files at r7, 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56817#-:-NmZvGI33ZYzYW3d7wJ0:bnfp4nl)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
