### PR TITLE
fix: [PL-39503]: add validation in RG to check duplicate identifier

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
add validation in RG to check duplicate identifier
We were able to create RG with same identifiers as harness managed RG
Added validation in RG create API to check if we are creating any RG with identifier that already exists in harness managed RGs

Tested locally by cresting RG with existing harness Managed RG Id, throws exception as expected 
Screenshot 2023-07-05 at 4 25 57 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50173)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50173)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/50173#-NZa5OIl4NnuMWFDxqYn:-NZa5OIl4NnuMWFDxqYo:b-xkfyvc) ([raw file](https://github.com/harness/harness-core/blob/3c457710860dbac20f246338cebdabd172bd494d/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L87)):*
> ```Java
>     if (containsReservedWord(identifier)) {
>       log.warn("Identifier {} contains harness reserved keyword", identifier);
>       /* context.disableDefaultConstraintViolation();
> ```

Remove commented out code
___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/50173#-NZa5K8Q-7fkC9NL4fR6:-NZa5K8Q-7fkC9NL4fR7:b-f972c) ([raw file](https://github.com/harness/harness-core/blob/3c457710860dbac20f246338cebdabd172bd494d/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L96)):*
> ```Java
> 
>   private boolean containsReservedWord(String identifier) {
>     return identifier.contains(reservedKeyword);
> ```

Shouldn't it be startsWith
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/50173#-NZa5YmVAYTkeyTMHI4W:-NZa5YmVAYTkeyTMHI4X:b-6ltpuh) ([raw file](https://github.com/harness/harness-core/blob/3c457710860dbac20f246338cebdabd172bd494d/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L131)):*
> ```Java
>     if (resourceGroupOptional.isPresent()) {
>       throw new InvalidRequestException(
>           String.format("A harness managed resource group already exists with identifier %s", identifier));
> ```

Another Harness managed resource group already exists with identifier

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50173)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/50173#-NZa5OIl4NnuMWFDxqYn:-NZbcYRs2jODAtrOQJRJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3c457710860dbac20f246338cebdabd172bd494d/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L87)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Remove commented out code
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/50173#-NZa5K8Q-7fkC9NL4fR6:-NZbcYnJ1bd8kjIsXdBl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3c457710860dbac20f246338cebdabd172bd494d/980-commons/src/main/java/io/harness/data/validator/EntityIdentifierValidator.java#L96)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't it be startsWith
</blockquote></details>

Done.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/50173#-NZa5YmVAYTkeyTMHI4W:-NZbcZOI3mrJYQscuRQd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3c457710860dbac20f246338cebdabd172bd494d/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/framework/v2/service/impl/ResourceGroupServiceImpl.java#L131)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Another Harness managed resource group already exists with identifier
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50173#-:-NZd55IkE8WGYPWs8gek:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger messagecheck

**Pull request merged**
