### PR TITLE
feat: [DEL-3136]: Cleanup yaml for delegates

### PR DESCRIPTION
**Pull request by mdmilic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30228)

### CODE REVIEW

**Comment by mdmilic** [comment]
trigger publish-delegate

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30228)* status: :shipit: complete! ✓

**Review by bojanmicovic — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30228)* status: :shipit: complete! ✓

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30228)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1235 at r1](https://reviewable.io/reviews/harness/harness-core/30228#-MuR_Iho4r0Ypqsy0eGq:-MuR_Iho4r0Ypqsy0eGr:bli3z1f) ([raw file](https://github.com/harness/harness-core/blob/089cb6591c273c9cb45c907a9643c3a4df790b8d/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1235)):*
> ```Java
>               .put("accountId", templateParameters.getAccountId())
>               .put("accountSecret", accountSecret)
>               .put("base64Secret", base64Secret)
> ```

don't follow why do we need both?

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/30228#-MuR_QmY7XckIvt3SM9h:-MuR_QmY7XckIvt3SM9i:bworq0s) ([raw file](https://github.com/harness/harness-core/blob/089cb6591c273c9cb45c907a9643c3a4df790b8d/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L22)):*
> ```FreeMarker
> ---
> 
> <@secret.accountToken base64Secret/>
> ```

don't understand this change. lets talk over zoom

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30228#-MuR_csOCA04Dsv2vJ73:-MuR_csOCA04Dsv2vJ74:b-kqh9bi) ([raw file](https://github.com/harness/harness-core/blob/089cb6591c273c9cb45c907a9643c3a4df790b8d/400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl#L34)):*
> ```FreeMarker
>         - name: ENABLE_CE
>           value: "${enableCE}"
>         - name: PROXY_HOST
> ```

i thought we won't be having them by default

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30228)* status: 3. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1235 at r1](https://reviewable.io/reviews/harness/harness-core/30228#-MuR_Iho4r0Ypqsy0eGq:-MuT450H0b2Ee51DYWZw:b-nf8o7) ([raw file](https://github.com/harness/harness-core/blob/089cb6591c273c9cb45c907a9643c3a4df790b8d/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1235)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't follow why do we need both?
</blockquote></details>

This method is actually used for generating all templates. We are not making a difference if it's CG/NG yml or a startup script. We always pass all the available parameters to the generators. accountSecret would still be used by the old delegate templates and the base64Secret for immutable delegate templates
___
*[400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/30228#-MuR_QmY7XckIvt3SM9h:-MuT4dod4NeZ8ikyzyKa:b-3ia3na) ([raw file](https://github.com/harness/harness-core/blob/089cb6591c273c9cb45c907a9643c3a4df790b8d/400-rest/src/main/resources/delegatetemplates/harness-delegate-immutable.yaml.ftl#L22)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't understand this change. lets talk over zoom
</blockquote></details>

I think we were discussing to take the secret out of env variable and put it in the secret resource (but then still load it as env var for convenience for now). This can help us in the future to implement for instance certificate based auth (mount the secret as volume and read cert from there). I don't think there is any real benefit right now. 
I was also hoping to move all the env vars to a ConfigMap though to cleanup the Deployment definition, so this would also be in line with that attempt. 
___
*[400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30228#-MuR_csOCA04Dsv2vJ73:-MuT5fgM437YaeJTYkU2:b-48oipn) ([raw file](https://github.com/harness/harness-core/blob/089cb6591c273c9cb45c907a9643c3a4df790b8d/400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl#L34)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i thought we won't be having them by default
</blockquote></details>

This is for old delegates. Immutable delegates won't have them. Check one of expected....Immutable.yml files for details on how immutable delegate yaml should look like after the changes.

**Comment by mdmilic** [comment]
trigger publish-delegate

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30228)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger compile, ti0, ti1, ti2, ti3, ti4

**Comment by mdmilic** [comment]
trigger messagecheck, recency, codeformat

**Comment by mdmilic** [comment]
trigger ft1, ft2, pmd

**Comment by mdmilic** [comment]
trigger checkstyle, buildnum, codebasehash

**Pull request merged**
