### PR TITLE
[feat]: [CCM-11452]: Add Cluster orchestrator permission option in CCM AWS connector

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
List of changes:
1. Cluster_Orchestrator as one other feature.
2. Enabling validation as part of AWS connector when the feature is enabled.
3. Added same permissions to QA HarnessAwsTemplate.
4. Added test cases around cluster orchestrator feature.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45212)

### CODE REVIEW

**Comment by iamanmolm** [comment]
trigger ut0, ut3, ut8

**Review by nikunj-badjatya — COMMENTED** [review]
General question - can cluster orchestrator alone as a feature can work ? without BILLING, OPTIMISATION etc. ?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45212#-:-NQfdUQRCnod2G-nLtuB:b-au351w)* status: 7 file(s) to review. 0 of 1 approvals obtained.

**Comment by iamanmolm** [comment]
> General question - can cluster orchestrator alone as a feature can work ? without BILLING, OPTIMISATION etc. ?
> 
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/45212#-:-NQfdUQRCnod2G-nLtuB:b-au351w)_ status: 7 file(s) to review. 0 of 1 approvals obtained.

Just confirmed with Shalin and I quote "Cluster orchestrator is an independent permission on a connector. Hence should work independently irrespective of other feature enablement".

**Review by iamanmolm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45212)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEAWSConnectorValidator.java` line 554 at r1](https://reviewable.io/reviews/harness/harness-core/45212#-NQfdgYD6zdMxlcvkCSu:-NQhx3jD5nv0us8lsuFp:bvqke19) ([raw file](https://github.com/harness/harness-core/blob/2df1a929d3474edfc3af76901fe1fe248e8ada42/ce-nextgen/service/src/main/java/io/harness/ccm/connectors/CEAWSConnectorValidator.java#L554)):*
<details><summary><i>Previously, nikunj-badjatya (Nikunj Badjatya) wrote…</i></summary><blockquote>

Also add these in harness documentation. 
</blockquote></details>

Done, here it is: https://harness.atlassian.net/browse/DOC-2796

**Review by nikunj-badjatya — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45212)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by nikunj-badjatya — APPROVED** [review]
:lgtm:
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45212#-:-NQi7wIG6nSQZ_K5TZh-:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
