### PR TITLE
[feat]: [PL-23285]: Removed NG_DASHBOARD_LANDING_PAGE ff from backend

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Removed NG_DASHBOARD_LANDING_PAGE ff from backend

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31122)

### CODE REVIEW

**Review by meenakshi-harness — DISMISSED** [review]

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31122)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by rathodmeetsatish** [comment]
trigger ft2

**Comment by rathodmeetsatish** [comment]
trigger codebasehash,trigger ft1,trigger codebasehash,

**Comment by rathodmeetsatish** [comment]
trigger compile

**Comment by rathodmeetsatish** [comment]
trigger license/cla

**Comment by rathodmeetsatish** [comment]
trigger license/cla

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31122)* status: :shipit: complete! ✓

**Comment by rathodmeetsatish** [comment]
trigger license/cla

**Pull request merged**
