### PR TITLE
feat: [PL-25049]: added logging for git sdk and git service methods

### PR DESCRIPTION
**Pull request by bhavya181**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33502)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/33502#-N2rm4AdE64eElINm7nM:-N2rm4Ae7AfH0-o7JICq:bgqy211) ([raw file](https://github.com/harness/harness-core/blob/6d4ceb9df6c9f4c8b34487009d54fd38db53ef80/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java#L27)):*
> ```Java
>   public static Map<String, String> setContext(ScopeIdentifiers scope, String repoName, String branchName,
>       String filePath, GitOperation operationType, Map<String, String> contextMap) {
>     logContextMap = contextMap;
> ```

what if contextMap = null? Lets init it in that case.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/33502#-N2rlBhEARa-yZnHVbvz:-N2u6JVy0-2zQoYRUHh-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d4ceb9df6c9f4c8b34487009d54fd38db53ef80/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets use Scope here instead of ScopeIdentifiers as its a proto object
</blockquote></details>

Done.
___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/33502#-N2rm4AdE64eElINm7nM:-N2u6JwnAWmOlp5B25yr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d4ceb9df6c9f4c8b34487009d54fd38db53ef80/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if contextMap = null? Lets init it in that case.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502#-:-N2uIdVE5LgivMcsW82N:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/33502#-N2rlT1LD8QWkQM6c_vu:-N2rlT1MCLZQHIHLzfVe:b-ujpofm) ([raw file](https://github.com/harness/harness-core/blob/6d4ceb9df6c9f4c8b34487009d54fd38db53ef80/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java#L25)):*
> ```Java
>   private Map<String, String> logContextMap;
> 
>   public static Map<String, String> setContext(ScopeIdentifiers scope, String repoName, String branchName,
> ```

Can we rename the method to something better as it doesn't actually set any context but only fills in details to a context map

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/33502#-N2uVMed34uFfneJMxts:-N2uVMed34uFfneJMxtt:b-ri9mi7) ([raw file](https://github.com/harness/harness-core/blob/5dfb1c7cae7f4749cb5b7b059c4dbd375736b4a9/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L109)):*
> ```Java
>     Map<String, String> contextMap = GitSyncLogContextHelper.setContextMap(
>         ScopeIdentifierMapper.getScopeFromScopeIdentifiers(request.getScopeIdentifiers()), request.getRepoName(),
>         request.getBranchName(), request.getFilePath(), GitOperation.GET_FILE, request.getContextMapMap());
> ```

Why map is coming twice in getcontextmapmap ?

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/33502#-N2uVMed34uFfneJMxts:-N2urCa7AxTbFpef-Y2F:bwh1v59) ([raw file](https://github.com/harness/harness-core/blob/5dfb1c7cae7f4749cb5b7b059c4dbd375736b4a9/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L109)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Why map is coming twice in getcontextmapmap ?
</blockquote></details>

Don't know, in proto the field name is context_map, I don't know it is converted to getContextMapMap()
___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/33502#-N2rlT1LD8QWkQM6c_vu:-N2urBxh2jBG7nwG1nN9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6d4ceb9df6c9f4c8b34487009d54fd38db53ef80/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncLogContextHelper.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we rename the method to something better as it doesn't actually set any context but only fills in details to a context map
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502#-:-N2urh-u--z_VwmjEpuo:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33502)* status: :shipit: complete! ✓

**Pull request merged**
