### PR TITLE
[feat]: [CDS-71584]: Creating POJO and Templates for webhook notification events

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48939)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48939)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/notification/TriggerExecutionInfo.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/48939#-NXL6o0Z3YNjM2x4BKW7:-NXL6o0Z3YNjM2x4BKW8:b6zaofh) ([raw file](https://github.com/harness/harness-core/blob/b77a7e0b1a541e6d2ed14f823bbb7c83700611cb/953-yaml-commons/src/main/java/io/harness/notification/TriggerExecutionInfo.java#L8)):*
> ```Java
> @Builder
> @Value
> public class TriggerExecutionInfo {
> ```

team annotation
___
*[`953-yaml-commons/src/main/java/io/harness/notification/WebhookNotificationEvent.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48939#-NXL6yIEAfVJHf44euL9:-NXL6yIEAfVJHf44euLA:b-spwtu2) ([raw file](https://github.com/harness/harness-core/blob/b77a7e0b1a541e6d2ed14f823bbb7c83700611cb/953-yaml-commons/src/main/java/io/harness/notification/WebhookNotificationEvent.java#L29)):*
> ```Java
>   PipelineEventType eventType;
>   TriggerExecutionInfo triggeredBy;
>   String startTime;
> ```

why string startTime and endTIme is required?

How we are thinking to add different event for stage and step events?

Can you make this abstract and have different impl for each type? like EventPayloadData

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48939)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/notification/TriggerExecutionInfo.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/48939#-NXL6o0Z3YNjM2x4BKW7:-NXL7soN689mp45UZl80:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b77a7e0b1a541e6d2ed14f823bbb7c83700611cb/953-yaml-commons/src/main/java/io/harness/notification/TriggerExecutionInfo.java#L8)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

team annotation
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/notification/WebhookNotificationEvent.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48939#-NXL6yIEAfVJHf44euL9:-NXL7wpx30RwLvubRTX-:bzbuot1) ([raw file](https://github.com/harness/harness-core/blob/b77a7e0b1a541e6d2ed14f823bbb7c83700611cb/953-yaml-commons/src/main/java/io/harness/notification/WebhookNotificationEvent.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why string startTime and endTIme is required?

How we are thinking to add different event for stage and step events?

Can you make this abstract and have different impl for each type? like EventPayloadData
</blockquote></details>

startTime and endTime is in Human readable DateTime format. 
PipelineEventType is common eventType for Pipeline, stage and step. Its just enumName isPipelineEventType. So i think we don't need to make this abstract as we will be sending same info for all events. Just the values will be different.

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 12 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48939)* status: 12 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 283 at r5](https://reviewable.io/reviews/harness/harness-core/48939#-NXP9sz022aKSQdTIQHZ:-NXPrTunAb9DTY7iMM9f:bs9uiq5) ([raw file](https://github.com/harness/harness-core/blob/73e84f5e939cd51133d45560ee194f61906d27ad/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L283)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we add a help to move creating this dto logic separate?
</blockquote></details>

done, discussed offfline in next pr
___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 366 at r5](https://reviewable.io/reviews/harness/harness-core/48939#-NXP9xeY0Xdkum0Zrpnt:-NXPrVvtB7Xk4ZhUro9Q:bs9uiq5) ([raw file](https://github.com/harness/harness-core/blob/73e84f5e939cd51133d45560ee194f61906d27ad/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L366)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

include this in same helper, helper should be static, pass required inputs as params
</blockquote></details>

done, discussed offfline in next pr

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut3

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 7 of 12 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48939)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48939)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger review

**Comment by brijeshdhakar** [comment]
trigger ut0 ut4

**Pull request merged**
