### PR TITLE
[fix]: [PIE-5833]: Fix expressionMode coming THROW_EXCEPTION_IF_UNRESOLVED when the proto changes are not available in the sdk

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes
We added one enum in proto that is used in pipeline-sdk. The default expressionMode should be RETURN_NULL_IF_UNRESOLVED but in proto we kept THROW_EXCEPTION_IF_UNRESOLVED with number 0. So when the other services were not deployed and did not have this enum. And only pipeline service was deployed.  proto sent the value 0(As corresponding to not provided). And pipeline-service considered it as the provided mode and did not use the default mode(When mode is not provided, we use default mode). This changed some behaviour during the expressionEvaluation. And CI pipelines started to fail.
Now we added one UNRECOGNISED enum with number zero and on pipeline service, if we get this unrecognised then we will use the default mode RETURN_NULL_IF_UNRESOLVED. This will make sure that if other-services proved some valid expressionMode then only that mode will be used. And in case not proveded(Like above), default mode will be used.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38828)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
Codebase hash change:
Safe change for delegate communication. Making change is a proto ExpressionMode that is used by pipeline service and it's sdk. Its not used in delegate communication anyway.

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/expression/ExpressionMode.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/38828#-NEZs12VCkSNBK54sKhc:-NEZs12VCkSNBK54sKhd:batfxxf) ([raw file](https://github.com/harness/harness-core/blob/4928a34a438248e644d13454122a1de5e9c77026/980-commons/src/main/java/io/harness/expression/ExpressionMode.java#L20)):*
> ```Java
> 
> public enum ExpressionMode {
>   RETURN_NULL_IF_UNRESOLVED(1),
> ```

Add UNKNOWN (0)

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/38828#-NEZs8e40FdH1ACgVa6h:-NEZs8e40FdH1ACgVa6i:b2i52sq) ([raw file](https://github.com/harness/harness-core/blob/4928a34a438248e644d13454122a1de5e9c77026/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java#L112)):*
> ```Java
>         return ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED;
>       case 0:
>       case 1:
> ```

I think this is not required. we can directly use default.



_Code quote:_
```Java
      case 1:
```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38828)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38828)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38828)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38828)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38828)* status: :shipit: complete! ✓

**Pull request merged**
