### PR TITLE
feat: [SRM-13422] Downtime Implementation

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Downtime Implementation

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: 29 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/jobs/EntityChangeEventMessageProcessor.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/42234#-NL-mAEN4yG4vkg-HZ8-:-NL-mAEN4yG4vkg-HZ80:bcl2dr0) ([raw file](https://github.com/harness/harness-core/blob/f6015ef888f051f7de4f0d2532cc5d469c22afde/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/jobs/EntityChangeEventMessageProcessor.java#L71)):*
> ```Java
>     EXCEPTIONS = new HashSet<>();
>     EXCEPTIONS.add(ServiceLevelIndicator.class);
>     EXCEPTIONS.add(Downtime.class);
> ```

Why we have added it as an exception? we can need to extend DeleteEntityByHandler for DowntimeService.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeDTO.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0e9UwEEf67kvOvb-k:-NL0e9UwEEf67kvOvb-l:bhkv2vl) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeDTO.java#L35)):*
> ```Java
>   @ApiModelProperty(required = true) @EntityIdentifier String orgIdentifier;
>   @ApiModelProperty(required = true) @EntityIdentifier String projectIdentifier;
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier String identifier;
> ```

We need to add name property as well here
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeHistoryView.java` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0iLqk-AEF5EaEZ9RN:-NL0iLqk-AEF5EaEZ9RO:b-erb3b9) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeHistoryView.java#L18)):*
> ```Java
>   String startTime;
>   String endTime;
>   String duration;
> ```

should have name and identifier as well.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java` line 16 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0iQOL1eZDNA9yc1t-:-NL0iQOL1eZDNA9yc1t0:b-erb3b9) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java#L16)):*
> ```Java
> @Builder
> public class DowntimeListView {
>   DowntimeCategory category;
> ```

should have name and identifier as well.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0hrlC3avTdjCGpvm-:-NL0hrlC3avTdjCGpvm0:b1sql44) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java#L19)):*
> ```Java
>   List<String> affectedEntities;
>   String notes;
>   String status;
> ```

nit: status should be a polymorphic class with enum Scheduled | Active. Active will also have end time as well.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeRecurrence.java` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0iWxJ0JA1eB5POrQg:-NL0iWxKDQox2cDPAeP2:b-8h63p) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeRecurrence.java#L18)):*
> ```Java
> public class DowntimeRecurrence {
>   private DowntimeRecurrenceType recurrenceType;
>   private int recurrenceValue;
> ```

we should have a validation that it cann't be null
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0j0Z-5Xi_epOcaEbm:-NL0j0Z-5Xi_epOcaEbn:bppys11) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L64)):*
> ```Java
>   String orgIdentifier;
>   String projectIdentifier;
>   @NotNull String identifier;
> ```

add name as well here
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0j48m6Wz1DKQ91-rV:-NL0j48m6Wz1DKQ91-rW:bdc7av4) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L65)):*
> ```Java
>   String projectIdentifier;
>   @NotNull String identifier;
>   String description;
> ```

everywhere we can use description. Thani has renamed notes to description. We need to tags as well
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0jeWS7yvoql7N02JW:-NL0jeWS7yvoql7N02JX:b-ya536d) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L71)):*
> ```Java
>   @NotNull String timezone;
>   @NotNull DowntimeDetails downtimeDetails;
>   private List<String> entityDetails;
> ```

rename to entityRefs
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 125 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0jV4n-KWeW_cTDR5D:-NL0jV4n-KWeW_cTDR5E:bdocsl5) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L125)):*
> ```Java
>                  .field(DowntimeKeys.accountId)
>                  .field(DowntimeKeys.orgIdentifier)
>                  .field(DowntimeKeys.projectIdentifier)
> ```

add identifier as well to the index.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/resources/DowntimeProjectLevelResource.java` line 63 at r5](https://reviewable.io/reviews/harness/harness-core/42234#-NL0kACp9-44LGS4CevM:-NL0kACp9-44LGS4CevN:b-qli0g9) ([raw file](https://github.com/harness/harness-core/blob/67053012ff9f26939c75f20a476e6ecfb5e7d278/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/resources/DowntimeProjectLevelResource.java#L63)):*
> ```Java
> @NextGenManagerAuth
> @Tag(name = "Downtime", description = "This contains APIs related to CRUD operations of Downtime")
> @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = NGCommonEntityConstants.BAD_REQUEST_CODE,
> ```

lets disable it until APIs are developed and integrated

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 14 of 25 files at r1, 1 of 1 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 10 of 11 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java` line 37 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2UUug2ykSBQQetFRj:-NL2UUug2ykSBQQetFRk:b-3etexv) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java#L37)):*
> ```Java
> 
>   private static class LastModifiedBy {
>     String name;
> ```

we should have Identifier as well



_Code quote:_
```Java
String name;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java` line 28 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2V62yAcsRSlId_N3Q:-NL2V62yAcsRSlId_N3R:byvil1p) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java#L28)):*
> ```Java
>   @Valid
>   @NotNull
>   DowntimeSpec spec;
> ```

This will be different from what we store, we store in epoch, but we need to send the string with the timezoned date



_Code quote:_
```Java
  DowntimeSpec spec;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java` line 76 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2T9ux1xOAxkKFCQGP:-NL2T9ux1xOAxkKFCQGQ:b3obosm) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/entities/Downtime.java#L76)):*
> ```Java
>   @NotNull String timezone;
>   @NotNull DowntimeDetails downtimeDetails;
>   private List<String> entityRefs;
> ```

Instead of just refs create a new Class EntityDetails and boolean enabled as well there



_Code quote:_
```Java
String
```

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: Some of the checks are too old. 10 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java` line 37 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2UUug2ykSBQQetFRj:-NLJzHw305-F6SMInqgF:b-c651bp) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java#L37)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

we should have Identifier as well
</blockquote></details>

lastUpdatedAt,
lastUpdatedBy
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java` line 27 at r9](https://reviewable.io/reviews/harness/harness-core/42234#-NLJynRI7_tGqIbNRVZY:-NLJynRJ5ppRI_6wO5sL:b53fdmb) ([raw file](https://github.com/harness/harness-core/blob/266deb0aa95be4edcbab2cd1c929c62952c23c8b/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeListView.java#L27)):*
> ```Java
> 
>   private static class AffectedEntities {
>     int total;
> ```

Don't need this

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: Some of the checks are too old. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java` line 28 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2V62yAcsRSlId_N3Q:-NLMWdA14PRXGozL7x4V:b-2l6x0y) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java#L28)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

This will be different from what we store, we store in epoch, but we need to send the string with the timezoned date
</blockquote></details>

@sathish-soundarapandian Can you please reply/acknowledge this

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: Some of the checks are too old. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java` line 28 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2V62yAcsRSlId_N3Q:-NLOq38mA6tTt9fUlOIs:b-11ao12) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java#L28)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

@sathish-soundarapandian Can you please reply/acknowledge this
</blockquote></details>

Yeah, the abstract DowntimeSpec will have - String timezone, long startTime; i.e timezone and then the epoch time. This is what UI sends us during create / update.

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 10 of 11 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java` line 28 at r7](https://reviewable.io/reviews/harness/harness-core/42234#-NL2V62yAcsRSlId_N3Q:-NLPaD5HESrVljQLctsc:b-8tz6ns) ([raw file](https://github.com/harness/harness-core/blob/b051101e0d6930d0b4596a3fcfb09c46a9ffde3f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeSpecDTO.java#L28)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Yeah, the abstract DowntimeSpec will have - String timezone, long startTime; i.e timezone and then the epoch time. This is what UI sends us during create / update.
</blockquote></details>

Should this logic be in UI of getting epoch time and generating time from the epoch and timezone?

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234#-:-NLQwtws6-rknH_CjX9C:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 14 of 25 files at r1, 3 of 4 files at r4, 4 of 11 files at r6, 4 of 9 files at r8, 1 of 1 files at r9, 10 of 11 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42234)* status: :shipit: complete! ✓

**Pull request merged**
