### PR TITLE
feat: [PIE-4849]: Support for environment group in multi-environments

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38178)

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/38178#-NDCf6OqEclB0Dk2JG6D:-NDCf6OqEclB0Dk2JG6E:b-x6k104) ([raw file](https://github.com/harness/harness-core/blob/bfde37a72b0f97bdeb3a5dfba4d277d94e315920/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L204)):*
> ```Java
>       return new ArrayList<>();
>     }
>     if (EmptyPredicate.isEmpty(environments)) {
> ```

should we not handle both these conditions in the same manner
1. environments == null
2. isEmpty(environments)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 413 at r2](https://reviewable.io/reviews/harness/harness-core/38178#-NDCfSMaDK15ICw2hh7r:-NDCfSMaDK15ICw2hh7s:b-29xsx4) ([raw file](https://github.com/harness/harness-core/blob/bfde37a72b0f97bdeb3a5dfba4d277d94e315920/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L413)):*
> ```Java
>       DeploymentStageNode stageNode, PlanCreationContext ctx) {
>     DeploymentStageConfig stageConfig = stageNode.getDeploymentStageConfig();
>     if (stageConfig.getServices() == null && stageConfig.getEnvironments() == null
> ```

should we have gitops enabled check here ?

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 413 at r2](https://reviewable.io/reviews/harness/harness-core/38178#-NDCfSMaDK15ICw2hh7r:-NDCuc3L7Aml1On2NpsP:b-jfhwhi) ([raw file](https://github.com/harness/harness-core/blob/bfde37a72b0f97bdeb3a5dfba4d277d94e315920/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L413)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we have gitops enabled check here ?
</blockquote></details>

Will add gitOps check in next PR.

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/38178#-NDCf6OqEclB0Dk2JG6D:-NDCug80-BfbYlFXU6Ml:b-emzr16) ([raw file](https://github.com/harness/harness-core/blob/bfde37a72b0f97bdeb3a5dfba4d277d94e315920/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L204)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not handle both these conditions in the same manner
1. environments == null
2. isEmpty(environments)
</blockquote></details>

I think they both can be merged, will merge

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: 3 file(s) to review.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38178)* status: :shipit: complete! ✓

**Pull request merged**
