### PR TITLE
feat: [CDS-52632]: K8s declarative rollback opt-in configuration

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
For NG, users will now have a checkbox in manifest details section to enable declarative rollback. This will help us get rid of the declarative rollback NG FF.

Screenshot 2023-02-06 at 11 21 29 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)

### CODE REVIEW

**Review by GoelPratyush99 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/K8sManifest.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/43409#-NNGX56w6tqJsE1HD1rI:-NNGX56w6tqJsE1HD1rJ:b-t4416x) ([raw file](https://github.com/harness/harness-core/blob/b0b36cb508ff7bf41c8ac840cff5d954ea387232/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/K8sManifest.java#L80)):*
> ```Java
> 
>   @Wither @YamlSchemaTypes({string, bool}) @SkipAutoEvaluation ParameterField<Boolean> skipResourceVersioning;
>   @Wither @YamlSchemaTypes({string, bool}) @SkipAutoEvaluation ParameterField<Boolean> enableDeclarativeRollback;
> ```

We would need to add the same in HelmChartManifest, OpenshiftManifest and KustomizeManifest

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abosii-harness** [comment]
@abhinavsingh1196 do we still need the FF? Should we confirm with Rohan?

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by GoelPratyush99 — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by GoelPratyush99 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 12 files at r1, 1 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by TarunUba1 — DISMISSED** [review]
> Reviewed 11 of 12 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by GoelPratyush99 — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger feature-build

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 2 file(s) to review.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java` line 654 at r6](https://reviewable.io/reviews/harness/harness-core/43409#-NNfUuybCbv2g1ssoHgq:-NNfUuybCbv2g1ssoHgr:b-10exs5) ([raw file](https://github.com/harness/harness-core/blob/b9968d084ec915b9186877b39a0234eebcd7d19f/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandler.java#L654)):*
> ```Java
>             kubernetesResourceIdRevision.getWorkload().kindNameRef(),
>             kubernetesResourceIdRevision.getWorkload().getNamespace(), kubernetesResourceIdRevision.getRevision(),
>             result.outputUTF8()));
> ```

need to have check result.hasOutput()

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43409)* status: :shipit: complete! ✓

**Pull request merged**
