### PR TITLE
[feat]: [PIE-6088]: Add first rollback stage’s ID in execution summary

### PR DESCRIPTION
**Pull request by namanvermah**
Add first rollback stage’s ID in pipeline execution summary. Also every stage in the graph layout will have a flag that tells if it is a rollback stage or not. Fixed a test in StagesPlanCreator as well

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39831)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39831)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39831)* status: 13 file(s) to review. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/stages/parallel/ParallelPlanCreatorTest.java` line 154 at r4](https://reviewable.io/reviews/harness/harness-core/39831#-NGUxJoo7fJKdpukd2iH:-NGUxJoo7fJKdpukd2iI:barwwlw) ([raw file](https://github.com/harness/harness-core/blob/6ea9b818f6eecb6e85a72e9123851d593181da4e/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/plancreator/stages/parallel/ParallelPlanCreatorTest.java#L154)):*
> ```Java
>     assertThat(layoutNodes.containsKey(stage0Field.getNode().getUuid() + "_rollbackStage")).isTrue();
>     assertThat(layoutNodes.containsKey(stage1Field.getNode().getUuid() + "_rollbackStage")).isTrue();
>     assertThat(layoutNodes.containsKey(parallelStagesField.getNode().getUuid() + "_rollbackStage")).isTrue();
> ```

nit, you can also unit test the linkages b/w parallel, it's children and siblings

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39831)* status: 3 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39831)* status: :shipit: complete! ✓

**Pull request merged**
