### PR TITLE
feat: [CDS-79493]: Update Abort Interrupt Messages for registration and already existing abort interrupt

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
If we were hitting the Abort Interrupt multiple times, we used to get the error message - `Execution has already been aborted.`
Even if the pipeline didn't actually aborted 

Now we are showing error message as - `Execution abort is already under progress.`
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53714)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger ut4

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53714)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/53714#-NfyE0fr64ds5iJ5K5mD:-NfyE0fr64ds5iJ5K5mE:bhaf3h1) ([raw file](https://github.com/harness/harness-core/blob/62644ca8a61e656cdcd3c07d1ba3c26bc705b280/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L215)):*
> ```Java
>   ABORT_ALL_ALREADY,
> 
>   ABORT_ALL_ALREADY_NG,
> ```

please move it to bottom.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53714)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/53714#-NfyHHzpAEM_4LsExCYo:-NfyHHzpAEM_4LsExCYp:bf7wyfm) ([raw file](https://github.com/harness/harness-core/blob/62644ca8a61e656cdcd3c07d1ba3c26bc705b280/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L90)):*
> ```Java
>   private Interrupt processInterrupt(@Valid @NonNull Interrupt interrupt, List<Interrupt> interrupts) {
>     if (checkIfInterruptAlreadyPresent(interrupt, interrupts)) {
>       throw new InvalidRequestException("Execution already has ABORT_ALL interrupt", ABORT_ALL_ALREADY_NG, USER);
> ```

@utkarshchoubey-harness check all cases in NG i can see in CVNGStep as well

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53714)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/eraro/ErrorCode.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/53714#-NfyE0fr64ds5iJ5K5mD:-NfyZzmG8nrZWbQbGp0C:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/62644ca8a61e656cdcd3c07d1ba3c26bc705b280/980-commons/src/main/java/io/harness/eraro/ErrorCode.java#L215)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

please move it to bottom.
</blockquote></details>

Done

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53714)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Review by n00bitax — APPROVED** [review]

**Pull request merged**
