### PR TITLE
[fix]:[PL-26657]: Fix delegateTask setup in notification service

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Fix delegateTask setup in notification service

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35498)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/SlackTaskParams.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PbSar0r2tJjJo-85c:-N7PbSar0r2tJjJo-85d:bff1x66) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/SlackTaskParams.java#L53)):*
> ```Java
>                   .build());
>         } catch (URISyntaxException e) {
>           log.error("Can't parse webhookurl as URI {}", notificationId);
> ```

We should log the exception as well.

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pbdd8-AIIV-OKh3KO:-N7Pbdd8-AIIV-OKh3KP:b-mcy0mc) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java#L221)):*
> ```Java
>   }
> 
>   private Map<String, String> getAbstractionMap(String accountId, String orgId, String projectId) {
> ```

we should name arguments as accountIdentifier, orgIdentifier, projectIdentifier

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 255 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pbw5w53cH2uTSzgkA:-N7Pbw5w53cH2uTSzgkB:b-hs38d3) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L255)):*
> ```Java
>   @Override
>   public Map<String, String> buildAbstractions(EncryptionConfig encryptionConfig) {
>     Map<String, String> abstractions = new HashMap<>(2);
> ```

why do we need to initialize it with size=2?

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pc1f59wtUj9NUs3lb:-N7Pc1f59wtUj9NUs3lc:b4hx78u) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L265)):*
> ```Java
>         abstractions.put(NG_DELEGATE_OWNER_CONSTANT, owner);
>       }
>       abstractions.put(NG_DELEGATE_ENABLED_CONSTANT, "true");
> ```

Lets not use hardcoded strings. Please use constants from a common util so that everyone uses the same. I'm not sure how does someone uses this value later on as its hardcoded

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java` line 223 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PcQdsCG8t5tzgz7A5:-N7PcQdsCG8t5tzgz7A6:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java#L223)):*
> ```Java
>   }
> 
>   private Map<String, String> getAbstractionMap(String accountId, String orgId, String projectId) {
> ```

same as above

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PcWjR2XhQka_cACj-:-N7PcWjR2XhQka_cACj0:bt4t3qh) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java#L227)):*
> ```Java
>         VaultConfig.builder()
>             .accountId(accountId)
>             .ngMetadata(NGSecretManagerMetadata.builder().orgIdentifier(orgId).projectIdentifier(projectId).build())
> ```

we do have accountidentifier also in NGSecretManagerMetadata, lets set that as well as these are common scope fields.



_Code quote:_
```Java
NGSecretManagerMetadata
```

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java` line 173 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PcjJIDfIWyMOiWR39:-N7PcjJIDfIWyMOiWR3A:b3euq3w) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java#L173)):*
> ```Java
>   }
> 
>   private Map<String, String> getAbstractionMap(String accountId, String orgId, String projectId) {
> ```

I see this method's implementation is same across all impls. If thats the case, can we move it out to a common layer?

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pctry-a6Cs_ciGN0k:-N7Pctry-a6Cs_ciGN0l:b-gdi8sn) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java#L16)):*
> ```Java
>   private static final String ORG_OWNER = "%s";
> 
>   public String getOwner(String accountId, String orgIdentifier, String projectIdentifier) {
> ```

accountIdentifier*

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pd0vD3qlOhfdan5Co:-N7Pd0vD3qlOhfdan5Cp:b-oikd84) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java#L23)):*
> ```Java
>       owner = String.format(ORG_OWNER, orgIdentifier);
>     }
>     return owner;
> ```

I don't see any usage of accountId here, is it a miss?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35498)* status: 9 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/SlackTaskParams.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PbSar0r2tJjJo-85c:-N7PdKxT6iyIoykWbtSi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/SlackTaskParams.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should log the exception as well.
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pbdd8-AIIV-OKh3KO:-N7Pdbg6BsPlguKL6OdY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java#L221)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should name arguments as accountIdentifier, orgIdentifier, projectIdentifier
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 255 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pbw5w53cH2uTSzgkA:-N7PfNhq1usSgCS5kD-b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L255)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to initialize it with size=2?
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pc1f59wtUj9NUs3lb:-N7PfLrs-5Den_gv3bPe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L265)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets not use hardcoded strings. Please use constants from a common util so that everyone uses the same. I'm not sure how does someone uses this value later on as its hardcoded
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java` line 223 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PcQdsCG8t5tzgz7A5:-N7Pdi4UDdktvE7DfRlv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java#L223)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PcWjR2XhQka_cACj-:-N7Pdvqp87UzMl5ABl0x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java#L227)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we do have accountidentifier also in NGSecretManagerMetadata, lets set that as well as these are common scope fields.
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java` line 173 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7PcjJIDfIWyMOiWR39:-N7PfIxQ2FTJvjgeCURL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java#L173)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see this method's implementation is same across all impls. If thats the case, can we move it out to a common layer?
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pccb70iDMVleOcLsN:-N7PfJDrBMzxVboRQACb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java#L177)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pctry-a6Cs_ciGN0k:-N7Pejkz8umuXaPxrnZ6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

accountIdentifier*
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pd0vD3qlOhfdan5Co:-N7Pe8t6BFVdOZGN1VAY:b-li6so3) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I don't see any usage of accountId here, is it a miss?
</blockquote></details>

Its not needed here.

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/35498#-N7QDRZU7ZpdNa904UVq:-N7QDRZU7ZpdNa904UVr:bzi3746) ([raw file](https://github.com/harness/harness-core/blob/f83c67f5f2573c924c19c17ec7b3bc2833727abb/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java#L126)):*
> ```Java
> 
>     Map<String, String> abstractionMap = notificationSettingsService.buildAbstractions(
>         VaultConfig.builder()
> ```

Why VaultConfig here?

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pd0vD3qlOhfdan5Co:-N7QDyi29AwdBZwjl5pf:b15masv) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java#L23)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Its not needed here.
</blockquote></details>

Why this class was changed?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35498)* status: 9 file(s) to review. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java` line 126 at r3](https://reviewable.io/reviews/harness/harness-core/35498#-N7QDRZU7ZpdNa904UVq:-N7QHduJ9Ed5bZHL1T1w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f83c67f5f2573c924c19c17ec7b3bc2833727abb/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java#L126)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why VaultConfig here?
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pd0vD3qlOhfdan5Co:-N7QHbAJDw8qBf6upQEc:b-5mw4c9) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/utils/TaskSetupAbstractionHelper.java#L23)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this class was changed?
</blockquote></details>

Done. Removed

**Comment by piyush-harness** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 255 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pbw5w53cH2uTSzgkA:-N7QLzPb4ovszyjlOwdY:b3qzqj6) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L255)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Map with size 2 is good since this map will always have 2 entries so why allocate 16

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35498)* status: 9 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 255 at r2](https://reviewable.io/reviews/harness/harness-core/35498#-N7Pbw5w53cH2uTSzgkA:-N7QXKeq-A-JA3ufyrNN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d6330ebce959fad3a867a73c559866a06ab5404f/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L255)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Map with size 2 is good since this map will always have 2 entries so why allocate 16 
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java` line 258 at r3](https://reviewable.io/reviews/harness/harness-core/35498#-N7QDfCjCz_L_tzYJYRP:-N7QWoKmD9qWBpA8AUR2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f83c67f5f2573c924c19c17ec7b3bc2833727abb/platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java#L258)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

you don't need all of this just create owner object from accountId, orgId and projectId, I gave this as an example only
</blockquote></details>

Done.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 7 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35498)* status: 9 file(s) to review. 11. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
trigger codebasehashcheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 5 of 7 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35498)* status: 11. unresolved discussions.

**Pull request merged**
