### PR TITLE
fix: [PIE-4522]: Fix step Params being null

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35806)

### CODE REVIEW

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35806)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/35806#-N83maBJ3wG6dbbOUMdN:-N83maBKDshdTClt9F7Z:b-qeo3cr) ([raw file](https://github.com/harness/harness-core/blob/e7b08d9fd5ff95461986dd26eb5fa961cb7fc26a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java#L101)):*
> ```Java
>       if (isOutcomeUpdateGraphStatus(newValue.getStatus())) {
>         if (EmptyPredicate.isEmpty(newValue.getStepParameters())) {
>           newValue.setStepParameters(pmsGraphStepDetailsService.getStepInputs(planExecutionId, nodeExecutionId));
> ```

nit: add a log line in this if block to know if step params are coming null till here.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35806)* status: :shipit: complete! ✓

**Review by smjt-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35806)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by hemanthbsridhar — APPROVED** [review]

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35806#-:-N84PZ5f0Dbh2rgC9JP0:bnfp4nl)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
