### PR TITLE
fix: [SRM-12748]: update slo validation for slo target entity and delete validation and giving slo listing view api for fetching simple slos of composite slos account scope

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 178 at r1](https://reviewable.io/reviews/harness/harness-core/39778#-NGQCC2H6D6MLgngu2wr:-NGQCC2H6D6MLgngu2ws:b-6vtucz) ([raw file](https://github.com/harness/harness-core/blob/a3755bd67b03dc2b2f8bb947a6754960cce9e83d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L178)):*
> ```Java
>         throw new InvalidRequestException(String.format(
>             "Can't update the compliance time period for SLO with identifier %s, accountId %s, orgIdentifier %s and projectIdentifier %s as it is associated with Composite SLO with identifier%s %s.",
>             identifier, projectParams.getAccountIdentifier(), projectParams.getOrgIdentifier(),
> ```

It can be possible that user doesn't has access to that composite SLO. Confirm how we are going to handle that. How is UI displaying this error? Will the user get redirected to that composite SLO, is this error clickable?



_Code quote:_
```Java
            "Can't update the compliance time period for SLO with identifier %s, accountId %s, orgIdentifier %s and projectIdentifier %s as it is associated with Composite SLO with identifier%s %s.",
            identifier, projectParams.getAccountIdentifier(), projectParams.getOrgIdentifier(),
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 755 at r1](https://reviewable.io/reviews/harness/harness-core/39778#-NGQI-QE-iRU6FEmvhRT:-NGQI-QE-iRU6FEmvhRU:b5x52o3) ([raw file](https://github.com/harness/harness-core/blob/a3755bd67b03dc2b2f8bb947a6754960cce9e83d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L755)):*
> ```Java
>         .projectIdentifier(slo.getProjectIdentifier())
>         .serviceLevelObjectiveRef(slo.getIdentifier());
>   }
> ```

move this to SimpleSLODetails class



_Code quote:_
```Java
  private SimpleSLODetailsBuilder getSimpleSLODetailsBuilder(AbstractServiceLevelObjective slo) {
    return SimpleSLODetails.builder()
        .accountId(slo.getAccountId())
        .orgIdentifier(slo.getOrgIdentifier())
        .projectIdentifier(slo.getProjectIdentifier())
        .serviceLevelObjectiveRef(slo.getIdentifier());
  }
```

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLOServiceImpl.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/39778#-NGQEvIOCkKJrcHYGAZw:-NGQEvIOCkKJrcHYGAZx:b-yeojb) ([raw file](https://github.com/harness/harness-core/blob/a3755bd67b03dc2b2f8bb947a6754960cce9e83d/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLOServiceImpl.java#L28)):*
> ```Java
>       SimpleServiceLevelObjective simpleServiceLevelObjective) {
>     List<AbstractServiceLevelObjective> compositeServiceLevelObjectives =
>         hPersistence.createQuery(AbstractServiceLevelObjective.class)
> ```

Can we create the keys on the serviceLevelObjectiveDetails project, org and account identifier and ref and make a direct DB call so that we don't have to iterate over the complete list.

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImplTest.java` line 379 at r2](https://reviewable.io/reviews/harness/harness-core/39778#-NGUYQafD21Z77tmRTZ9:-NGUYQafD21Z77tmRTZA:bl0pt03) ([raw file](https://github.com/harness/harness-core/blob/fa57a3d15a435f7061e141cf0bd34c010c9d05da/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImplTest.java#L379)):*
> ```Java
>   public void testDelete_SimpleSLO_AssociatedWith_CompositeSLO_Failure() {
>     List<String> referencedCompositeSLOIdentifiers =
>         serviceLevelObjectiveV2Service.getReferencedCompositeSLOs(simpleServiceLevelObjective1)
> ```

nit: If you have just made the method public for testing, then you could have marked @VisibleForTesting.



_Code quote:_
```Java
getReferencedCompositeSLO
```

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778#-:-NGUYu0B1zQTTE6V2LbF:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39778)* status: :shipit: complete! ✓

**Pull request merged**
