### PR TITLE
feat: [OPA-263]: Enable full git sync for OPA policy mgmt service

### PR DESCRIPTION
**Pull request by scottyw**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32165)

### CODE REVIEW

**Comment by scottyw** [comment]
@bojanmicovic @DeepakPatankar You reviewed my last Git Sync change - would it be possible to give this one a look as well? Thanks!

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32165)* status: :shipit: complete! ✓

**Comment by scottyw** [comment]
trigger ti3

**Comment by scottyw** [comment]
Thanks for the review @bojanmicovic - I fixed the broken test and it looks green now.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32165)* status: :shipit: complete! ✓

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32165)* status: :shipit: complete! ✓

**Pull request merged**
