### PR TITLE
[feat]: [PL-24144]: Ng variables get API

### PR DESCRIPTION
**Pull request by nishantsaini20**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32775)

### CODE REVIEW

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32775)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32775)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/32775#-N1JK2hJEFFOPBUcMp2e:-N1JK2hJEFFOPBUcMp2f:b7rgk5u) ([raw file](https://github.com/harness/harness-core/blob/554be63b9cbfd415997f3808c2d75ae2de455a8f/120-ng-manager/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java#L62)):*
> ```Java
>   @Hidden
>   public ResponseDTO<VariableResponseDTO> get(@PathParam(IDENTIFIER_KEY) @NotNull String identifier,
>       @QueryParam(ACCOUNT_KEY) @NotNull String accountIdentifier, @QueryParam(ORG_KEY) String orgIdentifier,
> ```

Please add @Paramter annotation to all the parameters in the api.
Example: For accountIdentifier, please add @Parameter(description = ACCOUNT_PARAM_MESSAGE) before to this @QueryParam(ACCOUNT_KEY) @NotNull String accountIdentifier.
For more context please refer any of the resource files like connectorResource.java

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32775)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/32775#-N1JK2hJEFFOPBUcMp2e:-N1JKsFR5b7xqq1wpHCt:b-jnaw6u) ([raw file](https://github.com/harness/harness-core/blob/554be63b9cbfd415997f3808c2d75ae2de455a8f/120-ng-manager/src/main/java/io/harness/ng/core/variable/resources/VariableResource.java#L62)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

Please add @Paramter annotation to all the parameters in the api.
Example: For accountIdentifier, please add @Parameter(description = ACCOUNT_PARAM_MESSAGE) before to this @QueryParam(ACCOUNT_KEY) @NotNull String accountIdentifier.
For more context please refer any of the resource files like connectorResource.java
</blockquote></details>

Are you referring to annotations for Open API doc. If yes then we'll be adding them in a separate PR. Therefore marked API as hidden for now.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32775)* status: :shipit: complete! ✓

**Pull request merged**
