### PR TITLE
[feat]: [SRM-10531]: refactored NotificationRuleDTO & Entity for SLO + added support for ErrorBudgetRemainingMinutes & ErrorBudgetBurnRate for SLO

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32868)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32868)* status: 16 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLOErrorBudgetBurnRateConditionSpec.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/32868#-N1RYEAOE4PfAoBm-mJO:-N1RYEAOE4PfAoBm-mJP:bk8ykjv) ([raw file](https://github.com/harness/harness-core/blob/2f19e9a57492178b5408bfaaec786771b5cd48bd/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLOErrorBudgetBurnRateConditionSpec.java#L25)):*
> ```Java
> public class SLOErrorBudgetBurnRateConditionSpec extends SLONotificationRuleConditionSpec {
>   @NonNull Double threshold;
>   @NonNull long lookBackDuration;
> ```

this should be a string with 10m, 20m because that is our yaml convention.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/32868#-N1Rd8nQA1VKQT_05YpW:-N1Rd8nQA1VKQT_05YpX:b1qfy27) ([raw file](https://github.com/harness/harness-core/blob/2f19e9a57492178b5408bfaaec786771b5cd48bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L405)):*
> ```Java
>       ServiceLevelObjective serviceLevelObjective, SLONotificationRuleEntityCondition condition) {
>     SLOHealthIndicator sloHealthIndicator = sloHealthIndicatorService.getBySLOEntity(serviceLevelObjective);
>     boolean isErrorBudgetRemainingPercentageBelowThreshold =
> ```

writing conditions like this is not testable and scalable. Let's talk once you are available.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32868)* status: 16 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLOErrorBudgetBurnRateConditionSpec.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/32868#-N1RYEAOE4PfAoBm-mJO:-N1SuQDn2ttFKOjf2KaZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2f19e9a57492178b5408bfaaec786771b5cd48bd/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLOErrorBudgetBurnRateConditionSpec.java#L25)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this should be a string with 10m, 20m because that is our yaml convention.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/32868#-N1Rd8nQA1VKQT_05YpW:-N1SuT4BDTVx-8Dfl4O1:b96csqk) ([raw file](https://github.com/harness/harness-core/blob/2f19e9a57492178b5408bfaaec786771b5cd48bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L405)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

writing conditions like this is not testable and scalable. Let's talk once you are available.
</blockquote></details>

accepted, I was facing a lot of challenges while designing this. 
I have come up with a new design, let me know your thoughts.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 16 files at r1, 34 of 34 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32868#-:-N1fi8H2-HHhiSjYLdjT:bnfp4nl)* status: 1. unresolved discussions.

**Review by kjoshi12345 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32868)* status: :shipit: complete! ✓

**Pull request merged**
