### PR TITLE
feat: [CDS-38232]: Add release repo manifest type

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Adding a new ManifestType of ReleaseRepo. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)

### CODE REVIEW

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ReleaseRepoManifestOutcome.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/33874#-N3cLEQsDec8R3pZTMlG:-N3cLEQsDec8R3pZTMlH:b-466ie7) ([raw file](https://github.com/harness/harness-core/blob/b0e2549f7b584133b92d588f8114cead97478fb2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ReleaseRepoManifestOutcome.java#L1)):*
> ```Java
> package io.harness.cdng.manifest.yaml;
> ```

Add Harness License info
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/33874#-N3cLH8g64qTl5Hw7TVy:-N3cLH8g64qTl5Hw7TVz:b-466ie7) ([raw file](https://github.com/harness/harness-core/blob/b0e2549f7b584133b92d588f8114cead97478fb2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java#L1)):*
> ```Java
> package io.harness.cdng.visitor.helpers.manifest;
> ```

Add Harness License info
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java` line 4 at r2](https://reviewable.io/reviews/harness/harness-core/33874#-N3cKual5txNUNfgZNgm:-N3cKuamAai6OMhr5gCi:bgh17lr) ([raw file](https://github.com/harness/harness-core/blob/b0e2549f7b584133b92d588f8114cead97478fb2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java#L4)):*
> ```Java
> 
> import io.harness.cdng.manifest.yaml.kinds.ReleaseRepoManifest;
> import io.harness.cdng.manifest.yaml.kinds.ValuesManifest;
> ```

Might have to remove this

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ReleaseRepoManifestOutcome.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/33874#-N3cLEQsDec8R3pZTMlG:-N3cRnrbCXLRtWfWOnpa:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/b0e2549f7b584133b92d588f8114cead97478fb2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ReleaseRepoManifestOutcome.java#L1)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add Harness License info
</blockquote></details>

added
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/33874#-N3cLH8g64qTl5Hw7TVy:-N3cRpn18kbydFcL1W6E:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/b0e2549f7b584133b92d588f8114cead97478fb2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java#L1)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add Harness License info
</blockquote></details>

added
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java` line 4 at r2](https://reviewable.io/reviews/harness/harness-core/33874#-N3cKual5txNUNfgZNgm:-N3cRrLj2VChEqqwJavZ:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/b0e2549f7b584133b92d588f8114cead97478fb2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/ReleaseRepoManifestVisitorHelper.java#L4)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Might have to remove this
</blockquote></details>

Removed

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger messagecheck

**Review by anshul-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger codeformat

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 1 of 8 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 8 files at r4, 7 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 8 of 8 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33874)* status: :shipit: complete! ✓

**Pull request merged**
