### PR TITLE
feat:[CDS-81774]: Handling NPE when instance info is not provided by the custom image

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

Handling NPE when instance info is not provided by the custom image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54441)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by PragyeshMishra01 — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/54441#-NhQLt5u9c6e2e4fEg6p:-NhQLt5u9c6e2e4fEg6q:b4qkbt) ([raw file](https://github.com/harness/harness-core/blob/323ff689b51fb7345ec176a1595654292d50534f/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java#L130)):*
> ```Java
>       StepOutput stepOutput = stepStatusTaskResponseData.getStepStatus().getOutput();
> 
>       List<ServerInstanceInfo> serverInstanceInfoList = null;
> ```

should this not be an empty list by default ?

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54441)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/54441#-NhQQgKk2vh1ggSoR4pj:-NhQQgKl2oa61FYOttep:ba4p6gq) ([raw file](https://github.com/harness/harness-core/blob/323ff689b51fb7345ec176a1595654292d50534f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L146)):*
> ```Java
>           String instancesByte64 = stepMapOutput.getMap().get("instances");
>           log.info(String.format("AWS SAM Deploy instances byte64 %s", instancesByte64));
>           instances = new String(Base64.getDecoder().decode(instancesByte64));
> ```

There is no point in calling Base64.getDecoder().decode(instancesByte64) if instancesByte64 is null or empty.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/54441#-NhQQvc97QrKh0nU-M2s:-NhQQvc97QrKh0nU-M2t:bekmhs3) ([raw file](https://github.com/harness/harness-core/blob/323ff689b51fb7345ec176a1595654292d50534f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L151)):*
> ```Java
> 
>         log.info(String.format("AWS SAM Deploy: Parsing instances from JSON %s", instances));
>         serverInstanceInfoList = Arrays.asList(objectMapper.readValue(instances, AwsSamServerInstanceInfo[].class));
> ```

The same here, there is no point in calling objectMapper.readValue(instances, AwsSamServerInstanceInfo[].class) when instances are null or empty, instead just return an empty list for server instances. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/54441#-NhQLt5u9c6e2e4fEg6p:-NhQRNJ3-kh2_28LXUmx:bwfdizj) ([raw file](https://github.com/harness/harness-core/blob/323ff689b51fb7345ec176a1595654292d50534f/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java#L130)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should this not be an empty list by default ?
</blockquote></details>

yes, agree, it should be an empty list by default.

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54441)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/54441#-NhRYRHaADIbbB3w3DEH:-NhRYRHaADIbbB3w3DEI:b-a5y1zf) ([raw file](https://github.com/harness/harness-core/blob/8a9ff9c50481ad8f99498d5e4911445b20b179d2/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamStepHelper.java#L147)):*
> ```Java
>           String instancesByte64 = stepMapOutput.getMap().get("instances");
>           log.info(String.format("AWS SAM Deploy instances byte64 %s", instancesByte64));
>           instances = new String(Base64.getDecoder().decode(instancesByte64));
> ```

Local variable String instances = null; is only populated if 'stepOutput instanceof StepMapOutput', hence move it as part of if block statement.
 Also, serverInstanceInfoList = Arrays.asList(objectMapper.readValue(instances, AwsSamServerInstanceInfo[].class));  should be as part of the same if block. 

Also, 
If (isEmpty(instancesByte64)) {
//log that there are no instances if needed. 
return serverInstanceInfoList; // there is no need to get/catch NPE in Base64.getDecoder().decode(). We can log that there are no instances before returning an empty list. 
}

Also, optimize logs, heaving three info logs in the same method for the same flow.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/54441#-NhQLt5u9c6e2e4fEg6p:-NhRtVJZ2nBJUj2IGIJO:bautnf2) ([raw file](https://github.com/harness/harness-core/blob/323ff689b51fb7345ec176a1595654292d50534f/125-cd-nextgen/src/main/java/io/harness/cdng/serverless/container/steps/ServerlessAwsLambdaDeployV2Step.java#L130)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

yes, agree, it should be an empty list by default.
</blockquote></details>

I think its better to set it to new ArrayList<>();
because  Collections.emptyList() produces a new immutable list and adding to it would cause exception

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger review

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54441#-:-NhS3lVWBAF47ldHsJJk:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rafaelmart1ns — APPROVED** [review]

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Review by PragyeshMishra01 — APPROVED** [review]

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54441#-:-Nha9TGK399JMj86fnXL:bnfp4nl)* status: 3 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54441)* status: :shipit: complete! ✓

**Comment by piyush-bhuwalka** [comment]
trigger review

**Pull request merged**
