### PR TITLE
fix: [CDS-53224]: Evaluate NG Command units variables

### PR DESCRIPTION
**Pull request by ivan-83**
Added support for evaluating NG Command units variable for the following properties,
- ScriptCommandUnit.workingDirectory
- NgDownloadArtifactCommandUnit.destinationPath
- CopyCommandUnit.destinationPath

Also, replaced @Value with appropriate annotations that it contains itself and apply @Setter on properties where only it is needed. 

Screenshot 2023-02-23 at 17 13 02

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44301)

### CODE REVIEW

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44301)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
how about winrm?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44301#-:-NOzuoF5B_hWr74tb7UG:bwc89c)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — COMMENTED** [review]
I think we need more discussion on how to propagate variables for WinRm, which format to use $variableName or, %variableName% or %env:variableName. I suggest going with the current changes for SSH only because this is urgent for customers based on comments on the ticket and we can create a separate ticket for WinRm and get the inputs from PMs if needed. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44301#-:-NOzz7gj9xoHkOWyByoD:buiokao)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44301)* status: 4 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44301)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44301)* status: :shipit: complete! ✓

**Pull request merged**
