### PR TITLE
feat: [CDS-46433]: Delegate changes: K8s & Native Helm (CG - Direct Kubernetes Cluster) Instance sync V2 implementation Revisit

### PR DESCRIPTION
**Pull request by namantalaycha10**
…ubernetes Cluster) Instance sync V2 implementation Revisit

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40031)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40031)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
trigger checkstyle

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40031)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
trigger ft1

**Comment by namantalaycha10** [comment]
trigger FTjUUCrgRSme6LMa7Cazvg

**Comment by namantalaycha10** [comment]
trigger featurenamecheck

**Comment by jennyjames21** [comment]
Can you add a summary and test performed?

**Comment by namantalaycha10** [comment]
Changes Summary:
1. These changes are behind the feature Flag 
2. No tests are failing because of these changes
these changes are backward compatible and we are not enable the FF for any customer until we complete the full feature

**Pull request closed without merging**
