### PR TITLE
[feat]: [CDS-17424]: Create WinRmExecutorFactoryNG in 930 module and …

### PR DESCRIPTION
**Pull request by vitsafronovici**
…FileBasedWinRmExecutorNG

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedWinRmExecutor.java, line 47 at r1](https://reviewable.io/reviews/harness/harness-core/31028#-MwwxPhhCAUpUqU0qY_C:-MwwxPhhCAUpUqU0qY_D:bht728r) ([raw file](https://github.com/harness/harness-core/blob/037c130e91a940aac0dabc80adc06a3ec8f17a39/400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedWinRmExecutor.java#L47)):*
> ```Java
>   @Override
>   public byte[] getConfigFileBytes(ConfigFileMetaData configFileMetaData) throws IOException {
>     try (InputStream is = delegateFileManager.downloadByConfigFileId(configFileMetaData.getFileId(),
> ```

@yogesh-chauhan @acasian-harness  we haven't moved the whole class to 930-delegate-task because of delegateFileManager.downloadByConfigFileId method. 

Should we start refactoring delegateFileManager manager part by part?
- Find an appropriate module for NG delegateFileManager where it can be consumed by 930-delegate-task
- I see delegateFileManager.downloadByConfigFileId uses delegateAgentManagerClient do download config files which is in 420-delegate-agent. Are you aware is there any other delegateAgentManagerClient that we can use on 930-delegate-task to download files from the manager?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedWinRmExecutor.java, line 47 at r1](https://reviewable.io/reviews/harness/harness-core/31028#-MwwxPhhCAUpUqU0qY_C:-Mx2FR_l5G3ah_8OyLP1:b4lgf1o) ([raw file](https://github.com/harness/harness-core/blob/037c130e91a940aac0dabc80adc06a3ec8f17a39/400-rest/src/main/java/software/wings/core/ssh/executors/FileBasedWinRmExecutor.java#L47)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@yogesh-chauhan @acasian-harness  we haven't moved the whole class to 930-delegate-task because of delegateFileManager.downloadByConfigFileId method. 

Should we start refactoring delegateFileManager manager part by part?
- Find an appropriate module for NG delegateFileManager where it can be consumed by 930-delegate-task
- I see delegateFileManager.downloadByConfigFileId uses delegateAgentManagerClient do download config files which is in 420-delegate-agent. Are you aware is there any other delegateAgentManagerClient that we can use on 930-delegate-task to download files from the manager? 


</blockquote></details>

Yes, we should move it part by part. On the second part, lets sync up offline, I am not aware offhand about the same

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Review by filip5rovic — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Review by bojanmicovic — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31028#-:-MzZs5CWECn7ZmErgJSn:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
