### PR TITLE
feat: [PL-24532]: Added new branch listing API

### PR DESCRIPTION
**Pull request by bhavya181**
Added new branch list API that will return default branch details also
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32672)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitBranchesResponseDTO.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N1033S596orj6Q-ZFps:-N1033S596orj6Q-ZFpt:b-tfxj2o) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitBranchesResponseDTO.java#L17)):*
> ```Java
> @OwnedBy(PL)
> public class GitBranchesResponseDTO {
>   @Schema(description = "This contains details of all the branches of given repo.") List<GitBranchDetailsDTO> branches;
> ```

This doesn't show all branches right? This would basically be paginated response.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103F9v1rZrkBlnj6lV:-N103F9v1rZrkBlnj6lW:b4f74tn) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L306)):*
> ```Java
> 
>   @GET
>   @Path("list-branches-by-connector")
> ```

it should just be list-branches, we don't need to append by connector, doesn't make much sense.

eg: if it was 1:1 mapping with repo, then still would have made some sense, but it can be a git account level connector.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103QgECOy69gthsljT:-N103QgECOy69gthsljU:b-88b3ij) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L308)):*
> ```Java
>   @Path("list-branches-by-connector")
>   @ApiOperation(
>       value = "Lists Git Branches of given repo by reference connector", nickname = "getListOfBranchesByRefConnectorV2")
> ```

same changes in descrtiption here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 319 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103WD3EoRZQTy2WsFJ:-N103WD3EoRZQTy2WsFK:btooedj) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L319)):*
> ```Java
>       hidden = true)
>   public ResponseDTO<GitBranchesResponseDTO>
>   listUserRepo(@Parameter(description = ACCOUNT_PARAM_MESSAGE) @NotBlank @QueryParam(
> ```

name of method wrong.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103QgECOy69gthsljT:-N103itN4wK0_FuosBig:bflmc7v) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L308)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same changes in descrtiption here.
</blockquote></details>

we can take this up later as well when we plan to make the API live on OAS 3.0.

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672)* status: 0 of 1 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672)* status: 2 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitBranchesResponseDTO.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N1033S596orj6Q-ZFps:-N12pYVYBJBdeUr4rx-b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/GitBranchesResponseDTO.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This doesn't show all branches right? This would basically be paginated response.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103F9v1rZrkBlnj6lV:-N12pZA57yWhnbnG1nQG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L306)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it should just be list-branches, we don't need to append by connector, doesn't make much sense.

eg: if it was 1:1 mapping with repo, then still would have made some sense, but it can be a git account level connector.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103QgECOy69gthsljT:-N12pZd84C0zRa-XkJ99:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L308)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can take this up later as well when we plan to make the API live on OAS 3.0.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 319 at r1](https://reviewable.io/reviews/harness/harness-core/32672#-N103WD3EoRZQTy2WsFJ:-N12p_Y_5kxOcQ9qIh_R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ee1f766d07b0d016818f7adfcf231e457299677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L319)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

name of method wrong.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672#-:-N12qhKiESiwzyEh-LUG:bnfp4nl)* status: :shipit: complete! ✓

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672)* status: :shipit: complete! ✓

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672#-:-N12tXrcDAnRPes6_wuO:bnfp4nl)* status: :shipit: complete! ✓

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32672#-:-N12xpp9EP1HCMXFj08y:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
