### PR TITLE
Feat: [SRM-14300]: Update DTO and entity for consecutive error budget…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
… burndown

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45565)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45565)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slimetricspec/RatioSLIMetricSpec.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/45565#-NRHYf-G551rjrD9aDWi:-NRHYf-G551rjrD9aDWj:b54bk4b) ([raw file](https://github.com/harness/harness-core/blob/f800403a1f42d1590589645580c13fdf17b36bb7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slimetricspec/RatioSLIMetricSpec.java#L33)):*
> ```Java
>   @NotNull ThresholdType thresholdType;
> 
>   @Builder.Default int considerConsecutiveMinutes = 1;
> ```

why do we need a default for it?
It will be tougher if customer doesn't send this data we populate it. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/45565#-NRHZ8PQE1wfx1x49f_t:-NRHZ8PQE1wfx1x49f_u:b-o9it4a) ([raw file](https://github.com/harness/harness-core/blob/f800403a1f42d1590589645580c13fdf17b36bb7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java#L41)):*
> ```Java
>   Integer considerConsecutiveMinutes;
> 
>   Boolean considerAllConsecutiveMinutesFromStartAsBad;
> ```

we can have getter methods with default value. That will avoid migration need as well,
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelindicator/ThresholdServiceLevelIndicatorTransformer.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/45565#-NRHZFp7CCHuJdl3hK0A:-NRHZFp7CCHuJdl3hK0B:bjphpvn) ([raw file](https://github.com/harness/harness-core/blob/f800403a1f42d1590589645580c13fdf17b36bb7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelindicator/ThresholdServiceLevelIndicatorTransformer.java#L35)):*
> ```Java
>         .metric1(thresholdSLIMetricSpec.getMetric1())
>         .considerConsecutiveMinutes(thresholdSLIMetricSpec.getConsiderConsecutiveMinutes())
>         .considerAllConsecutiveMinutesFromStartAsBad(
> ```

we need to add test case for it.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45565)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/45565#-NRI5WJa3FIm6TuzpVJ4:-NRI5WJa3FIm6TuzpVJ5:b9xwfyo) ([raw file](https://github.com/harness/harness-core/blob/e4d3102876254517a73e2b4cb982b64fca175b1e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java#L72)):*
> ```Java
>           .set(RatioServiceLevelIndicatorKeys.thresholdValue, ratioServiceLevelIndicator.getThresholdValue())
>           .set(RatioServiceLevelIndicatorKeys.thresholdType, ratioServiceLevelIndicator.getThresholdType());
>       if (ratioServiceLevelIndicator.getConsiderConsecutiveMinutes() != null) {
> ```

why do we need null check? can't we just update with null?

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45565)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slimetricspec/RatioSLIMetricSpec.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/45565#-NRHYf-G551rjrD9aDWi:-NRIKUULCHxtnzt99PRA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f800403a1f42d1590589645580c13fdf17b36bb7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/slimetricspec/RatioSLIMetricSpec.java#L33)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

why do we need a default for it?
It will be tougher if customer doesn't send this data we populate it. 

</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/45565#-NRHZ8PQE1wfx1x49f_t:-NRHZt0F77ae9qb6z8Wv:by8h2w8) ([raw file](https://github.com/harness/harness-core/blob/f800403a1f42d1590589645580c13fdf17b36bb7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java#L41)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

we can have getter methods with default value. That will avoid migration need as well,
</blockquote></details>

Migration there is still no need, because in the entity to dto transformer I have handled null scenario. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/45565#-NRI5WJa3FIm6TuzpVJ4:-NRIKGG23-tPSDlO45bM:b22ql15) ([raw file](https://github.com/harness/harness-core/blob/e4d3102876254517a73e2b4cb982b64fca175b1e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RatioServiceLevelIndicator.java#L72)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

why do we need null check? can't we just update with null?
</blockquote></details>

no it throws NPE. If you see in all our entities whenever we update desciption, we do this as well.
Earlier I missed this so tcs failed https://app.harness.io/ng/#/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/TIAll/executions/tvNCwaGDRF2jhzUwOlQSCg/tests?stage=IZRwri0yS1O-9KBR1O_eug&stageExecId=t36B9iKqQoG5nSEC3-Duyg
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelindicator/ThresholdServiceLevelIndicatorTransformer.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/45565#-NRHZFp7CCHuJdl3hK0A:-NRIKT4iA0VIC5AciyD3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f800403a1f42d1590589645580c13fdf17b36bb7/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelindicator/ThresholdServiceLevelIndicatorTransformer.java#L35)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

we need to add test case for it.
</blockquote></details>

Done.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45565)* status: :shipit: complete! ✓

**Pull request merged**
