### PR TITLE
feat: [IDP-724]: Setup for IDP Stage

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50815)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger uts

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 7 of 41 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50815)* status: Some of the checks are too old. 41 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/app/IdpApplication.java` line 96 at r5](https://reviewable.io/reviews/harness/harness-core/50815#-Na5Jc4v8AdkBN5OapwK:-Na5Jc4v8AdkBN5OapwL:b-k3vn76) ([raw file](https://github.com/harness/harness-core/blob/5a37f06be31c85656b785e244851296d9f68095a/idp-service/src/main/java/io/harness/idp/app/IdpApplication.java#L96)):*
> ```Java
> import com.github.dirkraft.dropwizard.fileassets.FileAssetsBundle;
> import com.google.common.util.concurrent.ThreadFactoryBuilder;
> import com.google.inject.*;
> ```

nit: we could avoid wildcards. This can be configured in IntelliJ as well.



_Code quote:_
```Java
*
```
___
*[`idp-service/src/main/java/io/harness/idp/app/IdpModule.java` line 348 at r5](https://reviewable.io/reviews/harness/harness-core/50815#-Na5VNSD3dYYDd0jfqe3:-Na5VNSD3dYYDd0jfqe4:b-ogp8g7) ([raw file](https://github.com/harness/harness-core/blob/5a37f06be31c85656b785e244851296d9f68095a/idp-service/src/main/java/io/harness/idp/app/IdpModule.java#L348)):*
> ```Java
>     install(NgLicenseHttpClientModule.getInstance(appConfig.getNgManagerServiceHttpClientConfig(),
>         appConfig.getNgManagerServiceSecret(), IDP_SERVICE.getServiceId()));
>     install(new SSCAServiceClientModuleV2(appConfig.getSscaServiceConfig(), IDP_SERVICE.getServiceId()));
> ```

Could we check with SSCA team reg. this? Can this be installed in the CIExecution...Module itself?

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50815)* status: Some of the checks are too old. 41 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/app/IdpModule.java` line 331 at r5](https://reviewable.io/reviews/harness/harness-core/50815#-Na5ZTL06qER-65uMmUE:-Na5ZTL06qER-65uMmUF:b-aphoo5) ([raw file](https://github.com/harness/harness-core/blob/5a37f06be31c85656b785e244851296d9f68095a/idp-service/src/main/java/io/harness/idp/app/IdpModule.java#L331)):*
> ```Java
>     install(DelegateServiceDriverModule.getInstance(false, false));
>     install(ExceptionModule.getInstance());
>     //    install(new AbstractWaiterModule() {
> ```

Have we tested whether the existing delegate flow works without this installation?

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 32 of 41 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50815)* status: Some of the checks are too old. 41 file(s) to review. 0 of 2 approvals obtained.

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut1,ut5

**Comment by devesh-harness** [comment]
trigger uts

**Review by raghavharness — DISMISSED** [review]

**Comment by devesh-harness** [comment]
trigger ut4, ut9

**Pull request closed without merging**
