### PR TITLE
[fix]: [PL-27345]: Search Users in NG before acknowledging to SCIM Provider.

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36280)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36280)

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BNkA_3Wg_Gi2mEWua:-N9BNkA_3Wg_Gi2mEWub:b-17mxua) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L147)):*
> ```Java
>     log.info("NGSCIM: completed search. accountId {}, search query {}, resultSize: {}", accountId, filter,
>         result.getTotalResults());
>     if (result.getTotalResults() > 0) {
> ```

nit: use `isNotEmpty` , thanks

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BNpW543lkBacWXGh7:-N9BNpW543lkBacWXGh8:b-z1c1h2) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L157)):*
> ```Java
>     for (ScimUser scimUser : result.getResources()) {
>       Optional<UserMetadataDTO> userOptional = ngUserService.getUserByEmail(scimUser.getUserName(), false);
>       if (!userOptional.isPresent()) {
> ```

nit: replace with `isEmpty()` predicate here instead of !isPresent(), thanks

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BOLhWBuBvQG87Vj86:-N9BOLhWBuBvQG87Vj87:bygxcau) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L162)):*
> ```Java
>     }
>     if (usersNotinNG.size() > 0) {
>       List<ScimUser> updatedResources = result.getResources();
> ```

Please add some logs here which will help to identify this corrected flow, thanks

**Review by pbarapatre10 — COMMENTED** [review]
lets add Unit tests for this flow, thanks

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36280#-:-N9BOYu37Zf2qYFeSW6F:b-9pf4ar)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by boopesh007** [comment]
trigger messagecheck

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BNkA_3Wg_Gi2mEWua:-N9BXRFT1N73NSFAmQ9S:bvwh1zd) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L147)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: use `isNotEmpty` , thanks
</blockquote></details>

result.getTotalResults() is also fine @pbarapatre10 because when we call CG, it will actually send us an object with all these details filled. It will not be empty.



_Code quote:_
```Java
result.getTotalResults(
```

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BOLhWBuBvQG87Vj86:-N9BXsFs00SuPhbGdLww:btt7hl7) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L162)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Please add some logs here which will help to identify this corrected flow, thanks
</blockquote></details>

Agree. Please add a log line like below so that we know what was changed:
"    log.info("NGSCIM: completed ng search. accountId {}, search query {}, resultSize: {}", accountId, filter,
        result.getTotalResults());
"



_Code quote:_
```Java
    log.info("NGSCIM: completed search. accountId {}, search query {}, resultSize: {}", accountId, filter,
        result.getTotalResults());
```

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BNpW543lkBacWXGh7:-N9BY93e8271zbyf0jY6:b7fyi39) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L157)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: replace with `isEmpty()` predicate here instead of !isPresent(), thanks
</blockquote></details>

isPresent is fine here as its an optional.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/36280#-N9BNpW543lkBacWXGh7:-N9CbMM92h5sEs7JV9Ac:b-jd85dp) ([raw file](https://github.com/harness/harness-core/blob/446a59efab80e54b5732df9195947362d98acc27/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L157)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

isPresent is fine here as its an optional.
</blockquote></details>

sure. isEmpty() is a new construct introduced in JDK 11 & its purpose is the exact same. But fine, use of isPresent() doesn't break anything

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java` line 202 at r4](https://reviewable.io/reviews/harness/harness-core/36280#-N9Ccjdq7lX2pU8Or4Kn:-N9Ccjdq7lX2pU8Or4Ko:bx54j5l) ([raw file](https://github.com/harness/harness-core/blob/fda3bdcc52a75f363fc7341fe71ea4fff2a24c74/120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java#L202)):*
> ```Java
>     when(ngUserService.searchScimUsersByEmailQuery(anyString(), anyString(), any(), any()))
>         .thenReturn(scimUserScimListResponse);
>     when(ngUserService.getUserByEmail(anyString(), anyBoolean())).thenReturn(Optional.ofNullable(null));
> ```

Minor Can use Optional.empty()



_Code quote:_
```Java
Optional.ofNullable(null)
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java` line 228 at r4](https://reviewable.io/reviews/harness/harness-core/36280#-N9CdCVz2ps2GjE8Veov:-N9CdCW-2-HAlS__Rwf-:br4gat) ([raw file](https://github.com/harness/harness-core/blob/fda3bdcc52a75f363fc7341fe71ea4fff2a24c74/120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java#L228)):*
> ```Java
>     ScimListResponse<ScimUser> result = scimUserService.searchUser("accountId", "filter", 1, 0);
>     assertThat(result.getTotalResults()).isEqualTo(1);
>     assertThat(result.getResources().size()).isEqualTo(1);
> ```

Minor : we can assert for userName & displayName as well. Thanks

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36280)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by boopesh007** [comment]
trigger codebasehash

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36280)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36280)* status: :shipit: complete! ✓

**Pull request merged**
