### PR TITLE
fix: [DEL-5659]: Fix on release delegate profile

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Release delegate profile lock when profile is not executing but lock file exists

Test Performed
- Unit testing
- Sanity test on new profile applied and delegate coming with profile

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42353)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
Sanity 
Profile apply 
image

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1099 at r1](https://reviewable.io/reviews/harness/harness-core/42353#-NLJgzbq3HB_UBYalM2j:-NLJgzbq3HB_UBYalM2k:b-hk9hoz) ([raw file](https://github.com/harness/harness-core/blob/fdac91e30866a198d398ea8870676cd768906d6f/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1099)):*
> ```Java
>           shouldContactManager(), executingProfile.get(), isLocked(new File("profile")), frozen.get());
>       File profileFile = new File("profile");
>       if (!executingProfile.get() && isLocked(profileFile)) {
> ```

was this the issue with the customer?  also why change file name? also why remove the time check? it could be in addition.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42353)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1099 at r1](https://reviewable.io/reviews/harness/harness-core/42353#-NLJgzbq3HB_UBYalM2j:-NLMe-3x71pV5XVQLBED:b44l55v) ([raw file](https://github.com/harness/harness-core/blob/fdac91e30866a198d398ea8870676cd768906d6f/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1099)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

for this customer we know from log , always getting 
{currently executing profile :false, isLocked :true} 
Profile gets locked when profile is executing and release lock once completed. So we can rely on 2 vars(executingProfile & isLocked) to decide lock file exists. 

Prev statement was wrong and also I don't think its profile lastmodified is getting updated correctly so not sure we should rely on lastModified.

File name changed since we don't use lastModified anymore, lock file directly
</blockquote></details>

https://cloudlogging.app.goo.gl/iBYP3qpEQmNyUJsLA

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42353)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
