### PR TITLE
feat: [PL-31511]: changed moduleType default implementation

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
changed ModuleType enum default implementation to set ignore field as true.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44425)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44425)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ModuleType.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44425#-NPLF8PM6aS1c-iTmcSc:-NPLF8PM6aS1c-iTmcSd:b-qfi4hb) ([raw file](https://github.com/harness/harness-core/blob/cc28f220d52f8a84f0f1f2bebaaa034e6ef98aee/970-ng-commons/src/main/java/io/harness/ModuleType.java#L50)):*
> ```Java
>   boolean ignore;
> 
>   ModuleType(String displayName) {
> ```

Can we remove this constructor altogether?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44425)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ModuleType.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44425#-NPLF8PM6aS1c-iTmcSc:-NPM9m-K2ZbZL3btImyL:bchuyy3) ([raw file](https://github.com/harness/harness-core/blob/cc28f220d52f8a84f0f1f2bebaaa034e6ef98aee/970-ng-commons/src/main/java/io/harness/ModuleType.java#L50)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we remove this constructor altogether?
</blockquote></details>

how will we set default variable then

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44425)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ModuleType.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44425#-NPLF8PM6aS1c-iTmcSc:-NPMBMMf645UjMbU-wpn:bme13sv) ([raw file](https://github.com/harness/harness-core/blob/cc28f220d52f8a84f0f1f2bebaaa034e6ef98aee/970-ng-commons/src/main/java/io/harness/ModuleType.java#L50)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

how will we set default variable then
</blockquote></details>

Default Variable?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44425)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ModuleType.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44425#-NPLF8PM6aS1c-iTmcSc:-NPMCSaz0-jUk32QroLC:bo246za) ([raw file](https://github.com/harness/harness-core/blob/cc28f220d52f8a84f0f1f2bebaaa034e6ef98aee/970-ng-commons/src/main/java/io/harness/ModuleType.java#L50)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Default Variable?
</blockquote></details>

I mean how will we set default value of 'ignore' to true, again devs will just copy another enum with its value as false

**Comment by bhavya181** [comment]
trigger feature-build

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44425#-:-NPNC3EPCsFQ9Nuyz4vi:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by bhavya181** [comment]
rigger ut5, trigger ut6, trigger ut7, trigger ut8, trigger ut9

**Comment by bhavya181** [comment]
trigger ut5, trigger ut6, trigger ut7, trigger ut8, trigger ut9

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44425)* status: :shipit: complete! ✓

**Pull request merged**
