### PR TITLE
feat: [SRM-14055]: Added RequestServiceLevelIndicator

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44351)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44351)* status: 24 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java` line 870 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPaqJmT6mJeiSSC0CP-:-NPaqJmT6mJeiSSC0CP0:b-lra56x) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java#L870)):*
> ```Java
>     MapBinder<String, ServiceLevelIndicatorUpdatableEntity> serviceLevelIndicatorMapBinder =
>         MapBinder.newMapBinder(binder(), String.class, ServiceLevelIndicatorUpdatableEntity.class);
>     serviceLevelIndicatorMapBinder.addBinding(SLIExecutionType.WINDOW_BASED.name() + "_" + SLIMetricType.RATIO.name())
> ```

You can have an abstract method getSLIMetricAndEvaluationType()
and these getEvaluationType() + "_" + getMetricType() can go there
RatioServiceLevelIndicator.getSLIMetricAndEvaluationType();
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIExecutionType.java` line 16 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPasczI9WFfkX5zAWpR:-NPasczI9WFfkX5zAWpS:bz9p7hp) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIExecutionType.java#L16)):*
> ```Java
> @AllArgsConstructor
> public enum SLIExecutionType {
>   @JsonProperty("Window") WINDOW_BASED,
> ```

I think we can drop based from enum as well
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIExecutionType.java` line 19 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPasnhgDk0kDTeVw5OP:-NPasnhgDk0kDTeVw5OQ:bdw86te) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIExecutionType.java#L19)):*
> ```Java
>   @JsonProperty("Request") REQUEST_BASED;
> 
>   private static Map<String, SLIExecutionType> STRING_TO_TYPE_MAP;
> ```

either implement from string or remove the map
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RequestServiceLevelIndicator.java` line 62 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPawZvSBChwk6BilPHe:-NPawZvT9WgTIcKU0R9c:brdzy9i) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RequestServiceLevelIndicator.java#L62)):*
> ```Java
>           this.getMonitoredServiceIdentifier().equals(serviceLevelIndicator.getMonitoredServiceIdentifier()));
>       Preconditions.checkArgument(isCoreUpdatable(serviceLevelIndicator));
>       RequestServiceLevelIndicator ratioServiceLevelIndicator = (RequestServiceLevelIndicator) serviceLevelIndicator;
> ```

requestServiceLevelIndicator
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RequestServiceLevelIndicator.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPaxH2X5ueo3megDb9L:-NPaxH2X5ueo3megDb9M:bgua8qd) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/RequestServiceLevelIndicator.java#L73)):*
> ```Java
>   @Override
>   public boolean shouldReAnalysis(ServiceLevelIndicator serviceLevelIndicator) {
>     return false;
> ```

should get recalculated in case of event type change.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelIndicator.java` line 77 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPaxeyj0OK116a6xc-j:-NPaxeyj0OK116a6xc-k:b-6757g5) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelIndicator.java#L77)):*
> ```Java
>   private String monitoredServiceIdentifier;
>   private boolean enabled;
>   private SLIExecutionType sliExecutionType;
> ```

can be changed to type
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 127 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPaxvtp3xGhUKLzegQA:-NPaxvtp3xGhUKLzegQB:bru8p8g) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L127)):*
> ```Java
>         monitoredServiceIdentifier, serviceLevelIndicatorDTO.getHealthSourceRef(), monitoredService.isEnabled());
> 
>     /*ServiceLevelIndicator serviceLevelIndicator =
> ```

remove the comments from here

**Comment by arpit-harness** [comment]
trigger utAll

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44351)* status: 24 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java` line 870 at r6](https://reviewable.io/reviews/harness/harness-core/44351#-NPaqJmT6mJeiSSC0CP-:-NPp9fSg2oOEmHtv1WD7:b1qxp6r) ([raw file](https://github.com/harness/harness-core/blob/3a200c6e913078d1c58bd7826392f4f8efdc3b18/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java#L870)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

You can have an abstract method getSLIMetricAndEvaluationType()
and these getEvaluationType() + "_" + getMetricType() can go there
RatioServiceLevelIndicator.getSLIMetricAndEvaluationType();
</blockquote></details>

initialising the class here is anti-pattern. Lets move it to a map.

**Pull request merged**
