### PR TITLE
fix: [DEL-4597]: Fix watcher stack driver issue

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
We have missing log4j and janino dependency in watcher, because of which watcher logs were not getting appended to stack driver.
Added respective dependencies.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36033)

### CODE REVIEW

**Comment by gaurav-jain1** [comment]
trigger messagecheck

**Comment by gaurav-jain1** [comment]
trigger ti4

**Comment by gaurav-jain1** [comment]
trigger ti4

**Comment by xingchi-jin** [comment]
I may miss some context. quick question: why missing some dependency would cause logs not appended at runtime ?

**Comment by gaurav-jain1** [comment]
@xingchi-jin we have condition in logback.xml to disable logging as per env variable. And if these libraries are missing, than that condition essentially doesn't gets executed. Hence we end up never enabling logging.

**Review by xingchi-jin — APPROVED** [review]

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36033)* status: :shipit: complete! ✓

**Pull request merged**
