### PR TITLE
feat: [CDS-46287]: configure rollback node for v2 env provisioning

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
...continued from https://github.com/harness/harness-core/pull/41530

v1 provisioner node hierarchy: 
infrastructure -> infrastructure_def -> provisioner (steps/rollbackSteps)

v2 provisioner node hierarchy
environment(v2) -> provisioner (steps/rollbackSteps)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41650)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/41650#-NJQRY6D4dHw0yX5S8s3:-NJQRY6D4dHw0yX5S8s4:bv41v3e) ([raw file](https://github.com/harness/harness-core/blob/a653ed1268aa4da22e02a20871c9c366cffaa8b3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java#L39)):*
> ```Java
> 
>   public static PlanCreationResponse createInfraRollbackPlan(
>       YamlField infraField, boolean isProvisionerPresentInEnvV2) {
> ```

can we have 2 different methods for "infrastructure" ( i.e v1 ) and "environment" ( i.e v2 ) and extract out common code
Reason
- we are calling the 1st argument as infraField but we are also passing environment into this ```InfraRollbackPMSPlanCreator.createInfraRollbackPlan(environmentField, true);```
- it will get us rid of the boolean argument probably

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/rollback/RollbackPlanCreator.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/41650#-NJQRLAy03-BPmngHGAO:-NJQRLAy03-BPmngHGAP:b-t6pj8e) ([raw file](https://github.com/harness/harness-core/blob/a653ed1268aa4da22e02a20871c9c366cffaa8b3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/rollback/RollbackPlanCreator.java#L61)):*
> ```Java
>               .dependentNodeIdentifier(infraNodeFullIdentifier)
>               .build());
>     } else {
> ```

just to note: else condition might include "environments" and "environmentGroup" also but we do not want to support provisioner for them yet
so the environmentField variable below might be null in those cases

**Comment by abhinavsingh1196** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/rollback/RollbackPlanCreator.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/41650#-NJQRLAy03-BPmngHGAO:-NJQePfH2YoxFkgGzgay:b-huohhw) ([raw file](https://github.com/harness/harness-core/blob/a653ed1268aa4da22e02a20871c9c366cffaa8b3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/rollback/RollbackPlanCreator.java#L61)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

just to note: else condition might include "environments" and "environmentGroup" also but we do not want to support provisioner for them yet
so the environmentField variable below might be null in those cases
</blockquote></details>

yes, for now that case is handled since it returns empty Plan from the static helper method.

**Comment by abhinavsingh1196** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/41650#-NJQRY6D4dHw0yX5S8s3:-NJQgbOk5qdJTsBvKLvv:b-s3lyoe) ([raw file](https://github.com/harness/harness-core/blob/a653ed1268aa4da22e02a20871c9c366cffaa8b3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we have 2 different methods for "infrastructure" ( i.e v1 ) and "environment" ( i.e v2 ) and extract out common code
Reason
- we are calling the 1st argument as infraField but we are also passing environment into this ```InfraRollbackPMSPlanCreator.createInfraRollbackPlan(environmentField, true);```
- it will get us rid of the boolean argument probably
</blockquote></details>

Done, removed the dependency on boolean

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/41650#-NJVTuNW9KvPBTkk3WFK:-NJVTuNW9KvPBTkk3WFL:b2qfjkn) ([raw file](https://github.com/harness/harness-core/blob/68a99c33c541c26068950340a04207973db2cdc0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraRollbackPMSPlanCreator.java#L105)):*
> ```Java
>   }
> 
>   private static boolean provisionerExistsInInfraDef(YamlField infraField) {
> ```

is infraField the correct name for this ? Since we are also passing environmentField here ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41650)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41650)* status: Some of the checks are too old.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41650)* status: 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41650)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41650)* status: :shipit: complete! ✓

**Pull request merged**
