### PR TITLE
fix: [PIE-7663]: reset offset only when type of error is KafkaConnectException

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43749)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43749)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/43749#-NNps0l2CWzBmeNmGr_K:-NNps0l2CWzBmeNmGr_L:b-l7yr53) ([raw file](https://github.com/harness/harness-core/blob/96134c403ce365c85580ae96c2a719e86168b29a/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java#L45)):*
> ```Java
>       } else if (!success && error.getCause() != null && error.getCause().getCause() != null
>           && error.getCause().getCause() instanceof MongoCommandException
>           && ((MongoCommandException) error.getCause().getCause()).getCode() == 286) {
> ```

can we create utils and add comments what this mean



_Code quote:_
```Java
      } else if (!success && error.getCause() != null && error.getCause().getCause() != null
          && error.getCause().getCause() instanceof MongoCommandException
          && ((MongoCommandException) error.getCause().getCause()).getCode() == 286) {
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43749)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/43749#-NNps0l2CWzBmeNmGr_K:-NNpwpzF3t2TMgHb0p48:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96134c403ce365c85580ae96c2a719e86168b29a/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create utils and add comments what this mean
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43749)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by shalini-agr** [comment]
trigger ti1

**Review by archit-harness — APPROVED** [review]
> Reviewed 8 of 13 files at r3, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43749)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 8 of 13 files at r3, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43749)* status: :shipit: complete! ✓

**Pull request merged**
