### PR TITLE
[feat]: [CDS-38553]: Infrastructure details addition to Infrastructur…

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
…e Outcome Interface

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34770)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34770)* status: 20 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorV2.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/34770#-N5e0Jsz4i8dLvA_0d69:-N5e0Jsz4i8dLvA_0d6A:bs95zv1) ([raw file](https://github.com/harness/harness-core/blob/dbbc0ec8f22b38f1df3c0071970f42e861575605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorV2.java#L159)):*
> ```Java
>   }
> 
>   private Infrastructure setInfraIdentifierAndName(
> ```

pls add unit test for this method

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorV2.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/34770#-N5e0Jsz4i8dLvA_0d69:-N5heZb6CYhihl59X09Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbbc0ec8f22b38f1df3c0071970f42e861575605/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorV2.java#L159)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

pls add unit test for this method
</blockquote></details>

Done.

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/34770#-N5ikf2FBjv4SMAzkP-V:-N5mZb3Y1Qf1htXlZGlS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/996a8e99e8dc4d8f3db4023bcda6a649fc80a0fe/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L66)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

create a separate function and set identifier and name instead of setting identifier for each type again and again.
You can call that function for each type and set name and identifier
</blockquote></details>

Done

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 219 at r3](https://reviewable.io/reviews/harness/harness-core/34770#-N5il56Q5MehO7IZtnHr:-N5mZg-x3VHfzHvyUyR_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/996a8e99e8dc4d8f3db4023bcda6a649fc80a0fe/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L219)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 9 of 20 files at r1, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34770)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34770)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/34770#-N5mx6dz5PyUiM6goBPW:-N5mx6e0DbulFzDMLvMi:b-1t5nnu) ([raw file](https://github.com/harness/harness-core/blob/f62e5d48b49d31da47dc9dfb8bfc7d17cacda5c4/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L66)):*
> ```Java
>                     service, environmentOutcome, k8SDirectInfrastructure.getInfrastructureKeyValues()))
>                 .build();
>         InfrastructurePlanCreatorHelper.setInfraIdentifierAndName(k8SDirectInfrastructureOutcome,
> ```

This looks odd that Infrastructure mapper needs to call InfraPlanCreatorHelper

setInfraIdentifierAndName() can be created in this same class ( InfraMapper ) or a new class ( InfraMapperHelper )

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/34770#-N5mx6dz5PyUiM6goBPW:-N5n8qAf565oX8_6ZfAt:b-30p7b0) ([raw file](https://github.com/harness/harness-core/blob/f62e5d48b49d31da47dc9dfb8bfc7d17cacda5c4/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L66)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This looks odd that Infrastructure mapper needs to call InfraPlanCreatorHelper

setInfraIdentifierAndName() can be created in this same class ( InfraMapper ) or a new class ( InfraMapperHelper )
</blockquote></details>

Have moved this method to Infrastructuremapper Class

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 9 of 20 files at r1, 10 of 14 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34770)* status: :shipit: complete! ✓

**Pull request merged**
