### PR TITLE
[fix]: [CDS-80109] Add validation for resolved tags value to be string - QA Hotfix

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Added the condition to use expression evaluator method if the expression resolution FF is not enabled.  

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53368)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger gitleaks

**Comment by lovish1999** [comment]
trigger commonchecks

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53368)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Comment by lovish1999** [comment]
trigger ut8

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53368)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/53368#-NfHdnxQDQoZtyxymFEo:-NfHdnxQDQoZtyxymFEp:b-dddljl) ([raw file](https://github.com/harness/harness-core/blob/179ab1016b7fa1770cc0b0365d93b53e03e04dc1/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L560)):*
> ```Java
>     // TODO: Remove this If condition when the new expression resolution FF is GAed
>     if (!ngFeatureFlagHelperService.isEnabled(accountIdentifier, CDS_ENABLE_NEW_PARAMETER_FIELD_PROCESSOR)) {
>       return expressionEvaluator.evaluateExpression(tags, ExpressionMode.RETURN_NULL_IF_UNRESOLVED);
> ```

Does expressionEvaluator.evaluateExpression return null if tags are null or throw some exception?

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53368#-:-NfHfj972D7YT-o8q7MO:bnfp4nl)* status: Waiting on team(s): del-team. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 560 at r1](https://reviewable.io/reviews/harness/harness-core/53368#-NfHdnxQDQoZtyxymFEo:-NfHff0D2H5BXWqq2rjt:b-1u5x19) ([raw file](https://github.com/harness/harness-core/blob/179ab1016b7fa1770cc0b0365d93b53e03e04dc1/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L560)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

yes, it will return null ```public <T\> T evaluateExpression(ParameterField<T\> parameterField, ExpressionMode expressionMode) {  
if (parameterField == null || parameterField.getValue() == null) {  
return null;  
}  
  
Object finalValue \= parameterField.fetchFinalValue();  
if (finalValue instanceof String) {  
return (T) evaluateExpression((String) finalValue, expressionMode);  
}  
  
return parameterField.getValue();  
}
</blockquote></details>

Nice. Approved.

**Comment by lovish1999** [comment]
trigger review

**Pull request merged**
