### PR TITLE
fix: [PL-31229]: Making sort case insensitive. Revert 

### PR DESCRIPTION
**Pull request by boopesh007**
Reverts harness/harness-core#45940

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46117)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger gitleaks

**Comment by boopesh007** [comment]
trigger messagecheck

**Review by Fernando-Dourado — APPROVED** [review]

**Comment by boopesh007** [comment]
trigger gitleaks

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46117)* status: 6 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46117)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46117)* status: :shipit: complete! ✓

**Pull request merged**
