### PR TITLE
[fix]:[PL-29719]: Replacing kryo FieldSerailizer with CompatibleFieldSerializer in cache module

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes

There are some compatibility issues with FieldSerializer currently being used. It does not support adding, removing, or changing the type of fields without invalidating previously serialized bytes. Renaming fields is allowed only if it doesn't change the alphabetical order of the fields. https://github.com/EsotericSoftware/kryo#fieldserializer

As part of this PR we will replace FieldSerializer with CompatibleFieldSerializer 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40037)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40037)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOENsD8Sf2I5J9JE_:-NGqOENsD8Sf2I5J9JEa:bsrch08) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java#L36)):*
> ```Java
>   }
> 
>   private synchronized Kryo kryo() {
> ```

why we are writing new method, if parent method already has same code?
___
*[`960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOB4d9EftKaAtGzpv:-NGqOB4d9EftKaAtGzpw:bdacs86) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java#L39)):*
> ```Java
>     final ClassResolver classResolver = new ClassResolver();
>     HKryo kryo = new HKryo(classResolver, false, false);
> ```

kryo.setDefaultSerializer(getDefaultSerializer()); this is not done.
___
*[`pipeline-service/service/src/main/resources/enterprise-redisson-jcache.yaml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOIGBEu9BrJerWj8F:-NGqOIGBEu9BrJerWj8G:bn8luaj) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/pipeline-service/service/src/main/resources/enterprise-redisson-jcache.yaml#L3)):*
> ```YAML
> singleServerConfig:
>   address: "redis://127.0.0.1:6379"
> codec: !<io.harness.redis.CompatibleFieldSerializerWithoutReferenceCodec> {}
> ```

will existing entries in redis cache work? i don't think so as serialiser is different now

**Comment by ashishsanodia-harness** [comment]
*[`960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOENsD8Sf2I5J9JE_:-NGtDV55-Uc8vnk1qPng:b-hdu6kx) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are writing new method, if parent method already has same code?
</blockquote></details>

Parent is having HKryo initialized with shouldSetReferences as true. For this we are using shouldSetReferences as false. This is needed along with CompatibleFieldSerializer

**Comment by ashishsanodia-harness** [comment]
*[`960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOB4d9EftKaAtGzpv:-NGtE06_9uHVq9Ge5deO:b-zbkrdc) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

kryo.setDefaultSerializer(getDefaultSerializer()); this is not done.
</blockquote></details>

This is not required because HKryo is setting CompatibleFieldSerializer as default serializer in constructor.

**Comment by ashishsanodia-harness** [comment]
*[`pipeline-service/service/src/main/resources/enterprise-redisson-jcache.yaml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOIGBEu9BrJerWj8F:-NGtETocBXmc56KtD996:bk4nkx4) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/pipeline-service/service/src/main/resources/enterprise-redisson-jcache.yaml#L3)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

will existing entries in redis cache work? i don't think so as serialiser is different now
</blockquote></details>

No it will return as null and end up doing db call

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40037)* status: 15 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/service/src/main/resources/enterprise-redisson-jcache.yaml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGqOIGBEu9BrJerWj8F:-NGuzCDrCCuEckj29G6k:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/pipeline-service/service/src/main/resources/enterprise-redisson-jcache.yaml#L3)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

No it will return as null and end up doing db call
</blockquote></details>

Discussed offline

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40037)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGvCZBj4-ZhmYJQ_Oy5:-NGvCZBk3QzxkPHV2T0R:b-emszrf) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java#L40)):*
> ```Java
>     HKryo kryo = new HKryo(classResolver, false, false);
> 
>     try {
> ```

Can we avoid duplicating this code. Maybe by having AbstractRedissonKryoCodec

**Comment by ashishsanodia-harness** [comment]
*[`960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/40037#-NGvCZBj4-ZhmYJQ_Oy5:-NGzBAAeDrqxGTm0_nIO:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/66c7aa6d28b403e083fd8e091cb26cef126756b3/960-persistence/src/main/java/io/harness/redis/CompatibleFieldSerializerWithoutReferenceCodec.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we avoid duplicating this code. Maybe by having AbstractRedissonKryoCodec
</blockquote></details>

Done

**Review by ankit-harness — APPROVED** [review]
> Reviewed 14 of 15 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40037)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40037#-:-NGzMX1SBOpz-OAKx-Yv:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40037)* status: Waiting on team(s): sto.

**Pull request merged**
