### PR TITLE
fix: [CDS-38368]: adding support for RANCHER Cloud Provider for GraphQL Support

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)

### CODE REVIEW

**Comment by shubham-in10se** [comment]
trigger messagecheck

**Comment by shubham-in10se** [comment]
trigger ti0

**Comment by tchaurasiya** [comment]
*[`400-rest/src/main/resources/graphql/public/cloudProviderMutation.graphql` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/34154#-N4B8Qwd72P9898iQ2AC:-N4B0__66aEtA6YulK-I:bu6p64y) ([raw file](https://github.com/harness/harness-core/blob/601c3877db874ae94973f34c85c5d7e8108dcb7d/400-rest/src/main/resources/graphql/public/cloudProviderMutation.graphql#L111)):*
> ```GraphQL
> 
>   rancherUrl: String!
>   bearerTokenSecretId: String
> ```

shouldn't this be mondatory field?

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)* status: 0 of 1 approvals obtained.

**Review by shubham-in10se — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/resources/graphql/public/cloudProviderMutation.graphql` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/34154#-N4B8Qwd72P9898iQ2AC:-N4BV66LA5ojpIMVC4Dg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/601c3877db874ae94973f34c85c5d7e8108dcb7d/400-rest/src/main/resources/graphql/public/cloudProviderMutation.graphql#L111)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

shouldn't this be mondatory field?
</blockquote></details>

Done.

**Comment by shubham-in10se** [comment]
trigger ti0

**Comment by shubham-in10se** [comment]
trigger ti1

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)* status: :shipit: complete! ✓

**Comment by shubham-in10se** [comment]
trigger ti0

**Review by kapil-harness — COMMENTED** [review]
> Reviewed 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)* status: 9 file(s) to review. 0 of 1 approvals obtained.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 7 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34154)* status: :shipit: complete! ✓

**Pull request closed without merging**
