### PR TITLE
feat: [CDS-3001]: Show CF provisioner connectorName instead of conne…

### PR DESCRIPTION
**Pull request by ivan-83**
…ctorId in Yaml on UI

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30454#-Mur-KD56SacnjwntSyU:-Mur-KD56SacnjwntSyV:bkasi5b) (no related file):*
is this backward compatible ?

---

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30454#-Mur-KD56SacnjwntSyU:-MvZt1xw07CHmUzzNgcM:bj71pea) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this backward compatible ?
</blockquote></details>

Hi, @yogesh-chauhan @anshul-harness pls take a look at tech specs where customer case is described,
https://harness.atlassian.net/wiki/spaces/CDP/pages/21036007463/Use+connectorName+instead+of+connectorId+as+GitConnector+reference+in+generated+YAML+for+CloudFormation+providers

---

**Comment by ivan-83** [comment]
trigger ft2

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30454#-Mur-KD56SacnjwntSyU:-MvaaXb_9UMa_9PSljcL:b-ckz8s2) (no related file):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Hi, @yogesh-chauhan @anshul-harness pls take a look at tech specs where customer case is described,
https://harness.atlassian.net/wiki/spaces/CDP/pages/21036007463/Use+connectorName+instead+of+connectorId+as+GitConnector+reference+in+generated+YAML+for+CloudFormation+providers
</blockquote></details>

@ivan-83 , I went through the spec. The only issue I see with the FF is that, we will not be able to get rid of it 

Since the field names are different connectorId vs connectorName, do we need a FF ?

if connectorName is set, use it, else use connectorId

---

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30454#-Mur-KD56SacnjwntSyU:-MvhZDoI4ceNAp42LIVO:boxyg7c) (no related file):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Thanks, @yogesh-chauhan for your comments and review.  The catch here is we need to make a decision on what to expose in YAML in CloudFormationInfrastructureProvisionerYamlHandler::toYaml method where we don't have info whether connectorName or connectorId is set.  In DB connectorName is always null because @Transient on connectorName in GitFileConfig entity. Making some extra logic in toBean or upsertFromYaml methods to store incoming state and later on reuse it in toYaml method could be complicated. 
</blockquote></details>

@yogesh-chauhan  Also, one more thing, the exiting customer YAMLs are presented with connector ids,  firstly they have to do migration from connectorId to connectorName by using FF. After that, they will export it to Git repo with connectorName. When importing in  SaaS we could think to leverage your logic by adding one more property to GitFileConfig let's say showConnectorName or similar where we are going to store info about what is set, connectorId or connectorName.  Or, add the new property on infra provisioner.

In that case, the purpose of FF will be only for migration from On-Prem to SaaS and it shouldn't be presented on SaaS. 
On SaaS we will have the behavior like what it is set in YAML during editing it will be presented later.  It means if some user is ready to switch to connectorName in YAML just edit YAML and put connectorName instead of connectorId, wdyt? 

---

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)* status: Some of the checks are too old.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30454#-:-Mx18opwCY0b-P7dLCQy:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
