### PR TITLE
techdebt: [DEL-4576]: Extract spring persistence layer in a module

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
Cherry-pick changes from #36182 to saas/762xx branch

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36236)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 7 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36236)

**Comment by xingchi-jin** [comment]
trigger buildnum

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 57 of 58 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36236)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 583 at r3](https://reviewable.io/reviews/harness/harness-core/36236#-N95MwEO0-dRugmjXZ8j:-N95MwEO0-dRugmjXZ8k:b-j0d31j) ([raw file](https://github.com/harness/harness-core/blob/07101ac3f4fdfc4c884e7fde77c49a66c051334a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L583)):*
> ```Java
>     pipelineEventConsumerController.register(injector.getInstance(CreatePartialPlanRedisConsumer.class), 2);
>     pipelineEventConsumerController.register(
>         injector.getInstance(PipelineExecutionSummaryCDRedisEventConsumer.class), 1);
> ```

is this intentional?

**Comment by xingchi-jin** [comment]
> > Reviewed 57 of 58 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/36236)_ status: 1 change requests. 0 of 1 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 583 at r3](https://reviewable.io/reviews/harness/harness-core/36236#-N95MwEO0-dRugmjXZ8j:-N95MwEO0-dRugmjXZ8k:b-j0d31j) ([raw file](https://github.com/harness/harness-core/blob/07101ac3f4fdfc4c884e7fde77c49a66c051334a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L583)):_
> 
> > ```java
> >     pipelineEventConsumerController.register(injector.getInstance(CreatePartialPlanRedisConsumer.class), 2);
> >     pipelineEventConsumerController.register(
> >         injector.getInstance(PipelineExecutionSummaryCDRedisEventConsumer.class), 1);
> > ```
> 
> is this intentional?

I didn't manually change anything, just cherry-picked. 
https://github.com/harness/harness-core/pull/36182/files#diff-6c153c493d1959b4cf0e7d7378b5f779c10dab5668406771da808ecffe62baa5L583

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36236)* status: :shipit: complete! ✓

**Comment by xingchi-jin** [comment]
trigger buildnum

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 57 of 58 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36236)* status: :shipit: complete! ✓

**Comment by xingchi-jin** [comment]
trigger ti0

**Pull request merged**
