### PR TITLE
fix: [DEL-3159]: Collect and publish task metric through stack driver

### PR DESCRIPTION
**Pull request by gaurav-jain1**
…h regular logging

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30479)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 384 at r1](https://reviewable.io/reviews/harness/harness-core/30479#-MuwM8S84NR6TPA2Utp1:-MuwM8S93wEvaW0Ij6eA:b-h3vsmi) ([raw file](https://github.com/harness/harness-core/blob/d8d7d07c78ab6dd8656cbfd7a78fd81536b46703/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L384)):*
> ```Java
>   private final AtomicInteger maxExecutingTasksCount = new AtomicInteger();
>   private final AtomicInteger maxExecutingFuturesCount = new AtomicInteger();
>   private final AtomicInteger taskReceivedCount = new AtomicInteger();
> ```

this doesn't seem very helpful. We should just print the info that @bojanmicovic added for metrics being published.

**Comment by raghuAtWings** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 389 at r1](https://reviewable.io/reviews/harness/harness-core/30479#-MuwMIHN5ZYG6vHTkEnu:-MuwMIHN5ZYG6vHTkEnv:b-k4oz6h) ([raw file](https://github.com/harness/harness-core/blob/d8d7d07c78ab6dd8656cbfd7a78fd81536b46703/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L389)):*
> ```Java
>   private final AtomicInteger validatingTaskCount = new AtomicInteger();
>   private final AtomicInteger executingTaskCount = new AtomicInteger();
>   private final AtomicLong totDispatchTime = new AtomicLong();
> ```

this also makes the code very messy to measure such metrics.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30479)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 384 at r1](https://reviewable.io/reviews/harness/harness-core/30479#-MuwM8S84NR6TPA2Utp1:-MuyY93DCG3mXqLzPIs3:bvlce54) ([raw file](https://github.com/harness/harness-core/blob/d8d7d07c78ab6dd8656cbfd7a78fd81536b46703/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L384)):*
> or metrics bei
I dont think metric collected by Bojan cover any of these. Moreover that code is pretty much attached with immutable delegates. So will into effect only when it's enabled.
Do you have any other way to enable those ?
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 389 at r1](https://reviewable.io/reviews/harness/harness-core/30479#-MuwMIHN5ZYG6vHTkEnu:-MuyYTta6TUnCsCwo2DB:b-krhyfc) ([raw file](https://github.com/harness/harness-core/blob/d8d7d07c78ab6dd8656cbfd7a78fd81536b46703/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L389)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this also makes the code very messy to measure such metrics. 
</blockquote></details>

We should have these, as they will be very helpful in debugging delegate performance. I started with the basic way of collected these. Let me know if you have any other clean approach to implement this.

**Comment by gaurav-jain1** [comment]
This change is not needed now.

**Pull request closed without merging**
