### PR TITLE
feat: [PIE-8422]: Added support for get-only-file-content in get-file API

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Have added support for get-only-file-content in get-file API itself by introducing a boolean variable for the same. This saves us a lot of complexity and development of code and helps in maintenance as well in long run.

Verified with current and previous delegate version, working fine.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44436)

### CODE REVIEW

**Comment by mohitg0795** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 3 of 13 files at r2, 2 of 10 files at r3, 15 of 16 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44436)* status: 22 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r2, 2 of 10 files at r3, 15 of 16 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44436)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1009 at r5](https://reviewable.io/reviews/harness/harness-core/44436#-NPQeXGS-L9jmVtHIqUs:-NPQeXGS-L9jmVtHIqUt:b-odzr4w) ([raw file](https://github.com/harness/harness-core/blob/b8e27fc6e5371b029d471c8b8ad6f73bce03f480/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1009)):*
> ```Java
>   @Override
>   public GitFileResponse getFile(
>       ScmConnector scmConnector, GitFileRequest gitFileRequest, SCMGrpc.SCMBlockingStub scmBlockingStub) {
> ```

can we break internal impl to use smaller methods like getFileIfEmptyBranch etc

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1009 at r5](https://reviewable.io/reviews/harness/harness-core/44436#-NPQeXGS-L9jmVtHIqUs:-NPRf6VEElKts2obLh7d:b-ld06w8) ([raw file](https://github.com/harness/harness-core/blob/b8e27fc6e5371b029d471c8b8ad6f73bce03f480/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1009)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we break internal impl to use smaller methods like getFileIfEmptyBranch etc
</blockquote></details>

We perform majorly 3 operations as part of get-file. I am also of same opinion that if modularized, it could've been better and it was something that I knew at the point when I wrote it. I didn't find any good mechanism to break this method further than what it currently is such that it becomes cleaner than what it currently is. Issue is if we fail to fetch default branch, then we need to return with a proper response right away and we skip all further operations. Thus its difficult to modularize it. Open to suggestions anyways.

Also, I guess this will be an enhancement activity even if we find a good solution for it.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44436)* status: :shipit: complete! ✓

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 1009 at r5](https://reviewable.io/reviews/harness/harness-core/44436#-NPQeXGS-L9jmVtHIqUs:-NPViFcJAqyve4ljscDF:b3y0etw) ([raw file](https://github.com/harness/harness-core/blob/e9107eff6266832edf8cd9f1d94055342100bec6/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L1009)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We perform majorly 3 operations as part of get-file. I am also of same opinion that if modularized, it could've been better and it was something that I knew at the point when I wrote it. I didn't find any good mechanism to break this method further than what it currently is such that it becomes cleaner than what it currently is. Issue is if we fail to fetch default branch, then we need to return with a proper response right away and we skip all further operations. Thus its difficult to modularize it. Open to suggestions anyways.

Also, I guess this will be an enhancement activity even if we find a good solution for it.
</blockquote></details>

done, we can discuss offline, modular methods can be written and caller parent can decide based on result whether it wants to return early or not.

**Pull request merged**
