### PR TITLE
feat: [PIE-2289]: Manifest implementing a partial plan creator

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java, line 97 at r2](https://reviewable.io/reviews/harness/harness-core/29954#-Mu9l7nK-hub0j-clapA:-Mu9l7nK-hub0j-clapB:b-zdzg0k) ([raw file](https://github.com/harness/harness-core/blob/7372ed52a4cde8a15da57e20c22cdf0196d4912d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java#L97)):*
> ```Java
>   }
> 
>   public String addDependenciesForIndividualManifest(YamlField manifestsYamlField, String manifestIdentifier,
> ```

nit: add minor comments for explanation of the logic

**Comment by sahilhindwani-harness** [comment]
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreator.java, line 43 at r2](https://reviewable.io/reviews/harness/harness-core/29954#-Mu9mOPWET0QGhE2EjQW:-Mu9mOPWET0QGhE2EjQX:b-ht5ktj) ([raw file](https://github.com/harness/harness-core/blob/7372ed52a4cde8a15da57e20c22cdf0196d4912d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreator.java#L43)):*
> ```Java
> 
>   @Override
>   public Map<String, Set<String>> getSupportedTypes() {
> ```

Add a list of all values in ManifestType itself and use that over here.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 17 of 18 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger ti0

**Comment by prashantsharma04** [comment]
trigger ti1

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 21 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreator.java, line 43 at r2](https://reviewable.io/reviews/harness/harness-core/29954#-Mu9mOPWET0QGhE2EjQW:-MuBccA53UXAdShtjn3Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7372ed52a4cde8a15da57e20c22cdf0196d4912d/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreator.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a list of all values in ManifestType itself and use that over here.
</blockquote></details>

Done.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 15 of 18 files at r1, 1 of 3 files at r2, 3 of 5 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuEy8m49l6trJEoEnRV:-MuEy8m49l6trJEoEnRW:bmfqrpv) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java#L89)):*
> ```Java
>         Collectors.toMap(e -> e.getField(YamlTypes.MANIFEST_CONFIG).getNode().getIdentifier(), k -> k));
> 
>     for (Map.Entry<String, ManifestInfo> entry : manifestList.getManifests().entrySet()) {
> ```

give the descriptive name here for entry
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java, line 216 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuF-o4TCHqkFKwR_-yT:-MuF-iDj0yXwnKbIWcy6:b-vtmylr) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java#L216)):*
> ```Java
>   }
> 
>   public Map<String, ByteString> prepareMetadataForWithNodeIdAndServiceConfig(
> ```

change name as discussed prepareMetadata
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java, line 247 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuF0Tfj2KrrwSQ29x8R:-MuF0Tfj2KrrwSQ29x8S:b-m8k52g) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java#L247)):*
> ```Java
>   }
> 
>   public boolean validateCreatePlanNodeForManifests(ServiceConfig actualServiceConfig) {
> ```

shouldCreatePlanForManifests

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreator.java, line 47 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuFX_JH6OocsDe_IKwr:-MuFX_JH6OocsDe_IKws:bua2mzc) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreator.java#L47)):*
> ```Java
>   @Override
>   public PlanCreationResponse createPlanForField(PlanCreationContext ctx, ManifestConfig manifestConfig) {
>     String manifestId = (String) kryoSerializer.asInflatedObject(
> ```

add a comment for manifest config
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java, line 69 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuFXwGF1VIvBv-PAJU-:-MuFXwGF1VIvBv-PAJU0:bxwszto) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java#L69)):*
> ```Java
>       PlanCreationContext ctx, ManifestsListConfigWrapper config) {
>     LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap = new LinkedHashMap<>();
> ```

this is resolved service config

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuEy8m49l6trJEoEnRV:-MuFhpKzEpu5kIycEkyP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/manifest/ManifestsPlanCreator.java#L89)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

give the descriptive name here for entry
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java, line 216 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuF-o4TCHqkFKwR_-yT:-MuFhqn39NCJcYfEG6bY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java#L216)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

change name as discussed prepareMetadata
</blockquote></details>

Done.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java, line 247 at r5](https://reviewable.io/reviews/harness/harness-core/29954#-MuF0Tfj2KrrwSQ29x8R:-MuFo6P023ufZTQfEZZJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c040857c8c84b641a44eb49b6bb1e44944c0329/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServicePlanCreator.java#L247)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

shouldCreatePlanForManifests
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 7 file(s) to review. 1. unresolved discussions.

**Comment by prashantsharma04** [comment]
No new task is added on this PR for delegate. cc @abhinav-harness

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 13 of 18 files at r1, 1 of 3 files at r2, 1 of 5 files at r3, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29954)* status: :shipit: complete! ✓

**Pull request merged**
