### PR TITLE
fix: [PL-27621]: added token lookup handler

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
HashiCorp vaults undergo a token renewal iterator job. The existing vaults with token auth that have a non-renewable token are causing a lot of unnecessary error logging in this process. To avoid this, we will run a iterator which will set the renewable interval to 0 for all the non-renewable vaults. 
For creation of new vaults, this check is already in place, hence the new vaults which have a non-renewable token cannot have a renewalInterval of greater than 0.
We plan to keep this iterator in prod for one release so that all existing vaults are updated.

Testing:-
The iterator has been tested locally, and the renewal interval of non-eligible vaults gets set to 0, and hence not picked up for renewal after that.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/42751#-NMDTEh-EtIB6VJ5dLxR:-NMDTEh-EtIB6VJ5dLxS:bjvqw6k) ([raw file](https://github.com/harness/harness-core/blob/b4fd089f96f73aa525ef0ea206aefaa8d29c7026/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java#L117)):*
> ```Java
>   }
> 
>   private boolean checkIfEligibleForRenewal(long renewedAt, long renewalInterval) {
> ```

where is this method being used?

**Comment by shashank-harness** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/42751#-NMDUGoz3QyI15B1YNhQ:-NMDUGoz3QyI15B1YNhR:b-hd1fkp) ([raw file](https://github.com/harness/harness-core/blob/b4fd089f96f73aa525ef0ea206aefaa8d29c7026/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L87)):*
> ```Java
>   }
> 
>   public long getLastTokenLookupAt() {
> ```

where is this method called from?

**Comment by shashank-harness** [comment]
> Testing:-
> The iterator has been tested locally, and the renewal interval of non-eligible vaults gets set to 0, and hence not picked up for renewal after that.
Have you tested for regression?
cc: @nishantsaini20

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/42751#-NMDTEh-EtIB6VJ5dLxR:-NMDZMR-24wQqoX-lCFA:b-14jnqg) ([raw file](https://github.com/harness/harness-core/blob/b4fd089f96f73aa525ef0ea206aefaa8d29c7026/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java#L117)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

where is this method being used?
</blockquote></details>

Not needed anymore, since this check is not required here. Removed this.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/42751#-NMDUGoz3QyI15B1YNhQ:-NMDZTnU2P6MTuUmUdO3:b6i0o0g) ([raw file](https://github.com/harness/harness-core/blob/b4fd089f96f73aa525ef0ea206aefaa8d29c7026/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L87)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

where is this method called from?
</blockquote></details>

Not needed anymore, since the check for token lookup interval is not required in this context. Removed this.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: Some of the checks are too old. 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMahbjcAMq03_b6oBJZ:-NMahbjcAMq03_b6oBJ_:b-23wpin) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L119)):*
> ```Java
> import io.harness.ng.core.filter.ApiResponseFilter;
> import io.harness.ng.core.handler.NGVaultSecretManagerRenewalHandler;
> import io.harness.ng.core.handler.NGVaultUnsetRenewalHandler;
> ```

There is VaultRenewal Iterator in CG Manager too, that is not facing a similar issue ? 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMahoPY5uv9wKjIcGOw:-NMahoPY5uv9wKjIcGOx:b-thst77) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java#L67)):*
> ```Java
>             .name(this.getClass().getName())
>             .poolSize(threadPoolSize)
>             .interval(ofMinutes(1))
> ```

This will make the thread pool to wake up every minute and make Mongo queries. Do we need a granularity as low as this ? If this is going to run for just one release in the Prod then we can have interval of 30 minutes too ? As the goal here is to just update the old entries in the Mongo Collection. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java` line 73 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMaiEuLDj6H9xNEMtKl:-NMaiEuLDj6H9xNEMtKm:b-ijzq1c) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java#L73)):*
> ```Java
>             .clazz(VaultConnector.class)
>             .fieldName(VaultConnectorKeys.nextTokenLookupIteration)
>             .targetInterval(ofMinutes(30))
> ```

After this iterator pick the document and updates it this same doc won't be picked up this new iterator right ? In that case this value won't matter and thus we can have a large value of 5 to 6 hours as well. Also, the `nextTokenLookupIteration` field will be removed after all the Prod documents are updated right ?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: 10 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMahbjcAMq03_b6oBJZ:-NMb1x3f8et_ampgcliR:b-9pvqmz) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L119)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

There is VaultRenewal Iterator in CG Manager too, that is not facing a similar issue ? 
</blockquote></details>

Yes, for that I will add iterator separately after checking if there is excessive logging for those CG vaults as well. Currently, the concern was raised for NG vaults by the delegate team.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMahoPY5uv9wKjIcGOw:-NMb2Nbg70x8MuEp-kts:bknlwy3) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java#L67)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

This will make the thread pool to wake up every minute and make Mongo queries. Do we need a granularity as low as this ? If this is going to run for just one release in the Prod then we can have interval of 30 minutes too ? As the goal here is to just update the old entries in the Mongo Collection. 
</blockquote></details>

Sure, I could not find the exact number of hashicorp connectors in the 3 clusters as db access has been revoked. But yes, 30 mins should also suffice. Else, we can have this running for one more release.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java` line 73 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMaiEuLDj6H9xNEMtKl:-NMb48O88jZcgvhdhDcx:b-5gu3rw) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultUnsetRenewalHandler.java#L73)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

After this iterator pick the document and updates it this same doc won't be picked up this new iterator right ? In that case this value won't matter and thus we can have a large value of 5 to 6 hours as well. Also, the `nextTokenLookupIteration` field will be removed after all the Prod documents are updated right ?
</blockquote></details>

Yes, the field will be removed after all documents are updated.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/42751#-NMahbjcAMq03_b6oBJZ:-NMeHjhu7gpN-7tdUpQL:b-4hvi0m) ([raw file](https://github.com/harness/harness-core/blob/6ce89f67190cb1e8f0aa2d521ae0c287d847a17a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L119)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Yes, for that I will add iterator separately after checking if there is excessive logging for those CG vaults as well. Currently, the concern was raised for NG vaults by the delegate team.
</blockquote></details>

Got it.

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: 9 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 3 of 5 files at r2, 1 of 2 files at r4, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: 8 file(s) to review. 2. unresolved discussions.

**Review by shashank-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: 8 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 2 of 5 files at r2, 1 of 2 files at r4, 1 of 2 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42751)* status: :shipit: complete! ✓

**Pull request merged**
