### PR TITLE
fix: [DEL-4167]: Add warning for heartbeat more than 3 mins

### PR DESCRIPTION
**Pull request by jennyjames21**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 890 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yiTP0GhQnN7XHANf:-N55yiTP0GhQnN7XHANg:b806nuo) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L890)):*
> ```Java
>     // Handle Heartbeat message in Health-monitor thread-pool.
>     if (StringUtils.startsWith(message, HEARTBEAT_RESPONSE)) {
>       DelegateHeartbeatResponse delegateHeartbeatResponse =
> ```

Have we changed the semantics of heartbeat response ?



_Code quote:_
```Java
      DelegateHeartbeatResponse delegateHeartbeatResponse =
          JsonUtils.asObject(message, DelegateHeartbeatResponse.class);
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1657 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yA0ZA-iMcVDrvNpP:-N55yA0ZA-iMcVDrvNpQ:bfqf5wr) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1657)):*
> ```Java
>     String receivedId = delegateHeartbeatResponse.getDelegateId();
>     if (delegateId.equals(receivedId)) {
>       long now = clock.millis();
> ```

final long
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1665 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yGWN69XFVl8a28vg:-N55yGWN69XFVl8a28vh:b-mtu3m7) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1665)):*
> ```Java
>             getDurationString(delegateHeartbeatResponse.getResponseSentAt(), now));
>       } else {
>         log.info("Delegate {} received heartbeat response {} after sending. {} since last response.", receivedId,
> ```

we can avoid this log at every response.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 890 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yiTP0GhQnN7XHANf:-N57KHlX18xY2Cfsqgjc:b-4b65su) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L890)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Have we changed the semantics of heartbeat response ?
</blockquote></details>

yes, with new change we sending heartbeat as object versus string as more fields got added

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1665 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yGWN69XFVl8a28vg:-N57KYCF-YsKJOVMgsUr:b-1bl7dy) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1665)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we can avoid this log at every response.
</blockquote></details>

IMO lets keep that for a while since we are making change to heartbeat. After it's stabled we can remove info part

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1657 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yA0ZA-iMcVDrvNpP:-N57LZpZ76rKJId_3QzF:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1657)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

final long
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
Different version of delegate - Polling mode enabled 
image

image

Different version of delegate - Streaming mode
image
image

**Comment by jennyjames21** [comment]
Same version - streaming 
image
image

Same version- polling mode
image
image

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1665 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yGWN69XFVl8a28vg:-N58e0dV8fHP8WTtwYDw:b-7zl2o0) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1665)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

IMO lets keep that for a while since we are making change to heartbeat. After it's stabled we can remove info part
</blockquote></details>

If that's the case, you can reduce the frequency though, may be log once every 10 responses
___
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 708 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fu0DEb2g4lvFM_wi:-N58fu0DEb2g4lvFM_wj:bv3ebnu) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/260-delegate/src/test/resources/kryo-registrations.txt#L708)):*
> ```help
> 6505:io.harness.delegate.beans.DelegateTaskEvent
> 6506:io.harness.delegate.beans.DelegateTaskAbortEvent
> 6507:io.harness.beans.DelegateHeartbeatResponseStreaming
> ```

Just curious what the use of this file ? Isn't the addition in kryoRegister.java should be good enough ?



_Code quote:_
```help
6507:io.harness.beans.DelegateHeartbeatResponseStreaming
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2630 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fJiN2ZOn_qTHz4Zg:-N58fJiN2ZOn_qTHz4Zh:b-kz7ouo) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2630)):*
> ```Java
>         StringBuilder message = new StringBuilder(128).append("[X]").append(delegate.getUuid());
>         updateBroadcastMessageIfEcsDelegate(message, delegate, registeredDelegate);
>         broadcasterFactory.lookup(STREAM_DELEGATE + delegate.getAccountId(), true).broadcast(message.toString());
> ```

May be can add a log.warn saying "delegate using older heartbeat mechanism", which can be used to get rid of this else part.
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fd10DDBX0vJRUOY6:-N58fd10DDBX0vJRUOY7:bzct7wh) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L15)):*
> ```Java
>   String delegateId;
>   String status;
>   boolean useCdn;
> ```

aren't we planning to get rid of this field completely ?



_Code quote:_
```Java
boolean useCdn;
```

**Comment by jennyjames21** [comment]
*[`260-delegate/src/test/resources/kryo-registrations.txt` line 708 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fu0DEb2g4lvFM_wi:-N58hCF7E91SCHxH25uO:bw2db98) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/260-delegate/src/test/resources/kryo-registrations.txt#L708)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Just curious what the use of this file ? Isn't the addition in kryoRegister.java should be good enough ?
</blockquote></details>

we added UT to compare all registered classes found during runtime with the expected, to be sure we dont miss any kry register.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1665 at r1](https://reviewable.io/reviews/harness/harness-core/34485#-N55yGWN69XFVl8a28vg:-N58hccd7s42LbQ-bpO6:b-byhm62) ([raw file](https://github.com/harness/harness-core/blob/b127f67d8519647217ae8d9a9a7edd202012b49b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1665)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

If that's the case, you can reduce the frequency though, may be log once every 10 responses
</blockquote></details>

i thought anupam already working on that.

**Comment by jennyjames21** [comment]
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fd10DDBX0vJRUOY6:-N58i5YA154SPwmdmlpc:b-7wjrrg) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L15)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

aren't we planning to get rid of this field completely ?
</blockquote></details>

not sure about that, last time we made some change on use_cdn, we got delegate outage :)

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2630 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fJiN2ZOn_qTHz4Zg:-N58ij_-9cp7xabxY7uy:b-98eq0w) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2630)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

May be can add a log.warn saying "delegate using older heartbeat mechanism", which can be used to get rid of this else part.
</blockquote></details>

Note we are not releasing delegate with this change, as i dont clearly know when is the next delegate release. Till then else part is for all so may not make sense to add warning.

**Review by gaurav-jain1 — DISMISSED** [review]
> Reviewed 3 of 9 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2630 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fJiN2ZOn_qTHz4Zg:-N5B5VAf1X-a7TYRsItG:befl1lp) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2630)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Note we are not releasing delegate with this change, as i dont clearly know when is the next delegate release. Till then else part is for all so may not make sense to add warning. 
</blockquote></details>

Ohk, make sense
___
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/34485#-N58fd10DDBX0vJRUOY6:-N5B5bCbAKOQTvYfu_po:b-17b4rj) ([raw file](https://github.com/harness/harness-core/blob/24d20730736dcbbc88b82d6833ecd3dbbc258674/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponseStreaming.java#L15)):*
> hat, last time we made some chan
I don't think we use this in delegate agent anywhere, see if we can avoid this

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)* status: 1. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)* status: 1. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34485)* status: :shipit: complete! ✓

**Pull request merged**
