### PR TITLE
[fix]: [CDS-51722]: Added fail safe retries for Spot api calls

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes
We have added FailSafe retries over our Retrofit client in SpotInst Client. This covers both CG and NG.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43274)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger ft1,ft2

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/spotinst/SpotInstHelperServiceDelegateImpl.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/43274#-NN7_ep9-Ghq5iLNf4nR:-NN7aqKj-X1Em9AfP69k:b-ypvkp5) ([raw file](https://github.com/harness/harness-core/blob/9b1e5c672348d93a9d99336b92552fa4c550ce48/960-api-services/src/main/java/io/harness/spotinst/SpotInstHelperServiceDelegateImpl.java#L87)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Is expected to have null as an exception message if the error body doesn't have content?
</blockquote></details>

This part we are not planning to change this from the previous implementation.

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43274)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43274)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43274)* status: :shipit: complete! ✓

**Pull request merged**
