### PR TITLE
fix: [SRM-11609]: keeping the MS enabled flag as it is after updating its value

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37198)

### CODE REVIEW

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37198)

**Review by arpit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37198)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 1162 at r2](https://reviewable.io/reviews/harness/harness-core/37198#-NBLMzxO1WU_BuGg6PAm:-NBLMzxP0wyRIq_uG3Gb:b-usogbl) ([raw file](https://github.com/harness/harness-core/blob/599d60377f31955a72bd6a75e6dbe4f57a310d0f/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L1162)):*
> ```Java
>     MonitoredServiceDTO monitoredServiceDTO = createMonitoredServiceDTO();
>     monitoredServiceService.create(builderFactory.getContext().getAccountId(), monitoredServiceDTO);
>     HealthMonitoringFlagResponse healthMonitoringFlagResponse = monitoredServiceService.setHealthMonitoringFlag(
> ```

this test name is for update while you are not using testing update function inside it. Can you change the name to something more suitable.
Also is this test really needed now?

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37198)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 1162 at r2](https://reviewable.io/reviews/harness/harness-core/37198#-NBLMzxO1WU_BuGg6PAm:-NBLcR7v9yZd7bnjRn93:b-t8hj66) ([raw file](https://github.com/harness/harness-core/blob/599d60377f31955a72bd6a75e6dbe4f57a310d0f/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L1162)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

this test name is for update while you are not using testing update function inside it. Can you change the name to something more suitable.
Also is this test really needed now?
</blockquote></details>

As I couldn't find any test for toggle button of MS, I thought this could be it.

**Pull request closed without merging**
