### PR TITLE
[techdebt]: [PL-28401]: Reuse Redisson client instances in Redis event producers and consumers

### PR DESCRIPTION
**Pull request by ankit-harness**
## Describe your changes

**Background:** 

Currently, Redis producers and Redis consumers create their own Redisson client instance to connect to Redis. This is unnecessary as each Redisson client instance connects to same Redis. Multiple Redisson client instances also has performance implications. Each Redisson client has its own set of netty threads, connection pool etc. which leads to increase in resource requirements, increase in startup time of the service and underutilization of resources. Due to this, Pipeline service for instance has about 600 redisson netty threads per pod.

Solution is that there should be a single Redisson client instance which should be shared among all Redis producers and consumers. This will allow sharing of netty threads, redis connections. Redisson Team also recommends that there should only be 1 Redisson client instance per JVM per Redis server.

**Change:** 

1. Created a new class `RedissonClientFactory` which caches `RedissonClient` instances per Redis config. Since Redis config is same for all Redis producers and consumers, same `RedissonClient` instance will be handed to them to connect to Redis.

2. Redirected all calls to create `RedissonClient` in the codebase to `RedissonClientFactory`. This will be the single place to create Redisson clients. So, `RedissonClient` needed for Redis Persistent Lock, Delegate Task Broadcasting are also created from `RedissonClientFactory` now.

3. Setting pingConnectionInterval to 30 seconds in RedissonClient. This is done as an attempt to resolve RedisTimeoutExceptions we see in code. 

**Pending:**

This PR doesn't unify RedissonClients for Cache, Persistent Lock and Delegate Redis Broadcaster. There are risks associated in doing it as codec used for each of them is different. This can be taken up in future after more investigation.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 25 Issues 
* Code issue 21 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37711)

**Review by hextechpal — APPROVED** [review]
> Reviewed 6 of 34 files at r1, 48 of 48 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)* status: 54 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 34 files at r1, 48 of 48 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/37711#-NCVtD0K1NDgFWoBCkM_:-NCVtD0L0IP5U8r-suSo:bho7ut4) ([raw file](https://github.com/harness/harness-core/blob/d6b2a7d40204e9503630088ff54952468a9189eb/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L38)):*
> ```Java
> 
>   public RedissonKryoCodec() {
>     this.useFieldSerializer = false;
> ```

we dont want to serialisae key value anymore? Then if we make it to false, existing key/value will work?

**Review by ankit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/37711#-NCVtD0K1NDgFWoBCkM_:-NCVtnam4H3p396yJ-he:bmct0lw) ([raw file](https://github.com/harness/harness-core/blob/d6b2a7d40204e9503630088ff54952468a9189eb/960-persistence/src/main/java/io/harness/redis/RedissonKryoCodec.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we dont want to serialisae key value anymore? Then if we make it to false, existing key/value will work?
</blockquote></details>

This codec is used at 2 places - Delegate Task Broadcasting, Redis Cache. At other places like Events Framework, we use default Redisson codec which comes out of the box.

Here, I just inverted the default field value and updated code where we create redisson client to pass the inverted value as well. So, no behavioural change 



_Code quote:_
```Java
RedissonKryoCodec
```

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)* status: :shipit: complete! ✓

**Comment by ankit-harness** [comment]
trigger ft1

**Comment by ankit-harness** [comment]
trigger ft2

**Comment by ankit-harness** [comment]
trigger ti1

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 5 of 34 files at r1, 46 of 48 files at r2, 3 of 4 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37711)* status: :shipit: complete! ✓

**Pull request merged**
