### PR TITLE
fix: [CDS-42924]: For Kerberos delegate capability check is not there

### PR DESCRIPTION
**Pull request by bojanmicovic**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37537)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 3 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37537)

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37537)* status: 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/37537#-NBw7OCR372vr0rx677I:-NBw7OCR372vr0rx677J:b32b744) ([raw file](https://github.com/harness/harness-core/blob/7e7e474a022cad2836c9aaa174ec1d2c59c15130/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L58)):*
> ```Java
>     CapabilityResponseBuilder capabilityResponseBuilder = CapabilityResponse.builder().delegateCapability(capability);
> 
>     if (!(capability.getWinRmInfraDelegateConfig() instanceof PdcWinRmInfraDelegateConfig)) {
> ```

we are checking this for all infras, than why are throwing exception is it's not azure or aws? Am i missing something?

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/37537#-NBw7OCR372vr0rx677I:-NBxvp1-2JTTaVfdGP2G:bx52gpz) ([raw file](https://github.com/harness/harness-core/blob/7e7e474a022cad2836c9aaa174ec1d2c59c15130/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L58)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we are checking this for all infras, than why are throwing exception is it's not azure or aws? Am i missing something?
</blockquote></details>

Good catch, I implemented firstly just for PDC and then realised that we need for all the infras.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37537)* status: 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/37537#-NBw7OCR372vr0rx677I:-NCU-SWd73P0eG8PV1pM:b-ez2dhw) ([raw file](https://github.com/harness/harness-core/blob/7e7e474a022cad2836c9aaa174ec1d2c59c15130/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L58)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

Good catch, I implemented firstly just for PDC and then realised that we need for all the infras.
</blockquote></details>

so i can see it still expects only PDC infra, correct?

**Comment by bojanmicovic** [comment]
Is it new task type? (If yes, no need to answer 2 then)
No
Did you add a new class which is added in kryo serialization if yes then do not use that class in any of the delegate task payload till it makes to delegate release
Yes
Did you make changes to the code in a backward-compatible manner?
Yes
will the new version of the delegate receive old version task and process?
Yes
If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes
Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
No
If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes
if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes
Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648](https://harness.atlassian.net/browse/DEL-3648): Move to name based kryo serializer for delegate/manager communication
No
Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
No

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/37537#-NBw7OCR372vr0rx677I:-NCZ6bZo6ua9mv4MBZm5:bo2raay) ([raw file](https://github.com/harness/harness-core/blob/7e7e474a022cad2836c9aaa174ec1d2c59c15130/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L58)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

so i can see it still expects only PDC infra, correct? 
</blockquote></details>

Thanks for pointing to this one.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37537)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger codebasehash

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 1 of 1 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37537)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 74 at r6](https://reviewable.io/reviews/harness/harness-core/37537#-NCdQ1DMEJC2-8oYfYJe:-NCdQ1DMEJC2-8oYfYJf:bqam3b2) ([raw file](https://github.com/harness/harness-core/blob/93f8873988cc0d108b8a64d5df59e360f77b8b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L74)):*
> ```Java
>       capabilityResponseBuilder.validated(true);
>     } catch (Exception e) {
>       log.info("Exception in WinrmSession Connection: ", ExceptionMessageSanitizer.sanitizeException(e));
> ```

Minor - maybe is batter to write in error level
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/37537#-NCdQ_LIBBDyQsuTOGtw:-NCdQ_LIBBDyQsuTOGtx:boikm99) ([raw file](https://github.com/harness/harness-core/blob/93f8873988cc0d108b8a64d5df59e360f77b8b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L105)):*
> ```Java
>             pdcWinrmInfraDelegateConfig.getEncryptionDataDetails(), port, useWinRMKerberosUniqueCacheFile);
>       default:
>         throw new IllegalArgumentException("Invalid authSchema provided:" + winRmAuthDTO.getAuthScheme());
> ```

Minor - more meaningful msg >> Invalid authSchema provided for WinRm authentication or ....
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 115 at r6](https://reviewable.io/reviews/harness/harness-core/37537#-NCdRJ0n-JXwJ_cd897N:-NCdRJ0n-JXwJ_cd897O:b9p1wvr) ([raw file](https://github.com/harness/harness-core/blob/93f8873988cc0d108b8a64d5df59e360f77b8b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L115)):*
> ```Java
> 
>     return WinRmSessionConfig.builder()
>         .workingDirectory(WINDOWS_HOME_DIR)
> ```

Will this work if WINDOWS_HOME_DIR doesn't exist on the machine?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 133 at r6](https://reviewable.io/reviews/harness/harness-core/37537#-NCdRUthCIFnrWKqggds:-NCdRUthCIFnrWKqggdt:b-wr6d0n) ([raw file](https://github.com/harness/harness-core/blob/93f8873988cc0d108b8a64d5df59e360f77b8b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L133)):*
> ```Java
>       boolean useWinRMKerberosUniqueCacheFile) {
>     boolean isUseKeyTab = false;
>     String password = org.jooq.tools.StringUtils.EMPTY;
> ```

Pls use here EMPTY from org.apache.commons.lang3.StringUtils.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java` line 153 at r6](https://reviewable.io/reviews/harness/harness-core/37537#-NCdS6rZDU54SiV5821s:-NCdS6rZDU54SiV5821t:bjkqrtp) ([raw file](https://github.com/harness/harness-core/blob/93f8873988cc0d108b8a64d5df59e360f77b8b28/930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java#L153)):*
> ```Java
>       default:
>         throw new IllegalArgumentException(
>             "Invalid TgtGenerationMethod provided:" + kerberosWinRmConfigDTO.getTgtGenerationMethod());
> ```

Minor - more meaningful error msg.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/pdcconnector/WinrmCapabilityHelper.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/37537#-NCdKbF1CQLUv5AOhESE:-NCdKbF1CQLUv5AOhESF:b-xrgiu8) ([raw file](https://github.com/harness/harness-core/blob/93f8873988cc0d108b8a64d5df59e360f77b8b28/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/pdcconnector/WinrmCapabilityHelper.java#L30)):*
> ```Java
> 
>     WinrmConnectivityExecutionCapability winrmConnectivityExecutionCapability =
>         WinrmConnectivityCapabilityGenerator.buildWinrmConnectivityExecutionCapability(
> ```

Minor - we don't need an additional generator class just build  WinrmConnectivityExecutionCapability here. 



_Code quote (from 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/mixin/WinrmConnectivityCapabilityGenerator.java):_
```Java
    return WinrmConnectivityExecutionCapability.builder()
        .useWinRMKerberosUniqueCacheFile(useWinRMKerberosUniqueCacheFile)
        .winRmInfraDelegateConfig(winRmInfraDelegateConfig)
        .build();
```

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by bojanmicovic** [comment]
trigger codebasehash

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37537)* status: :shipit: complete! ✓

**Pull request merged**
