### PR TITLE
[feat]:[pl-28109]: save commit message as comment

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have tested out save commit message as comment for remote template creation, update and delete with new gitx

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38756)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/38756#-NEFsSscA0e79LJEK7KL:-NEFsSscA0e79LJEK7KM:b43hdl0) ([raw file](https://github.com/harness/harness-core/blob/0f78532ec34b9cef581f74360cb814f708d8f295/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L245)):*
> ```Java
>     log.info(String.format("Creating Template with identifier %s with label %s in project %s, org %s, account %s",
>         templateEntity.getIdentifier(), templateEntity.getVersionLabel(), projectId, orgId, accountId));
>     if (comments.isEmpty() && gitEntityCreateInfo != null && !gitEntityCreateInfo.getCommitMsg().isEmpty()) {
> ```

what if commitMsg is null?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38756)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/38756#-NEFsSscA0e79LJEK7KL:-NEGHeiW2coG_0fM2bnl:b-jv2fqa) ([raw file](https://github.com/harness/harness-core/blob/0f78532ec34b9cef581f74360cb814f708d8f295/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L245)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if commitMsg is null?
</blockquote></details>

Ideally the commitMsg cannot be null or empty when we are creating it from UI, once the apis are exposed, keeping this in mind have added the null check for the commitMsg

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38756)* status: Some of the checks are too old.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38756#-:-NEeXbl36w60aLI7AqMO:bnfp4nl)* status: 1 file(s) to review.

**Pull request merged**
