### PR TITLE
[fix]: [CCM-7250]: Increased name size limit for perspective, budget and report to 80

### PR DESCRIPTION
**Pull request by sdsingh07**
Increased name size limit for perspective, budget and report to 80

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32139)

### CODE REVIEW

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32139#-:-N-2ZJjODTtC7fMVRCUW:bnfp4nl)* status: :shipit: complete! ✓

**Comment by sdsingh07** [comment]
trigger messagecheck

**Review by svmav — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32139)* status: Some of the checks are too old.

**Review by sdsingh07 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32139#-:-N0ExJww3nMl6tUf4IMI:bnfp4nl)* status: Some of the checks are too old.

**Pull request merged**
