### PR TITLE
feat: [PL-23213]: Bitbucket CommitToNewBranch UpdateFile Use-case Handling

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 347 at r1](https://reviewable.io/reviews/harness/harness-core/31285#-MxgdpYt-2B7amdenfGd:-MxgdpYu4I2plx1xAN6b:bmxcwnp) ([raw file](https://github.com/harness/harness-core/blob/512304f071914f2992156c4e4f544aeee26818ee/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L347)):*
> ```Java
> 
>   @VisibleForTesting
>   protected String fetchLastCommitIdForFile(FileInfo request, EntityDetail entityDetailDTO) {
> ```

Can we make logic more explicit by splitting it into cases

1. Add to an existing branch
2. Add to a new branch
3. Update to an existing branch
4. Update to a new branch
5. Delete in an existing branch
6. Delete in a new branch

It would make code much simpler to read and understand.



_Code quote:_
```Java
fetchLastCommitIdForFile
```

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285#-:-Mxn4_LfBHisZcEMomSf:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: :shipit: complete! ✓

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 351 at r3](https://reviewable.io/reviews/harness/harness-core/31285#-MxnVE_V363IymJRT4pT:-MxnVE_V363IymJRT4pU:b-fc60m5) ([raw file](https://github.com/harness/harness-core/blob/5d9a4a06a505d44f686ee02f45b09dd25bd51599/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L351)):*
> ```Java
>     if (isEmpty(lastCommitIdForFile) && request.getChangeType() != ChangeType.ADD) {
>       // If its saveToNewBranch use-case, then we choose base branch for existing entity commit
>       String branch = request.getIsNewBranch() ? request.getBaseBranch().getValue() : request.getBranch();
> ```

.getValue can throw NPE, if baseBranch is not set, instead can we throw an exception in this case.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 351 at r3](https://reviewable.io/reviews/harness/harness-core/31285#-MxnVE_V363IymJRT4pT:-MxnVo5xBwtDyx9bOSb5:bvlk00n) ([raw file](https://github.com/harness/harness-core/blob/5d9a4a06a505d44f686ee02f45b09dd25bd51599/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L351)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

.getValue can throw NPE, if baseBranch is not set, instead can we throw an exception in this case.
</blockquote></details>

baseBranch is always set as DEFAULT.

Also, do you remember, when this issue occured during bitbucket testing, then what was the error on UI?

**Review by bhavya181 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: :shipit: complete! ✓

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 351 at r3](https://reviewable.io/reviews/harness/harness-core/31285#-MxnVE_V363IymJRT4pT:-MxnfxFJEQA3Nd2n9d1Z:b-revvrz) ([raw file](https://github.com/harness/harness-core/blob/5d9a4a06a505d44f686ee02f45b09dd25bd51599/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L351)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

baseBranch is always set as DEFAULT.

Also, do you remember, when this issue occured during bitbucket testing, then what was the error on UI?
</blockquote></details>

I think NPE was directly coming.

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31285)* status: :shipit: complete! ✓

**Pull request merged**
