### PR TITLE
[feat]: [DEL-4379] : Immutable delegate autoupgrade

### PR DESCRIPTION
**Pull request by AnupamIO**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35905)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Vulnerability 3 Vulnerabilities 
 * Code issue 2 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35905)

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35905)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 659 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8ixL70D5kOf947ij39:-N8ixL70D5kOf947ij3A:b-fo6kzu) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L659)):*
> ```Java
>         startChroniqleQueueMonitor();
>         // Monitor if delegateUpgrader is enabled.
>         upgraderMonitorExecutor.scheduleAtFixedRate(() -> {
> ```

I don't think we need this complexity for delegate to make sure the status is up to date. We can do that on manager, or better yet while reading the data (e.g. when UI requests it). We don't really need boolean saying if it's on/off, we can only have a timestamp and decide the boolean status dynamically based on the timestamp e.g. if lastUpdated within few hours, then it's ON, otherwise OFF. 
One problem I see is that customer can change the CronJob schedule to e.g. once a week, so we will say the autoUpgrade is off, even though it happens weekly. This is regardless of the solution and OK for now, if turns to be a problem we can have upgrader announce it's schedule to manager and have some more complex logic around calculating that boolean status later. 
___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8j-sphAGqdgn1Gq3P-:-N8j-sphAGqdgn1Gq3P0:b-po90g0) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java#L64)):*
> ```Java
>   public RestResponse<UpgradeCheckResult> getDelegateImageTag(@QueryParam("accountId") @NotEmpty String accountId,
>       @QueryParam("currentDelegateImageTag") @NotEmpty String currentDelegateImageTag,
>       @QueryParam("delegateGroupName") String delegateGroupName, @QueryParam("isNg") Boolean isNg) {
> ```

Unfortunately I don't think upgrader knows if it's CG/NG right now. Will need to look into how we can give it this info if needed
___
*[`400-rest/src/main/java/io/harness/delegate/service/impl/DelegateUpgraderServiceImpl.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8iZvQiCu9feSISgQXT:-N8iZvQiCu9feSISgQXU:bbhycxe) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/400-rest/src/main/java/io/harness/delegate/service/impl/DelegateUpgraderServiceImpl.java#L41)):*
> ```Java
> 
>   @Override
>   public UpgradeCheckResult getDelegateImageTag(
> ```

Looks like this method could call the other override instead & do the updateUpgrader thing
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 848 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8j03mNEsdJpioRiYgU:-N8j03mO1F4ifNMmNPrh:bpy2nui) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L848)):*
> ```Java
>         .stream()
>         .map(entry -> {
>           DelegateGroup delegateGroup = persistence.createQuery(DelegateGroup.class)
> ```

It's not a good idea to have a DB query from within stream. This means one query per stream item which can easily become very slow (and hammer DB). In this case this would also have a lot of repeat (same) queries. Better do something similar to what activeDelegateConnection does. Have one query that gets you all the data and then you post process it here (match to correct delegates).
Also, in queries consider projecting only the fields you need to speed them up, since in this case you have big records but need very little data from them. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8j1rqnBPzC4SDeMzo1:-N8j1rqnBPzC4SDeMzo2:b-g060t6) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java#L73)):*
> ```Java
>   @EntityIdentifier private String identifier;
> 
>   private boolean autoUpgrade;
> ```

We probably don't need this boolean, just timestamp should be enough for calculating the status dynamically,

**Review by gaurav-jain1 — COMMENTED** [review]
mostly looks good, after addressing Marko's comments.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35905#-:-N90Y6c_CrRH-SDoenuJ:b-bognpa)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/io/harness/delegate/service/DelegateUpgraderServiceTest.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/35905#-N90UqOGBq1j989MxsHy:-N90UqOGBq1j989MxsHz:bmslasr) ([raw file](https://github.com/harness/harness-core/blob/abb4b1cde0050088e9b8a81164b69282127a348a/400-rest/src/test/java/io/harness/delegate/service/DelegateUpgraderServiceTest.java#L30)):*
> ```Java
> import org.mockito.Mock;
> import org.mockito.runners.MockitoJUnitRunner;
> import software.wings.service.intfc.DelegateService;
> ```

we don't need this
___
*[`420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/35905#-N90UicV1DFArKS7dGk6:-N90UicWEVK4Mo12iPjG:b-3os8yl) ([raw file](https://github.com/harness/harness-core/blob/abb4b1cde0050088e9b8a81164b69282127a348a/420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClient.java#L31)):*
> ```Java
> import io.harness.delegate.beans.DelegateUnregisterRequest;
> import io.harness.delegate.beans.FileBucket;
> import io.harness.delegate.beans.UpgradeCheckResult;
> ```

we don't need this.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35905)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 659 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8ixL70D5kOf947ij39:-N91NVZL1AXVSWwJ3BU7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L659)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't think we need this complexity for delegate to make sure the status is up to date. We can do that on manager, or better yet while reading the data (e.g. when UI requests it). We don't really need boolean saying if it's on/off, we can only have a timestamp and decide the boolean status dynamically based on the timestamp e.g. if lastUpdated within few hours, then it's ON, otherwise OFF. 
One problem I see is that customer can change the CronJob schedule to e.g. once a week, so we will say the autoUpgrade is off, even though it happens weekly. This is regardless of the solution and OK for now, if turns to be a problem we can have upgrader announce it's schedule to manager and have some more complex logic around calculating that boolean status later. 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 848 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8j03mNEsdJpioRiYgU:-N91NYCK6c5kEQKTYsuh:b-a2ujfl) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L848)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

It's not a good idea to have a DB query from within stream. This means one query per stream item which can easily become very slow (and hammer DB). In this case this would also have a lot of repeat (same) queries. Better do something similar to what activeDelegateConnection does. Have one query that gets you all the data and then you post process it here (match to correct delegates).
Also, in queries consider projecting only the fields you need to speed them up, since in this case you have big records but need very little data from them. 
</blockquote></details>

Changed.
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/35905#-N8j1rqnBPzC4SDeMzo1:-N91NJLZ2r8LrdbKfIqU:b-k8qm6w) ([raw file](https://github.com/harness/harness-core/blob/e33e7902b61b13445b5c2d99f4b759d1764568ac/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java#L73)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

We probably don't need this boolean, just timestamp should be enough for calculating the status dynamically, 
</blockquote></details>

Sounds good. Done

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 12 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35905)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 14 files at r1, 4 of 12 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35905#-:-N9AMRG19bCO09sPJ_J1:bnfp4nl)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35905#-:-N9AxglE5AsmY3dMxsDH:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
