### PR TITLE
feat: [SRM-10542]: Added Change Details Card API

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33048)

### CODE REVIEW

**Review by deepak-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33048)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1378 at r1](https://reviewable.io/reviews/harness/harness-core/33048#-N1rU8OQ2sLfAqEHKs4d:-N1rU8OQ2sLfAqEHKs4e:b-f02x47) ([raw file](https://github.com/harness/harness-core/blob/0bd5feb86d27c01d5921a1a558d7f43f29890267/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1378)):*
> ```Java
>         serviceLevelObjectiveService.getByMonitoredServiceIdentifier(projectParams, monitoredServiceIdentifier);
> 
>     List<MonitoredServiceChangeDetailSLO> monitoredServiceChangeDetailSLOS = new ArrayList<>();
> ```

nit: monitoredServiceChangeDetailSLOs instead of monitoredServiceChangeDetailSLOS
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java` line 242 at r1](https://reviewable.io/reviews/harness/harness-core/33048#-N1rUKbr2S9f4CkeG0K1:-N1rUKbr2S9f4CkeG0K2:b26x0qc) ([raw file](https://github.com/harness/harness-core/blob/0bd5feb86d27c01d5921a1a558d7f43f29890267/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L242)):*
> ```Java
>     serviceLevelObjectiveService.create(
>         builderFactory.getProjectParams(), builderFactory.getServiceLevelObjectiveDTOBuilder().build());
>     List<MonitoredServiceChangeDetailSLO> monitoredServiceChangeDetailSLOS =
> ```

nit: monitoredServiceChangeDetailSLOs

**Review by deepak-harness — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33048)* status: :shipit: complete! ✓

**Comment by arpit-harness** [comment]
trigger ti2

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 15 of 16 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33048)* status: :shipit: complete! ✓

**Pull request merged**
