### PR TITLE
feat: [PIE-7143]: adding live status to fetch the live status of stag…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…e if strategy is involved.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

What is the issue?
The issue was that if the user tries to fetch the status of stage when one of the step is inside strategy, even if the one of the step inside strategy failed.

What is the change?
Introduced a new expression `liveStatus` that will take into account the status of steps inside strategy as well.

Impact?
No impact on existing functionalities

Testing? 
a)Tried the cases where strategy was involved and also the customer use-case mentioned in the ticket

ReleaseNotes summary needed? Yes

1. Is it new task type? No
2. Did you make changes to the code in a backward-compatible manner? Yes
3. Did you add a new class which is added in kryo serialization? - No
4. Will the new version of the delegate receive old version task and process? No
5. If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
6. Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No
7. If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
8. if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
9. Did you remove an enum → No
10. Did you add an enum(That too at end of list) → No
11. FeatureFlag Added/Removed -> No

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42636)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42636)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 321 at r1](https://reviewable.io/reviews/harness/harness-core/42636#-NLtA6I-1Lelcggy17VS:-NLtA6I04pqMQ8rcGeDy:b-1sh0gc) ([raw file](https://github.com/harness/harness-core/blob/23d964cb720f36a53f000792f9b4ada4eea4ce5e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L321)):*
> ```Java
>   // Extracts child list recursively from parentChildrenMap into finalList
>   private void extractChildList(Map<String, List<NodeExecution>> parentChildrenMap, String parentId,
>       List<NodeExecution> finalList, boolean includeChildrenOfStrategy) {
> ```

can we check what Naidu was pointing if we directly update the currentStatus to include strategy internal steps?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 328 at r1](https://reviewable.io/reviews/harness/harness-core/42636#-NLt7ggO1oPofxH8hWHL:-NLt7ggP39CsKzzSC62B:btkfaml) ([raw file](https://github.com/harness/harness-core/blob/23d964cb720f36a53f000792f9b4ada4eea4ce5e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L328)):*
> ```Java
>     finalList.addAll(children);
>     children.forEach(child -> {
>       // NOTE: We are ignoring the status of steps inside strategy because of max concurrency defined.
> ```

In the Note can you add based on this flag we are checking to include strategy internal steps or not

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 321 at r1](https://reviewable.io/reviews/harness/harness-core/42636#-NLtA6I-1Lelcggy17VS:-NLtCh609MblTtgonq_5:b-2af47b) ([raw file](https://github.com/harness/harness-core/blob/23d964cb720f36a53f000792f9b4ada4eea4ce5e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L321)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we check what Naidu was pointing if we directly update the currentStatus to include strategy internal steps?
</blockquote></details>

The impact would be on already existing pipelines. If we start taking into account this now then we will run into issues with CI because with CI the default behaviour is to continue even if step fails which will not happen if we make changes  directly. The user will have to update their  pipelines as their current behaviour will change.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42636)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 321 at r1](https://reviewable.io/reviews/harness/harness-core/42636#-NLtA6I-1Lelcggy17VS:-NLtYhp32z-BiJbKu84w:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/23d964cb720f36a53f000792f9b4ada4eea4ce5e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L321)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

The impact would be on already existing pipelines. If we start taking into account this now then we will run into issues with CI because with CI the default behaviour is to continue even if step fails which will not happen if we make changes  directly. The user will have to update their  pipelines as their current behaviour will change.
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 328 at r1](https://reviewable.io/reviews/harness/harness-core/42636#-NLt7ggO1oPofxH8hWHL:-NLtYk9u3sxALFothdc2:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/23d964cb720f36a53f000792f9b4ada4eea4ce5e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L328)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

In the Note can you add based on this flag we are checking to include strategy internal steps or not
</blockquote></details>

done

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42636)* status: :shipit: complete! ✓

**Pull request merged**
