### PR TITLE
[feat]: [PIE-8631]: Updated account settings for input set repo settings

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Updated account settings for managing input set and pipelines in different repos. Added in the preqa branch to have it as part of the current release.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44445)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44445)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44445)* status: :shipit: complete! ✓

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44445)* status: :shipit: complete! ✓

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/44445#-NPLk7wG2LEIpXaWhStP:-NPLk7wG2LEIpXaWhStQ:b-rivvrn) ([raw file](https://github.com/harness/harness-core/blob/8c13cac0255bd0df786a63a6d8d27b0c09494cdc/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L72)):*
> ```YAML
>     allowedScopes:
>       - ACCOUNT
>   - identifier: allow_different_repo_for_pipeline_and_input_sets
> ```

This change will be treated as removal of same_repo_for_pipeline_and_input_sets setting and will delete any setting user would have modified. Is this acceptable ?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44445)* status: 1 change requests. 1. unresolved discussions. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/44445#-NPLk7wG2LEIpXaWhStP:-NPLkjJU6mVaiaf_PDTV:b-103tsr) ([raw file](https://github.com/harness/harness-core/blob/8c13cac0255bd0df786a63a6d8d27b0c09494cdc/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L72)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This change will be treated as removal of same_repo_for_pipeline_and_input_sets setting and will delete any setting user would have modified. Is this acceptable ? 
</blockquote></details>

yes, that is fine
that was introduced as part of this release only

**Review by nishantsaini20 — APPROVED** [review]
Approved for settings.yml changes.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44445#-:-NPLlNQKCEP9zW3e1AIv:b-gp08d9)* status: :shipit: complete! ✓

**Pull request merged**
