### PR TITLE
fix: [PL-26255]: hotfix for setting fileUrl for ssh connectors

### PR DESCRIPTION
**Pull request by bhavya181**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34982)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/34982#-N6C__Y04Lg9ymrKL25i:-N6C__Y04Lg9ymrKL25j:bcv1llp) ([raw file](https://github.com/harness/harness-core/blob/99b194849bbd3305291eb4a5d37cb129141fc79a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L122)):*
> ```Java
>                 gitRepositoryDTO.getName(), linkedRepo));
>       }
>       return url;
> ```

why is this change in fileURL changes?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34982)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/34982#-N6C__Y04Lg9ymrKL25i:-N6D0kHz6pfif304jQ0s:b-yj96nw) ([raw file](https://github.com/harness/harness-core/blob/99b194849bbd3305291eb4a5d37cb129141fc79a/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java#L122)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this change in fileURL changes?
</blockquote></details>

because getUrl gives gitConnectionUrl, once that is set, but if for account level connector, if I do getGitConnectorUrl with a diff repoNmae, it will append repoName to that repoUrl
and we use this method in getFileUrl to getRepoUrl

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34982#-:-N6ExzTM8wg-_z6kIagq:bnfp4nl)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34982#-:-N6Ezan5Bc_hkQjOkToU:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
