### PR TITLE
fix: [CCM-5537]: Fixed Perspective clone not cloning rules

### PR DESCRIPTION
**Pull request by svmav**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30964)

### CODE REVIEW

**Comment by Rohit-Kaliki** [comment]
trigger messagecheck

**Review by Rohit-Kaliki — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30964)* status: Some of the checks are too old.

**Review by Rohit-Kaliki — APPROVED** [review]

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30964#-:-MwvuZmV7fVL9To8pnYm:bnfp4nl)* status: Some of the checks are too old.

**Comment by Rohit-Kaliki** [comment]
trigger ft1

**Comment by Rohit-Kaliki** [comment]
trigger ft2

**Review by Rohit-Kaliki — APPROVED** [review]

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30964#-:-MwvxZLJ5W57j1GwZRIj:bnfp4nl)* status: Some of the checks are too old.

**Review by trunapushpa — APPROVED** [review]

**Review by trunapushpa — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30964#-:-Mww-JnM5gs3b7n65wWq:bnfp4nl)* status: Some of the checks are too old.

**Pull request merged**
