### PR TITLE
fix: [DEL-4544]: Delay checking watcher upgrade during watcher start

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
In case when current watcher version differs from global, watcher starts its upgrade before starting delegate process.
Which will delay the delegate start time. As part of this patch, we can delay the watcher upgrade via 10second, in the hope 
that delegate will start by that time.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36188)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36188)

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36188)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 447 at r1](https://reviewable.io/reviews/harness/harness-core/36188#-N90YNHs5uIIfkQzkbi5:-N90YNHs5uIIfkQzkbi6:b-jexb3h) ([raw file](https://github.com/harness/harness-core/blob/c151409593ee63c7f104df96973915820c0a27cc/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L447)):*
> ```Java
>   private void startUpgradeCheck() {
>     upgradeExecutor.scheduleWithFixedDelay(
>         new Schedulable("Error while checking for upgrades", this::syncCheckForWatcherUpgrade), 10,
> ```

shouldn't it be 30 sec, just for being on safe side and there is no harm also



_Code quote:_
```Java
10
```

**Comment by gaurav-jain1** [comment]
trigger compile

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36188)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 447 at r1](https://reviewable.io/reviews/harness/harness-core/36188#-N90YNHs5uIIfkQzkbi5:-N90ZFoX52vdQuQqu_f6:b-519qio) ([raw file](https://github.com/harness/harness-core/blob/c151409593ee63c7f104df96973915820c0a27cc/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L447)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

shouldn't it be 30 sec, just for being on safe side and there is no harm also
</blockquote></details>

It shouldn't matter, since both the method are in synchronized block, so the thread gets the lock first will complete its job. We just want to give some start time to thread starting delegate process. 10sec should be more than enough.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36188)* status: 1. unresolved discussions.

**Pull request merged**
