### PR TITLE
feat: [PL-27892]: Add option to exclude support accounts in User Get API

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37634)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37634)

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Comment by gupta-utkarsh** [comment]
trigger ti2

**Comment by gupta-utkarsh** [comment]
trigger ti2

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37634#-:-NCT-bboDVOoun2bMvxN:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/37634#-NCT-TobAIsbuBj5k9ru:-NCT-TobAIsbuBj5k9rv:b-tfalho) ([raw file](https://github.com/harness/harness-core/blob/4929cf93ab6f4582f850f183ca9cb0a9a59f2867/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L251)):*
> ```Java
>   @Path("/{userId}")
>   public RestResponse<Optional<UserInfo>> getUser(@PathParam("userId") String userId,
>       @QueryParam("includeSupportAccounts") @DefaultValue("true") Boolean includeSupportAccounts) {
> ```

Default Value should be false or true?

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37634)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/37634#-NCT-TobAIsbuBj5k9ru:-NCTeGI8C4e2YlWNUVi3:b-z0ii5d) ([raw file](https://github.com/harness/harness-core/blob/4929cf93ab6f4582f850f183ca9cb0a9a59f2867/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L251)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Default Value should be false or true?
</blockquote></details>

Kept it to true to preserve original behavior.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37634)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37634)* status: Some of the checks are too old.

**Pull request merged**
