### PR TITLE
[feat]: [CDS-53895]: improvise mergeTemplateInputs and validate-template-inputs for useFromStage for template

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes
mergeTemplateInputs Api:
**sourceTemplate:**
template
    service:
      serviceRef: <+input>
      serviceInputs: <+input>
 **Pipeline having template linked**
pipeline:
   templateInput:
      service:
        useFromStage:
        	stage: s1

**Old Api Response**
    service:
      serviceRef: <+input>
      serviceInputs: <+input>
**New Api Response**
      service:
        useFromStage:
        	stage: s1

_________________________________________
ValidateTemplateInputApi (For validate reconcilation)

**sourceTemplate:**
template
    service:
      serviceRef: <+input>
      serviceInputs: <+input>
 **Pipeline having template linked**
pipeline:
   templateInput:
      service:
        useFromStage:
        	stage: s1
**Older Api Response**
validYaml: false

**New Api Response**
validYaml: true
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)* status: 14 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger ut6, ut9

**Comment by yogesh-chauhan** [comment]
trigger ti3

**Comment by yogesh-chauhan** [comment]
trigger ut3

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257#-:-NPwBZOx4H-lvUv6NNu-:bnfp4nl)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger ut0

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 14 files at r9, 13 of 13 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 11 of 13 files at r12, 3 of 3 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 17 files at r15, 11 of 12 files at r16, 4 of 4 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257#-:-NQEIl_w5PB2y0Om5l66:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 17 files at r15, 11 of 12 files at r16, 4 of 4 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44257)* status: :shipit: complete! ✓

**Pull request merged**
