### PR TITLE
fix: [CDS-74335]: render step group overrides functor in execution

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Right now, we are rendering serviceOverrideVariables everywhere eg. Service step. 
Here we would not have access to step group context which would result in rendering variables from service instead of step group overrides. 
So we are now rendering only in context of execution. And the onus of rendering manifests and other service properties will fall onto individual steps.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50746)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/50746#-N_tsrHy391Foxo8e2Rp:-N_tsrHy391Foxo8e2Rq:b6t87i1) ([raw file](https://github.com/harness/harness-core/blob/2ec2635272643fec61aadf12410ab91e22e0955a/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L126)):*
> ```Java
>   private boolean isCurrentContextInsideExecution(Ambiance ambiance) {
>     String fqn = AmbianceUtils.getFQNUsingLevels(ambiance.getLevelsList());
>     return EmptyPredicate.isNotEmpty(fqn) && fqn.contains("execution");
> ```

should we instead match using type in the levels ?

**Comment by hingerabhinav** [comment]
> should we instead match using type in the levels ?

@yogesh-chauhan Yes we can collect the group properties or identifiers and check.

**Comment by hingerabhinav** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50746)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/50746#-Na6PLmb6KcWPYyyn7jS:-Na6PLmb6KcWPYyyn7jT:b-2g4bj1) ([raw file](https://github.com/harness/harness-core/blob/94840886fbfcf5d4490d3b6aa6acd9e7ce8939d4/pipeline-service/service/src/main/java/io/harness/pms/expressions/PMSExpressionEvaluator.java#L114)):*
> ```Java
> 
>     // step group overrides are rendered within execution context only
>     if (isCurrentContextInsideExecution(ambiance)) {
> ```

as discussed try moving this logic to functor to return null

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/ServiceVariableOverridesFunctor.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/50746#-NaAn4DgBG1sUXbYJPpE:-NaAn4DgBG1sUXbYJPpF:b-xpwma8) ([raw file](https://github.com/harness/harness-core/blob/e417b887153ac29f526d604bcf1667158b21b193/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/ServiceVariableOverridesFunctor.java#L51)):*
> ```Java
>     Set<String> groups = levels.stream().map(Level::getGroup).collect(Collectors.toSet());
>     // step group overrides are rendered within execution context only
>     if (!groups.contains("EXECUTION")) {
> ```

We might give users, the ability to choose expression mode in the future. In that case, we will have to again fix this bug ? Lets say they choose "resolve to null" ?

nit: do we have a constant for this somewhere ? or else we can create a constant in this class

**Comment by hingerabhinav** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 2 files at r5, 8 of 9 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50746)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 2 files at r4, 1 of 2 files at r5, 8 of 9 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50746)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]

**Pull request merged**
