### PR TITLE
feat: [PIE-4366]: Fix name and identifier on step inputs tab

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35067)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35067)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`320-ci-execution/src/main/java/io/harness/ci/plan/creator/step/CIPMSStepPlanCreatorV2.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/35067#-N6M8eGv47QNPPU1zUyu:-N6M8eGv47QNPPU1zUyv:bfy6mxy) ([raw file](https://github.com/harness/harness-core/blob/7658cc13e7bc246c2eeb79231ff9e0533d4bc291/320-ci-execution/src/main/java/io/harness/ci/plan/creator/step/CIPMSStepPlanCreatorV2.java#L104)):*
> ```Java
>     Map<String, ByteString> metadataMap = new HashMap<>();
>     stepElement.setIdentifier(StageStrategyUtils.getIdentifierWithExpression(ctx, stepElement.getIdentifier()));
>     stepElement.setIdentifier(StageStrategyUtils.getIdentifierWithExpression(ctx, stepElement.getIdentifier()));
> ```

these two lines are duplicate.



_Code quote:_
```Java
    stepElement.setIdentifier(StageStrategyUtils.getIdentifierWithExpression(ctx, stepElement.getIdentifier()));
    stepElement.setIdentifier(StageStrategyUtils.getIdentifierWithExpression(ctx, stepElement.getIdentifier()));
```

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35067)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/35067#-N6MBVUyCMBv42IAEkXC:-N6MBVUyCMBv42IAEkXD:b-jipgx7) ([raw file](https://github.com/harness/harness-core/blob/7658cc13e7bc246c2eeb79231ff9e0533d4bc291/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L90)):*
> ```Java
>     YamlField stepsField =
>         Preconditions.checkNotNull(ctx.getCurrentField().getNode().getField(YAMLFieldNameConstants.STEPS));
>     config.setIdentifier(StageStrategyUtils.getIdentifierWithExpression(ctx, config.getIdentifier()));
> ```

Don't we need to set name also here?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35067)* status: 10 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/35067#-N6MBVUyCMBv42IAEkXC:-N6Mt1bMEixo3uwDASDr:b32v57) ([raw file](https://github.com/harness/harness-core/blob/7658cc13e7bc246c2eeb79231ff9e0533d4bc291/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupPMSPlanCreator.java#L90)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Don't we need to set name also here?
</blockquote></details>

+1
___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/35067#-N6Mt90tCWik-_ZtMK3_:-N6Mt90tCWik-_ZtMK3a:bq22le) ([raw file](https://github.com/harness/harness-core/blob/7658cc13e7bc246c2eeb79231ff9e0533d4bc291/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L71)):*
> ```Java
>     YamlField strategyField = ctx.getCurrentField().getNode().getField(YAMLFieldNameConstants.STRATEGY);
>     // Since strategy is a child of stage but in execution we want to wrap stage around strategy,
>     // we are swapping the uuid of stage and strategy node.
> ```

this comment needs to be updated



_Code quote:_
```Java
    // Since strategy is a child of stage but in execution we want to wrap stage around strategy,
    // we are swapping the uuid of stage and strategy node.
```

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/35067#-N6Mt90tCWik-_ZtMK3_:-N6NJ2rR8fAp8SVWGeAm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7658cc13e7bc246c2eeb79231ff9e0533d4bc291/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this comment needs to be updated
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
