### PR TITLE
fix: [CDS-35582]: Service Dashboard fix

### PR DESCRIPTION
**Pull request by shivamnegi94**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33419)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger compile

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33419)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger compile

**Comment by diptiman-adak** [comment]
trigger compile

**Pull request merged**
