### PR TITLE
fix: [CDS-50524]: Improving helm logs by adding hints around timeout exception

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
Improving helm logs by adding hints around timeout exception
 Hint: user can configure a custom timeout for failed step in the service manifest

## Testing
Screenshot 2023-01-20 at 5 20 29 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/42812#-NM8kIl84pyBrNVp2ZLC:-NM8kIl84pyBrNVp2ZLD:b-wnnx42) ([raw file](https://github.com/harness/harness-core/blob/9fedb82f83ce52fd2edaff155fc5fecbd54f00d6/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmCommandTaskNG.java#L157)):*
> ```Java
>       closeOpenCommandUnits(
>           helmCommandRequestNG.getCommandUnitsProgress(), getLogStreamingTaskClient(), sanitizedException);
>       if (((HelmNGException) sanitizedException).getCode().equals(ErrorCode.DATA)
> ```

This will never happen, as TaskNGDataException is thrown latter and we should you Hint/Explanation exceptions

**Comment by TarunUba1** [comment]
trigger ft1 ft2

**Comment by TarunUba1** [comment]
trigger ti3

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by achyuth-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 0 of 2 approvals obtained.

**Comment by abhinavsingh1196** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java` line 135 at r4](https://reviewable.io/reviews/harness/harness-core/42812#-NMDoWHk0I9f9Zw9J6L_:-NMDoWHk0I9f9Zw9J6La:b-aiq0jp) ([raw file](https://github.com/harness/harness-core/blob/b43a4f79e6da11d0dac9134ff373e2fca878126f/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java#L135)):*
> ```Java
>     if (lowerCaseMessage.contains(TIMEOUT_EXCEPTION)) {
>       return NestedExceptionUtils.hintWithExplanationException(
>           HINT_TIMEOUT_ERROR + "\"" + commandType + "\" and pass the flag", EXPLAIN_TIMEOUT_EXCEPTION + commandType,
> ```

nit: this would be more readable if you just use String.format instead of having hardcoded ,constant and variable strings all together. Also, this code block is repeated 3 times, can extract it into a separate method.



_Code snippet:_
```Java
String.format(STATIC_MESSAGE, var1, var2, var2...)
```

**Review by achyuth-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/42812#-NMDqQixA2CTEdEl7gv4:-NMDqQixA2CTEdEl7gv5:b-d382rm) ([raw file](https://github.com/harness/harness-core/blob/663dc7e34e300ce81dff8751f9c6292e8f7a04de/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java#L50)):*
> ```Java
>     public static final String HINT_RESOURCE_CONFLICT = "There is conflict due to existing resource(s)";
>     public static final String HINT_TIMEOUT_ERROR =
>         "You can configure “—timeout” command flag in the service manifest section. In advanced, you can add helm command type ";
> ```

we can improve this message to something like



_Code snippet:_
```Java
"--timeout flag can be configured inside the service manifest section, under Advanced section of Manifest Details. Select the command type %s and pass the timeout flag with an appropriate value."
```

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/42812#-NMDqQixA2CTEdEl7gv4:-NME0R9Z5XlF5GcqA1R7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/663dc7e34e300ce81dff8751f9c6292e8f7a04de/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmExceptionConstants.java#L50)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

we can improve this message to something like
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812#-:-NMED59A7FpkmYGFUH4P:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42812)* status: :shipit: complete! ✓

**Pull request merged**
