### PR TITLE
fix: [DEL-5281]: Add log to PT Rebalance state migration to task_unassigined

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
Add log to PT Rebalance state migration to task_unassigined for tracking purposes.

## Checklist
- [ x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39466)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/39466#-NFpLr89-zU4JMPulv-1:-NFpLr8A63swYOKMNPPy:brt8f95) ([raw file](https://github.com/harness/harness-core/blob/86a53fe03367aec8f8aaaa5fd72b37fe076fc253/390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java#L54)):*
> ```Java
>                     System.currentTimeMillis()
>                         + TimeUnit.MINUTES.toMillis(FibonacciBackOff.getFibonacciElement(new Random().nextInt(10)))));
>         log.info("State changed to task_unssigned for PT's {}", ptsToUpdate);
> ```

Add logs in the beginning of the migration saying migration started and one for end

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39466)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/39466#-NFpLr89-zU4JMPulv-1:-NFpQPy_-RwymYp3DDa3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86a53fe03367aec8f8aaaa5fd72b37fe076fc253/390-db-migration/src/main/java/io/harness/migrations/UpdateRebalanceStateToTaskUnAssigned.java#L54)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

Add logs in the beginning of the migration saying migration started and one for end
</blockquote></details>

Done.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39466)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
