### PR TITLE
feat:[CDS-74726]: optimize Jira Approvals to fetch filtered fields

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- Jira Approvals are optimised to only fetch required fields whenever possible. If for example, a JEXL criteria is present then this optimisation is skipped.
- The fields to be used for filtering are only computed once for an approval instance during the first callback event and saved in the entity to use further.
-  The previous computation is performed irrespective of the FF, and FF is used to control the param send to the delegate. This ensures consistency for running executions when FF is turned on/off.
- YAML saves the names of the field in approval criteria, hence we are fetching all the names to key mapping in first polling event, and computing the fields `query` param
- The entire fields name to key map is not fetched for following polling events irrespective of the FF to reduce response of `get issue` delegate task
- [Spec](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21451080128/Jira+API+Performance+Improvements#%5BhardBreak%5D%5BhardBreak%5DRequirement-3)
- [Test plan](https://docs.google.com/spreadsheets/d/1PfTDKLqKibFRfyO1dmlTkrhri_-GI8JdISfwws9njLc/edit#gid=0)
- Additional Dev Testing: backward compatibility with delegate and manager for pipeline service, name to key mapping correct for different field types, entire mapping populated only in first polling event and not later.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52049)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 28 of 29 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52049)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger uts

**Review by puthrayaharness — DISMISSED** [review]

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52049)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — DISMISSED** [review]

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger ut1

**Comment by naman-goenka** [comment]
trigger ut6

**Comment by naman-goenka** [comment]
trigger ut1

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52049)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
trigger gitleaks

**Comment by naman-goenka** [comment]
trigger review

**Pull request merged**
