### PR TITLE
feat: [FFM-8037]:  Add RBAC Env check for Feature Flag Pipelines

### PR DESCRIPTION
**Pull request by stephenmcconkey**
## Describe your changes
This adds an RBAC check to see if the user is permitted to toggle a flag on a pipeline on the environment configured
The way RBAC permissions are used on FF differs slightly due to the nature of our set up, so we have to tailor the function to work for us i.e. check for the 'ff_featureflag_toggle' permission.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)

### CODE REVIEW

**Comment by stephenmcconkey** [comment]
trigger messagecheck

**Review by stephenmcconkey — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by stephenmcconkey — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Comment by stephenmcconkey** [comment]
trigger uts

**Comment by stephenmcconkey** [comment]
trigger uts

**Review by akiraqb — DISMISSED** [review]
I talked to Stephen and Im happy enough

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: 1 file(s) to review. 1 change requests. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf/FlagConfigurationStep.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/48983#-NXUbUOo0VA8mhHKKk14:-NXUbUOo0VA8mhHKKk15:b-xfwlj8) ([raw file](https://github.com/harness/harness-core/blob/6453a031f614ee5c444c7c9bf9eb681a95856956/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf/FlagConfigurationStep.java#L97)):*
> ```Java
>   @Inject @Named("cfPipelineAPI") private CFApi cfApi;
>   @Inject OrchestrationStepConfig config;
>   @Inject @Named("PRIVILEGED") AccessControlClient accessControlClient;
> ```

Is priviledged client the correct usage?



_Code quote:_
```Java
@Named("PRIVILEGED")
```

**Review by stephenmcconkey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf/FlagConfigurationStep.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/48983#-NXUbUOo0VA8mhHKKk14:-NXUfY5d3KiRoMFUKv-H:b-39j3sx) ([raw file](https://github.com/harness/harness-core/blob/6453a031f614ee5c444c7c9bf9eb681a95856956/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf/FlagConfigurationStep.java#L97)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Is priviledged client the correct usage?
</blockquote></details>

Yeah, this is what we need!

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: 1 file(s) to review. 2 change requests. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf/FlagConfigurationStep.java` line 409 at r3](https://reviewable.io/reviews/harness/harness-core/48983#-NXWCd4l9RQ_XcNfilbg:-NXWCd4l9RQ_XcNfilbh:bktc42x) ([raw file](https://github.com/harness/harness-core/blob/6453a031f614ee5c444c7c9bf9eb681a95856956/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf/FlagConfigurationStep.java#L409)):*
> ```Java
>                                                     .build();
>         if (patchInstruction.getType() == Type.SET_FEATURE_FLAG_STATE) {
>           permissionCheckDTO.setPermission("ff_featureflag_toggle");
> ```

We need to perform access check on combination of Environment access and FF toggle edit permission.

We basically have 2 cases:
Feature Flag toggle which is done per environment.
Variations are applicable across environment.
When calling https://apidocs.harness.io/tag/Access-Control-List for Access check.
case-1: Check if user has access to certain Env resource eg:- Non-Prod
(ResourceType -  Environment
 resourceIdentifier - Non-Prod)
and FF toggle edit permission.

Note: For environments we support RBAC check by Environment Identifier and  by Environment Attribute Type(Only 2 Attribute Type supported ie Prod and Non-Prod). FF team will have to decide what granular level of RBAC check is needed.

case-2 : Check if user has access to All Env resource (ResourceType -  Environment) and FF toggle edit permission.
When no resourceIdentifier is passed it indicates performing RBAC check on all Environments.

**Comment by stephenmcconkey** [comment]
trigger uts

**Comment by stephenmcconkey** [comment]
trigger uts

**Comment by stephenmcconkey** [comment]
trigger uts

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: :shipit: complete! ✓

**Comment by stephenmcconkey** [comment]
trigger uts

**Comment by stephenmcconkey** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48983)* status: :shipit: complete! ✓

**Pull request merged**
