### PR TITLE
[fix]: [PL-38592]: Adds Redis cache OOM exception handling on caller side

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
As part this PR exception handling added in places where `cache.put` is being called before sending data. All such api calls were resulting in failures if Redis cache is down because of RedisOutOfMemoryException.

Tested in local
- Started another instance of Redis to be used as cache and assigned very low memory. So that any incoming request to this instance will fail with RedisOutOfMemoryException
- Without exception handling
	- Unable to access NG UI it was stuck in fetching license in ng-manager
	- List pipeline was throwing error 
- With exception handling
	- Able to access NG UI without any issue
	- List pipeline was working and returning pipelines

Error logs: Below out of memory error logs were coming in services but UI was working as expected

pipeline
----------
2023-07-28 00:10:53,694 [dw-190 - POST /api/pipelines/list?routingId=kmpySmUISimoRrJL6NL73w&accountIdentifier=kmpySmUISimoRrJL6NL73w&projectIdentifier=default_project&orgIdentifier=default&page=0&sort=lastUpdatedAt%2CDESC&size=20] ERROR io.harness.gitsync.persistance.EntityLookupHelper - Unable to set git enabled data into cache [X-requestId=77276685-538b-4e59-8114-b36cb69b326f] 
javax.cache.CacheException: javax.cache.CacheException: org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'. script: 5ab98e4e00a85adade56988ef4145cdd4e5e1fe6, on @user_script:1.. channel: [id: 0x6f378a6b, L:/127.0.0.1:49173 - R:/127.0.0.1:6380] data: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@10b86d3(incomplete)], command=(EVALSHA), params=[5ab98e4e00a85adade56988ef4145cdd4e5e1fe6, 8, hCache/gitEnabledCacheSdk, jcache_timeout_set:{hCache/gitEnabledCacheSdk}, jcache_created_channel:{hCache/gitEnabledCacheSdk}, jcache_removed_channel:{hCache/gitEnabledCacheSdk}, jcache_updated_channel:{hCache/gitEnabledCacheSdk}, jcache_created_sync_channel:{hCache/gitEnabledCacheSdk}, jcache_removed_sync_channel:{hCache/gitEnabledCacheSdk}, jcache_updated_sync_channel:{hCache/gitEnabledCacheSdk}, ...], codec=io.harness.redis.RedissonKryoCodec]
	at org.redisson.jcache.JCache.lambda$putAsync$16(JCache.java:1116)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)

ng-manager
----------
2023-07-28 00:07:17,545 [dw-235 - POST /licenses/versions?routingId=kmpySmUISimoRrJL6NL73w&accountIdentifier=kmpySmUISimoRrJL6NL73w] ERROR io.harness.licensing.services.DefaultLicenseServiceImpl - Unable to set license data into cache [X-requestId=615a29ab-9ae1-40ee-8826-9a942f4d5fe0] 
javax.cache.CacheException: javax.cache.CacheException: org.redisson.client.RedisOutOfMemoryException: command not allowed when used memory > 'maxmemory'. script: 5ab98e4e00a85adade56988ef4145cdd4e5e1fe6, on @user_script:1.. channel: [id: 0x0a33d16c, L:/127.0.0.1:62942 - R:/127.0.0.1:6380] data: CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@4d3b4213(incomplete)], command=(EVALSHA), params=[5ab98e4e00a85adade56988ef4145cdd4e5e1fe6, 8, hCache/NGLicense, jcache_timeout_set:{hCache/NGLicense}, jcache_created_channel:{hCache/NGLicense}, jcache_removed_channel:{hCache/NGLicense}, jcache_updated_channel:{hCache/NGLicense}, jcache_created_sync_channel:{hCache/NGLicense}, jcache_removed_sync_channel:{hCache/NGLicense}, jcache_updated_sync_channel:{hCache/NGLicense}, ...], codec=io.harness.redis.RedissonKryoCodec]
	at org.redisson.jcache.JCache.lambda$putAsync$16(JCache.java:1116)
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:183)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51103)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut0

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51103)* status: Some of the checks are too old. 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
exception handling added in places where `cache.put` is being called before sending data.  
Not very sure which places we can skip.
IMO adding this handling should not impact anything because it will eventually get data from db if put call fails to update cache

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51103)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/intfc/signup/SignupSpamChecker.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCPli9Wt3ADFGY7YW:-NcQCPli9Wt3ADFGY7YX:bq7ef82) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/400-rest/src/main/java/software/wings/service/intfc/signup/SignupSpamChecker.java#L49)):*
> ```Java
>     }
>     try {
>       trialEmailCache.put(emailAddress, registrationCount);
> ```

This data we don't store in DB. Wouldn't it lead to issues if we catch exception and swallow as cache is the source of truth here
___
*[`400-rest/src/main/java/software/wings/yaml/gitSync/GitSyncPollingJob.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCd7-2TQM8F1zoe6b:-NcQCd7-2TQM8F1zoe6c:b-8b0np2) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/400-rest/src/main/java/software/wings/yaml/gitSync/GitSyncPollingJob.java#L86)):*
> ```Java
>         }
>         try {
>           gitPollingCache.put(accountId, System.currentTimeMillis());
> ```

I would suggest we should get it reviewed from gitsync team
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/EntityLookupHelper.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCnQj8FkkijkfgUbm:-NcQCnQj8FkkijkfgUbn:b-8b0np2) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/EntityLookupHelper.java#L71)):*
> ```Java
>                   harnessToGitPushInfoServiceBlockingStub::isOldGitSyncEnabledForModule, isOldGitSyncEnabledForModule)
>               .getIsEnabled();
>       try {
> ```

I would suggest we should get it reviewed from gitsync team
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCsij0gC3ELKbual7:-NcQCsij0gC3ELKbual8:btmt4yp) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L75)):*
> ```Java
>    */
>   @Nullable
>   public List<PartialSchemaDTO> fetchSchema(
> ```

I would suggest we should get it reviewed from Pipeline team
___
*[`pipeline-service/service/src/main/java/io/harness/pms/sdk/PmsSdkInstanceService.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCw8sEvA7qxWpYnQx:-NcQCw8sEvA7qxWpYnQy:btmt4yp) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/pipeline-service/service/src/main/java/io/harness/pms/sdk/PmsSdkInstanceService.java#L147)):*
> ```Java
>             String.format("Update for PmsSdkInstance for module: [%s] Failed", request.getName()));
>       }
>       if (shouldUseInstanceCache) {
> ```

I would suggest we should get it reviewed from Pipeline team

**Comment by ashishsanodia-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/intfc/signup/SignupSpamChecker.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCPli9Wt3ADFGY7YW:-NcRUefE4mYSPpqfMlZ0:b-7b3ps0) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/400-rest/src/main/java/software/wings/service/intfc/signup/SignupSpamChecker.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This data we don't store in DB. Wouldn't it lead to issues if we catch exception and swallow as cache is the source of truth here
</blockquote></details>

As cache is source of truth and if cache is down we can not do much here. By adding exception handling we are just avoiding method to fail in between. This cache is having 1 hr expiry configured.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51103)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCsij0gC3ELKbual7:-NcSD-13AGncgXuxh0wW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L75)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I would suggest we should get it reviewed from Pipeline team
</blockquote></details>

Done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/sdk/PmsSdkInstanceService.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/51103#-NcQCw8sEvA7qxWpYnQx:-NcSD4PeDqV92OFZYBo3:blic96l) ([raw file](https://github.com/harness/harness-core/blob/53153934135b79730bf4a3e27c70ea09ff5d169d/pipeline-service/service/src/main/java/io/harness/pms/sdk/PmsSdkInstanceService.java#L147)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I would suggest we should get it reviewed from Pipeline team
</blockquote></details>

We want to throw exception here as here cache acts as first source of truth @ashishsanodia-harness

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51103)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51103)* status: 1 change requests. 3. unresolved discussions.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51103#-:-Ncg54Bv7IvdrK4Y5vq0:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
