### PR TITLE
feat: [PL-40205]: Pipeline metrics with accountId and status

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR modifies the existing plan execution active count metrics to plan execution count metrics which includes the existing Active statuses along with additional Success, Failure and abort status.

Tested this locally and the metrics will now be published as below -

plan_execution_count{accountId="kmpySmUISimoRrJL6NL73w",environment="localhost",status="SUCCEEDED",} 37.0
plan_execution_count{accountId="kmpySmUISimoRrJL6NL73w",environment="localhost",status="ABORTED",} 96.0
plan_execution_count{accountId="kmpySmUISimoRrJL6NL73w",environment="localhost",status="FAILED",} 106.0
plan_execution_count{accountId="kmpySmUISimoRrJL6NL73w",environment="localhost",status="RUNNING",} 2.0

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51045)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51045)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/51045#-NaLvSV6DGfBmR2Rbb4A:-NaLvSV6DGfBmR2Rbb4B:brgng8v) ([raw file](https://github.com/harness/harness-core/blob/6fc27342d2da21ed79797211bed476eb2b90ffd5/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L77)):*
> ```Java
>       EnumSet.of(RUNNING, ASYNC_WAITING, TASK_WAITING, TIMED_WAITING, DISCONTINUING);
> 
>   private final EnumSet<Status> ACTIVE_STATUSES = EnumSet.of(INTERVENTION_WAITING, WAIT_STEP_RUNNING, APPROVAL_WAITING,
> ```

These statuses are changed - keep it same as. -   private final EnumSet<Status> ACTIVE_STATUSES = EnumSet.of(RUNNING, INTERVENTION_WAITING, WAIT_STEP_RUNNING,
      APPROVAL_WAITING, RESOURCE_WAITING, ASYNC_WAITING, TASK_WAITING, TIMED_WAITING, DISCONTINUING, INPUT_WAITING);
___
*[`pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/51045#-NaLrz8F8mipWgyM-FJ5:-NaLrz8F8mipWgyM-FJ6:b-jhvskw) ([raw file](https://github.com/harness/harness-core/blob/52b84ebebb7ebb5c3522ce20d168ec9f505f29fe/pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml#L5)):*
> ```YAML
> metricGroup: plan_execution_count_metric_group
> metrics:
>   - metricName: plan_execution_active_count
> ```

if we change current metric name, what will happen to existing dashboards?

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51045)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/51045#-NaLvSV6DGfBmR2Rbb4A:-NamKwuR1YTujBjY0NRz:b1be4gd) ([raw file](https://github.com/harness/harness-core/blob/6fc27342d2da21ed79797211bed476eb2b90ffd5/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L77)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

These statuses are changed - keep it same as. -   private final EnumSet<Status> ACTIVE_STATUSES = EnumSet.of(RUNNING, INTERVENTION_WAITING, WAIT_STEP_RUNNING,
      APPROVAL_WAITING, RESOURCE_WAITING, ASYNC_WAITING, TASK_WAITING, TIMED_WAITING, DISCONTINUING, INPUT_WAITING);

</blockquote></details>

Okay, will update it.
___
*[`pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml` line 5 at r1](https://reviewable.io/reviews/harness/harness-core/51045#-NaLrz8F8mipWgyM-FJ5:-NamKZinD5RGtNIN3g2z:b-5iwn45) ([raw file](https://github.com/harness/harness-core/blob/52b84ebebb7ebb5c3522ce20d168ec9f505f29fe/pipeline-service/service/src/main/resources/metrics/metricDefinitions/execution-count-metrics.yaml#L5)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if we change current metric name, what will happen to existing dashboards?
</blockquote></details>

Yes, we will update the dashboards.

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
This has been implemented in a different way when the events are available.

**Pull request closed without merging**
