### PR TITLE
fix: [CDS-43125]: [BE] Add Download Artifact command unit Ssh/WinRm

### PR DESCRIPTION
**Pull request by bojanmicovic**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37570)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 24 Issues 
* Vulnerability 3 Vulnerabilities 
 * Code issue 20 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37570)

**Review by mdmilic — DISMISSED** [review]
Approve delegate related changes and hashcheck

> Reviewed 7 of 18 files at r1, 14 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37570#-:-NCKNSRs29KzrulgIL7f:b-5e7d2c)* status: 12 file(s) to review.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 18 files at r1, 2 of 7 files at r2, 1 of 1 files at r3, 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37570)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 142 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKZ1L32J1R-zcVy-If:-NCKZ1L32J1R-zcVy-Ig:b6cfq38) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L142)):*
> ```Java
>       if (artifactHandler == null) {
>         log.warn("Wrong artifact delegate config submitted");
>         throw new InvalidRequestException("Expecting artifactory or jenkins delegate config");
> ```

Minor - it is better to write the wrong artifact name into logs 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKZH1n6ZP8DmVS2Lcx:-NCKZH1n6ZP8DmVS2Lcy:b-9uorsu) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L146)):*
> ```Java
>       command =
>           artifactHandler.getCommandString(artifactDelegateConfig, commandUnit.getDestinationPath(), getScriptType());
>     } catch (Exception e) {
> ```

log exception here
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/JenkinsArtifactsUtils.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKZlwQBkALcZUwgUag:-NCKZlwQBkALcZUwgUah:b-ohsksx) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/JenkinsArtifactsUtils.java#L26)):*
> ```Java
> @UtilityClass
> @Slf4j
> @OwnedBy(CDP)
> ```

Put *Utils classes to utils package
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/ArtifactoryArtifactHandler.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKamLw67zkLNtMIeK7:-NCKamLw67zkLNtMIeK8:b-1ec3j2) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/ArtifactoryArtifactHandler.java#L27)):*
> ```Java
> @Slf4j
> @Singleton
> public class ArtifactoryArtifactHandler implements ArtifactHandler {
> ```

Minor - Rename ArtifactoryArtifactHandler >> ArtifactoryArtifactDownloadHandler and ArtifactHandler >> ArtifactDownloadHandler
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/JenkinsArtifactHandler.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKb_3u4FRf50AahNqL:-NCKb_3u4FRf50AahNqM:b-za94rp) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/JenkinsArtifactHandler.java#L25)):*
> ```Java
> @Slf4j
> @Singleton
> public class JenkinsArtifactHandler implements ArtifactHandler {
> ```

Minor - rename JenkinsArtifactHandler >> JenkinsArtifactDownloadHandler
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/NgCommandUnit.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKc2UxAzJyAVq7PKJ2:-NCKc2UxAzJyAVq7PKJ3:b3dj93u) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/NgCommandUnit.java#L19)):*
> ```Java
>   String getCommandUnitType();
>   String getWorkingDirectory();
>   default String getDestinationPath() {
> ```

It doesn't make sense to have a default method returning null, it's better to have only method signature and override it.

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 142 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKZ1L32J1R-zcVy-If:-NCLhLU44I9v8kQSRjGX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L142)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - it is better to write the wrong artifact name into logs 
</blockquote></details>

Done.

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKZH1n6ZP8DmVS2Lcx:-NCLhPNUAo_6A80uzdOe:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L146)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

log exception here
</blockquote></details>

done

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/ArtifactoryArtifactHandler.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKamLw67zkLNtMIeK7:-NCLhTKh64hAJlMPqttu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/ArtifactoryArtifactHandler.java#L27)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Rename ArtifactoryArtifactHandler >> ArtifactoryArtifactDownloadHandler and ArtifactHandler >> ArtifactDownloadHandler
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/JenkinsArtifactHandler.java` line 25 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKb_3u4FRf50AahNqL:-NCLhVcO7wRENTUKowIj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/JenkinsArtifactHandler.java#L25)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - rename JenkinsArtifactHandler >> JenkinsArtifactDownloadHandler
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/JenkinsArtifactsUtils.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKZlwQBkALcZUwgUag:-NCLhYJ2B0EvlfWXfS3E:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/JenkinsArtifactsUtils.java#L26)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Put *Utils classes to utils package
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/NgCommandUnit.java` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/37570#-NCKc2UxAzJyAVq7PKJ2:-NCLhaB-2XMNIrsOPfnJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6236130a5dde22d41aef43b514b75111e3c9128e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/NgCommandUnit.java#L19)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It doesn't make sense to have a default method returning null, it's better to have only method signature and override it. 
</blockquote></details>

Done

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37570#-:-NCM4BoN3FfK1auf3_PP:bnfp4nl)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37570)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
Adding new Command Unit and Handlers for download artifact.

**Comment by bojanmicovic** [comment]
1. Is it new task type? (If yes, no need to answer 2 then)
- No
2. Did you add a new class which is added in kryo serialization if yes then do not use that class in any of the delegate task payload till it makes to delegate release
- Yes
3. Did you make changes to the code in a backward-compatible manner?
- Yes
4. will the new version of the delegate receive old version task and process?
- Yes
5. If new version of the manager receives response for the old task will it be able to handle it successfully?
- Yes
6. Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
- No
7. If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
- Yes
8. if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
- Yes
9. Did you remove an enum → this is not backward compatible yet (tracked by DEL-3648: Move to name based kryo serializer for delegate/manager communication
- No
10. Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
- No

**Review by yogesh-chauhan — APPROVED** [review]
Approving because SSH is work in progress and not released to customers yet

**Comment by bojanmicovic** [comment]
trigger codebasehash

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37570)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 2 of 7 files at r2, 1 of 1 files at r3, 14 of 21 files at r4, 14 of 17 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37570)* status: :shipit: complete! ✓

**Pull request merged**
