### PR TITLE
feat: [CDS-40557]: ArtifactsStepV2 - Better mapping of CDTaskRequest to DelegateTaskRequest

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Instead of creating task from scratch, map the original task ( from CD Step Helper )
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38589)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger codeformat

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38589#-NE9eA1hE9NQHeRyYNW3:-NE9eA1hE9NQHeRyYNW4:b-ht1rq9) ([raw file](https://github.com/harness/harness-core/blob/49babe2d513c0e8a531d7f3345b2b693867245b6/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L99)):*
> ```Java
>                                                .build();
> 
>   //  private static final Duration DEFAULT_TIMEOUT = Duration.ofMinutes(1);
> ```

missed?



_Code quote:_
```Java
private static final long DEFAULT_TIMEOUT
```

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/38589#-NE9gAS796s5ynpE6PDg:-NE9gAS796s5ynpE6PDh:b6i5xrg) ([raw file](https://github.com/harness/harness-core/blob/49babe2d513c0e8a531d7f3345b2b693867245b6/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L159)):*
> ```Java
>       final DelegateTaskRequest delegateTaskRequest =
>           cdStepHelper.mapTaskRequestToDelegateTaskRequest(taskRequest.getTaskRequest(), taskRequest.getTaskData(),
>               taskRequest.getTaskSelectorYamls()
> ```

not sure, but will this always be nonNull for infra?



_Code quote:_
```Java
 cdStepHelper.mapTaskRequestToDelegateTaskRequest(taskRequest.getTaskRequest(
```

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/38589#-NE9gAS796s5ynpE6PDg:-NE9gMujBNb21CCEugkm:b-7iwvbp) ([raw file](https://github.com/harness/harness-core/blob/49babe2d513c0e8a531d7f3345b2b693867245b6/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L159)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

not sure, but will this always be nonNull for infra?
</blockquote></details>

this.



_Code quote:_
```Java
 taskRequest.getTaskSelectorYamls()
```

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38589)* status: 3 file(s) to review. 0 of 1 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38589)* status: 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38589)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38589#-NE9eA1hE9NQHeRyYNW3:-NEA3B_X5vlEb6Cu2iVf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49babe2d513c0e8a531d7f3345b2b693867245b6/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L99)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

missed?
</blockquote></details>

Done.

**Comment by AnshuH** [comment]
trigger ti2

**Comment by AnshuH** [comment]
trigger ti3

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38589)* status: :shipit: complete! ✓

**Pull request merged**
