### PR TITLE
[Feat]: [CDS-38475]: Improves error handling for extracting text variables

### PR DESCRIPTION
**Pull request by gitNavV**
JIRA: https://harness.atlassian.net/browse/CDS-38475

- **Problem**

- **Solution**

---
- **Created JUnit test-cases**
```

```
---
- **Screenshots**

- Earlier

- Now

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34192)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 1023 at r1](https://reviewable.io/reviews/harness/harness-core/34192#-N4C3QUtCu45-uLbU4fk:-N4C3QUu1qrrZ66trcLp:bhh023o) ([raw file](https://github.com/harness/harness-core/blob/b8f817d5b4f00968ff2c1f9f5cc8a6f514f32c41/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L1023)):*
> ```Java
>         .filter(entry -> "TEXT".equals(entry.getValueType()))
>         .collect(toMap(NameValuePair::getName, entry -> context.renderExpression(entry.getValue()), (a, b) -> {
>           throw new IllegalStateException(format("Duplicate key with values %s and %s", a, b));
> ```

let's return name instead of values.

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 1048 at r1](https://reviewable.io/reviews/harness/harness-core/34192#-N4C3YN78L16h3EvLxpB:-N4C3YN78L16h3EvLxpC:b-bl64pv) ([raw file](https://github.com/harness/harness-core/blob/b8f817d5b4f00968ff2c1f9f5cc8a6f514f32c41/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L1048)):*
> ```Java
>                           format("The encrypted variable %s was not found", entry.getName()), USER));
>             },
>             (a, b) -> { throw new IllegalStateException("Duplicate key detected"); }));
> ```

same - return with name

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/34192#-N4C3a_C9E27qS1lTpXZ:-N4C3a_C9E27qS1lTpX_:b2d1a94) ([raw file](https://github.com/harness/harness-core/blob/b8f817d5b4f00968ff2c1f9f5cc8a6f514f32c41/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L310)):*
> ```Java
>           .build();
>     } catch (IllegalStateException e) {
>       return ExecutionResponse.builder().executionStatus(ExecutionStatus.FAILED).errorMessage(e.getMessage()).build();
> ```

same exception branch

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34192)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by gitNavV — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34192)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 1023 at r1](https://reviewable.io/reviews/harness/harness-core/34192#-N4C3QUtCu45-uLbU4fk:-N4CzwuR9sJ_jpY2jaa7:b-extzqo) ([raw file](https://github.com/harness/harness-core/blob/b8f817d5b4f00968ff2c1f9f5cc8a6f514f32c41/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L1023)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

let's return name instead of values.
</blockquote></details>

Done in 3169189b5e63352007baf8790777fd82ea1d438a
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java` line 1048 at r1](https://reviewable.io/reviews/harness/harness-core/34192#-N4C3YN78L16h3EvLxpB:-N4D-BXbByxXZUIA1fax:by2ylwe) ([raw file](https://github.com/harness/harness-core/blob/b8f817d5b4f00968ff2c1f9f5cc8a6f514f32c41/400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java#L1048)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

same - return with name
</blockquote></details>

Done in 3169189b5e63352007baf8790777fd82ea1d438a.
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/34192#-N4C3a_C9E27qS1lTpXZ:-N4D-9H49GwYJ5XwzhyF:b-8wvyqc) ([raw file](https://github.com/harness/harness-core/blob/b8f817d5b4f00968ff2c1f9f5cc8a6f514f32c41/400-rest/src/main/java/software/wings/sm/states/provision/CloudFormationCreateStackState.java#L310)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

same exception branch
</blockquote></details>

Done in 3169189b5e63352007baf8790777fd82ea1d438a.

**Comment by gitNavV** [comment]
trigger messagecheck

**Comment by gitNavV** [comment]
trigger messagecheck

**Comment by gitNavV** [comment]
trigger feature-build

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34192)* status: :shipit: complete! ✓

**Pull request merged**
