### PR TITLE
feat: [OPA-549]: Remove OPA policy-mgmt git sync support

### PR DESCRIPTION
**Pull request by scottyw**
## Describe your changes

Support for Git Sync in HPE (PolicyMgmt) has been dropped as a feature. We are reverting support for Git Sync for the PolicyMgmt service.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34106)

### CODE REVIEW

**Comment by scottyw** [comment]
trigger messagecheck

**Comment by scottyw** [comment]
trigger ti0

**Comment by scottyw** [comment]
trigger ti0

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34106#-:-N4OHNIS6fBGSrxTRL9i:bnfp4nl)* status: Some of the checks are too old.

**Review by bhavya181 — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34106)* status: Some of the checks are too old.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34106#-:-N4SmbyC3FPHDrKZcfKo:bnfp4nl)* status: :shipit: complete! ✓

**Review by bhavya181 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34106)* status: :shipit: complete! ✓

**Comment by scottyw** [comment]
trigger ti2,tin4

**Comment by scottyw** [comment]
trigger ti4

**Pull request merged**
