### PR TITLE
feat: [DEL-5162]: mark unassignable pt tasks to unassigned on updatin…

### PR DESCRIPTION
**Pull request by arpit3107**
…g delegate tags

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39502)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1214 at r1](https://reviewable.io/reviews/harness/harness-core/39502#-NFt3AVE2bB7adRvGhqE:-NFt3AVE2bB7adRvGhqF:b-g0hlq9) ([raw file](https://github.com/harness/harness-core/blob/71ab3d946d3c1f3ed5b8218a88a9a5445719e907/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1214)):*
> ```Java
>     }
> 
>     subject.fireInform(DelegateObserver::onDelegateTagsUpdated, delegate.getAccountId());
> ```

how often this is called?

**Review by arpit3107 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39502)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1214 at r1](https://reviewable.io/reviews/harness/harness-core/39502#-NFt3AVE2bB7adRvGhqE:-NFwK5GI1HuuQmogmHz4:b4qsrd9) ([raw file](https://github.com/harness/harness-core/blob/71ab3d946d3c1f3ed5b8218a88a9a5445719e907/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1214)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

how often this is called?
</blockquote></details>

20-30 times in last one week. Mostly 3-4 accounts were playing with this. https://cloudlogging.app.goo.gl/KChYnYZksWppDzfu9

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39502)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39502)* status: :shipit: complete! ✓

**Pull request merged**
