### PR TITLE
[feat]: [CDS-36066]: Added helm manifest source repo CG-NG Mapping

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32349)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32349)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/service/ngManifestFactory/K8sManifestHelmSourceRepoStoreService.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/32349#-N0ZZkZR4CkwWyv15zAt:-N0ZZkZR4CkwWyv15zAu:bv22zs6) ([raw file](https://github.com/harness/harness-core/blob/df81eefa983729f90d05f7d7f2591c474ad8ff17/100-migrator/src/main/java/io/harness/ngmigration/service/ngManifestFactory/K8sManifestHelmSourceRepoStoreService.java#L49)):*
> ```Java
>                     .type(StoreConfigType.GIT)
>                     .spec(manifestMigrationService.getGitStore(gitFileConfig, entitySpec, connector.getIdentifier()))
>                     .build()))
> ```

nit, gitStore mapping can be extracted out in a separate class rather than embedding it into manifestMigrationService.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32349)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32349)* status: :shipit: complete! ✓

**Pull request merged**
