### PR TITLE
feat: [PL-25881]: Removing default Account Viewer role binding while adding user to Har…

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
…ness using SCIM.

## Describe your changes
Removing default Account Viewer role binding while adding user to Harness using SCIM Integration.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34341)

### CODE REVIEW

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34341)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/34341#-N4vtdJ03b15eXQw-p_l:-N4vtdJ03b15eXQw-p_m:b-f2x9hn) ([raw file](https://github.com/harness/harness-core/blob/262556cc12fa6dbe7e0df7678484bafa6e748909/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L110)):*
> ```Java
>       }
>       else
>       {
> ```

indentationissue

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34341)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34341#-:-N4ww4c32O-W-q8dt61-:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/34341#-N4vtdJ03b15eXQw-p_l:-N4x3AXw14t-Elf57ZVi:b-b9e9gj) ([raw file](https://github.com/harness/harness-core/blob/262556cc12fa6dbe7e0df7678484bafa6e748909/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L110)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

indentationissue
</blockquote></details>

else block is still unindented

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34341#-:-N4x3GOnC6vFVJON84MG:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
