### PR TITLE
[feat]: [PL-32217]: Multiple IdP updating 'logintype' and 'authentication-info' APIs 

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Currently for 'logintype' and 'authentication-info' we send only redirectUrl for SAML, and it can only be one per account. With multiple IdP these can be a List and more details like SAMLProviderType, friendlyName, etc are needed to be passed along.
The changes takes care of those. These APIs will be used in Gateway as upstream APIs.

`/api/users/v2/logintype?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w` : 
RESPONSE:

> {
    "metaData": {},
    "resource": {
        "authenticationMechanism": "SAML",
        "ssoRequests": [
            {
                "oauthProviderType": null,
                "oauthProviderTypes": null,
                "idpRedirectUrl": "https://dev-274703.oktapreview.com/app/dev-274703_samllclprat02_1/exk1lr51rykNSlTZT0h8/sso/saml?SAMLRequest=fZLNTsMwEITvPEXkuxPHaZvUaoIKCFGJn4oGDlyQcRZqNbGD1ymUpydtqVQOIPm0Hs%2Bsv93J6WdTB2twqK3JSRwyEoBRttLmLScP5SXNyGlxMkHZ1LwV084vzT28d4A%2BmCKC8%2F27c2uwa8AtwK21gof765wsvW9RRFEFa8rTQcqS0K68bB2sNXyEyjaRbNuj6%2BdtRK3q1knP%2BHMcwecqrt0wdpvV7aIun0q2zCJEG22FJJhd5OSrSqt0NB4DTeJkTAeZZFRmI04Ve6myQSz5KFO9FLGDmUEvjc8JZzyhbNifkieCjwQfhkk6fiLB3Flvla3PtNn%2Fv3NGWIkahZENoPBKLKY314KHTLzsRSiuynJO53eLkgSPB458y7Ena1Dsyf3v1f4Ek2IPWuw6dscO%2FxvIwyhI0VMNl9IZQAy1nUTHhsVhjre9w%2BxibmutNsGldY30fwfEYbyr6Iq%2B7qSiM9iC0q8aKhIVPxm%2Ft6P4Bg%3D%3D&RelayState=triggerType%3Dlogin",
                "ssoId": "LLPAbERsRfet6FgTSsidww",
                "friendlySamlName": "SAML_FRIENDLY_NAME_N000022",
                "samlProviderType": "OTHER"
            },
            {
                "oauthProviderType": null,
                "oauthProviderTypes": null,
                "idpRedirectUrl": "https://dev-274703.oktapreview.com/app/dev-274703_samllclprat02_1/exk1lr51rykNSlTZT0h8/sso/saml?SAMLRequest=fZLLTsMwEEX3fEXkvfNwGmpZTVABISrxqGhgwQa5zoRaTezgccrj60lbKpUFSF6Nr%2B8dn5nJ2UfbBBtwqK3JSRLGJACjbKXNa04eyyvKyVlxMkHZNqwT096vzAO89YA%2BmCKC88O7C2uwb8EtwG20gseHm5ysvO9QRFEFG8rGo3GchnbtZedgo%2BE9VLaNZNcdXb9sIxrVdE76mL0kEXysk8Zliftc3y2a8rmMVzxCtNFWSILZZU6%2B6ppzNZKcZlWc0lGqxpRnKqNLLpcpH9d1lpwOUsQeZga9ND4nLGYpjbPhlCwV7FSwLEx58kyCubPeKtuca7P%2Ff%2B%2BMsBI1CiNbQOGVWExvbwQLY7Hci1Bcl%2BWczu8XJQmeDhzZluNA1qDYk%2Fvfq%2FsJJsUetNh17I4d%2FjeQh1GQYqAarqQzgBhqO4mODYvDHO8Gh9nl3DZafQZX1rXS%2Fx2QhMmuoita76SiN9iB0rWGikTFT8bv7Si%2BAQ%3D%3D&RelayState=triggerType%3Dlogin",
                "ssoId": "400i20QwRp2uAbQRVHoVsg",
                "friendlySamlName": null,
                "samlProviderType": "OTHER"
            }
        ],
        "showCaptcha": false,
        "postRequest": false,
        "oauthEnabled": false
    },
    "responseMessages": []
}

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47432)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 176 at r5](https://reviewable.io/reviews/harness/harness-core/47432#-NUoPd7K7rE_ge90ZujD:-NUoPd7K7rE_ge90ZujE:boy6zn3) ([raw file](https://github.com/harness/harness-core/blob/ccb0ee70ef6942ddbe45d1fc755e5765ff9a5316/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L176)):*
> ```Java
>     LoginTypeResponse response = LoginTypeResponse.builder().build();
>     List<SSORequest> ssoRequests = getSSORequestsListForLoginTypeResponseInternal(userName, accountId, response, false);
>     if (isNotEmpty(ssoRequests) && ssoRequests.size() > 0) {
> ```

Aren't these two condition same?

**Review by piyush-harness — APPROVED** [review]
https://harness.atlassian.net/browse/PL-38541 Approving in lieu this ticket implementation, Code is

> Reviewed 7 of 21 files at r1, 3 of 8 files at r2, 15 of 16 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47432#-:-NUoPNYaE-3xjnuLsfL0:b-l679ik)* status: 27 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 176 at r5](https://reviewable.io/reviews/harness/harness-core/47432#-NUoPd7K7rE_ge90ZujD:-NUoSFeK9G50i6UEQAz5:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/ccb0ee70ef6942ddbe45d1fc755e5765ff9a5316/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L176)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Aren't these two condition same?
</blockquote></details>

yes

**Review by shashank-harness — APPROVED** [review]
> Reviewed 7 of 21 files at r1, 3 of 8 files at r2, 15 of 16 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47432)* status: 1. unresolved discussions.

**Comment by shashank-harness** [comment]
please update the testing done in PR description before merging

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 176 at r5](https://reviewable.io/reviews/harness/harness-core/47432#-NUoPd7K7rE_ge90ZujD:-NUoWI3Q07-o8YXTPDuk:b-npe0gs) ([raw file](https://github.com/harness/harness-core/blob/ccb0ee70ef6942ddbe45d1fc755e5765ff9a5316/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L176)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

yes
</blockquote></details>

:smile: will handle it in any of my next PR, thanks

**Pull request merged**
