### PR TITLE
fix: [SPG-1024]: adding instance index

### PR DESCRIPTION
**Pull request by lasdox**
## Describe your changes
The current query has to fetch all documents from a time range, and examine its appId. This is costly for customer that has lots of instances.

We can solve this creating an index that satisfies the queries and also has appId in it.
We also need to make the query covered by the index, creating a { appId: 1, _id: 0 } projection
https://www.mongodb.com/docs/manual/core/query-optimization/

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40461)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40461)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40461)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/40461#-NHSWHJZCmMTbSKPKE5y:-NHSWHJZCmMTbSKPKE5z:bi5j3zw) ([raw file](https://github.com/harness/harness-core/blob/03e337054b924c00c5ef9e6dabe3305c1ee2f83e/400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java#L166)):*
> ```Java
>             .field(InstanceKeys.accountId)
>             .descSortField(InstanceKeys.createdAt)
>             .rangeField(InstanceKeys.appId)
> ```

what's significance of rangeField? Why not normal field?

**Comment by lasdox** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40461)_ status: :shipit: complete! ✓
> 
> _[`400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/40461#-NHSWHJZCmMTbSKPKE5y:-NHSWHJZCmMTbSKPKE5z:bi5j3zw) ([raw file](https://github.com/harness/harness-core/blob/03e337054b924c00c5ef9e6dabe3305c1ee2f83e/400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java#L166)):_
> 
> > ```java
> >             .field(InstanceKeys.accountId)
> >             .descSortField(InstanceKeys.createdAt)
> >             .rangeField(InstanceKeys.appId)
> > ```
> 
> what's significance of rangeField? Why not normal field?

@inderschera 
It enforces order on index, fields are evaluated first, then sort and then range. Also it is easier to read and understand the ESR rule.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40461)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/40461#-NHSWHJZCmMTbSKPKE5y:-NHce5I0908xbBqPiQZt:b-indzdu) ([raw file](https://github.com/harness/harness-core/blob/03e337054b924c00c5ef9e6dabe3305c1ee2f83e/400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java#L166)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

@inderschera 
It enforces order on index, fields are evaluated first, then sort and then range. Also it is easier to read and understand the ESR rule.

</blockquote></details>

But we added appId just for projections right? so that we don't have to do doc scan. probably we could have only field here unless there is some special significance of rangeField.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40461)* status: :shipit: complete! ✓

**Pull request merged**
