### PR TITLE
feat: [PL-26058]: Settings service

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 30 files at r4, 2 of 40 files at r9, 11 of 26 files at r10, 1 of 12 files at r11, 9 of 15 files at r12, 17 of 19 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)* status: 44 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingConfigurationDTO.java` line 31 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5iiZjf7o7HyiDCIQxV:-N5iiZjf7o7HyiDCIQxW:b-81og6) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingConfigurationDTO.java#L31)):*
> ```Java
>   @Schema(description = SettingConstants.NAME) @NotNull @NotBlank @NGEntityName String name;
>   @Schema(description = SettingConstants.CATEGORY) @NotNull @NotBlank SettingCategory category;
>   @Schema(description = SettingConstants.DEFAULT_VALUE) @NotNull @NotBlank String defaultValue;
> ```

This is not a mandatory field and hence can have null value as well.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingResponseDTO.java` line 24 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikJ7Q3yNHO7fDL9ci:-N5ikJ7Q3yNHO7fDL9cj:btxfhw7) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingResponseDTO.java#L24)):*
> ```Java
> public class SettingResponseDTO {
>   @NotNull SettingDTO setting;
>   @NotNull @Schema(description = SettingConstants.NAME) String name;
> ```

Should this field be part of SettingDTO?
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java` line 22 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikq259cLrKqYSVMlw:-N5ikq259cLrKqYSVMlx:buuoaa6) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java#L22)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> @Data
> public class SettingValueRequestDTO {
> ```

Is this DTO required?
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java` line 23 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikt7e57Y8j4dkz0_a:-N5ikt7fARRQPJN4d2xi:b-cj5r2w) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java#L23)):*
> ```Java
> @Data
> public class SettingValueRequestDTO {
>   @Schema(description = SettingConstants.IDENTIFIER) @NotNull @NotBlank @EntityIdentifier String identifier;
> ```

This can be api path param
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java` line 24 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikx530pfXDznszeFG:-N5ikx530pfXDznszeFH:b5y71sy) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java#L24)):*
> ```Java
> public class SettingValueRequestDTO {
>   @Schema(description = SettingConstants.IDENTIFIER) @NotNull @NotBlank @EntityIdentifier String identifier;
>   @NotNull @NotBlank @Schema(description = SettingConstants.CATEGORY) SettingCategory category;
> ```

This can also be a path param
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java` line 73 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ilTjD0m0dkJKGfNgS:-N5ilTjD0m0dkJKGfNgT:b-iu1djz) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java#L73)):*
> ```Java
> public interface SettingsResource {
>   @GET
>   @Path("{category}/{identifier}")
> ```

Since setting identifier is unique across categories, {category} as a path param is not required
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java` line 94 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ilwwM-8vgsZZ0g6Jn:-N5ilwwM-8vgsZZ0g6Jo:b-u6j0xw) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java#L94)):*
> ```Java
> 
>   @GET
>   @Path("{category}")
> ```

Should we keep the path as "category/{category}"
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java` line 100 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5imFwc-9c8m_-v4-NA:-N5imFwd4Pjwut2TtzjQ:be6eyxs) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java#L100)):*
> ```Java
>       {
>         @io.swagger.v3.oas.annotations.responses.
>         ApiResponse(responseCode = "default", description = "This contains a list of Settings")
> ```

Improve description. Include information that settings belonging to only a particular category are returned.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/NGSettingsModule.java` line 9 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5imrVd2M0wM7-rTZr-:-N5imrVd2M0wM7-rTZr0:bz3gpin) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/src/main/java/io/harness/NGSettingsModule.java#L9)):*
> ```Java
> import java.util.concurrent.atomic.AtomicReference;
> 
> public class NGSettingsModule extends AbstractModule {
> ```

There is one more module class define. This class should not be required.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/entities/ConfigurationState.java` line 25 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5jHglfD_xEaxiIo6su:-N5jHglfD_xEaxiIo6sv:b-3nack3) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/entities/ConfigurationState.java#L25)):*
> ```Java
> @Entity(value = "configurationState", noClassnameStored = true)
> @Document("configurationState")
> @TypeAlias("configurationState")
> ```

Rename value to NGConfigurationState
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 27 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5iqHMj8hbA7c3_b-mU:-N5iqHMj8hbA7c3_b-mV:b-98zacm) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L27)):*
> ```Java
>   @Override
>   public ResponseDTO<SettingValueResponseDTO> get(String identifier, SettingCategory category, String accountIdentifier,
>       String orgIdentifier, String projectIdentifier, SettingValueRequestDTO settingValueRequetDTO) {
> ```

What is the need of SettingValueRequestDTO param here?
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 375 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5jUMsQ2SidiY9On02q:-N5jUMsQ2SidiY9On02r:b-4bygje) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L375)):*
> ```Java
>     modules.add(cacheModule);
> 
>     //    modules.add(NGSettingsModule.getInstance());
> ```

remove commented code
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 85 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jM0n9CLeVn3HZCvu_:-N5jM0n9CLeVn3HZCvua:bnh0k6w) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L85)):*
> ```Java
>     List<SettingResponseDTO> settingResponseDTOList = new ArrayList<>();
>     while (settingsConfigurationIterator.hasNext()) {
>       SettingConfiguration settingConfiguration = settingsConfigurationIterator.next();
> ```

Move the logic to mapper method.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 126 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jOKJ11JPmmsZiy0Ss:-N5jOKJ11JPmmsZiy0St:bp7ooj4) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L126)):*
> ```Java
>                 settingRequestDTO.getIdentifier());
>         Setting updatedSettingResponse = null;
>         if (settingRequestDTO.getUpdateType() == SettingUpdateType.RESTORE) {
> ```

Move this as different method.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 146 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jO9x50uDODlKno6qx:-N5jO9x50uDODlKno6qy:bo1he3f) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L146)):*
> ```Java
>             updatedSetting.setValue(settingRequestDTO.getValue());
>             updatedSetting.setAllowOverrides(settingRequestDTO.getAllowOverrides());
>             updatedSetting.setLastModifiedAt(System.currentTimeMillis());
> ```

This is not required as field in entity is annotated with last modified annotation.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 162 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jO_SRDmNWXbqRmn0q:-N5jO_SSB9_fi7tH5tBq:b-k1k9fw) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L162)):*
> ```Java
>                       .setting(settingDTO)
>                       .name(settingConfiguration.getName())
>                       .lastModifiedAt(System.currentTimeMillis())
> ```

Here also not required.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)* status: 46 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 375 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5jUMsQ2SidiY9On02q:-N5nBjXz0eFvTOkzITzH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L375)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

remove commented code
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingConfigurationDTO.java` line 31 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5iiZjf7o7HyiDCIQxV:-N5nBmh_1ipH3jFyTfUb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingConfigurationDTO.java#L31)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This is not a mandatory field and hence can have null value as well.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java` line 22 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikq259cLrKqYSVMlw:-N5nBotw0LJg_4BQupDu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java#L22)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is this DTO required?
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java` line 23 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikt7e57Y8j4dkz0_a:-N5nBpOQ0No8jnf3BIae:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java#L23)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This can be api path param
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java` line 24 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikx530pfXDznszeFG:-N5nBpp16XY0e5EYeNrn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingValueRequestDTO.java#L24)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This can also be a path param
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/NGSettingsModule.java` line 9 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5imrVd2M0wM7-rTZr-:-N5nBrtJA_IX7Yosy2gb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/src/main/java/io/harness/NGSettingsModule.java#L9)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

There is one more module class define. This class should not be required.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java` line 73 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ilTjD0m0dkJKGfNgS:-N5nBOgyA-AUXI9JLIwW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java#L73)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Since setting identifier is unique across categories, {category} as a path param is not required
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java` line 94 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ilwwM-8vgsZZ0g6Jn:-N5nBPz-4EjPtVtHYDQZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java#L94)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should we keep the path as "category/{category}"
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java` line 100 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5imFwc-9c8m_-v4-NA:-N5nBQnbEKCh7NoOK3is:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/remote/SettingsResource.java#L100)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Improve description. Include information that settings belonging to only a particular category are returned.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/entities/ConfigurationState.java` line 25 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5jHglfD_xEaxiIo6su:-N5nBSBQAAAsRjG5rlCW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/entities/ConfigurationState.java#L25)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Rename value to NGConfigurationState
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 27 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5iqHMj8hbA7c3_b-mU:-N5nBX8JBfr0kN6n_HoH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L27)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What is the need of SettingValueRequestDTO param here?
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 85 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jM0n9CLeVn3HZCvu_:-N5nBsn8-MYQjTQV5VKM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L85)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Move the logic to mapper method.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 126 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jOKJ11JPmmsZiy0Ss:-N5nBvQb-dNdRLIk8wCj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L126)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Move this as different method.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 146 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jO9x50uDODlKno6qx:-N5nBv--3oUa6NbO2zYy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L146)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This is not required as field in entity is annotated with last modified annotation.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 162 at r14](https://reviewable.io/reviews/harness/harness-core/34651#-N5jO_SRDmNWXbqRmn0q:-N5nBvv62dopoftn6_WN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba9260af99464fe3c34770d08b38a61f9ce7f981/120-ng-manager/modules/ngsettings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L162)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Here also not required.
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 54 files at r15, 13 of 53 files at r16, 2 of 28 files at r17, 3 of 15 files at r19, 41 of 61 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)* status: 62 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 71 at r20](https://reviewable.io/reviews/harness/harness-core/34651#-N5oWs6P4gsDL-9Fcwza:-N5oWs6P4gsDL-9Fcwzb:b-2ux0yo) ([raw file](https://github.com/harness/harness-core/blob/f79f1f024c257352020a882216e2ba06e74f4008/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L71)):*
> ```Java
>   }
> 
>   public static SettingSource getSettingSource(String orgIdentifier, String projectIdentifier) {
> ```

Move this to a utility class. Method argument can be Setting object.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)* status: 62 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 71 at r20](https://reviewable.io/reviews/harness/harness-core/34651#-N5oWs6P4gsDL-9Fcwza:-N5ppwnK52ZzcdtVv0Iu:bur7qek) ([raw file](https://github.com/harness/harness-core/blob/f79f1f024c257352020a882216e2ba06e74f4008/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L71)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Move this to a utility class. Method argument can be Setting object.
</blockquote></details>

This is a temporary method only. Once we have the setting value resolution logic in place post the lean release, I will revamp this code anyways.
___
*[`120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingResponseDTO.java` line 24 at r13](https://reviewable.io/reviews/harness/harness-core/34651#-N5ikJ7Q3yNHO7fDL9ci:-N5ppkXiCXrKq0II1OUk:bcw66f9) ([raw file](https://github.com/harness/harness-core/blob/4847490f2a5b3355fcea00b50c525fb0868e559a/120-ng-manager/modules/ngsettings/contracts/src/main/java/io/harness/ngsettings/beans/SettingResponseDTO.java#L24)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should this field be part of SettingDTO?
</blockquote></details>

Lets decide this later as whether to keep name in BE or not is not finalised yet

**Comment by piyush-harness** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 71 at r25](https://reviewable.io/reviews/harness/harness-core/34651#-N5s7j-i22sF2AbLz29W:-N5s7j-i22sF2AbLz29X:b-ndn2vb) ([raw file](https://github.com/harness/harness-core/blob/441815060e58ab756a91b28306db9177b6d8338f/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L71)):*
> ```Java
> 
>   public static SettingSource getSettingSource(String orgIdentifier, String projectIdentifier) {
>     if (orgIdentifier != null) {
> ```

This should be isNotEmpty check

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 4 of 57 files at r20, 13 of 52 files at r21, 2 of 15 files at r24, 45 of 63 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)* status: 64 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 29 files at r22, 1 of 15 files at r24, 1 of 61 files at r25, 13 of 58 files at r26, 2 of 28 files at r27, 3 of 15 files at r29, 49 of 67 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34651)* status: 67 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by nishantsaini20** [comment]
Refer to this PR instead: https://github.com/harness/harness-core/pull/34973

**Pull request closed without merging**
