### PR TITLE
[techdebt]: [SPG-764]: Adding Commons YAML, Refactoring APIs

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Adds Commons YAML for OpenAPI spec in harness-core
Also refactors API folder to incorporate internal APIs in the same API spec.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40701)

### CODE REVIEW

**Comment by AnshuH** [comment]
trigger ti2

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40701)* status: :shipit: complete! ✓

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40701)* status: :shipit: complete! ✓

___
*[`access-control/contracts/openapi/v1/openapi.yaml` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/40701#-NHxet1T0tQOG_K06d7V:-NHxet1T0tQOG_K06d7W:b3ty3rv) ([raw file](https://github.com/harness/harness-core/blob/959803984312dd7c47dcf8421cee385eedef51c2/access-control/contracts/openapi/v1/openapi.yaml#L11)):*
> ```YAML
>     email: contact@harness.io
> servers:
>   - url: 'http://api.harness.io'
> ```

typo? or intentional?

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40701)* status: :shipit: complete! ✓

**Pull request merged**
