### PR TITLE
feat: [PL-24534]: Integrate git aware persistence v2 find() method with error handling

### PR DESCRIPTION
**Pull request by mohitg0795**
- Added global context for SCM git metadata. Its required to fill in details related to git in case of remote operations. SDK will ensure its properly populated and this will be the source of truth for anything once SDK returns any response.
- Completed handling of find() method in new git SDK. It is a backward compatible find() method for git sync use-case.
- Added error handling for git sync sdk grpc service, specifically for getFile() operation for now. It works on statusCode (used same as httpCode). Based on statusCode, different exceptions are thrown from sdk layer. More refined status codes to be added going forward.

-----------------------------------------------------------------
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32407)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceV2Impl.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/32407#-N0US6p81LC1L9aS3WvS:-N0US6p81LC1L9aS3WvT:b-wj4d1t) ([raw file](https://github.com/harness/harness-core/blob/034451d5361121715d951c9dea9d361b3889f454/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceV2Impl.java#L47)):*
> ```Java
>     if (savedEntityOptional.isPresent()) {
>       GitAware savedEntity = savedEntityOptional.get();
>       if (savedEntity.getStoreType() == null) {
> ```

We call existing find() method and get the saved object. If storeType==null, then only we need to return the object, coz then its an existing entity not onboarded to new flow. Otherwise, we will find object with respect to new flow.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmErrorDetails.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/32407#-N0USN8w-P1qwqrZxpxv:-N0USN8w-P1qwqrZxpxw:b-y7rykd) ([raw file](https://github.com/harness/harness-core/blob/034451d5361121715d951c9dea9d361b3889f454/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmErrorDetails.java#L22)):*
> ```Java
> @Builder
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class ScmErrorDetails {
> ```

Added new pojo to ensure flexibility in error details, it is used in the scm error handler interface. The idea is that going forward, this will also have fields like "hint" and "explanation", so that it can be appropriately used while creating final exceptions in the error handlers.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/GetFileScmErrorHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/32407#-N0USd_b0FAaQKUeXPdX:-N0USd_c8WKzhMrx79Ki:b25wrwa) ([raw file](https://github.com/harness/harness-core/blob/034451d5361121715d951c9dea9d361b3889f454/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/GetFileScmErrorHandler.java#L23)):*
> ```Java
> public class GetFileScmErrorHandler extends ScmErrorHandler {
>   @Override
>   void handleError(int statusCode, ScmErrorDetails errorDetails) {
> ```

if errorDetails is properly populated, then we can also attach required hints and explanations here. Currently, not using it, but it will be handled going forward.

**Review by hextechpal — APPROVED** [review]
> Reviewed 16 of 17 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32407)* status: 18 file(s) to review. 1 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceV2Impl.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/32407#-N0US6p81LC1L9aS3WvS:-N0UfIyA4lwPSKoG0olc:byz5jee) ([raw file](https://github.com/harness/harness-core/blob/034451d5361121715d951c9dea9d361b3889f454/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceV2Impl.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We call existing find() method and get the saved object. If storeType==null, then only we need to return the object, coz then its an existing entity not onboarded to new flow. Otherwise, we will find object with respect to new flow.
</blockquote></details>

Include it as a comment in the code itself

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceV2Impl.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/32407#-N0EjEyHk0yC1EGfu3Ta-r4-66:-N0V2nZV0jeLAa67Qnm7:b-2rh1xy) ([raw file](https://github.com/harness/harness-core/blob/458de04a0ff705e569a28be39eae693d486e3db5/900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/GitAwarePersistenceV2Impl.java#L66)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

If store type is inline then the scm git metadata would be null or an object with empty fields?
</blockquote></details>

Do we send empty values in current scenario in git details for non-git-synced pipelines?

I think empty scm git metadata should be good. I will incorporate change for it.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/32407)

**Pull request closed without merging**
