### PR TITLE
fix: [CDS-41336]: Resolve manifest/artifacts/files in their individual steps  

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
This is only for the new steps ( ManifestsV2/ ArtifactsV2/ ConfigFilesV2 )
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)

### CODE REVIEW

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)* status: :shipit: complete! ✓

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)* status: :shipit: complete! ✓

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/37208#-NBIQVG8Du0nsvCZFlkD:-NBLV4RU4nbI6mCv73xf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/38d2fbb13bd3407e3caa0164c143b78fe5c102ce/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L123)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: would it make difference if we resolve them in one call itself.
As you have done here.
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37208)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger api_backwardcompatibility

**Comment by yogesh-chauhan** [comment]
trigger pr_apibackwardcompatibility

**Comment by yogesh-chauhan** [comment]
trigger api_backwardcompatibility

**Pull request merged**
