### PR TITLE
[feat]: [PIE-2382]: Added get yaml for executions

### PR DESCRIPTION
**Pull request by smjt-h**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)

### CODE REVIEW

**Review by naidu-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RRvPQ443--V8BrgjC:-N4RRvPQ443--V8BrgjD:b81nv1r) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
> ```Java
> 
>   @GET
>   @Path("getmetadata/{planExecutionId}")
> ```

/{planExecutionId}/metadata
or
i would prefer /{planExecutionId}/executedYaml

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSelP6XPTdIFUa5R0:-N4RSelP6XPTdIFUa5R1:b-z4yhu8) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
> ```Java
> 
>   @GET
>   @Path("getmetadata/{planExecutionId}")
> ```

M capital
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 281 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSO7TDoVioGczQANj:-N4RSO7UEjQJwWCEHPxk:bekrq1z) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L281)):*
> ```Java
>   @ApiOperation(value = "Get metadata of an execution", nickname = "getExecutionData")
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)
>   @Operation(operationId = "getExecutionData", summary = "Get execution metadata of a pipeline",
> ```

of a pipeilne execution*
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSh_rD_dxerc16M8W:-N4RSh_rD_dxerc16M8X:bniagv0) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L290)):*
> ```Java
>   public ResponseDTO<ExecutionDataResponseDTO>
>   getExecutions(@NotNull @PathParam(NGCommonEntityConstants.PLAN_KEY) @Parameter(
>       description = "planExecutionId of the execution for which we want to get Metadata") String planExecutionId) {
> ```

ExecutionId -> no need of saying 'planExecutionId'
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSryPEgh5DcrSNz0p:-N4RSryPEgh5DcrSNz0q:bj6s84k) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L26)):*
> ```Java
> public class ExecutionDataResponseDTO {
>   @Schema(description = "the plan ExecutionID") String executionId;
>   @Schema(description = "Execution Yaml for the given ExecutionID") String executionYaml;
> ```

Can we add in description whether is templates, inputset resolved or not?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RTHHM6ftAqre6TyQ0:-N4RTHHM6ftAqre6TyQ1:b-qcun5o) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L406)):*
> ```Java
> 
>     if (!planExecutionMetadata.isPresent()) {
>       log.error(String.format("Execution with id [%s] is not present or deleted", planExecutionId));
> ```

No need to log, will get automaticall get logged as part of exception

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RRvPQ443--V8BrgjC:-N4RTSfL-mF69jrBmnae:bqmbaqw) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
<details><summary><i>Previously, naidu-harness (Sanyasi Naidu Annepu) wrote…</i></summary><blockquote>

/{planExecutionId}/metadata
or
i would prefer /{planExecutionId}/executedYaml
</blockquote></details>

we may extend this API for other metadata, so `/{planExecutionId}/metadata` looks better to me

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RRvPQ443--V8BrgjC:-N4RWKl76iPHGs9PBg-r:b32v57) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

we may extend this API for other metadata, so `/{planExecutionId}/metadata` looks better to me
</blockquote></details>

+1
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RWWUr19oArEPr5_fC:-N4RWWUr19oArEPr5_fD:bau2ite) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L25)):*
> ```Java
> @Schema(name = "ExecutionDataResponse", description = "This contains Execution metadata details.")
> public class ExecutionDataResponseDTO {
>   @Schema(description = "the plan ExecutionID") String executionId;
> ```

nit: T capital



_Code quote:_
```Java
the
```

**Review by smjt-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 1 file(s) to review. 2 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSelP6XPTdIFUa5R0:-N4Rg_yc-9k8U480HBrA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

M capital
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RRvPQ443--V8BrgjC:-N4Rgfs49spu5vLxe8Gm:b-2dmzsx) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

kept it like pipelines/execution/getMetadata
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 281 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSO7TDoVioGczQANj:-N4Rglyb5Ck5a3E2yh9t:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L281)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

of a pipeilne execution*
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 290 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSh_rD_dxerc16M8W:-N4RgmZiBNgCXdLm-yH5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L290)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

ExecutionId -> no need of saying 'planExecutionId'
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSryPEgh5DcrSNz0p:-N4RgnvXCYyu4MDWlpq9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L26)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Can we add in description whether is templates, inputset resolved or not?
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RTHHM6ftAqre6TyQ0:-N4Rgok94jmXu_kbjOkq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L406)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

No need to log, will get automaticall get logged as part of exception
</blockquote></details>

Done.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSryPEgh5DcrSNz0p:-N4RnLCZ5WMtoa64hRdJ:b3rj6rg) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L26)):*
<details><summary><i>Previously, smjt-h wrote…</i></summary><blockquote>

Done.
</blockquote></details>

templates also resolved, right?

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RRvPQ443--V8BrgjC:-N4RnZJo6zFlrbzHWjHC:bxg0xb5) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
<details><summary><i>Previously, smjt-h wrote…</i></summary><blockquote>

kept it like pipelines/execution/getMetadata
</blockquote></details>

Don't see the change. ExecutionId should come first

**Review by smjt-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 278 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RRvPQ443--V8BrgjC:-N4SVWq2Bh892z4X6wTA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L278)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Don't see the change. ExecutionId should come first
</blockquote></details>

Done.

**Review by smjt-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSryPEgh5DcrSNz0p:-N4Vv2RcBPl8Eretillc:b-lit0ta) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L26)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

templates also resolved, right?
</blockquote></details>

Yes templates also resolved.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251#-:-N4Wt3Sw2LxeTETcZv4p:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: :shipit: complete! ✓

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSryPEgh5DcrSNz0p:-N4X3NXXDYO5H--BFIdO:brl6w9i) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L26)):*
<details><summary><i>Previously, smjt-h wrote…</i></summary><blockquote>

Yes templates also resolved.
</blockquote></details>

We can keep in description. Something like "Execution YAML - Runtime values are merged on input Pipeline and templates are expanded." or something similar so everyone understands

**Review by smjt-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34251#-N4RSryPEgh5DcrSNz0p:-N4cQwxU7MolRFXZ2dXq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad256a0e316372cb49cf57d566a4405c4f50ee1/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java#L26)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

We can keep in description. Something like "Execution YAML - Runtime values are merged on input Pipeline and templates are expanded." or something similar so everyone understands
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34251)* status: :shipit: complete! ✓

**Pull request merged**
