### PR TITLE
feat: [PL-27456]: Rename the target to be module and make run analysis per module

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes
* Rename the targets to "module" instead of the package name. This helps with various pre-configured checks.
* Added run_analysis_per_module function

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36488)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36488)

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36488)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36488)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kXpAXB5czp_MmEbmg:-N9kXpAXB5czp_MmEbmh:b-tvrq4d) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L19)):*
> ```Java
> 
> public class BuildFile {
>   private Set<LoadStatement> loadStatementSet = new TreeSet<>();
> ```

Not part of this PR, but LoadStatement doesn't implement equals/hashcode. You should implement those if you want to store it in a Set/Map otherwise it can lead to hard to catch bugs and weird edge cases. Use lombok for that. For comparable, don't use toString(), that's always a bad idea as you can change it easily for different reasons (e.g. adding lombok annotation). Instead implement a separate method that converts object to string for comparison. 
On this line your interface should be a SortedSet<> not Set<> as this is an important property of your loadStatements. 
Finally, never append structure names in the field/variable name, there is no point to that in Java, from the type we can see it's a Set/List. Just call them loadStatements (plural), javaBinaries etc...
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kWgOE9NbY6-W0YFCT:-N9kWgOE9NbY6-W0YFCU:biiyffh) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L22)):*
> ```Java
>   private List<JavaLibrary> javaLibraryList = new ArrayList<>();
>   private List<JavaBinary> javaBinaryList = new ArrayList<>();
>   boolean runAnalysisPerModule = true;
> ```

You should always try to make classes as immutable as possible. Put final keyword on all field to make them reference immutable. Also, make this one private



_Code quote:_
```Java
  private Set<LoadStatement> loadStatementSet = new TreeSet<>();
  private List<JavaLibrary> javaLibraryList = new ArrayList<>();
  private List<JavaBinary> javaBinaryList = new ArrayList<>();
  boolean runAnalysisPerModule = true;
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kZPV5BzLiVOFIaNhQ:-N9kZPV5BzLiVOFIaNhR:bikf4a4) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L35)):*
> ```Java
>   public void enableAnalysisPerModule() {
>     loadStatementSet.add(new LoadStatement("//:tools/bazel/macros.bzl", "run_analysis_per_module"));
>     runAnalysisPerModule = false;
> ```

Is this intentionally false or should it be set to true?

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36488)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kXpAXB5czp_MmEbmg:-N9lNK4F6zwWdglUWVh9:bvi0f3v) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L19)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Not part of this PR, but LoadStatement doesn't implement equals/hashcode. You should implement those if you want to store it in a Set/Map otherwise it can lead to hard to catch bugs and weird edge cases. Use lombok for that. For comparable, don't use toString(), that's always a bad idea as you can change it easily for different reasons (e.g. adding lombok annotation). Instead implement a separate method that converts object to string for comparison. 
On this line your interface should be a SortedSet<> not Set<> as this is an important property of your loadStatements. 
Finally, never append structure names in the field/variable name, there is no point to that in Java, from the type we can see it's a Set/List. Just call them loadStatements (plural), javaBinaries etc...
</blockquote></details>

Will look into lombok. Otherwise, idea of toString was not for comparison, but to just serialize into file. Updated rest of it
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kWgOE9NbY6-W0YFCT:-N9lM9Aw1FeaPyGvOXMa:b-d57xt3) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L22)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You should always try to make classes as immutable as possible. Put final keyword on all field to make them reference immutable. Also, make this one private
</blockquote></details>

agreed, have not done it consistently across files; update neighboring files too.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kZPV5BzLiVOFIaNhQ:-N9lNDrI-PoiCZd4yPnQ:buxoqip) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L35)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Is this intentionally false or should it be set to true?
</blockquote></details>

this should be true, was trying out something and forgot to change back, thanks!

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36488)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/36488#-N9kXpAXB5czp_MmEbmg:-N9l_3Jw06bqDTEdaU3b:b-f1zyv6) ([raw file](https://github.com/harness/harness-core/blob/844b72cb592d3b9fd33b4e84e6c6f0a254170e2a/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L19)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Will look into lombok. Otherwise, idea of toString was not for comparison, but to just serialize into file. Updated rest of it
</blockquote></details>

So, this is the problematic code I'm referring to (from LoadStatement.java). Changing toString for whatever reason (e.g. adding a field, changing the custom toString() method, adding some of the lombok annotations etc..) will break the comparison of items. Anyway we can do that separately, just keep it in mind. 
```
  @Override
  public int compareTo(Object o) {
    return o.toString().compareTo(toString());
  }
```

**Pull request merged**
