### PR TITLE
fix: [PL-24129]: add validation on username and sanitize userName for mails

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
validation has been added on userName to disallow these characters - ` : `,` / `, `<` ,` > `, `=` , `(`, `)`
sanitize already saved wrong userName while sending to email templates to escape dynamic values. 

Testing -
1. validation on username has name has been tested by updating userName with img link, it throws this error
Screenshot 2023-05-09 at 7 07 50 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger feature-build

**Review by shashank-harness — APPROVED** [review]
> Reviewed 10 of 15 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)* status: Some of the checks are too old. 23 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Comment by pbarapatre10** [comment]
*[`125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/47571#-NVZt47q6JDCrYczqgA1:-NVZt47q6JDCrYczqgA2:b-mhqhmw) ([raw file](https://github.com/harness/harness-core/blob/3da233115f861d1565f0878a43205e5414311cca/125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java#L119)):*
> ```Java
>     if (freezeEventType.equals(FreezeEventType.DEPLOYMENT_REJECTED_DUE_TO_FREEZE) && ambiance != null) {
>       data.put("USER_NAME",
>           userNameSanitizer.sanitizeInput(ambiance.getMetadata().getTriggerInfo().getTriggeredBy().getIdentifier()));
> ```

Minor what happens when this value is null? 



_Code quote:_
```Java
ambiance.getMetadata().getTriggerInfo().getTriggeredBy().getIdentifier()))
```

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 10 of 15 files at r1, 10 of 10 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)* status: Some of the checks are too old. Waiting on team(s): del-team.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)* status: 6 file(s) to review. Waiting on team(s): del-team. 

___
*[`125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java` line 119 at r4](https://reviewable.io/reviews/harness/harness-core/47571#-NVZt47q6JDCrYczqgA1:-NVd3kmn2gIyN8EtArcm:bva02v8) ([raw file](https://github.com/harness/harness-core/blob/3da233115f861d1565f0878a43205e5414311cca/125-freeze/src/main/java/io/harness/freeze/notifications/NotificationHelper.java#L119)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

please take care of this in next PR
</blockquote></details>

This has been written like this only, it should be working as its present from years.

**Comment by bhavya181** [comment]
trigger ss

**Comment by bhavya181** [comment]
trigger codeformat

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)* status: 7 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)* status: 7 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger uts

**Review by piyush-harness — APPROVED** [review]
> Reviewed 9 of 15 files at r1, 8 of 10 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 5 of 6 files at r5, 2 of 2 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47571)* status: 8 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Comment by bhavya181** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Review by gn-harness — APPROVED** [review]

**Comment by bhavya181** [comment]
trigger messagecheck

**Pull request merged**
