### PR TITLE
fix: [CDS-80121]: fix method invocation in concatenated expressions

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** When a concatenated expression with two expressions in it is evaluated with method invocation in the latter expression, it fails.
Eg: <+pipeline.name> <+<+pipeline.sequenceId>.toString()>

**Changes:** Fixed the method to determine method invocation in a concatenated expression.

**Testing:** Tested locally the above expression and it is working now. Also, we added logs for the above change in prod 1 and 2 analyzed them for a week, and found that this change should not be breaking for any customer.

We do have a pipeline of NAB's added in automation that was failing with our change but it's not running in prod anymore by the customer. So, we have added in the documentation what changes need to be done to the customer's pipeline for expressions to correctly work and also updated automation. 

All the findings from logs are noted in this doc: https://harness.atlassian.net/wiki/spaces/CDNG/pages/21538996790/Expressions+with+Method+Invocation

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54942)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54942)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 939 at r1](https://reviewable.io/reviews/harness/harness-core/54942#-NiIzuep2C6jVcaJqMP8:-NiIzuep2C6jVcaJqMP9:bspxrif) ([raw file](https://github.com/harness/harness-core/blob/80b6b13033c806aed99704510239b6bb814df4e8/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L939)):*
> ```Java
>   CDS_K8S_TRAFFIC_ROUTING_NG(
>       "Providing Traffic Routing functionality for K8s - BG, Canary and TrafficRouting steps", HarnessTeam.CDP),
>   PIE_METHOD_INVOCATION_WITH_OLD_PATTERN("FF to support method invocation in expression", PIPELINE);
> ```

CDS_METHOD_INVOCATION_OLD_FLOW_EXPRESSION_ENGINE
Support new edgecases of method invocation in expression engine

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54942)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/54942#-NiJ-sP73sxEWNn6jULz:-NiJ-sP73sxEWNn6jUM-:bn0eykp) ([raw file](https://github.com/harness/harness-core/blob/80b6b13033c806aed99704510239b6bb814df4e8/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L260)):*
> ```Java
>   private boolean checkIfValueHasMethodInvocationWithTwoPatterns(StringBuffer buf, int expressionEndPos) {
>     // Right substring
>     CharSequence charSequence = buf.subSequence(expressionEndPos, buf.length());
> ```

as discussed offline, could be simplified

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54942)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 939 at r1](https://reviewable.io/reviews/harness/harness-core/54942#-NiIzuep2C6jVcaJqMP8:-NiJCKQ80hLx-DJJa6lo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80b6b13033c806aed99704510239b6bb814df4e8/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L939)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

CDS_METHOD_INVOCATION_OLD_FLOW_EXPRESSION_ENGINE
Support new edgecases of method invocation in expression engine
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/54942#-NiJ-sP73sxEWNn6jULz:-NiJGoPF533V9v6JRjx4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/80b6b13033c806aed99704510239b6bb814df4e8/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L260)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed offline, could be simplified
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger smartchecks

**Comment by shalini-agr** [comment]
trigger commonchecks

**Comment by shalini-agr** [comment]
trigger commonchecks

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54942)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54942)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
