### PR TITLE
fix: [CI-3747]: Enforce minimum 5 minutes interval in cron trigger

### PR DESCRIPTION
**Pull request by raghavharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32470)

### CODE REVIEW

**Comment by raghavharness** [comment]
trigger messagecheck

**Comment by harshjain12** [comment]
@raghavharness It will require UI change too

**Comment by raghavharness** [comment]
@harshjain12 What UI changes are required for this ? I was thinking if we can add some tooltip to show this 5 min thing to the user but then it can go independently right ? Or are we looking to enforce 5 min on UI itself ?

**Comment by harshjain12** [comment]
Enforcement on UI

**Comment by harshjain12** [comment]
Try creating one schedule trigger via UI

**Comment by raghavharness** [comment]
yeah did that already, in custom expression we can pass any value so I assume we need to add enforcement there.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/32470)

**Pull request closed without merging**
