### PR TITLE
[feat]: [PL-25591]: Adds implementation for organization resource using spec f…

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
…irst

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36522)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36522)

**Comment by ashishsanodia-harness** [comment]
trigger ti0

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by ashishsanodia-harness** [comment]
trigger ti2

**Comment by ashishsanodia-harness** [comment]
trigger ti0

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by ashishsanodia-harness** [comment]
trigger ti4

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36522)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36522)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationApiImpl.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/36522#-NAJhbKCDcHcVca3vLom:-NAJhbKCDcHcVca3vLon:bnt1y8v) ([raw file](https://github.com/harness/harness-core/blob/1c80667eaf17d51d35aa895baaf1ea25c5a671b9/120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationApiImpl.java#L125)):*
> ```Java
> 
>     if (!deleted) {
>       throw new NotFoundException(String.format("Organization with identifier [%s] not found", id));
> ```

Should this be some other exception and not NotFoundException?

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36522)* status: :shipit: complete! ✓

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationApiImpl.java` line 125 at r4](https://reviewable.io/reviews/harness/harness-core/36522#-NAJhbKCDcHcVca3vLom:-NANseXc0kCe0Xx0bmFN:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1c80667eaf17d51d35aa895baaf1ea25c5a671b9/120-ng-manager/src/main/java/io/harness/ng/core/remote/OrganizationApiImpl.java#L125)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should this be some other exception and not NotFoundException?
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
trigger codeformat

**Comment by ashishsanodia-harness** [comment]
trigger ti3

**Comment by ashishsanodia-harness** [comment]
trigger ti4

**Comment by ashishsanodia-harness** [comment]
trigger ti0

**Comment by ashishsanodia-harness** [comment]
trigger ti2

**Comment by ashishsanodia-harness** [comment]
trigger ti4

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36522)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36522)* status: :shipit: complete! ✓

**Pull request merged**
