### PR TITLE
[feat]: [CDP-20220]: GA: Kustomize Patches in NG

### PR DESCRIPTION
**Pull request by namantalaycha10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 48 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: 48 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: 53 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 47 of 48 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
Regarding Delegate team review:
No new  TaskType is added as well as no changes are made around already present TaskTypes

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 47 of 48 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 46 of 48 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30354)* status: :shipit: complete! ✓

**Pull request merged**
