### PR TITLE
[fix]: [PL-30070]: Changed Account Permission HIDE_NEXTGEN_BUTTON to be disabled for Default account admin user group.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Changed Account Permission HIDE_NEXTGEN_BUTTON to be disabled for Default account admin user group.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40762)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger smartchecks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java` line 1971 at r1](https://reviewable.io/reviews/harness/harness-core/40762#-NHzdrTA9t0mQiVs3Mm3:-NHzdrTA9t0mQiVs3Mm4:bqgl47e) ([raw file](https://github.com/harness/harness-core/blob/22ff5005e2422a710f39cb65f01a7cf536514897/400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java#L1971)):*
> ```Java
>     return allAccountPermissions.stream()
>         .filter(permission -> !disabledPermissions.contains(permission))
>         .collect(Collectors.toSet());
> ```

nit : I think its equivalent to Sets.difference (allAccountPerm , disableAccountPerm) ? Thanks



_Code quote:_
```Java
    return allAccountPermissions.stream()
        .filter(permission -> !disabledPermissions.contains(permission))
        .collect(Collectors.toSet());
```

**Comment by Jimit09Gandhi** [comment]
trigger smartchecks

**Review by reetika04 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40762)* status: :shipit: complete! ✓

**Comment by Jimit09Gandhi** [comment]
trigger ti0

**Comment by Jimit09Gandhi** [comment]
trigger ti2

**Comment by Jimit09Gandhi** [comment]
trigger ti3

**Comment by Jimit09Gandhi** [comment]
trigger ti2

**Comment by Jimit09Gandhi** [comment]
trigger ti3

**Pull request merged**
