### PR TITLE
[fix]: [CDS-40938]: removing hint from mongo

### PR DESCRIPTION
**Pull request by lasdox**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35839)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1349 at r2](https://reviewable.io/reviews/harness/harness-core/35839#-N8NnGhzDLL6BGwYI0jC:-N8NnGhzDLL6BGwYI0jD:b-xybund) ([raw file](https://github.com/harness/harness-core/blob/79804a94e2edccea1a1897f5d47408749f393a49/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1349)):*
> ```Java
>     if (featureFlagService.isNotGlobalEnabled(REMOVE_HINT_YAML_GIT_COMMITS)) {
>       findOptions.modifier("$hint", "gitCommitAccountIdStatusYgcLastUpdatedIdx");
>     }
> ```

We should have per account check, isn't it?

**Comment by lasdox** [comment]
> _[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1349 at r2](https://reviewable.io/reviews/harness/harness-core/35839#-N8NnGhzDLL6BGwYI0jC:-N8NnGhzDLL6BGwYI0jD:b-xybund) ([raw file](https://github.com/harness/harness-core/blob/79804a94e2edccea1a1897f5d47408749f393a49/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1349)):_
> 
> > ```java
> >     if (featureFlagService.isNotGlobalEnabled(REMOVE_HINT_YAML_GIT_COMMITS)) {
> >       findOptions.modifier("$hint", "gitCommitAccountIdStatusYgcLastUpdatedIdx");
> >     }
> > ```
> 
> We should have per account check, isn't it?

Do you think it is better? I can change it.
I was thinking in making a bigger test to see how it performs with other customers.

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35839)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1349 at r2](https://reviewable.io/reviews/harness/harness-core/35839#-N8NnGhzDLL6BGwYI0jC:-N8P-53S7VgeyFmsYgcJ:bneb9fs) ([raw file](https://github.com/harness/harness-core/blob/79804a94e2edccea1a1897f5d47408749f393a49/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1349)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

Do you think it is better? I can change it.
I was thinking in making a bigger test to see how it performs with other customers.
@abhinav-harness 

</blockquote></details>

we should reduce blast radius. We can always enable it for more customers or enable in whole cluster at once.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35839)

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35839)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35839)* status: :shipit: complete! ✓

**Pull request merged**
