### PR TITLE
feat: [CDS-78527]: Static Schema support for V1 Pipelines

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added Support for V1 Pipeline static schema in Individual Schema Open API , Created separate folders for v0 and v1 inside static-schema folder

Tests Done -
* Get Pipeline V0 Static Schema
* Get Pipeline V1 Static Schema
* Get Trigger V0 Static Schema
* Get Individual Schema from V0 Pipeline Static Schema
* Try Fetching Invalid version Pipeline Schema

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52350)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52350)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/release/release-branch.sh` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/52350#-NdFiIXPAXHTs_d15Bfy:-NdFiIXPAXHTs_d15Bfz:b-svekco) ([raw file](https://github.com/harness/harness-core/blob/d205823042f1c84702a2ab96f39ba8489b06ce5b/pipeline-service/release/release-branch.sh#L164)):*
> ```Shell
> 
>     # Updating static-schema for pipeline.json
>     PIPELINE_JSON="pipeline-service/service/src/main/resources/static-schema/v0/pipeline.json"
> ```

Wouldn't updating the path directly here impact the schema fetch?

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/release/release-branch.sh` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/52350#-NdFiIXPAXHTs_d15Bfy:-NdFkT6KBpnVll5ixX-F:b2o3lg6) ([raw file](https://github.com/harness/harness-core/blob/d205823042f1c84702a2ab96f39ba8489b06ce5b/pipeline-service/release/release-branch.sh#L164)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Wouldn't updating the path directly here impact the schema fetch?
</blockquote></details>

Got it.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52350)* status: Some of the checks are too old. 11 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52350)* status: Some of the checks are too old.

**Review by mankrit-singh — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
