### PR TITLE
[feat]: [CDS-75304]: List Repo and List branch api with pagination added

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added new paginated apis for listing branches and repos. Have tested out both the apis with different page params.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/PaginationDetails.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2UvcCY8nVoyGDKR-:-NaL2UvcCY8nVoyGDKR0:b-11wx9h) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/PaginationDetails.java#L24)):*
> ```Java
> public class PaginationDetails {
>   int next;
>   String nextPageUrl;
> ```

nit: for page number, the field name is "next". For next page url, the field name is "nextPageUrl". Don't you think naming should've been more synonymous in nature?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/PaginationDetails.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2UvcCY8nVoyGDKR-:-NaL2gM83vtnDdw0mstp:b-hge7cg) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/PaginationDetails.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: for page number, the field name is "next". For next page url, the field name is "nextPageUrl". Don't you think naming should've been more synonymous in nature?
</blockquote></details>

I think it may also contain "pageSize" as response. Not sure exactly, but if request asks for page of 100, but we deliver only 30 results, so we should probably mention that also. Something to think about.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2t6xCQH7RnCIM2at:-NaL2t6xCQH7RnCIM2au:brcxdof) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L213)):*
> ```Java
> 
>   @Override
>   public GitListRepositoryResponse listReposWithPagination(String accountIdentifier, String orgIdentifier,
> ```

Lets simply name it "listReposV2" or something.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL35Z92fRD-IaUIEDq:-NaL35Z92fRD-IaUIEDr:bbc8vh0) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L215)):*
> ```Java
>   public GitListRepositoryResponse listReposWithPagination(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String connectorRef, PageRequest pageRequest, RepoFilterParameters repoFilterParameters,
>       boolean applyGitXRepoAllowListFilter) {
> ```

I'm wondering if we should add "applyGitXRepoAllowListFilter" argument inside repoFilterParams itself coz actually thats simply a filter that needs to be applied.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3Xxv1wFEwdIkM4P3:-NaL3Xxv1wFEwdIkM4P4:b-ye4cgb) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L304)):*
> ```Java
> 
>   @Override
>   public GitListBranchesResponse listBranchesWithPagination(String accountIdentifier, String orgIdentifier,
> ```

same thing with naming here

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 900 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3g5y6FVwZGYCCPxm:-NaL3g5y6FVwZGYCCPxn:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L900)):*
> ```Java
>           .collect(Collectors.toList());
>     }
>   }
> ```

line spacing missing

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 901 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3n220tU0cZ7vNBlR:-NaL3n220tU0cZ7vNBlS:b-ibbmad) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L901)):*
> ```Java
>     }
>   }
>   private GitListRepositoryResponse prepareListRepoV2Response(
> ```

This method looks to be copy of already existing method for V1 API. Also, the logic would remain same I guess for both. So, we should think on how to merge them both instead of duplicating it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3yAG65z6fs8-JAMk:-NaL3yAG65z6fs8-JAMl:bbf2qpb) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L382)):*
> ```Java
> 
>   @GET
>   @Path("list-repos-by-connector-v2")
> ```

path should be simply : /v2/<older-api-path>

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL49s6CoKUiRE4qAz7:-NaL49s6CoKUiRE4qAz8:bvh26aa) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L410)):*
> ```Java
>       @Parameter(description = GitSyncApiConstants.APPLY_GITX_REPO_ALLOW_LIST_FILTER_PARAM_MESSAGE)
>       @QueryParam(NGCommonEntityConstants.APPLY_GITX_REPO_ALLOW_LIST_FILTER) @DefaultValue("false")
>       boolean applyGitXRepoAllowListFilter, @BeanParam ScmRepoFilterParams scmRepoFilterParams) {
> ```

here also we can combine gitXRepoAllowListFilter with repoFilterParams.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 421 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL4IKP1tC4vw4YOHTo:-NaL4IKP1tC4vw4YOHTp:b6f3t54) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L421)):*
> ```Java
>     }
>     return ResponseDTO.newResponse(scmFacilitatorService.listReposWithPagination(accountIdentifier, orgIdentifier,
>         projectIdentifier, connectorRef, PageRequest.builder().pageIndex(pageNum).pageSize(pageSize).build(),
> ```

idk if there's some validation at some level about page number not being -ve. If not, then lets add it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 491 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL4S23-wzl62VZR34m:-NaL4S23-wzl62VZR34n:bjquptk) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L491)):*
> ```Java
> 
>   @GET
>   @Path("list-branches-v2")
> ```

same as before

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: 10 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/PaginationDetails.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2UvcCY8nVoyGDKR-:-NaL6HkX4PH7XOzJJIFu:b-7u0us) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/PaginationDetails.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think it may also contain "pageSize" as response. Not sure exactly, but if request asks for page of 100, but we deliver only 30 results, so we should probably mention that also. Something to think about.
</blockquote></details>

we dont have page size in the response, we have only next and next_u
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2t6xCQH7RnCIM2at:-NaL7Fsj5elQnpXhHTBv:bhcsn7w) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L213)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets simply name it "listReposV2" or something.
</blockquote></details>

Done.
Had named it listReposWithPagination and listBranchesWithPagination because there was already a listBranchesV2 and i felt listBranchesV3 was absurd 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL35Z92fRD-IaUIEDq:-NaL7B607rd-oduHSP8F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L215)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm wondering if we should add "applyGitXRepoAllowListFilter" argument inside repoFilterParams itself coz actually thats simply a filter that needs to be applied.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 304 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3Xxv1wFEwdIkM4P3:-NaL7CueBzal8tWKnCfq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L304)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same thing with naming here
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 900 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3g5y6FVwZGYCCPxm:-NaL9-GtBoOoFEKgr6RK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L900)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 901 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3n220tU0cZ7vNBlR:-NaL86Ao1YzjGhR5KoEC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L901)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This method looks to be copy of already existing method for V1 API. Also, the logic would remain same I guess for both. So, we should think on how to merge them both instead of duplicating it.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3yAG65z6fs8-JAMk:-NaL8-uh42KG0KzS6kFZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L382)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

path should be simply : /v2/<older-api-path>
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL49s6CoKUiRE4qAz7:-NaL8Hw8-rEfLrLEkgLN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L410)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

here also we can combine gitXRepoAllowListFilter with repoFilterParams.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 421 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL4IKP1tC4vw4YOHTo:-NaLBIvY--ECdokhtQ6u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L421)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

idk if there's some validation at some level about page number not being -ve. If not, then lets add it.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 491 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL4S23-wzl62VZR34m:-NaL8Wqq2Z74LZFGpSXr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L491)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done.

**Review by senjucanon2 — DISMISSED** [review]
> Reviewed 5 of 10 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: 12 file(s) to review. 1 change requests. 10. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2t6xCQH7RnCIM2at:-NaMCDxBAbd4X2s0MKkX:bh14g7y) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L213)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
Had named it listReposWithPagination and listBranchesWithPagination because there was already a listBranchesV2 and i felt listBranchesV3 was absurd 
</blockquote></details>

Lets make it simpler itself : listResposV2 should be good I suppose

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1363 at r2](https://reviewable.io/reviews/harness/harness-core/51047#-NaMCUuN2YDQkHQqbeXe:-NaMCUuN2YDQkHQqbeXf:bo3hyad) ([raw file](https://github.com/harness/harness-core/blob/404d9ebcbc6bc81206d287360341ed5872ca5548/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1363)):*
> ```Java
>     }
>     if (pageRequest.getPageSize() < 0 || pageRequest.getPageIndex() < 0) {
>       throw new InvalidRequestException("Invalid pagination request params passed.");
> ```

we should also mention whats invalid here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1363 at r2](https://reviewable.io/reviews/harness/harness-core/51047#-NaMCUuN2YDQkHQqbeXe:-NaMCZj3BMqVq1CHyS0S:b-km9r9u) ([raw file](https://github.com/harness/harness-core/blob/404d9ebcbc6bc81206d287360341ed5872ca5548/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1363)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should also mention whats invalid here.
</blockquote></details>

page size = 0 is also invalid

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3yAG65z6fs8-JAMk:-NaMCgbn-RIt58b9vlRC:b-njucpz) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L382)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

should we simplify the path here : "v2/list-repos" ? I think "by-connector" sort of becomes irrelevant for now. We have already done same for "list-branches"

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL2t6xCQH7RnCIM2at:-NaQFc3jAgOPqvJ8QPzt:b-5g9o7c) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L213)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets make it simpler itself : listResposV2 should be good I suppose
</blockquote></details>

yes, done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1363 at r2](https://reviewable.io/reviews/harness/harness-core/51047#-NaMCUuN2YDQkHQqbeXe:-NaQG-p28nlOjs3lUvks:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/404d9ebcbc6bc81206d287360341ed5872ca5548/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1363)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

page size = 0 is also invalid
</blockquote></details>

done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/51047#-NaL3yAG65z6fs8-JAMk:-NaQFQRN30pUVVYCPGOS:bfwnz8m) ([raw file](https://github.com/harness/harness-core/blob/c34c295657d0a32bdb078ebb99dc7d09bfd486b1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L382)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should we simplify the path here : "v2/list-repos" ? I think "by-connector" sort of becomes irrelevant for now. We have already done same for "list-branches"
</blockquote></details>

yes, better

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 3 of 7 files at r2, 2 of 4 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51047)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
