### PR TITLE
[feat]: [CDS-68228]: Added CacheResponse in Exceptions

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47218)

### CODE REVIEW

**Review by shalini-agr — APPROVED** [review]

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 481 at r2](https://reviewable.io/reviews/harness/harness-core/47218#-NURCeLd4flabZj_dXxp:-NURCeLd4flabZj_dXxq:b-px66o9) ([raw file](https://github.com/harness/harness-core/blob/acc14591a38c97921749ee83d1347519034be2b3/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L481)):*
> ```Java
>           .build();
>     }
>     return null;
> ```



When this code already exists, then why are we writing line by line again. Please start thinking what can be the side effects of such coding:
1) If we add a new field to cache response, now that needs to be added at multiple places
2) If we change the way we fetch cache response, this needs to be done at multiple places
etc etc.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47218)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 481 at r2](https://reviewable.io/reviews/harness/harness-core/47218#-NURCeLd4flabZj_dXxp:-NURuWlg5P4J2Od628Be:bph7twj) ([raw file](https://github.com/harness/harness-core/blob/acc14591a38c97921749ee83d1347519034be2b3/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L481)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>



When this code already exists, then why are we writing line by line again. Please start thinking what can be the side effects of such coding:
1) If we add a new field to cache response, now that needs to be added at multiple places
2) If we change the way we fetch cache response, this needs to be done at multiple places
etc etc.
</blockquote></details>

I have used a single method now and have reduced the duplicate code.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/47218#-NUSIvL8718SQOTi4TO2:-NUSIvL8718SQOTi4TO3:bvketzg) ([raw file](https://github.com/harness/harness-core/blob/f6cc7cdf5f867d4657a765dd504c81353be66651/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L87)):*
> ```Java
> 
>   public CacheResponseMetadataDTO getCacheResponse(PipelineEntity pipelineEntity) {
>     if (pipelineEntity.getStoreType() != StoreType.REMOTE) {
> ```

whats the need to change the condition here? can't we simply use the method without changing anything else?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47218)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/47218#-NUSIvL8718SQOTi4TO2:-NUUtihGDuV-N4YIvqXZ:by167qf) ([raw file](https://github.com/harness/harness-core/blob/f6cc7cdf5f867d4657a765dd504c81353be66651/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L87)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the need to change the condition here? can't we simply use the method without changing anything else?
</blockquote></details>

Reverted to previous code here

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47218)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger ut0, ut1 , ut2, ut3, ut4, ut5, ut6, ut8, ut9

**Comment by senjucanon2** [comment]
trigger ut7

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47218)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
