### PR TITLE
fix: [CDS-74864]: use socket capability based on FF for container step

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
use socket capability based on FF for container step. This is done for container init and clean up tasks. 
Capability building is done by pipeline-service so no need for delegate side changes. Tested with an older delegate to verify this. 
Tested that capability is going through with mock node server

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51120)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Comment by hingerabhinav** [comment]
trigger messagecheck, review

**Comment by sahilhindwani-harness** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf62ZkEAwH0masHJpG:-Naf62ZkEAwH0masHJpH:bns5sno) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java#L37)):*
> ```Java
>   @Expression(ALLOW_SECRETS) @NotNull private String namespace;
>   @Builder.Default private static final CICleanupTaskParams.Type type = Type.GCP_K8;
>   private boolean useSocketCapability;
> ```

Use boxed boolean

**Comment by sahilhindwani-harness** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8InitializeTaskParams.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf69mrAfJ_TEtVkwCO:-Naf69mrAfJ_TEtVkwCP:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8InitializeTaskParams.java#L43)):*
> ```Java
>   private int podMaxWaitUntilReadySecs; // Max time for pod to reach running state after its creation in seconds
>   @Builder.Default private static final Type type = Type.GCP_K8;
>   private boolean useSocketCapability;
> ```

Same as above

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf6D63CYI8UggYRRai:-Naf6D63CYI8UggYRRaj:b-f23xh1) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java#L151)):*
> ```Java
>     String connectorRef = infrastructure.getSpec().getConnectorRef().getValue();
> 
>     boolean useSocketCapability = pmsFeatureFlagService.isEnabled(
> ```

Is this change already done for CI?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51120)* status: Some of the checks are too old. 4 file(s) to review.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51120)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf62ZkEAwH0masHJpG:-NafFoAW6RZUEgt-1KJQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java#L37)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use boxed boolean
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8InitializeTaskParams.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf69mrAfJ_TEtVkwCO:-NafFozo9CzZMIToE9TR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8InitializeTaskParams.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf6D63CYI8UggYRRai:-NafFqRu5YDmNPSyioNp:bq9i2dd) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ContainerStepInitHelper.java#L151)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Is this change already done for CI?
</blockquote></details>

This is done for both container step and InitContainerStepV2 since they use the same helper

**Comment by hingerabhinav** [comment]
trigger uts

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51120)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf62ZkEAwH0masHJpG:-Nah3qhN4gGsK5gskJNR:bjux0i7) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java#L37)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@sahilhindwani-harness , isn't it better to use primitive boolean ? the default value on the delegate task is going to be false

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51120)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
> _[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/51120#-Naf62ZkEAwH0masHJpG:-Nah3qhN4gGsK5gskJNR:bjux0i7) ([raw file](https://github.com/harness/harness-core/blob/7c22e4d7d3ffe056659a276747164efa20e3a70b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s/CIK8CleanupTaskParams.java#L37)):_
> 
> Previously, hingerabhinav (Abhinav Hinger) wrote…
> @sahilhindwani-harness , isn't it better to use primitive boolean ? the default value on the delegate task is going to be false

@yogesh-chauhan We discussed and there may be issues in del-manager communication with java serialiser when new fields are being added

**Comment by hingerabhinav** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51120)* status: 3. unresolved discussions.

**Comment by hingerabhinav** [comment]
trigger review

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
