### PR TITLE
[fix]: [CDS-35585]: updated aws-java-sdk to 1.12.220

### PR DESCRIPTION
**Pull request by vaibhav-harness**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33469)

### CODE REVIEW

**Comment by vaibhav-harness** [comment]
trigger ti4

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33469)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33469#-:-N2uR8Xx-hV0J7VN3tj0:bnfp4nl)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33469)* status: :shipit: complete! ✓

**Pull request merged**
