### PR TITLE
feat: [PIE-4046]: added stages types to telemetry

### PR DESCRIPTION
**Pull request by vaibhav-si**
This PR is made to better visualize the usage of stage types like `custom` by our customers.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36064)

**Comment by vaibhav-si** [comment]
trigger messagecheck

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)* status: Some of the checks are too old. 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)* status: Some of the checks are too old. 1 file(s) to review.

**Review by sribalij — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064#-:-N9-nFWn7unLwVzUOZT6:bnfp4nl)* status: Some of the checks are too old. 1 file(s) to review.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/instrumentaion/PipelineInstrumentationUtils.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/36064#-N90Ajk9EQ0F0RT1ccJN:-N90Ajk9EQ0F0RT1ccJO:b-mjjj9g) ([raw file](https://github.com/harness/harness-core/blob/276f203d55f844b05cc3d086d0a4d53278c15f84/pipeline-service/service/src/main/java/io/harness/pms/instrumentaion/PipelineInstrumentationUtils.java#L92)):*
> ```Java
>       List<String> res = new ArrayList<>();
>       if (stagesJsonNode.isArray()) {
>         for (JsonNode stageNode : stagesJsonNode) {
> ```

We should handle parallel stages as well.

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)* status: Some of the checks are too old.

**Comment by vaibhav-si** [comment]
trigger ti0

**Comment by vaibhav-si** [comment]
trigger ti4

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36064)* status: :shipit: complete! ✓

**Pull request merged**
