### PR TITLE
feat: [PL-25260]: changed scm errors and status codes

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Changed scm error status codes to maintain consistency, we will be sending out -

1. git svc will send 400 in case scm sends 404, 422, 400
2. git svc will send 409 in case scm sends 409 conflict error.
3. git svc will send 401 in case scm sends 401, 403.
4. git svc will send 500 in case scm sends any unexpected error.

I've tested it on local.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)

### CODE REVIEW

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)* status: 31 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmErrorCodeToHttpStatusCodeMapping.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEHeI8qp_UvrYHAgV:-N2vEHeI8qp_UvrYHAgW:bdib44d) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmErrorCodeToHttpStatusCodeMapping.java#L30)):*
> ```Java
>       case SCM_CONFLICT_ERROR_V2:
>         return 409;
>       case SCM_INTERNAL_SERVER_ERROR_V2:
> ```

we can just get away with it as its 500 only.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEMyT7j3m0pzeKLZY:-N2vEMyT7j3m0pzeKLZZ:bkj44cc) ([raw file](https://github.com/harness/harness-core/blob/371a0b399835f3075767c080004777fa5c9909c3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java#L35)):*
> ```Java
>         log.error("Encountered new status code: [{}] with message: [{}] from scm", statusCode, errorMessage);
>         throw new UnexpectedException("Unexpected error occurred while doing scm operation");
>       } else if (errorCode == ErrorCode.SCM_NOT_FOUND_ERROR) {
> ```

why are we touching current handlers? Lets not do anything to current handlers

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vERfu-3o8E2LWKnMZ:-N2vERfu-3o8E2LWKnM_:b-krbh70) ([raw file](https://github.com/harness/harness-core/blob/371a0b399835f3075767c080004777fa5c9909c3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java#L52)):*
> ```Java
>         return ErrorCode.SCM_NOT_MODIFIED;
>       case 404:
>         return ErrorCode.SCM_NOT_FOUND_ERROR;
> ```

Lets not touch current handlers anywhere.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEZAS3lrFlIdQ6-dh:-N2vEZAS3lrFlIdQ6-di:b-sz3fwd) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java#L51)):*
> ```Java
>         throw NestedExceptionUtils.hintWithExplanationException(CREATE_BRANCH_CONFLICT_ERROR_HINT,
>             CREATE_BRANCH_FAILED_MESSAGE + CREATE_BRANCH_CONFLICT_ERROR_EXPLANATION,
>             new ScmBadRequestException(errorMessage));
> ```

409 is conflict right?

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEmQMD69TYEhS0jhB:-N2vEmQMD69TYEhS0jhC:b-qdamwu) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java#L39)):*
> ```Java
>         throw prepareException(new ScmBadRequestException(errorDetails.getErrorMessage()), errorDetails);
>       case 401:
>         throw prepareException(new ScmUnauthorizedException(errorDetails.getErrorMessage()), errorDetails);
> ```

we decided right that for 400, 401, 403, we will send badRequestException from SDK.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmConflictException.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEvWn01_2_z7d_RIl:-N2vEvWn01_2_z7d_RIm:bhqxk2b) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmConflictException.java#L16)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> public class ScmConflictException extends ScmException {
>   private static final String MESSAGE_ARG = "message";
> ```

Lets not touch current exceptions. Please create new V2 wherever required.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmInternalServerErrorException.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vF-jJ0h5qpYymeKe2:-N2vF-jJ0h5qpYymeKe3:b-9yx8ml) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmInternalServerErrorException.java#L16)):*
> ```Java
> @OwnedBy(HarnessTeam.PL)
> public class ScmInternalServerErrorException extends ScmException {
>   private static final String MESSAGE_ARG = "message";
> ```

There's already a V2 exception for ScmInternalServerError, lets not touch existing ones.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmUnauthorizedException.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vF7jX3ChyDLSlgVdT:-N2vF7jX3ChyDLSlgVdU:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmUnauthorizedException.java#L17)):*
> ```Java
> @OwnedBy(PL)
> public class ScmUnauthorizedException extends ScmException {
>   private static final String MESSAGE_ARG = "message";
> ```

same

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)* status: 31 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEMyT7j3m0pzeKLZY:-N2vFTiP1mEBOX5Zqk6V:byqc9kf) ([raw file](https://github.com/harness/harness-core/blob/371a0b399835f3075767c080004777fa5c9909c3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we touching current handlers? Lets not do anything to current handlers
</blockquote></details>

This is not current handler, this has been written in error framework only, if we are not able to find handler for any api, we will use this defaultScmErrorHandler
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vERfu-3o8E2LWKnMZ:-N2vFeAc09KJkk0mI2VF:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/371a0b399835f3075767c080004777fa5c9909c3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java#L52)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets not touch current handlers anywhere.
</blockquote></details>

same
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEZAS3lrFlIdQ6-dh:-N2vFjFyEkiwv6F5uhfm:b-b0ijxf) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

409 is conflict right?
</blockquote></details>

Thee is a confusion, if branch already exist 409 will come, but should we want to send 409 or 400 here?
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmConflictException.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEvWn01_2_z7d_RIl:-N2vFt-8BTyEbCLBo16P:bln38di) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmConflictException.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets not touch current exceptions. Please create new V2 wherever required.
</blockquote></details>

It's not current exception, these exceptions are used in new flow only
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmInternalServerErrorException.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vF-jJ0h5qpYymeKe2:-N2vG-dv1ESz9nBJEa2y:b70pmcj) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmInternalServerErrorException.java#L16)):*
> It's not current exception, these exceptions are used in new flow only
It's not current exception, these exceptions are used in new flow only
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmUnauthorizedException.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vF7jX3ChyDLSlgVdT:-N2vG0ZR94KU09T2fHML:bln38di) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmUnauthorizedException.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

It's not current exception, these exceptions are used in new flow only

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)* status: 31 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEZAS3lrFlIdQ6-dh:-N2vH3a3EBXOhZtlKMqo:b43djf6) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java#L51)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Thee is a confusion, if branch already exist 409 will come, but should we want to send 409 or 400 here?
</blockquote></details>

I think they are sending us the this but bitbucket sends 400 in this case, I think we should send ConflictError in case of createFile and UpdateFile Apis only

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)* status: 31 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmErrorCodeToHttpStatusCodeMapping.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEHeI8qp_UvrYHAgV:-N2vJ8Ea1HJKRDNl9CQc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmErrorCodeToHttpStatusCodeMapping.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can just get away with it as its 500 only.
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEmQMD69TYEhS0jhB:-N2vJ9Xk9hA64C-RROjp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/errorhandling/ScmErrorHandler.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we decided right that for 400, 401, 403, we will send badRequestException from SDK.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEMyT7j3m0pzeKLZY:-N2zZoUB1zlHENGAi5vC:b-woyirk) ([raw file](https://github.com/harness/harness-core/blob/371a0b399835f3075767c080004777fa5c9909c3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/DefaultScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

This is not current handler, this has been written in error framework only, if we are not able to find handler for any api, we will use this defaultScmErrorHandler
</blockquote></details>

Got it. Resolved.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEZAS3lrFlIdQ6-dh:-N2zZviY8CFFMcgdNnXW:b-n0dk1o) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubCreateBranchScmApiErrorHandler.java#L51)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I think they are sending us the this but bitbucket sends 400 in this case, I think we should send ConflictError in case of createFile and UpdateFile Apis only
</blockquote></details>

Ok got it, agreed.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmConflictException.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/33538#-N2vEvWn01_2_z7d_RIl:-N2z_CrJE1aCe2JrbyLf:b2nhll9) ([raw file](https://github.com/harness/harness-core/blob/6125eae1e9635cc8ec11e5e603fcf697205fa5e4/952-scm-java-client/src/main/java/io/harness/exception/ScmConflictException.java#L16)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

It's not current exception, these exceptions are used in new flow only
</blockquote></details>

Ok.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538#-:-N2z_J_A0F-z789aFc0U:bnfp4nl)* status: 31 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)* status: 31 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538)* status: 31 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 27 of 31 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33538#-:-N3-EQDc7hTPm4ObGcOa:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
