### PR TITLE
feat: [CDS-50321]: Impl for Migration logic Instance sync V2 CG

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/42519#-NL_dDNP5YtLR6ONZzgS:-NL_dDNP5YtLR6ONZzgT:bgfu1c1) ([raw file](https://github.com/harness/harness-core/blob/d354cdc635ba324e4a184697ac086da644a23ffc/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L177)):*
> ```Java
>           result.getAccountId(), perpetualTaskId);
>       List<InstanceSyncTaskDetails> instanceSyncTaskDetails =
>           taskDetailsService.fetchAllForPerpetualTask(result.getAccountId(), perpetualTaskId);
> ```

Use iterator or batching over here as if these are large they can affect our service by bringing too much of data in memory. 

Iterator will help us in not bloating up our pod memory.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 285 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLz0xt13KzsmsiW6OxN:-NLz0xt6Ajfc6AGNUEFa:b-epb6tk) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L285)):*
> ```Java
>     for (InstanceSyncTaskDetails taskDetails : instanceSyncTaskDetails) {
>       InfrastructureMapping infraMapping =
>           infrastructureMappingService.get(taskDetails.getAppId(), taskDetails.getInfraMappingId());
> ```

As relation between InfrastructureMapping and InstanceSyncTaskDetails is 1:n, we could refactor it to something like:
1. Map instanceSyncTaskDetails to Map<String, List<InstanceSyncTaskDetails>> where Key is infraMappingId
2. Loop through entry in map 
This way we will reduce duplicate calls to get InfrastructureMapping
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/service/CgInstanceSyncTaskDetailsService.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLytZFG3mdUPjNGbCc9:-NLytZFG3mdUPjNGbCcA:b-azsxef) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/instancesyncv2/service/CgInstanceSyncTaskDetailsService.java#L48)):*
> ```Java
>   public boolean delete(String taskDetailsId) {
>     return mongoPersistence.delete(InstanceSyncTaskDetails.class, taskDetailsId);
>   }
> ```

nit: add space after
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 207 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLyqqFG-n5lo2YlQlu4:-NLyqqFG-n5lo2YlQlu5:b-fqwh58) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L207)):*
> ```Java
>   }
> 
>   private ContainerMetadata getContainerMetadataFromPT(PerpetualTaskRecord record) {
> ```

This this method duplicate of the same logic as in createPerpetualTasksForNewDeployment? Should we then use this method as well in createPerpetualTasksForNewDeployment
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLyt9nE9-7f9qOVU7wL:-NLyt9nE9-7f9qOVU7wM:b-8fqr12) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java#L164)):*
> ```Java
>     }
> 
>     if (backup && perpetualTaskRecord != null) {
> ```

nit: move under first if
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java` line 221 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLyrpGf3a4sSKwQxPrh:-NLyrpGf3a4sSKwQxPri:b-68fmwc) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java#L221)):*
> ```Java
>     InstanceSyncByPerpetualTaskHandler handler = getInstanceHandler(infrastructureMapping);
>     InstanceSyncPerpetualTaskCreator instanceSyncPTCreator = handler.getInstanceSyncPerpetualTaskCreator();
>     // TODO: merge existing perpetual task and get perpetual task info
> ```

Is this TODO done?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: 8 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 177 at r1](https://reviewable.io/reviews/harness/harness-core/42519#-NL_dDNP5YtLR6ONZzgS:-NLzUCTC3fXapAYWrvuG:b-nnrnd1) ([raw file](https://github.com/harness/harness-core/blob/eff939278439b8713e5bf889929ca81ded242808/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L177)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use iterator or batching over here as if these are large they can affect our service by bringing too much of data in memory. 

Iterator will help us in not bloating up our pod memory. 
</blockquote></details>

only bringing one batch instanceSyncTaskDetails at a time now
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 285 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLz0xt13KzsmsiW6OxN:-NM28VlR6a_AsSgFEgox:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L285)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

As relation between InfrastructureMapping and InstanceSyncTaskDetails is 1:n, we could refactor it to something like:
1. Map instanceSyncTaskDetails to Map<String, List<InstanceSyncTaskDetails>> where Key is infraMappingId
2. Loop through entry in map 
This way we will reduce duplicate calls to get InfrastructureMapping
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 207 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLyqqFG-n5lo2YlQlu4:-NLzePue1ZwctukoB5Zq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L207)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This this method duplicate of the same logic as in createPerpetualTasksForNewDeployment? Should we then use this method as well in createPerpetualTasksForNewDeployment
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java` line 221 at r3](https://reviewable.io/reviews/harness/harness-core/42519#-NLyrpGf3a4sSKwQxPrh:-NLzp4tVCgyONEqcF4fC:bzbahs7) ([raw file](https://github.com/harness/harness-core/blob/7ceb1ab034f8c2ecf84f05e65ae9d2554b693a47/400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java#L221)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this TODO done?
</blockquote></details>

this I'm doing in new deployment PR

**Comment by namantalaycha10** [comment]
trigger ss

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 295 at r5](https://reviewable.io/reviews/harness/harness-core/42519#-NM3upVr5k9CvKkuy78g:-NM3upVr5k9CvKkuy78h:b-gehv0) ([raw file](https://github.com/harness/harness-core/blob/821881bf8e663b550fae57e633024f4a25ab546a/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L295)):*
> ```Java
>           infrastructureMappingService.get(instanceSyncTaskDetails.iterator().next().getAppId(), infraMappingId);
>       for (InstanceSyncTaskDetails taskDetails : instanceTaskMap.get(infraMappingId)) {
>         try (AcquiredLock lock = persistentLocker.tryToAcquireLock(
> ```

Wouldn't it be better if we will lock it only once and process all instanceSyncTaskDetails at once?
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/42519#-NM3vKQj8q-hjvHL2eKR:-NM3vKQj8q-hjvHL2eKS:b-xuysom) ([raw file](https://github.com/harness/harness-core/blob/821881bf8e663b550fae57e633024f4a25ab546a/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java#L37)):*
> ```Java
>   }
> 
>   Optional<InstanceSyncPTInfoBackup> findByAccountIdAndInfraMappingId(String accountId, String infraMappingId) {
> ```

Where we're using this method? It shouldn't be used or we're doing something wrong

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 295 at r5](https://reviewable.io/reviews/harness/harness-core/42519#-NM3upVr5k9CvKkuy78g:-NM7v45u9pDlTNlecqG4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/821881bf8e663b550fae57e633024f4a25ab546a/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L295)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Wouldn't it be better if we will lock it only once and process all instanceSyncTaskDetails at once?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/42519#-NM3vKQj8q-hjvHL2eKR:-NM7tAzi25uIjYlaDZJG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/821881bf8e663b550fae57e633024f4a25ab546a/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java#L37)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Where we're using this method? It shouldn't be used or we're doing something wrong
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: 15 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 13 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42519)* status: :shipit: complete! ✓

**Pull request merged**
