### PR TITLE
fix: [CDS-54283]: Adding null check for service override variable values

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Have added validation to avoid creating service overides variables with null values.
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44723)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
Lets wait on this, I put a question to product here: https://harness.atlassian.net/browse/CDS-54283?focusedCommentId=457639

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44723#-:-NPzvxqO9auHemoCtA26:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 198 at r3](https://reviewable.io/reviews/harness/harness-core/44723#-NQ6h8Y012Sc8F4PCA4A:-NQ6h8Y012Sc8F4PCA4B:b-o04098) ([raw file](https://github.com/harness/harness-core/blob/933526a5c04ffc10b629747c1e18b5e0d55c49f8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L198)):*
> ```Java
>             nullOverrideValues++;
>           }
>         }
> ```

can we just do this
```
if (variableOverride.getCurrentValue().fetchFinalValue() == null) {
          nullOverrideValues++;
        }
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44723)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 198 at r3](https://reviewable.io/reviews/harness/harness-core/44723#-NQ6h8Y012Sc8F4PCA4A:-NQBIZCg37mY4MaV8SSV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/933526a5c04ffc10b629747c1e18b5e0d55c49f8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L198)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we just do this
```
if (variableOverride.getCurrentValue().fetchFinalValue() == null) {
          nullOverrideValues++;
        }
```
</blockquote></details>

Done

**Review by vivekkarnatiharness — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44723)* status: 7 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/44723#-NPpFB2s3MNkkcevs-yP:-NQBIcSJ5h7GUsRRGjO8:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets wait on this, I put a question to product here: https://harness.atlassian.net/browse/CDS-54283?focusedCommentId=457639
</blockquote></details>

Done.

___

**Comment by vivekkarnatiharness** [comment]
trigger ut6

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44723)* status: 7 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 195 at r5](https://reviewable.io/reviews/harness/harness-core/44723#-NQOfPw4CZHsUK1SvOtq:-NQOfPw4CZHsUK1SvOtr:bpo63c6) ([raw file](https://github.com/harness/harness-core/blob/1086defb5b119097209d2e99a166941950d4b874/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L195)):*
> ```Java
>         String plural = nullOverrideValues == 1 ? "" : "s";
>         throw new InvalidRequestException(
>             String.format("value%s not provided for %s variable override%s in service ref: [%s]", plural,
> ```

can we also list variable names for which value is not provided ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 4 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44723)* status: 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 195 at r5](https://reviewable.io/reviews/harness/harness-core/44723#-NQOfPw4CZHsUK1SvOtq:-NQQ5F8N3SCK_Nwu58l0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1086defb5b119097209d2e99a166941950d4b874/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L195)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we also list variable names for which value is not provided ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44723)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
trigger ut0

**Pull request merged**
