### PR TITLE
feat: [PL-30373]: Added Basic role at ORG and Project Scope

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41524)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41524)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 747 at r2](https://reviewable.io/reviews/harness/harness-core/41524#-NJGeupA7Yl8cZEYFyi9:-NJGeupA7Yl8cZEYFyiA:b8fc5rb) ([raw file](https://github.com/harness/harness-core/blob/319eb8bdefae8c2b4ba0354615cb672f0c931105/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L747)):*
> ```YAML
>       allowedScopeLevels:
>         - account
>     - identifier: _organization_basic
> ```

Increment the version number for managed-roles.yaml

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41524)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 747 at r2](https://reviewable.io/reviews/harness/harness-core/41524#-NJGeupA7Yl8cZEYFyi9:-NJJuxTH8IzWCx1FpOP4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/319eb8bdefae8c2b4ba0354615cb672f0c931105/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L747)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Increment the version number for managed-roles.yaml
</blockquote></details>

Done.

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41524#-:-NJLUsEr8b6N-6eLYpVC:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41524)* status: :shipit: complete! ✓

**Pull request merged**
