### PR TITLE
techdebt: [PIE-4431]: added a config in CDC module

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35440)

### CODE REVIEW

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35440)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/entities/PipelineExecutionSummaryEntityCDCEntity.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/35440#-N7KHs0w5F0Ho84zcLny:-N7KHs0xColOxyKXc_O0:b-za8hyv) ([raw file](https://github.com/harness/harness-core/blob/c2f362b83e2d71a2b8a18528bd9c1b919cc51879/110-change-data-capture/src/main/java/io/harness/entities/PipelineExecutionSummaryEntityCDCEntity.java#L46)):*
> ```Java
>       return planExecutionSummaryChangeDataHandler;
>     } else if (handlerClass.contentEquals("PipelineExecutionSummaryEntityCD")) {
>       if (config.isDebeziumEnabled() && !debeziumEnabled) {
> ```

We should not have the config check here
otherwise it will not get the handler

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35440)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35440)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35440)* status: :shipit: complete! ✓

**Pull request merged**
