### PR TITLE
fix: [CDS-43600]: WinRM remote PS execution 15+ second delays after c…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…onnection before script(s) begin execution.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38073)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 4 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38073)

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/38073#-ND76f7KBlYicAtaMjWy:-ND76f7KBlYicAtaMjWz:b-sypweg) ([raw file](https://github.com/harness/harness-core/blob/83317b34755a11f415de5923782b26edb626f58b/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java#L74)):*
> ```Java
>   protected boolean shouldSaveExecutionLogs;
> 
>   public FileBasedAbstractWinRmExecutor(LogCallback logCallback, boolean shouldSaveExecutionLogs,
> ```

is this method being used? If not, we can remove it.

**Comment by arvind-choudhary-h** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 441 at r2](https://reviewable.io/reviews/harness/harness-core/38073#-ND77yem4mCX0efc9gjL:-ND77yem4mCX0efc9gjM:b-onng6c) ([raw file](https://github.com/harness/harness-core/blob/83317b34755a11f415de5923782b26edb626f58b/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L441)):*
> ```Java
>   PL_ENABLE_GOOGLE_SECRET_MANAGER_IN_NG("Enable Google Secret Manager in NG", HarnessTeam.PL),
>   WINRM_SCRIPT_COMMAND_SPLIT(
>       "Enables the new way of how to copy script command content to file on remote.", HarnessTeam.CDP);
> ```

nit: we can mention that it's for powershell / winrm scripts and we are using batching of 4KB of scripts to transfer at once.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 35 of 36 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38073)* status: 0 of 1 approvals obtained.

**Comment by bojanmicovic** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/CommandState.java` line 939 at r2](https://reviewable.io/reviews/harness/harness-core/38073#-ND75uBB8_J9PCwHfjHi:-ND7V_8CD0CHY8C2y_-4:b8go2vd) ([raw file](https://github.com/harness/harness-core/blob/83317b34755a11f415de5923782b26edb626f58b/400-rest/src/main/java/software/wings/sm/states/CommandState.java#L939)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

We should enable winrmScriptCommandSplit field.
</blockquote></details>

Good catch. Thanks!

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/38073#-ND76f7KBlYicAtaMjWy:-ND7VdgHBHch_IRHZc6I:b-w92azl) ([raw file](https://github.com/harness/harness-core/blob/83317b34755a11f415de5923782b26edb626f58b/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedAbstractWinRmExecutor.java#L74)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

is this method being used? If not, we can remove it.
</blockquote></details>

This one is used in NG for copying  config files for WinRm

**Comment by bojanmicovic** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 441 at r2](https://reviewable.io/reviews/harness/harness-core/38073#-ND77yem4mCX0efc9gjL:-ND7WMa44sSXCSJ3QTh9:bbtiiqh) ([raw file](https://github.com/harness/harness-core/blob/83317b34755a11f415de5923782b26edb626f58b/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L441)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

nit: we can mention that it's for powershell / winrm scripts and we are using batching of 4KB of scripts to transfer at once.
</blockquote></details>

Good point. Will do.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38073)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger codebasehash

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 30 of 36 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38073)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/38073#-ND8w1YRCHc9NmxgQHvp:-ND8w1YRCHc9NmxgQHvq:b-3o8nz4) ([raw file](https://github.com/harness/harness-core/blob/9cfc49e5fda73a81f84ce168e379081148d8b6ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L98)):*
> ```Java
>     String commandParametersString = buildCommandParameters(commandParameters);
> 
>     List<List<Byte>> partitions = Lists.partition(Bytes.asList(command.getBytes()), PARTITION_SIZE_IN_BYTES);
> ```

What I suggest here is firstly do escape break and line characters on the whole command and after that do bytes partitioning. I think that partitioning before that could break UTF8 decoding. Also, we need later on to add the snippet for appendalltext that is critical. We might need to think about the algorithm around the next line.

**Comment by arvind-choudhary-h** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 444 at r4](https://reviewable.io/reviews/harness/harness-core/38073#-NDDJZCA9A2Cl62AHePj:-NDDJZCA9A2Cl62AHePk:b-rb6zzu) ([raw file](https://github.com/harness/harness-core/blob/7bc4be98889dd3fcf61a4ad87fa87c7ae2cead40/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L444)):*
> ```Java
>   PL_ENABLE_GOOGLE_SECRET_MANAGER_IN_NG("Enable Google Secret Manager in NG", HarnessTeam.PL),
>   SPG_DISABLE_SEARCH_DEPLOYMENTS_PAGE("Disable search on deployment page in CG.", HarnessTeam.SPG),
>   CD_SERVICENOW_IMPORT_SET_NG("Enable ServiceNow Import Set Step", HarnessTeam.CDC),
> ```

how did these come here?

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/38073#-ND8w1YRCHc9NmxgQHvp:-NDDJbfmBNfWK0fyoSoO:b-dxcbts) ([raw file](https://github.com/harness/harness-core/blob/9cfc49e5fda73a81f84ce168e379081148d8b6ca/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L98)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What I suggest here is firstly do escape break and line characters on the whole command and after that do bytes partitioning. I think that partitioning before that could break UTF8 decoding. Also, we need later on to add the snippet for appendalltext that is critical. We might need to think about the algorithm around the next line. 
</blockquote></details>

Makes sense.

**Comment by bojanmicovic** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 444 at r4](https://reviewable.io/reviews/harness/harness-core/38073#-NDDJZCA9A2Cl62AHePj:-NDDR7XW0TFHu6KN-eJ5:bq9rsbh) ([raw file](https://github.com/harness/harness-core/blob/7bc4be98889dd3fcf61a4ad87fa87c7ae2cead40/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L444)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

how did these come here?
</blockquote></details>

Not my change. I just replaced ';' with ',' at this line

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38073)* status: 1. unresolved discussions.

**Comment by bojanmicovic** [comment]
trigger codebasehash

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 32 of 36 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38073)* status: :shipit: complete! ✓

**Pull request merged**
