### PR TITLE
[feat]:[pie-7333]: contract for moving pipeline from harness to git

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
BE contract changes for moving inline pipeline from harness db to remote repository.

Impact -> To easily move from harness to git

Testing: NA

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 491 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMOc_b-4EIXUPiTvng:-NKMOc_b-4EIXUPiTvnh:b-3jx6gk) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L491)):*
> ```Java
> 
>   @Override
>   public ResponseDTO<PipelineSaveResponse> movePipelineFromHarnessToRemote(String accountIdentifier,
> ```

Lets make it "InlineToRemote"

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 493 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMOiSG1Vz1gVG6KjSP:-NKMOiSG1Vz1gVG6KjSQ:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L493)):*
> ```Java
>   public ResponseDTO<PipelineSaveResponse> movePipelineFromHarnessToRemote(String accountIdentifier,
>       String orgIdentifier, String projectIdentifier, String pipelineIdentifier,
>       HarnessToGitInfoDTO harnessToGitInfoDTO) {
> ```

Same here

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 604 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMP0cYB5Tn5viAIRl-:-NKMP0cYB5Tn5viAIRl0:b-jqubno) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L604)):*
> ```Java
> 
>   @POST
>   @Path("/move-harness-to-git/{pipelineIdentifier}")
> ```

Lets think of some better path. Also, why is pipeline-identifier a path param here?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 604 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMP0cYB5Tn5viAIRl-:-NKMRTkY-1bE_e5bLeN_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L604)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets think of some better path. Also, why is pipeline-identifier a path param here?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 491 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMOc_b-4EIXUPiTvng:-NKMRSrF0Im9dVZXFqxH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L491)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets make it "InlineToRemote"
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 493 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMOiSG1Vz1gVG6KjSP:-NKMRSfXEsi1ZLYLbflb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L493)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/42026#-NKN6hPc0AZpEqJ_rehO:-NKN6hPc0AZpEqJ_rehP:b-8k1lfz) ([raw file](https://github.com/harness/harness-core/blob/dd90895afe85950eb5dacdc09b167192e098b5de/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java#L27)):*
> ```Java
> @Builder
> @FieldNameConstants(innerTypeName = "HarnessToGitInfoDTOKeys")
> @Schema(name = "HarnessToGitInfoDTO", description = "Details to move entity from harness to git")
> ```

need to change names here acc to class name

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42026#-NKN6xjCBfIfBmemdre8:-NKN6xjD-BT188NmT88b:bn9ryfh) ([raw file](https://github.com/harness/harness-core/blob/dd90895afe85950eb5dacdc09b167192e098b5de/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java#L31)):*
> ```Java
> @NoArgsConstructor
> @AllArgsConstructor
> public class InlineToRemoteInfoDTO {
> ```

shouldn't we name it "MoveInlineToRemoveRequestDTO" or similar?

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 604 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMP0cYB5Tn5viAIRl-:-NKN76CjCW9cHhE1YyH6:brix0r9) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L604)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@adivishy1 please go through the link shared on DM. I think its fair to have identifier in the path param.

Also, I guess we should put URL as "move-config" and take some parameter as input in request body to identify whether its from REMOTE TO INLINE or INLINE TO REMOTE.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: 2. unresolved discussions.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: 6 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 604 at r1](https://reviewable.io/reviews/harness/harness-core/42026#-NKMP0cYB5Tn5viAIRl-:-NKNHs8U6bFihSHjiOlq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/850154de259fd3ab54c74aa153c8e5d1d023a06c/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L604)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@adivishy1 please go through the link shared on DM. I think its fair to have identifier in the path param.

Also, I guess we should put URL as "move-config" and take some parameter as input in request body to identify whether its from REMOTE TO INLINE or INLINE TO REMOTE.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/42026#-NKN6hPc0AZpEqJ_rehO:-NKN9bZt3UEbI3Lh1vMb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd90895afe85950eb5dacdc09b167192e098b5de/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

need to change names here acc to class name
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42026#-NKN6xjCBfIfBmemdre8:-NKN9bqaADocAW5uDZqk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd90895afe85950eb5dacdc09b167192e098b5de/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't we name it "MoveInlineToRemoveRequestDTO" or similar?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: 5. unresolved discussions.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java` line 27 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRfMKy-OnlFBT-4Zrp:-NKRfMKz0Natn7Cld94J:btomsmq) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java#L27)):*
> ```Java
> @Builder
> @FieldNameConstants(innerTypeName = "MoveInlineToRemoveRequestDTOKeys")
> @Schema(name = "MoveInlineToRemoveRequestDTO", description = "Details to move entity from harness to git")
> ```

The schema name shouldn't be InlineToRemote as its a generic dto.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java` line 46 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRfTYlCyvRgHzowiQq:-NKRfTYlCyvRgHzowiQr:b-j55w7b) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java#L46)):*
> ```Java
>   @Parameter(description = GitSyncApiConstants.MOVE_CONFIG_PARAM_MESSAGE)
>   @QueryParam(GitSyncApiConstants.MOVE_CONFIG_KEY)
>   MoveConfigType moveConfigType;
> ```

Lets name it OperationType or MoveConfigOperationType or something similar.

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 604 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRfa3d8sRxcAeXyVpH:-NKRfa3e6sbElvxl2Dw8:bd291z) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L604)):*
> ```Java
> 
>   @POST
>   @Path("/move-configs/{pipelineIdentifier}")
> ```

should be "move-config" not "configs"

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42026#-NKN6xjCBfIfBmemdre8:-NKRfzkP2aAIMKwjpjHc:b693jjv) ([raw file](https://github.com/harness/harness-core/blob/dd90895afe85950eb5dacdc09b167192e098b5de/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java#L31)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We should also have pipelineidentifier in our request body and have validation on it. Reference: https://dzone.com/articles/rest-api-path-vs-request-body-parameters

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSMoveConfigResponse.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRh8JL5FWixJqLioia:-NKRh8JL5FWixJqLioib:bti0ogd) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSMoveConfigResponse.java#L28)):*
> ```Java
> @Schema(name = "PMSMoveConfigResponse", description = "Tells us if the move config was successful or not")
> @OwnedBy(PL)
> public class PMSMoveConfigResponse {
> ```

why does the name has "PMS" in it?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: 8. unresolved discussions. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 604 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRfa3d8sRxcAeXyVpH:-NKSCYl241f2Rrlmcn6K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L604)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should be "move-config" not "configs"
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSMoveConfigResponse.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRh8JL5FWixJqLioia:-NKSCZKl9ui-MQsK8pb_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSMoveConfigResponse.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why does the name has "PMS" in it?
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/42026#-NKN6xjCBfIfBmemdre8:-NKSCTnyADQ5oshn4sYv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd90895afe85950eb5dacdc09b167192e098b5de/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/InlineToRemoteInfoDTO.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should also have pipelineidentifier in our request body and have validation on it. Reference: https://dzone.com/articles/rest-api-path-vs-request-body-parameters
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java` line 27 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRfMKy-OnlFBT-4Zrp:-NKSBu7i6xIiSjFg9A4a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The schema name shouldn't be InlineToRemote as its a generic dto.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java` line 46 at r5](https://reviewable.io/reviews/harness/harness-core/42026#-NKRfTYlCyvRgHzowiQq:-NKSCUGY1wHGEkpoYvue:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/95f453220d0c1bd8c82f79a89662eb58bb60491c/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/MoveConfigsRequestDTO.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets name it OperationType or MoveConfigOperationType or something similar.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42026)* status: :shipit: complete! ✓

**Pull request merged**
