### PR TITLE
feat: [CDS-58103]: Aws SAM Build and Deploy step on containerv2 step

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Add AWS SAM build/deploy steps based on pluginstep of CI
- Add plugininfoproviders for fetching information for preparing pod specifications

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)

### CODE REVIEW

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: 33 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 423 at r1](https://reviewable.io/reviews/harness/harness-core/46976#-NTvoFm_1ikw6XFszi5M:-NTvoFmaEoUCGj34yCS9:b-edwrzq) ([raw file](https://github.com/harness/harness-core/blob/0cb0be7c055a4cf398b28524cb8c8f2a53dc006b/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L423)):*
> ```Java
> 
>     planCreators.add(new AzureARMRollbackResourceStepPlanCreator());
>     planCreators.add(new StepGroupPMSPlanCreatorV2());
> ```

please revert this for now and remove the dependency to this.

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: 37 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 423 at r1](https://reviewable.io/reviews/harness/harness-core/46976#-NTvoFm_1ikw6XFszi5M:-NU4GyOnD6jUKeqlDEuR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0cb0be7c055a4cf398b28524cb8c8f2a53dc006b/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L423)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

please revert this for now and remove the dependency to this. 
</blockquote></details>

done

**Review by sainath-b — APPROVED** [review]
> Reviewed 8 of 33 files at r1, 33 of 33 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: Some of the checks are too old. 41 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployBaseStepInfo.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/46976#-NUPiZcC1rs_0kBuCtg4:-NUPiZcC1rs_0kBuCtg5:bx6732j) ([raw file](https://github.com/harness/harness-core/blob/c00dccb20f00d5ebabdcdc3b9ca1fca79a6ba360/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployBaseStepInfo.java#L11)):*
> ```Java
> //
> // import static io.harness.beans.SwaggerConstants.BOOLEAN_CLASSPATH;
> // import static io.harness.beans.SwaggerConstants.INTEGER_CLASSPATH;
> ```

This file is commented out. Can we remove this if not used?

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/46976#-NUPijVu6iJGrr-aNq8_:-NUPijVu6iJGrr-aNq8a:b-ierw61) ([raw file](https://github.com/harness/harness-core/blob/c00dccb20f00d5ebabdcdc3b9ca1fca79a6ba360/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L67)):*
> ```Java
>         getPort(ambiance, stepElementParameters.getIdentifier()), parkedTaskId, logKey,
>         stepElementParameters.getIdentifier(), getTimeout(ambiance, stepElementParameters), accountId,
>         stepElementParameters.getName(), delegateCallbackTokenSupplier, ambiance, new HashMap<>(),
> ```

We are not passing environment variables too over here. Will we do it in follow up PR?

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: Some of the checks are too old. 41 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployBaseStepInfo.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/46976#-NUPiZcC1rs_0kBuCtg4:-NUPl5Xx4DkpgUmJcuS4:b-73nukz) ([raw file](https://github.com/harness/harness-core/blob/c00dccb20f00d5ebabdcdc3b9ca1fca79a6ba360/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployBaseStepInfo.java#L11)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This file is commented out. Can we remove this if not used?
</blockquote></details>

will remove
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/46976#-NUPijVu6iJGrr-aNq8_:-NUPl3HdCYxiWb-PeIM1:byabc0k) ([raw file](https://github.com/harness/harness-core/blob/c00dccb20f00d5ebabdcdc3b9ca1fca79a6ba360/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L67)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We are not passing environment variables too over here. Will we do it in follow up PR?
</blockquote></details>

yes, followup PR,

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStepInfo.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/46976#-NUPoJidDGr-vFHHBhhV:-NUPoJidDGr-vFHHBhhW:b-zgzka1) ([raw file](https://github.com/harness/harness-core/blob/60dd39dbfb4ecd244275ae72a68e64859353fbc1/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStepInfo.java#L85)):*
> ```Java
>   public SpecParameters getSpecParameters() {
>     return AwsSamDeployStepParameters.infoBuilder()
>         .image(getImage())
> ```

nit: We should set all other fields as well.

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamBuildPluginInfoProvider.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/46976#-NUPoUAy77hSZo5lqQdN:-NUPoUAy77hSZo5lqQdO:bilikot) ([raw file](https://github.com/harness/harness-core/blob/60dd39dbfb4ecd244275ae72a68e64859353fbc1/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamBuildPluginInfoProvider.java#L37)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public class AwsSamBuildPluginInfoProvider implements CDPluginInfoProvider {
> ```

Can we please create a common class for both AwsSamBuildPluginInfoProvider and AwsSamDeployPluginInfoProvider?
and override if necessary.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/BUILD.bazel` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/46976#-NUPozC06kBgOc0oKvTx:-NUPozC1AVbCUBOnQXHa:bp7ify) ([raw file](https://github.com/harness/harness-core/blob/60dd39dbfb4ecd244275ae72a68e64859353fbc1/pipeline-service/modules/orchestration-steps/BUILD.bazel#L18)):*
> ```Starlark
>     visibility = [
>         "//100-migrator:__subpackages__",
>         "//125-cd-nextgen:__subpackages__",
> ```

nit: remove

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 33 files at r1, 32 of 33 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: 1 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStepInfo.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/46976#-NUPoJidDGr-vFHHBhhV:-NUQH-Ld4WPzyA2YimuC:b-gvtou3) ([raw file](https://github.com/harness/harness-core/blob/60dd39dbfb4ecd244275ae72a68e64859353fbc1/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStepInfo.java#L85)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: We should set all other fields as well.
</blockquote></details>

Will update in follow up PR
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamBuildPluginInfoProvider.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/46976#-NUPoUAy77hSZo5lqQdN:-NUQGz0fBqptkzCpize0:b-gvtou3) ([raw file](https://github.com/harness/harness-core/blob/60dd39dbfb4ecd244275ae72a68e64859353fbc1/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsSamBuildPluginInfoProvider.java#L37)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we please create a common class for both AwsSamBuildPluginInfoProvider and AwsSamDeployPluginInfoProvider?
and override if necessary.
</blockquote></details>

Will update in follow up PR
___
*[`pipeline-service/modules/orchestration-steps/BUILD.bazel` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/46976#-NUPozC06kBgOc0oKvTx:-NUQGv7HC6eTNzc0yNvN:b-gvtou3) ([raw file](https://github.com/harness/harness-core/blob/60dd39dbfb4ecd244275ae72a68e64859353fbc1/pipeline-service/modules/orchestration-steps/BUILD.bazel#L18)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: remove
</blockquote></details>

Will update in follow up PR

**Review by sainath-b — DISMISSED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46976)* status: 15 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sainath-b** [comment]
trigger messagecheck

**Comment by sainath-b** [comment]
trigger ut0

**Comment by sainath-b** [comment]
trigger ut2

**Comment by sainath-b** [comment]
trigger ut3

**Comment by sainath-b** [comment]
trigger ut4

**Comment by sainath-b** [comment]
trigger ut6

**Comment by sainath-b** [comment]
trigger ut7

**Comment by sainath-b** [comment]
trigger ut8

**Comment by sainath-b** [comment]
trigger ut9

**Review by sainath-b — APPROVED** [review]

**Comment by sainath-b** [comment]
trigger review

**Pull request merged**
