### PR TITLE
feat: [PIE-6829]: Add default branch support into gitx caching

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
In short, we are trying to add support to handle default branch use-cases with gitx caching. For details, please check JIRA: https://harness.atlassian.net/browse/PIE-6829

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)

### CODE REVIEW

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 6 of 25 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 25 file(s) to review. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/41185#-NIfvAVj7feZN26yueWL:-NIfvAVj7feZN26yueWM:b-s5demz) ([raw file](https://github.com/harness/harness-core/blob/d6bce511c2256d9f2d70a3ec4b16eb3667f273c4/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java#L83)):*
> ```Java
>                  .field(GitFileCacheKeys.completeFilepath)
>                  .field(GitFileCacheKeys.isDefaultBranch)
>                  .build())
> ```

do we need two keys or can we just one key, accountIdentifier_gitProvider_repoName_completeFilepath_isDefaultBranch_idx, and pass to this either true or false to this?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/41185#-NIfvAVj7feZN26yueWL:-NIfvwHf4DY7sRJrfaUX:b-wkfwya) ([raw file](https://github.com/harness/harness-core/blob/d6bce511c2256d9f2d70a3ec4b16eb3667f273c4/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java#L83)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

do we need two keys or can we just one key, accountIdentifier_gitProvider_repoName_completeFilepath_isDefaultBranch_idx, and pass to this either true or false to this?
</blockquote></details>

actually I did think of this, but I found out some issue in it. I'm not able to remember it as of now. Let me think more on it, if not, I will change it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/41185#-NIfvAVj7feZN26yueWL:-NIfxR5b-OUSyyNPrIhA:b-a70aek) ([raw file](https://github.com/harness/harness-core/blob/d6bce511c2256d9f2d70a3ec4b16eb3667f273c4/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitFileCache.java#L83)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

actually I did think of this, but I found out some issue in it. I'm not able to remember it as of now. Let me think more on it, if not, I will change it.
</blockquote></details>

have fixed the index for now as requested. Will think more on it, will update if I find something. Thanks for pointing out.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 25 files at r1, 18 of 19 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 327 at r2](https://reviewable.io/reviews/harness/harness-core/41185#-NIfyKa384bpNq0tfwlK:-NIfyKa384bpNq0tfwlL:b-6a5ebn) ([raw file](https://github.com/harness/harness-core/blob/d6bce511c2256d9f2d70a3ec4b16eb3667f273c4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L327)):*
> ```Java
>               .build());
>     }
> ```

isnt this and above method same?



_Code quote:_
```Java
    if (ngFeatureFlagHelperService.isEnabled(scope.getAccountIdentifier(), FeatureName.PIE_NG_GITX_CACHING)) {
      gitFileCacheService.upsertCache(
          getCacheKey(scmGetFileByBranchRequestDTO, scmConnector, gitFileResponse.getBranch()),
          GitFileCacheObject.builder()
              .fileContent(gitFileResponse.getContent())
              .commitId(gitFileResponse.getCommitId())
              .objectId(gitFileResponse.getObjectId())
              .build());
    }
```
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 552 at r2](https://reviewable.io/reviews/harness/harness-core/41185#-NIfyQ_DBh87GpLcrBun:-NIfyQ_DBh87GpLcrBuo:bwgkxxk) ([raw file](https://github.com/harness/harness-core/blob/d6bce511c2256d9f2d70a3ec4b16eb3667f273c4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L552)):*
> ```Java
>                                           .repoName(scmUpdateFileRequestDTO.getRepoName())
>                                           .ref(scmUpdateFileRequestDTO.getBranchName())
>                                           .build(),
> ```

same for this, only git cache key generation is different



_Code quote:_
```Java
    if (ngFeatureFlagHelperService.isEnabled(scope.getAccountIdentifier(), FeatureName.PIE_NG_GITX_CACHING)) {
      gitFileCacheService.upsertCache(GitFileCacheKey.builder()
                                          .accountIdentifier(scope.getAccountIdentifier())
                                          .completeFilePath(scmUpdateFileRequestDTO.getFilePath())
                                          .gitProvider(GitProviderUtil.getGitProvider(scmConnector))
                                          .repoName(scmUpdateFileRequestDTO.getRepoName())
                                          .ref(scmUpdateFileRequestDTO.getBranchName())
                                          .build(),
```

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 327 at r2](https://reviewable.io/reviews/harness/harness-core/41185#-NIfyKa384bpNq0tfwlK:-NIgetWK3dnb_GpeBlVS:b5pab4z) ([raw file](https://github.com/harness/harness-core/blob/d6bce511c2256d9f2d70a3ec4b16eb3667f273c4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L327)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this and above method same?
</blockquote></details>

fixed it, came due to rebasing with develop

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 1 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 2 file(s) to review.

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by naman-goenka — APPROVED** [review]
> Reviewed 2 of 25 files at r1, 2 of 2 files at r3, 1 of 3 files at r4, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 2 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: 2 file(s) to review.

**Review by akhilpandey1 — APPROVED** [review]
> Reviewed 2 of 25 files at r1, 16 of 19 files at r2, 2 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41185)* status: :shipit: complete! ✓

**Pull request merged**
