### PR TITLE
feat: [CDS-52513]: Integrating client-go credential for AKS kubeconfig.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Integrating client-go credential for AKS kubeconfig. [https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44939)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger checkstylecodeformat

**Comment by GoelPratyush99** [comment]
trigger ut3

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 19 files at r1, 1 of 3 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44939)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java` line 573 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQ9wsg88T3owd8G49Es:-NQ9wsg88T3owd8G49Et:b-jxrhru) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java#L573)):*
> ```Java
>         String apiServerId = Exec.getValueFromArgsList(userConfig.getExec().getArgs(), KUBECFG_ARGS_SERVER_ID);
>         azureKubeConfig.setAadToken(fetchAksAADToken(azureConfig, apiServerId));
>         azureKubeConfig.getUsers().get(0).getUser().setExec(
> ```

This can be userConfig.setExec(
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java` line 675 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQ9xty62D2hE5cmG2w_:-NQ9xty62D2hE5cmG2wa:b-u61p5b) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java#L675)):*
> ```Java
>       }
> 
>       if (isEmpty(azureKubeConfig.getUsers().get(0).getUser().getExec().getCommand())) {
> ```

Not necessary as we provide our own constant value in updateAzureKubeconfig
___
*[`960-api-services/src/main/java/io/harness/azure/client/AzureKubernetesRestClient.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQ9zDYOBRLzyC_CC6Eq:-NQ9zDYPCmMXuUUO4f9t:b-b2o11p) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/960-api-services/src/main/java/io/harness/azure/client/AzureKubernetesRestClient.java#L28)):*
> ```Java
>       @Path(value = AzureConstants.RESOURCE_GROUP) String resourceGroup,
>       @Path(value = AzureConstants.AKS_CLUSTER_NAME) String aksClusterName,
>       @Path(value = AzureConstants.FORMAT) String format);
> ```

Should be query
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 2391 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQA0ZX96hqlA57kEjy0:-NQA0ZX96hqlA57kEjy1:bdmpjhn) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2391)):*
> ```Java
>       exec = objectMapper.writeValueAsString(config.getExec()).replace("\n", "\n    ").stripTrailing();
>     } catch (JsonProcessingException ex) {
>       throw new InvalidRequestException("Unable to convert Exec to yaml", ex);
> ```

Let's provide a more meaning error, most probably customer will not be able to fix it if something wrong but at least to give context
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/Exec.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQA07nt64YX9Jxh2vFM:-NQA07nu3hUacoWQ3ID-:bqxumrs) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/Exec.java#L40)):*
> ```Java
> 
>   public static String getValueFromArgsList(List<String> args, String key) {
>     int apiServerIdIndex = args.indexOf(key);
> ```

should be keyIndex

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44939)* status: 32 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java` line 573 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQ9wsg88T3owd8G49Es:-NQegYLU032jLT1NHpJW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java#L573)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This can be userConfig.setExec(
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java` line 675 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQ9xty62D2hE5cmG2w_:-NQegZeDELkJbfLG19Zi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/930-delegate-tasks/src/main/java/software/wings/delegatetasks/azure/taskhelper/AzureAsyncTaskHelper.java#L675)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Not necessary as we provide our own constant value in updateAzureKubeconfig
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/azure/client/AzureKubernetesRestClient.java` line 28 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQ9zDYOBRLzyC_CC6Eq:-NQegdus0r_v3qB3rk4L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/960-api-services/src/main/java/io/harness/azure/client/AzureKubernetesRestClient.java#L28)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Should be query
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 2391 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQA0ZX96hqlA57kEjy0:-NQegfhc7MbdANs6Umyv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L2391)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's provide a more meaning error, most probably customer will not be able to fix it if something wrong but at least to give context
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/Exec.java` line 40 at r4](https://reviewable.io/reviews/harness/harness-core/44939#-NQA07nt64YX9Jxh2vFM:-NQeggqd1nq6k78DUN1h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b68200381d18195997f62c1289d212c5097d8bdb/970-api-services-beans/src/main/java/io/harness/k8s/model/kubeconfig/Exec.java#L40)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

should be keyIndex
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44939)* status: 32 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/azurecli/AzureCliClient.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/44939#-NQiSuoiAKduEIJ9xSAM:-NQiSuoiAKduEIJ9xSAN:b-ayolch) ([raw file](https://github.com/harness/harness-core/blob/0adcf6b134547d5ca44c47cf7e0d07748a23354b/960-api-services/src/main/java/io/harness/azurecli/AzureCliClient.java#L59)):*
> ```Java
>   }
> 
>   public static void loginToAksCluster(AzureConfig azureConfig, LogCallback logCallback) {
> ```

How this will work with multiple deployments running in parallel with different credentials?

**Comment by GoelPratyush99** [comment]
trigger ut8

**Comment by GoelPratyush99** [comment]
trigger ut9

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44939)* status: 32 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azurecli/AzureCliClient.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/44939#-NQiSuoiAKduEIJ9xSAM:-NQjVm4GC0J94gFI0YqH:bib7uoo) ([raw file](https://github.com/harness/harness-core/blob/0adcf6b134547d5ca44c47cf7e0d07748a23354b/960-api-services/src/main/java/io/harness/azurecli/AzureCliClient.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

How this will work with multiple deployments running in parallel with different credentials?
</blockquote></details>

This will taken as part of separate Story

**Comment by GoelPratyush99** [comment]
trigger ut2

**Comment by GoelPratyush99** [comment]
trigger ut5

**Comment by GoelPratyush99** [comment]
trigger ut6

**Comment by GoelPratyush99** [comment]
trigger ut1

**Review by abosii-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44939)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
