### PR TITLE
[fix]: [SRM-9115]: moving log analysis cluster from sequential  update to bulk update

### PR DESCRIPTION
**Pull request by deepak-harness**
…k update

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31735)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31735)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LogAnalysisCluster.java, line 120 at r2](https://reviewable.io/reviews/harness/harness-core/31735#-MyzDmwT5oCXmU9Yc-8e:-MyzDmwUBxRxJrNHdHDW:b-xft293) ([raw file](https://github.com/harness/harness-core/blob/6d0b369b540679a095c4a161890eb0cefda6d764/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LogAnalysisCluster.java#L120)):*
> ```Java
>     public <TDocument> BsonDocument toBsonDocument(Class<TDocument> aClass, CodecRegistry codecRegistry) {
>       BsonDocument bsonDocument = new BsonDocument();
>       bsonDocument.append("count", new BsonInt64(count));
> ```

nit: we can use lambok static keys also to avoid renaming issues.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TrendAnalysisServiceImpl.java, line 354 at r2](https://reviewable.io/reviews/harness/harness-core/31735#-MyzE4A0EARu81sVRlHM:-MyzE4A0EARu81sVRlHN:b-ia30fs) ([raw file](https://github.com/harness/harness-core/blob/6d0b369b540679a095c4a161890eb0cefda6d764/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TrendAnalysisServiceImpl.java#L354)):*
> ```Java
>       }
>     }
>     bulkWriteOperation.execute();
> ```

should we execute in the batches of some fixed number? Not sure if there is upper limit to bulkWriteOperation. Also writing too big operation might lead to timeout issues.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImplTest.java, line 222 at r2](https://reviewable.io/reviews/harness/harness-core/31735#-MyzEXDpE47r0765jY1o:-MyzEXDpE47r0765jY1p:b-e1x3r6) ([raw file](https://github.com/harness/harness-core/blob/6d0b369b540679a095c4a161890eb0cefda6d764/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImplTest.java#L222)):*
> ```Java
>   public void stressTestLogAnalysisCluster() {
>     Instant start = Instant.now();
>     Instant end = start.plus(1000, ChronoUnit.SECONDS);
> ```

can you put numbers also for this test?

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31735#-:-Mz-UQ6I5mzTdowQy9ka:bnfp4nl)* status: :shipit: complete! ✓

**Review by kjoshi12345 — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31735)* status: 0 of 1 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31735#-:-Mz-el6O1Y5ZF1NLX7xs:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
