### PR TITLE
[fix]:[CCM-10801]: EventTailer delegate fix

### PR DESCRIPTION
**Pull request by abhinavsingh-ccm**
## Describe your changes
The code changes required to enable receiving the K8S events from delegate for OnPrem setup. 
Earlier, ChronicleEventTailer is configured only in case of `SaaS` by enabling GRPC but now, for OnPrem we needed to initialise ChronicleEventTailer and also disabling GRPC.

Test Cases: 
1. Verified changes on OnPrem GCP/ AWS cluster.
2. Verified changes on SaaS as everything is working as before.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43029)

### CODE REVIEW

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43029)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
Can you please update both JIRA and PR description with why you are doing changes and how are you testing them. Neither has any useful info. 

> Reviewed 2 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43029#-:-NMi61Wi-rviznJwS5Lz:b-qi2glz)* status: :shipit: complete! ✓

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/43029#-NMi6oQT7-i53c-NltJW:-NMi6oQT7-i53c-NltJX:b-3vi0t3) ([raw file](https://github.com/harness/harness-core/blob/dca3ed9a02f326100b63cde70ce48a7d480525d6/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L107)):*
> ```Java
>     }
>     final Config appenderConfig = Config.builder().queueFilePath(configuration.getQueueFilePath()).build();
>     install(new AppenderModule(appenderConfig, () -> getDelegateId().orElse("UNREGISTERED")));
> ```

I think appender probably doesn't make sense without publisher. Would it be sensible to put this inside the above `if` statement?



_Code quote:_
```Java
    final Config appenderConfig = Config.builder().queueFilePath(configuration.getQueueFilePath()).build();
    install(new AppenderModule(appenderConfig, () -> getDelegateId().orElse("UNREGISTERED")));
    install(new EventPublisherModule());
```

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43029)* status: :shipit: complete! ✓

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/43029#-NMi6oQT7-i53c-NltJW:-NMi7ir29ESaChcPnrad:bkt1u94) ([raw file](https://github.com/harness/harness-core/blob/dca3ed9a02f326100b63cde70ce48a7d480525d6/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L107)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think appender probably doesn't make sense without publisher. Would it be sensible to put this inside the above `if` statement?
</blockquote></details>

Actually come to think of it, I probably tried doing this at some point, but it breaks Guice since appender injections are not optional.  You can ignore this request.

**Review by bharatgoelharness — COMMENTED** [review]
add the description in PR and test cases what all you have tested.

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43029#-:-NMmfyOEEpnzu0PSGtP5:b-6vpvyf)* status: 2 file(s) to review. 

___
*[`build.properties` line 3 at r4](https://reviewable.io/reviews/harness/harness-core/43029#-NMmezMkD7qHkROAPLE3:-NMmezMkD7qHkROAPLE4:bb5bfvd) ([raw file](https://github.com/harness/harness-core/blob/3a9830a59b9e25d039422895b68a9a1de9f36011/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=0
> build.number=78104
> ```

no need to change this

**Review by abhinavsingh-ccm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43029)* status: 3 file(s) to review. 1. unresolved discussions. 

___
*[`build.properties` line 3 at r4](https://reviewable.io/reviews/harness/harness-core/43029#-NMmezMkD7qHkROAPLE3:-NMmjt2wEEkTO6z5oN-p:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3a9830a59b9e25d039422895b68a9a1de9f36011/build.properties#L3)):*
<details><summary><i>Previously, bharatgoelharness (Bharat Goel) wrote…</i></summary><blockquote>

no need to change this
</blockquote></details>

Done

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43029)* status: 1. unresolved discussions.

**Pull request merged**
