### PR TITLE
[feat]: [CDS-35515]: Added Copy Templates Permission

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35928)

**Comment by utkarshchoubey-harness** [comment]
trigger ti1

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/35928#-NCcydxOBltNZNYMBmnj:-NCcydxOBltNZNYMBmnk:bedoeyh) ([raw file](https://github.com/harness/harness-core/blob/f9bbcdf1863392204a962b4b0b9e813ad77a9ae3/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L76)):*
> ```YAML
>         - core_template_edit
>         - core_template_copy
>         - core_template_view
> ```

Let the change in Managed Roles go along with Migration to add core_template_copy in all Custom created roles so that it is in sync.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928#-:-NCd-SU7E4kmeRLQ5wBp:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/35928#-NCcydxOBltNZNYMBmnj:-NCd-S107iAm0Dh0OmP-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9bbcdf1863392204a962b4b0b9e813ad77a9ae3/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L76)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Let the change in Managed Roles go along with Migration to add core_template_copy in all Custom created roles so that it is in sync.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928#-:-NCdoOFI6BfKabp1vvPr:bnfp4nl)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)* status: Some of the checks are too old.

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)* status: :shipit: complete! ✓

**Review by reetika04 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)* status: :shipit: complete! ✓

**Comment by Jimit09Gandhi** [comment]
trigger ti2

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35928)* status: :shipit: complete! ✓

**Pull request merged**
