### PR TITLE
feat: [CDS-86008]: Added support for Overlay Inputset CRUD/ Merge and Execution

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added support for Overlay Inputset CRUD/ Merge and Execution

Merge Inputsets
Request - 
{"input_set_references":["testover","otheris2"]}

testover is - 
```
version: 1
kind: input-set
spec:
  input-sets:
    - testis1
    - testis2
  fieldB: priorB
  fieldC: priorC 
```

otheris2 is - 
```
version: 1
kind: input-set
spec:
  fieldA: otheris2
```

testis1 is 
```
version: 1
kind: input-set
spec:
  fieldA: testA1
  fieldB: testB1
  fieldC: testC1
```

testis2 is 
```
version: 1
kind: input-set
spec:
  fieldA: testA2
  fieldD: testD2
```

Response - 
```
{
    "inputs_yaml_merged": "fieldA: otheris2\nfieldB: priorB\nfieldC: priorC\nfieldD: testD2\n",
    "merged_pipeline_yaml": "",
    "is_error_response": false,
    "inputset_error_wrapper": null
}
```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/56386#-NkyR7rOAgE5EqtGi1am:-NkyR7rOAgE5EqtGi1an:b-m63kl) ([raw file](https://github.com/harness/harness-core/blob/b6bbfd32925a40cdfa6268a77124c84de8919be6/953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java#L105)):*
> ```Java
> 
>   public final String INPUT_SET_REFERENCES = "inputSetReferences";
>   public final String INPUT_SETS = "input-sets";
> ```

input_sets
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/56386#-NkyUEp-D5LJYRmsp4yj:-NkyUEp-D5LJYRmsp4yk:b-bwlnro) ([raw file](https://github.com/harness/harness-core/blob/b6bbfd32925a40cdfa6268a77124c84de8919be6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L325)):*
> ```Java
>     List<JsonNode> inputSetJsonNodeList = new ArrayList<>();
>     Set<String> inputSetVersions = new HashSet<>();
>     List<JsonNode> overlayInputSetPriorityMergeJsonNode = new ArrayList<>();
> ```

as discussed not needed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 351 at r2](https://reviewable.io/reviews/harness/harness-core/56386#-NkySv5h4t54Plulnv2t:-NkySv5iCr1q0S0H_97E:bmk62ky) ([raw file](https://github.com/harness/harness-core/blob/b6bbfd32925a40cdfa6268a77124c84de8919be6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L351)):*
> ```Java
>             });
>           }
>         } else {
> ```

add else if for v1

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/56386#-NkyR7rOAgE5EqtGi1am:-Nkyo5MXByOL5_P-KQG1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6bbfd32925a40cdfa6268a77124c84de8919be6/953-yaml-commons/src/main/java/io/harness/pms/yaml/YAMLFieldNameConstants.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

input_sets
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 325 at r2](https://reviewable.io/reviews/harness/harness-core/56386#-NkyUEp-D5LJYRmsp4yj:-Nkyo6-6ECVCgM4qwvMa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6bbfd32925a40cdfa6268a77124c84de8919be6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L325)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed not needed
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 351 at r2](https://reviewable.io/reviews/harness/harness-core/56386#-NkySv5h4t54Plulnv2t:-Nkyo6WIEk8rytSyLzjO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6bbfd32925a40cdfa6268a77124c84de8919be6/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L351)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add else if for v1
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 374 at r5](https://reviewable.io/reviews/harness/harness-core/56386#-Nkywdvk2RaAzFqjt4hd:-Nkywdvk2RaAzFqjt4he:b-ibodia) ([raw file](https://github.com/harness/harness-core/blob/b4a7b6235fed3921718233e9813d560b87892b95/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L374)):*
> ```Java
>   }
> 
>   private JsonNode getOverlayInputSetInputs(JsonNode inputSetNode) {
> ```

discussed few changes to optimise
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 396 at r5](https://reviewable.io/reviews/harness/harness-core/56386#-Nkyvw3TAH7O7LZyozBf:-Nkyvw3TAH7O7LZyozBg:bg6cv4m) ([raw file](https://github.com/harness/harness-core/blob/b4a7b6235fed3921718233e9813d560b87892b95/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L396)):*
> ```Java
>   }
> 
>   List<JsonNode> getOverlayInputSetReferences(JsonNode inputSetNode, String accountId, String orgIdentifier,
> ```

return input set versions as well
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 398 at r5](https://reviewable.io/reviews/harness/harness-core/56386#-Nkyw-MdAss7RvsCUhZO:-Nkyw-MdAss7RvsCUhZP:b-1cbsv8) ([raw file](https://github.com/harness/harness-core/blob/b4a7b6235fed3921718233e9813d560b87892b95/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L398)):*
> ```Java
>   List<JsonNode> getOverlayInputSetReferences(JsonNode inputSetNode, String accountId, String orgIdentifier,
>       String projectIdentifier, String pipelineIdentifier, boolean loadFromCache, PipelineEntity pipelineEntity) {
>     List<JsonNode> overlayReferences = new ArrayList<>();
> ```

linkedList

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 359 at r6](https://reviewable.io/reviews/harness/harness-core/56386#-Nl6wkHV6zW_A4atsaXP:-Nl6wkHV6zW_A4atsaXQ:bkftwxb) ([raw file](https://github.com/harness/harness-core/blob/397da3bc783999809f4a390133b6b27da8997503/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L359)):*
> ```Java
>             }
>           } else {
>             inputSetJsonNodeList.add(YamlUtils.readAsJsonNode(inputSet.getYaml()));
> ```

We already have created the inputJsonNode above. No need to read yaml to jsonNode again.



_Code quote:_
```Java
YamlUtils.readAsJsonNode(inputSet.getYaml()
```

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 400 at r6](https://reviewable.io/reviews/harness/harness-core/56386#-Nl70Xqz3kTGR93r8Pz4:-Nl70Xqz3kTGR93r8Pz5:b1u9pdw) ([raw file](https://github.com/harness/harness-core/blob/397da3bc783999809f4a390133b6b27da8997503/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L400)):*
> ```Java
>             inputSetEntity.ifPresent(inputSetElement -> {
>               checkAndThrowExceptionWhenPipelineAndInputSetStoreTypesAreDifferent(pipelineEntity, inputSetEntity.get());
>               inputSetVersions.add(inputSetElement.getHarnessVersion());
> ```

we should not modify the inputSetversion in same method, we should return it

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56386)* status: <span>:shipit:</span> complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 401 at r7](https://reviewable.io/reviews/harness/harness-core/56386#-Nl7Gh38CIRtVTSgYorU:-Nl7Gh38CIRtVTSgYorV:b-d6pokb) ([raw file](https://github.com/harness/harness-core/blob/d5e7248a13ee6b3aa4165eb1705a983ac738858e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L401)):*
> ```Java
>           ArrayNode overlayInputSetReferences = (ArrayNode) inputSetsList;
>           for (JsonNode inputSetItem : overlayInputSetReferences) {
>             Optional<InputSetEntity> inputSetEntity = pmsInputSetService.getWithoutValidations(accountId, orgIdentifier,
> ```

nit: as optimisation we can fetch all input-sets at once. Currently there is no method for fetching list of input-sets for given ids. This will be done for V0 as well.

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
