### PR TITLE
fix: [DEL-3922]: startup script changes to pick watcher version from manager

### PR DESCRIPTION
**Pull request by gaurav-jain1**
Summary:
Changes to fetch watcher version from manager.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1370 at r2](https://reviewable.io/reviews/harness/harness-core/33957#-N4a5MyNEQogJX67viFv:-N4a5MyNEQogJX67viFw:b-joerho) ([raw file](https://github.com/harness/harness-core/blob/d5e59d45045c07af1aea281d745ca737785c9e06/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1370)):*
> ```Java
>                       DELEGATE_ENABLE_DYNAMIC_HANDLING_OF_REQUEST, templateParameters.getAccountId())));
> 
>       if (useCDN) {
> ```

don't use useCDN

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/delegatetemplates/start.sh.ftl` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/33957#-N4a5VAP2119TIi_7CtG:-N4a5VAP2119TIi_7CtH:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/d5e59d45045c07af1aea281d745ca737785c9e06/400-rest/src/main/resources/delegatetemplates/start.sh.ftl#L132)):*
> ```FreeMarker
> export DEPLOY_MODE=${deployMode}
> 
> <#if useCdn == "true">
> ```

same here

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/delegatetemplates/start.sh.ftl` line 143 at r2](https://reviewable.io/reviews/harness/harness-core/33957#-N4a62Je2yZRmtfn3oCb:-N4a62Je2yZRmtfn3oCc:b-7xbcgl) ([raw file](https://github.com/harness/harness-core/blob/d5e59d45045c07af1aea281d745ca737785c9e06/400-rest/src/main/resources/delegatetemplates/start.sh.ftl#L143)):*
> ```FreeMarker
> </#if>
> 
> if [ ! -e watcher.jar ]; then
> ```

include the change in container's start.sh

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: 0 of 1 approvals obtained.

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: :shipit: complete! ✓

**Review by arpit3107 — DISMISSED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: :shipit: complete! ✓

**Review by AnupamIO — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: :shipit: complete! ✓

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: :shipit: complete! ✓

**Review by AnupamIO — APPROVED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33957)* status: :shipit: complete! ✓

**Comment by sunilgupta-harness** [comment]
Merging since all checks are passed.

**Pull request merged**
