### PR TITLE
fix: [CDS-44478]: Ntlm and Kerberos are registered with same criteria

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38664)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38664)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/executioncapability/WinrmConnectivityExecutionCapability.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/38664#-NE6BlQ73CVx7ff44_Uh:-NE6BlQ82S0IUpxBgMRn:btk4ykx) ([raw file](https://github.com/harness/harness-core/blob/e4ea906c10182999c138636b49768ba875620c46/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/executioncapability/WinrmConnectivityExecutionCapability.java#L55)):*
> ```Java
>     }
> 
>     if (winRmInfraDelegateConfig.getWinRmCredentials().getAuth().getAuthScheme() == WinRmAuthScheme.Kerberos) {
> ```

Do we need NTLM suffix to differentiate between non-kerberos ssh hosts and WinRm NTLM?

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38664)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/executioncapability/WinrmConnectivityExecutionCapability.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/38664#-NE6BlQ73CVx7ff44_Uh:-NE6eQlRDfXF8CBULRvz:b6alikp) ([raw file](https://github.com/harness/harness-core/blob/e4ea906c10182999c138636b49768ba875620c46/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/executioncapability/WinrmConnectivityExecutionCapability.java#L55)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need NTLM suffix to differentiate between non-kerberos ssh hosts and WinRm NTLM?
</blockquote></details>

No, we don't. In CG also don't use

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38664)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
