### PR TITLE
[fix]: [CDS-33716]: lazy updating secrets cache

### PR DESCRIPTION
**Pull request by lasdox**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34988)

### CODE REVIEW

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34988)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/security/SecretManagerImplTest.java` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/34988#-N69XWml5p_dy6bvM9qd:-N69XWmmC2IFEehOYcTj:b-op1hts) ([raw file](https://github.com/harness/harness-core/blob/eea7749684227a877e91db72a0508a322de33aa7/400-rest/src/test/java/software/wings/service/impl/security/SecretManagerImplTest.java#L375)):*
> ```Java
>   @Owner(developers = LUCAS_SALES)
>   @Category(UnitTests.class)
>   public void testUpdateSecretText_shouldInvalidateCache() {
> ```

Please, add the case when the cache keeps without change.

**Comment by lasdox** [comment]
> > Reviewed 1 of 2 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/34988)_ status: 1 file(s) to review. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/test/java/software/wings/service/impl/security/SecretManagerImplTest.java` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/34988#-N69XWml5p_dy6bvM9qd:-N69XWmmC2IFEehOYcTj:b-op1hts) ([raw file](https://github.com/harness/harness-core/blob/eea7749684227a877e91db72a0508a322de33aa7/400-rest/src/test/java/software/wings/service/impl/security/SecretManagerImplTest.java#L375)):_
> 
> > ```java
> >   @Owner(developers = LUCAS_SALES)
> >   @Category(UnitTests.class)
> >   public void testUpdateSecretText_shouldInvalidateCache() {
> > ```
> 
> Please, add the case when the cache keeps without change.

The code is written in a way that every request will update the secret, even if is same values.
So the cache will be invalidated every time.
I think I will keep the updated check for semantics, as the code is written this way

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34988)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34988)* status: :shipit: complete! ✓

**Pull request merged**
