### PR TITLE
feat: [CDS-54457]: Adding InstanceSyncPerpetualTaskMapping collection for NG instance sync V2

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45352)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 19 files at r1, 6 of 6 files at r2, 6 of 9 files at r4, 4 of 5 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45352)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`126-instance/src/main/java/io/harness/entities/InstanceSyncPerpetualTaskMapping.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/45352#-NQySBy2ByQdzRfQdEnP:-NQySBy66mHCGc_ynzGo:b5ph4ai) ([raw file](https://github.com/harness/harness-core/blob/b1613d767b8d9ad13c68a80d6eb71ae0a2e11bac/126-instance/src/main/java/io/harness/entities/InstanceSyncPerpetualTaskMapping.java#L48)):*
> ```Java
> 
>   @Id @dev.morphia.annotations.Id String id;
>   String connectorIdentifier;
> ```

We need to account, org and project of the connector
___
*[`126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustom.java` line 2 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2X1aj8bZZjnHOeJdZ:-NR2X1aj8bZZjnHOeJd_:bb6ht38) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustom.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

2023
___
*[`126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustom.java` line 16 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2X8B-CBUs_bRx3ptp:-NR2X8B-CBUs_bRx3ptq:b8zw69k) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustom.java#L16)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public interface InstanceSyncPerpetualTaskMappingRepositoryCustom {
>   InstanceSyncPerpetualTaskMapping findByConnectorRef(
> ```

nit: this can return Optional
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 95 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2XigS-XbDyNywnQ7G:-NR2XigS-XbDyNywnQ7H:b4g8xow) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L95)):*
> ```Java
> 
>   @Inject
>   public InstanceSyncServiceImpl(PersistentLocker persistentLocker,
> ```

nit: let's remove this inject through constructor and add inject to each field
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 222 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2Xz3j3y8ueme9EwtX:-NR2Xz3j3y8ueme9EwtY:b4a4ex7) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L222)):*
> ```Java
>       ConnectorInfoDTO connectorInfoDTO = connectorDTO.get().getConnector();
> 
>       if (instanceSyncPerpetualTaskMappingService
> ```

Optional<InstanceSyncPerpetualTaskMapping> instanceSyncPerpetualTaskMapping = findByConnectorRef()
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 236 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2YmkvDhqzatEwZmX2:-NR2YmkvDhqzatEwZmX3:b-5jehka) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L236)):*
> ```Java
>       }
>     } else {
>       log.error(
> ```

Let's throw an exception instead

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45352)* status: 21 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/entities/InstanceSyncPerpetualTaskMapping.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/45352#-NQySBy2ByQdzRfQdEnP:-NR3_B4m4ZnbYdYLrzq_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b1613d767b8d9ad13c68a80d6eb71ae0a2e11bac/126-instance/src/main/java/io/harness/entities/InstanceSyncPerpetualTaskMapping.java#L48)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We need to account, org and project of the connector
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustom.java` line 2 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2X1aj8bZZjnHOeJdZ:-NR3_Bn079P-Lm_Gar95:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/repositories/instanceSyncPerpetualTaskMapping/InstanceSyncPerpetualTaskMappingRepositoryCustom.java#L2)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

2023
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 222 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2Xz3j3y8ueme9EwtX:-NR3_ExXAdfM_QdqSPve:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L222)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Optional<InstanceSyncPerpetualTaskMapping> instanceSyncPerpetualTaskMapping = findByConnectorRef()
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 236 at r7](https://reviewable.io/reviews/harness/harness-core/45352#-NR2YmkvDhqzatEwZmX2:-NR3_Fv2COQc-dwEoiBe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/223286a7e106d56b9513c2d2984c6df3436a5aa1/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L236)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's throw an exception instead
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 10 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45352)* status: 21 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 6 of 19 files at r1, 1 of 6 files at r2, 2 of 9 files at r4, 1 of 5 files at r5, 10 of 11 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45352)* status: Waiting on team(s): k8s-team.

**Pull request merged**
