### PR TITLE
Feat: [SRM-13727]: Handle all monitored services in downtime

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43156)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43156)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/AllEntitiesRule.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/43156#-NN_NY2dCR3m_os0lcjh:-NN_NY2dCR3m_os0lcji:b-8ps0n8) ([raw file](https://github.com/harness/harness-core/blob/09b05b62707d2d2806a24a92f1a7d7fd0b6a6de6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/AllEntitiesRule.java#L28)):*
> ```Java
>   @Override
>   public AffectedEntity getAffectedEntity() {
>     return AffectedEntity.builder().serviceRef("ALL").envRef("ALL").build();
> ```

nit: let's declare ALL as constant. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/EntitiesRule.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/43156#-NN_NkU8DbOzWlvvx7KO:-NN_NkU8DbOzWlvvx7KP:bhsvfjg) ([raw file](https://github.com/harness/harness-core/blob/09b05b62707d2d2806a24a92f1a7d7fd0b6a6de6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/EntitiesRule.java#L34)):*
> ```Java
>   public abstract boolean isPresent(Map<String, String> entityDetailsMap);
> 
>   public AffectedEntity getAffectedEntity() {
> ```

let's return optional in case it can be null.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 4 of 7 files at r3, 4 of 7 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43156)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Pull request merged**
