### PR TITLE
[feat]: [CDS-44502]: ServiceV2 S3 changes

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38513)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 1 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38513)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/S3BucketResource.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/38513#-NDmbkIT-9ZF5XsBO8pk:-NDmbkIT-9ZF5XsBO8pl:b-2q1mn9) ([raw file](https://github.com/harness/harness-core/blob/23b3ef231a60f07f1daff6790529637f6cbe6d76/120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/S3BucketResource.java#L208)):*
> ```Java
>   @ApiOperation(value = "Gets s3 file paths", nickname = "getFilePathsV2ForS3")
>   public ResponseDTO<List<FilePathDTO>> getFilePathsForServiceV2(@QueryParam("region") String region,
>       @NotNull @QueryParam("connectorRef") String awsConnectorIdentifier,
> ```

if connector is runtime, UI will not be able to send this. you can check the getBuildDetailsV2 APIs for this or we can sync offline

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/S3BucketResource.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/38513#-NDmbZnv3GxKt8xIKFq9:-NDmbZnv3GxKt8xIKFqA:b-dpdl00) ([raw file](https://github.com/harness/harness-core/blob/23b3ef231a60f07f1daff6790529637f6cbe6d76/120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/S3BucketResource.java#L205)):*
> ```Java
> 
>   @POST
>   @Path("getFilePathsV2")
> ```

lets call v2/getFilePaths
We did not follow this pattern at multiple places, good to follow this versioning scheme now

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38513)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/S3BucketResource.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/38513#-NDmbkIT-9ZF5XsBO8pk:-NDsFtiS6-WxpnB-2Ue1:b-l1shc8) ([raw file](https://github.com/harness/harness-core/blob/23b3ef231a60f07f1daff6790529637f6cbe6d76/120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/S3BucketResource.java#L208)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if connector is runtime, UI will not be able to send this. you can check the getBuildDetailsV2 APIs for this or we can sync offline
</blockquote></details>

Yes. Made the change.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38513)* status: :shipit: complete! ✓

**Pull request merged**
