### PR TITLE
[fix]: [PIE-8689]: Fixing multi-deployment nodes status coming success even when the node was skipped because prior stage failed

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Fixing multi-deployment nodes status coming success even when the node was skipped because prior stage failed.

Issue: When all statuses in the responseMap are SKIPPED then the calculateStatus returns the SUCCEEDED. 

Fix: Checking if all status in responoseMap are skipped then set the status as SKIPPED and return the stepResponse  because its skipped so no failureInfo will be available. So we can return here.
Please check the below screenshots before and after fix.
Screenshot 2023-03-02 at 12 40 54 PM

Screenshot 2023-03-02 at 12 41 14 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44592)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/44592#-NPWXLBr6AZpZuwBSNAW:-NPWXLBr6AZpZuwBSNAX:b-w67axc) ([raw file](https://github.com/harness/harness-core/blob/d28ea66a379594c8abb61f9ccb006e88288938eb/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L97)):*
> ```Java
>     if (StatusUtils.checkIfAllChildrenSkipped(responseDataMap.values()
>                                                   .stream()
>                                                   .map(o -> ((StepResponseNotifyData) o).getStatus())
> ```

can "o" always be cast to "StepResponseNotifyData"

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44592)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/44592#-NPWXLBr6AZpZuwBSNAW:-NPWYAe2DiapoqjSwJqn:b-7nh0hb) ([raw file](https://github.com/harness/harness-core/blob/d28ea66a379594c8abb61f9ccb006e88288938eb/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L97)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can "o" always be cast to "StepResponseNotifyData" 
</blockquote></details>

Yes, it will always be StepResponseNotifyData because this responseData is sent by orchestrationEngine when the children nodeExecutions were finished. And orchestrationEngine sends this StepResponseNotifyData only to the waitNotify engine.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44592)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44592)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44592)* status: :shipit: complete! ✓

**Pull request merged**
