### PR TITLE
[feat]: [PL-24881]: Adding ValidationProject field for ADO connector

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32748)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger ti0

**Comment by mankrit-singh** [comment]
trigger codeformat

**Comment by mankrit-singh** [comment]
trigger ti0

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32748#-:-N1Hjh33Aig52ZZas7al:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32748#-:-N1HldKtAWkbuzKEPIm6:bnfp4nl)* status: 15 file(s) to review.

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32748)* status: :shipit: complete! ✓

**Pull request merged**
