### PR TITLE
feat: [cds-49192]: Added Separate schema for stepGroup

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added Separate schema for stepGroup templates
We will be passing yamlGroup as STEP_GROUP and we will create the STEP_GROUP schema from the stage schema by changing the root properties to stepGroup and pointing the ref to corresponding stepGroupElementConfig and keeping $schema, definitions and type from the stage schema.
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42210)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/42210#-NKwAuUU6D0sBTmQ_bMc:-NKwAuUU6D0sBTmQ_bMd:b-b3y9o5) ([raw file](https://github.com/harness/harness-core/blob/2596fa1b53f5fc12c33ae63160ed745b57cf58cf/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L365)):*
> ```Java
>     JsonNode mergedDefinition = null;
>     Map<String, JsonNode> finalNameSpaceToDefinitionMap = new HashMap<>();
>     if (StepCategory.STAGE.toString().equals(yamlGroup) || StepCategory.STEP_GROUP.toString().equals(yamlGroup)) {
> ```

can we organize the code like this ?
```
if (yamlGroup == STAGE) {
  generateSchemaForStage(..)
} else if (yamlGroup == STEP_GROUP) {
   s = generateSchemaForStage(..)
   convertToStepGroupSchema(s)
}
```

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42210)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42210#-NKwfS8UDN2hY40kjuvr:-NKwfS8VE4_S3NQqHCu9:bwicvq8) (no related file):*
As discussed offline, we need to revisit our strategy. 
We should pick selective fields from the stage schema

___

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42210)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42210#-NKwfS8UDN2hY40kjuvr:-NKwivP-Dll-b4BQKdqR:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

As discussed offline, we need to revisit our strategy. 
We should pick selective fields from the stage schema
</blockquote></details>

Done.

___

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42210)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42210)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42210)* status: :shipit: complete! ✓

**Pull request merged**
