### PR TITLE
feat: [CDS-78680]: support get service header for remote services

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
allow git params to be passed in the request for getServiceHeaderInfo API 
improve service not found error message 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52449)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/52449#-NdZnbv92oPidRpBosSb:-NdZnbv92oPidRpBosSc:bs6ynp6) ([raw file](https://github.com/harness/harness-core/blob/476973970cfd682c905fd0adc168b11b8da5c989/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java#L164)):*
> ```Java
> 
>   ServiceHeaderInfo getServiceHeaderInfo(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String serviceId, boolean loadFromCache, boolean loadFromFallbackBranch);
> ```

does this method need to aware if Service is in Git ?

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52449)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/52449#-NdZnbv92oPidRpBosSb:-NdZr2X49Yk-Go8FG44T:bqssyoi) ([raw file](https://github.com/harness/harness-core/blob/476973970cfd682c905fd0adc168b11b8da5c989/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java#L164)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this method need to aware if Service is in Git ?
</blockquote></details>

It is done this way to allow UI the flexibility to provide the git related params. By default these are set to false.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52449)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/52449#-NdZmRGE5PdU1lzWw0eH:-NdZyWJpDwPpDf5TlMdy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/476973970cfd682c905fd0adc168b11b8da5c989/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L83)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets not use wildcard import
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/52449#-NdZnbv92oPidRpBosSb:-NdZyX2F79v2OXB0h_jP:bf72rm0) ([raw file](https://github.com/harness/harness-core/blob/476973970cfd682c905fd0adc168b11b8da5c989/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java#L164)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

It is done this way to allow UI the flexibility to provide the git related params. By default these are set to false.
</blockquote></details>

Removed this Params for now. Done.

**Review by rafaelmart1ns — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52449)* status: 5 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52449)* status: 5 file(s) to review.

**Pull request merged**
