### PR TITLE
feat: [SRM-11745]: Adding dataCollectionInfo, corresponding mapper, UTs and DSL.

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37582)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37582)

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37582)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CloudWatchMetricHealthSourceSpecTransformer.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/37582#-NC05EUp3_Ye-yxiK-ZC:-NC05EUp3_Ye-yxiK-ZD:b-pi9877) ([raw file](https://github.com/harness/harness-core/blob/82c4ccf327b0f8dc0d90744940a0a5dc9969ac0c/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/monitoredService/CloudWatchMetricHealthSourceSpecTransformer.java#L71)):*
> ```Java
>       cloudWatchMetricDefinitions.add(cloudWatchMetricDefinition);
>     }));
>     // TODO: Check if thresolds are getting transformed properly.
> ```

remove todo
___
*[`300-cv-nextgen/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/37582#-NC06OuH1L3HvO2dBdVk:-NC06OuH1L3HvO2dBdVl:b-k1nxpr) ([raw file](https://github.com/harness/harness-core/blob/82c4ccf327b0f8dc0d90744940a0a5dc9969ac0c/300-cv-nextgen/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection#L31)):*
> ```
>             Var timestamp = Var:timeseries[Var:index]
>             if Env:collectHostData != "true" {
>                 Var tsRecord = new TimeseriesRecord(txnName=Env:groupName, metricIdentifier=Var:metricIdentifier, metricName=Var:metricName, metricValue=Var:value, timestamp=Var:timestamp)
> ```

This should be metric_name and metric_identifier from user, 
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/utils/CloudWatchUtils.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/37582#-NC04f5j4o93sA6b8FIw:-NC04f5j4o93sA6b8FIx:bn8hl8r) ([raw file](https://github.com/harness/harness-core/blob/82c4ccf327b0f8dc0d90744940a0a5dc9969ac0c/948-cv-nextgen-beans/src/main/java/io/harness/cvng/utils/CloudWatchUtils.java#L50)):*
> ```Java
>   }
> 
>   public static Map<String, Object> getDslEnvVariables(String region, String group, String expression,
> ```

Sample request use a different function.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37582)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger codebasehash

**Pull request merged**
