### PR TITLE
fix: [PL-23803]: check style check fix

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31476)

### CODE REVIEW

**Review by DFieldFL — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31476)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Comment by shashank-harness** [comment]
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 514 at r1](https://reviewable.io/reviews/harness/harness-core/31476#-MyD94Bn0zdOfIdJmgfc:-MyD94Bn0zdOfIdJmgfd:b-db2uci) ([raw file](https://github.com/harness/harness-core/blob/1ca7a6390199532fa1bf98b3583b5a383464e653/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L514)):*
> ```Java
>       vaultNames = listVaultsInternal(accountIdentifier, azureVaultConfig);
>     } catch (WingsException wingsException) {
>       log.error("Listing vaults failed for account Id {}", accountIdentifier, wingsException);
> ```

Dont remove the complete log line.
Just remove exception from logging. Like this: 
log.error("Listing secret engines failed for account Id {}", baseVaultConfig.getAccountId());

**Review by boopesh007 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31476)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 514 at r1](https://reviewable.io/reviews/harness/harness-core/31476#-MyD9AtUE8p2LywS0MiF:-MyD9AtUE8p2LywS0MiG:b3mrzy2) ([raw file](https://github.com/harness/harness-core/blob/1ca7a6390199532fa1bf98b3583b5a383464e653/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L514)):*
> ```Java
>       vaultNames = listVaultsInternal(accountIdentifier, azureVaultConfig);
>     } catch (WingsException wingsException) {
>       log.error("Listing vaults failed for account Id {}", accountIdentifier, wingsException);
> ```

Dont remove the complete log line.
Just remove exception from logging. Like this: 
log.error("Listing vaults failed for account Id {}", accountIdentifier);

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31476)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31476)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by DFieldFL — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31476)* status: :shipit: complete! ✓

**Pull request merged**
