### PR TITLE
feat: [DEL-4551]: download correct JVM based on arch

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
Shell delegates should download the correct jre based on the arch and the os type. This is needed as we are moving towards  supporting multi-arch delegates.

Scenarios tested:
1. Install shell delegate in mac amd64 machine.
2. install shell delegate in linux amd64 machine.
3. install shell delegate in linux arm64 machine.
4. install k8s delegate in linux amd64 machine.
5. shell delegate upgrade by only updating the manager.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38837)

### CODE REVIEW

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38837)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/38837#-NE_ipTu6LiEHVxpsGMd:-NE_ipTu6LiEHVxpsGMe:b-dpx8yj) ([raw file](https://github.com/harness/harness-core/blob/8d41afaedff7e839086c840acf1f3f3094ec198a/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L52)):*
> ```FreeMarker
>   x86_64*)
>     ARCH=x64
>     ;;
> ```

Do we need to break from here and other cases too ?
___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/38837#-NE_ivSQ9Ty0mAeGLASC:-NE_ivSQ9Ty0mAeGLASD:b-h8w8x7) ([raw file](https://github.com/harness/harness-core/blob/8d41afaedff7e839086c840acf1f3f3094ec198a/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L71)):*
> ```FreeMarker
> <#if useCdn == "true">
>   <#noparse>
>     JVM_URL=$DELEGATE_STORAGE_URL/public/shared/jre/openjdk-11.0.14_9/OpenJDK11U-jre_${ARCH}_${OS}_hotspot_11.0.14_9.tar.gz
> ```

I don't see default value for ARCH being set



_Code quote:_
```FreeMarker
ARCH
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38837)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/38837#-NE_ipTu6LiEHVxpsGMd:-NEjHYPP7P1q9uesd4pZ:b-6gbkhj) ([raw file](https://github.com/harness/harness-core/blob/8d41afaedff7e839086c840acf1f3f3094ec198a/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L52)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Do we need to break from here and other cases too ?
</blockquote></details>

yes, or switch control will come at last default case also.
___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/38837#-NE_ivSQ9Ty0mAeGLASC:-NEjHevg7yiNzvwVO4d4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8d41afaedff7e839086c840acf1f3f3094ec198a/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L71)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I don't see default value for ARCH being set
</blockquote></details>

done

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38837)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/38837#-NE_ipTu6LiEHVxpsGMd:-NEjRLN2-jSi7-yR2cGT:b5ymzjz) ([raw file](https://github.com/harness/harness-core/blob/8d41afaedff7e839086c840acf1f3f3094ec198a/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L52)):*
>  switch control will come at last default cas
ok ;; signifies break
___
*[`400-rest/src/test/resources/expectedStartOpenJdk.sh` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/38837#-NEjRBbj6G56XcufLZsu:-NEjRBbj6G56XcufLZsv:b-vwwefn) ([raw file](https://github.com/harness/harness-core/blob/7f6ddd151591fd217a295c330372fc2b8442973d/400-rest/src/test/resources/expectedStartOpenJdk.sh#L64)):*
> ```Shell
>   *)
>     echo "unknown architecture $(uname -m). Proceeding as amd64 arch"
>     ;;
> ```

ditto here. 



_Code quote:_
```Shell
;;
```
___
*[`400-rest/src/test/resources/expectedStopOpenJdk.sh` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/38837#-NEjRFsu-qAv6ex-m6Wx:-NEjRFsu-qAv6ex-m6Wy:bps1s89) ([raw file](https://github.com/harness/harness-core/blob/7f6ddd151591fd217a295c330372fc2b8442973d/400-rest/src/test/resources/expectedStopOpenJdk.sh#L64)):*
> ```Shell
>   *)
>     echo "unknown architecture $(uname -m). Proceeding as amd64 arch"
>     ;;
> ```

here too



_Code quote:_
```Shell
;;
```

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38837)* status: :shipit: complete! ✓

**Pull request merged**
