### PR TITLE
feat: [PL-41188]: List api to accept a set of entity types for referredByEntityType filter

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
This PR rectifies the "referredByEntityType" filter for NG entity activity list API- "@get /activityHistory".
Currently, this filter only takes a single value. This PR enhances it to accept a list of allowed entity types. 

Testing:-
1. Verified that only the specified entity types are returned when the filter is populated.
2. Verified that all entities are returned when the filter is empty.
3. Verified that the change is backward compatible.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52746)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52746)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/52746#-NeMCr8RDeNsoUXKcPHH:-NeMCr8RDeNsoUXKcPHI:b-oyp5au) ([raw file](https://github.com/harness/harness-core/blob/936ef1bbfdc3066e147b8cce764613b4252f26e4/950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java#L74)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.STATUS) NGActivityStatus status,
>       @NotNull @QueryParam(NGCommonEntityConstants.REFERRED_ENTITY_TYPE) EntityType referredEntityType,
>       @QueryParam(NGCommonEntityConstants.REFERRED_BY_ENTITY_TYPE) Set<EntityType> referredByEntityTypes,
> ```

Is this backward compatible? Will this not change the api contract?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52746)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/52746#-NeMCr8RDeNsoUXKcPHH:-NeMZCOB3DjZx6EHWkPy:b-j8zc4z) ([raw file](https://github.com/harness/harness-core/blob/936ef1bbfdc3066e147b8cce764613b4252f26e4/950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java#L74)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Is this backward compatible? Will this not change the api contract?
</blockquote></details>

Yes, this will be backward compatible because this will work fine even if a single value is passed as a parameter. API contract with UI will not change as such because the way the single query param is passed, will continue to work as it is.  
However, the types on UI will change, which will be updated by the UI team simultaneously.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52746)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
