### PR TITLE
feat: [PL-29117]: fix for ng secret list query timing out

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Removed unnecessary db call to list secrets again.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/39887#-NGWCLDX4xXSEW9Q1m8H:-NGWCLDX4xXSEW9Q1m8I:b-26u7p2) ([raw file](https://github.com/harness/harness-core/blob/89037c54fba268849550c3f9beb8a43df9d1923c/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L131)):*
> ```Java
>   }
> 
>   public static <T> Page<T> getPage(List<T> input, int offset, int pageSize) {
> ```

we should have some assertions on the arguments eg: offset cannot be < 0, pageSize cannot be < 0 or similar. As its quite basic utility class which may be used across multiple functionalities, good to have such checks.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — DISMISSED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: :shipit: complete! ✓

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java` line 372 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGWZyf8AftKE53GVB9Q:-NGWZyf8AftKE53GVB9R:bww1ljm) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java#L372)):*
> ```Java
> 
>   @Override
>   public Page<Secret> getPaginatedResult(List<Secret> unpagedSecrets, int page, int size) {
> ```

No need to change method name here i think.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java` line 376 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_A2K2aKWCCPd01w3:-NGW_A2K2aKWCCPd01w4:be2qsfd) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java#L376)):*
> ```Java
>       return Page.empty();
>     }
>     List<Secret> secrets = new ArrayList<>(unpagedSecrets);
> ```

Do we need to do this?
___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_h8WEsugVtKS1XBr:-NGW_h8WEsugVtKS1XBs:b2d3gvx) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L131)):*
> ```Java
>   }
> 
>   public static <T> Page<T> getPage(List<T> input, int offset, int pageSize) {
> ```

Can we use https://stackoverflow.com/a/37771947 instead of writing the logic ourselves?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 1 change requests. 3. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java` line 372 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGWZyf8AftKE53GVB9Q:-NGWkzJm3UzOwN_zLAKl:b-albav5) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java#L372)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need to change method name here i think.
</blockquote></details>

this method is only converting list of secrets to page
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java` line 376 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_A2K2aKWCCPd01w3:-NGWkhFnBkTEO2jGmJ-t:bz7l33i) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretServiceV2Impl.java#L376)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need to do this?
</blockquote></details>

yes, the list that is coming is unmodifiable and that is throwing error, that's why need to creatae a new list.
___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_h8WEsugVtKS1XBr:-NGWkrS-D-LyJ40r_vRD:bde2zrp) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L131)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we use https://stackoverflow.com/a/37771947 instead of writing the logic ourselves?
</blockquote></details>

@ankit-harness this doc is showing the same thing finding sublist as I have done

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_h8WEsugVtKS1XBr:-NGWnZCjBWaO3BlmSB78:b-qw2ysb) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L131)):*
> https://stackoverflow.com/a/37771947

Make sure if conditions don't break current contract with consumers.

We should try to maintain the behaviour if we pass page and offset as negative to PageUtils.getPageRequest
___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGWnlOM8an-ZaF5dvR2:-NGWnlOM8an-ZaF5dvR3:b-v2igmo) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L141)):*
> ```Java
>       return Page.empty();
>     }
>     if (input.size() < offset * pageSize) {
> ```

Whats this condition?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_h8WEsugVtKS1XBr:-NGX3rnDA64e2YxYd3Ia:b-y6z5t) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L131)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

@ankit-harness this doc is showing the same thing finding sublist as I have done
</blockquote></details>

the logic is used when page we are requesting for, does not have any entity, suppose there are 5 entities and pagesize is 5 and we are requesting for 2 page.
also, I have checked the java's method which we use to create page for paginated results, that is throwing the same errors that I have put.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGW_h8WEsugVtKS1XBr:-NGa6QT7AaHRldkDzYFQ:b-g00ld) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L131)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

> https://stackoverflow.com/a/37771947

Make sure if conditions don't break current contract with consumers.

We should try to maintain the behaviour if we pass page and offset as negative to PageUtils.getPageRequest
</blockquote></details>

Done. I have checked the java's method which we use to create page for paginated results, that is throwing the same errors that I have put.
___
*[`960-persistence/src/main/java/io/harness/utils/PageUtils.java` line 141 at r2](https://reviewable.io/reviews/harness/harness-core/39887#-NGWnlOM8an-ZaF5dvR2:-NGa6S__2B-gy1Nal5SG:b7lpbb4) ([raw file](https://github.com/harness/harness-core/blob/dabc8897fee166c6a41637ff66dd1959d46334e1/960-persistence/src/main/java/io/harness/utils/PageUtils.java#L141)):*
> the logic is used when page we are requesting for, does not have any entity, suppose there are 5 entities and pagesize is 5 and we are requesting for 2 page.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887#-:-NGa72an8Q8ve04ktuGv:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39887)* status: :shipit: complete! ✓

**Pull request merged**
