### PR TITLE
[feat]: [PIE-8779]: Transform Plan for Rollback Mode

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 914 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPva1276wMFy7RJ_kWg:-NPva1276wMFy7RJ_kWh:b-nuotd7) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L914)):*
> ```Java
> 
>     return mongoTemplate.find(query, NodeExecution.class);
>   }
> ```

Number of nodes fetches at a time could be very high, this should be CloseableIterator



_Code quote:_
```Java
  @Override
  public List<NodeExecution> fetchNodesForPlanExecutionID(String planExecutionId) {
    Criteria criteria = Criteria.where(NodeExecutionKeys.planExecutionId).is(planExecutionId);
    Query query = new Query().addCriteria(criteria);

    return mongoTemplate.find(query, NodeExecution.class);
  }
```
___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaJkq2JZGj-EDyOzt:-NPvaJkq2JZGj-EDyOzu:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java#L71)):*
> ```Java
>   default List<AdviserObtainment> getAdvisorObtainmentsForRollbackMode() {
>     return null;
>   }
> ```

why do we need this?



_Code quote:_
```Java
  default List<AdviserObtainment> getAdviserObtainments() {
    return null;
  }

  default List<AdviserObtainment> getAdvisorObtainmentsForRollbackMode() {
    return null;
  }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaVXg1gqV83g9lSDm:-NPvaVXg1gqV83g9lSDn:b-qu501v) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L113)):*
> ```Java
>    * the map
>    * Step4: Go through `createdPlan`. If any Plan node has AdvisorObtainmentsForRollbackMode, add them to the
>    * corresponding Identity Plan Node in the initialised map
> ```

identity plan node or normal node?



_Code quote:_
```Java
corresponding Identity Plan Node in the initialised map
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaZqL396ZFU0oQDUF:-NPvaZqL396ZFU0oQDUG:b-d0wxhj) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L115)):*
> ```Java
>    * corresponding Identity Plan Node in the initialised map
>    * Step5: From `createdPlan`, pick out all nodes that are not a descendants of some stage, and add them to the
>    * initialised map. Step6: For all IDs in `nodeIDsToPreserve`, remove the Identity Plan Nodes in the map, and put the
> ```

new line
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvafnX0WsBVjowb_uf:-NPvafnX0WsBVjowb_ug:bp3dtfl) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L130)):*
> ```Java
>       if (planNode.getStepType().getStepCategory() == StepCategory.STAGE
>           || EmptyPredicate.isEmpty(planNode.getStageFqn())
>           || !planNode.getStageFqn().matches("pipeline\\.stages\\..+")) {
> ```

why we are using regex check here?



_Code quote:_
```Java
!planNode.getStageFqn().matches("pipeline\\.stages\\..+")
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvatum2DAGNRpuxxgq:-NPvatunCrkE6Y7B0RnX:b-8u72qu) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L148)):*
> ```Java
> 
>     // steps 5 and 6
>     for (Node planNode : createdPlan.getPlanNodes()) {
> ```

Plus we should create smaller functions for all steps, else for method completion, all big objects will not be garbage collected.



_Code quote:_
```Java
nodeExecutions
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 6 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 914 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPva1276wMFy7RJ_kWg:-NPvfz8_CyTSPPrvSr3K:bqjpbzb) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L914)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Number of nodes fetches at a time could be very high, this should be CloseableIterator
</blockquote></details>

Other methods in this class also has a lot of Todos added to paginate the response. I don't know exactly how it will work out, so maybe we can take this up as a separate exercise
___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaJkq2JZGj-EDyOzt:-NPvgGSg4Oe8vcTUFViz:bsevl9t) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

identity plan nodes can have advisor obtainments, hence added at the base interface. As for advisors for rollback mode, right now id nodes don't need them, but kept them here anyway if the use case comes up
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 113 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaVXg1gqV83g9lSDm:-NPvgbxkANydDPz0ocDZ:bkmyaqz) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

identity plan node or normal node?
</blockquote></details>

identity node, the AdvisorObtainmentsForRollbackMode from plan node are to be added to the identity node created for it
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaZqL396ZFU0oQDUF:-NPvgnEC12yd3ZTsRfaC:b8pfdsg) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L115)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

new line
</blockquote></details>

it is how code format wants it, on intellij it looks fine, only on reviewable it looks off
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvafnX0WsBVjowb_uf:-NPvgv3x9MekqTjfBsFR:b-e0mgzk) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L130)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are using regex check here?
</blockquote></details>

Can you suggest any other way to check if a plan node is a descendant of a stage or not?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvatum2DAGNRpuxxgq:-NPvhzMZ0d90QqVMIyzc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L148)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Plus we should create smaller functions for all steps, else for method completion, all big objects will not be garbage collected.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 914 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPva1276wMFy7RJ_kWg:-NQ-9Zk3AJZ_U0gXDaZS:bku5h8z) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L914)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Other methods in this class also has a lot of Todos added to paginate the response. I don't know exactly how it will work out, so maybe we can take this up as a separate exercise
</blockquote></details>

We can use projections over here rather than populating all the fields.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44762#-NQ-A7K64K0D3gyG7c_-:-NQ-A7K64K0D3gyG7c_0:bsf2w1i) ([raw file](https://github.com/harness/harness-core/blob/ad92cadc8191d5f6976f7ffa1dc067a6feca9f5a/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java#L55)):*
> public List<NodeExecution> fetchNodesForPlanExecutionID(String planExecutionId) {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

>     Criteria criteria = Criteria.where(NodeExecutionKeys.planExecutionId).is(planExecutionId);
>     Query query = new Query().addCriteria(criteria);
> 
>     return mongoTemplate.find(query, NodeExecution.class);
</details>
>   }
As discussed, can we have a map here
map of mode to list of adviserObtainment?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvafnX0WsBVjowb_uf:-NQ-ApdH4qi8f8bOUpLd:bbh5yob) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L130)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Can you suggest any other way to check if a plan node is a descendant of a stage or not?
</blockquote></details>

Discussed offline, we can fetch fqns from plan node and use that fetch only required nodeExecutions.



_Code quote:_
```Java
      if (planNode.getStepType().getStepCategory() == StepCategory.STAGE
          || EmptyPredicate.isEmpty(planNode.getStageFqn())
          || !planNode.getStageFqn().matches("pipeline\\.stages\\..+")) {
        continue;
      }
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/44762#-NQ-B75t4JsUg0lFyGrM:-NQ-B75u0Qh9Edur0R8x:bkvvrol) ([raw file](https://github.com/harness/harness-core/blob/ad92cadc8191d5f6976f7ffa1dc067a6feca9f5a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L136)):*
> ```Java
>       if (nodeIDsToPreserve.contains(planNode.getUuid())
>           || planNode.getStepType().getStepCategory() == StepCategory.STAGE
>           || EmptyPredicate.isEmpty(planNode.getStageFqn())
> ```

This will be simplified with the new approach suggested in previous comment.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/IdentityPlanNode.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/44762#-NQ-BbKr-pjxbivl7x0S:-NQ-BbKr-pjxbivl7x0T:b-d1higz) ([raw file](https://github.com/harness/harness-core/blob/ad92cadc8191d5f6976f7ffa1dc067a6feca9f5a/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/IdentityPlanNode.java#L45)):*
> ```Java
>   String executionInputTemplate;
> 
>   @With List<AdviserObtainment> adviserObtainments;
> ```

nit: Add a comment explaining that if this is populated then original adviser will not be used. We will call this adviser.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 3 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 4 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/44762#-NQ-A7K64K0D3gyG7c_-:-NQ2CBLuCGA0ceOk3onl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad92cadc8191d5f6976f7ffa1dc067a6feca9f5a/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/PlanNode.java#L55)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

> public List<NodeExecution> fetchNodesForPlanExecutionID(String planExecutionId) {
>     Criteria criteria = Criteria.where(NodeExecutionKeys.planExecutionId).is(planExecutionId);
>     Query query = new Query().addCriteria(criteria);
> 
>     return mongoTemplate.find(query, NodeExecution.class);
>   }
As discussed, can we have a map here
map of mode to list of adviserObtainment?
</blockquote></details>

Done.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 9 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 923 at r5](https://reviewable.io/reviews/harness/harness-core/44762#-NQ4pdbY41g7FB2pP41s:-NQOb5frBUs-YsDCDuby:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5e1ffc8e1edab3efe4f1013f52688578920f686/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L923)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not use mongoTemplate directly in service layer, use NodeExecutionReadHelper
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaJkq2JZGj-EDyOzt:-NQOb8kH5mk2Ajds0cd0:b-kau63h) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if not needed for now, can we remove them?
</blockquote></details>

This is ideally a property of all Node Types hence its better to keep it here even though we don't have it explicitly defined for id nodes
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 159 at r5](https://reviewable.io/reviews/harness/harness-core/44762#-NQ4qSQH879KCN7xHxIh:-NQObKEx5bGLk-kaG1-v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5e1ffc8e1edab3efe4f1013f52688578920f686/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L159)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use iterator approach
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 169 at r5](https://reviewable.io/reviews/harness/harness-core/44762#-NQ4qMq79av8JZuOH9Hn:-NQObMnDCll7jGMgXero:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5e1ffc8e1edab3efe4f1013f52688578920f686/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add to NodeProjectionUtils
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 179 at r5](https://reviewable.io/reviews/harness/harness-core/44762#-NQ4qgap4QiRA2X1qG4t:-NQObNeO5FeQWDCMC8K3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5e1ffc8e1edab3efe4f1013f52688578920f686/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L179)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt this be decided by passing rollbackMode in transformPlanForRollbackMode
</blockquote></details>

Done.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 9 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/44762#-NPvaJkq2JZGj-EDyOzt:-NQObvKuA9wb8N1uLIqO:b-fe3yiu) ([raw file](https://github.com/harness/harness-core/blob/8727d11381c1a0bd88ea6b2605a44d2b50a077ac/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan/Node.java#L71)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

This is ideally a property of all Node Types hence its better to keep it here even though we don't have it explicitly defined for id nodes
</blockquote></details>

We plan to remove the advisorobtainment field fully, we'll only keep the excution mode map. That's why that field is in Node and not just PlanNode

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 9 file(s) to review. 2 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 351 at r5](https://reviewable.io/reviews/harness/harness-core/44762#-NQ4pT4k5M7jH5f0wlPB:-NQOcVm--Cs2u8CCW52r:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a5e1ffc8e1edab3efe4f1013f52688578920f686/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L351)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should pagination at first go, pagination should be treated as part of first phase of impl details
</blockquote></details>

Done

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 350 at r7](https://reviewable.io/reviews/harness/harness-core/44762#-NQP9K4DAzcg51HU7a6M:-NQP9K4DAzcg51HU7a6N:bt6meqc) ([raw file](https://github.com/harness/harness-core/blob/40ebddabaece7c66add6a253df95e0cd4b045d86/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L350)):*
> ```Java
>   List<NodeExecution> fetchStageExecutionsWithEndTsAndStatusProjection(String planExecutionId);
> 
>   // TODO(Projection): Make it paginated, has projection
> ```

nit: comment not valid



_Code quote:_
```Java
/ TODO(Projection): Make it paginated, has projection
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 499 at r7](https://reviewable.io/reviews/harness/harness-core/44762#-NQP9xcm7F5DkagJb3Fi:-NQP9xcm7F5DkagJb3Fj:b-ov9pm5) ([raw file](https://github.com/harness/harness-core/blob/40ebddabaece7c66add6a253df95e0cd4b045d86/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L499)):*
> ```Java
>     if (executionMode.equals(ExecutionMode.POST_EXECUTION_ROLLBACK)) {
>       return rollbackModeExecutionHelper.transformPlanForRollbackMode(
>           plan, previousExecutionId, Collections.emptyList(), ExecutionMode.POST_EXECUTION_ROLLBACK);
> ```

can we not directly pass executionMode?



_Code quote:_
```Java
ExecutionMode.POST_EXECUTION_ROLLBACK
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 9 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 499 at r7](https://reviewable.io/reviews/harness/harness-core/44762#-NQP9xcm7F5DkagJb3Fi:-NQPawC3-xqLpmYW8doW:b-v2qkhj) ([raw file](https://github.com/harness/harness-core/blob/40ebddabaece7c66add6a253df95e0cd4b045d86/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L499)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we not directly pass executionMode?
</blockquote></details>

We only need this for post prod or pipeline rollback, right now it has to be an if condition but when we refactor executionhelper we can have a single transformer for everything

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 499 at r7](https://reviewable.io/reviews/harness/harness-core/44762#-NQP9xcm7F5DkagJb3Fi:-NQUFelCDzGS0XdET-fu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/40ebddabaece7c66add6a253df95e0cd4b045d86/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L499)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

We only need this for post prod or pipeline rollback, right now it has to be an if condition but when we refactor executionhelper we can have a single transformer for everything
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 4 of 6 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44762)* status: :shipit: complete! ✓

**Pull request merged**
