### PR TITLE
[feat]: [SRM-10633]: metric support for splunk 

### PR DESCRIPTION
**Pull request by kjoshi12345**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34222)

### CODE REVIEW

**Comment by kjoshi12345** [comment]
trigger messagecheck

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34222)* status: 39 file(s) to review. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/SplunkMetricHealthSourceSpec.java` line 109 at r4](https://reviewable.io/reviews/harness/harness-core/34222#-N4W-5gzAQavDT0ngb4L:-N4W-5gzAQavDT0ngb4M:bpyffuq) ([raw file](https://github.com/harness/harness-core/blob/d6b749465570e4b5e3f58d99a6d16fe5450115fd/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/SplunkMetricHealthSourceSpec.java#L109)):*
> ```Java
>     Map<Key, List<SplunkMetricDefinition>> keySplunkMetricDefinitionMap = new HashMap<>();
> 
>     metricDefinitions.forEach(metricDefinition -> {
> ```

nit: in streams, Collectors.toMap(), is a cleaner approach for this

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34222)* status: 39 file(s) to review.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 16 of 29 files at r1, 22 of 23 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34222)* status: :shipit: complete! ✓

**Pull request merged**
