### PR TITLE
fix: [PL-30439]: added email updation in user metadata via SCIM in NG

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Email update via SCIM was not reflecting in NG userMetadata for the PUT user update API. Added support for the same.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42358)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/42358#-NLKECrkBx7QXlQOjq4P:-NLKECrkBx7QXlQOjq4Q:b1pw38g) ([raw file](https://github.com/harness/harness-core/blob/15f3595ad804f273ff4e5626d05d66f3d37b51d6/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L251)):*
> ```Java
>               accountClient.isFeatureFlagEnabled(FeatureName.UPDATE_EMAILS_VIA_SCIM.name(), accountId))
>           && isEmailPresent && !existingUser.getEmail().equals(scimUser.getEmails().get(0).get("value").asText())) {
>         String updatedEmail = scimUser.getEmails().get(0).get("value").asText();
> ```

logic to get email value is complex and is being repeatedly being used, which increases chances of making mistakes and also redundancy in the code. We should write a private/util method to do that job.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 257 at r2](https://reviewable.io/reviews/harness/harness-core/42358#-NLKFYze5SVT1C8jhIH5:-NLKFYze5SVT1C8jhIH6:b6me87z) ([raw file](https://github.com/harness/harness-core/blob/15f3595ad804f273ff4e5626d05d66f3d37b51d6/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L257)):*
> ```Java
>       }
> 
>       ngUserService.updateUserMetadata(userMetadata);
> ```

We should add a log after this update call to confirm if update is successful. There may be a case where flow might break before reaching final update log written below.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 249 at r3](https://reviewable.io/reviews/harness/harness-core/42358#-NLUcPTsEO1W6HbdQqfQ:-NLUcPTsEO1W6HbdQqfR:bugv7v5) ([raw file](https://github.com/harness/harness-core/blob/f389918f44821d9766a018f90010e8cbf1c72c0c/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L249)):*
> ```Java
>       if (CGRestUtils.getResponse(
>               accountClient.isFeatureFlagEnabled(FeatureName.UPDATE_EMAILS_VIA_SCIM.name(), accountId))
>           && !existingUser.getEmail().equals(updatedEmail)) {
> ```

There's a catch here. getPrimaryEmail() returns smallcase email address. Just make sure existingUser.getEmail() also follows the same otherwise we may run into issues. Just highlighting, I guess you're already aware about it.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42358)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42358)* status: :shipit: complete! ✓

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Pull request merged**
