### PR TITLE
[fix]: [PIE-8132]: setting git context for the retryPipeline for non default branches

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added code to set the git context for the retryPipeline for non default branches. Have tested this out locally for default and non default branches for remote entities and the same has been tested for inline pipeline.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43607)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/43607#-NNfRCfjDaQnV5UezBZl:-NNfRCfjDaQnV5UezBZm:b-95qz9h) ([raw file](https://github.com/harness/harness-core/blob/adf982802598ff6cb2da7c7fe47c189e43d59252/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L182)):*
> ```Java
>   }
> 
>   private void setupEntityDetails(EntityGitDetails entityGitDetails) {
> ```

Do we not have anything like this already present? It seems we can have this placed in some common utils, its pretty generic.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/43607#-NNfROc45yZbQe-v1t7b:-NNfROc45yZbQe-v1t7c:be3djqe) ([raw file](https://github.com/harness/harness-core/blob/adf982802598ff6cb2da7c7fe47c189e43d59252/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L132)):*
> ```Java
>     setupEntityDetails(pipelineExecutionSummaryEntity.getEntityGitDetails());
> 
>     Optional<PipelineEntity> updatedPipelineEntity =
> ```

why is the variable name "updated Pipeline entity"? Doesn't sound correct. We can change it irrespective whatever it was before.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43607)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/43607#-NNfROc45yZbQe-v1t7b:-NNfXoEE4d144dG7Q2If:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/adf982802598ff6cb2da7c7fe47c189e43d59252/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L132)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is the variable name "updated Pipeline entity"? Doesn't sound correct. We can change it irrespective whatever it was before.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/43607#-NNfRCfjDaQnV5UezBZl:-NNfXoZLEI4M95MkEiJs:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/adf982802598ff6cb2da7c7fe47c189e43d59252/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L182)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Do we not have anything like this already present? It seems we can have this placed in some common utils, its pretty generic.
</blockquote></details>

done

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43607)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43607)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43607)* status: :shipit: complete! ✓

**Pull request merged**
