### PR TITLE
feat: [CDS-44389]: Integrate SCM Changes with Java Client

### PR DESCRIPTION
**Pull request by akhilpandey1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39668)

### CODE REVIEW

**Comment by akhilpandey1** [comment]
trigger feature-build

**Comment by mohitg0795** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/39668#-NGDOK17-ZBN-5QupYzQ:-NGDOK17-ZBN-5QupYzR:bnz1jbj) ([raw file](https://github.com/harness/harness-core/blob/fb86afb0d205273d706872589182083402dbbd0a/930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java#L251)):*
> ```Java
> 
>     createDirectoryIfDoesNotExist(parent.toString());
>     FileIo.writeFile(finalPath.toString(), Base64.getDecoder().decode(fileContent.getContent()));
> ```

Is this backward compatible change?

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/39668#-NGDOmPt7pdMktS8r1tm:-NGDOmPuAX7ZFyXYuVWn:bsy4mw) ([raw file](https://github.com/harness/harness-core/blob/fb86afb0d205273d706872589182083402dbbd0a/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L478)):*
> ```Java
> 
>   private GetBatchFileRequest createBatchFileRequest(
>       List<String> harnessRelatedFilePaths, String slug, String ref, Provider gitProvider, boolean getBase64Content) {
> ```

base64content enhancement should have been per file, not per batch. This isn't scalable going forward.

**Comment by mohitg0795** [comment]
*[`product/ci/scm/proto/scm.proto` line 293 at r1](https://reviewable.io/reviews/harness/harness-core/39668#-NGDPG6WBsVIV1auzm9N:-NGDPG6X5P0S2A990GXg:bozds4q) ([raw file](https://github.com/harness/harness-core/blob/fb86afb0d205273d706872589182083402dbbd0a/product/ci/scm/proto/scm.proto#L293)):*
> ```protobuf
>   }
>   Provider provider = 5;
>   bool base64Encoding = 6;
> ```

can you rename it to "isBase64EncodingRequired" or anything that signifies that basically either this file requires base64encoding/decoding or its type is base64encoded or anything similar.

My concern here is that currently it seems bit vague on what does the field represent. It should represent something clearly.

I don't mind if you want to take it up as a follow up ticket, but only request would be to get it done on priority, so that it doesn't get missed. Making the comment non-blocking for now.

**Comment by akhilpandey1** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/39668#-NGDOK17-ZBN-5QupYzQ:-NGDQXxQ9bmZxaiQtpB_:b-55sxic) ([raw file](https://github.com/harness/harness-core/blob/fb86afb0d205273d706872589182083402dbbd0a/930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java#L251)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is this backward compatible change?
</blockquote></details>


This is a CD owned method and we're fixing this part where it allows us to write compressed files to disk

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39668)* status: :shipit: complete! ✓

**Comment by akhilpandey1** [comment]
trigger codebasehash

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39668)* status: :shipit: complete! ✓

**Pull request merged**
