### PR TITLE
feat: [PL-41453]: HSM secret decryption on delegate side

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
Delegate side change
1. proto API changes to include secret decryption and mapping secret to step container
2. implementation on delegate side to decrypt secret from HSM
3. create secret in k8s

Sanity pipeline (shell) looks fine

image

Install a docker delegate looks fine
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53863)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53863)* status: Some of the checks are too old. 30 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyGABfD4cNK1QSOitK:-NgyGABfD4cNK1QSOitL:b5qvbel) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L107)):*
> ```Java
> 
>       // Step 1a - Should we decrypt other step secrets here and create resources?
>       var k8Secrets = flatMapping(task -> createTaskSecrets(infraId, k8sInfra.getStepsList().get(0), decrypted, context), toList());
> ```

This is probably some leftover 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyGKVp3k_hPL5rx-wz:-NgyGKVp3k_hPL5rx-x-:b-kjra3j) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L159)):*
> ```Java
>   @Override
>   public void execute(
>       final String taskGroupId, final InputData tasks, DecryptedSecrets decrypted, final Context context) {
> ```

[mark final]. What would be the use case for secrets here. We can't add these to infra (in K8S world). It's not used yet. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/SecretsBuilder.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyHKRB-FiyLxaYzkdo:-NgyHKRB-FiyLxaYzkdp:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/SecretsBuilder.java#L72)):*
> ```Java
>   public V1Secret createSecret(final String infraId, final String taskId, IdentifierRef ref, final char[] value) {
>     final var secretName = K8SResourceHelper.getSecretName(taskId);
>     // final var decryptedSecrets = decryptionService.decrypt(infraSecret);
> ```

remove
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/SecretsBuilder.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyHLOJCt0nlPI-HOk9:-NgyHLOJCt0nlPI-HOkA:b-yh78lp) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/SecretsBuilder.java#L76)):*
> ```Java
>       // TODO: create secret file
>       return K8SSecret.secret(secretName, config.getNamespace(), infraId)
>           .putAllCharDataItems(Map.of(K8SResourceHelper.normalizeResourceName(ref.getFullyQualifiedName()), value))
> ```

nit this map will always have one element and we will always need to unpack it when creating secret. Better just create an override K8SSecret.addCharDataItem, so that you don't need to create a Map. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/handlermapping/HandlerMappingServer.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyMUEQ90QX4eTLBTx7:-NgyMUEQ90QX4eTLBTx8:bfjro3m) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/handlermapping/HandlerMappingServer.java#L77)):*
> ```Java
>             decrypted);
>       } catch (Exception ex) {
>         log.error("exception occurred when decrypting the secret", ex);
> ```

Should we fail task if we fail to decrypt the secret? I think this would just fail it later on during the runtime. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyN6DQCstU-faYjZer:-NgyN6DQCstU-faYjZes:b-hf3p2e) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L33)):*
> ```Java
>   @Named("referenceFalseKryoSerializer") private final KryoSerializer kryoSerializer; // TODO: remove named
> 
>   @Deprecated
> ```

Why not just remove it altogether. 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyNBN9310A7ng8vWOJ:-NgyNBN9310A7ng8vWOK:boinbu) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L40)):*
> ```Java
>         secret.getEncryptedRecord().getBinaryData().toByteArray());
>     final var decrypt = decryptionService.decrypt(Map.of(secretConfig, kryoSecrets));
>     log.info("Decrypted secrets are: {}", decrypt);
> ```

I know you probably copy pasted this code from some other, but this logs the secret (looks like something I would write :smile: )
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyOFqX2vYYF4pfIlJH:-NgyOFqX2vYYF4pfIlJI:b1im6i8) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L54)):*
> ```Java
>     final EncryptedDataRecord encryptedDataRecord =
>         EncryptedDataRecord.parseFrom(secret.getEncryptedRecord().getBinaryData().toByteArray());
>     EncryptedRecordData mappedRecordData = EncryptedDataRecordProtoPojoMapper.map(encryptedDataRecord);
> ```

These two types are named awkwardly :smile:
What's the difference?  I'm assuming they are supposed to be the same thing in a different package. It would be great if we could rename one of them (if it's not touching too many files).



_Code quote:_
```Java
    final EncryptedDataRecord encryptedDataRecord =
        EncryptedDataRecord.parseFrom(secret.getEncryptedRecord().getBinaryData().toByteArray());
    EncryptedRecordData mappedRecordData = EncryptedDataRecordProtoPojoMapper.map(encryptedDataRecord);
```
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyNU2r29mk_k1DCPKT:-NgyNU2r29mk_k1DCPKU:bjy8jsz) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L60)):*
> ```Java
>     List<EncryptedRecord> encryptedRecordList = new ArrayList<>();
>     encryptedRecordList.add(mappedRecordData);
>     assert mappedEncryptionConfig != null;
> ```

you should not use assert in prod code. Also, assertions are disabled by default (so this would be NOOP). 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyPPmCAXK4sU1Kf6FA:-NgyPPmCAXK4sU1Kf6FB:bla83y) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L65)):*
> ```Java
>     if (!decrypt.containsKey(mappedRecordData.getUuid())) {
>       log.error("After decryption, cannot find decrypted secret for encryption record {}", mappedRecordData.getUuid());
>       return null;
> ```

Better throw some exception, this would just cause NPE somewhere. 
___
*[`920-delegate-service-beans/src/main/proto/io/harness/delegate/secrets.proto` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyIr7f0QuRMSxgGcMT:-NgyIr7f0QuRMSxgGcMU:b9rrqzt) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/920-delegate-service-beans/src/main/proto/io/harness/delegate/secrets.proto#L25)):*
> ```proto
>   org = 1;
>   project = 2;
> }
> ```

So far delegate didn't care about the concept of the scope (didn't even know which scope it's in). Why do we need this now?



_Code quote:_
```proto
enum Scope {
  account = 0;
  org = 1;
  project = 2;
}
```
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret.proto` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyPtaZ4JKxUyWmNWjL:-NgyPtaZ4JKxUyWmNWjM:b2ni1ar) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret.proto#L22)):*
> ```proto
>   InputData encrypted_record = 1;    // TaskInput may contain any number of secrets, not necessarily just one
>   SecretConfig config = 2;  // Config that can be used to deserialize all secrets from input
>   SecretRef secret_ref = 3;
> ```

doc
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret_details.proto` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyJHm53FCsLfbY_ZQv:-NgyJHm53FCsLfbY_ZQw:ben4gwf) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret_details.proto#L43)):*
> ```proto
> 
> enum EncryptionType {
>   NOT_SET = 0;
> ```

in proto3, zero value should always be `UNKNOWN`. We can decide to treat UNKNOWN as NOT_SET for now, but those are distinct IMO. This allows us to introduce NOT_SET in the future and handle it differently if we wish so, but changing the default would not be possible. 
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret_details.proto` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyKGkQ-VMM8e8nM__k:-NgyKGkQ-VMM8e8nM__l:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret_details.proto#L56)):*
> ```proto
> 
> enum SecretManagerType {
>   SM_NOT_SET = 0;
> ```

same

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53863)* status: Some of the checks are too old. 30 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyGABfD4cNK1QSOitK:-Nh-mtv14jE9NJP4MSJx:burwzia) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L107)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is probably some leftover
</blockquote></details>

good catch ! 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyGKVp3k_hPL5rx-wz:-Nh0MLKX2TehZFkJBydP:b-a9uv82) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/core/litek8s/K8SLiteRunner.java#L159)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

[mark final]. What would be the use case for secrets here. We can't add these to infra (in K8S world). It's not used yet.
</blockquote></details>

true , i m fine with adding this later when it's needed for execute. eg, VM or Docker runner may need secrets in execute
___
*[`260-delegate/src/main/java/io/harness/delegate/service/handlermapping/HandlerMappingServer.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyMUEQ90QX4eTLBTx7:-Nh0OPVh5Lk9lbx_XGT8:b-wczj99) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/handlermapping/HandlerMappingServer.java#L77)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Should we fail task if we fail to decrypt the secret? I think this would just fail it later on during the runtime.
</blockquote></details>

agree, we should. but we don't have a proper response data type & interface built yet. I added a TODO for now
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyNBN9310A7ng8vWOJ:-Nh0RYLb8wrJVudANw5J:bzqm1q) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L40)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I know you probably copy pasted this code from some other, but this logs the secret (looks like something I would write :smile: )
</blockquote></details>

good catch !
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyOFqX2vYYF4pfIlJH:-Nh0TTM56kP2EsrsARJJ:b-a7ksbb) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L54)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

These two types are named awkwardly :smile:
What's the difference?  I'm assuming they are supposed to be the same thing in a different package. It would be great if we could rename one of them (if it's not touching too many files).
</blockquote></details>

i can rename the proto to be EncryptedRecordForDelegateDecryption
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyNU2r29mk_k1DCPKT:-Nh0SAmM-jE0JZS3YqHq:bkm0y71) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L60)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

you should not use assert in prod code. Also, assertions are disabled by default (so this would be NOOP).
</blockquote></details>

another mistake, good catch ! thank you so much 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyPPmCAXK4sU1Kf6FA:-Nh0RrgJ1ZEkX-SXfyka:bqnzrg0) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/260-delegate/src/main/java/io/harness/delegate/service/secret/RunnerDecryptionService.java#L65)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Better throw some exception, this would just cause NPE somewhere.
</blockquote></details>

right, return null is not a good practice 
___
*[`920-delegate-service-beans/src/main/proto/io/harness/delegate/secrets.proto` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyIr7f0QuRMSxgGcMT:-Nh0TYnoA0jjXDfhYiDA:b-z6um69) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/920-delegate-service-beans/src/main/proto/io/harness/delegate/secrets.proto#L25)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

So far delegate didn't care about the concept of the scope (didn't even know which scope it's in). Why do we need this now?
</blockquote></details>

the only reason need this is to uniquely identify a secret. Secret id itself is not unique, but secret id + scope + (proj, or org, or account) id  is unique.
That's why in the DecryptedSecrets java object, i am using IdentifierRef as the key.
___
*[`955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret_details.proto` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/53863#-NgyJHm53FCsLfbY_ZQv:-Nh2rkgq0I4_apaAtt-7:bbgvj6n) ([raw file](https://github.com/harness/harness-core/blob/7919ada38218197188f9d0bb93da5616c5643c22/955-delegate-beans/src/main/proto/io/harness/delegate/core/beans/secret_details.proto#L43)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

in proto3, zero value should always be `UNKNOWN`. We can decide to treat UNKNOWN as NOT_SET for now, but those are distinct IMO. This allows us to introduce NOT_SET in the future and handle it differently if we wish so, but changing the default would not be possible.
</blockquote></details>

my intention is actually to distinct between unknown and not_set.
i checked the code generated, actually proto use -1 for UNRECOGNIZED  , -1 is reserved.
Instead, if i start the enum definition with number 1, (reserve 0), the compiler will report error

**Comment by xingchi-jin** [comment]
trigger uts

**Review by mdmilic — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 10 files at r2, 15 of 17 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53863#-:-NhE-3tn0eOtlr-HZQQ3:bnfp4nl)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger ut1

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 4 of 4 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53863)* status: 37 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): build-engineering.

**Comment by mdmilic** [comment]
trigger ut8

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger ut5

**Comment by xingchi-jin** [comment]
trigger ut7

**Comment by xingchi-jin** [comment]
trigger ut8

**Comment by xingchi-jin** [comment]
trigger ut5

**Comment by xingchi-jin** [comment]
trigger ut7

**Comment by xingchi-jin** [comment]
trigger ut5

**Comment by xingchi-jin** [comment]
trigger ut7

**Comment by xingchi-jin** [comment]
trigger ut7

**Pull request merged**
