### PR TITLE
feat: [PIE-7199]: added POJOs for Policy Config

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes
added POJO for Policy Config and set policyConfig field in stepParameters 

## Testing:
Ran automation in local for basic sanity

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/policy/PolicyConfig.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQdBa4teRBGQ4Wiz4:-NJxQdBa4teRBGQ4Wiz5:b76h95x) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/953-yaml-commons/src/main/java/io/harness/plancreator/policy/PolicyConfig.java#L33)):*
> ```Java
>   @NotNull
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH)
>   ParameterField<List<String>> policySets;
> ```

can this be executionRuntime input?
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNode.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQIXyDXYnLVOqr_Eo:-NJxQIXyDXYnLVOqr_Ep:bq44hj5) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNode.java#L68)):*
> ```Java
> 
>   @VariableExpression(skipVariableExpression = true) @JsonProperty("strategy") StrategyConfig strategy;
>   @VariableExpression(skipVariableExpression = true) @JsonProperty("enforce") PolicyConfig policyConfig;
> ```

can we rename field to be enforce itself? rather than using JsonProperty
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StepElementParameters.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQRiZ3U4H6EBn1cHN:-NJxQRiZ3U4H6EBn1cHO:b6ghy89) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StepElementParameters.java#L48)):*
> ```Java
>   String type;
>   SpecParameters spec;
>   PolicyConfig policyConfig;
> ```

we should have enforce only so that expressions work

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/policy/PolicyConfig.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQdBa4teRBGQ4Wiz4:-NJxSJU-EOzNe-MDy-WA:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/953-yaml-commons/src/main/java/io/harness/plancreator/policy/PolicyConfig.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can this be executionRuntime input?
</blockquote></details>

Yes
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNode.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQIXyDXYnLVOqr_Eo:-NJxSHzV-C0gdMawy3me:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNode.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename field to be enforce itself? rather than using JsonProperty
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StepElementParameters.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQRiZ3U4H6EBn1cHN:-NJxSJ064KB3HVRAVmNR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StepElementParameters.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should have enforce only so that expressions work
</blockquote></details>

Done.

**Review by namanvermah — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)* status: 1 change requests. 3. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868#-:-NKNQPAFDhMIX-qU4jzT:bnfp4nl)* status: 1 change requests. 3. unresolved discussions.

**Comment by shalini-agr** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/policy/PolicyConfig.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/41868#-NJxQdBa4teRBGQ4Wiz4:-NKNQPSM5P_GHqj6xQE6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa0ef54c3f088d7ef75c20ca50f16670c6a8d348/953-yaml-commons/src/main/java/io/harness/plancreator/policy/PolicyConfig.java#L33)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)* status: 1 change requests. 3. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41868)* status: Some of the checks are too old.

**Pull request merged**
