### PR TITLE
[feat]: [PL-30680]: Develop PR for already merged PR for Apple User Custom Session TImeout

### PR DESCRIPTION
**Pull request by shashank-harness**
[feat]: [PL-30680]: Develop PR for already merged PR for Apple User Custom Session TImeout
Original PR with all details: https://github.com/harness/harness-core/pull/45297

**Added below to this PR :**
- Lower limit of 30 mins for session timeout
- By default returning timeout of 24 hours/1440 mins.
- UTs including al above conditions

**Testing:**
- Same as in original PR
- Additionally, checking for lower limits and default value of session timeout.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PL-30680]: https://harness.atlassian.net/browse/PL-30680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45368)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 768 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0LpvUA3uxpdcwcbZ9:-NR0LpvUA3uxpdcwcbZA:bxqaatz) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L768)):*
> ```Java
>   public Integer getSessionTimeoutInMinutes(String accountId) {
>     Query<Account> getQuery = wingsPersistence.createQuery(Account.class).filter(ID_KEY2, accountId);
>     return getQuery.get().getSessionTimeOutInMinutes();
> ```

If this is not set in DB then it should return default 24 hours

**Comment by piyush-harness** [comment]
*[`400-rest/src/test/java/software/wings/service/AccountServiceTest.java` line 1711 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0MEinC9Kxx5SeiqGh:-NR0MEinC9Kxx5SeiqGi:b3i7pmx) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/test/java/software/wings/service/AccountServiceTest.java#L1711)):*
> ```Java
>   @Owner(developers = SHASHANK)
>   @Category(UnitTests.class)
>   public void testAccountSessionTimeOut() {
> ```

@jennyjames21 Add more negative scenarios for Unit tests 

Negative Values
Values below Minimum values
Setting it to Null etc

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 772 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0M6ARAaUY5e80CYKj:-NR0M6ARAaUY5e80CYKk:b28irgg) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L772)):*
> ```Java
> 
>   @Override
>   public void setSessionTimeout(String accountId, Integer sessionTimeOutInMinutes) {
> ```

@shashank-harness @jennyjames21 We should validate minValue before setting it in Account in case someone is invoking this API directly.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 603 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0LP6p4SBS5NGb3vog:-NR0LP6p4SBS5NGb3voh:b8hl6je) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L603)):*
> ```Java
>   public RestResponse<Boolean> setSessionTimeoutAtAccountLevel(
>       @QueryParam("accountId") @NotEmpty String accountId, @NotNull SessionTimeoutSettings sessionTimeoutSettings) {
>     if (null == sessionTimeoutSettings.getSessionTimeOutInMinutes()
> ```

@shashank-harness @jennyjames21 
What if I want unset sessionTimeout and make it what was default?  
Also in SessionTimeoutSettings I see this is marked sessionTimeOutInMinutes as @NotNull & @Min value as 30 do we need to again perform this check?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0LhfgAR5rNVa6lPTp:-NR0Lhfh4DgY_onua5Rw:b-qnujcx) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/beans/Account.java#L146)):*
> ```Java
> 
>   @Getter @Setter private boolean smpAccount;
>   @Getter @Setter private Integer sessionTimeOutInMinutes;
> ```

We should apply defaultValue of 24 hours;

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45368)* status: 12 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 772 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0M6ARAaUY5e80CYKj:-NR0pxe8D64yoqNTQjXd:b-tmu0o2) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L772)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

@shashank-harness @jennyjames21 We should validate minValue before setting it in Account in case someone is invoking this API directly.
</blockquote></details>

Its already being checked in API call at resource layer



_Code snippet:_
```Java
 @PUT
  @Path("session-timeout-account-level")
  public RestResponse<Boolean> setSessionTimeoutAtAccountLevel(
      @QueryParam("accountId") @NotEmpty String accountId, @NotNull SessionTimeoutSettings sessionTimeoutSettings) {
    if (null == sessionTimeoutSettings.getSessionTimeOutInMinutes()
        || sessionTimeoutSettings.getSessionTimeOutInMinutes() < MIN_SESSION_TIMEOUT) {
      throw new InvalidRequestException(String.format("Session Timeout should be a positive Integer."));
    } else {
      accountService.setSessionTimeout(accountId, sessionTimeoutSettings.getSessionTimeOutInMinutes());
      return new RestResponse(Boolean.TRUE);
    }
  }
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 603 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0LP6p4SBS5NGb3vog:-NR0qstG9ApAk-wjHxPi:b-3yesch) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L603)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

@shashank-harness @jennyjames21 
What if I want unset sessionTimeout and make it what was default?  
Also in SessionTimeoutSettings I see this is marked sessionTimeOutInMinutes as @NotNull & @Min value as 30 do we need to again perform this check?
</blockquote></details>

I think we missed the @valid annotation here. Adding that now so we need not perform this check again.

**Review by shashank-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45368)* status: 12 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0LhfgAR5rNVa6lPTp:-NR1-CXG9dR3rvhKoFMQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/beans/Account.java#L146)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

We should apply defaultValue of 24 hours;
</blockquote></details>

done

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 768 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0LpvUA3uxpdcwcbZ9:-NR10qvE1xirOYsd0KJi:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L768)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

If this is not set in DB then it should return default 24 hours 
</blockquote></details>

done

**Comment by shashank-harness** [comment]
*[`400-rest/src/test/java/software/wings/service/AccountServiceTest.java` line 1711 at r3](https://reviewable.io/reviews/harness/harness-core/45368#-NR0MEinC9Kxx5SeiqGh:-NR3PTe-BG2b9Q0ZHGPh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a21105f3f17e9391818a169748fa08dd094788f/400-rest/src/test/java/software/wings/service/AccountServiceTest.java#L1711)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

@jennyjames21 Add more negative scenarios for Unit tests 

Negative Values
Values below Minimum values
Setting it to Null etc


</blockquote></details>

Done.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 1 of 1 files at r2, 1 of 5 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45368)* status: 7 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 4 of 5 files at r4, 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45368)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45368)* status: :shipit: complete! ✓

**Pull request merged**
