### PR TITLE
fix: [CDS-42542]: fixing the values override for harness store and custom store using Helm Chart manifest with non git type store.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
Was not passing shouldOpenLogStream parameter earlier to ensure logs for fetch files. I have added this parameter.

Further if there are no git store in aggregateValuesManifest then we should not call GitValuesFetchTaskNG. To avoid it I have added a snippet to collect all the values files.

There are more bugs with Custom Remote Store I will fix them as part of this ticket https://harness.atlassian.net/browse/CDS-43041. As this is a CFD want to close this PR by today.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37107)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37107)

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37107)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
Approving these changes, but maybe it's time to think about some refactoring around here this look like a generator of bugs, a small change in any if will result in inconsistent behaviour. It's hard to keep track of what was processed, what need to be processed, what need to be added and when we need to open log stream for fetch files. Some suggestions:
1. openFetchFilesLogStream can be stored in passthrough data and made true by default, once it's read it can be changed to false
2. We could keep track of what manifests were unprocessed in passthrough data. Read from passthrough data unprocessed manifests -> create task to process manifest -> remove it from list, and so on until no more manifests left. 

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37107#-:-NBWIFUIDRhG1vBcYClV:b445wke)* status: :shipit: complete! ✓

**Comment by GoelPratyush99** [comment]
Will all the following in the next PR @abosii-harness

**Pull request merged**
