### PR TITLE
feat: [CDS-85020]: Publish metric for redis event times

### PR DESCRIPTION
**Pull request by Y0709**
In the previous pr https://github.com/harness/harness-core/pull/55928 we published metric value params to metric context . In this pr we are publishing actual new metrics .

Screenshot 2023-12-04 at 12 15 36 PM

Screenshot 2023-12-04 at 12 32 09 PM

Screenshot 2023-12-04 at 12 27 41 PM

Screenshot 2023-12-04 at 12 36 36 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56262)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56262)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/monitoring/EventMonitoringServiceImpl.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/56262#-NknqOUtBNvmCinkXcPw:-NknqOUtBNvmCinkXcPx:bo065mp) ([raw file](https://github.com/harness/harness-core/blob/b4968951c55808ba7b552b165417eaed4a9ea6b5/884-pms-commons/src/main/java/io/harness/monitoring/EventMonitoringServiceImpl.java#L26)):*
> ```Java
>   @Inject MetricService metricService;
> 
>   public void sendMetric(String metricName, Long metricCount) {
> ```

metricValue, as time is not count
___
*[`884-pms-commons/src/main/java/io/harness/monitoring/EventMonitoringServiceImpl.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/56262#-NknqQzN5CWkDq9o-prZ:-NknqQzN5CWkDq9o-pr_:b-j57zs) ([raw file](https://github.com/harness/harness-core/blob/b4968951c55808ba7b552b165417eaed4a9ea6b5/884-pms-commons/src/main/java/io/harness/monitoring/EventMonitoringServiceImpl.java#L30)):*
> ```Java
>       metricService.recordMetric(metricName, metricCount);
>     } catch (Exception ex) {
>       log.error("Exception Occurred while recording metrics", ex);
> ```

string.format else exception doesnt get printed
___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/EventMonitoringTestService.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/56262#-Nknr6RGBCXx8QSG9csD:-Nknr6RGBCXx8QSG9csE:bmy5wv0) ([raw file](https://github.com/harness/harness-core/blob/b4968951c55808ba7b552b165417eaed4a9ea6b5/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/EventMonitoringTestService.java#L17)):*
> ```Java
> public class EventMonitoringTestService implements EventMonitoringService {
>   @Override
>   public void sendMetric(String metricName, Long metricCount) {}
> ```

metricvalue

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56262)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger checkstylecodeformat

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut4, ut5, ut6, ut7, ut8, ut9, compile

**Comment by Y0709** [comment]
trigger ut4, ut5, ut7

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56262)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
