### PR TITLE
feat:[CDC-37215]: Handle Template yaml schema generation and validation

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)

### CODE REVIEW

**Comment by abhinavmittal-harness** [comment]
trigger feature-build

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 10 of 25 files at r1, 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/container/scripts/replace_configs.sh` line 190 at r3](https://reviewable.io/reviews/harness/harness-core/34600#-N5TQcAeDnuvUITIXeeL:-N5TQcAeDnuvUITIXeeM:b1unom7) ([raw file](https://github.com/harness/harness-core/blob/e691be89b64b421f6b2178e40c11ea6c6e8aa040/840-template-service/container/scripts/replace_configs.sh#L190)):*
> ```Shell
> replace_key_value pmsGrpcClientConfig.target $PMS_GRPC_TARGET
> replace_key_value pmsGrpcClientConfig.authority $PMS_GRPC_AUTHORITY
> replace_key_value pipelineServiceClientConfig.baseUrl "$PIPELINE_SERVICE_CLIENT_BASEURL"
> ```

Should we add replace config for allowedParallelStages as well?
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/34600#-N5TTEAq66W09LZILaAB:-N5TTEAq66W09LZILaAC:b-84261s) ([raw file](https://github.com/harness/harness-core/blob/e691be89b64b421f6b2178e40c11ea6c6e8aa040/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L75)):*
> ```Java
>     }
> 
>     public static boolean isFeatureFlagEnabled(FeatureName dontRestrictParallelStageCount, String accountIdentifier, AccountClient accountClient) {
> ```

Nit: dontRestrictParallelStageCount change variable name
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/34600#-N5TRvysE5CMV3ekUVkx:-N5TRvytA57Lt1aBPZUE:b-7s3vb5) ([raw file](https://github.com/harness/harness-core/blob/e691be89b64b421f6b2178e40c11ea6c6e8aa040/840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L76)):*
> ```Java
> 
>         if(!schemaValidationSupported(templateEntityType)){
>             return null;
> ```

Can we return default template schema (with JsonNode in spec) here as well?

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 26 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/container/scripts/replace_configs.sh` line 190 at r3](https://reviewable.io/reviews/harness/harness-core/34600#-N5TQcAeDnuvUITIXeeL:-N5Yc-nW4mGWuC5OICPN:b-984n27) ([raw file](https://github.com/harness/harness-core/blob/e691be89b64b421f6b2178e40c11ea6c6e8aa040/840-template-service/container/scripts/replace_configs.sh#L190)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Should we add replace config for allowedParallelStages as well?
</blockquote></details>

Doesn't have a replace config for allowedParallelStage in pipeline service as well.
I think we don't have scenarios where this is needed right now
Can add it with unit tests if needed
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/34600#-N5TTEAq66W09LZILaAB:-N5YcHTjAOu03ZVZgv3S:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e691be89b64b421f6b2178e40c11ea6c6e8aa040/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L75)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Nit: dontRestrictParallelStageCount change variable name
</blockquote></details>

Done
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/34600#-N5TRvysE5CMV3ekUVkx:-N5YcJXcANgP-2nItOJg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e691be89b64b421f6b2178e40c11ea6c6e8aa040/840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L76)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Can we return default template schema (with JsonNode in spec) here as well?
</blockquote></details>

Done

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 25 files at r1, 26 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 276 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YpGBH48MXIVl4BegR:-N5YpGBJ5-5rMX9rqPDc:b-51xhdq) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L276)):*
> ```Java
> //        modules.add(moduleType);
> //      }
> //    });
> ```

Discussed offline, that license modules are not coming, thus returning all modules
cc: @brijeshdhakar 



_Code quote:_
```Java
    //TODO: Ideally it should be received from accountLicenses but there were some issues observed this part.
//    AccountLicenseDTO accountLicense =
//        NGRestUtils.getResponse(ngLicenseHttpClient.getAccountLicensesDTO(accountIdentifier));
//    accountLicense.getAllModuleLicenses().forEach((moduleType, value) -> {
//      if (EmptyPredicate.isNotEmpty(value)) {

//        modules.add(moduleType);
//      }
//    });
```
___
*[`840-template-service/src/main/java/io/harness/TemplateServiceApplication.java` line 358 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YpasX9xTNDG3cohUb:-N5YpasZCIRzat74Tktw:b-333wyc) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/TemplateServiceApplication.java#L358)):*
> ```Java
>             .requireSchemaInit(true)
>             .requireSnippetInit(true)
>             .requireValidatorInit(true)
> ```

this value is false in pipeline-service, do we know why we are making it to true?



_Code quote:_
```Java
requireValidatorInit(true
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YpoVC2Y06qXVdyQVm:-N5YpoVC2Y06qXVdyQVn:b-xy8bo1) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L24)):*
> ```Java
> import java.util.Set;
> 
> public class YamlSchemaMergeHelper {
> ```

i dont think code format is done here
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YqNBK2tR5DgVRy7as:-N5YqNBK2tR5DgVRy7at:bm7ai3v) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L24)):*
> ```Java
> import java.util.Set;
> 
> public class YamlSchemaMergeHelper {
> ```

Can we rename it to TemplateYamlSchemaMergeHelper, just so that all modules use generic name
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Yq2CK4KvYpqoRcu-_:-N5Yq2CK4KvYpqoRcu-a:buysq7s) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L30)):*
> ```Java
>         Set<String> keys = getKeysToRemoveFromTemplateSpec(templateEntityType);
> 
>         //TODO: create constants for these
> ```

which constants?



_Code quote:_
```Java
//TODO: create constants for these
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YqCpE8eTjY0PGKUqb:-N5YqCpE8eTjY0PGKUqc:brhcydc) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L32)):*
> ```Java
>         //TODO: create constants for these
>         if(EntityType.PIPELINES.equals(entityType)){
>             //TODO: remove one of for those once we add them in the ticket CDS-.
> ```

didnt understand this



_Code quote:_
```Java
remove one of for those once we add them in the ticket CDS-.
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Yq8g6Cyl8i2u1DpcB:-N5Yq8g6Cyl8i2u1DpcC:b-issod3) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L67)):*
> ```Java
>             case STAGE_TEMPLATE:
>             case STEP_TEMPLATE:
>                 return new HashSet<>(Arrays.asList("name", "identifier", "description", "orgIdentifier", "projectIdentifier"));
> ```

constants for these exitst



_Code quote:_
```Java
name", "identifier", "description", "orgIdentifier", "projectIdentifier"
```
___
*[`840-template-service/src/main/java/io/harness/template/mappers/TemplateChildEntityTypeToEntityTypeMapper.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YqgcuAAwaNFYpi4QM:-N5YqgcuAAwaNFYpi4QN:b1iqln0) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/mappers/TemplateChildEntityTypeToEntityTypeMapper.java#L29)):*
> ```Java
>         map.put("Approval", EntityType.APPROVAL_STAGE);
>         map.put("CI", EntityType.INTEGRATION_STAGE);
>         map.put("SecurityTests", EntityType.SECURITY_STAGE);
> ```

are we doing schema only for stage and not steps? or is steps entity names matching as steps?



_Code quote:_
```Java
        map.put("Deployment", EntityType.DEPLOYMENT_STAGE);
        map.put("FeatureFlag", EntityType.FEATURE_FLAG_STAGE);
        map.put("Custom", EntityType.CUSTOM_STAGE);
        map.put("Approval", EntityType.APPROVAL_STAGE);
        map.put("CI", EntityType.INTEGRATION_STAGE);
        map.put("SecurityTests", EntityType.SECURITY_STAGE);
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 68 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Yr7P_AIgoTi9ZLHbK:-N5Yr7P_AIgoTi9ZLHbL:bbjge2f) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L68)):*
> ```Java
>             return getTemplateYamlSchemaInternal(accountIdentifier, projectIdentifier, orgIdentifier, scope, templateChildType, templateEntityType);
>         } catch (Exception e) {
>             log.error("[Template] Failed to get pipeline yaml schema", e);
> ```

pipeline? it should be template
___
*[`888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaClientModule.java` line 17 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Ys7570XmfdP3qb2nC:-N5Ys7570XmfdP3qb2nD:b-nmi7rz) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaClientModule.java#L17)):*
> ```Java
> import io.harness.serializer.kryo.KryoConverterFactory;
> 
> public class YamlSchemaClientModule extends AbstractModule {
> ```

Rename this to PipelineYamlSchemaClientModule
___
*[`888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaServiceClient.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YsB-09ckQ1SAHIZSm:-N5YsB-09ckQ1SAHIZSn:bu4jlxt) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaServiceClient.java#L23)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> public interface YamlSchemaServiceClient {
> ```

PipelineYamlSchemaServiceClient
___
*[`960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java` line 127 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YszP98vQasjqS1CtT:-N5YszPA4vtRstGeH-zt:bbr6iux) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java#L127)):*
> ```Java
>     }
>     String[] pathToStageNode = pathToJsonNode.split("/");
>     JsonNode stagesNode = yaml;
> ```

If this field is only used here, then it will always be pipeline/stages



_Code quote:_
```Java
pathToJsonNode.split("/"
```

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 9 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/TemplateServiceApplication.java` line 358 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YpasX9xTNDG3cohUb:-N5ZyJtq3r9U-X0vDSh7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/TemplateServiceApplication.java#L358)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this value is false in pipeline-service, do we know why we are making it to true?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/mappers/TemplateChildEntityTypeToEntityTypeMapper.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YqgcuAAwaNFYpi4QM:-N5Zb6jGEp5a1QMabWjW:b6cg0j0) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/mappers/TemplateChildEntityTypeToEntityTypeMapper.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

are we doing schema only for stage and not steps? or is steps entity names matching as steps?
</blockquote></details>

They are matching for steps
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 68 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Yr7P_AIgoTi9ZLHbK:-N5ZbNQK-buCAygZCtts:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

pipeline? it should be template
</blockquote></details>

Done
___
*[`960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java` line 86 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Z1zea6STl857Bz53h:-N5ZyZBsDnLqrB1_pcu3:bovu7m0) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java#L86)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think this method's responsibility should only be validating the YAML against the schema. We added `shouldValidateParallelStageCount` with keeping in mind that this will be removed from here in future, but now this is making more args to come.
Can we extract the parallel stage count validation out of this method?
</blockquote></details>

Let's take that separately.
As we will want to test more things and I need to hotfix this to qa today
___
*[`960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java` line 127 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YszP98vQasjqS1CtT:-N5Zc0oEBnroimiiP6Tr:b4od5e9) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java#L127)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

If this field is only used here, then it will always be pipeline/stages
</blockquote></details>

We use this for tempate too
In that case it will be template/spec/stages
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YqNBK2tR5DgVRy7as:-N5ZaJb6CAnI4cuhTEnv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we rename it to TemplateYamlSchemaMergeHelper, just so that all modules use generic name
</blockquote></details>

done
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YpoVC2Y06qXVdyQVm:-N5ZyNWm8GjFmBlU8YWF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont think code format is done here
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Yq2CK4KvYpqoRcu-_:-N5YyY4eE4a8pASErjTE:bf3xr7n) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

which constants?
</blockquote></details>

I am using lot of strings here.
I will create a constants file for these with unit test pr
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YqCpE8eTjY0PGKUqb:-N5YwuPF7aZ_R7D0wPLc:b-aiw30m) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

didnt understand this
</blockquote></details>

So pipleineInfoConfig has stages and tempalte.
So only one of them should be present and we are going to add oneOf statement here
So based on that we will have to modify template schema generation logic for pipeline a bit
___
*[`840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Yq8g6Cyl8i2u1DpcB:-N5Zb4lC61L9kfsSqj0C:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/840-template-service/src/main/java/io/harness/template/helpers/YamlSchemaMergeHelper.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

constants for these exitst
</blockquote></details>

Done
___
*[`888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaClientModule.java` line 17 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5Ys7570XmfdP3qb2nC:-N5ZblJF2YdqVHBbuJAK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaClientModule.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Rename this to PipelineYamlSchemaClientModule
</blockquote></details>

Done
___
*[`888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaServiceClient.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/34600#-N5YsB-09ckQ1SAHIZSm:-N5ZbzsAApc0CpEBAlM5:b-fitfs3) ([raw file](https://github.com/harness/harness-core/blob/43bbb8f835a52e1b93e9144052f72a19643cde9b/888-pms-client/src/main/java/io/harness/pipeline/yamlschema/YamlSchemaServiceClient.java#L23)):*
> PipelineYamlSchemaServiceClient
Done

**Comment by abhinavmittal-harness** [comment]
trigger ti4

**Review by archit-harness — APPROVED** [review]
> Reviewed 28 of 28 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 1 change requests. 3. unresolved discussions.

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 1 of 25 files at r1, 1 of 26 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 1 change requests. 2. unresolved discussions.

**Review by inderschera — DISMISSED** [review]
> Reviewed 28 of 28 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 7 of 9 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 1 file(s) to review.

**Comment by abhinavmittal-harness** [comment]
trigger compile

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 9 of 25 files at r1, 20 of 28 files at r10, 5 of 9 files at r11, 1 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34600)* status: 1 file(s) to review.

**Pull request merged**
