### PR TITLE
[feat]: [PL-28667]: Enable Iterators through new environment variable

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes
Enable or disable iterator configuration for the CG Manager through the environment variable ENABLE_ITERATORS. Previously the iterator configuration was always set to true but with this change we can control the configuration through the manifest files.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38170)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38170)

**Review by gn-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38170)* status: :shipit: complete! ✓

___
*[`360-cg-manager/config.yml` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/38170#-NDBWpEDDq4vSrga9Icm:-NDBWpEDDq4vSrga9Icn:b3azmqa) ([raw file](https://github.com/harness/harness-core/blob/2dd8e17e1455f89d7b78c289a84b23038019b323/360-cg-manager/config.yml#L60)):*
> ```YAML
>   #mongoUri: mongodb://localhost:27017/service_scheduler
> 
> enableIterators: ${ENABLE_ITERATORS:-true}
> ```

Were you able to start manager locally and verify the value to this flag flipping?



_Code quote:_
```YAML
enableIterators
```

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38170)* status: :shipit: complete! ✓

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38170)* status: :shipit: complete! ✓

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38170)* status: :shipit: complete! ✓

**Pull request merged**
