### PR TITLE
fix: [IDP-1000]:Internal API for fetching the data points data

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51569)

### CODE REVIEW

**Review by mankrit-singh — DISMISSED** [review]

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51569)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1124 at r1](https://reviewable.io/reviews/harness/harness-core/51569#-NbUWaTDDvgHTtFcwkyA:-NbUWaTDDvgHTtFcwkyB:b-7y4l96) ([raw file](https://github.com/harness/harness-core/blob/f2580dd56759275cd1039491d59ddc60a3a971ed/idp-service/contracts/openapi/v1/openapi.yaml#L1124)):*
> ```YAML
>       x-stoplight:
>         id: o1dppys5mqejp
>   '/v1/data-source/{data-source}/data-point/data':
> ```

How about just `/v1/data-source/{data-source}/data-points`?



_Code quote:_
```YAML
/v1/data-source/{data-source}/data-point/data
```
___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 1130 at r1](https://reviewable.io/reviews/harness/harness-core/51569#-NbUXCAz83LV64N0rc8N:-NbUXCAz83LV64N0rc8O:bueoyhn) ([raw file](https://github.com/harness/harness-core/blob/f2580dd56759275cd1039491d59ddc60a3a971ed/idp-service/contracts/openapi/v1/openapi.yaml#L1130)):*
> ```YAML
>         '200':
>           $ref: '#/components/responses/DataSourceDataPointInfoResponse'
>       operationId: get-v1-data-source-data-point-data
> ```

`get-data-source-data-points`



_Code quote:_
```YAML
get-v1-data-source-data-point-data
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapointsdata/resource/DataPointDataApiImpl.java` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/51569#-NbUXUTS5gHoxeMmEOc1:-NbUXUTS5gHoxeMmEOc2:b-u92kyx) ([raw file](https://github.com/harness/harness-core/blob/f2580dd56759275cd1039491d59ddc60a3a971ed/idp-service/src/main/java/io/harness/idp/scorecard/datapointsdata/resource/DataPointDataApiImpl.java#L1)):*
> ```Java
> package io.harness.idp.scorecard.datapointsdata.resource;
> ```

Why do we need a new package for this? Is this to avoid a circular dependency?
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapointsdata/resource/DataPointDataApiImpl.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/51569#-NbUXaBu8MFJNDWbQCXL:-NbUXaBv8MxMkmnAHD8l:b-jdxkrb) ([raw file](https://github.com/harness/harness-core/blob/f2580dd56759275cd1039491d59ddc60a3a971ed/idp-service/src/main/java/io/harness/idp/scorecard/datapointsdata/resource/DataPointDataApiImpl.java#L13)):*
> ```Java
>   public Response getV1DataSourceDataPointData(
>       String dataSource, @Valid DataSourceDataPointInfoRequest body, String harnessAccount) {
>     return null;
> ```

Is the implementation missing? Or are you planning to take it up later?



_Code quote:_
```Java
null
```

**Review by vikyathharekal — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger uts

**Review by vikyathharekal — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger uts

**Review by mankrit-singh — DISMISSED** [review]

**Comment by devesh-harness** [comment]
trigger ut0, ut1, ut9

**Comment by devesh-harness** [comment]
trigger review

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger messagecheck

**Comment by devesh-harness** [comment]
trigger uts

**Review by sandeepa-kv-jois — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger ut6

**Review by mankrit-singh — APPROVED** [review]

**Comment by mankrit-singh** [comment]
trigger review

**Pull request merged**
