### PR TITLE
feat: [CDS-37242]: Support for variables/service variables in Environment Entity NG

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- [x] Move Environment entity up to 127 module
- [x] Add variables & service variables to Environment entity/DTOs

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 43 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/32923#-N1gaqIz5aQ5Co6SKe9o:-N1gaqIz5aQ5Co6SKe9p:b-iqpjpl) ([raw file](https://github.com/harness/harness-core/blob/dab8648b1b95862ed0375920d4ad844bac6de47b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java#L85)):*
> ```Java
> 
>   private List<NGVariable> variables;
>   private List<NGServiceVariables> svcVariables;
> ```

why service Variables we need to store separately? in yaml it will be part of it? same for variables?



_Code quote:_
```Java
svcVariables
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 43 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/32923#-N1gaqIz5aQ5Co6SKe9o:-N1gdgiWBN_zFozVHRdc:bl9hpo7) ([raw file](https://github.com/harness/harness-core/blob/dab8648b1b95862ed0375920d4ad844bac6de47b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java#L85)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why service Variables we need to store separately? in yaml it will be part of it? same for variables?
</blockquote></details>

these will be at root level. If it is okay to move root level fields to yaml, I can move them

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 43 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/32923#-N1gaqIz5aQ5Co6SKe9o:-N1geNwF4DzOpKLEjuqb:bx79ftu) ([raw file](https://github.com/harness/harness-core/blob/dab8648b1b95862ed0375920d4ad844bac6de47b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/Environment.java#L85)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

these will be at root level. If it is okay to move root level fields to yaml, I can move them
</blockquote></details>

yeah i agree but i think we can check with UI if they don't need it even If they are root levels i don't they will be needed at all apart from yaml, plus at root its not svcVariables, rather its serviceOverrides isn't?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 27 of 44 files at r1, 12 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/BUILD.bazel` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lYaXM2gKRb3bXITtG:-N1lYaXM2gKRb3bXITtH:b-5opdh9) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/260-delegate/BUILD.bazel#L45)):*
> ```Starlark
>         "//950-events-framework:module",
>         "//950-ng-core:module",
>         "//953-yaml-commons:module",
> ```

add kryo and morphia of 953 module into 260 module as you installed this new module



_Code quote:_
```Starlark
//953-yaml-commons:module"
```
___
*[`440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXG-jDiJu0EJsLFA4:-N1lXG-jDiJu0EJsLFA5:b-n4v25q) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java#L35)):*
> ```Java
>           .addAll(NGCoreRegistrars.kryoRegistrars)
>           .addAll(DelegateServiceDriverRegistrars.kryoRegistrars)
>           .addAll(io.harness.serializer.NGCoreClientRegistrars.kryoRegistrars)
> ```

these fqn can be removed



_Code quote:_
```Java
io.harness.serializer
```
___
*[`950-ng-core/BUILD.bazel` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXJU99NLLMd28PkMN:-N1lXJUA3PKd69Cb0IzK:byx3acp) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/950-ng-core/BUILD.bazel#L16)):*
> ```Starlark
>         "//952-scm-java-client:module",
>         "//953-events-api:module",
>         #        "//953-yaml-commons:module",
> ```

this can be deleted
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentRequest.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lYLON6oNYTT7A-eYw:-N1lYLON6oNYTT7A-eYx:b-9bql1u) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentRequest.java#L24)):*
> ```Java
> @Data
> @Builder
> public class EnvironmentRequest implements YamlDTO {
> ```

why we have different pojo for this, shouldnt our yaml pojo be used here which i think you created NGEnvConfig



_Code quote:_
```Java
EnvironmentRequest
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lWmBZCFL1a3kCxQ2S:-N1lWmBZCFL1a3kCxQ2T:bj99i8a) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L69)):*
> ```Java
>         .projectIdentifier(ngEnvironmentInfoConfig.getProjectIdentifier())
>         .name(ngEnvironmentInfoConfig.getName())
>         .color(Optional.ofNullable(ngEnvironmentInfoConfig.getColor()).orElse(HARNESS_BLUE))
> ```

here color should not be there right?



_Code quote:_
```Java
color(Optional.ofNullable(ngEnvironmentInfoConfig.getColor()).orElse(HARNESS_BLUE))
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lWvuV811kXBRIbHbl:-N1lWvuV811kXBRIbHbm:b-ffkv0o) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java#L28)):*
> ```Java
> @OwnedBy(PIPELINE)
> @UtilityClass
> public class NGEnvironmentEntityMapper {
> ```

Why we have 2 mappers? one EnvironmentMapper and NGEnvEntityMapper?
___
*[`950-ng-core/src/main/java/io/harness/ng/core/environment/dto/EnvironmentResponseDTO.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXSrz75MfyH-m04GA:-N1lXSrz75MfyH-m04GB:b-xqx44d) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/950-ng-core/src/main/java/io/harness/ng/core/environment/dto/EnvironmentResponseDTO.java#L26)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(name = "EnvironmentResponseDetails", description = "This is the Environment entity defined in Harness")
> public class EnvironmentResponseDTO {
> ```

Shouldnt env request dto and response dto be part of 960 ng-core-beans always?



_Code quote:_
```Java
EnvironmentResponseDTO
```
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/NGServiceOverrides.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXa2MCLYKV8fyXgwI:-N1lXa2MCLYKV8fyXgwJ:biyhftv) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/NGServiceOverrides.java#L16)):*
> ```Java
> @Builder
> public class NGServiceOverrides {
>   @NotNull private String serviceIdentifier;
> ```

serviceRef



_Code quote:_
```Java
serviceIdentifier
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lWmBZCFL1a3kCxQ2S:-N1lYyHU4RzR_WQwLPzv:bz82042) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

here color should not be there right?
</blockquote></details>

Yes, I will remove that in a separate PR since this already has a lot of fils\es
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lWvuV811kXBRIbHbl:-N1lZ6pj7lRdcEslluCV:bstpgju) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why we have 2 mappers? one EnvironmentMapper and NGEnvEntityMapper?
</blockquote></details>

Not sure, both already existed

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentRequest.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lYLON6oNYTT7A-eYw:-N1ll-A0AEug4Hbb8pNL:bc6mzf2) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentRequest.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we have different pojo for this, shouldnt our yaml pojo be used here which i think you created NGEnvConfig
</blockquote></details>

will do in a separate PR where I will remove the color property
___
*[`950-ng-core/src/main/java/io/harness/ng/core/environment/dto/EnvironmentResponseDTO.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXSrz75MfyH-m04GA:-N1lke1a4FQcLqeTP9WZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/950-ng-core/src/main/java/io/harness/ng/core/environment/dto/EnvironmentResponseDTO.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt env request dto and response dto be part of 960 ng-core-beans always?
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 13 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/BUILD.bazel` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lYaXM2gKRb3bXITtG:-N1ll7AjDGI6oMeNobva:b-fv9l6v) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/260-delegate/BUILD.bazel#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add kryo and morphia of 953 module into 260 module as you installed this new module
</blockquote></details>

removed 953 dependency
___
*[`440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXG-jDiJu0EJsLFA4:-N1llA253cm7N0wMq_K3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/440-connector-nextgen/src/main/java/io/harness/serializer/ConnectorNextGenRegistrars.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

these fqn can be removed
</blockquote></details>

Done.
___
*[`950-ng-core/BUILD.bazel` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXJU99NLLMd28PkMN:-N1llAkN7mtVG63RcPhm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/950-ng-core/BUILD.bazel#L16)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this can be deleted
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 13 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/NGServiceOverrides.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lXa2MCLYKV8fyXgwI:-N1lwfpwCqHPZBnykJG_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/NGServiceOverrides.java#L16)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

serviceRef
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 44 files at r1, 1 of 16 files at r2, 8 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: 1 file(s) to review. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentRequest.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lYLON6oNYTT7A-eYw:-N1m3sIq-ZiifXSukh-h:b-52w3rd) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/EnvironmentRequest.java#L24)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

will do in a separate PR where I will remove the color property
</blockquote></details>

discussed offline to be done in another pr
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lWmBZCFL1a3kCxQ2S:-N1m384i5P0lyGxbRKSM:bg0t9lb) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L69)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes, I will remove that in a separate PR since this already has a lot of fils\es
</blockquote></details>

okay, done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/32923#-N1lWvuV811kXBRIbHbl:-N1m3j0s6fkIYIHrPCbr:b-im0iat) ([raw file](https://github.com/harness/harness-core/blob/17a63540d58ebf8a3880193d73d0f62dee6f94e5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java#L28)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Not sure, both already existed
</blockquote></details>

discussed offline to be handled in another pr

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 28 of 44 files at r1, 8 of 16 files at r2, 4 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32923)* status: :shipit: complete! ✓

**Pull request merged**
