### PR TITLE
[feat]:[pl-29386]: Added error handling for getBranchHeadCommit

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added error handling for getBranchHeadCommit. Tested out the following:
1. Github 
	1. for sending wrong branch: - done
	2. wrong repo name: - done
	3. wrong connector: - done

2. BitBucket
	1. for sending wrong branch: - done
	2. wrong repo name: - done
	3. wrong connector: - done
	

3. ADO 	
	1. for sending wrong branch: - done
	2. wrong repo name: - done
	3. wrong connector: - done
	
		
4. BitBucket OnPrem
	1. for sending wrong branch: - done
	2. wrong repo name: - done
	3. wrong connector: - done
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39356)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbUToElanTCc91b8d:-NFhbUToElanTCc91b8e:bnsz3qp) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
> ```Java
> public class AdoGetBranchHeadCommitScmApiErrorHandler implements ScmApiErrorHandler {
>   public static final String GET_BRANCH_HEAD_COMMIT_FAILED_MESSAGE =
>       "Fetching the branch head commit from Azure failed.";
> ```

Lets re-organize the message as "Failed to fetch branch head commit details".

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbUToElanTCc91b8d:-NFhbdYp3ymU3ziKqqYm:b-ilpziw) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets re-organize the message as "Failed to fetch branch head commit details".
</blockquote></details>

Also, we should add "branchName" into the message. Please check other handlers how its done using string templates.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbpx81-IWLTzEPMKJ:-NFhbpx81-IWLTzEPMKK:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java#L23)):*
> ```Java
> public class BitbucketGetBranchHeadCommitScmApiErrorHandler implements ScmApiErrorHandler {
>   public static final String GET_BRANCH_HEAD_COMMIT_FAILED_MESSAGE =
>       "Fetching the branch head commit from Bitbucket failed.";
> ```

same here

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbtAQ3Rh5SozVSyCI:-NFhbtAQ3Rh5SozVSyCJ:bqj7xs7) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java#L38)):*
> ```Java
>         throw NestedExceptionUtils.hintWithExplanationException(
>             ErrorMessageFormatter.formatMessage(FILE_NOT_FOUND, errorMetadata),
>             ErrorMessageFormatter.formatMessage(ScmErrorExplanations.FILE_NOT_FOUND, errorMetadata),
> ```

why is the explanation for "FILE_NOT_FOUND" used here?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhc4uWEcxbArF5xyiK:-NFhc4uWEcxbArF5xyiL:b56wkfu) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java#L35)):*
> ```Java
>             ErrorMessageFormatter.formatMessage(FILE_NOT_FOUND, errorMetadata),
>             ErrorMessageFormatter.formatMessage(ScmErrorExplanations.FILE_NOT_FOUND, errorMetadata),
>             new ScmBadRequestException(SCMExceptionErrorMessages.FILE_NOT_FOUND_ERROR));
> ```

Why is "FILE_NOT_FOUND" referred here?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmApiErrorHandlerFactory.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcKv-CQGQh8FUJuNC:-NFhcKv-CQGQh8FUJuND:bjvitgc) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmApiErrorHandlerFactory.java#L122)):*
> ```Java
>           .put(Pair.of(ScmApis.GET_BRANCH_HEAD_COMMIT, RepoProviders.GITHUB),
>               GithubGetBranchHeadCommitScmApiErrorHandler.class)
>           .put(Pair.of(ScmApis.GET_BRANCH_HEAD_COMMIT, RepoProviders.BITBUCKET),
> ```

Lets keep the ordering of git providers same as done in previous registrations.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcWkjDlsaNyEeHTwZ:-NFhcWkjDlsaNyEeHTw_:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java#L21)):*
> ```Java
> public class BitbucketServerGetBranchHeadCommitScmApiErrorHandler implements ScmApiErrorHandler {
>   public static final String GET_DEFAULT_BRANCH_FAILED_MESSAGE =
>       "Fetching the branch head commit from Bitbucket failed.";
> ```

same

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhccnC2VCAcS7VwurF:-NFhccnC2VCAcS7VwurG:bc1tzua) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
> ```Java
> @OwnedBy(PL)
> public class BitbucketServerGetBranchHeadCommitScmApiErrorHandler implements ScmApiErrorHandler {
>   public static final String GET_DEFAULT_BRANCH_FAILED_MESSAGE =
> ```

The variable name is wrong.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcgD97A3UYFJIrR9v:-NFhcgD97A3UYFJIrR9w:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
> ```Java
> public class GithubGetBranchHeadCommitScmApiErrorHandler implements ScmApiErrorHandler {
>   public static final String GET_BRANCH_HEAD_COMMIT_FAILED_MESSAGE =
>       "Fetching the branch head commit from Github failed.";
> ```

same

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcy5jB5uy4WEq5qyj:-NFhcy5jB5uy4WEq5qyk:b8k0eby) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java#L42)):*
> ```Java
>             ErrorMessageFormatter.formatMessage(ScmErrorHints.BRANCH_NOT_FOUND, errorMetadata),
>             ErrorMessageFormatter.formatMessage(
>                 GET_BRANCH_HEAD_COMMIT_FAILED_MESSAGE + ScmErrorExplanations.BRANCH_NOT_FOUND, errorMetadata),
> ```

HTTP 422 for BranchNotFound? Just confirming

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39356)* status: 7 file(s) to review. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmApiErrorHandlerFactory.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcKv-CQGQh8FUJuNC:-NFi698t1kuMLeuT7b7S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/ScmApiErrorHandlerFactory.java#L122)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets keep the ordering of git providers same as done in previous registrations.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbUToElanTCc91b8d:-NFi6LT16Vb453xYVQv0:b-dwbs8f) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
> Failed to fetch branch head commit details
branch name will be added, have updated the error message
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbpx81-IWLTzEPMKJ:-NFi6jwC61Fr09JvVFk6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhccnC2VCAcS7VwurF:-NFi7p_vAXiiwZzH3XNS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The variable name is wrong.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcWkjDlsaNyEeHTwZ:-NFi7pv1C8Xz-qnIuxh9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java#L21)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcgD97A3UYFJIrR9v:-NFi7qj53aMPN0pLWhYe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhcy5jB5uy4WEq5qyj:-NFi71oM-FXh5p7sr9FB:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/github/GithubGetBranchHeadCommitScmApiErrorHandler.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

HTTP 422 for BranchNotFound? Just confirming
</blockquote></details>

yes

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39356)* status: 15 file(s) to review. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhc4uWEcxbArF5xyiK:-NFiCZ8jE1P7As9Nnx3X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoGetBranchHeadCommitScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is "FILE_NOT_FOUND" referred here?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/39356#-NFhbtAQ3Rh5SozVSyCI:-NFiDAyP80T2f89-a0JQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f214b763f4e3f24cb9d811b0899dad7f24d32a39/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketGetBranchHeadCommitScmApiErrorHandler.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is the explanation for "FILE_NOT_FOUND" used here? 
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/39356#-NFiHV2C19AQ7tfqiSmt:-NFiHV2D4UT4kREc5nzI:b7xjhgz) ([raw file](https://github.com/harness/harness-core/blob/3963a9baf77a7e00719a9dbbc3c6f3553c74ca5b/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionErrorMessages.java#L22)):*
> ```Java
>   public final String REPOSITORY_NOT_FOUND_ERROR = "Git repository not found";
> 
>   public final String REPO_BRANCH_NOT_FOUND_ERROR = "Repo or branch not found";
> ```

Can we make it "Git repository or branch not found", just to keep it same as other messages as well. Nothing wrong with the current one, but just trying to keep in sync.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/ScmErrorHints.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/39356#-NFiHoI6-eVJ1NTNRkCy:-NFiHoI6-eVJ1NTNRkCz:b90u4b6) ([raw file](https://github.com/harness/harness-core/blob/3963a9baf77a7e00719a9dbbc3c6f3553c74ca5b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/ScmErrorHints.java#L32)):*
> ```Java
> 
>   public static final String WRONG_REPO_OR_BRANCH =
>       "Please check if the provided branch<BRANCH> or the Azure repo name<REPO> are valid.";
> ```

it should be "Bitbucket repo name", can you check if its typo over there as we are in bitbucketserver directory

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/39356#-NFiI5qaEkJTqIodPMOc:-NFiI5qaEkJTqIodPMOd:bax9bet) ([raw file](https://github.com/harness/harness-core/blob/3963a9baf77a7e00719a9dbbc3c6f3553c74ca5b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketserver/BitbucketServerGetBranchHeadCommitScmApiErrorHandler.java#L21)):*
> ```Java
> public class BitbucketServerGetBranchHeadCommitScmApiErrorHandler implements ScmApiErrorHandler {
>   public static final String GET_BRANCH_HEAD_COMMIT_FAILED_MESSAGE =
>       "Failed to fetch branch head commit details from Bitbucket(server).";
> ```

Lets not mention "(server)" anywhere. For consumer, its bitbucket only.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/39356#-NFiIEJMBOcTXsHTN5mq:-NFiIEJMBOcTXsHTN5mr:bber2iy) ([raw file](https://github.com/harness/harness-core/blob/3963a9baf77a7e00719a9dbbc3c6f3553c74ca5b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java#L25)):*
> ```Java
>       "Please check the requested file path<FILEPATH> / branch<BRANCH> / repo name<REPO> if they exist or not.";
>   public static final String WRONG_REPO_OR_BRANCH =
>       "Please check if the provided branch<BRANCH> or the Azure repo name<REPO> are valid.";
> ```

same "azure" mentioned inside bitbucket

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2, 6 of 13 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39356)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger ti0, ti1, ti3, ti4, ft1, ft2, codebasehash

**Comment by adivishy1** [comment]
trigger ft1

**Pull request merged**
