### PR TITLE
fix: [CDS-39584]: validation for variable overrides for empty name

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35214)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35214)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/35214#-N6ggVWd-jBZBYU1qG24:-N6ggVWd-jBZBYU1qG25:b-qfz3zf) ([raw file](https://github.com/harness/harness-core/blob/7582b4bd83aa08cc033796d96c1b6f4859b08f89/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L126)):*
> ```Java
>       for (NGVariable variableOverride : variableOverrides) {
>         if (isEmpty(variableOverride.getName())) {
>           throw new InvalidRequestException(String.format(
> ```

if there are multiple variables with empty names, we should raise an exception with all those violations instead of hinting user one by one

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35214)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/35214#-N6ggVWd-jBZBYU1qG24:-N6gh8GsCkU71sF3Pxbx:b-poexxw) ([raw file](https://github.com/harness/harness-core/blob/7582b4bd83aa08cc033796d96c1b6f4859b08f89/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L126)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if there are multiple variables with empty names, we should raise an exception with all those violations instead of hinting user one by one
</blockquote></details>

I've prompted the service ref but if there is no name provided, how can we ask user to change the specific override?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35214)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/35214#-N6ggVWd-jBZBYU1qG24:-N6glHnpA81Q0ebWxdL4:b-35vcol) ([raw file](https://github.com/harness/harness-core/blob/7582b4bd83aa08cc033796d96c1b6f4859b08f89/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L126)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

We can display # of offending overrides
</blockquote></details>

Yes, number should be fine I guess

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35214)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/35214#-N6ggVWd-jBZBYU1qG24:-N6glOGp2GH1FP0hCxaD:bh9jadl) ([raw file](https://github.com/harness/harness-core/blob/7582b4bd83aa08cc033796d96c1b6f4859b08f89/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L126)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes, number should be fine I guess
</blockquote></details>

for eg. 3 variable overrides do not have a name. Please add names for all the variables and try again

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35214)* status: :shipit: complete! ✓

**Pull request merged**
