### PR TITLE
feat: [CDS-47836]: added GitOps clusters in Execution Summary

### PR DESCRIPTION
**Pull request by vaibhav-si**
Screenshot 2022-12-06 at 12 33 07 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41169)

### CODE REVIEW

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41169)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/GitOpsExecutionSummary.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/41169#-NIab7HT4e8b0p49QSXE:-NIab7HT4e8b0p49QSXF:b-312dmp) ([raw file](https://github.com/harness/harness-core/blob/5551f213d8949ebe7640671544ce20aef5e15642/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/GitOpsExecutionSummary.java#L59)):*
> ```Java
>   @Builder
>   public static class Cluster {
>     String envGroupId;
> ```

To uniquely identify a cluster we have agentId and clusterId. Should we add it here ?

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41169)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/GitOpsExecutionSummary.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/41169#-NIab7HT4e8b0p49QSXE:-NIaddz22GtT_DgNd6SJ:baeeld1) ([raw file](https://github.com/harness/harness-core/blob/5551f213d8949ebe7640671544ce20aef5e15642/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/GitOpsExecutionSummary.java#L59)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

To uniquely identify a cluster we have agentId and clusterId. Should we add it here ?
</blockquote></details>

ClusterId is already present. I can add agentId as well in subsequent PR.

AgentId is not published in the outcome currently. But I see that the DB entity has it. So, will add it in outcome and propagate to Execution Summary.

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/GitOpsExecutionSummary.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/41169#-NIab7HT4e8b0p49QSXE:-NIagn6v-Lso1aBlD9qG:b-pcccan) ([raw file](https://github.com/harness/harness-core/blob/5551f213d8949ebe7640671544ce20aef5e15642/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/GitOpsExecutionSummary.java#L59)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

ClusterId is already present. I can add agentId as well in subsequent PR.

AgentId is not published in the outcome currently. But I see that the DB entity has it. So, will add it in outcome and propagate to Execution Summary.
</blockquote></details>

sounds good, we can add in follow up. Resolving.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41169)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41169)* status: :shipit: complete! ✓

**Pull request merged**
