### PR TITLE
fix: [PL-20995]: Consume secret environment variables in platform ser…

### PR DESCRIPTION
**Pull request by pbarapatre10**
…vice

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29951)

### CODE REVIEW

**Review by filip5rovic — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29951)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger ti4

**Review by filip5rovic — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29951)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29951)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by filip5rovic — APPROVED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29951)* status: :shipit: complete! ✓

**Pull request merged**
