### PR TITLE
fix: [CDS-38030]: fix artifact collection step not working for nexus3

### PR DESCRIPTION
**Pull request by inderschera**
Issue: When we have nexus3 artifact source, the artifact collection step fails with error "Nexus 3.x does not support getVersion for parameterized artifact stream"
Fix: Changed InvalidRequestException to UnsupportedOperationException.
Reason: For GET_BUILD request type in BUILD_SOURCE_TASK, if we get UnsupportedOperationException for any artifact source getBuild() method, we have fallback logic to get all the builds and filter out the requested build number. Since, getting single version is not implemented yet for nexus3, we are throwing UnsupportedOperationException here and then finally getting all the builds and filtering requested build number out. 

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33506)

### CODE REVIEW

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33506)* status: :shipit: complete! ✓

**Comment by inderschera** [comment]
trigger tin1

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33506)* status: :shipit: complete! ✓

**Pull request merged**
