### PR TITLE
fix: [CDS-47428]: Prevent folder/file creation if project/org not exist for Root parent

### PR DESCRIPTION
**Pull request by ivan-83**
The issue was, the user can create a file/folder on an account/org/project that doesn't exist when the parent identifier is Root. The reason is we are not checking whether the root folder exists in DB because it is a logical unit.  
Now we are doing that.

What are changes:
- Prevent folder/file creation if project/org does not exist for the Root parent
- Created the new class FileValidationService to move the non-static validation logic from FileStoreService because FileStoreService becomes larger.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42098)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42098)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 631 at r1](https://reviewable.io/reviews/harness/harness-core/42098#-NKX1T4M-4YE53oX1pxo:-NKX1T4M-4YE53oX1pxp:bvnmiu7) ([raw file](https://github.com/harness/harness-core/blob/9f344fe95d0009d471f7707e8c79fdb7af7f8d01/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L631)):*
> ```Java
>                                format("Org with identifier [%s] does not exist, accountIdentifier: %s", orgIdentifier,
>                                    accountIdentifier)));
>     }
> ```

shall we validate for account existence also?

**Comment by ivan-83** [comment]
trigger copyrightcheck

**Comment by vladimir-peric** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileValidationServiceImpl.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/42098#-NKY7ukbE9-yovJKKJr3:-NKY7ukc5TYw3-G0VEKQ:bqlcraz) ([raw file](https://github.com/harness/harness-core/blob/a1c4e428b829a4a22c671136da3533f6f861ff25/877-filestore/src/main/java/io/harness/filestore/service/impl/FileValidationServiceImpl.java#L86)):*
> ```Java
>                                    accountIdentifier)));
>     } else {
>       accountService.getAccount(accountIdentifier);
> ```

This getAccount() throws exception with hint and is readable enough in ui?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42098)* status: 7 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileValidationServiceImpl.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/42098#-NKY7ukbE9-yovJKKJr3:-NKYBFXr0Ag2_7lcXnJz:b3ild9w) ([raw file](https://github.com/harness/harness-core/blob/a1c4e428b829a4a22c671136da3533f6f861ff25/877-filestore/src/main/java/io/harness/filestore/service/impl/FileValidationServiceImpl.java#L86)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

This getAccount() throws exception with hint and is readable enough in ui? 
</blockquote></details>

yes, that is true, it throws an exception when the account does not exist.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42098)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42098)* status: :shipit: complete! ✓

**Pull request merged**
