### PR TITLE
[feat]:[PIE-7048]: adding git config on save flow

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes
Added the git metadata in onSave flow too

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)

### CODE REVIEW

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/45781#-NRg5img5pCSUywCmuZY:-NRg5img5pCSUywCmuZZ:b1b173i) ([raw file](https://github.com/harness/harness-core/blob/f4c59727f739b03b42cfeca1fc18424b58a04913/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java#L25)):*
> ```Java
>       PipelineEntity pipelineEntity, String pipelineYaml, boolean isExecution, String branch, String action);
>   String getExpandedPipelineJSONFromYaml(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String pipelineYaml, boolean isGitConfigRequired, String branch, PipelineEntity pipelineEntity);
> ```

why to take this flag if it needs to pass always?

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/45781#-NRg5img5pCSUywCmuZY:-NRiiu1i6G8zLz4-N42z:bql3s9f) ([raw file](https://github.com/harness/harness-core/blob/f4c59727f739b03b42cfeca1fc18424b58a04913/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why to take this flag if it needs to pass always?
</blockquote></details>

the implementation of method  validateGovernanceRules above passes the flag as false

**Review by senjucanon2 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/45781#-NRg5img5pCSUywCmuZY:-NRkXthFBy2VGXUdhim2:b-z8kxc9) ([raw file](https://github.com/harness/harness-core/blob/f4c59727f739b03b42cfeca1fc18424b58a04913/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java#L25)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

the implementation of method  validateGovernanceRules above passes the flag as false 
</blockquote></details>

Earlier when i had introduced this flag, it was because there were multiple flows when expandedJsonYaml was fetched and we required it for only execution flow, now if there is no other flow apart from save/execution you can remove the flag altogether @ankittiwari-harness .

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/45781#-NRg5img5pCSUywCmuZY:-NRkqqOkB2029NCCVZVY:bek86ws) ([raw file](https://github.com/harness/harness-core/blob/f4c59727f739b03b42cfeca1fc18424b58a04913/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceService.java#L25)):*
> validateGovernanceRules
@ankittiwari-harness that method is called from get async flow, as we decided every flow should contain git so i think we should remove the flag

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45781)* status: :shipit: complete! ✓

**Pull request merged**
