### PR TITLE
[fix]: [PLG-2847]: made ACTIVE credits come before EXPIRED in credits GET API and added + char to CustomerDTOs

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
This PR covers these 2 bugs:
1. https://harness.atlassian.net/browse/PLG-2847
2. https://harness.atlassian.net/browse/PLG-2832

made ACTIVE credits come before EXPIRED in credits GET and added + char to CustomerDTOs

API Response:
```
{
    "status": "SUCCESS",
    "data": [
        {
            "id": "63a5a8921f2ed11b87c4d348",
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "creditStatus": "ACTIVE",
            "quantity": 100,
            "purchaseTime": 1690848000769,
            "expiryTime": 1698009157,
            "creditType": "FREE",
            "moduleType": "CI"
        },
        {
            "id": "62a5a8921f2ed11b87c4d017",
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "creditStatus": "ACTIVE",
            "quantity": 100,
            "purchaseTime": 1690848000769,
            "expiryTime": 1698009999,
            "creditType": "FREE",
            "moduleType": "CI"
        },
        {
            "id": "64a5a8931f2ed11b87c4d01c",
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "creditStatus": "EXPIRED",
            "quantity": 2000,
            "purchaseTime": 1690848000035,
            "expiryTime": 1693526400035,
            "creditType": "FREE",
            "moduleType": "CI"
        }
    ],
    "metaData": null,
    "correlationId": "c24b16ea-9552-4f5d-807e-891b8957c978"
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53239)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53239)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/53239#-Nf0H8Lh6vOfHzBZH_pE:-Nf0H8Lh6vOfHzBZH_pF:b-1ywi84) ([raw file](https://github.com/harness/harness-core/blob/db784cc2e40536268c07082aca3e1ee3afd8ee08/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L47)):*
> ```Java
>     List<Credit> nonActiveCredits = new ArrayList<>();
>     totalCredits.forEach(credit -> {
>       if (credit.getCreditStatus().equals(CreditStatus.ACTIVE)) {
> ```

better to use reverse comparison : ACTIVE.equals()

**Comment by mohitg0795** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/53239#-Nf0HCLJ9CmKYUCstteV:-Nf0HCLJ9CmKYUCstteW:b-y8b9hj) ([raw file](https://github.com/harness/harness-core/blob/db784cc2e40536268c07082aca3e1ee3afd8ee08/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L45)):*
> ```Java
> 
>     List<Credit> activeCredits = new ArrayList<>();
>     List<Credit> nonActiveCredits = new ArrayList<>();
> ```

nit: "inactive" would be better word

**Comment by kapil-harness** [comment]
trigger uts

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53239)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/53239#-Nf0HCLJ9CmKYUCstteV:-Nf7egpT6B_icqKWSlfy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/db784cc2e40536268c07082aca3e1ee3afd8ee08/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: "inactive" would be better word
</blockquote></details>

done
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/53239#-Nf0H8Lh6vOfHzBZH_pE:-Nf7ei68Evm9t4d4tLlJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/db784cc2e40536268c07082aca3e1ee3afd8ee08/930-ng-license-manager/src/main/java/io/harness/credit/services/impl/CreditServiceImpl.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

better to use reverse comparison : ACTIVE.equals()
</blockquote></details>

done

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53239)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by neelam-harness — APPROVED** [review]
lgtm!

**Comment by kapil-harness** [comment]
trigger messagecheck

**Pull request merged**
