### PR TITLE
feat: [DEL-3736]: Add mTLS to kubernetes yaml for immutable delegate

### PR DESCRIPTION
**Pull request by johannesHarness**
## Describe your changes
This PR adds mTLS support to our template generation for immutable delegate.
The functionality is only added to kubernetes (as that's the only mode supported by immutable delegate as of now), and only is being executed if the account has mTLS enabled.

**Yaml Changes**
1. Add new Secret resource that contains certificate cert and pem files which will be mounted to the upgrader / delegate pod. Values are set with placeholders that aren't valid, so the customer has to replace the cert information with the correct data or the deployment will fail. The other option for customers is to remove the secret from the yaml and replace its references with a new value -> would make sense to have a link to documentation before we GA the feature.
The **name** of the secret will be `{delegate-name}-client-certificate`.

1. Mount the secret as volume to the delegate deployment

1. Add ENV values to delegate pointing to the mounted cert files and disabling gRPC authority modification (required for delegate-gateway)
 
1. Mount the secret to the upgrader pod

1. Add entries to the upgrader configuration (in configmap) pointing to the mounted cert files.

Please reference the generated yamls linked in the testing section for reference yamls.

***DelegateMtlsEndpointService Changes***
Some environments (qa, prod) or applications (migration, ...) aren't configured yet with the delegateMtlsSubdomain value in the manager configuration. To avoid that such environments fail to start up, I added a `DelegateMtlsEndpointServiceReadOnlyImpl` class which is registered for the `DelegateMtlsEndpointService` interface in case no `delegateMtlsSubdomain` value is provided in the configuration.
This will allow all other functionalities (download yaml, datapath mTLS check, ...) to work, but adding / updating /deleting mtlsEndpoints will fail. Which is okay to happen if mTLS hasn't been setup yet in an environment.

### Testing
I've ran both CG & NG manager + UI locally and generated the yaml for multiple combinations of immutable and mTLS.
The generated yamls can be found here:
https://harness.atlassian.net/wiki/spaces/~203497205/pages/21110980760/Yaml+Changes

Furthermore, I've deployed the changes in PR and used them together with my [delegate changes](https://github.com/harness/harness-core/pull/34139) to verify that everything is working as expected

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34521)

### CODE REVIEW

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34521)* status: Some of the checks are too old.

**Review by mdmilic — CHANGES_REQUESTED** [review]
Are all the configurations to use `delegate.local.harness.io` intentional or leftover from testing?

> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34521#-:-N5eT9gY8mZMtzODWUFJ:b7qi1ai)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1514 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eQd-R2rL7eYVo8Iwg:-N5eQd-R2rL7eYVo8Iwh:blshf2a) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1514)):*
> ```Java
> 
>   @VisibleForTesting
>   public TemplateParameters finalizeTemplateParametersWithMtlsIfRequired(
> ```

I think it's probably better for this method to return builder instead.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1517 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eQw-A21pB9VuJ2zXn:-N5eQw-A21pB9VuJ2zXo:b-93qt52) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1517)):*
> ```Java
>       TemplateParametersBuilder templateParametersBuilder) {
>     // build to retrieve current state of builder
>     TemplateParameters original = templateParametersBuilder.build();
> ```

You shouldn't build it twice (here and at the bottom). Builder is not guaranteed to be idempotent (I think it is in this case, but still shouldn't be done.) but also creates extra objects. 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1572 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5ePPaU4131xvUaAhUL:-N5ePPaU4131xvUaAhUM:blns7kk) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1572)):*
> ```Java
>     try {
>       String originalPath = new URI(originalUri).getPath();
>       String basePath = new URI(baseUri).getPath();
> ```

Not sure I understand the reasoning behind these conversions to URI and back to String. Also, you can consider using URI.create(...) convenience factory method which does the same thing as you (wraps the checked exception and throws unchecked - IllegalArgumentException if I recall correctly).



_Code quote:_
```Java
      String originalPath = new URI(originalUri).getPath();
      String basePath = new URI(baseUri).getPath();

      String newPath =
          isNotBlank(basePath) && isNotBlank(originalPath) ? originalPath.replace(basePath, "") : originalPath;

      return new URI("https", mtlsEndpointFqdn, newPath, null, null).toString();
```
___
*[`400-rest/src/supporter-test/java/software/wings/rules/WingsRule.java` line 475 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eShNW5pkk9gIBErKV:-N5eShNW5pkk9gIBErKW:b-twqble) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/supporter-test/java/software/wings/rules/WingsRule.java#L475)):*
> ```Java
>     modules.add(TestMongoModule.getInstance());
>     modules.add(new SpringPersistenceTestModule());
>     modules.add(new DelegateServiceModule("delegate.ut.harness.io"));
> ```

Was this intentional?
___
*[`420-delegate-service/src/main/java/io/harness/service/intfc/DelegateMtlsEndpointService.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eUKdx3SeCQlU4P0Ln:-N5eUKdx3SeCQlU4P0Lo:bt10ze5) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/420-delegate-service/src/main/java/io/harness/service/intfc/DelegateMtlsEndpointService.java#L75)):*
> ```Java
>    * @return The details of the requested delegate mTLS endpoint or null if it doesn't exist.
>    */
>   DelegateMtlsEndpointDetails getEndpointForAccountOrNull(String accountId);
> ```

Consider marking the method as `@Nullable` to indicate that it can return null, or even use `Optional<DelegateMtlsEndpointDetails>` return instead if you want to be explicit. With the annotation you get a warning from the IntelliJ if you misuse the method.

**Comment by johannesHarness** [comment]
*[`400-rest/src/supporter-test/java/software/wings/rules/WingsRule.java` line 475 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eShNW5pkk9gIBErKV:-N5eh3NB2fecf1gPku6U:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/supporter-test/java/software/wings/rules/WingsRule.java#L475)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Was this intentional?
</blockquote></details>

yes

**Comment by johannesHarness** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/intfc/DelegateMtlsEndpointService.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eUKdx3SeCQlU4P0Ln:-N5eh7Oe63Bl2X_w0jEa:b-5uk7ez) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/420-delegate-service/src/main/java/io/harness/service/intfc/DelegateMtlsEndpointService.java#L75)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Consider marking the method as `@Nullable` to indicate that it can return null, or even use `Optional<DelegateMtlsEndpointDetails>` return instead if you want to be explicit. With the annotation you get a warning from the IntelliJ if you misuse the method. 
</blockquote></details>

okay, will do!

**Comment by johannesHarness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1517 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eQw-A21pB9VuJ2zXn:-N5eggZ-DUfXGBgjjyIW:b-s06cf1) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1517)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You shouldn't build it twice (here and at the bottom). Builder is not guaranteed to be idempotent (I think it is in this case, but still shouldn't be done.) but also creates extra objects. 
</blockquote></details>

Hmm that's why I have unit tests for it, to ensure that's the case. Do you know how else I could read out the values?
There are ways to generate a new builder out of the original object and then return that, but I wanted to avoid impacting existing code.

**Comment by johannesHarness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1514 at r2](https://reviewable.io/reviews/harness/harness-core/34521#-N5eQd-R2rL7eYVo8Iwg:-N5ekNrN4ZxPwKt2lY6r:bp9msmb) ([raw file](https://github.com/harness/harness-core/blob/f0a4493957d2d2525f408473e0e7e17ad53bbc47/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1514)):*
<details><summary><i>Previously, johannesHarness (Johannes Batzill) wrote…</i></summary><blockquote>

I was thinking about that too, can do that.
</blockquote></details>

But then I can't read the values. I could regenerate a builder from the existing object (lombok supports that), but then that would be a bigger risk for existing code flow.

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34521)* status: :shipit: complete! ✓

**Comment by johannesHarness** [comment]
trigger ti1

**Pull request merged**
