### PR TITLE
feat: [PIE-8756]: Add API to update repo URL for pipelines of given scope

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44720)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/44720#-NPn5h0W7bZqM7Osa6u9:-NPn5h0W7bZqM7Osa6uA:b-l2d77f) ([raw file](https://github.com/harness/harness-core/blob/dbbdd3e3ecf686bdf20dbd759094580e4f879ca7/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L399)):*
> ```Java
> 
>     registerCorrelationFilter(environment, injector);
>     //    registerNotificationTemplates(injector);
> ```

is this intentional ?

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 556 at r2](https://reviewable.io/reviews/harness/harness-core/44720#-NPn6NSA707DA7tLstsL:-NPn6NSA707DA7tLstsM:ba0114v) ([raw file](https://github.com/harness/harness-core/blob/dbbdd3e3ecf686bdf20dbd759094580e4f879ca7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L556)):*
> ```Java
>         InputSetEntity updatedInputSet = inputSetRepository.update(criteriaToUpdate, update);
>         updatedInputSetList.add(updatedInputSet);
>         log.info("Updated Repo URL for Input Set {}", updatedInputSet);
> ```

can we just log identifier here instead of the entire object ?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 556 at r2](https://reviewable.io/reviews/harness/harness-core/44720#-NPn6NSA707DA7tLstsL:-NPn6rNo7U6iyciHNMGn:b-7sqxvi) ([raw file](https://github.com/harness/harness-core/blob/dbbdd3e3ecf686bdf20dbd759094580e4f879ca7/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L556)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we just log identifier here instead of the entire object ?
</blockquote></details>

It was a limited operation, so thought to log complete stuff, just for backup. Let me only update repo url here as we update it was the only field.

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44720)* status: 11 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/44720#-NPn5h0W7bZqM7Osa6u9:-NPn6m7mElfV11AiEegm:bdv5i7k) ([raw file](https://github.com/harness/harness-core/blob/dbbdd3e3ecf686bdf20dbd759094580e4f879ca7/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L399)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional ?
</blockquote></details>

Removed it, typo error

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44720)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44720)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
