### PR TITLE
feat: [CDS-56488]: OPA Policy Expansion for multi environments

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- [feat]: [CDS-56488]: Expansion handler working fine, replacement strategy pending
- [feat]: [56488]: Fix ExpansionsMerger
- [feat]: [56488]: Implement toJson method
- [feat]: [56488]: Use REPLACE strategy
- [feat]: [56488]: Add test for MultiEnvExpandedValue
- [feat]: [56488]: Add test for MultiEnvironmentExpansionHandlerTest
- [feat]: [56488]: Rename values field in MultiEnvExpandedValue

## Describe your changes
Add expansion handler for "stage/spec/environments" key in deploy stage
The expanded yaml can be found here for reference: https://harness.atlassian.net/wiki/spaces/CDNG/pages/21347631653/OPA+for+multi+environments
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-45752]: https://harness.atlassian.net/browse/CDS-45752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)

[CDS-56488]: https://harness.atlassian.net/browse/CDS-56488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-56488]: https://harness.atlassian.net/browse/CDS-56488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-56488]: https://harness.atlassian.net/browse/CDS-56488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/45786#-NRd_MdkBthq-Woj7Ha3:-NRd_MdkBthq-Woj7Ha4:be8t0x6) ([raw file](https://github.com/harness/harness-core/blob/5bde26c8ea39fd980a9e9b190cedbd5a2539bfe1/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L90)):*
> ```Java
> 
>     final Optional<String> envRefOpt = EnvironmentExpansionUtils.getEnvRefFromEnvYamlV2Node(envYamlV2Node);
>     if (envRefOpt.isEmpty()) {
> ```

Todo: update error messages

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)* status: 11 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/45786#-NRgS8WU4PFrqqo0T0Du:-NRgS8WU4PFrqqo0T0Dv:b9rde3l) ([raw file](https://github.com/harness/harness-core/blob/177ae06d70fb0e9a8583c965ba54c0d4cfecd8a4/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L64)):*
> ```Java
>       JsonNode environments = fieldValue.get("values");
>       if (!environments.isArray()) {
>         return ExpansionResponse.builder().success(false).errorMessage("field is not an array").build();
> ```

for eg. if  we have ```values: <+input>```, do we want to set success as false?
___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/45786#-NRgTjwG9e-8LAypxJNx:-NRgTjwG9e-8LAypxJNy:b-w2s6zs) ([raw file](https://github.com/harness/harness-core/blob/177ae06d70fb0e9a8583c965ba54c0d4cfecd8a4/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L136)):*
> ```Java
> 
>     final List<InfrastructureEntity> infrastructures =
>         infrastructureService.getAllInfrastructureFromIdentifierList(accountId, orgId, projectId, envId, identifiers);
> ```

we should pass envRef instead of env id since we're using org,project from context which might be different

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/45786#-NRgS8WU4PFrqqo0T0Du:-NRhKsXD1pQPyJc_Gki1:b3eoq6z) ([raw file](https://github.com/harness/harness-core/blob/177ae06d70fb0e9a8583c965ba54c0d4cfecd8a4/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L64)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

for eg. if  we have ```values: <+input>```, do we want to set success as false?
</blockquote></details>

Yes, that means so expansion so the original yaml remains as is
For eg.
```
environments:
   values: <+input>
```

The expanded json is 
```
"environments":
                        {
                            "metadata":
                            {
                                "parallel": true
                            },
                            "values": "<+input>"
                        }
```

**Comment by yogesh-chauhan** [comment]
trigger ut6, ut7

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentExpansionUtils.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/45786#-NRmqpRN7MXCehNP6c9Y:-NRmqpRN7MXCehNP6c9Z:btcqtut) ([raw file](https://github.com/harness/harness-core/blob/05530bb1506cf0cbb6d2831ba8bb4080c1c87633/125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentExpansionUtils.java#L106)):*
> ```Java
>   }
> 
>   static List<InfrastructureDataBag> getInfraRefAndInputs(JsonNode fieldValue) {
> ```

Do we also need handling for infrastructure identifier as an expression here?

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/45786#-NRmrDgj5LsnZlz_HOEU:-NRmrDgj5LsnZlz_HOEV:b-77x7pl) ([raw file](https://github.com/harness/harness-core/blob/05530bb1506cf0cbb6d2831ba8bb4080c1c87633/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L192)):*
> ```Java
>   }
> 
>   private Map<String, ConnectorResponseDTO> getConnectorRefToDTOMap(
> ```

I think for connectorRef as an expression we are replacing it with an ObjectNode right?



_Code snippet:_
```Java
  static InfrastructureExpandedValue buildInfraExpandedValue(ObjectMapper objectMapper, Environment environment,
      InfrastructureConfig infrastructureConfig, ConnectorResponseDTO connectorDTO) {
    return InfrastructureExpandedValue.builder()
        .infrastructureDefinition(InfrastructureValue.builder()
                                      .type(infrastructureConfig.getInfrastructureDefinitionConfig().getType())
                                      .spec(infrastructureConfig.getInfrastructureDefinitionConfig().getSpec())
                                      .build())
        .environment(EnvironmentMapper.toBasicInfo(environment))
    -->    .infrastructureConnectorNode(
            connectorDTO != null ? objectMapper.convertValue(connectorDTO.getConnector(), ObjectNode.class) : null) <--
        .build();
  }
```

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/45786#-NRmrDgj5LsnZlz_HOEU:-NRmsoSO0y67CLGAnVXu:b7s6vml) ([raw file](https://github.com/harness/harness-core/blob/05530bb1506cf0cbb6d2831ba8bb4080c1c87633/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L192)):*
> replacing it with an ObjectNode right?
replacing it with an NULL right?

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 3 of 7 files at r2, 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentExpansionUtils.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/45786#-NRmqpRN7MXCehNP6c9Y:-NRnLqjK1T4Tb5OKiTV5:b-vkwfxt) ([raw file](https://github.com/harness/harness-core/blob/05530bb1506cf0cbb6d2831ba8bb4080c1c87633/125-cd-nextgen/src/main/java/io/harness/pms/governance/EnvironmentExpansionUtils.java#L106)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Do we also need handling for infrastructure identifier as an expression here?
</blockquote></details>

Not needed for now. The caller method handles it 
___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/45786#-NRmkvOVEXQLavFsJm4L:-NRnLxr3C1WoPOZOxlzi:bi6e0c2) ([raw file](https://github.com/harness/harness-core/blob/05530bb1506cf0cbb6d2831ba8bb4080c1c87633/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvironmentExpansionHandler.java#L133)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

I see this method is only handling one infrastructure under environment node,
are we planning to handle multiple infrastructure later?

</blockquote></details>

Added it. I found this while testing yesterday but did not push yet :sweat_smile:

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 6 of 8 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvExpandedValue.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/45786#-NRnSOZMEFC0YKe3PGJZ:-NRnSOZMEFC0YKe3PGJ_:bcskjsj) ([raw file](https://github.com/harness/harness-core/blob/6ef280f89b447d47bbc58b6a702ce598b71f1124/125-cd-nextgen/src/main/java/io/harness/pms/governance/MultiEnvExpandedValue.java#L49)):*
> ```Java
>     Map<String, Object> map = new HashMap<>();
>     if (metadata != null) {
>       map.put(VALUES, environments);
> ```

we're now putting values in map conditionally on metadata. Is this expected?

**Review by tchaurasiya — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786#-:-NRq40er7hmbrep5ysBB:bnfp4nl)* status: 3 file(s) to review.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45786)* status: :shipit: complete! ✓

**Pull request merged**
