### PR TITLE
[feat]:[pl-29060]: adding repo filter for template listing and selection

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Adding repo filter for template listing and selection, tested out the filter repo logic via postman for template listing and template selection in gitx project 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38906)

### CODE REVIEW

**Review by mankrit-singh — DISMISSED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38906)* status: :shipit: complete! ✓

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java` line 196 at r3](https://reviewable.io/reviews/harness/harness-core/38906#-NEixyD2ArZeSzuFVUMQ:-NEixyD2ArZeSzuFVUMR:bx82qhy) ([raw file](https://github.com/harness/harness-core/blob/7fd8b8af90eee992fb15013a713196c32bbffc1d/840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java#L196)):*
> ```Java
>                  .build())
>         .add(CompoundMongoIndex.builder()
>                  .name("filter_by_repo")
> ```

for index, there's nothing like filter or anything else. Its pale index creation. So, we should follow consistent naming convention that defines the fields in an index: eg: "accountId_orgId_projectId_repo" something like this .

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/38906#-NEiyGtoDiAtrmkrhkO0:-NEiyGtoDiAtrmkrhkO1:b70mxci) ([raw file](https://github.com/harness/harness-core/blob/7fd8b8af90eee992fb15013a713196c32bbffc1d/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L278)):*
> ```Java
>       criteria.andOperator(criteriaList.toArray(new Criteria[0]));
>     }
>     if (templateFilter.getRepoName() != null && EmptyPredicate.isNotEmpty(templateFilter.getRepoName())) {
> ```

isNotEmpty() automatically checks for null as well.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 309 at r3](https://reviewable.io/reviews/harness/harness-core/38906#-NEiyMfOAj7g6zdU4PZF:-NEiyMfOAj7g6zdU4PZG:bn9w7po) ([raw file](https://github.com/harness/harness-core/blob/7fd8b8af90eee992fb15013a713196c32bbffc1d/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L309)):*
> ```Java
>       criteria.andOperator(criteriaList.toArray(new Criteria[0]));
>     }
>     if (templateFilter.getRepoName() != null && EmptyPredicate.isNotEmpty(templateFilter.getRepoName())) {
> ```

repetitive code in same file, should be modularized.

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38906)* status: 0 of 1 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38906)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java` line 196 at r3](https://reviewable.io/reviews/harness/harness-core/38906#-NEixyD2ArZeSzuFVUMQ:-NEj-wwe1Vie-qKdGtZh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7fd8b8af90eee992fb15013a713196c32bbffc1d/840-template-service/src/main/java/io/harness/template/entity/TemplateEntity.java#L196)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

for index, there's nothing like filter or anything else. Its pale index creation. So, we should follow consistent naming convention that defines the fields in an index: eg: "accountId_orgId_projectId_repo" something like this .
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/38906#-NEiyGtoDiAtrmkrhkO0:-NEj0wjt3RLmec-Eb85K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7fd8b8af90eee992fb15013a713196c32bbffc1d/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L278)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

isNotEmpty() automatically checks for null as well.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 309 at r3](https://reviewable.io/reviews/harness/harness-core/38906#-NEiyMfOAj7g6zdU4PZF:-NEj1csx28Vt351aA9Ob:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7fd8b8af90eee992fb15013a713196c32bbffc1d/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L309)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

repetitive code in same file, should be modularized.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38906)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38906)* status: :shipit: complete! ✓

**Pull request merged**
