### PR TITLE
fix: [PIE-8981]: Auto-abort previous execution not working as expecte…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…d for chaining pipeline

## Describe your changes
Child execution api call happens via async call. If user aborts the parent pipeline, if abort call thread is faster than child execution api call (which is possible as it contains a run api call), then child execution details will not be present at the time of interrupt registration.

As a fix, I have added a check in PipelineSetupStep to check if the current execution is a child pipeline or not. If child, then we will check if there is any abort interrupt in its parent. If yes, we will register an interrupt for child pipeline too.

Note: These changes will get activated only for the edge case. If child pipeline is already running, and user aborts the parent pipeline, then interrupt will be registered from PipelineStageStep itself.

Tested in local

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger ut5

**Comment by prashantsharma04** [comment]
trigger ut9

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java` line 57 at r5](https://reviewable.io/reviews/harness/harness-core/45230#-NQj5erW4RHGQrOkghAA:-NQj6I881LuwwbHR2gZf:bijjz2r) ([raw file](https://github.com/harness/harness-core/blob/4c218382fe5f41e7e00159d297073e7497ea8406/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java#L57)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what if interrupt is registered in pipelineStageStep as well?
</blockquote></details>

This step would have been executed by then
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java` line 76 at r5](https://reviewable.io/reviews/harness/harness-core/45230#-NQj5aWs2yGemQiP35nc:-NQj5wul-lXMWYzFLoPG:bkfqkqz) ([raw file](https://github.com/harness/harness-core/blob/4c218382fe5f41e7e00159d297073e7497ea8406/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java#L76)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

pmsExecutionService.registerInterrupt( why we are not using this?
</blockquote></details>

pmsExecutionService is not accessible from orchestration module. PmsExecutionService is in service module.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java` line 57 at r5](https://reviewable.io/reviews/harness/harness-core/45230#-NQj5erW4RHGQrOkghAA:-NQj76s86_fg8xezulrO:b-rvtts1) ([raw file](https://github.com/harness/harness-core/blob/4c218382fe5f41e7e00159d297073e7497ea8406/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java#L57)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

This step would have been executed by then
</blockquote></details>

Have added try catch just in case there is abort in parent along with pipelineSetUp step is running for child

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/45230#-NQj99Jl2vJiRCbjnBzV:-NQj99Jl2vJiRCbjnBzW:bk7ffgf) ([raw file](https://github.com/harness/harness-core/blob/185b420f0de774f74fad8bd5b868f9627a365579/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java#L64)):*
> ```Java
>           handleAbort(ambiance, interrupts.get(0).getInterruptConfig());
>         } catch (Exception e) {
>           log.error("Error during interrupt registration ", e);
> ```

move to warn 



_Code quote:_
```Java
error
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/45230#-NQj99Jl2vJiRCbjnBzV:-NQxEmET8AD8R8tJOuSx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/185b420f0de774f74fad8bd5b868f9627a365579/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline/PipelineSetupStep.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

move to warn 
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45230)* status: Some of the checks are too old.

**Pull request closed without merging**
