### PR TITLE
[feat]: [CDP-18940]: support inline hosts

### PR DESCRIPTION
**Pull request by tmacari-harness**
[feat]: [CDP-18940]: support inline hosts

[CDP-18940]: https://harness.atlassian.net/browse/CDP-18940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java, line 91 at r1](https://reviewable.io/reviews/harness/harness-core/30094#-MtrttXd-iUHi3lBQMPI:-MtrttXd-iUHi3lBQMPJ:beqwevl) ([raw file](https://github.com/harness/harness-core/blob/418d25fc0ffd29c3e911e70720da398ef68079f8/400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java#L91)):*
> ```Java
> import java.util.stream.Collectors;
> import lombok.extern.slf4j.Slf4j;
> import org.jetbrains.annotations.NotNull;
> ```

are we using this somewhere?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java, line 91 at r1](https://reviewable.io/reviews/harness/harness-core/30094#-MtrttXd-iUHi3lBQMPI:-MtrymO27KXsHxPVhbdR:b-i0fjgx) ([raw file](https://github.com/harness/harness-core/blob/418d25fc0ffd29c3e911e70720da398ef68079f8/400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java#L91)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

are we using this somewhere?
</blockquote></details>

I think it got added here by IntelliJ when I was extracting a method. I can remove it, but does'n have any functional impact.
@NotNull
 private List<String> getResolvedHosts(ExecutionContext context, List<String> hosts) {

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java, line 91 at r1](https://reviewable.io/reviews/harness/harness-core/30094#-MtrttXd-iUHi3lBQMPI:-MtvhZWO0ON7cKL6sjft:b-s3nifr) ([raw file](https://github.com/harness/harness-core/blob/418d25fc0ffd29c3e911e70720da398ef68079f8/400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java#L91)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I think it got added here by IntelliJ when I was extracting a method. I can remove it, but does'n have any functional impact.
@NotNull
 private List<String> getResolvedHosts(ExecutionContext context, List<String> hosts) {

</blockquote></details>

let's remove it since it adds unused import and unnecessary dependency.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java, line 1485 at r4](https://reviewable.io/reviews/harness/harness-core/30094#-MuJC38tA4CTSb9pXUMw:-MuJC38tA4CTSb9pXUMx:b-tosuge) ([raw file](https://github.com/harness/harness-core/blob/76d0f6c342f6e49f3c887257d1b8c2f69dcec0ce/400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java#L1485)):*
> ```Java
>         if (isNotEmpty(pyInfraMapping.hosts())) {
>           if (featureFlagService.isEnabled(DEPLOY_TO_INLINE_HOSTS, infrastructureMapping.getAccountId())
>               && isNotEmpty(selectionParams.getHostNames())) {
> ```

are we ignoring the hosts coming from pyinfraMapping.getHosts()
___
*[400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java, line 272 at r4](https://reviewable.io/reviews/harness/harness-core/30094#-MuJOxr87I5W0UWqV_0l:-MuJOxr9Ba-n397nD1vY:b-xqlzeh) ([raw file](https://github.com/harness/harness-core/blob/76d0f6c342f6e49f3c887257d1b8c2f69dcec0ce/400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java#L272)):*
> ```Java
>         .map(s -> Arrays.asList(s.split(",")))
>         .flatMap(resolvedHosts -> resolvedHosts.stream().map(String::trim))
>         .collect(toList());
> ```

should we use Set instead of List ?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java, line 1485 at r4](https://reviewable.io/reviews/harness/harness-core/30094#-MuJC38tA4CTSb9pXUMw:-MuKH26PEGzjjN-dXGaO:bvbadkz) ([raw file](https://github.com/harness/harness-core/blob/76d0f6c342f6e49f3c887257d1b8c2f69dcec0ce/400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java#L1485)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we ignoring the hosts coming from pyinfraMapping.getHosts()
</blockquote></details>

If isNotEmpty(pyInfraMapping.hosts())  then it is a dynamic infra.
If user choose to deploy to some specific hosts we have to deploy just to those.
___
*[400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java, line 272 at r4](https://reviewable.io/reviews/harness/harness-core/30094#-MuJOxr87I5W0UWqV_0l:-MuKGqlP9uj1mppuDrIi:b-rju1oi) ([raw file](https://github.com/harness/harness-core/blob/76d0f6c342f6e49f3c887257d1b8c2f69dcec0ce/400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java#L272)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we use Set instead of List ?
</blockquote></details>

Will add .distinct() to stream so we will have uniques values.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java, line 91 at r1](https://reviewable.io/reviews/harness/harness-core/30094#-MtrttXd-iUHi3lBQMPI:-MuKHzxiB7uL3_HaM-Mw:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/418d25fc0ffd29c3e911e70720da398ef68079f8/400-rest/src/main/java/software/wings/sm/states/NodeSelectState.java#L91)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

let's remove it since it adds unused import and unnecessary dependency.
</blockquote></details>

Done

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30094)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
