### PR TITLE
[feat]: [CDS-44020]: Adding UpdateReleaseRepo step with variables

### PR DESCRIPTION
**Pull request by lasdox**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38092)

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 24 files at r1, 17 of 17 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoBaseStepInfo.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA3M7D8z8V87vadZOI:-NDA3M7D8z8V87vadZOJ:bi2ci1m) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoBaseStepInfo.java#L45)):*
> ```Java
>   @ApiModelProperty(dataType = BOOLEAN_CLASSPATH)
>   @YamlSchemaTypes({string})
>   ParameterField<Boolean> overrideConfig;
> ```

We should remove this
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoOutcome.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA3SA_DF5pzWdOS9F1:-NDA3SAa3Dcb2uv9xx4P:b-btahge) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoOutcome.java#L10)):*
> ```Java
> package io.harness.cdng.gitops;
> 
> import static io.harness.annotations.dev.HarnessTeam.CDP;
> ```

Change it to GitOps Team
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoOutcome.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA3Uib6cZfSwGYtLxA:-NDA3Uib6cZfSwGYtLxB:b-wg7y5h) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoOutcome.java#L23)):*
> ```Java
> import org.springframework.data.annotation.TypeAlias;
> 
> @OwnedBy(CDP)
> ```

Change it to GitOps
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java` line 195 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA3tkBDwfMZ_SzPTwy:-NDA3tkCAaRACbUHRdnM:b1imib0) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java#L195)):*
> ```Java
>       String file = Strings.EMPTY;
> 
>       for (GitopsClustersOutcome.ClusterData cluster : clustersData) {
> ```

There is another PR that is going to change some logic around this for Create PR step. Please get those changes before we merge it.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepNode.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA4HEjBOOTODObqYii:-NDA4HEjBOOTODObqYij:b-bsq1vi) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepNode.java#L36)):*
> ```Java
> @JsonTypeName(StepSpecTypeConstants.GITOPS_UPDATE_RELEASE_REPO)
> @TypeAlias("UpdateReleaseRepoStepNode")
> @OwnedBy(CDP)
> ```

Change it to GitOps team
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepParams.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA4OJW0jMkVcVAqKoO:-NDA4OJW0jMkVcVAqKoP:b-sqbapv) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepParams.java#L22)):*
> ```Java
>   @Builder(builderMethodName = "infoBuilder")
>   public UpdateReleaseRepoStepParams(ParameterField<List<TaskSelectorYaml>> delegateSelectors,
>       ParameterField<Map<String, String>> stringMap, ShellType shellType, ParameterField<Boolean> overrideConfig) {
> ```

Remove the shell type and override config



_Code quote:_
```Java
ShellType shellType, ParameterField<Boolean> overrideConfig
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 131 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA4SofBbJWef1V7spG:-NDA4SofBbJWef1V7spH:b-3kig0a) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L131)):*
> ```Java
>     }
>     try {
>       IndividualClusterInternal validCluster = IndividualClusterInternal.builder().clusterName("test").clusterRef("cluster3").envName("env1").build();
> ```

Remove this code.
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 2241 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA4ipl0hHjUPz2-Pzg:-NDA4ipl0hHjUPz2-Pzh:b-9jwj6) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L2241)):*
> ```JSON
>           "required": [
>             "overrideConfig",
>             "shell"
> ```

This code needs to be removed once we remove the shell and overrideConfig



_Code quote:_
```JSON
          "required": [
            "overrideConfig",
            "shell"
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/38092#-NDA4tzL8ECmGFhyKBd5:-NDA4tzL8ECmGFhyKBd6:bkhmqdw) ([raw file](https://github.com/harness/harness-core/blob/9971844261be550c377cd7d52783da0d21fd42a7/127-cd-nextgen-entities/src/main/java/io/harness/executions/steps/StepSpecTypeConstants.java#L18)):*
> ```Java
>   String GITOPS_CREATE_PR = "CreatePR";
>   String GITOPS_MERGE_PR = "MergePR";
>   String GITOPS_UPDATE_RELEASE_REPO = "UpdateReleaseRepo";
> ```

Is this the step type that shows up in UI? If yes, then add GitOps prefix to it

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 12 of 24 files at r1, 17 of 17 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java` line 193 at r4](https://reviewable.io/reviews/harness/harness-core/38092#-NDAlnBUABL-RLMBDHug:-NDAlnBUABL-RLMBDHuh:b2ylfbe) ([raw file](https://github.com/harness/harness-core/blob/72e156bf248c06fbd32cbc661b531b25bfc31681/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java#L193)):*
> ```Java
>       List<GitopsClustersOutcome.ClusterData> clustersData = output.getClustersData();
> 
>       String file = Strings.EMPTY;
> ```

This should be set to `filePath` instead of empty. As Anshul mentioned a recent change was merged.

**Review by anshul-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 19 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepInfo.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/38092#-NDE0xVQ5mPSn3bhwKCF:-NDE0xVQ5mPSn3bhwKCG:b-3jj8mk) ([raw file](https://github.com/harness/harness-core/blob/cf383f98892d8fe4dd913cf76ea1e52deffd9676/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepInfo.java#L55)):*
> ```Java
>   @Builder(builderMethodName = "infoBuilder")
>   public UpdateReleaseRepoStepInfo(ParameterField<List<TaskSelectorYaml>> delegateSelectors,
>       ParameterField<Map<String, String>> stringMap, List<NGVariable> environmentVariables) {
> ```

Change the name from environmentVariables --> variables
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepParams.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/38092#-NDE1AJc6BvNk9AfzsUA:-NDE1AJc6BvNk9AfzsUB:b-3jj8mk) ([raw file](https://github.com/harness/harness-core/blob/cf383f98892d8fe4dd913cf76ea1e52deffd9676/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepParams.java#L23)):*
> ```Java
>   @Builder(builderMethodName = "infoBuilder")
>   public UpdateReleaseRepoStepParams(ParameterField<List<TaskSelectorYaml>> delegateSelectors,
>       ParameterField<Map<String, String>> stringMap, Map<String, Object> environmentVariables) {
> ```

Change the name from environmentVariables --> variables

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 19 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java` line 223 at r6](https://reviewable.io/reviews/harness/harness-core/38092#-NDFoXoS5kBB5y88BN1W:-NDFoXoS5kBB5y88BN1X:b-1jv4ow) ([raw file](https://github.com/harness/harness-core/blob/27a9d0c06c44eaf75c1ed7683db5b138a5f3f71a/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java#L223)):*
> ```Java
>           if (value.contains("<+env.name>")) {
>             value = value.replaceAll("<\\+env.name>", cluster.getEnvName());
>           }
> ```

We need to add a check to render the final value as it may still contain some expressions

**Review by rohitk-h — APPROVED** [review]
> Reviewed 12 of 19 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 2 of 4 files at r8, 13 of 13 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 408 at r10](https://reviewable.io/reviews/harness/harness-core/38092#-NDYwZFO5AeVGAwy4MYf:-NDYwZFO5AeVGAwy4MYg:bv9kt3c) ([raw file](https://github.com/harness/harness-core/blob/46d8aaf7ea690761454a4e0c5c574b01c8aef527/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L408)):*
> ```Java
>             .setName("GitOps Create PR")
>             .setType(StepSpecTypeConstants.GITOPS_CREATE_PR)
>             .setFeatureFlag(FeatureName.NG_GITOPS_SHOW_CREATE_PR.name())
> ```

Should we rename this to update release repo step instead? 
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 450 at r10](https://reviewable.io/reviews/harness/harness-core/38092#-NDYx8Ec1jkg3pyLvIYu:-NDYx8Ec1jkg3pyLvIYv:b-k5gqz9) ([raw file](https://github.com/harness/harness-core/blob/46d8aaf7ea690761454a4e0c5c574b01c8aef527/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L450)):*
> ```Java
>       HarnessTeam.CDP),
>   SERVICE_ENV_RECONCILIATION("Do reconciliation of service and env on pipeline/template save", HarnessTeam.CDC),
>   NG_GITOPS_SHOW_CREATE_PR("Start showing CreatePR step on the plan creator if enabled", HarnessTeam.GITOPS);
> ```

Isn't this update release repo?

**Comment by lasdox** [comment]
> > Reviewed 1 of 1 files at r7, 2 of 4 files at r8, 13 of 13 files at r9, 4 of 4 files at r10, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)_ status: :shipit: complete! ✓
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 408 at r10](https://reviewable.io/reviews/harness/harness-core/38092#-NDYwZFO5AeVGAwy4MYf:-NDYwZFO5AeVGAwy4MYg:bv9kt3c) ([raw file](https://github.com/harness/harness-core/blob/46d8aaf7ea690761454a4e0c5c574b01c8aef527/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L408)):_
> 
> > ```java
> >             .setName("GitOps Create PR")
> >             .setType(StepSpecTypeConstants.GITOPS_CREATE_PR)
> >             .setFeatureFlag(FeatureName.NG_GITOPS_SHOW_CREATE_PR.name())
> > ```
> 
> Should we rename this to update release repo step instead?
> 
> _[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 450 at r10](https://reviewable.io/reviews/harness/harness-core/38092#-NDYx8Ec1jkg3pyLvIYu:-NDYx8Ec1jkg3pyLvIYv:b-k5gqz9) ([raw file](https://github.com/harness/harness-core/blob/46d8aaf7ea690761454a4e0c5c574b01c8aef527/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L450)):_
> 
> > ```java
> >       HarnessTeam.CDP),
> >   SERVICE_ENV_RECONCILIATION("Do reconciliation of service and env on pipeline/template save", HarnessTeam.CDC),
> >   NG_GITOPS_SHOW_CREATE_PR("Start showing CreatePR step on the plan creator if enabled", HarnessTeam.GITOPS);
> > ```
> 
> Isn't this update release repo?

Hey Rohit, we are hiding the current CreatePRStep behind another feature flag and substituting the default to be the new UpdateReleaseRepo

**Review by anshul-harness — COMMENTED** [review]
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by rohitk-h** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 450 at r10](https://reviewable.io/reviews/harness/harness-core/38092#-NDYx8Ec1jkg3pyLvIYu:-NDZY7tc0pE0KOkfezt9:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/46d8aaf7ea690761454a4e0c5c574b01c8aef527/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L450)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

Hey Rohit, we are hiding the current CreatePRStep behind another feature flag and substituting the default to be the new UpdateReleaseRepo
</blockquote></details>

ok

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

**Comment by lasdox** [comment]
trigger messagecheck

**Review by anshul-harness — COMMENTED** [review]
> Reviewed 3 of 4 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by anshul-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 4 files at r12, 1 of 2 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger codebasehash

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38092)* status: :shipit: complete! ✓

**Comment by anshul-harness** [comment]
trigger codebasehash

**Comment by anshul-harness** [comment]
trigger codebasehash

**Pull request merged**
