### PR TITLE
[fix]: [CDS-69595]: added terraform steps to google function and aws lambda and cloud formation steps to aws lambda

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
1. Added Cloud Formation Steps to be visible inside step library for AWS Lambda Swimlane.
2. Added Terraform Steps to be visible inside step library for AWS Lambda and Google Functions Swimlane.
3. Added Terragrunt steps to be visible inside step library for AWS Lambda and Google Functions Swimlane.
4. Added Shell Script Provisioner steps to be visible inside step library for AWS Lambda and Google Functions Swimlane.

Screenshot 2023-05-17 at 7 17 52 PM

Screenshot 2023-05-17 at 7 18 23 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47973)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
> > > Reviewed all commit messages.
> > > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/47973)_ status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> > 
> > 
> > _[a discussion](https://reviewable.io/reviews/harness/harness-core/47973#-NVdgM6bAo_NGigjNfmJ:-NVdgM6bAo_NGigjNfmK:bmbywko) (no related file):_ can we check if this is missing from any other place ?
> 
> yes, I see that terraform steps are missing for some other swimlanes like PCF, Ssh/Winrm.
> 
> I also see that terragrunt and Shell script provisioner steps are also missing in a lot of swimlanes. I will convey it to PMs @shylajas and @thisrohangupta to decide which swimlanes we need to enable these steps.

@yogesh-chauhan I enabled shell script provisioner step and terragrunt steps also for these swimlanes

**Review by rohitk-h — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47973)* status: 1 file(s) to review. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/47973#-NVdgM6bAo_NGigjNfmJ:-NVequTYCJwqrogmPGiW:b-9uqvvc) (no related file):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

@yogesh-chauhan I enabled shell script provisioner step and terragrunt steps also for these swimlanes
</blockquote></details>

Thanks @PragyeshMishra01 

___

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
