### PR TITLE
techdebt: [PIE-5428]: Remove FF PIPELINE_MONITORING 

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37742)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37742)

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/37742#-NCU11u353N4Y4KwmCi1:-NCU11u42RcsW_HeMe8M:botw6qj) ([raw file](https://github.com/harness/harness-core/blob/0cd0534af4290625a399538fb93dbaefdc55c6a9/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java#L92)):*
> ```Java
> 
>     if (isMonitored
>         && pmsFeatureFlagService.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.PIPELINE_MONITORING)) {
> ```

I think we will need isMonitored check.

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/37742#-NCU11u353N4Y4KwmCi1:-NCU2XuY5BVKjxYlG-O9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0cd0534af4290625a399538fb93dbaefdc55c6a9/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java#L92)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think we will need isMonitored check.
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37742)* status: Some of the checks are too old. 10 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37742)* status: Some of the checks are too old.

**Pull request merged**
