### PR TITLE
feat: [SRM-13569]: Log feedback changes.

### PR DESCRIPTION
**Pull request by naveen-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43551)

### CODE REVIEW

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43551)* status: 17 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/contracts/commons/src/main/java/io/harness/cvng/analysis/beans/Risk.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/43551#-NNeJA-jB5ic_mD86XvX:-NNeJA-jB5ic_mD86XvY:bwevjpe) ([raw file](https://github.com/harness/harness-core/blob/f67436795ac65b6281bcddc7f4681bdb1f44cf6d/srm-service/modules/cv-nextgen-service/contracts/commons/src/main/java/io/harness/cvng/analysis/beans/Risk.java#L23)):*
> ```Java
>   NEED_ATTENTION(2, "Need Attention"),
>   UNHEALTHY(3, "Unhealthy"),
>   MEDIUM_HEALTHY(4, "Medium Healthy");
> ```

In some places we compare Risk by risk values. For example (Risk > 2), this will change the order, as MEDIUM_HEALTHY is coming after UNHEALTHY. Please verify such logics are no longer there, and where ever we are using MEDIUM_HEALTHY even for LE communication, use ENUM instead of this number
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/LogFeedbackHistory.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/43551#-NNeKXHoCRmzhYk6Q3Os:-NNeKXHoCRmzhYk6Q3Ot:b-e81fvi) ([raw file](https://github.com/harness/harness-core/blob/f67436795ac65b6281bcddc7f4681bdb1f44cf6d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/LogFeedbackHistory.java#L18)):*
> ```Java
> public class LogFeedbackHistory {
>   LogFeedback logFeedback;
>   @JsonProperty("createdBy") String createdBy;
> ```

nit: Why we need @JsonProperty here?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/LogFeedbackResource.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/43551#-NNeKqqi0kiJGXR_vHr1:-NNeKqqi0kiJGXR_vHr2:b-d4r80i) ([raw file](https://github.com/harness/harness-core/blob/f67436795ac65b6281bcddc7f4681bdb1f44cf6d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/LogFeedbackResource.java#L111)):*
> ```Java
>   @ApiOperation(value = "saves log data collected for verification", nickname = "deleteLogFeedback")
>   public RestResponse<Boolean> deleteLogFeedback(
>       @PathParam(CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY) @NonNull String accountIdentifier,
> ```

use @BeanParam ProjectPathParams for getting account, org, project
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/LogFeedbackServiceImpl.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/43551#-NNeLdu56z7bhiag6L8H:-NNeLdu56z7bhiag6L8I:bi2smvt) ([raw file](https://github.com/harness/harness-core/blob/f67436795ac65b6281bcddc7f4681bdb1f44cf6d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/LogFeedbackServiceImpl.java#L61)):*
> ```Java
>   }
> 
>   private void updateDeploymentLogAnalysis(ProjectParams projectParams, LogFeedback logFeedback) {
> ```

nit: keep the private functions after all public functions

**Review by naveen-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43551)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/contracts/commons/src/main/java/io/harness/cvng/analysis/beans/Risk.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/43551#-NNeJA-jB5ic_mD86XvX:-NNk-zbB4EmpE6Yrr1KX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f67436795ac65b6281bcddc7f4681bdb1f44cf6d/srm-service/modules/cv-nextgen-service/contracts/commons/src/main/java/io/harness/cvng/analysis/beans/Risk.java#L23)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

In some places we compare Risk by risk values. For example (Risk > 2), this will change the order, as MEDIUM_HEALTHY is coming after UNHEALTHY. Please verify such logics are no longer there, and where ever we are using MEDIUM_HEALTHY even for LE communication, use ENUM instead of this number
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/LogFeedbackResource.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/43551#-NNeKqqi0kiJGXR_vHr1:-NNk00EJDOGN9oAUy-v7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f67436795ac65b6281bcddc7f4681bdb1f44cf6d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/LogFeedbackResource.java#L111)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

use @BeanParam ProjectPathParams for getting account, org, project
</blockquote></details>

Done.

**Comment by naveen-harness** [comment]
trigger messagecheck

**Comment by naveen-harness** [comment]
trigger messagecheck

**Review by AbhijithHarness — DISMISSED** [review]
> Reviewed 7 of 17 files at r1, 9 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43551)* status: Some of the checks are too old.

**Pull request closed without merging**
