### PR TITLE
[feat]: [CDS-70183]: Recreate Plan for Post Prod Rollback

### PR DESCRIPTION
**Pull request by namanvermah**
Recreate plan for post prod rollback as we can’t reuse old plan right now until we handle the skip tree field for steps under strategy
In order to handle it, we will need to have an executionMode->skipGraphType map and handle it during graph generation

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48285)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger buildnum

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48285)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48285)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48285)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48285)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
