### PR TITLE
[feat]: [CCM-7537]: GCP Connector Validation [ Inventory/Auto-Stopping ]

### PR DESCRIPTION
**Pull request by abhijeet-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33113)

### CODE REVIEW

**Comment by abhijeet-harness** [comment]
trigger messagecheck

**Comment by abhijeet-harness** [comment]
> lets keep this list sorted and pretty formatted here for easier lookup.

Sorted both permissions list. However, code_format check is failing due to prettified lists. Should we clang-format it and revert permissions list to previous form?

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33113)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/33113#-N2uTTam4KybYX9nYELy:-N2uTTam4KybYX9nYELz:b-v90qzj) ([raw file](https://github.com/harness/harness-core/blob/03bb80e67339f7faba2eb2ac14746d7a70dc0a9c/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java#L93)):*
> ```Java
>     }
>     CloudResourceManager service = null;
>     try {
> ```

Add config variable here with default value false
___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/33113#-N2uTbPWCRi1L2bj_NH_:-N2uTbPWCRi1L2bj_NHa:b-fbswxl) ([raw file](https://github.com/harness/harness-core/blob/03bb80e67339f7faba2eb2ac14746d7a70dc0a9c/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java#L102)):*
> ```Java
>                         .code(500)
>                         .build());
>       return ConnectorValidationResult.builder()
> ```

The error message here should be generic. Refer to AWS/Azure ones
___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/33113#-N2uTXdS4z6EZFx7P0u9:-N2uTXdS4z6EZFx7P0uA:bugnnbu) ([raw file](https://github.com/harness/harness-core/blob/03bb80e67339f7faba2eb2ac14746d7a70dc0a9c/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java#L109)):*
> ```Java
>     }
>     try {
>       if (featuresEnabled.contains(CEFeatures.VISIBILITY)) {
> ```

all permission related messages - lets send in one go. 
___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/33113#-N2uTqrD2oawRbvuY3Il:-N2uTqrD2oawRbvuY3Im:b-5nc8ub) ([raw file](https://github.com/harness/harness-core/blob/03bb80e67339f7faba2eb2ac14746d7a70dc0a9c/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java#L204)):*
> ```Java
>       errorList.add(ErrorDetail.builder()
>                         .reason("Some required permissions were found to be missing")
>                         .message("Please check if service account " + impersonatedServiceAccount
> ```

pretty format missingpermissions in the final message.
___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/33113#-N2uU8Og7aT8HfLUA1dm:-N2uU8Og7aT8HfLUA1dn:bnxakiu) ([raw file](https://github.com/harness/harness-core/blob/03bb80e67339f7faba2eb2ac14746d7a70dc0a9c/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEGcpConnectorValidator.java#L217)):*
> ```Java
>       log.error("Unable to test permissions", e);
>       errorList.add(ErrorDetail.builder()
>                         .reason("Unable to test required permissions")
> ```

Refer to AWS/Azure permisison messages

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33113)* status: :shipit: complete! ✓

**Pull request merged**
