### PR TITLE
feat: [SRM-10015]: Added fixed duration graph data support for SLO Details page.

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java, line 186 at r1](https://reviewable.io/reviews/harness/harness-core/32202#-N-WsR2M2ZVoLTesSbOh:-N-WsR2N03Ge0FV-aiVT:bxc9567) ([raw file](https://github.com/harness/harness-core/blob/4ed190c58a20583cc28596d22034c2e11af7b6a4/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L186)):*
> ```Java
>       errorBudgetRemaining = totalErrorBudgetMinutes - sliValue.getBadCount();
>     }
>     return SLOGraphData.builder()
> ```

I think you will need to remove the start and end time points if the start and end time is different than the given start and end time.
Also, add more test case around this scenario 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/32202#-N-WqV1r3dz5GU43gXDO:-N-WqV1r3dz5GU43gXDP:b-nyg6n0) ([raw file](https://github.com/harness/harness-core/blob/4ed190c58a20583cc28596d22034c2e11af7b6a4/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L83)):*
> ```Java
>     endTime = customTime.get(1);
>     ServiceLevelObjectiveResponse sloResponse = serviceLevelObjectiveService.get(projectParams, identifier);
>     SLODashboardWidget sloDashboardWidget = getSloDashboardWidget(projectParams, sloResponse, startTime, endTime);
> ```

Add a validation that start and end time should be 1 hour apart and should be in 'current' SLO time range.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java, line 108 at r1](https://reviewable.io/reviews/harness/harness-core/32202#-N-Wre1RCQQ4CdZsmFYM:-N-Wre1RCQQ4CdZsmFYN:b-vo0yex) ([raw file](https://github.com/harness/harness-core/blob/4ed190c58a20583cc28596d22034c2e11af7b6a4/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L108)):*
> ```Java
>           startTime = DateTimeUtils.roundDownToOneMonthBoundary(clock.instant());
>           break;
>         default:
> ```

What if this is a custom time range? we should take the start and end time and round them to nearest minute.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java, line 117 at r1](https://reviewable.io/reviews/harness/harness-core/32202#-N-WrlCZEh9FlmI96f70:-N-WrlCZEh9FlmI96f71:br0bjgd) ([raw file](https://github.com/harness/harness-core/blob/4ed190c58a20583cc28596d22034c2e11af7b6a4/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L117)):*
> ```Java
>       }
>     }
>     List<Instant> customTimeList = new ArrayList<>();
> ```

Rather than List<Instant> you can use the Pair<Instant, Instant> since there will always be two points.

**Comment by arpit-harness** [comment]
trigger ti0

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java, line 39 at r3](https://reviewable.io/reviews/harness/harness-core/32202#-N-xNT2B8ktvuNXaQ3P6:-N-xNT2B8ktvuNXaQ3P7:bi03rt0) ([raw file](https://github.com/harness/harness-core/blob/918a2f7981e2ccf78c23f063bd6c50137fb49059/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java#L39)):*
> ```Java
>   }
> 
>   public static Pair<Instant, Instant> getCustomTimeRange(Instant startTime, Instant endTime, DurationDTO durationDTO) {
> ```

I am not sure why do we need this? Can we sync to understand more? I want to understand this little better.

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 6 of 10 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: :shipit: complete! ✓

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardDetail.java, line 21 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04hyLl1lyINbh3n2Fh:-N04hyLl1lyINbh3n2Fi:b-xzffyo) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardDetail.java#L21)):*
> ```Java
>   Long createdAt;
>   Long lastModifiedAt;
>   List<TimeRangeFilter> timeRangeFilterList;
> ```

timeRangeFilters
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardDetail.java, line 27 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04hsMhE0FrYSxRxPRP:-N04hsMhE0FrYSxRxPRQ:b-do39r2) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardDetail.java#L27)):*
> ```Java
>   public static class TimeRangeFilter {
>     String displayName;
>     long durationMilliSecond;
> ```

durationMillis or durationMilliSeconds
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java, line 126 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04i2yl3culTKwmYnwc:-N04i2yl3culTKwmYnwd:b-8kefke) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L126)):*
> ```Java
>   }
> 
>   public List<TimeRangeFilter> getTimeRangeFilterList() {
> ```

In my opinion getTimeRangeFilters is more readable. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java, line 177 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04iKgtA_TtbRQnG0B7:-N04iKgtA_TtbRQnG0B8:b-5h08c7) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L177)):*
> ```Java
>     public abstract TimePeriod getCurrentTimeRange(LocalDateTime currentDateTime);
>     public abstract SLOTargetType getType();
>     public abstract List<TimeRangeFilter> getTimeRangeFilterList();
> ```

same here.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java, line 229 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04iVSY87ZnmYmAYFL7:-N04iVSY87ZnmYmAYFL8:byxdx12) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L229)):*
> ```Java
>           TimeRangeFilter.builder().displayName("1 Hour").durationMilliSecond(Duration.ofHours(1).toMillis()).build());
>       timeRangeFilterList.add(
>           TimeRangeFilter.builder().displayName("1 Day").durationMilliSecond(Duration.ofDays(1).toMillis()).build());
> ```

can you create these time range filters as static values in TimeRangeFilter class and use them directly here?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java, line 277 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04ihzT8X58sFo2HubK:-N04ihzT8X58sFo2HubL:bkw0ehk) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L277)):*
> ```Java
>           TimeRangeFilter.builder().displayName("1 Week").durationMilliSecond(Duration.ofDays(7).toMillis()).build());
>       timeRangeFilterList.add(
>           TimeRangeFilter.builder()
> ```

let's keep it to fixed length of 31 days as we are already handling the range outside of the range. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java, line 298 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04jGUE0Eg3QxF5xCjU:-N04jGUE0Eg3QxF5xCjV:bigfrlg) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L298)):*
> ```Java
> 
>     @Override
>     public List<TimeRangeFilter> getTimeRangeFilterList() {
> ```

we should also write few tests for this method?

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java, line 13 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04k0wF3A6nhV2lEgJg:-N04k0wF3A6nhV2lEgJh:bhzybke) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/DurationDTO.java#L13)):*
> ```Java
> 
> public enum DurationDTO {
>   ONE_HOUR(Duration.ofHours(1)),
> ```

please revert changes that are not needed anymore.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/DateTimeUtils.java, line 37 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04k5va0Xi-9hX7hQpT:-N04k5va0Xi-9hX7hQpU:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/DateTimeUtils.java#L37)):*
> ```Java
>   }
> 
>   public static Instant roundDownToHourBoundary(Instant instant, int hourBoundary) {
> ```

same here
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordService.java, line 23 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04kOT78f5Tq7r0Hn-V:-N04kOT78f5Tq7r0Hn-W:b-ypxzin) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordService.java#L23)):*
> ```Java
>       SLIMissingDataType sliMissingDataType, int sliVersion);
>   SLOGraphData getGraphData(String sliId, Instant startTime, Instant endTime, int totalErrorBudgetMinutes,
>       SLIMissingDataType sliMissingDataType, int sliVersion, Instant customStartTime, Instant customEndTime);
> ```

this api is confusing because of customStartTime and customEndTime. We should probably use io.harness.cvng.core.beans.params.TimeRangeParams with filter as a variable name.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java, line 188 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04lLUO5AdLSlp4iR13:-N04lLUO5AdLSlp4iR14:bh3w1f5) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L188)):*
> ```Java
>     }
> 
>     if (sliTread.size() > 0
> ```

this logic is not correct. sli needs to be calculated from the start of the sli period. We can not calculate it based on

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java, line 143 at r5](https://reviewable.io/reviews/harness/harness-core/32202#-N04peVYD8HNAMxW5tqR:-N04peVYD8HNAMxW5tqS:b-ll8e4r) ([raw file](https://github.com/harness/harness-core/blob/90337648522a25b74e4d9b432c1b529c96ff970b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L143)):*
> ```Java
>   public SLOGraphData getGraphData(String sliId, Instant startTime, Instant endTime, int totalErrorBudgetMinutes,
>       SLIMissingDataType sliMissingDataType, int sliVersion, Instant customStartTime, Instant customEndTime) {
>     Preconditions.checkState(totalErrorBudgetMinutes != 0, "Total error budget minutes should not be zero.");
> ```

add preconditions for range outside of the SLO range.



_Code quote:_
```Java
    if (sliTread.size() > 0 && Instant.ofEpochMilli(sliTread.get(0).getTimestamp()).isBefore(customStartTime)) {
      sliTread.remove(0);
      errorBudgetBurndown.remove(0);
    }
```

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardDetail.java, line 27 at r6](https://reviewable.io/reviews/harness/harness-core/32202#-N095IS95pvGDyNzJdgx:-N095IS95pvGDyNzJdgy:b-g5a05z) ([raw file](https://github.com/harness/harness-core/blob/b27cc382c295cb5021e9d645a96409c43ae2ba96/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardDetail.java#L27)):*
> ```Java
>   @Builder
>   public static class TimeRangeFilter {
>     public static final TimeRangeFilter oneHourFilter =
> ```

please use UPPER_CASE for static variables.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordService.java, line 24 at r6](https://reviewable.io/reviews/harness/harness-core/32202#-N095Z-44LWFGfXbr3ai:-N095Z-44LWFGfXbr3aj:b-id0hqu) ([raw file](https://github.com/harness/harness-core/blob/b27cc382c295cb5021e9d645a96409c43ae2ba96/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordService.java#L24)):*
> ```Java
>       SLIMissingDataType sliMissingDataType, int sliVersion);
>   SLOGraphData getGraphData(String sliId, Instant startTime, Instant endTime, int totalErrorBudgetMinutes,
>       SLIMissingDataType sliMissingDataType, int sliVersion, TimeRangeParams timeRangeParams);
> ```

please rename the variable to filter to communicate the intent

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32202#-:-N09FQ877nAVNGSOgUMY:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
