### PR TITLE
feat: [PL-40511]: Revert Fix projects-count API to resolve timeout issue

### PR DESCRIPTION
**Pull request by sahibaHarness**
Reverts harness/harness-core#55708

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55851)

### CODE REVIEW

**Comment by sahibaHarness** [comment]
trigger uts

**Comment by sahibaHarness** [comment]
trigger ut7

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Comment by sahibaHarness** [comment]
trigger gitleaks

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Comment by sahibaHarness** [comment]
trigger messagecheck

**Review by nishantsaini20 — APPROVED** [review]

**Pull request merged**
