### PR TITLE
[feat]: [PL-23468]: Adds x-api-key telemetry filter in RBAC service

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31464)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger ti0

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by ashishsanodia-harness** [comment]
trigger ti2

**Comment by ashishsanodia-harness** [comment]
trigger ti3

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger ti4

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger ti0

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31464)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
