### PR TITLE
fix: [DEL-5704]: Remove expression map from task data

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Remove Expression Map from Task data as it's not used and causing kryo issue while serializing task data while queuing task
- Fix the issue of filtering delegated by stage 

Test Performed
- local testing for queue NG delegate task 
- PR Testing for sanity, NG deployment with latest and older version of the delegate. And CG K8 end to end deployment

## Checklist
- [ X] I've documented the changes in the PR description.
- [X ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42352)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
Sanity Test
NG pipeline with shell script task 
image

CG K8 deployment
image

**Comment by jennyjames21** [comment]
Older version delegate - NG pipeline
image

**Comment by raghuAtWings** [comment]
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateResourceCriteriaCheckForTaskTest.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJgIqD6g5b9Ypg074V:-NLJgIqE-vlNVZ5DBj4R:ba003l8) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/400-rest/src/test/java/software/wings/service/delegate/DelegateResourceCriteriaCheckForTaskTest.java#L122)):*
> ```Java
>     List<Delegate> delegateList = orderByTotalNumberOfTaskAssignedCriteria.getFilteredEligibleDelegateList(
>         eligibleDelegateIds, TaskType.INITIALIZATION_PHASE, accountId);
>     assertThat(delegateList.size()).isEqualTo(3);
> ```

i don't see any assert for the delegate which should be the one at top

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJtJuQ4n7H7EZ3m-6G:-NLJtJuREGRZxDVshy-A:b-xsgum) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L60)):*
> ```Java
>     delegateList.forEach(delegate -> {
>       List<DelegateTask> delegateTaskList =
>           getTotalNumberOfTaskAssignedInDelegate(accountId, taskType, delegate.getUuid());
> ```

Does this make db call? Will it create a lot of db queries?

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJtJuQ4n7H7EZ3m-6G:-NLJvSVXCh3UNpMLc-E9:bt2jdr2) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L60)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

Does this make db call? Will it create a lot of db queries? 
</blockquote></details>

this is temporary until we have Redis implementation to fetch from.  For the docker runner, it's generally one eligible delegate.

**Comment by jennyjames21** [comment]
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateResourceCriteriaCheckForTaskTest.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJgIqD6g5b9Ypg074V:-NLJw-u3Cc98viI9nC8m:bcjlgwl) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/400-rest/src/test/java/software/wings/service/delegate/DelegateResourceCriteriaCheckForTaskTest.java#L122)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i don't see any assert for the delegate which should be the one at top
</blockquote></details>

There are 3 eligible delegates and  none of the delegates running any task so the order is not predictable when they sort- TreeMap (number of tasks currently assigned is 0 for all three) 

I will change to one eligible delegate

**Comment by jennyjames21** [comment]
NG Pipeline Sanity test with older NG build
image

**Comment by jennyjames21** [comment]
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateResourceCriteriaCheckForTaskTest.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJgIqD6g5b9Ypg074V:-NLK87ru-AGZvEJmQEf0:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/400-rest/src/test/java/software/wings/service/delegate/DelegateResourceCriteriaCheckForTaskTest.java#L122)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

There are 3 eligible delegates and  none of the delegates running any task so the order is not predictable when they sort- TreeMap (number of tasks currently assigned is 0 for all three) 

I will change to one eligible delegate 
</blockquote></details>

updated

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42352)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJtJuQ4n7H7EZ3m-6G:-NLKGqHCD6fiR5xfg_TL:beozx2e) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L60)):*
> esting for sanity, NG deployment with latest and older version of the delegate. And CG K8 end to end deployment
this compute is directly proportional to number of delegate and number of task being executed for give account. Do you want to disable it, till we enable redis ?

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/42352#-NLJtJuQ4n7H7EZ3m-6G:-NLKJLZEAWMhxLwbXaaw:b-9erjk9) ([raw file](https://github.com/harness/harness-core/blob/9ab52c9d6226589379e0b808b25c8d246e6da776/420-delegate-service/src/main/java/io/harness/queueservice/impl/OrderByTotalNumberOfTaskAssignedCriteria.java#L60)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> esting for sanity, NG deployment with latest and older version of the delegate. And CG K8 end to end deployment
this compute is directly proportional to number of delegate and number of task being executed for give account. Do you want to disable it, till we enable redis ?
</blockquote></details>

Yes it's already under FF(QUEUE_CI_EXECUTIONS,) where queueing is enabled.

**Pull request merged**
