### PR TITLE
[feat]: [PL-39599]: Adds explicit resource-permission mapping to support some exception cases for acl

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds explicit resource-permission mapping to support some exception cases for acl

Added below explicit mapping for resource-permissions
```
resourcePermissionMapping:
  - resourceIdentifier: CCM_FOLDER
    permissions:
    - ccm_perspective_view
    - ccm_perspective_edit
    - ccm_perspective_delete
    - ccm_budget_view
    - ccm_budget_edit
    - ccm_budget_delete
  - resourceIdentifier: CCM_PERSPECTIVE
    permissions:
    - ccm_overview_view
  - resourceIdentifier: ENVIRONMENT
    permissions:
    - ff_featureflag_edit
    - ff_featureflag_delete
    - ff_featureflag_toggle
    - ff_targetgroup_edit
    - ff_targetgroup_delete
    - sto_ticket_view
  - resourceIdentifier: GOVERNANCEPOLICY
    permissions:
    - core_governancePolicySets_edit
  - resourceIdentifier: CONNECTOR
    permissions:
    - ccm_cloudAssetGovernanceRule_execute
```

Test:
- Verified ACL generation for role bindings with custom role-resource groups
- Verified redundant ACLs getting disabled
- Verified ACLs are being enabled if there is explicit mapping present
- Verified ACL check API call returning correct response for valid acl combination including resource-permission mentioned in explicit mapping

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50410)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut9

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50410)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_87F2Q4RL1B1bmVbPx:-N_87F2Q4RL1B1bmVbPy:b-okd7s3) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L207)):*
> ```Java
>   public List<PermissionCheckResult> checkAccess(Principal principal, List<PermissionCheck> permissionChecks,
>       ResourceAttributeProvider resourceAttributeProvider) {
>     permissionChecks.stream()
> ```

This change is not clear
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissions.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83GCy0p4C7aZlgB0h:-N_83GCy0p4C7aZlgB0i:b-8y3ysc) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissions.java#L20)):*
> ```Java
> @Value
> @Builder
> public class ResourcePermissions {
> ```

Lets have these classes inside InMemoryPermissionRepository itself as they are implementation details.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissionsMapping.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_839Xz1i2CZVwszgbk:-N_839Xz1i2CZVwszgbl:b-8y3ysc) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissionsMapping.java#L20)):*
> ```Java
> @Value
> @Builder
> public class ResourcePermissionsMapping {
> ```

Lets have these classes inside InMemoryPermissionRepository itself as they are implementation details.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83YQr3KBP03_yietJ:-N_83YQr3KBP03_yietK:b-ootpos) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L49)):*
> ```Java
>   private Map<String, List<String>> explicitPermissionToResourceTypeMapping;
>   private Map<String, List<String>> permissionToResourceTypeMapping;
>   private ResourcePermissionsMapping resourcePermissionsMapping;
> ```

Why this should a field in the class and not a local variable?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83wXY5UVgx2B1c8jd:-N_83wXY5UVgx2B1c8je:bdtyurw) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L54)):*
> ```Java
>   public InMemoryPermissionRepository(@Named("mongoTemplate") MongoTemplate mongoTemplate) {
>     this.mongoTemplate = mongoTemplate;
>     this.implicitPermissionToResourceTypeMapping = new HashMap<>();
> ```

We should load implicitPermissionToResourceTypeMapping here like how we are doing for explicit for consistency

Also, we should populate resourcePermissionsMapping here itself instead of inside  List<String> getResourceTypesBy(String permission) method
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83szj6QEJiJD4WVO3:-N_83szj6QEJiJD4WVO4:b8cstj2) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L111)):*
> ```Java
>   }
> 
>   public List<String> getResourceTypesBy(String permission) {
> ```

Return type should be Set<String>

Method name we can change to getResoureTypesApplicationToPermission()
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceSelector.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_86IQR4OdShpMFGzwy:-N_86IQR4OdShpMFGzwz:bq5gxzi) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceSelector.java#L37)):*
> ```Java
>   String condition;
> 
>   public static boolean validateResourceType(List<String> resourceTypes, String resourceSelector) {
> ```

We should expose a method like boolean isPermissionCompatibleWithResourceSelector(Permission, Resource Selector) inside InMemoryPermissionRepository itself
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resource-permissions.yml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_815aE0Lhyluyhk71q:-N_815aE0Lhyluyhk71r:b-kxgyqf) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resource-permissions.yml#L1)):*
> ```YAML
> resourcePermissionMapping:
> ```

resourceToPermissionsExceptionMapping

Similarly file should be resource-permissions-exception-mapping.yml

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_87F2Q4RL1B1bmVbPx:-N_8MYeoDl272aVOoZHW:b-ho6etx) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/ACLServiceImpl.java#L207)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This change is not clear
</blockquote></details>

This is to log redundant ACL check requests. Now I am filtering requests coming with SCOPE as resource.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83YQr3KBP03_yietJ:-N_8yt194Y-dklUnTnEL:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this should a field in the class and not a local variable?
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83wXY5UVgx2B1c8jd:-N_8zJ9y4klHpLPdHcNe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L54)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should load implicitPermissionToResourceTypeMapping here like how we are doing for explicit for consistency

Also, we should populate resourcePermissionsMapping here itself instead of inside  List<String> getResourceTypesBy(String permission) method
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83szj6QEJiJD4WVO3:-N_8zPdpCh2Fr9KTv61l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/persistence/repositories/InMemoryPermissionRepository.java#L111)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Return type should be Set<String>

Method name we can change to getResoureTypesApplicationToPermission()
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceSelector.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_86IQR4OdShpMFGzwy:-N_8zSPe9-WagdePJoi7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceSelector.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should expose a method like boolean isPermissionCompatibleWithResourceSelector(Permission, Resource Selector) inside InMemoryPermissionRepository itself
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resource-permissions.yml` line 1 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_815aE0Lhyluyhk71q:-N_8zVdyD3YyLW86Uu0q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resource-permissions.yml#L1)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

resourceToPermissionsExceptionMapping

Similarly file should be resource-permissions-exception-mapping.yml
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissions.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_83GCy0p4C7aZlgB0h:-N_8z_FE6PsBUkGgGYjg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissions.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets have these classes inside InMemoryPermissionRepository itself as they are implementation details.
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissionsMapping.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/50410#-N_839Xz1i2CZVwszgbk:-N_8zajq07HktPN52gMq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96a15a32ef9934457554abac075c9bd7821f1a7b/access-control/libs/core/src/main/java/io/harness/accesscontrol/permissions/ResourcePermissionsMapping.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets have these classes inside InMemoryPermissionRepository itself as they are implementation details.
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut5

**Review by ankit-harness — APPROVED** [review]
> Reviewed 12 of 12 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50410)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50410)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/test/java/io/harness/accesscontrol/persistence/InMemoryPermissionRepositoryTest.java` line 165 at r5](https://reviewable.io/reviews/harness/harness-core/50410#-N_E8s1p374cogF1fRcf:-N_E8s1p374cogF1fRcg:bgpotbw) ([raw file](https://github.com/harness/harness-core/blob/562e137dbab07b592051f47faa83c6753e30e153/access-control/libs/core/src/test/java/io/harness/accesscontrol/persistence/InMemoryPermissionRepositoryTest.java#L165)):*
> ```Java
>         .isTrue();
>     assertThat(inMemoryPermissionRepository.isPermissionCompatibleWithResourceSelector(
>                    ENVIRONMENT_GROUP_RESOURCE_NAME, "/ACCOUNT/account-id$/RESOURCEGROUP/user-group-id-2"))
> ```

I think in case of UTs as well it is referring to exception list defined in yaml. In that case how is this valid combination?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50410)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlApplication.java` line 201 at r5](https://reviewable.io/reviews/harness/harness-core/50410#-N_EBWGK1tknnzuU9Qe2:-N_EBWGL9yyt9DDSxtbU:b-y55rhl) ([raw file](https://github.com/harness/harness-core/blob/562e137dbab07b592051f47faa83c6753e30e153/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlApplication.java#L201)):*
> ```Java
>     injector.getInstance(HPersistence.class);
> 
>     AccessControlManagementJob accessControlManagementJob = injector.getInstance(AccessControlManagementJob.class);
> ```

Is this change because permissions need to be loaded before In Memory store is created?

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/core/src/test/java/io/harness/accesscontrol/persistence/InMemoryPermissionRepositoryTest.java` line 165 at r5](https://reviewable.io/reviews/harness/harness-core/50410#-N_E8s1p374cogF1fRcf:-N_H3QOD6iNSHcRX2RFd:b5sz05z) ([raw file](https://github.com/harness/harness-core/blob/562e137dbab07b592051f47faa83c6753e30e153/access-control/libs/core/src/test/java/io/harness/accesscontrol/persistence/InMemoryPermissionRepositoryTest.java#L165)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think in case of UTs as well it is referring to exception list defined in yaml. In that case how is this valid combination?
</blockquote></details>

No, it is not loading actual file. This data is mocked.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlApplication.java` line 201 at r5](https://reviewable.io/reviews/harness/harness-core/50410#-N_EBWGK1tknnzuU9Qe2:-N_H3xRQ0SV4ywb0RIfY:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/562e137dbab07b592051f47faa83c6753e30e153/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlApplication.java#L201)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Is this change because permissions need to be loaded before In Memory store is created?
</blockquote></details>

Yes

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 14 files at r1, 12 of 12 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50410#-:-N_Hs6usD1g5mY5q33lY:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
