### PR TITLE
[fix]: [CDS-47290]: blueprint issue

### PR DESCRIPTION
**Pull request by markoharness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40623)

### CODE REVIEW

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40623)* status: 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/40623#-NHfuenC6Ys_9Hg3283N:-NHfuenC6Ys_9Hg3283O:b-6vvi32) ([raw file](https://github.com/harness/harness-core/blob/f1a0648995b3362ed4c1379469bb4eea6826600b/960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java#L88)):*
> ```Java
>           .block(REST_CLIENT_RESPONSE_TIMEOUT);
>     } catch (AzureClientRuntimeException e) {
>       return null;
> ```

Why catch exception and return nul, potential NPE, just not having catch? 
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/40623#-NHfufTs5ezwCZFbX44q:-NHfufTs5ezwCZFbX44r:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/f1a0648995b3362ed4c1379469bb4eea6826600b/960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java#L179)):*
> ```Java
>           .block(REST_CLIENT_RESPONSE_TIMEOUT);
>     } catch (AzureClientRuntimeException e) {
>       return null;
> ```

The same as above.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java` line 280 at r1](https://reviewable.io/reviews/harness/harness-core/40623#-NHfuSm0DCdSynm_b9vb:-NHfuSm0DCdSynm_b9vc:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/f1a0648995b3362ed4c1379469bb4eea6826600b/960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java#L280)):*
> ```Java
>       return getAssignmentWithServiceResponseAsync(azureConfig, resourceScope, assignmentName).block();
>     } catch (AzureClientRuntimeException e) {
>       return null;
> ```

The same as above.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/40623#-NHfuenC6Ys_9Hg3283N:-NHfxUdO3CW4aPVaNjM0:b-q504mc) ([raw file](https://github.com/harness/harness-core/blob/f1a0648995b3362ed4c1379469bb4eea6826600b/960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java#L88)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why catch exception and return nul, potential NPE, just not having catch? 
</blockquote></details>

Because in the calling parent method we are checking for null. If we throw an exception it will fail the pipeline exeecution.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java` line 179 at r1](https://reviewable.io/reviews/harness/harness-core/40623#-NHfufTs5ezwCZFbX44q:-NHfxpRYCNY5yX0rBfIN:b-q504mc) ([raw file](https://github.com/harness/harness-core/blob/f1a0648995b3362ed4c1379469bb4eea6826600b/960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java#L179)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

Because in the calling parent method we are checking for null. If we throw an exception it will fail the pipeline exeecution.

**Comment by markoharness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java` line 280 at r1](https://reviewable.io/reviews/harness/harness-core/40623#-NHfuSm0DCdSynm_b9vb:-NHfxqZg4Ug-K5LODRch:b-q504mc) ([raw file](https://github.com/harness/harness-core/blob/f1a0648995b3362ed4c1379469bb4eea6826600b/960-api-services/src/main/java/io/harness/azure/impl/AzureBlueprintClientImpl.java#L280)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

Because in the calling parent method we are checking for null. If we throw an exception it will fail the pipeline exeecution.

**Comment by markoharness** [comment]
trigger checkstylecodeformat

**Comment by markoharness** [comment]
trigger pmd, featurenamecheck, ti0, ti1, ti2, ti3, ti4, ft1, ft2, codebasehash, ss

**Pull request merged**
