### PR TITLE
fix: [CDS-39235]: Improving the error message for failed rancher test connection

### PR DESCRIPTION
**Pull request by namantalaycha10**
…ection

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34821)

### CODE REVIEW

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34821)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SettingValidationService.java` line 515 at r1](https://reviewable.io/reviews/harness/harness-core/34821#-N5iK3jy3qqT3_EAhG3g:-N5iK3jy3qqT3_EAhG3h:b-493czq) ([raw file](https://github.com/harness/harness-core/blob/4227a469586353275da8096e5e9ce9b0e87e5e41/400-rest/src/main/java/software/wings/service/impl/SettingValidationService.java#L515)):*
> ```Java
>     } catch (Exception e) {
>       log.error("Exception while validating RancherConfig", e);
>       throw new InvalidRequestException("Please provide the valid Rancher URL and Bearer Token", USER);
> ```

add `ExceptionUtils.getMessage(e)` as well in the message sent to the UI. It'll help the customer in reporting issues in case of different Exceptions.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34821)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SettingValidationService.java` line 515 at r1](https://reviewable.io/reviews/harness/harness-core/34821#-N5iK3jy3qqT3_EAhG3g:-N5iTGYR3BXCkaVwviVd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4227a469586353275da8096e5e9ce9b0e87e5e41/400-rest/src/main/java/software/wings/service/impl/SettingValidationService.java#L515)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add `ExceptionUtils.getMessage(e)` as well in the message sent to the UI. It'll help the customer in reporting issues in case of different Exceptions. 
</blockquote></details>

Done.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34821)* status: :shipit: complete! ✓

**Pull request merged**
