### PR TITLE
feat: [PL-41453]: bijou decrypt on manager side

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
Manager side change for secret decryption from Harness Secret Manager

Test
1. Secret is created and added to LE pod

image

2. decrypted secret value is correct 
image

3. decrypt secret from org works
image

4. decrypt secret from project works
image

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)* status: Some of the checks are too old. 1 file(s) to review. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 954 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-ecPi9U51AYupxKe5:-Ni-ecPj0LavFofvAF52:b-8ypvtm) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L954)):*
> ```Java
>           List<EncryptedDataDetail> encryptedDataDetailList = new ArrayList<>();
>           Map<String, SecretRef> encryptedRecordUuidToSecretRef = new HashMap<>();
>           delegateTask.getSecretsToDecrypt().forEach(scopedSecretId -> {
> ```

You should add bulk APIs on TaskSecretService (i.e. take collection, return collection, could also assert both have the same number of items). You can then later on decide to turn this into a proper bulk REST API requests to secret service to avoid hundreds of calls for big tasks. 
I think I remember CG customer having hundred secrets in a task (we had to increase our secret fetch timeouts because of them from 2 to 5min). 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 957 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-_6t36yuWa_mKYepw:-Ni-_6t36yuWa_mKYepx:b-mdwbcy) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L957)):*
> ```Java
>             List<EncryptedDataDetail> dataDetails =
>                 taskSecretService.getEncryptionDetails(scopedSecretId, delegateTask.getAccountId(),
>                     Optional.ofNullable(delegateTask.getOrgId()), Optional.ofNullable(delegateTask.getProjectId()));
> ```

At this point you are using orgId/projId of the task for orgId/projId of the secret which don't necessarily need to be the same (e.g. you could use account level secret for project level task). Is this expected?
IMO we shouldn't even leak the secret related implementation details like orgId/projId to delegate service as it creates a strong coupling, so would be harder to introduce changes and maintain in the future. Instead, whomever is submitting the secret they want us to decrypt should just provide the scopedId (or any other type of ID that we could use directly). 
Also, note that we are moving away from concepts of orgId/projId for our internal APIs and uniqueness constraints and would be using `parentId` in the future. orgId and projId would still exist, but would mostly be relevant only as user friendly IDs which also appear in the external APIs (so that URLs look nicer in browser), but would not be used in internal APIs (like the one you are using for secret service today). 



_Code quote:_
```Java
                taskSecretService.getEncryptionDetails(scopedSecretId, delegateTask.getAccountId(),
                    Optional.ofNullable(delegateTask.getOrgId()), Optional.ofNullable(delegateTask.getProjectId()));
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 959 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-e0tyAnGvLQP8gYBh:-Ni-e0tyAnGvLQP8gYBi:b-7l8e28) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L959)):*
> ```Java
>                     Optional.ofNullable(delegateTask.getOrgId()), Optional.ofNullable(delegateTask.getProjectId()));
>             encryptedDataDetailList.addAll(dataDetails);
>             if (dataDetails.size() == 1) {
> ```

Put this check on TaskSecretService instead and throw from there, also then you could return a single element instead of the list. You could then decide later if this becomes a use case or not in a single place. 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 971 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-f_6oD0iOoTNlrwBp:-Ni-f_6oD0iOoTNlrwBq:b6apfza) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L971)):*
> ```Java
>           secretsToDecryptByDelegate =
>               encryptedDataDetailList.stream()
>                   .map(encryptedDataDetail -> {
> ```

This is a mapper, extract it to a mapper class. 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1010 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-fqaDBEev8q73lNgu:-Ni-fqaDBEev8q73lNgv:bdc79qg) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1010)):*
> ```Java
>         builder.setAccountId(accountId);
>         builder.setOrgId(Objects.toString(delegateTask.getOrgId(), ""));
>         builder.setProjectId(Objects.toString(delegateTask.getProjectId(), ""));
> ```

Why do we need these on the delegate/runner?



_Code quote:_
```Java
        builder.setAccountId(accountId);
        builder.setOrgId(Objects.toString(delegateTask.getOrgId(), ""));
        builder.setProjectId(Objects.toString(delegateTask.getProjectId(), ""));
```

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)* status: Some of the checks are too old. 1 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 954 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-ecPi9U51AYupxKe5:-NiC6oYM1zuASAc_zDqe:bgvs52k) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L954)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You should add bulk APIs on TaskSecretService (i.e. take collection, return collection, could also assert both have the same number of items). You can then later on decide to turn this into a proper bulk REST API requests to secret service to avoid hundreds of calls for big tasks. 
I think I remember CG customer having hundred secrets in a task (we had to increase our secret fetch timeouts because of them from 2 to 5min).
</blockquote></details>

will do 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 957 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-_6t36yuWa_mKYepw:-NiC62TABKekkxFmD3Fu:byziqy9) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L957)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

At this point you are using orgId/projId of the task for orgId/projId of the secret which don't necessarily need to be the same (e.g. you could use account level secret for project level task). Is this expected?
IMO we shouldn't even leak the secret related implementation details like orgId/projId to delegate service as it creates a strong coupling, so would be harder to introduce changes and maintain in the future. Instead, whomever is submitting the secret they want us to decrypt should just provide the scopedId (or any other type of ID that we could use directly). 
Also, note that we are moving away from concepts of orgId/projId for our internal APIs and uniqueness constraints and would be using `parentId` in the future. orgId and projId would still exist, but would mostly be relevant only as user friendly IDs which also appear in the external APIs (so that URLs look nicer in browser), but would not be used in internal APIs (like the one you are using for secret service today).
</blockquote></details>

got it, i think i want to discuss with you regarding this point.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 959 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-e0tyAnGvLQP8gYBh:-NiC6n7Q3EHOAs3B9EyZ:b-rq10r4) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L959)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Put this check on TaskSecretService instead and throw from there, also then you could return a single element instead of the list. You could then decide later if this becomes a use case or not in a single place.
</blockquote></details>

good idea, will do 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 971 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-f_6oD0iOoTNlrwBp:-NiC6lboBORzXk5rUbGz:b-rq10r4) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L971)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is a mapper, extract it to a mapper class.
</blockquote></details>

good idea, will do 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1010 at r1](https://reviewable.io/reviews/harness/harness-core/54527#-Ni-fqaDBEev8q73lNgu:-NiC5Oxd7xw9wv_2iCWY:bft97vb) ([raw file](https://github.com/harness/harness-core/blob/2c44321e5f8d18ef7191aeb9da1d72b322c4f770/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1010)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why do we need these on the delegate/runner?
</blockquote></details>

this is used by secrets in the runner.
but in general it makes sense to pass scope ids to tasks, because they need it. 
Think about on browser user know abt the 3 scope ids, in tasks side too when tasks are plugins.

**Review by mdmilic — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)* status: 1 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/secret/TaskSecretServiceImpl.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/54527#-NiEbsHJCMU14qRi9Xrx:-NiEbsHJCMU14qRi9Xry:b-qbro72) ([raw file](https://github.com/harness/harness-core/blob/154a69ff612347fba989d4debd5946d2748b109b/420-delegate-service/src/main/java/io/harness/delegate/secret/TaskSecretServiceImpl.java#L57)):*
> ```Java
>       log.error("Fetching encryption details returned unexpected number of results for secret ",
>           secretIdentifierRef.getFullyQualifiedName());
>       return Optional.empty();
> ```

Not sure if valid, but I often think of these secrest as all or nothing. If we fail to decrypt one we might just as well fail the entire thing (because my expectation is that they are all required, so if one is missing the step would just fail during execution). In that regard its better to throw exception here (also saves you from optional), but again not sure if there are use cases for optional secrets.

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger uts

**Review by VikasMaddukuriHarness — APPROVED** [review]

**Comment by xingchi-jin** [comment]
trigger uts

**Comment by xingchi-jin** [comment]
trigger ut8

**Review by mdmilic — COMMENTED** [review]
> Reviewed 7 of 25 files at r3, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)* status: 33 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/secret/EncryptedDataRecordPojoProtoMapper.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/54527#-Nil03xq5cx6R0yDIG3t:-Nil03xq5cx6R0yDIG3u:b-4hanzb) ([raw file](https://github.com/harness/harness-core/blob/44541a7a63fc3c70ac6e868cfc56cb4555dd0868/420-delegate-service/src/main/java/io/harness/delegate/secret/EncryptedDataRecordPojoProtoMapper.java#L37)):*
> ```Java
> public interface EncryptedDataRecordPojoProtoMapper {
>   EncryptedDataRecordPojoProtoMapper INSTANCE = Mappers.getMapper(EncryptedDataRecordPojoProtoMapper.class);
>   @Mapping(target = "uuid", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_DEFAULT)
> ```

Not sure if it would be correct, but there is an annotation called [BeanMapping](https://mapstruct.org/documentation/dev/api/org/mapstruct/BeanMapping.html) which can be used to set general mapping parameters (e.g. nullValuePropertyMappingPolicy) for the entire mapping method. This would be set though for all fields (i.e. might be wrong if you explicitly don't want it for some fields).

**Review by mdmilic — APPROVED** [review]
> Reviewed 15 of 25 files at r3, 2 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)* status: 33 file(s) to review. 1. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/secret/EncryptionTypePojoProtoMapper.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/54527#-Nil0y0kCJXsmhgVAhYY:-Nil0y0kCJXsmhgVAhYZ:b-d037xd) ([raw file](https://github.com/harness/harness-core/blob/44541a7a63fc3c70ac6e868cfc56cb4555dd0868/420-delegate-service/src/main/java/io/harness/delegate/secret/EncryptionTypePojoProtoMapper.java#L24)):*
> ```Java
>     nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS, unmappedSourcePolicy = ReportingPolicy.ERROR,
>     unmappedTargetPolicy = ReportingPolicy.ERROR)
> public interface EncryptionTypePojoProtoMapper {
> ```

If you feel that mapstruct is an overkill in some scenarios (i.e. it would be simpler not to use it) I'm ok with not using it as well. Which ever you prefer.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54527)* status: 33 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/secret/EncryptedDataRecordPojoProtoMapper.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/54527#-Nil03xq5cx6R0yDIG3t:-NilAn2H3zCNk6OulDfb:b573ojb) ([raw file](https://github.com/harness/harness-core/blob/44541a7a63fc3c70ac6e868cfc56cb4555dd0868/420-delegate-service/src/main/java/io/harness/delegate/secret/EncryptedDataRecordPojoProtoMapper.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Not sure if it would be correct, but there is an annotation called [BeanMapping](https://mapstruct.org/documentation/dev/api/org/mapstruct/BeanMapping.html) which can be used to set general mapping parameters (e.g. nullValuePropertyMappingPolicy) for the entire mapping method. This would be set though for all fields (i.e. might be wrong if you explicitly don't want it for some fields).
</blockquote></details>

yea, i think there is some redundancy, the way i set Mappings here. but i will use the next PR to fix. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/secret/TaskSecretServiceImpl.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/54527#-NiEbsHJCMU14qRi9Xrx:-NilAw6HE1B_5FeVa4Nt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/154a69ff612347fba989d4debd5946d2748b109b/420-delegate-service/src/main/java/io/harness/delegate/secret/TaskSecretServiceImpl.java#L57)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

agree. done
</blockquote></details>

done

**Review by Raghav-Murali — APPROVED** [review]

**Review by gn-harness — APPROVED** [review]

**Review by jyotiraval — APPROVED** [review]
changed the WORKSPACE file, but that's just remove a dup line

**Pull request merged**
