### PR TITLE
[feat]:[PL-27896]: Updating GraphQL Mappers

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37167)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37167)

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37167)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupPermissionsController.java` line 439 at r2](https://reviewable.io/reviews/harness/harness-core/37167#-NBGGAMM-yl9e9CvbhSa:-NBGGAMN4FYoYScIICH6:b-hrp82b) ([raw file](https://github.com/harness/harness-core/blob/70e0fddd09246f1f25cbe4585f6de3838e3200c8/400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupPermissionsController.java#L439)):*
> ```Java
>       actionsList.add(QLActions.EXECUTE_PIPELINE);
>       actionsList.add(QLActions.ROLLBACK_WORKFLOW);
>       actionsList.add(QLActions.ABORT_WORKFLOW);
> ```

why are giving this by default? Shouldn't it be based on Execute Workflow?

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37167)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 655 at r3](https://reviewable.io/reviews/harness/harness-core/37167#-NBGSnytDNtKTFKAlp8h:-NBGSnyu51Yws_YXVx3K:bwf9wc) ([raw file](https://github.com/harness/harness-core/blob/34a8d3aa7456a635fa1160794248f8985699b0c4/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L655)):*
> ```Java
>           }
>           if (action != null && action.equals(EXECUTE_WORKFLOW)) {
>             actionSet.add(ABORT_WORKFLOW);
> ```

add enum when EXECUTE is there (for backward compatibility), rest looks good



_Code quote:_
```Java
EXECUTE
```

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupPermissionsController.java` line 439 at r2](https://reviewable.io/reviews/harness/harness-core/37167#-NBGGAMM-yl9e9CvbhSa:-NBGU_PN-T6VQyQhu8zE:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/70e0fddd09246f1f25cbe4585f6de3838e3200c8/400-rest/src/main/java/software/wings/graphql/datafetcher/userGroup/UserGroupPermissionsController.java#L439)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

why are giving this by default? Shouldn't it be based on Execute Workflow? 
</blockquote></details>

Done

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 655 at r3](https://reviewable.io/reviews/harness/harness-core/37167#-NBGSnytDNtKTFKAlp8h:-NBGUcXp8kusIkDzuUew:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/34a8d3aa7456a635fa1160794248f8985699b0c4/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L655)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

add enum when EXECUTE is there (for backward compatibility), rest looks good
</blockquote></details>

Done.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37167)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by boopesh007** [comment]
trigger messagecheck

**Review by hingerabhinav — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37167#-:-NBGaBSoBQ04xipLEfY4:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
