### PR TITLE
fix: [DEL-6287]: Updated delegate UI error message for capability failure

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Changes to add capability failure information when not able to assign task to any delegate. Changes are in the iterator codepath.

Tested in local and PR branch while creating a step with unreachable URL, with 1 and 1+ delegates

image
image

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46548)

### CODE REVIEW

**Comment by gn-harness** [comment]
trigger feature-build

**Comment by gn-harness** [comment]
trigger feature-build

**Comment by gn-harness** [comment]
trigger feature-build

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46548)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1150 at r5](https://reviewable.io/reviews/harness/harness-core/46548#-NTVeNqG1Nh-VaaR4_Mc:-NTVeNqG1Nh-VaaR4_Md:b6z7im4) ([raw file](https://github.com/harness/harness-core/blob/dfff232d7f2f181dc54f41ddb438459e49de1659/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1150)):*
> ```Java
> 
>     for (DelegateConnectionResult connectionResult : delegateConnectionResults) {
>       if (!eligibleDelegateIds.contains(connectionResult.getDelegateId())) {
> ```

why not filter this in db query ?

**Comment by gn-harness** [comment]
> 



> 



> > Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/46548)_ status: :shipit: complete! ✓
> 
> _[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1150 at r5](https://reviewable.io/reviews/harness/harness-core/46548#-NTVeNqG1Nh-VaaR4_Mc:-NTVeNqG1Nh-VaaR4_Md:b6z7im4) ([raw file](https://github.com/harness/harness-core/blob/dfff232d7f2f181dc54f41ddb438459e49de1659/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1150)):_
> 
> > ```java
> >     for (DelegateConnectionResult connectionResult : delegateConnectionResults) {
> >       if (!eligibleDelegateIds.contains(connectionResult.getDelegateId())) {
> > ```
> 
> why not filter this in db query ?

Good point, this could have been done. However, since there is a filter on the delegateTask - delta should be minimum, so ok to skip to save me a round of testing?

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46548)* status: 1. unresolved discussions.

**Pull request merged**
