### PR TITLE
[feat]: [PL-31460]: Migration Task for UserAccountLevel Data generation

### PR DESCRIPTION
**Pull request by shashank-harness**
## Describe your changes
Store User Data with newly introduced AccountLevelData property for each account this user is part of.
Details about the root cause and solution [here](https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21272101267/Solving+User+Management+In+Harness)

Migration logic detailed [here](https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21272101267/Solving+User+Management+In+Harness#Migration-of-existing-users)

**Testing:**
- Tested with accounts in local for both CG NG.
- Tested for all 3- Manual, SCIM and LDAP Users.
- More testing will be performed in Pre-QA once this PR is merged.
- 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)

### CODE REVIEW

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: :shipit: complete! ✓

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
Approving for PreQA testing without test cases. @shashank-harness Please ensure test cases are implemented before code goes to QA . :lgtm:

**Review by piyush-harness — APPROVED** [review]
> Reviewed 20 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/UserServiceHelperTest.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/46419#-NTBedsEChob2FaHAwII:-NTBedsEChob2FaHAwIJ:b-dky9y9) ([raw file](https://github.com/harness/harness-core/blob/4607fe3b4630c496c1a63726e238292769337738/400-rest/src/test/java/software/wings/service/impl/UserServiceHelperTest.java#L157)):*
> ```Java
>     userServiceHelper.populateAccountToUserMapping(user, account.getUuid(), Generation.NG, MANUAL);
>     boolean result = userServiceHelper.isUserActiveInNG(user, ACCOUNT_ID);
> ```

Revert this new line

**Review by shashank-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 21 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/UserServiceHelperTest.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/46419#-NTBedsEChob2FaHAwII:-NTCLRLNCVkmjNZCOvQv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4607fe3b4630c496c1a63726e238292769337738/400-rest/src/test/java/software/wings/service/impl/UserServiceHelperTest.java#L157)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Revert this new line
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]

**Comment by shashank-harness** [comment]
trigger ut8

**Review by piyush-harness — APPROVED** [review]
> Reviewed 18 of 20 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 21 file(s) to review.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 21 file(s) to review. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserAccountLevelDataMigrationJob.java` line 62 at r6](https://reviewable.io/reviews/harness/harness-core/46419#-NTE-Tnn6edjZgUrDSFm:-NTE-Tno1-z_8aEbsZwX:b5f7xkg) ([raw file](https://github.com/harness/harness-core/blob/56b77fa8cb5d0f81d4ac1ad659aae2af51abe683/400-rest/src/main/java/software/wings/service/impl/UserAccountLevelDataMigrationJob.java#L62)):*
> ```Java
> @Slf4j
> @Singleton
> public class UserAccountLevelDataMigrationJob implements Managed {
> ```

This migration should be a background migration i.e. should be part of MigrationBackgroundList.
Currently it will hamper cg-manager start up, which is not a good idea.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 18 of 20 files at r4, 1 of 1 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 1 of 22 files at r1, 18 of 20 files at r4, 1 of 1 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: :shipit: complete! ✓

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 18 of 20 files at r4, 1 of 1 files at r6, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: :shipit: complete! ✓

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46419)* status: :shipit: complete! ✓

**Pull request merged**
