### PR TITLE
[fix]: [PL-23636]: Gitsync - error improvement on which crednetial is incorrect SCM vs connector

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31527)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31527)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 297 at r1](https://reviewable.io/reviews/harness/harness-core/31527#-MyLSUZO1wv4a8dmJ3vS:-MyLSUZO1wv4a8dmJ3vT:b-tdh948) ([raw file](https://github.com/harness/harness-core/blob/941a42e6f6ba17a107f0b1a9d9b6faf18f804ffc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L297)):*
> ```Java
>                 entityReference.getProjectIdentifier(), entityReference.getOrgIdentifier(), accountId);
> 
>         checkForUnauthorizedErrorCode(request, deleteFileResponse.getStatus());
> ```

Can this check be part of ScmResponse...Utils ?

So that we don't have to explicitly call it every time.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 373 at r1](https://reviewable.io/reviews/harness/harness-core/31527#-MyLTNhV96tOqaTnksbB:-MyLTNhV96tOqaTnksbC:btrrbir) ([raw file](https://github.com/harness/harness-core/blob/941a42e6f6ba17a107f0b1a9d9b6faf18f804ffc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L373)):*
> ```Java
> 
>   private void checkForUnauthorizedErrorCode(FileInfo request, int status) {
>     if (request.getIsFullSyncFlow() || request.getPrincipal().hasUserPrincipal()) {
> ```

nit: 
Though there is no case right now, but in future:

There might be a case when we have set request principal in the request and we are using the connector credentials.
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/31527#-MyLSOhL0-d9sjvVGzHy:-MyLSOhMBB_p3lrk1rNL:b-bvinj6) ([raw file](https://github.com/harness/harness-core/blob/941a42e6f6ba17a107f0b1a9d9b6faf18f804ffc/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L20)):*
> ```Java
>       + "3. Credentials have expired";
> 
>   public static final String INCORRECT_SCM_CREDENTIALS="Incorrect SCM credentials";
> ```

We will need to add more details here

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 273 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_-_m1RkADQEe2x5o:-MyM_-_n1dtiUT-LuQCY:b6dutin) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L273)):*
> ```Java
>               .build();
>         } catch (Exception ex) {
>           processException(request, ex);
> ```

we can put this in global try catch over the complete method itself. We don't need to repeat this for all ops : Modify, Add etc.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 384 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_EG96jLct4nmJj5K:-MyM_EG96jLct4nmJj5L:b6gag4o) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L384)):*
> ```Java
>   protected void processException(FileInfo request, Exception ex) {
>     final WingsException cause = ExceptionUtils.cause(ErrorCode.SCM_UNAUTHORIZED, ex);
>     if (request.getIsFullSyncFlow() || request.getPrincipal().hasUserPrincipal()) {
> ```

can we further make it modular for SCM unauthorized exception? Think about it what if there are 2 more types of error codes you want to handle now, it will make this method go messy. Agreed?

**Comment by mohitg0795** [comment]
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/31527#-MyLSOhL0-d9sjvVGzHy:-MyM_QfW03wTKdr9-d3c:b32v57) ([raw file](https://github.com/harness/harness-core/blob/941a42e6f6ba17a107f0b1a9d9b6faf18f804ffc/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L20)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

We will need to add more details here
</blockquote></details>

+1

**Comment by mohitg0795** [comment]
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 15 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_WWh6_uRRaszfMgv:-MyM_WWh6_uRRaszfMgw:b-adftit) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L15)):*
> ```Java
> public class SCMExceptionExplanations {
>   public static final String UNABLE_TO_PUSH_TO_REPO_WITH_USER_CREDENTIALS =
>       "We could not perform git operation using the credentials of the user. Possible reasons can be:\n"
> ```

I think we can also remove mentioning "using credentials of the user". This is also redundant right?

**Comment by mohitg0795** [comment]
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 15 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_WWh6_uRRaszfMgv:-MyM_bGW2FW7xpMu706a:b-o3hjfy) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L15)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we can also remove mentioning "using credentials of the user". This is also redundant right? 
</blockquote></details>

We can probably mention for now : "We couldn't perform required git operation"

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31527)* status: 7 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 297 at r1](https://reviewable.io/reviews/harness/harness-core/31527#-MyLSUZO1wv4a8dmJ3vS:-MyN7QMU4Zut_zQbKxkN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/941a42e6f6ba17a107f0b1a9d9b6faf18f804ffc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L297)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Can this check be part of ScmResponse...Utils ?

So that we don't have to explicitly call it every time.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 273 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_-_m1RkADQEe2x5o:-MyN7NiF7vJEw-IX29UX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L273)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can put this in global try catch over the complete method itself. We don't need to repeat this for all ops : Modify, Add etc.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java, line 384 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_EG96jLct4nmJj5K:-MyN7T1V0Lh6RGeKQYEy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L384)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we further make it modular for SCM unauthorized exception? Think about it what if there are 2 more types of error codes you want to handle now, it will make this method go messy. Agreed?
</blockquote></details>

Done.
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/31527#-MyLSOhL0-d9sjvVGzHy:-MyN7V_p9JGfU4QnnI7X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/941a42e6f6ba17a107f0b1a9d9b6faf18f804ffc/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java, line 15 at r2](https://reviewable.io/reviews/harness/harness-core/31527#-MyM_WWh6_uRRaszfMgv:-MyN7ULm1gwBUs1U8jdF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8bf026874f41380d01b91099ab20251ea1e8794/952-scm-java-client/src/main/java/io/harness/exception/SCMExceptionExplanations.java#L15)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We can probably mention for now : "We couldn't perform required git operation"
</blockquote></details>

Done.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31527)* status: 7 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31527#-:-MyNtQxDBlTOR_HCdO1l:bnfp4nl)* status: :shipit: complete! ✓

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31527)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31527#-:-MySF5Ct04xbw_wkoS8I:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
