### PR TITLE
[feat]: [PL-25623]: added audit trails for NG Auth Settings

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added audit trails for NG Auth Settings:
1. Harness UserName and Password
2. Restrict users to email domains

Below Scenarios are WIP:
1. Use Public OAuth Providers
2. + SAML Provider
3. Enforce Two Factor Authentication

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36312)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36312)

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
Screenshot 2022-08-14 at 12 06 13 AM
Screenshot 2022-08-14 at 12 06 45 AM

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/LoginSettingsServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R-Znj5u-c2MFWowuP:-N9R-Znj5u-c2MFWowuQ:b-o9r2y3) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/LoginSettingsServiceImpl.java#L272)):*
> ```Java
>     LoginSettings newLoginSettings = updateAndGetLoginSettings(loginSettingsId, accountId, operations);
>     auditLoginSettings(accountId, newLoginSettings);
>     ngAuditLoginSettings(accountId, oldLoginSettings, newLoginSettings);
> ```

if auditing fails, do we want to fail the complete update as there's no try catch to handle it?

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R09WD-4TNh1s-MoZF:-N9R09WD-4TNh1s-MoZG:b-mgzb3w) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L47)):*
> ```Java
>   @Override
>   public boolean handle(OutboxEvent outboxEvent) {
>     log.info("Outbox event handler: {}", outboxEvent);
> ```

just checking if this outbox event is logged properly? We should check it once.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R0P8x1W_dWEoogwt7:-N9R0P8x1W_dWEoogwt8:b-toi4ty) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L55)):*
> ```Java
>         case WHITELISTED_DOMAINS_UPDATED:
>           return handleWhitelistedDomainsUpdateEvent(outboxEvent, globalContext);
>         default:
> ```

shouldn't we log unidentified event type here?

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R0Sbf28OsOt-KNwzB:-N9R0Sbf28OsOt-KNwzC:bovsp72) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L59)):*
> ```Java
>       }
>     } catch (IOException exception) {
>       return false;
> ```

log exception

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1713 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R1CtW22SUUJ4K5PdZ:-N9R1CtX96UTvE8FumVN:b-sq9ts0) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1713)):*
> ```Java
>     }
> 
>     Account account = getAccounts(Arrays.asList(accountId)).get(0);
> ```

what if the result is empty list?



_Code quote:_
```Java
getAccounts
```

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1719 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R1HDw85muPdkiNvPF:-N9R1HDw85muPdkiNvPG:bmuo41x) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1719)):*
> ```Java
>     wingsPersistence.update(wingsPersistence.createQuery(Account.class).filter(Mapper.ID_KEY, accountId),
>         whitelistedDomainsUpdateOperations);
>     ngAuditLoginSettings(accountId, account.getWhitelistedDomains(), validDomains);
> ```

There's no try catch over outboxService call. Do we intentionally want to fail the complete update operation if outbox service call fails?

**Comment by pbarapatre10** [comment]
Please add some UTs @kapil-harness. Thanks

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36312)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-NA4SidDCWkHzlZjWjGa:-NA4SidDCWkHzlZjWjGb:b3v1lgt) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java#L64)):*
> ```Java
>   public static final String AUTOSTOPPING_STARTSTOP = "AUTOSTOPPING_STARTSTOP";
>   public static final String SETTING = "SETTING";
>   public static final String NG_LOGIN_SETTINGS = "NG_LOGIN_SETTINGS";
> ```

Change in platform service should be a separate PR and should go to prod at-least one release ahead from this PR.

**Review by kapil-harness — COMMENTED** [review]
I am planning to add UTs in the next PR. First trying to get the basic design right.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36312#-:-NA4QaQ41D-vJILHZ7To:b-ppms5r)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/LoginSettingsServiceImpl.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R-Znj5u-c2MFWowuP:-NA4M-B140qIJcbmHUh4:bulp7lf) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/LoginSettingsServiceImpl.java#L272)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if auditing fails, do we want to fail the complete update as there's no try catch to handle it?
</blockquote></details>

No we do not want to fail the complete update. So added a log in the try catch.
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R09WD-4TNh1s-MoZF:-NA4Lxs-2ZbcYXTFvZCm:b-vbid16) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

just checking if this outbox event is logged properly? We should check it once.
</blockquote></details>

you were right, it is just printing the class name and not the object value. 
Removed this log as its not required.
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R0P8x1W_dWEoogwt7:-NA4N7B-0Aw1wajSrbCB:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't we log unidentified event type here?
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R0Sbf28OsOt-KNwzB:-NA4N89FBTyOJCH3wRyO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1713 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R1CtW22SUUJ4K5PdZ:-NA4TtGV2W_DMF3mG5su:braq0z4) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1713)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if the result is empty list?
</blockquote></details>

handled the empty list failure scenario, thanks nice catch.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 1719 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-N9R1HDw85muPdkiNvPF:-NA4R_2t7AE646Zx9qbq:bi8jvog) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L1719)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

There's no try catch over outboxService call. Do we intentionally want to fail the complete update operation if outbox service call fails?
</blockquote></details>

done, same as above.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36312)* status: 10 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/36312#-NA4SidDCWkHzlZjWjGa:-NA5Oh6l4J9Ff7MrrknV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7bbd769e9d0d8bc045c3dc68c8d5267b5b11934a/platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java#L64)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Change in platform service should be a separate PR and should go to prod at-least one release ahead from this PR.
</blockquote></details>

done

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/36312#-NA5iYZKDShJWFV4nCLW:-NA5iYZKDShJWFV4nCLX:b-rfe4tn) ([raw file](https://github.com/harness/harness-core/blob/8a183d80aa4a196b897ffbe0d58679be717c660b/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L59)):*
> ```Java
>       }
>     } catch (IOException exception) {
>       log.error("Failed to handle " + outboxEvent.getEventType() + " event with exception: ", exception);
> ```

we should always log the error like : log.error(<message>, exception). This prints complete stacktrace of the exception.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 4 of 8 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36312#-:-NA84_i-7a0jJ1geARER:bnfp4nl)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36312)* status: :shipit: complete! ✓

**Pull request merged**
