### PR TITLE
[feat]: [CDS-68522]: Remove second remote git call in execution flow

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Issue:
In the execution flow, there are 2 remote git calls happening. In this pr, we have added code to remove the second git call during the execution flow. Due to this the customer hits the rate limits when they are executing pipelines within one hour window.

Approach:
We have added a new field pipelineYaml in the PlanExecutionMetadata collection. After the first git call, we are storing the pipeline yaml in the newly added filed in PlanExecutionMetadata and after the usage of this field we are unsetting the value to avoid increasing the size of the PlanExecutionMetadata collection. 

Impact:
The execution flow will have only one remote git call, which will help with the customer not reaching rate limits.

Testing:
1. Pipeline run flow
2. Pipeline rerun flow
3. Pipeline retry flow [before the pr, 3 remote calls, after this code enhancement 2 remote calls]

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51474)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51474)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/51474#-NbOuvPSC4QIi34D5Oc6:-NbOuvPSC4QIi34D5Oc7:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/e9022a1c4cb6e8513f32f68ec1819a65759ab1e8/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java#L36)):*
> ```Java
>   String updateNotesForExecution(String planExecutionId, String notes);
> 
>   String updatePipelineYaml(String planExecutionId);
> ```

why do we need this?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/51474#-NbOuzDS0w-eBNsDI8HM:-NbOuzDS0w-eBNsDI8HN:bo612q4) ([raw file](https://github.com/harness/harness-core/blob/e9022a1c4cb6e8513f32f68ec1819a65759ab1e8/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L91)):*
> ```Java
> 
>   @Override
>   public String updatePipelineYaml(String planExecutionId) {
> ```

not required as annotation should work
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/PlanExecutionMetadata.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/51474#-NbOumVU3E9Ofz25dh4d:-NbOumVV0e2fWy3gg5kc:b-g8c3vf) ([raw file](https://github.com/harness/harness-core/blob/e9022a1c4cb6e8513f32f68ec1819a65759ab1e8/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/PlanExecutionMetadata.java#L64)):*
> ```Java
> 
>   // Pipeline yaml before resolving templates and input sets
>   private String pipelineYaml;
> ```

Add @transient annotation to it so even by chance we don't unset it it will not get saved into db

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51474)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/51474#-NbOuzDS0w-eBNsDI8HM:-NbPPK_q5-WMyKTx-9l0:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/e9022a1c4cb6e8513f32f68ec1819a65759ab1e8/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataServiceImpl.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

not required as annotation should work
</blockquote></details>

removed
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/PlanExecutionMetadata.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/51474#-NbOumVU3E9Ofz25dh4d:-NbPDC71-Ba8tDxWSSGw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e9022a1c4cb6e8513f32f68ec1819a65759ab1e8/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/PlanExecutionMetadata.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add @transient annotation to it so even by chance we don't unset it it will not get saved into db
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/51474#-NbOuvPSC4QIi34D5Oc6:-NbPPJpEEOcUJ8CZiXC6:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/e9022a1c4cb6e8513f32f68ec1819a65759ab1e8/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionMetadataService.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

removed

**Comment by adivishy1** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51474)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
