### PR TITLE
feat: [SRM-12043]: Modify write to include service level objective v2

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37954)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 22 Issues 
* Code issue 18 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37954)

**Comment by Varsha-lalwani** [comment]
trigger pmd

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37954)* status: 34 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java` line 892 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2ejKu7JxfKefkdRom:-ND2ejKu7JxfKefkdRon:b-n69z3j) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L892)):*
> ```Java
>                     query.criteria(ServiceLevelObjectiveV2Keys.lastUpdatedAt)
>                         .greaterThan(
>                             injector.getInstance(Clock.class).instant().minus(240, ChronoUnit.MINUTES).toEpochMilli()),
> ```

lets keep it 45 minutes.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/jobs/ServiceLevelObjectiveV2VerifyTaskHandler.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2f1F34Tmw7P6EH0R7:-ND2f1F34Tmw7P6EH0R8:bwn9add) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/core/jobs/ServiceLevelObjectiveV2VerifyTaskHandler.java#L39)):*
> ```Java
>         serviceLevelObjectiveService.getEntity(projectParams, serviceLevelObjectiveV2.getIdentifier());
>     if (Objects.isNull(serviceLevelObjective)) {
>       log.warn("[SLO Data Mismatch]: SLO with identifier " + serviceLevelObjectiveV2.getIdentifier() + " not found");
> ```

let's convert it to error.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2f_0j8iSCLJ8YW7Nd:-ND2f_0j8iSCLJ8YW7Ne:bmq5cav) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L47)):*
> ```Java
>   ServiceLevelIndicatorType type;
>   @Valid @NotNull List<ServiceLevelIndicatorDTO> serviceLevelIndicators;
>   @Valid @NotNull SLOTargetDTO target;
> ```

nit: UI should use the new swagger.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2fm8W0uofBfLl0LKr:-ND2fm8W0uofBfLl0LKs:bckkswq) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L41)):*
> ```Java
>     description = "This is the Service Level Objective V2 entity defined in Harness")
> public class ServiceLevelObjectiveV2DTO implements YamlDTO {
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier ServiceLevelObjectiveType serviceLevelObjectiveType;
> ```

type instead of serviceLevelObjectiveType
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2gEWg2mz4g7Xm37qR:-ND2gEWg2mz4g7Xm37qS:b-8ogsb5) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L42)):*
> ```Java
> public class ServiceLevelObjectiveV2DTO implements YamlDTO {
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier ServiceLevelObjectiveType serviceLevelObjectiveType;
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier String orgIdentifier;
> ```

Can be null
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2gHCt7UVmuIkbVh3L:-ND2gHCt7UVmuIkbVh3M:b-8ogsb5) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L43)):*
> ```Java
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier ServiceLevelObjectiveType serviceLevelObjectiveType;
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier String orgIdentifier;
>   @ApiModelProperty(required = true) @NotNull @EntityIdentifier String projectIdentifier;
> ```

Can be null
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2gPqj6RzEbvP4LisH:-ND2gPqj6RzEbvP4LisI:b-gas4uy) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L52)):*
> ```Java
>   @ApiModelProperty(required = true) @NotNull String healthSourceRef;
>   @Valid ServiceLevelIndicatorType serviceLevelIndicatorType;
>   @Valid List<ServiceLevelIndicatorDTO> serviceLevelIndicators;
> ```

nit: Should move to different specs.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2gW632LY6rFfRuWsU:-ND2gW632LY6rFfRuWsV:bq702o8) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveV2DTO.java#L53)):*
> ```Java
>   @Valid ServiceLevelIndicatorType serviceLevelIndicatorType;
>   @Valid List<ServiceLevelIndicatorDTO> serviceLevelIndicators;
>   @Valid List<CompositeServiceLevelObjective.ServiceLevelObjectivesDetail> serviceLevelObjectivesDetails;
> ```

Should use serviceLevelObjectiveDetailsDTO.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2hKFy-b4kMnuT7Hql:-ND2hKFy-b4kMnuT7Hqm:b-lg2bc6) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveServiceImpl.java#L183)):*
> ```Java
>                                 .getSLOTarget(serviceLevelObjectiveDTO.getTarget().getSpec())
>                                 .getCurrentTimeRange(currentLocalDate);
>     TimePeriod currentTimePeriod = serviceLevelObjective.getCurrentTimeRange(currentLocalDate);
> ```

nit: Util class.



_Code quote:_
```Java
    LocalDateTime currentLocalDate = LocalDateTime.ofInstant(clock.instant(), ZoneOffset.UTC);
    TimePeriod timePeriod = sloTargetTypeSLOTargetTransformerMap.get(serviceLevelObjectiveDTO.getTarget().getType())
                                .getSLOTarget(serviceLevelObjectiveDTO.getTarget().getSpec())
                                .getCurrentTimeRange(currentLocalDate);
    TimePeriod currentTimePeriod = serviceLevelObjective.getCurrentTimeRange(currentLocalDate);
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2kHUV6958GbJzD0dA:-ND2kHU_CTVd3ccMjgxE:bumek4h) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L218)):*
> ```Java
>     updateOperations.set(
>         ServiceLevelObjectiveV2Keys.userJourneyIdentifiers, serviceLevelObjectiveV2DTO.getUserJourneyRefs());
>     if (abstractServiceLevelObjective.getServiceLevelObjectiveType().equals(ServiceLevelObjectiveType.SIMPLE)) {
> ```

lets use setUpdateOperations in individual classes for update operations



_Code quote:_
```Java
    if (abstractServiceLevelObjective.getServiceLevelObjectiveType().equals(ServiceLevelObjectiveType.COMPOSITE)) {
      updateOperations.set(CompositeServiceLevelObjectiveKeys.serviceLevelObjectivesDetails,
          serviceLevelObjectiveV2DTO.getServiceLevelObjectivesDetails());
    }
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2kz0z-LNVDgYIJEXo:-ND2kz0z-LNVDgYIJEXp:b-z5d2b4) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L252)):*
> ```Java
> 
>   private void deleteNotificationRuleRefs(ProjectParams projectParams,
>       AbstractServiceLevelObjective serviceLevelObjective, List<NotificationRuleRef> notificationRuleRefs) {
> ```

send serviceLevelObjective.getNotificationRuleRefs only. move the method to NotificationServiceImpl.



_Code quote:_
```Java
 serviceLevelObjective
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2lXoQ956Vh6aDrZXv:-ND2lXoQ956Vh6aDrZXw:bta0emh) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L44)):*
> ```Java
>         .serviceLevelObjectivesDetails(
>             Collections.singletonList(CompositeServiceLevelObjective.ServiceLevelObjectivesDetail.builder()
>                                           .weightagePercentage(100.00)
> ```

use servicelevelobjectivedetails.getweightage
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2lhK30ZLPNqph5W4n:-ND2lhK41AMscpTbHnJr:byt3pbh) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L55)):*
> ```Java
>   @Override
>   public CompositeServiceLevelObjective getSLOV2(ServiceLevelObjective serviceLevelObjective) {
>     return CompositeServiceLevelObjective.builder()
> ```

Throw an exception. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/37954#-ND2lxuy0dNPaK9K0ADS:-ND2lxuy0dNPaK9K0ADT:b-cgiasl) ([raw file](https://github.com/harness/harness-core/blob/fe996621267107b78cf45403abe37ef078a167bd/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L105)):*
> ```Java
> 
>   public ServiceLevelObjectiveV2DTO getSLOV2DTO(ServiceLevelObjectiveDTO serviceLevelObjectiveDTO) {
>     return ServiceLevelObjectiveV2DTO.builder()
> ```

throw an exception

**Review by deepak-harness — APPROVED** [review]
> Reviewed 21 of 34 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37954)* status: :shipit: complete! ✓

**Pull request merged**
