### PR TITLE
[feat]: [CDS-84705]: Added webhook processing behind the setting

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added the bi directional sync processing behind the account level setting. Have tested the following loaclly:
1. Processing of webhook events when the setting is enabled/disabled
2. Using Cache in the getFile and execution flows when the setting is enabled/disabled

Also, Fixed the uts in ScmFacilitatorServiceImplTest.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55985)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger uts

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55985)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/helper/GitXWebhookHelper.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/55985#-NkZ0Ttn21HOUxK4mwCW:-NkZ2EJe4ng99UgQJkL1:b-qzycc6) ([raw file](https://github.com/harness/harness-core/blob/01aa1195d4cfb6eed10ec0244bc31289d85c276d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/helper/GitXWebhookHelper.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add exception handling if exception, treat as false
</blockquote></details>

yes, added
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/55985#-NkZ0_m61XQ1KT9oSQ4S:-NkZ3cb038b9WLKHXZy5:b-yalb74) ([raw file](https://github.com/harness/harness-core/blob/01aa1195d4cfb6eed10ec0244bc31289d85c276d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookEventServiceImpl.java#L78)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: is this okay that we will get too many log lines for this?
</blockquote></details>

agreed, removed the log line

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55985)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
