### PR TITLE
fix: [DEL-2812]: Skip publishing stack driver logging based on config

### PR DESCRIPTION
**Pull request by gaurav-jain1**
…uration

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[960-watcher/src/main/resources/logback.xml, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwLlQhEqzoFFbsSqMd:-MuwLlQi0Y6-5DN_ZhiG:b1rukhg) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/960-watcher/src/main/resources/logback.xml#L34)):*
> ```XML
>     </appender>
> 
>     <if condition='property("STACK_DRIVER_LOGGING_ENABLED").equalsIgnoreCase("true")'>
> ```

is STACK_DRIVER_LOGGING_ENABLED for all the delegates for customers ? if thats not the case then wouldn't it just stop logging for all delegates in field?



_Code quote:_
```XML
STACK_DRIVER_LOGGING_ENABLED
```

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/resources/logback-test.xml, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwWN_oE-tuKbRZ7vvk:-MuwWN_s6ETnJs2nil5G:bxyaa58) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/260-delegate/src/main/resources/logback-test.xml#L41)):*
> ```XML
>     </appender>
> 
>     <if condition='property("STACK_DRIVER_LOGGING_ENABLED").equalsIgnoreCase("true")'>
> ```

I think you probably want the condition the other way around (i.e. STACK_DRIVER_LOGGING_DISABLED != true) so that you have it enabled by default. 
Other thank that it would probably be better to make the referencing appender conditional (i.e. you have the config, but not use it vs you try to use the config but don't have it). The 
<appender-ref ref="REST2"/>

**Review by mdmilic — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/resources/logback-test.xml, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwWN_oE-tuKbRZ7vvk:-MuwXCts49t7sr4wbTjD:bjon2zr) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/260-delegate/src/main/resources/logback-test.xml#L41)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think you probably want the condition the other way around (i.e. STACK_DRIVER_LOGGING_DISABLED != true) so that you have it enabled by default. 
Other thank that it would probably be better to make the referencing appender conditional (i.e. you have the config, but not use it vs you try to use the config but don't have it). The 
<appender-ref ref="REST2"/>
</blockquote></details>

This is the line I would conditionally exclude



_Code snippet:_
```XML
<appender-ref ref="REST2"/>
```

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/resources/logback-test.xml, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwWN_oE-tuKbRZ7vvk:-MuyQnYeE6klbS2tri2D:b-3wcrt4) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/260-delegate/src/main/resources/logback-test.xml#L41)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is the line I would conditionally exclude
</blockquote></details>

Do we have not equals operation in logback ? I didn't find any..

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/resources/logback-test.xml, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwWN_oE-tuKbRZ7vvk:-MuyVorlCRtldtax45-B:ba7554i) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/260-delegate/src/main/resources/logback-test.xml#L41)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Do we have not equals operation in logback ? I didn't find any..
</blockquote></details>

true, I didn't find also, maybe you can do 
```isNull(STACK_DRIVER_LOGGING_DISABLED) || p("STACK_DRIVER_LOGGING_DISABLED").equalsIgnoreCase("false")```
Or have the appender in the else (and empty if)

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/resources/logback-test.xml, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwWN_oE-tuKbRZ7vvk:-MuyWa_T9BVmnjd2hvGh:buyaov7) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/260-delegate/src/main/resources/logback-test.xml#L41)):*
> ("STACK_DRIVER_LOGGING_DISABLED").equalsIgnoreCase("false")
STACK_DRIVER_LOGGING_DISABLED is not intuitive. Rest of the code we are using 'STACK_DRIVER_LOGGING_ENABLED' and as a customer its easy to understand flag with "ENABLED" name rather than "DISABLED"
See the modified code.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486#-:-MvKqE-U5j8gkCR_Cj74:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 1 change requests. 1. unresolved discussions.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 1 change requests. 2. unresolved discussions. 

___
*[960-watcher/src/main/resources/logback.xml, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30486#-MuwLlQhEqzoFFbsSqMd:-MvMe1G-ErQ-wUFsrPTI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a9572bdb83f7cf66f21da34db245d5f3822a813/960-watcher/src/main/resources/logback.xml#L34)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

is STACK_DRIVER_LOGGING_ENABLED for all the delegates for customers ? if thats not the case then wouldn't it just stop logging for all delegates in field?
</blockquote></details>

Done.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 1 change requests. 1. unresolved discussions.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486)* status: 1. unresolved discussions.

**Review by arpit3107 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30486#-:-MvN3CRR6ihKaKWJsnkX:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
