### PR TITLE
feat: [PL-30097]: Audits for Streaming Destination

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
Adding audits for streaming destination.
Onboarded the outbox framework to publish audits for the streaming destination.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)

### CODE REVIEW

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: 17 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLKpkg3U7NGEwrxdqM:-NLU5yBJ3N6hPtyo28IE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java#L78)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Camel case? streamingDestination
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingDestinationEventHandler.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLLsNa9LrlQ-PYCIrv:-NLU5yu5591yOxcy0cnr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingDestinationEventHandler.java#L72)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use constant here and above cases.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingDestinationEventHandler.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLNGDsA4irXcCv7syu:-NLU5zc346N2crOnsoKk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/streaming/impl/StreamingDestinationEventHandler.java#L165)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

log action and streaming destination identifier as well.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationCreateEvent.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLL_KO49j2WOC5cRo2:-NLU6-9q5M6BOPArGYcD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationCreateEvent.java#L60)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Create constant in this class itself.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationDeleteEvent.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLLhQc85fYxrLWZkmr:-NLU6-tx8cnZ7j-B6oAA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationDeleteEvent.java#L60)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Create constant in this class itself.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationUpdateEvent.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLOYFk4NRYhpXfLdVs:-NLU65XV36Mj9sItp0Yr:b-y636v3) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationUpdateEvent.java#L44)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Certain methods like this are same in all the three events (Create, Delete and Update). Can we have a based class say StreamingDestinationEvent having common methods to avoid code duplication?
</blockquote></details>

No, since every event needs to extend the event class, we cannot have a base class.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationUpdateEvent.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLLiLS2Y0aANz9aI9g:-NLU6BjrAkxQ_WLOsJug:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationUpdateEvent.java#L63)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Create constant in this class itself.
</blockquote></details>

Done.
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/mapper/streaming/StreamingDestinationMapper.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLPMJf5LFIUwTx9hkL:-NLU84d16DgUEUSfxwd0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/mapper/streaming/StreamingDestinationMapper.java#L36)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Spec dto will be based on type. e.g. if type is AWS_S3 then spec dto will be AwsS3StreamingDestinationSpecDTO. Modify this mapper method to support this.
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceConfiguration.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLQy3d6crXLctxX1zj:-NLUAtyS4estECFfYNz7:b-ghggkc) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceConfiguration.java#L33)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

For the outbox module

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: 17 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/test/java/io/harness/audit/api/streaming/impl/StreamingServiceImplTest.java` line 127 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLQi7g8dLMM1axBZUx:-NLUCzvn8h5zeI22OxdN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/test/java/io/harness/audit/api/streaming/impl/StreamingServiceImplTest.java#L127)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

verify outbox save is called. Same in delete and update test cases as well.
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: 17 file(s) to review. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationUpdateEvent.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/42136#-NLLOYFk4NRYhpXfLdVs:-NLdXK729qBipZ-kUSFq:blnj3b4) ([raw file](https://github.com/harness/harness-core/blob/2689223d293de8041f3f94b43bc34ffd239ca907/platform-service/modules/audit-service/src/main/java/io/harness/audit/events/StreamingDestinationUpdateEvent.java#L44)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

No, since every event needs to extend the event class, we cannot have a base class.
</blockquote></details>

Base class can implement Event class and concrete classes can extend base class

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`clients/audit/src/main/java/io/harness/audit/client/api/impl/NoopAuditClientServiceImpl.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/42136#-NLdtOp99-w3pMv2fcKb:-NLdtOp99-w3pMv2fcKc:bnuwfrk) ([raw file](https://github.com/harness/harness-core/blob/31d4973369a0a67ab56844a0dc6bc72b936fee74/clients/audit/src/main/java/io/harness/audit/client/api/impl/NoopAuditClientServiceImpl.java#L34)):*
> ```Java
>   public AuditEventDTO getAuditEventDTO(
>       AuditEntry auditEntry, GlobalContext globalContext, AuthenticationInfoDTO authenticationInfoDTO) {
>     return null;
> ```

Should we return empty instead of NULL here, whats the usecase of NoopAuditClient?

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: 17 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/audit/src/main/java/io/harness/audit/client/api/impl/NoopAuditClientServiceImpl.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/42136#-NLdtOp99-w3pMv2fcKb:-NLdv0ziECHEA271M4vZ:b5d4528) ([raw file](https://github.com/harness/harness-core/blob/31d4973369a0a67ab56844a0dc6bc72b936fee74/clients/audit/src/main/java/io/harness/audit/client/api/impl/NoopAuditClientServiceImpl.java#L34)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Should we return empty instead of NULL here, whats the usecase of NoopAuditClient?
</blockquote></details>

Noop audit client gets used when the audits are not enabled, returning null should be fine for us. Will change it to empty in the next PR.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 7 of 17 files at r1, 3 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42136)* status: :shipit: complete! ✓

**Pull request merged**
