### PR TITLE
fix: [FFM-9672]: FF Pipeline RBAC Cherrypick

### PR DESCRIPTION
**Pull request by stephenmcconkey**
## Describe your changes
**Cherrypick**

This adds an environment identifier for the RBAC Check for All FF pipeline steps, it was only previous on toggle actions, it now is used for edit too.

**Test Cases Covered**
(All have been done for actions that require toggle and/or edit permissions, We have a pipeline where we try to edit and toggle a flag in both Prod and NonProd environments)

_At FF Access Control Level_
User has access to all environments - Passes on All environments (Prod and Non-Prod)
User has access to no environments - Passes on No environments (Prod and Non-Prod)
User has access to Non-Prod environments - Passes on Non-Prod, Fails on Prod
User has access to Prod environments - Passes on Prod, Fails on Non-Prod
User has access to a specific environment - Passes on specific environment, Fails on environment not specified

_At Account Level with Projects_
(This is setup so the user has all other permissions needed, where only environment is changing)
User has access to all environments - Passes on All environments (Prod and Non-Prod)
User has access to no environments - Passes on No environments (Prod and Non-Prod)
User has access to Non-Prod environments - Passes on Non-Prod, Fails on Prod
User has access to Prod environments - Passes on Prod, Fails on Non-Prod
You cannot set specific environments at this level for FF Pipelines

(cherry picked from 98e192d7f92409196120ecf58f77bcc2ebab21ba)

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54392)

### CODE REVIEW

**Comment by stephenmcconkey** [comment]
trigger messagecheck

**Comment by stephenmcconkey** [comment]
trigger messagecheck

**Comment by stephenmcconkey** [comment]
trigger commonchecks

**Comment by davejohnston** [comment]
trigger commonchecks

**Comment by davejohnston** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54392)* status: :shipit: complete! ✓

**Comment by davejohnston** [comment]
trigger commonchecks

**Comment by stephenmcconkey** [comment]
trigger uts

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54392)* status: :shipit: complete! ✓

**Pull request merged**
