### PR TITLE
feat: [CDS-80751]: add Git DTOs for Infra entity

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. Add git params for Infrastructure Resource
2. Added gitX params to Infra Response DTO 
3. Moved some of the method for old git sync to the interface to avoid unnecessary implementation. Marked them as deprecated as well. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts, messagecheck

**Review by adivishy1 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 422 at r1](https://reviewable.io/reviews/harness/harness-core/53685#-NfuIA-G5oqyduVCB5n-:-NfuIA-H393blEd1sjmB:b7nse8u) ([raw file](https://github.com/harness/harness-core/blob/b35dbb0ce98c7f02e81ffb32c629569ce9c9a4da/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L422)):*
> ```Java
>       @QueryParam("serviceRefs") List<String> serviceRefs,
>       @Parameter(description = "Specifies the repo name of the entity", hidden = true) @QueryParam(
>           "repoName") String repoName) {
> ```

As repo will be a filterParam, wont it be better if we create an object so that in future we can add all the filter params there?

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
> > Reviewed 5 of 5 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)_ status: 5 file(s) to review. 1 of 2 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 422 at r1](https://reviewable.io/reviews/harness/harness-core/53685#-NfuIA-G5oqyduVCB5n-:-NfuIA-H393blEd1sjmB:b7nse8u) ([raw file](https://github.com/harness/harness-core/blob/b35dbb0ce98c7f02e81ffb32c629569ce9c9a4da/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L422)):_
> 
> > ```java
> >       @QueryParam("serviceRefs") List<String> serviceRefs,
> >       @Parameter(description = "Specifies the repo name of the entity", hidden = true) @QueryParam(
> >           "repoName") String repoName) {
> > ```
> 
> As repo will be a filterParam, wont it be better if we create an object so that in future we can add all the filter params there?

@adivishy1 Since this is a GET call, we can't add body to it. We can create a single java pojo as a @beanparam but that would be just be a readability improvement at Resource layer. We can revisit it afterwards.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Review by rafaelmart1ns — DISMISSED** [review]

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by hingerabhinav** [comment]
trigger ut0

**Comment by adivishy1** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 422 at r1](https://reviewable.io/reviews/harness/harness-core/53685#-NfuIA-G5oqyduVCB5n-:-Nfy6rwMCAfT8Md_AMjX:b-tn0f53) ([raw file](https://github.com/harness/harness-core/blob/08fddb0aea58279c9d5e8a1aef6534e92c5eaab8/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L422)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@adivishy1 Since this is a GET call, we can't add body to it. We can create a single java pojo as a @beanparam but that would be just be a readability improvement at Resource layer. We can revisit it afterwards.  
</blockquote></details>

fair point

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger review

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53685)* status: :shipit: complete! ✓

**Pull request merged**
