### PR TITLE
feat: [CDS-42270]: Configure retention policies for CD TSDB tables

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37418)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37418)

**Comment by vikyathharekal** [comment]
trigger ti1, ti2

**Comment by vikyathharekal** [comment]
trigger ti3, ti4

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 4 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37418)* status: 19 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 463 at r1](https://reviewable.io/reviews/harness/harness-core/37418#-NBunXk6B06fPh-cTkVw:-NBunXk7AX312iirf7gB:bj7r7xg) ([raw file](https://github.com/harness/harness-core/blob/d30bd166772a12c82270a606e94adde6c9a1588a/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L463)):*
> ```Java
>   @Provides
>   @Singleton
>   public CDRetentionPeriodNG cdRetentionPeriod() {
> ```

I dont think we need to create a new Java Object here. We can create a provider which gives a named string.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37418)* status: 19 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 463 at r1](https://reviewable.io/reviews/harness/harness-core/37418#-NBunXk6B06fPh-cTkVw:-NBvPXvNCWKxrbkV6cUd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d30bd166772a12c82270a606e94adde6c9a1588a/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L463)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

I dont think we need to create a new Java Object here. We can create a provider which gives a named string.
</blockquote></details>

Done.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 10 of 23 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37418)* status: :shipit: complete! ✓

**Pull request merged**
