### PR TITLE
fix: [PL-31572]: Redis Lock release issue for iterators and batch size config

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR does the following -

1. Fixes the Redis Lock release issue - While releasing the Redis Lock it is observed that there is an unchecked exception being thrown by redisson which causes the thread to die abruptly without any stack trace. Adding the Redis unlock function in a try-catch block fixes this issue.

2. Configure the Redis batch size through iterator config rather than having a fixed value.
3. Moves away from using a single executor service and relying on `scheduleAtFixedRate`. Instead introduces a new Main executor service which has one thread that carries out the main processing of acquiring Redis lock, fetching and updating the Mongo docs and submitting the docs to another worker executor service. This makes it simpler to understand and separates the responsibility of fetching the docs from Mongo and processing those docs in 2 separate thread pools.

I have tested this locally and in the Pre-QA env. Below test cases validated -

1. Redis mode iterator running for ArtifactCollection iterator in 2 manager-iterator pods and both processing ~40 docs / secs for more than 1 hour. The metrics for this can be seen [here](https://console.cloud.google.com/monitoring/metrics-explorer?project=qa-setup&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22custom.googleapis.com%2Fopencensus%2Fiterator_working_on_entity%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metric.label.%5C%22iteratorName%5C%22%3D%5C%22ArtifactCollection%5C%22%20metric.label.%5C%22environment%5C%22%3D%5C%22stress%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_RATE%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22alignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%22resource.label.%5C%22pod_name%5C%22%22%5D%7D,%7B%22perSeriesAligner%22:%22ALIGN_NONE%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22alignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%5D%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221h%22%7D%7D).
2. Batch size being set to default value of 2 * threadPoolSize if the `redisBatchSize` parameter is not configured.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44024)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44024)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44024#-NORHwZ07OpWaSedXAVr:-NORHwZ07OpWaSedXAVs:bj3gr7r) ([raw file](https://github.com/harness/harness-core/blob/6555c7e643ee8b1b84dd8210073de93dbb0db29e/960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java#L36)):*
> ```Java
>     } catch (Throwable t) {
>       log.error("Received an exception while releasing the Redis lock {} ", t.getStackTrace());
>       throw new RuntimeException(t);
> ```

why throwing again?


One place should be enough - probably in the iterator code, not here
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 312 at r1](https://reviewable.io/reviews/harness/harness-core/44024#-NORHzsSDG_Yssqhck5q:-NORHzsSDG_Yssqhck5r:b-89sewa) ([raw file](https://github.com/harness/harness-core/blob/6555c7e643ee8b1b84dd8210073de93dbb0db29e/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L312)):*
> ```Java
>       // Check if iterators should run or not.
>       if (!shouldProcess()) {
>         sleep(ofSeconds(1));
> ```

Why 1 second? Should this not be based on the input parameters?
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 342 at r1](https://reviewable.io/reviews/harness/harness-core/44024#-NORJbT8CG3WuDbLBzS4:-NORJbT8CG3WuDbLBzS5:b-mziy1q) ([raw file](https://github.com/harness/harness-core/blob/6555c7e643ee8b1b84dd8210073de93dbb0db29e/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L342)):*
> ```Java
>         iteratorMetricsService.recordIteratorMetrics(iteratorName, ITERATOR_ERROR);
>         Thread.currentThread().interrupt();
>         sleep(ofSeconds(1));
> ```

What is this sleep for?

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44024)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 312 at r1](https://reviewable.io/reviews/harness/harness-core/44024#-NORHzsSDG_Yssqhck5q:-NORn1PQCUGJV_9TY5aH:b-6ds0tr) ([raw file](https://github.com/harness/harness-core/blob/6555c7e643ee8b1b84dd8210073de93dbb0db29e/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L312)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Why 1 second? Should this not be based on the input parameters?
</blockquote></details>

This one is related to Shutdown and Maintenance checks. So that's why this is a constant of 1 sec because the App is usually in this state only during startup and we want to get to processing asap. The sleeps based on input params is for when there are no more docs available to process. 
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 342 at r1](https://reviewable.io/reviews/harness/harness-core/44024#-NORJbT8CG3WuDbLBzS4:-NORnaBt17jV1SXKNApi:bu7nl7h) ([raw file](https://github.com/harness/harness-core/blob/6555c7e643ee8b1b84dd8210073de93dbb0db29e/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L342)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

What is this sleep for?
</blockquote></details>

This semaphore acquisition is no longer needed as only one thread is going to run this method now. So I will remove this part of the code.
___
*[`960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44024#-NORHwZ07OpWaSedXAVr:-NORwUeN4dDeAV7nL6CJ:b-iukfh3) ([raw file](https://github.com/harness/harness-core/blob/6555c7e643ee8b1b84dd8210073de93dbb0db29e/960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java#L36)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

why throwing again?


One place should be enough - probably in the iterator code, not here
</blockquote></details>

Yes, I will remove it from the internal Redis helper API.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44024)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44024)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44024)* status: :shipit: complete! ✓

**Pull request merged**
