### PR TITLE
[feat]: [PIE-8924]: Add when condition for rollback steps in rollback mode execution

### PR DESCRIPTION
**Pull request by namanvermah**
If the user hasn't explicitly added any when condition for a rollback step, we add a condition ourselves that it should run only on stage failure. However, for rollback mode execution, we don't want to base the when condition for rollback steps on stage failure/success. Hence, if the user hasn't explicitly added any when condition for a rollback step, adding the ALWAYS instead of STAGE_FAILURE clause to the when condition in rollback mode is required.

**Impact**: No impact until rollback mode executions are made live.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45113)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45113)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45113#-:-NQZIvRi66vAwkNRI5fe:bnfp4nl)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45113)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45113)* status: :shipit: complete! ✓

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45113#-:-NQj92ElDCVRjLJej5hI:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45113)* status: :shipit: complete! ✓

**Pull request merged**
