### PR TITLE
feat: [PL-32119]: Extend Redis Batch mode support for Loop iterators

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR extends the Redis Batch mode for the existing iterators with Irregular scheduling mode.

Tested it in local environment to update a iterator with Irregular scheduling.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45505)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45505)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/45505#-NRbGlMH2m3jYGT5bKbe:-NRjY2cKEliTUozN5GOy:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/24a1a9d4b48c7dfe2b4bbe772dd58f99e04f119b/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L119)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add notifyAll here as well
</blockquote></details>

Done

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45505)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45505)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
Discussed with @abhinavmittal-harness  and @sourabh-awashti on how we can use the Redis Batch Mode with Regular scheduling for Deployment Freeze Iterator.

The high level design will be as below -
* Replace list of nextIterations in the DTO to a single integer value for nextIteration. This filed will be set based on the configured targetInterval.
* Introduce a new list of nextNotificationIntervals field which will replace the existing list of nextIterations to determine when to send a Deployment Freeze Notification.
* For ex- if targetInterval is 1-day and notification intervals are at irregular intervals like Apr-10, Apr-24, May-1 etc. The doc will be picked up every single day and the Application handle logic will check its nextNotificationIntervals to determine whether to send the notification currently or not. Every time a notification is send the handle method will update the nextNotificationIntervals by recalculating it and making a write to Mongo.

With the above way of handling this iterator there should not be a need to handle irregular scheduling in the iterator framework. Thus, closing this PR. Can re-opened if this support is needed in the future for other use cases.

**Pull request closed without merging**
