### PR TITLE
feat: [PIE-6494]: Add service level configuration support for gitx caching durations

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41420)

### CODE REVIEW

**Review by adivishy1 — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41420)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitFileCacheServiceImpl.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/41420#-NJ4x1Uw92dSb-bYOuwx:-NJ4x1Uw92dSb-bYOuwy:bpwq6xd) ([raw file](https://github.com/harness/harness-core/blob/e615bc26d73e264c2c6eb55da4e1826f7302d19a/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitFileCacheServiceImpl.java#L36)):*
> ```Java
> public class GitFileCacheServiceImpl implements GitFileCacheService {
>   @Inject GitFileCacheRepository gitFileCacheRepository;
>   @Inject GitFileCacheTTLHelper gitFileCacheTTLHelper;
> ```

Do we need this here? I dont think this is used in this class.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitFileCacheServiceImpl.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/41420#-NJ4x1Uw92dSb-bYOuwx:-NJ53l-o3mro7nQ0Awbk:b-5vwvb8) ([raw file](https://github.com/harness/harness-core/blob/e615bc26d73e264c2c6eb55da4e1826f7302d19a/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitFileCacheServiceImpl.java#L36)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Do we need this here? I dont think this is used in this class.
</blockquote></details>

its being used

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by adivishy1 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41420)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 27 of 28 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41420)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 27 of 28 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41420)* status: :shipit: complete! ✓

**Review by adivishy1 — APPROVED** [review]
> Reviewed 9 of 28 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41420)* status: :shipit: complete! ✓

**Pull request merged**
