### PR TITLE
[fix]: [PL-28014]: Ignore DuplicateKeyException of Default User Group create in event handler.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
Ignore DuplicateKeyException of Default User Group create in event handler.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37228)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37228)

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37228)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/UserGroupEntityCRUDStreamListener.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/37228#-NBIqa7M3rkFyhviNTbK:-NBIqa7M3rkFyhviNTbL:b-euggby) ([raw file](https://github.com/harness/harness-core/blob/ddef60048c87fb0372a6f147f51d5a952dfeebf9/120-ng-manager/src/main/java/io/harness/ng/core/event/UserGroupEntityCRUDStreamListener.java#L156)):*
> ```Java
>     } catch (DuplicateFieldException ex) {
>       // Safe to assume Default User Group is created.
>       log.info(String.format("Safe to assume Default User Group is created at scope %s", scope));
> ```

Can't we handle duplicate exception within create method to simplify API usage?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37228)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/UserGroupEntityCRUDStreamListener.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/37228#-NBIqa7M3rkFyhviNTbK:-NBIrPaODDYNXUlIUZ7I:b-mtj1pb) ([raw file](https://github.com/harness/harness-core/blob/ddef60048c87fb0372a6f147f51d5a952dfeebf9/120-ng-manager/src/main/java/io/harness/ng/core/event/UserGroupEntityCRUDStreamListener.java#L156)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can't we handle duplicate exception within create method to simplify API usage?
</blockquote></details>

I think same endpoint can be used by different consumers and depending on usecase we may want to either throw error or handle gracefully.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37228)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/UserGroupEntityCRUDStreamListener.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/37228#-NBIqa7M3rkFyhviNTbK:-NBItBtlCAWQfXiQQhnj:bekdmaq) ([raw file](https://github.com/harness/harness-core/blob/ddef60048c87fb0372a6f147f51d5a952dfeebf9/120-ng-manager/src/main/java/io/harness/ng/core/event/UserGroupEntityCRUDStreamListener.java#L156)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think same endpoint can be used by different consumers and depending on usecase we may want to either throw error or handle gracefully.
</blockquote></details>

sure, let me make the change you suggested.
I think Default UG create would not be exposed to customers to we can swallow the DuplicateKeyException in create.

**Pull request closed without merging**
