### PR TITLE
fix: [PL-27080]: Sanitize user group during CRUD 

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35776)

### CODE REVIEW

**Comment by gupta-utkarsh** [comment]
trigger ti1

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupBackgroundMigrationDetails.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/35776#-N83oeH4A0zf2zLPgZeg:-N83oeH4A0zf2zLPgZeh:bjjhgj4) ([raw file](https://github.com/harness/harness-core/blob/527a8a7402cc0a54e0bca5d50024592b8c9146fb/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupBackgroundMigrationDetails.java#L39)):*
> ```Java
>         .add(Pair.of(2, NoOpMigration.class))
>         .add(Pair.of(3, NoOpMigration.class))
>         .add(Pair.of(4, UserGroupSanitizationMigration.class))
> ```

Shouldn't this be at 5?
Because we already merging at 4 in release going on Monday

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35776)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35776)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupBackgroundMigrationDetails.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/35776#-N83oeH4A0zf2zLPgZeg:-N83r8on6qDH-K-UoVU2:b-s8402e) ([raw file](https://github.com/harness/harness-core/blob/527a8a7402cc0a54e0bca5d50024592b8c9146fb/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupBackgroundMigrationDetails.java#L39)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Shouldn't this be at 5?
Because we already merging at 4 in release going on Monday
</blockquote></details>

No, because we are also merging the sanitization of user groups on CRUD at the same time. The migration won't be required after this.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35776)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35776)* status: :shipit: complete! ✓

**Pull request merged**
