### PR TITLE
[feat]: [SRM-11369]: adding support for open spec 3

### PR DESCRIPTION
**Pull request by deepak-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36916)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Vulnerability 4 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36916)

**Comment by deepak-harness** [comment]
SRM-11369

**Comment by deepak-harness** [comment]
trigger messagecheck

**Comment by deepak-harness** [comment]
trigger ti4

**Comment by deepak-harness** [comment]
trigger ti3

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36916)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/GenerateOpenApiSpecCommand.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzRXqr6JANTojD7m0J:-NAzRXqr6JANTojD7m0K:b-9xrrky) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/main/java/io/harness/cvng/GenerateOpenApiSpecCommand.java#L31)):*
> ```Java
> 
> @Slf4j
> public class GenerateOpenApiSpecCommand extends ConfiguredCommand<VerificationConfiguration> {
> ```

is this mostly boiler plate code ? Can this be moved to a common library across modules and reused ?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationConfiguration.java` line 169 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzQPn2DrmeXOtmaugS:-NAzQPn2DrmeXOtmaugT:b7udhnm) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationConfiguration.java#L169)):*
> ```Java
>     OpenAPI oas = new OpenAPI();
>     Info info = new Info()
>                     .title("Verification Service API Reference")
> ```

Nit: I think we can start calling this SRM service to the public. They do not know anything about verification svc, no ?
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzQpTZ7BfqsbfTpXcn:-NAzQpTZ7BfqsbfTpXco:b34upc8) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java#L75)):*
> ```Java
> 
>   @Test
>   @Owner(developers = ASHISHSANODIA)
> ```

change owner
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java` line 89 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzQngQ8ejzB2gHhyZu:-NAzQngQ8ejzB2gHhyZv:b34upc8) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java#L89)):*
> ```Java
> 
>   @Test
>   @Owner(developers = ASHISHSANODIA)
> ```

change owner

**Review by deepak-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36916)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/GenerateOpenApiSpecCommand.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzRXqr6JANTojD7m0J:-NB6M4yJ7pSHOaPmadjD:b1gv3gu) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/main/java/io/harness/cvng/GenerateOpenApiSpecCommand.java#L31)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

is this mostly boiler plate code ? Can this be moved to a common library across modules and reused ?
</blockquote></details>

Let me take this up with the platform team who own the api standardisation code base.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationConfiguration.java` line 169 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzQPn2DrmeXOtmaugS:-NB6MM_C8bF2nbc_BboF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationConfiguration.java#L169)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Nit: I think we can start calling this SRM service to the public. They do not know anything about verification svc, no ?
</blockquote></details>

done
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzQpTZ7BfqsbfTpXcn:-NB6MNoUDGqZSOnFsZgt:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java#L75)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

change owner
</blockquote></details>

done
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java` line 89 at r4](https://reviewable.io/reviews/harness/harness-core/36916#-NAzQngQ8ejzB2gHhyZu:-NB6MOnZ1V7gfiPf0tv5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/428a5fc6d17a7f7b770c47f55ee8c41a97058fe2/300-cv-nextgen/src/test/java/io/harness/cvng/GenerateOpenApiSpecCommandTest.java#L89)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

change owner
</blockquote></details>

done

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36916)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions.

**Pull request merged**
