### PR TITLE
fix: [DEL-4288]: Revamp NG secret manager

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34246)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java` line 592 at r2](https://reviewable.io/reviews/harness/harness-core/34246#-N4f0RdC9EEiY17bSCpj:-N4f0RdC9EEiY17bSCpk:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/aa5700fc64c73c4680328d6d4848dc1831c25a7a/400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java#L592)):*
> ```Java
>     kryo.register(RancherStateExecutionData.class, 50009);
>     kryo.register(UserGroupEntityReference.class, 50010);
>     kryo.register(EncryptedDataDetails.class, 50013);
> ```

why is this needed?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/expression/EncryptedDataDetails.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/34246#-N4f18Vn11xvaPUcJIUM:-N4f18Vn11xvaPUcJIUN:b-tz6ouf) ([raw file](https://github.com/harness/harness-core/blob/aa5700fc64c73c4680328d6d4848dc1831c25a7a/400-rest/src/main/java/software/wings/expression/EncryptedDataDetails.java#L18)):*
> ```Java
> @Getter
> @Builder
> public class EncryptedDataDetails {
> ```

why is this needed? why can't we store the list directly in the cache?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34246)* status: 0 of 1 approvals obtained.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34246)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java` line 592 at r2](https://reviewable.io/reviews/harness/harness-core/34246#-N4f0RdC9EEiY17bSCpj:-N4h6dmz6uSJc0LdO-1p:b-hqar7d) ([raw file](https://github.com/harness/harness-core/blob/aa5700fc64c73c4680328d6d4848dc1831c25a7a/400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java#L592)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

SecretCache is based on Redis, hence we need to serialize/deserialize value during insert/lookup of cache.
___
*[`400-rest/src/main/java/software/wings/expression/EncryptedDataDetails.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/34246#-N4f18Vn11xvaPUcJIUM:-N4h6tMd45rG6BmLKKPx:b-wg7nzw) ([raw file](https://github.com/harness/harness-core/blob/aa5700fc64c73c4680328d6d4848dc1831c25a7a/400-rest/src/main/java/software/wings/expression/EncryptedDataDetails.java#L18)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why is this needed? why can't we store the list directly in the cache?
</blockquote></details>

During cache initialisation, we need to mention exact type of key and value cache gonna hold. We cannot mention List<T> there, hence that need to be either Object type or any class object.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34246)* status: :shipit: complete! ✓

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34246)* status: :shipit: complete! ✓

**Pull request merged**
