### PR TITLE
[fix]: [CDS-76632]: adding support for expressions for command flag option in k8s

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes

When an expression is used for field command flags on K8s steps it was not getting resolved. 
Logic that does the resolution in case of an expression has been introduced thus resolving the issue.

Tested cases:
- [x] fixed value
- [x] runtime value
- [x] expression value
- [x] nested expression value (like customer use case)

Changes only influence K8s steps when using k8s manifest.
In case of using Helm Manifest and providing command flag via manifest config the expression is already evaluated/resolved when it reaches the step class code.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51466)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger checkstylecodeformat, messagecheck, pmd, codebasehash, uts

**Review by alebuh — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51466)* status: 8 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 1009 at r1](https://reviewable.io/reviews/harness/harness-core/51466#-NbJqgt92dSDPv49rPpz:-NbJqgt92dSDPv49rPq-:b-halft7) ([raw file](https://github.com/harness/harness-core/blob/dd433fc4a67cfec4f2ddde8974897d9abe495093/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L1009)):*
> ```Java
>         commandsValueMap.put(commandFlag.getCommandType().getSubCommandType(), resolvedExpression);
>       } else {
>         commandsValueMap.put(commandFlag.getCommandType().getSubCommandType(), commandFlag.getFlag().getValue());
> ```

nit: we can move this outside the if and us ternary if
String flag = commandFlag.getFlag().isExpression() ? cdExpressionResolver.renderExpression(ambiance, commandFlag.getFlag().getExpressionValue()) : cdExpressionResolver.renderExpression(ambiance, commandFlag.getFlag().getExpressionValue());
commandsValueMap.put(commandFlag.getCommandType().getSubCommandType(), flag);

**Comment by markoharness** [comment]
trigger checkstylecodeformat, messagecheck, pmd, codebasehash, uts

**Comment by markoharness** [comment]
trigger checkstylecodeformat, messagecheck, pmd, codebasehash, uts

**Review by alebuh — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51466)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]

**Comment by markoharness** [comment]
trigger review

**Pull request merged**
