### PR TITLE
feat: [CDS-47029]: add Asg canary deploy

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41722)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java` line 258 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd0ZPR9Ty_Qtt_qLP2:-NJd0ZPR9Ty_Qtt_qLP3:bisx46m) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java#L258)):*
> ```Java
> 
>   public <T> T parseJson(String json, Class<T> clazz) {
>     ObjectMapper mapper = getObjectMapper();
> ```

Shall we create a bean for ObjectMapper and inject it here? It is thread-safe too.

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java` line 235 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd1TY569KXTSdi8ftg:-NJd1TY569KXTSdi8fth:b4in7e9) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java#L235)):*
> ```Java
>       HTimeLimiter.callInterruptible(timeLimiter, Duration.ofMinutes(steadyStateTimeOutInMinutes), () -> {
>         while (!predicate.test(asgName)) {
>           info("Waiting for operation `%s` to complete", operationName);
> ```

can we show stats on how many instances are ready. Like `5/11` instances are healthy?

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd1wSxBRO1CNz1qGqH:-NJd1wSxBRO1CNz1qGqI:b-t7zaed) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java#L64)):*
> ```Java
> @Slf4j
> @OwnedBy(CDP)
> public class AsgManager {
> ```

Shall we move this to API layer as this is independent of Delegate tasks and can be shared. `960-api-service`

**Comment by vitsafronovici** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41722)* status: 20 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCanaryDeployResult.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd0ANU5sUm_gbtOwcI:-NJeCaoWEBxSwZ-YHG6F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgCanaryDeployResult.java#L21)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

`canaryAsgName` do we need this field now?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd1wSxBRO1CNz1qGqH:-NJeCbjd55YuFh8zkMSu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java#L64)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Shall we move this to API layer as this is independent of Delegate tasks and can be shared. `960-api-service`
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java` line 235 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd1TY569KXTSdi8ftg:-NJeCh6O6PjRFHXArH0a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java#L235)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

can we show stats on how many instances are ready. Like `5/11` instances are healthy?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java` line 258 at r1](https://reviewable.io/reviews/harness/harness-core/41722#-NJd0ZPR9Ty_Qtt_qLP2:-NJeCktZAkbn2Q8XEeYo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa9a90e909d35d85e72f99d75e896aeedfc0868d/930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgManager.java#L258)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Shall we create a bean for ObjectMapper and inject it here? It is thread-safe too.
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgManager.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/41722#-NJeJkFf4eCCh-KbEtYZ:-NJeJkFh5Jr-KDwsDE5A:bxhsic5) ([raw file](https://github.com/harness/harness-core/blob/846dfa7391983e7939cdd5a538c42f49c7b1314e/960-api-services/src/main/java/io/harness/aws/asg/AsgManager.java#L72)):*
> ```Java
>   private static final String INSTANCE_STATUS_IN_SERVICE = "InService";
> 
>   private final AmazonEC2Client ec2Client;
> ```

@vitsafronovici - we can't use them as a variable here as these are closable entities and will lead to memory leak. We'll need to redesign this class. If you plan to add manager layer in the middle, you can refer to io.harness.pcf.CfDeploymentManager

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41722)* status: 20 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgManager.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/41722#-NJeJkFf4eCCh-KbEtYZ:-NJfB7O4BrKnyqP42CIU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/846dfa7391983e7939cdd5a538c42f49c7b1314e/960-api-services/src/main/java/io/harness/aws/asg/AsgManager.java#L72)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

@vitsafronovici - we can't use them as a variable here as these are closable entities and will lead to memory leak. We'll need to redesign this class. If you plan to add manager layer in the middle, you can refer to io.harness.pcf.CfDeploymentManager
</blockquote></details>

Done.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 16 of 19 files at r1, 4 of 8 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41722)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by lovish1999 — COMMENTED** [review]
LGTM

**Review by lovish1999 — COMMENTED** [review]
> Reviewed 12 of 19 files at r1, 4 of 8 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41722)* status: 1 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41722)* status: :shipit: complete! ✓

**Pull request merged**
