### PR TITLE
feat: [CDS-42877]: resolve template refs in Service step V3

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger ti0

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 443 at r2](https://reviewable.io/reviews/harness/harness-core/38849#-NEnanYG-v8rJwPHv_sC:-NEnanYG-v8rJwPHv_sD:b-dr9z5e) ([raw file](https://github.com/harness/harness-core/blob/7196aace151f13d045b12ee91eb906f28c2204ed/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L443)):*
> ```Java
> 
>   public TemplateMergeResponseDTO resolveTemplateRefsInService(String accountId, String orgId, String projectId,
>       String yaml, boolean checkForTemplateAccess, boolean getMergedTemplateWithTemplateReferences) {
> ```

This boolean can be removed from here



_Code quote:_
```Java
getMergedTemplateWithTemplateReferences
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 443 at r2](https://reviewable.io/reviews/harness/harness-core/38849#-NEnaqd-BrOPwopgbVJW:-NEnaqd-BrOPwopgbVJX:b-n5oyam) ([raw file](https://github.com/harness/harness-core/blob/7196aace151f13d045b12ee91eb906f28c2204ed/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L443)):*
> ```Java
> 
>   public TemplateMergeResponseDTO resolveTemplateRefsInService(String accountId, String orgId, String projectId,
>       String yaml, boolean checkForTemplateAccess, boolean getMergedTemplateWithTemplateReferences) {
> ```

If template access permissions needs to be check, please pass this boolean as true.



_Code quote:_
```Java
checkForTemplateAccess
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 357 at r3](https://reviewable.io/reviews/harness/harness-core/38849#-NEoAQ8X4SVXVI1U6KoC:-NEoAQ8X4SVXVI1U6KoD:b-aq5dyi) ([raw file](https://github.com/harness/harness-core/blob/7c3574624c4d7c5071410335615db28211dc1f6f/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L357)):*
> ```Java
>     }
>     // resolve template refs in service
>     TemplateMergeResponseDTO templateMergeResponseDTO = resolveTemplateRefsInService(serviceEntity.getAccountId(),
> ```

I think we can just return updated service yaml instead of TemplateMergeResponseDTO
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 441 at r3](https://reviewable.io/reviews/harness/harness-core/38849#-NEoBAEcD3eu0SAdgIP1:-NEoBAEcD3eu0SAdgIP2:b-jhslat) ([raw file](https://github.com/harness/harness-core/blob/7c3574624c4d7c5071410335615db28211dc1f6f/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L441)):*
> ```Java
>   }
> 
>   public TemplateMergeResponseDTO resolveTemplateRefsInService(
> ```

maybe better to call resolveArtifactTemplates..

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 443 at r2](https://reviewable.io/reviews/harness/harness-core/38849#-NEnanYG-v8rJwPHv_sC:-NEoBhisDXX0gkxwedwr:b2ngthx) ([raw file](https://github.com/harness/harness-core/blob/7196aace151f13d045b12ee91eb906f28c2204ed/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L443)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This boolean can be removed from here
</blockquote></details>

+1

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 441 at r4](https://reviewable.io/reviews/harness/harness-core/38849#-NEpJhZTBXze9_WjWJ5A:-NEpJhZTBXze9_WjWJ5B:b-8mgd84) ([raw file](https://github.com/harness/harness-core/blob/24c92267f11e4cebcd416a270e7a09cdde734905/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L441)):*
> ```Java
> 
>   public String resolveTemplateRefsInService(
>       String accountId, String orgId, String projectId, String yaml, boolean checkForTemplateAccess) {
> ```

do we need this boolean `checkForAccess` ?

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 561 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFKBz9VEFrhLZlSHHKm:-NFKBz9VEFrhLZlSHHKn:b-n77dgy) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L561)):*
> ```Java
>     if (serviceDefField == null) {
>       throw new InvalidRequestException(
>           "Invalid Service being referred as serviceDefinition section is not there in DeploymentStage");
> ```

looks like this says "serviceDefinition is not in DeploymentStage"
whereas it should say "serviceDefinition is not in Service"

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 588 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFKCUBiBWHDoKXObI2f:-NFKCUBiBWHDoKXObI2g:bzgkoad) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L588)):*
> ```Java
>     String primaryArtifactRefValue = primaryArtifactRef.getNode().asText();
> 
>     if (artifactSourcesField != null && artifactSourcesField.getNode().isArray() && primaryArtifactRefValue != null) {
> ```

what happens if primaryArtifactRef is empty string ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/test/resources/service-with-artifact-template-ref.yaml` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFKD2jd4Gbww1xnzAM_:-NFKD2je6cVcLbDsDqYk:b5st9wz) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/test/resources/service-with-artifact-template-ref.yaml#L18)):*
> ```YAML
>                   type: DockerRegistry
>                   spec:
>                     tag: latest
> ```

can we add test with multiple template refs/different versions. Also with mix of template refs, regular artifact sources, sidecars

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 757 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFJ8Uei7vEub1SmcKvR:-NFJ8Uei7vEub1SmcKvS:b616ob6) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L757)):*
> ```Java
>       return ((ServiceSweepingOutput) resolveOptional.getOutput()).getFinalServiceYaml();
>     }
>     return StringUtils.EMPTY;
> ```

I think we should throw exception here if not found

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 757 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFJ8Uei7vEub1SmcKvR:-NFT0aO16KG59Hj4q3Ld:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L757)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think we should throw exception here if not found
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 561 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFKBz9VEFrhLZlSHHKm:-NFT0cpW089utAZAKz4Q:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L561)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

looks like this says "serviceDefinition is not in DeploymentStage"
whereas it should say "serviceDefinition is not in Service"
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java` line 588 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFKCUBiBWHDoKXObI2f:-NFT0ubi4foG-7J-nTGh:byh0oir) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactStepHelper.java#L588)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what happens if primaryArtifactRef is empty string ?
</blockquote></details>

added a check for this. 
___
*[`125-cd-nextgen/src/test/resources/service-with-artifact-template-ref.yaml` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/38849#-NFKD2jd4Gbww1xnzAM_:-NFT0zvJ8Ug_qOLJ5ZFD:b5ysr4v) ([raw file](https://github.com/harness/harness-core/blob/b1e64329252a7d9b2f8e7bacf318a39388c1dbb4/125-cd-nextgen/src/test/resources/service-with-artifact-template-ref.yaml#L18)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we add test with multiple template refs/different versions. Also with mix of template refs, regular artifact sources, sidecars
</blockquote></details>

resolving multiple template refs falls within the purview of TS. We're mocking these calls. I have added tests for multiple sources, sidecars etc.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 755 at r7](https://reviewable.io/reviews/harness/harness-core/38849#-NFT2SmoBGfmoW5bupEc:-NFT2SmoBGfmoW5bupEd:bgbpei8) ([raw file](https://github.com/harness/harness-core/blob/bc54d8eb3657a7427f42e7c60df51de51a2923ff/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L755)):*
> ```Java
>         ambiance, RefObjectUtils.getOutcomeRefObject(ServiceStepV3.SERVICE_SWEEPING_OUTPUT));
>     if (!resolveOptional.isFound()) {
>       throw new InvalidRequestException("Cannot find merged service in sweeping output");
> ```

better to say "cannot find service. Make sure this is running in a CD stage with service configured".

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 1 change requests. 2. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 1 change requests. 2. unresolved discussions.

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 1 change requests. 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 146 at r8](https://reviewable.io/reviews/harness/harness-core/38849#-NFTN4W9Az4d53O8MzHV:-NFTN4W9Az4d53O8MzHW:b-jll5iv) ([raw file](https://github.com/harness/harness-core/blob/25d23df1ed7ec746603794f2a631388bfe85b8f3/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L146)):*
> ```Java
>       mergedServiceYaml =
>           resolveArtifactSourceTemplateRefs(accountId, orgIdentifier, projectIdentifier, processedServiceYaml);
>       ngServiceConfig = YamlUtils.read(mergedServiceYaml, NGServiceConfig.class);
> ```

@yogesh-chauhan We would need to set primaryArtifact true and identifier as "primary" inside primary.spec after this, right?

**Comment by hingerabhinav** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by hingerabhinav** [comment]
trigger ti0

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java` line 146 at r8](https://reviewable.io/reviews/harness/harness-core/38849#-NFTN4W9Az4d53O8MzHV:-NFw8RV90py98Kc7cJGG:b-j2ipi8) ([raw file](https://github.com/harness/harness-core/blob/25d23df1ed7ec746603794f2a631388bfe85b8f3/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/steps/ArtifactsStepV2.java#L146)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

@yogesh-chauhan We would need to set primaryArtifact true and identifier as "primary" inside primary.spec after this, right?
</blockquote></details>

this happens in the constructor itself when identifier is removed

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 1 change requests. 2. unresolved discussions.

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 4 of 6 files at r7, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: 1 change requests. 2. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38849)* status: :shipit: complete! ✓

**Pull request merged**
