### PR TITLE
[fix]: [CDS-82502] : fix ServiceOverrideUtilityFacadeTest

### PR DESCRIPTION
**Pull request by lovish1999**
Reverts harness/harness-core#54586

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54627)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54627)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger gitLeaks

**Comment by lovish1999** [comment]
trigger gitLeaks

**Comment by lovish1999** [comment]
trigger gitleaks

**Review by naman-goenka — APPROVED** [review]

**Pull request merged**
