### PR TITLE
[feat]: [CDS-69780]: Adding a functor under strategyFunctor to return strategy currentStatus

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

 Adding expression support to get strategy node's currentStatus during execution.
Below are the expressions that will be supported 
```
- <+strategy.currentStatus> : Get the currentStatus of strategy node with maximum depth.
- <+strategy.node.strategyNodeIdentifier.currentStatus> :  Get the currentStatus of strategy node having identifier as strategyNodeIdentifier.
- <+strategy.node.get("strategyNodeIdentifier").currentStatus> :  Get the currentStatus of strategy node having identifier as strategyNodeIdentifier.

```

Below are the changes: Added a new StrategyNodeFunctor of type LateBindingMap. That calculated the currentStatus of a strategy node based on identifier.
Registered the above functor in the Strategy functor so that expression starts with `<+strategy...>`
 strategy.currentStatus or strategy.node.strategyNodeIdentifier.currentStatus

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48178)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48178)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/48178#-NW69C_k579MWzj3evVi:-NW69C_k579MWzj3evVj:b4apad0) ([raw file](https://github.com/harness/harness-core/blob/d90807fc74c7894ee15fa2577233ed551e2793c5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java#L42)):*
> ```Java
>         levelsWithStrategyMetadata, ambiance.getMetadata().getUseMatrixFieldName());
>     map.put("node", strategyNodeFunctor);
>     map.put(StrategyNodeFunctor.CURRENT_STATUS_KEY, strategyNodeFunctor.get(StrategyNodeFunctor.CURRENT_STATUS_KEY));
> ```

can we expose getCurrentStatus method in functor directly?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/48178#-NW69O0IDmoBPEKXvjcY:-NW69O0IDmoBPEKXvjcZ:b-rul9) ([raw file](https://github.com/harness/harness-core/blob/d90807fc74c7894ee15fa2577233ed551e2793c5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L70)):*
> ```Java
>       }
>     }
>     return strategyLevel;
> ```

if not strategy matched, should we return null?

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/48178#-NW69O0IDmoBPEKXvjcY:-NW6Fy79Eqi-FqG0J5CP:b-qlkts5) ([raw file](https://github.com/harness/harness-core/blob/d90807fc74c7894ee15fa2577233ed551e2793c5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if not strategy matched, should we return null?
</blockquote></details>

I think that is more correct. If user is giving the identifier then return only when there is a strategy node with that identifier. Else return null.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48178)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/48178#-NW69C_k579MWzj3evVi:-NW6Jmw6Cg_RoMD91rmp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d90807fc74c7894ee15fa2577233ed551e2793c5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyFunctor.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we expose getCurrentStatus method in functor directly?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/48178#-NW69O0IDmoBPEKXvjcY:-NW6JpcX4NzIv_xgbwlp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d90807fc74c7894ee15fa2577233ed551e2793c5/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L70)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think that is more correct. If user is giving the identifier then return only when there is a strategy node with that identifier. Else return null.
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48178)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/48178#-NW6dur91ubj_WBblN2G:-NW6eaAq0VfQhezewVX6:b-rwr4q6) ([raw file](https://github.com/harness/harness-core/blob/212cc3c77cdda82cb22ddaa42c16d57c86b6b12d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/StrategyNodeFunctor.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt this be using FunctorUtils.fetchCurrentStatus?
</blockquote></details>

fetchCurrentStatus is different in both in this functor and NodeExecutionMap. So we did not move to util.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/48178#-NW6d_uUAZEKtAStyHvI:-NW6ek1WDmuHTf0chzdL:b-dtun22) ([raw file](https://github.com/harness/harness-core/blob/212cc3c77cdda82cb22ddaa42c16d57c86b6b12d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java#L93)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt this be used only in fetchCurrentStatus and not at fetchFirst?
</blockquote></details>

We moved only fetchFirst to FunctorUtil and not currentStatus. Because currentStatus logic is not same as in StrategyNodeFUnctor we also need to find out the level with strategy. While here we already have the nodeExecution.
Also nodeExecutionCache will be needed so did not move to util.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48178)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 4 files at r2, 2 of 5 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48178)* status: :shipit: complete! ✓

**Pull request merged**
