### PR TITLE
feat: [PIE-9167]: Token Refresh Cron jobs for gitlab

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Written a cron job to refresh OAuth token for gitlab SCMs.

Tested locally.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)

### CODE REVIEW

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS586Rt1CBlr6cJtWF-:-NS586Rt1CBlr6cJtWF0:b-yyl5rl) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L79)):*
> ```Java
>     if (token.getScope() != Scope.ACCOUNT) {
>       orgIdentifier = null;
>       projectIdentifier = null;
> ```

they are already null why do you need to set it again?
___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS58ck_3zNPH46d4lcL:-NS58ck_3zNPH46d4lcM:b-gkpkfp) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L101)):*
> ```Java
>     Secret secret = Secret.fromDTO(secretDTOV2);
>     ngSecretCrudService.update(entity.getAccountIdentifier(), secret.getOrgIdentifier(), secret.getProjectIdentifier(),
>         secretDTOV2.getIdentifier(), secretDTOV2);
> ```

if its a Db write, you could add a logging here if write operation fails.
___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS58zhh4QXx9HHWoZT4:-NS58zhh4QXx9HHWoZT5:bemkbjh) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L144)):*
> ```Java
> 
>       updateSecretSecretValue(entity, tokenDTO, refreshTokenResponse.getAccessToken());
>       updateSecretSecretValue(entity, refreshTokenDTO, refreshTokenResponse.getRefreshToken());
> ```

Not clear if they both need to happen, if so you can wrap then under transaction.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS7RdgY2snVC9d2sI8I:-NS7RdgY2snVC9d2sI8J:bb4n944) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L105)):*
> ```Java
> 
>   @Override
>   public void handle(GitlabSCM entity) {
> ```

Lets move this method to the top. Its really a hassle in readability of the code wherein helper methods are on the top and the main one is down here.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 6 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS586Rt1CBlr6cJtWF-:-NS5cLBaC0aFGbfjD--9:b-tynvc4) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L79)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

they are already null why do you need to set it again?
</blockquote></details>

removing this block as scope of these tokens will always be account.
___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS7RdgY2snVC9d2sI8I:-NS9KNhw5CgtaC6MU5de:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L105)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets move this method to the top. Its really a hassle in readability of the code wherein helper methods are on the top and the main one is down here.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS7Rn0X7SryROpbXI8S:-NS9KOGK5MyxStYDjgRc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L106)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Use contexts to put account and user details into all logs. Similar to AccountLogContext.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS58zhh4QXx9HHWoZT4:-NS5KEifD0tsZuDJNFo-:b-dzyrsh) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L144)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Not clear if they both need to happen, if so you can wrap then under transaction.
</blockquote></details>

when we refresh the token, both access and refresh tokens are generated again, so we do need to update both of them.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 6 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/45973#-NS58ck_3zNPH46d4lcL:-NSApdWsD7MGAD5AJ7P4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5259184faf3b97aadddb333160665259ed66832/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L101)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

if its a Db write, you could add a logging here if write operation fails.
</blockquote></details>

Done.

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 6 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained.

**Review by senjucanon2 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 6 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 2. unresolved discussions.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBONeO0ox9jWj0H3SZ:-NSBONeO0ox9jWj0H3S_:b6b6fmw) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L137)):*
> ```Java
>   }
> 
>   AutoLogContext getAutoLogContext(String accountIdentifier, String userIdentifier) {
> ```

This isn't a good way to create auto log context. Its very restricted and not expandable.

We already have a userLogContext which you can use :
```public class UserLogContext extends AutoLogContext {
```

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBONeO0ox9jWj0H3SZ:-NSBO_Q31Djo3hjo3zoz:b-jx4s1i) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L137)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This isn't a good way to create auto log context. Its very restricted and not expandable.

We already have a userLogContext which you can use :
```public class UserLogContext extends AutoLogContext {
```
</blockquote></details>

```
public class UserLogContext extends AutoLogContext {

```

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBOjUz8NiBQbfeU6_K:-NSBOjUz8NiBQbfeU6_L:bz7519i) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L77)):*
> ```Java
> 
>       if (tokenDTO == null || refreshTokenDTO == null) {
>         log.error("[Gitlab SCM OAuth refresh] Error getting refresh/access token");
> ```

lets print tokenDTO and refreshTokenDTO here so that we know what happened, what value was null etc.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBOjUz8NiBQbfeU6_K:-NSBOy-JBB1ScEXwilkI:b-94vmuf) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L77)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets print tokenDTO and refreshTokenDTO here so that we know what happened, what value was null etc.
</blockquote></details>

Ok, I'm not sure actually if we can log here, as token or refreshtoken may contain user secret values. Just check, we can see if we can do anything better here.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBPJed1NArx1H7gFjd:-NSBPJed1NArx1H7gFje:b7und5q) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L100)):*
> ```Java
>       log.info("[Gitlab SCM OAuth refresh] -Got new access & refresh token");
> 
>       updateSecretSecretValue(entity, tokenDTO, refreshTokenResponse.getAccessToken());
> ```

we were about to put a dedicated try catch for these update use-cases right?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBONeO0ox9jWj0H3SZ:-NSBPPFR7P8RhW7ghv0x:b-aeapx9) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L137)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

```
public class UserLogContext extends AutoLogContext {

```
</blockquote></details>

I would suggest to create a new auto log context which is dedicated for toke refresher. We can keep a field for type of token refresher or type of git provider in it. This way if you see right now in every log we append : "Gitlab SCM OAuth refresh", this won't be required once we do it.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 2. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBOjUz8NiBQbfeU6_K:-NSBPv9S01IP8t-sAXWi:b-uhhcfm) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L77)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Ok, I'm not sure actually if we can log here, as token or refreshtoken may contain user secret values. Just check, we can see if we can do anything better here.
</blockquote></details>

we can check for them separately and add in the log which token was null
___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java` line 100 at r4](https://reviewable.io/reviews/harness/harness-core/45973#-NSBPJed1NArx1H7gFjd:-NSBPgs_4cBqILIyc5t6:b-ra0df0) ([raw file](https://github.com/harness/harness-core/blob/746a5b3bc4de4078cf35434e3ec43f8b57d4a36f/120-ng-manager/src/main/java/io/harness/ng/oauth/GitlabSCMOAuthTokenRefresher.java#L100)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we were about to put a dedicated try catch for these update use-cases right?
</blockquote></details>

have put them in the updateSecretSecretValue method itself

**Review by HenAmar — DISMISSED** [review]

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: 3 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger review

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger ut2

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45973)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
