### PR TITLE
[feat]:[pl-28597]: Import Template from Git

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Import Template from Git. Have tested out the following flows:

1. Import from git happy path 
2. File uniqueness
3. Matching data logic from user inputs and yaml from git
4. Import V2 of existing template and verify last updated and stable version

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38262)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSJkKd6MxJ6JgDgjcU:-NDSJkKd6MxJ6JgDgjcV:baxf5u9) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L89)):*
> ```Java
>   boolean deleteAllOrgLevelTemplates(String accountId, String orgId);
> 
>   Long countFileInstances(String accountId, String repoURL, String filePath);
> ```

accountIdentifier

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Code issue 9 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38262)

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSJvEf-hmZ1hCmhiGw:-NDSJvEf-hmZ1hCmhiGx:bl2zhrp) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L478)):*
> ```Java
>   }
> 
>   private Long countAllTemplates(Criteria criteria) {
> ```

better method name would be "count" or "countTemplates" only

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 468 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSK3n8CtgJhhDODCWr:-NDSK3n8CtgJhhDODCWs:b-7s5l1l) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L468)):*
> ```Java
> 
>   @Override
>   public TemplateEntity saveTemplateEntityForImportedYAML(TemplateEntity templateEntity, String comments) {
> ```

whats so special about IMPORT that this method does that its name is so specific?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 545 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSKPGdBnLNw6fJpylJ:-NDSKPGdBnLNw6fJpylK:bvrxep3) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L545)):*
> ```Java
> 
>   public String getRepoUrlAndCheckForFileUniqueness(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String templateIdentifier, Boolean isForceImport) {
> ```

should be "boolean"

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 565 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSKpjf2HDG7Qa_pLfx:-NDSKpjf2HDG7Qa_pLfy:b8fe11u) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L565)):*
> ```Java
>   }
> 
>   public String importTemplateFromRemote(String accountId, String orgIdentifier, String projectIdentifier) {
> ```

why is this a new method? Whats so special about IMPORT that it does?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 578 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSKwyV1-w5D2h-YHjS:-NDSKwyV1-w5D2h-YHjT:b-csa8tn) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L578)):*
> ```Java
> 
>   public static void checkAndThrowMismatchInImportedTemplateMetadata(String orgIdentifier, String projectIdentifier,
>       String templateIdentifier, TemplateImportRequestDTO templateImportRequest, String importedTemplate) {
> ```

Lets rename it importTemplateYaml just to be more specific

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 577 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSLKaD5szAGxAIAEWh:-NDSLKaD5szAGxAIAEWi:b-suvqt1) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L577)):*
> ```Java
>   }
> 
>   public static void checkAndThrowMismatchInImportedTemplateMetadata(String orgIdentifier, String projectIdentifier,
> ```

why is this a static method

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 659 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSLQat4PRXOx3q5BHL:-NDSLQat4PRXOx3q5BHM:blsqnfc) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L659)):*
> ```Java
>   }
> 
>   public static InvalidYamlException buildInvalidYamlException(String errorMessage, String pipelineYaml) {
> ```

why is this private method?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 659 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSLQat4PRXOx3q5BHL:-NDSLX1j6DyAvaEj0Nmm:b-7m2zro) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L659)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this private method?
</blockquote></details>

not ^

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 764 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSLedq6-uCeaNpGBH7:-NDSLedq6-uCeaNpGBH8:b-yf8p6l) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L764)):*
> ```Java
>   public TemplateEntity importTemplateFromRemote(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String templateIdentifier, TemplateImportRequestDTO templateImportRequest,
>       Boolean isForceImport) {
> ```

boolean

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 549 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSLqU8DQXgZtR7bhhb:-NDSLqU8DQXgZtR7bhhc:bupy2xn) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L549)):*
> ```Java
>     String repoURL = gitAwareEntityHelper.getRepoUrl(accountIdentifier, orgIdentifier, projectIdentifier);
> 
>     if (Boolean.TRUE.equals(isForceImport)) {
> ```

what is this check even doing here? There's no concrete action in the if block

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 778 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSM5QQ3I7QMWnyDKH_:-NDSM5QQ3I7QMWnyDKHa:baskevn) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L778)):*
> ```Java
>     try {
>       GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
>       if (templateGitXService.isNewGitXEnabledAndIsRemoteEntity(templateEntityToSave, gitEntityInfo)) {
> ```

We can remove this check from here and put it at the start of this method itself. Basically you cannot import if its not a gitX enabled project or similar.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 807 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSMHNN4Dzj-vJvZm0E:-NDSMHNN4Dzj-vJvZm0F:bgpcz88) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L807)):*
> ```Java
>     GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
>     gitEntityInfo.setStoreType(StoreType.REMOTE);
>     templateEntity.setStoreType(StoreType.REMOTE);
> ```

typo: duplicate line

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 803 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSMRfx7b3z4dBzu0kF:-NDSMRfx7b3z4dBzu0kG:bqwfx1o) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L803)):*
> ```Java
>   }
> 
>   private TemplateEntity prepareTemplateEntity(TemplateEntity templateEntity, String repoUrl) {
> ```

i guess similar method must exist before this one. We can just re-use the same and set RepoURL separately if required.

**Comment by adivishy1** [comment]
> ```java
> ForceImpo
> ```

By default when the UI calls this api for the first time, the value for forceImport is false, now in this flow on checking the file path already exists, we tell the user that its already present and do they want to still import it, on clicking confirm, in this case, the importFlow will get called again with the value for forceImport to be true and in this case, we dont check for the file uniqueness and we just log that its being imported forcefully.

**Comment by adivishy1** [comment]
> _[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 803 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSMRfx7b3z4dBzu0kF:-NDSMRfx7b3z4dBzu0kG:bqwfx1o) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L803)):_
> 
> > ```java
> >   }
> > 
> >   private TemplateEntity prepareTemplateEntity(TemplateEntity templateEntity, String repoUrl) {
> > ```
> 
> i guess similar method must exist before this one. We can just re-use the same and set RepoURL separately if required.

Yes, there is method which adds only a few of the required parameters but not everything, hence created a new one

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 783 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDip9NjCHex12WHvu74:-NDip9NjCHex12WHvu75:b-464tf0) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L783)):*
> ```Java
>       String projectIdentifier, String templateIdentifier, TemplateImportRequestDTO templateImportRequest,
>       boolean isForceImport) {
>     if (!templateGitXService.isNewGitXEnabled(accountIdentifier, orgIdentifier, projectIdentifier)) {
> ```

can we move this complete if block into a private method. It would make code much cleaner

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 794 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDipIiX8YXZKBtPtqIw:-NDipIiX8YXZKBtPtqIx:b-p2nri2) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L794)):*
> ```Java
>       }
>     }
>     String repoUrl = templateGitXService.getRepoUrlAndCheckForFileUniqueness(
> ```

can we make method name: checkForFileUniquenessAndGetRepoURL. This sounds more logical in order of action that we doing.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 798 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDipUX-58PYtv9jP8q_:-NDipUX-58PYtv9jP8qa:b-zatsin) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L798)):*
> ```Java
>     String importedTemplateYAML =
>         templateGitXService.importTemplateFromRemote(accountIdentifier, orgIdentifier, projectIdentifier);
>     templateGitXService.importTemplateYaml(
> ```

is this just a miss?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXService.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDipsqo5ZgViFoNuh-O:-NDipsqo5ZgViFoNuh-P:b-nlyous) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXService.java#L29)):*
> ```Java
>   String importTemplateFromRemote(String accountId, String orgIdentifier, String projectIdentifier);
> 
>   void importTemplateYaml(String orgIdentifier, String projectIdentifier, String templateIdentifier,
> ```

these 2 methods are really confusing. It is not clear what do they do.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDiqAXO7wvJRHRaftXf:-NDiqAXO7wvJRHRaftXg:b5526nl) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L156)):*
> ```Java
>   }
> 
>   private boolean isAlreadyImported(String accountIdentifier, String repoURL, String filePath) {
> ```

can we place these private methods at end of the class? It help to organize the code better.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDiqWPr9FLNEveC2fvA:-NDiqWPr9FLNEveC2fvB:b8wlxjj) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L161)):*
> ```Java
>   }
> 
>   public String importTemplateFromRemote(String accountId, String orgIdentifier, String projectIdentifier) {
> ```

Has pipeline service also written this in pipeline service? Isn't there any common method available to do it?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDiqrm5CfVESC4DtFIO:-NDiqrm5CfVESC4DtFIP:bilsjor) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L174)):*
> ```Java
> 
>   public void importTemplateYaml(String orgIdentifier, String projectIdentifier, String templateIdentifier,
>       TemplateImportRequestDTO templateImportRequest, String importedTemplate) {
> ```

its "importedTemplateYaml" right? Lets add yaml prefix just for better readability. May be it was obvious, please correct me if thats the case.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 259 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDirKA9C3II2JH5GuCB:-NDirKA9C3II2JH5GuCC:brcszjl) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L259)):*
> ```Java
>         YamlSchemaErrorWrapperDTO.builder()
>             .schemaErrors(
>                 Collections.singletonList(YamlSchemaErrorDTO.builder().message(errorMessage).fqn("$.pipeline").build()))
> ```

will this be "pipeline" here?

**Comment by AnshuH** [comment]
trigger codebasehash

**Comment by adivishy1** [comment]
trigger ti1

**Comment by adivishy1** [comment]
trigger authorcheck

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXService.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDipsqo5ZgViFoNuh-O:-NDm-JDx92O0R_kCfxcX:b-2f5kuu) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXService.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

these 2 methods are really confusing. It is not clear what do they do.
</blockquote></details>

can we rename it to something like : performImportFlowYamlValidations() as the method takes in importRequest as argument but method name is very generic

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 151 at r5](https://reviewable.io/reviews/harness/harness-core/38262#-NDm-acN674Sr0PIsk_9:-NDm-acN674Sr0PIsk_A:b-gdi8sn) ([raw file](https://github.com/harness/harness-core/blob/d5129ccd935442e6b29d45a61eb3f497114fff2c/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L151)):*
> ```Java
>   }
> 
>   public String importTemplateFromRemote(String accountId, String orgIdentifier, String projectIdentifier) {
> ```

accountIdentifier*

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38262)* status: 17 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 468 at r1](https://reviewable.io/reviews/harness/harness-core/38262#-NDSK3n8CtgJhhDODCWr:-NDm0zzL-vJgvD7C8zCm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e40e7526dc98339a50fe6ac29d1fca950f9eb23f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L468)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats so special about IMPORT that this method does that its name is so specific?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXService.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDipsqo5ZgViFoNuh-O:-NDm0u4V1AbaMmrJrbwh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXService.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we rename it to something like : performImportFlowYamlValidations() as the method takes in importRequest as argument but method name is very generic
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/38262#-NDiqWPr9FLNEveC2fvA:-NDm0v9k4ClFMFTyAHu5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0124f33907a3be39ae9324b53ca5a7dabe220858/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L161)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Has pipeline service also written this in pipeline service? Isn't there any common method available to do it?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java` line 151 at r5](https://reviewable.io/reviews/harness/harness-core/38262#-NDm-acN674Sr0PIsk_9:-NDm0vpz1UECkPLGj2Cg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5129ccd935442e6b29d45a61eb3f497114fff2c/840-template-service/src/main/java/io/harness/template/services/TemplateGitXServiceImpl.java#L151)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

accountIdentifier*
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 5 of 13 files at r2, 3 of 9 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38262)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38262)* status: :shipit: complete! ✓

**Pull request merged**
