### PR TITLE
fix: [CDC-16376]: Error Handling for Service & Environment APIs

### PR DESCRIPTION
**Pull request by shivamnegi94**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30708)

### CODE REVIEW

**Review by poojaSinghal — DISMISSED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30708)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30708)* status: :shipit: complete! ✓

___
*[120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java, line 69 at r1](https://reviewable.io/reviews/harness/harness-core/30708#-MvcBCRc1Bm7JuvqHbGx:-MvcBCRc1Bm7JuvqHbGy:b20t9km) ([raw file](https://github.com/harness/harness-core/blob/4bae1ba40fdaa9a07fdff4853be53e39f60a2d4d/120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java#L69)):*
> ```Java
>       }
>     }
>     return true;
> ```

This code is same as env manage service impl, why not create another helper. class which has this method?



_Code quote:_
```Java
  @Override
  public boolean checkThatTheOrganizationAndProjectExists(
      String orgIdentifier, String projectIdentifier, String accountIdentifier) {
    if (isNotEmpty(orgIdentifier)) {
      final Optional<Organization> organization = organizationService.get(accountIdentifier, orgIdentifier);
      if (!organization.isPresent()) {
        throw new NotFoundException(String.format("org [%s] not found.", orgIdentifier));
      }
    }

    if (isNotEmpty(orgIdentifier) && isNotEmpty(projectIdentifier)) {
      final Optional<Project> project = projectService.get(accountIdentifier, orgIdentifier, projectIdentifier);
      if (!project.isPresent()) {
        throw new NotFoundException(String.format("project [%s] not found.", projectIdentifier));
      }
    }
    return true;
```
___
*[950-ng-core/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java, line 409 at r1](https://reviewable.io/reviews/harness/harness-core/30708#-MvcB6m4DE9pHMm4X53S:-MvcB6m4DE9pHMm4X53T:bd5s3ff) ([raw file](https://github.com/harness/harness-core/blob/4bae1ba40fdaa9a07fdff4853be53e39f60a2d4d/950-ng-core/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L409)):*
> ```Java
>       return;
>     }
>     serviceEntities.forEach(serviceEntity -> validateTheServiceRequest(serviceEntity));
> ```

rename maybe to modifyServiceRequest?



_Code quote:_
```Java
validateTheServiceRequest
```

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 16 Issues 
* Vulnerability 4 Vulnerabilities 
 * Code issue 8 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/30708)

**Pull request closed without merging**
