### PR TITLE
feat: [CDS-77481]: Remove list for nodeExecution in expression playground

### PR DESCRIPTION
**Pull request by Y0709**
Removed the list query for fetching node execution with planExecutionId from a closeable iterator query.

Testing 

Tested basic scenarios using expression playground for a pipeline with a few expressions
Screenshot 2023-08-22 at 6 22 19 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/51909#-NcSHqAy4bHnUuSr6wmq:-NcSHqAy4bHnUuSr6wmr:bco1wkb) ([raw file](https://github.com/harness/harness-core/blob/0eb8acc5d4c3066f4bd7b68436ab767291d6ab72/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java#L60)):*
> ```Java
>     // This map matches the fqn with each Ambiance. Here the fqn is calculated using level's identifier (till where last
>     // group in level is not null) of each ambiance.
>     Map<String, Ambiance> fqnToAmbianceMap = getFQNToAmbianceMap(nodeExecutions);
> ```

why do we need to keep map of string. ambiance?



_Code quote:_
```Java
Map<String, Ambiance> fqnToAmbianceMap
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/51909#-NcSHqAy4bHnUuSr6wmq:-NcT7PM-2hHws6by9_9l:be8e5il) ([raw file](https://github.com/harness/harness-core/blob/0eb8acc5d4c3066f4bd7b68436ab767291d6ab72/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java#L60)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need to keep map of string. ambiance?
</blockquote></details>

Map is required for resolving expressions in the pipeline. Customer might use execution.steps...outcome.name
which will be resolved via ambiance.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/51909#-NcWsOd4BjLeRpOSoP_Q:-NcWsOd4BjLeRpOSoP_R:b-fo955j) ([raw file](https://github.com/harness/harness-core/blob/81bc0a4e9099f6293d57b6f7d399949e3ad53fbc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java#L57)):*
> ```Java
>     // TODO Optimise this further to avoid getting ambiance for all the node executions for a planExecution
>     CloseableIterator<NodeExecution> nodeExecutions =
>         nodeExecutionService.fetchAllWithPlanExecutionId(planExecutionId, NodeProjectionUtils.withAmbiance);
> ```

can you move this to analytis node

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/51909#-NcWsOd4BjLeRpOSoP_Q:-NcWwObO2jdp0ICwbHRw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81bc0a4e9099f6293d57b6f7d399949e3ad53fbc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java#L57)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you move this to analytis node
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51909)* status: :shipit: complete! ✓

**Pull request merged**
