### PR TITLE
fix: [CDS-75799]: add projection to remove excluded fields from change stream document output in debezium

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51309)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51309)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/51309#-NauXDA82L6aibXCUApK:-NauXDA82L6aibXCUApL:bqepe5a) ([raw file](https://github.com/harness/harness-core/blob/f996c8e728451ce860684d0fa2f93ad480410c53/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L116)):*
> ```Java
>     if (!isEmpty(fieldExcludeList)) {
>       List<String> excludedFields = Arrays.asList(fieldExcludeList.split(","));
>       String cursor = "[{ $project: { ";
> ```

Please use StringBuilder 

https://dev.to/this-is-learning/performance-benchmarking-string-and-string-builder-3bid#:~:text=StringBuilder%20executes%20significantly%20faster%20than,should%20consider%20the%20StringBuilder%20class.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51309)* status: 1 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51309)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/51309#-NauXDA82L6aibXCUApK:-NaudO-B9NqGJ7Soid2r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f996c8e728451ce860684d0fa2f93ad480410c53/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L116)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please use StringBuilder 

https://dev.to/this-is-learning/performance-benchmarking-string-and-string-builder-3bid#:~:text=StringBuilder%20executes%20significantly%20faster%20than,should%20consider%20the%20StringBuilder%20class.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51309)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51309)* status: 1 file(s) to review.

**Comment by shalini-agr** [comment]
trigger review

**Review by pranay-harness — APPROVED** [review]
Library version upgrade approved

**Pull request merged**
