### PR TITLE
[fix]: [PL-24905]: Fixing Base Url for SAML Test Connection for Vanit…

### PR DESCRIPTION
**Pull request by boopesh007**
…y URLs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34563)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 495 at r1](https://reviewable.io/reviews/harness/harness-core/34563#-N5Ji2NZ0bd-_HtuwT5K:-N5Ji2NZ0bd-_HtuwT5L:b-wu1gm4) ([raw file](https://github.com/harness/harness-core/blob/57112bb21d72afe0c694c56e3ac0470f9e208f59/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L495)):*
> ```Java
>     } catch (WingsException e) {
>       if (e.getCode() == ErrorCode.SAML_TEST_SUCCESS_MECHANISM_NOT_ENABLED) {
>         accountId = credentials[2];
> ```

This can lead to indexOutofBound exception in some cases, need to have check `credentials.length >= 3` 
Also, will this always be credentials[2]? there won't be case where we might have to get the defaultAccountId of user?

Thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 497 at r1](https://reviewable.io/reviews/harness/harness-core/34563#-N5JiWlr1lHpJbj8REIn:-N5JiWlr1lHpJbj8REIo:b2qys6o) ([raw file](https://github.com/harness/harness-core/blob/57112bb21d72afe0c694c56e3ac0470f9e208f59/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L497)):*
> ```Java
>         accountId = credentials[2];
>         String baseUrl = accountService.get(accountId).getSubdomainUrl();
>         if (baseUrl == null) {
> ```

nit: isNotEmpty would be better here

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 495 at r1](https://reviewable.io/reviews/harness/harness-core/34563#-N5Ji2NZ0bd-_HtuwT5K:-N5KLvI518hz1br9W18n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/57112bb21d72afe0c694c56e3ac0470f9e208f59/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L495)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

This can lead to indexOutofBound exception in some cases, need to have check `credentials.length >= 3` 
Also, will this always be credentials[2]? there won't be case where we might have to get the defaultAccountId of user?

Thanks
</blockquote></details>

Done.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34563)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34563)* status: :shipit: complete! ✓

**Pull request merged**
