### PR TITLE
techdebt: [PL-29652]: Fix the cycle between exception and ngexception of 980-commons

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

Fix the below cycle in 980-commons between exception and ngexception:

ERROR: /Users/raghavendramurali/harness-core/980-commons/src/main/java/io/harness/exception/BUILD.bazel:4:13: in java_library rule //980-commons/src/main/java/io/harness/exception:module: cycle in dependency graph:

.-> //980-commons/src/main/java/io/harness/exception:module 
|   //980-commons/src/main/java/io/harness/exception/ngexception:module 
`-- //980-commons/src/main/java/io/harness/exception:module 

The ErrorMetadataDTO and ErrorMetadataConstants have been moved to a sub-folder without renaming the package name as renaming the package causes kryo exceptions.

Tested the below scenarios in PR env -

1. K8s end to end workflow (CG).
2. Secret manager and secrets creation (CG and NG).
 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41053)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41053)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger smartchecks

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, ti2

**Comment by Raghav-Murali** [comment]
trigger ft1, ft2

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, ti2

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, ti2

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat

**Review by gn-harness — APPROVED** [review]

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41053)* status: 2 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41053)* status: :shipit: complete! ✓

**Pull request merged**
