### PR TITLE
fix: [CDS-79717]: Maintaining InfrastructureEntity list order

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
Maintaining InfrastructureEntity list order in the ChildrenExecutableResponse to avoid the rollback step stuck issue
All changes are on NG manager Side

#### Before Code changes Screenshot:
Screenshot 2023-09-27 at 5 27 56 PM

#### After Code changes Screenshot:
Screenshot 2023-09-27 at 5 29 30 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53448)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger uts

**Review by tchaurasiya — DISMISSED** [review]

**Comment by namantalaycha10** [comment]
trigger uts

**Review by tchaurasiya — DISMISSED** [review]

**Comment by namantalaycha10** [comment]
> _[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/53448#-NfMJaJ_-biRUH6g_iXy:-NfMJaJa73i73sc7n5ou:b1kq5r3) ([raw file](https://github.com/harness/harness-core/blob/03233632421444829b69a1c10b1ece26155c4036/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L184)):_
> 
> > ```java
> >   public List<InfrastructureEntity> getInfrastructureForEnvironmentList(String accountIdentifier, String orgIdentifier,
> >       String projectIdentifier, String envRef, ServiceDefinitionType deploymentType) {
> >     return infrastructureEntityService.getAllInfrastructureFromEnvRefAndDeploymentType(
> > ```
> 
> are these always sorted?
> 
> _Code quote:_
> 
> ```java
> getAllInfrastructureFromEnvRefAndDeploymentType
> ```

ohh sorry forgot , to commit that file
done now

**Comment by namantalaycha10** [comment]
> _[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/53448#-NfMJaJ_-biRUH6g_iXy:-NfQyyH19awWiCDBI3hV:bu1fioz) ([raw file](https://github.com/harness/harness-core/blob/03233632421444829b69a1c10b1ece26155c4036/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L184)):_
> 
> Previously, sahilhindwani-harness (Sahil Hindwani) wrote…
> did we not add sort on createdAT ?

ohh sorry forgot , to commit that file
done now

**Comment by namantalaycha10** [comment]
trigger uts

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53448)* status: 5 file(s) to review. 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53448)* status: 5 file(s) to review.

**Comment by namantalaycha10** [comment]
trigger review

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53448)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
LGTM

**Pull request merged**
