### PR TITLE
fix: [CDS-7642]: Updating Chartmuseum bin version from 0.13.0 to 0.12.0

### PR DESCRIPTION
**Pull request by namantalaycha10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30971)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by shubham-in10se — COMMENTED** [review]
can we explore to have the versions as constants to be used in shell scripts, similar to what we do in Java [using a constants file]
for implementation reference:
https://unix.stackexchange.com/questions/495082/maintaining-several-constants-for-several-bash-scripts

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30971)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30971)* status: Some of the checks are too old. 1 change requests. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30971#-MwyX4M27y4PgK50k5pH:-MwyX4M27y4PgK50k5pI:bq05sda) (no related file):*
Did we upload chartmuseum v0.12 in our GCS buckets ?

---

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30971)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/30971#-MwyX4M27y4PgK50k5pH:-MwycNtkBBwxdVNb7-aE:bc6e5fq) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Did we upload chartmuseum v0.12 in our GCS buckets ?
</blockquote></details>

Yes @yogesh-chauhan 

---

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30971)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30971)* status: :shipit: complete! ✓

**Pull request merged**
