### PR TITLE
[fix]: [CDS-77557]: Introducing InstrumentedExecutorService for pipeline-service

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

Changes- Introducing InstrumentedExecutorService for pipeline-service

Impact - Adding new metrics as scheduled metrics, will not impact any executions

Testing -
Metrics are getting published into prometheus
Screenshot 2023-10-17 at 10 30 59 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54265)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger messagecheck

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger ut6,ut7,ut8,ut9

**Comment by archit-harness** [comment]
trigger ut8

**Comment by archit-harness** [comment]
trigger ut6

**Comment by archit-harness** [comment]
trigger ut7

**Comment by archit-harness** [comment]
trigger ut8

**Comment by archit-harness** [comment]
trigger uts

**Review by hextechpal — DISMISSED** [review]
> Reviewed 9 of 12 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54265)* status: 18 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/iterator/PersistenceIteratorFactory.java` line 202 at r2](https://reviewable.io/reviews/harness/harness-core/54265#-Nh136p5065QmpIg6onQ:-Nh136p5065QmpIg6onR:b-yif5u6) ([raw file](https://github.com/harness/harness-core/blob/e29ae1e1548c6a8138f8897e7c6265072a3a2686/960-persistence/src/main/java/io/harness/iterator/PersistenceIteratorFactory.java#L202)):*
> ```Java
>     // Create the main executor thread that carries out the Redis
>     // lock acquisition and fetching / updating docs with Mongo.
>     String iteratorMainName = iteratorName + "-Main";
> ```

nit, why this change

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54265)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/iterator/PersistenceIteratorFactory.java` line 202 at r2](https://reviewable.io/reviews/harness/harness-core/54265#-Nh136p5065QmpIg6onQ:-Nh1Okrv243YKNBIBbBi:b-w4v7sz) ([raw file](https://github.com/harness/harness-core/blob/e29ae1e1548c6a8138f8897e7c6265072a3a2686/960-persistence/src/main/java/io/harness/iterator/PersistenceIteratorFactory.java#L202)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

nit, why this change
</blockquote></details>

Earlier we added instrumented in this method as well, but we reverted as initially we don't want to capture it, it got left. didn't see any harm thus left it

**Comment by archit-harness** [comment]
trigger uts

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54265)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]

**Review by rafaelmart1ns — APPROVED** [review]

**Review by deepak-harness — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 1 of 1 files at r2, 7 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54265)* status: 1. unresolved discussions.

**Pull request merged**
