### PR TITLE
feat: [PL-29878]: reduce call to load support account

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
This method just checks whether user has access to that account, so, not need to load support accounts for this. 
We can just check whether user is harnessSupportUser and that account has enabled harnessSupportAccess.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)

### CODE REVIEW

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3139 at r1](https://reviewable.io/reviews/harness/harness-core/41041#-NIIJrxf9G9HNAZoBr4u:-NIILlG-0QWQHQYo0UCi:b4hjjza) ([raw file](https://github.com/harness/harness-core/blob/11e2f5ed29848be9ded4df838c28728b9352d692/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3139)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be 

accountService.isRestrictedAccessEnabled(accountId)
</blockquote></details>

No, actually this reverse 
This is its implementation

Screenshot 2022-12-02 at 8.30.21 PM

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3139 at r1](https://reviewable.io/reviews/harness/harness-core/41041#-NIIJrxf9G9HNAZoBr4u:-NIIM34v96N6PZILQHe2:b-rwqr61) ([raw file](https://github.com/harness/harness-core/blob/11e2f5ed29848be9ded4df838c28728b9352d692/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3139)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

No, actually this reverse 
This is its implementation

Screenshot 2022-12-02 at 8.30.21 PM
</blockquote></details>

Hahaha. Can we improve this code. This is quite unintuitive

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by bhavya181** [comment]
trigger ti3

**Comment by bhavya181** [comment]
trigger ti3

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041#-:-NIX-Mks7Vp-lsj74YN_:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)* status: :shipit: complete! ✓

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 4 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)* status: :shipit: complete! ✓

**Review by rijajoo — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 5 files at r2, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041)* status: :shipit: complete! ✓

**Review by rijajoo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41041#-:-NIgWGc564a_Xgg-jeSF:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
