### PR TITLE
fix: [DEL-3686]: Add task failure reason to exception message

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32154)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 828 at r1](https://reviewable.io/reviews/harness/harness-core/32154#-N-Bn-Nh6Y5bUr9dxrPn:-N-Bn-Nh6Y5bUr9dxrPo:b2g1wyg) ([raw file](https://github.com/harness/harness-core/blob/99f1b30411e721d3735839fabcbb5af0603cadfb/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L828)):*
> ```Java
>     try {
>       List<Delegate> accountDelegates = fetchActiveDelegates(task.getAccountId());
>       boolean isTaskNg = !isEmpty(task.getSetupAbstractions())
> ```

lets create a method inside DelegateTask to return if its ng

**Comment by raghuAtWings** [comment]
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 832 at r1](https://reviewable.io/reviews/harness/harness-core/32154#-N-BnAn44XWzmK3oBogl:-N-BnAn44XWzmK3oBogm:b-rpx2vp) ([raw file](https://github.com/harness/harness-core/blob/99f1b30411e721d3735839fabcbb5af0603cadfb/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L832)):*
> ```Java
>           && Boolean.TRUE.equals(Boolean.valueOf(task.getSetupAbstractions().get(NgSetupFields.NG)));
>       accountDelegates = accountDelegates.stream()
>                              .filter(delegate -> delegate.isNg() == isTaskNg || !delegate.isNg() == !isTaskNg)
> ```

wouldn't the first condition be enough?

**Comment by raghuAtWings** [comment]
*[920-delegate-service-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java, line 18 at r1](https://reviewable.io/reviews/harness/harness-core/32154#-N-BnoFVDejST0VCw-XS:-N-BnoFVDejST0VCw-XT:btbgrav) ([raw file](https://github.com/harness/harness-core/blob/99f1b30411e721d3735839fabcbb5af0603cadfb/920-delegate-service-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java#L18)):*
> ```Java
>     super("No eligible delegates to execute task. ", NO_AVAILABLE_DELEGATES);
>   }
>   public NoEligibleDelegatesInAccountException(String message) {
> ```

no reason to have the default constructor

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32154)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 832 at r1](https://reviewable.io/reviews/harness/harness-core/32154#-N-BnAn44XWzmK3oBogl:-N-JSn8F1dbEPGmwxrvb:bz9a65i) ([raw file](https://github.com/harness/harness-core/blob/99f1b30411e721d3735839fabcbb5af0603cadfb/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L832)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

wouldn't the first condition be enough?
</blockquote></details>

here we are filter delegates based in NG or CG, So for CG task we need to filter based on isNG false and for NG task to filter based on isNG true.

**Comment by jennyjames21** [comment]
*[400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java, line 828 at r1](https://reviewable.io/reviews/harness/harness-core/32154#-N-Bn-Nh6Y5bUr9dxrPn:-N-JSmMPCPbNFmSeYv2S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/99f1b30411e721d3735839fabcbb5af0603cadfb/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L828)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

lets create a method inside DelegateTask to return if its ng
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[920-delegate-service-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java, line 18 at r1](https://reviewable.io/reviews/harness/harness-core/32154#-N-BnoFVDejST0VCw-XS:-N-JTApb4Tx4_6Oy8mM9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/99f1b30411e721d3735839fabcbb5af0603cadfb/920-delegate-service-beans/src/main/java/io/harness/delegate/NoEligibleDelegatesInAccountException.java#L18)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

no reason to have the default constructor
</blockquote></details>

Done.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32154)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger ti3

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32154)* status: :shipit: complete! ✓

**Pull request merged**
