### PR TITLE
[fix]: [PL-30547]: Fixing delegate v2 task failure handling

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41978)

### CODE REVIEW

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41978)* status: Some of the checks are too old. 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/41978#-NKHCzpHAVFsaqPYGvs0:-NKHCzpHAVFsaqPYGvs1:bmyta7j) ([raw file](https://github.com/harness/harness-core/blob/3451de7f623f444753562bd391db64b084d457de/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L310)):*
> ```Java
>   private boolean canAssignDelegateScopes(Delegate delegate, DelegateTask task) {
>     TaskGroup taskGroup;
>     if (task.getData() != null) {
> ```

Should we check for taskDataV2 null condition first incase data is already copied to taskDataV2 previously

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41978)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/41978#-NKHCvEd3E9Je8B_XLoZ:-NKHCvEd3E9Je8B_XLo_:bnryugp) ([raw file](https://github.com/harness/harness-core/blob/3451de7f623f444753562bd391db64b084d457de/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L322)):*
> ```Java
>       persistence.save(DelegateSyncTaskResponse.builder()
>                            .uuid(delegateTask.getUuid())
>                            .usingKryoWithoutReference(false)
> ```

Why false?

**Comment by ashishsanodia-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 310 at r1](https://reviewable.io/reviews/harness/harness-core/41978#-NKHCzpHAVFsaqPYGvs0:-NKHpz0l4weYRtLGMA7c:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/3451de7f623f444753562bd391db64b084d457de/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L310)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Should we check for taskDataV2 null condition first incase data is already copied to taskDataV2 previously
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 322 at r1](https://reviewable.io/reviews/harness/harness-core/41978#-NKHCvEd3E9Je8B_XLoZ:-NKHq0of0l-5YtUZ7-Vk:b-2apzq9) ([raw file](https://github.com/harness/harness-core/blob/3451de7f623f444753562bd391db64b084d457de/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L322)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why false?
</blockquote></details>

This is still using kryoSerializer and should be false. We will make it true once we change delegate responses to start using referenceFalseKryoSerializer

**Comment by diptiman-adak** [comment]
trigger codeformat

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41978)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41978)* status: :shipit: complete! ✓

**Pull request merged**
