### PR TITLE
feat: [SMP-819]: add smpAccount field in dto and migrations

### PR DESCRIPTION
**Pull request by kapilgarg1996**
## Describe your changes
Requirement
1. Maintain SMP customer accounts in SaaS for auditing and book-keeping. These accounts won't be associated with any user
2. There MUST be an identifier to distinguish these accounts from SaaS regular accounts.
3. This identifier should be boolean to use it in filters on dashboards for analysis on saas accounts and smp accounts separately
4. The existing accounts in SaaS are all SaaS customer accounts and this identifier should be added to those accounts. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40215)

### CODE REVIEW

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java` line 411 at r3](https://reviewable.io/reviews/harness/harness-core/40215#-NH9TI7CBiWqEeOxL71H:-NH9TI7CBiWqEeOxL71I:b-t6m2gs) ([raw file](https://github.com/harness/harness-core/blob/2fba2f9fc3e4aa52fe6629e8a00c7f30a2da5876/390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java#L411)):*
> ```Java
>         .add(Pair.of(237, DisableArtifactCollectionForInactiveAccount.class))
>         .add(Pair.of(238, AddMisfireInstructionToQuartz.class))
>         .add(Pair.of(239, BaseMigration.class))
> ```

where is this migration in the code?

**Review by kapilgarg1996 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40215)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java` line 411 at r3](https://reviewable.io/reviews/harness/harness-core/40215#-NH9TI7CBiWqEeOxL71H:-NH9nCtD9msdgCju-DCd:bj0cisg) ([raw file](https://github.com/harness/harness-core/blob/2fba2f9fc3e4aa52fe6629e8a00c7f30a2da5876/390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java#L411)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

where is this migration in the code?
</blockquote></details>

Isn't BaseMigration just a way to increment the schema version in db ? I saw someone had his own migration with number 239, and they removed it and the migration has been completed in prod
Now if i define my migration with same number 239, it won't run because 239 has already been completed. So I thought of skipping 239 by BaseMigration. Do let me know if there is any other solution to this

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddIsSmpAccountToAccount.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/40215#-NHT1XgB1XTK6JeO0UE-:-NHT1XgB1XTK6JeO0UE0:bmt6bih) ([raw file](https://github.com/harness/harness-core/blob/2fba2f9fc3e4aa52fe6629e8a00c7f30a2da5876/390-db-migration/src/main/java/io/harness/migrations/all/AddIsSmpAccountToAccount.java#L28)):*
> ```Java
>       for (Account account : accounts) {
>         if (!Objects.isNull(account) && !account.isSmpAccount()) {
>           wingsPersistence.updateField(Account.class, account.getUuid(), IS_SMP_ACCOUNT_FIELD, Boolean.FALSE);
> ```

add catch block and capture errors for each update call. Also info logs for each update would be better for migration purpose.

**Comment by mohitg0795** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java` line 70 at r3](https://reviewable.io/reviews/harness/harness-core/40215#-NHT1mPbDlO67v04znqq:-NHT1mPbDlO67v04znqr:b-vdsgrs) ([raw file](https://github.com/harness/harness-core/blob/2fba2f9fc3e4aa52fe6629e8a00c7f30a2da5876/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/AccountDTO.java#L70)):*
> ```Java
>   @Schema(description = "Specifies if Account is SMP account.")
>   @VariableExpression(skipVariableExpression = true)
>   boolean smpAccount;
> ```

should we name field as "isSmpAccount" ? Probably a better conventional name.

**Comment by kapilgarg1996** [comment]
trigger messagecheck

**Pull request closed without merging**
