### PR TITLE
feat: [IDP-1921]: Migrate roles with idp_manage permission to granular level idp resources permissions, Migrate resourceGroups with idp_settings resource to granular level idp resources

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Migrate roles with idp_manage permission to granular level idp resources permissions, Migrate resourceGroups with idp_settings resource to granular level idp resources

1. Updating custom roles which have idp_idpsettings_manage. Will remove idp_idpsettings_manage and add granular level resources permissions. Filtering by '_', as identifier with underscore are managed roles.
2. Updating resourceGroups which have IDP_SETTINGS resource selected. Will remove IDP_SETTINGS resource and add granular level resources

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57317)

### CODE REVIEW

**Review by Jimit09Gandhi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57317)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/57317#-NnTx3zVCmDBWXwqLC9F:-NnTx3zVCmDBWXwqLC9G:b3brbj3) ([raw file](https://github.com/harness/harness-core/blob/742f60026a97a4947c319a22f214bd258778fce4/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L89)):*
> ```Java
>       try {
>         log.info("Migrating {} for accountIdentifier = {}", MIGRATION_PURPOSE, accountIdentifier);
>         rolesUpdate(accountIdentifier);
> ```

Can you please get Prod data to check how many roles and RG have IDP permissions and resources ? Also since this is going to add load to access control on updating for roles and RG in cluster lets plan to run this during non-peak hours across all 3 Prod clusters to minimize any impact. 
___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/57317#-NnTtqHt2as5_SffDqph:-NnTtqHt2as5_SffDqpi:bqnrfx4) ([raw file](https://github.com/harness/harness-core/blob/742f60026a97a4947c319a22f214bd258778fce4/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L112)):*
> ```Java
>               String roleIdentifier = roleDTO.getIdentifier();
>               Set<String> permissions = roleDTO.getPermissions();
>               if (!roleIdentifier.startsWith("_") && permissions.contains(IDP_IDPSETTINGS_MANAGE_PERMISSION)) {
> ```

To identify Harness managed vs Non-managed roles you can you use harnessManaged from RoleResponseDTO.

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57317)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/57317#-NnTx3zVCmDBWXwqLC9F:-NnXMtThCmTFAj6TSTHi:b-cveqck) ([raw file](https://github.com/harness/harness-core/blob/742f60026a97a4947c319a22f214bd258778fce4/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L89)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can you please get Prod data to check how many roles and RG have IDP permissions and resources ? Also since this is going to add load to access control on updating for roles and RG in cluster lets plan to run this during non-peak hours across all 3 Prod clusters to minimize any impact.
</blockquote></details>

Done. Created ticket - https://harness.atlassian.net/browse/OPS-17643
Mostly, there will be less number of roles and resourceGroups for update. Will get it confirmed after above ticket execution.
And yes, we will run this during non peak hours
___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/57317#-NnTtqHt2as5_SffDqph:-NnXMsVIE4FT70ag3wOq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/742f60026a97a4947c319a22f214bd258778fce4/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L112)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

To identify Harness managed vs Non-managed roles you can you use harnessManaged from RoleResponseDTO.
</blockquote></details>

Done

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57317)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/57317#-NncNB09A29MpfKLFgoJ:-NncNB09A29MpfKLFgoK:bwpftki) ([raw file](https://github.com/harness/harness-core/blob/e3ac92c710da9f637f39dcc90442e0306eb795f0/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L158)):*
> ```Java
>             if (isNotEmpty(resourceSelectors)) {
>               for (ResourceSelector resourceSelector : resourceSelectors) {
>                 if (resourceSelector.getResourceType().equals(IDP_SETTINGS_RESOURCE_TYPE)) {
> ```

you can check for Non-harness managed resource group and update those.

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57317)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/57317#-NncM_WfC6KMTp0pzPTA:-Nncld-X0UbO-1_HrmaS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e3ac92c710da9f637f39dcc90442e0306eb795f0/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L111)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

nit: you can iterate over    List<RoleResponseDTO> roleResponseDTOS  and avoid another map rolesTypes.
</blockquote></details>

Done
___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/57317#-NncMgeh1BwTmcNZNupS:-Nncldev-nqbdwdnpHwC:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e3ac92c710da9f637f39dcc90442e0306eb795f0/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L126)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I dont see any error handling in migaration. If anything fails whole migration would fail. See if that is intented.
</blockquote></details>

Done
___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/57317#-NncNB09A29MpfKLFgoJ:-NnclePlD1GhI2K8WWqS:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e3ac92c710da9f637f39dcc90442e0306eb795f0/idp-service/src/main/java/io/harness/idp/migration/IdpRbacGlobalToGranularResourcesPermissionsMigration.java#L158)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

you can check for Non-harness managed resource group and update those.
</blockquote></details>

Done

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by kapilgarg1996 — APPROVED** [review]

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57317)* status: 9 file(s) to review.

**Comment by sathish-soundarapandian** [comment]
trigger review

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57317#-:-NncyghQBOAYw4M2676c:bnfp4nl)* status: <span>:shipit:</span> complete! ✓

**Review by jyotiraval — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger ut0, ut5

**Comment by sandeepa-kv-jois** [comment]
Unrelated tests are failing, going ahead with FM.

**Pull request merged**
