### PR TITLE
[feat]: [CVS-9292]: implemented Execution Logs for verify step for dataCollectionTaskService

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31219)

### CODE REVIEW

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31219)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ExecutionLogRecord.java, line 23 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxbTGAj0-D0GJiuuQnH:-MxbTGAj0-D0GJiuuQnI:b-37knsh) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ExecutionLogRecord.java#L23)):*
> ```Java
> @Data
> @Builder
> @OwnedBy(HarnessTeam.CV)
> ```

nit: you dont need this for files within 300-cvng
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 211 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxbUMRV66tYooPfppVv:-MxbUMRV66tYooPfppVw:br4elb7) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L211)):*
> ```Java
>     }
> 
>     ExecutionLogDTO executionLogDTO =
> ```

Should this be in a finally block ? It seems like, if the orchestrationService.queueAnalysis throws an exception for whatever reason, we will completely miss this execution log altogether. 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 228 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxbUwdEBNC5IuA45KiL:-MxbUwdEBNC5IuA45KiM:b-4rkn9b) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L228)):*
> ```Java
>       executionLogDTO.setLogLevel(ExecutionLogDTO.LogLevel.WARN);
>     } else {
>       executionLogDTO.setLog(
> ```

Also, what is the point of printing taskId in the execution log ? This is going to be visible to the customer in the UI, no ? Might be better to convert it to actual healthsource name etc and put that in the log.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31219)* status: 12 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ExecutionLogRecord.java, line 23 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxbTGAj0-D0GJiuuQnH:-MxdM98j1LWFZyVY1ZCe:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ExecutionLogRecord.java#L23)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

nit: you dont need this for files within 300-cvng
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 211 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxZrxv860QLdjjgL88G:-MxdMCBP2MpwZ65_VZ-h:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L211)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We need to have a better abstraction for execution log. Please look at ActivityLogger in current gen for example
Something like ExecutionLogger which you can get from CVNGLogService or we can define it's own provider in guice.
The api should be similar to logger interface with info, error, warn and log(level, message)

</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 211 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxbUMRV66tYooPfppVv:-MxdME5Y91EaalM6fh0K:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L211)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Should this be in a finally block ? It seems like, if the orchestrationService.queueAnalysis throws an exception for whatever reason, we will completely miss this execution log altogether. 
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 221 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxZsaOEE4dm48iHdwsl:-MxdMD4J6k_zS95lRzVp:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L221)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this mapping needs to be defined in a much better way.
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 228 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxbUwdEBNC5IuA45KiL:-MxdMEn40Gzc21nTIDnu:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L228)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Also, what is the point of printing taskId in the execution log ? This is going to be visible to the customer in the UI, no ? Might be better to convert it to actual healthsource name etc and put that in the log. 
</blockquote></details>

done
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, line 179 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxZraeR0hGVA0ZrFLTd:-MxdMHNw3cVOP1xmUhNp:bmh98xd) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java#L179)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

error filter condition should be in CVNGLog as an abstract method instead of if else condition. Filter should happen before converting this to DTO.
</blockquote></details>

removed this part from this PR. Will be added in next PR keeping these points in mind.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/CVNGLogServiceImplTest.java, line 359 at r1](https://reviewable.io/reviews/harness/harness-core/31219#-MxZsy-ODXcPtVa2oEKI:-MxdMRzJDkUx-bDwPk3P:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/17b45560d53ae918fac5f901826fb7e7a6c73897/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/CVNGLogServiceImplTest.java#L359)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why request and response time?
</blockquote></details>

removed

**Comment by kapil-harness** [comment]
PFA all the EXECUTION_LOGs getting recorded successfully in CVNGLog entity.

Screenshot 2022-03-08 at 5 02 46 PM

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 6 of 9 files at r3, 1 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31219#-:-MxgbqTs6epe-pJYpuw3:bnfp4nl)* status: 1 change requests. 2. unresolved discussions.

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 6 files at r2, 4 of 9 files at r3, 1 of 3 files at r4, 4 of 5 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31219)* status: :shipit: complete! ✓

**Pull request merged**
