### PR TITLE
fix: [PL-28659]: Handling deletion of NG entities

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41950)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger ti1

**Comment by abhinav-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/repositories/invites/custom/InviteRepositoryCustomImpl.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/41950#-NKqPqxi-vxC7nCBPZft:-NKqPqxi-vxC7nCBPZfu:b5n2yem) ([raw file](https://github.com/harness/harness-core/blob/3011d3cebd1f464b16f9c614aaeba6a44f75c3a4/120-ng-manager/src/main/java/io/harness/repositories/invites/custom/InviteRepositoryCustomImpl.java#L61)):*
> ```Java
>   public List<Invite> deleteAll(Criteria criteria) {
>     Query query = new Query(criteria);
>     return mongoTemplate.findAllAndRemove(query, Invite.class);
> ```

deleteall?



_Code quote (from 120-ng-manager/src/main/java/io/harness/ng/core/event/SettingsEventListener.java):_
```Java
AbstractEntityCleanupListener 
```

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 6 of 23 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41950)* status: 34 file(s) to review. 0 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 14 of 23 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41950)* status: 34 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java` line 294 at r5](https://reviewable.io/reviews/harness/harness-core/41950#-NKwZJXb3pVErLb1HxJM:-NKwZJXb3pVErLb1HxJN:bbojzn1) ([raw file](https://github.com/harness/harness-core/blob/046a9e66b4f562d11327cc8a27037424103b5d75/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java#L294)):*
> ```Java
>     criteria.and(ApiKeyKeys.projectIdentifier).is(projectIdentifier);
>     return criteria;
>   }
> ```

minor: This seems common code, if possible try to move it to some util in next PR. 
Thanks



_Code quote:_
```Java
  private Criteria createScopeCriteria(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
    Criteria criteria = new Criteria();
    criteria.and(ApiKeyKeys.accountIdentifier).is(accountIdentifier);
    criteria.and(ApiKeyKeys.orgIdentifier).is(orgIdentifier);
    criteria.and(ApiKeyKeys.projectIdentifier).is(projectIdentifier);
    return criteria;
  }
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 8 of 13 files at r1, 7 of 23 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41950)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 8 of 13 files at r1, 7 of 23 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41950)* status: :shipit: complete! ✓

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java` line 294 at r5](https://reviewable.io/reviews/harness/harness-core/41950#-NKwZJXb3pVErLb1HxJM:-NKwb0Ld879N_vFMav5l:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/046a9e66b4f562d11327cc8a27037424103b5d75/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java#L294)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: This seems common code, if possible try to move it to some util in next PR. 
Thanks
</blockquote></details>

Done

**Pull request merged**
