### PR TITLE
[feat]: [PIE-9122]:Added Settings For Git enabling

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger ut5

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRIJeXxCjxAbOH-y9vW:-NRIJeXxCjxAbOH-y9vX:ba3whg5) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L3)):*
> ```YAML
> #Any edit in this file should accompany an increment in version.
> name : settingsConfiguration
> version : 16
> ```

shouldnt the version be 15 not 16?

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRaphAXCfFx0IXgPxhL:-NRaphAXCfFx0IXgPxhM:b-6gmmwd) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L163)):*
> ```YAML
>         editable: true
>   - identifier: default_connector_for_git_experience
>     name: Default Connector For Git EXPERIENCE
> ```

Why's the "experience" written in all caps? Also, "name" field is the one that appears on UI?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapnck5RsszvpLpA8U:-NRapncl4DFjRtWepYE_:bihtqcv) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L172)):*
> ```YAML
>       - PROJECT
>   - identifier: enforce_git_experience
>     name: Enforce For Git EXPERIENCE
> ```

"Enforce Git Experience"

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapzaYD6_0VEpSsXec:-NRapzaYD6_0VEpSsXed:b-p68vuw) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L181)):*
> ```YAML
>       - ORGANIZATION
>       - PROJECT
>   - identifier: default_pipeline_store_type
> ```

its not only pipeline, but for all entities.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRaphAXCfFx0IXgPxhL:-NRat2hD46cvDeB8Ymvn:bez6788) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L163)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why's the "experience" written in all caps? Also, "name" field is the one that appears on UI?
</blockquote></details>

Done. Yes name id the field that will appear on UI.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapnck5RsszvpLpA8U:-NRat8UlAg8rFTQMyooT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L172)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

"Enforce Git Experience"
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapzaYD6_0VEpSsXec:-NRat9on57HS-0VU1TqL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L181)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

its not only pipeline, but for all entities.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapnck5RsszvpLpA8U:-NRbEmZF7AHkg2SbULaD:btrdfkw) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L172)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

again Experience is written all caps.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapzaYD6_0VEpSsXec:-NRbErCDDj2LYlkrReeH:bkf4w8i) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L181)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we should write that its applicable for pipelines, input-sets and templates.

So, just add "[Pipelines, Input-sets, Templates]" after "for entities" in the name field.

Same we should do for other settings names as well.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapnck5RsszvpLpA8U:-NRbmuBQCHzhU-VkaLTf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L172)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

again Experience is written all caps.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/45470#-NRapzaYD6_0VEpSsXec:-NRbmwgfEEST-WcTUdlD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4b11173713da18e9863cc38103b2188a668fbb21/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L181)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we should write that its applicable for pipelines, input-sets and templates.

So, just add "[Pipelines, Input-sets, Templates]" after "for entities" in the name field.

Same we should do for other settings names as well.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger ut8

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: :shipit: complete! ✓

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: :shipit: complete! ✓

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45470)* status: :shipit: complete! ✓

**Pull request merged**
