### PR TITLE
fix: [PL-26472]: Do not renew appRole token in HashicorpVault

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36201)

**Comment by piyush-harness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/36201#-N95U-bI84-Dkvr3qaWm:-N95U-bI84-Dkvr3qaWn:b55j8wz) ([raw file](https://github.com/harness/harness-core/blob/682302e1ea96214ce716d2746bee4a73be3c3f00/930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java#L81)):*
> ```Java
>   @Attributes(title = "k8sAuthEndpoint") private String k8sAuthEndpoint;
> 
>   @Attributes(title = "doNotRenewAppRole") private boolean doNotRenewAppRoleToken;
> ```

The name should be renewAppRoleToken with Default value set as true This name is confusing. 

Also what happens for old records in database where this value is set to Null. You need to run a migration to set true for all APP_ROLE token vault configs or Change this boolean value to Boolean to accept null where null is equivalent true.

Also mark this field optional using @FieldSerializer.Optional to avoid Kryo Errors in case of version mismatch between services.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/36201#-N95U-bI84-Dkvr3qaWm:-N95VdqqAMSeIFZx4mpj:b-9exzlc) ([raw file](https://github.com/harness/harness-core/blob/682302e1ea96214ce716d2746bee4a73be3c3f00/930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java#L81)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

The name should be renewAppRoleToken with Default value set as true This name is confusing. 

Also what happens for old records in database where this value is set to Null. You need to run a migration to set true for all APP_ROLE token vault configs or Change this boolean value to Boolean to accept null where null is equivalent true.

Also mark this field optional using @FieldSerializer.Optional to avoid Kryo Errors in case of version mismatch between services.
</blockquote></details>

I checked with old records in local, turns out nothing is breaking. I will modify the field as @optional. But we do not store baseVaultConfig in dB. So i think it is not required to put a default tag to it and assign a value. I will change the name and add the optional tag.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java` line 111 at r4](https://reviewable.io/reviews/harness/harness-core/36201#-N98YstM6fJSABzP5XyQ:-N98YstN48ivLVsRBLw1:b-f3e4ty) ([raw file](https://github.com/harness/harness-core/blob/a5d9b71a6583a7bf6a58bebc167a516b3043dc7f/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java#L111)):*
> ```Java
>                   && (ngFeatureFlagHelperService.isEnabled(
>                       accountIdentifier, FeatureName.DO_NOT_RENEW_APPROLE_TOKEN))) {
>                 BaseVaultConfig baseVaultConfig = (BaseVaultConfig) encryptionConfig;
> ```

does "vaultConfig.setDoNotRenewAppRoleToken(true);" not work?



_Code quote:_
```Java
                BaseVaultConfig baseVaultConfig = (BaseVaultConfig) encryptionConfig;
                baseVaultConfig.setDoNotRenewAppRoleToken(true);
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/36201#-N98YkW7-HqnzJdHZlg9:-N98YkW7-HqnzJdHZlgA:b-vrz8o) ([raw file](https://github.com/harness/harness-core/blob/a5d9b71a6583a7bf6a58bebc167a516b3043dc7f/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java#L113)):*
> ```Java
>                 BaseVaultConfig baseVaultConfig = (BaseVaultConfig) encryptionConfig;
>                 baseVaultConfig.setDoNotRenewAppRoleToken(true);
>                 vaultConfig = (VaultConfig) baseVaultConfig;
> ```

This seems redundant, as it is the same object



_Code quote:_
```Java
vaultConfig = (VaultConfig) baseVaultConfig;
```

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 9 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/36201#-N95U-bI84-Dkvr3qaWm:-N98_WyREtI5553JBoSO:b4emuzh) ([raw file](https://github.com/harness/harness-core/blob/682302e1ea96214ce716d2746bee4a73be3c3f00/930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java#L81)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

I checked with old records in local, turns out nothing is breaking. I will modify the field as @optional. But we do not store baseVaultConfig in dB. So i think it is not required to put a default tag to it and assign a value. I will change the name and add the optional tag.
</blockquote></details>

+1 to changing the renewAppRoleToken

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 12 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java` line 111 at r4](https://reviewable.io/reviews/harness/harness-core/36201#-N98YstM6fJSABzP5XyQ:-N9cMXJ38kvdvdZjVrLa:b3kre) ([raw file](https://github.com/harness/harness-core/blob/a5d9b71a6583a7bf6a58bebc167a516b3043dc7f/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java#L111)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

does "vaultConfig.setDoNotRenewAppRoleToken(true);" not work?
</blockquote></details>

?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/36201#-N98YkW7-HqnzJdHZlg9:-N9cMZKf9o9BcVA4dyYF:b-2yy4th) ([raw file](https://github.com/harness/harness-core/blob/a5d9b71a6583a7bf6a58bebc167a516b3043dc7f/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java#L113)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

This seems redundant, as it is the same object
</blockquote></details>

required?
___
*[`400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java` line 325 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9cQdWNDAtRCvPO_C8S:-N9cQdWOEnpKOHsqHPYr:b-t2sf7x) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L325)):*
> ```Java
>   }
> 
>   private SecretManagerConfig checkForAppRoleTokenRenewal(SecretManagerConfig secretManagerConfig, String accountId) {
> ```

nit: updateConfigForAppRoleTokenRenewal()



_Code quote:_
```Java
checkForAppRoleTokenRenewal
```
___
*[`400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9cPIHQ0guGsHlU11hm:-N9cPIHQ0guGsHlU11hn:b-oa5y9s) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L327)):*
> ```Java
>   private SecretManagerConfig checkForAppRoleTokenRenewal(SecretManagerConfig secretManagerConfig, String accountId) {
>     if ((secretManagerConfig instanceof BaseVaultConfig)
>         && (((BaseVaultConfig) secretManagerConfig).getAccessType() == APP_ROLE)) {
> ```

can combine these two if statements



_Code quote:_
```Java
    if ((secretManagerConfig instanceof BaseVaultConfig)
        && (((BaseVaultConfig) secretManagerConfig).getAccessType() == APP_ROLE)) {
      if (accountService.isFeatureFlagEnabled(FeatureName.DO_NOT_RENEW_APPROLE_TOKEN.name(), accountId)) {
        ((BaseVaultConfig) secretManagerConfig).setRenewAppRoleToken(false);
```
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9cJyQKAanU_BvaeLz1:-N9cJyQKAanU_BvaeLz2:b-nmxdhb) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java#L82)):*
> ```Java
>   @Attributes(title = "k8sAuthEndpoint") private String k8sAuthEndpoint;
> 
>   @Attributes(title = "doNotRenewAppRole") @Builder.Default private Boolean renewAppRoleToken = Boolean.TRUE;
> ```

change the title?



_Code quote:_
```Java
doNotRenewAppRole
```

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 242 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9duOXI-uZkuaSSOlUi:-N9duOXI-uZkuaSSOlUj:b-kfjtup) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L242)):*
> ```Java
>     } else if (VAULT.equals(secretManagerType)) {
>       BaseVaultConfig baseVaultConfig = (BaseVaultConfig) secretManagerConfig;
>       if (APP_ROLE.equals(baseVaultConfig.getAccessType())
> ```

Why do we need to set this value for each CRUD operation? Should'nt it be set during renewal job if the FF is enabled? 
I think the logic in VaultRenewalHandler should be querying using filter on this flag and only pick records with renewAppRoleToken=true and in the processing logic check for FF enabled and mark it false so that in the nextIteration this record does not remain eligible for renewal. Correct me if I missed something.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 14 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java` line 111 at r4](https://reviewable.io/reviews/harness/harness-core/36201#-N98YstM6fJSABzP5XyQ:-N9e9UEK6YhV2DnaIAXn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5d9b71a6583a7bf6a58bebc167a516b3043dc7f/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java#L111)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/36201#-N98YkW7-HqnzJdHZlg9:-N9e9VTw2HUcAPi8RazY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5d9b71a6583a7bf6a58bebc167a516b3043dc7f/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGSecretManagerServiceImpl.java#L113)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

required?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9cPIHQ0guGsHlU11hm:-N9eBjkJ4bcS54El_fKR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/400-rest/src/main/java/software/wings/service/impl/security/SecretManagerConfigServiceImpl.java#L327)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

can combine these two if statements
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/36201#-N95U-bI84-Dkvr3qaWm:-N9eCItb3ByJEGlo7CvZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/682302e1ea96214ce716d2746bee4a73be3c3f00/930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java#L81)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

+1 to changing the renewAppRoleToken
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java` line 82 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9cJyQKAanU_BvaeLz1:-N9eCIZh4T0swWyW5Rp9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/930-delegate-tasks/src/main/java/software/wings/beans/BaseVaultConfig.java#L82)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

change the title?
</blockquote></details>

Done.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 30 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 242 at r5](https://reviewable.io/reviews/harness/harness-core/36201#-N9duOXI-uZkuaSSOlUi:-N9lofrF9aCiUIa6R_4h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8986b07ba93fadb4ed20f0d63bded1b770cb96ee/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L242)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why do we need to set this value for each CRUD operation? Should'nt it be set during renewal job if the FF is enabled? 
I think the logic in VaultRenewalHandler should be querying using filter on this flag and only pick records with renewAppRoleToken=true and in the processing logic check for FF enabled and mark it false so that in the nextIteration this record does not remain eligible for renewal. Correct me if I missed something.
</blockquote></details>

Done.

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 3 of 11 files at r5, 3 of 8 files at r6, 11 of 15 files at r8, 3 of 4 files at r9, 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 30 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 30 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/ConnectorServiceImplTest.java` line 68 at r11](https://reviewable.io/reviews/harness/harness-core/36201#-N9wAPqA7AmGCskTm5s_:-N9wAPqA7AmGCskTm5sa:b-k5n07s) ([raw file](https://github.com/harness/harness-core/blob/21bbaeac3e37c68739d4c03d122d22a2873d3069/120-ng-manager/src/test/java/io/harness/ng/ConnectorServiceImplTest.java#L68)):*
> ```Java
>   }
> 
>   private ConnectorDTO getRequestDTO_vaultAppRole() {
> ```

nit: move after tests

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 3 of 11 files at r5, 3 of 8 files at r6, 10 of 15 files at r8, 3 of 4 files at r9, 7 of 9 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 3 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 3 of 11 files at r5, 3 of 8 files at r6, 10 of 15 files at r8, 3 of 4 files at r9, 9 of 9 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: 4. unresolved discussions.

**Comment by VikasMaddukuriHarness** [comment]
trigger codebasehash

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36201)* status: :shipit: complete! ✓

**Pull request merged**
