### PR TITLE
[feat]: [CDS-78125]: Adding the utils changes required for supporging V0 stages/steps in V1 pipelines

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52148)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52148)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-Ncznlu48cpIndGdAiOo:-Ncznlu48cpIndGdAiOp:bdyolvu) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java#L19)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class PlanCreatorConstants {
>   public final String NEXT_ID = "nextId";
> ```

@shalini-agr i think you added these constants, Can you make change to adopt these as these are plan creator constant and not yaml
___
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorUtils.java` line 221 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-NcznzwT19uGydTsKu58:-NcznzwT19uGydTsKu59:bhmrujd) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorUtils.java#L221)):*
> ```Java
> 
>   public String getNextIdFromDependency(Dependency dependency, KryoSerializer kryoSerializer) {
>     if (dependency != null && dependency.getMetadataMap().containsKey(PlanCreatorConstants.NEXT_ID)) {
> ```

Can you add changes to support both map, @shalini-agr can help
___
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtilsV1.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-NczoGnQ74Hq2dP8EMhH:-NczoGnQ74Hq2dP8EMhI:b-gazydj) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtilsV1.java#L36)):*
> ```Java
>           Dependency.newBuilder()
>               .putMetadata(
>                   PlanCreatorConstants.YAML_VERSION, ByteString.copyFrom(kryoSerializer.asBytes(PipelineVersion.V1)))
> ```

how parent is deciding its child is v0 or v1?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 134 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-NczoWv3-Suq_F_jRMcj:-NczoWv3-Suq_F_jRMck:b-lj0hyt) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L134)):*
> ```Java
> 
>       String siblingFieldUuid = PlanCreatorUtils.getNextIdFromDependency(dependency, kryoSerializer);
>       if (EmptyPredicate.isEmpty(siblingFieldUuid)) {
> ```

@brijeshdhakar can we discuss this once?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepPlanCreatorUtils.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-Nczoeao1kyfSdfML-AZ:-Nczoeao1kyfSdfML-A_:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/PmsStepPlanCreatorUtils.java#L154)):*
> ```Java
> 
>       String nextNodeId = PlanCreatorUtils.getNextIdFromDependency(dependency, kryoSerializer);
>       if (EmptyPredicate.isEmpty(nextNodeId)) {
> ```

same as above

**Comment by shalini-agr** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-Ncznlu48cpIndGdAiOo:-Nd-68l08dKd6N0-YCPb:bqo3405) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/884-pms-commons/src/main/java/io/harness/pms/plan/creation/PlanCreatorConstants.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr i think you added these constants, Can you make change to adopt these as these are plan creator constant and not yaml
</blockquote></details>

sure, will make those changes once this PR is merged.

**Comment by brijeshdhakar** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtilsV1.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-NczoGnQ74Hq2dP8EMhH:-Nd-b03gD9W4mGBk_67Z:briaxfx) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtilsV1.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

how parent is deciding its child is v0 or v1?
</blockquote></details>

Based on the structure of child its deciding.
For example stepPlanCreator knows that the children is v0 if it has {- step: {props}} and v1 if its like {- props}. Similarly for the stage.

And except for array nodes(stages/steps), a node will have its children of same version. V1 will have V1 child and V0 will have V0. 
Please check the StepsPlanCreatorV1 changes in this pr https://github.com/harness/harness-core/pull/52146

**Comment by brijeshdhakar** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtilsV1.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/52148#-NczoGnQ74Hq2dP8EMhH:-Nd-bpLT9bJFf0H6Neyk:bkopr3i) ([raw file](https://github.com/harness/harness-core/blob/128b91fb7ac49694d2ebf8ee39d63da9bfcc07de/884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtilsV1.java#L36)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Based on the structure of child its deciding.
For example stepPlanCreator knows that the children is v0 if it has {- step: {props}} and v1 if its like {- props}. Similarly for the stage.

And except for array nodes(stages/steps), a node will have its children of same version. V1 will have V1 child and V0 will have V0. 
Please check the StepsPlanCreatorV1 changes in this pr https://github.com/harness/harness-core/pull/52146
</blockquote></details>

For example stepPlanCreator -> For example stepsPlanCreator. Its stepsPlanCreator and not stepPlanCreator in the above comment

**Pull request closed without merging**
