### PR TITLE
feat: [CDS-36107]: add API to get templates resolved pipeline yaml

### PR DESCRIPTION
**Pull request by inderschera**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 718 at r1](https://reviewable.io/reviews/harness/harness-core/32119#-N-1kpOx2ajtT5UrMwEq:-N-1kpOx2ajtT5UrMwEr:b-fe4yv1) ([raw file](https://github.com/harness/harness-core/blob/72baa67e4bbe4d375d92b344266a37ac95fffa18/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L718)):*
> ```Java
>         TemplatesResolvedPipelineResponseDTO.builder()
>             .resolvedTemplatesPipelineYaml(templateResolvedPipelineYaml)
>             .yamlPipeline(pipelineYaml)
> ```

the caller already have original yaml, why to return this?



_Code quote:_
```Java
yamlPipeline(pipelineYaml)
```

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/32119#-N-1lneZ1QzuiXlOhj1l:-N-1lneZ1QzuiXlOhj1m:bbkyxey) ([raw file](https://github.com/harness/harness-core/blob/72baa67e4bbe4d375d92b344266a37ac95fffa18/890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java#L20)):*
> ```Java
> @Data
> @Builder
> public class TemplatesResolvedPipelineResponseDTO {
> ```

add schema annotation with description to the fields if you plan to expose to customer later

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 718 at r1](https://reviewable.io/reviews/harness/harness-core/32119#-N-1kpOx2ajtT5UrMwEq:-N-1l9xB-fIyTo4GlYUu:btrpxe6) ([raw file](https://github.com/harness/harness-core/blob/72baa67e4bbe4d375d92b344266a37ac95fffa18/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L718)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

the caller already have original yaml, why to return this?
</blockquote></details>

@archit-harness I believe they don't have. Consider the case when they open run form directly from pipeline list page.
Also, if they had, I think they could have directly called applyTemplates api then.
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java, line 20 at r1](https://reviewable.io/reviews/harness/harness-core/32119#-N-1lneZ1QzuiXlOhj1l:-N-1pvNL9J6gIGZSASew:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72baa67e4bbe4d375d92b344266a37ac95fffa18/890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java#L20)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

add schema annotation with description to the fields if you plan to expose to customer later
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1. unresolved discussions.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1 change requests. 1. unresolved discussions. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java, line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32119#-N-1rvRUDJk_zC7l85ZD:-N-1rvRUDJk_zC7l85ZE:b-ruw60c) ([raw file](https://github.com/harness/harness-core/blob/8c94086abf6692e19b98b56f96cb4ee1ea9ab3e6/890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java#L21)):*
> ```Java
> @Data
> @Builder
> @Schema(name = "TemplatesResolvedPipelineResponse")
> ```

add description here as well

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java, line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32119#-N-1rvRUDJk_zC7l85ZD:-N-1uXZU01C2VZc7_6X1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c94086abf6692e19b98b56f96cb4ee1ea9ab3e6/890-pms-contracts/src/main/java/io/harness/pms/pipeline/TemplatesResolvedPipelineResponseDTO.java#L21)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

add description here as well
</blockquote></details>

Done.

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32119)* status: 1 change requests. 0 of 1 approvals obtained.

**Pull request merged**
