### PR TITLE
fix: [CDS-83318]: use node group to get TemplateEntityType for v1 and rootYamlName for v0

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** use node group to get TemplateEntityType for v1 and rootYamlName for v0

**Testing:** 
- Tested templates/schema/templateSchema API
- open api for templates schema 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Comment by brijeshdhakar** [comment]
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/55155#-NiogOgm9_QLVDDpSAdR:-NiogOgm9_QLVDDpSAdS:b17a706) ([raw file](https://github.com/harness/harness-core/blob/8121e2effb3ec126c5a41ccc7b9eeb269d053b51/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L119)):*
> ```Java
> 
>   @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
>   public static TemplateEntityType getTemplateType(@JsonProperty("type") String yamlType) {
> ```

@shalini-agr this will be called while deserialisation right. So for time being we might use the wrong type in yaml and the illegalArgException might come. But when all changes are done then this exception should not come right. And we can remove this if else condition correct?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/55155#-NiogOgm9_QLVDDpSAdR:-Nirf1DD8VfpPmVQ2tNC:b3ctxn0) ([raw file](https://github.com/harness/harness-core/blob/8121e2effb3ec126c5a41ccc7b9eeb269d053b51/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L119)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@shalini-agr this will be called while deserialisation right. So for time being we might use the wrong type in yaml and the illegalArgException might come. But when all changes are done then this exception should not come right. And we can remove this if else condition correct?
</blockquote></details>

yes, for deserialization it is only used by v0 but this method is also called by another method in the get templates list API, so, we can't remove this try catch because we want to show both v0 and v1 templates in the list.

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/55155#-Nisf93yDQURnm_E__wM:-Nisf93yDQURnm_E__wN:b-yhhs7b) ([raw file](https://github.com/harness/harness-core/blob/1ad58feb9baf49b99146a7373e80d6dda0295d6c/template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java#L42)):*
> ```Java
>       String templateChildType) {
>     JsonNode schema = ngTemplateSchemaService.getIndividualStaticSchema(
>         templateEntityType.getRootYamlName(), templateChildType, "v0");
> ```

nit: add comment that we will remove this fallback after few releases.
___
*[`template-service/service/src/main/java/io/harness/template/resources/SchemasApiImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/55155#-NisfW3T4tPj3mfwf-3u:-NisfW3U5MAQ1jFXobE6:b232m7z) ([raw file](https://github.com/harness/harness-core/blob/1ad58feb9baf49b99146a7373e80d6dda0295d6c/template-service/service/src/main/java/io/harness/template/resources/SchemasApiImpl.java#L56)):*
> ```Java
>   public Response getTemplateSchema(String nodeGroup, String nodeType, String harnessAccount, String version) {
>     ObjectNode schema = ngTemplateSchemaService.getIndividualStaticSchema(nodeGroup, nodeType, version);
>     if (schema == null) {
> ```

once UI also adapts to the change then we can remove the below code right?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/55155#-Nisf93yDQURnm_E__wM:-NispU-79z2p4z_zQkbl:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ad58feb9baf49b99146a7373e80d6dda0295d6c/template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java#L42)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

nit: add comment that we will remove this fallback after few releases.
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/resources/SchemasApiImpl.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/55155#-NisfW3T4tPj3mfwf-3u:-Nisp_sh2KeNUkq2nd5o:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1ad58feb9baf49b99146a7373e80d6dda0295d6c/template-service/service/src/main/java/io/harness/template/resources/SchemasApiImpl.java#L56)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

once UI also adapts to the change then we can remove the below code right?
</blockquote></details>

done

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/55155#-NiogOgm9_QLVDDpSAdR:-NjLm842EVw8MXmRR_iC:bj2y1vw) ([raw file](https://github.com/harness/harness-core/blob/8121e2effb3ec126c5a41ccc7b9eeb269d053b51/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L119)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

yes, for deserialization it is only used by v0 but this method is also called by another method in the get templates list API, so, we can't remove this try catch because we want to show both v0 and v1 templates in the list.
</blockquote></details>

needs further discussion
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/55155#-NjLiPHp4QelsfKmWd1n:-NjLiPHp4QelsfKmWd1o:b-wi1muz) ([raw file](https://github.com/harness/harness-core/blob/be9fcd8b54c03d13359c3ecc0aa677858b9cb583/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L78)):*
> ```Java
>   private final String yamlType;
>   // root yaml name to be added in pipeline yaml while merging template yaml v0 eg: step, stage, stepGroup, etc.
>   private String rootYamlName;
> ```

add suffix v0
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/55155#-NjLlpHn0jswIND_oZJU:-NjLlpHn0jswIND_oZJV:by9rx2q) ([raw file](https://github.com/harness/harness-core/blob/be9fcd8b54c03d13359c3ecc0aa677858b9cb583/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L99)):*
> ```Java
>       case HarnessYamlVersion.V0:
>         for (TemplateEntityType value : TemplateEntityType.values()) {
>           if (value.rootYamlName.equalsIgnoreCase(yamlType)) {
> ```

earlier we were using yamlType so we should use it



_Code quote:_
```Java
rootYamlName
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/55155#-NjLiPHp4QelsfKmWd1n:-NjM0Vl_2HoDEGjTjZc3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/393dbd83158eff3d0eef51a72e6981fe4f52b29c/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L78)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add suffix v0
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 99 at r4](https://reviewable.io/reviews/harness/harness-core/55155#-NjLlpHn0jswIND_oZJU:-NjM0W0AEPRmwzJL82KI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/393dbd83158eff3d0eef51a72e6981fe4f52b29c/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L99)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

earlier we were using yamlType so we should use it
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 7 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/55155#-NiogOgm9_QLVDDpSAdR:-NjRG2Vf-v4l3eE10Aqb:b-fg7k6c) ([raw file](https://github.com/harness/harness-core/blob/8121e2effb3ec126c5a41ccc7b9eeb269d053b51/960-ng-core-beans/src/main/java/io/harness/ng/core/template/TemplateEntityType.java#L119)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

needs further discussion
</blockquote></details>

removed the catch block from here as it will be only called for v0

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55155)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
