### PR TITLE
[fix]: [CDS-67998]: Unsetting the resolvedParams

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Describe your changes

Context - 
The stepParameters get resolved after the step begins but before the execution input is given by the user. Here the variables test2 and test3 are still not given by the user and hence the value of these variables is getting resolved to null in the stepParameters which is getting used at the time of resolution during step execution.

Fix - 
Unsetting the resolvedParams so that it gets populated with the correct user given inputs once the execution resumes. 

Testing - 
Screenshot 2023-08-28 at 9 49 30 PM
Screenshot 2023-08-28 at 9 49 01 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)

### CODE REVIEW

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52143#-NcznNZ04ZUEUVifAsp0:-NcznNZ04ZUEUVifAsp1:b-h15q96) ([raw file](https://github.com/harness/harness-core/blob/c7e55868b97c0c83333f901604dfbee0767d4b08/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L105)):*
> ```Java
>   public void notify(Map<String, ResponseData> response) {
>     nodeExecutionService.updateStatusWithOps(nodeExecutionId, Status.QUEUED,
>         ops -> ops.unset(NodeExecutionKeys.resolvedParams), EnumSet.of(Status.INPUT_WAITING));
> ```

UT is missing for it

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52143#-NcznNZ04ZUEUVifAsp0:-NcznQ2_25lT-8X8KjQu:b-wgjix1) ([raw file](https://github.com/harness/harness-core/blob/c7e55868b97c0c83333f901604dfbee0767d4b08/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

UT is missing for it
</blockquote></details>

@brijeshdhakar please review

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52143#-NcznNZ04ZUEUVifAsp0:-Nd-SZsb8rJhg9uDY1ex:bxav34d) ([raw file](https://github.com/harness/harness-core/blob/c7e55868b97c0c83333f901604dfbee0767d4b08/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar please review
</blockquote></details>

@vtxorxwitty can we sync up once how does this solve the issue?

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52143#-NcznNZ04ZUEUVifAsp0:-Nd-h_7I2MX_K2gujBjy:b1fyikf) ([raw file](https://github.com/harness/harness-core/blob/c7e55868b97c0c83333f901604dfbee0767d4b08/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L105)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@vtxorxwitty can we sync up once how does this solve the issue?
</blockquote></details>

Synched up. Looks good.

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/52143#-NcznNZ04ZUEUVifAsp0:-Nd0GXrw9yqIxt5Md-HF:b-upbg5h) ([raw file](https://github.com/harness/harness-core/blob/c7e55868b97c0c83333f901604dfbee0767d4b08/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L105)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Synched up. Looks good.
</blockquote></details>

Done. Added UTs

**Comment by vtxorxwitty** [comment]
trigger ut2

**Comment by vtxorxwitty** [comment]
trigger ut3

**Comment by vtxorxwitty** [comment]
trigger ut7

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/52143#-Nd0P2DN0blerYuFJigX:-Nd0P2DN0blerYuFJigY:b-pi9d9n) ([raw file](https://github.com/harness/harness-core/blob/4033412fcf1ba8f90d3ae159d79963174d60133a/120-ng-manager/config.yml#L280)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}
> ```

remove this

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/52143#-Nd0P2DN0blerYuFJigX:-Nd0bt0EDMwv28g-AnYX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4033412fcf1ba8f90d3ae159d79963174d60133a/120-ng-manager/config.yml#L280)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

**Comment by vtxorxwitty** [comment]
trigger ut0

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 1. unresolved discussions.

**Comment by vtxorxwitty** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52143)* status: 1. unresolved discussions.

**Pull request merged**
