### PR TITLE
techdebt: [CDS-84452]: cleanup code for FF GITOPS_UPDATE_APP_STEP

### PR DESCRIPTION
**Pull request by shivagowda**
.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56145)

### CODE REVIEW

**Review by mankrit-singh — APPROVED** [review]

**Comment by shivagowda** [comment]
trigger ut9

**Comment by shivagowda** [comment]
trigger messagecheck

**Comment by shivagowda** [comment]
trigger review

**Review by thisrohangupta — APPROVED** [review]

**Comment by shivagowda** [comment]
trigger review

**Pull request merged**
