### PR TITLE
feat: [PL-28477]: Added logs for account setup

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added logs during account setup process. Logs added for the following steps:-
1. Account event received
2. Account update/delete/restore event start
3. Default org creation
4. Default project creation
5. Global SM creation
6. Harness SM creation
7. Rbac setup

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38191)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38191)

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38191)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/38191#-NDCsWfaDw-vfhwL8s3s:-NDCsWfaDw-vfhwL8s3t:b-t0djpy) ([raw file](https://github.com/harness/harness-core/blob/81a1f78df0eacd4ce74551310be45af36059f275/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L62)):*
> ```Java
>                 String.format("Exception in unpacking EntityChangeDTO for key %s", message.getId()), e);
>           }
>           String action = metadataMap.get(ACTION);
> ```

Capture in log the start of handling account event. Also capture action as part of the log.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/38191#-NDCs9Mx61goxVXGbSJ5:-NDCs9Mx61goxVXGbSJ6:baicbj7) ([raw file](https://github.com/harness/harness-core/blob/81a1f78df0eacd4ce74551310be45af36059f275/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L89)):*
> ```Java
>         "[AccountSetupListener]: Received account update event for account %s", accountEntityChangeDTO.getAccountId()));
>     AccountDTO account = CGRestUtils.getResponse(accountClient.getAccountDTO(accountEntityChangeDTO.getAccountId()));
>     if (account.isNextGenEnabled()) {
> ```

Add log capturing the start of account setup.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/38191#-NDCsJtyC31rt9UCcfyA:-NDCsJtyC31rt9UCcfyB:bpk0h98) ([raw file](https://github.com/harness/harness-core/blob/81a1f78df0eacd4ce74551310be45af36059f275/120-ng-manager/src/main/java/io/harness/ng/core/event/NGAccountSetupService.java#L119)):*
> ```Java
>     if (!accountOrgProjectValidator.isPresent(accountIdentifier, null, null)) {
>       log.info(String.format(
>           "[NGAccountSetupService]: Account with accountIdentifier %s not found, skipping creation of Default Organization",
> ```

Reword to NGAccountSetup everywhere

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38191)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/38191#-NDCsWfaDw-vfhwL8s3s:-NDmA7YDBgDPhoNOtHyl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81a1f78df0eacd4ce74551310be45af36059f275/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L62)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Capture in log the start of handling account event. Also capture action as part of the log.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/38191#-NDCs9Mx61goxVXGbSJ5:-NDmA9_jA4XZVlf00hCm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81a1f78df0eacd4ce74551310be45af36059f275/120-ng-manager/src/main/java/io/harness/ng/core/event/AccountSetupListener.java#L89)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add log capturing the start of account setup.
</blockquote></details>

Done.

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38191)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38191)* status: Some of the checks are too old.

**Review by VikasMaddukuriHarness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38191#-:-NDmJe1tBQwDOC05XOJ6:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38191)* status: :shipit: complete! ✓

**Pull request merged**
