### PR TITLE
[Fix]: [CDS-67986]: Improve the unclear error message

### PR DESCRIPTION
**Pull request by yagyanshbhatia**
Context: 
This message is displayed if someone tries to trigger a pipeline which has already been executed/aborted. This could happen if someone hits the API or has multiple tabs open.. and tries to run pipeline once, lets say aborts, and then hits the API to run.
API returns error: Expected parent to be in list

I have discussed this with sudarshan purohit and made changes according to his suggestions. 

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47459)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 339 at r1](https://reviewable.io/reviews/harness/harness-core/47459#-NUrnaT72H7ODZ50_WD0:-NUrnaT72H7ODZ50_WD1:b-rgwhw1) ([raw file](https://github.com/harness/harness-core/blob/8801ab23e9a9a56eddaaf2c1d5115706de52e76f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L339)):*
> ```Java
>                         .filter(ne -> ne.getUuid().equals(parentId))
>                         .findFirst()
>                         .orElseThrow(() -> new UnexpectedException("Pipeline has already completed execution")));
> ```

Looks like drastic change in message. Can we add some context to the JIRA and PR to better understand the change.

**Comment by yagyanshbhatia** [comment]
Thanks @mohitg0795 . Added context at the top of this PR.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 339 at r1](https://reviewable.io/reviews/harness/harness-core/47459#-NUrnaT72H7ODZ50_WD0:-NUv3DWi6Hc-s7EbyXVY:b-t5mwi2) ([raw file](https://github.com/harness/harness-core/blob/8801ab23e9a9a56eddaaf2c1d5115706de52e76f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L339)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Looks like drastic change in message. Can we add some context to the JIRA and PR to better understand the change.
</blockquote></details>

Thanks for adding context to the PR. I think we are changing the message at wrong place. The earlier message looks correct in given context of the code. If we are sending something back to UI, that should be handled better on downstream layer and not in core piece of functional code. 
Do we know who's exactly owner of this method or who has best context on it? We can further discuss once with them.

**Comment by yagyanshbhatia** [comment]
trigger messagecheck

**Comment by yagyanshbhatia** [comment]
> _[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 339 at r1](https://reviewable.io/reviews/harness/harness-core/47459#-NUrnaT72H7ODZ50_WD0:-NUv3DWi6Hc-s7EbyXVY:b-t5mwi2) ([raw file](https://github.com/harness/harness-core/blob/8801ab23e9a9a56eddaaf2c1d5115706de52e76f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L339)):_
> 
> Previously, mohitg0795 (Mohit Garg) wrote…
> Thanks for adding context to the PR. I think we are changing the message at wrong place. The earlier message looks correct in given context of the code. If we are sending something back to UI, that should be handled better on downstream layer and not in core piece of functional code. Do we know who's exactly owner of this method or who has best context on it? We can further discuss once with them.

I discussed it with @sahilhindwani-harness , we think that this message sufficiently conveys the intent of information that we would want the exception to provide, as well as make relevant sense to the customer. Discussed more on this in person. Please let me know if you have any more concerns or we can close it.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47459)* status: :shipit: complete! ✓

**Comment by yagyanshbhatia** [comment]
trigger uts

**Comment by yagyanshbhatia** [comment]
trigger messagecheck, review

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47459)* status: :shipit: complete! ✓

**Comment by yagyanshbhatia** [comment]
trigger messagecheck, review

**Comment by inderschera** [comment]
trigger messagecheck

**Comment by yagyanshbhatia** [comment]
trigger messagecheck

**Comment by yagyanshbhatia** [comment]
trigger review

**Pull request merged**
