### PR TITLE
fix: [CDS-53074]: added db artifact check for gcs artifacts

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)

### CODE REVIEW

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/BuildSourceResource.java` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/43834#-NNwqrwS1hbEqemKAkNu:-NNwqrwS1hbEqemKAkNv:b-whiket) ([raw file](https://github.com/harness/harness-core/blob/41326e7bf7011065a136a3d19ce13c03a522eef1/400-rest/src/main/java/software/wings/resources/BuildSourceResource.java#L261)):*
> ```Java
>             artifactService.listArtifactsByArtifactStreamId(artifactStream.getAccountId(), artifactStreamId);
> 
>         if (featureFlagService.isEnabled(SPG_ALLOW_FILTER_BY_PATHS_GCS, artifactStream.getAccountId())
> ```

We need add unit test Move the code to ArtifactService in a new method like listArtifactByArtifactStreamIdAndFilterPath this will help in write unit test cases.

**Comment by rafaelmart1ns** [comment]
trigger tiAll

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: Some of the checks are too old. 5 file(s) to review. 1 of 2 approvals obtained.

**Review by franciscojuniorharness — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: Some of the checks are too old. 1 file(s) to review.

**Comment by rafaelmart1ns** [comment]
trigger tiAll

**Comment by rafaelmart1ns** [comment]
trigger ut0,ut1,ut2,ut3,ut4

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: Some of the checks are too old. 1 file(s) to review.

**Review by Fernando-Dourado — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834#-:-NOtcd7Q8OUmwknUUA2I:bnfp4nl)* status: Some of the checks are too old.

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: Some of the checks are too old.

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: 1 file(s) to review.

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: 1 file(s) to review.

**Review by Fernando-Dourado — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834#-:-NOtvz1v65qPt471W_BI:bnfp4nl)* status: 1 file(s) to review.

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43834)* status: :shipit: complete! ✓

**Pull request merged**
