### PR TITLE
[feat]: [SRM-13782]: Next Gen Health Source Refactoring and ELK v2 persist.

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43524)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43524)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParamValuesRequest.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_Qw9hBIlP1G96XbZ3:-NN_Qw9hBIlP1G96XbZ4:bseij1r) ([raw file](https://github.com/harness/harness-core/blob/cf8d58dd7327788208e3c17adee7f047c78f0d30/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParamValuesRequest.java#L27)):*
> ```Java
> 
>   public void validate() {
>     if (providerType == MonitoredServiceDataSourceType.ELASTICSEARCH) {
> ```

Are we removing this check because this validation is applicable for all health sources?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_QmGrCpmvD7cdyhiR:-NN_QmGrCpmvD7cdyhiS:b-f4jxda) ([raw file](https://github.com/harness/harness-core/blob/e7fbf23e045456c3f88b2d30f0e00b16dda6ac9f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L136)):*
> ```Java
>     });
>     if (dataSourceType.getVerificationType() == VerificationType.LOG) {
>       if (dataSourceType == DataSourceType.ELASTICSEARCH) {
> ```

We should move validations specific to Elk to the helper class
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/NextGenHealthSourceHelper.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_RUgsBHCEje8C9FHg:-NN_RUgsBHCEje8C9FHh:b-hnzu2f) ([raw file](https://github.com/harness/harness-core/blob/e7fbf23e045456c3f88b2d30f0e00b16dda6ac9f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/NextGenHealthSourceHelper.java#L19)):*
> ```Java
> import java.util.List;
> 
> public interface NextGenHealthSourceHelper {
> ```

Can we add a validate method too, it will help us provide impl for validation specific to the health source in the helper itself
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ElasticSearchLogNextGenHealthSourceHelper.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_RmqX7EQ9G6botloR:-NN_RmqX7EQ9G6botloS:b-855ka9) ([raw file](https://github.com/harness/harness-core/blob/e7fbf23e045456c3f88b2d30f0e00b16dda6ac9f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ElasticSearchLogNextGenHealthSourceHelper.java#L52)):*
> ```Java
>       HealthSourceParamValuesRequest healthSourceParamValuesRequest, ProjectParams projectParams) {
>     if (QueryParamsDTO.QueryParamKeys.index.equals(healthSourceParamValuesRequest.getParamName())) {
>       DataCollectionRequest<? extends ConnectorConfigDTO> request = ELKIndexCollectionRequest.builder().build();
> ```

nit: We can extract out these methods for better readability.

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43524)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParamValuesRequest.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_Qw9hBIlP1G96XbZ3:-NN_VLwmA3drApYY5C8A:ba1z4zw) ([raw file](https://github.com/harness/harness-core/blob/cf8d58dd7327788208e3c17adee7f047c78f0d30/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/HealthSourceParamValuesRequest.java#L27)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Are we removing this check because this validation is applicable for all health sources?
</blockquote></details>

yes this check is true for all health sources.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_QmGrCpmvD7cdyhiR:-NN_VOj-5fEfsaN9XyE5:b-4sn3m0) ([raw file](https://github.com/harness/harness-core/blob/e7fbf23e045456c3f88b2d30f0e00b16dda6ac9f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NextGenHealthSourceSpec.java#L136)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We should move validations specific to Elk to the helper class
</blockquote></details>

I didn't want to do every refactoring and create thousand line PR, will take up validations in next PR.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/NextGenHealthSourceHelper.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/43524#-NN_RUgsBHCEje8C9FHg:-NN_Vcsc9Cg8Y8IUKPxW:bqjr5io) ([raw file](https://github.com/harness/harness-core/blob/e7fbf23e045456c3f88b2d30f0e00b16dda6ac9f/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/NextGenHealthSourceHelper.java#L19)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Can we add a validate method too, it will help us provide impl for validation specific to the health source in the helper itself
</blockquote></details>

will take that up in next PR

**Review by dhruv-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43524)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43524)* status: :shipit: complete! ✓

**Pull request merged**
