### PR TITLE
feat: [IDP-264]: Unit tests: Provision module

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45336)

### CODE REVIEW

**Comment by vigneswara-propelo** [comment]
trigger ut8

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45336)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/status/k8s/PodHealthCheck.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxjRRWATJDp64ELmPR:-NQxjRRWATJDp64ELmPS:by9m8i0) ([raw file](https://github.com/harness/harness-core/blob/e154253df313fcfaea66f556d4fc0b37ef89d991/idp-service/src/main/java/io/harness/idp/status/k8s/PodHealthCheck.java#L41)):*
> ```Java
>   @Inject private K8sClient k8sClient;
> 
>   private static final String LABEL_SELECTOR = "app=idp-ui";
> ```

Is there a use case where this could be different? Since we ourselves are deploying idp UI as well



_Code quote:_
```Java
app=idp-ui
```
___
*[`idp-service/src/test/java/io/harness/idp/provision/resource/ProvisionApiImplTest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxkMIz7nk5TUMzVTFr:-NQxkMIz7nk5TUMzVTFs:b-d90nwb) ([raw file](https://github.com/harness/harness-core/blob/c4bca505138f879406b852babde0c7b161d5413d/idp-service/src/test/java/io/harness/idp/provision/resource/ProvisionApiImplTest.java#L51)):*
> ```Java
>     when(namespaceService.saveAccountIdNamespace(ACCOUNT_ID)).thenReturn(namespaceEntity);
>     doNothing().when(provisionService).triggerPipelineAndCreatePermissions(ACCOUNT_ID, NAMESPACE);
>     Response response = provisionApiImpl.provisionIdp(ACCOUNT_ID);
> ```

Can we add a test to check the exception case?
___
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxk5MP-koI6CyTK6Xo:-NQxk5MP-koI6CyTK6Xp:b9puy51) ([raw file](https://github.com/harness/harness-core/blob/c4bca505138f879406b852babde0c7b161d5413d/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L33)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public class ProvisionServiceImplTest {
> ```

Are we planning to add tests for other methods?

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45336)* status: 9 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/status/k8s/PodHealthCheck.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxjRRWATJDp64ELmPR:-NQxq3wo2TB1HVRlax51:bj1nit7) ([raw file](https://github.com/harness/harness-core/blob/e154253df313fcfaea66f556d4fc0b37ef89d991/idp-service/src/main/java/io/harness/idp/status/k8s/PodHealthCheck.java#L41)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Is there a use case where this could be different? Since we ourselves are deploying idp UI as well
</blockquote></details>

For now, the label doesn't change. But if in future if we are planning to change it, Sandeepa suggested that we can prefer changing config files instead of hot-fixing it
___
*[`idp-service/src/test/java/io/harness/idp/provision/resource/ProvisionApiImplTest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxkMIz7nk5TUMzVTFr:-NQxrhI4Ecw0zNOSdfts:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/c4bca505138f879406b852babde0c7b161d5413d/idp-service/src/test/java/io/harness/idp/provision/resource/ProvisionApiImplTest.java#L51)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add a test to check the exception case?
</blockquote></details>

sure
___
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxk5MP-koI6CyTK6Xo:-NQxqnv31LfTrhCt-Iwa:b-b9mmkt) ([raw file](https://github.com/harness/harness-core/blob/c4bca505138f879406b852babde0c7b161d5413d/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L33)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Are we planning to add tests for other methods?
</blockquote></details>

Thought UT for makeTriggerApi() is not needed as it is specific for calling the webhook trigger and we wont be having much response data to verify.
Will add UT for createDefaultPermissions method

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45336)* status: 9 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/test/java/io/harness/idp/provision/resource/ProvisionApiImplTest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxkMIz7nk5TUMzVTFr:-NQyNrud7M_AY-1dECi5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c4bca505138f879406b852babde0c7b161d5413d/idp-service/src/test/java/io/harness/idp/provision/resource/ProvisionApiImplTest.java#L51)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

sure
</blockquote></details>

done
___
*[`idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/45336#-NQxk5MP-koI6CyTK6Xo:-NQyNXM--T74PEMsgW73:b-5z3mqo) ([raw file](https://github.com/harness/harness-core/blob/c4bca505138f879406b852babde0c7b161d5413d/idp-service/src/test/java/io/harness/idp/provision/service/ProvisionServiceImplTest.java#L33)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

Thought UT for makeTriggerApi() is not needed as it is specific for calling the webhook trigger and we wont be having much response data to verify.
Will add UT for createDefaultPermissions method
</blockquote></details>

connected with @sarthakkasat he is currently adding UT for createDefaultPermissions in his PR

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45336)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45336)* status: :shipit: complete! ✓

**Pull request merged**
