### PR TITLE
feat: [IDP-271]: Migration code for Plugins Metadata

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45518)

### CODE REVIEW

**Review by vigneswara-propelo — COMMENTED** [review]
We need not add it in MigrationList if we are using NGMigration.
We just need to add the migration number in IdpBGMigrationDetails
References: PopulateYamlAuthFieldInNGJiraConnectorMigration
Please check this documentation for more details: https://harness.atlassian.net/wiki/spaces/DX/pages/1601798145/NG+Migration+Framework+Adoption 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518#-:-NRGR2rTC6MvJ8_BPgth:b2trlhi)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 20 of 24 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpMigrationProvider.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/45518#-NRGYK-z4G8Yv4OB57lh:-NRGYK0-7kQo0QA-YRLL:bj0pxm5) ([raw file](https://github.com/harness/harness-core/blob/8e12693ccc4c56f37442f184846492590d7c6344/idp-service/src/main/java/io/harness/idp/migration/IdpMigrationProvider.java#L20)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.IDP)
> public class IdpMigrationProvider implements MigrationProvider {
> ```

Wouldn't this run only once? Didn't we have the use-case of running it every time idp-service starts?
___
*[`idp-service/src/main/java/io/harness/idp/plugin/services/PluginInfoServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45518#-NRGYtA03aFlJfoX3QgW:-NRGYtA03aFlJfoX3QgX:bul4r68) ([raw file](https://github.com/harness/harness-core/blob/8e12693ccc4c56f37442f184846492590d7c6344/idp-service/src/main/java/io/harness/idp/plugin/services/PluginInfoServiceImpl.java#L42)):*
> ```Java
>   private PluginInfoRepository pluginInfoRepository;
>   private ConfigManagerService configManagerService;
>   private static final List<String> pluginIds = List.of("pager-duty", "snyk-security", "harness-ci-cd");
> ```

Wondering if we can have this list in a constants file or as an enum?

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518)* status: 24 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/migration/IdpMigrationProvider.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/45518#-NRGYK-z4G8Yv4OB57lh:-NRG_Zc41bD-WjfRS0LY:b-yfago1) ([raw file](https://github.com/harness/harness-core/blob/8e12693ccc4c56f37442f184846492590d7c6344/idp-service/src/main/java/io/harness/idp/migration/IdpMigrationProvider.java#L20)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Wouldn't this run only once? Didn't we have the use-case of running it every time idp-service starts?
</blockquote></details>

we need not run this every time. We just need to run this again only if there is any change in the plugin schema. For that we are maintaining the migration number
___
*[`idp-service/src/main/java/io/harness/idp/plugin/services/PluginInfoServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45518#-NRGYtA03aFlJfoX3QgW:-NRG_umW5WsLjeFnVj14:b-hxmmpn) ([raw file](https://github.com/harness/harness-core/blob/8e12693ccc4c56f37442f184846492590d7c6344/idp-service/src/main/java/io/harness/idp/plugin/services/PluginInfoServiceImpl.java#L42)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Wondering if we can have this list in a constants file or as an enum?
</blockquote></details>

Thought about it as well, but currently we are using it only in this file.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518)* status: 25 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/plugin/services/PluginInfoServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45518#-NRGYtA03aFlJfoX3QgW:-NRGnD2L0zCKo7bt6iYV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8e12693ccc4c56f37442f184846492590d7c6344/idp-service/src/main/java/io/harness/idp/plugin/services/PluginInfoServiceImpl.java#L42)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

Thought about it as well, but currently we are using it only in this file.
</blockquote></details>

done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518)* status: 25 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by vigneswara-propelo — COMMENTED** [review]
:lgtm:

> Reviewed 19 of 24 files at r1, 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518#-:-NRGyFR88HePoAmoocfP:bnfp4nl)* status: 25 file(s) to review.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 19 of 24 files at r1, 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45518)* status: :shipit: complete! ✓

**Pull request merged**
