### PR TITLE
fix: [PL-24155]: fix H2g resolve errors

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31851)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 45 at r1](https://reviewable.io/reviews/harness/harness-core/31851#-MzKlboy-Nt1t_CPHSLZ:-MzKlboy-Nt1t_CPHSL_:b2ux6re) ([raw file](https://github.com/harness/harness-core/blob/e3f3516790e2b246dd97fec6cf7bbb667764be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L45)):*
> ```Java
>             Pageable pageable = PageRequest.of(pageIdx, pageSize);
>             Query query = new Query().with(pageable);
>             List<GitSyncError> gitSyncErrorList = mongoTemplate.find(query, GitSyncError.class);
> ```

Isn't there any simple way to fetch documents in batches like HIterator in CG. This seems too complex.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 75 at r1](https://reviewable.io/reviews/harness/harness-core/31851#-MzKlmQr9_bp-gxi3x4l:-MzKlmQr9_bp-gxi3x4m:b150j2u) ([raw file](https://github.com/harness/harness-core/blob/e3f3516790e2b246dd97fec6cf7bbb667764be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L75)):*
> ```Java
>                 Update update = update(GitSyncErrorKeys.completeFilePath, newFilePath);
>                 Criteria criteria = Criteria.where(GitSyncErrorKeys.uuid).is(gitSyncError.getUuid());
>                 gitSyncErrorRepository.updateError(criteria, update);
> ```

We should update in batch

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 53 at r1](https://reviewable.io/reviews/harness/harness-core/31851#-MzKr9YV2tYd7YqpfZJk:-MzKr9YV2tYd7YqpfZJl:bnz2hh9) ([raw file](https://github.com/harness/harness-core/blob/e3f3516790e2b246dd97fec6cf7bbb667764be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L53)):*
> ```Java
>                updateCompleteFilePath(gitSyncErrorList);
>             } catch (DuplicateKeyException ex) {
>                 // this would happen when migration is run for the second time
> ```

lets log the error here as well so that we know it occurred for some given record

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 45 at r1](https://reviewable.io/reviews/harness/harness-core/31851#-MzKlboy-Nt1t_CPHSLZ:-MzKwlsI56UejAMgm3G-:b-8n7cnw) ([raw file](https://github.com/harness/harness-core/blob/e3f3516790e2b246dd97fec6cf7bbb667764be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L45)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Isn't there any simple way to fetch documents in batches like HIterator in CG. This seems too complex.
</blockquote></details>

I didn't find any other simple way
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 53 at r1](https://reviewable.io/reviews/harness/harness-core/31851#-MzKr9YV2tYd7YqpfZJk:-MzKwkLIDi9UAgoAWtIN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e3f3516790e2b246dd97fec6cf7bbb667764be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets log the error here as well so that we know it occurred for some given record
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 75 at r1](https://reviewable.io/reviews/harness/harness-core/31851#-MzKlmQr9_bp-gxi3x4l:-MzKwktz1ejZEynFbkP6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e3f3516790e2b246dd97fec6cf7bbb667764be5f/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L75)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should update in batch
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/31851#-MzL9-fd1PJmCxql3xXE:-MzL9-fd1PJmCxql3xXF:b-upo50l) ([raw file](https://github.com/harness/harness-core/blob/6caee740366322c95e2a1d6b0b805c88a9d03af9/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L48)):*
> ```Java
>       try {
>         updateCompleteFilePath(gitSyncErrorList);
>         gitSyncErrorRepository.saveAll(gitSyncErrorList);
> ```

Are u sure saveAll will not throw DuplicateKeyException if an unchanged documented is saved again.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/31851#-MzL9-fd1PJmCxql3xXE:-MzMO7_m8ZsnnOk9nQ0M:bbbrtwh) ([raw file](https://github.com/harness/harness-core/blob/6caee740366322c95e2a1d6b0b805c88a9d03af9/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L48)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Are u sure saveAll will not throw DuplicateKeyException if an unchanged documented is saved again.
</blockquote></details>

I did a basic check. saveAll isn't helping us in anyway here. Its a one-by-one save internally. Also, as its a usual save call, no issue should occur with respect to changes.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java, line 48 at r2](https://reviewable.io/reviews/harness/harness-core/31851#-MzL9-fd1PJmCxql3xXE:-MzOrYQYEiNTo022D4NJ:b-oqsu5h) ([raw file](https://github.com/harness/harness-core/blob/6caee740366322c95e2a1d6b0b805c88a9d03af9/136-git-sync-manager/src/main/java/io/harness/gitsync/migration/GitSyncErrorCompleteFilePathMigration.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I did a basic check. saveAll isn't helping us in anyway here. Its a one-by-one save internally. Also, as its a usual save call, no issue should occur with respect to changes.
</blockquote></details>

yes, it is not throwing any exception

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851#-:-MzP3B1a-_C9suBHB1v1:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851#-:-MzP3Dq14fQD-6hLrO4J:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31851#-:-MzUMWd1CwhwzzlA5_1c:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
