### PR TITLE
[feat]: [CET-1036] Adding License module for CET.

### PR DESCRIPTION
**Pull request by cseverino789**
## Describe your changes

This is PR is to add licensing to the new Continuous Error Tracking Module. It follows the same pattern as modules being added. Note that the Trial will only initially support Enterprise and PLG subscriptions will be supported later.

Similar PR:
https://github.com/harness/harness-core/pull/44210

## Checklist
- [ X] I've documented the changes in the PR description.
- [ X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)

### CODE REVIEW

**Comment by cseverino789** [comment]
trigger feature-build

**Review by ricksjames — APPROVED** [review]

**Comment by cseverino789** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/CETModuleLicenseClient.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/45626#-NRZgbmeEFuLHMG1cSZC:-NRZkPvs23X2M6nGBHQ5:bra2dka) ([raw file](https://github.com/harness/harness-core/blob/079fb386336c8b5486f13932e536a40c5d786b7b/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/CETModuleLicenseClient.java#L16)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

should be ModuleLicenseClient<CETModuleLicenseDTO> here
</blockquote></details>

Looking at the other clients do you mean some thing like below?



_Code snippet:_
```Java

public interface CETModuleLicenseClient extends ModuleLicenseClient<CETModuleLicenseDTO>
```

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/CETModuleLicenseClient.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/45626#-NRZgbmeEFuLHMG1cSZC:-NRZoiN4B5Eg85ISSein:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/079fb386336c8b5486f13932e536a40c5d786b7b/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/CETModuleLicenseClient.java#L16)):*
<details><summary><i>Previously, cseverino789 (Corey Severino) wrote…</i></summary><blockquote>

Looking at the other clients do you mean some thing like below?
</blockquote></details>

Yes

**Comment by cseverino789** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CETLocalClient.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/45626#-NRZh7_18PQ5qnGjHGIl:-NRZuWhR949OOjDGqzvY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/079fb386336c8b5486f13932e536a40c5d786b7b/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CETLocalClient.java#L40)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

If CED does not support TEAM and FREE edition, then these two empty cases should be removed, it will fall into default case, otherwise it will cause issue.
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ModuleType.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/45626#-NR_ynXO504bzdcoExGd:-NR_ynXO504bzdcoExGe:b-ypjsbi) ([raw file](https://github.com/harness/harness-core/blob/3a7123a236bcea792963be083bdcf4f20dc5154c/970-ng-commons/src/main/java/io/harness/ModuleType.java#L37)):*
> ```Java
>   @JsonProperty("SRM") SRM("Service Reliability Management", PUBLIC, ONBOARDED),
>   @JsonProperty("IACM") IACM("Infrastructure as Code Manager", PUBLIC, ONBOARDED),
>   @JsonProperty("CET") CET("Continuous Error Tracking", PUBLIC, ONBOARDED),
> ```

This should be 
@JsonProperty("CET") CET("Continuous Error Tracking", INTERNAL, ONBOARDING_IN_PROGRESS)
OR
@JsonProperty("CET") CET("Continuous Error Tracking", PUBLIC, ONBOARDING_IN_PROGRESS)

First time you are onboarding a module, it starts with ONBOARDING_IN_PROGRESS state. Once services (such as access control) are deployed with this enum, then you can change it to ONBOARDED and start using it.

If we don't do this, it will break services. Because other services won't be able to recognize CET module

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)* status: :shipit: complete! ✓

**Comment by Xin-Harness** [comment]
Please kindly attach the test result as well.

**Comment by cseverino789** [comment]
[cet-module-testing.csv](https://github.com/harness/harness-core/files/11094395/cet-module-testing.csv)

> Please kindly attach the test result as well.

I ran through the NG licenses and CG Account endpoints in both a local and PR env for testing.

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)* status: 1 change requests. 1. unresolved discussions.

**Comment by cseverino789** [comment]
trigger ut2

**Review by shashank-harness — APPROVED** [review]
> Reviewed 4 of 19 files at r1, 9 of 11 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)* status: 1 change requests. 1. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 19 files at r1, 9 of 11 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626#-:-NRfATjb3r2IDWn8eHhQ:bnfp4nl)* status: :shipit: complete! ✓

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 4 of 19 files at r1, 9 of 11 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45626)* status: :shipit: complete! ✓

**Pull request merged**
