### PR TITLE
feat: [CDS-77593]: add repoName filter for service details

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. add repo name filter for service details. Used on the Services Page (project level) 
2. add git params for reconciliation on service configuration page. 

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53341)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger review

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1329 at r2](https://reviewable.io/reviews/harness/harness-core/53341#-NfFLeDF8Uw5c2zvvUzx:-NfFLeDGBZyO_Li-cpvs:b-mie6gn) ([raw file](https://github.com/harness/harness-core/blob/3f60641705375e9f9eb5a19b6267f932f3c945c1/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1329)):*
> ```Java
>       }
>       Page<ServiceEntity> pageResponse = serviceEntityService.list(criteria, pageRequest);
>       if (pageResponse.isEmpty()) {
> ```

we should also check if the length of contents is less than page size to break from the loop

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53341)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
trigger uts

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53341)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1319 at r2](https://reviewable.io/reviews/harness/harness-core/53341#-NfFLt229hL0LWH7N5n0:-NgpAeNI5o6PRnaPLxRh:b-89rjll) ([raw file](https://github.com/harness/harness-core/blob/3f60641705375e9f9eb5a19b6267f932f3c945c1/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1319)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets query in batch size of 1000 only
PL team recently mandated that we do not fetch large amounts of Data in 1 DB call, hence they updated all Resource class to have MAX_LIMIT = 1000, lets follow that
</blockquote></details>

DONE.
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1329 at r2](https://reviewable.io/reviews/harness/harness-core/53341#-NfFLeDF8Uw5c2zvvUzx:-NgpAgXA5M5hkIkVcdul:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3f60641705375e9f9eb5a19b6267f932f3c945c1/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1329)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should also check if the length of contents is less than page size to break from the loop
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53341)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
