### PR TITLE
fix: [CDS-49431]: Added support for Azure Repo connector project type.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Added support for azure project type connector to fetch manifest files.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42005)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42005)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42005)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 376 at r3](https://reviewable.io/reviews/harness/harness-core/42005#-NKWyo1BAL1-5gE4Mamw:-NKWyo1C-5xYthCVyWlZ:b8v41cg) ([raw file](https://github.com/harness/harness-core/blob/b22230231c6f1a831acd0a932b39e25c517085ea/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L376)):*
> ```Java
>       if (gitConfigDTO.getGitConnectionType() == GitConnectionType.ACCOUNT) {
>         String repoUrl = getGitRepoUrl(gitConfigDTO, repoName);
>         gitConfigDTO.setUrl(repoUrl);
> ```

we are duplicating code here, only thing that differs is the way how to calculate repoUrl. No need to repeat the `setUrl` and `setGitConnectionType`. We can encapsulate the logic that handles account or project within the getGitRepoUrl and have another method for getConnectionType.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42005)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42005)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42005)* status: :shipit: complete! ✓

**Pull request merged**
