### PR TITLE
[techdebt]: [PIE-2871]: Add descriptions to fields in Input Set DTOs

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)

### CODE REVIEW

**Review by vtxorxwitty — APPROVED** [review]

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java, line 33 at r1](https://reviewable.io/reviews/harness/harness-core/30948#-MwaTFlEEpY7bShPaZJU:-MwaTFlEEpY7bShPaZJV:b-go1kw0) ([raw file](https://github.com/harness/harness-core/blob/31ca978bc46b2f2142f0b1bc5b439a447c046f61/890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java#L33)):*
> ```Java
> @Schema(name = "MergeInputSetResponse", description = "View of the Response of Merging of Input Sets of a Pipeline")
> public class MergeInputSetResponseDTOPMS {
>   @Schema(description = "Merged YAML of all the Input Sets") String pipelineYaml;
> ```

This is not pipeline yaml?
___
*[890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30948#-MwaTMGL26fESgBpdq0Z:-MwaTMGL26fESgBpdq0_:b-egvsn8) ([raw file](https://github.com/harness/harness-core/blob/31ca978bc46b2f2142f0b1bc5b439a447c046f61/890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java#L34)):*
> ```Java
> public class MergeInputSetResponseDTOPMS {
>   @Schema(description = "Merged YAML of all the Input Sets") String pipelineYaml;
>   @Schema(description = "Merged YAML of all the Input Sets, merged into the full Pipeline YAML")
> ```

Pipeline Yaml after Input Sets merge?
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 29 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweDwiA5E3b1ALcrElN:-MweDwiB4PjRbakq3Z8J:b-odg024) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L29)):*
> ```Java
>   String UPDATED_AT_MESSAGE = "Time at which the entity was last updated";
>   String GIT_DETAILS_MESSAGE = "This contains the Git Details of the entity if the Project is Git enabled";
>   String GIT_VALIDITY_MESSAGE = "This contains Validity Details of the Entity";
> ```

what's this validity details?
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweEH1F5DFxPCiWM5A5:-MweEH1F5DFxPCiWM5A6:braakbb) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L34)):*
> ```Java
>   String END_TIME_EPOCH_PARAM_MESSAGE = "End Date Epoch time in ms";
> 
>   String PIPELINE_ID_FOR_INPUT_SET_PARAM_MESSAGE = "Pipeline Identifier for the entity.";
> ```

can we rename the constant to PIPELINE_ID as the message is generally applicable for all entities?
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweDGck-t1SoTdiwWH2:-MweDGcm4o_tNyT7xGR7:b-nvbgyf) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L37)):*
> ```Java
>   String RUNTIME_INPUT_TEMPLATE_MESSAGE = "Runtime Input template for the Pipeline";
>   String INPUT_SET_ID_MESSAGE = "Input Set Identifier";
>   String INPUT_SET_NAME_MESSAGE = "Input Set Name";
> ```

can we create a new constants file for input set constants? Don't want to bloat this one
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweF5Uo2pKp-rLZPkI-:-MweF5Uo2pKp-rLZPkI0:b5fkzzv) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L45)):*
> ```Java
>       "Type of Input Set needed: \"INPUT_SET\", or \"OVERLAY_INPUT_SET\", or \"ALL\". If nothing is sent, ALL is considered.";
>   String INPUT_SET_TAGS_MESSAGE = "Input Set tags";
>   String INPUT_SET_OUTDATED_MESSAGE =
> ```

"This field is true if a Pipeline update removed some runtime inputs that were defined in the Input Set." How about this message? This seems more relevant to me as a user.
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweG5pDAFXIe5iEyTC_:-MweG5pDAFXIe5iEyTCa:b3g6g1t) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L47)):*
> ```Java
>   String INPUT_SET_OUTDATED_MESSAGE =
>       "This field is true if a Pipeline update has made this Input Set invalid, and cannot be used for Pipeline Execution";
>   String INPUT_SET_ERROR_MESSAGE = "This field is true if an Input Set did not get saved";
> ```

"This field is true if an Input Set had errors and hence could not be saved"
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 48 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweGSLpE3mGzc6wtG3n:-MweGSLpE3mGzc6wtG3o:biz38oh) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L48)):*
> ```Java
>       "This field is true if a Pipeline update has made this Input Set invalid, and cannot be used for Pipeline Execution";
>   String INPUT_SET_ERROR_MESSAGE = "This field is true if an Input Set did not get saved";
>   String OVERLAY_INPUT_SET_ERROR_MESSAGE = "This field is true if an Overlay Input Set did not get saved";
> ```

"This field is true if an Overlay Input Set had errors and hence could not be saved"

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: 13 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java, line 33 at r1](https://reviewable.io/reviews/harness/harness-core/30948#-MwaTFlEEpY7bShPaZJU:-MweKynD9dyZ10kt0B3f:b93p5lp) ([raw file](https://github.com/harness/harness-core/blob/31ca978bc46b2f2142f0b1bc5b439a447c046f61/890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java#L33)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

This is not pipeline yaml?
</blockquote></details>

Yes it isn't. The fieldname is confusing yes, we can change it in the next sprint if you want
___
*[890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30948#-MwaTMGL26fESgBpdq0Z:-MweL4QGAcF9819fvZpA:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/31ca978bc46b2f2142f0b1bc5b439a447c046f61/890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java#L34)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Pipeline Yaml after Input Sets merge?
</blockquote></details>

Yes
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 29 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweDwiA5E3b1ALcrElN:-MweL5sVACS9JHm_njX5:buyt8ha) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L29)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

what's this validity details?
</blockquote></details>

Updated the message
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweEH1F5DFxPCiWM5A5:-MweL7pe1wEOwzx1R56c:b-9vqf3s) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L34)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can we rename the constant to PIPELINE_ID as the message is generally applicable for all entities?
</blockquote></details>

I had made this similar to other messages like "Project identifier for the entity". And this message is only for entities that are children to a pipeline, which is nothing other than input sets.
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 37 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweDGck-t1SoTdiwWH2:-MweLK2WBSc95dexOGgX:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L37)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can we create a new constants file for input set constants? Don't want to bloat this one
</blockquote></details>

Done
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 45 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweF5Uo2pKp-rLZPkI-:-MweLLTh-jbbQhJa6lY9:b-cy9yoj) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L45)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

"This field is true if a Pipeline update removed some runtime inputs that were defined in the Input Set." How about this message? This seems more relevant to me as a user.
</blockquote></details>

The message you're saying is for input sets but not for overlay input sets, its better to have a message that fits both of these because they come together in the list view.
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 47 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweG5pDAFXIe5iEyTC_:-MweLVZr3EOUukLmU1Dw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L47)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

"This field is true if an Input Set had errors and hence could not be saved"
</blockquote></details>

Done.
___
*[890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java, line 48 at r3](https://reviewable.io/reviews/harness/harness-core/30948#-MweGSLpE3mGzc6wtG3n:-MweLVvUBiPFX9JUeF8E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed62c19e62f524c714dfd9bea5e6d2957deb9c10/890-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L48)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

"This field is true if an Overlay Input Set had errors and hence could not be saved"
</blockquote></details>

Done.

**Comment by namanvermah** [comment]
trigger ti1

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 2 of 3 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30948#-MwaTMGL26fESgBpdq0Z:-MwjRm12A6HP5xIYoIyl:bmaeydi) ([raw file](https://github.com/harness/harness-core/blob/31ca978bc46b2f2142f0b1bc5b439a447c046f61/890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java#L34)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

"Pipeline YAML after merging with the Input Sets"?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java, line 34 at r1](https://reviewable.io/reviews/harness/harness-core/30948#-MwaTMGL26fESgBpdq0Z:-MwjT7T2DNIdIxAt1lvi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31ca978bc46b2f2142f0b1bc5b439a447c046f61/890-pms-contracts/src/main/java/io/harness/pms/inputset/MergeInputSetResponseDTOPMS.java#L34)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

"Pipeline YAML after merging with the Input Sets"?
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 2 of 3 files at r2, 5 of 8 files at r4, 1 of 1 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30948)* status: :shipit: complete! ✓

**Pull request merged**
