### PR TITLE
feat: [CDS-40413]: prune yaml git config

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35990)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35990)

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35990)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/sync/YamlGitConfigServiceImpl.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/35990#-N8ZI8Jk41ukhX4aoOEA:-N8ZI8Jk41ukhX4aoOEB:b-rasgfv) ([raw file](https://github.com/harness/harness-core/blob/294ef874988e08b0e176c8088fe6c23dcf687863/400-rest/src/main/java/software/wings/service/impl/yaml/sync/YamlGitConfigServiceImpl.java#L169)):*
> ```Java
>   @Override
>   public void deleteByAccountId(String accountId) {
>     boolean delete = wingsPersistence.delete(
> ```

variable name delete should be changed

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35990)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/sync/YamlGitConfigServiceImpl.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/35990#-N8ZI8Jk41ukhX4aoOEA:-N8bYBuj3X7C12UkDmZT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/294ef874988e08b0e176c8088fe6c23dcf687863/400-rest/src/main/java/software/wings/service/impl/yaml/sync/YamlGitConfigServiceImpl.java#L169)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

variable name delete should be changed
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/sync/YamlGitConfigServiceImpl.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/35990#-N8ZItcwCXao567cyNxr:-N8bYCZLDruJGePjrtd5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/294ef874988e08b0e176c8088fe6c23dcf687863/400-rest/src/main/java/software/wings/service/impl/yaml/sync/YamlGitConfigServiceImpl.java#L171)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

since delete is boolean it will be "Deleted true yaml ...."
</blockquote></details>

Done.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35990)* status: :shipit: complete! ✓

**Pull request merged**
