### PR TITLE
Feat: [PL-23707]: Add missing error handling for create webhook SCM API

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31834)

### CODE REVIEW

**Review by goelsatyam2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31834)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java, line 632 at r1](https://reviewable.io/reviews/harness/harness-core/31834#-MzJNF3k3xJXOKCMkh0c:-MzJNF3k3xJXOKCMkh0d:b86671b) ([raw file](https://github.com/harness/harness-core/blob/80bfd286db2a6fe6fcc78a94ef12b8854f17d43c/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L632)):*
> ```Java
> 
>   @VisibleForTesting
>   protected CreateWebhookRequest getCreateWebhookRequest(String slug, Provider gitProvider,
> ```

is it possible to pass the correct/invalid argument from the test case itself? so that we don't have to move the function to protected

**Comment by mohitg0795** [comment]
___
*[952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java, line 632 at r1](https://reviewable.io/reviews/harness/harness-core/31834#-MzJNF3k3xJXOKCMkh0c:-MzKoHVs-8BnnTC9sDtC:b-qpf5zk) ([raw file](https://github.com/harness/harness-core/blob/80bfd286db2a6fe6fcc78a94ef12b8854f17d43c/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L632)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Agreed with the concern here. I did check once and AFAIR, there was another method call inside which had complex logic. Let me take a look at it again if this can be improved.
</blockquote></details>

Handled it now. Done.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31834)* status: 1 change requests. 1. unresolved discussions.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31834)* status: 1 change requests. 1. unresolved discussions.

**Review by goelsatyam2 — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31834)* status: 1. unresolved discussions.

**Review by goelsatyam2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31834)* status: :shipit: complete! ✓

**Pull request merged**
