### PR TITLE
[feat]: [PIE-7412]: Add a method to update pipelineBranchName field in trigger

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
## Describe your changes
Add a method to update pipelineBranchName field in trigger. A request by pipeline team where they want a method which they can call and update pipelineBranchName field in trigger

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)

### CODE REVIEW

**Review by vcalasansh — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1141 at r1](https://reviewable.io/reviews/harness/harness-core/42923#-NMTzJ_5-icyrSmuxc3K:-NMTzJ_68qd3pEmdujn5:b1xhbax) ([raw file](https://github.com/harness/harness-core/blob/38ad7c904de892022a18111753e1c6c4d513847c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1141)):*
> ```Java
>         if (Objects.equals(operationType, GitOperationType.INLINE_TO_REMOTE)) {
>           try {
>             YamlField yamlField = YamlUtils.readTree(triggerEntity.getYaml());
> ```

Could we add a more generic method for updating / removing fields from trigger yaml, and use it here? Maybe we could change `updateEntityYmlWithEnabledValue` in `NGTriggerElementMapper` to be a more generic method and use it here.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1169 at r1](https://reviewable.io/reviews/harness/harness-core/42923#-NMU-bft0Ylbq0AXmFry:-NMU-bft0Ylbq0AXmFrz:b44r1kk) ([raw file](https://github.com/harness/harness-core/blob/38ad7c904de892022a18111753e1c6c4d513847c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1169)):*
> ```Java
> 
>   private void updateTriggerEntityPipelineBranchName(NGTriggerEntity triggerEntity) {
>     Criteria criteria = Criteria.where(NGTriggerEntityKeys.accountId)
> ```

Can't we use the `update` method instead? Maybe add a new param to it controlling if it should perform the "postUpsert" flow or not (I think the postUpsert flow should not be performed for this use-case).
If you agree with the suggestion above, we could make this call to `update` method directly inside the `updateBranchName` method - then pipeline team would have to call only one method from triggers to make the update happen. Also, I think we should update all trigger entries with a single request in the DB (send a batch update request).

**Review by vcalasansh — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 8 file(s) to review. 0 of 2 approvals obtained.

**Review by vcalasansh — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/GitOperationType.java` line 17 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMborGNDzrInZSFNRYv:-NMborGNDzrInZSFNRYw:b-tumfh1) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/GitOperationType.java#L17)):*
> ```Java
> 
> @OwnedBy(SPG)
> public enum GitOperationType {
> ```

This should be GitMoveOperationType

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1153 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbrpLfEEiC9p7HEI6i:-NMbrpLfEEiC9p7HEI6j:b-s4lwjp) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1153)):*
> ```Java
>           listOfUpdatedTriggers.add(triggerEntity);
>         } catch (Exception e) {
>           log.error("Error performing yaml operations for Trigger: " + TriggerHelper.getTriggerRef(triggerEntity));
> ```

log the exception as well, also log the operation name clearly that it failed during updating branch name operation

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbs4TF5qp30GgZEOvV:-NMbs4TF5qp30GgZEOvW:b-kau6mc) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java#L128)):*
> ```Java
>       bulkOperations.execute();
>     } catch (Exception ex) {
>       log.error("Error while updating trigger yaml", ex);
> ```

why are we consuming exception here? How will service layer get to know whether operation failed or succeeded?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1145 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbsU7c0m3T-1O-RiZz:-NMbsU7c0m3T-1O-Ri_-:b-l7g5y2) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1145)):*
> ```Java
>           YamlNode triggerNode = yamlField.getNode().getField("trigger").getNode();
>           if (Objects.equals(operationType, GitOperationType.INLINE_TO_REMOTE)) {
>             ((ObjectNode) triggerNode.getCurrJsonNode()).put("pipelineBranchName", pipelineBranchName);
> ```

we should use constants for yaml fieldnames

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1133 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbt1hO12HOCFnY9onh:-NMbt1hO12HOCFnY9oni:bw4bfv1) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1133)):*
> ```Java
>   }
> 
>   public void updateBranchName(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

Instead of void, I think we should return a complex response struct which mentions status of successfully updated triggers and failure cases as well otherwise it may be misleading.

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 8 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1145 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbsU7c0m3T-1O-RiZz:-NMc0NIfD5Oyz4L98lW7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1145)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should use constants for yaml fieldnames
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1153 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbrpLfEEiC9p7HEI6i:-NMc0OD56qhCTGAIQIPb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1153)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log the exception as well, also log the operation name clearly that it failed during updating branch name operation
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbs4TF5qp30GgZEOvV:-NMc0PP_-kZ5CylHAwmY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java#L128)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we consuming exception here? How will service layer get to know whether operation failed or succeeded?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/GitOperationType.java` line 17 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMborGNDzrInZSFNRYv:-NMbt6XZ0aUjCOoVeCd8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/GitOperationType.java#L17)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This should be GitMoveOperationType
</blockquote></details>

Done.

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 9 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1133 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbt1hO12HOCFnY9onh:-NMcNlzy4i5MZLb9DWW_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1133)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Instead of void, I think we should return a complex response struct which mentions status of successfully updated triggers and failure cases as well otherwise it may be misleading.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1153 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbrpLfEEiC9p7HEI6i:-NMcOOsSEJ2NfUyfEowr:b-up9kaw) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1153)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still the error log is unclear, its very generic. We should mention the operation during which it failed. eg: "Error performing updateBranchName operation on triggers"

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 9 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1153 at r4](https://reviewable.io/reviews/harness/harness-core/42923#-NMbrpLfEEiC9p7HEI6i:-NMcSCYS-i0XDcC4vM0J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cd2f6f53b690daec135be970a2ba37e211e7a9b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1153)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Still the error log is unclear, its very generic. We should mention the operation during which it failed. eg: "Error performing updateBranchName operation on triggers"
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1161 at r9](https://reviewable.io/reviews/harness/harness-core/42923#-NMcYaqRBvnANItXxucY:-NMcYaqS8bBNNZVPmPPM:bcunqo0) ([raw file](https://github.com/harness/harness-core/blob/8860c6ae1c80b5beb39c461ab9105b6108bf6ef1/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1161)):*
> ```Java
>       }
> 
>       long successTriggerUpdateCount = ngTriggerRepository.updateTriggerYaml(listOfUpdatedTriggers);
> ```

why are we getting only success count from repo layer method? The repo layer method should be generic enough to send back proper response with success and failed count, then it can be used anywhere else as well whenever required.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1156 at r9](https://reviewable.io/reviews/harness/harness-core/42923#-NMcYqKf03wl9WEAZbCK:-NMcYqKf03wl9WEAZbCL:b-n7kyj2) ([raw file](https://github.com/harness/harness-core/blob/8860c6ae1c80b5beb39c461ab9105b6108bf6ef1/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1156)):*
> ```Java
>         } catch (Exception e) {
>           log.error(
>               "Error performing updateBranchName operation on trigger: " + TriggerHelper.getTriggerRef(triggerEntity),
> ```

btw, in what case will this exception block be called? I mean what are the cases when it can fail to write the proper yaml?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java` line 99 at r9](https://reviewable.io/reviews/harness/harness-core/42923#-NMcZ7AV8wRsvS2YS_qN:-NMcZ7AV8wRsvS2YS_qO:bompmmb) ([raw file](https://github.com/harness/harness-core/blob/8860c6ae1c80b5beb39c461ab9105b6108bf6ef1/pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/NGTriggerRepositoryCustomImpl.java#L99)):*
> ```Java
> 
>   @Override
>   public long updateTriggerYaml(List<NGTriggerEntity> ngTriggerEntityList) {
> ```

this method should itself return success and failure operation counts.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 1156 at r9](https://reviewable.io/reviews/harness/harness-core/42923#-NMcYqKf03wl9WEAZbCK:-NMckx1o3Fmh6H3Bp6CE:bpe5gef) ([raw file](https://github.com/harness/harness-core/blob/8860c6ae1c80b5beb39c461ab9105b6108bf6ef1/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L1156)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

          YamlField yamlField = YamlUtils.readTree(triggerEntity.getYaml());
when yamlutils read or write failes
</blockquote></details>

If this exception occurs, then we should count it as a failure in the final update response. We are ignoring it currently.

**Review by vcalasansh — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 1 of 4 files at r6, 2 of 5 files at r8, 2 of 3 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 6 files at r2, 1 of 5 files at r5, 1 of 4 files at r6, 2 of 5 files at r8, 2 of 3 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42923)* status: :shipit: complete! ✓

**Pull request merged**
