### PR TITLE
[feat]: [CDS-68200]: Unsent the stepParmaeters in case of IdentityStepNode.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Changes: Incase of IdentityPlanNode now with this change not sending step parameters while emitting orchestration event.
Testing: Local (Errors were not produced after this fix.)

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48009)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 252 at r3](https://reviewable.io/reviews/harness/harness-core/48009#-NViUQ-PBXITU8bhzHxc:-NViUQ-PBXITU8bhzHxd:bhp88b5) ([raw file](https://github.com/harness/harness-core/blob/cbf71419db389bfe98332bb8737ecbc5656bd774/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L252)):*
> ```Java
>     Optional<Level> stageLevel = Optional.empty();
>     for (Level level : ambiance.getLevelsList()) {
>       if (level.getStepType().getStepCategory() == StepCategory.STAGE || Objects.equals(level.getGroup(), "STAGE")) {
> ```

use constants

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 713 at r3](https://reviewable.io/reviews/harness/harness-core/48009#-NViVqkdAmqeaiGZ0GZ-:-NViVqkdAmqeaiGZ0GZ0:b1vdd9e) ([raw file](https://github.com/harness/harness-core/blob/cbf71419db389bfe98332bb8737ecbc5656bd774/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L713)):*
> ```Java
> 
>     if (nodeExecution.getResolvedStepParameters() != null && nodeExecution.getNodeType() != null
>         && nodeExecution.getNodeType() != NodeType.IDENTITY_PLAN_NODE) {
> ```

I see condition here and in prev comment is exactly same, possible to put it inside method?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48009)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 252 at r3](https://reviewable.io/reviews/harness/harness-core/48009#-NViUQ-PBXITU8bhzHxc:-NVjXgE61NVtI51dEnJM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cbf71419db389bfe98332bb8737ecbc5656bd774/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L252)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

use constants
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 713 at r3](https://reviewable.io/reviews/harness/harness-core/48009#-NViVqkdAmqeaiGZ0GZ-:-NVjXiEOAC9uQ_jcYYd7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cbf71419db389bfe98332bb8737ecbc5656bd774/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L713)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see condition here and in prev comment is exactly same, possible to put it inside method?
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48009)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
