### PR TITLE
fix: [CDS-46794]: Environment Info is not available in MultiService MultiInfra Gitops Deployment

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Earlier there was handling for single environment to be shown in stage level module info because regular (non gitops ) deployments support only 1 per stage
This PR adds a new POJO to the ModuleInfo called `GitopsExecutionSummary`  so that multi environment information can be captured per stage
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40527)

### CODE REVIEW

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40527)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java` line 307 at r1](https://reviewable.io/reviews/harness/harness-core/40527#-NHZdr8NDj8zjBiVcZLr:-NHZdr8NDj8zjBiVcZLs:b-vxrrxl) ([raw file](https://github.com/harness/harness-core/blob/a34aad2f7124c6686d2bc140c8eeea8e773654b7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java#L307)):*
> ```Java
>   }
> 
>   static class Pair<T> {
> ```

This doesn't seem to be used? can we remove.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40527)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40527)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java` line 307 at r1](https://reviewable.io/reviews/harness/harness-core/40527#-NHZdr8NDj8zjBiVcZLr:-NH_rOLX3ccU1qku0NzI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a34aad2f7124c6686d2bc140c8eeea8e773654b7/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java#L307)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This doesn't seem to be used? can we remove. 
</blockquote></details>

Done.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40527)* status: :shipit: complete! ✓

**Pull request merged**
