### PR TITLE
feat: [CDS-45910]: support template linking in sidecar artifact

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39557)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39557)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39557)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarArtifact.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/39557#-NGFrUIt7p2dVsWJGOpZ:-NGFrUIt7p2dVsWJGOp_:bf68wpf) ([raw file](https://github.com/harness/harness-core/blob/59651f1fa32ef3be8a4cef3e7a6bfa72bc67f58a/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarArtifact.java#L47)):*
> ```Java
> @SimpleVisitorHelper(helperClass = SidecarArtifactVisitorHelper.class)
> @TypeAlias("sidecarArtifact")
> @OneOfField(fields = {"spec", "template"})
> ```

nit: should it be type or template?

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39557)* status: 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarArtifact.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/39557#-NGFrUIt7p2dVsWJGOpZ:-NGGhJlO080jszhiA5pc:b-owuoyh) ([raw file](https://github.com/harness/harness-core/blob/59651f1fa32ef3be8a4cef3e7a6bfa72bc67f58a/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/SidecarArtifact.java#L47)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: should it be type or template?
</blockquote></details>

added since we will have either one of template node or spec node

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39557)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39557)* status: :shipit: complete! ✓

**Pull request merged**
