### PR TITLE
[feat]: [CDS-69996]: change v1 overrides get api to not get v2 types of overrides

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes
* added condition of having non null yaml for service overrides v1 apis
* add ng setting condition in service step

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48947)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/48947#-NXPQVg28Ze87LTmfETd:-NXPQVg28Ze87LTmfETe:b-18bwux) ([raw file](https://github.com/harness/harness-core/blob/5152f7bd2496048097532929061c500e8d99b0b0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L1107)):*
> ```Java
>   private boolean isOverridesV2Enabled(String accountId, String orgId, String projectId) {
>     return ngFeatureFlagHelperService.isEnabled(accountId, FeatureName.CDS_SERVICE_OVERRIDES_2_0)
>         && NGRestUtils
> ```

should we not use the below method 
```
isOverridesV2SettingEnabled(String accountId, String orgId, String projectId)
``` ?
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/spring/ServiceOverrideRepository.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/48947#-NXPQnx-CsGavvhpk6G7:-NXPQnx-CsGavvhpk6G8:b5xpj53) ([raw file](https://github.com/harness/harness-core/blob/5152f7bd2496048097532929061c500e8d99b0b0/127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/spring/ServiceOverrideRepository.java#L26)):*
> ```Java
>   @Query(
>       value =
>           "{ 'accountId': ?0, 'orgIdentifier': ?1, 'projectIdentifier': ?2, 'environmentRef': ?3, 'serviceRef': ?4, 'type': ?5, 'yaml': { '$exists': true, '$ne': null } }")
> ```

why we do have ```'$ne': null``` ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48947)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/48947#-NXPQVg28Ze87LTmfETd:-NXPRNDd3VfsEhfS9fUh:btuvyn0) ([raw file](https://github.com/harness/harness-core/blob/5152f7bd2496048097532929061c500e8d99b0b0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L1107)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not use the below method 
```
isOverridesV2SettingEnabled(String accountId, String orgId, String projectId)
``` ?
```

</blockquote></details>

PLan is to remove FF after development.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48947)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/spring/ServiceOverrideRepository.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/48947#-NXPQnx-CsGavvhpk6G7:-NXPRSWBAXF77hYv-VnA:b-ft1llv) ([raw file](https://github.com/harness/harness-core/blob/5152f7bd2496048097532929061c500e8d99b0b0/127-cd-nextgen-entities/src/main/java/io/harness/repositories/serviceoverride/spring/ServiceOverrideRepository.java#L26)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why we do have ```'$ne': null``` ?
</blockquote></details>

just to be double check that someone has not save override with yaml null.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/48947#-NXPQVg28Ze87LTmfETd:-NXPRpen1qbJ0mP8t1wv:b-ltwvsy) ([raw file](https://github.com/harness/harness-core/blob/5152f7bd2496048097532929061c500e8d99b0b0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L1107)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

No I meant that 
shouldn't the above method be 
```
return     return ngFeatureFlagHelperService.isEnabled(accountId, FeatureName.CDS_SERVICE_OVERRIDES_2_0)
        && isOverridesV2SettingEnabled 
``` 
</blockquote></details>

```
```
return     return ngFeatureFlagHelperService.isEnabled(accountId, FeatureName.CDS_SERVICE_OVERRIDES_2_0)
        && isOverridesV2SettingEnabled(accountId, orgId, projectId)
```
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48947)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 1107 at r2](https://reviewable.io/reviews/harness/harness-core/48947#-NXPQVg28Ze87LTmfETd:-NXPVZCwBsG2o0esLi4b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5152f7bd2496048097532929061c500e8d99b0b0/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L1107)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

```
```
return     return ngFeatureFlagHelperService.isEnabled(accountId, FeatureName.CDS_SERVICE_OVERRIDES_2_0)
        && isOverridesV2SettingEnabled(accountId, orgId, projectId)
```
```

</blockquote></details>

Done.

**Review by lovish1999 — COMMENTED** [review]
LGTM

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48947)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
trigger uts

**Pull request merged**
