### PR TITLE
feat: [DEL-6238]: Delegate DB migration in smp

### PR DESCRIPTION
**Pull request by AnupamIO**
Adding migration for migrating to delegate db in smp.

Testing:
1- Tested with taking data from QA env and ran migration on local.
2- Tested rollback scenarios.
3- Tested on smp test env
https://harness.atlassian.net/wiki/spaces/DEL/pages/21291370861/Test+strategy+for+DB+migration

Please note that while creating indexes, few collection which are labelled as @StoreIn(DbAliases.ALL) will also be created in dms-db, however these collections will be empty.

Screenshot 2023-05-05 at 12 00 24 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)

### CODE REVIEW

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_54cXD2FjQiN3rvK6:-NT_54cXD2FjQiN3rvK7:bf5zuln) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L63)):*
> ```Java
> 
>     // Check if we already did the migration
>     if (persistence.isMigrationEnabled(ON_PREM_MIGRATION)) {
> ```

does this mean migration has happened ?  if so, rename to ON_PREM_MIGRATION_DONE
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_7VKODPRlRko3cRhW:-NT_7VKODPRlRko3cRhX:b-zanfts) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L131)):*
> ```Java
>     int insertDocCount = 0;
> 
>     try (HIterator<PersistentEntity> records = new HIterator<>(query.fetch())) {
> ```

records in runtime contains only 1 item, correct ? 
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_7oY_AcdOQPYu5GXz:-NT_7oY_AcdOQPYu5GY-:btobo3j) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L160)):*
> ```Java
>   }
> 
>   private boolean verifyWriteOperation(int insertCount, String collection) {
> ```

during the time of migration, won't new insert go to the old collection ? 

in this case, the count of old collection maybe should calculated right before migration starts

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_8Xz5CWjWJdKA5JNh:-NT_8Xz5CWjWJdKA5JNi:b-l9acg5) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L160)):*
> ```Java
>   }
> 
>   private boolean verifyWriteOperation(int insertCount, String collection) {
> ```

mongo provides a way to do dbHash, https://www.mongodb.com/docs/manual/reference/command/dbHash/#dbhash. 
do you think it's better to use this, as it provides md5 for the entire collection

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_54cXD2FjQiN3rvK6:-NTlqNPD2SwADc18le4g:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L63)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

does this mean migration has happened ?  if so, rename to ON_PREM_MIGRATION_DONE
</blockquote></details>

sure
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_7VKODPRlRko3cRhW:-NToB6hV-z1Ff0o84HjO:b1g9f58) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L131)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

records in runtime contains only 1 item, correct ? 
</blockquote></details>

not exactly, it points to iterator object.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_7oY_AcdOQPYu5GXz:-NToBFRrA9i3goVjJxGE:b-g812zy) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L160)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

during the time of migration, won't new insert go to the old collection ? 

in this case, the count of old collection maybe should calculated right before migration starts 
</blockquote></details>

yes, that's true, however chance of new insert is very low because entire migration will finish max in 20s and these collections don't get rapid inserts. But it is a fair point, ill change to get count before migration starts.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_8Xz5CWjWJdKA5JNh:-NToDOPMCRVPG7mVbHZR:bwvaiic) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L160)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

mongo provides a way to do dbHash, https://www.mongodb.com/docs/manual/reference/command/dbHash/#dbhash. 
do you think it's better to use this, as it provides md5 for the entire collection 
</blockquote></details>

good point, I searched a bit and it feels like its mostly to compare data within replica set of same cluster.
Another thing is it will store documents in memory, so it's not advisable to use in production (provided dataset is large)
https://stackoverflow.com/questions/27346463/verify-that-two-mongodb-collections-are-identical

**Comment by raghuAtWings** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1626 at r2](https://reviewable.io/reviews/harness/harness-core/46788#-NToK2YZ3YdD6SwdWCLX:-NToK2Y_-lW8w3SjM7IS:br5kqmb) ([raw file](https://github.com/harness/harness-core/blob/a8f6038168db03b64af15040b0924691b35f04af/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1626)):*
> ```Java
>   }
> 
>   private void runMigrations(Injector injector) throws DelegateDBMigrationFailed {
> ```

don't like this approach of sending DelegateDBMigrationFailed

we should do try and catch in the migrations to allow or fail server coming up

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_7VKODPRlRko3cRhW:-NToN--H4IdAq0MrE1zp:b-t7zm1) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L131)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

not exactly, it points to iterator object.
</blockquote></details>

i see, it copies all the documents from a collection, temporarily keep in memory, and then bulk write to new collection. am i correct ? 
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_8Xz5CWjWJdKA5JNh:-NToNn565kFlBIi4zxRT:bakpmr9) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L160)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

good point, I searched a bit and it feels like its mostly to compare data within replica set of same cluster.
Another thing is it will store documents in memory, so it's not advisable to use in production (provided dataset is large)
https://stackoverflow.com/questions/27346463/verify-that-two-mongodb-collections-are-identical
</blockquote></details>

make sense. if risky in prod, we can ignore this option

**Review by xingchi-jin — COMMENTED** [review]
@AnupamIO  qq: is the index created by datagen app, but migration executed by cg-manager ? 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788#-:-NTop_MO3Aag0g0JdYnB:bp024ky)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java` line 131 at r1](https://reviewable.io/reviews/harness/harness-core/46788#-NT_7VKODPRlRko3cRhW:-NTqspd-E5PFWbwgLYOC:brba39s) ([raw file](https://github.com/harness/harness-core/blob/c08360915dcf6f78d311effad72dcf90d27f2671/390-db-migration/src/main/java/io/harness/migrations/all/DMSDatabaseMigration.java#L131)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

i see, it copies all the documents from a collection, temporarily keep in memory, and then bulk write to new collection. am i correct ? 
</blockquote></details>

yes, only difference is not all documents will be in memory, iterator works in batches, it will fetch 101 documents by default, iterate on it then again fetch 101 documents (I read about this 101 default batch size from stackoverflow, couln't find in official documentation) We will bulk write 1000 documents at once at destination collection.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1626 at r2](https://reviewable.io/reviews/harness/harness-core/46788#-NToK2YZ3YdD6SwdWCLX:-NUbxzlI4WCICz3CTtEp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8f6038168db03b64af15040b0924691b35f04af/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1626)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't like this approach of sending DelegateDBMigrationFailed

we should do try and catch in the migrations to allow or fail server coming up
</blockquote></details>

Done.

**Comment by AnupamIO** [comment]
trigger uts

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 2 of 4 files at r3, 4 of 5 files at r4, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 1. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]

**Comment by AnupamIO** [comment]
trigger uts

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 1 of 4 files at r3, 4 of 5 files at r4, 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46788)* status: 1. unresolved discussions.

**Pull request merged**
