### PR TITLE
feat: [SPG-128]: logic for text index and search

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37324)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 8 Issues 
* Code issue 8 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37324)

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37324)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 242 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjouIH6svVAZQXqdF0:-NBjouIH6svVAZQXqdF1:b-t3ff8e) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L242)):*
> ```Java
>                  .build())
>         .add(SortTextMongoIndex.builder()
>                  .name("accountId_cdPageCandidate_createdAt_keywords")
> ```

can we name it text_keywords_createdAt

whats the purpose of accountId and cdPageCandidate fields here?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjoVdi0sciF5A_Mxvx:-NBjoVdj-ed8JWuBjdZ4:bmvl1sm) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
> ```Java
>   NG_ARTIFACT_SOURCES("Flag to support multi artifact sources for service V2", HarnessTeam.CDC),
>   UPDATE_EMAILS_VIA_SCIM("Will enable updating emails in Harness via SCIM", HarnessTeam.PL),
>   USE_TEXT_SEARCH_FOR_EXECUTION(
> ```

Why behind FF?
___
*[`960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjnQSsE45GtsS5NaqM:-NBjnQSt0JVqMvehr92P:bu1lnht) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java#L20)):*
> ```Java
> @Builder
> @Slf4j
> public class SortTextMongoIndex implements MongoIndex {
> ```

1. We should name it just TextMongoIndex.

2. Why this class has sparse, fields, rangeFields in it? Whats the purpose of them. I see the importance of only textfield and sortFields.  textField should be a list.

3.  Text Indexes have performance cost and storage cost. Have we run it through Sreehari. What was the bottleneck with Regex search?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37324)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 242 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjouIH6svVAZQXqdF0:-NBjpgs0-II2eQIKcyr_:b-aiw08h) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L242)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

can we name it text_keywords_createdAt

whats the purpose of accountId and cdPageCandidate fields here?
</blockquote></details>

it will help us limit more documents - the query is accountId-cdpagecandidate-createdAt-1,keywords :P 
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjoVdi0sciF5A_Mxvx:-NBjq6hS3MrPnI0tRyoT:b-7ghylt) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why behind FF?
</blockquote></details>

workflowexecution page we will slowly rollover currently its regex search 
___
*[`960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjnQSsE45GtsS5NaqM:-NBjqFvzANQKrjMEhf4A:bd0vbk6) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

1. We should name it just TextMongoIndex.

2. Why this class has sparse, fields, rangeFields in it? Whats the purpose of them. I see the importance of only textfield and sortFields.  textField should be a list.

3.  Text Indexes have performance cost and storage cost. Have we run it through Sreehari. What was the bottleneck with Regex search?
</blockquote></details>

1. TextMongoIndex is already there.
2. mongo doesnt allow 2 text fields at once i think 
3. current regex search is worst possible - sreehari has suggested this.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37324)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 242 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjouIH6svVAZQXqdF0:-NBjuA2n0ePxdYKn6fbB:b2ni9bh) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L242)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

it will help us limit more documents - the query is accountId-cdpagecandidate-createdAt-1,keywords :P 
</blockquote></details>

ok.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjoVdi0sciF5A_Mxvx:-NBjtg0-7Wd6mvyCY1hE:b-pc32sd) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

workflowexecution page we will slowly rollover currently its regex search 
</blockquote></details>

Why need of slow rollout? What feedback we are looking for before wider rollout. I am assuming we would have considered both performance and functional implications.
___
*[`960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjnQSsE45GtsS5NaqM:-NBjtG2k8OelYLfOcmED:b-tsg67o) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java#L20)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

1. TextMongoIndex is already there.
2. mongo doesnt allow 2 text fields at once i think 
3. current regex search is worst possible - sreehari has suggested this.
</blockquote></details>

1. Why we can not then re-use TextMongoIndex itself
2. It allows
3. Ok. Then it's fine. I want to make sure we understand the performance implications of this.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37324)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjoVdi0sciF5A_Mxvx:-NBk_O_TBlS2JVaR1fvP:b-wfe8ku) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why need of slow rollout? What feedback we are looking for before wider rollout. I am assuming we would have considered both performance and functional implications.
</blockquote></details>

Customers complain on such huge changes and sometimes we have to rollback for them - for example we restricted searching to 3 months and we had one unhappy customer who was not willing to renew so we had to enable for him.

We will rollout globally as per current plan but if situation arises we can rollback.
___
*[`960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjnQSsE45GtsS5NaqM:-NBk_J7u6pDBrb8_NbMU:b-o9mnxs) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

1. Why we can not then re-use TextMongoIndex itself
2. It allows
3. Ok. Then it's fine. I want to make sure we understand the performance implications of this.

</blockquote></details>

That textmongoindex doesnt have sorting - let me edit that class itself.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37324)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjnQSsE45GtsS5NaqM:-NBnStWPB93KjADkZDs0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/960-persistence/src/main/java/io/harness/mongo/SortTextMongoIndex.java#L20)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

That textmongoindex doesnt have sorting - let me edit that class itself. 
</blockquote></details>

Done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37324#-:-NBokT4G36dXYLcZflyt:bnfp4nl)* status: :shipit: complete! ✓

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 438 at r2](https://reviewable.io/reviews/harness/harness-core/37324#-NBjoVdi0sciF5A_Mxvx:-NBokE9K07vUAwa1F9F9:b-fynx9q) ([raw file](https://github.com/harness/harness-core/blob/5d15a9c54f04b2bee1e368d522c135c3a7e28997/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L438)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Customers complain on such huge changes and sometimes we have to rollback for them - for example we restricted searching to 3 months and we had one unhappy customer who was not willing to renew so we had to enable for him.

We will rollout globally as per current plan but if situation arises we can rollback.
</blockquote></details>

ok. but i think here customer should not have a choice between regex and text search. its more of an implementation detail.

**Pull request merged**
