### PR TITLE
[fix]: [PIE-9435]: Fetch commit ID during create file for gitlab

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to fetch commit ID during create file for gitlab and cache update is successful. Have tested out the cache data for remote file creations for gitlab connector for default and non default branches.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger buildnum

**Comment by adivishy1** [comment]
trigger buildnum

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/46058#-NSAsMyb94gbXd4rHTOW:-NSAsMyb94gbXd4rHTOX:b-tqwak1) ([raw file](https://github.com/harness/harness-core/blob/30aea9ed813447a3fd6a11235dcff6d1e58bd71c/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L149)):*
> ```Java
>     CreateFileResponse createFileResponse =
>         ScmGrpcClientUtils.retryAndProcessException(scmBlockingStub::createFile, fileModifyRequest);
>     if (ScmResponseStatusUtils.isSuccessResponse(createFileResponse.getStatus())
> ```

200 or 201 both are kind of Creation Successful HTTP Response Codes. So, I think we should do the handling here itself at common place for all such kind of use-case where its success but response commit id is empty.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/46058#-NSAsdK4E3zPrQjSgp3p:-NSAsdK4E3zPrQjSgp3q:bns4flq) ([raw file](https://github.com/harness/harness-core/blob/30aea9ed813447a3fd6a11235dcff6d1e58bd71c/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L169)):*
> ```Java
>   private CreateFileResponse handleCommitIdForGitlabFileCreation(CreateFileResponse createFileResponse,
>       GitFileDetails gitFileDetails, ScmConnector scmConnector, SCMGrpc.SCMBlockingStub scmBlockingStub) {
>     GetLatestCommitOnFileResponse getLatestCommitOnFileResponse =
> ```

This can be done for all such cases where we get empty commit id for successful response.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/46058#-NSAsMyb94gbXd4rHTOW:-NSAuQ0pEP1bWhtqxeEP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/30aea9ed813447a3fd6a11235dcff6d1e58bd71c/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L149)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

200 or 201 both are kind of Creation Successful HTTP Response Codes. So, I think we should do the handling here itself at common place for all such kind of use-case where its success but response commit id is empty.
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/46058#-NSAsdK4E3zPrQjSgp3p:-NSAuPOR89Qg3hgE51zd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/30aea9ed813447a3fd6a11235dcff6d1e58bd71c/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L169)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This can be done for all such cases where we get empty commit id for successful response.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/46058#-NSAvA8G42TKt07Kr6oy:-NSAvA8G42TKt07Kr6oz:b-y5jq8h) ([raw file](https://github.com/harness/harness-core/blob/b43741db7055d6bffd6e5770e5bdce02e27b5b72/952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java#L122)):*
> ```Java
> 
>   public boolean isSuccessResponse(int statusCode) {
>     return statusCode == 200 || statusCode == 201;
> ```

We shouldn't combine both status codes in success response. May be we can create a separate method for CREATE flow itself that takes into account both status codes. For other operations, 201 is not expected.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/46058#-NSAvPeD4evsAamzZ5TX:-NSAvPeD4evsAamzZ5TY:b-b7skvo) ([raw file](https://github.com/harness/harness-core/blob/b43741db7055d6bffd6e5770e5bdce02e27b5b72/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L151)):*
> ```Java
>     if (ScmResponseStatusUtils.isSuccessResponse(createFileResponse.getStatus())
>         && isEmpty(createFileResponse.getCommitId())) {
>       if (isBitbucketOnPrem(scmConnector)) {
> ```

We should remove this check as well. We can create a backlog ticket to check it later once we are done with hotfix. Our logic here should be agnostic of the git provider.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/46058#-NSAvA8G42TKt07Kr6oy:-NSAxIXiB5Uiwq7HxRXB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b43741db7055d6bffd6e5770e5bdce02e27b5b72/952-scm-java-client/src/main/java/io/harness/impl/ScmResponseStatusUtils.java#L122)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We shouldn't combine both status codes in success response. May be we can create a separate method for CREATE flow itself that takes into account both status codes. For other operations, 201 is not expected.
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/46058#-NSAvPeD4evsAamzZ5TX:-NSAxgIw7Bzpa_6VRQH4:b-asek3i) ([raw file](https://github.com/harness/harness-core/blob/b43741db7055d6bffd6e5770e5bdce02e27b5b72/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L151)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should remove this check as well. We can create a backlog ticket to check it later once we are done with hotfix. Our logic here should be agnostic of the git provider.
</blockquote></details>

https://harness.atlassian.net/browse/PIE-9438

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46058)* status: :shipit: complete! ✓

**Pull request merged**
