### PR TITLE
fix: [PIE-8842]: add handling for fields of type list in RecasterOrchestrationUtils

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

We are adding this because if it is a list then we are trying to convert it to a map and that is giving a few issues. This fixes the part where if parameter field has a list inside or a string array

**Testing:** Tested the behavior locally, fields like uuid, __recaster, and __encoded are removed from step parameters and in userGroups in approvers in the approval step, when the user gives a combined expression split with `,` its value is correctly shown in input tab.

Screenshot 2023-03-23 at 12 11 13 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45462)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/serializer/recaster/RecastOrchestrationUtils.java` line 335 at r1](https://reviewable.io/reviews/harness/harness-core/45462#-NR7e0T88br-hbwVNgsv:-NR7e0T88br-hbwVNgsw:bjmqtpl) ([raw file](https://github.com/harness/harness-core/blob/9cc8b202b4d92dba404dc8eadd949f60da5910ec/953-yaml-commons/src/main/java/io/harness/pms/serializer/recaster/RecastOrchestrationUtils.java#L335)):*
> ```Java
>                 || type == byte.class || type == Date.class || type == Locale.class || type == Class.class
>                 || type == UUID.class || type == URI.class || type.isEnum())
>         || type == String[].class || type == List.class);
> ```

For other reviewers:
We are adding this because if it is a list then we are trying to convert to map and that is giving few issues. This fixes the part where if parameterField has a list inside or string array

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45462)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45462)* status: :shipit: complete! ✓

**Pull request merged**
