### PR TITLE
[feat]: [SRM-10086]: added NotificationRule into SLO with new mock up changes

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32382)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32382)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/32382#-N0V0fds66uJTiSsaFnu:-N0V0fds66uJTiSsaFnv:bu8ghvd) ([raw file](https://github.com/harness/harness-core/blob/13995995861d5b6dd809002aabf90b7a778fbc4b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java#L26)):*
> ```Java
> public class SLONotificationRuleSpec extends NotificationRuleSpec {
>   @NonNull SLONotificationRuleSpecType specType;
>   @NonNull Integer threshold;
> ```

I think this should be double
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32382#-N0V0wzT01gbnDlA4ZPX:-N0V0wzT01gbnDlA4ZPY:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/13995995861d5b6dd809002aabf90b7a778fbc4b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java#L30)):*
> ```Java
> public class SLONotificationRule extends NotificationRule {
>   @NonNull SLONotificationRuleSpecType specType;
>   @NonNull Integer threshold;
> ```

same here
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/32382#-N0V1D9uDA1Z30xSjFBB:-N0V1D9uDA1Z30xSjFBC:btpe5fm) ([raw file](https://github.com/harness/harness-core/blob/13995995861d5b6dd809002aabf90b7a778fbc4b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L45)):*
> ```Java
>   @Valid @NotNull List<ServiceLevelIndicatorDTO> serviceLevelIndicators;
>   @Valid @NotNull SLOTarget target;
>   List<NotificationRuleDTO> notificationRules;
> ```

it should not be List of notification rule right? It should be just the notificationRuleIdentifier

**Comment by kapil-harness** [comment]
trigger ft1

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32382)* status: 17 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/32382#-N0V0fds66uJTiSsaFnu:-N0Xbv1QEXLX1qs9QerC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/13995995861d5b6dd809002aabf90b7a778fbc4b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java#L26)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think this should be double
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32382#-N0V0wzT01gbnDlA4ZPX:-N0Xc-Lw-PvSqjyMKz1I:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/13995995861d5b6dd809002aabf90b7a778fbc4b/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java#L30)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

same here
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/32382#-N0V1D9uDA1Z30xSjFBB:-N0Xc4kb4tIxuXDlCkhv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/13995995861d5b6dd809002aabf90b7a778fbc4b/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L45)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

it should not be List of notification rule right? It should be just the notificationRuleIdentifier
</blockquote></details>

done

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 9 of 15 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32382)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YsXAQCLqN_meSJoi9:-N0YsXAQCLqN_meSJoiA:b-ojckdx) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java#L37)):*
> ```Java
>   boolean enabled;
>   @NotNull NotificationRuleType type;
>   @Valid @NotNull List<NotificationRuleSpec> spec;
> ```

we should call it conditions
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YuqRF3gu829v9cF3L:-N0YuqRF3gu829v9cF3M:bsc4r1k) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java#L25)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class SLONotificationRuleSpec extends NotificationRuleSpec {
>   @NonNull SLONotificationRuleSpecType specType;
> ```

it should be type not specType
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0Yuy0X-KgDqKyQOW0_:-N0Yuy0X-KgDqKyQOW0a:b7imivx) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java#L26)):*
> ```Java
> public class SLONotificationRuleSpec extends NotificationRuleSpec {
>   @NonNull SLONotificationRuleSpecType specType;
>   @NonNull Double threshold;
> ```

This needs to  be in the spec 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YvCfR4yKw_WnzxBhr:-N0YvCfR4yKw_WnzxBhs:byst9qe) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java#L30)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> public class SLONotificationRule extends NotificationRule {
>   @NonNull List<SLONotificationRuleEntitySpec> specs;
> ```

I think we will need to have corresponding entity classes for different types of conditions. We should not directly save DTO in the database.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0Yw-iNDtB7JZkL2K22:-N0Yw-iNDtB7JZkL2K23:bokbc2r) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L55)):*
> ```Java
>   @Data
>   @Builder
>   public static class NotificationRuleRef {
> ```

this can be moved to bean with right name. We can reuse this for MonitoredService
NotificationRuleRefDTO
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YvxIt5n3EYDPT4XsU:-N0YvxIt5n3EYDPT4XsV:b-nm5e85) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L56)):*
> ```Java
>   @Builder
>   public static class NotificationRuleRef {
>     @NotNull String identifier;
> ```

the name should be notificationRuleRef
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YwGcf9AuZL4c9ZQ4h:-N0YwGcf9AuZL4c9ZQ4i:b3qo3p2) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L85)):*
> ```Java
>   String monitoredServiceIdentifier;
>   List<String> serviceLevelIndicators;
>   List<String> notificationRuleIdentifiers;
> ```

why only list of string? It should save enabled, disable information also right?

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32382)* status: 19 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YsXAQCLqN_meSJoi9:-N0_w_ia07ky46zuwwpH:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/NotificationRuleDTO.java#L37)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should call it conditions
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YvCfR4yKw_WnzxBhr:-N0_wlaH2wQ4_j9W2416:b-1lafkv) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/SLONotificationRule.java#L30)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think we will need to have corresponding entity classes for different types of conditions. We should not directly save DTO in the database.
</blockquote></details>

done, not directly using DTO
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0Yw-iNDtB7JZkL2K22:-N0_wtI-8DDF56NEd_AY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L55)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this can be moved to bean with right name. We can reuse this for MonitoredService
NotificationRuleRefDTO
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YvxIt5n3EYDPT4XsU:-N0_wu8y3k7SGDJNlLrY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ServiceLevelObjectiveDTO.java#L56)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

the name should be notificationRuleRef
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YwGcf9AuZL4c9ZQ4h:-N0_wvynEcufv-eDXPk5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/ServiceLevelObjective.java#L85)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why only list of string? It should save enabled, disable information also right?
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0YuqRF3gu829v9cF3L:-N0_wb2n2SUCtJQPuLkP:b-outekp) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java#L25)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

it should be type not specType
</blockquote></details>

due to a technical issue this will be done in subsequent PRs
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/32382#-N0Yuy0X-KgDqKyQOW0_:-N0_wjli9BUpIhlqYmC-:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b514d2716d4497c7d95f370cc3ce125eb9325e95/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/SLONotificationRuleSpec.java#L26)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

This needs to  be in the spec 
</blockquote></details>

done

**Pull request merged**
