### PR TITLE
techdebt: [SRM-12430]: Refactor SLI and Composite SLO record service

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40405)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40405)* status: 23 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLORecordService.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/40405#-NHY2lH13sPCdQ2ND7ZG:-NHY2lH13sPCdQ2ND7ZH:b-6v9ayd) ([raw file](https://github.com/harness/harness-core/blob/daaca06676050f8ac3508e5b02de011e5c0a3a37/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLORecordService.java#L29)):*
> ```Java
>   void create(List<SLIRecordParam> sliRecordList, String sliId, String verificationTaskId, int sliVersion);
> 
>   SLOGraphData getGraphData(AbstractServiceLevelObjective serviceLevelObjective, Instant startTime, Instant endTime,
> ```

Lets move this to new class SLOGraphDataService. And keep the SLORecord Service and SLI Record service as seperate

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40405)* status: 27 file(s) to review. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImplTest.java` line 179 at r6](https://reviewable.io/reviews/harness/harness-core/40405#-NHbs1BnEU93r9O2zvOs:-NHbs1BnEU93r9O2zvOt:bricovl) ([raw file](https://github.com/harness/harness-core/blob/b334921b8589b056dd07448b7c3bbeb1035510c6/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/GraphDataServiceImplTest.java#L179)):*
> ```Java
>   }
> 
>   //    @Test
> ```

nit: Lets add them as ignore if we intend to fix them/

**Review by deepak-harness — APPROVED** [review]
> Reviewed 5 of 24 files at r1, 17 of 22 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40405)* status: :shipit: complete! ✓

**Pull request merged**
