### PR TITLE
fix: [BT-5901]: Bazel build target optimisation in 400-rest & 930-delegate-tasks tests target

### PR DESCRIPTION
**Pull request by VivekHarness**
## Describe your changes
After analysing 400-rest module and coming up with the approach mentioned in [BT-5897](https://harness.atlassian.net/browse/BT-5897)
I was able to reduce the time of 400-rest build by 7% i.e. nearly 1 min, in Apple M1 Pro based laptop.

Approach followed: [Bazel Build Target Optimisation](https://harness.atlassian.net/wiki/spaces/BT/pages/21556462213/Bazel+Build+Target+Optimisation)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[BT-5897]: https://harness.atlassian.net/browse/BT-5897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57113)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]

**Comment by VivekHarness** [comment]
trigger smartchecks

**Comment by VivekHarness** [comment]
trigger commonchecks

**Comment by VivekHarness** [comment]
trigger codeformat

**Comment by VivekHarness** [comment]
trigger mdc

**Comment by VivekHarness** [comment]
trigger its

**Comment by VivekHarness** [comment]
trigger its

**Comment by VivekHarness** [comment]
trigger uts

**Comment by VivekHarness** [comment]
trigger uts

**Comment by VivekHarness** [comment]
trigger checkstylecodeformat

**Comment by VivekHarness** [comment]
trigger uts

**Comment by VivekHarness** [comment]
trigger ut5, trigger ut6, trigger ut7, trigger ut8

**Comment by VivekHarness** [comment]
trigger ut6

**Comment by VivekHarness** [comment]
trigger ut7

**Comment by VivekHarness** [comment]
trigger ut7

**Review by mdmilic — APPROVED** [review]

**Comment by VivekHarness** [comment]
trigger ut7

**Comment by VivekHarness** [comment]
trigger ut7

**Comment by VivekHarness** [comment]
trigger ut7

**Pull request merged**
