### PR TITLE
[feat]: [CDS-34222]: Cloudformation refactoring

### PR DESCRIPTION
**Pull request by tmacari-harness**
[feat]: [CDS-34222]: Cloudformation refactoring to be able to use in NG tasks.
NG cloudformation tasks skeleton.
Moved the cloudformation logic from Cloudformationtaskhandlers to CloudformationBaseHelper.
Refactored / migrated required services.

[CDS-34222]: https://harness.atlassian.net/browse/CDS-34222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31159)

### CODE REVIEW

**Review by nassergonzalez — DISMISSED** [review]
> Reviewed 25 of 40 files at r1, 26 of 29 files at r2, 3 of 29 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31159)* status: 29 file(s) to review.

**Comment by arvind-choudhary-h** [comment]
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNG.java, line 47 at r9](https://reviewable.io/reviews/harness/harness-core/31159#-MyE4zY3CygS3KofKu8c:-MyE4zY3CygS3KofKu8d:b-w78s6j) ([raw file](https://github.com/harness/harness-core/blob/1bcbf5338e48731bfc4af7656ebfb104981c423b/930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNG.java#L47)):*
> ```Java
>   @Override
>   public DelegateResponseData run(Object[] parameters) {
>     return null;
> ```

Can throw unsupported exception

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 21 of 40 files at r1, 2 of 32 files at r3, 1 of 31 files at r5, 5 of 35 files at r6, 6 of 6 files at r7, 1 of 25 files at r8, 24 of 24 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31159)* status: 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 21 of 40 files at r1, 2 of 32 files at r3, 1 of 29 files at r4, 1 of 31 files at r5, 1 of 25 files at r8, 24 of 24 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31159)* status: :shipit: complete! ✓

___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGParameters.java, line 42 at r9](https://reviewable.io/reviews/harness/harness-core/31159#-MyF2g1QCLEYqAlZejXS:-MyF2g1QCLEYqAlZejXT:b19bii0) ([raw file](https://github.com/harness/harness-core/blob/1bcbf5338e48731bfc4af7656ebfb104981c423b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGParameters.java#L42)):*
> ```Java
>   public List<ExecutionCapability> fetchRequiredExecutionCapabilities(ExpressionEvaluator maskingEvaluator) {
>     List<ExecutionCapability> capabilities = new ArrayList<>();
>     log.info("Adding Required Execution Capabilities");
> ```

nit: not necessary
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGResponse.java, line 26 at r9](https://reviewable.io/reviews/harness/harness-core/31159#-MyF2kwjE9FOEgH8XUNl:-MyF2kwjE9FOEgH8XUNm:bn1melf) ([raw file](https://github.com/harness/harness-core/blob/1bcbf5338e48731bfc4af7656ebfb104981c423b/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNGResponse.java#L26)):*
> ```Java
> @Builder
> @OwnedBy(CDP)
> public class CloudformationTaskNGResponse implements DelegateTaskNotifyResponseData {
> ```

nit: fields can be private

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 3 of 27 files at r10, 26 of 26 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31159)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 19 of 40 files at r1, 3 of 35 files at r6, 6 of 6 files at r7, 2 of 27 files at r10, 2 of 28 files at r12, 28 of 28 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31159)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 27 files at r10, 2 of 28 files at r12, 28 of 28 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31159#-:-Mysi40f7MjkxHPjl78T:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
