### PR TITLE
feat: [CDS-37289]: Convert given env from pipeline ref to env pojo (c…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…ontaining infradef and gitops)

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33263)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33263)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 233 at r1](https://reviewable.io/reviews/harness/harness-core/33263#-N2GkX9CBON_c6JZ8IyP:-N2GkX9DDfwwJ_JAjOyG:bow77zt) ([raw file](https://github.com/harness/harness-core/blob/7dffa40f7c5d5baf9870840775765b5f629a59e6/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L233)):*
> ```Java
>         environmentV2.getInfrastructureDefinitions().get(0).getRef().getValue());
> 
>     if (environment.isPresent() && infrastructureEntity.isPresent()) {
> ```

both present is not compulory, either git cluster or infrared is compulsory else throw error that neither of them is present
cc: @yogesh-chauhan 



_Code quote:_
```Java
environment.isPresent() && infrastructureEntity.isPresent()
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentPlanCreatorConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/33263#-N2GkgbO99etoo3089qw:-N2GkgbO99etoo3089qx:bgwyxjc) ([raw file](https://github.com/harness/harness-core/blob/7dffa40f7c5d5baf9870840775765b5f629a59e6/125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentPlanCreatorConfig.java#L50)):*
> ```Java
>   private String uuid;
> 
>   @NotNull String environmentRef;
> ```

We should add schema validtion that only runtime or constant string is allowed and not expression, @yogesh-chauhan has exposed a pattern already

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33263)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentPlanCreatorConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/33263#-N2GkgbO99etoo3089qw:-N2GtAw4Bf-H1F3jPFfQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7dffa40f7c5d5baf9870840775765b5f629a59e6/125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentPlanCreatorConfig.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should add schema validtion that only runtime or constant string is allowed and not expression, @yogesh-chauhan has exposed a pattern already
</blockquote></details>

done

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33263)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 233 at r1](https://reviewable.io/reviews/harness/harness-core/33263#-N2GkX9CBON_c6JZ8IyP:-N2H1eHn-NFA8K64xouc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7dffa40f7c5d5baf9870840775765b5f629a59e6/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L233)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

both present is not compulory, either git cluster or infrared is compulsory else throw error that neither of them is present
cc: @yogesh-chauhan 
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33263)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/33263#-N2Kower1WWzgL0N2ctD:-N2Kowet3NJicqRkQAE3:bjqf3gu) ([raw file](https://github.com/harness/harness-core/blob/a95086a1369145c118f9cb074f40ed09bcbec146/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L292)):*
> ```Java
>     }
> 
>     if (environment.isPresent()) {
> ```

this check is not required anymore



_Code quote:_
```Java
if (environment.isPresent()) {
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33263)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/33263#-N2Kower1WWzgL0N2ctD:-N2LWOAH-wYx06Ia7Yod:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a95086a1369145c118f9cb074f40ed09bcbec146/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L292)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this check is not required anymore
</blockquote></details>

done

**Pull request merged**
