### PR TITLE
fix: [PIE-9632]: Fetch FF value using CG API in on prem and community version

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46454)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46454)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/46454#-NTHvMJhAkr27Z5gyMDO:-NTHvMJhAkr27Z5gyMDP:beo4fao) ([raw file](https://github.com/harness/harness-core/blob/bdc045ae37d630c57fd1c0380b25d1e61b2e07eb/878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java#L52)):*
> ```Java
>                   || (DEPLOY_VERSION != null && DEPLOY_VERSION.equals("COMMUNITY"))) {
>                 return CGRestUtils.getResponse(accountClient.isFeatureFlagEnabled(
>                     featureNameAndAccountId.getFeatureName().name(), featureNameAndAccountId.getAccountId()));
> ```

expose a different method rather than inline, method check could be only on if condition even



_Code quote:_
```Java
              if ((DEPLOY_MODE != null && (DEPLOY_MODE.equals("ONPREM") || DEPLOY_MODE.equals("KUBERNETES_ONPREM")))
                  || (DEPLOY_VERSION != null && DEPLOY_VERSION.equals("COMMUNITY"))) {
                return CGRestUtils.getResponse(accountClient.isFeatureFlagEnabled(
                    featureNameAndAccountId.getFeatureName().name(), featureNameAndAccountId.getAccountId()));
              }
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46454)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/46454#-NTHvMJhAkr27Z5gyMDO:-NTI6F3PE6BDiyMp8XIw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bdc045ae37d630c57fd1c0380b25d1e61b2e07eb/878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

expose a different method rather than inline, method check could be only on if condition even
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46454)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/46454#-NTI7Ibm59yTAVMZ9qEE:-NTI7Ibn1lbfKb5ahPpp:b-xi9eni) ([raw file](https://github.com/harness/harness-core/blob/e3fceec6a37a0a01badbf39ef8fa9a14c9f85bce/878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java#L79)):*
> ```Java
>   private boolean isFlagEnabledForAccountId(FeatureNameAndAccountId featureNameAndAccountId) {
>     if ((DEPLOY_MODE != null && (DEPLOY_MODE.equals("ONPREM") || DEPLOY_MODE.equals("KUBERNETES_ONPREM")))
>         || (DEPLOY_VERSION != null && DEPLOY_VERSION.equals("COMMUNITY"))) {
> ```

create subMethod for this if condition to tell what its checking. could be checkIfEnvOnPremOrCommunity



_Code quote:_
```Java
    if ((DEPLOY_MODE != null && (DEPLOY_MODE.equals("ONPREM") || DEPLOY_MODE.equals("KUBERNETES_ONPREM")))
        || (DEPLOY_VERSION != null && DEPLOY_VERSION.equals("COMMUNITY"))) {
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46454)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/46454#-NTI7Ibm59yTAVMZ9qEE:-NTIS0FpCdTT8A7KAgGv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e3fceec6a37a0a01badbf39ef8fa9a14c9f85bce/878-ng-common-utilities/src/main/java/io/harness/utils/PmsFeatureFlagHelper.java#L79)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

create subMethod for this if condition to tell what its checking. could be checkIfEnvOnPremOrCommunity
</blockquote></details>

done

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46454)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
