### PR TITLE
feat: [PIE-7689]: add delegate task handling for get batch files use-case

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Added new delegate task to get files in batch at once. It internally calls get-file method which is basically a way of sequentially fetching files from GIT but overall as a delegate task it does fetch all files at once and sends back the response for all files, thus helps to optimize creating separate delegate tasks for each file fetch use-case.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 27 of 28 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)* status: 31 file(s) to review. 1 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/beans/response/ScmGitFileBatchResponse.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42700#-NLzbSbiB2Mt0nPeBlJF:-NLzbSbiB2Mt0nPeBlJG:b-fn6la7) ([raw file](https://github.com/harness/harness-core/blob/d304ed593715252efa7f1c00146c3899aa0079a6/952-scm-java-client/src/main/java/io/harness/beans/response/ScmGitFileBatchResponse.java#L19)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @Value
> @SuperBuilder
> ```

nit: why do you superbuilder here? and same for others?

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/beans/response/ScmGitFileBatchResponse.java` line 19 at r3](https://reviewable.io/reviews/harness/harness-core/42700#-NLzbSbiB2Mt0nPeBlJF:-NLzbxFEBq5wcBqk2oD3:bo9sjzl) ([raw file](https://github.com/harness/harness-core/blob/d304ed593715252efa7f1c00146c3899aa0079a6/952-scm-java-client/src/main/java/io/harness/beans/response/ScmGitFileBatchResponse.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: why do you superbuilder here? and same for others?
</blockquote></details>

SuperBuilder is used to create objects for classes that extend other classes. Its a annotation of lombok itself.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 25 of 28 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]
> Reviewed 22 of 28 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 22 of 28 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)* status: 1. unresolved discussions.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 22 of 28 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42700)* status: 1. unresolved discussions.

**Pull request merged**
