### PR TITLE
feat: [cds-48962]: Remove Template Inputs Validations from all apis

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
As part of improving improving ART for pipeline and template api's we are removing the validations from applyTemplates call, and from now on Support for reconcillation will become on demand improving overall user experience 
Also We need removed `removeOmittedRuntimeInputsFromMergedYaml` function from applyTemplates call

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41856)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger ti3

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/41856#-NJvQiG0DW8AkrFM3zmc:-NJvQiG0DW8AkrFM3zmd:b-hgftly) ([raw file](https://github.com/harness/harness-core/blob/d6e183ec6ddc41089e744b7aa2cae318ac92e094/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L95)):*
> ```Java
>    * @return final yaml with all template occurrences replaced with actual template information.
>    */
>   public TemplateMergeResponseDTO applyTemplatesToYamlV2(String accountId, String orgId, String projectId, String yaml,
> ```

lets see if we can deprecate one of the methods or call applyTemplates from applyTemplatesV2 ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41856)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/41856#-NJxT7U-D-iGMeedlZTg:-NJxT7U-D-iGMeedlZTh:b-14d33n) ([raw file](https://github.com/harness/harness-core/blob/5a548b6ea34a9a71747fca54c7bf503a1718db67/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L92)):*
> ```Java
>     Map<String, TemplateEntity> templateCacheMap = new HashMap<>();
>     TemplateInputsErrorMetadataDTO errorResponse = templateMergeServiceHelper.validateLinkedTemplateInputsInYaml(
>         accountId, orgId, projectId, yamlNode, templateCacheMap, loadFromCache);
> ```

Let's check this templateCacheMap field, i believe it wont be needed in this subsequent method.
If not in this pr, Let's do the code clean up accordingly.



_Code quote:_
```Java
.validateLinkedTemplateInput
```

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41856)* status: 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41856)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/41856#-NJxT7U-D-iGMeedlZTg:-NLVHtI60iXhjPvX-xyR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5a548b6ea34a9a71747fca54c7bf503a1718db67/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L92)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Let's check this templateCacheMap field, i believe it wont be needed in this subsequent method.
If not in this pr, Let's do the code clean up accordingly.


</blockquote></details>

Done.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41856)* status: Some of the checks are too old.

**Review by inderschera — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41856)* status: Some of the checks are too old.

**Pull request merged**
