### PR TITLE
fix: [DEL-4031]: cache watcher calls

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1474 at r1](https://reviewable.io/reviews/harness/harness-core/33088#-N1s1Ltj5U_cxpDpux-A:-N1s1Ltj5U_cxpDpux-B:ba6255) ([raw file](https://github.com/harness/harness-core/blob/0e59c4fc8261a4ffafa945025af79ffddf7f0a3d/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1474)):*
> ```Java
>       statusData.put(DELEGATE_SHUTDOWN_PENDING, !acquireTasks.get());
>       // dont pass null delegateId, instead pass "Unregistered" as delegateId
>       statusData.put(DELEGATE_ID, getDelegateId().orElse("Unregistered"));
> ```

Instead of writing delegateId in heartbeat, I would suggest send it via message channel, like we send process id. And in watcher code, you can  look for that message in `watchDelegate()` method till you get that.



_Code quote:_
```Java
Unregistered
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 635 at r1](https://reviewable.io/reviews/harness/harness-core/33088#-N1s1EUE9AJzFd4lFK_k:-N1s1EUE9AJzFd4lFK_l:b-wmmkbf) ([raw file](https://github.com/harness/harness-core/blob/0e59c4fc8261a4ffafa945025af79ffddf7f0a3d/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L635)):*
> ```Java
>               }
> 
>               String delegateIdFromAgent = (String) delegateData.get(DELEGATE_ID);
> ```

You can call this only when getDelegateId() returns unregistered.



_Code quote:_
```Java
              String delegateIdFromAgent = (String) delegateData.get(DELEGATE_ID);
              this.setDelegateId(delegateIdFromAgent);
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1474 at r1](https://reviewable.io/reviews/harness/harness-core/33088#-N1s1Ltj5U_cxpDpux-A:-N26VuwZ0re26sTH30Xz:b-qy43cg) ([raw file](https://github.com/harness/harness-core/blob/0e59c4fc8261a4ffafa945025af79ffddf7f0a3d/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1474)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Instead of writing delegateId in heartbeat, I would suggest send it via message channel, like we send process id. And in watcher code, you can  look for that message in `watchDelegate()` method till you get that.
</blockquote></details>

sending it individually via message service will lead to watcher waiting for msg and remain idle for few mins.
Just like this 



_Code snippet:_
```Java
 Message message =
      messageService.waitForMessage(NEW_DELEGATE, TimeUnit.MINUTES.toMillis(version == null ? 15 : 4));
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 635 at r1](https://reviewable.io/reviews/harness/harness-core/33088#-N1s1EUE9AJzFd4lFK_k:-N26WHfdDIUisBYCgDQg:b-7oi75n) ([raw file](https://github.com/harness/harness-core/blob/0e59c4fc8261a4ffafa945025af79ffddf7f0a3d/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L635)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

You can call this only when getDelegateId() returns unregistered.
</blockquote></details>

will do after resolving your first comment.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKxpYCzi3SUDKa2_W:-N2FKxpYCzi3SUDKa2_X:bvs0php) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java#L38)):*
> ```Java
>     return chain.proceed(request.newBuilder()
>                              .header("Authorization", "Delegate " + token)
>                              .addHeader("delegateId", WatcherServiceImpl.getDelegateId())
> ```

What happen if we send "unregistered" here, how will manager react to this ?



_Code quote:_
```Java
addHeader("delegateId", WatcherServiceImpl.getDelegateId())
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 206 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKmQ41LjJwuSR18r8:-N2FKmQ41LjJwuSR18r9:b5pae52) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L206)):*
> ```Java
>   private static final String DELEGATE_TYPE = System.getenv().get("DELEGATE_TYPE");
>   private static final String DELEGATE_SCRIPT = "delegate.sh";
>   private static final String UNREGISTERED = "Unregistered";
> ```

Make this a const messageConstant.java



_Code quote:_
```Java
"Unregistered";
```
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 636 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKc6--Z0rVVnkmsm2:-N2FKc6--Z0rVVnkmsm3:b-neu8o5) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L636)):*
> ```Java
>               }
> 
>               String delegateIdFromAgent = (String) delegateData.get(DELEGATE_ID);
> ```

Move this inside below if condition.



_Code quote:_
```Java
  String delegateIdFromAgent = (String) delegateData.get(DELEGATE_ID);
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKxpYCzi3SUDKa2_W:-N2FPSAh2Q3UTyU7re4C:b-3t1i04) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java#L38)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

What happen if we send "unregistered" here, how will manager react to this ?
</blockquote></details>

manager will be caching that call also, but that will be of no use. I kept it just for proper error handling.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 635 at r1](https://reviewable.io/reviews/harness/harness-core/33088#-N1s1EUE9AJzFd4lFK_k:-N2FPd3o28IL9n1pNyl6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0e59c4fc8261a4ffafa945025af79ffddf7f0a3d/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L635)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

will do after resolving your first comment.
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 206 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKmQ41LjJwuSR18r8:-N2FPbPZ1Uk1sEXnRfvt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L206)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Make this a const messageConstant.java
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java` line 636 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKc6--Z0rVVnkmsm2:-N2FPdNrD6uelOYCRnqS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L636)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Move this inside below if condition.
</blockquote></details>

Done.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/33088#-N2FKxpYCzi3SUDKa2_W:-N2FZNz9CNikK4nMjuUN:b-ro99py) ([raw file](https://github.com/harness/harness-core/blob/7386fae59bbbee29a197f8f454c04068dfced78f/960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java#L38)):*
> that call also, but that will be of no use. I kept it just for 
You can send empty delegateId in such case, let manager should validate through DB.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: 4 file(s) to review. 2. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33088)* status: :shipit: complete! ✓

**Pull request merged**
