### PR TITLE
[feat]: [CDS-38531]: add azure web apps service

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
Adding azure web app service
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 16 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: 18 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/34340#-N4cWQ-m6GuXPtmhPzDt:-N4cWQ-nCafhafENJ7A2:bq033yf) ([raw file](https://github.com/harness/harness-core/blob/67e348b36f2858bc059b2ddde669a1fd342c1687/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L174)):*
> ```Java
>     kryo.register(ConfigFileStepParameters.class, 12585);
>     kryo.register(CommandStepInfo.class, 12600);
>     kryo.register(StartupScriptParameters.class, 126001);
> ```

maybe you meant 12601

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 9 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/ConnectionStringsStep.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/34340#-N4ce9Q44j5Fwd1Ne3_p:-N4ce9Q5A9xjPc3E5lfs:b-fzx5bt) ([raw file](https://github.com/harness/harness-core/blob/67e348b36f2858bc059b2ddde669a1fd342c1687/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/ConnectionStringsStep.java#L57)):*
> ```Java
> 
> @OwnedBy(CDP)
> @Singleton
> ```

a step should not be a singleton 



_Code quote:_
```Java

@Slf4j
public class ConnectionStringsStep implements SyncExecutable<ConnectionStringsParameters> {
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/StartupScriptStep.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/34340#-N4ceFU7DcuY1Wp-rQBU:-N4ceFU7DcuY1Wp-rQBV:b-fzx5bt) ([raw file](https://github.com/harness/harness-core/blob/67e348b36f2858bc059b2ddde669a1fd342c1687/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/StartupScriptStep.java#L57)):*
> ```Java
> 
> @OwnedBy(CDP)
> @Singleton
> ```

a step should not be a singleton

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/ConnectionStringsStep.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/34340#-N4ce9Q44j5Fwd1Ne3_p:-N4fEbfP3lH2tnJJTx1d:b-ev4lym) ([raw file](https://github.com/harness/harness-core/blob/67e348b36f2858bc059b2ddde669a1fd342c1687/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/ConnectionStringsStep.java#L57)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

a step should not be a singleton 
</blockquote></details>

agree, changed it
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/StartupScriptStep.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/34340#-N4ceFU7DcuY1Wp-rQBU:-N4fEfY-3z4cLA8BJwsl:b-7ql1td) ([raw file](https://github.com/harness/harness-core/blob/67e348b36f2858bc059b2ddde669a1fd342c1687/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/StartupScriptStep.java#L57)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

a step should not be a singleton 
</blockquote></details>

fixed
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java` line 174 at r1](https://reviewable.io/reviews/harness/harness-core/34340#-N4cWQ-m6GuXPtmhPzDt:-N4fEh5w4lCcqMGVyEvf:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/67e348b36f2858bc059b2ddde669a1fd342c1687/125-cd-nextgen/src/main/java/io/harness/serializer/kryo/NGKryoRegistrar.java#L174)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe you meant 12601
</blockquote></details>

done

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 28 of 34 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests.

**Comment by abosii-harness** [comment]
trigger feature-build

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 34 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: Some of the checks are too old.

**Review by vlica-harness — APPROVED** [review]

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 18 of 34 files at r1, 10 of 10 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 18 of 34 files at r1, 10 of 10 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34340)* status: :shipit: complete! ✓

**Pull request merged**
