### PR TITLE
feat:[CDS-49816]: simplifying filter helper, added automation and bug fixes

### PR DESCRIPTION
**Pull request by vaibhav-si**
## Describe your changes

- Refactored FilterHelper to avoid duplication of code
- Added automation for FilterTagUtils
- Fixes for issues found in testing

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42566)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42566)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42566)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 540 at r2](https://reviewable.io/reviews/harness/harness-core/42566#-NLb-z7OATuT_RsWpuXM:-NLbETktEN6gzcN-cbIs:b72mro8) ([raw file](https://github.com/harness/harness-core/blob/f3c47e147f3b63fa96bd1d753451f0faf51b969e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L540)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This condition was to support use case where an environment gets qualified from the environments filtering and there is a specific filtering applied for the same environments by the user. Are we still handling this? 
</blockquote></details>

This is not a use case right now. Not possible via UI.

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 540 at r2](https://reviewable.io/reviews/harness/harness-core/42566#-NLb-z7OATuT_RsWpuXM:-NLbY_AT7weG5fVAE32y:bb7lyxf) ([raw file](https://github.com/harness/harness-core/blob/f3c47e147f3b63fa96bd1d753451f0faf51b969e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L540)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

This is not a use case right now. Not possible via UI.
</blockquote></details>

ok.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42566)* status: :shipit: complete! ✓

**Pull request merged**
