### PR TITLE
[fix]: [DEL-3835]: Create service and publisher for iterator metrics

### PR DESCRIPTION
**Pull request by rickmarry**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32549)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by rickmarry** [comment]
trigger messagecheck

**Comment by rickmarry** [comment]
trigger ti3

**Review by puneetsar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r6, 1 of 2 files at r7, 2 of 3 files at r10, 5 of 7 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32549)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/metrics/beans/IteratorMetricContext.java` line 21 at r12](https://reviewable.io/reviews/harness/harness-core/32549#-N1AY3cTDDfaVcxD6vGK:-N1AY3cTDDfaVcxD6vGL:b-4xfidy) ([raw file](https://github.com/harness/harness-core/blob/cc9feb71e8a31357aa74e2e3f95dc27993814025/960-persistence/src/main/java/io/harness/metrics/beans/IteratorMetricContext.java#L21)):*
> ```Java
> public class IteratorMetricContext extends AutoMetricContext {
>   public IteratorMetricContext(String threadName) {
>     put("threadName", threadName);
> ```

change this to iteratorName, and same for parameter name passed in.



_Code quote:_
```Java
threadName"
```
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 261 at r12](https://reviewable.io/reviews/harness/harness-core/32549#-N1AYyE4ES_I1_1HHv8z:-N1AYyE5BB9rdGe_6b1B:b-w9ife5) ([raw file](https://github.com/harness/harness-core/blob/cc9feb71e8a31357aa74e2e3f95dc27993814025/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L261)):*
> ```Java
> 
>             iteratorMetricsService.recordIteratorMetricsWithDuration(
>                 iteratorName, Duration.ofMillis(delay), ITERATOR_DELAY_PROCESSING);
> ```

why don't we always capture this metric?



_Code quote:_
```Java
ITERATOR_DELAY_PROCESSING
```
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 286 at r12](https://reviewable.io/reviews/harness/harness-core/32549#-N1AZYbbCTRSasZBgLLA:-N1AZYbbCTRSasZBgLLB:b-tlqu7l) ([raw file](https://github.com/harness/harness-core/blob/cc9feb71e8a31357aa74e2e3f95dc27993814025/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L286)):*
> ```Java
>             log.error("Done with entity but took too long acceptable {}", acceptableExecutionTime.toMillis());
>             iteratorMetricsService.recordIteratorMetricsWithDuration(
>                 iteratorName, Duration.ofMillis(processTime), ITERATOR_DELAY_ON_EXECUTION);
> ```

Same here, we should just record the processing time always. So we have just two metrics, delay and processing_time.



_Code quote:_
```Java
ITERATOR_DELAY_ON_EXECUTION
```

**Review by puneetsar — APPROVED** [review]
> Reviewed 1 of 1 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32549)* status: :shipit: complete! ✓

**Pull request merged**
