### PR TITLE
techdebt: [PIE-8201]: Remove FF usages for Pipeline OPA Governance

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43736)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43736)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/43736#-NNpZgK48CuNvv5kHEvu:-NNpZgK48CuNvv5kHEvv:be60uf0) ([raw file](https://github.com/harness/harness-core/blob/d19d152384a7de7689f10c7ae3be0b3df0a64c70/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L340)):*
> ```Java
>         // Apply all the templateRefs(if any) then check for schema validation.
>         TemplateMergeResponseDTO templateMergeResponseDTO =
>             pipelineTemplateHelper.resolveTemplateRefsInPipeline(pipelineEntity, true, loadFromCache);
> ```

this true flag can be removed from method only?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 331 at r1](https://reviewable.io/reviews/harness/harness-core/43736#-NNpZjWx9vNBBa-9EQob:-NNpZjWx9vNBBa-9EQoc:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/d19d152384a7de7689f10c7ae3be0b3df0a64c70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L331)):*
> ```Java
>       TemplateMergeResponseDTO templateMergeResponseDTO = pipelineTemplateHelper.resolveTemplateRefsInPipeline(
>           pipelineEntity.getAccountId(), pipelineEntity.getOrgIdentifier(), pipelineEntity.getProjectIdentifier(),
>           pipelineYaml, true, true, BOOLEAN_FALSE_VALUE);
> ```

same as above

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43736)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43736)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/43736#-NNpZgK48CuNvv5kHEvu:-NNpauuKBmAz4iceC3V5:b-qdqrow) ([raw file](https://github.com/harness/harness-core/blob/d19d152384a7de7689f10c7ae3be0b3df0a64c70/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L340)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this true flag can be removed from method only?
</blockquote></details>

will do in separate PR
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 331 at r1](https://reviewable.io/reviews/harness/harness-core/43736#-NNpZjWx9vNBBa-9EQob:-NNpawYbE5QODRlFOcbr:b-qdqrow) ([raw file](https://github.com/harness/harness-core/blob/d19d152384a7de7689f10c7ae3be0b3df0a64c70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L331)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

will do in separate PR

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43736)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 331 at r1](https://reviewable.io/reviews/harness/harness-core/43736#-NNpZjWx9vNBBa-9EQob:-NNpfnj-5rFXVI-YkQGt:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/d19d152384a7de7689f10c7ae3be0b3df0a64c70/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L331)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

will do in separate PR
</blockquote></details>

done, discussed offline

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43736)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 340 at r1](https://reviewable.io/reviews/harness/harness-core/43736#-NNpZgK48CuNvv5kHEvu:-NNpfuUl6dcemFmX8eV_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d19d152384a7de7689f10c7ae3be0b3df0a64c70/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L340)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

will do in separate PR
</blockquote></details>

done

**Comment by namanvermah** [comment]
trigger ti1

**Comment by namanvermah** [comment]
trigger ti1

**Comment by abhayganvir** [comment]
trigger messagecheck

**Comment by abhayganvir** [comment]
trigger messagecheck

**Pull request closed without merging**
