### PR TITLE
feat: [CDS-52609]: AWS SAM Deploy, Rollback Steps

### PR DESCRIPTION
**Pull request by sainath-b**
## Describe your changes
AWS SAM Deploy, Rollback Steps code layout. Main logic is there in another PR.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43905)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by sainath-b** [comment]
trigger messagecheck

**Comment by sainath-b** [comment]
trigger ft1

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 17 of 27 files at r1, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43905)* status: 32 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/43905#-NOuUpzz9pyUgvh5fMqe:-NOuUpzz9pyUgvh5fMqf:bxaxlpy) ([raw file](https://github.com/harness/harness-core/blob/c4e3e64842c46c839557638e9f457e9748ec341c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamDeployStep.java#L52)):*
> ```Java
>   public StepResponse finalizeExecutionWithSecurityContext(Ambiance ambiance, StepElementParameters stepParameters,
>       PassThroughData passThroughData, ThrowingSupplier<ResponseData> responseDataSupplier) throws Exception {
>     return StepResponse.builder().status(Status.SUCCEEDED).stepOutcome(null).build();
> ```

nit: can created empty builder instead of null. (non-blocking)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamRollbackStep.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/43905#-NOuVHle6-wl-sFn2p_f:-NOuVHle6-wl-sFn2p_g:b-iicguq) ([raw file](https://github.com/harness/harness-core/blob/c4e3e64842c46c839557638e9f457e9748ec341c/125-cd-nextgen/src/main/java/io/harness/cdng/aws/sam/AwsSamRollbackStep.java#L52)):*
> ```Java
>   public StepResponse finalizeExecutionWithSecurityContext(Ambiance ambiance, StepElementParameters stepParameters,
>       PassThroughData passThroughData, ThrowingSupplier<ResponseData> responseDataSupplier) throws Exception {
>     return StepResponse.builder().status(Status.SUCCEEDED).stepOutcome(null).build();
> ```

nit: same comment as above about using builder.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43905)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 27 files at r1, 7 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43905)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 12 of 27 files at r1, 8 of 15 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43905)* status: :shipit: complete! ✓

**Pull request merged**
