### PR TITLE
feat: [PL-29793]: added index on userGroup collection

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
This query is failing as it does not have any index
`       wingsPersistence.createQuery(UserGroup.class, excludeAuthority)
               .filter(UserGroupKeys.linkedSsoId, ssoId)
               .count();
`
There is also a query on {accountId, linkedSssoId, isSsoLinked} that's why changed this query and added index on these three fields.
Also, this query is just use to check whether count is greater than 0, that's why added limit to 1 only, so that query will perform faster.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40283)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`400-rest/src/test/resources/mongo/indexes.txt` line 823 at r1](https://reviewable.io/reviews/harness/harness-core/40283#-NH3_H4X14Bq_zy3XNJK:-NH3_H4Y0JGfDgJE1Ami:badho6z) ([raw file](https://github.com/harness/harness-core/blob/b9af8fca8b8ec4605a4aeeaab6aaabcd4b0e2905/400-rest/src/test/resources/mongo/indexes.txt#L823)):*
> ```help
> userGroups {"name": "createdAt_1", "background": true} {"createdAt": 1}
> userGroups {"name": "name_1", "background": true} {"name": 1}
> userGroups {"name": "accountId_isSsoLinked_ssoI", "background": true} {"accountId": 1, linkedSsoId": 1, "isSsoLinked": 1}
> ```

minor :  typo, should be  `"accountId_isSsoLinked_ssoId"` I think



_Code quote:_
```help
"accountId_isSsoLinked_ssoI"
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40283)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Review by akash-nagarajan — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40283)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/test/resources/mongo/indexes.txt` line 823 at r1](https://reviewable.io/reviews/harness/harness-core/40283#-NH3_H4X14Bq_zy3XNJK:-NH3g1yS4bEA9Lass2Wz:b-ht9ent) ([raw file](https://github.com/harness/harness-core/blob/b9af8fca8b8ec4605a4aeeaab6aaabcd4b0e2905/400-rest/src/test/resources/mongo/indexes.txt#L823)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor :  typo, should be  `"accountId_isSsoLinked_ssoId"` I think
</blockquote></details>

Also i think it uses alphabetical ordering and this should be added after this line
userGroups {"name": "accountId_1", "background": true} {"accountId": 1}
I believe the checks will fail otherwise

**Review by pbarapatre10 — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40283#-:-NH3ofvM-u5NAOySnjWB:bnfp4nl)* status: 1. unresolved discussions.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40283)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40283)* status: :shipit: complete! ✓

**Pull request merged**
