### PR TITLE
[feat]: [CDS-68538]: Made InputSet Creation independent of EnforceGitX as a setting 

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47313)

### CODE REVIEW

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47313)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/47313#-NU_ys543BgbisK7UbGt:-NU_zKRG2v-2C0-1wVOS:bnkb8uf) ([raw file](https://github.com/harness/harness-core/blob/6633cda8c993952008beb2a1c30c076f6f912913/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I have an unrelated query: why's storeType an argument in finding default storeType?
</blockquote></details>

Ideally it is not required but, to handle backward compatibility incase of ngManager not having the required settings(if pipSrvc is deployed first on diff environments) we will receive 500 from ngManager side : thats why whenver is that case we just pass the same storeType what is in the thread during USER requests .

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47313)* status: 9 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/47313#-NU_zWb38Qebb0cEyhfV:-NUaGcfZBiwdxTF7Dsrm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6633cda8c993952008beb2a1c30c076f6f912913/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L85)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Right now we have 2 code pieces doing same thing but with little difference. We should make them modular enough to not confuse things. Lets syncup on call.
</blockquote></details>

Done.
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/47313#-NU_ys543BgbisK7UbGt:-NUaGdOk8iYZH6oqhBda:bciabrb) ([raw file](https://github.com/harness/harness-core/blob/6633cda8c993952008beb2a1c30c076f6f912913/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L91)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Ideally it is not required but, to handle backward compatibility incase of ngManager not having the required settings(if pipSrvc is deployed first on diff environments) we will receive 500 from ngManager side : thats why whenver is that case we just pass the same storeType what is in the thread during USER requests .
</blockquote></details>

Have removed the try catches as now settings are there in prod

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47313)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by senjucanon2** [comment]
trigger commonchecks

**Comment by senjucanon2** [comment]
trigger pmd

**Comment by senjucanon2** [comment]
trigger codebasehash

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47313)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 7 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47313)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Review by utkarshchoubey-harness — APPROVED** [review]

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
