### PR TITLE
[feat]:[pie-6510]: GetTemplate and applyTemplates v2 api contract 

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Updated the getTemplate and applyTemplatesV2 existing api contracts for integrating with git caching

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck, codebasehash

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 699 at r3](https://reviewable.io/reviews/harness/harness-core/40706#-NHyA6boDlsXdlT-8-pM:-NHyA6boDlsXdlT-8-pN:bvzc8qz) ([raw file](https://github.com/harness/harness-core/blob/385aa488238c915ab7e42d8e3e84ab6bf0ece634/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L699)):*
> ```Java
>   @Hidden
>   public ResponseDTO<TemplateMergeResponseDTO>
>   applyTemplatesV2(@NotNull @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier String accountId,
> ```

can we also add to applyTemplates method ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 16 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — DISMISSED** [review]

**Comment by adivishy1** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 200 at r6](https://reviewable.io/reviews/harness/harness-core/40706#-NI1E61E0uOXzvCIA98G:-NI1E61E0uOXzvCIA98H:bdh9pnq) ([raw file](https://github.com/harness/harness-core/blob/79c1c7597fea19e4ec60957f4c4c4bc65b163a62/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L200)):*
> ```Java
>       @Parameter(description = "This contains details of Git Entity like Git Branch info")
>       @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo,
>       @HeaderParam("Load-From-Cache") @DefaultValue("false") boolean loadFromCache) {
> ```

These changes would have to be done for Spec-first APIs as well.

yes, we have created a ticket to track it: https://harness.atlassian.net/browse/PIE-6660

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: 1. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 200 at r6](https://reviewable.io/reviews/harness/harness-core/40706#-NI1E61E0uOXzvCIA98G:-NI1EtOe1CAUI8xKVoPW:b-2p7n6) ([raw file](https://github.com/harness/harness-core/blob/79c1c7597fea19e4ec60957f4c4c4bc65b163a62/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L200)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

These changes would have to be done for Spec-first APIs as well.
</blockquote></details>

Yes, we have created a ticket for the same: https://harness.atlassian.net/browse/PIE-6660

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 6 of 16 files at r1, 1 of 2 files at r2, 6 of 6 files at r3, 5 of 7 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40706)* status: :shipit: complete! ✓

**Pull request merged**
