### PR TITLE
feat: [IDP-230]: IDP Setup API Auth Integration

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
### Changes
1. Moved NgConnectorManagerClientModule from 120-ng-manager to 878-ng-common-utlities
2. Check user if part of harness support

### Testing scenarios:
**Update GlobalKMS**
image
image

**IDP Provision**
image
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)

### CODE REVIEW

**Comment by vigneswara-propelo** [comment]
trigger messagecheck

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/config/config.yml` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8NAJw3Xzjmm8qeJZA:-NQ8NAJw3Xzjmm8qeJZB:bbgfbp) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/config/config.yml#L71)):*
> ```YAML
>   readTimeOutSeconds: 15
> 
> managerClientConfig:
> ```

Do we need the manager's secret as well?
___
*[`idp-service/src/main/java/io/harness/idp/app/IdpModule.java` line 188 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8NZGJ3TDVqKrTZMbp:-NQ8NZGJ3TDVqKrTZMbq:b-o2o2eb) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/src/main/java/io/harness/idp/app/IdpModule.java#L188)):*
> ```Java
>         appConfig.getAccessControlClientConfiguration(), IDP_SERVICE.getServiceId()));
>     install(
>         new NgConnectorManagerClientModule(appConfig.getManagerClientConfig(), appConfig.getNgManagerServiceSecret()));
> ```

Don't we have to use the manager secret instead of ng-manager secret? Or is the secret same for both?



_Code quote:_
```Java
getNgManagerServiceSecret
```
___
*[`idp-service/src/main/java/io/harness/idp/provision/BUILD.bazel` line 17 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8Rr9J8yhLCP3MLXTH:-NQ8Rr9J8yhLCP3MLXTI:b-1047ef) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/src/main/java/io/harness/idp/provision/BUILD.bazel#L17)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//120-ng-manager:module",
> ```

Do we need to depend on 120-ng-manager? It's a big module, and could add significantly to the sync/build time and binary size :thinking: 
Can you see if there is an alternative? Please check https://github.com/harness/harness-core/pull/37346 once



_Code quote:_
```Starlark
"//120-ng-manager:module",
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 8 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/app/IdpModule.java` line 188 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8NZGJ3TDVqKrTZMbp:-NQ8ehuR4YRz25e6o6WN:b-jrsx49) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/src/main/java/io/harness/idp/app/IdpModule.java#L188)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Don't we have to use the manager secret instead of ng-manager secret? Or is the secret same for both?
</blockquote></details>

the secret seems to be same for both
___
*[`idp-service/src/main/java/io/harness/idp/provision/BUILD.bazel` line 17 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8Rr9J8yhLCP3MLXTH:-NQ8enR-6p-Y4h5284PI:b-umz1c0) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/src/main/java/io/harness/idp/provision/BUILD.bazel#L17)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we need to depend on 120-ng-manager? It's a big module, and could add significantly to the sync/build time and binary size :thinking: 
Can you see if there is an alternative? Please check https://github.com/harness/harness-core/pull/37346 once
</blockquote></details>

sure will check

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 8 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/config/config.yml` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8mV5oA59K74f-WfVB:-NQ8mV5oA59K74f-WfVC:b-xvd7cm) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/config/config.yml#L71)):*
> ```YAML
>   readTimeOutSeconds: 15
> 
> managerClientConfig:
> ```

+1 to Vikyath's comment. managerClientConfig is for CG manager. I believe we need to have a separate secret for that and use it while binding. For local / QA testing, the secret might look same. But it will be mostly different in production environment as cg manager and ng manager are both different modules.



_Code quote:_
```YAML
managerClientConfig
```
___
*[`idp-service/container/scripts/replace_configs.sh` line 133 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8n88F96aODkgpMIxk:-NQ8n88F96aODkgpMIxl:b2aw9u) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/container/scripts/replace_configs.sh#L133)):*
> ```Shell
> 
> if [[ "" != "$MANAGER_CLIENT_BASE_URL" ]]; then
>   export MANAGER_CLIENT_BASE_URL; yq -i '.managerClientConfig.baseUrl=env(MANAGER_CLIENT_BASE_URL)' $CONFIG_FILE
> ```

We need to replace it finally. Take a look at the end of this file. Also after the cg manager secret config change, let's make sure that part is also added here for runtime replacement.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 18 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/config/config.yml` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8NAJw3Xzjmm8qeJZA:-NQJ7l9F7JYSk49lWluC:b-v24dzs) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/config/config.yml#L71)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we need the manager's secret as well?
</blockquote></details>

added manager secret
___
*[`idp-service/config/config.yml` line 71 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8mV5oA59K74f-WfVB:-NQJ7rm9D5etJ9Qp0x83:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/config/config.yml#L71)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

+1 to Vikyath's comment. managerClientConfig is for CG manager. I believe we need to have a separate secret for that and use it while binding. For local / QA testing, the secret might look same. But it will be mostly different in production environment as cg manager and ng manager are both different modules.
</blockquote></details>

Done.
___
*[`idp-service/container/scripts/replace_configs.sh` line 133 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8n88F96aODkgpMIxk:-NQJ824dDIB1NDTGmeai:b-h8uww1) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/container/scripts/replace_configs.sh#L133)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

We need to replace it finally. Take a look at the end of this file. Also after the cg manager secret config change, let's make sure that part is also added here for runtime replacement.
</blockquote></details>

as we discussed, it is not really required to do so. Tested this in PR env and seems to work fine
___
*[`idp-service/src/main/java/io/harness/idp/provision/BUILD.bazel` line 17 at r6](https://reviewable.io/reviews/harness/harness-core/44903#-NQ8Rr9J8yhLCP3MLXTH:-NQJ8E9Q24zo-SDa2NiG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3d85ea1fca0115fa828a40e57c2d5f5eeab56fb2/idp-service/src/main/java/io/harness/idp/provision/BUILD.bazel#L17)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

sure will check
</blockquote></details>

done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 18 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r6, 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 2. unresolved discussions.

**Review by deepharness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r6, 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: 2. unresolved discussions.

**Review by sathish-soundarapandian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44903)* status: :shipit: complete! ✓

**Pull request merged**
