### PR TITLE
fix: [CDS-47225]: populateInstanceStatsData - Add empty string instead of null

### PR DESCRIPTION
**Pull request by vikyathharekal**
### Problem
Daily and hourly Instance stats aggregators are not working for instances when the cloud provider id is null. 

### Fix
Hence if the cloud provider is null, set it to an empty string in the DB so that the aggregation works as usual.

The other 2 options were -
1. We don't fetch and use `CLOUDPROVIDERID` anywhere. This has been baggage from the CG code. We could remove this completely. But there could be other use cases in CG which we don't have in NG now. Hence decided not to remove it now.
2. Append the query with `CLOUDPROVIDERID is NULL` for GitOps and `CLOUDPROVIDERID=value` for other kinds.

## Testing
1. GitOps Hour Aggregation
gitops hour
3. GitOps Day Aggregation
gitops day
4. Non GitOps Hour Aggregation
non gitops hour
5. Non GitOps Day Aggregation 
non gitops day

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40656)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40656)* status: 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/models/InstanceStats.java` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/40656#-NHiUhm95A0BBZEEO23O:-NHiUhm95A0BBZEEO23P:b-m74ajv) ([raw file](https://github.com/harness/harness-core/blob/38b881656cf72e914511f5e2d8662568abcc31d3/126-instance/src/main/java/io/harness/models/InstanceStats.java#L0)):*
where was this used?

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40656)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/models/InstanceStats.java` line  at r1](https://reviewable.io/reviews/harness/harness-core/40656#-NHiUhm95A0BBZEEO23O:-NHiWwab91jdQcRhaKBi:bjap978) ([raw file](https://github.com/harness/harness-core/blob/38b881656cf72e914511f5e2d8662568abcc31d3/126-instance/src/main/java/io/harness/models/InstanceStats.java#L)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

where was this used?
</blockquote></details>

We were fetching the whole record, but we just needed the reportedAt Timestamp. 
I had added a mongo projection in one of my previous PR.
https://github.com/harness/harness-core/pull/40075/files#diff-13822295b3e13785421b05cbdd85dbfd19c2361cbfdd99b676380ab90421327eR31

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40656)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/models/InstanceStats.java` line  at r1](https://reviewable.io/reviews/harness/harness-core/40656#-NHiUhm95A0BBZEEO23O:-NHiXQPD6cRFoeBRJa8e:b-fivwnw) ([raw file](https://github.com/harness/harness-core/blob/38b881656cf72e914511f5e2d8662568abcc31d3/126-instance/src/main/java/io/harness/models/InstanceStats.java#L)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We were fetching the whole record, but we just needed the reportedAt Timestamp. 
I had added a mongo projection in one of my previous PR.
https://github.com/harness/harness-core/pull/40075/files#diff-13822295b3e13785421b05cbdd85dbfd19c2361cbfdd99b676380ab90421327eR31
</blockquote></details>

Forgot to remove this last time

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40656)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40656)* status: :shipit: complete! ✓

**Pull request merged**
