### PR TITLE
feat:[CDS-41717]: Add support to PowerShell download from Artifactory using environment proxy

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
Support to execute command to download the artifact from Artifactory using the proxy value read from the environment variable `HTTP_PROXY`, to enable this feature needs to set the variable `HARNESS_ENV_PROXY` to true in the same target server.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40264)

### CODE REVIEW

**Comment by lasdox** [comment]
Shouldn't we keep logging the http_proxy usage?

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40264)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — COMMENTED** [review]
We keep logging when both variables are set and keep the current behavior if none is set. When the HARNESS_ENV_PROXY is set to true and the HTTP_PROXY is not set, we add a message to the output as this sound like a misconfiguration.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40264#-:-NHjBQDv5JW7Wl-uNZDZ:b-eputif)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40264)* status: :shipit: complete! ✓

**Pull request merged**
