### PR TITLE
[techdebt]: [PIE-4188]: Add tests for GovernanceServiceImpl and NoopTaskExecutor

### PR DESCRIPTION
**Pull request by namanvermah**
Added tests for NoopTaskExecutor.java, GovernanceServiceImpl.java, EngineExpressionServiceImpl. Was supposed to add tests for AmbianceExpressionEvaluator as well, but @sahilhindwani-harness already increased the coverage for that.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34889)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by naidu-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34889)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34889#-:-N5rxprm4PUK0_IJWqYI:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34889)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34889)* status: :shipit: complete! ✓

**Pull request merged**
