### PR TITLE
[feat]: [CI-3287]: Add support for pull app.harness.io for pulling OOTB step image

### PR DESCRIPTION
**Pull request by shubham149**
…images

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30090)

### CODE REVIEW

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30090#-:-Mtm9CWN-965iaOm0zaW:bnfp4nl)* status: 2 file(s) to review.

**Comment by shubham149** [comment]
trigger messagecheck

**Review by aman-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30090#-:-Mtmdqf22qOBHM4a1kPH:bnfp4nl)* status: :shipit: complete! ✓

**Comment by USB-05** [comment]
trigger compile

**Pull request merged**
