### PR TITLE
[feat]: [SRM-12244]: Added flag failOnNoAnalysis and implementation

### PR DESCRIPTION
**Pull request by n00bitax**
…ehind it

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38699)

### CODE REVIEW

**Comment by n00bitax** [comment]
trigger ti4

**Review by praveensugavanam — DISMISSED** [review]
> Reviewed 2 of 8 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38699)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHd6DD8c6ejNRliKyl:-NEHd6DD8c6ejNRliKym:bf8dtqq) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java#L95)):*
> ```Java
>         .envIdentifier(createExpressionField(ENV_IDENTIFIER_EXPRESSION))
>         .deploymentTag(spec.getDeploymentTag())
>         .failOnNoAnalysis(spec.getFailOnNoAnalysis())
> ```

refer to comment below in VerificationJobSpec
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHcotd3S-qUrL2lVtr:-NEHcotf7-Xd_kXdA9YU:b-kpy845) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java#L62)):*
> ```Java
>   @ApiModelProperty(hidden = true)
>   public VerificationJobBuilder getVerificationJobBuilder() {
>     RuntimeParameter failOnNoAnalysisFromParam =
> ```

can we instead override getFailOnNoAnalysis ? If we do that, it will help CVNGStep also. Right now, over there you're doing `spec.failOnAnalysis' which might be null. 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHdgT_CLik_1Lhdhls:-NEHdgT_CLik_1Lhdhlt:b-pllop1) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java#L65)):*
> ```Java
>         getFailOnNoAnalysis() == null || getFailOnNoAnalysis().getValue() == null
>         ? RuntimeParameter.builder().value("false").build()
>         : RuntimeParameter.builder().value(getFailOnNoAnalysis().getValue().toString()).build();
> ```

we dont seem to be setting isRuntimeParam() at all in this builder ?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 388 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHeWF22XsqB4TrkQSL:-NEHeWF22XsqB4TrkQSM:b623pw9) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L388)):*
> ```Java
>         if (optionalRisk.isPresent()) {
>           Risk risk = optionalRisk.get();
>           if (risk.isGreaterThanEq(Risk.NEED_ATTENTION)
> ```

I know that at this point it means the same, but let's not change the condition from Observe to Needs attention. In your if, you can just say 
```if (risk.isGreaterThan(Risk.Observe))``` 
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImplTest.java` line 449 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHfE1o4E-czGKwM5Ya:-NEHfE1o4E-czGKwM5Yb:b-xqagxm) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/test/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImplTest.java#L449)):*
> ```Java
>     assertThat(activityVerificationStatus).isEqualTo(VERIFICATION_FAILED);
>   }
> ```

Please add a test where isRuntimeParam is set to true.

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38699)* status: 7 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHd6DD8c6ejNRliKyl:-NE_6ooH2cW-hT7GoC22:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java#L95)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

refer to comment below in VerificationJobSpec
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHcotd3S-qUrL2lVtr:-NE_6kNz1bZbudL9K8oM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java#L62)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

can we instead override getFailOnNoAnalysis ? If we do that, it will help CVNGStep also. Right now, over there you're doing `spec.failOnAnalysis' which might be null. 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHdgT_CLik_1Lhdhls:-NE_6krB5oydAqmoDE8i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/VerificationJobSpec.java#L65)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

we dont seem to be setting isRuntimeParam() at all in this builder ?
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 388 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHeWF22XsqB4TrkQSL:-NE_6mzUDG8QYRnP4Omd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L388)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

I know that at this point it means the same, but let's not change the condition from Observe to Needs attention. In your if, you can just say 
```if (risk.isGreaterThan(Risk.Observe))``` 

</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImplTest.java` line 449 at r2](https://reviewable.io/reviews/harness/harness-core/38699#-NEHfE1o4E-czGKwM5Ya:-NE_6nrsAI8rjWiiBj_5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02d59a4a29466aaf9fabca88acff05af5d4798f2/300-cv-nextgen/src/test/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImplTest.java#L449)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Please add a test where isRuntimeParam is set to true.
</blockquote></details>

Done.

**Review by n00bitax — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38699)* status: 7 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained.

**Pull request merged**
