### PR TITLE
[feat]: [CDS-80142]: Added a new method updateGitCacheForWebhookEvent for updating cache for webhook events

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added a new method updateGitCacheForWebhookEvent for updating cache for webhook events. Have tested out this locally, its working as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmUpdateGitCacheForWebhookEventRequestDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/53369#-NfPOlHLEvBknLCu3fDi:-NfPOlHLEvBknLCu3fDj:bjpdqyf) ([raw file](https://github.com/harness/harness-core/blob/beaa7b670db60b5ebfcf559e43e51a32a4b42ecb/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmUpdateGitCacheForWebhookEventRequestDTO.java#L23)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @Builder
> public class ScmUpdateGitCacheForWebhookEventRequestDTO {
> ```

naming should be agnostic of webhook

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/53369#-NfPQqxG7qKxwENMRzBE:-NfPQqxG7qKxwENMRzBF:b-caz2yr) ([raw file](https://github.com/harness/harness-core/blob/beaa7b670db60b5ebfcf559e43e51a32a4b42ecb/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L26)):*
> ```Java
>   @Inject private ScmFacilitatorService scmFacilitatorService;
>   @Inject private GitXWebhookEventService gitXWebhookEventService;
>   private ScmUpdateGitCacheForWebhookEventRequestDTO scmUpdateGitCacheForWebhookEventRequestDTO;
> ```

we shouldn't take next service arguments directly in this helper.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmUpdateGitCacheForWebhookEventRequestDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/53369#-NfPOlHLEvBknLCu3fDi:-NfPd546BFerIQZW0QX0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/beaa7b670db60b5ebfcf559e43e51a32a4b42ecb/136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/ScmUpdateGitCacheForWebhookEventRequestDTO.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

naming should be agnostic of webhook
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/53369#-NfPQqxG7qKxwENMRzBE:-NfPd5NgCHeQuPRqrw91:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/beaa7b670db60b5ebfcf559e43e51a32a4b42ecb/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookCacheUpdateRunnable.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't take next service arguments directly in this helper.
</blockquote></details>

Done.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/ScmFacilitatorService.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/53369#-NfUccW10qITOrQaNSjG:-NfUccW10qITOrQaNSjH:bhhoj7u) ([raw file](https://github.com/harness/harness-core/blob/4bf9cb4503c8a794cd543e3d189bf23d9c58dbc3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/ScmFacilitatorService.java#L72)):*
> ```Java
>       ScmGetBatchFilesByBranchRequestDTO scmGetBatchFilesByBranchRequestDTO);
> 
>   void updateGitCacheForWebhookEvent(ScmUpdateGitCacheForRequestDTO scmUpdateGitCacheForRequestDTO);
> ```

this is generic method, how does it depend on webhook?

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/ScmFacilitatorService.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/53369#-NfUccW10qITOrQaNSjG:-NfUgvyz72HSS_EjqgGK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4bf9cb4503c8a794cd543e3d189bf23d9c58dbc3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/ScmFacilitatorService.java#L72)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is generic method, how does it depend on webhook?
</blockquote></details>

Done.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53369)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — DISMISSED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger ut2

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
