### PR TITLE
feat: [PL-24095]: added UTs for getFilePathWithoutStartingSlash method

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31807)

### CODE REVIEW

**Review by goelsatyam2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31807)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 80 at r1](https://reviewable.io/reviews/harness/harness-core/31807#-MzFNnFS9t3xaG_OEI-i:-MzFNnFS9t3xaG_OEI-j:bsldopq) ([raw file](https://github.com/harness/harness-core/blob/8895b2ee8e5e929a25700900e0a7b50104bf5cb4/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L80)):*
> ```Java
>       throw new InvalidRequestException("File Path cannot be empty");
>     }
>     return StringUtils.stripStart(path, "/");
> ```

"/" can be moved to a constant

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by goelsatyam2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31807)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java, line 27 at r2](https://reviewable.io/reviews/harness/harness-core/31807#-MzFWy8LBv31DpJGxMgF:-MzFWy8LBv31DpJGxMgG:b-ok8nq4) ([raw file](https://github.com/harness/harness-core/blob/78d165867275a6a9b46938540d35b9ba1f74c6f8/953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils/GitSyncFilePathUtils.java#L27)):*
> ```Java
> @UtilityClass
> public class GitSyncFilePathUtils {
>   public static final String SLASH = "/";
> ```

Slash can be a private const variable.
And SLASH variable name doesn't tell why it's being used, can be renamed to something like file_path_seperator.

**Review by goelsatyam2 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31807)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31807)* status: :shipit: complete! ✓

**Pull request merged**
