### PR TITLE
fix: [CDS-54666]: k8s apply are similar

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44648)

### CODE REVIEW

**Review by brettzu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44648)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/data/structure/CompareUtils.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/44648#-NPe4K6W1fZ1d9XgNBSY:-NPe4K6W1fZ1d9XgNBSZ:b-ahapxa) ([raw file](https://github.com/harness/harness-core/blob/6ec97dc32a2d554e80f3f220518ce4782b1cb5c2/980-commons/src/main/java/io/harness/data/structure/CompareUtils.java#L16)):*
> ```Java
> @UtilityClass
> public class CompareUtils {
>   public boolean compareNullableStrings(String string1, String string2) {
> ```

Isn't there a StringUtils method for this already?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44648)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/data/structure/CompareUtils.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/44648#-NPe4K6W1fZ1d9XgNBSY:-NPtGY9ZAdF9oi7O0tfq:b32wsm) ([raw file](https://github.com/harness/harness-core/blob/6ec97dc32a2d554e80f3f220518ce4782b1cb5c2/980-commons/src/main/java/io/harness/data/structure/CompareUtils.java#L16)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

Isn't there a StringUtils method for this already?
</blockquote></details>

no

**Review by brettzu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44648)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/data/structure/CompareUtils.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/44648#-NPe4K6W1fZ1d9XgNBSY:-NPunK-U5pgrM0VF29ga:b-9eypy4) ([raw file](https://github.com/harness/harness-core/blob/6ec97dc32a2d554e80f3f220518ce4782b1cb5c2/980-commons/src/main/java/io/harness/data/structure/CompareUtils.java#L16)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

no
</blockquote></details>

Yes there is.

StringsUtils.equals(str1, str2)

Decompiled it looks like this:



_Code snippet:_
```Java
    public static boolean equals(CharSequence cs1, CharSequence cs2) {
        if (cs1 == cs2) {
            return true;
        } else if (cs1 != null && cs2 != null) {
            return cs1 instanceof String && cs2 instanceof String ? cs1.equals(cs2) : CharSequenceUtils.regionMatches(cs1, false, 0, cs2, 0, Math.max(cs1.length(), cs2.length()));
        } else {
            return false;
        }
    }
```

**Review by brettzu — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44648)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by sribalij — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44648)* status: :shipit: complete! ✓

**Pull request merged**
