### PR TITLE
fix: [CDP-19129]: optimizing logging and rollback issue

### PR DESCRIPTION
**Pull request by anilchowdhury-harness**
fix: [CDP-19129]: optimizing logging and rollback issue

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

[CDP-19129]: https://harness.atlassian.net/browse/CDP-19129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30275)

### CODE REVIEW

**Comment by anilchowdhury-harness** [comment]
trigger messagecheck

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275#-:-MuR3rE48zTNszmoWMg-:bnfp4nl)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by jelenaHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275)* status: 24 file(s) to review.

**Review by jelenaHarness — DISMISSED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275)* status: :shipit: complete! ✓

**Review by jelenaHarness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275)* status: Some of the checks are too old. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275#-:-MupK_Fz9II0ul591BJ_:bnfp4nl)* status: Some of the checks are too old.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275#-:-MupKr0S4Cglv696QZRd:bnfp4nl)* status: Some of the checks are too old.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275#-:-MupMFR58QLGbwUsOMDg:bnfp4nl)* status: Some of the checks are too old.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/AzureAppServiceDeploymentService.java, line 218 at r2](https://reviewable.io/reviews/harness/harness-core/30275#-MvE2whX4BHXpTP-vn2n:-MvE2whX4BHXpTP-vn2o:b-4kqwyp) ([raw file](https://github.com/harness/harness-core/blob/b9487266328f215e6c0a7069a2b3e56c468cd456/260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/AzureAppServiceDeploymentService.java#L218)):*
> ```Java
> 
>     try {
>       DateTime startSlotTime = new DateTime(DateTimeZone.UTC).minusMinutes(1);
> ```

Minor - why do we need minus one minute here?
___
*[960-api-services/src/main/java/io/harness/azure/impl/SlotLogStreamer.java, line 58 at r2](https://reviewable.io/reviews/harness/harness-core/30275#-MvE2l2v3_EjQFLAH06-:-MvE2l2v3_EjQFLAH060:bjtmmoa) ([raw file](https://github.com/harness/harness-core/blob/b9487266328f215e6c0a7069a2b3e56c468cd456/960-api-services/src/main/java/io/harness/azure/impl/SlotLogStreamer.java#L58)):*
> ```Java
>     this.logCallback = logCallback;
>     this.logParser = new AzureLogParser();
>     this.startTime = startTime;
> ```

Minor -  we could initialise start time here, 
this.startTime  = new DateTime(DateTimeZone.UTC).minusMinutes(1)

**Review by jelenaHarness — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30275)* status: :shipit: complete! ✓

**Pull request closed without merging**
