### PR TITLE
fix: [DEL-6293]: Change DelegateServiceDriverException to extend from WingsException

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

DelegateServiceDriverException does not have a corresponding Mapper, hence it gets mapped to GenericExceptionMapper, which hides the exception details from users.

We have two options: 1) Add a new mapper for DelegateServiceDriverException 2) Just make DelegateServiceDriverException to be a wings exception, so that it can use WingsExceptionMapper

We have implemented the second one, since many other delegate exceptions inherit from WingsException, such as DelegateNotAvailableException

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)

### CODE REVIEW

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 206 at r2](https://reviewable.io/reviews/harness/harness-core/46724#-NT_fvsk6H5tij_qztie:-NT_fvsk6H5tij_qztif:ba5z45z) ([raw file](https://github.com/harness/harness-core/blob/150c20e303efb5ff269501fa83004a5127b04a1e/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L206)):*
> ```Java
>         throw ex;
>       } else {
>         throw new WingsException(String.format(
> ```

maybe can add a setter to DelegateServiceDriverException, and set the message



_Code quote:_
```Java
DelegateServiceDriverException
```
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 701 at r2](https://reviewable.io/reviews/harness/harness-core/46724#-NT_fk3U4EBf_LNTDYQa:-NT_fk3U4EBf_LNTDYQb:b-zcmryh) ([raw file](https://github.com/harness/harness-core/blob/150c20e303efb5ff269501fa83004a5127b04a1e/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L701)):*
> ```Java
>         throw ex;
>       } else {
>         throw new WingsException(ex);
> ```

looks like we can directly throw the DelegateServiceDriverException ex because it's WingsException

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 206 at r2](https://reviewable.io/reviews/harness/harness-core/46724#-NT_fvsk6H5tij_qztie:-NT_q4oa3YhxCNsgYKmy:b-b5gtsc) ([raw file](https://github.com/harness/harness-core/blob/150c20e303efb5ff269501fa83004a5127b04a1e/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L206)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

maybe can add a setter to DelegateServiceDriverException, and set the message
</blockquote></details>

setter would not have access to message either, so will need to add method in parent.. 

instead just added ex to the new exception, so that the context is preserved
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java` line 701 at r2](https://reviewable.io/reviews/harness/harness-core/46724#-NT_fk3U4EBf_LNTDYQa:-NT_qGSVBKusABjEHzR7:b-x0qs0c) ([raw file](https://github.com/harness/harness-core/blob/150c20e303efb5ff269501fa83004a5127b04a1e/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L701)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

looks like we can directly throw the DelegateServiceDriverException ex because it's WingsException 
</blockquote></details>

Just removed the entire section,. Wingsexception will throw it regardless

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)* status: :shipit: complete! ✓

**Comment by gn-harness** [comment]
trigger ut0, ut2, ut3, ut7, ut9

**Comment by gn-harness** [comment]
trigger compatibility

**Comment by gn-harness** [comment]
trigger compatibility_checks

**Comment by gn-harness** [comment]
trigger pr_openapi_check

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46724)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]

**Pull request merged**
