### PR TITLE
[feat]: [PL-24523]: LDAP Password Secret Reference, Enum Introduction for AuthType.

### PR DESCRIPTION
**Pull request by boopesh007**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)

### CODE REVIEW

**Review by shashank-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: :shipit: complete! ✓

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: :shipit: complete! ✓

**Review by manish-manchanda — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939#-:-N1e3uHHDLqldzY0t0bk:bnfp4nl)* status: :shipit: complete! ✓

**Review by reetika04 — DISMISSED** [review]
> Reviewed 8 of 9 files at r1, 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by devesh-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32939)* status: :shipit: complete! ✓

**Pull request merged**
