### PR TITLE
[feat]:[PL-26309]: Template create integration with gitX

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Template create integration with gitX, 
tests covered
	1. No gitSync
		working
	2. Old gitSync
		working
	3. New gitSync
		3.1 Inline - working
		3.2 Remote - different connector refs - github connector ref working
		3.3 StoreType Null - github connector ref working - error scenario

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)

### CODE REVIEW

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/35039#-N6SIMV7Dsp0qaeulwHl:-N6SIMV7Dsp0qaeulwHm:b-s4o86h) ([raw file](https://github.com/harness/harness-core/blob/6954d5991b2e438c11c45f7b90994eabcfa4acbe/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L88)):*
> ```Java
>       Scope scope = buildScope(templateToSave);
>       String yamlToPush = templateToSave.getYaml();
>       addGitParamsToPipelineEntity(templateToSave, gitEntityInfo);
> ```

change the method method, templateEntity

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/35039#-N6SIMV7Dsp0qaeulwHl:-N6SL535Bg0iN0B1eRF8:bus731g) ([raw file](https://github.com/harness/harness-core/blob/6954d5991b2e438c11c45f7b90994eabcfa4acbe/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L88)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

change the method method, templateEntity
</blockquote></details>

good catch, will update

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/35039#-N6SIMV7Dsp0qaeulwHl:-N6ScLEY8361-ZRhPSzm:b32w0x) ([raw file](https://github.com/harness/harness-core/blob/6954d5991b2e438c11c45f7b90994eabcfa4acbe/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L88)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

good catch, will update
</blockquote></details>

OK

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sup896AI15G1fu3Oy:-N6Sup8A1Naljs7SlhKM:b-bny5fu) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L56)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, Criteria criteria, Update update);
> 
>   TemplateEntity updatePreviousStableTemplateFalseMongoDirectly(TemplateEntity templateEntity);
> ```

This is repo level method so we don't need to mention "falseMongoDirectly" or anything. We should simply name "updateIsStableTemplate(Template, Boolean))". It should mark the field true/false based on the input. Its a repo level method so should be more generic without any service logical sense.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SvOZgEMMSx4HGDXNp:-N6SvOZgEMMSx4HGDXNq:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L58)):*
> ```Java
>   TemplateEntity updatePreviousStableTemplateFalseMongoDirectly(TemplateEntity templateEntity);
> 
>   TemplateEntity updatePreviousLastUpdatedTemplateFalseMongoDirectly(TemplateEntity templateEntity);
> ```

same as above

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SvweX8e6XKC5YRRmI:-N6SvweX8e6XKC5YRRmJ:bkuhkql) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L94)):*
> ```Java
>       gitAwareEntityHelper.createEntityOnGit(templateToSave, yamlToPush, scope);
>     } else {
>       log.info(String.format(
> ```

In the log, it should be "INLINE for "template"" not "Pipeline"

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 290 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SwCO-6aWFtQ_d67qa:-N6SwCO-6aWFtQ_d67qb:b-iigsc3) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L290)):*
> ```Java
>   }
> 
>   Scope buildScope(TemplateEntity templateEntity) {
> ```

This method should be in a util class, not in custom repository.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SwK5G20C3JqLFjHOy:-N6SwK5H7YKiJLAcqdZb:b-qfy09v) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
> ```Java
>   }
> 
>   void addGitParamsToTemplateEntity(TemplateEntity templateEntity, GitEntityInfo gitEntityInfo) {
> ```

lets make it private

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SwRVNC9QBWKd07pdY:-N6SwRVOBzZONrV_SLG5:bpjdajo) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L142)):*
> ```Java
>               finalTemplateEntity.getOrgIdentifier(), finalTemplateEntity.getProjectIdentifier(),
>               finalTemplateEntity.getIdentifier(), finalTemplateEntity.getVersionLabel());
>           if (isOldGitSync(finalTemplateEntity)) {
> ```

This complete block is being repeated. Lets make this a separate private method.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 755 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sxmaq1gKwOQIF3X-x:-N6SxmarCOTnQ13YSacA:b93ief4) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L755)):*
> ```Java
>       // Update the git context with details of the template on which the operation is going to run.
>       if (isOldGitSync(oldTemplate)) {
>         try (TemplateGitSyncBranchContextGuard ignored = templateServiceHelper.getTemplateGitContextForGivenTemplate(
> ```

shouldn't this try() block be outside the if() block? Basically "if" should be inside try catch.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 790 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SzKVSB4ur2zvkGEFx:-N6SzKVSB4ur2zvkGEFy:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L790)):*
> ```Java
>         // Update the git context with details of the template on which the operation is going to run.
>         try (TemplateGitSyncBranchContextGuard ignored = templateServiceHelper.getTemplateGitContextForGivenTemplate(
>                  oldTemplate, GitContextHelper.getGitEntityInfo(),
> ```

same as above.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6T-Tov1lsP-19K4Pgg:-N6T-Tow5wCiSxstRaIz:bsg778t) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L12)):*
> ```Java
> import static io.harness.annotations.dev.HarnessTeam.CDC;
> 
> import static org.springframework.data.mongodb.core.query.Query.query;
> ```

We should add UTs for repo layer as well.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sup896AI15G1fu3Oy:-N6Sz3huEOplW2umOIVT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is repo level method so we don't need to mention "falseMongoDirectly" or anything. We should simply name "updateIsStableTemplate(Template, Boolean))". It should mark the field true/false based on the input. Its a repo level method so should be more generic without any service logical sense.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SvOZgEMMSx4HGDXNp:-N6Sz4YE4iHywciuA-cu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 12 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6T-Tov1lsP-19K4Pgg:-N6T4xW_1M37-U7c4NvK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L12)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should add UTs for repo layer as well.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sv_3L4GcxEeDd-INQ:-N6T05XK6U8NKnagiruv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L76)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets move this check to somewhere at common util layer or a private method in this class itself, something like "isInlineEntity" etc.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SvweX8e6XKC5YRRmI:-N6T09Vk9rfDVL5KErrH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L94)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

In the log, it should be "INLINE for "template"" not "Pipeline"
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 290 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SwCO-6aWFtQ_d67qa:-N6T1E7M9z4ClnlZtvjB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L290)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This method should be in a util class, not in custom repository.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SwK5G20C3JqLFjHOy:-N6T0mu86ySy16RkkyqN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets make it private
</blockquote></details>

Done.



_Code quote:_
```Java
          templateToSave.getIdentifier(), templateToSave.getProjectIdentifier(),
          templateToSave.getAccountIdentifier()));
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SwRVNC9QBWKd07pdY:-N6T1wlQ67hwqh3fJxNI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L142)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This complete block is being repeated. Lets make this a separate private method.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 755 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sxmaq1gKwOQIF3X-x:-N6T4XEl1RTitzd3Gtw7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L755)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't this try() block be outside the if() block? Basically "if" should be inside try catch.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 790 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6SzKVSB4ur2zvkGEFx:-N6T4Y4Q5cifysrJaW5M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L790)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 846 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6T-JEE8vbj9pTqM_jp:-N6T3624A-ieCCC09F9J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L846)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets move this also to a util class. cc @inderschera please suggest if there's such a class where we can move it.
</blockquote></details>

Done.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/35039#-N6SIMV7Dsp0qaeulwHl:-N6SrhRa3siIo8Nhgbx4:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/6954d5991b2e438c11c45f7b90994eabcfa4acbe/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L88)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done

**Review by bhavya181 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 7 file(s) to review. 11. unresolved discussions. 1 of 2 approvals obtained.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 5 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sv_3L4GcxEeDd-INQ:-N6iDyug8x4ywvqr_fX_:b-11l3yv) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L76)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: use TemplateUtils.isInlineEntity(). Calling static methods with their class provide better readability and understanding.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/35039#-N6hYKmAAl_s2A57paJF:-N6hv9vN1x5M93Hzyp70:bhvys03) ([raw file](https://github.com/harness/harness-core/blob/699339caf7452c5da92db3a171e3b510473f13e0/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L64)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

This is in 878-ng-common-utils not in 120-ng-manager, i dont think need to have a separate feature flag helper.
</blockquote></details>

Even then let's create a separate helper. 
1. This would give more flexibility if we want to add cache for feature flags for template service. 
2. We are going towards independent microservice deployment, would be better to have separate codes for both. 
3. Getting feature flag requires communication to cg-manager, if the helper is in below layers, and someone uses it who doesn't have config overrides set for cg-manager, they probably would have to spend sometime debugging why it's not working.
I feel this helper should be in respective microservice only.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 102 at r5](https://reviewable.io/reviews/harness/harness-core/35039#-N6iEdyL9FFHQJoxLyYu:-N6iEdyL9FFHQJoxLyYv:b1fq90x) ([raw file](https://github.com/harness/harness-core/blob/49ce72a9dabd6e487ef61e184a1d851b2a091b5a/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L102)):*
> ```Java
>     } else {
>       throw new InvalidRequestException(
>           String.format("Git simplification was not enabled for Project [%s] in Account [%s]",
> ```

Since templates are at all scopes, error message should be more focused on where the git simplifaction is not enabled.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 282 at r5](https://reviewable.io/reviews/harness/harness-core/35039#-N6hw92L-0oqzTOk3Lfs:-N6hw92L-0oqzTOk3Lft:b-x5gqch) ([raw file](https://github.com/harness/harness-core/blob/49ce72a9dabd6e487ef61e184a1d851b2a091b5a/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L282)):*
> ```Java
>         .is(templateEntity.getBranch())
>         .and(TemplateEntityKeys.repo)
>         .is(templateEntity.getRepo());
> ```

Should be getYamlGitConfigRef() (repo in old git experience is yamlGitConfigRef)

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 840 at r5](https://reviewable.io/reviews/harness/harness-core/35039#-N6ixGzr2_FgGGoNuDkL:-N6ixGzr2_FgGGoNuDkM:b-sj2hj3) ([raw file](https://github.com/harness/harness-core/blob/49ce72a9dabd6e487ef61e184a1d851b2a091b5a/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L840)):*
> ```Java
> 
>   private TemplateEntity saveTemplate(TemplateEntity templateEntity, String comments)
>       throws io.harness.exception.InvalidRequestException {
> ```

can we simplify the import for this exception? It should be simply "InvalidRequestException"

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/35039#-N6Sv_3L4GcxEeDd-INQ:-N6kUpn45_u7kRHLcpHv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60eeeaed825cb998e18144f0098deea1ffea8884/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L76)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: use TemplateUtils.isInlineEntity(). Calling static methods with their class provide better readability and understanding.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/35039#-N6hYKmAAl_s2A57paJF:-N6kUPP6Es5zLwu1XtvN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/699339caf7452c5da92db3a171e3b510473f13e0/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L64)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Even then let's create a separate helper. 
1. This would give more flexibility if we want to add cache for feature flags for template service. 
2. We are going towards independent microservice deployment, would be better to have separate codes for both. 
3. Getting feature flag requires communication to cg-manager, if the helper is in below layers, and someone uses it who doesn't have config overrides set for cg-manager, they probably would have to spend sometime debugging why it's not working.
I feel this helper should be in respective microservice only.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 282 at r5](https://reviewable.io/reviews/harness/harness-core/35039#-N6hw92L-0oqzTOk3Lfs:-N6kVBgB6nRW3e1_gFgL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49ce72a9dabd6e487ef61e184a1d851b2a091b5a/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L282)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Should be getYamlGitConfigRef() (repo in old git experience is yamlGitConfigRef)
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 840 at r5](https://reviewable.io/reviews/harness/harness-core/35039#-N6ixGzr2_FgGGoNuDkL:-N6kVPsl5MAVvs3E_zeo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49ce72a9dabd6e487ef61e184a1d851b2a091b5a/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L840)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we simplify the import for this exception? It should be simply "InvalidRequestException"
</blockquote></details>

Done.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 1 change requests. 16. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 102 at r5](https://reviewable.io/reviews/harness/harness-core/35039#-N6iEdyL9FFHQJoxLyYu:-N6kaxa563G5I3SvDmU_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49ce72a9dabd6e487ef61e184a1d851b2a091b5a/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L102)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Since templates are at all scopes, error message should be more focused on where the git simplifaction is not enabled.
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 6 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 286 at r6](https://reviewable.io/reviews/harness/harness-core/35039#-N6kbtgs6TQt6ShzBjAC:-N6kbtgtCyTy2lx1d0-e:b-4e4cqf) ([raw file](https://github.com/harness/harness-core/blob/2c0c4075656a50a5dd8f7bf4e5da5fabd0f5a7a6/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L286)):*
> ```Java
>         .and(TemplateEntityKeys.branch)
>         .is(templateEntity.getBranch())
>         .and(TemplateEntityKeys.repo)
> ```

change to TemplateEntityKeys.yamlGitConfigRef

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: 7 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 286 at r6](https://reviewable.io/reviews/harness/harness-core/35039#-N6kbtgs6TQt6ShzBjAC:-N6lA2MU43LcRLOzmOr-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c0c4075656a50a5dd8f7bf4e5da5fabd0f5a7a6/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L286)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

change to TemplateEntityKeys.yamlGitConfigRef
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 2 of 4 files at r3, 3 of 4 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039#-:-N6lAA967q0uOS7FbDZf:bnfp4nl)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 3 of 4 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: :shipit: complete! ✓

**Review by bhavya181 — APPROVED** [review]
> Reviewed 3 of 4 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35039)* status: :shipit: complete! ✓

**Pull request merged**
