### PR TITLE
fix: [CDS-45853]: handling for unresolved connector ref in InfrastructureStepHelper

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Better error message if connector ref remains unresolved in the infrastructure spec
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40176)

### CODE REVIEW

**Review by hingerabhinav — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40176)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/40176#-NGz8aXL9A7ZRXTRXNpi:-NGz8aXL9A7ZRXTRXNpj:b-u2233b) ([raw file](https://github.com/harness/harness-core/blob/8ddbb6391ba08a27e34db5cae409343675de8302/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStepHelper.java#L88)):*
> ```Java
>       if (NGExpressionUtils.isRuntimeField(connectorRef.getExpressionValue())) {
>         throw new InvalidRequestException(
>             "Connector ref is a runtime input but its value not provided in the infrastructure");
> ```

nit: its value "is" not provided



_Code quote:_
```Java
 throw new InvalidRequestException("Connector ref field not pr
```

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40176)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40176#-NGzBukBEgn7W3XHwbPL:-NGzBukC3IhIEmf_B80u:b9usbwz) (no related file):*
@yogesh-chauhan same scenario is also present for artifact connector.
We should handle that too.

___

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40176)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40176#-NGzBukBEgn7W3XHwbPL:-NH494yK4TBjUVC8nPBf:b-896fix) (no related file):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

@yogesh-chauhan same scenario is also present for artifact connector.
We should handle that too.
</blockquote></details>

Done.

___

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40176)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40176)* status: :shipit: complete! ✓

**Pull request merged**
