### PR TITLE
fix: [DEL-3461]: delete failed ng delegate token audit events

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)

### CODE REVIEW

**Comment by arpit3107** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
___
*[390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java, line 46 at r1](https://reviewable.io/reviews/harness/harness-core/31688#-MyqV_Ih4JpYJY5-ryoW:-MyqV_Ih4JpYJY5-ryoX:bkxufuc) ([raw file](https://github.com/harness/harness-core/blob/9fee212220a01e3b971d8f46c7b85447fa910abc/390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java#L46)):*
> ```Java
>       deleted = deleteResult.getDeletedCount();
>     } catch (Exception e) {
>       log.error("Error occurred during migration for deleting all failed ng delegate token audit events.", e);
> ```

what is the total record count in qa and prod?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java, line 46 at r1](https://reviewable.io/reviews/harness/harness-core/31688#-MyqV_Ih4JpYJY5-ryoW:-Myqb1pbD8lxmZ6aCQ9S:bxipf9s) ([raw file](https://github.com/harness/harness-core/blob/9fee212220a01e3b971d8f46c7b85447fa910abc/390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java#L46)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

what is the total record count in qa and prod?
</blockquote></details>

860 prod 2
337 prod 1
0 prod 3
9752 QA

**Comment by abhinav-harness** [comment]
___
*[390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java, line 46 at r1](https://reviewable.io/reviews/harness/harness-core/31688#-MyqV_Ih4JpYJY5-ryoW:-Myqd23o2Wit0aUWZgJF:b3g5g1v) ([raw file](https://github.com/harness/harness-core/blob/9fee212220a01e3b971d8f46c7b85447fa910abc/390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java#L46)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

860 prod 2
337 prod 1
0 prod 3
9752 QA
</blockquote></details>

ok approving.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)* status: :shipit: complete! ✓

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)* status: :shipit: complete! ✓

___
*[390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/31688#-MyprIWiLYyNxhuzCFT6-r1-61:-MyqmdGgCmS5vrlxEmSk:b3kqx) ([raw file](https://github.com/harness/harness-core/blob/9fee212220a01e3b971d8f46c7b85447fa910abc/390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java#L61)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Why are we setting batch size when we want to remove it in one go?
</blockquote></details>

.

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)* status: :shipit: complete! ✓

___
*[390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/31688#-MyprIWiLYyNxhuzCFT6-r1-61:-MyrPFWR4lh5RTcXo9YO:b-on5y5m) ([raw file](https://github.com/harness/harness-core/blob/9fee212220a01e3b971d8f46c7b85447fa910abc/390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java#L61)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

No, we want to delete 500 records one at a time, to reduce the db load. There are approx 10k records in qa.  Isn't this the right way to delete?
</blockquote></details>

Cursor batch size of used to query in batches (eg. NGSecretMigrationFromManager), not sure how it will be used with remove method. Check once by reducing the batch size and let me know if it is working as expected.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)* status: 1 change requests. 1. unresolved discussions. 

___
*[390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/31688#-MyprIWiLYyNxhuzCFT6-r1-61:-MytzUS7CDYrGvWw0iY5:b-tejrdt) ([raw file](https://github.com/harness/harness-core/blob/9fee212220a01e3b971d8f46c7b85447fa910abc/390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenAuditsMigration.java#L61)):*
<details><summary><i>Previously, karansiwach360 (Karan Siwach) wrote…</i></summary><blockquote>

Cursor batch size of used to query in batches (eg. NGSecretMigrationFromManager), not sure how it will be used with remove method. Check once by reducing the batch size and let me know if it is working as expected.
</blockquote></details>

Tested in local. batchSize was 2 and #records were 10, and the migration was able to delete all the records.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31688)* status: :shipit: complete! ✓

**Pull request merged**
