### PR TITLE
fix: [PL-28582]: replaced mindrot:jbcrypt with springframework.security:jbcrypt

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42060)

### CODE REVIEW

**Review by shashank-harness — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42060)* status: Some of the checks are too old. 16 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/BUILD.bazel` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/42060#-NKv9c1BAqhUkRDSicIx:-NKv9c1BAqhUkRDSicIy:bf8w6e2) ([raw file](https://github.com/harness/harness-core/blob/c8f7bfd811704c3037f9c3ad0cf7e09e1ddd7498/120-ng-manager/BUILD.bazel#L563)):*
> ```Starlark
>     "@maven//:org_jvnet_staxex_stax_ex",
>     "@maven//:org_ldaptive_ldaptive",
>     "@maven//:org_mindrot_jbcrypt",
> ```

@tiwaritejas I see that we have deleted this dependency but we haven't added the spring lib dependency here so is ng-manager getting it transitively from another build file?
cc: @pbarapatre10

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42060)* status: Some of the checks are too old. 16 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/BUILD.bazel` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/42060#-NKv9c1BAqhUkRDSicIx:-NKvAfof4QCiM2o28QwZ:b-ckwgzg) ([raw file](https://github.com/harness/harness-core/blob/c8f7bfd811704c3037f9c3ad0cf7e09e1ddd7498/120-ng-manager/BUILD.bazel#L563)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

@tiwaritejas I see that we have deleted this dependency but we haven't added the spring lib dependency here so is ng-manager getting it transitively from another build file?
cc: @pbarapatre10 
</blockquote></details>

@shashank-harness That is because "@maven//:org_springframework_security_spring_security_crypto" is already present in ng-manager.

**Review by devinder-harness — APPROVED** [review]

**Comment by tiwaritejas** [comment]
retrigger ti0,ti1,ti2,ti3,ti4,ft1,ft2

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42060#-:-NL0J9gt-pQkEJiTVbDG:bnfp4nl)* status: 16 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by devinder-harness — APPROVED** [review]

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42060)* status: 16 file(s) to review. 2. unresolved discussions.

**Pull request merged**
