### PR TITLE
fix: [CDS-68917]: refactor SSH session manager to become less blocking

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes

Currently, SSH session manager is blocking all threads coming to this method `getCachedSession`.

This change refactors this blocking method. Due to usage of ConcurrentHashmap's `computeIfAbsent` method, we do not need this explicit locking. The creation and test of the created session is now inside the mapping function, which will be atomic.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47660)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by ivan-83 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47660)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/SshSessionManager.java` line 67 at r3](https://reviewable.io/reviews/harness/harness-core/47660#-NVVFqAVEtC0E9xEmdud:-NVVFqAW5C_I0FH8-S8I:b56vci8) ([raw file](https://github.com/harness/harness-core/blob/8444cd0a35c9f4f8ea37fed625c112db6fee81dc/960-api-services/src/main/java/io/harness/shell/SshSessionManager.java#L67)):*
> ```Java
>     String key = getKey(config.getExecutionId(), config.getHost());
>     try {
>       synchronized (hostSessionLocks.get(key)) {
> ```

All looks good to me, just a quick question, do we need 'synchronizedon' for getting keys?

**Review by abhinavsingh1196 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47660)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/SshSessionManager.java` line 67 at r3](https://reviewable.io/reviews/harness/harness-core/47660#-NVVFqAVEtC0E9xEmdud:-NVVHACiAbH-Hv0WkueW:b-qnsy9p) ([raw file](https://github.com/harness/harness-core/blob/8444cd0a35c9f4f8ea37fed625c112db6fee81dc/960-api-services/src/main/java/io/harness/shell/SshSessionManager.java#L67)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

All looks good to me, just a quick question, do we need 'synchronizedon' for getting keys?
</blockquote></details>

For SSH deployments' script executions, I see we are making connections sequentially for the command units, so I don't think we need synchronization there. We probably need this for SSH copy command?

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47660)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinavsingh1196** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger review

**Comment by abhinavsingh1196** [comment]
trigger publish-delegate

**Pull request merged**
