### PR TITLE
fix: [DEL-4167]: Add warning for heartbeat more than 3 mins

### PR DESCRIPTION
**Pull request by jennyjames21**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34022)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1664 at r1](https://reviewable.io/reviews/harness/harness-core/34022#-N3ws-aqCgAQJKutv2F-:-N3ws-aqCgAQJKutv2F0:byfnmut) ([raw file](https://github.com/harness/harness-core/blob/35a91d1de9e77d90b13e50af313eb1fb3c233671/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1664)):*
> ```Java
>             getDurationString(lastHeartbeatSentAt.get(), now), getDurationString(lastHeartbeatReceivedAt.get(), now));
>       } else {
>         log.info("Delegate {} received heartbeat response {} after sending. {} since last response.", receivedId,
> ```

do we need this log?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1664 at r1](https://reviewable.io/reviews/harness/harness-core/34022#-N3ws-aqCgAQJKutv2F-:-N3yxizQDf5ZxPqt9Wfv:b-kvztri) ([raw file](https://github.com/harness/harness-core/blob/35a91d1de9e77d90b13e50af313eb1fb3c233671/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1664)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

+1,
On other note, @anupamio is working on removing heartbeat broadcast from manager, so all this will be deprecate soon.
</blockquote></details>

but we still need warning part if it takes more 3 mins ????

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 893 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1BI4DBQ6feFiCiCB:-N4d1BI5-BpJcsgkQFZE:brusnis) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L893)):*
> ```Java
>       healthMonitorExecutor.submit(() -> processHeartbeat(delegateHeartbeatResponse));
>     } else if (StringUtils.startsWith(message, "[X]")) {
>       healthMonitorExecutor.submit(() -> processHeartbeat(message));
> ```

we should get rid of the else



_Code quote:_
```Java
ocessHeartbeat
```

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2500 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1NUt0IudbyLnhz5l:-N4d1NUt0IudbyLnhz5m:bfizgzs) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2500)):*
> ```Java
>   }
> 
>   private void handleEcsDelegateSpecificMessage(DelegateHeartbeatResponse delegateHeartbeatResponse) {
> ```

remove the other piece

**Comment by raghuAtWings** [comment]
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1gAqBIh3YPWxYyCD:-N4d1gAqBIh3YPWxYyCE:b-5hnykb) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java#L52)):*
> ```Java
>   boolean proxy;
>   boolean ceEnabled;
>   boolean sendAsDelegateHeartBeat;
> ```

rename to heartbeatAsObject

**Comment by raghuAtWings** [comment]
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponse.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1mSqCivMYokg3T9n:-N4d1mSqCivMYokg3T9o:b-g3v12n) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponse.java#L26)):*
> ```Java
>   String delegateRandomToken;
>   String sequenceNumber;
>   long requestStartedAt;
> ```

responseSentAt

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34022)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
Heartbeat thru heartbeat object
image

**Comment by jennyjames21** [comment]
polling enabled 
image

**Comment by jennyjames21** [comment]
image

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 893 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1BI4DBQ6feFiCiCB:-N50od0cDc8MwOQhloE4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L893)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should get rid of the else
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1650 at r1](https://reviewable.io/reviews/harness/harness-core/34022#-N497h8t921rTI81Pd6x:-N50of3D9sbgWwgEjrST:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/35a91d1de9e77d90b13e50af313eb1fb3c233671/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1650)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

add information in the manager about when the heartbeat was sent so we know the difference. Also test it with new and old delegate. 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2500 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1NUt0IudbyLnhz5l:-N50ogvW6VYaOeTHyAb8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2500)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

remove the other piece 
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponse.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1mSqCivMYokg3T9n:-N50oiHe86aCuGobhgnd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/920-delegate-agent-beans/src/main/java/io/harness/beans/DelegateHeartbeatResponse.java#L26)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

responseSentAt
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[`920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/34022#-N4d1gAqBIh3YPWxYyCD:-N50ojZbADOIZCTuBQrU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad9b32ab895f025ee130abac3d47166d83748b7e/920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateParams.java#L52)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

rename to heartbeatAsObject
</blockquote></details>

Done.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 6 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34022)* status: 7 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
trigger codebasehash

**Comment by jennyjames21** [comment]
with different version, non polling 
image
Polling

**Pull request closed without merging**
