### PR TITLE
[fix]: [CDS-46791]: pre qa hotfix

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
[fix]: [CDS_46791]: pre qa hotfix
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40338)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`build.properties` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/40338#-NH8_J2ADgqDvl69EXXN:-NH8_J2B0tcicqsDyRAL:bpwfnht) ([raw file](https://github.com/harness/harness-core/blob/778bc24f0e4f176e95fe1300abbcf4eecb2305c6/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=0
> build.number=776001
> ```

it seems strange with suffix 1. Also, do we need to increment this number for preqa hf?

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40338)* status: 6 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40338)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

___
*[`build.properties` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/40338#-NH8_J2ADgqDvl69EXXN:-NH8a_na0LHWuYkq_cHJ:bvth56w) ([raw file](https://github.com/harness/harness-core/blob/778bc24f0e4f176e95fe1300abbcf4eecb2305c6/build.properties#L3)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

it seems strange with suffix 1. Also, do we need to increment this number for preqa hf?
</blockquote></details>

reverted

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40338)* status: 6 file(s) to review. 0 of 1 approvals obtained.  (waiting on @vlica-harness)

**Comment by tmacari-harness** [comment]
trigger messagecheck

**Comment by tmacari-harness** [comment]
trigger messagecheck

**Review by vlica-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40338)* status: :shipit: complete! ✓

**Pull request merged**
