### PR TITLE
feat: [PL-31104]: deletion of externally managed user from org and project

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMjWr1v4_O_-VVFvUnv:bdtdokf) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier) {
>     if (isUserExternallyManaged(userId)
>         && ScopeLevel.ACCOUNT.equals(ScopeLevel.of(accountIdentifier, orgIdentifier, projectIdentifier))) {
> ```

Put this change behind a FF and enable it only for the customer who is asking for it. We will need to analyse more use cases before we can GA.

For example, what will happen if customer delete a genuine user. 
Next time their SCIM provider tries to update this user, they will receive an error.
cc: @pbarapatre10 @manish-manchanda

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091#-:-NMm-OUYAigMLmRQhC1G:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMm1kI6B1d94qyhFBa4:bdah1ua) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Put this change behind a FF and enable it only for the customer who is asking for it. We will need to analyse more use cases before we can GA.

For example, what will happen if customer delete a genuine user. 
Next time their SCIM provider tries to update this user, they will receive an error.
cc: @pbarapatre10 @manish-manchanda 
</blockquote></details>

Added behind FF- PL_REMOVE_EXTERNAL_USER_ORG_PROJECT

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMnBIpa6zFLRaSDTO3q:b-20ci09) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Added behind FF- PL_REMOVE_EXTERNAL_USER_ORG_PROJECT
</blockquote></details>

According to your changes, even if FF is not ON, we are deleting just by checking scope.
FF is supposed to do following:

- If FF ON, then execute new logic
- Else, continue with existing logic.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMnDzXs9UiqZAoCKytz:b-2az0wu) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

According to your changes, even if FF is not ON, we are deleting just by checking scope.
FF is supposed to do following:

- If FF ON, then execute new logic
- Else, continue with existing logic.

</blockquote></details>

Sorry, I do not follow this. Can you help with a specific case of (Scope, FF) where this will not perform as expected.
The following is how this should work as of now-
SCOPE            FF               ACTION
Account        On              Throw exception
                      Off              Throw exception
Org                On              Delete user 
                      Off              Throw exception
Project          On              Delete user 
                      Off              Throw exception

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMnGTVqDLJCbjX53MNr:b1yizc8) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Sorry, I do not follow this. Can you help with a specific case of (Scope, FF) where this will not perform as expected.
The following is how this should work as of now-
SCOPE            FF               ACTION
Account        On              Throw exception
                      Off              Throw exception
Org                On              Delete user 
                      Off              Throw exception
Project          On              Delete user 
                      Off              Throw exception



</blockquote></details>

The idea here is that FF call should not even be made if scope is account, as user deletion is not allowed from account. For org and project scopes, it will check for FF whether is true or not.

**Comment by piyush-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMnHNk-A8Jl_SpkvrDy:bio8gjw) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

The idea here is that FF call should not even be made if scope is account, as user deletion is not allowed from account. For org and project scopes, it will check for FF whether is true or not.
</blockquote></details>

@shashank-harness Why are we complicating this by putting behind FF, It's functionality gap. User can be removed from org or project scopes in all conditions , Only externally managed users cannot be removed from Account.

**Comment by shashank-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMnMZ7o6zZXcCKYYfi7:b-4mj2xs) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

@shashank-harness Why are we complicating this by putting behind FF, It's functionality gap. User can be removed from org or project scopes in all conditions , Only externally managed users cannot be removed from Account.
</blockquote></details>

As discussed, approving

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMnMzWqAX2ZUUGX9q6R:b6l3pga) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

As discussed, approving
</blockquote></details>

@piyush-harness We are keeping it behind FF because we haven't done extensive testing yet. We have tested the functionality properly, but since this comes as an urgent requirement, we couldn't test its impact thoroughly, although, we should be mostly good. We will remove this FF soon.

**Comment by piyush-harness** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 568 at r1](https://reviewable.io/reviews/harness/harness-core/43091#-NMjWr1v4_O_-VVFvUnu:-NMrBWFB0ohs-mt9SwKD:b-1x4zna) ([raw file](https://github.com/harness/harness-core/blob/d5bc3579c1752c7e2a9ac45525fce3be304a83e4/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L568)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

@piyush-harness We are keeping it behind FF because we haven't done extensive testing yet. We have tested the functionality properly, but since this comes as an urgent requirement, we couldn't test its impact thoroughly, although, we should be mostly good. We will remove this FF soon.
</blockquote></details>

Approving Please log a ticket to remove the FF in the subsequent release

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43091)* status: :shipit: complete! ✓

**Pull request merged**
