### PR TITLE
[feat]: [CDS-34698]: Made setup usage framework changes for workflow

### PR DESCRIPTION
**Pull request by prabu-kr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)

### CODE REVIEW

**Review by srinivaswings — APPROVED** [review]

**Review by srinivaswings — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)* status: :shipit: complete! ✓

**Review by srinivaswings — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)* status: :shipit: complete! ✓

**Review by srinivaswings — DISMISSED** [review]
> Reviewed 3 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java, line 972 at r4](https://reviewable.io/reviews/harness/harness-core/31437#-MyIQ9lA9ZvZnwwu26dd:-MyIQ9lA9ZvZnwwu26de:bbp4so1) ([raw file](https://github.com/harness/harness-core/blob/19dbdf0c58d8b1f032d3bd87b56f8a2850033722/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java#L972)):*
> ```Java
>       Set<String> currentUserGroups = getUserGroups(workflow);
>       try {
>         updateWorkflowReferenceInUserGroup(new HashSet<>(), currentUserGroups, workflow.getAccountId(),
> ```

Just a thought that can we move populating user group references after we have saved workflow and that too maybe on a separate thread so that it doesn't slow down workflow save/update?

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 3 of 5 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31437)* status: :shipit: complete! ✓

**Pull request merged**
