### PR TITLE
fix: [PL-18485]: Raise alert when a more general issue happens during git integration

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32342)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by srinivaswings — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32342)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32342)* status: :shipit: complete! ✓

**Review by shivagowda — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32342)* status: :shipit: complete! ✓

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32342)* status: :shipit: complete! ✓

**Comment by DeepakPatankar** [comment]
@Fernando-Dourado  The general error won't include the internal harness errors like NPEs, right ?

**Comment by Fernando-Dourado** [comment]
@DeepakPatankar Yes, you are right. These error code happens only when WingsException are raised and handled inside a git operation in GitCommandTask class and already arrive at this point with already set general error.

**Pull request merged**
