### PR TITLE
fix: [CDS-46036]: delete perpetual tasks in case service/env doesn't …

### PR DESCRIPTION
**Pull request by achyuth-harness**
…exist

## Describe your changes
We will delete the perpetual tasks for which we are not able to find the service id (or env id). 

UT added: ensure we call the method to delete the perpetual task if service with given id is not found

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 204 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYFId4yXrUGjubTP6:-NHyYFId4yXrUGjubTP7:b3hgqoh) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L204)):*
> ```Java
>         } catch (InvalidRequestException e) {
>           if (e.getMessage().contains("Service not found for serviceId :")) {
>             log.info("Deleting perpetual task as " + e.getMessage());
> ```

log.error
And we should simply log complete exception, not only message.

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 203 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYMpV-HcH-Pvheh0B:-NHyYMpV-HcH-Pvheh0C:b1l27dn) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L203)):*
> ```Java
>           ServiceEntity serviceEntity = instanceSyncHelper.fetchService(infrastructureMappingDTO.get());
>         } catch (InvalidRequestException e) {
>           if (e.getMessage().contains("Service not found for serviceId :")) {
> ```

Why do you need such a hard coded if? We should do better here. I would suggest to throw very pointed exception from the method and then catch it here and do the required handling.

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYWh084J97cmaj2hF:-NHyYWh084J97cmaj2hG:b-yl1v8q) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L205)):*
> ```Java
>           if (e.getMessage().contains("Service not found for serviceId :")) {
>             log.info("Deleting perpetual task as " + e.getMessage());
>             instanceSyncPerpetualTaskService.deletePerpetualTask(accountIdentifier, perpetualTaskId);
> ```

what if this call fails?

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYZJTAG94EMIoLEr7:-NHyYZJTAG94EMIoLEr8:bi0arhd) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L216)):*
> ```Java
>             log.info("Deleting perpetual task as " + e.getMessage());
>             instanceSyncPerpetualTaskService.deletePerpetualTask(accountIdentifier, perpetualTaskId);
>             return;
> ```

all comments same as above

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYYryEPrClWUoFJHf:-NHyYYryEPrClWUoFJHg:bedpe5m) (no related file):*
Please describe the changes in the pr details and also provide the test cases that have been used to validate the fix.

___
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYnX23uJ5eIRiQ9kq:-NHyYnX23uJ5eIRiQ9kr:b878uv1) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L215)):*
> ```Java
>           if (e.getMessage().contains("Environment not found for envId :")) {
>             log.info("Deleting perpetual task as " + e.getMessage());
>             instanceSyncPerpetualTaskService.deletePerpetualTask(accountIdentifier, perpetualTaskId);
> ```

i can see in case if infra mapping is missing, we are invoking `instanceSyncHelper.cleanUpInstanceSyncPerpetualTaskInfo(instanceSyncPerpetualTaskInfoDTO);`
can we check if we are not missing anything.

**Review by vikyathharekal — COMMENTED** [review]
If you see the stack trace in the Jira ticket,  we call these 2 methods anyway in the `buildInstances()` method. 
Can we handle it there instead of making these additional calls?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745#-:-NHyZhHy-Ksoms5KZRhq:b-h65qc9)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: 2 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYYryEPrClWUoFJHf:-NI17jkuETt0dlCISgbk:b-896fix) (no related file):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

Please describe the changes in the pr details and also provide the test cases that have been used to validate the fix.
</blockquote></details>

Done.

___
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 203 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYMpV-HcH-Pvheh0B:-NI17mcCAEtMt_CrEFjw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L203)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why do you need such a hard coded if? We should do better here. I would suggest to throw very pointed exception from the method and then catch it here and do the required handling.
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 204 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYFId4yXrUGjubTP6:-NI17n2B8dPnCMyQiNdi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L204)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log.error
And we should simply log complete exception, not only message.
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYWh084J97cmaj2hF:-NI17nOb9MvTB8MF3hqJ:b5pefrs) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L205)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this call fails?
</blockquote></details>

This is already being handled. 
We have this:



_Code snippet:_
```Java
public void deletePerpetualTask(AccountId accountId, PerpetualTaskId perpetualTaskId) {
    try {
      delegateServiceBlockingStub.withDeadlineAfter(30, TimeUnit.SECONDS)
          .deletePerpetualTask(DeletePerpetualTaskRequest.newBuilder()
                                   .setAccountId(accountId)
                                   .setPerpetualTaskId(perpetualTaskId)
                                   .build());
    } catch (StatusRuntimeException ex) {
      throw new DelegateServiceDriverException("Unexpected error occurred while deleting perpetual task.", ex);
    }
  }
```
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYnX23uJ5eIRiQ9kq:-NI18Dov-O314OTwu9Xq:b-jc7435) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L215)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i can see in case if infra mapping is missing, we are invoking `instanceSyncHelper.cleanUpInstanceSyncPerpetualTaskInfo(instanceSyncPerpetualTaskInfoDTO);`
can we check if we are not missing anything.
</blockquote></details>

Infra mapping will be missing if both env + service don't exist. Here looking at the stack-trace the svc doesn't exist (perhaps its been deleted) but env does
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYZJTAG94EMIoLEr7:-NI18Y7u9sd2EbRMIu76:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L216)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

all comments same as above
</blockquote></details>

Done.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: 2 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYnX23uJ5eIRiQ9kq:-NI2srzV4KuEv2VqyXrt:b-tne3mu) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L215)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Infra mapping will be missing if both env + service don't exist. Here looking at the stack-trace the svc doesn't exist (perhaps its been deleted) but env does
</blockquote></details>

i was referring to the method itself, `cleanupInstanceSyncPerpetualTaskInfo()`, shall we use it instead of hard delete perpetual task?

**Review by achyuth-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: 2 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/40745#-NHyYnX23uJ5eIRiQ9kq:-NI6Cgvs2Gvk42xFNWMn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6daad8a812bd96d4e0ed00d2aa8273f860e3a03c/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L215)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i was referring to the method itself, `cleanupInstanceSyncPerpetualTaskInfo()`, shall we use it instead of hard delete perpetual task?
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 617 at r3](https://reviewable.io/reviews/harness/harness-core/40745#-NI6LoML3o7pDSwngDIl:-NI6LoML3o7pDSwngDIm:b9uujm9) ([raw file](https://github.com/harness/harness-core/blob/246946667507181070c1d29d36ee0d45c0367e3b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L617)):*
> ```Java
>     try {
>       ServiceEntity serviceEntity = instanceSyncHelper.fetchService(infrastructureMappingDTO);
>     } catch (InvalidRequestException e) {
> ```

I checked we are sending InvalidRequestException in case service isn't found. That should be changed to EntityNotFound exception for better clarity.

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 618 at r3](https://reviewable.io/reviews/harness/harness-core/40745#-NI6Lv1q6Y_6wbcZ6QK3:-NI6Lv1q6Y_6wbcZ6QK4:b-9nfsz9) ([raw file](https://github.com/harness/harness-core/blob/246946667507181070c1d29d36ee0d45c0367e3b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L618)):*
> ```Java
>       ServiceEntity serviceEntity = instanceSyncHelper.fetchService(infrastructureMappingDTO);
>     } catch (InvalidRequestException e) {
>       log.error("Failed to get service", e);
> ```

Considering the current implementation, if its invalidRequestException then its a genuine exception which means service isn't found in DB, so we shouldn't log error saying "failed to get service", its misleading.

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 624 at r3](https://reviewable.io/reviews/harness/harness-core/40745#-NI6M3nZBphgPrMf6j1L:-NI6M3nZBphgPrMf6j1M:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/246946667507181070c1d29d36ee0d45c0367e3b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L624)):*
> ```Java
>       Environment environment = instanceSyncHelper.fetchEnvironment(infrastructureMappingDTO);
>     } catch (InvalidRequestException e) {
>       log.error("Failed to get env", e);
> ```

same as above

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: 3 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 617 at r3](https://reviewable.io/reviews/harness/harness-core/40745#-NI6LoML3o7pDSwngDIl:-NI6Z1Zz42UcCxsGX6-K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/246946667507181070c1d29d36ee0d45c0367e3b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L617)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I checked we are sending InvalidRequestException in case service isn't found. That should be changed to EntityNotFound exception for better clarity.
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 618 at r3](https://reviewable.io/reviews/harness/harness-core/40745#-NI6Lv1q6Y_6wbcZ6QK3:-NI6Z1nTAYPpJReTqln3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/246946667507181070c1d29d36ee0d45c0367e3b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L618)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Considering the current implementation, if its invalidRequestException then its a genuine exception which means service isn't found in DB, so we shouldn't log error saying "failed to get service", its misleading.
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java` line 624 at r3](https://reviewable.io/reviews/harness/harness-core/40745#-NI6M3nZBphgPrMf6j1L:-NI6Z2Dc4hAzmrFPC9wW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/246946667507181070c1d29d36ee0d45c0367e3b/126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java#L624)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40745)* status: :shipit: complete! ✓

**Pull request merged**
