### PR TITLE
feat: [CDS-54352]: Dynamic provisioning for SSH/WinRm

### PR DESCRIPTION
**Pull request by ivan-83**
Added support for dynamic provisioning for all infras,

Steps execute in the following order: service step >> provisioner steps >> infra steps >> execution steps ...
When the provisioner finishes provisioning resources we save outputs into sweeping output collection. After that consume saved outputs in infra steps and create provisioner functor. 

When we have a provisioner functor set with outputs, we resolve <provader.some property from output> expressions in the infrastructure mapping class. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger ut3

**Comment by ivan-83** [comment]
trigger ut0

**Comment by ivan-83** [comment]
trigger ut2

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/provision/ProvisionerOutputHelper.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/45071#-NRda5ba861RmghclLDX:-NRda5ba861RmghclLDY:b-89dzjl) ([raw file](https://github.com/harness/harness-core/blob/3bcf62008945e9a18c1ae2ccf4b4c7f73584f0c2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/provision/ProvisionerOutputHelper.java#L47)):*
> ```Java
>     }
> 
>     String provisionerIdentifier = currentLevel.getIdentifier();
> ```

is this the step identifier or the provisioner identifier ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 51 of 65 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)* status: 65 file(s) to review. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/45071#-NRkodYx-PHRJmbgdZps:-NRkodYx-PHRJmbgdZpt:b12txlc) ([raw file](https://github.com/harness/harness-core/blob/3bcf62008945e9a18c1ae2ccf4b4c7f73584f0c2/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L104)):*
> ```Java
>                 .connectorRef(k8SDirectInfrastructure.getConnectorRef().getValue())
>                 .namespace(getParameterFieldValueOrResolveExpression(expressionEvaluator, isDynamicallyProvisioned,
>                     k8SDirectInfrastructure.getNamespace(), ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED))
> ```

does this throw an exception today also if the namespace is not resolved?

Also why do we have different behaviours for namespace and release name field ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 14 of 65 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)* status: 65 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)* status: 65 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/45071#-NRkodYx-PHRJmbgdZps:-NRmdGfn4LJoXyQLYVzO:b-c935mg) ([raw file](https://github.com/harness/harness-core/blob/3bcf62008945e9a18c1ae2ccf4b4c7f73584f0c2/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L104)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this throw an exception today also if the namespace is not resolved?

Also why do we have different behaviours for namespace and release name field ?
</blockquote></details>

We are throwing exceptions where we expect the value for infra property and can't resolve provisioner expression.
We return the original expression where we expect value or expression for infra property but can't resolve provisioner expression.

I also added support for K8s release name fields. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 590 at r1](https://reviewable.io/reviews/harness/harness-core/45071#-NRm1OL70dNryHGE39eG:-NRmeudG0GgGkfUf4DPq:b-80tlqk) ([raw file](https://github.com/harness/harness-core/blob/3bcf62008945e9a18c1ae2ccf4b4c7f73584f0c2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L590)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets validate for deploy templates as well 
</blockquote></details>

Sure.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/provision/ProvisionerOutputHelper.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/45071#-NRda5ba861RmghclLDX:-NRmSNND8ebOO-WWHaQc:b-lpquj0) ([raw file](https://github.com/harness/harness-core/blob/3bcf62008945e9a18c1ae2ccf4b4c7f73584f0c2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/provision/ProvisionerOutputHelper.java#L47)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this the step identifier or the provisioner identifier ?
</blockquote></details>

Yes, it is a step identifier. Updated.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 19 of 20 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)* status: 65 file(s) to review. 1 of 2 approvals obtained.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 45 of 65 files at r1, 19 of 20 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45071)* status: :shipit: complete! ✓

**Pull request merged**
