### PR TITLE
[feat]: [CDS-36354] Increase code coverage in cloudformation NG logic

### PR DESCRIPTION
**Pull request by vlica-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)

### CODE REVIEW

**Review by nassergonzalez — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperUtilityClassTest.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06Y1UP9TXWgV3S6w3_:-N06Y1UP9TXWgV3S6w3a:b-nj1a01) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperUtilityClassTest.java#L34)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testValidateGitStoreConfig() {
>     io.harness.cdng.CDStepHelper cDStepHelper = new CDStepHelper();
> ```

I think that we would normally import the static library so it's just CDStepHelper
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java, line 78 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06YhoX-FJRBFD28RC5:-N06YhoY0gZ1f1hqKpLR:bt49j0s) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java#L78)):*
> ```Java
>                                   .build();
> 
>     origin.getKind();
> ```

If you are going to call origin.getKind in the assertThat, you can delete this call probably
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java, line 93 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06Yp7M34k9Z8iLuRz0:-N06Yp7M34k9Z8iLuRz1:brvqckk) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java#L93)):*
> ```Java
>                                   .build();
> 
>     origin.getKind();
> ```

I think that you can remove this call
___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java, line 136 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06eySX-CuIEcMY8h3a:-N06eySX-CuIEcMY8h3b:b7c41nq) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java#L136)):*
> ```Java
>     verify(cloudformationBaseHelper, times(1)).getCapabilities(any(), anyString(), anyString(), any(), any());
>     verify(awsCloudformationClient, times(1)).createStack(anyString(), any(), any());
>     verify(awsCloudformationClient, times(2)).getAllStacks(anyString(), any(), any());
> ```

Should getAllStacks only be called once?



_Code quote:_
```Java
getAllStacks
```

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperUtilityClassTest.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06Y1UP9TXWgV3S6w3_:-N06oAEV8VWhorMxE9-Z:bqkt24u) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperUtilityClassTest.java#L34)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I think that we would normally import the static library so it's just CDStepHelper
</blockquote></details>

yep, you are right, strange that checkstyle pr check didn't catch this. Thanks,
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java, line 78 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06YhoX-FJRBFD28RC5:-N06oQHF2tD_Y623R7Y6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java#L78)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

If you are going to call origin.getKind in the assertThat, you can delete this call probably
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java, line 93 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06Yp7M34k9Z8iLuRz0:-N06oSsLDZ4DObxuI5M_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java#L93)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I think that you can remove this call
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java, line 136 at r2](https://reviewable.io/reviews/harness/harness-core/32279#-N06eySX-CuIEcMY8h3a:-N06npI1En_U1hOjiYBV:b-3f70xk) ([raw file](https://github.com/harness/harness-core/blob/6b683470554c6bce4be6d08beee4d284deb416e1/930-delegate-tasks/src/test/java/io/harness/delegate/task/cloudformation/handlers/CloudformationCreateStackTaskHandlerTest.java#L136)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

Should getAllStacks only be called once?
</blockquote></details>

hey @nassergonzalez , no, it should be 2,
we call getAllStacks() in the beginning of creation to check if such stack exists. And then the second call happens after we create it, to verify that it was created and it's status.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: 1 change requests. 4. unresolved discussions.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java, line 36 at r3](https://reviewable.io/reviews/harness/harness-core/32279#-N0A88vpBgdcjPCWhfck:-N0A88vpBgdcjPCWhfcl:bz14tvg) ([raw file](https://github.com/harness/harness-core/blob/6d570dba9b899fc794e767b3bf623971ab146931/125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java#L36)):*
> ```Java
>     S3UrlStoreConfig result = (S3UrlStoreConfig) s3UrlStoreConfig.applyOverrides(override);
> 
>     assertThat(result.getConnectorRef().getValue()).isEqualTo("connector-Ref");
> ```

I observed that "applyOverrides" method doesn't override all fields. Can we fix it within the same PR ?

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: :shipit: complete! ✓

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: 1 file(s) to review. 1 change requests. 

___
*[bazelrc.common, line 41 at r4](https://reviewable.io/reviews/harness/harness-core/32279#-N0AGzhV9fBX2AAjL6xG:-N0AGzhV9fBX2AAjL6xH:b-97fcm3) ([raw file](https://github.com/harness/harness-core/blob/28216d791bb29de45d0125e8effef6ae07c209c2/bazelrc.common#L41)):*
> ```
> build --define=HARNESS_ARGS=
> 
> # Bazel SonarQube Integration
> ```

let's undo that

**Comment by vlica-harness** [comment]
*[125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java, line 36 at r3](https://reviewable.io/reviews/harness/harness-core/32279#-N0A88vpBgdcjPCWhfck:-N0AHW0C0_Byw19XQ3CX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6d570dba9b899fc794e767b3bf623971ab146931/125-cd-nextgen/src/test/java/io/harness/cdng/manifest/yaml/S3UrlStoreConfigTest.java#L36)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I observed that "applyOverrides" method doesn't override all fields. Can we fix it within the same PR ?
</blockquote></details>

done

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
*[bazelrc.common, line 41 at r4](https://reviewable.io/reviews/harness/harness-core/32279#-N0AGzhV9fBX2AAjL6xG:-N0AHQRR2Ea6SQziUnDQ:b7wsok5) ([raw file](https://github.com/harness/harness-core/blob/28216d791bb29de45d0125e8effef6ae07c209c2/bazelrc.common#L41)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's undo that
</blockquote></details>

done, my mistake checking coverage locally ))

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32279)* status: :shipit: complete! ✓

**Pull request merged**
