### PR TITLE
fix: [CDS-70832]: retry failed pipeline is not copying the correct no…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…des after retrying failed stages in matrix

## Describe your changes

Problem: Retry failed pipeline not working when steps used retried failure strategy.

Solution: We are fetching last retried node instead of next node id. If next node id is last retried node, it will copy all previous node execution (Code was added before. IdentityNodeExecutionStrategy::handleLeafNodes::copyNodeExecutionsForRetriedNodes) 

Testing:
Manual Testing on local. Did testing on stategy use case as well.
We need to add automation as well for this - https://harness.atlassian.net/browse/CDS-71268

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 972 at r5](https://reviewable.io/reviews/harness/harness-core/48851#-NXFG-ujEeQWgpqBCFAX:-NXFG-ukCykkssn027uJ:b37l07y) ([raw file](https://github.com/harness/harness-core/blob/dbe7ca898225f76a0921fb9f1bfc5b7ff08847a3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L972)):*
> ```Java
>     Query query = query(criteria);
>     query.fields().include(NodeExecutionKeys.id);
>     return mongoTemplate.findOne(query, NodeExecution.class);
> ```

it can go to secondaryMongoTemplate as its retried node thus it will always be available

**Comment by prashantsharma04** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 972 at r5](https://reviewable.io/reviews/harness/harness-core/48851#-NXFG-ujEeQWgpqBCFAX:-NXFYyD2Dcq_Jbfw4UKO:b-gpc0h0) ([raw file](https://github.com/harness/harness-core/blob/dbe7ca898225f76a0921fb9f1bfc5b7ff08847a3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L972)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it can go to secondaryMongoTemplate as its retried node thus it will always be available
</blockquote></details>

it will not work

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 115 at r8](https://reviewable.io/reviews/harness/harness-core/48851#-NXFro8x2DVt6qU51Xyg:-NXFro8x2DVt6qU51Xyh:b-2u4ahz) ([raw file](https://github.com/harness/harness-core/blob/68a432df27a340e7802cfc6d7cee7f799a9fa7af/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L115)):*
> ```Java
>     query.cursorBatchSize(MAX_BATCH_SIZE);
>     validateNodeExecutionStreamQuery(query);
>     return secondaryMongoTemplate.stream(query, NodeExecution.class);
> ```

You dont need stream, you can still use - secondaryMongoTemplate.findOne to return only one and change method name accordingly findOneNodeExecutionfromSecondary

**Comment by prashantsharma04** [comment]
trigger uts

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 115 at r8](https://reviewable.io/reviews/harness/harness-core/48851#-NXFro8x2DVt6qU51Xyg:-NXJ76taBIQugWW6mhlE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68a432df27a340e7802cfc6d7cee7f799a9fa7af/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L115)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

You dont need stream, you can still use - secondaryMongoTemplate.findOne to return only one and change method name accordingly findOneNodeExecutionfromSecondary
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 972 at r5](https://reviewable.io/reviews/harness/harness-core/48851#-NXFG-ujEeQWgpqBCFAX:-NXJ77mU3dl_nAH7dPHi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbe7ca898225f76a0921fb9f1bfc5b7ff08847a3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L972)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it will not work
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 114 at r10](https://reviewable.io/reviews/harness/harness-core/48851#-NXJ8jH58VYQWiTwdgGa:-NXJ8jH58VYQWiTwdgGb:bvjw4qg) ([raw file](https://github.com/harness/harness-core/blob/49faee4d6ba6d98f128963e9e2e813a6612a6526/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L114)):*
> ```Java
>   public NodeExecution fetchNodeExecutionsFromSecondaryTemplate(Query query) {
>     query.cursorBatchSize(MAX_BATCH_SIZE);
>     validateNodeExecutionStreamQuery(query);
> ```

This is not stream so use only - validateNodeExecutionProjection and don't use max batch size as here only on record is there

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 114 at r10](https://reviewable.io/reviews/harness/harness-core/48851#-NXJ8jH58VYQWiTwdgGa:-NXJDqRO7YRh-wh4IS-U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49faee4d6ba6d98f128963e9e2e813a6612a6526/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L114)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This is not stream so use only - validateNodeExecutionProjection and don't use max batch size as here only on record is there
</blockquote></details>

Done.

**Comment by prashantsharma04** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 5 files at r7, 2 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48851)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
