### PR TITLE
fix: [DEL-3372]: Introduce Delegate Token in Watcher and Delegate agent

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30962)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, line 59 at r1](https://reviewable.io/reviews/harness/harness-core/30962#-MwgPcTj6JPO2DMLbanV:-MwgPcTj6JPO2DMLbanW:b92y5id) ([raw file](https://github.com/harness/harness-core/blob/9acf93ddd37cfcf9a5eb8f45949668ee2e6389e9/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L59)):*
> ```Java
> 
>     String accountSecret = configuration.getAccountSecret();
>     if (StringUtils.isEmpty(accountSecret)) {
> ```

We can write a getter in the configuration and hide this complexity there instead of repeating everywhere

**Comment by raghuAtWings** [comment]
___
*[960-watcher/src/main/java/io/harness/watcher/app/WatcherConfiguration.java, line 19 at r1](https://reviewable.io/reviews/harness/harness-core/30962#-MwgPyIw1Wnqao1XkBnI:-MwgPyIw1Wnqao1XkBnJ:b-psicfc) ([raw file](https://github.com/harness/harness-core/blob/9acf93ddd37cfcf9a5eb8f45949668ee2e6389e9/960-watcher/src/main/java/io/harness/watcher/app/WatcherConfiguration.java#L19)):*
> ```Java
>   private String accountId;
>   private String accountSecret;
>   private String delegateToken;
> ```

We need to make changes such that if DELEGAT_TOKEN is present as env variable then the new variable is written in the watcher config yaml

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30962)* status: 0 of 1 approvals obtained.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30962)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, line 59 at r1](https://reviewable.io/reviews/harness/harness-core/30962#-MwgPcTj6JPO2DMLbanV:-Mwj8Ong9p-2NqwNz2tY:bimea91) ([raw file](https://github.com/harness/harness-core/blob/9acf93ddd37cfcf9a5eb8f45949668ee2e6389e9/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L59)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

We can write a getter in the configuration and hide this complexity there instead of repeating everywhere 
</blockquote></details>

Yup, Done
___
*[960-watcher/src/main/java/io/harness/watcher/app/WatcherConfiguration.java, line 19 at r1](https://reviewable.io/reviews/harness/harness-core/30962#-MwgPyIw1Wnqao1XkBnI:-Mwgdv0x8eqVaV0b5Cqf:b-an0lll) ([raw file](https://github.com/harness/harness-core/blob/9acf93ddd37cfcf9a5eb8f45949668ee2e6389e9/960-watcher/src/main/java/io/harness/watcher/app/WatcherConfiguration.java#L19)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

We need to make changes such that if DELEGAT_TOKEN is present as env variable then the new variable is written in the watcher config yaml 
</blockquote></details>

They are not needed right now, can come later along with other changes.

**Comment by raghuAtWings** [comment]
___
*[960-watcher/src/main/java/io/harness/watcher/app/WatcherApplication.java, line 134 at r2](https://reviewable.io/reviews/harness/harness-core/30962#-MwjkhhM8z9NVucZdJme:-MwjkhhM8z9NVucZdJmf:b-l0xqw) ([raw file](https://github.com/harness/harness-core/blob/49077347732038f5cc03404b35a8eb06c5b8b655/960-watcher/src/main/java/io/harness/watcher/app/WatcherApplication.java#L134)):*
> ```Java
>     String delegateToken = configuration.getDelegateToken();
>     if (StringUtils.isEmpty(delegateToken)) {
>       log.error("Error while reading secret");
> ```

shouldn't we just fail to start in this case?

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30962)* status: 7 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-watcher/src/main/java/io/harness/watcher/app/WatcherApplication.java, line 134 at r2](https://reviewable.io/reviews/harness/harness-core/30962#-MwjkhhM8z9NVucZdJme:-MwkSofr1cHLotGiI45y:b-4hvemi) ([raw file](https://github.com/harness/harness-core/blob/49077347732038f5cc03404b35a8eb06c5b8b655/960-watcher/src/main/java/io/harness/watcher/app/WatcherApplication.java#L134)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

shouldn't we just fail to start in this case?
</blockquote></details>

I haven't seen use of assert or fatal in the code, hence logged an error. But yeah, we should fail in this case.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30962)* status: 7 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-watcher/src/main/java/io/harness/watcher/app/WatcherApplication.java, line 134 at r2](https://reviewable.io/reviews/harness/harness-core/30962#-MwjkhhM8z9NVucZdJme:-MwkTK4j2Fbu3iq3XWmi:b9n23yy) ([raw file](https://github.com/harness/harness-core/blob/49077347732038f5cc03404b35a8eb06c5b8b655/960-watcher/src/main/java/io/harness/watcher/app/WatcherApplication.java#L134)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I haven't seen use of assert or fatal in the code, hence logged an error. But yeah, we should fail in this case.
</blockquote></details>

throwing exception will also block the main thread.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30962)* status: :shipit: complete! ✓

**Pull request merged**
