### PR TITLE
[feat]: [CDS-39264]: rollback container azure webapps

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
Support rollback for container based azure webapps
Some of the changes may look not backward compatible - that's ok those delegate tasks are not yet used in PROD and steps are behind FF.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)

### CODE REVIEW

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)* status: 43 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/35052#-N6HCvvgWxs8yh-Zm8GF-r1-119:-N6I8qFIBbTCGti52HVT:bkpn4p2) ([raw file](https://github.com/harness/harness-core/blob/f30838f1c1ce89b5794bf463aa2a1c786705a789/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L119)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

Can we use here the swapSlotsSweepingOutput which you have in the parent method you call this method? 
</blockquote></details>

good point, DONE.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 42 of 43 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/35052#-N6IC0FeC5Ir33ywnl_3:-N6IC0FeC5Ir33ywnl_4:b3mo5ef) ([raw file](https://github.com/harness/harness-core/blob/a15832c7b24ae3325f46c17185d7efd960bd6603/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L77)):*
> ```Java
>         getDeploymentProgressMarker(ambiance, stepParameters, trafficShiftSweepingOutput, swapSlotsSweepingOutput);
>     AzureAppServicePreDeploymentData azureAppServicePreDeploymentData = getPreDeploymentData(ambiance, stepParameters);
>     if (isEmpty(lastDeploymentProgressMarker) || azureAppServicePreDeploymentData == null) {
> ```

nit: this check can be split so we can first check azureAppServicePreDeploymentData is present and then lastDeploymentProgressMarker should be fetched. If there is no previous deployment done then this will result in 4 requests when can be stopped after first one
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/35052#-N6ICt1R3JrPEuKMCMBd:-N6ICt1R3JrPEuKMCMBe:b-tdhiz9) ([raw file](https://github.com/harness/harness-core/blob/a15832c7b24ae3325f46c17185d7efd960bd6603/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L77)):*
> ```Java
>         getDeploymentProgressMarker(ambiance, stepParameters, trafficShiftSweepingOutput, swapSlotsSweepingOutput);
>     AzureAppServicePreDeploymentData azureAppServicePreDeploymentData = getPreDeploymentData(ambiance, stepParameters);
>     if (isEmpty(lastDeploymentProgressMarker) || azureAppServicePreDeploymentData == null) {
> ```

isEmpty(lastDeploymentProgressMarker) should result in starting rollback from the start, any steps may not report progress marker if there is a timeout. I think check should be only for azureAppServicePreDeploymentData
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/35052#-N6IAj5p56GDbwQz1jQ-:-N6IAj5p56GDbwQz1jQ0:bessfi7) ([raw file](https://github.com/harness/harness-core/blob/a15832c7b24ae3325f46c17185d7efd960bd6603/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppRollbackStep.java#L79)):*
> ```Java
>     if (isEmpty(lastDeploymentProgressMarker) || azureAppServicePreDeploymentData == null) {
>       return TaskRequest.newBuilder()
>           .setSkipTaskRequest(SkipTaskRequest.newBuilder().setMessage("Rollback data not found").build())
> ```

nit: message should be more clear for user that slot deployment step not executed

**Review by abosii-harness — APPROVED** [review]
> Reviewed 14 of 14 files at r3, 6 of 8 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)* status: 1. unresolved discussions.

**Review by vlica-harness — APPROVED** [review]

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 23 of 43 files at r1, 12 of 14 files at r3, 6 of 8 files at r4, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052#-:-N6Ng5M9Bz1V4ZtcR0i_:bnfp4nl)* status: 1. unresolved discussions.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)* status: 1. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)* status: 1. unresolved discussions.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 18 of 43 files at r1, 9 of 14 files at r3, 6 of 8 files at r4, 1 of 3 files at r6, 1 of 1 files at r7, 10 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35052)* status: :shipit: complete! ✓

**Pull request merged**
