### PR TITLE
[feat]: [PL-31462]: Pre_QA: Added changes on NG side to accommodate data inconsistency between CG and NG user

### PR DESCRIPTION
**Pull request by shashank-harness**
## Describe your changes
Includes two things:

- Couple of functionality to complete phase 2 of User mgmt.
  - Only CG Users will appear on CG UI
  - We can delete an NG User if its NOT SCIM managed on NG side in the same account 
- Few more changes required in order to fix issues that may arise if we enable new User Mgmt.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)

### CODE REVIEW

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 430 at r3](https://reviewable.io/reviews/harness/harness-core/48300#-NWG1zg69tzQ4LAGQnGq:-NWG1zg69tzQ4LAGQnGr:b-lp9x1a) ([raw file](https://github.com/harness/harness-core/blob/fa2aa7ff2a413be6a8b1df7b53ed5800f96870b0/400-rest/src/main/java/software/wings/resources/UserResource.java#L430)):*
> ```Java
>       throw exception;
>     } else if (user.isImported()) {
>       throw exception;
> ```

nit: we could have ORed this two conditions :smiley: 



_Code quote:_
```Java
    if (featureFlagService.isEnabled(FeatureName.PL_USER_ACCOUNT_LEVEL_DATA_FLOW, accountId)
        && userServiceHelper.isSCIMManagedUser(accountId, user, CG)) {
      throw exception;
    } else if (user.isImported()) {
      throw exception;
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3772 at r3](https://reviewable.io/reviews/harness/harness-core/48300#-NWG2dJA4yZYNesZctB5:-NWG2dJA4yZYNesZctB6:bfse4k1) ([raw file](https://github.com/harness/harness-core/blob/fa2aa7ff2a413be6a8b1df7b53ed5800f96870b0/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3772)):*
> ```Java
>         && userServiceHelper.validationForUserAccountLevelDataFlow(user, accountId)) {
>       if (null != user.getUserAccountLevelDataMap().get(accountId)
>           && user.getUserAccountLevelDataMap().get(accountId).getUserProvisionedTo().contains(generation)) {
> ```

minor : can there be a possible NPE case here?



_Suggestion:_
```Java
user.getUserAccountLevelDataMap().get(accountId).getUserProvisionedTo().contains
```

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 10 of 13 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 430 at r3](https://reviewable.io/reviews/harness/harness-core/48300#-NWG1zg69tzQ4LAGQnGq:-NWGW71eDu_JZ4-4jOhx:b-7ql1td) ([raw file](https://github.com/harness/harness-core/blob/fa2aa7ff2a413be6a8b1df7b53ed5800f96870b0/400-rest/src/main/java/software/wings/resources/UserResource.java#L430)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: we could have ORed this two conditions :smiley: 
</blockquote></details>

fixed

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3772 at r3](https://reviewable.io/reviews/harness/harness-core/48300#-NWG2dJA4yZYNesZctB5:-NWGWC0I6jZdfVuN8oqa:b-arcd6l) ([raw file](https://github.com/harness/harness-core/blob/fa2aa7ff2a413be6a8b1df7b53ed5800f96870b0/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3772)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor : can there be a possible NPE case here?
</blockquote></details>

This will take care of all validations 



_Code snippet:_
```Java
userServiceHelper.validationForUserAccountLevelDataFlow(user, accountId)
```

**Comment by shashank-harness** [comment]
trigger uts

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 7 of 13 files at r1, 3 of 4 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
trigger messagecheck

**Comment by shashank-harness** [comment]
trigger uts

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
trigger uts

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48300)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
trigger ut2

**Pull request merged**
