### PR TITLE
[fix]: [CDS-81889]: fixed container step group for looping strategies

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
Fixed Container Step Group for a case when a step inside it is using looping strategy.
Currently, pipeline service create a list of requests for pluginInfo with a requestId corresponding to every request and call other services to get pluginInfo as response. This requestId is equal to step uuid. And looking from code, it seems like requestId has to be unique as we create map with this requestId (as key). 
Now when we are using looping strategy to run a step x times concurrently, there will be x requests for pluginInfo but for all request, (requestId) step uuid remains same and it throws duplicate key exception while creating map.
To fix this issue, I have modified requestId to be equal to (step uuid + step identifier) as we have unique step identifier for each step instance in looping strategy.

## Testing
Tested running run step with all type of looping strategy inside container step group
Screenshot 2023-10-19 at 9 40 49 AM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54345)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/54345#-Nh59aN59nkQ0-VZl7uU:-Nh59aN59nkQ0-VZl7uV:b-gwknnl) ([raw file](https://github.com/harness/harness-core/blob/31162f87dbff10dd830e5e1f3b4a6c272c3db0b9/pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java#L137)):*
> ```Java
>                 .setOsType(os.getYamlName())
>                 .setUsedPortDetails(PortDetails.newBuilder().addAllUsedPorts(usedPorts).build())
>                 .setRequestId(stepInfo.getStepUuid())
> ```

Isnt stepUUid always unique?

**Review by PragyeshMishra01 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54345)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/54345#-Nh59aN59nkQ0-VZl7uU:-Nh5lBEx-5KPtbUcf692:b7mrkfk) ([raw file](https://github.com/harness/harness-core/blob/31162f87dbff10dd830e5e1f3b4a6c272c3db0b9/pipeline-service/service/src/main/java/io/harness/pms/plugin/ContainerStepV2PluginProviderImpl.java#L137)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Isnt stepUUid always unique?
</blockquote></details>

It will be unique for a step. But we run a step x times concurrently, then it will not be unique

**Review by piyush-bhuwalka — APPROVED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54345)* status: 1 file(s) to review.

**Comment by PragyeshMishra01** [comment]
trigger review

**Pull request merged**
