### PR TITLE
fix: [PL-23072]: Removing error log line from GitContextHelper

### PR DESCRIPTION
**Pull request by goelsatyam2**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31690)

### CODE REVIEW

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by goelsatyam2** [comment]
trigger messagecheck

**Review by bhavya181 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690#-:-MyrQdET-cMjow5D391W:bnfp4nl)* status: 1 file(s) to review.

**Comment by mohitg0795** [comment]
___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/helpers/GitContextHelper.java, line 29 at r1](https://reviewable.io/reviews/harness/harness-core/31690#-MyrxG2s5o_1lO47QU36:-MyrxG2s5o_1lO47QU37:brphmtd) ([raw file](https://github.com/harness/harness-core/blob/5aa269e24bfa5f30f72406337ff231575a228b47/900-git-sync-sdk/src/main/java/io/harness/gitsync/helpers/GitContextHelper.java#L29)):*
> ```Java
>         GlobalContextManager.get(GitSyncBranchContext.NG_GIT_SYNC_CONTEXT);
>     if (gitSyncBranchContext == null) {
>       log.error("Git branch context set as null even git sync is enabled");
> ```

@bhavya181 @deepakpatankar whats the use-case for this comment? Should we improve this comment or is it totally useless?

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690)* status: 1 file(s) to review. 1. unresolved discussions. 

___
*[900-git-sync-sdk/src/main/java/io/harness/gitsync/helpers/GitContextHelper.java, line 29 at r1](https://reviewable.io/reviews/harness/harness-core/31690#-MyrxG2s5o_1lO47QU36:-Myu6Nww98OGo_AVGUm8:b9ox3f8) ([raw file](https://github.com/harness/harness-core/blob/5aa269e24bfa5f30f72406337ff231575a228b47/900-git-sync-sdk/src/main/java/io/harness/gitsync/helpers/GitContextHelper.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@bhavya181 @deepakpatankar whats the use-case for this comment? Should we improve this comment or is it totally useless?
</blockquote></details>

we can remove this comment, it is not useful

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690#-:-MyuSyIw1jV3SQ0D9GkO:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690#-:-MyzkDmRA9ofBav0NWX_:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31690)* status: :shipit: complete! ✓

**Pull request merged**
