### PR TITLE
feat: [PIE-9451]: Settings support for on demand rollback and few improvements

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added Ng-Settings support for On-demand rollback

New Setting added with identifier - `enable_user_marked_failure_interrupt_for_pipeline` ( This can be enabled/disabled at Acc/Org/Project scope)
( Tested out Both True/False scenerio's for this setting)

Also added support for Multiple `UserMarkedFailure` interrupts ( Tested that even after triggering multiple `UserMarkedFailure` interrupts pipeline remains the consistent state, and the stage/step steps gets failed appropiately with proper error message ) 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46092)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 171 at r2](https://reviewable.io/reviews/harness/harness-core/46092#-NSG90-qAV5UU6QrvjoI:-NSG90-qAV5UU6QrvjoJ:b-oc60iy) ([raw file](https://github.com/harness/harness-core/blob/a8a5750a5b439ebe2af82af498875e874391ba90/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L171)):*
> ```YAML
>       - ACCOUNT
>   - identifier: enable_user_marked_failure_interrupt_for_pipeline
>     name: Enable User Marked Failure Interrupt For Pipeline
> ```

nit: "Allow user to mark the step as failed explicitily"

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java` line 470 at r2](https://reviewable.io/reviews/harness/harness-core/46092#-NSGDsdo9pK1WPJbYzMn:-NSGDsdo9pK1WPJbYzMo:b-m5z41m) ([raw file](https://github.com/harness/harness-core/blob/a8a5750a5b439ebe2af82af498875e874391ba90/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java#L470)):*
> ```Java
>             "Could not fetch [User Marked Failure Interrupt] Settings, Please contact Harness for further support.");
>       }
>       if (!ENABLE_USER_MARKED_FAILURE_INTERRUPT_FOR_PIPELINE_TRUE_VALUE.equals(enableNodeAudit)) {
> ```

nit: rename variable

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java` line 472 at r2](https://reviewable.io/reviews/harness/harness-core/46092#-NSGDyFV6Y0iMkRRd8Wi:-NSGDyFV6Y0iMkRRd8Wj:boeqgww) ([raw file](https://github.com/harness/harness-core/blob/a8a5750a5b439ebe2af82af498875e874391ba90/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java#L472)):*
> ```Java
>       if (!ENABLE_USER_MARKED_FAILURE_INTERRUPT_FOR_PIPELINE_TRUE_VALUE.equals(enableNodeAudit)) {
>         throw new InvalidRequestException(
>             "[User Marked Failure Interrupt] Settings is not enabled, Please contact Harness for further support.");
> ```

nit: Please enable setting if you want to use this product.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46092)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46092)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46092)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
Approved for `settings.yml` change

**Pull request merged**
