### PR TITLE
feat: [IDP-1969]: Backstage Permissions Sync Job

### PR DESCRIPTION
**Pull request by Aashrit-Harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57493)

### CODE REVIEW

**Comment by Aashrit-Harness** [comment]
trigger uts

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57493)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/envvariable/jobs/BackstageEnvVariablesSyncJob.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/57493#-NnxUqygD-jWqgqz6Xbp:-NnxUqygD-jWqgqz6Xbq:brgvej8) ([raw file](https://github.com/harness/harness-core/blob/0ce2cb208b4a632e60e82b8f198eb81ad96f1efe/idp-service/src/main/java/io/harness/idp/envvariable/jobs/BackstageEnvVariablesSyncJob.java#L48)):*
> ```Java
>     executorService = Executors.newSingleThreadScheduledExecutor(
>         new ThreadFactoryBuilder().setNameFormat("backstage-env-variable-sync-job").build());
>     executorService.scheduleWithFixedDelay(this::run, 0, DELAY_IN_MINUTES, TimeUnit.MINUTES);
> ```

You have to update a test. It'll fail because of this change.



_Code quote:_
```Java
0,
```
___
*[`idp-service/src/main/java/io/harness/idp/settings/jobs/BackstagePermissionsSyncJob.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/57493#-NnxVT-0-gYMUIIDTHiJ:-NnxVT-0-gYMUIIDTHiK:b-d0xgxw) ([raw file](https://github.com/harness/harness-core/blob/0ce2cb208b4a632e60e82b8f198eb81ad96f1efe/idp-service/src/main/java/io/harness/idp/settings/jobs/BackstagePermissionsSyncJob.java#L36)):*
> ```Java
> 
>   @Inject
>   public BackstagePermissionsSyncJob(@Named("backstageEnvVariableSyncer") ScheduledExecutorService executorService,
> ```

This needs to be changed



_Code quote:_
```Java
backstageEnvVariableSyncer
```
___
*[`idp-service/src/main/java/io/harness/idp/settings/jobs/BackstagePermissionsSyncJob.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/57493#-NnxVUTTCdzbKqyYrc8F:-NnxVUTTCdzbKqyYrc8G:b-ia41wb) ([raw file](https://github.com/harness/harness-core/blob/0ce2cb208b4a632e60e82b8f198eb81ad96f1efe/idp-service/src/main/java/io/harness/idp/settings/jobs/BackstagePermissionsSyncJob.java#L46)):*
> ```Java
>   public void start() throws Exception {
>     executorService = Executors.newSingleThreadScheduledExecutor(
>         new ThreadFactoryBuilder().setNameFormat("backstage-env-variable-sync-job").build());
> ```

same comment as above



_Code quote:_
```Java
backstage-env-variable-sync-job
```
___
*[`idp-service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/57493#-NnxVnrJD9NczUY86LOG:-NnxVnrJD9NczUY86LOH:bnv4nx7) ([raw file](https://github.com/harness/harness-core/blob/0ce2cb208b4a632e60e82b8f198eb81ad96f1efe/idp-service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L101)):*
> ```Java
>     Optional<BackstagePermissionsEntity> permissionsEntity =
>         backstagePermissionsRepository.findByAccountIdentifier(accountIdentifier);
>     BackstagePermissions backstagePermissions = permissionsEntity.map(BackstagePermissionsMapper::toDTO).get();
> ```

in case we don't have a record in db for this account, this would throw an error
most likely won't happen.
but we can do this to be safe 
```permissionsEntity.map(BackstagePermissionsMapper::toDTO).ifPresent(backstagePermissions -> updateConfigMap(backstagePermissions, accountIdentifier));```



_Code quote:_
```Java
get()
```

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57493#-:-NnxcFp49EoQWG4jtDsX:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sandeepa-kv-jois — APPROVED** [review]

**Comment by Aashrit-Harness** [comment]
trigger uts

**Comment by Aashrit-Harness** [comment]
trigger review

**Pull request merged**
