### PR TITLE
fix: [CDS-48905]: merge artifact template inputs with template spec for getBuilds tasks

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Merge inputs provided while linking artifact source template to service with template spec for getBuilds
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41807)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/41807#-NJjHfwu8rpSG69-p2gG:-NJjHfwu8rpSG69-p2gH:b3cxlwn) ([raw file](https://github.com/harness/harness-core/blob/3b9fe205bcea82a66c902a63629313308b51946f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java#L63)):*
> ```Java
>   public String mergeRuntimeInputValuesIntoOriginalYamlForArrayNode(String oldInputsYaml, String newInputsYaml)
>       throws IOException {
>     if (isEmpty(newInputsYaml)) {
> ```

new yaml is the input set yaml here. If the input set yaml is empty but the old Yaml ( artifact template spec node ) is not empty, should we not return the old yaml itself ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41807)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41807)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/41807#-NJjHfwu8rpSG69-p2gG:-NJkO9mQ-WjzE8WNn76a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b9fe205bcea82a66c902a63629313308b51946f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java#L63)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

new yaml is the input set yaml here. If the input set yaml is empty but the old Yaml ( artifact template spec node ) is not empty, should we not return the old yaml itself ? 
</blockquote></details>

Done.

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41807)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41807)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41807)* status: :shipit: complete! ✓

**Pull request merged**
