### PR TITLE
[fix]: [CDS-35819]: deleted AZURE_WEBAPP_NON_CONTAINER

### PR DESCRIPTION
**Pull request by vaibhav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32341)

### CODE REVIEW

**Comment by vaibhav-harness** [comment]
trigger messagecheck

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32341)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceHelper.java, line 1082 at r2](https://reviewable.io/reviews/harness/harness-core/32341#-N0A33v51wynE1uCIm51:-N0A33v659EuYr6zd1lB:bisuwex) ([raw file](https://github.com/harness/harness-core/blob/957e416ad850136f4f836c0c36d6f01a133b7048/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceHelper.java#L1082)):*
> ```Java
>           format("Azure WebApp non-container deployment is disabled by feature flag for account id : %s", accountId),
>           USER);
>     }
> ```

We can remove this entire IF block, we already have validation for FeatureName.AZURE_WEBAPP at the top

**Review by anilchowdhury-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32341)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32341#-:-N0Aq5oH9D5tARVkJ_uV:bnfp4nl)* status: :shipit: complete! ✓

**Pull request closed without merging**
