### PR TITLE
[fix]: [CI-3532]: TI - add logging when instrumentation is disabled

### PR DESCRIPTION
**Pull request by hemanthmantri**
Addon doesn't attach TI intrumentation agents for certain cases where
instrumentation is disabled. This change adds logs to help debug when
the agent is not being attached.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30824)

### CODE REVIEW

**Comment by hemanthmantri** [comment]
trigger compile

**Comment by hemanthmantri** [comment]
trigger compile

**Review by jamie-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30824)* status: Some of the checks are too old.

**Comment by jamie-harness** [comment]
@hemanthmantri Pull latest master and trigger go build. I have fixed the go build in another PR

**Review by jamie-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30824#-:-MweQMBz8_WDmYx4OwM8:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vistaarjuneja** [comment]
trigger ft1

**Comment by vistaarjuneja** [comment]
trigger ft2

**Review by jamie-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30824)* status: Some of the checks are too old.

**Review by jamie-harness — APPROVED** [review]

**Review by vistaarjuneja — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30824#-:-Mx3Ii-X5khWfVJ3CO62:bnfp4nl)* status: Some of the checks are too old.

**Comment by hemanthmantri** [comment]
> @hemanthmantri Pull latest develop and trigger go build. I have fixed the go build in another PR

@jamie-harness : Apparently you need to resolve this comment and approve again.

**Review by jamie-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30824)* status: Some of the checks are too old.

**Comment by hemanthmantri** [comment]
reopening to re-trigger checks

**Pull request closed without merging**
