### PR TITLE
[fix]:[pl-27461]: fix GetTemplate

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Fix getTemplate for non default branch. GetTemplate has been been tested with and without the parent reference for default and non default branch

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36600)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36600)

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/36600#-NA4Ojex5fU_DuIcfKaN:-NA4Ojex5fU_DuIcfKaO:b5fqf14) ([raw file](https://github.com/harness/harness-core/blob/d8a8b10011f3641985846d141c95d0f928aa60d2/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L22)):*
> ```Java
>     GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
>     String branchName = gitEntityInfo.getBranch();
>     if (isParentReferenceEntityPresent(gitEntityInfo)) {
> ```

if its not present, then we should return branchName right?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/test/java/io/harness/template/helpers/TemplateGitXHelperTest.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/36600#-NA4OwYS75ZlJVrMbEeD:-NA4OwYS75ZlJVrMbEeE:bsgy2y8) ([raw file](https://github.com/harness/harness-core/blob/d8a8b10011f3641985846d141c95d0f928aa60d2/840-template-service/src/test/java/io/harness/template/helpers/TemplateGitXHelperTest.java#L52)):*
> ```Java
>   @Owner(developers = ADITHYA)
>   @Category(UnitTests.class)
>   public void testGetWorkingBranch() {
> ```

Can we put explicit UTs for getWorkingBranch for INLINE and REMOTE Templates, with and without parentReference

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36600)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/36600#-NA4Ojex5fU_DuIcfKaN:-NA4QZWf2DgjoQA6mxZ2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8a8b10011f3641985846d141c95d0f928aa60d2/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if its not present, then we should return branchName right?
</blockquote></details>

Done.
___
*[`840-template-service/src/test/java/io/harness/template/helpers/TemplateGitXHelperTest.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/36600#-NA4OwYS75ZlJVrMbEeD:-NA4QUwc1M_9kpkzVGNY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d8a8b10011f3641985846d141c95d0f928aa60d2/840-template-service/src/test/java/io/harness/template/helpers/TemplateGitXHelperTest.java#L52)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we put explicit UTs for getWorkingBranch for INLINE and REMOTE Templates, with and without parentReference
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36600)* status: :shipit: complete! ✓

**Review by bhavya181 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36600)* status: :shipit: complete! ✓

**Pull request merged**
