### PR TITLE
[feat]: [CDS-57898]: Added Exec and SFTP flows in SSH client and integrated

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes

1. Introduced SSH Manager as a interface to work with new SSH client.
2. Users should plan to user SshManager to do exec/sftp or scp via this.
3. Fixed few bugs where FF boolean was not passed everywhere.
4. Introduced specific ErrorCode.
5. Tested both CG and NG bash flows -- includes Shell script step, Copy and Download artifacts, copy configs.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46081)

### CODE REVIEW

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46081)* status: 22 file(s) to review. 0 of 2 approvals obtained.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 22 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46081)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/SSHAuthDTO.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSpo-d3BrvymhOklK7G:-NSpo-d3BrvymhOklK7H:b-ki8bjl) ([raw file](https://github.com/harness/harness-core/blob/a0b3e80c62730aba034e89d85cb423e9b00d4d77/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/SSHAuthDTO.java#L38)):*
> ```Java
>   private BaseSSHSpecDTO spec;
> 
>   @JsonIgnore private boolean useSshClient;
> ```

These two properties should be ignored by the Jackson serializer and deserializer, right? 
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptSshExecutor.java` line 258 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSpppGp2wIlqLCZgMjQ:-NSpppGp2wIlqLCZgMjR:baekiq1) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ScriptSshExecutor.java#L258)):*
> ```Java
>   }
> 
>   private ExecuteCommandResponse executeWithSshClient(
> ```

Minor -  rename executeWithSshClient >> executeCommandStringWithSshClient
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqwJTy-L_DfOvsInWx:-NSqwJTy-L_DfOvsInWy:b-xvx655) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java#L45)):*
> ```Java
>         clientCache.get(key).setLogCallback(logCallback);
>       }
>       return clientCache.get(key);
> ```

We are using ConcurrentMap but we are not thread-safe in getSshClient method, I suggest using atomic operation which cannot be interrupted between checking the presence of the key and the replacement of the value, use computeIfAbsent..
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqyT7yCtYnSot50kDl:-NSqyT7z5a79iXwfQK9P:b-k4ldpj) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java#L105)):*
> ```Java
>       SshClient sshClient = clientCache.get(cacheKey.get());
>       if (null != sshClient) {
>         sshClient.close();
> ```

If one thread closes sshClient and another thread tries to do the same, will we get an exception?
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/SshUtils.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqzcio8wKG0W9bi1EA:-NSqzcio8wKG0W9bi1EB:b-14ardu) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/SshUtils.java#L53)):*
> ```Java
>       return Optional.empty();
>     } else {
>       return Optional.of(executionId + "~" + host.trim());
> ```

Are we using "~" for the purpose?
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/BaseSshRequest.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqzvN-5XpRAaNgoKjJ:-NSqzvN-5XpRAaNgoKjK:b-912saf) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/client/BaseSshRequest.java#L18)):*
> ```Java
>   private boolean retry = false;
>   private SshClientType clientType = SshClientType.JSCH;
>   public enum SshClientType { JSCH, SSHJ }
> ```

Minor - I guess we will use SshClientType on multiple places in the code where logic will not be related to SshRequest, I suggest moving SshClientType from this class.
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/SshClient.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSr1TdT2oO6tS24m6pA:-NSr1TdT2oO6tS24m6pB:bf0o4l2) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/client/SshClient.java#L98)):*
> ```Java
>           getSshSessionConfig().getExecutionId(), getSshSessionConfig().getHost());
>       connection = getConnection();
>       connectionCache.add(connection);
> ```

Just to check do we want to use CopyOnWriteArrayList here?
 
While writing the connection to the connection cache, it copies all elements from the previous underlining array and creates the new one, then adds a connection to the new array, and after that move synchronously referencing from the old array to the new one.
It works well when there are a lot of reads and very, very few WRITES.

Here, we are having writes and reads, right?

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqwJTy-L_DfOvsInWx:-NTG09nLCeuYD96AVd78:bmlz5dk) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java#L45)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We are using ConcurrentMap but we are not thread-safe in getSshClient method, I suggest using atomic operation which cannot be interrupted between checking the presence of the key and the replacement of the value, use computeIfAbsent..
</blockquote></details>

Thanks for this. I have updated this method.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqyT7yCtYnSot50kDl:-NTG0IQ04XTkzRxob22R:b9dfz07) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/SshClientManager.java#L105)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If one thread closes sshClient and another thread tries to do the same, will we get an exception?
</blockquote></details>

No. SshClient.close() is expected is handle all exceptions but not throw any.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/SshUtils.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqzcio8wKG0W9bi1EA:-NTG0OAv89SdqrE6Orcv:b-7nddz8) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/SshUtils.java#L53)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Are we using "~" for the purpose?
</blockquote></details>

This is in sync with current JSCH implementation we have in our code..

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/BaseSshRequest.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/46081#-NSqzvN-5XpRAaNgoKjJ:-NTG0TRS-Sb3yhl-s-Ue:b-gqwry5) ([raw file](https://github.com/harness/harness-core/blob/9d7f885654553d2cb457aa975866a89c58119a97/960-api-services/src/main/java/io/harness/shell/ssh/client/BaseSshRequest.java#L18)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - I guess we will use SshClientType on multiple places in the code where logic will not be related to SshRequest, I suggest moving SshClientType from this class.
</blockquote></details>

Thanks, I have extracted this out.

**Comment by arvind-choudhary-h** [comment]
Done

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 18 of 23 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46081)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]
LGTM

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46081#-:-NTJ8xa0CWBYWYHk3km_:bnfp4nl)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger review

**Pull request merged**
