### PR TITLE
fix: [spg-21]: Audit Cleanup

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38672)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38672#-:-NE6ehG19DScCcv5U_ft:bnfp4nl)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/38672#-NE7Qyz19BYBvpP7F-0L:-NE7Qyz19BYBvpP7F-0M:b-eh2879) ([raw file](https://github.com/harness/harness-core/blob/e45ec63a16275de23054513c9f13e25ff7e17362/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L392)):*
> ```Java
>           wingsPersistence.deleteOnServer(wingsPersistence.createQuery(AuditHeader.class, excludeAuthority)
>                                               .field(AuditHeaderKeys.createdAt)
>                                               .lessThan(retentionMillis));
> ```

this will delete lot of records in first run and cause issues. if we have excess of 100k records this will kill mongo.

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 384 at r1](https://reviewable.io/reviews/harness/harness-core/38672#-NE7RMvrBqaApWO5z48b:-NE7RMvrBqaApWO5z48c:br5tulh) ([raw file](https://github.com/harness/harness-core/blob/e45ec63a16275de23054513c9f13e25ff7e17362/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L384)):*
> ```Java
>   public void deleteAuditRecords(long retentionMillis) {
>     final int batchSize = 1000;
>     final int limit = 3000;
> ```

modify limit?

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 426 at r1](https://reviewable.io/reviews/harness/harness-core/38672#-NE7RblKB4MAqAut-Wxx:-NE7RblKB4MAqAut-Wxy:b-yyom79) ([raw file](https://github.com/harness/harness-core/blob/e45ec63a16275de23054513c9f13e25ff7e17362/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L426)):*
> ```Java
>         while (fileIdsToBeDeleted.hasNext()) {
>           DBObject record = fileIdsToBeDeleted.next();
>           String uuId = record.get("_id").toString();
> ```

Do we want to go dbcursor way?

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 441 at r1](https://reviewable.io/reviews/harness/harness-core/38672#-NE7RgNU96bwDkpg-5ZO:-NE7RgNU96bwDkpg-5ZP:b-961nlz) ([raw file](https://github.com/harness/harness-core/blob/e45ec63a16275de23054513c9f13e25ff7e17362/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L441)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error("Audit Files and Chunks deletion failed with Exception {}", e.getMessage());
> ```

we should log whole exception instead of just e.getmessage

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/AuditCleanupJob.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/38672#-NE7RupE9fSkiqJ8nyBV:-NE7RupFCBD-lYYNuRRo:b-lwkhc9) ([raw file](https://github.com/harness/harness-core/blob/e45ec63a16275de23054513c9f13e25ff7e17362/400-rest/src/main/java/software/wings/service/impl/instance/AuditCleanupJob.java#L54)):*
> ```Java
>   public void run() {
>     log.info("Audit Cleanup Job Started @ {}", Instant.now());
>     long toBeDeletedTillTimestamp =
> ```

wasnt it planned only for weekend

**Pull request merged**
