### PR TITLE
feat: [CDS-74850]: Added the API to import template from market place

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Added a new API which will import template from Global template Market Place.

- Global template doesn't have any scope, User will going to define the scope of the template during importing the template.
-  UI will be providing the scope information to API.
- We have to add ProjectIdentifier if user imported the template at project level.
- We have to add OrgIdentifier if user imported the template at org level.

TCs:

1. projectIdentifier and OrgIdentifier should be added to the Yaml if template imported at project level.
2. OrgIdentifier should be added to the Yaml if template imported at org level.
3. Nothing should be added if template imported at account level.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51922)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 696 at r1](https://reviewable.io/reviews/harness/harness-core/51922#-NcVhPR89TvlTae72WtS:-NcVhPR89TvlTae72WtT:baympm1) ([raw file](https://github.com/harness/harness-core/blob/9f9a0699d79cdf16dbe90c1f8fcc29f2375b111b/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateResource.java#L696)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns the created Template")
>       })
>   ResponseDTO<TemplateWrapperResponseDTO>
> ```

Can we create a global template resource for global templates?

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateService.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/51922#-NcVhU8s9YR5jh7K0uau:-NcVhU8s9YR5jh7K0uav:b-t14w2) ([raw file](https://github.com/harness/harness-core/blob/9f9a0699d79cdf16dbe90c1f8fcc29f2375b111b/template-service/service/src/main/java/io/harness/template/services/NGTemplateService.java#L122)):*
> ```Java
>   GovernanceMetadata validateGovernanceRules(TemplateEntity templateEntity);
>   void populateSetupUsageAsync(TemplateEntity templateEntity);
>   String importTemplateFromGlobalTemplateMarketPlace(
> ```

Can we create a globalTemplateService for all global templates method?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51922)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Pull request closed without merging**
