### PR TITLE
[feat]: [CDS-76329]: Fix for testing github connectors

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added code to make the scm list repos backward compatible. Have tested out the test connection for all the git providers.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51330)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`product/ci/scm/proto/scm_service.proto` line 785 at r1](https://reviewable.io/reviews/harness/harness-core/51330#-NavAR5_6s_R5IuRyq51:-NavAR5_6s_R5IuRyq52:b-kjimu7) ([raw file](https://github.com/harness/harness-core/blob/d06bd2854075fe43d5510893ee34db9bc0e4a6b8/product/ci/scm/proto/scm_service.proto#L785)):*
> ```proto
>   bool fetchAllRepos = 3;
>   RepoFilterParams repoFilterParams = 4;
>   int32 version = 5;
> ```

lets add a comment on this field on how to use it

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 968 at r1](https://reviewable.io/reviews/harness/harness-core/51330#-NavCSR57JIYIb1C35f9:-NavCSR6AsQb7SIMZ4uT:b-cgh71y) ([raw file](https://github.com/harness/harness-core/blob/d06bd2854075fe43d5510893ee34db9bc0e4a6b8/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L968)):*
> ```Java
>       SCMGrpc.SCMBlockingStub scmBlockingStub, RepoFilterParamsDTO repoFilterParamsDTO) {
>     GetUserReposRequest getUserReposRequest =
>         buildGetUserReposRequest(scmConnector, pageRequest, repoFilterParamsDTO, 2);
> ```

please use some constant here

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51330)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 968 at r1](https://reviewable.io/reviews/harness/harness-core/51330#-NavCSR57JIYIb1C35f9:-NavH0gI6zaxcghmAQz9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d06bd2854075fe43d5510893ee34db9bc0e4a6b8/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L968)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please use some constant here
</blockquote></details>

Done.
___
*[`product/ci/scm/proto/scm_service.proto` line 785 at r1](https://reviewable.io/reviews/harness/harness-core/51330#-NavAR5_6s_R5IuRyq51:-NavH1GWBUxUQ1vlUVH6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d06bd2854075fe43d5510893ee34db9bc0e4a6b8/product/ci/scm/proto/scm_service.proto#L785)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets add a comment on this field on how to use it
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 151 at r2](https://reviewable.io/reviews/harness/harness-core/51330#-NavHQk93DKKzVVopk3X:-NavHQk93DKKzVVopk3Y:bh2o1ov) ([raw file](https://github.com/harness/harness-core/blob/d463a762be077ed16de84a2cb6c68ba4da318899/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L151)):*
> ```Java
>   ScmGitProviderHelper scmGitProviderHelper;
>   SCMGitAccessToProviderMapper scmGitAccessToProviderMapper;
>   public static final int LIST_REPO_API_VERSION_TWO = 2;
> ```

if default is 0, then new one should be 1

**Review by mohitg0795 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51330)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger gobuild

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51330)* status: 5 file(s) to review.

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
