### PR TITLE
[feat]: [CDS-34222]: Create Cloudformation skeleton tasks

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31029)

### CODE REVIEW

**Comment by nassergonzalez** [comment]
trigger messagecheck

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31029)* status: 17 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cf/CFTaskType.java, line 15 at r2](https://reviewable.io/reviews/harness/harness-core/31029#-MwzF4GxAHsu9Cjicgcs:-MwzF4Gy-3WqRdZm_H5t:b-1n3flc) ([raw file](https://github.com/harness/harness-core/blob/a476ae41139f4c7dc4e0c2825bb1a618d0633dd3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cf/CFTaskType.java#L15)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> 
> public enum CFTaskType {
> ```

Let's try not to use CF abbreviation  for cloudformation

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31029)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31029)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cf/CloudformationCommandUnit.java, line 8 at r2](https://reviewable.io/reviews/harness/harness-core/31029#-MwzL894EdaLRx-pwDrr:-MwzL894EdaLRx-pwDrs:b-io4o6r) ([raw file](https://github.com/harness/harness-core/blob/a476ae41139f4c7dc4e0c2825bb1a618d0633dd3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/cf/CloudformationCommandUnit.java#L8)):*
> ```Java
>  */
> 
> package io.harness.delegate.task.cf;
> ```

Let's use cloudformation instead of cf.

**Review by tmacari-harness — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31029)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31029)* status: :shipit: complete! ✓

**Pull request merged**
