### PR TITLE
[fix]: [PIE-4209]: Removing dependency 860-orchestration-steps (pipeline internal module) from cd service

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Removing dependency 860-orchestration-steps (pipeline internal module) from cd service

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: 118 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 287 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5KARVQ5TCk0PGdXnKb:-N5KARVQ5TCk0PGdXnKc:b-8q9cx5) ([raw file](https://github.com/harness/harness-core/blob/0274da53ab1957b95d49f6690d3d0699e44e0f70/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L287)):*
> ```Java
>   public static void configureObjectMapper(final ObjectMapper mapper) {
>     HObjectMapper.configureObjectMapperForNG(mapper);
>     mapper.registerModule(new PmsBeansJacksonModule());
> ```

This is pipeline internal jackson module, it has yamlOutputProperties etc which are used by others, but they use for variables as protos and only pipeline-service needs proto to jackson serialisation
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 618 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5KFxel5mPOh8QJaJLg:-N5KFxel5mPOh8QJaJLh:b-93ivo7) ([raw file](https://github.com/harness/harness-core/blob/0274da53ab1957b95d49f6690d3d0699e44e0f70/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L618)):*
> ```Java
>     });
>     install(OrchestrationModule.getInstance(getOrchestrationConfig()));
>     install(OrchestrationStepsModule.getInstance(null));
> ```

internal modules



_Code quote:_
```Java
    install(OrchestrationModule.getInstance(getOrchestrationConfig()));
    install(OrchestrationStepsModule.getInstance(null));
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/executions/resources/CDNGExecutionResource.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5KSqE88hX5daxEAPO4:-N5KSqE88hX5daxEAPO5:buvzefp) ([raw file](https://github.com/harness/harness-core/blob/0274da53ab1957b95d49f6690d3d0699e44e0f70/120-ng-manager/src/main/java/io/harness/ng/executions/resources/CDNGExecutionResource.java#L78)):*
> ```Java
>     log.info("Get pipeline");
>     return ResponseDTO.newResponse(PipelineConfig.builder().build());
>   }
> ```

pipeline code, moved to pipeline service



_Code quote:_
```Java
  @GET
  @ApiOperation(value = "dummy api for checking pms schema", nickname = "dummyApiForSwaggerSchemaCheck")
  @Path("/dummyApiForSwaggerSchemaCheck")
  // DO NOT DELETE THIS WITHOUT CONFIRMING WITH UI
  public ResponseDTO<PipelineConfig> dummyApiForSwaggerSchemaCheck() {
    log.info("Get pipeline");
    return ResponseDTO.newResponse(PipelineConfig.builder().build());
  }
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/ShellType.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5KhqOe9Yke6R22xxim:-N5KhqOe9Yke6R22xxin:b-hqyla9) ([raw file](https://github.com/harness/harness-core/blob/28335a76e42722eec6fc899bfc51bd2051ee4ddf/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/ShellType.java#L8)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.GITOPS)
> public enum ShellType {
> ```

gitops should have differnt shelltype rather than using shellstep one



_Code quote:_
```Java
ShellType {
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5Khz2v9xrhDtOF7D9F:-N5Khz2v9xrhDtOF7D9G:bli3gb9) ([raw file](https://github.com/harness/harness-core/blob/28335a76e42722eec6fc899bfc51bd2051ee4ddf/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L292)):*
> ```Java
>   }
> 
>   String getWorkingDirectory(
> ```

shell helpers which were used from pipeline, thus cloned it, they should use common ones



_Code quote:_
```Java
  Map<String, String> getEnvironmentVariables(Map<String, Object> inputVariables) {
    if (EmptyPredicate.isEmpty(inputVariables)) {
      return new HashMap<>();
    }
    Map<String, String> res = new LinkedHashMap<>();
    inputVariables.forEach((key, value) -> {
      if (value instanceof ParameterField) {
        ParameterField<?> parameterFieldValue = (ParameterField<?>) value;
        if (parameterFieldValue.getValue() == null) {
          throw new InvalidRequestException(String.format("Env. variable [%s] value found to be null", key));
        }
        res.put(key, parameterFieldValue.getValue().toString());
      } else if (value instanceof String) {
        res.put(key, (String) value);
      } else {
        log.error(String.format(
            "Value other than String or ParameterField found for env. variable [%s]. value: [%s]", key, value));
      }
    });
    return res;
  }

  String getWorkingDirectory(
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResource.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5Ki8FH8sB2QD5rtfTb:-N5Ki8FH8sB2QD5rtfTc:b1s4azy) ([raw file](https://github.com/harness/harness-core/blob/28335a76e42722eec6fc899bfc51bd2051ee4ddf/800-pipeline-service/src/main/java/io/harness/pms/schema/PmsYamlSchemaResource.java#L109)):*
> ```Java
>   @Path("/dummyApiForSwaggerSchemaCheck")
>   // DO NOT DELETE THIS WITHOUT CONFIRMING WITH UI
>   public ResponseDTO<PipelineConfig> dummyApiForSwaggerSchemaCheck() {
> ```

complete pipeline swagger
___
*[`880-pipeline-cd-commons/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/34657#-N5K9u043ai7sMUBsGGX:-N5K9u043ai7sMUBsGGY:b-ktviaw) ([raw file](https://github.com/harness/harness-core/blob/28335a76e42722eec6fc899bfc51bd2051ee4ddf/880-pipeline-cd-commons/BUILD.bazel#L6)):*
> ```Starlark
> 
> java_library(
>     name = "module",
> ```

Added this module as cd and pipeline are sharing output/outcomes beans from infra and shellstep



_Code quote:_
```Starlark
name = "module",
```

**Review by inderschera — APPROVED** [review]
> Reviewed 106 of 118 files at r1, 2 of 2 files at r2, 53 of 53 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: Waiting on team(s): sto.

**Review by inderschera — DISMISSED** [review]
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: 11 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: 11 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 104 of 118 files at r1, 2 of 2 files at r2, 36 of 53 files at r4, 9 of 11 files at r5, 31 of 31 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: 33 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657#-:-N5ckOMZ0mrS4zR7enCJ:bnfp4nl)* status: 54 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by inderschera — APPROVED** [review]
> Reviewed 19 of 31 files at r7, 20 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: 15 file(s) to review. Waiting on team(s): sto.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 9 of 11 files at r5, 19 of 31 files at r7, 20 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34657)* status: Waiting on team(s): sto.

**Pull request merged**
