### PR TITLE
fix: [CDS-70930]: check org/project validation with case sensitive id…

### PR DESCRIPTION
**Pull request by hingerabhinav**
…entifiers

## Describe your changes
validate org/project identifiers considering case. This is to disallow duplicate entities being created.
Since NG entities have uniqueness defined with case sensitive ids, index does not prevent creation when just case is different in project, org. So we end up with 2 entities.
We should disallow the creation of service where the project, org are just different in case.  
In case the case is correct, then unique index will disallow duplicate. 

Please note OrgProjectValidationHelper is just used by CD

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49040)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 294 at r1](https://reviewable.io/reviews/harness/harness-core/49040#-NXUsowM0IscUJAGkFUy:-NXUsowM0IscUJAGkFUz:buiob9s) ([raw file](https://github.com/harness/harness-core/blob/d70c8e830f4064acb1e32209f70ae797e2c91fb6/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L294)):*
> ```Java
> 
>   @Override
>   @DefaultOrganization
> ```

why do we need this annotation ? "DefaultOrganization"

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49040)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 294 at r1](https://reviewable.io/reviews/harness/harness-core/49040#-NXUsowM0IscUJAGkFUy:-NXUwXzk1RIJ8UBkw5s8:b-nbl5ty) ([raw file](https://github.com/harness/harness-core/blob/d70c8e830f4064acb1e32209f70ae797e2c91fb6/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L294)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why do we need this annotation ? "DefaultOrganization"
</blockquote></details>

This annotation assumes "default" as org identifier in case its not provided.

**Comment by hingerabhinav** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 294 at r1](https://reviewable.io/reviews/harness/harness-core/49040#-NXUsowM0IscUJAGkFUy:-NXUxAll0xC-0FsL1YJC:b51gfgp) ([raw file](https://github.com/harness/harness-core/blob/d70c8e830f4064acb1e32209f70ae797e2c91fb6/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L294)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

This annotation assumes "default" as org identifier in case its not provided.
</blockquote></details>

Its not needed exactly since we do check for org, project to be present in validation helper

**Comment by hingerabhinav** [comment]
trigger uts

**Review by meenakshi-harness — APPROVED** [review]
Lets make this solution case insensitive as part of this when planned https://harness.atlassian.net/browse/PL-28030

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49040)* status: Some of the checks are too old. 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Pull request merged**
