### PR TITLE
fix: [DEL-4472]: Upgrader gets immutable delegate image from DelegateVersionService

### PR DESCRIPTION
**Pull request by AnupamIO**
JIRA: https://harness.atlassian.net/browse/DEL-4472

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35565)

### CODE REVIEW

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35565)* status: :shipit: complete! ✓

**Review by mdmilic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35565)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/35565#-N7VkCBb3Lgc_PQPTrfP:-N7VkCBb3Lgc_PQPTrfQ:bz7xeqz) ([raw file](https://github.com/harness/harness-core/blob/498f5122d1d4eb3add7909ea3317fca3082e7d4f/400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java#L84)):*
> ```Java
>       return managerConfigImage;
>     }
>     return DEFAULT_DELEGATE_IMAGE_TAG;
> ```

This one should throw an exception if it gets to this point. There is no default tag for immutable delegate. Throw something like IllegalStateException. Feel free to let it propagate to HTTP 5xx

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35565)* status: :shipit: complete! ✓

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35565)* status: 1 change requests. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/35565#-N7VkCBb3Lgc_PQPTrfP:-N7uLmnV21oBrJC_o285:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/498f5122d1d4eb3add7909ea3317fca3082e7d4f/400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java#L84)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This one should throw an exception if it gets to this point. There is no default tag for immutable delegate. Throw something like IllegalStateException. Feel free to let it propagate to HTTP 5xx
</blockquote></details>

Done.

**Comment by AnupamIO** [comment]
trigger feature-build

**Pull request merged**
