### PR TITLE
feat: [CDS-37476]: Create config for environment for merged yaml with…

### PR DESCRIPTION
**Pull request by prashantsharma04**
… infra info

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger ti3

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: :shipit: complete! ✓

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/33118#-N2AiHHv6g1R9anHGO2e:-N2AiHHv6g1R9anHGO2f:b-y5pr9s) ([raw file](https://github.com/harness/harness-core/blob/d45d8ce9e786c6365f16aded353a613adf895f08/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L52)):*
> ```Java
> 
>   // environmentInputs
>   JsonNode environmentInputs;
> ```

should this be a Map<String, Object> why is this a json node?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/33118#-N2AiVC20BPTmYsMK40L:-N2AiVC20BPTmYsMK40M:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/d45d8ce9e786c6365f16aded353a613adf895f08/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java#L45)):*
> ```Java
> 
>   // inputs
>   JsonNode inputs;
> ```

ditto

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: 1 change requests. 1. unresolved discussions. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/33118#-N2AiHHv6g1R9anHGO2e:-N2AmZ3M6qdS5dR8cUVn:bvf8fid) ([raw file](https://github.com/harness/harness-core/blob/d45d8ce9e786c6365f16aded353a613adf895f08/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L52)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

should this be a Map<String, Object> why is this a json node?
</blockquote></details>

This contains the runtime inputs value. We will bee solving them similarly how we are solving in templates.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/33118#-N2AiVC20BPTmYsMK40L:-N2BIZVD-RAMCeAoo22H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d45d8ce9e786c6365f16aded353a613adf895f08/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinition.java#L45)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/33118#-N2BKBlkCjooRXH3LIWD:-N2BKBllCsrj1RqtAJFT:bm5rtax) ([raw file](https://github.com/harness/harness-core/blob/b03c98ee2ae15ee7aff9ea64a860981072761c32/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java#L33)):*
> ```Java
> @Builder
> @SimpleVisitorHelper(helperClass = InfraStructureDefinitionVisitorHelper.class)
> @TypeAlias("infraStructureDefinitionYaml")
> ```

should not change this
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/33118#-N2BKDaCEPPg2Ki5aQbd:-N2BKDaCEPPg2Ki5aQbe:bm5rtax) ([raw file](https://github.com/harness/harness-core/blob/b03c98ee2ae15ee7aff9ea64a860981072761c32/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java#L35)):*
> ```Java
> @TypeAlias("infraStructureDefinitionYaml")
> @OwnedBy(CDC)
> @RecasterAlias("io.harness.cdng.infra.yaml.InfraStructureDefinitionYaml")
> ```

should not change this

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/33118#-N2BKBlkCjooRXH3LIWD:-N2BNWnO5QwXz5EvIXva:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b03c98ee2ae15ee7aff9ea64a860981072761c32/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java#L33)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

should not change this
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/33118#-N2BKDaCEPPg2Ki5aQbd:-N2BNX483AzPIIV8Pl8f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b03c98ee2ae15ee7aff9ea64a860981072761c32/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/InfraStructureDefinitionYaml.java#L35)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

should not change this
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 7 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructurePlanCreatorConfig.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/33118#-N2BP6-490fL_7gaoQW8:-N2BP6-490fL_7gaoQW9:bvrxv9r) ([raw file](https://github.com/harness/harness-core/blob/b03c98ee2ae15ee7aff9ea64a860981072761c32/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructurePlanCreatorConfig.java#L27)):*
> ```Java
> @Data
> @Builder
> @TypeAlias("infrastructureConfig")
> ```

do we need to change the type alias as well to ```InfrastructurePlanCreatorConfig```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33118)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructurePlanCreatorConfig.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/33118#-N2BP6-490fL_7gaoQW8:-N2BQPbu2q9oG0P1O0RI:bva5jb0) ([raw file](https://github.com/harness/harness-core/blob/b03c98ee2ae15ee7aff9ea64a860981072761c32/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructurePlanCreatorConfig.java#L27)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need to change the type alias as well to ```InfrastructurePlanCreatorConfig``` 
</blockquote></details>

Yes we need to change that. Done

**Pull request merged**
