### PR TITLE
feat: [CDS-42671]: create new api to return sourceIdentifiers and their runtimeInputs

### PR DESCRIPTION
**Pull request by inderschera**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37077)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 2 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37077)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 460 at r2](https://reviewable.io/reviews/harness/harness-core/37077#-NAyVJyF8owmz0H4FTHp:-NAyVJyF8owmz0H4FTHq:b-38axor) ([raw file](https://github.com/harness/harness-core/blob/c0a45bdfbae2c4f5130c3394cf956f19b823f2cb/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L460)):*
> ```Java
>       value = "This api returns source identifiers and their runtime inputs YAML", nickname = "getArtifactSourceInputs")
>   @Hidden
>   public ResponseDTO<ServiceArtifactSourcesResponseDTO>
> ```

nit: we can change to ArtifactSourcesResponseDTO

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 458 at r2](https://reviewable.io/reviews/harness/harness-core/37077#-NAyVRLXAPeobzWLLkIX:-NAyVRLXAPeobzWLLkIY:bqcpvyy) ([raw file](https://github.com/harness/harness-core/blob/c0a45bdfbae2c4f5130c3394cf956f19b823f2cb/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L458)):*
> ```Java
>   @Path("/artifactSourceInputs/{serviceIdentifier}")
>   @ApiOperation(
>       value = "This api returns source identifiers and their runtime inputs YAML", nickname = "getArtifactSourceInputs")
> ```

+ add artifact source identifiers

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 483 at r2](https://reviewable.io/reviews/harness/harness-core/37077#-NAyWbsnDlhHxMwqTeTQ:-NAyWbsnDlhHxMwqTeTR:bc8mz1b) ([raw file](https://github.com/harness/harness-core/blob/c0a45bdfbae2c4f5130c3394cf956f19b823f2cb/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L483)):*
> ```Java
>       List<String> artifactSourceIdentifiers = new ArrayList<>();
>       Map<String, String> sourceIdentifierToSourceInputMap = new HashMap<>();
>       YamlField artifactSourcesField = primaryArtifactField.getNode().getField(YamlTypes.ARTIFACT_SOURCES);
> ```

null check for ```sources``` field

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37077)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 458 at r2](https://reviewable.io/reviews/harness/harness-core/37077#-NAyVRLXAPeobzWLLkIX:-NBBrzLw9USq1ddpKKot:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a45bdfbae2c4f5130c3394cf956f19b823f2cb/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L458)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

+ add artifact source identifiers
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 483 at r2](https://reviewable.io/reviews/harness/harness-core/37077#-NAyWbsnDlhHxMwqTeTQ:-NBBs0q52JImWMlDqlLZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c0a45bdfbae2c4f5130c3394cf956f19b823f2cb/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L483)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

null check for ```sources``` field
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37077)* status: :shipit: complete! ✓

**Pull request merged**
