### PR TITLE
[fix]: [PIE-5797]: Process any unprocessed graph events even when the plan status is final but fetch by ExecutionDetail API

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38749)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38749)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/orchestrationEventLog/OrchestrationEventLogRepositoryCustomImpl.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/38749#-NEF5atAArQlzp3XEWRY:-NEF5atAArQlzp3XEWRZ:b-7mc7tp) ([raw file](https://github.com/harness/harness-core/blob/fb97652a2ead0dc4afc74a5a917b57aee807ec18/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/orchestrationEventLog/OrchestrationEventLogRepositoryCustomImpl.java#L47)):*
> ```Java
>     Criteria criteria = Criteria.where(OrchestrationEventLogKeys.planExecutionId).is(planExecutionId);
>     criteria.andOperator(Criteria.where(OrchestrationEventLogKeys.createdAt).gt(lastUpdatedAt));
>     Query query = new Query(criteria).with(Sort.by(Sort.Order.asc("createdAt")));
> ```

Do we need sorting?



_Code quote:_
```Java
Query query = new Query(criteria).with(Sort.by(Sort.Order.asc("createdAt")));
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38749)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/orchestrationEventLog/OrchestrationEventLogRepositoryCustomImpl.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/38749#-NEF5atAArQlzp3XEWRY:-NEF8jKICytMffPTjIyY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fb97652a2ead0dc4afc74a5a917b57aee807ec18/pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/orchestrationEventLog/OrchestrationEventLogRepositoryCustomImpl.java#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Do we need sorting?
</blockquote></details>

done

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38749)* status: :shipit: complete! ✓

**Pull request merged**
