### PR TITLE
feat: [IDP-1434]: IDP Stage - stage and step plan creator

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54602)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/54602#-NiGShle0roW4OePTy85:-NiGShle0roW4OePTy86:b-6wkja3) ([raw file](https://github.com/harness/harness-core/blob/a1699c48af4da19bef99d2485f8a4724f875b07d/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L116)):*
> ```Java
>             getIntegrationStageNode(stageNode), childNodeId, buildStatusUpdateParameter, ctx));
>     planCreationResponseMap.put(
>         specPlanNode.getUuid(), PlanCreationResponse.builder().node(specPlanNode.getUuid(), specPlanNode).build());
> ```

@archit-harness here we are creating the planNodes for the children nodes as well and the plan-creator will return more than one plan-node finally. Shall we add dependencies of the children instead of creating the planNodes directly here?

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPSpecStep.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/54602#-NiGT1e62puk4-eX3V3h:-NiGT1e62puk4-eX3V3i:b-bjij01) ([raw file](https://github.com/harness/harness-core/blob/a1699c48af4da19bef99d2485f8a4724f875b07d/idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPSpecStep.java#L29)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.IDP)
> public class IDPSpecStep implements ChildExecutable<IntegrationStageStepParametersPMS> {
> ```

This step is not needed. Its doing anything special why not use the NGSpecStep?  CI also written this separately i don't know why. @archit-harness any idea? And we should use the common steps if not doing anything extra right?

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54602)* status: Some of the checks are too old. 7 file(s) to review. 0 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54602)* status: Some of the checks are too old. 7 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/54602#-NiGShle0roW4OePTy85:-NiUUhW-56fTOb3nGAt7:b-2ex621) ([raw file](https://github.com/harness/harness-core/blob/a1699c48af4da19bef99d2485f8a4724f875b07d/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L116)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness here we are creating the planNodes for the children nodes as well and the plan-creator will return more than one plan-node finally. Shall we add dependencies of the children instead of creating the planNodes directly here?
</blockquote></details>

yes, we should follow that pattern only
___
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPSpecStep.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/54602#-NiGT1e62puk4-eX3V3h:-NiUUp10Cv98q03lEyAZ:bcysnk0) ([raw file](https://github.com/harness/harness-core/blob/a1699c48af4da19bef99d2485f8a4724f875b07d/idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPSpecStep.java#L29)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

This step is not needed. Its doing anything special why not use the NGSpecStep?  CI also written this separately i don't know why. @archit-harness any idea? And we should use the common steps if not doing anything extra right?
</blockquote></details>

for ci one we can check, if not required lets not introduce a new one just for idp at least, here i can see IntegrationStageStepParametersPMS, but not sure why it would be needed, lets not use until we are sure

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/54602#-NiGShle0roW4OePTy85:-NiZ4STS7wlYK26zV0IP:b8juhpc) ([raw file](https://github.com/harness/harness-core/blob/a1699c48af4da19bef99d2485f8a4724f875b07d/idp-service/src/main/java/io/harness/idp/pipeline/stages/plancreator/IDPStagePlanCreator.java#L116)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

yes, we should follow that pattern only
</blockquote></details>

Resolving this comment for now. will discuss with @archit-harness on this tomorrow that how to tackle this in a proper way. And then we can do whatever is decided.

**Comment by brijeshdhakar** [comment]
*[`idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPSpecStep.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/54602#-NiGT1e62puk4-eX3V3h:-Ni__VOtA_Fy_AbXagm5:b78c0wf) ([raw file](https://github.com/harness/harness-core/blob/a1699c48af4da19bef99d2485f8a4724f875b07d/idp-service/src/main/java/io/harness/idp/pipeline/stages/step/IDPSpecStep.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

for ci one we can check, if not required lets not introduce a new one just for idp at least, here i can see IntegrationStageStepParametersPMS, but not sure why it would be needed, lets not use until we are sure
</blockquote></details>

IDP is not using common spec step only. I checked that only childNodeid is being used from the IntegrationStageStepParametersPMS as well. So IDP is using common one only. No changes in ci.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54602)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
