### PR TITLE
feat: [SSCA-42]: Add beans for ssca orchestration step

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes

This PR adds SscaOrchestrationStep beans to CI-manager. I have created separate module inside CI-manager to have most of the SSCA code in one place.

Orchestration Step YAML:
```
step:
  type: SscaOrchestration
  name: SSCA SBOM Orchestration
  identifier: SscaOrchestration
  spec:
  	tool: Syft
  	format: spdx-json
        source:
    	    type: image
            spec:
    	       connector: someConnector
    	       image: library/nginx@digest-sha
        attestation:
            privateKey: key
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44110)

### CODE REVIEW

**Review by williamwissemann — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44110)* status: Waiting on team(s): sto.

**Review by deepharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44110)* status: :shipit: complete! ✓

___
*[`332-ci-manager/contracts/src/main/java/io/harness/ssca/beans/source/SbomSourceSpec.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/44110#-NOlkqp3ExaKmVcLfDVn:-NOlkqp3ExaKmVcLfDVo:buhu80c) ([raw file](https://github.com/harness/harness-core/blob/06345f9bd4c7a32381559d5339cb2006bc91d876/332-ci-manager/contracts/src/main/java/io/harness/ssca/beans/source/SbomSourceSpec.java#L13)):*
> ```Java
> 
> @JsonSubTypes({ @JsonSubTypes.Type(value = ImageSbomSource.class, name = SbomSourceConstants.IMAGE) })
> public interface SbomSourceSpec {}
> ```

Why we need this?

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44110)* status: 1. unresolved discussions. 

___
*[`332-ci-manager/contracts/src/main/java/io/harness/ssca/beans/source/SbomSourceSpec.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/44110#-NOlkqp3ExaKmVcLfDVn:-NOlnDnMAgHoa2KXxGUO:bc5uef6) ([raw file](https://github.com/harness/harness-core/blob/06345f9bd4c7a32381559d5339cb2006bc91d876/332-ci-manager/contracts/src/main/java/io/harness/ssca/beans/source/SbomSourceSpec.java#L13)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Why we need this?
</blockquote></details>

In future, sbom source would oneOf image, repository, artifact, etc. So, created an interface and would have separate implementations for when source is image or repo or artifact, etc. With this, our yaml schema won't be polluted with having all the unnecessary fields.

**Review by deepharness — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44110)* status: :shipit: complete! ✓

**Comment by inderschera** [comment]
trigger messagecheck

**Pull request merged**
