### PR TITLE
feat: [PIE-8824]: Delete ResourceRestraintInstance with Pipeline Scope when a pipeline execution is deleted

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Delete ResourceRestraintInstance with Pipeline Scope when a pipeline execution is deleted

**Testing:** Deleted a pipeline with queue step while it is running and then verified in DB that its corresponding resource restraint instance is deleted.
 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44882)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44882)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserver.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/44882#-NQ07URD77L4Y4xmlDsX:-NQ07URD77L4Y4xmlDsY:b-piak4z) ([raw file](https://github.com/harness/harness-core/blob/29f2c0af1002bdb2e459ac523976d22964490d75/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserver.java#L20)):*
> ```Java
> import java.util.stream.Collectors;
> 
> public class PipelineResourceRestraintInstanceDeleteObserver implements PlanExecutionDeleteObserver {
> ```

annotation for singleton and team name
___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserverTest.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/44882#-NQ07llo4KezqQJjA3nk:-NQ07llo4KezqQJjA3nl:b-idn37b) ([raw file](https://github.com/harness/harness-core/blob/29f2c0af1002bdb2e459ac523976d22964490d75/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserverTest.java#L29)):*
> ```Java
> import org.mockito.MockitoAnnotations;
> 
> public class PipelineResourceRestraintInstanceDeleteObserverTest extends CategoryTest {
> ```

team name

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44882)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserver.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/44882#-NQ07URD77L4Y4xmlDsX:-NQ09NMc7KpwBEaPu1Iz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29f2c0af1002bdb2e459ac523976d22964490d75/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserver.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

annotation for singleton and team name
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserverTest.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/44882#-NQ07llo4KezqQJjA3nk:-NQ09Nle5SZ_vda78Wko:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29f2c0af1002bdb2e459ac523976d22964490d75/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/event/PipelineResourceRestraintInstanceDeleteObserverTest.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

team name
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44882)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44882)* status: :shipit: complete! ✓

**Pull request merged**
