### PR TITLE
fix: [CDS-38837]: GCP shell

### PR DESCRIPTION
**Pull request by BogdanAtHarness**
## Describe your changes

To log in successfully to GCP in the shell script step (by kubectl) we need to persist the GCP JSON key file to a location on the disk, and supply the appropriate environment variable. This was done in K8s steps but not in the shell script step.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/ShellScriptParameters.java` line 186 at r1](https://reviewable.io/reviews/harness/harness-core/34557#-N59RkhY4ad7d6Ua7lqa:-N59RkhY4ad7d6Ua7lqb:bfz020l) ([raw file](https://github.com/harness/harness-core/blob/dab471a02300a0a18492875dcfeb8caf3d687382/930-delegate-tasks/src/main/java/software/wings/beans/delegation/ShellScriptParameters.java#L186)):*
> ```Java
>     String serviceAccountKeyFileContent = null;
>     if (isGcpDeployment(containerServiceParams)) {
>       GcpConfig gcpConfig=(GcpConfig) containerServiceParams.getSettingAttribute().getValue();
> ```

missing spacing before and after = 
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/ShellScriptParameters.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/34557#-N59O0ox2FL7_XO_TRic:-N59O0ox2FL7_XO_TRid:b-cdfnws) ([raw file](https://github.com/harness/harness-core/blob/dab471a02300a0a18492875dcfeb8caf3d687382/930-delegate-tasks/src/main/java/software/wings/beans/delegation/ShellScriptParameters.java#L189)):*
> ```Java
>       List<EncryptedDataDetail>encryptionDetails = containerServiceParams.getEncryptionDetails();
>       encryptionService.decrypt(gcpConfig, encryptionDetails,false);
>       serviceAccountKeyFileContent = new String(gcpConfig.getServiceAccountKeyFileContent());
> ```

What if instead of service account key file we're using inherit from delegate option? (workload identity)
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/34557#-N59RvwdBrDmaWHvPpUP:-N59RvwdBrDmaWHvPpUQ:bmjc09l) ([raw file](https://github.com/harness/harness-core/blob/dab471a02300a0a18492875dcfeb8caf3d687382/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L115)):*
> ```Java
> 
>       Path gcpKeyFile = null;
>       if (!isEmpty(config.getGcpKeyFileContent())) {
> ```

nit: isNotEmpty is more readable

**Comment by BogdanAtHarness** [comment]
trigger messagecheck

**Review by BogdanAtHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/beans/delegation/ShellScriptParameters.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/34557#-N59O0ox2FL7_XO_TRic:-N59iQvz0mVWULys1Tjx:b-phji8l) ([raw file](https://github.com/harness/harness-core/blob/dab471a02300a0a18492875dcfeb8caf3d687382/930-delegate-tasks/src/main/java/software/wings/beans/delegation/ShellScriptParameters.java#L189)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

@bogdanatharness in such a case, would `gcpConfig.getServiceAccountKeyFileContent()` return `null`..?
if so, we should it gracefully here.
</blockquote></details>

Correct! Removing conversion to string to avoid possible NPE

**Review by BogdanAtHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)* status: 3 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 115 at r2](https://reviewable.io/reviews/harness/harness-core/34557#-N59a6CGD91ezvlkCEj6:-N59rLdHCX2g7mwQ_6pz:b-sf0rg1) ([raw file](https://github.com/harness/harness-core/blob/c724727702103db116351e95fa166107e5b4e086/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L115)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

why are we not using `File` here, similar to what is used for `kubeConfigFile`
</blockquote></details>

In order to use guava methods for writing content to file. More clear, concise, less moving parts. What does the current approach give us?
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/34557#-N59__2c98Uv6XZBTvfN:-N59s9U78Wy5zhQE5ufj:bwtoiat) ([raw file](https://github.com/harness/harness-core/blob/c724727702103db116351e95fa166107e5b4e086/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L119)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

shouldn't we be using `.toAbsolutePath()` here..?
</blockquote></details>

In practice, it's the same, since Files.createTempFile will return a Path object created with an absolute URI. But you are correct, as a rule of thumb, we should always use toAbsolutePath, since the underlying implementation could change.

Changing
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/34557#-N59_nwCD6ECgdTHc_b2:-N59tLoj7Qsy3K7XxlWU:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c724727702103db116351e95fa166107e5b4e086/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L251)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

can we extract out this code piece to another method, which returns the created gcpKeyFile
</blockquote></details>

Done

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)* status: 1 change requests. 2. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34557)* status: :shipit: complete! ✓

**Pull request merged**
