### PR TITLE
fix: [PL-29699]: is_stable fix when not sent

### PR DESCRIPTION
**Pull request by TarunUba1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39950)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/39950#-NGXCJD674A2MgtyO-5o:-NGXCJD674A2MgtyO-5p:b-jxbk9p) ([raw file](https://github.com/harness/harness-core/blob/60c0105c50788ea3b85ac1c2e35c4359375d202d/840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java#L43)):*
> ```Java
>     String templateYaml = templateCreateRequestBody.getTemplateYaml();
>     Boolean check = Objects.isNull(templateCreateRequestBody.isIsStable());
>     Boolean isStable;
> ```

why is this not directly used in the if condition? Any usage of this variable?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/39950#-NGXCuPJ2uIVB6-8pZfI:-NGXCuPJ2uIVB6-8pZfJ:b90jrf8) ([raw file](https://github.com/harness/harness-core/blob/60c0105c50788ea3b85ac1c2e35c4359375d202d/840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java#L45)):*
> ```Java
>     Boolean isStable;
>     if (check) {
>       isStable = false;
> ```

isStable = false can be declared on the top itself and then we can just put an if condition on templatereqbody.isStable and set its value accordingly.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/39950#-NGXDIvu4hQLFEQ_6yOg:-NGXDIvu4hQLFEQ_6yOh:b-gxq8ui) ([raw file](https://github.com/harness/harness-core/blob/60c0105c50788ea3b85ac1c2e35c4359375d202d/840-template-service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java#L41)):*
> ```Java
>     GitCreateDetails gitCreateDetails = templateCreateRequestBody.getGitDetails();
>     String templateYaml = templateCreateRequestBody.getTemplateYaml();
>     Boolean check = Objects.isNull(templateCreateRequestBody.isIsStable());
> ```

I see this exact code being used in all 3 impls. Is it possible to put it inside some helper? Even the request object is exactly same

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39950)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/39950#-NGXCJD674A2MgtyO-5o:-NGXEHqn9VOB5fc5QDTR:bmq3fcd) ([raw file](https://github.com/harness/harness-core/blob/60c0105c50788ea3b85ac1c2e35c4359375d202d/840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this not directly used in the if condition? Any usage of this variable?
</blockquote></details>

yeah isStable is then used in return otherwise was throwing nullpointer
___
*[`840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/39950#-NGXCuPJ2uIVB6-8pZfI:-NGXJE_l5Q8nUaeMXaWc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60c0105c50788ea3b85ac1c2e35c4359375d202d/840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

isStable = false can be declared on the top itself and then we can just put an if condition on templatereqbody.isStable and set its value accordingly.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/39950#-NGXDIvu4hQLFEQ_6yOg:-NGXJCPt9UdFk_JLUJwf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60c0105c50788ea3b85ac1c2e35c4359375d202d/840-template-service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see this exact code being used in all 3 impls. Is it possible to put it inside some helper? Even the request object is exactly same
</blockquote></details>

Done.

**Comment by TarunUba1** [comment]
trigger compile codeformat messagecheck recency buildnum checkstyle pmd featurenamecheck ti0 ti1 ti2 codebasehash

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 301 at r2](https://reviewable.io/reviews/harness/harness-core/39950#-NGXaC5hCbO2m4owqJZC:-NGXaC5i0lJ1Dnstgc2Z:b6483uu) ([raw file](https://github.com/harness/harness-core/blob/003c9716d5c5a5b2921ea22460c289e3868dab17/840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L301)):*
> ```Java
> 
>   public Boolean checkIsStable(Boolean stable) {
>     Boolean check = Objects.isNull(stable);
> ```

instead of all this, you can simply write : "return Boolean.TRUE.equals(stable);" In that case, I guess you won't even need any utils. Just try it out.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39950)* status: 4 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
