### PR TITLE
[fix]: [CDS-69578]: Error message improvement for nested chained pipelines

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Describe your changes
Error message improvement in case of nested chained pipelines. 
Screenshot 2023-05-31 at 4 48 01 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)

### CODE REVIEW

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWlmIi1EZBFXSJdISRU:-NWlmIi212eRD_9bqgQu:bkf50pj) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L103)):*
> ```Java
>       validateNestedChainedPipeline(pipelineEntity);
>     } catch (Exception e) {
>       log.error("Error during nested chaining validation ", e);
> ```

if we are throwing exception we dont need to log



_Code quote:_
```Java
log.error("Error during nested chaining validation ", e);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWlmN2_9zMAZ8rmA6JE:-NWlmN2_9zMAZ8rmA6JF:btv7vm) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L105)):*
> ```Java
>       log.error("Error during nested chaining validation ", e);
>       throw NestedExceptionUtils.hintWithExplanationException(
>           String.format(hint, parentPipelineIdentifier), String.format(error, pipelineEntity.getIdentifier()), null);
> ```

Add sshot of error exp in UI
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWllzJ8C3ZtgvJBVjRC:-NWllzJ8C3ZtgvJBVjRD:bn9tiz) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L136)):*
> ```Java
> 
>       String parentPipelineIdentifier =
>           yamlField.getNode().getCurrJsonNode().get("pipeline").get("identifier").textValue();
> ```

why do you need this?
@prashantsharma04 can you help share better way to get parentPipelineId



_Code quote:_
```Java
      YamlField yamlField = null;
      try {
        yamlField = YamlUtils.readTree(ctx.getYaml());
      } catch (IOException e) {
        e.printStackTrace();
      }

      String parentPipelineIdentifier =
          yamlField.getNode().getCurrJsonNode().get("pipeline").get("identifier").textValue();
```

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWlmIi1EZBFXSJdISRU:-NWm2rT64Epw-rbLFtPy:b-f6k6cd) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L103)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if we are throwing exception we dont need to log
</blockquote></details>

Here, its essential to log the exception otherwise it will be lost. I don't see it getting passed anywhere else.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWm34jy9BEesPMO0Hcx:-NWm34jy9BEesPMO0Hcy:big7tv7) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L98)):*
> ```Java
>     String hint = "Unable to run pipeline [%s]";
>     String error =
>         "The referred pipeline [%s] invokes a child pipeline, so it cannot be included within another pipeline. Nested Pipeline Chaining is not supported. ";
> ```

any other good place where we can keep all such hints and explanations?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWm3CIm-DHKxOM8pw6v:-NWm3CIm-DHKxOM8pw6w:b-7ugnmi) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L132)):*
> ```Java
>         yamlField = YamlUtils.readTree(ctx.getYaml());
>       } catch (IOException e) {
>         e.printStackTrace();
> ```

any particular reason to not log.error(e) but e.printStackTrace()?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWm3It7AGcIg7SMySVN:-NWm3It7AGcIg7SMySVO:b-7ilvfu) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L137)):*
> ```Java
>       String parentPipelineIdentifier =
>           yamlField.getNode().getCurrJsonNode().get("pipeline").get("identifier").textValue();
>       ;
> ```

typo?

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger ut7

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger ut2

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWlmIi1EZBFXSJdISRU:-NX9ALtO5-eweQjzIrkw:bubbvcc) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L103)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here, its essential to log the exception otherwise it will be lost. I don't see it getting passed anywhere else.
</blockquote></details>

As its a user exception thus we don't need to log, as the nested method validateNestedChainedPipeline already has log for it.
Reference - https://harness.atlassian.net/wiki/spaces/~380461285/pages/21242708047/Good+logging+practices#Error-vs-Warning
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWlmN2_9zMAZ8rmA6JE:-NX9AfVkDsZXnjqQ5GJr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add sshot of error exp in UI
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWm3CIm-DHKxOM8pw6v:-NX9AhYQ6SjC2jiW0f8y:b-s47wkt) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L132)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

any particular reason to not log.error(e) but e.printStackTrace()?
</blockquote></details>

@vtxorxwitty print stack should never be the case, we should throw the exception with InternalServerException
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/48593#-NX9B6aDBX3nBp3svQVa:-NX9B6aDBX3nBp3svQVb:bdziqjp) ([raw file](https://github.com/harness/harness-core/blob/0edd6b8b121eb63cc77f5362bff6b91a7ff50515/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java#L105)):*
> ```Java
>     if (ambiance.getMetadata().getPipelineStageInfo().getHasParentPipeline()) {
>       throw new InvalidRequestException(
>           "The referring pipeline has a parent pipeline. Nested Pipeline Chaining is not supported.");
> ```

This error message should be same including Hints and Explanation

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWm3CIm-DHKxOM8pw6v:-NX9X48M-CvjvSz5HWnD:bbi6fdk) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L132)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@vtxorxwitty print stack should never be the case, we should throw the exception with InternalServerException
</blockquote></details>

We have removed this method after @prashantsharma04 suggested a better method to fetch parent pipeline identifier.

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWm3CIm-DHKxOM8pw6v:-NXA7RR-EfhuFt2gxUA1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L132)):*
<details><summary><i>Previously, vtxorxwitty (Ved Tambat) wrote…</i></summary><blockquote>

We have removed this method after @prashantsharma04 suggested a better method to fetch parent pipeline identifier.
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/48593#-NX9B6aDBX3nBp3svQVa:-NXA7PMLAZ7OnyWL8Jb4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0edd6b8b121eb63cc77f5362bff6b91a7ff50515/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This error message should be same including Hints and Explanation
</blockquote></details>

done

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/48593#-NWlmIi1EZBFXSJdISRU:-NXA8Dv83OanZogkgrKp:b-y106k1) ([raw file](https://github.com/harness/harness-core/blob/f12d682a1f6e799c153a85890d4658b4ec6f53fc/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L103)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

As its a user exception thus we don't need to log, as the nested method validateNestedChainedPipeline already has log for it.
Reference - https://harness.atlassian.net/wiki/spaces/~380461285/pages/21242708047/Good+logging+practices#Error-vs-Warning
</blockquote></details>

I don't see any such thing happening in the internal method. Also, its resolving templates which can fail giving some genuine error.


Also, if we are doing everything on the internal method, why do we even catch it here. Let it pass through the exception.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 2 of 5 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 1 change requests. 1. unresolved discussions.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 99 at r9](https://reviewable.io/reviews/harness/harness-core/48593#-NXAWGEh6RhgnlVXPrEm:-NXAWGEh6RhgnlVXPrEn:b-y7dvwi) ([raw file](https://github.com/harness/harness-core/blob/25cc9bec710bce7c3fa60780b9cb1fcc12facd22/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L99)):*
> ```Java
>       validateNestedChainedPipeline(pipelineEntity);
>     } catch (Exception e) {
>       throw NestedExceptionUtils.hintWithExplanationException(
> ```

Create a new exception and pass it here rather than passing it as null.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java` line 111 at r9](https://reviewable.io/reviews/harness/harness-core/48593#-NXAWcKj64nVQHzqlnHW:-NXAWcKj64nVQHzqlnHX:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/25cc9bec710bce7c3fa60780b9cb1fcc12facd22/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java#L111)):*
> ```Java
>       throw NestedExceptionUtils.hintWithExplanationException(
>           String.format(NESTED_CHAINING_HINT, ambiance.getMetadata().getPipelineStageInfo().getIdentifier()),
>           String.format(NESTED_CHAINING_ERROR, ambiance.getMetadata().getPipelineIdentifier()), null);
> ```

Same as above

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 1 change requests. 1. unresolved discussions.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 102 at r13](https://reviewable.io/reviews/harness/harness-core/48593#-NXEFyNACQ2Wr0pNVhFv:-NXEFyNACQ2Wr0pNVhFw:bar9e4w) ([raw file](https://github.com/harness/harness-core/blob/2a4d6e84742ba36bb5eb5f5f6617baf22a1a9f1f/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L102)):*
> ```Java
>       throw NestedExceptionUtils.hintWithExplanationException(
>           String.format(NESTED_CHAINING_HINT, parentPipelineIdentifier),
>           String.format(NESTED_CHAINING_ERROR, pipelineEntity.getIdentifier()));
> ```

Are we not passing it to hintWithExplanationException

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 5 files at r4, 3 of 4 files at r5, 1 of 1 files at r7, 1 of 1 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 5 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48593)* status: 2. unresolved discussions.

**Comment by vtxorxwitty** [comment]
trigger review

**Pull request merged**
