### PR TITLE
[techdebt]: [PIE-4184]: Make OpaClientFactory extend AbstractHttpClientFactory

### PR DESCRIPTION
**Pull request by namanvermah**
OpaClientFactory used a SafeOk Http client. AbstractHttpClientFactory provided support for UnsafeOk only. In order to make OpaClientFactory extend AbstractHttpClientFactory, this PR moves the functionality to generate a SafeOk Http client from OpaClientFactory to AbstractHttpClientFactory

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34959)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34959)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by r0610205 — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34959)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34959)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 7 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34959)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 3 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34959)* status: :shipit: complete! ✓

**Pull request merged**
