### PR TITLE
feat:[CDS-49782]: moved filtering logic to steps in case of Gitops

### PR DESCRIPTION
**Pull request by vaibhav-si**
## Describe your changes

In Gitops flow, we had to move filtering logic to the steps as Multi Spawner is not called when multiple env/infras.

Testing scenarios - 

For Gitops service - 

- Filters on Env Group
- Filters on Environments in Env Group
- Filters on Environments
- Filters on Individual Env in Envs.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42389)

### CODE REVIEW

**Review by rohitk-h — APPROVED** [review]
> Reviewed 10 of 17 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42389)* status: 23 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 699 at r2](https://reviewable.io/reviews/harness/harness-core/42389#-NLNJ9fgAdrqh5RTBUOe:-NLNJ9fh1KwQVMjlS5cz:bow8lnt) ([raw file](https://github.com/harness/harness-core/blob/ad6a48beaa4ff76e2f9745045fedc70cfaa9a154/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L699)):*
> ```Java
>   }
> 
>   public List<NGTag> getNGTags(Map<String, String> tags) {
> ```

nit: this and above function should be moved to commons package. eg. `TagUtils`
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 833 at r2](https://reviewable.io/reviews/harness/harness-core/42389#-NLNIjuz4E0S6_iL4614:-NLNIjuz4E0S6_iL4615:b68p9zj) ([raw file](https://github.com/harness/harness-core/blob/ad6a48beaa4ff76e2f9745045fedc70cfaa9a154/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L833)):*
> ```Java
> 
>     if (isEmpty(clsRefs)) {
>       throw new InvalidRequestException("No clusters found");
> ```

suggestion: We should enhance these messages to help identify which filtering was applied and qualification of entity failed.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42389)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 17 files at r1, 10 of 13 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42389)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42389)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 6 of 17 files at r1, 10 of 13 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42389)* status: :shipit: complete! ✓

**Pull request merged**
