### PR TITLE
feat: [PIE-4175]: Add fields to response of execution info endpoint

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
Added fields startTs, pipelineName, account, org and project to endpoint /pipeline/api/resource-constraints/executionInfo.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34590)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34590)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/34590#-N5KDmuh2UnkaAd0vvPn:-N5KDmuh2UnkaAd0vvPo:b2ijwts) ([raw file](https://github.com/harness/harness-core/blob/29683f6dcadaf493a9a6e3d5c405a766c97488e0/800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L72)):*
> ```Java
>     // WE NEED TO KEEP THE RELATION BETWEEN releaseEntityId AND planExecutionId TO USE
>     // AFTER GET ALL CURRENT EXECUTIONS
>     Map<String, String> rrInstanceMap = instances.stream().collect(
> ```

nit, call it rrIntanceToPlanExecutionidMap
___
*[`800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/34590#-N5KG3d906C7r8xg856P:-N5KG3dA3ubtxPir3Y2f:b-6nk2g7) ([raw file](https://github.com/harness/harness-core/blob/29683f6dcadaf493a9a6e3d5c405a766c97488e0/800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L94)):*
> ```Java
>     if (isScopeStage(instance)) {
>       try {
>         NodeExecution nodeExecution = nodeExecutionService.get(instance.getReleaseEntityId());
> ```

nit, we can make a batch call to fetch all nodeExecutions at once. We can put a todo or handle seperately

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34590)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34590)* status: 1. unresolved discussions. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 94 at r1](https://reviewable.io/reviews/harness/harness-core/34590#-N5KG3d906C7r8xg856P:-N5Kj0pDCbcd47SROK22:b32v57) ([raw file](https://github.com/harness/harness-core/blob/29683f6dcadaf493a9a6e3d5c405a766c97488e0/800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L94)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, we can make a batch call to fetch all nodeExecutions at once. We can put a todo or handle seperately
</blockquote></details>

+1
___
*[`800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/34590#-N5KjCyy16R85JZ13AZI:-N5KjCyy16R85JZ13AZJ:b-dkqic0) ([raw file](https://github.com/harness/harness-core/blob/29683f6dcadaf493a9a6e3d5c405a766c97488e0/800-pipeline-service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L144)):*
> ```Java
>             k
>             -> pipelineService.get(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier, false)
>                    .orElseGet(() -> PipelineEntity.builder().build()))
> ```

nit: if pipeline doesnt exist we want to return empty?

**Comment by Fernando-Dourado** [comment]
trigger recency

**Pull request merged**
