### PR TITLE
[fix]: [CDS-44812]: add yaml schema validation for remote templates

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

Earlier get call for remote templates didn't used to do yaml validation.
Now we have added Yaml Schema validation as well validation on fields so that they should not be changed on remote (accountid, orgid,projectid,identifier and name)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40748)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/40748#-NHzH5mm7P32e5z4kZzR:-NHzH5mm7P32e5z4kZzS:bjip45x) ([raw file](https://github.com/harness/harness-core/blob/840e35eaa12299ccd01b30fa03b88fdde6da36cb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L410)):*
> ```Java
>                          templateEntity.getVersionLabel()),
>                     e);
>               throw new InvalidRequestException(String.format("Error while saving template [%s] of versionLabel [%s]",
> ```

is this an expected change ?

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 431 at r1](https://reviewable.io/reviews/harness/harness-core/40748#-NHzHzhj-l9Sh4fSlILV:-NHzHzhj-l9Sh4fSlILW:blfvsc8) ([raw file](https://github.com/harness/harness-core/blob/840e35eaa12299ccd01b30fa03b88fdde6da36cb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L431)):*
> ```Java
>         if (isNotBlank(templateEntity.getYaml())) {
>           applyTemplatesToYamlAndValidateSchema(templateEntity);
>           templateGitXService.performImportFlowYamlValidations(templateEntity.getOrgIdentifier(),
> ```

can we 
- add 1 more method performImportFlowYamlValidation that takes in templateVersion and templateName
- not use templateImportRequestDTO here
- performImportFlowYamlValidation(..templateImportRequestDTO.. ) should just call the new method we create

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 431 at r1](https://reviewable.io/reviews/harness/harness-core/40748#-NHzHzhj-l9Sh4fSlILV:-NHzIWZtBNIEgRTmrrlc:b-9suew3) ([raw file](https://github.com/harness/harness-core/blob/840e35eaa12299ccd01b30fa03b88fdde6da36cb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L431)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we 
- add 1 more method performImportFlowYamlValidation that takes in templateVersion and templateName
- not use templateImportRequestDTO here
- performImportFlowYamlValidation(..templateImportRequestDTO.. ) should just call the new method we create
</blockquote></details>

then we can also rename the `performImportFlowYamlValidation` to something like `performBasicValidationForRemoteTemplates` ?

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 638 at r1](https://reviewable.io/reviews/harness/harness-core/40748#-NHzJ92X11X1nM4PrUx9:-NHzJ92X11X1nM4PrUxA:b-m7gogy) ([raw file](https://github.com/harness/harness-core/blob/840e35eaa12299ccd01b30fa03b88fdde6da36cb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L638)):*
> ```Java
>     }
> 
>     templateEntities.get()
> ```

I think in case of LIST call, we do not fetch yamls for remote templates, could you please check ?
If that is the case, we need not do validations

**Comment by tchaurasiya** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/40748#-NHzH5mm7P32e5z4kZzR:-NI0ls3t3MQGxTfftxlY:b-w5968a) ([raw file](https://github.com/harness/harness-core/blob/840e35eaa12299ccd01b30fa03b88fdde6da36cb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L410)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this an expected change ?
</blockquote></details>

No.Removed.

**Comment by tchaurasiya** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 638 at r1](https://reviewable.io/reviews/harness/harness-core/40748#-NHzJ92X11X1nM4PrUx9:-NI0lvZb5BIKhWXs8N8v:b-i0jm1) ([raw file](https://github.com/harness/harness-core/blob/840e35eaa12299ccd01b30fa03b88fdde6da36cb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L638)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think in case of LIST call, we do not fetch yamls for remote templates, could you please check ?
If that is the case, we need not do validations 
</blockquote></details>

List call do send the yaml. Anyways we have isNotBlank(entity.getYaml()) in filter.
For listing on templates page, we call diffferent "list-metadata" api.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40748)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40748)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40748)* status: 5 file(s) to review.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40748)* status: :shipit: complete! ✓

**Pull request merged**
