### PR TITLE
feat: [CDS-50122]: Stage yaml should be validated that it should have one of service, services or serviceConfig

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
have one of service, services or serviceConfig

Added oneOfField for service, services & serviceConfig in DeploymentStageConfig

example error msg - 
On line number 12, Only one of service or services must be present.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42915)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger ti3

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/42915#-NMSXG3KCELe6Maguv1g:-NMSXG3KCELe6Maguv1h:b-o7brsp) ([raw file](https://github.com/harness/harness-core/blob/f3d20753f5c957064e3031783a6e9ed7fac48a45/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L63)):*
> ```Java
>   String uuid;
> 
>   ServiceConfig serviceConfig;
> ```

in v1 setups, serviceConfig is present.



_Code quote:_
```Java
serviceConfig
```

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42915)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42915)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/42915#-NMUQ7zZ0C6ascg5kB3a:-NMUQ7z_1U7ZSeK4YOP3:b-yg7hnt) (no related file):*
Can we see if we can these checks in DeploymentStageFilterCreatorV2, if yes, we should remove them in a separate PR

___

**Pull request merged**
