### PR TITLE
feat: [CDS-42717]: FreezeEvaluation apis

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38486)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 13 Issues 
* Code issue 6 Code issues 
* Anti-pattern 7 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38486)

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38486)* status: :shipit: complete! ✓

___
*[`125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeEvaluateServiceImpl.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/38486#-NDmXLf62dBkjQx07D4s:-NDmXLf62dBkjQx07D4t:bwv84z6) ([raw file](https://github.com/harness/harness-core/blob/3e1f06d89f0b1824fb18ecfa56dc7f7cea14f150/125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeEvaluateServiceImpl.java#L53)):*
> ```Java
>         accountId, orgIdentifier, projectIdentifier, null, FreezeType.MANUAL, FreezeStatus.ENABLED, null, null);
>     PageRequest pageRequest =
>         PageRequest.of(0, 100, Sort.by(Sort.Direction.DESC, FreezeConfigEntity.FreezeConfigEntityKeys.createdAt));
> ```

nit: Would 100 be enough ?

**Comment by abhinavmittal-harness** [comment]
trigger messagecheck

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38486#-:-NDyWFvAA8bFGYJPMUo0:bnfp4nl)* status: 2 file(s) to review.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38486#-:-NDyWUjA7gYRuAXlOEjw:bnfp4nl)* status: 2 file(s) to review.

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38486)* status: 2 file(s) to review.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38486)* status: 2 file(s) to review.

**Pull request closed without merging**
