### PR TITLE
[feat]:[PIE-5550]: Adding dequeue , ack and unack request and implementation

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes
Adding implementation for dequeue , ack and unack in hsqs harness core repo
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38452)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/handler/handler.go` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgm6qc6nh9ZMOGEt3r:-NDgm6qc6nh9ZMOGEt3s:b-9rn051) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/handler/handler.go#L66)):*
> ```Go
> 	return func(c echo.Context) error {
> 
> 		// bind request body to enqueue request
> ```

dequeue



_Code quote:_
```Go
enqueue
```
___
*[`queue-service/hsqs/handler/handler.go` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgmDgsAKHg8r1sPTBC:-NDgmDgsAKHg8r1sPTBD:b2ni24g) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/handler/handler.go#L100)):*
> ```Go
> 		ack, err := h.s.Ack(c.Request().Context(), *p)
> 		if err != nil {
> 			return c.JSON(http.StatusBadRequest, nil)
> ```

err
___
*[`queue-service/hsqs/handler/handler.go` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgmCXa1fkbeEWLRwMz:-NDgmCXa1fkbeEWLRwN-:b2ni24g) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/handler/handler.go#L125)):*
> ```Go
> 		unAck, err := h.s.UnAck(c.Request().Context(), *p)
> 		if err != nil {
> 			return c.JSON(http.StatusBadRequest, nil)
> ```

err
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgmXq64lp2JoULJ2vb:-NDgmXq64lp2JoULJ2vc:b-l3nyoa) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/store/redis/redis_store.go#L62)):*
> ```Go
> 	_, err = s.client.SAdd(ctx, allSubTopicsKey, request.SubTopic).Result()
> 	if err != nil {
> 		return &store.EnqueueResponse{}, err
> ```

can return nil



_Code quote:_
```Go
&store.EnqueueResponse{}
```
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgmoaW6YcUq6UfatRU:-NDgmoaW6YcUq6UfatRV:b3ze2he) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/store/redis/redis_store.go#L104)):*
> ```Go
> 	selectedTopic := subtopics[index]
> 	s.logger.Debug().Msgf("selected subTopic is %s", selectedTopic)
> 	return s.ReadFromStream(ctx, utils.GetSubTopicStreamQueueKey(request.Topic, selectedTopic), request.BatchSize, request.Topic, request.ConsumerName)
> ```

shouldnt we use this GetConsumerGroupKeyForGivenTopic for given topic to create ConsumergroupName
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 325 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgu7MM6qfXOkIpz313:-NDgu7MM6qfXOkIpz314:b-s6q70b) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/store/redis/redis_store.go#L325)):*
> ```Go
> }
> 
> // helper method to map x message to response
> ```

comments are wrong?



_Code quote:_
```Go
/ helper method to map x message to response
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`queue-service/hsqs/handler/handler.go` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgm6qc6nh9ZMOGEt3r:-NDh6T7-5BOBelXAIoaC:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/handler/handler.go#L66)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

handled in rev
</blockquote></details>

done
___
*[`queue-service/hsqs/store/redis/redis_store.go` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgmoaW6YcUq6UfatRU:-NDh6Xkj94yi_6sYcEYC:bfodb0x) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/store/redis/redis_store.go#L104)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

Shouldn't we keep the consumer names assigned to calling servers. Consumer name will become too long in that case imo
</blockquote></details>

discussed to be fxed in another thread

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`queue-service/hsqs/hsqs` line 0 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgtipo7vXNxVfvnImk:-NDgtipo7vXNxVfvnIml:bdrlrg) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/hsqs#L0)):*
remove this binary

**Review by hextechpal — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`queue-service/hsqs/hsqs` line  at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgtipo7vXNxVfvnImk:-NDmRokHAkWV-sm0ELBd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/hsqs#L)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

remove this binary
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: 1. unresolved discussions.

**Comment by ankittiwari-harness** [comment]
*[`queue-service/hsqs/store/redis/redis_store.go` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/38452#-NDgmXq64lp2JoULJ2vb:-NDnSk7x8fD5yQ3Czgtp:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/e17d34f310c7b571d8ff6758a96d5fe2e77b8593/queue-service/hsqs/store/redis/redis_store.go#L62)):*
<details><summary><i>Previously, ankittiwari-harness (Ankit Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38452)* status: :shipit: complete! ✓

**Pull request merged**
