### PR TITLE
feat: [IDP-1266]: Jira Data Source Support

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Describe your changes

**Data Points**

1. Mean time to resolve (in hours)
2. Issues count
3. Issues Open/Close ratio

**Default Checks**

1. Mean time to resolve P0/P1 bugs in last 90 days is less than 2 days
2. Number of open P0/P1 bugs is less than 5
3. Features delivered in last 90 days is more than 5
4. P0/P1 bugs Open/Close ratio is less than 3 (last 90 days)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53524)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 15 of 20 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53524)* status: 20 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/DataPointParser.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/53524#-NfVMwkZ1QHZeb0YJENE:-NfVMwkZ1QHZeb0YJENF:b-j7oqyc) ([raw file](https://github.com/harness/harness-core/blob/0e315f04f1559c37f6569e050d386cb51717f26d/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/DataPointParser.java#L35)):*
> ```Java
>     } else if (inputValue.startsWith("\"")) {
>       inputValue = inputValue.replaceFirst("\"", "");
>       inputValue = inputValue.replace("\\", "");
> ```

If we have \\ , we'll end up with \
Just wanted to confirm if that is intended.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/JiraResolutionTimeParser.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/53524#-NfVPJOa5uY4YO237TeA:-NfVPJOa5uY4YO237TeB:b7nr200) ([raw file](https://github.com/harness/harness-core/blob/0e315f04f1559c37f6569e050d386cb51717f26d/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/JiraResolutionTimeParser.java#L47)):*
> ```Java
>         Map<String, Object> fields = (Map<String, Object>) issue.get("fields");
>         long createdAtMillis = DateUtils.parseTimestamp((String) fields.get("created"), DATE_FORMAT);
>         long resolvedAtMillis = DateUtils.parseTimestamp((String) fields.get("resolutiondate"), DATE_FORMAT);
> ```

Does this API return only closed/resolved issues? Otherwise we might not have resolutiondate



_Code quote:_
```Java
resolvedAtMillis
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/JiraIssuesOpenCloseRatioDsl.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/53524#-NfVRHs98fhUz8EgroyD:-NfVRHs98fhUz8EgroyE:b-818x9k) ([raw file](https://github.com/harness/harness-core/blob/0e315f04f1559c37f6569e050d386cb51717f26d/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/JiraIssuesOpenCloseRatioDsl.java#L48)):*
> ```Java
>   DslClientFactory dslClientFactory;
>   @Override
>   public Map<String, Object> fetchData(String accountIdentifier, BackstageCatalogEntity backstageCatalogEntity,
> ```

Let's connect sometime next week and see if we can make this common code and parameterize it. Similar code is needed in many DSLs. cc: @sathish-soundarapandian 



_Code quote:_
```Java
fetchData
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53524)* status: 22 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/DataPointParser.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/53524#-NfVMwkZ1QHZeb0YJENE:-NfVeMCD3XBMtAXCpflA:b-z9tkyn) ([raw file](https://github.com/harness/harness-core/blob/0e315f04f1559c37f6569e050d386cb51717f26d/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/DataPointParser.java#L35)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

If we have \\ , we'll end up with \
Just wanted to confirm if that is intended.
</blockquote></details>

Yes, its not needed. I was doing some test in local and forgot to remove it
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/JiraResolutionTimeParser.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/53524#-NfVPJOa5uY4YO237TeA:-NfVeU9Z59PCe9oBMxZY:b-9krbag) ([raw file](https://github.com/harness/harness-core/blob/0e315f04f1559c37f6569e050d386cb51717f26d/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/JiraResolutionTimeParser.java#L47)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Does this API return only closed/resolved issues? Otherwise we might not have resolutiondate
</blockquote></details>

Default checks will return only resolved issue. But if user doesnt enter 'resolved' in the JQL then we will get NPE. I have added a guardrail for the same

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53524)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Review by devesh-harness — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger ut0, ut8

**Pull request merged**
