### PR TITLE
fix: [DEL-3126]: Remove CDN based url(s) from yaml/sh files if useCDN flag is false

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31217)

### CODE REVIEW

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31217)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/31217#-MxdEBrC45TazHBIXUdT:-MxdEBrC45TazHBIXUdU:bluqdzk) ([raw file](https://github.com/harness/harness-core/blob/b4ff2f25eb45a8d7de0f3602c4d4c41f54937c99/400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl#L17)):*
> ```FreeMarker
>           value: ""
>         - name: USE_CDN
>           value: ${useCdn}
> ```

shouldnt this be hidden behind the flag.

<#if useCdn == "true">



_Code quote:_
```FreeMarker
        - name: USE_CDN
          value: ${useCdn}
        - name: CDN_URL
          value: "${cdnUrl}"
```

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31217)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/31217#-MxdEBrC45TazHBIXUdT:-MxhL7Q02JkDdK33h6fy:bygewsa) ([raw file](https://github.com/harness/harness-core/blob/b4ff2f25eb45a8d7de0f3602c4d4c41f54937c99/400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl#L17)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

shouldnt this be hidden behind the flag.

<#if useCdn == "true">
</blockquote></details>

We are will not publish values to cdnUrl in DelegateServiceImpl.java, so empty values will get populated.

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1286 at r1](https://reviewable.io/reviews/harness/harness-core/31217#-Mxogy5sERD-zUhVY_eu:-Mxogy5sERD-zUhVY_ev:b349xcw) ([raw file](https://github.com/harness/harness-core/blob/b4ff2f25eb45a8d7de0f3602c4d4c41f54937c99/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1286)):*
> ```Java
> 
>       params.put("useCdn", String.valueOf(useCDN));
>       if (useCDN) {
> ```

we should just control it in th eftl itself rather than having to add empty urls

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31217)* status: Some of the checks are too old. 4 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/31217#-MxdEBrC45TazHBIXUdT:-MyL9lBsAOvwsesHH8Xd:bzglxzq) ([raw file](https://github.com/harness/harness-core/blob/b4ff2f25eb45a8d7de0f3602c4d4c41f54937c99/400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl#L17)):*
>  will not publish values to cdnUrl in De
We could have done that too, I choose to populate these fields with empty string, to avoid changing at multiple script files. Since there are other empty fields as well in the yaml, can't we go with this approach ?

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31217)* status: Some of the checks are too old. 4 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 1286 at r1](https://reviewable.io/reviews/harness/harness-core/31217#-Mxogy5sERD-zUhVY_eu:-MyLAM1w3PdWg_auT-K3:b70twvw) ([raw file](https://github.com/harness/harness-core/blob/b4ff2f25eb45a8d7de0f3602c4d4c41f54937c99/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1286)):*
> ould just control it in th eftl itself rather than having to add empty urls
Please refer to my earlier reply, if you feel we should do changes in etfl, I'll take that up.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31217)* status: Some of the checks are too old.

**Review by arpit3107 — APPROVED** [review]
I see raghu and abhinav has already approved it. So approving it directly

> Reviewed 1 of 4 files at r1, 3 of 20 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31217#-:-MzPd_ic2IOTyAscavV3:bdbaeil)* status: :shipit: complete! ✓

**Pull request merged**
