### PR TITLE
[fix]: [DEL-4291]: remove feature flag for delegate jdk11

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34327)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34327)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 982 at r2](https://reviewable.io/reviews/harness/harness-core/34327#-N4asmXX2gHxhoiF3DXa:-N4asmXY32tcJiTlGevG:b7tinad) ([raw file](https://github.com/harness/harness-core/blob/ecfd1329d871431a8377e2c8a65a3d83d0c8b3c1/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L982)):*
> ```Java
>       throw new InvalidRequestException("Deleted AccountId: " + accountId);
>     }
>     if (featureFlagService.isEnabled(DELEGATE_VERSION_FROM_RING, accountId)) {
> ```

Maybe we can just enable this for all, we used it number of times in prod without issues, I think it's stable
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 1563 at r2](https://reviewable.io/reviews/harness/harness-core/34327#-N4arXYz76Ob-dnrDpQA:-N4arXYz76Ob-dnrDpQB:bw5i8xh) ([raw file](https://github.com/harness/harness-core/blob/d49ae12724ddfec5f4c5a6aaa6317621689c87dd/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L1563)):*
> ```Java
>    */
>   private JreConfig getJreConfig(final String accountId, final boolean isWatcher) {
>     final boolean enabled = isWatcher && isJdk11Watcher(accountId);
> ```

The condition here needs to be as below. You need JDK11 enabled if it's delegate or JDK11 watcher



_Code snippet:_
```Java
!isWatcher || isJdk11Watcher(accountId)
```

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
trigger ti1

**Review by mdmilic — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34327)* status: 16 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 15 of 18 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34327)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34327)* status: :shipit: complete! ✓

**Pull request merged**
