### PR TITLE
[feat]: [CDS-68135]: Rollback only those strategy stages that were run

### PR DESCRIPTION
**Pull request by namanvermah**
Stage node execution Ids used to create PostExecutionRollbackInfo can be used for Pipeline Rollback as well. We'll add the stage ids that were run in the og execution
Screenshot 2023-04-27 at 3 10 31 PM
Screenshot 2023-04-27 at 3 07 17 PM
Screenshot 2023-04-27 at 3 04 31 PM

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47052)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
