### PR TITLE
feat: [CDS-43263]: Map Http Helm connector

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37881)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37881)

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Review by GoelPratyush99 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37881)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/HttpHelmConnectorImpl.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/37881#-NCt_zq4CK1n50n8GZXD:-NCt_zq58Lzrg-en7qmq:b-lyrts8) ([raw file](https://github.com/harness/harness-core/blob/d163003213e005055213b39093aceb7ea595b114/100-migrator/src/main/java/io/harness/ngmigration/connector/HttpHelmConnectorImpl.java#L52)):*
> ```Java
>     authBuilder.authType(HttpHelmAuthType.ANONYMOUS);
>     String username = config.getUsername();
>     String secretId = this.getSecretId(settingAttribute);
> ```

Shouldn't we check for password here instead of secretId?



_Code quote:_
```Java
    String secretId = this.getSecretId(settingAttribute);
    if (isNotEmpty(username) && isNotEmpty(secretId)) {
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37881)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/HttpHelmConnectorImpl.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/37881#-NCt_zq4CK1n50n8GZXD:-NCubzfl9dntpWYQTQjw:blwefik) ([raw file](https://github.com/harness/harness-core/blob/d163003213e005055213b39093aceb7ea595b114/100-migrator/src/main/java/io/harness/ngmigration/connector/HttpHelmConnectorImpl.java#L52)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Shouldn't we check for password here instead of secretId?
</blockquote></details>

I have rebased the latest develop. We would have to check secretId now I guess.

**Review by GoelPratyush99 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37881#-:-NCuuMJ56YngE0OLicZY:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
