### PR TITLE
[feat]: [CDS-69739]: Updated status code when delegates are down

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have made the following enhancements in this pr:
1. Updated the status code to 500 instead of 400 when the delegates are down. 
2. Changed the default delegate task timeout from 2 mins to 30 seconds for all task except for getBatchFile delegate task.

Have tested out the above code enhancements.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW2ZdQA7nvz90wC13O3:-NW2ZdQA7nvz90wC13O4:bj4i7zq) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java#L15)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ScmDelegateTimeOutException extends ScmException {
> ```

Does this have to kryoSerializable?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1052 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW2emA67EJ5L5nPVMYo:-NW2emA67EJ5L5nPVMYp:b-cshgui) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1052)):*
> ```Java
>     } catch (DelegateServiceDriverException ex) {
>       log.error("Error occurred while executing delegate task.", ex);
>       throw new ScmDelegateTimeOutException(String.format(
> ```

why is it called timeout exception?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1052 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW2emA67EJ5L5nPVMYo:-NW2epqM8QZZDqS8Ix80:bh987ru) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1052)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it called timeout exception?
</blockquote></details>

Also, as we discussed, we don't want to change anything related to old git sync. We need to create similar method and use it in all our new gitx tasks.

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW364FuDfMwxYTdk8Lz:-NW364FuDfMwxYTdk8M-:b-x369br) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java#L15)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ScmDelegateTimeOutException extends ScmException {
> ```

Timeout word is a bit misleading.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)* status: 2 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1052 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW2emA67EJ5L5nPVMYo:-NW6Qta64AhGMQ4CNk08:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1052)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also, as we discussed, we don't want to change anything related to old git sync. We need to create similar method and use it in all our new gitx tasks.
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW364FuDfMwxYTdk8Lz:-NW5qrzX3SByutlNt6QK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java#L15)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Timeout word is a bit misleading.
</blockquote></details>

Done.
___
*[`952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/48174#-NW2ZdQA7nvz90wC13O3:-NW6BGHpBta4JvO55ci_:bv1xb1l) ([raw file](https://github.com/harness/harness-core/blob/1d347c7a7e6eb9c5c85fb5bd998c5f9510ea0860/952-scm-java-client/src/main/java/io/harness/exception/ScmDelegateTimeOutException.java#L15)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Does this have to kryoSerializable?
</blockquote></details>

we wouldnt be needing the kryo serialisation as we are just throwing an exception and not transferring an object

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1073 at r2](https://reviewable.io/reviews/harness/harness-core/48174#-NW6RHkDBmv2Via2HAyH:-NW6RHkDBmv2Via2HAyI:bz0c6jr) ([raw file](https://github.com/harness/harness-core/blob/3fb55974dd74dff40fc1f851dbc7f0ae31c3f108/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1073)):*
> ```Java
>     } catch (DelegateServiceDriverException ex) {
>       log.error("Error occurred while executing delegate task.", ex);
>       throw new ScmDelegateException(String.format(
> ```

why did we remove hints etc?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1004 at r2](https://reviewable.io/reviews/harness/harness-core/48174#-NW6ROtG-HqFx50gGkgF:-NW6ROtG-HqFx50gGkgG:b-l27f1v) ([raw file](https://github.com/harness/harness-core/blob/3fb55974dd74dff40fc1f851dbc7f0ae31c3f108/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1004)):*
> ```Java
> 
>   private DelegateTaskRequest getDelegateTaskRequest(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, TaskParameters taskParameters, TaskType taskType, long timeoutInMinutes) {
> ```

variable name should be "timeoutInSeconds"

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1012 at r2](https://reviewable.io/reviews/harness/harness-core/48174#-NW6RVJF-YGmK18Tlq5z:-NW6RVJF-YGmK18Tlq6-:bwdekh5) ([raw file](https://github.com/harness/harness-core/blob/3fb55974dd74dff40fc1f851dbc7f0ae31c3f108/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1012)):*
> ```Java
>         .taskParameters(taskParameters)
>         .taskType(taskType.name())
>         .executionTimeout(Duration.ofSeconds(timeoutInMinutes))
> ```

we have changed field from considering argument from minutes to seconds but no change in the users of this method, its a clear breaking change.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)* status: 2 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1004 at r2](https://reviewable.io/reviews/harness/harness-core/48174#-NW6ROtG-HqFx50gGkgF:-NW6V3NqB6UtLOIIeII-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3fb55974dd74dff40fc1f851dbc7f0ae31c3f108/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1004)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

variable name should be "timeoutInSeconds"
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1012 at r2](https://reviewable.io/reviews/harness/harness-core/48174#-NW6RVJF-YGmK18Tlq5z:-NW6VQ0oBo-iwX52VzOk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3fb55974dd74dff40fc1f851dbc7f0ae31c3f108/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1012)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we have changed field from considering argument from minutes to seconds but no change in the users of this method, its a clear breaking change.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1073 at r2](https://reviewable.io/reviews/harness/harness-core/48174#-NW6RHkDBmv2Via2HAyH:-NW6a3CZ7VXIXne9SxKH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3fb55974dd74dff40fc1f851dbc7f0ae31c3f108/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1073)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why did we remove hints etc?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48174)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
