### PR TITLE
feat: [CDS-47538]: Upgrade sshd-core library version to 2.9.2

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

Upgradation of sshd-core library to 2.9.2 version. Code changes were required because of following files ->

FileSystemAwareProcessShellFactory 
K8sTaskHelperSecondaryTest 
FileSystemAwareInvertedShellWrapper 
FileSystemAwareProcessShell  
SshRule 

All test cases are fixed , except the two which will be fixed by ssh team later. Those have been marked as ignored. Ssh team will fix them later because of some urgent CFD. As discussed with ssh team, for sanity , unit tests should pass and ssh pipeline should run fine.

Screenshot 2022-12-09 at 10 29 29 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41067)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger ti2

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 14 files at r3, 3 of 7 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41067#-:-NIr-0H94liVg8kgkxg5:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`260-delegate/BUILD.bazel` line 541 at r6](https://reviewable.io/reviews/harness/harness-core/41067#-NJ3drdV3a3Qsf_DwsZ-:-NJ3drdV3a3Qsf_DwsZ0:b-d9s74u) ([raw file](https://github.com/harness/harness-core/blob/ba2e1bf9568a9cd53fe7aeed221b409b21cdb3a4/260-delegate/BUILD.bazel#L541)):*
> ```Starlark
>         "@maven//:org_apache_neethi_neethi",
>         "@maven//:org_apache_santuario_xmlsec",
>         "@maven//:org_apache_sshd_sshd_common",
> ```

are these new addition to delegate dependency? how were things working before without these in delegate?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 7 of 14 files at r3, 3 of 7 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41067)* status: 1 of 2 approvals obtained.

**Comment by piyush-bhuwalka** [comment]
*[`260-delegate/BUILD.bazel` line 541 at r6](https://reviewable.io/reviews/harness/harness-core/41067#-NJ3drdV3a3Qsf_DwsZ-:-NJ3evNW6OSUgcjbYSs8:b9aph2o) ([raw file](https://github.com/harness/harness-core/blob/ba2e1bf9568a9cd53fe7aeed221b409b21cdb3a4/260-delegate/BUILD.bazel#L541)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

are these new addition to delegate dependency? how were things working before without these in delegate?
</blockquote></details>

There is a  version upgradation for the sshd-core library, as you can check in the WORKSPACE file. And there was a change of functionality due to which we need this new dependencies. As these changes are done by Ivan, I had a discussion with him. So these changes are only for the PR checks that are happening for us. Should not affect the customer in any way

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 14 files at r3, 3 of 7 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41067)* status: 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-bhuwalka** [comment]
trigger smartchecks

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41067#-:-NJ4zIzN0NfT-yvXmYe5:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41067)* status: :shipit: complete! ✓

**Pull request merged**
