### PR TITLE
[feat]: [CDS-85436]: Connector functor to resolve connectors expressions in V1

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Change: Writing a remote-functor for Connectors to resolve its expressions. We convert ConnectorInfoDTO into the map in the functor and return it.

Testing: Tested that the expressions like `<+connector.conn_id.spec.url>` resolve correctly with the help of this functor.

Impact: No impact as we are adding a new functor. No changes in existing.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56536)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56536)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/56536#-NlNgQEK2pFdIJbwYlmj:-NlNgQEK2pFdIJbwYlmk:b-2cc6vt) ([raw file](https://github.com/harness/harness-core/blob/4c655c8f10cb9bfa6fa90506d18bedc24577b860/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java#L28)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> @Slf4j
> ```

add codepulse annotation
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/56536#-NlNhJAu9R8ZYRP33Arm:-NlNhJAv8xEFfk3yhCA-:b-wtbdma) ([raw file](https://github.com/harness/harness-core/blob/4c655c8f10cb9bfa6fa90506d18bedc24577b860/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java#L41)):*
> ```Java
>       return Collections.emptyMap();
>     }
>     return JsonUtils.asMap(JsonUtils.asJson(optional.get().getConnector()));
> ```

instead of 2 serialisation, you can use objectMapper.convertValue to convert directly to map, if method doesn't exist, add one



_Code quote:_
```Java
JsonUtils.asMap(JsonUtils.asJson(
```

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56536)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/56536#-NlNgQEK2pFdIJbwYlmj:-NlSVJV_36AENTOCHcPN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c655c8f10cb9bfa6fa90506d18bedc24577b860/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add codepulse annotation
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/56536#-NlNhJAu9R8ZYRP33Arm:-NlSWkaaAZ_W1IdUgCWT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c655c8f10cb9bfa6fa90506d18bedc24577b860/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/ConnectorFunctor.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead of 2 serialisation, you can use objectMapper.convertValue to convert directly to map, if method doesn't exist, add one
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56536)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ut7 ut8

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
