### PR TITLE
fix:[PL-27859]: throw exception from delegate svc

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38479)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38479)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38479)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/serializer/PipelineServiceModuleRegistrars.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/38479#-NDkvBjl9YmiMYKVGLRs:-NDkvBjl9YmiMYKVGLRt:bt3mjao) ([raw file](https://github.com/harness/harness-core/blob/79dd17fd2b0894b8bfd7df4971e69f220fb603ba/pipeline-service/service/src/main/java/io/harness/serializer/PipelineServiceModuleRegistrars.java#L42)):*
> ```Java
>           .addAll(NGTriggerRegistrars.kryoRegistrars)
>           .add(NotificationBeansKryoRegistrar.class)
>           .add(DelegateServiceContractsKryoRegistrar.class)
> ```

Dont add it to Pipeline service module, add it to orchestration sub module package

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38479)* status: 23 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/BUILD.bazel` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/38479#-NDwRhqPB1RVljoJkpu9:-NDwRhqPB1RVljoJkpuA:bwe79xr) ([raw file](https://github.com/harness/harness-core/blob/0c991c4fccbd4fb300d86836d3ea692cae75c097/pipeline-service/modules/orchestration-steps/BUILD.bazel#L19)):*
> ```Starlark
>         "//878-ng-common-utilities:module",
>         "//880-pipeline-cd-commons:module",
>         "//925-delegate-service-contracts:module",
> ```

@abhinav-harness i meant to add in this file OrchestrationRegistrars as already we were dependent upon 930 delegate task registars
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/38479#-NDwRoVn2tTVvhpTp6dU:-NDwRoVn2tTVvhpTp6dV:b-kn1n4k) ([raw file](https://github.com/harness/harness-core/blob/0c991c4fccbd4fb300d86836d3ea692cae75c097/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L86)):*
> ```Java
>           .addAll(DelegateTaskRegistrars.kryoRegistrars)
>           .addAll(NGCommonModuleRegistrars.kryoRegistrars)
>           .addAll(DelegateServiceContractsRegistrars.kryoRegistrars)
> ```

it should be in OrchestrationRegistrars
___
*[`pipeline-service/service/src/main/java/io/harness/serializer/PipelineServiceModuleRegistrars.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/38479#-NDkvBjl9YmiMYKVGLRs:-NDwRCVQ0untzX4yOyIv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/79dd17fd2b0894b8bfd7df4971e69f220fb603ba/pipeline-service/service/src/main/java/io/harness/serializer/PipelineServiceModuleRegistrars.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Dont add it to Pipeline service module, add it to orchestration sub module package
</blockquote></details>

done

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38479)* status: 28 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/BUILD.bazel` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/38479#-NDwRhqPB1RVljoJkpu9:-NE-v_7m-CWcLgPsmaqI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c991c4fccbd4fb300d86836d3ea692cae75c097/pipeline-service/modules/orchestration-steps/BUILD.bazel#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@abhinav-harness i meant to add in this file OrchestrationRegistrars as already we were dependent upon 930 delegate task registars
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/38479#-NDwRoVn2tTVvhpTp6dU:-NE-vahQ9v9Z1lcW5YA2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c991c4fccbd4fb300d86836d3ea692cae75c097/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L86)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be in OrchestrationRegistrars
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38479)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
