### PR TITLE
[feat]: [PIE-8037]: Added New FailureStrategyAction "MARK_AS_FAILURE"

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/43663#-NNjsaSG7PRn23DObXNa:-NNjsaSG7PRn23DObXNb:bry3s08) ([raw file](https://github.com/harness/harness-core/blob/c03638609610d16a6b045a8f25a158d3523e156f/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L35)):*
> ```Java
>   MARK_SUCCESS,
>   PROCEED_WITH_DEFAULT,
>   MARK_FAILURE
> ```

should it be "MARK_AS_FAILURE"? Just checking

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/MarkFailureAdviseHandler.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43663#-NNjsnWq6Evy4LKHHWIk:-NNjsnWq6Evy4LKHHWIl:b-dj2eb5) ([raw file](https://github.com/harness/harness-core/blob/c03638609610d16a6b045a8f25a158d3523e156f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/MarkFailureAdviseHandler.java#L27)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class MarkFailureAdviseHandler implements AdviserResponseHandler {
> ```

Is it MarkAsFailure or MarkFailure? Just checking if we can keep convention same as everywhere.

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 26 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/43663#-NNjsaSG7PRn23DObXNa:-NNtkmdz8ZMUowS7PeHt:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c03638609610d16a6b045a8f25a158d3523e156f/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should it be "MARK_AS_FAILURE"? Just checking
</blockquote></details>

+1
___
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43663#-NNtkgmo8jE6cCXmFSrp:-NNtkgmo8jE6cCXmFSrq:b-snxdwa) ([raw file](https://github.com/harness/harness-core/blob/5f4d962f3f732f7df494b3173e42516b0f2e36d3/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L34)):*
> ```Java
> 
>   MARK_SUCCESS,
>   PROCEED_WITH_DEFAULT,
> ```

; is missing

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 30 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/NGFailureActionType.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuKXg17ldU8hFqojdO:-NNuKXg27UGKS2knBFv7:bpjtxd0) ([raw file](https://github.com/harness/harness-core/blob/012e361c73c2d90fa6fac5f92417064da0c84790/953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/NGFailureActionType.java#L36)):*
> ```Java
>   @JsonProperty(NGFailureActionTypeConstants.MARK_AS_FAILURE)
>   MARK_AS_FAILURE(NGFailureActionTypeConstants.MARK_AS_FAILURE),
>   ;
> ```

correct this extra ;
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/NodeStatusUpdateHandlerFactory.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuKriL03dA5pyPebVQ:-NNuKriL03dA5pyPebVR:b-6nq5xz) ([raw file](https://github.com/harness/harness-core/blob/46ae98270d42bb73633d1238e8e06e7211fff961/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/NodeStatusUpdateHandlerFactory.java#L32)):*
> ```Java
>   @Inject WaitStepStatusUpdate waitStepStatusUpdate;
>   @Inject QueuedLicenseLimitReachedStatusUpdate queuedLicenseLimitReachedStatusUpdate;
> ```

revert this file change
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuKzeX6oE47oB68Wqo:-NNuKzeX6oE47oB68Wqp:bhokkmn) ([raw file](https://github.com/harness/harness-core/blob/46ae98270d42bb73633d1238e8e06e7211fff961/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java#L60)):*
> ```Java
>   @JsonIgnore APPROVAL_WAITING(Status.APPROVAL_WAITING, true),
>   @JsonIgnore APPROVAL_REJECTED(Status.APPROVAL_REJECTED, true),
>   @JsonIgnore WAITING(Status.RESOURCE_WAITING, "Waiting", true);
> ```

revert these changes
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 394 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuL1BA8A0ydb3t6mlJ:-NNuL1BA8A0ydb3t6mlK:b-pmr6cj) ([raw file](https://github.com/harness/harness-core/blob/012e361c73c2d90fa6fac5f92417064da0c84790/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L394)):*
> ```Java
> 
>     registerCorrelationFilter(environment, injector);
>     // registerNotificationTemplates(injector);
> ```

uncomment this

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 32 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/markFailure/MarkAsFailure_FailureActionConfig.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/43663#-NO3dXxtDzJEtjagwnyj:-NO3dXxtDzJEtjagwnyk:b-vgz9vq) ([raw file](https://github.com/harness/harness-core/blob/b57269cb7460dd84e8da684572880c0435845847/953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/markFailure/MarkAsFailure_FailureActionConfig.java#L26)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @RecasterAlias("io.harness.yaml.core.failurestrategy.markFailure.MarkAsFailure_FailureActionConfig")
> public class MarkAsFailure_FailureActionConfig implements FailureStrategyActionConfig {
> ```

Refactor this file name to MarkAsFailFailureActionConfig

**Review by archit-harness — COMMENTED** [review]
As discussed - a) Interrupts are occuring twice, advisterType is coming as unknown in interrupt, plus we should introduce new advise so that its easy to debug

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663#-:-NO8T9Cp73sJujQ777BM:b-l0xv6n)* status: 32 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 32 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/43663#-NNjsaSG7PRn23DObXNa:-NO8Kqo5AywlIfsuU0eV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c03638609610d16a6b045a8f25a158d3523e156f/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L35)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/NGFailureActionType.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuKXg17ldU8hFqojdO:-NO8KrmD1aBi012s5xIF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/012e361c73c2d90fa6fac5f92417064da0c84790/953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/NGFailureActionType.java#L36)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

correct this extra ;
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/NodeStatusUpdateHandlerFactory.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuKriL03dA5pyPebVQ:-NO8L2NdAO50KGpO4Kti:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/46ae98270d42bb73633d1238e8e06e7211fff961/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate/NodeStatusUpdateHandlerFactory.java#L32)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

revert this file change
</blockquote></details>

Done.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 34 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/43663#-NNtkgmo8jE6cCXmFSrp:-NOAvR6n-LZWEU3qOaBo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f4d962f3f732f7df494b3173e42516b0f2e36d3/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L34)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

; is missing 
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 394 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuL1BA8A0ydb3t6mlJ:-NOAwqrd-bHjHxNLKSJK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/012e361c73c2d90fa6fac5f92417064da0c84790/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L394)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

uncomment this
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/MarkFailureAdviseHandler.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/43663#-NNjsnWq6Evy4LKHHWIk:-NOAx-7R82LZdSrLZwYm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c03638609610d16a6b045a8f25a158d3523e156f/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/MarkFailureAdviseHandler.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is it MarkAsFailure or MarkFailure? Just checking if we can keep convention same as everywhere.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/43663#-NNuKzeX6oE47oB68Wqo:-NOAx0b245mlJ6KR08cn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/46ae98270d42bb73633d1238e8e06e7211fff961/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution/ExecutionStatus.java#L60)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

revert these changes
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/markFailure/MarkAsFailure_FailureActionConfig.java` line 26 at r7](https://reviewable.io/reviews/harness/harness-core/43663#-NO3dXxtDzJEtjagwnyj:-NOAvVZyCoSe3-DXEQ2n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b57269cb7460dd84e8da684572880c0435845847/953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/markFailure/MarkAsFailure_FailureActionConfig.java#L26)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Refactor this file name to MarkAsFailFailureActionConfig
</blockquote></details>

Done.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 8 of 16 files at r1, 1 of 11 files at r2, 6 of 11 files at r3, 3 of 5 files at r4, 2 of 4 files at r5, 1 of 3 files at r6, 2 of 3 files at r7, 10 of 10 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 34 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 51 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarksuccess/OnMarkSuccessAdviserTest.java` line 97 at r12](https://reviewable.io/reviews/harness/harness-core/43663#-NODZiP--eMvCJGsUFQC:-NODZiP0-JIRGgSlERbR:b-roxt2q) ([raw file](https://github.com/harness/harness-core/blob/09ed11c21f989326b6bf7b588f03cf8b3eef7bc3/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarksuccess/OnMarkSuccessAdviserTest.java#L97)):*
> ```Java
> 
>   @Test
>   @Owner(developers = VIVEK_DIXIT)
> ```

why owner name has been changed?
___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java` line 47 at r12](https://reviewable.io/reviews/harness/harness-core/43663#-NOD_7GF12MIMeVq0Vz4:-NOD_7GF12MIMeVq0Vz5:b8my8d) ([raw file](https://github.com/harness/harness-core/blob/09ed11c21f989326b6bf7b588f03cf8b3eef7bc3/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java#L47)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class MarkAsFailureAdviseHandlerTest extends OrchestrationTestBase {
> ```

can we use category test here?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 51 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java` line 47 at r12](https://reviewable.io/reviews/harness/harness-core/43663#-NOD_7GF12MIMeVq0Vz4:-NODeF1j1QeX7JmFGqFr:bl9oyer) ([raw file](https://github.com/harness/harness-core/blob/09ed11c21f989326b6bf7b588f03cf8b3eef7bc3/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java#L47)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

can we use category test here?
</blockquote></details>

I orchestration Engine is used in the test, i believe we would require this
___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarksuccess/OnMarkSuccessAdviserTest.java` line 97 at r12](https://reviewable.io/reviews/harness/harness-core/43663#-NODZiP--eMvCJGsUFQC:-NODeOrW9Oga1DYwiCgy:b-5ks20e) ([raw file](https://github.com/harness/harness-core/blob/09ed11c21f989326b6bf7b588f03cf8b3eef7bc3/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarksuccess/OnMarkSuccessAdviserTest.java#L97)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

why owner name has been changed?
</blockquote></details>

reverted, did by mistake

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 8 of 16 files at r1, 1 of 11 files at r2, 6 of 11 files at r3, 3 of 5 files at r4, 2 of 4 files at r5, 1 of 3 files at r6, 2 of 3 files at r7, 7 of 10 files at r9, 1 of 1 files at r10, 10 of 16 files at r11, 2 of 2 files at r12, 1 of 1 files at r14, 7 of 7 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 21 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto.

**Review by prashantsharma04 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663#-:-NODxlDF76H5wqG0QExu:bnfp4nl)* status: 21 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 16 files at r1, 1 of 11 files at r2, 6 of 11 files at r3, 3 of 5 files at r4, 2 of 4 files at r5, 1 of 3 files at r6, 2 of 3 files at r7, 6 of 10 files at r9, 1 of 1 files at r10, 8 of 16 files at r11, 2 of 2 files at r12, 1 of 1 files at r14, 7 of 7 files at r15, 1 of 1 files at r16, 1 of 2 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java` line 47 at r18](https://reviewable.io/reviews/harness/harness-core/43663#-NOE_5SVCDVFYaTXiURa:-NOE_5SVCDVFYaTXiURb:b-289xko) ([raw file](https://github.com/harness/harness-core/blob/9f39d45960a9bd733976ea74dcccfc5e1801a319/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java#L47)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class MarkAsFailureAdviseHandlerTest extends OrchestrationTestBase {
> ```

why do you need this and not categoryTest?
___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarkfailure/OnMarkFailureAdviserTest.java` line 41 at r18](https://reviewable.io/reviews/harness/harness-core/43663#-NOEZyABBrZdra2d_CqX:-NOEZyAC9jDPwglB-fns:banww5) ([raw file](https://github.com/harness/harness-core/blob/9f39d45960a9bd733976ea74dcccfc5e1801a319/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarkfailure/OnMarkFailureAdviserTest.java#L41)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class OnMarkFailureAdviserTest extends PmsSdkCoreTestBase {
> ```

why do you need to inject?
cc: @prashantsharma04

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java` line 47 at r18](https://reviewable.io/reviews/harness/harness-core/43663#-NOE_5SVCDVFYaTXiURa:-NOEsiF63F_pW8dtBddC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f39d45960a9bd733976ea74dcccfc5e1801a319/pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need this and not categoryTest?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarkfailure/OnMarkFailureAdviserTest.java` line 41 at r18](https://reviewable.io/reviews/harness/harness-core/43663#-NOEZyABBrZdra2d_CqX:-NOFZtIJ4e_Sv7ZuALQ8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f39d45960a9bd733976ea74dcccfc5e1801a319/clients/pipeline-service/pms-sdk-core/src/test/java/io/harness/pms/sdk/core/adviser/onmarkfailure/OnMarkFailureAdviserTest.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do you need to inject?
cc: @prashantsharma04 
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by senjucanon2** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 8 of 16 files at r1, 1 of 11 files at r2, 6 of 11 files at r3, 3 of 5 files at r4, 2 of 4 files at r5, 1 of 3 files at r6, 2 of 3 files at r7, 6 of 10 files at r9, 1 of 1 files at r10, 8 of 16 files at r11, 2 of 2 files at r12, 1 of 1 files at r14, 7 of 7 files at r15, 1 of 1 files at r16, 1 of 2 files at r18, 1 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: Waiting on team(s): sto.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r18, 1 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43663)* status: Waiting on team(s): sto.

**Pull request merged**
