### PR TITLE
feat: [PL-27335]: Build files for 120-ng-manager.*accesscontrol.*

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Adding build files for 120-ng-manager/**/ng/accesscontrol . These build files still don't depend on granular targets, but this is a good start to break 120-ng-manager itself.

To create these files, I used the script to generate some build files and then replaced granular targets with top level targets manually.

## Checklist
- [X] I've documented the changes in the PR description.
- [NA] I've tested this change either in PR or local environment.
- [] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36187)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36187)

**Comment by gn-harness** [comment]
trigger ti1, ft1

**Comment by gn-harness** [comment]
trigger ti0, ti2, ti3

**Comment by gn-harness** [comment]
trigger ti0, ti2

**Comment by gn-harness** [comment]
trigger t0

**Comment by gn-harness** [comment]
trigger ti0

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 1 of 8 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36187)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36187#-:-NAdDw5f4I3VCcTJrfwk:bnfp4nl)* status: Some of the checks are too old.

**Comment by gn-harness** [comment]
trigger codebasehash, compile, pmd

**Review by puneetsar — APPROVED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36187)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by hemanthmantri — APPROVED** [review]

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36187)* status: :shipit: complete! ✓

**Pull request merged**
