### PR TITLE
feat: [CDS-76412]: Populate endts while forcefully aborting execution…

### PR DESCRIPTION
**Pull request by Y0709**
… via interruptMoniter

Currently when sometimes an execution is aborted via interrupt monitor the status of the execution is marked corrently but endTs is not updated due to which the execution run time in UI still increases even after the execution is in a final state. here we are fixing that issue. 

Tested this in local by forcibly queuing an execution in local and abort it via interrupt monitor

Screenshot 2023-11-16 at 12 34 27 PM

Screenshot 2023-11-16 at 12 34 49 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
Please add description and testing performed .

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/55302#-NjLufQF6xydJJSfQrYI:-NjLufQF6xydJJSfQrYJ:begjjyl) ([raw file](https://github.com/harness/harness-core/blob/ad66189b6026cfa5af93a81474e8ed239697a3e6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L197)):*
> ```Java
>       Status status = planExecutionService.calculateStatus(interrupt.getPlanExecutionId());
>       PlanExecution planExecution = planExecutionService.updateStatusForceful(interrupt.getPlanExecutionId(), status,
>           ops -> ops.set(PlanExecutionKeys.endTs, System.currentTimeMillis()), true);
> ```

Can we add a UT for the same?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)* status: Some of the checks are too old. 1 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 228 at r1](https://reviewable.io/reviews/harness/harness-core/55302#-NjLuoEt7QgAH7fQCtrI:-NjLuoEu0_HDT1DHpBIu:b4pdg5) ([raw file](https://github.com/harness/harness-core/blob/ad66189b6026cfa5af93a81474e8ed239697a3e6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L228)):*
> ```Java
>     Status status = planExecutionService.calculateStatus(interrupt.getPlanExecutionId());
>     PlanExecution planExecution = planExecutionService.updateStatusForceful(interrupt.getPlanExecutionId(), status,
>         ops -> ops.set(PlanExecutionKeys.endTs, System.currentTimeMillis()), true);
> ```

why not add this ops in updateStatusForceful if status is final?

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)* status: Some of the checks are too old. 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 228 at r1](https://reviewable.io/reviews/harness/harness-core/55302#-NjLuoEt7QgAH7fQCtrI:-NjLwq83CKOBK-6PlGco:b-1mmitl) ([raw file](https://github.com/harness/harness-core/blob/ad66189b6026cfa5af93a81474e8ed239697a3e6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L228)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why not add this ops in updateStatusForceful if status is final?
</blockquote></details>

This method is also used in other places where we are somtimes passing other updateOps as well and sometimes not passing any update ops hence i did not add it there

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/55302#-NjLufQF6xydJJSfQrYI:-NjRN2_P63NiQL63iqZR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad66189b6026cfa5af93a81474e8ed239697a3e6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L197)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a UT for the same?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 228 at r1](https://reviewable.io/reviews/harness/harness-core/55302#-NjLuoEt7QgAH7fQCtrI:-NjRN3cZ1PI6RXCdt3Bq:bek7kv7) ([raw file](https://github.com/harness/harness-core/blob/ad66189b6026cfa5af93a81474e8ed239697a3e6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L228)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

This method is also used in other places where we are somtimes passing other updateOps as well and sometimes not passing any update ops hence i did not add it there
</blockquote></details>

I have made this change

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55302)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger messagecheck, review

**Pull request merged**
