### PR TITLE
fix: [CDS-36932]: Unset infrastructure definitions when environment change

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32726)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Review by srinivaswings — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32726)* status: :shipit: complete! ✓

**Comment by Fernando-Dourado** [comment]
trigger ti4

**Comment by Fernando-Dourado** [comment]
trigger ti1

**Comment by Fernando-Dourado** [comment]
trigger pmd

**Comment by Fernando-Dourado** [comment]
trigger ft1

**Comment by Fernando-Dourado** [comment]
trigger ti2

**Review by srinivaswings — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32726)* status: :shipit: complete! ✓

**Review by srinivaswings — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32726#-:-N1JXO485MFQbKW3teXt:bnfp4nl)* status: :shipit: complete! ✓

**Comment by Fernando-Dourado** [comment]
trigger ti2

**Comment by Fernando-Dourado** [comment]
trigger ti2

**Review by srinivaswings — APPROVED** [review]

**Comment by Fernando-Dourado** [comment]
Wrong rebase, cancel the PR.

**Pull request closed without merging**
