### PR TITLE
techdebt: [PIE-2744]: Changed Redis Consumer for consuming events from redis streams for CD

### PR DESCRIPTION
**Pull request by shalini-agr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java, line 93 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGVEmc5z-v4wRYcytX:-MzGVEmc5z-v4wRYcytY:bumthrd) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L93)):*
> ```Java
>   private void pollAndProcessMessages() {
>     List<Message> messages;
>     String messageId;
> ```

nit: This can be defined in the loop itself.

**Comment by sahilhindwani-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java, line 94 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGVJwB3HAfPJxfQ3ft:-MzGVJwB3HAfPJxfQ3fu:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L94)):*
> ```Java
>     List<Message> messages;
>     String messageId;
>     boolean messageProcessed;
> ```

Same as above

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java, line 179 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGWN4oCqNfgpmBksiH:-MzGWN4p2iT95dyDP73d:bgv8swb) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java#L179)):*
> ```Java
>       } else {
>         return true;
>       }
> ```

do we want to handle empty list and records from exception differently?



_Code quote:_
```Java
    if (records.size() != 0) {
      if (records.get(0) == null) {
        return false;
      } else {
        return true;
      }
```

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGVWbW1ncN2Hp2Cguj:-MzK7oj8DdAcAcB4407R:bek69go) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java#L40)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we log something over here rather than silently returning true? Maybe something like: unknown optype found and log the optype too.
</blockquote></details>

+1 Shalini, we can throw some exception that unknown optype found

**Comment by shalini-agr** [comment]
___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java, line 179 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGWN4oCqNfgpmBksiH:-MzKbvBK7vGXuqyTtm_C:bsb2v1n) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java#L179)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we want to handle empty list and records from exception differently?
</blockquote></details>

removed this.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java, line 94 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGVJwB3HAfPJxfQ3ft:-MzGYoKW0hC6TVMFvxZa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDRedisEventConsumer.java#L94)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/31813#-MzGVWbW1ncN2Hp2Cguj:-MzIxMer7NHt9Yk_6qlY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1fee7a8905fe55438c095dd075e6ae8f84191af4/878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java#L40)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we log something over here rather than silently returning true? Maybe something like: unknown optype found and log the optype too.
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 6 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 3. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: :shipit: complete! ✓

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: :shipit: complete! ✓

___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java, line 171 at r2](https://reviewable.io/reviews/harness/harness-core/31813#-MzOjs7WBYrEpt2rzU-x:-MzOjs7WBYrEpt2rzU-y:b-4uywe2) ([raw file](https://github.com/harness/harness-core/blob/2f5e5bb7f9d7bc9a0db687813cc618e8cb128df6/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java#L171)):*
> ```Java
>     } catch (DataAccessException ex) {
>       log.error("Caught Exception while inserting data", ex);
>       if (ex.toString().contains("Error getting connection from data source")) {
> ```

use ex.getmessage

abstract this logic of checking connection error instead of duplicating

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: :shipit: complete! ✓

___
*[878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java, line 44 at r2](https://reviewable.io/reviews/harness/harness-core/31813#-MzOka9M1wr0mYwT0j9D:-MzOka9M1wr0mYwT0j9E:b29cezk) ([raw file](https://github.com/harness/harness-core/blob/2f5e5bb7f9d7bc9a0db687813cc618e8cb128df6/878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java#L44)):*
> ```Java
>         break;
>     }
>     log.info("Unknown optype found: {}", optype);
> ```

make it error

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java, line 171 at r2](https://reviewable.io/reviews/harness/harness-core/31813#-MzOjs7WBYrEpt2rzU-x:-MzP8uHXAs2vPxojCNKv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f5e5bb7f9d7bc9a0db687813cc618e8cb128df6/120-ng-manager/src/main/java/io/harness/pms/redisConsumer/PipelineExecutionSummaryCDChangeEventHandler.java#L171)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

use ex.getmessage

abstract this logic of checking connection error instead of duplicating
</blockquote></details>

Done.
___
*[878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java, line 44 at r2](https://reviewable.io/reviews/harness/harness-core/31813#-MzOka9M1wr0mYwT0j9D:-MzP93k3DLH12im9_RCG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f5e5bb7f9d7bc9a0db687813cc618e8cb128df6/878-ng-common-utilities/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java#L44)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

make it error
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31813)* status: :shipit: complete! ✓

**Pull request merged**
