### PR TITLE
[fix]: [PIE-3868]: Hiding Pipeline APIs as per Telemetry

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Hiding Pipeline APIs as per Telemetry

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33729)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33729)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/33729#-N3P04rq8E22hTnqBade:-N3P04rq8E22hTnqBadf:b-a1l2rv) ([raw file](https://github.com/harness/harness-core/blob/fec913fb54c4ff4c8a00aeae1f192bbc3f6c7dfb/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L207)):*
> ```Java
>       })
>   @Hidden
>   public ResponseDTO<PlanExecutionResponseDto>
> ```

@vaibhav-si can you re-verify all rerun/retry apis are not used as shown in telemetry. Because I remember 1-2 of them were being used.



_Code quote:_
```Java
public ResponseDTO<PlanExecutionResponseDto>
```

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33729)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 536 at r2](https://reviewable.io/reviews/harness/harness-core/33729#-N3Y7xLR2ea4nQ0tQeMM:-N3Y7xLS5RxsTDG1k_rR:b-rjnk0a) ([raw file](https://github.com/harness/harness-core/blob/888f11d8c1519e2cba71ed07c1437b2d08ac7e4c/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L536)):*
> ```Java
>                 "Fetch Runtime Input Template for a Pipeline, along with any expressions whose value is needed for running specific Stages")
>       })
>   @Hidden
> ```

let's remove hidden for template api as this would be needed

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33729)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/33729#-N3P04rq8E22hTnqBade:-N3Y8kszAqcyHnk__cr1:bevtn5k) ([raw file](https://github.com/harness/harness-core/blob/fec913fb54c4ff4c8a00aeae1f192bbc3f6c7dfb/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L207)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@vaibhav-si can you re-verify all rerun/retry apis are not used as shown in telemetry. Because I remember 1-2 of them were being used.
</blockquote></details>

Verified in past 2 months data, no one is using rerun/retry APIs

**Comment by mankrit-singh** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 536 at r2](https://reviewable.io/reviews/harness/harness-core/33729#-N3Y7xLR2ea4nQ0tQeMM:-N3Y94xn8CecH3fRB8CF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/888f11d8c1519e2cba71ed07c1437b2d08ac7e4c/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L536)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

let's remove hidden for template api as this would be needed
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33729)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33729)* status: :shipit: complete! ✓

**Pull request merged**
