### PR TITLE
feat: [PL-29185]: Adding email filter to User Filter

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
Adding email filter to the [`api`](https://apidocs.harness.io/tag/User#operation/getUsers)
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40184)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40184)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 221 at r1](https://reviewable.io/reviews/harness/harness-core/40184#-NH1BugH63E1_fVZHJzw:-NH1BugICM2Fx_iypAZ8:bws7qcg) ([raw file](https://github.com/harness/harness-core/blob/a53d9d50dd89f06fe6e39a71b09c497e4fe46218/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L221)):*
> ```Java
>       if (userFilter.getIdentifiers() != null) {
>         List<String> userIds = new ArrayList<>(userFilter.getIdentifiers());
>         if (userFilter.getEmails() != null) {
> ```

 filter by email shouldn't be within identifiers. We need support for both filters and independent of other.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40184)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 221 at r1](https://reviewable.io/reviews/harness/harness-core/40184#-NH1BugH63E1_fVZHJzw:-NI6d0571qd8Lpaw5tv3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a53d9d50dd89f06fe6e39a71b09c497e4fe46218/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L221)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

 filter by email shouldn't be within identifiers. We need support for both filters and independent of other.
</blockquote></details>

Done.

**Review by rijajoo — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40184)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40184#-:-NI8m3ZzD_VSh0D1SN8D:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
