### PR TITLE
[feat]: [PL-27337]: Use secondary mongo node for audit list call

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Use secondary mongo node for audit list call

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36496)

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/mongo/SecondaryMongoTemplateHolder.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/36496#-N9k-H2UCFuit5x4X_F-:-N9k-H2UCFuit5x4X_F0:blteer2) ([raw file](https://github.com/harness/harness-core/blob/984c1ec0a69b49970e0bbd19426a1484840cc516/980-commons/src/main/java/io/harness/mongo/SecondaryMongoTemplateHolder.java#L16)):*
> ```Java
> @Singleton
> public class SecondaryMongoTemplateHolder {
>     @Inject @Named("secondary-preferred-mongo") public MongoTemplate secondaryMongoTemplate;
> ```

Why this way instead of directly injecting? Also can we make this a constant "secondary-preferred-mongo"

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/mongo/SecondaryMongoTemplateHolder.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/36496#-N9k-H2UCFuit5x4X_F-:-NA3bb0S3Zxnrxj3X9h6:b-iiyuf7) ([raw file](https://github.com/harness/harness-core/blob/984c1ec0a69b49970e0bbd19426a1484840cc516/980-commons/src/main/java/io/harness/mongo/SecondaryMongoTemplateHolder.java#L16)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Why this way instead of directly injecting? Also can we make this a constant "secondary-preferred-mongo"
</blockquote></details>

using google inject we were getting same mongo template if we declared in class annotated with HarnessRepo so injected secondary mongo template 980 commons so that everyone can use it

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: Some of the checks are too old. 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/PersistenceModule.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/36496#-NA3zzqnBH815hUZETi6:-NA3zzqnBH815hUZETi7:biip7qd) ([raw file](https://github.com/harness/harness-core/blob/984c1ec0a69b49970e0bbd19426a1484840cc516/959-ng-persistence/src/main/java/io/harness/springdata/PersistenceModule.java#L43)):*
> ```Java
> 
>   @Provides
>   @Named("secondary-preferred-mongo")
> ```

Just name it secondary
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/36496#-NA44NH55x5QuuVfUDbB:-NA44NH55x5QuuVfUDbC:b-nyr13m) ([raw file](https://github.com/harness/harness-core/blob/984c1ec0a69b49970e0bbd19426a1484840cc516/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java#L53)):*
> ```Java
> 
>   @Override
>   public List<String> fetchDistinctAccountIdentifiers() {
> ```

Redirect to Secondary
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/36496#-NA44Pca6J_aX6gL8DAx:-NA44Pcb1GE-cv0llh2Q:b-nyr13m) ([raw file](https://github.com/harness/harness-core/blob/984c1ec0a69b49970e0bbd19426a1484840cc516/platform-service/modules/audit-service/src/main/java/io/harness/audit/repositories/AuditRepositoryCustomImpl.java#L59)):*
> ```Java
> 
>   @Override
>   public AuditEvent get(Criteria criteria) {
> ```

Redirect to Secondary

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: 4 file(s) to review. 2 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496#-:-NAEQYVg-NVsCbkRokOl:bnfp4nl)* status: 1 change requests. 4. unresolved discussions.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496#-:-NAG2Xwt6Y8rL1eX0Nfx:bnfp4nl)* status: 3. unresolved discussions.

**Review by gupta-utkarsh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: 3. unresolved discussions.

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: 3. unresolved discussions.

**Review by meenakshi-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: 3. unresolved discussions.

**Review by meenakshi-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: 3. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496#-:-NAIJPmW6fxrEyz9H1ls:bnfp4nl)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36496)* status: :shipit: complete! ✓

**Pull request merged**
