### PR TITLE
feat: [CI-6740]: Basic trust level implementation

### PR DESCRIPTION
**Pull request by HenAmar**
## Describe your changes

We wish to add the support for trust level for all harness modules. We are going to start with CI. 
 Each account will be assigned with trust level -1 and only these from 50K validated domains will be able to perform this https://harness.atlassian.net/wiki/spaces/~5f1f0648e8c4560022265233/pages/21219279058/RFC-0011+-+Trust+Levels 
 
Important note - this must be account level, not user level thing. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42755)

### CODE REVIEW

**Comment by piyush-harness** [comment]
Approving for PL piece of code :lgtm:

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 16 files at r1, 16 of 17 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755)* status: Some of the checks are too old. Waiting on team(s): sto.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755)* status: Some of the checks are too old. 1 change requests. Waiting on team(s): sto. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1129 at r3](https://reviewable.io/reviews/harness/harness-core/42755#-NN5nCQaByi24vwazSK8:-NN5nCQaByi24vwazSK9:b31y97z) ([raw file](https://github.com/harness/harness-core/blob/2f5158fba71bf2866f7a18f00a8c560ffdca8751/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1129)):*
> ```Java
> 
>   @Override
>   public List<User> getUsersEmails(String accountId) {
> ```

Name of this method should be getUsers

We don't have an index on pendingAccounts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755)* status: Some of the checks are too old. 1 change requests. Waiting on team(s): sto. 

___
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 121 at r3](https://reviewable.io/reviews/harness/harness-core/42755#-NN5nuLH-BVRfnsJfxtt:-NN5nuLH-BVRfnsJfxtu:b-grvv0l) ([raw file](https://github.com/harness/harness-core/blob/2f5158fba71bf2866f7a18f00a8c560ffdca8751/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L121)):*
> ```Java
> 
>   @POST(USER_EMAILS_BATCH_LIST_API)
>   Call<RestResponse<List<UserInfo>>> listUsersEmails(@Query("accountId") String accountId);
> ```

Do we need this API. Cann't we use USER_BATCH_LIST_API API?



_Code quote:_
```Java
USER_BATCH_LIST_API
```

**Comment by HenAmar** [comment]
@ankit-harness I was using the list users originally. 
But @piyush-harness wanted a new api  the will also project the users list emails. as all i need is the emails. 
regrading the pending users, i will remove the query from the pending users table. will leave only for the users table as I don't need the pending

**Review by ankit-harness — COMMENTED** [review]
But isn't the API returning all users?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755#-:-NN5qXF1C30e8jfe6uAY:b-quqljo)* status: Some of the checks are too old. 1 change requests. Waiting on team(s): sto.

**Comment by HenAmar** [comment]
my new api has projection. it returns only the emails

`query.project(UserKeys.email, true)`

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755#-:-NN5u7Sx8-ci9vxZf5lD:bnfp4nl)* status: Some of the checks are too old. Waiting on team(s): sto.

**Review by HenAmar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755)* status: Some of the checks are too old. 2. unresolved discussions. Waiting on team(s): sto. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1129 at r3](https://reviewable.io/reviews/harness/harness-core/42755#-NN5nCQaByi24vwazSK8:-NN5uSoY5e8YQ7TIbcF5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f5158fba71bf2866f7a18f00a8c560ffdca8751/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1129)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Name of this method should be getUsers

We don't have an index on pendingAccounts
</blockquote></details>

Done.
___
*[`930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java` line 121 at r3](https://reviewable.io/reviews/harness/harness-core/42755#-NN5nuLH-BVRfnsJfxtt:-NN5uUQB92vh9gcMCBfK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2f5158fba71bf2866f7a18f00a8c560ffdca8751/930-ng-core-clients/src/main/java/io/harness/user/remote/UserClient.java#L121)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need this API. Cann't we use USER_BATCH_LIST_API API?
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 16 files at r1, 16 of 17 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755#-:-NN5ua4J5dCI7DsdCE9k:bnfp4nl)* status: Some of the checks are too old. Waiting on team(s): sto.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755#-:-NN61QyE4mF81QC8HErE:bnfp4nl)* status: Waiting on team(s): sto.

**Comment by HenAmar** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42755)* status: Waiting on team(s): sto.

**Comment by harshjain12** [comment]
Force merging as it is approved by PL team

**Pull request merged**
