### PR TITLE
techdebt: [PL-29289]: Moved FailureType to eraro

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes
In the process of making 980-commons modular, we need to break cycles between modules. To break cycle between eraro and exception module, moving FailureType to eraro module.

Most of the changes are trivial only. Primary changes are in 980-commons/ and everything else is just auto-generated from Intellij. Since the Failure type is moved, had to update 260-delegate/src/test/resources/kryo-registrations.txt also for tests to pass.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
> Reviewed 94 of 94 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)* status: 94 file(s) to review. 1 of 2 approvals obtained.

**Comment by gn-harness** [comment]
trigger codebasehash

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 94 of 94 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)* status: :shipit: complete! ✓

**Review by archit-harness — DISMISSED** [review]
> Reviewed 93 of 94 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mdmilic — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)* status: 2 file(s) to review.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)* status: 1 of 2 approvals obtained.

**Comment by gn-harness** [comment]
trigger codebasehash

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39146)* status: :shipit: complete! ✓

**Comment by gn-harness** [comment]
trigger codebasehash

**Pull request merged**
