### PR TITLE
feat: [CDS-43003]: Nexus docker artifact

### PR DESCRIPTION
**Pull request by filip5rovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37345)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37345)

**Comment by filip5rovic** [comment]
trigger messagecheck

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37345)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 380 at r1](https://reviewable.io/reviews/harness/harness-core/37345#-NBXiiV6CR-1hYEZcdlj:-NBXiiV6CR-1hYEZcdlk:b-2bag18) ([raw file](https://github.com/harness/harness-core/blob/dc91ed347fbea4a08742816f58fe6710c9765711/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L380)):*
> ```Java
>   }
> 
>   public List<EncryptedDataDetail> getArtifactEncryptionDataDetails(
> ```

qq, why those were removed? For artifacotry and jenkins this will fail

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37345)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 380 at r1](https://reviewable.io/reviews/harness/harness-core/37345#-NBXiiV6CR-1hYEZcdlj:-NBkKn0F0eFeFXuE9tvm:b-wfm6pu) ([raw file](https://github.com/harness/harness-core/blob/dc91ed347fbea4a08742816f58fe6710c9765711/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L380)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

qq, why those were removed? For artifacotry and jenkins this will fail 
</blockquote></details>

I wasn't able to find its usage. There is a similar method `SshWinRmArtifactHelper#getArtifactEncryptionDataDetails` which is actually being used. 

Maybe I missed something there?

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37345)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 380 at r1](https://reviewable.io/reviews/harness/harness-core/37345#-NBXiiV6CR-1hYEZcdlj:-NBkSYWc4FuHIryv6mM8:bh04oom) ([raw file](https://github.com/harness/harness-core/blob/dc91ed347fbea4a08742816f58fe6710c9765711/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L380)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

I wasn't able to find its usage. There is a similar method `SshWinRmArtifactHelper#getArtifactEncryptionDataDetails` which is actually being used. 

Maybe I missed something there?
</blockquote></details>

Just to be on the safe side, can you pls check if artifactory works on your local?

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37345)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by filip5rovic** [comment]
trigger codebasehash

**Pull request merged**
