### PR TITLE
fix: [CDS-40054]: add null check for helm chart app version before saving

### PR DESCRIPTION
**Pull request by prabu-kr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

Is it new task type? No

Did you add a new class which is added in kryo serialization? No

if yes then do not use that class in any of the delegate task payload till it makes to delegate release

Did you make changes to the code in a backward-compatible manner? Yes

will the new version of the delegate receive old version task and process? Yes

If new version of the manager receives response for the old task will it be able to handle it successfully? Yes

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager? No

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay? Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay? Yes

Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )? No

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side. 

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35464)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35464)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35464)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/applicationmanifest/HelmChartServiceImpl.java` line 273 at r1](https://reviewable.io/reviews/harness/harness-core/35464#-N7KshmkB23SZQUJmIMP:-N7KshmkB23SZQUJmIMQ:b-rjs8za) ([raw file](https://github.com/harness/harness-core/blob/539228037e0a9b7aceb6e84a87441d799a3057b3/400-rest/src/main/java/software/wings/service/impl/applicationmanifest/HelmChartServiceImpl.java#L273)):*
> ```Java
>         helmChart.getAccountId(), helmChart.getApplicationManifestId(), helmChart.getVersion());
>     if (existingHelmChart != null) {
>       if(helmChart.getAppVersion()==null){
> ```

Better to have EmptyPredicate.isEmpty() check here

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35464)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35464)* status: :shipit: complete! ✓

**Comment by prabu-kr** [comment]
trigger codebasehash

**Comment by prabu-kr** [comment]
trigger messagecheck

**Pull request merged**
