### PR TITLE
feat:[CDS-75108]: fetching controller using java client for pod detail.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
fetching controller using java client to update the service name in pod detail
Continuing review from closed PR: https://github.com/harness/harness-core/pull/55115

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55726)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger uts

**Comment by GoelPratyush99** [comment]
trigger uts

**Review by alebuh — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55726)* status: 10 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-NjpyT8B9A5ktTCWviP5:-NjpyT8B9A5ktTCWviP6:b-mit5wa) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L252)):*
> ```Java
>       k8sServiceMetadata = kubernetesContainerService.getK8sServiceMetadataUsingFabric8(
>           kubernetesConfig, containerServiceName, accountId);
>       if (isNotEmpty(k8sServiceMetadata.getServiceName())) {
> ```

nit: I feel like this check is sufficient.  We can log that we are trying to fetch using fabric8 before calling a method, and anyway we are logging at the end if result is empty
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 253 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njpy7XW3nPlekluglLb:-Njpy7XW3nPlekluglLc:b-96zajj) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L253)):*
> ```Java
>           kubernetesConfig, containerServiceName, accountId);
>       if (isNotEmpty(k8sServiceMetadata.getServiceName())) {
>         log.info("Fetched service name using Fabric8 client but unable to fetch using kubernetes client");
> ```

nit: might be better to use warn or debug instead of info
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 421 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq1cjF7jfJp5aPoXGo:-Njq1cjF7jfJp5aPoXGp:b258xom) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L421)):*
> ```Java
>         String message = format("Unable to get ReplicationController/%s. Code: %s, message: %s",
>             kubernetesConfig.getNamespace(), exception.getCode(), getErrorMessage(exception));
>         log.info(message);
> ```

nit: should be warn or debug
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 436 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq2-C14R_DKzIiC6Vm:-Njq2-C14R_DKzIiC6Vn:b-h6jvh8) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L436)):*
> ```Java
>           String message = format("Unable to get Deployment/%s. Code: %s, message: %s", kubernetesConfig.getNamespace(),
>               exception.getCode(), getErrorMessage(exception));
>           log.info(message);
> ```

nit:  same here
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 452 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq21C4DZlSxyxttu50:-Njq21C4DZlSxyxttu51:b-vdhdo0) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L452)):*
> ```Java
>           String message = format("Unable to get ReplicaSet/%s. Code: %s, message: %s", kubernetesConfig.getNamespace(),
>               exception.getCode(), getErrorMessage(exception));
>           log.info(message);
> ```

nit: same here
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 484 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq2iVO3ANiPEqfRbMn:-Njq2iVO3ANiPEqfRbMo:b-vdhdo0) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L484)):*
> ```Java
>           String message = format("Unable to get DaemonSet/%s. Code: %s, message: %s", kubernetesConfig.getNamespace(),
>               exception.getCode(), getErrorMessage(exception));
>           log.info(message);
> ```

nit: same here
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 502 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq2kxG9K-T6sN7mCt2:-Njq2kxG9K-T6sN7mCt3:b-vdhdo0) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L502)):*
> ```Java
>           String message = format("Unable to get DeploymentConfig/%s. Code: %s, message: %s",
>               kubernetesConfig.getNamespace(), exception.getCode(), getErrorMessage(exception));
>           log.info(message);
> ```

nit: same here

**Comment by GoelPratyush99** [comment]
trigger uts

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55726)* status: 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-NjpyT8B9A5ktTCWviP5:-Njq8ZuMALIFVGf9vKIw:b-fghauj) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L252)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: I feel like this check is sufficient.  We can log that we are trying to fetch using fabric8 before calling a method, and anyway we are logging at the end if result is empty
</blockquote></details>

True, but we are planning to raise a OPS ticket to set an alert on this log.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java` line 253 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njpy7XW3nPlekluglLb:-Njq8rGV8uTAYSRn1tuS:b2gzv8h) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/260-delegate/src/main/java/io/harness/perpetualtask/instancesyncv2/cg/CgK8sInstancesDetailsFetcher.java#L253)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: might be better to use warn or debug instead of info
</blockquote></details>

Made it as warn as we need to set an alert
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 421 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq1cjF7jfJp5aPoXGo:-Njq9Q8-25dKt-_0G68j:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L421)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: should be warn or debug
</blockquote></details>

done
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 436 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq2-C14R_DKzIiC6Vm:-Njq9QhT4CJma9EjWuDn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L436)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit:  same here
</blockquote></details>

done
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 452 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq21C4DZlSxyxttu50:-Njq9RGt0MpBsewLS2nH:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L452)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: same here
</blockquote></details>

done
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 484 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq2iVO3ANiPEqfRbMn:-Njq9Rlo0YS6XHLz6N5Q:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L484)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: same here
</blockquote></details>

done
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 502 at r2](https://reviewable.io/reviews/harness/harness-core/55726#-Njq2kxG9K-T6sN7mCt2:-Njq9SGCDqsKDhWnCxDL:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/148e5cc288e5011ce79ea94320795356eaf59b93/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L502)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

nit: same here
</blockquote></details>

done

**Review by alebuh — DISMISSED** [review]

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55726)* status: 5 file(s) to review. 2. unresolved discussions. Waiting on team(s): k8s-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/K8sServiceMetadata.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/55726#-NjrYg6LAMecnxuNG90X:-NjrYg6LAMecnxuNG90Y:b-9qv94q) ([raw file](https://github.com/harness/harness-core/blob/4f8c80f76fa8a5cf0fb33b263a584cc573404365/960-api-services/src/main/java/io/harness/k8s/K8sServiceMetadata.java#L22)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = false, components = {HarnessModuleComponent.CDS_K8S})
> public class K8sServiceMetadata {
>   String serviceName;
> ```

nit: can just be `name` instead of `serviceName` since class is already named `K8sServiceMetadata`
___
*[`960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java` line 421 at r3](https://reviewable.io/reviews/harness/harness-core/55726#-NjrZlDB99hxk1Xl6jhl:-NjrZlDB99hxk1Xl6jhm:b1zz9is) ([raw file](https://github.com/harness/harness-core/blob/4f8c80f76fa8a5cf0fb33b263a584cc573404365/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L421)):*
> ```Java
>         String message = format("Unable to get ReplicationController/%s. Code: %s, message: %s",
>             kubernetesConfig.getNamespace(), exception.getCode(), getErrorMessage(exception));
>         log.debug(message);
> ```

debug will never be used in practice, since we have no way of overriding log level in delegate on runtime. we will need to change it in logback.xml to access this log line. will we need this log line to debug possible issues? if yes, then this should be warn.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55726)* status: 6 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by alebuh — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Comment by GoelPratyush99** [comment]
trigger uts

**Comment by GoelPratyush99** [comment]
trigger review

**Pull request merged**
