### PR TITLE
feat: [PIE-6658]: Replacing pipelineInputs with inputs - Pipeline stage

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Replacing pipelineInputs with inputs in pipeline stage config
Testing: In local

ReleaseNotes summary needed? Yes

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40731)

### CODE REVIEW

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40731)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageConfig.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/40731#-NI74DoO8ONp8JlWkuZ6:-NI74DoO8ONp8JlWkuZ7:b-2zqmiz) ([raw file](https://github.com/harness/harness-core/blob/dd0dff6b71bcb3e4f68af2f487409456d8257ed4/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageConfig.java#L60)):*
> ```Java
>   // TODO: this field should be deleted after ui changes
>   @ApiModelProperty(dataType = SwaggerConstants.JSON_NODE_CLASSPATH)
>   @YamlSchemaTypes(runtime)
> ```

We have pipelineInputs and inputs both fields? Are we keeping old field pipelineInput just for backward compatibility or both fields are needed.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40731)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageConfig.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/40731#-NI74DoO8ONp8JlWkuZ6:-NI750sy4ufuGDw2oCzD:b-irh45x) ([raw file](https://github.com/harness/harness-core/blob/dd0dff6b71bcb3e4f68af2f487409456d8257ed4/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageConfig.java#L60)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We have pipelineInputs and inputs both fields? Are we keeping old field pipelineInput just for backward compatibility or both fields are needed.
</blockquote></details>

Yes, will remove once ui removes all its usages

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40731)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/40731#-NI75Vh8EwvJGqSAiIiY:-NI75Vh8EwvJGqSAiIiZ:bquqbsx) ([raw file](https://github.com/harness/harness-core/blob/dd0dff6b71bcb3e4f68af2f487409456d8257ed4/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator/PipelineStagePlanCreator.java#L100)):*
> ```Java
>                     .getField(YAMLFieldNameConstants.SPEC)
>                     .getNode()
>                     .getField(YAMLFieldNameConstants.INPUTS)))
> ```

I think we should check null here. If UI has not made changes then the data will be available in pipelineInputs field. After UI changes data will be available in inputs field.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40731)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40731)* status: :shipit: complete! ✓

**Pull request merged**
