### PR TITLE
feat: [PIE-6046]: NG - Add support for Release Event in Github Webhook Triggers 

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR adds support for Github release events in Github webhook triggers.

## Checklist
- [x] I've documented the changes in the PR description.
- [] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40201)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger ft2

**Review by sribalij — APPROVED** [review]
> Reviewed 14 of 28 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40201)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerFilterStore.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/40201#-NMQUznGDcyMJIFKp726:-NMQUznH3GSFEoNGg7zw:b-9x0u2h) ([raw file](https://github.com/harness/harness-core/blob/a8e0c0e3e6ea715dbc3f978ab223a431e7927ea8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerFilterStore.java#L126)):*
> ```Java
>   }
> 
>   List<TriggerFilter> getTriggerFiltersGithubReleaseList() {
> ```

This isn't a good way of implementing stuff which is git provider specific. Such methods will keep on increasing as we onboard more git providers and will become difficult to maintain. There should be a separate class for such tasks. I guess coz this has been done this way previously thus we have continued it like that here as well, but I would recommend to start doing it the right way otherwise pretty soon it will become difficult to manage.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/WebhookConfigHelper.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/40201#-NMQVYD38wKoRIH5OUxT:-NMQVYD38wKoRIH5OUxU:b-s0fma5) ([raw file](https://github.com/harness/harness-core/blob/a8e0c0e3e6ea715dbc3f978ab223a431e7927ea8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/WebhookConfigHelper.java#L132)):*
> ```Java
>   }
> 
>   public static List<GithubReleaseAction> getGithubReleaseAction() {
> ```

same issue here as mentioned previously. This should be task of a dedicated class that focusses on github to return such release actions. Keeping everything in a generic class is going to make it chaotic.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/WebhookTriggerFilterUtils.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/40201#-NMQVoAZ4muVZCFsaR2C:-NMQVoAZ4muVZCFsaR2D:bdlw98q) ([raw file](https://github.com/harness/harness-core/blob/a8e0c0e3e6ea715dbc3f978ab223a431e7927ea8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/WebhookTriggerFilterUtils.java#L84)):*
> ```Java
>     }
> 
>     if (eventTypeFromPayload.equals(io.harness.beans.WebhookEvent.Type.RELEASE)) {
> ```

we should do a reverse check : constant.equals(variable.getValue())

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40201)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerFilterStore.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/40201#-NMQUznGDcyMJIFKp726:-NMUFNgzAu6HvoBpNfiU:b-7z4i9k) ([raw file](https://github.com/harness/harness-core/blob/a8e0c0e3e6ea715dbc3f978ab223a431e7927ea8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerFilterStore.java#L126)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This isn't a good way of implementing stuff which is git provider specific. Such methods will keep on increasing as we onboard more git providers and will become difficult to maintain. There should be a separate class for such tasks. I guess coz this has been done this way previously thus we have continued it like that here as well, but I would recommend to start doing it the right way otherwise pretty soon it will become difficult to manage.
</blockquote></details>

You are absolutely right, I agree we need to refactor this a bit urgently - I have created a ticket for this: https://harness.atlassian.net/browse/CDS-51726
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/WebhookTriggerFilterUtils.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/40201#-NMQVoAZ4muVZCFsaR2C:-NMUFZac6YGiPn-ffjJ5:b-66si3j) ([raw file](https://github.com/harness/harness-core/blob/a8e0c0e3e6ea715dbc3f978ab223a431e7927ea8/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/WebhookTriggerFilterUtils.java#L84)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should do a reverse check : constant.equals(variable.getValue())
</blockquote></details>

Solved. Thank you for reviewing!

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40201#-:-NMUlIV22Hdl9kjGyEL4:bnfp4nl)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40201)* status: 16 file(s) to review.

**Pull request closed without merging**
