### PR TITLE
fix: [DEL-3836]: Move PCF, host validation task out of 400-rest

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32433)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[890-sm-core/src/main/java/software/wings/beans/VaultConfig.java, line 108 at r2](https://reviewable.io/reviews/harness/harness-core/32433#-N0IVgXA1-672vC6PqPa:-N0IVgXA1-672vC6PqPb:bafdden) ([raw file](https://github.com/harness/harness-core/blob/cbb07598284cf5a571a565fb539e47350d5108c7/890-sm-core/src/main/java/software/wings/beans/VaultConfig.java#L108)):*
> ```Java
>                                           .delegateSelectors(getDelegateSelectors())
>                                           .build();
>     SecretManagerConfigMapper.updateNGSecretManagerMetadata(getNgMetadata(), ngVaultConfigDTO);
> ```

We should move the mapper

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 198 of 198 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32433)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
*[930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java, line 202 at r2](https://reviewable.io/reviews/harness/harness-core/32433#-N0N_yvH7SD1bqpBwzCg:-N0N_yvIDaRDLlidGcZ4:b6vu0hm) ([raw file](https://github.com/harness/harness-core/blob/76eb76d8b2fd9c7a1b3024928219e0c1857f455f/930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java#L202)):*
> ```Java
>     kryo.register(BasicValidationInfo.class, 7325);
>     kryo.register(HostValidationTaskParameters.class, 7341);
>     kryo.register(RancherConfig.class, 50006);
> ```

Are we changing number for the registered class?

**Comment by jennyjames21** [comment]
*[930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java, line 202 at r2](https://reviewable.io/reviews/harness/harness-core/32433#-N0N_yvH7SD1bqpBwzCg:-N0NaYUPCKbAiAofSSWt:b-ftrdoz) ([raw file](https://github.com/harness/harness-core/blob/76eb76d8b2fd9c7a1b3024928219e0c1857f455f/930-delegate-tasks/src/main/java/io/harness/serializer/kryo/DelegateTasksKryoRegistrar.java#L202)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

Are we changing number for the registered class?
</blockquote></details>

no we are keeping the same number

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32433)* status: 16 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[890-sm-core/src/main/java/software/wings/beans/VaultConfig.java, line 108 at r2](https://reviewable.io/reviews/harness/harness-core/32433#-N0IVgXA1-672vC6PqPa:-N0NbZjsBwf02ipYP0TL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cbb07598284cf5a571a565fb539e47350d5108c7/890-sm-core/src/main/java/software/wings/beans/VaultConfig.java#L108)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

We should move the mapper
</blockquote></details>

Done.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32433)* status: :shipit: complete! ✓

**Pull request merged**
