### PR TITLE
feat: [PIE-7518]: Execution changes for policy as advanced options for the steps extended by SyncExecutable

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42385)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 21 files at r1, 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42385)* status: 24 file(s) to review. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/SyncExecutableWithCapabilities.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/42385#-NLUmmui7PFE9eZWFeJN:-NLUmmui7PFE9eZWFeJO:bdb3vss) ([raw file](https://github.com/harness/harness-core/blob/3289328fe86a093610b91ae5234cfd40433417f5/878-ng-common-utilities/src/main/java/io/harness/steps/executable/SyncExecutableWithCapabilities.java#L21)):*
> ```Java
> import lombok.SneakyThrows;
> 
> // Sync Executable With RBAC and postSyncValidation
> ```

nit: There is no rollback?

**Comment by shalini-agr** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 21 files at r1, 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42385)* status: :shipit: complete! ✓

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42385)* status: 1. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/executable/SyncExecutableWithCapabilities.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/42385#-NLUmmui7PFE9eZWFeJN:-NLV4Zg47pD6mcY60bJC:b-32mtg) ([raw file](https://github.com/harness/harness-core/blob/01875f3be7fd7619f73943d6bd560db8bdbea27a/878-ng-common-utilities/src/main/java/io/harness/steps/executable/SyncExecutableWithCapabilities.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: There is no rollback?
</blockquote></details>

No, there's no SyncExecutableWithRollback class

**Pull request merged**
