### PR TITLE
fix: [CDS-85598]: GitClone privileged mode set to null when not set on UI

### PR DESCRIPTION
**Pull request by ivan-83**
The is an issue when k8s is running on Win where privileged is not supported and updated behaviour,
The behavior is next:

Reported issue https://harness.atlassian.net/browse/CDS-86973

missing privileged in YAML >> null
privileged: false in YAML >> false
privileged: true in YAML >> true

We need to inform customers that they need to explicitly provide privileged: false in YAML 

cc: @rajatharanganath 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56790)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger uts

**Comment by ivan-83** [comment]
trigger uts

**Comment by smjt-h** [comment]
Did we test it for windows and linux builds

**Comment by devkimittal** [comment]
let's add a ut to avoid any further regression

**Comment by ivan-83** [comment]
> Did we test it for windows and linux builds

I tested for Linux not having Win K8s, but I think we are safe because privileged will be null in the below code block if it's not set in YAML, like before my changes. 
```
    if (CIStepInfoUtils.getPrivilegedMode(stepInfo) != null) {
      privileged = CIStepInfoUtils.getPrivilegedMode(stepInfo).getValue();
    }
```

**Review by smjt-h — APPROVED** [review]

**Comment by ivan-83** [comment]
> let's add a ut to avoid any further regression

I am going to create a separate ticket for UTs, this is HF and we need to unblock QA sign-off process.

**Review by devkimittal — APPROVED** [review]

**Comment by ivan-83** [comment]
trigger review

**Review by harshjain12 — APPROVED** [review]

**Comment by ivan-83** [comment]
trigger review

**Pull request merged**
