### PR TITLE
fix: [PL-42344]: Update notification open api spec with enums

### PR DESCRIPTION
**Pull request by jennyjames21**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54898)

### CODE REVIEW

**Review by mankrit-singh — APPROVED** [review]

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 455 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUKFJ5t2bEY8l3Rvv:-NiYUKFJ5t2bEY8l3Rvw:b-mcsk4p) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L455)):*
> ```YAML
>         - MSTEAMS
>         - WEBHOOK
>       description: Notification Channel Type
> ```

I think it should have type defined as string for enums



_Code snippet:_
```YAML
type: string
```

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 463 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUV-w98da0SQ8w_FJ:-NiYUV-w98da0SQ8w_FK:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L463)):*
> ```YAML
>         - ENABLED
>         - DISABLED
>       description: Notification Rule Status
> ```

same as above

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUXuC2IsCrIKMlMSK:-NiYUXuC2IsCrIKMlMSL:b-iu7ie6) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L406)):*
> ```YAML
>                           notification_channel_type:
>                             $ref: '#/components/schemas/ChannelType'
>                           status:
> ```

This is some different status field. Or the one which you created and referenced below?

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYVE_U2nW5KMgB4bu8:-NiYVE_U2nW5KMgB4bu9:b7lkesg) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L405)):*
> ```YAML
>                             type: string
>                           notification_channel_type:
>                             $ref: '#/components/schemas/ChannelType'
> ```

Have you verified generated models for all these openapi changes?

**Comment by jennyjames21** [comment]
> _[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYVE_U2nW5KMgB4bu8:-NiYVE_U2nW5KMgB4bu9:b7lkesg) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L405)):_
> 
> > ```yaml
> >                             type: string
> >                           notification_channel_type:
> >                             $ref: '#/components/schemas/ChannelType'
> > ```
> 
> Have you verified generated models for all these openapi changes?

yes it's covered here and verified by FE https://github.com/harness/harness-core/pull/54164

**Comment by jennyjames21** [comment]
> _[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUXuC2IsCrIKMlMSK:-NiYUXuC2IsCrIKMlMSL:b-iu7ie6) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L406)):_
> 
> > ```yaml
> >                           notification_channel_type:
> >                             $ref: '#/components/schemas/ChannelType'
> >                           status:
> > ```
> 
> This is some different status field. Or the one which you created and referenced below?
Status created by me in this file and referenced here

**Comment by jennyjames21** [comment]
> _[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 455 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUKFJ5t2bEY8l3Rvv:-NiYUKFJ5t2bEY8l3Rvw:b-mcsk4p) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L455)):_
> 
> > ```yaml
> >         - MSTEAMS
> >         - WEBHOOK
> >       description: Notification Channel Type
> > ```
> 
> I think it should have type defined as string for enums
> 
> _Code snippet:_
> 
> ```yaml
> type: string
> ```

not sure in understand your comments, i defined enum in stoplight
image

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 406 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUXuC2IsCrIKMlMSK:-NiZ-HzI6IakKRJxucZt:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L406)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Status created by me in this file and referenced here
</blockquote></details>

ok

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 405 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYVE_U2nW5KMgB4bu8:-NiZ-JOo9kyo4rPYkH2a:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L405)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes it's covered here and verified by FE https://github.com/harness/harness-core/pull/54164
</blockquote></details>

ok

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml` line 455 at r1](https://reviewable.io/reviews/harness/harness-core/54898#-NiYUKFJ5t2bEY8l3Rvv:-NiYzoVF8t3BWKEdGI6v:bwcsrmf) ([raw file](https://github.com/harness/harness-core/blob/1d1fbefb373b80b4be1605833b6229687c019066/platform-service/modules/notification-service/contracts/openapi/v1/openapi.yaml#L455)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

not sure in understand your comments, i defined enum in stoplight
image

</blockquote></details>

Hmm.. I think it should generate type: string for enums something like this
https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#typed-enum
https://swagger.io/docs/specification/data-models/enums/

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54898)* status: Some of the checks are too old. 1 file(s) to review.

**Pull request merged**
