### PR TITLE
[feat]: [PL-41292]: add migration to populate uniqueId population for project and org entity

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Adding common migration logic to migrate NG entities for populating uniqueId. Using the common migration on ORG and PROJECT entities to populate uniqueId for existing ORG/PROJECT. Any entity extending from common UniqueIdAware can use the base migration to populate the uniqueId in their collection.

Testing done:
- Tested migration on Project entities with success count equal to uniqueId populated document count
- Tested migration on Organization entities with success count equal to uniqueId populated document count

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2AsTxCBd9-k7DoQYg:-Ng2AsTxCBd9-k7DoQYh:bjw8yxw) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java#L20)):*
> ```Java
>   String getUniqueId();
> 
>   String getId();
> ```

@pbarapatre10 We would not have it as we discussed yesterday
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2DBdf6mwZzF_SRkLy:-Ng2DBdf6mwZzF_SRkLz:b-j1om11) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L56)):*
> ```Java
>     int iteratedCounter = 0;
>     int tobeUpdatedCounter = 0;
>     final BulkOperations bulkOperations = mongoTemplate.bulkOps(BulkOperations.BulkMode.UNORDERED, persistentClass);
> ```

Initialize variables closer to usage site
Dont use final for method local variables
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2DNr95on54s3ZGcnZ:-Ng2DNr95on54s3ZGcn_:bn78d1n) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L60)):*
> ```Java
>     Query documentQuery = new Query(new Criteria());
>     long totalCount = mongoTemplate.count(documentQuery, persistentClass); // at end: totalCount = iteratedCounter
>     log.info(format("%s total count of entity type %s is equal to %s", UNIQUE_ID_GENERATION_LOG_CONST,
> ```

[%s] Entity Type : [%s], Count: [%s]
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2DXyA-AGuVPCoCh68:-Ng2DXyA-AGuVPCoCh69:b-in4743) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L64)):*
> ```Java
> 
>     try (CloseableIterator<? extends UniqueIdAware> iterator = mongoTemplate.stream(
>              documentQuery.limit(MongoConfig.NO_LIMIT).cursorBatchSize(BATCH_SIZE), persistentClass)) {
> ```

Specify maxTime as Integer.MAX_VALUE

Don't use cursorBatchSize. Its not needed
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2Dl-GDJnesHY1FWnS:-Ng2Dl-GDJnesHY1FWnT:br69ij0) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L68)):*
> ```Java
>         iteratedCounter++;
>         UniqueIdAware entity = iterator.next();
>         if (isEmpty(entity.getUniqueId()) && (entity instanceof Project || entity instanceof Organization)) {
> ```

Check instanceOf and then Cast to get Id
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2E2Ar-YM_pqkcoSmu:-Ng2E2Ar-YM_pqkcoSmv:brf8oic) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L82)):*
> ```Java
>     }
>     log.info(format(
>         "%s job was successful. Iterated through %s entities of type %s, needed update for total %s entities. Successfully migrated: %s, but failed for: %s",
> ```

[%s] Entity Type : [%s], Original Count: [%d], Success : [%d], Failure : [%d]

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2EuZc5mPIeYnRyemS:-Ng2EuZc5mPIeYnRyemT:bz1nmhr) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L74)):*
> ```Java
>         }
>       }
>       successMigratedCountTotal += bulkOperations.execute().getModifiedCount();
> ```

Update in batches

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2DBdf6mwZzF_SRkLy:-Ng2Ywye7C2bAra8WhCQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L56)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Initialize variables closer to usage site
Dont use final for method local variables
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2DNr95on54s3ZGcnZ:-Ng2YyGv2lymBc5JaSDO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L60)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

[%s] Entity Type : [%s], Count: [%s]
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2DXyA-AGuVPCoCh68:-Ng2YzT5COi7yF_zSCHg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L64)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Specify maxTime as Integer.MAX_VALUE

Don't use cursorBatchSize. Its not needed
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2Dl-GDJnesHY1FWnS:-Ng2Z1_d7MyETCjiy82n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L68)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Check instanceOf and then Cast to get Id
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2EuZc5mPIeYnRyemS:-Ng2Z3YH6kuwqYznT-30:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L74)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Update in batches
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2E2Ar-YM_pqkcoSmu:-Ng2Z5yZ1PDlZVXwQN-Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L82)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

[%s] Entity Type : [%s], Original Count: [%d], Success : [%d], Failure : [%d]
</blockquote></details>

Done.

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2AsTxCBd9-k7DoQYg:-Ng2Z8aX6HEqh6_Qw9Zh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@pbarapatre10 We would not have it as we discussed yesterday
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/53664#-Ng2EuZc5mPIeYnRyemS:-Ng3VY7J1ZuuoTow7AM0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/22ae925cfcd4dbbe26114455f5e1829ea21d1a39/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L74)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/ProjectBackgroundMigrationDetails.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/53664#-Ng3cyto5ZQ0tX8WMn7n:-Ng3cyto5ZQ0tX8WMn7o:bgmw48m) ([raw file](https://github.com/harness/harness-core/blob/139fdf08da9b813335ab679d054d4bc871e89da1/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/ProjectBackgroundMigrationDetails.java#L37)):*
> ```Java
>   public List<Pair<Integer, Class<? extends NGMigration>>> getMigrations() {
>     return new ImmutableList.Builder<Pair<Integer, Class<? extends NGMigration>>>()
>         .add(Pair.of(1, ProjectUniqueIdGenerationMigration.class))
> ```

Lets call it AddUniqueIdToProjectMigration.class. Same for Org
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/53664#-Ng3d4FFDGShZH3RmZnm:-Ng3d4FFDGShZH3RmZnn:b-1idgmn) ([raw file](https://github.com/harness/harness-core/blob/139fdf08da9b813335ab679d054d4bc871e89da1/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L37)):*
> ```Java
> @OwnedBy(PL)
> @Slf4j
> public class NGUniqueIdGenerationMigration<T extends UniqueIdAware> {
> ```

AddUniqueIdToNGEntitiesMigration

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/53664#-Ng3d4FFDGShZH3RmZnm:-Ng3edmdAXK7dpgDr1N-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/139fdf08da9b813335ab679d054d4bc871e89da1/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration/tasks/uniqueid/NGUniqueIdGenerationMigration.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

AddUniqueIdToNGEntitiesMigration
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664#-:-Ng3esUb9VH1_btL4fmC:bnfp4nl)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53664)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger uts

**Pull request merged**
