### PR TITLE
fix: [SRM-12174]: resource level test cases for SLO dashboard list view api

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38021)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38021)

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38021)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/38021#-ND1AQ__-eVRM7l_fZm5:-ND1AQ__-eVRM7l_fZm6:b-dtpkw6) ([raw file](https://github.com/harness/harness-core/blob/17585d2012768c9fba2ffb9e7568287ce51a4f1f/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java#L123)):*
> ```Java
>     serviceLevelObjectiveResponse = serviceLevelObjectiveService.create(builderFactory.getProjectParams(), sloDTO);
> 
>     sloDTO = builderFactory.getServiceLevelObjectiveDTOBuilder()
> ```

rename these as sloDto1,2,3 and verify all 3 responses are coming correct



_Code quote:_
```Java
sloDTO
```
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/38021#-ND1A2bgCc7UbhNfLTJH:-ND1A2bgCc7UbhNfLTJI:b-8odm4x) ([raw file](https://github.com/harness/harness-core/blob/17585d2012768c9fba2ffb9e7568287ce51a4f1f/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java#L143)):*
> ```Java
>     JSONObject pageResponse = new JSONObject(responseString);
>     pageResponse = (JSONObject) pageResponse.get("data");
>     assertThat(pageResponse.get("totalItems")).isEqualTo(2);
> ```

Shouldn't it be 3? Since you have created 3 slo's



_Code quote:_
```Java
.isEqualTo(2);
```
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImplTest.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/38021#-ND1BLaa9xSorm-6IAZV:-ND1BLaa9xSorm-6IAZW:bdhw4um) ([raw file](https://github.com/harness/harness-core/blob/17585d2012768c9fba2ffb9e7568287ce51a4f1f/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImplTest.java#L416)):*
> ```Java
>     PageResponse<SLOHealthListView> pageResponse =
>         sloDashboardService.getSloHealthListView(builderFactory.getProjectParams(),
>             SLODashboardApiFilter.builder().monitoredServiceIdentifier(monitoredServiceIdentifier + '1').build(),
> ```

verify the size is 2 for monitoredServiceIdentifier as well



_Code quote:_
```Java
monitoredServiceIdentifier + '1'
```

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38021)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java` line 123 at r1](https://reviewable.io/reviews/harness/harness-core/38021#-ND1AQ__-eVRM7l_fZm5:-ND1LgZcDpTLI89yv5TY:bbadstf) ([raw file](https://github.com/harness/harness-core/blob/17585d2012768c9fba2ffb9e7568287ce51a4f1f/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java#L123)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

rename these as sloDto1,2,3 and verify all 3 responses are coming correct
</blockquote></details>

ok, will do that
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/38021#-ND1A2bgCc7UbhNfLTJH:-ND1LB0S4uFeUBzJy1Sb:boziffw) ([raw file](https://github.com/harness/harness-core/blob/17585d2012768c9fba2ffb9e7568287ce51a4f1f/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResourceTest.java#L143)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Shouldn't it be 3? Since you have created 3 slo's
</blockquote></details>

applied a userJourneyIdentifier filter, so response contains two slos.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImplTest.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/38021#-ND1BLaa9xSorm-6IAZV:-ND1Lmll7Bhdyy7iEidE:b-cdvlgi) ([raw file](https://github.com/harness/harness-core/blob/17585d2012768c9fba2ffb9e7568287ce51a4f1f/300-cv-nextgen/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImplTest.java#L416)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

verify the size is 2 for monitoredServiceIdentifier as well
</blockquote></details>

ok got it

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38021)* status: 1 change requests. 3. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38021)* status: :shipit: complete! ✓

**Pull request merged**
