### PR TITLE
fix: [PL-29663]: Added check for name change in gcp sm rename

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
GCP SM does not allow rename operation for its secrets. Hence, GCP SM in Harness throws an error for rename operation. When we try to update a secret from the secret modal without actually making any changes, a rename operation is assumed, resulting in GCP SM's rename error on the UI. A name change check has been introduced so that an error is not thrown when the user saves secret modal without making any changes.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40351)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40351)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/40351#-NH9CRld-A8RfgO2igak:-NH9CRld-A8RfgO2igal:b22eczd) ([raw file](https://github.com/harness/harness-core/blob/b8ff81d238ef84c6770103cb83af0a8649185d33/890-sm-core/src/test/java/io/harness/encryptors/GcpSecretsManagerEncryptorTest.java#L110)):*
> ```Java
>         .thenCallRealMethod();
>     when(gcpSecretsManagerEncryptor.validateSecretManagerConfiguration(any(), any())).thenCallRealMethod();
>     when(gcpSecretsManagerEncryptor.renameSecret(any(), any(SecretText.class), any(), any())).thenCallRealMethod();
> ```

Calling real method might not be required for every test case. Move this to the specific test case.

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by piyush-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40351#-:-NHO0RkMCsep26SxCDrK:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40351)* status: :shipit: complete! ✓

**Pull request merged**
