### PR TITLE
fix: [PL-23102]: Move File Ops Entity Page file path fix

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)

### CODE REVIEW

**Review by bhavya181 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 8 files at r5, 12 of 14 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 3 of 14 files at r6, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)* status: 15 file(s) to review.

**Review by arpit3107 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)* status: 15 file(s) to review.

**Review by arpit3107 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329#-:-Mxu5YFq1cc1uw7d19Ui:bnfp4nl)* status: 15 file(s) to review.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 3 of 14 files at r6, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)* status: 15 file(s) to review.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 3 of 8 files at r5, 9 of 14 files at r6, 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31329)* status: :shipit: complete! ✓

**Pull request merged**
