### PR TITLE
feat: [CDS-36021]: Create and update files in FileStore via YAML

### PR DESCRIPTION
**Pull request by filip5rovic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32263)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 15 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32263#-:-N-hmgSR4wKWHABAbR6H:bnfp4nl)* status: :shipit: complete! ✓

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 15 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32263)* status: :shipit: complete! ✓

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32263)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 10 of 17 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32263)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32263)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 10 of 17 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, 5 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32263)* status: :shipit: complete! ✓

**Pull request merged**
