### PR TITLE
feat: [PL-25394]: added API support to set git sync v2 property per project level

### PR DESCRIPTION
**Pull request by mohitg0795**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33439)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33439)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/33439#-N2uJwsR3l23PKOHu3BW:-N2uJwsR3l23PKOHu3BX:b-onu5vj) ([raw file](https://github.com/harness/harness-core/blob/3b5a95cb109539694dccce240cedde3637ae61a4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java#L172)):*
> ```Java
>       @Parameter(required = true) @NotEmpty @QueryParam(PROJECT_KEY) @ProjectIdentifier String projectIdentifier) {
>     accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountIdentifier, orgIdentifier, projectIdentifier),
>         Resource.of(ResourceTypes.PROJECT, projectIdentifier), EDIT_PROJECT_PERMISSION);
> ```

Why Edit Project Permission check on get request.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/33439#-N2uJwsR3l23PKOHu3BW:-N2vB0KODZptBepDO9Lb:binucsa) ([raw file](https://github.com/harness/harness-core/blob/3b5a95cb109539694dccce240cedde3637ae61a4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java#L172)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why Edit Project Permission check on get request.
</blockquote></details>

Will fix it, copy paste issue.

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33439)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/33439#-N2uJwsR3l23PKOHu3BW:-N2wsobQ81YdJGOwt3Q0:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3b5a95cb109539694dccce240cedde3637ae61a4/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java#L172)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Will fix it, copy paste issue.
</blockquote></details>

done

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33439#-:-N2xxbr-8u6HKRKv7kKx:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 12 of 15 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33439#-:-N2z91U50PQvXpd2PSRp:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
:lgtm:

> Reviewed 12 of 15 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33439#-:-N2zA2JdAqRQCher4G42:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
