### PR TITLE
[feat]:[PL-26312]: Integrate GET template flow with GitX

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Integrate GET template flow with GitX
I have tested getTemplate for:
no gitX project - working
oldGitSync project - working
new GitX project - working

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35429)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GZwNqD6UGdmSrKdrg:-N7GZwNqD6UGdmSrKdrh:b1d6a3r) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L68)):*
> ```Java
>         : templateEntity.getStoreType() == StoreType.REMOTE
>         ? GitAwareContextHelper.getEntityGitDetailsFromScmGitMetadata()
>         : null;
> ```

can we avoid returning null in this case? If possible, lets return empty object.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7G_vIC1tJpIkoGebLA:-N7G_vIC1tJpIkoGebLB:bp44u8s) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L72)):*
> ```Java
>     try {
>       Optional<TemplateEntity> optionalTemplate;
>       boolean oldGitSync = TemplateUtils.isOldGitSync(gitSyncSdkService, accountId, orgIdentifier, projectIdentifier);
> ```

name of the variable should be "isOldGitSync"

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GacA61SXbkRQZmvc-:-N7GacA61SXbkRQZmvc0:b-w0t0m0) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L76)):*
> ```Java
>         if (oldGitSync) {
>           optionalTemplate =
>               templateRepository
> ```

can we move this complete block to a logical method? It will help to increase readability

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7Gahyy0dU9vLH5ysA7:-N7Gahyy0dU9vLH5ysA8:b-w0t0m0) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L92)):*
> ```Java
>       }
>       if (oldGitSync) {
>         optionalTemplate =
> ```

can we move this complete block to a logical method? It will help to increase readability

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GakYn41MnTekszrvp:-N7GakYn41MnTekszrvq:b-w0t0m0) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L209)):*
> ```Java
> 
>       Optional<TemplateEntity> optionalTemplate;
>       if (TemplateUtils.isOldGitSync(
> ```

can we move this complete block to a logical method? It will help to increase readability

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GaqzI8aODqbX5fS0E:-N7GaqzI8aODqbX5fS0F:btu0gdf) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java#L28)):*
> ```Java
> 
>   public static boolean isOldGitSync(
>       GitSyncSdkService gitSyncSdkService, String accountIdentifier, String orgIdentifier, String projectIdentifier) {
> ```

we shouldn't be passing services as arguments

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429)* status: 10 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GZ5vr62kZZUE9q37w:-N7Ja2aZ8J-xn_X1e67_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L141)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets not use newGitX anywhere. This is the way forward, so there's nothing like "new" gitX. You can just use "old gitx" wherever required
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GZwNqD6UGdmSrKdrg:-N7JaRYSAHm3CN50c9Kd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L68)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we avoid returning null in this case? If possible, lets return empty object.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7G_vIC1tJpIkoGebLA:-N7JaYCD3B0PDVOW5lch:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L72)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

name of the variable should be "isOldGitSync"
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GacA61SXbkRQZmvc-:-N7JcsXL7chfEbsA1Q91:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L76)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we move this complete block to a logical method? It will help to increase readability
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7Gahyy0dU9vLH5ysA7:-N7JcsxB-a4JLigXghm0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L92)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we move this complete block to a logical method? It will help to increase readability
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GakYn41MnTekszrvp:-N7Je0Pu5TMKvab05oNI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L209)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we move this complete block to a logical method? It will help to increase readability
</blockquote></details>

Done.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429)* status: 10 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/35429#-N7GaqzI8aODqbX5fS0E:-N7K1yrO1Dt4jnoxC8wf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f828b8c75b9f9e81dcb3b963473d5de17b8f7fec/840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't be passing services as arguments
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429)* status: 10 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/35429#-N7KL7trCndwJRjUusNs:-N7KL7trCndwJRjUusNt:bfj6b3y) (no related file):*
I see with the new changes Service layer and repository layer has become too complex.
I propose to create a Dao layer between service and repository layer which has the logic to check for old and new git sync flows, all the criterias that we need. Repository layer work should only be to get any information from 3rd party like mongo or git.

___

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 2 of 9 files at r2, 5 of 7 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429#-:-N7L0-Z4AzP5NQTHJ9hs:bnfp4nl)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429#-:-N7L3v0KAFkS423lG6Fs:bnfp4nl)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger codebasehash

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 2 of 9 files at r2, 2 of 3 files at r3, 6 of 7 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/35429#-N7KL7trCndwJRjUusNs:-N7KVe_N37RBPT5f4wLe:b-182ysm) (no related file):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

I see with the new changes Service layer and repository layer has become too complex.
I propose to create a Dao layer between service and repository layer which has the logic to check for old and new git sync flows, all the criterias that we need. Repository layer work should only be to get any information from 3rd party like mongo or git.
</blockquote></details>

As discussed, we will pick this refactoring task separately to clean up code.

___

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429#-:-N7LAY2ADlr7dejyi94_:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35429)* status: :shipit: complete! ✓

**Pull request merged**
