### PR TITLE
feat: [DEL-3377]: Next gen audit events for delegate

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31315)

### CODE REVIEW

**Comment by jennyjames21** [comment]
image

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2075 at r2](https://reviewable.io/reviews/harness/harness-core/31315#-MxpkWdh-vzxjLOa6Rl3:-MxpkWdh-vzxjLOa6Rl4:bjjq68r) ([raw file](https://github.com/harness/harness-core/blob/ff37afbe6cbac76821da35781460ce88b928ccce/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2075)):*
> ```Java
>                            .filter(DelegateKeys.accountId, accountId)
>                            .filter(DelegateKeys.uuid, delegateId));
>     if (existingDelegate.isNg()) {
> ```

we should move this check of ng in the methods like sendDelegateDeleteAuditEvent(existingDelegate, accountId) itself

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2496 at r2](https://reviewable.io/reviews/harness/harness-core/31315#-MxpkhH-4LHoTCJPLfAA:-MxpkhH-4LHoTCJPLfAB:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/ff37afbe6cbac76821da35781460ce88b928ccce/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2496)):*
> ```Java
> 
>       registeredDelegate = add(delegate);
>       if (delegate.isNg()) {
> ```

same here

**Comment by raghuAtWings** [comment]
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java, line 551 at r2](https://reviewable.io/reviews/harness/harness-core/31315#-MxpkqHO76SAQ361IS8a:-MxpkqHO76SAQ361IS8b:bcnz9pg) ([raw file](https://github.com/harness/harness-core/blob/ff37afbe6cbac76821da35781460ce88b928ccce/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L551)):*
> ```Java
>     delegateCache.invalidateDelegateGroupCacheByIdentifier(accountId, owner, delegateGroupName);
> 
>     outboxService.save(
> ```

we will create groups for cg as well for immutable delegates. we should do this based on ng or not and send the audit for cg delegates as well

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2075 at r2](https://reviewable.io/reviews/harness/harness-core/31315#-MxpkWdh-vzxjLOa6Rl3:-MxrisuuAy6CPfRROvW7:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/ff37afbe6cbac76821da35781460ce88b928ccce/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2075)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should move this check of ng in the methods like sendDelegateDeleteAuditEvent(existingDelegate, accountId) itself
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2496 at r2](https://reviewable.io/reviews/harness/harness-core/31315#-MxpkhH-4LHoTCJPLfAA:-Mxrive45-MEj2awYv4r:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/ff37afbe6cbac76821da35781460ce88b928ccce/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2496)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java, line 551 at r2](https://reviewable.io/reviews/harness/harness-core/31315#-MxpkqHO76SAQ361IS8a:-MxrizRsEsh8uu81kmf6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff37afbe6cbac76821da35781460ce88b928ccce/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L551)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we will create groups for cg as well for immutable delegates. we should do this based on ng or not and send the audit for cg delegates as well
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3906 at r3](https://reviewable.io/reviews/harness/harness-core/31315#-Mxuu8CqC_fqoomsvm6r:-Mxuu8CqC_fqoomsvm6s:bd3x4ye) ([raw file](https://github.com/harness/harness-core/blob/eb1c9f06785651eacb50d12ff59490b23d1cad3f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3906)):*
> ```Java
> 
>   private void sendUnregisterDelegateAuditEvent(Delegate delegate, String accountId) {
>     if (delegate.isNg()) {
> ```

we should add the corresponding cg side as well, the immutable delegate will call unregister

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3962 at r3](https://reviewable.io/reviews/harness/harness-core/31315#-MxuuITw3SCJWiT0rKUB:-MxuuITw3SCJWiT0rKUC:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/eb1c9f06785651eacb50d12ff59490b23d1cad3f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3962)):*
> ```Java
>   private void sendNewDelegateGroupAuditEvent(
>       DelegateSetupDetails delegateSetupDetails, DelegateGroup delegateGroup, String accountId) {
>     if (delegateGroup.isNg()) {
> ```

same here

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31315)* status: 0 of 1 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31315)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupDeleteEvent.java, line 32 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHgBHA6wThP-dInYZi:-MyHgBHA6wThP-dInYZj:bvbsva1) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupDeleteEvent.java#L32)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     return Resource.builder().identifier(delegateGroupId).type(ResourceTypeConstants.DELEGATE_GROUPS).build();
> ```

Add resource name as well.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupUpsertEvent.java, line 32 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHgCnA4XIVWxZn1TKe:-MyHgCnA4XIVWxZn1TKf:bvbsva1) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupUpsertEvent.java#L32)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     return Resource.builder().identifier(delegateGroupId).type(ResourceTypeConstants.DELEGATE_GROUPS).build();
> ```

Add resource name as well.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateRegisterEvent.java, line 26 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHg-HK0Q7lPW3mJqXx:-MyHg-HK0Q7lPW3mJqXy:bvbsva1) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateRegisterEvent.java#L26)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     return Resource.builder().identifier(delegateSetupDetails.getName()).type(ResourceTypeConstants.DELEGATE).build();
> ```

Add resource name as well.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateUnregisterEvent.java, line 26 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHflD3-6NfTpXHBjdl:-MyHflD3-6NfTpXHBjdm:bvbsva1) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateUnregisterEvent.java#L26)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     return Resource.builder().identifier(delegateSetupDetails.getName()).type(ResourceTypeConstants.DELEGATE).build();
> ```

Add resource name as well.

**Comment by jennyjames21** [comment]
image

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31315)* status: 14 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3906 at r3](https://reviewable.io/reviews/harness/harness-core/31315#-Mxuu8CqC_fqoomsvm6r:-MzSubiL7llGFQpt3C17:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eb1c9f06785651eacb50d12ff59490b23d1cad3f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3906)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should add the corresponding cg side as well, the immutable delegate will call unregister
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3962 at r3](https://reviewable.io/reviews/harness/harness-core/31315#-MxuuITw3SCJWiT0rKUB:-MzSuf7f9EY2jB-9hOTM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eb1c9f06785651eacb50d12ff59490b23d1cad3f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3962)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupDeleteEvent.java, line 32 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHgBHA6wThP-dInYZi:-MzSvaau0ytKknFd33Yx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupDeleteEvent.java#L32)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add resource name as well.
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupUpsertEvent.java, line 32 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHgCnA4XIVWxZn1TKe:-MzSvbRp9QK29WtPOR7q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateGroupUpsertEvent.java#L32)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add resource name as well.
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateRegisterEvent.java, line 26 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHg-HK0Q7lPW3mJqXx:-MzSvc4V3qKklvySkuk8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateRegisterEvent.java#L26)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add resource name as well.
</blockquote></details>

Done.
___
*[420-delegate-service/src/main/java/io/harness/delegate/events/DelegateUnregisterEvent.java, line 26 at r4](https://reviewable.io/reviews/harness/harness-core/31315#-MyHflD3-6NfTpXHBjdl:-MzSvcjT7ck2985PU_1c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68f3ea3e598dc0a113b26b778ecfa03035ca29fb/420-delegate-service/src/main/java/io/harness/delegate/events/DelegateUnregisterEvent.java#L26)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add resource name as well.
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31315)* status: 16 file(s) to review. 2. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 11 files at r4, 6 of 9 files at r5, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31315)* status: :shipit: complete! ✓

**Pull request merged**
