### PR TITLE
techdebt: [PL-31832]: Fix the 3rd batch of cycles in 930-delegate-tasks

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR fixes the 3rd batch of cycles in 930-delegate-tasks. It also adds granular Build targets for most of the modules in 930-delegate-tasks.

Below package was moved -

`helpers.ext.helm.request.HelmCommandRequest` --> `delegatetasks.validation.capabilities.HelmCommandRequest`

The rest of the cycles fixes were through minor code moves to different files, code refactoring and module creations.

Most of the line additions are because of the new Build files added.

Tested end to end K8s deployment in PR env.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 22 of 186 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)* status: 186 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/cvng/connectiontask/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2p45c2HKNAggaeKcm:-NS2p45d5LboJwJv1vA0:bwnfsmr) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/cvng/connectiontask/BUILD.bazel#L20)):*
> ```Starlark
>         "//960-api-services/src/main/java/io/harness/security/encryption:module",
>         "//970-api-services-beans/src/main/java/io/harness/security/encryption:module",
>         "//970-ng-commons:module",
> ```

I think 970-ng-commons should be broken down to package targets, maybe not completely?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/chartmuseum/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pXO5E2x0J8FrpwVy:-NS2pXO5E2x0J8FrpwVz:bgwcrjv) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/chartmuseum/BUILD.bazel#L19)):*
> ```Starlark
>         "//960-api-services/src/main/java/io/harness/chartmuseum:module",
>         "//960-api-services/src/main/java/io/harness/k8s/config:module",
>         "//970-ng-commons:module",
> ```

check if you can use package target
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/expression/BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pdbA4SvVojxKPaCR:-NS2pdbA4SvVojxKPaCS:b-tvl05k) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/expression/BUILD.bazel#L26)):*
> ```Starlark
>         "@maven//:com_google_inject_guice",
>         "@maven//:commons_io_commons_io",
>         "@maven//:io_harness_ng_license_beans",
> ```

remove license beans and format the file
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/http/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pkcID4q6HxMGFRAv:-NS2pkcID4q6HxMGFRAw:b-adjunz) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/http/BUILD.bazel#L20)):*
> ```Starlark
>         "//950-delegate-tasks-beans:module",
>         "//970-api-services-beans/src/main/java/io/harness/logging:module",
>         "//970-ng-commons:module",
> ```

Check all usages of ng-commons if you could use package targets
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/BUILD.bazel` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pv5X2fyOzS2h-1xw:-NS2pv5X2fyOzS2h-1xx:b-4lb4i6) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/BUILD.bazel#L33)):*
> ```Starlark
>         "//980-commons/src/main/java/io/harness/eraro:module",
>         "@maven//:com_google_inject_guice",
>         "@maven//:io_harness_ng_license_beans",
> ```

Remove all usages of license beans. I think they are included for some new deps when you didn't regenerate the index. Check the `index generation` section in the [readme](https://github.com/harness/harness-core/blob/develop/tools/build-cleaner/README.md#internals) and see if regenerating index would help not get those deps

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)* status: 189 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/cvng/connectiontask/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2p45c2HKNAggaeKcm:-NS9-6R02tJSiE9RezSv:bylteiu) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/cvng/connectiontask/BUILD.bazel#L20)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think 970-ng-commons should be broken down to package targets, maybe not completely?
</blockquote></details>

Yes,  added granular deps for it.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/chartmuseum/BUILD.bazel` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pXO5E2x0J8FrpwVy:-NS9-BIU2D_rIItfF_dM:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/chartmuseum/BUILD.bazel#L19)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

check if you can use package target
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/expression/BUILD.bazel` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pdbA4SvVojxKPaCR:-NS9-CPDCP9Z49cX8s5W:bnz8lqf) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/expression/BUILD.bazel#L26)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

remove license beans and format the file
</blockquote></details>

Done. Gaurav added a fix in BuildCleaner to exclude this.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/http/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pkcID4q6HxMGFRAv:-NS9-GvKC5etJGWyMtto:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/http/BUILD.bazel#L20)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Check all usages of ng-commons if you could use package targets
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/BUILD.bazel` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/45978#-NS2pv5X2fyOzS2h-1xw:-NS9-Hya7y5GijzYqaMb:bs8xt9h) ([raw file](https://github.com/harness/harness-core/blob/131e2402ab737802fc5374decae9be2f672787cb/930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/BUILD.bazel#L33)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Remove all usages of license beans. I think they are included for some new deps when you didn't regenerate the index. Check the `index generation` section in the [readme](https://github.com/harness/harness-core/blob/develop/tools/build-cleaner/README.md#internals) and see if regenerating index would help not get those deps
</blockquote></details>

Done. We added a fix in BuildCleaner to exclude this.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 111 of 186 files at r1, 47 of 47 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)* status: 192 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cvng/BUILD.bazel` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSArSDz3MP1z-V6aNUz:-NSArSDz3MP1z-V6aNV-:b-cknflz) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/io/harness/delegate/task/cvng/BUILD.bazel#L25)):*
> ```Starlark
>         "//srm-service/modules/cv-nextgen-service/contracts/delegate:module",
>         "@maven//:com_google_inject_guice",
>         "@maven//:io_harness_cv_data_collection_dsl",
> ```

Can you check this dep, it might be the same issue like license beans. Otherwise if this one is really needed it shouldn't be pulled from maven repo. 



_Code quote:_
```Starlark
io_harness_cv_data_collection_dsl
```
___
*[`930-delegate-tasks/src/main/java/io/harness/notification/senders/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSAtlFq0oz9sxImBvor:-NSAtlG--bkN2xAyOG91:b-vxsd3q) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/io/harness/notification/senders/BUILD.bazel#L27)):*
> ```Starlark
>         "@maven//:org_apache_commons_commons_lang3",
>         "@maven//:org_apache_httpcomponents_httpmime",
>         "@maven//:org_springframework_spring_core",
> ```

I know you haven't introduced this, but I think would be great if you could fix it since it's a simple fix (I'm not blocking so you can do as separate PR as well if it's easier for you). 
I think someone imported the wrong String constant for application/json which brings entire spring core in the mix (we don't want to use spring anywhere, we use dropwizard). Spring is used for building delegate only, but that's build time dep. 

Could you please remove that dep by replacing the usage in this file, with the one below:

https://github.com/harness/harness-core/blob/0334d4baa02e53a7a73ab5ea650db22b079e0ea7/930-delegate-tasks/src/main/java/io/harness/notification/senders/MSTeamsSenderImpl.java#L11

javax.ws.rs.core.MediaType#APPLICATION_JSON
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/external/comm/handlers/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSAvR-j6RcGOKTPHfSN:-NSAvR-j6RcGOKTPHfSO:be6lj9p) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/software/wings/helpers/ext/external/comm/handlers/BUILD.bazel#L27)):*
> ```Starlark
>         "@maven//:com_google_inject_guice",
>         "@maven//:com_sun_mail_javax_mail",
>         "@maven//:dev_morphia_morphia_core",
> ```

morphia is creeping in into delegate again. Double check if needed. 
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/BUILD.bazel` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSAvgC70xqvE1pqHwFa:-NSAvgC70xqvE1pqHwFb:bdar8vw) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/BUILD.bazel#L43)):*
> ```Starlark
>         "@maven//:com_squareup_retrofit2_converter_jaxb",
>         "@maven//:com_squareup_retrofit2_retrofit",
>         "@maven//:io_harness_cv_data_collection_dsl",
> ```

Check if there are more usages of this one

**Comment by Raghav-Murali** [comment]
trigger ut5, ut7

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)* status: 192 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cvng/BUILD.bazel` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSArSDz3MP1z-V6aNUz:-NSCflJq7oZKhYYUAzSF:b-y8dt17) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/io/harness/delegate/task/cvng/BUILD.bazel#L25)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Can you check this dep, it might be the same issue like license beans. Otherwise if this one is really needed it shouldn't be pulled from maven repo. 
</blockquote></details>

Good catch. Actually it is needed in all the 4 targets where it is being used.

It looks like there are some Harness libraries in Maven. That is how even the ng license beans was getting included. This library is also from `data-collection-dsl-0.43-RELEASE.jar` which is coming from maven and not from harness-core.
___
*[`930-delegate-tasks/src/main/java/io/harness/notification/senders/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSAtlFq0oz9sxImBvor:-NSCi2wb2xAjTAP6CcEA:b-uz0638) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/io/harness/notification/senders/BUILD.bazel#L27)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I know you haven't introduced this, but I think would be great if you could fix it since it's a simple fix (I'm not blocking so you can do as separate PR as well if it's easier for you). 
I think someone imported the wrong String constant for application/json which brings entire spring core in the mix (we don't want to use spring anywhere, we use dropwizard). Spring is used for building delegate only, but that's build time dep. 

Could you please remove that dep by replacing the usage in this file, with the one below:

https://github.com/harness/harness-core/blob/0334d4baa02e53a7a73ab5ea650db22b079e0ea7/930-delegate-tasks/src/main/java/io/harness/notification/senders/MSTeamsSenderImpl.java#L11

javax.ws.rs.core.MediaType#APPLICATION_JSON
</blockquote></details>

Sure, will update it.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/external/comm/handlers/BUILD.bazel` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSAvR-j6RcGOKTPHfSN:-NSCkSYj6vJ_OHQxxG1T:b8khh1e) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/software/wings/helpers/ext/external/comm/handlers/BUILD.bazel#L27)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

morphia is creeping in into delegate again. Double check if needed. 
</blockquote></details>

Ah, yes. Thanks



_Code quote:_
```Starlark
dev_morphia_morphia_core
```
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/BUILD.bazel` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSAvgC70xqvE1pqHwFa:-NSCkVU-6b7zA50czhIX:b5pu6gj) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/BUILD.bazel#L43)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Check if there are more usages of this one
</blockquote></details>

Yup, checked and updated it. Its needed at 2 places.

**Review by gn-harness — APPROVED** [review]

**Review by gn-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)* status: 193 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45978)* status: 193 file(s) to review. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/cvng/BUILD.bazel` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/45978#-NSArSDz3MP1z-V6aNUz:-NSDaaQ_9YNQaBGoUIf6:bkuvnnq) ([raw file](https://github.com/harness/harness-core/blob/d2a4f6e47bd7b1e1fbb4be2e84793fcf8321f6f8/930-delegate-tasks/src/main/java/io/harness/delegate/task/cvng/BUILD.bazel#L25)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Good catch. Actually it is needed in the below 2 targets - 

930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/mappers/BUILD.bazel
930-delegate-tasks/src/main/java/software/wings/helpers/ext/nexus/BUILD.bazel

But was spuriously added at 2 other places which I have removed.

So looks like there are some Harness libraries in Maven. That is how even the ng license beans was getting included. This library is also from `data-collection-dsl-0.43-RELEASE.jar` which is coming from maven and not from harness-core.
</blockquote></details>

Hmm, that usage seems strange. Lets resolve for now and figure out later if this is the proper usage of that dep.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Pull request merged**
