### PR TITLE
fix: [CDS-59080]: fixing error message for Invalid certificate in K8s cloud provider

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Improving error message and differentiating between CA and Client Certificate.
Screenshot 2023-05-10 at 1 10 27 AM
Screenshot 2023-05-10 at 1 09 53 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47559)

### CODE REVIEW

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47559)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/47559#-NV-btDQCWU9U549DaAa:-NV-btDQCWU9U549DaAb:be0tfj) ([raw file](https://github.com/harness/harness-core/blob/cb232a56a6eeae3e80bbbcbcc0d461a941a38ad9/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L172)):*
> ```Java
>     if (isNotEmpty(kubernetesConfig.getCaCert()) && isNotEmpty(kubernetesConfig.getClientCert())) {
>       return KubernetesApiClientRuntimeException.KubernetesCertificateType.BOTH_CA_AND_CLIENT_CERTIFICATE;
>     } else if (isNotEmpty(kubernetesConfig.getCaCert())) {
> ```

nested else-ifs are not needed, we can just do 
if (..) return
if (..) return
if (..) return
return
___
*[`980-commons/src/main/java/io/harness/exception/runtime/KubernetesApiClientRuntimeException.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/47559#-NV-bZo_0LqYHY1Co6BU:-NV-bZo_0LqYHY1Co6BV:b-qi2jke) ([raw file](https://github.com/harness/harness-core/blob/cb232a56a6eeae3e80bbbcbcc0d461a941a38ad9/980-commons/src/main/java/io/harness/exception/runtime/KubernetesApiClientRuntimeException.java#L19)):*
> ```Java
> @OwnedBy(CDP)
> public class KubernetesApiClientRuntimeException extends RuntimeException {
>   public enum KubernetesCertificateType {
> ```

we should move this enum somewhere else

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47559)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/47559#-NV-btDQCWU9U549DaAa:-NV0cUzH2dFNmK3WWf_A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb232a56a6eeae3e80bbbcbcc0d461a941a38ad9/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L172)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nested else-ifs are not needed, we can just do 
if (..) return
if (..) return
if (..) return
return

</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/runtime/KubernetesApiClientRuntimeException.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/47559#-NV-bZo_0LqYHY1Co6BU:-NV0cVkzAOLl22i4SFye:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb232a56a6eeae3e80bbbcbcc0d461a941a38ad9/980-commons/src/main/java/io/harness/exception/runtime/KubernetesApiClientRuntimeException.java#L19)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

we should move this enum somewhere else
</blockquote></details>

Done.

**Comment by GoelPratyush99** [comment]
trigger uts

**Review by thisrohangupta — APPROVED** [review]
Looks good to me, error message makes sense.

**Comment by GoelPratyush99** [comment]
trigger ut7

**Review by abhinavsingh1196 — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Pull request merged**
