### PR TITLE
feat: [CDS-51858]: Adds POJOs for Cluster Overrides

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Adds POJOs for Cluster Overrides

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47757)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47757)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/47757#-NVY-ig00G15qVh41Gxs:-NVY-ig00G15qVh41Gxt:b-4ldga7) ([raw file](https://github.com/harness/harness-core/blob/9af78db872dfd2660966fae7a50cbdb6d72e048f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java#L76)):*
> ```Java
>   @EntityIdentifier String identifier;
>   @Trimmed String infraIdentifier;
>   @Trimmed String clusterIdentifier;
> ```

How do we get scope of cluster? Is it inferred from environment? If yes, can add this comment in the code.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterGlobalOverridesConfig.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/47757#-NVY-rUWDLcHN2IcN38r:-NVY-rUWDLcHN2IcN38s:b-nk55z9) ([raw file](https://github.com/harness/harness-core/blob/9af78db872dfd2660966fae7a50cbdb6d72e048f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterGlobalOverridesConfig.java#L36)):*
> ```Java
> public class ClusterGlobalOverridesConfig extends ServiceOverridesConfig {
>   @NonNull String environmentRef;
>   String clusterIdentifier;
> ```

can clusterId be null? Doesn't sound correct to me.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterSpecificOverridesConfig.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/47757#-NVY-wZJ8UV6RBkhH_h9:-NVY-wZJ8UV6RBkhH_hA:b-goly0d) ([raw file](https://github.com/harness/harness-core/blob/9af78db872dfd2660966fae7a50cbdb6d72e048f/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterSpecificOverridesConfig.java#L37)):*
> ```Java
>   @NonNull String environmentRef;
>   @NonNull String serviceRef;
>   String clusterIdentifier;
> ```

same, nonnull for clusterId

**Review by mankrit-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47757)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/47757#-NVY-ig00G15qVh41Gxs:-NVYh7x2DBBveJfjGOv8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1024f4b91a298d800d988fcdd5087e47e300264/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/NGServiceOverridesEntity.java#L76)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

How do we get scope of cluster? Is it inferred from environment? If yes, can add this comment in the code.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterGlobalOverridesConfig.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/47757#-NVY-rUWDLcHN2IcN38r:-NVYh8Ji7sRpwMT7vElv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1024f4b91a298d800d988fcdd5087e47e300264/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterGlobalOverridesConfig.java#L36)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can clusterId be null? Doesn't sound correct to me.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterSpecificOverridesConfig.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/47757#-NVY-wZJ8UV6RBkhH_h9:-NVYh8cNBENT3Xnu2ULq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1024f4b91a298d800d988fcdd5087e47e300264/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/cluster/ClusterSpecificOverridesConfig.java#L37)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

same, nonnull for clusterId
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47757)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by mankrit-singh** [comment]
trigger uts

**Comment by mankrit-singh** [comment]
trigger review

**Pull request merged**
