### PR TITLE
[fix]: [CDS-38525]: added message and execution url for workflow

### PR DESCRIPTION
**Pull request by prabu-kr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34236)

### CODE REVIEW

**Review by puthrayaharness — APPROVED** [review]

**Review by poojaSinghal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34236)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6402 at r2](https://reviewable.io/reviews/harness/harness-core/34236#-N5-7ux97fr_7pKC-IXV:-N5-7ux97fr_7pKC-IXW:b-b9zttg) ([raw file](https://github.com/harness/harness-core/blob/14e835cc334a5149c1a4d97e898e89d97011bdf1/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6402)):*
> ```Java
>                 .stream()
>                 // Getting approval data only from states paused on the same step
>                 .filter(ad -> currentApprovalData.getApprovalStateIdentifier().equals(ad.getApprovalStateIdentifier()))
> ```

approvalStateIdentifier will be null for approvals which are already in paused state when your changes are deployed. We should handle and test this carefully for such cases. 
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6432 at r2](https://reviewable.io/reviews/harness/harness-core/34236#-N5-83nZB-PWhSHsUHpc:-N5-83nZB-PWhSHsUHpd:bcur1ci) ([raw file](https://github.com/harness/harness-core/blob/14e835cc334a5149c1a4d97e898e89d97011bdf1/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6432)):*
> ```Java
>     String executionUrl = "";
>     WorkflowExecution workflowExecution = getWorkflowExecution(appId, workflowExecutionId);
>     if (baseUrl != null) {
> ```

we should test these for vanityUrls and on prem env.

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34236)* status: 1 change requests. 2. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6402 at r2](https://reviewable.io/reviews/harness/harness-core/34236#-N5-7ux97fr_7pKC-IXV:-N5-YMtT3V6esvzSPW1A:b-8k9mq6) ([raw file](https://github.com/harness/harness-core/blob/14e835cc334a5149c1a4d97e898e89d97011bdf1/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6402)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

approvalStateIdentifier will be null for approvals which are already in paused state when your changes are deployed. We should handle and test this carefully for such cases. 
</blockquote></details>

It's a transient field and I am setting it only in the above function being called: fetchApprovalStateExecutionsDataFromWorkflowExecution. So even for existing executions, since the above function will set it and return, it won't be null



_Code quote:_
```Java
fetchApprovalStateExecutionsDataFromWorkflowExecution
```
___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 6432 at r2](https://reviewable.io/reviews/harness/harness-core/34236#-N5-83nZB-PWhSHsUHpc:-N5-Z19N8BgPZrZxYYUC:b98mk8t) ([raw file](https://github.com/harness/harness-core/blob/14e835cc334a5149c1a4d97e898e89d97011bdf1/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L6432)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

we should test these for vanityUrls and on prem env. 
</blockquote></details>

Vanity url can only be tested when this gets deployed there right? How do we handle on-prem? Do we have a test setup?

**Review by poojaSinghal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34236)* status: :shipit: complete! ✓

**Comment by prabu-kr** [comment]
trigger messagecheck

**Comment by prabu-kr** [comment]
trigger messagecheck

**Pull request merged**
