### PR TITLE
[techdebt]: [PIE-6373]: Refactor the validation calls in PmsPipelineServiceHelper

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
Testing: Ran locally

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40167)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40167)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 367 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv0LfEAlU5XXSBdLWV:-NGv0LfF9KGyOsX1svjr:b-8vnei7) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L367)):*
> ```Java
>     bind(PMSPipelineService.class).to(PMSPipelineServiceImpl.class);
>     bind(PmsExecutionSummaryService.class).to(PmsExecutionSummaryServiceImpl.class);
>     bind(PipelineSettingsService.class).to(PipelineSettingsServiceImpl.class);
> ```

why this binding is created right now only and not earlier? Please add for governance service and its impl



_Code quote:_
```Java
bind(PipelineSettingsService.class).to(PipelineSettingsServiceImpl.class);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv1Pb3E9aGtHa1greo:-NGv1Pb3E9aGtHa1grep:bsdnss6) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L261)):*
> ```Java
>     // Apply all the templateRefs(if any) then check for schema validation.
>     TemplateMergeResponseDTO templateMergeResponseDTO =
>         pipelineTemplateHelper.resolveTemplateRefsInPipeline(pipelineEntity, checkAgainstOPAPolicies);
> ```

why we are not passing this flag directly to governance validation? or remove this flag from passing from top up



_Code quote:_
```Java
checkAgainstOPAPolicies
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv0hwg9bkALkjT_brm:-NGv0hwg9bkALkjT_brn:b-hjb3tf) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L274)):*
> ```Java
>     pipelineEntity.setTemplateModules(templateModuleInfo);
> 
>     pipelineValidationService.validateYaml(accountId, orgIdentifier, projectIdentifier, resolveTemplateRefsInPipeline);
> ```

why we moved yaml validation down?



_Code quote:_
```Java
pipelineValidationService.validateYaml(accountId, orgIdentifier, projectIdentifier, resolveTemplateRefsInPipeline);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv0mUf8un4Yt0h_n7S:-NGv0mUf8un4Yt0h_n7T:bjrtd1i) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L14)):*
> ```Java
> 
>   @Override
>   public boolean validateYaml(
> ```

currently its doing only schema validation?

In next phase are you creating methods where different validation will be added to this file?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 261 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv1Pb3E9aGtHa1greo:-NGvC288AgbQjjRAKvHw:bs21tup) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L261)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are not passing this flag directly to governance validation? or remove this flag from passing from top up
</blockquote></details>

I will remove this in my upcoming PR's

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 274 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv0hwg9bkALkjT_brm:-NGvC959Cap7sP_Ktquj:b7x926y) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L274)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we moved yaml validation down?
</blockquote></details>

I just moved it casually, will get rid of the above things altogether.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv0mUf8un4Yt0h_n7S:-NGvCJZx-7MUgyh6N4P_:bb77ueg) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/PipelineValidationServiceImpl.java#L14)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

currently its doing only schema validation?

In next phase are you creating methods where different validation will be added to this file?
</blockquote></details>

Yes

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 367 at r2](https://reviewable.io/reviews/harness/harness-core/40167#-NGv0LfEAlU5XXSBdLWV:-NGvKu-X8fboVgmAW_2R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/27e38ced8a673ee19af0db0ee343cea4e8889295/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L367)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this binding is created right now only and not earlier? Please add for governance service and its impl
</blockquote></details>

Done.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 9 of 13 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40167)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 9 of 13 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40167)* status: 7 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40167)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
