### PR TITLE
feat: [CDP-20290]: changes to add Chart Version/Artifact details unde…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…r Service Page.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30119)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30119)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30119)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java, line 19 at r2](https://reviewable.io/reviews/harness/harness-core/30119#-Mu9lXnB6dcnjoWOyeYU:-Mu9lXnB6dcnjoWOyeYV:b-rkva9h) ([raw file](https://github.com/harness/harness-core/blob/038a5999b1efcea557f0f73ef2369662074e1824/126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java#L19)):*
> ```Java
> @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", include = JsonTypeInfo.As.EXISTING_PROPERTY)
> @JsonSubTypes({
>   @JsonSubTypes.Type(value = K8sInstanceInfoDTO.class, name = "K8S")
> ```

Shouldn't it be K8s? (S lowercase)

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30119)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java, line 19 at r2](https://reviewable.io/reviews/harness/harness-core/30119#-Mu9lXnB6dcnjoWOyeYU:-Mu9pJJQ5LrXVLGh0-bP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/038a5999b1efcea557f0f73ef2369662074e1824/126-instance/src/main/java/io/harness/dtos/instanceinfo/InstanceInfoDTO.java#L19)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't it be K8s? (S lowercase)
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30119)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30119)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30119#-:-MuC6Y8hAJDIsZYebTia:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
