### PR TITLE
fix: [DEL-5976]: Add referenceFalse kryo serializer option to perpetual task

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes

Summary:
-Adding referenceFalseKryoSerializer option for PT context calls and PT response call 

Test Performed
- Connector creation, verified PT getting created, pt running and showing response correctly
- Sanity k8 end to end flow
- NG pipeline execution 
- Sanity with older version delegate

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44775)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`260-delegate/config-delegate.yml` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/44775#-NQX-AgP5YwQmG3txzZY:-NQX-AgP5YwQmG3txzZZ:b-5z49pc) ([raw file](https://github.com/harness/harness-core/blob/1cc6a64d14aeb70768d5a75723d455c014c6a596/260-delegate/config-delegate.yml#L19)):*
> ```YAML
> clientToolsDownloadDisabled: false
> installClientToolsInBackground: true
> isLocalNgDelegate: true
> ```

accidental?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/AsgInstanceSyncPerpetualTaskExecutorNg.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/44775#-NQXuXjwD8-ZbZUw2K0m:-NQXuXjx0xU3LUn96-np:bj712w4) ([raw file](https://github.com/harness/harness-core/blob/1cc6a64d14aeb70768d5a75723d455c014c6a596/260-delegate/src/main/java/io/harness/perpetualtask/AsgInstanceSyncPerpetualTaskExecutorNg.java#L46)):*
> ```Java
> public class AsgInstanceSyncPerpetualTaskExecutorNg implements PerpetualTaskExecutor {
>   private static final String SUCCESS_RESPONSE_MSG = "success";
>   @Inject private KryoSerializer kryoSerializer;
> ```

should we remove kryoSerializer field?

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/AwsCodeDeployInstanceSyncExecutor.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/44775#-NQXufgi44YHYpi2nejp:-NQXufgi44YHYpi2nejq:b-osdcyb) ([raw file](https://github.com/harness/harness-core/blob/1cc6a64d14aeb70768d5a75723d455c014c6a596/260-delegate/src/main/java/io/harness/perpetualtask/AwsCodeDeployInstanceSyncExecutor.java#L43)):*
> ```Java
>   @Inject private AwsEc2HelperServiceDelegate ec2ServiceDelegate;
>   @Inject private DelegateAgentManagerClient delegateAgentManagerClient;
>   @Inject private KryoSerializer kryoSerializer;
> ```

same here, consider removing kryoSerializer if not used

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/AwsCodeDeployInstanceSyncExecutor.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/44775#-NQXufgi44YHYpi2nejp:-NQYmURm07joBJXCTQH4:b3ztbyx) ([raw file](https://github.com/harness/harness-core/blob/1cc6a64d14aeb70768d5a75723d455c014c6a596/260-delegate/src/main/java/io/harness/perpetualtask/AwsCodeDeployInstanceSyncExecutor.java#L43)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

same here, consider removing kryoSerializer if not used
</blockquote></details>

removed all usages from delegate side code

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/perpetualtask/AsgInstanceSyncPerpetualTaskExecutorNg.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/44775#-NQXuXjwD8-ZbZUw2K0m:-NQYmlkh0joe1Otb6-4h:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1cc6a64d14aeb70768d5a75723d455c014c6a596/260-delegate/src/main/java/io/harness/perpetualtask/AsgInstanceSyncPerpetualTaskExecutorNg.java#L46)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

should we remove kryoSerializer field?
</blockquote></details>

done

**Comment by jennyjames21** [comment]
*[`260-delegate/config-delegate.yml` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/44775#-NQX-AgP5YwQmG3txzZY:-NQYmrYt0J0IyP9HZKkk:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/1cc6a64d14aeb70768d5a75723d455c014c6a596/260-delegate/config-delegate.yml#L19)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

accidental?
</blockquote></details>

updated

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 52 of 108 files at r1, 15 of 22 files at r2, 4 of 7 files at r3, 41 of 41 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44775)* status: Waiting on team(s): del-team.

**Review by AbhijithHarness — DISMISSED** [review]
> Reviewed 2 of 41 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44775)* status: 10 file(s) to review.

**Comment by jennyjames21** [comment]
image
image
image

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 6 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44775)* status: 11 file(s) to review. 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 8 of 10 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44775)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44775)* status: :shipit: complete! ✓

**Pull request merged**
