### PR TITLE
[feat]: [cds-41322]: Disabled deletion of templates when referenced a…

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
…nywhere

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36604)

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by prabu-kr — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 502 at r2](https://reviewable.io/reviews/harness/harness-core/36604#-NAJkci33aewTAg8HtcG:-NAJkci33aewTAg8HtcH:b-avzc9u) ([raw file](https://github.com/harness/harness-core/blob/06bf3e169460182c29161cc65f8d165e337aa57b/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L502)):*
> ```Java
>   }
> 
>   private void checkThatTheTemplateIsNotUsedByOthers(TemplateEntity templateToDelete) {
> ```

This check should be in service layer.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 512 at r2](https://reviewable.io/reviews/harness/harness-core/36604#-NAJgZ2O8gCq9ZGkTfLw:-NAJgZ2O8gCq9ZGkTfLx:b-6ky1wv) ([raw file](https://github.com/harness/harness-core/blob/06bf3e169460182c29161cc65f8d165e337aa57b/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L512)):*
> ```Java
>     String referredEntityFQN = identifierRef.getFullyQualifiedName() + "/" + templateToDelete.getVersionLabel() + "/";
>     try {
>       isEntityReferenced = execute(entitySetupUsageClient.isEntityReferenced(
> ```

Nit: always have class name before static methods to know where it's called from. Else user has to check imports for the same.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 502 at r2](https://reviewable.io/reviews/harness/harness-core/36604#-NAJkci33aewTAg8HtcG:-NAJwkRNAu7BV4yenF4a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06bf3e169460182c29161cc65f8d165e337aa57b/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L502)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This check should be in service layer.
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 508 at r3](https://reviewable.io/reviews/harness/harness-core/36604#-NAOfVMZ94PKVE2j2-X6:-NAOfVMZ94PKVE2j2-X7:banhwjl) ([raw file](https://github.com/harness/harness-core/blob/81dd3a8f92c4912e686a7fd686b549fdc285c2d6/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L508)):*
> ```Java
>       log.info("Encountered exception while requesting the Entity Reference records of [{}], with exception",
>           templateToDelete.getIdentifier(), ex);
>       throw new UnexpectedException("Error while deleting the connector");
> ```

Error message needs to be changed here.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 508 at r3](https://reviewable.io/reviews/harness/harness-core/36604#-NAOfVMZ94PKVE2j2-X6:-NAOh5_yEQnsPNXMJsNg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81dd3a8f92c4912e686a7fd686b549fdc285c2d6/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L508)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Error message needs to be changed here.
</blockquote></details>

Done.



_Code quote:_
```Java
heckThatTheTemplateIsNotUsedByOthers
```

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 508 at r3](https://reviewable.io/reviews/harness/harness-core/36604#-NAOfVMZ94PKVE2j2-X6:-NAc4RBK-Gpl6t3zHFtS:bp2e1up) ([raw file](https://github.com/harness/harness-core/blob/81dd3a8f92c4912e686a7fd686b549fdc285c2d6/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L508)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have better error message then error while deleting the template, this error message customer will see.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 508 at r3](https://reviewable.io/reviews/harness/harness-core/36604#-NAOfVMZ94PKVE2j2-X6:-NAcX4ocB1r8EG5TvVKD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/81dd3a8f92c4912e686a7fd686b549fdc285c2d6/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L508)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Have better error message then error while deleting the template, this error message customer will see.
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 5 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36604)* status: :shipit: complete! ✓

**Pull request merged**
