### PR TITLE
feat: [CDS-73887]: Return the evaluated expression for given yaml

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes

"mapExpression": {
            "pipeline.variables.var2+<+pipeline.variables.var1>": {
                "resolvedValue": "\"test_pipeline\"",
                "fqn": "pipeline.variables.var2",
                "originalExpression": "<+pipeline.variables.var1>",
                "resolvedByYaml": true
            },
            "pipeline.stages.cs.spec.execution.steps.ShellScript_2.spec.source.spec.script+<+pipeline.stages.cs.spec.execution.steps.ShellScript_1.output.outputVariables.output>": {
                "resolvedValue": "\"prashant\"",
                "fqn": "pipeline.stages.cs.spec.execution.steps.ShellScript_2.spec.source.spec.script",
                "originalExpression": "<+pipeline.stages.cs.spec.execution.steps.ShellScript_1.output.outputVariables.output>",
                "resolvedByYaml": false
            },
            "pipeline.stages.stage2.spec.execution.steps.ShellScript_1.spec.source.spec.script+<+pipeline.stages.cs.name>": {
                "resolvedValue": "\"cs\"",
                "fqn": "pipeline.stages.stage2.spec.execution.steps.ShellScript_1.spec.source.spec.script",
                "originalExpression": "<+pipeline.stages.cs.name>",
                "resolvedByYaml": true
            },
            "pipeline.stages.cs.spec.execution.steps.ShellScript_2.spec.source.spec.script+<+execution.steps.ShellScript_1.name>": {
                "resolvedValue": "\"ShellScript_1\"",
                "fqn": "pipeline.stages.cs.spec.execution.steps.ShellScript_2.spec.source.spec.script",
                "originalExpression": "<+execution.steps.ShellScript_1.name>",
                "resolvedByYaml": true
            },
            "pipeline.stages.cs.spec.execution.steps.ShellScript_2.spec.source.spec.script+<+pipeline.executionId>": {
                "resolvedValue": "\"6_OHcJLUS1W5x28tm6XcRw\"",
                "fqn": "pipeline.stages.cs.spec.execution.steps.ShellScript_2.spec.source.spec.script",
                "originalExpression": "<+pipeline.executionId>",
                "resolvedByYaml": false
            },
            "pipeline.variables.var1+<+pipeline.identifier>": {
                "resolvedValue": "\"test_pipeline\"",
                "fqn": "pipeline.variables.var1",
                "originalExpression": "<+pipeline.identifier>",
                "resolvedByYaml": true
            },
            "pipeline.stages.stage2.spec.execution.steps.ShellScript_1.spec.source.spec.script+<+pipeline.stages.cs.spec.execution.steps.ShellScript_1.name>": {
                "resolvedValue": "\"ShellScript_1\"",
                "fqn": "pipeline.stages.stage2.spec.execution.steps.ShellScript_1.spec.source.spec.script",
                "originalExpression": "<+pipeline.stages.cs.spec.execution.steps.ShellScript_1.name>",
                "resolvedByYaml": true
            }
        }
        
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50629)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java` line 46 at r6](https://reviewable.io/reviews/harness/harness-core/50629#-N_gSLaM0UxF_i66CcnZ:-N_gSLaM0UxF_i66Ccn_:b-g134rc) ([raw file](https://github.com/harness/harness-core/blob/d0353de06e822248e518b3896bf7119f12729864/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java#L46)):*
> ```Java
>   }
> 
>   public Map<String, Object> generateYamlMapWithFqnExpression(String yaml) {
> ```

nit: let's add a comment a to what it does.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/YamlExpressionEvaluator.java` line 43 at r6](https://reviewable.io/reviews/harness/harness-core/50629#-N_gSXkxDjsp4WkiVe8U:-N_gSXkxDjsp4WkiVe8V:b64pz6g) ([raw file](https://github.com/harness/harness-core/blob/d0353de06e822248e518b3896bf7119f12729864/pipeline-service/service/src/main/java/io/harness/pms/expressions/YamlExpressionEvaluator.java#L43)):*
> ```Java
>   protected List<String> fetchPrefixes() {
>     ImmutableList.Builder<String> listBuilder = ImmutableList.builder();
>     return listBuilder.add("yaml").build();
> ```

note for other reviewers
this we are doing so as to prepend all expressions with yaml and then using yamlEvaluator to resolve.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java` line 156 at r6](https://reviewable.io/reviews/harness/harness-core/50629#-N_gTBch7kLxCn3wNrfx:-N_gTBch7kLxCn3wNrfy:b-ffeo0i) ([raw file](https://github.com/harness/harness-core/blob/d0353de06e822248e518b3896bf7119f12729864/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExpressionEvaluatorServiceImpl.java#L156)):*
> ```Java
>   This will return <+pipeline.stages.cs.spec.execution.steps.ShellScript_1.name>
>    */
>   private static String getExpressionForYamlEvaluator(String fqn, String expression) {
> ```

Let's add proper uts for this in next PR.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50629)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50629)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger review

**Comment by prashantsharma04** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50629)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger ut3

**Comment by prashantsharma04** [comment]
trigger ut2

**Comment by prashantsharma04** [comment]
trigger ut0

**Comment by prashantsharma04** [comment]
trigger ut0

**Comment by shalini-agr** [comment]
trigger ut0, ut1, ut2, ut3, ut4

**Comment by prashantsharma04** [comment]
trigger review

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50629)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]

**Pull request merged**
