### PR TITLE
[fix]: [PL-31422]: Fixing delegateTask.calcDescription call for task data v2

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
After migrating delegate task request flow to v2 Cloud Formation pipelines are failing with UNKNOWN_ERROR. There is NPE 

logs
```
io.harness.exception.WingsException: UNKNOWN_ERROR
	at software.wings.sm.StateMachineExecutor.startStateExecution(StateMachineExecutor.java:658)
	at software.wings.sm.StateMachineExecutor.startExecution(StateMachineExecutor.java:617)
	at software.wings.sm.StateMachineExecutor$SmExecutionDispatcher.run(StateMachineExecutor.java:2626)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at io.harness.beans.DelegateTask.calcDescription(DelegateTask.java:224)
	at software.wings.sm.State.appendDelegateTaskDetails(State.java:374)
	at software.wings.sm.states.provision.CloudFormationCreateStackState.queueFetchFileTask(CloudFormationCreateStackState.java:400)
	at software.wings.sm.states.provision.CloudFormationCreateStackState.buildAndQueueFetchS3FilesTask(CloudFormationCreateStackState.java:394)
	at software.wings.sm.states.provision.CloudFormationCreateStackState.buildAndQueueDelegateTask(CloudFormationCreateStackState.java:224)
	at software.wings.sm.states.provision.CloudFormationState.executeInternal(CloudFormationState.java:235)
	at software.wings.sm.states.provision.CloudFormationCreateStackState.executeInternal(CloudFormationCreateStackState.java:192)
	at software.wings.sm.states.provision.CloudFormationState.execute(CloudFormationState.java:162)
	at software.wings.sm.StateMachineExecutor.getExecutionResponseWithAdvise(StateMachineExecutor.java:707)
	at software.wings.sm.StateMachineExecutor.startStateExecution(StateMachineExecutor.java:649)
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43758)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43758)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43758#-:-NNqLWDH4fgB2Jy6gkcP:bnfp4nl)* status: :shipit: complete! ✓

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by AnshuH** [comment]
trigger ti1

**Comment by AnshuH** [comment]
trigger ti1

**Pull request closed without merging**
