### PR TITLE
fix: [CDS-86561]: Reverts PR 56631 - adds validation for branch name, relevant error message for remote entity update and create

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
Reverts harness/harness-core#56631

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56873)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56873)* status: 2 file(s) to review.

**Comment by sandeshsalunkhegh** [comment]
trigger ut0, review, messagecheck, gitleaks

**Comment by sandeshsalunkhegh** [comment]
trigger gitleaks, messagecheck

**Comment by sandeshsalunkhegh** [comment]
trigger messagecheck

**Comment by sandeshsalunkhegh** [comment]
trigger gitleaks, messagecheck

**Comment by sandeshsalunkhegh** [comment]
trigger messagecheck

**Pull request merged**
