### PR TITLE
[fix]: [CDS-36823]: QA hf AddClusterNameInGcpTypeInstanceMigration

### PR DESCRIPTION
**Pull request by tchaurasiya**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33187)

### CODE REVIEW

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33187)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/33187#-N2BrV8qBlZ9bWq685io:-N2BrV8qBlZ9bWq685ip:bmmp5oa) ([raw file](https://github.com/harness/harness-core/blob/f4c2414d9434a2eefc0c2c23f32f686766f95b9f/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L45)):*
> ```Java
>   public void migrate() {
>     log.info("Running AddClusterNameInGcpTypeInstanceMigration");
>     //    List<Account> allAccounts = accountService.listAllAccountWithDefaultsWithoutLicenseInfo();
> ```

remove commented out code, or add some relevant documentation if you need the commented code to be present.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/33187#-N2Brcq5B4Ia74ZYIxqp:-N2Brcq5B4Ia74ZYIxqq:bklybrm) ([raw file](https://github.com/harness/harness-core/blob/f4c2414d9434a2eefc0c2c23f32f686766f95b9f/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L46)):*
> ```Java
>     log.info("Running AddClusterNameInGcpTypeInstanceMigration");
>     //    List<Account> allAccounts = accountService.listAllAccountWithDefaultsWithoutLicenseInfo();
>     List<String> firstReleaseConsideredAccount = Collections.singletonList("8e_GD3EARMmLSjFpszuwzw");
> ```

add a comment with the human readable account name as well

**Review by shubham-in10se — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33187)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/33187#-N2BrV8qBlZ9bWq685io:-N2Fcz3-6jQxZ-ZUctjm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4c2414d9434a2eefc0c2c23f32f686766f95b9f/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L45)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

remove commented out code, or add some relevant documentation if you need the commented code to be present.
</blockquote></details>

Done.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33187)* status: :shipit: complete! ✓

**Pull request merged**
