### PR TITLE
[feat]: [PIE-3794]: Onboard Input Sets to simplified Git Experience

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IR1L9Cmj_cvq30PuI:-N3IR1LA0OYRPFABBzJd:bcyqmjt) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L315)):*
> ```Java
>       List<String> stageIdentifiers) {
>     String pipelineYaml = getPipelineYaml(
>         accountId, orgIdentifier, projectIdentifier, pipelineIdentifier, pipelineBranch, pipelineRepoID, false);
> ```

why we will keep this flag as false



_Code quote:_
```Java
checkForStoreType
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Im-DPEMtwoJGj8AyN:-N3Im-DPEMtwoJGj8AyO:bllpes8) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java#L170)):*
> ```Java
>         ? EntityGitDetailsMapper.mapEntityGitDetails(entity)
>         : entity.getStoreType() == StoreType.REMOTE ? GitAwareContextHelper.getEntityGitDetails(entity)
>                                                     : null;
> ```

Can you the get helper method which you created 



_Code quote:_
```Java
    EntityGitDetails entityGitDetails = entity.getStoreType() == null
        ? EntityGitDetailsMapper.mapEntityGitDetails(entity)
        : entity.getStoreType() == StoreType.REMOTE ? GitAwareContextHelper.getEntityGitDetails(entity)
                                                    : null;
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Imidq0FtXDsXtWX6s:-N3Imidq0FtXDsXtWX6t:b-h2svxc) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L174)):*
> ```Java
> 
>     if (inputSetEntity.getStoreType() == StoreType.REMOTE) {
>       // todo: remove dependency of validateAndMergeHelper on inputSetService and add this validation into service layer
> ```

Can we make this TODO is move the business logic to service layer, and in service layer we will make use of helpers as required.



_Code quote:_
```Java
// todo: remove dependency of validateAndMergeHelper on inputSetService and add this validation into service layer
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 225 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Imuf7-vOpzCAyNqLR:-N3Imuf7-vOpzCAyNqLS:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L225)):*
> ```Java
> 
>     if (inputSetEntity.getStoreType() == StoreType.REMOTE) {
>       // todo: remove dependency of validateAndMergeHelper on inputSetService and add this validation into service layer
> ```

Same here



_Code quote:_
```Java
// todo: remove dependency of validateAndMergeHelper on inputSetService and add this validation into service layer
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Iqvm178sX_wVnnkHn:-N3Iqvm178sX_wVnnkHo:b-xnau2m) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L114)):*
> ```Java
>       entityToSave.setStoreType(StoreType.INLINE);
>       InputSetEntity inputSetEntity = mongoTemplate.save(entityToSave);
>       functor.get();
> ```

this you can remove and after else you have the same instructions, you can use and use them in transaction



_Code quote:_
```Java
      InputSetEntity inputSetEntity = mongoTemplate.save(entityToSave);
      functor.get();
      return inputSetEntity;
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Ir2ND8VS7Gd1re9hH:-N3Ir2ND8VS7Gd1re9hI:btf30bs) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L136)):*
> ```Java
>     InputSetEntity savedInputSetEntity = mongoTemplate.save(entityToSave);
>     functor.get();
>     return savedInputSetEntity;
> ```

call this in transaction



_Code quote:_
```Java
    InputSetEntity savedInputSetEntity = mongoTemplate.save(entityToSave);
    functor.get();
    return savedInputSetEntity;
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 171 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IrDlbBe9wPEwPJwNe:-N3IrDlbBe9wPEwPJwNf:b-h3ym1z) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L171)):*
> ```Java
>                             .is(pipelineIdentifier)
>                             .and(InputSetEntityKeys.identifier)
>                             .is(identifier);
> ```

create smaller getCriteria method? maybe in helper



_Code quote:_
```Java
    Criteria criteria = Criteria.where(InputSetEntityKeys.deleted)
                            .is(!notDeleted)
                            .and(InputSetEntityKeys.accountId)
                            .is(accountId)
                            .and(InputSetEntityKeys.orgIdentifier)
                            .is(orgIdentifier)
                            .and(InputSetEntityKeys.projectIdentifier)
                            .is(projectIdentifier)
                            .and(InputSetEntityKeys.pipelineIdentifier)
                            .is(pipelineIdentifier)
                            .and(InputSetEntityKeys.identifier)
                            .is(identifier);
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 243 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IrRQuEw9IUJ6Cx1Vx:-N3IrRQuEw9IUJ6Cx1Vy:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L243)):*
> ```Java
>                             .is(entityToUpdate.getPipelineIdentifier())
>                             .and(InputSetEntityKeys.identifier)
>                             .is(entityToUpdate.getIdentifier());
> ```

same for this



_Code quote:_
```Java
    Criteria criteria = Criteria.where(InputSetEntityKeys.deleted)
                            .is(false)
                            .and(InputSetEntityKeys.accountId)
                            .is(entityToUpdate.getAccountId())
                            .and(InputSetEntityKeys.orgIdentifier)
                            .is(entityToUpdate.getOrgIdentifier())
                            .and(InputSetEntityKeys.projectIdentifier)
                            .is(entityToUpdate.getProjectIdentifier())
                            .and(InputSetEntityKeys.pipelineIdentifier)
                            .is(entityToUpdate.getPipelineIdentifier())
                            .and(InputSetEntityKeys.identifier)
                            .is(entityToUpdate.getIdentifier());
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IsYZpEm7uINPZTREP:-N3IsYZpEm7uINPZTREQ:b-10egp) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L267)):*
> ```Java
>           entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
>       return updatedEntity;
>     }
> ```

non git sync, and audits, should be done in transaction



_Code quote:_
```Java
    if (updatedEntity.getStoreType() == StoreType.INLINE) {
      outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(),
          entityToUpdate.getOrgIdentifier(), entityToUpdate.getProjectIdentifier(),
          entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
      return updatedEntity;
    }
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 278 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Isrlb665I0ILoc-92:-N3Isrlb665I0ILoc-93:b-wh9k2x) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L278)):*
> ```Java
>     }
>     outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(), entityToUpdate.getOrgIdentifier(),
>         entityToUpdate.getProjectIdentifier(), entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
> ```

same here, with git simplication as well transaction wrapped for update and audits



_Code quote:_
```Java
    outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(), entityToUpdate.getOrgIdentifier(),
        entityToUpdate.getProjectIdentifier(), entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 279 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IsPvc4ZkcmMr-rUdH:-N3IsPvc4ZkcmMr-rUdI:b-xpg37v) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L279)):*
> ```Java
>     outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(), entityToUpdate.getOrgIdentifier(),
>         entityToUpdate.getProjectIdentifier(), entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
>     return updatedEntity;
> ```

everything in one place becomes less readable, can we create methods which handles, update for old, update for inline, update for remote etc



_Code quote:_
```Java
    if (oldEntityFromDB == null) {
      return null;
    }
    InputSetEntity updatedEntity =
        PMSInputSetFilterHelper.updateFieldsInDBEntry(oldEntityFromDB, entityToUpdate, timeOfUpdate);
    if (updatedEntity.getStoreType() == null) {
      Update updateOperationsForOnboardingToInline = PMSInputSetFilterHelper.getUpdateOperationsForOnboardingToInline();
      updatedEntity = mongoTemplate.findAndModify(query, updateOperationsForOnboardingToInline,
          new FindAndModifyOptions().returnNew(true), InputSetEntity.class);
    }
    if (updatedEntity == null) {
      return null;
    }
    if (updatedEntity.getStoreType() == StoreType.INLINE) {
      outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(),
          entityToUpdate.getOrgIdentifier(), entityToUpdate.getProjectIdentifier(),
          entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
      return updatedEntity;
    }
    if (gitSyncSdkService.isGitSimplificationEnabled(entityToUpdate.getAccountIdentifier(),
            entityToUpdate.getOrgIdentifier(), entityToUpdate.getProjectIdentifier())) {
      Scope scope = Scope.builder()
                        .accountIdentifier(updatedEntity.getAccountIdentifier())
                        .orgIdentifier(updatedEntity.getOrgIdentifier())
                        .projectIdentifier(updatedEntity.getProjectIdentifier())
                        .build();
      gitAwareEntityHelper.updateEntityOnGit(updatedEntity, updatedEntity.getYaml(), scope);
    }
    outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(), entityToUpdate.getOrgIdentifier(),
        entityToUpdate.getProjectIdentifier(), entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
    return updatedEntity;
```
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 335 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Iswk4BJP42gAEMykk:-N3Iswk4BJP42gAEMykl:b-misjkk) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L335)):*
> ```Java
>                             .is(pipelineIdentifier)
>                             .and(InputSetEntityKeys.identifier)
>                             .is(identifier);
> ```

can be put inside method



_Code quote:_
```Java
    Criteria criteria = Criteria.where(InputSetEntityKeys.deleted)
                            .is(false)
                            .and(InputSetEntityKeys.accountId)
                            .is(accountId)
                            .and(InputSetEntityKeys.orgIdentifier)
                            .is(orgIdentifier)
                            .and(InputSetEntityKeys.projectIdentifier)
                            .is(projectIdentifier)
                            .and(InputSetEntityKeys.pipelineIdentifier)
                            .is(pipelineIdentifier)
                            .and(InputSetEntityKeys.identifier)
                            .is(identifier);
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 12 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Im-DPEMtwoJGj8AyN:-N3J0AS19GkKp4iW7CRL:bduhq1) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java#L170)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you the get helper method which you created 
</blockquote></details>

That helper method was for pipeline entity in pipeline's dto mapper. Keeping a separate method for input sets here.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 12 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IsYZpEm7uINPZTREP:-N3J1VjH0zsqfpyT1B_6:b-rvy04) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L267)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

non git sync, and audits, should be done in transaction
</blockquote></details>

There aren't supposed to be audits for update calls for remote entities. And if I keep the checks inside transactions on what the store type of the found and updated entity is, it'll get messy. 
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 278 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Isrlb665I0ILoc-92:-N3J22SMEn6QKesUp-kx:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L278)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here, with git simplication as well transaction wrapped for update and audits
</blockquote></details>

same as above

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 12 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 114 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Iqvm178sX_wVnnkHn:-N3J2G6NCy40CDUyY1L0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L114)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this you can remove and after else you have the same instructions, you can use and use them in transaction
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Ir2ND8VS7Gd1re9hH:-N3J2GgOCqOi2dahike-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L136)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

call this in transaction
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Im-DPEMtwoJGj8AyN:-N3J47HM8uRS_krK-_-Z:bqxhwqk) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java#L170)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

That helper method was for pipeline entity in pipeline's dto mapper. Keeping a separate method for input sets here.
</blockquote></details>

You have created the method but not used it
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IsYZpEm7uINPZTREP:-N3J4yzL-oFKs1Hub9Ea:b-fg2fsc) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L267)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

There aren't supposed to be audits for update calls for remote entities. And if I keep the checks inside transactions on what the store type of the found and updated entity is, it'll get messy. 
</blockquote></details>

as discussed offline, we should introduce it
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 278 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Isrlb665I0ILoc-92:-N3J51CUCww132aioLpZ:bf9xadw) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L278)):*
> as discussed offline, we should introduce it
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 251 at r4](https://reviewable.io/reviews/harness/harness-core/33643#-N3J5FZq2hmnUr8cl1mH:-N3J5FZr3WzdYMZ-yEzP:ba3dkei) ([raw file](https://github.com/harness/harness-core/blob/4526d008cf4cb0371c791528e4f643a30c8bc475/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L251)):*
> ```Java
>     }
>     outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(), entityToUpdate.getOrgIdentifier(),
>         entityToUpdate.getProjectIdentifier(), entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
> ```

the audits for git simpl are already here



_Code quote:_
```Java
    if (gitSyncSdkService.isGitSimplificationEnabled(entityToUpdate.getAccountIdentifier(),
            entityToUpdate.getOrgIdentifier(), entityToUpdate.getProjectIdentifier())) {
      Scope scope = Scope.builder()
                        .accountIdentifier(updatedEntity.getAccountIdentifier())
                        .orgIdentifier(updatedEntity.getOrgIdentifier())
                        .projectIdentifier(updatedEntity.getProjectIdentifier())
                        .build();
      gitAwareEntityHelper.updateEntityOnGit(updatedEntity, updatedEntity.getYaml(), scope);
    }
    outboxService.save(new InputSetUpdateEvent(entityToUpdate.getAccountIdentifier(), entityToUpdate.getOrgIdentifier(),
        entityToUpdate.getProjectIdentifier(), entityToUpdate.getPipelineIdentifier(), updatedEntity, oldEntityFromDB));
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 13 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Im-DPEMtwoJGj8AyN:-N3JAHr4A1pcnPAxjDXf:b-4bntno) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java#L170)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

You have created the method but not used it
</blockquote></details>

oh here, the method created is different from this one. List call needs a separate way to get entity git details. I'll add a comment
___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 278 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Isrlb665I0ILoc-92:-N3JA5_U52OfUge2vCxL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L278)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

> as discussed offline, we should introduce it
</blockquote></details>

Done.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 13 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java` line 170 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3Im-DPEMtwoJGj8AyN:-N3JAg2K1z2kBgA-XGtf:b-p1i752) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers/PMSInputSetElementMapper.java#L170)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

oh here, the method created is different from this one. List call needs a separate way to get entity git details. I'll add a comment
</blockquote></details>

added comment

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 13 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 267 at r2](https://reviewable.io/reviews/harness/harness-core/33643#-N3IsYZpEm7uINPZTREP:-N3JAotH4QcBdBfwAmQ1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96789dd07bdf726726d93cd366f3269f7a5fa656/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L267)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed offline, we should introduce it
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 12 files at r1, 2 of 3 files at r3, 1 of 3 files at r5, 3 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643#-:-N3JkmYlBWBdWRq9VWPQ:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33643)* status: :shipit: complete! ✓

**Pull request merged**
