### PR TITLE
[fix]: [CDS-33632]: Add NG host connectivity task and removed ssh ref for PDC connector

### PR DESCRIPTION
**Pull request by ivan-83**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)

### CODE REVIEW

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger messagecheck

**Comment by ivan-83** [comment]
trigger messagecheck

**Comment by ivan-83** [comment]
trigger messagecheck

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by acasian-harness — APPROVED** [review]
> Reviewed 9 of 17 files at r1, 18 of 20 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 18 of 20 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 10 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: 1 file(s) to review. 

___
*[440-connector-nextgen/src/test/resources/schema/Connectors/all.json, line 1024 at r5](https://reviewable.io/reviews/harness/harness-core/32218#-N-fwnvO64jktFsh4Xf8:-N-fwnvO64jktFsh4Xf9:bl6dgcy) ([raw file](https://github.com/harness/harness-core/blob/1d9d241c4cf088e07127f3969e05163581872641/440-connector-nextgen/src/test/resources/schema/Connectors/all.json#L1024)):*
> ```JSON
>       "$schema": "http://json-schema.org/draft-07/schema#"
>     },
>     "AzureInheritFromDelegateDetails": {
> ```

how is this related to PDC connector?

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 4 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Review by bojanmicovic — DISMISSED** [review]
> Reviewed 7 of 17 files at r1, 8 of 20 files at r2, 3 of 4 files at r3, 5 of 7 files at r4, 3 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 5 of 7 files at r6, 7 of 15 files at r7, 13 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 6 of 17 files at r1, 3 of 20 files at r2, 2 of 4 files at r3, 1 of 7 files at r4, 1 of 11 files at r5, 5 of 7 files at r6, 7 of 15 files at r7, 4 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32218)* status: :shipit: complete! ✓

**Pull request merged**
