### PR TITLE
[feat]: [CCM-13840]: Added support for AWS billingEntity and lineItemType

### PR DESCRIPTION
**Pull request by sdsingh07**
## Describe your changes
Added support for AWS billingEntity and lineItemType.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51471)

### CODE REVIEW

**Comment by sdsingh07** [comment]
trigger uts

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51471)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/51471#-NbPckXW7xrd5yqbW2rg:-NbPckXW7xrd5yqbW2rh:b-ntzydv) ([raw file](https://github.com/harness/harness-core/blob/4dc24515a01c6b894cc19346c1f2cffc05548623/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java#L32)):*
> ```Java
>   String AWS_INSTANCE_TYPE_FIELD_ID = "awsInstancetype";
>   String AWS_USAGE_TYPE_ID = "awsUsageType";
>   String AWS_BILLING_ENTITY = "awsBillingEntity";
> ```

We need to take into account supporting these for smp also, some additional changes might be required for clickhouse. I think there is a mapping that maintain to convert column names accordingly for clickhouse as the column names are case sensitive.

**Comment by sdsingh07** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/51471)_ status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/51471#-NbPckXW7xrd5yqbW2rg:-NbPckXW7xrd5yqbW2rh:b-ntzydv) ([raw file](https://github.com/harness/harness-core/blob/4dc24515a01c6b894cc19346c1f2cffc05548623/490-ce-commons/src/main/java/io/harness/ccm/commons/constants/ViewFieldConstants.java#L32)):_
> 
> > ```java
> >   String AWS_INSTANCE_TYPE_FIELD_ID = "awsInstancetype";
> >   String AWS_USAGE_TYPE_ID = "awsUsageType";
> >   String AWS_BILLING_ENTITY = "awsBillingEntity";
> > ```
> 
> We need to take into account supporting these for smp also, some additional changes might be required for clickhouse. I think there is a mapping that maintain to convert column names accordingly for clickhouse as the column names are case sensitive.

Discussed with @abhijeet-harness that we will add these columns in the next smp release. Places where we have to add these columns:
- Create table query
- Insert data query
- Clickhouse columns mapping

**Comment by sdsingh07** [comment]
trigger uts

**Review by svmav — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51471)* status: 1. unresolved discussions.

**Pull request merged**
