### PR TITLE
[feat]: [PIE-5454]: Add OnFailRollbackAdviser to steps for Pipeline Rollback

### PR DESCRIPTION
**Pull request by namanvermah**
For every step, where advisors are set for every failure strategy, this PR sets the OnFailRollbackAdviser for Pipeline Rollback. Next PR will add the rollback stages nodes and set them as the next nodes in these advisors for pipeline rollback.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37796)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37796)

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37796)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37796)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37796)* status: :shipit: complete! ✓

**Pull request merged**
