### PR TITLE
fix: [PIE-1338]: Variable creator v2 framework changes

### PR DESCRIPTION
**Pull request by archit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)

### CODE REVIEW

**Comment by archit-harness** [comment]
codehash is changed because proto is changed, by adding a new field, which is not used by any delegate task thus no issues

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 1 of 30 files at r1, 61 of 64 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: 90 file(s) to review. 0 of 2 approvals obtained.

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 19 of 30 files at r1, 3 of 64 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: 101 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — DISMISSED** [review]
> Reviewed 19 of 30 files at r1, 62 of 64 files at r2, 13 of 19 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: 9 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887#-:-Mzo7uW191OPufSlIyyp:bnfp4nl)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 19 of 30 files at r1, 61 of 64 files at r2, 13 of 19 files at r3, 9 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31887)* status: :shipit: complete! ✓

**Pull request merged**
