### PR TITLE
[fix]: [PL-26907]: Added additional logs for vault

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36122)

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/36122#-N8vgYqq8semvJlC4N1p:-N8vgYqr8Aya7kayYEWj:bajsht3) ([raw file](https://github.com/harness/harness-core/blob/42161b9572247dfaecbc718cb061384812644bc6/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L219)):*
> ```Java
>           vaultRestClient.readSecret(authToken, namespace, secretEngine, pathAndKey.path).execute();
>       if (result != null) {
>         log.info("V2Impl-readSecret {} result: isSuccessful: {}, message: {}, code: {}", fullPath,
> ```

nit: enclose {} with ''
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 250 at r1](https://reviewable.io/reviews/harness/harness-core/36122#-N8vggcxD-z8dPYRpzuN:-N8vggcxD-z8dPYRpzuO:buadll5) ([raw file](https://github.com/harness/harness-core/blob/42161b9572247dfaecbc718cb061384812644bc6/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L250)):*
> ```Java
>       String message;
>       if (response.errorBody() != null) {
>         message = String.format("%s %s", response.message(), response.errorBody().string());
> ```

nit: message: '{}', errorBody: '{}'



_Code quote:_
```Java
%s %s
```

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)* status: :shipit: complete! ✓

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/36122#-N8vhFwd-Vs-Fj26_bI_:-N8vhFwd-Vs-Fj26_bIa:bawobj3) ([raw file](https://github.com/harness/harness-core/blob/42161b9572247dfaecbc718cb061384812644bc6/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L219)):*
> ```Java
>           vaultRestClient.readSecret(authToken, namespace, secretEngine, pathAndKey.path).execute();
>       if (result != null) {
>         log.info("V2Impl-readSecret {} result: isSuccessful: {}, message: {}, code: {}", fullPath,
> ```

Would this be overly verbose -- logging every success case? Should we checking for empty response and then log?

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/36122#-N8vhFwd-Vs-Fj26_bI_:-N8vhlnC4YLeVwYJ_DO1:b-hauc0m) ([raw file](https://github.com/harness/harness-core/blob/42161b9572247dfaecbc718cb061384812644bc6/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L219)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Would this be overly verbose -- logging every success case? Should we checking for empty response and then log?
</blockquote></details>

This is required only to debug issue faced by one of the customer. This won't be added to normal release
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/36122#-N8vgYqq8semvJlC4N1p:-N8viHu_6XoIS2oNQWbO:b-6sngoj) ([raw file](https://github.com/harness/harness-core/blob/42161b9572247dfaecbc718cb061384812644bc6/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L219)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: enclose {} with ''
</blockquote></details>

This is required only to debug issue faced by one of the customer. This won't be added to normal release. We can come up with correct formatting as part of error handling improvement task which we already have.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java` line 250 at r1](https://reviewable.io/reviews/harness/harness-core/36122#-N8vggcxD-z8dPYRpzuN:-N8vi1KG52EZcjTlOsDf:b2f4st9) ([raw file](https://github.com/harness/harness-core/blob/42161b9572247dfaecbc718cb061384812644bc6/930-delegate-tasks/src/main/java/software/wings/helpers/ext/vault/VaultRestClientFactory.java#L250)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: message: '{}', errorBody: '{}'
</blockquote></details>

This is required only to debug issue faced by one of the customer. This won't be added to normal release. We can come up with correct formatting as part of error handling improvement task which we already have.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122)* status: :shipit: complete! ✓

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36122#-:-N8vqLVRBQ9vJpJa3n69:bnfp4nl)* status: :shipit: complete! ✓

**Comment by nishantsaini20** [comment]
trigger codebasehash

**Comment by rijajoo** [comment]
trigger codebasehash

**Review by gaurav-jain1 — APPROVED** [review]

**Pull request merged**
