### PR TITLE
feat: [CDS-39673]: apply templates to yaml in template CRUD flow and populate module info

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
- if template refers another template, apply templates in template create/update flow to do nested validations
- add nested templates module information to template
- check for template access permission of linked template
- Do schema validations on resolved yaml to validate template inputs as well.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35189)

### CODE REVIEW

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35189#-:-N6wGiUzCxBDMGQKzcZS:bnfp4nl)* status: :shipit: complete! ✓

**Review by poojaSinghal — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35189)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35189)

**Review by inderschera — COMMENTED** [review]
> Reviewed 5 of 11 files at r1, 2 of 19 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35189)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 544 at r3](https://reviewable.io/reviews/harness/harness-core/35189#-N8TF_RbDBEDnzX3bR79:-N8YbU6dESp0vGrs64eF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ceca77736705081ea1650c4cf2a6f165514a964/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L544)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

change v2/applyTemplates
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeService.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/35189#-N8TIlXl3Pl0LBahCfSy:-N8YbVM5CjVTp49cQEs7:bh91ogp) ([raw file](https://github.com/harness/harness-core/blob/6ceca77736705081ea1650c4cf2a6f165514a964/840-template-service/src/main/java/io/harness/template/services/TemplateMergeService.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

name could be better
</blockquote></details>

as discussed removed it.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 131 at r3](https://reviewable.io/reviews/harness/harness-core/35189#-N8TIq046rjzImYDfiG9:-N8YbY4b4mRnZhtpuFKm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ceca77736705081ea1650c4cf2a6f165514a964/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L131)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

code could be same as applyTempaltestoYaml
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35189)* status: :shipit: complete! ✓

**Comment by inderschera** [comment]
trigger ti0

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35189)* status: :shipit: complete! ✓

**Pull request merged**
