### PR TITLE
[feat]: [PIE-3794]: Save Inline and Remote Pipelines

### PR DESCRIPTION
**Pull request by namanvermah**
The flow for Pipeline save will now look as follows:
If the project has old git sync enabled, we'll use git aware persistence as we have been using till now.
If old git sync is not enabled, and the API call does not mention any store type, then a simple mongo db save is done. Same is done if store type is mentioned as INLINE. If storeType is mentioned as REMOTE, then we check if git simplification is enabled or not. If it is, then we push the file to git and then save the entry in db.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33580)

### CODE REVIEW

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580#-:-N3-2ksZ3D_BlvzAc6Lz:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/33580#-N32nhYZDx8Q7x5W5hZ4:-N32nhY_7y8jScARZiMH:b-mdxyfr) ([raw file](https://github.com/harness/harness-core/blob/f1e517d81b164c680a12caa5a021e5460455f258/800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L156)):*
> ```Java
>     }
>     supplier.get();
>     return mongoTemplate.save(pipelineToSave);
> ```

for this flow, can we set default value in entity for store as INLINE



_Code quote:_
```Java
    supplier.get();
    return mongoTemplate.save(pipelineToSave);
```

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/33580#-N32nhYZDx8Q7x5W5hZ4:-N32q8Gl0IQJDb_9xMYI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f1e517d81b164c680a12caa5a021e5460455f258/800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L156)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

for this flow, can we set default value in entity for store as INLINE
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33580#-:-N33K5-N9hjyBiIw3iZo:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
