### PR TITLE
feat: [PL-28866]: Remove loading support accounts for current user api

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
The current user api call is taking too long and this is happening because we are loading support accounts when we are trying to fetch the user by email. However we are omitting the response completely when we are converting it to NG User as the UserInfo doesn’t contain support accounts to begin with. This PR removes that additional loading of information which is irrelevant to NG.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40002)

### CODE REVIEW

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40002#-:-NG_XVcCBKm1IOHRv5q5:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40002)* status: :shipit: complete! ✓

**Comment by reetika04** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40002#-:-NGlsGML9MQ143lKk3bl:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1062 at r2](https://reviewable.io/reviews/harness/harness-core/40002#-NGluqE41r16suoxg7-I:-NGluqE41r16suoxg7-J:b-yyqzzq) ([raw file](https://github.com/harness/harness-core/blob/8c7f8e9c62e8b1112d057f4c34b774e0d64cddc8/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1062)):*
> ```Java
>     }
> 
>     return user;
> ```

nit: next PR please replace this with `getUserByEmail(email, true)` , lets not duplicate same code. Thanks



_Code quote:_
```Java
    User user = null;
    if (isNotEmpty(email)) {
      user = wingsPersistence.createQuery(User.class).filter(UserKeys.email, email.trim().toLowerCase()).get();
      loadSupportAccounts(user);
      if (user != null && isEmpty(user.getAccounts())) {
        user.setAccounts(newArrayList());
      }
      if (user != null && isEmpty(user.getPendingAccounts())) {
        user.setPendingAccounts(newArrayList());
      }
    }

    return user;
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40002)* status: :shipit: complete! ✓

**Pull request merged**
