### PR TITLE
feat: [PL-30745]: Added Logs for AWS SM

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
Added Log Lines to print Secret Name for AWS SM 

Testing Environment
1. Replicated the errors in UI locally and all the things were working as expected
2. Ran all the unit tests locally and all of them have been modified to work as per the new message 

Screenshot 2023-05-18 at 3 59 00 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47836)

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47836)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AwsSecretsManagerEncryptor.java` line 110 at r4](https://reviewable.io/reviews/harness/harness-core/47836#-NVcJHnu1Y8dsQFvhFux:-NVcJHnu1Y8dsQFvhFuy:b5gcbxf) ([raw file](https://github.com/harness/harness-core/blob/bb4b814244c11062804269c133a0fef737b8deaf/931-encryption-service/src/java/io/harness/encryptors/clients/AwsSecretsManagerEncryptor.java#L110)):*
> ```Java
>           } else {
>             String message = String.format("Secret with name [%s] creation failed after %d retries. %s",
>                 encryptionConfig.getName(), NUM_OF_RETRIES, e.getMessage());
> ```

Secret name might be same across different scopes. Check whether the scope info is also getting printed. If not, either print scope info or print some other metric, like uuid (since this is an internal log only).

**Review by tiwaritejas — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47836)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by adiyaar24** [comment]
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AwsSecretsManagerEncryptor.java` line 110 at r4](https://reviewable.io/reviews/harness/harness-core/47836#-NVcJHnu1Y8dsQFvhFux:-NVctiEx3aULWsgb-s2T:bs7wumb) ([raw file](https://github.com/harness/harness-core/blob/bb4b814244c11062804269c133a0fef737b8deaf/931-encryption-service/src/java/io/harness/encryptors/clients/AwsSecretsManagerEncryptor.java#L110)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Secret name might be same across different scopes. Check whether the scope info is also getting printed. If not, either print scope info or print some other metric, like uuid (since this is an internal log only).
</blockquote></details>

Done.

**Review by tiwaritejas — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47836)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger ut2

**Review by VikasMaddukuriHarness — APPROVED** [review]

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger uts

**Review by VikasMaddukuriHarness — APPROVED** [review]

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger ut7

**Review by rijajoo — APPROVED** [review]

**Pull request merged**
