### PR TITLE
feat: [CDS-43884]: Move v2 variables to factory pattern

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37990)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37990)

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37990)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NgTemplateVariableService.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7cP4IBqsOqITCiHZm:-ND7cP4IBqsOqITCiHZn:b-gfaw6s) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/NgTemplateVariableService.java#L13)):*
> ```Java
> import io.harness.pms.variables.VariableMergeServiceResponse;
> 
> public interface NgTemplateVariableService {
> ```

add another method supportVariables as well.
___
*[`840-template-service/src/main/java/io/harness/template/services/NgTemplateVariableService.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7d0eO5cg0pDugE2HM:-ND7d0eO5cg0pDugE2HN:b-wbuk1l) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/NgTemplateVariableService.java#L13)):*
> ```Java
> import io.harness.pms.variables.VariableMergeServiceResponse;
> 
> public interface NgTemplateVariableService {
> ```

nit: rename TemplateVariableCreatorService
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7cWYW6xi3Ac-qISkv:-ND7cWYW6xi3Ac-qISkw:b-c64mn8) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L15)):*
> ```Java
> import com.google.inject.Inject;
> 
> public class V2VariablesFactory {
> ```

nit: rename TemplateVariableCreatorFactory
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7bvmLEwlDLtJNGA0C:-ND7bvmLEwlDLtJNGA0D:b4bwqri) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L16)):*
> ```Java
> 
> public class V2VariablesFactory {
>   @Inject PipelineOwnedVariables pipelineOwnedVariables;
> ```

nit: change name to PipelineTemplateVariablesCreatorService
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7c0NeDdO8OYi_Kup_:-ND7c0NeDdO8OYi_Kupa:b-2lql1n) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L18)):*
> ```Java
>   @Inject PipelineOwnedVariables pipelineOwnedVariables;
>   @Inject CustomDeploymentVariables customDeploymentVariables;
>   @Inject TemplateOwnedVariables templateOwnedVariables;
> ```

nit: GenericTemplateVariablesCreatorService rename
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7btEJ1-yfFrybodMh:-ND7btEJ1-yfFrybodMi:bj8sr67) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L22)):*
> ```Java
>   public NgTemplateVariableService getVariablesService(TemplateEntityType templateEntityType) {
>     HarnessTeam ownerTeam = templateEntityType.getOwnerTeam();
>     switch (ownerTeam) {
> ```

simplify switch statements based on entityType
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7dDl58M22x8MEzGZD:-ND7dDl58M22x8MEzGZE:bbgwhgq) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L29)):*
> ```Java
>           case CUSTOM_DEPLOYMENT_TEMPLATE:
>             return customDeploymentVariables;
>           default:
> ```

default should be noOpVariablesCreatorService which has supportVariables false

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37990)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NgTemplateVariableService.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7cP4IBqsOqITCiHZm:-ND84hmc5qNNOJHLRxW5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/NgTemplateVariableService.java#L13)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

add another method supportVariables as well.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7btEJ1-yfFrybodMh:-ND84iNMEV3BRv_4rgu5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L22)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

simplify switch statements based on entityType
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/37990#-ND7dDl58M22x8MEzGZD:-ND84jpF-ArpCfN0EYOa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4117951ac3d2eee8bb44b7e837cdefd34f27d261/840-template-service/src/main/java/io/harness/template/services/V2VariablesFactory.java#L29)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

default should be noOpVariablesCreatorService which has supportVariables false
</blockquote></details>

Done.

**Review by RishabhGupta34 — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37990)* status: 1 change requests. 3. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37990)* status: 1 change requests. 3. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37990)* status: :shipit: complete! ✓

**Pull request merged**
