### PR TITLE
feat: [CDP-20002]: add skipping terraform show if version less than 0.12.x

### PR DESCRIPTION
**Pull request by BogdanAtHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java, line 751 at r1](https://reviewable.io/reviews/harness/harness-core/30556#-Mv3Qg_R8FjdHbzQsCUX:-Mv3Qg_R8FjdHbzQsCUY:b-l08j4m) ([raw file](https://github.com/harness/harness-core/blob/d24fae959445a6ac162010e243019b721f78409e/400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L751)):*
> ```Java
> 
>     TerraformVersion version = terraformClient.version(parameters.getTimeoutInMillis(), scriptDirectory);
>     if (!version.minVersion(0, 12)) {
> ```

just to check,  !version.minVersion(0,12) logic means that version is less than v.0.12.0, right?
___
*[400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java, line 755 at r1](https://reviewable.io/reviews/harness/harness-core/30556#-Mv3Qat-A4iPubhZLj8n:-Mv3Qat-A4iPubhZLj8o:b-ph08en) ([raw file](https://github.com/harness/harness-core/blob/d24fae959445a6ac162010e243019b721f78409e/400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L755)):*
> ```Java
>         "Skipping command.";
>       String message = format(messageFormat, version.getMajor(), version.getMinor(), version.getPatch());
>       logCallback.saveExecutionLog(color("\n" + message + "\n", Yellow, Bold), WARN, CommandExecutionStatus.SKIPPED); // TODO add test for this
> ```

Minor - remove // TODO add test for this

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java, line 752 at r2](https://reviewable.io/reviews/harness/harness-core/30556#-Mv3VKFoBimElzaElXs5:-Mv3VKFpEc3OJT0XOIyF:b-nclq7i) ([raw file](https://github.com/harness/harness-core/blob/c3a2ca59295da61dc301d0bc3ad7b2a2f759214e/400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L752)):*
> ```Java
>     TerraformVersion version = terraformClient.version(parameters.getTimeoutInMillis(), scriptDirectory);
>     if (!version.minVersion(0, 12)) {
>       String messageFormat = "Terraform plan json export not suppoerted in v%d.%d.%d. Minimum version is v0.12.x. " +
> ```

nit: typo in suppoErted

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556#-:-Mv3YWk76BwRaIL07zMe:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)* status: 2 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30556)* status: :shipit: complete! ✓

**Pull request merged**
