### PR TITLE
fix: [CDS-48051]: add refresh status on continue workflow action

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes

The customer reported an issue regarding the status of the approval step being `queued` when it should be `paused` in order to be able to continue the process.

And with that it returned the error ` Invalid request: Cannot continue Pipeline Stage, PipelineStageExecution is not Paused. current status: QUEUED`.

Trying to replicate and investigate the problem, the UI does not return the problem reported by the customer and therefore after some time he is able to use it. What happens, the UI sends several GET requests to the backend and these requests update the queue status to paused. That said, what was done was to use the same method to refresh the status regardless of the UI GET. Thus working for other types of connections with GraphQL and via SDK's.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)

### CODE REVIEW

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 4139 at r2](https://reviewable.io/reviews/harness/harness-core/41768#-NJl2hwA-d9Xzio0lAB8:-NJl2hwA-d9Xzio0lAB9:b-94r8s7) ([raw file](https://github.com/harness/harness-core/blob/9bea7b31470ba84ce901c2f90545c8e3fe74b39d/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L4139)):*
> ```Java
>     validatePipelineExecution(pipelineExecution.getUuid(), pipelineExecution);
> 
>     refreshPipelineExecution(pipelineExecution);
> ```

I see this code block as a critical point, let's reduce the risk and add a FF here.

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceTest.java` line 1713 at r3](https://reviewable.io/reviews/harness/harness-core/41768#-NJod6TN7VQ6vVY2SPTU:-NJod6TN7VQ6vVY2SPTV:b-fkf6il) ([raw file](https://github.com/harness/harness-core/blob/69960df27d3fa349e3c2208db17c023e28ea167f/400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceTest.java#L1713)):*
> ```Java
>     when(featureFlagService.isEnabled(
>              eq(FeatureName.SPG_ALLOW_REFRESH_PIPELINE_EXECUTION_BEFORE_CONTINUE_PIPELINE), any()))
>         .thenReturn(true);
> ```

Missing a UT when the FF is disabled and the refresh should not be executed.

**Review by lasdox — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 4139 at r2](https://reviewable.io/reviews/harness/harness-core/41768#-NJl2hwA-d9Xzio0lAB8:-NJrGlqj63Dwch7V0wyd:b-a819aa) ([raw file](https://github.com/harness/harness-core/blob/9bea7b31470ba84ce901c2f90545c8e3fe74b39d/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L4139)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

I see this code block as a critical point, let's reduce the risk and add a FF here.
</blockquote></details>

I did the change. done.
___
*[`400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceTest.java` line 1713 at r3](https://reviewable.io/reviews/harness/harness-core/41768#-NJod6TN7VQ6vVY2SPTU:-NJrGq4R5ikbAhogvuMw:bxfc03u) ([raw file](https://github.com/harness/harness-core/blob/69960df27d3fa349e3c2208db17c023e28ea167f/400-rest/src/test/java/software/wings/service/impl/WorkflowExecutionServiceTest.java#L1713)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Missing a UT when the FF is disabled and the refresh should not be executed.
</blockquote></details>

It added. done.

**Review by rafaelmart1ns — COMMENTED** [review]
done.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768#-:-NJrGx5ECT16ZQWPJ_I0:b-7rl0jd)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by rafaelmart1ns — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768#-:-NJv19LA-XZoME4k7OFX:bnfp4nl)* status: 1 file(s) to review.

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768#-:-NJvUBspDS9j5UttszPX:bnfp4nl)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41768)* status: :shipit: complete! ✓

**Pull request merged**
