### PR TITLE
[feat]: [PIE-1874]: Add Input Set Sanitise API

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31721)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Comment by naidu-harness** [comment]
@namanvermah / @vaibhav-harness do we have to expose this API via OpenSpec?

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 8 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31721)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31721)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31721)* status: 4 file(s) to review.

**Pull request merged**
