### PR TITLE
SEI-1683 - Register SEI resources, permissions and scopes on harness …

### PR DESCRIPTION
**Pull request by ashish-levelops**
## Describe your changes
SEI resource, permissions and scopes are defined on harness platform as defined here -
https://harness.atlassian.net/wiki/spaces/LEV/pages/21363688165/SEI+Authorization
https://harness.atlassian.net/wiki/spaces/LEV/pages/21417754907/SEI+on+Harness+User+Experience#SEI-Resources

## Checklist
- [ ] I've documented the changes in the PR description. - Yes
- [ ] I've tested this change either in PR or local environment. - Yes - tested on local env, WIP for devspaces
- [ ] If hashcheck failed I followed [the checklist] (https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50642)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50642)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/50642#-N_ZHTZFBxwdomZCQk0N:-N_ZHTZFBxwdomZCQk0O:bq9n6e2) ([raw file](https://github.com/harness/harness-core/blob/2a08886b6f38dc6bd9330f742a2234105c46ef36/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L75)):*
> ```Java
>     public Map<ScopeLevel, EnumSet<ValidatorType>> getSelectorKind() {
>         return ImmutableMap.of(ScopeLevel.ACCOUNT, EnumSet.of(BY_RESOURCE_TYPE,BY_RESOURCE_IDENTIFIER),
>                 ScopeLevel.ORGANIZATION, EnumSet.of(BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES), ScopeLevel.PROJECT,
> ```

This looks inconsistent across scope. ACCOUNT has BY_RESOURCE_TYPE but Org has BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES and not by identifier.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50642)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/50642#-N_ZHp_xCHZJAjKX9_Gn:-N_ZHp_xCHZJAjKX9_Go:bdi7u9i) ([raw file](https://github.com/harness/harness-core/blob/2a08886b6f38dc6bd9330f742a2234105c46ef36/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java#L73)):*
> ```Java
>     @Override
>     public Map<ScopeLevel, EnumSet<ValidatorType>> getSelectorKind() {
>         return ImmutableMap.of(ScopeLevel.ACCOUNT, EnumSet.of(BY_RESOURCE_TYPE,BY_RESOURCE_IDENTIFIER),
> ```

This looks inconsistent across scope. ACCOUNT has BY\_RESOURCE\_TYPE but Org has BY\_RESOURCE\_TYPE\_INCLUDING\_CHILD\_SCOPES and not by identifier.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50642)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 146 at r1](https://reviewable.io/reviews/harness/harness-core/50642#-N_ZIpxs2-pWugyYmXqp:-N_ZIpxs2-pWugyYmXqq:b-ih26gk) ([raw file](https://github.com/harness/harness-core/blob/2a08886b6f38dc6bd9330f742a2234105c46ef36/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L146)):*
> ```YAML
>     permissionKey: criticalevent
>   - identifier: SEI_CONFIGURATION_SETTINGS
>     permissionKey: seiconfigurationsettings
> ```

Ashish good that u included sei in permission key as well like seiconfigurationsettings enough though it is repetitive in permission name but this helps for identification when similar things may come across module.
Just adding here so others in team can recognize it.

**Review by ashish-levelops — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50642)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/50642#-N_ZHTZFBxwdomZCQk0N:-N_bRmPeACBSMc5RQYMj:b-g2tv2o) ([raw file](https://github.com/harness/harness-core/blob/2a08886b6f38dc6bd9330f742a2234105c46ef36/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEICollectionsResourceImpl.java#L75)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This looks inconsistent across scope. ACCOUNT has BY_RESOURCE_TYPE but Org has BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES and not by identifier.
</blockquote></details>

Addressed this
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/50642#-N_ZHp_xCHZJAjKX9_Gn:-N_bS5mu2BnmLJXdKYgA:b-g2tv2o) ([raw file](https://github.com/harness/harness-core/blob/2a08886b6f38dc6bd9330f742a2234105c46ef36/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/sei/SEIInsightsResourceImpl.java#L73)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This looks inconsistent across scope. ACCOUNT has BY\_RESOURCE\_TYPE but Org has BY\_RESOURCE\_TYPE\_INCLUDING\_CHILD\_SCOPES and not by identifier.
</blockquote></details>

Addressed this

**Pull request closed without merging**
