### PR TITLE
feat: [CDS-50321]: Backup classes for Migration logic Instance sync V2 cg

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Comment by namantalaycha10** [comment]
trigger checkstylecodeformat

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVurLm7c1PajCzZoQb:-NLVurLm7c1PajCzZoQc:b32k4s9) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java#L44)):*
> ```Java
> @StoreIn(DbAliases.HARNESS)
> @Entity(value = "instanceSyncPerpetualTasksInfoBackup", noClassnameStored = true)
> public class InstanceSyncPTInfoBackup implements PersistentEntity, UuidAware, UuidAccess, AccountAccess,
> ```

Create an combined index on accountId and infraMappingId?

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVv7U6-OnAXmz9Gdel:-NLVv7U6-OnAXmz9Gdem:b-3tqwyy) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L44)):*
> ```Java
>     }
>     instanceSyncPTBackup.getPerpetualTaskRecordIds().add(perpetualTaskRecord.getUuid());
>     List<PerpetualTaskRecord> records = new ArrayList<>(instanceSyncPTBackup.getPerpetualTaskRecords());
> ```

can we use findAndModify here? This will not be atomic and might cause some issues if two threads or pods try to update the same record, though it is less likely because of locks but maybe we can use addToSet here?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVurLm7c1PajCzZoQb:-NLWo_Kh7oQlm_4CCQT1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java#L44)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create an combined index on accountId and infraMappingId?
</blockquote></details>

Done.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVv7U6-OnAXmz9Gdel:-NL_-HPE-ZzQt9X1sUPP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L44)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

can we use findAndModify here? This will not be atomic and might cause some issues if two threads or pods try to update the same record, though it is less likely because of locks but maybe we can use addToSet here?
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVv7U6-OnAXmz9Gdel:-NLf8CXb8NNpSXuF1275:br74twp) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L44)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do we actually need to update it if it already exists? Shouldn't be the logic be if  (findByAccountIdAndInfraMappingIdPerpetualTaskId(
                accountId, infrastructureMappingId, perpetualTaskRecord.getUuid())) is not empty then skip save? Or do we even need to check if already exists? We could just straight away save it. This logic was required earlier because we had a list of PTs records
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf80WG4B-ClnvkwpZi:-NLf80WG4B-ClnvkwpZj:b-h0oezw) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L36)):*
> ```Java
>                                   .accountId(accountId)
>                                   .infrastructureMappingId(infrastructureMappingId)
>                                   .perpetualTaskRecordId("newPerpetualTaskRecordBackUp")
> ```

please make it const and uppercase, ex: NEW_PERPETUAL_TASK_RECORD_ID
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf7P5W9eeDo-y87rq2:-NLf7P5W9eeDo-y87rq3:bvcof2s) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java#L47)):*
> ```Java
> public class InstanceSyncPTInfoBackup implements PersistentEntity, UuidAware, UuidAccess, AccountAccess,
>                                                  CreatedAtAccess, CreatedAtAware, UpdatedAtAware, UpdatedAtAccess {
>   public static List<MongoIndex> mongoIndexes() {
> ```

Can we check if these mongoIndexes is actually called? Don't we need to register it some morphia reigstrars for this work?
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf6hJd2yDM0zFU_U3Y:-NLf6hJd2yDM0zFU_U3Z:b9jscor) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java#L64)):*
> ```Java
> 
>   @Id String uuid;
>   @FdIndex String accountId;
> ```

Do we still need these annotations @FdIndex if we're manually creating mongoIndexes? 
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf7dSd1R3BmuKW2mu-:-NLf7dSd1R3BmuKW2mu0:b-ezbdfy) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java#L59)):*
> ```Java
>         persistence.createQuery(InstanceSyncPTInfoBackup.class)
>             .filter(InstanceSyncPTInfoBackup.ACCOUNT_ID_KEY, accountId)
>             .filter(InstanceSyncPTInfoBackup.InstanceSyncPTBackupKeys.infrastructureMappingId, infraMappingId)
> ```

You don't have an index on infrastructureMappingId + perpeutalTaskId, only accountId + perpetualTaskId. Do you need this in your query? Or index need to be updated?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 3 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVv7U6-OnAXmz9Gdel:-NLt4hDx9CryyZP_hVKZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L44)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we actually need to update it if it already exists? Shouldn't be the logic be if  (findByAccountIdAndInfraMappingIdPerpetualTaskId(
                accountId, infrastructureMappingId, perpetualTaskRecord.getUuid())) is not empty then skip save? Or do we even need to check if already exists? We could just straight away save it. This logic was required earlier because we had a list of PTs records

</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf80WG4B-ClnvkwpZi:-NLtZyEX4TICvmMtr2QK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L36)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please make it const and uppercase, ex: NEW_PERPETUAL_TASK_RECORD_ID
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java` line 64 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf6hJd2yDM0zFU_U3Y:-NLt65u7-9ObJCQh373G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java#L64)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we still need these annotations @FdIndex if we're manually creating mongoIndexes? 
</blockquote></details>

Done.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 5 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf7P5W9eeDo-y87rq2:-NLxz-xpEnCiOjwjSFCH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackup.java#L47)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we check if these mongoIndexes is actually called? Don't we need to register it some morphia reigstrars for this work?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java` line 59 at r6](https://reviewable.io/reviews/harness/harness-core/42419#-NLf7dSd1R3BmuKW2mu-:-NLxz0yA4BKk2uvEez2H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02ff83a5f5a55a0cff1329c756c5bbde0a2cc597/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

You don't have an index on infrastructureMappingId + perpeutalTaskId, only accountId + perpetualTaskId. Do you need this in your query? Or index need to be updated?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java` line 58 at r8](https://reviewable.io/reviews/harness/harness-core/42419#-NLyZyRY8d4U2XFBWVQx:-NLyZyRZ4jAaw1irftek:b-34dcif) ([raw file](https://github.com/harness/harness-core/blob/d2531756119434512277640126a828ae056265f5/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTInfoBackupDao.java#L58)):*
> ```Java
>         persistence.createQuery(InstanceSyncPTInfoBackup.class)
>             .filter(InstanceSyncPTInfoBackup.ACCOUNT_ID_KEY, accountId)
>             .filter(InstanceSyncPTInfoBackup.InstanceSyncPTBackupKeys.perpetualTaskRecordId, perpetualTaskId);
> ```

nit : directly import Keys file.

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 42 at r8](https://reviewable.io/reviews/harness/harness-core/42419#-NLy_Z8sACRKVm0Zc1UH:-NLy_Z8sACRKVm0Zc1UI:b-5arhaq) ([raw file](https://github.com/harness/harness-core/blob/d2531756119434512277640126a828ae056265f5/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L42)):*
> ```Java
>     }
>     instanceSyncPTBackup.setPerpetualTaskRecord(perpetualTaskRecord);
>     instanceSyncPTInfoBackupDao.save(instanceSyncPTBackup);
> ```

why to save again if it already exists?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 5 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 2 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVv7U6-OnAXmz9Gdel:-NLyp6Nu-xuhOAqO-nwI:b-vzvf1y) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L44)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see we're still doing this, please check Sahil's comment

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/42419#-NLVv7U6-OnAXmz9Gdel:-NLzPlCY7ybuXwt-UcDu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a8fd061db9bc9ed3c9e5f0bad310d9440c0cbbc/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L44)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I see we're still doing this, please check Sahil's comment
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 42 at r8](https://reviewable.io/reviews/harness/harness-core/42419#-NLy_Z8sACRKVm0Zc1UH:-NLzPmlb3zEScfmPZSDV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d2531756119434512277640126a828ae056265f5/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L42)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why to save again if it already exists?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42419)* status: :shipit: complete! ✓

**Pull request merged**
