### PR TITLE
[feat]: [CDS-38696]: FileStore client

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34589)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
trigger ti3

**Review by arpit3107 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34589)* status: 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/FileStoreProxyResource.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GDH4EAAG1d-5McfeF:-N5GDH4F3ax619RZR_Zg:beu9tmw) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/420-delegate-service/src/main/java/io/harness/delegate/resources/FileStoreProxyResource.java#L74)):*
> ```Java
> @Slf4j
> @Hidden
> @AuthRule(permissionType = DELEGATE)
> ```

@DelegateAuth



_Code quote:_
```Java
@AuthRule(permissionType = DELEGATE)
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/FileStoreProxyResource.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GDNeSA1moeS6weF7F:-N5GDNeSA1moeS6weF7G:b-f2xoxu) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/420-delegate-service/src/main/java/io/harness/delegate/resources/FileStoreProxyResource.java#L90)):*
> ```Java
>                                     ApiResponse(responseCode = "default", description = "Get file, optionally with content")
>                     })
>     public ResponseDTO<FileNodeDTO>
> ```

Annotate every method with @DelegateAuth
___
*[`941-filestore-client/src/main/java/io/harness/filestoreclient/module/FileStoreClientNgModule.java` line 11 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GEBgy5ETjijXSMbAK:-N5GEBgy5ETjijXSMbAL:b-w4rmnv) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/941-filestore-client/src/main/java/io/harness/filestoreclient/module/FileStoreClientNgModule.java#L11)):*
> ```Java
> import com.google.inject.Scopes;
> 
> public class FileStoreClientNgModule extends AbstractModule {
> ```

CG Manager is using it, so rename it to CGModule



_Code quote:_
```Java
FileStoreClientNgModule
```
___
*[`941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreAuthInterceptorForCg.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GFmZlEBzMSouVlCFW:-N5GFmZlEBzMSouVlCFX:bwk1n1y) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreAuthInterceptorForCg.java#L26)):*
> ```Java
>         Request request = chain.request();
>         return chain.proceed(request.newBuilder()
>                 .header("Authorization", "NextGenManager " + token)
> ```

CGManager is sending this token, so it should send in its name. Please check with others.



_Code quote:_
```Java
NextGenManager
```
___
*[`941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreAuthInterceptorForCg.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GFxUR4Tm30vtEtc8I:-N5GFxUR4Tm30vtEtc8J:b-hd6dz2) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreAuthInterceptorForCg.java#L28)):*
> ```Java
>                 .header("Authorization", "NextGenManager " + token)
>                 .addHeader("delegateId", DelegateAgentCommonVariables.getDelegateId())
>                 .addHeader("delegateTokenName", DelegateAgentCommonVariables.getDelegateTokenName())
> ```

We don't need these variables, delegate uses it to communicate, but not needed in case of communication b/w cg manager and ng manager.



_Code quote:_
```Java
                .addHeader("delegateId", DelegateAgentCommonVariables.getDelegateId())
                .addHeader("delegateTokenName", DelegateAgentCommonVariables.getDelegateTokenName())
```
___
*[`941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreNgAuthInterceptor.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GGSch9PlkliO63YG6:-N5GGSch9PlkliO63YG7:b-rzpfa8) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreNgAuthInterceptor.java#L13)):*
> ```Java
> import static io.harness.network.Localhost.getLocalHostName;
> 
> public class FileStoreNgAuthInterceptor implements Interceptor {
> ```

Rename it to FileStoreDelegateAuthInterceptor



_Code quote:_
```Java
FileStoreNgAuthInterceptor
```
___
*[`941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreNgClient.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GGhoU3moKqgh00rHU:-N5GGhoU3moKqgh00rHV:b-bgkhpo) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/941-filestore-client/src/main/java/io/harness/filestoreclient/remote/FileStoreNgClient.java#L21)):*
> ```Java
> 
> @OwnedBy(CDP)
> public interface FileStoreNgClient {
> ```

CGClient



_Code quote:_
```Java
ileStoreNgClient
```

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34589)* status: 21 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/managerclient/DelegateManagerClientModule.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GYPZa7COwjSRtgHhx:-N5GYPZa7COwjSRtgHhy:b1yq1rh) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/260-delegate/src/main/java/io/harness/managerclient/DelegateManagerClientModule.java#L46)):*
> ```Java
>         .toProvider(new VerificationServiceClientFactory(verificationServiceBaseUrl, tokenGenerator));
>     bind(CVNextGenServiceClient.class).toProvider(new CVNextGenServiceClientFactory(cvNextGenUrl, tokenGenerator));
>     bind(FileStoreNgClient.class).toProvider(new FileStoreNgClientFactory(managerBaseUrl, tokenGenerator));
> ```

whats the motivation of this change? is it to get some data directly from ng manager?
if thats the case then i don't think we should go this route. we discussed this some other channel as well, the task parameters should just be part of the payload

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34589)* status: 21 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/managerclient/DelegateManagerClientModule.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/34589#-N5GYPZa7COwjSRtgHhx:-N5HU7BhEYwofZ0XMnBK:b-g589id) ([raw file](https://github.com/harness/harness-core/blob/5cd05d60f1f3641ef27c0c97ad77f66d289cd42d/260-delegate/src/main/java/io/harness/managerclient/DelegateManagerClientModule.java#L46)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

whats the motivation of this change? is it to get some data directly from ng manager?
if thats the case then i don't think we should go this route. we discussed this some other channel as well, the task parameters should just be part of the payload
</blockquote></details>

In first place we needed a client for file store, so it can be used by other modules without dependency on 877-filestore module. Additionally, we wanted to make possibility delegate reads content of a file in case sending content of all files referenced by a pipeline is a huge overhead (folders with many files listed in config files, but not all files are actually used). Yes, the idea is to get file content from ng manager, but Delegate sends rest api call to cg manager, which actually gets file content from ng manager, using the same client. 

If you think this is no way to go, I can remove the changes related to delegate. Just would need the reasons behind, so we can explain to other teams why we don’t offer this option, thx.

**Pull request closed without merging**
