### PR TITLE
feat: [PL-24335]: Add find repo support in scm

### PR DESCRIPTION
**Pull request by goelsatyam2**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[product/ci/scm/proto/scm.proto, line 759 at r1](https://reviewable.io/reviews/harness/harness-core/31990#-Mzo05X0EsoNBKF2HkIk:-Mzo05X0EsoNBKF2HkIl:b-69mtn) ([raw file](https://github.com/harness/harness-core/blob/a21dfef29f34d9d6f3ad42bb0a1a6e9b1c9b6389/product/ci/scm/proto/scm.proto#L759)):*
> ```protobuf
>   rpc GetAuthenticatedUser(GetAuthenticatedUserRequest) returns (GetAuthenticatedUserResponse);
>   rpc GetUserRepos(GetUserReposRequest) returns (GetUserReposResponse);
>   rpc GetUserRepo(GetUserRepoRequest) returns (GetUserRepoResponse);
> ```

How are the two APIs GetUserRepos and GetUserRepo different?

Could we have used the add a parameter in the GetUserRepos itself ?

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[product/ci/scm/proto/scm.proto, line 759 at r1](https://reviewable.io/reviews/harness/harness-core/31990#-Mzo05X0EsoNBKF2HkIk:-Mzo4BI1-ayipPCVOkdZ:bcem0si) ([raw file](https://github.com/harness/harness-core/blob/a21dfef29f34d9d6f3ad42bb0a1a6e9b1c9b6389/product/ci/scm/proto/scm.proto#L759)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

How are the two APIs GetUserRepos and GetUserRepo different?

Could we have used the add a parameter in the GetUserRepos itself ?
</blockquote></details>

GetUserRepos returns all the repos present in the project. While GetUserRepo returns the info of repo by slug(id or name).

GetUserRepos and GetUserRepo both use different go-SCM functions internally, combining them will change the contract and implementation won't be that straightforward.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990#-:-MzxVo_7-Bp0Uqmdz-Aw:bnfp4nl)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: :shipit: complete! ✓

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990#-:-Mzy-wnb6vOEZ554AVDf:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: :shipit: complete! ✓

**Review by shubham149 — DISMISSED** [review]
> Reviewed 5 of 6 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990#-:-N-2RMDS8ZYHAbmtaJYU:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: :shipit: complete! ✓

**Review by goelsatyam2 — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 12 of 14 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31990#-:-N-2T3iU6h4LF72fcc07:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
