### PR TITLE
[feat]:[pl-29192]: BE api contract for list repo in pipeline  resource

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
BE api contract for listing branches for a given pipeline on the execution history
BE api contract for listing repositories on pipeline listing page

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 597 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqHmsBx46rIleTjAs:-NEtqHmsBx46rIleTjAt:bkpsqr2) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L597)):*
> ```Java
>                    NGCommonEntityConstants.ACCOUNT_KEY) @AccountIdentifier String accountId,
>       @NotNull @Parameter(description = PipelineResourceConstants.ORG_PARAM_MESSAGE) @QueryParam(
>           NGCommonEntityConstants.ORG_KEY) @OrgIdentifier String orgId,
> ```

identifier

**Comment by mohitg0795** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 599 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqJgn-5VY-PdI6tyl:-NEtqJgn-5VY-PdI6tym:bkpsqr2) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L599)):*
> ```Java
>           NGCommonEntityConstants.ORG_KEY) @OrgIdentifier String orgId,
>       @NotNull @Parameter(description = PipelineResourceConstants.PROJECT_PARAM_MESSAGE) @QueryParam(
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId);
> ```

identifier

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqNl72oRLGA_DKnuO:-NEtqNl72oRLGA_DKnuP:b4hduob) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L485)):*
> ```Java
> 
>   @Override
>   public ResponseDTO<HashSet<String>> getListRepos(String accountId, String orgId, String projectId) {
> ```

identifier for org and project

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 364 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqUHT97bDjacNgus_:-NEtqUHT97bDjacNgusa:b-31xs8c) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L364)):*
> ```Java
> 
>   @GET
>   @Path("/list-execution- repo")
> ```

I think this can also be "list-repos" as it is already for /execution path

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 380 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqYfG5bi5WskEmij6:-NEtqYfG5bi5WskEmij7:btsjok5) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L380)):*
> ```Java
>           NGCommonEntityConstants.ORG_KEY) @OrgIdentifier String orgId,
>       @Parameter(description = PipelineResourceConstants.PROJECT_PARAM_MESSAGE, required = true) @NotNull @QueryParam(
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId,
> ```

same identifier comments as above.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: 3 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 597 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqHmsBx46rIleTjAs:-NEtr0dE3liq7Se3bL1q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L597)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

identifier
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 599 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqJgn-5VY-PdI6tyl:-NEtr0yR9t3zBt1CKH_H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L599)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

identifier
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqNl72oRLGA_DKnuO:-NEtqyq_0WwHeqQGjFIk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L485)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

identifier for org and project
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 364 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqUHT97bDjacNgus_:-NEtqlyY0iJ_qzUNtWVG:b-9yvx5y) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L364)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think this can also be "list-repos" as it is already for /execution path
</blockquote></details>

have updated it list-execution-repos
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 380 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqYfG5bi5WskEmij6:-NEtqkIq6xQHlIQZPMXP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L380)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same identifier comments as above.
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: 5. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 364 at r2](https://reviewable.io/reviews/harness/harness-core/39096#-NEtqUHT97bDjacNgus_:-NEtwEph1-8RWnea37mT:blowvlv) ([raw file](https://github.com/harness/harness-core/blob/d9149514dd982ec95b8236de64e1f0a43f6e52d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L364)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

have updated it list-execution-repos
</blockquote></details>

I agree with Mohit's point

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: :shipit: complete! ✓

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: :shipit: complete! ✓

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 593 at r1](https://reviewable.io/reviews/harness/harness-core/39096#-NEtmDI74Fqi8aUUrpBn:-NEtmDI74Fqi8aUUrpBo:b-ez8wkr) ([raw file](https://github.com/harness/harness-core/blob/0514cbf0b821133481ed7ce927d28e52d0bbcaed/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L593)):*
> ```Java
>       })
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)
>   ResponseDTO<HashSet<String>>
> ```

pls return a structure, else this becomes inextensible
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/39096#-NEu-zpfBguf9isCqREq:-NEu-zpfBguf9isCqREr:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/0514cbf0b821133481ed7ce927d28e52d0bbcaed/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L374)):*
> ```Java
>       })
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)
>   public ResponseDTO<HashSet<String>>
> ```

same

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: :shipit: complete! ✓

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: :shipit: complete! ✓

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 592 at r1](https://reviewable.io/reviews/harness/harness-core/39096#-NEu2Yk09Bfw2BQnOtQQ:-NEu2Yk09Bfw2BQnOtQR:brydb4k) ([raw file](https://github.com/harness/harness-core/blob/0514cbf0b821133481ed7ce927d28e52d0bbcaed/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L592)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns a list of all the repositories of all Pipelines")
>       })
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)
> ```

Is this something that needs to be exposed to customers?
If yes, should we do it the new way?
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/39096#-NEu6uQZ11z6sMBg08Lq:-NEu6uQZ11z6sMBg08Lr:bh84wi4) ([raw file](https://github.com/harness/harness-core/blob/0b71d320d46c775b3d7c3c5acf9beb6c48537240/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java#L23)):*
> ```Java
> @OwnedBy(PL)
> public class PMSPipelineListRepoResponse {
>   HashSet<String> repositories;
> ```

field would also need desrcription if you're planning to make this public

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: :shipit: complete! ✓

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: 1 change requests. 4. unresolved discussions. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 592 at r1](https://reviewable.io/reviews/harness/harness-core/39096#-NEu2Yk09Bfw2BQnOtQQ:-NEuU14SCrg63PEyTWrM:bug2xwq) ([raw file](https://github.com/harness/harness-core/blob/0514cbf0b821133481ed7ce927d28e52d0bbcaed/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L592)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Is this something that needs to be exposed to customers?
If yes, should we do it the new way?
</blockquote></details>

this will not be exposed to customers, so we dont need the accessControlCheck
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 593 at r1](https://reviewable.io/reviews/harness/harness-core/39096#-NEtmDI74Fqi8aUUrpBn:-NEuRurF9a3wxq-kK6J2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0514cbf0b821133481ed7ce927d28e52d0bbcaed/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L593)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

pls return a structure, else this becomes inextensible
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/39096#-NEu6uQZ11z6sMBg08Lq:-NEuSWUL9LSteSHzDl18:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b71d320d46c775b3d7c3c5acf9beb6c48537240/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineListRepoResponse.java#L23)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

field would also need desrcription if you're planning to make this public
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/39096#-NEu-zpfBguf9isCqREq:-NEuU8keC-Nt2XI4lN9m:b-fl7tvi) ([raw file](https://github.com/harness/harness-core/blob/0514cbf0b821133481ed7ce927d28e52d0bbcaed/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L374)):*
> this will not be exposed to customers, so we dont need the accessControlCheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: 1 change requests. 4. unresolved discussions.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 365 at r7](https://reviewable.io/reviews/harness/harness-core/39096#-NFMpTvrEpT7oax7SpD6:-NFMpTvrEpT7oax7SpD7:b-x7a6y3) ([raw file](https://github.com/harness/harness-core/blob/6e510ffb0c257274cca81b5aac039e86874ac003/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L365)):*
> ```Java
> 
>   @GET
>   @Path("/execution/list-repositories")
> ```

why are these under execution?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 365 at r7](https://reviewable.io/reviews/harness/harness-core/39096#-NFMpTvrEpT7oax7SpD6:-NFMpnTMANxpxjntRhw9:byscrd6) ([raw file](https://github.com/harness/harness-core/blob/6e510ffb0c257274cca81b5aac039e86874ac003/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L365)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

why are these under execution?
</blockquote></details>

We want to add the branch and repo filter in execution history page, on clicking the deployment tab, we can see all the pipeline executions, at this point we want to have the filter it based on repo and branch

**Comment by adivishy1** [comment]
trigger codebasehash

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 1 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39096)* status: :shipit: complete! ✓

**Pull request merged**
