### PR TITLE
feat: [CDS-77253]: Adding support to fetch helm chart from Ecr using OCI

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52167)

### CODE REVIEW

**Review by alebuh — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52167)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team,k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java` line 827 at r1](https://reviewable.io/reviews/harness/harness-core/52167#-Nd5N8fK6OOEF9Z1IqsX:-Nd5N8fK6OOEF9Z1IqsY:b-ur60nj) ([raw file](https://github.com/harness/harness-core/blob/0eace23a1fd66743c7cb559d1a46abf028c1f2c3/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java#L827)):*
> ```Java
>   private String getOciHelmEcrRepoName(
>       OciHelmStoreDelegateConfig ociHelmStoreDelegateConfig, long timeoutInMillis, String destinationDirectory) {
>     // RepositoryUrl: 479370281431.dkr.ecr.us-east-1.amazonaws.com/helm-test-chart
> ```

is this comment accidentally left?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/52167#-Nd5MQmo5r-UcxAauuuI:-Nd5MQmo5r-UcxAauuuJ:barpban) ([raw file](https://github.com/harness/harness-core/blob/0eace23a1fd66743c7cb559d1a46abf028c1f2c3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java#L29)):*
> ```Java
>   String basePath;
>   String repoDisplayName;
>   OciHelmConnectorDTO ociHelmConnector;
> ```

Should we remove this field as now we can use connectorConfigDTO ? In a few places, we are checking if it's null and then using another one if it is. I think that we should always use connectorConfigDTO as that will simplify logic

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52167)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team,k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java` line 827 at r1](https://reviewable.io/reviews/harness/harness-core/52167#-Nd5N8fK6OOEF9Z1IqsX:-Nd95k2w858jOTmBp-E-:b2q4oeo) ([raw file](https://github.com/harness/harness-core/blob/0eace23a1fd66743c7cb559d1a46abf028c1f2c3/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/base/HelmTaskHelperBase.java#L827)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

is this comment accidentally left?
</blockquote></details>

No it is for developers reference to get an idea what the RepositoryUrl looks like.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/52167#-Nd5MQmo5r-UcxAauuuI:-Nd95yob3NPrPqMJPts8:bfxlsmj) ([raw file](https://github.com/harness/harness-core/blob/0eace23a1fd66743c7cb559d1a46abf028c1f2c3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java#L29)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

Should we remove this field as now we can use connectorConfigDTO ? In a few places, we are checking if it's null and then using another one if it is. I think that we should always use connectorConfigDTO as that will simplify logic
</blockquote></details>

We should not remove a field from kryo registered class as it will result in serialisation and de-serialisation error. Besides to keep the changes backward compatible we need this field.

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52167)* status: 18 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team,k8s-team. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/52167#-Nd5MQmo5r-UcxAauuuI:-Nd9SqPj8EAFfpV-xzgp:b-5siwdc) ([raw file](https://github.com/harness/harness-core/blob/0eace23a1fd66743c7cb559d1a46abf028c1f2c3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/storeconfig/OciHelmStoreDelegateConfig.java#L29)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

We should not remove a field from kryo registered class as it will result in serialisation and de-serialisation error. Besides to keep the changes backward compatible we need this field.
</blockquote></details>

Oh my bad, I didn't see that we are using it on the manager side, Thought it was just a delegate side entity. In that case, you are right we should not remove it.

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52167)* status: 18 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Pull request closed without merging**
