### PR TITLE
[feat]: [CCM-7538]: Inventory GCP Wiring

### PR DESCRIPTION
**Pull request by abhijeet-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)

### CODE REVIEW

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`scripts/terraform/cloudfunctions/ce/src/python/gcp_inventory_init_main.py` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/32858#-N1dcaXzBXA_6JppnTee:-N1dcaXzBXA_6JppnTef:b-4vkhy6) ([raw file](https://github.com/harness/harness-core/blob/4bb1e589e14a6cdfdf946f871d745c54efe7b673/scripts/terraform/cloudfunctions/ce/src/python/gcp_inventory_init_main.py#L77)):*
> ```Python
>     topic_path = publisher.topic_path(PROJECTID, f"ce-gcp-{inventory_type}-inventory-data-scheduler")
> 
>     schedule = "0 * * * *"  # Run every hour
> ```

Check with @svmav on the right schedule suitable here. 
___
*[`scripts/terraform/cloudfunctions/ce/src/python/gcp_inventory_init_main.py` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/32858#-N1dchSI6baa60F6yc_Y:-N1dchSI6baa60F6yc_Z:b-lx7sck) ([raw file](https://github.com/harness/harness-core/blob/4bb1e589e14a6cdfdf946f871d745c54efe7b673/scripts/terraform/cloudfunctions/ce/src/python/gcp_inventory_init_main.py#L105)):*
> ```Python
>     topic_path = publisher.topic_path(PROJECTID, f"ce-gcp-{inventory_type}-inventory-data-load-scheduler")
> 
>     schedule = "15 * * * *"  # Run every hour
> ```

Same. Check with @svmav

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/service/impl/GCPEntityChangeEventServiceImpl.java` line 142 at r1](https://reviewable.io/reviews/harness/harness-core/32858#-N1ddcsf8mSleRSIHQ1i:-N1ddcsg0oQkaQLkx-Y5:bp8a3cw) ([raw file](https://github.com/harness/harness-core/blob/4bb1e589e14a6cdfdf946f871d745c54efe7b673/340-ce-nextgen/src/main/java/io/harness/ccm/service/impl/GCPEntityChangeEventServiceImpl.java#L142)):*
> ```Java
>   }
> 
>   public void publishMessage(ArrayList<ImmutableMap<String, String>> entityChangeEvents) {
> ```

This method can be moved to common class. I see this is similar to one used for AWS crud events.

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Comment by abhijeet-harness** [comment]
> 

Checked with @svmav on this earlier. Both schedulers need to run hourly. And ce-gcp-{inventory_type}-inventory**-data-load-scheduler** should run 15 minutes after ce-gcp-{inventory_type}-inventory-**data-scheduler**

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: 16 file(s) to review.

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: 16 file(s) to review.

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: 16 file(s) to review.

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: 16 file(s) to review.

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: 16 file(s) to review.

**Review by nikunj-badjatya — APPROVED** [review]

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 4 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32858)* status: :shipit: complete! ✓

**Pull request merged**
