### PR TITLE
feat: [CDS-2993]: K8s declarative rollback

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
https://harness.atlassian.net/browse/CDS-2993

K8s rollback in Harness has been implemented in an imperative way (`kubectl rollout undo`), which causes issues when used with declarative commands like `kubectl apply`. This change(CG/NG) converts imperative to declarative rollback.
A new way to manage release history was needed to facilitate this change. Pruning is integrated with the new release history f/w. Versioning of resources is no longer needed.

Details are captured in this spec:
https://harness.atlassian.net/wiki/spaces/CDP/pages/21075394834/Kubernetes+Declarative+Rollback

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36852)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 37 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 20 Code issues 
* Anti-pattern 16 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36852)

**Comment by abhinavsingh1196** [comment]
trigger ti3

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 14 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36852)* status: Some of the checks are too old. 37 file(s) to review. 0 of 1 approvals obtained.

**Comment by abhinavsingh1196** [comment]
Closing this PR in favour of more granular PRs.

**Pull request closed without merging**
