### PR TITLE
fix: [PL-42878]: Resolved createdAt inconsistency in resend invite flow

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Resend invite flow currently populates the "createdAt" field with an ISODate rather than epochMillis. This leads to inconsistency on sort filters. This PR resolves this bug by populating epochMillis in the resend flow.
Testing-
1. Verified that resend invite flow is now populating epoch instead of ISODate.
2. Verified that UI filter for "Newest" works fine after this change.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55793)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55793)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/55793#-NjpeOU20WC2VeGhsEQB:-NjpeOU20WC2VeGhsEQC:b-f8cv5w) ([raw file](https://github.com/harness/harness-core/blob/3a3e796bf570f8a3bba81d105262db15710550ca/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L481)):*
> ```Java
>           INVITE_PERMISSION_IDENTIFIER);
>       Update update = new Update()
>                           .set(InviteKeys.createdAt, Instant.now().toEpochMilli())
> ```

Add UT for this.

**Comment by tiwaritejas** [comment]
trigger uts

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55793)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/55793#-NjpeOU20WC2VeGhsEQB:-Njpx63S313qp9LWAFIA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a3e796bf570f8a3bba81d105262db15710550ca/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L481)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add UT for this.
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55793)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java` line 889 at r2](https://reviewable.io/reviews/harness/harness-core/55793#-Njpyl4O3K3mELkpxyHM:-Njpyl4O3K3mELkpxyHN:bdyku2a) ([raw file](https://github.com/harness/harness-core/blob/5808b47c12df88f0408997096c935ee9afac932e/120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java#L889)):*
> ```Java
>     assertThat(inviteIdArgumentCaptor.getValue()).isEqualTo(dummyInvite.getId());
>     assertThat(((Document) updateArgumentCaptor.getAllValues().get(0).getUpdateObject().get("$set")).get("createdAt")
>                    instanceof Long);
> ```

use .isInstanceOf() to assert

**Comment by tiwaritejas** [comment]
trigger uts

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55793)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java` line 889 at r2](https://reviewable.io/reviews/harness/harness-core/55793#-Njpyl4O3K3mELkpxyHM:-Njq-4zl4DdO1cYg0Uoi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5808b47c12df88f0408997096c935ee9afac932e/120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java#L889)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use .isInstanceOf() to assert
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55793)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger ut8

**Comment by tiwaritejas** [comment]
trigger ut9

**Pull request merged**
