### PR TITLE
fix: [CDS-53763]: Add Service v2 entity onSave validation for K8s/Native Helm deployment type

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes

This change performs multiple manifest validation for k8s/native helm deployment types on saving, since more than one manifest is not supported.
Service step already performs this validation when manifests are aggregated from all sources (overrides etc.).
Screenshot 2023-02-21 at 6 43 01 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44168)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
ˇ

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44168)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/44168#-NOsJ-M_4ln4lcMPZNF6:-NOsJ-M_4ln4lcMPZNF7:b-xj1i55) ([raw file](https://github.com/harness/harness-core/blob/e3887a3adea747dbb3db70dd3f399d848a43f3b0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java#L93)):*
> ```Java
>     List<ManifestConfigWrapper> manifests = serviceDefinition.getServiceSpec().getManifests();
> 
>     List<ManifestAttributes> manifestList = emptyIfNull(manifests)
> ```

nit: not a big deal, but we could skip anything after if manifests list is empty
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/44168#-NOsIi-C5oMgOOv7KyTD:-NOsIi-C5oMgOOv7KyTE:bar3ww4) ([raw file](https://github.com/harness/harness-core/blob/e3887a3adea747dbb3db70dd3f399d848a43f3b0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/NGServiceEntityMapper.java#L95)):*
> ```Java
>     List<ManifestAttributes> manifestList = emptyIfNull(manifests)
>                                                 .stream()
>                                                 .map(ManifestConfigWrapper::getManifest)
> ```

let's add a null check for getManifest result

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44168)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44168)* status: :shipit: complete! ✓

**Pull request merged**
