### PR TITLE
[fix]: [cds-44413]: Rbac issue with template access permission for ap…

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
…ply templates

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38468)

### CODE REVIEW

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38468)* status: :shipit: complete! ✓

**Review by poojaSinghal — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38468)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38468)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 730 at r1](https://reviewable.io/reviews/harness/harness-core/38468#-NDkqpsf-ZJsJnbH9yMO:-NDkqpsf-ZJsJnbH9yMP:b-gc7p5y) ([raw file](https://github.com/harness/harness-core/blob/8defa6e43a5db8e7a55648dd5be09b027bba879d/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L730)):*
> ```Java
>   @Override
>   public void checkLinkedTemplateAccess(
>       String accountId, String orgId, String projectId, TemplateMergeResponseDTO templateMergeResponseDTO) {
> ```

nit: let's add UT as well for this.

**Review by prabu-kr — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38468)* status: :shipit: complete! ✓

**Review by prabu-kr — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38468)* status: :shipit: complete! ✓

**Pull request merged**
