### PR TITLE
techdebt: [PIE-4916]: added UTs

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39890)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39890)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecDTOTest.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/39890#-NGV3rpW8c_UBLd2a698:-NGV3rpX5Wc9L_fJ36XD:b-bc24hu) ([raw file](https://github.com/harness/harness-core/blob/58eadad943a1b729863f95c5eb44dfbc45d3f5c1/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecDTOTest.java#L35)):*
> ```Java
>   @Owner(developers = SHALINI)
>   @Category(UnitTests.class)
>   public void testFromKeyValueCriteria() {
> ```

What are we testing?
___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecTest.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/39890#-NGV3wOq0OhLPYstAwOp:-NGV3wOq0OhLPYstAwOq:b-tux3gg) ([raw file](https://github.com/harness/harness-core/blob/58eadad943a1b729863f95c5eb44dfbc45d3f5c1/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecTest.java#L46)):*
> ```Java
>   @Owner(developers = SHALINI)
>   @Category(UnitTests.class)
>   public void testToCriteriaSpecDTO() {
> ```

I think we can add comments above test in test what case we are validating, same applies for others

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39890)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecDTOTest.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/39890#-NGV3rpW8c_UBLd2a698:-NGWDmiY1xKhPYT9DZBQ:b-bizqh8) ([raw file](https://github.com/harness/harness-core/blob/58eadad943a1b729863f95c5eb44dfbc45d3f5c1/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecDTOTest.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

What are we testing?
</blockquote></details>

Added comment.
___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecTest.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/39890#-NGV3wOq0OhLPYstAwOp:-NGWDmJb1AQtjwmkVYtg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/58eadad943a1b729863f95c5eb44dfbc45d3f5c1/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/beans/KeyValuesCriteriaSpecTest.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think we can add comments above test in test what case we are validating, same applies for others
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39890)* status: Some of the checks are too old. 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger checkstylecodeformat

**Pull request merged**
