### PR TITLE
[feat]: [CDS-56695]: add new version for on-prem

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
[feat]: [CDS-56695]: add new version for on-prem
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-56695]: https://harness.atlassian.net/browse/CDS-56695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)

### CODE REVIEW

**Review by alebuh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: :shipit: complete! ✓

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: :shipit: complete! ✓

___
*[`on-prem/disconnected_on_prem_pov_installer/generate.sh` line 231 at r1](https://reviewable.io/reviews/harness/harness-core/45622#-NRJSKbx1l521KelLJib:-NRJSKbx1l521KelLJic:big65kr) ([raw file](https://github.com/harness/harness-core/blob/58da250ed616e5e2a80ba01a07150600624209d3/on-prem/disconnected_on_prem_pov_installer/generate.sh#L231)):*
> ```Shell
> done
> 
> for tfConfigInspectVersion in v1.0 v1.1 v1.2; do
> ```

talked about it offline, we will enable the flag to use 1.1 and remove 1.0 and then put 1.2 behind flag

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`on-prem/disconnected_on_prem_pov_installer/generate.sh` line 231 at r1](https://reviewable.io/reviews/harness/harness-core/45622#-NRJSKbx1l521KelLJib:-NRJVyDr0HfqN9EbKgvV:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/58da250ed616e5e2a80ba01a07150600624209d3/on-prem/disconnected_on_prem_pov_installer/generate.sh#L231)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

talked about it offline, we will enable the flag to use 1.1 and remove 1.0 and then put 1.2 behind flag
</blockquote></details>

Done

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: :shipit: complete! ✓

**Review by alebuh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45622)* status: :shipit: complete! ✓

**Pull request merged**
