### PR TITLE
[feat]: [PIE-4167]: Added UTs for get yaml-execution api

### PR DESCRIPTION
**Pull request by smjt-h**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34401)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34401)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java` line 300 at r1](https://reviewable.io/reviews/harness/harness-core/34401#-N4fmcNuB-iQKpL_ZiRC:-N4fmcNv6jdsA_tblKI8:b-b11fft) ([raw file](https://github.com/harness/harness-core/blob/74341c62b32b817e857115379fb6d32864356a7c/800-pipeline-service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java#L300)):*
> ```Java
>     String planExecutionID = "tempID";
>     String executionyaml =
>         "pipeline:\\n  identifier: \\\"templ\\\"\\n  name: \\\"templ\\\"\\n  projectIdentifier: \\\"localproj\\\"\\n  orgIdentifier: \\\"default\\\"\\n  tags: {}\\n  stages:\\n  - stage:\\n      identifier: \\\"fij\\\"\\n      type: \\\"CI\\\"\\n      name: \\\"fij\\\"\\n      spec:\\n        cloneCodebase: false\\n        infrastructure:\\n          type: \\\"KubernetesDirect\\\"\\n          spec:\\n            connectorRef: \\\"deligateplay\\\"\\n            namespace: \\\"harness-delegate\\\"\\n            automountServiceAccountToken: true\\n            nodeSelector: {}\\n        execution:\\n          steps:\\n          - step:\\n              identifier: \\\"knk\\\"\\n              type: \\\"Run\\\"\\n              name: \\\"knk\\\"\\n              spec:\\n                connectorRef: \\\"account.harnessImage\\\"\\n                image: \\\"golang\\\"\\n                shell: \\\"Sh\\\"\\n                command: \\\"echo aaalo\\\"\\n              failureStrategies: []\\n          - step:\\n              identifier: \\\"tw\\\"\\n              type: \\\"Run\\\"\\n              name: \\\"tw\\\"\\n              spec:\\n                connectorRef: \\\"account.harnessImage\\\"\\n                image: \\\"golang\\\"\\n                shell: \\\"Sh\\\"\\n                command: \\\"echo eeee\\\"\\n";
> ```

read this from a file in test/resources folder

**Review by smjt-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34401)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java` line 300 at r1](https://reviewable.io/reviews/harness/harness-core/34401#-N4fmcNuB-iQKpL_ZiRC:-N4ftcdx7Fojgmx_0rQc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/74341c62b32b817e857115379fb6d32864356a7c/800-pipeline-service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java#L300)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

read this from a file in test/resources folder
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34401)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34401)* status: :shipit: complete! ✓

**Pull request merged**
