### PR TITLE
feat: [CDS-39331]: Support Azure Repo Connector for Create PR Step

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Support Azure Repo Connector for Create PR Step

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/35038#-N6GpmRs45eGkzzxkFbu:-N6GpmRs45eGkzzxkFbv:b5shv8a) ([raw file](https://github.com/harness/harness-core/blob/a013fc1fce242ff1c9bf284ba808cc032ece8027/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L148)):*
> ```Java
>         connectorUtils.getConnectorDetails(identifierRef, identifierRef.buildScopedIdentifier());
> 
>     GitStoreDelegateConfig gitStoreDelegateConfig = getGitStoreDelegateConfig(ambiance, releaseRepoOutcome);
> ```

We should probably extract it out to a method
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AzureRepoStore.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/35038#-N6Gqa53AD3F4dC6Sgta:-N6Gqa53AD3F4dC6Sgtb:b-32h3om) ([raw file](https://github.com/harness/harness-core/blob/a013fc1fce242ff1c9bf284ba808cc032ece8027/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AzureRepoStore.java#L49)):*
> ```Java
> @EqualsAndHashCode(callSuper = false)
> @JsonTypeName(ManifestStoreType.AZURE_REPO)
> @OneOfField(fields = {"paths", "folderPath"})
> ```

We don't need both for ReleaseRepo. We can keep it as it will be used by CDP later on



_Code quote:_
```Java
{"paths", "folderPath"}
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AzureRepoStore.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/35038#-N6GqVYt4xtfc75C7-0m:-N6GqVYt4xtfc75C7-0n:bubkj2e) ([raw file](https://github.com/harness/harness-core/blob/a013fc1fce242ff1c9bf284ba808cc032ece8027/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AzureRepoStore.java#L52)):*
> ```Java
> @OneOfField(fields = {"branch", "commitId"})
> @SimpleVisitorHelper(helperClass = ConnectorRefExtractorHelper.class)
> @TypeAlias("gitLabStore")
> ```

This has to be AzureRepo



_Code quote:_
```Java
gitLabStor
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 291 at r1](https://reviewable.io/reviews/harness/harness-core/35038#-N6GrJW34ogmRCYSvFpG:-N6GrJW34ogmRCYSvFpH:blnkv42) ([raw file](https://github.com/harness/harness-core/blob/a013fc1fce242ff1c9bf284ba808cc032ece8027/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L291)):*
> ```Java
>       case AZURE_REPO:
>         AzureRepoConnectorDTO azureRepoConnectorDTO = (AzureRepoConnectorDTO) scmConnector;
>         //POST https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullrequests?api-version=5.1
> ```

Is this intentionally here?



_Code quote:_
```Java
//POST https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullrequests?api-version=5.1
```

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/35038#-N6GpmRs45eGkzzxkFbu:-N6H-R5C9wRG__CijajX:b8re3f6) ([raw file](https://github.com/harness/harness-core/blob/a013fc1fce242ff1c9bf284ba808cc032ece8027/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L148)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

We should probably extract it out to a method
</blockquote></details>

AzureRepo is not yet implemented for MergeStep, will create a function when I add it.

**Comment by anshul-harness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AzureRepoStore.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/35038#-N6Gqa53AD3F4dC6Sgta:-N6H-if-8424ztvR_x_1:bb7s9zc) ([raw file](https://github.com/harness/harness-core/blob/a013fc1fce242ff1c9bf284ba808cc032ece8027/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AzureRepoStore.java#L49)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

so, keep as is correct? 
</blockquote></details>

yes

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Review by anshul-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger ti0

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 5 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 5 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35038)* status: :shipit: complete! ✓

**Pull request merged**
