### PR TITLE
[feat]: [PIE-4435]: Add lastExecutionTs to pipeline entity

### PR DESCRIPTION
**Pull request by namanvermah**
Updating last execution Ts field whenever execution summary info is being updated in pipeline entity. When the summary info field is gone, only this field will update during create event for executions.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35596)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
What will happen to existing PipelineEntity Collections, we won't be able to sort them until they execute atleast once?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35596)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35596)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
will keep on using the existing field. Closing this

**Pull request closed without merging**
