### PR TITLE
feat: [CDS-68153]: Fix init step in CD as well ssca step

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47078)

### CODE REVIEW

**Review by inderschera — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47078)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47078)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/47078#-NU65uuO4QRhi7K5YYI1:-NU65uuO4QRhi7K5YYI2:b-o94dmw) ([raw file](https://github.com/harness/harness-core/blob/b291d4b587868bf87dbc5fa44381e8a5ea7dfbe3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java#L87)):*
> ```Java
>       boolean isMonitored) {
>     if (INIT_CONTAINER_V2_STEP_TYPE.getType().equals(
>             AmbianceUtils.obtainCurrentLevel(ambiance).getStepType().getType())) {
> ```

There is a method in utils getCurrentStepType use that

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/47078#-NU65uuO4QRhi7K5YYI1:-NUQq7bE2ZPOFLn--CQR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b291d4b587868bf87dbc5fa44381e8a5ea7dfbe3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events/PmsEventSender.java#L87)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

There is a method in utils getCurrentStepType use that
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47078)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47078)* status: 1 change requests. 1. unresolved discussions.

**Comment by sahilhindwani-harness** [comment]
trigger review

**Comment by sahilhindwani-harness** [comment]
trigger review

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47078)* status: 1 change requests. 1. unresolved discussions.

**Review by inderschera — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47078#-:-NUR7m8UCa1rB4WHsQEp:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
