### PR TITLE
[fix]: [CDS-40046]: validating timeout properties workflow

### PR DESCRIPTION
**Pull request by lasdox**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)

### CODE REVIEW

**Review by poojaSinghal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/35383#-N7Jufq-3fchwOYc8hWU:-N7Jufq02q-O23TNaFmJ:b-pxdgey) ([raw file](https://github.com/harness/harness-core/blob/a72981164f58a2bf42065c170807c9cbd1290487/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java#L95)):*
> ```Java
>   @Inject private ServiceResourceService serviceResourceService;
> 
>   public void validatePhaseStepsProperties(PhaseStep phaseStep) {
> ```

Instead of this, we already have a ApprovalStepYamlBuilder which validates a steps yaml . Can you check if this can be added there? 

Also, please check same for pipeline approvals as well. 
For that as well, you should add it in YAML conversion ?

**Comment by lasdox** [comment]
> ApprovalStepYamlBuilder



> > Reviewed 3 of 4 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)_ status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/35383#-N7Jufq-3fchwOYc8hWU:-N7Jufq02q-O23TNaFmJ:b-pxdgey) ([raw file](https://github.com/harness/harness-core/blob/a72981164f58a2bf42065c170807c9cbd1290487/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java#L95)):_
> 
> > ```java
> >   @Inject private ServiceResourceService serviceResourceService;
> > 
> >   public void validatePhaseStepsProperties(PhaseStep phaseStep) {
> > ```
> 
> Instead of this, we already have a ApprovalStepYamlBuilder which validates a steps yaml . Can you check if this can be added there?
> 
> Also, please check same for pipeline approvals as well. For that as well, you should add it in YAML conversion ?

Hey @poojaSinghal , the problem with this approach is that when ApprovalStepYamlBuilder validates the step yaml, the workflow is already updated in db, letting it in an invalid state.
This is the current behaviour, the db is being updated before the validation.

**Review by poojaSinghal — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383#-:-N7QYsJc0M29UhJbSmFH:bnfp4nl)* status: 1 file(s) to review.

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/35383#-N7R1ysB24cMIvD_Jgvf:-N7R1ysB24cMIvD_Jgvg:bkjqhxb) ([raw file](https://github.com/harness/harness-core/blob/a72981164f58a2bf42065c170807c9cbd1290487/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java#L111)):*
> ```Java
>       CanaryOrchestrationWorkflow canaryOrchestrationWorkflow =
>           (CanaryOrchestrationWorkflow) newWorkflow.getOrchestrationWorkflow();
>       canaryOrchestrationWorkflow.getWorkflowPhases().forEach(workflowPhase -> {
> ```

what happens to phases already having more timeout?

**Comment by lasdox** [comment]
> > Reviewed 1 of 4 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)_ status: :shipit: complete! ✓
> 
> _[`400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/35383#-N7R1ysB24cMIvD_Jgvf:-N7R1ysB24cMIvD_Jgvg:bkjqhxb) ([raw file](https://github.com/harness/harness-core/blob/a72981164f58a2bf42065c170807c9cbd1290487/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java#L111)):_
> 
> > ```java
> >       CanaryOrchestrationWorkflow canaryOrchestrationWorkflow =
> >           (CanaryOrchestrationWorkflow) newWorkflow.getOrchestrationWorkflow();
> >       canaryOrchestrationWorkflow.getWorkflowPhases().forEach(workflowPhase -> {
> > ```
> 
> what happens to phases already having more timeout?

it will raise the InvalidRequestException asking to change it.
It will be better because otherwise user needs to try execute workflow to get the error message, in this case the error will happen in update operation.

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/35383#-N7R1ysB24cMIvD_Jgvf:-N7R6tqw1JTI2OqTAXwH:bwxbawl) ([raw file](https://github.com/harness/harness-core/blob/a72981164f58a2bf42065c170807c9cbd1290487/400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceTemplateHelper.java#L111)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

it will raise the InvalidRequestException asking to change it.
It will be better because otherwise user needs to try execute workflow to get the error message, in this case the error will happen in update operation.

</blockquote></details>

lets have list compiled via db query - we should have list of customer who have issue to be proactive

**Review by srinivaswings — APPROVED** [review]

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35383)* status: :shipit: complete! ✓

**Pull request merged**
