### PR TITLE
feat: [DEL-5430]: Enable Queuing for CI Delegate Task

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary: 
- Enable Queueing for CI delegate tasks based on FF 
- Executor service to dequeue delegate task from queue service

Test performed

- Local Testing with queue service to queue and dequeue task 
- Unit test

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42134)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1349 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsS1LREc5KyLWRWuhs:-NKsS1LREc5KyLWRWuht:b-xta5vz) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1349)):*
> ```Java
> 
>     delegateExecutor.scheduleWithFixedDelay(
>         new Schedulable("Failed to dequeue delegate task", injector.getInstance(DelegateTaskQueueService.class)), 0L,
> ```

are we dequeuing every two mins?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSDH51wTVZ7w_Glhk:-NKsSDH51wTVZ7w_Glhl:bou3pl5) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L140)):*
> ```Java
>                                  .execute()
>                                  .body();
>       assert response != null;
> ```

what happens if it is null? or the queue service guarantees that it won't be null?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSMkME6qD99qu6Zzw:-NKsSMkME6qD99qu6Zzx:btq1f71) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L151)):*
> ```Java
>   }
> 
>   public boolean isResourceAvailableToAssignTask(DelegateTask delegateTask) {
> ```

why is this public?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSpfl4PVRdtCvHRIl:-NKsSpfl4PVRdtCvHRIm:b-4edsey) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L187)):*
> ```Java
>         String itemId =
>             acknowledge(delegateTaskDequeue.getItemId(), delegateTaskDequeue.getDelegateTask().getAccountId());
>         log.info("Delegate task {} acknowledge with item id {} from Queue Service",
> ```

do we need these logs? it will be expensive to log these

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1967 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT-KK5POgjkOtkXw-:-NKsT-KK5POgjkOtkXw0:bpwphq1) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1967)):*
> ```Java
>   public String saveAndBroadcastDelegateTaskV2(DelegateTask delegateTask) {
>     delegateTask.setBroadcastToDelegateIds(Lists.newArrayList(delegateTask.getEligibleToExecuteDelegateIds().get(0)));
>     if (delegateTask.getTaskDataV2().isAsync()) {
> ```

we should get rid of this isAsync check. All tasks should be broadcasted after 5 seconds

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 2006 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT65r86Z3oiztIURD:-NKsT65r86Z3oiztIURE:btxaxon) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L2006)):*
> ```Java
>   private void saveDelegateTask(DelegateTask delegateTask, String accountId) {
>     if (featureFlagService.isEnabled(QUEUE_CI_EXECUTIONS, accountId)
>         && delegateTaskQueueService.isResourceAvailableToAssignTask(delegateTask)) {
> ```

shouldn't it be other way round? only if the resource not available we should queue

**Comment by jennyjames21** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1349 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsS1LREc5KyLWRWuhs:-NKsibVu-NdKJkkgQtqt:b-ev3r3d) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1349)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

are we dequeuing every two mins?
</blockquote></details>

yes, is it less or more according to you? Average time to execute task is 2 mins, that's why choose 2

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSMkME6qD99qu6Zzw:-NKsjL191HqXcSz3BTLe:b-wp30sa) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L151)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why is this public?
</blockquote></details>

it's used in unit test as well as in DelegateTaskServiceClassicImpl

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsTFLB4uznq0_sXlQb:-NKsja5-0Ikmzqh_C-94:bj40yuo) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L182)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why are these methods made public. Reconsider to make as much as possible private
</blockquote></details>

for unit testing

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSpfl4PVRdtCvHRIl:-NKsjcE01OJGA5knbXjf:b-ekwaur) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L187)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we need these logs? it will be expensive to log these
</blockquote></details>

we can remove after more accounts get enabled for queuing. On initial stage it's needed

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsTFLB4uznq0_sXlQb:-NKsp34yAFH1r_3ap2xd:bt3vbns) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L182)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

for unit testing
</blockquote></details>

  @VisibleForTesting with protected never works, not sure any other way around

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1967 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT-KK5POgjkOtkXw-:-NKsqBoC8H2I6dbawh9E:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1967)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should get rid of this isAsync check. All tasks should be broadcasted after 5 seconds
</blockquote></details>

done

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 164 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSZv17m2UH620Maz1:-NKsqFIg3cqTq5SU3XvO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L164)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you should call v2 in the v1
</blockquote></details>

done

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSDH51wTVZ7w_Glhk:-NKsqHKGCFIshoCtEqjV:bn13eqx) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L140)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what happens if it is null? or the queue service guarantees that it won't be null?
</blockquote></details>

updated with Objects.requireNonNull. Either way, it will throw an exception for a null response and we print it. It will remain in the queue so it will show up on the next iteration for dequeue.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSpfl4PVRdtCvHRIl:-NKsqsy99lgwBXUcPDge:b-aiegdr) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L187)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

we can remove after more accounts get enabled for queuing. On initial stage it's needed
</blockquote></details>

Note queue has TTL to remove after a few hours. How to send the response back on the such case is pending

**Comment by raghuAtWings** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1349 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsS1LREc5KyLWRWuhs:-NKsv3JS4F6f9aT4mPPo:b-ak0oce) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1349)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes, is it less or more according to you? Average time to execute task is 2 mins, that's why choose 2
</blockquote></details>

2 mins is pretty big i think. It should be like 10-15 seconds. Since eventually we will have other tasks go through this logic as well

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSDH51wTVZ7w_Glhk:-NKsvJD0-VkpZivZQkhb:b-lk3aof) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L140)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

updated with Objects.requireNonNull. Either way, it will throw an exception for a null response and we print it. It will remain in the queue so it will show up on the next iteration for dequeue. 
</blockquote></details>

will it block other tasks to get picked?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSMkME6qD99qu6Zzw:-NKsvMtp2uIDL40PmTOe:b-kjxwqr) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L151)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

it's used in unit test as well as in DelegateTaskServiceClassicImpl
</blockquote></details>

for unit test we should make package protected.

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsTFLB4uznq0_sXlQb:-NKsvSNhB76hhn0vmsj6:b-vilqj8) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L182)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

  @VisibleForTesting with protected never works, not sure any other way around
</blockquote></details>

remove the public identifier so its package protected, move the test in the same package

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/42134#-NKsvcF64jwGB2hzek5v:-NKsvcF64jwGB2hzek5w:b-sd53lo) ([raw file](https://github.com/harness/harness-core/blob/2b0bdfb6726b5d1c645cab6848278f8c73dc151b/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L207)):*
> ```Java
>   public void acknowledgeAndProcessDelegateTaskV2(DelegateTaskDequeue delegateTaskDequeue) {
>     try {
>       if (delegateTaskDequeue.getDelegateTask() != null) {
> ```

here also we should use V1 method

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1967 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT-KK5POgjkOtkXw-:-NKsvfqCDcFR7gSFbCer:b-jp1mip) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1967)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

done
</blockquote></details>

please make sure its removed in all flows.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42134)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1349 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsS1LREc5KyLWRWuhs:-NKsx7m-DOaVz9m9R_tL:b-tmocca) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1349)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

2 mins is pretty big i think. It should be like 10-15 seconds. Since eventually we will have other tasks go through this logic as well
</blockquote></details>

will 15 seconds be too aggressive?
 if resource is not available then what are odds it will be available after 15 seconds?
Maybe a minute to start with?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSDH51wTVZ7w_Glhk:-NKsxmTrCj7ymjdG3ZSO:b-esi5b2) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L140)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

will it block other tasks to get picked?
</blockquote></details>

Here the response is for a batch of max 100 tasks, not per task.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1967 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT-KK5POgjkOtkXw-:-NKt6YDf-yBe51RXgx0q:b-vxn1bf) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1967)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

please make sure its removed in all flows. 
</blockquote></details>

you mean regular task flow? that's is big change, need to think through more on that, maybe another PR to track that

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/42134#-NKsvcF64jwGB2hzek5v:-NKt6qOS6rSVwBgPnsLw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2b0bdfb6726b5d1c645cab6848278f8c73dc151b/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L207)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

here also we should use V1 method
</blockquote></details>

done

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsTFLB4uznq0_sXlQb:-NKt6s89EFnCFNdA4QQ-:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L182)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

remove the public identifier so its package protected, move the test in the same package 
</blockquote></details>

done

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSMkME6qD99qu6Zzw:-NKt6tQK3nq3YYVjoQSM:bw571kf) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L151)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

for unit test we should make package protected. 
</blockquote></details>

moved unit test to correct package

**Comment by raghuAtWings** [comment]
*[`360-cg-manager/src/main/java/software/wings/app/WingsApplication.java` line 1349 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsS1LREc5KyLWRWuhs:-NKtJXC77BJu20TXJT-B:bnj5ye3) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L1349)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

will 15 seconds be too aggressive?
 if resource is not available then what are odds it will be available after 15 seconds?
Maybe a minute to start with?
</blockquote></details>

i am assuming that the resource consumption on checking and putting in back would be very minimal so 15 seconds should not be a big deal

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSMkME6qD99qu6Zzw:-NKtV34M-VBZ9XWPFfb8:beucgt) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L151)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

moved unit test to correct package
</blockquote></details>

but its still public

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsSMkME6qD99qu6Zzw:-NKtY6xG7MEEFL3BDr43:b-idd2jw) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L151)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

but its still public
</blockquote></details>

that one is used in DelegateTaskServiceClassicImpl to check resource available first time before queueing

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1967 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT-KK5POgjkOtkXw-:-NKtcwrR95TkWnRPDkvw:b5jzqwu) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1967)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

you mean regular task flow? that's is big change, need to think through more on that, maybe another PR to track that 
</blockquote></details>

it came in one of the CFD triagging. We were broadcasting and acquiring the task immediately. There is no need of broadcasting the tasks again immediately.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1967 at r1](https://reviewable.io/reviews/harness/harness-core/42134#-NKsT-KK5POgjkOtkXw-:-NKtnYzEAOhi349_j4N7:byd8w3y) ([raw file](https://github.com/harness/harness-core/blob/e0d0750a8e41c032f40fcca845492630c090a892/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1967)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

it came in one of the CFD triagging. We were broadcasting and acquiring the task immediately. There is no need of broadcasting the tasks again immediately. 
</blockquote></details>

lets discuss this more on this. For the sync task, 5 seconds delay is not a good idea IMO. Can you send me CFD details?

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42134)* status: 4 file(s) to review. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42134)* status: :shipit: complete! ✓

**Pull request merged**
