### PR TITLE
feat: [CDS-85379]: Add basic montitoring metrics for template service

### PR DESCRIPTION
**Pull request by Y0709**
Add metrics for template Service

Screenshot 2023-11-28 at 1 59 50 PM

Enabled monitoring for all api's in open api docs for templates and non hidden api's
https://apidocs.harness.io/tag/Templates#operation/getTemplateMetadataList 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56045)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 9 of 9 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56045)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut0, ut9

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r2, 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56045)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateRefreshResource.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPADIq3N1zDxhHSaW5:-NkPADIq3N1zDxhHSaW6:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateRefreshResource.java#L109)):*
> ```Java
>   @Path("refreshed-yaml")
>   @Timed
>   @ResponseMetered
> ```

same for this



_Code quote:_
```Java
o
```
___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateRefreshResource.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPAA2SB5tk_-zOtiqj:-NkPAA2SB5tk_-zOtiqk:b-pyp5vx) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateRefreshResource.java#L134)):*
> ```Java
>   @Path("validate-template-inputs")
>   @Timed
>   @ResponseMetered
> ```

i think we can ignore this for now
___
*[`template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateRefreshResource.java` line 178 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPA7uE8btkq_bTe6bL:-NkPA7uE8btkq_bTe6bM:bn84v8t) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/contracts/src/main/java/io/harness/template/resources/NGTemplateRefreshResource.java#L178)):*
> ```Java
>   @Path("show-diff")
>   @Timed
>   @ResponseMetered
> ```

this is hidden so dont need it
___
*[`template-service/service/src/main/java/io/harness/metrics/TemplateServiceDwMetricsPublisher.java` line 184 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPARbh5xW8oRGGw_J_:-NkPARbh5xW8oRGGw_Ja:b-b702g1) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/service/src/main/java/io/harness/metrics/TemplateServiceDwMetricsPublisher.java#L184)):*
> ```Java
>   private boolean checkIfResourceMetrics(String metricName, String additionalMetricNameCheck) {
>     List<String> resourcesList = List.of(
>         "NGTemplateResource", "NGGlobalTemplateResource", "NGTemplateRefreshResource", "NGTemplateSchemaResource");
> ```

update this list based on resources shared above



_Code quote:_
```Java
NGTemplateResource", "NGGlobalTemplateResource", "NGTemplateRefreshResource", "NGTemplateSchemaResource"
```
___
*[`template-service/service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPAXnp2gVmwLA9t1Up:-NkPAXnp2gVmwLA9t1Uq:bz8jalb) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java#L46)):*
> ```Java
>   @Override
>   @Timed
>   @ResponseMetered
> ```

currently openapi are not getting captured, so remove those
___
*[`template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group.yaml` line 5 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPAfDN-3Rp8BT8NS7F:-NkPAfDN-3Rp8BT8NS7G:b-ma3nkf) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group.yaml#L5)):*
> ```YAML
> labels:
>   - namespace
>   - containerName
> ```

lets remove containerName from all, including pipeline-service
___
*[`template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group_http_method.yaml` line 6 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPAhhEAiF0oxXaXQ-8:-NkPAhhEAiF0oxXaXQ-9:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group_http_method.yaml#L6)):*
> ```YAML
>   - method
>   - namespace
>   - containerName
> ```

same as above
___
*[`template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group_resources.yaml` line 7 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPAiU-17P26Z8hrugf:-NkPAiU-17P26Z8hrugg:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group_resources.yaml#L7)):*
> ```YAML
>   - resource
>   - namespace
>   - containerName
> ```

same as above
___
*[`template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group_resources_responses.yaml` line 8 at r3](https://reviewable.io/reviews/harness/harness-core/56045#-NkPAjWa5NoeNANnNKVr:-NkPAjWa5NoeNANnNKVs:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/cefbf600d320ccc4d2ada11b6b0ea7604d786c64/template-service/service/src/main/resources/metrics/metricGroups/template_service_dw_metrics_group_resources_responses.yaml#L8)):*
> ```YAML
>   - statusCode
>   - namespace
>   - containerName
> ```

same as above

**Review by archit-harness — APPROVED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56045)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
