### PR TITLE
feat:[CDS-52326]: Terraform Cloud rollback step delegate side

### PR DESCRIPTION
**Pull request by alebuh**
## Describe your changes
Delegate side changes for Terraform Cloud Rollback step
Change Run status to be an enum
Refactor code
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)

### CODE REVIEW

**Comment by aman-harness** [comment]
trigger gitleaks

**Review by vlica-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraformcloud/RunRequestCreator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/44004#-NOtwNb_1NPEms8BBnbh:-NOtwNb_1NPEms8BBnbi:bafgykx) ([raw file](https://github.com/harness/harness-core/blob/ef74e07096a7174867f7bccb9f5db34995960588/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraformcloud/RunRequestCreator.java#L47)):*
> ```Java
>   private static final String WORKSPACES = "workspaces";
>   private static final String CV_VERSION = "configuration-version";
>   private static final String CV_VERSIONS = "configuration-versions";
> ```

What CV in CV_VERSION means ? :)

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraformcloud/RunRequestCreator.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/44004#-NOtwNb_1NPEms8BBnbh:-NOxHW1w2RO1eUh870HZ:b-y6yk4l) ([raw file](https://github.com/harness/harness-core/blob/ef74e07096a7174867f7bccb9f5db34995960588/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraformcloud/RunRequestCreator.java#L47)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

What CV in CV_VERSION means ? :)
</blockquote></details>

Changed now

**Review by vlica-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)* status: 1 of 2 approvals obtained.

**Review by vlica-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004#-:-NP2h0W93YiZPGcVmYjx:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44004)* status: :shipit: complete! ✓

**Pull request merged**
