### PR TITLE
[fix]: [PL-31077]: New User AccountLevel data and related CRUD API changes

### PR DESCRIPTION
**Pull request by shashank-harness**
Store User Data with newly introduced AccountLevelData property for each account this user is part of.
Details about the root cause and solution [here](https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21272101267/Solving+User+Management+In+Harness)

## Describe your changes

Specifically, this PR does below things:

1. For a User, add new mapping of each account to userAccountLevelData, which contains:

     - **Source of Provisioning** of a User in a Generation in an Account. Example, User1 was added in Acc1 as a SCIM user in CG and Manual user in NG in the same account
     - **Generations** to which this user is provisioned. Example: User1 is part of CG & NG while User2 is part of NG only.
     - **[In separate PR] Preference data** like a User's Default Experience in an account irrespective of what has been set at Account level for all Users.

2. Changes to CRUD APIs of User entity for this new mapping.
3. Changes are behind FF PL_USER_ACCOUNT_LEVEL_DATA_FLOW

**Testing**
- Testing done for various scenarios listed [here](https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21272101267/Solving+User+Management+In+Harness#Testing-Done)
- Testing done with and without FF
- This PR should be merged with PR for Migration Job[TBD] in order to properly test existing users too.

**Note:** PR for API to set Default Experience PR created separately as this one was becoming huge. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45273)

### CODE REVIEW

**Comment by shashank-harness** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger utAll

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/scheduler/LdapGroupSyncJobHelper.java` line 293 at r9](https://reviewable.io/reviews/harness/harness-core/45273#-NSwdmLS4VAK73OzByRr:-NSwdmLS4VAK73OzByRs:bdv9lwa) ([raw file](https://github.com/harness/harness-core/blob/3ca6cdc7c9976f2d6de764548e518f0379cd2576/400-rest/src/main/java/software/wings/scheduler/LdapGroupSyncJobHelper.java#L293)):*
> ```Java
>                                         .withUserGroups(Lists.newArrayList(userGroups))
>                                         .withUserId(ldapUserResponse.getUserId())
>                                         .withSource(UserInviteSource.builder().type(SSO).build())
> ```

Invites source should be LDAP here?

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 17 files at r2, 9 of 18 files at r3, 8 of 11 files at r5, 1 of 2 files at r6, 3 of 3 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45273)* status: 27 file(s) to review. 0 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 17 files at r2, 9 of 18 files at r3, 6 of 11 files at r5, 1 of 2 files at r6, 3 of 3 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45273)* status: 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scheduler/LdapGroupSyncJobHelper.java` line 293 at r9](https://reviewable.io/reviews/harness/harness-core/45273#-NSwdmLS4VAK73OzByRr:-NT9eLID3WmJOgkwqAgy:b-1i6il1) ([raw file](https://github.com/harness/harness-core/blob/3ca6cdc7c9976f2d6de764548e518f0379cd2576/400-rest/src/main/java/software/wings/scheduler/LdapGroupSyncJobHelper.java#L293)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Invites source should be LDAP here?
</blockquote></details>

We currently do not have that option. Also, SSO type is used in other places for LDAP. SO, I will change this SSO to LDAP later in a separate PR as it will require more changes which are not part of this task's scope.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 17 files at r2, 9 of 18 files at r3, 6 of 11 files at r5, 1 of 3 files at r8, 4 of 6 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45273)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45273)* status: 1. unresolved discussions.

**Pull request merged**
