### PR TITLE
[fix]: [PIE-3238]: Fix retry for trigger executions

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31712)

### CODE REVIEW

**Review by aman-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31712#-:-MyuayrR6PmFVwgXZTkE:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31712#-:-Myub2QE0h4WoUy3kush:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31712#-:-Myub8Y7CTS0OCnkxBIk:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by devkimittal — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31712)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31712)* status: :shipit: complete! ✓

**Pull request merged**
