### PR TITLE
fix: [PIE-5808]: Fix trigger details APIs when eventId maps to more than one trigger

### PR DESCRIPTION
**Pull request by vcalasansh**
In the case of multiple triggers getting fired from a single webhook call, both `triggerProcessingDetails` and `triggerExecutionDetails` APIs are throwing errors, because internally they don't expect this scenario.

This PR fixes this by returning only one of the trigger events and adding a warning to the response in case multiple triggers were fired.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38799)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger messagecheck

**Review by sribalij — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38799)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38799)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/WebhookEventProcessingDetails.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/38799#-NEdZnO3393F4DabIupI:-NEdZnO3393F4DabIupJ:b-basjsf) ([raw file](https://github.com/harness/harness-core/blob/31ed75f842fd00eac4855c83f82238134fb4bbe8/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/WebhookEventProcessingDetails.java#L38)):*
> ```Java
>   Long eventCreatedAt;
>   String runtimeInput;
>   String multipleEventsWarning;
> ```

nit, can this be just warningMsg like we have errorMsg?

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38799)* status: Some of the checks are too old.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38799)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
