### PR TITLE
[feat]:[pl-29319]: Branch and repo filter impl for executionDetails

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added implementations for repoListing and branchListing in execution history page and repoListing in pipeline listing page. Have tested out the all the 3 cases and works successfully.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39412)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39412)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/39412#-NFhQSiO5GXHkAv0ZLHl:-NFhQSiO5GXHkAv0ZLHm:b-d5g2bv) ([raw file](https://github.com/harness/harness-core/blob/2317c48f5a5d9600ded780a88305eaebd2f899f8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L148)):*
> ```Java
>             + "branch",
>         PipelineExecutionSummaryEntity.class, String.class);
>   }
> ```

Please add explain mongo db query when run in local or pr env, need to check winning plan and execution stats
example - query.explain("executionStats")

Also don't we should move this to read replica, refer pmsExecutionSummaryReadHelper

Plus use pagination in the api.



_Code quote:_
```Java
  public List<String> findAllUniqueRepos(Criteria criteria) {
    Query query = new Query(criteria);
    return mongoTemplate.findDistinct(query,
        PlanExecutionSummaryKeys.entityGitDetails + "."
            + "repoName",
        PipelineExecutionSummaryEntity.class, String.class);
  }

  @Override
  public List<String> findAllUniqueBranches(Criteria criteria) {
    Query query = new Query(criteria);
    return mongoTemplate.findDistinct(query,
        PlanExecutionSummaryKeys.entityGitDetails + "."
            + "branch",
        PipelineExecutionSummaryEntity.class, String.class);
  }
```

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39412)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/39412#-NFhQSiO5GXHkAv0ZLHl:-NFr27_y6clZkajrfDV8:b-djx06l) ([raw file](https://github.com/harness/harness-core/blob/2317c48f5a5d9600ded780a88305eaebd2f899f8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L148)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please add explain mongo db query when run in local or pr env, need to check winning plan and execution stats
example - query.explain("executionStats")

Also don't we should move this to read replica, refer pmsExecutionSummaryReadHelper

Plus use pagination in the api.
</blockquote></details>

1. I tried to run the query on mongo with explain("executionStats"), this was not returning anything, looking at ways, we can get this details
2. Have moved this db call to secondary db
3. As the pipeline will be tied to a particular project, we wont be having a lot repos or branches, hence we can skip the pagination at the moment and enhancing the query using search term as well

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39412)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/39412#-NFhQSiO5GXHkAv0ZLHl:-NFvqRTuECIf5GB98Kv5:b-rtc3zb) ([raw file](https://github.com/harness/harness-core/blob/2317c48f5a5d9600ded780a88305eaebd2f899f8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L148)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

1. I tried to run the query on mongo with explain("executionStats"), this was not returning anything, looking at ways, we can get this details
2. Have moved this db call to secondary db
3. As the pipeline will be tied to a particular project, we wont be having a lot repos or branches, hence we can skip the pagination at the moment and enhancing the query using search term as well

</blockquote></details>

As discussed, instead of the pagination, if the unique repo list or unique branch list is greater than 1000, we are logging an error



_Code quote (from pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java):_
```Java
CollectionUtils.filter(uniqueRepos, PredicateUtils.notNullPredicate());
```

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/39412#-NFwAk4Y1aTGy2XL_Ndy:-NFwAk4Y1aTGy2XL_Ndz:b-gotw9r) ([raw file](https://github.com/harness/harness-core/blob/251337e5cf6076c190505d20d4ab530a779080e8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L38)):*
> ```Java
>   }
> 
>   public List<String> findUniqueRepoOrBranchBasedOnFilter(Query query, @NotNull String projectFieldName) {
> ```

the implementation of this method doesn't relate to the method name. It could be any string field, not only branch or filter, so we should name the method more generically.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/39412#-NFwAk4Y1aTGy2XL_Ndy:-NFwAwno25izT8pmI8ee:b-xo43pu) ([raw file](https://github.com/harness/harness-core/blob/251337e5cf6076c190505d20d4ab530a779080e8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

the implementation of this method doesn't relate to the method name. It could be any string field, not only branch or filter, so we should name the method more generically.
</blockquote></details>

any field inside EntityGitDetails I meant ^

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/39412#-NFwAk4Y1aTGy2XL_Ndy:-NFwB6PJBaaWGsbi_zNL:bnsocy8) ([raw file](https://github.com/harness/harness-core/blob/251337e5cf6076c190505d20d4ab530a779080e8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

any field inside EntityGitDetails I meant ^
</blockquote></details>

Also the argument name should be accordingly, it shouldn't be generic like projectFieldName.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39412)* status: 15 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/39412#-NFwAk4Y1aTGy2XL_Ndy:-NFwOPIJCbp3bJ8FZoFE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/251337e5cf6076c190505d20d4ab530a779080e8/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also the argument name should be accordingly, it shouldn't be generic like projectFieldName.
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger ti0, ti1, ti2, ti3, ti4, ft1, ft2, codebasehash

**Comment by adivishy1** [comment]
trigger messagecheck, recency, pmd, checkstyle, ft1, ft2, i0, ti1, ti2, ti3, ti4, ft1, ft2, codebasehash, buildnum

**Pull request closed without merging**
