### PR TITLE
[feat]: [CDS-36738]: Support WinRm for infra definition

### PR DESCRIPTION
**Pull request by vitsafronovici**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)* status: 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32618#-N0kcxXMEGxu3sIL9wRX:-N0kcxXMEGxu3sIL9wRY:bhli1pn) ([raw file](https://github.com/harness/harness-core/blob/065bc2d152b9e69f0adc30256001fa01777301cb/120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java#L32)):*
> ```Java
> import io.harness.delegate.beans.connector.pdcconnector.HostConnectivityTaskParams;
> import io.harness.delegate.beans.connector.pdcconnector.HostConnectivityTaskResponse;
> import io.harness.delegate.beans.secrets.BaseConfigValidationTaskResponse;
> ```

nit: shall we rename it to `Host*` instead of `Base*` ?
___
*[`120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java` line 276 at r1](https://reviewable.io/reviews/harness/harness-core/32618#-N0kbWeP4eBDN1wdhxZj:-N0kbWeP4eBDN1wdhxZk:bwee940) ([raw file](https://github.com/harness/harness-core/blob/065bc2d152b9e69f0adc30256001fa01777301cb/120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java#L276)):*
> ```Java
>         .taskParameters(
>             WinRmTaskParams.builder().host(hostName).encryptionDetails(encryptionDetails).spec(secretSpecDTO).build())
>         .taskSetupAbstractions(setupTaskAbstractions(accountIdentifier, orgIdentifier, projectIdentifier))
> ```

i think we are missing here the delegate selector setup abstraction that @vladimir-peric was fixing also.
___
*[`120-ng-manager/src/test/java/io/harness/ng/validator/service/NGHostValidationServiceImplTest.java` line 170 at r1](https://reviewable.io/reviews/harness/harness-core/32618#-N0kcIvx7HCdbup5CKTY:-N0kcIvx7HCdbup5CKTZ:b2rghe5) ([raw file](https://github.com/harness/harness-core/blob/065bc2d152b9e69f0adc30256001fa01777301cb/120-ng-manager/src/test/java/io/harness/ng/validator/service/NGHostValidationServiceImplTest.java#L170)):*
> ```Java
>                                HOST, ACCOUNT_IDENTIFIER, ORG_IDENTIFIER, PROJECT_IDENTIFIER, SECRET_IDENTIFIER))
>         .isInstanceOf(InvalidArgumentsException.class)
>         .hasMessage(String.format("Invalid secret type, secret identifier: %s", SECRET_IDENTIFIER));
> ```

let's add also UT with winrm credentials checks

**Review by vitsafronovici — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618#-:-N0pHam92B1gtxjF9qMc:bb7f2mf)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)* status: 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/32618#-N0pQPmu0pquzTj0f7BD:-N0pQPmu0pquzTj0f7BE:bvkmu0t) ([raw file](https://github.com/harness/harness-core/blob/0b3b6f265e525b92120e122c4a92ec96c2296b45/120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java#L156)):*
> ```Java
> 
>   @Override
>   public List<HostValidationDTO> validateSSHHosts(@NotNull List<String> hosts, @Nullable String accountIdentifier,
> ```

Minor - rename this method from validateSSHHosts to validateHosts
___
*[`120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/32618#-N0pQDaF1Xqp3OyC1-EP:-N0pQDaG7NVpYGKa-8j2:b-blwtbv) ([raw file](https://github.com/harness/harness-core/blob/0b3b6f265e525b92120e122c4a92ec96c2296b45/120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java#L177)):*
> ```Java
> 
>   @Override
>   public HostValidationDTO validateSSHHost(@NotNull String host, String accountIdentifier,
> ```

Minor - rename this method from validateSSHHost to validateHost. 
We should update and host endpoint by removing ssh path( @Path("ssh")) and update description of endpoint in HostValidationResource because now we are using the same endpoint for both validations.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618#-:-N0pu61VC82Ww9u1KgfR:bnfp4nl)* status: 2. unresolved discussions.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)* status: 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java` line 156 at r2](https://reviewable.io/reviews/harness/harness-core/32618#-N0pQPmu0pquzTj0f7BD:-N0pxjGbAxYv203CTYOh:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0b3b6f265e525b92120e122c4a92ec96c2296b45/120-ng-manager/src/main/java/io/harness/ng/validator/service/NGHostValidationServiceImpl.java#L156)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - rename this method from validateSSHHosts to validateHosts
</blockquote></details>

done

**Review by vitsafronovici — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618#-:-N0pyGy57y-NOFhwZ25N:bb7f2mf)* status: 1. unresolved discussions.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)* status: :shipit: complete! ✓

**Comment by vitsafronovici** [comment]
trigger codebasehash

**Comment by jennyjames21** [comment]
*[`940-secret-manager-client/src/main/java/io/harness/delegate/beans/WinRmTaskParams.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/32618#-N0pLzJp9VkH4eqxN2Vp:-N0q4gnd6QkISMlRGF-L:b-41npry) ([raw file](https://github.com/harness/harness-core/blob/0b3b6f265e525b92120e122c4a92ec96c2296b45/940-secret-manager-client/src/main/java/io/harness/delegate/beans/WinRmTaskParams.java#L44)):*
<details><summary><i>Previously, vitsafronovici (Vitalie Safronovici) wrote…</i></summary><blockquote>

hz
</blockquote></details>

Recently delegate selectors are also introduced at stage and pipeline. Selectors at Connector ones will be ignored if present in pipeline or stage or step. This is under FF rite now.
https://harness.atlassian.net/wiki/spaces/DEL/pages/21025620016/Changes+to+Delegate+Scoping+in+NG?atlOrigin=eyJpIjoiMzNhZjQxMGNjYmViNGJmZmFhM2Q5OTY5ZWRiM2EzNzMiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ

Also see if you can use this helper class ConnectorCapabilityBaseHelper or set origin to "connector" instead of "task selector"

Im in process of make it consistent across, right now there is no logic based on origin but planning to add that as part of delegate selection log

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 1 of 3 files at r2, 3 of 5 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)* status: Some of the checks are too old.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 13 files at r1, 3 of 5 files at r4, 2 of 2 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32618)* status: :shipit: complete! ✓

**Pull request merged**
