### PR TITLE
fix: [CDS-69335]: fix ordering issue in map in ExpressionEvaluatorUtils

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** In FqnMapGenerator. generateFQNMapFromListOfSingleKeyMaps, we are assuming first element of the map as top key be an object node and looking for identifier there, earlier this function was not giving exception because __uuid field was coming at the end and the actual object node at first but with the latest pipeline-service, the uuid field started coming at the top and since the uuid is a text node rather than an expected object node, it is throwing NPE.

**Changes:** Fixed the updateExpressions function in ExpressionEvaluatorUtils to maintain the order of map and also, checking the top key be not uuid in FqnMapGenerator. generateFQNMapFromListOfSingleKeyMaps. 

**Testing:** Tested the behaviour locally and added a unit test.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47803)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47803)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/47803#-NVTUmNTBlioZylfbU1a:-NVTUmNTBlioZylfbU1b:blpqhja) ([raw file](https://github.com/harness/harness-core/blob/8c2a43bab633af5a2db7879690aed0ee8652ca41/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java#L132)):*
> ```Java
>         element.fieldNames().forEachRemaining(fieldNames::add);
>         String topKey = fieldNames.iterator().next();
>         if (keepUuidFields && topKey.equals(UUID_FIELD_NAME) && fieldNames.size() > 1) {
> ```

this code is finding the first field name in fieldNames that is not equal to the UUID_FIELD_NAME. If there is no such field name, the NoSuchElementException will be thrown by the get method call.

Thus what do we expect here? if exception, please log here just add a comment

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47803)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java` line 132 at r2](https://reviewable.io/reviews/harness/harness-core/47803#-NVTUmNTBlioZylfbU1a:-NVTdASz8iH9sJwKZfUZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8c2a43bab633af5a2db7879690aed0ee8652ca41/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java#L132)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this code is finding the first field name in fieldNames that is not equal to the UUID_FIELD_NAME. If there is no such field name, the NoSuchElementException will be thrown by the get method call.

Thus what do we expect here? if exception, please log here just add a comment
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47803)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
