### PR TITLE
[feat]: [PL-41293]: add parentId for Org and Project create/update flow

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Introduce a parentId for SCOPE (Org, Project) entities in Creation and Updation flow. Currently we use 'orgIdentifier, projectIdentifier' to determine an Org or Project scope for entity. With this change we are introducing the parentId field which would identify an entities unique Org/Project.

Testing done:

- New create Project has parentId populated (given the Org has uniqueId in it)
- New created Organization has parentId populated
- The OrgAddParentId migration populated the parentId as the accountIdentifier

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53729)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53729)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 176 at r3](https://reviewable.io/reviews/harness/harness-core/53729#-NgHUbUqAMgH0I4RMt3j:-NgHUbUqAMgH0I4RMt3k:b-cdxnai) ([raw file](https://github.com/harness/harness-core/blob/21231fa54268efaab45d33f0f9895dc267befb29/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L176)):*
> ```Java
>   @FeatureRestrictionCheck(MULTIPLE_PROJECTS)
>   public Project create(
>       @AccountIdentifier String accountIdentifier, String orgIdentifier, ProjectDTO projectDTO, String parentId) {
> ```

@pbarapatre10 Any reason for this API to take parentId as a parameter? Can it not be derived from Org?

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 176 at r3](https://reviewable.io/reviews/harness/harness-core/53729#-NgHUbUqAMgH0I4RMt3j:-NgI2tVm4tm7GcyYyPCy:bf84lbi) ([raw file](https://github.com/harness/harness-core/blob/21231fa54268efaab45d33f0f9895dc267befb29/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L176)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@pbarapatre10 Any reason for this API to take parentId as a parameter? Can it not be derived from Org?
</blockquote></details>

During default project creation with default Org, was passing the parentId to avoid re-caluclation of parentId from orgIdentifier. Removed it, thanks

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger ut6

**Comment by pbarapatre10** [comment]
trigger ut7

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53729#-:-NgI96Wf72gyCROzYHhU:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger ut6

**Pull request merged**
