### PR TITLE
[feat]: [CDS-46284]: add merge input api for env and infra

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

Written two apis, one for environment and one for infrastructure. Doing the same task.
Api Task:
Take an Input yaml of an entity from pipeline. Then compare it with inputs present in actual entity.
Then merge it.

Example : We can check following files
**Input set yaml from pipeline** : infrastructure-inputs-in-pipeline.yaml
**Actual Entity**: infrastructure-with-few-inputs.yaml
**Final merged input set yaml**:infrastructureInput-merged.yaml

  
  
  
  

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)

### CODE REVIEW

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 2 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: 19 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/39933#-NGZiH854Fz6hdhhVFgT:-NGZiH854Fz6hdhhVFgU:b-braqg4) ([raw file](https://github.com/harness/harness-core/blob/cc9560e63f96990c10712309544ff792fc8b317e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L501)):*
> ```Java
>   @ApiOperation(value = "This api merges old and new environment inputs YAML", nickname = "mergeEnvironmentInputs")
>   @Hidden
>   public ResponseDTO<EnvironmentInputsMergedResponseDto> mergeServiceInputs(
> ```

is method name correct?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/39933#-NGZiiE_2nB71Mt3TTYa:-NGZiiEa25Pb8dWdKDef:b-3dwd2s) ([raw file](https://github.com/harness/harness-core/blob/cc9560e63f96990c10712309544ff792fc8b317e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L503)):*
> ```Java
>   public ResponseDTO<EnvironmentInputsMergedResponseDto> mergeServiceInputs(
>       @Parameter(description = ENVIRONMENT_PARAM_MESSAGE) @PathParam(
>           "environmentIdentifier") @ResourceIdentifier String environmentIdentifier,
> ```

instead of environmentIdentifier, we can use NGCommonEntityConstants.ENVIRONMENT_IDENTIFIER_KEY
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 517 at r2](https://reviewable.io/reviews/harness/harness-core/39933#-NGZj6HfBxb7Jz2beHak:-NGZj6HfBxb7Jz2beHal:b-7tqhcb) ([raw file](https://github.com/harness/harness-core/blob/cc9560e63f96990c10712309544ff792fc8b317e/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L517)):*
> ```Java
>   @ApiOperation(value = "This api merges old and new infrastructure inputs YAML", nickname = "mergeInfraInputs")
>   @Hidden
>   public ResponseDTO<InfrastructureInputsMergedResponseDto> mergeServiceInputs(
> ```

same method name

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 517 at r2](https://reviewable.io/reviews/harness/harness-core/39933#-NGZj6HfBxb7Jz2beHak:-NGaI7XM0p9erZYSXB2M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc9560e63f96990c10712309544ff792fc8b317e/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L517)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

same method name
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/39933#-NGZiH854Fz6hdhhVFgT:-NGaJRQTDDCWXgBcLDZs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc9560e63f96990c10712309544ff792fc8b317e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L501)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

is method name correct?
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/39933#-NGZiiE_2nB71Mt3TTYa:-NGaJTlq1ZTEvA9y2t-r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc9560e63f96990c10712309544ff792fc8b317e/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L503)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

instead of environmentIdentifier, we can use NGCommonEntityConstants.ENVIRONMENT_IDENTIFIER_KEY
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 6 of 17 files at r2, 7 of 10 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYaml.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/39933#-NGgMMrbB7V2h-7lK3PC:-NGgMMrbB7V2h-7lK3PD:blfyzc8) ([raw file](https://github.com/harness/harness-core/blob/511e18b6466c5fd6755f62626f8626b617bc6783/125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYaml.java#L37)):*
> ```Java
> @Builder
> @SimpleVisitorHelper(helperClass = EnvironmentYamlVisitorHelper.class)
> @TypeAlias("infrastructureYaml")
> ```

is this expected ?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 655 at r5](https://reviewable.io/reviews/harness/harness-core/39933#-NGgMzzDBFuAqsHSfyIn:-NGgMzzDBFuAqsHSfyIo:b12wnj7) ([raw file](https://github.com/harness/harness-core/blob/511e18b6466c5fd6755f62626f8626b617bc6783/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L655)):*
> ```Java
>     try {
>       ObjectMapper mapper = new ObjectMapper();
>       List<Object> infraDefinitionInputListV2 = new ArrayList<>();
> ```

nit: v2 is not needed in the name
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 657 at r5](https://reviewable.io/reviews/harness/harness-core/39933#-NGgNw-T57oni-JfLl-4:-NGgNw-T57oni-JfLl-5:bf8s4rx) ([raw file](https://github.com/harness/harness-core/blob/511e18b6466c5fd6755f62626f8626b617bc6783/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L657)):*
> ```Java
>       List<Object> infraDefinitionInputListV2 = new ArrayList<>();
> 
>       createInfraDefinitionInputs(infrastructureEntity.get(), new ArrayList<>(), mapper, infraDefinitionInputListV2);
> ```

we should refactor this method to not modify the input arguments but to return, we can discuss offline
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/39933#-NGgNCKFB8NYB3LBQPMa:-NGgNCKFB8NYB3LBQPMb:bn40hes) ([raw file](https://github.com/harness/harness-core/blob/511e18b6466c5fd6755f62626f8626b617bc6783/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/InputSetMergeUtility.java#L29)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDC)
> @Singleton
> ```

Singleton does not make sense for a utility class

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYaml.java` line 37 at r5](https://reviewable.io/reviews/harness/harness-core/39933#-NGgMMrbB7V2h-7lK3PC:-NGo7ziD7Zowvxsabulz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/511e18b6466c5fd6755f62626f8626b617bc6783/125-cd-nextgen/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYaml.java#L37)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this expected ?
</blockquote></details>

Done.



_Code quote:_
```Java
@TypeAlias("environmentYaml")
```

**Comment by yogesh-chauhan** [comment]
trigger ft1

**Comment by yogesh-chauhan** [comment]
trigger ft2

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/dto/InfraDefinitionInputVersionedList.java` line 13 at r11](https://reviewable.io/reviews/harness/harness-core/39933#-NH8RIhL7LQTFLTGx4wh:-NH8RIhL7LQTFLTGx4wi:b-ygcn1s) ([raw file](https://github.com/harness/harness-core/blob/2830ca497637df3f79bb1a8325a8cc6c0100dd46/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/dto/InfraDefinitionInputVersionedList.java#L13)):*
> ```Java
> @Data
> @Builder
> public class InfraDefinitionInputVersionedList {
> ```

can this class be deleted ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, 5 of 8 files at r9, 15 of 15 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: Some of the checks are too old. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Comment by USB-05** [comment]
trigger ss

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: 3. unresolved discussions.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933#-:-NHPdBk-6DS0YnFBa2XC:bnfp4nl)* status: :shipit: complete! ✓

**Review by akhilpandey1 — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 3 of 17 files at r2, 4 of 10 files at r3, 1 of 2 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 4 of 8 files at r9, 15 of 15 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by akhilpandey1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 3 of 17 files at r2, 4 of 10 files at r3, 1 of 2 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 4 of 8 files at r9, 15 of 15 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by akhilpandey1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by rijajoo — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 3 of 17 files at r2, 4 of 10 files at r3, 1 of 2 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 4 of 8 files at r9, 15 of 15 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Review by AnshuH — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 2 of 17 files at r2, 4 of 10 files at r3, 1 of 2 files at r4, 1 of 3 files at r5, 1 of 3 files at r6, 4 of 8 files at r9, 15 of 15 files at r10, 1 of 1 files at r11, 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39933)* status: :shipit: complete! ✓

**Pull request merged**
