### PR TITLE
feat:[IE-83]: adding ce-nextgen chart to respective code repo

### PR DESCRIPTION
**Pull request by Vbhatia20**
## Describe your changes
adding ce-nextgen chart to respective code repo

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47295)

### CODE REVIEW

**Review by arya-harness — APPROVED** [review]

**Review by harness-jc — APPROVED** [review]

**Comment by Vbhatia20** [comment]
trigger uts

**Comment by Vbhatia20** [comment]
trigger copyrightcheck

**Comment by Vbhatia20** [comment]
trigger checkstylecodeformat

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Comment by Vbhatia20** [comment]
trigger copyrightcheck

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Comment by Vbhatia20** [comment]
trigger copyrightcheck

**Review by pranay-harness — DISMISSED** [review]
Identified secrets are Azure client id, which is not a secret.

Other secrets identified are place holder values and not used in prod

**Comment by Vbhatia20** [comment]
trigger uts

**Review by arya-harness — APPROVED** [review]

**Review by arya-harness — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47295)* status: :shipit: complete! ✓

**Review by harness-jc — APPROVED** [review]

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47295)* status: :shipit: complete! ✓

**Review by iamanmolm — APPROVED** [review]
Since we have changed the name back to ce-nextgen. Whenever we copy and move chart for batch-processing or any other service using the base url. Kindly do fix the service to service base url call as well, example: https://github.com/harness/helm-ccm/blob/90b7ec85c9a8486f6801901cabbfbd944991e73d/src/batch-processing/templates/config.yaml#L29.

**Pull request merged**
