### PR TITLE
fix: [CDS-52167]: K8SApply step does not work with inline values override

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
K8SApply step does not work with inline values override. Now we will handle those cases. also in this PR we handle the case when Git is sent as a value override in step and manifest store type is Harness-store. added test case for both the scenarios.
## Testing
For inline: replica set 2
Screenshot 2023-02-02 at 10 46 06 AM
For Git with replica:1
Screenshot 2023-02-02 at 10 46 36 AM
Tested with inline replica set as 2 and git set as 1:
Screenshot 2023-02-02 at 8 26 41 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)

### CODE REVIEW

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/43375#-NNGuU51044jAR-Nm3kD:-NNGuU51044jAR-Nm3kE:bwfjj8p) ([raw file](https://github.com/harness/harness-core/blob/8f3e400ba4ef476b9bb1401948a86a4304e87465/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L351)):*
> ```Java
>   }
> 
>   private boolean hasStepLevelFitOverrideForHarnessStore(StepElementParameters stepElementParameters) {
> ```

Is this method name correct?  The logic is to check if there any step overrides using git store

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/43375#-NNGuU51044jAR-Nm3kD:-NNGzVJe9UfqVZWfIUTM:b32v51) ([raw file](https://github.com/harness/harness-core/blob/8f3e400ba4ef476b9bb1401948a86a4304e87465/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L351)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this method name correct?  The logic is to check if there any step overrides using git store
</blockquote></details>

++

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/43375#-NNGuU51044jAR-Nm3kD:-NNH2BMw0dIJZ_PHcNJp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f3e400ba4ef476b9bb1401948a86a4304e87465/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L351)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

++
</blockquote></details>

Done.

**Review by abhinavsingh1196 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by TarunUba1** [comment]
> Please test this as well: multiple values overrides from different sources within apply step

done , working

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 1 change requests. 1. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/43375#-NNGuU51044jAR-Nm3kD:-NNHjlvx3ZnpahmXW3hE:bvtrlzg) ([raw file](https://github.com/harness/harness-core/blob/8f3e400ba4ef476b9bb1401948a86a4304e87465/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L351)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still confused what harness store has to with this?

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43375)* status: :shipit: complete! ✓

**Pull request merged**
