### PR TITLE
fix: [PL-27006]: Process both the commits if they have same time stamp

### PR DESCRIPTION
**Pull request by DeepakPatankar**
## Describe your changes
**Problem**
This problem is for a particular case where the user has made two commits at the exact same time( this would be very rare). Let's say the commits were c1 and c2, where c1 was done first and then c2 was done.

The flow would be:
1. We complete processing c1.
2. Then we start processing c2. Before processing, we check that the commit time of c2 should be greater than the previous commit.
3. Since the commit time of c2 is equal(and is not greater) to c1, we skip processing this commit.

This resulted into the loss of changes done in the c2 commit

**Solutions**
 Considering the c1 and c2 mentioned in the problem, We have two cases:

**Case 1**: We process c1 first and c2 next
This is the natural order of commits and this processing won't create any issues.

**Case 2**: We process c2 first and c1 next
If c2 is processed first, then it will have the changes of c1 and c2 both, hence both the changes would be applied. 
Now if we process c1, it will try to find a diff between c2 --> c1 and it will fail with the error that "c2 is a later commit than c1".
But the state of the harness and it would be the same.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or the local environment.
- [ ] If the hash check failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35976)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35976)

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35976)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35976)* status: :shipit: complete! ✓

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Pull request merged**
