### PR TITLE
fix: [DEL-3001]: Deprecate system executor threadpool and use common threadpool for task execution

### PR DESCRIPTION
**Pull request by gaurav-jain1**
common threadpool to execute both sync and async tasks.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)

### CODE REVIEW

**Review by puneetsar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1829 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtqmB0dEqtFwQp3_Ysb:-MtqmB0dEqtFwQp3_Ysc:b-mmvjak) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1829)):*
> ```Java
>     Future taskFuture = taskExecutor.submit(() -> dispatchDelegateTask(delegateTaskEvent));
>     log.info("Task submitted for execution");
>     if (taskFuture.isCancelled()) {
> ```

Who can cancel it.



_Code quote:_
```Java
taskFuture.isCancelled
```
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1850 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtqokRv5wDkqk83OSsc:-MtqokRv5wDkqk83OSsd:bd96xxw) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1850)):*
> ```Java
>     if (!acquireTasks.get()) {
>       log.info("[Old] Upgraded process is running. Won't acquire task while completing other tasks");
>       currentlyExecutingFutures.remove(delegateTaskId);
> ```

just keep in finally



_Code quote:_
```Java
currentlyExecutingFutures.remove
```
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java, line 126 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-Mtqqhld2N5nFIXrBztw:-Mtqqhld2N5nFIXrBztx:b-5ifhb2) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L126)):*
> ```Java
>           }
>         }
>         log.info("Response received for task: {}", taskId);
> ```

lets add delegateId



_Code quote:_
```Java
taskId)
```

**Comment by jennyjames21** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java, line 799 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtxSQLsBcSPqncrwAsO:-MtxSQLsBcSPqncrwAsP:b-iwnbt3) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L799)):*
> ```Java
>   @Named("taskExecutor")
>   public ExecutorService taskExecutor() {
>     ExecutorService taskExecutor = ThreadPool.create(10, 400, 1, TimeUnit.SECONDS,
> ```

Since we dont know customer settings,  should max thread pool size be something like
 Runtime.getRuntime().availableProcessors() * 2.  Or 100
I think default max thread pool size is 100, why 400 here?

**Comment by jennyjames21** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1829 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtxXAEM-1F7-hzg7xhA:-MtxXAEN3qGzmed2eE8z:b-3tj5l5) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1829)):*
> ```Java
>     Future taskFuture = taskExecutor.submit(() -> dispatchDelegateTask(delegateTaskEvent));
>     log.info("Task submitted for execution");
>     if (taskFuture.isCancelled()) {
> ```

is future.isCancelled() a blocking operation or expected here to be in blocking state?

If it's not designed to be in blocking, CompletableFuture instead of future will save some time.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)* status: Some of the checks are too old. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java, line 799 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtxSQLsBcSPqncrwAsO:-MuFapwc2ZNU66gaRNNM:bnafrx7) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L799)):*
>  default max thread pool size is 100, why 400 here?
This has been 400 earlier as well. @harshjain12 changed this long back with his testing  on async tasks. 
But you point make sense, instead of using static number here, we can actually throttle based on resource usage. Let's say reject the tasks if we hit 90% of CPU or memory.
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1829 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtqmB0dEqtFwQp3_Ysb:-MuFfOfg9_I4obOlWBwD:b4vnphc) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1829)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

Who can cancel it.
</blockquote></details>

Task cancellation is a separate even from manager.
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1829 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtxXAEM-1F7-hzg7xhA:-MuFfimA52SFqjFFmbTe:b7hluxm) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1829)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

is future.isCancelled() a blocking operation or expected here to be in blocking state?

If it's not designed to be in blocking, CompletableFuture instead of future will save some time.
</blockquote></details>

I this check is not helping us in anyway. will remove this.
___
*[420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java, line 126 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-Mtqqhld2N5nFIXrBztw:-MuFjiQO7mgoC6aFj_5g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L126)):*
<details><summary><i>Previously, puneetsar (Puneet Saraswat) wrote…</i></summary><blockquote>

lets add delegateId
</blockquote></details>

Done.

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)* status: 1 change requests. 4. unresolved discussions.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)* status: 1 change requests. 4. unresolved discussions.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)* status: 1 change requests. 4. unresolved discussions.

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30058)* status: 1 change requests. 3. unresolved discussions. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 1829 at r1](https://reviewable.io/reviews/harness/harness-core/30058#-MtxXAEM-1F7-hzg7xhA:-MuP_NmyAGCCfF26n9HP:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/98b41c54af2fbabf15dad590b75df801a1405598/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1829)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

I this check is not helping us in anyway. will remove this.
</blockquote></details>

Done

**Comment by gaurav-jain1** [comment]
Changes has been merged as part of https://github.com/harness/harness-core/pull/30283

**Pull request closed without merging**
