### PR TITLE
[feat]: [PIE-8925]: Add rollback steps as nodes to preserve in rollback mode

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46264)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46264)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46264)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
