### PR TITLE
feat: [CODE-1201]: CODEModule License Integration

### PR DESCRIPTION
**Pull request by akhilpandey1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)

### CODE REVIEW

**Comment by akhilpandey1** [comment]
trigger uts

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Comment by akhilpandey1** [comment]
trigger uts

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/CODEModuleLicense.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV5xfEBZCNkhH7Rb2V:-NlV5xfF7SB1B-tw68Gi:bamivta) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/CODEModuleLicense.java#L30)):*
> ```Java
> @Persistent
> @TypeAlias("io.harness.license.entities.module.CodeModuleLicense")
> public class CODEModuleLicense extends ModuleLicense {
> ```

why the class name i.e. CODE is in caps? should be in camel case i.e. 



_Code snippet:_
```Java
CodeModuleLicense
```
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV4K3a9Ihwl7SVVzU4:-NlV4K3a9Ihwl7SVVzU5:buyb7nm) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java#L352)):*
> ```Java
>         break;
>       case CODE:
>         CODEModuleLicense codeModuleUpdateLicense = (CODEModuleLicense) update;
> ```

better name would be:



_Code snippet:_
```Java
updatedCodeModuleLicense
```
___
*[`960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules/CODEModuleLicenseDTO.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV6K1T57BqM72KbrS3:-NlV6K1T57BqM72KbrS4:bamivta) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules/CODEModuleLicenseDTO.java#L34)):*
> ```Java
> @JsonInclude(NON_NULL)
> @Schema(name = "CODEModuleLicense", description = "Contains Details of the CODE License in Harness")
> public class CODEModuleLicenseDTO extends ModuleLicenseDTO {
> ```

why the class name i.e. CODE is in caps? should be in camel case i.e. 



_Code snippet:_
```Java
CodeModuleLicenseDTO
```

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CODELocalClient.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV7-Yo0CL0Bx8EdXwc:-NlV7-Yo0CL0Bx8EdXwd:bi188tt) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CODELocalClient.java#L37)):*
> ```Java
>         CODEModuleLicenseDTO.builder().startTime(currentTime).expiryTime(expiryTime).status(LicenseStatus.ACTIVE);
> 
>     if (edition == Edition.ENTERPRISE) {
> ```

not planning for a FREE Fitness plan?

**Comment by akhilpandey1** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CODELocalClient.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV7-Yo0CL0Bx8EdXwc:-Nlx8JPUBa1Cm12Xj3yD:b-3bz6hq) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CODELocalClient.java#L37)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

not planning for a FREE Fitness plan?
</blockquote></details>

It's still under discussion.

**Comment by akhilpandey1** [comment]
*[`960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules/CODEModuleLicenseDTO.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV6K1T57BqM72KbrS3:-Nlx8PsK8prgN6J-Rhh2:bgl15qw) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules/CODEModuleLicenseDTO.java#L34)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why the class name i.e. CODE is in caps? should be in camel case i.e.
</blockquote></details>

done, renamed at all places from CODE to Code

**Comment by akhilpandey1** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/CODEModuleLicense.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV5xfEBZCNkhH7Rb2V:-Nlx8V2u1HAs5lBMWP0K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/930-ng-license-manager/src/main/java/io/harness/licensing/entities/modules/CODEModuleLicense.java#L30)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

why the class name i.e. CODE is in caps? should be in camel case i.e.
</blockquote></details>

Done.

**Comment by akhilpandey1** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java` line 352 at r2](https://reviewable.io/reviews/harness/harness-core/56669#-NlV4K3a9Ihwl7SVVzU4:-Nlx8cOcEO8g0rXYE0E-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0db8c778983c5caa9b562ab8c61919d1e0a57777/930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java#L352)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

better name would be:
</blockquote></details>

Done.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r3, 3 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)* status: 10 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java` line 357 at r4](https://reviewable.io/reviews/harness/harness-core/56669#-Nm2jcPV7elYkba0q5Q2:-Nm2jcPV7elYkba0q5Q3:bxdoh7x) ([raw file](https://github.com/harness/harness-core/blob/c575775da6e81f80acfbe1022c8b5c13757ec76e/930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java#L357)):*
> ```Java
>                 && !updatedCodeModuleLicense.getNumberOfDevelopers().equals(
>                     currentCodeModuleLicense.getNumberOfDevelopers()))
>             || (updatedCodeModuleLicense.getNumberOfRepositories() != null
> ```

This or statement should be separate to different if statement, since the put request may not includes all the fields to update. 
___
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/56669#-Nm2qwKDB6FeVZcstDLl:-Nm2qwKDB6FeVZcstDLm:b-83ym9g) ([raw file](https://github.com/harness/harness-core/blob/c575775da6e81f80acfbe1022c8b5c13757ec76e/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java#L47)):*
> ```Java
>         return builder.numberOfDevelopers(Integer.valueOf(UNLIMITED))
>             .numberOfRepositories(5)
>             .licenseType(LicenseType.TRIAL)
> ```

The license type shouldn't be trial for free plan. Take a look at CELocalClient

**Comment by akhilpandey1** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java` line 357 at r4](https://reviewable.io/reviews/harness/harness-core/56669#-Nm2jcPV7elYkba0q5Q2:-Nm2x5eR-Oqfjsl-hsEx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c575775da6e81f80acfbe1022c8b5c13757ec76e/930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseHelper.java#L357)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

This or statement should be separate to different if statement, since the put request may not includes all the fields to update.
</blockquote></details>

Done.

**Comment by akhilpandey1** [comment]
*[`930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java` line 47 at r4](https://reviewable.io/reviews/harness/harness-core/56669#-Nm2qwKDB6FeVZcstDLl:-Nm2xA7d20zfYI5sxwfU:b-so2sxi) ([raw file](https://github.com/harness/harness-core/blob/c575775da6e81f80acfbe1022c8b5c13757ec76e/930-ng-license-manager/src/main/java/io/harness/licensing/interfaces/clients/local/CodeLocalClient.java#L47)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

The license type shouldn't be trial for free plan. Take a look at CELocalClient
</blockquote></details>

removed licenseType from FREE license as per CELocalClient

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Review by Xin-Harness — COMMENTED** [review]
> Reviewed 1 of 9 files at r3, 6 of 12 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)* status: 1 change requests. 4. unresolved discussions.

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Comment by akhilpandey1** [comment]
trigger smartchecks

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56669)* status: 1 change requests. 4. unresolved discussions.

**Comment by akhilpandey1** [comment]
trigger uts

**Pull request merged**
