### PR TITLE
fix: [DEL-3719]: Improvements in watcher while watching delegate process

### PR DESCRIPTION
**Pull request by gaurav-jain1**
This change-set contains following improvements:
1) Send primaryVersion while starting Delegate process (in case of on-prem)
2) Verbose logging if we get exception in watchDelegate()
3) Look for existence of delegate process before attempting to kill it.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32265)

### CODE REVIEW

**Review by puneetsar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32265)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 973 at r1](https://reviewable.io/reviews/harness/harness-core/32265#-N-cviwjCBHnpVd_4qqY:-N-cviwjCBHnpVd_4qqZ:b-gnvco5) ([raw file](https://github.com/harness/harness-core/blob/0f3a2c5f1a16745154cc333ffa3676bb67da6301/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L973)):*
> ```Java
> 
>   private boolean isPrimaryDelegate(String delegateVersion, List<String> expectedVersions) {
>     return delegateVersion.equals(getPrimaryDelegate(expectedVersions));
> ```

We should do null check on delegateVersion as well. I see the getPrimaryDelegate can return null, and we are using that for getting the version.



_Code quote:_
```Java
delegateVersion
```

**Review by puneetsar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32265)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 975 at r3](https://reviewable.io/reviews/harness/harness-core/32265#-N-iFDSD7FFqZrY_fx15:-N-iFDSD7FFqZrY_fx16:b-20to9c) ([raw file](https://github.com/harness/harness-core/blob/5d306704020b8b1fa4cac5b758eb83348905bd1c/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L975)):*
> ```Java
>   private boolean isPrimaryDelegate(String delegateVersion, List<String> expectedVersions) {
>     if (isEmpty(delegateVersion)) {
>       if (expectedVersions.size() == 1) {
> ```

this seems wrong, if its empty then we will not get to if (expectedVersions.size() == 1)

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32265)* status: :shipit: complete! ✓

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32265)* status: 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32265#-:-N04B67A-Yfbk2Ng2jYg:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
