### PR TITLE
feat: [CDS-38608]: Fix environment and servicesped Node id for enviro…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…nment plan creator v2

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34093)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34093)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40wMylCsGtj1WjJx68:-N40wMymCtwzdk7HTurA:bho2tha) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L58)):*
> ```Java
>   Map<String, Object> environmentInputs;
>   Map<String, Object> serviceOverrideInputs;
>   @NotNull @DefaultValue("false") boolean deployToAll;
> ```

nit: it cannot be null since its a primitive bool

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34093)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40xfea-jNqTr_yfEsv:-N40xfea-jNqTr_yfEsw:b-ud9m3b) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L124)):*
> ```Java
>     }
> 
>     if (gitOpsEnabled != Boolean.TRUE && env.isDeployToAll()) {
> ```

this Boolean true is not required.



_Code quote:_
```Java
gitOpsEnabled != Boolean.TRUE
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40wMylCsGtj1WjJx68:-N40xYpYEx6YRFOkM_oP:b-ahsoa1) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L58)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: it cannot be null since its a primitive bool
</blockquote></details>

this was added for schema making it compulsory field.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40xc1WA40lqm_H2-8x:-N40xc1WA40lqm_H2-8y:b-v5i28g) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L58)):*
> ```Java
>   Map<String, Object> environmentInputs;
>   Map<String, Object> serviceOverrideInputs;
>   @NotNull @DefaultValue("false") boolean deployToAll;
> ```

this default value can be removed.



_Code quote:_
```Java
DefaultValue("false")
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34093)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40xfea-jNqTr_yfEsv:-N411WtGCI6LjR6wMtpm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L124)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this Boolean true is not required.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40wMylCsGtj1WjJx68:-N411YUX4j2aZMUnIly-:buhguqi) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L58)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this was added for schema making it compulsory field.
</blockquote></details>

that is for schema

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34093)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/34093#-N40xc1WA40lqm_H2-8x:-N411wPj933YE7lY0KDS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed317fa14678f361cf6ca9e010c68811f813f3e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java#L58)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this default value can be removed.
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34093)* status: :shipit: complete! ✓

**Pull request merged**
