### PR TITLE
feat: [PL-29234]: longer data retention without ff

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
We had set of three feature flag to control state management of longer retention of data for instances and deployment. 
To achieve longer retention we started storing rolled up data in multiple tables. 
Earlier pattern was - 
REALTIME flag - it was used to migrate data which is coming in now in both new and rolled up tables. 
CRON flag - to keep migrating old data into rolled up table in throttled manner - took about 3 days.
UI enable flag - to enable UI to serve from new flags.

This approach had multiple downsides. 
1. Anti pattern: The bg cron to disable bg thread for migration was based on an anti pattern i.e. at the end of all data migration feature flag was switched off from application and used to manage state. 
2. UI wait: CSE had to wait for other flags to complete to enable UI flag to serve from newer tables. 

To help resolve the issue following has been done:
1. State management happens as part of mongo collection now to assure data has been migrated the cron ff disable won't be required.
2. UI will start serving from newer tables on completion and no ff toggle required on completion.

To get old customer back to same state we have written a migration to get state as true for all customers who have ff enabled to serve from new tables. 
Also, in flight customer wont get an issue as at the end of migration it will disable the mongo state and there wont be an issue.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41670)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger feature-build

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 8 of 11 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41670)* status: Some of the checks are too old. 16 file(s) to review. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 3 of 8 files at r2, 3 of 3 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41670)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 3 of 8 files at r2, 3 of 3 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41670)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41670)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 3 of 8 files at r2, 3 of 3 files at r3, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41670)* status: :shipit: complete! ✓

**Pull request merged**
