### PR TITLE
[feat]: [CDS-82571]: Support empty folder paths for gitx webhooks

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Customer Ask: When there are no folder paths mentioned at the time of creation of gitx webhooks, all the events received for the webhook for a given repo should be processed, instead of adding multiple folder paths.

1. CRUD operations to support empty folder path for gitx webhook.
2. GitXWebhook processing, when we come across a webhook where the folder paths are empty, in such cases, we parse all the modified file paths received in the webhook event from git. 
3. Have tested out these changes locally, its working as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54659)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/54659#-NheXM1Z1GbcyW0j7Ype:-NheXM1Z1GbcyW0j7Ypf:b-oej8f3) ([raw file](https://github.com/harness/harness-core/blob/cea404c57fc7fe40f76195182ae8f17729dd20a7/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java#L199)):*
> ```Java
>   }
> 
>   private List<String> parseEmptyFolderPaths(List<String> folderPaths) {
> ```

method name is incorrect. It should be simply getFolderPaths() or something on these lines. Essentially you're just getting the folder paths from webhook response.

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/54659#-NheXM1Z1GbcyW0j7Ype:-Nhejlc92YbO_kmGoBlt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cea404c57fc7fe40f76195182ae8f17729dd20a7/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/mapper/GitXWebhookMapper.java#L199)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

method name is incorrect. It should be simply getFolderPaths() or something on these lines. Essentially you're just getting the folder paths from webhook response.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54659)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
