### PR TITLE
[feat]: [PIE-6672]: Removed metadata requirement in the validation flows for InputSets

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Changes: For new apis(which support only new GitX and New Yaml Structure), i have removed validations for metadata in inputSetYaml.

Testing: Below Automation tests(InputSetCRUD) pass against my branch. Also basic requests and response has been tested by @mankrit-singh 

Some broad points about changes done:
Validations for metadata in inputSetYaml(which include identifier, name, description, projectIdentifier, orgIdentifier, tags) removed from CREATE flow, GET flow, UPDATE flow
Although you may encounter some validations for metadata in Yaml for some oldGitSync flows, but new apis do not support it and thus can be ignored

Screenshot 2022-12-14 at 11 07 48 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)

### CODE REVIEW

**Comment by senjucanon2** [comment]
Ignore Last Commit Message

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/41070#-NIkKmTY8F6alPNc-Rq-:-NIkKmTY8F6alPNc-Rq0:baqlkge) ([raw file](https://github.com/harness/harness-core/blob/9752e0220b862791bc045e745950cff979495d0c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java#L42)):*
> ```Java
>   public final String OUTDATED_INPUT_SET_MESSAGE = "Reference is an outdated input set";
> 
>   public InputSetErrorWrapperDTOPMS getErrorMap(String pipelineYaml, String inputSetIdentifier, String inputSetYaml) {
> ```

please add new arguments at end of the list, not in b/w

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/41070#-NIkKmTY8F6alPNc-Rq-:-NIpRuiy4sy4Sfqz0AeJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9752e0220b862791bc045e745950cff979495d0c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/InputSetErrorsHelper.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please add new arguments at end of the list, not in b/w
</blockquote></details>

Done.

**Review by namanvermah — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: 16 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070#-:-NJKH1xn99fwI_g-dsKL:bnfp4nl)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: :shipit: complete! ✓

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: Some of the checks are too old.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: 2 file(s) to review.

**Review by sourabh-awashti — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 3 of 9 files at r2, 3 of 3 files at r3, 2 of 5 files at r4, 4 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41070)* status: :shipit: complete! ✓

**Pull request merged**
