### PR TITLE
fix: [CDS-47000]: have added DuplicateKeyException to retry policy

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
This pr is add retry policy for mongo calls made by environment crud operations.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40572)

### CODE REVIEW

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40572)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/40572#-NHhXZHB6Jx0qcJ7_7Ak:-NHhXZHB6Jx0qcJ7_7Al:b6zzx0b) ([raw file](https://github.com/harness/harness-core/blob/d9f0ce46e10e685b9e475fa3e9bc3ac43365fb38/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L117)):*
> ```Java
> 
>   private RetryPolicy<Object> getRetryPolicy(String failedAttemptMessage, String failureMessage) {
>     return PersistenceUtils.getRetryPolicyWithDuplicateKeyException(failedAttemptMessage, failureMessage);
> ```

Lets add this retry policy only at upsert calls.



_Code quote:_
```Java
urn PersistenceUtils.getRetryPolicyWithDuplicateKe
```

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40572)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/40572#-NHhXZHB6Jx0qcJ7_7Ak:-NHiDebT7V5-l2ZVfHty:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9f0ce46e10e685b9e475fa3e9bc3ac43365fb38/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L117)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Lets add this retry policy only at upsert calls.
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40572)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40572)* status: :shipit: complete! ✓

**Comment by vivekkarnatiharness** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40572)* status: :shipit: complete! ✓

**Pull request merged**
