### PR TITLE
[feat]: [CDS-33772]: Add Poweshell Command Parameters

### PR DESCRIPTION
**Pull request by jelenaHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33082)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33082)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/schema/type/secrets/QLWinRmCommandParameter.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/33082#-N1tEZtm6RQGVN0G_zga:-N1tEZtm6RQGVN0G_zgb:b-3xkd83) ([raw file](https://github.com/harness/harness-core/blob/1e0ba6a4f7834f6e05a5f9abe2ac218efdb38424/400-rest/src/main/java/software/wings/graphql/schema/type/secrets/QLWinRmCommandParameter.java#L22)):*
> ```Java
> 
> @Value
> @Builder
> ```

You shouldn't use builder here unless some of the fields are not mandatory (which it doesn't seem to be the case). Just use constructor to create the object instead. 
___
*[`930-delegate-tasks/src/main/java/software/wings/beans/WinRmCommandParameter.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/33082#-N1tFM9p1_0049iN5nqI:-N1tFM9qDeB0cfl5ZD39:bw326wr) ([raw file](https://github.com/harness/harness-core/blob/1e0ba6a4f7834f6e05a5f9abe2ac218efdb38424/930-delegate-tasks/src/main/java/software/wings/beans/WinRmCommandParameter.java#L10)):*
> ```Java
> @Data
> @Builder
> @NoArgsConstructor
> ```

You should remove those 3 as not needed. Only use `@Value` OR `@Data` with all fields explicitly final. That makes the object (reference) immutable which makes it much more manageable and inherently thread safe. 



_Code quote:_
```Java
@Builder
@NoArgsConstructor
@AllArgsConstructor
```

**Comment by jelenaHarness** [comment]
> > Reviewed 13 of 17 files at r1, 6 of 6 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33082)_ status: 1 change requests. 0 of 1 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/graphql/schema/type/secrets/QLWinRmCommandParameter.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/33082#-N1tEZtm6RQGVN0G_zga:-N1tEZtm6RQGVN0G_zgb:b-3xkd83) ([raw file](https://github.com/harness/harness-core/blob/1e0ba6a4f7834f6e05a5f9abe2ac218efdb38424/400-rest/src/main/java/software/wings/graphql/schema/type/secrets/QLWinRmCommandParameter.java#L22)):_
> 
> > ```java
> > @Value
> > @Builder
> > ```
> 
> You shouldn't use builder here unless some of the fields are not mandatory (which it doesn't seem to be the case). Just use constructor to create the object instead.
> 
> _[`930-delegate-tasks/src/main/java/software/wings/beans/WinRmCommandParameter.java` line 10 at r2](https://reviewable.io/reviews/harness/harness-core/33082#-N1tFM9p1_0049iN5nqI:-N1tFM9qDeB0cfl5ZD39:bw326wr) ([raw file](https://github.com/harness/harness-core/blob/1e0ba6a4f7834f6e05a5f9abe2ac218efdb38424/930-delegate-tasks/src/main/java/software/wings/beans/WinRmCommandParameter.java#L10)):_
> 
> > ```java
> > @Data
> > @Builder
> > @NoArgsConstructor
> > ```
> 
> You should remove those 3 as not needed. Only use `@Value` OR `@Data` with all fields explicitly final. That makes the object (reference) immutable which makes it much more manageable and inherently thread safe.
> 
> _Code quote:_
> 
> ```java
> @Builder
> @NoArgsConstructor
> @AllArgsConstructor
> ```

done

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 83 at r4](https://reviewable.io/reviews/harness/harness-core/33082#-N2GHETb332CKpeLMVgU:-N2GHETb332CKpeLMVgV:b-4u0nvr) ([raw file](https://github.com/harness/harness-core/blob/cc3e06332efdc1eb0c966b40ea47bb14f965c067/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L83)):*
> ```Java
>   private static String buildCommandParameters(List<WinRmCommandParameter> commandParameters) {
>     StringBuilder parametersStringBuilder = new StringBuilder();
>     if (commandParameters == null || isEmpty(commandParameters)) {
> ```

nit: can use `io.harness.data.structure.EmptyPredicate#isNotEmpty`

**Review by arvind-choudhary-h — APPROVED** [review]
:lgtm:

> Reviewed 10 of 17 files at r1, 2 of 6 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33082#-:-N2GHcLV69bgdy1nDCo_:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by mdmilic — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33082)* status: 1. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33082)* status: :shipit: complete! ✓

**Pull request merged**
