### PR TITLE
[feat]: [CDS-54264]: validation for query interval

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
Added a validation that startTime and endTime interval should be less than equal to 6 months for API used to get pipeline execution count ('/getPipelineExecutionCount').

Added index for the same query use case.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45443)

### CODE REVIEW

**Comment by USB-05** [comment]
trigger pmd

**Comment by USB-05** [comment]
trigger pmd

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45443)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45443)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBugoc8MNrMitqqjZU:-NRBugoc8MNrMitqqjZV:b-8n2hqz) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L600)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.ARTIFACT_VERSION) String artifactVersion,
>       @QueryParam(NGCommonEntityConstants.ARTIFACT) String artifact,
>       @QueryParam(NGCommonEntityConstants.STATUS) String status) throws InvalidRequestException {
> ```

You sure this is needed? I haven't seen Resource method throwing Exceptions.
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBuYUT09LY2vP3PEYp:-NRBuYUT09LY2vP3PEYq:bccozzv) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java#L168)):*
> ```Java
>   PipelineExecutionCountInfo getPipelineExecutionCountInfo(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String serviceId, Long startInterval, Long endInterval, String artifactPath,
>       String artifactVersion, String artifact, String status) throws InvalidRequestException;
> ```

InvalidRequest is RuntimeException (unchecked exception). Do we need to add it to throws?
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1368 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBuy_M7E64IIDDi1mg:-NRBuy_M7E64IIDDi1mh:bulivcj) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1368)):*
> ```Java
>     startInterval = DashboardServiceHelper.checkForDefaultStartInterval(startInterval, endInterval);
>     if (!DashboardServiceHelper.validateDuration(startInterval, endInterval)) {
>       throw new InvalidRequestException("startTime and endTime interval should be less than 6 months");
> ```

nit, S capital
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java` line 858 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBv6ax6X284LMX-o6C:-NRBv6ax6X284LMX-o6D:b-9ee1ok) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java#L858)):*
> ```Java
>   public boolean validateDuration(Long startInterval, Long endInterval) {
>     long duration = endInterval - startInterval;
>     long durationSixMonths = 15552000000l;
> ```

nit, Java has library functions like TimeUnit.Months(6).tomilliis. or something similar. You should use those ideally.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBvLn47ce_Ixj7reju:-NRBvLn582Rtm7-ZPRp0:bvhsjih) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java#L51)):*
> ```Java
>         .add(Pair.of(15, UpdatePipelineExecutionSummaryCdTimescaleTable.class))
>         .add(Pair.of(16, AddExecutionFailureDetailsToServiceInfraInfoTable.class))
>         .add(Pair.of(17, AddIndexToServiceInfraInfoTable.class))
> ```

ServiceInfraInfo table is owned by CD Team. Why are we writing migrations in PMS?

**Comment by Abhishek-CDC** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBvLn47ce_Ixj7reju:-NRBwGUP-dyWgKh1R1EH:bh9mdp5) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java#L51)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

ServiceInfraInfo table is owned by CD Team. Why are we writing migrations in PMS?
</blockquote></details>

service_infra_info table was created as part of 'create_change_data_capture_tables_timescale.sql' file which is also in PMS

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java` line 858 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBv6ax6X284LMX-o6C:-NRDSPH3BaszpY3d_tDf:b66jw3y) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java#L858)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, Java has library functions like TimeUnit.Months(6).tomilliis. or something similar. You should use those ideally.
</blockquote></details>

It was based on calendar time, to fix the value kept this constant.

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java` line 600 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBugoc8MNrMitqqjZU:-NRDSZ-a88IRp9ETOTlZ:ba3dfob) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java#L600)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

You sure this is needed? I haven't seen Resource method throwing Exceptions.
</blockquote></details>

Removed

**Comment by Abhishek-CDC** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBvLn47ce_Ixj7reju:-NRDSdxqBZWhny-C3ud_:bes2lqk) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java#L51)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

service_infra_info table was created as part of 'create_change_data_capture_tables_timescale.sql' file which is also in PMS
</blockquote></details>

moved to ng-manager

**Comment by Abhishek-CDC** [comment]
trigger ut7

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45443)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java` line 858 at r2](https://reviewable.io/reviews/harness/harness-core/45443#-NRBv6ax6X284LMX-o6C:-NREkCpv6d34mij66oMA:bog2rsi) ([raw file](https://github.com/harness/harness-core/blob/dadd0854d15a1ab315defc8c716bfba19c4e2db6/120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java#L858)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

It was based on calendar time, to fix the value kept this constant. 
</blockquote></details>

umm, it's just duration, should not be timezone dependent

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45443)* status: :shipit: complete! ✓

**Pull request merged**
