### PR TITLE
[feat]:[pl-27803]: import template from git BE api contract

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
import template from git BE api contract

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37512)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateImportRequestDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/37512#-NBvEgyq4VNyLxl3INeP:-NBvEgyq4VNyLxl3INeQ:b-d52yps) ([raw file](https://github.com/harness/harness-core/blob/1c27c3aff668989d86c19c4729f7ca32cc8fab9c/840-template-service/src/main/java/io/harness/template/beans/TemplateImportRequestDTO.java#L23)):*
> ```Java
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @ApiModel("TemplateImportRequest")
> @Schema(name = "TemplateImportRequest",
> ```

The DTO must be hidden from OpenAPI3.0

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateSaveResponse.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/37512#-NBvEmSN0z5s6KWERnv7:-NBvEmSN0z5s6KWERnv8:b-10clm9) ([raw file](https://github.com/harness/harness-core/blob/1c27c3aff668989d86c19c4729f7ca32cc8fab9c/840-template-service/src/main/java/io/harness/template/beans/TemplateSaveResponse.java#L13)):*
> ```Java
> @Value
> @Builder
> @Schema(
> ```

same hidden.

**Comment by adivishy1** [comment]
> _[`840-template-service/src/main/java/io/harness/template/beans/TemplateImportRequestDTO.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/37512#-NBvEgyq4VNyLxl3INeP:-NBvEgyq4VNyLxl3INeQ:b-d52yps) ([raw file](https://github.com/harness/harness-core/blob/1c27c3aff668989d86c19c4729f7ca32cc8fab9c/840-template-service/src/main/java/io/harness/template/beans/TemplateImportRequestDTO.java#L23)):_
> 
> > ```java
> > @JsonInclude(JsonInclude.Include.NON_NULL)
> > @ApiModel("TemplateImportRequest")
> > @Schema(name = "TemplateImportRequest",
> > ```
> 
> The DTO must be hidden from OpenAPI3.0

Done

**Comment by adivishy1** [comment]
> _[`840-template-service/src/main/java/io/harness/template/beans/TemplateSaveResponse.java` line 13 at r1](https://reviewable.io/reviews/harness/harness-core/37512#-NBvEmSN0z5s6KWERnv7:-NBvEmSN0z5s6KWERnv8:b-10clm9) ([raw file](https://github.com/harness/harness-core/blob/1c27c3aff668989d86c19c4729f7ca32cc8fab9c/840-template-service/src/main/java/io/harness/template/beans/TemplateSaveResponse.java#L13)):_
> 
> > ```java
> > @Value
> > @Builder
> > @Schema(
> > ```
> 
> same hidden.

Done

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37512)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateSaveResponse.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/37512#-NCP8faEARBtZSGZkTo0:-NCP8faFDTBsEEVPtic1:b-rtoaoh) ([raw file](https://github.com/harness/harness-core/blob/0b834eae057dd344556466da076b15f0f3631a0b/840-template-service/src/main/java/io/harness/template/beans/TemplateSaveResponse.java#L17)):*
> ```Java
> @Schema(
>     name = "TemplateSaveResponse", description = "Contains the Template details for the given Template ID and version")
> public class TemplateSaveResponse {
> ```

Can we change the name to TemplateImportSaveResponse

**Comment by adivishy1** [comment]
> TemplateImportSaveResponse

Done

**Review by inderschera — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37512)* status: 2. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/beans/TemplateImportRequestDTO.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/37512#-NCPDYx22dPjTnCzuDGX:-NCPDYx22dPjTnCzuDGY:bgmohdt) ([raw file](https://github.com/harness/harness-core/blob/499f48a03ed6ec750b72e58bd132f799677a7526/840-template-service/src/main/java/io/harness/template/beans/TemplateImportRequestDTO.java#L28)):*
> ```Java
>     description = "Contains basic information required to be linked with imported Template YAML")
> public class TemplateImportRequestDTO {
>   @Schema(description = "Expected Name of the Template to be imported") String templateName;
> ```

nit: should it be templateIdentifier?
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 873 at r3](https://reviewable.io/reviews/harness/harness-core/37512#-NCPDTF53eS7esZ8tUg1:-NCPDTF53eS7esZ8tUg2:b-ri6el4) ([raw file](https://github.com/harness/harness-core/blob/499f48a03ed6ec750b72e58bd132f799677a7526/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L873)):*
> ```Java
>       @ResourceIdentifier String templateIdentifier, GitImportInfoDTO gitImportInfoDTO,
>       TemplateImportRequestDTO templateImportRequestDTO) {
>     return ResponseDTO.newResponse(TemplateImportSaveResponse.builder().build());
> ```

nit: should we create a new resource file for import flows?

**Comment by adivishy1** [comment]
> templateIdentifier

Done

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37512)* status: :shipit: complete! ✓

**Pull request merged**
