### PR TITLE
feat: [PIE-5460]: Create PipelineStageNode for pipeline stage

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes
Have created stage node and config for pipeline stage which will be a stage for pipeline chaining. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37846)

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageConfig.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/37846#-NCdxh_15C0GiIal7NwY:-NCdxh_15C0GiIal7NwZ:b-c1xnyi) ([raw file](https://github.com/harness/harness-core/blob/2d35b3d82e243df41e15d0e435e2fe68c5872efc/pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageConfig.java#L41)):*
> ```Java
>   String uuid;
> 
>   @NotNull String pipeline;
> ```

nit: shouldn't we use identifier sufix here? like pipelineIdentifier.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageNode.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/37846#-NCdxzNAEV3W50BGKdlS:-NCdxzNAEV3W50BGKdlT:b-8s4wh1) ([raw file](https://github.com/harness/harness-core/blob/2d35b3d82e243df41e15d0e435e2fe68c5872efc/pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageNode.java#L51)):*
> ```Java
>   @Override
>   public StageInfoConfig getStageInfoConfig() {
>     return null;
> ```

We should return the `pipelineStageConfig` field here.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageConfig.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/37846#-NCdxh_15C0GiIal7NwY:-NCsReOkCL5M6WXW-iDI:bh2jh9y) ([raw file](https://github.com/harness/harness-core/blob/2d35b3d82e243df41e15d0e435e2fe68c5872efc/pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageConfig.java#L41)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

nit: shouldn't we use identifier sufix here? like pipelineIdentifier.
</blockquote></details>

As decided, we will be using pipeline, org, and project under spec. https://harness.atlassian.net/wiki/spaces/PIPE/pages/21169931135/Tech+Spec+Pipeline+Chaining+BE#Pipeline-Stage

cc @hextechpal

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageNode.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/37846#-NCdxzNAEV3W50BGKdlS:-NCs_tVU8bG6NthvdUl_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d35b3d82e243df41e15d0e435e2fe68c5872efc/pipeline-service/service/src/main/java/io/harness/pms/pipeline/stage/PipelineStageNode.java#L51)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

We should return the `pipelineStageConfig` field here.
</blockquote></details>

Done.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger ti0

**Comment by prashantsharma04** [comment]
trigger ti2

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37846)* status: :shipit: complete! ✓

**Pull request merged**
