### PR TITLE
[feat]: [CVS-9171]: refactored service-dependeny-graph API using monitoredServideIdentifier

### PR DESCRIPTION
**Pull request by kapil-harness**
…iceIdentifier

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30943)

### CODE REVIEW

**Comment by kapil-harness** [comment]
API: 
https://localhost:8181/cv/api/service-dependency-graph?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&orgIdentifier=default&projectIdentifier=Learning_Harness&serviceIdentifier=service3&environmentIdentifier=env1&servicesAtRiskFilter=false
Response: 
{
    "metaData": {},
    "resource": {
        "nodes": [
            {
                "identifierRef": "service1_env1",
                "serviceRef": "service1",
                "serviceName": "service1",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service3_env1",
                "serviceRef": "service3",
                "serviceName": "service3",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service2_env1",
                "serviceRef": "service2",
                "serviceName": "service2",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            }
        ],
        "edges": [
            {
                "from": "service1_env1",
                "to": "service3_env1"
            },
            {
                "from": "service2_env1",
                "to": "service3_env1"
            }
        ]
    },
    "responseMessages": []
}

************************************

API:
https://localhost:8181/cv/api/service-dependency-graph?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&orgIdentifier=default&projectIdentifier=Learning_Harness&servicesAtRiskFilter=false
Response:
{
    "metaData": {},
    "resource": {
        "nodes": [
            {
                "identifierRef": "service1_env1",
                "serviceRef": "service1",
                "serviceName": "service1",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service3_env1",
                "serviceRef": "service3",
                "serviceName": "service3",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service2_env1",
                "serviceRef": "service2",
                "serviceName": "service2",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            }
        ],
        "edges": [
            {
                "from": "service1_env1",
                "to": "service3_env1"
            },
            {
                "from": "service2_env1",
                "to": "service3_env1"
            },
            {
                "from": "service1_env1",
                "to": "service2_env1"
            }
        ]
    },
    "responseMessages": []
}

***********************************

API:
https://localhost:8181/cv/api/service-dependency-graph?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&orgIdentifier=default&projectIdentifier=Learning_Harness&servicesAtRiskFilter=false&monitoredServiceIdentifier=service3_env1
Response:
{
    "metaData": {},
    "resource": {
        "nodes": [
            {
                "identifierRef": "service1_env1",
                "serviceRef": "service1",
                "serviceName": "service1",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service3_env1",
                "serviceRef": "service3",
                "serviceName": "service3",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service2_env1",
                "serviceRef": "service2",
                "serviceName": "service2",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            }
        ],
        "edges": [
            {
                "from": "service1_env1",
                "to": "service3_env1"
            },
            {
                "from": "service2_env1",
                "to": "service3_env1"
            }
        ]
    },
    "responseMessages": []
}

*************************************

API:
https://localhost:8181/cv/api/service-dependency-graph?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&orgIdentifier=default&projectIdentifier=Learning_Harness&serviceIdentifier=service3&environmentIdentifier=env1&servicesAtRiskFilter=false&monitoredServiceIdentifier=service3_env1
Response:
{
    "metaData": {},
    "resource": {
        "nodes": [
            {
                "identifierRef": "service1_env1",
                "serviceRef": "service1",
                "serviceName": "service1",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service3_env1",
                "serviceRef": "service3",
                "serviceName": "service3",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            },
            {
                "identifierRef": "service2_env1",
                "serviceRef": "service2",
                "serviceName": "service2",
                "environmentRef": "env1",
                "environmentName": null,
                "riskScore": 0.0,
                "riskLevel": "NO_DATA",
                "riskData": {
                    "healthScore": null,
                    "riskStatus": "NO_DATA",
                    "startTime": 0,
                    "endTime": 0,
                    "timeRangeParams": null
                },
                "type": "Application"
            }
        ],
        "edges": [
            {
                "from": "service1_env1",
                "to": "service3_env1"
            },
            {
                "from": "service2_env1",
                "to": "service3_env1"
            }
        ]
    },
    "responseMessages": []
}

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30943)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java, line 684 at r1](https://reviewable.io/reviews/harness/harness-core/30943#-MwaXLLTEVG0XccofIRV:-MwaXLLU8gW0tZINapo0:b-hgxu2x) ([raw file](https://github.com/harness/harness-core/blob/5f1a65b63d3b3c97c7a715b1777188663309a19c/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L684)):*
> ```Java
>             .filter(MonitoredServiceKeys.orgIdentifier, projectParams.getOrgIdentifier())
>             .filter(MonitoredServiceKeys.projectIdentifier, projectParams.getProjectIdentifier());
>     if (!identifiers.isEmpty()) {
> ```

why this condition?

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30943)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java, line 684 at r1](https://reviewable.io/reviews/harness/harness-core/30943#-MwaXLLTEVG0XccofIRV:-MwbiMmP-j554r11MXaV:b-r6pn9r) ([raw file](https://github.com/harness/harness-core/blob/5f1a65b63d3b3c97c7a715b1777188663309a19c/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L684)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why this condition? 
</blockquote></details>

if identifiers List is empty then it filters out all the monitoredServices. So in order to deal with that case I have used this condition.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30943)* status: :shipit: complete! ✓

**Pull request merged**
