### PR TITLE
[fix]: [CI-3633]: Fixed scm exception message

### PR DESCRIPTION
**Pull request by devkimittal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31508)

### CODE REVIEW

**Comment by devkimittal** [comment]
Earlier we were getting Unexpected error and this view when scm download was failing or wrong version was provided.
Screenshot 2022-02-06 at 7 32 01 PM

This pr will provide the correct error message and will look like
Screenshot 2022-03-16 at 2 26 05 PM

**Comment by devkimittal** [comment]
trigger messagecheck

**Review by harshjain12 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31508)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/31508#-MyHQ6oK05eivpTwe7Fb:-MyHQ6oK05eivpTwe7Fc:b1fmv1p) ([raw file](https://github.com/harness/harness-core/blob/250227f397913e34f10cbcee7e799b5230e2603b/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/SCMExceptionHandler.java#L38)):*
> ```Java
>           new InvalidRequestException(exception.getMessage(), USER));
>     } else if (errorCode == ErrorCode.INVALID_REQUEST) {
>       return NestedExceptionUtils.hintWithExplanationException(HintException.HINT_SCM_INVALID_REQUEST,
> ```

SCM service running with delegate has error



_Code quote:_
```Java
SCM service error
```

**Review by harshjain12 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31508)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/31508#-MyHQUzk8xX802rdXlZ3:-MyHQUzk8xX802rdXlZ4:b6uovf9) ([raw file](https://github.com/harness/harness-core/blob/250227f397913e34f10cbcee7e799b5230e2603b/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L133)):*
> ```Java
>         reposResponse = scmClient.getUserRepos(scmConnector);
>       } else {
>         reposResponse = scmDelegateClient.processScmRequest(
> ```

InvalidRequestException might be getting thrown in different errors too

**Review by harshjain12 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31508)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/31508#-MyHQUzk8xX802rdXlZ3:-MyHQ_8o6ilRGSgGIs5F:bpfah7l) ([raw file](https://github.com/harness/harness-core/blob/250227f397913e34f10cbcee7e799b5230e2603b/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L133)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

InvalidRequestException might be getting thrown in different errors too 
</blockquote></details>

It might not only be related to scm version issue.

**Comment by devkimittal** [comment]
___
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/31508#-MyHQUzk8xX802rdXlZ3:-MyHR0sa94Bbnzn7kwEU:bnm522x) ([raw file](https://github.com/harness/harness-core/blob/250227f397913e34f10cbcee7e799b5230e2603b/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L133)):*
<details><summary><i>Previously, harshjain12 (Harsh Jain) wrote…</i></summary><blockquote>

It might not only be related to scm version issue.
</blockquote></details>

yeah, we are not mentioning the version thing. We are just saying Delegate wasn’t able to download or run SCM service

**Comment by devkimittal** [comment]
___
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/31508#-MyHQUzk8xX802rdXlZ3:-MyHUHsQ8Fr21hd7ZODq:bkv2ugc) ([raw file](https://github.com/harness/harness-core/blob/250227f397913e34f10cbcee7e799b5230e2603b/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L133)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

yeah, we are not mentioning the version thing. We are just saying Delegate wasn’t able to download or run SCM service
</blockquote></details>

And since in the try block we have two scm calls only, so it will be pretty much related to scm

**Comment by devkimittal** [comment]
___
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/31508#-MyHQUzk8xX802rdXlZ3:-MyHUvfY30-ai2YTuP2D:byindwd) ([raw file](https://github.com/harness/harness-core/blob/250227f397913e34f10cbcee7e799b5230e2603b/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L133)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

And since in the try block we have two scm calls only, so it will be pretty much related to scm
</blockquote></details>

I checked, InvalidRequestException is being thrown in second call ie Delegate call only. So we are good with it

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31508#-:-MyHW3Lz0IoR7RzpZNfE:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
