### PR TITLE
techdebt: [PIE-2804]: Remove n+1 queries for outcomes

### PR DESCRIPTION
**Pull request by hextechpal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30915)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30915)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 434 at r1](https://reviewable.io/reviews/harness/harness-core/30915#-Mw_Ug88Ai32qLlF4Igf:-Mw_Ug88Ai32qLlF4Igg:b-wv6lgb) ([raw file](https://github.com/harness/harness-core/blob/cbf245f0fb2da5def12a3a09dec22b2cc61c7e74/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L434)):*
> ```Java
>         .include(NodeExecutionKeys.failureInfo)
>         .include(NodeExecutionKeys.adviserResponse)
>         .include(NodeExecutionKeys.oldRetry);
> ```

can we use moving projections to a single class -> NodeProjectionUtils



_Code quote:_
```Java
    query.fields()
        .include(NodeExecutionKeys.uuid)
        .include(NodeExecutionKeys.nodeId)
        .include(NodeExecutionKeys.identifier)
        .include(NodeExecutionKeys.status)
        .include(NodeExecutionKeys.failureInfo)
        .include(NodeExecutionKeys.adviserResponse)
        .include(NodeExecutionKeys.oldRetry);
```

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30915)* status: 20 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 434 at r1](https://reviewable.io/reviews/harness/harness-core/30915#-Mw_Ug88Ai32qLlF4Igf:-MweTTEvBc_ocxQvs-07:b-a4910f) ([raw file](https://github.com/harness/harness-core/blob/cbf245f0fb2da5def12a3a09dec22b2cc61c7e74/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L434)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we use moving projections to a single class -> NodeProjectionUtils
</blockquote></details>

I think for this method projections in side the method make sense. I do not ever want to change projections for this method and also i do not want to allow that flexibility as well

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30915)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30915#-:-MwerjxF3AdYQ4hfZWoI:bnfp4nl)* status: :shipit: complete! ✓

**Comment by hextechpal** [comment]
trigger ft1

**Comment by hextechpal** [comment]
trigger ft2

**Comment by diptiman-adak** [comment]
trigger ft1, ft2

**Comment by diptiman-adak** [comment]
trigger ft1

**Comment by diptiman-adak** [comment]
trigger ft2

**Pull request merged**
