### PR TITLE
fix: [CDS-37283]: Fix bug in service step v2 impl and allow previous expressions to work

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Fix bug in service step v2 impl and allow previous expressions to work

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33987)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33987)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33987)* status: 1 file(s) to review. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelperTest.java` line 105 at r3](https://reviewable.io/reviews/harness/harness-core/33987#-N3wZ_Q576Micr8WkfBe:-N3wZ_Q576Micr8WkfBf:b-jq0gyv) ([raw file](https://github.com/harness/harness-core/blob/78787c6796ebb43deff4f830fd190e77bcc71754/125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/service/ServicePlanCreatorHelperTest.java#L105)):*
> ```Java
> 
>   @Test
>   @Owner(developers = PRASHANTSHARMA)
> ```

nit: you should be the owner

**Review by prashantsharma04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33987)* status: 1 file(s) to review.

**Comment by naidu-harness** [comment]
Unrelated Tests failing. TI is looking at it

**Pull request merged**
