### PR TITLE
feat: [CDS-78026]: Support for Static Schema for Triggers

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Support for Static Schema for Triggers in Individual Schema Open Spec Api

If Env is stress we will fetch Trigger Schema from GitHub, Else will read it from the trigger.json similar to Pipeline Schema

Tests Done -
* If Only Pass node_group as pipeline we will fetch Pipeline Schema ( if Env Stress then Git Call else from pipeline.json )
* If Only Pass node_group as trigger we will fetch Trigger Schema ( if Env Stress then Git Call else from trigger.json )
* If we pass node_group as strategy and node_type as strategy we will fetch strategy schema
* If we pass node_group as step_group and node_group_differentiator as ci we will fetch ci stepGroup schema

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52188)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52188)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 518 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SFHC7EMITLBCTqym:-Nd9SFHD2ICeIoizZmGr:bix9jr5) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L518)):*
> ```Java
>   public ObjectNode getStaticSchemaForAllEntities(String nodeGroup, String nodeType, String nodeGroupDifferentiator) {
>     JsonNode jsonNode;
>     String mergedString = schemaFetcher.getMergedString(nodeGroup, nodeType, nodeGroupDifferentiator);
> ```

can switch case only be on nodeGroup?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 522 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SREoE49D51-6M4vc:-Nd9SREoE49D51-6M4vd:bnjt4rc) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L522)):*
> ```Java
>       case PIPELINE:
>         jsonNode = schemaFetcher.fetchPipelineStaticYamlSchema();
>         return jsonNode.deepCopy();
> ```

same as below
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 525 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SPWK96nXzm_VgvzO:-Nd9SPWK96nXzm_VgvzP:bxf60b2) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L525)):*
> ```Java
>       case TRIGGER:
>         jsonNode = schemaFetcher.fetchTriggerStaticYamlSchema();
>         return jsonNode.deepCopy();
> ```

why we should return deep copy?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 217 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9TC6Y2o3m8qK1_zLC:-Nd9TC6Y2o3m8qK1_zLD:b-95bmvk) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L217)):*
> ```Java
>   }
> 
>   public ObjectNode getIndividualSchema(String nodeGroup, String nodeType, String nodeGroupDifferentiator) {
> ```

make all method private
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SkPI1xxks_UXPfKI:-Nd9SkPI1xxks_UXPfKJ:bt94qk2) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L220)):*
> ```Java
>     JsonNode jsonNode;
>     try {
>       jsonNode = fetchPipelineSchemaFile(PIPELINE_JSON_PATH);
> ```

can we use getPipelineStaticSchema() instead of reading from file to keep it consistent
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 237 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9Sraw9IDD_spVg8So:-Nd9Sraw9IDD_spVg8Sp:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L237)):*
> ```Java
>   }
> 
>   public String getMergedString(String nodeGroup, String nodeType, String nodeGroupDifferentiator) {
> ```

why is this needed?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9T3GE8Gu-93PQtiAm:-Nd9T3GE8Gu-93PQtiAn:b50l9lp) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L248)):*
> ```Java
>   }
> 
>   public JsonNode fetchPipelineSchemaFile(String filePath) throws IOException {
> ```

fetchFile was correct, based on any filePath its reading the content only
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9T79hACsyHrCsd8Ra:-Nd9T79hACsyHrCsd8Rb:b-b8qjs5) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L248)):*
> ```Java
>   }
> 
>   public JsonNode fetchPipelineSchemaFile(String filePath) throws IOException {
> ```

make it private

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52188)* status: 14 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 518 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SFHC7EMITLBCTqym:-Nd9niObDHaVNPzY-NAN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L518)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can switch case only be on nodeGroup?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 522 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SREoE49D51-6M4vc:-Nd9njCs0Yf3L-yoq5xu:b-h00q3l) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L522)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as below
</blockquote></details>

Done.
To convert JsonNode to ObjectNode
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 525 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SPWK96nXzm_VgvzO:-Nd9nnEsEVPSSJnRzkoh:b-h00q3l) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L525)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we should return deep copy?
</blockquote></details>

Done.
To convert JsonNode to ObjectNode
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 217 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9TC6Y2o3m8qK1_zLC:-Nd9o0w543-9Jk5yS-J3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L217)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

make all method private
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SkPI1xxks_UXPfKI:-Nd9o0ZM9pR1ZvrkonK_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L220)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we use getPipelineStaticSchema() instead of reading from file to keep it consistent
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 237 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9Sraw9IDD_spVg8So:-Nd9nqbQ39LTp6fupdaz:b-6gqpb6) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L237)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Done.
yes Not needed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9T3GE8Gu-93PQtiAm:-Nd9nsOABbTg15_mxyi4:b-jflpyg) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L248)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

fetchFile was correct, based on any filePath its reading the content only
</blockquote></details>

Done
It was setting the local pipelineSchema Variable as well
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9T79hACsyHrCsd8Ra:-Nd9nzam7TbFNK_3Y3Ts:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/SchemaFetcher.java#L248)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

make it private
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52188)* status: 14 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 518 at r1](https://reviewable.io/reviews/harness/harness-core/52188#-Nd9SFHC7EMITLBCTqym:-NdA1Ln76K-yauPICDoR:b-dnzkht) ([raw file](https://github.com/harness/harness-core/blob/0a88d988e474493d24c6945aaf7eb913f54977a0/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L518)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i dont see the change

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52188)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by shalini-agr — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by mankrit-singh — APPROVED** [review]

**Comment by mankrit-singh** [comment]
trigger review

**Pull request merged**
