### PR TITLE
feat: [PIE-6683]: Support for service overrides in multi-service/envi…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…ronment

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41757)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41757)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 167 at r1](https://reviewable.io/reviews/harness/harness-core/41757#-NJjCbuDAiSzlWitCjGf:-NJjCbuDAiSzlWitCjGg:b-tuyjt0) ([raw file](https://github.com/harness/harness-core/blob/2ec983eb426fa3911bd7552d7a1c84f27f5bd895/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L167)):*
> ```Java
>     for (EnvironmentMapResponse environmentMapResponse : environmentsMapList) {
>       Map<String, String> environmentMap = environmentMapResponse.getEnvironmentsMapList();
>       if (environmentMapResponse.getServiceOverrideInputsYamlMap().size() > 1) {
> ```

do we need to check for null here ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/41757#-NJjCp3L8h23myx7s-tQ:-NJjCp3L8h23myx7s-tR:b4nu4ju) ([raw file](https://github.com/harness/harness-core/blob/2ec983eb426fa3911bd7552d7a1c84f27f5bd895/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L199)):*
> ```Java
>   }
> 
>   private Map<String, Map<String, ServiceOverrideInputsYaml>> getEnvironmentRefToServiceOverrideInputsMap(
> ```

is this method used ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/ServiceOverrideInputsYaml.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/41757#-NJjFKO29SXKrbb6BbqJ:-NJjFKO29SXKrbb6BbqK:bblbrd4) ([raw file](https://github.com/harness/harness-core/blob/2ec983eb426fa3911bd7552d7a1c84f27f5bd895/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/ServiceOverrideInputsYaml.java#L17)):*
> ```Java
> @Builder
> public class ServiceOverrideInputsYaml {
>   String serviceRef;
> ```

can we mark serviceRef and serviceOverrideInputs as NotNull  ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41757)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/41757#-NJjCp3L8h23myx7s-tQ:-NJu_Ehn0XjUxvWKhsrg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ec983eb426fa3911bd7552d7a1c84f27f5bd895/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/MultiDeploymentSpawnerStep.java#L199)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this method used ?
</blockquote></details>

Done.



_Code quote:_
```Java
getEnvironmentRefToServiceOverrideInputsMap
```

**Comment by sahilhindwani-harness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/ServiceOverrideInputsYaml.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/41757#-NJjFKO29SXKrbb6BbqJ:-NJu_J-vEzdczyBcuVDi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ec983eb426fa3911bd7552d7a1c84f27f5bd895/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/ServiceOverrideInputsYaml.java#L17)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we mark serviceRef and serviceOverrideInputs as NotNull  ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41757)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41757)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 1 of 2 files at r2, 3 of 6 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41757)* status: :shipit: complete! ✓

**Pull request merged**
