### PR TITLE
fix: [PL-30319]: pipeline stuck as we dont handle graceful shutdown well

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)

### CODE REVIEW

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/41476#-NJ7lrvGC6fVIZ0Ekb6Z:-NJ7nxp_8W2d2f1Dg9hc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a0f9d30624f50f3db2ddb0a0ce268bc3c1b164f/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L54)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

See next comment below. 

If we're going to do this change then this line needs to change as well to be the same logic.
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/41476#-NJ7ldV3DCUC-pmcNNd5:-NJ7nzCu5SDrMn12uyj-:bf5lu53) ([raw file](https://github.com/harness/harness-core/blob/1a0f9d30624f50f3db2ddb0a0ce268bc3c1b164f/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L92)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

Now that I look closer at the code, it appears that the implementation was not a bug so much as it was used incorrectly by clients.

The idea of `forceMaintenance` being an object was that it would _force_ the state if you set it, meaning it overrides the value found via the maintenance file.

We have a lot of these on startup:
```
    log.info("Entering startup maintenance mode");
    MaintenanceController.forceMaintenance(true);
```

And then this is called at the end of the startup method:
```
    MaintenanceController.forceMaintenance(false);
```

But that means, force maintenance to be false, regardless of the maintenance file. All of these should have instead been:

`MaintenanceController.resetForceMaintenance()`

which sets it back to null.

We do have that as well, where we see:
```
    log.info("Leaving startup maintenance mode");
    MaintenanceController.resetForceMaintenance();
```

But it looks like the incorrect usage of forcing it to `false` has propagated to a lot of places in the code.

If we go ahead with this change then it means you can only force maintenance to be true, not false. Maybe that's okay given that it was widely misunderstood.
</blockquote></details>

Done. as agreed on slack we can go ahead since we never use the actual logic behind force maintenance

**Review by brettzu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/41476#-NJ7oLQPE4ZtBn7u6NMr:-NJ7oLQPE4ZtBn7u6NMs:b4kfkun) ([raw file](https://github.com/harness/harness-core/blob/061a15d82a32d8e47eb060faa38283209470810c/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L54)):*
> ```Java
> 
>   public static boolean getMaintenanceFlag() {
>     return (forceMaintenance != null ? forceMaintenance : maintenance.get()) || shutdown.get();
> ```

Should be:



_Suggestion:_
```Java
 (forceMaintenance != null && forceMaintenance) || maintenance.get()) || shutdown.get();
```

**Review by brettzu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/41476#-NJ7oLQPE4ZtBn7u6NMr:-NJ7p6BRC5a9RKNVJYnf:btpgbqj) ([raw file](https://github.com/harness/harness-core/blob/061a15d82a32d8e47eb060faa38283209470810c/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L54)):*
>  (forceMaintenance != null && forceMaintenance) || maintenance.get() || shutdown.get();

**Review by brettzu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476#-:-NJ7sdnC1p_4J6ez9rgd:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by brettzu — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]

**Comment by abhinav-harness** [comment]
trigger ft1

**Comment by abhinav-harness** [comment]
trigger ft2

**Review by Fernando-Dourado — COMMENTED** [review]
Please, add unit tests to cover the scenarios.

Now we know why we made the change, but in a few months we probably will forget why.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476#-:-NJALB2k28yWf9FLvjrs:b-cbv1r4)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by brettzu — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/41476#-NJCnhjB1-53OS9LI5bE:-NJCnhjB1-53OS9LI5bF:bwrx97y) ([raw file](https://github.com/harness/harness-core/blob/3cbb86b7d723daaaba0add4b4636979f279e18af/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L33)):*
> ```Java
>   private static final String SHUTDOWN_FILENAME = "shutdown";
> 
>   private static Boolean forceMaintenance;
> ```

Why not remove this variable then?
___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/41476#-NJCnm919ljC3t-Bu_OJ:-NJCnm919ljC3t-Bu_OK:b-4yez3l) ([raw file](https://github.com/harness/harness-core/blob/3cbb86b7d723daaaba0add4b4636979f279e18af/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L58)):*
> ```Java
> 
>   public static boolean getMaintenanceFlag() {
>     return currentMaintenanceState.get();
> ```

Shouldn't this still be OR'd with shutdown.get()? While shutting down the background jobs should stop.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/41476#-NJCnm919ljC3t-Bu_OJ:-NJD6k_y9MxR9aCjrjs-:b757r7f) ([raw file](https://github.com/harness/harness-core/blob/3cbb86b7d723daaaba0add4b4636979f279e18af/980-commons/src/main/java/io/harness/maintenance/MaintenanceController.java#L58)):*
<details><summary><i>Previously, brettzu (Brett Zane) wrote…</i></summary><blockquote>

Shouldn't this still be OR'd with shutdown.get()? While shutting down the background jobs should stop.
</blockquote></details>

currentMaintenanceState will get updated automatically if its shutdown mode from the poller thread

**Comment by abhinav-harness** [comment]
trigger checkstylecodeformat

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by Y0709 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41476)* status: :shipit: complete! ✓

**Pull request merged**
