### PR TITLE
fix: [CDS-81869]: Split canary and primary instances in different groups

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
As part of this PR we want to split the canary instances and primary instances in a 2 different sets. Having them in the same group causes the canary deployment to update the execution info of the primary instance (eg. artifact and pipeline execution id) which causes incorrect information being displayed in the service dashboard if for example execution failed before primary deployment. This also prevents the proper work of post production rollback

**Tested cases**
1. Canary Deployment Successful, Canary Delete Successful, Primary Deployment Successful 
2. Canary Deployment Successful, Fail, Rollback (Canary Delete)
3. Canary Deployment Successful, Canary Delete Successful, Fail, Rollback (Skipped) 
4. Canary Deployment Successful, Canary Delete Successful, Primary Deployment Successful, Fail, Rollback
5. Older version of delegate

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54733)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger commonchecks, checkstylecodeformat

**Comment by abosii-harness** [comment]
trigger commonchecks, checkstylecodeformat

**Comment by abosii-harness** [comment]
trigger uts

**Comment by abosii-harness** [comment]
trigger commonchecks, checkstylecodeformat

**Comment by abosii-harness** [comment]
trigger commonchecks, checkstylecodeformat

**Comment by abosii-harness** [comment]
trigger commonchecks, checkstylecodeformat

**Comment by abosii-harness** [comment]
trigger uts

**Comment by abosii-harness** [comment]
trigger pmd, codebasehash, gitleaks

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 27 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54733)* status: Some of the checks are too old. 27 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by alebuh — DISMISSED** [review]
> Reviewed 27 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54733)* status: Some of the checks are too old. Waiting on team(s): k8s-team. 

___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sInstanceInfo.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/54733#-Ni5Fgi8BJPnuSzkj4g6:-Ni5Fgi8BJPnuSzkj4g7:b-s34atq) ([raw file](https://github.com/harness/harness-core/blob/082386bd72c793240658891fac764ad430936110/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sInstanceInfo.java#L33)):*
> ```Java
>   @NotNull private List<K8sContainer> containerList;
>   private HelmChartInfo helmChartInfo;
>   private Boolean canary;
> ```

I'm just curious, why we are using Wrapper class here?

**Comment by abosii-harness** [comment]
trigger smartchecks

**Comment by abosii-harness** [comment]
> > Reviewed 27 of 27 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/54733)_ status: Some of the checks are too old. Waiting on team(s): k8s-team.
> 
> _[`126-instance/src/main/java/io/harness/entities/instanceinfo/K8sInstanceInfo.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/54733#-Ni5Fgi8BJPnuSzkj4g6:-Ni5Fgi8BJPnuSzkj4g7:b-s34atq) ([raw file](https://github.com/harness/harness-core/blob/082386bd72c793240658891fac764ad430936110/126-instance/src/main/java/io/harness/entities/instanceinfo/K8sInstanceInfo.java#L33)):_
> 
> > ```java
> >   @NotNull private List<K8sContainer> containerList;
> >   private HelmChartInfo helmChartInfo;
> >   private Boolean canary;
> > ```
> 
> I'm just curious, why we are using Wrapper class here?

If value is not present in DB with primitive type causes NPE

**Comment by abosii-harness** [comment]
trigger uts

**Comment by abosii-harness** [comment]
trigger smartcheks

**Comment by abosii-harness** [comment]
trigger uts

**Comment by abosii-harness** [comment]
trigger smartcheks

**Comment by abosii-harness** [comment]
trigger uts

**Review by alebuh — APPROVED** [review]

**Review by TarunUba1 — APPROVED** [review]

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54733)* status: 4 file(s) to review. 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by abosii-harness** [comment]
trigger messagecheck, review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54733)* status: 3 file(s) to review. 1. unresolved discussions.

**Review by harshjain12 — APPROVED** [review]

**Pull request merged**
