### PR TITLE
feat: [PIE-6194]: Fix one condition for stuck executions

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)

We went over the interrupts and found out that most of the interrupt are updating only plan status which is already correct.
This was mainly because the interrupt was registered after the pipeline was in terminal status. This PR fixes that logic wherein we cannot save interrupt if the execution is already in terminal status

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPjHqa9DmX8GjPHshP:-NGPjHqa9DmX8GjPHshQ:b-7lfnkt) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L71)):*
> ```Java
>     PlanExecution planExecution = planExecutionService.get(interrupt.getPlanExecutionId());
>     if (StatusUtils.isFinalStatus(planExecution.getStatus())) {
>       throw new InvalidRequestException(
> ```

Shouldnt we mark the interrupt to processed unsuccessful? or with exception it will be done?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPjHqa9DmX8GjPHshP:-NGPqBgu9yTxCwf33Yzh:bsq6tky) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt we mark the interrupt to processed unsuccessful? or with exception it will be done?
</blockquote></details>

We will not even save this interrupt.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGPsAtaAyFBjDNpGorO:bezzr1m) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
> ```Java
>     List<Interrupt> interrupts = interruptService.fetchActiveInterrupts(interrupt.getPlanExecutionId());
>     // Use projections
>     PlanExecution planExecution = planExecutionService.get(interrupt.getPlanExecutionId());
> ```

We can optimize this to just get the status

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGR22ck0kYj0b5giTxm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We can optimize this to just get the status 
</blockquote></details>

Done.

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGR4nUL1jk8jhWL4v9a:b-ucg0lr) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@sahilhindwani-harness we should use find({_id:....}, {_id:0, status:0}) and this would use projection covered

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGR62lZ7XHHRa0uhfz4:b-eq5m92) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

@sahilhindwani-harness we should use find({_id:....}, {_id:0, status:0}) and this would use projection covered
</blockquote></details>

PP i think you mean only _id: 0, status we are using then it cannot be 0 isn't?

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGR6oQ80huI0jo8_wfH:bgqgfrr) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

PP i think you mean only _id: 0, status we are using then it cannot be 0 isn't?
</blockquote></details>

find({_id:....}, {_id:0, status:1}) i think you meant this

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGR7c3J51NGNyWauHF1:bu1io2x) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

find({_id:....}, {_id:0, status:1}) i think you meant this
</blockquote></details>

Yes, I think Prashant meant this only. Making the changes ready, will update the PR in sometime

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGRF1aN-kjxIPDSdoqF:b-w17m6g) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes, I think Prashant meant this only. Making the changes ready, will update the PR in sometime
</blockquote></details>

Sahil i think we should not expose getWithProjections here, as caller doesn't know uuid is 0, here only status is used, thus we can have function to expose only getStatus, so anyone using it knows only status is coming.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGRHyGg-SxQv3TAOCDD:b-cp3r6o) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Sahil i think we should not expose getWithProjections here, as caller doesn't know uuid is 0, here only status is used, thus we can have function to expose only getStatus, so anyone using it knows only status is coming. 
</blockquote></details>

I updated the name of this function  in my previous already, let me check why it is not updated here.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGRIbpA7Mkjvph_yo_e:bbbub3r) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I updated the name of this function  in my previous already, let me check why it is not updated here.
</blockquote></details>

Pushed the change, had not pushed latest.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 8 files at r2, 2 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/39820#-NGPsAtaAyFBjDNpGorN:-NGRWQeQ7MKb59HydPos:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/55e010236d8243e9e6d0d423c73709b11bc49ea4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortAllInterruptHandler.java#L69)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Pushed the change, had not pushed latest.
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 4 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 8 files at r2, 1 of 3 files at r3, 2 of 4 files at r4, 3 of 3 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39820)* status: :shipit: complete! ✓

**Pull request merged**
