### PR TITLE
fix: [CDS-35067]: Make auto scaling operation optional

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
JIRA - https://harness.atlassian.net/browse/CDS-35067

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33601)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger authorcheck

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/pcf/pcftaskhandler/PcfSetupCommandTaskHandler.java` line 777 at r3](https://reviewable.io/reviews/harness/harness-core/33601#-N3JV4qh2ENe0Cp3xL0W:-N3JV4qmENMDMP-IsH4a:bwi3fj) ([raw file](https://github.com/harness/harness-core/blob/973632541c466f702a128498f27127541aed242b/930-delegate-tasks/src/main/java/software/wings/delegatetasks/pcf/pcftaskhandler/PcfSetupCommandTaskHandler.java#L777)):*
> ```Java
>       try {
>         pcfCommandTaskBaseHelper.disableAutoscalar(appAutoscalarRequestData, executionLogCallback);
>       } catch (PivotalClientApiException e) {
> ```

Duplicate code. Please add this logic at io.harness.delegate.cf.PcfCommandTaskBaseHelper#disableAutoscalar



_Code quote:_
```Java
disableAutoscalar
```

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfCommandTaskBaseHelper.java` line 348 at r3](https://reviewable.io/reviews/harness/harness-core/33601#-N3JVACw45J4YfhtpjXh:-N3JVACw45J4YfhtpjXi:b-2ft0d3) ([raw file](https://github.com/harness/harness-core/blob/973632541c466f702a128498f27127541aed242b/930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfCommandTaskBaseHelper.java#L348)):*
> ```Java
>         try {
>           disableAutoscalar(appAutoscalarRequestData, executionLogCallback);
>         } catch (PivotalClientApiException e) {
> ```

Same. Duplicate code. Can add in io.harness.delegate.cf.PcfCommandTaskBaseHelper#disableAutoscalar

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfCommandTaskBaseHelper.java` line 279 at r3](https://reviewable.io/reviews/harness/harness-core/33601#-N3JVFWA91Ockycz4geF:-N3JVFWA91Ockycz4geG:b368ie6) ([raw file](https://github.com/harness/harness-core/blob/973632541c466f702a128498f27127541aed242b/930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfCommandTaskBaseHelper.java#L279)):*
> ```Java
>       try {
>         autoscalarStateChanged = disableAutoscalar(appAutoscalarRequestData, executionLogCallback);
>       } catch (PivotalClientApiException e) {
> ```

Same duplicate code issue.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33601)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r2, 2 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33601#-:-N3U09W07FYImiSkbZPY:bnfp4nl)* status: 1. unresolved discussions.

**Comment by RishabhGupta34** [comment]
trigger tin0

**Review by arpit3107 — APPROVED** [review]
> Reviewed 4 of 10 files at r2, 4 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33601)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 10 files at r2, 4 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33601)* status: :shipit: complete! ✓

**Pull request merged**
