### PR TITLE
[feat]: [CDS-38213]: Add Azure WebApp steps

### PR DESCRIPTION
**Pull request by tmacari-harness**
[CDS-38213]: Add Azure WebApp steps

[CDS-38213]: https://harness.atlassian.net/browse/CDS-38213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Is it new task type? NO

Did you add a new class which is added in kryo serialization. -  NO

Did you make changes to the code in a backward-compatible manner?  YES

will the new version of the delegate receive old version task and process?  YES

If new version of the manager receives response for the old task will it be able to handle it successfully?   YES

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager.   -   NO

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay.    -    YES

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay.    -    YES

Did you remove an enum → NO

Did you add an enum →  Yes but it is not sent to delegate.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)

### CODE REVIEW

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 42 of 45 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by vlica-harness — DISMISSED** [review]
> Reviewed 41 of 45 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by nassergonzalez — DISMISSED** [review]
:lgtm:

> Reviewed 41 of 45 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691#-:-N3Q-vDW9DYXeEoGlpHJ:bnfp4nl)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/33691#-N3Q8w_0ERzPA5KjXhAs:-N3Q8w_1DreT3PCbea5T:b-xmncpn) ([raw file](https://github.com/harness/harness-core/blob/2d390e09d46b63db47fe529b0b8e03e039abb357/943-enforcement-beans/src/main/java/io/harness/enforcement/constants/FeatureRestrictionName.java#L69)):*
> ```Java
>   DELETE_STACK,
>   ROLLBACK_STACK,
>   AZURE_WEBAPP_SLOT_SETUP,
> ```

please add these in the end and not in between

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 41 of 45 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 40 of 45 files at r1, 2 of 3 files at r2, 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 38 of 38 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 32 of 38 files at r7, 13 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by vlica-harness — DISMISSED** [review]

**Review by abosii-harness — APPROVED** [review]
> Reviewed 15 of 21 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

___
*[`970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java` line 99 at r10](https://reviewable.io/reviews/harness/harness-core/33691#-N4S49HX7V2xt2UO4FRF:-N4S49HX7V2xt2UO4FRG:b-jq5jrg) ([raw file](https://github.com/harness/harness-core/blob/4884be62bd5170b9891a1c940f0ddadb0eb15f88/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L99)):*
> ```Java
>   String COMMAND = "Command";
>   String STRATEGY_NODE = "StrategyNode";
>   String AZURE_WEBAPP_SLOT_DEPLOYMENT = "AzureSlotDeployment";
> ```

nit: maybe we should remove it from const name as well

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 23 of 25 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Comment by rijajoo** [comment]
trigger ti3

**Comment by tmacari-harness** [comment]
trigger tin1

**Comment by tmacari-harness** [comment]
trigger TIbootstrap1-tin1

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 8 files at r10, 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: 6 file(s) to review.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r15, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 9 of 45 files at r1, 10 of 38 files at r7, 2 of 13 files at r8, 3 of 21 files at r9, 5 of 8 files at r10, 20 of 25 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, 3 of 3 files at r15, 1 of 3 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691#-:-N4XM-pu2bMZknCF-TaJ:bnfp4nl)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
Approve haschange 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691#-:-N4Xt-NK8OGXFIZ0IKlE:b-n6sgk2)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691#-:-N4a1vrj6jocxRf0vgYL:bnfp4nl)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 10 of 38 files at r7, 2 of 13 files at r8, 3 of 21 files at r9, 5 of 8 files at r10, 20 of 25 files at r11, 3 of 3 files at r12, 1 of 1 files at r13, 3 of 3 files at r15, 2 of 2 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33691)* status: :shipit: complete! ✓

**Pull request merged**
