### PR TITLE
feat: [CDS-73716]: add AWS CDK deploy step

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
feat: [CDS-73716]: add AWS CDK deploy step
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-73716]: https://harness.atlassian.net/browse/CDS-73716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51008)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger ut0

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by tmacari-harness** [comment]
trigger ut0

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by tmacari-harness** [comment]
trigger ut8

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by tmacari-harness** [comment]
trigger ut5

**Comment by tmacari-harness** [comment]
trigger ut5

**Comment by tmacari-harness** [comment]
trigger ut6

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by tmacari-harness** [comment]
trigger ut9

**Comment by tmacari-harness** [comment]
trigger ut5

**Comment by tmacari-harness** [comment]
trigger ut6

**Comment by tmacari-harness** [comment]
trigger ut7

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by tmacari-harness** [comment]
trigger ut5

**Comment by tmacari-harness** [comment]
trigger ut6

**Comment by tmacari-harness** [comment]
trigger ut5

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by tmacari-harness** [comment]
trigger uts

**Comment by tmacari-harness** [comment]
trigger ut2

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by tmacari-harness** [comment]
trigger ut2

**Review by piyush-bhuwalka — APPROVED** [review]

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51008)* status: 28 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 1770 at r5](https://reviewable.io/reviews/harness/harness-core/51008#-Nafwmh0-9YBY45E_XAE:-Nafwmh0-9YBY45E_XAF:b-vmrar7) ([raw file](https://github.com/harness/harness-core/blob/77ec3b82cf29951fa0deeae7562787235ebdb877/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L1770)):*
> ```JSON
>         }
>       ],
>       "$schema": "http://json-schema.org/draft-07/schema#"
> ```

please update static schema too.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51008)* status: 28 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsCdkDeployPluginInfoProvider.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/51008#-NafwU0u8M0oVJn66MqS:-Nag45596HSgG9wv0-vR:b-2u2365) ([raw file](https://github.com/harness/harness-core/blob/77ec3b82cf29951fa0deeae7562787235ebdb877/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsCdkDeployPluginInfoProvider.java#L43)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we extract common piece of code to an abstract class.
@tmacari-harness , could we please do this to cdk steps only?
</blockquote></details>

will do in next PRs

**Comment by tmacari-harness** [comment]
trigger ut7

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsCdkDeployPluginInfoProvider.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/51008#-NafwU0u8M0oVJn66MqS:-NakYLFM6hKuax6_t628:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/77ec3b82cf29951fa0deeae7562787235ebdb877/125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/AwsCdkDeployPluginInfoProvider.java#L43)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

will do in next PRs
</blockquote></details>

Done

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51008)* status: 28 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 19 of 28 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51008)* status: 28 file(s) to review.

**Comment by tmacari-harness** [comment]
trigger review

**Pull request merged**
