### PR TITLE
[feat]: [PL-28599]: Input Sets API Implementation from Server Stub

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Added API redesign implementation for Input Sets APIs.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)

### CODE REVIEW

**Review by senjucanon2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/38819#-NEfx4po2KcIU1CFn3rK:-NEfx4po2KcIU1CFn3rL:b-ahb8rz) ([raw file](https://github.com/harness/harness-core/blob/7c4618c7874556369c6b674ed1ba23e0ec0cede9/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L137)):*
> ```Java
>     String yaml = removeRuntimeInputFromYaml(requestBody.getInputSetYaml());
> 
>     // Create InputSetRequestInfoDTO same as PipelineRequestInfoDTO so that below method can be resolved.
> ```

    // Create InputSetRequestInfoDTO same as PipelineRequestInfoDTO so that below method can be resolved.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5, 3 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 14 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 170 at r8](https://reviewable.io/reviews/harness/harness-core/38819#-NHNpHMi9nqs6Nk4MAXB:-NHNpHMi9nqs6Nk4MAXC:bypsmy7) ([raw file](https://github.com/harness/harness-core/blob/d92dc29d9029af973d4004abde05006e2c91330d/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L170)):*
> ```Java
>   }
> 
>   private String getPipelineYaml(String accountId, String orgIdentifier, String projectIdentifier,
> ```

Dont we have already get pipeline method which handles for old and new git flow?



_Code quote:_
```Java
getPipelineYaml
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 15 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 170 at r8](https://reviewable.io/reviews/harness/harness-core/38819#-NHNpHMi9nqs6Nk4MAXB:-NI74vWAAYTJb13x0wRJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d92dc29d9029af973d4004abde05006e2c91330d/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L170)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Dont we have already get pipeline method which handles for old and new git flow?
</blockquote></details>

done



_Code quote (from pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java):_
```Java
      pipelineYaml = InputSetValidationHelper.getPipelineYamlForOldGitSyncFlow(pipelineService, accountId,
          orgIdentifier, projectIdentifier, pipelineIdentifier, pipelineBranch, pipelineRepoID);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 111 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75-NuB5s4-NJxqgnQ:-NI75-NuB5s4-NJxqgnR:bof2ffw) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L111)):*
> ```Java
>     boolean deleted = pmsPipelineService.delete(account, org, project, pipeline, null);
>     if (!deleted) {
>       throw new InvalidRequestException(String.format("Pipeline with identifier %s cannot be deleted.", pipeline));
> ```

why we removed this?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 197 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75Kl8Crq1xiEp7l5k:-NI75Kl8Crq1xiEp7l5l:b-jsd1t9) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L197)):*
> ```Java
>           && !basicPipeline.getTags().equals(requestInfoDTO.getTags())) {
>         throw new InvalidRequestException(
>             String.format("Expected updated Pipeline tags in YAML to be [%s], but was [%s]", requestInfoDTO.getTags(),
> ```

Changing error messages, please check if automation doesn't break

**Review by mankrit-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 15 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/38819#-NEfx4po2KcIU1CFn3rK:-NI76y7k3kecIMjzcSbU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c4618c7874556369c6b674ed1ba23e0ec0cede9/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L137)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

    // Create InputSetRequestInfoDTO same as PipelineRequestInfoDTO so that below method can be resolved.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 111 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75-NuB5s4-NJxqgnQ:-NI77B7v5kggD0B7XUFI:b-exu54g) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L111)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we removed this?
</blockquote></details>

It served no function, since if it were already deleted/DNE then it throws Exception from within the method itself
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 197 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75Kl8Crq1xiEp7l5k:-NI772lz64UuZWUZdvsJ:ba5x7cg) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Changing error messages, please check if automation doesn't break
</blockquote></details>

Recently created, automation yet to be done here.

**Review by mankrit-singh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 15 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java` line 111 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75-NuB5s4-NJxqgnQ:-NI77i1dA3ffE2_aH0dW:byew2fi) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/PipelinesApiImpl.java#L111)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

It served no function, since if it were already deleted/DNE then it throws Exception from within the method itself
</blockquote></details>

pmsPipelineService.delete <- from this



_Code quote:_
```Java
pmsPipelineService.delete
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r13.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 197 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75Kl8Crq1xiEp7l5k:-NI7sT36-FEAI9YrgQis:bobgras) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L197)):*
<details><summary><i>Previously, mankrit-singh (Mankrit Singh) wrote…</i></summary><blockquote>

Recently created, automation yet to be done here.
</blockquote></details>

i meant this method is called for older apis, thus existing automation may fail

**Comment by mankrit-singh** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 197 at r14](https://reviewable.io/reviews/harness/harness-core/38819#-NI75Kl8Crq1xiEp7l5k:-NI7v62l-5scq7puId5r:bucmb4m) ([raw file](https://github.com/harness/harness-core/blob/0dc49a1812da52f3b7d98f45d643e232daa1af59/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i meant this method is called for older apis, thus existing automation may fail
</blockquote></details>

No, this method is only used in new APIs after YAML metadata removal

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38819)* status: 9 file(s) to review.

**Pull request merged**
