### PR TITLE
[feat]: [CDS-52208]: winrm session parameters in ng

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44536)

### CODE REVIEW

**Review by ivan-83 — COMMENTED** [review]
Question: why do command parameters need to be added to WinRmCredentialsSpec and WinRmCredentialsSpecDTO?

> Reviewed 6 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536#-:-NPTJF2b4ieHHbUozx_c:b-k69cxb)* status: 16 file(s) to review. 0 of 2 approvals obtained.

**Review by vladimir-peric — COMMENTED** [review]
These additional Invoke-Command parameters are actually provided as a part of WinRm connection attributes. This is the same way as done in CG. It has sense to be there as are used together with authentication and port attributes, and should also be entered within WinRm Credential configuration in UI.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536#-:-NPTRPuKD0WL8TIO48Pd:bse3747)* status: 18 file(s) to review. 0 of 2 approvals obtained.

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Review by ivan-83 — DISMISSED** [review]
LGTM with minor comments

> Reviewed 9 of 16 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536#-:-NPTVCRV6n4BkdL7ewOv:b-z5hs9a)* status: 18 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java` line 168 at r2](https://reviewable.io/reviews/harness/harness-core/44536#-NPTUMPA48om4Chuupsj:-NPTUMPA48om4Chuupsk:b-e17aqe) ([raw file](https://github.com/harness/harness-core/blob/188ff8b7d14462cf559d0029950b9bc9d537db1c/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java#L168)):*
> ```Java
>             .timeout(SESSION_TIMEOUT)
>             .commandParameters(taskParameters.getSshKeySpecDTO() instanceof WinRmCredentialsSpecDTO
>                     ? ((WinRmCredentialsSpecDTO) taskParameters.getSshKeySpecDTO()).getParameters()
> ```

Minor - Also ((WinRmCredentialsSpecDTO) taskParameters.getSshKeySpecDTO()).getParameters() can be null because we don't have default value for params in 
 WinRmCredentialsSpecDTO class.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/44536#-NPTUdGCAODr43CnzElL:-NPTUdGCAODr43CnzElM:bstge6t) ([raw file](https://github.com/harness/harness-core/blob/188ff8b7d14462cf559d0029950b9bc9d537db1c/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java#L200)):*
> ```Java
>             .timeout(SESSION_TIMEOUT)
>             .commandParameters(taskParameters.getSshKeySpecDTO() instanceof WinRmCredentialsSpecDTO
>                     ? ((WinRmCredentialsSpecDTO) taskParameters.getSshKeySpecDTO()).getParameters()
> ```

the same as above
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmUtils.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/44536#-NPTUknz3JSIRDhdtLKx:-NPTUknz3JSIRDhdtLKy:bstge6t) ([raw file](https://github.com/harness/harness-core/blob/188ff8b7d14462cf559d0029950b9bc9d537db1c/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmUtils.java#L47)):*
> ```Java
>             .commandParameters(winRmCommandTaskParameters.getWinRmInfraDelegateConfig() != null
>                         && winRmCommandTaskParameters.getWinRmInfraDelegateConfig().getWinRmCredentials() != null
>                     ? winRmCommandTaskParameters.getWinRmInfraDelegateConfig().getWinRmCredentials().getParameters()
> ```

the same as above
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/WinRmCredentialsSpecDTO.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44536#-NPTUu7UEaaRx1JPV50T:-NPTUu7UEaaRx1JPV50U:b-qo4fuw) ([raw file](https://github.com/harness/harness-core/blob/188ff8b7d14462cf559d0029950b9bc9d537db1c/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/WinRmCredentialsSpecDTO.java#L44)):*
> ```Java
>   @Schema(description = "WinRm port") @DefaultValue("5986") int port = 5986;
>   @Valid @NotNull WinRmAuthDTO auth;
>   @Attributes(title = "Parameters") private List<WinRmCommandParameter> parameters;
> ```

Add default value here empty list, also add the default value for Lombok builder
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/WinRmCredentialsSpec.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44536#-NPTVAs09C-Q8YK6sVsA:-NPTVAs09C-Q8YK6sVsB:b-qo4fuw) ([raw file](https://github.com/harness/harness-core/blob/188ff8b7d14462cf559d0029950b9bc9d537db1c/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/WinRmCredentialsSpec.java#L34)):*
> ```Java
>   @DefaultValue("5986") int port;
>   WinRmAuth auth;
>   List<WinRmCommandParameter> parameters;
> ```

Add default value here empty list, also add the default value for Lombok builder

**Comment by vladimir-peric** [comment]
trigger ut4

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536#-:-NPY0L57BBX0pmXN-5_O:bnfp4nl)* status: 21 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java` line 224 at r4](https://reviewable.io/reviews/harness/harness-core/44536#-NPY0CL39ldbF6Qz5zBv:-NPY0CL39ldbF6Qz5zBw:b6obciq) ([raw file](https://github.com/harness/harness-core/blob/3e8b44ddbff72104952e2c267ab40e2536203f7b/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java#L224)):*
> ```Java
>           : Collections.emptyList();
>       return commandParameters == null ? Collections.emptyList() : commandParameters;
>     } catch (Exception e) {
> ```

why exception handling here?

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536)* status: 21 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java` line 224 at r4](https://reviewable.io/reviews/harness/harness-core/44536#-NPY0CL39ldbF6Qz5zBv:-NPY2C5YE53S8Bz4P82A:b-g1m76w) ([raw file](https://github.com/harness/harness-core/blob/3e8b44ddbff72104952e2c267ab40e2536203f7b/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/WinRmShellScriptTaskNG.java#L224)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

why exception handling here?
</blockquote></details>

Actually it is not needed, this is a good point, removed it.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536#-:-NPY8trz0EBQBeeJfdKe:bnfp4nl)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536#-:-NPYDun8AWVaSlm0wi9S:bnfp4nl)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 13 of 16 files at r1, 1 of 3 files at r2, 5 of 7 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44536)* status: :shipit: complete! ✓

**Pull request merged**
