### PR TITLE
feat: [PL-25137]: Fixed duplicate error message for UI

### PR DESCRIPTION
**Pull request by meenakshi-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33373)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33373)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/33373#-N2Vi-ib4pA1dF1rVtXB:-N2Vi-ib4pA1dF1rVtXC:b-wxqevz) ([raw file](https://github.com/harness/harness-core/blob/9661872031acbbfad50df1c9f9af57a06ab8be7a/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L96)):*
> ```Java
>     } catch (DuplicateKeyException de) {
>       throw new DuplicateFieldException(String.format(
>           "Invalid request: Variable with identifier [%s] already exists in this scope", variableDTO.getIdentifier()));
> ```

Why adding "Invalid request:" in message?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33373)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/33373#-N2Vi-ib4pA1dF1rVtXB:-N2W6y5RCdCCZa1dYCZ6:bl4jzg1) ([raw file](https://github.com/harness/harness-core/blob/9661872031acbbfad50df1c9f9af57a06ab8be7a/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L96)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why adding "Invalid request:" in message?
</blockquote></details>

This is the exact message we show on UI for Secrets. Hence to keep it consistent. https://harness.atlassian.net/browse/PL-25137

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33373)* status: 1 change requests. 1. unresolved discussions.

**Review by VikasMaddukuriHarness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33373#-:-N2WGqVK7Z-enWBlTBvk:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33373)* status: :shipit: complete! ✓

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33373)* status: :shipit: complete! ✓

**Pull request merged**
