### PR TITLE
fix: [PL-31862]: Issue with Approval stage notification

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
Adds feature flag to list of alerts affected by change  https://harness.atlassian.net/browse/PL-29104.
This will resolve the issue of approval alerts being incorrectly sent via slack.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44240)

### CODE REVIEW

**Review by lasdox — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44240)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44240)* status: 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AlertServiceImpl.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/44240#-NOzvJ0QEUctGDe3p8iu:-NOzvJ0QEUctGDe3p8iv:b-cj9jwt) ([raw file](https://github.com/harness/harness-core/blob/220a3046d5598f38442beb4c5c95bd31bc80543b/400-rest/src/main/java/software/wings/service/impl/AlertServiceImpl.java#L122)):*
> ```Java
> 
>   @Override
>   public List<AlertType> listCategoriesAndTypes(String accountId) {
> ```

Please, add unit test coverage to this new code block.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44240)* status: Some of the checks are too old. 1 file(s) to review. 1 of 2 approvals obtained.

**Review by vcalasansh — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44240)* status: Some of the checks are too old.

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44240)* status: Some of the checks are too old.

**Pull request merged**
