### PR TITLE
feat: [CDS-40803]: GCP connector migration.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Migration for GCP cloud provider in CG. It has 2 credential type
1) Manual Config using Service account token. By default the secret is being created at project level and referenced at project level.
2) Using delegate selector.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37688)

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/ConnectorFactory.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOsw7m2RextlIBD-6-:-NCOsw7m2RextlIBD-60:b-r2i1r7) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/ConnectorFactory.java#L24)):*
> ```Java
>   private static final BaseConnector kubernetesConnector = new KubernetesConnectorImpl();
>   private static final BaseConnector gitConnector = new GitConnectorImpl();
>   private static final GCPConnectorImpl gcpConnector = new GCPConnectorImpl();
> ```

shouldn't this be `BaseConnector`.?



_Code quote:_
```Java
GCPConnectorImpl gcpConnector
```
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOtyht9vZRX9pBDkYa:-NCOtyht9vZRX9pBDkYb:bx2m86x) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L56)):*
> ```Java
>       String scope;
>       if (isBlank(migratedEntities.get(cgEntityId).getOrgIdentifier())) {
>         scope = "account.";
> ```

no magic strings please. Convert them to string constants.
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOtu243RTtx-CkWQ-P:-NCOtu243RTtx-CkWQ-Q:bpdlrvi) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L62)):*
> ```Java
>         scope = "";
>       }
>       SecretRefData secretRefData = new SecretRefData(scope + clusterConfig.getEncryptedServiceAccountKeyFileContent());
> ```

this can be `this.getSecretId()`



_Code quote:_
```Java
clusterConfig.getEncryptedServiceAccountKeyFileContent()
```
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOuArU-J3rZFRY9-ad:-NCOuArU-J3rZFRY9-ae:b9o1fx6) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L63)):*
> ```Java
>       }
>       SecretRefData secretRefData = new SecretRefData(scope + clusterConfig.getEncryptedServiceAccountKeyFileContent());
>       credentialDTO = GcpConnectorCredentialDTO.builder()
> ```

can't there be `delegateSelectors` in case of `MANUAL_CREDENTIALS`.?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/ConnectorFactory.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOsw7m2RextlIBD-6-:-NCP7E8hEMXojowT58-5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/ConnectorFactory.java#L24)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

shouldn't this be `BaseConnector`.?
</blockquote></details>

Done.
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOtyht9vZRX9pBDkYa:-NCP7FM239Yf_dlZmKLb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L56)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

no magic strings please. Convert them to string constants.
</blockquote></details>

Done.
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOtu243RTtx-CkWQ-P:-NCP7G93CTuqsa-4_zMI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L62)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

this can be `this.getSecretId()`
</blockquote></details>

Done.
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/37688#-NCOuArU-J3rZFRY9-ad:-NCP7Gsh69E1OmiLG7xQ:b-sd24bj) ([raw file](https://github.com/harness/harness-core/blob/8d19a17399720045e251d2b2cd3f2ccbe96a1ff2/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L63)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

can't there be `delegateSelectors` in case of `MANUAL_CREDENTIALS`.?
</blockquote></details>

The UI did not show the provision to add delegate selector but we could have modified the yaml to do so. Hence I have changed it

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/37688#-NCPqXus7F75pUebqVrR:-NCPqXus7F75pUebqVrS:b6kr7q9) ([raw file](https://github.com/harness/harness-core/blob/739117cb4508ca02a2c6fe4b898cf5852203bd38/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L33)):*
> ```Java
> 
> public class GCPConnectorImpl implements BaseConnector {
>   private static final String ACCOUNT = "account.";
> ```

rename this to something more meaningful, like `ACCOUNT_SCOPE_PREFIX`
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/37688#-NCPqde_3RnukXfDUi0Y:-NCPqde_3RnukXfDUi0Z:bwibb61) ([raw file](https://github.com/harness/harness-core/blob/739117cb4508ca02a2c6fe4b898cf5852203bd38/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L35)):*
> ```Java
>   private static final String ACCOUNT = "account.";
>   private static final String ORG = "org.";
>   private static final String PROJECT = "";
> ```

` = StringUtils.EMPTY`

**Review by GoelPratyush99 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688#-:-NCPuyLI4OTY3KPoVNf2:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/37688#-NCPqXus7F75pUebqVrR:-NCPuz9L3ELv5fCmgA0X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/739117cb4508ca02a2c6fe4b898cf5852203bd38/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L33)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

rename this to something more meaningful, like `ACCOUNT_SCOPE_PREFIX`
</blockquote></details>

Done.
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 35 at r4](https://reviewable.io/reviews/harness/harness-core/37688#-NCPqde_3RnukXfDUi0Y:-NCPuz_tA3uI9umQIDn3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/739117cb4508ca02a2c6fe4b898cf5852203bd38/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L35)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

` = StringUtils.EMPTY`
</blockquote></details>

Done.

**Review by shubham-in10se — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: :shipit: complete! ✓

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: :shipit: complete! ✓

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/37688#-NCSlu4k6puXPsdUbFS9:-NCSlu4k6puXPsdUbFSA:bo4uxt9) ([raw file](https://github.com/harness/harness-core/blob/084f5b77696dbc13c6886802432bd7f18b4e1be1/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L33)):*
> ```Java
> import org.apache.commons.lang3.StringUtils;
> 
> public class GCPConnectorImpl implements BaseConnector {
> ```

Just wondering - GCP is capitalized in this class name, whereas in GcpConfig it's not. What is the convention we follow?
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 61 at r5](https://reviewable.io/reviews/harness/harness-core/37688#-NCSmGwq4QAIyJNHozS-:-NCSmGwq4QAIyJNHozS0:byz0fbu) ([raw file](https://github.com/harness/harness-core/blob/084f5b77696dbc13c6886802432bd7f18b4e1be1/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L61)):*
> ```Java
>       credentialDTO = GcpConnectorCredentialDTO.builder().gcpCredentialType(INHERIT_FROM_DELEGATE).build();
>     } else {
>       CgEntityId cgEntityId = childEntities.stream().findFirst().get();
> ```

Are we sure that we'll have at least one childEntity always? Anyway it's safer to add isPresent check
Otherwise, findFirst() would return empty, and get() would throw an exception I guess.

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 33 at r5](https://reviewable.io/reviews/harness/harness-core/37688#-NCSlu4k6puXPsdUbFS9:-NCTZHPfB5NirG--X0lF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/084f5b77696dbc13c6886802432bd7f18b4e1be1/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L33)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Just wondering - GCP is capitalized in this class name, whereas in GcpConfig it's not. What is the convention we follow?
</blockquote></details>

Done.
___
*[`100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java` line 61 at r5](https://reviewable.io/reviews/harness/harness-core/37688#-NCSmGwq4QAIyJNHozS-:-NCTZI9n2wNYrRPrF9x_:b-rm6ml2) ([raw file](https://github.com/harness/harness-core/blob/084f5b77696dbc13c6886802432bd7f18b4e1be1/100-migrator/src/main/java/io/harness/ngmigration/connector/GCPConnectorImpl.java#L61)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Are we sure that we'll have at least one childEntity always? Anyway it's safer to add isPresent check
Otherwise, findFirst() would return empty, and get() would throw an exception I guess.

</blockquote></details>

Ideally we should only pick org and account identifier from SECRET entity instead of first one.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: 2. unresolved discussions.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: :shipit: complete! ✓

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37688)* status: :shipit: complete! ✓

**Pull request merged**
