### PR TITLE
[feat]: [CDS-38223]: FileStore filtering enhancements

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33921)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 14 of 17 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33921#-:-N3eBEuE4Jb2Z8zZrHbZ:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger ti3, ti4

**Comment by vladimir-peric** [comment]
trigger ti3, ti4

**Comment by vladimir-peric** [comment]
trigger ti3

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33921#-:-N3eW9Lv6anoe7Aih8z7:bnfp4nl)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger codeformat

**Comment by vladimir-peric** [comment]
trigger codeformat

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33921#-:-N3eoJzp8ea9Pj-ZXhNw:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger codeformat

**Comment by vladimir-peric** [comment]
trigger ti4

**Comment by vladimir-peric** [comment]
trigger codeformat

**Comment by vladimir-peric** [comment]
trigger codeformat

**Comment by vladimir-peric** [comment]
trigger ti3

**Comment by vladimir-peric** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by ivan-83 — APPROVED** [review]
> Reviewed 20 of 21 files at r5, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33921)* status: :shipit: complete! ✓

**Pull request merged**
