### PR TITLE
fix:[CDS-57705]: Populate adoptDelegateDecryption from an FF

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- When a service variable value is a secret expression and that expression uses nested variables, we are unable to render it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631#-:-NRKXXA0BhHdHv3D5e_6:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by Fernando-Dourado** [comment]
trigger featurenamecheck

**Review by rafaelmart1ns — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)* status: :shipit: complete! ✓

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by rafaelmart1ns — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)* status: :shipit: complete! ✓

**Review by rafaelmart1ns — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45631)* status: :shipit: complete! ✓

**Pull request merged**
