### PR TITLE
feat: [SSCA-843]: Artifact listing license view

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
Adds license filter for artifact listing

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54746)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger uts

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54746)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 238 at r2](https://reviewable.io/reviews/harness/harness-core/54746#-NhzTvzv3WnlvIHp7WY9:-NhzTvzv3WnlvIHp7WYA:bjn85g) ([raw file](https://github.com/harness/harness-core/blob/616b2b86b0bcc505c3cbcb54bdf3876e1faf6a11/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L238)):*
> ```Java
>   private Criteria[] getCriteriaFromOrchestrationIds(List<String> orchestrationIds) {
>     return orchestrationIds.stream()
>         .map(orchestrationId -> Criteria.where(ArtifactEntityKeys.orchestrationId).is(orchestrationId))
> ```

Why are we not using "in" query here?
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 263 at r2](https://reviewable.io/reviews/harness/harness-core/54746#-NhzUIoE73qcDwPFIm0y:-NhzUIoE73qcDwPFIm0z:b-psb8ty) ([raw file](https://github.com/harness/harness-core/blob/616b2b86b0bcc505c3cbcb54bdf3876e1faf6a11/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L263)):*
> ```Java
>     Criteria[] licenseCriteria =
>         getLicenseCriteria(accountId, orgIdentifier, projectIdentifier, body.getLicenseFilter());
> ```

can we put getLicenseCriteria in line 262?

**Comment by reetika04** [comment]
trigger uts

**Review by arpit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54746#-:-Ni3WjGb-WQ_pMgDoCs2:bnfp4nl)* status: 4 file(s) to review.

**Pull request merged**
