### PR TITLE
feat: [PL-39293]: Add manual vault configure to AzurekeyVault

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
We have introduced a new boolean variable **vaultconfiguredManually** which takes in information, if the vault details are manual or fetched .

Here is the screenshot how is it being reflected in the DB

Screenshot 2023-06-15 at 11 39 16 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49327)

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger ut1

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger ut9

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49327)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultConfigUpdateDTO.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/49327#-NYMHzLq72tg_TDgymaa:-NYMHzLq72tg_TDgymab:bdm5a1u) ([raw file](https://github.com/harness/harness-core/blob/0298c28d9165d032059d288e8e818b14705c7ca7/940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultConfigUpdateDTO.java#L41)):*
> ```Java
>   private String subscription;
>   private boolean isDefault;
>   private boolean vaultConfiguredManually;
> ```

This should not be needed. The flow where it is being used is deprecated and no longer in use.

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 3 of 9 files at r1, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49327)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqAt0I0zHBo4RrFc44:-NYqAt0I0zHBo4RrFc45:b-sez0fd) ([raw file](https://github.com/harness/harness-core/blob/75984a0c5450dfefa4df61ce876d79889d1dd256/931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java#L42)):*
> ```Java
>             .delegateSelectors(azureKeyVaultConfigDTO.getDelegateSelectors())
>             .useManagedIdentity(azureKeyVaultConfigDTO.getUseManagedIdentity())
>             .vaultConfiguredManually(azureKeyVaultConfigDTO.getVaultConfiguredManually())
> ```

Which flow uses this? Is this used in NG flow?
___
*[`931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java` line 173 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqAzC42aJ1l_GxCBO4:-NYqAzC42aJ1l_GxCBO5:b-sez0fd) ([raw file](https://github.com/harness/harness-core/blob/75984a0c5450dfefa4df61ce876d79889d1dd256/931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java#L173)):*
> ```Java
>                                                           .useManagedIdentity(getUseManagedIdentity())
>                                                           .managedClientId(getManagedClientId())
>                                                           .vaultConfiguredManually(getVaultConfiguredManually())
> ```

Which flow uses this? Is this used in NG flow?
___
*[`940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultMetadataRequestSpecDTO.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqBKDE3cTudeUyhE9o:-NYqBKDE3cTudeUyhE9p:brhun0a) ([raw file](https://github.com/harness/harness-core/blob/75984a0c5450dfefa4df61ce876d79889d1dd256/940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultMetadataRequestSpecDTO.java#L42)):*
> ```Java
>   private AzureManagedIdentityType azureManagedIdentityType;
>   private String managedClientId;
>   private Boolean vaultConfiguredManually;
> ```

Same here?

**Comment by adiyaar24** [comment]
*[`931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqAt0I0zHBo4RrFc44:-NYqb1PZ4oG1WSl2P_K0:bqvn1m3) ([raw file](https://github.com/harness/harness-core/blob/1a89c93e22966a5fe6d076a0a42412a1f2393a53/931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Which flow uses this? Is this used in NG flow?
</blockquote></details>

Yes this is used in NG Flow

**Comment by adiyaar24** [comment]
*[`940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultMetadataRequestSpecDTO.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqBKDE3cTudeUyhE9o:-NYqhcf9EuzwDNb5tX5I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a89c93e22966a5fe6d076a0a42412a1f2393a53/940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultMetadataRequestSpecDTO.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Same here?
</blockquote></details>

Done.

**Comment by adiyaar24** [comment]
trigger uts

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49327)* status: 13 file(s) to review. 1 of 2 approvals obtained. 

___
*[`931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqAt0I0zHBo4RrFc44:-NYqziry1eq2XUdia7lG:b-b3cdjb) ([raw file](https://github.com/harness/harness-core/blob/1a89c93e22966a5fe6d076a0a42412a1f2393a53/931-secret-providers/src/java/io/harness/mappers/AzureKeyVaultConfigMapper.java#L42)):*
<details><summary><i>Previously, adiyaar24 (Aditya Kashyap) wrote…</i></summary><blockquote>

Yes this is used in NG Flow
</blockquote></details>

As discussed it is not used.
___
*[`931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java` line 173 at r5](https://reviewable.io/reviews/harness/harness-core/49327#-NYqAzC42aJ1l_GxCBO4:-NYqzqKO0WW-qsN2sIuG:biul490) ([raw file](https://github.com/harness/harness-core/blob/1a89c93e22966a5fe6d076a0a42412a1f2393a53/931-secret-providers/src/java/software/wings/beans/AzureVaultConfig.java#L173)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Which flow uses this? Is this used in NG flow?
</blockquote></details>

As discussed, this is not required.
___
*[`940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultConfigUpdateDTO.java` line 41 at r4](https://reviewable.io/reviews/harness/harness-core/49327#-NYMHzLq72tg_TDgymaa:-NYr-3Wl32ZtcvJkjh2E:bj78y06) ([raw file](https://github.com/harness/harness-core/blob/0298c28d9165d032059d288e8e818b14705c7ca7/940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/azurekeyvault/AzureKeyVaultConfigUpdateDTO.java#L41)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This should not be needed. The flow where it is being used is deprecated and no longer in use. 
</blockquote></details>

As discussed. This is not required.

**Comment by adiyaar24** [comment]
trigger ss

**Pull request merged**
