### PR TITLE
feat: [CDS-53754]: Sync step implementation - polling and after

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
Sync step implementation - polling and after polling. Will add unit tests after this is merged.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Review by meenaravichandran1 — COMMENTED** [review]
I just realized that I need to add checks for service and environment. Will add it tomorrow. Please review the rest of the flow.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140#-:-NQY9UmIBJ85dIigNyOQ:b-duxq1t)* status: 17 file(s) to review. 0 of 2 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 17 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQ_QSCT0_CN-J8h5VYf:-NQ_QSCT0_CN-J8h5VYg:b-9fkvwy) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L230)):*
> ```Java
>     saveExecutionLog(format("Sync failed for applications %s", applicationsFailedToSync), logger);
>     log.info("Sync is still running for applications {}", syncStillRunningForApplications);
>     saveExecutionLog(format("Sync is still running for applications %s", syncStillRunningForApplications), logger);
> ```

Will change these to constants

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 274 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQ_ls7l0EszwUMrbrya:-NQ_wpcRBGIJK5wU6dQK:b-q7d12u) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L274)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

instead of getting current time again, we can work on the duration. Idk what's the performance impact of hitting System.currentTimeMillis repeatedly.
</blockquote></details>

AFAIK, System.currentTimeMillis() is based on the system clock, which is based on a quartz clock inside the server. Will read more on this.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-core-clients/src/main/java/io/harness/gitops/models/ApplicationResource.java` line 175 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQ_l_e57EZWfIJNc9w7:-NQbomGk396h6yIOJVCx:b-tkku0f) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/930-ng-core-clients/src/main/java/io/harness/gitops/models/ApplicationResource.java#L175)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, StringUtils.emptyifNull
</blockquote></details>

here the null check is for operation state, but the string returned from the method is operationState.message

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQYTNzk6N4a5uEC2mvo:-NQbpBjR5naO2vVkwXnX:b2nhysk) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L128)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

do we need this start time log for customer?
</blockquote></details>

ack
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQYTh-k6Pj0KF-XUvut:-NQbpAWqClUwfnZrgZWR:b2nhysk) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L132)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

log&UILog(saveExecutionLog) can be abstracted. 
</blockquote></details>

ack
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 294 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQ_mDhQ45kfy3CJa5_r:-NQbp9J63afOfRWN_Whe:b2nhysk) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L294)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

put these conditions into a method named : isAppSuccessfullySynced or similar.
</blockquote></details>

ack

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 128 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQYTNzk6N4a5uEC2mvo:-NQbxQlWAB0qryfPRcBr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L128)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

ack
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQYTh-k6Pj0KF-XUvut:-NQbxfwb7eEw9LgkwjH-:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L132)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

ack
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java` line 294 at r4](https://reviewable.io/reviews/harness/harness-core/45140#-NQ_mDhQ45kfy3CJa5_r:-NQbxi3a1TGrpX2P2j_h:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a225f76a7101cdb3c4bae676306c60d7f784c8f3/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/syncstep/SyncStep.java#L294)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

ack
</blockquote></details>

done

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 6 of 17 files at r1, 5 of 6 files at r2, 5 of 6 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: Some of the checks are too old. 18 file(s) to review.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 6 of 17 files at r1, 5 of 6 files at r2, 5 of 6 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: Some of the checks are too old.

**Review by meenaravichandran1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 1 file(s) to review.

**Review by meenaravichandran1 — COMMENTED** [review]
> Reviewed 6 of 17 files at r1, 5 of 6 files at r2, 4 of 6 files at r3, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 1 file(s) to review.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 1 file(s) to review.

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: 1 file(s) to review.

**Review by anshul-harness — APPROVED** [review]

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45140)* status: :shipit: complete! ✓

**Pull request merged**
