### PR TITLE
[feat]: [PL-28065]: Avoid excessive retries when making inter-service and mongodb calls

### PR DESCRIPTION
**Pull request by ankit-harness**
## Describe your changes

Change the retry logic for MongoDB call and inter-service HTTP calls so that retries happen only if exception is retryable with exponential backoff. Earlier we were retrying on all exceptions

1. In case of MongoDB, retry would happen only if exception thrown is transient (TransactionException, TransientDataAccessException and MongoException of transient kind)
2. In case of interservice HTTP calls, retries would happen only if there is network issue (IOException) or HTTP status code is 408, 502, 503, 504

This logic is in PersistenceUtils, NGRestUtils, CGRestUtils.

We have changed most of the code to use these classes instead of defining and using the retry policies in individual classes. This will bring some standardisation. We have left few places in the code where we have not redirected the calls to use these common functions. Reason is we couldn't figure out the reason of retries at those places. Those places are module specific and can be taken care of by module teams

Most important classes to review
1. PersistenceUtils
2. NGRestUtils
3. CGRestUtils
4. PipelineRbacHelper
5. TimescaleDBServiceImpl
6. RemoteSchemaGetter

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 5 Issues 
* Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37395)

**Comment by ankit-harness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 24 files at r1, 3 of 63 files at r2, 10 of 91 files at r3, 1 of 1 files at r5, 2 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: 155 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzjyj-7kATVtdoLvFQ:-NBzjyj-7kATVtdoLvFR:b2o9cfl) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/878-ng-common-utilities/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java#L30)):*
> ```Java
>   public boolean isEnabled(String accountId, FeatureName featureName) {
>     try {
>       return CGRestUtils.getResponse(accountClient.isFeatureFlagEnabled(featureName.name(), accountId), ERROR_MESSAGE);
> ```

Can we use NGRestUtils?



_Code quote:_
```Java
CGRestUtils
```
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkHrd-AqsyZil1pjV:-NBzkHrd-AqsyZil1pjW:b-p9e7g8) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L31)):*
> ```Java
> 
>   public String getBaseUrl(String accountIdentifier) {
>     return CGRestUtils.getResponse(accountClient.getBaseUrl(accountIdentifier));
> ```

Can we use NGResultUtils? and RestClientUtils have similar impl, not sure why duplicate code exists



_Code quote:_
```Java
CGRestUtils
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/pms/helpers/PmsFeatureFlagHelper.java` line 68 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkTTkAgsfEGVzDkQH:-NBzkTTkAgsfEGVzDkQI:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/modules/orchestration/src/main/java/io/harness/pms/helpers/PmsFeatureFlagHelper.java#L68)):*
> ```Java
> 
>   private Set<String> listAllEnabledFeatureFlagsForAccount(String accountId) {
>     return CGRestUtils.getResponse(accountClient.listAllFeatureFlagsForAccount(accountId))
> ```

NGRestUtils



_Code quote:_
```Java
CGRestUti
```
___
*[`pipeline-service/service/src/main/java/io/harness/metrics/PipelineTelemetryPublisher.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkwTV6iSGP8iAS-Oy:-NBzkwTV6iSGP8iAS-Oz:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/service/src/main/java/io/harness/metrics/PipelineTelemetryPublisher.java#L92)):*
> ```Java
>   @VisibleForTesting
>   String getAccountId() {
>     List<AccountDTO> accountDTOList = CGRestUtils.getResponse(accountClient.getAllAccounts());
> ```

NGRestUtils



_Code quote:_
```Java
CGRestUtils
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java` line 106 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkyDn1rUnF4Ara0dk:-NBzkyDn1rUnF4Ara0dl:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java#L106)):*
> ```Java
> 
>     String userId = principal.getName();
>     Optional<UserInfo> userOptional = CGRestUtils.getResponse(userClient.getUserById(userId));
> ```

NGRestUtils
___
*[`pipeline-service/service/src/main/java/io/harness/pms/helpers/PipelineExpressionHelper.java` line 104 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzl-MW60ByUVs7b4hu:-NBzl-MW60ByUVs7b4hv:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/service/src/main/java/io/harness/pms/helpers/PipelineExpressionHelper.java#L104)):*
> ```Java
> 
>   private String getVanityUrl(String accountIdentifier) {
>     return CGRestUtils.getResponse(accountClient.getVanityUrl(accountIdentifier));
> ```

NGRestUtils
___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PMSTriggerMigration.java` line 50 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzuZH54V7E-8zi8y1o:-NBzuZH54V7E-8zi8y1p:borjq8f) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/pipeline-service/service/src/main/java/io/harness/pms/migration/PMSTriggerMigration.java#L50)):*
> ```Java
>   @Inject private final MongoTemplate mongoTemplate;
>   @Inject private NGTriggerElementMapper ngTriggerElementMapper;
>   private final RetryPolicy<Object> updateRetryPolicy = PersistenceUtils.getRetryPolicy(
> ```

Does optimisticLocking comes under if (ex instanceof MongoException) {
            return ((MongoException) ex).hasErrorLabel(MongoException.TRANSIENT_TRANSACTION_ERROR_LABEL);

I am not sure why duplicate key they are retrying doesn't make sense
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/RemoteSchemaGetter.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzuvJaDdHl4THdRCA3:-NBzuvJaDdHl4THdRCA4:boq4ukm) ([raw file](https://github.com/harness/harness-core/blob/5a6effd196b0b0b2eb3d20b408f803de0c781241/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/RemoteSchemaGetter.java#L63)):*
> ```Java
>         format("[PMS] Error while calling %s service", moduleType.name()), ImmutableList.of(Exception.class),
>         Duration.ofMillis(600), 3, log);
>   }
> ```

nit: @sahilhindwani-harness we were doing retry on all exceptions which I don't think makes sense, let go without retry for now and see what issues we face, any particular error you think needs to be retried let me know



_Code quote:_
```Java
  private RetryPolicy<Object> getRetryPolicy(ModuleType moduleType) {
    return RetryUtils.getRetryPolicy(format("[PMS] [Retrying] Error while calling %s service", moduleType.name()),
        format("[PMS] Error while calling %s service", moduleType.name()), ImmutableList.of(Exception.class),
        Duration.ofMillis(600), 3, log);
  }
```
___
*[`pipeline-service/service/src/test/java/io/harness/metrics/PipelineTelemetryPublisherTest.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzvAm2BoAgA0h5Wlkf:-NBzvAm2BoAgA0h5Wlkg:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/pipeline-service/service/src/test/java/io/harness/metrics/PipelineTelemetryPublisherTest.java#L98)):*
> ```Java
> 
>     try (MockedStatic<CGRestUtils> mockStatic = Mockito.mockStatic(CGRestUtils.class)) {
>       mockStatic.when(() -> CGRestUtils.getResponse(requestCall)).thenReturn(accounts);
> ```

NGRestUtils
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 64 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzvTe2230CNH-PlRFe:-NBzvTe2230CNH-PlRFf:bftlz2o) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L64)):*
> ```Java
>   private final TransactionTemplate transactionTemplate;
> 
>   private final RetryPolicy<Object> transactionRetryPolicy = DEFAULT_RETRY_POLICY;
> ```

Have we confirmed that MongoTransactionException and UncategorizedMongoDbException has retry error label

**Comment by rathodmeetsatish** [comment]
> > Reviewed 3 of 24 files at r1, 3 of 63 files at r2, 10 of 91 files at r3, 1 of 1 files at r5, 2 of 11 files at r6.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)_ status: 155 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto.
> 
> _[`878-ng-common-utilities/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzjyj-7kATVtdoLvFQ:-NBzjyj-7kATVtdoLvFR:b2o9cfl) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/878-ng-common-utilities/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java#L30)):_
> 
> > ```java
> >   public boolean isEnabled(String accountId, FeatureName featureName) {
> >     try {
> >       return CGRestUtils.getResponse(accountClient.isFeatureFlagEnabled(featureName.name(), accountId), ERROR_MESSAGE);
> > ```
> 
> Can we use NGRestUtils?
> 
> _Code quote:_
> 
> ```java
> CGRestUtils
> ```
> 
> _[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkHrd-AqsyZil1pjV:-NBzkHrd-AqsyZil1pjW:b-p9e7g8) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L31)):_
> 
> > ```java
> >   public String getBaseUrl(String accountIdentifier) {
> >     return CGRestUtils.getResponse(accountClient.getBaseUrl(accountIdentifier));
> > ```
> 
> Can we use NGResultUtils? and RestClientUtils have similar impl, not sure why duplicate code exists
> 
> _Code quote:_
> 
> ```java
> CGRestUtils
> ```
> 
> _[`pipeline-service/modules/orchestration/src/main/java/io/harness/pms/helpers/PmsFeatureFlagHelper.java` line 68 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkTTkAgsfEGVzDkQH:-NBzkTTkAgsfEGVzDkQI:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/modules/orchestration/src/main/java/io/harness/pms/helpers/PmsFeatureFlagHelper.java#L68)):_
> 
> > ```java
> >   private Set<String> listAllEnabledFeatureFlagsForAccount(String accountId) {
> >     return CGRestUtils.getResponse(accountClient.listAllFeatureFlagsForAccount(accountId))
> > ```
> 
> NGRestUtils
> 
> _Code quote:_
> 
> ```java
> CGRestUti
> ```
> 
> _[`pipeline-service/service/src/main/java/io/harness/metrics/PipelineTelemetryPublisher.java` line 92 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkwTV6iSGP8iAS-Oy:-NBzkwTV6iSGP8iAS-Oz:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/service/src/main/java/io/harness/metrics/PipelineTelemetryPublisher.java#L92)):_
> 
> > ```java
> >   @VisibleForTesting
> >   String getAccountId() {
> >     List<AccountDTO> accountDTOList = CGRestUtils.getResponse(accountClient.getAllAccounts());
> > ```
> 
> NGRestUtils
> 
> _Code quote:_
> 
> ```java
> CGRestUtils
> ```
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java` line 106 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzkyDn1rUnF4Ara0dk:-NBzkyDn1rUnF4Ara0dl:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java#L106)):_
> 
> > ```java
> >     String userId = principal.getName();
> >     Optional<UserInfo> userOptional = CGRestUtils.getResponse(userClient.getUserById(userId));
> > ```
> 
> NGRestUtils
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/helpers/PipelineExpressionHelper.java` line 104 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzl-MW60ByUVs7b4hu:-NBzl-MW60ByUVs7b4hv:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/pipeline-service/service/src/main/java/io/harness/pms/helpers/PipelineExpressionHelper.java#L104)):_
> 
> > ```java
> >   private String getVanityUrl(String accountIdentifier) {
> >     return CGRestUtils.getResponse(accountClient.getVanityUrl(accountIdentifier));
> > ```
> 
> NGRestUtils
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/migration/PMSTriggerMigration.java` line 50 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzuZH54V7E-8zi8y1o:-NBzuZH54V7E-8zi8y1p:borjq8f) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/pipeline-service/service/src/main/java/io/harness/pms/migration/PMSTriggerMigration.java#L50)):_
> 
> > ```java
> >   @Inject private final MongoTemplate mongoTemplate;
> >   @Inject private NGTriggerElementMapper ngTriggerElementMapper;
> >   private final RetryPolicy<Object> updateRetryPolicy = PersistenceUtils.getRetryPolicy(
> > ```
> 
> Does optimisticLocking comes under if (ex instanceof MongoException) { return ((MongoException) ex).hasErrorLabel(MongoException.TRANSIENT_TRANSACTION_ERROR_LABEL);
> 
> I am not sure why duplicate key they are retrying doesn't make sense
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/RemoteSchemaGetter.java` line 63 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzuvJaDdHl4THdRCA3:-NBzuvJaDdHl4THdRCA4:boq4ukm) ([raw file](https://github.com/harness/harness-core/blob/5a6effd196b0b0b2eb3d20b408f803de0c781241/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/RemoteSchemaGetter.java#L63)):_
> 
> > ```java
> >         format("[PMS] Error while calling %s service", moduleType.name()), ImmutableList.of(Exception.class),
> >         Duration.ofMillis(600), 3, log);
> >   }
> > ```
> 
> nit: @sahilhindwani-harness we were doing retry on all exceptions which I don't think makes sense, let go without retry for now and see what issues we face, any particular error you think needs to be retried let me know
> 
> _Code quote:_
> 
> ```java
>   private RetryPolicy<Object> getRetryPolicy(ModuleType moduleType) {
>     return RetryUtils.getRetryPolicy(format("[PMS] [Retrying] Error while calling %s service", moduleType.name()),
>         format("[PMS] Error while calling %s service", moduleType.name()), ImmutableList.of(Exception.class),
>         Duration.ofMillis(600), 3, log);
>   }
> ```
> 
> _[`pipeline-service/service/src/test/java/io/harness/metrics/PipelineTelemetryPublisherTest.java` line 98 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzvAm2BoAgA0h5Wlkf:-NBzvAm2BoAgA0h5Wlkg:b-94kn8h) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/pipeline-service/service/src/test/java/io/harness/metrics/PipelineTelemetryPublisherTest.java#L98)):_
> 
> > ```java
> >     try (MockedStatic<CGRestUtils> mockStatic = Mockito.mockStatic(CGRestUtils.class)) {
> >       mockStatic.when(() -> CGRestUtils.getResponse(requestCall)).thenReturn(accounts);
> > ```
> 
> NGRestUtils
> 
> _[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 64 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzvTe2230CNH-PlRFe:-NBzvTe2230CNH-PlRFf:bftlz2o) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L64)):_
> 
> > ```java
> >   private final TransactionTemplate transactionTemplate;
> > 
> >   private final RetryPolicy<Object> transactionRetryPolicy = DEFAULT_RETRY_POLICY;
> > ```
> 
> Have we confirmed that MongoTransactionException and UncategorizedMongoDbException has retry error label
For AccountClient methods return type is Call<RestResponse<T>> so we will have to use CGRestUtils

**Comment by rathodmeetsatish** [comment]
@archit-harness For AccountClient methods return type is Call<RestResponse> so we will have to use CGRestUtils

**Review by ankit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: 155 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PMSTriggerMigration.java` line 50 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzuZH54V7E-8zi8y1o:-NC-0RKY6d0JX8AsjvVu:b6gtz00) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/pipeline-service/service/src/main/java/io/harness/pms/migration/PMSTriggerMigration.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Does optimisticLocking comes under if (ex instanceof MongoException) {
            return ((MongoException) ex).hasErrorLabel(MongoException.TRANSIENT_TRANSACTION_ERROR_LABEL);

I am not sure why duplicate key they are retrying doesn't make sense
</blockquote></details>

OptimisticLockingException extends from TransientDataAccessException
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java` line 64 at r7](https://reviewable.io/reviews/harness/harness-core/37395#-NBzvTe2230CNH-PlRFe:-NC-3E7G6uuhwmQkA0_f:b-4h567l) ([raw file](https://github.com/harness/harness-core/blob/e07cb2f68b4a84e7dadf446598cf8e0cdf11c765/platform-service/modules/audit-service/src/main/java/io/harness/audit/api/impl/AuditServiceImpl.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Have we confirmed that MongoTransactionException and UncategorizedMongoDbException has retry error label
</blockquote></details>

Both of them extends NonTransientDataAccessException so basically non-transient and should not be retried

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 13 of 24 files at r1, 46 of 63 files at r2, 81 of 91 files at r3, 1 of 1 files at r5, 10 of 11 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: 136 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 6 of 7 files at r9, 2 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: 144 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r9, 1 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: 137 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java` line 30 at r6](https://reviewable.io/reviews/harness/harness-core/37395#-NBzjyj-7kATVtdoLvFQ:-NCJxsij04rc0mOcuJPR:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/d704e410caf5c7fe9a8afb7ef7830f198ac045ad/878-ng-common-utilities/src/main/java/io/harness/utils/NGFeatureFlagHelperService.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we use NGRestUtils?
</blockquote></details>

done, discussed offline

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 12 of 24 files at r1, 41 of 63 files at r2, 77 of 91 files at r3, 1 of 1 files at r5, 9 of 11 files at r6, 1 of 3 files at r7, 7 of 7 files at r9, 11 of 13 files at r11, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: 14 file(s) to review. Waiting on team(s): sto.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 12 of 63 files at r2, 4 of 91 files at r3, 6 of 11 files at r6, 1 of 13 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395#-:-NCKopgPAyzVCc4fR5wP:bnfp4nl)* status: 13 file(s) to review. Waiting on team(s): sto.

**Review by r0610205 — APPROVED** [review]

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 12 of 24 files at r1, 41 of 63 files at r2, 77 of 91 files at r3, 1 of 1 files at r5, 9 of 11 files at r6, 1 of 3 files at r7, 7 of 7 files at r9, 11 of 13 files at r11, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 12 of 24 files at r1, 41 of 63 files at r2, 77 of 91 files at r3, 1 of 1 files at r5, 9 of 11 files at r6, 1 of 3 files at r7, 7 of 7 files at r9, 11 of 13 files at r11, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37395)* status: :shipit: complete! ✓

**Pull request merged**
