### PR TITLE
feat: [CDS-82742]: API to fetch the V1 Runtime Inputs Schema for Template

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
API to fetch the V1 Runtime Inputs Schema for Template - 
* API to fetch runtime inputs from given YAML
* API for fetch runtime inputs from project level template
* API for fetch runtime inputs from project level template
* API for fetch runtime inputs from project level template

Tests - 
1). 
for this body - 
```
{
    "template_yaml": "version: 1\nkind: template\nspec:\n  type: pipeline\n  spec:\n    stages:\n      - type: custom\n        name: s1\n        spec:\n          steps:\n            - type: JenkinsBuild\n              name: JenkinsBuild_1\n              identifier: JenkinsBuild_1\n              spec:\n                connectorRef: <+inputs.connectorRef>\n                consoleLogPollFrequency: 5s\n                jobName: <+inputs.jobName>\n                jobParameter: []\n                unstableStatusAsSuccess: false\n                useConnectorUrlForJobExecution: false\n              timeout: 1m\n  inputs:\n    connectorRef:\n      type: string\n      required: true\n    jobName:\n      type: string\n      required: true\n"
}
``` 

This is Output - 
```
{
    "inputs": [
        {
            "details": {
                "name": "connectorRef",
                "type": "String",
                "description": null,
                "required": true,
                "allowed_values": [],
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "jobName",
                "type": "String",
                "description": null,
                "required": true,
                "allowed_values": [],
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        }
    ]
}
``` 

2). Similarly tested for Acc/Org/Project level templates 
```
http://localhost:15001/api/v1/orgs/default/templates/stagtemp3/versions/v1/inputs-schema
http://localhost:15001/api/v1/orgs/default/projects/fdsf/templates/stagtemp1/versions/v1/inputs-schema
``` 

Output same as above

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
We need pass org_id, project_id as query param here, as want to use schema Tag and we are passing the yaml against which we are fetching inputs schema ( For fetching inputs-schema via template identifier we have created 3 diff apis similar to the convention )
Discussed the soln with @mankrit-singh

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 204 at r1](https://reviewable.io/reviews/harness/harness-core/54754#-Ni0HzRT8gH4wMLIBzzb:-Ni0HzRT8gH4wMLIBzzc:b-lmbkcs) ([raw file](https://github.com/harness/harness-core/blob/02f0a8e47c084e28f8a504088b2f5c01b07a7997/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L204)):*
> ```Java
>   }
> 
>   private static List<InputDetailsPerFieldDTO> toInputDetailsPerFieldDTOList(
> ```

These same method already exists in the `PipelinesApiUtils`. You can move these methods into the common layer and reuse them.

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/54754#-Ni0I9MC59AdGGv3irsG:-Ni0I9MC59AdGGv3irsH:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/02f0a8e47c084e28f8a504088b2f5c01b07a7997/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L218)):*
> ```Java
>   }
> 
>   private static YamlInputDependencyDetailsDTO toYamlInputDependencyDetailsDTO(DependencyDetails dependencyDetails) {
> ```

same as above

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 249 at r1](https://reviewable.io/reviews/harness/harness-core/54754#-Ni0IAsU9ymPYFDO9yW_:-Ni0IAsU9ymPYFDO9yWa:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/02f0a8e47c084e28f8a504088b2f5c01b07a7997/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L249)):*
> ```Java
>   }
> 
>   private static YamlInputType getYamlInputType(SchemaInputType schemaInputType) {
> ```

same as above

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: 11 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/54754#-Ni0I9MC59AdGGv3irsG:-Ni3Bgz_COhT6u2XdXQr:bgwlc78) ([raw file](https://github.com/harness/harness-core/blob/02f0a8e47c084e28f8a504088b2f5c01b07a7997/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L218)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Both are different DTOs, as those DTOs are autogenerated from the openApi.yaml file, therefore some methods needs to be duplicated 
___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/54754#-Ni0G22nByrf9jNMDFiA:-Ni3BgTe0LM09YxhK1E1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02f0a8e47c084e28f8a504088b2f5c01b07a7997/template-service/service/src/main/java/io/harness/yaml/individualschema/BaseTemplateSchemaParser.java#L53)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

use YAMLFieldNameConstants for steps and stages.
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: 11 file(s) to review.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: :shipit: complete! ✓

___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/54754#-Ni0I9MC59AdGGv3irsG:-NiEUNGs8m6IxC6_x53-:bhlggxa) ([raw file](https://github.com/harness/harness-core/blob/02f0a8e47c084e28f8a504088b2f5c01b07a7997/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L218)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Both are different DTOs, as those DTOs are autogenerated from the openApi.yaml file, therefore some methods needs to be duplicated
</blockquote></details>

@utkarshchoubey-harness can we somehow share this openapi in both pipeline and template to make these dtos same?
___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUWcH9-bAe_nimOKm:-NiEUWcH9-bAe_nimOKn:b-u8jlnt) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L365)):*
> ```Java
>         Resource.of(TEMPLATE, templateIdentifier), PermissionTypes.TEMPLATE_VIEW_PERMISSION);
>     Optional<TemplateEntity> templateEntity =
>         templateService.get(account, org, project, templateIdentifier, versionLabel, false, false);
> ```

why we are introducing db get etc in util class? cant this method be called via a service?
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUfvDDfTvag_nUlvR:-NiEUfvDDfTvag_nUlvS:bnjt4rc) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L196)):*
> ```Java
> 
>   private SchemaParserInterface getStaticSchemaParser(YamlConfig yamlConfig) {
>     if (yamlConfig.getYamlMap().get("template") != null) {
> ```

same as below
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUe9i8r_Cjjgjs9L7:-NiEUe9i8r_Cjjgjs9L8:b-elpeai) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L200)):*
> ```Java
>     }
> 
>     JsonNode versionNode = yamlConfig.getYamlMap().get("version");
> ```

why we are not using const?
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUiECCi6wft0lDggL:-NiEUiECCi6wft0lDggM:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L203)):*
> ```Java
>     if (versionNode != null) {
>       switch (versionNode.asText()) {
>         case "1":
> ```

same for this

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUfvDDfTvag_nUlvR:-NiYI7B246uAdfL7RtqS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L196)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as below
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUe9i8r_Cjjgjs9L7:-NiYI7ZyD4vH4wLpqVPw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L200)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are not using const?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 203 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUiECCi6wft0lDggL:-NiYI7wP4iYJbujz2oem:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L203)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same for this
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/54754#-NiEUWcH9-bAe_nimOKm:-NiYI6cP7XtyOMF6hM2P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e357a685917b9132a02f04355285084b37ca63a5/template-service/service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java#L365)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are introducing db get etc in util class? cant this method be called via a service?
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Review by archit-harness — COMMENTED** [review]
> Reviewed 9 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 10 of 10 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger ut1, ut3, ut5

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Review by naidu-harness — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by mankrit-singh — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54754)* status: 1 file(s) to review.

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Comment by utkarshchoubey-harness** [comment]
All the Uts passed, not sure why it is showing as failed

**Pull request merged**
