### PR TITLE
feat: [CDS-44143]: Implement batch undelete api

### PR DESCRIPTION
**Pull request by rohitk-h**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38308)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38308)

**Comment by rohitk-h** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 263 at r1](https://reviewable.io/reviews/harness/harness-core/38308#-NDWJtJ7CCIlbufJL_sU:-NDWJtJ7CCIlbufJL_sV:bloxb6k) ([raw file](https://github.com/harness/harness-core/blob/eb1acb0cb99d534db182fa332554ca241f2d638d/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L263)):*
> ```Java
>           request.getProjectIdentifier(), request.getEnvRef(), accountLevelClusters.getContent()));
>       entities.addAll(ClusterEntityMapper.toEntities(accountId, request.getOrgIdentifier(),
>           request.getProjectIdentifier(), request.getEnvRef(), projectLevelClusters.getContent()));
> ```

when unlinking all clusters, we only need to delete the cluster records from ng-manager DB. There is no need to call the gitops service in this case
just delete all clusters with the same accountid, orgId, projectId, envId

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 237 at r1](https://reviewable.io/reviews/harness/harness-core/38308#-NDWJelJBv3zXExBz0Jw:-NDWJelJBv3zXExBz0Jx:b1ije44) ([raw file](https://github.com/harness/harness-core/blob/eb1acb0cb99d534db182fa332554ca241f2d638d/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L237)):*
> ```Java
>   unlinkBatch(@Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @NotNull @QueryParam(
>                   NGCommonEntityConstants.ACCOUNT_KEY) String accountId,
>       @Parameter(description = "Details of the createCluster to be created") @Valid ClusterBatchRequest request) {
> ```

It might be better to have different DTOs for link and unlink so fields do not overlap between them ( linkAll vs unlinkAll )

**Comment by rohitk-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 237 at r1](https://reviewable.io/reviews/harness/harness-core/38308#-NDWJelJBv3zXExBz0Jw:-NDWMU7V8fAuwV1m7--0:b-7hvfn1) ([raw file](https://github.com/harness/harness-core/blob/eb1acb0cb99d534db182fa332554ca241f2d638d/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L237)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

It might be better to have different DTOs for link and unlink so fields do not overlap between them ( linkAll vs unlinkAll )
</blockquote></details>

I did think to do with different DTO's but since it is just one field I didn't create one. Users will also would need to define one more additional DTO in their automation.

**Comment by rohitk-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 263 at r1](https://reviewable.io/reviews/harness/harness-core/38308#-NDWJtJ7CCIlbufJL_sU:-NDWakBi4fq-n0MJ6gf0:b-ohtjjy) ([raw file](https://github.com/harness/harness-core/blob/eb1acb0cb99d534db182fa332554ca241f2d638d/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L263)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

when unlinking all clusters, we only need to delete the cluster records from ng-manager DB. There is no need to call the gitops service in this case
just delete all clusters with the same accountid, orgId, projectId, envId 
</blockquote></details>

make sense, will update

**Comment by rohitk-h** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38308)* status: :shipit: complete! ✓

**Pull request merged**
