### PR TITLE
fix: [CDS-43600]: WinRM remote PS execution 15+ second delays after c…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…onnection before script(s) begin execution. Executing command with powershell -encodedCommand

## Describe your changes
With the new implementation we have 4 steps:

1. Copying encoded script into separate file on remote
2. Decode on remote and create new file with the script content
3. Creating Executable file which reads and decodes upper one
4. Execute file from step 3

Test plan executed: https://docs.google.com/spreadsheets/d/1d6mp1_APzZ8pmNLSZaMFmeXHPahXU6AHuXlmMNKOMGc/edit#gid=1321123544

Screenshot of initial Schwab issue:
image

Executable file content:
```
try{
	$encoded = get-content C:\Users\cdp_admin/bojan/\harness-encoded-BhFe992DRxi8k9fD1DPNoA
	$decoded = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($encoded));
	Set-Content -Path C:\Users\cdp_admin/bojan/\harness-executable-BhFe992DRxi8k9fD1DPNoA.ps1 -Value $decoded -Encoding Unicode
	Invoke-Expression -Command C:\Users\cdp_admin/bojan/\harness-executable-BhFe992DRxi8k9fD1DPNoA.ps1
}
catch
{
	Write-Error $_;
	exit 1
}
finally
{
	if (Test-Path C:\Users\cdp_admin/bojan/\harness-executable-BhFe992DRxi8k9fD1DPNoA.ps1) {Remove-Item -Force -Path C:\Users\cdp_admin/bojan/\harness-executable-BhFe992DRxi8k9fD1DPNoA.ps1}
	if (Test-Path C:\Users\cdp_admin/bojan/\harness-encoded-BhFe992DRxi8k9fD1DPNoA) {Remove-Item -Force -Path C:\Users\cdp_admin/bojan/\harness-encoded-BhFe992DRxi8k9fD1DPNoA
}
```

We need this exception handling because child process Invoke-Expression -Command "file-path"  doesn’t propagate exit code.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40378#-NHAWalT5eR-lKyynEUG:-NHAWalUBWy5QMY-J5Jz:b-9hy8re) (no related file):*
@bojanmicovic if we copy a config file with WinRm that has | or any other special characters, is it going to work - or we need to accommodate the same fix?



_Code quote (from 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java):_
```Java
https://github.com/PowerShell/PowerShell/issues/5912
```

___
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/40378#-NHAZ1BB3mworA3-rLJZ:-NHAZ1BB3mworA3-rLJ_:bo99o7) ([raw file](https://github.com/harness/harness-core/blob/e74e891860bb7c7dfc096e95fed9c0e96b87024a/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L23)):*
> ```Java
> import software.wings.beans.WinRmCommandParameter;
> 
> import com.google.api.client.util.Base64;
> ```

what is the preference on this encoder with java bundled one?



_Code quote:_
```Java
encodeBase64String
```

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/40378#-NHAZ1BB3mworA3-rLJZ:-NHxYd0l-eSxLBpz72U6:buiv2n5) ([raw file](https://github.com/harness/harness-core/blob/e74e891860bb7c7dfc096e95fed9c0e96b87024a/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L23)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what is the preference on this encoder with java bundled one?
</blockquote></details>

No preferences, just didn't pay attention. Changed it.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40378#-NHyXMj64k9rx-GqL-8m:-NHyXMj64k9rx-GqL-8n:b-17uuhv) (no related file):*
@bojanmicovic pls provide the description of the solution in the pr details and highlight the test cases being covered.

___

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 387 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2FpMr7rShi6AcJIfW:-NI2FpMr7rShi6AcJIfX:bn4w6pd) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L387)):*
> ```Java
>     }
> 
>     String executable = getExecutableFile(config.getWorkingDirectory(), config.getExecutionId());
> ```

Minor - rename, executable to executablePSFilePath or..
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 392 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2G8KhAnd6nyDEAiMA:-NI2G8KhAnd6nyDEAiMB:bhjwx2e) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L392)):*
> ```Java
>     exitCode = session.executeCommandString(psExecutionCommand, outputWriter, errorWriter, false);
>     if (exitCode != 0) {
>       log.error("Transferring execution script to PowerShell script file FAILED.");
> ```

Minor - this error msg is not clear to me, is it related to transferring psExecutionCommand to a remote machine or decoding execution on a remote machine?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2MU5a8PvaBu6pWEGW:-NI2MU5c6ylxXu5Cux0W:b3a2p6w) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L93)):*
> ```Java
>       String command, String encodedScriptFile, String powershell, List<WinRmCommandParameter> commandParameters) {
>     command = "$ErrorActionPreference='Stop'\n" + command;
>     String base64Command = encodeBase64(command.getBytes(StandardCharsets.UTF_16LE));
> ```

Not sure why we need UTF_16LE here, we are getting string from UI or remote location in most probably UTF-8 code format, not sure do we need UTF_16LE to encode it, but it should work, java will take care of it.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2HpDzChFGSbIrcQiQ:-NI2HpDzChFGSbIrcQiR:b-ic7s1) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmExecutorHelper.java#L97)):*
> ```Java
>     String commandParametersString = buildCommandParameters(commandParameters);
> 
>     List<List<Byte>> partitions = Lists.partition(Bytes.asList(base64Command.getBytes()), PARTITION_SIZE_IN_BYTES);
> ```

This is the key part, here  base64Command.getBytes() will return the list of bytes in the platform's default charset, I will proceed with base64Command.getBytes(UTF-8)
and be sure that one encoded character is 1 byte (https://en.wikipedia.org/wiki/Base64). The good thing is all encoded characters will fit into one byte and partitioning shouldn't break characters.

@bojanmicovic could you pls check what is the default charset for java 11 on Linux? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java` line 245 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2GknjCWjPkDKo27Gf:-NI2GknjCWjPkDKo27Gg:b-x66ba9) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java#L245)):*
> ```Java
>         // adding output format at the end because there is a bug in powershell 5.1 and bellow which is fixed in 6.1.
>         // https://github.com/PowerShell/PowerShell/issues/5912
>         WinRmToolResponse winRmToolResponse = winRmTool.executeCommand(scriptExecCommand + " -OutputFormat Text");
> ```

I guess the output format is ignored PS versions different than 5.1 and we will not get any errors. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java` line 315 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2HJjX8MJLuPwSsRvM:-NI2HJjYEjJhIvumJeHb:bkhuhpl) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java#L315)):*
> ```Java
>   }
> 
>   private void writeLogs(WinRmToolResponse winRmToolResponse, Writer output, Writer error) throws IOException {
> ```

Minor - this processing log logic could be moved to a separate class in the next PR.

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by bojanmicovic** [comment]
trigger ti3

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java` line 392 at r3](https://reviewable.io/reviews/harness/harness-core/40378#-NI2G8KhAnd6nyDEAiMA:-NI6pKg_DBf0e6dwNshm:bcdltpz) ([raw file](https://github.com/harness/harness-core/blob/25021ec940e9fbd82e347b4d229475ea3e755b1f/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/DefaultWinRmExecutor.java#L392)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - this error msg is not clear to me, is it related to transferring psExecutionCommand to a remote machine or decoding execution on a remote machine?
</blockquote></details>

We have two steps before executing:
1. Encode script and transfer it to the remote file
2. Execution script which should read file from previous step, decode it and execute.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378#-:-NI760ytA17o-UDW2jOI:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378)* status: 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40378#-:-NI96mVY0EzDtw7YseB1:bnfp4nl)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger smartchecks

**Comment by bojanmicovic** [comment]
trigger ti1,ti2,ti3,ti4,ft1,ft2

**Pull request merged**
