### PR TITLE
[feat]: [CDS-53694] Add entities for EKS Infrastructure

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Add entities for EKS Infrastructure 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)

### CODE REVIEW

**Review by markoharness — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/K8sAwsInfrastructure.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/44736#-NQAF_Nt0yrGNaMxkzBw:-NQAF_Nt0yrGNaMxkzBx:b-vbw516) ([raw file](https://github.com/harness/harness-core/blob/30cd5640c1a2f88c508e9ec0c439708ac77d2636/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/K8sAwsInfrastructure.java#L66)):*
> ```Java
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH)
>   @YamlSchemaTypes({expression})
>   @Pattern(regexp = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$")
> ```

can we extract this out into some constant ? and make sure its used by other k8s infra also

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 16 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)* status: :shipit: complete! ✓

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/K8sAwsInfrastructure.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/44736#-NQAF_Nt0yrGNaMxkzBw:-NQB5Oo_7AZ6TuspYEQ2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/30cd5640c1a2f88c508e9ec0c439708ac77d2636/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/K8sAwsInfrastructure.java#L66)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we extract this out into some constant ? and make sure its used by other k8s infra also 
</blockquote></details>

Done

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 18 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44736)* status: :shipit: complete! ✓

**Pull request merged**
