### PR TITLE
feat: [CDS-38396]: get serviceInputs API

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 439 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3XljBj3A18CPymtzpm:-N3XljBj3A18CPymtzpn:bl49ij1) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L439)):*
> ```Java
>     Map<String, Object> serviceInputs = new HashMap<>();
>     if (serviceEntity.isPresent()) {
>       if (EmptyPredicate.isEmpty(serviceEntity.get().getYaml())) {
> ```

this api is only going to be used by v2, so we should assume that yaml should be present else throw exception



_Code quote:_
```Java
if (EmptyPredicate.isEmpty(serviceEntity.get().getYaml())) {
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 476 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3Xm5hTDsgJ--sDIbFi:-N3Xm5hUBaKms-aicKD4:bsyd0ux) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L476)):*
> ```Java
>       throw new InvalidRequestException("Error occurred while creating service inputs ", e);
>     }
>   }
> ```

we should not keep this in resource layer, and put this in service layer



_Code quote:_
```Java
  @VisibleForTesting
  String createServiceInputsYaml(String yaml) {
    try {
      if (isEmpty(yaml)) {
        throw new InvalidRequestException("Service yaml to create inputs cannot be empty");
      }
      YamlField serviceYamlField = YamlUtils.readTree(yaml).getNode().getField(NGServiceConstants.SERVICE);
      if (serviceYamlField == null) {
        throw new InvalidRequestException("Yaml provided is not a service yaml.");
      }
      ObjectNode serviceNode = (ObjectNode) serviceYamlField.getNode().getCurrJsonNode();
      String serviceDefinition = serviceNode.retain(NGServiceConstants.SERVICE_DEFINITION).toString();
      if (isEmpty(serviceDefinition)) {
        throw new InvalidRequestException("Service yaml provided does not have service definition in it.");
      }
      String serviceDefinitionInputs = RuntimeInputFormHelper.createTemplateFromYaml(serviceDefinition);
      if (isEmpty(serviceDefinitionInputs)) {
        return serviceDefinitionInputs;
      }

      return serviceDefinitionInputs;
    } catch (IOException e) {
      throw new InvalidRequestException("Error occurred while creating service inputs ", e);
    }
  }
```
___
*[`970-ng-commons/src/main/java/io/harness/cd/NGServiceConstants.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3Xl_cw08P60H5fR065:-N3Xl_cx6HFD-6I9vuST:b-vyacgj) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/970-ng-commons/src/main/java/io/harness/cd/NGServiceConstants.java#L30)):*
> ```Java
>   public static final String SERVICE_INPUTS = "serviceInputs";
>   public static final String SERVICE = "service";
>   public static final String SERVICE_DEFINITION = "serviceDefinition";
> ```

YamlTypes this class in 127 module already has all of it.



_Code quote:_
```Java
  public static final String SERVICE_INPUTS = "serviceInputs";
  public static final String SERVICE = "service";
  public static final String SERVICE_DEFINITION = "serviceDefinition";
```

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 456 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3Y1SiADleXBGIcHnR_:-N3Y1SiADleXBGIcHnRa:b-wb7ugj) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L456)):*
> ```Java
>     try {
>       if (isEmpty(yaml)) {
>         throw new InvalidRequestException("Service yaml to create inputs cannot be empty");
> ```

Yaml should never be empty. This error message does not seems relevant for customer.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 8 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 2 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 419 at r2](https://reviewable.io/reviews/harness/harness-core/33789#-N3r_kKG9BZELgngp_9n:-N3r_kKG9BZELgngp_9o:by06f5f) ([raw file](https://github.com/harness/harness-core/blob/7f57abdee83815cccb8d9254471edaa7047574ad/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L419)):*
> ```Java
>   @ApiOperation(value = "This api returns runtime input YAML", nickname = "getRuntimeInputsServiceEntity")
>   @Hidden
>   // do not delete this.
> ```

nit: we do not need this comment here
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 434 at r2](https://reviewable.io/reviews/harness/harness-core/33789#-N3ra3fN4h88eiY5o6V4:-N3ra3fN4h88eiY5o6V5:b-9wozea) ([raw file](https://github.com/harness/harness-core/blob/7f57abdee83815cccb8d9254471edaa7047574ad/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L434)):*
> ```Java
>     if (serviceEntity.isPresent()) {
>       if (EmptyPredicate.isEmpty(serviceEntity.get().getYaml())) {
>         throw new InvalidRequestException("Service yaml cannot be empty");
> ```

I think we need to improve the error message, a user might not understand what this means
maybe "service Entity is not configured with a service definition" ?

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 439 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3XljBj3A18CPymtzpm:-N3s-enf3FheS_bQIQvx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L439)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this api is only going to be used by v2, so we should assume that yaml should be present else throw exception
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 456 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3Y1SiADleXBGIcHnR_:-N3s-gpgCl7j_RQE8aMU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L456)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Yaml should never be empty. This error message does not seems relevant for customer.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 476 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3Xm5hTDsgJ--sDIbFi:-N3s-j1bEcMt2fAM_Afk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L476)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not keep this in resource layer, and put this in service layer
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/cd/NGServiceConstants.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/33789#-N3Xl_cw08P60H5fR065:-N3s-k-J-M2swNOvmUq6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8eb96a2ffe36358ed554ed64a4ac9c9f57be773d/970-ng-commons/src/main/java/io/harness/cd/NGServiceConstants.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

YamlTypes this class in 127 module already has all of it.
</blockquote></details>

Done.

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 417 at r5](https://reviewable.io/reviews/harness/harness-core/33789#-N3wPGamDwCxZ-WR7W7n:-N3wPGamDwCxZ-WR7W7o:btbpp6h) ([raw file](https://github.com/harness/harness-core/blob/fbf6fe5981195dd92c09812cb118af757d46f9b8/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L417)):*
> ```Java
>   public ResponseDTO<String> getServiceRuntimeInputs(
>       @Parameter(description = SERVICE_PARAM_MESSAGE) @PathParam(
>           "serviceIdentifier") @ResourceIdentifier String serviceIdentifier,
> ```

nit: i think we can keep here identifier field constant as message is already there to clear any doubts



_Code quote:_
```Java
serviceIdentifier
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 353 at r5](https://reviewable.io/reviews/harness/harness-core/33789#-N3wRLAD-IAJxVNt0Zbi:-N3wRLAD-IAJxVNt0Zbj:bn0mkxp) ([raw file](https://github.com/harness/harness-core/blob/fbf6fe5981195dd92c09812cb118af757d46f9b8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L353)):*
> ```Java
>       }
>       JsonNode serviceDefinitionNode = YamlUtils.readTree(serviceDefinitionInputs).getNode().getCurrJsonNode();
>       serviceInputs.put(YamlTypes.SERVICE_INPUTS, serviceDefinitionNode);
> ```

just check with UI, do they need inside value of serviceInputs only or with serviceInputs.



_Code quote:_
```Java
serviceInputs.put(YamlTypes.SERVICE_INPUTS, serviceDefinitionNode)
```

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 353 at r5](https://reviewable.io/reviews/harness/harness-core/33789#-N3wRLAD-IAJxVNt0Zbi:-N4BO51e0ElYFaFGRN3-:b-mhtqc4) ([raw file](https://github.com/harness/harness-core/blob/fbf6fe5981195dd92c09812cb118af757d46f9b8/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L353)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

just check with UI, do they need inside value of serviceInputs only or with serviceInputs.
</blockquote></details>

We're going ahead with the current approach.

**Comment by hingerabhinav** [comment]
trigger ti0

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: 1 change requests. 1. unresolved discussions.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 3 of 10 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33789)* status: :shipit: complete! ✓

**Pull request merged**
