### PR TITLE
techdebt: [CDS-76775]: Remove circular dep

### PR DESCRIPTION
**Pull request by hextechpal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51224)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51224)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionFinishCallback.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/51224#-NbIWT-hBwxlmcfyMx-i:-NbIWT-hBwxlmcfyMx-j:b-50e73f) ([raw file](https://github.com/harness/harness-core/blob/199fbbf088b634cc882ea2793263111494a9381b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionFinishCallback.java#L12)):*
> ```Java
> 
> @Builder
> public class PlanExecutionFinishCallback implements OldNotifyCallback {
> ```

can we move this to service module of pipeline-service as we need to re-use this to update ttl for entities once planExecution ends

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51224)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionFinishCallback.java` line 12 at r1](https://reviewable.io/reviews/harness/harness-core/51224#-NbIWT-hBwxlmcfyMx-i:-NbOd2Te2dgfxcnEusF8:bcgqvc0) ([raw file](https://github.com/harness/harness-core/blob/bbb34b07e75cb90fa166445e2b2d62f1074e3a70/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionFinishCallback.java#L12)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we move this to service module of pipeline-service as we need to re-use this to update ttl for entities once planExecution ends
</blockquote></details>

as discussed this is not needed

**Comment by hextechpal** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51224)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
