### PR TITLE
feat: [PL-31822]: fix queries for EntitySetupUsage and entityActivity that fetches data without limit

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
1. for entityActivity applied limits on APIs that fetches data
2. for entitySetupUsage fixed added limits on API and fixed methods that are fetching all the data without any limit, created a new method that will return iterator and changed that method to fetch only entityReference of referred entities not whole entitySetupUsage method.

Both changes has been tested in local.
1. This has been tested by sending more than 1k as page size.
2. both new methods has been tested by writing dummy API and then testing them out in local.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44688)

### CODE REVIEW

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688#-:-NPbjD2YE2xsFCPMWrrH:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by RishabhGupta34 — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java` line 296 at r3](https://reviewable.io/reviews/harness/harness-core/44688#-NQ9FMTO5Hnuc55eS79g:-NQ9FMTO5Hnuc55eS79h:bj2vfyu) ([raw file](https://github.com/harness/harness-core/blob/beb69954889046ed77f58b4a49f9d141f4b618f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L296)):*
> ```Java
>       String referredByEntityName) {
>     Criteria criteria;
>     if (referredByEntityType.equals(EntityType.INFRASTRUCTURE)) {
> ```

revert equals

**Comment by abhinav-harness** [comment]
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java` line 296 at r3](https://reviewable.io/reviews/harness/harness-core/44688#-NQ9Ff6m43H-lb0yS-JJ:-NQ9Ff6m43H-lb0yS-JK:b-bhbsn9) ([raw file](https://github.com/harness/harness-core/blob/beb69954889046ed77f58b4a49f9d141f4b618f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L296)):*
> ```Java
>       String referredByEntityName) {
>     Criteria criteria;
>     if (referredByEntityType.equals(EntityType.INFRASTRUCTURE)) {
> ```

ideally i would not like this to be layer to know about infra

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/customDeployment/eventlistener/CustomDeploymentEntityCRUDStreamEventHandlerTest.java` line 305 at r3](https://reviewable.io/reviews/harness/harness-core/44688#-NQ9FyOr2FvWkuGz8PBY:-NQ9FyOr2FvWkuGz8PBZ:b-dh81zm) ([raw file](https://github.com/harness/harness-core/blob/beb69954889046ed77f58b4a49f9d141f4b618f3/125-cd-nextgen/src/test/java/io/harness/cdng/customDeployment/eventlistener/CustomDeploymentEntityCRUDStreamEventHandlerTest.java#L305)):*
> ```Java
>     return new CloseableIterator<T>() {
>       @Override
>       public void close() {}
> ```

this works or we need to call super.close() ?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/customDeployment/eventlistener/CustomDeploymentEntityCRUDStreamEventHandlerTest.java` line 305 at r3](https://reviewable.io/reviews/harness/harness-core/44688#-NQ9FyOr2FvWkuGz8PBY:-NQ9R2trBnFoZ8zb5SjF:b6f7m7s) ([raw file](https://github.com/harness/harness-core/blob/beb69954889046ed77f58b4a49f9d141f4b618f3/125-cd-nextgen/src/test/java/io/harness/cdng/customDeployment/eventlistener/CustomDeploymentEntityCRUDStreamEventHandlerTest.java#L305)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

this works or we need to call super.close() ?
</blockquote></details>

this is test class, just added it here for returning iterator in test
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java` line 296 at r3](https://reviewable.io/reviews/harness/harness-core/44688#-NQ9FMTO5Hnuc55eS79g:-NQ9RAsSCTICP-m0NUs6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/beb69954889046ed77f58b4a49f9d141f4b618f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L296)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

revert equals
</blockquote></details>

Done.
___
*[`955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java` line 296 at r3](https://reviewable.io/reviews/harness/harness-core/44688#-NQ9Ff6m43H-lb0yS-JJ:-NQ9RBQ2AN271LsxCPlm:b-y6341h) ([raw file](https://github.com/harness/harness-core/blob/beb69954889046ed77f58b4a49f9d141f4b618f3/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L296)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

ideally i would not like this to be layer to know about infra
</blockquote></details>

Its an existing code, we don't want to change any existing functionality so we will not change it

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688#-:-NQ9r0KT5ae4bzmtF3E4:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688#-:-NQAkBOf1dlzuVejLycs:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by RishabhGupta34 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44688)* status: :shipit: complete! ✓

**Pull request merged**
