### PR TITLE
feat: [CDS-45333]: remove accountId from instance query for it use proper index

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
Query causing slowness is one of these, depending on infra: (notice: accountId, appId and isDeleted field is common in all)

db.getCollection('instance').find({accountId: "<>", appId: "<>", isDeleted: "<>",  "hostInstanceKey.hostName": "<>", "hostInstancekey.inframappingId": "<>"})

db.getCollection('instance').find({accountId: "<>", appId: "<>", isDeleted: "<>",  "containerInstanceKey.containerId": "<>"})

db.getCollection('instance').find({accountId: "<>", appId: "<>", isDeleted: "<>",  "pcfInstanceKey.id": "<>"})

db.getCollection('instance').find({accountId: "<>", appId: "<>", isDeleted: "<>",  "podInstanceKey.podName": "<>", "podInstanceKey.namespace": "<>"})

Adding separate indexes for each is not good. It will increase load.

I saw that there is not index with accountId and appId combined, but there exist an index instance {"name": "instance_index1", "background": true} {"appId": 1, "isDeleted": 1, "deletedAt": 1}

So, probably thinking if we remove accountId filter from the query, it might help a bit but not that much.

I will remove the accountId from this query and we have to re-check this later.

Open for any other suggestions as well.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39883)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39883)* status: :shipit: complete! ✓

**Comment by inderschera** [comment]
trigger ti1

**Comment by hextechpal** [comment]
Does it need all the instance data, what is it trying to do from the data?

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39883)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
We are fetching the instance and doing the saveOrUpdate on that here: software.wings.service.impl.instance.InstanceServiceImpl#saveOrUpdate(software.wings.beans.infrastructure.instance.Instance)
This code is internally being called from containerInstanceSyncHandler.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39883#-:-NH-56Nh5OLsSYTS0mu_:b8a3cw6)* status: :shipit: complete! ✓

**Comment by lasdox** [comment]
I dont think this will help, mongo should be smart enough to use the index.
Could you try some testing and get data from mongo queries?

**Comment by lasdox** [comment]
Hey can we also add projection for instance as well? seems like we only need _id here

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39883)* status: :shipit: complete! ✓

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39883)* status: :shipit: complete! ✓

**Comment by inderschera** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39883)* status: :shipit: complete! ✓

**Pull request merged**
