### PR TITLE
[fix]: [PIE-5347]: [Next-Gen] Webhook Triggering twice

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37497)

**Comment by sribalij** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/webhook/polling/PolledItemPublisher.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37497#-NBuLWWV6ZQ6MXQ6N9DW:-NBuLWWV6ZQ6MXQ6N9DX:bjm0vbm) ([raw file](https://github.com/harness/harness-core/blob/393bc843be7f3018e84d010bb1070b452d3b30e9/120-ng-manager/src/main/java/io/harness/ng/webhook/polling/PolledItemPublisher.java#L42)):*
> ```Java
>                                .setData(pollingResponse.toByteString())
>                                .build());
>     log.info("Published the webhook polled item with message id {} ", messageId);
> ```

Is this log inside any Auto Log context?



_Code quote:_
```Java
log.info("Published the webhook polled item with message id {} ", messageId)
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/37497#-NBuMY8e18G9wuFkKHsE:-NBuMY8e18G9wuFkKHsF:b-jas8ui) ([raw file](https://github.com/harness/harness-core/blob/393bc843be7f3018e84d010bb1070b452d3b30e9/pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java#L37)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.PIPELINE)
> public class PollingEventStreamConsumer implements Runnable {
> ```

Why not move PMSEventConsumerService to PipelineEventConsumerController that way its handled generically about redis cache etc.



_Code quote:_
```Java
PollingEventStreamConsumer
```

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/webhook/polling/PolledItemPublisher.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37497#-NBuLWWV6ZQ6MXQ6N9DW:-NBxY9ja6QyyGxpk106D:bjak4bs) ([raw file](https://github.com/harness/harness-core/blob/393bc843be7f3018e84d010bb1070b452d3b30e9/120-ng-manager/src/main/java/io/harness/ng/webhook/polling/PolledItemPublisher.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Is this log inside any Auto Log context?
</blockquote></details>

This is not inside Autolog but capturing it inside the PollingEventStreamListenerin autolog
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/37497#-NBuMY8e18G9wuFkKHsE:-NBxYPRiCOnzwtdp1TlF:byb5vec) ([raw file](https://github.com/harness/harness-core/blob/393bc843be7f3018e84d010bb1070b452d3b30e9/pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why not move PMSEventConsumerService to PipelineEventConsumerController that way its handled generically about redis cache etc.
</blockquote></details>

Done. Moved it to PipelineEventConsumerController

**Review by inderschera — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/37497#-NBzwfHBE9bDhfD6SbFC:-NCNg2R757OHsMml1bow:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/37ec9d6bdf8f2a56ed468b26dbe472eaf3ad7091/pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I dont think you need these 2
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/37497#-NBzwlMWBVmSJTLG_9Ik:-NCNg1qL5-Sp4eesLH2R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/37ec9d6bdf8f2a56ed468b26dbe472eaf3ad7091/pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent/PollingEventStreamConsumer.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This also i dont think you need
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37497)* status: :shipit: complete! ✓

**Pull request merged**
