### PR TITLE
[feat]: [PIE-5830]: Move Rollback Custom Advisor to Pipeline Service

### PR DESCRIPTION
**Pull request by namanvermah**
ParallelPlanCreator needs Rollback Custom Advisor for Pipeline Rollback, and so do all non CD stages. Hence moving it to a common module.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38820)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38820)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/rollback/RollbackStartAdvisor.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/38820#-NEZhc897yPIE__LN7ax:-NEZhc897yPIE__LN7ay:b-826hdw) ([raw file](https://github.com/harness/harness-core/blob/a82d73629a1dc9a7834ebb66cd3caf2bddd8437e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/rollback/RollbackStartAdvisor.java#L38)):*
> ```Java
>   @Override
>   public AdviserResponse onAdviseEvent(AdvisingEvent advisingEvent) {
>     OnFailRollbackOutput rollbackOutcome = getRollbackOutputV2(advisingEvent);
> ```

why have we named this function as v2 for newly created class

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38820)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38820)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/rollback/RollbackStartAdvisor.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/38820#-NEZhc897yPIE__LN7ax:-NE_klR045D9RROLvqit:bw142hm) ([raw file](https://github.com/harness/harness-core/blob/a82d73629a1dc9a7834ebb66cd3caf2bddd8437e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/rollback/RollbackStartAdvisor.java#L38)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

why have we named this function as v2 for newly created class
</blockquote></details>

This is not a new class, its a duplicate. The original will be removed after a release cycle

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38820)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38820)* status: :shipit: complete! ✓

**Pull request merged**
