### PR TITLE
[feat]: [CVS-9506]: added logs for monitored service

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31440)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31440)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/logsFilterParams/LiveMonitoringLogsFilter.java, line 24 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB-dNq27IhuB57YqxL:-MyB-dNq27IhuB57YqxM:b-vno0da) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/logsFilterParams/LiveMonitoringLogsFilter.java#L24)):*
> ```Java
> @Data
> @NoArgsConstructor
> public class LiveMonitoringLogsFilter extends SLILogsFilter {
> ```

it should not extend SLILogFilter, if SLI and these filter happen to be common we should have a common base class.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java, line 143 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB0as1-C0Lk3Nw8LZy:-MyB0as1-C0Lk3Nw8LZz:blxswhf) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L143)):*
> ```Java
>   @Mock SetupUsageEventService setupUsageEventService;
>   @Mock ChangeSourceService changeSourceServiceMock;
>   @Mock CVNGLogService cvngLogService;
> ```

why do we need to mock it?
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java, line 1920 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB0iii8ahyEqZTtHKC:-MyB0iii8ahyEqZTtHKD:b-mpbwny) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L1920)):*
> ```Java
>                                 .log("Data Collection successfully completed.")
>                                 .build();
>     PageResponse pageResponse = PageUtils.offsetAndLimit(Arrays.asList(cvngLogDTO), 0, 10);
> ```

we should create a real CVNGLog instead of mocking.
Please add test with health source filter and without health source filter.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31440)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/logsFilterParams/LiveMonitoringLogsFilter.java, line 24 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB-dNq27IhuB57YqxL:-MyBJDgo3PHlgvV75FAB:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/params/logsFilterParams/LiveMonitoringLogsFilter.java#L24)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

it should not extend SLILogFilter, if SLI and these filter happen to be common we should have a common base class.
</blockquote></details>

done
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java, line 143 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB0as1-C0Lk3Nw8LZy:-MyBJJPW4oqW56c8GJXa:bwhioiv) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L143)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why do we need to mock it?
</blockquote></details>

the idea is to not test cvngLogService.getCVNGLogs() because it is already tested in its respective class UTs
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java, line 1920 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB0iii8ahyEqZTtHKC:-MyBJFeZ5Z0NZOZFkYS8:bumsmd2) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L1920)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should create a real CVNGLog instead of mocking.
Please add test with health source filter and without health source filter. 
</blockquote></details>

added a UT with health source filter

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31440)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java, line 143 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB0as1-C0Lk3Nw8LZy:-MyBjkza88VzjXV9zDLG:bfofxty) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L143)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

the idea is to not test cvngLogService.getCVNGLogs() because it is already tested in its respective class UTs
</blockquote></details>

We should test the behaviour. The test should not be aware of which method is called internally. The behaviour is that some CVNGLogs are saved and we are trying to query for them. If we use Mocking we are testing implementation details. Also this is the convention that we use in CVNG. If you think we should do this differently we can also discuss in the arch board.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31440)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java, line 143 at r1](https://reviewable.io/reviews/harness/harness-core/31440#-MyB0as1-C0Lk3Nw8LZy:-MyC4V4B0uB7dG5JIbEz:b-bbl28q) ([raw file](https://github.com/harness/harness-core/blob/96bf72552e71e1ec36e3f73e54d244a4aa8a7789/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java#L143)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We should test the behaviour. The test should not be aware of which method is called internally. The behaviour is that some CVNGLogs are saved and we are trying to query for them. If we use Mocking we are testing implementation details. Also this is the convention that we use in CVNG. If you think we should do this differently we can also discuss in the arch board.
</blockquote></details>

understood, done

**Pull request merged**
