### PR TITLE
fix: [CDS-45397]: Handle Github API when commit sha is not present

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
MergePR Github API was throwing an error - "Base branch was modified. Review and try the merge again". But our API was returning the error as a key not found in json object. This change is to fix that and return the appropriate error to the user.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39306)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Review by rohitk-h — CHANGES_REQUESTED** [review]
We have a practice of putting in some information about the change and how to test etc. It's helpful for the reviewer to get more context on the change. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306#-:-NFPTJYa5xdYF8A9NuYZ:bo85qhd)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPVcmY0Fc41VdNq7u_:-NFPVcmY0Fc41VdNq7ua:b-tg3lv0) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L138)):*
> ```Java
>       } else {
>         log.error("Failed to merge pr error {}, message {}", response.errorBody().string(), response.message());
>         log.warn("Merge Request for merging PR returned with response code {}", prNumber, response.code());
> ```

Can we merge the two loggers into one?
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPW1Cs7PlisNgDjTLp:-NFPW1Cs7PlisNgDjTLq:bpbw4bt) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L140)):*
> ```Java
>         log.warn("Merge Request for merging PR returned with response code {}", prNumber, response.code());
>         JSONObject json = new JSONObject();
>         json.put("error", response.errorBody().string());
> ```

This error message is something that is returned to the user, can we just send the response message and code instead? 
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPWl0Y6Tm2DqEy5Kv7:-NFPWl0Y6Tm2DqEy5Kv8:b5uhpt7) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L142)):*
> ```Java
>         json.put("error", response.errorBody().string());
>         json.put(MERGED, false);
>         return json;
> ```

nitpick: this return can be outside the if

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by meenaravichandran1 — COMMENTED** [review]
>  a practice of putting in some information about the change and how to test etc. It's helpful for the reviewer to get more context on the change.
Should I put them in Reviewable as comments near the appropriate change or is it somewhere else?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306#-:-NFPYMUi1m5pszdR_zCs:b5swzvg)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPVcmY0Fc41VdNq7u_:-NFPbt193dOZOHH-Sy54:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L138)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Can we merge the two loggers into one?
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPW1Cs7PlisNgDjTLp:-NFPbz6G1CgF0EtoYbha:b-c4h729) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L140)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This error message is something that is returned to the user, can we just send the response message and code instead? 
</blockquote></details>

I'm not sure about the other errors, but for the specific error that I encountered, the response was like this,

"Failed to merge pr error {"message":"Base branch was modified. Review and try the merge again.","documentation_url":"https://docs.github.com/rest/reference/pulls#merge-a-pull-request"}, message "

Merge Request for merging PR returned with response code 94

Link: https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fqa-setup%2Flogs%2Fdelegate%22%0Alabels.managerHost%3D%22qa.harness.io%22%0A%0Alabels.accountId%3D%221bvyLackQK-Hapk25-Ry4w%22%0AjsonPayload.harness.taskId%3D%22ShhIFq12Tr-obvDjghIwLQ%22;timeRange=2022-10-22T00:20:00.000Z%2F2022-10-22T00:22:00.000Z;cursorTimestamp=2022-10-22T00:20:43.219Z?project=qa-setup

the response code was the PR number and the message was empty. The error details were in the error body. I can still make a change to return the response code as well considering other possible errors that could happen. Any other change should be made here?
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 142 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPWl0Y6Tm2DqEy5Kv7:-NFPbr7f-xOrwYPPGlbU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L142)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

nitpick: this return can be outside the if
</blockquote></details>

Done.

**Comment by rohitk-h** [comment]
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPW1Cs7PlisNgDjTLp:-NFPr1XME8kCcXjYsvHT:bw4o2q6) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L140)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

I'm not sure about the other errors, but for the specific error that I encountered, the response was like this,

"Failed to merge pr error {"message":"Base branch was modified. Review and try the merge again.","documentation_url":"https://docs.github.com/rest/reference/pulls#merge-a-pull-request"}, message "

Merge Request for merging PR returned with response code 94

Link: https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fqa-setup%2Flogs%2Fdelegate%22%0Alabels.managerHost%3D%22qa.harness.io%22%0A%0Alabels.accountId%3D%221bvyLackQK-Hapk25-Ry4w%22%0AjsonPayload.harness.taskId%3D%22ShhIFq12Tr-obvDjghIwLQ%22;timeRange=2022-10-22T00:20:00.000Z%2F2022-10-22T00:22:00.000Z;cursorTimestamp=2022-10-22T00:20:43.219Z?project=qa-setup

the response code was the PR number and the message was empty. The error details were in the error body. I can still make a change to return the response code as well considering other possible errors that could happen. Any other change should be made here?


</blockquote></details>

The message `Base branch was modified. Review and try the merge again` is helped that is what we return to the use along with the error code.

**Comment by rohitk-h** [comment]
It's in gihub when you create PR we have a template, describe your changes. We should add it there.

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/39306#-NFPW1Cs7PlisNgDjTLp:-NFQHyjhDe4TBx36cJ2z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/43f82bc0fcb5e9a104167c9cd230eb088ffee9fc/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L140)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

The message `Base branch was modified. Review and try the merge again` is helped that is what we return to the use along with the error code. 
</blockquote></details>

Done.

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 139 at r6](https://reviewable.io/reviews/harness/harness-core/39306#-NFQPHHoBEJ85iuw30tr:-NFQPHHoBEJ85iuw30ts:b-sgklqx) ([raw file](https://github.com/harness/harness-core/blob/2255121b347478e09b542c872caaa5c20e5ff591/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L139)):*
> ```Java
>         JSONObject errObject = new JSONObject(response.errorBody().string());
>         log.error("Failed to merge PR {}. error {}, code {}", prNumber, errObject.get(MESSAGE), response.code());
>         json.put("error", response.errorBody().string());
> ```

So `error` and `message` has the same information. can we just set `error` since the layer above is only reading the error?

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 139 at r6](https://reviewable.io/reviews/harness/harness-core/39306#-NFQPHHoBEJ85iuw30tr:-NFQSs5o-sAoNIJ-8fKJ:b-xay1wh) ([raw file](https://github.com/harness/harness-core/blob/2255121b347478e09b542c872caaa5c20e5ff591/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L139)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

So `error` and `message` has the same information. can we just set `error` since the layer above is only reading the error?
</blockquote></details>

my bad, I missed to make a change in this line. Thanks for pointing that out!

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39306)* status: :shipit: complete! ✓

**Pull request merged**
