### PR TITLE
[feat]:[PL-28834]: Moves generated sever spec to bazel module

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger ti3

**Review by USB-05 — DISMISSED** [review]

**Comment by ashishsanodia-harness** [comment]
trigger codebasehash

**Comment by ashishsanodia-harness** [comment]
trigger ft2

**Comment by ashishsanodia-harness** [comment]
trigger ti3

**Review by reetika04 — DISMISSED** [review]
> Reviewed 77 of 97 files at r2, 1 of 14 files at r3, 72 of 76 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: 155 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 97 files at r2, 8 of 76 files at r4, 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: 145 file(s) to review.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 77 of 97 files at r2, 1 of 14 files at r3, 72 of 76 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: :shipit: complete! ✓

**Comment by ashishsanodia-harness** [comment]
trigger codebasehash

**Comment by ashishsanodia-harness** [comment]
trigger ft2

**Review by reetika04 — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: :shipit: complete! ✓

**Review by archit-harness — DISMISSED** [review]
> Reviewed 76 of 97 files at r2, 1 of 14 files at r3, 63 of 76 files at r4, 1 of 1 files at r5, 1 of 4 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: :shipit: complete! ✓

**Comment by ashishsanodia-harness** [comment]
trigger compile, trigger ft2

**Comment by ashishsanodia-harness** [comment]
trigger ti0, trigger ti1, trigger ti2, trigger ti3, trigger ti4

**Comment by ashishsanodia-harness** [comment]
trigger ti0, trigger ti1, trigger ti2, trigger ti3, trigger ti4

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 77 of 97 files at r2, 1 of 14 files at r3, 66 of 76 files at r4, 1 of 1 files at r5, 2 of 4 files at r6, 1 of 3 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, 12 of 14 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 12 of 14 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38808)* status: :shipit: complete! ✓

**Pull request merged**
