### PR TITLE
[techdebt]: [PIE-6260]: Orchestration Event should be generated after…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
… the nodeExecution is created

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39918)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39918)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 386 at r1](https://reviewable.io/reviews/harness/harness-core/39918#-NGVAyBdBvX26VfYwdRv:-NGVAyBdBvX26VfYwdRw:b2ygawz) ([raw file](https://github.com/harness/harness-core/blob/566be322082162121f1a45f9b1cb5469eca0ba87/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L386)):*
> ```Java
>     if (nodeExecution.getVersion() == null) {
>       NodeExecution savedNodeExecution = transactionHelper.performTransaction(() -> {
>         NodeExecution nodeExecution1 = mongoTemplate.insert(nodeExecution);
> ```

betterName persistedNodeExecution
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 387 at r1](https://reviewable.io/reviews/harness/harness-core/39918#-NGVBFV76r57bdySORu-:-NGVBFV76r57bdySORu0:b-cjn31y) ([raw file](https://github.com/harness/harness-core/blob/566be322082162121f1a45f9b1cb5469eca0ba87/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L387)):*
> ```Java
>       NodeExecution savedNodeExecution = transactionHelper.performTransaction(() -> {
>         NodeExecution nodeExecution1 = mongoTemplate.insert(nodeExecution);
>         if (orchestrationLogConfiguration.isReduceOrchestrationLog()) {
> ```

can we get rid of this config?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 387 at r1](https://reviewable.io/reviews/harness/harness-core/39918#-NGVBFV76r57bdySORu-:-NGVKw_xBZTFji4QJ4Wc:bek3izu) ([raw file](https://github.com/harness/harness-core/blob/566be322082162121f1a45f9b1cb5469eca0ba87/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L387)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

can we get rid of this config?
</blockquote></details>

Yes, will create another PR for this

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39918)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39918)* status: :shipit: complete! ✓

**Pull request merged**
