### PR TITLE
[fix]:[pl-28108]: add parent entity scope for resolution 

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Add parent entity scope details for resolution of nested templates and pipeline using templates.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* Code issue 1 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37375)

**Review by inderschera — COMMENTED** [review]
> Reviewed 13 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvARYW8N_zrtAYnMO5:-NBvARYW8N_zrtAYnMO6:b-xr0yvb) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
> ```Java
>     GitAwareContextHelper.initDefaultScmGitMetaData();
>     GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
>     if (templateGitXService.isNewGitXEnabled(templateToUpdate, gitEntityInfo)) {
> ```

Why have we removed storeType remote check here?
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBv91FO4uliA9gfzUSO:-NBv91FO4uliA9gfzUSP:b1jdrwf) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L114)):*
> ```Java
>     List<EntityDetailProtoDTO> referredEntities = new ArrayList<>();
>     YamlConfig yamlConfig = new YamlConfig(yaml);
>     TemplateUtils.setupGitParentEntityDetails(accountId, orgId, projectId);
> ```

Why are we setting parent entity git details here? 
Aren't we setting it at beginning of save and update of template?
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 286 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBv9yhh3KATQBtyLGE6:-NBv9yhiBRYQnKyFVzHj:bv010w8) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L286)):*
> ```Java
>     enforcementClientService.checkAvailability(
>         FeatureRestrictionName.TEMPLATE_SERVICE, templateEntity.getAccountIdentifier());
>     if (TemplateRefHelper.hasTemplateRef(templateEntity.getYaml())) {
> ```

You can set parentEntityDetails without checking if template has templateRef here.
This would help for all calls like applyTemplates, populate template references and getAndValidateOldTemplateEntity.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1012 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvACAKA0bDqjB5cAgD:-NBvACAKA0bDqjB5cAgE:b-5an79n) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1012)):*
> ```Java
>   private TemplateEntity getAndValidateOldTemplateEntity(
>       TemplateEntity templateEntity, String oldOrgIdentifier, String oldProjectIdentifier) {
>     TemplateUtils.setupGitParentEntityDetails(
> ```

we probably don't need it here. Looks like duplicate thing to do.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvAsYy6XKrtR7xD9f9:-NBvAsYy6XKrtR7xD9fA:b-vcnz49) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L88)):*
> ```Java
>       String accountId, String orgId, String projectId, String yaml, boolean getMergedYamlWithTemplateField) {
>     YamlNode yamlNode = validateAndGetYamlNode(yaml);
>     TemplateUtils.setupGitParentEntityDetails(accountId, orgId, projectId);
> ```

Why do we need this here? This method is either called from resource layer or service layer. If called from resource layer, then caller should pass these details in api call and thread decorator should add the parent details in git context. From service layer we call it on template save/update where we are already populating this.
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvBXQq3Yj-TuLM58Fh:-NBvBXQq3Yj-TuLM58Fi:b-5h08c7) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L106)):*
> ```Java
>       String accountId, String orgId, String projectId, String yaml, boolean getMergedYamlWithTemplateField) {
>     YamlNode yamlNode = validateAndGetYamlNode(yaml);
>     TemplateUtils.setupGitParentEntityDetails(accountId, orgId, projectId);
> ```

same here.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: 4 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvARYW8N_zrtAYnMO5:-NBvGKyv7DH2KKtC_9Pg:b-w9lzv) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Why have we removed storeType remote check here?
</blockquote></details>

we are doing the check inside the isNewGitXEnabled for Remote StoreType as well



_Code quote (from 840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java):_
```Java
getNestedTemplateReferences
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBv91FO4uliA9gfzUSO:-NBvHoRB1VVxvosJg8b4:b-q96okk) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L114)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Why are we setting parent entity git details here? 
Aren't we setting it at beginning of save and update of template?
</blockquote></details>

As you mention when this is being invoked either from the create or update flow, we are setting the details already but when the api is called directly, we wont be having the parentEntityContext set, hence we need it here



_Code quote (from 840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java):_
```Java
applyTemplatesToYaml
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1012 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvACAKA0bDqjB5cAgD:-NBvH09i65tDe60G9TZ9:b-q7f07b) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1012)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

we probably don't need it here. Looks like duplicate thing to do.
</blockquote></details>

There are two flows which invoke this method, in one of the flow as you mentioned, we are setting it and in the other flow, we need to set it



_Code quote:_
```Java
getAndValidateOldTemplateEntity
```

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvARYW8N_zrtAYnMO5:-NBvJbKUEezg-dKYEAeY:badkidx) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we are doing the check inside the isNewGitXEnabled for Remote StoreType as well
</blockquote></details>

if gitEntityInfo is fetched from context itself, then why do we need to pass it in as argument? Lets fetch it inside the method only.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1012 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvACAKA0bDqjB5cAgD:-NBvK42y7GyMnmCkrj8_:b-6m8ilk) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1012)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

There are two flows which invoke this method, in one of the flow as you mentioned, we are setting it and in the other flow, we need to set it
</blockquote></details>

@adivishy1 is it possible to put this check as early as possible in all APIs? I mean to say that we can review the APIs and the first methods they call in service and just simply put this check over there, so that it takes care of all nested code-flows. I'm not sure if it would help but sounds good to me, thoughts?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: 4 file(s) to review. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvARYW8N_zrtAYnMO5:-NBvMjoQBPX_gThIz3XW:b-p36kpo) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if gitEntityInfo is fetched from context itself, then why do we need to pass it in as argument? Lets fetch it inside the method only.
</blockquote></details>

in the create flow, before we reach the remote type, we are checking with the git context for the inline case and as well as when there is no git  management enabled for the project.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1012 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvACAKA0bDqjB5cAgD:-NBvNIaJ2Vm4LJAKBEuB:b977vv9) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1012)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@adivishy1 is it possible to put this check as early as possible in all APIs? I mean to say that we can review the APIs and the first methods they call in service and just simply put this check over there, so that it takes care of all nested code-flows. I'm not sure if it would help but sounds good to me, thoughts?
</blockquote></details>

yes, i agree, in some of the cases, where its possible, like applyTemplates, i have done the same, in cases where its not possible have pushed it to later part of the code flow



_Code quote:_
```Java
getAndValidateOldTemplateEntity(
```
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvAsYy6XKrtR7xD9f9:-NBvNjFoBlM5bdA6b6UW:b5yem7g) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L88)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Why do we need this here? This method is either called from resource layer or service layer. If called from resource layer, then caller should pass these details in api call and thread decorator should add the parent details in git context. From service layer we call it on template save/update where we are already populating this.
</blockquote></details>

I have added this here mainly to handle the resource layer calls, if dont have this, the api call is failing, i have tried out this scenario, cause even i was having the same thought 
___
*[`840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvBXQq3Yj-TuLM58Fh:-NBvO6Ba-GVEPRepV3tw:bffwtwy) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/TemplateMergeServiceImpl.java#L106)):*
>I have added this here mainly to handle the resource layer calls, if dont have this, the api call is failing, i have tried out this scenario, cause even i was having the same thought

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvARYW8N_zrtAYnMO5:-NBvcZcfD5K_oHoQd6UT:b-l4bwp9) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L295)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

in the create flow, before we reach the remote type, we are checking with the git context for the inline case and as well as when there is no git  management enabled for the project.
</blockquote></details>

As discussed on DM, we agree to remove the argument gitEntityInfo from the method. This will be taken up separately.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: 3. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBv91FO4uliA9gfzUSO:-NBvr16KChUpMY4Cs_fD:bvs0u7y) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java#L114)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

As you mention when this is being invoked either from the create or update flow, we are setting the details already but when the api is called directly, we wont be having the parentEntityContext set, hence we need it here
</blockquote></details>

create a ticket to remove this from update scope flow.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1012 at r1](https://reviewable.io/reviews/harness/harness-core/37375#-NBvACAKA0bDqjB5cAgD:-NBvrQ_T9QsJRlQufxOY:b-bjpinn) ([raw file](https://github.com/harness/harness-core/blob/f9120487828f793035f200834d1313e64bd047d8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1012)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

yes, i agree, in some of the cases, where its possible, like applyTemplates, i have done the same, in cases where its not possible have pushed it to later part of the code flow
</blockquote></details>

Remove from here, since only part of scope flow.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37375)* status: :shipit: complete! ✓

**Pull request merged**
