### PR TITLE
[feat]: [CDS-79410]: Adding delegate tasks for ecs basic step

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
 Added delegate task request and response schema for ecs basic steps
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53683)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger ut9

**Comment by PragyeshMishra01** [comment]
trigger uts

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger ut7 ut8 ut9

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Review by ivan-83 — COMMENTED** [review]
@PragyeshMishra01 generally LGTM with comments. Do we have tech/dev spec for this, could you pls share it with me?  

> Reviewed 29 of 29 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53683#-:-NfwmXlCDPLlCoQu0Dal:bary24t)* status: 30 file(s) to review. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 2176 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwgWY0CU3QhG3Os05f:-NfwgWY10X9Hit2ECA47:bpcil18) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L2176)):*
> ```Java
>     mapBinder.addBinding(TaskType.ECS_TASK_ARN_BLUE_GREEN_CREATE_SERVICE_NG)
>         .toInstance(EcsTaskArnBlueGreenCreateServiceTaskNG.class);
>     mapBinder.addBinding(TaskType.ECS_BASIC_PREPARE_ROLLBACK_TASK_NG).toInstance(EcsBasicPrepareRollbackTaskNG.class);
> ```

What is the difference between EcsBasicPrepareRollbackTaskNG and EcsBasicRollbackTaskNG, do we need two rollbacks?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwhVd-1OdEk7Wpib-R:-NfwhVd-1OdEk7Wpib-S:b-t04xfj) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java#L20)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.CDP)
> public class EcsBasicDeployResult {
> ```

Can we have a better name instead of Result, like EcsBasicDeployData or...
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-Nfwh8KGA2NpJ4ODk3iN:-Nfwh8KGA2NpJ4ODk3iO:b-xt41m3) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java#L25)):*
> ```Java
>   private String region;
>   private List<EcsTask> oldServiceEcsTasks;
>   private String newServiceEcsTasks;
> ```

If it's String, should it be newServiceEcsTask instead of newServiceEcsTasks.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicPrepareRollbackResult.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwlshQ5Dn5ggRiiFXW:-NfwlshQ5Dn5ggRiiFXX:bpoqjon) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicPrepareRollbackResult.java#L22)):*
> ```Java
> public class EcsBasicPrepareRollbackResult {
>   String currentServiceName;
>   String createServiceRequestBuilderString;
> ```

Why Builder and String in instance variable names?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwhuXV4M7UCJNSyp5Y:-NfwhuXV4M7UCJNSyp5Z:b-5boetf) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java#L29)):*
> ```Java
> public class EcsBasicPrepareRollbackRequest implements EcsCommandRequest, NestedAnnotationResolver {
>   String accountId;
>   EcsCommandTypeNG ecsCommandType;
> ```

Minor: ecsCommandType >>commandType, We already know that it's Ecs and you can only consume property from this class or builder of this class.
The same and for ecsServiceDefinitionManifestContent and ecsInfraConfig. 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwihKW1JGXopxXDUJ_:-NfwihKW1JGXopxXDUJa:bpq58dv) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java#L34)):*
> ```Java
>   @NonFinal @Expression(ALLOW_SECRETS) String ecsServiceDefinitionManifestContent;
>   @NonFinal @Expression(ALLOW_SECRETS) EcsInfraConfig ecsInfraConfig;
>   @NonFinal @Expression(ALLOW_SECRETS) Integer timeoutIntervalInMin;
> ```

Should we allow secrets for timeout?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicRollbackRequest.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwiqSC7Xwt51ZdaAw_:-NfwiqSC7Xwt51ZdaAwa:b-b10fb6) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicRollbackRequest.java#L35)):*
> ```Java
>   Integer timeoutIntervalInMin;
>   @NonFinal @Expression(ALLOW_SECRETS) EcsInfraConfig ecsInfraConfig;
>   @NonFinal @Expression(ALLOW_SECRETS) String createServiceRequestBuilderString;
> ```

Why Builder and String in instance variable names? Does it have a special meaning for ECS deployment?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-Nfwkdt-ADLIWa8UzDBm:-Nfwkdt09hN1ZpKUDR_d:b-ri6asm) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java#L35)):*
> ```Java
>   CommandUnitsProgress commandUnitsProgress;
>   @NonFinal @Expression(ALLOW_SECRETS) EcsInfraConfig ecsInfraConfig;
>   @NonFinal @Expression(ALLOW_SECRETS) Integer timeoutIntervalInMin;
> ```

Do we need secrets for timeout?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-Nfwksl09mvCfJYQ5A6c:-Nfwksl09mvCfJYQ5A6d:b18ycxc) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java#L37)):*
> ```Java
>   @NonFinal @Expression(ALLOW_SECRETS) Integer timeoutIntervalInMin;
>   EcsResizeStrategy ecsResizeStrategy;
>   @NonFinal @Expression(ALLOW_SECRETS) Integer newServiceInstance;
> ```

There are a lot of properties for the new/old service. Can we consider having different data structures for old and new service?

**Review by PragyeshMishra01 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53683)* status: 32 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 2176 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwgWY0CU3QhG3Os05f:-Nfx0GK508qmKZJTz2Qz:bw7hsoi) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L2176)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What is the difference between EcsBasicPrepareRollbackTaskNG and EcsBasicRollbackTaskNG, do we need two rollbacks?
</blockquote></details>

EcsBasicRollbackTaskNG is use for rollback.
EcsBasicPrepareRollbackTaskNG is use to fetch required info needed for rollback. we will run this task before deploy task.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwhuXV4M7UCJNSyp5Y:-Nfx1A8j5nBOvTUZ43Qz:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java#L29)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor: ecsCommandType >>commandType, We already know that it's Ecs and you can only consume property from this class or builder of this class.
The same and for ecsServiceDefinitionManifestContent and ecsInfraConfig.
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwihKW1JGXopxXDUJ_:-Nfx1BH0-eAfXZ6GUa0G:b9eey21) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicPrepareRollbackRequest.java#L34)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we allow secrets for timeout?
</blockquote></details>

no, removed annotation
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicRollbackRequest.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwiqSC7Xwt51ZdaAw_:-Nfx1Dum5AQ4N7oxdfM7:b-hnq59u) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsBasicRollbackRequest.java#L35)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why Builder and String in instance variable names? Does it have a special meaning for ECS deployment?
</blockquote></details>

removed it.
 we used this naming in other ecs tasks so I followed it but I think it doesn't make sense to add these suffix to variable name.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-Nfwkdt-ADLIWa8UzDBm:-Nfx1jBD8vQXb_g-Thh_:btc6f39) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java#L35)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Do we need secrets for timeout?
</blockquote></details>

no, removed it
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-Nfwksl09mvCfJYQ5A6c:-Nfx1l9O-yMEWZMQlcaP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ecs/request/EcsUpgradeContainerRequest.java#L37)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

There are a lot of properties for the new/old service. Can we consider having different data structures for old and new service?
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwhVd-1OdEk7Wpib-R:-Nfx10Lt4A7iZuzDD4FX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java#L20)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we have a better name instead of Result, like EcsBasicDeployData or...
</blockquote></details>

done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-Nfwh8KGA2NpJ4ODk3iN:-Nfx11qTDULbZyUEYYEj:b-x42oi9) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicDeployResult.java#L25)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If it's String, should it be newServiceEcsTask instead of newServiceEcsTasks.
</blockquote></details>

done, created a new data structure for service details
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicPrepareRollbackResult.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/53683#-NfwlshQ5Dn5ggRiiFXW:-Nfx0kHs57OaprgBxjHR:bpoi38c) ([raw file](https://github.com/harness/harness-core/blob/817484bf4a8d676815a4030edb64171cebaef6c8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ecs/EcsBasicPrepareRollbackResult.java#L22)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why Builder and String in instance variable names?
</blockquote></details>

removed it
 we used this naming in other ecs tasks so I followed it but I think it doesn't make sense to add these suffix to variable name.

**Comment by PragyeshMishra01** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53683#-:-NfyltgC8bg4eQdkSQqD:bnfp4nl)* status: 34 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger review

**Comment by PragyeshMishra01** [comment]
trigger ut7 ut8

**Pull request merged**
