### PR TITLE
[feat]: [CDS-34034]: Saving stage execution info logic for rollback

### PR DESCRIPTION
**Pull request by ivan-83**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36060)

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 16 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gdVhe95wwRLza5Qfd:-N8gdVhe95wwRLza5Qfe:b-jdkyrk) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L108)):*
> ```Java
>   @Inject private CDStepHelper cdStepHelper;
>   @Inject ExecutionSweepingOutputService executionSweepingOutputService;
>   @Inject StageExecutionHelper saveStageExecutionInfo;
> ```

StageExecutionHelper stageExecutionHelper;
___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8ge9YVEuPAB7OGYxzC:-N8ge9YVEuPAB7OGYxzD:b-oixxv) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java#L36)):*
> ```Java
> 
>   @Override
>   public UpdateResult updateStatus(Scope scope, String stageExecutionId, StageStatus status) {
> ```

Scope is not used here.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gf6rBELOU_xKt4TV9:-N8gf6rBELOU_xKt4TVA:b-jdkyrk) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java#L121)):*
> ```Java
>   @Mock K8sInfraDelegateConfig k8sInfraDelegateConfig;
>   @Mock InfrastructureStepHelper infrastructureStepHelper;
>   @Mock StageExecutionHelper saveStageExecutionInfo;
> ```

StageExecutionHelper stageExecutionHelper;

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 14 of 16 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionInfoKey.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8ggB4yAWHZWgLLChWA:-N8ggB4yAWHZWgLLChWB:b-frpu1t) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionInfoKey.java#L28)):*
> ```Java
>   @NotNull String infraIdentifier;
>   @NotNull String serviceIdentifier;
>   @Nullable String customDeploymentKey;
> ```

what's the `customDeploymentKey` ? can we have it as deploymentIdentifier just to be consistent
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gi-Fd1nWwPs9ymc8B:-N8gi-Fd1nWwPs9ymc8C:bvtuwl8) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java#L70)):*
> ```Java
>     List<StageExecutionInfo> latestSucceededStageExecutionInfo =
>         stageExecutionInfoRepository.listSucceededStageExecutionNotIncludeCurrent(executionInfoKey, executionId, limit);
>     return latestSucceededStageExecutionInfo.size() != limit
> ```

not getting here, if we will have 3 success stages, we will return empty? Shouldn't we take care of this case and get the latest? Empty i guess should be when there is nothing in there
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8giXll7jyyrFrYp0t4:-N8giRAL6aFCMkr14Ro8:b-taixrk) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java#L27)):*
> ```Java
> public class SshWinRmStageExecutionDetails implements ExecutionDetails {
>   private ArtifactOutcome artifactOutcome;
>   private ConfigFilesOutcome configFilesOutcome;
> ```

nit: need to see if we can store variables also

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/StageExecutionInfo.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gp2PR14lnJ2UibGFk:-N8gp2PR14lnJ2UibGFl:b97vchn) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/StageExecutionInfo.java#L69)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(SortCompoundMongoIndex.builder()
>                  .name("scope_envIdentifier_infraIdentifier_serviceIdentifier_stageExecutionId_createdAt")
> ```

nit: scope is not part of index keys
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gp5ik5iPU8xoDkucP:-N8gp5ik5iPU8xoDkucQ:b-845r4m) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L36)):*
> ```Java
> @Slf4j
> @OwnedBy(CDP)
> public class StageExecutionHelper {
> ```

Wouldn't it make more sense to have a mapper class that will map all details to ExecutionDetails?  Helper class doesn't really make sense for this purpose
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gi-Fd1nWwPs9ymc8B:-N8gplSrALD3juPLftqc:bqc6zqh) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java#L70)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

not getting here, if we will have 3 success stages, we will return empty? Shouldn't we take care of this case and get the latest? Empty i guess should be when there is nothing in there
</blockquote></details>

I would say this logic is confusing for me either, if limit is always one, then how size() can return something different than 0 and 1, the logic should be simplified to isNotEmpty
And limit here should be a constant

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionDetails.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8h-6TU6Rprkq1puth4:-N8h-6TVCyHP2muPLh1-:b-px9r06) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionDetails.java#L20)):*
> ```Java
> @OwnedBy(CDP)
> @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
> public interface ExecutionDetails extends ReadConverter, WriteConverter {}
> ```

If it's gonna be converted to binary, should we register ti to kryo?
the same for implementations.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8hFovsBPh6L9quCJvL:-N8hFovsBPh6L9quCJvM:b-dile0u) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java#L37)):*
> ```Java
>   @Override
>   public UpdateResult updateStatus(Scope scope, String stageExecutionId, StageStatus status) {
>     Criteria criteria = createScopeCriteria(scope).and(StageExecutionInfoKeys.serviceIdentifier).is(stageExecutionId);
> ```

StageExecutionInfoKeys.stageExecutionId

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 7 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionDetails.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8h-6TU6Rprkq1puth4:-N8hBjkj04q602Wce4BA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionDetails.java#L20)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

If it's gonna be converted to binary, should we register ti to kryo?
the same for implementations. 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionInfoKey.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8ggB4yAWHZWgLLChWA:-N8hBkXkBasAeQDRtN84:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/ExecutionInfoKey.java#L28)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

what's the `customDeploymentKey` ? can we have it as deploymentIdentifier just to be consistent
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gp5ik5iPU8xoDkucP:-N8hGoHYAqWmPC1b5nni:bbvxjdf) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L36)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Wouldn't it make more sense to have a mapper class that will map all details to ExecutionDetails?  Helper class doesn't really make sense for this purpose
</blockquote></details>

Initially, it was mapper, but after thinking I decided to put mapping and saving logic in helper. The reason is, that we have two Infrastructure steps and in both, we have to have two actions, mapping, and saving, almost the same code, hence separating it in the new class, one place. Also, Tudor mentioned that you have to update execution details logic in a step which should be done in this new class, all of these signal to me to put in a separate class. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gi-Fd1nWwPs9ymc8B:-N8hC-oZCZ9PjwzJAZtO:b-9o28mn) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/service/StageExecutionInfoServiceImpl.java#L70)):*
> limit is always one
Correct, "limit is always one" hence if something different than 1 is 0, opposite what you suggested, the outcome is the same,  however, I see it is confusing,  updated logic. 

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8giXll7jyyrFrYp0t4:-N8hELC--b6ILiBUamV5:b-azzttd) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/sshwinrm/SshWinRmStageExecutionDetails.java#L27)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

nit: need to see if we can store variables also
</blockquote></details>

It will be added in the next PR specific for SSH/WinRm rollback. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gdVhe95wwRLza5Qfd:-N8hEnSn7a8u6-LmfblZ:bcbj259) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L108)):*
> StageExecutionHelper

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8ge9YVEuPAB7OGYxzC:-N8hT429-UmrwVjt6q__:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java#L36)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Scope is not used here.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8hFovsBPh6L9quCJvL:-N8hGYrf-LTSi9hw-0o8:bduy4l9) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/repositories/executions/StageExecutionInfoRepositoryCustomImpl.java#L37)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

StageExecutionInfoKeys.stageExecutionId
</blockquote></details>

Good catch. 

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gf6rBELOU_xKt4TV9:-N8hGim-4bMsJ5ZfmvBL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/test/java/io/harness/cdng/infra/steps/InfrastructureStepTest.java#L121)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

StageExecutionHelper stageExecutionHelper;
</blockquote></details>

Done

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 1 change requests. 4. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 9 of 16 files at r1, 3 of 6 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 3. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gp5ik5iPU8xoDkucP:-N8hUYU67mBsQby3TI44:bu6c8gg) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L36)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Initially, it was mapper, but after thinking I decided to put mapping and saving logic in helper. The reason is, that we have two Infrastructure steps and in both, we have to have two actions, mapping, and saving, almost the same code, hence separating it in the new class, one place. Also, Tudor mentioned that you have to update execution details logic in a step which should be done in this new class, all of these signal to me to put in a separate class. 
</blockquote></details>

Yes, but update execution logic anyway will require a new method. It's just that this helper doesn't really make sense for me and it may result to a god class in future from previous experience, but I'll let it go if you really think that there is no other option

**Review by abosii-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 3. unresolved discussions.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: :shipit: complete! ✓

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: 8 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/36060#-N8gp5ik5iPU8xoDkucP:-N8i4g1B6RW6Uy8zQPgH:b-smcd14) ([raw file](https://github.com/harness/harness-core/blob/3759e8286b91878962197200bdff5649fe88057a/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L36)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Yes, but update execution logic anyway will require a new method. It's just that this helper doesn't really make sense for me and it may result to a god class in future from previous experience, but I'll let it go if you really think that there is no other option
</blockquote></details>

Right, I exposed ExecutionKeyInfo to the mapper, execution details depend on injected beans not able to expose to the utility class.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36060)* status: :shipit: complete! ✓

**Pull request merged**
