### PR TITLE
feat: [PIE-3091]: List apis for env group

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 166 at r1](https://reviewable.io/reviews/harness/harness-core/31580#-MyezqZ-0SdnaN0DMiiU:-MyezqZ-0SdnaN0DMiiV:b2afumh) ([raw file](https://github.com/harness/harness-core/blob/21473ffd491ed959179e547a0c1a47de981aa8d3/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L166)):*
> ```Java
>   @Path("/list")
>   @ApiOperation(value = "Gets Environment Group list", nickname = "getEnvironmentGroupList")
>   @Operation(operationId = "getEnvironmentGroupList", summary = "Gets Environment Group list for a project",
> ```

nit, Project P capital
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 188 at r1](https://reviewable.io/reviews/harness/harness-core/31580#-Myf0M50CjEJ24XfAGIU:-Myf0M510PWzt-oWoeM7:b-yyt2wb) ([raw file](https://github.com/harness/harness-core/blob/21473ffd491ed959179e547a0c1a47de981aa8d3/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L188)):*
> ```Java
>           description =
>               "Specifies sorting criteria of the list. Like sorting based on the last updated entity, alphabetical sorting in an ascending or descending order")
>       @QueryParam("sort") List<String> sort,
> ```

can sort list be an enum? How will customer figure out the sort criteria from string type?

ProjectResource uses an enum.

Also, keep the sort description consistent. It should come from an already defined constant

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 188 at r1](https://reviewable.io/reviews/harness/harness-core/31580#-Myf0M50CjEJ24XfAGIU:-Myf4qww4BuPji_sortC:bacupzn) ([raw file](https://github.com/harness/harness-core/blob/21473ffd491ed959179e547a0c1a47de981aa8d3/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L188)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

can sort list be an enum? How will customer figure out the sort criteria from string type?

ProjectResource uses an enum.

Also, keep the sort description consistent. It should come from an already defined constant
</blockquote></details>

@vaibhav-si In many places, we are using list of string for sort like InputSetResourcePMS, PipelineResource, EnvironmentResourceV2. I added string just be consistent with the current  code base

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 188 at r1](https://reviewable.io/reviews/harness/harness-core/31580#-Myf0M50CjEJ24XfAGIU:-Myg6phS-dfcNI_jxT4s:b-fhyn7g) ([raw file](https://github.com/harness/harness-core/blob/21473ffd491ed959179e547a0c1a47de981aa8d3/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L188)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

@vaibhav-si In many places, we are using list of string for sort like InputSetResourcePMS, PipelineResource, EnvironmentResourceV2. I added string just be consistent with the current  code base
</blockquote></details>

@hextechpal What do you think? I find the way ProjectResource is using SortOrder.class better than ours. That seems more user-friendly to me.

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 10 of 11 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580#-:-Myk0u-VAKTaHGcCdJI-:bnfp4nl)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: 4 file(s) to review. 2 change requests. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 185 at r3](https://reviewable.io/reviews/harness/harness-core/31580#-Myk-g191fSU0VdklQUd:-Myk-g191fSU0VdklQUe:b-sx1gty) ([raw file](https://github.com/harness/harness-core/blob/2dcd32158bfaf03af05b7fcf8972509b31f80f26/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L185)):*
> ```Java
>     if (isEmpty(pageRequest.getSortOrders())) {
>       SortOrder order =
>           SortOrder.Builder.aSortOrder().withField(EnvironmentGroupKeys.createdAt, SortOrder.OrderType.DESC).build();
> ```

should be lastUpdatedBy desc



_Suggestion:_
```Java
createdAt
```
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 127 at r3](https://reviewable.io/reviews/harness/harness-core/31580#-Myk04qH7XMKCQEOJNok:-Myk04qH7XMKCQEOJNol:b-f2otvv) ([raw file](https://github.com/harness/harness-core/blob/2dcd32158bfaf03af05b7fcf8972509b31f80f26/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L127)):*
> ```Java
>     if (!nonExistentEnvIds.isEmpty()) {
>       throw new InvalidRequestException(String.format(
>           "Some environment identifiers are either deleted or not present for this project %s", nonExistentEnvIds));
> ```

Can we name which env are deleted in error message



_Code quote:_
```Java
Some environment identifiers
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: 4 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 185 at r3](https://reviewable.io/reviews/harness/harness-core/31580#-Myk-g191fSU0VdklQUd:-Myk4wxv2icNO9ThVq3O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2dcd32158bfaf03af05b7fcf8972509b31f80f26/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L185)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should be lastUpdatedBy desc
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 127 at r3](https://reviewable.io/reviews/harness/harness-core/31580#-Myk04qH7XMKCQEOJNok:-Myk4w0yBjp2-hjpfd1T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2dcd32158bfaf03af05b7fcf8972509b31f80f26/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L127)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we name which env are deleted in error message
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580#-:-MykJk6y9oiw3cxQgYG6:bnfp4nl)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31580)* status: :shipit: complete! ✓

**Pull request merged**
