### PR TITLE
[feat]: [CDS-80991]: Enhanced error when the connector is not found

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Enhanced error handling when the connector is not found. Have tested out the change locally, working as expected.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/53829#-Ng391XVEe0g5QWk-6fb:-Ng391XVEe0g5QWk-6fc:bq0m2ie) ([raw file](https://github.com/harness/harness-core/blob/4df8edf54149e821d451718cf642ca4e98ac364c/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L188)):*
> ```Java
>       log.error(String.format("Could not find the connector %s in the account %s.", connectorRef, accountIdentifier),
>           connectorNotFoundException);
>       gitXWebhookEventService.updateEvent(accountIdentifier, eventIdentifier,
> ```

Updation of event should be happening centrally, not for each call. Lets check if we can add some central management to such things.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/53829#-Ng391XVEe0g5QWk-6fb:-Ng3Fcj57-luWdQHqy_2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65020fd8d618c00436678d90f5914453c65f9779/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L188)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Updation of event should be happening centrally, not for each call. Lets check if we can add some central management to such things.
</blockquote></details>

Done.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/53829#-Ng391XVEe0g5QWk-6fb:-Ng3IY9CCtnbdBi8uXFK:b-67nq2k) ([raw file](https://github.com/harness/harness-core/blob/65020fd8d618c00436678d90f5914453c65f9779/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L188)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I mean instead of catching exception here and updating the status, it should be done at only selected places.

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/53829#-Ng391XVEe0g5QWk-6fb:-Ng3JwKkA33bqYuVoJeu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65020fd8d618c00436678d90f5914453c65f9779/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L188)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No, I mean instead of catching exception here and updating the status, it should be done at only selected places.
</blockquote></details>

Done.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1YlBDte2fNzNlRDk:-NgL1YlBDte2fNzNlRDl:bfkn38c) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L186)):*
> ```Java
>       return gitSyncConnectorHelper.getDecryptedConnectorForNewGitX(accountIdentifier, "", "", scmConnector);
>     } catch (ConnectorNotFoundException connectorNotFoundException) {
>       log.error(String.format("Could not find the connector %s in the account %s.", connectorRef, accountIdentifier),
> ```

do we need to catch it here? Can't we simply let it throw back to outer exception block, log it there and simply handle it?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1ee5CYxSh1sMEEbJ:-NgL1ee5CYxSh1sMEEbK:bnl4wd2) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L114)):*
> ```Java
>       } catch (Exception exception) {
>         updateEventStatus(gitXWebhookEvent.getAccountIdentifier(), gitXWebhookEvent.getEventIdentifier(),
>             GitXWebhookEventStatus.FAILED, null);
> ```

everywhere I see last argument is "null". Can we create another overloaded method that just takes the required arguments, otherwise it looks pretty messy and unreadable for now.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1nE0BPXt9jb9kHf5:-NgL1nE0BPXt9jb9kHf6:b-9uorsu) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L112)):*
> ```Java
>               GitXWebhookEventStatus.PROCESSING, processingFilePaths);
>         }
>       } catch (Exception exception) {
> ```

log exception here

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 113 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1p2E6nqdSXdxWB6e:-NgL1p2E6nqdSXdxWB6f:b-j1v66o) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L113)):*
> ```Java
>         }
>       } catch (Exception exception) {
>         updateEventStatus(gitXWebhookEvent.getAccountIdentifier(), gitXWebhookEvent.getEventIdentifier(),
> ```

this call itself can fail. lets put it into try catch and add log here.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1nE0BPXt9jb9kHf5:-NgMf_aX4GYF8QYLib-o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L112)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

log exception here
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 113 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1p2E6nqdSXdxWB6e:-NgMfpIz0ja0nUZfSFLe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L113)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this call itself can fail. lets put it into try catch and add log here.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1ee5CYxSh1sMEEbJ:-NgMh-r59uWZ5RA-LZtr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L114)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

everywhere I see last argument is "null". Can we create another overloaded method that just takes the required arguments, otherwise it looks pretty messy and unreadable for now.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/53829#-NgL1YlBDte2fNzNlRDk:-NgMgNNS9hZVx2IARaPc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ae6bdbe0cb7ca844bf9c136c665ee613f178d8b4/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/runnable/GitXWebhookProcessorRunnable.java#L186)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

do we need to catch it here? Can't we simply let it throw back to outer exception block, log it there and simply handle it?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53829)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger ut7, ut8, ut9

**Pull request merged**
