### PR TITLE
feat: [PL-22619]: Remove Resource Group V1 in V2

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32558)

### CODE REVIEW

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32558#-:-N2ALQSsEan26AR1yeXn:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by reetika04** [comment]
trigger checkstyle

**Comment by reetika04** [comment]
trigger checkstyle

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32558#-:-N2ENKQFA-KGXdvWrBWR:bnfp4nl)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32558)* status: 10 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32558#-:-N2FNsNV9gUNjnKhOEXL:bnfp4nl)* status: 10 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32558#-:-N2FRYAj6PxBHWQE5uw4:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
