### PR TITLE
[fix]: [CI-3723]: Updated jwt-go dependency

### PR DESCRIPTION
**Pull request by devkimittal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31288)

### CODE REVIEW

**Comment by devkimittal** [comment]
trigger ti2

**Comment by devkimittal** [comment]
trigger ti3

**Comment by devkimittal** [comment]
trigger ti0

**Comment by devkimittal** [comment]
trigger ti3

**Comment by devkimittal** [comment]
trigger ti0

**Comment by devkimittal** [comment]
trigger ti0

**Comment by devkimittal** [comment]
trigger ti2

**Comment by devkimittal** [comment]
trigger ti3

**Comment by devkimittal** [comment]
trigger messagecheck

**Review by aman-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31288#-:-My6f3MB7lpRcBlnmedL:bnfp4nl)* status: Some of the checks are too old.

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31288#-:-My6fDSz8t_B5Xsiqcmj:bnfp4nl)* status: Some of the checks are too old.

**Comment by devkimittal** [comment]
trigger compile

**Comment by devkimittal** [comment]
trigger messagecheck

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31288#-:-My6zgWj3BtGFLoImdqc:bnfp4nl)* status: Some of the checks are too old.

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31288#-:-My6zktG62YuVcI4I4UI:bnfp4nl)* status: Some of the checks are too old.

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31288#-:-My81NAHCEcSKvck6uhw:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
