### PR TITLE
fix: [CDS-34327]: fix RBAC for infrastructures CRUD

### PR DESCRIPTION
**Pull request by hingerabhinav**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33191)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33191)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33191#-N2BfZPl92ABBdt6CZgx:-N2BfZPmCpGE6pLm_fLM:b-3ro98u) ([raw file](https://github.com/harness/harness-core/blob/78f382cba679b18aaad625d891f8fca86fa13352/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L220)):*
> ```Java
>       checkForAccessOrThrow(accountId, infrastructureRequestDTO.getOrgIdentifier(),
>           infrastructureRequestDTO.getProjectIdentifier(), infrastructureRequestDTO.getEnvIdentifier(),
>           ENVIRONMENT_UPDATE_PERMISSION, "create");
> ```

we do not need to check this in a loop. maybe get all envs at once and loop over them or have some caching to make sure we do not do repeated calls

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33191)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33191#-N2BfZPl92ABBdt6CZgx:-N2BpgOcDyE2S0Q1YgYZ:bhw22l6) ([raw file](https://github.com/harness/harness-core/blob/78f382cba679b18aaad625d891f8fca86fa13352/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L220)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need to check this in a loop. maybe get all envs at once and loop over them or have some caching to make sure we do not do repeated calls
</blockquote></details>

this API takes in a list of infra DTOs each of which can have different org, project also. I'm seeing how we can implement caching here.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33191)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33191#-N2BfZPl92ABBdt6CZgx:-N2C7yj09DdnpV2xiXj9:bw310v2) ([raw file](https://github.com/harness/harness-core/blob/78f382cba679b18aaad625d891f8fca86fa13352/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L220)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

this API takes in a list of infra DTOs each of which can have different org, project also. I'm seeing how we can implement caching here. 
</blockquote></details>

is there a use case for that ? Does it make sense to only have an API that allows bulk creation of infra for 1 env.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33191)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33191#-N2BfZPl92ABBdt6CZgx:-N2FuDjjAp5R2pcq4pQ-:budzt84) ([raw file](https://github.com/harness/harness-core/blob/78f382cba679b18aaad625d891f8fca86fa13352/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L220)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is there a use case for that ? Does it make sense to only have an API that allows bulk creation of infra for 1 env. 
</blockquote></details>

Got it. API is hidden from OpenAPI and available in swagger. Will do a postman test once in PR env.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33191)* status: :shipit: complete! ✓

**Pull request merged**
