### PR TITLE
[feat]: [CDS-47032] Asg Rolling Rollback - Manager Changes

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Added implementation for asg ng rolling rollback manager side changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)

### CODE REVIEW

**Review by vitsafronovici — DISMISSED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)* status: :shipit: complete! ✓

**Comment by lovish1999** [comment]
trigger messagecheck

**Review by vitsafronovici — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)* status: 37 file(s) to review. 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 234 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJzmrnU2yKGwnFgX1JG:-NJzmrnU2yKGwnFgX1JH:b-xz40x2) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L234)):*
> ```Java
>       "Asg Rolling Deploy", Arrays.asList(ServiceDefinitionType.ASG), "ASG", StepSpecTypeConstants.ASG_ROLLING_DEPLOY),
>   @JsonProperty(StepSpecTypeConstants.ASG_ROLLING_ROLLBACK)
>   ASG_ROLLING_ROLLBACK("Asg Rolling Deploy", Arrays.asList(ServiceDefinitionType.ASG), "ASG",
> ```

rename - Asg Rolling Rollback

**Comment by arvind-choudhary-h** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgRollingRollbackResult.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJznKKo0F-f3zsNbYRw:-NJznKKo0F-f3zsNbYRx:b-szhvhh) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgRollingRollbackResult.java#L20)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public class AsgRollingRollbackResult {
>   private String region;
> ```

why do we need region?

**Comment by arvind-choudhary-h** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgRollingRollbackResult.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJznKKo0F-f3zsNbYRw:-NJznPHQCZLXJ76BdRB8:b-egvf0v) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgRollingRollbackResult.java#L20)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

why do we need region?
</blockquote></details>

and infrastructureKey?

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgRollingRollbackBaseStepInfo.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJznoqg78G_lPQP2CEw:-NJznoqg78G_lPQP2CEx:b-5iqu1t) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgRollingRollbackBaseStepInfo.java#L37)):*
> ```Java
>   ParameterField<List<TaskSelectorYaml>> delegateSelectors;
> 
>   @JsonIgnore String asgRollingRollbackFqn;
> ```

what is this field? who sets it?

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 28 of 31 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)* status: 1 of 2 approvals obtained.

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)* status: 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 234 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJzmrnU2yKGwnFgX1JG:-NK1bQldBR1jV9nApRIq:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L234)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

rename - Asg Rolling Rollback
</blockquote></details>

Ok
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgRollingRollbackResult.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJznKKo0F-f3zsNbYRw:-NK1bS9T1lMh-SvQsDTm:bdje73a) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgRollingRollbackResult.java#L20)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

and infrastructureKey?
</blockquote></details>

They are needed in ECS for getting some server instance info. I will remove it for now if not needed for us.

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)* status: 10 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgRollingRollbackBaseStepInfo.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/41968#-NJznoqg78G_lPQP2CEw:-NKHCLCDCwKtkAKgROBa:bkhhaxa) ([raw file](https://github.com/harness/harness-core/blob/754362c5093a57db28eeca5ff57a1a7ffb568ef0/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgRollingRollbackBaseStepInfo.java#L37)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

what is this field? who sets it?
</blockquote></details>

My Bad, I have added the implementation & modification now. It is set in the stepplancreator class.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by arpit3107 — APPROVED** [review]
Approving only for 260-delegate module as codeOwner

> Reviewed 21 of 31 files at r1, 8 of 9 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41968#-:-NKIdqTvExTwWQalTke0:b4y18jm)* status: :shipit: complete! ✓

**Pull request merged**
