### PR TITLE
[feat]: [PIE-4653]: Integrate the expression mode with evaluateExpression

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36209)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36209)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36209)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java` line 247 at r2](https://reviewable.io/reviews/harness/harness-core/36209#-N91ikp46u4pH-3OX1Cl:-N91ikp46u4pH-3OX1Cm:by3d5pg) ([raw file](https://github.com/harness/harness-core/blob/d4d9612544972a47a796a39a3b88662a75bbb349/980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java#L247)):*
> ```Java
>   //  private Object evaluateExpressionInternal(@NotNull String expression, @NotNull EngineJexlContext ctx, int depth) {
>   //    return evaluateExpressionInternal(expression,ctx,depth, ExpressionMode.RETURN_NULL_IF_UNRESOLVED);
>   //  }
> ```

delete comments



_Code quote:_
```Java
  //  private Object evaluateExpressionInternal(@NotNull String expression, @NotNull EngineJexlContext ctx, int depth) {
  //    return evaluateExpressionInternal(expression,ctx,depth, ExpressionMode.RETURN_NULL_IF_UNRESOLVED);
  //  }
```

**Comment by brijeshdhakar** [comment]
*[`980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java` line 247 at r2](https://reviewable.io/reviews/harness/harness-core/36209#-N91ikp46u4pH-3OX1Cl:-N9373ffDFsDIzQ7gUIm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d4d9612544972a47a796a39a3b88662a75bbb349/980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java#L247)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

delete comments
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36209)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ti2

**Pull request closed without merging**
