### PR TITLE
fix: [PL-16770]: yaml resource delete v2

### PR DESCRIPTION
**Pull request by abhinav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)

Screenshot 2022-03-02 at 2 22 12 AM

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/yaml/FilePathWithSubtype.java, line 10 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIMmZ-5uTtpunoq4ns:-MxIMmZ-5uTtpunoq4nt:b-dc6kz1) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/beans/yaml/FilePathWithSubtype.java#L10)):*
> ```Java
> public class FilePathWithSubtype {
>   String filePath;
>   String yamlSubtype;
> ```

Whether the customers are fine with sending the yamlSubType ?
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1146 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIMzI45PYnQrhkiqOO:-MxIMzI45PYnQrhkiqOP:bb1119w) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1146)):*
> ```Java
>       final String accountId, final List<FilePathWithSubtype> filePathsWithSubtype) {
>     try {
>       List changeList = filePathsWithSubtype.stream()
> ```

emptyIfNull check
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1146 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIN1TwA7OnKiStDNnB:-MxIN1TwA7OnKiStDNnC:b-nvs9e6) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1146)):*
> ```Java
>       final String accountId, final List<FilePathWithSubtype> filePathsWithSubtype) {
>     try {
>       List changeList = filePathsWithSubtype.stream()
> ```

List  -> List<GitFileChange>
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1147 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIN8skAC5OS3RDdiez:-MxIN8skAC5OS3RDdif-:b-vk1orn) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1147)):*
> ```Java
>     try {
>       List changeList = filePathsWithSubtype.stream()
>                             .map(filePath -> {
> ```

filePath -> filePathInfo 

the filePath variable felt like it is a string but it is actually not

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1146 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIN1TwA7OnKiStDNnB:-MxiIYNdCRbtOdsASh1R:b-icbtwq) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1146)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

List  -> List<GitFileChange>
</blockquote></details>

didnt get
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1146 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIMzI45PYnQrhkiqOO:-MxiIZkpBoAeuJn8iZ5a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1146)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

emptyIfNull check
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1147 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIN8skAC5OS3RDdiez:-MxiIXdr2HAB0erBXGrV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1147)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

filePath -> filePathInfo 

the filePath variable felt like it is a string but it is actually not
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/beans/yaml/FilePathWithSubtype.java, line 10 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIMmZ-5uTtpunoq4ns:-MxiIa4K6DpzywVuROrX:bf0fqdg) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/beans/yaml/FilePathWithSubtype.java#L10)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Whether the customers are fine with sending the yamlSubType ?
</blockquote></details>

discussed with mica and modified

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1146 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIN1TwA7OnKiStDNnB:-MxixtE04y3Cc1UIghbK:bubfrss) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1146)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

didnt get
</blockquote></details>

List -> List<ChangeSet>  like I meant to add the type in the list

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java, line 1146 at r1](https://reviewable.io/reviews/harness/harness-core/31103#-MxIN1TwA7OnKiStDNnB:-Mxp1pCu4OnJJkHH4p5i:b-q8jzb0) ([raw file](https://github.com/harness/harness-core/blob/cf357f1dac03770e947f777480cdceba64ec7ffc/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1146)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

List -> List<ChangeSet>  like I meant to add the type in the list
</blockquote></details>

got it

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31103)* status: :shipit: complete! ✓

**Pull request merged**
