### PR TITLE
[fix]: [CDS-79529]: Update polling subscribe method method

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
## Describe your changes
Inorder to know if the existing pollingDoc is assigned to a trigger we have modified save method in pollingServiceImpl

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54204)

### CODE REVIEW

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger ut8,ut5,ut7

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/54204#-Ngxj17n6NV_GwMtuBmQ:-Ngxj17n6NV_GwMtuBmR:b-9o1jm8) ([raw file](https://github.com/harness/harness-core/blob/9fde8771bb907701044ef3e54be73cf5e37c7dce/125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java#L72)):*
> ```Java
>         pollingDocument.getSignaturesLock());
>     if (savedPollingDoc != null) {
>       lastPollingUpdate = savedPollingDoc.getLastModifiedPolledResponseTime() == null
> ```

can we return directly from here?

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54204)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java` line 72 at r3](https://reviewable.io/reviews/harness/harness-core/54204#-Ngxj17n6NV_GwMtuBmQ:-NgxoB1Q20ulEVpkLArp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9fde8771bb907701044ef3e54be73cf5e37c7dce/125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java#L72)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

can we return directly from here?
</blockquote></details>

Done.

**Comment by rathodmeetsatish** [comment]
trigger uts

**Comment by rathodmeetsatish** [comment]
trigger ut9

**Review by sribalij — APPROVED** [review]

**Comment by rathodmeetsatish** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54204)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java` line 65 at r4](https://reviewable.io/reviews/harness/harness-core/54204#-Ngyi5Lh2W8tqA3OS4W_:-Ngyi5Lh2W8tqA3OS4Wa:b871b7a) ([raw file](https://github.com/harness/harness-core/blob/4f416c4ec545296321b0481a032e795c24063d9f/125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java#L65)):*
> ```Java
>   public PollingResponseDTO save(PollingDocument pollingDocument) {
>     List<String> lastPolled = new ArrayList<>();
>     Long lastPollingUpdate = null;
> ```

nit: for develop
Is this required?

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54204)* status: 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java` line 65 at r4](https://reviewable.io/reviews/harness/harness-core/54204#-Ngyi5Lh2W8tqA3OS4W_:-Ngyinct9BLNCVxXei3o:b97ez7z) ([raw file](https://github.com/harness/harness-core/blob/4f416c4ec545296321b0481a032e795c24063d9f/125-cd-nextgen/src/main/java/io/harness/polling/service/impl/PollingServiceImpl.java#L65)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: for develop
Is this required?
</blockquote></details>

yes its not required will remove in next pr will merge these changes for now

**Pull request merged**
