### PR TITLE
fix: [CDS-40449]: Ignore get tool path exception

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Current behavior is to throw an exception if tool doesn't exists. This is the right behavior because we would like to fail fast if any required tool doesn't exists for deployment. The problem is with if customer want to use a delegate with no tools and install only tools that are required for deployment. This should be a temporary solution to unblock the customer as the quickest and safest solution, further changes are required to use only tools that are required for specific manifest type.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Review by GoelPratyush99 — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/35580#-N7V7dJN9MAeYIjY7PRx:-N7V7dJN9MAeYIjY7PRy:b-udnc0m) ([raw file](https://github.com/harness/harness-core/blob/30aefb7c612ec64d741c3e41ab57c0707dcea779/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L102)):*
> ```Java
>       // required tools. We should improve our logic to fetch only tools that are required for a specific
>       // deployment/manifest type
>       log.warn("Failed to get tool path", e);
> ```

assuming that the exact tool is also logged here in case of an exception

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

**Review by GoelPratyush99 — DISMISSED** [review]

**Review by GoelPratyush99 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: 1 file(s) to review.

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: 1 file(s) to review. 

___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/35580#-N7V7dJN9MAeYIjY7PRx:-N7V96fy3jd5QuquXQHV:bfdh4ol) ([raw file](https://github.com/harness/harness-core/blob/30aefb7c612ec64d741c3e41ab57c0707dcea779/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L102)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

assuming that the exact tool is also logged here in case of an exception
</blockquote></details>

the original error that we try to handle here does, but it's a good point to mention tool and version in case if there is a different error

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/35580#-N7_TzDcBVE2zuPD4Ocq:-N7_TzDg-1Jc-6O7s7hU:b-efb8v) ([raw file](https://github.com/harness/harness-core/blob/c496239269776de6228bda1c61806a87fea2a786/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L104)):*
> ```Java
>       log.warn("Failed to get tool path for {} and version {}. Failing to default value: {}", tool.getBinaryName(),
>           version.getVersion(), tool.getBinaryName(), e);
>       return tool.getBinaryName();
> ```

I'm inclined to approve the PR to unblock customers, but just think it's worth mentioning:
The fallback path is never going to be valid, if the tool vas accessible with binary name (i.e. is on $PATH) delegate would find it and give you that path. This can lead to weird failures when e.g. customer has no tools image and doesn't put any tool, but runs a K8S task. I think it would fail with "command not found" or some such exception during execution. 
You should really look into making a proper fix soon as mentioned in your comment.

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35580)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/35580#-N7_TzDcBVE2zuPD4Ocq:-N7_b8kJEG_Vr1ReN68A:buzs9qr) ([raw file](https://github.com/harness/harness-core/blob/c496239269776de6228bda1c61806a87fea2a786/960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java#L104)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I'm inclined to approve the PR to unblock customers, but just think it's worth mentioning:
The fallback path is never going to be valid, if the tool vas accessible with binary name (i.e. is on $PATH) delegate would find it and give you that path. This can lead to weird failures when e.g. customer has no tools image and doesn't put any tool, but runs a K8S task. I think it would fail with "command not found" or some such exception during execution. 
You should really look into making a proper fix soon as mentioned in your comment. 
</blockquote></details>

Yes, we're going to get the tools only required current type of deployment. We didn't go ahead with this in first place just because it would require more testing around this. Fallback is more to give at least for the customer the idea which binary failed, because without this it was failing only with arguments, for example: template .. instead of helm template

**Pull request merged**
