### PR TITLE
feat: [PL-29104]: add support to filter approval alerts by appID

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
The previous behavior did not filter the approval alerts displayed on this tab, as shown in the image below.
image
Changes to this pr make the filter so that only alert and approval notifications appear for those who have permission to the application.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42018)

### CODE REVIEW

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42018)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/dl/WingsMongoPersistence.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/42018#-NKNo-Dw4LP-g_WNd8dF:-NKNo-Dw4LP-g_WNd8dG:bzexc23) ([raw file](https://github.com/harness/harness-core/blob/d0018eb19f61f2f67631a3a151f6ee123e4d3f58/400-rest/src/main/java/software/wings/dl/WingsMongoPersistence.java#L107)):*
> ```Java
>   }
> 
>   public static final String GLOBAL_APP_ID = "__GLOBAL_APP_ID__";
> ```

Follow the convention and declare class variables at the beginning of the class.

Do we already have these values declared in some other class?

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42018)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/dl/WingsMongoPersistence.java` line 107 at r2](https://reviewable.io/reviews/harness/harness-core/42018#-NKNo-Dw4LP-g_WNd8dF:-NKNqIAM67REYRtIqBK2:be74cf4) ([raw file](https://github.com/harness/harness-core/blob/d0018eb19f61f2f67631a3a151f6ee123e4d3f58/400-rest/src/main/java/software/wings/dl/WingsMongoPersistence.java#L107)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Follow the convention and declare class variables at the beginning of the class.

Do we already have these values declared in some other class?
</blockquote></details>

I added both vars in constant file.

**Review by rafaelmart1ns — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42018)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42018)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by rafaelmart1ns** [comment]
trigger feature-build

**Comment by rafaelmart1ns** [comment]
trigger feature-build

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42018)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
