### PR TITLE
[feat]: [PIE-3869]: Summary, Description Clean up for Pipeline APIs

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
[feat]: [PIE-3869]: Summary, Description Clean up for Pipeline APIs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

[PIE-3869]: https://harness.atlassian.net/browse/PIE-3869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33986)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33986)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33986)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 374 at r3](https://reviewable.io/reviews/harness/harness-core/33986#-N41NW3h0Nqeq87MDnzQ:-N41NW3h0Nqeq87MDnzR:b-a54szd) ([raw file](https://github.com/harness/harness-core/blob/c5cd076e63aa1f745aa6d6f9ae4e7827c41918b8/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L374)):*
> ```Java
>   @Operation(operationId = "postPipelineExecuteWithInputSetList",
>       description = "Executes a Pipeline with Input Set References List",
>       summary = "Execute a Pipeline (Input Set References List)",
> ```

Execute a Pipeline with Input Set References

**Comment by mankrit-singh** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 114 at r3](https://reviewable.io/reviews/harness/harness-core/33986#-N41Mr4L3XdSyGd5mINS:-N41OH7hD1-SziZ5wU6T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5cd076e63aa1f745aa6d6f9ae4e7827c41918b8/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L114)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

let's remove CRUD.
This contains APIs related to Setup of Pipelines.
</blockquote></details>

Done.

**Comment by mankrit-singh** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/33986#-N41NRB5A8KJ2_RL8L-u:-N41OKc9-ewf-zggbcuF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5cd076e63aa1f745aa6d6f9ae4e7827c41918b8/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L132)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Execute a Pipeline with Runtime Input YAML
</blockquote></details>

Done.

**Comment by mankrit-singh** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 374 at r3](https://reviewable.io/reviews/harness/harness-core/33986#-N41NW3h0Nqeq87MDnzQ:-N41OMIF1rCL2OseRHaK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5cd076e63aa1f745aa6d6f9ae4e7827c41918b8/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L374)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Execute a Pipeline with Input Set References
</blockquote></details>

Done.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33986)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33986)* status: :shipit: complete! ✓

**Pull request merged**
