### PR TITLE
feat: [SRM-11174]: Added support for new Pipeline yaml by adding resolution…

### PR DESCRIPTION
**Pull request by arpit-harness**
… for service: and environment: in new yaml

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35785)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35785)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepUtils.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/35785#-N8-MUa5EN6-OC4_eM3v:-N8-MUa5EN6-OC4_eM3w:bxmjsui) ([raw file](https://github.com/harness/harness-core/blob/20f6ec44868f36734aa177e12a720259eeef1d0f/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepUtils.java#L52)):*
> ```Java
>       return serviceKey.getNode().getField(SERVICE_REF_KEY).getNode();
>     } else {
>       return serviceConfigKey.getNode().getField(SERVICE_REF_KEY).getNode();
> ```

Can we put this whole block in try block and print the exception along with the actual stage yaml just in case a new variant is introduced.

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35785)* status: :shipit: complete! ✓

**Pull request merged**
