### PR TITLE
feat: [CDS-31886]: notification for approval or rejection action in approval step

### PR DESCRIPTION
**Pull request by sourabh-awashti**
Approval or rejection action notification for approval step
Tests Done:- 
1. Approval and rejection action for single and multi user notification
2. Approval and rejection without pipeline execution details notification.

Screenshots with sample notifications for email/slack/MS teams
https://harness.atlassian.net/browse/CDS-31886?focusedCommentId=497626

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)

### CODE REVIEW

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/47890#-NVdE2sW4wDnrPnwDuOa:-NVdE2sW4wDnrPnwDuOb:b-h7lmqa) ([raw file](https://github.com/harness/harness-core/blob/79c76c1d49a5a5a9c750f1673e79182e276867da/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java#L119)):*
> ```Java
>       boolean isApprovalAction = ApprovalStatus.APPROVED.equals(approvalInstance.getStatus())
>           || ApprovalStatus.REJECTED.equals(approvalInstance.getStatus());
>       if (isApprovalAction) {
> ```

nit: maybe a better name for isApproval ( because this also handles rejection )

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java` line 322 at r2](https://reviewable.io/reviews/harness/harness-core/47890#-NVdF-3q9D8lQ7Jqahp_:-NVdF-3q9D8lQ7Jqahpa:bn08npp) ([raw file](https://github.com/harness/harness-core/blob/79c76c1d49a5a5a9c750f1673e79182e276867da/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java#L322)):*
> ```Java
>     }
> 
>     switch (notificationSettingConfig.getType()) {
> ```

and this one as well ?

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java` line 275 at r2](https://reviewable.io/reviews/harness/harness-core/47890#-NVdEx4w4U55EKW723vt:-NVdEx4w4U55EKW723vu:b-wzbkkt) ([raw file](https://github.com/harness/harness-core/blob/79c76c1d49a5a5a9c750f1673e79182e276867da/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java#L275)):*
> ```Java
>         ApprovalStatus.APPROVED.equals(instance.getStatus()) || ApprovalStatus.REJECTED.equals(instance.getStatus());
> 
>     if (actionStatus) {
> ```

can we extract this logic out as a method ?

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalSummary.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/47890#-NVdI1KYDkBw4qnJo0hy:-NVdI1KYDkBw4qnJo0hz:b-scqoae) ([raw file](https://github.com/harness/harness-core/blob/79c76c1d49a5a5a9c750f1673e79182e276867da/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalSummary.java#L63)):*
> ```Java
>     params.put(ApprovalSummaryKeys.timeRemainingForApproval, timeRemainingForApproval);
>     params.put(ApprovalSummaryKeys.action, action);
>     params.put(ApprovalSummaryKeys.status, String.valueOf(status).toLowerCase(Locale.ROOT));
> ```

can status be null ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 13 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java` line 332 at r5](https://reviewable.io/reviews/harness/harness-core/47890#-NVhL4yE8WrFyQaTxTaT:-NVhL4yE8WrFyQaTxTaU:bw1sivz) ([raw file](https://github.com/harness/harness-core/blob/725c9066cfbb4ab6520718c6a966d1caef0ae18b/pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java#L332)):*
> ```Java
>       NotificationSettingConfigDTO notificationSettingConfig, UserGroupDTO userGroup, Map<String, String> templateData,
>       NotificationRequest.UserGroup.Builder notifyUserGroupBuilder) {
>     switch (notificationSettingConfig.getType()) {
> ```

nit:This cannot be null I assume?

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 7 of 11 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: :shipit: complete! ✓

**Comment by Jimit09Gandhi** [comment]
@sourabh-awashti  @yogesh-chauhan since its change to contract platform-service/modules/resource-group-service/contracts/src/main/java/io/harness/resourcegroup/v1/remote/dto/ZendeskHelper.java
ensure it is not breaking any thing else in system.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by naman-goenka — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47890)* status: 5 file(s) to review.

**Comment by sourabh-awashti** [comment]
trigger ut7

**Comment by sourabh-awashti** [comment]
trigger review

**Pull request merged**
