### PR TITLE
fix: [PIE-4827]: Fix parameter order in call to SCM service's `CompareCommits` method

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR fixes the params in a call to SCM service `CompareCommits` method within delegate task "ScmPathFilterEvaluationTask". Previously, source (base) and target (head)  commits were being incorrectly swapped in the method's call.

#### Explanation:
The `CompareCommits` method expects to receive both the hash of the "source" commit and the "target" commit. The "target" is the commit with the new changes, to be compared with the state of the previously existing "source" commit. These hashes are further passed to SCM service which in turn calls the specific source repo provider's API (github, bitbucket, etc.) to query for the changes between the two commits.

Just by looking at the signature of the `CompareCommits` method in `ScmServiceClientImpl` one can already see that these two parameters seem to be incorrectly swapped in the call made at `ScmPathFilterEvaluationTask`: https://github.com/harness/harness-core/blob/473e9e410e667b5153bdc2a815a0dfe653ebd1a1/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L770 , because `initialCommitId` comes before `finalCommitId`.

In my tests I confirmed that this is indeed the case, causing SCM Service to return empty changes for all `CompareCommits` calls, because of this wrong arguments order.

##### Requirements:
- Default NG services running (WingsApp, NextGenManager, PipelineService, DelegateApp connected to NG).
- Run LogService `bazel run //product/log-service:log-service server`
- Run SCM Service `bazel build //product/ci/scm/...` and `bazel run //product/ci/scm:scm`
##### Steps:
- Configure a Bitbucket connector in NG.
- Create webhook to trigger a pipeline for push events in bitbucket repo, for a specific branch,for changed files IN "path/to/a/file".
- Push a commit the the branch you selected in the trigger configuration, changing the file you specified.
- Copy to a file named "req.json" the body of the webhook request that bitbucket attempted to send to NG Manager, like this:
image

- Send a curl request to NG manager mocking the webhook call from bitbucket: 
```
curl 'http://localhost:7457/webhook?accountIdentifier=kmpySmUISimoRrJL6NL73w&secret=' -X 'POST' -H 'Content-Type: application/json' -H 'X-B3-Sampled: 1' -H 'X-B3-TraceId: dd687ec95c492a8a' -H 'X-Attempt-Number: 1' -H 'X-Event-Key: repo:push' -H 'X-Request-UUID: 8bbd3e6b-0c6a-4eae-a103-f55e82eae8d1' -H 'User-Agent: Bitbucket-Webhooks/2.0' --data-binary "@req.json"
```
- watch your pipeline being triggered (only works with the changes made in this PR) :slightly_smiling_face: 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36907)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger ti0, ti1, ti2, ft1, ft2, compile

**Comment by vcalasansh** [comment]
trigger ft1,ft2,messagecheck

**Comment by vcalasansh** [comment]
trigger ft1,ft2

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36907)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36907)* status: :shipit: complete! ✓

**Comment by vcalasansh** [comment]
trigger codebasehash

**Comment by vcalasansh** [comment]
trigger codebasehash

**Pull request merged**
