### PR TITLE
fix: [CDS-86705]: Allow expressions as input for paths fields

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
As part of this PR we want to allow users to use expressions to configure arrays type of fields . This will bring some parity with the CG where we allowed comma separated values and customer could use it with expressions.
Example:
```
type: K8sManifest
spec:
  store:
    type: Git
    spec:
      branch: master
      connectorRef: account.Sample_K8s_Manifests
      gitFetchType: Branch
      paths: <+stage.variables.paths>
valuesPaths: <+stage.variables.paths>
```

Harness Schema PR: https://github.com/harness/harness-schema/pull/258
#### Dependencies
For parameter fields to be correctly resolved it does require `CDS_ENABLE_NEW_PARAMETER_FIELD_PROCESSOR` to be enabled

#### Limitations
This will be applicable only for manifests fields (or the case when we manually resolve parameter fields). Currently this doesn't work for step fields, for example for Apply Step.

### Execution example:
Serivce.yaml
```
service:
  name: Service Paths Expression
  identifier: Service_Paths_Expression
  orgIdentifier: default
  projectIdentifier: Kubernetes
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: m1
            type: K8sManifest
            spec:
              store:
                type: Git
                spec:
                  connectorRef: account.Sample_K8s_Manifests
                  gitFetchType: Branch
                  paths: <+<+stage.variables.paths>.split(",")>
                  branch: master
              valuesPaths: <+<+stage.variables.paths>.split(",")>
              skipResourceVersioning: false
              enableDeclarativeRollback: false
        - manifest:
            identifier: vs12
            type: Values
            spec:
              store:
                type: Git
                spec:
                  connectorRef: account.Sample_K8s_Manifests
                  gitFetchType: Branch
                  paths: <+<+stage.variables.paths>.split(",")>
                  branch: master
    type: Kubernetes
```
Fetch Files result:
Screenshot 2023-12-13 at 18 38 45

### Test Cases
- [x] Use K8s Manifest with valuesPaths as array expression
- [x] Use K8s Manifest with Git Store using paths as array expression 
- [x] Use K8s Manifest with Github Store using paths as array expression 
- [x] Use K8s Manifest with Gitlab Store using paths as array expression 
- [x] Use K8s Manifest with Bitbucket Store using paths as array expression 
- [x] Use Kustomize Manifest with kustomizePatches as array expression
- [x] Use Kustomize Manifes with Git Store using paths as array expression 
- [x] Use Kustomize Manifes with Github Store using paths as array expression 
- [x] Use Kustomize Manifes with Gitlab Store using paths as array expression 
- [x] Use Kustomize Manifes with Bitbucket Store using paths as array expression 
- [x] Use Helm Chart Manifest with valuesPaths as array expression
- [x] Use Helm Chart Manifes with Git Store using paths as array expression 
- [x] Use Helm Chart Manifes with Github Store using paths as array expression 
- [x] Use Helm Chart Manifes with Gitlab Store using paths as array expression 
- [x] Use Helm Chart Manifes with Bitbucket Store using paths as array expression 
- [x] Use OpenShift Template Manifest with paramsPaths as array expression
- [x] Use Values.yaml manifest with Git Store using paths as array expression
- [x] Use Values.yaml manifest with Github Store using paths as array expression
- [x] Use Values.yaml manifest with Gitlab Store using paths as array expression
- [x] Use Values.yaml manifest with Bitbucket Store using paths as array expression

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56746)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger checkstylecodeformat, commonchecks, uts

**Comment by abosii-harness** [comment]
trigger checkstylecodeformat, commonchecks, uts

**Comment by abhinavsingh1196** [comment]
> This will be applicable only for manifests fields (or the case when we manually resolve parameter fields). Currently this doesn't work for step fields, for example for Apply Step.

For Apply step, we render expressions manually so it would also work there?

**Review by abhinavsingh1196 — APPROVED** [review]

**Review by markoharness — APPROVED** [review]

**Review by alebuh — APPROVED** [review]

**Comment by abosii-harness** [comment]
trigger review

**Comment by abosii-harness** [comment]
trigger pmd, codebasehash, compileCode

**Comment by abosii-harness** [comment]
trigger compile

**Pull request merged**
