### PR TITLE
feat: [CDS-42872]: linking and referenced by changes for artifact source templates

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 1 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38392)

**Review by inderschera — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 584 at r2](https://reviewable.io/reviews/harness/harness-core/38392#-NDklRWK2Nkc3xBsZYrt:-NDklRWK2Nkc3xBsZYru:b-hk2ps9) ([raw file](https://github.com/harness/harness-core/blob/cfb50d4e80e33eba762ffc67c832c2cf3815c9be/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L584)):*
> ```Java
>         @io.swagger.v3.oas.annotations.responses.ApiResponse(
>             responseCode = "default", description = "Returns all entity references in the artifact source template.")
>       })
> ```

let's mark the api hidden from docs. 
___
*[`125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json` line 403 at r2](https://reviewable.io/reviews/harness/harness-core/38392#-NDgTfL_HlLfY5oKC3KD-r2-403:-NDkltgNEpIha6-vh5nq:b101q6t) ([raw file](https://github.com/harness/harness-core/blob/cfb50d4e80e33eba762ffc67c832c2cf3815c9be/125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json#L403)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

@inderschera we should add name field as mandatory later or now? 
</blockquote></details>

@hingerabhinav name field hasn't been worked upon on UI and BE. Let' make it mandatory after it's supported in both UI and BE. For now, let's not making it required else it would break something.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/PrimaryArtifact.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/38392#-NDknKAL2MXGBUp-N_7x:-NDknKAM1NyXZvCNT1Er:bbn4l0q) ([raw file](https://github.com/harness/harness-core/blob/cfb50d4e80e33eba762ffc67c832c2cf3815c9be/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/PrimaryArtifact.java#L79)):*
> ```Java
>     this.sources = sources;
>     if (EmptyPredicate.isNotEmpty(sources)) {
>       // needed?
> ```

yes, it's required. Eventually when template is resolved, we have to do the same there as well.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntitySetupUsageHelper.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/38392#-NDknxMPBszwcCZkO0Ww:-NDknxMPBszwcCZkO0Wx:b-d7zp7i) ([raw file](https://github.com/harness/harness-core/blob/cfb50d4e80e33eba762ffc67c832c2cf3815c9be/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntitySetupUsageHelper.java#L90)):*
> ```Java
>       String accountId, String orgId, String projectId, String yaml) {
>     GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
>     if (gitEntityInfo != null) {
> ```

for now, we can assume gitEntityInfo will also be null because services doesn't reside in git today.

**Review by inderschera — DISMISSED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/entity/ServiceEntity.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/38392#-NDm6qd4AkBN3XE4lPck:-NDm6qd4AkBN3XE4lPcl:b-90ntkg) ([raw file](https://github.com/harness/harness-core/blob/6baf3b53bb96492495510334a2eac945d348feb9/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/entity/ServiceEntity.java#L117)):*
> ```Java
>   }
> 
>   public Boolean getTemplateReference() {
> ```

- better to return primitive
- maybe method should be hasTemplaterReference()

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/38392#-NDm6hl_AtQUEPyJWJJ6:-NDm6hl_AtQUEPyJWJJ7:b-heipc4) ([raw file](https://github.com/harness/harness-core/blob/6baf3b53bb96492495510334a2eac945d348feb9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java#L53)):*
> ```Java
>         String artifactSourceYaml = YamlUtils.writeYamlString(yaml);
>         return YamlUtils.read(artifactSourceYaml, ArtifactSourceConfig.class);
>       } catch (IOException e) {
> ```

we should log the exception since we are only throwing a message

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 7 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 595 at r3](https://reviewable.io/reviews/harness/harness-core/38392#-NDm6N7Z6XhWCKS5rgWk:-NDm6N7Z6XhWCKS5rgWl:bgq2yem) ([raw file](https://github.com/harness/harness-core/blob/6baf3b53bb96492495510334a2eac945d348feb9/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L595)):*
> ```Java
>       @RequestBody(required = true, description = "Artifact Source Yaml Request DTO containing entityYaml")
>       @NotNull ArtifactSourceYamlRequestDTO artifactSourceYamlRequestDTO) {
>     log.info("Retrieving entity references for Artifact Source Template");
> ```

nit: log is not needed here
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/38392#-NDm6bDH71RE6LxGDQSk:-NDm6bDH71RE6LxGDQSl:b-n5ihxx) ([raw file](https://github.com/harness/harness-core/blob/6baf3b53bb96492495510334a2eac945d348feb9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java#L33)):*
> ```Java
> @Slf4j
> @Singleton
> @OwnedBy(HarnessTeam.CDP)
> ```

team = CDC :p

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/38392#-NDm6hl_AtQUEPyJWJJ6:-NDm9dZkBS33RtJr3ZG7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6baf3b53bb96492495510334a2eac945d348feb9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java#L53)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should log the exception since we are only throwing a message
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)* status: 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java` line 54 at r4](https://reviewable.io/reviews/harness/harness-core/38392#-NDxMIL59KAIyMF0iWoQ:-NDxMIL64mak7lG-fP-0:ba46rw0) ([raw file](https://github.com/harness/harness-core/blob/6da12b17234ccf4ed6ad7e02936dc90049e5d0a9/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactSourceTemplateHelper.java#L54)):*
> ```Java
>         return YamlUtils.read(artifactSourceYaml, ArtifactSourceConfig.class);
>       } catch (IOException e) {
>         throw new InvalidRequestException("Cannot process artifact source config due to: " + e.getMessage(), e);
> ```

We dont need to include message here, it can be just like this

```throw new InvalidRequestException("Cannot process artifact source config, e);```

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38392)* status: :shipit: complete! ✓

**Pull request merged**
