### PR TITLE
feat: [PL-30518]: Adding Access Failure log for NG SCIM

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41859)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/41859#-NJnUEgI0JDtaQc2bRHt:-NJnUEgJ0FWDSOTls7qf:b-q53nlb) ([raw file](https://github.com/harness/harness-core/blob/b9d4f72e8c4c4f2c36da9a7b30255381cca08810/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L56)):*
> ```Java
>     if (!accessControlClient.hasAccess(ResourceScope.of(accountIdentifier, null, null), Resource.of(USERGROUP, null),
>             MANAGE_USERGROUP_PERMISSION)) {
>       log.error("NGSCIM: Missing permission to create group for accountId {}", accountIdentifier);
> ```

lets log as warning and not error. 



_Code quote:_
```Java
log.error("
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/41859#-NJnUYBx5j835XrFziZr:-NJnUYBx5j835XrFziZs:b-2r1n7a) ([raw file](https://github.com/harness/harness-core/blob/b9d4f72e8c4c4f2c36da9a7b30255381cca08810/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L74)):*
> ```Java
>       @PathParam("accountIdentifier") String accountIdentifier, @PathParam("groupIdentifier") String groupIdentifier) {
>     if (!accessControlClient.hasAccess(
>             ResourceScope.of(accountIdentifier, null, null), Resource.of(USERGROUP, null), VIEW_USERGROUP_PERMISSION)) {
> ```

I think the null should actually be `groupIdentifier` , thanks



_Code quote:_
```Java
, null)
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/41859#-NJnUsL8-XcoNqil8XKh:-NJnUsL8-XcoNqil8XKi:b-jexdlf) ([raw file](https://github.com/harness/harness-core/blob/b9d4f72e8c4c4f2c36da9a7b30255381cca08810/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L144)):*
> ```Java
>     if (!accessControlClient.hasAccess(ResourceScope.of(accountIdentifier, null, null),
>             Resource.of(USERGROUP, groupIdentifier), MANAGE_USERGROUP_PERMISSION)) {
>       log.error("NGSCIM: Missing permission to update group for accountId {}", accountIdentifier);
> ```

minor: lets add a PUT call distinguisher here, else PATCH and PUT would both log same, thanks



_Code quote:_
```Java
to update group 
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/41859#-NJnVu1Z1t4wYc7mj6Ij:-NJnVu1Z1t4wYc7mj6Ik:b8io4rg) ([raw file](https://github.com/harness/harness-core/blob/b9d4f72e8c4c4f2c36da9a7b30255381cca08810/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java#L116)):*
> ```Java
>     if (!accessControlClient.hasAccess(ResourceScope.of(accountIdentifier, null, null),
>             Resource.of(USER, userIdentifier), MANAGE_USER_PERMISSION)) {
>       log.error("NGSCIM: Missing permission to update user for accountId {}", accountIdentifier);
> ```

minor: lets add a PUT call distinguisher here, thanks



_Code quote:_
```Java
update user 
```

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41859)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/41859#-NJnUEgI0JDtaQc2bRHt:-NJnbXwJ1N73ah_3AuPW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9d4f72e8c4c4f2c36da9a7b30255381cca08810/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L56)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

lets log as warning and not error. 
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/41859#-NJnUYBx5j835XrFziZr:-NJnbZ7q0f5Ry2h15tKr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b9d4f72e8c4c4f2c36da9a7b30255381cca08810/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L74)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

I think the null should actually be `groupIdentifier` , thanks
</blockquote></details>

Done.

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41859#-:-NJncWwM8jD5Tc4OnE_1:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41859)* status: :shipit: complete! ✓

**Pull request merged**
