### PR TITLE
feat: [CDC-16703]: Send pipeline Execution details as part of Current Activ…

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
…e Instances in service dashboards

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30471)

### CODE REVIEW

**Comment by abhinavmittal-harness** [comment]
trigger messagecheck

**Comment by abhinavmittal-harness** [comment]
trigger messagecheck

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30471)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30471)* status: :shipit: complete! ✓

___
*[400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java, line 914 at r1](https://reviewable.io/reviews/harness/harness-core/30471#-MutdoaW2ab3iYVas01Z:-MutdoaZ9uyeFWXZKla8:bcvpbgl) ([raw file](https://github.com/harness/harness-core/blob/78accbcecd4022d8ec77e02c413c9b2d8308ed5f/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L914)):*
> ```Java
>         if (pipelineSummary != null) {
>           pipelineEntitySummary = getEntitySummary(
>               pipelineSummary.getPipelineName(), lastWE.getPipelineExecutionId(), EntityType.PIPELINE.name());
> ```

Should we add new Entity Type PIPELINE_EXECUTION instead of PIPELINE?

**Pull request merged**
