### PR TITLE
[fix]: [DEL-3530]: kryo backward compatibility is broken if there are more than 32 fields to serialize/deserialize

### PR DESCRIPTION
**Pull request by raghuAtWings**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31457)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
trigger messagecheck

**Review by puneetsar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31457)* status: :shipit: complete! ✓

**Pull request merged**
