### PR TITLE
feat: [PL-25231]: add org viewer role when account ug inherited in project

### PR DESCRIPTION
**Pull request by naman-goenka**
… assigned role at project level

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 509 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3ql0sX0a7_6NmYqgmu:-N3ql0sX0a7_6NmYqgmv:b-1ds2y2) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L509)):*
> ```Java
>       HarnessScopeParams harnessScopeParams, RoleAssignmentDTO roleAssignmentDTO) {
>     Scope scope = fromParams(harnessScopeParams);
>     if (USER_GROUP.equals(roleAssignmentDTO.getPrincipal().getType())
> ```

1. Are we adding ProjectViewer Role as well?
2. What if Account level User Group is re-used at Org Level?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 506 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3qla5H7o5nXeSHfDtd:-N3qla5H7o5nXeSHfDte:b-kyd587) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L506)):*
> ```Java
>   }
> 
>   private void checkAndAddManagedRoleAssignmentForUserGroup(
> ```

Shall we make this method return just Role Assignments?

**Comment by naman-goenka** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 509 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3ql0sX0a7_6NmYqgmu:-N3ql0sX0a7_6NmYqgmv:b-1ds2y2) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L509)):_
> 
> > ```java
> >       HarnessScopeParams harnessScopeParams, RoleAssignmentDTO roleAssignmentDTO) {
> >     Scope scope = fromParams(harnessScopeParams);
> >     if (USER_GROUP.equals(roleAssignmentDTO.getPrincipal().getType())
> > ```
> 
> 1. Are we adding ProjectViewer Role as well?
> 2. What if Account level User Group is re-used at Org Level?


1) default role binding at that scope (org viewer in org, project viewer in project) is `selected by default` and `can't be deleted` in assignRoles Modal. So we are not adding project viewer role. 
2) In that case assignRoles Modal would make sure that org viewer role is assigned.

**Comment by naman-goenka** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 506 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3qla5H7o5nXeSHfDtd:-N3qla5H7o5nXeSHfDte:b-kyd587) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L506)):_
> 
> > ```java
> >   }
> > 
> >   private void checkAndAddManagedRoleAssignmentForUserGroup(
> > ```
> 
> Shall we make this method return just Role Assignments?

We can for the purpose of readability, but I kept it separate just to clear the intent that this method doesn't modifies the existing stream in any way. Please advise me, I will do accordingly.

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3rf4PrAibQHFK3eNQ2:-N3rf4PrAibQHFK3eNQ3:b-2q3jvy) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L478)):*
> ```Java
>         requestDTO.getRoleAssignments()
>             .stream()
>             .map(roleAssignmentDTO -> {
> ```

Unnecessary map?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 506 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3qla5H7o5nXeSHfDtd:-N3riUQ7DTKuilO5JHkh:b1btfrh) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L506)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

We can for the purpose of readability, but I kept it separate just to clear the intent that this method doesn't modifies the existing stream in any way. Please advise me, I will do accordingly.
</blockquote></details>

I would suggest you first create the role bindings requested and then create these role bindings separately after that 
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 509 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3ql0sX0a7_6NmYqgmu:-N3qlZCF3-oWcSd4W-hk:bb7efny) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L509)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

1) default role binding at that scope (org viewer in org, project viewer in project) is `selected by default` and `can't be deleted` in assignRoles Modal. So we are not adding project viewer role. 
2) In that case assignRoles Modal would make sure that org viewer role is assigned.

</blockquote></details>

cool

**Comment by naman-goenka** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)_ status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.
> 
> _[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3rf4PrAibQHFK3eNQ2:-N3rf4PrAibQHFK3eNQ3:b-2q3jvy) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L478)):_
> 
> > ```java
> >         requestDTO.getRoleAssignments()
> >             .stream()
> >             .map(roleAssignmentDTO -> {
> > ```
> 
> Unnecessary map?
Can be changed to this implementation as per our discussion @reetika04 

```
                    .map(roleAssignmentDTO
                            ->
                            {
                              checkAndAddManagedRoleAssignmentForUserGroup(harnessScopeParams, roleAssignmentDTO);
                              return buildRoleAssignmentWithPrincipalScopeLevel(fromDTO(scope, roleAssignmentDTO, managed), scope)
  })
```

**Comment by naman-goenka** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)_ status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained.
> 
> _[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 506 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3qla5H7o5nXeSHfDtd:-N3riUQ7DTKuilO5JHkh:b1btfrh) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L506)):_
> 
> Previously, naman-goenka (Naman Goenka) wrote…
> > We can for the purpose of readability, but I kept it separate just to clear the intent that this method doesn't modifies the existing stream in any way. Please advise me, I will do accordingly.
> 
> I would suggest you first create the role bindings requested and then create these role bindings separately after that
> 
> _[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 509 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3ql0sX0a7_6NmYqgmu:-N3qlZCF3-oWcSd4W-hk:bb7efny) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L509)):_
> 
> Previously, naman-goenka (Naman Goenka) wrote…
> > 1. default role binding at that scope (org viewer in org, project viewer in project) is `selected by default` and `can't be deleted` in assignRoles Modal. So we are not adding project viewer role.
> > 2. In that case assignRoles Modal would make sure that org viewer role is assigned.
> 
> cool

@ankit-harness for that I would have to do 
`    requestDTO.getRoleAssignments()
            .stream()
            .forEach(roleAssignmentDTO ->
              checkAndAddManagedRoleAssignmentForUserGroup(harnessScopeParams, roleAssignmentDTO)
);`

This would need an additional stream and foreach operation. Second way without the need of additional map operation could be 
`                    .map(roleAssignmentDTO
                            ->
                            {
                              checkAndAddManagedRoleAssignmentForUserGroup(harnessScopeParams, roleAssignmentDTO);
                              return buildRoleAssignmentWithPrincipalScopeLevel(fromDTO(scope, roleAssignmentDTO, managed), scope)
  })`
  which should I follow?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java` line 509 at r1](https://reviewable.io/reviews/harness/harness-core/33925#-N3ql0sX0a7_6NmYqgmu:-N3sPY_wEcPtk6MJZbnj:bxzxnm0) ([raw file](https://github.com/harness/harness-core/blob/444aa4ce77affb6ee57d381240484b498e37dd9a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentResourceImpl.java#L509)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

@ankit-harness for that I would have to do 
`    requestDTO.getRoleAssignments()
            .stream()
            .forEach(roleAssignmentDTO ->
              checkAndAddManagedRoleAssignmentForUserGroup(harnessScopeParams, roleAssignmentDTO)
);`

This would need an additional stream and foreach operation. Second way without the need of additional map operation could be 
`                    .map(roleAssignmentDTO
                            ->
                            {
                              checkAndAddManagedRoleAssignmentForUserGroup(harnessScopeParams, roleAssignmentDTO);
                              return buildRoleAssignmentWithPrincipalScopeLevel(fromDTO(scope, roleAssignmentDTO, managed), scope)
  })`
  which should I follow?

</blockquote></details>

1st option

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925#-:-N3xD1XJBlRlvslW-rKM:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925#-:-N3xKmpn3Ut4Qk2cDFcV:bnfp4nl)* status: 1. unresolved discussions.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: 1. unresolved discussions.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33925)* status: :shipit: complete! ✓

**Pull request merged**
