### PR TITLE
techdebt: [PL-29835]: Break up 957-cg-beans dependency on 960-persistence

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR contains all the granular build files for 957-cg-beans, 960-persistence and 970-ng-commons after breaking up the dependency on 957-cg-beans on 960-persistence.

This PR has a dependency on the below 2 cycle fixes in 960-persistence -
1. https://github.com/harness/harness-core/pull/42025
2. https://github.com/harness/harness-core/pull/42040 

Tested End-to-End K8s workflow deployment in the PR Env.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)

### CODE REVIEW

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: 50 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: :shipit: complete! ✓

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, ft1, ft2

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 7 of 25 files at r2, 47 of 48 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: 50 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`957-cg-beans/BUILD.bazel` line 14 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLesfqC4joypzZX11Ar:-NLesfqC4joypzZX11As:b-sb41ln) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/957-cg-beans/BUILD.bazel#L14)):*
> ```Starlark
>     srcs = glob(["src/main/java/**/*.java"]),
>     visibility = ["//visibility:public"],
>     deps = [
> ```

If 957 is now completely broken down to package targets (has no srcs outside the new package targets), you would need to change this one to exports https://bazel.build/reference/be/java#java_library.exports
___
*[`960-persistence/src/main/java/io/harness/beans/BUILD.bazel` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLetah24VQOwmiv5iGp:-NLetah24VQOwmiv5iGq:b-ozt02d) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/beans/BUILD.bazel#L23)):*
> ```Starlark
>         "@maven//:com_fasterxml_jackson_core_jackson_annotations",
>         "@maven//:com_google_guava_guava",
>         "@maven//:dev_morphia_morphia_core",
> ```

I think we removed dev morphia recently. Maybe double check. You have org_morphia below as well
___
*[`960-persistence/src/main/java/io/harness/mongo/index/migrator/BUILD.bazel` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeu08cDr6scUSXp082:-NLeu08cDr6scUSXp083:b-8nmkaa) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/mongo/index/migrator/BUILD.bazel#L13)):*
> ```Starlark
>     srcs = glob(["*.java"]),
>     visibility = ["//visibility:public"],
>     deps = ["@maven//:dev_morphia_morphia_core"],
> ```

Check if we really wanted dev_morphia
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/filter/BUILD.bazel` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeu6_91tRvYfVqvPK2:-NLeu6_A3uJSLV4guZTq:bvgg4pd) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/mongo/iterator/filter/BUILD.bazel#L13)):*
> ```Starlark
>     srcs = glob(["*.java"]),
>     visibility = ["//visibility:public"],
>     deps = ["@maven//:dev_morphia_morphia_core"],
> ```

dev_morphia
___
*[`970-ng-commons/src/main/java/io/harness/metrics/BUILD.bazel` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeuev5BxitQDMWChnw:-NLeuev5BxitQDMWChnx:bblor9z) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/970-ng-commons/src/main/java/io/harness/metrics/BUILD.bazel#L13)):*
> ```Starlark
>     srcs = glob(["*.java"]),
>     visibility = ["//visibility:public"],
>     deps = ["@maven//:org_apache_logging_log4j_log4j_api"],
> ```

This import is odd. Normally libraries shouldn't be using any logging implementation, only logging interfaces (like slf4j). Binaries are the one that would need logging implementation (like logback). Also, we don't actually use log4j for logging, but logback. Can you please double check where is this coming from. 
___
*[`970-ng-commons/src/main/java/io/harness/metrics/service/impl/BUILD.bazel` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLevIvL5gzLNrujj-S5:-NLevIvL5gzLNrujj-S6:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/970-ng-commons/src/main/java/io/harness/metrics/service/impl/BUILD.bazel#L28)):*
> ```Starlark
>         "@maven//:io_opencensus_opencensus_exporter_stats_stackdriver",
>         "@maven//:io_prometheus_simpleclient_httpserver",
>         "@maven//:org_apache_logging_log4j_log4j_api",
> ```

same
___
*[`960-persistence/src/main/java/io/harness/persistence/converters/BUILD.bazel` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeuC4F0keVzOYH8_Nn:-NLeuC4F0keVzOYH8_No:bvgg4pd) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/persistence/converters/BUILD.bazel#L20)):*
> ```Starlark
>         "@maven//:com_google_protobuf_protobuf_java",
>         "@maven//:com_google_protobuf_protobuf_java_util",
>         "@maven//:dev_morphia_morphia_core",
> ```

dev_morphia

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: 50 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/beans/BUILD.bazel` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLetah24VQOwmiv5iGp:-NLgEZiO9ldQGaZX7IIv:b-kmsbfq) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/beans/BUILD.bazel#L23)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think we removed dev morphia recently. Maybe double check. You have org_morphia below as well
</blockquote></details>

I think this is the one we added. Probably org_morphia is what we need to remove

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: 50 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`957-cg-beans/BUILD.bazel` line 14 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLesfqC4joypzZX11Ar:-NLgaMDw91axx_sWnTUK:bwxjme2) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/957-cg-beans/BUILD.bazel#L14)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

If 957 is now completely broken down to package targets (has no srcs outside the new package targets), you would need to change this one to exports https://bazel.build/reference/be/java#java_library.exports
</blockquote></details>

It is not yet completely broken down. I just broke down the ones that depended on 960-persistence. Once 957 is broken up completely I will change it to exports.
___
*[`960-persistence/src/main/java/io/harness/beans/BUILD.bazel` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLetah24VQOwmiv5iGp:-NLgbBTH2qXDaa-oE3pG:b-xutn16) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/beans/BUILD.bazel#L23)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

I think this is the one we added. Probably org_morphia is what we need to remove
</blockquote></details>

Yeah looks like `dev_morphia_morphia_core` replaces `org_mongodb_morphia_morphia`. I've removed the `org_mongodb_morphia_morphia` dep, thanks for catching this!
___
*[`960-persistence/src/main/java/io/harness/mongo/index/migrator/BUILD.bazel` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeu08cDr6scUSXp082:-NLgbd7u4IuznuFUkpm2:b-s4cjnv) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/mongo/index/migrator/BUILD.bazel#L13)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Check if we really wanted dev_morphia
</blockquote></details>

Yes, this file - 960-persistence/src/main/java/io/harness/mongo/index/migrator/Migrator.java uses `import dev.morphia.AdvancedDatastore` so need this dep. However, I'm removing `org_mongodb_morphia_morphia` deps. 
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/filter/BUILD.bazel` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeu6_91tRvYfVqvPK2:-NLgc-4pAoeY3FkbcDUB:ba1tjwz) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/mongo/iterator/filter/BUILD.bazel#L13)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

dev_morphia
</blockquote></details>

This file 960-persistence/src/main/java/io/harness/mongo/iterator/filter/MorphiaFilterExpander.java is importing dev_morphia, so added it here.
___
*[`970-ng-commons/src/main/java/io/harness/metrics/BUILD.bazel` line 13 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeuev5BxitQDMWChnw:-NLgcrZa2qB803JDknnD:b-p26elk) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/970-ng-commons/src/main/java/io/harness/metrics/BUILD.bazel#L13)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This import is odd. Normally libraries shouldn't be using any logging implementation, only logging interfaces (like slf4j). Binaries are the one that would need logging implementation (like logback). Also, we don't actually use log4j for logging, but logback. Can you please double check where is this coming from. 
</blockquote></details>

Actually here we use this dep for `ThreadContext` and not for logging. The below file - 

970-ng-commons/src/main/java/io/harness/metrics/AutoMetricContext.java has a dep on `import org.apache.logging.log4j.ThreadContext` and thus added this.
___
*[`970-ng-commons/src/main/java/io/harness/metrics/service/impl/BUILD.bazel` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLevIvL5gzLNrujj-S5:-NLgdE_H9mCHvdsYqzKH:bbrwpvi) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/970-ng-commons/src/main/java/io/harness/metrics/service/impl/BUILD.bazel#L28)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

same
</blockquote></details>

Here looks like this is not needed because it depends on the above target `"//970-ng-commons/src/main/java/io/harness/metrics:module"` which has the dep `"@maven//:org_apache_logging_log4j_log4j_api"`. So removed it here.
___
*[`960-persistence/src/main/java/io/harness/persistence/converters/BUILD.bazel` line 20 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLeuC4F0keVzOYH8_Nn:-NLgcGu385FZ2tFUAAkg:b-fmn1dz) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/960-persistence/src/main/java/io/harness/persistence/converters/BUILD.bazel#L20)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

dev_morphia
</blockquote></details>

Actually multiple files listed below  - 

960-persistence/src/main/java/io/harness/persistence/converters/DurationConverter.java
960-persistence/src/main/java/io/harness/persistence/converters/ObjectArrayConverter.java
960-persistence/src/main/java/io/harness/persistence/converters/ProtoMessageConverter.java

were using `dev_morphia` so need this dep to compile.

**Comment by Raghav-Murali** [comment]
trigger ft1, ft2

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: 50 file(s) to review. 1 of 2 approvals obtained.

**Review by xingchi-jin — COMMENTED** [review]
Approval with a nit 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143#-:-NLi5Vs--mGXNCP6loQC:b-38q7bs)* status: 50 file(s) to review. 1 of 2 approvals obtained. 

___
*[`957-cg-beans/BUILD.bazel` line 14 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLesfqC4joypzZX11Ar:-NLi5OMIDiJWi9iUujlz:b17a3a5) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/957-cg-beans/BUILD.bazel#L14)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

It is not yet completely broken down. I just broke down the ones that depended on 960-persistence. Once 957 is broken up completely I will change it to exports.
</blockquote></details>

what's the right timing to make them exported? wait until everything is broken up

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: 50 file(s) to review. 1 of 2 approvals obtained. 

___
*[`957-cg-beans/BUILD.bazel` line 14 at r5](https://reviewable.io/reviews/harness/harness-core/42143#-NLesfqC4joypzZX11Ar:-NLi69BL6srntyxoaBQu:bs88rli) ([raw file](https://github.com/harness/harness-core/blob/24a484c3ad2bbd5bd76a75d648319f5050f586d3/957-cg-beans/BUILD.bazel#L14)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

what's the right timing to make them exported? wait until everything is broken up 
</blockquote></details>

We need to make them `export` when all the sub-folders within have their own Build files. At that time Bazel itself will throw an error that you cannot have `deps`.

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 45 of 48 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42143)* status: :shipit: complete! ✓

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Pull request merged**
