### PR TITLE
feat: [CDS-44931]: Hard delete files on project deletion

### PR DESCRIPTION
**Pull request by ivan-83**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39446)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39446)* status: 0 of 1 approvals obtained. 

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileFailsafeServiceImpl.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/39446#-NFmABTk9--TJPD5PMid:-NFmABTk9--TJPD5PMie:b-u20im9) ([raw file](https://github.com/harness/harness-core/blob/ae0f9d3e3ba826712b683d8f3bedb147ad4256a1/877-filestore/src/main/java/io/harness/filestore/service/impl/FileFailsafeServiceImpl.java#L112)):*
> ```Java
>     } catch (Exception ex) {
>       log.error("Failed to delete {} [{}].", ngFile.isFile() ? "file" : "folder", ngFile.getName(), ex);
>       throw ex;
> ```

not fail safe anymore? 
___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 369 at r3](https://reviewable.io/reviews/harness/harness-core/39446#-NFmARR18FRkiU1VFPyv:-NFmARR18FRkiU1VFPyw:bj9u39z) ([raw file](https://github.com/harness/harness-core/blob/ae0f9d3e3ba826712b683d8f3bedb147ad4256a1/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L369)):*
> ```Java
>         accountIdentifier, orgIdentifier, projectIdentifier);
>     identifiers.forEach(identifier -> {
>       NGFile ngFile = findOrThrow(accountIdentifier, orgIdentifier, projectIdentifier, identifier);
> ```

so if there are 100 files we will query 100 times. Can we instead perform deleteAll?

**Comment by vladimir-peric** [comment]
*[`877-filestore/src/main/java/io/harness/filestore/events/listener/FileEntityCRUDStreamListener.java` line 128 at r3](https://reviewable.io/reviews/harness/harness-core/39446#-NFmI0Zl2utaHG338mJ-:-NFmI0Zm5pAlekJS9Qnv:btnia1c) ([raw file](https://github.com/harness/harness-core/blob/ae0f9d3e3ba826712b683d8f3bedb147ad4256a1/877-filestore/src/main/java/io/harness/filestore/events/listener/FileEntityCRUDStreamListener.java#L128)):*
> ```Java
> 
>   private String getAction(Message message) {
>     return hasMessage(message) ? message.getMessage().getMetadataMap().get(ACTION) : null;
> ```

Do we need a check that getMetadataMap() is null? Additionally, returning Optional.empty() might be more suitable here than null.

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39446)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileFailsafeServiceImpl.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/39446#-NFmABTk9--TJPD5PMid:-NFnP4Aj9M2PS0X_ks6A:b-yp380e) ([raw file](https://github.com/harness/harness-core/blob/ae0f9d3e3ba826712b683d8f3bedb147ad4256a1/877-filestore/src/main/java/io/harness/filestore/service/impl/FileFailsafeServiceImpl.java#L112)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

not fail safe anymore? 
</blockquote></details>

just preventing an infinite loop for deleteBatch.
___
*[`877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java` line 369 at r3](https://reviewable.io/reviews/harness/harness-core/39446#-NFmARR18FRkiU1VFPyv:-NFnNz2m3STtbsDvoiX4:b54jhfi) ([raw file](https://github.com/harness/harness-core/blob/ae0f9d3e3ba826712b683d8f3bedb147ad4256a1/877-filestore/src/main/java/io/harness/filestore/service/impl/FileStoreServiceImpl.java#L369)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

so if there are 100 files we will query 100 times. Can we instead perform deleteAll?
</blockquote></details>

We have to perform the following actions when deleting one file.
1. Delete file from GridFS bucket >> GridFSBucket API doesn't support deleteMany, needs to be done one by one 
https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/gridfs/#delete-files

2. Delete the file from NGFile collection
3. Delete all file activities
4. Publish FileDelete Event for auditing events

Actions 2,3,4 need to be done in one transaction with a retry strategy to satisfy atomicity for deleting items and sending messages/event operations.

Because of all of the above we are limited to using deleteAll. 

If we don't need to satisfy transaction atomicity and not publish auditing events when deleting a project,  we can use deleteMany for 2 and 3 but still need to delete one by one file from GridFS bucket

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39446)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger messagecheck

**Pull request merged**
