### PR TITLE
feat: [SRM-9295]: Error Tracking dsl to use account, org, project IDs

### PR DESCRIPTION
**Pull request by DFieldFL**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31483)

### CODE REVIEW

**Comment by DFieldFL** [comment]
delegate hash is changed. Error Tracking hasn't been released yet so no backwards compatibility is needed.

**Review by ccaspanello — APPROVED** [review]
> Reviewed 11 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31483)* status: :shipit: complete! ✓

**Comment by DFieldFL** [comment]
1. Is it new task type? no
2. Did you make changes to the code in a backward-compatible manner? Error Tracking is new and hasn't been released yet.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 11 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31483)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31483)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 11 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31483)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31483)* status: :shipit: complete! ✓

**Pull request merged**
