### PR TITLE
[feat]: [CDS-43964]: Default templates for execution

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38810)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 62 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38810)* status: 72 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbmlCD7nF4Hp54kqP-:-NEbmlCE7ScHKPEBMpXL:b-s2r9wx) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java#L33)):*
> ```Java
> @Singleton
> @OwnedBy(CDP)
> public class CDNGDefaultTemplateHelper {
> ```

I will rename this to DefaultTempateLoader, and keep all static methods,resolveTemplateConfig method, and TemplateConfig static class.
Also, will moved getOrCreateAccountLevelTemplate to CDNGPipelineExecutionStrategyHelperV2 class with TemplateResourceClient templateResourceClient client. it's up to you.
   



_Code quote:_
```Java
CDNGDefaultTemplateHelper
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java` line 110 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbkl8jD-cCc2oR5ksh:-NEbkl8n6ZfxIo4ryAaj:bysl3ba) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java#L110)):*
> ```Java
>   }
> 
>   TemplateConfig resolveTemplateConfig(ServiceDefinitionType serviceDefinitionType, ArtifactType artifactType) {
> ```

Make this method private because TemplateConfig is private or put VisibleForTesting annotation. 



_Code quote:_
```Java
TemplateConfig
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java` line 159 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbrXdm72dbuvA1W4_v:-NEbrXdq8DuQxwXTsN33:b1482w1) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java#L159)):*
> ```Java
>         return response.getYaml();
>       }
>     } catch (InvalidRequestException e) {
> ```

Can we catch the 404 response status, need to handle better cases when an item doesn't exist in DB or some other exception happens. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbrzwD69K2IOfj4hwu:-NEbrzwD69K2IOfj4hwv:b-wkc4px) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGDefaultTemplateHelper.java#L167)):*
> ```Java
>       log.error("Error occurred while getting/creating default template", e);
>     }
>     return "";
> ```

The empty string means here that UnexpectedException happens, it is better to rethrow an exception or handle it better. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEba1wXDgx3MVkwyNpQ:-NEba1wXDgx3MVkwyNpR:bv14fb1) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java#L96)):*
> ```Java
>   }
> 
>   public String createDefaultTemplateIfNotExists(
> ```

I think we don't need this method as well as the resource endpoint to create default templates on the account level. Pls, delete both, if we would need we will implement them. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbZL8H1JUY1X-naOYh:-NEbZL8H1JUY1X-naOYi:b-1xos87) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelper.java#L111)):*
> ```Java
>       StrategyParameters strategyParameters) throws IOException {
>     if (ExecutionStrategyType.CANARY.equals(executionStrategyType)) {
>       return generateCanaryYaml(accountIdentifier, serviceDefinitionType, includeVerify, strategyParameters);
> ```

I will move these three methods generateCanaryYaml, generateRollingYaml, and generateBasicYaml to  CDNGPipelineFromTemplateHelper because we are already using defaultTemplateHelpe and having logic around empty temples in that helper. You can have one public method like generateSshWinRmExecutionStrategyYaml in CDNGPipelineFromTemplateHelper where you can have if-else logic around these three methods. 

Also, the logic where we catch InvalidRequestException and again call generateSshWinRmCanaryYaml is not clear we have to be more specific, when you move methods to CDNGPipelineFromTemplateHelper this case will be easy to solve. 

Pls rename CDNGPipelineFromTemplateHelper to CDNGPipelineExecutionStrategyHelperV2 or CDNGPipelineExecutionStrategyTemplate Helper it is easy get the context about the changes. 

Remove CDNGDefaultTemplateHelper defaultTemplateHelper from this class.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbd6OD2ONaVheby6yc:-NEbd6OD2ONaVheby6yd:boswvp8) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L82)):*
> ```Java
>     } else if (ExecutionStrategyType.BASIC.equals(executionStrategyType)) {
>       return generateSshWinRmBasicYaml(accountIdentifier, serviceDefinitionType, strategyParameters, includeVerify);
>     }
> ```

Throw exception here or handle it better. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbdkC72d7bbRAgPo7L:-NEbdkC72d7bbRAgPo7M:bcu84s5) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L99)):*
> ```Java
>     try (StringWriter stringWriter = new StringWriter()) {
>       ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
>       String artifactType = isSSHServiceDefinitionType(serviceDefinitionType)
> ```

Will this work for WinRm?



_Code quote:_
```Java
isSSHServiceDefinitionType
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbocsE-JYWT1UdI1Mm:-NEbocsIEb3lIYkANzyk:b-rqxhw5) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L125)):*
> ```Java
>       StrategyParameters strategyParameters, boolean includeVerify) throws IOException {
>     validateStrategyParametersForRolling(strategyParameters);
>     String templateYaml = cdngDefaultTemplateHelper.getOrCreateAccountLevelTemplate(
> ```

Minor - maybe return data structure with a template reference and template content as a string and pass template reference as templateParams.



_Code quote:_
```Java
templateYaml 
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 127 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbeBLGD-KHdpg8-_4c:-NEbeBLGD-KHdpg8-_4d:b-o324l4) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L127)):*
> ```Java
>     String templateYaml = cdngDefaultTemplateHelper.getOrCreateAccountLevelTemplate(
>         accountIdentifier, serviceDefinitionType, strategyParameters.getArtifactType());
>     if (isEmpty(templateYaml)) {
> ```

I will not return the empty string from cdngDefaultTemplateHelper helper just try to get and create a template if it doesn't work throw an exception.  If the template service is down handle it here. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbf2s00lpB4KkIAU9m:-NEbf2s00lpB4KkIAU9n:b-syig15) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L175)):*
> ```Java
>       ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
>       String artifactType = isSSHServiceDefinitionType(serviceDefinitionType)
>           ? artifactSSHTypeSuffix(strategyParameters.getArtifactType())
> ```

I will move this snippet to a separate method because we repeat it more times. 



_Code quote:_
```Java
      String artifactType = isSSHServiceDefinitionType(serviceDefinitionType)
          ? artifactSSHTypeSuffix(strategyParameters.getArtifactType())
          : artifactWinRmTypeSuffix(strategyParameters.getArtifactType());
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 208 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbby-O3YYVPN6lk9yJ:-NEbby-O3YYVPN6lk9yK:b-a106rv) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L208)):*
> ```Java
>   }
> 
>   private static void loadStaticScriptSnippets(ClassLoader classLoader) throws IOException {
> ```

Move at beginning of class
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 217 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbg0Sy4k2xJAau6MW0:-NEbg0Sy4k2xJAau6MW1:b-xan4kx) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L217)):*
> ```Java
>   }
> 
>   private void validateStrategyParametersForCanary(StrategyParameters strategyParameters) {
> ```

Minor - move to the new StrategyValidator class



_Code quote:_
```Java
validateStrategyParametersForCanary
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbfHja7QHPRAt1pnH8:-NEbfHja7QHPRAt1pnH9:bpssrpj) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L219)):*
> ```Java
>   private void validateStrategyParametersForCanary(StrategyParameters strategyParameters) {
>     if (null == strategyParameters.getPhases() || isEmpty(strategyParameters.getPhases())) {
>       throw new GeneralException("phases need to be defined, e.g. phases : [10, 50, 100]");
> ```

Instead of GeneralException use InvalidArgumentException



_Code quote:_
```Java
GeneralException(
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbgYiR97v6m1nJwPTG:-NEbgYiR97v6m1nJwPTH:b-xan4kx) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L249)):*
> ```Java
>   }
> 
>   private void validateStrategyParametersForRolling(StrategyParameters strategyParameters) {
> ```

Minor - move to the new StrategyValidator class



_Code quote:_
```Java
validateStrategyParametersForRolling
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 265 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbfgbNAHZsX8eeHTZh:-NEbfgbNAHZsX8eeHTZi:bhglzy2) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L265)):*
> ```Java
>   }
> 
>   private boolean isSSHServiceDefinitionType(ServiceDefinitionType serviceDefinitionType) {
> ```

Move to the Utility class
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 269 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbfhHK0dZzPF1QlZgQ:-NEbfhHK0dZzPF1QlZgR:bhglzy2) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L269)):*
> ```Java
>   }
> 
>   private String artifactSSHTypeSuffix(ArtifactType artifactType) {
> ```

Move to the Utility class
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbfhvEEyOB_2sOS9-F:-NEbfhvEEyOB_2sOS9-G:bhglzy2) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L281)):*
> ```Java
>   }
> 
>   private String artifactWinRmTypeSuffix(ArtifactType artifactType) {
> ```

Move to the Utility class

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38810#-NEbdkC72d7bbRAgPo7L:-NEdyycODVnnzQa2wCQS:b-7j54kz) ([raw file](https://github.com/harness/harness-core/blob/97b94c9dff239cdcf00ed53180697387f40692bd/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineFromTemplateHelper.java#L99)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Will this work for WinRm?
</blockquote></details>

Yes, this method distinguishes between ssh and winrm artifact types



_Code quote:_
```Java
 String artifactType = isSSHServiceDefinitionType(serviceDefinitionType)
```

**Comment by vladimir-peric** [comment]
trigger compile

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 12 of 75 files at r1, 29 of 62 files at r2, 30 of 36 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38810)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineExecutionStrategyHelperV2.java` line 225 at r4](https://reviewable.io/reviews/harness/harness-core/38810#-NEgbqXb8LfTK3859Cts:-NEgbqXb8LfTK3859Ctt:byl134f) ([raw file](https://github.com/harness/harness-core/blob/412ef932421daeafdf15ebf82d5a79999005c211/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineExecutionStrategyHelperV2.java#L225)):*
> ```Java
>       } else {
>         throw new InvalidRequestException(String.format(
>             "Default template % does not exist, or has no stable version.", templateConfig.getTemplateIdentifier()));
> ```

Minor - can be done in the next iteration. I think this exception msg should be updated, if the template doesn't exist InvalidRequestException will be caught and a new one stable will be created.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 50 of 51 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38810)* status: :shipit: complete! ✓

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38810)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineExecutionStrategyHelperV2.java` line 221 at r8](https://reviewable.io/reviews/harness/harness-core/38810#-NEjiB8Z8HPsDCOpzBx2:-NEjiB8_2UPR1xqAuRWI:bkg1xeb) ([raw file](https://github.com/harness/harness-core/blob/dd6c839ec6bcf051f088b8fdc4ec3fa3650d550b/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/helpers/CDNGPipelineExecutionStrategyHelperV2.java#L221)):*
> ```Java
>       } else {
>         throw new InvalidRequestException(
>             format("Default template % does not exist.", templateConfig.getTemplateIdentifier()));
> ```

We need better error msg and more generic exception in order not to catch in try/catch block.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38810#-:-NEl1_LH7vp4InTuy8Sv:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
