### PR TITLE
fix: [CDS-83829]: updates template stage type validation error message

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
fix: [CDS-83829]: updates template stage type validation error message

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-83829]: https://harness.atlassian.net/browse/CDS-83829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55423)

### CODE REVIEW

**Comment by sandeshsalunkhegh** [comment]
Response from Postman:
```{
    "status": "ERROR",
    "code": "INVALID_REQUEST",
    "message": "Invalid request: Error while saving template [custom_stage_1] of versionLabel [v1] : [Template with identifier [custom_stage_1] and versionLabel [v1] under Project[Project_1], Organization [default] cannot update the internal template type, current type is [Custom] and the requested type is [CI].]",
    "correlationId": "701b5423-506f-4c99-a3fe-f04a79cc9a9b",
    "detailedMessage": null,
    "responseMessages": [
        {
            "code": "INVALID_REQUEST",
            "level": "ERROR",
            "message": "Invalid request: Error while saving template [custom_stage_1] of versionLabel [v1] : [Template with identifier [custom_stage_1] and versionLabel [v1] under Project[Project_1], Organization [default] cannot update the internal template type, current type is [Custom] and the requested type is [CI].]",
            "exception": null,
            "failureTypes": []
        },
        {
            "code": "INVALID_REQUEST",
            "level": "ERROR",
            "message": "Invalid request: Template with identifier [custom_stage_1] and versionLabel [v1] under Project[Project_1], Organization [default] cannot update the internal template type, current type is [Custom] and the requested type is [CI].",
            "exception": null,
            "failureTypes": []
        }
    ],
    "metadata": null
}```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55423)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1432 at r1](https://reviewable.io/reviews/harness/harness-core/55423#-NjLVmuN6UbZvvHh9UH8:-NjLVmuN6UbZvvHh9UH9:bi58t8b) ([raw file](https://github.com/harness/harness-core/blob/ed15924a2d0ddc59ecf66d50fbe864e3185d7996/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1432)):*
> ```Java
>             || oldTemplateEntity.getChildType().equals(templateEntity.getChildType()))) {
>       throw new InvalidRequestException(format(
>           "Template with identifier [%s] and versionLabel [%s] under Project[%s], Organization [%s] cannot update the internal template type, current type is [%s] and the requested type is [%s].",
> ```

Please add test for this particular function
The test should fail if someone changes this error message

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55423)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1432 at r1](https://reviewable.io/reviews/harness/harness-core/55423#-NjLVmuN6UbZvvHh9UH8:-NjLkFWj0dNHvZcpB6Jv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed15924a2d0ddc59ecf66d50fbe864e3185d7996/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1432)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please add test for this particular function
The test should fail if someone changes this error message
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55423)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55423)* status: :shipit: complete! ✓

**Pull request merged**
