### PR TITLE
feat: [SSCA-1005]: Changes to use OPA policies in ssca enforcement

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Describe your changes
Adding feature flag client and account client module.
Adding usage of PolicyMgmt service to evaluate OPA policies in SSCA enforcement step 
Adding usage of FF to decide whether to evaluate just OPA policies or both OPA and SSCA policies 
Adding code to clean up rules which are received in the OPA policy evaluation response 
Adding code to create human readable violation msgs for OPA violations 
Adding UTs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger uts

**Comment by dhruv-harness** [comment]
trigger uts

**Comment by krishi0408** [comment]
trigger checkstylecodeformat

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-Nks_YZs2H1nXRPFPrq7:-Nks_YZs2H1nXRPFPrq8:b-12zie) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java#L76)):*
> ```Java
>     if (featureFlagService.isFeatureFlagEnabled(
>             accountId, FeatureName.SSCA_ENFORCEMENT_WITH_BOTH_NATIVE_AND_OPA_POLICIES_ENABLED.name())) {
>       if (StringUtils.isNotBlank(body.getPolicySetRef())) {
> ```

Can we simplify the conditions here ?

if( ! enabled(SSCA_ENFORCEMENT_WITH_BOTH_NATIVE_AND_OPA_POLICIES_ENABLED.))
   err

if( featureFlagService.isFeatureFlagEnabled(
            accountId, FeatureName.SSCA_ENFORCEMENT_WITH_BOTH_NATIVE_AND_OPA_POLICIES_ENABLED.name()) ||
StringUtils.isNotBlank(body.getPolicySetRef())
      policyEvaluationResult = evaluatePolicyViolationsUsingOpaPolicies

else if( StringUtils.isNotBlank(body.getPolicyFileId()))
   policyEvaluationResult = evaluatePolicyViolationsUsingSscaPolicies
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-NksbHa61ap_wYDsn6M0:-NksbHa7BPo_IifoOIkz:b-ggd76t) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java#L101)):*
> ```Java
>   }
> 
>   private Pair<List<EnforcementResultEntity>, List<EnforcementResultEntity>> evaluatePolicyViolationsUsingOpaPolicies(
> ```

Can we create a separate abstraction for opa ? like sscaOPAPolicyEvaluater . All OPA code can be separated from generic enforcement service
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-NkscEb_DKhGk475GRSq:-NkscEb_DKhGk475GRSr:b-ayabd6) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java#L121)):*
> ```Java
>         getEnforcementResultEntitiesFromOpaViolations(accountId, orgIdentifier, projectIdentifier,
>             body.getEnforcementId(), components, artifactEntity, opaPolicyEvaluationResult.getDenyListViolations());
>     enforcementResultRepo.saveAll(denyListViolations);
> ```

Save all EnforcementResultEntity in one call

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: Some of the checks are too old. 5 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/config/ssca-manager-config.yml` line 135 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-Nkt8VaE0XtkImTEPck0:-Nkt8VaE0XtkImTEPck1:b-8qkf92) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/config/ssca-manager-config.yml#L135)):*
> ```YAML
>   syncFeaturesToCF: false
> 
> managerClientConfig:
> ```

We should move away from calling cg manager to get the feature flag.
All other services have started creating their own featureFlag collection in their own database. We should also move to that.

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: Some of the checks are too old. 5 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/config/ssca-manager-config.yml` line 135 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-Nkt8VaE0XtkImTEPck0:-NktChN6AXLSJ57Ai_2_:b8kgt7b) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/config/ssca-manager-config.yml#L135)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

We should move away from calling cg manager to get the feature flag.
All other services have started creating their own featureFlag collection in their own database. We should also move to that.
</blockquote></details>

I had planned the same initially, but there were issues while using the FF SDK and we were blocked because of that. So we discussed and decided to use the old approach
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-Nks_YZs2H1nXRPFPrq7:-NktD1ZC0268lJc9mI3G:b4x4m3x) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java#L76)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can we simplify the conditions here ?

if( ! enabled(SSCA_ENFORCEMENT_WITH_BOTH_NATIVE_AND_OPA_POLICIES_ENABLED.))
   err

if( featureFlagService.isFeatureFlagEnabled(
            accountId, FeatureName.SSCA_ENFORCEMENT_WITH_BOTH_NATIVE_AND_OPA_POLICIES_ENABLED.name()) ||
StringUtils.isNotBlank(body.getPolicySetRef())
      policyEvaluationResult = evaluatePolicyViolationsUsingOpaPolicies

else if( StringUtils.isNotBlank(body.getPolicyFileId()))
   policyEvaluationResult = evaluatePolicyViolationsUsingSscaPolicies
</blockquote></details>

sure, I will take this up
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java` line 101 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-NksbHa61ap_wYDsn6M0:-NktD5DnA-JaCUcCW5OE:bb74ce2) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java#L101)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can we create a separate abstraction for opa ? like sscaOPAPolicyEvaluater . All OPA code can be separated from generic enforcement service
</blockquote></details>

Sure
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-NkscEb_DKhGk475GRSq:-NktD5rE8jvtjYVz1KdD:bb74ce2) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java#L121)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Save all EnforcementResultEntity in one call
</blockquote></details>

Sure

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/SSCAManagerApplication.java` line 321 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-NktIhNj-ya7X-tPIzGb:-NktIhNj-ya7X-tPIzGc:bdk7ku9) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/SSCAManagerApplication.java#L321)):*
> ```Java
> 
>   private void initializeServiceSecretKeys() {
>     VERIFICATION_SERVICE_SECRET.set(System.getenv(CVNextGenConstants.VERIFICATION_SERVICE_SECRET));
> ```

Why is this needed?

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/SSCAManagerApplication.java` line 321 at r2](https://reviewable.io/reviews/harness/harness-core/56133#-NktIhNj-ya7X-tPIzGb:-NktLZVy5167o7_2cWnO:b3hu6ir) ([raw file](https://github.com/harness/harness-core/blob/264f80da0096e2fcbdc68f0da867a76b85c63957/ssca-manager/service/src/main/java/io/harness/SSCAManagerApplication.java#L321)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

This is needed to authenticate with the CgManager. We need not use the constant from cvng constants. I have removed it in my local changes

**Comment by dhruv-harness** [comment]
trigger uts

**Review by deepharness — DISMISSED** [review]
> Reviewed 3 of 16 files at r1, 1 of 6 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: 1 change requests. 2. unresolved discussions.

**Comment by dhruv-harness** [comment]
trigger uts

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 19 files at r3, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56133)* status: :shipit: complete! ✓

**Review by harshjain12 — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]

**Pull request merged**
