### PR TITLE
[feat]: [CDS-50913]: Moving-repository-classes-to-separate-bazel-packages-in-…

### PR DESCRIPTION
**Pull request by markoharness**
…125-module

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42721)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
> Reviewed 80 of 80 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721)* status: 80 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
Let's discuss "contracts" module on call.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721#-:-NM3foPZ5TR5m6kZplD4:b-rlfszc)* status: 80 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — DISMISSED** [review]
> Reviewed 41 of 80 files at r1, 39 of 39 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721)* status: 39 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 30 of 39 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721#-:-NM964Y6-UwjOmR1rYP5:bnfp4nl)* status: 9 file(s) to review.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 9 of 39 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721#-:-NM96hif3VWDQm1k6nLJ:bnfp4nl)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721#-:-NMDGJLFD_H8ZB8OcXYP:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42721)* status: :shipit: complete! ✓

**Pull request merged**
