### PR TITLE
fix: [PL-24662]: Do selective full sync in case of h2g rename

### PR DESCRIPTION
**Pull request by abhinav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)

### CODE REVIEW

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: Some of the checks are too old. 3 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/32401#-N0V_2uHCqY2Dpbw83G1:-N0V_2uHCqY2Dpbw83G2:b-jftl4h) ([raw file](https://github.com/harness/harness-core/blob/494f1fb69fb2f0431b1ceae11abc3687dfd94e65/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java#L126)):*
> ```Java
>     Application app = null;
>     try {
>       app = yamlHelper.getApp(accountId, newPath);
> ```

does yamlHelper has isApp function ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/32401#-N0V_o1B42CmI-CpWPJv:-N0V_o1B42CmI-CpWPJw:bsnaxhj) ([raw file](https://github.com/harness/harness-core/blob/494f1fb69fb2f0431b1ceae11abc3687dfd94e65/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java#L126)):*
> ```Java
>     Application app = null;
>     try {
>       app = yamlHelper.getApp(accountId, newPath);
> ```

But this new app doesn't actually exists in harness yet right ? How does yamlHelper.getApp return the new app

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/32401#-N0V_2uHCqY2Dpbw83G1:-N0VjIPC4Qgkx8VCI0_m:b-e4adi) ([raw file](https://github.com/harness/harness-core/blob/494f1fb69fb2f0431b1ceae11abc3687dfd94e65/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java#L126)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

does yamlHelper has isApp function ?
</blockquote></details>

no it doesnt
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/32401#-N0V_o1B42CmI-CpWPJv:-N0Vjg2P29POpNz8Eing:b-8ilnb3) ([raw file](https://github.com/harness/harness-core/blob/494f1fb69fb2f0431b1ceae11abc3687dfd94e65/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java#L126)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

But this new app doesn't actually exists in harness yet right ? How does yamlHelper.getApp return the new app
</blockquote></details>

If it doesnt exist it throws exception?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/32401#-N0V_o1B42CmI-CpWPJv:-N0Vnn7i6d6h8xtdhq-x:b-sltnp3) ([raw file](https://github.com/harness/harness-core/blob/494f1fb69fb2f0431b1ceae11abc3687dfd94e65/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java#L126)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

If it doesnt exist it throws exception?
</blockquote></details>

But since this is a rename operation, then how does the app with the new name already exists?

This is part of git to harness flow right ?

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/32401#-N0V_o1B42CmI-CpWPJv:-N0_stAa0QAzu-tiE24T:bonxkte) ([raw file](https://github.com/harness/harness-core/blob/494f1fb69fb2f0431b1ceae11abc3687dfd94e65/400-rest/src/main/java/software/wings/service/impl/yaml/YamlChangeSetHelper.java#L126)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

But since this is a rename operation, then how does the app with the new name already exists?

This is part of git to harness flow right ?
</blockquote></details>

harness to git

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: Some of the checks are too old.

**Review by Fernando-Dourado — APPROVED** [review]

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
lgtm

**Review by lasdox — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32401)* status: :shipit: complete! ✓

**Pull request merged**
