### PR TITLE
feat: [CI-4715]: Update go-scm version 1.25.0

### PR DESCRIPTION
**Pull request by rutvijmehta-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34430)

### CODE REVIEW

**Review by jamie-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34430)* status: :shipit: complete! ✓

**Review by hemanthmantri — APPROVED** [review]

**Comment by rutvijmehta-harness** [comment]
trigger ti1

**Comment by rutvijmehta-harness** [comment]
trigger compile

**Comment by rutvijmehta-harness** [comment]
trigger ti2

**Comment by rutvijmehta-harness** [comment]
trigger ti3

**Comment by rutvijmehta-harness** [comment]
trigger ti4

**Comment by rutvijmehta-harness** [comment]
trigger ti0

**Review by jamie-harness — APPROVED** [review]

**Review by jamie-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34430)* status: :shipit: complete! ✓

**Review by jamie-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34430)* status: :shipit: complete! ✓

___
*[`product/ci/scm/go.sum` line 194 at r2](https://reviewable.io/reviews/harness/harness-core/34430#-N4udckEAo5IIdh_-HGb:-N4udckEAo5IIdh_-HGc:b-ar7xyy) ([raw file](https://github.com/harness/harness-core/blob/d7859d9d9b9ca01a925081eb5df9b0cf9d19e66e/product/ci/scm/go.sum#L194)):*
> ```
> github.com/drone/go-scm v1.23.1 h1:JL27huaUPBodZQosOPQwofeyRnm/DU5d5iVvD9w5k+o=
> github.com/drone/go-scm v1.23.1/go.mod h1:DFIJJjhMj0TSXPz+0ni4nyZ9gtTtC40Vh/TGRugtyWw=
> github.com/drone/go-scm v1.24.0 h1:wE6bP9gnuyyKJStnl6wl0npt/SBQumjE9jilQAcFy6Q=
> ```

let's remove those previous version sum in future changes. But we can merge this one if you are trying to get it in before branch cut.

**Review by jamie-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34430)* status: :shipit: complete! ✓

**Comment by rutvijmehta-harness** [comment]
*[`product/ci/scm/go.sum` line 194 at r2](https://reviewable.io/reviews/harness/harness-core/34430#-N4udckEAo5IIdh_-HGb:-N4ulPSY-GCvDXLmqx_a:b-wktkwc) ([raw file](https://github.com/harness/harness-core/blob/d7859d9d9b9ca01a925081eb5df9b0cf9d19e66e/product/ci/scm/go.sum#L194)):*
<details><summary><i>Previously, jamie-harness (Jamie Li) wrote…</i></summary><blockquote>

let's remove those previous version sum in future changes. But we can merge this one if you are trying to get it in before branch cut.
</blockquote></details>

I followed the steps here https://harness.atlassian.net/wiki/spaces/~240970147/pages/1990656655/Making+changes+to+the+SCM+service. I can remove these in a follow up patch if required

**Review by jamie-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34430)* status: :shipit: complete! ✓

___
*[`product/ci/scm/go.sum` line 194 at r2](https://reviewable.io/reviews/harness/harness-core/34430#-N4udckEAo5IIdh_-HGb:-N4umCF971UfxoeqieJS:b-gxo799) ([raw file](https://github.com/harness/harness-core/blob/d7859d9d9b9ca01a925081eb5df9b0cf9d19e66e/product/ci/scm/go.sum#L194)):*
<details><summary><i>Previously, rutvijmehta-harness (Rutvij Mehta) wrote…</i></summary><blockquote>

I followed the steps here https://harness.atlassian.net/wiki/spaces/~240970147/pages/1990656655/Making+changes+to+the+SCM+service. I can remove these in a follow up patch if required
</blockquote></details>

Not required. Can do it any time, maybe next time we touch this file.

**Pull request merged**
