### PR TITLE
fix: [SRM-14483]: shifting timezone logic to backend

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46371)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46371)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeHistoryView.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDebky6okYi7wIc5Yn:-NTDebky6okYi7wIc5Yo:b-pyv797) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeHistoryView.java#L27)):*
> ```Java
> 
>   DowntimeSpecDTO spec;
>   DowntimeSpecDTO downtimeDetails;
> ```

Why do we need this, we already have new startTime in spec



_Code quote:_
```Java
  DowntimeSpecDTO downtimeDetails;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDfsxmC1_diR8f8lsG:-NTDfsxmC1_diR8f8lsH:bg2cqqm) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java#L59)):*
> ```Java
>                       .downtimeDuration(((Downtime.OnetimeDurationBased) entity).getDowntimeDuration())
>                       .build())
>             .startTime(entity.getStartTime())
> ```

why are we not setting startdatetime here itself



_Code quote:_
```Java
 .startTime(entity.getStartTime())
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDg5gz9TiirOghvM4Z:-NTDg5gz9TiirOghvM4_:bhh594m) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java#L104)):*
> ```Java
>   @Override
>   public List<Pair<Long, Long>> getStartAndEndTimesForFutureInstances(OnetimeDowntimeSpec spec) {
>     long startTime = DateTimeUtils.getEpochValueFromDateString(spec.getStartDateTime(), spec.getTimezone());
> ```

This is not backward compatible, everywhere we have to take value from new field if available otherwise fall back to old field.



_Code quote:_
```Java
    long startTime = DateTimeUtils.getEpochValueFromDateString(spec.getStartDateTime(), spec.getTimezone());
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/RecurringDowntimeSpecDetailsTransformer.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDgNks7MkQtipKO6U6:-NTDgNks7MkQtipKO6U7:b-tp0k0e) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/RecurringDowntimeSpecDetailsTransformer.java#L35)):*
> ```Java
>         .downtimeDuration(spec.getDowntimeDuration())
>         .downtimeRecurrence(spec.getDowntimeRecurrence())
>         .startTime(DateTimeUtils.getEpochValueFromDateString(spec.getStartDateTime(), spec.getTimezone()))
> ```

set startDateTime here as well



_Code quote:_
```Java
.startTime(DateTimeUtils.getEpochValueFromDateString(spec.getStartDateTime(), spec.getTimezone()))
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/utils/DateTimeUtils.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDgZnE4-3k9IxTO7Tl:-NTDgZnE4-3k9IxTO7Tm:bbeblr7) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/utils/DateTimeUtils.java#L23)):*
> ```Java
>                                             .parseCaseInsensitive()
>                                             .appendPattern("yyyy-MM-dd hh:mm a")
>                                             .toFormatter(Locale.ENGLISH);
> ```

what error does it send if the datetime string we recieved is not in this format? Can we modify that error and send what the correct dateTimeFormat there as well. Will be helpful for terraform users.



_Code quote:_
```Java
                                            .appendPattern("yyyy-MM-dd hh:mm a")
                                            .toFormatter(Locale.ENGLISH);
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/downtime/services/impl/DowntimeServiceImplTest.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDh6TiBMOuj2w0EzUQ:-NTDh6TiBMOuj2w0EzUR:b9cm3s5) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/downtime/services/impl/DowntimeServiceImplTest.java#L205)):*
> ```Java
> 
>   @Test
>   @Owner(developers = VARSHA_LALWANI)
> ```

also please add UT for validating dls is correctly saved and returned



_Code quote:_
```Java
  @Owner(developers = VARSHA_LALWANI)
```

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46371)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeHistoryView.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDebky6okYi7wIc5Yn:-NTHZ1F108QaRvCyQrKj:boguobn) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/beans/DowntimeHistoryView.java#L27)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Why do we need this, we already have new startTime in spec
</blockquote></details>

will remove the spec field later
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDfsxmC1_diR8f8lsG:-NTHZ6KN2koHigHHz5da:bueykw3) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java#L59)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why are we not setting startdatetime here itself
</blockquote></details>

it is common, have set it outside in the parent function
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDg5gz9TiirOghvM4Z:-NTHZVII1Vs4qCK7NB63:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/OnetimeDowntimeSpecDetailsTransformer.java#L104)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

This is not backward compatible, everywhere we have to take value from new field if available otherwise fall back to old field.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/RecurringDowntimeSpecDetailsTransformer.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/46371#-NTDgNks7MkQtipKO6U6:-NTH_dFQE0FHUEI7bKbT:b98fd6f) ([raw file](https://github.com/harness/harness-core/blob/1405d9fa6ebc7a75510a33a0c03c61f526b32bab/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/RecurringDowntimeSpecDetailsTransformer.java#L35)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

set startDateTime here as well
</blockquote></details>

this is downtimeDetails, we don't have startDateTime here

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46371)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/impl/DowntimeServiceImpl.java` line 612 at r3](https://reviewable.io/reviews/harness/harness-core/46371#-NTMkRAcE1eMl4Ru1seD:-NTMkRAcE1eMl4Ru1seE:byi2qxj) ([raw file](https://github.com/harness/harness-core/blob/33176183dcd4ef5fbacaf16f24453ceae0b81c00/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/impl/DowntimeServiceImpl.java#L612)):*
> ```Java
>       DowntimeType downtimeType, DowntimeDetails downtimeDetails, String timeZone) {
>     DowntimeSpec downtimeSpec = downtimeTransformerMap.get(downtimeType).getDowntimeSpec(downtimeDetails, timeZone);
>     downtimeSpec.setStartDateTime(DateTimeUtils.getDateStringFromEpoch(downtimeDetails.getStartTime(), timeZone));
> ```

why are we setting it here if we have already set in the transformer method



_Code quote:_
```Java
  downtimeSpec.setStartDateTime(DateTimeUtils.getDateStringFromEpoch(downtimeDetails.getStartTime(), timeZone));
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/BuilderFactory.java` line 1953 at r3](https://reviewable.io/reviews/harness/harness-core/46371#-NTMleRkCYUBj3UCu7yk:-NTMleRl0T_2oo4VMqRp:b-hzoh0h) ([raw file](https://github.com/harness/harness-core/blob/33176183dcd4ef5fbacaf16f24453ceae0b81c00/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/BuilderFactory.java#L1953)):*
> ```Java
>                                       .endDateTime(dtf.format(endDateTime))
>                                       .build())
>                             .build())
> ```

Instead of modifying the current UT, can you add a new one atleast for create update validation so that we are sure it works for both fields sent from UI.



_Code quote:_
```Java
                  .type(DowntimeType.ONE_TIME)
                  .spec(OnetimeDowntimeSpec.builder()
                            .startTime(startTime)
                            .startDateTime(dtf.format(startDateTime))
                            .timezone("UTC")
                            .type(OnetimeDowntimeType.END_TIME)
                            .spec(OnetimeDowntimeSpec.OnetimeEndTimeBasedSpec.builder()
                                      .endTime(endTime)
                                      .endDateTime(dtf.format(endDateTime))
                                      .build())
                            .build())
```

**Review by deepak-harness — APPROVED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46371)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/RecurringDowntimeSpecDetailsTransformer.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/46371#-NTRookYAtqaI3P7Nkc8:-NTRookYAtqaI3P7Nkc9:b-msauxl) ([raw file](https://github.com/harness/harness-core/blob/33176183dcd4ef5fbacaf16f24453ceae0b81c00/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/transformer/RecurringDowntimeSpecDetailsTransformer.java#L108)):*
> ```Java
>         return currentStartTime + Duration.ofDays(7L * recurrence.getRecurrenceValue()).toSeconds();
>       case MONTH:
>         cal.setTimeInMillis(currentStartTime * 1000);
> ```

nit: we can use TimeUnit.SECONDS.toMillis (its much more readable and less prone to errors).

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 2 of 14 files at r1, 3 of 10 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46371#-:-NTXoxpT0XLldQwxu9tT:bnfp4nl)* status: 2. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 8 of 10 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46371)* status: 2. unresolved discussions.

**Pull request merged**
