### PR TITLE
feat: [PL-39616]: add admin API to disable IP allowlist for an account

### PR DESCRIPTION
**Pull request by sahibaCCM**
## Describe your changes
Added an Admin API to disable API allow-list for an account.

Tested for:
-> Disabling all the IPs in ipAllowlist DB [ng manager] and ip_allowlist DB [gateway]
-> Validated the Behaviour with invalid/ expired tokens.

Generated jwt token using adminPortalSecret & https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21331772440/Enable+Nextgen+Without+Using+Admin+Tool

https://github.com/harness/harness-core/assets/112424209/93180dbf-7a6d-40c9-9c87-78ce5ba88a76

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49956)

### CODE REVIEW

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger ut0

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49956)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustom.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/49956#-N_ZTiLME2CYzi8BzD-v:-N_ZTiLME2CYzi8BzD-w:b-emxy6x) ([raw file](https://github.com/harness/harness-core/blob/5baa82990bbafd34bf6a1dff97042384af12ffb6/120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustom.java#L18)):*
> ```Java
> public interface IPAllowlistRepositoryCustom {
>   Page<IPAllowlistEntity> findAll(Criteria criteria, Pageable pageable);
>   void disableIPAllowListWithAccountId(String accountIdentifier);
> ```

This should return boolean indicating if operation succeded or not. Check pattern for similar method in harness-core and follow best practice.
___
*[`120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustomImpl.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/49956#-N_ZTTjI7m2Kr96OV5Ex:-N_ZTTjI7m2Kr96OV5Ey:bxch0mk) ([raw file](https://github.com/harness/harness-core/blob/5baa82990bbafd34bf6a1dff97042384af12ffb6/120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustomImpl.java#L41)):*
> ```Java
>   @Override
>   public void disableIPAllowListWithAccountId(String accountIdentifier) {
>     Query query =
> ```

Shouldn't this method be generic and accept boolean to toggle enable/disable. I think we may have this need in future to enable IPAllowListWithAccountId if not now.

**Comment by sahibaCCM** [comment]
> ```java
> void disableIPAllowListWithAccount
> ```

We have made it to disable all the ipAllowlist as per the need; usecase of enabling all at once is not there as of now. We can make it generic when the need for it comes up.

For making it boolean, I can do the changes in the followup PR as we need to merge this one to do the testing on priority.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49956)* status: Some of the checks are too old. 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustom.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/49956#-N_ZTiLME2CYzi8BzD-v:-N_bczVAAbu8-J9pqx_j:bpg3ow) ([raw file](https://github.com/harness/harness-core/blob/5baa82990bbafd34bf6a1dff97042384af12ffb6/120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom/IPAllowlistRepositoryCustom.java#L18)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This should return boolean indicating if operation succeded or not. Check pattern for similar method in harness-core and follow best practice.
</blockquote></details>

Resolving as raising this as part of next PR.

**Review by meenakshi-harness — APPROVED** [review]

**Pull request merged**
