### PR TITLE
feat: [CDS-74212]: remove FFs from code

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
We have GA'd 2 FF's in Prod-1/2/3, removing them from code as well:
1. CDS_CUSTOM_STAGE_EXECUTION_DATA_SYNC
2. CDS_STEP_EXECUTION_DATA_SYNC

Tested locally if the data sync for dashboard is working fine

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52531)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52531)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/customstage/CustomStageStepTest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/52531#-Ndi_1cWCK_bgr6MkF4_:-Ndi_1cWCK_bgr6MkF4a:b7kls7w) ([raw file](https://github.com/harness/harness-core/blob/875d5eb12054c12923fc292a6a30162a858b6c26/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/customstage/CustomStageStepTest.java#L34)):*
> ```Java
>   @Rule public MockitoRule mockitoRule = MockitoJUnit.rule();
>   @Mock private PmsFeatureFlagHelper pmsFeatureFlagHelper;
>   @Mock ExecutorService dashboardExecutorService;
> ```

Is this intended

**Comment by RishabhGupta34** [comment]
> > Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/52531)_ status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/customstage/CustomStageStepTest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/52531#-Ndi_1cWCK_bgr6MkF4_:-Ndi_1cWCK_bgr6MkF4a:b7kls7w) ([raw file](https://github.com/harness/harness-core/blob/875d5eb12054c12923fc292a6a30162a858b6c26/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/customstage/CustomStageStepTest.java#L34)):_
> 
> > ```java
> >   @Rule public MockitoRule mockitoRule = MockitoJUnit.rule();
> >   @Mock private PmsFeatureFlagHelper pmsFeatureFlagHelper;
> >   @Mock ExecutorService dashboardExecutorService;
> > ```
> 
> Is this intended

yes, as the FF is now removed, the dashboardExecutorService was being called, and as it was null the test was failing

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52531)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/customstage/CustomStageStepTest.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/52531#-Ndi_1cWCK_bgr6MkF4_:-Ndi_Ulq1WApTrBmRAKU:btn461w) ([raw file](https://github.com/harness/harness-core/blob/875d5eb12054c12923fc292a6a30162a858b6c26/pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/customstage/CustomStageStepTest.java#L34)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

yes, as the FF is now removed, the dashboardExecutorService was being called, and as it was null the test was failing
</blockquote></details>

Got it

**Review by sahilhindwani-harness — APPROVED** [review]

**Pull request merged**
