### PR TITLE
fix: [PIE-2585]: Introducing application level lock during graph generation.

### PR DESCRIPTION
**Pull request by archit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/30576#-MvNFM48-2zGWDfs372H:-MvNFM48-2zGWDfs372I:blececx) ([raw file](https://github.com/harness/harness-core/blob/4ad1670f4f8836889c94e45a7f0043eb95bdbae4/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L81)):*
> ```Java
>   public void updateGraph(String planExecutionId) {
>     AcquiredLock<?> lock;
>     String lockName = "GRAPH_LOCK_" + planExecutionId;
> ```

Convert this to try with resources format with the try below
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 153 at r2](https://reviewable.io/reviews/harness/harness-core/30576#-MvNGLro1cPS3hEY9sQQ:-MvNGLro1cPS3hEY9sQR:brpjaa1) ([raw file](https://github.com/harness/harness-core/blob/4ad1670f4f8836889c94e45a7f0043eb95bdbae4/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L153)):*
> ```Java
>       }
>     } finally {
>       persistentLocker.destroy(lock);
> ```

Acquired loc is auto closable so you would not need to to this once you move to try

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java, line 84 at r2](https://reviewable.io/reviews/harness/harness-core/30576#-MvNGSe51jBJAVTr0gh6:-MvNGSe51jBJAVTr0gh7:b-pi9d9n) ([raw file](https://github.com/harness/harness-core/blob/4ad1670f4f8836889c94e45a7f0043eb95bdbae4/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java#L84)):*
> ```Java
>     } else if (!("ONPREM".equals(deployMode) || "KUBERNETES_ONPREM".equals(deployMode))) {
>       String versionPrefix = "v-" + versionInfo.getVersion().replace('.', '-') + "-";
>       String versionedAuthority = authority;
> ```

remove this

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/30576#-MvNFM48-2zGWDfs372H:-MvNkjP24bYUfHy-Ugtz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ad1670f4f8836889c94e45a7f0043eb95bdbae4/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L81)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Convert this to try with resources format with the try below
</blockquote></details>

Done.
___
*[860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, line 153 at r2](https://reviewable.io/reviews/harness/harness-core/30576#-MvNGLro1cPS3hEY9sQQ:-MvNkjzc37BIiCqZr7sm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ad1670f4f8836889c94e45a7f0043eb95bdbae4/860-orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L153)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Acquired loc is auto closable so you would not need to to this once you move to try
</blockquote></details>

Done.
___
*[910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java, line 84 at r2](https://reviewable.io/reviews/harness/harness-core/30576#-MvNGSe51jBJAVTr0gh6:-MvNkkt78VPCZXpxMC8Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4ad1670f4f8836889c94e45a7f0043eb95bdbae4/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceDriverGrpcClientModule.java#L84)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

**Comment by archit-harness** [comment]
trigger messagecheck

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576#-:-MvO1BojDAyTu0UGHZ-8:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 1 file(s) to review.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 1 file(s) to review.

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576)* status: 1 file(s) to review.

**Review by hextechpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576#-:-MvODzzO6fz-5ZSa6OmI:bnfp4nl)* status: 1 file(s) to review.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30576#-:-MvOF1lfCthIihCHTirL:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
