### PR TITLE
fix: [DEL-4811]: delegate from NG and CG can have same hostnames

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Goal is to allow delegates from NG and CG to use the same hostnames

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38719)

### CODE REVIEW

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38719)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 261 at r1](https://reviewable.io/reviews/harness/harness-core/38719#-NECfErR9To9edPBrsyz:-NECfErR9To9edPBrsz-:b-mu0t41) ([raw file](https://github.com/harness/harness-core/blob/6d2c9d5356dd97a289c0af3b41bb6ccb5e76120b/120-ng-manager/config.yml#L261)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-false}
> ```

remove this line
___
*[`260-delegate/config-delegate.yml` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/38719#-NEIHxPn2CxjVrmAyuHW:-NEIHxPn2CxjVrmAyuHX:b-rtwfym) ([raw file](https://github.com/harness/harness-core/blob/bf72726dc498b918d36e26de4ee4ae34e8e2a4e1/260-delegate/config-delegate.yml#L19)):*
> ```YAML
> clientToolsDownloadDisabled: false
> installClientToolsInBackground: true
> localDelegate: true
> ```

having one more boolean flag doesn't make too much sense. As delegate doesn't have a new type as "Local". On the other hand, having too many boolean flags makes it hard to manage, difficult for developers to understand the combinations too. For example, how about  ( Local+CG+kubernetes )   (Local + NG + Docker)  ... etc ? 
Maybe remove this. 

I agree to have isNGDelegate and even DelegateType to come from config.yaml, in our DelegateAgentServiceImpl.java, both these configurations load from yaml file.

During the process of building docker images, the config.yaml fill will be populated by environment variables. 

can we do this way? 
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 458 at r1](https://reviewable.io/reviews/harness/harness-core/38719#-NECi6Z8AfRlAX7gvemD:-NECi6Z9CPaC52S8ZkXP:bgvkex5) ([raw file](https://github.com/harness/harness-core/blob/bf72726dc498b918d36e26de4ee4ae34e8e2a4e1/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L458)):*
> ```Java
>   private void initDelegateProcess(final boolean watched) {
>     try {
>       if (delegateConfiguration.isLocalDelegate() && delegateConfiguration.isNGDelegate()) {
> ```

if we do the way I described above, we can remove this block

**Review by xingchi-jin — COMMENTED** [review]
regardless of the opinion of implementation, i like this change. It makes dev life easier 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38719#-:-NEILbNGEnprYQG91rnP:bj07ua2)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38719)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/config-delegate.yml` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/38719#-NEIHxPn2CxjVrmAyuHW:-NFIarqP4HP26lbwcZar:b-jt0gc4) ([raw file](https://github.com/harness/harness-core/blob/bf72726dc498b918d36e26de4ee4ae34e8e2a4e1/260-delegate/config-delegate.yml#L19)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

having one more boolean flag doesn't make too much sense. As delegate doesn't have a new type as "Local". On the other hand, having too many boolean flags makes it hard to manage, difficult for developers to understand the combinations too. For example, how about  ( Local+CG+kubernetes )   (Local + NG + Docker)  ... etc ? 
Maybe remove this. 

I agree to have isNGDelegate and even DelegateType to come from config.yaml, in our DelegateAgentServiceImpl.java, both these configurations load from yaml file.

During the process of building docker images, the config.yaml fill will be populated by environment variables. 

can we do this way? 
</blockquote></details>

We can do that, but that will be big change in delegate along with manager, which has to be done in backward compatible fashion. For now we can keep these flags, and can edit once we have other changes done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 458 at r1](https://reviewable.io/reviews/harness/harness-core/38719#-NECi6Z8AfRlAX7gvemD:-NFIbRYp4ibs7DFB-E0K:b-3jms2f) ([raw file](https://github.com/harness/harness-core/blob/bf72726dc498b918d36e26de4ee4ae34e8e2a4e1/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L458)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

if we do the way I described above, we can remove this block 
</blockquote></details>

Yeah, that change need some effort, so for quick workaround let's do in this way.

**Comment by gaurav-jain1** [comment]
trigger ti1

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38719)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/config-delegate.yml` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/38719#-NEIHxPn2CxjVrmAyuHW:-NFQkIOoBGA6N-h8i7ZH:b-fu92ss) ([raw file](https://github.com/harness/harness-core/blob/bf72726dc498b918d36e26de4ee4ae34e8e2a4e1/260-delegate/config-delegate.yml#L19)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We can do that, but that will be big change in delegate along with manager, which has to be done in backward compatible fashion. For now we can keep these flags, and can edit once we have other changes done.
</blockquote></details>

I am looking at organize our delegate configurations overall. I can take the change.

For this PR, do you mind define a combined flag - localNGDelegate for now?

I think it serves better for the purpose here. because for 1. the condition is 'if (delegateConfiguration.isLocalDelegate() && delegateConfiguration.isNGDelegate()) ', it's a combined condition.  2. there is already a ng variable in delegate that is loaded directly from environment

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38719)* status: 1. unresolved discussions.

**Pull request merged**
