### PR TITLE
fix: [PL-27555]: Stop validating readOnly vaults in PPT's

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Return the validation as success without creating secret if it is a readOnly vault

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38454)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38454)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/38454#-NDmLS4bB3aBegxJISrO:-NDmLS4bB3aBegxJISrP:buuxfrc) ([raw file](https://github.com/harness/harness-core/blob/9cb9811370080ee3144298133e1a647b35005eee/890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java#L54)):*
> ```Java
>       UpsertSecretTaskParameters upsertSecretTaskParameters =
>           getTaskParams(connectorValidationParams, accountIdentifier);
>       if ((upsertSecretTaskParameters.getEncryptionConfig() instanceof VaultConfig)
> ```

Why there is need for checking instanceof? Can't we use ConnectorType.VAULT.equals(connectorValidationParams.getConnectorType())

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38454)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/38454#-NDmLS4bB3aBegxJISrO:-NDmMwZy2jBTfH42eZ1j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9cb9811370080ee3144298133e1a647b35005eee/890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java#L54)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why there is need for checking instanceof? Can't we use ConnectorType.VAULT.equals(connectorValidationParams.getConnectorType())
</blockquote></details>

Done.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38454)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/38454#-NDmLS4bB3aBegxJISrO:-NDmRELr7eZtToth0pG-:b-uevs4s) ([raw file](https://github.com/harness/harness-core/blob/9cb9811370080ee3144298133e1a647b35005eee/890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java#L54)):*
<details><summary><i>Previously, VikasMaddukuriHarness (VikasMaddukuriHarness) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

after discussion, we agreed on using instance of rather than type as it is safer to use instanceOf because the next condition requires a typecasting.

**Review by nishantsaini20 — APPROVED** [review]
Approving as UT will be a separate task.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38454#-:-NDmRZ0C0hEF2yrP9e5K:b-9e522g)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38454)* status: :shipit: complete! ✓

**Pull request merged**
