### PR TITLE
fix: [PL-22402]: added validations on trigger API

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30639)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30639)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 117 at r2](https://reviewable.io/reviews/harness/harness-core/30639#-MvXizJ1-B1SazcL4t5p:-MvXizJ1-B1SazcL4t5q:b5bioty) ([raw file](https://github.com/harness/harness-core/blob/9c7b9c5736fe1054eafc6419e4b30515275eb52e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L117)):*
> ```Java
> 
>   public boolean validateIfScmUserProfileIsSet(String accountIdentifier) {
>     List<SourceCodeManagerDTO> sourceCodeManagerDTOS = sourceCodeManagerService.get(accountIdentifier);
> ```

Here user is automatically taken from principal context?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 119 at r2](https://reviewable.io/reviews/harness/harness-core/30639#-MvXitIj5g3axYme-VTg:-MvXitIj5g3axYme-VTh:b2c7ywq) ([raw file](https://github.com/harness/harness-core/blob/9c7b9c5736fe1054eafc6419e4b30515275eb52e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L119)):*
> ```Java
>     List<SourceCodeManagerDTO> sourceCodeManagerDTOS = sourceCodeManagerService.get(accountIdentifier);
>     if (sourceCodeManagerDTOS.isEmpty()) {
>       throw new InvalidRequestException("We don’t have your git credentials for the selected folder."
> ```

we can simply say that SCM isn't set, right? We don't need to mention selected folder etc.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30639)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30639)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java, line 117 at r2](https://reviewable.io/reviews/harness/harness-core/30639#-MvXizJ1-B1SazcL4t5p:-MvXjSG_4NIfbent5GDV:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/9c7b9c5736fe1054eafc6419e4b30515275eb52e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/UserProfileHelper.java#L117)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here user is automatically taken from principal context?
</blockquote></details>

yes

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30639#-:-MvXtM8z2Z3t2vDMYDY4:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
