### PR TITLE
feat: [SSCA-1064]: Add implementation for Remediation APIs

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

1. Includes fixes to the spec
2. Implemenattion for all the remaining APIs

What is left?
1. Adding details of the tickets
2. RBAC

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57135)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger ut0, ut4, ut5

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57135)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/api/RemediationTrackerApiUtils.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-NmiUCzqDm2OXrLH07Pv:-NmiUCzr2bRaXPhDOBjd:b-bjrq1h) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/api/RemediationTrackerApiUtils.java#L17)):*
> ```Java
> 
> @Slf4j
> public class RemediationTrackerApiUtils {
> ```

can we name it based on the usage , don't create generic names for utils. 
https://stackoverflow.com/questions/3340032/are-utility-classes-evil
https://lostechies.com/chrismissal/2009/06/01/anti-patterns-and-worst-practices-utils-class/
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-NmiTmz34HTRGf49X7oe:-NmiTmz46UHCWVw4Mmb8:b-oorfnx) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L278)):*
> ```Java
> 
>   @Override
>   public PipelineInfo getPipelineInfo(
> ```

move it to pipeline utils 
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-NmibvPR0ABb07A6sIEf:-NmibvPR0ABb07A6sIEg:bey3f0o) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L109)):*
> ```Java
> 
>   @Inject private UserClient userClient;
> ```

this class has more than 500 lines of code , consider breaking it down 
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 163 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-NmiQPRaDKwLaeoMRwsp:-NmiQPRaDKwLaeoMRwsq:b-3yxcl1) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L163)):*
> ```Java
> 
>     repository.update(new Query(criteria), update);
>     updateArtifactsAndEnvironments(remediationTracker);
> ```

Why we are have 2 updates on repo can't we club them , also this code is not fault tolerant 
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 206 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-NmiXwJ5CZVGtuCwkvDv:-NmiXwJ61Hop6LWxVsY2:bwxy7nb) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L206)):*
> ```Java
>     if (latestArtifact != null) {
>       PipelineInfo pipeline = artifactService.getPipelineInfo(accountId, orgId, projectId, latestArtifact);
>       response.setBuildPipeline(pipeline);
> ```

this will be part of mapper 
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 496 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-Nmiaa_5BFJAtvRJAOtU:-Nmiaa_5BFJAtvRJAOtV:b-grb8xk) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L496)):*
> ```Java
> 
>   @Override
>   public List<io.harness.spec.server.ssca.v1.model.EnvironmentInfo> getAllEnvironmentsInArtifact(String accountId,
> ```

rename to getAllEnvironmentsForArtifact
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 744 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-NmibV2R4b3rB1mWNfFx:-NmibV2R4b3rB1mWNfFy:btku5wq) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L744)):*
> ```Java
>   }
> 
>   private List<io.harness.spec.server.ssca.v1.model.EnvironmentInfo> buildEnvironmentInfos(
> ```

this should be part of mapper
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java` line 757 at r3](https://reviewable.io/reviews/harness/harness-core/57135#-Nmib0fuDAYxufPgNr60:-Nmib0fuDAYxufPgNr61:b-2akg2t) ([raw file](https://github.com/harness/harness-core/blob/9caf9fc4e0b2a303fa1b744d25566160cadaee31/ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java#L757)):*
> ```Java
>   }
> 
>   private boolean isEnvironmentTypeMatch(EnvironmentTypeFilter environmentType, EnvType envType) {
> ```

put it as a part of EnvironmentTypeFilter

**Review by Varsha-lalwani — COMMENTED** [review]
@deepharness Can I address your comments in next PR? Deepesh need these changes.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57135#-:-NminjCe2XS-4ZB3vQhu:bzb7oru)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by deepharness — APPROVED** [review]
> Reviewed 11 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57135)* status: <span>:shipit:</span> complete! ✓

**Pull request merged**
