### PR TITLE
feat: [DEL-4054]: remove perpetualTaskExecutor and use common thread …

### PR DESCRIPTION
**Pull request by arpit3107**
…pool

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: :shipit: complete! ✓

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 832 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2GoqhA6bHod9Tht3Ea:-N2GoqhA6bHod9Tht3Eb:b-vfv9qg) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L832)):*
> ```Java
>   }
> 
>   // TODO: I dont think we need to club this pool also (remove comment before merging)
> ```

Remove comment

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: :shipit: complete! ✓

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 838 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2L22vR6sDJPBqtn0Fx:-N2L22vR6sDJPBqtn0Fy:b91ojxm) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L838)):*
> ```Java
>   public ScheduledExecutorService perpetualTaskTimeoutExecutor() {
>     return new ScheduledThreadPoolExecutor(40,
>         new ThreadFactoryBuilder()
> ```

Can we get rid of this tp as well ?



_Code quote:_
```Java
  @Provides
  @Singleton
  @Named("perpetualTaskTimeoutExecutor")
  public ScheduledExecutorService perpetualTaskTimeoutExecutor() {
    return new ScheduledThreadPoolExecutor(40,
        new ThreadFactoryBuilder()
            .setNameFormat("perpetual-task-timeout-%d")
            .setPriority(Thread.NORM_PRIORITY)
            .build());
  }
```
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2L1TXq3RPjVWL-8A5E:-N2L1TXq3RPjVWL-8A5F:b-kkp0fv) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java#L200)):*
> ```Java
> 
>       PerpetualTaskLifecycleManager perpetualTaskLifecycleManager =
>           new PerpetualTaskLifecycleManager(task.getTaskId(), context, factoryMap, perpetualTaskServiceGrpcClient,
> ```

What executor will be there in this map, looks like eventual execution of perpetual task depends on this.



_Code quote:_
```Java
factoryMap
```
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2L2ArE5jORJIQjHPGU:-N2L2ArE5jORJIQjHPGV:baecjkw) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java#L207)):*
> ```Java
>           log.info("Starting perpetual task with id: {}.", task.getTaskId().getId());
>           ScheduledFuture<?> taskHandle = perpetualTaskTimeoutExecutor.scheduleWithFixedDelay(
>               new Schedulable("Throwable while executing perpetual task", perpetualTaskLifecycleManager::startTask),
> ```

We are scheduling task on perpetualTaskTimeoutExecutor, which again schedule task on timelimiter and taskexecutor, can you see if we can get rid of this double assignment ?



_Code quote:_
```Java
          ScheduledFuture<?> taskHandle = perpetualTaskTimeoutExecutor.scheduleWithFixedDelay(
              new Schedulable("Throwable while executing perpetual task", perpetualTaskLifecycleManager::startTask),
```

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/33245#-N33LnoT5SLyEvfsaNxk:-N33LnoT5SLyEvfsaNxl:btbpa04) ([raw file](https://github.com/harness/harness-core/blob/ffa09de644f65db1e6faf00989f7d3e4bbec0d14/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java#L207)):*
> ```Java
>           log.info("Starting perpetual task with id: {}.", task.getTaskId().getId());
>           ScheduledFuture<?> taskHandle = perpetualTaskTimeoutExecutor.scheduleWithFixedDelay(
>               new Schedulable("Throwable while executing perpetual task", perpetualTaskLifecycleManager::startTask),
> ```

Arpit, can we convert log.debug to log.error in catch block inside io.harness.perpetualtask.PerpetualTaskLifecycleManager#startTask

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 838 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2L22vR6sDJPBqtn0Fx:-N3EwYF-6p8vdgnDiv9Q:bgq04ng) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L838)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can we get rid of this tp as well ?
</blockquote></details>

not as part of this pr
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2L1TXq3RPjVWL-8A5E:-N3ExAZM8kcP7jzWA9PP:blsznmg) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java#L200)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

What executor will be there in this map, looks like eventual execution of perpetual task depends on this.
</blockquote></details>

Yes the final execution depends on this. And threadpool is perpetualTaskTimeLimiter, which gets created by perpetualTaskExecutor i.e 
@Named("taskExecutor") ThreadPoolExecutor perpetualTaskExecutor
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2L2ArE5jORJIQjHPGU:-N3ExkZl8fUy9wZJACsS:b1p46pu) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java#L207)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We are scheduling task on perpetualTaskTimeoutExecutor, which again schedule task on timelimiter and taskexecutor, can you see if we can get rid of this double assignment ?
</blockquote></details>

Not as part of this pr.
___
*[`260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/33245#-N33LnoT5SLyEvfsaNxk:-N3ExshtCJhHX_kjVLvl:b-kyom0u) ([raw file](https://github.com/harness/harness-core/blob/ffa09de644f65db1e6faf00989f7d3e4bbec0d14/260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java#L207)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Arpit, can we convert log.debug to log.error in catch block inside io.harness.perpetualtask.PerpetualTaskLifecycleManager#startTask
</blockquote></details>

Yes, good catch. Done

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java` line 832 at r1](https://reviewable.io/reviews/harness/harness-core/33245#-N2GoqhA6bHod9Tht3Ea:-N3ThMQt9grB7zs2_saJ:b-fvdvxp) ([raw file](https://github.com/harness/harness-core/blob/65a204c155034d6e7b8f3f6a458abd2cb06b6dfd/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L832)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Remove comment 
</blockquote></details>

@arpit3107 please address this comment

**Comment by arpit3107** [comment]
> 

I have removed that comment. But still its showing on reviewable, but not on github

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: 1 change requests. 4. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33245)* status: :shipit: complete! ✓

**Pull request merged**
