### PR TITLE
feat: [PL-30294]: refactored settings validation to include enforcement validation

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added support for enforcements framework based validations in settings framework.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdEYGr1EHzEyxepYZ5:-NLdEYGr1EHzEyxepYZ6:ba8i94e) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java#L39)):*
> ```Java
> 
>   public static FeatureRestrictionName getFeatureRestrictionName(String settingIdentifier) {
>     return registrar.get(settingIdentifier).getFeatureRestrictionName();
> ```

null check. If wrong settingIdentifier is passed then it will result in NPE.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdEgDr64IV94PLragP:-NLdEgDs9ylGwnQ_O_sn:b-g009ho) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java#L43)):*
> ```Java
> 
>   public static Class<? extends SettingValidator> getCustomValidator(String settingIdentifier) {
>     return registrar.get(settingIdentifier).getSettingValidator();
> ```

null check
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdEit75fIi-AonCNqh:-NLdEit75fIi-AonCNqi:b-g009ho) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java#L47)):*
> ```Java
> 
>   public static Class<? extends SettingEnforcementValidator> getEnforcementValidator(String settingIdentifier) {
>     return registrar.get(settingIdentifier).getSettingEnforcementValidator();
> ```

null check
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdFaH97MvgNz8n1ufW:-NLdFaH97MvgNz8n1ufX:bnurbwt) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L35)):*
> ```Java
>         getResponse(enforcementClient.getFeatureRestrictionMetadata(featureRestrictionName, accountIdentifier));
>     Edition edition = featureRestrictionMetadataDTO.getEdition();
>     RestrictionMetadataDTO currentRestriction = featureRestrictionMetadataDTO.getRestrictionMetadata().get(edition);
> ```

Can getRestrictionMetadata() return null?
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdFsDq9QFIUFc1TgLK:-NLdFsDq9QFIUFc1TgLL:bej74gd) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L45)):*
> ```Java
>               String.format("{} cannot be grater than {} for your account plan", newSettingDTO.getName(), limit));
>         }
>         return;
> ```

This can be extracted as method. With more restriction type switch case block can grow huge.



_Code quote:_
```Java
        Long limit = ((StaticLimitRestrictionMetadataDTO) currentRestriction).getLimit();
        Long settingValue = Long.parseLong(newSettingDTO.getValue());
        if (settingValue > limit) {
          throw new InvalidRequestException(
              String.format("{} cannot be grater than {} for your account plan", newSettingDTO.getName(), limit));
        }
        return;
```

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdEYGr1EHzEyxepYZ5:-NLd_NCpB5rAF1h8LlnV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java#L39)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

null check. If wrong settingIdentifier is passed then it will result in NPE.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdEgDr64IV94PLragP:-NLd_NT4A3PXEEY5Zgmw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java#L43)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

null check
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdEit75fIi-AonCNqh:-NLd_Np-2kOvZmlAEBEG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/SettingsValidatorFactory.java#L47)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

null check
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdFaH97MvgNz8n1ufW:-NLd_PSq1U4BaHto1twG:b-gu5vs0) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L35)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can getRestrictionMetadata() return null?
</blockquote></details>

Added null check and try-catch for it.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/42491#-NLdFsDq9QFIUFc1TgLK:-NLd_Tz0BcRNKp7BMXY5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0ffbf39a93bb9e69f6d6dae42255f99c0b456f0a/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L45)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This can be extracted as method. With more restriction type switch case block can grow huge.
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/42491#-NLdbgJ3-8uxm7q-h-eO:-NLdbgJ3-8uxm7q-h-eP:bqmigv7) ([raw file](https://github.com/harness/harness-core/blob/904dce4c71b28fa48b0e225e36ec64c07e3bb1e8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L32)):*
> ```Java
> 
>   @Override
>   public void validate(String accountIdentifier, FeatureRestrictionName featureRestrictionName,
> ```

Add UT
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/42491#-NLdaESwEWmhtDpzatXN:-NLdaESwEWmhtDpzatXO:b-t852xc) ([raw file](https://github.com/harness/harness-core/blob/904dce4c71b28fa48b0e225e36ec64c07e3bb1e8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L42)):*
> ```Java
>           "[SettingEnforcementValidator]: Error occurred while fetching enforcement metadata for featureRestrictionName: {}. Skipping the validation.",
>           featureRestrictionName, ex);
>       return;
> ```

validation should fail in case of exception else there is a probability of storing wrong value against a setting
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/42491#-NLdaqRRC28sboiPLweK:-NLdaqRRC28sboiPLweL:b-7smvhi) ([raw file](https://github.com/harness/harness-core/blob/904dce4c71b28fa48b0e225e36ec64c07e3bb1e8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L56)):*
> ```Java
>       case STATIC_LIMIT:
>         checkStaticMaxLimit(currentRestriction, newSettingDTO);
>         return;
> ```

break

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/42491#-NLdbgJ3-8uxm7q-h-eO:-NLfX8Eo4a5F4EAtP-4f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/904dce4c71b28fa48b0e225e36ec64c07e3bb1e8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L32)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add UT
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/42491#-NLdaESwEWmhtDpzatXN:-NLfX8vNDnaFmyfrzV8Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/904dce4c71b28fa48b0e225e36ec64c07e3bb1e8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

validation should fail in case of exception else there is a probability of storing wrong value against a setting
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/42491#-NLdaqRRC28sboiPLweK:-NLfXAHlDwwnU80ylQEH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/904dce4c71b28fa48b0e225e36ec64c07e3bb1e8/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidator.java#L56)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

break
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java` line 39 at r4](https://reviewable.io/reviews/harness/harness-core/42491#-NLfp1Tc6NkGjo5AN5ub:-NLfp1Tc6NkGjo5AN5uc:b-v9zoeh) ([raw file](https://github.com/harness/harness-core/blob/fb8134a9f5370d7e1131457aac0937844acb8a77/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java#L39)):*
> ```Java
> import retrofit2.Response;
> 
> public class EnforcementMaxLimitValidatorTest extends CategoryTest {
> ```

Missing cases for exceptions.
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/42491#-NLfov6MErgUklPN1LG6:-NLfov6MErgUklPN1LG7:bc6rrf1) ([raw file](https://github.com/harness/harness-core/blob/fb8134a9f5370d7e1131457aac0937844acb8a77/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java#L72)):*
> ```Java
>         .thenReturn(request);
> 
>     enforcementMaxLimitValidator.validate(accountIdentifier, featureRestrictionName, settingDTO, settingDTO);
> ```

What is validated here? Method calls can be verified
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/42491#-NLfpDIm1F5oYJooFcm9:-NLfpDIm1F5oYJooFcmA:bn4ckpm) ([raw file](https://github.com/harness/harness-core/blob/fb8134a9f5370d7e1131457aac0937844acb8a77/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java#L98)):*
> ```Java
>         .thenReturn(request);
> 
>     enforcementMaxLimitValidator.validate(accountIdentifier, featureRestrictionName, settingDTO, settingDTO);
> ```

compare for error message as well.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java` line 39 at r4](https://reviewable.io/reviews/harness/harness-core/42491#-NLfp1Tc6NkGjo5AN5ub:-NLq_7-527oE4CiMPLJZ:b-jpvea5) ([raw file](https://github.com/harness/harness-core/blob/fb8134a9f5370d7e1131457aac0937844acb8a77/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java#L39)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Missing cases for exceptions.
</blockquote></details>

Added tests for all failure cases
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/42491#-NLfov6MErgUklPN1LG6:-NLq_AGV5TPSQeRnsLzg:b-lx4sw3) ([raw file](https://github.com/harness/harness-core/blob/fb8134a9f5370d7e1131457aac0937844acb8a77/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java#L72)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What is validated here? Method calls can be verified
</blockquote></details>

Here, we want to primarily verify that the validation runs successfully without any failure. I have now added a method call check for the enforcements client as well.
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/42491#-NLfpDIm1F5oYJooFcm9:-NLq_ThnCMxgqjWMBvT5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb8134a9f5370d7e1131457aac0937844acb8a77/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/services/impl/validators/enforcement/EnforcementMaxLimitValidatorTest.java#L98)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

compare for error message as well.
</blockquote></details>

Done.

**Comment by tiwaritejas** [comment]
trigger ti1

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 1 of 3 files at r2, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42491)* status: :shipit: complete! ✓

**Pull request merged**
