### PR TITLE
feat: [PIE-9107]: Allow user to mark a running stage as Failure, and Failure Strategy to kick in 

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Introduced a new PlanExecutionInterruptType _UserMarkedFailure_ basically which lets user manually mark all the stages/steps as failure and then failure strategies gets kicked in

Tests Done :-
* Initiated a _UserMarkedFailure_ Interrupt in service step/ Infrastructure step, It failed with appropiate error message - working fine
* Initiated a _UserMarkedFailure_ Interrupt after approval step starts step, It failed with appropiate error message - working fine
* Initiated a _UserMarkedFailure_ Interrupt after approval step starts step, and marked failure strategies as Mark as Success/Aborted , It moved to respective success/aborted status - working fine
* Initiated a _UserMarkedFailure_ Interrupt for a particular node execution, i.e shell script, , it failed with proper error message
* Tried hitting 2 diff interrupts at once with minor millisecond difference, only first interrupt was taken into account and pipeline was in consistent state

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45884)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/UserMarkedFailAllInterruptHandler.java` line 84 at r4](https://reviewable.io/reviews/harness/harness-core/45884#-NS4gpn_Dbm1iPaddL4N:-NS4gpn_Dbm1iPaddL4O:bevbcya) ([raw file](https://github.com/harness/harness-core/blob/8dcfd03d82abab896aa23a0e6e1815069ea48ad3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/UserMarkedFailAllInterruptHandler.java#L84)):*
> ```Java
> 
>   private Interrupt processInterrupt(@Valid @NonNull Interrupt interrupt, List<Interrupt> interrupts) {
>     if (isPresent(interrupts, presentInterrupt -> presentInterrupt.getType() == InterruptType.USER_MARKED_FAIL_ALL)) {
> ```

This condition is good for first cut but we should eventually allow user to give multiple interrupts of this type.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/UserMarkedFailAllInterruptHandler.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/45884#-NS4i0aA1jLJWzh50_zu:-NS4i0aB4siZXN90BK48:b1rbuca) ([raw file](https://github.com/harness/harness-core/blob/8dcfd03d82abab896aa23a0e6e1815069ea48ad3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/UserMarkedFailAllInterruptHandler.java#L105)):*
> ```Java
>   public Interrupt handleInterruptForNodeExecution(Interrupt interrupt, String nodeExecutionId) {
>     try (AutoLogContext ignore = interrupt.autoLogContext()) {
>       log.info("Stating to handle interrupt for Node Execution");
> ```

nit: spelling: Starting

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 9 of 14 files at r3, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45884)* status: 21 file(s) to review. 0 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 9 of 14 files at r3, 1 of 5 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45884)* status: 11 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 7 files at r1, 2 of 14 files at r3, 1 of 1 files at r4, 1 of 5 files at r5, 1 of 1 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45884)* status: 10 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 2 of 14 files at r3, 1 of 1 files at r4, 2 of 5 files at r5, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45884)* status: Waiting on team(s): sto.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45884)* status: 3 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Pull request merged**
