### PR TITLE
fix: [PL-43761]: fix error in search term in userGroup list API

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
fix error in search term in userGroup list API
We have implemented regex search with the text user searches on search bar, Now if someone enters any special character in search term that will be considered as regex pattern and then we try to match that with name of the entity. 
But this pattern may be wrong many times and thus query throws error internally.
Suppose in searchTerm I put abc( , this is incorrect regex pattern and will throw error internally and API will show 500.

Fix: 
In usergroup flow, we will check the search term whether it is valid regex pattern, if its invalid regex pattern we will throw error to user that search term is invalid regex pattern. This will solve the error that we are seeing right now. 

Tests- 
tested locally and added Uts as well
Screenshot 2024-01-09 at 9 16 04 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57413)

### CODE REVIEW

**Review by pbarapatre10 — APPROVED** [review]
Just ensure the below:

- Since we are adding regex check, was there any pattern or search term for which the filter worked earlier and might give exception with the current change?
- If we are going more restrictive in the search term, we need to be cautious and inform Product, Customers appropriately, as it will be considered as a breaking API change w.r.t. allowed search filter

Also, ensure release notes are properly added with details
Thanks

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57413#-:-NnmHaQiBg95uCXFbbHl:bnfp4nl)* status: 2 file(s) to review.

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
> Just ensure the below:
> 
> * Since we are adding regex check, was there any pattern or search term for which the filter worked earlier and might give exception with the current change?
> * If we are going more restrictive in the search term, we need to be cautious and inform Product, Customers appropriately, as it will be considered as a breaking API change w.r.t. allowed search filter
> 
> Also, ensure release notes are properly added with details Thanks

So, @pbarapatre10 
- regex check has been added so that we can catch and show the exception before to user. Earlier exception was coming while creating query which is not passed correctly and 500 is coming. So, there is no such case which was working earlier and will not work now.
- we are not making any changes with respect to product, its just improving the error, but yes we can specify in doc that search term willbe considered as regex pattern.

**Comment by bhavya181** [comment]
trigger messagecheck

**Pull request merged**
