### PR TITLE
[fix]: [PL-21549]: Changed description of some fields in GitSyncConfigDTO

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Changed description of some fields in GitSyncConfigDTO

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31772)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31772)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/31772#-Mz1DGvh1PrDR7JCznm5:-Mz1DGvi7tPDDlI9twvx:bexrhcl) ([raw file](https://github.com/harness/harness-core/blob/a5c527741fbd57d7c9651195a7f09f5d6cfc4bb3/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L41)):*
> ```Java
>   @Schema(description = GitSyncApiConstants.REPOID_PARAM_MESSAGE) @Trimmed @NotEmpty private String identifier;
>   @Schema(description =
>               GitSyncApiConstants.REPO_NAME_PARAM_MESSAGE + " Any leading/trailing spaces in the name will be removed.")
> ```

why have we removed the constant?

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31772)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/31772#-Mz1DGvh1PrDR7JCznm5:-Mz3IdT814YRFgwbUJ_c:bv6wgz9) ([raw file](https://github.com/harness/harness-core/blob/a5c527741fbd57d7c9651195a7f09f5d6cfc4bb3/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why have we removed the constant?
</blockquote></details>

trim message is now personalised for every field

**Comment by mohitg0795** [comment]
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/31772#-Mz1DGvh1PrDR7JCznm5:-Mz4CKl_-bOmw4Ahve5l:b-hliyx6) ([raw file](https://github.com/harness/harness-core/blob/a5c527741fbd57d7c9651195a7f09f5d6cfc4bb3/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L41)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

trim message is now personalised for every field
</blockquote></details>

Why have we personalized it now? There's no need for it.

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31772)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/31772#-Mz1DGvh1PrDR7JCznm5:-Mz5kXgq6fKBJnZCMI7P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5c527741fbd57d7c9651195a7f09f5d6cfc4bb3/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why have we personalized it now? There's no need for it.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31772#-:-Mz7AvH1CpDcBFNqXOob:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31772)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31772)* status: :shipit: complete! ✓

**Pull request merged**
