### PR TITLE
feat: [DEL-4617] add websocket metrics

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
Adding metric to show the number of pubsub subscriptions each manager pod has (per topic == per account).
Adding metric to show the number of open websocket connections for each manager pod (per accountId/delegateId)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36290)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 22 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 20 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36290)

**Comment by mdmilic** [comment]
trigger feature-build

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYB269MBfiwEBCmD_:-N9DYB269MBfiwEBCmDa:bswfia6) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L134)):*
> ```Java
>       String delegateId = req.getParameter("delegateId");
> 
>       cachedMetrics.incrementMetric(accountId, delegateId);
> ```

this gets called during heartbeats. we shouldn't be adding metrics here

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/metrics/metricGroups/delegateid_metrics_group.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYJT07rODNT26JEou:-N9DYJT1EKKf8PTisbp2:b-qjelic) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/400-rest/src/main/resources/metrics/metricGroups/delegateid_metrics_group.yaml#L1)):*
> ```YAML
> name: DelegateId
> ```

this will create a lot of metrics in our system and will be very expensive. Why do we need delegateId?

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYYxjBCjt6yHyXcy4:-N9DYYxjBCjt6yHyXcy5:b-xz61qb) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
> ```Java
>   }
> 
>   public void incrementMetric(final String accountId, final String delegateId) {
> ```

rename method appropriately. We are not really incrementing a count here

**Review by mdmilic — COMMENTED** [review]
> Reviewed 4 of 12 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36290)* status: 16 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 134 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYB269MBfiwEBCmD_:-N9H6iwQEw7S8tWxchHX:b-z5bh3q) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L134)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this gets called during heartbeats. we shouldn't be adding metrics here
</blockquote></details>

So the point was to keep the cache item away from expiring. From my debugging GET is used only for opening a connection and we use POST after that (though not 100% sure it's a rule, couldn't find info on that). So if I just put it in GET it will expire after 3min even though the connection is still alive. That's why we said we should use cached publisher, so that this actually just writes to cache, doesn't really publish anything. 
___
*[`400-rest/src/main/resources/metrics/metricGroups/delegateid_metrics_group.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYJT07rODNT26JEou:-N9Gz6C74cEZ_GFtOUeQ:b-vpcxen) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/400-rest/src/main/resources/metrics/metricGroups/delegateid_metrics_group.yaml#L1)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this will create a lot of metrics in our system and will be very expensive. Why do we need delegateId?
</blockquote></details>

This is supposed to show us how many websockets we have per delegate, this metric per account is not much useful. If we remove delegateId, the only thing I can think of is to see the difference between number of active delegates and number of open connections per account. In this case though we don't know which delegates have multiple connections. Do you think this could work?
___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYYxjBCjt6yHyXcy4:-N9H9IUU6UQEVXjuONlA:bebrt1w) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

rename method appropriately. We are not really incrementing a count here
</blockquote></details>

Will do

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/resources/metrics/metricGroups/delegateid_metrics_group.yaml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYJT07rODNT26JEou:-NAI_Ppv-7DSpJ7Ae4LU:b-maofkh) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/400-rest/src/main/resources/metrics/metricGroups/delegateid_metrics_group.yaml#L1)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This is supposed to show us how many websockets we have per delegate, this metric per account is not much useful. If we remove delegateId, the only thing I can think of is to see the difference between number of active delegates and number of open connections per account. In this case though we don't know which delegates have multiple connections. Do you think this could work?
</blockquote></details>

i just merged the change in develop to have the reconnection done by the library. hopefully we will not have multiple connections after that. per account should be good.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-NAI_zy0C8M1Fg4M2QzY:-NAI_zy0C8M1Fg4M2QzZ:b-5ts1v6) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L26)):*
> ```Java
>   private final MetricService metricService;
>   private final Cache<String, String> cntCache =
>       Caffeine.newBuilder().expireAfterWrite(3000, TimeUnit.MILLISECONDS).build();
> ```

the heartbeat comes every minute, we should have the expiry to be more than that. may be 90 seconds.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-N9DYYxjBCjt6yHyXcy4:-NAIaNEc4doIFXzJNkaZ:b-uq6w9a) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

this doesn't seem right, we should have the cache to be telling us number of delegates connected for each account. Also since each delegate can have two processes running this will not account for that as well. We probably need to maintain <delegateId, delegateConnectionId, accountId> and while publishing the metrics we publish the number of delegate connectionIds we have per account. That will give us a ballpark of number of connections.

**Comment by raghuAtWings** [comment]
*[`960-persistence/src/main/resources/metrics/metricGroups/redis_metrics_group.yaml` line 4 at r3](https://reviewable.io/reviews/harness/harness-core/36290#-NAIbElY4ZeNAZwA8Fdr:-NAIbElY4ZeNAZwA8Fds:bgeiyry) ([raw file](https://github.com/harness/harness-core/blob/56900c44a5ab0eb3d614ef00ffde731b41aecf70/960-persistence/src/main/resources/metrics/metricGroups/redis_metrics_group.yaml#L4)):*
> ```YAML
> identifier: redis
> labels:
>   - redisTopic
> ```

if we create a metric for each redis topic, it will end up creating a lot of metrics and will cost a lot of money to store. We  probably can reduce it by having number of topics per account

**Pull request closed without merging**
