### PR TITLE
feat: [CDS-76386]: Added the expression support for connectorRef

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Added the expression support for connectorRef <+trigger.connectorRef>
Screenshot 2023-08-04 at 1 15 38 PM
Screenshot 2023-08-04 at 1 16 54 PM

Test Case:

- Verified the expression resolved to correct connectorRef `<+trigger.connectorRef>`
- 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51360)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by shivamnegi94** [comment]
trigger ut7

**Comment by shivamnegi94** [comment]
trigger ut4

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/51360#-NbDjDKF8nCwIglOgmPB:-NbDjDKF8nCwIglOgmPC:b-pcgyxb) ([raw file](https://github.com/harness/harness-core/blob/cf762c220daef52b5cfe473bbf40495250ad3324/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java#L54)):*
> ```Java
>                                  "No Metadata present for planExecution :" + ambiance.getPlanExecutionId()));
>     Map<String, Object> jsonObject = TriggerHelper.buildJsonObjectFromAmbiance(metadata.getTriggerPayload());
>     if (EmptyPredicate.isNotEmpty(metadata.getTriggerPayload().getConnectorRef())) {
> ```

nit: can we replaced with 
metadata.getTriggerPayload().hasConnectorRef()

**Review by shivamnegi94 — COMMENTED** [review]
yes currently we doing it for webhook

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51360#-:-NbIRHuQDjGWa6P09x_y:b-14lcc2)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/51360#-NbDjDKF8nCwIglOgmPB:-NbIRNLSBl4NoUpvJELd:b-p1jx68) ([raw file](https://github.com/harness/harness-core/blob/7812b41c5ec0d9531278f9352fe46720d17619c4/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java#L54)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: can we replaced with 
metadata.getTriggerPayload().hasConnectorRef()

</blockquote></details>

@sahilhindwani-harness connectorRef is a String type and has method is only available for object type

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/51360#-NbDjDKF8nCwIglOgmPB:-NbISfH9AQASTuG2xEkz:bc85364) ([raw file](https://github.com/harness/harness-core/blob/7812b41c5ec0d9531278f9352fe46720d17619c4/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java#L54)):*
<details><summary><i>Previously, shivamnegi94 (Shivam Negi) wrote…</i></summary><blockquote>

@sahilhindwani-harness connectorRef is a String type and has method is only available for object type
</blockquote></details>

yes, string does not support has field. Closing this comment.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51360)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger review

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger ut6

**Pull request merged**
