### PR TITLE
feat: [CDS-67872]: Add token refresh cron job - Bitbucket OAuth

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Add token refresh cron job - Bitbucket OAuth

**Testing:** Tested locally that access token gets refreshed for Bitbucket SCM, also tested for gitlabSCM and gitlabConnector, as extracted some code common code from there.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46822)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut0, ut5, ut6, ut7, ut9, ut3

**Comment by shalini-agr** [comment]
trigger ut1, ut4, ut3, ut6

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/AbstractSCMOAuthTokenRefresher.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURWoc92TpI496yT_X9:-NURWoc92TpI496yT_XA:bo2ed0) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/AbstractSCMOAuthTokenRefresher.java#L28)):*
> ```Java
>     implements MongoPersistenceIterator.Handler<T> {
>   @Inject private ScmClient scmClient;
> ```

lets not add irrelevant blank lines/spaces

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NURXhXT5w4b30lKYzd7:b-xka48j) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't these all injections be in the abstract handler?
</blockquote></details>

I mean not injections, but declaration of fields.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 126 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXqzp6Hew8YdTnRNi:-NURXqzp6Hew8YdTnRNj:b-w1e021) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L126)):*
> ```Java
>   public OAuthConfig getOAuthConfig() {
>     return OAuthConfig.builder()
>         .endpoint("https://bitbucket.org/site/oauth2/access_token")
> ```

please use constants from a common class instead of hard coding.

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 6 of 34 files at r1, 5 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46822)* status: Some of the checks are too old. 38 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/OAuthTokenRefresherHelper.java` line 83 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURY7oJC1-AmQIuMECX:-NUS1_6MEv2zRIC5KIjV:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/OAuthTokenRefresherHelper.java#L83)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't be log.error?
</blockquote></details>

+1
___
*[`400-rest/src/main/java/software/wings/security/authentication/oauth/BitbucketConfig.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NUS1pCC29hS_e98a_C3:-NUS1pCC29hS_e98a_C4:b-amfaap) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/400-rest/src/main/java/software/wings/security/authentication/oauth/BitbucketConfig.java#L19)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> @Data
> ```

See if @Value serves your purpose here

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NUTIqrD1HsDPFTUky9P:bq6fwb2) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

whats the change here? I was expecting to move these fields to abstract class.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/oauth/BitbucketConfig.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/46822#-NUTJCU5Cckqm55VGUAd:-NUTJCU5Cckqm55VGUAe:b-7msd6t) ([raw file](https://github.com/harness/harness-core/blob/701b03f7b4c5b2070660b1bba0fe800d2cebdb8e/400-rest/src/main/java/software/wings/security/authentication/oauth/BitbucketConfig.java#L21)):*
> ```Java
> @Value
> @Builder
> @Singleton
> ```

why have we put singleton here? its not a service class

**Comment by shalini-agr** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NUUdhj8CZUDRa85kEkW:b-8aucjb) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the change here? I was expecting to move these fields to abstract class.
</blockquote></details>

mongoTemplate and configuration are required here. I removed the other declarations that could be moved to abstract class

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46822)* status: 43 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/AbstractSCMOAuthTokenRefresher.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXFrA3MZSjCdN4bj0:-NUVCU_V5suW3I3LMJjO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/AbstractSCMOAuthTokenRefresher.java#L33)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should have a global try catch. And then inside a functional try catch who's exception block will be used.
So, issue in current case is that the logs that we add in exception block won't have the context that we are setting in the try block. Thus, there needs to be a global try which will have nested functional try catch.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/security/authentication/oauth/BitbucketConfig.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/46822#-NUTJCU5Cckqm55VGUAd:-NUUdrh71ww8ZxiilmJv:bew4inu) ([raw file](https://github.com/harness/harness-core/blob/701b03f7b4c5b2070660b1bba0fe800d2cebdb8e/400-rest/src/main/java/software/wings/security/authentication/oauth/BitbucketConfig.java#L21)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why have we put singleton here? its not a service class
</blockquote></details>

yes, not needed here, removed.

**Comment by shalini-agr** [comment]
trigger utAll

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NUVQUKKB_M_FMZC0Eyb:b-44gd71) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

mongoTemplate and configuration are required here. I removed the other declarations that could be moved to abstract class
</blockquote></details>

Why can't it be used from abstract class? The whole idea is that if these are to be required by everyone, then abstract it out in common class from where everyone can use it directly.

**Comment by shalini-agr** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NUVWSjf-jTN32aXdf7P:bo1qjt5) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why can't it be used from abstract class? The whole idea is that if these are to be required by everyone, then abstract it out in common class from where everyone can use it directly.
</blockquote></details>

from configuration, both gitlab and bitbucket are extracting different things like for bitbucket it is `configuration.getBitbucketConfig().getClientId()` and for gitlab it is  `configuration.getGitlabConfig().getClientId()`
and for azure, it'll be `getAzureConfig()`, so we can't put this in abstract class.

And mongoTemplate is being used in registerIterators method which uses above clientId so that method and mongoTemplate also have to be in individual providers' classes.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NUVsOT15U3Q2sB8zR5b:b-frxx7c) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

from configuration, both gitlab and bitbucket are extracting different things like for bitbucket it is `configuration.getBitbucketConfig().getClientId()` and for gitlab it is  `configuration.getGitlabConfig().getClientId()`
and for azure, it'll be `getAzureConfig()`, so we can't put this in abstract class.

And mongoTemplate is being used in registerIterators method which uses above clientId so that method and mongoTemplate also have to be in individual providers' classes. 
</blockquote></details>

As discussed offline, these fields will be moved to abstract class.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46822)* status: 43 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/46822#-NURXbHi1OZPCbBuVvr8:-NUVtXv1-vI2ECbhY_rV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c9b0853a356a28556b339544bcb9ddb7d19f7b5f/120-ng-manager/src/main/java/io/harness/ng/oauth/BitbucketSCMOAuthTokenRefresher.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As discussed offline, these fields will be moved to abstract class.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger utAll

**Comment by shalini-agr** [comment]
trigger uts

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 25 of 32 files at r2, 7 of 11 files at r3, 1 of 2 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46822)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
