### PR TITLE
[fix]: [CDS-38553]: Infra Details Addition to Outcome Interface

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34576)

### CODE REVIEW

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34576)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34576)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/34576#-N5J28K14a2kaVC4kTZ5:-N5J28K14a2kaVC4kTZ6:bciqyri) ([raw file](https://github.com/harness/harness-core/blob/6adc3c3eee7aa786f066d50294c9fa8504cbb06c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L224)):*
> ```Java
>       // Adding infrastructure node
>       PlanNode infraStepNode = InfrastructurePmsPlanCreator.getInfraStepPlanNode(
>           pipelineInfrastructure.getInfrastructureDefinition().getSpec(), null, null);
> ```

instead of passing (null, null), we should use java method overloading to create a new method 
```public PlanNode getInfraStepPlanNode(Infrastructure pipelineInfrastructure) ```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/SshWinRmAwsInfrastructureOutcome.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/34576#-N5J2s3Q8U7vcfOpdDh_:-N5J2s3Q8U7vcfOpdDha:blvanud) ([raw file](https://github.com/harness/harness-core/blob/6adc3c3eee7aa786f066d50294c9fa8504cbb06c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/SshWinRmAwsInfrastructureOutcome.java#L27)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @RecasterAlias("io.harness.cdng.infra.beans.SshWinRmAwsInfrastructureOutcome")
> public class SshWinRmAwsInfrastructureOutcome implements InfrastructureOutcome {
> ```

instead of adding this field to each class, we should ideally create a class InfraOutComeAbstract

abstract class InfraAbstractOutcome implements InfrastructureOutcome {
  String infraIdentifier;
  String infraName;
}

public class SshWinRmAwsInfrastructureOutcome extends InfraAbstractOutcome {
//
}

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/34576#-N5J28K14a2kaVC4kTZ5:-N5Jx0q1CsaTwqEjCzqp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6adc3c3eee7aa786f066d50294c9fa8504cbb06c/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L224)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

instead of passing (null, null), we should use java method overloading to create a new method 
```public PlanNode getInfraStepPlanNode(Infrastructure pipelineInfrastructure) ```
</blockquote></details>

Done.

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/SshWinRmAwsInfrastructureOutcome.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/34576#-N5J2s3Q8U7vcfOpdDh_:-N5JxDI72R3pft5PeoMy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6adc3c3eee7aa786f066d50294c9fa8504cbb06c/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/SshWinRmAwsInfrastructureOutcome.java#L27)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

instead of adding this field to each class, we should ideally create a class InfraOutComeAbstract

abstract class InfraAbstractOutcome implements InfrastructureOutcome {
  String infraIdentifier;
  String infraName;
}

public class SshWinRmAwsInfrastructureOutcome extends InfraAbstractOutcome {
//
}


</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 14 files at r1, 2 of 3 files at r2, 4 of 12 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34576)* status: :shipit: complete! ✓

**Pull request merged**
