### PR TITLE
feat: [CDS-39289]: cd_account_license_telemetry

### PR DESCRIPTION
**Pull request by lovish1999**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger messagecheck

**Review by hextechpal — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
:lgtm:

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]

**Review by shubham-in10se — DISMISSED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 739 at r1](https://reviewable.io/reviews/harness/harness-core/34939#-N6l5E0tCvI_5sej1l4Z:-N6l5E0tCvI_5sej1l4_:b-j7mmfg) ([raw file](https://github.com/harness/harness-core/blob/33b5e33ed5eb8d9bdcb87a09ab243bd3a9ea4c67/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L739)):*
> ```Java
>         .toInstance(new ScheduledThreadPoolExecutor(1,
>             new ThreadFactoryBuilder()
>                 .setNameFormat("Cd-telemetry-publisher-Thread-%d")
> ```

we are doing this only for `ng` right.?
so let's name the threads as: cd-ng-telemetry-publisher-thread-%d
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sMFCf-zOEEp2-XhQw:-N6sMFCf-zOEEp2-XhQx:b-cj1r8r) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java#L36)):*
> ```Java
> @OwnedBy(CDP)
> public class CdTelemetryPublisher {
>   @Inject LicenseUsageInterface licenseUsageInterface;
> ```

`LicenseUsageInterface` has 3 implementations. ensure we are doing the correct binding.
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sMVzj5B97UoTHB3TW:-N6sMVzj5B97UoTHB3TX:b-udfe68) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java#L38)):*
> ```Java
>   @Inject LicenseUsageInterface licenseUsageInterface;
>   @Inject TelemetryReporter telemetryReporter;
>   @Inject AccountClient accountClient;
> ```

all dependencies should be ``private`



_Code quote:_
```Java
  @Inject LicenseUsageInterface licenseUsageInterface;
  @Inject TelemetryReporter telemetryReporter;
  @Inject AccountClient accountClient;
  @Inject CdTelemetryStatusRepository cdTelemetryStatusRepository;
```
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sMZg4DgEZC8JjBwyI:-N6sMZg4DgEZC8JjBwyJ:b-nw1xx) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java#L41)):*
> ```Java
>   @Inject CdTelemetryStatusRepository cdTelemetryStatusRepository;
>   String COUNT_ACTIVE_SERVICES = "cd_license_services_used";
>   String COUNT_ACTIVE_SERVICE_INSTANCES = "cd_license_service_instances_used";
> ```

all string constants should be `private static final`



_Code quote:_
```Java
  String COUNT_ACTIVE_SERVICES = "cd_license_services_used";
  String COUNT_ACTIVE_SERVICE_INSTANCES = "cd_license_service_instances_used";
  String ACCOUNT_DEPLOY_TYPE = "account_deploy_type";
```
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sMdaREGNyVxc6oeca:-N6sMdaREGNyVxc6oecb:b3eipd5) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java#L45)):*
> ```Java
>   // Locking for a bit less than one day. It's ok to send a bit more than less considering downtime/etc
>   //(24*60*60*1000)-(10*60*1000)
>   static final long A_DAY_MINUS_TEN_MINS_IN_MILLIS = 85800000;
> ```

this should also be `private`
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sLuBBCff4y0b9qkwP:-N6sLuBBCff4y0b9qkwQ:byacssw) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryPublisher.java#L91)):*
> ```Java
>   }
> 
>   List<AccountDTO> getAllAccounts() {
> ```

this should be `private`
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryRecordsJob.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sN8kh3l_iubTsuZyU:-N6sN8ki1mBgWa0zvUc3:byacssw) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryRecordsJob.java#L22)):*
> ```Java
>   public static final int THIRTY_MINS_IN_SECS = 1800;
> 
>   @Inject @Named("CdTelemetryPublisherExecutor") protected ScheduledExecutorService executorService;
> ```

this should be `private`
___
*[`120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryRecordsJob.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sNBJN-JTQ7dAx59j7:-N6sNBJN-JTQ7dAx59j8:byacssw) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/120-ng-manager/src/main/java/io/harness/telemetry/CdTelemetryRecordsJob.java#L23)):*
> ```Java
> 
>   @Inject @Named("CdTelemetryPublisherExecutor") protected ScheduledExecutorService executorService;
>   @Inject CdTelemetryPublisher publisher;
> ```

this should be `private`
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/beans/CdTelemetrySentStatus.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sNWKoDeT90-3z-bXW:-N6sNWKp83Phk6sljsGW:bogbzhk) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/beans/CdTelemetrySentStatus.java#L58)):*
> ```Java
>         .build();
>   }
>   String accountId;
> ```

all member variables should be private



_Code quote:_
```Java
  String accountId;
  long lastSent; // timestamp
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/beans/CdTelemetrySentStatus.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/34939#-N6sNR2N91tX6mH0n6hI:-N6sNR2N91tX6mH0n6hJ:bx9mnmt) ([raw file](https://github.com/harness/harness-core/blob/972ad8afd58aa215592744ce2255d57a18bd788c/125-cd-nextgen/src/main/java/io/harness/cdng/usage/beans/CdTelemetrySentStatus.java#L59)):*
> ```Java
>   }
>   String accountId;
>   long lastSent; // timestamp
> ```

club all member variables together



_Code quote:_
```Java
  String accountId;
  long lastSent; // timestamp
```

**Comment by lovish1999** [comment]
Is it new task type? (If yes, no need to answer 2 then)
No

Did you add a new class which is added in kryo serialization
No

Did you make changes to the code in a backward-compatible manner?
Yes

will the new version of the delegate receive old version task and process?
Yes

If new version of the manager receives response for the old task will it be able to handle it successfully?
Yes

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
No

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
Yes

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
Yes

Did you remove an enum → this is not backward compatible yet (tracked by DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS )
No

Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
No

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 2 of 14 files at r1, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: :shipit: complete! ✓

**Comment by lovish1999** [comment]
trigger codebasehash

**Comment by lovish1999** [comment]
trigger codebasehash

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 14 files at r1, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34939)* status: :shipit: complete! ✓

**Comment by lovish1999** [comment]
trigger codebasehash

**Pull request merged**
