### PR TITLE
feat: [PL-22259]: Supporting Org and Project level RBAC for ServiceAccounts.

### PR DESCRIPTION
**Pull request by boopesh007**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31413)

### CODE REVIEW

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31413)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31413)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/java/io/harness/resourcegroup/resourceclient/serviceaccount/ServiceAccountResourceImpl.java, line 81 at r1](https://reviewable.io/reviews/harness/harness-core/31413#-My90sYs3ItcSrT1hQaL:-My90sYs3ItcSrT1hQaM:b-c98z4a) ([raw file](https://github.com/harness/harness-core/blob/ba7229a5741e05546c104dbe78227f787c87a21a/830-resource-group/src/main/java/io/harness/resourcegroup/resourceclient/serviceaccount/ServiceAccountResourceImpl.java#L81)):*
> ```Java
>   @Override
>   public Set<ScopeLevel> getValidScopeLevels() {
>     return EnumSet.of(ScopeLevel.ACCOUNT, ScopeLevel.ORGANIZATION, ScopeLevel.PROJECT);
> ```

All these changes will go with the UI changes.

**Review by karansiwach360 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31413#-:-MyB5i-Y3pnB6LwR0HQM:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach360 — COMMENTED** [review]
Merge backend changes with UI changes.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31413#-:-MyB5nuW6UsfC2CpH73P:b5an3wz)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31413)* status: :shipit: complete! ✓

**Pull request merged**
