### PR TITLE
feat: [CVS-4113]: custom logs

### PR DESCRIPTION
**Pull request by anjanBalgovind**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31139)

### CODE REVIEW

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 44 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQLHX87-dLNN24eYs:-MxbQLHY142bSyxpTqZt:bobddpb) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L44)):*
> ```Java
>   @Data
>   @Builder
>   public static class Key {
> ```

Remove key. It has only one item within it. Doesnt make sense to have a class for that.

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQUocBBvcik9JZAMc:-MxbQUocBBvcik9JZAMd:b-s8dupq) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L49)):*
> ```Java
> 
>   @Override
>   public HealthSource.CVConfigUpdateResult getCVConfigUpdateResult(String accountId, String orgIdentifier,
> ```

import the whole thing up top.

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQ_Jr5KSAk1ejg-bZ:-MxbQ_Jr5KSAk1ejg-b_:b-55me15) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L60)):*
> ```Java
>         environmentRef, serviceRef, monitoredServiceIdentifier, identifier, name);
> 
>     Set<Key> deleted = Sets.difference(existingConfigs.keySet(), currentCVConfigs.keySet());
> ```

without Key object, this will become Set<String>

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 106 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQhDo9s1A-_zTmpxJ:-MxbQhDo9s1A-_zTmpxK:bhgjj7d) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L106)):*
> ```Java
>               .serviceInstanceJsonPath(logDefinition.getServiceInstanceJsonPath())
>               .queryName(queryName)
>               .query("")
> ```

query is empty ? Is this because we use the urlPath and body ? I thought we discussed that this would be filled in with the path ?

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthMetricCVConfig.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbRFpvBIN5r07DqpDA:-MxbRFpvBIN5r07DqpDB:ballgtw) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthMetricCVConfig.java#L43)):*
> ```Java
> @AllArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> public class CustomHealthMetricCVConfig extends MetricCVConfig {
> ```

any migration for this ? Atleast clean up existing ones so it's a fresh start?

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/serializer/morphia/CVNextGenMorphiaRegister.java, line 176 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSAjU6AoyR7ITRJzd:-MxbSAjU6AoyR7ITRJze:boozavg) ([raw file](https://github.com/harness/harness-core/blob/9812b7933215314fdd0751513e14fed3aab76f49/300-cv-nextgen/src/main/java/io/harness/serializer/morphia/CVNextGenMorphiaRegister.java#L176)):*
> ```Java
>     set.add(Comparable.class);
>     set.add(PrometheusCVConfig.class);
>     set.add(CustomHealthCVConfig.class);
> ```

you are probably going to have issues reading existing cvConfigs due to this change.

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/main/resources/io/harness/cvng/core/entities/custom-log-fetch-data.datacollection, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSKQ37BX2UMZ7tUhD:-MxbSKQ37BX2UMZ7tUhE:bbao4r4) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/resources/io/harness/cvng/core/entities/custom-log-fetch-data.datacollection#L1)):*
> ```
> Var one = 1
> ```

please add a comment here that this is not yet ready for review.

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceLogSpecTest.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSUJ_DOF-ZjB-WPno:-MxbSUJ_DOF-ZjB-WPnp:b-z9kzvh) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceLogSpecTest.java#L57)):*
> ```Java
>   public void setup() {
>     customHealthSourceSpecs = new ArrayList<>();
>     CustomHealthLogDefinition customHealthSpecLogDefinition =
> ```

can this go into builderFactory ?

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceMetricSpecTest.java, line 62 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSgdv--bARqBI0OQk:-MxbSgdv--bARqBI0OQl:b-qk3xks) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceMetricSpecTest.java#L62)):*
> ```Java
> 
>   @Before
>   public void setup() {
> ```

you should use builderFactory here to create your cvConfigs and metricDefinitions if possible.

**Comment by praveensugavanam** [comment]
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/entities/CustomHealthLogCVConfigTest.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSpDp2g47m0J_U6dV:-MxbSpDp2g47m0J_U6dW:b3h790t) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/entities/CustomHealthLogCVConfigTest.java#L26)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class CustomHealthLogCVConfigTest extends CategoryTest {
> ```

use builderFactory

**Review by praveensugavanam — COMMENTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31139)* status: 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbR7LZCImNamz5QlGh:-MxbR7LZCImNamz5QlGi:brq4kde) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java#L60)):*
> ```Java
>   @Override
>   public String getDataCollectionDsl() {
>     return null;
> ```

null ? Is this coming in the next PR ?

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbR7LZCImNamz5QlGh:-Mxevv4H5m8iErssCUN3:b-n5kot5) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java#L60)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

null ? Is this coming in the next PR ?
</blockquote></details>

yeah in the DSL PR

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceLogSpecTest.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSUJ_DOF-ZjB-WPno:-Mxew0MmEgJLBNEDKhZQ:b-jnhtsw) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceLogSpecTest.java#L57)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

can this go into builderFactory ?
</blockquote></details>

will do in following PR

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceMetricSpecTest.java, line 62 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSgdv--bARqBI0OQk:-Mxew2MW6NvRCYSCcwzI:b-jnhtsw) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceMetricSpecTest.java#L62)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

you should use builderFactory here to create your cvConfigs and metricDefinitions if possible.
</blockquote></details>

will do in following PR

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/entities/CustomHealthLogCVConfigTest.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSpDp2g47m0J_U6dV:-Mxew4ja9qJWa3tQ2rw0:b-jnhtsw) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/entities/CustomHealthLogCVConfigTest.java#L26)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

use builderFactory
</blockquote></details>

will do in following PR

**Review by anjanBalgovind — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31139)* status: 2 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 44 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQLHX87-dLNN24eYs:-MxevrjoCn07bRL7FOCk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L44)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

Remove key. It has only one item within it. Doesnt make sense to have a class for that. 
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQUocBBvcik9JZAMc:-Mxevt1Z0oC2q4udyogh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L49)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

import the whole thing up top. 
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQ_Jr5KSAk1ejg-bZ:-MxevtX9Cpjzz1oulGsC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L60)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

without Key object, this will become Set<String>
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 106 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQhDo9s1A-_zTmpxJ:-Mxevu7505xDApXeSU0J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L106)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

query is empty ? Is this because we use the urlPath and body ? I thought we discussed that this would be filled in with the path ?
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/resources/io/harness/cvng/core/entities/custom-log-fetch-data.datacollection, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSKQ37BX2UMZ7tUhD:-Mxew-j9EENLfxAadFxF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/resources/io/harness/cvng/core/entities/custom-log-fetch-data.datacollection#L1)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

please add a comment here that this is not yet ready for review.
</blockquote></details>

Done.

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthMetricCVConfig.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbRFpvBIN5r07DqpDA:-MxlMlfs8snbHwYmIoPO:b-dg7jvl) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthMetricCVConfig.java#L43)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

any migration for this ? Atleast clean up existing ones so it's a fresh start?
</blockquote></details>

not in produuction yet

**Comment by anjanBalgovind** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/serializer/morphia/CVNextGenMorphiaRegister.java, line 176 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSAjU6AoyR7ITRJzd:-MxlMqDuAK_JS46Avaj6:bph9otc) ([raw file](https://github.com/harness/harness-core/blob/9812b7933215314fdd0751513e14fed3aab76f49/300-cv-nextgen/src/main/java/io/harness/serializer/morphia/CVNextGenMorphiaRegister.java#L176)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

you are probably going to have issues reading existing cvConfigs due to this change. 
</blockquote></details>

not in production yet, will delete all existing configs

**Review by anjanBalgovind — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31139)* status: 8 file(s) to review. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceLogSpecTest.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSUJ_DOF-ZjB-WPno:-MxlMvE9BqgfKhZDzNHL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceLogSpecTest.java#L57)):*
<details><summary><i>Previously, anjanBalgovind (Anjan Balgovind) wrote…</i></summary><blockquote>

will do in following PR
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/entities/CustomHealthLogCVConfigTest.java, line 26 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSpDp2g47m0J_U6dV:-MxlMyFY-j4tyh-ewDBN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/entities/CustomHealthLogCVConfigTest.java#L26)):*
<details><summary><i>Previously, anjanBalgovind (Anjan Balgovind) wrote…</i></summary><blockquote>

will do in following PR
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceMetricSpecTest.java, line 62 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbSgdv--bARqBI0OQk:-MxlMwT4A8vkwjIKF4Xt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/test/java/io/harness/cvng/core/beans/monitoredService/healthSourceSpec/CustomHealthSourceMetricSpecTest.java#L62)):*
<details><summary><i>Previously, anjanBalgovind (Anjan Balgovind) wrote…</i></summary><blockquote>

will do in following PR
</blockquote></details>

Done.

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 5 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31139)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31139#-MxbQUocBBvcik9JZAMc:-MxmJ6O0CF606CoXEuiu:bn2petd) ([raw file](https://github.com/harness/harness-core/blob/a8d149907d769e6c50570880872ed5eb1ceec6de/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/CustomHealthSourceLogSpec.java#L49)):*
<details><summary><i>Previously, anjanBalgovind (Anjan Balgovind) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not done. Please do it in the next PR

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 19 of 28 files at r1, 1 of 2 files at r2, 5 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31139)* status: :shipit: complete! ✓

**Pull request merged**
