### PR TITLE
[feat]: [PL-32078]: Adds feature flag for select specific service account in resource group

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds feature flag for select specific service account in resource group

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45281)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger ut2, trigger ut4, trigger ut5, trigger ut7

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45281#-:-NQiwMOoBzyq5cpuEF2A:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 661 at r1](https://reviewable.io/reviews/harness/harness-core/45281#-NQiwsRw3eUrWVCX8TaI:-NQiwsRw3eUrWVCX8TaJ:b-m56yc1) ([raw file](https://github.com/harness/harness-core/blob/6d0b139341629d8bfeda3f8a89d281df90310517/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L661)):*
> ```Java
>   CDS_K8S_SOCKET_CAPABILITY_CHECK_NG(
>       "Replace HTTP capability check for Kubernetes connector with Socket Capability", HarnessTeam.CDP),
>   PL_SELECT_SERVICE_ACCOUNT_IN_RESOURCE_GROUP("Allow selection of service account in Resource group", HarnessTeam.PL);
> ```

Does this  PL_SELECT_SPECIFIC_SERVICE_ACCOUNT_IN_RESOURCE_GROUP look better?



_Code quote:_
```Java
  PL_SELECT_SERVICE_ACCOUNT_IN_RESOURCE_GROUP("Allow selection of service account in Resource group", HarnessTeam.PL);
```

**Comment by ashishsanodia-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 661 at r1](https://reviewable.io/reviews/harness/harness-core/45281#-NQiwsRw3eUrWVCX8TaI:-NQiyTkf2KDwYFjVCgYn:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/6d0b139341629d8bfeda3f8a89d281df90310517/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L661)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Does this  PL_SELECT_SPECIFIC_SERVICE_ACCOUNT_IN_RESOURCE_GROUP look better?
</blockquote></details>

Fixed

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45281#-:-NQiygRg1niepANTWu7u:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
