### PR TITLE
[fix]: [CI-0]: Fix typo in bazelisk command

### PR DESCRIPTION
**Pull request by hemanthmantri**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31083)

### CODE REVIEW

**Review by vardanbansal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31083)* status: :shipit: complete! ✓

**Review by jamie-harness — APPROVED** [review]

**Review by jamie-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31083)* status: :shipit: complete! ✓

**Comment by vardanbansal-harness** [comment]
@hemanthmantri From what I remember QA team has a script to flag all PRs using ticket ids such `CI-0`, `PL-0` etc. to prevent people from committing without a valid ticket id. Just FYI.

**Comment by hemanthmantri** [comment]
@vardanbansal-harness : I think it is not worthwhile creating a ticket for README changes like this. It is also mentioned in the engineering onboarding wiki page about using DEL-0 like ticket ID for changes like this. Also the checks pass so I think we are good for now :)

**Pull request merged**
