### PR TITLE
[feat]: [CDS-35474]: Implement referenced by for ng file store

### PR DESCRIPTION
**Pull request by vladimir-peric**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 170 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00jVrR6xLVBILQimN8:-N00jVrR6xLVBILQimN9:b-sfrxjl) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L170)):*
> ```Java
>       throw new InvalidArgumentsException("Account identifier cannot be null or empty");
>     }
>     NGFile file = fetchFile(accountIdentifier, orgIdentifier, projectIdentifier, identifier);
> ```

Pls rename fetchFile method to fetchFileOrThrow and here create IdentifierRef identifierRef and pass to new ref service 
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00cFBR6Cdv8NAHNBI0:-N00cFBU2DSOQ4W0I1UH:bhfc4cc) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L22)):*
> ```Java
> @Slf4j
> @Singleton
> public class FileReferencedByHelper {
> ```

Let's make this more general, Please create the new EntityReferenceByServiceImpl service and put in the same package where is FileStoreServiceImp also create and appropriate interface. 
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00gB90DiCnGc9jLXkO:-N00gB90DiCnGc9jLXkP:b-fzn5lz) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L30)):*
> ```Java
>   }
> 
>   public boolean isFileReferencedByOtherEntities(NGFile file) {
> ```

Method signature could be isEntityReferencedByOtherEntities(IdentifierRef entityRef)  or something similar 



_Code quote:_
```Java
IdentifierRef identifierRef
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00kREr8IPYCkoYxs2m:-N00kREr8IPYCkoYxs2n:b-j2tuc5) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L38)):*
> ```Java
>           file.getAccountIdentifier(), referredEntityFQN, EntityType.NG_FILE);
>     } catch (Exception ex) {
>       log.info("Encountered exception while requesting the Entity Reference records of [{}], with exception.",
> ```

Write to error level or just throw unexpected exception with populated message and ex. It should be logged by framework. 
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 44 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00gb2sC2gKfwzXuSS0:-N00gb2sC2gKfwzXuSS1:b5pvi7j) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L44)):*
> ```Java
>   }
> 
>   public Page<EntitySetupUsageDTO> getReferencedBy(SearchPageParams pageParams, NGFile file, EntityType entityType) {
> ```

Method signature could be getReferencedBy(SearchPageParams pageParams, IdentifierRef entityRe, EntityType entityType) or something similar 
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/SearchPageParams.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00gvDj0kw39wnOZpUZ:-N00gvDj0kw39wnOZpU_:b-ajygg6) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/SearchPageParams.java#L21)):*
> ```Java
> @NoArgsConstructor
> @OwnedBy(CDP)
> public class SearchPageParams {
> ```

Could yo check do we already  have similar data structure if not this is ok and should be in beans package
___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java, line 217 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00hg1n1Z9h9yO-BpsT:-N00hg1n1Z9h9yO-BpsU:b5cebjz) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java#L217)):*
> ```Java
>   @GET
>   @Consumes({"application/json"})
>   @Path("referenced-by")
> ```

identifier should be path param like this /{identifier}/referenced-by



_Code quote:_
```Java
identifier
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java, line 236 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00hzk24i56xdhh1HfY:-N00hzk24i56xdhh1HfZ:b-mz5ptn) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java#L236)):*
> ```Java
>           NGCommonEntityConstants.IDENTIFIER_KEY) String identifier,
>       @Parameter(description = "Entity type") @QueryParam(ENTITY_TYPE) EntityType entityType,
>       @QueryParam(NGResourceFilterConstants.SEARCH_TERM_KEY) String searchTerm) {
> ```

Minor - use static imports for IDENTIFIER_KEY, PAGE_KEY and SEARCH_TERM_KEY
___
*[955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java, line 72 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00odjIBUGCvaKgK7eV:-N00odjIBUGCvaKgK7eW:b-4kv2z8) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L72)):*
> ```Java
>     Criteria criteria = entitySetupUsageFilterHelper.createCriteriaFromEntityFilter(
>         accountIdentifier, referredEntityFQN, referredEntityType, searchTerm);
>     Pageable pageable = getPageRequest(page, size, Sort.by(Sort.Direction.DESC, EntitySetupUsageKeys.createdAt));
> ```

Just check with Meenakshi how to sort reference by files. 



_Code quote:_
```Java
EntitySetupUsageKeys
```

**Comment by vladimir-peric** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/SearchPageParams.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00gvDj0kw39wnOZpUZ:-N01YAHZ5Cy_kwHkfEwU:b6dbnsr) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/SearchPageParams.java#L21)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Could yo check do we already  have similar data structure if not this is ok and should be in beans package
</blockquote></details>

There is similar one named PageParams, but doesn't contain the searchTerm property and is in 300-cv-nextgen module, which I would not introduce dependency to.

**Comment by vladimir-peric** [comment]
*[955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java, line 72 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00odjIBUGCvaKgK7eV:-N01fWe00o91GoD39IQq:b-xbfusf) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/impl/EntitySetupUsageServiceImpl.java#L72)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Just check with Meenakshi how to sort reference by files. 
</blockquote></details>

Checked with Meenakshi, it should be by name, changing this.

**Comment by vladimir-peric** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00cFBR6Cdv8NAHNBI0:-N01gqWC498Y1y37SozW:b4sb3wc) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L22)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Let's make this more general, Please create the new EntityReferenceByServiceImpl service and put in the same package where is FileStoreServiceImp also create and appropriate interface. 
</blockquote></details>

I would rather keep this helper class, to avoid putting too much code in FileStoreServiceImplClass. Additionally, there already exists more general service which is actually called from this helper, named EntitySetupUsageService.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00kREr8IPYCkoYxs2m:-N01hUIX1jVm27m55FSI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L38)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Write to error level or just throw unexpected exception with populated message and ex. It should be logged by framework. 
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java, line 217 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00hg1n1Z9h9yO-BpsT:-N01dmFPE1uMgCY2XEes:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java#L217)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

identifier should be path param like this /{identifier}/referenced-by
</blockquote></details>

Done.

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 2 of 14 files at r1, 1 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/32289#-N00cFBR6Cdv8NAHNBI0:-N01sOnvDYFog7fpmyH8:b-l99jto) ([raw file](https://github.com/harness/harness-core/blob/d5ff65072d55dcf3bda8e6b1bcec37575bb100e4/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/utils/FileReferencedByHelper.java#L22)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

I would rather keep this helper class, to avoid putting too much code in FileStoreServiceImplClass. Additionally, there already exists more general service which is actually called from this helper, named EntitySetupUsageService.
</blockquote></details>

Ok, in that case create new package filestore in io.harness.ng.core and move files store services and helpers in that packages the same like we have for invites (io.harness.ng.core.invites).

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: :shipit: complete! ✓

___
*[120-ng-manager/src/main/java/io/harness/ng/core/filestore/utils/FileReferencedByHelper.java, line 24 at r4](https://reviewable.io/reviews/harness/harness-core/32289#-N06DX7h6w85l_0iUzlI:-N06DX7h6w85l_0iUzlJ:b-yeehm) ([raw file](https://github.com/harness/harness-core/blob/388eba85d9ce190bb89b73363e547ad489e52b28/120-ng-manager/src/main/java/io/harness/ng/core/filestore/utils/FileReferencedByHelper.java#L24)):*
> ```Java
> @Singleton
> public class FileReferencedByHelper {
>   protected static final String REFFERED_BY_IDENTIFIER_KEY = "referredByEntity.entityRef.identifier";
> ```

Do concatenation by using entitySetupUsageKeys.
___
*[120-ng-manager/src/test/java/io/harness/ng/core/filestore/remote/FileStoreResourceTest.java, line 55 at r4](https://reviewable.io/reviews/harness/harness-core/32289#-N06CkMoCniDMI8b3FwP:-N06CkMoCniDMI8b3FwQ:bk8kc7a) ([raw file](https://github.com/harness/harness-core/blob/388eba85d9ce190bb89b73363e547ad489e52b28/120-ng-manager/src/test/java/io/harness/ng/core/filestore/remote/FileStoreResourceTest.java#L55)):*
> ```Java
>   @Mock private FileStoreServiceImpl fileStoreService;
> 
>   private io.harness.ng.core.filestore.remote.FileStoreResource fileStoreResource;
> ```

Minor - remove full import path.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32289#-:-N07NBwt4ILfyIlQESo0:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger license/cla

**Pull request merged**
