### PR TITLE
feat: [CDS-49647]: Adding columns to store revert information using tags in…

### PR DESCRIPTION
**Pull request by Y0709**
… timescale
For Dora metric -- mean time to restore
We have added 3 columns in pipeline_execution_summary_cd and added code to sync data in these columns through cdc handler and debezium handler
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42668)

### CODE REVIEW

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42668)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/42668#-NM85xKBABEU-zlYfIeK:-NM8ZN-s8kuiqiXHqkGJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f67a91a37f59355e078c9f2b26a5fef2e7b58115/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L103)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, you're looking for success status only I believe, Why not add it to the query?
</blockquote></details>

done
___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/42668#-NM864iF1FpOyD9zkY02:-NM8ZP8Y7rOiIXHGwo6h:bpm2wqq) ([raw file](https://github.com/harness/harness-core/blob/f67a91a37f59355e078c9f2b26a5fef2e7b58115/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L138)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Don't understand. Why are you retrying if you don't find the expected result? DB has given you whatever it had for your query. 
</blockquote></details>

Sometimes, the connection might be broken in between or some other issue might happen. This is for such a scenario.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42668)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 138 at r2](https://reviewable.io/reviews/harness/harness-core/42668#-NM864iF1FpOyD9zkY02:-NM8ehZM2VlvfOdMRgs5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f67a91a37f59355e078c9f2b26a5fef2e7b58115/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L138)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

Sometimes, the connection might be broken in between or some other issue might happen. This is for such a scenario. 
</blockquote></details>

done

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42668)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger messagecheck

**Comment by Y0709** [comment]
trigger ft1

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 5 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42668)* status: 9 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 5 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42668)* status: :shipit: complete! ✓

**Pull request merged**
