### PR TITLE
[fix]: [PL-28549]: added 2FA QR code in NG user invite/notify email + enhanced logging and error handling + UTs

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added 2FA QR code in NG user invite email when 2FA is enabled on account level

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`970-ng-commons/src/main/java/io/harness/NgInviteLogContext.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKCsrq97-UAJ5bOhIo:-NEKCsrq97-UAJ5bOhIp:b-qo8rrf) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/970-ng-commons/src/main/java/io/harness/NgInviteLogContext.java#L16)):*
> ```Java
> public class NgInviteLogContext extends AutoLogContext {
>   public static final String INVITE_IDENTIFIER = "inviteIdentifier";
>   public static final String ACCOUNT_IDENTIFIER = "accountIdentifier";
> ```

Lets try to use this common string from `NGCommonEntityConstants` , thanks



_Code quote:_
```Java
public static final String ACCOUNT_IDENTIFIER = "accountIdentifier";
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 679 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKFpe650Z8UtMaPMKu:-NEKFpe650Z8UtMaPMKv:b1yahmw) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L679)):*
> ```Java
>       log.info("NG User Invite: notification with notificationId {} and templateId {} is successfully sent",
>           notificationResult.getNotificationId(), emailChannelBuilder.build().getTemplateId());
>     } catch (Exception ex) {
> ```

nit - a question: would this actually catch exception & log appropriately?, since the called method seems to be an Async method? 



_Code quote:_
```Java
 } catch (Exception ex) {
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 697 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKGJjSBcDWMnAzVLNX:-NEKGJjSBcDWMnAzVLNY:b-uqemfu) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L697)):*
> ```Java
>   private String generateOtpUrl(String companyName, String userEmailAddress, String secret) {
>     return format(
>         "otpauth://totp/%s:%s?secret=%s&issuer=Harness-Inc", companyName.replace(" ", "-"), userEmailAddress, secret);
> ```

nit extract to a String constant 



_Code quote:_
```Java
otpauth://totp/%s:%s?secret=%s&issuer=Harness-Inc
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java` line 551 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKGwpL79QXU3sWT8PH:-NEKGwpL79QXU3sWT8PI:bk5olw9) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java#L551)):*
> ```Java
>     assertThat(notificationChannelArgumentCaptor.getValue().getTemplateId()).isEqualTo(EMAIL_INVITE_TEMPLATE_ID);
>     assertThat(notificationChannelArgumentCaptor.getValue().getTemplateData().get(SHOULD_MAIL_CONTAIN_TWO_FACTOR_INFO))
>         .isEqualTo("true");
> ```

minor let's update previous tests to not have this extra segment of 2FA when 2FA not abled to account. Like for auto accept invite with no 2FA, `assertThat(notificationChannelArgumentCaptor.getValue().getTemplateData().get(SHOULD_MAIL_CONTAIN_TWO_FACTOR_INFO))` would be null/false. Thanks



_Code quote:_
```Java
    assertThat(notificationChannelArgumentCaptor.getValue().getTemplateData().get(SHOULD_MAIL_CONTAIN_TWO_FACTOR_INFO))
        .isEqualTo("true");
```

**Review by pbarapatre10 — COMMENTED** [review]
You can add screenshot for the email template update with before & after QR code so that other reviewers can check the updated template, thanks

> Reviewed 6 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603#-:-NEKHyxC-jP12uIpp0PU:b-yq3dy5)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Comment by kapil-harness** [comment]
trigger feature-build

**Comment by kapil-harness** [comment]
trigger ti1

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
sure, done

> Reviewed 6 of 8 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603#-:-NEKlnPn14tzfLrO-vtl:b-sfidww)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 679 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKFpe650Z8UtMaPMKu:-NEKlM31Dx4UnUokKTFp:b-iua60d) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L679)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit - a question: would this actually catch exception & log appropriately?, since the called method seems to be an Async method? 
</blockquote></details>

yes you are write and to confirm this I stopped PL service and then invited the user and no exception was seen in ng-manager because its an async call, thanks.
I have removed the try catch here.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 697 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKGJjSBcDWMnAzVLNX:-NEKeYOt-6VNfVOQznjK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L697)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit extract to a String constant 
</blockquote></details>

done
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java` line 551 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKGwpL79QXU3sWT8PH:-NEKjBpR-a0a-BOjZqfn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/120-ng-manager/src/test/java/io/harness/ng/core/invites/api/InviteServiceImplTest.java#L551)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor let's update previous tests to not have this extra segment of 2FA when 2FA not abled to account. Like for auto accept invite with no 2FA, `assertThat(notificationChannelArgumentCaptor.getValue().getTemplateData().get(SHOULD_MAIL_CONTAIN_TWO_FACTOR_INFO))` would be null/false. Thanks
</blockquote></details>

done
___
*[`970-ng-commons/src/main/java/io/harness/NgInviteLogContext.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/38603#-NEKCsrq97-UAJ5bOhIo:-NEKf1B9AD1UzIt4M2E1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ed375b8109562ec0b04c5bd3eb31fae677b09ed7/970-ng-commons/src/main/java/io/harness/NgInviteLogContext.java#L16)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Lets try to use this common string from `NGCommonEntityConstants` , thanks
</blockquote></details>

done

**Comment by kapil-harness** [comment]
NG Notify email w/o 2FA QR code
Screenshot 2022-10-13 at 2 33 16 PM

****************************************

NG Notify email with 2FA QR code
Screenshot 2022-10-13 at 2 33 36 PM
Screenshot 2022-10-13 at 2 33 44 PM

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 1. unresolved discussions.

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 1. unresolved discussions.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 1. unresolved discussions.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 3 of 3 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 1. unresolved discussions.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 1. unresolved discussions.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603)* status: 1. unresolved discussions.

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38603#-:-NEZFIHB-f6QpHcCf7GP:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
