### PR TITLE
[feat]: [PIE-8923]: Add rollback mode behaviour and its propagation in plan creation

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46163)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46163)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtils.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/46163#-NSOzbhI-EX7V1tux6Zu:-NSOzbhJ9VnjrWOTHAdK:b-r3hjn7) ([raw file](https://github.com/harness/harness-core/blob/ae35677b37556cc5e7e24b4ba01617ae4752b1ca/884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtils.java#L33)):*
> ```Java
>   }
> 
>   public Dependencies toDependenciesProtoWithRollbackMode(
> ```

where is this method used?



_Code quote:_
```Java
toDependenciesProtoWithRollbackMode
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/46163#-NSP-2v39lHwBC-2GKzp:-NSP-2v39lHwBC-2GKzq:bfrga3d) ([raw file](https://github.com/harness/harness-core/blob/ae35677b37556cc5e7e24b4ba01617ae4752b1ca/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L164)):*
> ```Java
>     }
>     if (!PlanCreatorServiceHelper.isBehaviourToPropagate(initialDependencyDetails.getRollbackModeBehaviour())) {
>       return;
> ```

why we are checking twice? as below checkAndAdd method is also doing the same



_Code quote:_
```Java
    if (!PlanCreatorServiceHelper.isBehaviourToPropagate(initialDependencyDetails.getRollbackModeBehaviour())) {
      return;
    }
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46163)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtils.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/46163#-NSOzbhI-EX7V1tux6Zu:-NSP55Dx8CoqkBsOwwBR:b-40b1qz) ([raw file](https://github.com/harness/harness-core/blob/ae35677b37556cc5e7e24b4ba01617ae4752b1ca/884-pms-commons/src/main/java/io/harness/pms/yaml/DependenciesUtils.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

where is this method used?
</blockquote></details>

this will be used in plan creators (rollback ones) which I'll add in a separate PR
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/46163#-NSP-2v39lHwBC-2GKzp:-NSP59Bs0il864CGC4TY:b-jpieia) ([raw file](https://github.com/harness/harness-core/blob/ae35677b37556cc5e7e24b4ba01617ae4752b1ca/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L164)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are checking twice? as below checkAndAdd method is also doing the same
</blockquote></details>

The is for forward compatibility. In future we can have other propagation behaviours.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46163)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46163)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
