### PR TITLE
[feat]:[CDS-41439]: Add Harness Store for Azure ARM/BP NG

### PR DESCRIPTION
**Pull request by nassergonzalez**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37209)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNVnA3-pCvyaecWe2E:-NBNVnA3-pCvyaecWe2F:bgyzvl2) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L151)):*
> ```Java
>     } else if (ManifestStoreType.HARNESS.equals(azureTemplateFile.getStore().getSpec().getKind())) {
>       HarnessStore harnessStore = (HarnessStore) azureTemplateFile.getStore().getSpec();
>       harnessStore = (HarnessStore) cdExpressionResolver.updateExpressions(ambiance, harnessStore);
> ```

nit: I think assignment here is not required
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWC4d5eW72JGCm_9L:-NBNWC4d5eW72JGCm_9M:b-qz23mw) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L213)):*
> ```Java
>     if (ManifestStoreType.HARNESS.equals(azureTemplateFile.getStore().getSpec().getKind())) {
>       HarnessStore harnessStore = (HarnessStore) azureTemplateFile.getStore().getSpec();
>       templateBody = azureWebAppStepHelper.fetchFileContentFromHarnessStore(ambiance, "AzureARM", harnessStore);
> ```

Second argument should be entity type, I believe in your case that would be Azure ARM Template File
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 431 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWbQoDJR33FbzWOZh:-NBNWbQoDJR33FbzWOZi:bjrvwli) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L431)):*
> ```Java
>             spec.getConfigurationParameters().getParameters().getStore().getSpec().getKind())) {
>       HarnessStore harnessStore = (HarnessStore) spec.getConfigurationParameters().getParameters().getStore().getSpec();
>       parametersBody = azureWebAppStepHelper.fetchFileContentFromHarnessStore(ambiance, "AzureARM", harnessStore);
> ```

Same here, name should be something like Azure ARM Parameters File
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWuKV9k2iv7rdgS5Z:-NBNWuKV9k2iv7rdgS5_:b-cptliz) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L218)):*
> ```Java
>       HarnessStore harnessStore =
>           (HarnessStore) azureCreateBPStepConfigurationParameters.getTemplateFile().getStore().getSpec();
>       Map<String, String> fileContent = fetchFileContentFromHarnessStore(ambiance, harnessStore);
> ```

Don't we want to support encrypted value here as well?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNX44b05oqoxfCmH_O:-NBNX44b05oqoxfCmH_P:b9chazt) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L111)):*
> ```Java
>         .mode(deploymentParameters.getDeploymentMode())
>         .templateJson(deploymentParameters.getTemplateBody().fetchFileContent())
>         .parametersJson(deploymentParameters.getParametersBody().fetchFileContent())
> ```

Is it possible that parameters will not be there? Or it is mandatory?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNG.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNXLyWCL9Odo-GBpC4:-NBNXLyWCL9Odo-GBpC5:bn77mlz) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNG.java#L109)):*
> ```Java
>       decryptFiles(((AzureARMTaskNGParameters) taskNGParameters).getParametersBody(), decryptionDetails);
>     }
>     decryptableEntities.forEach(decryptableEntity
> ```

nit: it would make more sense to have this logic on populating decryptionDetails list in task parameters so you would have only one method and wouldn't care about type of task

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: 4 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 354 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRsuwRDo7iJTkue0J9:-NBRsuwRDo7iJTkue0JA:b-xjzm1r) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L354)):*
> ```Java
>       } catch (InvalidArgumentsException ex) {
>         throw new InvalidArgumentsException(
>             ex.getMessage() + ". Check that the store is not pointing to the root folder (ex: account:/)");
> ```

Why do we catch and append this message?
I see that in fetchFileContentFromFileStore() we throw InvalidArgumentsException if fileStoreNodeDTO instanceof FolderNodeDTO
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRq9_I8eDv9HHFBVBy:-NBRq9_I8eDv9HHFBVBz:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L215)):*
> ```Java
>     assertThat(entityDetails.get(0).getEntityRef().getAccountIdentifier()).isEqualTo("test-account");
>   }
>   @Test
> ```

please add empty line
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 407 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRqCtn7Zji_SkDeub4:-NBRqCtn7Zji_SkDeub5:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L407)):*
> ```Java
>     assertThat(taskChainResponse.isChainEnd()).isTrue();
>   }
>   @Test
> ```

same here
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRtXcj2UKLjo9WWEhB:-NBRtXcj2UKLjo9WWEhC:b-jqnksa) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L42)):*
> ```Java
>         .templateJson(deploymentParameters.getTemplateBody().fetchFileContent())
>         .parametersJson(deploymentParameters.getParametersBody() != null
>                 ? deploymentParameters.getParametersBody().fetchFileContent()
> ```

Why do we set that empty json here?
If there is are no parameters let's keep "parametersJson" as null and do a null check on delegate when processing it
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNGParameters.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRufzbE7afUCIuFROo:-NBRufzbE7afUCIuFROp:bwecfzy) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNGParameters.java#L36)):*
> ```Java
> @OwnedBy(CDP)
> public class AzureARMTaskNGParameters extends AzureResourceCreationTaskNGParameters {
>   AppSettingsFile templateBody;
> ```

would the secret expressions form template file get resolved if we remove @Expression(ALLOW_SECRETS) ?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNGParameters.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRutXd6T6PSQSrV-Yp:-NBRutXd6T6PSQSrV-Yq:b1irkk7) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNGParameters.java#L47)):*
> ```Java
>     return Collections.emptyList();
>   }
>   void decryptFiles(
> ```

please add empty line

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: 4 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWC4d5eW72JGCm_9L:-NBRHWQ52QdAzqumU9A_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L213)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Second argument should be entity type, I believe in your case that would be Azure ARM Template File
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java` line 431 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWbQoDJR33FbzWOZh:-NBRHXbL3iXxX7WsYiYn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStep.java#L431)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, name should be something like Azure ARM Parameters File
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWuKV9k2iv7rdgS5Z:-NBRHYri-2ShHq-wJADm:bon2arq) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L218)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Don't we want to support encrypted value here as well?
</blockquote></details>

I checked with Ivan. So if you select encrypted in the selection window, that is just only for a single file. You can't select a folder and for BP we need to select a folder with a specific structure. So basically secret can't be use in this use case. There is also another use case that is not supported due to how the Harness Store is implemented and is having the blueprint and assign files in the root folder. So basically we need to explain in the documentation that if the customer wants to use the harness store it has to
- Create first a folder and use that folder as root
- Then create the blueprint and assign files inside that folder
- Then create another folder with the artifacts and then
- Put the artifacts there
- And in all this process, secrets are not supported
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 354 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRsuwRDo7iJTkue0J9:-NBSB7btBK_R5cUBZE-8:b-bmfhdx) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L354)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we catch and append this message?
I see that in fetchFileContentFromFileStore() we throw InvalidArgumentsException if fileStoreNodeDTO instanceof FolderNodeDTO
</blockquote></details>

I think that he message is cleaner. The exception that we catch will say that the file doesn't exist. The complementation of the message explains that it could be pointing to the root directory
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 215 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRq9_I8eDv9HHFBVBy:-NBSCohZ6KmcFGvXmRog:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L215)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java` line 407 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRqCtn7Zji_SkDeub4:-NBSCpCY5vUqMbMR-yvJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCreateARMResourceStepTest.java#L407)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNX44b05oqoxfCmH_O:-NBRNMO4Df_WFinOSFrf:b-519v4d) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L111)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is it possible that parameters will not be there? Or it is mandatory?
</blockquote></details>

You are right, I changed the logic to be a ternary operator so it the parameter is null, we will just set it to empty
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRtXcj2UKLjo9WWEhB:-NBSCqcR8zr53sHQPxYC:b-8cmmuf) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L42)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why do we set that empty json here?
If there is are no parameters let's keep "parametersJson" as null and do a null check on delegate when processing it
</blockquote></details>

This is the delegate. The idea is that at this point the delegate is going to create the context to be sent to the azure library and if there are no parameters, we can sent the parameters as empty
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNG.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNXLyWCL9Odo-GBpC4:-NBReJYA5w1jSi_CNLAm:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNG.java#L109)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: it would make more sense to have this logic on populating decryptionDetails list in task parameters so you would have only one method and wouldn't care about type of task
</blockquote></details>

Done
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNGParameters.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRufzbE7afUCIuFROo:-NBSD3oq4EQqNl_MADxc:b5po8kq) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNGParameters.java#L36)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

would the secret expressions form template file get resolved if we remove @Expression(ALLOW_SECRETS) ?
</blockquote></details>

I did some testing and the secrets are resolved without the @expression(Allow_secrets) I think that it is because the @expression(ALLOW_SECRETS) is defined in the AppSettingsFile class
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNGParameters.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRutXd6T6PSQSrV-Yp:-NBSDsoyDlU4oqrpiq1h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureResourceCreationTaskNGParameters.java#L47)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

please add empty line
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 8 files at r2, 1 of 2 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: 1 change requests. 6. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNWuKV9k2iv7rdgS5Z:-NBXYnm81F6mH_Zvm6ox:b-ahcufz) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCreateBPStep.java#L218)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I checked with Ivan. So if you select encrypted in the selection window, that is just only for a single file. You can't select a folder and for BP we need to select a folder with a specific structure. So basically secret can't be use in this use case. There is also another use case that is not supported due to how the Harness Store is implemented and is having the blueprint and assign files in the root folder. So basically we need to explain in the documentation that if the customer wants to use the harness store it has to
- Create first a folder and use that folder as root
- Then create the blueprint and assign files inside that folder
- Then create another folder with the artifacts and then
- Put the artifacts there
- And in all this process, secrets are not supported
</blockquote></details>

Make sense
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/37209#-NBNX44b05oqoxfCmH_O:-NBXZK-M01dglOIV6F4H:b316pf0) ([raw file](https://github.com/harness/harness-core/blob/76fd8265ac2c258bf59364c1cb8961842c4e79ee/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/arm/AzureARMBaseHelperImpl.java#L111)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

You are right, I changed the logic to be a ternary operator so it the parameter is null, we will just set it to empty
</blockquote></details>

nit: this can be confusing, maybe will make more sense just to have null check, but I'll let it to you to decide
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNGParameters.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/37209#-NBRufzbE7afUCIuFROo:-NBXZfn33c1C6qT9nRel:b-wa4blj) ([raw file](https://github.com/harness/harness-core/blob/9bba5cd6aebaa8121c435405a424c9d99e8e6219/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/arm/AzureARMTaskNGParameters.java#L36)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I did some testing and the secrets are resolved without the @expression(Allow_secrets) I think that it is because the @expression(ALLOW_SECRETS) is defined in the AppSettingsFile class
</blockquote></details>

No, I believe it's working for secrets because you're doing later decryption, but if your file content will contain something like: <+secrets.getValue("")> it will not work. At least this is how it used to work, maybe some recent changes but before it was evaluating only fields that has Expression annotation and if it's a complex object it should implement NestedAnnotationResolver

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2, 1 of 2 files at r3, 6 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 239 at r5](https://reviewable.io/reviews/harness/harness-core/37209#-NBkUBIM-PGPVYreUmz5:-NBkUBIM-PGPVYreUmz6:b-aeyphs) ([raw file](https://github.com/harness/harness-core/blob/820651978812a17a19ce0617f7bdfaeba2949e28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L239)):*
> ```Java
>           AzureConstants.BLUEPRINT_DEPLOYMENT_STEADY_STATE);
>     } else if (passThroughData instanceof AzureCreateARMResourcePassThroughData) {
>       return Arrays.asList(K8sCommandUnitConstants.FetchFiles, AzureCommandUnit.Create.name(),
> ```

Do we obtain any logCallback using "AzureCommandUnit.Create.name()"? why do we need it?

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 239 at r5](https://reviewable.io/reviews/harness/harness-core/37209#-NBkUBIM-PGPVYreUmz5:-NBknMdG2B4bchRNxVej:b-j4fskc) ([raw file](https://github.com/harness/harness-core/blob/820651978812a17a19ce0617f7bdfaeba2949e28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L239)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Do we obtain any logCallback using "AzureCommandUnit.Create.name()"? why do we need it?
</blockquote></details>

Yes, the logging used to log that the step was completed as success of error. File AzureResourceCreationTaskNG.java lines 87 and 89

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: 1 change requests. 1. unresolved discussions.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 13 files at r1, 1 of 8 files at r2, 1 of 2 files at r3, 4 of 7 files at r5, 3 of 4 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37209#-:-NBlYPSW-8-_iDxo6w-W:bnfp4nl)* status: :shipit: complete! ✓

**Comment by nassergonzalez** [comment]
trigger codebasehash

**Pull request merged**
