### PR TITLE
fix: [CDS-4009]: Improving logs Segregation for Fetch Files step

### PR DESCRIPTION
**Pull request by namantalaycha10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31131)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31131)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31131)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31131)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java, line 80 at r4](https://reviewable.io/reviews/harness/harness-core/31131#-MxI3NBT9Dy7EfubMFvv:-MxI3NBT9Dy7EfubMFvw:bv6x92f) ([raw file](https://github.com/harness/harness-core/blob/525a438bf8cb156cebd7e2e7810d22efeedfa084/260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java#L80)):*
> ```Java
>     printHelmBinaryPathAndVersion(taskParams.getHelmChartConfigTaskParams().getHelmVersion(), executionLogCallback);
> 
>     executionLogCallback.saveExecutionLog(color("\nStarting Helm values fetch task", LogColor.White, LogWeight.Bold));
> ```

These logs are not useful for the user because "Task" is an internal entity. We should log it into the delegate logs instead  or change the message
___
*[260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java, line 101 at r4](https://reviewable.io/reviews/harness/harness-core/31131#-MxI3YK1E4y-wGBjVPkn:-MxI3YK1E4y-wGBjVPko:bv6x92f) ([raw file](https://github.com/harness/harness-core/blob/525a438bf8cb156cebd7e2e7810d22efeedfa084/260-delegate/src/main/java/software/wings/delegatetasks/helm/HelmValuesFetchTask.java#L101)):*
> ```Java
> 
>       executionLogCallback.saveExecutionLog(
>           color("\nHelm values fetch task completed successfully", LogColor.White, LogWeight.Bold));
> ```

These logs are not useful for the user because "Task" is an internal entity. We should log it into the delegate logs instead  or change the message
___
*[260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sApplyTaskHandler.java, line 102 at r4](https://reviewable.io/reviews/harness/harness-core/31131#-MxI3Z_9-8Y2JAn3OIBu:-MxI3Z_9-8Y2JAn3OIBv:bv6x92f) ([raw file](https://github.com/harness/harness-core/blob/525a438bf8cb156cebd7e2e7810d22efeedfa084/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sApplyTaskHandler.java#L102)):*
> ```Java
>       ExecutionLogCallback executionLogCallback =
>           k8sTaskHelper.getExecutionLogCallback(k8sApplyTaskParameters, FetchFiles);
>       executionLogCallback.saveExecutionLog(color("\nStarting Kubernetes Apply Task", LogColor.White, LogWeight.Bold));
> ```

These logs are not useful for the user because "Task" is an internal entity. We should log it into the delegate logs instead  or change the message

**Comment by namantalaycha10** [comment]
Hi @yogesh-chauhan here actually they wanted the proper segregation in fetch files UI logs , should I change these task lines to something like: "Starting fetching Helm values" and "Fetching helm values completed successfully"

**Comment by namantalaycha10** [comment]
trigger ti0

**Comment by namantalaycha10** [comment]
trigger ti1

**Comment by namantalaycha10** [comment]
trigger ti2

**Comment by namantalaycha10** [comment]
trigger ti3

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 15 of 15 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31131)* status: :shipit: complete! ✓

**Pull request merged**
