### PR TITLE
fix: [CDS-51523]: Wait for Steady state logs should contain only the logs of that deployment

### PR DESCRIPTION
**Pull request by namantalaycha10**
… logs of that deployment

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN0gkQQ0u5kvEhvp1ae:-NN0gkQQ0u5kvEhvp1af:bq7379e) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L87)):*
> ```Java
>             CoreV1Event event = eventListResponse.object;
>             V1ObjectReference ref = event.getInvolvedObject();
>             K8sEventFilter k8sEventFilter = new K8sEventFilter(k8sNamespaceEventWatchDTO.getResourceIds(), coreV1Api,
> ```

This should be moved before for loop

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN0gp7w6VcLtSQnd7oL:-NN0gp7w6VcLtSQnd7oM:b52sc4d) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L44)):*
> ```Java
>   String releaseName;
> 
>   public K8sEventFilter(
> ```

Please add some UTs for this

**Comment by abhinavsingh1196** [comment]
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2eQZfAzVuLjjj6l4S:-NN2eQZfAzVuLjjj6l4T:b-anp1yw) ([raw file](https://github.com/harness/harness-core/blob/04badbc0cc420daba8ec9dceaab8661fd4aa9c91/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L111)):*
> ```Java
>           if (releaseName.equals(labels.get(HarnessLabels.releaseName))) {
>             includeResourceRefs.add(ref);
>             return;
> ```

redundant return

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: 2 file(s) to review. 2 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java` line 87 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN0gkQQ0u5kvEhvp1ae:-NN1nCPgErLL2THHxXgR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sApiEventWatcher.java#L87)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be moved before for loop
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN17qfr14HgA5Z7b6yd:-NN1gxbcCE7WGTz367Ze:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L34)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Missing class owner
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN18IbLEFS-26qfcbXj:-NN1h6ho-6hHy50UXBuf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L60)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should return true
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN18EQiDQXcr-m8hd0z:-NN1h73TAr7SsWbGB2Oi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L67)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should return true
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/43194#-NN18b5y4YUMn8qTWCVm:-NN1mtbo4QfUzGPZBBth:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed1bb79d35dae2eca0f1e8a5b21fb9e404a55f84/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L90)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

if releaseName == null should be the first condition
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2fn1H3Ja69AYWO-OJ:-NN6UDiM1nvpwbyhoe91:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3d8406e420ffd93f36d9ca40339fa2353891326/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L38)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

Should be `private static final`
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2eWCo5TrvcKneHSmT:-NN6Wbry9JRR0ESLqHaI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3d8406e420ffd93f36d9ca40339fa2353891326/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L109)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

These conditions can be combined together:
- v1 pod not null
- metadata not null
- labels not null
- labels contain releaseName key
- releaseName key equals given value

resulting condition can be put in a separate method, but it will improve readability

</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2eQZfAzVuLjjj6l4S:-NN6WdPq2eGOfsUZbONS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c3d8406e420ffd93f36d9ca40339fa2353891326/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L111)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

redundant return
</blockquote></details>

Done.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: 2 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2gVeI10wPMrKzTAQ-:-NN6gW-21-XEbdVZ5I_8:b-h06a5g) ([raw file](https://github.com/harness/harness-core/blob/c3d8406e420ffd93f36d9ca40339fa2353891326/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L62)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

would this structure be better here?
</blockquote></details>

hi @abhinavsingh1196 these are not similar
case like if kind or name is null it will return true according to your logic
but actually
if kind is null
still we are checking the name

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: 2 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2gVeI10wPMrKzTAQ-:-NN6hv0A17qs2CQ0CCDz:b9to9fj) ([raw file](https://github.com/harness/harness-core/blob/c3d8406e420ffd93f36d9ca40339fa2353891326/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L62)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

hi @abhinavsingh1196 these are not similar
case like if kind or name is null it will return true according to your logic
but actually
if kind is null
still we are checking the name
</blockquote></details>

But yes if can be more simplifying

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/43194#-NN2eWCo5TrvcKneHSmT:-NNBZMIwDQMJXpg0DyKv:bux6yem) ([raw file](https://github.com/harness/harness-core/blob/c3d8406e420ffd93f36d9ca40339fa2353891326/960-api-services/src/main/java/io/harness/k8s/steadystate/watcher/event/K8sEventFilter.java#L109)):*
<details><summary><i>Previously, namantalaycha10 (Naman Talaycha) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please move to a different method

**Comment by abosii-harness** [comment]
@namantalaycha10 please take care of this "Failed condition 3 New Critical Issues (is greater than 1)"

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43194)* status: :shipit: complete! ✓

**Pull request merged**
