### PR TITLE
[FEAT]: [PIE-6426]: Updating identifier name for matrix variables

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes
Tested on local for both stage and step variables

image
image

New Name 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45771)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 265 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEJXrN-ZIjkPY7CpSb:-NTEJXrN-ZIjkPY7CpSc:b-m5i4d6) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L265)):*
> ```Java
> 
>   public static String modifyIdentifier(Ambiance ambiance, String identifier) {
>     String accountId = getAccountId(ambiance);
> ```

nit: not required

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEKPUC8aXESUTPDzTF:-NTEKPUC8aXESUTPDzTG:b-bybqb0) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L59)):*
> ```Java
>     Map<String, Integer> combinationStringMap = new HashMap<>();
> 
>     for (Map<String, String> combination : combinations) {
> ```

Could you please add a note explaining that this is done to resolve duplicates.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 334 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEKfpW2O1TjixF6Ufm:-NTEKfpW2O1TjixF6Ufn:bff8zqd) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L334)):*
> ```Java
>     }
>     Call<ResponseDTO<SettingValueResponseDTO>> setting =
>         settingsClient.getSetting(ENABLE_MATRIX_FIELD_NAME_SETTING, pipelineEntity.getAccountIdentifier(),
> ```

Add a try catch block to set the useMatrixFieldName to false if this call resulted in an exception

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 14 of 16 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45771)* status: 0 of 1 approvals obtained.

**Review by ankittiwari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45771)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEJO0s0W-b9-ss8068:-NTEmAuuDHDzA91Ta_9m:bebrt1w) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L209)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Do we need to hotfix this to ng-manager's pre-qa branch?
</blockquote></details>

Will do
___
*[`884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java` line 265 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEJXrN-ZIjkPY7CpSb:-NTEmCmN4FNR7WqVoc86:bk0mejx) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java#L265)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: not required
</blockquote></details>

removed in rev
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEQKIH2UcySnrLz4FW:-NTEmEPFB-HwkF8ZhmF8:bc1c7o0) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L57)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

how is this combinationStringMap used anywhere? didnt get it
</blockquote></details>

WE are using it to identify common name combinations during Data creation. It creates a name for a particular combo, and adds it into the map. If the same name comes again, we add a prefix to the combination key value. 

This saves analysis while fetching the data
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEKPUC8aXESUTPDzTF:-NTEm_RX-gV_jTjI0tI9:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L59)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Could you please add a note explaining that this is done to resolve duplicates.
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 334 at r3](https://reviewable.io/reviews/harness/harness-core/45771#-NTEKfpW2O1TjixF6Ufm:-NTEmaf61pJKgmZIBxHg:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e583d877e79fe735d4b80d9c6679c76b66922804/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L334)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a try catch block to set the useMatrixFieldName to false if this call resulted in an exception
</blockquote></details>

done

**Review by sahilhindwani-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45771#-:-NTHeuliC_oH9QVdZ3uj:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Comment by ankittiwari-harness** [comment]
trigger reviewCheck

**Pull request merged**
