### PR TITLE
feat: [PL-26594]: NG Settings resolution

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 23 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_J31W6XoSccJRvvL8:-N7_J31W6XoSccJRvvL9:b-sby4ww) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L42)):*
> ```Java
>   @Override
>   public ResponseDTO<List<SettingResponseDTO>> list(String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, SettingCategory category, String group) {
> ```

rename to groupIdentifier
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_J9tI0tjRs24oa_ZT:-N7_J9tJ-g0RObzO6dOK:b-sby4ww) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L47)):*
> ```Java
>     }
>     return ResponseDTO.newResponse(
>         settingsService.list(accountIdentifier, orgIdentifier, projectIdentifier, category, group));
> ```

rename to groupIdentifier
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/SettingsService.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_JC4T0smbd9MoORCM:-N7_JC4T0smbd9MoORCN:b-sby4ww) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/SettingsService.java#L21)):*
> ```Java
> public interface SettingsService {
>   List<SettingResponseDTO> list(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, SettingCategory category, String group);
> ```

rename to groupIdentifier
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_MIRO32-xWzABanZA:-N7_MIRPE1XfS3kmw_f7:b-1fk6tz) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L111)):*
> ```Java
>   }
> 
>   private ScopeLevel getHighestScopeForSetting(Set<ScopeLevel> allowedScopes) {
> ```

move to utility class
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_NhJB7F-rWo_rkKn7:-N7_NhJB7F-rWo_rkKn8:b3l6ax1) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L154)):*
> ```Java
>               settingRequestDTO.getIdentifier());
>       if (setting.isPresent()) {
>         if (setting.get().getAllowOverrides()) {
> ```

combine these as single if condition
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_OuEi3QslJHfQ6CdQ:-N7_OuEi3QslJHfQ6CdR:b-rpf01n) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L161)):*
> ```Java
>       }
>     }
>     Optional<SettingConfiguration> settingConfiguration =
> ```

add check for highest scope
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 241 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_QsLn-Xxp3c7m1Yh-:-N7_QsLn-Xxp3c7m1Yh0:b-digr8e) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L241)):*
> ```Java
>                     .and(SettingKeys.projectIdentifier)
>                     .is(projectIdentifier)));
>     if (groupIdentifier != null) {
> ```

use isNotEmpty in place of null check
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 256 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_R2aS6_FEhuUWxAze:-N7_R2aS6_FEhuUWxAzf:b-digr8e) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L256)):*
> ```Java
>     List<ScopeLevel> scopes = Collections.singletonList(ScopeLevel.of(scope));
>     List<SettingConfiguration> defaultSettingConfigurations;
>     if (group != null) {
> ```

use isNotEmpty in place of null check
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 323 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_T8Si-9OIa1i6trDz:-N7_T8Si-9OIa1i6trE-:b-7iobqm) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L323)):*
> ```Java
>   private void deleteSettingInSubScopes(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, SettingRequestDTO settingRequestDTO) {
>     if (isEmpty(orgIdentifier)) {
> ```

Use scope and rewrite conditions using scopes.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 332 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_TVW80vEOTAcTauch:-N7_TVW80vEOTAcTauci:b-7iobqm) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L332)):*
> ```Java
> 
>   private Scope getParentScope(Scope currentScope) {
>     if (isNotEmpty(currentScope.getProjectIdentifier())) {
> ```

Use scope and rewrite conditions using scopes.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/settings/SettingsCreationJob.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_TgLo1hqacEcYhbO5:-N7_TgLo1hqacEcYhbO6:b-g8dz4u) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/settings/SettingsCreationJob.java#L67)):*
> ```Java
> 
>   private void populateDefaultConfigs(SettingsConfig settingsConfig) {
>     settingsConfig.getSettings().forEach(settingConfiguration -> {
> ```

Check if this can be avoided by using some annotation to provide the default value.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)* status: 11 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_J31W6XoSccJRvvL8:-N7_mcHvCXEJtVXDgxtK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

rename to groupIdentifier
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_J9tI0tjRs24oa_ZT:-N7_mg1L1_O5ZupJNql6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/remote/SettingsResourceImpl.java#L47)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

rename to groupIdentifier
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/SettingsService.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_JC4T0smbd9MoORCM:-N7_mhmb9MjELNGjN7RX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/SettingsService.java#L21)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

rename to groupIdentifier
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_MIRO32-xWzABanZA:-N7_nVvS1F2Gj6Bvc5MV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L111)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

move to utility class
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_NhJB7F-rWo_rkKn7:-N7_nne94QUT9FayUKaC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L154)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

combine these as single if condition
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_OuEi3QslJHfQ6CdQ:-N7_pff0C5DPecFNxVuZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L161)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

add check for highest scope
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 241 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_QsLn-Xxp3c7m1Yh-:-N7_qCHCCh60xTLc2dfk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L241)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use isNotEmpty in place of null check
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 256 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_R2aS6_FEhuUWxAze:-N7_qE701LYcFw4GUBwp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L256)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use isNotEmpty in place of null check
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 323 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_T8Si-9OIa1i6trDz:-N7a728s1iREWHvWN4d2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L323)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use scope and rewrite conditions using scopes.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 332 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_TVW80vEOTAcTauch:-N7a72Zh3WWfWPjY6qMP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L332)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use scope and rewrite conditions using scopes.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/settings/SettingsCreationJob.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/35613#-N7_TgLo1hqacEcYhbO5:-N7a9ct598YFkDRrW-wD:bvuvoq0) ([raw file](https://github.com/harness/harness-core/blob/14c0da99514aba9707fd2da896ae7540eec0548b/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/settings/SettingsCreationJob.java#L67)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Check if this can be avoided by using some annotation to provide the default value.
</blockquote></details>

A direct annotation is not available, we can change this in the next release if there is a feasible solution

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 1 of 23 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)* status: 25 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/35613#-N7aMjYO4lJCc3_rT-Wn:-N7aMjYP49-ksP3HBjGP:bgi4b1x) ([raw file](https://github.com/harness/harness-core/blob/d51995d9f11cb569168eec4c82e469c78b4d24ce/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/utils/SettingUtils.java#L106)):*
> ```Java
> 
>   public Scope getParentScope(Scope currentScope) {
>     if (isNotEmpty(currentScope.getProjectIdentifier())) {
> ```

These checks can also be done via ScopeLevel.

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 23 files at r1, 1 of 8 files at r2, 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613#-:-N7dg46wB6s_Mma0CPzU:bnfp4nl)* status: :shipit: complete! ✓

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35613)* status: :shipit: complete! ✓

**Pull request merged**
