### PR TITLE
[fix]: [CDS-24529]: change http step name to HTTP

### PR DESCRIPTION
**Pull request by atharvatrivedi1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30874)

### CODE REVIEW

**Comment by atharvatrivedi1** [comment]
trigger ti4

**Comment by atharvatrivedi1** [comment]
trigger authorcheck

**Comment by atharvatrivedi1** [comment]
trigger authorcheck

**Comment by atharvatrivedi1** [comment]
trigger authorcheck

**Comment by atharvatrivedi1** [comment]
trigger authorcheck

**Comment by atharvatrivedi1** [comment]
trigger authorcheck

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30874)* status: :shipit: complete! ✓

**Pull request merged**
