### PR TITLE
fix: [CCM-8837]: Anomaly notification sent status

### PR DESCRIPTION
**Pull request by trunapushpa**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40318)

### CODE REVIEW

**Review by divyanshuchaubisa — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40318)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/40318#-NH8_dyN1ZmRDDJsEi4v:-NH8_dyOCf1NJYcUxiRQ:b-g149ln) ([raw file](https://github.com/harness/harness-core/blob/970e1988140d8c3182ae97e6fef79dce0fdf04f2/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java#L90)):*
> ```Java
>                                                      .where(ANOMALIES.ACCOUNTID.eq(accountId)
>                                                                 .and(ANOMALIES.ANOMALYTIME.eq(toOffsetDateTime(date)))
>                                                                 .and(ANOMALIES.NOTIFICATIONSENT.eq(false))
> ```

For existing entries, are we going to backfill with `false` value ? If not then we can consider empty values as well in the query?
___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/40318#-NH8_IiXAf0bxP8vzC8I:-NH8_IiXAf0bxP8vzC8J:b-uqpte) ([raw file](https://github.com/harness/harness-core/blob/970e1988140d8c3182ae97e6fef79dce0fdf04f2/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java#L124)):*
> ```Java
>   @RetryOnException(retryCount = RETRY_COUNT, sleepDurationInMilliseconds = SLEEP_DURATION)
>   public void updateAnomalyNotificationSentStatus(
>       @NonNull String accountId, String anomalyId, boolean notificationSentStatus) {
> ```

We can validate the @NotNull check for anomalyId as well here ?

**Review by trunapushpa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40318)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/40318#-NH8_dyN1ZmRDDJsEi4v:-NHDTPyRAFwmGf7-LSEk:b-qdgjd9) ([raw file](https://github.com/harness/harness-core/blob/970e1988140d8c3182ae97e6fef79dce0fdf04f2/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java#L90)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

For existing entries, are we going to backfill with `false` value ? If not then we can consider empty values as well in the query?
</blockquote></details>

While adding the `notificationsent` column in timescale, we have set the default value to FALSE. That should take care of backfilling, or even insertion without the value.
___
*[`490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/40318#-NH8_IiXAf0bxP8vzC8I:-NHDTNSM8Xegb-bzo3xD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/970e1988140d8c3182ae97e6fef79dce0fdf04f2/490-ce-commons/src/main/java/io/harness/ccm/commons/dao/anomaly/AnomalyDao.java#L124)):*
<details><summary><i>Previously, divyanshuchaubisa (Divyanshu Chaubisa) wrote…</i></summary><blockquote>

We can validate the @NotNull check for anomalyId as well here ?
</blockquote></details>

Done

**Review by svmav — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40318)* status: 1 change requests. 2. unresolved discussions.

**Comment by USB-05** [comment]
trigger ss

**Review by divyanshuchaubisa — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40318)* status: 2. unresolved discussions.

**Review by trunapushpa — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40318#-:-NHOlgnC5L1dKVXAU4a1:bnfp4nl)* status: 2. unresolved discussions.

**Review by hitesharinga — APPROVED** [review]

**Review by hitesharinga — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40318)* status: 2. unresolved discussions.

**Pull request merged**
