### PR TITLE
feat: [DEL-5019]: Endpoint to check latest supported delegate version

### PR DESCRIPTION
**Pull request by AnupamIO**
Add endpoint for fetching delegate version supported. 
Input needed: accoountId -> this will be used to determine ring.
x-api-key: api-key in header.

Testing:
local postman.
Screenshot 2022-12-06 at 2 02 50 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/41174#-NIae_gO8A_skzm_eQYr:-NIae_gO8A_skzm_eQYs:bgkv53e) ([raw file](https://github.com/harness/harness-core/blob/22819e57daea40a9bff04ad15d1314757351fbe2/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java#L15)):*
> ```Java
>   private final String latestSupportedVersion;
>   private final String latestSupportedMinimalVersion;
>   private final String metadata;
> ```

what it does contain ?

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/41174#-NIaei7P3MyEiMO4ArzZ):*
write comments in pr about what this change is and what testing has been done.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/41174#-NIaei7P3MyEiMO4ArzZ):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

write comments in pr about what this change is and what testing has been done.
</blockquote></details>

Done.
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/41174#-NIae_gO8A_skzm_eQYr:-NIaivAj0IciyELITD6u:b17xomp) ([raw file](https://github.com/harness/harness-core/blob/22819e57daea40a9bff04ad15d1314757351fbe2/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java#L15)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

what it does contain ?
</blockquote></details>

essentially whatever version is present in ring for that account.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/41174#-NIae_gO8A_skzm_eQYr:-NIas-RWCnMARPBITl92:bry8k9d) ([raw file](https://github.com/harness/harness-core/blob/22819e57daea40a9bff04ad15d1314757351fbe2/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java#L15)):*
> ntially whatever version is present in ring for that account.
How is it different from `latestSupportedVersion` ?

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/41174#-NIae_gO8A_skzm_eQYr:-NIbsBcD6EJy3QFl6HPX:bpmkb2o) ([raw file](https://github.com/harness/harness-core/blob/22819e57daea40a9bff04ad15d1314757351fbe2/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/SupportedDelegateVersion.java#L15)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> ntially whatever version is present in ring for that account.
How is it different from `latestSupportedVersion` ?
</blockquote></details>

latestSupportedVersion is same as version present in ring.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41174)* status: :shipit: complete! ✓

**Pull request merged**
