### PR TITLE
feat: [PL-41470]: Fixed role-assignment listing for user

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
While filtering role-assignments for a user for a different scope, usergroup roleassigments were missing.
This was happening due to recent change done to filter usergroups for given scope only.  For fixing this we have added new service method that filters usergroup for all scope, depending on scope selector filter.

Testing:
1. Tested for ALL Account including child scope.
2. Tested for Only Account, Only Org, Only Project.
3. Tested for ALL at Org level (this should fetch Account and project scope RA both)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54076)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
@meenakshi-harness  Need to rebase PR. Changes look good. Please add UTs.

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger ut5, ut8

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 56 files at r1, 50 of 50 files at r2, 2 of 3 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54076)* status: 57 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/persistence/UserGroupDaoImpl.java` line 103 at r7](https://reviewable.io/reviews/harness/harness-core/54076#-Nh6Talt3bKjr0yjFVQL:-Nh6Talu5ivhOOVwLc-B:bng50r0) ([raw file](https://github.com/harness/harness-core/blob/307a4b6fd8b57cad981af99d424dd5eb1e75d6bc/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/persistence/UserGroupDaoImpl.java#L103)):*
> ```Java
>     criteria.orOperator(scopeCriterion.toArray(new Criteria[0])).and(UserGroupDBOKeys.users).in(userIdentifier);
> 
>     List<UserGroupDBO> userGroupPages = userGroupRepository.find(criteria);
> ```

Did we check if this using index?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54076)* status: 57 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/persistence/UserGroupDaoImpl.java` line 103 at r7](https://reviewable.io/reviews/harness/harness-core/54076#-Nh6Talt3bKjr0yjFVQL:-Nh6bwJRALfK5JPchUwp:b-3ipbgn) ([raw file](https://github.com/harness/harness-core/blob/307a4b6fd8b57cad981af99d424dd5eb1e75d6bc/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/persistence/UserGroupDaoImpl.java#L103)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Did we check if this using index?
</blockquote></details>

Yes its using index

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54076)* status: 57 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
