### PR TITLE
feat: [DEL-3944]: Remove grpc calls between manager and delegate

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:

- Remove grpc call from delegate and use proto over REST to communicate with manager
- This PR includes changing perpetual task and task progress API's. Introducing two new Resource files, as well as converting existing client api files(PerpetualTaskServiceAgentClient &  DelegateServiceAgentClient) to use rest instead of grpc.
- Calls(Async) also has support retry mechanism on failure 

## Checklist
- [ x] I've documented the changes in the PR description.
- [ x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35194)

### CODE REVIEW

**Comment by jennyjames21** [comment]
Connector Validation PT Task
image

**Comment by jennyjames21** [comment]
Get K8 PT Task context
image

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/35194#-N6jQhmvCpIu6VFw1PIr:-N6jQhmvCpIu6VFw1PIs:b-hg3x0t) ([raw file](https://github.com/harness/harness-core/blob/ad48adb6a1258218b9a57b2f0f270627464d35af/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L257)):*
> ```Java
> 
>   @Override
>   public List<PerpetualTaskAssignDetails> listAssignedTasks(String delegateId, String accountId) {
> ```

why did we need to add this?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 12 of 18 files at r1, 4 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35194)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/35194#-N6jRJun-6vFALqZSpBb:-N6jRqlg-vh5IEAMwUyi:b-y5fzpa) ([raw file](https://github.com/harness/harness-core/blob/ad48adb6a1258218b9a57b2f0f270627464d35af/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L164)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why these additional APIs?
</blockquote></details>

Instead of moving im copying here(from DelegateTaskServiceClassicImpl). We cannot move that rite now as we need for older delegates that are using grpc. In final phase part of the clean up process i can remove from DelegateTaskServiceClassicImpl

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java` line 257 at r3](https://reviewable.io/reviews/harness/harness-core/35194#-N6jQhmvCpIu6VFw1PIr:-N6ncUhCEckesKmMaHuo:b-do9x08) ([raw file](https://github.com/harness/harness-core/blob/4232579e16aea9d63405a13873cac4bc7bb5e24d/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L257)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

because for grpc it takes account id from context versus for rest we need to pass around
</blockquote></details>

lets use this in the above method

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35194)* status: :shipit: complete! ✓

**Pull request merged**
