### PR TITLE
feat: [DEL-5972]: fetching tasks log api

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes

API for fetching delegate stackdriver logs.
The API will fetch delegate agent's task logs for a given period of time

Test Status: Validated
PR ENV is alive: [https://del.pr.harness.io/del-1002
image

image

Screen Shot 2023-02-09 at 8 54 42 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42581)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateStackDriverLog.java` line 16 at r5](https://reviewable.io/reviews/harness/harness-core/42581#-NP-_zcs2PVSzdonnaB8:-NP-_zct9sKaJR4mHoSP:bz2x8rw) ([raw file](https://github.com/harness/harness-core/blob/ef05a9fab79247629f6e68a2c71377abd5d6803f/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateStackDriverLog.java#L16)):*
> ```Java
> @Builder
> public class DelegateStackDriverLog {
>   String ISOTime;
> ```

all of them should be private

**Comment by raghuAtWings** [comment]
*[`970-ng-commons/src/main/java/io/harness/ng/beans/PageRequest.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/42581#-NP-aPoo59a48WkpaWkt:-NP-aPoo59a48WkpaWku:bd8d7u9) ([raw file](https://github.com/harness/harness-core/blob/ef05a9fab79247629f6e68a2c71377abd5d6803f/970-ng-commons/src/main/java/io/harness/ng/beans/PageRequest.java#L51)):*
> ```Java
>   @Parameter(description = PAGE_TOKEN_PARAM_MESSAGE) @QueryParam(PAGE_TOKEN_KEY) String pageToken;
> 
>   public PageRequest(final int pageIndex, final int pageSize, final List<SortOrder> sortOrders) {
> ```

why do we need this?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 4 of 14 files at r1, 4 of 5 files at r2, 4 of 7 files at r3, 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42581)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42581)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateStackDriverLog.java` line 16 at r5](https://reviewable.io/reviews/harness/harness-core/42581#-NP-_zcs2PVSzdonnaB8:-NP6-wlO0ZIjmlokKdtU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef05a9fab79247629f6e68a2c71377abd5d6803f/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateStackDriverLog.java#L16)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

all of them should be private 
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/ng/beans/PageRequest.java` line 51 at r5](https://reviewable.io/reviews/harness/harness-core/42581#-NP-aPoo59a48WkpaWkt:-NP6-xaVERn7aeispnby:b-o14bcl) ([raw file](https://github.com/harness/harness-core/blob/ef05a9fab79247629f6e68a2c71377abd5d6803f/970-ng-commons/src/main/java/io/harness/ng/beans/PageRequest.java#L51)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

because before adding the new field "pageToken", this constructor has been used in many places.
pageIndex (int) and pageToken(string) essentially are the same kind of pagination, but in some implementation int is used to locate a page, while in some (like google api) string is used to locate a page.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42581)* status: Waiting on team(s): del-team.

**Pull request merged**
