### PR TITLE
feat: [PIE-5995]: added support for expression for duration in wait step

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39288)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStep.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/39288#-NFOIK2L1s1mpCnjnmXt:-NFOIK2L1s1mpCnjnmXu:b-3b8tu8) ([raw file](https://github.com/harness/harness-core/blob/52cc1b7b33bbef87909352c5e66901b8daab50d8/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStep.java#L52)):*
> ```Java
>       duration = (int) durationParameterField.getValue().getTimeoutInMillis();
>     } else {
>       duration = (int) Objects.requireNonNull(Timeout.fromString(String.valueOf(durationParameterField.getValue())))
> ```

add unit-test for this.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39288)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39288)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStep.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/39288#-NFgqRl61YksFjkk2eqp:-NFgqRl88jaI_Kfvy5WS:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/52cc1b7b33bbef87909352c5e66901b8daab50d8/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStep.java#L47)):*
> ```Java
>     String correlationId = UUIDGenerator.generateUuid();
>     WaitStepParameters waitStepParameters = (WaitStepParameters) stepParameters.getSpec();
>     ParameterField<Timeout> durationParameterField = waitStepParameters.duration;
> ```

discussed offline

**Comment by shalini-agr** [comment]
trigger ti0,ti1,ti2,ti3,ti4,ft1,ft2

**Comment by shalini-agr** [comment]
trigger checkstyle,pmd, compile

**Comment by shalini-agr** [comment]
trigger compile

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39288)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStep.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/39288#-NFgqRl61YksFjkk2eqp:-NFhhCNG-nJeNxhs5IlO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/52cc1b7b33bbef87909352c5e66901b8daab50d8/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStep.java#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

discussed offline
</blockquote></details>

done

**Pull request merged**
