### PR TITLE
feat: [CDS-36905]: add variables for service, env and infra for v2 pipelines

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. This PR adds expressions related to service/env/infra.
2. These expressions are added to service node, environment node, infradefinitions -> ref node respectively for correct mapping on UI. 
3. Added accountId, orgId etc. to VariableCreationContext so its available to children nodes.
4. Basic service/env expressions are added when they are runtime inputs as well. Eg. <+service.name>
5. serviceVariables: These are collected from env variables, service overrides and service variables.
6. VariableCreatorHelper: changed fieldType to fieldValue. @archit-harness Please review this change.
7. Skipped service/env yamls from variables framework.
8. Added try-catch so it doesnt affect the other nodes. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34696)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34696)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/34696#-N5cjxVT-od_Z8SVm-m9:-N5cjxVT-od_Z8SVm-mA:b2r2v5a) ([raw file](https://github.com/harness/harness-core/blob/7d67e54eec8aeb143d73376c2afc2af468470935/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L204)):*
> ```Java
>     variableCreators.add(new GitOpsMergePRStepVariableCreator());
>     variableCreators.add(new DeploymentStageVariableCreator(
>         serviceEntityService, environmentService, serviceOverrideService, infrastructureEntityService));
> ```

these can be directly injected inside creator, why to pass?



_Code quote:_
```Java
serviceEntityService, environmentService, serviceOverrideService, infrastructureEntityService))
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/34696#-N5ck2Hy6-8ZZ8zCfjQ2:-N5ck2Hy6-8ZZ8zCfjQ3:b-pt2cvd) ([raw file](https://github.com/harness/harness-core/blob/7d67e54eec8aeb143d73376c2afc2af468470935/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java#L84)):*
> ```Java
>   @Inject private final ServiceOverrideService serviceOverrideService;
>   @Inject private final InfrastructureEntityService infrastructureEntityService;
> ```

You are already injecting



_Code quote:_
```Java
  @Inject private final ServiceEntityService serviceEntityService;
  @Inject private final EnvironmentService environmentService;
  @Inject private final ServiceOverrideService serviceOverrideService;
  @Inject private final InfrastructureEntityService infrastructureEntityService;
```
___
*[`882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java` line 598 at r2](https://reviewable.io/reviews/harness/harness-core/34696#-N5ckHks1AykrY3KYZKp:-N5ckHks1AykrY3KYZKq:b17olag) ([raw file](https://github.com/harness/harness-core/blob/7d67e54eec8aeb143d73376c2afc2af468470935/882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java#L598)):*
> ```Java
>       addExpressionInCustomObject(field, parameterFieldValue.getValue(), resultantFieldExpressions, mergedFqn);
>     } else {
>       resultantFieldExpressions.addAll(getExpressionsInObject(fieldValue, mergedFqn));
> ```

why this change was needed?



_Code quote:_
```Java
fieldValue
```

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34696)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 204 at r2](https://reviewable.io/reviews/harness/harness-core/34696#-N5cjxVT-od_Z8SVm-m9:-N5eVqUKA1iOMAvxT40A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d67e54eec8aeb143d73376c2afc2af468470935/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L204)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Revert your change here, send new only
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreatorTest.java` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/34696#-N5djWtJBZKrnbELZdIF:-N5eVTsRAg4YGfsGqr17:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44e4f122c248bb08fb10dbcaebc0569c34bc1862/125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreatorTest.java#L261)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not expose infra.environment.* expressions
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreatorTest.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/34696#-N5djd4s03kJ5_-Mw1vk:-N5eVTIoADAdFi6S0K0i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44e4f122c248bb08fb10dbcaebc0569c34bc1862/125-cd-nextgen/src/test/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreatorTest.java#L271)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add unit test for artifacts as well
</blockquote></details>

Done.
___
*[`882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java` line 598 at r2](https://reviewable.io/reviews/harness/harness-core/34696#-N5ckHks1AykrY3KYZKp:-N5eVXFL1eCXDk5ZBR3r:b-n488rq) ([raw file](https://github.com/harness/harness-core/blob/7d67e54eec8aeb143d73376c2afc2af468470935/882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/VariableCreatorHelper.java#L598)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you test it out, if any unit test fails or not, earlier any custom object having custom object was not there? f not if you have tested then itsokay, but confirm once
</blockquote></details>

Yeah I have checked the usages. Nested objects are skipped so we weren't running into this. Steps mostly have primitive/parameter fields.

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 5 of 9 files at r3, 13 of 14 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34696)* status: 1 change requests. 4. unresolved discussions.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 12 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34696)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34696)* status: :shipit: complete! ✓

**Pull request merged**
