### PR TITLE
[feat]: [CDS-77115] : call override v2 api for environment api when override v2 enabled

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

Environment Create/Update/Upsert
* environment db get updated as usual
* if environment request contain variables or override section, then override v2 create/update call goes
* return the same yaml as given in request 

Environment get - No change
Environment delete - No change, as environment delete, also delete override through cascade deletion

Service Override Upsert
* save request yaml as yaml internal, to send back in response
* call override v2 create/update

Service Override delete - no change

Service Override Get -
* set yaml as yamlInternal in response

Test Executed
Terraform Override v1 tests + Override V2 disabled
Terraform Override v1 tests + Override V2 enabled
Terraform Override v2 tests + Override V2 enabled
Terraform Environment tests + Override V2 enabled
Terraform Environment tests + Override V2 disabled

Cli Test:

resource "harness_platform_environment_service_overrides" "localexample2" {
  org_id     = "default"
  project_id = "Project1"
  env_id     = "env1"
  service_id = "s1"
  yaml       = <<-EOT
        serviceOverrides:
          environmentRef: env1
          serviceRef: s1
          variables:
           - name: test1
             type: String
             value: test1
          EOT
}

resource "harness_platform_environment" "example" {
  identifier = "identifier"
  name       = "name"
  org_id     = "default"
  project_id = "Project1"
  tags       = ["foo:bar", "bar:foo"]
  type       = "PreProduction"
  yaml = <<-EOT
      environment:
         name: name
         identifier: identifier
         orgIdentifier: default
         projectIdentifier: Project1
         type: PreProduction
         tags:
           foo: bar
           bar: foo
         variables:
           - name: envVar1
             type: String
             value: v1
             description: ""
  EOT
}

resource "harness_platform_environment" "example2" {
  identifier = "identifier2"
  name       = "identifier2"
  org_id     = "default"
  project_id = "Project1"
  tags       = ["foo:bar", "bar:foo"]
  type       = "PreProduction"
  yaml = <<-EOT
      environment:
         name: identifier2
         identifier: identifier2
         orgIdentifier: default
         projectIdentifier: Project1
         type: PreProduction
         tags:
           foo: bar
           bar: foo
  EOT

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52142)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52142)* status: 6 file(s) to review. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 271 at r3](https://reviewable.io/reviews/harness/harness-core/52142#-NdAewKMEsc7omEAXO6w:-NdAewKMEsc7omEAXO6x:bm2w6s5) ([raw file](https://github.com/harness/harness-core/blob/a93c224cbf5d7b9c2e19be3fd1314172860c9117/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L271)):*
> ```Java
>              NGCommonEntityConstants.ACCOUNT_KEY) String accountId,
>       @Parameter(description = "Details of the Environment to be created")
>       @Valid EnvironmentRequestDTO environmentRequestDTO) throws IOException {
> ```

IOException will be caught and processed by the framework, can we rethrow the custom uncheck exception on the service level?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 307 at r3](https://reviewable.io/reviews/harness/harness-core/52142#-NdAibQz3WesDEOXUpM8:-NdAibQz3WesDEOXUpM9:b-jvep2p) ([raw file](https://github.com/harness/harness-core/blob/a93c224cbf5d7b9c2e19be3fd1314172860c9117/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L307)):*
> ```Java
> 
>     if (overrideRequestDTOV2 != null) {
>       Optional<NGServiceOverridesEntity> envGlobalOverridesEntity = serviceOverridesServiceV2.get(accountId,
> ```

Is it possible that service overrides exist for newly created env?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 991 at r3](https://reviewable.io/reviews/harness/harness-core/52142#-NdAkETYEpQS9z6AWtZ2:-NdAkETYEpQS9z6AWtZ3:b-gdcz22) ([raw file](https://github.com/harness/harness-core/blob/a93c224cbf5d7b9c2e19be3fd1314172860c9117/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L991)):*
> ```Java
>     boolean overridesV2Enabled = isOverridesV2Enabled(accountId, orgIdentifier, projectIdentifier);
>     if (overridesV2Enabled) {
>       log.warn(format("Using service override v1 api in projectId: %s, orgId: %s, accountId: %s", projectIdentifier,
> ```

do you mean override v2, the message could be improved.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 1283 at r3](https://reviewable.io/reviews/harness/harness-core/52142#-NdAkrTs1TV9g5yBLJT-:-NdAkrTs1TV9g5yBLJT0:b-cbhmin) ([raw file](https://github.com/harness/harness-core/blob/a93c224cbf5d7b9c2e19be3fd1314172860c9117/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L1283)):*
> ```Java
>       String accountId, String orgId, String projectId, String envIdentifier) {
>     String envQualifiedRef = IdentifierRefHelper.getRefFromIdentifierOrRef(accountId, orgId, projectId, envIdentifier);
>     return String.join("_", envQualifiedRef).replace(".", "_");
> ```

do we need "_" in join if envQualifiedRef is not list? 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/mappers/ServiceOverridesMapperV2.java` line 129 at r3](https://reviewable.io/reviews/harness/harness-core/52142#-NdAnfCr0tJW6vS-Thuj:-NdAnfCr0tJW6vS-Thuk:beaej1y) ([raw file](https://github.com/harness/harness-core/blob/a93c224cbf5d7b9c2e19be3fd1314172860c9117/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/mappers/ServiceOverridesMapperV2.java#L129)):*
> ```Java
>     NGEnvironmentInfoConfig envInfoConfig = environmentConfig.getNgEnvironmentInfoConfig();
>     if (isEmpty(envInfoConfig.getVariables()) && envInfoConfig.getNgEnvironmentGlobalOverride() == null) {
>       return null;
> ```

Optional could be a better choice than renaming the method name.

**Comment by tchaurasiya** [comment]
trigger uts

**Review by ivan-83 — COMMENTED** [review]
Everything looks fine to me, let's discuss updateEnvSpecificOverrideV2 method

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52142#-:-NdBpMCO8J2wLlPSCCGY:brb7dln)* status: 6 file(s) to review. 0 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52142#-:-NdEW9X31WshQ0wEURC_:bnfp4nl)* status: 6 file(s) to review.

**Comment by tchaurasiya** [comment]
trigger review

**Pull request merged**
