### PR TITLE
feat: [PIE-8948]: Support for strategy expressions via new engine

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45119)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45119)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/45119#-NQUzTxS28JMEiw3tFq6:-NQUzTxS28JMEiw3tFq7:b-r1ld0p) ([raw file](https://github.com/harness/harness-core/blob/81c249a3e9327281144b52be6d59f886deeeebf6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java#L44)):*
> ```Java
>     }
>     List<String> expressions = new ArrayList<>();
>     expressions.add(String.format("expandedJson.%s", expression));
> ```

How this expandedJson will work? we didnt add in the prefixes right?

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45119)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/45119#-NQUzTxS28JMEiw3tFq6:-NQV-w_S8OtBpSA_fo3x:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/81c249a3e9327281144b52be6d59f886deeeebf6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/ExpandedJsonFunctorUtils.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

How this expandedJson will work? we didnt add in the prefixes right?
</blockquote></details>

done, discussed offline

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45119)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45119)* status: :shipit: complete! ✓

**Pull request closed without merging**
