### PR TITLE
[feat]: [CDS-39691]: infra detail addition to service_infra_info and activeServiceDeployme…

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
…nts API

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: :shipit: complete! ✓

**Comment by abhinavmittal-harness** [comment]
*[`800-pipeline-service/src/main/resources/timescale/add_infrastructureIdentifier_to_service_infra_info_table.sql` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/35303#-N6vLtdf31DkSpPcQFon:-N6vLtdf31DkSpPcQFoo:bu4ublp) ([raw file](https://github.com/harness/harness-core/blob/48addc216d554dca7f844e64a1675b2bc721c9da/800-pipeline-service/src/main/resources/timescale/add_infrastructureIdentifier_to_service_infra_info_table.sql#L3)):*
> ```TSQL
> BEGIN;
> 
> ALTER TABLE service_infra_info ADD COLUMN infrastructureIdentifier text;
> ```

Use if not exists
ADD COLUMN IF NOT EXISTS

**Comment by Abhishek-CDC** [comment]
*[`800-pipeline-service/src/main/resources/timescale/add_infrastructureIdentifier_to_service_infra_info_table.sql` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/35303#-N6vLtdf31DkSpPcQFon:-N6vR4UYCgb5D5vMT0mz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48addc216d554dca7f844e64a1675b2bc721c9da/800-pipeline-service/src/main/resources/timescale/add_infrastructureIdentifier_to_service_infra_info_table.sql#L3)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Use if not exists
ADD COLUMN IF NOT EXISTS
</blockquote></details>

Done.

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by Abhishek-CDC** [comment]
trigger codebasehash

**Comment by Abhishek-CDC** [comment]
trigger codebasehash

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: Some of the checks are too old.

**Comment by Abhishek-CDC** [comment]
trigger ti2

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35303)* status: :shipit: complete! ✓

**Pull request merged**
