### PR TITLE
[feat]: [PIE-6165]: Add next stage advisor for parallel rollback blocks plus unit tests

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39597)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39597)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39597)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39597)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/39597#-NG0bfvXBdrnz63WE1YX:-NG0bfvXBdrnz63WE1YY:b-ln6s46) ([raw file](https://github.com/harness/harness-core/blob/69019e35c7e5b70cb4e60004675e6f08c4aeb881/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java#L100)):*
> ```Java
>     List<String> childNodeIDs = new ArrayList<>();
>     stageNodes.forEach(stageNode -> {
>       YamlNode stageNodeInternal = stageNode.getFieldOrThrow(YAMLFieldNameConstants.STAGE).getNode();
> ```

why do we need field or throw?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39597)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/39597#-NG0bfvXBdrnz63WE1YX:-NG0uack4OOq_xrL8CQV:bgujnqs) ([raw file](https://github.com/harness/harness-core/blob/69019e35c7e5b70cb4e60004675e6f08c4aeb881/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need field or throw?
</blockquote></details>

the get field or throw method catches the NPE inside it. It’s to avoid keeping a null check everywhere

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39597)* status: Some of the checks are too old.

**Pull request merged**
