### PR TITLE
feat: [PIE-2847]: Fix of rollback not working for stages in parallel

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31016)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31016)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/RollbackOptionalChildChainStep.java, line 105 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl7KEHBCU2VnK_x8s_:-Mwl7KEHBCU2VnK_x8sa:b-u6sicl) ([raw file](https://github.com/harness/harness-core/blob/f7b26c1b1206fa145a6bdcc009e7e6ae199e5725/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/RollbackOptionalChildChainStep.java#L105)):*
> ```Java
>           RollbackTriggeredOutput.builder().rollbackTriggered(true).build(), StepCategory.STAGE.name());
>     }
>     // If status is suspended, then we should mark the execution as success
> ```

add back the comment



_Code quote:_
```Java
// If status is suspended, then we should mark the execution as success
```
___
*[878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java, line 63 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl7wno1g-vWYMVehKj:-Mwl7wno1g-vWYMVehKk:b-y4vo1b) ([raw file](https://github.com/harness/harness-core/blob/1b69833173efe9cc49afd3188c39c026c813b801/878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java#L63)):*
> ```Java
> 
>     optionalSweepingOutput = executionSweepingOutputService.resolveOptional(advisingEvent.getAmbiance(),
>         RefObjectUtils.getSweepingOutputRefObject(YAMLFieldNameConstants.STOP_STAGE_SEQUENCE));
> ```

STOP_STEPS_SEQEUNCE



_Code quote:_
```Java
STOP_STAGE_SEQUENCE
```
___
*[878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java, line 69 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl7sHW1sKHMdvLzv0c:-Mwl7sHW1sKHMdvLzv0d:b-xwd6bz) ([raw file](https://github.com/harness/harness-core/blob/1b69833173efe9cc49afd3188c39c026c813b801/878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java#L69)):*
> ```Java
>             RollbackTriggeredOutput.builder().rollbackTriggered(true).build(), StepCategory.STAGE.name());
>       } catch (Exception e) {
>         log.warn("Ignoring duplicate sweeping output of - " + YAMLFieldNameConstants.USE_ROLLBACK_STRATEGY);
> ```

STOP_STEPS_SEQUENCE



_Code quote:_
```Java
USE_ROLLBACK_STRATEGY
```
___
*[884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl88Yv9KC2a7zs9JJ-:-Mwl88Yv9KC2a7zs9JJ0:b-1tg1ae) ([raw file](https://github.com/harness/harness-core/blob/1b69833173efe9cc49afd3188c39c026c813b801/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L22)):*
> ```Java
>   // NEXT_STEP
>   NEXT_STEP,
>   NEXT_STEP_STAGE_LEVEL,
> ```

rename to NEXT_STAGE



_Code quote:_
```Java
NEXT_STEP_STAGE_LEVEL
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31016)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/RollbackOptionalChildChainStep.java, line 105 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl7KEHBCU2VnK_x8s_:-MwlARtC96m1r-oh7AtM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f7b26c1b1206fa145a6bdcc009e7e6ae199e5725/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/steps/RollbackOptionalChildChainStep.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add back the comment
</blockquote></details>

Done.
___
*[878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java, line 69 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl7sHW1sKHMdvLzv0c:-MwlAWiRB7PJs4ZmXp-_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b69833173efe9cc49afd3188c39c026c813b801/878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

STOP_STEPS_SEQUENCE
</blockquote></details>

Done.
___
*[884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java, line 22 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl88Yv9KC2a7zs9JJ-:-MwlAYUv8ykEMb6IC0Bq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b69833173efe9cc49afd3188c39c026c813b801/884-pms-commons/src/main/java/io/harness/pms/sdk/core/adviser/OrchestrationAdviserTypes.java#L22)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to NEXT_STAGE
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31016)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java, line 63 at r1](https://reviewable.io/reviews/harness/harness-core/31016#-Mwl7wno1g-vWYMVehKj:-MwlBfn15HMBvKfOlM4e:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1b69833173efe9cc49afd3188c39c026c813b801/878-ng-common-utilities/src/main/java/io/harness/advisers/rollback/OnFailRollbackAdviser.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

STOP_STEPS_SEQEUNCE
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31016)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 4 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31016)* status: :shipit: complete! ✓

**Pull request merged**
