### PR TITLE
feat: [PIE-3691]: Give a way to filter pipelines belong to FF

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)

There was a requirement from CF to filter:
- Pipelines containing only one FF Step

This PR adds a new api that would be able to fetch pipelines containing only one FF Step.

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 558 at r3](https://reviewable.io/reviews/harness/harness-core/33621#-N3UOCxuDuu3l3qtNi5B:-N3UOCxuDuu3l3qtNi5C:b-k959xb) ([raw file](https://github.com/harness/harness-core/blob/c2e045c37ee99b765aa9fb260130db77356c7af0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L558)):*
> ```Java
> 
>   @POST
>   @Path("/list/feature-flag")
> ```

camelcase



_Code quote:_
```Java
feature-flag
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 569 at r3](https://reviewable.io/reviews/harness/harness-core/33621#-N3UO9DP5qTKzCl60eHP:-N3UO9DP5qTKzCl60eHQ:bz8c4vf) ([raw file](https://github.com/harness/harness-core/blob/c2e045c37ee99b765aa9fb260130db77356c7af0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L569)):*
> ```Java
>       })
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_VIEW)
>   public ResponseDTO<Page<PMSPipelineSummaryResponseDTO>>
> ```

@hidden annotation needed
___
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/PipelineServiceFilter.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/33621#-N3UObjQ493PB3UB4dM7:-N3UObjQ493PB3UB4dM8:b-pc7kko) ([raw file](https://github.com/harness/harness-core/blob/c2e045c37ee99b765aa9fb260130db77356c7af0/860-orchestration-steps/src/main/java/io/harness/plancreator/PipelineServiceFilter.java#L17)):*
> ```Java
> @Builder
> public class PipelineServiceFilter implements PipelineFilter {
>   public static final String APPROVAL = "approval";
> ```

can be removed

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 558 at r3](https://reviewable.io/reviews/harness/harness-core/33621#-N3UOCxuDuu3l3qtNi5B:-N3XrWPs2IGvuQXoz4UJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2e045c37ee99b765aa9fb260130db77356c7af0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L558)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

camelcase
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 569 at r3](https://reviewable.io/reviews/harness/harness-core/33621#-N3UO9DP5qTKzCl60eHP:-N3XrX43AeMapCz5KQeE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2e045c37ee99b765aa9fb260130db77356c7af0/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L569)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@hidden annotation needed
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`860-orchestration-steps/src/main/java/io/harness/plancreator/PipelineServiceFilter.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/33621#-N3UObjQ493PB3UB4dM7:-N3XrYoW5cbhU64166Iv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2e045c37ee99b765aa9fb260130db77356c7af0/860-orchestration-steps/src/main/java/io/harness/plancreator/PipelineServiceFilter.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can be removed
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)* status: 12 file(s) to review. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 309 at r5](https://reviewable.io/reviews/harness/harness-core/33621#-N3XsE0m0FdaCFbRdjSE:-N3XsE0m0FdaCFbRdjSF:b-depyjq) ([raw file](https://github.com/harness/harness-core/blob/cc573d9939a6bcf5cf0c24754dcdd6ec001e5898/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L309)):*
> ```Java
>     if (EmptyPredicate.isNotEmpty(module)) {
>       // Add approval stage criteria to check for the pipelines containing the given module and the approval stage.
>       Criteria approvalStageCriteria =
> ```

should we rename this to internalModulesCriteria, as both ff and approval would come here

**Review by naidu-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 558 at r6](https://reviewable.io/reviews/harness/harness-core/33621#-N3YvCgQB7zGB3UeT2yl:-N3YvCgQB7zGB3UeT2ym:bfiibkv) ([raw file](https://github.com/harness/harness-core/blob/f652fd7342ea37f14a68c72c14db64ae088bc789/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L558)):*
> ```Java
> 
>   @POST
>   @Path("/list/featureFlag/executionsPage")
> ```

/list/{stageType}/default-pipelines

stageType - ff/approval..etc

Add queryParam to take step count

**Review by archit-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)* status: 19 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 309 at r5](https://reviewable.io/reviews/harness/harness-core/33621#-N3XsE0m0FdaCFbRdjSE:-N3dD3zY4edZxwNzu75k:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/cc573d9939a6bcf5cf0c24754dcdd6ec001e5898/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L309)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should we rename this to internalModulesCriteria, as both ff and approval would come here
</blockquote></details>

done

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621#-:-N3wAgxQDP2wlud028lP:bnfp4nl)* status: 19 file(s) to review.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r4, 10 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)* status: 8 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33621)* status: 7 file(s) to review.

**Pull request merged**
