### PR TITLE
techdebt: [CDS-53907]: disable unwanted long running CG unit tests

### PR DESCRIPTION
**Pull request by shivagowda**
.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44174)

### CODE REVIEW

**Comment by shivagowda** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44174)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Raghav-Murali — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44174)* status: 3 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44174#-:-NOqeKe694t0azYcD_IC:bnfp4nl)* status: 3 file(s) to review.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44174)* status: :shipit: complete! ✓

**Pull request merged**
