### PR TITLE
feat: [PIE-4385]: Support for exclude as per product

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

what was the ask?
In exclude earlier we had to provide each and every combination for exclude. In this PR, we have made a change to provide a subet to exclude as well

Before this change:
strategy:
  matrix:
     os: ["mac", "windows", "linux"]
     browser: ["safari", "chrome", "firefox"]
     exclude:
       - os: "mac"

Before this change, we would not have included any combination because the exclude is not proper but now with this change, we would be excluding all the combinations containing os
Have added a testcase for reference

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35620)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35620)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/test/resources/pipeline-with-wrong-exclude.yaml` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/35620#-N7Zf3gV4WX_NQqkIer3:-N7Zf3gV4WX_NQqkIer4:bghlkv1) ([raw file](https://github.com/harness/harness-core/blob/067fd20e3aac78e672439df5bf31d53eff85a275/878-ng-common-utilities/src/test/resources/pipeline-with-wrong-exclude.yaml#L14)):*
> ```YAML
>         strategy:
>           matrix:
>             a: [ "1","2","3" ]
> ```

add a test case when axis are 3, but subset is of 2

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35620)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35620)* status: :shipit: complete! ✓

**Pull request merged**
