### PR TITLE
[feat]: [CDS-84610]: Integrated Get File with org/project level webhooks

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Integrated the get file flow with org/project level webhooks. Have tested out the following:
1. for project level webhook, fetching and execution of a pipeline, its using the cache.
2. for org level webhook, execution of pipeline to use cache

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java` line 162 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdM1r_-OkAq0eDiYrY:-NjdM1r_-OkAq0eDiYrZ:bkdr5lv) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/GitXWebhookServiceImpl.java#L162)):*
> ```Java
>   @Override
>   public List<GitXWebhook> getGitXWebhookForAllScopes(Scope scope, String repoName) {
>     return gitXWebhookRepository.findByAccountIdentifierAndOrgIdentifierAndProjectIdentifierAndRepoName(
> ```

The method name says that it fetches webhooks for "all scopes" but it does take "scope" as an argument as well. Its confusing, can you please explain.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdMK4PA2OxTdE-wLn1:-NjdMK4PA2OxTdE-wLn2:b-evc7im) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L53)):*
> ```Java
>   }
> 
>   public boolean isBiDirectionalSyncEnabled(Scope fileScope, List<GitXWebhook> gitXWebhookList, String entityFilePath) {
> ```

I think "filepath" can be the argument name instead of "entityFilePath" just for simplicity.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdNxC651kQQI6xAk5k:-NjdNxC651kQQI6xAk5l:b-uxb9x1) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L75)):*
> ```Java
> 
>   private List<GitXWebhook> getWebhooksWithMatchingFolderPaths(
>       List<GitXWebhook> gitXWebhookList, String entityFilePath) {
> ```

"filePath" instead of "entityFilePath"

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdO8h5Db2eg6uY4Zs5:-NjdO8h5Db2eg6uY4Zs6:b-4jfyik) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L81)):*
> ```Java
>         if (isEmpty(gitXWebhook.getFolderPaths())
>             || isNotEmpty(
>                 compareFolderPaths(gitXWebhook.getFolderPaths(), Collections.singletonList(entityFilePath)))) {
> ```

I'm thinking if we should put a default logic inside "compareFolderPaths" which automatically checks if webhook's folder paths are empty, then it returns true. There's no point of putting always an extra check for empty folder paths. This is our default behaviour and should be handled centrally, otherwise we may miss it somewhere.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdOSveDP8ZaWpA6dEs:-NjdOSveDP8ZaWpA6dEt:btq1f71) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L89)):*
> ```Java
>   }
> 
>   public GitXWebhook getClosetGitXWebhookForGivenScope(Scope fileScope, List<GitXWebhook> gitXWebhookList) {
> ```

why is this public?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdOZle3NsVR1XbrQIP:-NjdOZle3NsVR1XbrQIQ:b-gk3r44) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L100)):*
> ```Java
>   }
> 
>   private boolean isMatching(Scope webhookScope, Scope fileScope) {
> ```

method name should be "isMatchingScope" or something similar

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdOZle3NsVR1XbrQIP:-NjdOfqkCLaPdtLnMcrZ:b-hb5ufw) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L100)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

method name should be "isMatchingScope" or something similar
</blockquote></details>

I see there's similar method underneath, but still lets do better naming of this method which represents it logically

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/55576#-NjdP9933TjVNUt9Fs7v:-NjdP9933TjVNUt9Fs7w:b-cyt7w0) ([raw file](https://github.com/harness/harness-core/blob/825225c695358c11486e4e2f38e3e905f2bfed1d/136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/utils/GitXWebhookUtils.java#L101)):*
> ```Java
> 
>   private boolean isMatching(Scope webhookScope, Scope fileScope) {
>     if (isScopeMatching(webhookScope.getProjectIdentifier(), fileScope.getProjectIdentifier())) {
> ```

This logic seems to be wrong. How can we say that a webhook scope matches a file scope if their project identifier matches?

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55576)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
