### PR TITLE
feat: [CDS-38674]: Improving the error message

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34719)

### CODE REVIEW

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34719)* status: 5 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 3007 at r1](https://reviewable.io/reviews/harness/harness-core/34719#-N5_lhr0-wZZpeM8sA-1:-N5_lhr0-wZZpeM8sA-2:b-76mq34) ([raw file](https://github.com/harness/harness-core/blob/5ebc7f84341c8fa5dc4fad69fddc59c101a136d4/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L3007)):*
> ```Java
>             "Deployment rate limit reached. You can deploy only 40% of maximum allowed deployments in a day in an hour. Please try again after some time.";
>       } else {
>         errMsg =
> ```

i will explain why this code is not the best code then we can merge because i think this is what we will have to do for now

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34719)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java` line 3005 at r1](https://reviewable.io/reviews/harness/harness-core/34719#-N5dLODO4VAL9gGOlHs_:-N5dLODO4VAL9gGOlHsa:bwjmgtk) ([raw file](https://github.com/harness/harness-core/blob/5ebc7f84341c8fa5dc4fad69fddc59c101a136d4/400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java#L3005)):*
> ```Java
>       if (e.getErrorType() == ErrorType.SHORT_TERM_DEPLOYMENT_ERROR) {
>         errMsg =
>             "Deployment rate limit reached. You can deploy only 40% of maximum allowed deployments in a day in an hour. Please try again after some time.";
> ```

no need of if else, make msg a bit generic and let error message come from class itself. 

Also null check ?

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34719)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger ft2

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34719)* status: :shipit: complete! ✓

**Pull request merged**
