### PR TITLE
fix: [PL-30907]: added try catch for individual api key migration

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added a try-catch for migration of individual api keys so that failure in migration of one api key does not stop other api key migrations.

Testing:
1. Ran the migration locally, api keys are migrating correctly.
2. Added a failure scenario for one api key -> verified that migration continues for other api keys.
3. Confirmed batch migration is running as expected by using PreQA data with more than 3000 records. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger ut3, ut4, ut6

**Comment by pbarapatre10** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/44813#-NPvWXLS8eD3AeHlPcuB:-NPvWXLS8eD3AeHlPcuC:bxkbt9) ([raw file](https://github.com/harness/harness-core/blob/c130fee4d5180000df21b7967e2d67e380189984/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L60)):*
> ```Java
>         } catch (Exception ex) {
>           log.error("ApiKeyLocalToKMSMigration: Exception occurred while migrating the api key with uuid- {}",
>               record.get("_id"), ex);
> ```

minor: Can this throw an exception?



_Code quote:_
```Java
record.get("_id")
```

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 2 file(s) to review.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 2 file(s) to review.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/44813#-NPvWXLS8eD3AeHlPcuB:-NPvg9q6-MVjME7QtHRM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c130fee4d5180000df21b7967e2d67e380189984/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L60)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: Can this throw an exception?
</blockquote></details>

Done.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/44813#-NPvWXLS8eD3AeHlPcuB:-NPvgCGC1HJRPWlt1yyI:b71jswz) ([raw file](https://github.com/harness/harness-core/blob/c130fee4d5180000df21b7967e2d67e380189984/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L60)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, it can throw an error. Handled it. Please check. Thanks!

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: :shipit: complete! ✓

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44813)* status: :shipit: complete! ✓

**Pull request merged**
