### PR TITLE
fix:[del-5688]: fixing client tools for immutable delegate

### PR DESCRIPTION
**Pull request by bharatgoelharness**
wiki : https://harness.atlassian.net/wiki/spaces/DEL/pages/21241922781/Delegate+3rd+party+tools+version+upgrade+plan
In this Jira we are optimising the client tools to reduce the cve's.
This was tested by CD team and all the sign off detail is mentioned in this channel **#immutable-delegate-signoff** 

Change is only for immutable delegate and we have uploaded the required new binaries in both QA and PROD cdn.

Created 2 docker files
1: docker-immutable-minimal : This is base minimal file which will have delegate jar and scm
2: docker-immutable: This file will have all the other tools. To bake the image from this file we need to pass an extra argument which is the base image tag.

minimal image build:  docker buildx build --push --platform linux/amd64,linux/arm64 --tag ${REPO}.minimal .
maximal image build: docker buildx build --push --platform linux/amd64,linux/arm64 --tag ${REPO} .

Below is the  docker run command output for both image
Screenshot 2023-01-13 at 11 42 46 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42369)

### CODE REVIEW

**Comment by bharatgoelharness** [comment]
@mdmilic I have closed the previous PR due to conflicts.

Please review this and this change is only for immutable delegates

**Review by mdmilic — COMMENTED** [review]
@bharatgoelharness lets not diverge the dockerfiles it will make it harder to maintain. Can you please keep it as one Dockerfile and make the client tool installation conditional (if no args provided we build minimal delegate)? 
You can have a separate installation script for immutable delegates if needed. The alternative approach I can think of is having multi stage build (where minimal and regular delegates can be separate stages in single build file, and full delegate is `FROM minimal` and just adds client tools and envs). 
After you get them built, make sure the image size have not changed significantly. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42369#-:-NLLgK4n8tEIJ1cP-kPv:b-9bb52w)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Comment by bharatgoelharness** [comment]
@mdmilic We wanted to make it these images public after few days. So that customer who want to build their own image can use this.
thats why we are having 2 separate files, so that if customer can bake image as per their requirement. They will be having full control over it.

Multistage we can try out but having conditional statement will increase the complexity.

**Comment by bharatgoelharness** [comment]
@mdmilic 
I think we can't use multi stage also as we need to images (with tools and without tools). Customer can use anyone of them. 
What I got to know from multi stage doc that it will give you one image tag finally. Other images will be in cache only.

**Comment by mdmilic** [comment]
> We wanted to make it these images public after few days
I still think we should have a single Dockerfile, but this is why I mentioned that minimal delegate is the default option (because most customers customize minimal delegate and they don't need to do anything special to build it). They are still in full control and the build arg is even self explanatory, so anyone building images would not have hard time understanding this. In my opinion having multiple Dockerfiles is both more confusing for users and harder to maintain for us. 

> @mdmilic I think we can't use multi stage also as we need to images (with tools and without tools). Customer can use anyone of them. What I got to know from multi stage doc that it will give you one image tag finally. Other images will be in cache only.

You would just build it twice the same way as today or if having multiple Dockerfiles. This is [example](https://stackoverflow.com/a/60820156) of conditional multistage I'm referring to. 

BTW, I would love if our build flag is called minimal = true|false, but changing flag name is backwards incompatible change and we would have to support both flags.

**Comment by bharatgoelharness** [comment]
> > We wanted to make it these images public after few days
> > I still think we should have a single Dockerfile, but this is why I mentioned that minimal delegate is the default option (because most customers customize minimal delegate and they don't need to do anything special to build it). They are still in full control and the build arg is even self explanatory, so anyone building images would not have hard time understanding this. In my opinion having multiple Dockerfiles is both more confusing for users and harder to maintain for us.
> 
> > @mdmilic I think we can't use multi stage also as we need to images (with tools and without tools). Customer can use anyone of them. What I got to know from multi stage doc that it will give you one image tag finally. Other images will be in cache only.
> 
> You would just build it twice the same way as today or if having multiple Dockerfiles. This is [example](https://stackoverflow.com/a/60820156) of conditional multistage I'm referring to.
> 
> BTW, I would love if our build flag is called minimal = true|false, but changing flag name is backwards incompatible change and we would have to support both flags.

Still this will give you one final image at a time. We would have to build it 2 times.
We have only 1 dependency that is minimal image is base image for image with tools.
Build stage is useful when we have multiple dependency.

**Comment by bharatgoelharness** [comment]
@raghuAtWings @mdmilic Please review this. We wanted to merge it before next branch cut 783xx.

**Comment by bharatgoelharness** [comment]
@mdmilic 
Regarding ARG TARGETARCH, this will take current system arch if not being passed.

Regarding SCM, this is required for CD task.

**Comment by mdmilic** [comment]
> @mdmilic Regarding ARG TARGETARCH, this will take current system arch if not being passed.
I know, but I think it's better to be explicit here. It can lead to some really hard to debug issues otherwise (because it's different behavior on different hosts). If you think this is what we actually want, then I'm fine. 
> Regarding SCM, this is required for CD task.
All tools are needed by some CD tasks :) minimal image should have only executables/deps/libraries that are needed for core delegate operation (i.e. for absolutely every task), so no SCM by default. Also, it didn't have it so far.

**Comment by bharatgoelharness** [comment]
My bad this SCM change came from CI team. If customer is using minimal image for CI task then we didn't had the scm tool for CI task. AFAIK for each CI task SCM is mandatory.

I can add default ARCH and we should add this in doc also that we support linux/amd64 and linux/arm64 as of now.

**Comment by mdmilic** [comment]
> My bad this SCM change came from CI team. If customer is using minimal image for CI task then we didn't had the scm tool for CI task. AFAIK for each CI task SCM is mandatory. https://harness.atlassian.net/browse/CI-6195
> 
> I can add default ARCH and we should add this in doc also that we support linux/amd64 and linux/arm64 as of now.

I assumed it was probably for CI, but still not all our customers are CI, why would we force SCM on CD only customers.

**Comment by mdmilic** [comment]
> > My bad this SCM change came from CI team. If customer is using minimal image for CI task then we didn't had the scm tool for CI task. AFAIK for each CI task SCM is mandatory. https://harness.atlassian.net/browse/CI-6195
> > I can add default ARCH and we should add this in doc also that we support linux/amd64 and linux/arm64 as of now.
> 
> I assumed it was probably for CI, but still not all our customers are CI, why would we force SCM on CD only customers.

You could say tomorrow that every STO task needs snyk or some other tool, so we just bake it in minimal image. That goes against what minimal image is supposed to be. Minimal image is a starting point for you to customize delegate and manage your own tools, so I'm strongly against baking SCM or anything else into it.

**Comment by bharatgoelharness** [comment]
@mdmilic added the default arch also

**Review by bharatgoelharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42369)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`dockerization/delegate/Dockerfile-minimal` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42369#-NLuOfe26JwmMWULKt06:-NM1wXLt2EjxXT2Up3eq:bbwr5o3) ([raw file](https://github.com/harness/harness-core/blob/6461e50ef65975a9d0f90ba190cf510b222c1a18/dockerization/delegate/Dockerfile-minimal#L29)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Why do we need SCM in the minimal image?
</blockquote></details>

This is the requirement.

**Comment by bharatgoelharness** [comment]
@mdmilic @raghuAtWings Please approve this.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42369)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
