### PR TITLE
[feat]: [PL-30518]: add access control checks for incoming SCIM API c…

### PR DESCRIPTION
**Pull request by pbarapatre10**
[feat]: [PL-30518]: add access control checks for incoming SCIM API calls in NG

## Describe your changes
Issue:
- Currently the NG SCIM APIs are not adhering to any RBAC checks, even though through SCIM APIs we are able to do CRUD operations on User & Group.
- This was found during JPMC SCIM enhancements when they specifically wanted to assign roles to ServiceAccount token keys separately for User CRUD.

Fix made:
- Since the feature might break existing other customers who might not be using a privileged RBAC API token, we first introduced logs to check in how many accounts/cases this RBAC violation was happening in prod
- We found that there is only one account (which is also Harness internal account), where the API token is violating the required RBAC checks. Captured the data points in this ticket: https://harness.atlassian.net/browse/PL-30846 
- We are going ahead to add the RBAC in the NG SCIM User/Group resources going ahead. We are adding a FF to be even safe guarded in case any customer reports of violation and we can disable the FF for them.
- Unit tests are not added as it is resource level changes and the relevant RBAC methods for applying access control checks are already tested aprior with UnitTests

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PL-30518]: https://harness.atlassian.net/browse/PL-30518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43856)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/43856#-NOJUm5n32K8Eflws5dS:-NOJUm5n32K8Eflws5dT:bjhk9mw) ([raw file](https://github.com/harness/harness-core/blob/d75be62d2a71956eb81cfdfc8ae7711aecb20bc0/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L172)):*
> ```Java
>             Resource.of(USERGROUP, groupIdentifier), MANAGE_USERGROUP_PERMISSION)) {
>       throw new AccessDeniedException(
>           String.format("Token needs to have %s permission on account: %s to perform SCIM UserGroup action",
> ```

Small observation.
This string repeats in every method.
Can we use a final static String instead of repeating the same message?

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java` line 251 at r3](https://reviewable.io/reviews/harness/harness-core/43856#-NOJV9mN5nDfZCevdaoO:-NOJV9mN5nDfZCevdaoP:b8wravw) ([raw file](https://github.com/harness/harness-core/blob/d75be62d2a71956eb81cfdfc8ae7711aecb20bc0/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java#L251)):*
> ```Java
>             Resource.of(USER, userIdentifier), MANAGE_USER_PERMISSION)) {
>       throw new AccessDeniedException(
>           String.format("Token needs to have %s permission on account: %s to perform SCIM user action",
> ```

Small observation.
This string repeats in every method.
Can we use a constant string instead of repeating the same message?



_Code quote:_
```Java
Token needs to have %s permission on account: %s to perform SCIM user actio
```

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43856)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/43856#-NOJUm5n32K8Eflws5dS:-NOJaaU30AvDlqtj_t1X:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/d75be62d2a71956eb81cfdfc8ae7711aecb20bc0/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimGroupResource.java#L172)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Small observation.
This string repeats in every method.
Can we use a final static String instead of repeating the same message?

</blockquote></details>

LGTM

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java` line 251 at r3](https://reviewable.io/reviews/harness/harness-core/43856#-NOJV9mN5nDfZCevdaoO:-NOJaenR67jRetjCW7C9:bb6ywmx) ([raw file](https://github.com/harness/harness-core/blob/d75be62d2a71956eb81cfdfc8ae7711aecb20bc0/120-ng-manager/src/main/java/io/harness/ng/scim/resource/NGScimUserResource.java#L251)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Small observation.
This string repeats in every method.
Can we use a constant string instead of repeating the same message?

</blockquote></details>

LGTM

**Review by shashank-harness — APPROVED** [review]
LGTM

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43856#-:-NOJahFV4fQ6OfmfhQqL:bb6ywmx)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43856)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43856)* status: :shipit: complete! ✓

**Pull request merged**
