### PR TITLE
fix: [PIE-3156]: Updating graph outcomes for intervention waiting status a…

### PR DESCRIPTION
**Pull request by archit-harness**
…s well

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31656)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31656)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java, line 91 at r1](https://reviewable.io/reviews/harness/harness-core/31656#-Myl_k-MDVuS0sWav2L6:-Myl_k-MDVuS0sWav2L7:b-e75od4) ([raw file](https://github.com/harness/harness-core/blob/318af9de3e463192166ada2ccb0b2511cbcbe47d/860-orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java#L91)):*
> ```Java
>     graphVertexMap.computeIfPresent(nodeExecutionId, (key, prevValue) -> {
>       GraphVertex newValue = convertFromNodeExecution(prevValue, nodeExecution);
>       if (StatusUtils.isOutcomeUpdateGraphStatus(newValue.getStatus())) {
> ```

add one more condition here or create a utility here
___
*[884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java, line 186 at r1](https://reviewable.io/reviews/harness/harness-core/31656#-Myl_go_9QL_Z9b8kcvo:-Myl_go_9QL_Z9b8kcvp:bp23t91) ([raw file](https://github.com/harness/harness-core/blob/318af9de3e463192166ada2ccb0b2511cbcbe47d/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L186)):*
> ```Java
>   }
> 
>   public boolean isOutcomeUpdateGraphStatus(Status status) {
> ```

do not put this method here @archit-harness . This is in a lower module it has no idea what graph is

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31656)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java, line 91 at r1](https://reviewable.io/reviews/harness/harness-core/31656#-Myl_k-MDVuS0sWav2L6:-Myld5j97MAYUiej4bmZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/318af9de3e463192166ada2ccb0b2511cbcbe47d/860-orchestration-visualization/src/main/java/io/harness/event/GraphStatusUpdateHelper.java#L91)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

add one more condition here or create a utility here
</blockquote></details>

Done.
___
*[884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java, line 186 at r1](https://reviewable.io/reviews/harness/harness-core/31656#-Myl_go_9QL_Z9b8kcvo:-Myld7EpCbc6KZwI-x9A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/318af9de3e463192166ada2ccb0b2511cbcbe47d/884-pms-commons/src/main/java/io/harness/pms/execution/utils/StatusUtils.java#L186)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

do not put this method here @archit-harness . This is in a lower module it has no idea what graph is
</blockquote></details>

Done.

**Review by hextechpal — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31656)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — DISMISSED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31656)* status: 2 file(s) to review.

**Pull request merged**
