### PR TITLE
fix: [CDS-51943]: NG- ClassCastException on pipeline when connector specified for infra is wrong

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
Did log changes for k8s infras. When class cast exception is thrown we will log more detailed error to help the user 

## Testing
Screenshot 2023-01-31 at 4 20 34 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/43283#-NN6NsV82VKu-Gz81ZN1:-NN6NsV93Jtoa9Yc5JhD:bgzycgk) ([raw file](https://github.com/harness/harness-core/blob/938b6fc592a91163dacda215f6021132f81a321f/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java#L199)):*
> ```Java
>     } catch (ClassCastException ex) {
>       if (infrastructure.getKind().equals(KUBERNETES_DIRECT)) {
>         throw new ClassCastException(String.format(CLASS_CAST_EXCEPTION_ERROR, infrastructure.getKind(),
> ```

We should use InvalidArgumentsException(Pair.of("connectorRef", ...)) instead

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/43283#-NN6NsV82VKu-Gz81ZN1:-NN6b63MCYG3O643cYG3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/938b6fc592a91163dacda215f6021132f81a321f/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java#L199)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We should use InvalidArgumentsException(Pair.of("connectorRef", ...)) instead
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/43283#-NN6jdSm46uuSWcLxIeA:-NN6jdSm46uuSWcLxIeB:b-7ubxxi) ([raw file](https://github.com/harness/harness-core/blob/7a52c286d1b0322a7bf8ff7af079b534a761ec3f/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java#L200)):*
> ```Java
>       }
>     } catch (ClassCastException ex) {
>       if (infrastructure.getKind().equals(KUBERNETES_DIRECT)) {
> ```

repetitive code. refactor to:



_Code snippet:_
```Java
if (Set.of(KUBERNETES_DIRECT, KUBERNETES_GCP, KUBERNETES_AZURE).contains(infrastructure.getKind()) ) {
  String requiredConnectorType = getRequiredConnectorType(infrastructure.getKind());
  throw new InvalidArgumentsException(Pair.of("connectorRef",
    String.format(CLASS_CAST_EXCEPTION_ERROR, infrastructure.getKind(), connectorDTO.getConnectorType(), requiredConnectorType)));
}

throw ex;
```

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/43283#-NN6jdSm46uuSWcLxIeA:-NN6sRqrDNZINArnwZIC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a52c286d1b0322a7bf8ff7af079b534a761ec3f/127-cd-nextgen-entities/src/main/java/io/harness/cdng/k8s/K8sEntityHelper.java#L200)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

repetitive code. refactor to:
</blockquote></details>

Done.

**Review by TarunUba1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283#-:-NN6sYvr9zXAItqtGQIE:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by TarunUba1** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43283)* status: :shipit: complete! ✓

**Pull request merged**
