### PR TITLE
[feat]: [PL-41296]: add ScopeFilter to process account, org, project identifiers to get ScopeInfo

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Add a filter to deduce the ScopeInfo and populate in Context. The ScopeInfo can then be consumed at resource layers instead of user specified identifiers, to perform operations. 

Testing scenario:
- Tested in few resource layer and context is getting populated and can be extracted at resource layer

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 284 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFttJQEDCQYYRKd5hn:-NjFttJQEDCQYYRKd5ho:b-e8k2e) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L284)):*
> ```Java
>           NGResourceFilterConstants.SEARCH_TERM_KEY) String searchTerm,
>       @QueryParam("filterType") @DefaultValue("EXCLUDE_INHERITED_GROUPS") UserGroupFilterType filterType,
>       @BeanParam PageRequest pageRequest, @Context ScopeInfo scopeInfo) {
> ```

Change in this file is for testing?
___
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFvM6Y2AF5q5Y8JscZ:-NjFvM6Y2AF5q5Y8Jsc_:bwjioec) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L37)):*
> ```Java
> @OwnedBy(PL)
> @Singleton
> @Priority(6000)
> ```

What does 6000 mean?
___
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFuExZ8cy_3gYm_xaC:-NjFuExZ8cy_3gYm_xaD:b-9vv6ij) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L40)):*
> ```Java
> @Slf4j
> @Provider
> public class ScopeInfoFilter implements ContainerRequestFilter {
> ```

Any reason to put this in 965-api-key-filter?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG2ggzC_-Mo3ebbCf2:-NjG2ggzC_-Mo3ebbCf3:b-b1wisk) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L51)):*
> ```Java
>   public void filter(ContainerRequestContext requestContext) {
>     Object requestCtxObject = requestContext.getProperty(SCOPE_INFO_CONTEXT_PROPERTY);
>     if (requestCtxObject instanceof ScopeInfo) {
> ```

Why this check?
___
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG3jMt3cVumClf3xJI:-NjG3jMt3cVumClf3xJJ:b-yqz0ny) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L64)):*
> ```Java
>     }
> 
>     if (!isInternalRequest(resourceInfo)) {
> ```

Any reason to skip Internal APIs?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG4Se8-Rw9_AstYAd9:-NjG4Se8-Rw9_AstYAdA:bwviikb) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L61)):*
> ```Java
>     Optional<String> accountIdentifierOptional = getAccountIdentifierFrom(requestContext);
>     if (accountIdentifierOptional.isEmpty() || accountIdentifierOptional.get().isEmpty()) {
>       return;
> ```

How will application behave if we return from here without resolving ScopeInfo?
___
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG4blF22hWZMmhXiqE:-NjG4blF22hWZMmhXiqF:b-6myucu) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L88)):*
> ```Java
> 
>   private Optional<String> getAccountIdentifierFrom(ContainerRequestContext containerRequestContext) {
>     String accountIdentifier = containerRequestContext.getHeaderString(ACCOUNT_HEADER);
> ```

How will accountId, orgId and projectId be available in header?

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFvM6Y2AF5q5Y8JscZ:-NjGHRgACBUoDBRaBcLL:bvmg96o) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L37)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What does 6000 mean?
</blockquote></details>

This is the priority of the filter. Till 5000 prioirties are defined in Javax (USER==5000), after every filter we want to apply this filter, so added the priority of 6000 to it, thanks

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG4Se8-Rw9_AstYAd9:-NjGHubx2-RVsMQalqXk:b3hzaat) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L61)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How will application behave if we return from here without resolving ScopeInfo?
</blockquote></details>

Client will continue to behave as is, but will not be able to leverage the resolved ScopeInfo.

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG3jMt3cVumClf3xJI:-NjGIJ0I3nGwjG4BCxj3:bhqpniu) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L64)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to skip Internal APIs?
</blockquote></details>

This is required as we are calling the ScopeResource, so we need to escape it. One other way is to annotate the Scope resource specially with a new Annotation and then we can just skip for the ScopeResource and internal requests would also be validated through this filter.

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG4blF22hWZMmhXiqE:-NjGJC2m5nJB3kk5TkeQ:b-ze48c3) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L88)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How will accountId, orgId and projectId be available in header?
</blockquote></details>

Only account can be present in Header, there are APIs which sends account data in Header, thanks

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 284 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFttJQEDCQYYRKd5hn:-NjGJX00EaGdVjpfOp5H:b-y4sjli) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L284)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Change in this file is for testing?
</blockquote></details>

Yes, used it for testing, will remove, thanks

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFvM6Y2AF5q5Y8JscZ:-NjMqJyfCZqZIDlKmp5r:bs6uixk) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L37)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

This is the priority of the filter. Till 5000 prioirties are defined in Javax (USER==5000), after every filter we want to apply this filter, so added the priority of 6000 to it, thanks
</blockquote></details>

Updated the priority to User level only, thanks

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFuExZ8cy_3gYm_xaC:-NjMqO1LDbgiUQG1V-8z:b920lwy) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L40)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to put this in 965-api-key-filter?
</blockquote></details>

renamed the module to `ng-filter`, thanks

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjG2ggzC_-Mo3ebbCf2:-NjMqSxM3s9fObnf_DLk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/965-api-key-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L51)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this check?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 284 at r2](https://reviewable.io/reviews/harness/harness-core/55152#-NjFttJQEDCQYYRKd5hn:-NjMqbzrDJphYQ1C4SHh:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee4d94a2490120c5515df46a9d2676d5ee6508bb/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L284)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Yes, used it for testing, will remove, thanks
</blockquote></details>

Done

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 24 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 36 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`.aeriform/BUILD.bazel` line 446 at r3](https://reviewable.io/reviews/harness/harness-core/55152#-NjNBe679HGu3Ehcp-dF:-NjNBe679HGu3Ehcp-dG:b-f1ee75) ([raw file](https://github.com/harness/harness-core/blob/5fe1b30b2aa214d2096c46ce824384a99e94b490/.aeriform/BUILD.bazel#L446)):*
> ```Starlark
> aeriform("//965-ng-filter:module")
> 
> aeriform("//965-api-key-filter:tests")
> ```

Should we change this as well?
___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/55152#-NjNCKsbA3ebfUpae5RY:-NjNCKsbA3ebfUpae5RZ:bva7009) ([raw file](https://github.com/harness/harness-core/blob/5fe1b30b2aa214d2096c46ce824384a99e94b490/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L133)):*
> ```Java
>   private boolean isScopeInfoResolutionExemptedRequest(
>       ResourceInfo requestResourceInfo, ContainerRequestContext requestContext) {
>     return (requestResourceInfo.getResourceMethod().getAnnotation(InternalApi.class) != null
> ```

Should we not remove checks for InternalAPI?

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 16 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 40 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): build-engineering.

**Comment by pbarapatre10** [comment]
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/55152#-NjNCKsbA3ebfUpae5RY:-NjQqta_1Jp5R9x72cu3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5fe1b30b2aa214d2096c46ce824384a99e94b490/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L133)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we not remove checks for InternalAPI?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`.aeriform/BUILD.bazel` line 446 at r3](https://reviewable.io/reviews/harness/harness-core/55152#-NjNBe679HGu3Ehcp-dF:-NjQqw-HEegMk8EYCaA7:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5fe1b30b2aa214d2096c46ce824384a99e94b490/.aeriform/BUILD.bazel#L446)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we change this as well?
</blockquote></details>

done

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 40 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): build-engineering.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152)* status: 40 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): build-engineering.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55152#-:-NjQwSkP5DZh4G15634W:bnfp4nl)* status: 40 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): build-engineering.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Pull request merged**
