### PR TITLE
fix: [CDP-20230]: Fix S3 deployment

### PR DESCRIPTION
**Pull request by jelenaHarness**
Add S3 and Azure artifacts to metadata-only artifact types.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30269)

### CODE REVIEW

**Comment by jelenaHarness** [comment]
trigger messagecheck

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/azure/AzureVMSSStateHelper.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30269#-MuPtC6T897s_oGOJzXd:-MuPtC6T897s_oGOJzXe:b-t2u7u4) ([raw file](https://github.com/harness/harness-core/blob/ab9b37f7da335b5d4ffaf9c9b8a78e5adeaf2046/400-rest/src/main/java/software/wings/sm/states/azure/AzureVMSSStateHelper.java#L125)):*
> ```Java
>   protected static final List<String> METADATA_ONLY_ARTIFACT_STREAM_TYPES =
>       Arrays.asList("JENKINS", "BAMBOO", "ARTIFACTORY", "NEXUS", "AMAZON_S3", "AZURE_ARTIFACTS");
> ```

Instead of hard coding this list as String, should not we use enum list of ArtifactStreamType ?

**Review by jelenaHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/azure/AzureVMSSStateHelper.java, line 125 at r1](https://reviewable.io/reviews/harness/harness-core/30269#-MuPtC6T897s_oGOJzXd:-MuQE-jv9JWW3usRXzJ1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ab9b37f7da335b5d4ffaf9c9b8a78e5adeaf2046/400-rest/src/main/java/software/wings/sm/states/azure/AzureVMSSStateHelper.java#L125)):*
<details><summary><i>Previously, anilchowdhury-harness (Anil Chowdhury) wrote…</i></summary><blockquote>

Instead of hard coding this list as String, should not we use enum list of ArtifactStreamType ?
</blockquote></details>

Done.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269#-:-MuQOB-NCKvSl1RWsqt7:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269#-:-MuQObhxAlx2sHHFgMfK:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269#-:-MulEv5hDt3rm81f05jQ:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269#-:-MuoeGvN9xEuAz0dG30c:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30269)* status: :shipit: complete! ✓

**Pull request merged**
