### PR TITLE
[fix]: [PIE-7657]: Adding fix for authentication issue with Queue Service

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes

Added fix for queue Service Auth From Partner Services.
Added Extra logs in hsqs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 27 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — DISMISSED** [review]
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 24 of 27 files at r1, 1 of 1 files at r3, 2 of 5 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 5 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: :shipit: complete! ✓

**Comment by ankittiwari-harness** [comment]
trigger tin0, tin1, tin4, ti2

**Comment by ankittiwari-harness** [comment]
trigger tin4

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by ankittiwari-harness** [comment]
trigger tin0

**Comment by ankittiwari-harness** [comment]
trigger smartchecks

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: 4 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 27 files at r1, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42667)* status: :shipit: complete! ✓

**Pull request merged**
