### PR TITLE
fix: [PL-38813]: Delegate token name unique across within CG and NG

### PR DESCRIPTION
**Pull request by jennyjames21**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49636)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
Update the PR description and testing done

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49636#-:-NYbx4bXAIKqGPK7zmgQ:blf5c4c)* status: 7 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 1047 at r1](https://reviewable.io/reviews/harness/harness-core/49636#-NYbuUvRClwgAI8-iNnt:-NYbuUvS5EkpujZwf-Ug:bnalysj) ([raw file](https://github.com/harness/harness-core/blob/dea9a1bb74359638e1d0911d38d1b5b25347ed34/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L1047)):*
> ```Java
>                                              .in(tokensNameList)
>                                              .field(DelegateTokenKeys.isNg)
>                                              .equal(false)
> ```

Is this CG specific? How does it work for NG
___
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/49636#-NYbx-Ps-vQUv0K8Hu39:-NYbx-Ps-vQUv0K8Hu3A:b-g5j2a0) ([raw file](https://github.com/harness/harness-core/blob/dea9a1bb74359638e1d0911d38d1b5b25347ed34/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L56)):*
> ```Java
>                  .field(DelegateTokenKeys.name)
>                  .unique(true)
>                  .name("byAccountAndName")
> ```

Is the old (prefix) index still needed? We should probably use the NG flag in all queries now?
Is it possible to update the existing index or should we remove it?

**Comment by jennyjames21** [comment]
*[`920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/49636#-NYbx-Ps-vQUv0K8Hu39:-NYdnLBr3PuAd9HtTcdq:b-i5rg7v) ([raw file](https://github.com/harness/harness-core/blob/dea9a1bb74359638e1d0911d38d1b5b25347ed34/920-delegate-service-beans/src/main/java/io/harness/delegate/beans/DelegateToken.java#L56)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Is the old (prefix) index still needed? We should probably use the NG flag in all queries now?
Is it possible to update the existing index or should we remove it?
</blockquote></details>

In the past, i seen DBAs asking to create a new one instead of updating. We can't delete it immediately but will do on the next releases

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 1047 at r1](https://reviewable.io/reviews/harness/harness-core/49636#-NYbuUvRClwgAI8-iNnt:-NYdo4AR6--wwpcHPd_f:btey4rc) ([raw file](https://github.com/harness/harness-core/blob/dea9a1bb74359638e1d0911d38d1b5b25347ed34/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L1047)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Is this CG specific? How does it work for NG
</blockquote></details>

this is wrong, i will update

**Comment by jennyjames21** [comment]
added more files, still in the process of testing.

It's a tricky one so please re-review after one round of testing

**Pull request closed without merging**
