### PR TITLE
feat: [PLG-1966]: Create schema for ModuleLicenses in TimeScaleDB and add POJOs using jOOQ

### PR DESCRIPTION
**Pull request by neelam-harness**
## Describe your changes
1. Created schema for module-licenses table in TimescaleDB
2. Generated the pojos using the jooq plugin
3. Added an OwnerRule
4. Tested the Table creation in TimescaleDB locally
Screen Shot 2023-02-07 at 1 57 13 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/43645#-NNi--TW0vhSX57qdwZk:-NNi--TW0vhSX57qdwZl:b8xbdoa) ([raw file](https://github.com/harness/harness-core/blob/85ddb616bf745c156d53e3509d7a4f8cd746ccb2/120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java#L20)):*
> ```Java
>     @Override
>     public String getFileName() {
>         return "timescale/create_plg_licenses_utilization.sql";
> ```

Can we create a constant instead of hardcoding value ?

**Review by ivan-83 — DISMISSED** [review]
LGTM with minor comments

> Reviewed 10 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645#-:-NNkBV0N75HlraoeIaR0:b-z5hs9a)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/43645#-NNkA8x99f7csoMINLan:-NNkA8xA90U4V7aJvAo2:b-pkicwv) ([raw file](https://github.com/harness/harness-core/blob/e195d5540ab13314646da2cfaf66e0879789d4fc/120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java#L17)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PLG)
> public class CreatePLGLicensesUtilizationTable extends NGAbstractTimeScaleMigration {
> ```

Minor - rename CreatePLGLicensesUtilizationTable to CreateModuleLicensesTable



_Code quote:_
```Java
NGAbstractTimeScaleMigration
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/43645#-NNkAS0Q7jYA7x10Kbmq:-NNkAS0Q7jYA7x10Kbmr:b-65h6bh) ([raw file](https://github.com/harness/harness-core/blob/e195d5540ab13314646da2cfaf66e0879789d4fc/120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java#L20)):*
> ```Java
>     @Override
>     public String getFileName() {
>         return "timescale/create_plg_licenses_utilization.sql";
> ```

Minor - rename timescale/create_plg_licenses_utilization.sql to timescale/create_module_licenses_table.sql

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: :shipit: complete! ✓

**Review by neelam-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/43645#-NNi--TW0vhSX57qdwZk:-NNm_hyI9xwaKHRfam3-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85ddb616bf745c156d53e3509d7a4f8cd746ccb2/120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/CreatePLGLicensesUtilizationTable.java#L20)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Can we create a constant instead of hardcoding value ?
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645#-:-NNnBRzdCVaUf6OFrSG2:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by neelam-harness** [comment]
trigger ti0

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 4 of 10 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by neelam-harness** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Comment by neelam-harness** [comment]
trigger ti1

**Comment by neelam-harness** [comment]
trigger ti1

**Comment by neelam-harness** [comment]
trigger messagecheck, checkstylecodeformat

**Comment by neelam-harness** [comment]
trigger messagecheck

**Comment by neelam-harness** [comment]
trigger checkstylecodeformat

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: Some of the checks are too old. 1 of 2 approvals obtained.

**Comment by neelam-harness** [comment]
trigger checkstylecodeformat

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: :shipit: complete! ✓

**Comment by neelam-harness** [comment]
trigger ti3

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645#-:-NOqMFf81-iyOBxv9QS-:bnfp4nl)* status: 1 of 2 approvals obtained.

**Comment by neelam-harness** [comment]
trigger ti3

**Review by pranil-harness — APPROVED** [review]

**Review by neelam-harness — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, 6 of 6 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43645)* status: 1 of 2 approvals obtained.

**Pull request merged**
