### PR TITLE
[feat]: [PL-21921]: Support AWS IAM for Hashicorp Vault in NG

### PR DESCRIPTION
**Pull request by shashank-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)

### CODE REVIEW

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/secretsmanagement/SecretManagerResourceNG.java, line 62 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb7_Uq7psNm1DhcRxG:-Mvb7_Uq7psNm1DhcRxH:b-6ruva8) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/400-rest/src/main/java/software/wings/resources/secretsmanagement/SecretManagerResourceNG.java#L62)):*
> ```Java
>   @Produces("application/json")
>   @Consumes("application/json")
>   @Deprecated
> ```

If we are making it deprecated , Should we hide it as well?

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 21 files at r1, 7 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java, line 82 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb7Na6BlITxl_WyWum:-Mvb7Na6BlITxl_WyWun:bg7k9im) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java#L82)):*
> ```Java
>   public void handle(VaultConnector vaultConnector) {
>     log.info("renewing client tokens for {}", vaultConnector.getUuid());
>     if (vaultConnector.isUseVaultAgent() || vaultConnector.getUseAwsIam()) {
> ```

Separate out a method - isRenewalNeeded in Vault connector itself and use it.
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 283 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb87mH4AAboimtjoLc:-Mvb87mH4AAboimtjoLd:bm8wn3d) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L283)):*
> ```Java
>   public void processAppRole(ConnectorDTO connectorDTO, ConnectorConfigDTO existingConnectorConfigDTO,
>       String accountIdentifier, boolean create) {
>     if (ConnectorType.VAULT == connectorDTO.getConnectorInfo().getConnectorType()) {
> ```

Null check for getConnectorInfo()
___
*[890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java, line 83 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb9xhy-QIf_TY-clP4:-Mvb9xhy-QIf_TY-clP5:b-hyliyx) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java#L83)):*
> ```Java
>   public static VaultAppRoleLoginResult getVaultAwmIamAuthLoginResult(BaseVaultConfig vaultConfig) {
>     try {
>       VaultSysAuthRestClient restClient =
> ```

Validate vaultConfig before using it.
___
*[890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java, line 165 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb9ly9-je0jGsc3SJC:-Mvb9ly9-je0jGsc3SJD:b-8eac87) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java#L165)):*
> ```Java
>   String getBase64EncodedRequestHeaders(BaseVaultConfig vaultConfig) throws URISyntaxException {
>     final LinkedHashMap<String, String> headers = new LinkedHashMap<>();
>     headers.put("X-Vault-AWS-IAM-Server-ID", vaultConfig.getXVaultAwsIamServerId());
> ```

Extract out constants

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 8 of 21 files at r1, 8 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)* status: 27 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
___
*[120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java, line 82 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb7Na6BlITxl_WyWum:-Mvc5VbQBPoTqTBAknOK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java#L82)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Separate out a method - isRenewalNeeded in Vault connector itself and use it.
</blockquote></details>

Done.

**Comment by shashank-harness** [comment]
___
*[440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java, line 283 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb87mH4AAboimtjoLc:-MvcIVye-WN0e8hvdiib:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/440-connector-nextgen/src/main/java/io/harness/connector/impl/NGVaultServiceImpl.java#L283)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Null check for getConnectorInfo()
</blockquote></details>

Done.

**Comment by shashank-harness** [comment]
___
*[890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java, line 83 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb9xhy-QIf_TY-clP4:-MvcIYJb8jSiN1c4KHp9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java#L83)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Validate vaultConfig before using it.
</blockquote></details>

Done.

**Comment by shashank-harness** [comment]
___
*[890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java, line 165 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb9ly9-je0jGsc3SJC:-MvcI_y7Bbmq8eebiCZx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/890-sm-core/src/main/java/io/harness/helpers/NGVaultTaskHelper.java#L165)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Extract out constants
</blockquote></details>

Done.

**Comment by shashank-harness** [comment]
___
*[400-rest/src/main/java/software/wings/resources/secretsmanagement/SecretManagerResourceNG.java, line 62 at r2](https://reviewable.io/reviews/harness/harness-core/30512#-Mvb7_Uq7psNm1DhcRxG:-MvcIjWiCBrfIFf-hzWm:bpyw7ws) ([raw file](https://github.com/harness/harness-core/blob/09501591d104e14ed7b43fb8c152ec5dd9b7f16b/400-rest/src/main/java/software/wings/resources/secretsmanagement/SecretManagerResourceNG.java#L62)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

If we are making it deprecated , Should we hide it as well?
</blockquote></details>

This is unrelated change. Have reverted it and will take care of it as part of a separate jira.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 70 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)* status: 88 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> Reviewed 60 of 70 files at r3, 6 of 9 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)* status: 88 file(s) to review. 1 of 2 approvals obtained.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 7 of 21 files at r1, 4 of 15 files at r2, 62 of 70 files at r3, 3 of 9 files at r4, 5 of 8 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512#-:-MvlU5zo2HfDqzxRMYd4:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)* status: 4 file(s) to review.

**Comment by piyush-harness** [comment]
:lgtm:

**Comment by piyush-harness** [comment]
:lgtm:

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 7 of 21 files at r1, 4 of 15 files at r2, 62 of 70 files at r3, 3 of 9 files at r4, 5 of 8 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30512)* status: 4 file(s) to review.

**Pull request merged**
