### PR TITLE
feat: [CDS-48517]: Manager changes: K8s & Native Helm (CG - Direct Kubernetes Cluster) Instance sync V2 implementation Revisit

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
Manager side Changes for Instance sync V2, Behind FF INSTANCE_SYNC_V2_CG

## Checklist
- No documentation require.
- I've tested this change either in PR or local environment.
- These changes are behind FF 

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)

### CODE REVIEW

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 1 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)* status: 34 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 119 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOY8ibDG0oWX8VG9Yv:-NKOY8ibDG0oWX8VG9Yw:b5w1bjy) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L119)):*
> ```Java
>       }
> 
>       deploymentSummaries = deploymentSummaries.stream().filter(this::hasDeploymentKey).collect(Collectors.toList());
> ```

Is this filter and 
      event.getDeploymentSummaries()
          .stream()
          .filter(deployment -> Objects.nonNull(deployment.getDeploymentInfo()))
          .filter(this::hasDeploymentKey)
different? Why is this? What is the actual behavior here?
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 121 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOYeha6PTJjTdwozfG:-NKOYeha6PTJjTdwozfH:bp2cku0) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L121)):*
> ```Java
>       deploymentSummaries = deploymentSummaries.stream().filter(this::hasDeploymentKey).collect(Collectors.toList());
> 
>       deploymentSummaries.forEach(deploymentSummary -> saveDeploymentSummary(deploymentSummary, false));
> ```

any reason why rollback is always false?
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 147 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOYNUVBsZfnAow4A1b:-NKOYNUVBsZfnAow4A1c:bbs08x5) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L147)):*
> ```Java
> 
>     } catch (Exception ex) {
>       // We have to catch all kinds of runtime exceptions, log it and move on, otherwise the queue impl keeps retrying
> ```

Is the comment accurate? We catch all exception, not only runtime, don't log and don't "move on"
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 159 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOZ92t6t2-dvAKWYks:-NKOZ92t6t2-dvAKWYkt:bkdij38) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L159)):*
> ```Java
>     log.info("Got the result. Starting to process. Perpetual Task Id: [{}] and response [{}]", perpetualTaskId, result);
> 
>     if (!result.getExecutionStatus().equals(CommandExecutionStatus.SUCCESS.name())) {
> ```

Let's add some logic around here, if perpetual task is failing for 7/14 days then let's remove the PT
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 167 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOZHtn7H6KP9SNq2pp:-NKOZHtn7H6KP9SNq2pq:b-dywt9h) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L167)):*
> ```Java
>     Map<String, List<InstanceSyncData>> instancesPerTask = new HashMap<>();
>     for (InstanceSyncData instanceSyncData : result.getInstanceDataList()) {
>       if (!instanceSyncData.getExecutionStatus().equals(CommandExecutionStatus.SUCCESS.name())) {
> ```

We need to handle release identifiers here and clean up the ones that are failing for some period of time
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 196 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOZr9C4Us0nIasDyNR:-NKOZr9C4Us0nIasDyNS:b2bjfwm) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L196)):*
> ```Java
>         Map<String, SettingAttribute> cloudProviders = new ConcurrentHashMap<>();
>         SettingAttribute cloudProvider =
>             cloudProviders.computeIfAbsent(taskDetails.getCloudProviderId(), cloudProviderService::get);
> ```

Any reason why do you even need this cloudProviders HashMap? You're always end up in creating a new Map and always populate with a single element, I don't see to be used anywhere else
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 199 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKO_vJj2g2d1bYnM-eU:-NKO_vJk0Qp1Akd3DT7K:b6wkkk9) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L199)):*
> ```Java
> 
>         Map<CgReleaseIdentifiers, InstanceSyncData> cgReleaseIdentifiersInstanceSyncDataMap =
>             helperFactory.getHelper(cloudProvider.getValue().getSettingType())
> ```

Can we store helper in a temp variable and use it instead of always calling helperFactory.getHelper(cloudProvider.getValue().getSettingType())
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 227 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOaAahBc8Z7CVWFF6R:-NKOaAai4qp8A-GgDTSL:b-esvi9e) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L227)):*
> ```Java
>         } catch (NoInstancesException e) {
>           log.error(e.getMessage());
>           taskDetailsService.updateLastRun(taskDetailsId, releasesToUpdate, releasesToDelete);
> ```

You're ending up in updating 2 times in row if NoInstanceException is thrown, first time in catch block and second time after catch block
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java` line 114 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOcDmD2_Ep5auHj_zQ:-NKOcDmF5HoAXtz1-Rlt:b-sn87us) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java#L114)):*
> ```Java
> 
>   @Override
>   public Set<CgReleaseIdentifiers> mergeReleaseIdentifiers(
> ```

Is this logic something specific to K8s or can be common for everyone? Then it shouldn't be in this class
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/model/AbstractCgReleaseIdentifier.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOd3Ds6I6Ue_Q_vMyw:-NKOd3Ds6I6Ue_Q_vMyx:b-ucihl6) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/model/AbstractCgReleaseIdentifier.java#L21)):*
> ```Java
>   @Builder.Default
>   @EqualsAndHashCode.Exclude
>   private CgReleaseMetadata metadata = CgReleaseMetadata.builder().deleteAfter(0).build();
> ```

Can you please add empty lines after fields & each method

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)* status: 34 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 159 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOZ92t6t2-dvAKWYks:-NKRF5cf2ef2PUW2JHgu:b-bw174c) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L159)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add some logic around here, if perpetual task is failing for 7/14 days then let's remove the PT
</blockquote></details>

Will raise a separate enhancement ticket for this
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 196 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOZr9C4Us0nIasDyNR:-NKRUadd8oXh-Sr8vkm-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L196)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Any reason why do you even need this cloudProviders HashMap? You're always end up in creating a new Map and always populate with a single element, I don't see to be used anywhere else
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 199 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKO_vJj2g2d1bYnM-eU:-NKRU_0b7e4-ZAkyjKyL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L199)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we store helper in a temp variable and use it instead of always calling helperFactory.getHelper(cloudProvider.getValue().getSettingType())
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 227 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOaAahBc8Z7CVWFF6R:-NKRUrIrAeYoA1b9wXrg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L227)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

You're ending up in updating 2 times in row if NoInstanceException is thrown, first time in catch block and second time after catch block
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/model/AbstractCgReleaseIdentifier.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOd3Ds6I6Ue_Q_vMyw:-NKRVsNh3CgAyIoSuzUc:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/model/AbstractCgReleaseIdentifier.java#L21)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can you please add empty lines after fields & each method
</blockquote></details>

Done

**Comment by namantalaycha10** [comment]
trigger ss

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/api/k8s/K8sStateExecutionData.java` line 124 at r10](https://reviewable.io/reviews/harness/harness-core/41810#-NKSHlI-DzXTeh42OaYq:-NKSHlI-DzXTeh42OaYr:bfdhxr1) ([raw file](https://github.com/harness/harness-core/blob/a48b89f18d3008d6c9549b4a136623348872c8b2/400-rest/src/main/java/software/wings/api/k8s/K8sStateExecutionData.java#L124)):*
> ```Java
>         .exportManifests(exportManifests)
>         .clusterName(clusterName)
>         .pods(getPods())
> ```

just confirming, this was added for instanceSyncV2 only, not being used anywhere else in CG.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)* status: 34 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/api/k8s/K8sStateExecutionData.java` line 124 at r10](https://reviewable.io/reviews/harness/harness-core/41810#-NKSHlI-DzXTeh42OaYq:-NKSUBiOBE5ptnD40OWF:b-l39u4a) ([raw file](https://github.com/harness/harness-core/blob/01e42e38f9869eaa9a4f1bdf9c09d5b327c14fa6/400-rest/src/main/java/software/wings/api/k8s/K8sStateExecutionData.java#L124)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

just confirming, this was added for instanceSyncV2 only, not being used anywhere else in CG.
</blockquote></details>

Yes @sahilhindwani-harness 
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 121 at r5](https://reviewable.io/reviews/harness/harness-core/41810#-NKOYeha6PTJjTdwozfG:-NKSPBzJBwo5b3tpnKFv:b-mt6yur) ([raw file](https://github.com/harness/harness-core/blob/70ef7c68c86b9fb8ce40cd5834bce5e8c99e3f36/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L121)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

any reason why rollback is always false?
</blockquote></details>

This is the same way happening in instance sync v1

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 3 of 22 files at r2, 17 of 24 files at r7, 7 of 7 files at r8, 3 of 5 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)* status: 34 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 22 files at r2, 13 of 24 files at r7, 7 of 7 files at r8, 3 of 5 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r14, 3 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r14, 3 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41810)* status: :shipit: complete! ✓

**Pull request merged**
