### PR TITLE
feat: [CDS-46991]: Adding Tas Connector, Tas Service, Tas Infrastructure , Manifest and Cf command Task Handler for TAS-NG

### PR DESCRIPTION
**Pull request by sourabh-awashti**
## Describe your changes
1.Adding Infrastructure, Service, Connector for TAS in NG
2.Adding Instance sync for TAS in NG
3.Adding 3 new manifest types(TasManifest, Vars, Autoscaler)
4.Adding TAS connector validation NG task
5.Adding Instance sync for TAS containing TasInstanceSyncPerpetualTaskExecuter for delegate side.

Test Performed:
1.Creating TAS Service with TasManifest, Vars and AutoScaler manifest.
2.Created TAS connector.
3.Tested connector connectivity with harness platform
4.Tested connector connectivity with delegate

Screenshot 2022-11-18 at 10 40 39 AM
Screenshot 2022-11-17 at 4 30 25 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)

### CODE REVIEW

**Comment by sourabh-awashti** [comment]
trigger smartchecks

**Comment by sourabh-awashti** [comment]
trigger ti0

**Comment by sourabh-awashti** [comment]
trigger ti1

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 71 files at r1, 1 of 99 files at r16, 8 of 152 files at r17, 11 of 24 files at r18, 4 of 13 files at r19, 31 of 95 files at r20, 1 of 6 files at r21, 98 of 107 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556#-:-NI24Jp35R_Mt8OB_zwN:bnfp4nl)* status: 154 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556#-:-NI281bB3Ii9YT_i8NcN:bnfp4nl)* status: 154 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556#-:-NI2UbIv-utzbbCXy3Fk:bnfp4nl)* status: 154 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 269 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI32m03DCqY0N6lP7op:-NI32m03DCqY0N6lP7oq:bkxkkr) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L269)):*
> ```Java
>       ManifestType.EcsScalableTargetDefinition, ManifestType.Kustomize, ManifestType.EcsServiceDefinition, CONFIG_FILES,
>       ManifestType.HelmChart, ManifestType.ReleaseRepo, ManifestType.DeploymentRepo, ManifestType.OpenshiftTemplate,
>       ManifestType.OpenshiftParam, ManifestType.TAS_MANIFEST, ManifestType.VARS, ManifestType.AUTOSCALER);
> ```

ManifestType.VARS and ManifestType.AUTOSCALER seem generic, can we prefix TAS_ to them ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 390 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI33zhlAfxEkRtujx2o:-NI33zhlAfxEkRtujx2p:b8d78jn) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L390)):*
> ```Java
>       }
>     }
> ```

we should also make changes here 
```io.harness.cdng.infra.steps.AbstractInfrastructureTaskExecutableStep```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 390 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI33zhlAfxEkRtujx2o:-NI343nd5utKgxmCkfuO:b-bjclhr) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L390)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should also make changes here 
```io.harness.cdng.infra.steps.AbstractInfrastructureTaskExecutableStep``` 
</blockquote></details>

This is what is used with service v2

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 24 files at r18, 5 of 95 files at r20, 3 of 107 files at r22, 1 of 5 files at r24.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 143 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/TanzuApplicationServiceInfraMapping.java` line 26 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI3CToR-vRpwLbOp6dX:-NI3CToR-vRpwLbOp6dY:b-g8sy0c) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/TanzuApplicationServiceInfraMapping.java#L26)):*
> ```Java
> @RecasterAlias("io.harness.cdng.infra.beans.TanzuApplicationServiceInfraMapping")
> public class TanzuApplicationServiceInfraMapping implements InfraMapping {
>   @Id private String uuid;
> ```

@Id is a morphia annotation and probably this does not make sense here

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 269 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI32m03DCqY0N6lP7op:-NI67CnW-ADa9BdYUFXb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L269)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

ManifestType.VARS and ManifestType.AUTOSCALER seem generic, can we prefix TAS_ to them ?
</blockquote></details>

Done.

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 390 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI33zhlAfxEkRtujx2o:-NI67O3yEbw1diRo2B7K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L390)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This is what is used with service v2
</blockquote></details>

Done.

**Comment by sourabh-awashti** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/TanzuApplicationServiceInfraMapping.java` line 26 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI3CToR-vRpwLbOp6dX:-NI611kFDWyf3mszDaz1:b-rqu2p9) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/TanzuApplicationServiceInfraMapping.java#L26)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

@Id is a morphia annotation and probably this does not make sense here
</blockquote></details>

All the swimlane infraMapping are also adding the same annotation in front of UUID

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 269 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI32m03DCqY0N6lP7op:-NI6FQL-ANq-b3prNCBW:bpsn7tc) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L269)):*
<details><summary><i>Previously, sourabh-awashti wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think this is done

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 390 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI33zhlAfxEkRtujx2o:-NI6FfNJBoHrbLADnCnD:b4inswl) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L390)):*
<details><summary><i>Previously, sourabh-awashti wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think this is done either

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 269 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI32m03DCqY0N6lP7op:-NI6FfoiAGm67oYYtmaX:b-mkihwt) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L269)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I don't think this is done 
</blockquote></details>

let me push it

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 390 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI33zhlAfxEkRtujx2o:-NI6Glj301U_Vz7l3M9o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L390)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I don't think this is done either
</blockquote></details>

Done.

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 269 at r24](https://reviewable.io/reviews/harness/harness-core/40556#-NI32m03DCqY0N6lP7op:-NI6GoOTEwPdfxa4RWcm:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/88fd07e0fe59e0cfd7e25545379554dd85e457e2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L269)):*
<details><summary><i>Previously, sourabh-awashti wrote…</i></summary><blockquote>

let me push it
</blockquote></details>

done

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/TanzuApplicationServiceInfrastructure.java` line 32 at r25](https://reviewable.io/reviews/harness/harness-core/40556#-NI6SpZZ68b5KpVoIMEl:-NI6SpZZ68b5KpVoIMEm:b-gaqro8) ([raw file](https://github.com/harness/harness-core/blob/83649a964ff9eb41ccf1b54ea74884778c32a0c4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/TanzuApplicationServiceInfrastructure.java#L32)):*
> ```Java
> import lombok.Value;
> import lombok.With;
> import org.hibernate.validator.constraints.NotEmpty;
> ```

we should use 
```import javax.validation.constraints.NotEmpty;```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 24 files at r18, 5 of 95 files at r20, 4 of 107 files at r22, 2 of 5 files at r24, 7 of 11 files at r25.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 131 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 24 files at r18, 1 of 13 files at r19, 1 of 107 files at r22.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 127 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 24 files at r18, 1 of 107 files at r22, 1 of 11 files at r25.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 124 file(s) to review. 0 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/TanzuApplicationServiceInfrastructure.java` line 32 at r25](https://reviewable.io/reviews/harness/harness-core/40556#-NI6SpZZ68b5KpVoIMEl:-NI6i6wQ2CGNEAbja9M9:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/83649a964ff9eb41ccf1b54ea74884778c32a0c4/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/yaml/TanzuApplicationServiceInfrastructure.java#L32)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use 
```import javax.validation.constraints.NotEmpty;```
</blockquote></details>

done

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 108 files at r31.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 155 file(s) to review. 0 of 2 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 8 of 153 files at r26, 11 of 24 files at r27, 4 of 13 files at r28, 31 of 95 files at r29, 1 of 6 files at r30, 99 of 108 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 148 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 24 files at r27, 9 of 95 files at r29, 10 of 108 files at r31.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 125 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 125 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 24 files at r27, 1 of 13 files at r28, 4 of 108 files at r31.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 115 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 71 files at r1, 1 of 98 files at r22, 8 of 153 files at r26, 2 of 24 files at r27, 3 of 13 files at r28, 22 of 95 files at r29, 1 of 6 files at r30, 78 of 108 files at r31.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: :shipit: complete! ✓

**Comment by sourabh-awashti** [comment]
trigger ft1

**Comment by sourabh-awashti** [comment]
trigger ft2

**Comment by piyush-bhuwalka** [comment]
trigger ti2

**Comment by piyush-bhuwalka** [comment]
trigger ss

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 8 of 153 files at r32, 11 of 24 files at r33, 4 of 13 files at r34, 31 of 95 files at r35, 1 of 6 files at r36, 99 of 108 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556#-:-NI8KO2D0OP-W1MYuVaO:bnfp4nl)* status: 154 file(s) to review. 1 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
trigger ti0

**Review by yogesh-chauhan — APPROVED** [review]

**Review by sourabh-awashti — COMMENTED** [review]
> Reviewed 1 of 71 files at r1, 11 of 24 files at r33, 4 of 13 files at r34, 28 of 95 files at r35, 1 of 6 files at r36, 97 of 108 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: 154 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 153 files at r32, 11 of 24 files at r33, 4 of 13 files at r34, 31 of 95 files at r35, 1 of 6 files at r36, 99 of 108 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40556)* status: :shipit: complete! ✓

**Pull request merged**
