### PR TITLE
feat: [SRM-12253]: Move Service Guard Iterators to CVConfiguration in CG

### PR DESCRIPTION
**Pull request by praveensugavanam**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38615)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java` line 583 at r1](https://reviewable.io/reviews/harness/harness-core/38615#-NECSotT23_F8fs82cg3:-NECSotT23_F8fs82cg4:b-5bpaq) ([raw file](https://github.com/harness/harness-core/blob/d49801d053681c1190de2749ee711a43b5be9793/270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java#L583)):*
> ```Java
>             .handler(handler)
>             .schedulingType(REGULAR)
>             .persistenceProvider(injector.getInstance(MorphiaPersistenceProvider.class))
> ```

use entityProcessController as io.harness.perpetualtask.internal.PerpetualTaskRecordHandler

**Comment by raghuAtWings** [comment]
*[`270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java` line 583 at r1](https://reviewable.io/reviews/harness/harness-core/38615#-NECSotT23_F8fs82cg3:-NECSx1h37l0wMxkrugV:bhx25ou) ([raw file](https://github.com/harness/harness-core/blob/d49801d053681c1190de2749ee711a43b5be9793/270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java#L583)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

use entityProcessController as io.harness.perpetualtask.internal.PerpetualTaskRecordHandler
</blockquote></details>

also put .unsorted(true)

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38615)* status: 0 of 1 approvals obtained.

**Review by praveensugavanam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38615)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java` line 563 at r1](https://reviewable.io/reviews/harness/harness-core/38615#-NECSH-b19A4aJGxdtMF:-NEm6iuZBDk60pfvmZDw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d49801d053681c1190de2749ee711a43b5be9793/270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java#L563)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't hard code, make it a config
</blockquote></details>

Done.
___
*[`270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java` line 583 at r1](https://reviewable.io/reviews/harness/harness-core/38615#-NECSotT23_F8fs82cg3:-NEm6kWO0lh-ZsjJPyZf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d49801d053681c1190de2749ee711a43b5be9793/270-verification/src/main/java/io/harness/app/VerificationServiceApplication.java#L583)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

also put .unsorted(true) 
</blockquote></details>

Done.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38615)* status: :shipit: complete! ✓

**Comment by praveensugavanam** [comment]
trigger ti3

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38615)* status: :shipit: complete! ✓

**Pull request merged**
