### PR TITLE
[feat]: [PIE-3387]: adding expression for execution url

### PR DESCRIPTION
**Pull request by brijeshdhakar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32521)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32521)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/32521#-N0ZyYqEEmnyr2kH_I0N:-N0ZyYqEEmnyr2kH_I0O:b-2rtyzh) ([raw file](https://github.com/harness/harness-core/blob/bacb33c643859fbe68731c37664bd4e306aacfcc/800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java#L58)):*
> ```Java
>     executionMap.put("url", pipelineExpressionHelper.generateUrl(ambiance));
>     jsonObject.put("execution", executionMap);
>   }
> ```

dont add this functor to triggers as they might move out soon



_Code quote:_
```Java
  private void addExecutionUrlMap(Map<String, Object> jsonObject) {
    Map<String, String> executionMap = new HashMap<>();
    executionMap.put("url", pipelineExpressionHelper.generateUrl(ambiance));
    jsonObject.put("execution", executionMap);
  }
```

**Comment by sahilhindwani-harness** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/32521#-N0ZyYqEEmnyr2kH_I0N:-N0_GYSe0qu6BX7FvC6F:bp8lojt) ([raw file](https://github.com/harness/harness-core/blob/bacb33c643859fbe68731c37664bd4e306aacfcc/800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java#L58)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont add this functor to triggers as they might move out soon
</blockquote></details>

@archit-harness , I think this will always be in the pipeline as it is a triggeredByFunctor. The trigger functor is different which will be moved to trigger service

**Comment by brijeshdhakar** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/32521#-N0ZyYqEEmnyr2kH_I0N:-N0_IyPf8bWgWLpPmkj0:b5twpdz) ([raw file](https://github.com/harness/harness-core/blob/bacb33c643859fbe68731c37664bd4e306aacfcc/800-pipeline-service/src/main/java/io/harness/pms/expressions/functors/TriggeredByFunctor.java#L58)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@archit-harness , I think this will always be in the pipeline as it is a triggeredByFunctor. The trigger functor is different which will be moved to trigger service
</blockquote></details>

Renamed it to PipelinExecutionFunctor to avoid confusion.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32521)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32521)* status: :shipit: complete! ✓

**Pull request merged**
