### PR TITLE
techdebt: [SRM-14725]: Migrate SLI Records table to SLIRecordBucket table and perform writes on both

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes

1. Has a migration script which consists of Deleting SLI Records older than 3 months.
2. The migration scripts also consists of bucketing records into 5 minutes and adding it into the new table.
3. We are planning to delete this SLI Record table after read and write is completed. So moved SLIRecordParam and SLIState out of this class.
4. Write is now done in both the tables.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47610)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47610)* status: Some of the checks are too old. 41 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVYltYZ-yAIA6k9V5HT:-NVYltYZ-yAIA6k9V5HU:b-fdco5g) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java#L47)):*
> ```Java
>     while (true) {
>       List<SLIRecord> recordsToBeDeleted = queryToDeleteOlderRecords.find(new FindOptions().limit(1000)).toList();
>       List<String> uuidsToBeDeleted = recordsToBeDeleted.stream().map(SLIRecord::getUuid).collect(Collectors.toList());
> ```

Can use VerificationTaskCleanupSideKickExecutor::convertToObjectIdIfRequired (can move this to utils class)
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVXj-qxD_IAPxmCcREq:-NVXj-qxD_IAPxmCcREr:bty3tz0) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java#L51)):*
> ```Java
>         break;
>       }
>       hPersistence.delete(hPersistence.createQuery(SLIRecord.class).field(UuidAware.UUID_KEY).in(uuidsToBeDeleted));
> ```

nit: can add a log to track the progress.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVYmEp7-eXdcFCxn_iQ:-NVYmEp7-eXdcFCxn_iR:b-izladn) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java#L78)):*
> ```Java
>     if ((currentBucket.isEmpty())
>         || ((currentBucket.get(currentBucket.size() - 1).getEpochMinute() + 1 == sliRecord.getEpochMinute())
>             && (currentBucket.get(currentBucket.size() - 1).getSliId().equals(sliRecord.getSliId())))) {
> ```

wouldn't this lead to losing out some records? if there are 4 records with sliid = 1 and then then records comes with slid=2... current bucket will be reset.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVYnrjz5SGEjU3_ymtx:-NVYnrjz5SGEjU3_ymty:b-160hgj) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java#L93)):*
> ```Java
> 
>   public static SLIRecordBucket getSLIRecordBucketFromSLIRecords(List<SLIRecord> sliRecords) {
>     Preconditions.checkArgument(sliRecords.size() == 5);
> ```

There should be precondition that first record timestamp should be round to 5 boundary.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47610)* status: 41 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVYltYZ-yAIA6k9V5HT:-NVbrG-r9gmjWztpNOM6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java#L47)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Can use VerificationTaskCleanupSideKickExecutor::convertToObjectIdIfRequired (can move this to utils class)
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java` line 78 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVYmEp7-eXdcFCxn_iQ:-NVbrH9c96uC5EdeVTiS:bzd4k3o) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/SLIRecordToSLIRecordBucketMigration.java#L78)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

wouldn't this lead to losing out some records? if there are 4 records with sliid = 1 and then then records comes with slid=2... current bucket will be reset.
</blockquote></details>

Now we won't lose any records which we shouldn't, But didn't go through simplifying the logic approach  as getting the new sliId if current is done will still be a logic, It won't simplify much, and we can lose records.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/47610#-NVYnrjz5SGEjU3_ymtx:-NVbrffH8aMROHD4Y2a_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5a9632fa93c99c65f3099d919de2e905a92d3a86/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java#L93)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

There should be precondition that first record timestamp should be round to 5 boundary.
</blockquote></details>

Done.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by deepak-harness — APPROVED** [review]
> Reviewed 35 of 41 files at r1, 1 of 3 files at r2, 4 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47610)* status: 2. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java` line 93 at r5](https://reviewable.io/reviews/harness/harness-core/47610#-NVhdhf19nAlQ0KfFkkI:-NVhdhf19nAlQ0KfFkkJ:brlmgbp) ([raw file](https://github.com/harness/harness-core/blob/8592e0f11068154bba3bb24bbb0f94a85d4be046/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java#L93)):*
> ```Java
> 
>   public static SLIRecordBucket getSLIRecordBucketFromSLIRecords(List<SLIRecord> sliRecords) {
>     Preconditions.checkArgument(sliRecords.size() == 5);
> ```

nit: ideally we should have a custom message so that it is easy to track just in case there are flows where it is breaking.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47610)* status: :shipit: complete! ✓

**Pull request merged**
