### PR TITLE
techDebt: [PL-23701]: Remove Hazelcast library

### PR DESCRIPTION
**Pull request by rijajoo**
## Describe your changes

Remove Hazelcast library

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)

### CODE REVIEW

**Comment by rijajoo** [comment]
trigger checkstyle

**Comment by rijajoo** [comment]
trigger codeformat

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)* status: 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/SourceCodeManagerServiceImpl.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43731#-NNvCMWkAlfDDgaDOkql:-NNvCMWkAlfDDgaDOkqm:b-iypd2v) ([raw file](https://github.com/harness/harness-core/blob/2c60d8bcf668550e66a3c3c9f782099c5a25b702/123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/SourceCodeManagerServiceImpl.java#L26)):*
> ```Java
> import io.harness.security.dto.PrincipalType;
> 
> import com.google.common.base.Preconditions;
> ```

How did we check no functional behaviour will change
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/43731#-NNvCG1z7JlKZteaItzP:-NNvCG1z7JlKZteaItzQ:b8zrjcr) ([raw file](https://github.com/harness/harness-core/blob/2c60d8bcf668550e66a3c3c9f782099c5a25b702/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L52)):*
> ```Java
> import java.util.Optional;
> import java.util.stream.Collectors;
> import org.apache.commons.lang3.StringUtils;
> ```

Is this same implementation as hazelcast one?



_Code quote:_
```Java
StringUtils
```
___
*[`400-rest/src/main/java/io/harness/ccm/billing/graphql/CloudBillingAggregate.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/43731#-NNvCYZm0_RQTvqH84-V:-NNvCYZm0_RQTvqH84-W:b7btj3q) ([raw file](https://github.com/harness/harness-core/blob/2c60d8bcf668550e66a3c3c9f782099c5a25b702/400-rest/src/main/java/io/harness/ccm/billing/graphql/CloudBillingAggregate.java#L20)):*
> ```Java
> import software.wings.graphql.datafetcher.billing.QLCCMAggregateOperation;
> 
> import com.google.common.base.Preconditions;
> ```

We need to make sure no functional behaviour changes and implementation is same

**Comment by rijajoo** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/43731#-NNvCG1z7JlKZteaItzP:-NNvDmYy15j0sMXclr2E:b-oqwzx4) ([raw file](https://github.com/harness/harness-core/blob/2c60d8bcf668550e66a3c3c9f782099c5a25b702/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service/AzureResourceServiceImpl.java#L52)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is this same implementation as hazelcast one?
</blockquote></details>

Yes, isEmpty method implementation is same. Went through it.

**Comment by rijajoo** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/SourceCodeManagerServiceImpl.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/43731#-NNvCMWkAlfDDgaDOkql:-NNvFYIa4JopjUI1P99y:b2nreh6) ([raw file](https://github.com/harness/harness-core/blob/2c60d8bcf668550e66a3c3c9f782099c5a25b702/123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl/SourceCodeManagerServiceImpl.java#L26)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How did we check no functional behaviour will change
</blockquote></details>

Same as above.

**Review by rijajoo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731#-:-NNvFbCO6-AXxtfLF8bb:bnfp4nl)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731#-:-NNvHAKy1_ZYe77sUyu6:bnfp4nl)* status: Waiting on team(s): del-team.

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)* status: Waiting on team(s): del-team.

**Comment by rijajoo** [comment]
trigger copyrightcheck

**Comment by rijajoo** [comment]
trigger ti1

**Comment by rijajoo** [comment]
trigger ti1

**Comment by diptiman-adak** [comment]
trigger ti1

**Comment by diptiman-adak** [comment]
trigger ti1

**Comment by diptiman-adak** [comment]
trigger ti1

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 27 of 28 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731#-:-NOKpG8gESwYTVutwpsM:bnfp4nl)* status: Waiting on team(s): del-team.

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 27 of 28 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)* status: Waiting on team(s): del-team.

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 22 of 26 files at r1, 27 of 28 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)* status: Waiting on team(s): del-team.

**Review by puthrayaharness — APPROVED** [review]

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 22 of 26 files at r1, 27 of 28 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)* status: Waiting on team(s): del-team.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 22 of 26 files at r1, 27 of 28 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43731)* status: Waiting on team(s): del-team.

**Pull request merged**
