### PR TITLE
[feat]: [PIE-6557]: Add template validations to pipeline validation event and update db record

### PR DESCRIPTION
**Pull request by namanvermah**
Impact: Touches a flow not exposed anywhere, and no existing flows are touched. So, no impact.
Testing: Unit Tests Added. E2E testing done by hitting the new API to start the validation process, and then hitting the get result by uuid API added in the previous PR. The response came as expected.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40788)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40788)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/40788#-NI_uXMl251QtR9JpHxz:-NI_uXMmDp06OEx3cJKH:b47rm8o) ([raw file](https://github.com/harness/harness-core/blob/9a47f21040502ce68eabada32b6fda9d741790e4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java#L61)):*
> ```Java
>     // Add Template Module Info temporarily to Pipeline Entity
>     pipelineEntity.setTemplateModules(pipelineTemplateHelper.getTemplatesModuleInfo(templateMergeResponse));
>     // template merge response will be used for policy evaluation
> ```

what about this comment?



_Code quote:_
```Java
// template merge response will be used for policy evaluation
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40788)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/40788#-NI_uXMl251QtR9JpHxz:-NI_wInS34w3wmlrnzjZ:b-tp7azn) ([raw file](https://github.com/harness/harness-core/blob/9a47f21040502ce68eabada32b6fda9d741790e4/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler/PipelineAsyncValidationHandler.java#L61)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what about this comment?
</blockquote></details>

This is more of a todo sort of comment. Will be removing this in the next PR

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40788)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40788#-:-NI_x6BJ3OkBTAg0BZY_:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
