### PR TITLE
feat: [CDS-83183]: add event id while sending message in redis

### PR DESCRIPTION
**Pull request by Y0709**
Context - 
To build de-duplication of events recieved from redis streams we are adding eventId support with value as uuid in the Message.

Description -
We have observed a few instances of same redis event being received twice with different message ids by the consumers in pipeline service which sometimes results in duplicate exception in some form or other . In order to avoid that we decided to pass a unique event key and on consumer side we will check via this event key if a message is processed or not . This will ensure that even if same message is received twice we do not process it twice. In this pr we have just populated the event id and send it from producer to consumer. We will create another pr to use this id on consumer side.

Testing -- 
Tested via a basic pipeline that when we are setting event id we are receiving it on consumer side in message map and are able to set it while forming consumer message
In case message id is not set it is simply coming as empty.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisUtils.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/54909#-NiDq9s79uLn_xcj1Hw1:-NiDq9s79uLn_xcj1Hw2:b3gyl3r) ([raw file](https://github.com/harness/harness-core/blob/05f6aa989bc775bb1035da9913897968c1361cbc/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisUtils.java#L40)):*
> ```Java
>   public static final int MAX_DEAD_LETTER_QUEUE_SIZE = 50000;
>   public static final int UNACKED_RETRY_COUNT = 10;
>   public static final String HARNESS_EVENT_ID = "harness_event_id";
> ```

we are adding a big key, data normally is added with O key, can we use similarly some small key say e for this eventId

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisUtils.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/54909#-NiDq9s79uLn_xcj1Hw1:-NiDwPO836YL2i2nHU3m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/05f6aa989bc775bb1035da9913897968c1361cbc/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisUtils.java#L40)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we are adding a big key, data normally is added with O key, can we use similarly some small key say e for this eventId
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — COMMENTED** [review]
Do we know the root cause of same redis event is received twice with different message ids? Did we check with Redis team?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909#-:-NiEYmYj5mYi46vz8bjp:bo70wcd)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/MessageLogContext.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/54909#-NiF39DmAhsY-jEFlWPA:-NiF39Dn0HYRdN_qnL-q:b9un4mo) ([raw file](https://github.com/harness/harness-core/blob/05f6aa989bc775bb1035da9913897968c1361cbc/884-pms-commons/src/main/java/io/harness/pms/events/base/MessageLogContext.java#L31)):*
> ```Java
>     Map<String, String> contextMap = new HashMap<>(message.getMessage().getMetadataMap());
>     if (isNotEmpty(message.getMessage().getEventId())) {
>       contextMap.put("eventId", message.getMessage().getEventId());
> ```

lets add this to auto log context from metadataMap

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: :shipit: complete! ✓

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: :shipit: complete! ✓

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/PmsEventFrameworkConstants.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/54909#-NiIPZ7e4yESsTQis4Au:-NiIPZ7e4yESsTQis4Av:b-9uuxc1) ([raw file](https://github.com/harness/harness-core/blob/b0d2a334f11b66a2477f5692fd0846ba6a02339e/884-pms-commons/src/main/java/io/harness/pms/events/PmsEventFrameworkConstants.java#L14)):*
> ```Java
>   public static final String PIPELINE_MONITORING_ENABLED = "PIPELINE_MONITORING_ENABLED";
>   public static final int MAX_PROCESSING_TIME_SECONDS = 10;
>   public static final String PIE_EVENT_ID = "pieEventId";
> ```

lets just call it id
___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/54909#-NiIPlKd7I2QCNYV-m8c:-NiIPlKd7I2QCNYV-m8d:b-idirm8) ([raw file](https://github.com/harness/harness-core/blob/b0d2a334f11b66a2477f5692fd0846ba6a02339e/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L192)):*
> ```Java
>         || isEmpty(message.getMessage().getMetadataMap().get(PIE_EVENT_ID))) {
>       return message.getId();
>     } else {
> ```

no need for else here

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/events/PmsEventFrameworkConstants.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/54909#-NiIPZ7e4yESsTQis4Au:-NiIVcy49XPz-NJ-3gg0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0d2a334f11b66a2477f5692fd0846ba6a02339e/884-pms-commons/src/main/java/io/harness/pms/events/PmsEventFrameworkConstants.java#L14)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

lets just call it id
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/54909#-NiIPlKd7I2QCNYV-m8c:-NiIVeUA3QITIxgru4ma:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0d2a334f11b66a2477f5692fd0846ba6a02339e/884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractRedisConsumer.java#L192)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

no need for else here
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54909)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger review

**Comment by Y0709** [comment]
trigger messagecheck

**Pull request merged**
