### PR TITLE
feat: [CDS-35582]: Service Dashboard changes for blackrock

### PR DESCRIPTION
**Pull request by shivamnegi94**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32562)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32562)* status: :shipit: complete! ✓

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32562)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1654 at r1](https://reviewable.io/reviews/harness/harness-core/32562#-N0oJdX7BAKLOUYVP7ru:-N0oJdX7BAKLOUYVP7rv:b474sz7) ([raw file](https://github.com/harness/harness-core/blob/1b804f0df26f49071a814d6634bff58cf8809b15/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1654)):*
> ```Java
>   public String queryBuilderDeploymentsWithArtifactsDetails(
>       String accountId, String orgId, String projectId, String serviceId) {
>     return "SELECT DISTINCT ON (env_id) env_name, env_id, artifact_image, tag, service_startts, "
> ```

Did we explore on last function in timescale further?

**Comment by abhinavmittal-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1658 at r1](https://reviewable.io/reviews/harness/harness-core/32562#-N12SrW6BSfu0yx4jmwc:-N12SrW6BSfu0yx4jmwd:b-8lmxx) ([raw file](https://github.com/harness/harness-core/blob/1b804f0df26f49071a814d6634bff58cf8809b15/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1658)):*
> ```Java
>         + String.format("accountid='%s' and ", accountId) + String.format("orgidentifier='%s' and ", orgId)
>         + String.format("projectidentifier='%s' and ", projectId) + String.format("service_id='%s'", serviceId)
>         + " and service_status = 'SUCCESS' and artifact_image is not null order by env_id , service_endts DESC;";
> ```

lets add tag is not null
tags will always be there correct
Otherwise we might get entries that have no artifact deployed
We can check with Juhi as well if the last deployment of a service doesn't have anything deployed should we show that in the list

**Comment by abhinavmittal-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1658 at r1](https://reviewable.io/reviews/harness/harness-core/32562#-N12SrW6BSfu0yx4jmwc:-N1DTkKj74sk2UFz06Pa:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1b804f0df26f49071a814d6634bff58cf8809b15/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1658)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

lets add tag is not null
tags will always be there correct
Otherwise we might get entries that have no artifact deployed
We can check with Juhi as well if the last deployment of a service doesn't have anything deployed should we show that in the list
</blockquote></details>

Done

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32562)* status: 2 file(s) to review.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32562)* status: 2 file(s) to review.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32562)* status: :shipit: complete! ✓

**Pull request merged**
