### PR TITLE
fix: [CI-8904]: Add retries when calling SCM APIs

### PR DESCRIPTION
**Pull request by rutvijmehta-harness**
## Describe your changes
1. Added retries for server errors or connection reset when calling SCM APIs
2. Logged status code when the API fails

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51011)

### CODE REVIEW

**Comment by rutvijmehta-harness** [comment]
trigger uts

**Comment by rutvijmehta-harness** [comment]
trigger gobuild

**Comment by rutvijmehta-harness** [comment]
trigger messagecheck

**Comment by devkimittal** [comment]
Does this cover all the scm apis?

**Review by tphoney — CHANGES_REQUESTED** [review]
Really nice to have this functionality !
it looks as if the retry functions are exactly the same, except for one line. could this be made into a single generic function ?
it would be great to add some unit tests around this new functionality as well. how did you test this ?

**Comment by rutvijmehta-harness** [comment]
> Really nice to have this functionality ! it looks as if the retry functions are exactly the same, except for one line. could this be made into a single generic function ? it would be great to add some unit tests around this new functionality as well. how did you test this ?

@tphoney there's no cleaner way to add retries in a generic function since this is a wrapper over go-scm. Creating an additional interface would just complicate the code. Ideally we should be adding retries in go-scm http client since these are server side errors. I'm not opting to do so since it is fairly stable.

Regarding the UT, today we don't really mock the go-scm client. We pass a mock http server to return a certain response. It's not possible to return a different response after a retry with the current design. In future, we should add a mock for the client in the go-scm repo so that it can be consumed by harness-core.
 
I've already tested the functional calls in the e2e testing. Since it is not possible to replicate connection resets / server side errors, I've tested the retries by adding a simple test case and validated the logs locally.

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(500)
	}))
	defer ts.Close()

	in := &pb.FindPRRequest{
		Slug:   "octocat/hello-world",
		Number: 1,
		Provider: &pb.Provider{
			Hook: &pb.Provider_Github{
				Github: &pb.GithubProvider{
					Provider: &pb.GithubProvider_AccessToken{
						AccessToken: "963408579168567c07ff8bfd2a5455e5307f74d4",
					},
				},
			},
			Endpoint: ts.URL,
		},
	}

	config := zap.NewProductionConfig()
	log, _ := config.Build()
	got, err := FindPR(context.Background(), in, log.Sugar())
	assert.Nil(t, err)
	assert.Equal(t, got.Status, int32(500))

Logs:
`{"level":"info","ts":1691409577.309095,"caller":"git/git.go:162","msg":"FindPR starting","slug":"octocat/hello-world"}
{"level":"error","ts":1691409577.3097658,"caller":"git/git.go:810","msg":"Find Pull Request Git API failed with server side error","provider":"github","slug":"octocat/hello-world","number":1,"status_code":500,"retry_count":1,"stacktrace":"github.com/harness/harness-core/product/ci/scm/git.findPullRequestWithRetry\n\tproduct/ci/scm/git/git.go:810\ngithub.com/harness/harness-core/product/ci/scm/git.FindPR\n\tproduct/ci/scm/git/git.go:170\ngithub.com/harness/harness-core/product/ci/scm/git.TestFindPullRequestWithRetry\n\tproduct/ci/scm/git/git_test.go:504\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1576"}
{"level":"error","ts":1691409577.412551,"caller":"git/git.go:810","msg":"Find Pull Request Git API failed with server side error","provider":"github","slug":"octocat/hello-world","number":1,"status_code":500,"retry_count":2,"stacktrace":"github.com/harness/harness-core/product/ci/scm/git.findPullRequestWithRetry\n\tproduct/ci/scm/git/git.go:810\ngithub.com/harness/harness-core/product/ci/scm/git.FindPR\n\tproduct/ci/scm/git/git.go:170\ngithub.com/harness/harness-core/product/ci/scm/git.TestFindPullRequestWithRetry\n\tproduct/ci/scm/git/git_test.go:504\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1576"}
{"level":"error","ts":1691409577.513077,"caller":"git/git.go:810","msg":"Find Pull Request Git API failed with server side error","provider":"github","slug":"octocat/hello-world","number":1,"status_code":500,"retry_count":3,"stacktrace":"github.com/harness/harness-core/product/ci/scm/git.findPullRequestWithRetry\n\tproduct/ci/scm/git/git.go:810\ngithub.com/harness/harness-core/product/ci/scm/git.FindPR\n\tproduct/ci/scm/git/git.go:170\ngithub.com/harness/harness-core/product/ci/scm/git.TestFindPullRequestWithRetry\n\tproduct/ci/scm/git/git_test.go:504\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1576"}
`

**Comment by rutvijmehta-harness** [comment]
> Does this cover all the scm apis?

This covers all the SCM APIs currently used by CI.

**Comment by rutvijmehta-harness** [comment]
trigger uts

**Review by tphoney — APPROVED** [review]

**Review by tphoney — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51011)* status: :shipit: complete! ✓

**Pull request merged**
