### PR TITLE
fix: [CDS-84373]: Checkout branch or ref before checkout file paths

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Current approach will clone the first time based on branch or commit id the repository. Next executions will use checkout by file paths without changing the base ref. Checkout by file paths is working in overlay mode which means that it will only update and add the files paths (ref: https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefoverlayaoverlay). In this case, when a folder is used, we're not going to delete files that are not present in current branch or commit/tag. As part of this fix we're going to checkout first branch or commit id/tag and only after we will checkout the files by file path.

Changes are done only for the deployments task, for the fetch files tasks is expected that we will fetch only file paths

**Behaviour before fix**
Screenshot 2023-11-16 at 14 41 40 

> `master` branch contains README.md and templates/NOTES.txt that are not present in other branches

Screenshot 2023-11-16 at 14 43 29

> `helm-files-test` branch doesn't contain README.md and templates/NOTEST.txt files but we're still fetching those.

**Behaviour after fix**
Screenshot 2023-11-16 at 14 45 54

Screenshot 2023-11-16 at 14 46 18

Screenshot 2023-11-16 at 14 47 31

> commit `e6b8d3a` matches `helm-files-test`  branch

Screenshot 2023-11-16 at 15 14 17

> tag `helm-files-test-2` matches branch `helm-files-test-2` that is the same as `helm-files-test` without `templates/hpa.yaml`

### Tested use cases
- [x] First fetch base branch with files that are not present in other branches and after fetch a branch where some files are not present
- [x] First fetch base branch with files that are not present and after fetch by commit where some files are not present
- [x] First fetch base commit id with files that are not present in other commits and after fetch by commit where some files are not present
- [x] First fetch base commit id with files that are not present in other branch and after fetch by branch where some files are not present   
- [x] First fetch a tag matching with a branch name and then fetch that branch 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55499)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger checkstylecodeformat

**Comment by abosii-harness** [comment]
trigger commonchecks

**Comment by abosii-harness** [comment]
trigger uts

**Review by acasian-harness — DISMISSED** [review]

**Review by vlica-harness — DISMISSED** [review]

**Review by markoharness — DISMISSED** [review]

**Review by alebuh — APPROVED** [review]

**Comment by abosii-harness** [comment]
trigger messagecheck, review

**Comment by abosii-harness** [comment]
trigger checkstylecodeformat, commonchecks, uts

**Review by tmacari-harness — APPROVED** [review]

**Review by acasian-harness — APPROVED** [review]

**Review by GoelPratyush99 — APPROVED** [review]

**Review by TarunUba1 — APPROVED** [review]

**Comment by abosii-harness** [comment]
trigger messagecheck, review

**Comment by abosii-harness** [comment]
trigger messagecheck

**Pull request merged**
