### PR TITLE
[feat]: [CDS-73576]: Integrating page size and branch filters in list branch api

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added code to integrate the page size and the branch filters in the scm service. Have tested out the code flows both via delegate and manager, was able to verify the passed params are reaching the scm service.
It is a backward compatible change with respect to delegate.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50922)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1248 at r2](https://reviewable.io/reviews/harness/harness-core/50922#-NaBqv8A6Th2i2N5Pe8O:-NaBqv8A6Th2i2N5Pe8P:b-nl95w3) ([raw file](https://github.com/harness/harness-core/blob/a4a2d08aae2598490aaa819a8db5849acf2914df/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1248)):*
> ```Java
>   }
> 
>   private BranchFilterDelegateTaskParams buildRepoFilterDelegateTaskParams(
> ```

why's the name : "buildRepo..."

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 245 at r2](https://reviewable.io/reviews/harness/harness-core/50922#-NaBr1-j1T0jsJAA1nNU:-NaBr1-j1T0jsJAA1nNV:b-inzn1j) ([raw file](https://github.com/harness/harness-core/blob/a4a2d08aae2598490aaa819a8db5849acf2914df/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L245)):*
> ```Java
>   @Override
>   public GitBranchesResponseDTO listBranchesV2(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String connectorRef, String repoName, PageRequest pageRequest, ScmBranchFilterParams scmBranchFilterParams) {
> ```

Why's a structure that contains API schema information being used at service level?

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 245 at r2](https://reviewable.io/reviews/harness/harness-core/50922#-NaBr1-j1T0jsJAA1nNU:-NaBvjhT2pmVVtrfpjqp:bcyzuap) ([raw file](https://github.com/harness/harness-core/blob/a4a2d08aae2598490aaa819a8db5849acf2914df/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L245)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why's a structure that contains API schema information being used at service level?
</blockquote></details>

We expect all the params to be passed across to service layer and also its an internal api, so didnt create a dto

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50922)* status: 26 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1248 at r2](https://reviewable.io/reviews/harness/harness-core/50922#-NaBqv8A6Th2i2N5Pe8O:-NaBvjHPBMiC2Xyp3kTt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a4a2d08aae2598490aaa819a8db5849acf2914df/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1248)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why's the name : "buildRepo..."
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 245 at r2](https://reviewable.io/reviews/harness/harness-core/50922#-NaBr1-j1T0jsJAA1nNU:-NaD_rOY--_DkJnW4wZJ:bw9au3m) ([raw file](https://github.com/harness/harness-core/blob/a4a2d08aae2598490aaa819a8db5849acf2914df/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L245)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

We expect all the params to be passed across to service layer and also its an internal api, so didnt create a dto
</blockquote></details>

If its internal API, then why schema details added?

I think its already known and concluded that no service layer should have any dto from resource layer. Lets abide by it unless we have some other reasoning against it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1280 at r3](https://reviewable.io/reviews/harness/harness-core/50922#-NaDa6Kr3bnDROeFQ0iV:-NaDa6Kr3bnDROeFQ0iW:b-i7by1z) ([raw file](https://github.com/harness/harness-core/blob/529cd0a663837f856ef37f0bbf4b1bf06a1a7926/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1280)):*
> ```Java
>         .userName(scmRepoFilterParams.getUserName())
>         .build();
>   }
> ```

space line missing

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50922)* status: 26 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 245 at r2](https://reviewable.io/reviews/harness/harness-core/50922#-NaBr1-j1T0jsJAA1nNU:-NaFckHZ09RABIim1WKp:b-jwy65a) ([raw file](https://github.com/harness/harness-core/blob/a4a2d08aae2598490aaa819a8db5849acf2914df/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L245)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If its internal API, then why schema details added?

I think its already known and concluded that no service layer should have any dto from resource layer. Lets abide by it unless we have some other reasoning against it.
</blockquote></details>

Have added a new DTO and also we had followed similar approach for the repo filter api, updated the same for list repo api
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1280 at r3](https://reviewable.io/reviews/harness/harness-core/50922#-NaDa6Kr3bnDROeFQ0iV:-NaFcdJ3EX9vmkXo8h5a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/529cd0a663837f856ef37f0bbf4b1bf06a1a7926/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1280)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

space line missing
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 20 of 26 files at r1, 2 of 2 files at r3, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50922)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 20 of 26 files at r1, 2 of 2 files at r3, 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50922)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger ut0

**Comment by adivishy1** [comment]
trigger ut5

**Comment by adivishy1** [comment]
trigger ut0

**Comment by adivishy1** [comment]
trigger ut0, ut5

**Pull request merged**
