### PR TITLE
fix: [CDS-44282]: changes to download chart (atmost once) in …

### PR DESCRIPTION
**Pull request by achyuth-harness**
…K8s Rolling/Helm Deploy step

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38407)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38407)

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38407)* status: 6 file(s) to review. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2665 at r2](https://reviewable.io/reviews/harness/harness-core/38407#-NDflob82dm1MdAcZnwm:-NDflob902tNR3uDwQRI:br63ksf) ([raw file](https://github.com/harness/harness-core/blob/e0b5a6fb3f54a7709ef63e615b9487c71172cd69/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2665)):*
> ```Java
>       String repoName = helmTaskHelperBase.getRepoNameNG(manifestDelegateConfig.getStoreDelegateConfig());
>       if (isEnvVarSet) {
>         String parentDir = helmTaskHelperBase.getHelmLocalRepositoryCompletePath(repoName, chartName, chartVersion);
> ```

Do we have UT covering this scenario already?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38407)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2665 at r2](https://reviewable.io/reviews/harness/harness-core/38407#-NDflob82dm1MdAcZnwm:-NDfpAwZ3SxAgFL1DLXz:b-pid307) ([raw file](https://github.com/harness/harness-core/blob/e0b5a6fb3f54a7709ef63e615b9487c71172cd69/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2665)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

I just ran tests locally. testFetchManifestFilesAndWriteToDirectoryHttpHelmEnvVar is failing, can you check?
Not sure if it's only for me
</blockquote></details>

Yes, its failing for me too, weird that TI did not catch this

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38407)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 2665 at r2](https://reviewable.io/reviews/harness/harness-core/38407#-NDflob82dm1MdAcZnwm:-NDg0qwQ3KPyTnjd1lE2:bk3pu6g) ([raw file](https://github.com/harness/harness-core/blob/e0b5a6fb3f54a7709ef63e615b9487c71172cd69/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L2665)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Yes, its failing for me too, weird that TI did not catch this 
</blockquote></details>

Have fixed this UT (ran other tests also, like HelmTaskHelperBaseTest, HelmTaskHelperTest and K8sTaskHelperTest)

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38407#-:-NDg7b1kDtmDSDypL745:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
