### PR TITLE
[feat]: [CCM-8010]: CCM License Usage - Group Trait

### PR DESCRIPTION
**Pull request by Rohit-Kaliki**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34965)

### CODE REVIEW

**Comment by Rohit-Kaliki** [comment]
trigger messagecheck

**Comment by Rohit-Kaliki** [comment]
trigger feature-build

**Comment by Rohit-Kaliki** [comment]
trigger feature-build

**Comment by Rohit-Kaliki** [comment]
trigger feature-build

**Comment by Rohit-Kaliki** [comment]
trigger feature-build

**Comment by Rohit-Kaliki** [comment]
trigger feature-build

**Comment by Rohit-Kaliki** [comment]
trigger feature-build

**Comment by Rohit-Kaliki** [comment]
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22ccm-play%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22ce-dev%22%0Aresource.labels.namespace_name%3D%22harness%22%0Alabels.k8s-pod%2Fapp%3D%22batch-processing%22%0AjsonPayload.logger%3D%22io.harness.batch.processing.schedule.BatchJobRunner%22%0A%22kmpySmUISimoRrJL6NL73w%22;cursorTimestamp=2022-07-06T11:30:27.667521927Z?project=ccm-play

**Review by hitesharinga — APPROVED** [review]
> Reviewed 4 of 6 files at r3, 2 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34965)* status: :shipit: complete! ✓

**Pull request merged**
