### PR TITLE
feat: [SRM-14836]: move monitored service entity to platform level ch…

### PR DESCRIPTION
**Pull request by karansaraswat19**
…anges

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48664)

### CODE REVIEW

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48664)* status: 4 file(s) to review. 0 of 1 approvals obtained.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
As discussed please create a new rest end point for platform monitored service API.

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48664#-:-NWvzu9I2Of2RCd172yX:b-aqyyy6)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48664)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItem.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/48664#-NXFaZK01XOVEr5vtO_B:-NXFaZK01XOVEr5vtO_C:b2t77rp) ([raw file](https://github.com/harness/harness-core/blob/d7a3c0df10abca2667a41a4cf32fd8221ebbb1bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItem.java#L18)):*
> ```Java
> @Value
> @Builder
> public class MonitoredServiceListItem {
> ```

MonitoredServicePlatformResponse
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java` line 300 at r3](https://reviewable.io/reviews/harness/harness-core/48664#-NXF_tDW-TfFzsEK5Pnv:-NXF_tDW-TfFzsEK5Pnw:b-vmsu3b) ([raw file](https://github.com/harness/harness-core/blob/d7a3c0df10abca2667a41a4cf32fd8221ebbb1bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java#L300)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @Path("/list/v2")
> ```

v2 suggest there is some logic change since v1. since it is only response change we can use /monitored-service/platform/list
same with nicknames and method names
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/48664#-NXFaPev3Cu1TVYN__Gf:-NXFaPev3Cu1TVYN__Gg:bdohi0u) ([raw file](https://github.com/harness/harness-core/blob/d7a3c0df10abca2667a41a4cf32fd8221ebbb1bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/monitoredService/MonitoredServiceService.java#L64)):*
> ```Java
>       Integer offset, Integer pageSize, String filter);
> 
>   PageResponse<MonitoredServiceListItem> getList(ProjectParams projectParams, List<String> environmentIdentifiers,
> ```

getplatformMonitoredServiceList

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 9 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48664)* status: :shipit: complete! ✓

**Comment by karansaraswat19** [comment]
trigger uts

**Pull request merged**
