### PR TITLE
feat: [PL-25633]: Add support for consuming resource group in Access Control

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34571)

### CODE REVIEW

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F3L1b1LAUPPSB1MSi:-N5F3L1b1LAUPPSB1MSj:b-stauvs) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L53)):*
> ```Java
>         .resourceSelector(resourceSelector.getSelector())
>         .conditional(resourceSelector.isConditional())
>         .jexlCondition(resourceSelector.getCondition())
> ```

I think we should just call it condition instead of jexlCondition
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F79cb2b5ny4aRP7vL:-N5F79cb2b5ny4aRP7vM:byb5o0w) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java#L105)):*
> ```Java
> 
>   @Override
>   public long deleteByRoleAssignmentIdAndResourceSelectors(
> ```

Can we delete matching ACLs in 1 shot instead of multiple DB calls
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceGroupFactory.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F8Bho6rNQyU9Loc3R:-N5F8Bho6rNQyU9Loc3S:babgv56) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/service/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceGroupFactory.java#L59)):*
> ```Java
>         .scopeIdentifier(scopeIdentifier)
>         .name(resourceGroupDTO.getName())
>         .resourceSelectors(resourceSelectors.stream()
> ```

Will this field be completely redundant now after this change?

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F3L1b1LAUPPSB1MSi:-N5Gb3U037nDcJP7prIa:bb71kmx) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/libs/aggregator/src/main/java/io/harness/aggregator/ACLUtils.java#L53)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we should just call it condition instead of jexlCondition
</blockquote></details>

Okay
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F79cb2b5ny4aRP7vL:-N5Gb42Q53DASza2dD5D:bfnov3r) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java#L105)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we delete matching ACLs in 1 shot instead of multiple DB calls
</blockquote></details>

No that would not be possible.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceGroupFactory.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F8Bho6rNQyU9Loc3R:-N5Gb5gA5cZxSTlhh-3M:b5au8xt) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/service/src/main/java/io/harness/accesscontrol/resources/resourcegroups/ResourceGroupFactory.java#L59)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Will this field be completely redundant now after this change?
</blockquote></details>

Yes. I am maintaining backwards compatibility for now.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F79cb2b5ny4aRP7vL:-N5IOcgzCRx6BJrfcilX:b-5tlqct) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java#L105)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

No that would not be possible.
</blockquote></details>

Lets discuss it once

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571#-:-N5K2MHu9vNmuLgKO3gc:bnfp4nl)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/34571#-N5F79cb2b5ny4aRP7vL:-N5KTu4G0FETQuU2SC4m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/78614b79735188b96744a8ef252d17c40f2aebee/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java#L105)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets discuss it once
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571#-:-N5KsF4eDBAxiPlarRh9:bnfp4nl)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 12 of 15 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34571)* status: :shipit: complete! ✓

**Pull request merged**
