### PR TITLE
feat: [PIE-8809]: Integrate FF SDK with Pipeline service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Integrate FF SDK with Pipeline service. This will remove dependency on CG-Manager for fetching the value of a FF.

**Testing:** Tested locally as follows:
Case-1: give value of featureFlagSystem as local, this fetches the value from featureFlag collection of pms-harness DB.
Case-2: give value of featureFlagSystem as CF, and also mention API key of an env, this fetches the value from UAT.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut4, ut5

**Comment by mohitg0795** [comment]
*[`pipeline-service/config/config.yml` line 571 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-SzXK-bfvctarbErb:-NQ-SzXK-bfvctarbErc:bbsb076) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/config/config.yml#L571)):*
> ```YAML
>   analyticsEnabled: true
>   connectionTimeout: 10000
>   readTimeout: 45000
> ```

whats the difference b/w read timeout and connection timeout?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-TPUA1K1A_Ph1P0IP:-NQ-TPUA1K1A_Ph1P0IQ:b-42xeiw) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L45)):*
> ```Java
>     try {
>       List<StatusAndTime> statusAndTime;
>       if (!featureFlagService.isEnabled(FETCH_PIPELINE_HEALTH_FROM_NEW_TABLE, accountId)) {
> ```

instead of doing changes like this everywhere, can't we simply replace the integration in our PMS feature flag service itself? It can simply start talking to FF sdk instead of previous CG/NG service.

This way automatically all the current FF calls will move to FF sdk, with change at a central place.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 335 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-br_f9eHY6aJIu6kJ:-NQ-br_f9eHY6aJIu6kK:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L335)):*
> ```Java
>         return CfMigrationConfig.builder().build();
>       }
> ```

why is this needed?



_Code quote:_
```Java
      @Override
      public CfMigrationConfig cfMigrationConfig() {
        return CfMigrationConfig.builder().build();
      }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-TPUA1K1A_Ph1P0IP:-NQ-bzmT8MDkVO4Masvk:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

instead of doing changes like this everywhere, can't we simply replace the integration in our PMS feature flag service itself? It can simply start talking to FF sdk instead of previous CG/NG service.

This way automatically all the current FF calls will move to FF sdk, with change at a central place.
</blockquote></details>

+1

**Comment by shalini-agr** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 335 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-br_f9eHY6aJIu6kJ:-NQ-dLSaCtVx_F-OfTp-:b6juu2o) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L335)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

cfMigrationConfig() is an abstract method in AbstractCfModule, so, if we want to use AbstractCfModule, we'll have to override this method

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-TPUA1K1A_Ph1P0IP:-NQ0PG01DgohApi9w5sQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 571 at r2](https://reviewable.io/reviews/harness/harness-core/44869#-NQ-SzXK-bfvctarbErb:-NQ9ndjF7uMBJIvjGZAD:b4cxjth) ([raw file](https://github.com/harness/harness-core/blob/c13ddbf8739f359ad79f90afd7e6c2582fd54f0b/pipeline-service/config/config.yml#L571)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the difference b/w read timeout and connection timeout?
</blockquote></details>

I'm not really sure, it's a part of cfClientConfig but I don't find any usage for these fields, copied their default values from other services.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: 17 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/FeatureNameAndAccountId.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/44869#-NQ9vNVj9oqpO0LJCEDG:-NQ9vNVj9oqpO0LJCEDH:ba6x2uv) ([raw file](https://github.com/harness/harness-core/blob/c304af28fbbc6523d7bc04185805fa7bd7db40c7/878-ng-common-utilities/src/main/java/io/harness/utils/FeatureNameAndAccountId.java#L21)):*
> ```Java
> @Data
> @Builder
> public class FeatureNameAndAccountId {
> ```

add team annotation and description what does it mean
Also you can create this in helper class only where its needed, as its not shared
___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/pms/helpers/PmsFeatureFlagHelperTest.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/44869#-NQ9vqSR9aOWVRd33nkl:-NQ9vqSS9KiZJMEjZAYo:bxfcldr) ([raw file](https://github.com/harness/harness-core/blob/c304af28fbbc6523d7bc04185805fa7bd7db40c7/pipeline-service/modules/orchestration/src/test/java/io/harness/pms/helpers/PmsFeatureFlagHelperTest.java#L35)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class PmsFeatureFlagHelperTest extends OrchestrationTestBase {
> ```

I think this can be category test as everything is mocked

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: 17 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/utils/FeatureNameAndAccountId.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/44869#-NQ9vNVj9oqpO0LJCEDG:-NQ9yOxJA3ngMQ226Cia:bukg3h4) ([raw file](https://github.com/harness/harness-core/blob/c304af28fbbc6523d7bc04185805fa7bd7db40c7/878-ng-common-utilities/src/main/java/io/harness/utils/FeatureNameAndAccountId.java#L21)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add team annotation and description what does it mean
Also you can create this in helper class only where its needed, as its not shared
</blockquote></details>

yes, moved this class to PmsFeatureFlagHelper

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/pms/helpers/PmsFeatureFlagHelperTest.java` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/44869#-NQ9vqSR9aOWVRd33nkl:-NQ9yUaN4hUKk88GkYm2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c304af28fbbc6523d7bc04185805fa7bd7db40c7/pipeline-service/modules/orchestration/src/test/java/io/harness/pms/helpers/PmsFeatureFlagHelperTest.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think this can be category test as everything is mocked
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger ut2

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 2 of 7 files at r3, 2 of 2 files at r4, 3 of 4 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44869)* status: :shipit: complete! ✓

**Pull request merged**
