### PR TITLE
[feat]: [CDS-71819]: Propogation of template error to pipeline service

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Describe your changes

Updating a remote pipeline:

Screenshot 2023-06-13 at 1 23 20 PM

Creating a remote pipeline
This one will be improved from UI. All error messages are getting propogated to the UI but UI seems to be not utilising those

Screenshot 2023-06-13 at 1 39 07 PM

On Run form
This will also be improved.

Screenshot 2023-06-13 at 1 40 16 PM

- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)* status: 10 file(s) to review. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ngexception/PipelineException.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/49152#-NXnoEBjEoiUgJGcUpJI:-NXnoEBjEoiUgJGcUpJJ:b-k8n7vs) ([raw file](https://github.com/harness/harness-core/blob/d05c2cca8188452373ab7598eb89739992f738ae/980-commons/src/main/java/io/harness/exception/ngexception/PipelineException.java#L14)):*
> ```Java
> import io.harness.exception.WingsException;
> 
> public class PipelineException extends WingsException {
> ```

nit: Team annotation

**Comment by naidu-harness** [comment]
@sahilhindwani-harness  @mohitg0795 Where do i see the actual Git error from SCM provider? The requested file path does not exist coming from SCM or our own messaging. i want to show the exact SCM error in this case

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)* status: 11 file(s) to review.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqK0e0-8YybWL5rJ9H:-NYqK0e0-8YybWL5rJ9I:bkuym56) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L125)):*
> ```Java
>       PipelineEntity createdEntity = pipelineCRUDResult.getPipelineEntity();
>       return ResponseDTO.newResponse(createdEntity.getVersion().toString(), createdEntity.getIdentifier());
>     } catch (NGTemplateException ex) {
> ```

We should add this catch in service layer as its a centralized change for all create flows.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqK7FnACn6KIVSz1O5:-NYqK7FnACn6KIVSz1O6:b9b4exa) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L127)):*
> ```Java
>     } catch (NGTemplateException ex) {
>       throw new PipelineException(
>           PipelineException.PIPELINE_CREATE_MESSAGE, ex, ErrorCode.NG_PIPELINE_CREATE_EXCEPTION);
> ```

may be a better way would be to use specific exceptions like Pipeline-create-exception instead of free-form where it introduces chances of missed. This is discussed and will be taken up going forward.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqLZ7tDDeFuMYwolJc:-NYqLZ7tDDeFuMYwolJd:b-mvs86v) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L127)):*
> ```Java
>         }
>       } catch (InvalidRequestException e) {
>         throw new NGTemplateException("", e.getResponseMessages());
> ```

we can have use-case based error message instead of blank error message.

**Comment by mohitg0795** [comment]
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 148 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqMWwx9oBj60uX8Vex:-NYqMWwx9oBj60uX8Vey:b-evabaa) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L148)):*
> ```Java
>     }
>     if (!templateEntity.isPresent()) {
>       throw new NGTemplateException(String.format(
> ```

lets make it modular and keep it available as a method to be used elsewhere as we go and onboard more methods to our new error handling

**Comment by mohitg0795** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 120 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqMqfGBxTrx3zLQ3nQ:-NYqMqfGBxTrx3zLQ3nR:by87j0j) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L120)):*
> ```Java
>       ScmException exception = TemplateUtils.getScmException(e);
>       if (null != exception) {
>         throw new InvalidRequestException(
> ```

these are repeated codes, lets check and see if we can improve here.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqLZ7tDDeFuMYwolJc:-NZzbLi47g2I5fx7xoN-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L127)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we can have use-case based error message instead of blank error message.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 148 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqMWwx9oBj60uX8Vex:-NZzbMn694_9hU6yg2nL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L148)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets make it modular and keep it available as a method to be used elsewhere as we go and onboard more methods to our new error handling
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 120 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqMqfGBxTrx3zLQ3nQ:-NZzbOkL7rs4mxjiiVZ1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L120)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

these are repeated codes, lets check and see if we can improve here.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/49152#-NYqK0e0-8YybWL5rJ9H:-NZzbPYu9qqeMj-Ci4w6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/25cb00686284482203cdc18eb84425a6ee166416/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L125)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We should add this catch in service layer as its a centralized change for all create flows.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)* status: 13 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)* status: 13 file(s) to review.

**Comment by sahilhindwani-harness** [comment]
trigger commonchecks

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)* status: 13 file(s) to review.

**Comment by sahilhindwani-harness** [comment]
trigger review

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 10 files at r1, 2 of 3 files at r2, 5 of 9 files at r4, 1 of 1 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49152)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger review

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by sahilhindwani-harness** [comment]
trigger review

**Pull request merged**
