### PR TITLE
[fix]: [DEL-4028]: Remove keepAlive packets for polling and socket communicat…

### PR DESCRIPTION
**Pull request by AnupamIO**
JIRA: https://harness.atlassian.net/browse/DEL-4028

Changes:
1. Removed sending of keepAlive packets from delegate to manager for non ECS delegate using sockets.
2. Removed sending of keepAlive packets from delegate to manager using polling.
3. Removed broadcasting of cdn and jre message as they are not used.
4. **Not removed** broadcasting of SELF_DESTRUCT if delegateGroup is deleted or account is deleted, I feel we should put it there because we have no other way to stop delegate itself after it is deleted from UI.

Changes needs to be tested in pr environment. Preferably we should run delegate for few hours and see it it works properly in pr env.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34221)

### CODE REVIEW

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34221)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34221)* status: :shipit: complete! ✓

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 915 at r1](https://reviewable.io/reviews/harness/harness-core/34221#-N4QmoO51C97x4ueFyE7:-N4QmoO51C97x4ueFyE8:bvjt1iv) ([raw file](https://github.com/harness/harness-core/blob/f9a11115339aaf108331ff862038139ad0d97393/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L915)):*
> ```Java
>       log.warn("Delegate used revoked token. It will be frozen and drained.");
>       freeze();
>     }
> ```

we can add else condition with log.warn of unaccepted message received.

**Comment by AnupamIO** [comment]
trigger messagecheck

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34221)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 915 at r1](https://reviewable.io/reviews/harness/harness-core/34221#-N4QmoO51C97x4ueFyE7:-N50PzEOBkfltClsKyS7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9a11115339aaf108331ff862038139ad0d97393/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L915)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we can add else condition with log.warn of unaccepted message received.
</blockquote></details>

Done.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34221)* status: :shipit: complete! ✓

**Pull request merged**
