### PR TITLE
techdebt: [SRM-11076]: Adding unit tests for Prometheus Data Collection DSL wit…

### PR DESCRIPTION
**Pull request by dhruv-harness**
…hout host info

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35708)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger ti4

**Review by naveen-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35708)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/PrometheusDataCollectionDSLTest.java` line 309 at r1](https://reviewable.io/reviews/harness/harness-core/35708#-N7ty2r14Kz7tTvA6HE4:-N7ty2r14Kz7tTvA6HE5:b-7mt7vd) ([raw file](https://github.com/harness/harness-core/blob/3814aa61961ad4d39f980adc4c0d819ff5d35df0/300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/PrometheusDataCollectionDSLTest.java#L309)):*
> ```Java
>     assertThat(timeSeriesRecords.get(89).getTxnName()).isEqualTo("g1");
>     assertThat(timeSeriesRecords.get(0).getMetricName()).isEqualTo("container_file_descriptors");
>     assertThat(timeSeriesRecords.get(0).getMetricIdentifier()).isEqualTo("container_file_descriptors");
> ```

Why are we only asserting data at first and last index ? Shouldn't we check all the 90 indexes using for loop ? 



_Code quote:_
```Java
    assertThat(timeSeriesRecords).hasSize(90);
    assertThat(timeSeriesRecords.get(0).getTimestamp()).isEqualTo(1658778508000L);
    assertThat(timeSeriesRecords.get(0).getTxnName()).isEqualTo("g1");
    assertThat(timeSeriesRecords.get(0).getMetricValue()).isEqualTo(3.0);
    assertThat(timeSeriesRecords.get(0).getTimestamp()).isGreaterThanOrEqualTo(startInstant.toEpochMilli());
    assertThat(timeSeriesRecords.get(89).getTimestamp()).isLessThanOrEqualTo(endInstant.toEpochMilli());
    assertThat(timeSeriesRecords.get(89).getTimestamp()).isEqualTo(1658778808000L);
    assertThat(timeSeriesRecords.get(89).getMetricValue()).isEqualTo(0.0);
    assertThat(timeSeriesRecords.get(89).getTxnName()).isEqualTo("g1");
    assertThat(timeSeriesRecords.get(0).getMetricName()).isEqualTo("container_file_descriptors");
    assertThat(timeSeriesRecords.get(0).getMetricIdentifier()).isEqualTo("container_file_descriptors");
```
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/PrometheusDataCollectionDSLTest.java` line 377 at r1](https://reviewable.io/reviews/harness/harness-core/35708#-N7tyGe6-zWLbxscHucX:-N7tyGe6-zWLbxscHucY:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/3814aa61961ad4d39f980adc4c0d819ff5d35df0/300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/PrometheusDataCollectionDSLTest.java#L377)):*
> ```Java
>     assertThat(timeSeriesRecords.get(89).getTxnName()).isEqualTo("g1");
>     assertThat(timeSeriesRecords.get(0).getMetricName()).isEqualTo("container_file_descriptors");
>     assertThat(timeSeriesRecords.get(0).getMetricIdentifier()).isEqualTo("container_file_descriptors");
> ```

Ditto



_Code quote:_
```Java
    assertThat(timeSeriesRecords).hasSize(90);
    assertThat(timeSeriesRecords.get(0).getTimestamp()).isEqualTo(1658778508000L);
    assertThat(timeSeriesRecords.get(0).getTxnName()).isEqualTo("g1");
    assertThat(timeSeriesRecords.get(0).getMetricValue()).isEqualTo(3.0);
    assertThat(timeSeriesRecords.get(0).getTimestamp()).isGreaterThanOrEqualTo(startInstant.toEpochMilli());
    assertThat(timeSeriesRecords.get(89).getTimestamp()).isLessThanOrEqualTo(endInstant.toEpochMilli());
    assertThat(timeSeriesRecords.get(89).getTimestamp()).isEqualTo(1658778808000L);
    assertThat(timeSeriesRecords.get(89).getMetricValue()).isEqualTo(0.0);
    assertThat(timeSeriesRecords.get(89).getTxnName()).isEqualTo("g1");
    assertThat(timeSeriesRecords.get(0).getMetricName()).isEqualTo("container_file_descriptors");
    assertThat(timeSeriesRecords.get(0).getMetricIdentifier()).isEqualTo("container_file_descriptors");
```

**Review by naveen-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35708#-:-N7vOCUX2j_8h3dfHJzK:bnfp4nl)* status: 3 file(s) to review.

**Review by naveen-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35708)* status: :shipit: complete! ✓

**Pull request merged**
