### PR TITLE
[fix]: [PL-41356]: Fixing dependency issue while monitoring initialization in platform service

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
We resolved the dependency issue to ensure proper monitoring initialization in platform-service.

Test:

- After the fix, we no longer encounter the below error that was occurring previously.

```
2023-09-20 23:55:20,138 [main] ERROR io.harness.metrics.jobs.RecordMetricsJob - Exception while creating a scheduled metrics recorder  
com.google.inject.ConfigurationException: Guice configuration errors:

1) [Guice/MissingImplementation]: No implementation for OutboxDao was bound.

Requested by:
1  : OutboxMetricsPublisher.<init>(OutboxMetricsPublisher.java:38)
      \_ for 1st parameter outboxDao
     while locating OutboxMetricsPublisher

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2) [Guice/MissingImplementation]: No implementation for String annotated with @Named("serviceIdForOutboxMetrics") was bound.

Requested by:
1  : OutboxMetricsPublisher.<init>(OutboxMetricsPublisher.java:38)
      \_ for 3rd parameter serviceId
     while locating OutboxMetricsPublisher

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2 errors

======================
Full classname legend:
======================
Named:                  "com.google.inject.name.Named"
OutboxDao:              "io.harness.outbox.api.OutboxDao"
OutboxMetricsPublisher: "io.harness.outbox.monitor.OutboxMetricsPublisher"
========================
End of classname legend:
========================

	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1127)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1087)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139)
	at io.harness.metrics.jobs.RecordMetricsJob.lambda$scheduleMetricsTasks$1(RecordMetricsJob.java:36)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.harness.metrics.jobs.RecordMetricsJob.scheduleMetricsTasks(RecordMetricsJob.java:34)
	at io.harness.platform.PlatformApplication.initMetrics(PlatformApplication.java:334)
	at io.harness.platform.PlatformApplication.run(PlatformApplication.java:197)
	at io.harness.platform.PlatformApplication.run(PlatformApplication.java:100)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at io.harness.platform.PlatformApplication.main(PlatformApplication.java:113)
```
- Also platform-service deployed in devspace without restart
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PL-41356]: https://harness.atlassian.net/browse/PL-41356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53104)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53104)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/53104#-NeqRCLX70hV2xwuN8N9:-NeqRCLY7HDFkzqyZQeX:b-azee4l) ([raw file](https://github.com/harness/harness-core/blob/9f26a051a8ca1c2eb01dee8861214d2a027844f0/platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java#L64)):*
> ```Java
>     registerIterators(injector);
>     registerOasResource(appConfig, environment, injector);
>     initializeMonitoring(appConfig, injector);
> ```

This change will register metrics for only audit module with in platform service. Is this intentional? What will happen for notification and resource group module?

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/53104#-NeqRCLX70hV2xwuN8N9:-NeqkEXI67z31-XkXdO0:bkeqwrr) ([raw file](https://github.com/harness/harness-core/blob/9f26a051a8ca1c2eb01dee8861214d2a027844f0/platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java#L64)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This change will register metrics for only audit module with in platform service. Is this intentional? What will happen for notification and resource group module?
</blockquote></details>

As discussed monitoring is already configured for resource group. And in notification service not using outbox and not outbox metrics being published.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53104)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
