### PR TITLE
[feat]: [CDS-79376]: Add Config Boolean Variable to Disable Custom Stage In Pipeline Service

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
We have added a boolean variable `disableCustomStageInPipelineService` in pipeline service config file. If that variable is true, then custom stage plan creator will not be registered in pipeline service & thus ng-manager service will pick it up and execute it. 

Test Scenarios: 
1. DISABLE_CUSTOM_STAGE_IN_PIPELINE_SERVICE env. variable set as false - Custom Stage executes via pipeline service and env. & infra. steps are not executed. 
2. DISABLE_CUSTOM_STAGE_IN_PIPELINE_SERVICE env. variable set as true - Custom Stage executes via ng-manager service and env. & infra. steps are executed. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger uts

**Review by abhinavmittal-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 675 at r2](https://reviewable.io/reviews/harness/harness-core/54111#-NgZFBDvEb0KEtQzM41K:-NgZFBDvEb0KEtQzM41L:b-7qsa40) ([raw file](https://github.com/harness/harness-core/blob/615ee6d87deccd386a6032c685668d3b927b16d4/pipeline-service/config/config.yml#L675)):*
> ```YAML
> publishAdviserEventForCustomAdvisers: ${PUBLISH_ADVISER_EVENT_FOR_CUSTOM_ADVISERS:-false}
> 
> disableCustomStageInPipelineService: false
> ```

Please add variables that would help us override this config.

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/config/config.yml` line 675 at r2](https://reviewable.io/reviews/harness/harness-core/54111#-NgZFBDvEb0KEtQzM41K:-Ngr69KnBP7fuyf-Gej5:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/615ee6d87deccd386a6032c685668d3b927b16d4/pipeline-service/config/config.yml#L675)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Please add variables that would help us override this config.
</blockquote></details>

Done

**Comment by lovish1999** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/54111#-NgrAJqV1_EPgLlp_JrU:-NgrAJqV1_EPgLlp_JrV:b-p2lppf) ([raw file](https://github.com/harness/harness-core/blob/509217721150ee561d1f2985697d581967affa55/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java#L125)):*
> ```Java
> public class PipelineServiceInternalInfoProvider implements PipelineServiceInfoProvider {
>   @Inject InjectorUtils injectorUtils;
>   @Inject PipelineServiceConfiguration pipelineServiceConfiguration;
> ```

dont inject complete configuration, instead expose as named injection in pipelineServiceModule and then inject that named variable here

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 5 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 7 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/54111#-NgrAJqV1_EPgLlp_JrU:-Ngs0GbB5Rx1uqfkCkSu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/509217721150ee561d1f2985697d581967affa55/pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java#L125)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont inject complete configuration, instead expose as named injection in pipelineServiceModule and then inject that named variable here
</blockquote></details>

Done.

**Comment by lovish1999** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/54111#-Ngs6gYn6psasBtUb_gR:-Ngs6gYn6psasBtUb_gS:b-7xfols) ([raw file](https://github.com/harness/harness-core/blob/f4be031106660e69e132d9376f42c7f8581cc91d/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L197)):*
> ```Java
>       @Named("disableCustomStageInPipelineService")
>       public Boolean getDisableCustomStageInPipelineService() {
>         return false;
> ```

return the config map variables and not fixed false

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/54111#-Ngs6gYn6psasBtUb_gR:-NgsK_KfEzNW2KRzsUoM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f4be031106660e69e132d9376f42c7f8581cc91d/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L197)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

return the config map variables and not fixed false
</blockquote></details>

done

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54111#-:-NgsawxO04FfAz_0iSxH:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger review

**Pull request merged**
