### PR TITLE
[feat]: [PL-28284]: Removing Default Role Assignments assigned directly to users at all scopes.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Removing Default Role Assignments assigned directly to users at all scopes.
We are introducing the concept of default User Groups. We have shipped feature where we create default User Groups in each scope (Account, every org and all the projects). 
All users in that scope will be part of these User Groups. Now we will stop assigning any role to any user by default and whatever role customers assign to the default User Group will become the default role for the users in the scope. 
Why this is better:
1. Customers can decide what default they want to assign to their users
2. Change of default role requires just changing the role assigned to default User Group

Currently rolling out behind ACCOUNT_BASIC_ROLE FF.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 14 Issues 
* Vulnerability 5 Vulnerabilities 
 * Code issue 6 Code issues 
* Anti-pattern 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37611)

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/37611#-NC9yKfTAu6YqdNuct5P:-NC9yKfTAu6YqdNuct5Q:b-jesi0d) ([raw file](https://github.com/harness/harness-core/blob/2213ad216dca2f1827ae60d6816eb31b408b4ccc/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java#L75)):*
> ```Java
>     List<AccountDTO> accountDTOS = new ArrayList<>();
>     try {
>       accountDTOS = RestClientUtils.getResponse(accountClient.getAllAccounts());
> ```

Why aren't we getting the distinct accounts from organization collection?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/37611#-NC9yKfTAu6YqdNuct5P:-NCA-CO01nLUEZV35R0J:b-62ymrq) ([raw file](https://github.com/harness/harness-core/blob/2213ad216dca2f1827ae60d6816eb31b408b4ccc/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java#L75)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Why aren't we getting the distinct accounts from organization collection?
</blockquote></details>

organization collection contains stale reference of Account Ids either not existing or Organizations which are soft-deleted.

**Review by gupta-utkarsh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611#-:-NCA0O552IyCpoHN5r_C:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/37611#-NCDeaP_8ZJSgbIT3H93:-NCDeEzMBiwvlt-aXghb:b-poq77a) ([raw file](https://github.com/harness/harness-core/blob/2213ad216dca2f1827ae60d6816eb31b408b4ccc/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java#L41)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.PL)
> public class UserRoleAssignmentRemovalMigration implements NGMigration {
> ```

I think we should make it Background Migration.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/37611#-NCDfFSy8XR4Ask5vZ7l:-NCDfFSz9pc2a_1_YFKi:bx0kbn3) ([raw file](https://github.com/harness/harness-core/blob/2213ad216dca2f1827ae60d6816eb31b408b4ccc/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java#L106)):*
> ```Java
>   }
> 
>   private void deleteAccountScopeRoleAssignments(HashSet<String> accountIds) {
> ```

Make sure indexes are in place and will get used for these queries. Order of fields in WHERE clause is important.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/37611#-NCDeaP_8ZJSgbIT3H93:-NCE0R3J22Mwq8htw5XS:b-f3doip) ([raw file](https://github.com/harness/harness-core/blob/2213ad216dca2f1827ae60d6816eb31b408b4ccc/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java#L41)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we should make it Background Migration.
</blockquote></details>

UserRoleAssignmentRemovalMigration is registered in AccessControlMongoBackgroundMigrationDetails, which is of Background Migration type.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/37611#-NCDfFSy8XR4Ask5vZ7l:-NCLn-hFE9gO9PzXKmID:b-foffwc) ([raw file](https://github.com/harness/harness-core/blob/2213ad216dca2f1827ae60d6816eb31b408b4ccc/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/UserRoleAssignmentRemovalMigration.java#L106)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Make sure indexes are in place and will get used for these queries. Order of fields in WHERE clause is important.
</blockquote></details>

Its using index either roleScopeLevelIndex(roleIdentifier, scopeLevel) in QA or roleIndex(roleIdentifier, scopeIdentifier) in local. Checked using query generated using Query object.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611#-:-NCNjaxC5JuqeSn50_jN:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37611)* status: :shipit: complete! ✓

**Pull request merged**
