### PR TITLE
[feat]:[pl-29319]: Repo and branch listing impl

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added implementations for repoListing and branchListing in execution history page and repoListing in pipeline listing page. Have tested out the all the 3 cases and works successfully.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39553)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyCdOAHNMuFFhnhmr:-NFwyCdOAHNMuFFhnhms:b46mz96) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L38)):*
> ```Java
>   }
> 
>   public List<String> findUniqueEntityGitDetailAttribute(Query query, @NotNull String entityGitDetailAttribute) {
> ```

as discussed, this adds genericness but lacks clarity. We should try and fix it.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39553)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 655 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwy3IQ1ji2Bhs9bI06:-NFwy3IQ1ji2Bhs9bI07:b6k5mi2) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L655)):*
> ```Java
>     CollectionUtils.filter(uniqueRepos, PredicateUtils.notNullPredicate());
>     if (uniqueRepos.size() > MAX_LIST_SIZE) {
>       log.error("The size of unique repositories list is greater than 1000");
> ```

1000, take value from constant
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyINvEi0mVtSLVddj:-NFwyINvEi0mVtSLVddk:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L240)):*
> ```Java
>     CollectionUtils.filter(uniqueRepos, PredicateUtils.notNullPredicate());
>     if (uniqueRepos.size() > MAX_LIST_SIZE) {
>       log.error("The size of unique repositories list is greater than 1000");
> ```

same here
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyHOrAmwgx1XcPFyq:-NFwyHOrAmwgx1XcPFyr:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L252)):*
> ```Java
>     CollectionUtils.filter(uniqueBranches, PredicateUtils.notNullPredicate());
>     if (uniqueBranches.size() > MAX_LIST_SIZE) {
>       log.error("The size of unique branches list is greater than 1000");
> ```

same here

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyuQBBDhQdQA3N7rO:-NFwyuQBBDhQdQA3N7rP:bt0y114) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L119)):*
> ```Java
> 
>   private static final int MAX_LIST_SIZE = 1000;
>   private static final String REPO_SIZE_EXCEPTION = "The size of unique repository list is greater than 1000";
> ```

REPO_LIST_SIZE_EXCEPTION can be better?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 389 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwzrFk3b2rdgyCRXt2:-NFwzrFk3b2rdgyCRXt3:b17osn0) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L389)):*
> ```Java
>       @Parameter(description = PipelineResourceConstants.PIPELINE_ID_LIST_PARAM_MESSAGE) @QueryParam(
>           NGCommonEntityConstants.PIPELINE_KEY) String pipelineIdentifier) {
>     Criteria criteria = pmsExecutionService.formCriteriaForRepoAndBranchFilter(
> ```

it should be formCriteriaForRepoAndBranchListing?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFx-ExU0XiX_QZMRxoM:-NFx-ExU0XiX_QZMRxoN:bo3ngdh) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L253)):*
> ```Java
>     if (uniqueBranches.size() > MAX_LIST_SIZE) {
>       log.error("The size of unique branches list is greater than 1000");
>       throw new InternalServerErrorException(BRANCH_SIZE_EXCEPTION);
> ```

BRANCH_LIST_SIZE_EXCEPTION?

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39553)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39553)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyCdOAHNMuFFhnhmr:-NFx2CsBAa_H6RsdCuI1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryReadHelper.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

as discussed, this adds genericness but lacks clarity. We should try and fix it.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyuQBBDhQdQA3N7rO:-NFx2YfvB3F5QR8Qf2Cf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L119)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

REPO_LIST_SIZE_EXCEPTION can be better?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 655 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwy3IQ1ji2Bhs9bI06:-NFx2Z41-Q5ynexiDApw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L655)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

1000, take value from constant
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 389 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwzrFk3b2rdgyCRXt2:-NFx3-Ff96Ny8S2uewL1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L389)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it should be formCriteriaForRepoAndBranchListing?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyINvEi0mVtSLVddj:-NFx3nmB-ZQvm0haJ8NO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L240)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 252 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFwyHOrAmwgx1XcPFyq:-NFx3man-hC2UtOoW-Fg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L252)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/39553#-NFx-ExU0XiX_QZMRxoM:-NFx3mwfE8fiQ05xiU5U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c7e659354281a525dc65843b9c866db3a637099/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L253)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

BRANCH_LIST_SIZE_EXCEPTION?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39553#-:-NFx4tdy1mbaq56M3dT7:bnfp4nl)* status: 1 change requests. 3. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39553)* status: :shipit: complete! ✓

**Pull request merged**
