### PR TITLE
feat: [CET-1760]: Remove cool off duration logic for Code Errors Noti…

### PR DESCRIPTION
**Pull request by ricksjames**
…fications

## Describe your changes
Error Tracking Notifications - notify in smaller thresholds than every hour

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53299)

### CODE REVIEW

**Comment by ricksjames** [comment]
trigger messagecheck

**Comment by ricksjames** [comment]
trigger messagecheck

**Comment by ricksjames** [comment]
trigger messagecheck

**Comment by ricksjames** [comment]
trigger uts

**Comment by ricksjames** [comment]
trigger ut1

**Review by abeg777 — DISMISSED** [review]

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53299)* status: 2 file(s) to review. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1928 at r1](https://reviewable.io/reviews/harness/harness-core/53299#-NfJr-sn8aJkUF3QXOm1:-NfJr-sn8aJkUF3QXOm2:bsaguxs) ([raw file](https://github.com/harness/harness-core/blob/66d3c0f43369970ac72c9982c738409d0b7f1980/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1928)):*
> ```Java
>     List<String> notificationRuleRefs = monitoredService.getNotificationRuleRefs()
>                                             .stream()
>                                             .filter(ref -> ref.isEligible(clock.instant(), COOL_OFF_DURATION))
> ```

Adding to remove the cool off logic for specific type of notifications will make more sense here rather than spilling it in the main code base.

**Comment by ricksjames** [comment]
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1928 at r1](https://reviewable.io/reviews/harness/harness-core/53299#-NfJr-sn8aJkUF3QXOm1:-NfNU5bg7eDvoOE0G2g_:b-hftqfn) ([raw file](https://github.com/harness/harness-core/blob/66d3c0f43369970ac72c9982c738409d0b7f1980/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1928)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Adding to remove the cool off logic for specific type of notifications will make more sense here rather than spilling it in the main code base.
</blockquote></details>

Done. Note that I used just a foreach because I needed access to both the NotificationRuleRef and NotificationRule at the same time - but return the list of notification rules.

**Comment by ricksjames** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53299)* status: 1. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53299)* status: :shipit: complete! ✓

**Pull request closed without merging**
