### PR TITLE
fix: [DEL-3567]: Update profile for all instances on profile change

### PR DESCRIPTION
**Pull request by mdmilic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)

### CODE REVIEW

**Review by arpit3107 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2518 at r1](https://reviewable.io/reviews/harness/harness-core/31676#-MyrN3jv60XOOMealL89:-MyrN3jv60XOOMealL8A:b-lqg8kq) ([raw file](https://github.com/harness/harness-core/blob/1a14bd052927570ddf1088540f9f1f306317894f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2518)):*
> ```Java
>       }
>       if (ECS.equals(delegate.getDelegateType())) {
>         registeredDelegate = updateEcsDelegateInstance(delegate);
> ```

This method is being called on every heartbeat request. So, you are updating all the ecs instances now. There are few customers who rotate their ecs delegates very frequently. So will it be optimal to update all the ecs delegates at every heartbeat.



_Code quote:_
```Java
registeredDelegate = updateEcsDelegateInstance(delegate);
```

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2518 at r1](https://reviewable.io/reviews/harness/harness-core/31676#-MyrN3jv60XOOMealL89:-MysOPbtB4Ks1D6OEnmq:biellv8) ([raw file](https://github.com/harness/harness-core/blob/1a14bd052927570ddf1088540f9f1f306317894f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2518)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

This method is being called on every heartbeat request. So, you are updating all the ecs instances now. There are few customers who rotate their ecs delegates very frequently. So will it be optimal to update all the ecs delegates at every heartbeat.
</blockquote></details>

That seems excessive. Nothing really changed here though, it's still updating just a single delegate instance. I just broke the bigger method down and renamed it. We should definitely look into optimizing this though, but not as part of this PR I think.

**Comment by mdmilic** [comment]
trigger messagecheck

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 861 at r1](https://reviewable.io/reviews/harness/harness-core/31676#-MyxKbhR8FxxjWNG7PK8:-MyxKbhR8FxxjWNG7PK9:b392ibw) ([raw file](https://github.com/harness/harness-core/blob/1a14bd052927570ddf1088540f9f1f306317894f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L861)):*
> ```Java
>   }
> 
>   private Delegate updateEcsDelegateInstance(Delegate delegate) {
> ```

since this is not only for ECS anymore, we should rename the method

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)* status: 1. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 861 at r1](https://reviewable.io/reviews/harness/harness-core/31676#-MyxKbhR8FxxjWNG7PK8:-MyyEh_b-68u8N9RBoO3:bo5zi8c) ([raw file](https://github.com/harness/harness-core/blob/1a14bd052927570ddf1088540f9f1f306317894f/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L861)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

since this is not only for ECS anymore, we should rename the method
</blockquote></details>

No this one still handles only ECS registration (and I believe heartbeat) and not other delegate types.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)* status: 1. unresolved discussions.

**Review by mdmilic — COMMENTED** [review]
> Dismissed @raghuAtWings from a discussion.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31676)* status: :shipit: complete! ✓

**Pull request merged**
