### PR TITLE
feat: [CDS-77878]: Handling missing null checks for pipeline service.

### PR DESCRIPTION
**Pull request by Aninditaa-ch**
## Describe your changes

**Issue:** Missing null check in BaseCreatorService for pipeline-service. 

**Changes:** In BaseCreatorService, we have added an InvalidRequestException to ensure YamlField is not empty.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52929)

### CODE REVIEW

**Review by shalini-agr — DISMISSED** [review]

**Comment by Aninditaa-ch** [comment]
trigger messagecheck

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52929)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/52929#-NfqcVab7VYWmIuuT5ZQ:-NfqcVac0L8OMexSJPq6:b-2gsh0q) ([raw file](https://github.com/harness/harness-core/blob/075d9e244809d9cd4c94051fee0352fc36cdb13e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java#L102)):*
> ```Java
>       R response = processNodeInternal(metadata, yamlField, request);
> 
>       if (yamlField != null) {
> ```

nit: can we do something like
if (yamlField == null) {
throw exception;
}

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52929)* status: Some of the checks are too old. 1 change requests.

**Comment by Aninditaa-ch** [comment]
trigger messagecheck

**Comment by Aninditaa-ch** [comment]
trigger uts

**Review by Aninditaa-ch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52929)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/52929#-NfqcVab7VYWmIuuT5ZQ:-Nftxbe24XbJH_d-X47T:b-7rl0kd) ([raw file](https://github.com/harness/harness-core/blob/075d9e244809d9cd4c94051fee0352fc36cdb13e/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/creators/BaseCreatorService.java#L102)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: can we do something like
if (yamlField == null) {
throw exception;
}
</blockquote></details>

done

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52929)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by Aninditaa-ch** [comment]
trigger uts

**Comment by Aninditaa-ch** [comment]
trigger ut9

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52929)* status: Some of the checks are too old.

**Comment by Aninditaa-ch** [comment]
trigger review

**Pull request merged**
