### PR TITLE
[feat]: [CI-3462]: Add variable ADDITIONAL_CERTS_PATH on delegate to be used by SCM service

### PR DESCRIPTION
**Pull request by vistaarjuneja**
Context:
Instead of disabling SSL, there is a customer ask to enable SSL on all test connection calls. This PR adds support for a certificate path. All the certs in the path get appended to the system certs for outgoing calls.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)

### CODE REVIEW

**Comment by vistaarjuneja** [comment]
trigger messagecheck

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 881 at r2](https://reviewable.io/reviews/harness/harness-core/30897#-MwVF9AY1jL1EkRgo9X5:-MwVF9AY1jL1EkRgo9X6:bg4zs3h) ([raw file](https://github.com/harness/harness-core/blob/d8b3f72a145c458a28dbfd1d485f16bcf0c0d50b/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L881)):*
> ```Java
>       log.info("Download Url is {}", downloadUrl);
> 
>       String script = "curl $MANAGER_PROXY_CURL -kLO " + downloadUrl + "\n"
> ```

What does k does ?

**Review by vistaarjuneja — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 881 at r2](https://reviewable.io/reviews/harness/harness-core/30897#-MwVF9AY1jL1EkRgo9X5:-MwVFZQN2CVVEqr_f1mw:bqhzv8x) ([raw file](https://github.com/harness/harness-core/blob/d8b3f72a145c458a28dbfd1d485f16bcf0c0d50b/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L881)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

What does k does ?
</blockquote></details>

This is for insecure download. It's present for all the other installs. Context: https://harness.atlassian.net/browse/CI-3533

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)* status: 1 change requests. 1. unresolved discussions.

**Review by DeepakPatankar — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30897)* status: :shipit: complete! ✓

**Pull request merged**
