### PR TITLE
techdebt: [CDS-40269]: Removing FF HELM_STEADY_STATE_CHECK_1_16 from BE.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38955)

### CODE REVIEW

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38955)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1166 at r2](https://reviewable.io/reviews/harness/harness-core/38955#-NFgECFP96zH5bUdzb6O:-NFgECFP96zH5bUdzb6P:bqqyycn) ([raw file](https://github.com/harness/harness-core/blob/3a41ce6a750f9ab1a46d55d39cfb3eb654a9e5ca/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1166)):*
> ```Java
>         encryptedDataDetails, cmdFlags, manifestConfig, appManifestMap, helmVersion, helmCommandFlag);
> 
>     commandRequest.setK8SteadyStateCheckEnabled(
> ```

Don't we have to set this to true? similar to 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
Otherwise, could we have backward compatibility issues?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38955)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1166 at r2](https://reviewable.io/reviews/harness/harness-core/38955#-NFgECFP96zH5bUdzb6O:-NFgFDIF4ySxNFekFEAH:b-kchr8l) ([raw file](https://github.com/harness/harness-core/blob/3a41ce6a750f9ab1a46d55d39cfb3eb654a9e5ca/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1166)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Don't we have to set this to true? similar to 125-cd-nextgen/src/main/java/io/harness/cdng/helm/HelmDeployStep.java
Otherwise, could we have backward compatibility issues?
</blockquote></details>

If we remove this field then it would cause cause backward compatibility issues. If we set it to false then the old delegate then it will always treat it as if feature flag is disabled.

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38955)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1166 at r2](https://reviewable.io/reviews/harness/harness-core/38955#-NFgECFP96zH5bUdzb6O:-NFgJSUE5JtLhUukhmMa:b-unwdft) ([raw file](https://github.com/harness/harness-core/blob/3a41ce6a750f9ab1a46d55d39cfb3eb654a9e5ca/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1166)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

If we remove this field then it would cause cause backward compatibility issues. If we set it to false will be false then the old delegate then it will always treat it as if feature flag is disabled.
</blockquote></details>

Ok got it keeping the behaviour same in both CG and NG.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38955)* status: :shipit: complete! ✓

**Pull request merged**
