### PR TITLE
fix: [DEL-3921]: APIs to return current watcher/delegate version for given accountId

### PR DESCRIPTION
**Pull request by gaurav-jain1**
Summary:
This change introduces 2 APIs for returning active delegate and watcher version respectively.
These API will get used by start.sh script to figure out current watcher version and download it from corresponding location.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32467)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32467)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32467#-N0lurw9EnKSWu4930hb:-N0lurw9EnKSWu4930hc:b-v9t1z4) ([raw file](https://github.com/harness/harness-core/blob/2100794079a662a5ae66759af7122b22c87288df/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L30)):*
> ```Java
> @Path("/version")
> @Produces(MediaType.APPLICATION_JSON)
> @PublicApi
> ```

I don't think we can have this as a public API. That means that anyone can just find anyones version of delegate/watcher. Not super secret, but we shouldn't leak any customer information. 
I think you should put `@DelegateAuth` there instead
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32467#-N0luDGk4Zy8BoBWRO7U:-N0luDGk4Zy8BoBWRO7V:bvaep5r) ([raw file](https://github.com/harness/harness-core/blob/2100794079a662a5ae66759af7122b22c87288df/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L32)):*
> ```Java
> @PublicApi
> public class DelegateVersionInfoResource {
>   @Inject private software.wings.service.intfc.AccountService accountService;
> ```

Don't use field injection, use constructor injection instead (and make the field `final`). Here's example how to do it
https://harness.atlassian.net/wiki/spaces/~686770990/pages/1889075203/Constructor+Injection
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/32467#-N0lvPs69MzPipbYOb16:-N0lvPs69MzPipbYOb17:b9ho3e4) ([raw file](https://github.com/harness/harness-core/blob/2100794079a662a5ae66759af7122b22c87288df/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L51)):*
> ```Java
>       return watcherVersion.get(0);
>     }
>     return null;
> ```

Don't return null. Better throw exception (500 or 404 is fine depending on why we don't have a version)

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32467)* status: Some of the checks are too old. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/32467#-N0lurw9EnKSWu4930hb:-N0nt-825RvICJU1rbJ2:bt784x8) ([raw file](https://github.com/harness/harness-core/blob/2100794079a662a5ae66759af7122b22c87288df/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L30)):*
> d injection, use constructor injection instead (and make 
Watcher version gets pulled in start.sh. we don't have secret build up there. Is there a way we can have secret in .sh file ?
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/32467#-N0luDGk4Zy8BoBWRO7U:-N0ntOyUE5dqvH4Kix9K:b2nhb2c) ([raw file](https://github.com/harness/harness-core/blob/2100794079a662a5ae66759af7122b22c87288df/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L32)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Don't use field injection, use constructor injection instead (and make the field `final`). Here's example how to do it
https://harness.atlassian.net/wiki/spaces/~686770990/pages/1889075203/Constructor+Injection
</blockquote></details>

Ack
___
*[`400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/32467#-N0lvPs69MzPipbYOb16:-N0ntNuVBEUesV1K0Oms:b-im6hrn) ([raw file](https://github.com/harness/harness-core/blob/2100794079a662a5ae66759af7122b22c87288df/400-rest/src/main/java/software/wings/resources/DelegateVersionInfoResource.java#L51)):*
> eturn null. Better
Ack

**Review by mdmilic — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32467)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger compile

**Comment by gaurav-jain1** [comment]
trigger ti4

**Comment by gaurav-jain1** [comment]
trigger compile

**Comment by gaurav-jain1** [comment]
trigger checkstyle
trigger codebasehash

**Comment by gaurav-jain1** [comment]
trigger checkstyle

**Comment by gaurav-jain1** [comment]
trigger ft1

**Comment by gaurav-jain1** [comment]
trigger ft2

**Comment by gaurav-jain1** [comment]
trigger pmd

**Review by arpit3107 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32467)* status: :shipit: complete! ✓

**Pull request merged**
