### PR TITLE
[fix]: [CCM-11309]: Added Invalid parent check while budget/budget group creation

### PR DESCRIPTION
**Pull request by svmav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44140)

### CODE REVIEW

**Review by iamanmolm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44140)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`374-ceng-graphql/src/main/java/io/harness/ccm/graphql/core/budget/BudgetServiceImpl.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/44140#-NOn9Alp1UtAjhhW3iQr:-NOn9Alp1UtAjhhW3iQs:b-8egzhk) ([raw file](https://github.com/harness/harness-core/blob/9a3fda5425531786b56e833b8f63f92eeaec5f30/374-ceng-graphql/src/main/java/io/harness/ccm/graphql/core/budget/BudgetServiceImpl.java#L176)):*
> ```Java
> 
>   private static void validateParent(Budget budget) {
>     List<BudgetGroup> existingBudgetGroups = budgetGroupDao.list(budget.getAccountId());
> ```

Instead of using list call, why don't we just simply use get(budget.getParentBudgetGroupId(), budget.getAccountId()) and validate directly if we got a budgetGroup or not. Then we don't need to stream any list.
___
*[`490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/dao/BudgetGroupDao.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/44140#-NOn9e2V0jfO_Y83zlTE:-NOn9e2V0jfO_Y83zlTF:bjakgxz) ([raw file](https://github.com/harness/harness-core/blob/9a3fda5425531786b56e833b8f63f92eeaec5f30/490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/dao/BudgetGroupDao.java#L136)):*
> ```Java
>   }
> 
>   public List<BudgetGroup> list(String accountId) {
> ```

We wouldn't need to introduce new list call, if we simply use get() instead of this.

**Review by svmav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44140)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`374-ceng-graphql/src/main/java/io/harness/ccm/graphql/core/budget/BudgetServiceImpl.java` line 176 at r1](https://reviewable.io/reviews/harness/harness-core/44140#-NOn9Alp1UtAjhhW3iQr:-NOnG801164k14UxI1Ay:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a3fda5425531786b56e833b8f63f92eeaec5f30/374-ceng-graphql/src/main/java/io/harness/ccm/graphql/core/budget/BudgetServiceImpl.java#L176)):*
<details><summary><i>Previously, iamanmolm (Anmol Maheshwari) wrote…</i></summary><blockquote>

Instead of using list call, why don't we just simply use get(budget.getParentBudgetGroupId(), budget.getAccountId()) and validate directly if we got a budgetGroup or not. Then we don't need to stream any list.
</blockquote></details>

Done.
___
*[`490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/dao/BudgetGroupDao.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/44140#-NOn9e2V0jfO_Y83zlTE:-NOnG90QE8Q3Lyeukrbk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a3fda5425531786b56e833b8f63f92eeaec5f30/490-ce-commons/src/main/java/io/harness/ccm/budgetGroup/dao/BudgetGroupDao.java#L136)):*
<details><summary><i>Previously, iamanmolm (Anmol Maheshwari) wrote…</i></summary><blockquote>

We wouldn't need to introduce new list call, if we simply use get() instead of this.
</blockquote></details>

Done.

**Comment by svmav** [comment]
trigger messagecheck

**Review by iamanmolm — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44140)* status: 4 file(s) to review.

**Review by iamanmolm — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44140)* status: :shipit: complete! ✓

**Pull request merged**
