### PR TITLE
fix: [PL-29109]: Added null checks for RoleAssignmentDTO

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added the missing null and empty checks for RoleAssignmentDTO
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39682)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39682)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTO.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/39682#-NGGF1gV9PaXMHGHBcjJ:-NGGF1gV9PaXMHGHBcjK:bj2uyr3) ([raw file](https://github.com/harness/harness-core/blob/e771740f3d2c56e9b674c2165cf232511eb727ec/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTO.java#L46)):*
> ```Java
>   public static final String MODEL_NAME = "RoleAssignment";
> 
>   @NotEmpty final String identifier;
> ```

identifier would be null/empty when creating RoleAssignment.



_Code quote:_
```Java
identifier
```

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39682)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTO.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/39682#-NGGF1gV9PaXMHGHBcjJ:-NGGGbYxBp3NttdlOb-w:b-ew33g) ([raw file](https://github.com/harness/harness-core/blob/e771740f3d2c56e9b674c2165cf232511eb727ec/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentDTO.java#L46)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

identifier would be null/empty when creating RoleAssignment.
</blockquote></details>

Removed the check

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39682#-:-NGGGpgb7YMy-43ywa2E:bnfp4nl)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39682)* status: 1. unresolved discussions.

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39682)* status: :shipit: complete! ✓

**Pull request merged**
