### PR TITLE
feat: [COMP-3490]: Implement security step as plugin compatible

### PR DESCRIPTION
**Pull request by r0610205**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30541)

### CODE REVIEW

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30541#-:-Mv9fQZ00qUnTLpfKalg:bnfp4nl)* status: :shipit: complete! ✓

**Review by williamwissemann — DISMISSED** [review]
LGTM

**Review by williamwissemann — DISMISSED** [review]
> Reviewed 22 of 33 files at r1, 17 of 20 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30541)* status: :shipit: complete! ✓

**Comment by r0610205** [comment]
@raghuAtWings Re: codebasehash checklist - this is new task type

**Review by williamwissemann — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30541)* status: :shipit: complete! ✓

**Review by williamwissemann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30541)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 22 of 33 files at r1, 17 of 20 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30541)* status: :shipit: complete! ✓

**Pull request merged**
