### PR TITLE
feat: [CDS-40926]: Record instance sync metrics

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36191)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36191)

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36191)* status: 15 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java` line 829 at r2](https://reviewable.io/reviews/harness/harness-core/36191#-N95utjiBFmZhUmb-d_F:-N95utjiBFmZhUmb-d_G:bmlbzhy) ([raw file](https://github.com/harness/harness-core/blob/11a4cfdf55a0b68fed77f52819090d6f4a302ad1/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java#L829)):*
> ```Java
>                                                 .status(status)
>                                                 .build();
>     instanceSyncMonitoringService.recordMetrics(instanceSyncMetric);
> ```

move this to `InstanceSyncMonitoringService`



_Code quote:_
```Java
  private void recordMetrics(
      String metricName, String accountId, String appId, String deploymentType, String status, long duration) {
    InstanceSyncMetric instanceSyncMetric = InstanceSyncMetric.builder()
                                                .metricName(metricName)
                                                .accountId(accountId)
                                                .appId(appId)
                                                .isNg(false)
                                                .deploymentType(deploymentType)
                                                .status(status)
                                                .build();
    instanceSyncMonitoringService.recordMetrics(instanceSyncMetric);
    InstanceSyncMetric instanceSyncDurationMetric = InstanceSyncMetric.builder()
                                                        .metricName(INSTANCE_SYNC_DURATION_METRIC_NAME)
                                                        .accountId(accountId)
                                                        .appId(appId)
                                                        .isNg(false)
                                                        .deploymentType(deploymentType)
                                                        .status(status)
                                                        .build();
    instanceSyncMonitoringService.recordMetricsDuration(instanceSyncDurationMetric, Duration.ofMillis(duration));
  }
```
___
*[`970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/model/InstanceSyncMetricContext.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/36191#-N95uoyJ4j9cDeDmAc9m:-N95uoyJ4j9cDeDmAc9n:b-ye7s71) ([raw file](https://github.com/harness/harness-core/blob/11a4cfdf55a0b68fed77f52819090d6f4a302ad1/970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/model/InstanceSyncMetricContext.java#L21)):*
> ```Java
>     put("projectId", instanceSyncMetric.getProjectId());
>     put("deploymentType", instanceSyncMetric.getDeploymentType());
>     put("status", instanceSyncMetric.getStatus());
> ```

'isNg' parameter is missing here.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36191)* status: 15 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java` line 829 at r2](https://reviewable.io/reviews/harness/harness-core/36191#-N95utjiBFmZhUmb-d_F:-N96qP_95ltkn2QigQCW:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/11a4cfdf55a0b68fed77f52819090d6f4a302ad1/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java#L829)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

move this to `InstanceSyncMonitoringService`
</blockquote></details>

Done
___
*[`970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/model/InstanceSyncMetricContext.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/36191#-N95uoyJ4j9cDeDmAc9m:-N96qN28-2LAYp96FW-2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/11a4cfdf55a0b68fed77f52819090d6f4a302ad1/970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/model/InstanceSyncMetricContext.java#L21)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

'isNg' parameter is missing here.
</blockquote></details>

Done

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36191)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java` line 803 at r3](https://reviewable.io/reviews/harness/harness-core/36191#-N96xfwG1SOd5SlGH13X:-N96xfwHD_RxKKhIK0dn:bnsz2u3) ([raw file](https://github.com/harness/harness-core/blob/ea67419bbb920607d3cc88287a9cabeb3cf6d43c/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java#L803)):*
> ```Java
>           buildMetricDetails(infrastructureMapping.getAccountId(), infrastructureMapping.getAppId(),
>               infrastructureMapping.getDeploymentType(), status.isSuccess() ? SUCCESS_STATUS : FAILED_STATUS);
>       instanceSyncMonitoringService.recordMetrics(metricDetails, true, System.currentTimeMillis() - startTime);
> ```

this is for perpetual task Instance Sync. The param value should be false.



_Code quote:_
```Java
true
```
___
*[`970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/service/InstanceSyncMonitoringServiceImpl.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/36191#-N96y1rkEU0L2lotx1pJ:-N96y1rkEU0L2lotx1pK:bc6wjc) ([raw file](https://github.com/harness/harness-core/blob/ea67419bbb920607d3cc88287a9cabeb3cf6d43c/970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/service/InstanceSyncMonitoringServiceImpl.java#L41)):*
> ```Java
> 
>   private void recordMetric(InstanceSyncMetricDetails instanceSyncMetricDetails, String metricName) {
>     try (io.harness.instancesyncmonitoring.model.InstanceSyncMetricContext ignore =
> ```

remove the package names 



_Code quote:_
```Java
io.harness.instancesyncmonitoring.model.
```

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36191)* status: :shipit: complete! ✓

**Pull request merged**
