### PR TITLE
[feat]: [PIE-9192]: Fill pipeline rollback graph info into rollbackGraph field

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/45641#-NRWK2oBBHFASMRaL1QN:-NRWK2oBBHFASMRaL1QO:benbb8f) ([raw file](https://github.com/harness/harness-core/blob/342b443c1f8e2daf53c90f1a756d549a99cc4ef9/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L146)):*
> ```Java
>   Boolean notifyOnlyMe;
> 
>   ExecutionMode executionMode; // this is used to filter out rollback mode executions from executions list API
> ```

Can we add this in executionMetadata instead?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/45641#-NRWK2oBBHFASMRaL1QN:-NRWNCKh8m5vtByZpYHD:b1vssen) ([raw file](https://github.com/harness/harness-core/blob/342b443c1f8e2daf53c90f1a756d549a99cc4ef9/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L146)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add this in executionMetadata instead?
</blockquote></details>

the execution mode field is already there in execution metadata, but execution metadata is not there in exec summary entity, and we don't fetch execution metadata when getting list response. So we'll need the field in exec summary entity

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 9 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/45641#-NRWK2oBBHFASMRaL1QN:-NRWOuoY91aJDqA4OKP-:b-45ehtr) ([raw file](https://github.com/harness/harness-core/blob/342b443c1f8e2daf53c90f1a756d549a99cc4ef9/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java#L146)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

the execution mode field is already there in execution metadata, but execution metadata is not there in exec summary entity, and we don't fetch execution metadata when getting list response. So we'll need the field in exec summary entity
</blockquote></details>

Added a pojo for extensibility though

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 3 of 4 files at r2, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/RollbackExecutionInfo.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/45641#-NRXN8tO6oYlkt7U-B2W:-NRXN8tO6oYlkt7U-B2X:b-3r1o5k) ([raw file](https://github.com/harness/harness-core/blob/b0f14c1f76965c7920dccb88aae02da6daa51961/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/RollbackExecutionInfo.java#L19)):*
> ```Java
> @Value
> @Builder
> public class RollbackExecutionInfo {
> ```

nit: team annotation
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 579 at r5](https://reviewable.io/reviews/harness/harness-core/45641#-NRXNv-n6dKnkfKLl6l9:-NRXNv-n6dKnkfKLl6lA:bakpw3i) ([raw file](https://github.com/harness/harness-core/blob/b0f14c1f76965c7920dccb88aae02da6daa51961/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L579)):*
> ```Java
>             .getResponseDTOWithChildGraph(accountId, childStageNodeId, executionSummaryEntity, entityGitDetails,
>                 nodeExecution, stageNodeExecutionId)
>             .withRollbackGraph(rollbackGraph);
> ```

Why we need to use with here, and not add this details in -> PipelineStageHelper.getExecutionDetailDTO
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/PipelineExecutionDetailDTO.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/45641#-NRXO1OaBdQWbXRl1LKh:-NRXO1OaBdQWbXRl1LKi:bbile16) ([raw file](https://github.com/harness/harness-core/blob/b0f14c1f76965c7920dccb88aae02da6daa51961/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/PipelineExecutionDetailDTO.java#L38)):*
> ```Java
>   ChildExecutionDetailDTO childGraph;
>   @Schema(hidden = true, description = "Execution details of the Rollback Stages executed under Pipeline Rollback")
>   @With
> ```

we should not recommend this unless abs required

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/RollbackExecutionInfo.java` line 19 at r5](https://reviewable.io/reviews/harness/harness-core/45641#-NRXN8tO6oYlkt7U-B2W:-NRXUOaGET2vln_-O6eb:b-qglexu) ([raw file](https://github.com/harness/harness-core/blob/b0f14c1f76965c7920dccb88aae02da6daa51961/pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/RollbackExecutionInfo.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: team annotation
</blockquote></details>

it is there
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 579 at r5](https://reviewable.io/reviews/harness/harness-core/45641#-NRXNv-n6dKnkfKLl6l9:-NRXURO-6j1VXp4UFPI2:bqm4v69) ([raw file](https://github.com/harness/harness-core/blob/b0f14c1f76965c7920dccb88aae02da6daa51961/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L579)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why we need to use with here, and not add this details in -> PipelineStageHelper.getExecutionDetailDTO
</blockquote></details>

I don't think we should move rollback graph to pipeline stage helper, that makes the helper dependant on rollback graph when they should ideally be independent. Imo it makes sense to use @With here

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/PipelineExecutionDetailDTO.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/45641#-NRXO1OaBdQWbXRl1LKh:-NRaC2Ti9gt9xaP6CHtU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0f14c1f76965c7920dccb88aae02da6daa51961/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto/PipelineExecutionDetailDTO.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not recommend this unless abs required
</blockquote></details>

Done.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 4 files at r2, 1 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45641)* status: :shipit: complete! ✓

**Pull request merged**
