### PR TITLE
feat: [CDS-40780]: [INFRASTRUCTURE] Improve YAML structure for PDC/Az…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…ure/AWS infrastructure

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36046)

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 21 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046#-:-NAKOUrD-Xxy5sFRvDaI:bnfp4nl)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 12 of 22 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger ti4

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 5 of 17 files at r4, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)* status: :shipit: complete! ✓

**Review by ivan-83 — DISMISSED** [review]
There are some comments related to renaming. Let's merge this unblock UI and address renaming in the next PR. 

> Reviewed 1 of 10 files at r3, 5 of 17 files at r4, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046#-:-NAaKEra2d1-UU6bVkgr:b3rvq54)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 219 at r6](https://reviewable.io/reviews/harness/harness-core/36046#-NAaIfm91sLd3p_Xectp:-NAaIfmB7lTVMA2BuB67:b-x312ub) ([raw file](https://github.com/harness/harness-core/blob/b64a4ff0de373ade0d2765f1a17ffde553f1513a/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L219)):*
> ```Java
>   }
> 
>   private HostFilterOutcome getHostFilterOutcome(HostFilter hostFilter) {
> ```

HostFilterOutcome should be renamed, this is not the outcome. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 220 at r6](https://reviewable.io/reviews/harness/harness-core/36046#-NAaIqsO4FbxE9emxl6D:-NAaIqsP5yP8rqj36HZ-:b-l1pd6t) ([raw file](https://github.com/harness/harness-core/blob/b64a4ff0de373ade0d2765f1a17ffde553f1513a/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L220)):*
> ```Java
> 
>   private HostFilterOutcome getHostFilterOutcome(HostFilter hostFilter) {
>     if (hostFilter == null) {
> ```

The default type should be ALL and here we have to throw an exception if one of type is not set. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 223 at r6](https://reviewable.io/reviews/harness/harness-core/36046#-NAaJ0QW9xYDlt6gRuvD:-NAaJ0QW9xYDlt6gRuvE:bi6s4tq) ([raw file](https://github.com/harness/harness-core/blob/b64a4ff0de373ade0d2765f1a17ffde553f1513a/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L223)):*
> ```Java
>       return HostFilterOutcome.builder().type(HostFilterType.ALL).build();
>     }
>     Filter spec = hostFilter.getSpec();
> ```

Filter should be HostFilterSpec
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 235 at r6](https://reviewable.io/reviews/harness/harness-core/36046#-NAaJFjdCmn3gZaryMq5:-NAaJFjdCmn3gZaryMq6:b-md87m9) ([raw file](https://github.com/harness/harness-core/blob/b64a4ff0de373ade0d2765f1a17ffde553f1513a/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L235)):*
> ```Java
>       filterOutcome = AllHostsFilterOutcome.builder().build();
>     }
>     return HostFilterOutcome.builder().spec(filterOutcome).type(type).build();
> ```

Again, filterOutcome shouldn't be null, it should be ALL by default for select preconfigured hosts and specify hosts here.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/FilterOutcome.java` line 16 at r6](https://reviewable.io/reviews/harness/harness-core/36046#-NAaK2qH2KkuEu4JuTZX:-NAaK2qH2KkuEu4JuTZY:beqmmmd) ([raw file](https://github.com/harness/harness-core/blob/b64a4ff0de373ade0d2765f1a17ffde553f1513a/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/beans/FilterOutcome.java#L16)):*
> ```Java
> 
> @OwnedBy(CDP)
> public interface FilterOutcome {
> ```

More specific name.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 25 of 25 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)* status: 1 file(s) to review. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 247 at r8](https://reviewable.io/reviews/harness/harness-core/36046#-NAsW4Kh3azZk98n0Txj:-NAsW4Kh3azZk98n0Txk:b629obf) ([raw file](https://github.com/harness/harness-core/blob/e196a210774f7ddd2fe3a4d6066b4309d28c32a8/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L247)):*
> ```Java
>       return HostFilterDTO.builder().spec(AllHostsFilterDTO.builder().build()).type(type).build();
>     } else {
>       throw new InvalidArgumentsException(format("Not supported host filter type: %s", type));
> ```

minor: can we have the message as: `Unuspported host filter type found` instead

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 7 files at r7, 24 of 25 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 247 at r8](https://reviewable.io/reviews/harness/harness-core/36046#-NAsW4Kh3azZk98n0Txj:-NAsjBZ-CTKV4JOuEyt0:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e196a210774f7ddd2fe3a4d6066b4309d28c32a8/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L247)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

minor: can we have the message as: `Unuspported host filter type found` instead
</blockquote></details>

Done

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 22 files at r1, 1 of 7 files at r7, 24 of 25 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36046)* status: :shipit: complete! ✓

**Pull request merged**
