### PR TITLE
fix: [PL-22557]: github connector error handling from manager 

### PR DESCRIPTION
**Pull request by pbarapatre10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32208)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32208)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java, line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/32208#-N-Y49d7BMMfZU8VJSae:-N-Y49d8-cpEAywbuGC2:b-u6vtgc) ([raw file](https://github.com/harness/harness-core/blob/5939786aedfd3259924e69b7fbc810fe4ef48703/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1694)):*
> ```Java
>         exception -> exceptionHandlerMapBinder.addBinding(exception).to(CVConnectorExceptionHandler.class));
>     JGitExceptionHandler.exceptions().forEach(
>         exception -> exceptionHandlerMapBinder.addBinding(exception).to(JGitExceptionHandler.class));
> ```

Is this exception handling not at all required on delegate tasks? It should be ensured that no tasks expect this error handling otherwise it will break for them
___
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/32208#-N-Y4N4g7255eHrNcIrs:-N-Y4N4g7255eHrNcIrt:bx19m37) ([raw file](https://github.com/harness/harness-core/blob/5939786aedfd3259924e69b7fbc810fe4ef48703/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L71)):*
> ```Java
>           gitConnector, scmConnector, accountIdentifier, sshSessionConfig);
>     } catch (Exception e) {
>       return ConnectorValidationResult.builder()
> ```

It should be ensured that all consumers for this validate method are able to handle the error after this change. Its a contract change clearly. Please check APIs as well.

**Comment by pbarapatre10** [comment]
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java, line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/32208#-N-Y49d7BMMfZU8VJSae:-N-Y6xlK8-PF1usW5Dxd:bgnlaoy) ([raw file](https://github.com/harness/harness-core/blob/5939786aedfd3259924e69b7fbc810fe4ef48703/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1694)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is this exception handling not at all required on delegate tasks? It should be ensured that no tasks expect this error handling otherwise it will break for them
</blockquote></details>

Since we moved this from `DelegateModule` to the base `ExceptionModule` I believe this ExceptionHandler will continue to work, since the same ExceptionHandler is able to handle errors for delegate-module & ng-module and return the correct error response.

**Comment by pbarapatre10** [comment]
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/32208#-N-Y4N4g7255eHrNcIrs:-N-Y7SQL0I8e0uy1YT1M:b-rofgzf) ([raw file](https://github.com/harness/harness-core/blob/5939786aedfd3259924e69b7fbc810fe4ef48703/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It should be ensured that all consumers for this validate method are able to handle the error after this change. Its a contract change clearly. Please check APIs as well.
</blockquote></details>

Yes, the API contract is changing. But we discussed in last meeting that for all connector API response we will send actual ERROR status and not a SUCCESS status, and to not break the contract the /v2/ would need to be introduced, but that also we discussed in our last meeting to avoid additional complexity of replicating code, we for now decided to not introduce /v2 & that will be handled as a part of separate error handling framework work later.

**Comment by mohitg0795** [comment]
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java, line 1694 at r1](https://reviewable.io/reviews/harness/harness-core/32208#-N-Y49d7BMMfZU8VJSae:-N-YAT9F14KwvmpLa8jA:b642uvs) ([raw file](https://github.com/harness/harness-core/blob/5939786aedfd3259924e69b7fbc810fe4ef48703/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateModule.java#L1694)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Since we moved this from `DelegateModule` to the base `ExceptionModule` I believe this ExceptionHandler will continue to work, since the same ExceptionHandler is able to handle errors for delegate-module & ng-module and return the correct error response. 
</blockquote></details>

Got it, I assume anyways your test cases for this PR will include failures cases of delegate tasks as well, so it should get verified.

**Comment by mohitg0795** [comment]
*[932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java, line 71 at r1](https://reviewable.io/reviews/harness/harness-core/32208#-N-Y4N4g7255eHrNcIrs:-N-YAbuR-2Wmg8O1pB76:b-lvkeq9) ([raw file](https://github.com/harness/harness-core/blob/5939786aedfd3259924e69b7fbc810fe4ef48703/932-connector-task/src/main/java/io/harness/connector/task/git/GitCommandTaskHandler.java#L71)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Yes, the API contract is changing. But we discussed in last meeting that for all connector API response we will send actual ERROR status and not a SUCCESS status, and to not break the contract the /v2/ would need to be introduced, but that also we discussed in our last meeting to avoid additional complexity of replicating code, we for now decided to not introduce /v2 & that will be handled as a part of separate error handling framework work later.
</blockquote></details>

Agreed, please take explicit approval from either of @ashishsanodia-harness or @piyush-harness on the same.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32208#-:-N-YAnTf-VEqNZyOoSnO:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32208)* status: Some of the checks are too old.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32208)* status: Some of the checks are too old.

**Review by ashishsanodia-harness — APPROVED** [review]

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32208)* status: 1 file(s) to review.

**Pull request merged**
