### PR TITLE
[fix]: [CDS-3002]: bind k8s manifest fetch with values fetch

### PR DESCRIPTION
**Pull request by tchaurasiya**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30949)

i) We are utilising same delegate task in k8s, thats was written for helm (CUSTOM_MANIFEST_FETCH_TASK), with some tweaks.
ii) In AbstractK8sState, we are choosing new task type (CUSTOM_MANIFEST_FETCH_TASK) if ff is on, else we are using same old task type CUSTOM_MANIFEST_VALUES_FETCH_TASK.
iii) Two conditional tasktype are present, just to add backward compatibility if something goes your.
iv) When we do this feature GA, our goal is to remove task CUSTOM_MANIFEST_VALUES_FETCH_TASK totally.
v) FF : BIND_CUSTOM_VALUE_AND_MANIFEST_FETCH_TASK

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30949)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 384 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwfUa-m0k7PLoL1kYNV:-MwfUa-n2pNIhrtAj9e0:b-63pu96) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L384)):*
> ```Java
>       CustomManifestSource customManifestSource = delegateManifestConfig.getCustomManifestSource();
>       handleIncorrectConfiguration(delegateManifestConfig);
>       helmTaskHelper.downloadAndUnzipCustomSourceManifestFiles(
> ```

nit: we should move this methods to some independent of helm and K8s class, at least semantically this will be right
___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 390 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwfW8GB8uksdphe28Sn:-MwfV_ld5PcdDDVDDEaH:b-a9xn4a) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L390)):*
> ```Java
>         throw new InvalidRequestException("No manifest files found under working directory", USER);
>       }
>       File manifestDirectory = file.listFiles(pathname -> !file.isHidden())[0];
> ```

If there will be multiple directories in manifest will we take only first non hidden one? Or is that we zip some directory and expect that only that directory to be available? 
___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 391 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwfXTHs8FVQRIjszhjA:-MwfXTHtBNmtGZI3A8T7:bg76wty) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L391)):*
> ```Java
>       }
>       File manifestDirectory = file.listFiles(pathname -> !file.isHidden())[0];
>       copyManifestFilesToWorkingDir(manifestDirectory, new File(manifestFilesDirectory));
> ```

Why we can't unzip it directly to manifestFilesDirectory and avoid all of this confusion around workingDirectory, manifestDirectory and manifestFilesDirectory. I have the feeling that is just the same thing 
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 456 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwaXzvG6Izwckv0Eh7o:-MwaXzvG6Izwckv0Eh7p:b-ijxi69) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L456)):*
> ```Java
>       }
> 
>       if (customSourceConfig != null && customSourceConfig.getScript() == null) {
> ```

Script can be null in the case when we just want to copy file from delegate without any script processing. At least it was supposed to be supported by design

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 456 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwaXzvG6Izwckv0Eh7o:-MxXvDCo7R1755iTMWEK:b-ee6tix) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L456)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Script can be null in the case when we just want to copy file from delegate without any script processing. At least it was supposed to be supported by design
</blockquote></details>

Done.Thanks for pointing out.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 390 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwfW8GB8uksdphe28Sn:-MxXvIxVE7UUi0KM5xPo:b-dk2zfd) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L390)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If there will be multiple directories in manifest will we take only first non hidden one? Or is that we zip some directory and expect that only that directory to be available? 
</blockquote></details>

 discussed offline.

**Comment by tchaurasiya** [comment]
___
*[400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java, line 391 at r1](https://reviewable.io/reviews/harness/harness-core/30949#-MwfXTHs8FVQRIjszhjA:-MxXvPlN2L7m2_Bi2zRH:b40ff9h) ([raw file](https://github.com/harness/harness-core/blob/a1d37ff7e60a7e573d4fb5157ade187335256d3e/400-rest/src/main/java/software/wings/delegatetasks/k8s/K8sTaskHelper.java#L391)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why we can't unzip it directly to manifestFilesDirectory and avoid all of this confusion around workingDirectory, manifestDirectory and manifestFilesDirectory. I have the feeling that is just the same thing 
</blockquote></details>

Done. discussed offline.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30949)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30949)* status: :shipit: complete! ✓

**Pull request merged**
