### PR TITLE
feat: [DEl-2806]: Create perpetual task metrics

### PR DESCRIPTION
**Pull request by Xin-Harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30501)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30501)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java, line 338 at r2](https://reviewable.io/reviews/harness/harness-core/30501#-Mv5QAlm-LPtw7GLbkGh:-Mv5QAlm-LPtw7GLbkGi:b-xq56gs) ([raw file](https://github.com/harness/harness-core/blob/c496bc7a52019306ef037624f9d13fe1384f92ea/400-rest/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceImpl.java#L338)):*
> ```Java
>     perpetualTaskRecordDao.updateTaskUnassignedReason(taskId, reason, assignTryCount);
> 
>     PerpetualTaskRecord perpetualTaskRecord = perpetualTaskRecordDao.getTask(taskId);
> ```

shouldn't this happen when the perpetual task gets unassigned and not when reason is updated

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30501)* status: 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30501)* status: :shipit: complete! ✓

**Comment by Xin-Harness** [comment]
trigger tin4

**Comment by Xin-Harness** [comment]
trigger TIbootstrap-tin0

**Review by raghuAtWings — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30501#-:-Mv5r3CxEMXHZ_h6DyZt:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
