### PR TITLE
[feat]: [PL-28466]: moved ng-manager call from login flow in manager to audit event handler

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
moved ng-manager call from login flow in manager to audit event handler

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37863)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 2 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37863)

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37863#-:-NCf4dEoDVuDNvosq17d:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/37863#-NCjfHhyDobx7UKoa1tV:-NCjfHhyDobx7UKoa1tW:be8rctr) ([raw file](https://github.com/harness/harness-core/blob/f8670eea164da8b444503fd7ffb7337034add6c9/400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java#L81)):*
> ```Java
> 
>     try {
>       if (isUserInScope(userId, accountIdentifier)) {
> ```

this method name isn't clear, what does it mean?

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/37863#-NCjfL8F-dP0AzqW_xVL:-NCjfL8F-dP0AzqW_xVM:bcml1fb) ([raw file](https://github.com/harness/harness-core/blob/f8670eea164da8b444503fd7ffb7337034add6c9/400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java#L90)):*
> ```Java
>       log.warn("Skipping audit for account {} and userId {} due to exception: ", accountIdentifier, userId, ex);
>     }
>     return false;
> ```

will this be always false? just checking

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37863)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/37863#-NCjfHhyDobx7UKoa1tV:-NCji_imEh_Ysuk--m5e:bwv602q) ([raw file](https://github.com/harness/harness-core/blob/f8670eea164da8b444503fd7ffb7337034add6c9/400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java#L81)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this method name isn't clear, what does it mean?
</blockquote></details>

this method checks whether the user is part of NG user list or not, we have not changed this name, its same.
___
*[`400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/37863#-NCjfL8F-dP0AzqW_xVL:-NCjiuoZ7QUjXnWZgZfr:bozli4a) ([raw file](https://github.com/harness/harness-core/blob/f8670eea164da8b444503fd7ffb7337034add6c9/400-rest/src/main/java/software/wings/core/outbox/UserEventHandler.java#L90)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

will this be always false? just checking
</blockquote></details>

it will be false in 2 cases. 1. when user is not present in NG user list. 2. an exception is thrown e.g. is ng-manager is down.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37863)* status: :shipit: complete! ✓

**Pull request merged**
