### PR TITLE
fix: [PL-21988]: Try to unlock infinite lock even when expired

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/29977)

### CODE REVIEW

**Review by vikas-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29977)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29977#-:-MtlCfhz0O-R-EkzNLw0:bnfp4nl)* status: 4 file(s) to review.

**Comment by gupta-utkarsh** [comment]
trigger pmd

**Review by karansiwach — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29977)* status: :shipit: complete! ✓

**Review by karansiwach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29977)* status: :shipit: complete! ✓

**Review by karansiwach — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29977)* status: 1 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/29977)* status: :shipit: complete! ✓

**Pull request merged**
