### PR TITLE
[feat]: [CDS-39609]: onboarding InfraDefinition to reference framework

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37898)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37898)

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37898)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 249 at r2](https://reviewable.io/reviews/harness/harness-core/37898#-NDRhMo2-E1iEKDbiIlQ:-NDRhMo2-E1iEKDbiIlR:bhm081p) ([raw file](https://github.com/harness/harness-core/blob/97a5a879ee15bd4766ff870270776ed5d823a2ab/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L249)):*
> ```Java
> 
>         infraEntityOptional.ifPresent(
>             infrastructureEntity -> infrastructureEntitySetupUsageHelper.deleteSetupUsages(infrastructureEntity));
> ```

batch delete should also do this
___
*[`953-events-api/src/main/java/io/harness/eventsframework/protohelper/InfraDefinitionRefProtoDTOHelper.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/37898#-NDRhkwo1U749Mznv8t6:-NDRhkwo1U749Mznv8t7:b-ukymqi) ([raw file](https://github.com/harness/harness-core/blob/97a5a879ee15bd4766ff870270776ed5d823a2ab/953-events-api/src/main/java/io/harness/eventsframework/protohelper/InfraDefinitionRefProtoDTOHelper.java#L21)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.CDC)
> public class InfraDefinitionRefProtoDTOHelper {
> ```

can we move to 120 or similar module 
___
*[`953-events-api/src/main/java/io/harness/eventsframework/protohelper/InfraDefinitionRefProtoDTOHelper.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/37898#-NDRhxuQEg8HNays6zPh:-NDRhxuQEg8HNays6zPi:bm73i42) ([raw file](https://github.com/harness/harness-core/blob/97a5a879ee15bd4766ff870270776ed5d823a2ab/953-events-api/src/main/java/io/harness/eventsframework/protohelper/InfraDefinitionRefProtoDTOHelper.java#L35)):*
> ```Java
>     }
>     if (isNotBlank(envIdentifier)) {
>       identifierRefBuilder.setEnvIdentifier(StringValue.of(envIdentifier));
> ```

we should validate that env must not be empty
___
*[`970-ng-commons/src/main/java/io/harness/beans/InfraDefReference.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/37898#-NDRiHIpAlRTwbmGOq7M:-NDRiHIpAlRTwbmGOq7N:bqh2kg2) ([raw file](https://github.com/harness/harness-core/blob/97a5a879ee15bd4766ff870270776ed5d823a2ab/970-ng-commons/src/main/java/io/harness/beans/InfraDefReference.java#L22)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.PIPELINE)
> public class InfraDefReference implements EntityReference {
> ```

lets move to 125/127

**Comment by tchaurasiya** [comment]
*[`970-ng-commons/src/main/java/io/harness/beans/InfraDefReference.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/37898#-NDRiHIpAlRTwbmGOq7M:-NDRl4mxCC99TWUAJWi5:bt2r5kq) ([raw file](https://github.com/harness/harness-core/blob/97a5a879ee15bd4766ff870270776ed5d823a2ab/970-ng-commons/src/main/java/io/harness/beans/InfraDefReference.java#L22)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets move to 125/127
</blockquote></details>

Used in its mapper which is in 970-ng-commons. (EntityDetailProtoToRestMapper)

**Comment by tchaurasiya** [comment]
*[`953-events-api/src/main/java/io/harness/eventsframework/protohelper/InfraDefinitionRefProtoDTOHelper.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/37898#-NDRhxuQEg8HNays6zPh:-NDRnaS_91XQkzMnxJjX:b-jn5s6n) ([raw file](https://github.com/harness/harness-core/blob/97a5a879ee15bd4766ff870270776ed5d823a2ab/953-events-api/src/main/java/io/harness/eventsframework/protohelper/InfraDefinitionRefProtoDTOHelper.java#L35)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should validate that env must not be empty
</blockquote></details>

Discussed offline.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 17 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37898)* status: :shipit: complete! ✓

**Pull request merged**
