### PR TITLE
[feat]: [PIE-7554]: Check for events in last 30 mins only during pipeline get

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)

### CODE REVIEW

**Comment by USB-05** [comment]
trigger gitleaks

**Comment by diptiman-adak** [comment]
trigger gitleaks

**Comment by diptiman-adak** [comment]
trigger gitleaks

**Comment by diptiman-adak** [comment]
trigger gitleaks

**Comment by diptiman-adak** [comment]
trigger gitleaks

**Comment by diptiman-adak** [comment]
trigger gitleaks

**Comment by diptiman-adak** [comment]
trigger gitleaks

**Comment by USB-05** [comment]
trigger gitleaks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r1, 4 of 4 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/validation/async/PipelineValidationEventRepositoryCustomImpl.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/42460#-NLZKfkZ5lnMTHNqUOMY:-NLZKfkZ5lnMTHNqUOMZ:b-ympjjh) ([raw file](https://github.com/harness/harness-core/blob/3131aa89467df1a1312b0209c3da0a609d386891/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/validation/async/PipelineValidationEventRepositoryCustomImpl.java#L44)):*
> ```Java
>     Query query = new Query(criteria).with(Sort.by(Direction.DESC, PipelineValidationEventKeys.startTs));
>     PipelineValidationEvent event = mongoTemplate.findOne(query, PipelineValidationEvent.class);
>     return Optional.ofNullable(event);
> ```

please add unit test for this with actual mongo



_Code quote:_
```Java
  public Optional<PipelineValidationEvent> findLatestValidEvent(String fqn, Action action) {
    Criteria criteria = PipelineAsyncValidationHelper.getCriteriaForFindLatest(fqn, action);
    Query query = new Query(criteria).with(Sort.by(Direction.DESC, PipelineValidationEventKeys.startTs));
    PipelineValidationEvent event = mongoTemplate.findOne(query, PipelineValidationEvent.class);
    return Optional.ofNullable(event);
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/validation/async/PipelineValidationEventRepositoryCustomImpl.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/42460#-NLZKfkZ5lnMTHNqUOMY:-NLwsjgb6uUgEDke6u0J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88a18be02efdd9c5839d742c8334b284332578ea/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/validation/async/PipelineValidationEventRepositoryCustomImpl.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

please add unit test for this with actual mongo
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 205 at r5](https://reviewable.io/reviews/harness/harness-core/42460#-NLyEcFw9K9lqLWm1tzn:-NLyEcFw9K9lqLWm1tzo:b-3u5zq1) ([raw file](https://github.com/harness/harness-core/blob/c748d30f4c2e5f3cb4f24178d78a6ab0d74ef5b2/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L205)):*
> ```Java
>         bind(PipelineGovernanceService.class).toInstance(mock(PipelineGovernanceService.class));
>         bind(PipelineEnforcementService.class).toInstance(mock(PipelineEnforcementService.class));
>         bind(TemplateResourceClient.class).toInstance(mock(TemplateResourceClient.class));
> ```

you can directly add mock in your test isn't?



_Code quote:_
```Java
        bind(PipelineGovernanceService.class).toInstance(mock(PipelineGovernanceService.class));
        bind(PipelineEnforcementService.class).toInstance(mock(PipelineEnforcementService.class));
        bind(TemplateResourceClient.class).toInstance(mock(TemplateResourceClient.class));
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 205 at r5](https://reviewable.io/reviews/harness/harness-core/42460#-NLyEcFw9K9lqLWm1tzn:-NLyaAKd-NvoHIpeiDPE:b21h1eg) ([raw file](https://github.com/harness/harness-core/blob/c748d30f4c2e5f3cb4f24178d78a6ab0d74ef5b2/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L205)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you can directly add mock in your test isn't?
</blockquote></details>

directly mocking in test wasn’t working, the binding error was still coming. And anyway, these bindings would be added anyway when the tests for any class referring to these classes are added

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 12 files at r1, 4 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460#-:-NLyakPv2Iph-IQRYfcK:bnfp4nl)* status: 6 file(s) to review.

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460#-:-NLyuQW50OtDG11ZRQns:bnfp4nl)* status: 6 file(s) to review.

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42460)* status: :shipit: complete! ✓

**Pull request merged**
