### PR TITLE
fix: [GTM-712]: Use default signup notification template OnPrem

### PR DESCRIPTION
**Pull request by thomas-grasman**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31326)

### CODE REVIEW

**Comment by thomas-grasman** [comment]
trigger messagecheck

**Review by pranil-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31326)* status: Some of the checks are too old.

**Review by zhuoyin00 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31326)* status: Some of the checks are too old. 1 change requests. 

___
*[920-ng-signup/src/main/java/io/harness/signup/SignupModule.java, line 65 at r2](https://reviewable.io/reviews/harness/harness-core/31326#-My8VNu97dRsgG8w6agU:-My8VNu97dRsgG8w6agV:b-nni4tl) ([raw file](https://github.com/harness/harness-core/blob/b8ee60d5514ec113ee487fec1b3b6572be7c0d07/920-ng-signup/src/main/java/io/harness/signup/SignupModule.java#L65)):*
> ```Java
>     String deployMode = System.getenv().get(DEPLOY_MODE);
>     if (DeployMode.isOnPrem(deployMode)) {
>       bind(SignupNotificationHelper.class).to(SaasSignupNotificationHelper.class).in(Singleton.class);
> ```

This is written during we were testing the code. 
Let's not use this way, instead define @Singleton in Onprem and SaasSignupNotificationHelper

Same as below



_Code quote:_
```Java
in(Singleton.class);
```
___
*[920-ng-signup/src/test/java/io/harness/signup/notification/SignupNotificationHelperTest.java, line 37 at r2](https://reviewable.io/reviews/harness/harness-core/31326#-My8VGH162dFLE--HnPS:-My8VGH162dFLE--HnPT:b-sg5iiz) ([raw file](https://github.com/harness/harness-core/blob/b8ee60d5514ec113ee487fec1b3b6572be7c0d07/920-ng-signup/src/test/java/io/harness/signup/notification/SignupNotificationHelperTest.java#L37)):*
> ```Java
> import org.mockito.Mock;
> 
> public class SignupNotificationHelperTest extends CategoryTest {
> ```

Change the test name to SaasSignupNotificationHelper



_Code quote:_
```Java
SignupNotificationHelperTest
```
___
*[920-ng-signup/src/test/java/io/harness/signup/services/SignupServiceImplTest.java, line 221 at r2](https://reviewable.io/reviews/harness/harness-core/31326#-My8V6TQ-P-Mq1UdbNve:-My8V6TQ-P-Mq1UdbNvf:b697ys0) ([raw file](https://github.com/harness/harness-core/blob/b8ee60d5514ec113ee487fec1b3b6572be7c0d07/920-ng-signup/src/test/java/io/harness/signup/services/SignupServiceImplTest.java#L221)):*
> ```Java
>   }
> 
>   @Test(expected = RuntimeException.class)
> ```

What is the intention change exception here?



_Code quote:_
```Java
RuntimeException
```

**Comment by thomas-grasman** [comment]
>What is the intention change exception here?
>
>Code quote:
>
>RuntimeException

SonarLint was giving me an error because the exception was deprecated. I just switch it out for the parent class exception.

**Review by zhuoyin00 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31326)* status: :shipit: complete! ✓

**Pull request closed without merging**
