### PR TITLE
feat: [CDS-38781]: Add fetch predeployment data request handler

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Add request handler for fetch pre deployment data

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Codebase hash checks
- Is it new task type? (If yes, no need to answer 2 then)
  **No**
- Did you add a new class which is added in kryo serialization
  **Yes**
- if yes then do not use that class in any of the delegate task payload till it makes to delegate release
  **Yes. Not yet implemented on manager**
- Did you make changes to the code in a backward-compatible manner?
  **Not required, no previous logic implemented **
- will the new version of the delegate receive old version task and process?
  **Yes. Not yet used**
- If new version of the manager receives response for the old task will it be able to handle it successfully?
  **Yes**
- Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
  **No**
- If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
  **Yes**
- if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
  **Yes**
- Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
  **No**
- Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
  **No**

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34287)

### CODE REVIEW

**Review by vlica-harness — DISMISSED** [review]

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34287)* status: :shipit: complete! ✓

**Review by vlica-harness — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34287)* status: Some of the checks are too old.

**Review by vlica-harness — APPROVED** [review]

**Comment by abosii-harness** [comment]
trigger messagecheck

**Comment by abosii-harness** [comment]
trigger ti0

**Comment by abosii-harness** [comment]
trigger ft2

**Review by vlica-harness — APPROVED** [review]

**Review by vlica-harness — APPROVED** [review]

**Review by arpit3107 — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 3 of 6 files at r2, 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34287)* status: :shipit: complete! ✓

**Pull request merged**
