### PR TITLE
[feat]: [PIE-6231]: Removing unnecessary pipeline validations in get call

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Removing unnecessary pipeline validations in get pipeline call from caller code

Impact: Will impact the pipeline execute flow
Testing: Did manual testing. Ran basic flows of pipeline.

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40088)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40088)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/40088#-NGqAFHACdcqKGbtE1Ji:-NGqAFHACdcqKGbtE1Jj:b-xozbfw) ([raw file](https://github.com/harness/harness-core/blob/7268dcdaa85dc850965dd80d32f2af1aabd2d442/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L445)):*
> ```Java
>     log.info(String.format("Validating the pipeline with identifier %s in project %s, org %s, account %s", pipelineId,
>         projectId, orgId, accountId));
>     Optional<PipelineEntity> entityOptional =
> ```

What is the use of entityOptional here?

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40088)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/40088#-NGqAFHACdcqKGbtE1Ji:-NGqEvjz8SZ_vnTJWOrS:bk1euvo) ([raw file](https://github.com/harness/harness-core/blob/7268dcdaa85dc850965dd80d32f2af1aabd2d442/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L445)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

What is the use of entityOptional here?
</blockquote></details>

Validate a Pipeline with Schema, the api says it needs to validate the pipeline, thus if it returns means pipeline exists plus all validation pass



_Code quote:_
```Java
Optional<PipelineEntity> entityOptional =
```

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40088)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40088)* status: :shipit: complete! ✓

**Pull request merged**
