### PR TITLE
feat: [PL-40111]: Add API to check if resource is public or not

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
Added API to check if a resource is public or not.

Testing:
1. Check with valid resource ID and type
2. Check with invalid resource ID, type or scope -- returns false

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52333)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger ut8

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
*[`access-control/contracts/openapi/v1/openapi.yaml` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdTvRFfAwDSZI5c3bQe:-NdTvRFfAwDSZI5c3bQf:bfmwioh) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/contracts/openapi/v1/openapi.yaml#L91)):*
> ```YAML
>       summary: Enable Public Access for a Resource
>       operationId: is-resource-public
>       description: 'Returns if a Resource is public or not '
> ```

summary and description are not in sync

**Comment by ashishsanodia-harness** [comment]
*[`access-control/contracts/openapi/v1/openapi.yaml` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdTvgH-6Qsq565sQv3N:-NdTvgH-6Qsq565sQv3O:b-dfash3) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/contracts/openapi/v1/openapi.yaml#L98)):*
> ```YAML
>       responses:
>         '201':
>           $ref: '#/components/responses/PublicAccessResponse'
> ```

Why it is returning 201 response? Are we creating resource here?

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessApiImpl.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdTvvH_0KoYV4LykjuA:-NdTvvH_0KoYV4LykjuB:b-utwei9) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessApiImpl.java#L58)):*
> ```Java
>     ResourceType resourceType = validateAndGetResourceType(body.getResourceType());
>     boolean isPublic = publicAccessService.isResourcePublic(body.getResourceIdentifier(), resourceType, resourceScope);
>     return Response.status(Response.Status.OK).entity(isPublic).build();
> ```

Response status is not in sync with openapi

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52333)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdUgEkW4zpvjlhfLJnk:-NdUgEkW4zpvjlhfLJnl:b-tm632s) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L99)):*
> ```Java
>   public boolean isResourcePublic(String resourceIdentifier, ResourceType resourceType, Scope resourceScope) {
>     Optional<ResourceGroupResponse> existingResourceGroupOptional = Optional.ofNullable(
>         NGRestUtils.getResponse(resourceGroupClient.getResourceGroup(PUBLIC_RESOURCE_GROUP_IDENTIFIER,
> ```

Why making PL service call to fetch RG?  RG copy is present in RBAC Db. We can source it from their.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdUfv3M5jZZe_Hnk1TI:-NdUfv3M5jZZe_Hnk1TJ:b-kea7ei) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L111)):*
> ```Java
>                                              .map(ResourceSelector::getIdentifiers)
>                                              .collect(Collectors.toList())
>                                              .get(0);
> ```

If resource doesn't exist won't get(0) fail and throw exception ?

**Comment by piyush-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdaOM819zSIBqy_8yN5:-NdaOM819zSIBqy_8yN6:bwgp0ys) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L108)):*
> ```Java
>         List<ResourceSelector> resourceSelectors = resourceFilter.getResources();
>         List<String> existingResources = resourceSelectors.stream()
>                                              .filter(x -> x.getResourceType().equals(resourceType.getIdentifier()))
> ```

Here we are filtering on  x.getResourceType().equals(resourceType.getIdentifier()) and then again checking if this filtered list will contain Resource identifier, This is not clear to me , Can you explain/>

**Comment by piyush-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdaOM819zSIBqy_8yN5:-Ndch4YHE6B0IGdsH4L6:b2ni9ah) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L108)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Here we are filtering on  x.getResourceType().equals(resourceType.getIdentifier()) and then again checking if this filtered list will contain Resource identifier, This is not clear to me , Can you explain/>
</blockquote></details>

ok

**Comment by piyush-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdaO9po5QHUAQ_vF7Cl:-NdaO9ppCHA_4uFb7TRX:bbqmvds) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L112)):*
> ```Java
>                                              .collect(Collectors.toList())
>                                              .get(0);
>         if (existingResources.contains(resourceIdentifier)) {
> ```

return existingResources.contains(resourceIdentifier) directly.

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52333)* status: 5 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/openapi/v1/openapi.yaml` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdTvRFfAwDSZI5c3bQe:-Ndn1SIH4kGH5NfLuSCG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/contracts/openapi/v1/openapi.yaml#L91)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

summary and description are not in sync
</blockquote></details>

Done.
___
*[`access-control/contracts/openapi/v1/openapi.yaml` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdTvgH-6Qsq565sQv3N:-Ndn1Sdd863tq1rQ2cWK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/contracts/openapi/v1/openapi.yaml#L98)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Why it is returning 201 response? Are we creating resource here?
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessApiImpl.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdTvvH_0KoYV4LykjuA:-Ndn1acz8zX7GvUuPLEh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessApiImpl.java#L58)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Response status is not in sync with openapi
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdUgEkW4zpvjlhfLJnk:-Ndn1bOm3DnZeFe5lJmg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L99)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why making PL service call to fetch RG?  RG copy is present in RBAC Db. We can source it from their.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdaOM819zSIBqy_8yN5:-Ndn1fEf0-B1y_61Y8tW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L108)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdUfv3M5jZZe_Hnk1TI:-Ndn1eHlACCTi8_0TdeO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L111)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Comment by piyush-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdaOM819zSIBqy_8yN5:-Ndn5XIT0P6tQvFlxXTf:b2ni9ah) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L108)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok

**Comment by piyush-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/52333#-NdUfv3M5jZZe_Hnk1TI:-Ndn5_lmCeA-V2FCC-Th:b2ni9ah) ([raw file](https://github.com/harness/harness-core/blob/dbda881c7f1f129ce53b8c2be981d7e04eb884d0/access-control/service/src/main/java/io/harness/accesscontrol/publicaccess/PublicAccessServiceImpl.java#L111)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52333)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger ut3

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52333#-:-NdpZP1tAIj3Q_itDoZN:bnfp4nl)* status: 3. unresolved discussions.

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52333#-:-Ne1ZefkCucm1sNyn9vv:bnfp4nl)* status: Some of the checks are too old.

**Pull request merged**
