### PR TITLE
feat:[del-1610]: making delegate image multi arch 

### PR DESCRIPTION
**Pull request by bharatgoelharness**
Making latest, ubi and ubi-no-tools multi arch for amd64 and arm64.
For this we will be uploading binaries in gcs.

test images with tools : 
**ubi with tools** : https://hub.docker.com/layers/harness/delegate-test/buildx-tools-8/images/sha256-020e9919cadbc27cc24a7bdc2c3620ed469916619d75941186cc924deab4e4ef?context=explore

**ubuntu with tools**: https://hub.docker.com/layers/harness/delegate-test/latest-tools-8/images/sha256-88df9f87b9ddc59e69604e3650b73a9da2fca2c806857022e309667f822739c9?context=explore

**immutable**: https://hub.docker.com/layers/harness/delegate-test/buildx-immutable/images/sha256-ea9d3ad07a89935f23826ca0d2d7d20f1fb3936dbe82337a6f9f8dd55df9e5b2?context=explore

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37778)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37778)

**Comment by bharatgoelharness** [comment]
trigger ti1

**Comment by bharatgoelharness** [comment]
trigger ti4

**Comment by bharatgoelharness** [comment]
trigger ti3

**Comment by bharatgoelharness** [comment]
trigger ti4

**Comment by bharatgoelharness** [comment]
trigger ti0

**Comment by bharatgoelharness** [comment]
trigger ti2

**Review by mdmilic — DISMISSED** [review]
Great work @bharatgoelharness 

> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778#-:-NCZurc76AqqQM8Uo8LV:b-dwknwu)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`960-api-services/src/main/java/io/harness/delegate/clienttools/InstallUtils.java` line 308 at r3](https://reviewable.io/reviews/harness/harness-core/37778#-NCcrNeK8UsOXm0g6mFq:-NCcrNeK8UsOXm0g6mFr:b-2lol3z) ([raw file](https://github.com/harness/harness-core/blob/d368f2da0660011eecb94e15506857d069003a45/960-api-services/src/main/java/io/harness/delegate/clienttools/InstallUtils.java#L308)):*
> ```Java
>   private static String getArchPath() {
>     if (SystemUtils.OS_ARCH != null) {
>       if ("x86_64".equals(SystemUtils.OS_ARCH)) {
> ```

define constants.

**Comment by raghuAtWings** [comment]
*[`960-api-services/src/main/java/io/harness/delegate/clienttools/InstallUtils.java` line 308 at r3](https://reviewable.io/reviews/harness/harness-core/37778#-NCctXmg4jJwFUcfzB6U:-NCctXmg4jJwFUcfzB6V:br4g930) ([raw file](https://github.com/harness/harness-core/blob/d368f2da0660011eecb94e15506857d069003a45/960-api-services/src/main/java/io/harness/delegate/clienttools/InstallUtils.java#L308)):*
> ```Java
>   private static String getArchPath() {
>     if (SystemUtils.OS_ARCH != null) {
>       if ("x86_64".equals(SystemUtils.OS_ARCH)) {
> ```

define constatnt

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778)* status: :shipit: complete! ✓

**Review by bharatgoelharness — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778)* status: Some of the checks are too old.

**Review by bharatgoelharness — COMMENTED** [review]
thanks

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778#-:-NCxmneQ0Kt32egCmGT4:bd5l6m4)* status: Some of the checks are too old.

**Review by bharatgoelharness — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778)* status: Some of the checks are too old.

**Review by bharatgoelharness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778#-:-NCxmyjj6t2IcD40POs-:bnfp4nl)* status: Some of the checks are too old.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778)* status: Some of the checks are too old.

**Review by gaurav-jain1 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778#-:-NCxpRHc1hnWDe1YYlnE:bnfp4nl)* status: Some of the checks are too old.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 3 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37778#-:-NCy6MT78N6G5ClknWSR:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
