### PR TITLE
[feat]: [CDS-41655]: change getCdDeployStageMetadata api to handle inherit se…

### PR DESCRIPTION
**Pull request by tchaurasiya**
…rvice case

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38498)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38498)

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38498)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/38498#-NDy9CJR-jj531FrrF5D:-NDy9CJR-jj531FrrF5E:bpv0199) ([raw file](https://github.com/harness/harness-core/blob/4fef82e6edcd54c02282a19f3b03e4a7bad808f8/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java#L58)):*
> ```Java
>   public ResponseDTO<CDStageMetaDataDTO>
>   getCdDeployStageMetadata(@Parameter(description = "Stage Identifier") String stageIdentifier,
>       @Parameter(description = "Pipeline yaml string to be parsed") @NotNull String pipelineYaml) throws IOException {
> ```

1. should be hidden from Open API spec
2. How will it accept pipeline yaml in a GET request ? shouldn't it be POST

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38498)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/CdDeployStageMetadataRequestDTO.java` line 21 at r5](https://reviewable.io/reviews/harness/harness-core/38498#-NEEflX6-9uuvCnPJpEs:-NEEflX6-9uuvCnPJpEt:b-k1718s) ([raw file](https://github.com/harness/harness-core/blob/c1c993af57166063b83faf7f678217be2cda67b5/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/CdDeployStageMetadataRequestDTO.java#L21)):*
> ```Java
> @JsonInclude(NON_NULL)
> @OwnedBy(HarnessTeam.CDC)
> @Schema(name = "ServiceRequest", description = "Service Request details defined in Harness.")
> ```

nit: This description needs to be updated

**Pull request merged**
