### PR TITLE
fix: [CDS-2157]: Fixed rollback and container deployment logs for Azure WebApp Non Containers

### PR DESCRIPTION
**Pull request by ivan-83**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30591)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 13 files at r1, 18 of 28 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30591#-:-Mvb-CpP8OKjQ-BOuan7:bnfp4nl)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Review by jelenaHarness — DISMISSED** [review]
> Reviewed 3 of 13 files at r1, 18 of 28 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30591)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger messagecheck

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30591#-:-MvgC2B53Dx0PH2mGGoM:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
