### PR TITLE
fix: [PL-43849]: Revert Enable new nav for all new accounts by default

### PR DESCRIPTION
**Pull request by sahibaHarness**
Reverts harness/harness-core#55279
This is being done as in saas env the call to enable FF is not getting honoured and changes are being reflected only in dev space and SMP envs

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57250)

### CODE REVIEW

**Comment by sahibaHarness** [comment]
trigger uts

**Review by arya-harness — APPROVED** [review]

**Comment by sahibaHarness** [comment]
trigger ut2, ut9

**Review by pbarapatre10 — APPROVED** [review]

**Comment by pbarapatre10** [comment]
Please re-open the respective ticket back. We may have to devise another way to handle this. We didn't get any further direction from FF team on this, right?

**Comment by sahibaHarness** [comment]
> Please re-open the respective ticket back. We may have to devise another way to handle this. We didn't get any further direction from FF team on this, right?

the ticket has been reopened again. We came to the conclusion that we will provide the functionality of enable and disable the new nav via user preference 
https://harness.slack.com/archives/C064R52E0G6/p1702398265292729

**Pull request merged**
