### PR TITLE
fix: [CDS-75591]: Disable escaping  WinRm environment variables reserved symbols

### PR DESCRIPTION
**Pull request by acasian-harness**
## Describe your changes
This change will add an option to WinRm deployment to disable the inhouse escaping mechanism for reserved symbols used as part of environment variables.

Fix is behind feature flag: `CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS`

**Context:**
PowerShell along with Microsoft command line utilities (`set` - which creates a env variable) do have a set symbols that are reserved for future use and recommend having a escaping mechanism as such in order to use those with scripts.
The reserved symbols are: `^&|<>%`.
During some investigation done, we noticed that winrm4j is able to set an environment variable if the value contains any of the reserved symbol, however if the variable will be used further in PowerShell script, it will require manual escape or depending on the combination of feature flags might no even require special handing.

**Feature flag and variable escaping compatibility matrix:**
DISABLE_WINRM_COMMAND_ENCODING_NG | WINRM_SCRIPT_COMMAND_SPLIT_NG | Result
TRUE                                                                       | TRUE                                                            | No escaping required
TRUE                                                                       | FALSE                                                           | Escaping required
FALSE                                                                      | (TRUE|FALSE)                                             | No escaping required

**Tests:**
Pre-Requisite:
Harness variable that will be exported as WinRM env variable:
`$AlexUrlTest` = `http://google.com?var=value&var2=vale^2d|a<s>d`

Script that will list env variables set on host:
`dir env:`

Script that will consume env variable in PowerShell:
`Write-Output "Url: $env:AlexUrlTest"`

Test case 1: 
- DISABLE_WINRM_COMMAND_ENCODING_NG = true 
- WINRM_SCRIPT_COMMAND_SPLIT_NG = true
- CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS = false
disable-winrm-encoding-true-split-true
disable-winrm-encoding-true-split-true-validate

Test case 2: 
- DISABLE_WINRM_COMMAND_ENCODING_NG = true 
- WINRM_SCRIPT_COMMAND_SPLIT_NG = false
- CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS = false
disable-winrm-encoding-true-split-false
disable-winrm-encoding-true-split-false-validate

Test case 3: 
- DISABLE_WINRM_COMMAND_ENCODING_NG = false 
- WINRM_SCRIPT_COMMAND_SPLIT_NG = false
- CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS = false
disable-winrm-encoding-false
disable-winrm-encoding-false-validate

Test case 4: 
- DISABLE_WINRM_COMMAND_ENCODING_NG = true 
- WINRM_SCRIPT_COMMAND_SPLIT_NG = true
- CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS = true
disable-escape-disable-winrm-encoding-true-split-true
disable-escape-disable-winrm-encoding-true-split-true-validate

Test case 5: 
- DISABLE_WINRM_COMMAND_ENCODING_NG = true 
- WINRM_SCRIPT_COMMAND_SPLIT_NG = false
- CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS = true
disable-escape-disable-winrm-encoding-true-split-false
disable-escape-disable-winrm-encoding-true-split-false-validate

Test case 6: 
- DISABLE_WINRM_COMMAND_ENCODING_NG = false 
- WINRM_SCRIPT_COMMAND_SPLIT_NG = false
- CDS_NG_DISABLE_SPECIAL_CHARS_ESCAPE_OF_WINRM_ENV_VARS = true
disable-escape-disable-winrm-encoding-false-split-false
disable-escape-disable-winrm-encoding-false-split-false-validate

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52667)

### CODE REVIEW

**Comment by acasian-harness** [comment]
trigger uts

**Comment by acasian-harness** [comment]
trigger commonchecks

**Comment by acasian-harness** [comment]
trigger smartchecks

**Comment by acasian-harness** [comment]
trigger checkstylecodeformat

**Comment by acasian-harness** [comment]
trigger messagecheck

**Comment by acasian-harness** [comment]
trigger pmd

**Comment by acasian-harness** [comment]
trigger codebasehash

**Comment by acasian-harness** [comment]
trigger messagecheck

**Comment by acasian-harness** [comment]
trigger uts

**Comment by acasian-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52667)* status: 15 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmUtils.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/52667#-NeDZ1Yl6HgbRLPAYzOH:-NeDZ1Yl6HgbRLPAYzOI:bhheozu) ([raw file](https://github.com/harness/harness-core/blob/ae6ad284087f066211087917417ad3c169017cb9/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmUtils.java#L98)):*
> ```Java
>   public static boolean shouldDisableWinRmEnvVarsEscaping(WinRmShellScriptTaskParametersNG winRmCommandTaskParameters) {
>     if (winRmCommandTaskParameters.isDisableCommandEncoding()
>         && !winRmCommandTaskParameters.isWinrmScriptCommandSplit()) {
> ```

We discussed and agreed that winrm script command script should be setting.

**Comment by acasian-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52667#-:-NeMrdmc4c99Jz6k0d8D:bnfp4nl)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`980-commons/src/main/java/io/harness/windows/CmdUtils.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/52667#-NeN5kmKDjFhYELKEPX1:-NeN5kmLDVh0k3Iqysu4:bdqlpk0) ([raw file](https://github.com/harness/harness-core/blob/8298b3c1cb552d5951a6c28782821735ed7a139f/980-commons/src/main/java/io/harness/windows/CmdUtils.java#L32)):*
> ```Java
> 
>     if (!isValidEnvValue(value)) {
>       log.debug(format("Escaping %s env variable as there is a single %% occurrence", value));
> ```

currently, there is no way to add get delegate logs in debug mode, should we add it in warn or info ?

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 12 of 15 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52667)* status: :shipit: complete! ✓

**Comment by acasian-harness** [comment]
> _[`980-commons/src/main/java/io/harness/windows/CmdUtils.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/52667#-NeN5kmKDjFhYELKEPX1:-NeN5kmLDVh0k3Iqysu4:bdqlpk0) ([raw file](https://github.com/harness/harness-core/blob/8298b3c1cb552d5951a6c28782821735ed7a139f/980-commons/src/main/java/io/harness/windows/CmdUtils.java#L32)):_
> 
> > ```java
> >     if (!isValidEnvValue(value)) {
> >       log.debug(format("Escaping %s env variable as there is a single %% occurrence", value));
> > ```
> 
> currently, there is no way to add get delegate logs in debug mode, should we add it in warn or info ?

done

**Comment by acasian-harness** [comment]
trigger uts

**Comment by acasian-harness** [comment]
trigger ut0 ut5

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52667)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52667#-:-NeOQJe48SEOmZzg94lw:bnfp4nl)* status: 1 of 2 approvals obtained.

**Pull request merged**
