### PR TITLE
[feat]: [PIE-8232]: Onboard input-sets/template API onto gitx caching

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Onboard input-sets/template API onto gitx caching. Have tested out the get pipeline flow within the api for both remote and inline entities. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44455)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44455)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 22 files at r1, 19 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44455)* status: 24 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/mappers/GitXCacheMapperTest.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/44455#-NPQdzy725IkInPzjQoo:-NPQdzy725IkInPzjQop:b-3up4qi) ([raw file](https://github.com/harness/harness-core/blob/6e2c8696d0c40e86576859dd29ceab266afe1f48/pipeline-service/service/src/test/java/io/harness/pms/mappers/GitXCacheMapperTest.java#L25)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> public class GitXCacheMapperTest {
> ```

should extend cateogyTest

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44455)* status: 24 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/mappers/GitXCacheMapperTest.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/44455#-NPQdzy725IkInPzjQoo:-NPQeYhh4RL95nTFQf88:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e2c8696d0c40e86576859dd29ceab266afe1f48/pipeline-service/service/src/test/java/io/harness/pms/mappers/GitXCacheMapperTest.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should extend cateogyTest
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 24 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44455)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 22 of 24 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44455)* status: :shipit: complete! ✓

**Pull request merged**
