### PR TITLE
fix: [CDS-35470]: Delegate side changes

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
Delegate side changes for command flags
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 37 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sApplyTaskHandlerTest.java` line 321 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4wL9N8PifUPG0WJ0C:-NJ4wL9N8PifUPG0WJ0D:b-qmq6dn) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sApplyTaskHandlerTest.java#L321)):*
> ```Java
>     doReturn(true).when(k8sTaskHelper).restore(any(), any(), any(), any(), any());
>     doReturn(true).when(mockedK8sApplyBaseHandler).prepare(any(), anyBoolean(), any());
>     doReturn(true).when(k8sTaskHelperBase).applyManifests(any(), any(), any(), any(), anyBoolean(), any());
> ```

Is test working? I believe you need to pass anyNullable here instead. But anyway, can we ensure that we pass null here like eq(null)?
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sApplyRequest.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4wxmJ28h1WhTaEQTV:-NJ4wxmJ28h1WhTaEQTW:b-1rvar2) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sApplyRequest.java#L46)):*
> ```Java
>   boolean useNewKubectlVersion;
>   boolean useK8sApiForSteadyStateCheck;
>   String k8sCommandFlags;
> ```

Why is this string? It's better to have proper support of multiple commands type even that if we don't support right now other command types, it will be easier to extend in case if this change. And we should control this on manager side only
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4xTXr2djNq9pFAiXh:-NJ4xTXr2djNq9pFAiXi:bq4lujo) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java#L45)):*
> ```Java
>   boolean pruningEnabled;
>   boolean useK8sApiForSteadyStateCheck;
>   K8sCommandFlag k8sCommandFlag;
> ```

Let's not have this wrapper class, we can directly pass @Expression(ALLOW_SECRETS) private Map<String, String> valueMap;
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 2033 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ5-6H-5G8ckwe6K9Vy:-NJ5-6H-5G8ckwe6K9Vz:b-fybcd5) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L2033)):*
> ```Java
>     kryo.register(EcsS3FetchRunTaskResponse.class, 573567);
>     kryo.register(TerragruntCommandType.class, 573568);
>     kryo.register(K8sCommandFlag.class, 601234);
> ```

Let's remove this wrapper class
___
*[`960-api-services/src/main/java/io/harness/k8s/K8sCommandFlagsUtils.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4zXqW3FkudB0it1ub:-NJ4zXqW3FkudB0it1uc:bevzs9m) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/960-api-services/src/main/java/io/harness/k8s/K8sCommandFlagsUtils.java#L22)):*
> ```Java
>     String flags = "";
>     if (isNotEmpty(commandFlags)) {
>       flags = commandFlags.getOrDefault(commandType, "");
> ```

nit: this logic can be simplified to:



_Code snippet:_
```Java
if (isNotEmpty(commandFlags)) {
    String flags = commandFlags.get(commandType);
    return isNotEmpty(flags) ? flags : "";
}

return "";
```
___
*[`960-api-services/src/main/java/io/harness/k8s/kubectl/ApplyCommand.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ5-CSE4HC-RvMrKlMm:-NJ5-CSE4HC-RvMrKlMn:b-vraj1t) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/960-api-services/src/main/java/io/harness/k8s/kubectl/ApplyCommand.java#L61)):*
> ```Java
>   }
> 
>   public ApplyCommand commandFlags(String commandFlags) {
> ```

Shouldn't this be common for every kubectl commands? We can put it in AbstractExecutable 
___
*[`970-api-services-beans/src/main/java/io/harness/serializer/kryo/ApiServiceBeansKryoRegister.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ5-3MS0USm5lVE2Rw1:-NJ5-3MS0USm5lVE2Rw2:b53rwf3) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/970-api-services-beans/src/main/java/io/harness/serializer/kryo/ApiServiceBeansKryoRegister.java#L478)):*
> ```Java
>     kryo.register(AMITagsResponse.class, 81001);
>     kryo.register(NexusRepositories.class, 9000312);
>     kryo.register(K8sCliCommandType.class, 80314);
> ```

Do we need to register this to kryo?

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 37 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sApplyTaskHandlerTest.java` line 321 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4wL9N8PifUPG0WJ0C:-NJ8zXDW0ACl5QJ6-bQj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/260-delegate/src/test/java/software/wings/delegatetasks/k8s/taskhandler/K8sApplyTaskHandlerTest.java#L321)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is test working? I believe you need to pass anyNullable here instead. But anyway, can we ensure that we pass null here like eq(null)?
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4xTXr2djNq9pFAiXh:-NJ8zaHq37n514t9dFVb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java#L45)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's not have this wrapper class, we can directly pass @Expression(ALLOW_SECRETS) private Map<String, String> valueMap;
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 2033 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ5-6H-5G8ckwe6K9Vy:-NJ8zkUY4UpPTrAynu0Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L2033)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's remove this wrapper class
</blockquote></details>

Done.
___
*[`970-api-services-beans/src/main/java/io/harness/serializer/kryo/ApiServiceBeansKryoRegister.java` line 478 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ5-3MS0USm5lVE2Rw1:-NJ8zlDr8WXWqdWsKifD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/970-api-services-beans/src/main/java/io/harness/serializer/kryo/ApiServiceBeansKryoRegister.java#L478)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Do we need to register this to kryo?
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 37 files at r1, 17 of 17 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 37 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sApplyRequestHandlerTest.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJElyXD5LHNrQCrrXvt:-NJElyXD5LHNrQCrrXvu:bu5ktxt) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sApplyRequestHandlerTest.java#L120)):*
> ```Java
>                                        .commandName("K8s Apply")
>                                        .skipDryRun(true)
>                                        .k8sCommandFlags(null)
> ```

Isn't it by default null? Why we need to specifically set it as null?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java` line 322 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJElrhdDKLl_ilvCbx8:-NJElrhdDKLl_ilvCbx9:bu5ktxt) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java#L322)):*
> ```Java
>             .manifestDelegateConfig(KustomizeManifestDelegateConfig.builder().build())
>             .releaseName("releaseName")
>             .k8sCommandFlag(null)
> ```

Isn't it by default null? Why we need to specifically set it as null?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryRequestHandlerTest.java` line 508 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJEm8qG1RMG9KAk27PD:-NJEm8qG1RMG9KAk27PE:bu5ktxt) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryRequestHandlerTest.java#L508)):*
> ```Java
>                                                .instanceUnitType(NGInstanceUnitType.COUNT)
>                                                .instances(3)
>                                                .k8sCommandFlag(null)
> ```

Isn't it by default null? Why we need to specifically set it as null?
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandlerTest.java` line 652 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJEmEr6BRTOb3MCb8lT:-NJEmEr6BRTOb3MCb8lU:b6pvfeq) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandlerTest.java#L652)):*
> ```Java
>     verify(k8sTaskHelperBase, times(1))
>         .applyManifests(any(Kubectl.class), anyList(), any(K8sDelegateTaskParams.class), any(LogCallback.class),
>             anyBoolean(), any(String.class));
> ```

Can we make sure that the right command flag is passed?

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 37 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sApplyRequestHandlerTest.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJElyXD5LHNrQCrrXvt:-NJFQQMCBUY8fFpcFTAq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sApplyRequestHandlerTest.java#L120)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Isn't it by default null? Why we need to specifically set it as null?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java` line 322 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJElrhdDKLl_ilvCbx8:-NJFQQnf-f267YC7Jf4A:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java#L322)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Isn't it by default null? Why we need to specifically set it as null?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryRequestHandlerTest.java` line 508 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJEm8qG1RMG9KAk27PD:-NJFQROQ6sCZY6PgQiLi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryRequestHandlerTest.java#L508)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Isn't it by default null? Why we need to specifically set it as null?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandlerTest.java` line 652 at r4](https://reviewable.io/reviews/harness/harness-core/41342#-NJEmEr6BRTOb3MCb8lT:-NJFQxhR3dp-deo9PZbL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97511c4e55167bb050878c6945a1a13775ebc793/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sRollingRollbackBaseHandlerTest.java#L652)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we make sure that the right command flag is passed?
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sApplyRequest.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ4wxmJ28h1WhTaEQTV:-NJFOtMHDSsngPdk_1F6:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sApplyRequest.java#L46)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why is this string? It's better to have proper support of multiple commands type even that if we don't support right now other command types, it will be easier to extend in case if this change. And we should control this on manager side only
</blockquote></details>

Done
___
*[`960-api-services/src/main/java/io/harness/k8s/kubectl/ApplyCommand.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/41342#-NJ5-CSE4HC-RvMrKlMm:-NJFOiZu6F1Oza0Fv93J:bk3mhhz) ([raw file](https://github.com/harness/harness-core/blob/e0247c27c59e614cd3aa8700dd8a4a45173ad114/960-api-services/src/main/java/io/harness/k8s/kubectl/ApplyCommand.java#L61)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Shouldn't this be common for every kubectl commands? We can put it in AbstractExecutable 
</blockquote></details>

Currently going forward with the same approach. Discussed offline

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 37 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java` line 46 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJg-NT3YCmIULSuKep:-NJJg-NT3YCmIULSuKeq:b-7rbhkq) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java#L46)):*
> ```Java
>   boolean pruningEnabled;
>   boolean useK8sApiForSteadyStateCheck;
>   @Expression(ALLOW_SECRETS) Map<String, String> k8sCommandFlag;
> ```

This should be k8sCommandFlags, same as for Apply 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sCanaryDeployRequest.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJg9jz2bEK4o7DldWZ:-NJJg9jz2bEK4o7DldW_:b-7rbhkq) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sCanaryDeployRequest.java#L49)):*
> ```Java
>   boolean cleanUpIncompleteCanaryDeployRelease;
>   boolean useK8sApiForSteadyStateCheck;
>   @Expression(ALLOW_SECRETS) Map<String, String> k8sCommandFlag;
> ```

This should be k8sCommandFlags, same as for Apply 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRequest.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJgEA40geUexBaXvRp:-NJJgEA40geUexBaXvRq:b-268bl3) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRequest.java#L49)):*
> ```Java
>   boolean pruningEnabled;
>   boolean useK8sApiForSteadyStateCheck;
>   @Expression(ALLOW_SECRETS) Map<String, String> k8sCommandFlag;
> ```

This should be k8sCommandFlags, similar as for Apply 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingRollbackDeployRequest.java` line 40 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJgHrZ4rESkTLSCqph:-NJJgHrZ4rESkTLSCqpi:b-268bl3) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingRollbackDeployRequest.java#L40)):*
> ```Java
>   boolean pruningEnabled;
>   List<KubernetesResourceId> prunedResourceIds;
>   @Expression(ALLOW_SECRETS) Map<String, String> k8sCommandFlag;
> ```

This should be k8sCommandFlags, similar as for Apply 
___
*[`960-api-services/src/main/java/io/harness/k8s/K8sCommandFlagsUtils.java` line 17 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJgMz98ynsV5dJEPZ_:-NJJgMz98ynsV5dJEPZa:b-6y0m2x) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/960-api-services/src/main/java/io/harness/k8s/K8sCommandFlagsUtils.java#L17)):*
> ```Java
> @UtilityClass
> public class K8sCommandFlagsUtils {
>   public String applyK8sCommandFlags(String commandType, Map<String, String> commandFlags) {
> ```

Method name should be getK8sCommandFlags

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 33 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java` line 46 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJg-NT3YCmIULSuKep:-NJMChYT7NKYW5APEoRa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sBGDeployRequest.java#L46)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be k8sCommandFlags, same as for Apply 
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sCanaryDeployRequest.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJg9jz2bEK4o7DldWZ:-NJMCi8G4zJC7IugYByk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sCanaryDeployRequest.java#L49)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be k8sCommandFlags, same as for Apply 
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRequest.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJgEA40geUexBaXvRp:-NJMCi_v-rmdCV_cyMDj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingDeployRequest.java#L49)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be k8sCommandFlags, similar as for Apply 
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingRollbackDeployRequest.java` line 40 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJgHrZ4rESkTLSCqph:-NJMCj5E8__iXZYzbPdO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sRollingRollbackDeployRequest.java#L40)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This should be k8sCommandFlags, similar as for Apply 
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/K8sCommandFlagsUtils.java` line 17 at r5](https://reviewable.io/reviews/harness/harness-core/41342#-NJJgMz98ynsV5dJEPZ_:-NJMCkl59saoQZQA7cA-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8f937a79ae82a65646d01a53a664c46355298f71/960-api-services/src/main/java/io/harness/k8s/K8sCommandFlagsUtils.java#L17)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Method name should be getK8sCommandFlags
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 12 of 14 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: Some of the checks are too old. 34 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
> Reviewed 13 of 37 files at r1, 5 of 17 files at r2, 1 of 2 files at r3, 4 of 4 files at r5, 12 of 14 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: Some of the checks are too old. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java` line 158 at r8](https://reviewable.io/reviews/harness/harness-core/41342#-NJiuqoX9ju13Vo8qmLu:-NJiuqoX9ju13Vo8qmLv:b9dxog0) ([raw file](https://github.com/harness/harness-core/blob/8641a9eb4c49ad48f8551ad4c1ff6c9e335022f5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java#L158)):*
> ```Java
>     } else {
>       k8sRollingBaseHandler.setManagedWorkloadsInRelease(k8sDelegateTaskParams, managedWorkloads, release, client);
>       k8sRollingBaseHandler.setCustomWorkloadsInRelease(customWorkloads, release);
> ```

Is this intended or did this come while resolving merge conflicts?



_Code quote:_
```Java
      k8sRollingBaseHandler.setManagedWorkloadsInRelease(k8sDelegateTaskParams, managedWorkloads, release, client);
      k8sRollingBaseHandler.setCustomWorkloadsInRelease(customWorkloads, release);
```

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java` line 158 at r8](https://reviewable.io/reviews/harness/harness-core/41342#-NJiuqoX9ju13Vo8qmLu:-NJixQNCDq74IGpw5Xem:b71mhz4) ([raw file](https://github.com/harness/harness-core/blob/8641a9eb4c49ad48f8551ad4c1ff6c9e335022f5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java#L158)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Is this intended or did this come while resolving merge conflicts?
</blockquote></details>

This came while resolving conflicts. Will remove these changes as i think its already taken care in finallly block

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java` line 158 at r8](https://reviewable.io/reviews/harness/harness-core/41342#-NJiuqoX9ju13Vo8qmLu:-NJiz4JU2VANxZuYIvej:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8641a9eb4c49ad48f8551ad4c1ff6c9e335022f5/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sRollingRequestHandler.java#L158)):*
<details><summary><i>Previously, TarunUba1 (Tarun Uba) wrote…</i></summary><blockquote>

This came while resolving conflicts. Will remove these changes as i think its already taken care in finallly block
</blockquote></details>

Done

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41342)* status: :shipit: complete! ✓

**Pull request merged**
