### PR TITLE
[feat]: [CDS-71727]: Log service in async while closing log streams

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes
Currently, we have many failures while closing log stream with socket exceptions.
	a) Implement separate ThreadPool to handle log stream long running tasks so that tasks don't slow down or fail because of such failures.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NYMEzTdC5yUyMAoj-Sf:beiwo60) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
> ```Java
> 
>   // We have a ScalingQueue with MAX_INT size but keeping LogStreamingRejectedExecutionHandler just to log info.
>   private final ThreadPoolExecutor logStreamingClientExecutor =
> ```

Shouldnt we use ManagedExecutorService
Example -
@Provides
  @Singleton
  @Named("PipelineAsyncValidationExecutorService")
  public Executor pipelineAsyncValidationExecutorService() { in PipelineServiceModule

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMFKKH2Garg-s9SgcA:-NYMFKKH2Garg-s9SgcB:b-mr2179) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java#L23)):*
> ```Java
>   public void rejectedExecution(Runnable r, ThreadPoolExecutor executor) {
>     log.info("Log failed to be closed. Retrying on same thread");
>     r.run();
> ```

I think we should just log it?, and add retry in the rest client call?



_Code quote:_
```Java
r.run();
```

**Comment by yogesh-chauhan** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NYRbEcA7rZXn9rZ7WBK:b23v265) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt we use ManagedExecutorService
Example -
@Provides
  @Singleton
  @Named("PipelineAsyncValidationExecutorService")
  public Executor pipelineAsyncValidationExecutorService() { in PipelineServiceModule
</blockquote></details>

I feel that since its a like a library method/utility, its better if this takes in an executor service from the caller itself, what do you think @arvind-choudhary-h  ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMFKKH2Garg-s9SgcA:-NYUxtC48nptyoM5QIpn:b-m1dvpd) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I think we should just log it?, and add retry in the rest client call?
</blockquote></details>

The code will come here only if 2 conditions are met:
1. The queue is full -- this will not happen as we have flexible queue.
2. The Shutdown hook is called and executor is not ready to take any new tasks. This can happen but retrying from rest client won't do anything as executor is shut down now.

**Comment by arvind-choudhary-h** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NYUyVopDmXZkwyIZM0H:b8vso5z) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I feel that since its a like a library method/utility, its better if this takes in an executor service from the caller itself, what do you think @arvind-choudhary-h  ?
</blockquote></details>

Didn't create managed because it's not shared. LogStreamingStepClientFactory is a singleton. Here, the provider of this bean is `LogStreamingStepClientFactory` and we forward this final executor to `LogStreamingStepClientImpl`

Any benefits of using otherwise? The issue with managed is we'll have to take care of where all to enable this.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NYc2YhI7CeCIXVJ3uM0:b7ekys7) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Didn't create managed because it's not shared. LogStreamingStepClientFactory is a singleton. Here, the provider of this bean is `LogStreamingStepClientFactory` and we forward this final executor to `LogStreamingStepClientImpl`

Any benefits of using otherwise? The issue with managed is we'll have to take care of where all to enable this.
</blockquote></details>

I agree we can send the executorService from the caller and not keep it here this can be controlled by respective service then

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMFKKH2Garg-s9SgcA:-NYq1Buj7qkgnVfdKL_j:b-q75e91) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java#L23)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

The code will come here only if 2 conditions are met:
1. The queue is full -- this will not happen as we have flexible queue.
2. The Shutdown hook is called and executor is not ready to take any new tasks. This can happen but retrying from rest client won't do anything as executor is shut down now.

</blockquote></details>

@arvind-choudhary-h , could you please validate this once? 
As per our understanding, this gets triggered whenever the executor service rejects the task which can be because of the number of threads that are part of thread pool are busy and the queue is full but we have seen this practically where it gets triggered when the threads in the thread pool are busy.
 Though queue is scalable, even then this would be called multiple times during execution.

In the first cut, maybe for now we should just add the log line and monitor

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NYq2RIS04M757GIPhs7:b-cyzglr) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I agree we can send the executorService from the caller and not keep it here this can be controlled by respective service then
</blockquote></details>

+1, this should be taken from the caller and also should be configurable.

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYq2ZnyCvX7qC60bqoh:-NYq2ZnyCvX7qC60bqoi:b-wp1dez) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java#L85)):*
> ```Java
>   public void closeAllOpenStreamsWithPrefix(String prefix) {
>     // we don't want steps to hang because of any log reasons.
>     logStreamingClientExecutor.submit(() -> {
> ```

what would happen to the task which are not yet processed and the pod dies/restarts, there will be no way to close the pending streams because the information is in memory, does log-service take care of closing it?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: Some of the checks are too old. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYq2ZnyCvX7qC60bqoh:-NZ26vwC9FGH0GUVHUt3:b9wahgf) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientImpl.java#L85)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

what would happen to the task which are not yet processed and the pod dies/restarts, there will be no way to close the pending streams because the information is in memory, does log-service take care of closing it?
</blockquote></details>

Yeah, they are working on it. This is the most that we could do on our end. :)

**Comment by arvind-choudhary-h** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMFKKH2Garg-s9SgcA:-NZ28bLJBjqwkKg3FoRH:bh0vnp) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingRejectedExecutionHandler.java#L23)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@arvind-choudhary-h , could you please validate this once? 
As per our understanding, this gets triggered whenever the executor service rejects the task which can be because of the number of threads that are part of thread pool are busy and the queue is full but we have seen this practically where it gets triggered when the threads in the thread pool are busy.
 Though queue is scalable, even then this would be called multiple times during execution.

In the first cut, maybe for now we should just add the log line and monitor 
</blockquote></details>

That is strange. But cool, if that's the case, I'll remove it for now.

**Comment by arvind-choudhary-h** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NZ28nIn0K7jlYFZAsej:b-w1gqm8) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1, this should be taken from the caller and also should be configurable.
</blockquote></details>

Caller you mean the caller of `io.harness.logstreaming.LogStreamingStepClientFactory#getLogStreamingStepClient` method? Steps sending ThreadPoolExecutor I feel is too much. Why do they have to worry about its internal implementation?

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 604 at r6](https://reviewable.io/reviews/harness/harness-core/49276#-NZZwO2a6E_VQ9WkhaJG:-NZZwO2bE_pjZuJjNLO6:b-jm4ces) ([raw file](https://github.com/harness/harness-core/blob/dd8a28df7f12f80775348df9dd7e3a4d2474869b/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L604)):*
> ```Java
>         threadPoolConfig.getIdleTime(), threadPoolConfig.getTimeUnit(),
>         new ThreadFactoryBuilder().setNameFormat("log-client-pool-%d").build(), threadPoolConfig.getQueueSize(),
>         new ThreadPoolExecutor.CallerRunsPolicy());
> ```

Please refer to: https://www.baeldung.com/java-rejectedexecutionhandler#2-caller-runs-policy

**Comment by yogesh-chauhan** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/49276#-NYMEzTdC5yUyMAoj-Se:-NZZwSRz0CeEFWgwLY8q:btr367z) ([raw file](https://github.com/harness/harness-core/blob/36b489d13418aca5fdbdf3730369dadc169fa64d/878-ng-common-utilities/src/main/java/io/harness/logstreaming/LogStreamingStepClientFactory.java#L52)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Caller you mean the caller of `io.harness.logstreaming.LogStreamingStepClientFactory#getLogStreamingStepClient` method? Steps sending ThreadPoolExecutor I feel is too much. Why do they have to worry about its internal implementation? 
</blockquote></details>

I have injected the thread pool now. Both NG Manager and Pipeline service have defined these thread pools

**Review by archit-harness — COMMENTED** [review]
> Reviewed 6 of 7 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 9 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.  (waiting on @yogesh-chauhan)

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 566 at r9](https://reviewable.io/reviews/harness/harness-core/49276#-NZbVJl31LM6e6Q_mt4L:-NZbVJl31LM6e6Q_mt4M:b-f1qj41) ([raw file](https://github.com/harness/harness-core/blob/f4033666ee6efda9d543afe4a226079845c7f767/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L566)):*
> ```Java
>         ? configuration.getLogStreamingServiceConfig().getThreadPoolConfig()
>         : ThreadPoolConfig.builder().corePoolSize(1).maxPoolSize(50).idleTime(30).timeUnit(TimeUnit.SECONDS).build();
>     return ThreadPool.create(threadPoolConfig.getCorePoolSize(), threadPoolConfig.getMaxPoolSize(),
> ```

This uses a ForceQueue policy i.e puts back elements in the Queue on rejection

**Comment by arvind-choudhary-h** [comment]
trigger uts

**Comment by arvind-choudhary-h** [comment]
trigger uts

**Comment by arvind-choudhary-h** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 10 files at r8, 9 of 9 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 13 file(s) to review. 2 change requests. 3. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
trigger checkstylecodeformat

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 8 of 8 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 12 file(s) to review. 2 change requests. 3. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r8, 1 of 9 files at r9, 8 of 8 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 1 change requests. 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.  (waiting on @yogesh-chauhan)

**Comment by yogesh-chauhan** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 1 change requests. 1. unresolved discussions.

**Comment by arvind-choudhary-h** [comment]
trigger review

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 10 files at r8, 1 of 9 files at r9, 7 of 8 files at r12, 3 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: 1 change requests. 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r8, 1 of 9 files at r9, 7 of 8 files at r12, 3 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49276)* status: :shipit: complete! ✓

**Pull request merged**
