### PR TITLE
feat: [IDP-1464][IDP-1465]: RBAC for IDP Admin entities - ResourceTypes, Permissions

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
RBAC for IDP Admin entities - ResourceTypes, Permissions, Roles -

**Newly added resources** -
IDP_PLUGIN, IDP_SCORECARD, IDP_LAYOUT, IDP_CATALOG_ACCESS_POLICY, IDP_INTEGRATION, IDP_ADVANCED_CONFIGURATION

**Newly added permissions** -
idp_plugin_view, idp_plugin_edit, idp_plugin_toggle, idp_plugin_delete, idp_scorecard_view, idp_scorecard_edit, idp_scorecard_delete, idp_layout_view, idp_layout_edit, idp_catalogaccesspolicy_view, idp_catalogaccesspolicy_create, idp_catalogaccesspolicy_edit, idp_catalogaccesspolicy_delete, idp_integration_view, idp_integration_create, idp_integration_edit, idp_integration_delete, idp_advancedconfiguration_view, idp_advancedconfiguration_edit, idp_advancedconfiguration_delete

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)

### CODE REVIEW

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1439 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlDL749Pc1atfhYD7N:-NjlDL749Pc1atfhYD7O:b-2j4nec) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1439)):*
> ```YAML
>     allowedScopeLevels:
>       - account
>   - identifier: idp_idpplugins_disable
> ```

Is there need for both idp_idpplugins enable/disable permission?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1423 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlDosV-5d0WrLYcHwL:-NjlDosV-5d0WrLYcHwM:bopo0fi) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1423)):*
> ```YAML
>   - identifier: idp_idpsettings_manage
>     name: Manage Policies in settings UI
>     status: ACTIVE
> ```

Are following docs referred for implmentation?
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812876/Onboarding+Resources+for+ResourceGroup
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812887/Permissions+Management

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1444 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlEliQC5VZ8-vUowIi:-NjlEliQC5VZ8-vUowIj:boam1k4) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1444)):*
> ```YAML
>     includedInAllRoles: false
>     allowedScopeLevels:
>       - account
> ```

Are all this permissions restricted to only account scope?

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1439 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlDL749Pc1atfhYD7N:-NjlFwPOCluW-J4YCy4E:bn2qux0) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1439)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Is there need for both idp_idpplugins enable/disable permission?
</blockquote></details>

Ok. Yes, it can be replaced it with toggle permission. Will do it.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1444 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlEliQC5VZ8-vUowIi:-NjlG3MSDvOJmvnhni8R:b-8oigt8) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1444)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Are all this permissions restricted to only account scope?
</blockquote></details>

Yes. IDP is account level. All permissions will be scoped to account only.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1547 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlEJNy50710Kq7gKxU:-NjlG9rb8oh1vZLic_WY:b-81bvxp) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1547)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

What is the need of this specific Access control permissions for IDP? Isn't Platform level Access control permissions suffiicient?
</blockquote></details>

In IDP module, we have a separate access control to control permissions for backstage entities - https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/idp-admin/access-control

As of now, backstage entities cannot be converged with platform level access control permissions and that's the reason we have separate access control to manage it
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1553 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlETL80gCd1XiDquuP:-NjlH3uf1Cg_pZ37Wgq_:b-81bvxp) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1553)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

In IDP module, we have a separate access control to control permissions for backstage entities - https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/idp-admin/access-control

As of now, backstage entities cannot be converged with platform level access control permissions and that's the reason we have separate access control to manage it

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/AccessControlResourceImpl.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlIjBCAG7u3XLav6pK:-NjlIjBCAG7u3XLav6pL:b-sznsfh) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/AccessControlResourceImpl.java#L40)):*
> ```Java
> @OwnedBy(IDP)
> public class AccessControlResourceImpl implements Resource {
>   public static final String IDP_ACCESS_CONTROL = "IDP_ACCESS_CONTROL";
> ```

What is the usecase for specific Idp access control?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/OAuthConfigurationsResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJUO16HpI2I0o4QMl:-NjlJUO16HpI2I0o4QMm:bp74l4l) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/OAuthConfigurationsResourceImpl.java#L39)):*
> ```Java
> @Slf4j
> @OwnedBy(IDP)
> public class OAuthConfigurationsResourceImpl implements Resource {
> ```

Rename to IdpOAuthConfigurationsResourceImpl

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/ScorecardChecksResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJkPT69ft18DmrEZE:-NjlJkPT69ft18DmrEZF:b-rbqk5a) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/ScorecardChecksResourceImpl.java#L39)):*
> ```Java
> @Slf4j
> @OwnedBy(IDP)
> public class ScorecardChecksResourceImpl implements Resource {
> ```

Prefix class with Idp.

**Review by Jimit09Gandhi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/UrlAllowListResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJx28CeuMTwnQ4BO4:-NjlJx28CeuMTwnQ4BO5:b-rbqk5a) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/UrlAllowListResourceImpl.java#L39)):*
> ```Java
> @Slf4j
> @OwnedBy(IDP)
> public class UrlAllowListResourceImpl implements Resource {
> ```

Prefix class with Idp.

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1439 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlDL749Pc1atfhYD7N:-NjlL84o95QJhqdGhzIq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1439)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Ok. Yes, it can be replaced it with toggle permission. Will do it.
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/AccessControlResourceImpl.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlIjBCAG7u3XLav6pK:-NjlLCAs2WvZNheNoYZx:b-muwq95) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/AccessControlResourceImpl.java#L40)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

What is the usecase for specific Idp access control?
</blockquote></details>

In IDP module, we have a separate access control to control permissions for backstage entities - [https://app.harness.io/ng/account/vpCkHKsDSxK9\_KYfjCTMKA/module/idp-admin/access-control](https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/idp-admin/access-control)

As of now, backstage entities cannot be converged with platform level access control permissions and that's the reason we have separate access control to manage it
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/ConnectorsResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJG264Z62BD2y0J3U:-NjlLDPS2wBAk0_lHGnf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/ConnectorsResourceImpl.java#L39)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Rename to IdpConnectorsResourceImpl.
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/LayoutResourceImpl.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJMKV67zG-LCztaaI:-NjlLEL-E913oxkchSOL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/LayoutResourceImpl.java#L40)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Rename to IdpLayoutResourceImpl
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/OAuthConfigurationsResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJUO16HpI2I0o4QMl:-NjlLEvQ2YIJu-nx3cCn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/OAuthConfigurationsResourceImpl.java#L39)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Rename to IdpOAuthConfigurationsResourceImpl
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/OnboardingSetupResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJd012U1lRALslMoJ:-NjlLFT0A59kvH_WMdim:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/OnboardingSetupResourceImpl.java#L39)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Prefix class with Idp.
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/PluginsResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJgEf0pncnzDGg855:-NjlLFzC1BaCm83XS_3X:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/PluginsResourceImpl.java#L39)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Prefix class with Idp.
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/ScorecardChecksResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJkPT69ft18DmrEZE:-NjlLGRv3WQpeG3NZwLL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/ScorecardChecksResourceImpl.java#L39)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Prefix class with Idp.
</blockquote></details>

Done
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/UrlAllowListResourceImpl.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlJx28CeuMTwnQ4BO4:-NjlLHLv73nCg-DgB0JK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/idp/UrlAllowListResourceImpl.java#L39)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Prefix class with Idp.
</blockquote></details>

Done

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1423 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlDosV-5d0WrLYcHwL:-NjlUPFyD5oZFlHYCTLq:b-om1r9k) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1423)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Are following docs referred for implmentation?
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812876/Onboarding+Resources+for+ResourceGroup
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812887/Permissions+Management
</blockquote></details>

Done. Thanks for this. Updated permissions with staging status and will follow the phases for further changes.

**Review by Jimit09Gandhi — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1547 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlEJNy50710Kq7gKxU:-NjleTiH9PJ0mZedoRut:b-7yi27j) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1547)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

In IDP module, we have a separate access control to control permissions for backstage entities - https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/idp-admin/access-control

As of now, backstage entities cannot be converged with platform level access control permissions and that's the reason we have separate access control to manage it
</blockquote></details>

cc @ankit-harness FYI.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1523 at r1](https://reviewable.io/reviews/harness/harness-core/55597#-NjlpSvX-LaP7TyrTKqn:-NjlpSvX-LaP7TyrTKqo:b-swr6g4) ([raw file](https://github.com/harness/harness-core/blob/d79b3936fd9ff7682354ee6d4dcb0c5e3683049b/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1523)):*
> ```YAML
>     allowedScopeLevels:
>       - account
>   - identifier: idp_idpscorecarddatasources_delete
> ```

can we have singular form instead of plural idp_idpscorecarddatasource_delete? I think it would be consistent with other permissions onboarded

**Comment by sathish-soundarapandian** [comment]
trigger ut7, ut8

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 4 of 13 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Comment by sathish-soundarapandian** [comment]
trigger ut5

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Comment by sathish-soundarapandian** [comment]
trigger ut1, ut7

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55597)* status: 15 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Comment by sathish-soundarapandian** [comment]
trigger ut4

**Review by devesh-harness — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger review

**Pull request merged**
