### PR TITLE
[feat]: [PIE-9453]: Onboarded DefaultConnectorRef for Pipeline, InputSets and Templates.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Changes: Have added a setting named as Default Connector for GitExperience, which is used when no connector is provided in case create flows.
Testing: Local testing has been done.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)

### CODE REVIEW

**Review by shalini-agr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJBhVU6ug8xjFWKj0C:-NTJBhVU6ug8xjFWKj0D:b5cxjg0) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L74)):*
> ```Java
>   private final MongoTemplate mongoTemplate;
>   private final TemplateGitXService templateGitXService;
>   private final GitXSettingsHelper gitXSettingsHelper;
> ```

remove this declaration if not used anywhere in this class
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1482 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJCGDWAlrVHi7W8l2v:-NTJCGDWAlrVHi7W8l2w:beg51fh) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1482)):*
> ```Java
>   }
> 
>   private void setConnectorRefForRemoteEntity(TemplateEntity templateEntity) {
> ```

move this method to a commonplace, and use it from there, as this block of code is being repeated thrice in this PR itself
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 742 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJBnx_7vqFwlpOUU1_:-NTJBnx_7vqFwlpOUU1a:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L742)):*
> ```Java
>   }
> 
>   private void setConnectorRefForRemoteEntity(InputSetEntity inputSetEntity) {
> ```

same
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJBvFOBTEazQRXmalT:-NTJBvFOBTEazQRXmalU:b-7jl271) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
> ```Java
> 
>   private void setConnectorRefForRemoteEntity(PipelineEntity pipelineEntity) {
>     GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
> ```

same.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJC-DQB3BbKh0L6MMs:-NTJC-DQB3BbKh0L6MMt:b5cxjg0) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L76)):*
> ```Java
>   private final GitAwareEntityHelper gitAwareEntityHelper;
>   private final TransactionHelper transactionHelper;
>   private final GitXSettingsHelper gitXSettingsHelper;
> ```

remove this declaration if not used anywhere in this class
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJC0A4B9KmVfPm9VR0:-NTJC0A4B9KmVfPm9VR1:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L82)):*
> ```Java
>   private final GitSyncSdkService gitSyncSdkService;
>   private final PipelineEntityReadHelper pipelineEntityReadHelper;
>   private final GitXSettingsHelper gitXSettingsHelper;
> ```

same
___
*[`pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineServiceImplSimplifiedGitExpTest.java` line 546 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJC22Z4vEesVVF1PvK:-NTJC22Z4vEesVVF1PvL:bbtm6pb) ([raw file](https://github.com/harness/harness-core/blob/ea48d95f35b864135a071e65b5240a9e0cdc0ba2/pipeline-service/service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineServiceImplSimplifiedGitExpTest.java#L546)):*
> ```Java
>   public void testDeletePipeline() {
>     doReturn(getResponseDTOCall(false)).when(entitySetupUsageClient).isEntityReferenced(any(), any(), any());
>     MockedStatic<CGRestUtils> cgStatic = Mockito.mockStatic(CGRestUtils.class);
> ```

revert this change if unrelated to your changes

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1482 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJCGDWAlrVHi7W8l2v:-NTJtjlNAZP0wtcSW67q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1482)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

move this method to a commonplace, and use it from there, as this block of code is being repeated thrice in this PR itself
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 742 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJBnx_7vqFwlpOUU1_:-NTJtkv90HG6osZ6CK_-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L742)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 978 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJBvFOBTEazQRXmalT:-NTJtlUg7Q3AZXqZlVuV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L978)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

same.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJBhVU6ug8xjFWKj0C:-NTJtmLd4sRLCBhnzqod:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L74)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

remove this declaration if not used anywhere in this class
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJC-DQB3BbKh0L6MMs:-NTJtmxK26QQR1oFI2al:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L76)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

remove this declaration if not used anywhere in this class
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/46188#-NTJC0A4B9KmVfPm9VR0:-NTJtnTt5lcSM_LLQSqO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d00777e488a44c9ecbb2ff1de85c2f137105a2f/pipeline-service/service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java#L82)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 60 at r6](https://reviewable.io/reviews/harness/harness-core/46188#-NTKI-re1oKlcwOdNYVb:-NTKI-re1oKlcwOdNYVc:bjsz1dk) ([raw file](https://github.com/harness/harness-core/blob/c0895a272f02e8ff40d5fea8ca671c8459bf9e42/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L60)):*
> ```Java
>           getDefaultConnectorForGitX(accountIdentifier, orgIdentifier, projIdentifier, gitEntityInfo.getConnectorRef());
> 
>       if (defaultConnectorForGitX != null) {
> ```

use isEmpty() here instead of !=null

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 17 files at r1, 1 of 15 files at r2, 9 of 16 files at r3, 6 of 8 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)* status: 20 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 15 files at r2, 9 of 16 files at r3, 6 of 8 files at r4, 2 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188#-:-NTKOzRV-ncx9I1EdICL:bnfp4nl)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 17 files at r1, 1 of 15 files at r2, 9 of 16 files at r3, 6 of 8 files at r4, 2 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188#-:-NTKWE5F0gewFHPgPEIO:bnfp4nl)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188#-:-NTKWIB85XWIWUDrxSmL:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankittiwari-harness — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 17 files at r1, 1 of 15 files at r2, 9 of 16 files at r3, 6 of 8 files at r4, 2 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46188)* status: :shipit: complete! ✓

**Pull request merged**
