### PR TITLE
[feat]: [PL-24060]: Correction in ConnectorType enum

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32127)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32127#-:-N-1zLueB3kZGZfucBaZ:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by mankrit-singh** [comment]
Have removed breaking change from previous commit
New connector is added in the end for ConnectorType enum

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32127#-:-N-20hQY9EWVON_Tjx-q:bnfp4nl)* status: :shipit: complete! ✓

**Comment by mankrit-singh** [comment]
trigger ti1

**Review by rijajoo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32127#-:-N-2DDfpC6EX9rv5CeQG:bnfp4nl)* status: 1 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32127)* status: :shipit: complete! ✓

**Pull request merged**
