### PR TITLE
[feat]: [CDS-54909]: validate command parameter uniqueness for winrm …

### PR DESCRIPTION
**Pull request by vladimir-peric**
…credetnials

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
trigger smartchecks

**Review by ivan-83 — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 824 at r2](https://reviewable.io/reviews/harness/harness-core/44881#-NQ4YTBxEkIdH9UeDGUw:-NQ4YTBxEkIdH9UeDGUx:b-isap4v) ([raw file](https://github.com/harness/harness-core/blob/1e031531de0b1422a16b2cea4a2830541a6726e2/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L824)):*
> ```Java
>         parameters.stream().map(WinRmCommandParameter::getParameter).collect(Collectors.toSet());
>     if (parameterNames.size() != parameters.size()) {
>       throw new InvalidRequestException("Command parameter names must be unique.");
> ```

It could be nice to inform in an exception which exact param is duplicate. We could do something like this,

Set<String> uniqueParmNames = new HashSet<>();
    Set<String> duplicateParamNames =
        parameters.stream().map(WinRmCommandParameter::getParameter).filter(param -> !uniqueParmNames.add(param)).collect(Collectors.toSet());

and log duplicate paramNames.

**Comment by vladimir-peric** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 824 at r2](https://reviewable.io/reviews/harness/harness-core/44881#-NQ4YTBxEkIdH9UeDGUw:-NQ4iq8j-oXx8ErjWDxZ:b-gm84sz) ([raw file](https://github.com/harness/harness-core/blob/1e031531de0b1422a16b2cea4a2830541a6726e2/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L824)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

It could be nice to inform in an exception which exact param is duplicate. We could do something like this,

Set<String> uniqueParmNames = new HashSet<>();
    Set<String> duplicateParamNames =
        parameters.stream().map(WinRmCommandParameter::getParameter).filter(param -> !uniqueParmNames.add(param)).collect(Collectors.toSet());

and log duplicate paramNames.

</blockquote></details>

Yes, I agree, I didn't pay too much details to the log listing, getting this enhanced.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 7 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881#-:-NQ5lnM14L4nnnYniTgi:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by vitsafronovici — DISMISSED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger checkstyle

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 409 at r5](https://reviewable.io/reviews/harness/harness-core/44881#-NQ6IFzt8lTsknoOIm15:-NQ7m-3y9lNXpHHe96a9:bf0nawz) ([raw file](https://github.com/harness/harness-core/blob/d278b7e470391eb0f72cb7c27d1d46a1ab5b75cf/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L409)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why do we have changes here? 
</blockquote></details>

I think this came up after I rebased the branch. Will need to get this sorted out.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 409 at r5](https://reviewable.io/reviews/harness/harness-core/44881#-NQ6IFzt8lTsknoOIm15:-NQ9clMPEYbKDqQxSalv:b-r3se9p) ([raw file](https://github.com/harness/harness-core/blob/d278b7e470391eb0f72cb7c27d1d46a1ab5b75cf/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L409)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

I think this came up after I rebased the branch. Will need to get this sorted out.
</blockquote></details>

Try to rebase with develop branch, or just copy and paste the valid code in this file.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java` line 409 at r5](https://reviewable.io/reviews/harness/harness-core/44881#-NQ6IFzt8lTsknoOIm15:-NQ9lzxI4BDxzpLp4qq_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d278b7e470391eb0f72cb7c27d1d46a1ab5b75cf/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java#L409)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Try to rebase with develop branch, or just copy and paste the valid code in this file.
</blockquote></details>

Done.

**Review by vitsafronovici — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44881#-:-NQAbDR0EV72mLxEfu_H:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
