### PR TITLE
fix: [CDS-54062]: Improving error message in case the filePath is empty.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
FilePaths is being checked for 2 cases, one while performing GitFetchTaskNG for override files and while performing GitTaskNG for manifest files. In this PR, we have updated the error message logs to cater to both the cases
Screenshot 2023-03-06 at 6 37 13 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44755)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Review by thisrohangupta — CHANGES_REQUESTED** [review]
@GoelPratyush99 can you say

"Path for values.yaml files is not valid. Check in the values.yaml setup in the manifest configuration to make sure it's not empty"

**Review by achyuth-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44755)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java` line 1421 at r3](https://reviewable.io/reviews/harness/harness-core/44755#-NPuqmt3072xHPvqKEhn:-NPuqmt3072xHPvqKEho:bzhzrhz) ([raw file](https://github.com/harness/harness-core/blob/e165a91c3f40739f5483f06a6a17304ac8d766cd/960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java#L1421)):*
> ```Java
>     if (isEmpty(request.getFilePaths())) {
>       throw new InvalidRequestException(
>           "Path for manifest files is not valid. Check in the file/folder path setup in the manifest configuration to make sure it's not empty",
> ```

Can we throw Hint + explanation exception instead? We usually do this for better readability

**Review by achyuth-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44755)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java` line 1421 at r3](https://reviewable.io/reviews/harness/harness-core/44755#-NPuqmt3072xHPvqKEhn:-NPur9vj6xJxxXDASzs-:b-kf7p5k) ([raw file](https://github.com/harness/harness-core/blob/e165a91c3f40739f5483f06a6a17304ac8d766cd/960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java#L1421)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Can we throw Hint + explanation exception instead? We usually do this for better readability
</blockquote></details>

Something like this: 
NestedExceptionUtils.hintWithExplanationException("Path for manifest files is not valid. Check in the file/folder path setup in the manifest configuration to make sure it's not empty",
          "Empty file/folder path", new InvalidRequestException(message));

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44755)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java` line 1421 at r3](https://reviewable.io/reviews/harness/harness-core/44755#-NPuqmt3072xHPvqKEhn:-NPv5U4e707fPK0Nod49:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e165a91c3f40739f5483f06a6a17304ac8d766cd/960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java#L1421)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Something like this: 
NestedExceptionUtils.hintWithExplanationException("Path for manifest files is not valid. Check in the file/folder path setup in the manifest configuration to make sure it's not empty",
          "Empty file/folder path", new InvalidRequestException(message));
</blockquote></details>

Done.

**Review by achyuth-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44755)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by achyuth-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44755#-:-NPv9tH-3sgQ8epLg3MU:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
