### PR TITLE
[fix]: [CDS-70889]: migrating k8s delete to k8s canary delete incase of canary workflow

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
Migrating k8s delete to k8s canary delete incase of canary workflow
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.
Screenshot 2023-06-28 at 2 06 23 AM
Screenshot 2023-06-28 at 2 06 34 AM

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49831)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by PragyeshMishra01** [comment]
trigger uts

**Review by srinivaswings — APPROVED** [review]

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49831)* status: 1 file(s) to review. 

___
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/49831#-NZ-RkvyBXS9KLg0rsZl:-NZ-RkvyBXS9KLg0rsZm:bzdmo3d) ([raw file](https://github.com/harness/harness-core/blob/907e2d41952a867b86c0e631ba77f9ff34031fc3/100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java#L43)):*
> ```Java
> public class K8sDeleteStepMapperImpl extends StepMapper {
>   private static final List<String> CANARY_DELETE_STEP_RESOURCE_PATTERNS = asList(
>       "^<\\+execution\\.steps\\.[^\\.]+\\.steps\\.[^\\.]+\\.canaryWorkload>$",
> ```

nit, does this full FQN needs to be here for matching canary workload patterns?
___
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/49831#-NZ-SL-b1I1TXzgy5w63:-NZ-SL-c9UvBNyK1DV-Q:bv2l706) ([raw file](https://github.com/harness/harness-core/blob/907e2d41952a867b86c0e631ba77f9ff34031fc3/100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java#L74)):*
> ```Java
>   }
> 
>   private boolean isDeleteStateK8sCanaryDelete(K8sDelete state) {
> ```

nit, could be renamed to `matchesK8sCanaryWorkoadPatterns` or something similar
___
*[`100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/49831#-NZ-RrsEB8xH6t7VukWM:-NZ-RrsEB8xH6t7VukWN:b-hz28s7) ([raw file](https://github.com/harness/harness-core/blob/907e2d41952a867b86c0e631ba77f9ff34031fc3/100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java#L76)):*
> ```Java
>   private boolean isDeleteStateK8sCanaryDelete(K8sDelete state) {
>     return Pattern.compile(CANARY_DELETE_STEP_RESOURCE_PATTERNS.get(0)).matcher(state.getResources()).matches()
>         || Pattern.compile(CANARY_DELETE_STEP_RESOURCE_PATTERNS.get(1)).matcher(state.getResources()).matches();
> ```

nit, if you add/remove from the patterns list, this code would need to be changed. You could iterate on the list of patterns without assuming only 2 entries.

**Comment by PragyeshMishra01** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/49831)_ status: 1 file(s) to review.
> 
> _[`100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/49831#-NZ-RkvyBXS9KLg0rsZl:-NZ-RkvyBXS9KLg0rsZm:bzdmo3d) ([raw file](https://github.com/harness/harness-core/blob/907e2d41952a867b86c0e631ba77f9ff34031fc3/100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java#L43)):_
> 
> > ```java
> > public class K8sDeleteStepMapperImpl extends StepMapper {
> >   private static final List<String> CANARY_DELETE_STEP_RESOURCE_PATTERNS = asList(
> >       "^<\\+execution\\.steps\\.[^\\.]+\\.steps\\.[^\\.]+\\.canaryWorkload>$",
> > ```
> 
> nit, does this full FQN needs to be here for matching canary workload patterns?
this pattern is now removed
> 
> _[`100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/49831#-NZ-SL-b1I1TXzgy5w63:-NZ-SL-c9UvBNyK1DV-Q:bv2l706) ([raw file](https://github.com/harness/harness-core/blob/907e2d41952a867b86c0e631ba77f9ff34031fc3/100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java#L74)):_
> 
> > ```java
> >   }
> > 
> >   private boolean isDeleteStateK8sCanaryDelete(K8sDelete state) {
> > ```
> 
> nit, could be renamed to `matchesK8sCanaryWorkoadPatterns` or something similar
Done
> 
> _[`100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/49831#-NZ-RrsEB8xH6t7VukWM:-NZ-RrsEB8xH6t7VukWN:b-hz28s7) ([raw file](https://github.com/harness/harness-core/blob/907e2d41952a867b86c0e631ba77f9ff34031fc3/100-migrator/src/main/java/io/harness/ngmigration/service/step/k8s/K8sDeleteStepMapperImpl.java#L76)):_
> 
> > ```java
> >   private boolean isDeleteStateK8sCanaryDelete(K8sDelete state) {
> >     return Pattern.compile(CANARY_DELETE_STEP_RESOURCE_PATTERNS.get(0)).matcher(state.getResources()).matches()
> >         || Pattern.compile(CANARY_DELETE_STEP_RESOURCE_PATTERNS.get(1)).matcher(state.getResources()).matches();
> > ```
> 
> nit, if you add/remove from the patterns list, this code would need to be changed. You could iterate on the list of patterns without assuming only 2 entries.
this pattern is now removed

**Review by puthrayaharness — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger uts

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49831)* status: 2 file(s) to review. 2. unresolved discussions.

**Comment by PragyeshMishra01** [comment]
trigger smartchecks

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger review

**Pull request merged**
