### PR TITLE
[feat]: [SRM-11069]:  If FailFast then stop creating new DataCollectionTasks and clean up already created  AnalysisOrchestrators, AnalysisStateMachines

### PR DESCRIPTION
**Pull request by kapil-harness**
…y created  AnalysisOrchestrator, AnalysisStateMachine

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)

### CODE REVIEW

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0-izBcTbTP1rcaMQ:-N7Y0-j-6NX8pi6BjqKa:bgil480) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L68)):*
> ```Java
>     log.info("Queuing analysis for verificationTaskId: {}, startTime: {}, endTime: {}", verificationTaskId, startTime,
>         endTime);
>     if (deploymentTimeSeriesAnalysisService.isAnalysisFailFastForLatestTimeRange(verificationTaskId)) {
> ```

add log
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0NOL2hrSIJnuyfBE:-N7Y0NOL2hrSIJnuyfBF:bmkgdnr) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L129)):*
> ```Java
> 
>       hPersistence.upsert(orchestratorQuery, updateOperations);
>       return;
> ```

this is deployment specific logic in the general orchestrate() method. Can we do this somewhere specific to that type ?



_Code quote:_
```Java
    if (deploymentTimeSeriesAnalysisService.isAnalysisFailFastForLatestTimeRange(
            orchestrator.getVerificationTaskId())) {
      Query<AnalysisOrchestrator> orchestratorQuery =
          hPersistence.createQuery(AnalysisOrchestrator.class)
              .filter(AnalysisOrchestratorKeys.verificationTaskId, orchestrator.getVerificationTaskId());

      List<AnalysisStateMachine> analysisStateMachines = orchestrator.getAnalysisStateMachineQueue();
      analysisStateMachines.forEach(analysisStateMachine -> analysisStateMachine.setStatus(AnalysisStatus.TERMINATED));
      stateMachineService.save(analysisStateMachines);

      UpdateOperations<AnalysisOrchestrator> updateOperations =
          hPersistence.createUpdateOperations(AnalysisOrchestrator.class)
              .setOnInsert(AnalysisOrchestratorKeys.verificationTaskId, orchestrator.getVerificationTaskId())
              .set(AnalysisOrchestratorKeys.status, AnalysisOrchestratorStatus.TERMINATED)
              .addToSet(AnalysisOrchestratorKeys.analysisStateMachineQueue, Arrays.asList(analysisStateMachines));

      hPersistence.upsert(orchestratorQuery, updateOperations);
      return;
    }
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 533 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0aPK8ZoCz6h5Y3Nw:-N7Y0aPK8ZoCz6h5Y3Nx:b2ni78f) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L533)):*
> ```Java
> 
>       if (deploymentTimeSeriesAnalysisService.isAnalysisFailFastForLatestTimeRange(verificationTaskId)) {
>         return;
> ```

log

**Comment by praveensugavanam** [comment]
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 535 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0qB9D1jzmLosmi2o:-N7Y0qB9D1jzmLosmi2p:b-hei2kc) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L535)):*
> ```Java
>         return;
>       }
> ```

what about cleaning up datacollection tasks that have already been created ?

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0-izBcTbTP1rcaMQ:-N7_sDcu7FrzWm_Yyq2E:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L68)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

add log
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0NOL2hrSIJnuyfBE:-N7_sF4c2hZ2yOMYx2TA:b-mmu46j) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L129)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

this is deployment specific logic in the general orchestrate() method. Can we do this somewhere specific to that type ?
</blockquote></details>

I am not sure where this logic can go as it has upset for AnalysisOrchestrator collection, let me know if you have an idea where this can go.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 533 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0aPK8ZoCz6h5Y3Nw:-N7_swo-7UoekOoAWj34:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L533)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

log
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 535 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0qB9D1jzmLosmi2o:-N7_sxFaAOh-4jNOCJCQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L535)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

what about cleaning up datacollection tasks that have already been created ? 
</blockquote></details>

done

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: 9 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/DeploymentTimeSeriesAnalysis.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/35558#-N7oddx7DEgRAId6xMEO:-N7oddx7DEgRAId6xMEP:br7a72) ([raw file](https://github.com/harness/harness-core/blob/6c2ee53a4d5bd5a06a024bd9356730cbfb91d0cb/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/DeploymentTimeSeriesAnalysis.java#L74)):*
> ```Java
>   private boolean isFailFast;
>   private List<DeploymentTimeSeriesAnalysisDTO.HostInfo> hostSummaries;
>   private List<DeploymentTimeSeriesAnalysisDTO.TransactionMetricHostData> transactionMetricSummaries;
> ```

failFast should be there for the Metric+Host level transaction failure too.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0NOL2hrSIJnuyfBE:-N7od22c3tpVLSuYE6Ov:bxmdtcc) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L129)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

I am not sure where this logic can go as it has upset for AnalysisOrchestrator collection, let me know if you have an idea where this can go.
</blockquote></details>

The Verification Type is separate at the Analysis State Machine level not at the orchestrator Level. Handling the orchestrator for the type of the state machine will be taking the abstraction above. But At least have it inside a separate method which is called based on status and inside the locking code block 
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImplTest.java` line 980 at r3](https://reviewable.io/reviews/harness/harness-core/35558#-N7oeBfV48cSMG2iUfSo:-N7oeBfV48cSMG2iUfSp:b-haz9f4) ([raw file](https://github.com/harness/harness-core/blob/6c2ee53a4d5bd5a06a024bd9356730cbfb91d0cb/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImplTest.java#L980)):*
> ```Java
>     assertThat(isAnalysisFailFast).isTrue();
>   }
> ```

Add a test case for the Analysis Orchestrator Aborted status scenario

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: 10 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/DeploymentTimeSeriesAnalysis.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/35558#-N7oddx7DEgRAId6xMEO:-N7wbFEA5YqNNCzVk5jT:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/dd4e574cb0236f81afc28713cb3fa5b1c81503e0/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/DeploymentTimeSeriesAnalysis.java#L74)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

failFast should be there for the Metric+Host level transaction failure too.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/35558#-N7Y0NOL2hrSIJnuyfBE:-N7wbHAUDVJmdQmKOvWJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9edabdad592dba6d1253a721e648840cae7c2d4e/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/impl/OrchestrationServiceImpl.java#L129)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

The Verification Type is separate at the Analysis State Machine level not at the orchestrator Level. Handling the orchestrator for the type of the state machine will be taking the abstraction above. But At least have it inside a separate method which is called based on status and inside the locking code block 
</blockquote></details>

done
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImplTest.java` line 980 at r3](https://reviewable.io/reviews/harness/harness-core/35558#-N7oeBfV48cSMG2iUfSo:-N7wbIjc5Fw4eBTqBLrP:b-w4uqp9) ([raw file](https://github.com/harness/harness-core/blob/dd4e574cb0236f81afc28713cb3fa5b1c81503e0/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImplTest.java#L980)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Add a test case for the Analysis Orchestrator Aborted status scenario
</blockquote></details>

added a UT for queueAnalysis(), still working on orchestrate()

**Comment by deepak-harness** [comment]
testOrchestrate_withFailFast_withoutStateMachine test case is failing. Can you check

**Review by kapil-harness — COMMENTED** [review]
done. removed this UT as it was not a valid scenario

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558#-:-N82V03N2_N6_ygzlZxG:bsxsy1i)* status: 10 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 4. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 4. unresolved discussions.

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: Some of the checks are too old. 10 file(s) to review. 1 change requests. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 538 at r6](https://reviewable.io/reviews/harness/harness-core/35558#-N8Ortts72SXKRZPIKlx:-N8Ortts72SXKRZPIKly:bw9rkwn) ([raw file](https://github.com/harness/harness-core/blob/568e8a40e86030224d320208d9c4b696f77b3fb6/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L538)):*
> ```Java
>             "DeploymentTimeSeriesAnalysis from LE is FailFast, so not creating DataCollectionTask for verificationTaskId: {}",
>             verificationTaskId);
>         List<DataCollectionTask> allDataCollectionTasks = dataCollectionTaskService.getAllDataCollectionTasks(
> ```

this is incorrect. We should only mark the incomplete tasks as ABORTED. The ones that are complete should be left alone as is. 

The method that's being called here doesnt filter by status. So maybe create a new method to do that ? 
```  @Override
  public List<DataCollectionTask> getAllDataCollectionTasks(String accountId, String verificationTaskId) {
    return hPersistence.createQuery(DataCollectionTask.class)
        .filter(DataCollectionTaskKeys.accountId, accountId)
        .filter(DataCollectionTaskKeys.verificationTaskId, verificationTaskId)
        .order(Sort.descending(DataCollectionTaskKeys.startTime))
        .asList();
  }```
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35558)

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java` line 538 at r6](https://reviewable.io/reviews/harness/harness-core/35558#-N8Ortts72SXKRZPIKlx:-N8Pp2Es2dkaH3XghNnR:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0cd516fd18f6a596210628178a69a18dd69bd178/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L538)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

this is incorrect. We should only mark the incomplete tasks as ABORTED. The ones that are complete should be left alone as is. 

The method that's being called here doesnt filter by status. So maybe create a new method to do that ? 
```  @Override
  public List<DataCollectionTask> getAllDataCollectionTasks(String accountId, String verificationTaskId) {
    return hPersistence.createQuery(DataCollectionTask.class)
        .filter(DataCollectionTaskKeys.accountId, accountId)
        .filter(DataCollectionTaskKeys.verificationTaskId, verificationTaskId)
        .order(Sort.descending(DataCollectionTaskKeys.startTime))
        .asList();
  }```
```

</blockquote></details>

done

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35558)* status: :shipit: complete! ✓

**Pull request merged**
