### PR TITLE
[feat]: [CDS-72746]: Integrated the setting for Create/Update GitOperations.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Changes: We now use a setting : GitX RepoAllowList which will restrict activities to only specified repos. Integration of setting with list-repo api was already done in a previous PR. This PR integrated the setting with CREATE/UPDATE flows.

Impact: Git Create/Update Flow are impacted with this PR.

Testing: Both Create/Update flow has been tested with empty, null , valid and invalid repoNames in repoAllowListSetting.

Screenshot 2023-06-28 at 4 00 19 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyHtRi3zjN7Bc4R6Pq:-NYyHtRi3zjN7Bc4R6Pr:b-9rrcke) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L52)):*
> ```Java
>   }
> 
>   public void validateRepoBasedOnGitXRepoAllowlistIfApplicable(
> ```

The method name shouldn't be this elaborative. The helper already mentions the use-case its trying to solve, so the method name should just be very pointed.

eg: validateRepo() is more than enough

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyI8Fn2r_qFhmq4i5r:-NYyI8Fn2r_qFhmq4i5s:b-cjyo55) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L55)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String repoName) {
>     List<String> repoAllowlist =
>         gitXSettingsHelper.getGitRepoAllowlist(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

lets move this call to a private method. We don't need to use gitxSettingsHelper everywhere.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyIJF02F_AdiXIMSD4:-NYyIJF02F_AdiXIMSD5:b-afqufu) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L57)):*
> ```Java
>         gitXSettingsHelper.getGitRepoAllowlist(accountIdentifier, orgIdentifier, projectIdentifier);
> 
>     if (!repoAllowlist.isEmpty() && !validateIfCurrentRepoIsAllowed(repoAllowlist, repoName)) {
> ```

can't we put the list empty check inside validateIfCurrentRepoIsAllowed()? This shall make it cleaner

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyIfclCtZ1XFGEQgi2:-NYyIfclCtZ1XFGEQgi3:b-9j37eu) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L59)):*
> ```Java
>     if (!repoAllowlist.isEmpty() && !validateIfCurrentRepoIsAllowed(repoAllowlist, repoName)) {
>       throw new InvalidRequestException(String.format(
>           "[repo: %s] is not allowed for GitExperience due to defaultSetting under current scope", repoName));
> ```

Lets add proper hints, explanations etc to the error.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 529 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyIs9SCxvrSHwBaA_T:-NYyIs9SCxvrSHwBaA_U:b8wpe0l) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L529)):*
> ```Java
>     Scope scope = scmCreateFileRequestDTO.getScope();
> 
>     gitRepoAllowlistHelper.validateRepoBasedOnGitXRepoAllowlistIfApplicable(scope.getAccountIdentifier(),
> ```

lets create a new method : "validateCreateFileRequest" or something similar and put this validation inside it. As we go on, there may be more validations and we can just put it at single place.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 596 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyJ18q3L1_rfwWQ113:-NYyJ18rAjC5F2dOykKp:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L596)):*
> ```Java
>     Scope scope = scmUpdateFileRequestDTO.getScope();
> 
>     gitRepoAllowlistHelper.validateRepoBasedOnGitXRepoAllowlistIfApplicable(scope.getAccountIdentifier(),
> ```

same as above

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 597 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NZ-KR0S7TpObXV5r3QY:-NZ-KR0S7TpObXV5r3QZ:b-kkdmch) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L597)):*
> ```Java
> 
>     gitRepoAllowlistHelper.validateRepoBasedOnGitXRepoAllowlistIfApplicable(scope.getAccountIdentifier(),
>         scope.getOrgIdentifier(), scope.getProjectIdentifier(), scmUpdateFileRequestDTO.getRepoName());
> ```

For update flow, do we really need to do this check?
1. Updates via UI, can be done only to the different branch but the same repo
2. Updates via api, we anyways do a metadata call, we can simply check if the repo passed as query param is same or not as the metadata

I understand this is a centralised place where you have added this check which has to deal with doing a extra db call to get the setting, on the contrary, what i suggested will just a simple condition check without an extra db call

@mohitg0795 what do you think?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: 2 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyHtRi3zjN7Bc4R6Pq:-NZ-deIX3oqZ6PpUVDqk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L52)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The method name shouldn't be this elaborative. The helper already mentions the use-case its trying to solve, so the method name should just be very pointed.

eg: validateRepo() is more than enough
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyI8Fn2r_qFhmq4i5r:-NZ-dzAn7EZynN3IvfYr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets move this call to a private method. We don't need to use gitxSettingsHelper everywhere.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyIJF02F_AdiXIMSD4:-NZ-f-7zDkH_OnRgala3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L57)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we put the list empty check inside validateIfCurrentRepoIsAllowed()? This shall make it cleaner
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyIfclCtZ1XFGEQgi2:-NZ-iQtmEAxEAID-lC7j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add proper hints, explanations etc to the error.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 529 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyIs9SCxvrSHwBaA_T:-NZ-fi-O2VqN6Jc51EFh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L529)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets create a new method : "validateCreateFileRequest" or something similar and put this validation inside it. As we go on, there may be more validations and we can just put it at single place.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 596 at r1](https://reviewable.io/reviews/harness/harness-core/49755#-NYyJ18q3L1_rfwWQ113:-NZ-fiIr3rAds20rLyjS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e5953314fbdde35171de35637826b34a71769d6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L596)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger review

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: 2 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1234 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ-zilc3pM-_tBA0CdM:-NZ-zilc3pM-_tBA0CdN:b-n9gmcs) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1234)):*
> ```Java
>     Scope scope = scmUpdateFileRequestDTO.getScope();
>     gitRepoAllowlistHelper.validateRepo(scope.getAccountIdentifier(), scope.getOrgIdentifier(),
>         scope.getProjectIdentifier(), scmUpdateFileRequestDTO.getRepoName());
> ```

We can have single function which takes the Scope and the repoName directly instead right?
Or instead when you are calling the validateRepo method pass a keyword telling what operation type it is and you can add this in the error/log message

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: 2 file(s) to review. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1234 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ-zilc3pM-_tBA0CdM:-NZ0-mvo6Huqk024uJ_s:byjpvj6) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1234)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

We can have single function which takes the Scope and the repoName directly instead right?
Or instead when you are calling the validateRepo method pass a keyword telling what operation type it is and you can add this in the error/log message
</blockquote></details>

Earlier this was implemented in a single method, but keeping in mind we can have more validations in future, separately for update and create flow hence 2 separate methods were introduced.

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1234 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ-zilc3pM-_tBA0CdM:-NZ00i4s-n7Gvf2GYZP4:bfmiau4) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1234)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Earlier this was implemented in a single method, but keeping in mind we can have more validations in future, separately for update and create flow hence 2 separate methods were introduced.
</blockquote></details>

got it
what do you think about "instead when you are calling the validateRepo method pass a keyword [Creation/Updation] telling what operation type it is and you can add this in the error/log message"?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ000GJ8Rqzvhr1EU8l:-NZ000GJ8Rqzvhr1EU8m:b-rd589i) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L59)):*
> ```Java
>       throw NestedExceptionUtils.hintWithExplanationException(
>           String.format(
>               "Please check if your current repo is an allowed repo in GitXRepoAllowlist under [default setting: %s].",
> ```

Never use terms that are related to your code in user error messages. eg: People will not understand whats "GitXRepoAllowlist".

Suggested messages:
Hint: "Please check if repo [<repo-name>] is in allowed repository list under default setting : <setting-name> for current <Project/Org/Account> scope.
Explanation: "GIT operations on Repo [<repo-name>] are restricted due to default setting : <setting-name> for current <pro/org/acc> scope.
Error: "Failed to perform GIT operation as access to repo [<repo-name>] is forbidden".

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ01jTZ6AbSHfQwA0KG:-NZ01jTZ6AbSHfQwA0KH:b-lsz6aw) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L63)):*
> ```Java
>           String.format(
>               "[repo: %s] is not allowed for GitExperience due to default setting under current scope.", repoName),
>           new ScmUnauthorizedException(String.format("Access to [repo: %s] is Denied for GitExperience", repoName)));
> ```

lets not use Scm based exceptions as those are only for GIT operations. This is a validation exception so either we can create something new or we can use InvalidRequestException which is being used currently in other validations.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1234 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ-zilc3pM-_tBA0CdM:-NZ0DEAM89fnE53YbFxP:beg6aeg) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1234)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

got it
what do you think about "instead when you are calling the validateRepo method pass a keyword [Creation/Updation] telling what operation type it is and you can add this in the error/log message"?
</blockquote></details>

This can be another good way of doing it, but i think both are apt, maybe in future better decisions could be made seeing on what all different validations are required in create and update flow.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ000GJ8Rqzvhr1EU8l:-NZ0EPcoDCfNtj-2Bi-e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Never use terms that are related to your code in user error messages. eg: People will not understand whats "GitXRepoAllowlist".

Suggested messages:
Hint: "Please check if repo [<repo-name>] is in allowed repository list under default setting : <setting-name> for current <Project/Org/Account> scope.
Explanation: "GIT operations on Repo [<repo-name>] are restricted due to default setting : <setting-name> for current <pro/org/acc> scope.
Error: "Failed to perform GIT operation as access to repo [<repo-name>] is forbidden".
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/49755#-NZ01jTZ6AbSHfQwA0KG:-NZ0EPH-4iqxNuOpejHF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f76bfec94e37ed38d80f31f68f7b72a94a0a0d3/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets not use Scm based exceptions as those are only for GIT operations. This is a validation exception so either we can create something new or we can use InvalidRequestException which is being used currently in other validations.
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49755)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
