### PR TITLE
fix: [CDS-42440]: helm repo flags fix

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
Make https://github.com/harness/harness-core/pull/35701 backward compatible with older delegate.
Helm v2 deployments were failing as they were trying to use repo flags.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36894)

### CODE REVIEW

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36894)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36894)

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
trigger ti0

**Comment by abhinavsingh1196** [comment]
trigger ti1,ti2

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36894)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 911 at r3](https://reviewable.io/reviews/harness/harness-core/36894#-NAeqmgbCO8eQCzcsoxO:-NAeqmgcDWp5aBXBGyEw:b-2700uj) ([raw file](https://github.com/harness/harness-core/blob/cbd774045833174be6363ed92df2928a0c20334a/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L911)):*
> ```Java
>       details here: https://harness.atlassian.net/wiki/spaces/CDP/pages/21134344193/Helm+FFs+cleanup
>      */
>     boolean useCache =
> ```

@achyuth-harness should there be a check here filtering out helm v2? 
see commit: https://github.com/harness/harness-core/pull/36894/commits/cbd774045833174be6363ed92df2928a0c20334a

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36894)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 911 at r3](https://reviewable.io/reviews/harness/harness-core/36894#-NAeqmgbCO8eQCzcsoxO:-NAhBJxw5wfIxreOxoF9:bm5t7b2) ([raw file](https://github.com/harness/harness-core/blob/cbd774045833174be6363ed92df2928a0c20334a/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L911)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

@achyuth-harness should there be a check here filtering out helm v2? 
see commit: https://github.com/harness/harness-core/pull/36894/commits/cbd774045833174be6363ed92df2928a0c20334a
</blockquote></details>

Yes, as for helm v2 these flags mostly aren't supported

**Comment by abhinavsingh1196** [comment]
trigger ti0,ti1,ti2,ti3,ti4

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 3 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36894)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger ti0

**Comment by achyuth-harness** [comment]
trigger ti1

**Comment by achyuth-harness** [comment]
trigger ti2

**Comment by achyuth-harness** [comment]
trigger ti3

**Comment by achyuth-harness** [comment]
trigger ti4

**Comment by abhinavsingh1196** [comment]
trigger ti0,ti1,ti2,ti3,ti4

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36894)* status: :shipit: complete! ✓

**Pull request merged**
