### PR TITLE
feat: [PL-27152]: added caller context details to GET Templates API

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
tried to fetch template when parent entity url is provided and when its not provided

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36167)

**Review by inderschera — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/36167#-N90v7qk7fE7LgWtYRlY:-N90v7qm5g0dCd0-pxzW:brpat5x) ([raw file](https://github.com/harness/harness-core/blob/9fc7a44f386f7673e4fb71f6f78e1187478b8726/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L107)):*
> ```Java
>     if (!GitAwareContextHelper.isNullOrDefault(gitEntityInfo.getParentEntityRepoURL())
>         && !gitEntityInfo.getParentEntityRepoURL().equals(entityRepoURL)) {
>       branchName = "";
> ```

Does empty branch means, it will fetch from default branch of repo?

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/36167#-N90v7qk7fE7LgWtYRlY:-N910KYu4YbtTytzO4q-:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/9fc7a44f386f7673e4fb71f6f78e1187478b8726/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L107)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Does empty branch means, it will fetch from default branch of repo?
</blockquote></details>

yes

**Review by inderschera — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger codebasehash

**Review by adivishy1 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)* status: 3 file(s) to review.

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36167)* status: :shipit: complete! ✓

**Pull request merged**
