### PR TITLE
fix:[CDS-69101]: Change query to execute in batches to avoid read timeout when huge service list

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- A query using 1175 services reaches timeout, and running the same query from a pgAdmin it returned after 1 min 47 secs.
- When the account has many services the query to retrieve the license usage takes much time and exceeds the connection timeout. For the verified accounts I see around +1k services related that are taking ~1 minute to retrieve the result.
- I execute a query explain command and the result shows we are using an index during the search.
- The first action is to change the code to execute the query in small batches to avoid read timeout.
- The next phase if needed, is to execute each batch in its own thread to reduce the execution round trip overall.

## Comment Triggers
<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47693)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]

**Comment by Fernando-Dourado** [comment]
trigger uts

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47693)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/47693#-NVDOp2W9UgqYLvo6m70:-NVDOp2XExH9p95RDW9q:b-flsg4i) ([raw file](https://github.com/harness/harness-core/blob/d45362330c93c75f4ec84b05097e874d9573d222/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L59)):*
> ```Java
> 
>   @VisibleForTesting
>   Map<String, CgServiceUsage> queryPercentileInstanceForServices(String accountId, List<String> svcIds) {
> ```

nit, this is not Business logic, would it make sense to move it to DB layer?

This would make this service cleaner and the method itself reusable from other places.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47693)* status: 4 file(s) to review.

**Comment by Fernando-Dourado** [comment]
trigger review

**Comment by Fernando-Dourado** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/47693)_ status: 4 file(s) to review. 1 of 2 approvals obtained.
> 
> _[`400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/47693#-NVDOp2W9UgqYLvo6m70:-NVDOp2XExH9p95RDW9q:b-flsg4i) ([raw file](https://github.com/harness/harness-core/blob/d45362330c93c75f4ec84b05097e874d9573d222/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L59)):_
> 
> > ```java
> >   @VisibleForTesting
> >   Map<String, CgServiceUsage> queryPercentileInstanceForServices(String accountId, List<String> svcIds) {
> > ```
> 
> nit, this is not Business logic, would it make sense to move it to DB layer?
> 
> This would make this service cleaner and the method itself reusable from other places.

@vaibhav-si I agree. I decide to use that way to easily unit test it, the best approach is to use a new class with parallel rules working as a facade before the DB layer. When the second phase comes, I can do it that way.

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Pull request merged**
