### PR TITLE
[fix]: [CDS-35152]: Concurrent Execution of AMI Infrastructure creating invalid inframappings fixed

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32693)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32693)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/test/resources/mongo/indexes.txt` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/32693#-N13CUixA9Pl2QjHzn5I:-N13CUixA9Pl2QjHzn5J:bzf6glo) ([raw file](https://github.com/harness/harness-core/blob/8ba4c523c5563884b84dbe0f33ab5873cd488b3c/120-ng-manager/src/test/resources/mongo/indexes.txt#L125)):*
> ```help
> cloudFormationRollbackConfig {"name": "appId_1", "background": true} {"appId": 1}
> cloudFormationRollbackConfig {"name": "awsConfigId_1", "background": true} {"awsConfigId": 1}
> cloudFormationRollbackConfig {"name": "byAppAndEntityAndAwsConfig", "background": true} {"appId": 1, "entityId": 1, "awsConfigId": 1, "createdAt": 1}
> ```

is this related to broken tests in develop ?
___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java` line 564 at r1](https://reviewable.io/reviews/harness/harness-core/32693#-N13CQCP1gmW76St97Hq:-N13CQCP1gmW76St97Hr:byknv2f) ([raw file](https://github.com/harness/harness-core/blob/8ba4c523c5563884b84dbe0f33ab5873cd488b3c/400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java#L564)):*
> ```Java
>         && ((AwsInfrastructureMapping) infraMapping).getAwsInstanceFilter() != null) {
>       try {
>         wingsPersistence.updateField(AwsInfrastructureMapping.class, savedInfraMapping.getUuid(), "awsInstanceFilter",
> ```

maybe use ```AwsInstanceInfrastructureKeys.awsInstanceFilter``` instead



_Code quote (from 400-rest/src/main/java/software/wings/infra/AwsInstanceInfrastructure.java):_
```Java
AwsInstanceInfrastructureKeys.awsInstanceFilter
```

**Comment by arvind-choudhary-h** [comment]
*[`120-ng-manager/src/test/resources/mongo/indexes.txt` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/32693#-N13CUixA9Pl2QjHzn5I:-N13CmCk19rg7Qz8GCxm:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/8ba4c523c5563884b84dbe0f33ab5873cd488b3c/120-ng-manager/src/test/resources/mongo/indexes.txt#L125)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this related to broken tests in develop ?
</blockquote></details>

Yes

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java` line 564 at r1](https://reviewable.io/reviews/harness/harness-core/32693#-N13CQCP1gmW76St97Hq:-N13CnO74ZAA0fJvdYzm:b8rv1ik) ([raw file](https://github.com/harness/harness-core/blob/8ba4c523c5563884b84dbe0f33ab5873cd488b3c/400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java#L564)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe use ```AwsInstanceInfrastructureKeys.awsInstanceFilter``` instead
</blockquote></details>

I tried it. It starts throwing lombok exceptions - https://app.harness.io/ng/#/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/Compile/executions/qdVIv-w9SFO7HGSuWRXF9A/pipeline

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32693)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java` line 564 at r1](https://reviewable.io/reviews/harness/harness-core/32693#-N13CQCP1gmW76St97Hq:-N13DWBYE-YAHK5vJtRb:bj84a8b) ([raw file](https://github.com/harness/harness-core/blob/8ba4c523c5563884b84dbe0f33ab5873cd488b3c/400-rest/src/main/java/software/wings/service/impl/InfrastructureMappingServiceImpl.java#L564)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

I tried it. It starts throwing lombok exceptions - https://app.harness.io/ng/#/account/VRuJ8-dqQH6QZgAtoBr66g/ci/orgs/default/projects/PRCHECKS/pipelines/Compile/executions/qdVIv-w9SFO7HGSuWRXF9A/pipeline
</blockquote></details>

maybe because you were doing static import of ```AwsInstanceInfrastructureKeys.awsInstanceFilter```

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32693)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32693)* status: :shipit: complete! ✓

**Pull request merged**
