### PR TITLE
feat: [IDP-179]: Gitlab connector implementation

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44407)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44407)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/GitIntegrationConstants.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/44407#-NPHnhCn5Uy_Z0f_Rkwf:-NPHnhCn5Uy_Z0f_Rkwg:bi9cgyx) ([raw file](https://github.com/harness/harness-core/blob/e37494545f01a30dc281a44df52da8d1e4618952/idp-service/service/src/main/java/io/harness/idp/gitintegration/GitIntegrationConstants.java#L10)):*
Can we add @UtilityClass annotation to this class?
> A utility class is a class that is just a namespace for functions. No instances of it can exist, and all its members are static.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/GitIntegrationConstants.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/44407#-NPHl9gp7yPtQqWBnhr-:-NPHl9gp7yPtQqWBnhr0:b-v2ep6z) ([raw file](https://github.com/harness/harness-core/blob/e37494545f01a30dc281a44df52da8d1e4618952/idp-service/service/src/main/java/io/harness/idp/gitintegration/GitIntegrationConstants.java#L19)):*
> ```Java
>   public static final String GITLAB_TOKEN = "GITLAB_TOKEN";
>   public static final String GITLAB_CONNECTOR_TYPE = "Gitlab";
>   public static final String GITLAB_CONNECTOR_AUTH_TYPE = "UsernameToken";
> ```

nit: Could we have a common constant for both Github and Gitlab for UsernameToken?
___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GitlabConnectorProcessor.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/44407#-NPHlyNYCKqruK8_7a7P:-NPHlyNZDoqyS9AyariM:brn7322) ([raw file](https://github.com/harness/harness-core/blob/e37494545f01a30dc281a44df52da8d1e4618952/idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GitlabConnectorProcessor.java#L34)):*
> ```Java
>     List<EnvironmentSecret> resultList = new ArrayList<>();
> 
>     if (!connectorDTO.isPresent()) {
> ```

nit: we could use connectorDTO.isEmpty() instead
___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GitlabConnectorProcessor.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44407#-NPHmKuw5qAZE4FNE7TT:-NPHmKuw5qAZE4FNE7TU:b-4qrkp9) ([raw file](https://github.com/harness/harness-core/blob/e37494545f01a30dc281a44df52da8d1e4618952/idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GitlabConnectorProcessor.java#L50)):*
> ```Java
>     if (!outcome.getType().toString().equals(GitIntegrationConstants.GITLAB_CONNECTOR_AUTH_TYPE)) {
>       throw new InvalidRequestException(String.format(
>           " Authentication is not Username and Token for Gitlab Connector with id - [%s] ", connectorIdentifier));
> ```

Can we add the account identifier as well in all the log messages? it would help in debugging later

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44407)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/GitIntegrationConstants.java` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/44407#-NPHnhCn5Uy_Z0f_Rkwf:-NPI-9pyAFlycIPgc-R7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e37494545f01a30dc281a44df52da8d1e4618952/idp-service/service/src/main/java/io/harness/idp/gitintegration/GitIntegrationConstants.java#L10)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add @UtilityClass annotation to this class?
> A utility class is a class that is just a namespace for functions. No instances of it can exist, and all its members are static.
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GitlabConnectorProcessor.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44407#-NPHmKuw5qAZE4FNE7TT:-NPI-7Av5-klzXmIPwCH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e37494545f01a30dc281a44df52da8d1e4618952/idp-service/service/src/main/java/io/harness/idp/gitintegration/implementation/GitlabConnectorProcessor.java#L50)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add the account identifier as well in all the log messages? it would help in debugging later
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44407)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by sandeepa-kv-jois — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44407)* status: :shipit: complete! ✓

**Pull request merged**
