### PR TITLE
feat: [CDS-49910]: added stage schema validation for TAS

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added pipeline schema validation for TAS

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42437)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by anilchowdhury-harness** [comment]
@RishabhGupta34 
did you do sanity for Deployment Template ?

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42437#-:-NLRbL917v64b5vDyBrm:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by RishabhGupta34** [comment]
> @RishabhGupta34 did you do sanity for Deployment Template ?

yes, have done

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42437)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/validator/TasValidator.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/42437#-NLeOcYx4zRCEO-pMmBn:-NLeOcYx4zRCEO-pMmBo:bas1iy7) ([raw file](https://github.com/harness/harness-core/blob/249e5b08c5114cbad65f8e1f3b71c7d52477d840/125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/validator/TasValidator.java#L8)):*
> ```Java
>  */
> 
> package io.harness.cdng.visitor.helpers.deploymentstage.validator;
> ```

nit, pls add tests for these methods

**Comment by RishabhGupta34** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42437)_ status: 6 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/validator/TasValidator.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/42437#-NLeOcYx4zRCEO-pMmBn:-NLeOcYx4zRCEO-pMmBo:bas1iy7) ([raw file](https://github.com/harness/harness-core/blob/249e5b08c5114cbad65f8e1f3b71c7d52477d840/125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/validator/TasValidator.java#L8)):_
> 
> > ```java
> >  */
> > 
> > package io.harness.cdng.visitor.helpers.deploymentstage.validator;
> > ```
> 
> nit, pls add tests for these methods

yes, I'm working on them as part of separate ticket

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/DeploymentStageVisitorHelper.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/42437#-NLeeDnIEY5ODAlMFrWH:-NLeeDnJ1KcLS11YqA13:b-s1o143) ([raw file](https://github.com/harness/harness-core/blob/249e5b08c5114cbad65f8e1f3b71c7d52477d840/125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/DeploymentStageVisitorHelper.java#L41)):*
> ```Java
>   public Set<EntityDetailProtoDTO> addReference(Object object, String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, Map<String, Object> contextMap) {
>     DeploymentStageValidator pipelineValidationHelper =
> ```

lets call this "stage Validator" helper

**Comment by RishabhGupta34** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/DeploymentStageVisitorHelper.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/42437#-NLeeDnIEY5ODAlMFrWH:-NLegiwA5F_8niQ6R6vs:b-kcenwr) ([raw file](https://github.com/harness/harness-core/blob/249e5b08c5114cbad65f8e1f3b71c7d52477d840/125-cd-nextgen/src/main/java/io/harness/cdng/visitor/helpers/deploymentstage/DeploymentStageVisitorHelper.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets call this "stage Validator" helper
</blockquote></details>

the class itself? or just the variable name

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42437#-:-NLfNQ3E3xYVFbEssFIV:bnfp4nl)* status: 8 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 8 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42437)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42437#-:-NM2ndpK2lk45V1enHkq:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
