### PR TITLE
feat: [PL-23944]: Added more logs to find the root cause

### PR DESCRIPTION
**Pull request by Y0709**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35815)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35815)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 343 at r1](https://reviewable.io/reviews/harness/harness-core/35815#-N838jQ83nSvyQajtK4A:-N838jQ83nSvyQajtK4B:bb7pa6j) ([raw file](https://github.com/harness/harness-core/blob/f4a4bc1161f1d8706c6417a7b587d7261e97bc51/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L343)):*
> ```Java
>       } catch (Exception ex) {
>         // If there was any exception, remove that entry from cache
>         // TO DO log exception
> ```

todo

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35815)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 382 at r1](https://reviewable.io/reviews/harness/harness-core/35815#-N838zMu77MO9baqOSR2:-N838zMu77MO9baqOSR3:bulwy9h) ([raw file](https://github.com/harness/harness-core/blob/f4a4bc1161f1d8706c6417a7b587d7261e97bc51/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L382)):*
> ```Java
> 
>   private void logApiKeyPermissions(UserPermissionInfo apiKeyPermissionInfo) {
>     try {
> ```

Lets use only one try catch and include both the permissions there only

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35815)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ershadalim — APPROVED** [review]

**Review by ershadalim — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35815)* status: Some of the checks are too old. 3 file(s) to review.

**Pull request merged**
