### PR TITLE
fix: [DEL-2135]: Upgrading AsyncHttpClient to 2.12.3

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 634 at r1](https://reviewable.io/reviews/harness/harness-core/32097#-MzzaOos2bkv2mhHawH5:-MzzaOos2bkv2mhHawH6:bixzynk) ([raw file](https://github.com/harness/harness-core/blob/c975a33bf89df748329db7d6f584976b6bf43ae8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L634)):*
> ```Java
>             .on(new Function<IOException>() {
>               @Override
>               public void on(IOException ioe) {
> ```

wouldn't this mean that we will not retry to make a websocket connection?

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 636 at r1](https://reviewable.io/reviews/harness/harness-core/32097#-N--HtDy-7KOgl6OjRd_:-N--HtDy-7KOgl6OjRda:b-utsiv7) ([raw file](https://github.com/harness/harness-core/blob/c975a33bf89df748329db7d6f584976b6bf43ae8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L636)):*
> ```Java
>               public void on(IOException ioe) {
>                 log.error("Error occured while starting Delegate");
>                 ioe.printStackTrace();
> ```

log the exception in the previous line instead of this

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 634 at r1](https://reviewable.io/reviews/harness/harness-core/32097#-MzzaOos2bkv2mhHawH5:-N-1Sc647peFyZLgey_x:b-uwwq03) ([raw file](https://github.com/harness/harness-core/blob/c975a33bf89df748329db7d6f584976b6bf43ae8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L634)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

wouldn't this mean that we will not retry to make a websocket connection?
</blockquote></details>

We will, those events will be separately handled by Event OPEN and CLOSE. This event is to handle other IOExceptions.
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 636 at r1](https://reviewable.io/reviews/harness/harness-core/32097#-N--HtDy-7KOgl6OjRd_:-N-1T8QPDQNO9vUjTi1l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c975a33bf89df748329db7d6f584976b6bf43ae8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L636)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

log the exception in the previous line instead of this
</blockquote></details>

Done.

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: 1. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: 1. unresolved discussions.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 3 of 9 files at r1, 2 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: :shipit: complete! ✓

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: Some of the checks are too old.

**Review by gaurav-jain1 — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 2 of 3 files at r2, 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: Some of the checks are too old.

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger ti0

**Comment by gaurav-jain1** [comment]
trigger ti0

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 4 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32097)* status: :shipit: complete! ✓

**Pull request merged**
