### PR TITLE
feat: [DEL-5055]: Enhanced error message on missing selectors to include selector names

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes
Enhanced error message on UI for the case when there are no delegates found with required selectors.

Also made a few clean up changes, returning false instead of variable names to make the intend clear.

image

image

image

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46250)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1062 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS1FeR3aIcPRI2ktWX:-NSS1FeR3aIcPRI2ktWY:b-cu8zrd) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1062)):*
> ```Java
>       log.debug("Delegate {} does not support task {} which is of type {}", delegateId, task.getUuid(),
>           task.getTaskDataV2().getTaskType());
>       return false;
> ```

how can intent not clear here? It only goes inside the loop if canAssignTaskToDelegate is false?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1093 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS1Y0H6HCUdzDQcmYe:-NSS1Y0H6HCUdzDQcmYf:bovflrn) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1093)):*
> ```Java
>               .collect(Collectors.toSet());
>       final String noMatchingSelectorsMessage = CAN_NOT_ASSIGN_SELECTOR_TASK_GROUP + " " + selectors;
> ```

This is showing task selector. Right now it is only intended for displaying delegate selectors, I see delegate selectors are not included here. If we are adding both then we need to show AND selectors match with the delegate.  For example, if task comes with 2 selectors then we need to show with AND condition

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS2Vxc5y6Q4uXCjRb_:-NSS2Vxc5y6Q4uXCjRba:b-rwf9lz) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L103)):*
> ```Java
>   public static final String CAN_NOT_ASSIGN_DELEGATE_SCOPE_GROUP = "Delegate scope(s) mismatched";
>   public static final String CAN_NOT_ASSIGN_PROFILE_SCOPE_GROUP = "Delegate profile scope(s) mismatched ";
>   public static final String CAN_NOT_ASSIGN_SELECTOR_TASK_GROUP = "No matching selectors";
> ```

Selectors can be one or more than one.  (s) is a common way of showing that.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 962 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS2mOy712jmyXkQKId:-NSS2mOz9QC_XqI4anjb:b-9qatpv) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L962)):*
> ```Java
>         task.getNonAssignableDelegates().put(CAN_NOT_ASSIGN_OWNER, Collections.emptyList());
>         delegateTaskServiceClassic.addToTaskActivityLog(task, CAN_NOT_ASSIGN_OWNER);
>         return List.of();
> ```

i would recommend keeping as it's this one

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 955 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS2sa5B3zG3Aeh6kCy:-NSS2sa5B3zG3Aeh6kCz:b-mf0n85) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L955)):*
> ```Java
>         task.getNonAssignableDelegates().putIfAbsent(NO_ACTIVE_DELEGATES, Collections.emptyList());
>         delegateTaskServiceClassic.addToTaskActivityLog(task, NO_ACTIVE_DELEGATES);
>         return List.of();
> ```

what happens if there are no available delegates installed?  Maybe it's taken care other places, but please confirm. Test needed for sync and async task for both CG and NG

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46250)* status: 0 of 1 approvals obtained.

**Review by gn-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46250)* status: 1 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 955 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS2sa5B3zG3Aeh6kCy:-NSSDdq29tW6_L8tTxLl:b-6yn0d7) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L955)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

what happens if there are no available delegates installed?  Maybe it's taken care other places, but please confirm. Test needed for sync and async task for both CG and NG
</blockquote></details>

So when you throw this exception, it is caught in the same function and then we are returning empty eligibleDelegates at the end.

So there is no behavior change - the only thing it solves is, reducing duplicate logs, as the calling function is logging it too.
___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 962 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS2mOy712jmyXkQKId:-NSSCSoz5_tzUTM1UFrB:b-pzerbi) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L962)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i would recommend keeping as it's this one
</blockquote></details>

These were nits - but when I reading the code, I had to understand where all these fields could have been populated. That is why I made it clear that if we have entered this block, there is nothing we are returning

makes sense, right?
___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1062 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS1FeR3aIcPRI2ktWX:-NSSFLGUBaYA6vBR966h:bgayzjm) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1062)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

how can intent not clear here? It only goes inside the loop if canAssignTaskToDelegate is false?
</blockquote></details>

False is just being explicit - there are 5 lines of code after the if-check and someone can add more like the way I did below.
___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 1093 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS1Y0H6HCUdzDQcmYe:-NSSSnlX5JL2ica2ypHG:bd1a7u) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L1093)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

This is showing task selector. Right now it is only intended for displaying delegate selectors, I see delegate selectors are not included here. If we are adding both then we need to show AND selectors match with the delegate.  For example, if task comes with 2 selectors then we need to show with AND condition
</blockquote></details>

I am just updating the key with the selector names. so in the summary view, we will also see the selectors now, and in the selection log also, we will have this updated key
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/46250#-NSS2Vxc5y6Q4uXCjRb_:-NSST_4W18fq5XwoHBUK:blvfavl) ([raw file](https://github.com/harness/harness-core/blob/1f14cefac023109f17e5455e5d11554c54d9b187/400-rest/src/main/java/software/wings/service/impl/DelegateSelectionLogsServiceImpl.java#L103)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Selectors can be one or more than one.  (s) is a common way of showing that.
</blockquote></details>

sounds good. Updated log message as per Raghu's suggestion and updated snapshots on the UI too.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46250)* status: 5. unresolved discussions. 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46250)* status: 1. unresolved discussions.

**Pull request merged**
