### PR TITLE
fix: [CDS-70559]: Adding support to resolve eventpayload trigger expressio…

### PR DESCRIPTION
**Pull request by Y0709**
…ns on rerun of pipeine

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48450)

### CODE REVIEW

**Review by rathodmeetsatish — APPROVED** [review]

**Comment by Y0709** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48450)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java` line 658 at r2](https://reviewable.io/reviews/harness/harness-core/48450#-NWaizUf2SYPvts2Ev6v:-NWaizUf2SYPvts2Ev6w:b-wcvq9k) ([raw file](https://github.com/harness/harness-core/blob/255138e0ae9d729c67b21e7a3ffb88285a36be3a/980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java#L658)):*
> ```Java
>         unresolvedExpressions.addAll(ex.fetchExpressions());
>         return createExpression(expression);
>       } catch (Exception ex) {
> ```

dummy comment, will remove later

**Review by diptiman-adak — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48450)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/NGTriggerExpressionEvaluator.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/48450#-NWappqrAg2IS8lai-xb:-NWappqs9zf2wfwVKWuP:bb7p34n) ([raw file](https://github.com/harness/harness-core/blob/255138e0ae9d729c67b21e7a3ffb88285a36be3a/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/NGTriggerExpressionEvaluator.java#L14)):*
> ```Java
> import io.harness.engine.executions.plan.PlanExecutionMetadataService;
> import io.harness.expression.EngineExpressionEvaluator;
> import io.harness.ngtriggers.expressions.functors.EventPayloadFunctor;
> ```

test

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/NGTriggerExpressionEvaluator.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/48450#-NWapwTR996WKjsEYIJp:-NWaq0_o2TiG8sastcTN:bb7p34n) ([raw file](https://github.com/harness/harness-core/blob/255138e0ae9d729c67b21e7a3ffb88285a36be3a/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/NGTriggerExpressionEvaluator.java#L13)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

new test comment
</blockquote></details>

test

**Review by archit-harness — DISMISSED** [review]

**Comment by Y0709** [comment]
trigger uts

**Review by AbhijithHarness — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48450)* status: 4 file(s) to review. 2 change requests.

**Comment by Y0709** [comment]
trigger messagecheck, review

**Review by mohitg0795 — APPROVED** [review]

**Review by diptiman-adak — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48450#-:-NWfAMR0CZKivHOTt7Ak:bnfp4nl)* status: 4 file(s) to review.

**Pull request merged**
