### PR TITLE
[feat]: [CDS-7994]: Improving error messages for k8s exceptions

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
The aim here is to improve the overall user experience by supplementing the propagated error with more helpful hints/explanations, instead of passing generic errors. 

Change summary:
- Error message from CLI error stream propagated to the exception handler.
- New runtime exception with Kubectl command subtype introduced.
- Handled some common errors inside exception handler.
- Improved some error hints/explanations.
- Kubectl binary path added to error message.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30676)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
trigger codebasehash

**Comment by abhinavsingh1196** [comment]
trigger ti3

**Comment by abhinavsingh1196** [comment]
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 834 at r1](https://reviewable.io/reviews/harness/harness-core/30676#-MvYZAMMALV1RVvoO0DJ:-MvYq4Ql39u6ySXpuWmr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/171862a475dc7bbd1bf6dca4a97231aabdac3db4/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L834)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

would it possible to move this logic to executeCommand?
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesApiExceptionHandler.java, line 96 at r1](https://reviewable.io/reviews/harness/harness-core/30676#-MvYOGJ53c9YMlpFXVGS:-MvYq8e6AE0DF2oOv6Ie:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/171862a475dc7bbd1bf6dca4a97231aabdac3db4/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesApiExceptionHandler.java#L96)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can we create pattern as a static instead of String UNAUTHORIZED_ERROR_REGEX, it doesn't make sense to compile it every time
</blockquote></details>

Done.

**Comment by abhinavsingh1196** [comment]
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesCliRuntimeExceptionHandler.java, line 154 at r1](https://reviewable.io/reviews/harness/harness-core/30676#-MvYUjFk13rtyWCpsqCD:-MvYqARX5U_05k2jDZew:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/171862a475dc7bbd1bf6dca4a97231aabdac3db4/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesCliRuntimeExceptionHandler.java#L154)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we precompile this regexes and have as argument Pattern?
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30676)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger license/cla

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30676)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger codebasehash

**Comment by abhinavsingh1196** [comment]
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, line 330 at r3](https://reviewable.io/reviews/harness/harness-core/30676#-MvbvzAk8kHTtGzyT69j:-Mvc7kayAtD9xcvz_Tp2:b-jp38mo) ([raw file](https://github.com/harness/harness-core/blob/dca8eb79d41b63953c1d15ac5b59c2b5bfb8292c/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L330)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

I can see that we are writing to `errorCaptureStream` and printing the content, but where is it closed?
</blockquote></details>

The stream is defined within the try() block, so it will automatically be destroyed when the function exits.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30676)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — DISMISSED** [review]
> Reviewed 7 of 15 files at r1, 2 of 4 files at r2, 1 of 5 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30676)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30676)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30676#-:-MvcbRzK6Y-i7lwPo7A1:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
