### PR TITLE
fix: [CDS-69342]: use jsonNode for field yaml in execution input helper

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** We are saving a field yaml for the stage that contains an execution input. We are first storing its yaml string then converting it to JSON node to create yamlMap and resolve expressions and then converting it to yaml string again to save in the DB. With this serialization and deserialization, in some cases, we end up with an invalid yaml like when we have an expression inside a shell script, after rendering the expression, we had quotes inside quotes that were not escaped. 

**Changes:** We are dealing only with jsonNode for creating yaml map and resolving expression and after all of this processing is done, we convert this jsonNode to yaml string and save it in DB. This resolves our problem of preserving escape characters inside the shell script.

**Testing:** Tested the following cases locally:
- Have a secret in the same stage with an execution input var, refer to that secret in the shell script.
- Have a secret in the same stage with an execution input var, refer to that secret in a multi line shell script.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut3

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 6 file(s) to review.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/48319#-NWILJVT8icH_EAjqNcM:-NWILJVT8icH_EAjqNcN:boza54l) ([raw file](https://github.com/harness/harness-core/blob/7544a1d6858d91094446915d6a22217f547af994/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java#L98)):*
> ```Java
>                                      .nodeExecutionId(nodeExecutionId)
>                                      .fieldYaml(YamlUtils.writeYamlString(fieldYaml))
>                                      .template(node.getExecutionInputTemplate())
> ```

@shalini-agr we should handle all String saving in this db record to json only. If API contracts are asking string, then only convert to string.

Plus as all executionInput apis are hidden, we can work with UI to convert and take inputs as json and not yaml. Lets check with them tomorrow if they can move it.



_Code quote:_
```Java
      executionInputService.save(ExecutionInputInstance.builder()
                                     .inputInstanceId(inputInstanceId)
                                     .nodeExecutionId(nodeExecutionId)
                                     .fieldYaml(YamlUtils.writeYamlString(fieldYaml))
                                     .template(node.getExecutionInputTemplate())
```

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 91 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOe7q7zP4aQS23aoK:-NWMOe7q7zP4aQS23aoL:bo2gtow) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L91)):*
> ```Java
>       return mapper.readTree(yaml);
>     } catch (IOException ex) {
>       throw new InvalidRequestException("Couldn't convert yaml to object");
> ```

nit: can you improve error message and add original exception as cause?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMNj1OAgXJsfYqyZgO:-NWMNj1P9M0BX35wCxrl:b281i4c) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L94)):*
> ```Java
> 
>   public JsonNode mergeExecutionInputIntoOriginalYamlJsonNode(
>       JsonNode originalYaml, JsonNode inputSetPipelineCompYaml, boolean appendInputSetValidator) {
> ```

can we rename originalJson and inputSetPipelineCompJson
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 188 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO-1B9Qp7o9FlCsbG:-NWMO-1B9Qp7o9FlCsbH:bnbuqze) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L188)):*
> ```Java
>     JsonNode modifiedOriginalMap =
>         addNonIgnorableBaseKeys(originalYamlJsonNode, mergedYamlFQNMap, nonIgnorableKeys, inputSetJsonNode);
>     return new YamlConfig(mergedYamlFQNMap, modifiedOriginalMap);
> ```

For ExecutionRuntime input, it should not return yamlConfig



_Code quote:_
```Java
new YamlConfig(mergedYamlFQNMap, modifiedOriginalMap);
```
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 87 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO4K88y0qciwSC3wQ:-NWMO4K88y0qciwSC3wR:b-z9nv7b) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L87)):*
> ```Java
>   }
> 
>   public JsonNode readAsJsonNode(String yaml) {
> ```

Add comment, stringified yaml is the input
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 91 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO7rVAlkI1SoEn86b:-NWMO7rVAlkI1SoEn86c:b2th5i) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L91)):*
> ```Java
>       return mapper.readTree(yaml);
>     } catch (IOException ex) {
>       throw new InvalidRequestException("Couldn't convert yaml to object");
> ```

add exception into logs as well
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOULF-DUCbPAY9Qjg:-NWMOULF-DUCbPAY9Qjh:bgzp4v3) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L137)):*
> ```Java
>                   .map(FQN::getExpressionFqn)
>                   .collect(Collectors.toList())
>                   .toString());
> ```

remove to String
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOYUi9EhTiuar6Ynj:-NWMOYUj6uGdeQdu7eS_:b-n4s4rd) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L141)):*
> ```Java
>       JsonNode userInputJsonNode = YamlUtils.readAsJsonNode(executionInputInstance.getUserInput());
>       JsonNode mergedJsonNode =
>           MergeHelper.mergeExecutionInputIntoOriginalYamlJsonNode(templateJsonNode, userInputJsonNode, false);
> ```

Yaml keyword from method can be removed
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOhdm4YVJvOQUhxt7:-NWMOhdm4YVJvOQUhxt8:b-c8pury) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L153)):*
> ```Java
>   // Using duplicate method of InputSetErrorHelper in pipeline-service. Will refactor the method and use the bring
>   // down to 870.
>   public Map<FQN, String> getInvalidFQNsInInputSet(JsonNode templateYaml, JsonNode inputSetPipelineCompYaml) {
> ```

its not yaml anymore
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOj0aDJfK1DKJvFWd:-NWMOj0b2WyEFcxm65Bk:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L153)):*
> ```Java
>   // Using duplicate method of InputSetErrorHelper in pipeline-service. Will refactor the method and use the bring
>   // down to 870.
>   public Map<FQN, String> getInvalidFQNsInInputSet(JsonNode templateYaml, JsonNode inputSetPipelineCompYaml) {
> ```

same as above
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOmLhD6oIRMoAFqCx:-NWMOmLhD6oIRMoAFqCy:bqgzlrj) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L157)):*
> ```Java
>     Map<FQN, Object> inputSetFqnToValueMap = FQNMapGenerator.generateFQNMap(inputSetPipelineCompYaml);
>     Set<FQN> inputSetFQNs = new LinkedHashSet<>(inputSetFqnToValueMap.keySet());
>     if (templateYaml == null || templateYaml.isNull()) {
> ```

Shouldnt we have any EmptyPredicate for this, if not create one
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOyzvEX0iZ4Gmi1XH:-NWMOyzvEX0iZ4Gmi1XI:bhn2onl) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L165)):*
> ```Java
>       if (inputSetFQNs.contains(key)) {
>         Object templateValue = templateFqnToValueMap.get(key);
>         Object value = templateFqnToValueMap.get(key);
> ```

it should be inputSetFqnToValueMap
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMP-RX2ImUldfQUVQ2:-NWMP-RX2ImUldfQUVQ3:bhn2onl) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L181)):*
> ```Java
>         inputSetFQNs.remove(key);
>       } else {
>         Map<FQN, Object> subMap = YamlSubMapExtractor.getFQNToObjectSubMap(templateFqnToValueMap, key);
> ```

it should be inputSetFqnToValueMap

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 4 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 94 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMNj1OAgXJsfYqyZgO:-NWMQaN96eshNCYE9hGX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename originalJson and inputSetPipelineCompJson
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 188 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO-1B9Qp7o9FlCsbG:-NWMSlJYAVbF9hK4Xsxx:b-n7r023) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L188)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

For ExecutionRuntime input, it should not return yamlConfig
</blockquote></details>

we still have some flows that use yaml string from yaml config returned from here. So, i think we should keep this return type as yaml config only for now. 
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 87 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO4K88y0qciwSC3wQ:-NWMRZ7BBAFDc5KJzyO6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L87)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add comment, stringified yaml is the input
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 91 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOe7q7zP4aQS23aoK:-NWMReHa7UzsCG7eewaX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L91)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

nit: can you improve error message and add original exception as cause?
</blockquote></details>

done
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 91 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO7rVAlkI1SoEn86b:-NWMRfAX2uDlDx8wZURc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add exception into logs as well
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 137 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOULF-DUCbPAY9Qjg:-NWMQhvL7Gt7NoVm-Haq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L137)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove to String
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOYUi9EhTiuar6Ynj:-NWMRC1g-im1nnZvIWOv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L141)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Yaml keyword from method can be removed
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOhdm4YVJvOQUhxt7:-NWMRHd34GBu4PI8pEMU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L153)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

its not yaml anymore
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOj0aDJfK1DKJvFWd:-NWMRIyfCmpHnZJHZauA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L153)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOmLhD6oIRMoAFqCx:-NWMS2X92_2lSey6RJQT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L157)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt we have any EmptyPredicate for this, if not create one
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMOyzvEX0iZ4Gmi1XH:-NWMRMkR1tD6wZNnWEpc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L165)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be inputSetFqnToValueMap
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 181 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMP-RX2ImUldfQUVQ2:-NWMRNPA69QavitrJqC-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L181)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be inputSetFqnToValueMap
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 6 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 188 at r4](https://reviewable.io/reviews/harness/harness-core/48319#-NWMO-1B9Qp7o9FlCsbG:-NWNBXYt7jKUActJLJua:b-rvwktk) ([raw file](https://github.com/harness/harness-core/blob/aac8989ca46db32fad68bf66ce27c01c977b720d/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L188)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

we still have some flows that use yaml string from yaml config returned from here. So, i think we should keep this return type as yaml config only for now. 
</blockquote></details>

changed return type to jsonNode for v2 method.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 128 at r8](https://reviewable.io/reviews/harness/harness-core/48319#-NWQTrEgC6NZghvPLh7G:-NWQTrEhE1dKIEzv3_Xw:bk5chpq) ([raw file](https://github.com/harness/harness-core/blob/061008c32a43b2541050e332667d069555dfbf9d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L128)):*
> ```Java
>       executionInputJsonNode = (JsonNode) pmsEngineExpressionService.resolve(
>           ambiance, executionInputJsonNode, ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED);
>       executionInputInstance.setUserInput(YamlUtils.write(executionInputJsonNode));
> ```

in this write method, replace ---- is not there is this expected?



_Code quote:_
```Java
YamlUtils.write(executionInputJsonNode)
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 135 at r8](https://reviewable.io/reviews/harness/harness-core/48319#-NWQU2SmBDqbKDfLjXLw:-NWQU2SmBDqbKDfLjXLx:b-wo97s7) ([raw file](https://github.com/harness/harness-core/blob/061008c32a43b2541050e332667d069555dfbf9d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L135)):*
> ```Java
>             + invalidFQNsInInputSet.keySet().stream().map(FQN::getExpressionFqn).collect(Collectors.toList()));
>       }
>       JsonNode userInputJsonNode = YamlUtils.readAsJsonNode(executionInputInstance.getUserInput());
> ```

Earlier we set in same flow, thus we need to read it again as json from yaml? cant we store above in a json field?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 128 at r8](https://reviewable.io/reviews/harness/harness-core/48319#-NWQTrEgC6NZghvPLh7G:-NWR-2OQ6ZDwmxwontKf:b-4u80yv) ([raw file](https://github.com/harness/harness-core/blob/061008c32a43b2541050e332667d069555dfbf9d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

in this write method, replace ---- is not there is this expected?
</blockquote></details>

updated to use YamlUtils.writeYamlString() instead, this has replace --- in it.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java` line 135 at r8](https://reviewable.io/reviews/harness/harness-core/48319#-NWQU2SmBDqbKDfLjXLw:-NWR-MSr7RxZ5iWtTvpM:b-i72rd7) ([raw file](https://github.com/harness/harness-core/blob/061008c32a43b2541050e332667d069555dfbf9d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/ExecutionInputServiceImpl.java#L135)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Earlier we set in same flow, thus we need to read it again as json from yaml? cant we store above in a json field?
</blockquote></details>

Yes, userInput in ExecutionInputInstance is yaml string, so we need to convert it to JsonNode.
as we decided not to change anything from yaml to jsonNode in ExecutionInputInstance.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/48319#-NWILJVT8icH_EAjqNcM:-NWR-F3V2vfpuWK3wsU2:b4kaghr) ([raw file](https://github.com/harness/harness-core/blob/7544a1d6858d91094446915d6a22217f547af994/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@shalini-agr we should handle all String saving in this db record to json only. If API contracts are asking string, then only convert to string.

Plus as all executionInput apis are hidden, we can work with UI to convert and take inputs as json and not yaml. Lets check with them tomorrow if they can move it.
</blockquote></details>

Discussed this offline.
For now, we will save yaml only in db, and to ui also, we will send yaml only.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger ut6

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ut4,ut5,ut6,ut7,ut8,ut9

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48319)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
