### PR TITLE
feat: [IDP-1073]: Data Population and creating dsl for harness

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52286)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 8 of 21 files at r1, 2 of 6 files at r4, 23 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52286)* status: 31 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java` line 36 at r5](https://reviewable.io/reviews/harness/harness-core/52286#-NdBAcrrBBD33fGZNMo0:-NdBAcrrBBD33fGZNMo1:bsvlkhu) ([raw file](https://github.com/harness/harness-core/blob/29c8508f54dc30a64749d0d453439cbc929619fc/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java#L36)):*
> ```Java
> @Slf4j
> public class HarnessProvider extends DataSourceProvider {
>   String BODY = "{BODY}";
> ```

Can we add private static final?
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java` line 108 at r5](https://reviewable.io/reviews/harness/harness-core/52286#-NdBArjY5gRPsldcPglQ:-NdBArjZB4LVEgyxQ0a4:bnc68sy) ([raw file](https://github.com/harness/harness-core/blob/29c8508f54dc30a64749d0d453439cbc929619fc/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/HarnessProvider.java#L108)):*
> ```Java
>         return possibleReplaceableUrlPairs;
>       case LOCAL_ENV:
>         possibleReplaceableUrlPairs.put(HOST, LOCAL_HOST);
> ```

Can we add break; in each case instead? and return possibleReplaceableUrlPairs at the end (as it is common to every case anyway)
___
*[`idp-service/src/main/resources/migrations/scorecard/checks.json` line 187 at r5](https://reviewable.io/reviews/harness/harness-core/52286#-NdBA8-J8nfr4GGI0tMw:-NdBA8-J8nfr4GGI0tMx:bjoga4c) ([raw file](https://github.com/harness/harness-core/blob/29c8508f54dc30a64749d0d453439cbc929619fc/idp-service/src/main/resources/migrations/scorecard/checks.json#L187)):*
> ```JSON
>     "accountIdentifier": "__GLOBAL_ACCOUNT_ID__",
>     "identifier": "__HARNESS__b5e32af1-1c66-4501-9bdf-571ba9cdee16",
>     "name": "No test failing on CI Pipeline is zero",
> ```

No test failing on the CI Pipeline



_Code quote:_
```JSON
No
```

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut7

**Review by mankrit-singh — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger ut7

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 20 of 20 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52286)* status: 32 file(s) to review.

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
