### PR TITLE
fix: [CDS-76025]: creating migration to add better index on instance_stats

### PR DESCRIPTION
**Pull request by lasdox**
…stats

## Describe your changes
Changing CD Usage queries to be async in multiple threads rather than sync.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51245)

### CODE REVIEW

**Comment by lasdox** [comment]
trigger uts

**Comment by lasdox** [comment]
trigger uts

**Comment by lasdox** [comment]
trigger commonchecks

**Comment by lasdox** [comment]
trigger uts_JDK11

**Comment by lasdox** [comment]
trigger uts_JDK11

**Comment by lasdox** [comment]
trigger uts

**Comment by lasdox** [comment]
trigger uts

**Comment by lasdox** [comment]
trigger uts

**Comment by lasdox** [comment]
trigger uts

**Comment by lasdox** [comment]
trigger uts_JDK11

**Review by ivan-83 — CHANGES_REQUESTED** [review]
LGTM with comments.

> Reviewed 7 of 11 files at r1, 1 of 1 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245#-:-NbGdgvE3EC9vY1319eA:b-6wbxll)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java` line 147 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGbQ9i1pG2rVqkhOEg:-NbGbQ9i1pG2rVqkhOEh:bifuyp5) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L147)):*
> ```Java
>           // Handle exceptions if needed
>           log.error("Failed to get CgCdLicenseUsage", e);
>           throw new WingsException("Failed to get CgCdLicenseUsage, please contact support");
> ```

Pls, add accountId in the error msgs. 
___
*[`400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGamfb1X06gzKlroPK:-NbGamfb1X06gzKlroPL:b-mbx0s4) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L151)):*
> ```Java
>       }
>     } finally {
>       executorService.shutdown();
> ```

Do we need a shutdown executor service after each execution? I think the ExecutorService should be managed by the framework and shut down when the NG manager service stops.  
___
*[`400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGbfaX7ggwWVnfm7zj:-NbGbfaX7ggwWVnfm7zk:bmewog6) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java#L71)):*
> ```Java
>     bind(ExecutorService.class)
>         .annotatedWith(Names.named("cgCdLicenseUsageExecutor"))
>         .toInstance(ThreadPool.create(5, 20, 1L, TimeUnit.SECONDS,
> ```

5 means that we will have 5 parallel probably time consuming queries running at the same time on Timescale DB. Based on the logs the most consuming lasts around 70 seconds, but it's improved by creating the new indexes. 
___
*[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 262 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGcFu98P44Ruiytxdj:-NbGcFuA3WwLStVMqpVm:b2qcgsy) ([raw file](https://github.com/harness/harness-core/blob/3aa361daca73088b92c496a044f4dcd352781e43/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L262)):*
> ```Java
>                  .descSortField(WorkflowExecutionKeys.createdAt)
>                  .build())
>         .add(SortCompoundMongoIndex.builder()
> ```

Why are we removing workflow execution indexes?
___
*[`400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java` line 1864 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGcj8n0ERN1RduOEoH:-NbGcj8n0ERN1RduOEoI:bi3mt2y) ([raw file](https://github.com/harness/harness-core/blob/3aa361daca73088b92c496a044f4dcd352781e43/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L1864)):*
> ```Java
>   private StateExecutionInstance clone(StateExecutionInstance stateExecutionInstance, State nextState) {
>     StateExecutionInstance cloned = kryoSerializer.clone(stateExecutionInstance);
>     if (featureFlagService.isEnabled(SPG_FIX_APPROVAL_WAITING_FOR_INPUTS, stateExecutionInstance.getAccountId())) {
> ```

I guess this is part of another ticket or?
___
*[`400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql` line 7 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGc_xX6vf_VuDTtaN2:-NbGc_xX6vf_VuDTtaN3:b-4tx9gx) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql#L7)):*
> ```TSQL
> 
> BEGIN;
> CREATE INDEX IF NOT EXISTS INSTANCE_STATS_ACCTID_SRVID_REPORTEDAT_APPID_INSTCOUNT_INDEX ON INSTANCE_STATS(ACCOUNTID, SERVICEID, REPORTEDAT DESC, APPID, INSTANCECOUNT);
> ```

Why REPORTEDAT DESC? 
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 478 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGcyf96jlBfvclhKSH:-NbGcyf96jlBfvclhKSI:b-zecw9e) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L478)):*
> ```Java
>   MOVE_AWS_CODE_DEPLOY_INSTANCE_SYNC_TO_PERPETUAL_TASK,
>   MOVE_AWS_LAMBDA_INSTANCE_SYNC_TO_PERPETUAL_TASK,
>   CD_MAKE_CD_LICENSE_USAGE_ASYNC("Make CD License Usage dashboards to be async", HarnessTeam.CDC),
> ```

Minor - Make CD License Usage reports async 

Because it's used on the Account Overview page and for telemetry reports.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGbfaX7ggwWVnfm7zj:-NbGkFUjCiR5l38_YOIA:b-36m4gk) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java#L71)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

5 means that we will have 5 parallel probably time consuming queries running at the same time on Timescale DB. Based on the logs the most consuming lasts around 70 seconds, but it's improved by creating the new indexes. 
</blockquote></details>

Can we decrease the number of threads to 3? 
___
*[`400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql` line 7 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGc_xX6vf_VuDTtaN2:-NbGk1PO0u7QEbPvb37c:b-t8shtk) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql#L7)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Why REPORTEDAT DESC? 
</blockquote></details>

This index can't be deployed on PROD because we are having around 1.8 billion rows.

**Review by harness-david — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql` line 7 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGc_xX6vf_VuDTtaN2:-NbGjxWpDkukjkkeCARo:b4nza9k) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql#L7)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This index can't be deployed on PROD because we are having around 1.8 billion rows.
</blockquote></details>

All other indexes on that table that use REPORTEDAT are DESC.  It is generally better to go with the precedence set when the datetime is a later column in the index.  If it was the first column, it should be ASC.  Before I got to Harness people already created many DESC indexes.

**Review by harness-david — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql` line 7 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGc_xX6vf_VuDTtaN2:-NbGkyjO2g2X2F1ip_rh:bkkees1) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql#L7)):*
<details><summary><i>Previously, harness-david (David McNamara) wrote…</i></summary><blockquote>

All other indexes on that table that use REPORTEDAT are DESC.  It is generally better to go with the precedence set when the datetime is a later column in the index.  If it was the first column, it should be ASC.  Before I got to Harness people already created many DESC indexes.
</blockquote></details>

@lasdox PROD has already been indexed in a special way to avoid indexing a billion+ rows for nothing.  Timescale does not respect the ONLY keyword in the CREATE INDEX statement so there's no way I can add this as a dummy index to the Timescale hypertable instance_stats

**Comment by lasdox** [comment]
> LGTM with comments.
> 
> > Reviewed 7 of 11 files at r1, 1 of 1 files at r3, 1 of 3 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245#-:-NbGdgvE3EC9vY1319eA:b-6wbxll)_ status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java` line 147 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGbQ9i1pG2rVqkhOEg:-NbGbQ9i1pG2rVqkhOEh:bifuyp5) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L147)):_
> 
> > ```java
> >           // Handle exceptions if needed
> >           log.error("Failed to get CgCdLicenseUsage", e);
> >           throw new WingsException("Failed to get CgCdLicenseUsage, please contact support");
> > ```
> 
> Pls, add accountId in the error msgs.

Done.

> 
> _[`400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGamfb1X06gzKlroPK:-NbGamfb1X06gzKlroPL:b-mbx0s4) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/io/harness/cdlicense/impl/CgCdLicenseUsageServiceImpl.java#L151)):_
> 
> > ```java
> >       }
> >     } finally {
> >       executorService.shutdown();
> > ```
> 
> Do we need a shutdown executor service after each execution? I think the ExecutorService should be managed by the framework and shut down when the NG manager service stops.

Removed this

> 
> _[`400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGbfaX7ggwWVnfm7zj:-NbGbfaX7ggwWVnfm7zk:bmewog6) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java#L71)):_
> 
> > ```java
> >     bind(ExecutorService.class)
> >         .annotatedWith(Names.named("cgCdLicenseUsageExecutor"))
> >         .toInstance(ThreadPool.create(5, 20, 1L, TimeUnit.SECONDS,
> > ```
> 
> 5 means that we will have 5 parallel probably time consuming queries running at the same time on Timescale DB. Based on the logs the most consuming lasts around 70 seconds, but it's improved by creating the new indexes.
> 

Yeah, but this should pool the tsdb connection pool, so this will only use limited resources.

> _[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 262 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGcFu98P44Ruiytxdj:-NbGcFuA3WwLStVMqpVm:b2qcgsy) ([raw file](https://github.com/harness/harness-core/blob/3aa361daca73088b92c496a044f4dcd352781e43/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L262)):_
> 
> > ```java
> >                  .descSortField(WorkflowExecutionKeys.createdAt)
> >                  .build())
> >         .add(SortCompoundMongoIndex.builder()
> > ```
> 
> Why are we removing workflow execution indexes?

Want to remove some useless code in this pr too
> 
> _[`400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java` line 1864 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGcj8n0ERN1RduOEoH:-NbGcj8n0ERN1RduOEoI:bi3mt2y) ([raw file](https://github.com/harness/harness-core/blob/3aa361daca73088b92c496a044f4dcd352781e43/400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java#L1864)):_
> 
> > ```java
> >   private StateExecutionInstance clone(StateExecutionInstance stateExecutionInstance, State nextState) {
> >     StateExecutionInstance cloned = kryoSerializer.clone(stateExecutionInstance);
> >     if (featureFlagService.isEnabled(SPG_FIX_APPROVAL_WAITING_FOR_INPUTS, stateExecutionInstance.getAccountId())) {
> > ```
> 
> I guess this is part of another ticket or?
> 

Just removing useless code!

> _[`400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql` line 7 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGc_xX6vf_VuDTtaN2:-NbGc_xX6vf_VuDTtaN3:b-4tx9gx) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/resources/timescaledb/create_instance_stats_index_overview_page.sql#L7)):_
> 
> > ```tsql
> > BEGIN;
> > CREATE INDEX IF NOT EXISTS INSTANCE_STATS_ACCTID_SRVID_REPORTEDAT_APPID_INSTCOUNT_INDEX ON INSTANCE_STATS(ACCOUNTID, SERVICEID, REPORTEDAT DESC, APPID, INSTANCECOUNT);
> > ```
> 
> Why REPORTEDAT DESC?
> 

Suggested by David

> _[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 478 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGcyf96jlBfvclhKSH:-NbGcyf96jlBfvclhKSI:b-zecw9e) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L478)):_
> 
> > ```java
> >   MOVE_AWS_CODE_DEPLOY_INSTANCE_SYNC_TO_PERPETUAL_TASK,
> >   MOVE_AWS_LAMBDA_INSTANCE_SYNC_TO_PERPETUAL_TASK,
> >   CD_MAKE_CD_LICENSE_USAGE_ASYNC("Make CD License Usage dashboards to be async", HarnessTeam.CDC),
> > ```
> 
> Minor - Make CD License Usage reports async
> 
> Because it's used on the Account Overview page and for telemetry reports.

Done

**Comment by lasdox** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245)_ status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java` line 71 at r4](https://reviewable.io/reviews/harness/harness-core/51245#-NbGbfaX7ggwWVnfm7zj:-NbGkFUjCiR5l38_YOIA:b-36m4gk) ([raw file](https://github.com/harness/harness-core/blob/6745e7deed013708ef683a372af956c8e2271b91/400-rest/src/main/java/software/wings/app/ManagerExecutorModule.java#L71)):_
> 
> Previously, ivan-83 (Ivan Mijailovic) wrote…
> > 5 means that we will have 5 parallel probably time consuming queries running at the same time on Timescale DB. Based on the logs the most consuming lasts around 70 seconds, but it's improved by creating the new indexes.
> 
> Can we decrease the number of threads to 3?

It will be only 3 threads for all customers, I dont like this. Can we start with 5 and decrease if resources are being wasted?


@ivan-83

**Comment by lasdox** [comment]
trigger uts_JDK11

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 1 of 3 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245#-:-NbJPGkz4tcT1pqjbt35:bnfp4nl)* status: 12 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 2 of 3 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51245)* status: 2. unresolved discussions.

**Comment by lasdox** [comment]
trigger review

**Comment by lasdox** [comment]
trigger messageCheck

**Comment by lasdox** [comment]
trigger messageCheck

**Comment by lasdox** [comment]
trigger messagecheck

**Pull request merged**
