### PR TITLE
feat:[PL-32649]: In ACS, Acl processing for Resource group via Outbox framework.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
In ACS, ACL processing for Resource group via Outbox framework.
Currently we are doing ACL processing via [Debezium](https://debezium.io/documentation/reference/1.9/connectors/mongodb.html) .
The change is behind config flag enableAclProcessingThroughOutbox.

Tests:
Resource Group update:
ACL creation only for resources added.
ACL creation only for resources deleted.
Implicit ACL generation.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-3rdQ9xmMhS9giREH:-Ni-3rdQ9xmMhS9giREI:bcpldbx) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L177)):*
> ```Java
>   public long createImplicitACLsForRoleAssignment(RoleAssignmentDBO roleAssignment) {
>     List<ACL> acls = getImplicitACLsForRoleAssignment(roleAssignment);
>     return aclRepository.insertAllIgnoringDuplicates(acls);
> ```

@Jimit09Gandhi Should we reduce the batch size to 5000 during batch insertion as I see we are still relying on this method
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumer.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-47Og-ph7Ioq8qRWm:-Ni-47Og-ph7Ioq8qRWn:b-pztnoz) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumer.java#L49)):*
> ```Java
> 
>   @Inject
>   public ResourceGroupChangeConsumer(@Named(ACL.PRIMARY_COLLECTION) ACLRepository aclRepository,
> ```

What are the changes in this file?
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-4Vcm4ne1zKhY01M_:-Ni-4Vcm4ne1zKhY01Ma:b8by07) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java#L71)):*
> ```Java
> 
>     List<RoleChangeConsumer.ReProcessRoleAssignmentOnRoleUpdateTask> tasksToExecute =
>         roleAssignmentRepository.findAll(criteria, Pageable.ofSize(50000))
> ```

Any reason for this change?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)* status: 18 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-4Vcm4ne1zKhY01M_:-Ni-7_qy3aqkGzv5KSUA:bveujw7) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java#L71)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason for this change?
</blockquote></details>

For managed role/resource groups, it will lead to update of Role assignments across cluster. So increased the role assignments fetch from 10k to 50k.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumer.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-47Og-ph7Ioq8qRWm:-Ni-Ymzu7FthBMrpdq0i:b38ferc) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ResourceGroupChangeConsumer.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What are the changes in this file?
</blockquote></details>

resourceSelectors calcuated both from V1 and V2. I have moved that logic to ResourceGroup class. And have cleaned up the logic.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-4Vcm4ne1zKhY01M_:-Ni-Z5XcAuWTLrbZ7KLb:b-kscrsn) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java#L71)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

For managed role/resource groups, it will lead to update of Role assignments across cluster. So increased the role assignments fetch from 10k to 50k.
</blockquote></details>

As discussed changing to 100k for now. We will refactor this later.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java` line 177 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-3rdQ9xmMhS9giREH:-Ni-ZD879AYHcRpL0sC_:b-vr33j1) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ACLGeneratorServiceImpl.java#L177)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@Jimit09Gandhi Should we reduce the batch size to 5000 during batch insertion as I see we are still relying on this method
</blockquote></details>

Will raise subsequent PR for this change.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54686#-Ni-4Vcm4ne1zKhY01M_:-Ni-fZRlAQpoN1rWRTcy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/85c84ec2ebd1b38f8753f9fc6b4f40274d62962a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleChangeConsumer.java#L71)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

As discussed changing to 100k for now. We will refactor this later.
</blockquote></details>

done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54686#-:-Ni-gJ8DAVml_uxxFHQ-:bnfp4nl)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Pull request merged**
