### PR TITLE
feat: [IDP-1165]: Mark conditional input as required based on flag

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52784)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52784)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/CheckServiceImpl.java` line 191 at r1](https://reviewable.io/reviews/harness/harness-core/52784#-Ne8ybj4-4QDZskgjQKq:-Ne8ybj54IfLV3oC0ajQ:b-xld4vs) ([raw file](https://github.com/harness/harness-core/blob/7992940715f658ccdf39b4d13646a59a0d32e982/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/CheckServiceImpl.java#L191)):*
> ```Java
>     Map<String, DataPoint> dataPointMap = dataPointService.getDataPointsMap(accountIdentifier);
>     for (Rule rule : checkDetails.getRules()) {
>       String key = rule.getDataSourceIdentifier() + DOT_SEPARATOR + rule.getDataPointIdentifier();
> ```

In the dropdown, we only list the data points for a selected data source. Is there a scenario where it won't be the case and we would need this validation? :thinking:

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52784)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/CheckServiceImpl.java` line 191 at r1](https://reviewable.io/reviews/harness/harness-core/52784#-Ne8ybj4-4QDZskgjQKq:-Ne930DP7XTHsVzGyJsd:b-hk0pai) ([raw file](https://github.com/harness/harness-core/blob/7992940715f658ccdf39b4d13646a59a0d32e982/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/CheckServiceImpl.java#L191)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

In the dropdown, we only list the data points for a selected data source. Is there a scenario where it won't be the case and we would need this validation? :thinking:
</blockquote></details>

yes, mostly we wont be facing this issue. I have just added this extra guard rail in backend if something goes wrong in the UI while saving

**Comment by vigneswara-propelo** [comment]
trigger messagecheck

**Comment by vigneswara-propelo** [comment]
trigger messagecheck

**Comment by vigneswara-propelo** [comment]
trigger messagecheck

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52784)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger ut4

**Review by devesh-harness — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
