### PR TITLE
feat:[CDS-51867]: changes for supporting scoped env in multi-env scenarios in Gitops

### PR DESCRIPTION
**Pull request by vaibhav-si**
## Describe your changes

Verified by running execution locally with Account level env, with env variables, with service overrides.

Screenshot 2023-02-23 at 7 26 16 PM

Also ran a sanity Execution locally for Project level env.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)

### CODE REVIEW

**Review by meenaravichandran1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 483 at r1](https://reviewable.io/reviews/harness/harness-core/44294#-NP0UsKN1WAXgrWEIRRa:-NP0UsKN1WAXgrWEIRRb:b-w5qhk2) ([raw file](https://github.com/harness/harness-core/blob/35c9c081c93a951404c6ec4c044b464670e7f8bc/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L483)):*
> ```Java
>                                  .in(orgLevelIdentifiers);
>       entities.addAll(environmentRepository.fetchesNonDeletedEnvironmentFromListOfIdentifiers(orgCriteria));
>     }
> ```

Nit Can we abstract this logic into a separate method since this is repeated for account, org and project levels



_Suggestion:_
```Java
    if (isNotEmpty(orgLevelIdentifiers)) {
      Criteria orgCriteria = Criteria.where(ServiceEntity.ServiceEntityKeys.accountId)
                                 .is(accountId)
                                 .and(ServiceEntity.ServiceEntityKeys.orgIdentifier)
                                 .is(orgIdentifier)
                                 .and(ServiceEntity.ServiceEntityKeys.projectIdentifier)
                                 .is(null)
                                 .and(ServiceEntity.ServiceEntityKeys.identifier)
                                 .in(orgLevelIdentifiers);
    }
```

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 449 at r1](https://reviewable.io/reviews/harness/harness-core/44294#-NP1srjF1KbrYzv1QogM:-NP1srjF1KbrYzv1QogN:bum0lm6) ([raw file](https://github.com/harness/harness-core/blob/35c9c081c93a951404c6ec4c044b464670e7f8bc/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L449)):*
> ```Java
>       if (isNotEmpty(envRef)) {
>         IdentifierRef identifierRef =
>             IdentifierRefHelper.getIdentifierRef(envRef, accountId, orgIdentifier, projectIdentifier);
> ```

using this implies we're using refs always, because if we supply identifiers (of org/acc level envs) then this will throw error
in that case can we change the method name? 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 462 at r1](https://reviewable.io/reviews/harness/harness-core/44294#-NP1tGjr2jSMQBsGTESo:-NP1tGjr2jSMQBsGTESp:b-xcvggu) ([raw file](https://github.com/harness/harness-core/blob/35c9c081c93a951404c6ec4c044b464670e7f8bc/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L462)):*
> ```Java
> 
>     if (isNotEmpty(projectLevelIdentifiers)) {
>       Criteria projectCriteria = Criteria.where(ServiceEntity.ServiceEntityKeys.accountId)
> ```

EnvironmentKeys

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 449 at r1](https://reviewable.io/reviews/harness/harness-core/44294#-NP1srjF1KbrYzv1QogM:-NP2701C2RBMvm6kjWTG:b-91kx15) ([raw file](https://github.com/harness/harness-core/blob/35c9c081c93a951404c6ec4c044b464670e7f8bc/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L449)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

using this implies we're using refs always, because if we supply identifiers (of org/acc level envs) then this will throw error
in that case can we change the method name? 
</blockquote></details>

To avoid any side-effect, added new method which works only for refs.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 462 at r1](https://reviewable.io/reviews/harness/harness-core/44294#-NP1tGjr2jSMQBsGTESo:-NP274Bf1Q5hr0_Ho41M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/35c9c081c93a951404c6ec4c044b464670e7f8bc/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L462)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

EnvironmentKeys
</blockquote></details>

Done.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44294)* status: :shipit: complete! ✓

**Pull request merged**
