### PR TITLE
feat: [IDP-65]: Config stitching(Base config+Runtime Config)

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: 13 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/beans/entity/MergedAppConfigEntity.java` line 12 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhbYwH72i3eUnBEmzp:-NQhbYwH72i3eUnBEmzq:blqdork) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/beans/entity/MergedAppConfigEntity.java#L12)):*
> ```Java
> import io.harness.annotations.dev.HarnessTeam;
> import io.harness.annotations.dev.OwnedBy;
> import io.harness.mongo.index.CompoundMongoIndex;
> ```

nit: There are some unused imports.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/mappers/MergedAppConfigMapper.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhbu4FAmyOXfJZnCwH:-NQhbu4FAmyOXfJZnCwI:b-ealss9) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/mappers/MergedAppConfigMapper.java#L14)):*
> ```Java
> 
> @UtilityClass
> public class MergedAppConfigMapper {
> ```

nit: @OwnedBy(HarnessTeam.IDP)
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustom.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhc4y_EeZ8DTzgMjpG:-NQhc4y_EeZ8DTzgMjpH:b-ealss9) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustom.java#L11)):*
> ```Java
> import io.harness.idp.configmanager.beans.entity.MergedAppConfigEntity;
> 
> public interface MergedAppConfigRepositoryCustom {
> ```

nit: @OwnedBy(HarnessTeam.IDP)
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhdCqN7xIJ68WbeZfL:-NQhdCqN7xIJ68WbeZfM:b-jvh468) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java#L30)):*
> ```Java
>       return mongoTemplate.save(mergedAppConfigEntity);
>     }
>     Criteria criteria = Criteria.where(MergedAppConfigEntity.MergedAppConfigEntityKeys.accountIdentifier)
> ```

Since the same criteria is used for find and update, can we just pass criteria to findByAccountId?
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhdLHJ9KfC9y1O7ocf:-NQhdLHJ9KfC9y1O7ocg:b-u7hn6x) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java#L37)):*
> ```Java
>     update.set(MergedAppConfigEntity.MergedAppConfigEntityKeys.lastModifiedAt, System.currentTimeMillis());
>     FindAndModifyOptions options = new FindAndModifyOptions().returnNew(true);
>     return mongoTemplate.findAndModify(query, update, options, MergedAppConfigEntity.class);
> ```

Can we explore https://www.mongodb.com/docs/manual/reference/method/db.collection.update/#std-label-update-upsert ?
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerService.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhdrk10y61x83JXhdI:-NQhdrk10y61x83JXhdJ:b-5opsf7) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerService.java#L28)):*
> ```Java
>   public Map getPluginEnablementForAccount(String accountIdentifier);
> 
>   public MergedAppConfigEntity mergeAndSaveAppConfig(String accountIdentifier) throws Exception;
> ```

nit: All methods in an interface are public by default



_Code quote:_
```Java
public
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQheVX_9LjjQejYATzf:-NQheVX_9LjjQejYATzg:b-l8wjn9) ([raw file](https://github.com/harness/harness-core/blob/50df57df2daa285ecfce78bd9c9f7f1933ed70b0/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L36)):*
> ```Java
>         appConfigRepository.findByAccountIdentifierAndPluginId(accountIdentifier, pluginId);
>     if (pluginConfig.isEmpty()) {
>       throw new InvalidRequestException(format(PLUGIN_CONFIG_NOT_FOUND, pluginId, accountIdentifier));
> ```

Reason for this change? :thinking: 
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQheyxw8EDWitSzzw2S:-NQheyxw8EDWitSzzw2T:b8c2jax) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L81)):*
> ```Java
> 
>   @Override
>   public Map getPluginEnablementForAccount(String accountIdentifier) {
> ```

Can we add the parameters for the Map?
Also should we name this method as `getAllPlugins()`?



_Code quote:_
```Java
Map
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhfV-v7QsEVeRgjae7:-NQhfV-v7QsEVeRgjae8:b49y9s2) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L93)):*
> ```Java
>     MergedAppConfigEntity mergedAppConfigEntity =
>         MergedAppConfigMapper.getMergedAppConfigEntity(accountIdentifier, mergedAppConfig);
>     MergedAppConfigEntity insertedMergedAppConfig = mergedAppConfigRepository.saveOrUpdate(mergedAppConfigEntity);
> ```

nit: we could return from here itself. Same comment for other methods.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 100 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhg-ib8yPVdslE1bGX:-NQhg-ib8yPVdslE1bGY:bolhpq3) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L100)):*
> ```Java
>     String baseAppConfig = ConfigManagerUtils.readFile(BASE_APP_CONFIG_PATH);
>     JsonNode baseConfig = ConfigManagerUtils.asJsonNode(baseAppConfig);
>     Iterator itr = configs.iterator();
> ```

nit: `Iterator<String>`



_Code quote:_
```Java
Iterator
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhgLeC7cVugW8nhVmq:-NQhgLeC7cVugW8nhVmr:bmdbwol) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L104)):*
> ```Java
>       String config = itr.next().toString();
>       JsonNode pluginConfig = ConfigManagerUtils.asJsonNode(config);
>       baseConfig = JsonNodeUtils.merge(baseConfig, pluginConfig);
> ```

Looks like baseConfig will already have the merged value. We don't have to explitly assign back.



_Code quote:_
```Java
baseConfig
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhgxyV-FcYL1_FaFCS:-NQhgxyV-FcYL1_FaFCT:b-px28bz) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L29)):*
> ```Java
>       return Resources.toString(Objects.requireNonNull(classLoader.getResource(filename)), StandardCharsets.UTF_8);
>     } catch (IOException e) {
>       throw new InvalidRequestException("Could not read resource file: " + filename);
> ```

Let's log or rethrow the error object. Once our product is stable, we can optmize the logging cost.
Either `log.error(e);` or `throw new InvalidRequestException("Could not read resource file: " + filename, e);`

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: 13 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhva3a5Csq7PYMOOqR:-NQhva3a5Csq7PYMOOqS:b-i9m06y) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L42)):*
> ```Java
> 
>   @Override
>   public AppConfig getPluginConfig(String accountIdentifier, String pluginId) {
> ```

lets plan to remove GET /v1/app-config if UI wont be using this.
Also, can we re-think on API naming and AppConfig entity something related to Plugin
we can plan this in next PR also

**Review by devesh-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256#-:-NQiI0Xg55Zc2US26o2g:bnfp4nl)* status: 13 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhdCqN7xIJ68WbeZfL:-NQhtU9d3iscwongRDZt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java#L30)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Since the same criteria is used for find and update, can we just pass criteria to findByAccountId?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhdLHJ9KfC9y1O7ocf:-NQi5Q0PBfux1GXrH_Z1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/repositories/MergedAppConfigRepositoryCustomImpl.java#L37)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we explore https://www.mongodb.com/docs/manual/reference/method/db.collection.update/#std-label-update-upsert ?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQheVX_9LjjQejYATzf:-NQi5iWRDp4rmgOipEra:bj07bjl) ([raw file](https://github.com/harness/harness-core/blob/50df57df2daa285ecfce78bd9c9f7f1933ed70b0/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L36)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Reason for this change? :thinking: 
</blockquote></details>

yes Vignesh need this change for checking whether we have to give static config or dynamic config supplied by the user.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhva3a5Csq7PYMOOqR:-NQi5bDr1kFMRBpCDtVk:b-g41dgr) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L42)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

lets plan to remove GET /v1/app-config if UI wont be using this.
Also, can we re-think on API naming and AppConfig entity something related to Plugin
we can plan this in next PR also
</blockquote></details>

yes will plan to remove it later when things will get finalised for now we can use it on service layer.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 81 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQheyxw8EDWitSzzw2S:-NQiGZKvEqtMDx-6gro9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L81)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we add the parameters for the Map?
Also should we name this method as `getAllPlugins()`?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhgLeC7cVugW8nhVmq:-NQi7Kkt3JHQYF9cSZUU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L104)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Looks like baseConfig will already have the merged value. We don't have to explitly assign back.
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhgxyV-FcYL1_FaFCS:-NQi7zGLAf-6CRtWIayN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L29)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Let's log or rethrow the error object. Once our product is stable, we can optmize the logging cost.
Either `log.error(e);` or `throw new InvalidRequestException("Could not read resource file: " + filename, e);`
</blockquote></details>

Done.

**Comment by devesh-harness** [comment]
trigger utAll

**Comment by devesh-harness** [comment]
trigger smartchecks

**Comment by devesh-harness** [comment]
trigger gitleaks

**Comment by devesh-harness** [comment]
trigger ss

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 7 of 10 files at r4, 3 of 7 files at r5, 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: 17 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 468 at r9](https://reviewable.io/reviews/harness/harness-core/45256#-NQxl-Vg6TlEtEWq9nxI:-NQxl-Vg6TlEtEWq9nxJ:b-qu8hu2) ([raw file](https://github.com/harness/harness-core/blob/75154efce4949780cedbbf7d12967546f8b9abef/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L468)):*
> ```YAML
>         - AppConfig
>     parameters:
>       - name: pluginId
> ```

Looks like we need to use kebab-case as per the standards
https://github.com/harness/harness-core/blob/develop/docs/api-standards/paths-and-actions.md#:~:text=Use-,kebab%2Dcase,-in%20resource%20collection



_Code quote:_
```YAML
pluginId
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/AppConfigRepository.java` line 22 at r9](https://reviewable.io/reviews/harness/harness-core/45256#-NQxlAYUECY2RNV4l1Zf:-NQxlAYUECY2RNV4l1Zg:bbdode0) ([raw file](https://github.com/harness/harness-core/blob/75154efce4949780cedbbf7d12967546f8b9abef/idp-service/src/main/java/io/harness/idp/configmanager/repositories/AppConfigRepository.java#L22)):*
> ```Java
> public interface AppConfigRepository extends CrudRepository<AppConfigEntity, String>, AppConfigRepositoryCustom {
>   List<AppConfigEntity> findAllByAccountIdentifier(String accountIdentifier);
>   Optional<AppConfigEntity> findByAccountIdentifierAndPluginId(String accountIdentifier, String pluginName);
> ```

nit: pluginId



_Code quote:_
```Java
pluginName
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhgxyV-FcYL1_FaFCS:-NQxlwnw76o2PvaVitVI:b-ck9p54) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L29)):*
<details><summary><i>Previously, devesh-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I doubt if e.getMessage() will have the stacktrace

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: 17 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 468 at r9](https://reviewable.io/reviews/harness/harness-core/45256#-NQxl-Vg6TlEtEWq9nxI:-NQxngKE8-eVXMjrcRsL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/75154efce4949780cedbbf7d12967546f8b9abef/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L468)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Looks like we need to use kebab-case as per the standards
https://github.com/harness/harness-core/blob/develop/docs/api-standards/paths-and-actions.md#:~:text=Use-,kebab%2Dcase,-in%20resource%20collection
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/45256#-NQhgxyV-FcYL1_FaFCS:-NQxnYZ7DiI62_Yj37JU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3903e073139b3e6c1f3cdcd27a27b097fe6713b4/idp-service/src/main/java/io/harness/idp/configmanager/utils/ConfigManagerUtils.java#L29)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

I doubt if e.getMessage() will have the stacktrace
</blockquote></details>

Done.

**Review by vikyathharekal — DISMISSED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: 17 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by devesh-harness** [comment]
trigger ut1

**Review by vigneswara-propelo — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 1 of 1 files at r3, 6 of 10 files at r4, 1 of 7 files at r5, 1 of 1 files at r9, 4 of 4 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45256)* status: :shipit: complete! ✓

**Comment by devesh-harness** [comment]
trigger ut2

**Pull request merged**
