### PR TITLE
[feat]: [CDS-49543]: API For Environment Tabular View

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
created API '/getActiveInstanceGroupedByEnvironment' for getting active instance count for a service, grouped on environment, infrastructure and artifact.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)

### CODE REVIEW

**Comment by Abhishek-CDC** [comment]
trigger messagecheck

**Review by meenaravichandran1 — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 13 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByEnvironmentList.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyKSpy3WBce70BZPE6:-NLyKSpy3WBce70BZPE7:bip9cen) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByEnvironmentList.java#L26)):*
> ```Java
>     String envId;
>     String envName;
>     List<InstanceGroupedByEnvironmentType> instanceGroupedByEnvironmentTypeList;
> ```

Can an env have multiple types?

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByEnvironmentList.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyKSpy3WBce70BZPE6:-NLyMBv_CEKY-6djUtHd:b-j4t6r6) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByEnvironmentList.java#L26)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Can an env have multiple types?
</blockquote></details>

Yes, if we deploy instances using an environment and then change its type and deploy more instances. then we can have instances from both types.

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByEnvironmentList.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyKSpy3WBce70BZPE6:-NLyMTucCg6SejjWSYX7:b-tdqea1) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByEnvironmentList.java#L26)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Yes, if we deploy instances using an environment and then change its type and deploy more instances. then we can have instances from both types.
</blockquote></details>

So, an environment may not have multiple types but possible to have instances deployed of both type.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 13 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 2298 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyMXkK8NHfMh0yJaAS:-NLyMXkL5PHSYgzX1lk5:b7bvh3z) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L2298)):*
> ```Java
>     // sort based on last deployed time
> 
>     Collections.sort(activeServiceInstanceInfoList, new Comparator<ActiveServiceInstanceInfoWithEnvType>() {
> ```

fyi, Comparator.comparingInt can be used which has some of the boilerplate code
___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyNBxw2B_NAV7LLzYU:-NLyNBxx05RHpzLQC9r0:b-2h0jw5) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java#L29)):*
> ```Java
>   public InstanceGroupedByEnvironmentList getInstanceGroupedByEnvironmentListHelper(
>       List<ActiveServiceInstanceInfoWithEnvType> activeServiceInstanceInfoList, boolean isGitOps) {
>     Map<String, Map<EnvironmentType, Map<String, Map<String, Pair<Integer, Long>>>>> instanceCountMap = new HashMap<>();
> ```

nit, can these nested objects be replaced with the objects you've created? These look weird and difficult to understand. Chances of introducing errors is also high.

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyNBxw2B_NAV7LLzYU:-NLyU-1-ApVvEHr8XMTZ:bcd9u11) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java#L29)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, can these nested objects be replaced with the objects you've created? These look weird and difficult to understand. Chances of introducing errors is also high.
</blockquote></details>

Adding comment

**Review by meenaravichandran1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 17 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42634#-NLyNBxw2B_NAV7LLzYU:-NM0twUHCUHgPGUGnaHy:b32v57) ([raw file](https://github.com/harness/harness-core/blob/4e42a39aa58bef4c37649aa54ea57aecd5a6d91d/120-ng-manager/src/main/java/io/harness/ng/overview/service/DashboardServiceHelper.java#L29)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Adding comment
</blockquote></details>

+1

**Review by meenaravichandran1 — DISMISSED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 17 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 6 of 12 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Y0709 — APPROVED** [review]
> Reviewed 6 of 12 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 2. unresolved discussions.

**Review by Abhishek-CDC — COMMENTED** [review]
> Reviewed 6 of 12 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: 1. unresolved discussions.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 6 of 12 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42634)* status: :shipit: complete! ✓

**Pull request merged**
