### PR TITLE
feat: [CDS-73346]: Handle in ParameterFieldProcessor the case when expected fieldType is int or double but the resolved expression value is of type string

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Testing:** Tested locally by giving maxConcurrency as an expression of pipeline string variable with value as an integer. Automation is also already added for this.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49962)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49962)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldProcessor.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/49962#-NZA3OqB84xmlEcOd2x_:-NZA3OqC72lWlnY9K8OJ:bzf28y7) ([raw file](https://github.com/harness/harness-core/blob/c27ee1ea9f052b696448bd3761617cee99b51ea0/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldProcessor.java#L73)):*
> ```Java
>           } else if (fieldClass.equals(Double.class)) {
>             if (newValue.getClass().equals(String.class)) {
>               newValue = Double.valueOf((String) newValue);
> ```

Extract into a method plus lets do after engine expression resolve

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49962)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldProcessor.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/49962#-NZA3OqB84xmlEcOd2x_:-NZA3jZM5wIxOW_E0Rg_:bnwz5le) ([raw file](https://github.com/harness/harness-core/blob/c27ee1ea9f052b696448bd3761617cee99b51ea0/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldProcessor.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Extract into a method plus lets do after engine expression resolve
</blockquote></details>

use switch statements

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49962)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldProcessor.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/49962#-NZA3OqB84xmlEcOd2x_:-NZAIyUD55tXqLNbipJi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c27ee1ea9f052b696448bd3761617cee99b51ea0/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldProcessor.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use switch statements
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49962)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49962)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
