### PR TITLE
fix: [CDS-46062]: Migration to sync status for time scale executions that …

### PR DESCRIPTION
**Pull request by Y0709**
…are not in final status and could possibly in wrong status due to disconnection for cdc service

Context: There were a few executions in timescale db where the status was incorrect when compared with mongo and as the data that is displayed on dashboards on welcome page fetches data from timescale db it showing incorrect no of running or waiting for approval pipelines. This will require a bit of refactoring of cdc service as permanent solution but for temporary solution we have added a background migration which checks all timescale migrations that are not in final states and compare them to mongo and in case they are not same the update the timescale execution summary

No of records in running status in prod2 timescaledb = 3700
No of records in running status in prod1 timescaledb = 400

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/40890#-NIHs9Yu56oXNujYyel3:-NIHs9Yu56oXNujYyel4:b-zusai) ([raw file](https://github.com/harness/harness-core/blob/2885060e290ef7444fbffa55313a0793b09608ea/pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java#L89)):*
> ```Java
>         Criteria.where(PipelineExecutionSummaryEntity.PlanExecutionSummaryKeys.planExecutionId).is(planExecutionId);
>     PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity =
>         analyticsMongoTemplate.findOne(new Query(criteria), PipelineExecutionSummaryEntity.class);
> ```

Use projections to fetch only status and required fields

**Review by abhinavmittal-harness — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/40890#-NIIt2euDQLEsOP2OlYE:-NIIt2ev4xMc2rFzoqLK:b-7jqhf6) ([raw file](https://github.com/harness/harness-core/blob/790da65c65d1fc6bc643d60024edec79a43c3bd0/pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java#L106)):*
> ```Java
>         .include("endTs");
>     List<PipelineExecutionSummaryEntity> pipelineExecutionSummaryEntityList =
>         analyticsMongoTemplate.find(query, PipelineExecutionSummaryEntity.class);
> ```

PmsExecutionSummaryRepositoryCustomImpl create findAllFromAnalytics equivalent to findAll and pass max batch size of 1k in the above query and loop over it.



_Code quote:_
```Java
 analyticsMongoTemplate.find(query, PipelineExecutionSummaryEntity.class);
```

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/40890#-NIIt2euDQLEsOP2OlYE:-NINolEz-t_zls5vcRXQ:b-w94trt) ([raw file](https://github.com/harness/harness-core/blob/790da65c65d1fc6bc643d60024edec79a43c3bd0/pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java#L106)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

PmsExecutionSummaryRepositoryCustomImpl create findAllFromAnalytics equivalent to findAll and pass max batch size of 1k in the above query and loop over it.
</blockquote></details>

We have used batch size of 500 in timescale query to get 500 ids at a time. Do i need to pass batch size in mongo as well because in one query only 500 executions will be fetched from mongo

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/40890#-NIIt2euDQLEsOP2OlYE:-NISrEM7Cimr5Ah7cXVK:b-bkk7xw) ([raw file](https://github.com/harness/harness-core/blob/511879d5ec116274c0da929889e54cc9a1f4100c/pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java#L106)):*
<details><summary><i>Previously, Y0709 (Yuvraj Singhal) wrote…</i></summary><blockquote>

We have used batch size of 500 in timescale query to get 500 ids at a time. Do i need to pass batch size in mongo as well because in one query only 500 executions will be fetched from mongo
</blockquote></details>

Please use PlanExecutionSummaryRepository and using projections and not directly using mongo template,

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/40890#-NIWuCvE22oMYc2B8zIn:-NIWuCvE22oMYc2B8zIo:bec6mye) ([raw file](https://github.com/harness/harness-core/blob/a195352297739edd62fc95da3e26041857b5ba40/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java#L28)):*
> ```Java
>   UpdateResult deleteAllExecutionsWhenPipelineDeleted(Query query, Update update);
>   Page<PipelineExecutionSummaryEntity> findAll(Criteria criteria, Pageable pageable);
>   List<PipelineExecutionSummaryEntity> findAllWithRequiredProjection(Criteria criteria, Pageable pageable);
> ```

either rename this function to be more verbose as to what fields it is returning or accept the list of keys for projections as parameters.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 99 at r5](https://reviewable.io/reviews/harness/harness-core/40890#-NIWuh9f4XXA7wu2sOae:-NIWuh9f4XXA7wu2sOaf:b-3irq1t) ([raw file](https://github.com/harness/harness-core/blob/a195352297739edd62fc95da3e26041857b5ba40/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L99)):*
> ```Java
>       query.fields().include(PlanExecutionSummaryKeys.createdAt);
>       query.fields().include(PlanExecutionSummaryKeys.lastUpdatedAt);
>       query.fields().include(PlanExecutionSummaryKeys.status);
> ```

Create a constant which has this list and then use it over here by looping over that constant.



_Code quote:_
```Java
      query.fields().include(PlanExecutionSummaryKeys.uuid);
      query.fields().include(PlanExecutionSummaryKeys.runSequence);
      query.fields().include(PlanExecutionSummaryKeys.accountId);
      query.fields().include(PlanExecutionSummaryKeys.projectIdentifier);
      query.fields().include(PlanExecutionSummaryKeys.orgIdentifier);
      query.fields().include(PlanExecutionSummaryKeys.pipelineIdentifier);
      query.fields().include(PlanExecutionSummaryKeys.name);
      query.fields().include(PlanExecutionSummaryKeys.endTs);
      query.fields().include(PlanExecutionSummaryKeys.planExecutionId);
      query.fields().include(PlanExecutionSummaryKeys.createdAt);
      query.fields().include(PlanExecutionSummaryKeys.lastUpdatedAt);
      query.fields().include(PlanExecutionSummaryKeys.status);
```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 2 change requests. 0 of 2 approvals obtained.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/40890#-NIWuCvE22oMYc2B8zIn:-NIX-IxGBbgRVdhVrOa0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a195352297739edd62fc95da3e26041857b5ba40/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java#L28)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

either rename this function to be more verbose as to what fields it is returning or accept the list of keys for projections as parameters.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 99 at r5](https://reviewable.io/reviews/harness/harness-core/40890#-NIWuh9f4XXA7wu2sOae:-NIX-LFuEAbQ_rlpnV2I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a195352297739edd62fc95da3e26041857b5ba40/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L99)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Create a constant which has this list and then use it over here by looping over that constant.
</blockquote></details>

Done.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: :shipit: complete! ✓

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java` line 106 at r4](https://reviewable.io/reviews/harness/harness-core/40890#-NIIt2euDQLEsOP2OlYE:-NIXA4kY6_kqZAwVYOgY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/511879d5ec116274c0da929889e54cc9a1f4100c/pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java#L106)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please use PlanExecutionSummaryRepository and using projections and not directly using mongo template,
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40890)* status: :shipit: complete! ✓

**Pull request merged**
