### PR TITLE
feat: [CDS-71660]: Allow only git supported template types to move to…

### PR DESCRIPTION
**Pull request by rohitk-h**
… git

## Describe your changes
- We are preventing users from allowing to move certain Template types to move to git

## Test scenarions
- Error thrown when moving secret_manager template 
prevent move to git

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48955)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48955)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1452 at r1](https://reviewable.io/reviews/harness/harness-core/48955#-NXO5vnT9Nmqhn-6JREB:-NXO5vnT9Nmqhn-6JREC:b3ho988) ([raw file](https://github.com/harness/harness-core/blob/4b3c4359ad3df893eb451d9ed86c245bd3bda4ef/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1452)):*
> ```Java
> 
>     if (templateEntityOptional.isPresent()) {
>       if (!gitSupportedTemplateEntities().contains(templateEntityOptional.get().getTemplateEntityType().toString())) {
> ```

TemplateEntityType already contains which entities can be remote, we can check if getTemplate.getEntityType.isGit, if false throw exception

NGTemplateServiceImpl -> create method already has exception, reuse the same exception

**Review by utkarshchoubey-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48955)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1474 at r1](https://reviewable.io/reviews/harness/harness-core/48955#-NXOGdAhC3QLu3hOIUH5:-NXOGdAhC3QLu3hOIUH6:b-fx366b) ([raw file](https://github.com/harness/harness-core/blob/4b3c4359ad3df893eb451d9ed86c245bd3bda4ef/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1474)):*
> ```Java
>   protected HashSet<String> gitSupportedTemplateEntities() {
>     return Sets.newHashSet(TemplateEntityType.STEP_TEMPLATE.toString(), TemplateEntityType.STAGE_TEMPLATE.toString(),
>         TemplateEntityType.PIPELINE_TEMPLATE.toString(), TemplateEntityType.CUSTOM_DEPLOYMENT_TEMPLATE.toString(),
> ```

CUSTOM deployment template is not supported in GIT, we can utilise TemplateEntityType class it has field isGitEntity

**Comment by rohitk-h** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1452 at r1](https://reviewable.io/reviews/harness/harness-core/48955#-NXO5vnT9Nmqhn-6JREB:-NXOHJzEBNb6UgMYTDlT:b-cypxrc) ([raw file](https://github.com/harness/harness-core/blob/4b3c4359ad3df893eb451d9ed86c245bd3bda4ef/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1452)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

TemplateEntityType already contains which entities can be remote, we can check if getTemplate.getEntityType.isGit, if false throw exception

NGTemplateServiceImpl -> create method already has exception, reuse the same exception 
</blockquote></details>

updated.

**Comment by rohitk-h** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1474 at r1](https://reviewable.io/reviews/harness/harness-core/48955#-NXOGdAhC3QLu3hOIUH5:-NXOHOKo547viDM3ifGR:b-cypxrc) ([raw file](https://github.com/harness/harness-core/blob/4b3c4359ad3df893eb451d9ed86c245bd3bda4ef/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1474)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

CUSTOM deployment template is not supported in GIT, we can utilise TemplateEntityType class it has field isGitEntity
</blockquote></details>

updated.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48955)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48955)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger review

**Pull request merged**
