### PR TITLE
feat: [CDS-40391]: delete branch for gitlab

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36391)

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/36391#-N9bQrvK3GdlJGSymzGy:-N9bQrvK3GdlJGSymzGz:bkiawth) ([raw file](https://github.com/harness/harness-core/blob/0583107ef3df3d628f9793c4b228a8ded7d513b3/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L76)):*
> ```Java
>       String slug = gitApiTaskParams.getSlug();
>       String prNumber = gitApiTaskParams.getPrNumber();
>       Boolean deleteSourceBranch = gitApiTaskParams.getDeleteSourceBranch();
> ```

can this just be `boolean` instead? 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/gitapi/GitApiTaskParams.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/36391#-N9bR4t-4gJGC9hpkef9:-N9bR4t-4gJGC9hpkefA:bbxgkzp) ([raw file](https://github.com/harness/harness-core/blob/0583107ef3df3d628f9793c4b228a8ded7d513b3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/gitapi/GitApiTaskParams.java#L45)):*
> ```Java
>   @NotEmpty GitApiRequestType requestType;
>   String sha;
>   Boolean deleteSourceBranch;
> ```

Same comment as above

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/36391#-N9bQrvK3GdlJGSymzGy:-N9hSO2wCZTE8fQRR2xb:b7e7ijq) ([raw file](https://github.com/harness/harness-core/blob/0583107ef3df3d628f9793c4b228a8ded7d513b3/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L76)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

can this just be `boolean` instead? 
</blockquote></details>

Don't we to get the sha from the merge response?

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/36391#-N9bQrvK3GdlJGSymzGy:-N9hSePt9uvb75hclBQK:b-lio3ud) ([raw file](https://github.com/harness/harness-core/blob/0583107ef3df3d628f9793c4b228a8ded7d513b3/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L76)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Don't we to get the sha from the merge response?
</blockquote></details>

I think I'm looking at the wrong line

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java` line 76 at r1](https://reviewable.io/reviews/harness/harness-core/36391#-N9bQrvK3GdlJGSymzGy:-N9hU2Rf9k6Km9d7Qkae:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0583107ef3df3d628f9793c4b228a8ded7d513b3/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/GitlabApiClient.java#L76)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

I think I'm looking at the wrong line
</blockquote></details>

Done

**Review by GabeAboy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/gitapi/GitApiTaskParams.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/36391#-N9bR4t-4gJGC9hpkef9:-N9hU25oDVfbseuXiIJN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0583107ef3df3d628f9793c4b228a8ded7d513b3/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/gitapi/GitApiTaskParams.java#L45)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabRestClient.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/36391#-N9iR2dA6IylniZLlYAB:-N9iR2dA6IylniZLlYAC:b-48bw37) ([raw file](https://github.com/harness/harness-core/blob/c2e9edd00e94d3ef0d06db28010331ad235b5749/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabRestClient.java#L27)):*
> ```Java
>   @PUT("v4/projects/{project}/merge_requests/{prNumber}/merge")
>   Call<Object> mergePR(@Header("PRIVATE-TOKEN") String token, @Path("project") String project,
>       @Path("prNumber") String prNumber, @Query("should_remove_source_branch") Boolean should_remove_source_branch);
> ```

How about changing to `boolean` here?

**Review by GabeAboy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabRestClient.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/36391#-N9iR2dA6IylniZLlYAB:-N9mYSjI61OphF177z_i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c2e9edd00e94d3ef0d06db28010331ad235b5749/960-api-services/src/main/java/io/harness/cistatus/service/gitlab/GitlabRestClient.java#L27)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

How about changing to `boolean` here?
</blockquote></details>

Done.

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/36391#-N9mgaUW4GHuX92FTq0g:-N9mgaUX2XSbu97VPHU4:b54jm9y) ([raw file](https://github.com/harness/harness-core/blob/f477aab67310d7903ad21b580738e88b2cf28e69/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L211)):*
> ```Java
> 
>       if (fetchFilesResult == null || fetchFilesResult.getFiles().isEmpty()) {
>         // TODO Create files with variables
> ```

This seems unintentional

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: :shipit: complete! ✓

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: :shipit: complete! ✓

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: :shipit: complete! ✓

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: :shipit: complete! ✓

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger codebasehash

**Review by GabeAboy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36391)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 211 at r3](https://reviewable.io/reviews/harness/harness-core/36391#-N9mgaUW4GHuX92FTq0g:-N9nHWTXBWqVtBrQw_YJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f477aab67310d7903ad21b580738e88b2cf28e69/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L211)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This seems unintentional 
</blockquote></details>

Done.

**Pull request merged**
