### PR TITLE
[feat]: [CDS-42831]: adding service override support for svc as expression

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37252)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37252)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/37252#-NBQVEzf4lzFPQTxaYtk:-NBQVEzf4lzFPQTxaYtl:b-y3fz66) ([raw file](https://github.com/harness/harness-core/blob/72383a1d6315d944558363895af012b9a511c895/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L108)):*
> ```Java
>                                                       .collect(Collectors.toList());
>     cdExpressionResolver.updateExpressions(ambiance, manifestAttributes);
>     cdExpressionResolver.updateExpressions(ambiance, manifestAttributes);
> ```

this is duplicated



_Code quote:_
```Java
cdExpressionResolver.updateExpressions(ambiance, manifestAttributes);
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/37252#-NBQVgFaDfXG6k6F2sRH:-NBQVgFaDfXG6k6F2sRI:b-b898uc) ([raw file](https://github.com/harness/harness-core/blob/72383a1d6315d944558363895af012b9a511c895/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L49)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDC)
> @Slf4j
> ```

This can be a singleton

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/37252#-NBQVmKdCABK1z2HSkLK:-NBQVmKdCABK1z2HSkLL:b-9gynbq) ([raw file](https://github.com/harness/harness-core/blob/72383a1d6315d944558363895af012b9a511c895/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L52)):*
> ```Java
> public class ServiceStepOverrideHelper {
>   @Inject private ExecutionSweepingOutputService sweepingOutputService;
>   @Inject private CDExpressionResolver cdExpressionResolver;
> ```

looks like ```cdExpressionResolver``` is not used in this class

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37252)* status: 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 108 at r2](https://reviewable.io/reviews/harness/harness-core/37252#-NBQVEzf4lzFPQTxaYtk:-NBVlLBn3Ny-aGqIVLUh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72383a1d6315d944558363895af012b9a511c895/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L108)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is duplicated
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/37252#-NBQVgFaDfXG6k6F2sRH:-NBVlMutBLa4sgxVfF04:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/72383a1d6315d944558363895af012b9a511c895/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepOverrideHelper.java#L49)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This can be a singleton
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 5 of 7 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37252)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 71 at r7](https://reviewable.io/reviews/harness/harness-core/37252#-NBfEwld8dqDjPRYgXsS:-NBfEwld8dqDjPRYgXsT:b-kcgfad) ([raw file](https://github.com/harness/harness-core/blob/85d1d11ac5dc99169d937f13e698af593695591f/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L71)):*
> ```Java
>       ConfigFileAttributes spec = file.getConfigFile().getSpec();
>       String identifier = file.getConfigFile().getIdentifier();
>       cdExpressionResolver.updateStoreConfigExpressions(ambiance, spec.getStore().getValue());
> ```

we can get rid of this call to cdExpressionResolver since we are already calling it at line:64
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java` line 90 at r7](https://reviewable.io/reviews/harness/harness-core/37252#-NBfFHH83o4p02jrX9vA:-NBfFHH83o4p02jrX9vB:b-fx6orn) ([raw file](https://github.com/harness/harness-core/blob/85d1d11ac5dc99169d937f13e698af593695591f/125-cd-nextgen/src/main/java/io/harness/cdng/manifest/steps/ManifestsStepV2.java#L90)):*
> ```Java
>   public StepResponse executeSync(Ambiance ambiance, EmptyStepParameters stepParameters, StepInputPackage inputPackage,
>       PassThroughData passThroughData) {
>     final NgManifestsMetadataSweepingOutput ngManifestsMetadataSweepingOutput =
> ```

Lets name classes consistently
For config files, we are calling it: NgConfigFilesSweepingOutput
but here: NgManifestsMetadataSweepingOutput

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 71 at r7](https://reviewable.io/reviews/harness/harness-core/37252#-NBfEwld8dqDjPRYgXsS:-NBkAkUm4Y_zxXOhOlD8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/85d1d11ac5dc99169d937f13e698af593695591f/125-cd-nextgen/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L71)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can get rid of this call to cdExpressionResolver since we are already calling it at line:64
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37252)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37252)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 1 of 3 files at r3, 2 of 3 files at r5, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37252)* status: :shipit: complete! ✓

**Pull request merged**
