### PR TITLE
feat: [cds-41332]: Added Service schema validation for new service env redesign 

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added Service schema validation for create and update calls for new service env redesign behind CDS_SERVICE_SCHEMA_VALIDATION feature flag

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

Sample Response
```
{
    "status": "ERROR",
    "code": "SCHEMA_VALIDATION_FAILED",
    "message": "Invalid yaml: $.service.serviceDefinition.spec: is missing but it is required",
    "correlationId": "4cd8e350-01be-4617-a913-04fbd589bbfe",
    "detailedMessage": null,
    "responseMessages": [
        {
            "code": "SCHEMA_VALIDATION_FAILED",
            "level": "ERROR",
            "message": "Invalid yaml: $.service.serviceDefinition.spec: is missing but it is required",
            "exception": null,
            "failureTypes": []
        }
    ],
    "metadata": {
        "type": "YamlSchemaErrorWrapperDTO",
        "schemaErrors": [
            {
                "message": "spec: is missing but it is required",
                "messageWithFQN": "$.service.serviceDefinition.spec: is missing but it is required",
                "stageInfo": null,
                "stepInfo": null,
                "fqn": "$.service.serviceDefinition",
                "hintMessage": null
            }
        ],
        "type": "YamlSchemaErrorWrapperDTO"
    }
}
```

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 672 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW0Uor8ECW86mY_l9l:-NJW0Uor8ECW86mY_l9m:b93uo11) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L672)):*
> ```Java
>   }
> 
>   public void validateSchema(String accountId, ServiceRequestDTO serviceRequestDTO) {
> ```

nit: lets make this private



_Code quote:_
```Java
validateSchema(
```

**Comment by tchaurasiya** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 532 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW0bSDDG_gSgeFiNAz:-NJW0bSDDG_gSgeFiNB-:bsgv85) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L532)):*
> ```Java
>   CDC_SEND_NOTIFICATION_FOR_FREEZE("Send notifications for deployment freeze", HarnessTeam.CDC),
>   CDS_SERVICE_ENV_SCHEMA_VALIDATION(
>       "Added support for Service Env schema validation for new service env redesign", HarnessTeam.CDC),
> ```

If there is no plan to do schema validation for environment, Then Lets change description or even name of feature flag to only state service schema validation.
Else it will confuse CSMs that env is also getting validated.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 5 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 684 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW1aYoBKYkZyCkST5i:-NJW1aYoBKYkZyCkST5j:bgzlp5n) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L684)):*
> ```Java
>             yamlNode, validationMessages, serviceRequestDTO.getYaml());
>       } catch (io.harness.yaml.validator.InvalidYamlException e) {
>         log.info("[NG_MANAGER] Schema validation took total time {}ms", System.currentTimeMillis() - start);
> ```

just want to know, what is reasoning behind put this computational time check only in this condition.

**Comment by yogesh-chauhan** [comment]
We also need to make changes here ```io.harness.ng.core.service.resources.AbstractServicesApiImpl```. These are new API endpoints for service as per the API redesign

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 683 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJalscE6LvcKDpoDPQY:-NJalscE6LvcKDpoDPQZ:b-loocr3) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L683)):*
> ```Java
>         yamlSchemaValidator.processAndHandleValidationMessage(
>             yamlNode, validationMessages, serviceRequestDTO.getYaml());
>       } catch (io.harness.yaml.validator.InvalidYamlException e) {
> ```

Lets do import of io.harness.yaml.validator



_Code quote:_
```Java
io.harness.yaml.validator.InvalidYamlException 
```

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 684 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW1aYoBKYkZyCkST5i:-NJamK13C4dX6eWK4r1Z:b-2c2ahx) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L684)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

just want to know, what is reasoning behind put this computational time check only in this condition.
</blockquote></details>

+ 1. We should log this always (in finally block)

**Comment by yogesh-chauhan** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 532 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW0bSDDG_gSgeFiNAz:-NJamT1f27VC2DVnjv9W:b-eihp5i) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L532)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

If there is no plan to do schema validation for environment, Then Lets change description or even name of feature flag to only state service schema validation.
Else it will confuse CSMs that env is also getting validated.
</blockquote></details>

Plan is to add it for both environment/infrastructure/overrides

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceV2Test.java` line 67 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJamZvA3t0wrg5vd_jI:-NJamZvA3t0wrg5vd_jJ:byat67y) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceV2Test.java#L67)):*
> ```Java
>   @Mock AccessControlClient accessControlClient;
>   @Mock YamlSchemaValidator yamlSchemaValidator;
>   @Mock NGFeatureFlagHelperService featureFlagHelperService;
> ```

Lets add test for
- checking that validation is called in every flow
- checking the exception thrown

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 160 at r6](https://reviewable.io/reviews/harness/harness-core/41631#-NJdbdKZ7ChN_8TDXMof:-NJdbdKZ7ChN_8TDXMog:b-7u0gjc) ([raw file](https://github.com/harness/harness-core/blob/cb3e006cdb9f617927dc5e5e71711e4d25c9df0c/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L160)):*
> ```Java
>   @Inject ArtifactSourceTemplateHelper artifactSourceTemplateHelper;
>   private YamlSchemaValidator yamlSchemaValidator;
>   private final NGFeatureFlagHelperService featureFlagHelperService;
> ```

are these 2 imports needed now ? because we have moved to new class

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceSchemaHelper.java` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/41631#-NJdbY3l2wTRS8n6TPT9:-NJdbY3l2wTRS8n6TPTA:b-gbe5z6) ([raw file](https://github.com/harness/harness-core/blob/cb3e006cdb9f617927dc5e5e71711e4d25c9df0c/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceSchemaHelper.java#L33)):*
> ```Java
> 
> @AllArgsConstructor(access = AccessLevel.PACKAGE, onConstructor = @__({ @Inject }))
> @OwnedBy(HarnessTeam.CDC)
> ```

This should be Singleton

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 672 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW0Uor8ECW86mY_l9l:-NJalVC19a7RJLw7IKoL:b32v57) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L672)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: lets make this private
</blockquote></details>

+1

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 1. unresolved discussions.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 1 of 8 files at r6, 7 of 7 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 1. unresolved discussions.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631#-:-NJiLT9H8gFQNGy8rt97:bnfp4nl)* status: 1. unresolved discussions. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 532 at r5](https://reviewable.io/reviews/harness/harness-core/41631#-NJW0bSDDG_gSgeFiNAz:-NJiLPv662hocupLLrZx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86051000d573b919f43bf1ed72dc0e1a529ad6c5/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L532)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Plan is to add it for both environment/infrastructure/overrides
</blockquote></details>

Done.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 1 of 8 files at r6, 7 of 7 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: 1. unresolved discussions.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41631)* status: :shipit: complete! ✓

**Pull request merged**
