### PR TITLE
[techdebt]: [PIE-6449]: Refactor OrchestrationEventLog and PlanExecut…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…ionStatusUpdate

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40309)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40309)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8Fp5aC8qt3m6qw6A3:-NH8Fp5aC8qt3m6qw6A4:b-g0j5p1) ([raw file](https://github.com/harness/harness-core/blob/0a649be072642315d7d2dd0f3bd362477af12f14/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryService.java#L24)):*
> ```Java
>   void regenerateStageLayoutGraph(String planExecutionId, List<NodeExecution> nodeExecutions);
> 
>   boolean onPlanStatusUpdate(PlanExecution planExecution, Update update);
> ```

rename -> updateExecutionSummaryOnPlanStatusUpdate ?



_Code quote:_
```Java
onPlanStatusUpdate
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8GClBC7yA2dx2x5Vw:-NH8GClBC7yA2dx2x5Vx:b-30cqzz) ([raw file](https://github.com/harness/harness-core/blob/0a649be072642315d7d2dd0f3bd362477af12f14/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L171)):*
> ```Java
>           PlanExecution planExecution = planExecutionService.getWithStatusAndEndTs(planExecutionId);
>           updateRequired =
>               pmsExecutionSummaryService.onPlanStatusUpdate(planExecution, executionSummaryUpdate) || updateRequired;
> ```

just checking why do we need to do executionSummary update here and it was not there earlier



_Code quote:_
```Java
          PlanExecution planExecution = planExecutionService.getWithStatusAndEndTs(planExecutionId);
          updateRequired =
              pmsExecutionSummaryService.onPlanStatusUpdate(planExecution, executionSummaryUpdate) || updateRequired;
```
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 675 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8G_tW7VCVqW5rZ4qV:-NH8G_tW7VCVqW5rZ4qW:bcrtiv1) ([raw file](https://github.com/harness/harness-core/blob/04d5957f4f6e055589227935a91dc14a4c737134/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L675)):*
> ```Java
>     QueueListenerController queueListenerController = injector.getInstance(QueueListenerController.class);
>     queueListenerController.register(injector.getInstance(DelayEventListener.class), 1);
>     queueListenerController.register(injector.getInstance(PmsNotifyEventListener.class), 3);
> ```

can we delete PmsNotifyEventListener as well 



_Code quote:_
```Java
queueListenerController.register(injector.getInstance(PmsNotifyEventListener.class), 3);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8HBXg01V2Gg9ynUlu:-NH8HBXg01V2Gg9ynUlv:b-nrm5jo) ([raw file](https://github.com/harness/harness-core/blob/04d5957f4f6e055589227935a91dc14a4c737134/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L43)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class PipelineStatusUpdateEventHandler implements PlanStatusUpdateObserver, OrchestrationEndObserver {
> ```

Can we connect on this

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8HBXg01V2Gg9ynUlu:-NH8HydY6L5FS9VRLkJp:b3haovv) ([raw file](https://github.com/harness/harness-core/blob/04d5957f4f6e055589227935a91dc14a4c737134/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we connect on this
</blockquote></details>

I have moved this to GraphGenerationServiceImpl

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40309)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8GClBC7yA2dx2x5Vw:-NHP8KcgEM9J_xzBKJzW:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/0a649be072642315d7d2dd0f3bd362477af12f14/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L171)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

just checking why do we need to do executionSummary update here and it was not there earlier
</blockquote></details>

Discussed offline

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java` line 171 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8GClBC7yA2dx2x5Vw:-NHSgayDCQQgHZ8Sz4ot:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0a649be072642315d7d2dd0f3bd362477af12f14/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java#L171)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Discussed offline
</blockquote></details>

Done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 675 at r1](https://reviewable.io/reviews/harness/harness-core/40309#-NH8G_tW7VCVqW5rZ4qV:-NHSgfhS3M_1KFJ1let3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04d5957f4f6e055589227935a91dc14a4c737134/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L675)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we delete PmsNotifyEventListener as well 
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 17 files at r1, 3 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40309)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40309)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by archit-harness** [comment]
trigger messagecheck

**Pull request merged**
