### PR TITLE
fix: [CDS-78903]: Reduce call to resolveStepInputs for every step

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Describe your changes
There is a lot of dead code present because of Stepgroup rollback which we earlier supported but are not supporting now.

This change removes the rollbackinfo present in every step and now use information directly from ambiance.

This will help us save:
- Expression engine calls.
- Space which we are using to store two duplicate json.

Testing done
- Create a pipeline with cd stage and make it fail. Rollback was triggered as expected.

Screenshots
Without this change:
Screenshot 2023-09-07 at 12 38 10 PM

With this change:
Screenshot 2023-09-07 at 12 37 58 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers

<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52409)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by hextechpal — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52409)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52409)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/beans/DeploymentStageStepParameters.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/52409#-NdUUwMt9LSYnwOXNHin:-NdUUwMt9LSYnwOXNHio:b-1v4cu1) ([raw file](https://github.com/harness/harness-core/blob/a883c36e568f9299bf2c55cad53ae69f15f2d083/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/beans/DeploymentStageStepParameters.java#L34)):*
> ```Java
>   @Override
>   public SpecParameters getViewJsonObject() {
>     return DeploymentStageStepParameters.builder().build();
> ```

we can keep this right?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StageElementParameters.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/52409#-NdZ2nnf9_KjzExriUC9:-NdZ2nnf9_KjzExriUCA:b6zlvut) ([raw file](https://github.com/harness/harness-core/blob/a883c36e568f9299bf2c55cad53ae69f15f2d083/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StageElementParameters.java#L55)):*
> ```Java
>     StageElementParameters stageElementParameters = cloneParameters();
>     stageElementParameters.setSpecConfig(specConfig.getViewJsonObject());
>     return RecastOrchestrationUtils.toJson(stageElementParameters);
> ```

can you add sshot of input UI section view after your changes

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/beans/DeploymentStageStepParameters.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/52409#-NdUUwMt9LSYnwOXNHin:-NdiVgIe28AmxrHXoPs0:b7x7dz) ([raw file](https://github.com/harness/harness-core/blob/a883c36e568f9299bf2c55cad53ae69f15f2d083/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/pipeline/beans/DeploymentStageStepParameters.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we can keep this right?
</blockquote></details>

Yes, but I don't see any importance of this. Maybe for stage we can convert to null?

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StageElementParameters.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/52409#-NdZ2nnf9_KjzExriUC9:-NdiVo-g5RxZuDILJW5C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a883c36e568f9299bf2c55cad53ae69f15f2d083/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/steps/common/StageElementParameters.java#L55)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add sshot of input UI section view after your changes
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52409)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52409)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger review

**Review by Y0709 — APPROVED** [review]

**Pull request merged**
