### PR TITLE
[fix]: [CDS-36563]: Fixed setting up aws ami variables in sweeping output for BG incremental

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32390)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32390)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/AwsAmiServiceTrafficShiftAlbSetup.java, line 101 at r1](https://reviewable.io/reviews/harness/harness-core/32390#-N0FD3VR9mWs-jvNcayc:-N0FD3VU4eCPe_N-vYQ9:bcsa15l) ([raw file](https://github.com/harness/harness-core/blob/fc8218c732b9d13a522c115e786e83c30e2c69f1/400-rest/src/main/java/software/wings/sm/states/AwsAmiServiceTrafficShiftAlbSetup.java#L101)):*
> ```Java
>   @Inject private AwsStateHelper awsStateHelper;
>   @Inject private FeatureFlagService featureFlagService;
>   @Inject private WorkflowExecutionService workflowExecutionService;
> ```

It looks like we don't use it
___
*[400-rest/src/main/java/software/wings/sm/states/AwsStateHelper.java, line 69 at r1](https://reviewable.io/reviews/harness/harness-core/32390#-N0FDLBP8C3oVDLrXopZ:-N0FDLBP8C3oVDLrXop_:b-7c7iqw) ([raw file](https://github.com/harness/harness-core/blob/fc8218c732b9d13a522c115e786e83c30e2c69f1/400-rest/src/main/java/software/wings/sm/states/AwsStateHelper.java#L69)):*
> ```Java
>   @Inject private ServiceResourceService serviceResourceService;
>   @Inject private SweepingOutputService sweepingOutputService;
>   @Inject private WorkflowExecutionService workflowExecutionService;
> ```

the same here.

**Comment by arvind-choudhary-h** [comment]
*[400-rest/src/main/java/software/wings/sm/states/AwsAmiServiceTrafficShiftAlbSetup.java, line 101 at r1](https://reviewable.io/reviews/harness/harness-core/32390#-N0FD3VR9mWs-jvNcayc:-N0FHZDJ12I6Xp3B_6iS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fc8218c732b9d13a522c115e786e83c30e2c69f1/400-rest/src/main/java/software/wings/sm/states/AwsAmiServiceTrafficShiftAlbSetup.java#L101)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

It looks like we don't use it
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[400-rest/src/main/java/software/wings/sm/states/AwsStateHelper.java, line 69 at r1](https://reviewable.io/reviews/harness/harness-core/32390#-N0FDLBP8C3oVDLrXopZ:-N0FH__PEY5pI2JslOqY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fc8218c732b9d13a522c115e786e83c30e2c69f1/400-rest/src/main/java/software/wings/sm/states/AwsStateHelper.java#L69)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

the same here.
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32390)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Pull request merged**
