### PR TITLE
[feat]: [CDS-42651]: added api to get service v2 yaml and input set

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37129)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 3 Issues 
* Code issue 1 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37129)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCWbSf4iAHmGlZVOge:-NBCWbSf4iAHmGlZVOgf:b3f13mm) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java#L22)):*
> ```Java
> import lombok.experimental.FieldDefaults;
> 
> @OwnedBy(PIPELINE)
> ```

OwnedBy: CD

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCWhnJE9ywvYM5KmvL:-NBCWhnKDdkTj5jiBmrd:b94n01j) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java#L30)):*
> ```Java
> @ApiModel("ServiceV2YamlMetadata")
> public class ServiceV2YamlMetadata {
>   String serviceIdentifier;
> ```

lets also put NotNull annotations

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadataDTO.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCWoIa9veSeb_DQuQs:-NBCWoIa9veSeb_DQuQt:b-r4esrp) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadataDTO.java#L30)):*
> ```Java
> @JsonInclude(JsonInclude.Include.NON_NULL)
> @ApiModel("ServiceV2YamlMetadataDTO")
> public class ServiceV2YamlMetadataDTO {
> ```

We can call this Services..

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadataDTO.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCWuiU6-6qfyeNV7Mo:-NBCWuiU6-6qfyeNV7Mp:b32vqe) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadataDTO.java#L23)):*
> ```Java
> import lombok.experimental.FieldDefaults;
> 
> @OwnedBy(PIPELINE)
> ```

CD

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 461 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCX7Tq7cD3z_YnK4jK:-NBCX7Tq7cD3z_YnK4jL:b-n3m9g8) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L461)):*
> ```Java
>   }
> 
>   @GET
> ```

this should be POST right ?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCWbSf4iAHmGlZVOge:-NBCcHs_3KvMHSK1lsnh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java#L22)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

OwnedBy: CD
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCWhnJE9ywvYM5KmvL:-NBCcJL_-bnXKfHX5CHI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/beans/ServiceV2YamlMetadata.java#L30)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets also put NotNull annotations
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 461 at r2](https://reviewable.io/reviews/harness/harness-core/37129#-NBCX7Tq7cD3z_YnK4jK:-NBCcKrF1AlEbouPZanl:b-kb86i) ([raw file](https://github.com/harness/harness-core/blob/066d9602995cfa0e400a74a5560b1c108fa54f97/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L461)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this should be POST right ?
</blockquote></details>

Yeah fixed. Some issue happened with rebase, somehow got it wrong.

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37129)* status: :shipit: complete! ✓

**Pull request merged**
