### PR TITLE
feat: [CDS-42991]: Terraform Human Readable Plan for NG

### PR DESCRIPTION
**Pull request by akhilpandey1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)

### CODE REVIEW

**Comment by akhilpandey1** [comment]
trigger feature-build

**Comment by diptiman-adak** [comment]
trigger featurenamecheck

**Comment by diptiman-adak** [comment]
trigger featurenamecheck

**Comment by diptiman-adak** [comment]
trigger featurenamecheck

**Comment by akhilpandey1** [comment]
trigger feature-build

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 20 files at r1, 4 of 10 files at r2, 1 of 5 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 512 at r4](https://reviewable.io/reviews/harness/harness-core/39943#-NGum7ua3v8Jg9b-6eX2:-NGum7ua3v8Jg9b-6eX3:bu5m75d) ([raw file](https://github.com/harness/harness-core/blob/16b7314be5b13862c072862f7a69fa8b8b66bcdc/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L512)):*
> ```Java
>             .build();
> 
>     List<TerraformPlanExecutionDetails> terraformPlanExecutionDetailsList =
> ```

Can you recheck this part with develop, I believe @vlica-harness made some changes around this. Clean up will not happen because terraform plan execution details will be deleted by clean up tf plan json
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandler.java` line 216 at r4](https://reviewable.io/reviews/harness/harness-core/39943#-NGuncru9L7CL0G4UO4t:-NGuncrv3kgUS_OE1PJ8:bjkw42v) ([raw file](https://github.com/harness/harness-core/blob/16b7314be5b13862c072862f7a69fa8b8b66bcdc/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandler.java#L216)):*
> ```Java
> 
>       logCallback.saveExecutionLog(
>           format("\nTerraform Human Readable plan will be available at: %s\n", tfHumanReadableFilePath), INFO,
> ```

This is not true, customer wouldn't have access to this path after provision task is completed

**Review by alebuh — CHANGES_REQUESTED** [review]
As the implementation is similar to the one for exportTfPlanJson, I'm just wondering if it is worth doing some refactoring to reuse existing code and avoid duplicating code lines? Not sure how much effort that would take or if it's risky, just throwing idea here 

> Reviewed 9 of 20 files at r1, 2 of 10 files at r2, 1 of 5 files at r3, 10 of 12 files at r4, 34 of 34 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943#-:-NGw0O4kEk8ALVvqgBQ8:b1kbnr0)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java` line 243 at r5](https://reviewable.io/reviews/harness/harness-core/39943#-NGvshDY8O13A7m5VxoC:-NGvshDY8O13A7m5VxoD:b-x6npl) ([raw file](https://github.com/harness/harness-core/blob/9c64eb96d6548eb927aea87b6246ad2167ff4652/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java#L243)):*
> ```Java
>         String humanReadableOutputName =
>             helper.saveTerraformPlanHumanReadableOutput(ambiance, terraformTaskNGResponse, provisionerIdentifier);
>         helper.saveTerraformPlanExecutionDetails(
> ```

We are calling the same method with the same inputs later when exportTfPlanJson is true. Is it possible to have exportTfPlanJson and exportHumanReadablePlan set to true?

**Comment by akhilpandey1** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 512 at r4](https://reviewable.io/reviews/harness/harness-core/39943#-NGum7ua3v8Jg9b-6eX2:-NGwCKNOE9K1PD69Jl1U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16b7314be5b13862c072862f7a69fa8b8b66bcdc/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L512)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can you recheck this part with develop, I believe @vlica-harness made some changes around this. Clean up will not happen because terraform plan execution details will be deleted by clean up tf plan json
</blockquote></details>

Done.

**Comment by akhilpandey1** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandler.java` line 216 at r4](https://reviewable.io/reviews/harness/harness-core/39943#-NGuncru9L7CL0G4UO4t:-NGwCNpmA_C-oOoTPVQ3:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/16b7314be5b13862c072862f7a69fa8b8b66bcdc/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/handlers/TerraformPlanTaskHandler.java#L216)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is not true, customer wouldn't have access to this path after provision task is completed
</blockquote></details>

removed

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 33 of 34 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 512 at r4](https://reviewable.io/reviews/harness/harness-core/39943#-NGum7ua3v8Jg9b-6eX2:-NH07cCGCyVCyNNH9gAU:b-t0waf6) ([raw file](https://github.com/harness/harness-core/blob/16b7314be5b13862c072862f7a69fa8b8b66bcdc/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L512)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I believe you need to pass terraformPlanExecutionDetailsList as argument instead of fetching it again, it should be available in event handler

**Comment by akhilpandey1** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 512 at r4](https://reviewable.io/reviews/harness/harness-core/39943#-NGum7ua3v8Jg9b-6eX2:-NH4Yfgg2BOARFQ26t6k:b-6qdqdi) ([raw file](https://github.com/harness/harness-core/blob/16b7314be5b13862c072862f7a69fa8b8b66bcdc/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L512)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I believe you need to pass terraformPlanExecutionDetailsList as argument instead of fetching it again, it should be available in event handler
</blockquote></details>

Thanks, I pass it from the handler now

**Comment by akhilpandey1** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java` line 243 at r5](https://reviewable.io/reviews/harness/harness-core/39943#-NGvshDY8O13A7m5VxoC:-NH4ZAEX8CYNwFMdj0HK:b7oxv5g) ([raw file](https://github.com/harness/harness-core/blob/9c64eb96d6548eb927aea87b6246ad2167ff4652/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java#L243)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

We are calling the same method with the same inputs later when exportTfPlanJson is true. Is it possible to have exportTfPlanJson and exportHumanReadablePlan set to true? 
</blockquote></details>

The method is different for both, here its    `helper.saveTerraformPlanExecutionDetails` whereas in Json its `  helper.saveTerraformPlanJsonOutput`
We can discuss if this more on this if required

**Review by akhilpandey1 — COMMENTED** [review]
Good idea, I think we can explore this and do in a follow-up PR

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943#-:-NH4YsfUBXgygHd9FLKw:b-saojpi)* status: 5 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: 1 change requests. 1. unresolved discussions.

**Review by alebuh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java` line 243 at r5](https://reviewable.io/reviews/harness/harness-core/39943#-NGvshDY8O13A7m5VxoC:-NH4l8yP-e19gsUaEi8X:brwayi7) ([raw file](https://github.com/harness/harness-core/blob/9c64eb96d6548eb927aea87b6246ad2167ff4652/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformPlanStep.java#L243)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

The method is different for both, here its    `helper.saveTerraformPlanExecutionDetails` whereas in Json its `  helper.saveTerraformPlanJsonOutput`
We can discuss if this more on this if required
</blockquote></details>

Discussed over the call. @akhilpandey1 confirmed that it's been already tested and it's not causing an issue if we call it twice.

**Review by alebuh — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

**Comment by akhilpandey1** [comment]
trigger feature-build

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 20 files at r1, 1 of 10 files at r2, 4 of 12 files at r4, 20 of 34 files at r5, 4 of 5 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 450 at r9](https://reviewable.io/reviews/harness/harness-core/39943#-NH8k70F5Dr_BZTXmIvO:-NH8k70F5Dr_BZTXmIvP:b9si4u6) ([raw file](https://github.com/harness/harness-core/blob/e4fc95b2a26523adcb4102f92614638ca9f00e28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L450)):*
> ```Java
>   public void saveTerraformPlanExecutionDetails(Ambiance ambiance, TerraformTaskNGResponse response,
>       String provisionerIdentifier, TerraformPlanStepParameters planStepParameters) {
>     if (isEmpty(response.getTfPlanJsonFileId()) && isEmpty(response.getTfHumanReadablePlanFileId())) {
> ```

@vlica-harness @akhilpandey1 not sure if the condition is correct.
We should save execution details only if jsonPlan and human readable plan is present.
What if they're not.... we still have to cleanup secrets (or I'm wrong) ?

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 20 files at r1, 1 of 10 files at r2, 1 of 5 files at r3, 5 of 12 files at r4, 11 of 34 files at r5, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 450 at r9](https://reviewable.io/reviews/harness/harness-core/39943#-NH8k70F5Dr_BZTXmIvO:-NH8wipR5aUAcaXgdwph:blww2dx) ([raw file](https://github.com/harness/harness-core/blob/e4fc95b2a26523adcb4102f92614638ca9f00e28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L450)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

@vlica-harness @akhilpandey1 not sure if the condition is correct.
We should save execution details only if jsonPlan and human readable plan is present.
What if they're not.... we still have to cleanup secrets (or I'm wrong) ?
</blockquote></details>

I would say we don't need this condition at all, because we need to save all the time executionDetails in order to clean the secrets from vault. 



_Code quote:_
```Java
saveTerraformPlanExecutionDetails
```

**Comment by akhilpandey1** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 450 at r9](https://reviewable.io/reviews/harness/harness-core/39943#-NH8k70F5Dr_BZTXmIvO:-NH9-ohV0MKWiBirMJSm:bomt5ht) ([raw file](https://github.com/harness/harness-core/blob/e4fc95b2a26523adcb4102f92614638ca9f00e28/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L450)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

I would say we don't need this condition at all, because we need to save all the time executionDetails in order to clean the secrets from vault. 
</blockquote></details>

done, this is removed

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

**Review by vlica-harness — APPROVED** [review]

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 7 of 20 files at r1, 2 of 10 files at r2, 1 of 5 files at r3, 9 of 12 files at r4, 28 of 34 files at r5, 4 of 5 files at r7, 1 of 2 files at r8, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39943)* status: :shipit: complete! ✓

**Pull request merged**
