### PR TITLE
feat: [PL-39555]: Added roles and rg for anonymous access

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes

Final Implementation:
1. Add new field `publicRole` in Role object to identify public roles while creating roleassingments.
2. Public role are also marked as managed role (the ones that we are adding OOB)
3. We are not maintaining separate file for maintaining public_roles. (This is different from what was decided in ADR)
4. For generation of public role we are using existing RoleManagementJob (as these are also managed) 
5. Added `publicResource` flag in existing resourceType.yml. Not used separate file. -  (This is different from what was decided in ADR)

Testing done
1. Restart ACS application.
2. New roles with public field gets created.
3. Existing resource type document gets updated with field `isPublic` as true

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)* status: 4 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/public-resources.yml` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/51386#-NbXomKL2l4QaeFm0Vwd:-NbXomKL2l4QaeFm0Vwe:bgu07qq) ([raw file](https://github.com/harness/harness-core/blob/c281ad545b1b57f659203369b1c5b787257a867d/access-control/service/src/main/resources/io/harness/accesscontrol/resources/public-resources.yml#L2)):*
> ```YAML
> # Any edit in this file should accompany an increment in version.
> name: publicResourceTypes
> ```

Instead of a new file, can we add public field in resourceTypes.yml instead?
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 1039 at r1](https://reviewable.io/reviews/harness/harness-core/51386#-NbXpAdL4H2nVgwWDZZz:-NbXpAdL4H2nVgwWDZ_-:btlgu3d) ([raw file](https://github.com/harness/harness-core/blob/c281ad545b1b57f659203369b1c5b787257a867d/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L1039)):*
> ```YAML
>         - project
>     - identifier: _pipeline_allUsers_access_role
>       name: Pipeline All Users Access Role
> ```

Did we get the name of the roles reviewed with PM

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)* status: 4 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/Role.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/51386#-NbVDQag4s3bJLDYwcH3:-NbXqjrNBZMnjJUBtT7T:b-39gj7t) ([raw file](https://github.com/harness/harness-core/blob/c281ad545b1b57f659203369b1c5b787257a867d/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/Role.java#L45)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Rename to public.
</blockquote></details>

public is a reserved keyword, we cannot use it.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/public-resources.yml` line 1 at r1](https://reviewable.io/reviews/harness/harness-core/51386#-NbVDK_pDe0oeNdQG6tX:-NbXqrOK4lJX-1bRrvjk:b-adh4mp) ([raw file](https://github.com/harness/harness-core/blob/c281ad545b1b57f659203369b1c5b787257a867d/access-control/service/src/main/resources/io/harness/accesscontrol/resources/public-resources.yml#L1)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add version. 
</blockquote></details>

We don't need version for this, as this is only the static file with list of ResourceTypes supported for public role which will be fetched to validate resource type at runtime. We are not storing these in DB.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/public-resources.yml` line 2 at r1](https://reviewable.io/reviews/harness/harness-core/51386#-NbXomKL2l4QaeFm0Vwd:-NbXrLLHAlKhdWmy1E0f:b-6i1rt1) ([raw file](https://github.com/harness/harness-core/blob/c281ad545b1b57f659203369b1c5b787257a867d/access-control/service/src/main/resources/io/harness/accesscontrol/resources/public-resources.yml#L2)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Instead of a new file, can we add public field in resourceTypes.yml instead?
</blockquote></details>

Yes let we try that

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)* status: 12 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcetypes/ResourceType.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/51386#-NboRZn6E54J0kbcH9JT:-NboRJPdCim8mvEr7nqw:b-lw4jma) ([raw file](https://github.com/harness/harness-core/blob/0b408e601b04c0a986bde090e11ac5f8c4dc0f32/access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcetypes/ResourceType.java#L25)):*
> ```Java
>   @NotEmpty String identifier;
>   @NotEmpty String permissionKey;
>   boolean publicResource;
> ```

public
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcetypes/persistence/ResourceTypeDBO.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/51386#-NboRdEW6DtEQHzHPJ5h:-NboRdEW6DtEQHzHPJ5i:b-dqakv8) ([raw file](https://github.com/harness/harness-core/blob/0b408e601b04c0a986bde090e11ac5f8c4dc0f32/access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcetypes/persistence/ResourceTypeDBO.java#L54)):*
> ```Java
>   @FdUniqueIndex @NotEmpty final String identifier;
>   @FdUniqueIndex @NotEmpty final String permissionKey;
>   @Builder.Default Boolean publicResource = Boolean.FALSE;
> ```

publicResource
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/Role.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/51386#-NboRMMnCdE1GfXooS7s:-NboRMMnCdE1GfXooS7t:b-lw4jma) ([raw file](https://github.com/harness/harness-core/blob/0b408e601b04c0a986bde090e11ac5f8c4dc0f32/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/Role.java#L45)):*
> ```Java
>   final boolean managed;
>   final boolean internal;
>   final boolean publicRole;
> ```

public
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBO.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/51386#-NboRm-eAKUqzlE45e_y:-NboRm-eAKUqzlE45e_z:b-lw4jma) ([raw file](https://github.com/harness/harness-core/blob/0b408e601b04c0a986bde090e11ac5f8c4dc0f32/access-control/libs/core/src/main/java/io/harness/accesscontrol/roles/persistence/RoleDBO.java#L73)):*
> ```Java
>   @NotNull final Set<String> permissions;
>   final boolean managed;
>   @Builder.Default final Boolean publicRole = Boolean.FALSE;
> ```

public
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/51386#-NboRt-P-I1BqOHbsG9D:-NboRt-P-I1BqOHbsG9E:b-lw4jma) ([raw file](https://github.com/harness/harness-core/blob/0b408e601b04c0a986bde090e11ac5f8c4dc0f32/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L21)):*
> ```YAML
>   - identifier: PIPELINE
>     permissionKey: pipeline
>     publicResource: true
> ```

public

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)* status: 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcetypes/ResourceType.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/51386#-NboRZn6E54J0kbcH9JT:-Nboajm97QF6NPqbo3mF:b-598dp5) ([raw file](https://github.com/harness/harness-core/blob/0b408e601b04c0a986bde090e11ac5f8c4dc0f32/access-control/libs/core/src/main/java/io/harness/accesscontrol/resources/resourcetypes/ResourceType.java#L25)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

public
</blockquote></details>

changed to isPublic

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 10 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)* status: 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386#-:-NbocwbUB7_6QCBR486T:bnfp4nl)* status: 12 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by meenakshi-harness** [comment]
trigger ut1

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger ut6

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 10 files at r2, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51386)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
