### PR TITLE
[feat]: [PL-31353]: Adds support to get child scope user groups in list user groups api

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
There is ask to to provide list of User Groups for account including child scopes. 

As part of this we are extending [user group list](https://apidocs.harness.io/tag/User-Group/#operation/getUserGroupList) api to support one more filtertype value `INCLUDE_CHILD_SCOPE_GROUPS`. This allows to include child scoped user groups in response.

Test
- Tested in PR environment response looks fine with new filter type

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44260)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44260)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44260)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 702 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxX1WUAZVeFipPGCqI:-NOxX1WUAZVeFipPGCqJ:b-pkp0bf) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L702)):*
> ```Java
> 
>   @Test
>   @Owner(developers = NAMANG)
> ```

change to developers = ASHISHSANODIA



_Code quote:_
```Java
developers = ASHISHSANODIA
```
___
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 728 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxX5AG8VH4hqKO2F4s:-NOxX5AG8VH4hqKO2F4t:b-pkp0bf) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L728)):*
> ```Java
> 
>   @Test
>   @Owner(developers = NAMANG)
> ```

change to developers = ASHISHSANODIA
___
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 752 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxXuABE00B0ZtiASmo:-NOxXuABE00B0ZtiASmp:b-pkp0bf) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L752)):*
> ```Java
> 
>   @Test
>   @Owner(developers = NAMANG)
> ```

change to developers = ASHISHSANODIA
___
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxXwnh88ShEMIWOfSS:-NOxXwnh88ShEMIWOfST:b-pkp0bf) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L780)):*
> ```Java
> 
>   @Test
>   @Owner(developers = NAMANG)
> ```

change to developers = ASHISHSANODIA

**Comment by ashishsanodia-harness** [comment]
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 702 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxX1WUAZVeFipPGCqI:-NOxjopi3DvhW9w8YpMY:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L702)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change to developers = ASHISHSANODIA
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 728 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxX5AG8VH4hqKO2F4s:-NOxjrkb7SYvz1Nqldq0:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L728)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change to developers = ASHISHSANODIA
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 752 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxXuABE00B0ZtiASmo:-NOxjsrTE0Jhnxiz02p9:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L752)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change to developers = ASHISHSANODIA
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java` line 780 at r1](https://reviewable.io/reviews/harness/harness-core/44260#-NOxXwnh88ShEMIWOfSS:-NOxjthuDEz6ctTr2xJm:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/f47d6b40f25a75dbdd88b46eb1b32ef39f06952c/123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java#L780)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change to developers = ASHISHSANODIA
</blockquote></details>

Fixed

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44260#-:-NOxlNrV3B06Z7mg4D5d:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44260)* status: :shipit: complete! ✓

**Pull request merged**
