### PR TITLE
[feat]: [CCM-11754]: Publish redis events on settings update

### PR DESCRIPTION
**Pull request by sdsingh07**
## Describe your changes
CCM is preparing to launch a new feature called `perspective preferences`, which is outlined in the default account settings. As part of this implementation, whenever there is an update in the perspective preferences, we require an event to trigger certain operations on the BE side. To accomplish this, we are publishing redis events on settings update.

**Testing:**
1. Successfully updated default settings across various categories and able to publish individual events for each category.
2. Updated default settings that include a groupIdentifier. Able to publish event based on the <category, groupIdentifier> combination.
3. Updated default settings without a groupIdentifier. Handled `null` groupIdentifier in the event's metadata and able to successfully published the event.

**Event Messages:**
```
Events framework message inserted - messageId: 1689340859210-0, metaData: {accountId=kmpySmUISimoRrJL6NL73w, entityType=settings, settingGroupIdentifier=perspective_preferences, action=update, producer=NextGenManager, settingCategory=CE} in the topic: entity_crud

Events framework message inserted - messageId: 1689340859212-0, metaData: {accountId=kmpySmUISimoRrJL6NL73w, entityType=settings, settingGroupIdentifier=pms_execution_settings, action=update, producer=NextGenManager, settingCategory=PMS} in the topic: entity_crud

Events framework message inserted - messageId: 1689340859214-0, metaData: {action=update, accountId=kmpySmUISimoRrJL6NL73w, producer=NextGenManager, entityType=settings, settingCategory=PMS} in the topic: entity_crud
```

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50531)

### CODE REVIEW

**Comment by sdsingh07** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by sdsingh07** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50531)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/50531#-N_JGQly9ASkOL-Xqujb:-N_JGQly9ASkOL-Xqujc:b-q76etk) ([raw file](https://github.com/harness/harness-core/blob/f9f53a759942efa024de7b3ccfbe5af32911e66b/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java#L74)):*
> ```Java
>   public static final String SETTINGS = "settings";
>   public static final String SETTINGS_GROUP_IDENTIFIER = "group";
>   public static final String SETTINGS_CATEGORY = "category";
> ```

prepend value with setting.



_Code snippet:_
```Java
  public static final String SETTINGS_GROUP_IDENTIFIER = "settingGroupIdentifier";
  public static final String SETTINGS_CATEGORY = "settingCategory";
```
___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/settings/settings_entity.proto` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/50531#-N_JHMU53CJL6le6Y7KX:-N_JHMU53CJL6le6Y7KY:brju0fy) ([raw file](https://github.com/harness/harness-core/blob/f9f53a759942efa024de7b3ccfbe5af32911e66b/953-events-api/src/main/proto/io/harness/eventsframework/schemas/settings/settings_entity.proto#L14)):*
> ```proto
> option go_package = "953_events_api";
> 
> message SettingsEntityChangeDTO {
> ```

Should this proto placed under entity_crud?

**Review by sdsingh07 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50531)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/50531#-N_JGQly9ASkOL-Xqujb:-N_JL86h7NunDmdKJ9Nc:b-837i3v) ([raw file](https://github.com/harness/harness-core/blob/f9f53a759942efa024de7b3ccfbe5af32911e66b/953-events-api/src/main/java/io/harness/eventsframework/EventsFrameworkMetadataConstants.java#L74)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

prepend value with setting.
</blockquote></details>

Okay.
___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/settings/settings_entity.proto` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/50531#-N_JHMU53CJL6le6Y7KX:-N_JL1038xz1asrJTuTs:b-jgse2q) ([raw file](https://github.com/harness/harness-core/blob/f9f53a759942efa024de7b3ccfbe5af32911e66b/953-events-api/src/main/proto/io/harness/eventsframework/schemas/settings/settings_entity.proto#L14)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should this proto placed under entity_crud?
</blockquote></details>

No. Will put it under `entity_crud`.

**Comment by sdsingh07** [comment]
trigger uts

**Comment by sdsingh07** [comment]
trigger ut1

**Pull request merged**
