### PR TITLE
[feat]: [CDS-34034]: Added support for storing Rollback data

### PR DESCRIPTION
**Pull request by ivan-83**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)

### CODE REVIEW

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 8 of 21 files at r1, 2 of 12 files at r2, 14 of 17 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger messagecheck

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 21 files at r1, 2 of 12 files at r2, 14 of 17 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/rollback/RollbackData.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8NyhZUE6yOrd9Hhw7n:-N8NyhZUE6yOrd9Hhw7o:b-4s8co8) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/125-cd-nextgen/src/main/java/io/harness/cdng/rollback/RollbackData.java#L50)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> public class RollbackData implements PersistentEntity, UuidAware {
>   @org.springframework.data.annotation.Id @Id String uuid;
> ```

So which one of these Id's are required? Are we messing spring data + morphia?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/CommandStepRollbackDeploymentInfo.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8O-BNBCuliW2cpF1Zk:-N8O-BNC2vszyOQh4wBP:bjb8xb7) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/CommandStepRollbackDeploymentInfo.java#L27)):*
> ```Java
> public class CommandStepRollbackDeploymentInfo implements RollbackDeploymentInfo {
>   private ArtifactOutcome artifactOutcome;
>   private ConfigFilesOutcome configFilesOutcome;
> ```

Not aware of all usages here, but does the config files supporting versioning here? If you're going to store details of how to fetch data without versioning it, it may result in using newer version of file and not deployed version
___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/rollback/RollbackDataRepositoryCustom.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8Nzw88BrNL2tanhZnT:-N8Nzw88BrNL2tanhZnU:b-a6tlnk) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/125-cd-nextgen/src/main/java/io/harness/repositories/rollback/RollbackDataRepositoryCustom.java#L23)):*
> ```Java
>   UpdateResult updateStatus(String stageExecutionId, StageStatus status);
> 
>   List<RollbackData> listRollbackDataOrderedByCreatedAt(String key, StageStatus status, int limit);
> ```

Aren't Sprint Data supports these terms? Same for updateStatus, why we do need custom implementation?
___
*[`980-commons/src/main/java/io/harness/utils/StageStatus.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8O-zev9dohNe3bR_oT:-N8O-zev9dohNe3bR_oU:b397p5k) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/980-commons/src/main/java/io/harness/utils/StageStatus.java#L20)):*
> ```Java
>   SUCCEEDED("SUCCEEDED"),
>   FAILED("FAILED"),
>   UNKNOWN("UNKNOWN");
> ```

What is unknown status here? Should not we have instead in progress status for rollback data just created?

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)* status: 22 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/rollback/RollbackData.java` line 50 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8NyhZUE6yOrd9Hhw7n:-N8O5UYw84i3nco0TkpS:b320l6o) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/125-cd-nextgen/src/main/java/io/harness/cdng/rollback/RollbackData.java#L50)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

So which one of these Id's are required? Are we messing spring data + morphia?
</blockquote></details>

Yes, we are using the best from both.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/CommandStepRollbackDeploymentInfo.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8O-BNBCuliW2cpF1Zk:-N8O3kl48NP2OK1J0Qcw:b-wdio3e) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/CommandStepRollbackDeploymentInfo.java#L27)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Not aware of all usages here, but does the config files supporting versioning here? If you're going to store details of how to fetch data without versioning it, it may result in using newer version of file and not deployed version
</blockquote></details>

Yes, that is true, in the new version of CommandStepRollbackDeploymentInfo on which we are working on, we are not storing outcomes. 
___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/rollback/RollbackDataRepositoryCustom.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8Nzw88BrNL2tanhZnT:-N8O49_8DiTTOzrzkGnn:b-aojdgb) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/125-cd-nextgen/src/main/java/io/harness/repositories/rollback/RollbackDataRepositoryCustom.java#L23)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Aren't Sprint Data supports these terms? Same for updateStatus, why we do need custom implementation?
</blockquote></details>

Yes, it supports, the outcome is the same, morphia provides more control. Generally, custom implementation is needed for complex queries.

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)* status: 22 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/utils/StageStatus.java` line 20 at r4](https://reviewable.io/reviews/harness/harness-core/35833#-N8O-zev9dohNe3bR_oT:-N8O6Y6_9iwx-IMYAnFl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e3c1dd92256978f125a91da1462ba6b69e67c34a/980-commons/src/main/java/io/harness/utils/StageStatus.java#L20)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What is unknown status here? Should not we have instead in progress status for rollback data just created?
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 21 files at r5, 1 of 12 files at r6, 13 of 17 files at r7, 2 of 3 files at r8, 2 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)* status: 1 change requests. 3. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 21 files at r5, 1 of 12 files at r6, 13 of 17 files at r7, 2 of 3 files at r8, 2 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35833)* status: :shipit: complete! ✓

**Pull request merged**
