### PR TITLE
fix: [CDS-40533]: correctly delete cache directories (in CG & NG) and working directories (in NG)

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35675)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger ft2

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 279 at r2](https://reviewable.io/reviews/harness/harness-core/35675#-N7nxqJc6OFGKaPUQm7o:-N7nxqJc6OFGKaPUQm7p:b-ikc2eq) ([raw file](https://github.com/harness/harness-core/blob/ebb3fa60f8870279223ea1722b123ec2d7ef8576/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L279)):*
> ```Java
>         deleteAndPurgeHelmRelease(commandRequest, logCallback);
>       }
>       int index = commandRequest.getWorkingDir().lastIndexOf('/');
> ```

nit: better to use ```Paths.get(commandRequest.getWorkingDir()).getParent().toString()```

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35675)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 279 at r2](https://reviewable.io/reviews/harness/harness-core/35675#-N7nxqJc6OFGKaPUQm7o:-N7o1n9x0U7bLJkURMYm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebb3fa60f8870279223ea1722b123ec2d7ef8576/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L279)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: better to use ```Paths.get(commandRequest.getWorkingDir()).getParent().toString()```
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35675)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by namantalaycha10 — APPROVED** [review]

**Pull request merged**
