### PR TITLE
fix: [CI-5977]: fixed issue with spaces in inputset

### PR DESCRIPTION
**Pull request by devkimittal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39637)

### CODE REVIEW

**Comment by devkimittal** [comment]
trigger messagecheck

**Comment by devkimittal** [comment]
In case of trigger execution, we were not trimming the inputyaml values. This small change will fix it.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39637)* status: :shipit: complete! ✓

**Comment by devkimittal** [comment]
Customer was passing some input as empty space and this input was being used as jexl condition evaluation. If the execution is being done manually, it was passing without an issue, but in case of a trigger with inputset it was failing.
The solution here is to trim the merged pipeline and input yaml as it is being done in manual execution.
Tested it using new git sync flow.

**Comment by raghavharness** [comment]
@devkimittal Can you do this for V0 version only. It'll break new simplified yaml. Add something like this.

```
 switch (pipelineEntity.getHarnessVersion()) {
        case PipelineVersion.V0:
          pipelineYaml = InputSetSanitizer.trimValues(pipelineYaml);
          break;
        default:
      }
```

**Pull request merged**
