### PR TITLE
feat:[CDS-81536]: Support for filter in overrides v2

### PR DESCRIPTION
**Pull request by sourabh-awashti**
## Describe your changes
Added the support for filters for overrides V2. We can provide Service Refs, Env Refs and Infra identifiers to get list of particular overrides.  Changes include addition of new filter dto class with changes in list api for overrides.
Tests Done :
1. Tested filter for Global env , service specific , svc-env , infra-svc overrides with list of only svc refs, svc-env refs , svc-infra refs.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54749)

### CODE REVIEW

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by lovish1999 — APPROVED** [review]
LGTM

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54749)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/OverrideFilterPropertiesDTO.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/54749#-Ni48TRPE5ZVKFfzMC2v:-Ni48TRPE5ZVKFfzMC2w:bbk988v) ([raw file](https://github.com/harness/harness-core/blob/1232cfdb9906a61ca10b06a960bbf4f9e5c46903/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/OverrideFilterPropertiesDTO.java#L36)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @ApiModel("OverrideFilterProperties")
> @JsonTypeName(OVERRIDE)
> ```

do we need JsonTypeName here ? If yes, the name is "override" which looks confusing since this is a filter object

**Comment by sourabh-awashti** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/OverrideFilterPropertiesDTO.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/54749#-Ni48TRPE5ZVKFfzMC2v:-Ni49yYm-vC_8dzb1hVr:bp4phme) ([raw file](https://github.com/harness/harness-core/blob/1232cfdb9906a61ca10b06a960bbf4f9e5c46903/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/OverrideFilterPropertiesDTO.java#L36)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need JsonTypeName here ? If yes, the name is "override" which looks confusing since this is a filter object
</blockquote></details>

yes it is required. It is being added to each filter property.
I will change the variable name here

**Comment by sourabh-awashti** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/OverrideFilterPropertiesDTO.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/54749#-Ni48TRPE5ZVKFfzMC2v:-Ni4BhX80PNktLxaYeVL:bk2pirl) ([raw file](https://github.com/harness/harness-core/blob/1232cfdb9906a61ca10b06a960bbf4f9e5c46903/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans/OverrideFilterPropertiesDTO.java#L36)):*
<details><summary><i>Previously, sourabh-awashti wrote…</i></summary><blockquote>

yes it is required. It is being added to each filter property.
I will change the variable name here
</blockquote></details>

done @yogesh-chauhan

**Comment by yogesh-chauhan** [comment]
*[`970-api-services-beans/src/main/java/io/harness/filter/FilterConstants.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/54749#-Ni4CiNH07nvXkhVQEDa:-Ni4CiNH07nvXkhVQEDb:b-f59stv) ([raw file](https://github.com/harness/harness-core/blob/82f8c104fbcc8feb159ed310f6fe14b2a9384d72/970-api-services-beans/src/main/java/io/harness/filter/FilterConstants.java#L31)):*
> ```Java
>   public static final String ENVIRONMENT = "Environment";
>   public static final String EXECUTION_FILTER = "RuleExecution";
>   public static final String OVERRIDE_FILTER = "Override";
> ```

the value is still "Override" Only

**Comment by sourabh-awashti** [comment]
*[`970-api-services-beans/src/main/java/io/harness/filter/FilterConstants.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/54749#-Ni4CiNH07nvXkhVQEDa:-Ni4ES7t1QV9PH1RjGSc:b-48afu5) ([raw file](https://github.com/harness/harness-core/blob/82f8c104fbcc8feb159ed310f6fe14b2a9384d72/970-api-services-beans/src/main/java/io/harness/filter/FilterConstants.java#L31)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

the value is still "Override" Only
</blockquote></details>

@yogesh-chauhan if you check for any other type of filter, they have also not provided any suffix for this value, its just entity name in value thats why i didn't change the value. Should we change the value as well here??

**Comment by sourabh-awashti** [comment]
*[`970-api-services-beans/src/main/java/io/harness/filter/FilterConstants.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/54749#-Ni4CiNH07nvXkhVQEDa:-Ni4IUMY6odfCNEjQxDD:b-onyd8g) ([raw file](https://github.com/harness/harness-core/blob/82f8c104fbcc8feb159ed310f6fe14b2a9384d72/970-api-services-beans/src/main/java/io/harness/filter/FilterConstants.java#L31)):*
<details><summary><i>Previously, sourabh-awashti wrote…</i></summary><blockquote>

@yogesh-chauhan if you check for any other type of filter, they have also not provided any suffix for this value, its just entity name in value thats why i didn't change the value. Should we change the value as well here??
</blockquote></details>

changes the value

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54749)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by lovish1999 — DISMISSED** [review]

**Review by yogesh-chauhan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54749)* status: 5 file(s) to review.

**Comment by sourabh-awashti** [comment]
trigger ut0, ut1, ut3, ut4, ut7

**Comment by sourabh-awashti** [comment]
trigger ut0, ut1

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54749)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by lovish1999 — APPROVED** [review]

**Pull request merged**
