### PR TITLE
feat: [PIE-3018]: GET env group api from env group identifier

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger authorcheck

**Review by namanvermah — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 103 at r1](https://reviewable.io/reviews/harness/harness-core/31296#-MxsPiteA59gT25bItFG:-MxsPiteA59gT25bItFH:b8t7b8s) ([raw file](https://github.com/harness/harness-core/blob/049b7fd2b49b52f66c89bc83377959727de317bc/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L103)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectIdentifier,
>       @Parameter(description = "Specify whether Environment is deleted or not") @QueryParam(
>           NGCommonEntityConstants.DELETED_KEY) @DefaultValue("false") boolean deleted) {
> ```

Add git query params. Just that much should be enough

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 103 at r1](https://reviewable.io/reviews/harness/harness-core/31296#-MxsPiteA59gT25bItFG:-MxsSmQK1K_cVRS_M85U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/049b7fd2b49b52f66c89bc83377959727de317bc/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L103)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Add git query params. Just that much should be enough
</blockquote></details>

Done.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296#-:-MxsTCJa4E7hQf_JtM5y:bnfp4nl)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)* status: 13 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 83 at r2](https://reviewable.io/reviews/harness/harness-core/31296#-MxsTMRn6K9BkYgFUy5O:-MxsTMRn6K9BkYgFUy5P:b-81301) ([raw file](https://github.com/harness/harness-core/blob/ca2b4af61edbd7110904f2e287da77e073425b48/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L83)):*
> ```Java
>     })
> @OwnedBy(HarnessTeam.PIPELINE)
> public class EnvironmentGroupResource {
> ```

unit test missing



_Code quote:_
```Java
EnvironmentGroupResource
```
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/31296#-MxsTJow08x-w7dLuN20:-MxsTJoxA5mze1zDtbDb:b-5v8fv4) ([raw file](https://github.com/harness/harness-core/blob/ca2b4af61edbd7110904f2e287da77e073425b48/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java#L23)):*
> ```Java
> @Singleton
> @Slf4j
> public class EnvironmentGroupServiceImpl implements EnvironmentGroupService {
> ```

Unit tests missing



_Code quote:_
```Java
EnvironmentGroupServiceImpl
```
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/31296#-MxsTGmr0bYZXqwZMnBT:-MxsTGmr0bYZXqwZMnBU:b-9sovl5) ([raw file](https://github.com/harness/harness-core/blob/ca2b4af61edbd7110904f2e287da77e073425b48/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L24)):*
> ```Java
> @AllArgsConstructor(access = AccessLevel.PRIVATE, onConstructor = @__({ @Inject }))
> @Slf4j
> public class EnvironmentGroupRepositoryCustomImpl implements EnvironmentGroupRepositoryCustom {
> ```

Please add unit tests for the same



_Code quote:_
```Java
EnvironmentGroupRepositoryCustomImpl
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)* status: 16 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 83 at r2](https://reviewable.io/reviews/harness/harness-core/31296#-MxsTMRn6K9BkYgFUy5O:-MxsrOEv0Ov6sQ9iSlms:b-u1ro7p) ([raw file](https://github.com/harness/harness-core/blob/ca2b4af61edbd7110904f2e287da77e073425b48/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L83)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

unit test missing
</blockquote></details>

Will be adding with the next api
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/31296#-MxsTJow08x-w7dLuN20:-MxsrJayEFadvn7yKHDn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ca2b4af61edbd7110904f2e287da77e073425b48/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Unit tests missing
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/31296#-MxsTGmr0bYZXqwZMnBT:-MxsrKHP06gSny88nhpE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ca2b4af61edbd7110904f2e287da77e073425b48/125-cd-nextgen/src/main/java/io/harness/repositories/envGroup/EnvironmentGroupRepositoryCustomImpl.java#L24)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please add unit tests for the same
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31296#-:-MyB-sco0PcvQQsCk-bc:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
