### PR TITLE
[feat]: [CDS-36017]: Add WinRm credentials in NG

### PR DESCRIPTION
**Pull request by vitsafronovici**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger ti0

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/32143#-N00zTRnEcRU51leNkT1:-N00zTRnEcRU51leNkT2:bm72b2f) (no related file):*
one minor thing, we need to specify the owner as CDP for newly added classes since it's our team that will support WinRmCredentials secrets.
Also, please add UT for `WinRmConfigValidationDelegateTask` and `WinRmCredentialsSpecDTOHelper`

---
___
*[930-delegate-tasks/src/main/java/io/harness/cdng/secrets/tasks/WinRmConfigValidationDelegateTask.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32143#-N01-Ln-7f2JekIcOuTH:-N01-Ln-7f2JekIcOuTI:b-rtf7mn) ([raw file](https://github.com/harness/harness-core/blob/219a763d323f0ff212d3135a3d069eb9300a8188/930-delegate-tasks/src/main/java/io/harness/cdng/secrets/tasks/WinRmConfigValidationDelegateTask.java#L67)):*
> ```Java
>                                             .port(winRmCredentialsSpecDTO.getPort())
>                                             .environment(Collections.EMPTY_MAP)
>                                             .timeout(1800000);
> ```

this is 30 min, shall we make it less?

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/cdng/secrets/tasks/WinRmConfigValidationDelegateTask.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32143#-N01-Ln-7f2JekIcOuTH:-N01F6KJ3UuwPIBVy6-a:b-e31f2t) ([raw file](https://github.com/harness/harness-core/blob/219a763d323f0ff212d3135a3d069eb9300a8188/930-delegate-tasks/src/main/java/io/harness/cdng/secrets/tasks/WinRmConfigValidationDelegateTask.java#L67)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

this is 30 min, shall we make it less?
</blockquote></details>

This is how it works in CG. Seems it it so much in order to reuse sessions. At manager side 45 seconds is set for execution timeout

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/32143#-N00zTRnEcRU51leNkT1:-N01FTB29KzwtRdSxiKp:b-896fix) (no related file):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

one minor thing, we need to specify the owner as CDP for newly added classes since it's our team that will support WinRmCredentials secrets.
Also, please add UT for `WinRmConfigValidationDelegateTask` and `WinRmCredentialsSpecDTOHelper`
</blockquote></details>

Done.

---

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: 1. unresolved discussions.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: 21 file(s) to review. 22. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/WinRmCredentialsValidationMetadata.java, line 20 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01GjF44-8FU9FseS1m:-N01TTJs8dksy092l1Lm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/120-ng-manager/src/main/java/io/harness/ng/core/remote/WinRmCredentialsValidationMetadata.java#L20)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

CDP
</blockquote></details>

Done.
___
*[940-secret-manager-client/src/main/java/io/harness/delegate/beans/WinRmTaskParams.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01GpU98tFmI0uiocoE:-N01TU4tE1AVv2KEpTTN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/940-secret-manager-client/src/main/java/io/harness/delegate/beans/WinRmTaskParams.java#L24)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owendby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/secrets/BaseConfigValidationTaskResponse.java, line 19 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01GtGY1Oz7AghdWSZo:-N01TVJu4QRavOOywldv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/secrets/BaseConfigValidationTaskResponse.java#L19)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/secrets/WinRmConfigValidationTaskResponse.java, line 13 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01H2qd8rVZ5-Ob4SE2:-N01TWM6EEJvLo_eWD58:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/secrets/WinRmConfigValidationTaskResponse.java#L13)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/BaseWinRmSpecDTO.java, line 24 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01Jx-oAWwDznol9mVH:-N01TX0e1pjZhVfi7ztL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/BaseWinRmSpecDTO.java#L24)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/KerberosBaseConfigDTO.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01JycP7dLhmTDpS0nT:-N01TXrU85nhRcZdEnPW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/KerberosBaseConfigDTO.java#L23)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/KerberosConfigDTO.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01K0r426UDWKiDo1Dy:-N01TY_aE4rxQCTnix7M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/KerberosConfigDTO.java#L30)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/KerberosWinRmConfigDTO.java, line 31 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01K43w4NNaCpRz92h5:-N01TZFp3yhEv4klgcVY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/KerberosWinRmConfigDTO.java#L31)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedbty
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/NTLMConfigDTO.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01K6Cd70O_Q5Uywg2x:-N01T_-B7r9n-zOrp4SC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/NTLMConfigDTO.java#L30)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/SSHConfigDTO.java, line 28 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KDhU7URzXdECXDlX:-N01T_kv-VbyYKjFxWSG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/SSHConfigDTO.java#L28)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/WinRmAuthDTO.java, line 25 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KFN51KO0F_5y23CR:-N01Ta_vAcZqCDIuEGRQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/WinRmAuthDTO.java#L25)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/WinRmCredentialsSpecDTO.java, line 30 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KHaH7HcpvQ1DdI6L:-N01TbMb-8V16burn-jN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/dto/secrets/WinRmCredentialsSpecDTO.java#L30)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/BaseSSHSpec.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KKihE7t-ukPBRGA4:-N01Tc4D5GiJvQxsaVny:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/BaseSSHSpec.java#L16)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/BaseWinRmSpec.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KMRfDqO_-9Kp7C37:-N01TcfW0cbx0duekvvU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/BaseWinRmSpec.java#L16)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/KerberosBaseConfig.java, line 20 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KO1S7B1AkV-cIjCi:-N01TdIr2OwH2uk-UDa-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/KerberosBaseConfig.java#L20)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/KerberosWinRmConfig.java, line 25 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KRVFAHTF1qfqZCmA:-N01Te2HCbc615jdzGKr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/KerberosWinRmConfig.java#L25)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/NTLMConfig.java, line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KTD371P5lazHOVp0:-N01TehPEYpXtDE6tOO-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/NTLMConfig.java#L21)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/SSHConfig.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KV1q6k7NIiu_jh7u:-N01TfPt7huLMyzjwpFJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/SSHConfig.java#L23)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/WinRmAuth.java, line 21 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KX779E9A6UedODNi:-N01TgBMCF4lW4sPKGBN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/WinRmAuth.java#L21)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/WinRmCredentialsSpec.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01KYMSErRnk60tjhYG:-N01Tgr--mdY3rLH4xq3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/WinRmCredentialsSpec.java#L23)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.
___
*[950-delegate-tasks-beans/src/main/java/io/harness/secretmanagerclient/WinRmAuthScheme.java, line 10 at r2](https://reviewable.io/reviews/harness/harness-core/32143#-N01K_M93Gpa1-ulC29O:-N01Thy81KQYHTCaA-_o:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e6d02197b7a94a728006ad4ef28c2beeb6f33f09/950-delegate-tasks-beans/src/main/java/io/harness/secretmanagerclient/WinRmAuthScheme.java#L10)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

ownedby
</blockquote></details>

Done.

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 12 of 39 files at r1, 4 of 6 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: 22. unresolved discussions.

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: 22. unresolved discussions.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 12 of 39 files at r1, 4 of 6 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

**Review by vitsafronovici — COMMENTED** [review]
> Reviewed 12 of 39 files at r1, 4 of 6 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32143)* status: :shipit: complete! ✓

**Pull request merged**
