### PR TITLE
feat: [CDS-37891]: Service Overrides entity and CRUD

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
1. Create a new entity for Service Overrides
2. Added an upsert API with sample body below
`{
  "orgIdentifier": "default",
  "projectIdentifier": "neo",
  "environmentRef": "qa",
  "serviceRef": "k8sservice",
  "variableOverrides": [
    {
      "name": "memory",
      "type": "String",  
      "value": "8"
    },
    {
      "name": "cpu",
      "type": "String",  
      "value": "1"
    }
  ]
}`

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 8 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 498 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30ZvylBf6ZBNXqxmxC:-N30ZvylBf6ZBNXqxmxD:b-8mcxho) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L498)):*
> ```Java
>     if (dto == null) {
>       throw new InvalidRequestException(
>           "No request body sent in the API. Following fields are required: name, orgIdentifier, projectIdentifier, environmentRef, serviceRef");
> ```

why are we saying "Following fields are required: name, orgIdentifier, projectIdentifier, environmentRef, serviceRef" ?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideRequestDTO.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30_NW_2XDSaGtHBHNi:-N30_NW_2XDSaGtHBHNj:b-vjb9kk) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideRequestDTO.java#L35)):*
> ```Java
> @JsonInclude(NON_NULL)
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(name = "ServiceOverrideRequest", description = "This is the Service Override entity defined in Harness")
> ```

ServiceOverrideRequestDTO



_Suggestion:_
```Java
this is the Service Override entity defined in Harness
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideResponseDTO.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30_VhV8A8SicIZQplI:-N30_VhV8A8SicIZQplJ:bsceule) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideResponseDTO.java#L24)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Schema(name = "ServiceOverrideResponse", description = "This is the Service Override entity defined in Harness")
> ```

ServiceOverrideResponseDTO



_Suggestion:_
```Java
this is the Service Override entity defined in Harness"
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30_cEoBzlG-JArFbuK:-N30_cEoBzlG-JArFbuL:b-t30fj4) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L218)):*
> ```Java
>     update.set(NGServiceOverridesEntityKeys.serviceRef, serviceOverridesEntity.getServiceRef());
>     update.set(NGServiceOverridesEntityKeys.variableOverrides, serviceOverridesEntity.getVariableOverrides());
>     update.setOnInsert(NGServiceOverridesEntityKeys.createdAt, System.currentTimeMillis());
> ```

createdAt should not change

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 498 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30ZvylBf6ZBNXqxmxC:-N32giJp4msSWj2w1AqV:bebrt1w) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L498)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why are we saying "Following fields are required: name, orgIdentifier, projectIdentifier, environmentRef, serviceRef" ?
</blockquote></details>

Will do
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java` line 218 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30_cEoBzlG-JArFbuK:-N32gQqB0HEzIfrqb0Nk:b-jl8ay8) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentFilterHelper.java#L218)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

createdAt should not change
</blockquote></details>

setOnInsert only updates values if the update operation results in insert of a document

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 11 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideRequestDTO.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30_NW_2XDSaGtHBHNi:-N33Aj5W8v-L_w9J0Fxd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideRequestDTO.java#L35)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

ServiceOverrideRequestDTO
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideResponseDTO.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/33586#-N30_VhV8A8SicIZQplI:-N33AjhKERItSRX0zYPB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/408ca456fa35e29dfa6ef777df54f48f4cf2f698/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideResponseDTO.java#L24)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

ServiceOverrideResponseDTO
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 11 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/33586#-N33AkZA7X2v6vfEMm1R:-N33AkZA7X2v6vfEMm1S:bma76xy) ([raw file](https://github.com/harness/harness-core/blob/1617eb82996444e6a5c063579981140474eb1401/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java#L48)):*
> ```Java
> @StoreIn(DbAliases.NG_MANAGER)
> @OwnedBy(CDC)
> public class NGServiceOverridesEntity implements PersistentEntity {
> ```

@yogesh-chauhan are we creating new entity for just overrides?



_Code quote:_
```Java
NGServiceOverridesEntity
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/33586#-N33AkZA7X2v6vfEMm1R:-N33D2-pE2XqzVfuEvML:b7klivp) ([raw file](https://github.com/harness/harness-core/blob/1617eb82996444e6a5c063579981140474eb1401/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@yogesh-chauhan are we creating new entity for just overrides?
</blockquote></details>

Yes Archit. This will be similar to infra entity i.e have an envRef as identifier

**Comment by hingerabhinav** [comment]
@yogesh-chauhan added environment update RBAC in this PR. Will add validation for service and its RBAC in separate PR.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/33586#-N33AkZA7X2v6vfEMm1R:-N33_MM_4nQKba_ImIvC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1617eb82996444e6a5c063579981140474eb1401/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java#L48)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Yes Archit. This will be similar to infra entity i.e have an envRef as identifier
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1, 3 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33fSkGC5156WpRs3Fb:-N33fSkGC5156WpRs3Fc:b-xuluua) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java#L71)):*
> ```Java
>   @NotNull @Trimmed String environmentRef;
> 
>   List<NGVariable> variableOverrides;
> ```

@yogesh-chauhan should we not have serviceOverrides identifier, or lets decide how its yaml should look like?



_Code quote:_
```Java
  @Wither @Id @org.mongodb.morphia.annotations.Id String id;
  @Trimmed @NotEmpty String accountId;

  @NotNull @Trimmed String orgIdentifier;
  @NotNull @Trimmed String projectIdentifier;
  @NotNull @Trimmed String serviceRef;
  @NotNull @Trimmed String environmentRef;

  List<NGVariable> variableOverrides;
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideRequestDTO.java` line 41 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33e9WH3DOlyb65dUp1:-N33e9WH3DOlyb65dUp2:b-v4jdb0) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideRequestDTO.java#L41)):*
> ```Java
>   @Schema(description = NGCommonEntityConstants.ENV_PARAM_MESSAGE) String environmentRef;
>   @Schema(description = NGCommonEntityConstants.SERVICE_PARAM_MESSAGE) String serviceRef;
>   @Schema(description = NGCommonEntityConstants.VARIABLE_OVERRIDE_PARAM_MESSAGE) List<NGVariable> variableOverrides;
> ```

Shouldnt we take yaml? follow same approach @yogesh-chauhan 



_Code quote:_
```Java
@Schema(description = NGCommonEntityConstants.VARIABLE_OVERRIDE_PARAM_MESSAGE) List<NGVariable> variableOverrides
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideResponseDTO.java` line 32 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33eERD34nobR_5HymY:-N33eERD34nobR_5HymZ:b-x18tgk) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/ServiceOverrideResponseDTO.java#L32)):*
> ```Java
>   String environmentRef;
>   String serviceRef;
>   List<NGVariable> variableOverrides;
> ```

Same we should return yaml as well?



_Code quote:_
```Java
  String accountId;
  String orgIdentifier;
  String projectIdentifier;
  String environmentRef;
  String serviceRef;
  List<NGVariable> variableOverrides;
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/ServiceOverridesMapper.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33eQiD0fpfCz0oDLLy:-N33eQiD0fpfCz0oDLLz:b-8do8yg) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/ServiceOverridesMapper.java#L35)):*
> ```Java
>         .variableOverrides(serviceOverridesEntity.getVariableOverrides())
>         .build();
>   }
> ```

i think yaml both in dto, and entity should be there



_Code quote:_
```Java
  public NGServiceOverridesEntity toServiceOverridesEntity(
      String accountId, ServiceOverrideRequestDTO serviceOverrideRequestDTO) {
    return NGServiceOverridesEntity.builder()
        .accountId(accountId)
        .orgIdentifier(serviceOverrideRequestDTO.getOrgIdentifier())
        .projectIdentifier(serviceOverrideRequestDTO.getProjectIdentifier())
        .environmentRef(serviceOverrideRequestDTO.getEnvironmentRef())
        .serviceRef(serviceOverrideRequestDTO.getServiceRef())
        .variableOverrides(serviceOverrideRequestDTO.getVariableOverrides())
        .build();
  }

  public ServiceOverrideResponseDTO toResponseWrapper(NGServiceOverridesEntity serviceOverridesEntity) {
    return ServiceOverrideResponseDTO.builder()
        .accountId(serviceOverridesEntity.getAccountId())
        .orgIdentifier(serviceOverridesEntity.getOrgIdentifier())
        .projectIdentifier(serviceOverridesEntity.getProjectIdentifier())
        .environmentRef(serviceOverridesEntity.getEnvironmentRef())
        .serviceRef(serviceOverridesEntity.getServiceRef())
        .variableOverrides(serviceOverridesEntity.getVariableOverrides())
        .build();
  }
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/ServiceOverrideService.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33eVMyE2HjpvuH8N3i:-N33eVMyE2HjpvuH8N3j:bt05hk9) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/ServiceOverrideService.java#L17)):*
> ```Java
> import org.springframework.data.mongodb.core.query.Criteria;
> 
> public interface ServiceOverrideService {
> ```

shoud we not have delete api as well?



_Code quote:_
```Java
  Page<NGServiceOverridesEntity> list(Criteria criteria, Pageable pageable);
}
```

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33fSkGC5156WpRs3Fb:-N33u4LuDm0I7iHRef4k:b-px5weg) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java#L71)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@yogesh-chauhan should we not have serviceOverrides identifier, or lets decide how its yaml should look like?
</blockquote></details>

for a given orgid, projectid, envId and serviceId, there will be unique service override entity
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/ServiceOverrideService.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33eVMyE2HjpvuH8N3i:-N33uI6rAcVciBbD9pHG:b-6kv3bk) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/ServiceOverrideService.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shoud we not have delete api as well?
</blockquote></details>

deleting a single override can be accomplised by upsert API as well since we're storing a list of overrides in 1 entity. 
Was waiting for some UX clarity for an API to delete entire service override entity.

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java` line 71 at r3](https://reviewable.io/reviews/harness/harness-core/33586#-N33fSkGC5156WpRs3Fb:-N3DTVr7DJzmiJipdKE3:b-g26vt9) ([raw file](https://github.com/harness/harness-core/blob/4c46d23adaf9f980bf51a55a29034cf3e12b70ad/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGServiceOverridesEntity.java#L71)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

for a given orgid, projectid, envId and serviceId, there will be unique service override entity
</blockquote></details>

Yes, we do not have serviceOverridesIdentifier

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 1 change requests. 2. unresolved discussions.

**Review by prashantsharma04 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/yaml/NGServiceOverrideInfoConfig.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/33586#-N3SyS2W3h9LtZe2Ty9a:-N3SyS2W3h9LtZe2Ty9b:b-gshrw8) ([raw file](https://github.com/harness/harness-core/blob/ec78368e39351dc1897d7f97115f9313e1619eff/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/yaml/NGServiceOverrideInfoConfig.java#L43)):*
> ```Java
>   String uuid;
> 
>   String orgIdentifier;
> ```

confirm with @archit-harness if orgIdentifier and projectIdentifier are required in config file

**Review by archit-harness — APPROVED** [review]
> Reviewed 17 of 19 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 1. unresolved discussions. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/yaml/NGServiceOverrideInfoConfig.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/33586#-N3SyS2W3h9LtZe2Ty9a:-N3TgYWH1z95ABDDvVDH:b-c8bn8v) ([raw file](https://github.com/harness/harness-core/blob/ec78368e39351dc1897d7f97115f9313e1619eff/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/yaml/NGServiceOverrideInfoConfig.java#L43)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Got it
</blockquote></details>

@hingerabhinav we should remove org / project identifier.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 520 at r5](https://reviewable.io/reviews/harness/harness-core/33586#-N3VF-Wo-zeZNaTHHbb6:-N3XwpJHAsGYVY-pIcD3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ec78368e39351dc1897d7f97115f9313e1619eff/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L520)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use one API call. Below one would be better
```
AccessCheckResponseDTO checkForAccess(List<PermissionCheckDTO> permissionCheckDTOList);
```
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/yaml/NGServiceOverrideInfoConfig.java` line 43 at r5](https://reviewable.io/reviews/harness/harness-core/33586#-N3SyS2W3h9LtZe2Ty9a:-N3XwqXWAICWRePNSBsH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ec78368e39351dc1897d7f97115f9313e1619eff/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/yaml/NGServiceOverrideInfoConfig.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@hingerabhinav we should remove org / project identifier.
</blockquote></details>

Done.

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 15 of 19 files at r4, 2 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33586)* status: 1 change requests. 2. unresolved discussions.

**Pull request merged**
