### PR TITLE
techdebt: [CDS-41162]: k8s client java library upgrade to 16.0.0

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
With these changes we are upgrading the **Kubernetes Java Client** Library from version `13.0.1` to `16.0.0`
also as **Snakeyaml** library version `1.26` is not compatible with k8s java client version `16.0.0` so we are also upgrading snakeyaml library version to `1.28`

we replaced withNewToken to withToken as in version 13.0.1 it was internally calling this method and now withNewToken is removed 
image (4)

[Kubernetes Java Client Github Link](https://github.com/kubernetes-client/java/tree/release-16)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36018)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
changes are still in Progress

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36018)

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
@namantalaycha10 get git sync git to harness flow tested once

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 12 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36018)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36018)* status: :shipit: complete! ✓

**Review by shubham-in10se — DISMISSED** [review]
> Reviewed 12 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36018)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
@abhinav-harness tested git sync is working fine

**Comment by namantalaycha10** [comment]
trigger ti1

**Comment by namantalaycha10** [comment]
trigger compile

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36018)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 12 of 17 files at r1, 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36018)* status: :shipit: complete! ✓

**Pull request merged**
