### PR TITLE
[feat]: [PL-28502]: restrict login audits to only 1 account which user logins into + improved audit logs

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your 
restrict login audits to only 1 account which user logins into + improved audit logs

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38420)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38420)

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/38420#-NDdfm6Q-tjCirjVDNMq:-NDdfm6R770EZV8y6Jga:b-mpf5qf) ([raw file](https://github.com/harness/harness-core/blob/c4b495c53df89fd7163fef6a424f57fccbf13025/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L152)):*
> ```Java
> 
>     if (account == null) {
>       throw new IllegalStateException(
> ```

Shouldn't this be unexpectedException?

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 127 at r1](https://reviewable.io/reviews/harness/harness-core/38420#-NDdg-0-0I3aoqPPnaTC:-NDdg-0-0I3aoqPPnaTD:bc6d42m) ([raw file](https://github.com/harness/harness-core/blob/c4b495c53df89fd7163fef6a424f57fccbf13025/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L127)):*
> ```Java
>   }
> 
>   private Account getAccount(User user, String accountId) {
> ```

If possible, lets add a more meaningful descriptive method name

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/38420#-NDdgC8vDklEbIy5VFPu:-NDdgC8vDklEbIy5VFPv:bic89ou) ([raw file](https://github.com/harness/harness-core/blob/c4b495c53df89fd7163fef6a424f57fccbf13025/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L157)):*
> ```Java
>     }
>     if (account.getAuthenticationMechanism() == null) {
>       account.setAuthenticationMechanism(io.harness.ng.core.account.AuthenticationMechanism.USER_PASSWORD);
> ```

can we fix this import here?

**Review by pbarapatre10 — DISMISSED** [review]
:lgtm: 
Please once verify with audits in CG

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38420#-:-NDfxXYZBkxLHpj511dJ:bni5isu)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38420)* status: 10 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 127 at r1](https://reviewable.io/reviews/harness/harness-core/38420#-NDdg-0-0I3aoqPPnaTC:-NDh-6ki9RMnPb_R2kBx:b-uulbgt) ([raw file](https://github.com/harness/harness-core/blob/c4b495c53df89fd7163fef6a424f57fccbf13025/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L127)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If possible, lets add a more meaningful descriptive method name
</blockquote></details>

I think this name is fine
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/38420#-NDdfm6Q-tjCirjVDNMq:-NDh0wem7HAphLgjpHza:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c4b495c53df89fd7163fef6a424f57fccbf13025/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L152)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't this be unexpectedException?
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/38420#-NDdgC8vDklEbIy5VFPu:-NDh0w1E4nO4RiQvRZMm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c4b495c53df89fd7163fef6a424f57fccbf13025/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L157)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we fix this import here?
</blockquote></details>

done

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38420)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38420)* status: :shipit: complete! ✓

**Pull request merged**
