### PR TITLE
fix: [PIE-3919]: Better error handling when dashboard data gen fails in pipeline execution history

### PR DESCRIPTION
**Pull request by shalini-agr**
Changed the error message:

Screenshot 2022-06-15 at 3 48 07 PM

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34114)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34114)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/34114#-N41rDv40kI31dXaA5EM:-N41rDv40kI31dXaA5EN:byt8wwf) ([raw file](https://github.com/harness/harness-core/blob/3d6e5426cd23e80af026b3270426eb143baa6130/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L63)):*
> ```Java
>     } catch (Exception ex) {
>       log.error("Unable to fetch Dashboard data for executions", ex);
>       throw new InvalidRequestException("Unable to fetch Dashboard data for executions");
> ```

we don't need to log and throw.

We can simply pass ex as a parameter in Exception. The framework will take care of logging it. Please verify this once

**Comment by shalini-agr** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/34114#-N41rDv40kI31dXaA5EM:-N41x71D8rnBJD5f3fi_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3d6e5426cd23e80af026b3270426eb143baa6130/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L63)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

we don't need to log and throw.

We can simply pass ex as a parameter in Exception. The framework will take care of logging it. Please verify this once
</blockquote></details>

Done.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34114)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34114)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34114)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/34114#-N4ahShUDQQa23XLiX2L:-N4ahShUDQQa23XLiX2M:b-od7ozk) ([raw file](https://github.com/harness/harness-core/blob/1f8dad28d9c97bac126b01b44e47ca2e52a61886/800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L30)):*
> ```Java
>   private String CD_TableName = "pipeline_execution_summary_cd";
> 
>   public boolean isConnectionError(DataAccessException ex) {
> ```

nit, we can put this in some commons

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34114)* status: :shipit: complete! ✓

**Pull request merged**
