### PR TITLE
feat: [CDS-37248]: add support for yaml diff, refresh and validate api for pipeline

### PR DESCRIPTION
**Pull request by inderschera**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java` line 87 at r3](https://reviewable.io/reviews/harness/harness-core/33266#-N2L5N534OB2AOK2Ffk3:-N2L5N534OB2AOK2Ffk4:brq6782) ([raw file](https://github.com/harness/harness-core/blob/9810e1645a8580a1e328bb4294f849401b0d54af/800-pipeline-service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java#L87)):*
> ```Java
>     }
>     return optionalPipelineEntity.get();
>   }
> ```

this method should exists already somewhere



_Code quote:_
```Java
  private PipelineEntity getPipelineEntity(
      String accountId, String orgId, String projectId, String pipelineIdentifier) {
    Optional<PipelineEntity> optionalPipelineEntity =
        pmsPipelineService.get(accountId, orgId, projectId, pipelineIdentifier, false);
    if (!optionalPipelineEntity.isPresent()) {
      throw new InvalidRequestException(
          String.format("Pipeline with the given id: %s does not exist or has been deleted", pipelineIdentifier));
    }
    return optionalPipelineEntity.get();
  }
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/33266#-N2LJev82H1YqwBsJX_J:-N2LJev82H1YqwBsJX_K:b-kla2rk) ([raw file](https://github.com/harness/harness-core/blob/dc02a5c4634110e0abce49137f6a72505bd7d345/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L69)):*
> ```Java
> 
>     // Returning the Refreshed YAML corresponding to the ResMap
>     return YamlUtils.write(refreshedTemplateInputsMap).replace("---\n", "");
> ```

yamlpipeline utils me this method exists



_Code quote:_
```Java
YamlUtils.write(refreshedTemplateInputsMap).replace("---\n", "");
```

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/33266#-N2LJev82H1YqwBsJX_J:-N2LUO_65iSWnQQO3VwG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dc02a5c4634110e0abce49137f6a72505bd7d345/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

yamlpipeline utils me this method exists
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)* status: 1. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266)* status: :shipit: complete! ✓

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 4 of 9 files at r1, 4 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33266#-:-N2LsnYFEgZw23nO6o-q:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
