### PR TITLE
feat: [PL-23731]: Added support for skip validation for connectivity status…

### PR DESCRIPTION
**Pull request by tiwaritejas**
Add skip validation option for Custom SM

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerServiceImpl.java` line 145 at r4](https://reviewable.io/reviews/harness/harness-core/32654#-N1CVobI914E7Qe54fiy:-N1CVobI914E7Qe54fiz:b79yfxu) ([raw file](https://github.com/harness/harness-core/blob/165983f1a1320a1e75d394ff98e3f5109d2f296c/400-rest/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerServiceImpl.java#L145)):*
> ```Java
>     }
>     setCommandPathInConfig(secretsManagerConfig);
>     validateInternal(secretsManagerConfig, testVariables, secretsManagerConfig.isSkipValidation());
> ```

Third argument is not required. secretsManagerConfig is passed as the first argument which can be used the get the value of skipValidation.



_Code quote:_
```Java
secretsManagerConfig.isSkipValidation()
```
___
*[`400-rest/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerServiceImpl.java` line 190 at r4](https://reviewable.io/reviews/harness/harness-core/32654#-N1CW3m_-y847I26mKzG:-N1CW3m_-y847I26mKzH:b-8yw7yd) ([raw file](https://github.com/harness/harness-core/blob/165983f1a1320a1e75d394ff98e3f5109d2f296c/400-rest/src/main/java/software/wings/service/impl/security/customsecretsmanager/CustomSecretsManagerServiceImpl.java#L190)):*
> ```Java
>   @VisibleForTesting
>   public void validateInternal(
>       CustomSecretsManagerConfig secretsManagerConfig, Set<EncryptedDataParams> testVariables, boolean skipValidation) {
> ```

additional argument is not required.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r4, 1 of 1 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)* status: 1 file(s) to review.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32654)* status: :shipit: complete! ✓

**Pull request merged**
