### PR TITLE
[feat]: [CDS-73947]: Added regex to ignore trimming of quotes for strings having values with numbers and underscores.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: We had an exercise a month ago to remove quotation marks from the value field for string type variables in mergedPipelineYaml. This was done to ensure that we don’t have unnecessary yaml diff in audit events. Now the use-case is: If that for a string which has only numbers and underscores, BE is sending the same string in mergedPipelineYaml response but without quotation marks ( ““ ). And js-yaml used by UI, consider the value without ““ as a number and hence removes underscores from it.

Changes: Have added another regex which includes strings having numbers and underscores. Any value of a string having that regex pattern will be returned with quotes around it and hence UI will then consider it as a string not number.

Impact: All the strings in yaml having only numbers and underscores in it.

Testing: Created a variable with value: 123_321 and BE returned it as "123_321" and UI treated as string not number and underscores were not trimmed thereafter.
Also tested with:
"123_"
"_12321"

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51299)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck, uts

**Comment by senjucanon2** [comment]
trigger messagecheck

**Review by shalini-agr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51299)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/51299#-NaufMBo6M5LVSJ2Ic-Z:-NaufMBo6M5LVSJ2Ic-_:b-ipi8xn) ([raw file](https://github.com/harness/harness-core/blob/03414f71372bff5a60d5d51033a5744074691962/970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java#L38)):*
> ```Java
>   // When string is of type 123_321, it also needs to be wrapped around quotes, else, it'll be considered a number and
>   // user will be able to save that value but, upon reloading UI will remove underscores from it.
>   private Pattern numbersWithUnderscoresRegex = Pattern.compile("^[0-9_]*$");
> ```

we only need the pattern matching number_number, right?
If so, modify the regex accordingly. This regex will also match strings like _1, 1, _, etc, which we don't need to handle.
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/51299#-NaufEXK6mE_bSMQUqSX:-NaufEXK6mE_bSMQUqSY:b92oj1w) ([raw file](https://github.com/harness/harness-core/blob/03414f71372bff5a60d5d51033a5744074691962/970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java#L47)):*
> ```Java
>     if (value != null) {
>       if (shaRegex.matcher(value).matches() || positiveNumberRegex.matcher(value).matches()
>           || numbersWithUnderscoresRegex.matcher(value).matches()) {
> ```

can you add UTs for this in YamlUtilsTest?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51299)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/51299#-NaufMBo6M5LVSJ2Ic-Z:-NayjcMZ200jgIYJrT5M:b7lpbbh) ([raw file](https://github.com/harness/harness-core/blob/03414f71372bff5a60d5d51033a5744074691962/970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java#L38)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

we only need the pattern matching number_number, right?
If so, modify the regex accordingly. This regex will also match strings like _1, 1, _, etc, which we don't need to handle.
</blockquote></details>

Have Improvised The regex.
___
*[`970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/51299#-NaufEXK6mE_bSMQUqSX:-NayjfEe6Jz8VzrnedCI:b-1rs7j6) ([raw file](https://github.com/harness/harness-core/blob/03414f71372bff5a60d5d51033a5744074691962/970-ng-commons/src/main/java/io/serializer/jackson/EdgeCaseRegexStringSerializer.java#L47)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

can you add UTs for this in YamlUtilsTest?
</blockquote></details>

Added a UT in YamlUtilsTest

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51299)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51299)* status: 2 file(s) to review.

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
