### PR TITLE
[feat]: [CVS-9138]: added FF for disabling UI changes for new verify step

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30780)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30780)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, line 221 at r1](https://reviewable.io/reviews/harness/harness-core/30780#-MvxHP4Q9DTFn5Afew-O:-MvxHP4Q9DTFn5Afew-P:b-rymd61) ([raw file](https://github.com/harness/harness-core/blob/8e3b9b99f9aa01d01054c9a1b3b7cf0282723fa7/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L221)):*
> ```Java
>   CVNG_VERIFY_STEP_DEMO,
>   CVNG_MONITORED_SERVICE_DEMO,
>   CVNG_VERIFY_STEP_UI_DISABLED,
> ```

We should name it specific to logs 
maybe something like: CVNG_VERIFY_STEP_LOGS_V2

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30780)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, line 221 at r1](https://reviewable.io/reviews/harness/harness-core/30780#-MvxHP4Q9DTFn5Afew-O:-MvxI3TgE2yvU89JRSt-:b-nv9eht) ([raw file](https://github.com/harness/harness-core/blob/8e3b9b99f9aa01d01054c9a1b3b7cf0282723fa7/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L221)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We should name it specific to logs 
maybe something like: CVNG_VERIFY_STEP_LOGS_V2
</blockquote></details>

ok, how about CVNG_VERIFY_STEP_LOGS_UI_DISABLED

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30780)* status: :shipit: complete! ✓

**Pull request merged**
