### PR TITLE
feat: [PL-23778]: supporting principal scope in role assignment apis

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31848)

### CODE REVIEW

**Comment by karansiwach360** [comment]
trigger messagecheck

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 7 of 13 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31848#-:-N-wCjIYCrW214cvY0Dw:bnfp4nl)* status: Some of the checks are too old. 26 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 5 of 13 files at r1, 14 of 19 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31848)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 5 of 13 files at r1, 14 of 19 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31848)* status: :shipit: complete! ✓

**Pull request merged**
