### PR TITLE
fix: [CDS-46983]: adding ConnectionShutdownException to retry class

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
Adding ConnectionShutdownException for retry
## Tests run
Socket Exception:-
Screenshot 2022-11-25 at 1 16 30 PM
Screenshot 2022-11-25 at 1 16 43 PM
ConnectionTimeoutException (Required Case):-
Screenshot 2022-11-25 at 1 19 41 PM
Screenshot 2022-11-25 at 1 21 04 PM
ApiException without subtype case:-
Screenshot 2022-11-25 at 2 29 16 PM
Screenshot 2022-11-25 at 1 38 48 PM
Added StreamResetException
Screenshot 2022-11-29 at 1 16 20 PM
Screenshot 2022-11-29 at 1 18 24 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)

### CODE REVIEW

**Comment by TarunUba1** [comment]
trigger messagecheck

**Review by vikyathharekal — COMMENTED** [review]
So we don't have to iterator over the child throwables because indexOfType() does that for us?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597#-:-NHgbWsmAq0nn4Ihr_Xg:b5oa7qq)* status: 0 of 1 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40597#-NHgbp9sBU5PyScD_YmH:-NHgbp9sBU5PyScD_YmI:bjpu3yp) (no related file):*
Also, could you add what you have tested? A screenshot, log message, or even a 1 liner explaining it would be helpful.

___

**Review by TarunUba1 — COMMENTED** [review]
Yes, like type of ApiException is what we check there

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597#-:-NHjJ39O8TfRyRYZ6kvy:b-bw9i23)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40597#-NHgbp9sBU5PyScD_YmH:-NHjJCGxBrSknsuTxJBr:b-896fix) (no related file):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Also, could you add what you have tested? A screenshot, log message, or even a 1 liner explaining it would be helpful.
</blockquote></details>

Done.

___

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: Some of the checks are too old. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40597#-NHwlfFICpPhNs40JDSs:-NHwlfFICpPhNs40JDSt:b-9pmkxx) (no related file):*
Changes and local testing look good to me.
@acasian-harness We weren't able to test this by adding load on the API client and getting the connection shutdown exception. 
Can we go ahead without this? Or do you think we need to simulate load and test the retries on actual exception?

___

**Review by vikyathharekal — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40597#-NHwlfFICpPhNs40JDSs:-NI1xzXM6VZV4ACY0CUL:bj1p561) (no related file):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Changes and local testing look good to me.
@acasian-harness We weren't able to test this by adding load on the API client and getting the connection shutdown exception. 
Can we go ahead without this? Or do you think we need to simulate load and test the retries actual exception?
</blockquote></details>

Can we have a UT that at least validates the behaviour in case if those exceptions are thrown?

___

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: :shipit: complete! ✓

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40597)* status: :shipit: complete! ✓

**Pull request merged**
