### PR TITLE
feat: [PLG-1424]: Add customer details to subscription creation endpoint

### PR DESCRIPTION
**Pull request by thomas-grasman**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36362)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36362)

**Comment by thomas-grasman** [comment]
trigger messagecheck

**Comment by thomas-grasman** [comment]
trigger messagecheck

**Review by pranil-harness — DISMISSED** [review]

**Review by pranil-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36362)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by pranil-harness — APPROVED** [review]

**Review by pranil-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36362)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/36362#-N9c_EhoCzZ6_JZeNweV:-N9c_EhoCzZ6_JZeNweW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9aa3b42f7c724e640fcd7cbc6edec842e6bb59e3/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java#L85)):*
> ```Java
>                                                .setPostalCode(customerParams.getAddress().getPostalCode())
>                                                .setState(customerParams.getAddress().getState())
>                                                .build();
> ```

done

**Review by pranil-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36362)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by pranil-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36362)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/36362#-N9c_YfaEai1q1LOVaDg:-N9c_YfaEai1q1LOVaDh:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/9aa3b42f7c724e640fcd7cbc6edec842e6bb59e3/935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java#L85)):*
> ```Java
>                                                .setPostalCode(customerParams.getAddress().getPostalCode())
>                                                .setState(customerParams.getAddress().getState())
>                                                .build();
> ```

done

**Pull request merged**
