### PR TITLE
[fix]: [PL-39051]: Fixing scope identifier regex match criteria for listing role assignments api

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Earlier Roleassignment list api returning incorrect roleassignments due to scope identifiers having substring i.e Project/Org. This Issue was limited to project/org under same same account, having overlapping project/org identifiers along with filter INCLUDING_CHILD_SCOPES

For example if there are two org `org1` and `org12`. Here `org1` is substring of `org12` so regex was end up matching both orgs and returning role assignments for both the orgs. same thing can happen with project identifier having substring. 

Fixing scope identifier regex criteria for listing role assignments by updating below matching criteria
Before: (It was matching roleassignments for both org1 and org12)
```
scopeIdentifier: {$regex : "^/ACCOUNT/kmpySmUISimoRrJL6NL73w/ORGANIZATION/org1"
```

After: (It is matching roleassignments for org1 only)
```
$or: [
        {scopeIdentifier: {$regex : "^/ACCOUNT/kmpySmUISimoRrJL6NL73w/ORGANIZATION/org1/"}}, 
        {scopeIdentifier: "/ACCOUNT/kmpySmUISimoRrJL6NL73w/ORGANIZATION/org1"}
    ]
```

Test:
Tested response for below api call for fetching role assignments.

> curl 'https://ashishs.pr2.harness.io/gateway/authz/api/roleassignments/v2/filter?routingId=-ryfnnBhR9GFU3_UlcQzMQ&accountIdentifier=-ryfnnBhR9GFU3_UlcQzMQ&orgIdentifier=default&projectIdentifier=P1&pageIndex=0&pageSize=10' \
>         -H 'accept: */*' \
>         -H 'authorization: Bearer <token>' \
>         -H 'content-type: application/json' \
>         --data-raw '{"scopeFilters":[{"accountIdentifier":"-ryfnnBhR9GFU3_UlcQzMQ","orgIdentifier":"default","projectIdentifier":"P1","filter":"INCLUDING_CHILD_SCOPES"}],"principalFilter":{"identifier":"KOk-zdfuQtCbYNNlIRGYWw","type":"USER"}}'

- Before changes. It was returning roleassignments for Project `P1` and `P12`

```
{
  "status": "SUCCESS",
  "data": {
    "totalPages": 1,
    "totalItems": 2,
    "pageItemCount": 2,
    "pageSize": 10,
    "content": [
      {
        "identifier": "role_assignment_nlRxo2gUDhxtPn3q3fUH",
        "principal": {
          "scopeLevel": null,
          "identifier": "KOk-zdfuQtCbYNNlIRGYWw",
          "name": "admin user",
          "email": "admin@harness.io",
          "type": "USER"
        },
        "disabled": false,
        "role": {
          "role": {
            "identifier": "_project_admin",
            "name": "Project Admin",
            "permissions": [
              "core_governancePolicy_view",
              "core_governancePolicy_delete",
              ... //truncated output
              "core_connector_delete",
              "core_file_edit"
            ],
            "allowedScopeLevels": [
              "project"
            ],
            "description": "Administrate an existing project.",
            "tags": null
          },
          "scope": null,
          "harnessManaged": true,
          "createdAt": 1700539188561,
          "lastModifiedAt": 1700539188561
        },
        "resourceGroup": {
          "identifier": "_all_project_level_resources",
          "name": "All Project Level Resources",
          "color": "#0063F7",
          "tags": {},
          "description": "All the resources at this project scope are included in this resource group.",
          "allowedScopeLevels": [
            "project"
          ],
          "includedScopes": [
            {
              "filter": "EXCLUDING_CHILD_SCOPES"
            }
          ],
          "resourceFilter": {
            "resources": [],
            "includeAllResources": true
          }
        },
        "scope": {
          "accountIdentifier": "-ryfnnBhR9GFU3_UlcQzMQ",
          "accountName": "Vishal-SMP",
          "orgIdentifier": "default",
          "orgName": "default",
          "projectIdentifier": "P1",
          "projectName": "P1"
        },
        "createdAt": 1700543998598,
        "lastModifiedAt": 1700543998598,
        "harnessManaged": false
      },
      {
        "identifier": "role_assignment_bQy8oZikbXGFzUXd5vr4",
        "principal": {
          "scopeLevel": null,
          "identifier": "KOk-zdfuQtCbYNNlIRGYWw",
          "name": "admin user",
          "email": "admin@harness.io",
          "type": "USER"
        },
        "disabled": false,
        "role": {
          "role": {
            "identifier": "_project_admin",
            "name": "Project Admin",
            "permissions": [
              "core_governancePolicy_view",
              "core_governancePolicy_delete",
              ... //truncated output
              "core_connector_delete",
              "core_file_edit"
            ],
            "allowedScopeLevels": [
              "project"
            ],
            "description": "Administrate an existing project.",
            "tags": null
          },
          "scope": null,
          "harnessManaged": true,
          "createdAt": 1700539188561,
          "lastModifiedAt": 1700539188561
        },
        "resourceGroup": {
          "identifier": "_all_project_level_resources",
          "name": "All Project Level Resources",
          "color": "#0063F7",
          "tags": {},
          "description": "All the resources at this project scope are included in this resource group.",
          "allowedScopeLevels": [
            "project"
          ],
          "includedScopes": [
            {
              "filter": "EXCLUDING_CHILD_SCOPES"
            }
          ],
          "resourceFilter": {
            "resources": [],
            "includeAllResources": true
          }
        },
        "scope": {
          "accountIdentifier": "-ryfnnBhR9GFU3_UlcQzMQ",
          "accountName": "Vishal-SMP",
          "orgIdentifier": "default",
          "orgName": "default",
          "projectIdentifier": "P12",
          "projectName": "P12"
        },
        "createdAt": 1700633371186,
        "lastModifiedAt": 1700633371186,
        "harnessManaged": false
      }
    ],
    "pageIndex": 0,
    "empty": false,
    "pageToken": null
  },
  "metaData": null,
  "correlationId": "35d49e76-705d-4972-be96-3b96480374df"
}
```

- After changes it is returning roleassignments only for Project `P1` as expected

```
{
  "status": "SUCCESS",
  "data": {
    "totalPages": 1,
    "totalItems": 1,
    "pageItemCount": 1,
    "pageSize": 10,
    "content": [
      {
        "identifier": "role_assignment_nlRxo2gUDhxtPn3q3fUH",
        "principal": {
          "scopeLevel": null,
          "identifier": "KOk-zdfuQtCbYNNlIRGYWw",
          "name": "admin user",
          "email": "admin@harness.io",
          "type": "USER"
        },
        "disabled": false,
        "role": {
          "role": {
            "identifier": "_project_admin",
            "name": "Project Admin",
            "permissions": [
              "core_governancePolicy_view",
              "core_governancePolicy_delete",
              ... //truncated output
              "core_connector_delete",
              "core_file_edit"
            ],
            "allowedScopeLevels": [
              "project"
            ],
            "description": "Administrate an existing project.",
            "tags": null
          },
          "scope": null,
          "harnessManaged": true,
          "createdAt": 1700539188561,
          "lastModifiedAt": 1700641297140
        },
        "resourceGroup": {
          "identifier": "_all_project_level_resources",
          "name": "All Project Level Resources",
          "color": "#0063F7",
          "tags": {},
          "description": "All the resources at this project scope are included in this resource group.",
          "allowedScopeLevels": [
            "project"
          ],
          "includedScopes": [
            {
              "filter": "EXCLUDING_CHILD_SCOPES"
            }
          ],
          "resourceFilter": {
            "resources": [],
            "includeAllResources": true
          }
        },
        "scope": {
          "accountIdentifier": "-ryfnnBhR9GFU3_UlcQzMQ",
          "accountName": "Vishal-SMP",
          "orgIdentifier": "default",
          "orgName": "default",
          "projectIdentifier": "P1",
          "projectName": "P1"
        },
        "createdAt": 1700543998598,
        "lastModifiedAt": 1700543998598,
        "harnessManaged": false
      }
    ],
    "pageIndex": 0,
    "empty": false,
    "pageToken": null
  },
  "metaData": null,
  "correlationId": "fe443ce0-2edc-421b-b60a-6473f7d17523"
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55804)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55804)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]

**Review by Jimit09Gandhi — COMMENTED** [review]
Please add test cases that need regression testing.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55804)* status: Some of the checks are too old. 6 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
