### PR TITLE
fix: [CDS-35514]: improve error message for K8s ApiException

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32034)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 1352 at r1](https://reviewable.io/reviews/harness/harness-core/32034#-Mzs_j42BoyJn1ewIaah:-Mzs_j42BoyJn1ewIaai:b1q7p3q) ([raw file](https://github.com/harness/harness-core/blob/798b6ca437a3db32e7f49710069fb13529ae17b1/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1352)):*
> ```Java
> 
>   public String getErrorMessage(ApiException apiException, String errMsg) {
>     if (errMsg == null) {
> ```

nit: let's use EmptyPredicate.isEmpty() for nullcheck

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32034)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 1352 at r1](https://reviewable.io/reviews/harness/harness-core/32034#-Mzs_j42BoyJn1ewIaah:-Mzssz_s3ci8gz8yTjXv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/798b6ca437a3db32e7f49710069fb13529ae17b1/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1352)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: let's use EmptyPredicate.isEmpty() for nullcheck
</blockquote></details>

Done.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32034)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, line 1351 at r2](https://reviewable.io/reviews/harness/harness-core/32034#-MztcZKs1Ce5tebfdNy0:-Mztfb0U298OUu5Glsg9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d2b26ee3fc6b3b7462ae845f548f8fe55cacac97/960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java#L1351)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

This method can be private. Also, let's take only ApiException as the method arg, since responseBody and errorMessage can be extracted from it.
</blockquote></details>

Done.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32034)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32034)* status: :shipit: complete! ✓

**Pull request merged**
