### PR TITLE
[feat]: [PIE-9142]: Fetching the expressions usages

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45672)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger ss

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45672)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsageServiceImpl.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/45672#-NRYw1-cDJ9P4Lis6JqJ:-NRYw1-cDJ9P4Lis6JqK:b8y9025) ([raw file](https://github.com/harness/harness-core/blob/6a968bc35f28166f7388d0e3f5406b00c928fa60/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsageServiceImpl.java#L82)):*
> ```Java
>     Query query = new Query(criteria);
> 
>     // TODO(BRIJESH): Add projections on category.
> ```

can we add category in find ?



_Code quote:_
```Java
ExpressionCategor
```

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45672)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsageServiceImpl.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/45672#-NRYw1-cDJ9P4Lis6JqJ:-NRYwU6hDvT4RH6QHyCp:b-u93ydi) ([raw file](https://github.com/harness/harness-core/blob/6a968bc35f28166f7388d0e3f5406b00c928fa60/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsageServiceImpl.java#L82)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add category in find ?
</blockquote></details>

category can not be added for querying. because the entities are not stored by categoryWise. But a single entity will have data for all categories for a pipeline.
We can use projections to fetch only the category data. That i have added a todo and will implement in next pr.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45672)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 9 of 12 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45672)* status: :shipit: complete! ✓

**Pull request merged**
