### PR TITLE
[feat]: [SRM-10436]: Template Registry + Trigger notifications + Enhance DELETE operation for Monitored Service

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33015)

### CODE REVIEW

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33015#-:-N1l_tsxB4-mRjxassG5:bnfp4nl)* status: 1 file(s) to review. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java` line 979 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1lRLFw-e9ZbqYd1buB:-N1lRLFw-e9ZbqYd1buC:bf9hk49) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L979)):*
> ```Java
>             .build();
>     injector.injectMembers(dataCollectionIterator);
>     notificationExecutor.scheduleWithFixedDelay(() -> dataCollectionIterator.process(), 0, 15, TimeUnit.MINUTES);
> ```

Will we check every 15 min? The interval is 10 but the delay is 15.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1lSWgO0PZH-VDkGJqo:-N1lSWgO0PZH-VDkGJqp:bawyjal) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java#L244)):*
> ```Java
>                                    .field(ActivityKeys.type)
>                                    .in(activityTypes)
>                                    .filter(ActivityKeys.analysisStatus, ActivityVerificationStatus.VERIFICATION_PASSED)
> ```

why verification_passed condition?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1l_L54-PAvGlv214sh:-N1l_L54-PAvGlv214si:b-1l8fc) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java#L90)):*
> ```Java
>           .set(NotificationRuleKeys.notificationMethod, notificationRule.getNotificationMethod())
>           // TODO: add lastSuccessfulCheckTime
>           .set(NotificationRuleKeys.lastSuccessfulCheckTime, notificationRule.getLastSuccessfulCheckTime())
> ```

do we need this anymore?

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33015)* status: 1 file(s) to review. 3. unresolved discussions. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java` line 979 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1lRLFw-e9ZbqYd1buB:-N1lbaCNBEt_IG-hL9Db:b80l7u0) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L979)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

Will we check every 15 min? The interval is 10 but the delay is 15.
</blockquote></details>

nice catch, changed it to 5
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1lSWgO0PZH-VDkGJqo:-N1lb6DqDbJE8pMwyk-8:b-ux1dx) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java#L244)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why verification_passed condition?
</blockquote></details>

I think we should also add: IGNORED, VERIFICATION_PASSED, VERIFICATION_FAILED, ERROR, ABORTED.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1l_L54-PAvGlv214sh:-N1lbNTI1oWcdpuZztFl:b-roipzb) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/notification/entities/NotificationRule.java#L90)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

do we need this anymore?
</blockquote></details>

its removed now

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33015)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java` line 244 at r1](https://reviewable.io/reviews/harness/harness-core/33015#-N1lSWgO0PZH-VDkGJqo:-N1llxIz9wX-xxe9kR2l:b-te8puq) ([raw file](https://github.com/harness/harness-core/blob/f600e30e2da5a301f88481f8ac010314f858bbb1/300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/impl/ActivityServiceImpl.java#L244)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

I think we should also add: IGNORED, VERIFICATION_PASSED, VERIFICATION_FAILED, ERROR, ABORTED.
</blockquote></details>

removed this condition

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33015)* status: :shipit: complete! ✓

**Pull request merged**
