### PR TITLE
fix: [CDS-42422]: Synchronize command units progress instance when sending task progress

### PR DESCRIPTION
**Pull request by abosii-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37055)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37055)

**Comment by yogesh-chauhan** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/37055#-NAxCUNwBPA4HzebScf-:-NAxCUNwBPA4HzebScf0:bacc51w) ([raw file](https://github.com/harness/harness-core/blob/d3205e99aa6ee5f2607d949bec59d3b23df08395/930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java#L112)):*
> ```Java
>       // This sync expects that executor service will use a scheduler based on FIFO priority and update of
>       // commandUnitsProgress is happening in the same thread
>       synchronized (commandUnitsProgress) {
> ```

can command unit progress be null ?
I see there is handling for the same in ```UnitProgressDataMapper.toUnitProgressData(commandUnitsProgress)```

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37055)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/37055#-NAxCUNwBPA4HzebScf-:-NAxKs70-kTF6Bw1Nyzh:bb1g7gi) ([raw file](https://github.com/harness/harness-core/blob/d3205e99aa6ee5f2607d949bec59d3b23df08395/930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java#L112)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can command unit progress be null ?
I see there is handling for the same in ```UnitProgressDataMapper.toUnitProgressData(commandUnitsProgress)```
</blockquote></details>

Good point.. Tbh I'm not sure if this is a valid case but added null handle for this

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37055)* status: 1. unresolved discussions.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37055)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37055)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37055)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger messagecheck

**Pull request merged**
