### PR TITLE
feat: [SPG-21]: Harness Managed Job to clean up Audits

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37786)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37786)

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37786)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 437 at r2](https://reviewable.io/reviews/harness/harness-core/37786#-NCWq1GoA8tcbTun4YL0:-NCWq1GoA8tcbTun4YL1:b250vud) ([raw file](https://github.com/harness/harness-core/blob/4e20bf557f9a1eca7d6f7e53b75db40de7c3772c/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L437)):*
> ```Java
>             log.warn("Failed to delete {} audit records", auditHeaders.size(), ex);
>           }
>           log.info("Successfully deleted {} audits, audit files and chunks", auditHeaders.size());
> ```

unit tests?

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 437 at r2](https://reviewable.io/reviews/harness/harness-core/37786#-NCWq1GoA8tcbTun4YL0:-NCYZteh0pYSHpjWg9uf:b-kmoloo) ([raw file](https://github.com/harness/harness-core/blob/4e20bf557f9a1eca7d6f7e53b75db40de7c3772c/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L437)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

unit tests?
</blockquote></details>

Getting it done.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37786)* status: :shipit: complete! ✓

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37786#-:-ND1Cl5r0VEQeSNlw7eX:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
