### PR TITLE
[fix]: [CDS-51372]: Fix progress update delete logic

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42833)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42833)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42833)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`950-wait-engine/src/main/java/io/harness/waiter/ProgressUpdateService.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/42833#-NM9upas54NsQwteVmzc:-NM9upas54NsQwteVmzd:b-chh1t0) ([raw file](https://github.com/harness/harness-core/blob/85ee9d8c282eaecdedd55913b39c6cd9c417220d/950-wait-engine/src/main/java/io/harness/waiter/ProgressUpdateService.java#L92)):*
> ```Java
>       } finally {
>         if (progressUpdate != null) {
>           log.info(String.format(
> ```

can we make it debug logs

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42833)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42833)* status: :shipit: complete! ✓

___
*[`950-wait-engine/src/main/java/io/harness/waiter/ProgressUpdateService.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/42833#-NM9upas54NsQwteVmzc:-NMCTB6P3YJXkhgwh7jd:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/85ee9d8c282eaecdedd55913b39c6cd9c417220d/950-wait-engine/src/main/java/io/harness/waiter/ProgressUpdateService.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we make it debug logs
</blockquote></details>

done, discussed offline

**Pull request merged**
