### PR TITLE
fix:[PL-32133]: Fix exception in manager logs due to AuthTokenID

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
- Added Validation for AuthToken Id with length Less than 5 
- Added Test to Validate the same

**Test Results**

Screenshot 2023-05-24 at 1 39 47 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47982)

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger messagecheck

**Comment by adiyaar24** [comment]
trigger mdc

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger messagecheck

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47982)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 227 at r3](https://reviewable.io/reviews/harness/harness-core/47982#-NVi4LKD2cx8kkEKopfx:-NVi4LKD2cx8kkEKopfy:bcaq6do) ([raw file](https://github.com/harness/harness-core/blob/a165a0aa2ddd72cdf601f3c10cecee2a33d3a7c2/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L227)):*
> ```Java
>     if (authToken == null) {
>       if (authTokenId.length() >= 5) {
>         log.info("Token with prefix {} not found in cache hence fetching it from db", authTokenId.substring(0, 5));
> ```

Set a variable authTokenIdValue as "authTokenIdValue = authTokenId.length() >= 5 ? authTokenId.substring(0, 5) ?  authTokenId". Do this instead of duplicating the log lines in the if-else.

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger buildnum

**Comment by adiyaar24** [comment]
trigger buildnum

**Comment by adiyaar24** [comment]
trigger ut5

**Comment by adiyaar24** [comment]
trigger checkstylecodeformat

**Comment by adiyaar24** [comment]
trigger codebasehas

**Comment by adiyaar24** [comment]
trigger codebasehash

**Comment by adiyaar24** [comment]
trigger messagecheck

**Review by tiwaritejas — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47982)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]

**Pull request merged**
