### PR TITLE
[feat]: [SRM-10592]: GET API for Notification Rule

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33215)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33215)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/33215#-N2Ej3DiC3KUCXBpYuVe:-N2Ej3DiC3KUCXBpYuVf:b5iscxr) ([raw file](https://github.com/harness/harness-core/blob/749fcb373512bdf33412b7e9d45cc7b115945691/300-cv-nextgen/src/main/java/io/harness/cvng/notification/resources/NotificationRuleResource.java#L105)):*
> ```Java
>   public ResponseDTO<PageResponse<NotificationRuleResponse>>
>   getNotificationRuleDataForSLOOrMonitoredService(@BeanParam ProjectParams projectParams,
>       @QueryParam("pageNumber") @NotNull Integer pageNumber, @QueryParam("pageSize") @NotNull Integer pageSize,
> ```

nit: please use PageParams. You can do this in the next PR
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/NotificationRuleServiceImpl.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/33215#-N2EjI5S4j2iOuFLzP92:-N2EjI5S4j2iOuFLzP93:br6ujbx) ([raw file](https://github.com/harness/harness-core/blob/749fcb373512bdf33412b7e9d45cc7b115945691/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/NotificationRuleServiceImpl.java#L56)):*
> ```Java
>   @Inject private Map<NotificationRuleType, NotificationRuleUpdatableEntity> notificationRuleMapBinder;
>   @Inject Clock clock;
>   @Inject ServiceLevelObjectiveService serviceLevelObjectiveService;
> ```

We should not introduce this dependency. If we want an api with monitoredServiceIdentifier and slo identifier this api should be in the MonitoredServiceResource and SLOResource.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33215#-:-N2G-edP5nP6KgA10b1x:bnfp4nl)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33215#-:-N2G-o9_D9GwLn0zplTk:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
