### PR TITLE
[fix]: [PL-20688]: fix account defaults usage restriction error

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30310)

### CODE REVIEW

**Comment by karansiwach360** [comment]
trigger messagecheck

**Comment by karansiwach360** [comment]
trigger messagecheck

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30310)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/SettingServiceHelper.java, line 308 at r2](https://reviewable.io/reviews/harness/harness-core/30310#-Muj42O642a2InNDPHGc:-Muj42O642a2InNDPHGd:b47dpe3) ([raw file](https://github.com/harness/harness-core/blob/fdacefaa3d1fbd0236535bf3d18f1870b53f94d2/400-rest/src/main/java/software/wings/service/impl/SettingServiceHelper.java#L308)):*
> ```Java
>   }
> 
>   private boolean skipUsageRestrictionsValidation(boolean isAccountAdmin, SettingAttribute settingAttribute) {
> ```

Please write unit tests for this method.

**Review by karansiwach360 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30310)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/SettingServiceHelper.java, line 308 at r2](https://reviewable.io/reviews/harness/harness-core/30310#-Muj42O642a2InNDPHGc:-MukR_fMCtpjkJZQEA8y:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/fdacefaa3d1fbd0236535bf3d18f1870b53f94d2/400-rest/src/main/java/software/wings/service/impl/SettingServiceHelper.java#L308)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Please write unit tests for this method.
</blockquote></details>

Done

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30310#-:-MukXTHtAYKO0v_b6EL6:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30310)* status: :shipit: complete! ✓

**Pull request merged**
