### PR TITLE
feat: [CDS-35073]: added step for creating a PR

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger ft1

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 43 files at r1, 1 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)* status: 50 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/GitOpsServiceSpec.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/33634#-N3JGg016uTc0_2-iC89:-N3JGg016uTc0_2-iC8A:b-tt9pdu) ([raw file](https://github.com/harness/harness-core/blob/a8838995596eb8c8a43169ab4a9a57954a53dc8b/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/GitOpsServiceSpec.java#L35)):*
> ```Java
> @RecasterAlias("io.harness.cdng.service.beans.GitOpsServiceSpec")
> @OwnedBy(HarnessTeam.CDP)
> public class GitOpsServiceSpec implements ServiceSpec, Visitable {
> ```

 we do not need a new Gitops Service Spec. We still want to keep the deployment type as kubernetes. So we can re-use k8s service spec, do you see any issues with that ?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)* status: 51 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/GitOpsServiceSpec.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/33634#-N3JGg016uTc0_2-iC89:-N3JjvsW9rNYEvUoo-3n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8838995596eb8c8a43169ab4a9a57954a53dc8b/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/GitOpsServiceSpec.java#L35)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

 we do not need a new Gitops Service Spec. We still want to keep the deployment type as kubernetes. So we can re-use k8s service spec, do you see any issues with that ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 14 of 43 files at r1, 9 of 26 files at r2, 7 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)* status: 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3JrkD63BPc2_JVWtYV:-N3JrkD63BPc2_JVWtYW:b-o71axv) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L201)):*
> ```Java
>             .setType(StepSpecTypeConstants.GITOPS_CREATE_PR)
>             .setFeatureFlag(FeatureName.NG_GITOPS.name())
>             .setStepMetaData(StepMetaData.newBuilder().addCategory("Kubernetes").setFolderPath("Kubernetes").build())
> ```

as per mocks, should it be shown under kubernetes or Gitops ?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePROutcome.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3JsAQ15qCcDsXZfrhS:-N3JsAQ15qCcDsXZfrhT:bm3rpvn) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePROutcome.java#L23)):*
> ```Java
> @RecasterAlias("io.harness.cdng.gitops.CreatePROutcome")
> public class CreatePROutcome implements Outcome, ExecutionSweepingOutput {
>   String prLink;
> ```

since we do not have PR link now, is this set to the PR number ? If that is the case, we can have a new field. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NRZl-0b5tot2f94iT:-N3NRZl07xMdqR21SO4H:bgib07j) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L74)):*
> ```Java
>   @Inject private CDStepHelper cdStepHelper;
>   @Inject private StepHelper stepHelper;
>   @Inject ExecutionSweepingOutputService executionSweepingOutputService;
> ```

this should also be private
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 144 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NRpSMBUqynCk8S0oj:-N3NRpSMBUqynCk8S0ok:biptgp) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L144)):*
> ```Java
>     List<GitFetchFilesConfig> gitFetchFilesConfig = new ArrayList<>();
>     gitFetchFilesConfig.add(
>         getGitFetchFilesConfig(ambiance, store, ValuesManifestOutcome.builder().identifier("dummy").build()));
> ```

lets add a ToDo here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NRwI3DPg_afvJQ9l8:-N3NRwI3DPg_afvJQ9l9:b-oad0jh) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L153)):*
> ```Java
>             .stringMap(stringMap)
>             .prTitle("new PR")
>             .connectorInfoDTO(cdStepHelper.getConnector(store.getConnectorReference().getValue(), ambiance))
> ```

we should check if the connector is present or not ?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NS0YM1ST_eQuUvO8c:-N3NS0YM1ST_eQuUvO8d:bsoqg63) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L155)):*
> ```Java
>             .connectorInfoDTO(cdStepHelper.getConnector(store.getConnectorReference().getValue(), ambiance))
>             .sourceBranch(gitFetchFilesConfig.get(0).getGitStoreDelegateConfig().getBranch())
>             .targetBranch("master")
> ```

Lets expose this as a step parameter instead of hard coding
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NSoDyAAIyS7suSxEc:-N3NSoDyAAIyS7suSxEd:b-jyhg2e) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L77)):*
> ```Java
> 
>   public static final String FetchFiles = "Fetch Files";
>   public static final String UpdateFiles = "Update fetched files";
> ```

Lets call it "update Gitops configuration files"
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 202 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NTKwr8i86V8UcuCj1:-N3NTKwr8i86V8UcuCj2:b-lzfi96) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L202)):*
> ```Java
>                                                 .build();
> 
>     return ngGitService.commitAndPush(gitConfig, gitCommitRequest, getAccountId(), sshSessionConfig);
> ```

we are supporting ssh as well as token right ?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 252 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NU3Sr63a5nt5jS1Df:-N3NU3Ss4E5BNEaA8ELz:b-2jp1xi) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L252)):*
> ```Java
>   }
> 
>   public List<String> replaceFields(List<String> stringList, Map<String, String> stringMap) throws ParseException {
> ```

lets give better names to stringList and stringMap

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)* status: 21 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3JrkD63BPc2_JVWtYV:-N3Oed4A4LJftHGlHPg8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L201)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

as per mocks, should it be shown under kubernetes or Gitops ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePROutcome.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3JsAQ15qCcDsXZfrhS:-N3Oeg6XBJ33834WrTny:b-ayu7ze) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePROutcome.java#L23)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

since we do not have PR link now, is this set to the PR number ? If that is the case, we can have a new field. 
</blockquote></details>

No creating the PR link from PR number based on connector type
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NRZl-0b5tot2f94iT:-N3Oemi06N703ipGy-oO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L74)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this should also be private
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 144 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NRpSMBUqynCk8S0oj:-N3OenG--8N3RVzZ_nQH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L144)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets add a ToDo here
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NRwI3DPg_afvJQ9l8:-N3Of0Fi0FCRQCspTQP-:b-8kxyyu) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L153)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should check if the connector is present or not ?
</blockquote></details>

we have @NotNull annotation for Store -> getConnectorRef()
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NS0YM1ST_eQuUvO8c:-N3Of6o24iA7v7yvC_4x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/CreatePRStep.java#L155)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets expose this as a step parameter instead of hard coding
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NSoDyAAIyS7suSxEc:-N3Of7PfA8h3oO1bEr_g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L77)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets call it "update Gitops configuration files"
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 252 at r3](https://reviewable.io/reviews/harness/harness-core/33634#-N3NU3Sr63a5nt5jS1Df:-N3Of9Lo9KiK5QkuRkkG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/750ecc588b6e796fe1ad92aecf79bc5e78280c27/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L252)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets give better names to stringList and stringMap
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 43 files at r1, 8 of 26 files at r2, 5 of 13 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger ti4

**Comment by diptiman-adak** [comment]
trigger ti4

**Review by anshul-harness — APPROVED** [review]
> Reviewed 12 of 43 files at r1, 5 of 26 files at r2, 2 of 13 files at r3, 3 of 18 files at r4, 6 of 42 files at r5, 36 of 36 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33634)* status: :shipit: complete! ✓

**Pull request merged**
