### PR TITLE
fix: [DEL-5510] Sanitize multiline secrets in NG

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Multiline secrets were used to getting appear in step logs, as in NG delegate logStreamingSanitizer doesn't break down the multiline secrets. As a fix, we break the multiline secret into individual secrets during initialisation of sanitizer itself.

Testing:
Tested locally and also introduced unit test.

Before
Screenshot 2022-12-12 at 11 09 30 AM

After:
Screenshot 2022-12-12 at 11 08 05 AM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41289)

### CODE REVIEW

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41289)* status: :shipit: complete! ✓

___
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/41289#-NIlc2fp6hmj50Q-ILMF:-NIlc2fp6hmj50Q-ILMG:b962cba) ([raw file](https://github.com/harness/harness-core/blob/eda6fd0a7a6d3c09e9de1a94f38aa59612deb756/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java#L59)):*
> ```Java
>     return secrets.stream()
>         .flatMap(secret -> {
>           String[] split = secret.split("\\r?\\n");
> ```

Looks good, but depending on the use case you would get better performance if you statically compile a Pattern and then use Matchers. Compiling Pattern is quite expensive, but for small use cases this doesn't matter much. However we do it on each iteration here (split internally uses patterns and matchers I believe).

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41289)* status: :shipit: complete! ✓

___
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/41289#-NIlc2fp6hmj50Q-ILMF:-NIpLyLi8wzGDKSYYeM7:bcsu0m) ([raw file](https://github.com/harness/harness-core/blob/eda6fd0a7a6d3c09e9de1a94f38aa59612deb756/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java#L59)):*
> nternally uses patterns and matcher
This happens once during task lifecycle, so should be fine.

**Comment by raghuAtWings** [comment]
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/41289#-NIlc2fp6hmj50Q-ILMF:-NIsGlQX3-ueiNWhcFxU:b-mbcw0k) ([raw file](https://github.com/harness/harness-core/blob/eda6fd0a7a6d3c09e9de1a94f38aa59612deb756/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java#L59)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

> nternally uses patterns and matcher
This happens once during task lifecycle, so should be fine.
</blockquote></details>

how do we ensure that this is not causing any regression. also can we post screenshots of the tests in the PR

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41289)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41289)* status: Some of the checks are too old. 

___
*[`950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/41289#-NIlc2fp6hmj50Q-ILMF:-NJ3s7ZX4eDz2ptqmi0l:b-4krzx9) ([raw file](https://github.com/harness/harness-core/blob/eda6fd0a7a6d3c09e9de1a94f38aa59612deb756/950-log-client/src/main/java/io/harness/logstreaming/LogStreamingSanitizer.java#L59)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

how do we ensure that this is not causing any regression. also can we post screenshots of the tests in the PR 
</blockquote></details>

Same method is being used in CG delegates as well (LogSanitizer.java) from long time. So we just replicated the same behaviour here.

**Pull request merged**
