### PR TITLE
feat: [PIE-6401]: Create a new metric name for plan executions

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40203)

### CODE REVIEW

**Comment by sribalij** [comment]
trigger smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40203)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/resources/metrics/metricGroups/execution-count-metric-group.yaml` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/40203#-NGyp_owC8iIKKhRIVxJ:-NGyp_owC8iIKKhRIVxK:be61rii) ([raw file](https://github.com/harness/harness-core/blob/bc8c180b5ef2e806b946ab4789e0d6a203748acb/pipeline-service/service/src/main/resources/metrics/metricGroups/execution-count-metric-group.yaml#L6)):*
> ```YAML
>   - accountId
>   - orgIdentifier
>   - projectIdentifier
> ```

remove org and project

Plus remove org and project from PlanMonitorServiceImpl during metrics publishing



_Code quote:_
```YAML
  - orgIdentifier
  - projectIdentifier
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40203)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/resources/metrics/metricGroups/execution-count-metric-group.yaml` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/40203#-NGyp_owC8iIKKhRIVxJ:-NGyqMFM3cOnd91GamcY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/bc8c180b5ef2e806b946ab4789e0d6a203748acb/pipeline-service/service/src/main/resources/metrics/metricGroups/execution-count-metric-group.yaml#L6)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

remove org and project

Plus remove org and project from PlanMonitorServiceImpl during metrics publishing
</blockquote></details>

done

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40203#-:-NGyuVCe0tFZHNZ-mJ93:bnfp4nl)* status: :shipit: complete! ✓

**Comment by USB-05** [comment]
trigger sswc

**Comment by USB-05** [comment]
trigger sswc

**Comment by sribalij** [comment]
trigger smartchecks

**Comment by USB-05** [comment]
trigger sswc

**Comment by sribalij** [comment]
trigger smartchecks

**Comment by USB-05** [comment]
trigger sswc

**Comment by USB-05** [comment]
trigger sswc

**Comment by USB-05** [comment]
trigger sswc

**Comment by sribalij** [comment]
trigger ft1

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40203)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40203)* status: :shipit: complete! ✓

**Pull request merged**
