### PR TITLE
[fix]: [PL-21549]: Trimmed leading trailing spaces for name and branch fields in GitSyncConfigDTO

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Trimmed leading trailing spaces for name and branch fields in GitSyncConfigDTO

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 138 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB7Qpl3USUUZlTCfm9:-MyB7Qpl3USUUZlTCfmA:b77xj45) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L138)):*
> ```Java
>       @RequestBody(required = true,
>           description = "Details of Git Sync Config") @NotNull @Valid GitSyncConfigDTO updateGitSyncConfigDTO) {
>     trimNameAndBranch(updateGitSyncConfigDTO);
> ```

please make this method as probably "cleanupRequest" or "formatRequest" and internally you should just do whatever you're doing inside this current method.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 211 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB7aCL0K9hte7CNRkl:-MyB7aCL0K9hte7CNRkm:b-74d2g6) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L211)):*
> ```Java
> 
>   private void trimNameAndBranch(GitSyncConfigDTO gitSyncConfigDTO) {
>     gitSyncConfigDTO.setName(FilePathUtils.trimLeadingAndTrailingSpaces(gitSyncConfigDTO.getName()));
> ```

No need of util method. Simply call .getName().trim(). That should work I guess.
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB7K1y1SJB7bu_QzXZ:-MyB7K1y1SJB7bu_QzX_:b-z92gjv) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L38)):*
> ```Java
> @OwnedBy(DX)
> @ApiModel("GitSyncConfig")
> public class GitSyncConfigDTO {
> ```

make sure wherever this dto is used as request, we add trim logic to the fields in resource layer.
___
*[980-commons/src/main/java/io/harness/utils/FilePathUtils.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB707FDq3UGG9PubhE:-MyB707FDq3UGG9PubhF:b-6c3t3c) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/980-commons/src/main/java/io/harness/utils/FilePathUtils.java#L57)):*
> ```Java
> 
>   public static String trimLeadingAndTrailingSpaces(String value) {
>     int len = value.length();
> ```

There's a direct trim() method for all strings. We don't need this utility method.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)* status: 4 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 210 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB8tE07MXk8BpbSz66:-MyB8tE07MXk8BpbSz67:b-szf7xs) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L210)):*
> ```Java
>   }
> 
>   private void trimNameAndBranch(GitSyncConfigDTO gitSyncConfigDTO) {
> ```

add a null check that if gitSyncConfigDTO is null we don't do anything
___
*[980-commons/src/main/java/io/harness/utils/FilePathUtils.java, line 56 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB8eyKCoka51LN4hDb:-MyB8eyL5kZDe-yxyqvd:b7d9ipu) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/980-commons/src/main/java/io/harness/utils/FilePathUtils.java#L56)):*
> ```Java
>   }
> 
>   public static String trimLeadingAndTrailingSpaces(String value) {
> ```

There should be a harness utils somewhere which trims the string. Please use that function

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)* status: 4 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 138 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB7Qpl3USUUZlTCfm9:-MyBxJvw6mJ8yOG3Hr27:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L138)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please make this method as probably "cleanupRequest" or "formatRequest" and internally you should just do whatever you're doing inside this current method.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 210 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB8tE07MXk8BpbSz66:-MyBxLJh3diVZPMVxv7I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L210)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

add a null check that if gitSyncConfigDTO is null we don't do anything
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 211 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB7aCL0K9hte7CNRkl:-MyBxMTN9dy5CvXYr8K5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L211)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No need of util method. Simply call .getName().trim(). That should work I guess.
</blockquote></details>

Done.
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB7K1y1SJB7bu_QzXZ:-MyBxPQJ8TgYwwKaO2id:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L38)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

make sure wherever this dto is used as request, we add trim logic to the fields in resource layer.
</blockquote></details>

Done.
___
*[980-commons/src/main/java/io/harness/utils/FilePathUtils.java, line 56 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB8eyKCoka51LN4hDb:-MyBxRuO4UNjwXVEAOFc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/980-commons/src/main/java/io/harness/utils/FilePathUtils.java#L56)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

There should be a harness utils somewhere which trims the string. Please use that function
</blockquote></details>

Done.
___
*[980-commons/src/main/java/io/harness/utils/FilePathUtils.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB707FDq3UGG9PubhE:-MyBxTYs34mMygCp10vI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/980-commons/src/main/java/io/harness/utils/FilePathUtils.java#L57)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

There's a direct trim() method for all strings. We don't need this utility method.
</blockquote></details>

Done.

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)* status: 4 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java, line 210 at r1](https://reviewable.io/reviews/harness/harness-core/31441#-MyB8tE07MXk8BpbSz66:-MyCcNvp9zd03rD4XAwV:b-2t1mmd) ([raw file](https://github.com/harness/harness-core/blob/800da02c16b3dfb80782d9238db66ba631daae38/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/YamlGitConfigResource.java#L210)):*
<details><summary><i>Previously, rathodmeetsatish (Meet Rathod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no null check required here, its in resource layer, the dto can't be null here. Redundant check.

Not blocking for now.
___
*[953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java, line 46 at r2](https://reviewable.io/reviews/harness/harness-core/31441#-MyCcnWC9ExacOJCpZhc:-MyCcnWC9ExacOJCpZhd:b84dpk1) ([raw file](https://github.com/harness/harness-core/blob/f2684a8b538bf7eb6a13d2558879b4a548d479b0/953-git-sync-commons/src/main/java/io/harness/gitsync/common/dtos/GitSyncConfigDTO.java#L46)):*
> ```Java
>   @Schema(description = ORG_PARAM_MESSAGE) @Trimmed private String orgIdentifier;
>   @Schema(description = "Id of the Connector referenced in Git") @Trimmed @NotEmpty private String gitConnectorRef;
>   @Schema(description = GitSyncApiConstants.REPO_URL_PARAM_MESSAGE) @Trimmed @NotEmpty private String repo;
> ```

check should be on repo as well right?

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441#-:-MyDpljX7x9xdXD6H1yE:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31441)* status: :shipit: complete! ✓

**Pull request merged**
