### PR TITLE
feat: [CDS-80575]: Add POJOs for variables v1

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger gitleaks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/53612#-Nft6UyhANrjdV3svOKL:-Nft6UyhANrjdV3svOKM:brej3r7) ([raw file](https://github.com/harness/harness-core/blob/68b83c03877136a49ee08f0c032325a6d270ad76/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java#L25)):*
> ```Java
> @Value
> @JsonTypeName(NGVariableConstantsV1.ARRAY_TYPE)
> @OwnedBy(PIPELINE)
> ```

add codepulse to all pojos
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/53612#-NftByAE-ZdU6CdFyIlP:-NftByAE-ZdU6CdFyIlQ:box772d) ([raw file](https://github.com/harness/harness-core/blob/68b83c03877136a49ee08f0c032325a6d270ad76/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java#L27)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class ArrayNGVariableV1 implements NGVariableV1 {
>   NGVariableTypeV1 type = NGVariableTypeV1.ARRAY;
> ```

how we will get name of the variable?
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/53612#-Nft6dW879FNsGXzp4Yj:-Nft6dW879FNsGXzp4Yk:b-66vmuh) ([raw file](https://github.com/harness/harness-core/blob/68b83c03877136a49ee08f0c032325a6d270ad76/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java#L32)):*
> ```Java
>   String desc;
>   boolean required;
>   @JsonProperty("default") List<?> defaultValue;
> ```

can we check if List<Object> is working? for string/number etc

**Comment by shalini-agr** [comment]
trigger uts

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/53612#-Nft6UyhANrjdV3svOKL:-NftE--9DcXjTTO888vy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/68b83c03877136a49ee08f0c032325a6d270ad76/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add codepulse to all pojos
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/53612#-NftByAE-ZdU6CdFyIlP:-NftCB1J515ZTjGMBo03:bm4ud9d) ([raw file](https://github.com/harness/harness-core/blob/68b83c03877136a49ee08f0c032325a6d270ad76/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java#L27)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

how we will get name of the variable?
</blockquote></details>

we will be using Map<String, NGVariableV1> wherever we use this, the key of the map will be the variable name.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 11 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/53612#-Nft6dW879FNsGXzp4Yj:-NfzCF3fDqvD8pXq6lYp:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/68b83c03877136a49ee08f0c032325a6d270ad76/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/ArrayNGVariableV1.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we check if List<Object> is working? for string/number etc
</blockquote></details>

done
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/NGVariableV1Wrapper.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/53612#-NfzCOoIDip-WBB2a7LH:-NfzCOoJ226YhoIXM9CH:b-utyuv6) ([raw file](https://github.com/harness/harness-core/blob/727080d2e3b23aaea412bd275991d5b05953aecc/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/NGVariableV1Wrapper.java#L31)):*
> ```Java
>     if (key.equals(YamlNode.UUID_FIELD_NAME))
>       return;
>     NGVariableV1 variableV1 = YamlUtils.read(YamlUtils.writeYamlString(value), NGVariableV1.class);
> ```

cant we directly read object value into required type? why write is needed?



_Code quote:_
```Java
YamlUtils.read(YamlUtils.writeYamlString(value), NGVariableV1.class);
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/NGVariableV1Wrapper.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/53612#-NfzCOoIDip-WBB2a7LH:-NfzN2eICctB3AaZuNcf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/727080d2e3b23aaea412bd275991d5b05953aecc/953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1/NGVariableV1Wrapper.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant we directly read object value into required type? why write is needed?
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53612)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut5

**Comment by shalini-agr** [comment]
trigger ut7

**Review by mohitg0795 — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger ut5

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
