### PR TITLE
techdebt: [PIE-6388]: combine mean and median queries to optimise API time

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**What is the issue?**
API ("/pipelineHealth") for pipeline executions dashboard is currently taking 1.2+ seconds.

**What is the change?**
The API is currently making 5 queries on timescaleDB to find currentMean, PreviousMean, currentMedian, PreviousMedian, statusAndTime. We have now changed this to 3 queries, by combining mean and median queries.

**Impact?**
Time taken by API reduced by ~500ms.

**Testing?**
a) If Manual -> hit API in local through postman on local, QA and pre-QA timescale database.
b) If indexes -> No
c) If particular/complete sanity ran -> No

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? No
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? No
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? No
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? No
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? No
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/40395#-NHNofp8C3tSJGPrVGKr:-NHNofp8C3tSJGPrVGKs:bn0cuur) ([raw file](https://github.com/harness/harness-core/blob/9b34c1e01431cf7084a94c8a33ab641d7feb8ef9/pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java#L8)):*
> ```Java
>  */
> 
> package io.harness.pms.Dashboard;
> ```

please refactor to dashboard instead of Dashboard package
___
*[`pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/40395#-NHNoan-9gMZa5Id3Ifq:-NHNoan077uje-dqqeBH:b3wagiq) ([raw file](https://github.com/harness/harness-core/blob/9b34c1e01431cf7084a94c8a33ab641d7feb8ef9/pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java#L23)):*
> ```Java
>   private long median;
> 
>   public MeanAndMedian(long mean, long median) {
> ```

please add comment as discussed

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)* status: 4 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/40395#-NHNpcFBCnPpDKleFBjq:-NHNpcFC3g8amFw1enzz:b-f7qg1m) ([raw file](https://github.com/harness/harness-core/blob/9b34c1e01431cf7084a94c8a33ab641d7feb8ef9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PipelineDashboardQueryService.java#L107)):*
> ```Java
>                                                                     Tables.PIPELINE_EXECUTION_SUMMARY_CD.STARTTS))
>                                                             .div(1000),
>                                  DSL.percentileDisc(0.5)
> ```

Also can we add log lines for time how much major component in this API is taking it?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)* status: 24 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/40395#-NHNofp8C3tSJGPrVGKr:-NHOj5yA0gostBCSf_X9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9b34c1e01431cf7084a94c8a33ab641d7feb8ef9/pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java#L8)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

please refactor to dashboard instead of Dashboard package
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/40395#-NHNoan-9gMZa5Id3Ifq:-NHOj3_K-lSYA82n2Kv1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9b34c1e01431cf7084a94c8a33ab641d7feb8ef9/pipeline-service/service/src/main/java/io/harness/pms/Dashboard/MeanAndMedian.java#L23)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

please add comment as discussed
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)* status: 24 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40395)* status: :shipit: complete! ✓

**Pull request merged**
