### PR TITLE
feat:[SRM-13570]: log feedback state

### PR DESCRIPTION
**Pull request by naveen-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44549)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 6 of 14 files at r1, 9 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44549)* status: 6 file(s) to review. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/LogFeedbackAnalysisLearningEngineTask.java` line 2 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbAUe2-w39SNGYiwQY:-NPbAUe2-w39SNGYiwQZ:b-rx6qxx) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/entities/LogFeedbackAnalysisLearningEngineTask.java#L2)):*
> ```Java
> /*
>  * Copyright 2020 Harness Inc. All rights reserved.
> ```

nit: We can update the year
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbBzHB9ScyeFFthCyV:-NPbBzHB9ScyeFFthCyW:b-dcatd) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L31)):*
> ```Java
> 
>   public static final String SRM_INTERNAL_CHANGE_SOURCE_FF = "SRM_INTERNAL_CHANGE_SOURCE_FF";
>   public static final String SRM_LOG_FEEDBACK_ENABLE_UI = "SRM_LOG_FEEDBACK_ENABLE_UI";
> ```

Are we using this anywhere?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogAnalysisStateExecutor.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbCUX54F55NdZk-DA9:-NPbCUX54F55NdZk-DAA:ba2wtq8) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogAnalysisStateExecutor.java#L53)):*
> ```Java
>     Duration duration = verificationJobInstance.getResolvedJob().getDuration();
>     Instant startTime = verificationJobInstance.getStartTime();
>     Instant instant = endTime.minus(duration.toMinutes(), ChronoUnit.MINUTES);
> ```

nit: This variable denotes what instant? We can rename it to be more meaningful



_Code quote:_
```Java
instant
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogAnalysisStateExecutor.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbCrNsBXXXFNzuOKJI:-NPbCrNsBXXXFNzuOKJJ:b-keo0cu) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogAnalysisStateExecutor.java#L66)):*
> ```Java
>         && featureFlagService.isFeatureFlagEnabled(
>             verificationJobInstance.getAccountId(), FeatureFlagNames.SRM_LOG_FEEDBACK_ENABLE_UI)) {
>       analysisState.setStatus(AnalysisStatus.SUCCESS);
> ```

We are already setting the analysisStatus as SUCCESS in the beginning of the function.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbDMH97a_bXdpORG9_:-NPbDMH97a_bXdpORG9a:b-ra7dh0) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java#L51)):*
> ```Java
>     Preconditions.checkNotNull(analysisState.getWorkerTaskId(), "workerId can not be null");
>     analysisState.setStatus(AnalysisStatus.RUNNING);
>     log.info("Executing service guard log analysis for {}", analysisState.getInputs());
> ```

nit: Maybe we should not use CG terminology ie service guard
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbEAxa-Tbz9PoQmX9Z:-NPbEAxa-Tbz9PoQmX9_:bi99ju7) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java#L73)):*
> ```Java
>         default:
>           throw new AnalysisStateMachineException(
>               "Unknown worker state when executing service guard log analysis: " + taskStatus);
> ```

nit: Same as above
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbEGd2-9KbmCRbk3LP:-NPbEGd2-9KbmCRbk3LQ:be5184g) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java#L81)):*
> ```Java
>   @Override
>   public AnalysisState handleRerun(DeploymentLogFeedbackState analysisState) {
>     analysisState.setRetryCount(analysisState.getRetryCount() + 1);
> ```

can getRetryCount() return null

**Review by naveen-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44549)* status: 7 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbBzHB9ScyeFFthCyV:-NPuIyqA6q3MYRL0CN9b:b-rak85o) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L31)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Are we using this anywhere?
</blockquote></details>

Yes, this is used in UI
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogAnalysisStateExecutor.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbCrNsBXXXFNzuOKJI:-NPuJgAjCQVdZIH4GknA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogAnalysisStateExecutor.java#L66)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We are already setting the analysisStatus as SUCCESS in the beginning of the function.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbEGd2-9KbmCRbk3LP:-NPuKUQZDdCO-J1xMgdP:b-m8xsj4) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/DeploymentLogFeedbackStateExecutor.java#L81)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

can getRetryCount() return null
</blockquote></details>

No, this is a standard template of statemachines, it's used everywhere.

**Review by dhruv-harness — COMMENTED** [review]
Lets make sure there are UTs for the updated functionality

> Reviewed 3 of 14 files at r1, 3 of 12 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44549#-:-NPuaPzXE0uMkxuyKbz3:bdk05xs)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImpl.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/44549#-NPu_OxjEsYDqN16FbHB:-NPu_OxjEsYDqN16FbHC:b-bz50wc) ([raw file](https://github.com/harness/harness-core/blob/a623e39b50925094f9656be9c9b6a26260f5c831/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImpl.java#L108)):*
> ```Java
> 
>   @Override
>   public String scheduleDeploymentLogFeedbackTask(AnalysisInput analysisInput) {
> ```

Lets add UT for this
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbBzHB9ScyeFFthCyV:-NPuXwAB771UA93jsE5e:bwhzlgn) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L31)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

Yes, this is used in UI
</blockquote></details>

We have already declared this in the FeatureName enum. Why are we declaring this again?

**Review by naveen-harness — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44549#-:-NQFx7NnBiSrBREnCPWL:bb6un1j)* status: 15 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImpl.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/44549#-NPu_OxjEsYDqN16FbHB:-NQFx9aPDzqgiZpVb6Pz:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a623e39b50925094f9656be9c9b6a26260f5c831/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImpl.java#L108)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Lets add UT for this
</blockquote></details>

Done
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44549#-NPbBzHB9ScyeFFthCyV:-NQFxAcpDup-5LODPYWH:b-imdalb) ([raw file](https://github.com/harness/harness-core/blob/728e6ad8ba89cf4a198e9280240f8072f92b1d09/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L31)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We have already declared this in the FeatureName enum. Why are we declaring this again?
</blockquote></details>

Removed this constant

**Comment by naveen-harness** [comment]
trigger smartchecks

**Review by dhruv-harness — DISMISSED** [review]
> Reviewed 9 of 13 files at r5, 5 of 5 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44549)* status: :shipit: complete! ✓

**Comment by naveen-harness** [comment]
trigger smartchecks

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 12 of 12 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44549)* status: :shipit: complete! ✓

**Pull request merged**
