### PR TITLE
techdebt: [PIE-3190]: Debezium version upgrade

### PR DESCRIPTION
**Pull request by shalini-agr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[WORKSPACE, line 5251 at r1](https://reviewable.io/reviews/harness/harness-core/31542#-MyLsIms3Wl5mQZ9lWvP:-MyLsIms3Wl5mQZ9lWvQ:b-24l1m8) ([raw file](https://github.com/harness/harness-core/blob/48872ad465c1a22381be5331242356532919a002/WORKSPACE#L5251)):*
> ```Starlark
> )
> 
> maven_install(
> ```

Add a comment here as well 
___
*[952-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/31542#-MyLs48Z6SlOmkBaHPRt:-MyLs48Z6SlOmkBaHPRu:bf41ysg) ([raw file](https://github.com/harness/harness-core/blob/48872ad465c1a22381be5331242356532919a002/952-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java#L11)):*
> ```Java
> import io.debezium.engine.RecordChangeEvent;
> import org.apache.kafka.connect.source.SourceRecord;
> ```

Add a comment here why we need to copy this 



_Code quote (from WORKSPACE):_
```Starlark
maven_debezium
```

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)* status: 23 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[WORKSPACE, line 5251 at r1](https://reviewable.io/reviews/harness/harness-core/31542#-MyLsIms3Wl5mQZ9lWvP:-MygFMe957XnR4Np5yle:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/48872ad465c1a22381be5331242356532919a002/WORKSPACE#L5251)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Add a comment here as well 
</blockquote></details>

Done
___
*[952-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java, line 11 at r1](https://reviewable.io/reviews/harness/harness-core/31542#-MyLs48Z6SlOmkBaHPRt:-MyfzDH43bRYFopdu1Jg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/48872ad465c1a22381be5331242356532919a002/952-debezium-engine/src/main/java/io/debezium/embedded/EmbeddedEngineChangeEvent.java#L11)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Add a comment here why we need to copy this 
</blockquote></details>

Done

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygQ7NO4llw1HymF0Vh:-MygQ7NO4llw1HymF0Vi:bnudv2x) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L34)):*
> ```Java
>   public RedisOffsetBackingStore() {}
> 
>   public void connect() {
> ```

we can remove this connect. 
___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 44 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygQAhXAKDEkI78pkUd:-MygQAhXAKDEkI78pkUe:bhbaa6s) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L44)):*
> ```Java
>     super.configure(config);
>     this.redisKey = config.getString("offset.storage.topic");
>     this.config = buildConfig(config.getString("offset.storage.file.filename"));
> ```

lets create the clinet here itself
___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 59 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygQDAh5PBq9H2kIwmQ:-MygQDAh5PBq9H2kIwmR:bn2muvh) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L59)):*
> ```Java
>     super.start();
>     log.info("Starting RedisOffsetBackingStore");
>     this.connect();
> ```

this wont be needed
___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/DebeziumConfig.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygPwZ3EoEtEcKOQNmv:-MygPwZ3EoEtEcKOQNmw:bj7wxjy) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/access-control/libs/aggregator/src/main/java/io/harness/aggregator/DebeziumConfig.java#L16)):*
> ```Java
> import lombok.Builder;
> import lombok.Data;
> ```

this too is a copy?
___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/OpType.java, line 9 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygPeco8WcFghahex3B:-MygPeco8WcFghahex3C:b-iiutw4) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/access-control/libs/aggregator/src/main/java/io/harness/aggregator/OpType.java#L9)):*
> ```Java
> 
> package io.harness.aggregator;
> ```

why are we creating copes is it because of the version thing?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)* status: 1 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 34 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygQ7NO4llw1HymF0Vh:-MygVSEFArj8QJoTNoxx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L34)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

we can remove this connect. 
</blockquote></details>

Done
___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 44 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygQAhXAKDEkI78pkUd:-MygVTMDD9y7q17EKf1p:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L44)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

lets create the clinet here itself
</blockquote></details>

Done
___
*[959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java, line 59 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygQDAh5PBq9H2kIwmQ:-MygVVA35MroiOWyNw1M:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/959-debezium-beans/src/main/java/io/harness/debezium/RedisOffsetBackingStore.java#L59)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this wont be needed
</blockquote></details>

Done
___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/DebeziumConfig.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygPwZ3EoEtEcKOQNmv:-MygQXo29GL12U046QRj:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/access-control/libs/aggregator/src/main/java/io/harness/aggregator/DebeziumConfig.java#L16)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this too is a copy?
</blockquote></details>

yes
___
*[access-control/libs/aggregator/src/main/java/io/harness/aggregator/OpType.java, line 9 at r2](https://reviewable.io/reviews/harness/harness-core/31542#-MygPeco8WcFghahex3B:-MygQWsP58z_ZC4FFKJz:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/405de0ad6ffd95588221bd8a7d751e1468d11ec3/access-control/libs/aggregator/src/main/java/io/harness/aggregator/OpType.java#L9)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why are we creating copes is it because of the version thing?
</blockquote></details>

yes

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 17 of 20 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[951-debezium-service-application/config.yml, line 33 at r3](https://reviewable.io/reviews/harness/harness-core/31542#-MykJp_u57zjaIYs3VHt:-MykJp_u57zjaIYs3VHu:btddhk9) ([raw file](https://github.com/harness/harness-core/blob/81c96c8a4d1d541a6f916fd833231497244b6cf6/951-debezium-service-application/config.yml#L33)):*
> ```YAML
>   - isEnabled: true
>     offset.storage.file.filename: redisson-jcache.yaml
>     offset.storage.topic: debezium:offsets
> ```

nit, offsets need to be as per config name. it could be some prefix-configname



_Code quote:_
```YAML
pmsMongo
```

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by hextechpal — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31542)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Pull request merged**
