### PR TITLE
feat: [CDS-38745]: Added WinRm task parameters support from command step

### PR DESCRIPTION
**Pull request by acasian-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34924)

### CODE REVIEW

**Comment by acasian-harness** [comment]
trigger ti4

**Review by ivan-83 — APPROVED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34924)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/34924#-N67Y6HxA8l064R9M4qf:-N67Y6HxA8l064R9M4qg:bujy8e9) ([raw file](https://github.com/harness/harness-core/blob/0fec794f7dcbc433e8bad86f8ba3088e161569e0/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L219)):*
> ```Java
>   private void publishWinRmInfraDelegateConfigOutput(InfrastructureOutcome infrastructureOutcome, Ambiance ambiance) {
>     WinRmInfraDelegateConfig winRmInfraDelegateConfig =
>         k8sStepHelper.getWinRmInfraDelegateConfig(infrastructureOutcome, ambiance);
> ```

Minor - we could have separate handler for SSH & WinRM deployments or rename k8sStepHelper to common name.

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34924)* status: 6 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/34924#-N67Y6HxA8l064R9M4qf:-N67p5osDXGwtHoNbOPu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0fec794f7dcbc433e8bad86f8ba3088e161569e0/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureStep.java#L219)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - we could have separate handler for SSH & WinRM deployments or rename k8sStepHelper to common name.
</blockquote></details>

Done

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34924#-:-N67qTud91IbQHe32rn-:bnfp4nl)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34924#-:-N6835QK4PCGD2wbjjSj:bnfp4nl)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 15 of 23 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34924)* status: :shipit: complete! ✓

**Pull request merged**
