### PR TITLE
fix: [CDS-43811]: Detect a success zombie condition

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
The condition is detected when the workflow execution keeps running after the most recent state execution instance has succeeded after the end for more than 45 minutes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38412)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38412)

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/38412#-NE9UZKP19xlizVRA4E-:-NE9UZKP19xlizVRA4E0:bhmeuj3) ([raw file](https://github.com/harness/harness-core/blob/c9101b270c3cf92b62e5e715ef086f9da366f33f/400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java#L133)):*
> ```Java
>   //
>   // THE MOST RECENT StateExecutionInstance SHOULD NOT HAVE SUCCESS STATUS AND THE WORKFLOW
>   // EXECUTION STILL IN A RUNNING STATE.
> ```

is this comment valid ? Looks like the most recent stateExecution needs to be in success/skipped state 



_Code quote:_
```Java
  // THE MOST RECENT StateExecutionInstance SHOULD NOT HAVE SUCCESS STATUS AND THE WORKFLOW
  // EXECUTION STILL IN A RUNNING STATE.
```

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java` line 134 at r1](https://reviewable.io/reviews/harness/harness-core/38412#-NE9ZGiqAD_H1RuExxCI:-NE9ZGiqAD_H1RuExxCJ:ba6bf90) ([raw file](https://github.com/harness/harness-core/blob/c9101b270c3cf92b62e5e715ef086f9da366f33f/400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java#L134)):*
> ```Java
>   // THE MOST RECENT StateExecutionInstance SHOULD NOT HAVE SUCCESS STATUS AND THE WORKFLOW
>   // EXECUTION STILL IN A RUNNING STATE.
>   private boolean isSuccessZombie(StateExecutionInstance seInstance) {
> ```

do we also need to check for ```isZombieState(..)``` similar to the ```isZombie``` method ?

**Review by Fernando-Dourado — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38412)* status: Some of the checks are too old. 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/38412#-NE9UZKP19xlizVRA4E-:-NEB02ua5BYlTqKHlXNP:byjqfjj) ([raw file](https://github.com/harness/harness-core/blob/c9101b270c3cf92b62e5e715ef086f9da366f33f/400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java#L133)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this comment valid ? Looks like the most recent stateExecution needs to be in success/skipped state 
</blockquote></details>

It looks good to me, and I can improve if you feel something is missing.

The initial comment block mentions what is the condition to detect a success zombie, the second paragraph just enforces that is not expected to have a workflow execution running if the last `stateExecutionInstance` is already set as a success after ended threshold.
___
*[`400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java` line 134 at r1](https://reviewable.io/reviews/harness/harness-core/38412#-NE9ZGiqAD_H1RuExxCI:-NEAzPhOC7O_hp6bxokg:b5pxxrt) ([raw file](https://github.com/harness/harness-core/blob/c9101b270c3cf92b62e5e715ef086f9da366f33f/400-rest/src/main/java/io/harness/workers/background/critical/iterator/WorkflowExecutionZombieHandler.java#L134)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we also need to check for ```isZombieState(..)``` similar to the ```isZombie``` method ?
</blockquote></details>

The `isZombieState` check only if the `stateExecutionInstance` is one of the zombie state types, it is a support method. The real logic is inside `isZombie` where the main responsibility is to check for three rules to detect a zombie and orchestrate that validation.

In the new method `isSuccessZombie` we don't need to check the state type, as the success condition and keep workflow execution running is the case we want to detect.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38412)* status: Some of the checks are too old.

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Pull request merged**
