### PR TITLE
feat: [PLG-1391]: Added a backfill to manager to mark accounts as product-led

### PR DESCRIPTION
**Pull request by allenthom**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35966)

### CODE REVIEW

**Comment by allenthom** [comment]
trigger ti0

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35966)

**Comment by allenthom** [comment]
trigger messagecheck

**Comment by allenthom** [comment]
trigger messagecheck

**Review by pranil-harness — APPROVED** [review]

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35966)* status: 7 file(s) to review.

**Review by pranil-harness — APPROVED** [review]

**Review by pranil-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 4 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35966)* status: Some of the checks are too old. 1 file(s) to review.

**Comment by allenthom** [comment]
trigger ti3

**Comment by allenthom** [comment]
trigger ti4

**Comment by allenthom** [comment]
trigger ti3

**Comment by allenthom** [comment]
TIbootstrap4-tin4

**Review by diptiman-adak — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35966)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35966)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35966#-:-N9dtC659k5mlZVnKYYQ:bnfp4nl)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35966)* status: :shipit: complete! ✓

**Pull request merged**
