### PR TITLE
[fix]: [CDS-36823]: Add Cluster Name In Gcp Type Instance Migration

### PR DESCRIPTION
**Pull request by tchaurasiya**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32911)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32911)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/32911#-N1rgn7PAECYCc1xyIlv:-N1rgn7PAECYCc1xyIlw:b-81mrf9) ([raw file](https://github.com/harness/harness-core/blob/40b745930db9bb8cd980827f958568a30ac5e66b/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L72)):*
> ```Java
>                     .append(InstanceKeys.infraMappingId, infrastructureMapping.getUuid())
>                     .append(InstanceKeys.appId, infrastructureMapping.getAppId())
>                     .append(InstanceKeys.createdAt, new BasicDBObject("$gt", START_TIMESTAMP));
> ```

we should add isDeleted: false query 
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/32911#-N1rgepJ-FkJ3NUQK64t:-N1rgepJ-FkJ3NUQK64u:b-cz7jps) ([raw file](https://github.com/harness/harness-core/blob/40b745930db9bb8cd980827f958568a30ac5e66b/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L74)):*
> ```Java
>                     .append(InstanceKeys.createdAt, new BasicDBObject("$gt", START_TIMESTAMP));
>             instanceWriteOperation.find(basicDBObject)
>                 .update(new BasicDBObject("$set", new Document("instanceInfo.clusterName", "new-cluster")));
> ```

value should be from infraMapping

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/32911#-N1rgn7PAECYCc1xyIlv:-N1rhvBi5a1cSM7TmPLU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/40b745930db9bb8cd980827f958568a30ac5e66b/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L72)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we should add isDeleted: false query 
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/32911#-N1rgepJ-FkJ3NUQK64t:-N1rhwMp3EjoMDxLv3pK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/40b745930db9bb8cd980827f958568a30ac5e66b/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L74)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

value should be from infraMapping 
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32911)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32911)* status: :shipit: complete! ✓

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32911)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2Bt7vp4orpRyLpe_gC:-N2Bt7vp4orpRyLpe_gD:b7f4gtp) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L45)):*
> ```Java
>   public void migrate() {
>     log.info("Running AddClusterNameInGcpTypeInstanceMigration");
>     //    List<Account> allAccounts = accountService.listAllAccountWithDefaultsWithoutLicenseInfo();
> ```

remove commented out code, or add some documentation around why it needs to stay here.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2BtE6f3nILFOtAC7Vw:-N2BtE6f3nILFOtAC7Vx:b-9amno6) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L46)):*
> ```Java
>     log.info("Running AddClusterNameInGcpTypeInstanceMigration");
>     //    List<Account> allAccounts = accountService.listAllAccountWithDefaultsWithoutLicenseInfo();
>     List<String> firstReleaseConsideredAccount = Collections.singletonList("8e_GD3EARMmLSjFpszuwzw");
> ```

add a human readable name for the account added here.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2Bv-985fD7WH3--Iay:-N2Bv-997csw4hSMmy8i:bl54sil) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L79)):*
> ```Java
>                     "$set", new Document("instanceInfo.clusterName", infrastructureMapping.getClusterName())));
> 
>             log.info("Added clusterName to instances for infraMappingId: {} infra mappings: {}",
> ```

please confirm what the output of `instanceWriteOperation.execute()` is, as we might bloat the logs with un-relevant information.



_Code quote:_
```Java
instanceWriteOperation.execute()
```
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2BvJij2laRj_h_2hb2:-N2BvJij2laRj_h_2hb3:bov0bic) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L82)):*
> ```Java
>                 infrastructureMapping.getUuid(), instanceWriteOperation.execute());
>           } catch (Exception e) {
>             log.error(StringUtils.join(DEBUG_LINE, "Failed to add cluster name to instances for infraMappingId: ",
> ```

we can add the infraMappingName to the logs as well (if we already have it with us), human readable info helps in debugging.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2Bt7vp4orpRyLpe_gC:-N2Gk8181okipXghaMdC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L45)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

remove commented out code, or add some documentation around why it needs to stay here.
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2BtE6f3nILFOtAC7Vw:-N2Gk8fi9pLyRsEPS_Vj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L46)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add a human readable name for the account added here.
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2Bv-985fD7WH3--Iay:-N2GkACI-v_wlSy4ORpI:b2ppjmf) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L79)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

please confirm what the output of `instanceWriteOperation.execute()` is, as we might bloat the logs with un-relevant information.
</blockquote></details>

Done.This tells how many document have been inserted/updated/deleted

**Comment by tchaurasiya** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/32911#-N2BvJij2laRj_h_2hb2:-N2GqzKl0BR5v8bewbGA:b-n9ho6f) ([raw file](https://github.com/harness/harness-core/blob/9f660078f2099d7e52cdf1223df350e0ad612870/390-db-migration/src/main/java/io/harness/migrations/all/AddClusterNameInGcpTypeInstanceMigration.java#L82)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

we can add the infraMappingName to the logs as well (if we already have it with us), human readable info helps in debugging.
</blockquote></details>

Done.Added

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32911)* status: :shipit: complete! ✓

**Pull request merged**
