### PR TITLE
fix: [CDS-49570]: Running workflow with helmv3 does not render the fields having null or empty value

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)

### CODE REVIEW

**Review by GoelPratyush99 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1036 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nUcx4ZuUr6K1u9CN:-NL_nUcx4ZuUr6K1u9CO:btbd63) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1036)):*
> ```Java
>                                .manifestStoreTypes(StoreType.HelmSourceRepo)
>                                .helmCommandFlag(helmCommandFlag)
>                                .dontRenderDefaultValues(
> ```

Missing condition check for Helm V2
___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1076 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ncv91EhUNpWZ7CE_:-NL_ncv91EhUNpWZ7CEa:btbd63) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1076)):*
> ```Java
>                                  .helmCommandFlag(helmCommandFlag)
>                                  .dontRenderDefaultValues(
>                                      featureFlagService.isEnabled(CDP_SKIP_DEFAULT_VALUES_YAML, context.getAccountId()))
> ```

Missing condition check for Helm V2
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nfM95cYm56PKZNRU:-NL_nfM95cYm56PKZNRV:btbd63) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L280)):*
> ```Java
>         prepareRemoteDelegateManifestConfig(context, appManifest, manifestConfigBuilder);
>         manifestConfigBuilder.dontRenderDefaultValues(
>             featureFlagService.isEnabled(CDP_SKIP_DEFAULT_VALUES_YAML, context.getAccountId()));
> ```

Missing condition check for Helm V2
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ng9l7-VO6YE3heZ2:-NL_ng9l7-VO6YE3heZ3:btbd63) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L291)):*
> ```Java
>             helmChartConfigHelperService.getHelmChartConfigTaskParams(context, appManifest));
>         manifestConfigBuilder.dontRenderDefaultValues(
>             featureFlagService.isEnabled(CDP_SKIP_DEFAULT_VALUES_YAML, context.getAccountId()));
> ```

Missing condition check for Helm V2
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1511 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_npVr-yLGop7KLkUf:-NL_npVr-yLGop7KLkUg:b-22aity) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1511)):*
> ```Java
>       defaultValuesYaml = new String(Files.readAllBytes(Paths.get(chartDir, "values.yaml")));
>     } catch (IOException e) {
>       throw new InvalidRequestException("[IO exception]: Failed to read default values.yaml");
> ```

When default "values.yaml" file is not present in Helm Chart and the user provides the values with different name then this will fail the pipeline as this exception is not handled.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 562 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_oJd62oZg0GSqgnMQ:-NL_oJd62oZg0GSqgnMR:b-bo02gw) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L562)):*
> ```Java
>   DEPLOYMENT_RECONCILIATION_LOGIC_QUERY_OPTIMIZATIONS(
>       "Used to modify logic for reconciliation queries", HarnessTeam.CDC),
>   CDP_SKIP_DEFAULT_VALUES_YAML(
> ```

Can we have 2 different FF one for CG and one for NG.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 13 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1036 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nUcx4ZuUr6K1u9CN:-NLdlxvc7XEanQnDGxmY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1036)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1076 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ncv91EhUNpWZ7CE_:-NLdlyOR-y2iFAr1GpJG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1076)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nfM95cYm56PKZNRU:-NLdo7BLA_0HgESoUDNQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L280)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ng9l7-VO6YE3heZ2:-NLdo7UZDpBvIidE8Z1I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L291)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 562 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_oJd62oZg0GSqgnMQ:-NLduh0HA6rCpmATWg2C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L562)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Can we have 2 different FF one for CG and one for NG.
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 8 files at r2, 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 7 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 582 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLez0xNEyFieW2xTaB_:-NLez0xNEyFieW2xTaBa:bv33vnu) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L582)):*
> ```Java
>             .useRepoFlags(helmVersion != HelmVersion.V2)
>             .deleteRepoCacheDir(helmVersion != HelmVersion.V2)
>             .dontRenderDefaultValues(helmVersion != HelmVersion.V2
> ```

Let's do the helm version check on delegate
___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1036 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nUcx4ZuUr6K1u9CN:-NLezGFH-Kw-qqHoyw0e:b-xvhn0) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1036)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Same here, move version check to delegate
___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1076 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ncv91EhUNpWZ7CE_:-NLezGit3BxycPnOu6V9:b-xvhn0) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1076)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Same here, move version check to delegate
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nfM95cYm56PKZNRU:-NLezL9sEKMZIsD2bwZj:b-xvhn0) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L280)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Same here, move version check to delegate
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ng9l7-VO6YE3heZ2:-NLezLsP0P__nfWyikki:b-xvhn0) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L291)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Missing condition check for Helm V2
</blockquote></details>

Same here, move version check to delegate
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 1364 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLezNdZ-PXVjNaC_Her:-NLezNdZ-PXVjNaC_Hes:b-5g2kkv) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L1364)):*
> ```Java
>   }
> 
>   public HelmVersion getHelmVersionFromSvc(ExecutionContext context) {
> ```

We shouldn't need it anymore
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1508 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLezm2e36VppPYkUPc3:-NLezm2e36VppPYkUPc4:b4ibxli) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1508)):*
> ```Java
>     }
>     String renderedDefValuesYaml = valuesYamlList.get(0);
>     String defaultValuesYaml = "";
> ```

nit: why we can't just move it under catch block?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1511 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf-w01DAZIo-cvCIpT:-NLf-w01DAZIo-cvCIpU:bcnb9qf) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1511)):*
> ```Java
>     try {
>       defaultValuesYaml = new String(Files.readAllBytes(Paths.get(chartDir, "values.yaml")));
>     } catch (FileNotFoundException e) {
> ```

let's add some logging here for debuging purpose. And let's not fail if something went, just log it
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 355 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf14-j0Mqx7S4JNOAz:-NLf14-j0Mqx7S4JNOB-:b-93eiqo) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L355)):*
> ```Java
>   }
> 
>   public void skipDefaultValuesYamlWhileRender(HelmInstallCommandRequest commandRequest) {
> ```

should be private and better name
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 364 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf0szc4nIsLLTaymQz:-NLf0szc4nIsLLTaymR-:b-ekqghc) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L364)):*
> ```Java
>       List<String> valuesYamlList = commandRequest.getVariableOverridesYamlFiles();
>       valuesYamlList.remove(0);
>       commandRequest.setVariableOverridesYamlFiles(valuesYamlList);
> ```

nit: redundant, variableOverridesYamlFiles in commandRequest is already valuesYamlList
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDelegateManifestConfig.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLey9NEC6tQOt2oJNzu:-NLey9NFEKEb3wrVatxu:b-v29bg0) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDelegateManifestConfig.java#L64)):*
> ```Java
> 
>   private boolean shouldSaveManifest;
>   private boolean dontRenderDefaultValues;
> ```

Something like skipApplyHelmDefaultValues may be a better option
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/HelmChartManifestDelegateConfig.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLeyfyy7ijTpoacjShV:-NLeyfyy7ijTpoacjShW:b-eg7e0c) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/HelmChartManifestDelegateConfig.java#L29)):*
> ```Java
>   private boolean useRepoFlags;
>   private boolean deleteRepoCacheDir;
>   private boolean dontRenderDefaultValues;
> ```

Same here (naming)
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 574 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf1SiH4KbDhqfTtjLv:-NLf1SiH4KbDhqfTtjLw:bg75zh0) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L574)):*
> ```Java
>       "Skip adding the default values file as an override if it doesn't contain any expressions in case of helm chart manifest for NG",
>       HarnessTeam.CDP),
>   CDP_SKIP_DEFAULT_VALUES_YAML_CG(
> ```

Please make sure that the name was approved by Rohan and add PM Rohan to FF description

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 13 file(s) to review. 2 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 582 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLez0xNEyFieW2xTaB_:-NLf8BWe7PKiOpy4PIBA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L582)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's do the helm version check on delegate
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1036 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nUcx4ZuUr6K1u9CN:-NLfJykv-4gwECcojNf1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1036)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, move version check to delegate
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java` line 1076 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ncv91EhUNpWZ7CE_:-NLf8CmHA0lZqY4aJm6c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/HelmDeployState.java#L1076)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, move version check to delegate
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 280 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_nfM95cYm56PKZNRU:-NLfK-ClAMgJtjP4EsdT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L280)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, move version check to delegate
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_ng9l7-VO6YE3heZ2:-NLfK-xv4JFSGw2-sL4y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L291)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here, move version check to delegate
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java` line 1364 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLezNdZ-PXVjNaC_Her:-NLfJMjz3QyyHooata8b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L1364)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We shouldn't need it anymore
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1511 at r2](https://reviewable.io/reviews/harness/harness-core/42277#-NL_npVr-yLGop7KLkUf:-NLfNmcG7MMxk516bv3C:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f9818f4b8c75fec9ccf6b83973476c94576c7365/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1511)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

When default "values.yaml" file is not present in Helm Chart and the user provides the values with different name then this will fail the pipeline as this exception is not handled.
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java` line 1511 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf-w01DAZIo-cvCIpT:-NLfNlE84biEH_BVe7YY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L1511)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's add some logging here for debuging purpose. And let's not fail if something went, just log it
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java` line 355 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf14-j0Mqx7S4JNOAz:-NLfQ_7P0ErDk3bjCKCW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/software/wings/helpers/ext/helm/HelmDeployServiceImpl.java#L355)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

should be private and better name
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDelegateManifestConfig.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLey9NEC6tQOt2oJNzu:-NLfJnMF8RS1zp5JXJu4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/930-delegate-tasks/src/main/java/software/wings/helpers/ext/k8s/request/K8sDelegateManifestConfig.java#L64)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Something like skipApplyHelmDefaultValues may be a better option
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/HelmChartManifestDelegateConfig.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLeyfyy7ijTpoacjShV:-NLfJw6H1VR7dpa4rg3j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/HelmChartManifestDelegateConfig.java#L29)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Same here (naming)
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 574 at r4](https://reviewable.io/reviews/harness/harness-core/42277#-NLf1SiH4KbDhqfTtjLv:-NLfRVtM1YtXgavZaxMO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f292b336a28f7659d572f8bc3f208a9e76cf57a/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L574)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please make sure that the name was approved by Rohan and add PM Rohan to FF description
</blockquote></details>

Done.

**Comment by abosii-harness** [comment]
Please take care of the sonarqube issues

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 9 of 12 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 14 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 16 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Comment by abosii-harness** [comment]
Don't forget to add some automation at least for NG

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 16 file(s) to review.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 7 of 12 files at r5, 2 of 4 files at r6, 2 of 2 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: 1 file(s) to review.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42277)* status: :shipit: complete! ✓

**Pull request merged**
