### PR TITLE
feat: [IDP-1716]: Store scorecard & check stats data in DB

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55923)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55923)* status: 35 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatsRepositoryCustomImpl.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/55923#-Nk0eRyf1Y5nJRUqwCIe:-Nk0eRyf1Y5nJRUqwCIf:bsjdj6h) ([raw file](https://github.com/harness/harness-core/blob/01e7d650ca02b204aaa57e85b5074560361b29be/idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatsRepositoryCustomImpl.java#L33)):*
> ```Java
>   private MongoTemplate mongoTemplate;
>   @Override
>   public CheckStatsEntity saveOrUpdate(CheckStatus checkStatus, BackstageCatalogEntity backstageCatalog,
> ```

Same comment as earlier.
We aren't creating or updating ScorecardStatsEntity in this one. Can we rename this appropriately?
Or we could have this in service layer and use findByAccountIdentifierAndEntityIdentifierAndCheckIdentifierAndIsCustom() to get from DB



_Code quote:_
```Java
saveOrUpdate
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardStatsRepositoryCustomImpl.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/55923#-Nk0BLW82JNkf-VdD2OJ:-Nk0BLW82JNkf-VdD2OK:bld4zcy) ([raw file](https://github.com/harness/harness-core/blob/01e7d650ca02b204aaa57e85b5074560361b29be/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardStatsRepositoryCustomImpl.java#L45)):*
> ```Java
> 
>   @Override
>   public ScorecardStatsEntity saveOrUpdate(ScoreEntity scoreEntity, BackstageCatalogEntity backstageCatalog) {
> ```

We aren't creating or updating ScorecardStatsEntity in this one. Can we rename this appropriately?



_Code quote:_
```Java
saveOrUpdate
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/beans/StatsMetadata.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/55923#-Nk09iYq4eZZ3kW_8KyQ:-Nk09iYr9jV65P-QOVkl:b50ztdx) ([raw file](https://github.com/harness/harness-core/blob/01e7d650ca02b204aaa57e85b5074560361b29be/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/beans/StatsMetadata.java#L8)):*
> ```Java
>  */
> 
> package io.harness.idp.scorecard.scores.beans;
> ```

shouldn't the package be io.harness.idp.scorecard.scorecards.beans?



_Code quote:_
```Java
io.harness.idp.scorecard.scores.bean
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55923)* status: 42 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatsRepositoryCustomImpl.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/55923#-Nk0eRyf1Y5nJRUqwCIe:-Nk0s7wTEub_HAhMCYXI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/01e7d650ca02b204aaa57e85b5074560361b29be/idp-service/src/main/java/io/harness/idp/scorecard/checks/repositories/CheckStatsRepositoryCustomImpl.java#L33)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Same comment as earlier.
We aren't creating or updating ScorecardStatsEntity in this one. Can we rename this appropriately?
Or we could have this in service layer and use findByAccountIdentifierAndEntityIdentifierAndCheckIdentifierAndIsCustom() to get from DB
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardStatsRepositoryCustomImpl.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/55923#-Nk0BLW82JNkf-VdD2OJ:-Nk0srdh6VRLBE010HW9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/01e7d650ca02b204aaa57e85b5074560361b29be/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/repositories/ScorecardStatsRepositoryCustomImpl.java#L45)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We aren't creating or updating ScorecardStatsEntity in this one. Can we rename this appropriately?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/beans/StatsMetadata.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/55923#-Nk09iYq4eZZ3kW_8KyQ:-Nk0s8of1E9O6xO7L0rS:bove1hs) ([raw file](https://github.com/harness/harness-core/blob/01e7d650ca02b204aaa57e85b5074560361b29be/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/beans/StatsMetadata.java#L8)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

shouldn't the package be io.harness.idp.scorecard.scorecards.beans?
</blockquote></details>

yeah, some weird thing in intellij. Although it says "scores.bean", it was appearing in "scorecards.bean".

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55923)* status: 42 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Review by devesh-harness — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
