### PR TITLE
feat: [CDS-82480] Support TrafficRouting for the Canary Step [delegate]

### PR DESCRIPTION
**Pull request by alebuh**
## Describe your changes
Adding logic for creating Traffic Routing resources in Canary Step. All logic will be done just in case when TrafficRoutingConfig is provided
1. Find the primary service in the manifest. Similar logic as in the BG step, if there is only one service use that one. If there are more than one, one should have a primary annotation
2. From the primary service create a canary that will be the same, just with a canary suffix in the name
3. Add canary service to the resource lis
4. In primary service add a stable and in canary add canary label selector
5. Create Traffic Routing resources and add them to the list of resources
6. Keep track of the created resources (canary service and traffic routing resources) as we are going to delete them in the canary delete step
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57131)

### CODE REVIEW

**Comment by alebuh** [comment]
trigger uts, messagecheck, ss

**Comment by alebuh** [comment]
trigger ss

**Comment by alebuh** [comment]
trigger uts

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java` line 229 at r2](https://reviewable.io/reviews/harness/harness-core/57131#-NmogLMcAyBA5wxxO83w:-NmogLMcAyBA5wxxO83x:b79z8qb) ([raw file](https://github.com/harness/harness-core/blob/0f957c9cec7251aed7bc5766334fd8a2ed60873a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java#L229)):*
> ```Java
>     if (k8sCanaryDeployRequest.getTrafficRoutingConfig() != null
>         && k8sCanaryHandlerConfig.getTrafficRoutingCanaryResources() != null) {
>       canaryObjectsNames += "," + k8sCanaryHandlerConfig.getTrafficRoutingCanaryResources();
> ```

nit: could have used String.format(...)

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 379 at r2](https://reviewable.io/reviews/harness/harness-core/57131#-NmohFyT-x4HV-z_HcRY:-NmohFyT-x4HV-z_HcRZ:bvayomd) ([raw file](https://github.com/harness/harness-core/blob/0f957c9cec7251aed7bc5766334fd8a2ed60873a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L379)):*
> ```Java
>     // canary delete step
>     String trafficRoutingCanaryResources = canaryService.getResourceId().namespaceKindNameRef();
>     trafficRoutingCanaryResources += isNotEmpty(trafficRoutingResources) ? ","
> ```

nit: same here string.format(..)

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 374 at r2](https://reviewable.io/reviews/harness/harness-core/57131#-Nmoi0KsDsMbwxTkWSPd:-Nmoi0KsDsMbwxTkWSPe:b-4kpiev) ([raw file](https://github.com/harness/harness-core/blob/0f957c9cec7251aed7bc5766334fd8a2ed60873a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L374)):*
> ```Java
>   }
> 
>   void setTrafficRoutingCanaryResources(K8sCanaryHandlerConfig k8sCanaryHandlerConfig, KubernetesResource canaryService,
> ```

I think you can re-use existing field that contains all the resources that will be deleted.
You can take a look at the logic

io.harness.delegate.k8s.K8sCanaryBaseHandler#appendResourceNamesToCanaryWorkloads

**Review by markoharness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57131)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57131)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 374 at r2](https://reviewable.io/reviews/harness/harness-core/57131#-Nmoi0KsDsMbwxTkWSPd:-NmpF8RJ7AxEEyhL-qHF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/0f957c9cec7251aed7bc5766334fd8a2ed60873a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L374)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

I think you can re-use existing field that contains all the resources that will be deleted.
You can take a look at the logic

io.harness.delegate.k8s.K8sCanaryBaseHandler#appendResourceNamesToCanaryWorkloads
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java` line 379 at r2](https://reviewable.io/reviews/harness/harness-core/57131#-NmohFyT-x4HV-z_HcRY:-NmpFAMI-fGgCgm1VFE7:b-b6d7gw) ([raw file](https://github.com/harness/harness-core/blob/0f957c9cec7251aed7bc5766334fd8a2ed60873a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java#L379)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

nit: same here string.format(..)
</blockquote></details>

not relevant anymore
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java` line 229 at r2](https://reviewable.io/reviews/harness/harness-core/57131#-NmogLMcAyBA5wxxO83w:-NmpFD9v0XpgSpdbBSRf:b-b6d7gw) ([raw file](https://github.com/harness/harness-core/blob/0f957c9cec7251aed7bc5766334fd8a2ed60873a/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryRequestHandler.java#L229)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

nit: could have used String.format(...)
</blockquote></details>

not relevant anymore

**Comment by alebuh** [comment]
trigger uts

**Review by markoharness — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57131)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team.

**Review by markoharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57131)* status: 9 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by markoharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57131)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]

**Review by abhinavsingh1196 — APPROVED** [review]

**Comment by alebuh** [comment]
trigger review

**Pull request merged**
