### PR TITLE
[feat]: [CDS-43571]: support shell script provisioning

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37918)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 8 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37918)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 42 of 42 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37918)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/shellscript/ShellScriptProvisionStep.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2CubECgQ18O_XMlKV:-ND2CubFD1kLVeKH3Rp3:b-n2rcve) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/125-cd-nextgen/src/main/java/io/harness/cdng/provision/shellscript/ShellScriptProvisionStep.java#L163)):*
> ```Java
>         res.put(key, (String) value);
>       } else {
>         log.error(String.format(
> ```

nit: this should be warn if it's not failing deployment
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/shellscript/ShellScriptProvisionStep.java` line 180 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2D5JvB-ef32zaxoXa:-ND2D5JvB-ef32zaxoXb:b2wk678) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/125-cd-nextgen/src/main/java/io/harness/cdng/provision/shellscript/ShellScriptProvisionStep.java#L180)):*
> ```Java
>       return new ObjectMapper().readValue(output, typeRef);
>     } catch (IOException e) {
>       log.error("Output : " + output);
> ```

Can output contain sensitive data? Should we avoid printing it?
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java` line 614 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2Dr694tDKBezMV3El:-ND2Dr694tDKBezMV3Em:b-4023hl) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java#L614)):*
> ```Java
>                    .entityType(EntityType.SHELL_SCRIPT_PROVISION_STEP)
>                    .availableAtProjectLevel(true)
>                    .availableAtOrgLevel(true)
> ```

shouldn't it be available only at project level?
___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java` line 619 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2E2ysDVsqYTYNJLXS:-ND2E2ysDVsqYTYNJLXT:b8lnbfk) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java#L619)):*
> ```Java
>                    .yamlSchemaMetadata(YamlSchemaMetadata.builder()
>                                            .namespace(SchemaNamespaceConstants.CD)
>                                            .modulesSupported(ImmutableList.of(ModuleType.CD))
> ```

I can see for other provisioner steps we added PMS module type as well, don't we need to the same for ShellScript provisioner?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2Eim42_7WVgvZjWIU:-ND2Eim42_7WVgvZjWIV:b2dpvb0) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java#L99)):*
> ```Java
>       logCallback.saveExecutionLog(message, INFO, SUCCESS);
>       if (executeCommandResponse.getStatus() == CommandExecutionStatus.FAILURE) {
>         return ShellScriptProvisionTaskNGResponse.builder()
> ```

any plans for error handling?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java` line 121 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2Fefd9jCMYvhK8rqM:-ND2Fefd9jCMYvhK8rqN:brneg9s) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java#L121)):*
> ```Java
>           .build();
>     } finally {
>       FileUtils.deleteQuietly(outputFile);
> ```

Are we good with keeping shellScriptProvisioner/executionId path? Shouldn't we delete and this path as well?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2Er9x7EA1RIYrQ1Gg:-ND2Er9x7EA1RIYrQ1Gh:bjjote8) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java#L126)):*
> ```Java
> 
>   private String getOutputPath(String executionId) {
>     return Paths.get("").toAbsolutePath() + "/shellScriptProvisioner/" + executionId + "/output.json";
> ```

nit: This can be Paths.get("shellScriptProvisioner", executionId, "output.json").toAbsolutePath(). And just to confirm that /opt/harness-delegate/shellScriptProvisioner/executionId/output.json is expected path here 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2FEpKA97jyObSkvNF:-ND2FEpL65J3OO0I_PkO:b-3ftph5) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java#L133)):*
> ```Java
>     boolean mkdirs = file.getParentFile().mkdirs();
>     if (!mkdirs && !file.getParentFile().exists()) {
>       throw new InvalidRequestException("Unable to create directory for output file");
> ```

nit: logging the path or provide in error may be useful for debugging.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNGRequest.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/37918#-ND2G3VY9RdJ1QW25u9v:-ND2G3VY9RdJ1QW25u9w:b-4bdthm) ([raw file](https://github.com/harness/harness-core/blob/68a773b31a24ea1010b2a167013b452ce77daf0e/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNGRequest.java#L36)):*
> ```Java
>     implements TaskParameters, ExecutionCapabilityDemander, NestedAnnotationResolver {
>   @NonNull String accountId;
>   private String executionId;
> ```

nit: private modifier is not required, it's default private for Value annotation

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37918#-:-ND3dxA73DojuEDlX7S1:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 37 of 42 files at r1, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37918#-:-ND7EOCm-CzcCZGhn-Lq:bnfp4nl)* status: :shipit: complete! ✓

**Review by vaibhav-si — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37918)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/37918#-ND7HgSOCmQ9KiWje0jN:-ND7HgSOCmQ9KiWje0jO:b-m8tvz0) ([raw file](https://github.com/harness/harness-core/blob/574a25f26094cd39501e2bd0cba8055c1a15a1f7/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java#L72)):*
> ```Java
>     String workingDir = null;
>     try {
>       CommandUnitsProgress commandUnitsProgress = CommandUnitsProgress.builder().build();
> ```

when there is single command unit, we can skip it altogether. It doesn't serve any purpose for the user but adds complexity to the system to update the statuses of command units.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37918)* status: 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java` line 72 at r4](https://reviewable.io/reviews/harness/harness-core/37918#-ND7HgSOCmQ9KiWje0jN:-ND7QFl39TbPFyz7sikR:b-2yunt8) ([raw file](https://github.com/harness/harness-core/blob/574a25f26094cd39501e2bd0cba8055c1a15a1f7/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/provisioner/ShellScriptProvisionTaskNG.java#L72)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

when there is single command unit, we can skip it altogether. It doesn't serve any purpose for the user but adds complexity to the system to update the statuses of command units.
</blockquote></details>

Not sure if I got it. In  getLogCallback() we create  a new NGDelegateLogCallback() which require a CommandUnitsProgress.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 37 of 42 files at r1, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37918)* status: :shipit: complete! ✓

**Pull request merged**
