### PR TITLE
[feat]: [CVS-9133]: added total cluster count and event count

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)

### CODE REVIEW

**Comment by kapil-harness** [comment]
@GET API:
https://localhost:8181/cv/api/verify-step/jkuTfvxnQ3-NzYU1gB7CIg/deployment-log-analysis-data-v2?routingId=kmpySmUISimoRrJL6NL73w&accountId=kmpySmUISimoRrJL6NL73w&pageNumber=0&pageSize=10&clusterTypes=KNOWN_EVENT&clusterTypes=UNKNOWN_EVENT

Response:
{
    "metaData": {},
    "resource": {
        "totalClusters": 4,
        "eventCounts": [
            {
                "clusterType": "KNOWN_EVENT",
                "count": 2
            },
            {
                "clusterType": "UNKNOWN_EVENT",
                "count": 1
            },
            {
                "clusterType": "UNEXPECTED_FREQUENCY",
                "count": 0
            }
        ],
        "logAnalysisClusterDTO": {
            "totalPages": 1,
            "totalItems": 3,
            "pageItemCount": 3,
            "pageSize": 10,
            "content": [
                {
                    "message": "java.lang.RuntimeException: java.io.IOException: Error reading and writing to file  at io.IOExceptionGenerator.generateIOException(IOExceptionGenerator.java:16)  at inside.RequestException.doGet(RequestException.java:128)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)  at java.lang.Thread.run(Thread.java:748) Caused by: java.io.IOException: Error reading and writing to file  ... 26 more ",
                    "label": 12,
                    "clusterType": "UNKNOWN_EVENT",
                    "risk": "UNHEALTHY",
                    "score": 1.0,
                    "count": 14,
                    "controlFrequencyData": [
                        12.0,
                        8.0,
                        8.0,
                        20.0,
                        4.0,
                        3.0,
                        5.0,
                        4.0,
                        2.0
                    ],
                    "testFrequencyData": [
                        14.0,
                        10.0,
                        8.0,
                        20.0,
                        4.0,
                        5.0,
                        5.0,
                        4.0,
                        5.0
                    ]
                },
                {
                    "message": "java.lang.NullPointerException: Null pointer exception  at com.realtime.StreamProcessor.processStreamData(StreamProcessor.java:13)  at inside.RequestException.doGet(RequestException.java:108)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)  at java.lang.Thread.run(Thread.java:748) ",
                    "label": 0,
                    "clusterType": "KNOWN_EVENT",
                    "risk": "HEALTHY",
                    "score": 0.0,
                    "count": 58,
                    "controlFrequencyData": [
                        4.0,
                        2.0,
                        7.0,
                        2.0,
                        5.0,
                        6.0,
                        5.0,
                        4.0,
                        5.0
                    ],
                    "testFrequencyData": [
                        10.0,
                        4.0,
                        11.0,
                        9.0,
                        6.0,
                        4.0,
                        10.0,
                        4.0
                    ]
                },
                {
                    "message": "java.lang.RuntimeException: Method throws runtime exception  at com.runtime.RunTimeExceptionGenerator.generateRunTimeException(RunTimeExceptionGenerator.java:16)  at inside.RequestException.doGet(RequestException.java:99)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)  at java.lang.Thread.run(Thread.java:748) ",
                    "label": 1,
                    "clusterType": "KNOWN_EVENT",
                    "risk": "HEALTHY",
                    "score": 0.0,
                    "count": 69,
                    "controlFrequencyData": [
                        4.0,
                        5.0,
                        5.0,
                        4.0,
                        5.0,
                        4.0,
                        5.0,
                        4.0,
                        2.0,
                        4.0
                    ],
                    "testFrequencyData": [
                        8.0,
                        10.0,
                        8.0,
                        20.0,
                        4.0,
                        5.0,
                        5.0,
                        4.0,
                        5.0
                    ]
                }
            ],
            "pageIndex": 0,
            "empty": false
        }
    },
    "responseMessages": []
}

**Review by kanhaiyarat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 124 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xOE341AruLnt1ZYe:-Mw4xOE341AruLnt1ZYf:b7ct7vv) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L124)):*
> ```Java
>     Integer totalClusters =
>         getLogAnalysisResult(accountId, verificationJobInstanceId, label, DeploymentLogAnalysisFilter.builder().build())
>             .size();
> ```

getLogAnalysisResult call is not required as we're calling it again in the next line. let's use the below call to figure out the totalCluster count.



_Code quote:_
```Java
getLogAnalysisResult
```
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java, line 291 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xqEe7DYYCa3T2XXU:-Mw4xqEe7DYYCa3T2XXV:b-aeppks) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java#L291)):*
> ```Java
>     assertThat(logAnalysisClusterWithCountDTO.getLogAnalysisClusterDTO().getContent()).isNotNull();
>     assertThat(logAnalysisClusterWithCountDTO.getLogAnalysisClusterDTO().getContent().size()).isEqualTo(0);
>   }
> ```

we also need to shift the existing test case methods to use the new one.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 124 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xOE341AruLnt1ZYe:-Mw50c1K0yAixshWBjc0:bv4j1x3) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L124)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

getLogAnalysisResult call is not required as we're calling it again in the next line. let's use the below call to figure out the totalCluster count.
</blockquote></details>

we cannot use that as we need Total cluster count without any filters. In the below getLogAnalysisResult call we send filters coming from user.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java, line 291 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xqEe7DYYCa3T2XXU:-Mw50wsB5kCsZc6s8DYX:bknqaml) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java#L291)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

we also need to shift the existing test case methods to use the new one.
</blockquote></details>

so currently that is not required as we still have old API. Once we phase out old API then these test cases will be shifted as it is to new API

**Review by kanhaiyarat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 124 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xOE341AruLnt1ZYe:-Mw5DqU98aoAgpyiHN75:b-562lei) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L124)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

we cannot use that as we need Total cluster count without any filters. In the below getLogAnalysisResult call we send filters coming from user.
</blockquote></details>

got it. in that case, can you check if we can make a simpler method just to get the count of the clusters.

**Review by kanhaiyarat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java, line 291 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xqEe7DYYCa3T2XXU:-Mw5E56gCYetpBVeLJvd:ba046tw) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java#L291)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

so currently that is not required as we still have old API. Once we phase out old API then these test cases will be shifted as it is to new API
</blockquote></details>

let's make sure when we deprecate it, we should be moving all the test cases to this new method.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 124 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xOE341AruLnt1ZYe:-Mw5UscD-4MyCeNfBlap:be890oo) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L124)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

got it. in that case, can you check if we can make a simpler method just to get the count of the clusters.
</blockquote></details>

that's a really good idea.....done the changes
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java, line 291 at r2](https://reviewable.io/reviews/harness/harness-core/30792#-Mw4xqEe7DYYCa3T2XXU:-Mw5Uy_i-30RM-Q7uPvg:bv3mpbu) ([raw file](https://github.com/harness/harness-core/blob/d2c093ffd2e3b1f41dd9f98f5d19481b21c76e73/300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java#L291)):*
<details><summary><i>Previously, kanhaiyarat (Kanhaiya Rathi) wrote…</i></summary><blockquote>

let's make sure when we deprecate it, we should be moving all the test cases to this new method.
</blockquote></details>

so I deprecated the old api and replicated all the existing test cases to new API keeping old API test cases as it is. We will delete those once that API is removed

**Review by kanhaiyarat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, line 182 at r3](https://reviewable.io/reviews/harness/harness-core/30792#-Mw69q8Q1Xw23KOujzbw:-Mw69q8R-zDOYmCYCUFS:bzvty3) ([raw file](https://github.com/harness/harness-core/blob/50094b5b4ca7f8a6fc380a6dad04f710294c2ba7/300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java#L182)):*
> ```Java
>     if (isEmpty(latestDeploymentLogAnalysis)) {
>       return 0;
>     }
> ```

we can directly check on the total number of clusters, rather than using getOverallLogAnalysisClusters. 
just need to confirm on behavior when the label is passed. 
Need not do the other calculations but just filter based on label if required. 
Total number of clusters can directly be calculated using the cluster field

**Review by kanhaiyarat — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 2 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30792)* status: Some of the checks are too old.

**Pull request merged**
