### PR TITLE
fix: [DEL-4617]: Metrics for number of websocket connections and number of Redis topics.

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
We are caching each websocket connection on its heartbeat ensuring that cache doesn't expire. If there is no heartbeat cache item will expire. Every 60s metrics publisher will publish current stats. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36892)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36892)

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/36892#-NAenBqB5JR9jeVIxEUy:-NAenBqB5JR9jeVIxEUz:bt62kwr) ([raw file](https://github.com/harness/harness-core/blob/6999be8759d089bcc064cf317b076e0b48fc38fc/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L24)):*
> ```Java
> @RequiredArgsConstructor(onConstructor_ = @Inject)
> public class CachedMetricsPublisher implements MetricsPublisher {
>   public static final String WEBSOCKET_CONNECTIONS_CNT = "websocket_connections_cnt";
> ```

rename this to reflect number of active delegate processes and create a new one for the websocket connections

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36892)* status: 0 of 1 approvals obtained.

**Comment by mdmilic** [comment]
trigger feature-build

**Comment by mdmilic** [comment]
trigger feature-build

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36892)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/36892#-NBR0ZKJ5MLOTbqzVFfp:-NBR0ZKJ5MLOTbqzVFfq:b58d9fn) ([raw file](https://github.com/harness/harness-core/blob/680489f6f314a0d29abe15b16a2369a22c5a29d7/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
> ```Java
> 
>   @Override
>   public void recordMetrics() {
> ```

how frequently did this gets called ? Is there a possibility that we publish same metric twice or miss some metric.

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36892)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/36892#-NAenBqB5JR9jeVIxEUy:-NBDJtaE7PF6FaydSdQE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6999be8759d089bcc064cf317b076e0b48fc38fc/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L24)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

rename this to reflect number of active delegate processes and create a new one for the websocket connections
</blockquote></details>

Done.
___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/36892#-NBR0ZKJ5MLOTbqzVFfp:-NBSU6ikEj9uTnLW2FeV:bsp7bu4) ([raw file](https://github.com/harness/harness-core/blob/680489f6f314a0d29abe15b16a2369a22c5a29d7/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

how frequently did this gets called ? Is there a possibility that we publish same metric twice or miss some metric. 
</blockquote></details>

It's called on a schedule every 60s

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 3 of 12 files at r1, 2 of 4 files at r5, 2 of 2 files at r6, 5 of 5 files at r7, 2 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36892)* status: :shipit: complete! ✓

___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/36892#-NBR0ZKJ5MLOTbqzVFfp:-NBX8Y2H5k05FLp_4kFw:bvkomoa) ([raw file](https://github.com/harness/harness-core/blob/680489f6f314a0d29abe15b16a2369a22c5a29d7/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

It's called on a schedule every 60s
</blockquote></details>

cache TTL is 90sec, so we can publish same metric twice after 60sec window in a 90sec window ? or am I missing something

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36892)* status: :shipit: complete! ✓

___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java` line 37 at r6](https://reviewable.io/reviews/harness/harness-core/36892#-NBR0ZKJ5MLOTbqzVFfp:-NBXAto98YRL9eaqO6f4:b-442osq) ([raw file](https://github.com/harness/harness-core/blob/680489f6f314a0d29abe15b16a2369a22c5a29d7/420-delegate-service/src/main/java/io/harness/metrics/impl/CachedMetricsPublisher.java#L37)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

cache TTL is 90sec, so we can publish same metric twice after 60sec window in a 90sec window ? or am I missing something
</blockquote></details>

No, that's fine, it's more like same datapoint multiple times, but that's what we actually wanted to achieve with cache. It needs to make sure the last value is kept until the next run. As long as our cache writes are idempotent (which they are), it doesn't matter how many times we called write or if we missed to call it for a bit. There might be slight inconsistency with the metric and actual world in terms that e.g. connection might die, jobRuns and reads from the cache as if connection is there, cache item expires and every subsequent jobRun shows correct number. So the metric might be few seconds off, but that's completely fine.

**Pull request merged**
