### PR TITLE
[feat]: [PIE-5759]: Support for adding axis keys during execution

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes
Issue: Enhancement was requested to provide matrix as runtime input
Change: Matrix config is now a Parameter<> field hence runtime input.
Testing: Expected behaviour on local. Automation also pass against it. @sahilhindwani-harness and I tested some flows manually on local as well.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)

### CODE REVIEW

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 7 of 15 files at r1, 1 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)* status: 15 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r1, 1 of 4 files at r2, 1 of 7 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 80 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLPBwXPEm21B1shDdc2:-NLPBwXPEm21B1shDdc3:b-81vy6c) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java#L80)):*
> ```Java
>       log.warn("Got exception while taking to enforcement service, taking default limit of 100 for maxConcurrency");
>     }
>     if (stepParameters.getStrategyConfig().getMatrixConfig().getValue() != null) {
> ```

@sahilhindwani-harness we should add some validation during execution that if runtime then fail

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 80 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLPBwXPEm21B1shDdc2:-NLVWfDeA-N0iemrdS8F:bv4f323) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sahilhindwani-harness we should add some validation during execution that if runtime then fail
</blockquote></details>

Yes @archit-harness , we will add validations for the same.
@senjucanon2 could you please add validations as we discussed in the morning

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLVZcyt-92LByehr0fK:-NLVZcyt-92LByehr0fL:b-nek701) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java#L56)):*
> ```Java
>     StrategyConfig strategyConfig = JsonPipelineUtils.read(node.toString(), StrategyConfig.class);
>     StrategyValidationUtils.validateStrategyNode(strategyConfig);
>     if (strategyConfig.getMatrixConfig().getValue() != null) {
> ```

throw exception if matrixConfig is an expression.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLVZovM54ATIjUB6qAF:-NLVZovM54ATIjUB6qAG:b-n7soqd) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L81)):*
> ```Java
>     StrategyConfig strategy = field.getStrategy();
>     if (strategy != null && containsCommandStep(field)
>         && (strategy.getMatrixConfig().getValue() != null
> ```

Add a check for `ParameterField.isNotEmpty(strategy.getMatrixConfig())`

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLV_-K00n64-OwD2Ezn:-NLV_-K00n64-OwD2Ezo:b6vc2qe) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java#L63)):*
> ```Java
>     }
>     ParameterField<Integer> maxConcurrency = null;
>     if (config.getMatrixConfig() != null && config.getMatrixConfig().getValue() != null) {
> ```

Use ParameterField.isNotEmpty instead of comparing it with null.



_Code quote:_
```Java
config.getMatrixConfig() != null 
```

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java` line 56 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLVZcyt-92LByehr0fK:-NLWO3mM2OE2RTmd3qig:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java#L56)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

throw exception if matrixConfig is an expression.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLVZovM54ATIjUB6qAF:-NLWO4HJDai5SfxDLnN0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L81)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add a check for `ParameterField.isNotEmpty(strategy.getMatrixConfig())`
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLV_-K00n64-OwD2Ezn:-NLWO4h71CZ9nFdiJIdl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyConfigPlanCreator.java#L63)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Use ParameterField.isNotEmpty instead of comparing it with null.
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 80 at r4](https://reviewable.io/reviews/harness/harness-core/41452#-NLPBwXPEm21B1shDdc2:-NLWO5AI91W1fnckY4n3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1b8117d442fcfc285e6956c298884b3e1c4a316a/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java#L80)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes @archit-harness , we will add validations for the same.
@senjucanon2 could you please add validations as we discussed in the morning
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)* status: 13 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/41452#-NLZRKfp5e8jfjMynxh0:-NLZRKfp5e8jfjMynxh1:bwnrzoo) ([raw file](https://github.com/harness/harness-core/blob/b09761d52999248912504fd32cd724a3649a7326/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java#L50)):*
> ```Java
>   private void validateStrategy(StrategyConfig strategy) {
>     if (strategy != null
>         && ((strategy.getMatrixConfig() != null && strategy.getMatrixConfig().getValue() != null)
> ```

can we add ParameterFIeld is notNull?



_Code quote:_
```Java
trategy.getMatrixConfig() !
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 81 at r5](https://reviewable.io/reviews/harness/harness-core/41452#-NLZRR9C67fu5MtESQii:-NLZRR9C67fu5MtESQij:b-3rkst5) ([raw file](https://github.com/harness/harness-core/blob/b09761d52999248912504fd32cd724a3649a7326/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L81)):*
> ```Java
>     StrategyConfig strategy = field.getStrategy();
>     if (strategy != null && containsCommandStep(field)
>         && ((strategy.getMatrixConfig() != null && strategy.getMatrixConfig().getValue() != null)
> ```

isnotNull helper not used

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)* status: 13 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/41452#-NLZRKfp5e8jfjMynxh0:-NLZYoaCCtGJIqbu-5VQ:b2zxbqp) ([raw file](https://github.com/harness/harness-core/blob/b09761d52999248912504fd32cd724a3649a7326/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add ParameterFIeld is notNull?
</blockquote></details>

Done. but i earlier i didn't use ParameterField.isNotNull as it was a very old method and already !=null was used for parallelism so just to maintain coding pattern i earlier didn't used it.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 81 at r5](https://reviewable.io/reviews/harness/harness-core/41452#-NLZRR9C67fu5MtESQii:-NLZZ2cODHL9USL_fb_U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b09761d52999248912504fd32cd724a3649a7326/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnotNull helper not used
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r4, 5 of 7 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41452)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Pull request merged**
