### PR TITLE
feat: [CDS-43075]: populate deployment type in infra save and update

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
On save and update of infra, if yaml contains deploymentType, populate it in database.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37337)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37337)

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/mapper/InfrastructureMapper.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/37337#-NBWkPqz5BD56NLj0awZ:-NBWkPqz5BD56NLj0aw_:bvso45o) ([raw file](https://github.com/harness/harness-core/blob/6ba86018d8bd6a364e625d04441d6bd22d73ba52/125-cd-nextgen/src/main/java/io/harness/cdng/infra/mapper/InfrastructureMapper.java#L48)):*
> ```Java
>       infrastructureEntity.setYaml(InfrastructureEntityConfigMapper.toYaml(infrastructureConfig));
>     }
>     if (infrastructureConfig.getInfrastructureDefinitionConfig().getDeploymentType() != null) {
> ```

we can just do
``` infrastructureEntity.setDeploymentType(infrastructureConfig.getInfrastructureDefinitionConfig().getDeploymentType())```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/mapper/InfrastructureMapper.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/37337#-NBWkPqz5BD56NLj0awZ:-NBWkXkF7y2DZnHLwE_7:bgyeedg) ([raw file](https://github.com/harness/harness-core/blob/6ba86018d8bd6a364e625d04441d6bd22d73ba52/125-cd-nextgen/src/main/java/io/harness/cdng/infra/mapper/InfrastructureMapper.java#L48)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can just do
``` infrastructureEntity.setDeploymentType(infrastructureConfig.getInfrastructureDefinitionConfig().getDeploymentType())```
</blockquote></details>

*without the if condition

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37337)* status: :shipit: complete! ✓

**Pull request merged**
