### PR TITLE
feat: [DEL-5321]: proto send task response

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
Created new REST endpoint for sending task updates from delegate to manager and appropriate proto definitions of the objects.
None of the changes affect existing delegate.jar for any delegate type as they are not built into those jars. Manager change to add new endpoint does affect existing managers, but this endpoint is not used.
Tested by running all components and manually sending dummy data from code.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)

### CODE REVIEW

**Review by xingchi-jin — DISMISSED** [review]
> Reviewed 15 of 20 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: Some of the checks are too old. Waiting on team(s): del-team.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources/k8s_task_template.yaml` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/41028#-NM0pRoO0XYNIomJRyVR:-NM0pRoPD0dwZ61rxEBS:blt9s55) ([raw file](https://github.com/harness/harness-core/blob/f8d6c248001d908369dd4538bd75a434916128f0/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources/k8s_task_template.yaml#L22)):*
> ```YAML
>               memory: "512Mi"
>           command: [ "/bin/sh" ]
>           args: [ "-c", "env; while true; do echo hello; sleep 10; echo slept; done" ]
> ```

consider making a script which finishes

**Review by raghuAtWings — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: Some of the checks are too old. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources/k8s_task_template.yaml` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/41028#-NM0pc5D5ArGwA-xSdOI:-NM0pc5D5ArGwA-xSdOJ:b-oi14ft) ([raw file](https://github.com/harness/harness-core/blob/f8d6c248001d908369dd4538bd75a434916128f0/260-delegate/src/main/java/io/harness/delegate/service/core/k8s/resources/k8s_task_template.yaml#L22)):*
> ```YAML
>               memory: "512Mi"
>           command: [ "/bin/sh" ]
>           args: [ "-c", "env; while true; do echo hello; sleep 10; echo slept; done" ]
> ```

consider making a script which finishes

**Review by mdmilic — COMMENTED** [review]
> Reviewed 1 of 20 files at r1, 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: 26 file(s) to review. 0 of 1 approvals obtained.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: 28 file(s) to review. 

___
*[`260-delegate/pr-config-delegate.yml` line 35 at r5](https://reviewable.io/reviews/harness/harness-core/41028#-NP-XwwbDfnv2XkM9Ih5:-NP-XwwbDfnv2XkM9Ih6:b-wsrqam) ([raw file](https://github.com/harness/harness-core/blob/94e5da41a590204ddae1f52d7b65c589ca609ede/260-delegate/pr-config-delegate.yml#L35)):*
> ```YAML
> installClientToolsInBackground: true
> 
> # Required for local development as manger uses self-signed cert
> ```

manager*



_Code quote:_
```YAML
manger
```

**Review by mdmilic — COMMENTED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: 28 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed 19 of 26 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: :shipit: complete! ✓

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41028)* status: :shipit: complete! ✓

**Pull request merged**
