### PR TITLE
feat: [CDS-38441]: Add base AzureWebAppTaskNG

### PR DESCRIPTION
**Pull request by abosii-harness**
## Describe your changes
Adding new delegate task for azure web app. Not used yet 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist]

## Codebase hashcheck
- Is it new task type? 
   **Yes**
- Did you add a new class which is added in kryo serialization
   **Yes**
- if yes then do not use that class in any of the delegate task payload till it makes to delegate release
  **Task will not be used in near time**
- Did you make changes to the code in a backward-compatible manner?
  **Task is not used. Enums are properly updated**
- Will the new version of the delegate receive old version task and process?
   **No**
- If new version of the manager receives response for the old task will it be able to handle it successfully?
  **Task not used yet**
- Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
  **No**
- If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
  **Yes, task not used**
- if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
  **Yes, task not used**
- Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
  **No**
- Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
  **Yes**. https://github.com/harness/harness-core/pull/33979/files#diff-29a1b3d45fbfe241ff932a64250e48833749d1e673fcf9bc8d6ab9ee62efd069

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33979)

### CODE REVIEW

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33979)* status: :shipit: complete! ✓

**Review by vlica-harness — DISMISSED** [review]

**Comment by abosii-harness** [comment]
trigger ti0

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, 6 of 10 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33979)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33979)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 9 of 18 files at r1, 3 of 10 files at r3, 2 of 4 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33979)* status: :shipit: complete! ✓

**Pull request merged**
