### PR TITLE
fix: [CDS-47250]: have added validation method for yaml passed and query params

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Have added a validation method while we update the environment info
image

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40808)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/40808#-NI2S9EM6ZnteNnFpuAG:-NI2S9EM6ZnteNnFpuAH:bqn1evk) ([raw file](https://github.com/harness/harness-core/blob/c2673c25dd1fba92567bbb7f451a47b95b1ad3e2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L90)):*
> ```Java
>   }
>   public void validateYamlOfEnv(NGEnvironmentConfig config, EnvironmentRequestDTO dto) {
>     if (!config.getNgEnvironmentInfoConfig().getOrgIdentifier().equals(dto.getOrgIdentifier())) {
> ```

what will happen if orgIdentifier is null ? This will be true for environments at org level

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/40808#-NI2SHrBB6BRTjLD5_Ot:-NI2SHrBB6BRTjLD5_Ou:b5jgn5x) ([raw file](https://github.com/harness/harness-core/blob/c2673c25dd1fba92567bbb7f451a47b95b1ad3e2/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L96)):*
> ```Java
>     }
> 
>     if (!config.getNgEnvironmentInfoConfig().getProjectIdentifier().equals(dto.getProjectIdentifier())) {
> ```

what will happen if projectIdentifier is null ? This will be true for environments at org level

**Comment by vivekkarnatiharness** [comment]
:lgtm:

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 299 at r6](https://reviewable.io/reviews/harness/harness-core/40808#-NI7pXTeA2nRE8WNbSyn:-NI7pXTeA2nRE8WNbSyo:b6dmope) ([raw file](https://github.com/harness/harness-core/blob/47d32f54d725c048508b9930cce481b6384f5c46/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L299)):*
> ```Java
>     if (StringUtils.compare(config.getNgEnvironmentInfoConfig().getIdentifier(), dto.getIdentifier()) != 0) {
>       throw new InvalidRequestException(
>           String.format("Environment Group Identifier %s passed in yaml is not same as passed in query params %s",
> ```

This should not be "Environment Group"

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 299 at r6](https://reviewable.io/reviews/harness/harness-core/40808#-NI7pXTeA2nRE8WNbSyn:-NI7q5YVCgIZXz9kHIaP:btpte1o) ([raw file](https://github.com/harness/harness-core/blob/47d32f54d725c048508b9930cce481b6384f5c46/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L299)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This should not be "Environment Group"
</blockquote></details>

fixed it

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 9 files at r2, 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40808)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40808)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40808)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/test/resources/env-org-level.yaml` line 6 at r9](https://reviewable.io/reviews/harness/harness-core/40808#-NIHzBq64f-fy_BKMxd2:-NIHzBq7BnZWeME9aN93:b32hdmp) ([raw file](https://github.com/harness/harness-core/blob/37d7612d0ee56f1a973a40f8b4edd99547628ad7/127-cd-nextgen-entities/src/test/resources/env-org-level.yaml#L6)):*
> ```YAML
>   tags: {}
>   type: Production
>   projectIdentifier: PROJECT_ID
> ```

org level env will not have project identifier in yaml

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/test/resources/env-org-level.yaml` line 6 at r9](https://reviewable.io/reviews/harness/harness-core/40808#-NIHzBq64f-fy_BKMxd2:-NII_eLQ69rEMb_ul5VW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/37d7612d0ee56f1a973a40f8b4edd99547628ad7/127-cd-nextgen-entities/src/test/resources/env-org-level.yaml#L6)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

org level env will not have project identifier in yaml 
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40808)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40808)* status: :shipit: complete! ✓

**Pull request merged**
