### PR TITLE
fix: [CDS-48409]: adding valuesPaths as File entity to get Entity Referenced By in Harness Store.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
fix: [CDS-48409]: adding valuesPaths as File entity to get Entity Referenced By in Harness Store.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42828)

[CDS-48409]: https://harness.atlassian.net/browse/CDS-48409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by acasian-harness — APPROVED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828)* status: 15 file(s) to review. 1 of 2 approvals obtained.  (waiting on @abhinavsingh1196)

**Review by ivan-83 — CHANGES_REQUESTED** [review]
There is one comment that needs to be addressed all other looks good to me.

> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828#-:-NM9LJE--OVOdDeqDia_:b4hieg)* status: 15 file(s) to review. 1 change requests. 1 of 2 approvals obtained.  (waiting on @abhinavsingh1196)

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/utils/HarnessStoreManifestVisitorUtils.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/42828#-NM9KTd37Fd7Q1Cpf278:-NM9KTd58KDnGkP-zfs9:b5d8ief) ([raw file](https://github.com/harness/harness-core/blob/125554f3982b52156c5e25f1b5b37dc6e1e61c64/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/utils/HarnessStoreManifestVisitorUtils.java#L29)):*
> ```Java
> import java.util.Set;
> 
> public class HarnessStoreManifestVisitorUtils {
> ```

We already have io.harness.cdng.visitor.helpers.store.HarnessStoreVisitorHelper, 
Just add your new method to the existing Helper, move the common code to separate method/s and we are good.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828#-:-NM9g3q62JRxzOuFYz7t:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.  (waiting on @abhinavsingh1196)

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Comment by GoelPratyush99** [comment]
trigger ti0

**Comment by GoelPratyush99** [comment]
trigger ti2

**Review by acasian-harness — APPROVED** [review]
> Reviewed 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828#-:-NM9miRf8AmbqkOZQbjd:bnfp4nl)* status: 1 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42828)* status: :shipit: complete! ✓

**Pull request merged**
