### PR TITLE
feat: [PL-39089]: Added secret usage creation event for connector test

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
This PR adds the support to send secret usage events for connector test events.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49141)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 16 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49141)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorEntityReferenceHelper.java` line 381 at r3](https://reviewable.io/reviews/harness/harness-core/49141#-NavHXtpAoE9CZvUs54X:-NavHXtpAoE9CZvUs54Y:bri532v) ([raw file](https://github.com/harness/harness-core/blob/dee862187952065281d0411c3be55e539a524208/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorEntityReferenceHelper.java#L381)):*
> ```Java
> 
>     secrets.forEach((key, value) -> {
>       if (isNotEmpty(value.getIdentifier())) { // check for a better condition (eg- cert does not have any identifiers)
> ```

Why is this required?

**Comment by tiwaritejas** [comment]
trigger uts

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49141)* status: 18 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorEntityReferenceHelper.java` line 381 at r3](https://reviewable.io/reviews/harness/harness-core/49141#-NavHXtpAoE9CZvUs54X:-NbJIId_CHnTGk0i5yHa:b-bb5l5d) ([raw file](https://github.com/harness/harness-core/blob/dee862187952065281d0411c3be55e539a524208/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorEntityReferenceHelper.java#L381)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why is this required?
</blockquote></details>

It was added for some testing. Removed it.

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger ut7

**Comment by tiwaritejas** [comment]
trigger ut7

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49141)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
