### PR TITLE
feat: [CDS-45548]: Implement terragrunt plan task NG

### PR DESCRIPTION
**Pull request by abosii-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40793)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger codeformat

**Comment by vlica-harness** [comment]
trigger smartchecks

**Comment by vlica-harness** [comment]
trigger smartchecks

**Comment by vlica-harness** [comment]
trigger smartchecks

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 20 of 36 files at r1, 2 of 26 files at r2, 25 of 26 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40793)* status: 46 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java` line 106 at r7](https://reviewable.io/reviews/harness/harness-core/40793#-NImG4_16us4TlZS3jyn:-NImG4_16us4TlZS3jyo:b-e9f76u) ([raw file](https://github.com/harness/harness-core/blob/07e7e8167a7c74748edc023db6e1ca2d29c41698/930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java#L106)):*
> ```Java
>   }
> 
>   public PlanJsonLogOutputStream getPlanJsonLogOutputStream() {
> ```

Not sure if we need that method that only creates an object and is is used in only one place.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/files/GitStoreDownloadService.java` line 69 at r7](https://reviewable.io/reviews/harness/harness-core/40793#-NImL8f36OT25D9su8-f:-NImL8f45nQGLJ08nopS:b-5txhtf) ([raw file](https://github.com/harness/harness-core/blob/07e7e8167a7c74748edc023db6e1ca2d29c41698/930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/files/GitStoreDownloadService.java#L69)):*
> ```Java
>     log.info("Downloading files {} from git to {}", gitStoreConfig.getPaths(), outputDirectory);
>     logCallback.saveExecutionLog(format("Downloading files %s from git %s to directory %s", gitStoreConfig.getPaths(),
>         getLoggableGitSrc(gitStoreConfig), getLoggablePath(outputDirectory)));
> ```

Not sure it make sense to log partial path, it may be more useful in some scenario to have full path.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/files/GitStoreDownloadService.java` line 183 at r7](https://reviewable.io/reviews/harness/harness-core/40793#-NImNntp4Sk4_EgMMuMJ:-NImNntp4Sk4_EgMMuMK:byl49d8) ([raw file](https://github.com/harness/harness-core/blob/07e7e8167a7c74748edc023db6e1ca2d29c41698/930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/files/GitStoreDownloadService.java#L183)):*
> ```Java
>   }
> 
>   private static String getLoggableGitSrc(GitStoreDelegateConfig storeDelegateConfig) {
> ```

Do we need it to be static?

**Comment by vlica-harness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java` line 106 at r7](https://reviewable.io/reviews/harness/harness-core/40793#-NImG4_16us4TlZS3jyn:-NImZF_R6kLqiIRcke4O:b-cvgi27) ([raw file](https://github.com/harness/harness-core/blob/07e7e8167a7c74748edc023db6e1ca2d29c41698/930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/TerragruntTaskService.java#L106)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Not sure if we need that method that only creates an object and is is used in only one place.
</blockquote></details>

this was moved intentionally to a method just because it would be difficult to stub this object for unit tests.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40793)* status: 46 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/files/GitStoreDownloadService.java` line 183 at r7](https://reviewable.io/reviews/harness/harness-core/40793#-NImNntp4Sk4_EgMMuMJ:-NImdOb13fu9VxUpQYfh:blyxqfb) ([raw file](https://github.com/harness/harness-core/blob/07e7e8167a7c74748edc023db6e1ca2d29c41698/930-delegate-tasks/src/main/java/io/harness/delegate/task/terragrunt/files/GitStoreDownloadService.java#L183)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

why not to be, it's used as a utility method. 
</blockquote></details>

but it is private... we use it only in this class as instance method

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 26 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40793)* status: 46 file(s) to review. 1 of 2 approvals obtained.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 20 of 36 files at r1, 26 of 26 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40793)* status: :shipit: complete! ✓

**Pull request merged**
