### PR TITLE
feat: [PIE-4845]: Support for multiple environment/infra in NG execution

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37079)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37079)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/config.yml` line 207 at r2](https://reviewable.io/reviews/harness/harness-core/37079#-NBAzhZv2l6A6avCdfA_:-NBAzhZw2wxIMoKXrJyD:blfyzc8) ([raw file](https://github.com/harness/harness-core/blob/d680f40e21a9d3d5c99cbe449e2eec23c7a36ded/120-ng-manager/config.yml#L207)):*
> ```YAML
> gitSyncServerConfig:
>   connectors:
>     - port: 13003
> ```

is this expected ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/37079#-NBB2Cax9X97dU_szDJu:-NBB2Cax9X97dU_szDJv:b-arxprz) ([raw file](https://github.com/harness/harness-core/blob/d680f40e21a9d3d5c99cbe449e2eec23c7a36ded/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java#L195)):*
> ```Java
>       List<String> infraIdentifierList = new ArrayList<>();
> 
>       if (ParameterField.isBlank(environmentV2.getInfrastructureDefinition())) {
> ```

should we not check for environmentV2.getInfraDefinitions to be not blank here ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37079)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 7 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37079)* status: :shipit: complete! ✓

**Pull request merged**
