### PR TITLE
fix: [PLG-1475]: Added support for ga client id tracking

### PR DESCRIPTION
**Pull request by devinder-harness**
## Describe your changes
Added support for ga client id tracking
https://harness.atlassian.net/browse/PLG-1475
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37878)

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/37878#-NCvDu3Q7ONn0Yaj4W7e:-NCvDu3Q7ONn0Yaj4W7f:bhjz8k0) ([raw file](https://github.com/harness/harness-core/blob/bd591c657d543f6b718461c7e4dafce72376ec4b/920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java#L92)):*
> ```Java
>   @PublicApi
>   public RestResponse<UserInfo> completeSignupInvite(@PathParam("token") String token,
>       @QueryParam("referer") String referer, @QueryParam("gaClientId") String gaClientId) {
> ```

My suggestion would be added those as signupDTO/OauthDTO as what UTMinfo do instead of in the query parameter, since we only want to track in the telemetry.

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/37878#-NCvDu3Q7ONn0Yaj4W7e:-NCz81do275gY2rdsYu4:blyzsdz) ([raw file](https://github.com/harness/harness-core/blob/bd591c657d543f6b718461c7e4dafce72376ec4b/920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java#L92)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

My suggestion would be added those as signupDTO/OauthDTO as what UTMinfo do instead of in the query parameter, since we only want to track in the telemetry.
</blockquote></details>

The query string, as part of the URL (a URI), it's there to identify which resource you are posting or patching and used to specify the exact data requested, whereas this is not our case. 
Therefore we should use content body to sent those information, since the content body is used for the data that is to be uploaded/downloaded to/from the server

**Review by pranil-harness — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: :shipit: complete! ✓

**Review by Xin-Harness — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/37878#-NCvDu3Q7ONn0Yaj4W7e:-ND8VApt3qpdFPOoRzzT:bwysbzr) ([raw file](https://github.com/harness/harness-core/blob/bd591c657d543f6b718461c7e4dafce72376ec4b/920-ng-signup/src/main/java/io/harness/signup/resources/SignupResource.java#L92)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

The query string, as part of the URL (a URI), it's there to identify which resource you are posting or patching and used to specify the exact data requested, whereas this is not our case. 
Therefore we should use content body to sent those information, since the content body is used for the data that is to be uploaded/downloaded to/from the server

</blockquote></details>

We should also avoid add queryParam in completeSignupInvite, instead those information could be stored in UserInvite in the database like all the other attribute do, in the cg manager when doing the real complete signup, we should pass referer and gaClientId through userinfo. 
___
*[`920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java` line 281 at r2](https://reviewable.io/reviews/harness/harness-core/37878#-ND8WtJK0QDQxfVsnlCo:-ND8WtJK0QDQxfVsnlCp:bazv9y4) ([raw file](https://github.com/harness/harness-core/blob/846e4c628bef18dbc018df2d877550a0832261c3/920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java#L281)):*
> ```Java
>     @Override
>     public UserInfo completeSignupInvite(String token, String referer, String gaClientId) {
>         if (DeployVariant.isCommunity(deployVersion)) {
> ```

Please also work on coding formatter, there is an automatic coding formatter tool build in to help format the entire file.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]

**Review by Xin-Harness — APPROVED** [review]

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed 5 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by pranil-harness — DISMISSED** [review]

**Review by pranil-harness — DISMISSED** [review]

**Comment by devinder-harness** [comment]
trigger messagecheck

**Comment by devinder-harness** [comment]
trigger authorcheck

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 7 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: Some of the checks are too old. 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java` line 56 at r6](https://reviewable.io/reviews/harness/harness-core/37878#-NEZ5OdJ3xFLI9PYzOFJ:-NEZ5OdJ3xFLI9PYzOFK:b-3wl37o) ([raw file](https://github.com/harness/harness-core/blob/207e24c8dd6a2b7d39638a37966d366bc3c13792/970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java#L56)):*
> ```Java
>   public static final String MODULE_TYPE = "moduleType";
>   public static final String REFERER = "referer";
>   public static final String GA_CLIENT_ID = "ga_client_id";
> ```

Its not a common constant for NG. We can create a new class specific to License service

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: Some of the checks are too old. 6 file(s) to review.

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 3 of 7 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: Some of the checks are too old.

**Review by thomas-grasman — DISMISSED** [review]
> Reviewed 3 of 7 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: Some of the checks are too old.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: Some of the checks are too old.

**Review by vtxorxwitty — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 3 of 7 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37878)* status: 1 of 2 approvals obtained.

**Pull request merged**
