### PR TITLE
feat: [SRM-14334]: Added request composite slo

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46579)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46579)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/46579#-NTRrwvT5IjGsjID86Pn:-NTRrwvT5IjGsjID86Po:b-fek5gc) ([raw file](https://github.com/harness/harness-core/blob/12ffbe787aca063073819aefb5e8afc1440922bf/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java#L29)):*
> ```Java
>   }
> 
>   public static SLIValue getSLIValue(SLIRecord currentSLIRecord, SLIRecord prevSLIRecord) {
> ```

We should rename it to getRunningCountDifference (getSLIValue doesn't convey much)
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 114 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTUjESO0UQNvvIdsMdJ:-NTUjESO0UQNvvIdsMdK:bcb8dv2) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L114)):*
> ```Java
>           objectivesDetailSLIMissingDataTypeMap, sloVersion, runningGoodCount, runningBadCount, verificationTaskId);
>     }
>     return getWindowCompositeSLORecordsFromSLIsDetails(serviceLevelObjectivesDetailCompositeSLORecordMap,
> ```

nit: can put this in else for better readability
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java` line 281 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTUm53E6F1h36_BoboL:-NTUm53E6F1h36_BoboM:bbo8km4) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L281)):*
> ```Java
>                                         .build();
>       SimpleServiceLevelObjective simpleServiceLevelObjective =
>           (SimpleServiceLevelObjective) serviceLevelObjectiveV2Service.getEntity(
> ```

why can't we make this method in serviceLevelObjectiveV2 Service: getEntityBySLODetails(ServiceLevelObjectiveDetails objectiveDetails)
we will not need to spill over this logic outside.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTUlOiI1L1R8NnsZT3t:-NTUlOiI1L1R8NnsZT3u:b-vc17if) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java#L66)):*
> ```Java
>         (CompositeServiceLevelObjective) serviceLevelObjectiveV2Service.get(sloId);
>     SLIEvaluationType evaluationType =
>         serviceLevelObjectiveV2Service
> ```

I think we decided we will move the slievaluation type to abstractslolevel

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 2 of 5 files at r2, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46579)* status: 5 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/config-delegate.yml` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTT_qAV0U0cGP0roNLz:-NTT_qAW2qXYBvTetldh:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/260-delegate/config-delegate.yml#L19)):*
> ```YAML
> clientToolsDownloadDisabled: false
> installClientToolsInBackground: true
> isLocalNgDelegate: true
> ```

remove



_Code quote:_
```YAML
isLocalNgDelegate: true
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTXpKFG8EHZgwKV8_Hq:-NTXpKFG8EHZgwKV8_Hr:b7tp999) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java#L29)):*
> ```Java
>   }
> 
>   public static SLIValue getSLIValue(SLIRecord currentSLIRecord, SLIRecord prevSLIRecord) {
> ```

why do we have this here? we can have this in SLI Record class



_Code quote:_
```Java
public static SLIValue getSLIValue(SLIRecord currentSLIRecord, SLIRecord prevSLIRecord)
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTXqaalAvl7vja6Z83Z:-NTXqaam35D8OvVNMBve:bwwjyo6) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java#L79)):*
> ```Java
>   private double runningBadCount;
>   private double runningGoodCount;
>   private Map<String, SLIRecord> scopedIdentifierSLIRecordMap;
> ```

Why are we adding the whole SLIRecord, is SLI state not sufficient?



_Code quote:_
```Java
SLIRecord
```

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46579)* status: 5 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/config-delegate.yml` line 19 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTT_qAV0U0cGP0roNLz:-NTY3CaT594BwQIkwCKH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/260-delegate/config-delegate.yml#L19)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/46579#-NTRrwvT5IjGsjID86Pn:-NTY3DRvE75ONitDfkiR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12ffbe787aca063073819aefb5e8afc1440922bf/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java#L29)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We should rename it to getRunningCountDifference (getSLIValue doesn't convey much)
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTXpKFG8EHZgwKV8_Hq:-NTY3EuW358Hlh4-H1R_:b-b3gqih) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIValue.java#L29)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why do we have this here? we can have this in SLI Record class
</blockquote></details>

Changed Its name as per deepak's comment but since this is essentially a SLIValue constructor thats why I kept it in here.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java` line 79 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTXqaalAvl7vja6Z83Z:-NTY3_NWCOMBe11slp7d:b-u7qvui) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java#L79)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Why are we adding the whole SLIRecord, is SLI state not sufficient?
</blockquote></details>

We need 5 fields from SLIRecord... 1. timestamp, 2. sliId, 3. runningGoodCount, 4. runningBadCount, 5. SLIState. Thats Why I added full SLIRecord.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java` line 281 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTUm53E6F1h36_BoboL:-NTY40A2-OvdevMjQqPL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordServiceImpl.java#L281)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

why can't we make this method in serviceLevelObjectiveV2 Service: getEntityBySLODetails(ServiceLevelObjectiveDetails objectiveDetails)
we will not need to spill over this logic outside.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/46579#-NTUlOiI1L1R8NnsZT3t:-NTY41G61-jPF9RL2XKy:b2s98jh) ([raw file](https://github.com/harness/harness-core/blob/2681536734063c0310c013b82544389744bd136e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java#L66)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

I think we decided we will move the slievaluation type to abstractslolevel
</blockquote></details>

Will Do in a separate PR.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 1 of 5 files at r2, 2 of 4 files at r4, 6 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46579)* status: 1 change requests. 3. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 1 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46579#-:-NTYZJgxBhoapXSzJTic:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
