### PR TITLE
feat: [GTM-705]: Community version will default to community license

### PR DESCRIPTION
**Pull request by allenthom**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32682)

### CODE REVIEW

**Comment by allenthom** [comment]
trigger messagecheck

**Review by nanaxuHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32682)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32682#-N0qaQ2lB6R_RBnFk7dT:-N0qaQ2m1RotUMsQLgBM:b-g63qa6) ([raw file](https://github.com/harness/harness-core/blob/404493b123efd3de4fc164943265645defbe0a07/925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java#L253)):*
> ```Java
>     if (licenseInfo == null) {
>       Edition edition = Edition.FREE;
>       // if licenseInfo is null, and it is on prem + community, fallback on community edition instead of free
> ```

just wondering why for on-prem, we fall back to Community? on-prem should not be bounded to license, is it?

**Review by nanaxuHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32682)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java` line 255 at r1](https://reviewable.io/reviews/harness/harness-core/32682#-N0qajXC7XmV3V-Q1epS:-N0qajXC7XmV3V-Q1epT:b-2jufuy) ([raw file](https://github.com/harness/harness-core/blob/404493b123efd3de4fc164943265645defbe0a07/925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java#L255)):*
> ```Java
>       // if licenseInfo is null, and it is on prem + community, fallback on community edition instead of free
>       if (DeployMode.isOnPrem(System.getenv().get(DEPLOY_MODE))
>           && DeployVariant.isCommunity(System.getenv().get(DEPLOY_VERSION))) {
> ```

is it `&&` here or `||`?

**Comment by allenthom** [comment]
*[`925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/32682#-N0qaQ2lB6R_RBnFk7dT:-N0qfkoU-jlZvLXcTsKP:bk1dexq) ([raw file](https://github.com/harness/harness-core/blob/404493b123efd3de4fc164943265645defbe0a07/925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java#L253)):*
<details><summary><i>Previously, nanaxuHarness (Nana Xu) wrote…</i></summary><blockquote>

just wondering why for on-prem, we fall back to Community? on-prem should not be bounded to license, is it?
</blockquote></details>

The current enforcement framework limits features based on license. On-prem not having a license is something that can be implemented in the future.

**Comment by allenthom** [comment]
*[`925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java` line 255 at r1](https://reviewable.io/reviews/harness/harness-core/32682#-N0qajXC7XmV3V-Q1epS:-N0qg5_RDphjkEF31lAv:b-wjgj6d) ([raw file](https://github.com/harness/harness-core/blob/404493b123efd3de4fc164943265645defbe0a07/925-enforcement-service/src/main/java/io/harness/enforcement/services/impl/EnforcementServiceImpl.java#L255)):*
<details><summary><i>Previously, nanaxuHarness (Nana Xu) wrote…</i></summary><blockquote>

is it `&&` here or `||`?
</blockquote></details>

I believe it should be a `&&` because the deploy mode is "on prem", but the deploy version can be "Community" or "SAAS"(Enterprise). So we want to default to Community edition only when it is both  on prem AND community.

**Review by nanaxuHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32682)* status: :shipit: complete! ✓

**Review by hekimoglu010 — APPROVED** [review]

**Review by pranil-harness — APPROVED** [review]

**Pull request merged**
