### PR TITLE
[feat]: [PIE-8309]: Account setting added for independent InputSets

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added Account setting for creating remote inputs in different repo compared to pipelines. Also, added validations for repo check as per account settings.
Have tested out the following:

1. Creation in same repo with AccountSetting on
2. Creation in same repo with AccountSetting off
3. Creation in different repo with AccountSetting on
4. Creation in different repo with AccountSetting off

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOOQv7S3bW_Vtk-TLQ_:-NOOQv7S3bW_Vtk-TLQa:b-durixv) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java#L22)):*
> ```Java
>   public static final String TRUE_VALUE = "true";
>   public static final String GIT_CLIENT_ENABLED_SETTING = "enable_git_commands";
>   public static final String INDEPENDENT_INPUT_SET_SETTING = "independent_inputSets";
> ```

everything should be snake case in the name

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOORD7m7UqiZ0nllUVV:-NOORD7m7UqiZ0nllUVW:b-3odnpu) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java#L210)):*
> ```Java
>   }
> 
>   public boolean isIndependentInputSetEnabledInSettings(String accountId) {
> ```

this method name isn't clear on what it actually means

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOORUkM5MCMu2n90e4u:-NOORUkM5MCMu2n90e4v:b-19daen) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L111)):*
> ```Java
>       InputSetValidationHelper.checkForPipelineStoreType(inputSetEntity, pipelineService);
>     }
>     validateIndependentInputSetSetting(inputSetEntity);
> ```

we don't need to mention anything in the method name here. For us, its a validation calls, thats it. Internally then we can do validations based on its remote or INLINE.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 9 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOOQv7S3bW_Vtk-TLQ_:-NOOUlO_0zKIr66aYleW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

everything should be snake case in the name
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOORD7m7UqiZ0nllUVV:-NOOXf7n5CPFt3Lznmrg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java#L210)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this method name isn't clear on what it actually means
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOORUkM5MCMu2n90e4u:-NOOYwfH4mG_-l6xKLdg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L111)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we don't need to mention anything in the method name here. For us, its a validation calls, thats it. Internally then we can do validations based on its remote or INLINE.
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/44034#-NOOQoQNDX_riCZo5Jax:-NOOUihF6ExgPCQzOcoC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e4a2fa36627082fc1e9585af1e281ebeeec1874/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is this separate? It should be part of Git Experience only
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 685 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOP9oE6-x9rcC-RZV9w:-NOP9oE6-x9rcC-RZV9x:b-97c6le) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L685)):*
> ```Java
>     if (EmptyPredicate.isNotEmpty(pipelineRepo) && EmptyPredicate.isNotEmpty(inputSetRepo)
>         && pipelineRepo.equals(inputSetRepo)) {
>       log.info("Input-Set is created in the same repo as the pipeline.");
> ```

Log line can be better here

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 687 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOP9zCv7zeXTnlV62RH:-NOP9zCv7zeXTnlV62RI:b-3fuycq) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L687)):*
> ```Java
>       log.info("Input-Set is created in the same repo as the pipeline.");
>     } else {
>       throw new InvalidRequestException("Input-Set has to be in the same repo as the pipeline.");
> ```

put better explanation and error exceptions here in terms of account level setting

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOPCP2J-m3YyzKgS-aw:-NOPCP2K40CPbuXgcfyt:bhgtin) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java#L113)):*
> ```Java
> 
>   public PipelineEntity getPipelineMetadata(PMSPipelineService pmsPipelineService, String accountId,
>       String orgIdentifier, String projectIdentifier, String pipelineIdentifier) {
> ```

this method already doesnt exist isnt?



_Code quote:_
```Java
  public PipelineEntity getPipelineMetadata(PMSPipelineService pmsPipelineService, String accountId,
      String orgIdentifier, String projectIdentifier, String pipelineIdentifier) {
```

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 9 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOPCP2J-m3YyzKgS-aw:-NOh2HpE3eKEFSdyOWv-:bhkpefd) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this method already doesnt exist isnt?
</blockquote></details>

From inputset layer, the get pipeline metadata isnt there. While checking, found out that the get pipeline metadata flow is broken. When i tried to fix it as part of this pr, it became to many file changes and out of this pr scope. Hence have created this method call from input set service to get pipeline metadata.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 685 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOP9oE6-x9rcC-RZV9w:-NOh4aQUASzCJ8H8iAIC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L685)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Log line can be better here
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 687 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOP9zCv7zeXTnlV62RH:-NOh4abyE7f6z0lvrzzL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L687)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

put better explanation and error exceptions here in terms of account level setting
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/44034#-NOPCP2J-m3YyzKgS-aw:-NOhDDa16_JKWfHN_osm:b4qozj0) ([raw file](https://github.com/harness/harness-core/blob/7261d5363426fdb3e9129d64723eb2f8ea5d4e7a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/InputSetValidationHelper.java#L113)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

From inputset layer, the get pipeline metadata isnt there. While checking, found out that the get pipeline metadata flow is broken. When i tried to fix it as part of this pr, it became to many file changes and out of this pr scope. Hence have created this method call from input set service to get pipeline metadata.
</blockquote></details>

Discussed offline, first a separate pr for handling getPipelineMetadata 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/44034#-NOhBvT50Rl9l4OyqEOB:-NOhBvT50Rl9l4OyqEOC:bsnbdsa) ([raw file](https://github.com/harness/harness-core/blob/6fb943758b18bf68504cdcb76aff496542f9ba1a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L110)):*
> ```Java
>     InputSetValidationHelper.validateInputSet(this, inputSetEntity, hasNewYamlStructure);
>     if (!isOldGitSync) {
>       InputSetValidationHelper.checkForPipelineStoreType(inputSetEntity, pipelineService);
> ```

Can we reduce the pipeline metadata call as its happening in checkForPipelineStore and in validateInputSetSetting

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 1 of 6 files at r3, 1 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 12 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 110 at r5](https://reviewable.io/reviews/harness/harness-core/44034#-NOhBvT50Rl9l4OyqEOB:-NOhc_n3AcvlcGeKpJ8M:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6fb943758b18bf68504cdcb76aff496542f9ba1a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L110)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we reduce the pipeline metadata call as its happening in checkForPipelineStore and in validateInputSetSetting
</blockquote></details>

done

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 690 at r7](https://reviewable.io/reviews/harness/harness-core/44034#-NOhdkOT9UdGUNMEa-FB:-NOhdkOT9UdGUNMEa-FC:b-uikgi6) ([raw file](https://github.com/harness/harness-core/blob/b975c26b178f47e816b5b05bdd27bcc137e4f9d1/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L690)):*
> ```Java
>     } else {
>       throw new HintException(HINT_INPUT_SET_ACCOUNT_SETTING,
>           new InvalidRequestException("Input-Set has to be in the same repo as the pipeline."));
> ```

We need to do better in terms of error messages here

Suggestion:
Error Message: "Input-set repository <> doesn't match linked pipeline repository <>"
Explanation: "As per the account level setting : <>, the input set repository is not same as the linked pipeline repository"
Hint: "1) Please check if account level setting is expected to be enabled. 2) Please check if requested input-set is in same repository as the linked pipeline."

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 151 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhjH9aBaUwWPSPwKx3:-NOhjH9aBaUwWPSPwKx4:b-832omn) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/980-commons/src/main/java/io/harness/exception/HintException.java#L151)):*
> ```Java
> 
>   public static final String HINT_INPUT_SET_ACCOUNT_SETTING =
>       "1) Please check if account level setting is expected to be enabled. 2) Please check if requested input-set is in same repository as the linked pipeline.";
> ```

It shouldn't be logged in same line. There should be a new-line char after 1st point similar to what we do in our gitx error handling.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 687 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhkt572VtPc5Vx0KRE:-NOhkt572VtPc5Vx0KRF:b-ybb5e7) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L687)):*
> ```Java
>     } else {
>       throw NestedExceptionUtils.hintWithExplanationException(HINT_INPUT_SET_ACCOUNT_SETTING,
>           INPUT_SET_ACCOUNT_SETTING_EXPLANATION,
> ```

naming convention is messed up. For hints, we say "HINT_INPUT_..." , for explanation, we say "INPUT_SET..._EXPLANATION"

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 99 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhl1jDBA7G1rsHs8ra:-NOhl1jDBA7G1rsHs8rb:bqulmj9) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L99)):*
> ```Java
>   private static final String REPO_LIST_SIZE_EXCEPTION = "The size of unique repository list is greater than [%d]";
>   private static final String INPUT_SET_ACCOUNT_SETTING_EXPLANATION =
>       "As per the account level setting: Enforce same repo for Pipeline and InputSets, the input set repository is not same as the linked pipeline repository";
> ```

lets put some identifiers around the setting name. Here setting name is like a sentence, so someone may get confused.

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 4 of 6 files at r3, 1 of 3 files at r6, 4 of 5 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 690 at r7](https://reviewable.io/reviews/harness/harness-core/44034#-NOhdkOT9UdGUNMEa-FB:-NOhhGgV3q5XLhouSuTs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b975c26b178f47e816b5b05bdd27bcc137e4f9d1/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L690)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We need to do better in terms of error messages here

Suggestion:
Error Message: "Input-set repository <> doesn't match linked pipeline repository <>"
Explanation: "As per the account level setting : <>, the input set repository is not same as the linked pipeline repository"
Hint: "1) Please check if account level setting is expected to be enabled. 2) Please check if requested input-set is in same repository as the linked pipeline."
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 687 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhkt572VtPc5Vx0KRE:-NOhnaZs8-1RFLPlHNpL:b7pz6vo) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L687)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

naming convention is messed up. For hints, we say "HINT_INPUT_..." , for explanation, we say "INPUT_SET..._EXPLANATION"
</blockquote></details>

I have followed the same, for hint, HINT_INPUT_SET_ACCOUNT_SETTING and for explanation, INPUT_SET_ACCOUNT_SETTING_EXPLANATION

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 687 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhkt572VtPc5Vx0KRE:-NOhpAiQ0yqaX7a1UXcL:b-1jlpgc) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L687)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

I have followed the same, for hint, HINT_INPUT_SET_ACCOUNT_SETTING and for explanation, INPUT_SET_ACCOUNT_SETTING_EXPLANATION
</blockquote></details>

I meant to highlight that its wrong. We are having 2 different conventions, why so? Both should say "HINT_" and "EXPLANATION_" or both should end with the definite prefix.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 2 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/HintException.java` line 151 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhjH9aBaUwWPSPwKx3:-NOhoHUh3syvLCyklzti:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/980-commons/src/main/java/io/harness/exception/HintException.java#L151)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It shouldn't be logged in same line. There should be a new-line char after 1st point similar to what we do in our gitx error handling.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 99 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhl1jDBA7G1rsHs8ra:-NOho42oCbNBhzv6F0IZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L99)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets put some identifiers around the setting name. Here setting name is like a sentence, so someone may get confused.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 687 at r8](https://reviewable.io/reviews/harness/harness-core/44034#-NOhkt572VtPc5Vx0KRE:-NOi1qke9KzH6Zv8PgrP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0c1cf0631ae0b6000cee8a24032e6cd4bf78f5ed/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L687)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I meant to highlight that its wrong. We are having 2 different conventions, why so? Both should say "HINT_" and "EXPLANATION_" or both should end with the definite prefix.
</blockquote></details>

Done.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034#-:-NOi8Wb_1eCiFz1tdO5l:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger ft1, ft2

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 3 files at r2, 4 of 6 files at r3, 1 of 3 files at r6, 4 of 5 files at r7, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44034)* status: :shipit: complete! ✓

**Pull request merged**
