### PR TITLE
feat: [CDS-82924]: Adding metric for active nodeExecution count per m…

### PR DESCRIPTION
**Pull request by Y0709**
…odule and stepType

Verified the mterics locally 

Screenshot 2023-11-17 at 1 17 44 PM

Screenshot 2023-11-10 at 5 53 10 PM

Screenshot 2023-11-10 at 5 52 58 PM

Index used by query -- status_idx

Time taken by query on QA -- 0.65 to 0.7 sec
Time taken by query in prod2 --  0.7 to 0.8sec

Also tested new added cache verified its use to make count of keys that are not present in current query result to be 0 

Screenshot 2023-11-20 at 1 16 38 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: Some of the checks are too old. 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/55300#-NjGMwfdBFuKlmbFnMVA:-NjGMwfdBFuKlmbFnMVB:bia8mvd) ([raw file](https://github.com/harness/harness-core/blob/8f1aad0631154b9559c072e4c9b5b583b8fb7717/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L138)):*
> ```Java
>   }
> 
>   public List<ExecutionCountWithAccountResult> aggregateRunningExecutionCountPerModule() {
> ```

I read more through it -> the aggregation happens on mongo in memory but now as our set of records are same thus we can use facet of aggregations example - ConnectorStatisticsHelper

More details - https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: 17 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/55300#-NjGMwfdBFuKlmbFnMVA:-NjRFV6e7jWORvmolYVL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/949c8534ce9848e53d36a6fa1e322a702dc4ccea/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L138)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

I read more through it -> the aggregation happens on mongo in memory but now as our set of records are same thus we can use facet of aggregations example - ConnectorStatisticsHelper

More details - https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, 7 of 12 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/55300#-NjRSK5z3oYdRAiuaPYO:-NjRSK5z3oYdRAiuaPYP:b-nwswbn) ([raw file](https://github.com/harness/harness-core/blob/8b9052219587ffef986831d2e6703f00fbb89170/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionReadHelper.java#L133)):*
> ```Java
>   }
> 
>   public List<ExecutionStatistics> aggregateRunningExecutionCount() {
> ```

can we send only one result from here as it will always be one

**Review by archit-harness — COMMENTED** [review]
> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java` line 308 at r6](https://reviewable.io/reviews/harness/harness-core/55300#-NjfisvJ7zPC88YUgz-N:-NjfisvJ7zPC88YUgz-O:b-p8i6f2) ([raw file](https://github.com/harness/harness-core/blob/696932bd8a2cb43462a618bdc5875cc4241d9c44/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java#L308)):*
> ```Java
>     return Caffeine.newBuilder()
>         .maximumSize(1000)
>         .expireAfterWrite(7, TimeUnit.DAYS)
> ```

we can remove this?



_Code quote:_
```Java
        .maximumSize(1000)
        .expireAfterWrite(7, TimeUnit.DAYS)
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/55300#-NjfjdvLDnHvqYQnVooF:-NjfjdvLDnHvqYQnVooG:b-bk7d6c) ([raw file](https://github.com/harness/harness-core/blob/696932bd8a2cb43462a618bdc5875cc4241d9c44/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java#L80)):*
> ```Java
>       if (!currentAccountIds.contains(accountId)) {
>         populateMetric(
>             PmsEventMonitoringConstants.ACCOUNT_ID, accountId, NODE_EXECUTION_ACTIVE_EXECUTION_COUNT_METRIC_NAME, 0);
> ```

move as a private method to push zero type values so code is not complex
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java` line 84 at r6](https://reviewable.io/reviews/harness/harness-core/55300#-NjfjbZNDPiIZo5xSxKE:-NjfjbZNDPiIZo5xSxKF:bj1avmx) ([raw file](https://github.com/harness/harness-core/blob/696932bd8a2cb43462a618bdc5875cc4241d9c44/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java#L84)):*
> ```Java
>     }
> 
>     Set<String> cachedModules = metricsLoadingCache.get("modules");
> ```

use constants in above class

**Review by Y0709 — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java` line 308 at r6](https://reviewable.io/reviews/harness/harness-core/55300#-NjfisvJ7zPC88YUgz-N:-NjggryuAY0bzPj5DKZ-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/696932bd8a2cb43462a618bdc5875cc4241d9c44/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java#L308)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we can remove this?
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java` line 80 at r6](https://reviewable.io/reviews/harness/harness-core/55300#-NjfjdvLDnHvqYQnVooF:-NjggrFE5bHFkhQWKAm6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/696932bd8a2cb43462a618bdc5875cc4241d9c44/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

move as a private method to push zero type values so code is not complex
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java` line 84 at r6](https://reviewable.io/reviews/harness/harness-core/55300#-NjfjbZNDPiIZo5xSxKE:-NjggrUqASpjWyGsaxrQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/696932bd8a2cb43462a618bdc5875cc4241d9c44/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionMonitorServiceImpl.java#L84)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use constants in above class
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55300)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
