### PR TITLE
feat: [PLG-1395]: Signup moment tracking

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36301)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36301)

**Comment by Xin-Harness** [comment]
trigger messagecheck

**Comment by Xin-Harness** [comment]
trigger messagecheck

**Comment by Xin-Harness** [comment]
Test

Fully intent with intent: CE, signupAction: Trial, edition: TEAM

￼

￼
Enable Trial license for the intended module
￼





Module intent: suppose to only enable free license for that module
￼


￼

No intent:

Backend will not enable module license for this account,  it needs to be enabled from front end
￼
￼


Corner case: 
Only specify the edition:

￼
it will enable free license for this module
￼


Oauth:

Fully intent:

￼

￼

Module intent:
￼
￼
no intent:

￼

￼
corner case:
￼
￼

**Comment by Xin-Harness** [comment]
Fully intent with intent: CE, signupAction: Trial, edition: TEAM
Pasted Graphic 30
Pasted Graphic 31
Enable Trial license for the intended module
Pasted Graphic 32
Module intent: suppose to only enable free license for that module
Pasted Graphic 34
Pasted Graphic 33
No intent:
Backend will not enable module license for this account,  it needs to be enabled from front end
Pasted Graphic 36
Pasted Graphic 35
Corner case: 
Only specify the edition:

Pasted Graphic 37
it will enable free license for this module
Pasted Graphic 38
Oauth:

Fully intent:
Pasted Graphic 39
Pasted Graphic 40
Module intent:
Pasted Graphic 41
Pasted Graphic 42
no intent:
Pasted Graphic 43
Pasted Graphic 44
corner case:
Pasted Graphic 46
Pasted Graphic 45

**Review by devinder-harness — APPROVED** [review]

**Review by devinder-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36301)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36301)* status: :shipit: complete! ✓

**Pull request merged**
