### PR TITLE
feat: [CDS-44405]: Handle empty secret value

### PR DESCRIPTION
**Pull request by puthrayaharness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38600)

### CODE REVIEW

**Review by manjunatha-etagi — APPROVED** [review]

**Comment by puthrayaharness** [comment]
trigger ti0 ti1 ti2 ti3 ti4

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38600)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/SettingAttribute.java` line 281 at r1](https://reviewable.io/reviews/harness/harness-core/38600#-NE4J-Vo2sWmdvIXeqD9:-NE4J-Vo2sWmdvIXeqDA:b-nhuake) ([raw file](https://github.com/harness/harness-core/blob/4e3caebbda3202b99d8b37109ca83815ee197a69/950-delegate-tasks-beans/src/main/java/software/wings/beans/SettingAttribute.java#L281)):*
> ```Java
>         .id(getUuid())
>         .name(getName())
>         .type(CONNECTOR)
> ```

what is the best way to avoid duplication here since we're only changing the type here for each entity.

**Comment by USB-05** [comment]
trigger ti1

**Comment by abhayganvir** [comment]
trigger ti2 ti3 ti4

**Comment by aman-harness** [comment]
trigger ti1

**Comment by puthrayaharness** [comment]
trigger checkstyle

**Review by prabu-kr — DISMISSED** [review]
> Reviewed 37 of 38 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38600)* status: :shipit: complete! ✓

**Comment by rutvijmehta-harness** [comment]
trigger ti0

**Comment by rutvijmehta-harness** [comment]
trigger ti1

**Comment by rutvijmehta-harness** [comment]
trigger ti2

**Comment by rutvijmehta-harness** [comment]
trigger ti3

**Comment by rutvijmehta-harness** [comment]
trigger ti4

**Review by rutvijmehta-harness — APPROVED** [review]
> Reviewed 37 of 38 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38600)* status: :shipit: complete! ✓

**Pull request merged**
