### PR TITLE
feat: [BT-1605] identify flaky unit tests

### PR DESCRIPTION
**Pull request by shivagowda**
we run java unit tests with flag: --flaky_test_attempts=3
In bazel, it means, that whenever a test is failed or errored out, retry 3 times. We have more than 20k unit tests in harness-core and all tests are currently passing. However, while analyzing, found that about 3% of unit tests have failed at least once due to `exited with error code 137` and these tests are taking unusually long (~4 min) to run.
Note that, they all succeed in subsequent retries due to the above flag --flaky_test_attempts=3

We determined that, the heap memory of 32GB is too high causing this OOM. So, reduced it to 4GB for both individual tests and package tests. Now, we are no more seeing `exited with error code 137` 

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36216)

### CODE REVIEW

**Comment by shivagowda** [comment]
trigger tin3

**Comment by shivagowda** [comment]
trigger ti3

**Comment by shivagowda** [comment]
trigger ti0, ti1, ti3

**Comment by shivagowda** [comment]
trigger ti0, ti1

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36216)* status: :shipit: complete! ✓

**Pull request merged**
