### PR TITLE
techdebt: [CDS-81090]: improves test coverage for InputSetsApiUtils.java

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
techdebt: [CDS-81090]: improves test coverage for InputSetsApiUtils.java from 17% to 100%

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-81090]: https://harness.atlassian.net/browse/CDS-81090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55523)

### CODE REVIEW

**Comment by sandeshsalunkhegh** [comment]
Estimated Code Coverage after merging this PR
image

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55523)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 276 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf79-11bJN5cr0NamV:-Njf79-11bJN5cr0NamW:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L276)):*
> ```Java
>   public void testGetInputSetResponseWithError() {
>     InputSetEntity inputSetEntity = mock(InputSetEntity.class);
>     InputSetErrorWrapperDTOPMS inputSetErrorWrapperDTOPMS = mock(InputSetErrorWrapperDTOPMS.class);
> ```

same for this
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 285 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf76CC3p44aDnq8ADw:-Njf76CC3p44aDnq8ADx:b-w8j49d) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L285)):*
> ```Java
>     doReturn(PROJ_IDENTIFIER).when(inputSetEntity).getProjectIdentifier();
>     doReturn(DESCRIPTION).when(inputSetEntity).getDescription();
>     doReturn(ERROR_PIPELINE_YAML).when(inputSetErrorWrapperDTOPMS).getErrorPipelineYaml();
> ```

why we are mocking and not creating a tmp object



_Code quote:_
```Java
    doReturn(ERROR_PIPELINE_YAML).when(inputSetEntity).getYaml();
    doReturn(identifier).when(inputSetEntity).getIdentifier();
    doReturn(name).when(inputSetEntity).getName();
    doReturn(ORG_IDENTIFIER).when(inputSetEntity).getOrgIdentifier();
    doReturn(PROJ_IDENTIFIER).when(inputSetEntity).getProjectIdentifier();
    doReturn(DESCRIPTION).when(inputSetEntity).getDescription();
    doReturn(ERROR_PIPELINE_YAML).when(inputSetErrorWrapperDTOPMS).getErrorPipelineYaml();
```
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 305 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf7BYQ7Gp7OxuM7aqf:-Njf7BYQ7Gp7OxuM7aqg:bqpra7l) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L305)):*
> ```Java
>     inputSetResponseBody.setGitDetails(gitDetails);
>     inputSetResponseBody.setCreated(0L);
>     inputSetResponseBody.setUpdated(0L);
> ```

you can create private method to create these object to keep test method clean



_Code quote:_
```Java
    InputSetErrorDetails errorDetails = new InputSetErrorDetails();
    errorDetails.setValid(false);
    errorDetails.setOutdated(false);
    errorDetails.setMessage("Some fields in the Input Set are invalid.");
    errorDetails.setErrorPipelineYaml(ERROR_PIPELINE_YAML);
    errorDetails.setInvalidRefs(Collections.emptyList());
    errorDetails.setFqnErrors(Collections.emptyList());

    inputSetResponseBody.setInputSetYaml(inputSetEntity.getYaml());
    inputSetResponseBody.setIdentifier(inputSetEntity.getIdentifier());
    inputSetResponseBody.setName(inputSetEntity.getName());
    inputSetResponseBody.setOrg(inputSetEntity.getOrgIdentifier());
    inputSetResponseBody.setProject(inputSetEntity.getProjectIdentifier());
    inputSetResponseBody.setDescription(inputSetEntity.getDescription());
    inputSetResponseBody.setTags(Collections.emptyMap());
    inputSetResponseBody.setErrorDetails(errorDetails);
    inputSetResponseBody.setGitDetails(gitDetails);
    inputSetResponseBody.setCreated(0L);
    inputSetResponseBody.setUpdated(0L);
```
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf7HDnCRVqWcRjhSRA:-Njf7HDnCRVqWcRjhSRB:b-tobx9w) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L315)):*
> ```Java
>   @Owner(developers = SANDESH_SALUNKHE)
>   @Category(UnitTests.class)
>   public void testGetFQNErrors() {
> ```

can you either add comments or be method descriptive what we are testing for getFQNErrors? is it success case or failed/exception?
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 642 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf7yl4DR6Wb_3OWMjj:-Njf7yl4DR6Wb_3OWMjk:b-b2sn51) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L642)):*
> ```Java
>   public void testMapCreateToRequestInfoDTONullRequestBody() {
>     try {
>       InputSetsApiUtils.mapCreateToRequestInfoDTO(null);
> ```

instead use - assertThatThrownBy
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 682 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf80-yEJav9D_RG91I:-Njf80-yEJav9D_RG91J:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L682)):*
> ```Java
>       InputSetsApiUtils.mapUpdateToRequestInfoDTO(null);
>     } catch (InvalidRequestException ex) {
>       assertThat(ex.getMessage()).isEqualTo("Update Request Body cannot be null.");
> ```

same here
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 870 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf886XCc2KBA5-ecm8:-Njf886XCc2KBA5-ecm9:b-vy0hiw) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L870)):*
> ```Java
>     inputSetsApiUtils.checkAndSetContextIfGetOnlyFileContentEnabled(account, getOnlyFileContent);
>     verifyStatic(ThreadOperationContextHelper.class, times(1));
>     ThreadOperationContextHelper.setUserFlow(USER_FLOW.EXECUTION);
> ```

what testing we are doing by setting this at end?



_Code quote:_
```Java
ThreadOperationContextHelper.setUserFlow(USER_FLOW.EXECUTION);
```

**Review by sandeshsalunkhegh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55523)* status: 1 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 276 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf79-11bJN5cr0NamV:-NjfOE6v5WSQya8-hd4M:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L276)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same for this
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 285 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf76CC3p44aDnq8ADw:-NjfOEhfB98zYQ5EdCSd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L285)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are mocking and not creating a tmp object
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 305 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf7BYQ7Gp7OxuM7aqf:-NjfOFLu1O9OxGjeN0hf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L305)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

you can create private method to create these object to keep test method clean
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf7HDnCRVqWcRjhSRA:-NjfOFyG2dFBZBdcseVe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L315)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you either add comments or be method descriptive what we are testing for getFQNErrors? is it success case or failed/exception?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 642 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf7yl4DR6Wb_3OWMjj:-NjfOIEy7g3xYftB2bMD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L642)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead use - assertThatThrownBy
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 682 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf80-yEJav9D_RG91I:-NjfOIg20rVdadOulcXK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L682)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java` line 870 at r2](https://reviewable.io/reviews/harness/harness-core/55523#-Njf886XCc2KBA5-ecm8:-NjfOKcUENFmhX2M8BdZ:b-2n3u2j) ([raw file](https://github.com/harness/harness-core/blob/7d3e9ac42cd299e8ba757ce12519ce232503176f/pipeline-service/service/src/test/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtilsTest.java#L870)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what testing we are doing by setting this at end?
</blockquote></details>

Done.
Removed the above line.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55523)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55523)* status: :shipit: complete! ✓

**Pull request merged**
