### PR TITLE
feat: [CDS-42089]: create sample k8s manifests at account level file store when NG account is created

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 5 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36596)

**Review by ivan-83 — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: 1 file(s) to review. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/SampleManifestFileService.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/36596#-NA5JH_w9o6HN_vu4k6F:-NA5JH_w9o6HN_vu4k6G:b-l7e9rz) ([raw file](https://github.com/harness/harness-core/blob/4b09efd1b14f7486cc911994250edeec67fc996d/120-ng-manager/src/main/java/io/harness/ng/core/manifests/SampleManifestFileService.java#L26)):*
> ```Java
> @Singleton
> @Slf4j
> public class SampleManifestFileService {
> ```

Everything looks good to me, one thing we could do is to make this service and resource more generic and call it like SimpleFileCreationService or...
Also, we can move hardcoded value for folder and files names from method to service Map<String, List<String>> field and everyone can add one more folder with files to that map and add resources to the resources folder. Again it's up to you not required.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/SampleManifestFileService.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/36596#-NA5JH_w9o6HN_vu4k6F:-NA8EQDREnjexP8L5fcK:b-o0lwdb) ([raw file](https://github.com/harness/harness-core/blob/4b09efd1b14f7486cc911994250edeec67fc996d/120-ng-manager/src/main/java/io/harness/ng/core/manifests/SampleManifestFileService.java#L26)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Everything looks good to me, one thing we could do is to make this service and resource more generic and call it like SimpleFileCreationService or...
Also, we can move hardcoded value for folder and files names from method to service Map<String, List<String>> field and everyone can add one more folder with files to that map and add resources to the resources folder. Again it's up to you not required. 
</blockquote></details>

I believe that we should not generalise at the first time because we might not know how future usage might be. I try to wait to someone else use it and then generalise
https://wiki.c2.com/?PrematureGeneralization

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 3 of 14 files at r1, 2 of 4 files at r2, 5 of 9 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
trigger ti2,ti3,ti4

**Comment by yogesh-chauhan** [comment]
trigger ti2

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596#-:-NADnU8-EyZ3Ps5uvSdY:bnfp4nl)* status: 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36596)* status: :shipit: complete! ✓

**Pull request merged**
