### PR TITLE
Fix: [IDP-211]: Fixing null check and API response

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: 0 of 1 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/44408#-NPIJurL2d2aoXmXso5d:-NPIJurL2d2aoXmXso5e:b-gm681r) ([raw file](https://github.com/harness/harness-core/blob/c2843f402e82a1c6dca2c701acc5753553e1bb52/idp-service/service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java#L27)):*
> ```Java
> 
>   @Override
>   public Optional<NamespaceInfo> getNamespaceForAccountIdentifier(String accountId) {
> ```

Since we always return with a NamespaceInfo, wondering if we really need to return Optional here?

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/44408#-NPIJurL2d2aoXmXso5d:-NPIbpCk9Ddq5iceerEr:b-j7bwvr) ([raw file](https://github.com/harness/harness-core/blob/c2843f402e82a1c6dca2c701acc5753553e1bb52/idp-service/service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java#L27)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Since we always return with a NamespaceInfo, wondering if we really need to return Optional here?
</blockquote></details>

Correct we can return directly return NamespaceInfo, fixed it.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: :shipit: complete! ✓

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/resource/AccountInfoApiImpl.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44408#-NPIj5_a3sexFvap61bt:-NPIj5_a3sexFvap61bu:bdt4ep7) ([raw file](https://github.com/harness/harness-core/blob/faec40f264d66de94ba64044232da578320d6833/idp-service/service/src/main/java/io/harness/idp/namespace/resource/AccountInfoApiImpl.java#L31)):*
> ```Java
>     NamespaceInfo accountInfo;
>     try {
>       accountInfo = namespaceService.getAccountIdForNamespace(namespace);
> ```

nit: could we have the return statement here itself?

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/resource/AccountInfoApiImpl.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44408#-NPIj5_a3sexFvap61bt:-NPIoB7I4BbnIBfrMx1K:bwz8m3q) ([raw file](https://github.com/harness/harness-core/blob/faec40f264d66de94ba64044232da578320d6833/idp-service/service/src/main/java/io/harness/idp/namespace/resource/AccountInfoApiImpl.java#L31)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: could we have the return statement here itself?
</blockquote></details>

yes fixed it please review it again.

**Comment by devesh-harness** [comment]
trigger ut0

**Comment by devesh-harness** [comment]
trigger ut1

**Comment by devesh-harness** [comment]
trigger ut2

**Review by deepharness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/resource/NamespaceApiImpl.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/44408#-NPKrKO301_u7yivwqZq:-NPKrKO301_u7yivwqZr:byz030d) ([raw file](https://github.com/harness/harness-core/blob/e358b29d25f516a6dc5cda9da639c07f1f0031e1/idp-service/service/src/main/java/io/harness/idp/namespace/resource/NamespaceApiImpl.java#L36)):*
> ```Java
>       NamespaceInfo namespaceInfo = NamespaceMapper.toDTO(saveResponse);
>       return Response.status(Response.Status.CREATED).entity(namespaceInfo).build();
>     } catch (DuplicateKeyException e) {
> ```

Do you have to catch generic exception ? now you are only catching "DuplicateKeyException" only

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/namespace/resource/NamespaceApiImpl.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/44408#-NPKrKO301_u7yivwqZq:-NPLZWno5W3_WlLwmysT:b-thtnoi) ([raw file](https://github.com/harness/harness-core/blob/e358b29d25f516a6dc5cda9da639c07f1f0031e1/idp-service/service/src/main/java/io/harness/idp/namespace/resource/NamespaceApiImpl.java#L36)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Do you have to catch generic exception ? now you are only catching "DuplicateKeyException" only
</blockquote></details>

correct, fixed it.

**Review by deepharness — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: 1. unresolved discussions.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44408)* status: :shipit: complete! ✓

**Pull request merged**
