### PR TITLE
[feat]: [CDS-17418]: initial changes for unblocking UI for SNOW Create Update CRUD

### PR DESCRIPTION
**Pull request by hingerabhinav**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30891)

### CODE REVIEW

**Review by prabu-kr — CHANGES_REQUESTED** [review]
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30891)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/CommonStepInfo.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/30891#-Mx8R3DPDshfKjXSRP4n:-Mx8R3DQEswUBBbL9ogf:bz6oyub) ([raw file](https://github.com/harness/harness-core/blob/3232cbe8f9c5ded78068396133f1af246113a146/800-pipeline-service/src/main/java/io/harness/pms/pipeline/CommonStepInfo.java#L133)):*
> ```Java
>           .setName("ServiceNow Update")
>           .setType(StepSpecTypeConstants.SERVICENOW_UPDATE)
>           .setStepMetaData(StepMetaData.newBuilder().addCategory("ServiceNow").addFolderPaths("ServiceNow").build())
> ```

Use constants like above
___
*[860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowStepUtils.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/30891#-Mx8Rv8F7T_YAKf4wOu9:-Mx8Rv8F7T_YAKf4wOuA:be63lg2) ([raw file](https://github.com/harness/harness-core/blob/3232cbe8f9c5ded78068396133f1af246113a146/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowStepUtils.java#L57)):*
> ```Java
>     Map<String, String> finalMap = new HashMap<>();
>     for (Map.Entry<String, ParameterField<String>> entry : fields.entrySet()) {
>       if (EmptyPredicate.isEmpty(entry.getKey()) || ParameterField.isNull(entry.getValue())) {
> ```

Should this be isNull or isEmpty
___
*[860-orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateSpecParameters.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/30891#-Mx8TjhYDgwxtLszQj9G:-Mx8TjhYDgwxtLszQj9H:brvo1nl) ([raw file](https://github.com/harness/harness-core/blob/3232cbe8f9c5ded78068396133f1af246113a146/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateSpecParameters.java#L35)):*
> ```Java
>   @NotNull ParameterField<String> connectorRef;
>   @NotNull ParameterField<String> ticketType;
>   @NotNull ParameterField<String> issueKey;
> ```

Change this to ticketNumber. Issue is for jira, in servicenow we usually refer to as ticket

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30891)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/CommonStepInfo.java, line 133 at r1](https://reviewable.io/reviews/harness/harness-core/30891#-Mx8R3DPDshfKjXSRP4n:-MxFDYnBEad2cKmbVhm1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3232cbe8f9c5ded78068396133f1af246113a146/800-pipeline-service/src/main/java/io/harness/pms/pipeline/CommonStepInfo.java#L133)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Use constants like above
</blockquote></details>

Done.
___
*[860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowStepUtils.java, line 57 at r1](https://reviewable.io/reviews/harness/harness-core/30891#-Mx8Rv8F7T_YAKf4wOu9:-MxFDaiS5RhTMl0osg4F:b4pbv96) ([raw file](https://github.com/harness/harness-core/blob/3232cbe8f9c5ded78068396133f1af246113a146/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/ServiceNowStepUtils.java#L57)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Should this be isNull or isEmpty
</blockquote></details>

Removed this method as its unused
___
*[860-orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateSpecParameters.java, line 35 at r1](https://reviewable.io/reviews/harness/harness-core/30891#-Mx8TjhYDgwxtLszQj9G:-MxFDjmXBiQYLPlK5jqp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3232cbe8f9c5ded78068396133f1af246113a146/860-orchestration-steps/src/main/java/io/harness/steps/servicenow/update/ServiceNowUpdateSpecParameters.java#L35)):*
<details><summary><i>Previously, prabu-kr (Prabu Rajendran) wrote…</i></summary><blockquote>

Change this to ticketNumber. Issue is for jira, in servicenow we usually refer to as ticket
</blockquote></details>

Done.

**Review by prabu-kr — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30891)* status: :shipit: complete! ✓

**Review by prabu-kr — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30891)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 28 of 40 files at r1, 10 of 14 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30891)* status: :shipit: complete! ✓

**Pull request merged**
