### PR TITLE
[feat]: [PL-25747]: Hard delete Input Set Entities

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34090)

### CODE REVIEW

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34090)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34090)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/34090#-N4BykL0DNx7UAovbP2f:-N4BykL0DNx7UAovbP2g:b9x4bi) ([raw file](https://github.com/harness/harness-core/blob/774b54e6c0bf239d3925c28cddd8db2aaeecd82e/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L314)):*
> ```Java
>     RetryPolicy<Object> retryPolicy = getRetryPolicy(
>         "[Retrying]: Failed deleting Input Set; attempt: {}", "[Failed]: Failed deleting Input Set; attempt: {}");
>     Failsafe.with(retryPolicy).get(() -> mongoTemplate.findAllAndRemove(query, InputSetEntity.class));
> ```

Here also we should add bulk audits for delete, or add a todo with a jira ticket if handling in another pr



_Code quote:_
```Java
    RetryPolicy<Object> retryPolicy = getRetryPolicy(
        "[Retrying]: Failed deleting Input Set; attempt: {}", "[Failed]: Failed deleting Input Set; attempt: {}");
    Failsafe.with(retryPolicy).get(() -> mongoTemplate.findAllAndRemove(query, InputSetEntity.class));
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34090)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java` line 314 at r1](https://reviewable.io/reviews/harness/harness-core/34090#-N4BykL0DNx7UAovbP2f:-N4BzQ2F5TqxqIlAjaD1:bfovtum) ([raw file](https://github.com/harness/harness-core/blob/774b54e6c0bf239d3925c28cddd8db2aaeecd82e/800-pipeline-service/src/main/java/io/harness/repositories/inputset/PMSInputSetRepositoryCustomImpl.java#L314)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Here also we should add bulk audits for delete, or add a todo with a jira ticket if handling in another pr
</blockquote></details>

Have started working on this in branch `namanverma/outbox-events`. Ticket for this: https://harness.atlassian.net/browse/PIE-4020
Will be covering all types of audits here.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34090)* status: :shipit: complete! ✓

**Pull request merged**
