### PR TITLE
feat: [PL-26819]: Removing CG_RBAC_EXCLUSION FF

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36028)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36028)

**Comment by reetika04** [comment]
trigger messagecheck

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028#-:-NAhi7IJ4H1S-lVrTw6t:bnfp4nl)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/application/AppFilterController.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/36028#-NAhjcwT0VQYxQEyMb77:-NAhjcwT0VQYxQEyMb78:b-mosaa1) ([raw file](https://github.com/harness/harness-core/blob/6eff0090aa9a9b17eb0d15d01ec0d7312f0a53d8/400-rest/src/main/java/software/wings/graphql/datafetcher/application/AppFilterController.java#L67)):*
> ```Java
>       throw new InvalidRequestException("Cannot set both appIds and filterType ALL in app filter");
>     }
>     if (!featureFlagService.isEnabled(FeatureName.CG_RBAC_EXCLUSION, accountId)
> ```

I think we can remove the featureFlagService reference from this file.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028#-:-NAhkHiyExk0hOVLtuaf:bnfp4nl)* status: Some of the checks are too old. 1 change requests.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/application/AppFilterController.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/36028#-NAhjcwT0VQYxQEyMb77:-NAifpDZ1e7P0xNwh49D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6eff0090aa9a9b17eb0d15d01ec0d7312f0a53d8/400-rest/src/main/java/software/wings/graphql/datafetcher/application/AppFilterController.java#L67)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think we can remove the featureFlagService reference from this file.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028#-:-NAikGJsBPHT8PZM0Zxo:bnfp4nl)* status: :shipit: complete! ✓

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36028#-:-NAilwniESRKjb9twQLG:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
