### PR TITLE
fix: [PL-24786]: Delete Org scope connectors when an Org is deleted

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/32428#-N0Z5ZqOC11I6sYR1DBV:-N0Z5ZqOC11I6sYR1DBW:boaymsa) ([raw file](https://github.com/harness/harness-core/blob/f07fcc56c9dd93b817885587572775b39360fc3d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L102)):*
> ```Java
> 
>   private boolean processOrganizationDeleteEvent(OrganizationEntityChangeDTO organizationEntityChangeDTO) {
>     return connectorEntityCRUDEventHandler.deleteAssociatedConnectors(
> ```

Will the connectors associated with all the projects inside the organization also get deleted? 
Hope the various cases are tested. Thanks

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 106 at r1](https://reviewable.io/reviews/harness/harness-core/32428#-N0Z6mokCN0CD8Is1ctR:-N0Z6mokCN0CD8Is1ctS:b-zfle6i) ([raw file](https://github.com/harness/harness-core/blob/f07fcc56c9dd93b817885587572775b39360fc3d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L106)):*
> ```Java
>   }
> 
>   private boolean processOrganizationRestoreEvent(OrganizationEntityChangeDTO organizationEntityChangeDTO) {
> ```

Yes. The connectors inside projects are deleted via projectDelete event call. All the scenarios are tested.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/32428#-N0Z5ZqOC11I6sYR1DBV:-N0Z6mgA2hSEU8ESKRg7:bcm4jic) ([raw file](https://github.com/harness/harness-core/blob/f07fcc56c9dd93b817885587572775b39360fc3d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L102)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Will the connectors associated with all the projects inside the organization also get deleted? 
Hope the various cases are tested. Thanks
</blockquote></details>

Yes. All the connectors inside projects are deleted via projectDelete event call. All scenarios are tested.

**Review by pbarapatre10 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: 2 file(s) to review.

**Review by boopesh007 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: 2 file(s) to review.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32428)* status: :shipit: complete! ✓

**Pull request merged**
