### PR TITLE
fix: [PL-38575]: Handle all runtime exceptions thrown from Redis in Iterator module

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

In prod-1 and prod-2 we encountered Redis out of memory and as a result the iterators (ArtifactCollection, ArtifactCleanup and PerpetualTaskAssignment) running in RedisBatchMode stopped working. This was because the Redisson library was throwing a `RedisOutOfMemoryException` which was not being caught in the code. The distributed lock framework (RedisPersistentLocker) is suppose to catch the exception and return a Null lock instead of throwing the exception further.

This PR fixes this behavior by handling the exception and returning a Null lock object. A new API has been added for the time being as the usage of the Persistent locker interface is intertwined in multiple places with some of them expecting a Null object and some of them expecting an exception. Eventually this new API will phase out the usage of lock acquisition at all other places in follow up PRs.

Reproduced the issue locally and tested the fix by making Redis go OOM.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47584)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 460 at r1](https://reviewable.io/reviews/harness/harness-core/47584#-NV1Jzla6kzRuFLVj5nN:-NV1Jzla6kzRuFLVj5nO:b-m3n4pl) ([raw file](https://github.com/harness/harness-core/blob/d5b36f406ea6c05d305468d3241340d053d5b484/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L460)):*
> ```Java
>     while (true) {
>       // Hardcoding the lockTimeout and waitTimeout for the lock to 5 secs.
>       try (AcquiredLock acquiredLock = persistentLocker.waitToAcquireLock(MongoPersistenceIterator.class, iteratorName,
> ```

@Raghav-Murali  I think we discussed that We should handle errors at framework level and return Null Locks and this code should make decision based on that.

**Comment by piyush-harness** [comment]
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/47584#-NV1LyTR3uiG86p2MTVS:-NV1LyTR3uiG86p2MTVT:b-ycoki0) ([raw file](https://github.com/harness/harness-core/blob/d5b36f406ea6c05d305468d3241340d053d5b484/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L369)):*
> ```Java
>       } finally {
>         // Release the distributed lock - acquiredLock cannot be null
>         releaseLock(acquiredLock);
> ```

This can also throw OOM Exception.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47584)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/47584#-NV1LyTR3uiG86p2MTVS:-NV6MCt_-A_c1IgVKBl6:b69azin) ([raw file](https://github.com/harness/harness-core/blob/d5b36f406ea6c05d305468d3241340d053d5b484/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L369)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This can also throw OOM Exception.
</blockquote></details>

There is a general RuntimeException that we catch inside releaseLock(). Also, looks like Redis OOM Exception extends RedisException which is also being handled.
___
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 460 at r1](https://reviewable.io/reviews/harness/harness-core/47584#-NV1Jzla6kzRuFLVj5nN:-NV6MXO3-EHaHobUwj0C:b-elkpa3) ([raw file](https://github.com/harness/harness-core/blob/d5b36f406ea6c05d305468d3241340d053d5b484/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L460)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

@Raghav-Murali  I think we discussed that We should handle errors at framework level and return Null Locks and this code should make decision based on that.
</blockquote></details>

Yup, I have updated the PR to handle this at the framework level.

**Comment by piyush-harness** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/repositories/CIAccountExecutionMetadataRepositoryCustomImpl.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/47584#-NV7Zi2q1Gek23ie69X0:-NV7Zi2q1Gek23ie69X1:b-5s1gqc) ([raw file](https://github.com/harness/harness-core/blob/fb8458a332bbc79dce7967e9d661835a336cab88/332-ci-manager/service/src/main/java/io/harness/ci/repositories/CIAccountExecutionMetadataRepositoryCustomImpl.java#L82)):*
> ```Java
>     Criteria criteria = Criteria.where(CIAccountExecutionMetadataKeys.accountId).is(accountId);
>     Query query = new Query(criteria);
>     try (AcquiredLock<?> lock = persistentLocker.waitToAcquireLockOrNull(
> ```

I think we should use Optional instead of naming the method as OrNull, Thats more cleaner way of telling "I can return null" and you should check.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47584)* status: 24 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/repositories/CIAccountExecutionMetadataRepositoryCustomImpl.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/47584#-NV7Zi2q1Gek23ie69X0:-NV7pEfL7P3693uEysnD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fb8458a332bbc79dce7967e9d661835a336cab88/332-ci-manager/service/src/main/java/io/harness/ci/repositories/CIAccountExecutionMetadataRepositoryCustomImpl.java#L82)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

I think we should use Optional instead of naming the method as OrNull, Thats more cleaner way of telling "I can return null" and you should check.
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 21 of 22 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47584)* status: 24 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by harshjain12 — APPROVED** [review]

**Comment by piyush-harness** [comment]
*[`960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/47584#-NV1LyTR3uiG86p2MTVS:-NVBnez1-i1TyFRusWIa:b-vzs6kj) ([raw file](https://github.com/harness/harness-core/blob/d5b36f406ea6c05d305468d3241340d053d5b484/960-persistence/src/main/java/io/harness/mongo/iterator/MongoPersistenceIterator.java#L369)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

There is a general RuntimeException that we catch inside releaseLock(). Also, looks like Redis OOM Exception extends RedisException which is also being handled.
</blockquote></details>

@Raghav-Murali I meant framework level Release method can also throw Exception we should handle that as well

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by piyush-harness** [comment]
*[`960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/47584#-NVC4qnm98wILntPPzO6:-NVD3Svn1h3yYRQ3KfuA:b2ni9ah) ([raw file](https://github.com/harness/harness-core/blob/b1220c71a84e0a937328e8ccbb7f33a866222020/960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java#L39)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

We should catch Exception here as well
</blockquote></details>

ok

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 21 of 22 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47584)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java` line 39 at r8](https://reviewable.io/reviews/harness/harness-core/47584#-NVC4qnm98wILntPPzO6:-NVD3YGJEDSKo8-Dyr0k:b4ujbwf) ([raw file](https://github.com/harness/harness-core/blob/b1220c71a84e0a937328e8ccbb7f33a866222020/960-persistence/src/main/java/io/harness/lock/redis/RedisAcquiredLock.java#L39)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Minor:  "Received an exception"

**Review by harshjain12 — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47584)* status: :shipit: complete! ✓

**Pull request merged**
