### PR TITLE
feat:[SRM-14169]: Added Filter For SLI Evaluation Type

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45528)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45528)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 546 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCw6gT62FcJzwCc1h0:-NRCw6gT62FcJzwCc1h1:b-t95ohp) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L546)):*
> ```Java
>   }
>   @Override
>   public List<AbstractServiceLevelObjective> get(ProjectParams projectParams, List<String> identifiers) {
> ```

add UT



_Code quote:_
```Java
  @Override
  public List<AbstractServiceLevelObjective> get(ProjectParams projectParams, List<String> identifiers) {
    Filter.FilterBuilder filterBuilder = Filter.builder().identifiers(identifiers);
    if (projectParams.getOrgIdentifier() == null) {
      filterBuilder.childResource(true);
    }
    return get(projectParams, filterBuilder.build());
  }
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 822 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCv6b9EMzzUwMFUVuj:-NRCv6bA5JfcZrxkUoWs:b-9n79r6) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L822)):*
> ```Java
>                                            .getServiceLevelObjectivesDetails()
>                                            .get(0)
>                                            .getServiceLevelObjectiveRef());
> ```

If we just need any one, in this case 0th, why are we adding all to the list to fetch



_Code quote:_
```Java
          sloIdentifierToEntityMap.get(((CompositeServiceLevelObjective) serviceLevelObjective)
                                           .getServiceLevelObjectivesDetails()
                                           .get(0)
                                           .getServiceLevelObjectiveRef());
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 830 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCus3h0CylUAQdH9Jx:-NRCus3i8SCYP_8uT_rJ:boc9z89) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L830)):*
> ```Java
>       Map<String, ServiceLevelIndicator> sliIdentifierToEntityMap) {
>     return sliIdentifierToEntityMap
>         .get(((SimpleServiceLevelObjective) serviceLevelObjective).getServiceLevelIndicators().get(0))
> ```

getOrDefault( value, WINDOW)



_Code quote:_
```Java
get
```

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45528)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 546 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCw6gT62FcJzwCc1h0:-NRD0yVmDSf5ztsyHUw3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L546)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

add UT
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 822 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCv6b9EMzzUwMFUVuj:-NRD0xWj-gLChKp3YZF-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L822)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

If we just need any one, in this case 0th, why are we adding all to the list to fetch
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 830 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCus3h0CylUAQdH9Jx:-NRD0v1xD6ABkiqVKN_p:b-kebvd) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L830)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

getOrDefault( value, WINDOW)
</blockquote></details>

Not Needed.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45528#-:-NRDYIfm9QOlDTbGIZ_w:bnfp4nl)* status: 2 file(s) to review.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45528)* status: 2 file(s) to review. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardApiFilter.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/45528#-NRCmBAWEnm5JqDH5cmv:-NRCmBAX7HTlzKwsVmqU:bffztjx) ([raw file](https://github.com/harness/harness-core/blob/689ba4b545ae749a3c9a7422c231ea0599b986d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardApiFilter.java#L47)):*
> ```Java
>   @Parameter(description = "For filtering on the basis of SLO target spec") SLOTargetFilterDTO sloTargetFilterDTO;
>   @Parameter(description = "For filtering on the basis of Composite SLO") String compositeSLOIdentifier;
>   @Parameter(description = "For filtering on the basis of SLI Evaluation type")
> ```

either use evaluationtype or execution type it has to be consistent.
Evaluation looks more relevant
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 549 at r2](https://reviewable.io/reviews/harness/harness-core/45528#-NRDlITU098mHfyK4msh:-NRDlITU098mHfyK4msi:bxeo0fn) ([raw file](https://github.com/harness/harness-core/blob/f5282618b18d2ba3a8f58da60c4f1f705f9b7c61/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L549)):*
> ```Java
>     Filter.FilterBuilder filterBuilder = Filter.builder().identifiers(identifiers);
>     if (projectParams.getOrgIdentifier() == null) {
>       filterBuilder.childResource(true);
> ```

is it something needed for this PR?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 771 at r2](https://reviewable.io/reviews/harness/harness-core/45528#-NRDkSWQ56ljODelw7zk:-NRDkSWQ56ljODelw7zl:b-pgoyzb) ([raw file](https://github.com/harness/harness-core/blob/f5282618b18d2ba3a8f58da60c4f1f705f9b7c61/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L771)):*
> ```Java
>     List<String> sliIdentifierList = new ArrayList<>();
>     serviceLevelObjectiveList.forEach(serviceLevelObjective -> {
>       if (serviceLevelObjective.getType() == ServiceLevelObjectiveType.COMPOSITE) {
> ```

move this to another method where it takes list of AbstractServiceLevelObjective and return List<SimpleServiceLevelObjective>
For compositeSLO it group them and make a DB single DB call. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java` line 792 at r2](https://reviewable.io/reviews/harness/harness-core/45528#-NRDkxe18pybRfh8kVTH:-NRDkxe18pybRfh8kVTI:bau2gg7) ([raw file](https://github.com/harness/harness-core/blob/f5282618b18d2ba3a8f58da60c4f1f705f9b7c61/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelObjectiveV2ServiceImpl.java#L792)):*
> ```Java
>     });
> 
>     Query<ServiceLevelIndicator> query =
> ```

Move this to seperate method which takes list of Simple SLOs and return map of slo to sli mapping.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 15 of 22 files at r3, 5 of 7 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45528)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45528)* status: :shipit: complete! ✓

**Pull request merged**
