### PR TITLE
feat: [CDS-77797]: adding yaml to upsert response

### PR DESCRIPTION
**Pull request by lasdox**
## Describe your changes
Adding the yaml of the processed entity in the response to be used together with go-sdk for performance reasons.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52092)

### CODE REVIEW

**Comment by lasdox** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
@lasdox could you please update the PR description ? Thanks!

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1325 at r1](https://reviewable.io/reviews/harness/harness-core/52092#-NcknbVD8jjqBSwDr5zI:-NcknbVE2m7kZsUGYHVp:b-ay0l12) ([raw file](https://github.com/harness/harness-core/blob/51bb2f1f41f6b6dd325a198a0aec6acedb0672b3/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1325)):*
> ```Java
>               .build();
>         }
>         String dumpedYaml = software.wings.yaml.YamlHelper.toYamlString(changeContext.getYaml());
> ```

is this the same yaml that was sent by the client in the upsertAPI  ?

**Comment by lasdox** [comment]
> _[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1325 at r1](https://reviewable.io/reviews/harness/harness-core/52092#-NcknbVD8jjqBSwDr5zI:-NcknbVE2m7kZsUGYHVp:b-ay0l12) ([raw file](https://github.com/harness/harness-core/blob/51bb2f1f41f6b6dd325a198a0aec6acedb0672b3/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1325)):_
> 
> > ```java
> >               .build();
> >         }
> >         String dumpedYaml = software.wings.yaml.YamlHelper.toYamlString(changeContext.getYaml());
> > ```
> 
> is this the same yaml that was sent by the client in the upsertAPI ?

Not sure if they are identical, it is the yaml returned by a entity after it is processed

**Review by RajBaviskar — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52092)* status: Some of the checks are too old. 2 file(s) to review.

**Pull request merged**
