### PR TITLE
fix: [CDS-55785]: Fix git-sync context leaking between trigger executions

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
After enabling the Feature Flag `CDS_NG_TRIGGER_EXECUTION_REFACTOR` we noticed issues related to git-sync global context leaking between trigger executions. This PR is a fix for all these issues. Details of the issues and fix are below.

**[WHY WE CREATED THIS FF]**
Currently, the code ran before creating a pipeline execution in triggers is different from manual execution’s flow. In manual execution we use ExecutionHelper.java:buildExecutionArgs, while in triggers everything is done independently within TriggerExecutionHelper.java:createPlanExecution.  The Feature Flag CDS_NG_TRIGGER_EXECUTION_REFACTOR is an attempt to unify both flows, by making trigger’s flow leverage the same methods used by manual execution. This is important because:
- TriggerExecutionHelper.java:createPlanExecution  is a huge method, it has more than 250 lines. This makes it very hard to maintain.
- In the past few months, we’ve seen some changes added to manual execution flow which were not duplicated in the trigger’s execution method (input validations and filtering, especially related to migration to svc/env v2). Every time this happens, triggers start behaving differently from manual executions (throwing different error messages in case of wrong inputs, or wrongly filtering otherwise valid inputs that were provided).
So since trigger’s flow was pretty much an outdated copy/paste of manual execution flow, it became pretty obvious that the right thing to do was to unify both of them.

**[WHY ENABLING THIS FF CAUSE ISSUES WITH OPA INPUTS]**
Git-sync framework operates through global context variables, relevant here are NG_GIT_SYNC_CONTEXT and SCM_GIT_META_DATA_CONTEXT. In manual executions, we reset the whole global context on each request received by our APIs, so everything works smoothly. Triggers work via consumer/handler persistent threads, and we never really reset the global context at the beginning of each new execution.
- Whenever trigger receives an event, one of the first things we do is check if its pipelineBranchName and inputSetRefs are both empty. If they are, we call pmsPipelineService.getPipeline to fetch the pipeline entity from our DB, expecting it to be an inline pipeline. If the pipeline is of REMOTE type, we throw an error, because remote pipelines are not supposed to have both pipelineBranchName and inputSetRefs as null in the yaml. Even if the pipeline is remote and we don’t provide any git info when fetching it, it fetches it from the main branch of the repo. And there is a side-effect to pmsPipelineService.getPipeline : it populatesSCM_GIT_META_DATA_CONTEXT with git details (main branch, repo, etc) corresponding to the fetched pipeline’s yaml file.
- Although it is not possible to create a broken trigger like this from the UI, this case is not unusual at all - because of the new “migrate pipeline to git” feature. When customers migrate their inline pipelines to git, they are supposed to go and manually add  pipelineBranchName  and inputSetRefs to their triggers’ yamls. Until they do that, their triggers will be in this broken state.
- The first pipeline fetching attempt (mentioned above) done in triggers flow is not done behind a context guard, so the global context SCM_GIT_META_DATA_CONTEXT leaks to the thread’s global context (both in old and refactored trigger’s flow).
- In refactored trigger’s flow, we use ExecutionHelper.java:buildExecutionArgs to fetch gitDetails for OPA inputs, while in the old flow we did it differently. ExecutionHelper.java:buildExecutionArgs uses global context SCM_GIT_META_DATA_CONTEXT to populate gitDetails for OPA. So after enabling the FF, we had gitDetails from previous attempted executions of broken triggers leaking and being used to populate OPA inputs of the next trigger executions.

**[TRIGGER EXECUTIONS INTERMITTENTLY IGNORING PipelineBranchName OF TRIGGER EXECUTIONS]**
As we saw above, whenever some customer executed a trigger for remote pipeline with empty  pipelineBranchName and inputSetRefs , the consumer/handler thread’s global context got polluted with its SCM_GIT_META_DATA_CONTEXT . In the refactored execution flow we are using ExecutionHelper.java:buildExecutionArgs , and inside this method we call the seemingly innocent method ExecutionHelper.java:buildExecutionMetadata to get the ExecutionMetadata for the execution. But, as it happens, this method has the side-effect of overriding in global context the values of NG_GIT_SYNC_CONTEXT with the content of  SCM_GIT_META_DATA_CONTEXT ! And to fetch the pipeline entity, we actually use the Git config values present in NG_GIT_SYNC_CONTEXT , which just got overwritten. 

***[THE FIX]***
I think the best way of avoiding issues of these kind is to just reset the global context upon each trigger execution, just like we do in the manual execution case.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 500 at r1](https://reviewable.io/reviews/harness/harness-core/48318#-NWG2kNV4jmPPTMKLYnN:-NWG2kNV4jmPPTMKLYnO:b-ti98d8) ([raw file](https://github.com/harness/harness-core/blob/e2a6cf122f7cadb84aa98850cea43b1a07bfcf2e/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L500)):*
> ```Java
>       gitSyncBranchContextByteString = pmsGitSyncHelper.serializeGitSyncBranchContext(gitSyncBranchContext);
> 
>       if (featureFlagService.isEnabled(ngTriggerEntity.getAccountId(), FeatureName.CDS_NG_TRIGGER_EXECUTION_REFACTOR_GIT_SYNC)) {
> ```

@vcalasansh should we introduce one more FF? this FF itself is new in prod, so we can make changes for this flow only?
cc: @mohitg0795 @rohitk-h

**Comment by rohitk-h** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 500 at r1](https://reviewable.io/reviews/harness/harness-core/48318#-NWG2kNV4jmPPTMKLYnN:-NWItvw-6C4mCr7FKRec:b-fej50w) ([raw file](https://github.com/harness/harness-core/blob/e2a6cf122f7cadb84aa98850cea43b1a07bfcf2e/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L500)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@vcalasansh should we introduce one more FF? this FF itself is new in prod, so we can make changes for this flow only?
cc: @mohitg0795 @rohitk-h 
</blockquote></details>

agree, we should use the same FF. Any reason we are not?

**Comment by vcalasansh** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 455 at r2](https://reviewable.io/reviews/harness/harness-core/48318#-NWefcfP31BGi7C9T726:-NWefcfP31BGi7C9T727:b3jfqb1) ([raw file](https://github.com/harness/harness-core/blob/f64ba60bd5099ff937a3596d6da7e87c38cad248/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L455)):*
> ```Java
>       return planExecution;
>     } catch (Exception e) {
>       GitAwareContextHelper.initDefaultScmGitMetaDataAndRequestParams();
> ```

@vcalasansh do we need to do this again? wouldn't the top setting up of thread context is good enough as its a single thread, if another flow comes, that would be in another thread
cc: @mohitg0795 



_Code quote:_
```Java
      // Reset git-sync global context again,
      // thus avoiding any issues with global context leaking in the next trigger run.
      GitAwareContextHelper.initDefaultScmGitMetaDataAndRequestParams();
      return planExecution;

    } catch (Exception e) {
      GitAwareContextHelper.initDefaultScmGitMetaDataAndRequestParams();
```

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/48318#-NWg4kiT4YyMZVEXr0uO:-NWg4kiT4YyMZVEXr0uP:b-bxoe70) ([raw file](https://github.com/harness/harness-core/blob/f64ba60bd5099ff937a3596d6da7e87c38cad248/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L53)):*
> ```Java
>     GlobalContextManager.upsertGlobalContextRecord(
>         GitSyncBranchContext.builder().gitBranchInfo(GitEntityInfo.builder().build()).build());
>     GlobalContextManager.upsertGlobalContextRecord(
> ```

why do we need to init scm git metadata?

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/48318#-NWg4kiT4YyMZVEXr0uO:-NWg4s_Y-x6OHr-GczKk:b-15dxom) ([raw file](https://github.com/harness/harness-core/blob/f64ba60bd5099ff937a3596d6da7e87c38cad248/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to init scm git metadata?
</blockquote></details>

Ok I see later in some code its mentioned its required so that there's no old context available.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 455 at r2](https://reviewable.io/reviews/harness/harness-core/48318#-NWefcfP31BGi7C9T726:-NWm-uc5-OOkh1OrYyMW:b6an6jr) ([raw file](https://github.com/harness/harness-core/blob/f64ba60bd5099ff937a3596d6da7e87c38cad248/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L455)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

Thanks for looking into this man! Yes, it is necessary, because the methods called inside `createPlanExecutionV2` have side-effects in git-sync's global context, so we need to reset global context before ending the method, otherwise the same thread can pick up another execution later and will have its global context polluted by a previous execution. 
- I think the cleanest way of doing this is just resetting the global context at the beginning of all trigger execution flows (in `WebhookEventStreamListener`, `PollingEventStreamListener` and `ScheduledTriggerHandler`).
- But doing it would affect the old (before refactor) trigger's flow, and I don't really want to touch it now. 
- So after we GA this FF, I will clean up the FF and do the context resetting only once at the beginning of each trigger execution.
</blockquote></details>

done, discussed offline

**Comment by vcalasansh** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 455 at r2](https://reviewable.io/reviews/harness/harness-core/48318#-NWefcfP31BGi7C9T726:-NWpiFV84ep9Gc6QNoIB:b-hmxi43) ([raw file](https://github.com/harness/harness-core/blob/f64ba60bd5099ff937a3596d6da7e87c38cad248/pipeline-service/service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L455)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

done, discussed offline
</blockquote></details>

As discussed, we are resetting contexts multiple times just to be safe here. Ideally, there shouldn't be resetting of context involved anywhere here. It should be automatically done by the thread manager.
As discussed with @vcalasansh, this is just an interim fix but we are going to fix it the right way soon.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48318)* status: :shipit: complete! ✓

**Pull request merged**
