### PR TITLE
feat: [CDS-83394]: support linking, execution and reconcile for remote infra

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. simplified and generalised logic for getting git context for infra based on env metadata and branch used in linking
2. reconcile / refresh for remote infra 
3. fixed a bug with artifact dropdowns when env is statically linked 
4. infra visitor helper and filter creator to use correct git context 
5. set correct Source Principal in DeploymentStageFilterJsonCreatorV2. 

Tested 
1. execution with env static linking / dynamic linking 
2. reconcile and refresh of pipelines
3. saving of inline / remote pipelines with static/dynamic linking

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger compile, uts

**Comment by hingerabhinav** [comment]
trigger uts, compile

**Comment by hingerabhinav** [comment]
trigger uts, compile

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java` line 117 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-Njl4hlk5Y7tq2FJVCQR:-Njl4hlk5Y7tq2FJVCQS:bjfebv) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java#L117)):*
> ```Java
>               accountIdentifier, orgIdentifier, projectIdentifier, envRef, environmentBranch);
> 
>           try (EntityGitDetailsGuard entityGitDetailsGuard = new EntityGitDetailsGuard(gitContextForInfra)) {
> ```

do we need infra yaml in visitor helper or just identifier is enough ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 14 of 20 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 0 of 2 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java` line 117 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-Njl4hlk5Y7tq2FJVCQR:-NjlDPEXBUV78mJtJTRY:b8bl8en) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/127-cd-nextgen-entities/src/main/java/io/harness/cdng/infra/helper/InfraStructureDefinitionVisitorHelper.java#L117)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need infra yaml in visitor helper or just identifier is enough ?
</blockquote></details>

yes @yogesh-chauhan we need it. our logic to add setup usages from infra inputs to pipeline is based on fetching usages in infra YAML first and then comparing with inputs.

**Comment by hingerabhinav** [comment]
trigger ut5, ut6, ut7, ut8, ut9

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 130 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqxdC-CDMb2OEsVsx3:-NjqxdC0DvI7A7Sg9pGg:b-a9zqjo) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L130)):*
> ```Java
>       throw ex;
>     } catch (Exception ex) {
>       throw new InternalServerErrorException(
> ```

not logging the exception here?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 588 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqxnuKAhYl12tE9nYC:-NjqxnuKAhYl12tE9nYD:bmwwyrb) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L588)):*
> ```Java
>       }
>     }
>     String envGitBranch = contextMap.get(ENV_GIT_BRANCH);
> ```

what is this context map here?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EnvironmentRefreshHelper.java` line 276 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqxyRN0Y4V0guMRVkG:-NjqxyRN0Y4V0guMRVkH:b-vkuozl) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EnvironmentRefreshHelper.java#L276)):*
> ```Java
>   }
> 
>   private String getEnvironmentBranchFromNode(YamlNode envNodeInResolvedTemplatesYaml) {
> ```

this whole method seems generic, can't we move this to some util?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 675 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-Njqz2bU7Qxn7jtjoAn0:-Njqz2bU7Qxn7jtjoAn1:bwlhxap) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L675)):*
> ```Java
> 
>   @Override
>   public List<InfrastructureEntity> getAllInfrastructuresWithYamlFromEnvRef(String accountIdentifier,
> ```

Can't we do better modularisation here? I see almost same piece of code is written above

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 21 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 698 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqzJEY9ZBi6_wGC8OC:-NjqzJEY9ZBi6_wGC8OD:b-dlz50e) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L698)):*
> ```Java
> 
>     return infrastructureEntities;
>   }
> ```

line spacing missing

**Comment by hingerabhinav** [comment]
trigger uts

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 22 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 588 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqxnuKAhYl12tE9nYC:-Njvh8eS0vBMqSLWpe3S:bz0cik5) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L588)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what is this context map here?
</blockquote></details>

This context map is created after processing the pipeline YAML for artifact drodowns. We do the processing 1 time and create evaluator and context map together.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EnvironmentRefreshHelper.java` line 276 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqxyRN0Y4V0guMRVkG:-Njvh0x6BBoiZgLGepBZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/EnvironmentRefreshHelper.java#L276)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this whole method seems generic, can't we move this to some util?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 130 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqxdC-CDMb2OEsVsx3:-Njvh1iS2Pa8DFzZa4p3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L130)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

not logging the exception here?
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 675 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-Njqz2bU7Qxn7jtjoAn0:-Njvh41A8Wq-GiO3vCp2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L675)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can't we do better modularisation here? I see almost same piece of code is written above
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 698 at r5](https://reviewable.io/reviews/harness/harness-core/55606#-NjqzJEY9ZBi6_wGC8OC:-Njvh3kP4GUU4-Yc-IF0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2094173d1accd1811e9b63879b66f49ae7fdce0/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L698)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

line spacing missing
</blockquote></details>

Done.

**Comment by hingerabhinav** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Review by tchaurasiya — APPROVED** [review]

**Comment by hingerabhinav** [comment]
trigger review

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55606)* status: 22 file(s) to review. 5. unresolved discussions.

**Pull request merged**
