### PR TITLE
[feat]: [CDS-80945]: Added Support for Creation, Get and Update of Infrastructure on Remote.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes
Changes: Have added for Create, Get and Update flow for remote Infra.
Testing: Create,Get and Update Flows were tested and expected changes were observed on the remote repo.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53805)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSdJuw736LTDEPsUIz:-NgSdJuxCN8tQ3dTJcIK:b-noyg0o) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L39)):*
> ```Java
>       @NotEmpty String projectIdentifier, @NotEmpty String envIdentifier, @NotEmpty String infraIdentifier);
> 
>   Optional<InfrastructureEntity> get(@NotEmpty String accountId, @NotEmpty String orgIdentifier,
> ```

does this work with org/account scoped infra ?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/infrastructure/custom/InfrastructureRepositoryCustomImpl.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSeYkJD_k8ebfDiqrV:-NgSeYkJD_k8ebfDiqrW:bldwhha) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/repositories/infrastructure/custom/InfrastructureRepositoryCustomImpl.java#L117)):*
> ```Java
>     return Failsafe.with(retryPolicy)
>         .get(()
>                  -> mongoTemplate.findAndModify(query, update, new FindAndModifyOptions().returnNew(true).upsert(true),
> ```

are we not supporting upsert for remote infra ?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53805)* status: 8 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSeHKPBXKu2i5iKIG4:-NgSt9LR20-DweLOWwWm:b8b46ge) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L37)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we update this same method ?
</blockquote></details>

The previous method had a lot of usages, and was used in many test class, updating that would mean a large part of the code, also in parallel with pipeline,InputSets and Services , they had different overloaded methods, so to be in the sync did this.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSdJuw736LTDEPsUIz:-NgSt58v8becxIAxFAh5:b-9r051f) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L39)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this work with org/account scoped infra ?
</blockquote></details>

Have removed annotations.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/infrastructure/custom/InfrastructureRepositoryCustomImpl.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSeYkJD_k8ebfDiqrV:-NgStVX84Dv3y2g8evYl:b72dnae) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/repositories/infrastructure/custom/InfrastructureRepositoryCustomImpl.java#L117)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we not supporting upsert for remote infra ?
</blockquote></details>

Upsert will be implemented in subsequent separate PRs with GitX settings

**Review by hingerabhinav — DISMISSED** [review]
> Reviewed 4 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53805)* status: 5 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSeHKPBXKu2i5iKIG4:-NgTGMQi0oGqNtGogLZK:bf02wf2) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L37)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

The previous method had a lot of usages, and was used in many test class, updating that would mean a large part of the code, also in parallel with pipeline,InputSets and Services , they had different overloaded methods, so to be in the sync did this.
</blockquote></details>

let's discuss once on this
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/infrastructure/custom/InfrastructureRepositoryCustomImpl.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSeYkJD_k8ebfDiqrV:-NgTGpstAAzYlcjZkw3x:b4c9lyr) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/repositories/infrastructure/custom/InfrastructureRepositoryCustomImpl.java#L117)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Upsert will be implemented in subsequent separate PRs with GitX settings
</blockquote></details>

:thumbsup:

**Comment by adivishy1** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/53805#-NgSeHKPBXKu2i5iKIG4:-NgTOu3C4wfA5GFWFwpg:b-6q3yal) ([raw file](https://github.com/harness/harness-core/blob/f913e1ed654047f43d20b2ea1c7a3b20cf1156be/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/InfrastructureEntityService.java#L37)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

let's discuss once on this
</blockquote></details>

i feel this is a better to write a new method and call that, else there will be too many code changes as @senjucanon2  mentioned

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 4 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53805)* status: 3. unresolved discussions.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
Please write UTs for the same

**Review by yogesh-chauhan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 1 of 1 files at r4, 4 of 4 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53805#-:-NgTjCfj8FbB8X4BVj7b:bnfp4nl)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by hingerabhinav — DISMISSED** [review]
> Reviewed 3 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53805)* status: 1 file(s) to review. 1. unresolved discussions.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger ut9

**Review by yogesh-chauhan — DISMISSED** [review]

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger uts

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53805)* status: 3 file(s) to review. 1. unresolved discussions.

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
