### PR TITLE
fix: [CDS-41706]: Error msg improvement for Helm upgrade when there a…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…re no releases in Deployed state

## Describe your changes
When there are no releases in the release history with “Deployed” status, this error occurs Release xxxxx has no deployed releases. Workarounds are to either delete the release or change the status of the helm-managed release secret manually. We are including the above as hints (as part of exception handling) in case of this error.

How error message looks like post fix:
image

Tests added - UT for the above

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41033)

### CODE REVIEW

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41033)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/41033#-NIWQbkl1W0D4y-T56RO:-NIWUjDNC86_GR-t3oer:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/996a05f18cce897baca44ca8cfab5b2739d1f68c/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java#L64)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

let's use apache commons for consistency
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java` line 209 at r2](https://reviewable.io/reviews/harness/harness-core/41033#-NIWQolDEVpy3-nFR_4G:-NIWUn6qDHKFlorC1zPS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/996a05f18cce897baca44ca8cfab5b2739d1f68c/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/HelmClientRuntimeExceptionHandler.java#L209)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

lowerCase() returns null as-is. We can either add null checks or use below apache commons function (it returns empty string when null)
</blockquote></details>

Done.

**Comment by abosii-harness** [comment]
I'm confused about overall fix here, let's discuss this tomorrow

**Review by abosii-harness — CHANGES_REQUESTED** [review]
I'm confused about overall fix here, let's discuss this tomorrow

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41033#-:-NIYhTqR8T41UxyJ07H7:boi0qeo)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by achyuth-harness — COMMENTED** [review]
As discussed offline, have added error handling for rollback too

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41033#-:-NIb6xPK4SPOYIzpCJmh:b14ezqf)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Comment by achyuth-harness** [comment]
trigger ti1

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41033)* status: :shipit: complete! ✓

**Pull request merged**
