### PR TITLE
[feat]: [PIE-9142]: POJOs for storing expression usages

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Adding the POJOs for storing the expression usages.
```
ExpressionUsageEntity:
  String accountId;
  String pipelineId;
  Map<ExpressionCategory, List<ExpressionMetadata>> expressionsMap;

ExpressionMetadata:
  String fqn;
  String expressions;

```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45506)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45506)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/45506#-NRC0DSG949JivmL_fri:-NRC0DSG949JivmL_frj:bnohron) ([raw file](https://github.com/harness/harness-core/blob/6661c9037ce56a7028541d7eec5fac3a168fed4d/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java#L161)):*
> ```Java
>     bind(PmsGraphStepDetailsService.class).to(PmsGraphStepDetailsServiceImpl.class);
>     bind(ExecutionInputService.class).to(ExecutionInputServiceImpl.class);
>     bind(ExpressionUsageService.class).to(ExpressionUsageServiceImpl.class);
> ```

add singleton
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionCategory.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/45506#-NRC04eq55iILvwq88vB:-NRC04eq55iILvwq88vC:bolyau9) ([raw file](https://github.com/harness/harness-core/blob/6661c9037ce56a7028541d7eec5fac3a168fed4d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionCategory.java#L15)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public enum ExpressionCategory {
>   WHEN_CONDITION,
> ```

add unknown with 0 value
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/45506#-NRC0IQ4151HE3aQWCu0:-NRC0IQ4151HE3aQWCu1:b-s6u1aq) ([raw file](https://github.com/harness/harness-core/blob/6661c9037ce56a7028541d7eec5fac3a168fed4d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java#L38)):*
> ```Java
> public class ExpressionUsagesEntity {
>   @NotEmpty String accountIdentifier;
>   @FdUniqueIndex String pipelineIdentifier;
> ```

add org and project details as well

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45506)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java` line 161 at r1](https://reviewable.io/reviews/harness/harness-core/45506#-NRC0DSG949JivmL_fri:-NRC1fI76uIHLZtNiasu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6661c9037ce56a7028541d7eec5fac3a168fed4d/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationModule.java#L161)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add singleton
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionCategory.java` line 15 at r1](https://reviewable.io/reviews/harness/harness-core/45506#-NRC04eq55iILvwq88vB:-NRC1cuA0zse1XC0re2q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6661c9037ce56a7028541d7eec5fac3a168fed4d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionCategory.java#L15)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add unknown with 0 value
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/45506#-NRC0IQ4151HE3aQWCu0:-NRC1duy72iC9fO58DnF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6661c9037ce56a7028541d7eec5fac3a168fed4d/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add org and project details as well
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45506)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/45506#-NRCj0XO278nwa6CxsBl:-NRCj0XO278nwa6CxsBm:b-dv7l9j) ([raw file](https://github.com/harness/harness-core/blob/9c61b133f205dba640c7954ec0e5ea4cec82255b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java#L38)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ExpressionUsagesEntity {
>   @NotEmpty String accountIdentifier;
> ```

Add uuid field

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/45506#-NRCj7E40X_FZ-O6x4OO:-NRCj7E40X_FZ-O6x4OP:bpk5kio) ([raw file](https://github.com/harness/harness-core/blob/9c61b133f205dba640c7954ec0e5ea4cec82255b/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExpressionUsagesEntity.java#L37)):*
> ```Java
> @TypeAlias("expressionUsage")
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ExpressionUsagesEntity {
> ```

Add this in OrchestrationBeansContractMorphiaRegistrar.java 
so that indexes are created automatically.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45506)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
Discussed offline. Will do it in next pr.

**Pull request merged**
