### PR TITLE
fix: [PL-29540]: Error log cleanup in manager

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40199)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40199)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/smtp/SmtpNgServiceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4D8PW42wG1CEkbcCS:-NH4D8PW42wG1CEkbcCT:bwrc4hi) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/120-ng-manager/src/main/java/io/harness/ng/core/smtp/SmtpNgServiceImpl.java#L91)):*
> ```Java
>     SettingAttribute response = getResponse(ngSMTPSettingsHttpClient.getSmtpSettings(accountId));
>     if (response == null) {
>       log.warn("Smtp is not configured. Please create a new config");
> ```

This should be INFO I think
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 340 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4EVPE2nD0BKb0WO5r:-NH4EVPE2nD0BKb0WO5s:bwekt1l) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L340)):*
> ```Java
>           apiKeyCache.put(getKeyForAPIKeyCache(accountId, apiKeyEntry.getDecryptedKey()), apiKeyEntry);
>         }
>       } catch (GeneralException ex) {
> ```

Why this?

Cann't we remove notNullCheck
___
*[`960-persistence/src/main/java/io/harness/persistence/HQuery.java` line 293 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4DSgfCrcxnqRvfryw:-NH4DSgfCrcxnqRvfryx:b-q834os) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/960-persistence/src/main/java/io/harness/persistence/HQuery.java#L293)):*
> ```Java
> 
>     if (!this.getChildren().stream().map(Criteria::getFieldName).anyMatch(requiredFilterArgs::contains)) {
>       log.warn("QUERY-ENFORCEMENT: appId or accountId must be present in List(Object/Key)/Get/Count/Search query",
> ```

Should this be a WARN. I think the idea was in multitenant system, always specify accountId or explicitly excludeAuthority.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4Dnj9DDptjQ6aKusI:-NH4Dnj9DDptjQ6aKusJ:b-u83xw9) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java#L68)):*
> ```Java
>         jsonNodeMap.put(cacheKey, expansionResponse);
>         expansionResponseBatchBuilder.addExpansionResponseProto(convertToResponseProto(jsonNodeMap.get(cacheKey), fqn));
>       } catch (Exception ex) {
> ```

Get it reviewed from Archit once if not done yet

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40199)* status: 11 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/smtp/SmtpNgServiceImpl.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4D8PW42wG1CEkbcCS:-NH4G_T_2Ln6ndKdFNo9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/120-ng-manager/src/main/java/io/harness/ng/core/smtp/SmtpNgServiceImpl.java#L91)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This should be INFO I think
</blockquote></details>

Done.



_Code quote:_
```Java
mtp is not configured. Please create a new config
```
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 340 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4EVPE2nD0BKb0WO5r:-NH4GxrA5uyuOv0V8dth:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L340)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this?

Cann't we remove notNullCheck
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/persistence/HQuery.java` line 293 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4DSgfCrcxnqRvfryw:-NH4Hq9z1flc_wbrxnRA:b-o1r5f7) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/960-persistence/src/main/java/io/harness/persistence/HQuery.java#L293)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be a WARN. I think the idea was in multitenant system, always specify accountId or explicitly excludeAuthority.
</blockquote></details>

We are still proceeding with the query even though when the call comes here. You are saying it should be error only?



_Code quote:_
```Java
QUERY-ENFORCEMENT: appId or accountId must be present in List(Object/Key)/Get/Count/Search query
```
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/40199#-NH4Dnj9DDptjQ6aKusI:-NH4IGl82PT-TQ_zDEf1:b-bts9ep) ([raw file](https://github.com/harness/harness-core/blob/ccf8486ace93d63f545de4ddae90f18ede4693e5/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java#L68)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Get it reviewed from Archit once if not done yet
</blockquote></details>

He approved them already

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40199#-:-NHO-ziX5heDF5KTfvVf:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 5 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40199)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3343 at r4](https://reviewable.io/reviews/harness/harness-core/40199#-NHO1BO-ALHrGrUEWwQR:-NHO1BO-ALHrGrUEWwQS:b-7vf83b) ([raw file](https://github.com/harness/harness-core/blob/39bd48ae252f185ce5effc41dc386e15c73bdcd1/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3343)):*
> ```Java
>         } else {
>           delegateMetricsService.recordDelegateMetrics(delegate, DELEGATE_RESTARTED);
>           log.debug("Delegate restarted");
> ```

This should be warn , I don't think we see debug log by default on stackdriver.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40199)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3343 at r4](https://reviewable.io/reviews/harness/harness-core/40199#-NHO1BO-ALHrGrUEWwQR:-NHO34tGEGCw3Cy3tPBu:b-ajv4dj) ([raw file](https://github.com/harness/harness-core/blob/39bd48ae252f185ce5effc41dc386e15c73bdcd1/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3343)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This should be warn , I don't think we see debug log by default on stackdriver.
</blockquote></details>

Delegate team wanted this to be a debug log. slack link -  https://harness.slack.com/archives/CSL96M7UG/p1668493812670659

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40199)* status: :shipit: complete! ✓

**Pull request merged**
