### PR TITLE
feat: [CDS-53680]: handling destroy process graceful sigterm for CLI

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
The issue was that customer reported that their terraform state is always locked after they abort the pipeline, so they would expect we close the process with sigterm not sigkill.  We use same CLI process executor for multiple swimlines to destroy the process.
After the fix, for example when we trigger abort pipeline from UI during  acquire state lock, we can see these logs in UI execution logs, that we gracefully destroying the process, and the lock will be available. 
```
Acquiring state lock. This may take a few moments...
Stopping operation...
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
╷
Gracefully shutting down..
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)

### CODE REVIEW

**Review by alebuh — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: Some of the checks are too old. 12 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: Some of the checks are too old. 

___
*[`960-api-services/src/main/java/io/harness/terraform/TerraformClientImpl.java` line 331 at r2](https://reviewable.io/reviews/harness/harness-core/44062#-NOhxD2W9PprTFTMFsNV:-NOhxD2X7zmkOO4fVdvt:b-ihpwdl) ([raw file](https://github.com/harness/harness-core/blob/e2f15fa4b97706d53734c387557f742665b7dfb2/960-api-services/src/main/java/io/harness/terraform/TerraformClientImpl.java#L331)):*
> ```Java
> 
>     return cliHelper.executeCliCommand(command, timeoutInMillis, envVariables, scriptDirectory, executionLogCallBack,
>         loggingCommand, logOutputStream, new TerraformCliErrorLogOutputStream(executionLogCallBack), 30);
> ```

nit: can this be a constant?

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: Some of the checks are too old.

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terraform/TerraformClientImpl.java` line 331 at r2](https://reviewable.io/reviews/harness/harness-core/44062#-NOhxD2W9PprTFTMFsNV:-NOi-F4w5-f3vUHxpbn1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e2f15fa4b97706d53734c387557f742665b7dfb2/960-api-services/src/main/java/io/harness/terraform/TerraformClientImpl.java#L331)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: can this be a constant?
</blockquote></details>

done

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: 1 of 2 approvals obtained.

**Review by alebuh — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: :shipit: complete! ✓

**Review by alebuh — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44062)* status: :shipit: complete! ✓

**Pull request merged**
