### PR TITLE
techdebt: [PIE-2752]: Remove 860-orchestration-steps dependency from cv-nextgen

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32795)

### CODE REVIEW

**Review by hextechpal — DISMISSED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795#-:-N1I2xqF9MaN4aSELd9G:bnfp4nl)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795#-:-N1JBJ_gAMpibG0arURs:bnfp4nl)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795)* status: 1 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 17 files at r1, 1 of 1 files at r2, 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795)* status: 1 file(s) to review.

**Review by hextechpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795#-:-N1MnPcr5c7Xm2UQ5FO2:bnfp4nl)* status: 1 file(s) to review.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
discussed offline, some files rather than being moved to 882 sdk-core it should go to 878

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32795#-:-N1Mo2Ti4iCWG_GMpy1j:b-giki2w)* status: :shipit: complete! ✓

**Pull request merged**
