### PR TITLE
fix: [CDB-301]: ignore update events for untracked fields

### PR DESCRIPTION
**Pull request by sean-harness**
## Describe your changes
When receiving update events, check the changed fields against the fields which we record in Timescale before processing the event.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35908)

### CODE REVIEW

**Comment by sean-harness** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35908)

**Comment by sean-harness** [comment]
trigger ti0

**Comment by sean-harness** [comment]
trigger ti0,ti2,ti3,ti4

**Review by Rohit-Kaliki — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35908#-:-N8ZRbuR0blGm7-23_Ud:bnfp4nl)* status: :shipit: complete! ✓

___
*[`110-change-data-capture/src/main/java/io/harness/changestreamsframework/ChangeTracker.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/35908#-N8ZPUCY-BzptaHBPz2O:-N8ZPUCY-BzptaHBPz2P:b-y545y2) ([raw file](https://github.com/harness/harness-core/blob/6f3ebeb48ad7d55704fac995784a484ab49ee3bf/110-change-data-capture/src/main/java/io/harness/changestreamsframework/ChangeTracker.java#L163)):*
> ```Java
>   }
> 
>   private <T extends PersistentEntity> boolean hasTrackedFieldBeenChanged(
> ```

We will need to double check on any Handlers which don't have the fields to null, if they have any fields that are being tracked.

**Comment by sean-harness** [comment]
*[`110-change-data-capture/src/main/java/io/harness/changestreamsframework/ChangeTracker.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/35908#-N8ZPUCY-BzptaHBPz2O:-N8ZS3kb3WtZ-WDlff8o:b-im6s1s) ([raw file](https://github.com/harness/harness-core/blob/6f3ebeb48ad7d55704fac995784a484ab49ee3bf/110-change-data-capture/src/main/java/io/harness/changestreamsframework/ChangeTracker.java#L163)):*
<details><summary><i>Previously, Rohit-Kaliki (K Rohit Reddy) wrote…</i></summary><blockquote>

We will need to double check on any Handlers which don't have the fields to null, if they have any fields that are being tracked. 
</blockquote></details>

There is a check for handlers which have no fields defined 



_Code quote:_
```Java
    if (subscribedFields.isEmpty()) {
      return true;
    }
```

**Review by Rohit-Kaliki — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35908)* status: :shipit: complete! ✓

**Pull request merged**
