### PR TITLE
[feat]: [CVNG-4077]: adding SLO policy yaml expansion

### PR DESCRIPTION
**Pull request by deepak-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30109)

Is it new task type? YES
Did you make changes to the code in a backward-compatible manner?
1. will the new version of the delegate receive old version task and process? YES
2. If new version of the manager receives response for the old task will it be able to handle it successfully? YES

### CODE REVIEW

**Review by namanvermah — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30109)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30109#-:-MtrLabnBDnbbbeuriHx:bnfp4nl)* status: :shipit: complete! ✓

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30109)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/beans/SLOPolicyDTO.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/30109#-MtrSg_40plKTu36P9Qe:-MtrSg_40plKTu36P9Qf:bcwv1fr) ([raw file](https://github.com/harness/harness-core/blob/9b017c3f40f1d15ff9fb6d24b30b8b75afff74e8/300-cv-nextgen/src/main/java/io/harness/cvng/governance/beans/SLOPolicyDTO.java#L31)):*
> ```Java
> @OwnedBy(CV)
> public class SLOPolicyDTO implements YamlDTO {
>   @JsonProperty("sloErrorBudgetRemaining") @Valid double sloErrorBudgetRemaining;
> ```

I think we should make it Double 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java, line 54 at r1](https://reviewable.io/reviews/harness/harness-core/30109#-MtrQidX2ycEc3xnWtRO:-MtrQidX2ycEc3xnWtRP:bqlxsuh) ([raw file](https://github.com/harness/harness-core/blob/9b017c3f40f1d15ff9fb6d24b30b8b75afff74e8/300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java#L54)):*
> ```Java
>     String serviceRef = fieldValue.get(SERVICE_CONFIG).get(SERVICE_REF).asText();
>     String environmentRef = fieldValue.get(INFRASTRUCTURE).get(ENVIRONMENT_REF).asText();
>     String monitoredServiceRef = serviceRef + MONITORED_SERVICE_DELIMITER + environmentRef;
> ```

monitoredServiceService using serviceRef and envRef
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/30109#-MtrTA5yEcyo6cLLejtd:-MtrTA5yEcyo6cLLejte:b-4zwwi4) ([raw file](https://github.com/harness/harness-core/blob/9b017c3f40f1d15ff9fb6d24b30b8b75afff74e8/300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java#L67)):*
> ```Java
>       double sloErrorBudgetRemaining = Double.MAX_VALUE;
>       for (ServiceLevelObjective serviceLevelObjective : serviceLevelObjectiveList) {
>         Preconditions.checkState(serviceLevelObjective.getServiceLevelIndicators().size() == 1,
> ```

we should move it to serviceLevelObjective. 
We can also think about making it parallel 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java, line 87 at r1](https://reviewable.io/reviews/harness/harness-core/30109#-MtrSHPNDMV59mQ8NuMA:-MtrSHPNDMV59mQ8NuMB:b5a7th0) ([raw file](https://github.com/harness/harness-core/blob/9b017c3f40f1d15ff9fb6d24b30b8b75afff74e8/300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java#L87)):*
> ```Java
>       }
>       sloPolicyDTO = SLOPolicyDTO.builder()
>                          .sloErrorBudgetRemaining(sloErrorBudgetRemaining)
> ```

sloErrorBudgetRemainingPercentage



_Code quote:_
```Java
sloErrorBudgetRemaining(
```
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/governance/SLOPolicyExpansionHandlerTest.java, line 61 at r1](https://reviewable.io/reviews/harness/harness-core/30109#-MtrUxgADBZgrOOwMJ3m:-MtrUxgADBZgrOOwMJ3n:bfhpdbs) ([raw file](https://github.com/harness/harness-core/blob/9b017c3f40f1d15ff9fb6d24b30b8b75afff74e8/300-cv-nextgen/src/test/java/io/harness/cvng/governance/SLOPolicyExpansionHandlerTest.java#L61)):*
> ```Java
> public class SLOPolicyExpansionHandlerTest extends CvNextGenTestBase {
>   @InjectMocks SLOPolicyExpansionHandler sloPolicyExpansionHandler;
>   @Mock ServiceLevelObjectiveService serviceLevelObjectiveService;
> ```

let's see if we can write without mocks.

**Comment by deepak-harness** [comment]
trigger ti0

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30109#-:-Mtv34e9AImF8IsvCyUI:bnfp4nl)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 8 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30109)* status: :shipit: complete! ✓

**Pull request merged**
