### PR TITLE
[fix]: [PL-29511]: Updating redis connectionMinimumIdleSize to use same value as REDIS_NETTY_THREADS

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
… value as REDIS_NETTY_THREADS

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39996)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39996)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`dockerization/manager/scripts/replace_configs.sh` line 764 at r1](https://reviewable.io/reviews/harness/harness-core/39996#-NG_Vwey4kzc099x5DM2:-NG_Vwey4kzc099x5DM3:b-so5cjm) ([raw file](https://github.com/harness/harness-core/blob/5aa04a635e3d455f35f76a3d78b14006af6347b1/dockerization/manager/scripts/replace_configs.sh#L764)):*
> ```Shell
>   export REDIS_NETTY_THREADS; yq -i '.nettyThreads=env(REDIS_NETTY_THREADS)' $REDISSON_CACHE_FILE
> 
>   export REDIS_NETTY_THREADS; yq -i '.redisLockConfig.connectionMinimumIdleSize=env(REDIS_NETTY_THREADS)' $CONFIG_FILE
> ```

Can we make this change in RedissonClientFactory so that it is reflected for all services
___
*[`dockerization/manager/scripts/replace_configs.sh` line 766 at r1](https://reviewable.io/reviews/harness/harness-core/39996#-NG_W-w9C1wtXYc0oHcq:-NG_W-w9C1wtXYc0oHcr:b-2ywtuw) ([raw file](https://github.com/harness/harness-core/blob/5aa04a635e3d455f35f76a3d78b14006af6347b1/dockerization/manager/scripts/replace_configs.sh#L766)):*
> ```Shell
>   export REDIS_NETTY_THREADS; yq -i '.redisLockConfig.connectionMinimumIdleSize=env(REDIS_NETTY_THREADS)' $CONFIG_FILE
>   export REDIS_NETTY_THREADS; yq -i '.redisAtmosphereConfig.connectionMinimumIdleSize=env(REDIS_NETTY_THREADS)' $CONFIG_FILE
>   export REDIS_NETTY_THREADS; yq -i '.singleServerConfig.connectionMinimumIdleSize=env(REDIS_NETTY_THREADS)' $REDISSON_CACHE_FILE
> ```

For cache, we can keep it like this because Redis Cache instance is not instantiated from RedissonClientFactory but via some other path

**Comment by ashishsanodia-harness** [comment]
*[`dockerization/manager/scripts/replace_configs.sh` line 764 at r1](https://reviewable.io/reviews/harness/harness-core/39996#-NG_Vwey4kzc099x5DM2:-NG_eZZB1y0mHJ90ErUr:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/5aa04a635e3d455f35f76a3d78b14006af6347b1/dockerization/manager/scripts/replace_configs.sh#L764)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we make this change in RedissonClientFactory so that it is reflected for all services
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`dockerization/manager/scripts/replace_configs.sh` line 766 at r1](https://reviewable.io/reviews/harness/harness-core/39996#-NG_W-w9C1wtXYc0oHcq:-NG_ejgu1NbjPX0KFUaL:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/5aa04a635e3d455f35f76a3d78b14006af6347b1/dockerization/manager/scripts/replace_configs.sh#L766)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

For cache, we can keep it like this because Redis Cache instance is not instantiated from RedissonClientFactory but via some other path
</blockquote></details>

Done

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39996#-:-NG_h5K03reb8QMDoh7f:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39996#-:-NG_hAEB2hFxaIoUeXNe:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39996)* status: :shipit: complete! ✓

**Pull request merged**
