### PR TITLE
feat: [SRM-14030]: Added Migration for updating tags in ServiceLevelObjective

### PR DESCRIPTION
**Pull request by arpit-harness**
…jective

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44213)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44213)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44213#-NOt3q9P0xDH3jezKK6L:-NOt3q9P0xDH3jezKK6M:b-od3mj0) ([raw file](https://github.com/harness/harness-core/blob/f34123d7bc1827be452c14c07a3f56f515d3e422/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java#L35)):*
> ```Java
>     Query<AbstractServiceLevelObjective> serviceLevelObjectiveQuery =
>         hPersistence.createQuery(AbstractServiceLevelObjective.class)
>             .filter(AbstractServiceLevelObjective.ServiceLevelObjectiveV2Keys.type, ServiceLevelObjectiveType.SIMPLE)
> ```

How many records are eligible for this migration? Would we need any indexing on the query fields to ensure the db is not loaded?

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44213)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44213#-NOt3q9P0xDH3jezKK6L:-NOt6tMfAOWVw8NJSb-k:b-nenked) ([raw file](https://github.com/harness/harness-core/blob/f34123d7bc1827be452c14c07a3f56f515d3e422/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java#L35)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

How many records are eligible for this migration? Would we need any indexing on the query fields to ensure the db is not loaded? 
</blockquote></details>

@dhruv-harness This would Impact all existing simple SLOs. @Varsha-lalwani Did a similar migration for Type field in SLOs.

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44213)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/44213#-NOt6l0a48hOb_Qxz_uP:-NOt6l0a48hOb_Qxz_uQ:bcy530a) ([raw file](https://github.com/harness/harness-core/blob/f34123d7bc1827be452c14c07a3f56f515d3e422/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java#L36)):*
> ```Java
>         hPersistence.createQuery(AbstractServiceLevelObjective.class)
>             .filter(AbstractServiceLevelObjective.ServiceLevelObjectiveV2Keys.type, ServiceLevelObjectiveType.SIMPLE)
>             .filter(AbstractServiceLevelObjective.ServiceLevelObjectiveV2Keys.tags, null);
> ```

why do we have this filter? We need to update for all, right?



_Code quote:_
```Java
.filter(AbstractServiceLevelObjective.ServiceLevelObjectiveV2Keys.tags, null);
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/44213#-NOt6sUkCYOBuja4E3XX:-NOt6sUkCYOBuja4E3XY:b-md2joo) ([raw file](https://github.com/harness/harness-core/blob/f34123d7bc1827be452c14c07a3f56f515d3e422/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java#L46)):*
> ```Java
>             hPersistence.createUpdateOperations(AbstractServiceLevelObjective.class)
>                 .set(AbstractServiceLevelObjective.ServiceLevelObjectiveV2Keys.tags, TagMapper.convertToList(tags)));
>         log.info("Updated serviceLevelObjectivesV2 {}", updateResults);
> ```

nit: updated tags in serviceLevelObjectivesV2



_Code quote:_
```Java
Updated serviceLevelObjectivesV2 
```

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44213#-:-NOvvXn1-lq0xSbfMdew:bnfp4nl)* status: 1. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44213)* status: 1. unresolved discussions.

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44213)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/44213#-NOt3q9P0xDH3jezKK6L:-NOx23dm4QhAOkKZRHkm:b-cgbe4r) ([raw file](https://github.com/harness/harness-core/blob/f34123d7bc1827be452c14c07a3f56f515d3e422/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/migration/list/UpdateTagsInServiceLevelObjectiveV2.java#L35)):*
<details><summary><i>Previously, arpit-harness wrote…</i></summary><blockquote>

@dhruv-harness This would Impact all existing simple SLOs. @Varsha-lalwani Did a similar migration for Type field in SLOs.
</blockquote></details>

Resolving this as the number of records is ~1000 and index is not required.

**Pull request merged**
