### PR TITLE
feat: [CDS-7771]: Updates `jsch` artifact for implementing `rsa-sha2-256` and `rsa-sha2-512`

### PR DESCRIPTION
**Pull request by gitNavV**
**Extends https://github.com/wings-software/jsch/pull/4**

JIRA: https://harness.atlassian.net/browse/CDS-7771
Test-plan: https://docs.google.com/spreadsheets/d/1XHvQuQlvo8S3pDvfFOakUFHteh8VfVYNLJvs8sTI9xc/edit#gid=733168098

- **Problem**
Patched `jsch` is outdated and doesn't support `rsa-sha2-256` / `rsa-sha2-512` which adds support for these new algorithms implemented

- **Solution**
Update Patched `jsch` with new artifact version having changes from the mentioned PR

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32017)

### CODE REVIEW

**Comment by gitNavV** [comment]
trigger messagecheck

**Comment by gitNavV** [comment]
trigger messagecheck

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32017)* status: :shipit: complete! ✓

**Comment by gitNavV** [comment]
trigger ti4

**Comment by gitNavV** [comment]
trigger feature-build

**Pull request merged**
