### PR TITLE
feat:[PL-25884]: changed list size for list branches Api

### PR DESCRIPTION
**Pull request by bhavya181**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34623)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 338 at r1](https://reviewable.io/reviews/harness/harness-core/34623#-N5Gr9rz7tJaAVDBzhZq:-N5Gr9rz7tJaAVDBzhZr:b-wbl02g) ([raw file](https://github.com/harness/harness-core/blob/0a52cc80c2254ecd3be44528581a392eafaef99e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L338)):*
> ```Java
>           description = GitSyncApiConstants.GIT_REPO_SCOPE_PARAM_MESSAGE) GitRepoScopeParams gitRepoScopeParams,
>       @Parameter(description = PAGE_PARAM_MESSAGE) @QueryParam(NGCommonEntityConstants.PAGE) @DefaultValue(
>           "0") int pageNum,
> ```

Lets remove the pageNum from the contract.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 342 at r1](https://reviewable.io/reviews/harness/harness-core/34623#-N5GrGLFAeSpu_yM1IiW:-N5GrGLFAeSpu_yM1IiX:bk47ffc) ([raw file](https://github.com/harness/harness-core/blob/0a52cc80c2254ecd3be44528581a392eafaef99e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L342)):*
> ```Java
>               + "(max 100)"
>               + "Default Value: 50") @QueryParam(NGCommonEntityConstants.SIZE) @DefaultValue("50") @Max(100)
>       int pageSize,
> ```

we should rename the param as well

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 311 at r1](https://reviewable.io/reviews/harness/harness-core/34623#-N5GrbuRBXRGEqK86qIe:-N5GrbuRBXRGEqK86qIf:b-vtdign) ([raw file](https://github.com/harness/harness-core/blob/0a52cc80c2254ecd3be44528581a392eafaef99e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L311)):*
> ```Java
>     final String slug = scmGitProviderHelper.getSlug(scmConnector);
>     final Provider provider = scmGitProviderMapper.mapToSCMGitProvider(scmConnector);
>     List<String> branchesList = new ArrayList<>();
> ```

Here we should make single call to "listBranchesWithDefault" SCM API and rest of the calls to usual listBranches API.

If we make all calls to "listBranchesWithDefault" API, then effectively, for N calls, we would be effectively making Nx2 calls to git, out of which (N-1) calls are redundant calls to fetch default API.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34623)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 338 at r1](https://reviewable.io/reviews/harness/harness-core/34623#-N5Gr9rz7tJaAVDBzhZq:-N5KQBH-CDCncnhKHT9p:b-5dfryo) ([raw file](https://github.com/harness/harness-core/blob/0a52cc80c2254ecd3be44528581a392eafaef99e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L338)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets remove the pageNum from the contract.
</blockquote></details>

removed it
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 342 at r1](https://reviewable.io/reviews/harness/harness-core/34623#-N5GrGLFAeSpu_yM1IiW:-N5KQ7mP-LmxDEVNRf09:b21jtwg) ([raw file](https://github.com/harness/harness-core/blob/0a52cc80c2254ecd3be44528581a392eafaef99e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L342)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should rename the param as well
</blockquote></details>

changed it, queryparam is size only

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34623)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 311 at r1](https://reviewable.io/reviews/harness/harness-core/34623#-N5GrbuRBXRGEqK86qIe:-N5iaJdG28XcKUNhxIsX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0a52cc80c2254ecd3be44528581a392eafaef99e/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L311)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here we should make single call to "listBranchesWithDefault" SCM API and rest of the calls to usual listBranches API.

If we make all calls to "listBranchesWithDefault" API, then effectively, for N calls, we would be effectively making Nx2 calls to git, out of which (N-1) calls are redundant calls to fetch default API.
</blockquote></details>

Done.

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 402 at r5](https://reviewable.io/reviews/harness/harness-core/34623#-N5kn8nS3fMo-g6NH5UV:-N5kn8nS3fMo-g6NH5UW:b-gxr19k) ([raw file](https://github.com/harness/harness-core/blob/58de0daf114644fc5b04b40ca57ade3ae17149e1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L402)):*
> ```Java
>       @Parameter(description = SIZE_PARAM_MESSAGE + "(max 100)"
>               + "Default Value: 50") @QueryParam(NGCommonEntityConstants.SIZE) @DefaultValue("50") @Max(100)
>       int listSize,
> ```

How do we limit the listSize? I mean where is the code for it?

**Comment by mohitg0795** [comment]
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/34623#-N5knMwv-hK8r7X9OBqj:-N5knMwv-hK8r7X9OBqk:brr4vlv) ([raw file](https://github.com/harness/harness-core/blob/58de0daf114644fc5b04b40ca57ade3ae17149e1/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L327)):*
> ```Java
>     pageNumber = listBranchesWithDefaultResponse.getPagination().getNext();
>     branchCount += listBranchesWithDefaultResponse.getBranchesCount();
>     ListBranchesResponse listBranchesResponse = null;
> ```

I have 2 points here:
1) I see we are using pageNumber. Bitbucket works on pointers. Then how did this code work for bitbucket?
2) There's a lot of code in a single block. Lets modularize it further. We should have smaller readable logical methods.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34623)* status: 3 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 402 at r5](https://reviewable.io/reviews/harness/harness-core/34623#-N5kn8nS3fMo-g6NH5UV:-N5un0scEfhbO_xPtI2p:b-o2r39f) ([raw file](https://github.com/harness/harness-core/blob/58de0daf114644fc5b04b40ca57ade3ae17149e1/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L402)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

How do we limit the listSize? I mean where is the code for it?
</blockquote></details>

It has max annotation on it
___
*[`952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java` line 327 at r5](https://reviewable.io/reviews/harness/harness-core/34623#-N5knMwv-hK8r7X9OBqj:-N5un5R368EBu0Cgnwvk:b-hb86z9) ([raw file](https://github.com/harness/harness-core/blob/58de0daf114644fc5b04b40ca57ade3ae17149e1/952-scm-java-client/src/main/java/io/harness/impl/scm/ScmServiceClientImpl.java#L327)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I have 2 points here:
1) I see we are using pageNumber. Bitbucket works on pointers. Then how did this code work for bitbucket?
2) There's a lot of code in a single block. Lets modularize it further. We should have smaller readable logical methods.
</blockquote></details>

Tested bitbucket also, its working

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34623#-:-N5ykEVY0E9iyZHnPPxz:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34623)* status: :shipit: complete! ✓

**Pull request merged**
