### PR TITLE
[fix]: [PLG-1859]: fixing community sign-up flow by increasing the initial delay=5s

### PR DESCRIPTION
**Pull request by neelam-harness**
## Describe your changes
Not able to sign up new user in Community Edition.
The actual sign up flow takes longer than 1 second to finish the sign-up process. Therefore, increasing the request initial_delay=5 seconds the sign-up runs successfully without any re-tries or issues.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42342)

### CODE REVIEW

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42342)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/CGRestUtils.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/42342#-NL7_eEdBf4wMjM7A_Bw:-NL7_eEeAk_Ko47Hq8fX:ba7yana) ([raw file](https://github.com/harness/harness-core/blob/c7818414af357609e48cc48262d942884df70273/970-ng-commons/src/main/java/io/harness/remote/client/CGRestUtils.java#L101)):*
> ```Java
>   private <T> RetryPolicy<Response<RestResponse<T>>> getRetryPolicy(String failureMessage) {
>     return new RetryPolicy<Response<RestResponse<T>>>()
>         .withBackoff(5, 10, ChronoUnit.SECONDS)
> ```

As discussed, can we avoid making changes here as its being used by many other services.
You can overload the same method with the new initial delay.

**Comment by neelam-harness** [comment]
trigger feature-build

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42342)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/42342#-NL7hzcY6gPX7ILDPZyg:-NL7hzcY6gPX7ILDPZyh:b-bx5z0a) ([raw file](https://github.com/harness/harness-core/blob/d57d3f71ad838076126f7a9eabd32dd89516dd50/920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java#L212)):*
> ```Java
>     try {
>       userInfo = getResponse(userClient.createCommunityUserAndCompleteSignup(signupRequest),
>           CGRestUtils.getRetryPolicy("SignupServiceImpl-Request failed", 5L, 10L, ChronoUnit.SECONDS));
> ```

nit: we can use static variables in place of direct values e.g. 5L, 10L.
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/CGRestUtils.java` line 101 at r1](https://reviewable.io/reviews/harness/harness-core/42342#-NL7_eEdBf4wMjM7A_Bw:-NL7kvhu2Nyy8-T8HAf_:brh5ekf) ([raw file](https://github.com/harness/harness-core/blob/c7818414af357609e48cc48262d942884df70273/970-ng-commons/src/main/java/io/harness/remote/client/CGRestUtils.java#L101)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

As discussed, can we avoid making changes here as its being used by many other services.
You can overload the same method with the new initial delay.
</blockquote></details>

pls revert your change.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42342)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by neelam-harness** [comment]
trigger feature-build

**Review by hekimoglu010 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42342)* status: :shipit: complete! ✓

**Comment by neelam-harness** [comment]
trigger checkstylecodeformat

**Review by pranil-harness — APPROVED** [review]

**Comment by neelam-harness** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Comment by neelam-harness** [comment]
trigger messagecheck

**Review by hekimoglu010 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42342)* status: 1 file(s) to review. Waiting on team(s): sto.

**Pull request merged**
