### PR TITLE
feat:[CDS-44555]: added connector outcome classes

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added connector outcome classes for:
Cloud Providers (AWS, Azure, GCP, Kubernetes Cluster)
Code Repositories (Git, GitHub, GitLab)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 52 of 74 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: :shipit: complete! ✓

**Comment by RishabhGupta34** [comment]
*[`954-connector-beans/src/test/java/io/harness/delegate/beans/connector/ConnectorOutcomeTest.java` line 127 at r2](https://reviewable.io/reviews/harness/harness-core/38972#-NEpDqh14KlT0FeJRbia:-NEqJHNY9DHKXAyJk2wU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/69cf446b9c6364e3dd63b41e12e0d1e26e90f56f/954-connector-beans/src/test/java/io/harness/delegate/beans/connector/ConnectorOutcomeTest.java#L127)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should not use this
</blockquote></details>

Done.

**Review by alebuh — COMMENTED** [review]
> Reviewed 26 of 74 files at r1, 2 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by sainath-b — APPROVED** [review]

**Review by devkimittal — APPROVED** [review]
> Reviewed 52 of 74 files at r1, 22 of 23 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 74 files at r1, 1 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: Some of the checks are too old. 2 change requests. 1. unresolved discussions. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpconnector/outcome/GcpConnectorOutcomeDTO.java` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/38972#-NFIdniU9L92jBFiHNV9:-NFIdniU9L92jBFiHNVA:b3j82xf) ([raw file](https://github.com/harness/harness-core/blob/007a36954d93947f9f1c21acf3808898ccdbef92/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpconnector/outcome/GcpConnectorOutcomeDTO.java#L2)):*
> ```Java
> /*
>  * Copyright 2021 Harness Inc. All rights reserved.
> ```

nit: copyright is outdated and missing class owner
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/k8Connector/outcome/KubernetesDelegateDetailsOutcomeDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/38972#-NFIeBV9BQ6CUJBBfa_K:-NFIeBVA8JsIRt4tyuvl:bhvt7pg) ([raw file](https://github.com/harness/harness-core/blob/007a36954d93947f9f1c21acf3808898ccdbef92/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/k8Connector/outcome/KubernetesDelegateDetailsOutcomeDTO.java#L22)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class KubernetesDelegateDetailsOutcomeDTO implements KubernetesCredentialSpecOutcomeDTO {
>   //  @NotNull @Size(min = 1) Set<String> delegateSelectors;
> ```

Should it be commented? And what need to be deleted?

**Comment by RishabhGupta34** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpconnector/outcome/GcpConnectorOutcomeDTO.java` line 2 at r3](https://reviewable.io/reviews/harness/harness-core/38972#-NFIdniU9L92jBFiHNV9:-NFIesDIBLEwKtlnkeEJ:b-5s5vy9) ([raw file](https://github.com/harness/harness-core/blob/007a36954d93947f9f1c21acf3808898ccdbef92/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpconnector/outcome/GcpConnectorOutcomeDTO.java#L2)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: copyright is outdated and missing class owner
</blockquote></details>

Will update copyright
GcpConnectorDTO as well doesn't have an owner, so didn't add in outcome class as well, should I mark `CDP` as owner?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: Some of the checks are too old. 2 change requests. 1. unresolved discussions. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/k8Connector/outcome/KubernetesDelegateDetailsOutcomeDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/38972#-NFIeBV9BQ6CUJBBfa_K:-NFIi4-U0t8JlDoDfCpz:b7rnx5z) ([raw file](https://github.com/harness/harness-core/blob/007a36954d93947f9f1c21acf3808898ccdbef92/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/k8Connector/outcome/KubernetesDelegateDetailsOutcomeDTO.java#L22)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

this is same object as `KubernetesDelegateDetailsDTO`, so added the same block of commented code
</blockquote></details>

I believe you can delete it, it was meant for deletion

**Comment by RishabhGupta34** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/k8Connector/outcome/KubernetesDelegateDetailsOutcomeDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/38972#-NFIeBV9BQ6CUJBBfa_K:-NFIkCM88sXThvaMGy5-:bpw5u4r) ([raw file](https://github.com/harness/harness-core/blob/007a36954d93947f9f1c21acf3808898ccdbef92/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/k8Connector/outcome/KubernetesDelegateDetailsOutcomeDTO.java#L22)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I believe you can delete it, it was meant for deletion
</blockquote></details>

Sure, will do as a part of separate PR

**Review by abosii-harness — APPROVED** [review]

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38972)* status: Some of the checks are too old.

**Pull request merged**
