### PR TITLE
[feat]: [CDP-20324]: artifactory endpoints

### PR DESCRIPTION
**Pull request by tmacari-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
All the logic from io.harness.artifactory.ArtifactoryServiceHelper is extracted from software.wings.helpers.ext.artifactory.ArtifactoryServiceImpl so it could be used in NG service: io.harness.artifactory.ArtifactoryNgServiceImpl

**Comment by tmacari-harness** [comment]
All the logic from ArtifactoryClientImpl.java  is just migrated from "400-rest/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java"

**Review by nassergonzalez — COMMENTED** [review]
> Reviewed 66 of 80 files at r1, 15 of 17 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)* status: Some of the checks are too old. 84 file(s) to review. 0 of 2 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 231 at r5](https://reviewable.io/reviews/harness/harness-core/30266#-MuogoBk1ePJ90t6ilna:-MuogoBm-ACLeekK3k_i:b-6xlh3d) ([raw file](https://github.com/harness/harness-core/blob/a77a21ae2aab2e544b7579b470d0406e0efb834f/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L231)):*
> ```Java
>       if (repositories.isEmpty()) {
>         // Better way of handling Unauthorized access
>         log.info("Repositories are not available of package types {} or User not authorized to access artifactory",
> ```

If repositories are empty, shouldn't we need to raise that as an exception so the front end displays that?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)* status: Some of the checks are too old. 84 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, line 231 at r5](https://reviewable.io/reviews/harness/harness-core/30266#-MuogoBk1ePJ90t6ilna:-MuolU28Av9d1MTwsiEE:b-9b30aw) ([raw file](https://github.com/harness/harness-core/blob/a77a21ae2aab2e544b7579b470d0406e0efb834f/960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java#L231)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

If repositories are empty, shouldn't we need to raise that as an exception so the front end displays that?
</blockquote></details>

All code from this class is  extracted from ArtifactoryService so we could reuse it in NG (it already works like this in CG)

**Review by nassergonzalez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)* status: Some of the checks are too old. 84 file(s) to review. 1 of 2 approvals obtained.

**Review by nassergonzalez — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266#-:-MuorTCM0I20bq8MjP-q:bnfp4nl)* status: Some of the checks are too old. 84 file(s) to review. 1 of 2 approvals obtained.

**Review by allofthesepeople — APPROVED** [review]
I can't comment to much on the actual language or org-style but the logic appears to be correct.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 67 of 80 files at r1, 16 of 17 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)* status: Some of the checks are too old. 1 file(s) to review. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 71 at r2](https://reviewable.io/reviews/harness/harness-core/30266#-MuQhA3jC1hsF3TtoG1z:-MuQhA3jC1hsF3TtoG2-:bus2po7) ([raw file](https://github.com/harness/harness-core/blob/fd5fa3dfa51a99cfb56d7488deb8bab5009bd91c/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L71)):*
> ```Java
>         connectorRef.getOrgIdentifier(), connectorRef.getProjectIdentifier(), connectorRef.getIdentifier());
>     if (!connectorDTO.isPresent()
>         || ConnectorType.ARTIFACTORY != (connectorDTO.get().getConnector().getConnectorType())) {
> ```

nit: any reasons why this need to be wrapped in ( )?

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)* status: 2 file(s) to review.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30266)* status: 2 file(s) to review. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, line 71 at r2](https://reviewable.io/reviews/harness/harness-core/30266#-MuQhA3jC1hsF3TtoG1z:-MupGjx66ofB7KycmR76:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/fd5fa3dfa51a99cfb56d7488deb8bab5009bd91c/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java#L71)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

No, will change
</blockquote></details>

Done



_Code quote:_
```Java
ArtifactoryResourceServiceImpl
```

**Comment by tmacari-harness** [comment]
trigger OpenJDKPortalWithPatch-openjdkportalfeature

**Pull request merged**
