### PR TITLE
feat: [PL-29241]: added index on resourceLookup query

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
added index on resourceLookup query
The api which is failing has two two type of queries 

`db.getCollection('resourceLookup').find({accountId: "zEaak-FLS425IEO7OLzMUg", "accountId": {"$in": ["zEaak-FLS425IEO7OLzMUg"]}, "resourceType": {"$in": ["CLOUD_PROVIDER"]} }).sort({"resourceType": 1})`

`db.getCollection('resourceLookup').find({accountId: "zEaak-FLS425IEO7OLzMUg", "accountId": {"$in": ["zEaak-FLS425IEO7OLzMUg"]}, "resourceId": {"$in": ["AXVCa0yPS7Wordseu33UYw"]} }).sort({"resourceId": 1})
`

for the first query, index is not properly picked up though the correct index is present, added sort on accountId, now the index is correctly picked, as this query is for single account, sorting does not make any impact.
Second query is correctly picking up the index.

for first query
Screenshot 2022-11-09 at 1 39 59 PM

I have written a doc as well https://docs.google.com/document/d/1vrAQvDOoHsqrmt7802ohuT0wDaiAKkVuBJnNYBffPXU/edit#heading=h.bqfn104livtx
and anurag has opened a ticket with mongo on this.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/ResourceLookupResource.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/39851#-NGWZIB1EzQqBNwlFBpr:-NGWZIB1EzQqBNwlFBps:b9t4d0x) ([raw file](https://github.com/harness/harness-core/blob/249583af8438af3721ccee4ff819e6b65bc75dad/400-rest/src/main/java/software/wings/resources/ResourceLookupResource.java#L57)):*
> ```Java
>     pageRequest.addFilter(ResourceLookupKeys.accountId, EQ, accountId);
>     // Sorting has been added so that it takes index correctly
>     pageRequest.addOrder(ResourceLookupKeys.accountId, SortOrder.OrderType.ASC);
> ```

@bhavya181 Was the plan using the index rejected without this sort order. Can you check with DBA about this behaviour. Why it is so that on adding sort order, index is picked up

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/ResourceLookupResource.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/39851#-NGWZIB1EzQqBNwlFBpr:-NGWfLGA3TsWxS075dcq:b-x513x7) ([raw file](https://github.com/harness/harness-core/blob/249583af8438af3721ccee4ff819e6b65bc75dad/400-rest/src/main/java/software/wings/resources/ResourceLookupResource.java#L57)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@bhavya181 Was the plan using the index rejected without this sort order. Can you check with DBA about this behaviour. Why it is so that on adding sort order, index is picked up
</blockquote></details>

yes @ankit-harness it is now using the index. 
I have written a doc as well https://docs.google.com/document/d/1vrAQvDOoHsqrmt7802ohuT0wDaiAKkVuBJnNYBffPXU/edit#heading=h.bqfn104livtx
and anurag has opened a ticket with mongo on this.

**Review by ankit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/ResourceLookupResource.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/39851#-NGWZIB1EzQqBNwlFBpr:-NGWmDnY3-y0YHVZCsw7:b-18254t) ([raw file](https://github.com/harness/harness-core/blob/249583af8438af3721ccee4ff819e6b65bc75dad/400-rest/src/main/java/software/wings/resources/ResourceLookupResource.java#L57)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

yes @ankit-harness it is now using the index. 
I have written a doc as well https://docs.google.com/document/d/1vrAQvDOoHsqrmt7802ohuT0wDaiAKkVuBJnNYBffPXU/edit#heading=h.bqfn104livtx
and anurag has opened a ticket with mongo on this.
</blockquote></details>

@bhavya181 Thanks. Pls add these details in PR description as well

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)* status: 1 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39851)* status: :shipit: complete! ✓

**Comment by bhavya181** [comment]
trigger messagecheck

**Pull request merged**
