### PR TITLE
feat:[CDS-54686]: adding failure details column in service infrs info table and trigger info in pipeline execution summary CD table

### PR DESCRIPTION
**Pull request by sourabh-awashti**
Changes are related to adding column for failure details in pipeline execution summary table
Tests Done:-
1. Checking error message getting populated in timescale db for failed pipeline

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45087)

### CODE REVIEW

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45087)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java` line 75 at r4](https://reviewable.io/reviews/harness/harness-core/45087#-NQ_oVeNEHBp6JeGWPcK:-NQ_oVeNEHBp6JeGWPcL:bg9por5) ([raw file](https://github.com/harness/harness-core/blob/6e2b2a998b9f7bb2b251d8adff052961d49d5a5b/110-change-data-capture/src/main/java/io/harness/changehandlers/PlanExecutionSummaryCdChangeDataHandler.java#L75)):*
> ```Java
>     if (dbObject.get(PlanExecutionSummaryKeys.failureInfo) != null
>         && ((BasicDBObject) dbObject.get(PlanExecutionSummaryKeys.failureInfo)).get("message") != null) {
>       columnValueMapping.put("execution_failure_details",
> ```

What would be the case if multiple stage running in parallel fail
I don't think we are handling that

**Comment by sourabh-awashti** [comment]
trigger messagecheck

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 4 files at r3, 1 of 2 files at r4, 6 of 6 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45087)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 4 files at r3, 1 of 2 files at r4, 6 of 6 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45087)* status: Some of the checks are too old.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 2 files at r4, 2 of 6 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45087)* status: Some of the checks are too old.

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
