### PR TITLE
fix: [CDS-49403]: change the log output level in bazel

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
Before this change when you run the tests show all outputs log like : 
`INFO: From generating openapi sources //120-ng-manager/contracts/openapi/public/v1:ng-manager-server-spec-gen:
15:35:06.527 [Thread-0] INFO  i.s.c.v.i.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
15:35:06.530 [Thread-0] INFO  i.s.c.v.g.java.AbstractJavaCodegen - Invoker Package Name, originally not set, is now derived from api package name: io.harness.spec.server.ng
15:35:07.840 [Thread-0] INFO  i.s.codegen.v3.AbstractGenerator - writing file /private/var/tmp/_bazel_christopherham/6feb48c919368e34d74de68489db5df9/sandbox/darwin-sandbox/465/execroot/harness_monorepo/120-ng-manager/contracts/openapi/public/v1/ng-manager-server-spec-gen/src/main/java/io/harness/spec/server/ng/v1/model/CreateOrganizationRequest.java
15:35:07.964 [Thread-0] INFO  i.s.codegen.v3.AbstractGenerator - writing file /private/var/tmp/_bazel_christopherham/6feb48c919368e34d74de68489db5df9/sandbox/darwin-sandbox/465/execroot/harness_monorepo/120-ng-manager/contracts/openapi/public/v1/ng-manager-server-spec-gen/src/main/java/io/harness/spec/server/ng/v1/model/CreateProjectRequest.java
15:35:08.044 [Thread-0] INFO  i.s.codegen.v3.AbstractGenerator - writing file /private/var/tmp/_bazel_christopherham/6feb48c919368e34d74de68489db5df9/sandbox/darwin-sandbox/465/execroot/harness_monorepo/120-ng-manager/contracts/openapi/public/v1/ng-manager-server-spec-gen/src/main/java/io/harness/spec/server/ng/v1/model/ModuleType.java`

After this change the log will be: 
`(10:41:35) INFO: Build completed successfully, 609 total actions
//120-ng-manager:io.harness.NGSwaggerTest                                PASSED in 21.0s
//120-ng-manager:io.harness.NgManagerComponentTest                       PASSED in 69.9s
//120-ng-manager:io.harness.mongo.NgManagerMongoIndexesTest              PASSED in 23.6s
//120-ng-manager:io.harness.ng.ConnectorServiceImplTest                  PASSED in 18.4s`

For more details and full log diff check the ticket.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)

### CODE REVIEW

**Review by Fernando-Dourado — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by rafaelmart1ns** [comment]
trigger ti0, ti1

**Comment by rafaelmart1ns** [comment]
trigger ti0, ti1

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/resources/logback.xml` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/42038#-NKU9PSzA9vupmi7U35O:-NKU9PSzA9vupmi7U35P:b-o8y6qf) ([raw file](https://github.com/harness/harness-core/blob/b67f53b03e0991d6aba3fd62670fafef2b7d61a8/120-ng-manager/src/main/resources/logback.xml#L29)):*
> ```XML
>     </root>
>     
>     <logger name="io.swagger" level="WARN"/>
> ```

Not clear why we need this change. Could you explain more?

Doing that we are changing our prod value and the ticket mention only about build time.

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/resources/logback.xml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/42038#-NKU9uhPCDlHnJjnKM4T:-NKU9uhPCDlHnJjnKM4U:b-tt2epy) ([raw file](https://github.com/harness/harness-core/blob/b67f53b03e0991d6aba3fd62670fafef2b7d61a8/120-ng-manager/src/test/resources/logback.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

The file name should be logback-test.xml to be auto-detected during test execution. 

The root level should be OFF to disable the logging for all.

**Review by rafaelmart1ns — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/resources/logback.xml` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/42038#-NKU9PSzA9vupmi7U35O:-NKYX9npEWuqmdg5ASG8:b-r73k4e) ([raw file](https://github.com/harness/harness-core/blob/b67f53b03e0991d6aba3fd62670fafef2b7d61a8/120-ng-manager/src/main/resources/logback.xml#L29)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Not clear why we need this change. Could you explain more?

Doing that we are changing our prod value and the ticket mention only about build time.
</blockquote></details>

This change was committed wrong. It fixed. 
___
*[`120-ng-manager/src/test/resources/logback.xml` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/42038#-NKU9uhPCDlHnJjnKM4T:-NKYX7_qCLa_kfmxVEJw:bybs544) ([raw file](https://github.com/harness/harness-core/blob/b67f53b03e0991d6aba3fd62670fafef2b7d61a8/120-ng-manager/src/test/resources/logback.xml#L1)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

The file name should be logback-test.xml to be auto-detected during test execution. 

The root level should be OFF to disable the logging for all.
</blockquote></details>

It renamed. done.

**Review by brettzu — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 9 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: Some of the checks are too old. 3 file(s) to review.

**Review by Fernando-Dourado — DISMISSED** [review]
> Reviewed 7 of 9 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: Some of the checks are too old.

**Review by diptiman-adak — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 9 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: Some of the checks are too old.

**Review by diptiman-adak — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038)* status: 1 of 2 approvals obtained.

**Review by Fernando-Dourado — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42038#-:-NKxI10_1v58Iz8KUnQ2:bnfp4nl)* status: :shipit: complete! ✓

**Review by mankrit-singh — APPROVED** [review]

**Pull request merged**
