### PR TITLE
[fix]: [PIE-5619]: Filtered responses of NG-Manager, to get only that connector which is actually referred in pipeline

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: Customer was using old-git sync and was having multiple connectors in different branches, Upon skiping PreflightCheck pipeline was successful, and when preflight was enabled it failed as it fetched all connectors with that identifier from DB and subsequently ran preflight check upon them.

Changes: Filtered responses of NG-Manager, to get only that connector which is actually referred in pipeline

Testing: I ran preflight Automation against my changes and they passed.
2 cases needed to be checked one was verified on local(connectors with same identifier in different branches), other is (connectors with same identifier in different repos).Although 2nd was not verified on local but verified on PR-env, Also added logs for debugging.

Screenshot 2022-10-31 at 8 28 31 PM
Screenshot 2022-10-31 at 8 28 40 PM
Screenshot 2022-10-31 at 8 28 48 PM
Screenshot 2022-11-01 at 2 00 08 PM
Screenshot 2022-11-02 at 11 16 19 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39103)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/39103#-NFIb-rABxFlZrKsmkRi:-NFIb-rABxFlZrKsmkRj:bdf5poc) ([raw file](https://github.com/harness/harness-core/blob/5c2c702233b75c822d1fbeac4e53549608318d4f/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L117)):*
> ```Java
> 
>   private boolean ifResponseHasAConnectorUsage(ConnectorResponseDTO responseDTO, EntityDetail connectorUse) {
>     return connectorUse.getEntityRef().getBranch().equals(responseDTO.getGitDetails().getBranch())
> ```

use responseDTO.getGitDetails().getBranch().equals(connectorUse.getEntityRef().getBranch())
Same for getRepoIdentifier and getIdentifier.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39103)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/39103#-NFIb-rABxFlZrKsmkRi:-NFIfZccAA4Y_rYnK5Sx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5c2c702233b75c822d1fbeac4e53549608318d4f/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L117)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

use responseDTO.getGitDetails().getBranch().equals(connectorUse.getEntityRef().getBranch())
Same for getRepoIdentifier and getIdentifier.
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39103)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39103)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/39103#-NFqfVJs0NHrgjvrs1C0:-NFqfVJs0NHrgjvrs1C1:b-dwxwj4) ([raw file](https://github.com/harness/harness-core/blob/bf95f3548e881158e2fde860321ba09a59f43982/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L105)):*
> ```Java
>         } else {
>           log.info("Connector is either null or empty. Hence rejected for Preflight checks");
>         }
> ```

Did we added if else log just for debugging?



_Code quote:_
```Java
        if (responseDTO.getConnector() != null && !EmptyPredicate.isEmpty(responseDTO.getConnector().getIdentifier())) {
          log.info(
              "Preflight will be run on connector with identifier: {}, this connector is either Inline Pipeline or New-Git-Experience IsEnabled.",
              responseDTO.getConnector().getIdentifier());
        } else {
          log.info("Connector is either null or empty. Hence rejected for Preflight checks");
        }
```
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 119 at r6](https://reviewable.io/reviews/harness/harness-core/39103#-NFqfctnEEVLLk7kTk-j:-NFqfctnEEVLLk7kTk-k:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/bf95f3548e881158e2fde860321ba09a59f43982/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L119)):*
> ```Java
>                 responseDTO.getConnector().getIdentifier(), responseDTO.getGitDetails().getRepoIdentifier(),
>                 responseDTO.getGitDetails().getBranch());
>           }
> ```

same as above



_Code quote:_
```Java
          } else {
            log.info("Rejecting Connector with Identifier: {}, repoIdentifier: {} and branch: {} for preflight checks.",
                responseDTO.getConnector().getIdentifier(), responseDTO.getGitDetails().getRepoIdentifier(),
                responseDTO.getGitDetails().getBranch());
          }
```

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39103)* status: 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/39103#-NFqfVJs0NHrgjvrs1C0:-NFqhChyA7-2ZHRXOqw5:bauf9t5) ([raw file](https://github.com/harness/harness-core/blob/bf95f3548e881158e2fde860321ba09a59f43982/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L105)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Did we added if else log just for debugging?
</blockquote></details>

Yes. Also it reminds us about that even if we are filtering our connectors for the actually referred one, but we are getting responses of all connectors from NG-manager
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 119 at r6](https://reviewable.io/reviews/harness/harness-core/39103#-NFqfctnEEVLLk7kTk-j:-NFqhgZL6ieaFBaNPqlS:bb3iwf3) ([raw file](https://github.com/harness/harness-core/blob/bf95f3548e881158e2fde860321ba09a59f43982/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L119)):*
> Yes. Also it reminds us about that even if we are filtering our connectors for the actually referred one, but we are getting responses of all connectors from NG-manager

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39103)* status: :shipit: complete! ✓

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 105 at r6](https://reviewable.io/reviews/harness/harness-core/39103#-NFqfVJs0NHrgjvrs1C0:-NFqnj3O1yMU1URLkvtz:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/bf95f3548e881158e2fde860321ba09a59f43982/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L105)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Yes. Also it reminds us about that even if we are filtering our connectors for the actually referred one, but we are getting responses of all connectors from NG-manager
</blockquote></details>

discussed offline
___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 119 at r6](https://reviewable.io/reviews/harness/harness-core/39103#-NFqfctnEEVLLk7kTk-j:-NFqnl2yAlQe6QEKuX0B:b-iypmbn) ([raw file](https://github.com/harness/harness-core/blob/bf95f3548e881158e2fde860321ba09a59f43982/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L119)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

> Yes. Also it reminds us about that even if we are filtering our connectors for the actually referred one, but we are getting responses of all connectors from NG-manager
</blockquote></details>

Discussed offline

**Pull request merged**
