### PR TITLE
techdebt:[CDS-71826]: Removed usage of PL_CONNECTOR_ENCRYPTION_PRIVILEGED_CALL and moderated the code

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
Removed usage of PL_CONNECTOR_ENCRYPTION_PRIVILEGED_CALL and moderated the code

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)

### CODE REVIEW

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger feature-build

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by sandeshsalunkhegh** [comment]
trigger feature-build

**Comment by sandeshsalunkhegh** [comment]
trigger checkstylecodeformat

**Review by utkarshchoubey-harness — DISMISSED** [review]

**Review by ankittiwari-harness — APPROVED** [review]

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)* status: Some of the checks are too old. 5 file(s) to review.

**Review by sandeshsalunkhegh — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564#-:-NaBVn2cC7mrPRV1bb3B:bnfp4nl)* status: Some of the checks are too old. 5 file(s) to review.

**Comment by sandeshsalunkhegh** [comment]
trigger checkstylecodeformat

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)* status: Some of the checks are too old. 4 file(s) to review. 1 change requests. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/pms/rbac/PipelineRbacHelper.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/50564#-NaBXdk4Bm82CykPWZ1H:-NaBXdk4Bm82CykPWZ1I:b30tt3s) ([raw file](https://github.com/harness/harness-core/blob/70fb9f1994a40ee0dee48a1509dffaafe4e5b48b/878-ng-common-utilities/src/main/java/io/harness/pms/rbac/PipelineRbacHelper.java#L89)):*
> ```Java
> 
>     String accountId = AmbianceUtils.getAccountId(ambiance);
>     if (shouldExtractInternalEntities) {
> ```

ContainerStepRbacHelper is passing this value as true
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/50564#-NaBXmUIEyGhz2Z2hPeR:-NaBXmUJEzdndkrsK66A:bgzbun7) ([raw file](https://github.com/harness/harness-core/blob/70fb9f1994a40ee0dee48a1509dffaafe4e5b48b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L113)):*
> ```Java
>     List<EntityDetail> entityDetails = PipelineSetupUsageUtils.extractInputReferredEntityFromYaml(
>         accountIdentifier, orgIdentifier, projectIdentifier, pipelineYamlWithUnresolvedTemplates, allReferredUsages);
>     entityDetails.addAll(internalReferredEntityExtractor.extractInternalEntities(accountIdentifier, entityDetails));
> ```

why we are removing this?

**Comment by sandeshsalunkhegh** [comment]
trigger checkstylecodeformat, uts

**Review by sandeshsalunkhegh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/pms/rbac/PipelineRbacHelper.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/50564#-NaBXdk4Bm82CykPWZ1H:-NaCX1010ULDmu7AXZF8:bby4plk) ([raw file](https://github.com/harness/harness-core/blob/70fb9f1994a40ee0dee48a1509dffaafe4e5b48b/878-ng-common-utilities/src/main/java/io/harness/pms/rbac/PipelineRbacHelper.java#L89)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

ContainerStepRbacHelper is passing this value as true
</blockquote></details>

@archit-harness I didn't understand what are you trying to point out here, can you please elaborate?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/50564#-NaBXmUIEyGhz2Z2hPeR:-NaCWX3G-aZSjh2nhIQD:b-z30w9g) ([raw file](https://github.com/harness/harness-core/blob/70fb9f1994a40ee0dee48a1509dffaafe4e5b48b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are removing this?
</blockquote></details>

@archit-harness We are removing all references to `PL_CONNECTOR_ENCRYPTION_PRIVILEGED_CALL` FF and also it's related code. So the entire class `InternalReferredEntityExtractor` will have only dead code i.e. the function `extractInternalEntities` which will be returning an empty list. That's why we are removing this.

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/pms/rbac/PipelineRbacHelper.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/50564#-NaBXdk4Bm82CykPWZ1H:-NaHBtrz0Pcv_lg74rL7:b-r9sz3d) ([raw file](https://github.com/harness/harness-core/blob/70fb9f1994a40ee0dee48a1509dffaafe4e5b48b/878-ng-common-utilities/src/main/java/io/harness/pms/rbac/PipelineRbacHelper.java#L89)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness the code inside the method `internalReferredEntityExtractor.extractInternalEntities(accountId, entityDetails)` is no-op. It always returns empty list. So we can remove this.
</blockquote></details>

@archit-harness Let me know whether this clears the doubt.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java` line 113 at r2](https://reviewable.io/reviews/harness/harness-core/50564#-NaBXmUIEyGhz2Z2hPeR:-NaHC26a-48U3uGcp9ai:bjv2x56) ([raw file](https://github.com/harness/harness-core/blob/70fb9f1994a40ee0dee48a1509dffaafe4e5b48b/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java#L113)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Same, the complete code inside `internalReferredEntityExtractor` is dead-code. So we can remove.
</blockquote></details>

@archit-harness Let me know whether this answers your question.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50564)* status: :shipit: complete! ✓

**Pull request merged**
