### PR TITLE
feat: [DEL-5713]:  Support test targets for BuildCleaner

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
Adding support for creating package level test targets in build cleaner. We still run code analysis for test code, but only checkstyle (as before). Needed to update analysis and run_tests macros to support these. 
Added one example package level test build file here c1832f37ede032704d4aa518ef810e90ab8f0df4

Tested:
* Creating new BUILD.bazel for test package
* Updating existing BUILD.bazel for test package
* Creating new BUILD.bazel for standard java package
* Updating existing BUILD.bazel for standard java package
* Running all tests includes package level test targets
* IntelliJ can run tests
* Run tests from CMD line

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)

### CODE REVIEW

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

___
*[`tools/bazel/GenTestRules.bzl` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/42401#-NLN_-rR3dySY1pZzdxY:-NLN_-rR3dySY1pZzdxZ:b-siqjh8) ([raw file](https://github.com/harness/harness-core/blob/1b0cfdea153fa403548f3ae49344684fc7726d04/tools/bazel/GenTestRules.bzl#L32)):*
> ```Starlark
>         if pattern in path:  # For root level build file we have relative path from root
>             return path[len(pattern):][:-5].replace("/", ".")
> ```

nit: Can you please add a comment with an example of what native.package_name() resolves to

**Review by gn-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

___
*[`tools/bazel/macros.bzl` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/42401#-NLNaBdO411XBz5clYGj:-NLNaBdO411XBz5clYGk:b-k0vsev) ([raw file](https://github.com/harness/harness-core/blob/1b0cfdea153fa403548f3ae49344684fc7726d04/tools/bazel/macros.bzl#L87)):*
> ```Starlark
>         pmd_srcs = ["*"],
>         sonarqube_srcs = ["*.java"],
>         test_only = False):
> ```

You will need to fix:

~/source-code/harness-core (960-api-services-split-0)> cfind run_analysis_per_module *  | grep run_duplicated
260-delegate/src/main/java/io/harness/delegate/app/platform/BUILD.bazel:run_analysis_per_module(run_duplicated = False)

**Comment by mdmilic** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)_ status: :shipit: complete! ✓
> 
> _[`tools/bazel/macros.bzl` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/42401#-NLNaBdO411XBz5clYGj:-NLNaBdO411XBz5clYGk:b-k0vsev) ([raw file](https://github.com/harness/harness-core/blob/1b0cfdea153fa403548f3ae49344684fc7726d04/tools/bazel/macros.bzl#L87)):_
> 
> > ```python
> >         pmd_srcs = ["*"],
> >         sonarqube_srcs = ["*.java"],
> >         test_only = False):
> > ```
> 
> You will need to fix:
> 
> ~/source-code/harness-core (960-api-services-split-0)> cfind run_analysis_per_module * | grep run_duplicated 260-delegate/src/main/java/io/harness/delegate/app/platform/BUILD.bazel:run_analysis_per_module(run_duplicated = False)

Yes, done. Forgot delegate can't handle dupe check targets. Didn't appear in my intellJ searches for some reason, so I thought it was unused, but I was the one who disabled it in the first place :)

**Review by gn-harness — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

**Review by diptiman-adak — DISMISSED** [review]
> Reviewed 6 of 11 files at r1, 4 of 4 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger ti1

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42401)* status: :shipit: complete! ✓

**Pull request merged**
