### PR TITLE
feat: [PIE-6110]: add user name and email in interruptConfig

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** We are not showing who aborted Pipeline

**Changes:** add user name and email in interruptConfig

**Impact:** Now for each interrupt, like abort, ignore failed, markedAsSuccess, etc. through manualIntervention or postRetryAction or directly from execution page, user name, and email will be populated in the interrupt config interrupt history.

**Testing:** Tested the behavior locally.

Screenshot 2023-03-14 at 4 54 52 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45102)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut8

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45102)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 548 at r1](https://reviewable.io/reviews/harness/harness-core/45102#-NQUh58O-smBwMzAiNYd:-NQUh58O-smBwMzAiNYe:b-8nma5s) ([raw file](https://github.com/harness/harness-core/blob/baaf5be8ca9a955add600286c2e5ed6b09bd4ccd/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L548)):*
> ```Java
>                                                   .setIdentifier(principal.getName())
>                                                   .setEmailId(PrincipalHelper.getEmail(principal))
>                                                   .setUserId(PrincipalHelper.getUsername(principal))
> ```

Please add unit test.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45102)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java` line 548 at r1](https://reviewable.io/reviews/harness/harness-core/45102#-NQUh58O-smBwMzAiNYd:-NQVNmKeCD8r4hDCwOnk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/baaf5be8ca9a955add600286c2e5ed6b09bd4ccd/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java#L548)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Please add unit test.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger ut6

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45102)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ut0

**Comment by shalini-agr** [comment]
trigger ut1, ut2, ut3, ut4, ut5, ut6, ut7, ut8, ut9, messagecheck

**Comment by shalini-agr** [comment]
trigger ut2, ut5

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45102)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45102)* status: :shipit: complete! ✓

**Pull request merged**
