### PR TITLE
feat: [CDS-37284]: add deployment type to NG service entity

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes

- Add ServiceDefinitionType to ServiceEntity at root level. We read the field from the service yaml and set it into the entity. The request response DTOs for the service remain the same
- Add API to filter services based on deployment Type
- Also add gitOps enabled as hidden property of deploymentStageConfig and changes from this PR #33972
- Convert gitOps enabled to boxed boolean from primitive to hide from yaml 
  
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33983)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33983)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33983)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33983)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33983)* status: :shipit: complete! ✓

**Pull request merged**
