### PR TITLE
fix: [PL-40558]: Update SSO linked UserGroup only if it maps to same ssoGroupId

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

We observed a scenario in customer env where NGLdapUserGroupSync was reverting the SSO Group to the older values after a UserGroup was linked to another SSO Group. This PR fixes the issue by ensuring that while NGLdapUserGroupSync we make the update only if the sync is happening to the same SSO Group to which userGroup is currently linked to.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51494)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 317 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-NbXqnYw9yn7K4YGIBBw:-NbXqnYxCPHpgIey_l8r:bx7uzde) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L317)):*
> ```Java
>               userGroup.getIdentifier(), savedUserGroup.get().getSsoGroupId(), userGroup.getSsoGroupId());
>           continue;
>         }
> ```

minor: more of a question - Would it make sense to have these checks even before we get the delegateResponseData, since in this cases we are anyways going to discard the delegateResponse, thanks



_Code quote:_
```Java
        // Check if the User Group State has not changed
        Optional<UserGroup> savedUserGroup = userGroupService.get(userGroup.getAccountIdentifier(),
            userGroup.getOrgIdentifier(), userGroup.getProjectIdentifier(), userGroup.getIdentifier());
        if (!savedUserGroup.isPresent()) {
          log.error("NGLDAP: User group {} no longer exists. Not syncing this user group.", userGroup.getIdentifier());
          continue;
        }
        if (!savedUserGroup.get().getIsSsoLinked()) {
          log.error(
              "NGLDAP: User group {} is no longer SSO linked. Not syncing this user group.", userGroup.getIdentifier());
          continue;
        }
        if (savedUserGroup.get().getSsoGroupId() != userGroup.getSsoGroupId()) {
          log.error(
              "NGLDAP: User group {} is linked to SSO Group {} but sync happening for SSO Group {}. Not syncing this user group",
              userGroup.getIdentifier(), savedUserGroup.get().getSsoGroupId(), userGroup.getSsoGroupId());
          continue;
        }
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 312 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-NbXzl6rCqCjjcHn-UNg:-NbXzl6rCqCjjcHn-UNh:byrk67e) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L312)):*
> ```Java
>           continue;
>         }
>         if (savedUserGroup.get().getSsoGroupId() != userGroup.getSsoGroupId()) {
> ```

nit: !savedUserGroup.get().getSsoGroupId().equals(userGroup.getSsoGroupId()), thanks



_Code quote:_
```Java
savedUserGroup.get().getSsoGroupId() != userGroup.getSsoGroupId()
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51494)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 301 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-Nb_P-cZ4PCXjk6sUYzr:-Nb_P-cZ4PCXjk6sUYzs:b-nuuksr) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L301)):*
> ```Java
> 
>         // Check if the User Group State has not changed
>         Optional<UserGroup> savedUserGroup = userGroupService.get(userGroup.getAccountIdentifier(),
> ```

can you refactor this check in a single method and call it

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51494)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 301 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-Nb_P-cZ4PCXjk6sUYzr:-Nb_Uaa04qKreBlhkc6e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L301)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

can you refactor this check in a single method and call it
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 312 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-NbXzl6rCqCjjcHn-UNg:-Nb_UcXS9CgK9FGWFO8N:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L312)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: !savedUserGroup.get().getSsoGroupId().equals(userGroup.getSsoGroupId()), thanks
</blockquote></details>

Done
___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 317 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-NbXqnYw9yn7K4YGIBBw:-Nb_UgNMB5igYEN8AcHt:bayh33u) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L317)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: more of a question - Would it make sense to have these checks even before we get the delegateResponseData, since in this cases we are anyways going to discard the delegateResponse, thanks
</blockquote></details>

Yeah makes sense. We can save on the delegate call. I will move it up. Thanks

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger checkstylecodeformat, pmd, uts, codebasehash

**Comment by piyush-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 317 at r1](https://reviewable.io/reviews/harness/harness-core/51494#-NbXqnYw9yn7K4YGIBBw:-Nba3UMDANLdeYmBKI5h:bxsba5x) ([raw file](https://github.com/harness/harness-core/blob/8a72c5a92eedf96b58108133f10e6adc9904ea0f/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L317)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Yeah makes sense. We can save on the delegate call. I will move it up. Thanks
</blockquote></details>

Sync can run long , I think we should check state after the delegate task only.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 320 at r3](https://reviewable.io/reviews/harness/harness-core/51494#-Nba3lK936q2Ff_Ca1-T:-Nba3lK936q2Ff_Ca1-U:b-k7xqb1) ([raw file](https://github.com/harness/harness-core/blob/1ca5e5101156b910c294bb8460a81f7f38626fd0/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L320)):*
> ```Java
>   }
> 
>   private boolean isUserGroupSsoStateValid(UserGroup userGroup) {
> ```

Please write UTs for this

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51494)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51494)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51494)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger uts

**Pull request merged**
