### PR TITLE
[feat]: [CDS-73868]: Added UTs

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Changes: Some more UTs are added for code that was added for gitXRepoAllowlist.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51069)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51069)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Review by shalini-agr — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51069)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/51069#-NapGlSqDRSSgUjpMGk9:-NapGlSqDRSSgUjpMGkA:b83dytk) ([raw file](https://github.com/harness/harness-core/blob/18f167b0430cf17bc466a8f2b9d370a690dde9ec/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java#L49)):*
> ```Java
> public class GitRepoAllowlistHelperTest {
>   @Mock GitXSettingsHelper gitXSettingsHelper;
>   @Spy GitRepoHelper gitRepoHelper = new GitRepoHelper();
> ```

I don't see this field being used anywhere. we can remove this 
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/51069#-NapH2OE2av3XqkF6BZM:-NapH2OE2av3XqkF6BZN:b-fm90jy) ([raw file](https://github.com/harness/harness-core/blob/18f167b0430cf17bc466a8f2b9d370a690dde9ec/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java#L144)):*
> ```Java
>     repoAllowlist.add("senjucanon2/test-repo");
>     doReturn(repoAllowlist).when(gitXSettingsHelper).getGitRepoAllowlist(any(), any(), any());
>     doNothing().when(gitRepoAllowlistHelper).validateRepo(any(), any(), any(), any(), any());
> ```

let's also add a test when this is not a valid repo and assert error messages.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51069)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/51069#-NapGlSqDRSSgUjpMGk9:-NapOqKHE9_BQ0bE6pfj:br4cur7) ([raw file](https://github.com/harness/harness-core/blob/18f167b0430cf17bc466a8f2b9d370a690dde9ec/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java#L49)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

I don't see this field being used anywhere. we can remove this 
</blockquote></details>

This is being used. It is injected in gitRepoAllowlistHelper. @Spy annotation injects a real object of this class into the gitRepoAllowlistHelper. Which is internally called in the method.
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/51069#-NapH2OE2av3XqkF6BZM:-NapQRg99-9aXF7XF8HX:b1gfhrq) ([raw file](https://github.com/harness/harness-core/blob/18f167b0430cf17bc466a8f2b9d370a690dde9ec/136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelperTest.java#L144)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

let's also add a test when this is not a valid repo and assert error messages.
</blockquote></details>

Test for error response was already added during development of this feature have added message assertion in it.

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51069)* status: 2 file(s) to review.

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
