### PR TITLE
fix: [CHAOS-1267]: Adding chaos view permission in privileged-roles 

### PR DESCRIPTION
**Pull request by S-ayanide**
## Describe your changes

Adding chaos view permission for hub, gameday, experiment and infrastructure. The following permissions are added:

```
chaos_chaoshub_view

chaos_chaosinfrastructure_view

chaos_chaosexperiment_view

chaos_chaosgameday_view
```

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)

### CODE REVIEW

**Review by reetika04 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)* status: :shipit: complete! ✓

**Review by imrajdas — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)* status: :shipit: complete! ✓

**Comment by imrajdas** [comment]
trigger messagecheck

**Comment by imrajdas** [comment]
trigger messagecheck

**Comment by S-ayanide** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)* status: :shipit: complete! ✓

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/44322#-NP2rY3u8fjRxhxwpDit:-NP2rY3u8fjRxhxwpDiu:b-b78alv) ([raw file](https://github.com/harness/harness-core/blob/b6f83eb5ddde3a4ec016c8eb068d9e6ea733c07b/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L3)):*
> ```YAML
> # Any edit in this file should accompany an increment in version.
> name: supportRolesConfiguration
> version: 17
> ```

Hi, @S-ayanide we need to increase the version number to 18 because we've already merged code changes with that version.

**Review by S-ayanide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/44322#-NP2rY3u8fjRxhxwpDit:-NPHRsUVAC3_ZSSmi7Z3:brs0s82) ([raw file](https://github.com/harness/harness-core/blob/b6f83eb5ddde3a4ec016c8eb068d9e6ea733c07b/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L3)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Hi, @S-ayanide we need to increase the version number to 18 because we've already merged code changes with that version. 
</blockquote></details>

Missed this, thanks for pointing this out @ivan-83 have updated the version to 18

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)* status: :shipit: complete! ✓

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322#-:-NPLNHXc0jQCjBZosX2N:bnfp4nl)* status: :shipit: complete! ✓

**Comment by Jimit09Gandhi** [comment]
@S-ayanide 

Please test the changes in PreQA/ QA by login as Support User in an account where you are not directly added as User.

You can follow steps:

1. In any existing/new account, add a new user.
2. Add the user into the Harness Support UG.
3. Login into the User.
4. Switch to account apart from one account user is already part of.
5. Validate user can view flows having  file store permission RBAC check.

You can reach out to @Suma T for getting add user to Support NG UG.

**Comment by S-ayanide** [comment]
trigger messagecheck

**Comment by S-ayanide** [comment]
trigger ut5

**Comment by S-ayanide** [comment]
trigger ut6

**Comment by S-ayanide** [comment]
trigger ut7

**Comment by S-ayanide** [comment]
trigger ut8

**Comment by S-ayanide** [comment]
trigger ut9

**Review by S-ayanide — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44322)* status: Some of the checks are too old.

**Pull request merged**
