### PR TITLE
fix: [PL-20184]: Restrict atmosphere threads

### PR DESCRIPTION
**Pull request by abhinav-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30645)

### CODE REVIEW

**Comment by piyush-harness** [comment]
___
*[360-cg-manager/src/main/java/software/wings/app/WingsApplication.java, line 977 at r1](https://reviewable.io/reviews/harness/harness-core/30645#-MvTHGnF0f8HJ84Z_bQa:-MvTHGnF0f8HJ84Z_bQb:b-7lt12) ([raw file](https://github.com/harness/harness-core/blob/e78d75e948b25ba3876bbb0fec3214979cdec1e0/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L977)):*
> ```Java
>     AtmosphereServlet atmosphereServlet = injector.getInstance(AtmosphereServlet.class);
>     final AtmosphereConfig atmosphereConfig = configuration.getAtmosphereConfig();
>     atmosphereServlet.framework().addInitParameter("org.atmosphere.cpr.broadcaster.maxProcessingThreads",
> ```

Read from AtmosphereConstant class if available in framework else create your own

**Comment by piyush-harness** [comment]
___
*[360-cg-manager/config.yml, line 689 at r1](https://reviewable.io/reviews/harness/harness-core/30645#-MvTHBjJ0jSwYw023P5f:-MvTHBjJ0jSwYw023P5g:b8v3hmo) ([raw file](https://github.com/harness/harness-core/blob/e78d75e948b25ba3876bbb0fec3214979cdec1e0/360-cg-manager/config.yml#L689)):*
> ```YAML
> 
> atmosphereConfig:
>     maxProcessingThreads: ${MAX_ATMOSPHERE_PROCESSING_THREAD:-20}
> ```

Add these to replace_config.sh as well.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30645)* status: 5 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[360-cg-manager/config.yml, line 689 at r1](https://reviewable.io/reviews/harness/harness-core/30645#-MvTHBjJ0jSwYw023P5f:-MvTbCgbBQIUoyClctyF:b-rktsy6) ([raw file](https://github.com/harness/harness-core/blob/e78d75e948b25ba3876bbb0fec3214979cdec1e0/360-cg-manager/config.yml#L689)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Add these to replace_config.sh as well.
</blockquote></details>

I believe its not needed now since this means it will pick from env variable automatically 
___
*[360-cg-manager/src/main/java/software/wings/app/WingsApplication.java, line 977 at r1](https://reviewable.io/reviews/harness/harness-core/30645#-MvTHGnF0f8HJ84Z_bQa:-MvTbIdw8_o1w8w6IJSJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e78d75e948b25ba3876bbb0fec3214979cdec1e0/360-cg-manager/src/main/java/software/wings/app/WingsApplication.java#L977)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Read from AtmosphereConstant class if available in framework else create your own
</blockquote></details>

Done.

**Comment by abhinav-harness** [comment]
trigger ti1

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30645)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/beans/atmosphere/AtmosphereConfig.java, line 17 at r3](https://reviewable.io/reviews/harness/harness-core/30645#-MvVDsrFBxr426ut8pQV:-MvVDsrFBxr426ut8pQW:bxqlpmd) ([raw file](https://github.com/harness/harness-core/blob/e5b218588330f3941e3cb7a90851ab5d28b1cbf7/400-rest/src/main/java/software/wings/beans/atmosphere/AtmosphereConfig.java#L17)):*
> ```Java
> @Builder
> @NoArgsConstructor
> @AllArgsConstructor
> ```

Depending on the usage you don't need all of these. Definitely remove builder and noArgsConstructor (if possible because of JSON deserialization - don't remember if it can do it or not). All args might also not be needed. Data annotation would bring in one constructor (requiredArgs), so depending on your fields it will be noArgs or allArgs or something in between. 



_Code quote:_
```Java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
```
___
*[400-rest/src/main/java/software/wings/beans/atmosphere/AtmosphereConfig.java, line 21 at r3](https://reviewable.io/reviews/harness/harness-core/30645#-MvVDoVY-jUHfScdNLEP:-MvVDoVY-jUHfScdNLEQ:bc3ymug) ([raw file](https://github.com/harness/harness-core/blob/e5b218588330f3941e3cb7a90851ab5d28b1cbf7/400-rest/src/main/java/software/wings/beans/atmosphere/AtmosphereConfig.java#L21)):*
> ```Java
> public class AtmosphereConfig {
>   int maxProcessingThreads;
>   int maxAsyncWriteThreads;
> ```

You probably want to make these private final. 



_Code quote:_
```Java
  int maxProcessingThreads;
  int maxAsyncWriteThreads;
```

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
Closing this since its already implemented and controlled via an env variable

**Pull request closed without merging**
