### PR TITLE
[feat]: [PIE-3729]: Send pipeline start notification after execution info is saved

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33109)

### CODE REVIEW

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33109)* status: Some of the checks are too old. 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/notification/orchestration/handlers/PipelineStartNotificationHandler.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/33109#-N2AJqjpBxezYC3AJuTx:-N2AJqjpBxezYC3AJuTy:b-1jb46) ([raw file](https://github.com/harness/harness-core/blob/05901000366c0aba56e9839f395fc1a100689f7e/800-pipeline-service/src/main/java/io/harness/pms/notification/orchestration/handlers/PipelineStartNotificationHandler.java#L22)):*
> ```Java
> import java.util.concurrent.ExecutorService;
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> ```

Since this class will not be used anymore, can you add some annotation or comments to remove it later?

**Review by brijeshdhakar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33109)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33109)* status: Some of the checks are too old. 1 file(s) to review.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33109)* status: 1 file(s) to review. 1. unresolved discussions. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/notification/orchestration/handlers/PipelineStartNotificationHandler.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/33109#-N2AJqjpBxezYC3AJuTx:-N2FlfvWCsHTWyUXT4iG:bgp6tp5) ([raw file](https://github.com/harness/harness-core/blob/002e3f15b5e9c3a5ce9946b6b3e7ff314f353fb2/800-pipeline-service/src/main/java/io/harness/pms/notification/orchestration/handlers/PipelineStartNotificationHandler.java#L22)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Since this class will not be used anymore, can you add some annotation or comments to remove it later?
</blockquote></details>

Will add it in the followup PR

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33109#-:-N2GHE_ADqTC-63njjdo:bnfp4nl)* status: 1. unresolved discussions.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33109)* status: :shipit: complete! ✓

**Pull request merged**
