### PR TITLE
[feat]: [CDS-49529]: Create YAML snippets for ARM / Blueprint and she…

### PR DESCRIPTION
**Pull request by tmacari-harness**
[feat]: [CDS-49529]: Create YAML snippets for ARM / Blueprint and shell script provisioner

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-49529]: https://harness.atlassian.net/browse/CDS-49529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42078)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/resources/provisionerStrategyYaml/script.yaml` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/42078#-NKx7-ga2O07vHnVX2dx:-NKx7-ga2O07vHnVX2dy:b-h9j2qw) ([raw file](https://github.com/harness/harness-core/blob/95e6b2015217d324f2e1faae2443a648f7ff701b/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/script.yaml#L6)):*
> ```YAML
>         type: ShellScriptProvision
>         name: Shell Script Provision
>         identifier: dfe51017-d346-5323-be6f-c55cbb699cc5
> ```

is there a reason we have such an identifier ?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42078)* status: Some of the checks are too old. 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/resources/provisionerStrategyYaml/script.yaml` line 6 at r1](https://reviewable.io/reviews/harness/harness-core/42078#-NKx7-ga2O07vHnVX2dx:-NL-hdQw5wFKmszV25jL:b2d25ir) ([raw file](https://github.com/harness/harness-core/blob/95e6b2015217d324f2e1faae2443a648f7ff701b/125-cd-nextgen/src/main/resources/provisionerStrategyYaml/script.yaml#L6)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is there a reason we have such an identifier ?
</blockquote></details>

We do the same for other provisioners yaml snippets. Not sure what was the initial reason,,,I think UI is overriding it later

**Review by vlica-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42078)* status: Some of the checks are too old. 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by akhilpandey1 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42078)* status: Some of the checks are too old. 1. unresolved discussions.

**Comment by tmacari-harness** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42078)* status: Some of the checks are too old.

**Pull request merged**
