### PR TITLE
feat: [CDS-69940]: Upgrade jackson-databind from 2.14.2 to 2.15.1

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48560)

### CODE REVIEW

**Comment by sribalij** [comment]
trigger uts

**Comment by sribalij** [comment]
trigger ut2

**Review by pranay-harness — DISMISSED** [review]
Jackson 2.14.2 had vulnerabilities.
2.15.0 and above is the recommended version

**Comment by sribalij** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]

**Review by raghuAtWings — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/48560#-NXxvcXV7iXkI6kvhuMS:-NXxvcXV7iXkI6kvhuMT:broy1k6) ([raw file](https://github.com/harness/harness-core/blob/d39f77cf4658b78b3ec2fcd46ad67488feb6a624/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L90)):*
> ```Java
>   @NotNull @VariableExpression(skipVariableExpression = true) ExecutionElementConfig execution;
> 
>   GoogleCloudFunctionDeploymentMetaData deploymentMetadata;
> ```

can we just keep the interface and put the json subtype annotations here ?

**Comment by PragyeshMishra01** [comment]
> _[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 90 at r3](https://reviewable.io/reviews/harness/harness-core/48560#-NXxvcXV7iXkI6kvhuMS:-NXxvcXV7iXkI6kvhuMT:broy1k6) ([raw file](https://github.com/harness/harness-core/blob/d39f77cf4658b78b3ec2fcd46ad67488feb6a624/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L90)):_
> 
> > ```java
> >   @NotNull @VariableExpression(skipVariableExpression = true) ExecutionElementConfig execution;
> > 
> >   GoogleCloudFunctionDeploymentMetaData deploymentMetadata;
> > ```
> 
> can we just keep the interface and put the json subtype annotations here ?

Earlier it had interface only, but it started failing after this upgrade because DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY doesn't seems to be working in this version as it was working with earlier versions. We tried to put json subtype annotations for Google Functions deployment type, but we found that it is failing during de-serialization for other deployment types with this error
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'Kubernetes' as a subtype of `io.harness.cdng.deploymentmetadata.DeploymentMetaData`: known type ids = [GoogleCloudFunctions] (for POJO property 'deploymentMetadata')
 at [Source: (StringReader); line: 1, column: 1333]
 so, to unblock, we removed the interface temporarily. 
 I'm working on a long term fix here that will have interface only in this class.

**Review by manish-manchanda — DISMISSED** [review]

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48560)* status: 5 file(s) to review.

**Review by nataraja2018 — DISMISSED** [review]

**Comment by sribalij** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger ut2

**Comment by piyush-bhuwalka** [comment]
trigger uts

**Comment by PragyeshMishra01** [comment]
trigger ut8

**Pull request merged**
