### PR TITLE
[feat]:[IDP-240]: Default backstage permissions

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)

### CODE REVIEW

**Comment by sarthakkasat** [comment]
trigger ut3

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44980#-NQESCRr0x3AuD_IKMrF:-NQESCRr0x3AuD_IKMrG:b-3l2z9x) ([raw file](https://github.com/harness/harness-core/blob/390e1822777e6210505a4ea8a9e58e45f07abd28/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L50)):*
> ```Java
>     makeTriggerApi(accountIdentifier, namespace);
>     BackstagePermissions backstagePermissions = new BackstagePermissions();
>     backstagePermissions.setUserGroup("");
> ```

Since the namespace is created by the pipeline, we should create config map only after we are sure that namespace has been created

**Review by vigneswara-propelo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/provision/resource/ProvisionApiImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/44980#-NQQNnDA11g3g3hvTyTM:-NQQNnDA11g3g3hvTyTN:b-gbs1oz) ([raw file](https://github.com/harness/harness-core/blob/a7ddfe13deb3d10365c71311588f95e8e4165727/idp-service/src/main/java/io/harness/idp/provision/resource/ProvisionApiImpl.java#L42)):*
> ```Java
>       NamespaceEntity namespaceEntity = namespaceService.saveAccountIdNamespace(accountIdentifier);
>       NamespaceInfo namespaceInfo = NamespaceMapper.toDTO(namespaceEntity);
>       k8sClient.createNamespace(namespaceInfo.getNamespace());
> ```

is there any reason why we are creating namespace here? 
Currently, the namespace gets created as part of webhook trigger itself

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/44980#-NQESCRr0x3AuD_IKMrF:-NQQT7fC0o_L6ta0V_gn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/390e1822777e6210505a4ea8a9e58e45f07abd28/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L50)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Since the namespace is created by the pipeline, we should create config map only after we are sure that namespace has been created
</blockquote></details>

Done.

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/resource/ProvisionApiImpl.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/44980#-NQQNnDA11g3g3hvTyTM:-NQQSkUA-Gq1RQCHy_AX:b-qdwh9p) ([raw file](https://github.com/harness/harness-core/blob/a7ddfe13deb3d10365c71311588f95e8e4165727/idp-service/src/main/java/io/harness/idp/provision/resource/ProvisionApiImpl.java#L42)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

is there any reason why we are creating namespace here? 
Currently, the namespace gets created as part of webhook trigger itself
</blockquote></details>

We want to create permissions when namespace is already present, creating namespace programatically ensures that

**Comment by sarthakkasat** [comment]
trigger ut2

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQRFGrm5nUJTi3Vkdz1:-NQRFGrm5nUJTi3Vkdz2:b-1xo8bz) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L55)):*
> ```Java
>   @Override
>   public void triggerPipeline(String accountIdentifier, String namespace) {
>     try {
> ```

Can we put this piece of code wherein we are creating permissions / settings config map in a separate function ? and then rename the parent function as triggerPipelineAndCreatePermissions(...)
Also from the already provided comments, if namespace creation is being done by the pipeline, then this piece should be after that.
___
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQRGFW11DEctrfHajB4:-NQRGFW11DEctrfHajB5:b-jbwdc7) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L60)):*
> ```Java
>       backstagePermissions.setPermissions(permissions);
>       backstagePermissionsService.createPermissions(backstagePermissions, accountIdentifier);
>     } catch (DuplicateKeyException e) {
> ```

The entity is already defined with FieldUniqueIndex on accountIdentifier
We don't need to explicitly catch and log it. If someone / some-flow is invoking it multiple times, it's the caller responsibility to make sure it is invoked only once.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java` line 256 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQTNOXs17JJhOSRZTdg:-NQTNOXs17JJhOSRZTdh:b-u5rciy) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java#L256)):*
> ```Java
>         v1ObjectMeta.setName(namespace);
>         v1Namespace.setMetadata(v1ObjectMeta);
>         return coreV1Api.createNamespace(v1Namespace, null, null, null, null);
> ```

what does this API return if the namespace is already created?

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java` line 256 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQTNOXs17JJhOSRZTdg:-NQUDc_lDSW7ck7MMK0K:b-8gh20c) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java#L256)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

what does this API return if the namespace is already created?
</blockquote></details>

The API will return log.info with message Namespace already created

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/resource/ProvisionApiImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQQlpk8-tEQtOGYGaBB:-NQUEBn5Euuc2OeDU8Ra:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/provision/resource/ProvisionApiImpl.java#L42)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Could the namespace creation go inside the namespaceService? 
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQRFGrm5nUJTi3Vkdz1:-NQUEEra3ZcvaTvkRZfI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L55)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Can we put this piece of code wherein we are creating permissions / settings config map in a separate function ? and then rename the parent function as triggerPipelineAndCreatePermissions(...)
Also from the already provided comments, if namespace creation is being done by the pipeline, then this piece should be after that.
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 62 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQQm_wM84AVAJZpLY-c:-NQUEM0fDwMISl5UHg76:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L62)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

It could be a warning or even just an info message, as this message is not something we should be worried about.
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/44980#-NQRGFW11DEctrfHajB4:-NQUERBK2N0Agcl69NNi:b-wzosox) ([raw file](https://github.com/harness/harness-core/blob/ac6952e890ef88928a897b31e7b3d532d31a8630/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L60)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

The entity is already defined with FieldUniqueIndex on accountIdentifier
We don't need to explicitly catch and log it. If someone / some-flow is invoking it multiple times, it's the caller responsibility to make sure it is invoked only once.
</blockquote></details>

Not throwing an exception there just showing it in log.info

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java` line 264 at r4](https://reviewable.io/reviews/harness/harness-core/44980#-NQUGV2Y144GbqD03C8L:-NQUGV2Y144GbqD03C8M:b-cj4xtx) ([raw file](https://github.com/harness/harness-core/blob/a2eeeda3bd92518c192b2a4e43bfbe926d974a50/idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java#L264)):*
> ```Java
>           log.info("Namespace {} already exists", namespace);
>           return null;
>         }
> ```

nit: We could have this block before creating the message string.



_Code quote:_
```Java
        if (ex.getCode() == 409) {
          log.info("Namespace {} already exists", namespace);
          return null;
        }
```
___
*[`idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/44980#-NQUGtNG4YofdkhO0u_A:-NQUGtNG4YofdkhO0u_B:bgsqcrl) ([raw file](https://github.com/harness/harness-core/blob/a2eeeda3bd92518c192b2a4e43bfbe926d974a50/idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java#L26)):*
> ```Java
>   private static final String IDP_NOT_ENABLED = "IDP has not been set up for account [%s]";
>   private static final String IDP_NAMESPACE_NOT_LINKED = "Namespace - [%s] is not linked to any account";
>   @Inject private K8sClient k8sClient;
> ```

Let's use constructor injection going forward. Ref: https://rules.sonarsource.com/java/RSPEC-3306
___
*[`idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/44980#-NQUHR-2AVj711gIkcNb:-NQUHR-3B0lX1FaPy0z1:b-suqaq5) ([raw file](https://github.com/harness/harness-core/blob/a2eeeda3bd92518c192b2a4e43bfbe926d974a50/idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java#L49)):*
> ```Java
>     NamespaceEntity dataToInsert = NamespaceEntity.builder().accountIdentifier(accountId).build();
>     NamespaceEntity insertedData = namespaceRepository.save(dataToInsert);
>     NamespaceInfo namespaceInfo = NamespaceMapper.toDTO(insertedData);
> ```

nit: NamespaceEntity.id is the namespace. We might not need this conversion



_Code quote:_
```Java
toDTO
```

**Review by vigneswara-propelo — DISMISSED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 2. unresolved discussions.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by vigneswara-propelo — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by deepharness — DISMISSED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 2. unresolved discussions.

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java` line 264 at r4](https://reviewable.io/reviews/harness/harness-core/44980#-NQUGV2Y144GbqD03C8L:-NQ_X7Ye8rbwa62DBBb9:b-896fjx) ([raw file](https://github.com/harness/harness-core/blob/a2eeeda3bd92518c192b2a4e43bfbe926d974a50/idp-service/src/main/java/io/harness/idp/k8s/client/K8sApiClient.java#L264)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: We could have this block before creating the message string.
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/44980#-NQUGtNG4YofdkhO0u_A:-NQ_XAeS3gxpGJQXIleJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a2eeeda3bd92518c192b2a4e43bfbe926d974a50/idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java#L26)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Let's use constructor injection going forward. Ref: https://rules.sonarsource.com/java/RSPEC-3306
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java` line 49 at r4](https://reviewable.io/reviews/harness/harness-core/44980#-NQUHR-2AVj711gIkcNb:-NQ_XCtZ6MVSNWCcmU6-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a2eeeda3bd92518c192b2a4e43bfbe926d974a50/idp-service/src/main/java/io/harness/idp/namespace/service/NamespaceServiceImpl.java#L49)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

nit: NamespaceEntity.id is the namespace. We might not need this conversion
</blockquote></details>

Done

**Comment by sarthakkasat** [comment]
trigger ut2

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by deepharness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: 2. unresolved discussions.

**Review by sathish-soundarapandian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44980)* status: :shipit: complete! ✓

**Pull request merged**
