### PR TITLE
[feat]: [CDS-40082]: Org and Project deletion, deletes templates in that scope

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35528)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger ti0

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35528)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/35528#-N7uUOkODZ6Fna-j0XUi:-N7uUOkODZ6Fna-j0XUj:b-tso5h1) ([raw file](https://github.com/harness/harness-core/blob/882b554fbee402ef7a54e7caf6e20d9b6e296cdc/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L38)):*
> ```Java
> @Singleton
> @OwnedBy(CDC)
> public class EntityCRUDStreamConsumer implements Runnable {
> ```

Make an abstract RedisStreamConsumer since most of code will just be copy paste in future for other stream consumers.
Create a constructor in abstract consumer which takes redisConsumer, messageListenerList and queueController. The classes extending this abstract consumer should provide these things .
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 570 at r2](https://reviewable.io/reviews/harness/harness-core/35528#-N7uZ4aM944nJRemEtn2:-N7uZ4aM944nJRemEtn3:b-f8cv5w) ([raw file](https://github.com/harness/harness-core/blob/882b554fbee402ef7a54e7caf6e20d9b6e296cdc/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L570)):*
> ```Java
> 
>   @Override
>   public boolean deleteAllTemplatesInAProject(String accountId, String orgId, String projectId) {
> ```

Add UT for this.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 580 at r2](https://reviewable.io/reviews/harness/harness-core/35528#-N7uYe75ESic7jYkVg1E:-N7uYe75ESic7jYkVg1F:btcyepl) ([raw file](https://github.com/harness/harness-core/blob/882b554fbee402ef7a54e7caf6e20d9b6e296cdc/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L580)):*
> ```Java
>                               .is(projectId);
>       Pageable pageRequest = org.springframework.data.domain.PageRequest.of(
>           0, 1000, Sort.by(Sort.Direction.DESC, TemplateEntityKeys.lastUpdatedAt));
> ```

nit: Make this as a static constant in the file



_Suggestion:_
```Java
1000
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 599 at r2](https://reviewable.io/reviews/harness/harness-core/35528#-N7uZRkb7nCHFPfovTBB:-N7uZRkcE8YjKtyLfw7b:bfw8auh) ([raw file](https://github.com/harness/harness-core/blob/882b554fbee402ef7a54e7caf6e20d9b6e296cdc/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L599)):*
> ```Java
> 
>   @Override
>   public boolean deleteAllOrgLevelTemplates(String accountId, String orgId) {
> ```

Add UT here as well

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35528)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/35528#-N7uUOkODZ6Fna-j0XUi:-N7yw3cvD6jtMbn0CseZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/882b554fbee402ef7a54e7caf6e20d9b6e296cdc/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L38)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Make an abstract RedisStreamConsumer since most of code will just be copy paste in future for other stream consumers.
Create a constructor in abstract consumer which takes redisConsumer, messageListenerList and queueController. The classes extending this abstract consumer should provide these things .
</blockquote></details>

Done.

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35528)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/35528#-N7z5MPk6cP9LzQHRD8_:-N7z5MPk6cP9LzQHRD8a:b1mu7h5) ([raw file](https://github.com/harness/harness-core/blob/eaa8646bd4e3a18a72a27db15e0a80c5469528f7/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L36)):*
> ```Java
>   private final Consumer redisConsumer;
>   private final List<MessageListener> messageListenersList;
>   private final QueueController queueController;
> ```

These fields are not required here since they are already present in abstractStreamConsumer.



_Code quote:_
```Java
  private final Consumer redisConsumer;
  private final List<MessageListener> messageListenersList;
  private final QueueController queueController;
```
___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/35528#-N7z5ZQP3zVwfVRwbU-4:-N7z5ZQP3zVwfVRwbU-5:b-u762be) ([raw file](https://github.com/harness/harness-core/blob/eaa8646bd4e3a18a72a27db15e0a80c5469528f7/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L47)):*
> ```Java
>     messageListenersList = new ArrayList<>();
>     messageListenersList.add(projectEntityCrudStreamListener);
>     messageListenersList.add(orgEntityCrudStreamListener);
> ```

super should be called with this messageListenerList.



_Code quote:_
```Java
super(redisConsumer, queueController, new ArrayList<MessageListener>());
```
___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/35528#-N7z4hJQCZIeywySJK5F:-N7z4hJQCZIeywySJK5G:b-8jcfct) ([raw file](https://github.com/harness/harness-core/blob/eaa8646bd4e3a18a72a27db15e0a80c5469528f7/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L55)):*
> ```Java
>     AtomicBoolean success = new AtomicBoolean(true);
>     messageListenersList.forEach(messageListener -> {
>       if (!messageListener.handleMessage(message)) {
> ```

This method could also be moved to AbstractStreamConsumer.
Any redis consumer must have listeners and this method calls all the listeners as expected. If need be, class extended abstractStreamConsumer could provide it's own implementation of this.



_Suggestion:_
```Java
  protected boolean processMessage(Message message) {
    AtomicBoolean success = new AtomicBoolean(true);
    messageListenersList.forEach(messageListener -> {
      if (!messageListener.handleMessage(message)) {
        success.set(false);
      }
    });
    return success.get();
  }
```

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35528#-:-N7zAV8v9Bvy9X03C74S:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/35528#-N7z5MPk6cP9LzQHRD8_:-N7zAQfJ0g0Y5D2C-soL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eaa8646bd4e3a18a72a27db15e0a80c5469528f7/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L36)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

These fields are not required here since they are already present in abstractStreamConsumer.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/35528#-N7z4hJQCZIeywySJK5F:-N7zAPu2AvK0UWpJRQh6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eaa8646bd4e3a18a72a27db15e0a80c5469528f7/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L55)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This method could also be moved to AbstractStreamConsumer.
Any redis consumer must have listeners and this method calls all the listeners as expected. If need be, class extended abstractStreamConsumer could provide it's own implementation of this.
</blockquote></details>

Done.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35528)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/35528#-N7z5ZQP3zVwfVRwbU-4:-N7zAdII2gx0YMPxAeLJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eaa8646bd4e3a18a72a27db15e0a80c5469528f7/840-template-service/src/main/java/io/harness/template/event/EntityCRUDStreamConsumer.java#L47)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

super should be called with this messageListenerList.
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35528)* status: :shipit: complete! ✓

**Pull request merged**
