### PR TITLE
[feat]: [CDS-46755]: List Versions API for AMI

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Describe your changes
This PR contains API to list versions for the dropdown on UI for AMI Artifacts. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40297)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/40297#-NH5296XBEtQEuTUOr3z:-NH5296XBEtQEuTUOr4-:b1wq638) ([raw file](https://github.com/harness/harness-core/blob/b6f7788d3fdac342ef986a80e48645cf45492f43/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java#L147)):*
> ```Java
>       }
> 
>       if (amiRequestBody.getTags().isEmpty()) {
> ```

can tags be runtime ? 
if not, tags must always come from the amiArtifactConfig because that is the one which is stored in the service

**Comment by arvind-choudhary-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/40297#-NH8blgM48dBlsr3Jdcy:-NH8blgNDeDVGt2ldCz4:b-lqubiv) ([raw file](https://github.com/harness/harness-core/blob/b6f7788d3fdac342ef986a80e48645cf45492f43/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java#L123)):*
> ```Java
>   @ApiOperation(value = "List Versions for AMI Artifacts", nickname = "listVersionsForAMIArtifact")
>   public ResponseDTO<List<BuildDetails>> listVersions(@QueryParam("connectorRef") String awsConnectorRef,
>       @QueryParam("region") String region, @QueryParam("versionRegex") String versionRegex,
> ```

what all fields can be `NotNull` ?

**Comment by arvind-choudhary-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/40297#-NH8cKpp-KraAVwY-bNA:-NH8cKpq24zYaNfdEkI1:b-l39ti0) ([raw file](https://github.com/harness/harness-core/blob/b6f7788d3fdac342ef986a80e48645cf45492f43/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java#L122)):*
> ```Java
>   @Path("versions")
>   @ApiOperation(value = "List Versions for AMI Artifacts", nickname = "listVersionsForAMIArtifact")
>   public ResponseDTO<List<BuildDetails>> listVersions(@QueryParam("connectorRef") String awsConnectorRef,
> ```

Will you be updating listTags in this PR or separate PR?

**Comment by vtxorxwitty** [comment]
1. @yogesh-chauhan The tags and filters can be runtime inputs.
2. @arvind-choudhary-h The only not-null parameter will be accountId. As region and connector ref can be null and we handled it to pick them from the given serviceRef.
3. @arvind-choudhary-h I'll create a separate PR for the tags issue. Will first have to check whether it's a BE or an FE issue. We can merge this one so that UI can integrate.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40297)* status: :shipit: complete! ✓

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40297)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/40297#-NH5296XBEtQEuTUOr3z:-NHAcu9D-raVsh_FPyqr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b6f7788d3fdac342ef986a80e48645cf45492f43/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/ami/AMIArtifactResource.java#L147)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can tags be runtime ? 
if not, tags must always come from the amiArtifactConfig because that is the one which is stored in the service
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40297)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
We need to write unit tests and also update the PR description

**Review by satyam-harness — APPROVED** [review]

**Review by satyam-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40297)* status: :shipit: complete! ✓

**Pull request merged**
