### PR TITLE
feat: [SRM-4206]: support expression in duration time

### PR DESCRIPTION
**Pull request by AbhijithHarness**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33435)

### CODE REVIEW

**Comment by AbhijithHarness** [comment]
trigger ti0

**Comment by AbhijithHarness** [comment]
trigger ti1

**Comment by AbhijithHarness** [comment]
trigger ti3

**Comment by AbhijithHarness** [comment]
trigger ti0

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33435#-:-N2q4gsQ1BP3ybKEBXSj:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
