### PR TITLE
[fix]: [CDS-81515]: Adding support for http method metrics and pipeline and input set resource

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Changes - Adding support for HTTP method metrics and pipeline and input set resource

Impact - There is no impact for executions or crud operations

Testing -
a) Tested metrics are getting published for HTTP methods and resources
Screenshot 2023-11-02 at 11 29 00 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54864)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger ut5, ut6, ut8

**Comment by archit-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/metrics/DwMetricContext.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/54864#-NiITfmF-IuDfKSRiL3H:-NiITfmF-IuDfKSRiL3I:b-3tt1hs) ([raw file](https://github.com/harness/harness-core/blob/6004486f11c7dca16428e122d3579e421b74ef4f/970-ng-commons/src/main/java/io/harness/metrics/DwMetricContext.java#L30)):*
> ```Java
> 
>   public DwMetricContext(String method, String resource, String namespace, String containerName, String serviceName) {
>     put("method", method);
> ```

nit: can we reduce repeatition by calling the last constructor with null values for keys that are not required?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54864)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54864)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/metrics/DwMetricContext.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/54864#-NiITfmF-IuDfKSRiL3H:-NiIaIKL9Bm2cEHIj9hT:b-kedkcf) ([raw file](https://github.com/harness/harness-core/blob/6004486f11c7dca16428e122d3579e421b74ef4f/970-ng-commons/src/main/java/io/harness/metrics/DwMetricContext.java#L30)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: can we reduce repeatition by calling the last constructor with null values for keys that are not required?
</blockquote></details>

Will add it in next pr

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54864)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54864)* status: :shipit: complete! ✓

**Pull request merged**
