### PR TITLE
fix: [CDS-73243]: fix the error message

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Improve the error message if user tries to save template with same identifier and version of different  entity type.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51441)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51441)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 352 at r1](https://reviewable.io/reviews/harness/harness-core/51441#-NbINkpw2DANAmE_OYQZ:-NbINkpw2DANAmE_OYQ_:bwg2eqv) ([raw file](https://github.com/harness/harness-core/blob/d5d80d0508ac830276a4df5384ca6552b8515568/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L352)):*
> ```Java
>         throw NestedExceptionUtils.hintWithExplanationException(
>             String.format("Error while saving template [%s] of versionLabel [%s]: "
>                     + "Failed to save the template because an existing template of a different type has the same name and identifier",
> ```

I think the message here needs to be different. Its a different if condition here. Please check once. Refer the removed messages.

**Comment by shivamnegi94** [comment]
@mohitg0795 As per the ticket, existing error message was not clear to the customer.
Error message is suggested by PM in ticket - https://harness.atlassian.net/browse/CDS-73243

**Comment by shivamnegi94** [comment]
trigger review

**Comment by shivamnegi94** [comment]
trigger uts

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51441)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 352 at r1](https://reviewable.io/reviews/harness/harness-core/51441#-NbINkpw2DANAmE_OYQZ:-NbImVhw-vuRZVS7N_jk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5d80d0508ac830276a4df5384ca6552b8515568/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L352)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think the message here needs to be different. Its a different if condition here. Please check once. Refer the removed messages.


</blockquote></details>

Done.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by shivamnegi94** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Comment by shivamnegi94** [comment]
trigger review

**Comment by shivamnegi94** [comment]
trigger ut0

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Pull request merged**
