### PR TITLE
[techDebt]: [DEL-3891]: Move CollaborationProviderTask and related class to 930

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32797)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`800-pipeline-service/src/test/resources/mongo/indexes.txt` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/32797#-N1GdX_TBiUYzUfOHqWN:-N1GdX_UBfs-KHGJvsEz:b-fqsjnr) ([raw file](https://github.com/harness/harness-core/blob/b9122e28b6f8562e91262dc53f838a0e3ea133af/800-pipeline-service/src/test/resources/mongo/indexes.txt#L77)):*
> ```help
> encryptedRecords {"name": "path_1", "background": true} {"path": 1}
> entitySetupUsage {"name": "EntitySetupUsage_unique_index", "unique": true} {"referredByEntityType": 1, "referredByEntityFQN": 1, "referredByEntityRepoIdentifier": 1, "referredByEntityBranch": 1, "referredEntityType": 1, "referredEntityFQN": 1, "referredEntityRepoIdentifier": 1, "referredEntityBranch": 1, "accountIdentifier": 1}
> entitySetupUsage {"name": "ReferredByEntityIndex", "background": true} {"account`Identifier": 1, "referredByEntityType": 1, "referredByEntityFQN": 1}
> ```

Is this intentional?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32797)* status: 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`800-pipeline-service/src/test/resources/mongo/indexes.txt` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/32797#-N1GdX_TBiUYzUfOHqWN:-N1GqrRt5CovTLVOPtXq:b-ijonl2) ([raw file](https://github.com/harness/harness-core/blob/b9122e28b6f8562e91262dc53f838a0e3ea133af/800-pipeline-service/src/test/resources/mongo/indexes.txt#L77)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

yes test failure

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32797)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`800-pipeline-service/src/test/resources/mongo/indexes.txt` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/32797#-N1GdX_TBiUYzUfOHqWN:-N1H3OaiAvRwVPeT5Zb_:b2ni8n8) ([raw file](https://github.com/harness/harness-core/blob/b9122e28b6f8562e91262dc53f838a0e3ea133af/800-pipeline-service/src/test/resources/mongo/indexes.txt#L77)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

yes test failure
</blockquote></details>

no

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32797)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
trigger ti3

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32797)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger ti3

**Pull request merged**
