### PR TITLE
feat: [PL-29306]: Alerting for GitSyncError per Application level.

### PR DESCRIPTION
**Pull request by boopesh007**
## Alerting for GitSyncError at the Application level

We send alerts for git sync errors at the account level and we notify only for the first error, after which we will not notify it to the user until all the errors are discarded by the user. Now we do that at the application level, the changes are behind the FF. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42173)

### CODE REVIEW

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42173)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1177 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYkKtD8O_yEHMYQx0:-NLhYkKtD8O_yEHMYQx1:b-5wnzrd) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1177)):*
> ```Java
>     query.field(GitSyncErrorKeys.yamlFilePath).in(yamlFilePathList);
>     wingsPersistence.delete(query);
>     Set<String> appIdsFromYamlFilePaths =
> ```

do we need ff here?
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1200 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYpEu4TtxS5BzTwBw:-NLhYpEu4TtxS5BzTwBx:bmps4ui) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1200)):*
> ```Java
>     GitSyncError gitSyncError = wingsPersistence.get(GitSyncError.class, errorId);
>     wingsPersistence.delete(query);
>     closeAlertIfApplicable(accountId, gitSyncError.getAppId());
> ```

do we need to pass global_app_id in some cases?
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1210 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYucZ5p0qDSaPPVpX:-NLhYucZ5p0qDSaPPVpY:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1210)):*
> ```Java
>     query.filter(GitSyncErrorKeys.yamlFilePath, yamlFilePath);
>     wingsPersistence.delete(query);
>     closeAlertIfApplicable(accountId, yamlHelper.getAppId(accountId, yamlFilePath));
> ```

ditto
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1223 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYvbc9qnPJB-h7iRP:-NLhYvbc9qnPJB-h7iRQ:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1223)):*
> ```Java
>         yamlHelper.getAppIdsFromYamlFilePaths(new HashSet<>(yamlFilePaths), accountId);
>     appIdsFromYamlFilePaths.forEach(appId -> closeAlertIfApplicable(accountId, appId));
>     return RestResponse.Builder.aRestResponse().build();
> ```

ditto
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1232 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYwCPAdnrBPtrYaz-:-NLhYwCPAdnrBPtrYaz0:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1232)):*
> ```Java
>     wingsPersistence.delete(query);
>     Set<String> appIds = appService.getAppIdsAsSetByAccountId(accountId);
>     appIds.add(GLOBAL_APP_ID);
> ```

ditto

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1177 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYkKtD8O_yEHMYQx0:-NLj-vpf0C5LJl7uCdg8:b-2dmjvf) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1177)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

do we need ff here?
</blockquote></details>

I initially thought so, but what if the customers enable FF and then the alert comes with appID, now if the FF is turned off and now if they try to discard, it will not be discarded because the appId will not match. Hence I put it outside FF. Else i can do one more thing, behind FF i can discard first with appId and do one more duplicate discard with _GLOBAL_APP_ID_. @abhinav-harness what you suggest here.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1200 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYpEu4TtxS5BzTwBw:-NLj1GjsDJzSakkhxYqX:b-yx9f3r) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1200)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

do we need to pass global_app_id in some cases?
</blockquote></details>

the GitSync error is having __GLOABL_APP_ID_ for account level git sync errors, hence gitSyncError.getAppid() will return the _GLOBAL_APP_ID_

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1210 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYucZ5p0qDSaPPVpX:-NLnhkhSC1cGJQgmeG0F:b-6q92kk) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1210)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

same, appId is _GLOABL_APP_ID in yamlFilePath, so it will get generated.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1223 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYvbc9qnPJB-h7iRP:-NLni0se2rL5b9OH2rIR:b1ru1if) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1223)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

same reason

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42173)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java` line 1177 at r4](https://reviewable.io/reviews/harness/harness-core/42173#-NLhYkKtD8O_yEHMYQx0:-NLtYU_eEni1Vrs7Lrcy:b-1k3ioc) ([raw file](https://github.com/harness/harness-core/blob/83e96f9305ec4031250ffd84d03e565ddfb8dfff/400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java#L1177)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

I initially thought so, but what if the customers enable FF and then the alert comes with appID, now if the FF is turned off and now if they try to discard, it will not be discarded because the appId will not match. Hence I put it outside FF. Else i can do one more thing, behind FF i can discard first with appId and do one more duplicate discard with _GLOBAL_APP_ID_. @abhinav-harness what you suggest here. 
</blockquote></details>

yeah do that

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42173)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42173)* status: :shipit: complete! ✓

**Pull request merged**
