### PR TITLE
[feat]: [CDS-38027]: Empty page when no referred by entity type

### PR DESCRIPTION
**Pull request by vladimir-peric**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33507)

### CODE REVIEW

**Comment by vladimir-peric** [comment]
trigger ti1

**Comment by vladimir-peric** [comment]
trigger ti2, trigger ti3, trigger ti4

**Comment by vladimir-peric** [comment]
trigger ti1, trigger ti3, trigger ti4

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33507#-:-N2ub1IO4plgwTyJvAXU:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
