### PR TITLE
[fix]: [PL-32740]: HOTFIX CHANGE: redis acknowledge message without waiting for sync. API to trigger one individual group sync

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
- For NG LDAP periodic sync, the same redis message was consumed multiple times as it is not acknowledged immediately (acknowledged when entire groups are synced which takes 20-30 minutes of time), and this is leading to multiple LDAP syncs happening for customer and overloading their LDAP server and harness as well. 

- As part of this hotfix for debugging help we are also giving an API(Hidden) for only one user group sync

Testing Done:
- Create/Delete/Update LDAP settings.
- Link LDAP userGroup to Harness user group.
- Trigger all groups sync.
- Trigger one group sync using API.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 273 at r1](https://reviewable.io/reviews/harness/harness-core/49897#-NZ5Lu5IDJ1bkVlkDIAt:-NZ5Lu5JAT3tI3mdQ9uc:b-ctq32i) ([raw file](https://github.com/harness/harness-core/blob/9acf914ec0af2a2d55ca52d2767ddb75011c9535/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L273)):*
> ```Java
>     Map<UserGroup, LdapGroupResponse> userGroupsToLdapGroupMap = new HashMap<>();
> 
>     if (isNotEmpty(userGroupsToSync)) {
> ```

Avoid nesting.



_Code snippet:_
```Java
 if (isEmpty(userGroupsToSync)) {
   return;
 }
 for (UserGroup userGroup : userGroupsToSync) {
   .....
 }
```

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java` line 273 at r1](https://reviewable.io/reviews/harness/harness-core/49897#-NZ5Lu5IDJ1bkVlkDIAt:-NZ5Mrcx1fX3Bo7NsEye:bkskwr2) ([raw file](https://github.com/harness/harness-core/blob/9acf914ec0af2a2d55ca52d2767ddb75011c9535/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl/NGLdapServiceImpl.java#L273)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Avoid nesting.
</blockquote></details>

Will handle in develop PR, thanks

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/LdapGroupSyncStreamConsumer.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/49897#-NZ5Mv_w6AEKJ4ggN3-5:-NZ5Mv_w6AEKJ4ggN3-6:bavc3xe) ([raw file](https://github.com/harness/harness-core/blob/9acf914ec0af2a2d55ca52d2767ddb75011c9535/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/LdapGroupSyncStreamConsumer.java#L81)):*
> ```Java
>       redisConsumer.acknowledge(messageId);
>       log.info("EVENT_LDAP_GROUP_SYNC: acknowledged and processing message with id: {}", messageId);
>       handleMessage(message);
> ```

What if handleMessage fails? Shouldn't the message be put back to stream in that case?

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/LdapGroupSyncStreamConsumer.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/49897#-NZ5Mv_w6AEKJ4ggN3-5:-NZ5Nt951jk5g__O-X-x:bjtw85) ([raw file](https://github.com/harness/harness-core/blob/9acf914ec0af2a2d55ca52d2767ddb75011c9535/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/LdapGroupSyncStreamConsumer.java#L81)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What if handleMessage fails? Shouldn't the message be put back to stream in that case?
</blockquote></details>

The handleMessage is handled to capture the exception and throw it, which doesn't have any side effect apart from the fact that sync didn't complete. The sync would anyway get re-triggered in next cycle, or can be triggered manually again. Thanks

**Comment by tiwaritejas** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)_ status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.
> 
> _[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/LdapGroupSyncStreamConsumer.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/49897#-NZ5Mv_w6AEKJ4ggN3-5:-NZ5Mv_w6AEKJ4ggN3-6:bavc3xe) ([raw file](https://github.com/harness/harness-core/blob/9acf914ec0af2a2d55ca52d2767ddb75011c9535/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler/LdapGroupSyncStreamConsumer.java#L81)):_
> 
> > ```java
> >       redisConsumer.acknowledge(messageId);
> >       log.info("EVENT_LDAP_GROUP_SYNC: acknowledged and processing message with id: {}", messageId);
> >       handleMessage(message);
> > ```
> 
> What if handleMessage fails? Shouldn't the message be put back to stream in that case?

+1

**Review by tiwaritejas — APPROVED** [review]

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)* status: 6 file(s) to review.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)* status: 6 file(s) to review.

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49897)* status: 6 file(s) to review.

**Review by shashank-harness — COMMENTED** [review]
lgtm

**Pull request merged**
