### PR TITLE
[feat]: [CDS-46321]: Artifact rollback outcome added for all infa kinds

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Describe your changes
Rollback artifact outcome is included for all infra kinds (SSH/WinRm, PDC, K8s, ECS, Serverless, PDC, Custom deployment). With this change variable <+rollbackArtifact> can be used within shell scripts to fetch rollback artifact data (e.g. rollbackArtifact.image, rollbackArtifact.tag ...) 

rollback_artifact_before
rollback_artifact_after
rollback_artifact_script

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40675)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40675)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/DefaultExecutionDetails.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/40675#-NHks3sUBsFZmFM1Pd71:-NHks3sUBsFZmFM1Pd72:b-xn7m3p) ([raw file](https://github.com/harness/harness-core/blob/12e8ee5191cc857c1dd2fd5522aa9390eee51224/125-cd-nextgen/src/main/java/io/harness/cdng/execution/DefaultExecutionDetails.java#L23)):*
> ```Java
> @Data
> @Builder
> @JsonTypeName("ExecutionDetails")
> ```

Rename ExecutionDetails to DefaultExecutionDetails in @JsonTypeName.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 322 at r2](https://reviewable.io/reviews/harness/harness-core/40675#-NHksfE845-LaFIQf2-H:-NHksfE845-LaFIQf2-I:bnwfbx4) ([raw file](https://github.com/harness/harness-core/blob/12e8ee5191cc857c1dd2fd5522aa9390eee51224/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L322)):*
> ```Java
>   }
> 
>   private InstanceInfo getInstanceInfo(InfrastructureOutcome infrastructureOutcome, String serviceType, String host) {
> ```

Why have we updated the logic for instances? This shouldn't be changed.
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/DefaultInstanceInfo.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/40675#-NHkt1wZ7IpT_kM7-nKo:-NHkt1wZ7IpT_kM7-nKp:b6yxigq) ([raw file](https://github.com/harness/harness-core/blob/12e8ee5191cc857c1dd2fd5522aa9390eee51224/126-instance/src/main/java/io/harness/entities/instanceinfo/DefaultInstanceInfo.java#L24)):*
> ```Java
> @AllArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> public class DefaultInstanceInfo extends InstanceInfo {
> ```

We shouldn't change/update logic for instances.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40675)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/DefaultExecutionDetails.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/40675#-NHks3sUBsFZmFM1Pd71:-NI1ZoxM5JX8nQRFn1XB:b-k2vryk) ([raw file](https://github.com/harness/harness-core/blob/12e8ee5191cc857c1dd2fd5522aa9390eee51224/125-cd-nextgen/src/main/java/io/harness/cdng/execution/DefaultExecutionDetails.java#L23)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Rename ExecutionDetails to DefaultExecutionDetails in @JsonTypeName.
</blockquote></details>

Minor - it's better to have DefaultExecutionDetails for type name instead of defaultExecutionDetails but this is minor.



_Code quote:_
```Java
defaultExecutionDetails
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/40675#-NI1cYhyEcOBO54RC6fA:-NI1cYhyEcOBO54RC6fB:bol073k) ([raw file](https://github.com/harness/harness-core/blob/73f6c6b5aeefa387b5e6599be0da2b1167892a3b/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L86)):*
> ```Java
>   @Inject private InstanceDeploymentInfoService instanceDeploymentInfoService;
> 
>   public boolean shouldSaveStageExecutionInfo(String infrastructureKind) {
> ```

Where do we use this method?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 122 at r4](https://reviewable.io/reviews/harness/harness-core/40675#-NI1bPoH5a5s7QPqqodd:-NI1bPoH5a5s7QPqqode:b-wdtmu6) ([raw file](https://github.com/harness/harness-core/blob/73f6c6b5aeefa387b5e6599be0da2b1167892a3b/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L122)):*
> ```Java
>     }
> 
>     Optional<ExecutionDetails> executionDetails = getExecutionDetailsByInfraKind(ambiance, infrastructureKind);
> ```

We need and skip the saving execution key because there is no need to store the execution key when skipping saving execution data. To achieve it, move the code from  
saveStageExecutionInfo to saveStageExecutionInfoAndPublishExecutionInfoKey, skip and saving execution key, delete saveStageExecutionInfo method and fix tests.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java` line 301 at r4](https://reviewable.io/reviews/harness/harness-core/40675#-NI1_T2bAbYv4PcZq8XA:-NI1_T2bAbYv4PcZq8XB:b-qt7aew) ([raw file](https://github.com/harness/harness-core/blob/73f6c6b5aeefa387b5e6599be0da2b1167892a3b/125-cd-nextgen/src/main/java/io/harness/cdng/execution/helper/StageExecutionHelper.java#L301)):*
> ```Java
>       return Optional.of(CustomDeploymentExecutionDetails.builder().artifactsOutcome(artifactsOutcome).build());
>     }
>     Optional<ArtifactOutcome> artifactOutcome = cdStepHelper.resolveArtifactsOutcome(ambiance);
> ```

Minor - If artifactOutcome is not present return Optional.empty()
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/DefaultInstanceInfo.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/40675#-NHkt1wZ7IpT_kM7-nKo:-NI1_itK35fNB6Dp6GrA:biecory) ([raw file](https://github.com/harness/harness-core/blob/12e8ee5191cc857c1dd2fd5522aa9390eee51224/126-instance/src/main/java/io/harness/entities/instanceinfo/DefaultInstanceInfo.java#L24)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We shouldn't change/update logic for instances. 
</blockquote></details>

Delete this unnecessary class.

**Comment by vladimir-peric** [comment]
trigger smartchecks

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40675#-:-NI2DbH32lEIxDeoIEMC:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
:lgtm

> Reviewed 2 of 7 files at r1, 3 of 4 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40675#-:-NI2WPy_DKMG40GziFIl:b-8eqf7b)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 4 files at r4, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40675)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 4 files at r4, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40675)* status: :shipit: complete! ✓

**Pull request merged**
