### PR TITLE
[feat]: [CDS-69740]: Reduced GitSyncGrpcClientUtils retry to 1 instead of 3

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have reduced the number of retries from 3 to 1 for gitSyncGrpc client. Have tested out the crud and execution flow for the new gitx. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48237)

### CODE REVIEW

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncGrpcClientUtils.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/48237#-NW7KU5aE6jRpQ2KWIzs:-NW7KU5aE6jRpQ2KWIzt:be42ga) ([raw file](https://github.com/harness/harness-core/blob/9dbfb4dfceeb0da2de4c9b2bdadc0099ea2b8ee1/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncGrpcClientUtils.java#L98)):*
> ```Java
>         .withMaxAttempts(1)
>         .onFailedAttempt(event
>             -> log.warn(String.format("Harness to Git grpc retry attempt: %d", event.getAttemptCount()),
> ```

messages shouldn't mention anything about git-sync

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48237)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/48237#-NW7Jmp-CGYGPXF5EHc_:-NW7SZ1F-gFhbGSDsF_H:b-tm2rfo) ([raw file](https://github.com/harness/harness-core/blob/9dbfb4dfceeb0da2de4c9b2bdadc0099ea2b8ee1/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/SCMGitSyncHelper.java#L108)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we are touching old git sync methods here, why?
</blockquote></details>

Done. reverted
___
*[`953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncGrpcClientUtils.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/48237#-NW7KU5aE6jRpQ2KWIzs:-NW7cVVq7h4RbGFnph_w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9dbfb4dfceeb0da2de4c9b2bdadc0099ea2b8ee1/953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper/GitSyncGrpcClientUtils.java#L98)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

messages shouldn't mention anything about git-sync
</blockquote></details>

Done.

**Review by shalini-agr — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger ut4

**Pull request merged**
