### PR TITLE
fix: [CDS-49990]: Fixing the SSH workflow using Project type connector for Azure Store

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
When we configure SSH auth type using Azure repo store (Project type connector) we used to add "_git" to the final repo URL. This created an invalid url and the connection used to fail. "_git" substring must only be appended to HTTP auth type.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 385 at r1](https://reviewable.io/reviews/harness/harness-core/43271#-NN6Rm-T2n173JsT7P3E:-NN6Rm-V7Tizi1QcbJxH:b-aud0as) ([raw file](https://github.com/harness/harness-core/blob/e19917084af6191b162159bca5e969ace4f0bd00/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L385)):*
> ```Java
>     if (scmConnector instanceof GitConfigDTO) {
>       GitConfigDTO gitConfigDTO = (GitConfigDTO) scmConnector;
>       String repoUrl = convertGitAccountProjectUrlToRepoUrl(gitConfigDTO, gitstoreConfig, repoName);
> ```

Not clear why we need to handle this for GitConfigDTO

**Comment by abhinavsingh1196** [comment]
@GoelPratyush99  please write a bit more detailed PR description

**Comment by GoelPratyush99** [comment]
trigger messagecheck

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 385 at r1](https://reviewable.io/reviews/harness/harness-core/43271#-NN6Rm-T2n173JsT7P3E:-NN_wNBb8YPEKZeL8jid:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ea8c770af812ec946fb5355d45789e46b3db747d/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L385)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Not clear why we need to handle this for GitConfigDTO
</blockquote></details>

Done.

**Comment by GoelPratyush99** [comment]
> @GoelPratyush99 please write a bit more detailed PR description

Done

**Comment by GoelPratyush99** [comment]
trigger ti0
trigger ti1
trigger ti2
trigger ti3
trigger ti4

**Comment by GoelPratyush99** [comment]
trigger ti4

**Comment by GoelPratyush99** [comment]
trigger ti3

**Comment by GoelPratyush99** [comment]
trigger ti2

**Comment by GoelPratyush99** [comment]
trigger ti1

**Comment by GoelPratyush99** [comment]
trigger ti0

**Review by abhinavsingh1196 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 381 at r3](https://reviewable.io/reviews/harness/harness-core/43271#-NNbuvC61Gsi2yNxUbAT:-NNbuvC61Gsi2yNxUbAU:bjqsmer) ([raw file](https://github.com/harness/harness-core/blob/a08124eeeac33cddcdb2681fe3c8e2eb93f4b005/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L381)):*
> ```Java
> 
>   public void convertToRepoGitConfig(GitStoreConfig gitstoreConfig, ScmConnector scmConnector) {
>     String repoName = gitstoreConfig.getRepoName() != null ? gitstoreConfig.getRepoName().getValue() : null;
> ```

could this actually be null? if yes, will a meaningful error be thrown here?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 388 at r3](https://reviewable.io/reviews/harness/harness-core/43271#-NNbvqy0CRwyOj_xXzdk:-NNbvqy0CRwyOj_xXzdl:b71pwtu) ([raw file](https://github.com/harness/harness-core/blob/a08124eeeac33cddcdb2681fe3c8e2eb93f4b005/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L388)):*
> ```Java
>               && gitConfigDTO.getGitConnectionType() == GitConnectionType.PROJECT)) {
>         String repoUrl =
>             convertGitAccountProjectUrlToRepoUrl(gitstoreConfig, gitConfigDTO, gitConfigDTO.getGitAuthType(), repoName);
> ```

should we keep `isNotEmpty(repoUrl)` here? 
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/43271#-NNbwTs025tjFCz7E6A_:-NNbwTs025tjFCz7E6Aa:b-okr82u) ([raw file](https://github.com/harness/harness-core/blob/a08124eeeac33cddcdb2681fe3c8e2eb93f4b005/125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java#L142)):*
> ```Java
> import org.mockito.junit.MockitoRule;
> 
> public class CDStepHelperTest extends CategoryTest {
> ```

do existing tests cover this change?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 381 at r3](https://reviewable.io/reviews/harness/harness-core/43271#-NNbuvC61Gsi2yNxUbAT:-NNfOgPtBMRzrnB-NrE5:breax43) ([raw file](https://github.com/harness/harness-core/blob/a08124eeeac33cddcdb2681fe3c8e2eb93f4b005/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L381)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

could this actually be null? if yes, will a meaningful error be thrown here?
</blockquote></details>

Yes Repo Name is an optional field. So if the user selects Repo connection type then this field will be null.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 388 at r3](https://reviewable.io/reviews/harness/harness-core/43271#-NNbvqy0CRwyOj_xXzdk:-NNfOuonDZyToVmul6NO:buwy9go) ([raw file](https://github.com/harness/harness-core/blob/a08124eeeac33cddcdb2681fe3c8e2eb93f4b005/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L388)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

should we keep `isNotEmpty(repoUrl)` here? 
</blockquote></details>

repoUrl will never be empty as if we consider the worst case (somehow we passed validation with empty url) we are appending the processed repoName `purgedRepoUrl + "/" + purgedRepoName` / `purgedRepoUrl + GIT + purgedRepoName`. Hence it will never be null
___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java` line 142 at r3](https://reviewable.io/reviews/harness/harness-core/43271#-NNbwTs025tjFCz7E6A_:-NNfPR5G5KjFI2uD3HJs:b-t09lxq) ([raw file](https://github.com/harness/harness-core/blob/a08124eeeac33cddcdb2681fe3c8e2eb93f4b005/125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java#L142)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

do existing tests cover this change?
</blockquote></details>

Added one for SSH

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java` line 388 at r4](https://reviewable.io/reviews/harness/harness-core/43271#-NNfU8Vl77IDiKbmxeru:-NNfU8VmDR2eYhptdcnI:bk4cpow) ([raw file](https://github.com/harness/harness-core/blob/0589d65ea6030c40f82ab639fdb978849f568013/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java#L388)):*
> ```Java
>               && gitConfigDTO.getGitConnectionType() == GitConnectionType.PROJECT)) {
>         String repoUrl =
>             convertGitAccountProjectUrlToRepoUrl(gitstoreConfig, gitConfigDTO, gitConfigDTO.getGitAuthType(), repoName);
> ```

annotate method with NotNull

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43271)* status: :shipit: complete! ✓

**Pull request merged**
