### PR TITLE
[fix]:[pl-27879]: Code fix for creation of nested remote templates

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Code fix for creation of nested remote templates. The following has been tested:
1. creation of nested remote templates
2. creation of nested inline templates
3. creation of non nested remote templates
4. creation of non nested inline templates
5. creation of remote step and inline stage
6. creation of inline step and remote stage

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37060)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37060)

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1019 at r1](https://reviewable.io/reviews/harness/harness-core/37060#-NAyYmo63i_9ADiCGlU9:-NAyYmoAEOzIiFKob64M:b-1929vj) ([raw file](https://github.com/harness/harness-core/blob/da5e3e19c0e5f2989cb3f8aa37d295b63e628576/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1019)):*
> ```Java
> 
>   private void setupGitParentEntityDetails() {
>     GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
> ```

lets add a null check over here just to be sure.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37060)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1019 at r1](https://reviewable.io/reviews/harness/harness-core/37060#-NAyYmo63i_9ADiCGlU9:-NBAqiUB0YXlLaLgG3H7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/da5e3e19c0e5f2989cb3f8aa37d295b63e628576/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1019)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets add a null check over here just to be sure.
</blockquote></details>

Done.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37060)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37060)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37060)* status: :shipit: complete! ✓

**Comment by adivishy1** [comment]
trigger codebasehash

**Pull request merged**
