### PR TITLE
feat: [SRM-14550]: adding slo error budget reset details to secondary-events API

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46608)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46608)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 239 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSJfTEEZb2_ePYvOoV:-NTSJfTFD6TIYB3mjFxd:bhmmofu) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L239)):*
> ```Java
>       @Parameter(description = NGCommonEntityConstants.ACCOUNT_PARAM_MESSAGE) @AccountIdentifier @QueryParam(
>           "accountId") @NotNull String accountIdentifier,
>       @NotNull @QueryParam("secondaryEventType") SecondaryEventsType type,
> ```

why we have removed the valid annotation?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 577 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSK2sy6qnhTKrFOZl3:-NTSK2sy6qnhTKrFOZl4:b-wh1xkx) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L577)):*
> ```Java
> 
>     // Adding error budget resets
>     if (serviceLevelObjectiveV2DTO.getSloTarget().getType() == SLOTargetType.CALENDER) {
> ```

we can have an abstract method isResetErrorBudgetEnabled? (calendar can return true and rolling as false. (it can be used at multiple places)
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 585 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSKNSZDJGg8kjVAdlf:-NTSKNSZDJGg8kjVAdlg:b-cpbuay) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L585)):*
> ```Java
>                                             .type(SecondaryEventsType.ERROR_BUDGET_RESET)
>                                             .identifiers(Collections.singletonList(errorBudgetReset.getUuid()))
>                                             .startTime(errorBudgetReset.getCreatedAt() / 1000)
> ```

Time.MilliSecond.toSecond. will help in better understanding
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 608 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSL5G9ACglq4kWBQQp:-NTSL5G9ACglq4kWBQQq:b-tsxz44) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L608)):*
> ```Java
>             .details(DowntimeInstanceDetails.builder().build())
>             .build();
>       case ERROR_BUDGET_RESET:
> ```

We can have an interface  which has getInstanceByUuid and annotation service, entityUnavailabilityStatusesService and sloErrorBudgetResetService can implement it. 
then we can have a map binder <eventtype, entityinterface> and get rid of this switch case. In future if we have more usecase we can extend the same interface.

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46608)* status: 3 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 586 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTTBYnl2Kw8ySYRUoJE:-NTTBYnl2Kw8ySYRUoJF:b-ellarq) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L586)):*
> ```Java
>                                             .identifiers(Collections.singletonList(errorBudgetReset.getUuid()))
>                                             .startTime(errorBudgetReset.getCreatedAt() / 1000)
>                                             .endTime(errorBudgetReset.getCreatedAt() / 1000)
> ```

We don't need to send endTime as UI won't be using that. You can change the endTime field in SecondaryEventsResponse to non-primitive Long



_Code quote:_
```Java
.endTime(errorBudgetReset.getCreatedAt() / 1000)
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 613 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTTBltP3z3jxZwlW_wA:-NTTBltP3z3jxZwlW_wB:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L613)):*
> ```Java
>             .type(SecondaryEventsType.ERROR_BUDGET_RESET)
>             .startTime(sloErrorBudgetReset.getCreatedAt() / 1000)
>             .endTime(sloErrorBudgetReset.getCreatedAt() / 1000)
> ```

same



_Code quote:_
```Java
 .endTime(sloErrorBudgetReset.getCreatedAt() / 1000)
```

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46608)* status: 3 file(s) to review. 2 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java` line 239 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSJfTEEZb2_ePYvOoV:-NTTgkcS1AKh9HONqwFi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L239)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

why we have removed the valid annotation?
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 577 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSK2sy6qnhTKrFOZl3:-NTTgk9yBGlPHxNpUROq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L577)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

we can have an abstract method isResetErrorBudgetEnabled? (calendar can return true and rolling as false. (it can be used at multiple places)
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 585 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSKNSZDJGg8kjVAdlf:-NTTgn_y1StPMdluKi6_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L585)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Time.MilliSecond.toSecond. will help in better understanding
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 586 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTTBYnl2Kw8ySYRUoJE:-NTTgnw22CKuG0XPkfqJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L586)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We don't need to send endTime as UI won't be using that. You can change the endTime field in SecondaryEventsResponse to non-primitive Long
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 608 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTSL5G9ACglq4kWBQQp:-NTYjvi4EfttMF56ar54:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L608)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

We can have an interface  which has getInstanceByUuid and annotation service, entityUnavailabilityStatusesService and sloErrorBudgetResetService can implement it. 
then we can have a map binder <eventtype, entityinterface> and get rid of this switch case. In future if we have more usecase we can extend the same interface.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 613 at r2](https://reviewable.io/reviews/harness/harness-core/46608#-NTTBltP3z3jxZwlW_wA:-NTTgpCH-NMByaRkNqy6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1bd74f754045aba298ebb486e0263f40a417622d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L613)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 1 of 8 files at r1, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46608)* status: 1 change requests. 6. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 22 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46608#-:-NTZ-Z3M89De1y1MLyQY:bnfp4nl)* status: 6. unresolved discussions.

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46608)* status: 2. unresolved discussions.

**Pull request merged**
