### PR TITLE
fix: [DEL-4321]: fix audit trail gap with delegates

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
1. Audit trail was not being captured when ng k8s delegate was being downloaded.
2. TokenName was not being captured in audit events when delegate registers for the first time.

this two has been taken care of. Change was to just refractor the code and organize it to capture proper events. Screenshots have been attached in the jira.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/34734#-N5rzmNL5dhEslDwI1qx:-N5rzmNL5dhEslDwI1qy:b-xi1y3y) ([raw file](https://github.com/harness/harness-core/blob/b160fefcc493a3bc39e2850d0078b18ec4e9b5a3/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L523)):*
> ```Java
> 
>   @POST
>   @Path("validate-kubernetes-yaml")
> ```

do not remove the APIs, let the UI start using new APIs and then remove them in the next release

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3940 at r1](https://reviewable.io/reviews/harness/harness-core/34734#-N5s-T462O_K-wT3X1tv:-N5s-T462O_K-wT3X1tw:b-ww6xe2) ([raw file](https://github.com/harness/harness-core/blob/d20f87948ab34bcd4844791db65a2cd7c3359d96/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3940)):*
> ```Java
>       DelegateGroup delegateGroup =
>           upsertDelegateGroup(delegateSetupDetails.getName(), accountId, delegateSetupDetails);
>       sendNewDelegateGroupAuditEvent(delegateSetupDetails, delegateGroup, accountId);
> ```

where are we adding token in the audit event?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/34734#-N5rzmNL5dhEslDwI1qx:-N5s6vqr1zXTdz7JA8a3:bogfdk5) ([raw file](https://github.com/harness/harness-core/blob/b160fefcc493a3bc39e2850d0078b18ec4e9b5a3/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L523)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do not remove the APIs, let the UI start using new APIs and then remove them in the next release
</blockquote></details>

yes, UI is not using these APIs since long, there is a lot of mess around these classes/methods.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3940 at r1](https://reviewable.io/reviews/harness/harness-core/34734#-N5s-T462O_K-wT3X1tv:-N5s6OCM9SgaqU8n5nbW:btzcbvy) ([raw file](https://github.com/harness/harness-core/blob/d20f87948ab34bcd4844791db65a2cd7c3359d96/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3940)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

where are we adding token in the audit event?
</blockquote></details>

delegateSetupDetails will be having the tokenName. Also, This audit event is triggered for downloading a yaml.

**Review by AnupamIO — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/34734#-N5rzmNL5dhEslDwI1qx:-N5trtJI8v-MSIGF97J1:bmw41jn) ([raw file](https://github.com/harness/harness-core/blob/b160fefcc493a3bc39e2850d0078b18ec4e9b5a3/400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java#L523)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

yes, UI is not using these APIs since long, there is a lot of mess around these classes/methods.
</blockquote></details>

please verify once just in case this is used in some automation.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)* status: Some of the checks are too old.

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)* status: Some of the checks are too old.

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34734)* status: :shipit: complete! ✓

**Pull request merged**
