### PR TITLE
[feat]: [CDS-69836]: Integrating get api with default branch caching and REST endpoint for defaultBranchCacheDB

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
1. Have added for integrating get api with default branch caching. Have tested out the same for fetching remote pipelines and templates from the default branches with different git providers.
2. Exposed a rest end point for performing crud operations on the default cache db, have tested it out via curls

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49223)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/DefaultBranchCacheResponse.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyIHLK8FfktwlCdF04:-NXyIHLK8FfktwlCdF05:bq90kup) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/DefaultBranchCacheResponse.java#L25)):*
> ```Java
> @EqualsAndHashCode
> public class DefaultBranchCacheResponse {
>   String repo;
> ```

why do we need repo here?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/DefaultBranchCacheResponse.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyIHLK8FfktwlCdF04:-NXyKzcUCAfdXTYQGhiF:b-4yuf6b) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/DefaultBranchCacheResponse.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need repo here?
</blockquote></details>

its required when we fetch multiple records for a given account identifier

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/GitDefaultBranchCacheParamsRequestDTO.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyL5rB5pmqlTxI4F7M:-NXyL5rB5pmqlTxI4F7N:b-w7l33v) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/GitDefaultBranchCacheParamsRequestDTO.java#L20)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @OwnedBy(HarnessTeam.PIPELINE)
> ```

blank line

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/GitDefaultBranchCacheParamsRequestDTO.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyL5rB5pmqlTxI4F7M:-NXyi-5u9sBFlVNh1pmY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/dtos/GitDefaultBranchCacheParamsRequestDTO.java#L20)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyotkF-KN0nSEF-VRa:-NXyotkF-KN0nSEF-VRb:b-w7l33v) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java#L27)):*
> ```Java
>     return Date.from(Instant.ofEpochMilli(currentTime + maxCacheDuration));
>   }
>   public Date getValidUntilTimeInMinutes(long currentTime, long maxCacheDuration) {
> ```

blank line

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyov3sBfvZP2qObVjy:-NXyov3sBfvZP2qObVjz:b-r8i9z9) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java#L24)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class GitCacheUtils {
>   public Date getValidUntilTime(long currentTime, long maxCacheDuration) {
> ```

add units as well for reference

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXypUv1AxMfYTtvelyU:-NXypUv1AxMfYTtvelyV:b-v8z84f) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java#L28)):*
> ```Java
>   }
>   public Date getValidUntilTimeInMinutes(long currentTime, long maxCacheDuration) {
>     return Date.from(OffsetDateTime.now().plusMinutes(currentTime + maxCacheDuration).toInstant());
> ```

check logic

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 699 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyrHVtBHA2CbK-lWhR:-NXyrHVtBHA2CbK-lWhS:br4byys) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L699)):*
> ```Java
>   @Override
>   public String getDefaultBranch(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String connectorRef, String repoName) {
> ```

add argument for use-cache here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1207 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyt7ZgDd-lsId_rZgk:-NXyt7ZgDd-lsId_rZgl:bscm0xa) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1207)):*
> ```Java
>     GitDefaultBranchCacheKey gitDefaultBranchCacheKey =
>         buildGitDefaultBranchCacheKey(accountIdentifier, orgIdentifier, projectIdentifier, connectorRef, repoName);
>     log.info(String.format("Inserting defaultBranch [%s] in the cache for repoURL [%s] in the account [%s].",
> ```

logs should have some defined keyword such that if we want to see all logs for default branch cache, we are able to do so.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1218 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXytqgNCAcHQs3TZ2U9:-NXytqgNCAcHQs3TZ2UA:b-z258np) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1218)):*
> ```Java
>         buildGitDefaultBranchCacheKey(accountIdentifier, orgIdentifier, projectIdentifier, connectorRef, repoName);
>     GitDefaultBranchCacheResponse gitDefaultBranchCacheResponse =
>         gitDefaultBranchCacheService.fetchFromCache(gitDefaultBranchCacheKey);
> ```

what if this throws error

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1203 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyu1p01Q85z3zuIYhf:-NXyu1p01Q85z3zuIYhg:b12in93) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1203)):*
> ```Java
> 
>   @VisibleForTesting
>   protected void upsertDefaultBranch(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

lets move to some cache helper class

**Comment by adivishy1** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1218 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXytqgNCAcHQs3TZ2U9:-NXz390a0Z-yYcyz_sHF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1218)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this throws error
</blockquote></details>

Done.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49223)* status: Some of the checks are too old. 25 file(s) to review. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyov3sBfvZP2qObVjy:-NXyx2P66HvHLuFGMihh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add units as well for reference
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyotkF-KN0nSEF-VRa:-NXyx2mb2LjpDq7jzMea:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXypUv1AxMfYTtvelyU:-NXyxqft9TbBzrfClh4E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/utils/GitCacheUtils.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

check logic
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 264 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyqWfh8LkrDouveQwR:-NXyxrzn2a3ZFGNgwkm9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L264)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets not handle anything for V1. Handle it inside V2 only.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 699 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyrHVtBHA2CbK-lWhR:-NXz6tx13qALkUGEHhuB:b-b2yy44) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L699)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

add argument for use-cache here.
</blockquote></details>

added this to differentiate for get file v1 in which we arent using the default branch cache
in get file v2 and get batch file we are using the default branch cache
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1203 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyu1p01Q85z3zuIYhf:-NXz37BgB1ra63qPfuiz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1203)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets move to some cache helper class
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1207 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyt7ZgDd-lsId_rZgk:-NXzCq3h1lwVcMqjHzoa:b-xiwsm2) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1207)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

logs should have some defined keyword such that if we want to see all logs for default branch cache, we are able to do so.
</blockquote></details>

Added key word but not GitLogHelper as discussed, will create a ticket and take it later, this pr is getting bloated
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1209 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXysPKO0dtuysXYKQwo:-NXz38JX1oij8CVaEvL4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1209)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this upsert operation fails?
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 360 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNPjpw3bThPbZHmDFa:-NYNPjpx8E7vDx3RSpad:b5e6pt0) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L360)):*
> ```Java
>       return getFileResponseDTOOptional.get();
>     }
>     String branch = scmGetFileByBranchRequestDTO.getBranchName();
> ```

move it before checking for file in cache

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 409 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNQuG9Ev3DzfXYXhph:-NYNQuG9Ev3DzfXYXhpi:b5clxrf) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L409)):*
> ```Java
>               gitSyncConnectorHelper.getScmConnectorForGivenRepo(scmGetFileByBranchRequestDTO.getScope(),
>                   scmGetFileByBranchRequestDTO.getConnectorRef(), scmGetFileByBranchRequestDTO.getRepoName());
>           if (isEmpty(scmGetFileByBranchRequestDTO.getBranchName())) {
> ```

see if this can be made modular as its repetitive code

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 363 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNRip31xoZVHfBGA-8:-NYNRip31xoZVHfBGA-9:b-rwas7p) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L363)):*
> ```Java
>     if (isEmpty(branch)) {
>       scmGetFileByBranchRequestDTO.setBranchName(
>           getDefaultBranch(scope.getAccountIdentifier(), scope.getOrgIdentifier(), scope.getProjectIdentifier(),
> ```

we should just check in cache, and not call GIT here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 384 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNRtgA6gydSv_56tx7:-NYNRtgA6gydSv_56tx8:b98z6oh) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L384)):*
> ```Java
>         scmGetFileByBranchRequestDTO.getRepoName(), scmGetFileByBranchRequestDTO.getFilePath(),
>         scmGetFileByBranchRequestDTO.getBranchName(), scmGetFileByBranchRequestDTO.isGetOnlyFileContent());
> ```

we should set default branch cache here if applicable

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 699 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyrHVtBHA2CbK-lWhR:-NYNS3hB9iji_l-g32V5:bha6cd9) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L699)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

added this to differentiate for get file v1 in which we arent using the default branch cache
in get file v2 and get batch file we are using the default branch cache
</blockquote></details>

no changes required here as of now as its only used in get file v1 method

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49223)* status: 26 file(s) to review. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 699 at r2](https://reviewable.io/reviews/harness/harness-core/49223#-NXyrHVtBHA2CbK-lWhR:-NYOACHW0hM4Dhad52Kl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c66699d829e29d00a3351c9521c765a045ce7979/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L699)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

no changes required here as of now as its only used in get file v1 method
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 360 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNPjpw3bThPbZHmDFa:-NYOAFAe2vP2hvK60EAe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L360)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

move it before checking for file in cache
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 363 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNRip31xoZVHfBGA-8:-NYOAFu0Dmo0mI_FuBZ4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L363)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should just check in cache, and not call GIT here.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 384 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNRtgA6gydSv_56tx7:-NYOAHGl4mdr1AHJLGaS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L384)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should set default branch cache here if applicable
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 409 at r7](https://reviewable.io/reviews/harness/harness-core/49223#-NYNQuG9Ev3DzfXYXhph:-NYOAIkpAerGLEjRTod6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0b79a38bb371162708404804fdfa5a2a3ab4c676/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L409)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

see if this can be made modular as its repetitive code
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1192 at r11](https://reviewable.io/reviews/harness/harness-core/49223#-NYSD2IuAruEsy3Dwcpw:-NYSD2IuAruEsy3Dwcpx:b-7cn0qs) ([raw file](https://github.com/harness/harness-core/blob/8a927091023164773331a611ed1da59cdf725b4c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1192)):*
> ```Java
> 
>   @VisibleForTesting
>   protected void cacheDefaultBranchResponse(String accountIdentifier, ScmConnector scmConnector, String repoName,
> ```

can't this method itself move into helper?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1177 at r11](https://reviewable.io/reviews/harness/harness-core/49223#-NYSD8l_5z5Lj9_Bt_5D:-NYSD8l_5z5Lj9_Bt_5E:b-7cn0qs) ([raw file](https://github.com/harness/harness-core/blob/8a927091023164773331a611ed1da59cdf725b4c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1177)):*
> ```Java
> 
>   @VisibleForTesting
>   protected String setDefaultBranchIfInputBranchEmpty(
> ```

can't this method itself move into helper?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49223)* status: 28 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 360 at r11](https://reviewable.io/reviews/harness/harness-core/49223#-NYSB-ZHD5AGV-0QWZj6:-NYStMSf8hPO0DKCcmMV:b-ql0b8f) ([raw file](https://github.com/harness/harness-core/blob/8a927091023164773331a611ed1da59cdf725b4c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L360)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

cache is still relying on request branch. It should work on resolved branch name
</blockquote></details>

https://harness.atlassian.net/browse/CDS-72701
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1177 at r11](https://reviewable.io/reviews/harness/harness-core/49223#-NYSD8l_5z5Lj9_Bt_5D:-NYSlrqh124YYDpZZoAr:b-7mmp82) ([raw file](https://github.com/harness/harness-core/blob/8a927091023164773331a611ed1da59cdf725b4c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1177)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't this method itself move into helper?
</blockquote></details>

moved
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 1192 at r11](https://reviewable.io/reviews/harness/harness-core/49223#-NYSD2IuAruEsy3Dwcpw:-NYSlr7B0QdfVXeFjvj2:b-7mmp82) ([raw file](https://github.com/harness/harness-core/blob/8a927091023164773331a611ed1da59cdf725b4c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L1192)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't this method itself move into helper?
</blockquote></details>

moved

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 11 of 15 files at r2, 1 of 1 files at r3, 3 of 11 files at r4, 2 of 8 files at r5, 3 of 4 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49223)* status: 28 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Review by ankittiwari-harness — DISMISSED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r13, 1 of 1 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49223)* status: 26 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Pull request merged**
