### PR TITLE
[feat]: [PL-21798]: Installed OAS module for Platform service

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
…ication service

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30208)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208#-:-MuPX1YPCxY8u_9FPACv:bnfp4nl)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208)* status: 18 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208)* status: 13 file(s) to review.

**Review by rijajoo — APPROVED** [review]

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 6 of 18 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208#-:-MujtsKu6IcW5iqnU5XO:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by rijajoo — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208#-:-MujuFnY0RW92eIP95wM:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 12 of 13 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 6 of 18 files at r1, 12 of 13 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30208)* status: :shipit: complete! ✓

**Pull request merged**
