### PR TITLE
fix: [PL-31106]: added error handling for ldap user and group search

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
User search flow for LDAP fails with NPE when there are more than one users returned for a given baseDN and searchQuery. Rectified the error handling for this and a similar flow for group search as well.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43039)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapGroupsSearchRequest.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/43039#-NMbb_5H5b-_QcCnnTAh:-NMbb_5H5b-_QcCnnTAi:btt78c1) ([raw file](https://github.com/harness/harness-core/blob/7140c65c459af4fd67a2421a6cb1e5872f857d6c/930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapGroupsSearchRequest.java#L49)):*
> ```Java
>       log.error(defaultErrorMessage, le);
> 
>       if (isNull(le.getMessage())) {
> ```

nit: Just a better way to write the same code:
searchStatusMessage = le.Message;
if (searchStatusMessage == null) // or (isNull(searchStatusMessage)) {
    searchStatusMessage = defaultErrorMessage;
}

or even better:
searchStatusMessage = le.Message == null ? defaultErrorMessage : le.Message;

**Comment by piyush-harness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapUserExistsRequest.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/43039#-NMbdu35-eijL5Qj1Epc:-NMbdu35-eijL5Qj1Epd:b-u1ai8k) ([raw file](https://github.com/harness/harness-core/blob/7140c65c459af4fd67a2421a6cb1e5872f857d6c/930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapUserExistsRequest.java#L46)):*
> ```Java
>     } catch (LdapException le) {
>       String defaultErrorMessage = String.format(
>           "LdapException exception occurred when executing user exits request for baseDN = %s, searchFilter = %s",
> ```

user exists

**Comment by piyush-harness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapGroupsSearchRequest.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/43039#-NMbb_5H5b-_QcCnnTAh:-NMbef8LBIJX1aAjSpGv:b2c9z28) ([raw file](https://github.com/harness/harness-core/blob/7140c65c459af4fd67a2421a6cb1e5872f857d6c/930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapGroupsSearchRequest.java#L49)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

nit: Just a better way to write the same code:
searchStatusMessage = le.Message;
if (searchStatusMessage == null) // or (isNull(searchStatusMessage)) {
    searchStatusMessage = defaultErrorMessage;
}

or even better:
searchStatusMessage = le.Message == null ? defaultErrorMessage : le.Message;
</blockquote></details>

+1 for second

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43039)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapGroupsSearchRequest.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/43039#-NMbb_5H5b-_QcCnnTAh:-NMbhjWS-IZMdNHGvuEm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7140c65c459af4fd67a2421a6cb1e5872f857d6c/930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapGroupsSearchRequest.java#L49)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

+1 for second
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapUserExistsRequest.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/43039#-NMbdu35-eijL5Qj1Epc:-NMbhhrA5ebbntik9aSo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7140c65c459af4fd67a2421a6cb1e5872f857d6c/930-delegate-tasks/src/main/java/software/wings/service/impl/ldap/ExecuteLdapUserExistsRequest.java#L46)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

user exists
</blockquote></details>

Done.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43039)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43039)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43039)* status: :shipit: complete! ✓

**Pull request merged**
