### PR TITLE
[feat]: [CDS-46346]: remove strategy from default templates

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39932)

### CODE REVIEW

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39932#-:-NGW4LJ98CSlEAMlUpne:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Comment by vladimir-peric** [comment]
trigger ti0

**Comment by vladimir-peric** [comment]
trigger ti0

**Comment by vladimir-peric** [comment]
trigger ti0

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39932)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/v2/templates/DefaultInstallJarBash.yaml` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/39932#-NG_isZsBOsuLf488yo3:-NG_isZsBOsuLf488yo4:b-ew5guq) ([raw file](https://github.com/harness/harness-core/blob/a86151dc841763626c55bd7c6398ae6fb8fb96bb/125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/v2/templates/DefaultInstallJarBash.yaml#L19)):*
> ```YAML
>         items: <+stage.output.hosts>
>     spec:
>       host: <+repeat.item>
> ```

do we need to remove the host also?

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39932)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/v2/templates/DefaultInstallJarBash.yaml` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/39932#-NG_isZsBOsuLf488yo3:-NG_lvC0557ZoGTI7PoE:b-mfwy7d) ([raw file](https://github.com/harness/harness-core/blob/a86151dc841763626c55bd7c6398ae6fb8fb96bb/125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/v2/templates/DefaultInstallJarBash.yaml#L19)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

do we need to remove the host also?
</blockquote></details>

We tested it both with and without host and spotted no change in behaviour. My logic was that prior to introducing templates we didn't have it neither, that's why I removed it.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39932)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39932#-:-NGaCpDQCrWVtSuBybrD:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
