### PR TITLE
feat: [CDS-45930]: adding inputted variables to gql

### PR DESCRIPTION
**Pull request by lasdox**
## Describe your changes

Adding graphql support to fetch inputted variables on workflow executions.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39584)

### CODE REVIEW

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39584)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/graphql/datafetcher/VariableController.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/39584#-NFzVOYr1cZF6GS-BtO8:-NFzVOYr1cZF6GS-BtO9:b-i69qst) ([raw file](https://github.com/harness/harness-core/blob/9e08e8c10b25e0bc6ebc0d07856df4593e2f79f2/400-rest/src/main/java/software/wings/graphql/datafetcher/VariableController.java#L70)):*
> ```Java
>           .entrySet()
>           .stream()
>           .map(entry -> QLInputtedVariable.builder().name(entry.getKey()).value(entry.getValue()).build())
> ```

no null check needed?
___
*[`400-rest/src/main/java/software/wings/graphql/schema/type/QLWorkflowExecution.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/39584#-NFzVUHc2qIB_gGS9K1r:-NFzVUHc2qIB_gGS9K1s:b-kbh9kc) ([raw file](https://github.com/harness/harness-core/blob/9e08e8c10b25e0bc6ebc0d07856df4593e2f79f2/400-rest/src/main/java/software/wings/graphql/schema/type/QLWorkflowExecution.java#L49)):*
> ```Java
>   private String failureDetails;
>   private List<QLManifest> manifests;
>   private List<QLInputtedVariable> inputtedVariables;
> ```

inputVariables is a better name
___
*[`400-rest/src/main/resources/graphql/public/workflow.graphql` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/39584#-NFzVXqI42591iIkilL9:-NFzVXqI42591iIkilLA:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/9e08e8c10b25e0bc6ebc0d07856df4593e2f79f2/400-rest/src/main/resources/graphql/public/workflow.graphql#L39)):*
> ```GraphQL
> }
> 
> type InputtedVariable {
> ```

ditto

**Review by abhinav-harness — COMMENTED** [review]
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39584)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39584#-:-NG3-mbsASChVVh1m8S_:bnfp4nl)* status: :shipit: complete! ✓

**Comment by Fernando-Dourado** [comment]
trigger codeformat

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39584)* status: :shipit: complete! ✓

**Pull request merged**
