### PR TITLE
feat: [CDS-44084]: add clusters to dashboard

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)

### CODE REVIEW

**Comment by rohitk-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByArtifactList.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/38595#-NE1z2aT9lGQyAeuRuLj:-NE1z2aT9lGQyAeuRuLk:b-mphqud) ([raw file](https://github.com/harness/harness-core/blob/1e82a63dd4844b25a0a506df968aa728a2687e82/120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByArtifactList.java#L51)):*
> ```Java
>   @Value
>   @Builder
>   public static class InstanceGroupedByCluster {
> ```

Are the two objects exactly the same? Why are we creating a new one?

**Comment by GabeAboy** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByArtifactList.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/38595#-NE1z2aT9lGQyAeuRuLj:-NE2Npwl0t58Qh_nU0YF:bom4yyv) ([raw file](https://github.com/harness/harness-core/blob/1e82a63dd4844b25a0a506df968aa728a2687e82/120-ng-manager/src/main/java/io/harness/ng/overview/dto/InstanceGroupedByArtifactList.java#L51)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Are the two objects exactly the same? Why are we creating a new one?
</blockquote></details>

Done. This was left over from a previous iteration of the solution

**Comment by GabeAboy** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/38595#-NE2PBQ_8LbdcVJKuY15:-NE2PBQ_8LbdcVJKuY16:b52axaw) ([raw file](https://github.com/harness/harness-core/blob/1e82a63dd4844b25a0a506df968aa728a2687e82/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L227)):*
> ```Java
>                             .is(projectIdentifier)
>                             .and(InstanceKeys.serviceIdentifier)
>                             .is(serviceId)
> ```

Concerns here

**Comment by GabeAboy** [comment]
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/InstanceInfo.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/38595#-NE2Pl3DCavDqqjDZrVl:-NE2Pl3E3xga6JmwMH5w:b52axaw) ([raw file](https://github.com/harness/harness-core/blob/1e82a63dd4844b25a0a506df968aa728a2687e82/126-instance/src/main/java/io/harness/entities/instanceinfo/InstanceInfo.java#L18)):*
> ```Java
> @OwnedBy(HarnessTeam.DX)
> public abstract class InstanceInfo {
>   private String clusterIdentifier;
> ```

Concerns here



_Code quote (from 126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java):_
```Java
newAggregation(matchStage, groupClusterEnvId), Instance.class, ActiveServiceInstanceInfo.class);
```

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 9 of 11 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1797 at r4](https://reviewable.io/reviews/harness/harness-core/38595#-NE2bvOM-NXi1G2F9f6V:-NE2bvOM-NXi1G2F9f6W:bguo2z0) ([raw file](https://github.com/harness/harness-core/blob/ceecac843a3c11d16c7e0853fe144958a12e8c51/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1797)):*
> ```Java
>     Map<String, Map<String, List<InstanceGroupedByArtifactList.InstanceGroupedByInfrastructure>>> buildEnvInfraMap =
>         new HashMap<>();
>     new HashMap<>();
> ```

This seems unintentional. 
___
*[`126-instance/src/main/java/io/harness/entities/Instance.java` line 170 at r4](https://reviewable.io/reviews/harness/harness-core/38595#-NE2cnfX-JXakFCC_AfM:-NE2cnfX-JXakFCC_AfN:b-zetnx9) ([raw file](https://github.com/harness/harness-core/blob/ceecac843a3c11d16c7e0853fe144958a12e8c51/126-instance/src/main/java/io/harness/entities/Instance.java#L170)):*
> ```Java
>     public static final String instanceInfoNamespace = "instanceInfo.namespace";
>     public static final String instanceInfoClusterIdentifier = "instanceInfo.clusterIdentifier";
>     public static final String instanceInfoAgentIdentifier = "instanceInfo.agentIdentifier";
> ```

We should add an index for these two properties too. 
___
*[`126-instance/src/main/java/io/harness/entities/instanceinfo/InstanceInfo.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/38595#-NE2Pl3DCavDqqjDZrVl:-NE2h5kZDh3iFgJP4U5C:b-jgzwb3) ([raw file](https://github.com/harness/harness-core/blob/1e82a63dd4844b25a0a506df968aa728a2687e82/126-instance/src/main/java/io/harness/entities/instanceinfo/InstanceInfo.java#L18)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Concerns here
</blockquote></details>

This is already in the gitopsinstanceinfo so we shouldn't need to add this here. Also, this is a abstract class we do not want all the subclasses to have this field. 
___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/38595#-NE2PBQ_8LbdcVJKuY15:-NE2i2un64WOGxT7w_3m:b1o8snf) ([raw file](https://github.com/harness/harness-core/blob/1e82a63dd4844b25a0a506df968aa728a2687e82/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L227)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Concerns here
</blockquote></details>

Instead of modifying this and we can't create a new function then we can filter here instead of adding all. 



_Code quote (from 120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java):_
```Java
    List<ActiveServiceInstanceInfo> activeServiceInstanceGitOpsInfoList =
        instanceDashboardService.getActiveServiceGitOpsInstanceInfo(
            accountIdentifier, orgIdentifier, projectIdentifier, serviceId);
    activeServiceInstanceInfoList.addAll(activeServiceInstanceGitOpsInfoList);
```

**Review by rohitk-h — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/entities/GitOpsInstance.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/38595#-NE3ly0v5fVhrht6G22u:-NE3ly0v5fVhrht6G22v:bcyxto5) ([raw file](https://github.com/harness/harness-core/blob/e5b9bb71621835a210e817f00dea6119f325f1d0/126-instance/src/main/java/io/harness/entities/GitOpsInstance.java#L36)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @Document("instanceNG")
> @OwnedBy(HarnessTeam.DX)
> ```

This needs to be updated to gitops team

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: :shipit: complete! ✓

**Comment by GabeAboy** [comment]
trigger messagecheck

**Review by rohitk-h — APPROVED** [review]
> Reviewed 5 of 5 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1876 at r12](https://reviewable.io/reviews/harness/harness-core/38595#-NEDvHZSBe0mwk2mcDxF:-NEDvHZSBe0mwk2mcDxG:b-9q7lb4) ([raw file](https://github.com/harness/harness-core/blob/04d4f9576fb4518a590f75f808ff90c6acb1246d/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1876)):*
> ```Java
>             instanceList.stream().filter(e -> e.getInfraIdentifier() != null).collect(Collectors.toList());
>         List<InstanceGroupedByArtifactList.InstanceGroupedByInfrastructure> instanceGroupedByClusterList =
>             instanceList.stream().filter(e -> e.getClusterIdentifier() != null).collect(Collectors.toList());
> ```

Can we add some unit tests for this part? We can merge this PR.

**Comment by GabeAboy** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1876 at r12](https://reviewable.io/reviews/harness/harness-core/38595#-NEDvHZSBe0mwk2mcDxF:-NEHCoQzAS744KRBio3L:b-it0mbr) ([raw file](https://github.com/harness/harness-core/blob/04d4f9576fb4518a590f75f808ff90c6acb1246d/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1876)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Can we add some unit tests for this part? We can merge this PR. 
</blockquote></details>

addressing this in a fresh PR

**Review by GabeAboy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595)* status: 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java` line 1797 at r4](https://reviewable.io/reviews/harness/harness-core/38595#-NE2bvOM-NXi1G2F9f6V:-NE37mMJCQZrI-64HZBW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceecac843a3c11d16c7e0853fe144958a12e8c51/120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java#L1797)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

This seems unintentional. 
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/entities/Instance.java` line 170 at r4](https://reviewable.io/reviews/harness/harness-core/38595#-NE2cnfX-JXakFCC_AfM:-NE38Uz62UG-vorvAKc0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceecac843a3c11d16c7e0853fe144958a12e8c51/126-instance/src/main/java/io/harness/entities/Instance.java#L170)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

We should add an index for these two properties too. 
</blockquote></details>

Done.

**Review by GabeAboy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38595#-:-NEHCuVB6pjT-8kJmSKt:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
