### PR TITLE
fix: [DEL-4153]: delegate should do SSL cert verification

### PR DESCRIPTION
**Pull request by arpit3107**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34389)

### CODE REVIEW

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34389)* status: :shipit: complete! ✓

**Comment by arpit3107** [comment]
trigger ti0

**Comment by raghuAtWings** [comment]
*[`260-delegate/container/scripts/delegate.sh` line 140 at r2](https://reviewable.io/reviews/harness/harness-core/34389#-N513UAT9sl74bg-ZI5C:-N513UAT9sl74bg-ZI5D:b-n6u21s) ([raw file](https://github.com/harness/harness-core/blob/27f1bb93a125d32ca72279ea1b902c2c59f5c2c6/260-delegate/container/scripts/delegate.sh#L140)):*
> ```Shell
>   if [ ! -e delegate.jar ]; then
>     echo "Downloading Delegate $REMOTE_DELEGATE_VERSION ..."
>     curl $MANAGER_PROXY_CURL -#k $REMOTE_DELEGATE_URL -o delegate.jar
> ```

we can not remove -#, this change should be -#k -> -#

**Comment by raghuAtWings** [comment]
*[`260-delegate/container/scripts/delegate.sh` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/34389#-N513c0k2a9R1dWG8963:-N513c0k2a9R1dWG8964:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/27f1bb93a125d32ca72279ea1b902c2c59f5c2c6/260-delegate/container/scripts/delegate.sh#L148)):*
> ```Shell
>       mkdir -p backup.$DELEGATE_CURRENT_VERSION
>       cp delegate.jar backup.$DELEGATE_CURRENT_VERSION
>       curl $MANAGER_PROXY_CURL -#k $REMOTE_DELEGATE_URL -o delegate.jar
> ```

same here

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34389)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34389#-:-N597uA60-mz2iP_o2l-:bnfp4nl)* status: :shipit: complete! ✓

**Comment by arpit3107** [comment]
not needed

**Pull request closed without merging**
