### PR TITLE
[feat]: [PL-29652]: Fix the cycles in data and expression of 980-commons

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

While trying to break 980-commons exception module into a smaller Bazel target it gives raise to multiple cyclic dependencies among the sub-modules. These cycles need to be fixed before adding Bazel build files in all the modules.

This PR fixes the below 2 cycles of 980-commons:

[Cycle - 1]

.-> //980-commons/src/main/java/io/harness/expression/functors:module 
|   //980-commons/src/main/java/io/harness/expression:module 
`-- //980-commons/src/main/java/io/harness/expression/functors:module 

[Cycle - 2]

.-> //980-commons/src/main/java/io/harness/utils:module 
|   //980-commons/src/main/java/io/harness/exception:module 
|   //980-commons/src/main/java/io/harness/utils/constraintviolation:module 
|   //980-commons/src/main/java/io/harness/data/validator:module 
`-- //980-commons/src/main/java/io/harness/utils:module 

The changes are mainly refactoring of code such that it gets rid of the above 2 cycles.

The below test cases were validated in PR env -

1. End to End K8s workflow deployment.
2. Secret manager and secrets creations.
3. Fetch secret value using shell script. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39813)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39813)* status: 38 file(s) to review. 1 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39813)* status: :shipit: complete! ✓

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 3 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39813)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 35 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39813)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39813)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
