### PR TITLE
[feat]: [CDS-7234]: Improve CD connectors error handling

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
Improving user experience around connector errors by providing more information:

- K8s API requests logged in error explanations
- Some error message improvements

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30988)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30988)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesExceptionHints.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/30988#-Mwg6S0y9Uug-Qu81n8-:-Mwg6S0zA15DoXlAOAFL:bbc17hz) ([raw file](https://github.com/harness/harness-core/blob/5497e57f5875ead873627a27dbea1f0f7d5c2344/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesExceptionHints.java#L21)):*
> ```Java
> public class KubernetesExceptionHints {
>   public final String K8S_API_GENERIC_NETWORK_EXCEPTION =
>       "Verify network connection between Kubernetes cluster and Harness delegate. \nFor more info on how to log into delegates, refer:\nhttps://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/ \nhttps://docs.docker.com/engine/reference/commandline/exec/";
> ```

This actually is not always true. You can have ECS or Shell delegate that are not Kubernetes delegate
___
*[960-api-services/src/test/java/io/harness/k8s/apiclient/KubernetesApiCallTest.java, line 93 at r1](https://reviewable.io/reviews/harness/harness-core/30988#-Mwg7Fai59rIUsupLIj2:-Mwg7FalEHKPzxQgwaOU:b-x07u4w) ([raw file](https://github.com/harness/harness-core/blob/5497e57f5875ead873627a27dbea1f0f7d5c2344/960-api-services/src/test/java/io/harness/k8s/apiclient/KubernetesApiCallTest.java#L93)):*
> ```Java
>     try {
>       versionApiCall.get();
>       fail("Should not reach here.");
> ```

nit: you can use assertThatThrownBy

**Comment by abhinavsingh1196** [comment]
___
*[950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesExceptionHints.java, line 21 at r1](https://reviewable.io/reviews/harness/harness-core/30988#-Mwg6S0y9Uug-Qu81n8-:-Mwjcp5x3EN5iXbqz8GH:b2n0sdn) ([raw file](https://github.com/harness/harness-core/blob/5497e57f5875ead873627a27dbea1f0f7d5c2344/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/exception/KubernetesExceptionHints.java#L21)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This actually is not always true. You can have ECS or Shell delegate that are not Kubernetes delegate
</blockquote></details>

Changed to a more generic message, thanks.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30988)* status: :shipit: complete! ✓

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30988)* status: :shipit: complete! ✓

**Pull request merged**
