### PR TITLE
feat: [PL-27096]: changed restore logic

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/35809#-N83_qX35Bhym25sevb9:-N83_qX35Bhym25sevbA:b-jujtjx) ([raw file](https://github.com/harness/harness-core/blob/50f03593e2da5beaa740785a0c3041ed7cd93928/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L265)):*
> ```Java
>     Setting setting = settingRepository.upsert(settingsMapper.toSetting(accountIdentifier, newSettingDTO));
>     return settingsMapper.writeSettingResponseDTO(setting, settingConfiguration, true,
>         getSettingFromParentScope(Scope.of(accountIdentifier, orgIdentifier, projectIdentifier),
> ```

store in variable and pass in method
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/mapper/SettingsMapperTest.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/35809#-N83aURq2-_163hgR4Gu:-N83aURr-Lt6ZFUbGe9E:binbqt0) ([raw file](https://github.com/harness/harness-core/blob/50f03593e2da5beaa740785a0c3041ed7cd93928/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/mapper/SettingsMapperTest.java#L43)):*
> ```Java
> public class SettingsMapperTest extends CategoryTest {
>   @Spy private SettingsMapper settingsMapper;
>   private String dummyValue = "dummyValue";
> ```

use randomAlphabetic, rename to meaningful variable name

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/35809#-N83_qX35Bhym25sevb9:-N88ajBN12ZsUmB10fSt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50f03593e2da5beaa740785a0c3041ed7cd93928/120-ng-manager/modules/ng-settings/src/main/java/io/harness/ngsettings/services/impl/SettingsServiceImpl.java#L265)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

store in variable and pass in method
</blockquote></details>

Done.
___
*[`120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/mapper/SettingsMapperTest.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/35809#-N83aURq2-_163hgR4Gu:-N88ak0q8IMmdTtpEQR9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/50f03593e2da5beaa740785a0c3041ed7cd93928/120-ng-manager/modules/ng-settings/src/test/java/io/harness/ngsettings/mapper/SettingsMapperTest.java#L43)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

use randomAlphabetic, rename to meaningful variable name
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)* status: Some of the checks are too old. 5 file(s) to review.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)* status: Some of the checks are too old.

**Review by VikasMaddukuriHarness — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809#-:-N8OXm9DEfvYZnUSrWgr:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35809)* status: :shipit: complete! ✓

**Pull request merged**
