### PR TITLE
[feat]: [CDS-73618]:  fix Post retry manual intervention.

### PR DESCRIPTION
**Pull request by RajBaviskar**
## Describe your changes

- fix Post retry manual intervention.

https://github.com/harness/harness-core/assets/7086440/c43448f2-4999-4823-a919-7326047f6a94

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)

### CODE REVIEW

**Comment by RajBaviskar** [comment]
trigger messagecheck

**Comment by RajBaviskar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAAFlm22C3cIpUpXBJ:-NaAAFlm22C3cIpUpXBK:b-wfvr0m) ([raw file](https://github.com/harness/harness-core/blob/f0521742c6743cef94a375dfe0e065c091887330/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L109)):*
> ```Java
>             && retryConfig.getSpecConfig().getTimeout() != null) {
>           timeoutValue = retryConfig.getSpecConfig().getTimeout().getValue();
>         }
> ```

timeout value for MI is required, here if not given we are taking default value to 1d
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAATup582AF8hVtTgf:-NaAATup582AF8hVtTgg:b-b4gzxw) ([raw file](https://github.com/harness/harness-core/blob/f0521742c6743cef94a375dfe0e065c091887330/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L115)):*
> ```Java
>                     .setTimeout(Duration.newBuilder().setSeconds(TimeoutUtils.getTimeoutInSeconds(timeoutValue,
>                         Duration.newBuilder().setSeconds(java.time.Duration.ofDays(1).toMinutes() * 60).getSeconds())))
>                     .setFromStatus(toStatus)
> ```

Where is setRepairActionCode, when MI times out which action we are taking?

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAAFlm22C3cIpUpXBJ:-NaKuGZz0EsVPHDXfY2W:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/b7cac156b0f35e95a46b2414e69318dab29d688c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L109)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

timeout value for MI is required, here if not given we are taking default value to 1d
</blockquote></details>

yes
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAATup582AF8hVtTgf:-NaKuJ7h4w-RJnhskDg9:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/b7cac156b0f35e95a46b2414e69318dab29d688c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L115)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Where is setRepairActionCode, when MI times out which action we are taking?
</blockquote></details>

added

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAAFlm22C3cIpUpXBJ:-NaMth0799bFgPkUW1TB:b50js8j) ([raw file](https://github.com/harness/harness-core/blob/b7cac156b0f35e95a46b2414e69318dab29d688c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L109)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

yes
</blockquote></details>

@RajBaviskar i think we should log here to fail by sending fail advise if timeout is not set, as its required field. as per schema, so we shouldn't have any default value here
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/50935#-NaMu9V74sh9f6z7bxiG:-NaMu9V74sh9f6z7bxiH:b-e2p58v) ([raw file](https://github.com/harness/harness-core/blob/6b9801332af96bf8695fdf28526e423b9fcf22d1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L107)):*
> ```Java
> 
>         Timeout timeoutValue = Timeout.fromString("1d");
>         RepairActionCode actionAfterManualInterventionTimeout = RepairActionCode.END_EXECUTION; // Defaulting to ABORT
> ```

i dont think we should have any default action, toRepairAction throws exception if it doesn't match thus it will be the case only
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/50935#-NaMuh0f2_qGa_Cxs-uE:-NaMuh0f2_qGa_Cxs-uF:b1g6i9y) ([raw file](https://github.com/harness/harness-core/blob/6b9801332af96bf8695fdf28526e423b9fcf22d1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java#L104)):*
> ```Java
>     kryo.register(OnFailPipelineRollbackParameters.class, 878021);
>     kryo.register(NextStageAdviserParameters.class, 878022);
>     kryo.register(FailureStrategyActionConfig.class, 878023);
> ```

@ankittiwari-harness i think you got one kryo error due to this? do you remember?

**Review by prashantsharma04 — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935#-:-NaNK5Yw8Oy8IHsDqteo:bnfp4nl)* status: 1 change requests. 1 of 2 approvals obtained.

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAAFlm22C3cIpUpXBJ:-NaOZIeh48MNTMgtvAPn:b-1xjdcf) ([raw file](https://github.com/harness/harness-core/blob/b7cac156b0f35e95a46b2414e69318dab29d688c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L109)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@RajBaviskar i think we should log here to fail by sending fail advise if timeout is not set, as its required field. as per schema, so we shouldn't have any default value here
</blockquote></details>

Cool. I have removed defaults and added a log.error, Can you explain more about how can I send fail advise? 
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/50935#-NaMu9V74sh9f6z7bxiG:-NaOX7lT0xTCojPHOD_p:bs1e1n6) ([raw file](https://github.com/harness/harness-core/blob/6b9801332af96bf8695fdf28526e423b9fcf22d1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L107)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont think we should have any default action, toRepairAction throws exception if it doesn't match thus it will be the case only
</blockquote></details>

removed default.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/50935#-NaMuh0f2_qGa_Cxs-uE:-NaOZef7C__aTuok3JjO:b6pzr12) ([raw file](https://github.com/harness/harness-core/blob/6b9801332af96bf8695fdf28526e423b9fcf22d1/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@ankittiwari-harness i think you got one kryo error due to this? do you remember?
</blockquote></details>

Yes, I had to register ~7-8 classes.

**Comment by RajBaviskar** [comment]
trigger uts

**Comment by RajBaviskar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java` line 109 at r1](https://reviewable.io/reviews/harness/harness-core/50935#-NaAAFlm22C3cIpUpXBJ:-Naob-jA-01_EHgji9Ce:b-jd5pas) ([raw file](https://github.com/harness/harness-core/blob/b7cac156b0f35e95a46b2414e69318dab29d688c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserWithRollback.java#L109)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

Cool. I have removed defaults and added a log.error, Can you explain more about how can I send fail advise? 
</blockquote></details>

return adviserResponseBuilder
  
            .setInterventionWaitAdvise(
                InterventionWaitAdvise.newBuilder()
                    .setTimeout(Duration.newBuilder().setSeconds(TimeoutUtils.getTimeoutInSeconds(timeoutValue,
                        Duration.newBuilder().setSeconds(java.time.Duration.ofDays(1).toMinutes() * 60).getSeconds())))
                    .setFromStatus(toStatus)
                    .setRepairActionCode(actionAfterManualInterventionTimeout)
                    .build())
            .setType(AdviseType.INTERVENTION_WAIT)
            .build();


Like here you are sending InterventionWaitAdvise, then send fail advise like in - OnMarkFailureAdviser

**Comment by RajBaviskar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50935)* status: :shipit: complete! ✓

**Comment by RajBaviskar** [comment]
trigger review

**Review by Varsha-lalwani — APPROVED** [review]

**Review by AbhijithHarness — APPROVED** [review]

**Pull request merged**
