### PR TITLE
feat: [PIE-3832]: Plan Creation changes to support strategy

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33481)

### CODE REVIEW

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33481)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 16 of 20 files at r1, 3 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33481)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33481)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger ti2

**Comment by naidu-harness** [comment]
Unrelated Test Failure. Force Merging it

**Pull request merged**
