### PR TITLE
feat: [PL-22404]: Added support for SOEID in SAML/LDAP

### PR DESCRIPTION
**Pull request by ujjawal-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30771)

### CODE REVIEW

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java, line 169 at r1](https://reviewable.io/reviews/harness/harness-core/30771#-Mvwy6WC2c3O-vqrpCmP:-Mvwy6WD14tiiki1CpuF:buf3yz2) ([raw file](https://github.com/harness/harness-core/blob/ad9bc5cf2fa6346a26c34b45f5506031a7daa116/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L169)):*
> ```Java
>         }
>         log.info("Authenticating via SAML for user in account {}", account.getUuid());
>         samlSettings = ssoSettingService.getSamlSettingsByAccountId(accountId);
> ```

Do not change this?

**Review by ujjawal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30771)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java, line 169 at r1](https://reviewable.io/reviews/harness/harness-core/30771#-Mvwy6WC2c3O-vqrpCmP:-Mvx0R-FBrsqq7DM2Rny:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ad9bc5cf2fa6346a26c34b45f5506031a7daa116/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L169)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Do not change this?
</blockquote></details>

Done.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30771)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30771)* status: 1. unresolved discussions.

**Review by pbarapatre10 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30771)* status: 1. unresolved discussions.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30771)* status: 1 file(s) to review. 1. unresolved discussions.

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30771#-:-MvxkLDY73Rx89nvDrM-:bnfp4nl)* status: 2 file(s) to review. 1. unresolved discussions.

**Comment by piyush-harness** [comment]
:lgtm:

**Pull request merged**
