### PR TITLE
fix: [DEL-4840]: Send autoUpgrade from backend as enum

### PR DESCRIPTION
**Pull request by AnupamIO**
PR: https://del.pr.harness.io/del-4840/#/account/kmpySmUISimoRrJL6NL73w/delegates

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38136)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38136)

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38136)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 880 at r2](https://reviewable.io/reviews/harness/harness-core/38136#-NDDDoEV1dh_9bVO5cbB:-NDDDoEW1y2uZucNkFqm:b-oes598) ([raw file](https://github.com/harness/harness-core/blob/aea88dd0e93a15107a041c7ed3d978d57e89e034/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L880)):*
> ```Java
>   }
> 
>   private AutoUpgrade setAutoUpgrade(Long upgraderLastUpdated, List<Delegate> delegates) {
> ```

I think you should keep this logic in one place, possibly setupService for now (but ideally separate of the two) since this one injects setupService.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 882 at r2](https://reviewable.io/reviews/harness/harness-core/38136#-NDDEJECCCyhJ_YLZ6rS:-NDDEJECCCyhJ_YLZ6rT:b5egid2) ([raw file](https://github.com/harness/harness-core/blob/aea88dd0e93a15107a041c7ed3d978d57e89e034/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L882)):*
> ```Java
>   private AutoUpgrade setAutoUpgrade(Long upgraderLastUpdated, List<Delegate> delegates) {
>     final long delegateCreationTime = delegates.stream().mapToLong(Delegate::getCreatedAt).min().orElse(0);
>     if (TimeUnit.MILLISECONDS.toMinutes(System.currentTimeMillis() - upgraderLastUpdated)
> ```

Do you need to handle legacy delegates here as well?
___
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java` line 580 at r2](https://reviewable.io/reviews/harness/harness-core/38136#-NDCpawd2nmB6XkarrGs:-NDCpawd2nmB6XkarrGt:b-lbo1s1) ([raw file](https://github.com/harness/harness-core/blob/aea88dd0e93a15107a041c7ed3d978d57e89e034/400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java#L580)):*
> ```Java
>     Delegate delegateWithScalingGroup2 = createDelegateBuilder().build();
>     Calendar delegateCreatedCalendar2 = Calendar.getInstance();
>     delegateCreatedCalendar2.add(Calendar.MINUTE, -15);
> ```

cleanup



_Code quote:_
```Java
    Calendar delegateCreatedCalendar2 = Calendar.getInstance();
    delegateCreatedCalendar2.add(Calendar.MINUTE, -15);
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38136)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 880 at r2](https://reviewable.io/reviews/harness/harness-core/38136#-NDDDoEV1dh_9bVO5cbB:-NDKeqv0Ea78Yhf4DnQt:bf6vsjb) ([raw file](https://github.com/harness/harness-core/blob/aea88dd0e93a15107a041c7ed3d978d57e89e034/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L880)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think you should keep this logic in one place, possibly setupService for now (but ideally separate of the two) since this one injects setupService.
</blockquote></details>

added to setupService for now.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 882 at r2](https://reviewable.io/reviews/harness/harness-core/38136#-NDDEJECCCyhJ_YLZ6rS:-NDKeu-42uUFuXix_5W8:b-8b11j9) ([raw file](https://github.com/harness/harness-core/blob/aea88dd0e93a15107a041c7ed3d978d57e89e034/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L882)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Do you need to handle legacy delegates here as well?
</blockquote></details>

Added
___
*[`400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java` line 580 at r2](https://reviewable.io/reviews/harness/harness-core/38136#-NDCpawd2nmB6XkarrGs:-NDKevJ_8fmsfQoghte2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/aea88dd0e93a15107a041c7ed3d978d57e89e034/400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java#L580)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

cleanup
</blockquote></details>

Done

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38136)* status: :shipit: complete! ✓

**Pull request merged**
