### PR TITLE
feat: [CDS-46033]: fetch template for getBuilds when artifact source template used

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/39690#-NGGr7OJCp7j0F0QNisV:-NGGr7OJCp7j0F0QNisW:byhpd2c) ([raw file](https://github.com/harness/harness-core/blob/564bdc90b6e8894877bdea56c4d6e63373bc36b6/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L230)):*
> ```Java
> 
>     if (artifactSpecNode.getParentNode() != null
>         && artifactSpecNode.getParentNode().getFieldName().equals("template")) {
> ```

constants should be on the left side of the match
"template".equals..

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 235 at r1](https://reviewable.io/reviews/harness/harness-core/39690#-NGGyBwM02BR69qQWIMH:-NGGyBwN5vh3trorMrdb:bdelpy5) ([raw file](https://github.com/harness/harness-core/blob/564bdc90b6e8894877bdea56c4d6e63373bc36b6/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L235)):*
> ```Java
>       String versionLabel = templateNode.getField("versionLabel").getNode().getCurrJsonNode().asText();
> 
>       if (isNotEmpty(templateRef) && isNotEmpty(versionLabel)) {
> ```

is versionLabel mandatory ? Don't we use the stable version if not specified ?

**Review by inderschera — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 235 at r1](https://reviewable.io/reviews/harness/harness-core/39690#-NGGyBwM02BR69qQWIMH:-NGHg2XrB9-qgNK3Gs_z:b3n6n3a) ([raw file](https://github.com/harness/harness-core/blob/564bdc90b6e8894877bdea56c4d6e63373bc36b6/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L235)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is versionLabel mandatory ? Don't we use the stable version if not specified ?
</blockquote></details>

yes, versionLabel should not be mandatory.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 267 at r1](https://reviewable.io/reviews/harness/harness-core/39690#-NGHfK2r0irEMzeXXCrm:-NGHfK2r0irEMzeXXCrn:b4nfzr2) ([raw file](https://github.com/harness/harness-core/blob/564bdc90b6e8894877bdea56c4d6e63373bc36b6/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L267)):*
> ```Java
>   }
> 
>   public TemplateResponseDTO getScopedTemplateResponseDTO(
> ```

You can use io.harness.utils.IdentifierRefHelper#getIdentifierRef(java.lang.String, java.lang.String, java.lang.String, java.lang.String) and directly pass on parameters from the response instead of having separate if else conditions.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 267 at r1](https://reviewable.io/reviews/harness/harness-core/39690#-NGHfK2r0irEMzeXXCrm:-NGISmtm9Z8UuqDiryfW:b32v57) ([raw file](https://github.com/harness/harness-core/blob/564bdc90b6e8894877bdea56c4d6e63373bc36b6/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L267)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

You can use io.harness.utils.IdentifierRefHelper#getIdentifierRef(java.lang.String, java.lang.String, java.lang.String, java.lang.String) and directly pass on parameters from the response instead of having separate if else conditions.
</blockquote></details>

+1

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 230 at r1](https://reviewable.io/reviews/harness/harness-core/39690#-NGGr7OJCp7j0F0QNisV:-NGKqaBh8unf8cTY2ZUs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aad35c1fa5254cb94b1075eedf5bb63b07836f12/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L230)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

constants should be on the left side of the match
"template".equals..
</blockquote></details>

Done.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39690)* status: :shipit: complete! ✓

**Pull request merged**
