### PR TITLE
fix: [CDS-68866]: pass runtime input yaml as json node from pipeline stage plan creator

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Using jsonNode to process runtime input and pipeline yaml to support multi line strings as input in child pipeline.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 14 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 17 file(s) to review. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWpfRaY88xvSBGo-LVw:-NWpfRaZ3SJMq7hRoBLJ:b-iq8h57) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L56)):*
> ```Java
>   }
> 
>   public List<String> getinputSetPipelineCompYamlList(List<String> inputSetYamlList) {
> ```

Camel case follow this method
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWqsYBLDLHCXGShr4Gx:-NWqsYBLDLHCXGShr4Gy:b-53jg4w) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L56)):*
> ```Java
>   }
> 
>   public List<String> getinputSetPipelineCompYamlList(List<String> inputSetYamlList) {
> ```

This can return list of json node
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWqs_HU-VzVL_xcFZ8l:-NWqs_HU-VzVL_xcFZ8m:bruva07) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L83)):*
> ```Java
> 
>   public JsonNode mergeInputSetsForGivenStagesV2(
>       String template, List<String> inputSetYamlList, boolean appendInputSetValidator, List<String> stageIdentifiers) {
> ```

template can be of jsonNode
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 115 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWpfjT2BXeoZMSoD45x:-NWpfjT2BXeoZMSoD45y:braqvq0) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L115)):*
> ```Java
>   }
> 
>   public String mergeInputSetsV1(List<String> inputSetYamlList) {
> ```

add comments what is v1 and v2 different at all levels? 
method name can be withJson
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 130 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWpfqwm0ygkmE3vfXbS:-NWpfqwm0ygkmE3vfXbT:b-9dohx1) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L130)):*
> ```Java
>   }
> 
>   public JsonNode mergeInputSetsV2(List<String> inputSetYamlList) {
> ```

if both v1 and v2 return types are different, should we return an object which has string or json type 

New decide -> input should be list of jsonNode
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 76 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWqtMIT74WCf1cPZgX6:-NWqtMIT74WCf1cPZgX7:bewi4v8) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L76)):*
> ```Java
>       String originalYaml, String inputSetPipelineCompYaml, boolean appendInputSetValidator) {
>     YamlConfig mergedYamlConfig = mergeRuntimeInputValuesIntoOriginalYamlInternal(
>         originalYaml, inputSetPipelineCompYaml, appendInputSetValidator, false);
> ```

can it return directly jsonNode



_Code quote:_
```Java
    YamlConfig mergedYamlConfig = mergeRuntimeInputValuesIntoOriginalYamlInternal(
        originalYaml, inputSetPipelineCompYaml, appendInputSetValidator, false);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 275 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWqu7baBia6XFbuYWmw:-NWqu7baBia6XFbuYWmx:b-8zete1) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L275)):*
> ```Java
>   public JsonNode getMergedYamlFromInputSetReferencesAndRuntimeInputYamlV2(String accountId, String orgIdentifier,
>       String projectIdentifier, String pipelineIdentifier, List<String> inputSetReferences, String pipelineBranch,
>       String pipelineRepoID, List<String> stageIdentifiers, String lastYamlToMerge, boolean keepDefaultValues,
> ```

Can it be JsonNode

ex -> PMSPipelineTemplateHelper
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageStepParameters.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/48320#-NWquc122mUzwtd4U3sn:-NWquc122mUzwtd4U3so:bkmp2hf) ([raw file](https://github.com/harness/harness-core/blob/61412974a0ac63386dcdc623e7e76628be67f34c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/PipelineStageStepParameters.java#L39)):*
> ```Java
>   private String pipelineInputs;
>   String stageNodeId;
>   JsonNode pipelineInputsV2;
> ```

withJson

**Comment by shalini-agr** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 76 at r4](https://reviewable.io/reviews/harness/harness-core/48320#-NXOYTEt8q8kn5w6XYiW:-NXPB58JB9yaWtiMjW5i:b-r9gaia) ([raw file](https://github.com/harness/harness-core/blob/54eaa3229effa20e32fbe6f03c6e5613bccf158c/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L76)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont see corresponding old method?
</blockquote></details>

the original method is there below this one
it's input and output are both yamlConfig

**Comment by shalini-agr** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 207 at r4](https://reviewable.io/reviews/harness/harness-core/48320#-NXOf5-n1V04HR9a3b3R:-NXTtpjV8Kt_wIgkYg6J:bo90zsk) ([raw file](https://github.com/harness/harness-core/blob/54eaa3229effa20e32fbe6f03c6e5613bccf158c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L207)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this method with same name different than public method which we introduced?
</blockquote></details>

this private method is only for v0

**Review by archit-harness — COMMENTED** [review]
> Reviewed 3 of 5 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 31 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 52 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXU64q5-m3WufEa032Q:-NXU64q5-m3WufEa032R:b-phnhld) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L52)):*
> ```Java
>   }
> 
>   public List<JsonNode> getInputSetPipelineCompJsonNodeListWithJsonNode(List<JsonNode> inputSetJsonNodeList) {
> ```

private method and move this method down under public one



_Code quote:_
```Java
public
```
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 80 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXU8ODZB_m9uwBy4tD2:-NXU8ODZB_m9uwBy4tD3:bxevdjd) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L80)):*
> ```Java
>   }
> 
>   public JsonNode getMergedInputSetNodeWithJsonNode(List<JsonNode> inputSetJsonNodeList) {
> ```

private and move down this method
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/48320#-NXOYYAR-RAmdc95XABj:-NXUA7Cf3g5L1ZoR8dT8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/54eaa3229effa20e32fbe6f03c6e5613bccf158c/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L82)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets validate in intellij
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 280 at r4](https://reviewable.io/reviews/harness/harness-core/48320#-NXOeBvP8Qb9Y7DoM3UX:-NXUFHQDAV4vWrfGe_8S:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/54eaa3229effa20e32fbe6f03c6e5613bccf158c/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L280)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can this code be same as below?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 201 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXUDsyM8YIumfyVr36l:-NXUDsyM8YIumfyVr36m:bypa2sf) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L201)):*
> ```Java
>       Map<String, JsonNode> map = new HashMap<>();
>       map.put(YAMLFieldNameConstants.PIPELINE, inputJsonNode);
>       inputSetYaml = YamlPipelineUtils.writeYamlString(map);
> ```

use YamlUtils and create one common internal method which return map
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 215 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXUDQY86eHsm6lUImTT:-NXUDQY86eHsm6lUImTU:ba1y1zy) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L215)):*
> ```Java
>       Map<String, JsonNode> map = new HashMap<>();
>       map.put(YAMLFieldNameConstants.PIPELINE, inputJsonNode);
>       inputJsonNode = JsonUtils.asTree(map);
> ```

JsonPIpelineUtils 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/helper/PipelineStageHelperV1.java` line 81 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXUE0O72a8GrP_d8Vuo:-NXUE0O832CKOMzwr8L0:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/helper/PipelineStageHelperV1.java#L81)):*
> ```Java
>   }
> 
>   public JsonNode getInputSetJsonNode(YamlField pipelineInputs) {
> ```

same as above

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 37 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 120 at r4](https://reviewable.io/reviews/harness/harness-core/48320#-NXOVjjL5IhmIYKOJk44:-NXUOyI5EbKX8VTl1cuV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/54eaa3229effa20e32fbe6f03c6e5613bccf158c/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L120)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

needs discussion
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 52 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXU64q5-m3WufEa032Q:-NXUOjkh-35HILsqHhNA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

private method and move this method down under public one
</blockquote></details>

Done.
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java` line 80 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXU8ODZB_m9uwBy4tD2:-NXUOkky7HRwZ3H5R3En:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetMergeHelper.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

private and move down this method
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 201 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXUDsyM8YIumfyVr36l:-NXUPY04EozAubEUHoSx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L201)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use YamlUtils and create one common internal method which return map
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 215 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXUDQY86eHsm6lUImTT:-NXUPYUO2q73XxhOFgyS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L215)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

JsonPIpelineUtils 
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/helper/PipelineStageHelperV1.java` line 81 at r7](https://reviewable.io/reviews/harness/harness-core/48320#-NXUE0O72a8GrP_d8Vuo:-NXUPu3K8APIsowCgWVg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f09c9981c70c8a39cbcf00a45e26485fda329579/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/helper/PipelineStageHelperV1.java#L81)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 12 of 13 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 38 file(s) to review. 0 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 38 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r10, 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 41 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetTemplateHelper.java` line 96 at r11](https://reviewable.io/reviews/harness/harness-core/48320#-NXV96enA1n9uuxUtgJh:-NXV96eo4Hkg-zOkSklO:bx6qocj) ([raw file](https://github.com/harness/harness-core/blob/9c4c721d9ffa39370f42230214083f29632b7976/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetTemplateHelper.java#L96)):*
> ```Java
>     if (isEmpty(jsonNode)) {
>       return null;
>     }
> ```

move this check inside writeYamlString

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48320)* status: 41 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger review

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
