### PR TITLE
feat: [PL-28659]: Handling data deletion for churned accounts. 

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40622)

### CODE REVIEW

**Comment by praveensugavanam** [comment]
*[`270-verification/src/test/java/io/harness/service/LogMLAnalysisServiceTest.java` line 286 at r2](https://reviewable.io/reviews/harness/harness-core/40622#-NHzj1AsEGjvKs8S3FP6:-NHzj1AsEGjvKs8S3FP7:b-sist9y) ([raw file](https://github.com/harness/harness-core/blob/c0a2a2865bc71078cda227813225ca7191fa5548/270-verification/src/test/java/io/harness/service/LogMLAnalysisServiceTest.java#L286)):*
> ```Java
>   //    wingsPersistence.save(stateExecutionInstance);
>   //
>   //    List<LogElement> logElements = new ArrayList<>();
> ```

why has this been commented out ?

**Review by praveensugavanam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40622)* status: 10 file(s) to review. 0 of 2 approvals obtained. 

___
*[`270-verification/src/test/java/io/harness/service/LogMLAnalysisServiceTest.java` line 279 at r2](https://reviewable.io/reviews/harness/harness-core/40622#-NI-mMYODgxEg7pv01Q-:-NI-mMYR-5uY7B3CZdKg:b-7w4y2q) ([raw file](https://github.com/harness/harness-core/blob/c0a2a2865bc71078cda227813225ca7191fa5548/270-verification/src/test/java/io/harness/service/LogMLAnalysisServiceTest.java#L279)):*
> ```Java
>   //  @Category(UnitTests.class)
>   //  @RealMongo
>   //  public void saveLogDataValid() throws Exception {
> ```

Please change this to use @Ignore and remove the comments. And please create a ticket to SRM team, we will take a look and fix them

**Comment by praveensugavanam** [comment]
*[`270-verification/src/main/java/io/harness/service/LogAnalysisServiceImpl.java` line 1246 at r2](https://reviewable.io/reviews/harness/harness-core/40622#-NI-n8QgDDmnlX4xf-7z:-NI-n8QgDDmnlX4xf-8-:b-tnijji) ([raw file](https://github.com/harness/harness-core/blob/c0a2a2865bc71078cda227813225ca7191fa5548/270-verification/src/main/java/io/harness/service/LogAnalysisServiceImpl.java#L1246)):*
> ```Java
>   @Override
>   public void deleteByAccountId(String accountId) {
>     wingsPersistence.delete(wingsPersistence.createQuery(LogMLFeedbackRecord.class).filter(ACCOUNT_ID_KEY2, accountId));
> ```

why are we deleting just logmlfeedback records ? And not the other analysis records ?

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40622)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`270-verification/src/main/java/io/harness/service/LogAnalysisServiceImpl.java` line 1246 at r2](https://reviewable.io/reviews/harness/harness-core/40622#-NI-n8QgDDmnlX4xf-7z:-NI65Not8kqNhWzbmKfe:bko8dyf) ([raw file](https://github.com/harness/harness-core/blob/c0a2a2865bc71078cda227813225ca7191fa5548/270-verification/src/main/java/io/harness/service/LogAnalysisServiceImpl.java#L1246)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

why are we deleting just logmlfeedback records ? And not the other analysis records ? 
</blockquote></details>

@praveensugavanam we will create a followup ticket on cv team.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 3 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40622)* status: Some of the checks are too old. 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
