### PR TITLE
feat: [PL-31612]: Extend Dynamic Iterator Config support to new Redis Mode

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR extends the support for dynamic configuration of iterators to the new Redis Mode iterator framework. The Redis mode has 2 separate executor services - 1 for the main thread that does Mongo and Redis interaction to fetch the docs and the another for the worker thread pool that handles all the fetched Mongo docs. Thus, both these executor services need to be shut down or started when configured dynamically.

Tested in the local test setup for -
1. Dynamic enable and disable of Redis mode iterators.
2. Working of Redis mode iterators. 

Tested in Pre-QA env for -
1. Working of Redis mode iterators.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44077)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger messagecheck

**Review by gn-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44077)* status: Some of the checks are too old. 34 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/iterator/IteratorPumpAndRedisModeHandler.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/44077#-NOqCAP0038rW0pKfbr8:-NOqCAP0038rW0pKfbr9:bzhkakv) ([raw file](https://github.com/harness/harness-core/blob/a1654534b47eb9a20060cc8f4ad317497add1efe/960-persistence/src/main/java/io/harness/iterator/IteratorPumpAndRedisModeHandler.java#L49)):*
> ```Java
>     if (PersistenceIterator.ProcessMode.REDIS_BATCH.equals(iterator.getMode())) {
>       stopWorkerExecutor();
>     }
> ```

Can you please add description why worker executor need to be stopped 



_Code quote:_
```Java
    stopMainExecutor();
    if (PersistenceIterator.ProcessMode.REDIS_BATCH.equals(iterator.getMode())) {
      stopWorkerExecutor();
    }
```

**Review by gn-harness — APPROVED** [review]
> Reviewed 32 of 34 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44077)* status: 35 file(s) to review. 1 of 2 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 32 of 34 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44077)* status: :shipit: complete! ✓

**Pull request merged**
