### PR TITLE
[fix]: [CDS-40041]: refactor azure webApp infrastructure

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
[fix]: [CDS-40041]: refactor azure webApp infrastructure
Move web app name, deployment slot an d target slot from infrastructure to steps.

Is it new task type?    -   NO

Did you add a new class which is added in kryo serialization.   -   NO

Did you make changes to the code in a backward-compatible manner?   -   YES

will the new version of the delegate receive old version task and process?    -    YES

If new version of the manager receives response for the old task will it be able to handle it successfully?    -    YES

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager.  -   YES

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay.  -   YES

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay.   -    YES

Did you remove an enum → NO

Did you add an enum → NO

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

[CDS-40041]: https://harness.atlassian.net/browse/CDS-40041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)

### CODE REVIEW

**Comment by tmacari-harness** [comment]
trigger message_metadata

**Review by vlica-harness — DISMISSED** [review]

**Review by abosii-harness — APPROVED** [review]
> Reviewed 34 of 35 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)* status: :shipit: complete! ✓

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/AzureWebAppInfraDelegateConfig.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/35415#-N7HosNV3laJSDmpGbYY:-N7HosNV3laJSDmpGbYZ:b-bal9b8) ([raw file](https://github.com/harness/harness-core/blob/d19407bfb686514dd6543da38968bfb49b96a1b4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/AzureWebAppInfraDelegateConfig.java#L31)):*
> ```Java
>   private String resourceGroup;
>   private String deploymentSlot;
>   private String targetSlot;
> ```

the older delegates will get this field as null, what happens to those tasks then? have you tested it with older delegates?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/AzureWebAppInfraDelegateConfig.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/35415#-N7HosNV3laJSDmpGbYY:-N7HpJPdDL2p9YksVM0p:bv4wfze) ([raw file](https://github.com/harness/harness-core/blob/d19407bfb686514dd6543da38968bfb49b96a1b4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/AzureWebAppInfraDelegateConfig.java#L31)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

the older delegates will get this field as null, what happens to those tasks then? have you tested it with older delegates?
</blockquote></details>

we didn't release the feature yet, will be using older delegates.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/AzureWebAppInfraDelegateConfig.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/35415#-N7HosNV3laJSDmpGbYY:-N7K1mF1C1V6TzEVrAK7:b-ip239a) ([raw file](https://github.com/harness/harness-core/blob/d19407bfb686514dd6543da38968bfb49b96a1b4/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/AzureWebAppInfraDelegateConfig.java#L31)):*
> we didn't release the feature yet, will be using older delegates.
*nobody will be using older delegates

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 34 of 35 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)* status: :shipit: complete! ✓

**Comment by tmacari-harness** [comment]
trigger codebasehashcheck

**Comment by tmacari-harness** [comment]
trigger codebasehash

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35415)* status: :shipit: complete! ✓

**Review by vlica-harness — APPROVED** [review]

**Pull request merged**
