### PR TITLE
[feat]: [SMP-665]: validate SMP license using license library

### PR DESCRIPTION
**Pull request by kapilgarg1996**
This is the 2nd PR of the 3 PRs to support licensing in on-prem.

It provides a helper API to validate the generated SMP license. This can be used for ad-hoc verification of encrypted license

- expose smp license validate api through account resource
- add validation unit tests

## Checklist
- [X ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)

### CODE REVIEW

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 689 at r1](https://reviewable.io/reviews/harness/harness-core/38748#-NEktDL_17wwK9e6RIFV:-NEktDL_17wwK9e6RIFW:b-8x443o) ([raw file](https://github.com/harness/harness-core/blob/384b3e21379d80f6a36c75f0b2a2dc1b89fac8d8/400-rest/src/main/java/software/wings/resources/AccountResource.java#L689)):*
> ```Java
>       return RestResponse.Builder.aRestResponse()
>           .withResponseMessages(
>               Lists.newArrayList(ResponseMessage.builder().message("User not allowed to generate smp license").build()))
> ```

A typo here. It suppose to be "User not allowed to validate smp license"

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)* status: :shipit: complete! ✓

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)* status: :shipit: complete! ✓

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Review by gunascode — DISMISSED** [review]
> Reviewed 4 of 9 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)* status: :shipit: complete! ✓

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)* status: :shipit: complete! ✓

**Comment by kapilgarg1996** [comment]
trigger feature-build

**Review by arya-harness — APPROVED** [review]

**Review by arya-harness — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38748)* status: :shipit: complete! ✓

**Pull request merged**
