### PR TITLE
feat: [SCM-89]: Remove 'internal' flag for ModuleType CODE

### PR DESCRIPTION
**Pull request by johannesHarness**
## Describe your changes
As of now our `CODE` module is not injected into any projectDTO responses, which causes the `Select Project` box to always be empty on a full page load or refresh.

To add `CODE` as part of the responses, we have to disable the ignore flag for the `CODE` `ModuleType` enum value.

**NOTE**: To avoid issues in prod we first deployed it with the ignore flag enabled which was done 2 months ago:
https://github.com/harness/harness-core/pull/39020/files#diff-318be222a66868165831f68f88f672a7707cace953a057fc5bab3635b2aaf810

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43320)

### CODE REVIEW

**Comment by johannesHarness** [comment]
trigger feature-build

**Comment by johannesHarness** [comment]
trigger messagecheck

**Comment by johannesHarness** [comment]
PIPELINE BUILD:
https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/PipelineServiceUBIFeatureBuild/executions/qhh9ovcTTJW48k9jQhOGaQ/pipeline?storeType=INLINE

**Review by r0610205 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43320)* status: :shipit: complete! ✓

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43320)* status: :shipit: complete! ✓

**Pull request merged**
