### PR TITLE
feat: [CDS-39009]: Merge Step End to End

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes

- Implement Merge Step For Github PR request.
- Enhance error handling.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)

### CODE REVIEW

**Review by anshul-harness — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/34687#-N5NK1gS4EIZkVepI6L1:-N5NK1gT1uXHe7Xtokk-:bh57h2r) ([raw file](https://github.com/harness/harness-core/blob/59ec1d89cc46c7e09b6d196f652e65fb963087dd/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L145)):*
> ```Java
>       scope = "org.";
>     } else {
>       scope = "account.";
> ```

Did we find a better way of finding the scope?



_Code quote:_
```Java
    String scope = "";
    if (!isEmpty(connectorInfoDTO.getProjectIdentifier()) & !isEmpty(accountId)) {
      scope = "org.";
    } else {
      scope = "account.";
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 274 at r1](https://reviewable.io/reviews/harness/harness-core/34687#-N5NKIoO5Rjqpj-r0cVU:-N5NKIoO5Rjqpj-r0cVV:bdgkunw) ([raw file](https://github.com/harness/harness-core/blob/59ec1d89cc46c7e09b6d196f652e65fb963087dd/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L274)):*
> ```Java
>       case GITHUB:
>         GithubConnectorDTO githubConnectorDTO = (GithubConnectorDTO) scmConnector;
>         return "https://github.com"
> ```

Is this prefix right when someone has their own hosted github?



_Code quote:_
```Java
https://github.com
```

**Review by anshul-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/34687#-N5NK1gS4EIZkVepI6L1:-N5cyj6RBLxHxTousB2k:br4fw7q) ([raw file](https://github.com/harness/harness-core/blob/59ec1d89cc46c7e09b6d196f652e65fb963087dd/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java#L145)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Did we find a better way of finding the scope?
</blockquote></details>

found a way to fetch scope using `Identifierhelper` updated.

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 274 at r1](https://reviewable.io/reviews/harness/harness-core/34687#-N5NKIoO5Rjqpj-r0cVU:-N5cypnW0fxf3UkvU5iE:b-dgetnt) ([raw file](https://github.com/harness/harness-core/blob/59ec1d89cc46c7e09b6d196f652e65fb963087dd/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L274)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Is this prefix right when someone has their own hosted github?
</blockquote></details>

 Hosted github will require a different url to compute. I didn't find how this is handled in other places where we use gitconnectors. Will check and update in followup PR's

**Review by anshul-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 9 of 21 files at r1, 2 of 9 files at r2, 3 of 7 files at r3, 1 of 5 files at r4, 3 of 3 files at r6, 1 of 6 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34687)* status: :shipit: complete! ✓

**Pull request merged**
