### PR TITLE
[fix]: [PL-22260]: Fix to support vanity url in the webhook u…

### PR DESCRIPTION
**Pull request by DeepakPatankar**
…rl itself (#30665)"

This reverts commit 2f17ac55ad02ad86af3bb561379e3b719f4519e5.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30706)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger ti2

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30706#-:-MvcWCtLDU7rikhB62J1:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
rebase

**Review by bhavya181 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30706)* status: :shipit: complete! ✓

**Pull request merged**
