### PR TITLE
fix: [CDS-35523]: handling warning response of helm hist

### PR DESCRIPTION
**Pull request by namantalaycha10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31888)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 189 at r2](https://reviewable.io/reviews/harness/harness-core/31888#-MzQ7qeUAD10o5nvAVJ6:-MzQ7qeUAD10o5nvAVJ7:bgsydjc) ([raw file](https://github.com/harness/harness-core/blob/909f4cde8f23711046ca6d31ae2ecacbe266afde/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L189)):*
> ```Java
>     String errorMessagePrefix = "Failed in release history step. Executed command: ";
>     return fetchCliResponseWithExceptionHandling(
>         releaseHistory, commandType, errorMessagePrefix, null, DEFAULT_HELM_COMMAND_TIMEOUT);
> ```

should we do this change for NG, too?

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31888)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31888)* status: 1. unresolved discussions. 

___
*[960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java, line 189 at r2](https://reviewable.io/reviews/harness/harness-core/31888#-MzQ7qeUAD10o5nvAVJ6:-MzYVko92nngsi35Qh7a:bck7d4p) ([raw file](https://github.com/harness/harness-core/blob/909f4cde8f23711046ca6d31ae2ecacbe266afde/960-api-services/src/main/java/io/harness/helm/HelmClientImpl.java#L189)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

should we do this change for NG, too?
</blockquote></details>

@abhinavsingh1196 these changes are shared by NG as well

**Comment by namantalaycha10** [comment]
trigger ti0

**Pull request closed without merging**
