### PR TITLE
[feat]: [CDS-42313]: validate strategy for command step

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37515)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37515)

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37515)* status: :shipit: complete! ✓

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37515)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvX2HYAefXPZ_430_y:-NBvX2HYAefXPZ_430_z:b-id3alu) ([raw file](https://github.com/harness/harness-core/blob/974d81c3fd0f19899c38b465d13ab10443351a50/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java#L36)):*
> ```Java
>         StepSpecTypeConstants.CLOUDFORMATION_CREATE_STACK, StepSpecTypeConstants.CLOUDFORMATION_DELETE_STACK,
>         StepSpecTypeConstants.SERVERLESS_AWS_LAMBDA_DEPLOY, StepSpecTypeConstants.SERVERLESS_AWS_LAMBDA_ROLLBACK,
>         StepSpecTypeConstants.CLOUDFORMATION_ROLLBACK_STACK, StepSpecTypeConstants.COMMAND,
> ```

why it was removed?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvXMipCvr-Yc5zRc4a:-NBvXMipCvr-Yc5zRc4b:bwr2z4) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java#L37)):*
> ```Java
>                 && (strategy.getParallelism().getValue() != null
>                     || strategy.getParallelism().getExpressionValue() != null)))) {
>       throw new InvalidYamlException("Command step requires repeat strategy exclusively");
> ```

can you check on the message to be displayed with Suhas
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvXPpI8wwAO1EyGKIk:-NBvXPpI8wwAO1EyGKIl:bihosig) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java#L45)):*
> ```Java
>         && (((CommandStepNode) stepNode).getCommandStepInfo() == null
>             || isEmpty(((CommandStepNode) stepNode).getCommandStepInfo().getCommandUnits()))) {
>       throw new InvalidYamlException("Command step needs at least one command unit defined");
> ```

Pls check on the message to be displayed with Suhas
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvX7eO1VXY7HoTgqR2:-NBvX7eO1VXY7HoTgqR3:bl2m5kx) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L86)):*
> ```Java
> 
>   private boolean containsCommandStep(StepGroupElementConfig field) {
>     return field.getSteps().stream().anyMatch(i -> "Command".equalsIgnoreCase(i.getStep().get("type").asText()));
> ```

we should a constant for `Command`

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvX2HYAefXPZ_430_y:-NBvY-7SAVmORinWoN2U:buyw6fv) ([raw file](https://github.com/harness/harness-core/blob/974d81c3fd0f19899c38b465d13ab10443351a50/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDCreatorUtils.java#L36)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why it was removed?
</blockquote></details>

Command step is now validated with its own filter, CDPMSCommandStepFilterJsonCreator, instead of generic CDPMSStepFilterJsonCreatorV2. Each filter creator should have unique set of supported types, that's why Command was excluded.

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37515)* status: 4. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvXMipCvr-Yc5zRc4a:-NBvgFLA7UHELCj3o203:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java#L37)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

can you check on the message to be displayed with Suhas
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvXPpI8wwAO1EyGKIk:-NBvgEqOEpRw4ATUB47Y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/CDPMSCommandStepFilterJsonCreator.java#L45)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

Pls check on the message to be displayed with Suhas
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvX7eO1VXY7HoTgqR2:-NBvgDwyBKgvJUWxshxK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L86)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we should a constant for `Command`
</blockquote></details>

Done.

**Comment by vladimir-peric** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvX7eO1VXY7HoTgqR2:-NBvk9x0EoA6IT_YMTUJ:b3tr6dp) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L86)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

can you check `StepSpecTypeConstants.COMMAND` if that name change on step level we should be consistent.
</blockquote></details>

Yes, wanted to use that, but it is from higher level module. Let me see if this can be safely be targeted to clients module.

**Comment by vladimir-peric** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37515#-NBvX7eO1VXY7HoTgqR2:-NBvuYus-2alOR7EQCRh:bu19xl5) ([raw file](https://github.com/harness/harness-core/blob/a9f745eba0b183d2fec92508671762b40e4c5144/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters/StepGroupPmsFilterJsonCreator.java#L86)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

Yes, wanted to use that, but it is from higher level module. Let me see if this can be safely be targeted to clients module.
</blockquote></details>

I find it a bit difficult to move that class with constants to clients module. I'd rather keep it as is, though your point is in place.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37515)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37515)* status: :shipit: complete! ✓

**Pull request merged**
