### PR TITLE
[feat]: [CDS-68707]: Add utils to get stage and plan exec id based on execution mode

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47416)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47416)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47416)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
