### PR TITLE
[feat]:[PL-29002]: supporting secret creation flow to use addition metadata

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
supporting secret creation flow to use Secret Text class as it has addition metadata field.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)

### CODE REVIEW

**Comment by shreyas-harness** [comment]
trigger messagecheck

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjww4A4YvuKBrt7CDj:-NEjww4A4YvuKBrt7CDk:b-g9i0o2) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L164)):*
> ```Java
>     if (GCP_SECRETS_MANAGER.equals(secretManager.getEncryptionType())) {
>       validateEncryptedRecordForGcpSecretManagerEncryptionType(secret);
>     }
> ```

add and call validateAdditionalMetadata method. This method can have switch case based on encryption type passed.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjvbltA_He2qXdnqIe:-NEjvbluE533KdcQZd6g:b-780gko) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L186)):*
> ```Java
>     return encryptedDataDao.save(encryptedData);
>   }
>   @VisibleForTesting
> ```

Why is this annotation required?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 193 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjzEvY6abo--xD73is:-NEjzEvY6abo--xD73it:b-8ex0k9) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L193)):*
> ```Java
>           && secretTextSpecDTO.getAdditionalMetadata().getValues() != null) {
>         Map<String, Object> values = secretTextSpecDTO.getAdditionalMetadata().getValues();
>         if (values.size() == 0 || (values.size() == 1 && values.containsKey("regions"))) {
> ```

try reducing level of nested ifs
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 197 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjzNDsESz2OYG7aOLy:-NEjzNDsESz2OYG7aOLz:b-pr5zzx) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L197)):*
> ```Java
>         } else {
>           throw new InvalidRequestException(
>               String.format("Additional metadata values %s keys are invalid. ", values.keySet()));
> ```

What if some keys are valid but others are not? The message will be confusing
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjxFI_8lf1ME_VI54j:-NEjxFI_8lf1ME_VI54k:b-yppkfd) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L200)):*
> ```Java
>         }
>       }
>     }
> ```

validation for inline and reference can be two independent methods.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjzlDr3NVMwqMF1ya7:-NEjzlDr3NVMwqMF1ya8:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L209)):*
> ```Java
>       Map<String, Object> values = secretTextSpecDTO.getAdditionalMetadata().getValues();
>       if (values.size() != 1 || !values.containsKey("version")) {
>         throw new InvalidRequestException("Additional metadata values field should have only one field - version");
> ```

same here

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEk-WFZD5yUnUCbVQu3:-NEk-WFZD5yUnUCbVQu4:b-radc2m) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L145)):*
> ```Java
>         String version;
>         if (encryptedRecord.getAdditionalMetadata() != null
>             && encryptedRecord.getAdditionalMetadata().getValues() != null
> ```

replace with empty check.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 7 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEkZJY3A5S_Dzr2gwpT:-NEkZJY4512wmysR9rxI:bvg9uu4) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L205)):*
> ```Java
>       if (secretTextSpecDTO.getAdditionalMetadata() == null
>           || secretTextSpecDTO.getAdditionalMetadata().getValues() == null) {
>         throw new InvalidRequestException("Version information in additional metadata values field is missing. ");
> ```

Just confirming- version in case of GCP secret gets incremented whenever a secret value is updated, right? 
If so, does the customer have the option to specify the latest on UI(either using some tag like latest or maybe keep the version field blank)? 
If not, then in case no version info is sent in the referenced secret, should we not consider the latest version for the secret?
It might be a common use case when the customer when the customer just wants a secret to reference the present value of some other secret. So when the referenced secret is updated, the secret referencing it to should map to the updated value
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 154 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEkbLuY5A4tW2pqv3Dg:-NEkbLuY5A4tW2pqv3Dh:bjtoaia) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L154)):*
> ```Java
>           version = encryptedRecord.getPath();
>         }
>         if (secretName == null || isEmpty(secretName)) {
> ```

isEmpty() takes care of null check too

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 8 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 164 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjww4A4YvuKBrt7CDj:-NEl9g62C8hoiBDL7lZr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L164)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

add and call validateAdditionalMetadata method. This method can have switch case based on encryption type passed.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 186 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjvbltA_He2qXdnqIe:-NEl9gvv9YnsGsbqCYl3:b-exyx39) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L186)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why is this annotation required?
</blockquote></details>

Its to mark why the function was not private. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 193 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjzEvY6abo--xD73is:-NEl9o_5CoipWA8ff7mZ:bhrt2nr) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L193)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

try reducing level of nested ifs
</blockquote></details>

Done.
Had split the code into multiple functions. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 197 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjzNDsESz2OYG7aOLy:-NEl9tuT-HqT_kUsB5xU:b-ivgz2c) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L197)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What if some keys are valid but others are not? The message will be confusing
</blockquote></details>

Done. 
Updated the error message. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 200 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjxFI_8lf1ME_VI54j:-NEl9xKnEW9XEPRYvxx2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L200)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

validation for inline and reference can be two independent methods.
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEkZJY3A5S_Dzr2gwpT:-NEl9yGe7r35a7mfSfN4:b-5w5kzq) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L205)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Just confirming- version in case of GCP secret gets incremented whenever a secret value is updated, right? 
If so, does the customer have the option to specify the latest on UI(either using some tag like latest or maybe keep the version field blank)? 
If not, then in case no version info is sent in the referenced secret, should we not consider the latest version for the secret?
It might be a common use case when the customer when the customer just wants a secret to reference the present value of some other secret. So when the referenced secret is updated, the secret referencing it to should map to the updated value
</blockquote></details>

Yes, user can set version to be "latest". This will then pick latest from underlying Google Secret Manager. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 209 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEjzlDr3NVMwqMF1ya7:-NElAGQI5GZvXTXcpRck:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L209)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEk-WFZD5yUnUCbVQu3:-NElAHMDDEShGBBEaMZh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L145)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

replace with empty check.
</blockquote></details>

Done.
___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 154 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEkbLuY5A4tW2pqv3Dg:-NElAHvi93N27-d9oD1n:bs7wumx) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L154)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

isEmpty() takes care of null check too
</blockquote></details>

Done.

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 8 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java` line 145 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEk-WFZD5yUnUCbVQu3:-NElAX--829LskmMNvlM:b8ihrgr) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/890-sm-delegate/src/main/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java#L145)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Removed these extra checks as they are not needed. 
We already have the validation at time when encrypted record is created. So they are redundant.

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 8 file(s) to review. 2 change requests. 9. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 205 at r3](https://reviewable.io/reviews/harness/harness-core/38817#-NEkZJY3A5S_Dzr2gwpT:-NElRULL6KGzsEjkwfGT:bcg95t3) ([raw file](https://github.com/harness/harness-core/blob/ce1c221f028ce78976b9be96e585e4e2bccc6e51/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L205)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

Yes, user can set version to be "latest". This will then pick latest from underlying Google Secret Manager. 
</blockquote></details>

Also, user will always be expected to enter version info. Be it a version number to tie to a particular secret version. 
Or latest to always refer to the latest version of the secret in underlying google secret manager.

**Review by tiwaritejas — DISMISSED** [review]
> Reviewed 5 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 8 file(s) to review. 1 change requests. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtCIabC6QZYm3oZR_6:-NEtCIabC6QZYm3oZR_7:b-br2c9f) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L219)):*
> ```Java
>   private void validateInlineSecretAdditionalMetadataForGcpSecretManager(SecretTextSpecDTO secretTextSpecDTO) {
>     if (secretTextSpecDTO.getAdditionalMetadata() != null
>         && secretTextSpecDTO.getAdditionalMetadata().getValues() != null) {
> ```

replace with empty check for getValues
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtC9W2Bzn49iA-sQ4q:-NEtC9W2Bzn49iA-sQ4r:bjtsdkc) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L221)):*
> ```Java
>         && secretTextSpecDTO.getAdditionalMetadata().getValues() != null) {
>       Map<String, Object> values = secretTextSpecDTO.getAdditionalMetadata().getValues();
>       if (!values.isEmpty() && (values.size() != 1 || !values.containsKey("regions"))) {
> ```

Use constant for regions. Can multiple regions be selected? If not the rename to region.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtCoEeCeQm9IHnW6sC:-NEtCoEeCeQm9IHnW6sD:b5sq47m) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L223)):*
> ```Java
>       if (!values.isEmpty() && (values.size() != 1 || !values.containsKey("regions"))) {
>         throw new InvalidRequestException("Additional metadata values expect only one key - regions");
>       }
> ```

Also check that region value is non empty

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtCIabC6QZYm3oZR_6:-NEtIc746aVkCBcFConx:b-xv5znt) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L219)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

replace with empty check for getValues
</blockquote></details>

We can have empty map - where user is not giving region information. 
Region information is optional. Not passing info means automatically replicated supported by google secret manager. 
Hence empty map is possible. So not using empty check for this map. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtC9W2Bzn49iA-sQ4q:-NEtIqp64T-k5PvgmR9S:b-hk9l48) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L221)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use constant for regions. Can multiple regions be selected? If not the rename to region.
</blockquote></details>

Done. Moved to constant regions variable. 
Yes, there can be multiple regions, so sticking with regions. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtCoEeCeQm9IHnW6sC:-NEtIzy577Z4oEsAPO2d:b-cyxbbo) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L223)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Also check that region value is non empty
</blockquote></details>

It can be empty. So not doing empty validation here. Empty means use Automatically Replicated option of google secret manager.

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38817)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtCIabC6QZYm3oZR_6:-NEtdd_IBZBD4jB_fhok:b-2732ec) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L219)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

We can have empty map - where user is not giving region information. 
Region information is optional. Not passing info means automatically replicated supported by google secret manager. 
Hence empty map is possible. So not using empty check for this map. 
</blockquote></details>

Discussed offline. Added isEmpty check
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/38817#-NEtCoEeCeQm9IHnW6sC:-NEtdhhP2y0cdhifi9g9:bytta4v) ([raw file](https://github.com/harness/harness-core/blob/0a1c4ee82d9f5970a2a3cbead0e9a4de30d580aa/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L223)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

It can be empty. So not doing empty validation here. Empty means use Automatically Replicated option of google secret manager. 
</blockquote></details>

Discussed offline. Added extra check.

**Pull request closed without merging**
