### PR TITLE
feat: [CDS-52322]: Added API for service instances usage by dates

### PR DESCRIPTION
**Pull request by ivan-83**
Added API for getting service instance usage by dates.

In order to get the report java code will consume a function that will be installed on TimesaveDB when the NG manager starts. 

A modification migration framework is needed to add support for the execution of the whole script not line by line because we need to execute the entire file where the function is placed at once to install the function on TimescaleDB.  

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44074)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by harness-david — APPROVED** [review]
Processing each day separately is the only option that works as expected so far and it seems to perform well.  So we'll go with this for now.

**Review by neelam-harness — CHANGES_REQUESTED** [review]

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44074)* status: 18 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/GetServiceInstancesByDateFunction.java` line 17 at r3](https://reviewable.io/reviews/harness/harness-core/44074#-NOVViU-sPz9ZB94W2SW-r3-17:-NOqLHGrEYC3q0f2LI9p:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/32e0aaa69343ca25b0ef24cfc2573df6acf2e15b/120-ng-manager/src/main/java/io/harness/ng/core/migration/timescale/GetServiceInstancesByDateFunction.java#L17)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: Let's make the file name string as a constant ?
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/resources/timescale/get_service_instances_by_date_function_timescale.sql` line 1 at r3](https://reviewable.io/reviews/harness/harness-core/44074#-NOVViU-sPz9ZB94W2SY-r3-1:-NOqLKty6kipJL8GmMjf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/32e0aaa69343ca25b0ef24cfc2573df6acf2e15b/120-ng-manager/src/main/resources/timescale/get_service_instances_by_date_function_timescale.sql#L1)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: rename `2022` to `2023`
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/resources/timescale/get_service_instances_by_date_function_timescale.sql` line 6 at r3](https://reviewable.io/reviews/harness/harness-core/44074#-NOVViU-sPz9ZB94W2SY-r3-6:-NOqLLtu9JRzGy0CQDqp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/32e0aaa69343ca25b0ef24cfc2573df6acf2e15b/120-ng-manager/src/main/resources/timescale/get_service_instances_by_date_function_timescale.sql#L6)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: remove the commented code.
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java` line 334 at r3](https://reviewable.io/reviews/harness/harness-core/44074#-NOVViU-sPz9ZB94W2SZ-r3-334:-NOqLNPb5FtjJnoPn7AT:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/32e0aaa69343ca25b0ef24cfc2573df6acf2e15b/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java#L334)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

nit: let's add java doc for this public method ? and also rename the parameter to instancesUsageFetchData for more readability ?
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageResource.java` line 130 at r3](https://reviewable.io/reviews/harness/harness-core/44074#-NOVViU-sPz9ZB94W2S_-r3-130:-NOqLPBPA4SmiVPtnbUX:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/32e0aaa69343ca25b0ef24cfc2573df6acf2e15b/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageResource.java#L130)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

I think we can make use of `Hidden` annotation to make this internal. Please check.
Eg: https://github.com/harness/harness-core/blob/9836e1757e280dd4943e1816a8655f40e098bf2a/930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/LicenseResource.java#L83 
</blockquote></details>

Done

**Review by neelam-harness — DISMISSED** [review]
:lgtm:

> Reviewed 10 of 18 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44074#-:-NOqNfQ87sFjrMgYj1rN:bnfp4nl)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 9 of 18 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44074)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by ivan-83** [comment]
trigger tiAll

**Review by harness-david — APPROVED** [review]
Changes did not affect Postgres code.

**Comment by ivan-83** [comment]
trigger ti2

**Comment by ivan-83** [comment]
trigger ut2

**Comment by ivan-83** [comment]
trigger ut2

**Review by neelam-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44074)* status: 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44074#-:-NOuUUf1ABw6eFCfzGne:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
