### PR TITLE
[feat]: [CDS-53926]: ASG Instance sync - logcallback null issue fixed

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
ASG Instance sync - logcallback in asgtaskhelper was null which resulted in NPE.  Fixed that. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 461 at r2](https://reviewable.io/reviews/harness/harness-core/44216#-NOwrGGC-7FRQToGRutx:-NOwrGGC-7FRQToGRuty:b-gucsax) ([raw file](https://github.com/harness/harness-core/blob/b0f766673764b927cc1e52d72a5126d581ed92e0/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L461)):*
> ```Java
>   // using this method as getASG method above fails when used in AsgTaskHelper.java because logcallback is null in that
>   // case
>   public AutoScalingGroup getASGWithoutLogs(String asgName) {
> ```

io.harness.aws.asg.AsgSdkManager
Can we update info/warn methods here to null check logcallback? 
if logcallback is null, we can log.info(). getAsgWithoutLogs might be confusing.



_Code quote (from 930-delegate-tasks/src/main/java/io/harness/delegate/task/aws/asg/AsgTaskHelper.java):_
```Java
asgSdkManager.getASG
```

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java` line 461 at r2](https://reviewable.io/reviews/harness/harness-core/44216#-NOwrGGC-7FRQToGRutx:-NOwrUWs0VbZiE3qbs0c:b-try6x5) ([raw file](https://github.com/harness/harness-core/blob/b0f766673764b927cc1e52d72a5126d581ed92e0/960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java#L461)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

io.harness.aws.asg.AsgSdkManager
Can we update info/warn methods here to null check logcallback? 
if logcallback is null, we can log.info(). getAsgWithoutLogs might be confusing.
</blockquote></details>

This will also solve duplicate code + if someone calls such method then we'll not encounter NPE

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger checkstylecodeformat

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
trigger checkstylecodeformat

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
trigger ut0

**Review by vitsafronovici — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 6 of 17 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)* status: :shipit: complete! ✓

**Review by lovish1999 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 6 of 17 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 6 of 17 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44216)* status: :shipit: complete! ✓

**Pull request merged**
