### PR TITLE
feat: [CDS-35389]: File Store: Investigate and implement API endpoint…

### PR DESCRIPTION
**Pull request by bojanmicovic**
… for updating files

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31989)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31989#-:-MzufExV8OElK77IAAhx:bnfp4nl)* status: :shipit: complete! ✓

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 82 at r1](https://reviewable.io/reviews/harness/harness-core/31989#-MzuePAI2ejvRBaFxCoM:-MzuerbfAOpmHnCzuu-z:b35r9q4) ([raw file](https://github.com/harness/harness-core/blob/f5f91f14c905174957a8b7af783b1b59ac2de205/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L82)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Here if fileDto.isFile() then save file in file service. In the case of folders just saving in NGFile collection. 
</blockquote></details>

We could add one logging line like "Start updating file in file system" and supply file identifier and file name to the logging message.

**Review by ivan-83 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31989#-:-MzyOfaIEYv_1hFB5Asl:bnfp4nl)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 82 at r1](https://reviewable.io/reviews/harness/harness-core/31989#-MzuePAI2ejvRBaFxCoM:-Mzyfns0B1EPIzwJ49uZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f5f91f14c905174957a8b7af783b1b59ac2de205/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L82)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We could add one logging line like "Start updating file in file system" and supply file identifier and file name to the logging message. 
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31989#-:-N-2Sz1G5_M3KRkFc7HL:bnfp4nl)* status: :shipit: complete! ✓

___
*[120-ng-manager/src/main/java/io/harness/ng/core/mapper/FileDTOMapper.java, line 48 at r5](https://reviewable.io/reviews/harness/harness-core/31989#-N-2SLD_EZ3FQfV6gKEZ:-N-2SLD_EZ3FQfV6gKE_:b3dk89b) ([raw file](https://github.com/harness/harness-core/blob/db56b64685152ee354a9b87496d474967268b720/120-ng-manager/src/main/java/io/harness/ng/core/mapper/FileDTOMapper.java#L48)):*
> ```Java
>     file.setEntityId(fileDto.getEntityId());
>     file.setEntityType(fileDto.getEntityType());
>     file.setFileName(fileDto.getName());
> ```

Add and mime type from DTO and maybe the method name could be updateNGFileForSavingToDB or only updateNGFile.

**Pull request merged**
