### PR TITLE
[fix]: [PL-39780]: Improves log by adding entity identifier and scope

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51312)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51312)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/51312#-NauOR8Y5MvByn_TV1mj:-NauOR8Y5MvByn_TV1mk:bdshoot) ([raw file](https://github.com/harness/harness-core/blob/638362ac8ec44c8842d336a4edb006c0877c6d10/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java#L120)):*
> ```Java
>       log.info(
>           "UserGroupChangeConsumer.consumeUpdateEvent: Number of ACLs created: {} for identifier: {}, name: {}, scope: {} Time taken: {}",
>           numberOfACLsCreated, userGroup.getIdentifier(), userGroup.getName(), userGroup.getScopeIdentifier(),
> ```

I don't think we need to print name.
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/51312#-NauOWew1MBLQWFNmKGh:-NauOWew1MBLQWFNmKGi:bdshoot) ([raw file](https://github.com/harness/harness-core/blob/638362ac8ec44c8842d336a4edb006c0877c6d10/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java#L126)):*
> ```Java
>           numberOfACLsDeleted, userGroup.getIdentifier(), userGroup.getName(), userGroup.getScopeIdentifier(),
>           aclProcessingTime);
>     }
> ```

I don't think we need to print name.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java` line 120 at r1](https://reviewable.io/reviews/harness/harness-core/51312#-NauOR8Y5MvByn_TV1mj:-NauUC12-Cnl596LsohE:b2aowva) ([raw file](https://github.com/harness/harness-core/blob/638362ac8ec44c8842d336a4edb006c0877c6d10/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java#L120)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I don't think we need to print name.
</blockquote></details>

We do not have mongo id here

**Comment by ashishsanodia-harness** [comment]
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/51312#-NauOWew1MBLQWFNmKGh:-NauUFmP8iGewxKQPW59:b2aowva) ([raw file](https://github.com/harness/harness-core/blob/638362ac8ec44c8842d336a4edb006c0877c6d10/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/UserGroupChangeConsumer.java#L126)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I don't think we need to print name.
</blockquote></details>

We do not have mongo id here

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51312)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51312)* status: :shipit: complete! ✓

**Comment by ashishsanodia-harness** [comment]
trigger ut0, ut1, ut2, ut3, ut4

**Comment by ashishsanodia-harness** [comment]
trigger ut4

**Pull request merged**
