### PR TITLE
feat: [PL-29890]: removed unnecessary calls to laodSupportAccounts

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
removed unnecessary calls to loadSupportAccounts, in first pr the methods that require supportAccounts have been identified and they are changed to call  loadSupportAccounts explicitly.
In this pr, the default behaviour of all methods has been changed to not load supportAccounts and the methods that will require support accounts will call explicitly by setting field `true`

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/intfc/UserService.java` line 665 at r3](https://reviewable.io/reviews/harness/harness-core/40431#-NJ5-WXL0iME8G_0oTpD:-NJ5-WXL0iME8G_0oTpE:b-fxf3g8) ([raw file](https://github.com/harness/harness-core/blob/232d41be229f2e0c11e9ee0175f3091fd1bfa0b1/400-rest/src/main/java/software/wings/service/intfc/UserService.java#L665)):*
> ```Java
>   boolean ifUserHasAccessToSupportAccount(String userId, String accountId);
> 
>   boolean isRemoveLoadSupportAccountsFFDisabled();
> ```

boolean isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled()
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 526 at r3](https://reviewable.io/reviews/harness/harness-core/40431#-NJ4zUxh7emtSlS7Hr2y:-NJ4zUxh7emtSlS7Hr2z:ba16zwh) ([raw file](https://github.com/harness/harness-core/blob/232d41be229f2e0c11e9ee0175f3091fd1bfa0b1/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L526)):*
> ```Java
>   PL_SUPPORT_JWT_TOKEN_SCIM_API("Enable support for external OAuth JWT token for SCIM API calls", HarnessTeam.PL),
>   CCM_INSTANCE_DATA_CLUSTERID_FILTER("Query from instanceData collection based on clusterId", HarnessTeam.CE),
>   REMOVE_USAGE_OF_LOAD_SUPPORT_ACCOUNTS(
> ```

DO_NOT_LOAD_SUPPORT_ACCOUNTS_UNLESS_REQUIRED
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 527 at r3](https://reviewable.io/reviews/harness/harness-core/40431#-NJ4ztKB5Hq5QhZsNZoL:-NJ4ztKB5Hq5QhZsNZoM:bhotxah) ([raw file](https://github.com/harness/harness-core/blob/232d41be229f2e0c11e9ee0175f3091fd1bfa0b1/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L527)):*
> ```Java
>   CCM_INSTANCE_DATA_CLUSTERID_FILTER("Query from instanceData collection based on clusterId", HarnessTeam.CE),
>   REMOVE_USAGE_OF_LOAD_SUPPORT_ACCOUNTS(
>       "Enable to remove unnecessary loading of support accounts to reduce memory load", HarnessTeam.PL);
> ```

Avoid loading unnecessary support accounts unnecessarily. Enabling it will reduce memory pressure

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431#-:-NJFhCInChCnWTt9j3fU:bnfp4nl)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/intfc/UserService.java` line 665 at r3](https://reviewable.io/reviews/harness/harness-core/40431#-NJ5-WXL0iME8G_0oTpD:-NJJpbm7Cf2BU9LnQI8Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/232d41be229f2e0c11e9ee0175f3091fd1bfa0b1/400-rest/src/main/java/software/wings/service/intfc/UserService.java#L665)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

boolean isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled()
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 526 at r3](https://reviewable.io/reviews/harness/harness-core/40431#-NJ4zUxh7emtSlS7Hr2y:-NJJpcH9AyD6XyoytWT9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/232d41be229f2e0c11e9ee0175f3091fd1bfa0b1/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L526)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

DO_NOT_LOAD_SUPPORT_ACCOUNTS_UNLESS_REQUIRED
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 527 at r3](https://reviewable.io/reviews/harness/harness-core/40431#-NJ4ztKB5Hq5QhZsNZoL:-NJJpcc0BA88_8HbsM4U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/232d41be229f2e0c11e9ee0175f3091fd1bfa0b1/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L527)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Avoid loading unnecessary support accounts unnecessarily. Enabling it will reduce memory pressure
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r3, 1 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 196 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWGmK5XvOylScqY6I:-NJKWGmK5XvOylScqY6J:b-s4i5ak) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/resources/AccountResource.java#L196)):*
> ```Java
>     if (userService.isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled()) {
>       return new RestResponse<>(
>           accountService.getServices(accountId, UserThreadLocal.get().getPublicUser(true), request, serviceId));
> ```

Shouldn't this be false?
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 199 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWIriELUD0C_c95g9:-NJKWIriELUD0C_c95gA:b9etrn9) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/resources/AccountResource.java#L199)):*
> ```Java
>     }
>     return new RestResponse<>(
>         accountService.getServices(accountId, UserThreadLocal.get().getPublicUser(false), request, serviceId));
> ```

Shouldn't this be true?

Please check at other places in this PR
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3188 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWrx21jGnpIWhkIDM:-NJKWrx21jGnpIWhkIDN:b2r1str) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3188)):*
> ```Java
>     }
> 
>     if (isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled()) {
> ```

It should be !isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled()

Please check at other places in code
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 4112 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWfQh3wqT9g77dbK7:-NJKWfQh3wqT9g77dbK8:bn1pzy0) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4112)):*
> ```Java
>   @Override
>   public boolean isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled() {
>     return !featureFlagService.isEnabledForAllAccounts(FeatureName.DO_NOT_LOAD_SUPPORT_ACCOUNTS_UNLESS_REQUIRED);
> ```

Shouldn't this be 



_Code snippet:_
```Java
featureFlagService.isEnabledForAllAccounts(FeatureName.DO_NOT_LOAD_SUPPORT_ACCOUNTS_UNLESS_REQUIRED);
```

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: 9 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 196 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWGmK5XvOylScqY6I:-NJKYk2WDvjcaQJ-OZQR:b-kec4hy) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/resources/AccountResource.java#L196)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be false?
</blockquote></details>

method name was wrong, fixed it 
___
*[`400-rest/src/main/java/software/wings/resources/AccountResource.java` line 199 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWIriELUD0C_c95g9:-NJKYpa3BNn8qsI9bNb3:blj4pgu) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/resources/AccountResource.java#L199)):*
> method name was wrong, fixed it 
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3188 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWrx21jGnpIWhkIDM:-NJKYrZjEI3O6OgQRIU7:b-kec4hy) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3188)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It should be !isFFToAvoidLoadingSupportAccountsUnncessarilyEnabled()

Please check at other places in code
</blockquote></details>

method name was wrong, fixed it 
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 4112 at r5](https://reviewable.io/reviews/harness/harness-core/40431#-NJKWfQh3wqT9g77dbK7:-NJKYwFP8O3WO-KwWyWP:b-kec4hy) ([raw file](https://github.com/harness/harness-core/blob/06e102eaf353257bcf5c729b565c7ec9a7d35642/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4112)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be 
</blockquote></details>

method name was wrong, fixed it

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r4, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431#-:-NJK_tWUCcvrB-wIJBLu:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 10 files at r3, 1 of 9 files at r4, 4 of 7 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40431)* status: :shipit: complete! ✓

**Pull request merged**
