### PR TITLE
[feat]: [CDS-47006]: Spot Elastigroup added steps for Blue Green strategy

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Describe your changes
We were working on feature branch earlier. But later when we planned to merge it — we could create 4 PRs.
1. DTOs and other objects
2. Basic Deployment
3. Blue green Deployment (this one!)
4. Complete Junit coverage

This contains changes for Elastigroup swimlane. This includes:
1. Elastigroup Bue Green Deployment steps (Elastigroup Setup and Elastigroup Deploy steps)
2. Junits
The coverage is not complete and is being done in next to next PR.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41591)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger feature-build

**Comment by arvind-choudhary-h** [comment]
trigger feature-build

**Review by lovish1999 — DISMISSED** [review]
> Reviewed 34 of 118 files at r1, 63 of 72 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41591)* status: 120 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 34 of 118 files at r1, 63 of 72 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41591#-:-NJOcCIP2BIRgjQUD-i5:bnfp4nl)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 34 of 118 files at r1, 63 of 72 files at r2, 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41591)* status: :shipit: complete! ✓

**Review by piyush-bhuwalka — APPROVED** [review]
> Reviewed 34 of 118 files at r1, 7 of 23 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41591)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41591)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41591#-:-NJPOPKf1AW63CCKf7SH:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
