### PR TITLE
fix: [CDS-73034]: Adding identity postfix to matrix in case of same combin…

### PR DESCRIPTION
**Pull request by Y0709**
…ation

Issue -- Customer was unable to use matrix expressions when there exact same combination present in the object list for the matrix . They used a JsonArray as list for the matrix and few json objects were same in that list 

```
variables:
          - name: var2
            type: String
            description: ""
            required: false
            value: "{\"dependencies\":[{\"connectorRef\":\"account.docker\",\"imageName\"\
              :\"alpine\",\"imageTag\":\"latest\",\"entryPoint\":[\"/bin/sh\",\"-c\"\
              ,\"echohello\"]},{\"connectorRef\":\"account.docker\",\"imageName\"\
              :\"redis\",\"imageTag\":\"latest\",\"entryPoint\":[\"/bin/sh\",\"-c\"\
              ,\"redis-server\"]},{\"connectorRef\":\"account.docker\",\"imageName\"\
              :\"stable\",\"imageTag\":\"latest\",\"entryPoint\":[\"/bin/sh\",\"-c\"\
              ,\"echohello\"]},{\"connectorRef\":\"account.docker\",\"imageName\"\
              :\"alpine\",\"imageTag\":\"latest\",\"entryPoint\":[\"/bin/sh\",\"-c\"\
              ,\"echohello\"]}]}"
```

```
Like this 
 strategy:
         matrix:
             pipelineDependency: "<+json.list(\"dependencies\", <+stage.variables.var2>)>"
```    
                  
so the matrix expressions were not able to successfully executed for all of them except the first one as we are appending in the index in the keys of different fields in the matrix values in matrix metadata. For the above example the first and the fourth object in the json array are same. Then while evaluation of matrix if we see value of <+matrix.pipelineDependency>  for the 2 same objects we see that one is 
**connectorRef:account.docker imageName:alpine entryPoint:[/bin/sh -c echohello] imageTag:latest** and the other is 
**1_connectorRef:account.docker 1_imageName:alpine 1_entryPoint:[/bin/sh 1_-c 1_echohello] 1_imageTag:latest**

As we can see in the screen shot below the keys in object have become from connectorRef to 1_connectorRef when the same combination is repeated first time so its impossible for customer to figure out what expression to use like they were using <+matrix.pipelineDependency.connectorRef>  what would be working for them will be <+matrix.pipelineDependency.1_connectorRef>

Screenshot 2023-06-28 at 4 05 56 PM

We have fixed this by adding a new value called **matrixIdentifierPostfixForDuplicates** in the matrix values map in case we encounter a same combination as before and its value will be the time for which that combination was encountered again starting from 0. meaning if we encounter the same combination as before first time matrixIdentifierPostfixForDuplicates will be 0 , if second time then 1 and so on.

 We have tested matrix with both cases i.e 
 1) Directly passing list in the matrix

Screenshot 2023-06-28 at 4 08 53 PM

2) Giving diff axes to the matrix

 
Screenshot 2023-06-28 at 4 12 28 PM

 Also added unit tested for the same and will automation for this case as well https://harness.atlassian.net/browse/CDS-73259

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/MatrixConstants.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/49833#-NZ0cn9M0ZBcxhm1LFEb:-NZ0cn9M0ZBcxhm1LFEc:bevgi44) ([raw file](https://github.com/harness/harness-core/blob/c46bc31d96be5e86e578045757c473d3b02af7ac/953-yaml-commons/src/main/java/io/harness/yaml/core/MatrixConstants.java#L18)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class MatrixConstants {
>   public final String IDENTIFIER_POSTFIX = "identifierPostfix";
> ```

identifierPostFix is already an expression, maybe we should call it with a different name?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/MatrixConstants.java` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/49833#-NZ0cn9M0ZBcxhm1LFEb:-NZ0p1bp7w_QFv2Onc5a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c46bc31d96be5e86e578045757c473d3b02af7ac/953-yaml-commons/src/main/java/io/harness/yaml/core/MatrixConstants.java#L18)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

identifierPostFix is already an expression, maybe we should call it with a different name?
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/49833#-NZ1fFpVANXxMEm0FT9Z:-NZ1fFpXAG5oxgvLcgvm:b-g5pv6c) ([raw file](https://github.com/harness/harness-core/blob/5aef9c959daa7a7196d8fa69599b16e8b3e74d86/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/MatrixConfigServiceHelper.java#L74)):*
> ```Java
>       // two different combinations
>       if (combinationStringMap.containsKey(variableName)) {
>         Integer cnt = combinationStringMap.get(variableName);
> ```

nit: we can use map.getOrDefault method as well.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49833)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger review

**Comment by Y0709** [comment]
trigger messagecheck

**Pull request merged**
