### PR TITLE
feat: [PIE-4028]: Separate Resource interface from Resource Implementation

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35349)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
Also remove 800-pipeline contracts using visualizatin

> Reviewed 29 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35349#-:-N6vmv5g7ub83HZt5pQO:b-6f0m4b)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmZxN-ULO2_A3Zep4:-N6vmZxN-ULO2_A3Zep5:byquu61) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L20)):*
> ```Java
> 
> import com.google.inject.Inject;
> import io.swagger.v3.oas.annotations.Hidden;
> ```

Do we need this?



_Code quote:_
```Java
tations.Hidden;
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceImpl.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmeCq-2omk1q5YonE:-N6vmeCq-2omk1q5YonF:b-omr6kb) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceImpl.java#L23)):*
> ```Java
> 
> import com.google.inject.Inject;
> import io.swagger.v3.oas.annotations.Hidden;
> ```

hidden is needed?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceV2Impl.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmh591YzgosfODLQe:-N6vmh591YzgosfODLQf:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceV2Impl.java#L23)):*
> ```Java
> 
> import com.google.inject.Inject;
> import io.swagger.v3.oas.annotations.Hidden;
> ```

same
___
*[`800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PMSLandingDashboardResourceImpl.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmkiu3J7nS1ozZX4Q:-N6vmkiu3J7nS1ozZX4R:bpjkgiz) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PMSLandingDashboardResourceImpl.java#L34)):*
> ```Java
> import javax.ws.rs.Path;
> import javax.ws.rs.Produces;
> import javax.ws.rs.QueryParam;
> ```

should be removed



_Code quote:_
```Java
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import javax.validation.constraints.NotNull;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
```
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/HealthResourceImplTest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmEGu7_-MlioaoPl3:-N6vmEGu7_-MlioaoPl4:b-9bq9yj) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/120-ng-manager/src/test/java/io/harness/ng/core/remote/HealthResourceImplTest.java#L35)):*
> ```Java
> @RunWith(PowerMockRunner.class)
> @PrepareForTest(MaintenanceController.class)
> public class HealthResourceImplTest extends CategoryTest {
> ```

why we are chaning healthResource for other services?
___
*[`340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/HealthResourceImplTest.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmHlz-m0cUhLCpCJO:-N6vmHlz-m0cUhLCpCJP:b-9bq9yj) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/HealthResourceImplTest.java#L40)):*
> ```Java
> @RunWith(PowerMockRunner.class)
> @PrepareForTest(MaintenanceController.class)
> public class HealthResourceImplTest extends CategoryTest {
> ```

why we are chaning healthResource for other services?
___
*[`400-rest/src/test/java/software/wings/resources/HealthResourceImplTest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmIzi1V0si-OwEODc:-N6vmIzi1V0si-OwEODd:b-9bq9yj) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/400-rest/src/test/java/software/wings/resources/HealthResourceImplTest.java#L35)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class HealthResourceImplTest extends CategoryTest {
> ```

why we are chaning healthResource for other services?
___
*[`840-template-service/src/test/java/io/harness/template/health/HealthResourceImplTest.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmoxP8C-aeI2FF6jf:-N6vmoxP8C-aeI2FF6jg:b-q8xmgo) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/840-template-service/src/test/java/io/harness/template/health/HealthResourceImplTest.java#L37)):*
> ```Java
> @OwnedBy(CDC)
> @RunWith(PowerMockRunner.class)
> @PrepareForTest(MaintenanceController.class)
> ```

why change their services?

**Review by archit-harness — COMMENTED** [review]
> Reviewed 7 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35349)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmZxN-ULO2_A3Zep4:-N6wGEUU4KGQHbmfvCEO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/approval/resources/ApprovalResourceImpl.java#L20)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

done
___
*[`800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceImpl.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmeCq-2omk1q5YonE:-N6wGH0bBG1DXLBW7vxo:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceImpl.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

hidden is needed?
</blockquote></details>

done
___
*[`800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceV2Impl.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmh591YzgosfODLQe:-N6wGJGlBKDe_G9jYXz5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PipelineDashboardOverviewResourceV2Impl.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same
</blockquote></details>

done
___
*[`800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PMSLandingDashboardResourceImpl.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmkiu3J7nS1ozZX4Q:-N6wGKT46VsMKKXqJ2ij:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/800-pipeline-service/src/main/java/io/harness/pms/Dashboard/PMSLandingDashboardResourceImpl.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should be removed
</blockquote></details>

done

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r2, 1 of 1 files at r3, 47 of 47 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35349)* status: 78 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/35349#-N6x-4on8ZIagoelTQmL:-N6x-4on8ZIagoelTQmM:bba9g5p) ([raw file](https://github.com/harness/harness-core/blob/0770f087be7136fc08b5d0cc77fb6428f70fdeb5/800-pipeline-service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L69)):*
> ```Java
> import javax.validation.Valid;
> import javax.validation.constraints.NotNull;
> import javax.ws.rs.BeanParam;
> ```

remove beanParams
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/35349#-N6x-9oLA_ulu_tnto3K:-N6x-9oLA_ulu_tnto3L:b2vuq1e) ([raw file](https://github.com/harness/harness-core/blob/0770f087be7136fc08b5d0cc77fb6428f70fdeb5/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java#L57)):*
> ```Java
> import javax.validation.Valid;
> import javax.validation.constraints.NotNull;
> import javax.ws.rs.BeanParam;
> ```

remove beansParams
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/remote/HealthResourceImplTest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmEGu7_-MlioaoPl3:-N6x-QMp-p6RFOgVUBiZ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/120-ng-manager/src/test/java/io/harness/ng/core/remote/HealthResourceImplTest.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are chaning healthResource for other services?
</blockquote></details>

done
___
*[`340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/HealthResourceImplTest.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmHlz-m0cUhLCpCJO:-N6x-R2J12mAVQJxZ92p:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/340-ce-nextgen/src/test/java/io/harness/ccm/remote/resources/HealthResourceImplTest.java#L40)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are chaning healthResource for other services?
</blockquote></details>

done
___
*[`400-rest/src/test/java/software/wings/resources/HealthResourceImplTest.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmIzi1V0si-OwEODc:-N6x-RrW0Pjctp5QqJAD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/400-rest/src/test/java/software/wings/resources/HealthResourceImplTest.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are chaning healthResource for other services?
</blockquote></details>

done
___
*[`840-template-service/src/test/java/io/harness/template/health/HealthResourceImplTest.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/35349#-N6vmoxP8C-aeI2FF6jf:-N6x-SZFAyQLUCu34CgX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6e187a9b6d1131186c24d9f4a65fb08a0128bc3e/840-template-service/src/test/java/io/harness/template/health/HealthResourceImplTest.java#L37)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why change their services?
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35349)* status: 78 file(s) to review. 1 of 2 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 20 of 32 files at r1, 7 of 10 files at r2, 45 of 47 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35349)* status: 4 file(s) to review.

**Pull request merged**
