### PR TITLE
fix: [PL-29837]: Fix error case in git sync

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40240)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 453 at r1](https://reviewable.io/reviews/harness/harness-core/40240#-NH-FqL5CMyO2sNP8xWx:-NH-FqL6DexBGTpEw30Z:b-mvnw5y) ([raw file](https://github.com/harness/harness-core/blob/f70a91dce8d9b23bc2c79537f0784738f8ed6d01/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L453)):*
> ```Java
>             changeSetId, accountId, response);
>         log.error("Failure in git command execution", e);
>         YamlChangeSet yamlChangeSet = yamlChangeSetService.get(accountId, changeSetId);
> ```

what if this is null? it will result in NPE

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40240)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 453 at r1](https://reviewable.io/reviews/harness/harness-core/40240#-NH-FqL5CMyO2sNP8xWx:-NH-GCcOCB0v9WgX2wWq:b-5qxgl7) ([raw file](https://github.com/harness/harness-core/blob/f70a91dce8d9b23bc2c79537f0784738f8ed6d01/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L453)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this is null? it will result in NPE
</blockquote></details>

i dont think it can be null - if it is - let it be :smile:

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 453 at r1](https://reviewable.io/reviews/harness/harness-core/40240#-NH-FqL5CMyO2sNP8xWx:-NH-HvDP0y1QmSuT8T7g:b-hksnaf) ([raw file](https://github.com/harness/harness-core/blob/f70a91dce8d9b23bc2c79537f0784738f8ed6d01/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L453)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

i dont think it can be null - if it is - let it be :smile: 
</blockquote></details>

I must say not so good statements on code review :-p

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40240)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 453 at r1](https://reviewable.io/reviews/harness/harness-core/40240#-NH-FqL5CMyO2sNP8xWx:-NH-IaLR80e0Eac6T-RT:bwb0ado) ([raw file](https://github.com/harness/harness-core/blob/f70a91dce8d9b23bc2c79537f0784738f8ed6d01/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L453)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I must say not so good statements on code review :-p 
</blockquote></details>

fixed it at 4 am :/

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by Y0709 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40240)* status: :shipit: complete! ✓

**Pull request merged**
