### PR TITLE
[fix]: [CDS-41532]: validating issuetype on jira approval step

### PR DESCRIPTION
**Pull request by lasdox**
## Describe your changes

This PR adds validation on jira issue type in a jira step approval.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36215)

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/jira/JiraApprovalCallback.java` line 134 at r2](https://reviewable.io/reviews/harness/harness-core/36215#-N92hgKoClYy3WIiZ_zj:-N92hgKoClYy3WIiZ_zk:bm8ggbv) ([raw file](https://github.com/harness/harness-core/blob/584c1cd1e85e4e4417f56c209343b44b3d654235/pipeline-service/service/src/main/java/io/harness/pms/approval/jira/JiraApprovalCallback.java#L134)):*
> ```Java
>   @VisibleForTesting
>   protected void validateIssueType(JiraApprovalInstance instance, JiraTaskNGResponse jiraTaskNGResponse) {
>     if (!isNull(instance.getIssueType())) {
> ```

Please, add two more unit tests: when issueType is null and issueType is empty.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/approval/jira/JiraApprovalCallback.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/36215#-N92g__L2q-P_By4X2G6:-N92g__L2q-P_By4X2G7:b45l96r) ([raw file](https://github.com/harness/harness-core/blob/584c1cd1e85e4e4417f56c209343b44b3d654235/pipeline-service/service/src/main/java/io/harness/pms/approval/jira/JiraApprovalCallback.java#L137)):*
> ```Java
>       final String issueType = jiraTaskNGResponse.getIssue().getFields().getOrDefault("Issue Type", "").toString();
>       if (!instance.getIssueType().equals(issueType)) {
>         log.warn("Invalid issue type");
> ```

Please, add more context to that warning message. What is expected and what is received, like you already do in the below line.
___
*[`pipeline-service/service/src/test/java/io/harness/pms/approval/jira/JiraApprovalCallbackTest.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/36215#-N92hJWlDtnve--GpUVv:-N92hJWlDtnve--GpUVw:b-tnlxla) ([raw file](https://github.com/harness/harness-core/blob/584c1cd1e85e4e4417f56c209343b44b3d654235/pipeline-service/service/src/test/java/io/harness/pms/approval/jira/JiraApprovalCallbackTest.java#L176)):*
> ```Java
>     jiraApprovalCallback.validateIssueType(instance, response);
> 
>     verify(approvalInstanceService, times(0))
> ```

Please, change the use of times(0) to never() to turn the code more readable.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: :shipit: complete! ✓

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: :shipit: complete! ✓

**Review by Fernando-Dourado — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: :shipit: complete! ✓

**Review by srinivaswings — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36215)* status: :shipit: complete! ✓

**Pull request merged**
