### PR TITLE
fix: [CDS-73727]: Use Infrastructure Overriden Docker connector to set the image name for Init Task For Container step

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
If we override the image connector for pulling lite-engine/addon images, We have to send the fully qualified image path to the CI Init Task
Currently, if I setup a docker connector with registry URL ( lets say X ), we send the image name as `harness/lite-engine` 
However, the correct image name should contain the registry URL so that k8s does not pull the image from public docker hub. We have to send `X/harness/lite-engine` to the CI Init Task.

Also verified that CI does the same thing

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50355)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/50355#-N_-2Huv8X3G9-7vwZ6p:-N_-virq2tb7LUuvK70n:bsp5ajv) ([raw file](https://github.com/harness/harness-core/blob/3f922816850b669f85c366fcf91eae763ea14396/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L210)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Taken from: io.harness.ci.integrationstage.IntegrationStageUtils#getFullyQualifiedImageName
</blockquote></details>

Can we move this function to CiIntegrationStageUtils and call that function from CI too?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50355)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/50355#-N_-2Huv8X3G9-7vwZ6p:-N_2lZjl8eIYL2HqUGQd:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3f922816850b669f85c366fcf91eae763ea14396/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/ContainerParamsProvider.java#L210)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we move this function to CiIntegrationStageUtils and call that function from CI too?
</blockquote></details>

Done

**Comment by yogesh-chauhan** [comment]
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/IntegrationStageUtils.java` line 703 at r2](https://reviewable.io/reviews/harness/harness-core/50355#-N_2mNq_3DYzrniMfNOm:-N_2mNq_3DYzrniMfNOn:bn4lgsu) ([raw file](https://github.com/harness/harness-core/blob/58ff85323877bdd220649c167e9827aecf5fe509/332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/IntegrationStageUtils.java#L703)):*
> ```Java
>     String prefixRegistryPath = registryHostName + url.getPath();
>     return trimTrailingCharacter(prefixRegistryPath, '/') + '/' + trimLeadingCharacter(imageName, '/');
>   }
> ```

moved to CiIntegrationStageUtils

**Comment by yogesh-chauhan** [comment]
trigger checkstylecodeformat

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 12 of 13 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50355)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by harshjain12 — DISMISSED** [review]

**Comment by yogesh-chauhan** [comment]
trigger uts_JDK11

**Comment by yogesh-chauhan** [comment]
trigger uts_JDK11

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50355)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by harshjain12 — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
