### PR TITLE
feat: [PL-29026]: Create new listFiles GRPC endpoint in git-service with E2E integration

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39388)

### CODE REVIEW

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed 19 of 32 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39388)* status: 42 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 317 at r2](https://reviewable.io/reviews/harness/harness-core/39388#-NFgW0rk0pP-3v5pjJly:-NFgW0rk0pP-3v5pjJlz:bhod61i) ([raw file](https://github.com/harness/harness-core/blob/529eb474341898ba545fb2b217d40f41a28176a9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L317)):*
> ```Java
>                     .build()),
>             scmConnector);
> ```

will error handling be added later?
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/39388#-NFgY1rA9CLaBF0IF7aM:-NFgY1rA9CLaBF0IF7aN:bowprk0) ([raw file](https://github.com/harness/harness-core/blob/529eb474341898ba545fb2b217d40f41a28176a9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L445)):*
> ```Java
>                       .accountIdentifier(accountIdentifier)
>                       .orgIdentifier(orgIdentifier)
>                       .projectIdentifier(projectIdentifier)
> ```

if the testing has been done, can we remove this?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 317 at r2](https://reviewable.io/reviews/harness/harness-core/39388#-NFgW0rk0pP-3v5pjJly:-NFhe0Hd5qMWX3SkENUY:bb77ufg) ([raw file](https://github.com/harness/harness-core/blob/529eb474341898ba545fb2b217d40f41a28176a9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L317)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

will error handling be added later?
</blockquote></details>

Yes.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/39388#-NFgY1rA9CLaBF0IF7aM:-NFhe2OZ6P0qlkcBaFWr:b-n03cqe) ([raw file](https://github.com/harness/harness-core/blob/529eb474341898ba545fb2b217d40f41a28176a9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L445)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

if the testing has been done, can we remove this?
</blockquote></details>

Plan is to keep it for 1 release. Then we will remove it. There may be more testing required until its live on QA/Prod E2E with error handling.

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 17 of 32 files at r1, 22 of 23 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39388)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]

**Review by adivishy1 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39388)* status: 3 file(s) to review.

**Comment by AnshuH** [comment]
trigger ti1 ti3 ti4

**Comment by ChrisHam8066** [comment]
trigger ti0, ti1, ti2, ti3, ti4

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 11 of 32 files at r1, 18 of 23 files at r2, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 13 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39388)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39388)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
trigger codebasehash

**Pull request merged**
