### PR TITLE
fix: [CDS-37909]: Git sync better retry

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33701)

### CODE REVIEW

**Review by srinivaswings — CHANGES_REQUESTED** [review]
Instead of InstanceOf, have a separate catch block for each exception.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33701)* status: :shipit: complete! ✓

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 424 at r2](https://reviewable.io/reviews/harness/harness-core/33701#-N3smzpn1ye5-bt6BUp5:-N3smzpn1ye5-bt6BUp6:b-6xuh00) ([raw file](https://github.com/harness/harness-core/blob/a74f2f095224d54a1255dea7748b8fb3fdef403e/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L424)):*
> ```Java
>         notify(responseData);
>       } catch (NoAvailableDelegatesException | NoInstalledDelegatesException e) {
>         log.warn("Git request failed for command:[{}], changeSetId:[{}], account:[{}], response:[{}]", gitCommandType,
> ```

why is this warn log? Can we make it error log? I don't think it will pollute or dump a lot of data, but can help in debugging issues.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 430 at r2](https://reviewable.io/reviews/harness/harness-core/33701#-N3sn85YCPeKAerlvfK8:-N3sn85YCPeKAerlvfK9:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/a74f2f095224d54a1255dea7748b8fb3fdef403e/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L430)):*
> ```Java
>             Collections.singletonList(Status.RUNNING), Collections.singletonList(changeSetId));
>       } catch (Exception e) {
>         log.warn("Git request failed for command:[{}], changeSetId:[{}], account:[{}], response:[{}]", gitCommandType,
> ```

same

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33701)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 424 at r2](https://reviewable.io/reviews/harness/harness-core/33701#-N3smzpn1ye5-bt6BUp5:-N3soTj26UJq-PcI6X3g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a74f2f095224d54a1255dea7748b8fb3fdef403e/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L424)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this warn log? Can we make it error log? I don't think it will pollute or dump a lot of data, but can help in debugging issues.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java` line 430 at r2](https://reviewable.io/reviews/harness/harness-core/33701#-N3sn85YCPeKAerlvfK8:-N3soUMl2l56sKeKEmla:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a74f2f095224d54a1255dea7748b8fb3fdef403e/400-rest/src/main/java/software/wings/service/impl/yaml/GitCommandCallback.java#L430)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33701#-:-N3sqa1hEvkuyvGTbYDy:bnfp4nl)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33701)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33701)* status: :shipit: complete! ✓

**Pull request merged**
