### PR TITLE
fix: [PL-27456]: Include empty deps list in BUILD files

### PR DESCRIPTION
**Pull request by hemanthmantri**
Add empty dependencies also to the BUILD file. This would make it easier to upsert the BUILD files with any updated dependencies

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36455)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36455)

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36455)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]
Can you please add PR description on why this change was done?

"Adding empty dependencies also to the build cleaner. This would make it easier to upsert the BUILD files with any updated dependencies"

**Comment by hemanthmantri** [comment]
Addressed comments. Need an approval from Reviewable.

**Review by hemanthmantri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36455)* status: 1 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36455)* status: 1 file(s) to review.

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36455)* status: :shipit: complete! ✓

**Pull request merged**
