### PR TITLE
feat: [PL-40210]: notification rule minor fixes and clean up

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
-Fix document name for NotificationRule
-Add channel type to template identifier to match with existing template look up
-Pass notification trigger request id to store in notificationNg collection

Test-
-End to end notification testing
-Unit test

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56024)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger uts

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56024)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/56024#-NkJlNXi71izWPHuXlxQ:-NkJlNXi71izWPHuXlxR:bwu7dr1) ([raw file](https://github.com/harness/harness-core/blob/90614af37fb56638664816e3bdb3e1c98fb10e7d/platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java#L51)):*
> ```Java
>     try {
>       return Notification.builder()
>           .id(notificationRequestId)
> ```

Why are we using an external value instead of uuid to set value of id?
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/56024#-NkJlsil6JS7MK08vlOD:-NkJlsil6JS7MK08vlOE:bp4mfpc) ([raw file](https://github.com/harness/harness-core/blob/90614af37fb56638664816e3bdb3e1c98fb10e7d/platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java#L65)):*
> ```Java
>     NotificationRequest.Builder notificationRequestBuilder =
>         NotificationRequest.newBuilder().setAccountId(notificationRule.getAccountIdentifier());
>     String channelType = notificationChannel.getNotificationChannelType().toString().toLowerCase();
> ```

Why the need of lowercase? Can we add value for enum and use it instead of relying on logic? This can be error prone.

**Comment by jennyjames21** [comment]
> > Reviewed 4 of 4 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/56024)_ status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/56024#-NkJlNXi71izWPHuXlxQ:-NkJlNXi71izWPHuXlxR:bwu7dr1) ([raw file](https://github.com/harness/harness-core/blob/90614af37fb56638664816e3bdb3e1c98fb10e7d/platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java#L51)):_
> 
> > ```java
> >     try {
> >       return Notification.builder()
> >           .id(notificationRequestId)
> > ```
> 
> Why are we using an external value instead of uuid to set value of id?

> Id is not uuid here, there is _id field for that. Note this is how we set for existing notification flow and is used by notification engine 
image
> _[`platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/56024#-NkJlsil6JS7MK08vlOD:-NkJlsil6JS7MK08vlOE:bp4mfpc) ([raw file](https://github.com/harness/harness-core/blob/90614af37fb56638664816e3bdb3e1c98fb10e7d/platform-service/modules/notification-service/src/main/java/io/harness/notification/remote/mappers/NotificationMapper.java#L65)):_
> 
> > ```java
> >     NotificationRequest.Builder notificationRequestBuilder =
> >         NotificationRequest.newBuilder().setAccountId(notificationRule.getAccountIdentifier());
> >     String channelType = notificationChannel.getNotificationChannelType().toString().toLowerCase();
> > ```
> 
> Why the need of lowercase? Can we add value for enum and use it instead of relying on logic? This can be error prone.
Because this is how templates are registered,  delegate_expired_webhook

**Comment by jennyjames21** [comment]
trigger uts

**Comment by jennyjames21** [comment]
trigger uts

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56024)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
