### PR TITLE
feat: [PL-39821]: added config for enabling/disabling cache in hashicorp vault config

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
added new boolean field for enabling/disabling cache in hashicorp vault config

tested locally - 
- creating new hashicorp vault through UI, without setting `enableCache` field, by default value is setting as true
- creating new hashicorp vault through API, without setting `enableCache` field, by default value is setting as true
- using existing hashicorp vault to create secrets, for them `enableCache` is coming as true
- update existing hashicorp vault connector without setting `enableCache` field, by default value is setting as true
- update existing hashicorp vault connector with setting `enableCache` field as false, it is setting as false 
- check CG hashicorp vault creation and secret creation there `enableCache` is set as null in db and get is giving false value.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50970)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCwcUv9N9WL_Woe3VR:-NaCwcUwDBd5NAhSP7nY:b18eyn8) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L116)):*
> ```Java
> 
>   public Boolean getEnableCache() {
>     return enableCache == null ? Boolean.TRUE : enableCache;
> ```

Why its true for null here and false in BaseVault for same method?

**Comment by piyush-harness** [comment]
*[`931-secret-providers/src/java/software/wings/beans/BaseVaultConfig.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCwidw-ZT0nJDXizkp:-NaCwidw-ZT0nJDXizkq:b3mnwfu) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/931-secret-providers/src/java/software/wings/beans/BaseVaultConfig.java#L128)):*
> ```Java
>   @SchemaIgnore
>   public boolean getEnableCache() {
>     return enableCache == null ? Boolean.FALSE : enableCache;
> ```

Here ^^^ It was true when Null

**Comment by piyush-harness** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCyW0VCgzeI8AIRxAv:-NaCyW0VCgzeI8AIRxAw:b-j1po5a) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java#L114)):*
> ```Java
> 
>   @Builder
>   public VaultConnectorDTO(SecretRefData authToken, String basePath, String vaultUrl, boolean isReadOnly,
> ```

Do we need a new constructor here?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50970)* status: 11 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java` line 116 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCwcUv9N9WL_Woe3VR:-NaD1S804AhBbrv7NAzn:b-7e6xfw) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/vaultconnector/VaultConnector.java#L116)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why its true for null here and false in BaseVault for same method?
</blockquote></details>

This VaultConnector in NG entity, where we want default value as true, while BaseVault is cg entity where we are not doing caching, that's why there is default value of false.
We have made changes in BaseVault because HashiCorpVaultEncryptor is same for CG and NG and it takes VaultConfig as parameter i.e. cg entity
___
*[`931-secret-providers/src/java/software/wings/beans/BaseVaultConfig.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCwidw-ZT0nJDXizkp:-NaD2Cut9NUtEZRfMH4I:b-he4nu4) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/931-secret-providers/src/java/software/wings/beans/BaseVaultConfig.java#L128)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Here ^^^ It was true when Null
</blockquote></details>

replied
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCyW0VCgzeI8AIRxAv:-NaD20smBwUMXfvugOFA:bk0x5vk) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java#L114)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Do we need a new constructor here?
</blockquote></details>

added constructor because I was not able to set default value of boolean field as true

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger uts

**Comment by bhavya181** [comment]
trigger ut1

**Comment by bhavya181** [comment]
trigger message_check

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by piyush-harness** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCyW0VCgzeI8AIRxAv:-NaNas6j982h-hbsox7L:b-1dfxe) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java#L114)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

added constructor because I was not able to set default value of boolean field as true
</blockquote></details>

So setting it to true is not working?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50970)* status: Some of the checks are too old. 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/50970#-NaCyW0VCgzeI8AIRxAv:-NagHKF-5Qqldyi9M7Rw:bl037mq) ([raw file](https://github.com/harness/harness-core/blob/949da8a67f6b663e8249909e99237c9541e52713/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/vaultconnector/VaultConnectorDTO.java#L114)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

So setting it to true is not working?
</blockquote></details>

No, its not working.
I have tried  

-   `boolean` with default value true and using `@Builder.Default` \- for this it is setting default value as false
-   `Boolean` with default value true and using `@Builder.Default` \- for this again default value is null only.

Any other approach you want me to try?  
Or we can go ahead with constructor

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50970)* status: Some of the checks are too old. 12 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
