### PR TITLE
feat: [PL-30970]: Encrypt CG api keys with kms

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
**Problem:**
Currently, CG api keys are encrypted using local encryption. For this, the accountKey is used as an encryption key which is stored as plaintext in Harness DB. We want to remove this security vulnerability as an attacker can have access to the Harness api keys in case they are able to get access to the DB.

**Solution:**
1. We are removing the dependency on accountKey and starting to encrypt the api keys in CG using global KMS. For SAAS environments, this will use the GCP KMS, while for on-prem setup, local encryption will be used as keys will be stored in user db itself. 
(As a future enhancement, for encrypting api keys, we will support a user configured default KMS in on-prem environments too. But that is outside the scope of this task).
2. This will also include a one time migration of existing API keys from local encryption to encryption via KMS.

**Testing:**
The following flows have been tested in local and PR envs:
1. Creating new API key -> verifying its sanity by using in CG APIs.
2. Using existing API keys to check if migration from local encryption to KMS is successful or not.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv0gsiBgNZXf48Rjc-:-NNv0gsjBGtx0vrykvqx:b-2hqvnv) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L42)):*
> ```Java
>         String accountId = apiKeyEntry.getAccountId();
> 
>         if (!isNull(apiKeyEntry.getEncryptedDataId())) {
> ```

This is not the responsibility of this migration. This migration should just say save(apiKeyEntry). All this logic belong there
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 189 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv1mhT8yQ72vFG7hy0:-NNv1mhT8yQ72vFG7hy1:b-q0usmz) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L189)):*
> ```Java
>     } else {
>       User user = UserThreadLocal.get();
>       UserThreadLocal.set(null);
> ```

Whats the need for this?
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 300 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv14WgEJ1kmgJ33sBo:-NNv14WgEJ1kmgJ33sBp:bxf2rzv) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L300)):*
> ```Java
> 
>   @Override
>   public ApiKeyEntry getLocallyEncrypted(String uuid, String accountId) {
> ```

We should not need this method

We should have just 1 method in this class for encryption - encryptApiKey(String uuid) or encryptApiKey(ApiKeyEntry)
We can have 1 methods in this class for decryption - getApiKey(String uuid, boolean decrypt) 
___
*[`400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv0wPs6sqTE_er8wQJ:-NNv0wPs6sqTE_er8wQK:b-6jr7fr) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java#L31)):*
> ```Java
> 
>   ApiKeyEntry get(@NotEmpty String uuid, @NotEmpty String accountId);
>   ApiKeyEntry getLocallyEncrypted(@NotEmpty String uuid, @NotEmpty String accountId);
> ```

We should not expose this method outside
___
*[`400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv1-PU1dArpjxzed8o:-NNv1-PU1dArpjxzed8p:b-6jr7fr) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java#L43)):*
> ```Java
>   void loadUserGroupsForApiKeys(List<ApiKeyEntry> apiKeyEntries, String accountId);
>   Boolean isApiKeyValid(String key, String accountId);
>   EncryptedData encryptApiKey(String accountId, String apiKey);
> ```

We should not expose this method outside

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv0gsiBgNZXf48Rjc-:-NOD8SliAl_c_YVfwbWz:b-oiz8ik) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L42)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This is not the responsibility of this migration. This migration should just say save(apiKeyEntry). All this logic belong there
</blockquote></details>

Moved migration logic to a service method.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 189 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv1mhT8yQ72vFG7hy0:-NOD8YVa061ETaRQVNqW:b-i0wozg) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L189)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the need for this?
</blockquote></details>

This will internally check for secrets view permission. We should not impose secrets view permission for creating/viewing API keys as this will be inconsistent with the current behaviour. Hence, I am setting UserContext as null to bypass the access control check in the SecretsService.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 300 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv14WgEJ1kmgJ33sBo:-NOD8yNfBqdcvcsdnA4N:b-pevfuv) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L300)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should not need this method

We should have just 1 method in this class for encryption - encryptApiKey(String uuid) or encryptApiKey(ApiKeyEntry)
We can have 1 methods in this class for decryption - getApiKey(String uuid, boolean decrypt) 


</blockquote></details>

Refactored this code.
___
*[`400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv0wPs6sqTE_er8wQJ:-NOD92lA76QZ_Tli9zUj:b-11a77w) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should not expose this method outside
</blockquote></details>

Removed the method from service and made it private.
___
*[`400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/43705#-NNv1-PU1dArpjxzed8o:-NOD96tz0ddNMx41H50S:b-11a77w) ([raw file](https://github.com/harness/harness-core/blob/ea4d85786ee71cf2307e131f6d51fb63faae17c7/400-rest/src/main/java/software/wings/service/intfc/ApiKeyService.java#L43)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should not expose this method outside
</blockquote></details>

Removed the method from service and made it private.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/beans/ApiKeyEntry.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONacY2Cn_Ucb7GMT93:-NONacY2Cn_Ucb7GMT94:b-3ss8pf) ([raw file](https://github.com/harness/harness-core/blob/c1890965205fdaf3f3ed4587cb97d3e12e87556e/400-rest/src/main/java/software/wings/beans/ApiKeyEntry.java#L67)):*
> ```Java
>   @JsonView(JsonViews.Internal.class) @NotEmpty @Deprecated private String hashOfKey;
>   @JsonView(JsonViews.Internal.class) @NotEmpty private String sha256Hash;
>   @NotEmpty String encryptedDataId;
> ```

This is @NotEmpty, so won't it break for existing API keys.
Background migration might be in progress before all keys are migrated to new field, right?
cc: @ankit-harness

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 176 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONbBoPBlmWs6ok06nW:-NONbBoPBlmWs6ok06nX:brkce8g) ([raw file](https://github.com/harness/harness-core/blob/c1890965205fdaf3f3ed4587cb97d3e12e87556e/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L176)):*
> ```Java
>     String name = String.format("apiKey_%s_%s", accountId, UUID.randomUUID());
>     SecretText secretText;
>     String kmsId = isNull(secretManagerConfig) ? accountId : secretManagerConfig.getUuid();
> ```

Why is this check required? kmsId=accountId means LOCAL?

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 189 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONbQ6Y9i9yMt18wxta:-NONbQ6Y9i9yMt18wxtb:b-o126p) ([raw file](https://github.com/harness/harness-core/blob/c1890965205fdaf3f3ed4587cb97d3e12e87556e/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L189)):*
> ```Java
>     if (!isNull(apiKeyEntry.getEncryptedDataId())) {
>       // Api key is already encrypted using KMS
>       log.info("Skipping migration for Api key with id: {} in account: {}", uuid, accountId);
> ```

We are just printing log and not really doing anything.
Aren't we supposed to return from here.

**Comment by shashank-harness** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONcvk39XTwCKF0DT8x:-NONcvk39XTwCKF0DT8y:bm5p15x) ([raw file](https://github.com/harness/harness-core/blob/c1890965205fdaf3f3ed4587cb97d3e12e87556e/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L32)):*
> ```Java
>     try (HIterator<ApiKeyEntry> apiKeyEntryHIterator =
>              new HIterator<>(wingsPersistence.createQuery(ApiKeyEntry.class, excludeAuthority).fetch())) {
>       while (apiKeyEntryHIterator.hasNext()) {
> ```

Shouldn't we do this in batches?
How many API keys are there in Prod1/Prod2 and Prod3 currently in CG?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONcvk39XTwCKF0DT8x:-NOOhBBe2SOY-zcLIewR:b4dgk6p) ([raw file](https://github.com/harness/harness-core/blob/3b45db2ba9566086d9535bce20e39611316a8eb2/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L32)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Shouldn't we do this in batches?
How many API keys are there in Prod1/Prod2 and Prod3 currently in CG?
</blockquote></details>

I seen other API keys migrations being run without batches, so this should be fine too. Also, I've made this a background migration now, so should not be much of an issue.
___
*[`400-rest/src/main/java/software/wings/beans/ApiKeyEntry.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONacY2Cn_Ucb7GMT93:-NOOhEHK-gjcd_q5Bfqu:bxpk0g8) ([raw file](https://github.com/harness/harness-core/blob/3b45db2ba9566086d9535bce20e39611316a8eb2/400-rest/src/main/java/software/wings/beans/ApiKeyEntry.java#L67)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

This is @NotEmpty, so won't it break for existing API keys.
Background migration might be in progress before all keys are migrated to new field, right?
cc: @ankit-harness 
</blockquote></details>

The NotEmpty check is not getting triggered in any of the flows where we are fetching and saving ApiKeyEntry to DB. Anyways, I have removed the NotEmpty check for now, will add back once the Api Keys are migrated. We also need to check separately as to why the NotEmpty checks are not getting triggered in the flows.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 176 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONbBoPBlmWs6ok06nW:-NOOhid05TBdVyP1qGf7:bb77ufg) ([raw file](https://github.com/harness/harness-core/blob/3b45db2ba9566086d9535bce20e39611316a8eb2/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L176)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Why is this check required? kmsId=accountId means LOCAL?
</blockquote></details>

Yes.
___
*[`400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java` line 189 at r4](https://reviewable.io/reviews/harness/harness-core/43705#-NONbQ6Y9i9yMt18wxta:-NOOhkNVBPqTOyhYiMpD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b45db2ba9566086d9535bce20e39611316a8eb2/400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java#L189)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

We are just printing log and not really doing anything.
Aren't we supposed to return from here.

</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java` line 33 at r6](https://reviewable.io/reviews/harness/harness-core/43705#-NOsrFwt5ZFM0attd3qI:-NOsrFwt5ZFM0attd3qJ:bbui6ps) ([raw file](https://github.com/harness/harness-core/blob/5d456ad8bb9aa55871ee254e872cc79c8c52f582/390-db-migration/src/main/java/io/harness/migrations/all/ApiKeyLocalToKMSMigration.java#L33)):*
> ```Java
>   @Inject WingsPersistence wingsPersistence;
>   @Inject ApiKeyService apiKeyService;
>   private int batchLimit = 1000;
> ```

nit lets make it final to ensure no place else it is updated. Thanks



_Code quote:_
```Java
private int batchLimit = 1000;
```

**Review by shashank-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by shashank-harness — CHANGES_REQUESTED** [review]
Add the UTs as discussed

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705#-:-NOsvQm04lHTws89ZcUh:b-hwcjqo)* status: 9 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, 8 of 9 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 2 file(s) to review. 3 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/intfc/ApiKeyServiceTest.java` line 295 at r7](https://reviewable.io/reviews/harness/harness-core/43705#-NOwpUXN3DmbNtJLrq4m:-NOwpUXN3DmbNtJLrq4n:bcww7sc) ([raw file](https://github.com/harness/harness-core/blob/d9f615dcd325b6a6aace6830098b561ebb23eb39/400-rest/src/test/java/software/wings/service/intfc/ApiKeyServiceTest.java#L295)):*
> ```Java
>       apiKeyService.validate(apiKeyEntry.getDecryptedKey(), ACCOUNT_ID);
>     } catch (UnauthorizedException ex) {
>       fail("Validation failed: " + ex.getMessage());
> ```

What are we expecting by this test. To throw exception?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 2 file(s) to review. 3 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/java/software/wings/service/intfc/ApiKeyServiceTest.java` line 295 at r7](https://reviewable.io/reviews/harness/harness-core/43705#-NOwpUXN3DmbNtJLrq4m:-NOwpyBH3b_H_LE3w3Wz:b-iqn8r0) ([raw file](https://github.com/harness/harness-core/blob/d9f615dcd325b6a6aace6830098b561ebb23eb39/400-rest/src/test/java/software/wings/service/intfc/ApiKeyServiceTest.java#L295)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What are we expecting by this test. To throw exception?
</blockquote></details>

We just expect the validate call to pass successfully. It would mean that the hash of the saved ApiKey has matched with the key that we pass to the function, which is the expectation from this method.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 8 of 9 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 3 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by nishantsaini20 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43705)* status: 2 change requests. 5. unresolved discussions.

**Pull request merged**
