### PR TITLE
feat: [DEL-5440]: Add check if user has write permissions

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
Sometimes customers run delegate as specific users or groups which don't have write permissions on /opt/harness-delegate/ which is required. 
This change adds a sane error message in such case and exits early. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

Tested by running as different users. This is when run with random user and group.
image

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40665)

### CODE REVIEW

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger messagecheck

**Comment by mdmilic** [comment]
trigger publish-delegate

**Review by AnupamIO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40665)* status: Some of the checks are too old. 1 file(s) to review. 

___
*[`dockerization/delegate/immutable-scripts/start.sh` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/40665#-NIBg7u10a4_zpRfAv_g:-NIBg7u10a4_zpRfAv_h:b-1pw599) ([raw file](https://github.com/harness/harness-core/blob/dcbcba387522f2cecaaf81e68369561a1e7682a0/dockerization/delegate/immutable-scripts/start.sh#L18)):*
> ```Shell
>   echo "Missing required write permissions for running user $(id -run) or group $(id -rgn) on delegate home directory $PWD. Shutting down."
>   exit 1
> fi
> ```

looks good, one question: why are we creating proxy.config if no proxy settings are provided. I mean instead of creating this proxy.config here: https://github.com/harness/harness-core/blob/develop/dockerization/delegate/immutable-scripts/proxy_setup.sh#L21 can we create this file only when proxy_host is not null ?

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40665)* status: Some of the checks are too old.

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40665)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`dockerization/delegate/immutable-scripts/start.sh` line 18 at r1](https://reviewable.io/reviews/harness/harness-core/40665#-NIBg7u10a4_zpRfAv_g:-NID0mr3-0mF2egkkd1k:b-9psmdq) ([raw file](https://github.com/harness/harness-core/blob/dcbcba387522f2cecaaf81e68369561a1e7682a0/dockerization/delegate/immutable-scripts/start.sh#L18)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

looks good, one question: why are we creating proxy.config if no proxy settings are provided. I mean instead of creating this proxy.config here: https://github.com/harness/harness-core/blob/develop/dockerization/delegate/immutable-scripts/proxy_setup.sh#L21 can we create this file only when proxy_host is not null ?
</blockquote></details>

I think that's a fair observation, created a ticket to deal with that
https://harness.atlassian.net/browse/DEL-5482

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40665)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by AnupamIO — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40665)* status: :shipit: complete! ✓

**Pull request merged**
