### PR TITLE
fix: [SMP-758]: add smp account migration to background

### PR DESCRIPTION
**Pull request by kapilgarg1996**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38947)

### CODE REVIEW

**Comment by kapilgarg1996** [comment]
trigger messagecheck

**Comment by akshay-khole** [comment]
Since we are merging into saas, will pipeline cover enough tests to eliminate regression risks ?

**Review by akshay-khole — APPROVED** [review]
Approving, please comment on test related question

**Comment by kapilgarg1996** [comment]
> Since we are merging into saas, will pipeline cover enough tests to eliminate regression risks ?

This is a one time migration Akshay, it will happen once we deploy this into SaaS and the QA setup has roughly same number of accounts as prod so the regression should get identified in QA.
As we don't have those many accounts in PR env, nor do we have the same mongo infra, its hard to test out the actual runtime of this migration but still it should get completed within 2 hour time limit.

**Pull request merged**
