### PR TITLE
[feat]: [CDS-49544]: created api for Artifact card view

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
created API 'getArtifactInstanceDetails' for getting last deployment detail in each environment for artifacts having active instances of a service.

Artifact Card View (Service Dashboard Revamp)
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43041)

### CODE REVIEW

**Comment by Abhishek-CDC** [comment]
trigger messagecheck

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43041)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/EnvironmentInstanceDetails.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/43041#-NN29tsw-c1fKq3Xj5Uq:-NN29tsw-c1fKq3Xj5Ur:b-bd2bhl) ([raw file](https://github.com/harness/harness-core/blob/8cf072c2ca0eddb7e59101fa869ed18203fbfe8c/120-ng-manager/src/main/java/io/harness/ng/overview/dto/EnvironmentInstanceDetails.java#L28)):*
> ```Java
>     String envName;
>     EnvironmentType environmentType;
>     Integer count;
> ```

What was the reason to make this Integer?

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/EnvironmentInstanceDetails.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/43041#-NN29tsw-c1fKq3Xj5Uq:-NN2JyBh19LcNLMiJ5HC:b4w566t) ([raw file](https://github.com/harness/harness-core/blob/8cf072c2ca0eddb7e59101fa869ed18203fbfe8c/120-ng-manager/src/main/java/io/harness/ng/overview/dto/EnvironmentInstanceDetails.java#L28)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

What was the reason to make this Integer?
</blockquote></details>

In artifact card view we don't show instance count, to have value null in this case made count as 'Integer' in place of 'int' otherwise it will have default value 0

**Comment by abhinavmittal-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/overview/dto/EnvironmentInstanceDetails.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/43041#-NN29tsw-c1fKq3Xj5Uq:-NN2Kkpx5oRAN3YgQcDv:bb6u032) ([raw file](https://github.com/harness/harness-core/blob/8cf072c2ca0eddb7e59101fa869ed18203fbfe8c/120-ng-manager/src/main/java/io/harness/ng/overview/dto/EnvironmentInstanceDetails.java#L28)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

In artifact card view we don't show instance count, to have value null in this case made count as 'Integer' in place of 'int' otherwise it will have default value 0
</blockquote></details>

Cool

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43041)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
