### PR TITLE
[fix]: [CDS-48121]: Svc-Env  Migration APIs Swagger fix

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41303)

### CODE REVIEW

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41303)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/resources/ServiceEnvironmentV2MigrationResource.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/41303#-NIlPCpb8LKvXP9jonwB:-NIlPCpc4SJ6SHxOFKPG:bu0n3j8) ([raw file](https://github.com/harness/harness-core/blob/f326c0997aa82760ac09546fcd95a67590f209df/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/resources/ServiceEnvironmentV2MigrationResource.java#L61)):*
> ```Java
>       value = "Migrate a pipeline to new service and environment framework", nickname = "migrateSvcEnvFromPipeline")
>   @Operation(operationId = "migrateSvcEnvFromPipeline",
>       summary = "get pipeline id and migrate to a new svc-env framework  ",
> ```

nit: to the new svc-env framework

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Pull request merged**
