### PR TITLE
[feat]: [CDS-71454]: Core logic for default branch caching

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added the core logic for default branch caching and tested it out for get pipeline call when the branch is not passed and we have to fetch from the default branch. Have tested out the cache create, get and invalidate operations.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger ss

**Comment by mohitg0795** [comment]
*[`120-ng-manager/config.yml` line 223 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXijkj7-EaT3ytB4Yvv:-NXijkj7-EaT3ytB4Yvw:baig4ro) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/120-ng-manager/config.yml#L223)):*
> ```YAML
>       idleTime: ${GIT_SERVICE_CACHING_BACKGROUND_UPDATE_THREAD_POOL_IDLE_TIME:-60}
>       timeUnit: ${GIT_SERVICE_CACHING_BACKGROUND_UPDATE_THREAD_POOL_IDLE_TIME_TIME_UNIT:-SECONDS}
>     validDefaultBranchCacheDurationInMillis: ${GIT_SERVICE_DEFAULT_BRANCH_VALID_CACHE_DURATION:- 604800000}
> ```

I guess this is in ms right now? Lets convert it into seconds. We won't need ms for default branch caching.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitCacheTTLHelper.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/49009#-NXikmyd2L3LD8l66EIj:-NXikmyd2L3LD8l66EIk:b-6aj9ok) ([raw file](https://github.com/harness/harness-core/blob/8ba2af40a9b5275b289c30a6c1b6f33eb5d957c8/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitCacheTTLHelper.java#L22)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class GitCacheTTLHelper {
> ```

any reason that we want to combine both TTL helpers for file cache and default branch cache? Possible to use them separately only?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheService.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXil87w3y8vPrOrHNYR:-NXil87w3y8vPrOrHNYS:b-k0x4ei) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheService.java#L18)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface GitDefaultBranchCacheService {
>   GitDefaultBranchCacheResponse fetchFromCache(GitDefaultBranchCacheKey gitDefaultBranchCacheKey);
> ```

this can be a list response as well right? What if I pass only account identifier in the key?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)* status: 15 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 223 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXijkj7-EaT3ytB4Yvv:-NXitpYI9Gv0jGFXY3X_:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/120-ng-manager/config.yml#L223)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I guess this is in ms right now? Lets convert it into seconds. We won't need ms for default branch caching.
</blockquote></details>

Done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/GitServiceCacheConfiguration.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXijsfT2qOH1VVdYwZ-:-NXiuHJ4DaAVKuUmszyC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/GitServiceCacheConfiguration.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

seconds ^
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheService.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXil87w3y8vPrOrHNYR:-NXix3954tpcJLAImCpM:b-z6p024) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheService.java#L18)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this can be a list response as well right? What if I pass only account identifier in the key?
</blockquote></details>

as the the cache is for storing a default branch for a given repo, I dont feel its right to query for all default branches for a given accountIdentifier
also, when we have such a case, we can add the support to query based on accountIdentifiers 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitCacheTTLHelper.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/49009#-NXikmyd2L3LD8l66EIj:-NXiwTZ0-5FYyWwwmA9a:bxtbglm) ([raw file](https://github.com/harness/harness-core/blob/8ba2af40a9b5275b289c30a6c1b6f33eb5d957c8/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitCacheTTLHelper.java#L22)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

any reason that we want to combine both TTL helpers for file cache and default branch cache? Possible to use them separately only?
</blockquote></details>

Its doing the same set of operations and set of beans being injected, so thought we can have it in the same Helper even though we can have them in different helpers, 
any reason to have them separately?

**Comment by USB-05** [comment]
trigger sst

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)* status: 15 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 223 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXijkj7-EaT3ytB4Yvv:-NXj1MYRAjAttWk9Wgh1:b-rwxx9k) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/120-ng-manager/config.yml#L223)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Changing to mins
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheService.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/49009#-NXil87w3y8vPrOrHNYR:-NXjC1k7Ev-Qb8KMuyqR:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ceffa99c30821cbd2449ff73babed68ef0de75f0/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheService.java#L18)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

as the the cache is for storing a default branch for a given repo, I dont feel its right to query for all default branches for a given accountIdentifier
also, when we have such a case, we can add the support to query based on accountIdentifiers 
</blockquote></details>

Done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitCacheTTLHelper.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/49009#-NXikmyd2L3LD8l66EIj:-NXjC07RB4eJSXDCMgdl:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/8ba2af40a9b5275b289c30a6c1b6f33eb5d957c8/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitCacheTTLHelper.java#L22)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Its doing the same set of operations and set of beans being injected, so thought we can have it in the same Helper even though we can have them in different helpers, 
any reason to have them separately?
</blockquote></details>

Done

**Comment by mohitg0795** [comment]
*[`120-ng-manager/config.yml` line 223 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjVLNH6DCNYCc_qi1K:-NXjVLNH6DCNYCc_qi1L:b-m01912) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/120-ng-manager/config.yml#L223)):*
> ```YAML
>       idleTime: ${GIT_SERVICE_CACHING_BACKGROUND_UPDATE_THREAD_POOL_IDLE_TIME:-60}
>       timeUnit: ${GIT_SERVICE_CACHING_BACKGROUND_UPDATE_THREAD_POOL_IDLE_TIME_TIME_UNIT:-SECONDS}
>     validDefaultBranchCacheDurationInMinutes: ${GIT_SERVICE_DEFAULT_BRANCH_VALID_CACHE_DURATION:- 1440}
> ```

why do we need valid time duration? It should be simply cache duration. It expired after given time, thats it

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/beans/GitDefaultBranchCacheKeyParams.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjVXqz18CvXQL6Gprb:-NXjVXqz18CvXQL6Gprc:b62qaa0) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/beans/GitDefaultBranchCacheKeyParams.java#L24)):*
> ```Java
> @OwnedBy(HarnessTeam.PIPELINE)
> @ToString
> public class GitDefaultBranchCacheKeyParams {
> ```

Lets add keyword "filter" here otherwise people may confuse it with the other class

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjWcspEt1nhlcQs904:-NXjWcspEt1nhlcQs905:b-5hgk3w) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L73)):*
> ```Java
> 
>   @Override
>   public List<GitDefaultBranchCacheResponse> listFromCache(
> ```

Test out cases when one of the fields is passed empty or null. We want that those fields should be ignored from the query rather than assuming their value as empty in the query. eg: If only account id is passed, then we want that all results for the given account id are returned.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitDefaultBranchCacheHelper.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjYDOj7zl1g0LODRO3:-NXjYDOj7zl1g0LODRO4:b-pagjj6) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitDefaultBranchCacheHelper.java#L29)):*
> ```Java
>   }
> 
>   public Date getValidUntilTimeForDefaultBranchCache(long currentTime) {
> ```

why do we need to add into our methods : "ForDefaultBranchCache"? Its understood as its the helper class itself.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)* status: 18 file(s) to review. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 223 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjVLNH6DCNYCc_qi1K:-NXjkqmQ-Gp2L4Yq0t_Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/120-ng-manager/config.yml#L223)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need valid time duration? It should be simply cache duration. It expired after given time, thats it
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitDefaultBranchCacheHelper.java` line 29 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjYDOj7zl1g0LODRO3:-NXjizbP8MPfnswDdVqb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/helper/GitDefaultBranchCacheHelper.java#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to add into our methods : "ForDefaultBranchCache"? Its understood as its the helper class itself.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 45 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjW0i-6CYKO_pD54bP:-NXjjzF45qKUqLXGdBxv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L45)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

its not expected to have more than 1 response in this case. We should log an error here if thats happening and throw exception.
Also, ensure that we have unique index over the 3 fields in the cache key.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 54 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjWOah4pQPGIie8QSk:-NXjoooo8j1Eim9vfvN4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L54)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

how is it possible to get a null value here? Upsert should either result into error or success response only.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 67 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjWzc59WwiQg4AhF04:-NXjmuyl0I24eogPPzvQ:b-95txdl) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L67)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

how can it be an optional criteria if all fields in git default branch cache key are mandatory? We can also put @NotNull annotation to enforce the behaviour.

Invalidate case is very similar to fetch list case. We need to use filter params here.
</blockquote></details>


Done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 73 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjWcspEt1nhlcQs904:-NXjpy7c152Qf2iQKKDu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L73)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Test out cases when one of the fields is passed empty or null. We want that those fields should be ignored from the query rather than assuming their value as empty in the query. eg: If only account id is passed, then we want that all results for the given account id are returned.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/beans/GitDefaultBranchCacheKeyParams.java` line 24 at r6](https://reviewable.io/reviews/harness/harness-core/49009#-NXjVXqz18CvXQL6Gprb:-NXjikH54BYR8E2grW5b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14bf96dfa5d7ebfa244f5aecff940b4c0b2207aa/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/beans/GitDefaultBranchCacheKeyParams.java#L24)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add keyword "filter" here otherwise people may confuse it with the other class
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 85 at r7](https://reviewable.io/reviews/harness/harness-core/49009#-NXnJ7HVBCqCGgxaR3ah:-NXnJ7HVBCqCGgxaR3ai:brluscy) ([raw file](https://github.com/harness/harness-core/blob/09446ce5da2495edc59cff341ff5fab9978cfdf4/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L85)):*
> ```Java
>             gitDefaultBranchCacheKeyFilterParams.getRepoUrl(), gitDefaultBranchCacheKeyFilterParams.getRepo());
>     if (gitDefaultBranchCacheList == null) {
>       return null;
> ```

we shouldn't return null

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 4 of 12 files at r1, 2 of 6 files at r2, 1 of 3 files at r3, 5 of 12 files at r5, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)* status: 18 file(s) to review. 0 of 2 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)* status: 18 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java` line 85 at r7](https://reviewable.io/reviews/harness/harness-core/49009#-NXnJ7HVBCqCGgxaR3ah:-NXnKbugC4tFsYVKrxhX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09446ce5da2495edc59cff341ff5fab9978cfdf4/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/service/GitDefaultBranchCacheServiceImpl.java#L85)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't return null
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49009)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger commonchecks, uts

**Comment by adivishy1** [comment]
trigger codebasehash, pmd

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
