### PR TITLE
feat: [PL-26172]: added project type ADO connector

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Removed account type ADO connector and added project type ADO connector
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)

### CODE REVIEW

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 21 of 32 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)* status: 35 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67TdN05lBnkK13Mmi4:-N67TdN05lBnkK13Mmi5:bjinj07) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L61)):*
> ```Java
>     }
>     return AzureRepoConnector.builder()
>         .connectionType(getConnectionType(configDTO.getConnectionType()))
> ```

this is a bit misleading as we get connection type from "connection type". Can we rename the method a bit just to be exact here.

**Comment by mohitg0795** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67TmzuD1t5hn8bGnGh:-N67TmzuD1t5hn8bGnGi:bjquptk) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L55)):*
> ```Java
>     return AzureRepoConnectorDTO.builder()
>         .apiAccess(azureApiAccess)
>         .connectionType(buildConnectionType(connector.getConnectionType()))
> ```

same as before

**Comment by mohitg0795** [comment]
*[`810-ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMDataObtainer.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67U9Od9T9ww78m7NPK:-N67U9Od9T9ww78m7NPL:bb052f8) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/810-ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMDataObtainer.java#L174)):*
> ```Java
>       return gitConfigDTO.getConnectionType();
>     } else if (gitConnector.getConnectorType() == AZURE_REPO) {
>       AzureRepoConnectorDTO gitConfigDTO = (AzureRepoConnectorDTO) gitConnector.getConnectorConfig();
> ```

lets rename this variable to "azureGitConfigDTO", so that in next line we are clear that we are converting azure connection type to git connection type

**Comment by mohitg0795** [comment]
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/GitConnectionType.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67UPh2BRMDB0EBoB66:-N67UPh2BRMDB0EBoB67:bc4pob) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/GitConnectionType.java#L16)):*
> ```Java
>   @JsonProperty(GitConfigConstants.ACCOUNT) ACCOUNT,
>   @JsonProperty(GitConfigConstants.REPO) REPO,
>   @Hidden @JsonProperty(GitConfigConstants.PROJECT) PROJECT
> ```

Didn't we resolve it? How will someone know that for Azure, we only support REPO and PROJECT?

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 19 of 32 files at r1, 11 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)* status: 7 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67TdN05lBnkK13Mmi4:-N6DiB730BAcZ3YweAs-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoDTOToEntity.java#L61)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is a bit misleading as we get connection type from "connection type". Can we rename the method a bit just to be exact here.
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java` line 55 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67TmzuD1t5hn8bGnGh:-N6DiB_nA8N7ACzacVXR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/440-connector-nextgen/src/main/java/io/harness/connector/mappers/azurerepomapper/AzureRepoEntityToDTO.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done.
___
*[`810-ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMDataObtainer.java` line 174 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67U9Od9T9ww78m7NPK:-N6DiC692MINN5RmAP2X:b-xev2ql) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/810-ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMDataObtainer.java#L174)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets rename this variable to "azureGitConfigDTO", so that in next line we are clear that we are converting azure connection type to git connection type
</blockquote></details>

This file is owned by CI, if they need they will make changes
___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/GitConnectionType.java` line 16 at r2](https://reviewable.io/reviews/harness/harness-core/34876#-N67UPh2BRMDB0EBoB66:-N6DiIZh9M8Zs5Cj1FFS:b-rmxqe1) ([raw file](https://github.com/harness/harness-core/blob/fcf0ab1b78e9bf8c33d13f50f6f634cb36db20ae/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/GitConnectionType.java#L16)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Didn't we resolve it? How will someone know that for Azure, we only support REPO and PROJECT?
</blockquote></details>

GitConfig is at common layer, we cannot hide project from here, that depends on particular connector what they want to support

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 32 files at r1, 2 of 14 files at r2, 3 of 4 files at r5, 1 of 3 files at r6, 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876#-:-N6NwXBE2Vc6HpZVAirB:bnfp4nl)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 13 of 32 files at r1, 9 of 14 files at r2, 3 of 4 files at r5, 1 of 3 files at r6, 10 of 14 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876#-:-N6QgIg-8TT0hyMSDuPB:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876#-:-N6RdDKd6JkmkUP8BRno:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 13 of 32 files at r1, 9 of 14 files at r2, 3 of 4 files at r5, 1 of 3 files at r6, 10 of 14 files at r7, 1 of 4 files at r8, 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)* status: 2 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876#-:-N6RgGri3Rfsd_tc8Kmz:bnfp4nl)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 13 of 32 files at r1, 9 of 14 files at r2, 3 of 4 files at r5, 1 of 3 files at r6, 10 of 14 files at r7, 1 of 4 files at r8, 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34876)* status: :shipit: complete! ✓

**Pull request merged**
