### PR TITLE
fix: [DEL-4571]: Fix for Poll for task in delegate.sh

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Describe your changes
Updating pollForTask variable in delegate.sh

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)

### CODE REVIEW

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger ti0

**Comment by gaurav-jain1** [comment]
trigger ti1

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger messagecheck

**Comment by gaurav-jain1** [comment]
trigger ti1

**Comment by gaurav-jain1** [comment]
trigger ti0

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/35926#-N8TLbYH04uSW9Pf9ivt:-N8TLbYH04uSW9Pf9ivu:bidpgyx) ([raw file](https://github.com/harness/harness-core/blob/250523c257cb0a28b59f0f339bbb74b725530a2d/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L175)):*
> ```FreeMarker
>   if [ "$DEPLOY_MODE" == "ONPREM" ]; then
>       echo "pollForTasks: true" >> config-delegate.yml
>   elif [[ ! -z "$POLL_FOR_TASKS" ]]; then
> ```

either check for "true" explicitly or set "true" explicitly.
Someone might end up setting as "True" or "TRUE" which is not recognised by delegate config



_Code quote:_
```FreeMarker
! -z "$POLL_FOR_TASKS"
```

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/35926#-N8TLbYH04uSW9Pf9ivt:-N8TMlXo9w2ds_SazBQ1:b-na77xb) ([raw file](https://github.com/harness/harness-core/blob/250523c257cb0a28b59f0f339bbb74b725530a2d/400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl#L175)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

either check for "true" explicitly or set "true" explicitly.
Someone might end up setting as "True" or "TRUE" which is not recognised by delegate config
</blockquote></details>

Java yaml parser will take care of case sensitivity in config-delegate.yml, we are good there

**Comment by gaurav-jain1** [comment]
trigger messagecheck

**Review by Vbhatia20 — APPROVED** [review]

**Review by Vbhatia20 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926#-:-N8Yt5U5697mrsLDU0OW:bnfp4nl)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35926)* status: :shipit: complete! ✓

**Pull request merged**
