### PR TITLE
[feat]: [PL-30025]: Adding config for max batch size of stream processing events for Debezium connector.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Adding config for max batch size of stream processing events for Debezium connector.
Previously we were not setting this property for Debezium Connector as were leveraging the default of 2048 as defined 
https://debezium.io/documentation/reference/stable/connectors/mongodb.html#mongodb-property-max-batch-size
Setting default batch size to 500.
Debezium connector uses this max batch size to read the no of events from Mongo Oplog and we write Offset after processing all the events in batch. If the batch is high and if there is any failure while processing events before the offset is written the Debezium Connector will process all those events again from the last Offset. 

## Checklist
- [X] I've documented the changes in the PR description.
- [] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41957)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger ti4

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41957)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41957#-:-NKMXF_w1O6AcwcIH2de:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41957#-:-NKNCUUAAj5km_WncGrp:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41957)* status: :shipit: complete! ✓

**Pull request merged**
