### PR TITLE
fix: [PIE-4769]: Fix deployment stage bug related to name and identifier a…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…long with the step.iteration bug

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37561)

### CODE REVIEW

**Review by naidu-harness — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37561#-:-NBzchP6ELdqgY4ZJHw4:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37561)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37561)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/37561#-NC-1s747kfREleV5rhe:-NC-1s747kfREleV5rhf:b-wnyv98) ([raw file](https://github.com/harness/harness-core/blob/eefc8578da2173742abf70a63fd5058d7ecbff65/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java#L48)):*
> ```Java
>     JsonNode node = nodeWithStrategy.get("strategy");
>     if (node == null || node.isNull()) {
>       JsonNode clonedNode = JsonPipelineUtils.asTree(JsonUtils.asMap(
> ```

Can we discuss this?



_Code quote:_
```Java
sonPipelineUtils.asTree(JsonUtils.asMap(
```

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37561)* status: 1 file(s) to review. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java` line 48 at r1](https://reviewable.io/reviews/harness/harness-core/37561#-NC-1s747kfREleV5rhe:-NC-B6VG-WgPNoTrnsRG:b-ufcsq8) ([raw file](https://github.com/harness/harness-core/blob/eefc8578da2173742abf70a63fd5058d7ecbff65/878-ng-common-utilities/src/main/java/io/harness/steps/matrix/StrategyHelper.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

discussed, done

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37561)* status: :shipit: complete! ✓

**Pull request merged**
