### PR TITLE
fix: [CDS-35566]: support helm v380 wherever helm v3 is used

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)

### CODE REVIEW

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFZmB51cpQUU9TiDze:-MzFZmB51cpQUU9TiDzf:bz7b0ku) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java#L34)):*
> ```Java
>         .chartName(gcsHelmPayload.getChartName())
>         .helmVersion(gcsHelmPayload.getHelmVersion() == HelmVersion.V2 ? io.harness.k8s.model.HelmVersion.V2
>                 : gcsHelmPayload.getHelmVersion() == HelmVersion.V3    ? io.harness.k8s.model.HelmVersion.V3
> ```

nit: maybe, as suggested in another comment, create fromString method and use something like gcsHelmPayload.getHelmVersion().name (with null check)
___
*[260-delegate/src/main/java/io/harness/perpetualtask/NativeHelmInstanceSyncPerpetualTaskExcecutor.java, line 80 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFYBVs8wWfwMaXt2ST:-MzFYBVs8wWfwMaXt2SU:b-mw4641) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/260-delegate/src/main/java/io/harness/perpetualtask/NativeHelmInstanceSyncPerpetualTaskExcecutor.java#L80)):*
> ```Java
> 
>     HelmVersion helmVersion;
>     switch (taskParams.getHelmVersion()) {
> ```

nit: can be a method in HelmVersion, ex: HelmVersion.fromString(helmVersion)
___
*[400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java, line 92 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFYOMK2zi4R_Uuq2TY:-MzFYOMK2zi4R_Uuq2TZ:b-yk190k) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java#L92)):*
> ```Java
>     boolean useRepoFlags = false;
>     if (featureFlagService.isEnabled(FeatureName.USE_HELM_REPO_FLAGS, accountId)
>         && (HelmVersion.isHelmV3(service.getHelmVersion()))) {
> ```

nit: unnecessary ( 
___
*[970-api-services-beans/src/main/java/io/harness/k8s/model/HelmVersion.java, line 16 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFYbW86OBt9JfESiS-:-MzFYbW86OBt9JfESiS0:bq5yaij) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/970-api-services-beans/src/main/java/io/harness/k8s/model/HelmVersion.java#L16)):*
> ```Java
> 
>   public static boolean isHelmV3(HelmVersion helmVersion) {
>     return V3.equals(helmVersion) || V380.equals(helmVersion);
> ```

can we add null check here? Or use == instead of equals, ex: V3 == helmVersion, it is null safe

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFZmB51cpQUU9TiDze:-MzFjErA6tvB1W7KSjQI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java#L34)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: maybe, as suggested in another comment, create fromString method and use something like gcsHelmPayload.getHelmVersion().name (with null check)
</blockquote></details>

Done.
___
*[260-delegate/src/main/java/io/harness/perpetualtask/NativeHelmInstanceSyncPerpetualTaskExcecutor.java, line 80 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFYBVs8wWfwMaXt2ST:-MzFgYITA81zO_VIuISQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/260-delegate/src/main/java/io/harness/perpetualtask/NativeHelmInstanceSyncPerpetualTaskExcecutor.java#L80)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: can be a method in HelmVersion, ex: HelmVersion.fromString(helmVersion)
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java, line 92 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFYOMK2zi4R_Uuq2TY:-MzFeZ6g3k_dG0P95kNw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java#L92)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: unnecessary ( 
</blockquote></details>

Done.
___
*[970-api-services-beans/src/main/java/io/harness/k8s/model/HelmVersion.java, line 16 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFYbW86OBt9JfESiS-:-MzFe4eLB3zg6s-0fRs2:b-vry8tp) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/970-api-services-beans/src/main/java/io/harness/k8s/model/HelmVersion.java#L16)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can we add null check here? Or use == instead of equals, ex: V3 == helmVersion, it is null safe
</blockquote></details>

actually this was caught in UT. helmVersion.equals(V3) is not null safe (UT failed with NPE) but this V3.equals(helmVersion) is null safe.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFZmB51cpQUU9TiDze:-MzG6_MXDm8RlG6lrLln:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java#L34)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about null check? Just to be sure
</blockquote></details>

Done.



Doing the null check within the method HelmVersion.fromString

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java, line 34 at r3](https://reviewable.io/reviews/harness/harness-core/31794#-MzFZmB51cpQUU9TiDze:-MzG80441Bl83I3a64S1:b-md7l42) ([raw file](https://github.com/harness/harness-core/blob/3df5d2fcc43c7ada707c246b899030d1d44db475/125-cd-nextgen/src/main/java/io/harness/polling/mapper/manifest/GcsHelmChartManifestInfoBuilder.java#L34)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doing the null check within the method HelmVersion.fromString

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 6 of 10 files at r2, 6 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794#-:-MzJgtl0BlLgdSguCTNt:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794#-:-MzJzKYV6ECRNzEBQmeB:bnfp4nl)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31794)* status: :shipit: complete! ✓

**Pull request merged**
