### PR TITLE
feat:[CDS-77906]:Unable to see the artifact details in NG

### PR DESCRIPTION
**Pull request by sribalij**
## Describe your changes
Currently, the deployments page (pipeline executions) do not show artifact information when activated via a trigger. With this change, we are passing the artifact image path and build information and stored in the mongo. This is then used to show  the information on deployments page. 

Tested by uploading a new artifact to ECR. Added Unit tests
image
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52153)

### CODE REVIEW

**Comment by sribalij** [comment]
trigger uts

**Comment by sribalij** [comment]
trigger messagecheck

**Review by vcalasansh — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52153)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sribalij** [comment]
trigger review

**Review by rohitk-h — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52153)* status: :shipit: complete! ✓

**Comment by sribalij** [comment]
trigger review

**Comment by sribalij** [comment]
trigger review

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/trigger_info.proto` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/52153#-NdnNnPq3mp4blA1e4_P:-NdnNnPq3mp4blA1e4_Q:b-y6le9d) ([raw file](https://github.com/harness/harness-core/blob/6fb503a185905f5fd2bfc68de370acc02afea58b/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/trigger_info.proto#L17)):*
> ```proto
>   bool isRerun = 3;
>   RerunInfo rerunInfo = 4;
>   BuildInfo buildInfo = 5;
> ```

Can we store it in planExecutionMetadata maybe? 
We are working on removing all this information from execution metadata and seems like executionTriggerInfo is being used there

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52153)* status: 1. unresolved discussions. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/trigger_info.proto` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/52153#-NdnNnPq3mp4blA1e4_P:-NdnPJSADmSbtoaXQn2_:bq3pnbj) ([raw file](https://github.com/harness/harness-core/blob/6fb503a185905f5fd2bfc68de370acc02afea58b/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/trigger_info.proto#L17)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we store it in planExecutionMetadata maybe? 
We are working on removing all this information from execution metadata and seems like executionTriggerInfo is being used there
</blockquote></details>

This ExecutionTrigger info is already stored in PipelineExecutionSummaryEntity, i don't think in this PR they can remove easily.

plus they need in execution summary API, so for now they need to add it here.

It will be removed via our changes, so should be fine

**Comment by sribalij** [comment]
> 

Yes, that's one reason we had to add it there.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/trigger_info.proto` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/52153#-NdnNnPq3mp4blA1e4_P:-NdnWmSW4HzrBhy4PA2z:bxg8qav) ([raw file](https://github.com/harness/harness-core/blob/6fb503a185905f5fd2bfc68de370acc02afea58b/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/trigger_info.proto#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This ExecutionTrigger info is already stored in PipelineExecutionSummaryEntity, i don't think in this PR they can remove easily.

plus they need in execution summary API, so for now they need to add it here.

It will be removed via our changes, so should be fine
</blockquote></details>

sure, thanks for the clarification.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52153)* status: Some of the checks are too old. 1. unresolved discussions.

**Pull request merged**
