### PR TITLE
[feat]: [PL-30089]: Adding support of max length of 128 for Identifier and Name for all entities.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Adding support of max length of 128 for Identifier and Name for all entities.
Removing checks of Max Length as input parameter for File, Secrets and Connectors.

## Checklist
- [X] I've documented the changes in the PR description.
- [] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/43027#-NMbozNN7cfUuFo1BsaI:-NMbozNN7cfUuFo1BsaJ:bqbjd69) ([raw file](https://github.com/harness/harness-core/blob/f59ae43e8d9c22545d36c94ea047506b6aa07591/970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java#L19)):*
> ```Java
>   private static final String ALLOWED_CHARS_STRING =
>       "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_. /";
>   private static final int MAX_ALLOWED_LENGTH = 64;
> ```

are we going to make the change for 128 in a separate PR ?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/43027#-NMbozNN7cfUuFo1BsaI:-NMcsxzR8Vlun9pOKa32:b-wj5evd) ([raw file](https://github.com/harness/harness-core/blob/f59ae43e8d9c22545d36c94ea047506b6aa07591/970-ng-commons/src/main/java/io/harness/data/validator/NGEntityNameValidator.java#L19)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we going to make the change for 128 in a separate PR ?
</blockquote></details>

was yet to make that change.  change done. Testing is still pending.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 9 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Some of the checks are too old. 15 file(s) to review. 0 of 2 approvals obtained.

**Comment by Jimit09Gandhi** [comment]
trigger ft2

**Comment by Jimit09Gandhi** [comment]
trigger ti3

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: 52 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Waiting on team(s): sto.

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Waiting on team(s): sto.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Waiting on team(s): sto.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Waiting on team(s): sto.

**Review by inderschera — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: Waiting on team(s): sto.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027#-:-NNYFafV5k8J4ZJ9op98:bnfp4nl)* status: Waiting on team(s): sto.

**Review by r0610205 — APPROVED** [review]

**Review by ankit-harness — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 19 of 35 files at r6, 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43027)* status: :shipit: complete! ✓

**Pull request merged**
