### PR TITLE
feat: [CCM-8315]: [CCM]: Remove GRPC call between watcher, delegate and event-service

### PR DESCRIPTION
**Pull request by trunapushpa**
## Describe your changes
- Added rest support in CE Event Service
- Removed ChronicleEventTailer from watcher
- GRPC publish call in ChronicleEventTailer updated to Rest Proto
- Only delegate makes rest call to CE Event Service to publish messages

## Testing done
- Tested on Pre-QA environment
- Checked for backward compatibility
    - [x] Delegate is running an older version and Event Service is running an updated version
    - [x] Event Service is running an older version and Delegate is running an updated version

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 25 Issues 
* Vulnerability 17 Vulnerabilities 
 * Code issue 8 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36023)

**Comment by jennyjames21** [comment]
*[`260-delegate/config-delegate.yml` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/36023#-N8eOJ4sA75Zvrd8qBEG:-N8eOJ4sA75Zvrd8qBEH:by1pes9) ([raw file](https://github.com/harness/harness-core/blob/286fc9d0259c8ec60d52a8a15462481c5973af59/260-delegate/config-delegate.yml#L6)):*
> ```YAML
> verificationServiceUrl: https://localhost:7070/verification/
> cvNextGenUrl: https://localhost:6060/cv/api/
> ceEventServiceUrl: https://localhost:7281
> ```

is this new url? if yes, You may also need to make changes to add as part of yaml while delegate download. Ping me if you need more clarification on this

**Comment by jennyjames21** [comment]
*[`970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/36023#-N8eRLwQDZrqQMi3JYmF:-N8eRLwQDZrqQMi3JYmG:bdeh55c) ([raw file](https://github.com/harness/harness-core/blob/286fc9d0259c8ec60d52a8a15462481c5973af59/970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java#L35)):*
> ```Java
>       log.info("Response toString: {}", response.toString());
>       log.info("Response raw.body: {}", response.raw().body());
>       if (response.isSuccessful()) {
> ```

combine to one line due to log cost?

**Comment by jennyjames21** [comment]
*[`970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/36023#-N8eRVAk9IqyLMw6LBGr:-N8eRVAk9IqyLMw6LBGs:bcx5nd7) ([raw file](https://github.com/harness/harness-core/blob/286fc9d0259c8ec60d52a8a15462481c5973af59/970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java#L15)):*
> ```Java
> @OwnedBy(CE)
> @Slf4j
> public class GrpcRestUtils {
> ```

why does it call grpcRestUtil? Should this be EventRestUtil?

**Review by jennyjames21 — COMMENTED** [review]
Note we release watcher separately, it has be backward compatible with event service. 
Also please coordinate with delegate QA team for watcher release.

> Reviewed 12 of 19 files at r1, 6 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023#-:-N8eRhy2AtWeNg4oUeGD:bi0p3cp)* status: 7 file(s) to review. 0 of 1 approvals obtained.

**Review by hitesharinga — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: Some of the checks are too old. 7 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/config-delegate.yml` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/36023#-N8eOJ4sA75Zvrd8qBEG:-N9JTW_39uK1g7GZD9j1:b27qe21) ([raw file](https://github.com/harness/harness-core/blob/286fc9d0259c8ec60d52a8a15462481c5973af59/260-delegate/config-delegate.yml#L6)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

is this new url? if yes, You may also need to make changes to add as part of yaml while delegate download. Ping me if you need more clarification on this
</blockquote></details>

I don't think we need a new url, we can use manager url and in event service we can have ingress rule for / /event-publisher-server

**Comment by trunapushpa** [comment]
trigger authorcheck

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java` line 90 at r9](https://reviewable.io/reviews/harness/harness-core/36023#-NE7rjo15OYhHJ35QtYo:-NE7rjo2DQEnYRfi811i:b-wmi7ie) ([raw file](https://github.com/harness/harness-core/blob/0750f45324095904e48276c7e99299087149c529/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L90)):*
> ```Java
>     final String deployMode = System.getenv(DEPLOY_MODE);
>     if (!isOnPrem(deployMode) && isImmutableDelegate) {
>       final String managerHostAndPort = System.getenv("MANAGER_HOST_AND_PORT");
> ```

why remove isImmutabe?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/eventpublisherclient/EventPublisherClientFactory.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/36023#-NE7rwMUA3anZTSF6W1o:-NE7rwMUA3anZTSF6W1p:b-tv7648) ([raw file](https://github.com/harness/harness-core/blob/ba8d0a2f7d58acf1cfa02ce80763c74113f93222/260-delegate/src/main/java/io/harness/eventpublisherclient/EventPublisherClientFactory.java#L46)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.CE)
> public class EventPublisherClientFactory
> ```

Add @Singleton here to initialize this class only once. Refer recent change on DelegateagentClientModule

**Comment by jennyjames21** [comment]
*[`960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/36023#-NE7sx724omDk4CcTdld:-NE7sx724omDk4CcTdle:bfu5816) ([raw file](https://github.com/harness/harness-core/blob/860ccd427359dfe21a0f1d36353eb66bc3d42ab6/960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java#L59)):*
> ```Java
>     Retrofit retrofit = new Retrofit.Builder()
>                             .baseUrl(baseUrl)
>                             .client(getUnsafeOkHttpClient())
> ```

Can you make getUnsafeOkHttpClient() call only once and assigned to okhttpclient?

Also can you make this class @singleton

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 25 files at r3, 1 of 5 files at r7, 15 of 32 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: 23 file(s) to review. 0 of 1 approvals obtained.

**Review by trunapushpa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: 24 file(s) to review. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java` line 90 at r9](https://reviewable.io/reviews/harness/harness-core/36023#-NE7rjo15OYhHJ35QtYo:-NEARTTg6Zn1xA3ogczl:b-ia8rm8) ([raw file](https://github.com/harness/harness-core/blob/0750f45324095904e48276c7e99299087149c529/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L90)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why remove isImmutabe?
</blockquote></details>

Since we removed the tailer part from watcher, now delegate will run the tailer irrespective of it being immutable or not.
___
*[`260-delegate/src/main/java/io/harness/eventpublisherclient/EventPublisherClientFactory.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/36023#-NE7rwMUA3anZTSF6W1o:-NEARwlu9COd2xiMr0po:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ba8d0a2f7d58acf1cfa02ce80763c74113f93222/260-delegate/src/main/java/io/harness/eventpublisherclient/EventPublisherClientFactory.java#L46)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Add @Singleton here to initialize this class only once. Refer recent change on DelegateagentClientModule
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java` line 59 at r9](https://reviewable.io/reviews/harness/harness-core/36023#-NE7sx724omDk4CcTdld:-NEARvV4ANR9W7u16DXK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/860ccd427359dfe21a0f1d36353eb66bc3d42ab6/960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java#L59)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Can you make getUnsafeOkHttpClient() call only once and assigned to okhttpclient?

Also can you make this class @singleton 
</blockquote></details>

Done.
___
*[`970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/36023#-N8eRVAk9IqyLMw6LBGr:-NEARtRy-0CrBAMcu_t2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/286fc9d0259c8ec60d52a8a15462481c5973af59/970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java#L15)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why does it call grpcRestUtil? Should this be EventRestUtil?
</blockquote></details>

Done.
___
*[`970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/36023#-N8eRLwQDZrqQMi3JYmF:-NEARqaE9pCSIm0qV4oY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/286fc9d0259c8ec60d52a8a15462481c5973af59/970-grpc/src/main/java/io/harness/util/GrpcRestUtils.java#L35)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

combine to one line due to log cost?
</blockquote></details>

Done.

**Review by hitesharinga — DISMISSED** [review]
> Reviewed 1 of 19 files at r1, 7 of 25 files at r3, 1 of 5 files at r7, 28 of 32 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java` line 6 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAdfwK6988nUULLfVN:-NEAdfwK6988nUULLfVO:btlx1zj) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java#L6)):*
> ```Java
>  * that can be found in the licenses directory at the root of this repository, also available at
>  * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
>  */
> ```

We can remove this class from watcher 
___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java` line 24 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAdlYn6VufRN5DxkPI:-NEAdlYn6VufRN5DxkPJ:ba06sgb) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java#L24)):*
> ```Java
> 
>   public WatcherAuthInterceptor(TokenGenerator tokenGenerator) {
>     this.tokenGenerator = tokenGenerator;
> ```

revert this 
___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java` line 10 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAdoZW7PmD7Mr8uqlv:-NEAdoZX2cPIfd6xcJGq:b4wldth) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java#L10)):*
> ```Java
> package io.harness.managerclient;
> 
> import io.harness.eventpublisherclient.EventPublisherClient;
> ```

revert this
___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java` line 32 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAcgTJ8RLw1VumZol9:-NEAcgTJ8RLw1VumZolA:bjb63ur) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java#L32)):*
> ```Java
>     bind(TokenGenerator.class).toInstance(tokenGenerator);
>     bind(ManagerClientV2.class).toProvider(new WatcherManagerClientV2Factory(managerBaseUrl, tokenGenerator));
>     bind(EventPublisherClient.class).toProvider(new WatcherEventPublisherClientFactory(managerBaseUrl, tokenGenerator));
> ```

Can we remove this from watcher?
Since we have moved away from the watcher to publish events.  
___
*[`970-grpc/src/main/java/io/harness/event/client/impl/tailer/ChronicleEventTailer.java` line 173 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAeJpc2O-JCcY83knf:-NEAeJpc2O-JCcY83kng:b-d3z078) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/970-grpc/src/main/java/io/harness/event/client/impl/tailer/ChronicleEventTailer.java#L173)):*
> ```Java
>             log.error("Something wrong with publishing over rest ", e);
>           }
>           blockingStub.withDeadlineAfter(30, TimeUnit.SECONDS).publish(publishRequest);
> ```

Shall we send via grpc for now only if rest is erroring out, otherwise we should not publish via grpc

**Review by trunapushpa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: 4 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java` line 10 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAdoZW7PmD7Mr8uqlv:-NEAmyO91x-Gg9S0uHKT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java#L10)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

revert this
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java` line 32 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAcgTJ8RLw1VumZol9:-NEAnPKA2w-iw9wNNKs0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/managerclient/WatcherManagerClientModule.java#L32)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

Can we remove this from watcher?
Since we have moved away from the watcher to publish events.  
</blockquote></details>

Done.
___
*[`970-grpc/src/main/java/io/harness/event/client/impl/tailer/ChronicleEventTailer.java` line 173 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAeJpc2O-JCcY83knf:-NEAnQhi0-VR0hePaG60:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/970-grpc/src/main/java/io/harness/event/client/impl/tailer/ChronicleEventTailer.java#L173)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

Shall we send via grpc for now only if rest is erroring out, otherwise we should not publish via grpc
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java` line 6 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAdfwK6988nUULLfVN:-NEAnUF0Ca-5OeFASy3x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/eventpublisherclient/WatcherEventPublisherClientFactory.java#L6)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

We can remove this class from watcher 
</blockquote></details>

Done.
___
*[`960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java` line 24 at r10](https://reviewable.io/reviews/harness/harness-core/36023#-NEAdlYn6VufRN5DxkPI:-NEAna_IAO_hlE_axRRR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c6c9445e16e58c5e6552b6820857cde4a29b051/960-watcher/src/main/java/io/harness/managerclient/WatcherAuthInterceptor.java#L24)):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

revert this 
</blockquote></details>

Done.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 6 of 25 files at r3, 15 of 32 files at r9, 2 of 3 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: 10. unresolved discussions. 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: 5. unresolved discussions.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: Some of the checks are too old. 1 change requests. 5. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 658 at r11](https://reviewable.io/reviews/harness/harness-core/36023#-NEdxgTm51JTva7kPUpL:-NEdxgTm51JTva7kPUpM:bv63o73) ([raw file](https://github.com/harness/harness-core/blob/27961bf92d71965b7e81be1cdca7b15e65860a48/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L658)):*
> ```Java
>       }
> 
>       startChroniqleQueueMonitor();
> ```

This is sync call and will cause main thread to wait, can we do it in background ?



_Code quote:_
```Java
startChroniqleQueueMonitor();
```

**Review by trunapushpa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36023)* status: Some of the checks are too old. 1 change requests. 6. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 658 at r11](https://reviewable.io/reviews/harness/harness-core/36023#-NEdxgTm51JTva7kPUpL:-NEokYWEE8MOipx3eqEJ:b-fv1v7q) ([raw file](https://github.com/harness/harness-core/blob/27961bf92d71965b7e81be1cdca7b15e65860a48/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L658)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This is sync call and will cause main thread to wait, can we do it in background ?
</blockquote></details>

`startChroniqleQueueMonitor` is happening in initDelegateProcess and initDelegateProcess is already happening in background.



_Code snippet:_
```Java
// Initialize delegate process in background.
backgroundExecutor.submit(() -> { initDelegateProcess(watched); });      
```

**Pull request merged**
