### PR TITLE
fix: [CDS-40815]: helm FF cleanup 

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes

The new default behaviour (with no FFs enabled) will be to create a cache based on serviceID or envID or a combination of these. 

The old default behaviour in was having one repositories.yaml in the default location (i.e. in  ~/.config/helm/repositories.yaml) 

Also, going forward we will have only one FF called HELM_CACHE_TIED_TO_EXECUTION which will combine the 2 previous FFs, i.e. even after the above changes, if a customer is facing concurrency issues, enabling this will create a new randomised folder for each execution and delete it after the deployment. 

Ref doc: https://harness.atlassian.net/wiki/spaces/CDP/pages/21134344193/Helm+FFs+cleanup

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35701)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35701)

**Comment by achyuth-harness** [comment]
trigger ti0

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35701)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 913 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8S_gDu43X6tnNYT--1:-N8S_gDu43X6tnNYT--2:bw3ocfq) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L913)):*
> ```Java
>     boolean useCache =
>         !cdFeatureFlagHelper.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.HELM_CACHE_TIED_TO_EXECUTION);
>     String repoId = useCache ? infrastructureOutcome.getInfrastructureKey() : ambiance.getPlanExecutionId();
> ```

isn't this only the id of the infrastructure used.
we would need the infrastructure-service-mapping-id .. right ..??



_Code quote:_
```Java
getInfrastructureKey()
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 915 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8S_zYm2KbJi7rTpct0:-N8S_zYm2KbJi7rTpct1:b2sy1jm) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L915)):*
> ```Java
>     String repoId = useCache ? infrastructureOutcome.getInfrastructureKey() : ambiance.getPlanExecutionId();
> 
>     return convertBase64UuidToCanonicalForm(repoId);
> ```

thought ..
instead of UUIDs, can we create repo name (directory name) in some human readable format ..
___
*[`400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8Sb8k3DFL8InPOorEH:-N8Sb8k3DFL8InPOorEI:b-rl33di) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java#L153)):*
> ```Java
>             .encryptedDataDetails(encryptionDataDetails)
>             // TODO(achyuth): confirm if we need appManifestId here or can we use same logic as CDP
>             .repoName(convertBase64UuidToCanonicalForm(appManifestId))
> ```

how is this repo name different from other ones.
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 627 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8ScKFq0TFRiuZoLS_k:-N8ScKFq0TFRiuZoLS_l:b-j89dpc) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L627)):*
> ```Java
>       }
>     } finally {
>       // We do remove repo only when the useFlags FF is on.
> ```

remove/update this comment.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35701)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 913 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8S_gDu43X6tnNYT--1:-N8T46aw9R1-Zkku12X7:b-pdowr9) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L913)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

isn't this only the id of the infrastructure used.
we would need the infrastructure-service-mapping-id .. right ..??
</blockquote></details>

This is for NG, not sure if we have this? (I guess there is some svc - env refactoring going on)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 915 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8S_zYm2KbJi7rTpct0:-N8Szl3O7f-FUutlAfCh:b-iqealz) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L915)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

thought ..
instead of UUIDs, can we create repo name (directory name) in some human readable format ..
</blockquote></details>

We have repo display name for this
___
*[`400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java` line 153 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8Sb8k3DFL8InPOorEH:-N8T4L_p7Qjt0PwTrKoZ:b-haew7d) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java#L153)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

how is this repo name different from other ones.
</blockquote></details>

This is actually used by CDC. So need them to confirm
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 627 at r3](https://reviewable.io/reviews/harness/harness-core/35701#-N8ScKFq0TFRiuZoLS_k:-N8Sv3oS7CMQ_8Fk4iK4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5747a8d831101592b32e323f697013e31d95e0e/930-delegate-tasks/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L627)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

remove/update this comment.
</blockquote></details>

Done.

**Review by shubham-in10se — DISMISSED** [review]
> Reviewed 2 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35701)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java` line 160 at r5](https://reviewable.io/reviews/harness/harness-core/35701#-N8TcTXc0JGD_IupaGrQ:-N8TcTXdCN5-kzcnbG4U:b-xyjbv8) ([raw file](https://github.com/harness/harness-core/blob/368a2ee3f5fc0d5cc11977ca13560fe78497be3a/400-rest/src/main/java/software/wings/service/impl/applicationmanifest/ManifestCollectionUtils.java#L160)):*
> ```Java
>             .bypassHelmFetch(featureFlagService.isEnabled(FeatureName.BYPASS_HELM_FETCH, accountId))
>             .useRepoFlags(true)
>             .deleteRepoCacheDir(true)
> ```

if this is for the background job which collects manifest details every 90 secs, then I think it'll be better to let this use a common cache dir which is not cleaned up everytime.



_Code quote:_
```Java
            .useRepoFlags(true)
            .deleteRepoCacheDir(true)
```

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35701)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger codebasehash

**Pull request merged**
