### PR TITLE
feat: [PL-26173]: fix gitConnectionUrl and fileUrl for ADO

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
fix gitConnectionUrl and fileUrl for ADO
Tested - 
1. CRUD pipeline operations with http project type connector
2. fileUrl for http proejct type connector
3. CRUD pipeline operations with http repo type connector
4. fileUrl for http repo type connector

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35163)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35163)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/35163#-N6SNrhe-S3p0aHBCnH3:-N6SNrhe-S3p0aHBCnH4:bmzdqvv) ([raw file](https://github.com/harness/harness-core/blob/f7d27fb3a4fa15b14651ec601c3de914f04d8f80/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L165)):*
> ```Java
>     String repoUrl = removeStartingAndEndingSlash(getGitConnectionUrl(gitRepositoryDTO));
>     String httpRepoUrl = GitClientHelper.getCompleteHTTPUrlForAzureRepo(repoUrl);
>     log.info("{}", httpRepoUrl);
> ```

Add more info here

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35163)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 557 at r1](https://reviewable.io/reviews/harness/harness-core/35163#-N6SNxFbD9Rt6LC3mLjy:-N6SNxFbD9Rt6LC3mLjz:bpnvuh1) ([raw file](https://github.com/harness/harness-core/blob/f7d27fb3a4fa15b14651ec601c3de914f04d8f80/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L557)):*
> ```Java
> 
>   public static String getCompleteHTTPUrlForAzureRepo(String url) {
>     final String AZURE_REPO_URL = "https://dev.azure.com";
> ```

Will it be always dev.azure.com. Whether azure supports on prem ?

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35163)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 561 at r1](https://reviewable.io/reviews/harness/harness-core/35163#-N6SOB7p71aH-0smGGi5:-N6SOB7p71aH-0smGGi6:b-sr9334) ([raw file](https://github.com/harness/harness-core/blob/f7d27fb3a4fa15b14651ec601c3de914f04d8f80/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L561)):*
> ```Java
>     String gitRepoProject = getGitRepo(url);
>     List<String> parts = Arrays.asList(gitRepoProject.split("/"));
>     if (parts.size() < 2) {
> ```

If it is a project type connector then the parts size would be 1

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35163)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/35163#-N6SNrhe-S3p0aHBCnH3:-N6SUFAu9BJEXvOfdBTS:b-4uceff) ([raw file](https://github.com/harness/harness-core/blob/f7d27fb3a4fa15b14651ec601c3de914f04d8f80/954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/azurerepo/AzureRepoConnectorDTO.java#L165)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Add more info here
</blockquote></details>

removed it, added for testing
___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 557 at r1](https://reviewable.io/reviews/harness/harness-core/35163#-N6SNxFbD9Rt6LC3mLjy:-N6SUHhuC-5mix7TZk3c:b-60xwzo) ([raw file](https://github.com/harness/harness-core/blob/f7d27fb3a4fa15b14651ec601c3de914f04d8f80/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L557)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Will it be always dev.azure.com. Whether azure supports on prem ?
</blockquote></details>

this method is for Saas only, changed method name to make it clear
___
*[`960-api-services/src/main/java/io/harness/git/GitClientHelper.java` line 561 at r1](https://reviewable.io/reviews/harness/harness-core/35163#-N6SOB7p71aH-0smGGi5:-N6SUQRmEl7utwTxEJXr:b1o2mw1) ([raw file](https://github.com/harness/harness-core/blob/f7d27fb3a4fa15b14651ec601c3de914f04d8f80/960-api-services/src/main/java/io/harness/git/GitClientHelper.java#L561)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

If it is a project type connector then the parts size would be 1
</blockquote></details>

this will convert repoUrl only.

**Review by adivishy1 — APPROVED** [review]

**Comment by bhavya181** [comment]
trigger messagecheck

**Pull request merged**
