### PR TITLE
fix: [PL-40130]: Add NGAccessDeniedException when user don't have access to create/list api key

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
-Add NGAccessDeniedException when user dont have access to create api key or see list of api keys

Test
-Local Test

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50989)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50989)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java` line 319 at r1](https://reviewable.io/reviews/harness/harness-core/50989#-NaHhcKz71OWMrGg417n:-NaHhcKz71OWMrGg417o:b-48d2vw) ([raw file](https://github.com/harness/harness-core/blob/8bd45f53b243a0ee816e6b189f233d767e9c5478/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java#L319)):*
> ```Java
>         if (!userId.get().equals(parentIdentifier)) {
>           throw new NGAccessDeniedException(String.format("User [%s] not authenticated to create api key for user [%s]",
>                                                 userId.get(), parentIdentifier),
> ```

Lets print email of User instead userId for readability to customer.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java` line 336 at r1](https://reviewable.io/reviews/harness/harness-core/50989#-NaHhpDgC-fe8xVR3G14:-NaHhpDgC-fe8xVR3G15:b-48d2vw) ([raw file](https://github.com/harness/harness-core/blob/8bd45f53b243a0ee816e6b189f233d767e9c5478/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java#L336)):*
> ```Java
>           throw new NGAccessDeniedException(
>               String.format(
>                   "User [%s] is not authorized to create ApiKey for account: [%s]", userId.get(), accountIdentifier),
> ```

Lets print email of User instead userId for readability to customer.

**Comment by jennyjames21** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/50989)_ status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java` line 319 at r1](https://reviewable.io/reviews/harness/harness-core/50989#-NaHhcKz71OWMrGg417n:-NaHhcKz71OWMrGg417o:b-48d2vw) ([raw file](https://github.com/harness/harness-core/blob/8bd45f53b243a0ee816e6b189f233d767e9c5478/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java#L319)):_
> 
> > ```java
> >         if (!userId.get().equals(parentIdentifier)) {
> >           throw new NGAccessDeniedException(String.format("User [%s] not authenticated to create api key for user [%s]",
> >                                                 userId.get(), parentIdentifier),
> > ```
> 
> Lets print email of User instead userId for readability to customer.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java` line 336 at r1](https://reviewable.io/reviews/harness/harness-core/50989#-NaHhpDgC-fe8xVR3G14:-NaHhpDgC-fe8xVR3G15:b-48d2vw) ([raw file](https://github.com/harness/harness-core/blob/8bd45f53b243a0ee816e6b189f233d767e9c5478/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/ApiKeyServiceImpl.java#L336)):_
> 
> > ```java
> >           throw new NGAccessDeniedException(
> >               String.format(
> >                   "User [%s] is not authorized to create ApiKey for account: [%s]", userId.get(), accountIdentifier),
> > ```
> 
> Lets print email of User instead userId for readability to customer.

Exception is when userAccount is null, so the only information available is user id.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50989#-:-NaSdCBc3XYsN7WNPYsK:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
