### PR TITLE
[feat]: [CDS-70592]: Move the execution-audits setting-service call to ExecutionHelper and refactor

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48466)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48466)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 1 of 1 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48466)* status: 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/48466#-NWbB-QK0yII91E8Z8qs:-NWbB-QK0yII91E8Z8qt:b-p4e2lq) ([raw file](https://github.com/harness/harness-core/blob/44642788a425d7f48ab3bf49c5202f8c5a423f2e/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java#L92)):*
> ```Java
> 
>     Map<String, Object> strategyObjectMap = StrategyUtils.fetchStrategyObjectMap(stepLevelsWithStrategyMetadata,
>         AmbianceUtils.checkIfSettingEnabled(
> ```

@brijeshdhakar i think we should have simpler util exposed here -> caller should not pass ff

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48466)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/48466#-NWbB-QK0yII91E8Z8qs:-NWbVZff9NJcJPJ6E1gs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44642788a425d7f48ab3bf49c5202f8c5a423f2e/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@brijeshdhakar i think we should have simpler util exposed here -> caller should not pass ff
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48466)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ut1 ut3 messagecheck

**Comment by brijeshdhakar** [comment]
trigger ut1

**Comment by brijeshdhakar** [comment]
trigger ut1

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48466)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger ut1

**Comment by brijeshdhakar** [comment]
trigger review

**Comment by brijeshdhakar** [comment]
trigger ut1

**Pull request merged**
