### PR TITLE
fix: [CDS-41393]: add unitProgressData in case of failure in CustomMa…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…nifestFetchTaskNG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36067)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36067)

**Review by GoelPratyush99 — APPROVED** [review]

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36067)* status: Some of the checks are too old. 2 file(s) to review. 1 change requests. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 711 at r1](https://reviewable.io/reviews/harness/harness-core/36067#-N8wCG1s2lELiQsbh7_L:-N8wCG1s2lELiQsbh7_M:b-m13u09) ([raw file](https://github.com/harness/harness-core/blob/9d9c7b47b572ce231bdfcce97413c02cc8f9147b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L711)):*
> ```Java
>         (CustomManifestValuesFetchResponse) responseData;
> 
>     if (customManifestValuesFetchResponse.getCommandExecutionStatus() != SUCCESS) {
> ```

actually any failure should be handled as part of error framework, so you don't need commandExecutionStatus anymore. If there is a failure then it should throw an exception instead. Exception should be wrapped in TaskNGDataException where you can pass command unit progress. This will automatically handle unit progress for you

**Comment by abosii-harness** [comment]
trigger feature-build

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36067)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 711 at r1](https://reviewable.io/reviews/harness/harness-core/36067#-N8wCG1s2lELiQsbh7_L:-N8xc2688OZGsxUQOtP4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d9c7b47b572ce231bdfcce97413c02cc8f9147b/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L711)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

actually any failure should be handled as part of error framework, so you don't need commandExecutionStatus anymore. If there is a failure then it should throw an exception instead. Exception should be wrapped in TaskNGDataException where you can pass command unit progress. This will automatically handle unit progress for you
</blockquote></details>

Done.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36067)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/36067#-N90WQY41joi2DH9pQnD:-N90WOI206gMNjJFJaGw:b-9qojef) ([raw file](https://github.com/harness/harness-core/blob/7489746cd74f906450b3df3455ae5b7280682466/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L156)):*
> ```Java
>           LogLevel.ERROR, FAILURE);
>       return CustomManifestValuesFetchResponse.builder()
>           .unitProgressData(UnitProgressDataMapper.toUnitProgressData(commandUnitsProgress))
> ```

Why are we not throwing TaskNGDataException here unlike above?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36067)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java` line 156 at r3](https://reviewable.io/reviews/harness/harness-core/36067#-N90WQY41joi2DH9pQnD:-N90agZdE2Ma7vMLbCDi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7489746cd74f906450b3df3455ae5b7280682466/930-delegate-tasks/src/main/java/io/harness/delegate/task/manifests/CustomManifestFetchTaskNG.java#L156)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Why are we not throwing TaskNGDataException here unlike above?
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36067#-:-N91G2bo7crEQ-Q8SPB8:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36067)* status: 1. unresolved discussions.

**Review by GoelPratyush99 — APPROVED** [review]

**Pull request merged**
