### PR TITLE
fix: [CDS-74129]: do not filter pipeline yaml for rollback

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Service plan creator needs other stage yaml when creating plan for the stage being rolled back which is using useFromStage to define service.
Since we have the stage FQNs to rollback already, we are not processing YAML before plan creation. 
Then RollbackModeExecutionHelper uses stage FQNs to transform the plan. 

Scenarios tested:
1. Single stage post prod rollback 
2. Pipeline rollback 
3. Multiple infra/instances deployed 
4. Parallel stage deployment and rollback 
5. Serial stage deployment and rollback 
6. Use from stage and new service deployment

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50557)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/50557#-N_Xj8eX71tkZsE-4nSP:-N_Xj8eX71tkZsE-4nSQ:b-5ns8nb) ([raw file](https://github.com/harness/harness-core/blob/485228cc987dc1fda24cda71169a7b0040a45f07/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java#L146)):*
> ```Java
> 
>   void handleSerialStage(JsonNode currentNode, List<String> executedStages, ArrayNode reversedStages) {
>     String stageId = currentNode.get(YAMLFieldNameConstants.STAGE).get(YAMLFieldNameConstants.IDENTIFIER).asText();
> ```

why did we remove this?

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50557)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/50557#-N_Xj8eX71tkZsE-4nSP:-N_XniD_7XFkDfLMSTsx:b1vxfnz) ([raw file](https://github.com/harness/harness-core/blob/485228cc987dc1fda24cda71169a7b0040a45f07/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java#L146)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why did we remove this?
</blockquote></details>

In both serial and parallel stages, we just need to add the node. We don't need to match with stage ids to add only those stages.
Addition in reverse order is handled by the parent method.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50557)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50557)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger ti5, ti6, ti7, ti8, ti9

**Comment by hingerabhinav** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50557)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
