### PR TITLE
techdebt: [DEL-5610]: mongo free 959-common-entities

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Created granular build files for 959-common-entities and in the process trimmed down its dependencies on 960-persistence.

In 960-persistence, created sub-packages for non-mongo dependent code which are referred to in 959-common-entities. 

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41774)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 17 of 680 files at r1, 663 of 663 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41774)* status: :shipit: complete! ✓

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41774)* status: :shipit: complete! ✓

___
*[`959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/41774#-NJitGuiBC5bnDwoZ8ni:-NJitGuj5ZNK1Jt_x_xB:bmvxvoo) ([raw file](https://github.com/harness/harness-core/blob/9e05d76bc7fa606cff0495f03d0bc8c23d3153e6/959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java#L22)):*
> ```Java
>       ImmutableSet.<Class<? extends KryoRegistrar>>builder()
>           .addAll(PersistenceRegistrars.kryoRegistrars)
>           .add(CommonEntitiesKryoRegistrar.class)
> ```

Would it be simpler if we just move even `add(CommonEntitiesKryoRegistrar.class)` to CvNextGenCommonsRegistrar.java and get away with this class ?
___
*[`959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/41774#-NJitaTmApsCvUzRhhT2:-NJitaTmApsCvUzRhhT3:b-4yccg6) ([raw file](https://github.com/harness/harness-core/blob/9e05d76bc7fa606cff0495f03d0bc8c23d3153e6/959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java#L28)):*
> ```Java
>       ImmutableSet.<Class<? extends MorphiaRegistrar>>builder()
>           .addAll(PersistenceRegistrars.morphiaRegistrars)
>           .add(CommonEntitiesMorphiaRegister.class)
> ```

Would it be simpler if we just move even `add(CommonEntitiesMorphiaRegistrar.class)` to CvNextGenCommonsRegistrar.java and get away with this class ? Since this class is in outer folder it will also cause issues while adding build files ?

**Review by gn-harness — COMMENTED** [review]
> Reviewed 15 of 680 files at r1, 24 of 663 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41774)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/41774#-NJitGuiBC5bnDwoZ8ni:-NJlQ9EK3s7VKJSD-hTe:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9e05d76bc7fa606cff0495f03d0bc8c23d3153e6/959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java#L22)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Would it be simpler if we just move even `add(CommonEntitiesKryoRegistrar.class)` to CvNextGenCommonsRegistrar.java and get away with this class ?
</blockquote></details>

Done
___
*[`959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/41774#-NJitaTmApsCvUzRhhT2:-NJlQA7H1wV25BLoPMwg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/9e05d76bc7fa606cff0495f03d0bc8c23d3153e6/959-common-entities/src/main/java/io/harness/serializer/CommonEntitiesRegistrars.java#L28)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

Would it be simpler if we just move even `add(CommonEntitiesMorphiaRegistrar.class)` to CvNextGenCommonsRegistrar.java and get away with this class ? Since this class is in outer folder it will also cause issues while adding build files ?
</blockquote></details>

Done

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 13 of 680 files at r1, 663 of 663 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41774)* status: :shipit: complete! ✓

**Pull request merged**
