### PR TITLE
[fix]: [PL-23129]: Added null check to fix the failing branch sync for a newly created repo

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Added null check to fix the failing branch sync for a newly created repo

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30990)

### CODE REVIEW

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30990)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java, line 175 at r1](https://reviewable.io/reviews/harness/harness-core/30990#-MwgRsxHCu4SyqO7fJmg:-MwgzVD9AvdXZkFWFVrK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3a26003fe9fac52cc20246e663f9691433e4102f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java#L175)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

@Meet Rathod Please add the UT. Since the main public function(processBranchSyncEvent) is a big function, we might have to mock a lot of dependencies. It might make our UT complex. 
</blockquote></details>

Done.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30990)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java, line 183 at r3](https://reviewable.io/reviews/harness/harness-core/30990#-MwkkfAS1g8KwkBXKDSh:-MwkkfAS1g8KwkBXKDSi:b-p8raoz) ([raw file](https://github.com/harness/harness-core/blob/9780132b4920bdc5d67791b64264533e9f47d26f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java#L183)):*
> ```Java
>             -> scmClientFacilitatorService.findCommitById(yamlGitConfig, commitId),
>             yamlGitConfig.getProjectIdentifier(), yamlGitConfig.getOrganizationIdentifier(), accountIdentifier)
>         .getMessage();
> ```

what happens to this message if commit id is not found?

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java, line 183 at r3](https://reviewable.io/reviews/harness/harness-core/30990#-MwkkfAS1g8KwkBXKDSh:-MwkkkeL0QkKHPyg89l6:b-prn8gs) ([raw file](https://github.com/harness/harness-core/blob/9780132b4920bdc5d67791b64264533e9f47d26f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java#L183)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what happens to this message if commit id is not found?
</blockquote></details>

what do we return for an invalid commit id?

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java, line 183 at r3](https://reviewable.io/reviews/harness/harness-core/30990#-MwkkfAS1g8KwkBXKDSh:-Mwl3YTt95gV1O-58D7d:bh6eqwa) ([raw file](https://github.com/harness/harness-core/blob/9780132b4920bdc5d67791b64264533e9f47d26f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitBranchSyncServiceImpl.java#L183)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what do we return for an invalid commit id?
</blockquote></details>

Please check more on this as discussed on call. Approving for now.



_Code quote:_
```Java
getCommitMessage
```

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30990#-:-Mwl3jEYEU9ckpWw0l9c:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
