### PR TITLE
fix: [CDS-73695]: Adding handling for expire event seperately for shell sc…

### PR DESCRIPTION
**Pull request by Y0709**
…ript then using handle abort

Issue -- Earlier we used the handling for abort interrupt event for expire interrupt event as well but that created an issue for approval steps as we mark approval instances as aborted in the final handle abort method which we can do in case of an expire.
We have defined interface for handling expire events for all steps. We have handled expire event for shell script in this pr and added default empty method. This can be used by steps handle expire event as they like in future.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51170)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51170)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51170)* status: :shipit: complete! ✓

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/interrupt/InterruptEventHandler.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/51170#-Nafh_TIDf9LIjhKcfBR:-Nafh_TIDf9LIjhKcfBS:b-7uiyo9) ([raw file](https://github.com/harness/harness-core/blob/3d710eab6dc4fac83d8c46fba695dd243e795752/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/interrupt/InterruptEventHandler.java#L139)):*
> ```Java
>       log.error("Handling expire at sdk failed with interrupt event - {} ", event.getInterruptUuid(), ex);
>       // Even if error send feedback
>       pmsInterruptService.handleExpire(event.getNotifyId());
> ```

nit: Can we move the `pmsInterruptService.handleExpire(event.getNotifyId());` to the finally block? Its being executed in If, else and catch blocks. So moving to finally would be better. @archit-harness what do you think?

**Comment by Y0709** [comment]
trigger ut1

**Comment by Y0709** [comment]
trigger ut5, ut6

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51170)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/interrupt/InterruptEventHandler.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/51170#-Nafh_TIDf9LIjhKcfBR:-NafqNXr8uULMmOwjFen:b-u6wvpl) ([raw file](https://github.com/harness/harness-core/blob/3d710eab6dc4fac83d8c46fba695dd243e795752/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/interrupt/InterruptEventHandler.java#L139)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

nit: Can we move the `pmsInterruptService.handleExpire(event.getNotifyId());` to the finally block? Its being executed in If, else and catch blocks. So moving to finally would be better. @archit-harness what do you think?
</blockquote></details>

yes, looks clean, here we are not handling exception thrown by handleExpire, but that was true before as well, thus makes sense

**Comment by Y0709** [comment]
trigger ut7

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51170)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
Approved this PR. But @yuvrajharness please add unit-tests for the new code in subsequent PR.

**Comment by Y0709** [comment]
trigger review

**Pull request merged**
