### PR TITLE
feat: [DEL-5524]: smp use variable in configMap to toggle immutable delegate

### PR DESCRIPTION
**Pull request by AnupamIO**
- On SMP, immutable delegate can be toggled using variable: IMMUTABLE_DELEGATE_ENABLED present in manager's configMap.
- Default value of IMMUTABLE_DELEGATE_ENABLED will be set to empty string "" in configMap.
- To toggle, mention true/false then restart manager pod.

Testing:
tested by deploying image: 77622 on : https://smp-istio.qa.harness.io/#/account/d4aiiwamSsKzDSRSKdHAOQ/settings/resources/delegates/list

on toggling I was able to see correct UI and harness-delegate.yaml file.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41383)

### CODE REVIEW

**Review by arya-harness — APPROVED** [review]

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41383)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41383)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2045 at r1](https://reviewable.io/reviews/harness/harness-core/41383#-NJ3jdVM0Iq-NGIQaJ41:-NJ3jdVM0Iq-NGIQaJ42:bxyg5w5) ([raw file](https://github.com/harness/harness-core/blob/861271c318a1cbbf31b1b342994f3170a3ec37a5/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2045)):*
> ```Java
> 
>     // immutable delegate for ON-PREM is toggled using variable IMMUTABLE_DELEGATE_ENABLED in manager configMap
>     if (DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
> ```

May be just reverse if condition to have better code readability.
 if (!DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
    return immutableDelegateEnabledInDb;
}
// Rest of your code



_Code quote:_
```Java
if (DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
```

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41383)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2045 at r1](https://reviewable.io/reviews/harness/harness-core/41383#-NJ3jdVM0Iq-NGIQaJ41:-NJ45nfp-BFZZHcIc5eb:b-tbv92t) ([raw file](https://github.com/harness/harness-core/blob/861271c318a1cbbf31b1b342994f3170a3ec37a5/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2045)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

May be just reverse if condition to have better code readability.
 if (!DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
    return immutableDelegateEnabledInDb;
}
// Rest of your code
</blockquote></details>

Kept it this way because anyways we need to return DB entry if value is not present in ConfigMap. If I change according to above comment it will boil down to below which looks untidy.

if (!DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
   return immutableDelegateEnabledInDb;
}
if(Value if present in config) {
         return ConfigEntry;
}
return immutableDelegateEnabledInDb;

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41383)* status: :shipit: complete! ✓

**Comment by AnupamIO** [comment]
trigger featurenamecheck

**Pull request merged**
