### PR TITLE
[feat]: [BT-1426]: Optimising dockerfiles

### PR DESCRIPTION
**Pull request by diptiman-adak**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34781)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Test build: https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/diptiman_test/executions/-hCrVPpFT_KTQY2aWoxnmw/pipeline?stage=7Vs71hYOScGNT2aOmWPU4Q&step=3gBq3invSxCZuEFZ_Rj3IQ

Test Deployment:

https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/cd/orgs/default/projects/PREQA_NG_Pipelines/pipelines/PR_Harness/executions/MZ9oo8XyTxKzAjQ3_K2RJA/pipeline?step=LUkFUB3FTQKm9TdCjSDKDw&stage=GmmOxaKFTua-uAYz5GF_9g

 

Successful deployment: [https://console.cloud.google.com/kubernetes/workload/overview?project=platform-205701&pageState=("savedViews":("i":"dc53b031187d49c4a8223451bf26db40","c":["gke%2Fus-west1-b%2Fplatform-pr-cluster"],"n":["bt-1426"]))](https://console.cloud.google.com/kubernetes/workload/overview?project=platform-205701&pageState=(%22savedViews%22:(%22i%22:%22dc53b031187d49c4a8223451bf26db40%22,%22c%22:%5B%22gke%2Fus-west1-b%2Fplatform-pr-cluster%22%5D,%22n%22:%5B%22bt-1426%22%5D)))

**Comment by diptiman-adak** [comment]
trigger ti2

**Review by USB-05 — APPROVED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34781)* status: :shipit: complete! ✓

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34781)* status: :shipit: complete! ✓

___
*[`dockerization/base-images/apm/inject-onprem-apm-bins-into-dockerimage.sh` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/34781#-N5iGoy456Sy5JA-D0QK:-N5iGoy57EoqtDC9zmmb:b-8bud7x) ([raw file](https://github.com/harness/harness-core/blob/61ac16a6ee1cd6a1e4bef784a2632e4f5b623efc/dockerization/base-images/apm/inject-onprem-apm-bins-into-dockerimage.sh#L20)):*
> ```Shell
> }
> 
> export OCELET_AGENT='https://github.com/inspectIT/inspectit-ocelot/releases/download/1.16.0/inspectit-ocelot-agent-1.16.0.jar'
> ```

Should'nt this be coming via Base image
___
*[`dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/34781#-N5iHBi6-iiXozGTjuqZ:-N5iHBi6-iiXozGTjuq_:b-l1lfjn) ([raw file](https://github.com/harness/harness-core/blob/61ac16a6ee1cd6a1e4bef784a2632e4f5b623efc/dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh#L27)):*
> ```Shell
> }
> 
> export APPD_AGENT='https://harness.jfrog.io/artifactory/BuildsTools/docker/apm/appd/AppServerAgent-1.8-21.11.2.33305.zip'
> ```

Here also should'nt we be taking this from base image

**Comment by diptiman-adak** [comment]
*[`dockerization/base-images/apm/inject-onprem-apm-bins-into-dockerimage.sh` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/34781#-N5iGoy456Sy5JA-D0QK:-N5n2-glBO7JrzLsiHMo:bqdtwqq) ([raw file](https://github.com/harness/harness-core/blob/61ac16a6ee1cd6a1e4bef784a2632e4f5b623efc/dockerization/base-images/apm/inject-onprem-apm-bins-into-dockerimage.sh#L20)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Should'nt this be coming via Base image
</blockquote></details>

Adding the binaries into the base would have easiest solution to implement for us. However there are few reasons I have kept it out of the base image:
1. Bloated base image - It will reach to 600-700mb
2. We need to maintain two base one for the on-prem and another for Saas
3. All apps who inherit the base image will have same binaries, you need to delete it separately. But layer size won't reduce for docker. Image will be of large size
4. We need to maintain two different docker files for all the applications. 

With the current approach there is advantage:
1. Single image and dockerfile for base images and applications
2. Reduced docker image size

**Review by diptiman-adak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34781)* status: 1 change requests. 2. unresolved discussions. 

___
*[`dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/34781#-N5iHBi6-iiXozGTjuqZ:-N5n3y1t9ahzNswGrg_t:b-1ldtvw) ([raw file](https://github.com/harness/harness-core/blob/61ac16a6ee1cd6a1e4bef784a2632e4f5b623efc/dockerization/base-images/apm/inject-saas-apm-bins-into-dockerimage.sh#L27)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Here also should'nt we be taking this from base image
</blockquote></details>

Ditto as the other one

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34781)* status: :shipit: complete! ✓

**Pull request merged**
