### PR TITLE
feat: [CDS-42749]: support variable creator for artifact sources

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes

- [x] Add expressions for artifact sources through variable creator
- [x] Fix NPE with Infrastructure outcome generation which happens in variable creation flow

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38069)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 1 Code issues 
* Anti-pattern 2 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38069)

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38069)* status: 16 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/38069#-NDBjbSy9HRKnzNOOXMz:-NDBjbSy9HRKnzNOOXN-:brsl1tk) ([raw file](https://github.com/harness/harness-core/blob/bb26f45dad639b3618470406f101e9e4d43cf65f/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L80)):*
> ```Java
>       case InfrastructureKind.KUBERNETES_DIRECT:
>         K8SDirectInfrastructure k8SDirectInfrastructure = (K8SDirectInfrastructure) infrastructure;
>         validateK8sDirectInfrastructure(k8SDirectInfrastructure);
> ```

removed validations from this method and moved them to a new class "InfrastructureValidator" because this was violating the single responsibility principle
Also started calling the new validation method from all the callers of ```toOutcome``` to retain the current behaviour

**Review by inderschera — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38069)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 239 at r1](https://reviewable.io/reviews/harness/harness-core/38069#-NDBlCDS728qmoCvprng:-NDBlCDS728qmoCvprnh:b-d8qrxs) ([raw file](https://github.com/harness/harness-core/blob/cc410985e9620adb95b68f41e89566daae9b3ac3/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L239)):*
> ```Java
>                                              : null))
>         .registryHostname(garDelegateResponse != null
>                 ? garDelegateResponse.getBuildDetails().getMetadata().get("registryHostname")
> ```

chance of npe here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java` line 488 at r1](https://reviewable.io/reviews/harness/harness-core/38069#-NDBlPr70bqZ7RCmhDP1:-NDBlPr70bqZ7RCmhDP2:b-dljsu1) ([raw file](https://github.com/harness/harness-core/blob/cc410985e9620adb95b68f41e89566daae9b3ac3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java#L488)):*
> ```Java
>           } else if (isNotEmpty(primaryArtifact.getSources())) {
>             primaryArtifact.getSources().forEach(
>                 s -> populateExpressionsForArtifact(outputProperties, s.getSpec(), expressions));
> ```

With this, can there be duplicate auto suggestions if 2 sources of same type exist?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java` line 488 at r1](https://reviewable.io/reviews/harness/harness-core/38069#-NDBlPr70bqZ7RCmhDP1:-NDBouLd-5HO1YYpQzij:badp2qw) ([raw file](https://github.com/harness/harness-core/blob/cc410985e9620adb95b68f41e89566daae9b3ac3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/DeploymentStageVariableCreator.java#L488)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

With this, can there be duplicate auto suggestions if 2 sources of same type exist?
</blockquote></details>

using a set for the same purpose

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38069)* status: 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 239 at r1](https://reviewable.io/reviews/harness/harness-core/38069#-NDBlCDS728qmoCvprng:-NDBqmRC2Kb6c4IohByp:bstkqrg) ([raw file](https://github.com/harness/harness-core/blob/cc410985e9620adb95b68f41e89566daae9b3ac3/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L239)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

chance of npe here?
</blockquote></details>

there was already a NPE :p I fixed it

**Review by inderschera — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38069)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38069)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 239 at r3](https://reviewable.io/reviews/harness/harness-core/38069#-NDCrY749q3vLlapbPaT:-NDCrY765jR1UQbF_UoB:b1wdlzd) ([raw file](https://github.com/harness/harness-core/blob/b1116185d620beef7d3164994ea9b2ba3c1f740d/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L239)):*
> ```Java
>                                              : null))
>         .registryHostname(garDelegateResponse != null
>                 ? garDelegateResponse.getBuildDetails().getMetadata().get("registryHostname")
> ```

Minor - i guess garDelegateResponse.getBuildDetails() or garDelegateResponse.getBuildDetails().getMetadata() cannot be null
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java` line 240 at r3](https://reviewable.io/reviews/harness/harness-core/38069#-NDCrvQ--okKts9WeVRK:-NDCrvQ--okKts9WeVRL:b-4jcldo) ([raw file](https://github.com/harness/harness-core/blob/b1116185d620beef7d3164994ea9b2ba3c1f740d/125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java#L240)):*
> ```Java
>         .registryHostname(garDelegateResponse != null
>                 ? garDelegateResponse.getBuildDetails().getMetadata().get("registryHostname")
>                 : "")
> ```

Minor - I know that it's better to put "" instead of null, preventing NPE, but here if get("registryHostname") returns null, the consumer has to take care of real value, "" and null.   Maybe put null instead of empty string.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/38069#-NDBjbSy9HRKnzNOOXMz:-NDCtfnw08hzCVaJctZX:b-83sjoh) ([raw file](https://github.com/harness/harness-core/blob/bb26f45dad639b3618470406f101e9e4d43cf65f/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L80)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

removed validations from this method and moved them to a new class "InfrastructureValidator" because this was violating the single responsibility principle
Also started calling the new validation method from all the callers of ```toOutcome``` to retain the current behaviour
</blockquote></details>

Nice!

**Pull request merged**
