### PR TITLE
fix: [CI-6630]: fixed git exp repo listing

### PR DESCRIPTION
**Pull request by devkimittal**
## Describe your changes
Git exp repo list API does not work when the connect is a account level connect with url configured as https://github.com/ , this needs to be resolved. 
Tests done : Tested http and ssh for github, bitbucket, azure connectors with account and repo level settings. Tested fetch branch api as well.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44060)

### CODE REVIEW

**Comment by devkimittal** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java` line 344 at r2](https://reviewable.io/reviews/harness/harness-core/44060#-NOhg5rk27qH8g2cFZI3:-NOhg5rk27qH8g2cFZI4:bonfkc1) ([raw file](https://github.com/harness/harness-core/blob/f23ca1961583a23c3ef759553da018e4f344fb1e/930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java#L344)):*
> ```Java
>       return mapToGitConnectionType(gitConfigDTO.getConnectionType());
>     } else {
>       throw new CIStageExecutionException("scmType " + scmConnector.getConnectorType() + "is not supported.");
> ```

it is a generic util, we can't throw CI exceptions here.

**Comment by devkimittal** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java` line 344 at r2](https://reviewable.io/reviews/harness/harness-core/44060#-NOhg5rk27qH8g2cFZI3:-NOhhI2o5-qgXP4qzrsH:bs6cfdy) ([raw file](https://github.com/harness/harness-core/blob/f23ca1961583a23c3ef759553da018e4f344fb1e/930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java#L344)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it is a generic util, we can't throw CI exceptions here.
</blockquote></details>

Got it. will use InvalidRequestException

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44060)* status: :shipit: complete! ✓

**Pull request merged**
