### PR TITLE
techDebt: [PL-31049]: Migrate MongoClient to new version <WIP>

### PR DESCRIPTION
**Pull request by kshitij-harness**
## Describe your changes
- Use AbstractMongoClientConfiguration instead of AbstractMongoConfiguration
- Use org.mongodb.client.MongoClient instead of org.mongodb.MongoClient to support above operation
- Use MongoClientSettings instead of MongoClientOptions to create MongoClient
- Use non deprecated constructor for MongoTemplate
- Migrate SimpleMongoDbFactory to SimpleMongoClientDbFactory

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42967)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 20 of 23 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoModule.java` line 130 at r2](https://reviewable.io/reviews/harness/harness-core/42967#-NMYmH035jArQo7heHzu:-NMYmH035jArQo7heHzv:b-6qm3hg) ([raw file](https://github.com/harness/harness-core/blob/13cc5a77a715f2ea6c9259654c6e5182af10514e/960-persistence/src/main/java/io/harness/mongo/MongoModule.java#L130)):*
> ```Java
> 
>   @Provides
>   @Named("primaryMongoClient")
> ```

primaryNewMongoClient

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967#-:-NMYn9K8ElJT-YL1NOqY:bnfp4nl)* status: :shipit: complete! ✓

**Comment by kshitij-harness** [comment]
trigger ti1

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 23 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967)* status: 21 file(s) to review.

**Review by nishantsaini20 — COMMENTED** [review]
> Reviewed 1 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967)* status: 20 file(s) to review.

**Review by hextechpal — APPROVED** [review]
> Reviewed 20 of 23 files at r1, 4 of 7 files at r2, 15 of 19 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967)* status: :shipit: complete! ✓

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 15 of 19 files at r3, 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967#-:-NMmEc5f-KR6dl5YspIz:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankit-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967#-:-NMmEf7ZEDwTrvoVPcyV:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42967#-:-NMmduKMCaeHVnYl5ix7:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
