### PR TITLE
feat: [PL-26782]: Revert remove feature flag SEND_SLACK_NOTIFICATION_FROM_DELEGATE

### PR DESCRIPTION
**Pull request by rijajoo**
Reverts harness/harness-core#37644

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38179)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38179)

**Comment by rijajoo** [comment]
trigger messagecheck

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38179)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38179)* status: :shipit: complete! ✓

**Pull request merged**
