### PR TITLE
fix: [PL-30598]: Thread Contention in CgInstanceSyncV2

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
We are making a call to setCertValidation twice in this getById() call. Now we stopped making this call.
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42157)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 288 at r2](https://reviewable.io/reviews/harness/harness-core/42157#-NLUjocN1QfY-XR0ofI7:-NLUjocN1QfY-XR0ofI8:bbwqhqa) ([raw file](https://github.com/harness/harness-core/blob/b66c3bd2551de4728a5fcf4de66e066d71da24ec/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L288)):*
> ```Java
> 
>     List<CgDeploymentReleaseDetails> deploymentReleaseDetails = new ArrayList<>();
>     instanceSyncTaskDetails.parallelStream().forEach(taskDetails -> {
> ```

do we need paralleStream?

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42157)* status: Some of the checks are too old. 2 file(s) to review. 0 of 2 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42157)* status: Some of the checks are too old. 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 288 at r2](https://reviewable.io/reviews/harness/harness-core/42157#-NLUjocN1QfY-XR0ofI7:-NLUs8ec74c1iu5XhunM:bd9zjx3) ([raw file](https://github.com/harness/harness-core/blob/b66c3bd2551de4728a5fcf4de66e066d71da24ec/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L288)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

do we need paralleStream?
</blockquote></details>

No, parallelStream is already changed with stream 
@VikasMaddukuriHarness can you please rebase this PR with develop

**Comment by VikasMaddukuriHarness** [comment]
Closing this PR as the parallel stream has been removed by @namantalaycha10

**Pull request closed without merging**
