### PR TITLE
techdebt: [PIE-2744]: Handler to consume redis events for CD

### PR DESCRIPTION
**Pull request by shalini-agr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31554)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31554)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java, line 383 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMhhX0DtjIaKSoI60a:-MyMhhX0DtjIaKSoI60b:bvqb7wy) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L383)):*
> ```Java
>     // Will create collections and Indexes
>     injector.getInstance(HPersistence.class);
>     injector.getInstance(ObjectMapper.class);
> ```

y is this needed?
___
*[879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java, line 166 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMi7Jt8xPtmdroBtnH:-MyMi7Jt8xPtmdroBtnI:b28fa0e) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java#L166)):*
> ```Java
>       bind(Consumer.class)
>           .annotatedWith(Names.named(PIPELINE_EXECUTION_SUMMARY_REDIS_EVENT_CONSUMER_CD))
>           .toInstance(RedisConsumer.of("pms-harness_db.pms-harness.planExecutionsSummary", "test5", redissonClient,
> ```

We should expose some utility from put modules to calculate it



_Code quote:_
```Java
pms-harness_db.pms-harness.planExecutionsSummary
```
___
*[879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java, line 168 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMi09E9Dnrq6vxuVQL:-MyMi09E9Dnrq6vxuVQM:b-khd4r7) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java#L168)):*
> ```Java
>           .toInstance(RedisConsumer.of("pms-harness_db.pms-harness.planExecutionsSummary", "test5", redissonClient,
>               Duration.ofSeconds(MAX_PROCESSING_TIME_SECONDS), 100, redisConfig.getEnvNamespace()));
>     }
> ```

This binding should be in 120 module not here
___
*[889-yaml-commons/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMhLWt3VqKzR4_qGVS:-MyMhLWt3VqKzR4_qGVT:b-kq6bvv) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/889-yaml-commons/BUILD.bazel#L15)):*
> ```Starlark
>         "//900-git-sync-sdk:module",
>         "//950-walktree-visitor:module",
>         "//952-debezium-engine:module",
> ```

this should not be needed
___
*[889-yaml-commons/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMhDncCtWXuSLYdBDD:-MyMhDncCtWXuSLYdBDE:b-ytocci) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/889-yaml-commons/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java#L13)):*
> ```Java
> import lombok.SneakyThrows;
> 
> public abstract class RedisAbstractHandler implements PmsCommonsBaseEventHandler<DebeziumChangeEvent> {
> ```

This should not be here. @sahilhindwani-harness can you help in moving other handlers from here as well

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 3 of 9 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31554)* status: Some of the checks are too old. 1 change requests.

**Comment by shalini-agr** [comment]
___
*[889-yaml-commons/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMhLWt3VqKzR4_qGVS:-MyN8cR62dAczW_tY1fV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/889-yaml-commons/BUILD.bazel#L15)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this should not be needed
</blockquote></details>

done

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31554)* status: Some of the checks are too old. 1 change requests. 5. unresolved discussions. 

___
*[120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java, line 383 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMhhX0DtjIaKSoI60a:-MyN8RdsEqf8o3PFfM4W:b-9m4twp) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L383)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

y is this needed?
</blockquote></details>

Not needed. Removed this.
___
*[879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java, line 166 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMi7Jt8xPtmdroBtnH:-MyN8_uNDQ6SOKS480q-:b-hfaqdw) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java#L166)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

We should expose some utility from put modules to calculate it
</blockquote></details>

added as a constant
___
*[879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java, line 168 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMi09E9Dnrq6vxuVQL:-MyN8Z9u4q_1XHj-K2w0:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/879-pms-sdk/src/main/java/io/harness/pms/sdk/execution/PmsSdkEventsFrameworkModule.java#L168)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

This binding should be in 120 module not here
</blockquote></details>

done
___
*[889-yaml-commons/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java, line 13 at r1](https://reviewable.io/reviews/harness/harness-core/31554#-MyMhDncCtWXuSLYdBDD:-MyN8TtiBYEXuGKdQ7Hn:bqbclud) ([raw file](https://github.com/harness/harness-core/blob/05f6b70d64b83e232286ec4f5578b1f4c6e1cd3b/889-yaml-commons/src/main/java/io/harness/redisHandler/RedisAbstractHandler.java#L13)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

This should not be here. @sahilhindwani-harness can you help in moving other handlers from here as well
</blockquote></details>

Moved to 878-ng-common-utilities

**Comment by shalini-agr** [comment]
trigger ti1, ti2, ti4

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31554)* status: 1 change requests. 5. unresolved discussions.

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by hextechpal — APPROVED** [review]
> Reviewed 5 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31554)* status: 1 file(s) to review.

**Pull request merged**
