### PR TITLE
feat: [CDS-79096]: update azure java sdk resources to 2.26

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
The purpose of this PR is to update the azure java SDK resources. The customer faced and issue while they had this config turned off "Basic auth credentials". They used to have it off for a while, and from one day it started to fail.
Screenshot 2023-09-29 at 17 32 09
We expect that this is caused by these commits which goes in this version (2.26 and 2.26.1)
https://github.com/Azure/azure-sdk-for-java/commit/3f7d2f6f7359673ba7dad423f5e976a5a3e85432
`// Kudu's authentication changed from Basic Auth to AAD Auth
`

Locally I was able to face an issue if we turn off this setting also, but the customer had other error. 
Once I updated the azure java SDK resources to these versions, the azure web app deployment started to work for me.

Just one thing to mention, prior to update locally these libraries I was getting this error: "_401 (empty body)_". While customer had: "_okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR_"
```
azure-resourcemanager from 2.14 to 2.26
azure-resourcemanager-appservice from 2.14 to 2.26
azure-core-management from 1.6.2 to 1.11.1 
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53385)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger uts

**Comment by vlica-harness** [comment]
trigger uts

**Comment by vlica-harness** [comment]
trigger messagecheck

**Comment by vlica-harness** [comment]
trigger messagecheck

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53385#-:-NfWUK1S3I8gfIGMO1wI:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — DISMISSED** [review]

**Review by markoharness — DISMISSED** [review]

**Comment by vlica-harness** [comment]
trigger uts

**Comment by vlica-harness** [comment]
trigger uts

**Review by markoharness — APPROVED** [review]

**Comment by vlica-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53385#-:-NfpC9UREZLgDqyiBIkc:bnfp4nl)* status: 5 file(s) to review.

**Comment by vlica-harness** [comment]
trigger uts

**Comment by vlica-harness** [comment]
trigger review

**Review by pranay-harness — APPROVED** [review]
Library versions upgraded. Looks good

**Pull request merged**
