### PR TITLE
[feat]: [CI-4496]: Support OOTB steps for kubernetes windows

### PR DESCRIPTION
**Pull request by shubham149**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33288)

### CODE REVIEW

**Comment by shubham149** [comment]
trigger messagecheck

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33288#-:-N2WXCX61j-m5MlY-I1A:bnfp4nl)* status: :shipit: complete! ✓

**Comment by jamie-harness** [comment]
trigger ti3

**Comment by jamie-harness** [comment]
trigger ti3

**Comment by rutvijmehta-harness** [comment]
trigger ti3

**Comment by rutvijmehta-harness** [comment]
trigger ti3

**Comment by rutvijmehta-harness** [comment]
trigger ti3

**Review by aman-harness — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33288)* status: :shipit: complete! ✓

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33288#-:-N2jUr1X4AP-QqwfceEV:bnfp4nl)* status: :shipit: complete! ✓

**Review by aman-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33288#-:-N2jV1hx00km6BbyqzCX:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
