### PR TITLE
[feat]: [CDS-43506]: Create Elastigroup infrastructure

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38634)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger feature-build

**Review by puthrayaharness — DISMISSED** [review]

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38634#-:-NE_rKHd6OWYT4RfdJ33:bnfp4nl)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38634)* status: :shipit: complete! ✓

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38634)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 314 at r3](https://reviewable.io/reviews/harness/harness-core/38634#-NEgkpWOEvzSkN1KVIIX:-NEgkpWOEvzSkN1KVIIY:bwh3exx) ([raw file](https://github.com/harness/harness-core/blob/e3f27d210ec8dd5b9fdbc2f3f7a50a401c84669c/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L314)):*
> ```Java
>         StepCategory.STAGE.name());
> 
>     publishOutput(spec, ambiance);
> ```

We should publish outputs in produceStepResponseForNonTaskStepInfra(ambiance, infraOutput, logCallback) method, and the method name could be more specific like 
publishElastigroupConfiguration()



_Code quote:_
```Java
publishOutput(spec, ambiance)
```

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38634#-:-NFQJYnm-f0f8vNckFPN:bnfp4nl)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38634#-:-NFSRbaX62jgawvL-kUh:bnfp4nl)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
