### PR TITLE
feat: [PIE-4382]: Addition of new failure strategy for execution time input…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…s and some refactoring

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36289)

What the change is about?
- Addition of new failure strategy for execution time inputs.
- Addition of new error type for execution time inputs if the inputs were not provided on time.
- Refactoring of some code related to execution time inputs.

Bug Fixes:
- If whenCondition evaluates to true then the we don't wait for execution time inputs
- Execution time inputs working with matrix.

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 12 Issues 
* Code issue 12 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36289)

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/manualintervention/ManualInterventionAdviser.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/36289#-N9Fm-Hq4lvVxjYv1Pjy:-N9Fm-Hq4lvVxjYv1Pjz:b-o3dlvl) ([raw file](https://github.com/harness/harness-core/blob/bb9080e587cb2145954b63236c911abbdbafd4e3/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/manualintervention/ManualInterventionAdviser.java#L63)):*
> ```Java
>     boolean canAdvise = StatusUtils.brokeStatuses().contains(advisingEvent.getToStatus())
>         && advisingEvent.getFromStatus() != INTERVENTION_WAITING
>         && advisingEvent.getFromStatus() == Status.INPUT_WAITING;
> ```

remove from here.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/36289#-N9FmXpwA1dAZ3CX7ds4:-N9FmXpwA1dAZ3CX7ds5:b-y2yqoj) ([raw file](https://github.com/harness/harness-core/blob/bb9080e587cb2145954b63236c911abbdbafd4e3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputCallback.java#L66)):*
> ```Java
>     PlanNode node = nodeExecution.getNode();
>     FailureInfo failureInfo = FailureInfo.newBuilder()
>                                   .setErrorMessage("ExecutionInputExpired")
> ```

nit: improve error message

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 33 of 34 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36289)* status: 41 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36289)* status: 54 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
trigger ti4

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36289)* status: 55 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 24 of 34 files at r2, 1 of 3 files at r3, 16 of 21 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36289)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): sto. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/success/OnSuccessAdviser.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/36289#-N9eHCMB-BJvVt03Doqg:-N9eHCMB-BJvVt03Doqh:b-qhun5q) ([raw file](https://github.com/harness/harness-core/blob/65eebb03c666c03dba1cb13df0431e389c9613f4/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/success/OnSuccessAdviser.java#L47)):*
> ```Java
>   public boolean canAdvise(AdvisingEvent advisingEvent) {
>     return StatusUtils.positiveStatuses().contains(advisingEvent.getToStatus())
>         || advisingEvent.getFromStatus() == Status.INPUT_WAITING;
> ```

instead of hardcoded checking this, we should expose another method in status utils and use it here



_Code quote:_
```Java
|| advisingEvent.getFromStatus() == Status.INPUT_WAITING
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java` line 69 at r6](https://reviewable.io/reviews/harness/harness-core/36289#-N9eI04C315YnF3G7YCe:-N9eI04C315YnF3G7YCf:b-u0syux) ([raw file](https://github.com/harness/harness-core/blob/65eebb03c666c03dba1cb13df0431e389c9613f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java#L69)):*
> ```Java
>       TimeoutParameters timeoutParameters =
>           OrchestrationUtils.buildTimeoutParameters(kryoSerializer, evaluator, timeoutObtainment);
>       timeout = timeoutParameters.getTimeoutMillis();
> ```

isnt this means last value of timeout ?



_Code quote:_
```Java
      TimeoutParameters timeoutParameters =
          OrchestrationUtils.buildTimeoutParameters(kryoSerializer, evaluator, timeoutObtainment);
      timeout = timeoutParameters.getTimeoutMillis();
```

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36289)* status: 16 file(s) to review. 1 change requests. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java` line 69 at r6](https://reviewable.io/reviews/harness/harness-core/36289#-N9eI04C315YnF3G7YCe:-N9l-avI0boo_9iLH5AR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65eebb03c666c03dba1cb13df0431e389c9613f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/WaitForExecutionInputHelper.java#L69)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this means last value of timeout ?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/success/OnSuccessAdviser.java` line 47 at r6](https://reviewable.io/reviews/harness/harness-core/36289#-N9eHCMB-BJvVt03Doqg:-N9l-bt4CNZhjdMjoKv4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/65eebb03c666c03dba1cb13df0431e389c9613f4/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/success/OnSuccessAdviser.java#L47)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead of hardcoded checking this, we should expose another method in status utils and use it here
</blockquote></details>

Done.

**Pull request merged**
