### PR TITLE
fix: [SRM-13158]: added migration for deleting actvites which don't have associated monitored services and added function to delete activities while deleting monitored service

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40692)

### CODE REVIEW

**Comment by karansaraswat19** [comment]
trigger codebasehash

**Comment by karansaraswat19** [comment]
trigger codebasehash

**Comment by karansaraswat19** [comment]
trigger codebasehash

**Comment by karansaraswat19** [comment]
trigger codebasehash

**Comment by AnshuH** [comment]
trigger codebasehash

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40692)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/api/ActivityService.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/40692#-NHz8Gg69nEbh2yE2SuX:-NHz8Gg71guoqohoSRbM:b3to63s) ([raw file](https://github.com/harness/harness-core/blob/68a0c8fffaba41ea665842f3f5a57573fbc69377/300-cv-nextgen/src/main/java/io/harness/cvng/activity/services/api/ActivityService.java#L47)):*
> ```Java
>   String upsert(Activity activity);
> 
>   boolean deleteByMonitoredServiceIdentifier(String monitoredServiceIdentifier);
> ```

You should have projectParams here as well, since it's project scoped



_Code quote:_
```Java
tring monitoredServiceIdentifier)
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/migration/list/DeleteActivitiesNotAssociatedWithMonitoredServices.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/40692#-NHz8jFk-ptOMexF90Q7:-NHz8jFk-ptOMexF90Q8:bllyl8q) ([raw file](https://github.com/harness/harness-core/blob/68a0c8fffaba41ea665842f3f5a57573fbc69377/300-cv-nextgen/src/main/java/io/harness/cvng/migration/list/DeleteActivitiesNotAssociatedWithMonitoredServices.java#L45)):*
> ```Java
>     List<String> toBeDelectedActivitesUuid = new ArrayList<>();
>     int count = 0;
>     final int limit = 2;
> ```

why is the limit 2? Also did we verify this works? 



_Code quote:_
```Java
    final int limit = 2;
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/migration/list/DeleteActivitiesNotAssociatedWithMonitoredServices.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/40692#-NHz8pPO8i7nQZqkljsM:-NHz8pPO8i7nQZqkljsN:b-rn1xdl) ([raw file](https://github.com/harness/harness-core/blob/68a0c8fffaba41ea665842f3f5a57573fbc69377/300-cv-nextgen/src/main/java/io/harness/cvng/migration/list/DeleteActivitiesNotAssociatedWithMonitoredServices.java#L48)):*
> ```Java
> 
>     try {
>       HIterator<Activity> iterator = new HIterator<>(activityQuery.fetch(new FindOptions().limit(limit).skip(count)));
> ```

won't this needs to be changed as discussed?



_Code quote:_
```Java
count
```

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40692)* status: 11 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/migration/list/DeleteActivitiesNotAssociatedWithMonitoredServices.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/40692#-NI7LhU-2_w-7KXKQ0BQ:-NI7LhU-2_w-7KXKQ0BR:b-a1x1fi) ([raw file](https://github.com/harness/harness-core/blob/68a0c8fffaba41ea665842f3f5a57573fbc69377/300-cv-nextgen/src/main/java/io/harness/cvng/migration/list/DeleteActivitiesNotAssociatedWithMonitoredServices.java#L48)):*
> ```Java
> 
>     try {
>       HIterator<Activity> iterator = new HIterator<>(activityQuery.fetch(new FindOptions().limit(limit).skip(count)));
> ```

lets use the iterator without limit and delete the docs when they reach 1000.



_Code quote:_
```Java
toBeDelectedActivitesUuid.add(activity.getUuid());
```

**Review by deepak-harness — APPROVED** [review]
> Reviewed 10 of 11 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40692)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40692#-:-NI7qZGF0286TNIThl5U:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
