### PR TITLE
feat: [SRM-14139]: implementation file for create, update and delete functionality

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45011)

### CODE REVIEW

**Review by deepak-harness — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45011)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45011)* status: :shipit: complete! ✓

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 1 of 1 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45011)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 27 at r3](https://reviewable.io/reviews/harness/harness-core/45011#-NQPyMZr3BCu2LuUUht2:-NQPyMZr3BCu2LuUUht3:b-a39dwe) ([raw file](https://github.com/harness/harness-core/blob/e7548bb82f6c185b488e9854d5d2d8b73fd501d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L27)):*
> ```Java
>   @Override
>   public AnnotationResponse create(ProjectParams projectParams, AnnotationDTO annotationDTO) {
>     Annotation annotation = getAnnotationFromAnnotationDTO(projectParams, annotationDTO);
> ```

We need to add a validations for following:
1. We don't have any annotation with the same startTime and different end time for same slo.
2. SLO exists
3. Start time <= endTime



_Code quote:_
```Java
Annotation annotation = getAnnotationFromAnnotationDTO(projectParams, annotationDTO);
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/45011#-NQPxBd32A7rgW3BtGB2:-NQPxBd32A7rgW3BtGB3:bql973t) ([raw file](https://github.com/harness/harness-core/blob/e7548bb82f6c185b488e9854d5d2d8b73fd501d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L37)):*
> ```Java
> 
>   @Override
>   public AnnotationResponse update(String annotationId, AnnotationDTO annotationDTO) {
> ```

Add a validation that this annotationId is same as the id in dto



_Code quote:_
```Java
 annotationId
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/45011#-NQPygt39QzjZPWdTLOl:-NQPygt39QzjZPWdTLOm:bq9uffs) ([raw file](https://github.com/harness/harness-core/blob/e7548bb82f6c185b488e9854d5d2d8b73fd501d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L53)):*
> ```Java
>   @Override
>   public boolean delete(String annotationId) {
>     Annotation annotation = Annotation.builder().uuid(annotationId).build();
> ```

validate annotation exists



_Code quote:_
```Java
Annotation annotation = Annotation.builder().uuid(annotationId).build();
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 54 at r3](https://reviewable.io/reviews/harness/harness-core/45011#-NQPxgd45LvT8ZswNBg_:-NQPxgd45LvT8ZswNBga:bynuxc0) ([raw file](https://github.com/harness/harness-core/blob/e7548bb82f6c185b488e9854d5d2d8b73fd501d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L54)):*
> ```Java
>   public boolean delete(String annotationId) {
>     Annotation annotation = Annotation.builder().uuid(annotationId).build();
>     return hPersistence.delete(annotation);
> ```

nit: we already have a method to delete by id, use that



_Code quote:_
```Java
    Annotation annotation = Annotation.builder().uuid(annotationId).build();
    return hPersistence.delete(annotation);
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/45011#-NQPxKci8Zd_rone66ol:-NQPxKci8Zd_rone66om:b2pya3w) ([raw file](https://github.com/harness/harness-core/blob/e7548bb82f6c185b488e9854d5d2d8b73fd501d9/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L77)):*
> ```Java
>   private Annotation getEntity(String annotationId) {
>     return hPersistence.get(Annotation.class, annotationId);
>   }
> ```

Make it Optional, and verify it exists in create and update



_Code quote:_
```Java
  private Annotation getEntity(String annotationId) {
    return hPersistence.get(Annotation.class, annotationId);
  }
```

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45011#-:-NQTfQ8R2UlLT_sd6O7-:bnfp4nl)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java` line 98 at r5](https://reviewable.io/reviews/harness/harness-core/45011#-NQTfHon868t5IKmiiiL:-NQTfHon868t5IKmiiiM:b-oqgxma) ([raw file](https://github.com/harness/harness-core/blob/f3754471786d7db598e64a0ad1e12e7ab9d1e41b/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/AnnotationServiceImpl.java#L98)):*
> ```Java
>                                        .collect(Collectors.toList());
>     if (isNotEmpty(annotations) && annotations.get(0).getEndTime() != annotationDTO.getEndTime()) {
>       throw new IllegalStateException("Can make a single thread for the same start time");
> ```

nit: improve this.



_Code quote:_
```Java
Can make a single thread for the same start time
```

**Pull request merged**
