### PR TITLE
feat: [CCM-5482]: Analyse all "SlowQuery" queries

### PR DESCRIPTION
**Pull request by ketankr9**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30848)

### CODE REVIEW

**Comment by ketankr9** [comment]
trigger ti3

**Review by hitesharinga — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30848)* status: Some of the checks are too old.

**Review by hitesharinga — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30848)* status: Some of the checks are too old.

**Pull request merged**
