### PR TITLE
[feat]: [PL-25208]: Hard delete Pipeline

### PR DESCRIPTION
**Pull request by namanvermah**
For old git sync, there is a delete function already that can be used. For other flows, `findAndRemove` works.
When a project is deleted old git sync flow needs each pipeline to be deleted separately so that files are deleted on git. `findAllAndRemove` works for all other kinds of projects.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33872)

### CODE REVIEW

**Review by archit-harness — DISMISSED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33872)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger compile

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33872)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33872)* status: :shipit: complete! ✓

**Pull request merged**
