### PR TITLE
fix: [CDS-47939]: add retry lazy to collect manifest

### PR DESCRIPTION
**Pull request by rafaelmart1ns**
## Describe your changes
In this pr, it corrects a failure when logging information in the flow to collect artifacts.
It also adds an extra layer of reliability with a lazy retry to try to improve resiliency towards collecting helm artifacts.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44313)

### CODE REVIEW

**Comment by rafaelmart1ns** [comment]
trigger feature-build

**Comment by rafaelmart1ns** [comment]
trigger messagecheck

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44313)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/44313#-NPMiW4y835ydPUbnQc3:-NPMiW4y835ydPUbnQc4:bxhiuk7) ([raw file](https://github.com/harness/harness-core/blob/6b5b7ab75e1858e8f548abb7f67865e205d3b742/930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java#L94)):*
> ```Java
> 
>   private final boolean ALLOW_RETRY_ON_COLLECT_HELM_ARTIFACTS =
>       Boolean.parseBoolean(System.getenv().get("ALLOW_RETRY_ON_COLLECT_HELM_ARTIFACTS"));
> ```

We should leave the system env variables usage to infrastructure definitions as this requires customer-side changes.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java` line 419 at r3](https://reviewable.io/reviews/harness/harness-core/44313#-NPMiBEaAVur3RA9LB79:-NPMiBEaAVur3RA9LB7A:b-mqle0f) ([raw file](https://github.com/harness/harness-core/blob/6b5b7ab75e1858e8f548abb7f67865e205d3b742/930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java#L419)):*
> ```Java
>     final RetryConfig config =
>         RetryConfig.custom().maxAttempts(1).intervalFunction(IntervalFunction.ofExponentialBackoff()).build();
>     final Retry retry = Retry.of("ArtifactoryRetry", config);
> ```

Move RetryConfig and Retry initialization to the class constructor.
___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java` line 424 at r3](https://reviewable.io/reviews/harness/harness-core/44313#-NPMiJSLD2hDhB1Hv4zZ:-NPMiJSLD2hDhB1Hv4z_:bagbbm0) ([raw file](https://github.com/harness/harness-core/blob/6b5b7ab75e1858e8f548abb7f67865e205d3b742/930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java#L424)):*
> ```Java
>       response = Retry.decorateCallable(retry, () -> artifactory.restCall(request)).call();
>       return response;
>     } catch (Exception e) {
> ```

We should not catch the exception at this point, leave it to the caller, and add throws to the method signature.

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44313)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java` line 440 at r4](https://reviewable.io/reviews/harness/harness-core/44313#-NPOgcxzDu_IgWGgEZGu:-NPOgcxzDu_IgWGgEZGv:b-mbwdpu) ([raw file](https://github.com/harness/harness-core/blob/3a483c9c27e6952d604b0533b77269ca6f886bc2/930-delegate-tasks/src/main/java/software/wings/helpers/ext/artifactory/ArtifactoryServiceImpl.java#L440)):*
> ```Java
>       artifactoryResponse = retryCall(repositoryRequest, artifactory);
>     } catch (Exception e) {
>       log.error(format("Error occurred while get artifacts of manifests in retry"), e);
> ```

We don't need this log error, just leave the exception to go up.

Otherwise, we will get a NullPointerException in the next line after the try/catch block.

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44313)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44313)* status: :shipit: complete! ✓

**Pull request merged**
