### PR TITLE
feat: [SRM-15049]: Add spec for analyze deployment activity, change s…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…ource, and response

## Describe your changes

A new change source type is added SRMAnalysis which is for deployment analysis step. The activity for this will be created with analyze deployment step run.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50026)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50026)* status: 15 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/activity/ActivityType.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZMUCP9tTBeLvkdE1j:-NZZMUCP9tTBeLvkdE1k:boneajd) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/activity/ActivityType.java#L30)):*
> ```Java
>   CUSTOM_INFRA("CUSTOM_INFRA"),
>   CUSTOM_FF("CUSTOM_FF"),
>   SRM_ANALYSIS("SRM_ANALYSIS");
> ```

SRM_STEP_ANALYSIS
___
*[`srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/change/HarnessSRMAnalysisEventMetadata.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZMkjE8fLAuIq3p59O:-NZZMkjE8fLAuIq3p59P:b-njxmbo) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/change/HarnessSRMAnalysisEventMetadata.java#L25)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class HarnessSRMAnalysisEventMetadata extends ChangeEventMetadata {
>   long deploymentStartTime;
> ```

pipeline start time 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/entities/SRMAnalysisActivity.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZP1n-6N73UdnyYouf:-NZZP1n-6N73UdnyYoug:b-nyam0o) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/entities/SRMAnalysisActivity.java#L43)):*
> ```Java
> 
>   String analysisDuration;
>   io.harness.cvng.beans.change.SRMAnalysisStatus SRMAnalysisStatus;
> ```

Not required. Step should be source of truth.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/entities/SRMAnalysisActivity.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZRyW30NQYsA48rlSo:-NZZRyW30NQYsA48rlSp:bofy64g) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/entities/SRMAnalysisActivity.java#L76)):*
> ```Java
>     public String getEntityKeyLongString(SRMAnalysisActivity activity) {
>       return super.getKeyBuilder(activity).add(activity.getPlanExecutionId()).add(activity.getStageStepId()).toString();
>     }
> ```

nit: please add populateKeyQuery.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/entities/changeSource/SRMAnalysisChangeSource.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZSH0u-xHFnp_DO_nd:-NZZSH0u-xHFnp_DO_ne:b-oiqw4u) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/entities/changeSource/SRMAnalysisChangeSource.java#L22)):*
> ```Java
> public class SRMAnalysisChangeSource extends ChangeSource {
>   public static class UpdatableSRMAnalysisChangeSourceEntity
>       extends UpdatableChangeSourceEntity<SRMAnalysisChangeSource, SRMAnalysisChangeSource> {
> ```

take a look if this is required even

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger smartchecks

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50026)* status: 16 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/activity/ActivityType.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZMUCP9tTBeLvkdE1j:-NZ_Ld5I6-8l398VU5we:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/activity/ActivityType.java#L30)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

SRM_STEP_ANALYSIS
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/change/HarnessSRMAnalysisEventMetadata.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZMkjE8fLAuIq3p59O:-NZ_Le9SBb5LS5Rpj7hg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/change/HarnessSRMAnalysisEventMetadata.java#L25)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

pipeline start time 
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/entities/SRMAnalysisActivity.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZP1n-6N73UdnyYouf:-NZ_LvYG-C6uVGQeQ566:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/entities/SRMAnalysisActivity.java#L43)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Not required. Step should be source of truth.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/entities/changeSource/SRMAnalysisChangeSource.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/50026#-NZZSH0u-xHFnp_DO_nd:-NZ_Lwsz2NGvgz7cZe1q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ac05ee15a1f5eb02e9eab3cab9e1a50b2f120bc0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/entities/changeSource/SRMAnalysisChangeSource.java#L22)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

take a look if this is required even
</blockquote></details>

Done.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 15 files at r1, 11 of 12 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50026)* status: :shipit: complete! ✓

**Pull request merged**
