### PR TITLE
feat: [CDP-16747]: Support for package deployment

### PR DESCRIPTION
**Pull request by jelenaHarness**
Original pr: https://github.com/harness/harness-core/pull/22153

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)

### CODE REVIEW

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 28 of 41 files at r1, 2 of 6 files at r2, 3 of 10 files at r3, 8 of 13 files at r4, 11 of 13 files at r5, 2 of 5 files at r6, 3 of 3 files at r7, 5 of 5 files at r9, 20 of 20 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-MtxHwv76Yo5Lxo1udUW:bnfp4nl)* status: 82 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 28 of 41 files at r1, 2 of 6 files at r2, 3 of 10 files at r3, 8 of 13 files at r4, 11 of 13 files at r5, 2 of 5 files at r6, 3 of 3 files at r7, 5 of 5 files at r9, 20 of 20 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-MtxIH6i0Ln0SWyNUWRl:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu1H8be8pbAyoDnTN7A:bnfp4nl)* status: 16 file(s) to review.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu1HOua2q4JghitJkOP:bnfp4nl)* status: 16 file(s) to review.

**Comment by ivan-83** [comment]
trigger ti3

**Comment by anilchowdhury-harness** [comment]
trigger ti3

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: 18 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/azure/appservices/AbstractAzureAppServiceState.java, line 147 at r12](https://reviewable.io/reviews/harness/harness-core/30024#-Mu4oYgg03H54nR_nsTs:-Mu4oYgh-kqzpKIP4Bby:b-sze0xo) ([raw file](https://github.com/harness/harness-core/blob/8ad1ee838ff7e71b93d76e7c1b49889fb2013c0b/400-rest/src/main/java/software/wings/sm/states/azure/appservices/AbstractAzureAppServiceState.java#L147)):*
> ```Java
>     Artifact artifact = azureVMSSStateHelper.getWebAppNonContainerArtifact(context, isRollback());
>     boolean isNonDocker = azureVMSSStateHelper.isWebAppNonContainerDeployment(context);
>     if (supportRemoteManifest() && !isGitFetchDone(context) && !isRollback()) {
> ```

we can return FALSE from supportRemoteManifest() as during rollback GIT is not supported. We are returning TRUE from there and here we are checking if not rollback ... this is complicating the code.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r12, 8 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7CPEGBUw6L8RONxuW:bnfp4nl)* status: 23 file(s) to review.

**Review by anilchowdhury-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: 23 file(s) to review.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7HH0C37BZSPdFFOvZ:bnfp4nl)* status: 23 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 10 of 16 files at r11, 4 of 7 files at r12, 6 of 8 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7H_YzAIJ3zVwVey_9:bnfp4nl)* status: 1 file(s) to review.

**Review by jelenaHarness — COMMENTED** [review]
> Reviewed 25 of 41 files at r1, 2 of 6 files at r2, 1 of 10 files at r3, 5 of 13 files at r4, 7 of 13 files at r5, 3 of 3 files at r7, 4 of 5 files at r9, 13 of 20 files at r10, 10 of 16 files at r11, 5 of 7 files at r12, 6 of 8 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: 1 file(s) to review.

**Review by jelenaHarness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7JuwV3voVoAH0LIOf:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7KiEk8jiSUAiAEUNw:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7L8JZ4YDHxz3Qib8P:bnfp4nl)* status: 1 file(s) to review.

**Review by anilchowdhury-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: 1 file(s) to review.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7MRhN-7fDsU_zDJ53:bnfp4nl)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: 1 file(s) to review.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 16 files at r11, 3 of 7 files at r12.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30024#-:-Mu7Npwc7IEZQ_xBa0wb:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
