### PR TITLE
feat: [SPG-203]: making cluster API doc public

### PR DESCRIPTION
**Pull request by RajBaviskar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37492)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37492)

**Comment by rohitk-h** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java` line 306 at r1](https://reviewable.io/reviews/harness/harness-core/37492#-NBsTEdpDPd1_glN6FlO:-NBsdp1C8AkENYosLCXj:b32v57) ([raw file](https://github.com/harness/harness-core/blob/c355628e0016a058111ba8e64bdcc54fa1f36926/120-ng-manager/src/main/java/io/harness/ng/gitops/resource/ClusterResource.java#L306)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We should keep this API hidden, it is not supposed to be used by customers.
To list clusters from gitops, they should directly use gitops server APIs
</blockquote></details>

+1

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37492)* status: 1. unresolved discussions.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Comment by rohitk-h** [comment]
*[`build.properties` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/37492#-NBsq3WWEQIbNkr-_EeI:-NBsq3WX412x4BtN5T2_:bx47t9n) ([raw file](https://github.com/harness/harness-core/blob/a9055407c907360ff8c1d4b0d458b84cc1e7c14a/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=0
> build.number=76621
> ```

Can we not make this a patch release ?

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37492)* status: 1. unresolved discussions.

**Comment by RajBaviskar** [comment]
> _[`build.properties` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/37492#-NBsq3WWEQIbNkr-_EeI:-NBsq3WX412x4BtN5T2_:bx47t9n) ([raw file](https://github.com/harness/harness-core/blob/a9055407c907360ff8c1d4b0d458b84cc1e7c14a/build.properties#L3)):_
> 
> > ```ini
> > build.majorVersion=1
> > build.minorVersion=0
> > build.number=76621
> > ```
> 
> Can we not make this a patch release ?

changed to patch release

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37492)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37492)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37492)* status: :shipit: complete! ✓

**Pull request merged**
