### PR TITLE
feat: [PL-22614]: Swagger Annotations for ResourceGroupV2 Classes

### PR DESCRIPTION
**Pull request by reetika04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31751)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger messagecheck

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31751)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[930-ng-core-clients/src/main/java/io/harness/resourcegroupclient/remote/ResourceGroupClient.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/31751#-Mz-Z1Up83Sc6EwDroT_:-Mz-Z1Up83Sc6EwDroTa:b-77qtms) ([raw file](https://github.com/harness/harness-core/blob/a58ecbe36268fa8cb153e236cb3f8570ff61a79f/930-ng-core-clients/src/main/java/io/harness/resourcegroupclient/remote/ResourceGroupClient.java#L31)):*
> ```Java
> 
>   @GET(RESOURCE_GROUP_API + "/{identifier}")
>   Call<ResponseDTO<ResourceGroupResponse>> getResourceGroup(
> ```

Is there some usage of this API?

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31751)* status: 11 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31751#-:-Mz0iFDx3-DivmYKvWsK:bnfp4nl)* status: 3 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31751)* status: :shipit: complete! ✓

**Pull request merged**
