### PR TITLE
[techdebt]: [PL-29179]: Resolving new Pipeline APIs P2 bugs

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39108)

### CODE REVIEW

**Comment by AnshuH** [comment]
trigger ti0

**Review by RajBaviskar — DISMISSED** [review]

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39108)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by mankrit-singh** [comment]
trigger ti1

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39108)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`WORKSPACE` line 4842 at r5](https://reviewable.io/reviews/harness/harness-core/39108#-NFveBx49ifMLag1ILa6:-NFveBx49ifMLag1ILa7:b-28gsac) ([raw file](https://github.com/harness/harness-core/blob/335612ffd9074154c023c6ffa02f45789c344a2d/WORKSPACE#L4842)):*
> ```Starlark
>     "io.harness:ng-manager-server-spec:1.0.25",
>     "io.harness:platform-server-spec:1.0.10",
>     "io.harness:pipeline-server-spec:1.0.202",
> ```

202 - intentional?

**Review by RajBaviskar — APPROVED** [review]

**Pull request merged**
