### PR TITLE
[fix]: [CDS-82636]: fix for non resolved tags in webhook notification template

### PR DESCRIPTION
**Pull request by rchaudharyy**
## Describe your changes

Fix for non resolved tags in webhook notification template in case tags are expression

If tag is resolvable then it will get resolved otherwise original expression will be returned as visible in below screenshot.

> 
Screenshot 2023-11-15 at 3 03 19 PM

Testing done

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55342)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/55342#-Nj7Rtj4BG6U7UqiC6ud:-Nj7Rtj4BG6U7UqiC6ue:b8qk9js) ([raw file](https://github.com/harness/harness-core/blob/89ffe0cd193ed02b0a4c6ef5cd1af496d82ffebe/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L369)):*
> ```Java
>     List<NGTag> resolvedTags = (List<NGTag>) pmsEngineExpressionService.resolve(
>         ambiance, pipelineExecutionSummaryEntity.getTags(), ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED);
>     webhookNotificationEvent.tag(resolvedTags);
> ```

Can we add tests for the same?
Also, please add testing done in the comments

**Review by sribalij — APPROVED** [review]

**Review by sribalij — COMMENTED** [review]
Add Junit

**Review by sribalij — CHANGES_REQUESTED** [review]
Add Junits

**Comment by rchaudharyy** [comment]
trigger uts

**Comment by rchaudharyy** [comment]
> Details

done

**Comment by rchaudharyy** [comment]
trigger uts

**Comment by rchaudharyy** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/55342#-Nj7Rtj4BG6U7UqiC6ud:-NjII40wCsJjFTUS_T19:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/89ffe0cd193ed02b0a4c6ef5cd1af496d82ffebe/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L369)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add tests for the same?
Also, please add testing done in the comments
</blockquote></details>

Done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/test/java/io/harness/pms/notification/NotificationHelperTest.java` line 662 at r3](https://reviewable.io/reviews/harness/harness-core/55342#-NjIIYli4gfo1gUOcibE:-NjIIYli4gfo1gUOcibF:blcou88) ([raw file](https://github.com/harness/harness-core/blob/187cad72676340e2eb8d701e839e7279428d0828/pipeline-service/service/src/test/java/io/harness/pms/notification/NotificationHelperTest.java#L662)):*
> ```Java
>     JSONArray jsonArray = json.getJSONArray("tag");
>     jsonArray.get(0).toString();
>     assertThat("{\"value\":\"v1\",\"key\":\"k1\"}").isEqualTo(jsonArray.get(0).toString());
> ```

As discussed, please change to k2 , v2

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55342)* status: 2 file(s) to review. 2 change requests. 0 of 2 approvals obtained.

**Comment by rchaudharyy** [comment]
trigger uts

**Review by rchaudharyy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55342)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/pms/notification/NotificationHelperTest.java` line 662 at r3](https://reviewable.io/reviews/harness/harness-core/55342#-NjIIYli4gfo1gUOcibE:-NjLguiM1-0DM3xaqisg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/187cad72676340e2eb8d701e839e7279428d0828/pipeline-service/service/src/test/java/io/harness/pms/notification/NotificationHelperTest.java#L662)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

As discussed, please change to k2 , v2
</blockquote></details>

Done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 367 at r4](https://reviewable.io/reviews/harness/harness-core/55342#-Njeqpli4AeNgQ5Glzg_:-Njeqpli4AeNgQ5Glzga:b-riseb0) ([raw file](https://github.com/harness/harness-core/blob/ff3c521eff4d443231e15a485d85c403015af87f/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L367)):*
> ```Java
>     webhookNotificationEvent.pipelineUrl(pipelineUrl);
>     webhookNotificationEvent.executionUrl(executionUrl);
>     List<NGTag> resolvedTags = (List<NGTag>) pmsEngineExpressionService.resolve(
> ```

Lets call this only if tags contain expressions.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 367 at r4](https://reviewable.io/reviews/harness/harness-core/55342#-Njeqpli4AeNgQ5Glzg_:-NjeqvBwCFMMEVEN8cN5:b-ni4c0l) ([raw file](https://github.com/harness/harness-core/blob/ff3c521eff4d443231e15a485d85c403015af87f/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L367)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Lets call this only if tags contain expressions.
</blockquote></details>

We can discuss on this today.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 367 at r4](https://reviewable.io/reviews/harness/harness-core/55342#-Njeqpli4AeNgQ5Glzg_:-NjfoP_ODdiJARPCwyxB:b-f654qa) ([raw file](https://github.com/harness/harness-core/blob/ff3c521eff4d443231e15a485d85c403015af87f/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L367)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We can discuss on this today.
</blockquote></details>

I meant that we can run a loop first to check if expressions are there or not. 
If expressions are there then only call the `List<NGTag> resolvedTags = (List<NGTag>) pmsEngineExpressionService.resolve(
        ambiance, pipelineExecutionSummaryEntity.getTags(), ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED
`

**Review by rchaudharyy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55342)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 367 at r4](https://reviewable.io/reviews/harness/harness-core/55342#-Njeqpli4AeNgQ5Glzg_:-Njg49Rd9JRB3iDUxZ1x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ff3c521eff4d443231e15a485d85c403015af87f/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L367)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I meant that we can run a loop first to check if expressions are there or not. 
If expressions are there then only call the `List<NGTag> resolvedTags = (List<NGTag>) pmsEngineExpressionService.resolve(
        ambiance, pipelineExecutionSummaryEntity.getTags(), ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED
`
</blockquote></details>

Done.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55342)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 370 at r6](https://reviewable.io/reviews/harness/harness-core/55342#-NjgECzY4C70b-PzGezt:-NjgECzY4C70b-PzGezu:bvi10a4) ([raw file](https://github.com/harness/harness-core/blob/1455f1028d46e27c0050bae9710ac0fc9f45b7d6/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L370)):*
> ```Java
> 
>     boolean isTagsContainExpression = false;
>     for (NGTag tag : pipelineExecutionSummaryEntity.getTags()) {
> ```

nit: lets extract this into a function.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 381 at r6](https://reviewable.io/reviews/harness/harness-core/55342#-NjgEM5I6N7o-yQ_9VQb:-NjgEM5JDzTvZhHSh50Q:bsfm1l2) ([raw file](https://github.com/harness/harness-core/blob/1455f1028d46e27c0050bae9710ac0fc9f45b7d6/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L381)):*
> ```Java
>       webhookNotificationEvent.tag(resolvedTags);
>     } else {
>       webhookNotificationEvent.tag(pipelineExecutionSummaryEntity.getTags());
> ```

nit: can we simplified with something like this```

List<NGTag> resolvedTags = pipelineExecutionSummaryEntity.getTags();
if (isTagsContainExpression) {
   resolvedTags = (List<NGTag>) pmsEngineExpressionService.resolve(
          ambiance, pipelineExecutionSummaryEntity.getTags(), ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED);
}
webhookNotificationEvent.tag(resolvedTags);
```
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 370 at r7](https://reviewable.io/reviews/harness/harness-core/55342#-NjgISYL1X0VJUNfcJcE:-NjgISYL1X0VJUNfcJcF:b-o6s256) ([raw file](https://github.com/harness/harness-core/blob/5ac59a60afeaf43e832cce71cddcb5df98a37ef1/pipeline-service/service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L370)):*
> ```Java
> 
>     boolean isTagsContainExpression = false;
>     for (NGTag tag : pipelineExecutionSummaryEntity.getTags()) {
> ```

nit: what if tags are null?

**Comment by sahilhindwani-harness** [comment]
Can we test a pipeline without tags and only single tag?

**Comment by rchaudharyy** [comment]
> Can we test a pipeline without tags and only single tag?

Done, it's working as expected.

**Comment by rchaudharyy** [comment]
trigger ut7

**Comment by rchaudharyy** [comment]
trigger uts

**Comment by rchaudharyy** [comment]
trigger ut7

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55342)* status: 2 file(s) to review. 1 change requests.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by rchaudharyy** [comment]
> Add Junits

done

**Pull request merged**
