### PR TITLE
[feat]: [PIE-4373]: Add recent executions' field in PipelineMetadata and list view response

### PR DESCRIPTION
**Pull request by namanvermah**
Only the fields have been added, they are not getting populated as of now.
The DTOs added are hidden in openAPI spec as of now, will un-hide them when this feature is released.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35200)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35200)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineSummaryResponseDTO.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/35200#-N6fvnCiAy64s6Zs-MP0:-N6fvnCk7QZ0vYh_SCEw:bmzeohk) ([raw file](https://github.com/harness/harness-core/blob/4220ba18bfaaedea078be4d4bb0d229cd07814d8/954-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineSummaryResponseDTO.java#L48)):*
> ```Java
>   Set<String> modules;
>   ExecutionSummaryInfoDTO executionSummaryInfo;
>   List<RecentExecutionInfoDTO> recentExecutionsInfo;
> ```

Shouldnt this be hidden?

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35200)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineSummaryResponseDTO.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/35200#-N6fvnCiAy64s6Zs-MP0:-N6g1czO2aWWwsIMPPmx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/4220ba18bfaaedea078be4d4bb0d229cd07814d8/954-pms-contracts/src/main/java/io/harness/pms/pipeline/PMSPipelineSummaryResponseDTO.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt this be hidden?
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35200)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35200)* status: :shipit: complete! ✓

**Pull request merged**
