### PR TITLE
feat: [PL-23688]: Updating Title of OpenAPI spec

### PR DESCRIPTION
**Pull request by mankrit-singh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31382)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31382#-:-Mxrz4CxETi-N1QE0efi:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31382#-:-My5pCxZ8SGZMPLLMP7y:bnfp4nl)* status: 1 file(s) to review.

**Review by rijajoo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31382#-:-My5pWVl-Aqw3wRs9pyd:bnfp4nl)* status: 1 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31382)* status: :shipit: complete! ✓

**Pull request merged**
