### PR TITLE
feat: [CDS-40986]: GA FF KEEP_PT_AFTER_K8S_DOWNSCALE

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36475)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 6 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36475)

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36475)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1581 at r2](https://reviewable.io/reviews/harness/harness-core/36475#-N9lKEaR9tMSIMi6VOBO:-N9lKEaR9tMSIMi6VOBP:bmjbpa0) ([raw file](https://github.com/harness/harness-core/blob/29c6603871b5ed87ee7db7e07beab819c32de74d/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1581)):*
> ```Java
>     boolean success = response.getCommandExecutionStatus() == SUCCESS;
>     K8sInstanceSyncResponse k8sInstanceSyncResponse = (K8sInstanceSyncResponse) response.getK8sTaskResponse();
>     boolean deleteTask = success && isEmpty(k8sInstanceSyncResponse.getK8sPodInfoList());
> ```

if we go with the earlier logic, if a customer has `KEEP_PT_AFTER_K8S_DOWNSCALE` FF enabled, then deleteTask will always be `false` .. right ..??
in which case, the updated logic here would be wrong.



_Code quote:_
```Java
 boolean deleteTask = success && isEmpty(k8sInstanceSyncResponse.getK8sPodInfoList());
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36475)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1581 at r2](https://reviewable.io/reviews/harness/harness-core/36475#-N9lKEaR9tMSIMi6VOBO:-N9nkvxIAROpUy5RX3B3:bhzjmwy) ([raw file](https://github.com/harness/harness-core/blob/29c6603871b5ed87ee7db7e07beab819c32de74d/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1581)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

if we go with the earlier logic, if a customer has `KEEP_PT_AFTER_K8S_DOWNSCALE` FF enabled, then deleteTask will always be `false` .. right ..??
in which case, the updated logic here would be wrong.
</blockquote></details>

Yes, deleteTask will always be false now. Fixed it

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36475)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
