### PR TITLE
[feat]: [DEL-4340]: Don't assign tasks to expired immutable delegates

### PR DESCRIPTION
**Pull request by AnupamIO**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36079)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36079)

**Review by mdmilic — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36079)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 963 at r1](https://reviewable.io/reviews/harness/harness-core/36079#-N8iEYHa6zxHE_WSNCm5:-N8iEYHa6zxHE_WSNCm6:b-1fmn4r) ([raw file](https://github.com/harness/harness-core/blob/ce905fdf7b70184af9c2670be3ffdb2dc7bc1064/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L963)):*
> ```Java
>             -> delegate.getStatus() == DelegateInstanceStatus.ENABLED
>                 && delegate.getLastHeartBeat() > oldestAcceptableHeartBeat
>                 && (!delegate.isImmutable() || isActiveImmutableDelegate(delegate)))
> ```

I would put this isImmutable check inside the 'isActiveImmutableDelegate' method.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 963 at r1](https://reviewable.io/reviews/harness/harness-core/36079#-N8iXs0D84DhMXRfD-E4:-N8iXs0E1qppm7Dmy2fz:b-rc6u3u) ([raw file](https://github.com/harness/harness-core/blob/ce905fdf7b70184af9c2670be3ffdb2dc7bc1064/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L963)):*
> ```Java
>             -> delegate.getStatus() == DelegateInstanceStatus.ENABLED
>                 && delegate.getLastHeartBeat() > oldestAcceptableHeartBeat
>                 && (!delegate.isImmutable() || isActiveImmutableDelegate(delegate)))
> ```

why do need this check itself? Immutable delegates also records lastheartbeat, it should works similar to regular delegates. Or is there something different for immutable delegate in recording heartbeat? 
IMO  better avoid adding conditional checks on immutable as it should works same as regular delegate

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36079)* status: :shipit: complete! ✓

**Review by jennyjames21 — COMMENTED** [review]
@mdmilic is immutable delegate not sending hearbeat? Why we need special check for immutable here?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36079#-:-N8kAeUG2u6Q3WN864Uu:bl6d44k)* status: :shipit: complete! ✓

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36079)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java` line 963 at r1](https://reviewable.io/reviews/harness/harness-core/36079#-N8iXs0D84DhMXRfD-E4:-N95yOhoEumqaSANgznh:bxszq25) ([raw file](https://github.com/harness/harness-core/blob/ce905fdf7b70184af9c2670be3ffdb2dc7bc1064/400-rest/src/main/java/software/wings/service/impl/AssignDelegateServiceImpl.java#L963)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why do need this check itself? Immutable delegates also records lastheartbeat, it should works similar to regular delegates. Or is there something different for immutable delegate in recording heartbeat? 
IMO  better avoid adding conditional checks on immutable as it should works same as regular delegate
</blockquote></details>

We are aiming to put expiry time on immutable delegate image versions, same is not true for mutable delegates. Hence this check.

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36079)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by raghuAtWings — COMMENTED** [review]
lets hold on to this change. DO NOT MERGE

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36079#-:-NFtHqJMAfa0I-4SitHC:b-b1wfag)* status: Some of the checks are too old. 3 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Pull request closed without merging**
