### PR TITLE
[fix]: [PL-28807]: removed SAML condition for Auto Invite Accept feature and refactoring

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
removed SAML condition for Auto Invite Accept feature and refactoring

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39400)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 177 at r4](https://reviewable.io/reviews/harness/harness-core/39400#-NFiegmj6xOoBajBEfxI:-NFiegmj6xOoBajBEfxJ:b-uysj8x) ([raw file](https://github.com/harness/harness-core/blob/64d0e4cfc1ec7d0fcd18de51fb39d3f376155fad/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L177)):*
> ```Java
> 
>   @GET
>   @Path("isPLNoEmailForSamlAccountInvitesEnabled")
> ```

This is not a good path, we can change this to something like `saml-account-invites-no-email` or something on the lines. 
Also, let's mark this API internal/hidden to be used only internally, thanks 



_Code quote:_
```Java
"isPLNoEmailForSamlAccountInvitesEnabled"
```

**Review by pbarapatre10 — COMMENTED** [review]
Please also add a UT for the newly added service API on AccountService, thanks.
Also, lets test this a little thoroughly so that no current functionality changes/breaks with these changes, thanks

> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39400#-:-NFifJfX0CYEgqeNI5b_:bc4dnox)* status: 9 file(s) to review. 0 of 2 approvals obtained.

**Comment by kapil-harness** [comment]
trigger ti3

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/39400#-NFqdGNIA10i027mCqSA:-NFqdGNIA10i027mCqSB:b-7b221z) ([raw file](https://github.com/harness/harness-core/blob/2b7b5cc6d85052d29660a14122add3bd2a802736/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L174)):*
> ```Java
>   @GET
>   @Hidden
>   @Path("is-auto-invite-acceptance-enabled")
> ```

Let's not change the already existing endpoint, so as to avoid any contract changes anywhere. My comment was only for the new api-endpoint which you have created. Thanks



_Code quote:_
```Java
@Path("is-auto-invite-acceptance-enabled")
```

**Review by pbarapatre10 — COMMENTED** [review]
LGTM

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39400#-:-NFqdW778Xm7Qf0Yxsuw:bb6ywmx)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/resources/AccountResourceNG.java` line 174 at r5](https://reviewable.io/reviews/harness/harness-core/39400#-NFqdGNIA10i027mCqSA:-NFqkI0s3GLLVXhLDWJk:btla4zi) ([raw file](https://github.com/harness/harness-core/blob/2b7b5cc6d85052d29660a14122add3bd2a802736/400-rest/src/main/java/software/wings/resources/AccountResourceNG.java#L174)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Let's not change the already existing endpoint, so as to avoid any contract changes anywhere. My comment was only for the new api-endpoint which you have created. Thanks
</blockquote></details>

Discussed over call with @kapil-harness & since it is internal API, & not used anywhere else, we should be good here to go ahead. Thanks



_Code quote (from 945-account-mgmt/src/main/java/io/harness/account/AccountClient.java):_
```Java
/isAutoInviteAcceptanceEnabled
```

**Review by pbarapatre10 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39400)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
