### PR TITLE
[feat]: [PLG-2490]: created new endpoint for Canny to create jwt token and redirect URL

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
created new endpoint for Canny to create jwt token and redirect URL

Local testing results:
Screenshot 2023-06-14 at 2 41 53 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49233)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger uts

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49233)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by Xin-Harness — DISMISSED** [review]

**Review by neelam-harness — DISMISSED** [review]

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3613 at r2](https://reviewable.io/reviews/harness/harness-core/49233#-NXyRZX18VNPM9vOOItq:-NXyRZX18VNPM9vOOItr:bj8yopj) ([raw file](https://github.com/harness/harness-core/blob/e22fc1aafb083fbf82c33a18995909850632fbd0/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3613)):*
> ```Java
> 
>     String redirectUrl =
>         String.format("%s?companyID=%s&ssoToken=%s", configuration.getPortal().getCannyBaseUrl(), companyID, jwtToken);
> ```

nit: can a NPE happen?



_Code quote:_
```Java
configuration.getPortal()
```

**Comment by pbarapatre10** [comment]
*[`950-ng-authentication-service/src/main/java/software/wings/beans/CannySsoLoginResponse.java` line 15 at r2](https://reviewable.io/reviews/harness/harness-core/49233#-NXyYR-zAj_0pNUX9Sg_:-NXyYR-zAj_0pNUX9Sga:b-9rcbkv) ([raw file](https://github.com/harness/harness-core/blob/e22fc1aafb083fbf82c33a18995909850632fbd0/950-ng-authentication-service/src/main/java/software/wings/beans/CannySsoLoginResponse.java#L15)):*
> ```Java
> @Data
> @Builder
> public class CannySsoLoginResponse {
> ```

minor: @OwnedBy tag is missing, thanks



_Code quote:_
```Java
@Builder
public class CannySsoLoginResponse {
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3634 at r2](https://reviewable.io/reviews/harness/harness-core/49233#-NXyYy73CuAbQsXimUz2:-NXyYy73CuAbQsXimUz3:bhe3fcp) ([raw file](https://github.com/harness/harness-core/blob/e22fc1aafb083fbf82c33a18995909850632fbd0/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3634)):*
> ```Java
>         .setClaims(userData)
>         .signWith(SignatureAlgorithm.HS256, jwtCannySecret.getBytes("UTF-8"))
>         .compact();
> ```

nit: Question? we don't specify any issuedAt time when generating the token? or does the token by default takes the current DateTime? thanks



_Code quote:_
```Java
    return Jwts.builder()
        .setClaims(userData)
        .signWith(SignatureAlgorithm.HS256, jwtCannySecret.getBytes("UTF-8"))
        .compact();
```

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49233)* status: 8 file(s) to review. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3634 at r2](https://reviewable.io/reviews/harness/harness-core/49233#-NXyYy73CuAbQsXimUz2:-NXygngC8hrvYj7OXK92:buuv5u7) ([raw file](https://github.com/harness/harness-core/blob/e22fc1aafb083fbf82c33a18995909850632fbd0/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3634)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: Question? we don't specify any issuedAt time when generating the token? or does the token by default takes the current DateTime? thanks
</blockquote></details>

nice catch!! 
I have added .setIssuedAt(new Date()) to Jwts

**Review by mohitg0795 — APPROVED** [review]

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3615 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXzn9p5B0oMiFyKCw0J:-NXzn9p5B0oMiFyKCw0K:b6pjfzz) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3615)):*
> ```Java
>         String.format("%s?companyID=%s&ssoToken=%s", configuration.getPortal().getCannyBaseUrl(), companyID, jwtToken);
> 
>     if (returnToUrl != null) {
> ```

This should be StringUtils.isNotEmpty

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3608 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXzn-Cr8YtJuMbsfuWV:-NXzn-Cr8YtJuMbsfuWW:b-qzmag4) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3608)):*
> ```Java
> 
>   @Override
>   public CannySsoLoginResponse generateCannySsoJwt(String returnToUrl, String companyID) throws Exception {
> ```

Why throws Exception? Can we return meaningful errors?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3632 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXznNsWA1NuLccdVZu_:-NXznNsWA1NuLccdVZua:b9pnmi7) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3632)):*
> ```Java
> 
>     return Jwts.builder()
>         .setIssuedAt(new Date())
> ```

Use System.currentTimeMills()  instead

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3612 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXznZ9S63JscaQZoFPB:-NXznZ9S63JscaQZoFPC:b749yly) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3612)):*
> ```Java
>     String jwtToken = createCannyToken(user);
> 
>     String redirectUrl =
> ```

Add Unit test for this method

**Comment by piyush-harness** [comment]
*[`360-cg-manager/config.yml` line 385 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXzmqmt1MN3dLwNe4ZJ:-NXzmqmt1MN3dLwNe4ZK:bo8x9co) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/360-cg-manager/config.yml#L385)):*
> ```YAML
>   jwtExternalServiceSecret: nhUmut2NMcUnsR01OgOz0e51MZ51AqUwrOATJ3fJ
>   jwtZendeskSecret: RdL7j9ZdCz6TVSHO7obJRS6ywYLJjH8tdfPP39i4MbevKjVo
>   jwtCannySecret: yv7TV4NsP4fps8pLdGuVdV8CHgJT3wCaFgTEg7dKcanzKN7C
> ```

Is this a real token?

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49233)* status: 1 file(s) to review.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49233)* status: 1 file(s) to review. 5. unresolved discussions. 

___
*[`360-cg-manager/config.yml` line 385 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXzmqmt1MN3dLwNe4ZJ:-NXzqtpD17hFgfDGQPwr:bh69om9) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/360-cg-manager/config.yml#L385)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Is this a real token?
</blockquote></details>

its not a real secret rather it was randomly generated using https://delinea.com/resources/password-generator-it-tool
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3608 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXzn-Cr8YtJuMbsfuWV:-NXzuNrzDmPoiwc8JMG_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3608)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why throws Exception? Can we return meaningful errors?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3612 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXznZ9S63JscaQZoFPB:-NY-Gbv59xpAT9IyrWE4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3612)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Add Unit test for this method
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3615 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXzn9p5B0oMiFyKCw0J:-NXzr-IoAnrIM9lZlxON:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3615)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This should be StringUtils.isNotEmpty
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3632 at r3](https://reviewable.io/reviews/harness/harness-core/49233#-NXznNsWA1NuLccdVZu_:-NXzrM2J-ZocSF5HsqzI:bl28mb6) ([raw file](https://github.com/harness/harness-core/blob/88b21871edcc7bf2b0a5c0a66198b6ff74e7d670/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3632)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Use System.currentTimeMills()  instead
</blockquote></details>

internally "new Date()" uses System.currentTimeMills() only, so it makes sense to keep it as is.

**Pull request merged**
