### PR TITLE
[fix]: [BT-1696]: Classpath limit set

### PR DESCRIPTION
**Pull request by diptiman-adak**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36789)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
trigger ti2,ti3

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36789)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`dockerization/base-images/Dockerfile-ubi-java-base` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/36789#-NAL_zBRCgRQu_gUyH0m:-NAL_zBRCgRQu_gUyH0n:bbm1cjm) ([raw file](https://github.com/harness/harness-core/blob/3a370cfe357863d81a229ee3e5fc077618ec454e/dockerization/base-images/Dockerfile-ubi-java-base#L23)):*
> ```
> ENV JAVA_HOME=/opt/harness/OpenJDK11/jdk-11.0.15+10
> ENV PATH=$JAVA_HOME/bin:$PATH
> ENV CLASSPATH_LIMIT=200000
> ```

Please set this to 40000

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36789)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`dockerization/base-images/Dockerfile-ubi-java-base` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/36789#-NAL_zBRCgRQu_gUyH0m:-NALa1a6E2KY6Ik9rC7G:b7b7p6b) ([raw file](https://github.com/harness/harness-core/blob/3a370cfe357863d81a229ee3e5fc077618ec454e/dockerization/base-images/Dockerfile-ubi-java-base#L23)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please set this to 40000
</blockquote></details>

400000* (missed one zero earlier)



_Code quote:_
```
200000
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36789)

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36789)* status: :shipit: complete! ✓

**Pull request merged**
