### PR TITLE
[feat]: [CDS-46905]: created getInstancesDetails API

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
Created API getInstancesDetails for getting active instances meta data based on build, environment, infrastructure and pipelineExecutionId. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40480)

### CODE REVIEW

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40480)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 316 at r1](https://reviewable.io/reviews/harness/harness-core/40480#-NHzLr_D0R8ZiHVzbZ6m:-NHzLr_D0R8ZiHVzbZ6n:b-gcnamx) ([raw file](https://github.com/harness/harness-core/blob/0308ab2a02e861d0a86fd6eac3aef34ca1cb3b23/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L316)):*
> ```Java
>     if (infraId != null) {
>       criteria.and(InstanceKeys.infraIdentifier).is(infraId);
>     }
> ```

Add index for this

**Comment by Abhishek-CDC** [comment]
trigger messagecheck

**Comment by Abhishek-CDC** [comment]
trigger messagecheck

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40480)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by Abhishek-CDC** [comment]
*[`126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java` line 316 at r1](https://reviewable.io/reviews/harness/harness-core/40480#-NHzLr_D0R8ZiHVzbZ6m:-NI7KtMw4En-jSrE6wxs:bujqfi5) ([raw file](https://github.com/harness/harness-core/blob/0308ab2a02e861d0a86fd6eac3aef34ca1cb3b23/126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java#L316)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Add index for this
</blockquote></details>

resolved

**Review by Y0709 — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40480)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40480)* status: :shipit: complete! ✓

**Pull request merged**
