### PR TITLE
feat: [CI-5025]: Add support for filePathTrigger task via manager

### PR DESCRIPTION
**Pull request by raghavharness**
## Describe your changes
Add support for filePathTrigger task via manager
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35977)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35977)

**Review by harshjain12 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35977)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMFilePathEvaluator.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/35977#-N8vpLRT0IKDtB4boqhk:-N8vpLRT0IKDtB4boqhl:bu7euw9) ([raw file](https://github.com/harness/harness-core/blob/2aa5c7b4b178c56695681c8aa5a9e63f8c1001cd/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/SCMFilePathEvaluator.java#L61)):*
> ```Java
> @Slf4j
> @Singleton
> public class SCMFilePathEvaluator {
> ```

May be better to have separate classes for manager and delegate

**Review by harshjain12 — APPROVED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35977)* status: :shipit: complete! ✓

**Review by harshjain12 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35977#-:-N8wVfIsBmLOmYIj0jr3:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
