### PR TITLE
feat: [DEL-5101]: mark ecs delegate as deleted if no hearbeat is ther…

### PR DESCRIPTION
**Pull request by arpit3107**
…e for 5 mins

## Describe your changes
Ui dont list ECS delegate in delegate listing page if heartbeat is not there for more than 5 mins. But their tags will still be listed at other places (like task creation, connectors). This leads to user get confused as to where is the tags coming from.

So, we should mark the ECS delegate as deleted so that their tags will not be listed anywhere.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39168)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/39168#-NFCuwcA2FuvAf2qSnyr:-NFCuwcA2FuvAf2qSnys:bqfge8i) ([raw file](https://github.com/harness/harness-core/blob/2b978aa21f5847c5158b34ed393db20355deb080/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L65)):*
> ```Java
>             .fieldName(DelegateKeys.delegateDisconnectDetectorNextIteration)
>             .filterExpander(q
>                 -> q.field(DelegateKeys.status)
> ```

why do you need to add this in the query?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39168)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/39168#-NFCuwcA2FuvAf2qSnyr:-NFE9yo--JLu7Mv3GNRL:b-u89cgc) ([raw file](https://github.com/harness/harness-core/blob/2b978aa21f5847c5158b34ed393db20355deb080/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L65)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do you need to add this in the query?
</blockquote></details>

So that this iterator don't end up picking up deleted delegates and operating on them. This DELETED filter should have been there in the first place, even without my changes

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/39168#-NFCuwcA2FuvAf2qSnyr:-NFERca2-pmvKl9s_H6y:b4wf8ps) ([raw file](https://github.com/harness/harness-core/blob/2b978aa21f5847c5158b34ed393db20355deb080/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L65)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

So that this iterator don't end up picking up deleted delegates and operating on them. This DELETED filter should have been there in the first place, even without my changes
</blockquote></details>

in that case we need to add the right index

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/39168#-NFEhuPu8YZOuV6an5ay:-NFEhuPu8YZOuV6an5az:bqsr8k4) ([raw file](https://github.com/harness/harness-core/blob/2b978aa21f5847c5158b34ed393db20355deb080/400-rest/src/main/java/io/harness/iterator/DelegateDisconnectDetectorIterator.java#L80)):*
> ```Java
>   public void handle(Delegate delegate) {
>     markECSDelegateAsDeleted(delegate);
> ```

Put this in the end. As it will keep fetching query multiple times, we only need check this one per disconnected delegate

**Pull request closed without merging**
