### PR TITLE
[feat]:[IDP-78]: Idp settings API

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Describe your changes
Added API to view/create/update backstage Permissions and userGroup which has all the permissions

##Jira Links
[IDP-78](https://harness.atlassian.net/browse/IDP-78)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[IDP-78]: https://harness.atlassian.net/browse/IDP-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)

### CODE REVIEW

**Comment by sarthakkasat** [comment]
trigger messagecheck

**Comment by sarthakkasat** [comment]
trigger messagecheck

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: 12 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLSUHS6U14l3wjtIqW:-NPLSUHS6U14l3wjtIqX:bnkse2n) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L159)):*
> ```YAML
>         '200':
>           $ref: '#/components/responses/BackstagePermissionsResponse'
>       operationId: get-v1-backstage-permissions
> ```

Do we need v1 here? If not, could we rename all the operationIds?



_Code quote:_
```YAML
get-v1-backstage-permissions
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/beans/entity/BackstagePermissionsEntity.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLKQBn6h19cNa3dT1B:-NPLKQBn6h19cNa3dT1C:bkw5ou7) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/beans/entity/BackstagePermissionsEntity.java#L42)):*
> ```Java
>   @LastModifiedDate Long lastModifiedAt;
>   List<String> permissions;
>   String user_group;
> ```

Can we use camelCase here?



_Code quote:_
```Java
user_group
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLVPP1A_feL5eZVpev:-NPLVPP1A_feL5eZVpew:b8izk55) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L34)):*
> ```Java
>   public static final String MANAGE_PERMISSION = "idp_idpsettings_manage";
>   @Override
>   public Response getV1BackstagePermissions(@Valid BackstagePermissionsRequest body, String harnessAccount) {
> ```

We just need an account identifier right? Do we need the request body?



_Code quote:_
```Java
BackstagePermissionsReques
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLUIOv3yWkFgnMX7JZ:-NPLUIOv3yWkFgnMX7J_:b-t1gigz) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L29)):*
> ```Java
> 
>   @Override
>   public BackstagePermissions findByAccountIdentifier(String accountIdentifier) {
> ```

Could we return Optional?



_Code quote:_
```Java
BackstagePermissions
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 37 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLa-435irYkNtY28JF:-NPLa-435irYkNtY28JG:b3n3zdq) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L37)):*
> ```Java
>   @Override
>   public BackstagePermissions updatePermissions(BackstagePermissions backstagePermissions, String accountIdentifier)
>       throws Exception {
> ```

are we throwing exceptions anywhere in this flow?



_Code quote:_
```Java
Exception
```

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLUIOv3yWkFgnMX7JZ:-NPLkZCs0PmCjq0OMeoE:b-ov919a) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L29)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Could we return Optional?
</blockquote></details>

Do we return Optional in service layer?

**Comment by sarthakkasat** [comment]
*[`idp-service/contracts/openapi/SNAPSHOT/openapi.yaml` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLSUHS6U14l3wjtIqW:-NPLkVJf2EknY6BaftvO:b6wx0vm) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/contracts/openapi/SNAPSHOT/openapi.yaml#L159)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we need v1 here? If not, could we rename all the operationIds?
</blockquote></details>

Will Update

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/beans/entity/BackstagePermissionsEntity.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLKQBn6h19cNa3dT1B:-NPLkO671Mmr1ZfI6L_w:b-q9zpd0) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/beans/entity/BackstagePermissionsEntity.java#L42)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we use camelCase here?
</blockquote></details>

Will update.

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLVPP1A_feL5eZVpev:-NPLkINR50mZJyH7s-X-:bkqu2vu) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L34)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We just need an account identifier right? Do we need the request body?
</blockquote></details>

Yes we just need the accountID, will update.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLUIOv3yWkFgnMX7JZ:-NPLpaJF62KZ4DsAZqvZ:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L29)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

Do we return Optional in service layer?
</blockquote></details>

yes

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/44422#-NPLUIOv3yWkFgnMX7JZ:-NPLr33lA0IDwsdKlWfo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0abc270c3b364c7504e096912bbb03f0f1f4f713/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L29)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.

**Comment by sarthakkasat** [comment]
trigger ut5

**Comment by sarthakkasat** [comment]
trigger ut6

**Comment by sarthakkasat** [comment]
trigger ut7

**Comment by sarthakkasat** [comment]
trigger ut8

**Comment by sarthakkasat** [comment]
trigger ut9

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 5 of 8 files at r2, 1 of 1 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: 13 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 49 at r5](https://reviewable.io/reviews/harness/harness-core/44422#-NPXiutTDEO0uUIEmpGC:-NPXiutU4N52ZyJBlOcd:bbor811) ([raw file](https://github.com/harness/harness-core/blob/6365f116c787319dd6e68c30241e91e4fd8019b8/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L49)):*
> ```Java
>   @Override
>   @NGAccessControlCheck(resourceType = IDP_SETTINGS, permission = MANAGE_PERMISSION)
>   public Response postBackstagePermissions(@Valid BackstagePermissionsRequest body, String harnessAccount) {
> ```

can this method be renamed to something like `createBackstagePermissions`?



_Code quote:_
```Java
postBackstagePermissions
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 66 at r5](https://reviewable.io/reviews/harness/harness-core/44422#-NPXjBanB0HR3Fclz7dv:-NPXjBanB0HR3Fclz7dw:b-pfl0um) ([raw file](https://github.com/harness/harness-core/blob/6365f116c787319dd6e68c30241e91e4fd8019b8/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L66)):*
> ```Java
>   @Override
>   @NGAccessControlCheck(resourceType = IDP_SETTINGS, permission = MANAGE_PERMISSION)
>   public Response putBackstagePermissions(@Valid BackstagePermissionsRequest body, String harnessAccount) {
> ```

can this method be renamed to something like `updateBackstagePermissions`?



_Code quote:_
```Java
putBackstagePermissions
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 52 at r5](https://reviewable.io/reviews/harness/harness-core/44422#-NPXjSD02lqJSJyfkGaq:-NPXjSD02lqJSJyfkGar:bu8ieyi) ([raw file](https://github.com/harness/harness-core/blob/6365f116c787319dd6e68c30241e91e4fd8019b8/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L52)):*
> ```Java
>     String configPermissions = String.join(",", permissions);
>     Map<String, String> data = new HashMap<>();
>     data.put("permissions", configPermissions);
> ```

Can we define constants for all these strings? also for the join character/string?



_Code quote:_
```Java
"permissions"
```
___
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 68 at r5](https://reviewable.io/reviews/harness/harness-core/44422#-NPXjqvxAQeKIHztcHIB:-NPXjqvxAQeKIHztcHIC:b50l4cj) ([raw file](https://github.com/harness/harness-core/blob/6365f116c787319dd6e68c30241e91e4fd8019b8/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L68)):*
> ```Java
>     data.put("permissions", configPermissions);
>     data.put("userGroup", backstagePermissions.getUserGroup());
>     k8sClient.updateConfigMapData(getNamespaceForAccount(accountIdentifier), "settings-config", data, true);
> ```

Can we move this to a common method to avoid duplication?



_Code quote:_
```Java
    List<String> permissions = backstagePermissions.getPermissions();
    String configPermissions = String.join(",", permissions);
    Map<String, String> data = new HashMap<>();
    data.put("permissions", configPermissions);
    data.put("userGroup", backstagePermissions.getUserGroup());
    k8sClient.updateConfigMapData(getNamespaceForAccount(accountIdentifier), "settings-config", data, true);
```

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java` line 52 at r5](https://reviewable.io/reviews/harness/harness-core/44422#-NPXjSD02lqJSJyfkGaq:-NPY4NXd1euumnh1afCe:b7jisst) ([raw file](https://github.com/harness/harness-core/blob/6365f116c787319dd6e68c30241e91e4fd8019b8/idp-service/service/src/main/java/io/harness/idp/settings/service/BackstagePermissionsServiceImpl.java#L52)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we define constants for all these strings? also for the join character/string?
</blockquote></details>

Will update. For join it is a character sequence

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 66 at r5](https://reviewable.io/reviews/harness/harness-core/44422#-NPXjBanB0HR3Fclz7dv:-NPY4qQiEydrniLc40BV:bm2cxhu) ([raw file](https://github.com/harness/harness-core/blob/6365f116c787319dd6e68c30241e91e4fd8019b8/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L66)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

can this method be renamed to something like `updateBackstagePermissions`?
</blockquote></details>

Will update

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by sarthakkasat** [comment]
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/44422#-NPaLR_W2vGrFEa6kOca:-NPaOBra7qMFgSSmpDeO:b-eylqha) ([raw file](https://github.com/harness/harness-core/blob/55efc12b2151425c8a65cd34db2040f0f9c47315/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L55)):*
> thats
Duplicate key exception will be thrown by mongo query, do we need to handle it seperately?

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java` line 55 at r6](https://reviewable.io/reviews/harness/harness-core/44422#-NPaLR_W2vGrFEa6kOca:-NPaS48cCjTPAvAc_xkQ:b-tf7srx) ([raw file](https://github.com/harness/harness-core/blob/55efc12b2151425c8a65cd34db2040f0f9c47315/idp-service/service/src/main/java/io/harness/idp/settings/resources/BackstagePermissionsApiImpl.java#L55)):*
<details><summary><i>Previously, sarthakkasat (Sarthak Kasat) wrote…</i></summary><blockquote>

> thats
Duplicate key exception will be thrown by mongo query, do we need to handle it seperately?
</blockquote></details>

Not sure but will client need to know that , if api are used by user though frontend , showing 500 internal error may not make sense , as it will encourage them to retry . Any how i am approving it , check with team if it is required raise a separate pr

**Review by deepharness — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 1 of 8 files at r2, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: :shipit: complete! ✓

**Review by deepharness — APPROVED** [review]
> Reviewed 15 of 19 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 15 of 19 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44422)* status: :shipit: complete! ✓

**Pull request merged**
