### PR TITLE
fix: [CDS-81943]: Move Custom Stage V1 to NG-Manager

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Moved Custom stage plan creator, variable creator, filter creator, step, and POJOs from pipeline service to ng manager for v1

**Testing:** Ran v1 and v0 pipeline with custom stage locally.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: 18 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentAbstractStageNode.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5n0nAxRrqw1Oz5-v:-Nha5VUB65RczSC3vU3F:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentAbstractStageNode.java#L19)):*
> ```Java
> 
> @Data
> public abstract class DeploymentAbstractStageNode extends AbstractStageNodeV1 {
> ```

why is this needed?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/v1/EmptyVariableCreator.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5z6Z0BcYMjPMTu7f:-Nha5z6Z0BcYMjPMTu7g:b-w9xri) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/v1/EmptyVariableCreator.java#L28)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public class EmptyVariableCreator extends ChildrenVariableCreatorV1<DummyNodeV1> {
> ```

lets put this in sdk?
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageConfig.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5Lf8B-hsHXKRdMWB:-Nha5Lf8B-hsHXKRdMWC:b-dw1cgw) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageConfig.java#L26)):*
> ```Java
>   String uuid;
>   @NotNull @Size(min = 1) List<JsonNode> steps;
>   List<JsonNode> rollback_steps;
> ```

Here maybe we can use JsonProperty so java fields are following syntax
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageNode.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5jEP9Cz_hwGt6kd0:-Nha5jEP9Cz_hwGt6kd1:b-wdal4i) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageNode.java#L23)):*
> ```Java
> @OwnedBy(PIPELINE)
> @RecasterAlias("io.harness.cdng.creator.plan.stage.v1.CustomStageNode")
> public class CustomStageNode extends DeploymentAbstractStageNode {
> ```

Why we dont have CustomAbstractStageNode instead?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: 18 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentAbstractStageNode.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5n0nAxRrqw1Oz5-v:-Nha7lTr3H_dvgxY_zJi:bin39tm) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentAbstractStageNode.java#L19)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

this can be extended by the deployment stage node when created for v1, similar one we have in v0 as well
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/v1/EmptyVariableCreator.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5z6Z0BcYMjPMTu7f:-Nha7DcTCRstyPOM65nF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/v1/EmptyVariableCreator.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets put this in sdk?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageConfig.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5Lf8B-hsHXKRdMWB:-Nha7CGKD-pSrHGOMeKI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageConfig.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Here maybe we can use JsonProperty so java fields are following syntax
</blockquote></details>

Done.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageNode.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5jEP9Cz_hwGt6kd0:-Nha7bKV7kmMKGbslGAy:b-ykbm4j) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageNode.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why we dont have CustomAbstractStageNode instead?
</blockquote></details>

this is analogous to PmsAbstractStageNode, as this is in CD, named it like this, we also have DeploymentAbstractStageNode in V0

**Review by archit-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: 18 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageNode.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5jEP9Cz_hwGt6kd0:-NhaCMIt1bSle57HtxEh:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/CustomStageNode.java#L23)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

this is analogous to PmsAbstractStageNode, as this is in CD, named it like this, we also have DeploymentAbstractStageNode in V0
</blockquote></details>

done
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentAbstractStageNode.java` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/54592#-Nha5n0nAxRrqw1Oz5-v:-NhaCLJE9pqpl1vGfxDL:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b13a33ffaa80027cb89da4cb3f816d0c79aa962e/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentAbstractStageNode.java#L19)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

this can be extended by the deployment stage node when created for v1, similar one we have in v0 as well
</blockquote></details>

done

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 12 of 18 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger ut9

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54592)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
