### PR TITLE
feat: [PL-30822]: Fetch active streaming destinations

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
To start with streaming audit we events to external system, we first need to get active streaming destinations. This PR covers fetching of active streaming destinations.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42425)

### CODE REVIEW

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42425)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`project/run-configurations/AuditEventStreamingApp.xml` line 9 at r2](https://reviewable.io/reviews/harness/harness-core/42425#-NLQK39K2yBeWL3raa2h:-NLQK39K2yBeWL3raa2i:b-e4tol7) ([raw file](https://github.com/harness/harness-core/blob/6765dbf76184d2870c4eefe9ec67daa9c8b9ae15/project/run-configurations/AuditEventStreamingApp.xml#L9)):*
> ```XML
>                     blaze-command="run"
>                     keep-in-sync="true">
>         <blaze-target>//audit-event-streaming/service:module</blaze-target>
> ```

why do we need service
___
*[`project/run-configurations/AuditEventStreamingApp.xml` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/42425#-NLQK-YS8_nGmNJx_EBa:-NLQK-YS8_nGmNJx_EBb:bb2rpj9) ([raw file](https://github.com/harness/harness-core/blob/6765dbf76184d2870c4eefe9ec67daa9c8b9ae15/project/run-configurations/AuditEventStreamingApp.xml#L11)):*
> ```XML
>         <blaze-target>//audit-event-streaming/service:module</blaze-target>
>         <blaze-user-exe-flag>server</blaze-user-exe-flag>
>         <blaze-user-exe-flag>$PROJECT_DIR$/../audit-event-streaming/service/src/main/resources/audit-event-streaming-config.yml</blaze-user-exe-flag>
> ```

it's changed to application.yml

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42425)* status: 12 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`project/run-configurations/AuditEventStreamingApp.xml` line 9 at r2](https://reviewable.io/reviews/harness/harness-core/42425#-NLQK39K2yBeWL3raa2h:-NLQbIfb6OrsOtklZceo:b-ebhhlt) ([raw file](https://github.com/harness/harness-core/blob/6765dbf76184d2870c4eefe9ec67daa9c8b9ae15/project/run-configurations/AuditEventStreamingApp.xml#L9)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

why do we need service
</blockquote></details>

because BUILD.bazel is present in audit-event-streaming/service path
___
*[`project/run-configurations/AuditEventStreamingApp.xml` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/42425#-NLQK-YS8_nGmNJx_EBa:-NLQdA7ZBhe209C6narF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6765dbf76184d2870c4eefe9ec67daa9c8b9ae15/project/run-configurations/AuditEventStreamingApp.xml#L11)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

it's changed to application.yml
</blockquote></details>

Done.

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42425)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Comment by nishantsaini20** [comment]
trigger ti3

**Review by reetika04 — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42425)* status: 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42425)* status: :shipit: complete! ✓

**Pull request merged**
