### PR TITLE
[feat]: [PIE-3851]: Use Pipeline YAML instead of db entity to check for template references

### PR DESCRIPTION
**Pull request by namanvermah**
Pipeline Entity in DB has a flag templateReference which tells whether the pipeline has a templateRef in it or not. However, we need to remove the usage of the DB flag now, because the with git simplification, the YAML on Git can easily be outdated wrt the DB entry. Hence, we need to use the value of the flag in the YAML and not in the DB.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33526)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger ti1, ti3

**Review by inderschera — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33526)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33526)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33526)* status: :shipit: complete! ✓

**Pull request merged**
