### PR TITLE
[feat]: [CDS-49549]: moving service and related classes into separate bazel p…

### PR DESCRIPTION
**Pull request by markoharness**
…ackages

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42079)

### CODE REVIEW

**Comment by markoharness** [comment]
trigger messagecheck

**Review by puthrayaharness — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraUseFromStage.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/42079#-NKy8nFjBwY92pFrcGDL:-NKy8nFjBwY92pFrcGDM:b-olddrs) ([raw file](https://github.com/harness/harness-core/blob/1bac6906ee21207cdb38122c304e58ad57740712/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraUseFromStage.java#L32)):*
> ```Java
> @SimpleVisitorHelper(helperClass = InfraUseFromStageVisitorHelper.class)
> @TypeAlias("infraUseFromStage")
> @RecasterAlias("io.harness.cdng.infra.InfraUseFromStage")
> ```

can we confirm with Pipeline team if changing this recaster alias is okay ?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42079)* status: 103 file(s) to review. 1 change requests. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraSectionStepParameters.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/42079#-NL0K7QW7IaBg0oiQfEq:-NL0K7QW7IaBg0oiQfEr:b4rxjv2) ([raw file](https://github.com/harness/harness-core/blob/62cb41645e221589a995fcc1d13228625f69bb50/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraSectionStepParameters.java#L26)):*
> ```Java
> @Builder
> @TypeAlias("infraSectionStepParameters")
> @RecasterAlias("io.harness.cdng.infra.steps.InfraSectionStepParameters")
> ```

dont change any recaster alias, package you can change but not this annotation value

**Comment by markoharness** [comment]
:lgtm:

**Comment by markoharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraSectionStepParameters.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/42079#-NL0K7QW7IaBg0oiQfEq:-NL0LNWy1cbezPMEBX-H:b-ruup5u) ([raw file](https://github.com/harness/harness-core/blob/62cb41645e221589a995fcc1d13228625f69bb50/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraSectionStepParameters.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

dont change any recaster alias, package you can change but not this annotation value
</blockquote></details>

reverted to the original value

**Comment by markoharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraUseFromStage.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/42079#-NKy8nFjBwY92pFrcGDL:-NL0LWof6oFzZvpiG_Mx:b-ruup5u) ([raw file](https://github.com/harness/harness-core/blob/1bac6906ee21207cdb38122c304e58ad57740712/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfraUseFromStage.java#L32)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we confirm with Pipeline team if changing this recaster alias is okay ?
</blockquote></details>

reverted to the original value

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 103 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42079)* status: 103 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42079)* status: 103 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by markoharness** [comment]
trigger ti0,ti1,ti2,ti3,ti4,ft1,ft2

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 96 of 103 files at r1, 4 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42079)* status: 100 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 94 of 103 files at r1, 4 of 5 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42079)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 94 of 103 files at r1, 4 of 5 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42079#-:-NLLPedY5-TCvP9rK1s-:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
