### PR TITLE
feat: [PL-23733]: Endpoints for fetching both inherited and user groups of a scope

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33052)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
pr_apibackwardcompatibility

**Comment by diptiman-adak** [comment]
trigger pr_apibackwardcompatibility

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r5, 12 of 19 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33052)* status: 21 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateUserGroupServiceImpl.java` line 179 at r17](https://reviewable.io/reviews/harness/harness-core/33052#-N2US6n98XEBrQ-mypeT:-N2US6n98XEBrQ-mypeU:bokme1h) ([raw file](https://github.com/harness/harness-core/blob/10b125425fb312f6df8143fab99aef061cdeb7f9/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/AggregateUserGroupServiceImpl.java#L179)):*
> ```Java
>                 && resourceGroupMap.containsKey(roleAssignmentDTO.getResourceGroupIdentifier()))
>         .collect(Collectors.groupingBy(roleAssignment
>             -> roleAssignment.getPrincipal().getIdentifier(),
> ```

This map should be based on Principal Scope Level and Identifier both, otherwise it might create problems when we have multiple User Groups with same identifier in different scopes.
___
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/NGSamlUserGroupSync.java` line 102 at r17](https://reviewable.io/reviews/harness/harness-core/33052#-N2UT0dhCP8ruZvFM8X9:-N2UT0dhCP8ruZvFM8XA:b-9v09vq) ([raw file](https://github.com/harness/harness-core/blob/10b125425fb312f6df8143fab99aef061cdeb7f9/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/NGSamlUserGroupSync.java#L102)):*
> ```Java
>   @VisibleForTesting
>   void removeUsersFromScopesPostSync(String userId) {
>     // discuss
> ```

Remove this comment.

**Comment by naman-goenka** [comment]
trigger ti3

**Pull request closed without merging**
