### PR TITLE
feat: [PIE-5456]: FilterCreator for Pipeline Stage

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38065)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 20 Issues 
* Code issue 20 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38065)

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/LocalSchemaGetter.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/38065#-NDReGTR4c6_Wn_xdDAL:-NDReGTT0dj7St70-4n5:bh2z637) ([raw file](https://github.com/harness/harness-core/blob/40ef1435aa2bd982dac8673e16063794a6240021/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/LocalSchemaGetter.java#L61)):*
> ```Java
>         accountIdentifier, null, null, null, yamlSchemaWithDetailsList));
>     // TODO: uncomment this to enable schema for Pipeline Stage
>     // partialSchemaDTOList.add(pipelineStageYamlSchemaService.getPipelineStageYamlSchema(
> ```

Do we have any FF for this feature? If yes then we can add the pipelineStageSchema behind the ff. Else each time we want to save pipeline with pipelineStage, code change will be needed.

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 1 of 7 files at r2, 11 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38065)* status: 15 file(s) to review. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 9 of 13 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38065)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/38065#-NDSaD8H9FMbilsnqkRi:-NDSaD8o8iUCZZUDyaRY:b3zanxr) ([raw file](https://github.com/harness/harness-core/blob/485f80639535da3bc12cd3bdd3d266d2bce9f645/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L146)):*
> ```Java
>                    .availableAtOrgLevel(false)
>                    .availableAtAccountLevel(false)
>                    .clazz(PipelineStageNode.class)
> ```

why approval stage node got removed?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/LocalSchemaGetter.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/38065#-NDReGTR4c6_Wn_xdDAL:-NDSa_OY-y1bgDpGfFvr:b-ibsqux) ([raw file](https://github.com/harness/harness-core/blob/40ef1435aa2bd982dac8673e16063794a6240021/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/LocalSchemaGetter.java#L61)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Do we have any FF for this feature? If yes then we can add the pipelineStageSchema behind the ff. Else each time we want to save pipeline with pipelineStage, code change will be needed.
</blockquote></details>

We should add FF for complete feature

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38065)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/38065#-NDSaD8H9FMbilsnqkRi:-NDSfgkY-hFmi9a68DI7:b-6yyrl1) ([raw file](https://github.com/harness/harness-core/blob/485f80639535da3bc12cd3bdd3d266d2bce9f645/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/OrchestrationStepsModuleRegistrars.java#L146)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why approval stage node got removed?
</blockquote></details>

It was added wrongly for PipelineStage. Approval stage node is still there. Same was added for Pipeline Stage, which I have corrected it here
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/LocalSchemaGetter.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/38065#-NDReGTR4c6_Wn_xdDAL:-NDSfsGT2noPbbextgOz:b4dmd6i) ([raw file](https://github.com/harness/harness-core/blob/40ef1435aa2bd982dac8673e16063794a6240021/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/LocalSchemaGetter.java#L61)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We should add FF for complete feature
</blockquote></details>

Currently we do not check for schema for newly added stage using feature flag. I have created the ticket and assigned it to brijesh. Once that is merged, we can remove this comment.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 13 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38065)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 12 files at r1, 10 of 13 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38065)* status: :shipit: complete! ✓

**Pull request merged**
