### PR TITLE
feat: [GTM-1052]: Added telemetry for user invite to CG

### PR DESCRIPTION
**Pull request by allenthom**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33357)

### CODE REVIEW

**Comment by allenthom** [comment]
trigger messagecheck

**Review by nanaxuHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33357)* status: :shipit: complete! ✓

**Review by pranil-harness — APPROVED** [review]

**Review by nanaxuHarness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33357)* status: :shipit: complete! ✓

**Review by nanaxuHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33357)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1791 at r2](https://reviewable.io/reviews/harness/harness-core/33357#-N2Xto37Cm0OolLTwbfA:-N2Xto37Cm0OolLTwbfB:brt84wl) ([raw file](https://github.com/harness/harness-core/blob/4cea1597749501d1cdddb2a976f7369b606f28a2/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1791)):*
> ```Java
>     HashMap<String, Object> groupProperties = new HashMap<>();
>     groupProperties.put("group_id", accountId);
>     groupProperties.put("group_type", "Account");
> ```

is `group_type` enum?
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1803 at r2](https://reviewable.io/reviews/harness/harness-core/33357#-N2XtwqN7KuX2tyHZJzE:-N2XtwqN7KuX2tyHZJzF:b-8o0zet) ([raw file](https://github.com/harness/harness-core/blob/4cea1597749501d1cdddb2a976f7369b606f28a2/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1803)):*
> ```Java
>     properties.put("platform", "CG");
>     // Wait 20 seconds, to ensure identify is sent before track
>     ScheduledExecutorService tempExecutor = Executors.newSingleThreadScheduledExecutor();
> ```

is this 20 seconds wait asynchronous? will it slow down the api response by 20 seconds?

**Comment by allenthom** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1791 at r2](https://reviewable.io/reviews/harness/harness-core/33357#-N2Xto37Cm0OolLTwbfA:-N2XuhPPDEwNHyup4rb-:b58ulsv) ([raw file](https://github.com/harness/harness-core/blob/4cea1597749501d1cdddb2a976f7369b606f28a2/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1791)):*
<details><summary><i>Previously, nanaxuHarness (Nana Xu) wrote…</i></summary><blockquote>

is `group_type` enum?
</blockquote></details>

No, it is a string

**Comment by allenthom** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 1803 at r2](https://reviewable.io/reviews/harness/harness-core/33357#-N2XtwqN7KuX2tyHZJzE:-N2XukaQD3R3ZwwbeTwF:b-wxn5z5) ([raw file](https://github.com/harness/harness-core/blob/4cea1597749501d1cdddb2a976f7369b606f28a2/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L1803)):*
<details><summary><i>Previously, nanaxuHarness (Nana Xu) wrote…</i></summary><blockquote>

is this 20 seconds wait asynchronous? will it slow down the api response by 20 seconds?
</blockquote></details>

The 20 seconds wait is async because we want to make sure track event is sent after the group and identify events. Also, this won't slow down the api because it is on a separate thread.

**Review by nanaxuHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33357)* status: :shipit: complete! ✓

**Pull request merged**
