### PR TITLE
feat: [PL-30712]: Disable streaming destination on retry exhaustion

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
For a streaming destination the audit events are tried to publish for a certain number of times only. If the all the retries are exhausted and still its a failure attempt to publish then in that case the streaming destination should be marked as INACTIVE.  This PR takes care of the mentioned scenario.

Testing:
- Tested locally.
- Added UTs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2_iN1DIHCLhd7amqH:-NM2_iN1DIHCLhd7amqI:b-tsnlm2) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java#L28)):*
> ```Java
>   public static AuditEventStreamingConfig auditEventStreamingConfig(Environment environment) throws IOException {
>     String configFilePath = environment.getProperty("config-file",
>         "/Users/nishantsaini/IdeaProjects/harness-core/audit-event-streaming/service/src/main/resources/application.yml");
> ```

This is not right

**Comment by piyush-harness** [comment]
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingModule.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2a5NHB4Ikn5WaTSV6:-NM2a5NHB4Ikn5WaTSV7:bjoq2hf) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingModule.java#L27)):*
> ```Java
>   @Override
>   protected void configure() {
>     install(new StreamingDestinationClientModule(auditEventStreamingConfig.getAuditClientConfig(),
> ```

Why are we calling NG manager , shouldn't streaming destination be stored in Platform Service DB?

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 24 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2_iN1DIHCLhd7amqH:-NM2bunK2k1d-I9lJXFx:bfw1s9e) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java#L28)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This is not right
</blockquote></details>

Thank for point this. This was done for testing purpose. Will revert it back to correct path.
___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingModule.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2a5NHB4Ikn5WaTSV6:-NM2bb117BMwHWR8MS8Q:btkno0l) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingModule.java#L27)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why are we calling NG manager , shouldn't streaming destination be stored in Platform Service DB?
</blockquote></details>

Every module in Platform Service has its own db. For Streaming related collections we are using Audit DB, therefore using audit client.

**Review by reetika04 — DISMISSED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 24 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 23 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/ServiceSecrets.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2r_su50Rc4K7mkY95:-NM2r_su50Rc4K7mkY96:bfg03yk) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/ServiceSecrets.java#L21)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class ServiceSecrets {
>   @ConfigSecret String ngManagerServiceSecret;
> ```

Can we rename this to avoid confusion?

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2_iN1DIHCLhd7amqH:-NM7YIQBEwwP-t_Yi7kI:bossto8) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java#L28)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Thank for point this. This was done for testing purpose. Will revert it back to correct path.
</blockquote></details>

Replace the logic completely 
___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/ServiceSecrets.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2r_su50Rc4K7mkY95:-NM7YG3pC-PBvLGAyZep:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/ServiceSecrets.java#L21)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we rename this to avoid confusion?
</blockquote></details>

Done.

**Comment by piyush-harness** [comment]
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2_iN1DIHCLhd7amqH:-NM8gvmY-Md8YGRnieAt:b-qs09cx) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java#L28)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Replace the logic completely 
</blockquote></details>

This won't work in deployment environment as file is loaded from external location like /opt/harness

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/42719#-NM2_iN1DIHCLhd7amqH:-NM8ubKe4m3FPNEkvHvq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2dff9bbf144bdc9b175c910df35611c0d4811258/audit-event-streaming/service/src/main/java/io/harness/auditevent/streaming/config/AuditEventStreamingConfiguration.java#L28)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This won't work in deployment environment as file is loaded from external location like /opt/harness
</blockquote></details>

Done.

**Review by piyush-harness — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 7 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719#-:-NM9KyeP7tvmzq5qzYnr:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — DISMISSED** [review]
> Reviewed 5 of 7 files at r2, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 1 file(s) to review.

**Comment by nishantsaini20** [comment]
trigger ti3

**Comment by nishantsaini20** [comment]
trigger ti1

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42719)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
