### PR TITLE
[feat]: [CDS-47036] Asg NG Blue Green Swap Service Manager Changes

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Asg NG Blue Green Swap Service Manager Changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42498)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLdqoOS0yMb1JIxfXfD:-NLdqoOS0yMb1JIxfXfE:b-6dhibh) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L145)):*
> ```Java
> 
>     if (EmptyPredicate.isEmpty(asgBlueGreenSwapServiceStepParameters.asgBlueGreenDeployFqn)) {
>       return skipTaskRequest(ambiance, ASG_BLUE_GREEN_DEPLOY_STEP_MISSING);
> ```

should we fail here or just skip this step?

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceOutcome.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLeSAMgBjuD_GgTLJtg:-NLeSAMh4Sj6LgleK7Ky:b-104tuf) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceOutcome.java#L36)):*
> ```Java
>   String stageListenerRuleArn;
>   String stageTargetGroupArn;
>   boolean trafficShifted;
> ```

why do we need this boolean?

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStartOutcome.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLeSP4oB4aMkIPvDCF9:-NLeSP4oB4aMkIPvDCFA:baei3de) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStartOutcome.java#L28)):*
> ```Java
> @JsonTypeName("asgBlueGreenSwapServiceStartOutcome")
> @RecasterAlias("io.harness.cdng.aws.asg.AsgBlueGreenSwapServiceStartOutcome")
> public class AsgBlueGreenSwapServiceStartOutcome implements Outcome, ExecutionSweepingOutput {
> ```

what is the use of this Outcome object?

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLeSfPz-S0BMf7xlilt:-NLeSfQ-5upzhPQiIbK5:bjpgjr4) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L158)):*
> ```Java
> 
>     if (!asgBlueGreenPrepareRollbackDataOptional.isFound() || !asgBlueGreenDeployDataOptional.isFound()) {
>       return skipTaskRequest(ambiance, ASG_BLUE_GREEN_DEPLOY_STEP_MISSING);
> ```

skip or fail?

**Comment by arvind-choudhary-h** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceRequest.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLedUni4MD0EqQyPrX2:-NLedUnj14s1uv2nGIu6:b-w604x3) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceRequest.java#L31)):*
> ```Java
>   @NonFinal @Expression(ALLOW_SECRETS) AsgInfraConfig asgInfraConfig;
>   @NonFinal @Expression(ALLOW_SECRETS) Integer timeoutIntervalInMin;
>   @NonFinal @Expression(ALLOW_SECRETS) AsgLoadBalancerConfig asgLoadBalancerConfig;
> ```

we can allow list here. and what is oldServiceName? oldAsgName?

**Comment by arvind-choudhary-h** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceResult.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLedaN-4ViPg2-BoxSr:-NLedaN-4ViPg2-BoxSs:bjs44m) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceResult.java#L21)):*
> ```Java
> public class AsgBlueGreenSwapServiceResult {
>   private boolean trafficShifted;
>   private String infrastructureKey;
> ```

can return list here. and what is the use of trafficShifted?

**Comment by arvind-choudhary-h** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgLoadBalancerConfig.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLedhQbEw9FJQVtOt5Z:-NLedhQbEw9FJQVtOt5_:b-rjfefn) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgLoadBalancerConfig.java#L31)):*
> ```Java
>   @NonFinal @Expression(ALLOW_SECRETS) String prodListenerArn;
>   @NonFinal @Expression(ALLOW_SECRETS) String prodListenerRuleArn;
>   String prodTargetGroupArn;
> ```

we can remove this info. There can be multiple target groups.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 33 of 38 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42498)* status: 38 file(s) to review. 0 of 2 approvals obtained.

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42498)* status: 38 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceOutcome.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLeSAMgBjuD_GgTLJtg:-NLf6AB40guYJDNjxw7o:bfv7qsj) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceOutcome.java#L36)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

why do we need this boolean?
</blockquote></details>

it was there in ECS. But yes when I implemented the delegate changes - I found it is not used there also anywhere. so will remove that
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStartOutcome.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLeSP4oB4aMkIPvDCF9:-NLf6WdP4_OQIuUNEolm:bgju747) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStartOutcome.java#L28)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

what is the use of this Outcome object?
</blockquote></details>

it was there in ECS. But yes when I implemented the delegate changes - I found it is not used there also anywhere. so will remove that
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLdqoOS0yMb1JIxfXfD:-NLf6_ryD_Uw7WVYUFt1:b-t4q1aa) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L145)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

should we fail here or just skip this step?
</blockquote></details>

both can be done, let us just skip for now
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLeSfPz-S0BMf7xlilt:-NLf6dfwDxgBWGimKph4:b-t4q1aa) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgBlueGreenSwapServiceStep.java#L158)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

skip or fail?
</blockquote></details>

both can be done, let us just skip for now
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceRequest.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLedUni4MD0EqQyPrX2:-NLf6hRf5uZBdz3JOM6j:b-vtgb71) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceRequest.java#L31)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

we can allow list here. and what is oldServiceName? oldAsgName?
</blockquote></details>

yes. oldAsgname - yes. 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceResult.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLedaN-4ViPg2-BoxSr:-NLf6kz-8eWYno_YPp0L:b-hy5qgf) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgBlueGreenSwapServiceResult.java#L21)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

can return list here. and what is the use of trafficShifted?
</blockquote></details>

replied above
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgLoadBalancerConfig.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/42498#-NLedhQbEw9FJQVtOt5Z:-NLf6mik8XPap5ywi3nY:bb7m07t) ([raw file](https://github.com/harness/harness-core/blob/7718738ba204cb5a9048a4cb99eaf866f8b02b8f/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/aws/asg/AsgLoadBalancerConfig.java#L31)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

we can remove this info. There can be multiple target groups.
</blockquote></details>

okay

**Review by vitsafronovici — DISMISSED** [review]
> Reviewed 11 of 38 files at r1, 26 of 27 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42498)* status: 27 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42498)* status: 27 file(s) to review. 7. unresolved discussions.

**Pull request merged**
