### PR TITLE
techdebt: [CDS-81810]: Break GitSyncConnectorHelper into an interface and move unrelated methods out

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Change is to break GitSyncConnectorHelper into a interface
### 1. Why we made the change ? 
There is a cyclic dependency in the code which Guice tries to resolve by creating a proxy class for GitSyncConnectorHelper. However, since GitSyncConnectorHelper is not an interface, this is not possible and this can some time break NG Manager application depending on the order of resource **Initialization**
### 2. What is the change ?
Change is to break GitSyncConnectorHelper into a interface.
For this, following have been done
- Move out unrelated methods to their caller classes ( methods that being called from a single class )
- Once we have similar kind of methods ( like getScmConnector etc ), extract out interface from GitSyncConnectorHelper
- Rename GitSyncConnectorHelper to GitSyncConnectorService and create an implementation class
### 3. What will be the impact ?
There should be no functional impact
### 4. Is there a Design Doc / Tech Spec for feature attached in the PR Description?
Not needed. This is a tech debt item 
## Testing

- [ ]  Have you added Unit Tests for the Changes
Not needed, since we are only moving methods
- [ ]  Have you added Automation for the Changes
Not needed, since we are only moving methods
- [ ]  Have you run Sanity for existing features
Yes
- [ ]  Single PR may contain changes in multiple msvc, have you tested for inter-operability and backward compatibility?
Its a change in single service

## Feature Flags

- [ ]  Have you added / removed a feature flag in the code base : No
- [ ]  Have you ensured functionality is not breaking with or without Enabling FF
- [ ]  Have you created ticket for removing FF once GA’d.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
-
Specific builds
    - `trigger manager`
    - `trigger dms`
    - `trigger ng_manager`
    - `trigger cvng `
    - `trigger cmdlib`
    - `trigger template_svc`
    - `trigger events_fmwrk_monitor`
    - `trigger event_server`
    - `trigger change_data_capture`
    -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54179)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java` line 251 at r1](https://reviewable.io/reviews/harness/harness-core/54179#-NgryiCn-58IClTIkuJG:-NgryiCn-58IClTIkuJH:b-g4q56l) ([raw file](https://github.com/harness/harness-core/blob/42a5c859fdfdc724cb2e30a3aafddbca7686ddb9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/AbstractScmClientFacilitatorServiceImpl.java#L251)):*
> ```Java
>   }
> 
>   protected Optional<UserDetailsResponseDTO> getUserDetails(String accountIdentifier, ScmConnector connectorDTO) {
> ```

both these methods are moved out from GitSyncConnectorHelper to this abstract class

**Comment by yogesh-chauhan** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncConnectorServiceImpl.java` line 158 at r2](https://reviewable.io/reviews/harness/harness-core/54179#-NgsJSH-9OZfbQxVJjX8:-NgsJSH-9OZfbQxVJjX9:b-sw5w0g) ([raw file](https://github.com/harness/harness-core/blob/0a23664a3139156b1f2a8a8026cbec722a5a2f32/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncConnectorServiceImpl.java#L158)):*
> ```Java
>   }
> 
>   public void decryptGitAccessDTO(GitAccessDTO gitAccessDTO) {
> ```

these methods are either inlined at the callers or moved out to the individual callers because these were mostly called from single classes

**Comment by yogesh-chauhan** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncConnectorServiceImpl.java` line 346 at r2](https://reviewable.io/reviews/harness/harness-core/54179#-NgsL-T39nLcxyudTIZu:-NgsL-T39nLcxyudTIZv:b-sw5w0g) ([raw file](https://github.com/harness/harness-core/blob/0a23664a3139156b1f2a8a8026cbec722a5a2f32/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncConnectorServiceImpl.java#L346)):*
> ```Java
>   }
> 
>   public void testConnectionAsync(
> ```

these methods are either inlined at the callers or moved out to the individual callers because these were mostly called from single classes

**Review by abhinav-harness — APPROVED** [review]

**Comment by abhinav-harness** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
