### PR TITLE
[fix]: [DEL-1234]: move artifact classes out of 400-rest

### PR DESCRIPTION
**Pull request by raghuAtWings**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32305)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger ti3

**Comment by jennyjames21** [comment]
trigger ti2

**Review by srinivaswings — DISMISSED** [review]
> Reviewed 118 of 154 files at r1, 3 of 3 files at r3, 7 of 7 files at r4, 35 of 35 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32305)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 114 of 154 files at r1, 3 of 3 files at r3, 7 of 7 files at r4, 27 of 35 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32305)* status: :shipit: complete! ✓

**Pull request merged**
