### PR TITLE
[feat]: [CDS-36543]: Enable CLOUDFORMATION_NG FF

### PR DESCRIPTION
**Pull request by nassergonzalez**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32367)

### CODE REVIEW

**Review by vlica-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32367)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java, line 84 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N09v3n5-0_gvP5w4jPx:-N09v3n5-0_gvP5w4jPy:b7a8syx) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L84)):*
> ```Java
>       throw new AccessDeniedException(
>           "Cloudformation NG is not enabled for this user. Please contact harness customer care.",
>           ErrorCode.NG_ACCESS_DENIED, WingsException.USER);
> ```

hey Nasser, this ErrorCode is not too general in our case?

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32367)* status: 2 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N0A6lkb9S1cgsXJ6CGl:-N0A6lkc8h-kV_JlWQHt:b-viq8o5) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L83)):*
> ```Java
>     if (!cdFeatureFlagHelper.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.CLOUDFORMATION_NG)) {
>       throw new AccessDeniedException(
>           "Cloudformation NG is not enabled for this user. Please contact harness customer care.",
> ```

Let's mention that feature is not enabled for account: "Cloudformation NG is not enabled for this account. Please contact harness customer care."



_Code quote:_
```Java
ErrorCode.NG_ACCESS_DENIED
```
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java, line 86 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N0A71YK3rDvXRn6izNP:-N0A71YK3rDvXRn6izNQ:bi3dkt2) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java#L86)):*
> ```Java
>     if (!cdFeatureFlagHelper.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.CLOUDFORMATION_NG)) {
>       throw new AccessDeniedException(
>           "Cloudformation NG is not enabled for this user. Please contact harness customer care.",
> ```

the same here

**Review by nassergonzalez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32367)* status: 2 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java, line 83 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N0A6lkb9S1cgsXJ6CGl:-N0ACOqrEbSvAlrWjg5X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L83)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Let's mention that feature is not enabled for account: "Cloudformation NG is not enabled for this account. Please contact harness customer care."
</blockquote></details>

Done.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java, line 84 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N09v3n5-0_gvP5w4jPx:-N0ABodm9GIbNYSG6UQj:b-ud7ul8) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L84)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

hey Nasser, this ErrorCode is not too general in our case? 
</blockquote></details>

I don't think so. It's a forbidden access specific to NG, i don't think that we can make it more specific. The customer is not able to access to this functionality and if it wants to know why it should contact CS. Also it is going to be quite complicate that customer "just guess" that CF NG is enabled and they just start to try to find the proper yaml syntax to trigger it, so we can assume that no one would ever see this message unless they are trying to be hacky as hell.
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java, line 86 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N0A71YK3rDvXRn6izNP:-N0ACXDH5CYyT2cPBC4U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationDeleteStackStep.java#L86)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

the same here
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32367)* status: 1 change requests. 1. unresolved discussions.

**Comment by vlica-harness** [comment]
*[125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java, line 84 at r1](https://reviewable.io/reviews/harness/harness-core/32367#-N09v3n5-0_gvP5w4jPx:-N0AFaOq7Oek7YnbLqxY:b-l81z82) ([raw file](https://github.com/harness/harness-core/blob/18ca7a7f683cab2c19eed533d0b63c5ef80d93e9/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationCreateStackStep.java#L84)):*
<details><summary><i>Previously, nassergonzalez (Nasser Gonzalez Gonzalez) wrote…</i></summary><blockquote>

I don't think so. It's a forbidden access specific to NG, i don't think that we can make it more specific. The customer is not able to access to this functionality and if it wants to know why it should contact CS. Also it is going to be quite complicate that customer "just guess" that CF NG is enabled and they just start to try to find the proper yaml syntax to trigger it, so we can assume that no one would ever see this message unless they are trying to be hacky as hell.
</blockquote></details>

ahh okay, then makes sense.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32367)* status: :shipit: complete! ✓

**Pull request merged**
