### PR TITLE
fix: [PL-28613]: Delete encryptedData of secrets when project is deleted

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
Whenever a project/org gets deleted, from now on we will delete the records from NgEncryptedData as well. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38138)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38138)

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 611 at r2](https://reviewable.io/reviews/harness/harness-core/38138#-NDCgj6U0aTy9LbaEupH:-NDCgj6U0aTy9LbaEupI:bnsnby5) ([raw file](https://github.com/harness/harness-core/blob/f28a975a29b323ab09fbdff65a479ea137217528/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L611)):*
> ```Java
>   public boolean hardDelete(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String identifier) {
>     NGEncryptedData encryptedData = get(accountIdentifier, orgIdentifier, projectIdentifier, identifier);
> ```

why are we doing a get call to delete it?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 609 at r2](https://reviewable.io/reviews/harness/harness-core/38138#-NDCgpqTBv5LOzvKol7c:-NDCgpqTBv5LOzvKol7d:b-3abngl) ([raw file](https://github.com/harness/harness-core/blob/f28a975a29b323ab09fbdff65a479ea137217528/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L609)):*
> ```Java
> 
>   @Override
>   public boolean hardDelete(
> ```

why is this boolean? any specific purpose?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38138)* status: 9 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 609 at r2](https://reviewable.io/reviews/harness/harness-core/38138#-NDCgpqTBv5LOzvKol7c:-NDDQU1CBh4xiByC0Nuv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f28a975a29b323ab09fbdff65a479ea137217528/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L609)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this boolean? any specific purpose?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 611 at r2](https://reviewable.io/reviews/harness/harness-core/38138#-NDCgj6U0aTy9LbaEupH:-NDDQUWIBai_-wi5iVLQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f28a975a29b323ab09fbdff65a479ea137217528/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L611)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we doing a get call to delete it?
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38138)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 4 files at r2, 5 of 6 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38138)* status: 2 file(s) to review.

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38138#-:-NDS4jUFAxIEWHrOKuEf:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
