### PR TITLE
[fix]: [CDS-53490]: error handling for svc/env/envGroup ref as expression

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

Earlier validation for unresolved svc/env/envGroup were absent.
Added them now to improve error handling

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
trigger ft1

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/44102#-NQOWrmh6-RhKaVSin39:-NQOWrmh6-RhKaVSin3A:bs9sd2n) ([raw file](https://github.com/harness/harness-core/blob/7787b5e042bf2c569ca4a9452c835c4ce3ed1e86/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L251)):*
> ```Java
>       Pattern serviceVariablePattern = Pattern.compile(SERVICE_VARIABLES_PATTERN_REGEX);
>       String errorSuffix = StringUtils.EMPTY;
>       if (serviceVariablePattern.matcher(envGroupRef.getExpressionValue()).matches()) {
> ```

can we extract matching with serviceVariable pattern into a method?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/44102#-NOz2qesB1_fheCyXrv_:-NOz2qesB1_fheCyXrva:buig7dt) ([raw file](https://github.com/harness/harness-core/blob/bb6764ff12ee914a3e25f4c469ab190acbd98e8d/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L151)):*
> ```Java
>       + ".*)";
> 
>   private static final String ENV_VARIABLES_PATTERN_REGEX = "("
> ```

can we create a separate ServiceStepConstants class to hold these  and these can be single line right ? any reason for splitting this in this way

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/44102#-NQOWrmh6-RhKaVSin39:-NQOxCRL0r12aKCzlj6U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7787b5e042bf2c569ca4a9452c835c4ce3ed1e86/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L251)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

can we extract matching with serviceVariable pattern into a method? 
</blockquote></details>

Done.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/44102#-NQOWrmh6-RhKaVSin39:-NQPQr1a1Y8QlrMqZdL7:b-w8gyoc) ([raw file](https://github.com/harness/harness-core/blob/7787b5e042bf2c569ca4a9452c835c4ce3ed1e86/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L251)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's okay since we're doing it only twice. But we should ideally not recompile same pattern many times.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 251 at r2](https://reviewable.io/reviews/harness/harness-core/44102#-NQOWrmh6-RhKaVSin39:-NQPY8fp2PwTpfPEIC47:b8d4lmr) ([raw file](https://github.com/harness/harness-core/blob/7787b5e042bf2c569ca4a9452c835c4ce3ed1e86/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L251)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

It's okay since we're doing it only twice. But we should ideally not recompile same pattern many times.
</blockquote></details>

Good point @hingerabhinav . Made the pattern as static var

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 277 at r5](https://reviewable.io/reviews/harness/harness-core/44102#-NQPizfeCG77aQScNWyI:-NQPizfeCG77aQScNWyJ:b-inpwza) ([raw file](https://github.com/harness/harness-core/blob/c00e9219f29b06b228473da1bd1407e38602bddf/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L277)):*
> ```Java
> 
>   private void checkIfServiceRefIsExpAndThrow(ParameterField<String> serviceRef) {
>     if (EngineExpressionEvaluator.hasExpressions(serviceRef.getExpressionValue())) {
> ```

should we not check for serviceRef.isExpression() before the check ?

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 277 at r5](https://reviewable.io/reviews/harness/harness-core/44102#-NQPizfeCG77aQScNWyI:-NQQ4S4tCECgX6HE10B9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c00e9219f29b06b228473da1bd1407e38602bddf/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L277)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not check for serviceRef.isExpression() before the check ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44102)* status: :shipit: complete! ✓

**Pull request merged**
