### PR TITLE
feat: [CDS-35990]: Activate gitops permissions

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32148)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32148#-:-N-W48sGCejuxtvekx-S:bnfp4nl)* status: :shipit: complete! ✓

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32148#-:-N-j24bg6ISX8hc_SrTX:bnfp4nl)* status: :shipit: complete! ✓

**Review by gupta-utkarsh — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32148#-:-N00OI0f7x8vVm_q4_5y:bnfp4nl)* status: Some of the checks are too old.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32148#-:-N00TcGNAfGOXLSIVcXr:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
