### PR TITLE
fix:[PL-26330]: fix error message in case of protected branch

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Tested - 
1. ADO create 
2. ADO update
3. github create
4. github updtae
5. bitbucket create
6. bitbucket update
7. bitbucket server ceate
8. bitbucket server update

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35532)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateFileScmApiErrorHandler.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/35532#-N7QecFwBSb7s2KljK_7:-N7QecFwBSb7s2KljK_8:bpfi3xk) ([raw file](https://github.com/harness/harness-core/blob/da03a5c192fd69d1b700369157a7f95b28675ed9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateFileScmApiErrorHandler.java#L38)):*
> ```Java
>   public static final String CREATE_FILE_BAD_REQUEST_EXPLANATION =
>       "The requested branch<BRANCH> does not have push permission.";
>   public static final String CREATE_FILE_BAD_REQUEST_HINT =
> ```

its for HTTP 403 which is forbidden request, can we change the variable naming accordingly

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateFileScmApiErrorHandler.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/35532#-N7QerE5-4fgEP0BXw7j:-N7QerE61cYWYfy6m6Ma:bfqyira) ([raw file](https://github.com/harness/harness-core/blob/da03a5c192fd69d1b700369157a7f95b28675ed9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateFileScmApiErrorHandler.java#L39)):*
> ```Java
>       "The requested branch<BRANCH> does not have push permission.";
>   public static final String CREATE_FILE_BAD_REQUEST_HINT =
>       "Please use a pull request to create file<FILEPATH> in this branch<BRANCH>.";
> ```

Lets also mention to check if requested branch is allowed for write operations.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateFileScmApiErrorHandler.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/35532#-N7QerE5-4fgEP0BXw7j:-N7UdKWiALa6C6dtdLBj:b-g3qsvo) ([raw file](https://github.com/harness/harness-core/blob/da03a5c192fd69d1b700369157a7f95b28675ed9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateFileScmApiErrorHandler.java#L39)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

the reason is they do not have push permission and suggestion is to change via pr, why do we want to unecessary specify to check write permission, they know the reason, they will check if they want to remove it.
</blockquote></details>

We aren't the ones suggesting them way arounds. We are only trying to mention whats the issue in doing this particular operation. Ideally, as per API, we shouldn't even mention any work around, but from UX perspective, its good if we suggest a workaround. Thus asked you to add it to check if request branch is allowed for write operations, or do the workaround.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35532#-:-N7_Gg3w98e2uvLyrsn9:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — APPROVED** [review]

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35532)* status: 8 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35532)* status: :shipit: complete! ✓

**Pull request merged**
