### PR TITLE
feat: [DEL-3160]: Admin endpoint to set image tags

### PR DESCRIPTION
**Pull request by mdmilic**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30286)

### CODE REVIEW

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30286)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/resources/AdminRingResource.java, line 51 at r1](https://reviewable.io/reviews/harness/harness-core/30286#-MuljV-E3oSGWDx6BZnV:-MuljV-E3oSGWDx6BZnW:bacjisk) ([raw file](https://github.com/harness/harness-core/blob/72e2f73c7b1b6250b9b047eeebfc99ddb6855df7/400-rest/src/main/java/software/wings/resources/AdminRingResource.java#L51)):*
> ```Java
> 
>   @ApiKeyAuthorized(permissionType = ACCOUNT_MANAGEMENT, action = UPDATE)
>   @PUT
> ```

we dont need any auth annotation except AdminPortalAuth IMO

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30286)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger messagecheck

**Comment by mdmilic** [comment]
trigger messagecheck

**Pull request merged**
