### PR TITLE
fix: [CDS-44881]: sort after validation too in git sync

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
Currently during git sync we were sorting files and then processing them one at a time. 
But the order of things was - 
- Order/sort files
- Validate files if they have right file path
- process

Ideally we should have sorted right before processing. So making the change - to sort right before processing (still not removing the old sorting as we might have some side effects and sorting 100 files is nto a very heavy ops.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39166)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39166)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/39166#-NFsDoOE7bRArQZiLewz:-NFsDoOE7bRArQZiLex-:b-gzo0qc) ([raw file](https://github.com/harness/harness-core/blob/1dad21aefa2bb61326e3944370c0ffe94421d494/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L523)):*
> ```Java
>   }
> 
>   private void sortByProcessingOrder(ChangeContextErrorMap validationResponseMap) {
> ```

Please, add a unit test to avoid a future regression.
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1022 at r1](https://reviewable.io/reviews/harness/harness-core/39166#-NFsDeGe477D1KUtEnJZ:-NFsDeGe477D1KUtEnJ_:bzapffy) ([raw file](https://github.com/harness/harness-core/blob/1dad21aefa2bb61326e3944370c0ffe94421d494/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1022)):*
> ```Java
>   }
> 
>   private final class ChangeContextComparator implements Comparator<ChangeContext> {
> ```

Could this class move to package scope? Doing that the unit test can be isolated on it.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39166)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 523 at r1](https://reviewable.io/reviews/harness/harness-core/39166#-NFsDoOE7bRArQZiLewz:-NFu0l-e-7e9hsewVqwT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dec6481623df08012589f0b9ccf958e359326c23/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L523)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Please, add a unit test to avoid a future regression.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1022 at r1](https://reviewable.io/reviews/harness/harness-core/39166#-NFsDeGe477D1KUtEnJZ:-NFu0lkd71JM84yt8CS7:bmtjbpk) ([raw file](https://github.com/harness/harness-core/blob/dec6481623df08012589f0b9ccf958e359326c23/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1022)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Could this class move to package scope? Doing that the unit test can be isolated on it.
</blockquote></details>

Yeah, but we have similar comparator only in this class, dont want to move both. Can we proceed without this?

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39166)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger ft2

**Pull request merged**
