### PR TITLE
[feat]:[pl-26311]: Integrate UPDATE Template Flow with GitX

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Integrate UPDATE Template Flow with GitX
These flows have been tested out
1. updateExistingTemplateLabel api for both new GitX and old GitSync flows
2. updateStableTemplate api for both new GitX and old GitSync flows

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 722 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7z7C-P7oxmDHuxgg_s:-N7z7C-P7oxmDHuxgg_t:b-fp1cro) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L722)):*
> ```Java
>         }
>       }
>     }
> ```

we should add "else" block and put a log here that existing entity not found, thus ignoring update call

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 722 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7z7C-P7oxmDHuxgg_s:-N7zDgkKDahA0wmxJnxb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L722)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should add "else" block and put a log here that existing entity not found, thus ignoring update call
</blockquote></details>

Done.



_Code quote:_
```Java
makePreviousStableTemplateFalse
```

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 754 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7zIoGcE9gWb_KyZFwN:-N7zIoGcE9gWb_KyZFwO:bhr1dqb) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L754)):*
> ```Java
>         }
>       }
>     }
> ```

same else block thing here as well

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 615 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7zU73k7z7f2r0-1ufl:-N7zU73lE0-mMAtwpFgn:ba3vbf1) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L615)):*
> ```Java
>       makePreviousLastUpdatedTemplateFalse(
>           accountIdentifier, orgIdentifier, projectIdentifier, templateIdentifier, newStableTemplateVersion);
>       Optional<TemplateEntity> optionalTemplateEntity = getOrThrowExceptionIfInvalid(
> ```

@inderschera Shouldn't this check be the first one before prev 2 method calls to update lastUpdated and stable version?

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 422 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zkpn91TKBm3Dco_v2:-N7zkpn91TKBm3Dco_v3:buo7ukj) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L422)):*
> ```Java
>   }
> 
>   private boolean isAuditEnabled(TemplateEntity templateToUpdate, boolean skipAudits) {
> ```

nit: change name to templateEntity



_Suggestion:_
```Java
templateToUpdate
```
___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 428 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zkgXe4VcZq33dvjk1:-N7zkgXfA8lcWVaQ5lyT:b4y60ih) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L428)):*
> ```Java
>   }
> 
>   private OutboxEvent generateOutbox(TemplateEntity templateToUpdate, TemplateEntity oldTemplateEntity, String comments,
> ```

nit: change name to generateUpdateOutboxEvent
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7z3W6S1OlB36WPcPAz:-N7z3W6S1OlB36WPcPB-:bad0zhw) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L501)):*
> ```Java
>             .withYaml(invalidYaml)
>             .withIsEntityInvalid(true);
>     templateRepository.updateTemplateYamlForOldGitSync(
> ```

nit: add a comment here for future reference that it happens only for old git exp.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 615 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7zU73k7z7f2r0-1ufl:-N7zc2MPEFynwyBud48w:bi5to9v) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L615)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@inderschera Shouldn't this check be the first one before prev 2 method calls to update lastUpdated and stable version?
</blockquote></details>

yes @mohitg0795. @adivishy1 please do the change.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 184 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7ziiid3k7Mfs9BFuC7:-N7ziiid3k7Mfs9BFuC8:bfv2qj4) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L184)):*
> ```Java
>       makePreviousLastUpdatedTemplateFalse(templateEntity.getAccountIdentifier(), templateEntity.getOrgIdentifier(),
>           templateEntity.getProjectIdentifier(), templateEntity.getIdentifier(), templateEntity.getVersionLabel());
>       return updateTemplateHelper(templateEntity.getOrgIdentifier(), templateEntity.getProjectIdentifier(),
> ```

Let's have this call before makePreviousLastUpdatedTemplateFalse
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 225 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zis0f-1AcKMq-fVhf:-N7zis0f-1AcKMq-fVhg:b-embdaq) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L225)):*
> ```Java
>       }
>       if (!((oldTemplateEntity.getChildType() == null && templateEntity.getChildType() == null)
>               || oldTemplateEntity.getChildType().equals(templateEntity.getChildType()))) {
> ```

Let's move this part of code to a separate method.



_Code quote:_
```Java
      Optional<TemplateEntity> optionalTemplate =
          templateServiceHelper.getTemplateWithVersionLabel(templateEntity.getAccountId(), oldOrgIdentifier,
              oldProjectIdentifier, templateEntity.getIdentifier(), templateEntity.getVersionLabel(), false);

      if (!optionalTemplate.isPresent()) {
        throw new InvalidRequestException(format(
            "Template with identifier [%s] and versionLabel [%s] under Project[%s], Organization [%s] doesn't exist.",
            templateEntity.getIdentifier(), templateEntity.getVersionLabel(), templateEntity.getProjectIdentifier(),
            templateEntity.getOrgIdentifier()));
      }
      TemplateEntity oldTemplateEntity = optionalTemplate.get();
      if (!oldTemplateEntity.getTemplateEntityType().equals(templateEntity.getTemplateEntityType())) {
        throw new InvalidRequestException(format(
            "Template with identifier [%s] and versionLabel [%s] under Project[%s], Organization [%s] cannot update the template type, type is [%s].",
            templateEntity.getIdentifier(), templateEntity.getVersionLabel(), templateEntity.getProjectIdentifier(),
            templateEntity.getOrgIdentifier(), oldTemplateEntity.getTemplateEntityType()));
      }
      if (!((oldTemplateEntity.getChildType() == null && templateEntity.getChildType() == null)
              || oldTemplateEntity.getChildType().equals(templateEntity.getChildType()))) {
        throw new InvalidRequestException(format(
            "Template with identifier [%s] and versionLabel [%s] under Project[%s], Organization [%s] cannot update the internal template type, type is [%s].",
            templateEntity.getIdentifier(), templateEntity.getVersionLabel(), templateEntity.getProjectIdentifier(),
            templateEntity.getOrgIdentifier(), oldTemplateEntity.getChildType()));
      }
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 251 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zi3JG5G9Do-_nD2bd:-N7zi3JG5G9Do-_nD2be:bpih7r6) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L251)):*
> ```Java
>               templateEntity.getProjectIdentifier(), templateEntity.getIdentifier(),
>               templateToUpdate.getVersionLabel());
>           return templateServiceHelper.makeTemplateUpdateCall(templateToUpdateWithStable, oldTemplateEntity, changeType,
> ```

Let's have this call before makePreviousStableTemplateFalse
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 730 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zgVgQ-vh788fox4P6:-N7zgVgQ-vh788fox4P7:b-opdr9e) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L730)):*
> ```Java
>       String projectIdentifier, String templateIdentifier, String currentTemplateVersion) {
>     NGTemplateServiceHelper.validatePresenceOfRequiredFields(accountIdentifier, templateIdentifier);
>     Optional<TemplateEntity> optionalTemplateEntity = templateServiceHelper.getLastUpdatedTemplate(
> ```

We don't need to actually get this template from db. We can directly do findAndModify on this for new git experience. This would reduce an extra db call and fetching yaml from git.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 3 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 615 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7zU73k7z7f2r0-1ufl:-N7zsAoi4Pv79-DudEG9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L615)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

yes @mohitg0795. @adivishy1 please do the change.
</blockquote></details>

Done.



_Code quote:_
```Java
updateStableTemplateVersionHelper
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 754 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N7zIoGcE9gWb_KyZFwN:-N7zuuBZ6VtR8N_3xCsV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L754)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same else block thing here as well
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 184 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7ziiid3k7Mfs9BFuC7:-N7zqt_B5JOAsjMiBvko:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L184)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Let's have this call before makePreviousLastUpdatedTemplateFalse
</blockquote></details>

Done.



_Code quote:_
```Java
updateTemplateEntity
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 225 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zis0f-1AcKMq-fVhf:-N7zrfc-05FodulzLGrO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L225)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Let's move this part of code to a separate method.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 251 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zi3JG5G9Do-_nD2bd:-N7zrtAz4rbr9npm6KUF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L251)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Let's have this call before makePreviousStableTemplateFalse
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 730 at r3](https://reviewable.io/reviews/harness/harness-core/35745#-N7zgVgQ-vh788fox4P6:-N7zuQJk7IyPAUveQLk_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/903a179b87571406f7f0d11e7297387f8b722b1e/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L730)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

We don't need to actually get this template from db. We can directly do findAndModify on this for new git experience. This would reduce an extra db call and fetching yaml from git.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N803XP10cN3yNqq4pnB:-N803XP10cN3yNqq4pnC:b-mwhkzt) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L292)):*
> ```Java
>       Scope scope = TemplateUtils.buildScope(templateToUpdate);
>       gitAwareEntityHelper.updateEntityOnGit(templateToUpdate, templateToUpdate.getYaml(), scope);
>     }
> ```

I'm just wondering if entity is of REMOTE type and git simplification is disabled, shouldn't we throw an error in this case? Coz this case is invalid and shouldn't come at all

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N806P7GAAg1q8oyutEE:-N806P7GAAg1q8oyutEF:b-zglw8v) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L199)):*
> ```Java
>           templateEntity.getProjectIdentifier(), comments);
>       GitEntityInfo gitEntityInfo = GitContextHelper.getGitEntityInfo();
>       if (templateServiceHelper.isOldGitSync(templateEntity) && gitEntityInfo != null && gitEntityInfo.isNewBranch()) {
> ```

can we try and understand and make this complete if condition simpler and modularized? Currently its hard to understand

**Comment by mohitg0795** [comment]
*[`840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java` line 366 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N8073EN4SrCo6mK2HEs:-N8073EN4SrCo6mK2HEt:bln70oq) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java#L366)):*
> ```Java
> 
>     // Check update stable template
> ```

please remove this redundant change

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 3 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 292 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N803XP10cN3yNqq4pnB:-N824xGX4swa_ETHlNjn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L292)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm just wondering if entity is of REMOTE type and git simplification is disabled, shouldn't we throw an error in this case? Coz this case is invalid and shouldn't come at all
</blockquote></details>

Done.



_Code quote (from 840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java):_
```Java
estCreateAndUpdateWithStableTemplate
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 375 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N8042bBDZkpMm9bdEeJ:-N82F0lb4b7awx-wXQLP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L375)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see we log error differently here for the given 2 catch blocks. Can we keep it consistent?

The only difference should be that when we catch "Exception", then we should say "unexpected exception occured..." otherwise the rest of the error message should be consistent. It will help us trace issues easily.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 199 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N806P7GAAg1q8oyutEE:-N82HtmR2ZXkxIMAoCsY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L199)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we try and understand and make this complete if condition simpler and modularized? Currently its hard to understand
</blockquote></details>

Done.
___
*[`840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java` line 366 at r2](https://reviewable.io/reviews/harness/harness-core/35745#-N8073EN4SrCo6mK2HEs:-N82Fqe0-wQ-ZWV31r36:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d28a0a663b4a24dcd068ecbfe72f4da7c7cf7590/840-template-service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java#L366)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please remove this redundant change
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 7. unresolved discussions.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 7. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 481 at r6](https://reviewable.io/reviews/harness/harness-core/35745#-N82Tfm4EC7cWlyjciqz:-N82Tfm4EC7cWlyjcir-:b-7qs9v3) ([raw file](https://github.com/harness/harness-core/blob/2a350badfd787c0a5c57c6fc55e23288fa14f9cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L481)):*
> ```Java
>             .withYaml(invalidYaml)
>             .withIsEntityInvalid(true);
>     log.info("The update template yaml happens as this is oldGitSync flow");
> ```

add template identifier in it
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 704 at r6](https://reviewable.io/reviews/harness/harness-core/35745#-N82Tloj9pzyhUww4LsT:-N82Tloj9pzyhUww4LsU:bfy10ct) ([raw file](https://github.com/harness/harness-core/blob/2a350badfd787c0a5c57c6fc55e23288fa14f9cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L704)):*
> ```Java
>       }
>     } else {
>       log.info("Requested template entity not found, hence the update call is ignored");
> ```

Add template id in the log to atleast get the logs with template identifier.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 738 at r6](https://reviewable.io/reviews/harness/harness-core/35745#-N82TuIX1tH7z9YNyBlM:-N82TuIX1tH7z9YNyBlN:b-k3aqh3) ([raw file](https://github.com/harness/harness-core/blob/2a350badfd787c0a5c57c6fc55e23288fa14f9cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L738)):*
> ```Java
>       }
>     } else {
>       log.info("Requested template entity not found, hence the update call is ignored");
> ```

again same thing

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 10. unresolved discussions. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 481 at r6](https://reviewable.io/reviews/harness/harness-core/35745#-N82Tfm4EC7cWlyjciqz:-N82j0Yg-8fMRmVTy-dn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a350badfd787c0a5c57c6fc55e23288fa14f9cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L481)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

add template identifier in it
</blockquote></details>

Done.



_Code quote:_
```Java
markEntityInvalid
```
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 704 at r6](https://reviewable.io/reviews/harness/harness-core/35745#-N82Tloj9pzyhUww4LsT:-N82iXPSCtLhCm6h0UsR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a350badfd787c0a5c57c6fc55e23288fa14f9cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L704)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Add template id in the log to atleast get the logs with template identifier.
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 738 at r6](https://reviewable.io/reviews/harness/harness-core/35745#-N82TuIX1tH7z9YNyBlM:-N82iWts7oZYlB1ch-Wb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a350badfd787c0a5c57c6fc55e23288fa14f9cd/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L738)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

again same thing
</blockquote></details>

Done.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 3 of 8 files at r2, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 7. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745)* status: 7. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r2, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35745#-:-N83aTKP607u-_UzGyoS:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
