### PR TITLE
[feat]: [CDS-56497]: pojos to support overrides V2

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

Data models explained here
https://harness.atlassian.net/wiki/spaces/CDNG/pages/21353038137/Infrastructure+Overrides#Data-Models

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 1077 at r2](https://reviewable.io/reviews/harness/harness-core/46378#-NTNUFXL9KzhzcVcxYK0:-NTNUFXL9KzhzcVcxYK1:brix2ra) ([raw file](https://github.com/harness/harness-core/blob/7ec965b71802a676583b5e275527898cda88464a/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L1077)):*
> ```Java
>     }
>     if (isEmpty(dto.getServiceIdentifier())) {
>       throw new InvalidRequestException("No service identifier for Service Overrides sent in API");
> ```

can we get rid of "sent in API" wording in the message ?



_Code quote:_
```Java
sent in API
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesConfig.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/46378#-NTNWdiC3wQGiZM5rvcB:-NTNWdiC3wQGiZM5rvcC:byj2olt) ([raw file](https://github.com/harness/harness-core/blob/7ec965b71802a676583b5e275527898cda88464a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesConfig.java#L33)):*
> ```Java
>   String identifier;
>   ServiceOverridesType type;
>   ServiceOverridesSpec spec;
> ```

all 3 fields are not null right ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesResponseDTOV2.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/46378#-NTNWpw6A08tmy_LOHkh:-NTNWpw6A08tmy_LOHki:b-2e5li1) ([raw file](https://github.com/harness/harness-core/blob/7ec965b71802a676583b5e275527898cda88464a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverridesResponseDTOV2.java#L37)):*
> ```Java
>   String infraIdentifier;
>   ServiceOverridesType type;
>   ServiceOverridesSpec overrideSpec;
> ```

can we call this just spec ? ( because we follow type-spec pattern at other places also )

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 9 file(s) to review. 0 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/EnvServiceOverridesConfig.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/46378#-NTNZNfk0XEWuAkB1El-:-NTNZNfl7vlgz6_PJG__:bppz2qb) ([raw file](https://github.com/harness/harness-core/blob/7ec965b71802a676583b5e275527898cda88464a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/EnvServiceOverridesConfig.java#L33)):*
> ```Java
> @TypeAlias("envServiceOverrideConfig")
> public class EnvServiceOverridesConfig extends ServiceOverridesConfig {
>   String environmentRef;
> ```

These can't be null right? Can we add that?

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/EnvServiceOverridesConfig.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/46378#-NTNZNfk0XEWuAkB1El-:-NTmQewoBDP9Kd8Bcfd0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ec965b71802a676583b5e275527898cda88464a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/EnvServiceOverridesConfig.java#L33)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

These can't be null right? Can we add that?
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideRequestDTOV2.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/46378#-NTNW_XxElBFLhFy2oQO:-NTmQfxF2TYYl4dJEd5J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ec965b71802a676583b5e275527898cda88464a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans/ServiceOverrideRequestDTOV2.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are these refs or identifiers ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 7 files at r2, 5 of 7 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46378)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger review

**Pull request merged**
