### PR TITLE
[feat]: [CCM-8560]: CCM RBAC role migration

### PR DESCRIPTION
**Pull request by svmav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36739)

**Comment by svmav** [comment]
trigger ti4

**Comment by svmav** [comment]
trigger ti2

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/migration/CCMAdminRoleAssignmentMigration.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/36739#-NAFlZGH277q6gAQTZJQ:-NAFlZGH277q6gAQTZJR:bq7p7yg) ([raw file](https://github.com/harness/harness-core/blob/a8f11714565c52a568bf439ce2cca0e50ffdf474/340-ce-nextgen/src/main/java/io/harness/ccm/migration/CCMAdminRoleAssignmentMigration.java#L93)):*
> ```Java
>   private RoleAssignmentDTO buildRoleAssignmentDTO(RoleAssignmentResponseDTO roleAssignmentResponseDTO) {
>     return RoleAssignmentDTO.builder()
>         .roleIdentifier("role_assignment_".concat(CryptoUtils.secureRandAlphaNumString(20)))
> ```

This should be identifier not roleIdentifier.

**Review by svmav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/migration/CCMAdminRoleAssignmentMigration.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/36739#-NAFlZGH277q6gAQTZJQ:-NAFp8kVCpGvBOGdhxoj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8f11714565c52a568bf439ce2cca0e50ffdf474/340-ce-nextgen/src/main/java/io/harness/ccm/migration/CCMAdminRoleAssignmentMigration.java#L93)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

This should be identifier not roleIdentifier. 
</blockquote></details>

Done.

**Comment by svmav** [comment]
trigger ti2

**Review by reetika04 — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: 1 change requests. 1. unresolved discussions.

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/config.yml` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/36739#-NAG309Z3t6aC3ddyYu2:-NAG309Z3t6aC3ddyYu3:bsste9d) ([raw file](https://github.com/harness/harness-core/blob/48ba171d917cecdf95ba8be4c4420a4cc79f7098/340-ce-nextgen/config.yml#L197)):*
> ```YAML
>     enableHttpLogging: ${ENABLE_HTTP_LOGGING:-false}
>   accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
>   mockAccessControlService: false
> ```

This should be true by default.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1107 at r4](https://reviewable.io/reviews/harness/harness-core/36739#-NAG35fU4rx94R3TOrfY:-NAG35fU4rx94R3TOrfZ:b37arwr) ([raw file](https://github.com/harness/harness-core/blob/48ba171d917cecdf95ba8be4c4420a4cc79f7098/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1107)):*
> ```YAML
>       - account
>       - organization
>       - project
> ```

Please update the version.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: :shipit: complete! ✓

**Review by svmav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/config.yml` line 197 at r4](https://reviewable.io/reviews/harness/harness-core/36739#-NAG309Z3t6aC3ddyYu2:-NAHm-Gv0EpQZxEd4uJM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48ba171d917cecdf95ba8be4c4420a4cc79f7098/340-ce-nextgen/config.yml#L197)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

This should be true by default.
</blockquote></details>

Done.
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1107 at r4](https://reviewable.io/reviews/harness/harness-core/36739#-NAG35fU4rx94R3TOrfY:-NAHlzF_BCGg8jbF__5s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/48ba171d917cecdf95ba8be4c4420a4cc79f7098/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1107)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Please update the version.
</blockquote></details>

Done.

**Review by reetika04 — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36739)* status: :shipit: complete! ✓

**Pull request merged**
