### PR TITLE
[feat]: [PIE-8697]: Add null check for newly added query params in openapi yaml

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Add null check for newly added query params in openapi yaml and updated the param with a default value.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/44588#-NPW-yuRE8ULtpInmGF8:-NPW-yuRE8ULtpInmGF9:b5bznrb) ([raw file](https://github.com/harness/harness-core/blob/867b9e3b86209514aba724b313714d243f147041/pipeline-service/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=23
> build.patchVersion=4
> ```

why is it 4?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44588#-NPW05PaCYTW54r4EczN:-NPW05PaCYTW54r4EczO:b-ooguki) ([raw file](https://github.com/harness/harness-core/blob/867b9e3b86209514aba724b313714d243f147041/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L102)):*
> ```Java
>         inputSet, pipeline, project, org, account));
>     Optional<InputSetEntity> optionalInputSetEntity = Optional.empty();
>     if (null == loadFromFallbackBranch) {
> ```

please put this in the first line of the method itself.

**Review by archit-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44588#-NPW05PaCYTW54r4EczN:-NPW0DXsAJyBiSnpJx7k:b-jsmdi8) ([raw file](https://github.com/harness/harness-core/blob/867b9e3b86209514aba724b313714d243f147041/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L102)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please put this in the first line of the method itself.
</blockquote></details>

Cant we add default value coming from open API spec itself?

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/44588#-NPW-yuRE8ULtpInmGF8:-NPW0NnD11MEroZsz7l_:b-fs2k1x) ([raw file](https://github.com/harness/harness-core/blob/867b9e3b86209514aba724b313714d243f147041/pipeline-service/build.properties#L3)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it 4?
</blockquote></details>

Ankit is raising another HF pr with version 3
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44588#-NPW05PaCYTW54r4EczN:-NPW0VBT7f_JV1ciLJ4p:b-14ej6f) ([raw file](https://github.com/harness/harness-core/blob/867b9e3b86209514aba724b313714d243f147041/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L102)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Cant we add default value coming from open API spec itself?
</blockquote></details>

have added the default value in the spec as well, not sure why its not showing up in reviewable, https://github.com/harness/harness-core/pull/44588/files#diff-f68764817e058049d5e0b5a1074798bc56a34da5ea640bfd90c397adc10b5fcd

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/44588#-NPW05PaCYTW54r4EczN:-NPW0riC9KFIzU-IXh_S:b-3wajfm) ([raw file](https://github.com/harness/harness-core/blob/867b9e3b86209514aba724b313714d243f147041/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L102)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

have added the default value in the spec as well, not sure why its not showing up in reviewable, https://github.com/harness/harness-core/pull/44588/files#diff-f68764817e058049d5e0b5a1074798bc56a34da5ea640bfd90c397adc10b5fcd
</blockquote></details>

@mohit, have moved it to the first line

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 1 file(s) to review.

**Comment by adivishy1** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 2 file(s) to review.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: :shipit: complete! ✓

**Comment by hextechpal** [comment]
approved

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44588)* status: 1 file(s) to review.

**Pull request merged**
