### PR TITLE
feat: [CDS-47451]: default template changes, delegate selector fix, some logging

### PR DESCRIPTION
**Pull request by vaibhav-si**
…ome logging

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40807)

### CODE REVIEW

**Comment by vaibhav-si** [comment]
trigger smartchecks

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40807)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-gitops-with-linked-apps.yaml` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/40807#-NI3ZUk59rdF9GhFP1KV:-NI5mQ8jEhbXM2MT8ji7:b-9ysosg) ([raw file](https://github.com/harness/harness-core/blob/bea33b7459f622c88ff7a34d76fff8f4ec2a8c82/125-cd-nextgen/src/main/resources/executionStrategyYaml/kubernetes-gitops-with-linked-apps.yaml#L21)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Make default to true
</blockquote></details>

will do in follow up, should I also do it for existing template? (without my FF)
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java` line 1969 at r2](https://reviewable.io/reviews/harness/harness-core/40807#-NI3ZCD5B1aCi6KK3MVF:-NI5mEO494VQO2lcgVwv:bi6xqfm) ([raw file](https://github.com/harness/harness-core/blob/bea33b7459f622c88ff7a34d76fff8f4ec2a8c82/950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java#L1969)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Will changing the class names and reusing the same numbers cause any issue if these changes has been already released to delegate?
</blockquote></details>

It's released but no one would use yet.
We would need new delegate release anyways. Don't think it should impact.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40807)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40807)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]

**Pull request merged**
