### PR TITLE
[fix]: [CDS-39288]: fix secrets expression reverting, fix logging

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes

The logic io.harness.pms.expression.EngineExpressionSecretUtils#revertSecrets was detecting AWS expression as: ${AWS::StackName}.
Fixed a logging issue.

Is it new task type?  -  **no**

Did you add a new class which is added in kryo serialization  -   **no** 

Did you make changes to the code in a backward-compatible manner?   -   **yes**

will the new version of the delegate receive old version task and process?   -    **yes**

If new version of the manager receives response for the old task will it be able to handle it successfully?  -  **yes**

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager.    -     **yes**

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay.   -   **yes**

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay.   -   **yes**

Did you remove an enum →    **no**

Did you add an enum →.    **no**

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34900)

### CODE REVIEW

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34900#-:-N5spflACZJS1YyLyn25:bnfp4nl)* status: :shipit: complete! ✓

**Review by nassergonzalez — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34900)* status: 1 change requests. 2. unresolved discussions.

**Review by vlica-harness — DISMISSED** [review]

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34900)* status: 1 change requests. 2. unresolved discussions.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34900)* status: 1 change requests. 2. unresolved discussions.

**Review by vlica-harness — APPROVED** [review]

**Pull request merged**
