### PR TITLE
feat: [CDS-39316] Support Basic deployment for Azure WebApps

### PR DESCRIPTION
**Pull request by jelenaHarness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

Is it new task type?  -  NO

Did you add a new class which is added in kryo serialization. -  NO

Did you make changes to the code in a backward-compatible manner?   -   YES

will the new version of the delegate receive old version task and process?  -   YES

If new version of the manager receives response for the old task will it be able to handle it successfully?     -    YES

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager.  -   NO

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay.  -  YES

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay.   - YES

Did you remove an enum →    NO

Did you add an enum → NO

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)

### CODE REVIEW

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 15 of 21 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: :shipit: complete! ✓

**Comment by jelenaHarness** [comment]
trigger publish-delegate

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java` line 144 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6foV8770nIpZHNxVCa:-N6foV8770nIpZHNxVCb:bm2m6r3) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java#L144)):*
> ```Java
>       Optional<WebApp> azureApp = azureWebClient.getWebAppByName(azureWebClientContext);
>       if (!azureApp.isPresent()) {
>         throw new InvalidRequestException(format("WebApp - [%s] not ", azureWebClientContext.getAppName()));
> ```

not found?
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 298 at r1](https://reviewable.io/reviews/harness/harness-core/35142#-N6foxIeErJIbpxNXxv-:-N6foxIeErJIbpxNXxv0:b-ohhuyp) ([raw file](https://github.com/harness/harness-core/blob/99789b2c05807273049a529ddbfe2b90b1ca0c12/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L298)):*
> ```Java
>   private void updateWebAppAppSettings(
>       AzureWebClientContext context, Map<String, AzureAppServiceApplicationSetting> appSettings) {
>     if (appSettings.isEmpty()) {
> ```

Why do we remove this?

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 21 files at r1, 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/verifier/SlotStatusVerifier.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gYTWF-kMTouCMfOwl:-N6gYTWF-kMTouCMfOwm:b-kkglju) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/appservice/deployment/verifier/SlotStatusVerifier.java#L92)):*
> ```Java
>     Optional<WebApp> webAppOptional = azureWebClient.getWebAppByName(azureWebClientContext);
>     return webAppOptional.orElseThrow(
>         () -> new InvalidRequestException(format("Unable to find deployment slot with name: %s", slotName)));
> ```

Maybe it's better to say "Unable to find web app..."
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gYByO8WX5PhtvH3If:-N6gYByO8WX5PhtvH3Ig:b-xvqtzi) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java#L92)):*
> ```Java
> 
>     try {
>       if (!skipTargetSlotValidation && !isBasicDeployment) {
> ```

Minor - why do we skip slot validation for basic deployment.
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gcAsU3jwo7PV9K7h0:-N6gcAsU3jwo7PV9K7h1:by57ux1) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L69)):*
> ```Java
> @Singleton
> @Slf4j
> public class AzureWebClientImpl extends AzureClient implements AzureWebClient {
> ```

Overall comment for this class, you can expose all new private methods for web app by making them public and adding them to the AzureWebClient interface. 
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 185 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6g_MSUAfYD9xPC6r0o:-N6g_MSUAfYD9xPC6r0p:bvt839w) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L185)):*
> ```Java
>   }
> 
>   private void startProductionAsync(AzureWebClientContext context, ServiceCallback<Void> callback) {
> ```

Minor - rename this startProductionAsync >> startWebAppAsync.  Also, you can make this method public  and expose it for public use,
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 236 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6g_joE9nMklqe1pliF:-N6g_joE9nMklqe1pliG:bnexw54) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L236)):*
> ```Java
>   }
> 
>   private void stopProductionAsync(AzureWebClientContext context, ServiceCallback<Void> callback) {
> ```

Minor - rename this stopProductionAsync >> stopWebAppAsync. Also, you can make this method public  and expose it for public use,
___
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 854 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gblR5BR8tih7RbdIx:-N6gblR5BR8tih7RbdIy:b-dpr1ia) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L854)):*
> ```Java
> 
>     log.debug(
>         "Start listing instance identifiers for slot, resourceGroupName: {}, context: {}", resourceGroupName, context);
> ```

Minor - "Start listing instance identifiers for web app ..."

**Comment by jelenaHarness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gYByO8WX5PhtvH3If:-N6hMLov3cvMBb05I4WX:bthfzyw) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java#L92)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - why do we skip slot validation for basic deployment.
</blockquote></details>

In the case of basic deployment, we only deploy to deployment slot, so trying to validate target slot will result in an error

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: 1 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gYByO8WX5PhtvH3If:-N6hVM9Y5KgWSJxgT7EU:b-yma0b) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java#L92)):*
<details><summary><i>Previously, jelenaHarness (Jelena Arsenijevic) wrote…</i></summary><blockquote>

In the case of basic deployment, we only deploy to deployment slot, so trying to validate target slot will result in an error
</blockquote></details>

Ok, yes I remember we need this validation only for swapping and here we don't have that step.

**Comment by jelenaHarness** [comment]
*[`960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java` line 69 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6gcAsU3jwo7PV9K7h0:-N6hWXOE2COvtQKqQQWf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/960-api-services/src/main/java/io/harness/azure/impl/AzureWebClientImpl.java#L69)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Overall comment for this class, you can expose all new private methods for web app by making them public and adding them to the AzureWebClient interface. 
</blockquote></details>

Done.

**Comment by jelenaHarness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java` line 144 at r3](https://reviewable.io/reviews/harness/harness-core/35142#-N6foV8770nIpZHNxVCa:-N6hMhg62d_z1Ck-uFeh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79204b9f7de35ddfbcbde8d9fa8a0aba2d52bf0e/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/common/AzureAppServiceService.java#L144)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

not found?
</blockquote></details>

Done.

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: 1 change requests. 2. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142#-:-N6hwCuc25VGRgQK8a50:bnfp4nl)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 11 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 13 of 14 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 14 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 9 of 21 files at r1, 3 of 6 files at r3, 4 of 4 files at r4, 2 of 14 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35142)* status: :shipit: complete! ✓

**Pull request merged**
