### PR TITLE
feat: [PL-30455]: Added retry logic in NGRestClientExecutor and RestCallToNGManagerClientUtils

### PR DESCRIPTION
**Pull request by meenakshi-harness**
1. Added retry logic in NGRestClientExecutor
2. Deleted RestCallToNGManagerClientUtils and replaced its usages with NGRestUtils

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-core-clients/src/main/java/io/harness/utils/RestCallToNGManagerClientUtils.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/42011#-NKRzG3i4VixcyIX3Hve:-NKRzG3i4VixcyIX3Hvf:birldkr) ([raw file](https://github.com/harness/harness-core/blob/16bbffcda820e44208e15c79b597760601c20984/930-ng-core-clients/src/main/java/io/harness/utils/RestCallToNGManagerClientUtils.java#L28)):*
> ```Java
> @Slf4j
> @OwnedBy(PL)
> public class RestCallToNGManagerClientUtils {
> ```

We can delete this class and use NGRestUtils.getResponse instead
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestClientExecutor.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/42011#-NKS-SDZ6A09BgledqHb:-NKS-SDZ6A09BgledqHc:b-hdg9hf) ([raw file](https://github.com/harness/harness-core/blob/16bbffcda820e44208e15c79b597760601c20984/970-ng-commons/src/main/java/io/harness/remote/client/NGRestClientExecutor.java#L36)):*
> ```Java
> @Singleton
> @Slf4j
> public class NGRestClientExecutor {
> ```

Can we adopt exactly the same pattern (methods etc) as CGRestUtils and NGRestUtils. Only change would be in the handleResponse method

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/utils/RestClientUtils.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/42011#-NKS0Q5N7XnqXDNUE17x:-NKS0Q5OBc5Aow0vHbAT:bn0fxf6) ([raw file](https://github.com/harness/harness-core/blob/16bbffcda820e44208e15c79b597760601c20984/970-ng-commons/src/main/java/io/harness/utils/RestClientUtils.java#L26)):*
> ```Java
> @UtilityClass
> @Slf4j
> public class RestClientUtils {
> ```

We can probably keep this under /harness-core/970-ng-commons/src/main/java/io/harness/remote/client itself.

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: Some of the checks are too old. 17 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`930-ng-core-clients/src/main/java/io/harness/utils/RestCallToNGManagerClientUtils.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/42011#-NKRzG3i4VixcyIX3Hve:-NKwt5JS-wlrnnFhdY1I:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16bbffcda820e44208e15c79b597760601c20984/930-ng-core-clients/src/main/java/io/harness/utils/RestCallToNGManagerClientUtils.java#L28)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can delete this class and use NGRestUtils.getResponse instead
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/remote/client/NGRestClientExecutor.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/42011#-NKS-SDZ6A09BgledqHb:-NKwt6ctBEiiEscBU5Ye:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16bbffcda820e44208e15c79b597760601c20984/970-ng-commons/src/main/java/io/harness/remote/client/NGRestClientExecutor.java#L36)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we adopt exactly the same pattern (methods etc) as CGRestUtils and NGRestUtils. Only change would be in the handleResponse method
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/utils/RestClientUtils.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/42011#-NKS0Q5N7XnqXDNUE17x:-NKwtIknAC6Y0gieKygE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16bbffcda820e44208e15c79b597760601c20984/970-ng-commons/src/main/java/io/harness/utils/RestClientUtils.java#L26)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can probably keep this under /harness-core/970-ng-commons/src/main/java/io/harness/remote/client itself.
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011#-:-NKwvFrO98nYLsE_ZiMF:bnfp4nl)* status: 1 file(s) to review.

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 17 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011#-:-NKx1QK35Y2iQ-KpxpZR:bnfp4nl)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: :shipit: complete! ✓

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/RestClientUtils.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/42011#-NKx3lPX56AQZMskTYE5:-NKx3lPZ-Ia7fEKDX_Hw:b-vo0137) ([raw file](https://github.com/harness/harness-core/blob/198858a08804f47f9b28d3b04d64f14d5b440653/970-ng-commons/src/main/java/io/harness/remote/client/RestClientUtils.java#L26)):*
> ```Java
> @UtilityClass
> @Slf4j
> public class RestClientUtils {
> ```

why new class if NGRestUtils already there?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: 1 change requests. 1. unresolved discussions. 

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/RestClientUtils.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/42011#-NKx3lPX56AQZMskTYE5:-NKx4uBuDnhDC61jbiAr:b-f3nq1p) ([raw file](https://github.com/harness/harness-core/blob/198858a08804f47f9b28d3b04d64f14d5b440653/970-ng-commons/src/main/java/io/harness/remote/client/RestClientUtils.java#L26)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why new class if NGRestUtils already there?
</blockquote></details>

This util will have the methods that can be used across NGRestUtils, CGRestUtils etc. This removes duplicity of code.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: :shipit: complete! ✓

___
*[`970-ng-commons/src/main/java/io/harness/remote/client/RestClientUtils.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/42011#-NKx3lPX56AQZMskTYE5:-NKxAySI1mlH2asDrCFm:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/198858a08804f47f9b28d3b04d64f14d5b440653/970-ng-commons/src/main/java/io/harness/remote/client/RestClientUtils.java#L26)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

This util will have the methods that can be used across NGRestUtils, CGRestUtils etc. This removes duplicity of code.
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42011)* status: :shipit: complete! ✓

**Pull request merged**
