### PR TITLE
fix: [CDS-41738]: Setting name as EMPTY string for deleted services

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36482)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36482)

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36482)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java` line 451 at r1](https://reviewable.io/reviews/harness/harness-core/36482#-N9jPFBh3MNZOkxY86hU:-N9jPFBh3MNZOkxY86hV:bmpa74i) ([raw file](https://github.com/harness/harness-core/blob/0e3d2c5ad0f93c45ec755627365a4ff99d4efd7a/125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java#L451)):*
> ```Java
>   @Owner(developers = OwnerRule.SHUBHAM_MAHESHWARI)
>   @Category(UnitTests.class)
>   public void testGetLicenseUsageMultipleServicesAndOneDeletedService() {
> ```

Is this test supposed to verify the EMPTY string for deleted services? Or do we already have a test for that?

**Review by shubham-in10se — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36482)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java` line 451 at r1](https://reviewable.io/reviews/harness/harness-core/36482#-N9jPFBh3MNZOkxY86hU:-N9jnYYp2BGcF6M_R_Cs:b-pmu2pt) ([raw file](https://github.com/harness/harness-core/blob/0e3d2c5ad0f93c45ec755627365a4ff99d4efd7a/125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java#L451)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Is this test supposed to verify the EMPTY string for deleted services? Or do we already have a test for that?
</blockquote></details>

Yes. This test is validating that we are setting EMPTY string for the deleted service instances found.
It is checked in the last part of this test:
```   
    Optional<ReferenceDTO> deletedService = licenseUsage.getActiveServices()
                                                .getReferences()
                                                .stream()
                                                .filter(service -> serviceIdentifier2.equals(service.getIdentifier()))
                                                .findFirst();
    assertThat(deletedService.get()).isNotNull();
    assertThat(deletedService.get().getName()).isEqualTo(StringUtils.EMPTY);

```



_Code quote:_
```Java
    Optional<ReferenceDTO> deletedService = licenseUsage.getActiveServices()
                                                .getReferences()
                                                .stream()
                                                .filter(service -> serviceIdentifier2.equals(service.getIdentifier()))
                                                .findFirst();
    assertThat(deletedService.get()).isNotNull();
    assertThat(deletedService.get().getName()).isEqualTo(StringUtils.EMPTY);
```

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36482)* status: 2 file(s) to review. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java` line 451 at r1](https://reviewable.io/reviews/harness/harness-core/36482#-N9jPFBh3MNZOkxY86hU:-N9jql1l8DGU-7WbGO1F:bweoaew) ([raw file](https://github.com/harness/harness-core/blob/0e3d2c5ad0f93c45ec755627365a4ff99d4efd7a/125-cd-nextgen/src/test/java/io/harness/cdng/usage/impl/CDLicenseUsageImplTest.java#L451)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

Yes. This test is validating that we are setting EMPTY string for the deleted service instances found.
It is checked in the last part of this test:
```   
    Optional<ReferenceDTO> deletedService = licenseUsage.getActiveServices()
                                                .getReferences()
                                                .stream()
                                                .filter(service -> serviceIdentifier2.equals(service.getIdentifier()))
                                                .findFirst();
    assertThat(deletedService.get()).isNotNull();
    assertThat(deletedService.get().getName()).isEqualTo(StringUtils.EMPTY);

```
</blockquote></details>

Oh missed that. Looks good then

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36482)* status: :shipit: complete! ✓

**Pull request merged**
