### PR TITLE
feat: [CDS-86480]: Add Abstract Stage plan creator for v1

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Add Abstract stage plan creator for v1 and use it in v1 stages.

**Testing:** Ran a pipeline with custom and ci stage v1 and validated that plan creation happens successfully.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6utWB6tCXokF7XJTj:-Nl6utWB6tCXokF7XJTk:b-kj0d53) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L41)):*
> ```Java
> @CodePulse(module = ProductModule.CDS, unitCoverageRequired = true, components = {HarnessModuleComponent.CDS_PIPELINE})
> @OwnedBy(HarnessTeam.PIPELINE)
> public abstract class AbstractStagePlanCreator<T extends AbstractStageNodeV1> extends ChildrenPlanCreator<T> {
> ```

lets put these common plan creators in pms-commons and not in sdk
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6v0ZKDUokEk1iQdBj:-Nl6v0ZKDUokEk1iQdBk:b-ebs12w) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L68)):*
> ```Java
>   }
> 
>   public List<AdviserObtainment> getBuild(Dependency dependency) {
> ```

what is getBuild?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6v41zDyCMk011C2SS:-Nl6v41zDyCMk011C2ST:b4gm6sz) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java#L152)):*
> ```Java
>     kryo.register(ManualInterventionActionConfigPostRetry.class, 878052);
>     kryo.register(FailureConfigV1.class, 878054);
>     kryo.register(NGVariableV1Wrapper.class, 878055);
> ```

why we need to add here? where we are using it?

**Comment by shalini-agr** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6utWB6tCXokF7XJTj:-Nl6z2cc6kTjiAYwXTtX:b5hbl1x) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets put these common plan creators in pms-commons and not in sdk
</blockquote></details>

We are using some classes of sdk in this class, like PlanCreationContext, ChildrenPlanCreator, etc. 
and we haven't added pms sdk as dependency in pms-commons
so, either we can keep it here in sdk or add sdk dependency in pms-commons

**Comment by shalini-agr** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6v41zDyCMk011C2SS:-Nl6zscsCEHLPtIOuKc5:b-bp5wup) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java#L152)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we need to add here? where we are using it?
</blockquote></details>

in ci plan creator, stageNode is being converted to bytes using kryoserializer and NGVariableWrapper is used in v1 stage node that's why this needs to be added here

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6utWB6tCXokF7XJTj:-Nl77XNjDMRJ_1qgEsUZ:brzldv9) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L41)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

We are using some classes of sdk in this class, like PlanCreationContext, ChildrenPlanCreator, etc. 
and we haven't added pms sdk as dependency in pms-commons
so, either we can keep it here in sdk or add sdk dependency in pms-commons
</blockquote></details>

moved to 878-ng-common-utilities
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6v0ZKDUokEk1iQdBj:-Nl77BCl4qh7ri22xnvy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/v1/AbstractStagePlanCreator.java#L68)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

this method can be renamed to getAdviserObtainments
</blockquote></details>

done
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java` line 152 at r1](https://reviewable.io/reviews/harness/harness-core/56520#-Nl6v41zDyCMk011C2SS:-Nl77iB13jdXv7JTKI3j:b-25yw1k) ([raw file](https://github.com/harness/harness-core/blob/08be390209dc4573683c28b865e56db90a9069cf/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer/PmsSdkCoreKryoRegistrar.java#L152)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

in ci plan creator, stageNode is being converted to bytes using kryoserializer and NGVariableWrapper is used in v1 stage node that's why this needs to be added here
</blockquote></details>

moved to CIContractsKryoRegistrar

**Comment by shalini-agr** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/serializer/CIContractsKryoRegistrar.java` line 166 at r3](https://reviewable.io/reviews/harness/harness-core/56520#-NlMUYbL5bkBFdpyFYGc:-NlMUYbL5bkBFdpyFYGd:b-zhzpet) ([raw file](https://github.com/harness/harness-core/blob/4aa9f9db1940843e4bac680ab74e28a97fb2578f/332-ci-manager/contracts/src/main/java/io/harness/cimanager/serializer/CIContractsKryoRegistrar.java#L166)):*
> ```Java
>     kryo.register(VMRuntimeV1.class, 110147);
>     kryo.register(VMRuntimeSpec.class, 110148);
>     kryo.register(NGVariableV1Wrapper.class, 878055);
> ```

can we add incremental id of 110154 here, keeping series intact and not random number

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`332-ci-manager/contracts/src/main/java/io/harness/cimanager/serializer/CIContractsKryoRegistrar.java` line 166 at r3](https://reviewable.io/reviews/harness/harness-core/56520#-NlMUYbL5bkBFdpyFYGc:-NlMVXVU1zVO-dthRGEq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4aa9f9db1940843e4bac680ab74e28a97fb2578f/332-ci-manager/contracts/src/main/java/io/harness/cimanager/serializer/CIContractsKryoRegistrar.java#L166)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add incremental id of 110154 here, keeping series intact and not random number
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 9 of 15 files at r1, 6 of 7 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: <span>:shipit:</span> complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Review by raghavharness — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 9 of 15 files at r1, 4 of 7 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56520)* status: <span>:shipit:</span> complete! ✓

**Pull request merged**
