### PR TITLE
techDebt: [PL-30730]: Upgrade spring data mongo to 3.4.7 and mongo driver to 4.6.1

### PR DESCRIPTION
**Pull request by kshitij-harness**
## Describe your changes
- Upgrade spring-data-mongo to 3.4.7
- Upgrade spring-data-commons to 2.7.7 as needed for spring-data-mongo
- Upgrade mongo java driver to 4.6.1
- Upgrade mongo quartz to 2.2
- Update methods in HMongoTemplate to match MongoTemplate
- For all classes with extend AbstractMongoClientConfiguration:
  - Update method customConversions
  - Update method mongoTemplate
  -  Update method transactionManager
- Migrate all use cases of MongoDBFactory to MongoDatabaseFactory
- Migrate all use cases of SimpleMongoClientDBFactory to SimpleMongoClientDatabaseFactory
- Removed wait_queue_size metrics as it's no longer supported
- Added projection for classes using aggregate query as UnwindAndRead is no longer available

## Testing Done
- Tested creation of MongoClient in local
- Deployed pipeline, access control, platform, ng-manager, cg-manager in PR environment for basic sanity

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 98 of 98 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: :shipit: complete! ✓

**Review by archit-harness — COMMENTED** [review]
> Reviewed 94 of 98 files at r2, 6 of 6 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: :shipit: complete! ✓

**Review by nikunj-badjatya — DISMISSED** [review]
> Reviewed 94 of 98 files at r2, 6 of 6 files at r3, 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: :shipit: complete! ✓

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 94 of 98 files at r2, 6 of 6 files at r3, 4 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: :shipit: complete! ✓

___
*[`WORKSPACE` line 4810 at r5](https://reviewable.io/reviews/harness/harness-core/43142#-NNKv4NX-dNstutp0xzP:-NNKv4NX-dNstutp0xzQ:bttlpun) ([raw file](https://github.com/harness/harness-core/blob/407005874419ee222e354fef3f14873010bd7bb2/WORKSPACE#L4810)):*
> ```Starlark
>     "com.nimbusds:oauth2-oidc-sdk:7.4",
>     "org.asynchttpclient:async-http-client:2.12.3",
>     "com.novemberain:quartz-mongodb-harness-mongo-ssl:2.1.1-harness-mongo-ssl",
> ```

Check once if in code we are initializing Quartz classes with SSL config
___
*[`WORKSPACE` line 5283 at r5](https://reviewable.io/reviews/harness/harness-core/43142#-NNKvnbcBv6OLvgIUhH-:-NNKvnbcBv6OLvgIUhH0:b7y7ump) ([raw file](https://github.com/harness/harness-core/blob/407005874419ee222e354fef3f14873010bd7bb2/WORKSPACE#L5283)):*
> ```Starlark
>     "org.springframework.boot:spring-boot:2.3.2.RELEASE",
>     "org.springframework.data:spring-data-commons:2.2.7.RELEASE",
>     "org.springframework.data:spring-data-mongodb:2.2.7.RELEASE",
> ```

We can upgrade  these as well to be in sync
Apache 2.0	logo	org.springframework » spring-tx	5.3.25	6.0.4
Dep Injection
Apache 2.0	logo	org.springframework » spring-context	5.3.25	6.0.4
Dep Injection
Apache 2.0	logo	org.springframework » spring-beans	5.3.25	6.0.4
Core Utils
Apache 2.0	logo	org.springframework » spring-core	5.3.25	6.0.4
Expression Lang
Apache 2.0	logo	org.springframework » spring-expression	5.3.25	6.0.4

**Comment by kshitij-harness** [comment]
trigger ft2

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142#-:-NNMRgY49ye_Ueo6uVoh:bnfp4nl)* status: Waiting on team(s): del-team.

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 98 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43142)* status: 3 file(s) to review. 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Comment by kshitij-harness** [comment]
trigger ft1, ft2

**Comment by AnshuH** [comment]
trigger tiAll

**Comment by kshitij-harness** [comment]
trigger ft1,ft2

**Pull request merged**
