### PR TITLE
feat: [SRM-11716]: Srm Slo List View

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37058)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37058)

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37058)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java` line 271 at r1](https://reviewable.io/reviews/harness/harness-core/37058#-NAxV47IC-2F_h5zUoAc:-NAxV47IC-2F_h5zUoAd:btap7ip) ([raw file](https://github.com/harness/harness-core/blob/fb790c5810897993833c552c359bde7d782115b3/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L271)):*
> ```Java
>             .burnRate(sloHealthIndicator.getErrorBudgetBurnRate())
>             .noOfActiveAlerts(slo.getNotificationRuleRefs().size())
>             .noOfMaximumAlerts(5)
> ```

make this a constant. NUMBER_OF_MAX_NOTIFICATIONS

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37058)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/37058#-NBAdJs1-vt7j9gL4wKG:-NBAdJs1-vt7j9gL4wKH:b-gv8yth) ([raw file](https://github.com/harness/harness-core/blob/68f6723505fb287e6f81c72d92e6aa4bdd70ec1e/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java#L20)):*
> ```Java
> public class SLOHealthListView {
>     @NotNull String sloIdentifier;
>     @NotNull String title;
> ```

nit: change it to name only

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Review by deepak-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37058)* status: :shipit: complete! ✓

**Pull request merged**
