### PR TITLE
[feat]: [CDS-51832]: Added method to get environments by identifiers

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
Added method to fetch environment by identifiers (both deleted and non-deleted to be returned).
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43469)

### CODE REVIEW

**Comment by Abhishek-CDC** [comment]
trigger messagecheck

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43469)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 453 at r2](https://reviewable.io/reviews/harness/harness-core/43469#-NNM9CCpEHJ6KQ_gLhsy:-NNM9CCpEHJ6KQ_gLhsz:b-etrzxr) ([raw file](https://github.com/harness/harness-core/blob/fba28d2524d529f39e29ed9ff5c2f5ba26985656/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L453)):*
> ```Java
>   }
> 
>   public List<String> getIdentifiersFromRefs(List<String> envRefsList) {
> ```

Let's move this logic to IdentifierRefHelper with generic params 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 454 at r2](https://reviewable.io/reviews/harness/harness-core/43469#-NNM9LDiCXQ-gRibBlvo:-NNM9LDiCXQ-gRibBlvp:b-m6ekr2) ([raw file](https://github.com/harness/harness-core/blob/fba28d2524d529f39e29ed9ff5c2f5ba26985656/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L454)):*
> ```Java
> 
>   public List<String> getIdentifiersFromRefs(List<String> envRefsList) {
>     // assume same scope
> ```

are we sure, this flow will always have same scoped refs?

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 454 at r2](https://reviewable.io/reviews/harness/harness-core/43469#-NNM9LDiCXQ-gRibBlvo:-NN_Pbyx2c53tqm31CtI:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/fba28d2524d529f39e29ed9ff5c2f5ba26985656/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L454)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

are we sure, this flow will always have same scoped refs? 
</blockquote></details>

yes

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 453 at r2](https://reviewable.io/reviews/harness/harness-core/43469#-NNM9CCpEHJ6KQ_gLhsy:-NN_QbSe6qtGvC3gKGPB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/fba28d2524d529f39e29ed9ff5c2f5ba26985656/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L453)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Let's move this logic to IdentifierRefHelper with generic params 
</blockquote></details>

Done

**Pull request closed without merging**
