### PR TITLE
feat: [CDS-50147]: Use common Yaml ObjectMapper for triggers

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49849)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49849)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/ArtifactJexlConditionsTriggerFilter.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/49849#-NZ5JneG-ch84B7MCkki:-NZ5JneG-ch84B7MCkkj:b5ato3z) ([raw file](https://github.com/harness/harness-core/blob/b80b8cde664f5fb621a25ba9450e7bf6b74cff9c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/ArtifactJexlConditionsTriggerFilter.java#L112)):*
> ```Java
>     ArtifactData artifactData = ArtifactData.newBuilder().putAllMetadata(metadata).setBuild(build).build();
>     String jsonMetadata = "";
>     jsonMetadata = JsonUtils.asJson(metadata);
> ```

JsonPipeline
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/GithubIssueCommentTriggerFilter.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/49849#-NZ5JogE9sAd-EMZXsWj:-NZ5JogE9sAd-EMZXsWk:b5ato3z) ([raw file](https://github.com/harness/harness-core/blob/b80b8cde664f5fb621a25ba9450e7bf6b74cff9c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/GithubIssueCommentTriggerFilter.java#L138)):*
> ```Java
> 
>   private PullRequest generateProtoFromJson(String prJson) throws Exception {
>     JsonNode productNode = YamlUtils.readAsJsonNode(prJson);
> ```

JsonPipeline
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/MetadataConditionsTriggerFilter.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/49849#-NZ5Kj76B2hr0QQfGbmx:-NZ5Kj76B2hr0QQfGbmy:b5ato3z) ([raw file](https://github.com/harness/harness-core/blob/b80b8cde664f5fb621a25ba9450e7bf6b74cff9c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/MetadataConditionsTriggerFilter.java#L118)):*
> ```Java
>     ArtifactData artifactData = ArtifactData.newBuilder().putAllMetadata(metadata).setBuild(build).build();
>     String jsonMetadata = "";
>     jsonMetadata = JsonUtils.asJson(metadata);
> ```

JsonPipeline

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49849)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/ArtifactJexlConditionsTriggerFilter.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/49849#-NZ5JneG-ch84B7MCkki:-NZ5OQZk9Svob7HbW75U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b80b8cde664f5fb621a25ba9450e7bf6b74cff9c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/ArtifactJexlConditionsTriggerFilter.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

JsonPipeline
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/GithubIssueCommentTriggerFilter.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/49849#-NZ5JogE9sAd-EMZXsWj:-NZ5ORJf6EVMzkpJXE0B:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b80b8cde664f5fb621a25ba9450e7bf6b74cff9c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/GithubIssueCommentTriggerFilter.java#L138)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

JsonPipeline
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/MetadataConditionsTriggerFilter.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/49849#-NZ5Kj76B2hr0QQfGbmx:-NZ5ORtvAtQD4mNr0TGN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b80b8cde664f5fb621a25ba9450e7bf6b74cff9c/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/MetadataConditionsTriggerFilter.java#L118)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

JsonPipeline
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger commonchecks

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut0

**Comment by shalini-agr** [comment]
trigger pmd, codebasehash

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49849)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — CHANGES_REQUESTED** [review]
Add unit tests

**Comment by shalini-agr** [comment]
> Add unit tests

**Comment by shalini-agr** [comment]
> Add unit tests

Done

**Comment by shalini-agr** [comment]
trigger uts

**Review by Y0709 — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49849)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49849)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
