### PR TITLE
[feat]: [CVNG-4152]: Register SLOPolicyHandler to Pipeline Service

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30145)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger ti2

**Comment by namanvermah** [comment]
Proto changes are not related to any delegate task, hence this change is backwards compatible.

**Review by archit-harness — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30145)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30145)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
approving as change in only PMS pojos

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30145)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger ti3

**Comment by namanvermah** [comment]
trigger ti0

**Pull request merged**
