### PR TITLE
[feat]: [CDS-54347]: handling listing of chart versions for OCI helm connector

### PR DESCRIPTION
**Pull request by markoharness**
## Describe your changes

We have added new delegate task to be able to list helm chart versions when using OCI helm connector.

Is it new task type?
Yes it is

Did you add a new class which is added in kryo serialization
Yes. New classes will not be used until the delegate release.

Did you make changes to the code in a backward-compatible manner?
Yes.

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager

Did you remove an enum?
No.

Did you add an enum
Yes. Added at the end.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44779)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44779)* status: 20 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/OciHelmResource.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvUWyS6OHCQnoEG_IT:-NPvUWyT6ycCogB1MUYj:bqm6jj2) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/OciHelmResource.java#L58)):*
> ```Java
> @AllArgsConstructor(access = AccessLevel.PACKAGE, onConstructor = @__({ @Inject }))
> @Slf4j
> public class OciHelmResource {
> ```

Let see if we can reuse the same endpoint
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java` line 52 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvVzbL1wjQ7Xa5sirg:-NPvVzbL1wjQ7Xa5sirh:b-xr7ro4) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java#L52)):*
> ```Java
> public class OciHelmServiceImpl implements OciHelmService {
>   private static final long DEFAULT_TIMEOUT = 6000L;
>   private static final List<ConnectorType> validConnectorTypes = Arrays.asList(ConnectorType.OCI_HELM_REPO);
> ```

nit: uppercase with underscore
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvUcf2--38jH22YqG_:-NPvUcf2--38jH22YqGa:bv0laki) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java#L93)):*
> ```Java
>     final DelegateTaskRequest delegateTaskRequest = DelegateTaskRequest.builder()
>                                                         .accountId(ngAccess.getAccountIdentifier())
>                                                         .taskType(TaskType.OCI_HELM_DOCKER_API_LIST_TAGS_TASK_NG.name())
> ```

we need to have a proper validation if there is any delegates that does support this task, if not then we can throw a proper error: no delegates that does support listing oci helm charts etc.
ref: io.harness.grpc.DelegateServiceGrpcImpl#isTaskTypeSupported
io.harness.service.impl.DelegateTaskServiceImpl#isTaskTypeSupportedByAllDelegates
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvVjAr9XMeFzBU-KZM:-NPvVjAr9XMeFzBU-KZN:bemwtnt) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java#L110)):*
> ```Java
>         (OciHelmDockerApiListTagsTaskResponse) delegateResponseData;
>     List<String> chartVersions = ociHelmDockerApiListTagsTaskResponse.getChartVersions();
>     String lastTagFromResponse = ociHelmDockerApiListTagsTaskResponse.getLastTag() != null
> ```

Does this conditional make sense? Is same value as just ociHelmDockerApiListTagsTaskResponse.getLastTag()
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvVX1S-08ZRWF4ObdL:-NPvVX1S-08ZRWF4ObdM:b-ru7du5) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java#L119)):*
> ```Java
> 
>     return OciHelmChartVersionsResponseDTO.builder()
>         .helmChartVersions(chartVersions)
> ```

Can we default this to empty list if is null? or check if (chartVersions == null) {
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiHelper.java` line 124 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvYQRQ0UFIHlWP3sTs:-NPvYQRRAgjigw0JdRx5:b-xmjdm3) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiHelper.java#L124)):*
> ```Java
>   private String normalizeUrl(String url) throws MalformedURLException {
>     try {
>       URL urlObject = new URL(url);
> ```

Can we see if URI is working better here, so we could handle the use case for oci://
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiRestClient.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvZ4M69lNGQFSvONAd:-NPvZ4M69lNGQFSvONAe:b-y1tae5) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiRestClient.java#L28)):*
> ```Java
> 
>   @GET("/v2/{chartName}/tags/list")
>   Call<DockerApiTagsListResponse> getTagsList(@Path(value = "chartName", encoded = true) String chartName,
> ```

Let's rename this method to be clear that is for anonymous case

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiRestClient.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvZ4M69lNGQFSvONAd:-NQ4eBlL13vv0o22qL-T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/OciHelmDockerApiRestClient.java#L28)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's rename this method to be clear that is for anonymous case
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/OciHelmResource.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvUWyS6OHCQnoEG_IT:-NQ4etN06f_1yN-lnp4x:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/120-ng-manager/src/main/java/io/harness/ng/core/manifests/resources/OciHelmResource.java#L58)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let see if we can reuse the same endpoint
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvUcf2--38jH22YqG_:-NQ4ev_B2gWqO03GDGAa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java#L93)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

we need to have a proper validation if there is any delegates that does support this task, if not then we can throw a proper error: no delegates that does support listing oci helm charts etc.
ref: io.harness.grpc.DelegateServiceGrpcImpl#isTaskTypeSupported
io.harness.service.impl.DelegateTaskServiceImpl#isTaskTypeSupportedByAllDelegates
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/44779#-NPvVjAr9XMeFzBU-KZM:-NQ4f188BB0RnGI-PpJI:b-51fw1h) ([raw file](https://github.com/harness/harness-core/blob/cc1e6777be2a754a57290bca3302241119dac285/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/manifest/resources/OciHelmServiceImpl.java#L110)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Does this conditional make sense? Is same value as just ociHelmDockerApiListTagsTaskResponse.getLastTag()
</blockquote></details>

removed the condition. It was unnecessary.

**Comment by markoharness** [comment]
trigger feature-build

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 18 of 20 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44779)* status: 22 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44779)* status: 23 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by mdmilic — APPROVED** [review]
Approving delegate changes

> Reviewed 3 of 20 files at r1, 8 of 20 files at r2, 2 of 5 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44779#-:-NQBEfOu6iiesSbWaITh:b-a53hb1)* status: 12 file(s) to review. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/docker/DockerApiTagsListResponse.java` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/44779#-NQBDz6w-qYPmXQkTeHC:-NQBDz6w-qYPmXQkTeHD:b-l3wom4) ([raw file](https://github.com/harness/harness-core/blob/a91f6cfd1a3d27c115fdd21ab102951b49a7ae45/960-api-services/src/main/java/io/harness/docker/DockerApiTagsListResponse.java#L18)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> @Data
> ```

FYI you should either use @Value or make fields private finale. Now they are package private. This also means you have only no args ctor, retrofit should be able to handle your all args ctor.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 20 files at r1, 7 of 20 files at r2, 3 of 5 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44779)* status: :shipit: complete! ✓

**Pull request merged**
