### PR TITLE
feat: [CDS-47336]: Added filtering active services per org, project and service

### PR DESCRIPTION
**Pull request by ivan-83**
- Added filtering active services per org, project, and service identifiers
- Taking care of SQL injections

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41987)

### CODE REVIEW

**Comment by ivan-83** [comment]
trigger checkstylecodeformat

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41987)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41987)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java` line 277 at r2](https://reviewable.io/reviews/harness/harness-core/41987#-NKHel1C32-csSI6M5Uw:-NKHel1C32-csSI6M5Ux:b-n2odrr) ([raw file](https://github.com/harness/harness-core/blob/6be13a828ad6067782980b86cff22c5d31db7490/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java#L277)):*
> ```Java
>         log.error("Failed to fetch active services, accountIdentifier : [{}] , retry : [{}]", accountIdentifier, retry,
>             exception);
>         retry++;
> ```

if there will be thrown another type of exception, we will end up in infinite loop.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/41987#-NKHezk16JpRt6zZctmK:-NKHezk16JpRt6zZctmL:b-gybazn) ([raw file](https://github.com/harness/harness-core/blob/6be13a828ad6067782980b86cff22c5d31db7490/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L122)):*
> ```Java
>     Pageable pageRequest = defaultUsageRequestParams.getPageRequest();
>     ActiveServicesFilterParams filterParams = (ActiveServicesFilterParams) defaultUsageRequestParams.getFilterParams();
>     Scope scope = getScope(accountIdentifier, filterParams);
> ```

how about the previous comment:
` the following filter calls are needed because ng_instance_stats and service_infra_info tables do not contain`



_Code quote:_
```Java
 the following filter calls are needed because ng_instance_stats and service_infra_info tables do not contain
```

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41987)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java` line 277 at r2](https://reviewable.io/reviews/harness/harness-core/41987#-NKHel1C32-csSI6M5Uw:-NKHoqj64RHdotmTZ0Fe:botiduz) ([raw file](https://github.com/harness/harness-core/blob/6be13a828ad6067782980b86cff22c5d31db7490/125-cd-nextgen/src/main/java/io/harness/cdng/usage/CDLicenseUsageDAL.java#L277)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

if there will be thrown another type of exception, we will end up in infinite loop.
</blockquote></details>

If any SQLException is thrown, and the number of retries is greater or equal  MAX_RETRY, the loop will be ended.
 If non SQLException is thrown, the exception will not be caught and will be rethrown by the method and the loop will be ended. 
Pls, let me know if we are missing smt. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/41987#-NKHezk16JpRt6zZctmK:-NKJ9cuu2tthqjJzdvon:bxe7q39) ([raw file](https://github.com/harness/harness-core/blob/6be13a828ad6067782980b86cff22c5d31db7490/125-cd-nextgen/src/main/java/io/harness/cdng/usage/impl/CDLicenseUsageImpl.java#L122)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

how about the previous comment:
` the following filter calls are needed because ng_instance_stats and service_infra_info tables do not contain`
</blockquote></details>

We are sending ids from UI instead of names in order not to make the additional calls on BE side to obtain the ids based on names. UI already has the ids and names available.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41987)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41987#-:-NKJN4KA9Lu4q7ej5sIi:bnfp4nl)* status: :shipit: complete! ✓

**Comment by ivan-83** [comment]
trigger ti1

**Pull request merged**
