### PR TITLE
feat: [CDS-47349]: Add lock on notify response cleanup

### PR DESCRIPTION
**Pull request by inderschera**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40853)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40853)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-wait-engine/src/main/java/io/harness/waiter/NotifyResponseCleaner.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/40853#-NI75YYc2Wohe_C5Ykkl:-NI75SdvA2C3kwYqDbBE:bpwbza3) ([raw file](https://github.com/harness/harness-core/blob/c189414247cb11b7105ea5c512410a9460441a4d/950-wait-engine/src/main/java/io/harness/waiter/NotifyResponseCleaner.java#L54)):*
> ```Java
>       if (lockNotifyResponseCleanup) {
>         try (AcquiredLock lock = persistentLocker.waitToAcquireLock(
>                  NotifyResponse.class, NOTIFY_RESPONSE_LOCK, Duration.ofSeconds(10), Duration.ofSeconds(1))) {
> ```

where is the null check, this will always execute, if you cannot acquire lock just log and return

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40853)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by inderschera** [comment]
trigger feature-build

**Comment by inderschera** [comment]
trigger messagecheck

**Comment by inderschera** [comment]
trigger feature-build

**Review by hextechpal — APPROVED** [review]
> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40853)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 4 of 7 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40853)* status: :shipit: complete! ✓

**Pull request merged**
