### PR TITLE
feat: [CDS-52614]: Aws Lambda Service Changes

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Describe your changes

This PR is for implementing Service Step of Aws Lambda Swimlane in NG. Some changes are already merged in this PR https://github.com/harness/harness-core/pull/43463.   Spec could be found here - https://docs.google.com/document/d/1QJEQwDnQV0_Kkgmm-gnoeOIMUSR9mm8tg2HC7mO7M-0/edit# 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43594)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Review by PragyeshMishra01 — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 12 of 12 files at r2, 41 of 41 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43594)* status: 53 file(s) to review.

**Review by PragyeshMishra01 — APPROVED** [review]
> Reviewed 12 of 12 files at r2, 41 of 41 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43594)* status: :shipit: complete! ✓

**Pull request merged**
