### PR TITLE
fix: [CDS-45975]: Onboarding setup usages framework for environments

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Have added entity framework support for environment config,manifest .
## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43602)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 814 at r6](https://reviewable.io/reviews/harness/harness-core/43602#-NONjWDV8n-o3z7OejW9:-NONjWDV8n-o3z7OejWA:b-99gabd) ([raw file](https://github.com/harness/harness-core/blob/61788ba9cb33b081026ca201293db4897032306a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L814)):*
> ```Java
>     }
>   }
>   private Set<String> getreferredEntitytypes(Environment environment) {
> ```

nit: getReferredEntitiyTypes -  camel case



_Code quote (from 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/NGEnvironmentGlobalOverrideVisitorHelper.java):_
```Java
nmentGlobalOverrideVisitorHelper implements Confi
```

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43602)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 814 at r6](https://reviewable.io/reviews/harness/harness-core/43602#-NONjWDV8n-o3z7OejW9:-NOOrMIF753_x_Z3O8Yo:btpte1o) ([raw file](https://github.com/harness/harness-core/blob/61788ba9cb33b081026ca201293db4897032306a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L814)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: getReferredEntitiyTypes -  camel case
</blockquote></details>

fixed it

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/setupusage/SetupUsageHelper.java` line 76 at r6](https://reviewable.io/reviews/harness/harness-core/43602#-NNez_SCnaA7ThpRvZmt-r6-76:-NOOrPRXD9cSxqzO9HhX:b-3kk4lg) ([raw file](https://github.com/harness/harness-core/blob/61788ba9cb33b081026ca201293db4897032306a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/setupusage/SetupUsageHelper.java#L76)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Can we create a separate class for environment and infra setup usage ? 
The "SetupUsageHelper" is a very generic name it creates confusion sometimes
</blockquote></details>

Have created a separate class for environments.

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/setupusage/SetupUsageHelper.java` line 81 at r6](https://reviewable.io/reviews/harness/harness-core/43602#-NNez_SCnaA7ThpRvZmt-r6-81:-NOOrWtq64picmdhJvtR:busaxrw) ([raw file](https://github.com/harness/harness-core/blob/61788ba9cb33b081026ca201293db4897032306a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/setupusage/SetupUsageHelper.java#L81)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better way to acheive this is

referredEntities.stream().collect(Collectors.toMap(proto -> proto.getType.getName, Function::Identity))


</blockquote></details>

Fixed it

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 9 files at r8, 4 of 9 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43602)* status: Some of the checks are too old. 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/setupusage/EnvironmentEntitySetupUsageHelper.java` line 55 at r13](https://reviewable.io/reviews/harness/harness-core/43602#-NOfTksq3rUKmVeAEBHq:-NOfTksq3rUKmVeAEBHr:brtwun5) ([raw file](https://github.com/harness/harness-core/blob/2addcc452c432d86e82cee6f64bd53f3712bf046/127-cd-nextgen-entities/src/main/java/io/harness/setupusage/EnvironmentEntitySetupUsageHelper.java#L55)):*
> ```Java
>       }
>     }
>     return visitor.getEntityReferenceSet();
> ```

can we not just walk the ngEnvironmentconfig at once ?
You might need to override the "getchildrenToWalk" method to include overrides and variables

**Comment by vivekkarnatiharness** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/setupusage/EnvironmentEntitySetupUsageHelper.java` line 55 at r13](https://reviewable.io/reviews/harness/harness-core/43602#-NOfTksq3rUKmVeAEBHq:-NOr9J1y-edwywChIrKk:bjkx2r6) ([raw file](https://github.com/harness/harness-core/blob/2addcc452c432d86e82cee6f64bd53f3712bf046/127-cd-nextgen-entities/src/main/java/io/harness/setupusage/EnvironmentEntitySetupUsageHelper.java#L55)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we not just walk the ngEnvironmentconfig at once ?
You might need to override the "getchildrenToWalk" method to include overrides and variables
</blockquote></details>

NGEnvironmentConfig does not extends visitor class,so we can't  walk though this object.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 9 files at r8, 13 of 13 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43602)* status: :shipit: complete! ✓

**Pull request merged**
