### PR TITLE
fix: [CHAOS-352]: Updating new chaos terminology in License, Audit and AccessControl

### PR DESCRIPTION
**Pull request by imrajdas**
Signed-off-by: Raj Babu Das <rajbabu.das@harness.io>

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38297)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 8 Issues 
* Code issue 7 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38297)

**Comment by imrajdas** [comment]
trigger codebasehash

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38297)* status: 18 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/38297#-NDb0AfI7Z05_bRw8I61:-NDb0AfI7Z05_bRw8I62:b-25c7vx) ([raw file](https://github.com/harness/harness-core/blob/9843c2df42373d7a4b1f95f19ae4f738f6f32fbb/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L85)):*
> ```YAML
>   - identifier: VARIABLE
>     permissionKey: variable
>   - identifier: CHAOS_HUB
> ```

Version
___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/38297#-NDb08dN9OKB-1Arei3w:-NDb08dN9OKB-1Arei3x:bw6jlj7) ([raw file](https://github.com/harness/harness-core/blob/9843c2df42373d7a4b1f95f19ae4f738f6f32fbb/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L125)):*
> ```YAML
>         - core_variable_delete
>         - chaos_chaoshub_view
>         - chaos_chaoshub_edit
> ```

Please update the version

**Review by reetika04 — COMMENTED** [review]
> Reviewed 12 of 18 files at r1, 3 of 4 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38297)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
There are no changes wrt Delegate here, hence approving for codebase hash check

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by imrajdas** [comment]
trigger codebasehash

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 12 of 18 files at r1, 3 of 4 files at r3, 1 of 2 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38297)* status: :shipit: complete! ✓

**Review by reetika04 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38297)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38297)* status: :shipit: complete! ✓

**Pull request merged**
