### PR TITLE
[fix]: [PLG-3085]: changed canny-username-abbreviation-enabled API to use clientAccountId

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
changed canny-username-abbreviation-enabled API to use clientAccountId

@PUT API: 
`https://localhost:8181/gateway/api/account/kmpySmUISimoRrJL6NL73w/canny-username-abbreviation-enabled?routingId=kmpySmUISimoRrJL6NL73w&clientAccountId=kmpySmUISimoRrJL6NL73w&cannyUsernameAbbreviationEnabled=true`

Response:
```
{
    "metaData": {},
    "resource": {
        "uuid": "kmpySmUISimoRrJL6NL73w",
        "appId": "__GLOBAL_APP_ID__",
        "createdBy": null,
        "createdAt": 1684757371309,
        "lastUpdatedBy": {
            "uuid": "lv0euRhKRCyiXWzS7pOg6g",
            "name": "Admin",
            "email": "admin@harness.io",
            "externalUserId": null
        },
        "lastUpdatedAt": 1701699482094,
        "companyName": "Harness",
        "nextGenEnabled": true,
        "accountName": "Harness",
        "whitelistedDomains": [],
        "licenseId": null,
        "dataRetentionDurationMs": 0,
        "licenseInfo": {
            "accountType": "PAID",
            "accountStatus": "ACTIVE",
            "expiryTime": 1716402599000,
            "licenseUnits": 1500
        },
        "trustLevel": -1,
        "ceLicenseInfo": null,
        "accountEvents": null,
        "subdomainUrl": null,
        "twoFactorAdminEnforced": false,
        "forImport": false,
        "migratedToClusterUrl": null,
        "defaultExperience": "CG",
        "createdFromNG": false,
        "accountActivelyUsed": true,
        "smpAccount": false,
        "sessionTimeOutInMinutes": 1440,
        "publicAccessEnabled": false,
        "localEncryptionEnabled": false,
        "delegateConfiguration": null,
        "techStacks": null,
        "oauthEnabled": false,
        "ringName": "ring3",
        "accountPreferences": null,
        "cloudCostEnabled": false,
        "ceAutoCollectK8sEvents": false,
        "trialSignupOptions": null,
        "serviceGuardLimit": 20,
        "serviceAccountConfig": null,
        "globalDelegateAccount": false,
        "immutableDelegateEnabled": true,
        "optionalDelegateTaskLimit": null,
        "importantDelegateTaskLimit": null,
        "authenticationMechanism": "USER_PASSWORD",
        "encryption": null,
        "povAccount": false,
        "productLed": false,
        "defaults": {},
        "harnessSupportAccessAllowed": true,
        "crossGenerationAccessEnabled": false,
        "cannyUsernameAbbreviationEnabled": true
    },
    "responseMessages": []
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56283)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger uts

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by Xin-Harness — APPROVED** [review]

**Comment by kapil-harness** [comment]
trigger review

**Pull request merged**
