### PR TITLE
feat: [PIE-2915]: Deleting environment groups

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31665)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31665)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 203 at r2](https://reviewable.io/reviews/harness/harness-core/31665#-Mypm_rv416ZeZyNunGe:-Mypm_rv416ZeZyNunGf:bk7r8f1) ([raw file](https://github.com/harness/harness-core/blob/a81ee84c4ec900dd46ed942adc44d8f17931def5/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L203)):*
> ```Java
>   }
> 
>   //Delete api
> ```

nit, this comment not needed
___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 214 at r2](https://reviewable.io/reviews/harness/harness-core/31665#-MypmmeN7pv8npfXcNf0:-MypmmeN7pv8npfXcNf1:byg151t) ([raw file](https://github.com/harness/harness-core/blob/a81ee84c4ec900dd46ed942adc44d8f17931def5/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L214)):*
> ```Java
>                                   ApiResponse(responseCode = "default", description = "Returns true if the Environment Group is deleted")
>                   })
>   public ResponseDTO<Boolean>
> ```

boolean can't be extended in future, would recommend using an object here

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31665)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java, line 214 at r2](https://reviewable.io/reviews/harness/harness-core/31665#-MypmmeN7pv8npfXcNf0:-Myq3qjmA8y2jt-EQUbt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a81ee84c4ec900dd46ed942adc44d8f17931def5/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/resource/EnvironmentGroupResource.java#L214)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

boolean can't be extended in future, would recommend using an object here
</blockquote></details>

Done.

**Comment by prashantsharma04** [comment]
trigger ti0

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 3 of 5 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31665)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 3 of 5 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31665)* status: 1 file(s) to review. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java, line 83 at r4](https://reviewable.io/reviews/harness/harness-core/31665#-MyuGVq81FttkQpzFMHz:-MyuGVq99pnMO5qhBW0d:b-htusbj) ([raw file](https://github.com/harness/harness-core/blob/c80cfca5d3a46be6f0601fa08e9d57f5be74ce2f/125-cd-nextgen/src/main/java/io/harness/cdng/envGroup/services/EnvironmentGroupServiceImpl.java#L83)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error(String.format("Error while deleting Environment Group [%s]", envGroupId), e);
> ```

nit, we don't need to log and throw at the same time. While throwing, you can pass "e" as a parameter and it will log.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 3 of 12 files at r1, 3 of 5 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31665#-:-MyuIr6B2kAwD0Ji1ZTm:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
