### PR TITLE
[fix]: [CDS-35638]: Restrict users to use setting attributes based on usage scope in config as code

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Restrict users to use setting attributes based on usage scope in config as code

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33344)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 19 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33344)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/33344#-N2S51yZEKt66h3CYg61:-N2S51yb9AfcZDE7tGiC:b-b0usux) (no related file):*
Lets check that users are able to see proper message when they create/update entities from Git ( and do not have access to the involved cloud provider ) 

___

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 19 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33344)* status: :shipit: complete! ✓

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 19 of 19 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33344)* status: :shipit: complete! ✓

**Pull request merged**
