### PR TITLE
feat: [PIE-3034]: Reduce orchestration event log

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31305)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31305)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[800-pipeline-service/config.yml, line 413 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQ5MM4EX_35DnonXj:-MxrQ5MM4EX_35DnonXk:b-p29byf) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/800-pipeline-service/config.yml#L413)):*
> ```YAML
> allowedParallelStages: ${ALLOWED_PARALLEL_STAGES:-25}
> 
> reduceOrchestrationLog: ${REDUCE_ORCHESTRATION_EVENT_LOG:-true}
> ```

we should make it feature flag
___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java, line 475 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQNhn-z5tvw9EmhJD:-MxrQNhn-z5tvw9EmhJE:b-c6bemy) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java#L475)):*
> ```Java
>         injector.getInstance(Key.get(TimeoutInstanceRemover.class)));
> 
>     if (!appConfig.getReduceOrchestrationLog()) {
> ```

If FF we would need to change
___
*[800-pipeline-service/src/main/java/io/harness/PipelineServiceConfiguration.java, line 125 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQSs0B7S1atgPORSN:-MxrQSs0B7S1atgPORSO:bgreq8h) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/800-pipeline-service/src/main/java/io/harness/PipelineServiceConfiguration.java#L125)):*
> ```Java
>   @JsonProperty("allowedParallelStages") private int allowedParallelStages;
>   @JsonProperty("debeziumConfig") private DebeziumConfig debeziumConfig;
>   @JsonProperty("reduceOrchestrationLog") private Boolean reduceOrchestrationLog;
> ```

not applicable
___
*[860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationEndGraphHandler.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQkQY9WSFn3DBIir_:-MxrQkQY9WSFn3DBIira:b46huod) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationEndGraphHandler.java#L57)):*
> ```Java
>         graphGenerationService.updateGraphWithWaitLock(planExecution.getUuid());
>         // We are not deleting logs pro-actively if exception occurred, they will be helpful in debugging.
>         // orchestrationEventLogRepository.deleteLogsForGivenPlanExecutionId(ambiance.getPlanExecutionId());
> ```

intentional?
___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 294 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQylD8t00EQav_ZP-:-MxrQylD8t00EQav_ZP0:bvuu58j) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L294)):*
> ```Java
>   }
> 
>   private boolean shouldLog(Update updateOps) {
> ```

just to double check, we are not missing any cases here
___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 327 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrRRjT0vOP1D8TIeRf:-MxrRRjT0vOP1D8TIeRg:b-x4jnpy) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L327)):*
> ```Java
>       }
>       eventEmitter.emitEvent(builder.build());
>       return transactionHelper.performTransaction(() -> {
> ```

do not fire observers inside transaction
___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 402 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrR_Nh55F3DPZrYI-x:-MxrR_Nh55F3DPZrYI-y:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L402)):*
> ```Java
>           orchestrationLogPublisher.onNodeStatusUpdate(NodeUpdateInfo.builder().nodeExecution(updated).build());
>         }
>         stepStatusUpdateSubject.fireInform(
> ```

ditto
___
*[870-orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java, line 62 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrRdyL3uw6nrhC-CZq:-MxrRdyL3uw6nrhC-CZr:b-z4umzo) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/event/OrchestrationLogPublisher.java#L62)):*
> ```Java
>   @Override
>   public void onNodeUpdate(NodeUpdateInfo nodeUpdateInfo) {
>     createAndHandleEventLog(nodeUpdateInfo.getNodeExecution().getPlanExecutionId(),
> ```

nit, create a proxy method in update info

**Comment by sahilhindwani-harness** [comment]
___
*[860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationEndGraphHandler.java, line 57 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQkQY9WSFn3DBIir_:-MxrXdVg96AOddZyyOBP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/860-orchestration-visualization/src/main/java/io/harness/event/OrchestrationEndGraphHandler.java#L57)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

intentional?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 294 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrQylD8t00EQav_ZP-:-MxrXfc56iWJG8g628sE:bphjhwq) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L294)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

just to double check, we are not missing any cases here
</blockquote></details>

Added a test case for set and addToSet

**Comment by sahilhindwani-harness** [comment]
___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 327 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrRRjT0vOP1D8TIeRf:-MxrXjLkDExX-q20Xeto:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L327)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

do not fire observers inside transaction
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
___
*[870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, line 402 at r2](https://reviewable.io/reviews/harness/harness-core/31305#-MxrR_Nh55F3DPZrYI-x:-MxrXk0vEp0R30V0eoqo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8256ae53a8a13de93558fd5154340e65e693f6e6/870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L402)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by hextechpal — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31305#-:-Mxs62Nn-6ZL_oRyLh-u:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
