### PR TITLE
fix: [CDS-80440]: Fix merge templates logic with OPA_PIPELINE_GOVERNANCE

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Merge v0/v1 templates in v1 pipelines in the flow when OPA_PIPELINE_GOVERNANCE FF is enabled.

**Testing:** Tested locally and in devspace.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger gitleaks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 30 files at r6, 27 of 32 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: Some of the checks are too old. 34 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 692 at r7](https://reviewable.io/reviews/harness/harness-core/53816#-NgIQ7f-Bb_zlPFp_r48:-NgIQ7f-Bb_zlPFp_r49:bwr4gk) ([raw file](https://github.com/harness/harness-core/blob/d83d1fb261673b12e65eb12923aab852ceb58f67/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L692)):*
> ```Java
>       if (HarnessYamlVersion.isV1(templateEntity.getHarnessVersion())) {
>         return MergeTemplateInputsInObject.builder()
>             .resMap(resMap)
> ```

i think we had this code somewhere else as well, can we make this util or private method?
___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java` line 44 at r7](https://reviewable.io/reviews/harness/harness-core/53816#-NgIQFrB-A55riq5Rl3F:-NgIQFrB-A55riq5Rl3G:byahly8) ([raw file](https://github.com/harness/harness-core/blob/d83d1fb261673b12e65eb12923aab852ceb58f67/template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java#L44)):*
> ```Java
>       String templateChildType) {
>     JsonNode schema =
>         ngTemplateSchemaService.getIndividualStaticSchema(templateEntityType.getNodeGroup(), templateChildType, "v0");
> ```

what impact it will have on v0?

**Comment by krishi0408** [comment]
trigger uts

**Comment by krishi0408** [comment]
trigger gitleaks

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: Some of the checks are too old. 34 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 692 at r7](https://reviewable.io/reviews/harness/harness-core/53816#-NgIQ7f-Bb_zlPFp_r48:-NgIRNcz3HmUl0qm3Mpt:b642n54) ([raw file](https://github.com/harness/harness-core/blob/d83d1fb261673b12e65eb12923aab852ceb58f67/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L692)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think we had this code somewhere else as well, can we make this util or private method?
</blockquote></details>

yeah, in that method we didn't set resMapWithOpaResponse, but yes can be taken out in a private method.
___
*[`template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java` line 44 at r7](https://reviewable.io/reviews/harness/harness-core/53816#-NgIQFrB-A55riq5Rl3F:-NgISa3vCoDN0JqpZLWt:b-cigzsd) ([raw file](https://github.com/harness/harness-core/blob/d83d1fb261673b12e65eb12923aab852ceb58f67/template-service/service/src/main/java/io/harness/template/resources/NGTemplateSchemaResourceImpl.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what impact it will have on v0?
</blockquote></details>

this will return the individual static schema for v0, earlier we were not sending templateChildType so it was not able to send the schema for specific stage or step, this change fixes that.
This is the same change we HF'ed in template service and deployed in prod.

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by shalini-agr** [comment]
trigger uts

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: 34 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 692 at r7](https://reviewable.io/reviews/harness/harness-core/53816#-NgIQ7f-Bb_zlPFp_r48:-NgIpJ6h5Kv7fI0g4hZG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d83d1fb261673b12e65eb12923aab852ceb58f67/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L692)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

yeah, in that method we didn't set resMapWithOpaResponse, but yes can be taken out in a private method.
</blockquote></details>

done

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 32 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: 34 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 632 at r8](https://reviewable.io/reviews/harness/harness-core/53816#-NgJ-i923XbJ9h9HQm3E:-NgJ-i93AXWHwo-52wHh:b-i3xan5) ([raw file](https://github.com/harness/harness-core/blob/52526061393ab217e3cffbd3e73884c3d24a1cd9/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L632)):*
> ```Java
>       String fieldName = childYamlField.getName();
>       JsonNode value = childYamlField.getNode().getCurrJsonNode();
>       boolean isTemplatePresent = isTemplatePresent(fieldName, value, yamlNode.getCurrJsonNode());
> ```

we are passing both value and currentJsonNode -> could it be something better?



_Code quote:_
```Java
isTemplatePresent(fieldName, value, yamlNode.getCurrJsonNode());
```
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 638 at r8](https://reviewable.io/reviews/harness/harness-core/53816#-NgJ-vSA4ZE8eKpn1rj5:-NgJ-vSA4ZE8eKpn1rj6:b-yzvqym) ([raw file](https://github.com/harness/harness-core/blob/52526061393ab217e3cffbd3e73884c3d24a1cd9/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L638)):*
> ```Java
>         JsonNode templateJsonNode = value;
>         if (HarnessYamlVersion.isV1(currentYamlVersion)) {
>           templateJsonNode = yamlNode.getCurrJsonNode();
> ```

can we extract in private method?

**Comment by shalini-agr** [comment]
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 632 at r8](https://reviewable.io/reviews/harness/harness-core/53816#-NgJ-i923XbJ9h9HQm3E:-NgJ7Qjr91nH35Fvlrg3:b8se76f) ([raw file](https://github.com/harness/harness-core/blob/52526061393ab217e3cffbd3e73884c3d24a1cd9/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L632)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we are passing both value and currentJsonNode -> could it be something better?
</blockquote></details>

yeah, we can get value from currJsonNode and fieldName using:
yamlNode.getCurrJsonNode().get(fieldName) 

then won't need to send value

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: 34 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 632 at r8](https://reviewable.io/reviews/harness/harness-core/53816#-NgJ-i923XbJ9h9HQm3E:-NgJCFJn6bkttGHNEDrc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/52526061393ab217e3cffbd3e73884c3d24a1cd9/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L632)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

yeah, we can get value from currJsonNode and fieldName using:
yamlNode.getCurrJsonNode().get(fieldName) 

then won't need to send value
</blockquote></details>

done
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java` line 638 at r8](https://reviewable.io/reviews/harness/harness-core/53816#-NgJ-vSA4ZE8eKpn1rj5:-NgJCEPd42TBz3PehNZ-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/52526061393ab217e3cffbd3e73884c3d24a1cd9/template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java#L638)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we extract in private method?
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: 34 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
LGTM

> Reviewed 2 of 30 files at r6, 32 of 32 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816#-:-NgJuU8N9V-B8GQlNnGN:bb6ywmx)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53816)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
