### PR TITLE
[feat]: [CDS-68206]: Error handling when required fields are not present

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Describe your changes
It is possible that certain fields are not assigned value or declared as expressions or inputs.
Some of these fields might be required for fetching the relevant details for which delegate task is created.
Added validation for such fields before creating delegate tasks for APIs to fetch lastSuccessfulBuild.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)

### CODE REVIEW

**Comment by Abhishek-CDC** [comment]
trigger uts

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 24 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyplKz25rU8jJ6BLf-:-NUyplKz25rU8jJ6BLf0:b-lujnoi) ([raw file](https://github.com/harness/harness-core/blob/2fc016651626219836fecd94df9745f4fab31123/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java#L112)):*
> ```Java
>   public GcrBuildDetailsDTO getSuccessfulBuild(IdentifierRef gcrConnectorRef, String imagePath,
>       GcrRequestDTO gcrRequestDTO, String orgIdentifier, String projectIdentifier) {
>     ArtifactUtils.validateIfValueNotAssigned(NGCommonEntityConstants.IMAGE_PATH, imagePath);
> ```

nit, you could use variable args Java API, ref - https://stackoverflow.com/questions/7243145/java-method-with-unlimited-arguments

This code will become concise.
___
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyqEWdAqfTo5sYrGxS:-NUyqEWdAqfTo5sYrGxT:bok1932) ([raw file](https://github.com/harness/harness-core/blob/2fc016651626219836fecd94df9745f4fab31123/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L81)):*
> ```Java
>   public static final String VERSION_REGEX = "versionRegex";
>   public static final String PACKAGE = "package";
>   public static final String PACKAGE_NAME = "packageName";
> ```

fyi, this artifact expression constants can go in it's own class which can live in 125 module.

Keeping the code layered and self-contained will help to extract things in the future if required. Keeping the code in a shared class like this makes the extraction hard.

**Review by puthrayaharness — DISMISSED** [review]

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 20 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 24 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 222 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NVDBg9R-RIJWotwXD3P:-NVDBg9R-RIJWotwXD3Q:bguqp9t) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L222)):*
> ```Java
>         imagePath = null;
>       } else {
>         imagePath = imageParameter.getValue();
> ```

we can directly return from here and the above if statement
Also, instead of returning null, you can explore returning Optional.empty()

Returning null from methods is not advised
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NVDCRAc0XS5PCPlIP_B:-NVDCRAd6R-XJJeTQloW:b9t36ly) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L295)):*
> ```Java
>       throw new InvalidRequestException(String.format("value for %s and %s is empty or not provided", key1, key2));
>     }
>   }
> ```

We can use java varargs to write a single method for handling any number of keys
___
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyqEWdAqfTo5sYrGxS:-NVDCXGD2kymSYq3xxDW:b3cee12) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L81)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

fyi, this artifact expression constants can go in it's own class which can live in 125 module.

Keeping the code layered and self-contained will help to extract things in the future if required. Keeping the code in a shared class like this makes the extraction hard.
</blockquote></details>

+1. This should be 125 or 127

**Comment by Abhishek-CDC** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 222 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NVDBg9R-RIJWotwXD3P:-NVEBS_i-JM5t3VGFBZ1:b-1lqk1o) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L222)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can directly return from here and the above if statement
Also, instead of returning null, you can explore returning Optional.empty()

Returning null from methods is not advised
</blockquote></details>

As discussed, since this method has many usages returning optional will require changes for those usages also.
Adding @Nullable annotation to this method

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyplKz25rU8jJ6BLf-:-NVEBuF40NIAlEbXdYX1:b-j5mkpx) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java#L112)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, you could use variable args Java API, ref - https://stackoverflow.com/questions/7243145/java-method-with-unlimited-arguments

This code will become concise.
</blockquote></details>

Created method with varargs but keeping method calls same as earlier for specific error messages.

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NVDCRAc0XS5PCPlIP_B:-NVECAGR1zJWe0kyYHpy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L295)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We can use java varargs to write a single method for handling any number of keys
</blockquote></details>

Done.

**Comment by Abhishek-CDC** [comment]
*[`970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java` line 81 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyqEWdAqfTo5sYrGxS:-NVECEN85FcGNNvbOqHr:b-j7o4ce) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/970-ng-commons/src/main/java/io/harness/constants/NGCommonEntityConstants.java#L81)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

+1. This should be 125 or 127 
</blockquote></details>

Added new class for this

**Comment by Abhishek-CDC** [comment]
trigger commonchecks

**Comment by Abhishek-CDC** [comment]
trigger uts

**Comment by Abhishek-CDC** [comment]
trigger codebasehash

**Comment by Abhishek-CDC** [comment]
trigger uts

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 17 of 18 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 25 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NVDCRAc0XS5PCPlIP_B:-NVERLYE0-mrm84eHOuP:b-jo9yzf) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L295)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just checking it test is there for this method, because it has some logic which can be tricky

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 295 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NVDCRAc0XS5PCPlIP_B:-NVEYr5685Vp30fCSafu:b-pm8x9) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L295)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Just checking it test is there for this method, because it has some logic which can be tricky
</blockquote></details>

Scenarios for this method are included with tests for different artifacts. Please refer ResourceServiceImplTest (Example: GarResourceServiceImplTest) files for different artifacts.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 9 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 16 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 297 at r3](https://reviewable.io/reviews/harness/harness-core/47504#-NVEbjxB59B9fNd91wwt:-NVEbjxB59B9fNd91wwu:b-p9ksb5) ([raw file](https://github.com/harness/harness-core/blob/b53d4343fa5f117bdafd6bd1443f10348cbf2fa3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L297)):*
> ```Java
>       } else {
>         if (!checkIfNullOrRuntime(value[i])) {
>           return;
> ```

I am wondering how this method is working. It seems it will work for only 1 key-value pair.

If any key-value pair is as expected, you are returning.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 16 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 286 at r3](https://reviewable.io/reviews/harness/harness-core/47504#-NVEc1SDDsP8e9dpFMBV:-NVEc1SDDsP8e9dpFMBW:b-mtwobj) ([raw file](https://github.com/harness/harness-core/blob/b53d4343fa5f117bdafd6bd1443f10348cbf2fa3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L286)):*
> ```Java
>   }
> 
>   public void validateIfValueNotAssigned(String... value) {
> ```

You are complicating the method signature. You can pass an object that contains 2 fields - key and value. Then you don't have to do the parsing of key value using odd/even conditions.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 16 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyplKz25rU8jJ6BLf-:-NVEcNEi7IIep_ELLHFw:b-hmkpxe) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java#L112)):*
<details><summary><i>Previously, Abhishek-CDC (Abhishek) wrote…</i></summary><blockquote>

Created method with varargs but keeping method calls same as earlier for specific error messages.
</blockquote></details>

You will get specific error messages once you fix the actual function.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 16 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyplKz25rU8jJ6BLf-:-NVEcRfb3r73ZAbOq6UA:b-zdaf6o) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java#L112)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

You will get specific error messages once you fix the actual function.
</blockquote></details>

Whenever a key-value pair is wrong, you can prepare the error message accordingly -  "That this key has empty value."

**Comment by Abhishek-CDC** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/47504#-NUyplKz25rU8jJ6BLf-:-NVEoJc21D59Qq8UWsRo:bisfmwa) ([raw file](https://github.com/harness/harness-core/blob/6ad26404d960ea717bea95ad15562e424f2277bc/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service/GcrResourceServiceImpl.java#L112)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Whenever a key-value pair is wrong, you can prepare the error message accordingly -  "That this key has empty value."
</blockquote></details>

Done. Created new var args method to check all have values assigned

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 286 at r3](https://reviewable.io/reviews/harness/harness-core/47504#-NVEc1SDDsP8e9dpFMBV:-NVEoY9V66N3qMtjlqWk:b-k9uner) ([raw file](https://github.com/harness/harness-core/blob/b53d4343fa5f117bdafd6bd1443f10348cbf2fa3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L286)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

You are complicating the method signature. You can pass an object that contains 2 fields - key and value. Then you don't have to do the parsing of key value using odd/even conditions.
</blockquote></details>

Done. Passing pair object

**Comment by Abhishek-CDC** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 297 at r3](https://reviewable.io/reviews/harness/harness-core/47504#-NVEbjxB59B9fNd91wwt:-NVEoeS9-vLMILRhEgna:bpvlz6z) ([raw file](https://github.com/harness/harness-core/blob/b53d4343fa5f117bdafd6bd1443f10348cbf2fa3/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L297)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

I am wondering how this method is working. It seems it will work for only 1 key-value pair.

If any key-value pair is as expected, you are returning.
</blockquote></details>

As discussed, expectation from this method was to check if any of the field has value assigned and not every field.
Have renamed methods to avoid confusions.

**Comment by Abhishek-CDC** [comment]
trigger uts

**Review by puthrayaharness — APPROVED** [review]

**Review by puthrayaharness — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504)* status: 19 file(s) to review. 1 change requests. 2. unresolved discussions.

**Comment by Abhishek-CDC** [comment]
trigger review

**Review by vaibhav-si — APPROVED** [review]
Explained the comments offline.

> Reviewed 1 of 24 files at r1, 4 of 18 files at r2, 6 of 6 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47504#-:-NVEfCzr0g5EQpGO5m9n:b-ol702v)* status: :shipit: complete! ✓

**Pull request merged**
