### PR TITLE
[feat]: [PL-43892]: Connector service scope info changes for Create connector

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes

Make Connector service API changes to consume ScopeInfo rather than user specified org, project identifiers

Testing done :

- Tested for Create Connector in Org, Project, Account level
- Tested that the Update, Delete connector flow is working (not impacted) due to this change

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger ut5

**Comment by pbarapatre10** [comment]
trigger ut6

**Comment by pbarapatre10** [comment]
trigger ut8

**Comment by pbarapatre10** [comment]
trigger ut9

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)* status: 41 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NGSecretManagerMigration.java` line 96 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-Nnn_ndM-tK29ioptrBp:-Nnn_ndM-tK29ioptrBq:bp135r) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/core/migration/NGSecretManagerMigration.java#L96)):*
> ```Java
> @Slf4j
> @OwnedBy(PL)
> public class NGSecretManagerMigration {
> ```

Is this migration still needed? Can we remove this? cc : @nishantsaini20

**Comment by pbarapatre10** [comment]
trigger uts

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)* status: 45 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java` line 325 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnYVOb9vYj0Ba7JM3P:-Nns4bmt1wiBHLY1TqG8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/ConnectorServiceImpl.java#L325)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats this null indicate?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java` line 227 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnZQ_G2jKk-6qqe3Wq:-Nns57kQET8oNQe3HShS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/SecretManagerConnectorServiceImpl.java#L227)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any reason to resolve here? Can't we pass from above?
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/CIDefaultEntityManager.java` line 34 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnVXoGB0o-jue0sOq6:-Nns59H96QPRjMtECLqD:b-a05ibr) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/core/event/CIDefaultEntityManager.java#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why do we need to resolve scope here? Isn't it just accountIdentifier needed here as default entities are created at account scope?
</blockquote></details>

No, here we do see that organization and project are also being considered, thanks
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnWGox-H2bpAt36MuL:-Nns5dbC0cGqTleVDiDt:bea6ixg) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L105)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is this scope resolution temporary? Should we pass scopeInfo instead from the caller here?
</blockquote></details>

This is coming in the AccountSetupListener flow. We can update the `AccountEntityChangeDTO` to have the ScopeInfo and uniqueId as did for OrganizationEntityDTO, Will handle that in separate PR
___
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 280 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnWy3D8TKq-J4QhB16:-Nns6orHB08QLuW6H_MI:bnabft5) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L280)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Would this result into a remote call?
</blockquote></details>

No this would be an internal service call only
___
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 399 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnWrKV3LT_JNq6pKes:-Nns7CpE9yDr0aliSbLd:b-1un1xd) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L399)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we not handle it now itself?
</blockquote></details>

This is CI code, where the scopeInfo can come from Resource, but we are not changing Resource for CI servies. This would get removed once they use the @Context ScopeInfo, thanks
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java` line 214 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnXa08-ITZIjHvsmGZ:-Nns9MvAAwIJer2yLHGD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java#L214)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this resolution happen in createAccountScopedConnector method?
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/OrgConnectorApiImpl.java` line 225 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnXllbDNFtdOunS2VA:-NnsBXPd5uJmiW386g8L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/OrgConnectorApiImpl.java#L225)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this resolution happen in createOrgScopedConnector method?
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java` line 225 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnXjnL7jcBw5nDRJ5w:-NnsBlgQ-9HURS8UVobP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java#L225)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this resolution happen in createProjectScopedConnector method?
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/gitsync/ConnectorGitSyncHelper.java` line 108 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnYC94EyLrNQuQ1DH1:-NnsBxTeEpRf94sk3sDR:b-dp5ouh) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/440-connector-nextgen/src/main/java/io/harness/connector/gitsync/ConnectorGitSyncHelper.java#L108)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any risk of NullPointerException
</blockquote></details>

No, since we are already handling as `.oElseThrow()`, thanks

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r6, 16 of 26 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)* status: 45 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/CIDefaultEntityManager.java` line 37 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoAHZzh0dPWtHuK1y5d:-NoAHZzh0dPWtHuK1y5e:blzhwzf) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/event/CIDefaultEntityManager.java#L37)):*
> ```Java
>   @Inject ScopeInfoService scopeResolverService;
> 
>   public void createCIDefaultEntities(String accountIdentifier, ScopeInfo scopeInfo) {
> ```

Do we need to pass accountIdentifier?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 105 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnWGox-H2bpAt36MuL:-NoAHPm-9Fnke0vrFFVi:bf4ucyz) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L105)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

This is coming in the AccountSetupListener flow. We can update the `AccountEntityChangeDTO` to have the ScopeInfo and uniqueId as did for OrganizationEntityDTO, Will handle that in separate PR
</blockquote></details>

But for Account we know whats the ScopeInfo and uniqueId. Do we really need to change `AccountEntityChangeDTO`?
___
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 280 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnWy3D8TKq-J4QhB16:-NoAHktqEcOYJz1fhH08:b-v2qsdo) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L280)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

No this would be an internal service call only
</blockquote></details>

Thats because we have logic in Client?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r6, 10 of 26 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)* status: 45 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 140 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoAxsbvCt8-lJcv-ste:-NoAxsbvCt8-lJcv-stf:b-4j56ei) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L140)):*
> ```Java
>               .orgIdentifier(organizationEntityChangeDTO.getIdentifier())
>               .scopeType(ScopeLevel.ORGANIZATION)
>               .uniqueId(organizationEntityChangeDTO.getUniqueId())
> ```

What would happen if events without uniqueId are received?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 194 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoAyHzh55mLpg4jv8vN:-NoAyHzh55mLpg4jv8vO:b-4j56ei) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L194)):*
> ```Java
>               .orgIdentifier(projectEntityChangeDTO.getOrgIdentifier())
>               .projectIdentifier(projectEntityChangeDTO.getIdentifier())
>               .uniqueId(projectEntityChangeDTO.getUniqueId())
> ```

What would happen if events without uniqueId are received?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 231 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoAyIX6EJlMQNU2wPey:-NoAyIX6EJlMQNU2wPez:b-4j56ei) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L231)):*
> ```Java
>               .orgIdentifier(projectEntityChangeDTO.getOrgIdentifier())
>               .projectIdentifier(projectEntityChangeDTO.getIdentifier())
>               .uniqueId(projectEntityChangeDTO.getUniqueId())
> ```

What would happen if events without uniqueId are received?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java` line 74 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoAyblUANQuOqvHORDi:-NoAyblUANQuOqvHORDj:b70hqs5) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/event/HarnessSMManager.java#L74)):*
> ```Java
>   }
> 
>   public void createHarnessSecretManager(String accountIdentifier, ScopeInfo scopeInfo) {
> ```

Should we remove accountIdentifier from here?

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)* status: 45 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NGSecretManagerMigration.java` line 183 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoB5y4CAadEap6RVyGr:-NoB5y4D9dqdPss--Bce:b-9lc8nj) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/migration/NGSecretManagerMigration.java#L183)):*
> ```Java
>   }
> 
>   private void handleHarnessManagedSM(String accountIdentifier, String orgIdentifier, String projIdentifier,
> ```

We can pass scopeInfo here, isn't it?

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java` line 280 at r5](https://reviewable.io/reviews/harness/harness-core/57374#-NnnWy3D8TKq-J4QhB16:-NoAVfsc0J7MAp4L7l3s:bndcltl) ([raw file](https://github.com/harness/harness-core/blob/a34e98a3c51861757dadaa9085412814d991a943/120-ng-manager/src/main/java/io/harness/ng/trialsignup/ProvisionService.java#L280)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Thats because we have logic in Client?
</blockquote></details>

We are not using the ScopeInfoClient here, but directly using the scopeInfoService, which constructs the Scope

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/NGSecretManagerMigration.java` line 183 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoB5y4CAadEap6RVyGr:-NoF-x_F5UkSYkO-SRvM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/migration/NGSecretManagerMigration.java#L183)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can pass scopeInfo here, isn't it?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java` line 140 at r7](https://reviewable.io/reviews/harness/harness-core/57374#-NoAxsbvCt8-lJcv-ste:-NoF0Vb4BI7ojUfLeQlG:b-yyrwpg) ([raw file](https://github.com/harness/harness-core/blob/369e3d2d012ee2445c88dcc82bb1f57ef7faa57d/120-ng-manager/src/main/java/io/harness/ng/core/event/ConnectorEntityCRUDStreamListener.java#L140)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

What would happen if events without uniqueId are received?
</blockquote></details>

For now there won't be any issue, as we rely on identifiers value only in the subsequent getConnectorDTO() calls for createSecretManager. Once we incorporate ScopeInfo in getConnector flow then to not re-compute ScopeInfo uniqueId will be needed, thanks

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 1 of 6 files at r6, 6 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374)* status: 46 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57374#-:-NoGR3Yb0-Kqh3e3X2_S:bnfp4nl)* status: 46 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
