### PR TITLE
feat: [CDS-2886]: support for step level override for K8sApplyStep

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 326 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQBb9H11AutBH4YlJX:-MwQBb9I5igeyaOj5D2h:b-8ml4rs) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L326)):*
> ```Java
>   }
> 
>   public GitFetchFilesConfig convertGitFileConfig(
> ```

Are we handling anywhere expressions and comma separated filePath? ref: populateRemoteGitConfigFilePathList
Would it possible to extract this logic and have it in common with application manifest logic? 
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 343 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQD7Aj62oxMi13comm:-MwQD7Ak6G2sXjyZN6MR:b-ak5k5w) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L343)):*
> ```Java
>   public ExecutionResponse executeGitTask(ExecutionContext context,
>       Map<K8sValuesLocation, ApplicationManifest> appManifestMap, String activityId, String commandName,
>       GitFileConfig gitFileConfig) {
> ```

Let's rename this to something more explaining the purpose of it
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 370 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQD_150Z0sfSgS4TPV:-MwQD_150Z0sfSgS4TPW:b-up7hq8) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L370)):*
> ```Java
>     if (gitFileConfig != null) {
>       fetchFilesTaskParams.getGitFetchFilesConfigMap().put(
>           "Service", convertGitFileConfig(gitFileConfig, context.getAppId(), context.getWorkflowExecutionId()));
> ```

If we will override Service here, how the values.yaml that are in manifest already will be handled? 
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 706 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQDlCn0WrGmDv7oxki:-MwQDlCn0WrGmDv7oxkj:b-pstrv2) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L706)):*
> ```Java
>     return ((K8sStateExecutionData) context.getStateExecutionData()).getActivityId();
>   }
>   public GitFileConfig getApplyStateGitConfig(K8sStateExecutor k8sStateExecutor) {
> ```

I'll suggest that this method by default will return null and override it in K8sApplyState and have proper naming, ex: getStepRemoteOverrideGitConfig
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 724 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQED0OE291iksGzrn_:-MwQED0OE291iksGzrna:b76l96s) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L724)):*
> ```Java
>       boolean customSourceParams = false;
>       boolean ocTemplateSource = false;
>       GitFileConfig gitFileConfig = getApplyStateGitConfig(k8sStateExecutor);
> ```

the name of this var should be more descriptive
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 95 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQERuk1XLEwmI4fFEU:-MwQERuk1XLEwmI4fFEV:ba87mmy) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L95)):*
> ```Java
>   @Getter @Setter @Attributes(title = "Export manifests") private boolean exportManifests;
>   @Getter @Setter @Attributes(title = "Inherit manifests") private boolean inheritManifests;
>   @Getter @Setter @Attributes(title = "Override remote values yaml") private GitFileConfig gitFileConfig;
> ```

name of this should be more descriptive
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 162 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQGLdC2a8SE_9p1AIR:-MwQGCt-EDyNoximQ-aE:b-2jhjl2) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L162)):*
> ```Java
>     storePreviousHelmDeploymentInfo(context, appManifestMap.get(K8sValuesLocation.Service));
> 
>     if (isBlank(stepValuesOverride)) {
> ```

This logic expect that or you have inline value or you have remote, there is no condition handling when there is no any of this
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 188 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQEoH_3iCx7p48uGck:-MwQEoH_3iCx7p48uGcl:b-kqn18w) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L188)):*
> ```Java
> 
>     List<String> valuesYamlList = fetchRenderedValuesFiles(appManifestMap, context);
>     if (isNotEmpty(stepValuesOverride)) {
> ```

can we move this logic in fetchRenderedValuesFiles?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: 4 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 326 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQBb9H11AutBH4YlJX:-MwR2vBsEcyXOiMW8w7v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L326)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Are we handling anywhere expressions and comma separated filePath? ref: populateRemoteGitConfigFilePathList
Would it possible to extract this logic and have it in common with application manifest logic? 
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 343 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQD7Aj62oxMi13comm:-MwRIlMQ0D6tI6v7Lzbk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L343)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's rename this to something more explaining the purpose of it
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 370 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQD_150Z0sfSgS4TPV:-MwR2yxWE4G_-WK583ah:b-bs7yfw) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L370)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

If we will override Service here, how the values.yaml that are in manifest already will be handled? 
</blockquote></details>

Done. Added a new type in K8sValuesLocation -- 'Step'
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 706 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQDlCn0WrGmDv7oxki:-MwRJO9Q5uBrfeO_GVcW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L706)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I'll suggest that this method by default will return null and override it in K8sApplyState and have proper naming, ex: getStepRemoteOverrideGitConfig
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, line 724 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQED0OE291iksGzrn_:-MwRJUNnCCuPYCKiDpE7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java#L724)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

the name of this var should be more descriptive
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 95 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQERuk1XLEwmI4fFEU:-MwRJnA81Fl0LSEnp-Pq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L95)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

name of this should be more descriptive
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 162 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQGLdC2a8SE_9p1AIR:-MwRJv0e92Ol35HfT6de:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L162)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This logic expect that or you have inline value or you have remote, there is no condition handling when there is no any of this
</blockquote></details>

Done.
___
*[400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java, line 188 at r1](https://reviewable.io/reviews/harness/harness-core/30869#-MwQEoH_3iCx7p48uGck:-MwS7GwL2ZUI1YLmvkmj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c4245835921986f0003a8781693cab050856b48b/400-rest/src/main/java/software/wings/sm/states/k8s/K8sApplyState.java#L188)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can we move this logic in fetchRenderedValuesFiles?
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 4 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/test/java/software/wings/sm/states/k8s/AbstractK8SStateTest.java, line 1545 at r7](https://reviewable.io/reviews/harness/harness-core/30869#-Mwfeavd66r_PbuCMVQ4:-Mwfeavd66r_PbuCMVQ5:b-fxya7v) ([raw file](https://github.com/harness/harness-core/blob/e167987d0bc08058d8c830c53f10acd217b568d6/400-rest/src/test/java/software/wings/sm/states/k8s/AbstractK8SStateTest.java#L1545)):*
> ```Java
>   @Owner(developers = ACHYUTH)
>   @Category(UnitTests.class)
>   public void testExecuteWrapperWithManifestStepOverride() {
> ```

Can we add a test for fetchRenderedValues and check that values are in right order?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/test/java/software/wings/sm/states/k8s/AbstractK8SStateTest.java, line 1545 at r7](https://reviewable.io/reviews/harness/harness-core/30869#-Mwfeavd66r_PbuCMVQ4:-MwfvSnu-ahblx_spq0d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e167987d0bc08058d8c830c53f10acd217b568d6/400-rest/src/test/java/software/wings/sm/states/k8s/AbstractK8SStateTest.java#L1545)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we add a test for fetchRenderedValues and check that values are in right order?
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: :shipit: complete! ✓

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 2 of 4 files at r5, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: Some of the checks are too old.

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30869)* status: Some of the checks are too old.

**Pull request merged**
