### PR TITLE
feat: [PL-22631]: Add condition in test for public apis

### PR DESCRIPTION
**Pull request by rijajoo**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30752)

### CODE REVIEW

**Review by rathodmeetsatish — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[980-commons/src/test/java/io/harness/oas/OASModule.java, line 56 at r1](https://reviewable.io/reviews/harness/harness-core/30752#-MvtJQ8-6e30vQk9ibpZ:-MvtJQ8-6e30vQk9ibp_:b43bn72) ([raw file](https://github.com/harness/harness-core/blob/287e8db7f573a7dc8b6090c35819ab4785f954ff/980-commons/src/test/java/io/harness/oas/OASModule.java#L56)):*
> ```Java
> 
>   public void testOASAdoption(Collection<Class<?>> classes) {
>     List<String> dtoWithoutTagNameOrDescription = new ArrayList<>();
> ```

please change this name

**Comment by rijajoo** [comment]
trigger messagecheck

**Review by rathodmeetsatish — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752#-:-Mw0x3Dr37441K-vxd6v:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752#-:-Mw13SI490dcOq0yTAyp:bnfp4nl)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752#-:-Mw15Cbx2t-Mr0S4_5X2:bnfp4nl)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752#-:-Mw15gIi6pTQoi29XDUH:bnfp4nl)* status: 2 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752#-:-Mw15xT-2FIjznTmfY9V:bnfp4nl)* status: 2 file(s) to review.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30752)* status: :shipit: complete! ✓

**Pull request merged**
