### PR TITLE
[feat]: [CDS-50612]: add terraform cloud API client

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
[feat]: [CDS-50612]: add terraform cloud API client
Screenshot 2023-01-24 at 00 13 58

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-50612]: https://harness.atlassian.net/browse/CDS-50612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)

### CODE REVIEW

**Review by alebuh — APPROVED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 23 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terraformcloud/model/RunData.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/42929#-NMT2PRyAUDJyNnAfU2p:-NMT2PRyAUDJyNnAfU2q:b-uxvlzy) ([raw file](https://github.com/harness/harness-core/blob/1788b6621c16af4cc5f7a2dc02e77384a065df46/960-api-services/src/main/java/io/harness/terraformcloud/model/RunData.java#L39)):*
> ```Java
>     @JsonProperty("empty_apply") private boolean emptyApply;
>     @JsonProperty("target-addrs") private List<String> targets;
>     List<Variable> variables;
> ```

Are we going to need "configuration-version" field here? We might need it for rollback right?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 23 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terraformcloud/model/RunData.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/42929#-NMT2PRyAUDJyNnAfU2p:-NMT4vM55Aab_gEWZDcZ:b9e3rp2) ([raw file](https://github.com/harness/harness-core/blob/1788b6621c16af4cc5f7a2dc02e77384a065df46/960-api-services/src/main/java/io/harness/terraformcloud/model/RunData.java#L39)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

Are we going to need "configuration-version" field here? We might need it for rollback right?
</blockquote></details>

configuration-version to be used for a run should go to relationships:
    "relationships": {
      "workspace": {
        "data": {
          "type": "workspaces",
          "id": "ws-LLGHCr4SWy28wyGN"
        }
      },
      "configuration-version": {
        "data": {
          "type": "configuration-versions",
          "id": "cv-n4XQPBa2QnecZJ4G"
        }
      }

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 23 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terraformcloud/model/RunData.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/42929#-NMT2PRyAUDJyNnAfU2p:-NMT5YrJEWgWP18XwAs_:b-vmrs4e) ([raw file](https://github.com/harness/harness-core/blob/1788b6621c16af4cc5f7a2dc02e77384a065df46/960-api-services/src/main/java/io/harness/terraformcloud/model/RunData.java#L39)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

configuration-version to be used for a run should go to relationships:
    "relationships": {
      "workspace": {
        "data": {
          "type": "workspaces",
          "id": "ws-LLGHCr4SWy28wyGN"
        }
      },
      "configuration-version": {
        "data": {
          "type": "configuration-versions",
          "id": "cv-n4XQPBa2QnecZJ4G"
        }
      }
</blockquote></details>

and for an existing run is it coming also under relationships

**Review by alebuh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by alebuh — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 23 file(s) to review. 1 of 2 approvals obtained.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: :shipit: complete! ✓

**Review by jennyjames21 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: :shipit: complete! ✓

___
*[`960-api-services/BUILD.bazel` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMURkbZDWPb_XvzdpI8:-NMURkbZDWPb_XvzdpI9:bx97rqn) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/BUILD.bazel#L123)):*
> ```Starlark
>         "//960-api-services/src/main/java/io/harness/terraform/expression:module",
>         "//960-api-services/src/main/java/io/harness/terraformcloud:module",
>         "//960-api-services/src/main/java/io/harness/terragrunt:module",
> ```

Is this something to use in delegate to execute task?

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 1 change requests. 1. unresolved discussions. 

___
*[`960-api-services/BUILD.bazel` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMURkbZDWPb_XvzdpI8:-NMUTPJf4DgI7UezYBQW:b-xlcoxz) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/BUILD.bazel#L123)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Is this something to use in delegate to execute task? 
</blockquote></details>

yes, we will use the API client in some delegate tasks

**Comment by jennyjames21** [comment]
*[`960-api-services/BUILD.bazel` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMURkbZDWPb_XvzdpI8:-NMU_YFaDzj2EuB218rY:b-76qzfm) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/BUILD.bazel#L123)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

yes, we will use the API client in some delegate tasks
</blockquote></details>

Any External dependencies need to scan for any vulnerabilities. 
If you split modules into 2(one for task-specific and one for rest), you can avoid importing unwanted dependencies to delegate.
Also the goal is to keep the delegate lightweight.

**Comment by jennyjames21** [comment]
*[`960-api-services/BUILD.bazel` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMURkbZDWPb_XvzdpI8:-NMUiPJSE_juoU-AJnIi:bxa1kvx) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/BUILD.bazel#L123)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Any External dependencies need to scan for any vulnerabilities. 
If you split modules into 2(one for task-specific and one for rest), you can avoid importing unwanted dependencies to delegate.
Also the goal is to keep the delegate lightweight.
</blockquote></details>

@raghuAtWings , Do we need to scan for vulnerability for external dependencies before checkin?

**Comment by raghuAtWings** [comment]
*[`960-api-services/src/main/java/io/harness/terraformcloud/model/Data.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMV1zm44Qt6aaarr9XW:-NMV1zm5CeRrZI3uKcvs:bdma9s5) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/src/main/java/io/harness/terraformcloud/model/Data.java#L33)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @lombok.Data
> public abstract class Data {
> ```

don''t thing any of these should be in 960-api-services, if they are used in delegate then they should be added in 930-delegate-tasks

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 1 change requests. 1. unresolved discussions.

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/BUILD.bazel` line 123 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMURkbZDWPb_XvzdpI8:-NMVgGsX3JllH4uY7fz6:br5beh1) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/BUILD.bazel#L123)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why are these added here? we should add the dependency where its used, are you using them in 960-api-services?
</blockquote></details>

Done, added the dependency on 930 module and tests dependencies
___
*[`960-api-services/src/main/java/io/harness/terraformcloud/model/Data.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/42929#-NMV1zm44Qt6aaarr9XW:-NMVgBpZE04vD4tGMcnz:b3jnyzs) ([raw file](https://github.com/harness/harness-core/blob/40e34bf39a7f3e8c37b043d94b55c5970129cd0d/960-api-services/src/main/java/io/harness/terraformcloud/model/Data.java#L33)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don''t thing any of these should be in 960-api-services, if they are used in delegate then they should be added in 930-delegate-tasks
</blockquote></details>

Those will be used on manager and delegate.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vlica-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by alebuh — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42929)* status: 1 change requests. 1. unresolved discussions.

**Comment by tmacari-harness** [comment]
trigger ti4

**Pull request merged**
