### PR TITLE
fix: [CDS-51810]: handle empty scoped params for CD crud

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. handle empty scoped params for CD crud
2. check for referred entities in create, upsert, update of infra, service
3. Improve error message when mismatched children and parent entities

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 7 files at r2, 2 of 2 files at r3, 7 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 124 at r5](https://reviewable.io/reviews/harness/harness-core/43054#-NMlo6qNALw5GaFxqnvE:-NMlo6qNALw5GaFxqnvF:b58oakh) ([raw file](https://github.com/harness/harness-core/blob/c9754126b5cc9be3e4735cc07ea36fc243bdd692/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L124)):*
> ```Java
>       setNameIfNotPresent(infraEntity);
>       modifyInfraRequest(infraEntity);
>       Set<EntityDetailProtoDTO> referredEntities = getAndValidateReferredEntities(infraEntity);
> ```

should be final

**Review by utkarshchoubey-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 7 files at r2, 1 of 2 files at r3, 7 of 9 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)* status: 1 file(s) to review.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 491 at r5](https://reviewable.io/reviews/harness/harness-core/43054#-NMlqyJM2aPSWTXzTFg1:-NMlqyJM2aPSWTXzTFg2:b-b4tcsk) ([raw file](https://github.com/harness/harness-core/blob/c9754126b5cc9be3e4735cc07ea36fc243bdd692/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L491)):*
> ```Java
>       List<Set<EntityDetailProtoDTO>> referredEntityList = new ArrayList<>();
>       for (ServiceEntity serviceEntity : serviceEntities) {
>         referredEntityList.add(getAndValidateReferredEntities(serviceEntity));
> ```

lets throw InvalidRequestException here with service identifier so that user can know which service is at fault



_Code quote:_
```Java
      String serviceNames = serviceEntities.stream().map(ServiceEntity::getName).collect(Collectors.joining(","));
      log.info(
          "Encountered exception while saving the service entity records of [{}], with exception", serviceNames, ex);
      throw new UnexpectedException("Encountered exception while saving the service entity records.");
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntitySetupUsageHelper.java` line 56 at r5](https://reviewable.io/reviews/harness/harness-core/43054#-NMlrB6z-PwU1-dM2mwF:-NMlrB6z-PwU1-dM2mwG:b-prrtdy) ([raw file](https://github.com/harness/harness-core/blob/c9754126b5cc9be3e4735cc07ea36fc243bdd692/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntitySetupUsageHelper.java#L56)):*
> ```Java
>    * Update setup usages for the current service entity with referred entities
>    */
>   protected void updateSetupUsages(ServiceEntity entity, Set<EntityDetailProtoDTO> referredEntities) {
> ```

we should create a separate method for createSetupUsages as discussed

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 517 at r6](https://reviewable.io/reviews/harness/harness-core/43054#-NMmnIjQ5h9JDza9umFJ:-NMmnIjQ5h9JDza9umFK:b-14adau) ([raw file](https://github.com/harness/harness-core/blob/f68e10f7431ef98a9e44962550a45e68cd9096db/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L517)):*
> ```Java
>     } catch (WingsException ex) {
>       String infraNames = infraEntities.stream().map(InfrastructureEntity::getName).collect(Collectors.joining(","));
>       log.info("Encountered exception while saving the infrastructure entity records of [{}], with exception",
> ```

should be log.error()

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 7 files at r2, 2 of 2 files at r3, 4 of 9 files at r4, 1 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 516 at r6](https://reviewable.io/reviews/harness/harness-core/43054#-NMmnon99ZVEjHMU_pVP:-NMmnon99ZVEjHMU_pVQ:b-18n7vx) ([raw file](https://github.com/harness/harness-core/blob/f68e10f7431ef98a9e44962550a45e68cd9096db/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L516)):*
> ```Java
>     } catch (WingsException ex) {
>       String serviceNames = serviceEntities.stream().map(ServiceEntity::getName).collect(Collectors.joining(","));
>       log.info(
> ```

nit: shoud be log.error()

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 2 of 2 files at r3, 4 of 9 files at r4, 2 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)* status: 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43054)* status: :shipit: complete! ✓

**Pull request merged**
