### PR TITLE
fix: [DEL-5855]: Support to dequeue delegate task when task is aborted

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- When task gets aborted and if the task is not in DB but in queue service, then we need cancel or dequeue task from queue service 

Test Performed
-  Unit test to abort task
- Sanity test, k8 end to end flow and NG pipeline execution

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43033)

### CODE REVIEW

**Comment by jennyjames21** [comment]
k8 task flow
image

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43033)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 275 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgD-21J8Ba0EzXf6O:-NMcgD-21J8Ba0EzXf6P:b-35w3c6) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L275)):*
> ```Java
>   public void addToAbortTaskEventList(@NotNull String accountId, String delegateTaskId) {
>     abortTaskEvents.putIfAbsent(accountId, new ArrayList<>());
>     abortTaskEvents.get(accountId).add(delegateTaskId);
> ```

question: any specific reason to make this list per accountId, how about if we maintain a single list of delegateTaskId ?



_Code quote:_
```Java
get(accountId).add(delegateTaskId);
```
___
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMchCGVDGWtSX1ZcGXh:-NMchCGVDGWtSX1ZcGXi:b-1g2x77) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L283)):*
> ```Java
>     synchronized (abortTaskEvents) {
>       abortTaskEventList = new HashMap<>(abortTaskEvents);
>       abortTaskEvents.clear();
> ```

why we are clearing the list here ? It's possible that the task being aborted, but we didn't consume it.



_Code quote:_
```Java
abortTaskEvents.clear();
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1697 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgb5S80f9VDoH9GXm:-NMcgb5S80f9VDoH9GXn:bdlaeo4) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1697)):*
> ```Java
>                                ErrorNotifyResponseData.builder().errorMessage("Delegate task was aborted").build()))
>                            .build());
> ```

Should we call addToAbortTaskEventList here as well ?



_Code quote:_
```Java
 delegateTaskQueueService.addToAbortTaskEventList(accountId, delegateTaskId);
```

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 275 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgD-21J8Ba0EzXf6O:-NMeBuLn50uypI1jSQt4:b-wp962z) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L275)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

question: any specific reason to make this list per accountId, how about if we maintain a single list of delegateTaskId ?
</blockquote></details>

it's more of double check since queue service identified queued objects based on accountid and delegatetask id

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMchCGVDGWtSX1ZcGXh:-NMeCG6u3oyEpBzSqFrO:bv312rl) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L283)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

why we are clearing the list here ? It's possible that the task being aborted, but we didn't consume it.
</blockquote></details>

so dequeue(pull from queue) runs every 15 seconds. Synchronize() to make sure only one thread works on the list at a time to avoid collisions. 
Clearing list here as multiple threads will try to put more items in the list.

Note we dont expect this list very large but the frequency on dequeue check is high

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1697 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgb5S80f9VDoH9GXm:-NMeNWUB-ngKOx6P-Hy6:b-q4ooe0) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1697)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Should we call addToAbortTaskEventList here as well ?
</blockquote></details>

CI task already migrated to V2 flow so not making the change on V1. Queueing will only be enabled for CI customers for some time.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43033)* status: 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 275 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgD-21J8Ba0EzXf6O:-NMizd8J6aYsAcsE88k3:b-9gtqs6) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L275)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

it's more of double check since queue service identified queued objects based on accountid and delegatetask id
</blockquote></details>

It's generally better/faster that the property you are querying for is your key. You could just keep a Set<taskId> as Gaurav suggested, but if you want to have accountId as a check you could also invert your hashmap. I.e. Map<String, String> -> taskId to accountId. This way taskId is your hashkey, so you should always have O(1) access (accessing it in a list is O(N)). You probably won't have too many items in the list, so wouldn't be significant difference, but just a thought. 
Write side (both adding and removing items) is faster in this case as well, but considering we don't expect too many writes (it's read heavy) again won't be noticeable difference. 
___
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMchCGVDGWtSX1ZcGXh:-NMj19po41ILWI_wXf3f:b-5hztfe) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L283)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

so dequeue(pull from queue) runs every 15 seconds. Synchronize() to make sure only one thread works on the list at a time to avoid collisions. 
Clearing list here as multiple threads will try to put more items in the list.

Note we dont expect this list very large but the frequency on dequeue check is high 
</blockquote></details>

I don't think you would need synchronization here or synchronized collections, you should only remove the taskId that is being dequeued. Inverting Map would help with that.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 275 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgD-21J8Ba0EzXf6O:-NN4DGgY5v-7-kt1fcDV:b1qlqmm) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L275)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

It's generally better/faster that the property you are querying for is your key. You could just keep a Set<taskId> as Gaurav suggested, but if you want to have accountId as a check you could also invert your hashmap. I.e. Map<String, String> -> taskId to accountId. This way taskId is your hashkey, so you should always have O(1) access (accessing it in a list is O(N)). You probably won't have too many items in the list, so wouldn't be significant difference, but just a thought. 
Write side (both adding and removing items) is faster in this case as well, but considering we don't expect too many writes (it's read heavy) again won't be noticeable difference. 
</blockquote></details>

updated to concurrent set, for now, we can rely on only taskid.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMchCGVDGWtSX1ZcGXh:-NN4DX2PC1W4rtoNyVt3:b-wbnu3y) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/io/harness/delegate/queueservice/DelegateTaskQueueService.java#L283)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I don't think you would need synchronization here or synchronized collections, you should only remove the taskId that is being dequeued. Inverting Map would help with that. 
</blockquote></details>

we ST that runs every 15 seconds on all manager nodes that dequeue tasks from queue service (peek like operation) and acknowledge the dequeue(pop from the queue).  For abort flow we want only one thread to acknowledge or work on the list at a time. Note we dequeue the list of delegate tasks and work on them one by one.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43033)* status: 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 1697 at r3](https://reviewable.io/reviews/harness/harness-core/43033#-NMcgb5S80f9VDoH9GXm:-NN7nPlfCdTrtgLrCw6Q:b-svxcxw) ([raw file](https://github.com/harness/harness-core/blob/ff731ac8607305614ee3516781c6c70f48ae2385/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L1697)):*
> eady migrated to V2 flow so not making the change on V1. Queueing will only be enabled for CI customers for some time.

**Pull request closed without merging**
