### PR TITLE
fix:[PL-30319]: Add maintenance flag check

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- We are not verifying inside the CG redis consumer when entering maintenance mode, which could consume a new message and leave it in an unexpected state during a shutdown.

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41577)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41577)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41577)* status: :shipit: complete! ✓

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41577)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/io/harness/queue/consumers/AbstractBaseConsumerCg.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/41577#-NJKb0hMAtTDoOF_MmF9:-NJKb0hMAtTDoOF_MmFA:bazcjwz) ([raw file](https://github.com/harness/harness-core/blob/1d1795e32bc985658ee1d17ac2e448e113cca478/400-rest/src/main/java/io/harness/queue/consumers/AbstractBaseConsumerCg.java#L63)):*
> ```Java
>         }
>         if (MaintenanceController.getMaintenanceFlag()) {
>           log.info("We are under maintenance, will try again after {} seconds", MAINTENANCE_INTERVAL_SECONDS);
> ```

Here we are saying we will retry after 3 seconds. Then we are sleeping for 10 seconds.

I think we don't need MAINTENANCE_INTERVAL_SECONDS

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41577)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41577)* status: :shipit: complete! ✓

**Pull request merged**
