### PR TITLE
fix: [pl-28400]: Fixing meddled up quartz jobs

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38523)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38523)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/CorrectingQuartzTriggerFrequency.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/38523#-NDwjQeu82E8coMz1TVx:-NDwjQeu82E8coMz1TVy:bl251h5) ([raw file](https://github.com/harness/harness-core/blob/dcf09e16f765bb29fe126d20e1b45cdfd11e92f3/390-db-migration/src/main/java/io/harness/migrations/all/CorrectingQuartzTriggerFrequency.java#L72)):*
> ```Java
>         // reschedule the quartz job
>         if (previousFireTime != null && nextFireTime != null
>             && (((nextFireTime.getTime() - previousFireTime.getTime()) - repeatInterval > THRESHOLD_DELAY)
> ```

do we need threshold delay?
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/CorrectingQuartzTriggerFrequency.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/38523#-NDwiu7DBCcpSdLR8gEz:-NDwiu7DBCcpSdLR8gF-:b-3lz8og) ([raw file](https://github.com/harness/harness-core/blob/dcf09e16f765bb29fe126d20e1b45cdfd11e92f3/390-db-migration/src/main/java/io/harness/migrations/all/CorrectingQuartzTriggerFrequency.java#L97)):*
> ```Java
>           sleep(Duration.ofMillis(200));
>           bulkOperation = collection.initializeUnorderedBulkOperation();
>           dataRecords = collection.find(matchCondition, projection).limit(1000);
> ```

there is no sort order specified. how will we ensure duplicate records are not fetched in each iteration
___
*[`400-rest/src/main/java/software/wings/scheduler/LimitVicinityCheckerJob.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/38523#-NDwin0F69OJiNvYysHK:-NDwin0F69OJiNvYysHL:bc9mwpj) ([raw file](https://github.com/harness/harness-core/blob/dcf09e16f765bb29fe126d20e1b45cdfd11e92f3/400-rest/src/main/java/software/wings/scheduler/LimitVicinityCheckerJob.java#L48)):*
> ```Java
>   @Inject private LimitVicinityHandler limitVicinityHandler;
> 
>   public static TriggerBuilder<SimpleTrigger> vicinityTriggerBuilder(String accountId) {
> ```

this should be private. we should expose a public getter method

**Comment by abhinav-harness** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/CorrectingQuartzTriggerFrequency.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/38523#-NE7QJfM2k098a7faygL:-NE7QJfM2k098a7faygM:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/258fe04ae2616d06ca584529faf40e734875c7fe/390-db-migration/src/main/java/io/harness/migrations/all/CorrectingQuartzTriggerFrequency.java#L82)):*
> ```Java
>         // Difference between previousFireTime and nextFireTime should match with interval timing (max allowed
>         // difference is 10s) also Next fireTime should always be in the future, if any of these condition fails, we
>         // reschedule the quartz job
> ```

remove comment

**Review by ankit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38523)* status: 1 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38523)* status: :shipit: complete! ✓

**Pull request merged**
