### PR TITLE
[fix]: [DEL-3546]: move ELK and Logz task out of 400-rest

### PR DESCRIPTION
**Pull request by raghuAtWings**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31574)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
trigger Functional_tests

**Comment by raghuAtWings** [comment]
trigger FunctionalTest1-Functional_tests

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31574)* status: :shipit: complete! ✓

**Review by praveensugavanam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31574)* status: :shipit: complete! ✓

**Pull request merged**
