### PR TITLE
feat: [SRM-11734]: Adding entities for AWS CloudWatch integration

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Describe your changes
Adding backward compatible changes. Adding classes to Kryo
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37218)

### CODE REVIEW

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 34 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37218)* status: 24 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/client/VerificationManagerClient.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/37218#-NBlWSKm4e3MgglOw75R:-NBlWSKm4e3MgglOw75S:b-8j33gk) ([raw file](https://github.com/harness/harness-core/blob/3b25bbb830d40bbe57edf1845db89addef8a956f/300-cv-nextgen/src/main/java/io/harness/cvng/client/VerificationManagerClient.java#L98)):*
> ```Java
>       @Query("accountId") String accountId, @Query("appId") String appId, @Query("serviceId") String serviceId,
>       @Query("environmentId") String environmentId, @Query("startTime") Long startTime, @Query("endTime") Long endTime);
> ```

Keep this outside of the client

**Review by AbhijithHarness — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 10 of 34 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37218)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by AbhijithHarness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37218)* status: :shipit: complete! ✓

**Comment by dhruv-harness** [comment]
trigger codebasehash

**Comment by deepak-harness** [comment]
trigger codebasehash

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37218)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger codebasehash

**Pull request merged**
