### PR TITLE
feat: [PL-26326]: added logic to make git simplification as default experience

### PR DESCRIPTION
**Pull request by mohitg0795**
## Describe your changes
Tested all the scenarios listed in - 
https://harness.atlassian.net/wiki/spaces/~744563195/pages/21144405746/Managing+Git+Simplification+and+Old+Git+Sync+experience+with+FFs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35791)

### CODE REVIEW

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35791)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by adivishy1 — DISMISSED** [review]

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35791)

**Comment by bhavya181** [comment]
trigger ti0, ti4

**Comment by bhavya181** [comment]
trigger ti2, ti4

**Review by adivishy1 — DISMISSED** [review]

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/35791#-N8btuGM-XqD37JXa0Yy:-N8btuGN1lrPU_Q4H8o4:b-2scyy6) ([raw file](https://github.com/harness/harness-core/blob/bffa6c31b03305210ee7fe8d4ddbf234001d5e6a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/GitSyncSettingsServiceImpl.java#L138)):*
> ```Java
>     Optional<GitSyncSettingsDTO> optionalGitSyncSettingsDTO = get(accountIdentifier, orgIdentifier, projectIdentifier);
>     GitSyncSettingsDTO gitSyncSettings = optionalGitSyncSettingsDTO.get();
>     if (optionalGitSyncSettingsDTO.isPresent() && !gitSyncSettings.isGitSimplificationEnabled()) {
> ```

A better way would be to first check if optionalVariable.isPresent() and then inside it fetch the value via .get() and use it in another if statement. It just adds more readability. Not a blocking comment.

**Comment by bhavya181** [comment]
trigger feature-build

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java` line 211 at r6](https://reviewable.io/reviews/harness/harness-core/35791#-N98PCIQ8xTPg994dnTw:-N98PCIQ8xTPg994dnTx:b-o7i60q) ([raw file](https://github.com/harness/harness-core/blob/ff372ce251be35f0c36e25d358673bbd4ec6eed6/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L211)):*
> ```Java
>     // before saving the git config, check if branch exists
>     // otherwise we end-up saving invalid git configs
>     if (!canEnableOldGitSync(ygs.getAccountIdentifier())) {
> ```

Just wondering what if we check isGitSimplificationEnabled() here? If yes, then we throw exception. If not, then we know that we can go ahead and create yaml git config.
I guess isGitSimplificationEnabled() internally must be doing much more comprehensive checks around the same thing.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 6 of 15 files at r3, 7 of 8 files at r4, 2 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35791)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 6 of 15 files at r3, 7 of 8 files at r4, 2 of 3 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35791)* status: :shipit: complete! ✓

**Pull request merged**
