### PR TITLE
fix: [CDS-44619]: changes for supporting helm sub-charts

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes
These changes are to support helm sub-charts feature. Going forward, we will have an optional field in helm chart manifests called subChartName which can be configured to deploy only a particular sub-chart. 

Since sub-charts generally have dependencies on a shared library, we call `helm template` along with `--dependency-update` feature flag. To ensure this does not break any existing scenarios, we are putting this feature behind an FF. 

Further details, tech spec etc can be found here: https://harness.atlassian.net/browse/CDS-44619

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)

### CODE REVIEW

**Review by GoelPratyush99 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJPHW2T8KGhmGF8yr:-NMXJPHW2T8KGhmGF8ys:bz380i1) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L503)):*
> ```Java
>       String subChartName = getParameterFieldValue(manifestOutcome.getSubChartName());
>       if (isNotEmpty(subChartName)) {
>         folderPath = folderPath + "charts/" + subChartName;
> ```

Can we set "charts" as a static final variable.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 986 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJXch5KqBokR9mciw:-NMXJXch5KqBokR9mcix:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L986)):*
> ```Java
>     } else {
>       helmFetchFileConfigList.add(createHelmFetchFileConfig(
>           identifier, manifestType, Arrays.asList("charts/" + subChartName + "/" + VALUES_YAML_KEY), true));
> ```

Same here

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJPHW2T8KGhmGF8yr:-NMYMG4B0_xvusI4J8s1:b1uzyfm) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L503)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Can we set "charts" as a static final variable.
</blockquote></details>

Let handle the case when folderPath doesn't end with /



_Code quote:_
```Java
folderPath
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 986 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJXch5KqBokR9mciw:-NMYN4Dn9fL0u7taO5n0:beba613) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L986)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Let's handle the case when subChartName can have prefix and suffix /
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 794 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMYNV7Q8OZWLaSzvq7n:-NMYNV7Q8OZWLaSzvq7o:b-efkmd0) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L794)):*
> ```Java
>       if (isNotEmpty(helmChartManifest.getSubChartName())) {
>         manifestFilesDirectory =
>             Paths.get(manifestFilesDirectory, "charts", helmChartManifest.getSubChartName()).toString();
> ```

let's make charts const
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 1051 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMYRyxE0QYxnyIJJKOy:-NMYRyxG7minK21T5Nuw:bxl705a) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L1051)):*
> ```Java
>         HelmCommandDataMapperNG.getHelmCmdDataNG(commandRequest), chartLocation, namespace, valueOverrides, true);
> 
>     int index = helmTaskHelperBase.checkForDependencyUpdateFlag(
> ```

Let's have this behind FF
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3040 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMYTBWS7G1ZqlXTrgXP:-NMYTBWU32kFDoso8Rvl:b-neyxhe) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3040)):*
> ```Java
>     }
>     return isNotEmpty(helmChartManifest.getSubChartName())
>         ? Paths.get(baseManifestDirectory, "charts", helmChartManifest.getSubChartName()).toString()
> ```

Let's wrap this to a different method where you will get using this method manifestDir without subchart and then append subchart if it is present

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 9 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 503 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJPHW2T8KGhmGF8yr:-NMYigLG-D-36iRgMm1Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L503)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let handle the case when folderPath doesn't end with /
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 986 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJXch5KqBokR9mciw:-NMYjMznBNbPt_qGb6cw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L986)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's handle the case when subChartName can have prefix and suffix /
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 794 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMYNV7Q8OZWLaSzvq7n:-NMYjrtS6fL_siIqKTDq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L794)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's make charts const
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java` line 1051 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMYRyxE0QYxnyIJJKOy:-NMbRfzc8a5FOlgsYykw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmDeployServiceImplNG.java#L1051)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's have this behind FF
</blockquote></details>

Done.



_Code quote:_
```Java
checkForDependencyUpdateFlag
```
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java` line 3040 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMYTBWS7G1ZqlXTrgXP:-NMYoCVW43sU16RiYvZj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java#L3040)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's wrap this to a different method where you will get using this method manifestDir without subchart and then append subchart if it is present
</blockquote></details>

Done.

**Review by GoelPratyush99 — COMMENTED** [review]
> Reviewed 6 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 9 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 505 at r4](https://reviewable.io/reviews/harness/harness-core/42746#-NMbSyTYDPF6xOagJ-m5:-NMbSyTYDPF6xOagJ-m6:b-28j62i) ([raw file](https://github.com/harness/harness-core/blob/2186243f7ba71f56555507826dc61917ce78de15/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L505)):*
> ```Java
>       String subChartName = getParameterFieldValue(manifestOutcome.getSubChartName());
>       if (isNotEmpty(subChartName)) {
>         folderPath = folderPath + SUB_CHARTS_FOLDER + subChartName;
> ```

Should we handle the case when user provides subChartName as "/chart_name"
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 992 at r4](https://reviewable.io/reviews/harness/harness-core/42746#-NMbT6zC6ATT-WhUV7UD:-NMbT6zC6ATT-WhUV7UE:b-28j62i) ([raw file](https://github.com/harness/harness-core/blob/2186243f7ba71f56555507826dc61917ce78de15/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L992)):*
> ```Java
>       subChartName = ManifestHelper.normalizeFolderPath(subChartName);
>       helmFetchFileConfigList.add(createHelmFetchFileConfig(
>           identifier, manifestType, Arrays.asList(SUB_CHARTS_FOLDER + subChartName + VALUES_YAML_KEY), true));
> ```

Should we handle the case when user provides subChartName as "/chart_name"

**Review by GoelPratyush99 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 9 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r3, 2 of 3 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 986 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJXch5KqBokR9mciw:-NMcXUT33F71g_Dp2Wky:b-kiwceq) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L986)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about prefix? We can have a different method in ng-manager module only
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 596 at r5](https://reviewable.io/reviews/harness/harness-core/42746#-NMcXnTjD2gT3StCRsjm:-NMcXnTjD2gT3StCRsjn:bj2cuk4) ([raw file](https://github.com/harness/harness-core/blob/db3c8404e731042f4ffa43455cb3255db10a936c/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L596)):*
> ```Java
>   SPG_SIDENAV_COLLAPSE("FF for enabling collapse and expand of side nav", HarnessTeam.SPG),
>   PL_REMOVE_USER_VIEWER_ROLE_ASSIGNMENTS("Enable removal of user level viewer role assignments", HarnessTeam.PL),
>   NG_CDS_HELM_SUB_CHARTS("Support for helm sub charts", HarnessTeam.CDP);
> ```

Please confirm that it was approved by rohan

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 986 at r2](https://reviewable.io/reviews/harness/harness-core/42746#-NMXJXch5KqBokR9mciw:-NMcem0n-ZIq2rOo6BPV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84407b574b0396a214d616a2d194077f73d23f68/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L986)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What about prefix? We can have a different method in ng-manager module only
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 596 at r5](https://reviewable.io/reviews/harness/harness-core/42746#-NMcXnTjD2gT3StCRsjm:-NMcenRv6ceXhBmXoTIo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/db3c8404e731042f4ffa43455cb3255db10a936c/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L596)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please confirm that it was approved by rohan
</blockquote></details>

Done.

**Review by GoelPratyush99 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 7 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 1296 at r6](https://reviewable.io/reviews/harness/harness-core/42746#-NMdS_5U8Rgsq5X3z4RS:-NMdS_5U8Rgsq5X3z4RT:b-urv2tq) ([raw file](https://github.com/harness/harness-core/blob/0d6f1b240d1c2d7ed2f9bd92be9feed4990f87f3/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L1296)):*
> ```Java
>     if (lastIndex == -1) {
>       return path + "/";
>     }
> ```

This logic seems broken can we use Paths.get(dir1, charts, subchart, values).toString(). This will take care of forward slash "/" in prefix and suffix.



_Code quote:_
```Java
    lastIndex = path.lastIndexOf('/');
    if (lastIndex == -1) {
      return path + "/";
    }
```

**Review by abosii-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 7 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 9 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 1296 at r6](https://reviewable.io/reviews/harness/harness-core/42746#-NMdS_5U8Rgsq5X3z4RS:-NN0jfVDEU4o4feMW_lV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0d6f1b240d1c2d7ed2f9bd92be9feed4990f87f3/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L1296)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

This logic seems broken can we use Paths.get(dir1, charts, subchart, values).toString(). This will take care of forward slash "/" in prefix and suffix.
</blockquote></details>

Done.

**Review by abosii-harness — COMMENTED** [review]
> Reviewed 2 of 5 files at r7, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 9 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 4 of 7 files at r5, 2 of 5 files at r7, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42746)* status: :shipit: complete! ✓

**Pull request merged**
