### PR TITLE
[fix]: [PLG-2042]: adding migration for all accounts in 787 release and add new FF PLG_ENABLE_CROSS_GENERATION_ACCESS

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
adding migration for all accounts in 787 release and add new FF PLG_ENABLE_CROSS_GENERATION_ACCESS

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)

### CODE REVIEW

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/44942#-NQ6xZpT1CbivgNaA8uU:-NQ6xZpT1CbivgNaA8uV:b-gqzcl8) ([raw file](https://github.com/harness/harness-core/blob/44226fdfff986b81f2bd6773ba7f4c301bc12ddc/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L39)):*
> ```Java
>                                        .field(Account.AccountKeys.isCrossGenerationAccessEnabled)
>                                        .doesNotExist();
> ```

For monitoring purposes, can we add a total count of the accounts before beginning the migration ?
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/44942#-NQ6xuM15hVZ5jgcTA8W:-NQ6xuM15hVZ5jgcTA8X:b-93q1un) ([raw file](https://github.com/harness/harness-core/blob/44226fdfff986b81f2bd6773ba7f4c301bc12ddc/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L59)):*
> ```Java
>             }
>           }
>           wingsPersistence.update(account, updateOperations);
> ```

we can add a running counter here to keep a track of how many accounts got migrated. This will again help in monitoring purposes just incase something gets missed.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/44942#-NQ6xZpT1CbivgNaA8uU:-NQ7ItIB1Df7Pj1Hjrlj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44226fdfff986b81f2bd6773ba7f4c301bc12ddc/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L39)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

For monitoring purposes, can we add a total count of the accounts before beginning the migration ?
</blockquote></details>

Done.
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 59 at r1](https://reviewable.io/reviews/harness/harness-core/44942#-NQ6xuM15hVZ5jgcTA8W:-NQ7Iv5u47NNKiwvU0GL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/44226fdfff986b81f2bd6773ba7f4c301bc12ddc/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L59)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

we can add a running counter here to keep a track of how many accounts got migrated. This will again help in monitoring purposes just incase something gets missed. 
</blockquote></details>

Done.

**Review by neelam-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/44942#-NQ6xZpT1CbivgNaA8uU:-NQ7PVhcBEhrnpIX4neA:b-bnacz0) ([raw file](https://github.com/harness/harness-core/blob/44226fdfff986b81f2bd6773ba7f4c301bc12ddc/390-db-migration/src/main/java/io/harness/migrations/all/ForAllAccountsAddIsCrossGenerationAccessEnabledMigration.java#L39)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for making the changes, it will definitely help us with tracking down the accounts that failed in the migration :)

**Review by neelam-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review.

**Review by neelam-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review.

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: :shipit: complete! ✓

**Comment by kapil-harness** [comment]
trigger checkstylecodeformat

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by AnshuH** [comment]
trigger checkstylecodeformat

**Review by AnshuH — APPROVED** [review]

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942#-:-NQ8rkQW9iNMP6WlfVu9:bnfp4nl)* status: 1 file(s) to review.

**Review by AnshuH — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: 1 file(s) to review.

**Review by AnshuH — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44942)* status: :shipit: complete! ✓

**Review by pranil-harness — APPROVED** [review]

**Pull request merged**
