### PR TITLE
feat: [PL-30459]: reduce the object size loaded by percentile method

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
This method first loads a list of objects and that list is occupying large space
Changed it to aggregation to get only one object that needs to be returned

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41748)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748)* status: 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/41748#-NJf9vii7HLKC9oR-IpZ:-NJf9vij5T3OIrtKRiqm:b-1r855p) ([raw file](https://github.com/harness/harness-core/blob/cb23dda41c5872dbe47fbd32a6a374cfe580aafb/400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java#L225)):*
> ```Java
>                 .build())
>         .forEachRemaining(instanceStatsSnapshot -> count.add((double) instanceStatsSnapshot.getTotal()));
>     return count.get(0);
> ```

What if p is 100?
Although I don't think there is a use case to get the 100th percentile. It's mostly the 95th percentile.
But I see one call where p comes from a QueryParam. Could you check once?



_Code quote:_
```Java
count.get(0)
```

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java` line 225 at r1](https://reviewable.io/reviews/harness/harness-core/41748#-NJf9vii7HLKC9oR-IpZ:-NJkAd8JACGO2Op2E00d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cb23dda41c5872dbe47fbd32a6a374cfe580aafb/400-rest/src/main/java/software/wings/service/impl/instance/stats/InstanceStatServiceImpl.java#L225)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

What if p is 100?
Although I don't think there is a use case to get the 100th percentile. It's mostly the 95th percentile.
But I see one call where p comes from a QueryParam. Could you check once?
</blockquote></details>

Done.

**Review by vikyathharekal — COMMENTED** [review]
Do we have UTs for this? Or have you tested this locally?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748#-:-NJn0fwfErEYljfPMFOE:b-tgzh8y)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by bhavya181** [comment]
> Do we have UTs for this? Or have you tested this locally?
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748#-:-NJn0fwfErEYljfPMFOE:b-tgzh8y)_ status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

@vikyathharekal there was a integration test written on this, but that has been ignored, so, I have tested the changes using that test in local by comparing olad and new code and bot gives same result.

**Review by vikyathharekal — APPROVED** [review]
Looks good to me. @abosii-harness Could you take a look as well?

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748#-:-NJpT40L3mj-5tTlRq6E:b-tixd5r)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748)* status: 1. unresolved discussions.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41748)* status: :shipit: complete! ✓

**Pull request merged**
