### PR TITLE
feat: [CDS-69341]: use harness email when git email is empty

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** Github api /user returns empty email id if user does not have a public email in their github profile.

**Changes:** using api user/emails in case /user returns empty email id

**Testing:** Tested locally that we are saving primary email id of the user even they don't have a public email id.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47825)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`product/ci/scm/git/git.go` line 588 at r1](https://reviewable.io/reviews/harness/harness-core/47825#-NVWBLevCqVPjvLaJu67:-NVWBLevCqVPjvLaJu68:b-v691p4) ([raw file](https://github.com/harness/harness-core/blob/da59e4374d0aec832bacf33304db143a162ab850/product/ci/scm/git/git.go#L588)):*
> ```Go
> 	log.Infow("GetAuthenticatedUser success", "elapsed_time_ms", utils.TimeSince(start))
> 
> 	if response.Email == "" && request.GetProvider().GetBitbucketCloud() != nil || request.GetProvider().GetGithub() != nil {
> ```

isn't this if condition wrong? It will process && first and then ||

**Comment by shalini-agr** [comment]
*[`product/ci/scm/git/git.go` line 588 at r1](https://reviewable.io/reviews/harness/harness-core/47825#-NVWBLevCqVPjvLaJu67:-NVXcG3v72ALPOGF11IW:bq5p4j8) ([raw file](https://github.com/harness/harness-core/blob/da59e4374d0aec832bacf33304db143a162ab850/product/ci/scm/git/git.go#L588)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

isn't this if condition wrong? It will process && first and then ||
</blockquote></details>

yes, fixed now

**Comment by shalini-agr** [comment]
trigger codeformat

**Comment by shalini-agr** [comment]
trigger uts

**Review by senjucanon2 — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47825)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`product/ci/scm/git/git.go` line 588 at r1](https://reviewable.io/reviews/harness/harness-core/47825#-NVWBLevCqVPjvLaJu67:-NVY78Dm2lPeSK3oob7g:bki56s8) ([raw file](https://github.com/harness/harness-core/blob/da59e4374d0aec832bacf33304db143a162ab850/product/ci/scm/git/git.go#L588)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

yes, fixed now
</blockquote></details>

:) any problems using brackets to make it clearer? Now the condition is more complicated.

**Comment by shalini-agr** [comment]
*[`product/ci/scm/git/git.go` line 588 at r1](https://reviewable.io/reviews/harness/harness-core/47825#-NVWBLevCqVPjvLaJu67:-NVYA12e6hTwUhVsnbNS:b-qclcf) ([raw file](https://github.com/harness/harness-core/blob/da59e4374d0aec832bacf33304db143a162ab850/product/ci/scm/git/git.go#L588)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

:) any problems using brackets to make it clearer? Now the condition is more complicated.
</blockquote></details>

no issues in adding quotes, done.

**Comment by shalini-agr** [comment]
trigger codeformat

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47825)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47825)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
