### PR TITLE
feat: [SRM-14136]: [SRM-14137]: created annotation entity, DTO, response, and resource file

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44800)

### CODE REVIEW

**Comment by karansaraswat19** [comment]
trigger ut8, ut9

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44800)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationAccountLevelResource.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/44800#-NQFIWN57plhrJWEUjBE:-NQFIWN57plhrJWEUjBF:byc9foy) ([raw file](https://github.com/harness/harness-core/blob/4c8307cd0faf8c9bdf3ca7ca96cdb44357365ffc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationAccountLevelResource.java#L70)):*
> ```Java
>     })*/
> @OwnedBy(HarnessTeam.CV)
> public class AnnotationAccountLevelResource {
> ```

have a common interface for both resource files, take reference from ChangeEventNgResource



_Code quote:_
```Java
class AnnotationAccountLevelResource
```

**Comment by karansaraswat19** [comment]
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationDTO.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/44800#-NPvpP-GCYdvQXy1AQ4Q:-NQFRtV33k3IpNFOteCp:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5f3a5e62638c55d26b622899a43c6134c837f19e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationDTO.java#L35)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

This can be null for account Level SLO, same with project
</blockquote></details>

done

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44800)* status: 5 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationDTO.java` line 34 at r3](https://reviewable.io/reviews/harness/harness-core/44800#-NPvpqLwA-rACLdv_G66:-NQFRxh67hoWlWW1B0kE:bjwwx80) ([raw file](https://github.com/harness/harness-core/blob/5f3a5e62638c55d26b622899a43c6134c837f19e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationDTO.java#L34)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

We will need account Id as well, Because this is  what FE will send us, for us to create the Annotation we need to know which account
</blockquote></details>

we take accountId from pathParams, right? I checked two-three more DTOs, they didn't have accountId there as well
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationDTO.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/44800#-NPvpZtr2hWVKz1Jy3gw:-NQFSEhu7dE203Pp-wzz:b-2y8wy9) ([raw file](https://github.com/harness/harness-core/blob/5f3a5e62638c55d26b622899a43c6134c837f19e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/AnnotationDTO.java#L38)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Is this 1000 words or 1000 characters? give min as 1 as well
</blockquote></details>

characters
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/Annotation.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/44800#-NPvrzmr1C4yAIqJCkN1:-NQFSJbfBb6ey1Vz_lNJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f3a5e62638c55d26b622899a43c6134c837f19e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/Annotation.java#L55)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

min=1
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/Annotation.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/44800#-NPvrT0n4HfeGIYxufTH:-NQFSK_RBbsGqW0U7sZ-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f3a5e62638c55d26b622899a43c6134c837f19e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/Annotation.java#L58)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Let's have lastUpdatedBy field as well
Because currently we don't have any restriction that the user creating the annotation should only update it. Other user will update it, and it will still show that this user created this. Let's have this field atleast, we will see in future if we want to use it.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationProjectLevelResource.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/44800#-NPvs7Vi-EliuB7PGyBE:-NQFSO8pCJLMLRWSWQwU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f3a5e62638c55d26b622899a43c6134c837f19e/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationProjectLevelResource.java#L74)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

Can you add for all the APIs
</blockquote></details>

Done.

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 6 files at r4, 1 of 2 files at r5, 2 of 5 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44800)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationResource.java` line 46 at r8](https://reviewable.io/reviews/harness/harness-core/44800#-NQO348o9cmF6WolDsSH:-NQO348o9cmF6WolDsSI:besgj0p) ([raw file](https://github.com/harness/harness-core/blob/e33499c7d3087a586a13de087f95d7a528654c8d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationResource.java#L46)):*
> ```Java
>   @NextGenManagerAuth
>   @ExceptionMetered
>   RestResponse<AnnotationResponse> saveAnnotation(
> ```

add path



_Code quote:_
```Java
RestResponse<AnnotationResponse> saveAnnotation
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationResource.java` line 55 at r8](https://reviewable.io/reviews/harness/harness-core/44800#-NQO2gw6-IPrBIEp8BUM:-NQO2gw6-IPrBIEp8BUN:bbqmxo2) ([raw file](https://github.com/harness/harness-core/blob/e33499c7d3087a586a13de087f95d7a528654c8d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationResource.java#L55)):*
> ```Java
>   @ExceptionMetered
>   @Path(RESOURCE_IDENTIFIER_PATH)
>   RestResponse<AnnotationResponse> updateAnnotationMessage(
> ```

nit: updateAnnotation



_Code quote:_
```Java
updateAnnotationMessage
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationResource.java` line 63 at r8](https://reviewable.io/reviews/harness/harness-core/44800#-NQO2d9Z-90xgW3SG58_:-NQO2d9Z-90xgW3SG58a:b7tfln8) ([raw file](https://github.com/harness/harness-core/blob/e33499c7d3087a586a13de087f95d7a528654c8d/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/resources/AnnotationResource.java#L63)):*
> ```Java
>   @ExceptionMetered
>   @Path(RESOURCE_IDENTIFIER_PATH)
>   RestResponse<Boolean> deleteDowntimeData(@Valid @BeanParam ResourcePathParams resourcePathParams);
> ```

nit: deleteAnnotation



_Code quote:_
```Java
deleteDowntimeData
```

**Review by Varsha-lalwani — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44800#-:-NQOYfvS1esq7Nyy1wsW:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 6 files at r4, 2 of 2 files at r5, 2 of 5 files at r6, 3 of 3 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44800)* status: :shipit: complete! ✓

**Pull request merged**
