### PR TITLE
fix: [CDS-38675]: Delete the newly created PCF app if PCF setup failed

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
JIRA - https://harness.atlassian.net/browse/CDS-38675
Deleting the newly created app(non versioning) in PCF Setup to avoid failures while renaming the old apps back to there original names

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34396)

### CODE REVIEW

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34396)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/pcf/pcftaskhandler/PcfSetupCommandTaskHandler.java` line 349 at r2](https://reviewable.io/reviews/harness/harness-core/34396#-N4g8nPz0xhwEbCVXCAD:-N4g8nPz0xhwEbCVXCAE:b-djuro0) ([raw file](https://github.com/harness/harness-core/blob/3c77ece3f1d52c92b1308395a56b6473eebc0876/930-delegate-tasks/src/main/java/software/wings/delegatetasks/pcf/pcftaskhandler/PcfSetupCommandTaskHandler.java#L349)):*
> ```Java
>         if (newReleaseName != null) {
>           pcfDeploymentManager.deleteNewApplication(cfRequestConfig, releaseNamePrefix, newReleaseName);
>         }
> ```

use the existing method to delete the new application - pcfDeploymentManager.deleteApplication(cfRequestConfig);

First call getPreviousReleases () ... from that list if any app name is equal to newReleaseName then only delete. 

It could be possible the value of newReleaseName is not null, but the app may not have been created yet. The failure could have happen between newReleaseName initialization and creation of new app
___
*[`960-api-services/src/main/java/io/harness/pcf/CfDeploymentManager.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/34396#-N4g9DonC4UkTMwjZBWF:-N4g9DonC4UkTMwjZBWG:b-9dttjp) ([raw file](https://github.com/harness/harness-core/blob/3c77ece3f1d52c92b1308395a56b6473eebc0876/960-api-services/src/main/java/io/harness/pcf/CfDeploymentManager.java#L40)):*
> ```Java
>   void deleteNewApplication(CfRequestConfig cfRequestConfig, String releaseNamePrefix, String newReleaseName)
>       throws PivotalClientApiException;
> ```

remove this

**Comment by abhinav-harness** [comment]
approving as anil approved

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34396)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34396#-:-N4k5xSI2GTb1xwFwXDd:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34396#-:-N4kPaIZAhhcJ-Kbt-VT:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34396)* status: :shipit: complete! ✓

**Pull request merged**
