### PR TITLE
feat: [PIE-2597]: Adding pipeline service secondary read for PmsExecutionSummaryRepositoryCustomImpl count read

### PR DESCRIPTION
**Pull request by archit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30611)

### CODE REVIEW

**Review by naidu-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30611)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java, line 77 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWeKmzDgRpCYzxqeQe:-MvWeKmzDgRpCYzxqeQf:bjox00d) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L77)):*
> ```Java
>       Query query = new Query(criteria).with(pageable);
>       long count = pmsExecutionSummarySecondary.findCount(query);
>       List<PipelineExecutionSummaryEntity> projects = mongoTemplate.find(query, PipelineExecutionSummaryEntity.class);
> ```

nit: replace projects with pipelineExecutions. probably copy-paste mistake

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30611)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummarySecondaryImpl.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWZUkC3wkQoZsB_4vR:-MvWZUkC3wkQoZsB_4vS:bdcw8f6) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummarySecondaryImpl.java#L25)):*
> ```Java
> @OwnedBy(PIPELINE)
> @Singleton
> public class PmsExecutionSummarySecondaryImpl {
> ```

name this better
___
*[860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWZb8MCwUj2w0nL9dX:-MvWZb8MCwUj2w0nL9dY:b-7ropln) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L48)):*
> ```Java
> public class PmsExecutionSummaryRepositoryCustomImpl implements PmsExecutionSummaryRepositoryCustom {
>   private final MongoTemplate mongoTemplate;
>   private final PmsExecutionSummarySecondaryImpl pmsExecutionSummarySecondary;
> ```

ditto
___
*[860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWZc7dADCI7mE8NaZQ:-MvWZc7dADCI7mE8NaZR:bbhpz8l) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L76)):*
> ```Java
>     try {
>       Query query = new Query(criteria).with(pageable);
>       long count = pmsExecutionSummarySecondary.findCount(query);
> ```

add a comment here to not add this in lambda

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30611)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWZb8MCwUj2w0nL9dX:-MvX6WBL7dP20uGYOaaT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L48)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java, line 76 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWZc7dADCI7mE8NaZQ:-MvX6Wj_EDa4biefVMQg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L76)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

add a comment here to not add this in lambda
</blockquote></details>

Done.
___
*[860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummarySecondaryImpl.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30611#-MvWZUkC3wkQoZsB_4vR:-MvX6VVW2ePhklW8vu6v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/969c3369b17fac978e7f0b162aaedc6d4a7a7b09/860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummarySecondaryImpl.java#L25)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

name this better
</blockquote></details>

Done.

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30611)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30611)* status: :shipit: complete! ✓

**Pull request merged**
