### PR TITLE
[fix]: [PL-30200]: Refactors delegate response flow to use kryo serializer with reference false

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes

Kryo using CompatibleFieldSerializer along with references set to true does not behave correctly. There are some backward compatibility issues faced for below scenarios

- A new field is introduced or exiting field is updated which refers another field.
- New field is not present in Manager/Delegate code.
- During deserialisation you will get incorrect data or IndexOutOfBound in some deep nested object cases.

Delegate to manager communication already started using kryo with reference false.

We also upgraded all microservices to conditionally handle delegate response either usingKryoWithReference OR usingKryoWithoutReference. 

This PR is to update delegate responses to start using kryo with reference false. 

Test case tested locally

- CG SMTP setup and Connectivity Test working fine
- CG workflow expiry working fine
- CG workflow abort working fine
- Vault secret manager creation is working fine in CG
- Store secrets in hashicorp vault and reading it from workflow shell script step is working fine in CG
- AWS KMS secret manager creation is working fine in CG
- Store secrets in aws kms and reading it from workflow shell script step is working fine in CG
- NG SMTP setup and Connectivity Test working fine
- NG pipeline expiry working fine
- NG pipeline abort working fine
- Vault secret manager creation is working fine in NG
- Store secrets in hashicorp vault and reading it from pipeline shell script step is working fine in NG
- AWS KMS secret manager creation is working fine in NG
- Store secrets in aws kms and reading it from pipeline shell script step is working fine in NG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41192)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/41192#-NLwFSkm6j-d8cPOp1ho:-NLwFSkm6j-d8cPOp1hp:b-70276m) ([raw file](https://github.com/harness/harness-core/blob/efc359e4a9ada870bd3a46c366e9e544c6079c05/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L192)):*
> ```Java
>     }
> 
>     delegateMetricsService.recordDelegateTaskResponseMetrics(delegateTask, response, DELEGATE_TASK_RESPONSE);
> ```

why remove this?

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/41192#-NLwFSkm6j-d8cPOp1ho:-NLwFWok9PJ1wm2aN3Yw:bt0gvk2) ([raw file](https://github.com/harness/harness-core/blob/efc359e4a9ada870bd3a46c366e9e544c6079c05/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L192)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why remove this?
</blockquote></details>

metrics

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/41192#-NLwFSkm6j-d8cPOp1ho:-NLwFr3X0boFfG4C5DpK:b4e3w1k) ([raw file](https://github.com/harness/harness-core/blob/efc359e4a9ada870bd3a46c366e9e544c6079c05/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L192)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

metrics 
</blockquote></details>

nvm its' in v2 flow

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 17 files at r1, 5 of 17 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41192)* status: 22 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/41192#-NLyH3A10wbCkvrrz_KW:-NLyH3A581-bOo1NvYnh:bqai19r) ([raw file](https://github.com/harness/harness-core/blob/efc359e4a9ada870bd3a46c366e9e544c6079c05/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L192)):*
> ```Java
>     }
> 
>     delegateMetricsService.recordDelegateTaskResponseMetrics(delegateTask, response, DELEGATE_TASK_RESPONSE);
> ```

where is this metric being reported now?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 5 of 17 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41192)* status: 1 of 2 approvals obtained. Waiting on team(s): sto.

**Comment by ashishsanodia-harness** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java` line 192 at r3](https://reviewable.io/reviews/harness/harness-core/41192#-NLyH3A10wbCkvrrz_KW:-NLyL3go3hjzyccCtypz:b-v9gn8r) ([raw file](https://github.com/harness/harness-core/blob/efc359e4a9ada870bd3a46c366e9e544c6079c05/420-delegate-service/src/main/java/io/harness/service/impl/DelegateTaskServiceImpl.java#L192)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

where is this metric being reported now?
</blockquote></details>

Looks like these are opencensus metrics and it is there for quite some time.

Link to these metrics:
https://console.cloud.google.com/monitoring/metrics-explorer?referrer=search&organizationId=252201914815&project=qa-setup&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22custom.googleapis.com%2Fopencensus%2Fdelegate_response%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_RATE%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22alignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22alignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%5D%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221h%22%7D%7D

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 17 files at r1, 5 of 17 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41192)* status: 1. unresolved discussions. Waiting on team(s): sto.

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41192)* status: Waiting on team(s): sto.

**Pull request merged**
