### PR TITLE
[techdebt]: [PIE-6044]: Add restriction on concurrent executions runn…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…ing in account based on edition

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39358)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39358)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java` line 246 at r1](https://reviewable.io/reviews/harness/harness-core/39358#-NFTilaAByoU0vb3SJ4l:-NFTilaAByoU0vb3SJ4m:b9mmpx7) ([raw file](https://github.com/harness/harness-core/blob/ecaf6e8a5b27a744e3d67087d08dad24e8692c29/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java#L246)):*
> ```Java
>                             .and(PlanExecutionKeys.metadata + ".pipelineIdentifier")
>                             .is(pipelineIdentifier)
>                             .and(PlanExecutionKeys.status)
> ```

Index for this is created in another pr?



_Code quote:_
```Java
    Criteria criteria = new Criteria()
                            .and(PlanExecutionKeys.setupAbstractions + "." + SetupAbstractionKeys.accountId)
                            .is(accountId)
                            .and(PlanExecutionKeys.setupAbstractions + "." + SetupAbstractionKeys.orgIdentifier)
                            .is(orgId)
                            .and(PlanExecutionKeys.setupAbstractions + "." + SetupAbstractionKeys.projectIdentifier)
                            .is(projectId)
                            .and(PlanExecutionKeys.metadata + ".pipelineIdentifier")
                            .is(pipelineIdentifier)
                            .and(PlanExecutionKeys.status)
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionResumeCallback.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/39358#-NFTiREa7qsV1PlqHjEU:-NFTiREa7qsV1PlqHjEV:b-upgsrn) ([raw file](https://github.com/harness/harness-core/blob/ecaf6e8a5b27a744e3d67087d08dad24e8692c29/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionResumeCallback.java#L56)):*
> ```Java
>           accountIdIdentifier, orgIdentifier, projectIdentifier, pipelineIdentifier);
>       if (planExecution != null) {
>         planExecutionService.updateStatus(planExecution.getUuid(), Status.RUNNING);
> ```

sumary is also updated as part of this?

**Review by hextechpal — DISMISSED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39358)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java` line 246 at r1](https://reviewable.io/reviews/harness/harness-core/39358#-NFTilaAByoU0vb3SJ4l:-NFTkgRj1YtcNhQSSfxX:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/ecaf6e8a5b27a744e3d67087d08dad24e8692c29/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java#L246)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Index for this is created in another pr?
</blockquote></details>

Yes

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionResumeCallback.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/39358#-NFTiREa7qsV1PlqHjEU:-NFTkhRt5HbsbDDV9FC5:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/ecaf6e8a5b27a744e3d67087d08dad24e8692c29/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionResumeCallback.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

sumary is also updated as part of this?
</blockquote></details>

Yes

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39358)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by naidu-harness** [comment]
trigger ti0

**Pull request merged**
