### PR TITLE
[feat]: [PL-43831]: adding uniqueId, parentUniqueId for connector create/update scenaiors

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes

Adding support for `uniqueId`, `parentUniqueId` during Connector CREATE, UPDATE cases.

Testing done:
- CREATE connector at Project, Account level and uniqueId and parentUniqueId correctly created
- UPDATE connects and the ids are not changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57212)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57212)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 556 at r1](https://reviewable.io/reviews/harness/harness-core/57212#-NnCjvoV7Lmlgl4UpKNK:-NnCjvoV7Lmlgl4UpKNL:b-3700nz) ([raw file](https://github.com/harness/harness-core/blob/f4789a80a31a85b6dce6a296cb84defd6a5d8b8b/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L556)):*
> ```Java
>   }
> 
>   private ConnectorResponseDTO createInternal(
> ```

Pls make sure we have covered all update and create connector paths
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 576 at r1](https://reviewable.io/reviews/harness/harness-core/57212#-NnCkZTF3lU4WDbjNfKQ:-NnCkZTF3lU4WDbjNfKR:b8zjoj1) ([raw file](https://github.com/harness/harness-core/blob/f4789a80a31a85b6dce6a296cb84defd6a5d8b8b/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L576)):*
> ```Java
>     try {
>       Supplier<OutboxEvent> supplier = null;
>       if (isEmpty(connectorInfo.getOrgIdentifier()) && isEmpty(connectorInfo.getProjectIdentifier())) {
> ```

Is tis logic temporary? I am assuming this will go away and we will start using ScopeInfo passed to this method once Connector APIs are migrated. Correct?

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57212#-:-NnCkmtdDu61KIyI0T2j:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 576 at r1](https://reviewable.io/reviews/harness/harness-core/57212#-NnCkZTF3lU4WDbjNfKQ:-NnCmgDO7cSIY3cE5eiH:b5zb9ou) ([raw file](https://github.com/harness/harness-core/blob/f4789a80a31a85b6dce6a296cb84defd6a5d8b8b/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L576)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is tis logic temporary? I am assuming this will go away and we will start using ScopeInfo passed to this method once Connector APIs are migrated. Correct?
</blockquote></details>

Yes, this will go away once we get `ScopeInfo` from context passed from Resource layer, thanks

**Comment by pbarapatre10** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 556 at r1](https://reviewable.io/reviews/harness/harness-core/57212#-NnCjvoV7Lmlgl4UpKNK:-NnCmn9i55e8GtHbDXeD:b-xaxxpa) ([raw file](https://github.com/harness/harness-core/blob/f4789a80a31a85b6dce6a296cb84defd6a5d8b8b/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L556)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Pls make sure we have covered all update and create connector paths
</blockquote></details>

I have tested for normal connector, and secret manager connector. Didn't test for all the different types connector as they are many. Will get help from sanity and from other module team sanity as well, thanks

**Pull request merged**
