### PR TITLE
feat: [CDS-48541]: container stepoutcome

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41659)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41659)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepExecutionResponseHelper.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/41659#-NJPdCDsBl99FLq8X1aD:-NJPdCDsBl99FLq8X1aE:bsfrcok) ([raw file](https://github.com/harness/harness-core/blob/f20df94ae9bbcb271f62b8d0cb59723e276dcb5e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepExecutionResponseHelper.java#L41)):*
> ```Java
> @Slf4j
> @Singleton
> public class ContainerStepExecutionResponseHelper {
> ```

Owner missing

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41659)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepExecutionResponseHelper.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/41659#-NJPdCDsBl99FLq8X1aD:-NJRAfnY-FXIkDQ35Amo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f20df94ae9bbcb271f62b8d0cb59723e276dcb5e/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepExecutionResponseHelper.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Owner missing
</blockquote></details>

Done.

**Comment by abhinav-harness** [comment]
trigger ti1

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41659)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by Y0709 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41659)* status: :shipit: complete! ✓

**Pull request merged**
