### PR TITLE
Feat: [SRM-11997]: Add AbstractSLO and it's simple and composite implementa…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…tion

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37429)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 5 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37429)

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37429)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/AbstractServiceLevelObjective.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/37429#-NBp5xwtBRNUFBqOs5WO:-NBp5xwtBRNUFBqOs5WP:brrobip) ([raw file](https://github.com/harness/harness-core/blob/35906f7a622a8b2e20e7027593ef44b925572bc8/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/AbstractServiceLevelObjective.java#L69)):*
> ```Java
> @EqualsAndHashCode(callSuper = false)
> @StoreIn(DbAliases.CVNG)
> @Entity(value = "newServiceLevelObjectives")
> ```

Lets find a better name for the entity
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/37429#-NBp60Q02lNWPI-Tdet8:-NBp60Q02lNWPI-Tdet9:b9ilbr4) ([raw file](https://github.com/harness/harness-core/blob/35906f7a622a8b2e20e7027593ef44b925572bc8/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java#L28)):*
> ```Java
> 
>   public static class ServiceLevelObjectivesData {
>     AbstractServiceLevelObjective abstractServiceLevelObjective;
> ```

we can directly store the ref(identifier). no need to store the complete object
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SimpleServiceLevelObjective.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/37429#-NBp68AhCfyW_wbYDzMq:-NBp68AiCQucEeIzUzBn:bkd232l) ([raw file](https://github.com/harness/harness-core/blob/35906f7a622a8b2e20e7027593ef44b925572bc8/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SimpleServiceLevelObjective.java#L26)):*
> ```Java
> @EqualsAndHashCode(callSuper = true)
> public class SimpleServiceLevelObjective extends AbstractServiceLevelObjective {
>   String projectIdentifier;
> ```

project identfier can be present for compostie slo as well. should be in abstract class.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SimpleServiceLevelObjective.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/37429#-NBp6DU8-r592ivk2ALB:-NBp6DU8-r592ivk2ALC:b9d0oii) ([raw file](https://github.com/harness/harness-core/blob/35906f7a622a8b2e20e7027593ef44b925572bc8/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/SimpleServiceLevelObjective.java#L30)):*
> ```Java
>   String monitoredServiceIdentifier;
>   List<String> serviceLevelIndicators;
>   ServiceLevelIndicatorType type;
> ```

lets rename this to service level indicator type.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37429)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/AbstractServiceLevelObjective.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/37429#-NBp5xwtBRNUFBqOs5WO:-NBv7UwvDARgr6MWmcZ_:b-ds1tli) ([raw file](https://github.com/harness/harness-core/blob/35906f7a622a8b2e20e7027593ef44b925572bc8/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/AbstractServiceLevelObjective.java#L69)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Lets find a better name for the entity
</blockquote></details>

serviceLevelObjectivesV2
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/37429#-NBvAWNQ4fB-GzRn4r02:-NBvAWNQ4fB-GzRn4r03:b-2qhtva) ([raw file](https://github.com/harness/harness-core/blob/5767671a340d69ce69166c0439cbeca155df0c44/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java#L25)):*
> ref
SLODetails
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/37429#-NBvAbGBBKaqAyFI6PtF:-NBvAbGBBKaqAyFI6PtG:b-z2i732) ([raw file](https://github.com/harness/harness-core/blob/5767671a340d69ce69166c0439cbeca155df0c44/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeServiceLevelObjective.java#L27)):*
> ```Java
>   @Size(max = 20) List<ServiceLevelObjectivesData> serviceLevelObjectivesDataList;
> 
>   public static class ServiceLevelObjectivesData {
> ```

SLODetail

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37429)* status: :shipit: complete! ✓

**Pull request merged**
