### PR TITLE
fix: [DEL-5906]: Ensuring right error msg is displayed if im…

### PR DESCRIPTION
**Pull request by Vbhatia20**
## Describe your changes
GoaL: We want to restrict using an Immutable image with a legacy delegate yaml and as part of this, we want to display the right error message to the user.
This change will only focus on k8 and helm type of delegate
Fixed required condition for the same

Tests executed:

Screenshot 2023-02-03 at 10 13 56 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43451)

### CODE REVIEW

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43451)* status: 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 471 at r2](https://reviewable.io/reviews/harness/harness-core/43451#-NNN9Ry67OtGkqja-PoL:-NNN9Ry67OtGkqja-PoM:bz5s1xz) ([raw file](https://github.com/harness/harness-core/blob/bae8ab8af9ad7ef6b5ea8ca54cdd535c62154321/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L471)):*
> ```Java
>   @SuppressWarnings("PMD")
>   private void checkForImmutbleAndStatefulset() {
>     if (!this.isImmutableDelegate || !KUBERNETES.equals(DELEGATE_TYPE) || !HELM_DELEGATE.equals(DELEGATE_TYPE)) {
> ```

You could only change || to && to make the condition simpler. 



_Suggestion:_
```Java
    if (!this.isImmutableDelegate || !KUBERNETES.equals(DELEGATE_TYPE) && !HELM_DELEGATE.equals(DELEGATE_TYPE)) {
```

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43451)* status: :shipit: complete! ✓

**Pull request merged**
