### PR TITLE
[feat]: [PL-23864]: remove deprecated all resources resource group

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31543)

### CODE REVIEW

**Comment by karansiwach360** [comment]
trigger messagecheck

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31543)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/resources/io/harness/resourcegroup/managed-resourcegroups.yml, line 3 at r2](https://reviewable.io/reviews/harness/harness-core/31543#-MyLmLp7Ax9eqMCyYxgd:-MyLmLp88Ub4lYKGtcsX:b-84py5o) ([raw file](https://github.com/harness/harness-core/blob/98fc345bce99cea07078b0c7f429ee5dbfd99e0f/830-resource-group/src/main/resources/io/harness/resourcegroup/managed-resourcegroups.yml#L3)):*
> ```YAML
> # Any edit in this file should accompany an increment in version.
> name: resourceGroupsConfiguration
> version: 3
> ```

No version update?

**Review by karansiwach360 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31543)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[830-resource-group/src/main/resources/io/harness/resourcegroup/managed-resourcegroups.yml, line 3 at r2](https://reviewable.io/reviews/harness/harness-core/31543#-MyLmLp7Ax9eqMCyYxgd:-MyLnL0g4xj3Wahdes_K:b-ycv0x0) ([raw file](https://github.com/harness/harness-core/blob/98fc345bce99cea07078b0c7f429ee5dbfd99e0f/830-resource-group/src/main/resources/io/harness/resourcegroup/managed-resourcegroups.yml#L3)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

No version update?
</blockquote></details>

Done. Thanks, forgot it.

**Review by reetika04 — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31543)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by reetika04 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31543)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31543)* status: :shipit: complete! ✓

**Pull request merged**
