### PR TITLE
feat: [CVS-9492]: Refactor the DataCollection for Custom Health Mapper

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31471)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31471)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java, line 73 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCTxZZE16GipXKHyBm:-MyCTxZZE16GipXKHyBn:b6tjxxm) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java#L73)):*
> ```Java
>       return false;
>     }
>     return metricInfos.stream().anyMatch(metricInfo -> metricInfo.getSli().isEnabled());
> ```

we can have this logic at a common place?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java, line 98 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCUGyaDRrSav_LOqTY:-MyCUGyaDRrSav_LOqTZ:b53ypnb) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java#L98)):*
> ```Java
> 
>   @Override
>   public void setMetricInfos(List<MetricInfo> i) {
> ```

I think we should add filterMetricInfo with type as input and move the filtering logic in MetricCVConfig. 



_Code quote:_
```Java
setMetricInfos
```
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java, line 42 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCUc409ZBqZJG7pU7s:-MyCUc41AHwuwwXIFKRY:b-rvajw8) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java#L42)):*
> ```Java
> 
>   @Override
>   public boolean isSLIEnabled() {
> ```

this is overridden in LogCVConfig right. Do we need it here?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/jobs/ServiceGuardDataCollectionTaskCreateNextTaskHandler.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCVZCtCANmMC_pa0Dr:-MyCVZCtCANmMC_pa0Ds:bkmyqrq) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/jobs/ServiceGuardDataCollectionTaskCreateNextTaskHandler.java#L30)):*
> ```Java
>     Preconditions.checkArgument(
>         dataCollectionTaskManagementServiceMapBinder.containsKey(DataCollectionTask.Type.SERVICE_GUARD));
>     if (!entity.isLiveMonitoringEnabled()) {
> ```

I think we should add a warning in the execution logs. This logic should still go in ServiceGuardDataCollectionTaskService.



_Code quote:_
```Java
CVConfig entity
```
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/monitoredService/HealthSourceService.java, line 29 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCWBg2AIV5tix4y-G0:-MyCWBg2AIV5tix4y-G1:b-7ilvfu) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/monitoredService/HealthSourceService.java#L29)):*
> ```Java
>       List<String> identifiers);
>   void delete(String accountId, String orgIdentifier, String projectIdentifier,
>       String namenameSpaceIdentifierSpaceIdentifier, List<String> identifiers);
> ```

typo?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/ServiceGuardDataCollectionTaskServiceImpl.java, line 48 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCWMZu9sfNwRDJeMnO:-MyCWMZu9sfNwRDJeMnP:b7wpk49) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/ServiceGuardDataCollectionTaskServiceImpl.java#L48)):*
> ```Java
>   public void handleCreateNextTask(CVConfig cvConfig) {
>     Preconditions.checkState(cvConfig.isEnabled(), "CVConfig should be enabled");
>     Preconditions.checkState(
> ```

I think we should add the condition here with executionLog with a warning.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java, line 687 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCWs5M85xE-hYqkF2N:-MyCWs5M85xE-hYqkF2O:bdzub3l) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/services/impl/VerificationJobInstanceServiceImpl.java#L687)):*
> ```Java
>     List<TimeRange> timeRanges =
>         verificationJob.getDataCollectionTimeRanges(roundDownTo1MinBoundary(verificationJobInstance.getStartTime()));
>     cvConfigs.stream().filter(cvConfig -> cvConfig.isDeploymentVerificationEnabled()).forEach(cvConfig -> {
> ```

should we create the data collection task and let it go to DSL? We need to make sure that we are finishing the VerificationJobInstance with right error message in the execution log.

**Comment by AbhijithHarness** [comment]
trigger ft2

**Comment by AbhijithHarness** [comment]
trigger license

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31471)* status: 15 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java, line 73 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCTxZZE16GipXKHyBm:-MyL4xXG88ICRfCXzvkS:b-7mmp82) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java#L73)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we can have this logic at a common place?
</blockquote></details>

moved
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java, line 98 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCUGyaDRrSav_LOqTY:-MyFkD0NBqW8W1y19YL1:b-ozm512) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/AppDynamicsCVConfig.java#L98)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think we should add filterMetricInfo with type as input and move the filtering logic in MetricCVConfig. 
</blockquote></details>

that cannot be used for sli
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java, line 42 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCUc409ZBqZJG7pU7s:-MyL5KdQ6wkrsB4yuXgf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CustomHealthLogCVConfig.java#L42)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this is overridden in LogCVConfig right. Do we need it here?
</blockquote></details>

Done.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/jobs/ServiceGuardDataCollectionTaskCreateNextTaskHandler.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/31471#-MyCVZCtCANmMC_pa0Dr:-MyL5Mk9BtGX_z9iwCzh:b-azla7y) ([raw file](https://github.com/harness/harness-core/blob/651a49b122e0e44c990ad2a7a7683ac2ea0dc121/300-cv-nextgen/src/main/java/io/harness/cvng/core/jobs/ServiceGuardDataCollectionTaskCreateNextTaskHandler.java#L30)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

I think we should add a warning in the execution logs. This logic should still go in ServiceGuardDataCollectionTaskService.
</blockquote></details>

will create exrec

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31471#-:-MyL69SU-gtS2-btE1xk:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
