### PR TITLE
feat: [CDS-49860]: Added support for TAS manifest overrides

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added support for TAS manifest overrides and fixed a couple of bugs:
1. changing HARNESS__STATUS__IDENTIFIER to INACTIVE
2. fixing inbuilt variables
3. removing instances variable support for TAS
4. added manifest verifications for all 3 manifest types
5. fixed folder issues in path for manifest
6. Added support for Nexus2/GAR artifact

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42082)

### CODE REVIEW

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 22 of 22 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42082#-:-NL6Ii6J8qMfiWIjmdU2:bnfp4nl)* status: 25 file(s) to review. 1 of 2 approvals obtained.

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42082#-:-NL6tvzz6wNNn63akYKK:bnfp4nl)* status: 25 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 22 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42082)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/42082#-NLGg40e75YrC8Hvq9Ky:-NLGg40e75YrC8Hvq9Kz:b-yuyn1j) ([raw file](https://github.com/harness/harness-core/blob/adef9a8cd4f83f60c57c28c8ba435023559bb8b4/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java#L66)):*
> ```Java
>       return instance.getHostName();
>     } else if (INSTANCE_HOST_PROPERTY.equals(instanceProperty)) {
>       return instance.getHost();
> ```

we are removing the PCF functor intentionally right ? This means any user which is using the instance.pcf will not work

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 20 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42082)* status: 1 of 2 approvals obtained.

**Comment by RishabhGupta34** [comment]
*[`120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/42082#-NLGg40e75YrC8Hvq9Ky:-NLGrucM9gqAwzY7WVSi:bfbysij) ([raw file](https://github.com/harness/harness-core/blob/adef9a8cd4f83f60c57c28c8ba435023559bb8b4/120-ng-manager/src/main/java/io/harness/pms/expressions/functors/InstanceFunctor.java#L66)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we are removing the PCF functor intentionally right ? This means any user which is using the instance.pcf will not work 
</blockquote></details>

yeah, but no one was using it until now, as PCF is not yet released to customers in NG.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42082)* status: :shipit: complete! ✓

**Pull request merged**
