### PR TITLE
feat: [SRM-15829]: add auto discovery support to SRM

### PR DESCRIPTION
**Pull request by deepak-harness**
## Describe your changes
Changes are related to auto service dependency creation imported from the service discovery.
Design doc: https://harness.atlassian.net/wiki/spaces/LEARNING/pages/21467169419/Auto+Discovery+in+SRM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54272)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger checkstylecodeformat

**Comment by deepak-harness** [comment]
trigger messagecheck

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger checkstylecodeformat

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger checkstylecodeformat

**Comment by deepak-harness** [comment]
trigger messagecheck

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger messagecheck

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger copyrightcheck

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> Reviewed 3 of 21 files at r1, 10 of 29 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54272)* status: 20 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/autodiscovery/services/impl/AutoDiscoveryServiceImpl.java` line 182 at r4](https://reviewable.io/reviews/harness/harness-core/54272#-NhAznoDEKK844GIQ5vg:-NhAznoDEKK844GIQ5vh:bkyzboz) ([raw file](https://github.com/harness/harness-core/blob/816315d9ae2dafc8e80feeb0218a2d8ac3f4c1b8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/autodiscovery/services/impl/AutoDiscoveryServiceImpl.java#L182)):*
> ```Java
>                 -> ServiceEnvironmentParams.builderWithProjectParams(projectParams)
>                        .serviceIdentifier(
>                            discoveredService.getSpec().getHarnessServiceIdentity().getFullyQualifiedIdentifier())
> ```

These are not marked as NotNull and we have assumed they are notNull. Can you add correct notNull annotations in the entities added in Chaos side.



_Code quote:_
```Java
discoveredService.getSpec().getHarnessServiceIdentity().getFullyQualifiedIdentifier()
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/autodiscovery/services/impl/AutoDiscoveryServiceImpl.java` line 204 at r4](https://reviewable.io/reviews/harness/harness-core/54272#-NhB-1l41suaONvhLo18:-NhB-1l41suaONvhLo19:bdnz8kx) ([raw file](https://github.com/harness/harness-core/blob/816315d9ae2dafc8e80feeb0218a2d8ac3f4c1b8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/autodiscovery/services/impl/AutoDiscoveryServiceImpl.java#L204)):*
> ```Java
>       for (ServiceEnvironmentParams serviceNotPresentInTheSystem : servicesNotPresentInTheSystem) {
>         MonitoredServiceDTO createDefault =
>             monitoredServiceService
> ```

also, can we split this method into smaller functions? this has become huge
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/autodiscovery/services/impl/AutoDiscoveryServiceImpl.java` line 246 at r4](https://reviewable.io/reviews/harness/harness-core/54272#-NhB-MLY42eAGALr2dck:-NhB-MLY42eAGALr2dcl:b-6cz915) ([raw file](https://github.com/harness/harness-core/blob/816315d9ae2dafc8e80feeb0218a2d8ac3f4c1b8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/autodiscovery/services/impl/AutoDiscoveryServiceImpl.java#L246)):*
> ```Java
>   private String getMonitoredServiceIdentifier(String serviceIdentifier, String envIdentifier) {
>     return serviceIdentifier + "_" + envIdentifier;
>   }
> ```

MonitoredService entity has this public method, let's not duplicate this



_Code quote:_
```Java
  private String getMonitoredServiceIdentifier(String serviceIdentifier, String envIdentifier) {
    return serviceIdentifier + "_" + envIdentifier;
  }
```

**Comment by deepak-harness** [comment]
trigger uts

**Comment by deepak-harness** [comment]
trigger uts

**Review by Varsha-lalwani — APPROVED** [review]

**Review by jyotiraval — APPROVED** [review]

**Pull request merged**
