### PR TITLE
[fix]: [CDS-74603]: New error for handling response messages

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Describe your changes

The changes for PipelineRestUtils were done in this PR: https://github.com/harness/harness-core/pull/50602

If we see in the above PR, we made a change to WingsException where we added a new function for response messages. That resulted in the error message count increase in the delegate/manager communication. More details on the thread here
https://harness.slack.com/archives/C0421URA3FF/p1689197801507659

Why it started happening?
- We added a new field and there is a chance that delegate might not have been upgraded with this new method. As a result of which the kryo serialisation was failing for wings exception . Logs for the same: https://cloudlogging.app.goo.gl/oHJTm9s4chZ2fspN9
- Because of the new method added, kryo serialisation was failing.

What is the fix?
- Rather than adding a new method in WingsException, we have created a new interface that will contain the function information. If only, that interface is being used. We will append the response messages.
- We could have used InvalidRequestException and let it implement that interface but it might have caused some other regression as there are many usages of InvalidRequestException. We have created a new exception rather. Since nobody is using that class, we will not be seeing that exception anywhere and we should be good.

it is java serialisation that is failing because of the newly added method in WingsException. InvalidRequestException is not the cause.
RemoteMethodReturnValueData  it seems that in this we are using Java serialisation which uses serialVersionUuid and since in many of the classes that field might not be present so java uses it's own id generated based on fields, after adding the method in WingsException, it changed all those classes and thus their deserialisation was failing.
This issue could have been avoided if we had used serialVersionUuid static field in the class.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50602)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50602)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50602)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/HarnessServiceCallException.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/50602#-N_bMEJU8bx7OGUWF2B5:-N_bMEJU8bx7OGUWF2B6:b-bgqnut) ([raw file](https://github.com/harness/harness-core/blob/16dda137f7e9c1168521f39dc3a38bc7cd5ba2f8/980-commons/src/main/java/io/harness/exception/HarnessServiceCallException.java#L20)):*
> ```Java
> import java.util.List;
> 
> public class HarnessServiceCallException extends WingsException implements WithResponseMessages {
> ```

Shall we rename this to HarnessRemoteServiceException?
___
*[`980-commons/src/main/java/io/harness/exception/WithResponseMessages.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/50602#-N_bMY2w5-6ACIza9ybZ:-N_bMY2w5-6ACIza9yb_:bnlxiqq) ([raw file](https://github.com/harness/harness-core/blob/16dda137f7e9c1168521f39dc3a38bc7cd5ba2f8/980-commons/src/main/java/io/harness/exception/WithResponseMessages.java#L15)):*
> ```Java
> import java.util.List;
> 
> public interface WithResponseMessages {
> ```

HasResponseMessages

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/exception/HarnessServiceCallException.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/50602#-N_bMEJU8bx7OGUWF2B5:-N_bPzHi1QckI1P2MQMY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16dda137f7e9c1168521f39dc3a38bc7cd5ba2f8/980-commons/src/main/java/io/harness/exception/HarnessServiceCallException.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shall we rename this to HarnessRemoteServiceException?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/exception/WithResponseMessages.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/50602#-N_bMY2w5-6ACIza9ybZ:-N_bQ-kW72ggn-4b8HbA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16dda137f7e9c1168521f39dc3a38bc7cd5ba2f8/980-commons/src/main/java/io/harness/exception/WithResponseMessages.java#L15)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

HasResponseMessages
</blockquote></details>

Done.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50602)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50602#-:-N_bRsFNBY0CoFCaHnQA:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50602)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger review

**Pull request merged**
