### PR TITLE
feat: [CDS-39106]: resolve service/env expressions (v1 and v2) for image tag expressions

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. Created List of alias yaml fields in Yaml Expression Evaluator to resolve expressions other than pipeline rooted. Eg. <+service.name>
2. For v2 services (inline serv definition), UI sends serviceRef. Use that to create yaml field.
3. For v1 service, get serviceRef from imageTag fqn. Corresponding stage identifier needs to be picked.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/evaluators/YamlExpressionFunctor.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/34862#-N5oEw301_AJ7qvbTmL5:-N5oEw301_AJ7qvbTmL6:b-2t3ki4) ([raw file](https://github.com/harness/harness-core/blob/a04a2d5e01e13353b34f6485a3c78ee7fb666df7/878-ng-common-utilities/src/main/java/io/harness/evaluators/YamlExpressionFunctor.java#L33)):*
> ```Java
> @Value
> @Builder
> public class YamlExpressionFunctor {
> ```

We decided to move this functor to cd and rename this as service code is used only by cd



_Code quote:_
```Java
YamlExpressionFunctor
```

**Review by inderschera — DISMISSED** [review]
> Reviewed 11 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/ArtifactResourceUtilsTest.java` line 234 at r1](https://reviewable.io/reviews/harness/harness-core/34862#-N5oPeKl4H-ycoboDyVw:-N5oPeKl4H-ycoboDyVx:b5319kx) ([raw file](https://github.com/harness/harness-core/blob/80ee47e96952392f02a8c23167b5c2f42060f401/120-ng-manager/src/test/java/io/harness/ng/core/artifacts/resources/ArtifactResourceUtilsTest.java#L234)):*
> ```Java
>     String imagePath = artifactResourceUtils.getResolvedImagePath(ACCOUNT_ID, ORG_ID, PROJECT_ID, PIPELINE_ID, "",
>         "<+service.name>", "pipeline.stages.test.spec.serviceConfig.serviceDefinition.spec.artifacts.primary.spec.tag",
>         GitEntityFindInfoDTO.builder().build(), "");
> ```

lets. add test for sidecars also since they also contain arrays i.e sidecars[0].sidecar.spec.tag

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/evaluators/YamlExpressionFunctor.java` line 33 at r2](https://reviewable.io/reviews/harness/harness-core/34862#-N5oEw301_AJ7qvbTmL5:-N63WYHX-VwImiOp8Cyj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a04a2d5e01e13353b34f6485a3c78ee7fb666df7/878-ng-common-utilities/src/main/java/io/harness/evaluators/YamlExpressionFunctor.java#L33)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We decided to move this functor to cd and rename this as service code is used only by cd
</blockquote></details>

Done.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 112 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63Z1A62IW2ksEZ9exb:-N63Z1A62IW2ksEZ9exc:b-f19q3q) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L112)):*
> ```Java
>       String stageIdentifier = split[2];
>       String stageIndex = getStageIndex(mergedCompleteYaml, stageIdentifier);
>       if (EmptyPredicate.isEmpty(serviceId)) {
> ```

nit: static import for readability
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63_2HgEUf6Q6pJF_-G:-N63_2HgEUf6Q6pJF_-H:b-j6yg5k) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L117)):*
> ```Java
>       }
>       // get environment ref
>       String environmentId = getEnvironmentRef(mergedCompleteYaml, stageIndex);
> ```

we should not assume that environment ( or service ) will always be present. 
For better readability, both these methods can pass Optional<String> for serviceRef and EnvironmentRef
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 155 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63YwNB6S5ldSUupFWB:-N63YwNB6S5ldSUupFWC:b-l94b2y) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L155)):*
> ```Java
>       return service.asText();
>     }
>     return null;
> ```

nit: better to return optional<String> than returning null
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 186 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63YqsN-knQ76JEryJY:-N63YqsO0iWrFa2Hf8bZ:b-l94b2y) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L186)):*
> ```Java
>       return environment.asText();
>     }
>     return null;
> ```

nit: better to return optional<String> than returning null
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63XsQKBJQL7CTozMq-:-N63XsQKBJQL7CTozMq0:bbuqudw) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L200)):*
> ```Java
>                                   .getNode()
>                                   .asText(),
>             stageNode.getFieldName());
> ```

we can just match identifier here and break from the loop
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 204 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63Y1xMCDpy9FFfrpwp:-N63Y1xMCDpy9FFfrpwq:bi087d0) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L204)):*
> ```Java
>       return stageFieldNameMap.get(stageIdentifier);
>     } catch (Exception ex) {
>       throw new InvalidRequestException("Exception while resolving stage index for rendering image Path");
> ```

``` for rendering image path``` is not needed here. This method is generic and the error can just say

``` Provided stage <stageIdentifier> is not present in the pipeline ```

similarily, we can improve error messages in other methods 
- getEnvironmentRef

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 2 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63_2HgEUf6Q6pJF_-G:-N63izTt5Wj6f9iyR-9F:b-41mmjr) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L117)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should not assume that environment ( or service ) will always be present. 
For better readability, both these methods can pass Optional<String> for serviceRef and EnvironmentRef
</blockquote></details>

Are there cases where serviceRef will not be present in the final yaml (v1 or v2)? 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 200 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63XsQKBJQL7CTozMq-:-N63i71pED27dBYQQrok:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L200)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can just match identifier here and break from the loop
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 204 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63Y1xMCDpy9FFfrpwp:-N63i6Tx2PUxNl_rghVg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L204)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

``` for rendering image path``` is not needed here. This method is generic and the error can just say

``` Provided stage <stageIdentifier> is not present in the pipeline ```

similarily, we can improve error messages in other methods 
- getEnvironmentRef

</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 1 change requests. 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/34862#-N63_2HgEUf6Q6pJF_-G:-N63lOmw3L-iCtDpLo6g:b-w76mto) ([raw file](https://github.com/harness/harness-core/blob/6ebc6eba4d2323d5e19acc8d7147dbdd19d0f068/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L117)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Are there cases where serviceRef will not be present in the final yaml (v1 or v2)? 
</blockquote></details>

Not sure, maybe Custom stage.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 1 change requests. 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34862)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
