### PR TITLE
fix: [CDS-84036]: Allow the use of [ and , in concatenated expressions

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnCHF8IKUz-HeSzbP:-NjRnCHG8i5GRQc6sEQ8:bv4frz4) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L188)):*
> ```Java
>         // Expression inside [], square brackets denote get method for list/map, thus don't take decision of concatenate
>         // from left substring
>         if (expressionStartPos > 0 && StringUtils.isAlpha(String.valueOf(buf.charAt(expressionStartPos - 1)))) {
> ```

can we wrap this under private methods so caller method is clean? just like comma one
___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnNye8AmBK0rBKq7P:-NjRnNye8AmBK0rBKq7Q:b-q68488) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L210)):*
> ```Java
>         } else {
>           return false;
>         }
> ```

similarly separate private method for this?



_Code quote:_
```Java
        // Checking : belongs to ternary operator or not, if not concatenate it
        if (!buf.toString().contains("?")) {
          return true;
        } else {
          return false;
        }
```
___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnXXfAp8dPHRvdMFp:-NjRnXXfAp8dPHRvdMFq:b-4acg52) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L226)):*
> ```Java
>         // , denotes it could be part of parameter in method, example <+json.list("$", <+var1>)>, then var1 shouldn't be
>         // concatenated.
>         if (checkIfCommaIsInMethodInvocationInRightSubstring(buf, expressionStartPos, expressionEndPos)) {
> ```

do you think we need this for which case?
___
*[`980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java` line 708 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnfEu6xVSdmE38aqY:-NjRnfEu6xVSdmE38aqZ:b8qj0jc) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java#L708)):*
> ```Java
>     assertThat(evaluator.evaluateExpression("[<+f>] <+variables[<+i> + '5']> [<+g>] abc [<+h>]"))
>         .isEqualTo("[abc] archit-harness [def] abc [v2]");
>     assertThat(evaluator.evaluateExpression("<+f>, <+g>, abc, <+h>")).isEqualTo("abc, def, abc, v2");
> ```

can you add example for [ and , just like customer issue shared by rohit

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)* status: 2 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnCHF8IKUz-HeSzbP:-NjRoZLUAToaLnI6nJ-y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L188)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we wrap this under private methods so caller method is clean? just like comma one
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnNye8AmBK0rBKq7P:-NjRp34y4pNx1zYtzHQ2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L210)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

similarly separate private method for this?
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnXXfAp8dPHRvdMFp:-NjRp4BFDukNh3LaL0kB:b-j60z0h) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L226)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do you think we need this for which case?
</blockquote></details>

`<+f>, <+g>` for <+f> in this expr, since there's nothing on left, we will have to check right substring.
___
*[`980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java` line 708 at r1](https://reviewable.io/reviews/harness/harness-core/55554#-NjRnfEu6xVSdmE38aqY:-NjRq_7b05ixhNUSasX7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2ba62fd2b6d6d82788b0f917dcb47983582123d2/980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java#L708)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add example for [ and , just like customer issue shared by rohit
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 236 at r2](https://reviewable.io/reviews/harness/harness-core/55554#-NjS5UNc5Lq-ct_Vw6zv:-NjS5UNc5Lq-ct_Vw6zw:b-iu1skv) ([raw file](https://github.com/harness/harness-core/blob/96b5f60c3a7f5697f4b594af097c937fd6fde1c6/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L236)):*
> ```Java
>           return true;
>         } else {
>           return false;
> ```

use method here

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 236 at r2](https://reviewable.io/reviews/harness/harness-core/55554#-NjS5UNc5Lq-ct_Vw6zv:-NjS7Gdl-yzto6Zi8sSu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96b5f60c3a7f5697f4b594af097c937fd6fde1c6/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L236)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use method here
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut7

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55554)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
