### PR TITLE
[fix]: [PL-28739]: added UsernamePassword auth check for FF PL_NO_EMAIL_FOR_SAML_ACCOUNT_INVITES

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added UsernamePassword auth check for FF PL_NO_EMAIL_FOR_SAML_ACCOUNT_INVITES

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38363)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38363#-:-NDYjDu66pUcHVl2ULzW:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 404 at r5](https://reviewable.io/reviews/harness/harness-core/38363#-NDZcGYkEkTvyT5Az4AU:-NDZcGYkEkTvyT5Az4AV:bpfq5ve) ([raw file](https://github.com/harness/harness-core/blob/5aacb5526465d668434144ea0769ec161e1cd30d/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L404)):*
> ```Java
>     inviteRepository.updateInvite(newInvite.getId(), update);
>     String accountId = newInvite.getAccountIdentifier();
>     boolean isSSOEnabled = CGRestUtils.getResponse(accountClient.isSSOEnabled(accountId));
> ```

can we move this to a method call? something like "checkIfSSOEnabled(accountId)". I see its repetitively used

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38363)* status: 1 file(s) to review.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38363)* status: 1 file(s) to review.

**Pull request merged**
