### PR TITLE
Revert "fix: [DEL-4677]: Fix DelegateApp Guice issues and cleanup main BUILD.bazel"

### PR DESCRIPTION
**Pull request by gaurav-jain1**
Reverts harness/harness-core#39369

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39402)

### CODE REVIEW

**Comment by gaurav-jain1** [comment]
trigger ft1

**Comment by gaurav-jain1** [comment]
trigger ft2

**Comment by bharatgoelharness** [comment]
trigger ft1

**Comment by bharatgoelharness** [comment]
trigger ft2

**Comment by diptiman-adak** [comment]
trigger ft1

**Comment by diptiman-adak** [comment]
trigger ft1

**Comment by diptiman-adak** [comment]
trigger ti2

**Comment by diptiman-adak** [comment]
trigger ft1

**Comment by diptiman-adak** [comment]
trigger ft1

**Comment by diptiman-adak** [comment]
trigger ft1

**Comment by diptiman-adak** [comment]
trigger ft2

**Pull request merged**
