### PR TITLE
fix: [SRM-12629]: Added validations for NR, GCP_Logs, DynaTrace health source spec [SRM-12630] [SRM-12631]

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
Added validations for NR, GCP_Logs, DynaTrace health source spec while creating MonitoredService through YAML / template / API
Fix for - [SRM-12629](https://harness.atlassian.net/browse/SRM-12629) [SRM-12630](https://harness.atlassian.net/browse/SRM-12630) [SRM-12631](https://harness.atlassian.net/browse/SRM-12631)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40152)

### CODE REVIEW

**Comment by sathish-soundarapandian** [comment]
trigger messagecheck

**Comment by sathish-soundarapandian** [comment]
trigger ti0, ti1

**Comment by sathish-soundarapandian** [comment]
trigger tin4

**Comment by sathish-soundarapandian** [comment]
trigger compatibilitycheck

**Review by deepak-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40152)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NewRelicHealthSourceSpec.java` line 106 at r2](https://reviewable.io/reviews/harness/harness-core/40152#-NH3Si_W9feUS58dPQB8:-NH3Si_W9feUS58dPQB9:biqqs5y) ([raw file](https://github.com/harness/harness-core/blob/7a749bc125c3f6545a358f01c9696a0e692dae16/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/NewRelicHealthSourceSpec.java#L106)):*
> ```Java
>   @Override
>   public void validate() {
>     for (NewRelicMetricDefinition metricDefinition : newRelicMetricDefinitions) {
> ```

Why are we manually triggering the violation check? Add @Valid to the metricDefiniton doesn't trigger it?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/StackdriverLogHealthSourceSpec.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/40152#-NH3Sx0iC_PHpDQQ45IQ:-NH3Sx0iC_PHpDQQ45IR:b-eq05yj) ([raw file](https://github.com/harness/harness-core/blob/7a749bc125c3f6545a358f01c9696a0e692dae16/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/StackdriverLogHealthSourceSpec.java#L59)):*
> ```Java
>   @JsonIgnoreProperties(ignoreUnknown = true)
>   public static class QueryDTO {
>     @NotNull String identifier;
> ```

Check if in gcp UI is sending the identifier. Might break the backword compatibility

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40152)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/40152#-NHbtHy_CwfGKFA9yaf7:-NHbtHy_CwfGKFA9yaf8:b-v0mrrj) ([raw file](https://github.com/harness/harness-core/blob/5164d493a3de44e588bb68d8e5bb9733cadf4c2b/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/healthSouceSpec/DynatraceHealthSourceSpec.java#L68)):*
> ```Java
>   @Override
>   public void validate() {
>     Preconditions.checkNotNullNorEmpty(getMetricPacks(), "MetricPacks is null or empty");
> ```

Metric packs can be null in dynatrace.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40152)* status: :shipit: complete! ✓

**Pull request merged**
