### PR TITLE
[feat]: [PLG-3024]: added isCannyUsernameAbbreviationEnabled field in Account collection with UPDATE API

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added isCannyUsernameAbbreviationEnabled field in Account collection with UPDATE API

Scenarios tested:

API: @PUT -> https://localhost:8181/api/account/kmpySmUISimoRrJL6NL73w/canny-username-abbreviation-enabled?routingId=kmpySmUISimoRrJL6NL73w&cannyUsernameAbbreviationEnabled=true

Account collection record:
```
{
    "_id" : "kmpySmUISimoRrJL6NL73w",
    "companyName" : "Harness",
    "accountName" : "Harness",
    "accountKey" : "2f6b0988b6fb3370073c3d0505baee59",
    "dataRetentionDurationMs" : NumberLong(0),
    "licenseInfo" : {
        "accountType" : "PAID",
        "accountStatus" : "ACTIVE",
        "expiryTime" : NumberLong(1716402599000),
        "licenseUnits" : 1500
    },
    "trustLevel" : -1,
    "encryptedLicenseInfo" : { "$binary" : "LToXO58HmhICTWsd1+AAtpvL68hYyosyCpAWe7HNn+Fg7FyCm4FrWDKuqUgYic6JBNqLOh8D5pMqJGmeJR4fpw==", "$type" : "00" },
    "emailSentToSales" : false,
    "lastLicenseExpiryReminderSentAt" : NumberLong(0),
    "twoFactorAdminEnforced" : false,
    "defaultExperience" : "CG",
    "isCrossGenerationAccessEnabled" : false,
    "createdFromNG" : false,
    "accountActivelyUsed" : true,
    "isProductLed" : false,
    "smpAccount" : false,
    "sessionTimeOutInMinutes" : 1440,
    "localEncryptionEnabled" : false,
    "oauthEnabled" : false,
    "ringName" : "ring3",
    "backgroundJobsDisabled" : false,
    "isHarnessSupportAccessAllowed" : true,
    "delegateTelemetryPublisherIteration" : NumberLong(1699706104929),
    "delegateTaskRebroadcastIteration" : NumberLong(0),
    "delegateTaskFailIteration" : NumberLong(0),
    "cloudCostEnabled" : false,
    "ceAutoCollectK8sEvents" : false,
    "serviceGuardLimit" : NumberLong(20),
    "globalDelegateAccount" : false,
    "immutableDelegateEnabled" : true,
    "isPovAccount" : false,
    "appId" : "__GLOBAL_APP_ID__",
    "createdAt" : NumberLong(1684757371309),
    "lastUpdatedAt" : NumberLong(1699666654319),
    "authenticationMechanism" : "USER_PASSWORD",
    "nextGenEnabled" : true,
    "whitelistedDomains" : null,
    "licenseExpiryCheckIteration" : NumberLong(1699667148219),
    "accountDeletionIteration" : NumberLong(1693612127997),
    "resourceLookupSyncIteration" : NumberLong(1699707657328),
    "gitSyncExpiryCheckIteration" : NumberLong(1699705702159),
    "usageMetricsTaskIteration" : NumberLong(1699706104869),
    "lastUpdatedBy" : {
        "uuid" : "lv0euRhKRCyiXWzS7pOg6g",
        "name" : "Admin",
        "email" : "admin@harness.io"
    },
    "publicAccessEnabled" : false,
    "isCannyUsernameAbbreviationEnabled" : true
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55318)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger uts

**Review by Xin-Harness — DISMISSED** [review]

**Comment by kapil-harness** [comment]
trigger ut0,ut3,ut7,ut9

**Comment by kapil-harness** [comment]
trigger uts

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by kapil-harness** [comment]
trigger ut5,ut6,ut7,ut8,ut9

**Comment by kapil-harness** [comment]
trigger ut9

**Review by Xin-Harness — APPROVED** [review]

**Review by neelam-harness — APPROVED** [review]

**Comment by kapil-harness** [comment]
trigger review

**Pull request merged**
