### PR TITLE
[feat]: [CDS-83271]: Include and populate the default, allowed-values and execution keywords values in the inputs-metadata api

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

- Added allowed_values, regex and execution fields in the input-metadata API contract.
- Populating the allowed_values, regex and execution fields based on the inputs present in the YAML.

Testing: 
Tested the API with pipeline YAML having inputs with the allowed_values, execution, regex fields and without these values. 

- The input-details, metadata and dependencies are coming correctly.

Example: For the below YAML
```version: 1
kind: pipeline
spec:
  inputs:
    timeout:
      type: string
      desc: timeout of shell script step
      required: true
      default: 10m
      execution: false
      validator:
        allowed: 
          - 10m
          - 20m
    script:
      type: string
      execution: true
      validator:
        regex: ^.*@harness.io
    jenkinsJobName:
      type: string
      validator:
        allowed: [] 
    jenkinsConnector:
      type: string
    jobParam:
      type: object
      execution: false
  stages:
    - type: custom
      name: s1
      spec:
        steps:
          - type: shell-script
            name: shell_script_1
            identifier: shell_script_1
            spec:
              shell: bash
              onDelegate: true
              source:
                type: inline
                spec:
                  script: <+inputs.script>
            timeout: <+inputs.timeout>
          - type: JenkinsBuild
            name: JenkinsBuild_1
            identifier: JenkinsBuild_1
            spec:
              connectorRef: <+inputs.jenkinsConnector>
              consoleLogPollFrequency: 5s
              jobName: <+inputs.jenkinsJobName>
              jobParameter: <+inputs.jobParam>
              unstableStatusAsSuccess: false
              useConnectorUrlForJobExecution: false
            timeout: 10m
```
we will get the below inputs-metadata response.
```
{
    "inputs": [
        {
            "details": {
                "name": "timeout",
                "type": "String",
                "description": "timeout of shell script step",
                "required": true,
                "execution": false,
                "allowed_values": [
                    "10m",
                    "20m"
                ],
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "script",
                "type": "String",
                "description": null,
                "required": false,
                "execution": true,
                "allowed_values": null,
                "regex": "^.*@harness.io",
                "default": null
            },
            "metadata": {
                "field_properties": [],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "jenkinsJobName",
                "type": "String",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": [],
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "string",
                        "internal_type": "jenkins_job_name",
                        "entity_type": null,
                        "stage_type": null
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [
                        {
                            "field_name": "connectorRef",
                            "input_name": "jenkinsConnector"
                        }
                    ],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "jenkinsConnector",
                "type": "String",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "string",
                        "internal_type": "jenkins_connector",
                        "entity_type": null,
                        "stage_type": null
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [],
                    "required_fixed_values": []
                }
            }
        },
        {
            "details": {
                "name": "jobParam",
                "type": "Object",
                "description": null,
                "required": false,
                "execution": false,
                "allowed_values": null,
                "regex": null,
                "default": null
            },
            "metadata": {
                "field_properties": [
                    {
                        "input_type": "object",
                        "internal_type": "jenkins_job_parameter",
                        "entity_type": null,
                        "stage_type": null
                    }
                ],
                "dependencies": {
                    "required_runtime_inputs": [
                        {
                            "field_name": "connectorRef",
                            "input_name": "jenkinsConnector"
                        },
                        {
                            "field_name": "jobName",
                            "input_name": "jenkinsJobName"
                        }
                    ],
                    "required_fixed_values": []
                }
            }
        }
    ]
}
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54919)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54919)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/54919#-NiEORkJ02ASTQWxbVgf:-NiEORkJ02ASTQWxbVgg:b-27vq0j) ([raw file](https://github.com/harness/harness-core/blob/f40cb65923c4e63a82371b1c240f8ab9264b9aea/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java#L102)):*
> ```Java
>     InputDetailsBuilder builder =
>         InputDetails.builder().name(inputName).type(SchemaInputType.getYamlInputType(inputNode.get("type").asText()));
>     if (inputNode.get(YAMLFieldNameConstants.DESCRIPTION) != null) {
> ```

wouldnt this be desc and not description? schema could be old
@shalini-agr we are using desc at other places right?
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/54919#-NiEOszC8hH3Nl-XCFrU:-NiEOszC8hH3Nl-XCFrV:b-yrwdf9) ([raw file](https://github.com/harness/harness-core/blob/f40cb65923c4e63a82371b1c240f8ab9264b9aea/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java#L122)):*
> ```Java
>         }
>         builder.allowedValues(
>             (List<Object>) JsonNodeUtils.getValueFromJsonNode(validatorNode.get(YAMLFieldNameConstants.ALLOWED)));
> ```

nit: will it handle empty allowedValues etc?

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/54919#-NiEOszC8hH3Nl-XCFrU:-NiESuCGAN_GwbKB1ZCn:be62s2d) ([raw file](https://github.com/harness/harness-core/blob/f40cb65923c4e63a82371b1c240f8ab9264b9aea/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java#L122)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: will it handle empty allowedValues etc?
</blockquote></details>

In case of empty allowedValues list, we will send an empty list in the input-details.

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/54919#-NiEOszC8hH3Nl-XCFrU:-NiEXS-k-9-hQyphukTC:bx6ehyf) ([raw file](https://github.com/harness/harness-core/blob/f40cb65923c4e63a82371b1c240f8ab9264b9aea/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java#L122)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

In case of empty allowedValues list, we will send an empty list in the input-details.
</blockquote></details>

The question is should we allow empty allowed_values list?

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/54919#-NiEORkJ02ASTQWxbVgf:-NiEYbJCASejF29s___n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f40cb65923c4e63a82371b1c240f8ab9264b9aea/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java#L102)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

wouldnt this be desc and not description? schema could be old
@shalini-agr we are using desc at other places right?
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/54919#-NiEORkJ02ASTQWxbVgf:-NiEYd8T8TICEg3nj0oQ:b-ato9cx) ([raw file](https://github.com/harness/harness-core/blob/f40cb65923c4e63a82371b1c240f8ab9264b9aea/953-yaml-commons/src/main/java/io/harness/yaml/schema/inputs/YamlInputUtils.java#L102)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Updated to inputs. Will update the schema as well

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut4 ut7

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54919)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
@mankrit-singh @ashishsanodia-harness is there any setting in the open-api spec to not include the null values in the API response? If we see in the pr description, the response has many field values as null. Can we not include these null values in response? This will reduce the response size.

**Review by shalini-agr — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger review

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54919#-:-NiNhyNwB_23jbt2GAfB:bnfp4nl)* status: 5 file(s) to review.

**Pull request merged**
