### PR TITLE
feat: [CVS-9901]: Added API for SLO details page

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31936)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31936)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODetails.java, line 19 at r1](https://reviewable.io/reviews/harness/harness-core/31936#-MztYZYd268tDWy2LfmQ:-MztYZYd268tDWy2LfmR:b-frtdam) ([raw file](https://github.com/harness/harness-core/blob/897ab3124a807b83f966ecfcaf51c3842183cfb7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODetails.java#L19)):*
> ```Java
> 
>   public static SLODetailsBuilder withGraphData(SLOGraphData sloGraphData) {
>     return SLODetails.builder()
> ```

Use SLODashboardWidget with Graph data to initialise the SLODetailsBuilder
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java, line 72 at r1](https://reviewable.io/reviews/harness/harness-core/31936#-MztYkQz11JAWuQ8uOuY:-MztYkQz11JAWuQ8uOuZ:bh9nk37) ([raw file](https://github.com/harness/harness-core/blob/897ab3124a807b83f966ecfcaf51c3842183cfb7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L72)):*
> ```Java
>   @Path("widget/{identifier}")
>   @ExceptionMetered
>   @ApiOperation(value = "get widget for SLO", nickname = "getSLODashboardWidget")
> ```

getSLODashboardDetails
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java, line 74 at r1](https://reviewable.io/reviews/harness/harness-core/31936#-MztYxG8BClpd8_IbGUR:-MztYxG8BClpd8_IbGUS:b-jx1ewk) ([raw file](https://github.com/harness/harness-core/blob/897ab3124a807b83f966ecfcaf51c3842183cfb7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L74)):*
> ```Java
>   @ApiOperation(value = "get widget for SLO", nickname = "getSLODashboardWidget")
>   @NGAccessControlCheck(resourceType = SLO, permission = VIEW_PERMISSION)
>   public ResponseDTO<SLODashboardWidget> getSloDashboardWidget(
> ```

SLODashboardDetails instead of SLODashboardWidget
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java, line 138 at r1](https://reviewable.io/reviews/harness/harness-core/31936#-Mzt_42l9oDqxpxJ_mdd:-Mzt_42l9oDqxpxJ_mde:bujqaxg) ([raw file](https://github.com/harness/harness-core/blob/897ab3124a807b83f966ecfcaf51c3842183cfb7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java#L138)):*
> ```Java
>         timePeriod.getStartTime(serviceLevelObjective.getZoneOffset()), currentTimeMinute, totalErrorBudgetMinutes,
>         serviceLevelIndicator.getSliMissingDataType(), serviceLevelIndicator.getVersion());
>     return SLODashboardWidget.withGraphData(sloGraphData)
> ```

Try using the getSloDashboardWidgetHelper in SLODetails as well

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31936)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java, line 23 at r2](https://reviewable.io/reviews/harness/harness-core/31936#-MzxtznY7vcKXIte_Ok7:-MzxtznY7vcKXIte_Ok8:bchuu6d) ([raw file](https://github.com/harness/harness-core/blob/2a26513dae91080f00b74bb040b26fa41f11b475/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODashboardWidget.java#L23)):*
> ```Java
> import lombok.experimental.SuperBuilder;
> 
> @Data
> ```

why do we need Data?
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java, line 73 at r2](https://reviewable.io/reviews/harness/harness-core/31936#-MzxuAW51aIjdb6eVoMs:-MzxuAW51aIjdb6eVoMt:b-53ml4a) ([raw file](https://github.com/harness/harness-core/blob/2a26513dae91080f00b74bb040b26fa41f11b475/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L73)):*
> ```Java
>   @Path("widget/{identifier}")
>   @ExceptionMetered
>   @ApiOperation(value = "get SLO Dashboard Details", nickname = "getSLODetails")
> ```

please check description of the api also.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java, line 76 at r2](https://reviewable.io/reviews/harness/harness-core/31936#-MzxuJCo7qYj1WPochSd:-MzxuJCo7qYj1WPochSe:bw9hlxx) ([raw file](https://github.com/harness/harness-core/blob/2a26513dae91080f00b74bb040b26fa41f11b475/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/SLODashboardResource.java#L76)):*
> ```Java
>   @NGAccessControlCheck(resourceType = SLO, permission = VIEW_PERMISSION)
>   public ResponseDTO<SLODashboardDetail> getSloDashboardWidget(
>       @ApiParam(required = true) @NotNull @QueryParam("accountId") @AccountIdentifier String accountId,
> ```

please use ProjectParams
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODetails.java, line 19 at r1](https://reviewable.io/reviews/harness/harness-core/31936#-MztYZYd268tDWy2LfmQ:-MzxvMtd6J4_FRJsmZNu:b-59ti1l) ([raw file](https://github.com/harness/harness-core/blob/897ab3124a807b83f966ecfcaf51c3842183cfb7/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLODetails.java#L19)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Use SLODashboardWidget with Graph data to initialise the SLODetailsBuilder
</blockquote></details>

The difference between widget and this is only desc? We we need more things in future?

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31936)* status: 1 change requests. 1. unresolved discussions.

**Comment by arpit-harness** [comment]
trigger ti0

**Comment by arpit-harness** [comment]
trigger ti1

**Comment by arpit-harness** [comment]
trigger ti2

**Comment by arpit-harness** [comment]
trigger buildnum

**Comment by arpit-harness** [comment]
trigger recency

**Comment by arpit-harness** [comment]
trigger ft1

**Comment by arpit-harness** [comment]
trigger ft2

**Comment by arpit-harness** [comment]
trigger checkstyle

**Comment by arpit-harness** [comment]
trigger messagecheck

**Comment by arpit-harness** [comment]
trigger compile

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31936#-:-N-1gwddAhJ3NMS5LIMV:bnfp4nl)* status: 1. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31936)* status: :shipit: complete! ✓

**Pull request merged**
