### PR TITLE
fix: [CDS-81741]: Added failure in case of EXPIRE_ALL

### PR DESCRIPTION
**Pull request by shivamnegi94**
## Describe your changes
Failure Info was missing in case of EXPIRE_ALL.
Added the failure info in `expireDiscontinuedInstanceAndEndAllNodesExecution`
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)

### CODE REVIEW

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/54241#-Nh1hH7t8lvplw7VQAnI:-Nh2PpeBCdNFT9S4FTyB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7325a6975e4240314a99b5d0c925d7ee527bbe8e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L52)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

interrupt contains interruptConfig as well etc, pass metadata separately
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/interrupts/Interrupt.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/54241#-Nh1h_BcB0lmUYllrRxY:-Nh2PqVmCx3YPH_TGFMH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7325a6975e4240314a99b5d0c925d7ee527bbe8e/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/interrupts/Interrupt.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should not use setter but infact use toBuilder to create new field again
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java` line 53 at r3](https://reviewable.io/reviews/harness/harness-core/54241#-Nh1h8C0DAuYrkouL5sL:-Nh2PsLR1iJxiEOzSUba:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7325a6975e4240314a99b5d0c925d7ee527bbe8e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionService.java#L53)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We already have getWithFieldsIncluded, use it
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java` line 137 at r3](https://reviewable.io/reviews/harness/harness-core/54241#-Nh1hD-u8SBubeExJYib:-Nh2Pt-e-V11-PK2RZu8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7325a6975e4240314a99b5d0c925d7ee527bbe8e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java#L137)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

**Comment by shivamnegi94** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 9 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by shivamnegi94** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java` line 141 at r6](https://reviewable.io/reviews/harness/harness-core/54241#-Nh5SKr8CEdePOOg37bs:-Nh5SKr8CEdePOOg37bt:b-6b3sg4) ([raw file](https://github.com/harness/harness-core/blob/a9b78256a3abbb01ea60656fff1d088109c69bc6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java#L141)):*
> ```Java
> 
>   public void expireDiscontinuedInstanceAndEndAllNodesExecution(NodeExecution nodeExecution,
>       InterruptConfig interruptConfig, String interruptId, InterruptType interruptType, Map<String, String> metadata) {
> ```

Can we create a InterruptMetadata class altogether?
Map<String, String>

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java` line 141 at r6](https://reviewable.io/reviews/harness/harness-core/54241#-Nh5SKr8CEdePOOg37bs:-Nh5sPET45cuNQiNWZfM:b1gjco) ([raw file](https://github.com/harness/harness-core/blob/a9b78256a3abbb01ea60656fff1d088109c69bc6/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java#L141)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we create a InterruptMetadata class altogether?
Map<String, String>
</blockquote></details>

What will be the reason ?

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54241)* status: :shipit: complete! ✓

**Comment by shivamnegi94** [comment]
trigger review

**Comment by shivamnegi94** [comment]
trigger messagecheck

**Pull request merged**
