### PR TITLE
fix: [CDS-42543]: Handle AWS Throttling Error

### PR DESCRIPTION
**Pull request by jelenaHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37638)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37638)

**Comment by jelenaHarness** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/aws/delegate/AwsElbHelperServiceDelegateImpl.java` line 598 at r2](https://reviewable.io/reviews/harness/harness-core/37638#-NCsngEO5usfZ0aJUuX8:-NCsngEP1UFvwAKx_GzG:b-xza8m8) ([raw file](https://github.com/harness/harness-core/blob/ed869f3f77ace0a0c97d583973c4caf0221e94d2/930-delegate-tasks/src/main/java/software/wings/service/impl/aws/delegate/AwsElbHelperServiceDelegateImpl.java#L598)):*
> ```Java
>                  getAmazonElasticLoadBalancingClientV2(Regions.fromName(region), awsConfig))) {
>       HTimeLimiter.callInterruptible21(timeLimiter, Duration.ofMinutes(timeout),
>           waitForInstancesToRegisterWithBackoff(closeableAmazonElasticLoadBalancingClient.getClient(), awsConfig,
> ```

Can we use the already existing logic introduced and extracted out in https://github.com/harness/harness-core/pull/34377 ?

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/service/impl/aws/delegate/AwsElbHelperServiceDelegateImpl.java` line 598 at r2](https://reviewable.io/reviews/harness/harness-core/37638#-NCsngEO5usfZ0aJUuX8:-NCsnnMa21IBHwPa583K:b-frb8sk) ([raw file](https://github.com/harness/harness-core/blob/ed869f3f77ace0a0c97d583973c4caf0221e94d2/930-delegate-tasks/src/main/java/software/wings/service/impl/aws/delegate/AwsElbHelperServiceDelegateImpl.java#L598)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Can we use the already existing logic introduced and extracted out in https://github.com/harness/harness-core/pull/34377 ?
</blockquote></details>

We shouldn't introduce our own sleep times etc mechanism. AWS SDK provides by themselves.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37638)* status: Some of the checks are too old. 1 file(s) to review. 0 of 1 approvals obtained.

**Comment by jelenaHarness** [comment]
closing in benefit of https://github.com/harness/harness-core/pull/37910

**Pull request closed without merging**
