### PR TITLE
fix: [CDS-37918]: Make clone of object

### PR DESCRIPTION
**Pull request by abhinav-harness**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33486)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33486)* status: Some of the checks are too old.

**Review by srinivaswings — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33486)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger recency

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33486)* status: :shipit: complete! ✓

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33486)* status: :shipit: complete! ✓

**Pull request merged**
