### PR TITLE
feat: [CDS-36844]: Update createdBy and lastModifiedBy to use Embedde…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…dUser instead of String

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32863)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32863)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZVNva4hUwDUd6Bxgv:-N1ZVNvb4nNj1aAu5oy9:b-gyd7qb) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java#L55)):*
> ```Java
>   public Optional<EmbeddedUser> getCurrentAuditor() {
>     try {
>       UserPrincipal principal = (UserPrincipal) SecurityContextBuilder.getPrincipal();
> ```

Firstly check whether SecurityContextBuilder.getPrincipal() is different then null and after
that check for principal.getType() which needs to be UserPrincipal in our case. For all other cases return empty Optional. 

Try to use SourcePrincipalContextBuilder.getSourcePrincipal()
___
*[`400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZZbHrC4orlMYS-npt:-N1ZZbHrC4orlMYS-npu:b47xaxh) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java#L63)):*
> ```Java
>       return Optional.of(embeddedUser);
>     } catch (Exception e) {
>       log.warn("Something went wrong while trying to read current auditor.");
> ```

Write error msg to logs here.
___
*[`960-ng-core-beans/BUILD.bazel` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZXfez0CEG8hI7ecvw:-N1ZXfez0CEG8hI7ecvx:b-mez3cz) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/960-ng-core-beans/BUILD.bazel#L10)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//960-persistence:module",
> ```

Remove persistent module form beans module 
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/NGEmbeddedUserDTO.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZXn5s2cUs50ikaaHo:-N1ZXn5s2cUs50ikaaHp:b3v39g) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/NGEmbeddedUserDTO.java#L28)):*
> ```Java
>   private String email;
> 
>   public static NGEmbeddedUserDTO fromEmbeddedUser(EmbeddedUser user) {
> ```

Remove fromEmbeddedUser and create mapper here 120-ng-manager/src/main/java/io/harness/ng/core/mapper/ where EmbeddedUser and NGEmbeddedUserDTO are available. 

Pls, rename this from NGEmbeddedUserDTO to EmbeddedUserDetailsDTO 
___
*[`960-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZiaBH7ipEXod8VE_l:-N1ZiaBI6MoTNJQZ_khw:bvn5uyx) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/960-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java#L111)):*
> ```Java
>   @Bean
>   public AuditorAware<EmbeddedUser> auditorAware() {
>     return injector.getInstance(UserProvider.class);
> ```

Minor - here I suggest to create new class SpringSecurityAuditorAware which implements AuditorAware<EmbededUser> in the same package as this class and remove AuditorAware<> from UserProvider.

**Comment by bojanmicovic** [comment]
*[`400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZVNva4hUwDUd6Bxgv:-N1cE3lXBBqHPPIJn5M4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java#L55)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Firstly check whether SecurityContextBuilder.getPrincipal() is different then null and after
that check for principal.getType() which needs to be UserPrincipal in our case. For all other cases return empty Optional. 

Try to use SourcePrincipalContextBuilder.getSourcePrincipal()



</blockquote></details>

Done.

**Comment by bojanmicovic** [comment]
*[`400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZZbHrC4orlMYS-npt:-N1cE5kk2jq5G542vZzg:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/400-rest/src/main/java/software/wings/security/ThreadLocalUserProvider.java#L63)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Write error msg to logs here.
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`960-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZiaBH7ipEXod8VE_l:-N1cEA1MCMlylJksnPB1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/960-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java#L111)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - here I suggest to create new class SpringSecurityAuditorAware which implements AuditorAware<EmbededUser> in the same package as this class and remove AuditorAware<> from UserProvider. 
</blockquote></details>

Done

**Comment by bojanmicovic** [comment]
*[`960-ng-core-beans/BUILD.bazel` line 10 at r1](https://reviewable.io/reviews/harness/harness-core/32863#-N1ZXfez0CEG8hI7ecvw:-N1cEBwh57IARGISLT8b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/18086061f65fc12a4040ae1ec775e09bacdb9be3/960-ng-core-beans/BUILD.bazel#L10)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Remove persistent module form beans module 
</blockquote></details>

Done.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 16 of 20 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32863#-:-N1cLtqYBKvRhLv65zJs:bnfp4nl)* status: :shipit: complete! ✓

___
*[`960-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java` line 110 at r3](https://reviewable.io/reviews/harness/harness-core/32863#-N1cLThy-MVULdd-xVTM:-N1cLThz40OcEjyVznsr:bin2h5r) ([raw file](https://github.com/harness/harness-core/blob/fbe5490f242ad9de8df4a63949656f38ef04b75b/960-persistence/src/main/java/io/harness/springdata/SpringPersistenceConfig.java#L110)):*
> ```Java
>   @Bean
>   public AuditorAware<EmbeddedUser> auditorAware() {
>     return injector.getInstance(SpringSecurityAuditorAware.class);
> ```

Should we "return new SpringSecurityAuditorAware()' or this is better approach via injector?
___
*[`960-persistence/src/main/java/io/harness/springdata/SpringSecurityAuditorAware.java` line 15 at r3](https://reviewable.io/reviews/harness/harness-core/32863#-N1cKPis4hnpUD85UDIz:-N1cKPis4hnpUD85UDJ-:bfy0i9j) ([raw file](https://github.com/harness/harness-core/blob/fbe5490f242ad9de8df4a63949656f38ef04b75b/960-persistence/src/main/java/io/harness/springdata/SpringSecurityAuditorAware.java#L15)):*
> ```Java
> import org.springframework.data.mongodb.config.EnableMongoAuditing;
> 
> @EnableMongoAuditing
> ```

Annotation @EnableMongoAuditing is already placed on SpringPersistenceConfig pls remove here.
___
*[`960-persistence/src/main/java/io/harness/springdata/SpringSecurityAuditorAware.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/32863#-N1cKAuZ7u1w-zviK_AA:-N1cKAuZ7u1w-zviK_AB:b-8hztt9) ([raw file](https://github.com/harness/harness-core/blob/fbe5490f242ad9de8df4a63949656f38ef04b75b/960-persistence/src/main/java/io/harness/springdata/SpringSecurityAuditorAware.java#L22)):*
> ```Java
>   public Optional<EmbeddedUser> getCurrentAuditor() {
>     try {
>       if (!PrincipalType.USER.equals(SecurityContextBuilder.getPrincipal().getType())) {
> ```

Minor - can SecurityContextBuilder.getPrincipal() be null?

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 6 of 24 files at r1, 12 of 20 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32863)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger tin1

**Comment by bojanmicovic** [comment]
trigger ti1

**Comment by bojanmicovic** [comment]
trigger ft1

**Pull request merged**
