### PR TITLE
techdebt: [PL-22276]: Remove support for custom privileged role assignments

### PR DESCRIPTION
**Pull request by naman-goenka**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30614)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30614#-:-Mw0NuQw4uON78zPFOCh:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 4 of 14 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30614)* status: :shipit: complete! ✓

**Pull request merged**
