### PR TITLE
[fix]:[pie-6716]: fix for handling % in filepath

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added code fix for handling % in filepath while creating remote entities. 
Screenshot 2022-12-15 at 4 34 29 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41611)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/41611#-NJKSDVg09294tQzDWCV:-NJKSDVg09294tQzDWCW:b-s09adc) ([raw file](https://github.com/harness/harness-core/blob/f126c5de0a5a30555e2581cbb9d605d5c3e6e879/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L129)):*
> ```Java
>   }
> 
>   private void validateRequestParamFromContextWithoutDecoding(
> ```

We shouldn't put any specific check for filepath key. The issue could come in any key. It should be generic in nature.

Also, doesn't the url decoding fail in such case? Does it succeed here and only fail when it reaches SCM?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41611)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/41611#-NJKSDVg09294tQzDWCV:-NJKcUg90Dd8-iJbIcoD:buuq9r4) ([raw file](https://github.com/harness/harness-core/blob/f126c5de0a5a30555e2581cbb9d605d5c3e6e879/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L129)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We shouldn't put any specific check for filepath key. The issue could come in any key. It should be generic in nature.

Also, doesn't the url decoding fail in such case? Does it succeed here and only fail when it reaches SCM?
</blockquote></details>

we want to put this check for only file path cause, %2F gets decoded to /, we dont want to break such existing cases.

The Url decoder doesnt fail when we have % in the file path, it fails in the SCM. The only time it fails in the decoder is when the % is the last char, as it tries to use % and its next 2 chars to decode.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/41611#-NJKSDVg09294tQzDWCV:-NJMKv0-ELarw5h5MIqE:bo4w9mk) ([raw file](https://github.com/harness/harness-core/blob/f126c5de0a5a30555e2581cbb9d605d5c3e6e879/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L129)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

we want to put this check for only file path cause, %2F gets decoded to /, we dont want to break such existing cases.

The Url decoder doesnt fail when we have % in the file path, it fails in the SCM. The only time it fails in the decoder is when the % is the last char, as it tries to use % and its next 2 chars to decode.
</blockquote></details>

what if I try to pass % in my branch name?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41611)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/41611#-NJKSDVg09294tQzDWCV:-NJO1Gxb0ccz76HvsI_O:bp1bwua) ([raw file](https://github.com/harness/harness-core/blob/f126c5de0a5a30555e2581cbb9d605d5c3e6e879/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L129)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if I try to pass % in my branch name?
</blockquote></details>

We can pass the % if there is an actual branch with % present. We will be able to create a remote entity both from Ui and even from curl. But the issue will be when we try to retrieve it, with the branch with %, it fails to retrieve,

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41611)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java` line 129 at r2](https://reviewable.io/reviews/harness/harness-core/41611#-NJKSDVg09294tQzDWCV:-NJO37jX2nLOpp7bCLim:b-ov641) ([raw file](https://github.com/harness/harness-core/blob/f126c5de0a5a30555e2581cbb9d605d5c3e6e879/900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java#L129)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

We can pass the % if there is an actual branch with % present. We will be able to create a remote entity both from Ui and even from curl. But the issue will be when we try to retrieve it, with the branch with %, it fails to retrieve,
</blockquote></details>

also, if in any of the param, the value passed is abc%2def, then the decoder should be able to interpret it as abc/def, 
if we remove the check on file path key, then such cases will break

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41611)* status: 1. unresolved discussions.

**Pull request closed without merging**
