### PR TITLE
feat: [DEL-3689]: save delegate tags only in delegate group for ng

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31965)

### CODE REVIEW

**Review by mdmilic — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31965)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/31965#-Mza1T_Z9NjPhdb4hCEM:-Mza1T_Z9NjPhdb4hCEN:b-aixj5n) (no related file):*
what happens to existing NG tags? are they already part of delegateGroup tags, now that we are relying directly from delegateGroup.

---

**Comment by jennyjames21** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/31965#-Mza1T_Z9NjPhdb4hCEM:-Mza2jJH8MA1uw5rO71n:b-fsu5cf) (no related file):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

what happens to existing NG tags? are they already part of delegateGroup tags, now that we are relying directly from delegateGroup.
</blockquote></details>

nvm that's only for error message

---

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31965)* status: :shipit: complete! ✓

**Review by jennyjames21 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31965)* status: :shipit: complete! ✓

**Review by AnupamIO — APPROVED** [review]

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31965)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31965#-Mza1T_Z9NjPhdb4hCEM:-MznTHqQ1BlixKSIE-v6:bu1ja2n) (no related file):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

nvm that's only for error message
</blockquote></details>

existing ng tags were being saved in both delegate as well as delegate group collection. So we are good on that.

---

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31965)* status: :shipit: complete! ✓

**Pull request merged**
