### PR TITLE
[feat]: [CDS-83149]: Allow infrastructure definition override during plan creation

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
If infrastructure definitions field is provided during environment propagation from stage, then the plan creator should use that infrastructure value instead of the value of infrastructure from the propagated environment. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56319)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger ut9

**Comment by lovish1999** [comment]
trigger ut9

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger ut9

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 487 at r2](https://reviewable.io/reviews/harness/harness-core/56319#-NlPz0La4UJVGo0zJhb0:-NlPz0LbEUcRCktRrH-_:b-1gsqgc) ([raw file](https://github.com/harness/harness-core/blob/9e7d96eeca3e11bc819a574b2b508a1d69d7b39a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L487)):*
> ```Java
>             && isNotEmpty(environmentYaml.getInfrastructureDefinitions().getValue())) {
>           useFromStageEnvironmentYaml.setInfrastructureDefinitions(environmentYaml.getInfrastructureDefinitions());
>         } else if (ParameterField.isNotNull(environmentYaml.getInfrastructureDefinition())) {
> ```

What happens if this is the setup of the user
```
# s1
environment:
	environmentRef: e1
	infrastructureDefinition: 
		ref: i1
# s2
environment:
	useFromStage:
			stage: s1
	infrastructureDefinition: <+input>
```

Previously we would be using "i1" infra, now we would fail because of ```else if (ParameterField.isNotNull(environmentYaml.getInfrastructureDefinition()))``` ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56319)* status: Some of the checks are too old. 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56319)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 494 at r4](https://reviewable.io/reviews/harness/harness-core/56319#-NlRmeGUBP9dfC-vkFo9:-NlRmeGUBP9dfC-vkFoA:b-15qhuw) ([raw file](https://github.com/harness/harness-core/blob/821b2af736dfbda7db6dd7a341276e708bd42a6b/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L494)):*
> ```Java
>                 || (environmentYaml.getInfrastructureDefinition().isExpression()
>                     && NGExpressionUtils.isStrictlyExpressionField(
>                         environmentYaml.getInfrastructureDefinition().getExpressionValue())))) {
> ```

can we extract this logic out as a method?
```
(environmentYaml.getInfrastructureDefinition() != null)
            && ((environmentYaml.getInfrastructureDefinition().getValue() != null)
                || (environmentYaml.getInfrastructureDefinition().isExpression()
                    && NGExpressionUtils.isStrictlyExpressionField(
                        environmentYaml.getInfrastructureDefinition().getExpressionValue()
```

**Comment by lovish1999** [comment]
trigger ut5

**Comment by lovish1999** [comment]
trigger ut6

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger ut8

**Review by tchaurasiya — APPROVED** [review]

**Comment by lovish1999** [comment]
trigger ut8

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger ut5

**Comment by lovish1999** [comment]
trigger ut6

**Comment by lovish1999** [comment]
trigger review

**Comment by lovish1999** [comment]
trigger ut5

**Comment by lovish1999** [comment]
trigger ut5

**Pull request merged**
