### PR TITLE
[feat]: [CDS-83395]: Support Remote Environment in Custom Stage

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Adding support for remote environment in custom stage. 
1. Passing in envGitBranch via plan creator. 
2. Using Git Calls in custom stage variable creator and environment step while fetching environment entity. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54967)

### CODE REVIEW

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54967)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/beans/CustomStageEnvironmentStepParameters.java` line 38 at r1](https://reviewable.io/reviews/harness/harness-core/54967#-NiJOCnoAwrp4LVPfz2N:-NiJOCnoAwrp4LVPfz2O:b-1uktye) ([raw file](https://github.com/harness/harness-core/blob/63104f4cb6db1012ee910c21a084eecf9dd1c7dd/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/environment/helper/beans/CustomStageEnvironmentStepParameters.java#L38)):*
> ```Java
>   @Override
>   public List<String> excludeKeysFromStepInputs() {
>     return new LinkedList<>(Arrays.asList("envInputs", "childrenNodeIds", "envGitBranch"));
> ```

io.harness.cdng.service.steps.constants.ServiceStepV3Constants#ENV_GIT_BRANCH
Lets use this for constant?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/CustomStageVariableCreator.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/54967#-NiJOe30A4jodmEbX7Gh:-NiJOe319XPnyoo3hYvT:b-qgwibz) ([raw file](https://github.com/harness/harness-core/blob/63104f4cb6db1012ee910c21a084eecf9dd1c7dd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/CustomStageVariableCreator.java#L85)):*
> ```Java
>       VariableCreationContext ctx, CustomStageNode customStageNode) {
>     // set source principal to get git entities
>     SecurityContextBuilder.setContext(new ServicePrincipal(AuthorizationServiceHeader.NG_MANAGER.getServiceId()));
> ```

do we need to set manually if we're using the source guard?

**Review by hingerabhinav — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54967#-:-NiJW9A4AgQyrvWfJ-r2:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/CustomStageVariableCreator.java` line 85 at r1](https://reviewable.io/reviews/harness/harness-core/54967#-NiJOe30A4jodmEbX7Gh:-NiJVz3O-fWnAiqbXnrY:b-6merrn) ([raw file](https://github.com/harness/harness-core/blob/63104f4cb6db1012ee910c21a084eecf9dd1c7dd/125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/CustomStageVariableCreator.java#L85)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

do we need to set manually if we're using the source guard?
</blockquote></details>

This is Done.

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54967)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger checkstylecodeformat

**Comment by lovish1999** [comment]
trigger commonchecks

**Comment by lovish1999** [comment]
trigger pmd

**Comment by lovish1999** [comment]
trigger codebasehash

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger gitleaks

**Review by tchaurasiya — APPROVED** [review]

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger review

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54967)* status: :shipit: complete! ✓

**Pull request merged**
