### PR TITLE
fix: [CDS-37806]: Fetch rollback artifact from lastSuccessfulWorkflowExecution to fix Current Deployment Status

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
JIRA - https://harness.atlassian.net/browse/CDS-37806

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34263)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/34263#-N4S6rd0Cp-uZ2UHb2eF:-N4VMUKH6sKH0rvGDMqd:b-496oxv) ([raw file](https://github.com/harness/harness-core/blob/f880529fa21affa6319bae58df8508dc09bc282b/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L157)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think this might not work when a workflow has multiple phases and each phase has a different service deployed. There, we might not which artifact to choose from from the list of artifacts
</blockquote></details>

For that, I can put a filter by ServiceId on the artifacts, and choose the one which matches the serviceId of the instancesInDb

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 126 at r1](https://reviewable.io/reviews/harness/harness-core/34263#-N4S6OSM8ma2rSR_sk7F:-N4X25oJE5BfMh2551QI:b1xrf6s) ([raw file](https://github.com/harness/harness-core/blob/f880529fa21affa6319bae58df8508dc09bc282b/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L126)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

instead of defining new method here, can we override ```getDeploymentSummaryForInstanceCreation``` from the base class ?
</blockquote></details>

Yes, we can override, will make the changes

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/34263#-N4S6rd0Cp-uZ2UHb2eF:-N4cTYBXAd5Uub2OKBlG:bo0mgcp) ([raw file](https://github.com/harness/harness-core/blob/f880529fa21affa6319bae58df8508dc09bc282b/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L157)):*
<details><summary><i>Previously, RishabhGupta34 (Rishabh Gupta) wrote…</i></summary><blockquote>

For that, I can put a filter by ServiceId on the artifacts, and choose the one which matches the serviceId of the instancesInDb
</blockquote></details>

Have made the changes for the same, please take a look.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34263)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/34263#-N4cUDT1C1p5d2nOJFTn:-N4cUDT1C1p5d2nOJFTo:b-lbia3o) ([raw file](https://github.com/harness/harness-core/blob/58e0a7e5cada0a1c21d5b3ee6137dc07a54c1de9/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java#L283)):*
> ```Java
>       List<Instance> instancesInDb, DeploymentSummary deploymentSummary) {
>     try {
>       if (!instancesInDb.isEmpty()) {
> ```

Lets use EmptyPredicate.isNotEmpty(..), it is null safe 
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/34263#-N4cU_Jq0sLQsUtMkY1l:-N4cU_Jq0sLQsUtMkY1m:bu1rysg) ([raw file](https://github.com/harness/harness-core/blob/58e0a7e5cada0a1c21d5b3ee6137dc07a54c1de9/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java#L292)):*
> ```Java
>           lastArtifacts = lastArtifacts.stream()
>                               .filter(a -> a.getServiceIds().contains(instancesInDb.get(0).getServiceId()))
>                               .collect(Collectors.toList());
> ```

We can use findFirst()

https://stackoverflow.com/questions/23696317/find-first-element-by-predicategg

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java` line 283 at r3](https://reviewable.io/reviews/harness/harness-core/34263#-N4cUDT1C1p5d2nOJFTn:-N4fiWXsCamzYfQ27EN3:b2o13mc) ([raw file](https://github.com/harness/harness-core/blob/58e0a7e5cada0a1c21d5b3ee6137dc07a54c1de9/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java#L283)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets use EmptyPredicate.isNotEmpty(..), it is null safe 
</blockquote></details>

Thanks, have made the change

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/34263#-N4cU_Jq0sLQsUtMkY1l:-N4fi_QP7XzRe498ekcl:b-iry7x8) ([raw file](https://github.com/harness/harness-core/blob/58e0a7e5cada0a1c21d5b3ee6137dc07a54c1de9/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java#L292)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We can use findFirst()

https://stackoverflow.com/questions/23696317/find-first-element-by-predicategg
</blockquote></details>

Done, thanks

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34263)* status: :shipit: complete! ✓

**Comment by RishabhGupta34** [comment]
trigger message_metadata

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r6, 9 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34263)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 131 at r7](https://reviewable.io/reviews/harness/harness-core/34263#-N4lfaJg7OrW7U1LLmn-:-N4lfaJg7OrW7U1LLmn0:bie370d) ([raw file](https://github.com/harness/harness-core/blob/92150f9f1e5c8ed4bc860dba32b3a94ddfd9d1f6/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L131)):*
> ```Java
>     if (rollback) {
>       if (isNull(newDeploymentSummary.getRollbackArtifactId())) {
>         log.info("Couldn't find a rollback artifact, so no new instances will be created.");
> ```

lets put this as a warning
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java` line 146 at r7](https://reviewable.io/reviews/harness/harness-core/34263#-N4lhI8QC78bRmMbR8tp:-N4lhI8QC78bRmMbR8tq:bcn9c1s) ([raw file](https://github.com/harness/harness-core/blob/92150f9f1e5c8ed4bc860dba32b3a94ddfd9d1f6/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java#L146)):*
> ```Java
>   }
> 
>   private DeploymentSummary setValuesToDeploymentSummary(String stateExecutionInstanceId,
> ```

Its better to just pass 1 Artifact here as function argument. If rollback, pass ```rollbackArtifact``` else  pass the regular artifact
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java` line 256 at r7](https://reviewable.io/reviews/harness/harness-core/34263#-N4ljJ9h3KUiQGQ2SJtA:-N4ljJ9h3KUiQGQ2SJtB:bd0uefu) ([raw file](https://github.com/harness/harness-core/blob/92150f9f1e5c8ed4bc860dba32b3a94ddfd9d1f6/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java#L256)):*
> ```Java
>         }
> 
>         Artifact rollbackArtifact = workflowStandardParamsExtensionService.getRollbackArtifactForService(
> ```

This has multiple DB calls. We should call this only when its a rollback

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java` line 256 at r7](https://reviewable.io/reviews/harness/harness-core/34263#-N4ljJ9h3KUiQGQ2SJtA:-N4r_1tC69DLgazOqL4Y:b7mfrb9) ([raw file](https://github.com/harness/harness-core/blob/92150f9f1e5c8ed4bc860dba32b3a94ddfd9d1f6/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHelper.java#L256)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

This has multiple DB calls. We should call this only when its a rollback
</blockquote></details>

Yeah, let me do that

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java` line 146 at r7](https://reviewable.io/reviews/harness/harness-core/34263#-N4lhI8QC78bRmMbR8tp:-N4rZZUr0G4vTXX8S__z:bjoyej1) ([raw file](https://github.com/harness/harness-core/blob/92150f9f1e5c8ed4bc860dba32b3a94ddfd9d1f6/400-rest/src/main/java/software/wings/service/impl/instance/InstanceHandler.java#L146)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Its better to just pass 1 Artifact here as function argument. If rollback, pass ```rollbackArtifact``` else  pass the regular artifact
</blockquote></details>

This code is being used by other swimlanes as well, so we shouldn't modify the artifact value, that's why I added `rollbackArtifact` variables in the deploymentSummary struct

**Comment by RishabhGupta34** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 131 at r7](https://reviewable.io/reviews/harness/harness-core/34263#-N4lfaJg7OrW7U1LLmn-:-N4r_9BCDPJHRMDgo9Qw:bb74ce2) ([raw file](https://github.com/harness/harness-core/blob/92150f9f1e5c8ed4bc860dba32b3a94ddfd9d1f6/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L131)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets put this as a warning
</blockquote></details>

Sure

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 13 files at r6, 1 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34263)* status: :shipit: complete! ✓

**Pull request closed without merging**
