### PR TITLE
feat:[CDS-70387]: Define negative status priority inside the fork state

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- **QA Hotfix**
- The negative statuses ABORTED, REJECTED, and EXPIRED have higher priority over the FAILED one when inside a parallel execution and the FF is enabled.
- The enhancement is behind a feature flag.

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49738)

### CODE REVIEW

**Comment by Fernando-Dourado** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/ForkState.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/49738#-NYrvtJ8-W4tGb_LCLaD:-NYrvtJ8-W4tGb_LCLaE:b-50h9eq) ([raw file](https://github.com/harness/harness-core/blob/85356432a50faf8de9a90af0db14fbaf4944fab6/400-rest/src/main/java/software/wings/sm/states/ForkState.java#L138)):*
> ```Java
>       ExecutionStatus executionStatus = ((ExecutionStatusResponseData) status).getExecutionStatus();
>       if (executionStatus != ExecutionStatus.SUCCESS) {
>         if (isRejectStatusPriority(context, executionStatus)) {
> ```

Does this give priority to rejected status ? what is the first object is EXPIRED and the other one is EXPIRED ?

**Comment by Fernando-Dourado** [comment]
> _[`400-rest/src/main/java/software/wings/sm/states/ForkState.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/49738#-NYrvtJ8-W4tGb_LCLaD:-NYrvtJ8-W4tGb_LCLaE:b-50h9eq) ([raw file](https://github.com/harness/harness-core/blob/85356432a50faf8de9a90af0db14fbaf4944fab6/400-rest/src/main/java/software/wings/sm/states/ForkState.java#L138)):_
> 
> > ```java
> >       ExecutionStatus executionStatus = ((ExecutionStatusResponseData) status).getExecutionStatus();
> >       if (executionStatus != ExecutionStatus.SUCCESS) {
> >         if (isRejectStatusPriority(context, executionStatus)) {
> > ```
> 
> Does this give priority to rejected status ? what is the first object is EXPIRED and the other one is EXPIRED ?

The three negative status has the same priority, and I forgot to rename the method `isRejectStatusPriority` to provide a better understanding of the case.

My guess is you are asking about EXPIRED and REJECTED. Is not expected to have the three negative statuses coming at the same time, however, if that happens the first priority negative status will be the final status of the fork state.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by rafaelmart1ns — APPROVED** [review]

**Comment by Fernando-Dourado** [comment]
trigger uts

**Review by franciscojuniorharness — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49738)* status: 4 file(s) to review.

**Comment by Fernando-Dourado** [comment]
We miss the qa branch cut, now the change goes in the next planned release.

**Pull request closed without merging**
