### PR TITLE
[feat]:[pl-27462]: Use parentConnectorRef and parentRepoName 

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Use parentConnectorRef and parentRepoName to resolve parentEntityRepoURL

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36446)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36446)

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 217 at r1](https://reviewable.io/reviews/harness/harness-core/36446#-N9egmcB7m_oxv1gUyRU:-N9egmcB7m_oxv1gUyRV:blajwqi) ([raw file](https://github.com/harness/harness-core/blob/adf1fbb8f2258fc1da40e51f5ab928a3740df02e/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L217)):*
> ```Java
>   }
> 
>   public String getParentEntityRepoUrl(Scope scope, GitEntityInfo gitEntityInfo) {
> ```

It shouldn't take in gitEntityInfo. It should just take arguments that are required. Why would it rely on gitEntityInfo.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 217 at r1](https://reviewable.io/reviews/harness/harness-core/36446#-N9egxH-1IJ7eRM4ohtB:-N9egxH-1IJ7eRM4ohtC:bbuq08i) ([raw file](https://github.com/harness/harness-core/blob/adf1fbb8f2258fc1da40e51f5ab928a3740df02e/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L217)):*
> ```Java
>   }
> 
>   public String getParentEntityRepoUrl(Scope scope, GitEntityInfo gitEntityInfo) {
> ```

Also, the naming is inappropriate. It is basically just getting a repoURL, so it doesn't matter if its "parentEntity" or anything else.

We actually don't need this method at all. We can directly integrate scmGitSyncHelper method call wherever we want to use and it will either throw error or return correct result to us.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 207 at r1](https://reviewable.io/reviews/harness/harness-core/36446#-N9ehFJA6k_qg7xAEPEe:-N9ehFJB5DsMB6yITUCo:bg8ntrv) ([raw file](https://github.com/harness/harness-core/blob/adf1fbb8f2258fc1da40e51f5ab928a3740df02e/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L207)):*
> ```Java
>   }
> 
>   public String getWorkingBranch(Scope scope, String entityRepoURL) {
> ```

Getting a working branch isn't responsibility of gitAwareEntityHelper helper class if you think about it. It basically just fetches branch based on logic on context values.

This class is more of a helper class where we do operation on remote entities

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/36446#-N9ehWjl59KdiuGzkC-x:-N9ehWjl59KdiuGzkC-y:b-ez96oy) ([raw file](https://github.com/harness/harness-core/blob/adf1fbb8f2258fc1da40e51f5ab928a3740df02e/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java#L107)):*
> ```Java
>   }
> 
>   //  public String getWorkingBranch(Scope scope, String entityRepoURL) {
> ```

Lets keep this logic here only and not move to git aware entity helper. It is basically getting branch from context, thus its placed here.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/36446#-N9ehflfCLfeXkQpRGQ7:-N9ehflfCLfeXkQpRGQ8:b3y22xn) ([raw file](https://github.com/harness/harness-core/blob/adf1fbb8f2258fc1da40e51f5ab928a3740df02e/878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java#L208)):*
> ```Java
> 
>   public String getWorkingBranch(Scope scope, String entityRepoURL) {
>     GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
> ```

Also, just a pointer, if both connectorRef and reponame is empty, that means its not a remote entity and then we don't need to get the repo url or do any kind of matching. Then, it works as INLINE.

**Pull request closed without merging**
