### PR TITLE
[fix]: [CDS-53960]: Add config files javax validations for config file step v2

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Add config files javax validations for config file step v2
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45959)

### CODE REVIEW

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45959#-:-NS2YaaU49t-Gp_gFyVD:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/45959#-NS2TwMPCgziXSvKD2zs:-NS2TwMQ4ZUE1j0z0f1D:bacq8e9) ([raw file](https://github.com/harness/harness-core/blob/3984c1eb2a6a89c877cd3be2791688c86e8d8686/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L77)):*
> ```Java
>   @Inject private PipelineRbacHelper pipelineRbacHelper;
>   @Inject private ServiceStepsHelper serviceStepsHelper;
>   private final ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
> ```

If we are not using the factory in the below code we can reference only
 Validator validator = Validation.buildDefaultValidatorFactory().getValidator();



_Code quote:_
```Java
Validation.buildDefaultValidatorFactory()
```
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/45959#-NS2WRoE1iLBQ_0Xhhd1:-NS2WRoG44gbLiVjOTOm:bnl4o8e) ([raw file](https://github.com/harness/harness-core/blob/3984c1eb2a6a89c877cd3be2791688c86e8d8686/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L154)):*
> ```Java
>   }
> 
>   private void validateOrThrow(List<ConfigFileWrapper> configFiles) {
> ```

Minor - what I suggest here is making validateOrThrow more generic and moving from this class and supplying configFileValidatorDTO and method argument ( validateOrThrow(new ConfigFileValidatorDTO(configFiles)); ). Validator can be supplied as method param or injected in another helper class where the method will be moved. It's minor and up to you. 

private <T> void validateOrThrow(T configFileValidatorDTO) {
    Set<ConstraintViolation<T>> violations = validator.validate(configFileValidatorDTO);

    if (EmptyPredicate.isEmpty(violations)) {
      return;
    }

......


}



_Code quote:_
```Java
ConfigFileValidatorDTO
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/45959#-NS2YMkcDfv_4oKvq4kQ:-NS2YMkcDfv_4oKvq4kR:bp1b5e5) ([raw file](https://github.com/harness/harness-core/blob/3984c1eb2a6a89c877cd3be2791688c86e8d8686/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L96)):*
> ```Java
>   }
> 
>   private void validateOrThrow(NGEnvironmentConfig ngEnvironmentConfig) {
> ```

Reuse the above generic method

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45959)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45959#-:-NS5_j5i1SKXLjv8beaV:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/45959#-NS2TwMPCgziXSvKD2zs:-NS5cSVR03iS8q4-lpGU:b-c9u71v) ([raw file](https://github.com/harness/harness-core/blob/3984c1eb2a6a89c877cd3be2791688c86e8d8686/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L77)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

If we are not using the factory in the below code we can reference only
 Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
</blockquote></details>

I have created a new class Javax validator to help with validations

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/45959#-NS2WRoE1iLBQ_0Xhhd1:-NS5cX0PEDiVHqDJiI5g:bl2hl9u) ([raw file](https://github.com/harness/harness-core/blob/3984c1eb2a6a89c877cd3be2791688c86e8d8686/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/configfile/steps/ConfigFilesStepV2.java#L154)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - what I suggest here is making validateOrThrow more generic and moving from this class and supplying configFileValidatorDTO and method argument ( validateOrThrow(new ConfigFileValidatorDTO(configFiles)); ). Validator can be supplied as method param or injected in another helper class where the method will be moved. It's minor and up to you. 

private <T> void validateOrThrow(T configFileValidatorDTO) {
    Set<ConstraintViolation<T>> violations = validator.validate(configFileValidatorDTO);

    if (EmptyPredicate.isEmpty(violations)) {
      return;
    }

......


}

</blockquote></details>

Yes, moved to a generic class

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45959#-:-NS5d0NpEhhSFV8l1N0y:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45959)* status: :shipit: complete! ✓

**Pull request merged**
