### PR TITLE
feat: [CDS-47218]: support skipping terraform refresh command

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
Terraform steps: Plan; Apply Inline;  Destroy Inline, Destroy Inherit From Apply, Rollback will have a new yaml property: skipRefreshCommand. Based on this property we are skipping terraform refresh command. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44756)

### CODE REVIEW

**Comment by vlica-harness** [comment]
trigger ft1

**Comment by vlica-harness** [comment]
trigger ft2

**Review by alebuh — DISMISSED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44756)* status: 33 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/44756#-NPv9RvaDfjoZrVfelbk:-NPv9RvaDfjoZrVfelbl:b157enx) ([raw file](https://github.com/harness/harness-core/blob/54f47aa14e00908c762076c29e5079f87d108b14/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java#L205)):*
> ```Java
>             .isTerraformCloudCli(isTerraformCloudCli)
>             .skipTerraformRefresh(
>                 !ParameterField.isNull(skipTerraformRefreshCommand) && skipTerraformRefreshCommand.getValue())
> ```

just a suggestion: you can use the helper method here instead of checking if the field is null ParameterFieldHelper.getBooleanParameterFieldValue . The same goes for other places where you check if this field is null

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44756)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/44756#-NPvvwRIAWYbYqFDBmI3:-NPvvwRIAWYbYqFDBmI4:b-o05og0) ([raw file](https://github.com/harness/harness-core/blob/54f47aa14e00908c762076c29e5079f87d108b14/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java#L169)):*
> ```Java
>     ParameterField<Boolean> skipTerraformRefreshCommand = parameters.getConfiguration().getIsSkipTerraformRefresh();
> 
>     if (!ParameterField.isNull(skipTerraformRefreshCommand) && skipTerraformRefreshCommand.getValue()) {
> ```

we can obtain it once and use in both places: "!ParameterField.isNull(skipTerraformRefreshCommand) && skipTerraformRefreshCommand.getValue()"
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/steps/rolllback/TerraformRollbackStep.java` line 186 at r1](https://reviewable.io/reviews/harness/harness-core/44756#-NPvwqW3COPymdfKotvV:-NPvwqW3COPymdfKotvW:buo9nmt) ([raw file](https://github.com/harness/harness-core/blob/54f47aa14e00908c762076c29e5079f87d108b14/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/steps/rolllback/TerraformRollbackStep.java#L186)):*
> ```Java
>       ParameterField<Boolean> skipTerraformRefreshCommand = stepParametersSpec.getSkipRefreshCommand();
> 
>       if (!ParameterField.isNull(skipTerraformRefreshCommand) && skipTerraformRefreshCommand.getValue()) {
> ```

Same here

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44756)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java` line 205 at r1](https://reviewable.io/reviews/harness/harness-core/44756#-NPv9RvaDfjoZrVfelbk:-NPw89sH-G7ovWavBtS7:bgz4uj2) ([raw file](https://github.com/harness/harness-core/blob/54f47aa14e00908c762076c29e5079f87d108b14/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformApplyStep.java#L205)):*
<details><summary><i>Previously, alebuh (Aleksa Buha) wrote…</i></summary><blockquote>

just a suggestion: you can use the helper method here instead of checking if the field is null ParameterFieldHelper.getBooleanParameterFieldValue . The same goes for other places where you check if this field is null
</blockquote></details>

done, thank you
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java` line 169 at r1](https://reviewable.io/reviews/harness/harness-core/44756#-NPvvwRIAWYbYqFDBmI3:-NPw8B8Y09DNhLaLc3H0:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/54f47aa14e00908c762076c29e5079f87d108b14/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java#L169)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

we can obtain it once and use in both places: "!ParameterField.isNull(skipTerraformRefreshCommand) && skipTerraformRefreshCommand.getValue()"
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/steps/rolllback/TerraformRollbackStep.java` line 186 at r1](https://reviewable.io/reviews/harness/harness-core/44756#-NPvwqW3COPymdfKotvV:-NPw8DgC5vobCSBXPCuP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/54f47aa14e00908c762076c29e5079f87d108b14/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/steps/rolllback/TerraformRollbackStep.java#L186)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

done

**Review by alebuh — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44756)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44756)* status: :shipit: complete! ✓

**Pull request merged**
