### PR TITLE
feat: [CDS-70668]: Fetch the FF before starting of the execution and store in the executionMetadata

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49741)

### CODE REVIEW

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49741)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/49741#-NYvgY5j3Ch8V4LulhJq:-NYvgY5j3Ch8V4LulhJr:b-oqlh5f) ([raw file](https://github.com/harness/harness-core/blob/148d0988fab207cedcfcd79ea350862e8648084e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L153)):*
> ```Java
>       enabledFeatureFlags.add(EngineExpressionEvaluator.PIE_EXECUTION_JSON_SUPPORT);
>     }
>     if (ambiance.getMetadata().getFeatureFlagToValueMapMap().get(FeatureName.PIE_EXPRESSION_CONCATENATION.toString())) {
> ```

could you please create a function in ambianceUtils for doing so?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/49741#-NYvgY5j3Ch8V4LulhJq:-NYvgnWi--LL8Gjdc7Jw:b-vvwvel) ([raw file](https://github.com/harness/harness-core/blob/148d0988fab207cedcfcd79ea350862e8648084e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L153)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

could you please create a function in ambianceUtils for doing so?
</blockquote></details>

Also, add a check that if field is present.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49741)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/49741#-NYvgY5j3Ch8V4LulhJq:-NYvldMRCfjRY0cPZqeG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/148d0988fab207cedcfcd79ea350862e8648084e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L153)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Also, add a check that if field is present.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger ut0

**Comment by shalini-agr** [comment]
trigger ut0

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49741)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — DISMISSED** [review]

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/49741#-NZ0FHxdCqU7r8NM0wAo:-NZ0FHxdCqU7r8NM0wAp:b-ork92f) ([raw file](https://github.com/harness/harness-core/blob/b8c0fd142060f25ab57a649079e38b76015d4d23/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L156)):*
> ```Java
>       enabledFeatureFlags.add(FeatureName.PIE_EXPRESSION_CONCATENATION.name());
>     }
>     if (AmbianceUtils.isFFEnabled(ambiance, FeatureName.PIE_EXPRESSION_DISABLE_COMPLEX_JSON_SUPPORT.name())) {
> ```

For one release, I think we will need to keep both pmsFeatureFlagService and this AmbianceUtils to have backward compatibility. In next release we can remove.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49741)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 156 at r4](https://reviewable.io/reviews/harness/harness-core/49741#-NZ0FHxdCqU7r8NM0wAo:-NZ0KJ4BDISmbjKXCZ6u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b8c0fd142060f25ab57a649079e38b76015d4d23/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L156)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

For one release, I think we will need to keep both pmsFeatureFlagService and this AmbianceUtils to have backward compatibility. In next release we can remove.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49741)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
