### PR TITLE
feat: [PL-40205]: Add Login and Authentication Metrics

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR adds metrics to track the number of user logins based on the authentication type and the account.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50979)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 528 at r1](https://reviewable.io/reviews/harness/harness-core/50979#-NaxKV0TClt6hn4ap5Vq:-NaxKV0TClt6hn4ap5Vr:bdfzil8) ([raw file](https://github.com/harness/harness-core/blob/51ee63c9bf59365c01973a0b0c5f3835a7ea0f39/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L528)):*
> ```Java
>   }
> 
>   private String getAccountIdFromUserCredential(User user, String... credentials) {
> ```

What is purpose of this method?

**Comment by piyush-harness** [comment]
*[`960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/50979#-NaxLm1B3avfZuzC1qkM:-NaxLm1C3H92_jvEHwv5:b-ncdan0) ([raw file](https://github.com/harness/harness-core/blob/51ee63c9bf59365c01973a0b0c5f3835a7ea0f39/960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java#L30)):*
> ```Java
>   @Inject private MetricService metricService;
> 
>   private void recordApiRequestMetric(String loginType, String loginSubType, String accountId, String metricName) {
> ```

Why not directly invoke this method?

**Review by raghuAtWings — APPROVED** [review]

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50979)* status: 7 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 528 at r1](https://reviewable.io/reviews/harness/harness-core/50979#-NaxKV0TClt6hn4ap5Vq:-Nay_KFh8tT1xDY5V7rL:b-yeqp9k) ([raw file](https://github.com/harness/harness-core/blob/51ee63c9bf59365c01973a0b0c5f3835a7ea0f39/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L528)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

What is purpose of this method? 
</blockquote></details>

I added this because now User can be null and wanted to return Null for accountId if the user is null. In the other existing method User won't be null.
___
*[`960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/50979#-NaxLm1B3avfZuzC1qkM:-NayaJze5KnXZlt6V__w:b-lknjr5) ([raw file](https://github.com/harness/harness-core/blob/51ee63c9bf59365c01973a0b0c5f3835a7ea0f39/960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java#L30)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why not directly invoke this method?
</blockquote></details>

Didn't wanted to expose the internal Macros / Constants of this class like - LOGIN_SUCCESS_COUNT, LOGIN_FAILURE_COUNT or loginTypes. So tomorrow if we plan to change these constants then the changes will be only in this class and not at many different places.

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/oauth/OauthBasedAuthHandler.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-NayjZOj11DrwTml3TZ-:-NayjZOj11DrwTml3TZ0:bo73934) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/400-rest/src/main/java/software/wings/security/authentication/oauth/OauthBasedAuthHandler.java#L128)):*
> ```Java
>     }
> 
>     String domain = credentials[3];
> ```

This can possibly cause IndexOutOfBound, above we are checking `length != 3` , we should check `length < 4 or length != 4` for this to work fine, thanks



_Code quote:_
```Java
String domain = credentials[3];
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 552 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-Nayk3-x0fnAojg40yxl:-Nayk3-x0fnAojg40yxm:bxj0lku) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L552)):*
> ```Java
>       Map<String, String> params = getRedirectParamsForSsoRedirection(jwtToken, encodedApiUrl);
>       URI redirectUrl = authenticationUtils.buildAbsoluteUrl("/saml.html", params, accountId);
>       loginApiMetricsService.recordLoginRequestSuccessSaml(accountId);
> ```

minor: More of a question - What is the extra latency getting added as part of recording this metrics? because it can introduce latency in login, and would lead to degraded experience for user login to Harness, thanks



_Code quote:_
```Java
loginApiMetricsService.recordLoginRequestSuccessSaml(accountId);
```

**Comment by pbarapatre10** [comment]
*[`960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-Naykx9oE4LVvGrZIK2V:-Naykx9oE4LVvGrZIK2W:b3iricu) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java#L65)):*
> ```Java
> 
>   public void recordLoginRequestFailurePassword(String accountId) {
>     recordApiRequestMetric("PASSWORD", "NONE", accountId, LOGIN_SUCCESS_COUNT);
> ```

typo or missed change, should be LOGIN_FAILURE_COUNT, thanks



_Code quote:_
```Java
, LOGIN_SUCCESS_COUNT
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50979)* status: 7 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50979)* status: 7 file(s) to review. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 552 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-Nayk3-x0fnAojg40yxl:-NayvbIu9SWxFQUsovQb:be4oeq9) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L552)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: More of a question - What is the extra latency getting added as part of recording this metrics? because it can introduce latency in login, and would lead to degraded experience for user login to Harness, thanks
</blockquote></details>

We are not pushing the metrics as part of this call. This will only record it locally in memory and thus the latency is very minimal. 
___
*[`400-rest/src/main/java/software/wings/security/authentication/oauth/OauthBasedAuthHandler.java` line 128 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-NayjZOj11DrwTml3TZ-:-NayuhmnAIwydCbbsoZj:b24l7v5) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/400-rest/src/main/java/software/wings/security/authentication/oauth/OauthBasedAuthHandler.java#L128)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

This can possibly cause IndexOutOfBound, above we are checking `length != 3` , we should check `length < 4 or length != 4` for this to work fine, thanks
</blockquote></details>

Ah yes, thanks!
___
*[`960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-Naykx9oE4LVvGrZIK2V:-NayvWZY7TPJqU6lo9Bh:b-x3gtb4) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/960-api-services/src/main/java/io/harness/metrics/impl/LoginApiMetricsServiceImpl.java#L65)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

typo or missed change, should be LOGIN_FAILURE_COUNT, thanks
</blockquote></details>

Thanks for catching this.

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger ut4, ut7

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 552 at r2](https://reviewable.io/reviews/harness/harness-core/50979#-Nayk3-x0fnAojg40yxl:-NazyQdd9EkMxrTwH9l9:b-7aitbc) ([raw file](https://github.com/harness/harness-core/blob/7c7a8cd575942991d6010402f7bbf36d0dda6efd/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L552)):*
<details><summary><i>Previously, Raghav-Murali wrote…</i></summary><blockquote>

We are not pushing the metrics as part of this call. This will only record it locally in memory and thus the latency is very minimal. 
</blockquote></details>

Thanks for clarifying!

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50979)* status: 7 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger ut7

**Pull request merged**
