### PR TITLE
fix: [CDS-47289]: safeguard on setting null in update operations of artifacts

### PR DESCRIPTION
**Pull request by inderschera**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40618)

### CODE REVIEW

**Comment by inderschera** [comment]
trigger ti1

**Comment by inderschera** [comment]
trigger messagecheck

**Review by Fernando-Dourado — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40618)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/artifact/ArtifactServiceImpl.java` line 430 at r1](https://reviewable.io/reviews/harness/harness-core/40618#-NHioFFD7tfF3o-iBRcl:-NHioFFD7tfF3o-iBRcm:bcj932v) ([raw file](https://github.com/harness/harness-core/blob/b4b6f92d8390c926594bd492678f69ede406d026/400-rest/src/main/java/software/wings/service/impl/artifact/ArtifactServiceImpl.java#L430)):*
> ```Java
>                                 .filter(ArtifactKeys.accountId, accountId);
>     UpdateOperations<Artifact> ops = wingsPersistence.createUpdateOperations(Artifact.class);
>     if (newMetadata != null) {
> ```

Please, add a unit test to cover this scenario.
___
*[`400-rest/src/main/java/software/wings/service/impl/artifact/ArtifactServiceImpl.java` line 433 at r1](https://reviewable.io/reviews/harness/harness-core/40618#-NHioLlF8t5hLAB_jcb3:-NHioLlF8t5hLAB_jcb4:bcj932v) ([raw file](https://github.com/harness/harness-core/blob/b4b6f92d8390c926594bd492678f69ede406d026/400-rest/src/main/java/software/wings/service/impl/artifact/ArtifactServiceImpl.java#L433)):*
> ```Java
>       ops.set(ArtifactKeys.metadata, newMetadata);
>     }
>     if (revision != null) {
> ```

Please, add a unit test to cover this scenario.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40618)* status: :shipit: complete! ✓

**Pull request merged**
