### PR TITLE
[feat]: [CDS-37442]: Added OPA response along with merged yaml

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33192)

### CODE REVIEW

**Review by inderschera — COMMENTED** [review]
> Reviewed 13 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33192)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33192)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/33192#-N33O99nB6MSO_XwWDll:-N34XuBs3tMGtz5wr57v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5b8e99d54e21621529510a788d9b4c96fbe69fd/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L245)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Need to send the resolved yaml with refs as expanded json. Let's discuss.
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java` line 265 at r1](https://reviewable.io/reviews/harness/harness-core/33192#-N33OHD7EzOrnbjJTTmg:-N34Xvy4-HswaIBRdslI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c5b8e99d54e21621529510a788d9b4c96fbe69fd/800-pipeline-service/src/main/java/io/harness/pms/triggers/TriggerExecutionHelper.java#L265)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

same as ExecutionHelper
</blockquote></details>

Done.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33192#-:-N34bfHDE3pfv2J1wNOP:bnfp4nl)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33192)* status: :shipit: complete! ✓

**Pull request merged**
