### PR TITLE
[feat]: [PL-27544]: Adds implementation for secret resource using spec first

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36583)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 19 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 16 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36583)

**Comment by ashishsanodia-harness** [comment]
trigger pmd

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger checkstyle

**Comment by ashishsanodia-harness** [comment]
trigger compile

**Comment by ashishsanodia-harness** [comment]
trigger ft1

**Comment by ashishsanodia-harness** [comment]
trigger ft2

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/AccountSecretApiImpl.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGcJCJ2PqZpUASkr2G:-NBGcJCJ2PqZpUASkr2H:bru486j) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/AccountSecretApiImpl.java#L46)):*
> ```Java
>   public Response createAccountScopedSecret(SecretRequest body, String account, Boolean privateSecret) {
>     if (nonNull(body.getSecret().getOrg()) || nonNull(body.getSecret().getProject())) {
>       throw new InvalidRequestException("Invalid request, scope in payload and params do not match.", USER);
> ```

The error message looks inappropriate. Probably it should be something like: "Account scoped request is having non null org or project" or something similar.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/AccountSecretApiImpl.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGcJCJ2PqZpUASkr2G:-NBGcXSoBnUg3v7bCt-L:bh1y1im) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/AccountSecretApiImpl.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The error message looks inappropriate. Probably it should be something like: "Account scoped request is having non null org or project" or something similar.
</blockquote></details>

Basically we are doing only null checks but our error message conveys that we are comparing some params

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/OrgSecretApiImpl.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGciIk0l7aIEo6TN81:-NBGciIk0l7aIEo6TN82:bcim8uv) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/OrgSecretApiImpl.java#L47)):*
> ```Java
>   public Response createOrgScopedSecret(SecretRequest body, String org, String account, Boolean privateSecret) {
>     if (!Objects.equals(org, body.getSecret().getOrg()) || nonNull(body.getSecret().getProject())) {
>       throw new InvalidRequestException("Invalid request, scope in payload and params do not match.", USER);
> ```

same here, that we should throw different exceptions for different use-cases. Or you can let me know if this is something that we agreed upon to send it like this, then its fine.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectSecretApiImpl.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGczAsELL3vTSP5YEB:-NBGczAsELL3vTSP5YEC:b3ch8uu) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectSecretApiImpl.java#L132)):*
> ```Java
>   }
> 
>   private Response deleteSecret(String org, String project, String secret, String account) {
> ```

Is it some kind of convention now that whenever any entity field is written, it will mean that its the id that it contains. eg: secret means secretIdentifier, org means orgIdentifier? currently it looks a lot misleading.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/SecretApiUtils.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGdpsa27t10_2AnxsK:-NBGdpsa27t10_2AnxsL:b-pod35n) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/SecretApiUtils.java#L64)):*
> ```Java
>   public static SecretDTOV2 toSecretDto(Secret secret) {
>     SecretDTOV2Builder secretDTOV2Builder = SecretDTOV2.builder()
>                                                 .identifier(secret.getSlug())
> ```

Is this again some new convention field "slug" in Secret?

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/AccountSecretApiImpl.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGcJCJ2PqZpUASkr2G:-NBwLc-p2i7phXwyIhrB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/AccountSecretApiImpl.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Basically we are doing only null checks but our error message conveys that we are comparing some params
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/OrgSecretApiImpl.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGciIk0l7aIEo6TN81:-NBwLfUD-sMdGsVfmxnk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/OrgSecretApiImpl.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same here, that we should throw different exceptions for different use-cases. Or you can let me know if this is something that we agreed upon to send it like this, then its fine.
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectSecretApiImpl.java` line 132 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGczAsELL3vTSP5YEB:-NBwLjWA-RNj4qBqmVAJ:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/ProjectSecretApiImpl.java#L132)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is it some kind of convention now that whenever any entity field is written, it will mean that its the id that it contains. eg: secret means secretIdentifier, org means orgIdentifier? currently it looks a lot misleading.
</blockquote></details>

Yes

**Comment by ashishsanodia-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/SecretApiUtils.java` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/36583#-NBGdpsa27t10_2AnxsK:-NBwLnBI6edEtw6fdTrT:b-rei73z) ([raw file](https://github.com/harness/harness-core/blob/d9821fd04a5e2502c7ff572b66335e8c7deda53f/120-ng-manager/src/main/java/io/harness/ng/core/remote/SecretApiUtils.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Is this again some new convention field "slug" in Secret?
</blockquote></details>

Yes this also something we are using

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 2 of 8 files at r2, 2 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36583)* status: 8 file(s) to review. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 2 of 8 files at r2, 1 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36583)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 48 of 48 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36583)* status: 48 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 48 of 48 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36583)* status: :shipit: complete! ✓

**Pull request merged**
