### PR TITLE
feat: [CDS-39985]: graphql appid required

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36045)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36045)

**Comment by lasdox** [comment]
Suggestion:
If user sends deployedService without appId we should let it go, because deployedService has higher cardinality.
Also, I think we should also stop that autopopulating appId behind the same FeatureFlag

**Comment by abhinav-harness** [comment]
@lasdox appid i think is required for rbac 
so if some api key doesnt have access to some app mongo layer is filtering it out. 
Thats why I tried to make appid a required field instead

**Comment by lasdox** [comment]
@abhinav-harness 

I checked the code and MongoPersistency auto populates the appIds that the user/apikey has access.
software/wings/dl/WingsMongoPersistence.java:373
If customer doesnt send appId filter, the RBAC is safe because of this.

Then the method called `addAppIdValidation` populates all appIds from the account into the query. This method seems to be only dirtying the query. I think we should remove it.

For customers that has lots of services by appId would have performance greatly improved by sending deployedServices because of the new index anurag created.

In my opinion it doesnt make sense to ask for appId if customer send deployedServices.

What do you think?

**Comment by abhinav-harness** [comment]
Yes @lasdox but only issue is deployed services can be a range as well as equals which will give problems to our indexes. 
Second thing - yes we can directly scan via deployed services (and use that index) but even in that case restricting to single app doesn't take away anything and gives us more time to analyze - WDYT ?

**Comment by lasdox** [comment]
@abhinav-harness 
When i said "deployedServices" what I did mean is "services"
I think the approach is good, we can continue with that.
Its just that services should be even more performatic and sending appId and service would be redundant.
But we can start with appId for now.

What do you think about removing the `addAppIdValidation` method?

**Comment by abhinav-harness** [comment]
Even if we remove appid validation auth layer will add it and queries will perform poorly. Why not restrict and mandate appId?

**Review by lasdox — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36045)* status: :shipit: complete! ✓

**Pull request merged**
