### PR TITLE
feat: [CDS-44654]: suport azure devops artifacts for azure webapps

### PR DESCRIPTION
**Pull request by vlica-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39152)

### CODE REVIEW

**Review by alebuh — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39152)* status: :shipit: complete! ✓

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39152)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsDownloadHelper.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/39152#-NG1JoqG7m2LMFP_PnaK:-NG1JoqG7m2LMFP_PnaL:baj48qv) ([raw file](https://github.com/harness/harness-core/blob/6fa7d5dcd793ba8b8acf0833b4b60374e2624271/960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsDownloadHelper.java#L139)):*
> ```Java
>     }
>     return url
>         + format("_apis/packaging/feeds/%s/maven/%s/%s/%s/%s/content?api-version=5.1-preview.1", feed, groupId,
> ```

I've noticed that for most of artifact sources, Service step is creating in metadata download url, don't we have same for Azure artifacts?
___
*[`960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java` line 400 at r1](https://reviewable.io/reviews/harness/harness-core/39152#-NG1KO__8hekNW1ceUCO:-NG1KO__8hekNW1ceUCP:b-5x74db) ([raw file](https://github.com/harness/harness-core/blob/6fa7d5dcd793ba8b8acf0833b4b60374e2624271/960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsRegistryServiceImpl.java#L400)):*
> ```Java
> 
>       if (isBlank(packageId)) {
>         throw new InvalidRequestException(format("Failed to retrieve packageId for packageName: %s", packageName));
> ```

nit: ideally we should have something like hint + explanation + message, not sure how achievable is this

**Comment by vlica-harness** [comment]
*[`960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsDownloadHelper.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/39152#-NG1JoqG7m2LMFP_PnaK:-NG1Tyz0C9wUyLGeE-48:b-uinwjz) ([raw file](https://github.com/harness/harness-core/blob/6fa7d5dcd793ba8b8acf0833b4b60374e2624271/960-api-services/src/main/java/io/harness/artifacts/azureartifacts/service/AzureArtifactsDownloadHelper.java#L139)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I've noticed that for most of artifact sources, Service step is creating in metadata download url, don't we have same for Azure artifacts?
</blockquote></details>

no, I don't have this field in AzureArtifactsOutcome, and is not even coming in AzureArtifactsDelegateResponse when the artifact step is processed.

**Review by abosii-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39152)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39152#-:-NG1VtRF0gqd35syuM6U:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger codebasehash

**Comment by vlica-harness** [comment]
trigger codebasehash

**Pull request merged**
