### PR TITLE
feat: [cds-42721]: Notifications clients

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)

### CODE REVIEW

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)* status: 16 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-freeze/src/main/java/io/harness/freeze/FreezeNotificationTemplateRegistrar.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/38743#-NFIqjiP7mfZt6aauGWh:-NFIqjiP7mfZt6aauGWi:b1k0vy3) ([raw file](https://github.com/harness/harness-core/blob/35fbc3d52a82a6daf7cab8beb1270e65d14dbda1/125-freeze/src/main/java/io/harness/freeze/FreezeNotificationTemplateRegistrar.java#L42)):*
> ```Java
>           log.info("Registering {} with NotificationService", template);
>           try {
>             notificationClient.saveNotificationTemplate(Team.PIPELINE, template, true);
> ```

Team should be CDC right?

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)* status: 0 of 1 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-freeze/src/main/java/io/harness/freeze/FreezeNotificationTemplateRegistrar.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/38743#-NFIqjiP7mfZt6aauGWh:-NFIrUq98HjYojFD7lfS:b-tsvvyx) ([raw file](https://github.com/harness/harness-core/blob/35fbc3d52a82a6daf7cab8beb1270e65d14dbda1/125-freeze/src/main/java/io/harness/freeze/FreezeNotificationTemplateRegistrar.java#L42)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Team should be CDC right?
</blockquote></details>

actually I'm using pipeline owned notification channels ( Which was in common utils and was meant to used by others as well, but this framework while registering tries to match with the team as well, therefore when I was using CDC it was failing to register

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by abhinavmittal-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)* status: :shipit: complete! ✓

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38743)* status: :shipit: complete! ✓

**Pull request merged**
