### PR TITLE
fix: [CDS-85829]: fix check for conditional and looping operators in concatenated expression

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** We added a check in concatenated expressions that if there are conditional or looping operators (if, for, while, else, do) in the left substring of an expression then we won't replace it with the resolved value and let jexl resolve it.
But this change can break for some expressions which have these operator keywords in the left substring but not to be used as operators like `values-for-<+expr>`, here, for is just a word and not for looping operator, so, <+expr> should be concatenated by expr engine and not by jexl.

**Changes:** For these operators, we are also checking the operators should be followed by open paranthesis or curly bracket, to indicate that they want to be treated as operators and not normal words.

**Testing:** Tested customer scenario locally and added unit tests.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56212)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger smartchecks

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56212)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/56212#-NkZp-ef3o8ZicsDpDAB:-NkZp-ef3o8ZicsDpDAC:b-de9hlz) ([raw file](https://github.com/harness/harness-core/blob/04a411875aa2ca0fc4e4d364448c6c6c39a4878d/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L315)):*
> ```Java
>           String substring = leftSubString.substring(i, i + j);
>           if (jexlKeywordOperators.contains(substring)
>               && (i == 0 || !StringUtils.isAlphanumeric(String.valueOf(s.charAt(i - 1))))) {
> ```

lets convert to space check



_Code quote:_
```Java
!StringUtils.isAlphanumeric(String.valueOf(s.charAt(i - 1
```

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56212)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/56212#-NkZp-ef3o8ZicsDpDAB:-NkZqZ5lAxGjypVe-UDO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/04a411875aa2ca0fc4e4d364448c6c6c39a4878d/980-commons/src/main/java/io/harness/text/resolver/StringReplacer.java#L315)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets convert to space check
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56212)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
