### PR TITLE
fix: [CDS-24350]: Workflow variables now being validated

### PR DESCRIPTION
**Pull request by atharvatrivedi1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32220)

### CODE REVIEW

**Review by poojaSinghal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32220)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/trigger/TriggerServiceImpl.java, line 1418 at r1](https://reviewable.io/reviews/harness/harness-core/32220#-N-XDV4J3pESlA7rhv0a:-N-XDV4J3pESlA7rhv0b:b5j6pyh) ([raw file](https://github.com/harness/harness-core/blob/929e51c0dafe333dd390d5ad688a6d1e6178710b/400-rest/src/main/java/software/wings/service/impl/trigger/TriggerServiceImpl.java#L1418)):*
> ```Java
>   }
> 
>   private void validateWorkflowVariable(Map<String, String> workflowVariables, List<Variable> allowedValues) {
> ```

this will only work for workflows. @atharvatrivedi1 did you test for pipelines?

**Review by prabu-kr — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32220)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/trigger/TriggerServiceImpl.java, line 1418 at r1](https://reviewable.io/reviews/harness/harness-core/32220#-N-XDV4J3pESlA7rhv0a:-N-vFm6k79r6LNrqSC80:b-arr2a7) ([raw file](https://github.com/harness/harness-core/blob/929e51c0dafe333dd390d5ad688a6d1e6178710b/400-rest/src/main/java/software/wings/service/impl/trigger/TriggerServiceImpl.java#L1418)):*
<details><summary><i>Previously, poojaSinghal (Pooja Singhal) wrote…</i></summary><blockquote>

this will only work for workflows. @atharvatrivedi1 did you test for pipelines? 
</blockquote></details>

Yes and please check for templatized and runtime pipelines too
___
*[400-rest/src/test/java/software/wings/service/impl/trigger/TriggerServiceTest.java, line 530 at r2](https://reviewable.io/reviews/harness/harness-core/32220#-N-vFvNsCJOAr_olvAQZ:-N-vFvNsCJOAr_olvAQ_:b-gqsb5l) ([raw file](https://github.com/harness/harness-core/blob/fab92b6e284f94b5ac3c94d4a5db114696d606a4/400-rest/src/test/java/software/wings/service/impl/trigger/TriggerServiceTest.java#L530)):*
> ```Java
>   }
>   @Test
>   @Owner(developers = POOJA)
> ```

change owner :)

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32220)* status: :shipit: complete! ✓

**Review by prabu-kr — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32220)* status: :shipit: complete! ✓

**Pull request merged**
