### PR TITLE
feat: [CDS-78136]: Add tooling for supporting barriers within looping strategies

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR implements tooling that will be necessary for supporting Barrier Steps within looping strategies. In a next PR, we will leverage the changes introduced here in order to finish implementing the feature.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/52485#-Ndl2WlXE_LKYPXeLKMD:-Ndl2WlY3YmJjf3T8zvb:bi3uu4u) ([raw file](https://github.com/harness/harness-core/blob/ffe4417c3cb08167e6bb82c3e3b14fd41348deab/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java#L121)):*
> ```Java
>                 .name("planExecutionId_setupInfo_strategySetupIds_idx")
>                 .field(BarrierExecutionInstanceKeys.planExecutionId)
>                 .field(BarrierExecutionInstanceKeys.setupInfo.concat(".").concat(BarrierSetupInfoKeys.strategySetupIds))
> ```

you can create a constant in BarrierExecutionInstance. 
See NodeExecutionKeys in NodeExecution.java

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/52485#-Ndl2o67BtGCeo-SBQf7:-Ndl2o67BtGCeo-SBQf8:b-69zcuj) ([raw file](https://github.com/harness/harness-core/blob/ffe4417c3cb08167e6bb82c3e3b14fd41348deab/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L326)):*
> ```Java
>             .each(barrierExecutionInstance.getPositionInfo().getBarrierPositionList());
>     if (barrierExecutionInstance.getSetupInfo().getStrategySetupIds() != null) {
>       update.addToSet(BarrierExecutionInstanceKeys.setupInfo + "." + BarrierSetupInfoKeys.strategySetupIds)
> ```

nit: Move to constant in BarrierExecutionInstanceKeys.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/52485#-NdoshUD3RIGX3OdhjIU:-NdoshUD3RIGX3OdhjIV:b8eozur) ([raw file](https://github.com/harness/harness-core/blob/ffe4417c3cb08167e6bb82c3e3b14fd41348deab/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java#L47)):*
> ```Java
> 
>     String strategySetupId;
>     String strategyNodeType;
> ```

can we make this field enum and also add comment explaining why this is required?

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java` line 121 at r2](https://reviewable.io/reviews/harness/harness-core/52485#-Ndl2WlXE_LKYPXeLKMD:-NdpaISq5ZjFDJcU7ZXr:bol3kou) ([raw file](https://github.com/harness/harness-core/blob/ffe4417c3cb08167e6bb82c3e3b14fd41348deab/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java#L121)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

you can create a constant in BarrierExecutionInstance. 
See NodeExecutionKeys in NodeExecution.java
</blockquote></details>

Done! Thank you!
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/52485#-NdoshUD3RIGX3OdhjIU:-NdpaK3Z9URSOkjqVTai:b-896fja) ([raw file](https://github.com/harness/harness-core/blob/ffe4417c3cb08167e6bb82c3e3b14fd41348deab/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java#L47)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

can we make this field enum and also add comment explaining why this is required?
</blockquote></details>

Done!
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 326 at r2](https://reviewable.io/reviews/harness/harness-core/52485#-Ndl2o67BtGCeo-SBQf7:-NdpaLQ1E4gA_QU64r23:b-896fja) ([raw file](https://github.com/harness/harness-core/blob/ffe4417c3cb08167e6bb82c3e3b14fd41348deab/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L326)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Move to constant in BarrierExecutionInstanceKeys.
</blockquote></details>

Done!

**Comment by vcalasansh** [comment]
trigger uts

**Comment by vcalasansh** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 2 of 5 files at r3, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: 11 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxmtAzEO0L1UlfHrre:-NdxmtAzEO0L1UlfHrrf:b-t0tmjv) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java#L23)):*
> ```Java
> public interface BarrierNodeRepository extends CrudRepository<BarrierExecutionInstance, String> {
>   BarrierExecutionInstance findByIdentifierAndPlanExecutionId(String identifier, String planExecutionId);
>   List<BarrierExecutionInstance> findManyByPlanExecutionIdAndSetupInfo_StrategySetupIds(
> ```

does it do in mongo query on strategy setupId? can you share sshot or doc it does, plus explain("executionStats") query on Mongo to see its using index and how many records examined
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java` line 125 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxnO41BmIXQbSwWZgE:-NdxnO41BmIXQbSwWZgF:bole5c2) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java#L125)):*
> ```Java
>                  .build())
>         .add(CompoundMongoIndex.builder()
>                  .name("planExecutionId_setupInfo_strategySetupIds_idx")
> ```

can we not include setupInfo in index name?



_Code quote:_
```Java
setupInfo
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 269 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ndxq4Y4-RzrJe-R9BQb:-Ndxq4Y59UGjl7YNLG3i:b-skzudg) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L269)):*
> ```Java
>         Criteria stageCriteria =
>             Criteria.where(position.concat(".").concat(BarrierPositionKeys.stageSetupId)).is(positionSetupId);
>         if (addFiltersForBarriersWithinLoopingStrategy) {
> ```

can we rename this field ?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 271 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxqDYv9jmMQBe7ZviJ:-NdxqDYv9jmMQBe7ZviK:b-1srwzw) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L271)):*
> ```Java
>         if (addFiltersForBarriersWithinLoopingStrategy) {
>           stageCriteria = stageCriteria.and(position.concat(".").concat(BarrierPositionKeys.strategyNodeType))
>                               .nin(List.of(StrategyNodeType.STAGE.name(), StrategyNodeType.STEP_GROUP.name()));
> ```

as far as i know nin condition is not query friendly, please check. maybe use in [null, strategy]
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 282 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxqVHD0sFinlwmZ8ux:-NdxqVHD0sFinlwmZ8uy:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L282)):*
> ```Java
>         if (addFiltersForBarriersWithinLoopingStrategy) {
>           stepGroupCriteria = stepGroupCriteria.and(position.concat(".").concat(BarrierPositionKeys.strategyNodeType))
>                                   .ne(StrategyNodeType.STEP_GROUP.name());
> ```

same for this

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: 3 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java` line 58 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ne1jMgj1pEJPZk7DYZI:-Ne1jMgj1pEJPZk7DYZJ:b-nbikob) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java#L58)):*
> ```Java
> 
>     public enum BarrierPositionType { STAGE, STEP_GROUP, STEP }
>     public enum StrategyNodeType { STEP_GROUP, STAGE }
> ```

What is the diff between the two enums?



_Code quote:_
```Java
    public enum BarrierPositionType { STAGE, STEP_GROUP, STEP }
    public enum StrategyNodeType { STEP_GROUP, STAGE }
```
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 151 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ne1jaZf261DBswAKC4c:-Ne1jaZf261DBswAKC4d:bpxscvx) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L151)):*
> ```Java
>     /* This method is used by `BarrierWithinStrategyExpander` for fetching all BarrierExecutionInstances which
>        have positions that are children of a given strategy node. */
>     return barrierNodeRepository.findManyByPlanExecutionIdAndSetupInfo_StrategySetupIds(
> ```

why underscore in the method?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 238 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ne1jjcf3hh3ipwAXBB9:-Ne1jjcf3hh3ipwAXBBA:b9opjj4) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L238)):*
> ```Java
>   public void upsert(BarrierExecutionInstance barrierExecutionInstance) {
>     Update update = obtainInstanceUpdate(barrierExecutionInstance);
>     HMongoTemplate.retry(()
> ```

absorb this retry in usert only by overriding it in h mongo template

**Comment by vcalasansh** [comment]
trigger uts

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: 9 file(s) to review. 2 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxmtAzEO0L1UlfHrre:-Ne51hklAilJt6KxPCqP:b-i5ip3j) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

does it do in mongo query on strategy setupId? can you share sshot or doc it does, plus explain("executionStats") query on Mongo to see its using index and how many records examined
</blockquote></details>

The query that is executed is this:
```
find({"planExecutionId": planExecutionId, "setupInfo.strategySetupIds": strategySetupId})
```
The underscore is just to explicitly mark the traversal (that the right field to query for is `setupInfo.strategySetupIds`). It is documented here: https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repositories.query-methods.query-property-expressions

Below is a screenshot showing the index being used by this query in my local DB:

 
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java` line 125 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxnO41BmIXQbSwWZgE:-Ne53_b29modVwqcjPSJ:b-896fja) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierExecutionInstance.java#L125)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we not include setupInfo in index name?
</blockquote></details>

Done!
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java` line 58 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ne1jMgj1pEJPZk7DYZI:-Ne53bQC3Y3aAFUwJTSP:b92d8j6) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans/BarrierPositionInfo.java#L58)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

What is the diff between the two enums?
</blockquote></details>

Removed the `StrategyNodeType` enum.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 151 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ne1jaZf261DBswAKC4c:-Ne53gkK0lzvaIM690Fr:b-bhyd0o) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L151)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

why underscore in the method?
</blockquote></details>

The query that is executed is this:
```
find({"planExecutionId": planExecutionId, "setupInfo.strategySetupIds": strategySetupId})
```
The underscore is just to explicitly mark the traversal (that the right field to query for is `setupInfo.strategySetupIds`). It is documented here: https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repositories.query-methods.query-property-expressions
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 238 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ne1jjcf3hh3ipwAXBB9:-Ne53hcy5WQLWhv8DP70:b-896fja) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L238)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

absorb this retry in usert only by overriding it in h mongo template
</blockquote></details>

Done!
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 269 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-Ndxq4Y4-RzrJe-R9BQb:-Ne53iJcDGvL4eWkwwA_:bs7wubq) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L269)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we rename this field ?
</blockquote></details>

Done! 
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 271 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxqDYv9jmMQBe7ZviJ:-Ne53jX53vQv2mzRj32R:b-63dmjo) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L271)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as far as i know nin condition is not query friendly, please check. maybe use in [null, strategy]
</blockquote></details>

Moved to using only equality queries!
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java` line 282 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxqVHD0sFinlwmZ8ux:-Ne53pqV-Uqz751-zGME:b-63dmjo) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/BarrierServiceImpl.java#L282)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same for this
</blockquote></details>

Moved to using only equality queries!

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: 9 file(s) to review. 2 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxmtAzEO0L1UlfHrre:-Ne6RWpP7uj80lpiD6bs:bv4kn3z) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java#L23)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

The query that is executed is this:
```
find({"planExecutionId": planExecutionId, "setupInfo.strategySetupIds": strategySetupId})
```
The underscore is just to explicitly mark the traversal (that the right field to query for is `setupInfo.strategySetupIds`). It is documented here: https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repositories.query-methods.query-property-expressions

Below is a screenshot showing the index being used by this query in my local DB:

</blockquote></details>

```
"setupInfo.strategySetupIds": strategySetupId})
```

Are we sure it results into above query and not ```
"setupInfo.strategySetupIds": $in: [strategySetupId]})
```
```

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/resources/mongo/indexes.txt` line 16 at r7](https://reviewable.io/reviews/harness/harness-core/52485#-NekuCrO5Edl_TzAKKNc:-NekuCrO5Edl_TzAKKNd:b5xpv99) ([raw file](https://github.com/harness/harness-core/blob/a103c5099d91f5e2df668ca66d72ac682d5df3ed/pipeline-service/service/src/test/resources/mongo/indexes.txt#L16)):*
> ```help
> barrierExecutionInstances {"name": "next_iteration_idx", "background": true} {"barrierState": 1, "nextIteration": 1}
> barrierExecutionInstances {"name": "planExecutionId_barrierState_stagesIdentifier_idx", "background": true} {"planExecutionId": 1, "barrierState": 1, "setupInfo.stages.identifier": 1}
> barrierExecutionInstances {"name": "planExecutionId_strategySetupIds_idx", "background": true} {"planExecutionId": 1, "setupInfo.strategySetupIds": 1}
> ```

lets create a new index here and not touch this one

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/test/resources/mongo/indexes.txt` line 16 at r7](https://reviewable.io/reviews/harness/harness-core/52485#-NekuCrO5Edl_TzAKKNc:-NelRWODDq0tZN8KTniz:blj0bh5) ([raw file](https://github.com/harness/harness-core/blob/a103c5099d91f5e2df668ca66d72ac682d5df3ed/pipeline-service/service/src/test/resources/mongo/indexes.txt#L16)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

lets create a new index here and not touch this one
</blockquote></details>

This seems to be a new index added. Could you please check once again?

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java` line 23 at r6](https://reviewable.io/reviews/harness/harness-core/52485#-NdxmtAzEO0L1UlfHrre:-Neql1xL5L1-O8jb2_Xd:b-wze980) ([raw file](https://github.com/harness/harness-core/blob/652d0f657a4c17d3b0f5bb08c93e8932dba27b7d/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories/BarrierNodeRepository.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

```
"setupInfo.strategySetupIds": strategySetupId})
```

Are we sure it results into above query and not ```
"setupInfo.strategySetupIds": $in: [strategySetupId]})
```
```

</blockquote></details>

@archit-harness , looking at the documentation it feels like it does not use in query but rather the query shared by @vcalasansh

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52485)* status: 1 file(s) to review. 2. unresolved discussions.

**Pull request merged**
