### PR TITLE
fix: [CDS-50906]: Custom Deployment instance sync fixes

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
## Describe your changes
Added cleanup of custom deployment instance sync perpetual tasks

Changelog:
- Delete infrastructure mappings when service is deleted
- Migration to delete infrastructure mappings with deleted service IDs
- Fail custom deployment instance sync PTs with zero instances from DB: These tasks would be deleted if they keep failing. or tasks which return zero instances from server, they would delete the instances and then start failing the PT from the next iteration. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43087)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/CleanupInfraMappingsForDeletedServices.java` line 90 at r1](https://reviewable.io/reviews/harness/harness-core/43087#-NMeHTUe-QDdmI1OUgpl:-NMeHTUe-QDdmI1OUgpm:b-5yrdxv) ([raw file](https://github.com/harness/harness-core/blob/48d454cf8132dc1f58a7bb31856fe27c4bec822e/390-db-migration/src/main/java/io/harness/migrations/all/CleanupInfraMappingsForDeletedServices.java#L90)):*
> ```Java
> 
>   private boolean shouldDeleteInfraMapping(String accountId, InfrastructureMapping infrastructureMapping) {
>     return wingsPersistence.createQuery(Service.class)
> ```

there will be too many DB calls due to this. Can we get list of all serviceIds for a account ( just project the _id field ) and use Set.contains(..) ?

**Comment by yogesh-chauhan** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/43087#-NN1k_L94X2PyTu6bCBC:-NN1k_L94X2PyTu6bCBD:b-toymrw) ([raw file](https://github.com/harness/harness-core/blob/6a62c62b6a11f5201a18db313f293bcb7bbf49a6/400-rest/src/main/java/software/wings/service/impl/instance/CustomDeploymentInstanceHandler.java#L111)):*
> ```Java
>             deploymentTypeTemplate.getHostObjectArrayPath(), scriptOutput, jsonMapper);
> 
>     if (isEmpty(instancesInDb) || isEmpty(latestHostInfos)) {
> ```

we need the check for flow != NEW _DEPLOYMENT here right ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43087)* status: Some of the checks are too old. 5 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43087)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43087)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/CleanupInfraMappingsForDeletedServices.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/43087#-NNBXudCEPCH7JNk-aBv:-NNBXudCEPCH7JNk-aBw:b-mxri1k) ([raw file](https://github.com/harness/harness-core/blob/b0363d3ac6d9c373f0118da3e09b343744368a3d/390-db-migration/src/main/java/io/harness/migrations/all/CleanupInfraMappingsForDeletedServices.java#L56)):*
> ```Java
>         final Set<String> serviceIds = getServiceIdsForAccount(accountId);
>         Set<String> infraMappingsToDelete = new HashSet<>();
>         for (InfrastructureMapping infrastructureMapping : infrastructureMappings) {
> ```

nit: We could use HIterator instead
___
*[`390-db-migration/src/main/java/io/harness/migrations/all/CleanupInfraMappingsForDeletedServices.java` line 83 at r3](https://reviewable.io/reviews/harness/harness-core/43087#-NNBY7VX43F--hylwd9O:-NNBY7VX43F--hylwd9P:b-9b6fq9) ([raw file](https://github.com/harness/harness-core/blob/b0363d3ac6d9c373f0118da3e09b343744368a3d/390-db-migration/src/main/java/io/harness/migrations/all/CleanupInfraMappingsForDeletedServices.java#L83)):*
> ```Java
>         .asList()
>         .stream()
>         .map(Service::getServiceId)
> ```

should be uuid as discussed in meeting

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43087)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43087)* status: :shipit: complete! ✓

**Pull request merged**
