### PR TITLE
feat: [PL-42472]: Enable new nav for all new accounts by default

### PR DESCRIPTION
**Pull request by sahibaHarness**
## Describe your changes

Enable new nav for all new accounts by default.
With these changes we are enabling new nav for all new account signups

image

Tested for:
-> Spun up dev space for the changes post reseting the data, creating a new account 

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55279)

### CODE REVIEW

**Comment by arya-harness** [comment]
@sahibaHarness , how to disable this if someone needs to on SMP?

**Comment by sahibaHarness** [comment]
> @sahibaHarness , how to disable this if someone needs to on SMP?

We can disable the feature flag on that account.

**Comment by arya-harness** [comment]
> > @sahibaHarness , how to disable this if someone needs to on SMP?
> 
> We can disable the feature flag on that account.

on SMP, the featureflags currently get initialized during startup of the cg-manager using envConfig FEATURES. it first sets every FF to false and enables one by one with what is present in FEATURES list.

On SMP the flow only enables it, it does not disables it. to disable this functionality, you have to create an inverse FF and use that.
Also, currently SMP is 1 account only.

**Review by pbarapatre10 — APPROVED** [review]

**Comment by sahibaHarness** [comment]
> > > @sahibaHarness , how to disable this if someone needs to on SMP?
> > 
> > 
> > We can disable the feature flag on that account.
> 
> on SMP, the featureflags currently get initialized during startup of the cg-manager using envConfig FEATURES. it first sets every FF to false and enables one by one with what is present in FEATURES list.
> 
> On SMP the flow only enables it, it does not disables it. to disable this functionality, you have to create an inverse FF and use that. Also, currently SMP is 1 account only.

Had discussion with @arya-harness and made changes accordingly

**Review by arya-harness — APPROVED** [review]

**Review by pbarapatre10 — APPROVED** [review]

**Pull request merged**
