### PR TITLE
[techdebt]: [SRM-13962]: Add SLOTarget entity outside SLOV1 class, an…

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
…d make sure both fields are created/updated

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45214)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by naveen-harness — DISMISSED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45214)* status: Some of the checks are too old.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45214)* status: Some of the checks are too old. 1 change requests. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/45214#-NR2wSRc7gusLbMeHPm6:-NR2wSRdAoJ_-sqQibcg:b-c1quv3) ([raw file](https://github.com/harness/harness-core/blob/36d0f9ab3bdaf20a863b9d4e5f57cfab6cac5799/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java#L165)):*
> ```Java
>         }
>       } else {
>         sloRecord = CompositeSLORecord.builder()
> ```

Either we can put both is else if condition on move the constructor to CompositeSLORecord.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/45214#-NR2vfBc8yVJnJ6A9gUg:-NR2vfBc8yVJnJ6A9gUh:b5xom20) ([raw file](https://github.com/harness/harness-core/blob/36d0f9ab3bdaf20a863b9d4e5f57cfab6cac5799/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/transformer/servicelevelobjectivev2/CompositeSLOTransformer.java#L44)):*
> ```Java
>     ServiceLevelObjective.SLOTarget sloTarget =
>         sloTargetTypeSLOTargetTransformerMap.get(serviceLevelObjectiveV2DTO.getSloTarget().getType())
>             .getSLOTarget(serviceLevelObjectiveV2DTO.getSloTarget().getSpec());
> ```

Why do we need to still have old slo target transformer? why can't we move to the new directly here?

**Review by deepak-harness — APPROVED** [review]
> Reviewed 9 of 17 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45214)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45214)* status: :shipit: complete! ✓

**Pull request merged**
