### PR TITLE
feat: [CDS-34812]: Added Yaml support and GitSync entities to Environment

### PR DESCRIPTION
**Pull request by shivamnegi94**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/environment/beans/Environment.java, line 88 at r1](https://reviewable.io/reviews/harness/harness-core/31453#-MyBZSEK12teszd69nck:-MyBZSEK12teszd69ncl:bg33god) ([raw file](https://github.com/harness/harness-core/blob/c6f67650df5e86ba7329db425d8579e8da94726a/950-ng-core/src/main/java/io/harness/ng/core/environment/beans/Environment.java#L88)):*
> ```Java
>   @Setter @NonFinal String yamlGitConfigRef;
>   @Setter @NonFinal String filePath;
>   @Setter @NonFinal String rootFolder;
> ```

we should add their respective indexes as well for git sync



_Code quote:_
```Java
  @Wither @Setter @NonFinal String objectIdOfYaml;
  @Setter @NonFinal Boolean isFromDefaultBranch;
  @Setter @NonFinal String branch;
  @Setter @NonFinal String yamlGitConfigRef;
  @Setter @NonFinal String filePath;
  @Setter @NonFinal String rootFolder;
```

**Review by shivamnegi94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/environment/beans/Environment.java, line 88 at r1](https://reviewable.io/reviews/harness/harness-core/31453#-MyBZSEK12teszd69nck:-MyC-u8_7Z36CF0bkzCl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c6f67650df5e86ba7329db425d8579e8da94726a/950-ng-core/src/main/java/io/harness/ng/core/environment/beans/Environment.java#L88)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add their respective indexes as well for git sync
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)* status: 1 change requests. 1. unresolved discussions. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java, line 26 at r2](https://reviewable.io/reviews/harness/harness-core/31453#-MyDCkoT9yvgXOTddXBK:-MyDCkoU8Jfp2sxdOmwu:b2v4fvr) ([raw file](https://github.com/harness/harness-core/blob/5574b285246305cbd417a605ce23d89ce278341f/950-ng-core/src/main/java/io/harness/ng/core/environment/mappers/NGEnvironmentEntityMapper.java#L26)):*
> ```Java
> @UtilityClass
> public class NGEnvironmentEntityMapper {
>   public String toYaml(NGEnvironmentConfig ngServiceConfig) {
> ```

nit: rename variable name

**Review by inderschera — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)* status: 1 change requests. 1. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 9 of 13 files at r1, 7 of 9 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31453)* status: :shipit: complete! ✓

**Pull request merged**
