### PR TITLE
feat: [CDS-36908]: Pipeline CRUD with Service Ref

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32771)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32771)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/32771#-N1DsgOp1cSzaokRoKkG:-N1DsgOp1cSzaokRoKkH:b-rpwkhn) ([raw file](https://github.com/harness/harness-core/blob/d2982103f976fe5822b850f73f161ec7c7904a17/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L50)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @JsonTypeName("Deployment")
> @OneOfField(fields = {"serviceConfig", "service"})
> ```

use this @OneOfSet(fields =
Check StageElementConfig



_Code quote:_
```Java
@OneOfField(fields = {"serviceConfig", "service"})
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32771)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/32771#-N1DsgOp1cSzaokRoKkG:-N1IBY6aEDj9NRwIoEgz:bbb4h17) ([raw file](https://github.com/harness/harness-core/blob/d2982103f976fe5822b850f73f161ec7c7904a17/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use this @OneOfSet(fields =
Check StageElementConfig
</blockquote></details>

one of set remove from develop
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/32771#-N1IAmbR91N8T9I0cE_R:-N1IAmbR91N8T9I0cE_S:b-wedd7g) ([raw file](https://github.com/harness/harness-core/blob/c6d6ec300fea96bad71a3362d73972c6dafff8c1/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L77)):*
> ```Java
>   @Getter(onMethod_ = { @ApiModelProperty(hidden = true) })
>   @ApiModelProperty(hidden = true)
>   DeploymentType deploymentType;
> ```

use ServiceDefinitionType



_Code quote:_
```Java
DeploymentType
```
___
*[`930-delegate-tasks/src/main/java/software/wings/api/DeploymentType.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/32771#-N1IA9r5BQTsvaTFo712:-N1IA9r62PpDW3Gs_NNo:b22quet) ([raw file](https://github.com/harness/harness-core/blob/c6d6ec300fea96bad71a3362d73972c6dafff8c1/930-delegate-tasks/src/main/java/software/wings/api/DeploymentType.java#L44)):*
> ```Java
>   @JsonProperty("Custom") CUSTOM("Custom");
> 
>   private String displayName;
> ```

Remove this



_Code quote:_
```Java
public enum DeploymentType {
  @JsonProperty("Ssh") SSH("Secure Shell (SSH)"),
  @JsonProperty("AwsCodePloy") AWS_CODEDEPLOY("AWS CodeDeploy"),
  @JsonProperty("Ecs") ECS("Amazon EC2 Container Services (ECS)"),
  @JsonProperty("Spotinst") SPOTINST("SPOTINST"),
  @JsonProperty("Kubernetes") KUBERNETES("Kubernetes"),
  @JsonProperty("Helm") HELM("Helm"),
  @JsonProperty("AwsLambda") AWS_LAMBDA("AWS Lambda"),
  @JsonProperty("Ami") AMI("AMI"),
  @JsonProperty("Winrm") WINRM("Windows Remote Management (WinRM)"),
  @JsonProperty("Pcf") PCF("Tanzu Application Services"),
  @JsonProperty("AzureVmss") AZURE_VMSS("Azure Virtual Machine Image"),
  @JsonProperty("AzureWebapp") AZURE_WEBAPP("Azure Web App"),
  @JsonProperty("Custom") CUSTOM("Custom");

  private String displayName;
```

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32771)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/32771#-N1DsgOp1cSzaokRoKkG:-N1INt_lEdbwmXZV-8RG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/d2982103f976fe5822b850f73f161ec7c7904a17/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

one of set remove from develop
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java` line 77 at r4](https://reviewable.io/reviews/harness/harness-core/32771#-N1IAmbR91N8T9I0cE_R:-N1INvsQ2eifpMwcZjYd:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c6d6ec300fea96bad71a3362d73972c6dafff8c1/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java#L77)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use ServiceDefinitionType
</blockquote></details>

done
___
*[`930-delegate-tasks/src/main/java/software/wings/api/DeploymentType.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/32771#-N1IA9r5BQTsvaTFo712:-N1IO1pN00HLz-C-ZixF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c6d6ec300fea96bad71a3362d73972c6dafff8c1/930-delegate-tasks/src/main/java/software/wings/api/DeploymentType.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

done

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32771)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 3 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32771)* status: :shipit: complete! ✓

**Pull request merged**
