### PR TITLE
feat: [PIE-5470]: Saving outcomes of child pipeline in parent pipelin…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…e in Pipeline Stage Step

## Resolving outputs section under Pipeline Stage spec
Screenshot 2022-11-28 at 2 05 54 PM

Testing: In local

ReleaseNotes summary needed? Yes

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger ti0

**Comment by prashantsharma04** [comment]
trigger ti1

**Comment by prashantsharma04** [comment]
trigger ti3

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageOutputs.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/40644#-NHxXLP0A9HuXu0qFO0K:-NHxXLP19OapXWULDoYL:ba6c4j7) ([raw file](https://github.com/harness/harness-core/blob/51fb3732bc7f117249ee3df720995ff0c6adaa84/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageOutputs.java#L44)):*
> ```Java
>   @NotNull @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> value;
> 
>   public static Map<String, ParameterField<String>> getMapOfString(List<PipelineStageOutputs> outputs) {
> ```

PipelineStageOutput is simply key-value pair. is it?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/40644#-NHxXlQc0mBiuKV-tabv:-NHxXlQc0mBiuKV-tabw:bprodq1) ([raw file](https://github.com/harness/harness-core/blob/51fb3732bc7f117249ee3df720995ff0c6adaa84/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L200)):*
> ```Java
>       Map<String, ParameterField<String>> map, NodeExecution nodeExecution) {
>     Map<String, Object> resolvedMap = new HashMap<>();
>     for (Map.Entry<String, ParameterField<String>> entry : map.entrySet()) {
> ```

I think we can directly call the pmsEngineExpressionService.resolve method on the complete map. it can resolve the complete map at once.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageOutputs.java` line 47 at r2](https://reviewable.io/reviews/harness/harness-core/40644#-NHxYmHJ6AeUcvaGUodj:-NHxYmHJ6AeUcvaGUodk:b-wyldqy) ([raw file](https://github.com/harness/harness-core/blob/51fb3732bc7f117249ee3df720995ff0c6adaa84/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage/PipelineStageOutputs.java#L47)):*
> ```Java
>     Map<String, ParameterField<String>> mapOfString = new HashMap<>();
>     if (isNotEmpty(outputs)) {
>       for (PipelineStageOutputs output : outputs) {
> ```

nit: Using stream may provide more code readability.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/40644#-NHxXlQc0mBiuKV-tabv:-NHy2Hcm2rhyqdzsVgQf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/51fb3732bc7f117249ee3df720995ff0c6adaa84/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L200)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think we can directly call the pmsEngineExpressionService.resolve method on the complete map. it can resolve the complete map at once.
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/40644#-NHxXlQc0mBiuKV-tabv:-NI0omzU7BSxEGOW01GG:b-vd88m3) ([raw file](https://github.com/harness/harness-core/blob/51fb3732bc7f117249ee3df720995ff0c6adaa84/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L200)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do we really need this loop? Resolve will already reiterate this.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/40644#-NI0tlTd-zmpBAp0d73r:-NI0tlTg17_nKQruVCdA:b-p1r9x2) ([raw file](https://github.com/harness/harness-core/blob/a526bf6272d807336f35850d479cdc6a1f89d761/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java#L146)):*
> ```Java
> 
>     NodeExecution nodeExecution =
>         nodeExecutionService.getPipelineNodeExecution(pipelineStageSweepingOutput.getChildExecutionId()).get();
> ```

As discussed, use Projections for this call



_Code quote:_
```Java
etChildExecutionId()
```

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 200 at r2](https://reviewable.io/reviews/harness/harness-core/40644#-NHxXlQc0mBiuKV-tabv:-NI1dVv54xvcVx0LQMrp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/51fb3732bc7f117249ee3df720995ff0c6adaa84/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L200)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Do we really need this loop? Resolve will already reiterate this.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java` line 146 at r3](https://reviewable.io/reviews/harness/harness-core/40644#-NI0tlTd-zmpBAp0d73r:-NI1dX8T5j05lr1Zn4Ay:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a526bf6272d807336f35850d479cdc6a1f89d761/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/step/PipelineStageStep.java#L146)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

As discussed, use Projections for this call
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40644)* status: :shipit: complete! ✓

**Pull request merged**
