### PR TITLE
[feat]: [CDS-69463]: Add FF for Retry Step Group Failure Strategy

### PR DESCRIPTION
**Pull request by namanvermah**
Created a PR just for this as https://github.com/harness/harness-core/pull/48509 was repeatedly getting merge conflicts

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48625)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]

**Comment by namanvermah** [comment]
trigger uts

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48625)* status: 1 file(s) to review.

**Comment by namanvermah** [comment]
trigger review

**Review by prashantsharma04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48625)* status: 1 file(s) to review.

**Pull request merged**
