### PR TITLE
feat: [CDS-35108]: Support for Custom Deployment in NG

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37534)

### CODE REVIEW

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 134 of 134 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534#-:-NCaPZz904zj0G6qDVrc:bnfp4nl)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 131 of 134 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534#-:-NCceeIE7YmTO2lm0kQq:bnfp4nl)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 134 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> Reviewed 4 of 134 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/events/TemplateOutboxEventHandler.java` line 203 at r3](https://reviewable.io/reviews/harness/harness-core/37534#-NCcmibR0REFbxXcYIxx:-NCcmibR0REFbxXcYIxy:bjuwuul) ([raw file](https://github.com/harness/harness-core/blob/f347f179b94100df18bf2c20cdb659fb6b7a7581/840-template-service/src/main/java/io/harness/template/events/TemplateOutboxEventHandler.java#L203)):*
> ```Java
>       entityBuilder.setProjectIdentifier(StringValue.of(resourceScope.getProjectIdentifier()));
>     }
>     if (templateType == TemplateEntityType.CUSTOM_DEPLOYMENT_TEMPLATE) {
> ```

nit: IMO let's always publish versionLabel and templateType in metadata.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 131 of 134 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 131 of 134 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37534)* status: :shipit: complete! ✓

**Pull request merged**
