### PR TITLE
[fix]: [PIE-5619]: Filtered responses of NG-Manager, to get only that connector which is actually referred in pipeline

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: Customer was using old-git sync and was having multiple connectors in different branches, Upon skiping PreflightCheck pipeline was successful, and when preflight was enabled it failed as it fetched all connectors with that identifier from DB and subsequently ran preflight check upon them.

Changes: Filtered responses of NG-Manager, to get only that connector which is actually referred in pipeline

Testing: 2 cases needed to be checked one was verified on local(connectors with same identifier in different branches), other is only possible on QA(connectors with same identifier in different repos), so will test when changes gets deployed to QA

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38652)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38652)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/38652#-NEErA3fAHBGsGVLMY8g:-NEErA3fAHBGsGVLMY8h:b-o733sy) ([raw file](https://github.com/harness/harness-core/blob/6e15891f75b219098ff8f94caf536e3aca095b1a/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L82)):*
> ```Java
>         getConnectorResponses(accountIdentifier, orgIdentifier, projectIdentifier, scopeToConnectorIdentifiers);
> 
>     List<ConnectorResponseDTO> finalResponse = new ArrayList<>();
> ```

add unit test for this segment

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38652)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/38652#-NEErA3fAHBGsGVLMY8g:-NEF38r16poG5Abr_YPR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6e15891f75b219098ff8f94caf536e3aca095b1a/pipeline-service/contracts/src/main/java/io/harness/pms/preflight/connector/ConnectorPreflightHandler.java#L82)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

add unit test for this segment
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38652)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38652)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38652)* status: :shipit: complete! ✓

**Pull request merged**
