### PR TITLE
feat: [IDP-1873]: Workflow executions data for dashboards

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Workflow executions data for dashboards

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57148)

### CODE REVIEW

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57148)* status: Some of the checks are too old. 13 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/backstage/beans/BackstageScaffolderTasks.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8KkQq2U3iUzD7WWnP:-Nn8KkQq2U3iUzD7WWnQ:b-wy2nwk) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/beans/BackstageScaffolderTasks.java#L31)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> @OwnedBy(HarnessTeam.IDP)
> public class BackstageScaffolderTasks {
> ```

Since each entity represents one task, should we name this as BackstageScaffolderTask and the entity class as BackstageScaffolderTaskEntity?



_Code quote:_
```Java
BackstageScaffolderTasks
```
___
*[`idp-service/src/main/java/io/harness/idp/backstage/entities/BackstageScaffolderTasksEntity.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8K2DmB3f7TY5iA7SQ:-Nn8K2DmB3f7TY5iA7SR:b-gwi2fb) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/entities/BackstageScaffolderTasksEntity.java#L55)):*
> ```Java
>   long lastHeartbeatAt;
>   @NotNull String secrets;
>   @NotNull String createdBy;
> ```

Can we use some other names for createdAt and createdBy? These names are used by CreatedByAware and CreatedAtAware interfaces and we might want to add the information on which user triggered the workflow for audit soon.



_Code quote:_
```Java
  long createdAt;
  long lastHeartbeatAt;
  @NotNull String secrets;
  @NotNull String createdBy;
```
___
*[`idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8Mnzu6aVxnbig9_ow:-Nn8Mnzu6aVxnbig9_ox:bbb82c1) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java#L154)):*
> ```Java
>           accountIdentifier, syncFrom);
>       List<BackstageScaffolderTasksEntity> scaffolderTasksEntities = toEntities(accountIdentifier, scaffolderTasks);
>       scaffolderTasksEntityRepository.saveAll(scaffolderTasksEntities);
> ```

Do we need to purge these after say 6 months? Or do we plan to keep all the tasks for ever?



_Code quote:_
```Java
saveAll
```
___
*[`idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8M-3B-OdoUV3p0ORq:-Nn8M-3CAUY8RqFYZ_wu:b-11sj6e) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java#L369)):*
> ```Java
>         ? NamespaceEntity.Metadata.builder().build()
>         : namespaceEntity.getMetadata();
>     metadata.setScaffolderTasksSyncFrom(System.currentTimeMillis());
> ```

What if a workflow execution is triggered AFTER the API call to fetch tasks but BEFORE saving here? We might miss such tasks in incremental sync.



_Code quote:_
```Java
System.currentTimeMillis()
```

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57148)* status: 13 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8Mnzu6aVxnbig9_ow:-Nn8XnhU91INUHZQDoUM:b-xpujwl) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java#L154)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Do we need to purge these after say 6 months? Or do we plan to keep all the tasks for ever?
</blockquote></details>

Done. Have set it to 3 months. CC - @sandeepa-kv-jois 
___
*[`idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java` line 369 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8M-3B-OdoUV3p0ORq:-Nn8Xque3Y8LZXcd2oKW:b-1ioxqd) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/service/impl/BackstageServiceImpl.java#L369)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

What if a workflow execution is triggered AFTER the API call to fetch tasks but BEFORE saving here? We might miss such tasks in incremental sync.
</blockquote></details>

Done. Taking up in next PR along with harnes-idp changes
___
*[`idp-service/src/main/java/io/harness/idp/backstage/beans/BackstageScaffolderTasks.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8KkQq2U3iUzD7WWnP:-Nn8Xko83DoYrEGmD_52:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/beans/BackstageScaffolderTasks.java#L31)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Since each entity represents one task, should we name this as BackstageScaffolderTask and the entity class as BackstageScaffolderTaskEntity?
</blockquote></details>

Done
___
*[`idp-service/src/main/java/io/harness/idp/backstage/entities/BackstageScaffolderTasksEntity.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/57148#-Nn8K2DmB3f7TY5iA7SQ:-Nn8Xm5J9wZLjS3p6SIA:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2bc14833775b5603bcaa34e0589dff8ca7a70424/idp-service/src/main/java/io/harness/idp/backstage/entities/BackstageScaffolderTasksEntity.java#L55)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we use some other names for createdAt and createdBy? These names are used by CreatedByAware and CreatedAtAware interfaces and we might want to add the information on which user triggered the workflow for audit soon.
</blockquote></details>

Done

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Comment by sathish-soundarapandian** [comment]
trigger ut5

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57148)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by vigneswara-propelo — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger review

**Pull request merged**
