### PR TITLE
[fix]: [DEL-4655]: removed spring data mongodb dependencies

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
refactor to remove spring mongo data dependency from delegate jar 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36359)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 104 Issues 
* Vulnerability 34 Vulnerabilities 
 * Code issue 66 Code issues 
* Anti-pattern 4 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36359)

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 94 files at r1, 9 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36359)* status: 102 file(s) to review. 0 of 1 approvals obtained.

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/serializer/kryo/DelegateServiceKryoRegister.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9beAGq15GARnb0BaGU:-N9beAGrAvgXWLmmyXmm:b-70276m) ([raw file](https://github.com/harness/harness-core/blob/4ed50dbaf964addcc9c5a980f273a8cf7b0750a0/420-delegate-service/src/main/java/io/harness/serializer/kryo/DelegateServiceKryoRegister.java#L24)):*
> ```Java
>     kryo.register(PerpetualTaskClientContext.class, 40030);
>     kryo.register(Delegate.class, 40031);
>     kryo.register(DelegateTaskUsageInsightsEventType.class, 40032);
> ```

why remove this?

**Comment by jennyjames21** [comment]
*[`890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9beedo1FUNrpTT9wvX:-N9beedsC0swBlsYhUj1:b-rfij3j) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java#L101)):*
> ```Java
>   public static Secret fromDTO(SecretDTOV2 secretDTO) {
>     return Secret.builder()
>         .orgIdentifier(secretDTO.getOrgIdentifier())
> ```

accountIdentifier is missing here

**Comment by jennyjames21** [comment]
*[`890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9beedo1FUNrpTT9wvX:-N9besiP7HYIUEL612Ng:b-co7ocq) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java#L101)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

accountIdentifier is missing here
</blockquote></details>

  Boolean draft is also missing from Secret entity

**Comment by jennyjames21** [comment]
*[`890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9beedo1FUNrpTT9wvX:-N9bfC3O3Eff0eaAoKgU:b-eut5jf) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java#L101)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

  Boolean draft is also missing from Secret entity
</blockquote></details>

Boolean migratedFromManager need this??

**Comment by jennyjames21** [comment]
*[`920-delegate-agent-beans/BUILD.bazel` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9bfpGb0knouoFTihfH:-N9bfpGb0knouoFTihfI:bl8t9xu) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/920-delegate-agent-beans/BUILD.bazel#L16)):*
> ```Starlark
>     deps = [
>         "//:lombok",
>         "//920-delegate-agent-beans/src/main/proto:920_delegate_agent_beans_java_proto",
> ```

next line for proto?

**Comment by jennyjames21** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/perpetualtask/k8s/utils/K8sClusterHelper.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9bg-YKEe40hXBDxDlt:-N9bg-YKEe40hXBDxDlu:b-pc1zeg) ([raw file](https://github.com/harness/harness-core/blob/4ed50dbaf964addcc9c5a980f273a8cf7b0750a0/930-delegate-tasks/src/main/java/io/harness/perpetualtask/k8s/utils/K8sClusterHelper.java#L24)):*
> ```Java
> @Slf4j
> @Singleton
> @Service
> ```

why remove this? mite break dependency injection on usage

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 88 of 94 files at r1, 21 of 23 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36359)* status: 0 of 1 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/serializer/kryo/DelegateServiceKryoRegister.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9beAGq15GARnb0BaGU:-N9c90ZR4zmsZgetCjbh:bu3febi) ([raw file](https://github.com/harness/harness-core/blob/4ed50dbaf964addcc9c5a980f273a8cf7b0750a0/420-delegate-service/src/main/java/io/harness/serializer/kryo/DelegateServiceKryoRegister.java#L24)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why remove this?
</blockquote></details>

because this class is moved to a different module where its now registered

**Comment by raghuAtWings** [comment]
*[`890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9beedo1FUNrpTT9wvX:-N9cBlDQDGRWwIvaKfJd:b-57zlff) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/890-sm-core/src/main/java/io/harness/ng/core/models/Secret.java#L101)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Boolean migratedFromManager need this??
</blockquote></details>

look at io.harness.ng.core.dto.secrets.SecretDTOV2#toEntity in develop branch. Its copy pasted.

**Comment by raghuAtWings** [comment]
*[`920-delegate-agent-beans/BUILD.bazel` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9bfpGb0knouoFTihfH:-N9cBv0g4N6etWmxeIga:b-ffreo5) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/920-delegate-agent-beans/BUILD.bazel#L16)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

next line for proto?
</blockquote></details>

what do you mean?

**Comment by raghuAtWings** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/perpetualtask/k8s/utils/K8sClusterHelper.java` line 24 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9bg-YKEe40hXBDxDlt:-N9cBzARCddIE2ZKgGrl:bx7dos8) ([raw file](https://github.com/harness/harness-core/blob/4ed50dbaf964addcc9c5a980f273a8cf7b0750a0/930-delegate-tasks/src/main/java/io/harness/perpetualtask/k8s/utils/K8sClusterHelper.java#L24)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why remove this? mite break dependency injection on usage
</blockquote></details>

this is not used anywhere, confirmed with @hitesharinga 
he will delete this file

**Comment by jennyjames21** [comment]
*[`920-delegate-agent-beans/BUILD.bazel` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/36359#-N9bfpGb0knouoFTihfH:-N9cD0Xj-s88jydnjvJW:b-b4zo0q) ([raw file](https://github.com/harness/harness-core/blob/a472fb283767f2c0609dd8342a4aff709a8408ad/920-delegate-agent-beans/BUILD.bazel#L16)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what do you mean?
</blockquote></details>

nvm i thought it's 2 lines

**Review by jennyjames21 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36359#-:-N9cDCJH3F9YUEJE1n5b:bnfp4nl)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
trigger codebasehash

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 88 of 94 files at r1, 21 of 23 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36359)* status: :shipit: complete! ✓

**Pull request merged**
