### PR TITLE
[feat]: [PIE-2362]: Extract local FQN based requests

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30091)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30091)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30091)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger bazelbuild

**Comment by namanvermah** [comment]
trigger compile

**Pull request merged**
