### PR TITLE
[feat]: [PIE-8799]: Performance improvements for async validation

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)

### CODE REVIEW

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 655 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPv7TfA1T4eMiYBsQrD:-NPv95st9a2duX9hjTzS:b-vn7rp4) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L655)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Why is this a string, why not boolean?
</blockquote></details>

headers cant be boolean

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 655 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPv7TfA1T4eMiYBsQrD:-NPv9o3LBl5CTir7f25o:b-c4er1n) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L655)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

headers cant be boolean
</blockquote></details>

i think we should do default as true, we should ask customers to specifically pass true if needed or expose from UI by default true is set
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceConfiguration.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPvAh_kE3aYMHcBGKyU:-NPvAh_kE3aYMHcBGKyV:bxfz3lb) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/service/src/main/java/io/harness/PipelineServiceConfiguration.java#L176)):*
> ```Java
>   private GitSdkConfiguration gitSdkConfiguration;
>   private DelegatePollingConfig delegatePollingConfig;
>   private ThreadPoolConfig pipelineAsyncValidationPoolConfig;
> ```

add comments why this thread pool?
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 731 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPvAje20K0ir8mI7CRU:-NPvAje20K0ir8mI7CRV:bm7qkz9) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L731)):*
> ```Java
>   @Singleton
>   @Named("PipelineAsyncValidationExecutorService")
>   public Executor pipelineAsyncValidationExecutorService() {
> ```

add comments why this executor
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPvB6w98fHVHDS1XI9-:-NPvB6w98fHVHDS1XI90:b-902si) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java#L39)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class PipelineAsyncValidationServiceImpl implements PipelineAsyncValidationService {
>   @Inject PipelineValidationEventRepository pipelineValidationEventRepository;
> ```

would recommend to use constructor inject with @named on respective field , example - NodeExecutionReadHelper



_Code quote:_
```Java
  @Inject PipelineValidationEventRepository pipelineValidationEventRepository;
  @Inject @Named("PipelineAsyncValidationExecutorService") Executor executor;
  @Inject private PMSPipelineTemplateHelper pipelineTemplateHelper;
  @Inject private PipelineGovernanceService pipelineGovernanceService;
```

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 655 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPv7TfA1T4eMiYBsQrD:-NPvDOy1-we2xsKOEOcq:b-asf470) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L655)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think we should do default as true, we should ask customers to specifically pass true if needed or expose from UI by default true is set
</blockquote></details>

https://harness.atlassian.net/browse/PIE-8802

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceConfiguration.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPvAh_kE3aYMHcBGKyU:-NPvQP3X5ObASiPOPUir:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/service/src/main/java/io/harness/PipelineServiceConfiguration.java#L176)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments why this thread pool?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java` line 731 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPvAje20K0ir8mI7CRU:-NPvQQCHBU6bn01E6y_X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java#L731)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments why this executor
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPvB6w98fHVHDS1XI9-:-NPvQR-d585qxunhEMZ1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

would recommend to use constructor inject with @named on respective field , example - NodeExecutionReadHelper
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/44804#-NPv_GjEA65PrPBSqQrO:-NPv_GjEA65PrPBSqQrP:b4p3sid) ([raw file](https://github.com/harness/harness-core/blob/ea3c5e013d35d65b7fa5fb5408b0af21401b61ef/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java#L42)):*
> ```Java
>   Executor executor;
>   PMSPipelineTemplateHelper pipelineTemplateHelper;
>   PipelineGovernanceService pipelineGovernanceService;
> ```

these variables should be private and final



_Code quote:_
```Java
  Executor executor;
  PMSPipelineTemplateHelper pipelineTemplateHelper;
  PipelineGovernanceService pipelineGovernanceService;
```
___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 198 at r5](https://reviewable.io/reviews/harness/harness-core/44804#-NPv_UXm3cj5E-6wO88F:-NPv_UXm3cj5E-6wO88G:bicf8al) ([raw file](https://github.com/harness/harness-core/blob/ea3c5e013d35d65b7fa5fb5408b0af21401b61ef/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L198)):*
> ```Java
>         return ThreadPool.create(1, 1, 30, SECONDS,
>             new ThreadFactoryBuilder().setNameFormat("PipelineAsyncValidationExecutorService-%d").build());
>       }
> ```

why do we need threadpool here? i don't see other thread pool added here



_Code quote:_
```Java
      @Provides
      @Singleton
      @Named("PipelineAsyncValidationExecutorService")
      public Executor pipelineAsyncValidationExecutorService() {
        return ThreadPool.create(1, 1, 30, SECONDS,
            new ThreadFactoryBuilder().setNameFormat("PipelineAsyncValidationExecutorService-%d").build());
      }
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java` line 42 at r5](https://reviewable.io/reviews/harness/harness-core/44804#-NPv_GjEA65PrPBSqQrO:-NPvfORgD-zGz1poDuQf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ea3c5e013d35d65b7fa5fb5408b0af21401b61ef/pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/PipelineAsyncValidationServiceImpl.java#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

these variables should be private and final
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 198 at r5](https://reviewable.io/reviews/harness/harness-core/44804#-NPv_UXm3cj5E-6wO88F:-NPvfOnq6UO3UtvBPweT:b-f9vass) ([raw file](https://github.com/harness/harness-core/blob/ea3c5e013d35d65b7fa5fb5408b0af21401b61ef/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L198)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need threadpool here? i don't see other thread pool added here
</blockquote></details>

Because I am not using category test, and actually injecting the class to be tested (for mongo tests), I'll need the named executor.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java` line 198 at r5](https://reviewable.io/reviews/harness/harness-core/44804#-NPv_UXm3cj5E-6wO88F:-NQYi5yj3Xoe1yBozAS-:b-gndokm) ([raw file](https://github.com/harness/harness-core/blob/ea3c5e013d35d65b7fa5fb5408b0af21401b61ef/pipeline-service/service/src/test/java/io/harness/PipelineServiceTestRule.java#L198)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Because I am not using category test, and actually injecting the class to be tested (for mongo tests), I'll need the named executor. 
</blockquote></details>

Removed the threadpool

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, 10 of 12 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 14 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 10 of 12 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r6, 10 of 12 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 1. unresolved discussions.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44804)* status: 1. unresolved discussions. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 655 at r2](https://reviewable.io/reviews/harness/harness-core/44804#-NPv7TfA1T4eMiYBsQrD:-NQcvF716XxLL2Y2mOAc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/03c29de8996bc8449270dfc734d0a357022c3bdb/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L655)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

https://harness.atlassian.net/browse/PIE-8802
</blockquote></details>

done

**Pull request merged**
