### PR TITLE
feat: [SRM-10787]: added service enabled flag in monitored service list API

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 956 at r1](https://reviewable.io/reviews/harness/harness-core/34265#-N4SHkxPCD0DECjrZJy0:-N4SHkxPCD0DECjrZJy1:b-ec8bdb) ([raw file](https://github.com/harness/harness-core/blob/b21f6305ed770ffb62893dc124ef4ae926224e3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L956)):*
> ```Java
>             .map(monitoredService -> toMonitorServiceListDTO(monitoredService))
>             .collect(Collectors.toList());
>     List<String> enabledServices = getEnabledMonitoredServices(projectParams.getAccountIdentifier())
> ```

lets use hash set here so that checking if monitoredservicerdto.serviceref operation because O(1)

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)* status: 4 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/34265#-N4SwSyqDDryax56iDlq:-N4SwSyqDDryax56iDlr:bz4n4d) ([raw file](https://github.com/harness/harness-core/blob/b21f6305ed770ffb62893dc124ef4ae926224e3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java#L40)):*
> ```Java
>   ChangeSummaryDTO changeSummary;
>   Map<String, String> tags;
>   boolean serviceEnabled;
> ```

we should name this better. serviceEnabled does not communicate the intent. I think we can rename this to something like serviceLicenseEnabled 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1034 at r1](https://reviewable.io/reviews/harness/harness-core/34265#-N4SxGZU3u9DJTJbdUjs:-N4SxGZU3u9DJTJbdUjt:bd1o4bw) ([raw file](https://github.com/harness/harness-core/blob/b21f6305ed770ffb62893dc124ef4ae926224e3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1034)):*
> ```Java
> 
>   private List<MonitoredService> getEnabledMonitoredServices(String accountId) {
>     return hPersistence.createQuery(MonitoredService.class)
> ```

healthMonitoringEnabled is already a flag for this same information. shouldn't this use license framework to determine which flag is enabled? 
Also why are we queuing it on account level?

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)* status: 4 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/34265#-N4SwSyqDDryax56iDlq:-N4Uwvkb5VSicNCTS16b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b21f6305ed770ffb62893dc124ef4ae926224e3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/MonitoredServiceListItemDTO.java#L40)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should name this better. serviceEnabled does not communicate the intent. I think we can rename this to something like serviceLicenseEnabled 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 956 at r1](https://reviewable.io/reviews/harness/harness-core/34265#-N4SHkxPCD0DECjrZJy0:-N4Uyzuj8GsRvCSjvUsD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b21f6305ed770ffb62893dc124ef4ae926224e3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L956)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

lets use hash set here so that checking if monitoredservicerdto.serviceref operation because O(1) 
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1034 at r1](https://reviewable.io/reviews/harness/harness-core/34265#-N4SxGZU3u9DJTJbdUjs:-N4Uz5on8FRXj1rtkeab:bckwbku) ([raw file](https://github.com/harness/harness-core/blob/b21f6305ed770ffb62893dc124ef4ae926224e3f/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1034)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

..* which monitored service is enabled *..
</blockquote></details>

We need the information about activation state of the "Service" on all monitored-services having that particular "Service".
Queuing on account level because other projects can have monitored-services for that "Service" which might be enabled.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)* status: 1 change requests. 2. unresolved discussions.

**Comment by arpit-harness** [comment]
trigger ti2

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)* status: 1 change requests. 2. unresolved discussions.

**Review by deepak-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265#-:-N4azAp51an65ZCK04Hu:bnfp4nl)* status: 1 change requests. 2. unresolved discussions.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34265)* status: :shipit: complete! ✓

**Pull request merged**
