### PR TITLE
[feat]: [PL-39365]: Adds FF to show/hide default role at org and project level

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Adds FF to show/hide default role at org and project level
- PL_HIDE_PROJECT_LEVEL_DEFAULT_ROLE
- PL_HIDE_ORGANIZATION_LEVEL_DEFAULT_ROLE

Test:
- IF FF PL_HIDE_PROJECT_LEVEL_DEFAULT_ROLE is enabled roles list api returns custom role only
- IF FF PL_HIDE_ORGANIZATION_LEVEL_DEFAULT_ROLE is enabled roles list api returns custom role only
- Except above two cases roles list api returns both managed and custom roles

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50617)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger commonchecks

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50617)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 540 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_YfMRX2698T19KjRhN:-N_YfMRX2698T19KjRhO:bef94q0) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L540)):*
> ```Java
>   PL_HELM2_DELEGATE_BANNER("FF for adding banner on delegate to mention deprecation of helm 2", HarnessTeam.PL),
>   PL_HIDE_LAUNCH_NEXTGEN("FF to hide Launch NextGen button", HarnessTeam.PL),
>   PL_HIDE_ORGANIZATION_LEVEL_DEFAULT_ROLE("FF to hide organization level default roles", HarnessTeam.PL),
> ```

Change PL_HIDE_ORGANIZATION_LEVEL_DEFAULT_ROLE to PL_HIDE_ORGANIZATION_LEVEL_MANAGED_ROLE
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 541 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_YfQz1-lDq5wF5UKzP:-N_YfQz1-lDq5wF5UKzQ:brsbi5f) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L541)):*
> ```Java
>   PL_HIDE_LAUNCH_NEXTGEN("FF to hide Launch NextGen button", HarnessTeam.PL),
>   PL_HIDE_ORGANIZATION_LEVEL_DEFAULT_ROLE("FF to hide organization level default roles", HarnessTeam.PL),
>   PL_HIDE_PROJECT_LEVEL_DEFAULT_ROLE("FF to hide project level default roles", HarnessTeam.PL),
> ```

change to PL_HIDE_PROJECT_LEVEL_MANAGED_ROLE.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_Yf-H78WOw2T1soc0Q:-N_Yf-H84oZ05YSEdv5b:b-ghf1s2) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java#L104)):*
> ```Java
>         RoleFilter.builder().searchTerm(searchTerm).scopeIdentifier(scopeIdentifier);
> 
>     if ((nonNull(harnessScopeParams.getProjectIdentifier())
> ```

Use io.harness.data.structure.EmptyPredicate#isEmpty(java.lang.String) as that abstracts the java util and if changed in future will change in one place.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_Yf5y61843M5aJzcDV:-N_Yf5y61843M5aJzcDW:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java#L108)):*
> ```Java
>                 FeatureName.PL_HIDE_PROJECT_LEVEL_DEFAULT_ROLE, harnessScopeParams.getAccountIdentifier()))) {
>       roleFilterBuilder.managedFilter(ONLY_CUSTOM);
>     } else if ((nonNull(harnessScopeParams.getOrgIdentifier())
> ```

same as above.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 540 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_YfMRX2698T19KjRhN:-N_Ym8l76eR6xpTyZLRd:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L540)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Change PL_HIDE_ORGANIZATION_LEVEL_DEFAULT_ROLE to PL_HIDE_ORGANIZATION_LEVEL_MANAGED_ROLE
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 541 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_YfQz1-lDq5wF5UKzP:-N_YmB7j-WZtQWsGAjes:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L541)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

change to PL_HIDE_PROJECT_LEVEL_MANAGED_ROLE.
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java` line 104 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_Yf-H78WOw2T1soc0Q:-N_YmDUF9_858w2pkifH:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java#L104)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Use io.harness.data.structure.EmptyPredicate#isEmpty(java.lang.String) as that abstracts the java util and if changed in future will change in one place.
</blockquote></details>

Fixed

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/50617#-N_Yf5y61843M5aJzcDV:-N_YmJXXBFR4tAj0Myi-:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/2221c517995d3cef3819894d400a946d7ec201a2/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleResourceImpl.java#L108)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Fixed

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50617)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50617#-:-N_Z7LO67uN5DxokJBFK:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
