### PR TITLE
[feat]: [PL-29063]: add UTs, update to Map and remove explicit expiry check flow

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Follow up changes from - https://github.com/harness/harness-core/pull/40981 
Fixed 2 main points:
1) Removed explicit check for 'token-expired' and handled it in process JWT flow itself. 
2) Returning "map' of ID, value and then matching, so as to be more readable. 

Major refactoring of moving to ng-manager to be done in separate PR. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41105)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/41105#-NIXR6k3-QB_vIAKcVXC:-NIep11OEbOnbA0Mg-mU:b-nq4hyu) ([raw file](https://github.com/harness/harness-core/blob/e01b03bac9337316576680cc30f182196ea823e9/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L66)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this?
</blockquote></details>

static initialization, to use it as a class level member, rather than method. 
Thanks

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41105)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by piyush-harness** [comment]
*[`965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/41105#-NIXR6k3-QB_vIAKcVXC:-NIf3egODheTpZI-Hf8D:b-qv9i8) ([raw file](https://github.com/harness/harness-core/blob/e01b03bac9337316576680cc30f182196ea823e9/965-api-key-filter/src/main/java/io/harness/util/JWTTokenFlowAuthFilterUtils.java#L66)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

static initialization, to use it as a class level member, rather than method. 
Thanks
</blockquote></details>

This can be injected

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41105)* status: :shipit: complete! ✓

**Pull request merged**
