### PR TITLE
[fix]: [PIE-8856]: Adding autol-log-context and logs for better execution-flow tracking

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45490)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/45490#-NRBhAGN15D3gs8ROyXj:-NRBhAGN15D3gs8ROyXk:bwanzfj) ([raw file](https://github.com/harness/harness-core/blob/26184735416645b3764845f5f0d3f26a9815890a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L118)):*
> ```Java
>       String waitInstanceId =
>           waitNotifyEngine.waitForAllOn(publisherName, callback, callbackIds.toArray(new String[0]));
>       log.info("SpawnChildrenRequestProcessor registered a waitInstance with id: {}", waitInstanceId);
> ```

Let's add the same log line in SpawnChildRequestProcessor, just to be consistent.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/45490#-NRBhAGN15D3gs8ROyXj:-NRBhIER1_INdrKHMzhW:bbjr4uk) ([raw file](https://github.com/harness/harness-core/blob/26184735416645b3764845f5f0d3f26a9815890a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L118)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Let's add the same log line in SpawnChildRequestProcessor, just to be consistent. 
</blockquote></details>

Ignore, it is already added

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45490)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45490)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 110 at r3](https://reviewable.io/reviews/harness/harness-core/45490#-NRC53HX7Q6-SgGi9BmA:-NRC53HY9xfMY6qKY88q:b-89952w) ([raw file](https://github.com/harness/harness-core/blob/26184735416645b3764845f5f0d3f26a9815890a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L110)):*
> ```Java
>                 .build();
> 
>         waitNotifyEngine.waitForAllOn(publisherName, maxConcurrentChildCallback, uuid);
> ```

can we add here as well

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45490)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 110 at r3](https://reviewable.io/reviews/harness/harness-core/45490#-NRC53HX7Q6-SgGi9BmA:-NRCC0qc483JGCFqAXgG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26184735416645b3764845f5f0d3f26a9815890a/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L110)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add here as well
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45490)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45490)* status: :shipit: complete! ✓

**Pull request merged**
