### PR TITLE
feat:[CDS-53601]:Move a few read queries to secondary Node

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
## Describe your changes
Moving a few queries for environments and artifacts to secondary.

Narendra helped us get a query pattern which we wanted to move to secondary wherever possible.
This was the following pattern for Artifacts ({"artifactStreamId":"1","status":{"$in:"},"artifactSourceName":"1"},) and Environments (appIds: {$in:})
image

Also he helped get logs during which alert was rased.
Logs can be found in the ticket.
Based on these values we modified queries which matched the above mentioned criterias

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44065)

### CODE REVIEW

**Review by Fernando-Dourado — COMMENTED** [review]
Could you explain how to choose when to hit the secondary or not? I see some services use true parameters and others false and is not clear to me why.

> Reviewed 25 of 33 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44065#-:-NOjJrEX8st8bd6bUKfj:bovv7a4)* status: Some of the checks are too old. 33 file(s) to review. 0 of 2 approvals obtained.  (waiting on @Fernando-Dourado)

**Comment by abhinavmittal-harness** [comment]
trigger messagecheck

**Review by hextechpal — APPROVED** [review]
> Reviewed 25 of 33 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44065)* status: Some of the checks are too old. 1 of 2 approvals obtained.  (waiting on @Fernando-Dourado)

**Review by Fernando-Dourado — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44065#-:-NOo8gbN1pb4IcvEZn69:bnfp4nl)* status: Some of the checks are too old.

**Review by lasdox — APPROVED** [review]
> Reviewed 24 of 33 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44065)* status: 1 file(s) to review. 1 of 2 approvals obtained.  (waiting on @Fernando-Dourado)

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44065)* status: :shipit: complete! ✓

**Pull request merged**
