### PR TITLE
feat: [PL-27264]: Adding a build-cleaner tool to generate/update build files

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

This is the first commit to check-in the build cleaner tool which can generate the BUILD files automatically.

Other than the tools/ directory changes, here are some noteworthy changes:

1) Lombok target now exports  "@maven//:com_google_code_findbugs_annotations" and "@maven//:org_slf4j_slf4j_api" too. Without these two, build does not succeed -- but these are not statically imported, so no way for the tool to add these dependencies.
2) Added javaparser package to WORKSPACE and upgraded version of the commons-cli, these were required for the code borrowed from rules_jvm. https://harness.atlassian.net/browse/SECOPS-3677 security review ticket for the same.
3) maven_manifest_override.txt -- this is required to resolve targets, which can come from multiple dependencies.
4) maven_manifest.json -- this file is generated after parsing all the maven packages. This file would have to updated anytime we add new maven dependencies. TODO -- automate that process too.
5) main_maven_install.json - this is autogenerated after adding new packages in the WORKSPACE.  Ran " bazel run @unpinned_maven//:pin"

## Checklist
- [ X] I've documented the changes in the PR description.
- [ X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36036)

**Comment by gn-harness** [comment]
trigger messagecheck

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 10 of 22 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 2 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by diptiman-adak — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)* status: 22 file(s) to review.

**Review by gn-harness — COMMENTED** [review]
> Reviewed 5 of 22 files at r1, 12 of 12 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)* status: 22 file(s) to review.

**Comment by jennyjames21** [comment]
:lgtm:

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 5 of 22 files at r1, 12 of 12 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36036)* status: :shipit: complete! ✓

**Pull request merged**
