### PR TITLE
[fix]: [CCM-7964]: Fix for AWS-S3-Sync issues with large data volumes

### PR DESCRIPTION
**Pull request by abhijeet-harness**
… transfer

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34460)

### CODE REVIEW

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34460)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`280-batch-processing/src/main/java/io/harness/batch/processing/service/impl/AwsS3SyncServiceImpl.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/34460#-N5-IiB-EqEERupnhwB8:-N5-IiB-EqEERupnhwB9:b-bbbvfp) ([raw file](https://github.com/harness/harness-core/blob/df042135f2291afad7ed8879eb6cbc323a8b98d9/280-batch-processing/src/main/java/io/harness/batch/processing/service/impl/AwsS3SyncServiceImpl.java#L71)):*
> ```Java
> 
>       final ArrayList<String> multipartChunkSizeCmd =
>           Lists.newArrayList("aws", "configure", "set", "default.s3.multipart_chunksize", "16MB");
> ```

We can set this in the docker image itself. So that the config is available in all s3 sync commands.

**Review by nikunj-badjatya — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34460)* status: 13 file(s) to review. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEAWSConnectorValidator.java` line 350 at r2](https://reviewable.io/reviews/harness/harness-core/34460#-N59X-m_0icCN-ipmXGN:-N59X-ma12mTu_jBMXYP:buimrvv) ([raw file](https://github.com/harness/harness-core/blob/5c726e1fd87f63d01878933311b6a3ad1cabac1b/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEAWSConnectorValidator.java#L350)):*
> ```Java
>     try {
>       ObjectListing s3BucketObject = awsClient.getBucket(credentialsProvider, s3BucketName, s3PathPrefix);
>       List<S3ObjectSummary> s3ObjectSummaries = new ArrayList<>(s3BucketObject.getObjectSummaries());
> ```

This could be memory intensive in some cases. Lets use the Iterable method which is lazy loading approach.
___
*[`dockerization/batch-processing/Dockerfile-batch-processing-jenkins-k8-gcr` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/34460#-N59XOvg925e_oRmSWXD:-N59XOvg925e_oRmSWXE:b-wls6gf) ([raw file](https://github.com/harness/harness-core/blob/5c726e1fd87f63d01878933311b6a3ad1cabac1b/dockerization/batch-processing/Dockerfile-batch-processing-jenkins-k8-gcr#L18)):*
> ```
> RUN curl -LO https://aka.ms/downloadazcopy-v10-linux && tar -xvf downloadazcopy-v10-linux && cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/
> 
> # Add AWS S3 transfer config
> ```

In long term we can put these in a script instead.

**Comment by abhijeet-harness** [comment]
trigger ti4

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 6 of 9 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34460)* status: :shipit: complete! ✓

**Pull request merged**
