### PR TITLE
feat: [CDS-57899]: SSHJ Connection and Exec implementation

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46303)

### CODE REVIEW

**Comment by arvind-choudhary-h** [comment]
trigger ut0,ut2,ut6,ut7

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46303)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTs-zQVEgdxjnzxKMR6:-NTs-zQVEgdxjnzxKMR7:b-qc5oz3) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L84)):*
> ```Java
>         throw ex;
>       }
>       log.error("Command execution failed with error", ex);
> ```

Can we print an error msg to the console or supply ExecResponse with error message details?
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTs0CJe2T6P7i4CmiV6:-NTs0CJe2T6P7i4CmiV7:b-nwrpmw) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L87)):*
> ```Java
>       return ExecResponse.builder().output(null).exitCode(1).status(FAILURE).build();
>     } catch (Exception ex) {
>       log.error("Command execution failed with error", ex);
> ```

The same here.
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTryQLM7iTwy8mMnCjX:-NTryQLM7iTwy8mMnCjY:b-sx3ta5) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L167)):*
> ```Java
>     SSHClient session = null;
>     int retryCount = 0;
>     while (retryCount <= 6 && session == null) {
> ```

6 >> could be constant. 
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTs-nSY4Foqqc2MaDFj:-NTs-nSY4Foqqc2MaDFk:b-fxm7kw) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L169)):*
> ```Java
>     while (retryCount <= 6 && session == null) {
>       try {
>         TimeUnit.SECONDS.sleep(1);
> ```

1 >>  could be constant. 
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 186 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTryhJM3W0eTjcZm5Sv:-NTryhJM3W0eTjcZm5Sw:b-jdzumh) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L186)):*
> ```Java
>   }
> 
>   private SSHClient fetchSSHSession(SshSessionConfig config, LogCallback logCallback)
> ```

We print info and error messages to log, shouldn't we print some of them to the console(logCallback)
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 205 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzCdbAau6EIghiLAh:-NTrzCdbAau6EIghiLAi:b-ilz92u) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L205)):*
> ```Java
>           new LoginContext(config.getKerberosConfig().getPrincipal()),
>           new Oid(config.getKerberosConfig().getPrincipalWithRealm()));
>     } else if (config.getAccessType() != null && config.getAccessType() == USER_PASSWORD) {
> ```

Should we print the info message and in the console?
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 209 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzPBC8H0sH5zpaBiE:-NTrzPBC8H0sH5zpaBiF:b-nwrpmw) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L209)):*
> ```Java
>       client.authPassword(config.getUserName(), config.getSshPassword());
>     } else if (config.isKeyLess()) {
>       log.info("[SshSessionFactory]: SSH using KeyPath");
> ```

The same here.
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 225 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzblM9E_B1dWxMJZJ:-NTrzblM9E_B1dWxMJZK:b-nwrpmw) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L225)):*
> ```Java
>       client.authPublickey(config.getUserName(), openSSHKeyFile);
>     } else if (config.isVaultSSH()) {
>       log.info("[SshSessionFactory]: SSH using Vault SSH secret engine with SignedPublicKey: {} ",
> ```

The same here.
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 262 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzyN2E3iKU5rmgfO6:-NTrzyN2E3iKU5rmgfO7:b855opb) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L262)):*
> ```Java
>   protected SshjExecSession getExecSession(SshConnection sshConnection) throws SshClientException {
>     try {
>       SSHClient client = ((SshjConnection) sshConnection).getClient();
> ```

Minor  remove ;

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 167 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTryQLM7iTwy8mMnCjX:-NTvfyYO1tZziTLVryGB:b-v91aad) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L167)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

6 >> could be constant. 
</blockquote></details>

This logic I have to refactor later to use something like `RetryPolicy`. Most of the time, we are retrying here unnecessarily

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTs-nSY4Foqqc2MaDFj:-NTvg_9h5Rgr4IkITLJR:b-v91aad) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L169)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

1 >>  could be constant. 
</blockquote></details>

This logic I have to refactor later to use something like `RetryPolicy`. Most of the time, we are retrying here unnecessarily

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 87 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTs0CJe2T6P7i4CmiV6:-NTvihBXCPJ8dNoTNwEi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L87)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same here.
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTs-zQVEgdxjnzxKMR6:-NTvigoH2cqG3oMa-Zck:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L84)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we print an error msg to the console or supply ExecResponse with error message details?
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 186 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTryhJM3W0eTjcZm5Sv:-NTviomS9GVbhadLhtGh:begh8gy) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L186)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We print info and error messages to log, shouldn't we print some of them to the console(logCallback)
</blockquote></details>

Yes. Added.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 205 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzCdbAau6EIghiLAh:-NTvitWG80UbbILRvr4R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L205)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Should we print the info message and in the console?
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 209 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzPBC8H0sH5zpaBiE:-NTviu18BcrOCfmGPTrJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L209)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same here.
</blockquote></details>

Done.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 225 at r2](https://reviewable.io/reviews/harness/harness-core/46303#-NTrzblM9E_B1dWxMJZJ:-NTviv9DAXYaxIxZhy_u:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/03e00704c1d15f06dd0909856edb96ed43bffcab/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L225)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

The same here.
</blockquote></details>

Done.

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 10 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46303)* status: 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwORlKCK1TDyZT73dG:-NTwORlKCK1TDyZT73dH:b-sbmzra) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L127)):*
> ```Java
>   protected ScpResponse scpUploadInternal(ScpRequest scpRequest, SshConnection connection) throws SshClientException {
>     try (SshjScpSession scpSession = getScpSession(connection)) {
>       try (StreamingInMemorySourceFile sourceFile = new StreamingInMemorySourceFile(scpRequest.getFileProvider())) {
> ```

Minor - Begin transfer console log line is missing or it's logged in the caller method
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwOo1c9uT0SAclHuWN:-NTwOo1c9uT0SAclHuWO:bfpe6tz) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L153)):*
> ```Java
>       SFTPClient sftpClient = sftpSession.getSftpClient();
>       try (StreamingInMemoryDestFile dest = new StreamingInMemoryDestFile(new ByteArrayOutputStream())) {
>         String path = sftpClient.canonicalize(sftpRequest.getDirectory() + "/" + sftpRequest.getFileName());
> ```

Minor - Begin download console log line is missing or it's logged in the caller method
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwOrFaEQIyxCDXByl3:-NTwOrFaEQIyxCDXByl4:buhpwyf) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L157)):*
> ```Java
>         String content = dest.getOutputStream().toString(Charsets.UTF_8);
>         if (sftpRequest.isCleanup()) {
>           sftpClient.getSFTPEngine().remove(path);
> ```

Just for my reference the next line 'sftpClient.getSFTPEngine().remove(path); ' will remove the downloaded file from the delegate, right?
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 190 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwPNw23ynHaU8ng7mU:-NTwPNw23ynHaU8ng7mV:b47lq2s) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L190)):*
> ```Java
>       Session.Command cmd = session.exec("true");
>       String output = IOUtils.readFully(cmd.getInputStream()).toString();
>       cmd.join();
> ```

Just for my reference what cmd.join() is working? 
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 341 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwRsnD44cs8ZdtkaZI:-NTwRsnE3gGpfdmXyCiC:b-wo7bfv) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L341)):*
> ```Java
>           new String(getCopyOfKey()), config.getSignedPublicKey(), getPasswordFinder(config.getKeyPassphrase()));
>     }
>     keyProviders.add(openSSHKeyV1KeyFile);
> ```

qq, why do we need both openSSHKeyV1KeyFile and openSSHKeyFile?
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 344 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwRg5rBTxNbKvk85gg:-NTwRg5s6tKCIzrmcwSA:b-4zsg75) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L344)):*
> ```Java
> 
>     if (isNotEmpty(config.getKey()) && new String(config.getKey()).contains(" OPENSSH ")) {
>       OpenSSHKeyFile openSSHKeyFileUsingRSA = new OpenSSHKeyFile();
> ```

We are not using openSSHKeyFileUsingRSA for the time being, right? Because I see we haven't added in keyProviders.
___
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/StreamingInMemoryDestFile.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwSEdo-o1l6dWt84pU:-NTwSEdo-o1l6dWt84pV:b1i2bg1) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/StreamingInMemoryDestFile.java#L32)):*
> ```Java
> 
>   @Override
>   public OutputStream getOutputStream(boolean append) {
> ```

This is the same method as getOutputStream(), right? Or we are planning to do something with append?

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwORlKCK1TDyZT73dG:-NU0pg3u0o8WcilIEC0i:bh6mzq1) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L127)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Begin transfer console log line is missing or it's logged in the caller method
</blockquote></details>

It's called in #scpUpload method.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 153 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwOo1c9uT0SAclHuWN:-NU0pnGWCbO21MLMGaLl:buebgdj) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L153)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - Begin download console log line is missing or it's logged in the caller method
</blockquote></details>

It's called in caller.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwOrFaEQIyxCDXByl3:-NU0pu8rALHAaszNYIb8:bb77ufg) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L157)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Just for my reference the next line 'sftpClient.getSFTPEngine().remove(path); ' will remove the downloaded file from the delegate, right?
</blockquote></details>

Yes.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/StreamingInMemoryDestFile.java` line 32 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwSEdo-o1l6dWt84pU:-NU0rBax5MIi9FjxYkHi:b-qztv8v) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/StreamingInMemoryDestFile.java#L32)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This is the same method as getOutputStream(), right? Or we are planning to do something with append?
</blockquote></details>

Yes, it's the same. This append I believe it's specific to FileSystem type where it defines if we want to append content to already existing file or not.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 344 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwRg5rBTxNbKvk85gg:-NU0rl4H0BlwL2DntpJf:b-4mwl7o) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L344)):*
> openSSHKeyFileUsingRSA
Missed to add, probably during testing. Adding it back.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 341 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwRsnD44cs8ZdtkaZI:-NU10xAH3sQGjmPRtzmA:b-qalg4p) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L341)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, why do we need both openSSHKeyV1KeyFile and openSSHKeyFile?
</blockquote></details>

openSSHKeyFile are based on Standard RSA and other keys whereas  openSSHKeyV1KeyFile is based on new OpenSSH format.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java` line 190 at r4](https://reviewable.io/reviews/harness/harness-core/46303#-NTwPNw23ynHaU8ng7mU:-NU11bzjEcoc_RmBdYbA:b-l85ou3) ([raw file](https://github.com/harness/harness-core/blob/8ff9ff51f1a2936a5fd0c1f98ebfa110c8ecfdf9/960-api-services/src/main/java/io/harness/shell/ssh/client/sshj/SshjClient.java#L190)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Just for my reference what cmd.join() is working? 
</blockquote></details>

I believe it waits for the exit code of the Exec after script has completed executing and getting response. We can also provide timeout but anyways, we have interrupts that can handle it.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46303#-:-NUIyCVLE4OZBGSpr9Cs:bnfp4nl)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
trigger ut4,ut5,ut7

**Review by RishabhGupta34 — APPROVED** [review]

**Comment by arvind-choudhary-h** [comment]
trigger review

**Pull request merged**
