### PR TITLE
[feat]: [PIE-9194]: Add preservation info to Plan Node

### PR DESCRIPTION
**Pull request by namanvermah**
We're converting plan nodes to identity nodes in next step handler to handle cases related to retry failed pipeline wrt strategy. Over there, if the parent of previous node is identity then the next node is converted into identity. We won't want this conversion in rollback mode execution. 
In any case, the fact that a plan node needs to stay so should be known by the plan node, so that in future if we add any such conversion anywhere else, we can use this property to bypass the conversion.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45713)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45713)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/45713#-NRahmNy8oMhpJyXjs6A:-NRahmNy8oMhpJyXjs6B:b-vr7z3r) ([raw file](https://github.com/harness/harness-core/blob/56fb6898a98c5c145e8689d2b9ee0699cd2cb333/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L78)):*
> ```Java
>     // preserved, then return the node as is.
>     if (nextNode instanceof IdentityPlanNode
>         || (ExecutionModeUtils.isRollbackMode(executionMode) && ((PlanNode) nextNode).isPreserveInRollbackMode())) {
> ```

can we create a function instead of multiple condition in this OR?



_Code quote:_
```Java
(ExecutionModeUtils.isRollbackMode(executionMode) && ((PlanNode) nextNode).isPreserveInRollbackMode())
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45713)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/45713#-NRahmNy8oMhpJyXjs6A:-NRajY-OE8GyprC9U-po:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/56fb6898a98c5c145e8689d2b9ee0699cd2cb333/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L78)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create a function instead of multiple condition in this OR?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45713)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45713)* status: :shipit: complete! ✓

**Pull request merged**
