### PR TITLE
fix: [PL-39536]: Reframed user search query in CG

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
User search query on the CG users listing page does a mongo regex search for email and name. Since, this does not utilise the index efficiently, this PR reframes that query to use the index for "accountId" and "disabled" to perform a more optimal query.
Effect of the change- The number of keys examined has drastically reduced, since earlier the query was doing a filter on accountId and disabled, while now it uses an index on these fields and filters the email.
Testing:
1. Tested that the list users API works returns the correct user response with a search term.
2. Tested that the list users API works returns the correct user response without a search term.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49725)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49725)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 4193 at r1](https://reviewable.io/reviews/harness/harness-core/49725#-NYst7kI59j0ibbCC0eh:-NYst7kI59j0ibbCC0ei:b-j9ycai) ([raw file](https://github.com/harness/harness-core/blob/2e3c9c7770dd45baecae1d91bf11a242834dd159/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4193)):*
> ```Java
>       query = getSearchUserQuery(accountId, searchTerm, includeUsersPendingInviteAcceptance, includeDisabled);
>     } else {
>       query = getListUserQuery(accountId, includeUsersPendingInviteAcceptance, includeDisabled);
> ```

Can we write test cases to compare expected and generated query?

**Comment by tiwaritejas** [comment]
trigger uts

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49725)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 4193 at r1](https://reviewable.io/reviews/harness/harness-core/49725#-NYst7kI59j0ibbCC0eh:-NZ0eVyg9Cep9oSA27__:b-pi14qz) ([raw file](https://github.com/harness/harness-core/blob/2e3c9c7770dd45baecae1d91bf11a242834dd159/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L4193)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we write test cases to compare expected and generated query?
</blockquote></details>

Added a UT to verify for the returned user search query.

**Comment by tiwaritejas** [comment]
trigger uts

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49725)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger ut1

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49725)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
