### PR TITLE
[feat]: [PL-38920]: Internal API to list connectors across all accounts

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
As part of this added two things:
1. Support for accountIdentifer in the connectorInfoDTO.
2. Added a new internal API to get all the connectors for all the accounts.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: Some of the checks are too old. 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv7so69tF1z_AK6nmv:-NYv7so69tF1z_AK6nmw:bkd841h) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L128)):*
> ```Java
>         (CcmConnectorFilterPropertiesDTO) filterPropertiesDTO;
>     Criteria criteria = where(ConnectorKeys.accountIdentifier).in(ccmConnectorFilterPropertiesDTO.getAccountIds());
>     if (isNotEmpty(ccmConnectorFilterPropertiesDTO.getTypes())) {
> ```

Please confirm if this index accountId_orgId_projectId_type_status_deletedAt_decreasing_sort_Index in Connector is getting triggered and used.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: Some of the checks are too old. 12 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv6l2311tiuPwG9CDM:-NYv6l2311tiuPwG9CDN:b-d7f26m) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L392)):*
> ```Java
>   @Hidden
>   @ApiOperation(value = "Gets all connectors list", nickname = "getCCMConnectorList", hidden = true)
>   public ResponseDTO<PageResponse<ConnectorResponseDTO>> allConnectors(
> ```

Mark this as internal api. Use annotation @InternalApi
___
*[`954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv9BggAz9sBc3f6WJH:-NYv9BggAz9sBc3f6WJI:btknkdx) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java#L45)):*
> ```Java
> @Schema(
>     name = "CcmConnectorFilterProperties", description = "Properties of the Ccm Connector Filter defined in Harness")
> public class CcmConnectorFilterPropertiesDTO extends FilterPropertiesDTO {
> ```

Can we rename this DTO to something generic and internal? This can be used to fetch any other type of connectors as well.
___
*[`954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYvCaAE7iPlLvi82qF4:-NYvCaAE7iPlLvi82qF5:b-ydyzab) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java#L49)):*
> ```Java
>   @Schema(description = ConnectorConstants.CONNECTOR_STATUS_LIST) List<ConnectivityStatus> connectivityStatuses;
>   @Schema(description = "CCM Connector filter.") CcmConnectorFilter ccmConnectorFilter;
>   @Schema(description = "List of account ids", required = true) List<String> accountIds;
> ```

Rename this to accountIdentifiers

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: Some of the checks are too old. 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv7so69tF1z_AK6nmv:-NYvD0kC7PmsOqRqtNo1:b-czbb5b) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L128)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Please confirm if this index accountId_orgId_projectId_type_status_deletedAt_decreasing_sort_Index in Connector is getting triggered and used.
</blockquote></details>

This index will only be able to use accountId field because there is no criteria on org and project identifiers.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: Some of the checks are too old. 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv7so69tF1z_AK6nmv:-NYvhLfD95B2CH2GCRd6:bxbsxyl) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L128)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This index will only be able to use accountId field because there is no criteria on org and project identifiers.
</blockquote></details>

I think it would even consider type and status if present in input.

**Review by iamanmolm — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: 13 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java` line 392 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv6l2311tiuPwG9CDM:-NYwEbha13efrcBsSYj2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ConnectorResource.java#L392)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Mark this as internal api. Use annotation @InternalApi
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv7so69tF1z_AK6nmv:-NYwEfW38HyNVr4dFVha:bvv83wt) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/440-connector-nextgen/src/main/java/io/harness/connector/impl/ConnectorFilterServiceImpl.java#L128)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think it would even consider type and status if present in input.
</blockquote></details>

No it doesn't. Only index that was working was accountId_orgId_projectId_name_Index and type_nextTokenRenewIteration
___
*[`954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java` line 45 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYv9BggAz9sBc3f6WJH:-NYwEr4S--TXLcbw_qfZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java#L45)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can we rename this DTO to something generic and internal? This can be used to fetch any other type of connectors as well.
</blockquote></details>

Done.
___
*[`954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/49657#-NYvCaAE7iPlLvi82qF4:-NYwErW_2zh9OUUn8oIC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a2b280d459f8877e8ee3540911de01ef18f3ded/954-connector-beans/src/main/java/io/harness/connector/CcmConnectorFilterPropertiesDTO.java#L49)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Rename this to accountIdentifiers
</blockquote></details>

Done.

**Comment by iamanmolm** [comment]
trigger uts

**Review by nikunj-badjatya — DISMISSED** [review]
> Reviewed 3 of 12 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: 11 file(s) to review. 2 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Comment by iamanmolm** [comment]
trigger uts

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: 1 change requests. 1. unresolved discussions. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/entities/Connector.java` line 216 at r3](https://reviewable.io/reviews/harness/harness-core/49657#-NZQLVjO8IGkS-pfB9SG:-NZQLVjO8IGkS-pfB9SH:b-cuo6hg) ([raw file](https://github.com/harness/harness-core/blob/b5f9c9b7d310bec7f82afdd43b1826918e87757f/440-connector-nextgen/src/main/java/io/harness/connector/entities/Connector.java#L216)):*
> ```Java
>                  .build())
>         .add(SortCompoundMongoIndex.builder()
>                  .name("accountId_status_decreasing_sort_Index")
> ```

Please create OPS ticket and get these index approved by DBRE.

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 43 of 43 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: 43 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by iamanmolm** [comment]
trigger uts

**Comment by iamanmolm** [comment]
trigger ut0

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: 44 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by iamanmolm — COMMENTED** [review]
> Reviewed 38 of 43 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: 44 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 12 files at r1, 8 of 10 files at r2, 38 of 43 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49657)* status: :shipit: complete! ✓

**Pull request merged**
