### PR TITLE
[fix]: [CDS-69419]: Cleaned up jsch logs

### PR DESCRIPTION
**Pull request by arvind-choudhary-h**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47927)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47927)* status: 11 file(s) to review. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitCommandTask.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/47927#-NVcDZjG0Vphv4Y07wKL:-NVcDZjG0Vphv4Y07wKM:b-1pz5ef) ([raw file](https://github.com/harness/harness-core/blob/43f7d6ae93a29779be4f02774615e6d1b230b5de/930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitCommandTask.java#L178)):*
> ```Java
>     } catch (JschClientException ex) {
>       log.error(GIT_YAML_LOG_PREFIX + "Exception in processing GitTask {}",
>           ExceptionSanitizer.sanitizeTheMessage(ex.getMessage()));
> ```

nit, confirming, you don't need the full exception to be logged, right?
___
*[`960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java` line 435 at r2](https://reviewable.io/reviews/harness/harness-core/47927#-NVcDjZM40bZ-bBhTinT:-NVcDjZM40bZ-bBhTinU:b-6ktjen) ([raw file](https://github.com/harness/harness-core/blob/43f7d6ae93a29779be4f02774615e6d1b230b5de/960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java#L435)):*
> ```Java
>         .onFailedAttempt(event -> {
>           if (event.getLastFailure() instanceof TransportException) {
>             log.info(failedAttemptMessage, event.getAttemptCount(), event.getLastFailure().getMessage());
> ```

nit, these are intentional info logs or should these be error logs?

**Comment by arvind-choudhary-h** [comment]
trigger uts

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitCommandTask.java` line 178 at r2](https://reviewable.io/reviews/harness/harness-core/47927#-NVcDZjG0Vphv4Y07wKL:-NVlQWLi8twMrRfhwvE-:bflm3xv) ([raw file](https://github.com/harness/harness-core/blob/43f7d6ae93a29779be4f02774615e6d1b230b5de/930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitCommandTask.java#L178)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, confirming, you don't need the full exception to be logged, right?
</blockquote></details>

No no, just message is enough here if we know it's jschClientException.

**Comment by arvind-choudhary-h** [comment]
*[`960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java` line 435 at r2](https://reviewable.io/reviews/harness/harness-core/47927#-NVcDjZM40bZ-bBhTinT:-NVlQb0J8HUSYmiDvkhr:b-4b14h1) ([raw file](https://github.com/harness/harness-core/blob/43f7d6ae93a29779be4f02774615e6d1b230b5de/960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java#L435)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

nit, these are intentional info logs or should these be error logs?
</blockquote></details>

These are retry logs. We have one error log if all of them fails.

**Comment by arvind-choudhary-h** [comment]
trigger messagecheck

**Review by abhinavsingh1196 — APPROVED** [review]

**Comment by abhinavsingh1196** [comment]
trigger review

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47927)* status: 11 file(s) to review.

**Pull request merged**
