### PR TITLE
[feat]: [CDS-53178]: Modify GitOps PR Title

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Provides support for Custom PR title created by Harness GitOps steps -> UpdateReleaseRepoStep, CreatePRStep

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)

### CODE REVIEW

**Comment by mankrit-singh** [comment]
trigger messagecheck

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepParams.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/43665#-NNlZBU9A688RA-XYmj1:-NNlZBUACFLkYvGN_C0k:b-exv67s) ([raw file](https://github.com/harness/harness-core/blob/09135d4faae5ef9142fa508f7d1198574176ee04/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStepParams.java#L23)):*
> ```Java
> @OwnedBy(HarnessTeam.GITOPS)
> public class UpdateReleaseRepoStepParams extends UpdateReleaseRepoBaseStepInfo implements GitOpsSpecParameters {
>   ParameterField<String> prTitle;
> ```

nit, you can add the field in BaseStepInfo. BothStepInfo and StepParams extend it.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java` line 308 at r1](https://reviewable.io/reviews/harness/harness-core/43665#-NNlZP5F9hs8GaiynmqD:-NNlZP5F9hs8GaiynmqE:b-nep5ys) ([raw file](https://github.com/harness/harness-core/blob/09135d4faae5ef9142fa508f7d1198574176ee04/930-delegate-tasks/src/main/java/io/harness/delegate/task/git/NGGitOpsCommandTask.java#L308)):*
> ```Java
>       logCallback = markDoneAndStartNew(logCallback, CreatePR, commandUnitsProgress);
> 
>       String prTitle = gitOpsTaskParams.getPrTitle();
> ```

nit, you can use ternary operator, also use StringUtils.isEmpty instead of null check

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/43665#-NNm2Sqe2XAy_HvZoe9t:-NNm2Sqe2XAy_HvZoe9u:b-hkmlkh) (no related file):*
@mankrit-singh : Please add UTs also.

___

**Comment by mankrit-singh** [comment]
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

@mankrit-singh : Please add UTs also.
</blockquote></details>

sure

**Review by meenaravichandran1 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 5 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 5 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43665)* status: :shipit: complete! ✓

**Pull request merged**
