### PR TITLE
feat: [cds-46278]: Copy templates permission migration

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
We have introduced a new Copy Templates permission, We want to provide this permission to all the existing non-harness managed roles which already have Template Access permission, therefore we wrote the migration for the same

## Checklist
- [ YES ] I've documented the changes in the PR description.
- [ YES ] I've tested this change either in PR or local environment.
- [ YES ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39945)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/39945#-NGpmxoU95EuVy1righF:-NGpmxoU95EuVy1righG:ben7uoe) ([raw file](https://github.com/harness/harness-core/blob/5f42da567d657b01f63dd0a0fa8873de74bca482/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L54)):*
> ```Java
>     log.info(DEBUG_MESSAGE + "Started running...");
>     try {
>       SecurityContextBuilder.setContext(new ServicePrincipal(TEMPLATE_SERVICE.getServiceId()));
> ```

should this not be "NG_MANAGER" ?

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/39945#-NGpncQ6CPrt_E6XLmCd:-NGpncQ6CPrt_E6XLmCe:b-putdg5) ([raw file](https://github.com/harness/harness-core/blob/5f42da567d657b01f63dd0a0fa8873de74bca482/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L69)):*
> ```Java
>     try {
>       List<AccountDTO> allAccounts = CGRestUtils.getResponse(accountClient.getAllAccounts());
>       List<String> distinctAccountIds = allAccounts.stream()
> ```

this should be called "nextgenAccounts"

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/39945#-NGpnt0R4Y5_zBk0txWd:-NGpnt0R4Y5_zBk0txWe:b-2q8pni) ([raw file](https://github.com/harness/harness-core/blob/5f42da567d657b01f63dd0a0fa8873de74bca482/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L80)):*
> ```Java
>       addCopyTemplatesPermissionForAccountRoles(distinctAccountIds);
>     } catch (Exception ex) {
>       log.error(DEBUG_MESSAGE + " Fetching all accounts failed : ", ex);
> ```

This message is not correct.
The try block is doing 2 things here
- fetch all accounts
- addCopyTemplatesPermissionForAccountRoles


We should use 2 different try/catch blocks with individual work items so that we can handle them in a better way

- If we failed to fetch accounts, we should not swallow the exception. It should be thrown with logging the exception trace

**Comment by utkarshchoubey-harness** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/39945#-NGpmxoU95EuVy1righF:-NGpmxoU95EuVy1righG:ben7uoe) ([raw file](https://github.com/harness/harness-core/blob/5f42da567d657b01f63dd0a0fa8873de74bca482/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L54)):_
> 
> > ```java
> >     log.info(DEBUG_MESSAGE + "Started running...");
> >     try {
> >       SecurityContextBuilder.setContext(new ServicePrincipal(TEMPLATE_SERVICE.getServiceId()));
> > ```
> 
> should this not be "NG_MANAGER" ?

Done

**Comment by utkarshchoubey-harness** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/39945#-NGpncQ6CPrt_E6XLmCd:-NGpncQ6CPrt_E6XLmCe:b-putdg5) ([raw file](https://github.com/harness/harness-core/blob/5f42da567d657b01f63dd0a0fa8873de74bca482/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L69)):_
> 
> > ```java
> >     try {
> >       List<AccountDTO> allAccounts = CGRestUtils.getResponse(accountClient.getAllAccounts());
> >       List<String> distinctAccountIds = allAccounts.stream()
> > ```
> 
> this should be called "nextgenAccounts"

Done

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 198 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGulPqs4RjenkZ75cuA:-NGulPqs4RjenkZ75cuB:bq4oda6) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L198)):*
> ```Java
>            */
> 
>           if (roleResponseDTO.getRole().getPermissions() == null) {
> ```

lets use EmptyPredicate.isEmpty() instead

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 223 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGumAs9AnmPkIXeccyw:-NGumAs9AnmPkIXeccyx:b-2ie1ep) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L223)):*
> ```Java
>                                         .tags(roleDto.getTags())
>                                         .build();
>               getResponse(accessControlAdminClient.updateRole(
> ```

we should log this response in some way to be able to debug

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39945)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 228 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGumQhVBB2R5NvQ257R:-NGumQhVBB2R5NvQ257S:bypwo3f) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L228)):*
> ```Java
>             } catch (Exception exception) {
>               log.error(
>                   String.format("[CopyTemplatesPermissionRoleUpdate] Unexpected error occurred while updating role: %s",
> ```

we can use our debug line here

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 235 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGumjXzAtiA-7A5Xze3:-NGumjXzAtiA-7A5Xze4:b-vhto4b) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L235)):*
> ```Java
>         }
> 
>         pageIndex++;
> ```

can we bring pageIndex++ to the top just after we fetch 
```getResponse(accessControlAdminClient.getRoles(
            pageIndex, DEFAULT_PAGE_SIZE, accountId, orgIdentifier, projectIdentifier, null));``` just to be extra safe that this loop does not go into infinite loop
```




_Code quote:_
```Java
        pageIndex
```

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 124 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGun3nH4H_C8lBILA7D:-NGun3nH4H_C8lBILA7E:bfysc8e) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L124)):*
> ```Java
>       } while (true);
>     } catch (Exception ex) {
>       log.error(DEBUG_MESSAGE + " Fetching Organizations failed : ", ex);
> ```

is this message correct that "Fetching organisations failed" ?
we should again split up into multiple try catch here

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39945)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 124 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGun3nH4H_C8lBILA7D:-NGutn7yAOBfyXIi_CRo:bh7pb97) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L124)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this message correct that "Fetching organisations failed" ?
we should again split up into multiple try catch here 
</blockquote></details>

Message is correct, if it fails inside any other child function, it has its own try catch block inside it and proper logging is there inside it as well
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 235 at r6](https://reviewable.io/reviews/harness/harness-core/39945#-NGumjXzAtiA-7A5Xze3:-NGuq2Eb4T9Q125scD-c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8d89c4d28cab3e7912bf8d1bf464880bf7fd4547/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L235)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we bring pageIndex++ to the top just after we fetch 
```getResponse(accessControlAdminClient.getRoles(
            pageIndex, DEFAULT_PAGE_SIZE, accountId, orgIdentifier, projectIdentifier, null));``` just to be extra safe that this loop does not go into infinite loop
```

</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java` line 137 at r7](https://reviewable.io/reviews/harness/harness-core/39945#-NGvENQsCVU-vEzH9bkY:-NGvENQsCVU-vEzH9bkZ:bj6djhy) ([raw file](https://github.com/harness/harness-core/blob/971a137477e8f026008fde1036d5923dc6d0c6a0/120-ng-manager/src/main/java/io/harness/ng/core/migration/CopyTemplatesPermissionRoleUpdate.java#L137)):*
> ```Java
>         Criteria criteria = Criteria.where("accountIdentifier")
>                                 .is(accountId)
>                                 .and("orgIdentifier")
> ```

nit: we can use ProjectKeys.orgIdentifier for this

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39945)* status: :shipit: complete! ✓

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39945)* status: :shipit: complete! ✓

**Pull request merged**
