### PR TITLE
feat: [CDS-47022]: added service for ASG

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 11 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: 30 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — DISMISSED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/resources/CDNGPipelineConfigurationResourceTest.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHuKB8BCEbZLSNqHqf:-NIHuKBB8Do9AzEVOSAm:b-4d2er3) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/resources/CDNGPipelineConfigurationResourceTest.java#L90)):*
> ```Java
>             ExecutionStrategyType.BLUE_GREEN, ExecutionStrategyType.DEFAULT));
>     /*
>     Assertions commented as these service definitions are currently not supported
> ```

nit: remove commented code

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgConfigurationManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv3J55jF4eRB-YMvw:-NIHv3J55jF4eRB-YMvx:b-qeneiz) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgConfigurationManifest.java#L51)):*
> ```Java
> @SimpleVisitorHelper(helperClass = AsgConfigurationManifestVisitorHelper.class)
> @TypeAlias("asgConfigurationManifest")
> @OwnedBy(CDC)
> ```

nit: CDP

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgLaunchTemplateManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv67t3aLBUOvMC7I0:-NIHv67t3aLBUOvMC7I1:b-qeneiz) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgLaunchTemplateManifest.java#L51)):*
> ```Java
> @SimpleVisitorHelper(helperClass = AsgLaunchTemplateManifestVisitorHelper.class)
> @TypeAlias("asgLaunchTemplateManifest")
> @OwnedBy(CDC)
> ```

nit: CDP

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScalingPolicyManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv7uJEk1UswH8oKAV:-NIHv7uJEk1UswH8oKAW:b-qeneiz) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScalingPolicyManifest.java#L51)):*
> ```Java
> @SimpleVisitorHelper(helperClass = AsgConfigurationManifestVisitorHelper.class)
> @TypeAlias("asgScalingPolicyManifest")
> @OwnedBy(CDC)
> ```

nit: CDP

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScheduledUpdateGroupActionManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv9dD7x_VAOebcQKj:-NIHv9dD7x_VAOebcQKk:b-qeneiz) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScheduledUpdateGroupActionManifest.java#L51)):*
> ```Java
> @SimpleVisitorHelper(helperClass = AsgScheduledUpdateGroupActionManifestVisitorHelper.class)
> @TypeAlias("asgScheduledUpdateGroupActionManifest")
> @OwnedBy(CDC)
> ```

nit: CDP

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 14 of 30 files at r1, 15 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: 16 file(s) to review. 0 of 2 approvals obtained.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: 20 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/resources/CDNGPipelineConfigurationResourceTest.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHuKB8BCEbZLSNqHqf:-NIHzays50klEiEehxri:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/resources/CDNGPipelineConfigurationResourceTest.java#L90)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

nit: remove commented code
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgConfigurationManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv3J55jF4eRB-YMvw:-NIHzeQK9fdjc2R4HCV5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgConfigurationManifest.java#L51)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

nit: CDP
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgLaunchTemplateManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv67t3aLBUOvMC7I0:-NIHziDa6QMrexY27VRv:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgLaunchTemplateManifest.java#L51)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

nit: CDP
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScalingPolicyManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv7uJEk1UswH8oKAV:-NIHzkaD9mbqDA9p7f-X:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScalingPolicyManifest.java#L51)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

nit: CDP
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScheduledUpdateGroupActionManifest.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/40849#-NIHv9dD7x_VAOebcQKj:-NIHzmVN-MJR3-hAzFuP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6c117aa9b21601c931ce19a91b15457098924a01/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScheduledUpdateGroupActionManifest.java#L51)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

nit: CDP
</blockquote></details>

done

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by arvind-choudhary-h — APPROVED** [review]

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by arvind-choudhary-h — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849#-:-NIIH_zkDLuNVw42LSTF:bnfp4nl)* status: 20 file(s) to review.

**Review by vitsafronovici — COMMENTED** [review]
> Reviewed 10 of 30 files at r1, 14 of 16 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: 20 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 14 of 16 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40849)* status: :shipit: complete! ✓

**Pull request merged**
