### PR TITLE
fix: [PL-27376]: Resource Group Async Reconciliation Handler

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36498)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36498)

**Comment by reetika04** [comment]
trigger messagecheck

**Comment by reetika04** [comment]
trigger messagecheck

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36498)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/reconciliation/ResourceGroupAsyncReconciliationHandler.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/36498#-N9kAl9w8bo8eX24wumM:-N9kAl9w8bo8eX24wumN:boewru) ([raw file](https://github.com/harness/harness-core/blob/1501c38826dac1a8dff28c10629f2bf46212b595/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/reconciliation/ResourceGroupAsyncReconciliationHandler.java#L42)):*
> ```Java
>   @Inject private final MongoTemplate mongoTemplate;
>   @Inject private final ResourceGroupService resourceGroupService;
>   @Inject private final ResourceGroupValidatorImpl resourceGroupValidatorImpl;
> ```

Variable names do not have impl in them.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36498)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/reconciliation/ResourceGroupAsyncReconciliationHandler.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/36498#-N9kAl9w8bo8eX24wumM:-NA8Ps5oCTdv-KJ_G0aw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1501c38826dac1a8dff28c10629f2bf46212b595/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/reconciliation/ResourceGroupAsyncReconciliationHandler.java#L42)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Variable names do not have impl in them.
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36498#-:-NA986_kANhkNPIJ2pyS:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36498)* status: 1. unresolved discussions.

**Pull request merged**
