### PR TITLE
fix: [CDS-34191]: correct canary rollback steps

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
Step group rollback isn't supported anymore, hence fixed canary deployment template.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31756)

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
trigger FunctionalTest1-Functional_tests

**Comment by abhinavsingh1196** [comment]
trigger FunctionalTest2-Functional_tests

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31756)* status: :shipit: complete! ✓

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31756)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger ti1

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
trigger messagecheck

**Comment by abhinavsingh1196** [comment]
trigger ti1

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31756)* status: :shipit: complete! ✓

**Comment by abhinavsingh1196** [comment]
trigger ti1

**Pull request closed without merging**
