### PR TITLE
[feat]: [PL-28047]: OpenAPI Implementation for Pipeline Resource through Server Stub

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Implemented Pipeline Resource APIs through server-stub generation.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37660)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 13 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 12 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37660)

**Review by senjucanon2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37660)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/ProjectPipelinesApiImpl.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/37660#-ND70SeD-ONBUv9RE3uN:-ND70SeD-ONBUv9RE3uO:b-oz6285) ([raw file](https://github.com/harness/harness-core/blob/311f02396973a4102a253774f3f923c7009a79c9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/ProjectPipelinesApiImpl.java#L70)):*
> ```Java
>   public Response createPipelineProject(PipelineRequestBody requestBody, String org, String project, String account,
>       String branch, String filePath, String commitMessage, Boolean isNewBranch, String baseBranch, String connectorRef,
>       String storeType, String repoName) {
> ```

Currently "PMSPipelineDtoMapper.toPipelineEntity()" reads Pipeline name and identifier from Yaml, upon Yaml Simplification these fields will be removed, from where we'll get this things from now onwards, beacause i don't see it in params,or am i missing something? Also, RequestBody will have tags and description alongwith yaml, right? CMIIW.

**Comment by mankrit-singh** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/ProjectPipelinesApiImpl.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/37660#-ND70SeD-ONBUv9RE3uN:-ND8htV52bzKmIPJXZc0:byhxajx) ([raw file](https://github.com/harness/harness-core/blob/311f02396973a4102a253774f3f923c7009a79c9/pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/ProjectPipelinesApiImpl.java#L70)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Currently "PMSPipelineDtoMapper.toPipelineEntity()" reads Pipeline name and identifier from Yaml, upon Yaml Simplification these fields will be removed, from where we'll get this things from now onwards, beacause i don't see it in params,or am i missing something? Also, RequestBody will have tags and description alongwith yaml, right? CMIIW.
</blockquote></details>

We will be doing these changes after YAML Simplification, won't take long here

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37660)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37660)* status: :shipit: complete! ✓

**Pull request merged**
