### PR TITLE
feat: [PL-39947]: delete notification related data on account deletion

### PR DESCRIPTION
**Pull request by sahibaCCM**
## Describe your changes

Adding a consumer to listen to account delete event and remove data related to notification on the NG side.
Tested for:
-> Triggering and removing notification data when account delete event is triggered. 

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51238)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51238)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapWC0ACeq1VMil3PBx:-NapWC0ACeq1VMil3PBy:bo6uh7c) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L55)):*
> ```Java
>         String action = metadataMap.get(ACTION);
> 
>         String entityType = metadataMap.get(ENTITY_TYPE);
> ```

what if this is null?

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapWXHm53iEPOgi8mqM:-NapWXHm53iEPOgi8mqN:b-o0nqe0) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L67)):*
> ```Java
> 
>   private boolean processAccountEntityChangeEvent(AccountEntityChangeDTO entityChangeDTO, String action) {
>     if (DELETE_ACTION.equals(action)) {
> ```

nit: better to use switch case here for condition check

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapWgmrCAny4BSkI51x:-NapWgmrCAny4BSkI51y:b-8e06r) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L66)):*
> ```Java
>   }
> 
>   private boolean processAccountEntityChangeEvent(AccountEntityChangeDTO entityChangeDTO, String action) {
> ```

I see it always return "true", shouldn't it be void in this case?

**Comment by mohitg0795** [comment]
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapYDoUAzVIhVumqtwy:-NapYDoUAzVIhVumqtwz:b-q6kou6) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L75)):*
> ```Java
> 
>   private void processDeleteEvent(AccountEntityChangeDTO entityChangeDTO) {
>     notificationSettingsService.deleteByAccount(entityChangeDTO.getAccountId());
> ```

we should put this into try catch and put a failure log for better tracking.

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger ut5

**Comment by sahibaCCM** [comment]
trigger ut5

**Review by sahibaCCM — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51238)* status: 18 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapWC0ACeq1VMil3PBx:-NbNvFzp6ZZUPP9cD_Fl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L55)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if this is null?
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapYDoUAzVIhVumqtwy:-NbNvGhwE44q5jOsAXtd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L75)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should put this into try catch and put a failure log for better tracking.
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/java/io/harness/platform/PlatformApplication.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapXnAUCt1r5E-lUNeZ:-NbNvIhD4SxT-fVxPBTp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/service/src/main/java/io/harness/platform/PlatformApplication.java#L209)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/java/io/harness/platform/notification/NotificationServiceModule.java` line 235 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapXrXu52HI6LNpfe2m:-NbNvJH16Jj5lRxT8LsU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/service/src/main/java/io/harness/platform/notification/NotificationServiceModule.java#L235)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.
___
*[`platform-service/service/src/main/java/io/harness/platform/notification/NotificationServiceModule.java` line 240 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapXuvg4z2zSpLilmlI:-NbNvJh694OX04oR4gkS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/service/src/main/java/io/harness/platform/notification/NotificationServiceModule.java#L240)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line missing
</blockquote></details>

Done.

**Review by sahibaCCM — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51238)* status: 18 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/51238#-NapWgmrCAny4BSkI51x:-NbNvLGJ519XPBO0UfMb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84705620132146b3c019199a86943ab7482a013d/platform-service/modules/notification-service/src/main/java/io/harness/notification/eventframework/NotificationEntityCrudStreamListener.java#L66)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see it always return "true", shouldn't it be void in this case?
</blockquote></details>

Done.

**Review by ashishsanodia-harness — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 13 files at r1, 6 of 10 files at r2, 1 of 1 files at r5, 7 of 8 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51238#-:-NbNwzTrCFTUX3FAEZk2:bnfp4nl)* status: 18 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51238)* status: 18 file(s) to review.

**Comment by sahibaCCM** [comment]
trigger uts

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51238#-:-NbPOf_30XTmuvb1lVgb:bnfp4nl)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
