### PR TITLE
feat: [PL-22226]: Move rest resources to contracts

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30985)

### CODE REVIEW

**Review by ankit-harness — APPROVED** [review]
> Reviewed 120 of 120 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30985)* status: 120 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30985#-:-Mwfhh6tBSiPGs3yJh6U:bnfp4nl)* status: 120 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — DISMISSED** [review]
> Reviewed 120 of 120 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30985)* status: :shipit: complete! ✓

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Review by reetika04 — APPROVED** [review]
> Reviewed 59 of 59 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30985)* status: 67 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 63 of 120 files at r1, 59 of 59 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30985)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 59 of 59 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30985#-:-MwzvLNL2rJR0kNmdSW9:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
