### PR TITLE
feat: [CDS-46488]: Define Yaml Beans for EnvironmentGroup Filtering in Pipeline

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Update EnvironmentGroup Yaml POJO to support filters as per https://harness.atlassian.net/wiki/spaces/CDNG/pages/21185986996/Mapping+Services+to+Environment+Environment+Groups+and+Clusters

Actual Pipeline Yaml with filters  ( ignore deployToAll field here )
https://github.com/harness/harness-core/blob/CDS-46488-be-implement-filtering-support-in-the-environment-section/125-cd-nextgen/src/test/resources/deployStageWithEnvironmentGroupAndFilters.yaml
Screenshot 2022-11-21 at 3 46 00 PM

**These yamls are hidden as of now from the environment group yaml**

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46284]: https://harness.atlassian.net/browse/CDS-46284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46488]: https://harness.atlassian.net/browse/CDS-46488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46488]: https://harness.atlassian.net/browse/CDS-46488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46488]: https://harness.atlassian.net/browse/CDS-46488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-46488]: https://harness.atlassian.net/browse/CDS-46488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40386)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/customdeployment/helper/CustomDeploymentEntitySetupHelper.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/40386#-NHAvT4xEeXH4clLT_5q:-NHAvT4xEeXH4clLT_5r:bv9p3dc) ([raw file](https://github.com/harness/harness-core/blob/04aa5cd9ec715ed8371a8ced2eff75c7ed1c9e34/127-cd-nextgen-entities/src/main/java/io/harness/cdng/customdeployment/helper/CustomDeploymentEntitySetupHelper.java#L44)):*
> ```Java
> import lombok.extern.slf4j.Slf4j;
> 
> @Slf4j
> ```

this is an unrelated change but this was a typo done by the author

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by rohitk-h — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40386)* status: :shipit: complete! ✓

**Review by rohitk-h — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40386)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
@yogesh-chauhan all the new files need open source license information.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40386)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
> @yogesh-chauhan all the new files need open source license information.

Done

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 3 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40386)* status: 7 file(s) to review. 0 of 1 approvals obtained.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 7 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40386)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
