### PR TITLE
techdebt: [PL-29724]: Move outer files in 980-commons to misc module

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

SystemWrapper.java and GodInjector.java files are present in the outer folder of 980-commons. Generating a Build file for the outer package results in Bazel dependency errors thus moving these 2 files to a misc module so that granular build files can be generated for them.

Tested the below scenarios in PR Env -
1. End to end K8s workflow
2. Secret Manager and secrets creation 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)

### CODE REVIEW

**Review by gn-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/misc/GodInjector.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/40897#-NI9oANy4i4gndzpKty8:-NI9oANy4i4gndzpKty9:brexm03) ([raw file](https://github.com/harness/harness-core/blob/c4ee3fa0d0e0c78942470853dd14b783c3ac3d53/980-commons/src/main/java/io/harness/misc/GodInjector.java#L8)):*
> ```Java
>  */
> 
> package io.harness.misc;
> ```

you can move this to the platform service itself. does not look like there are any other consumers.



_Code quote:_
```Java
package io.harness.misc;
```
___
*[`980-commons/src/main/java/io/harness/misc/SystemWrapper.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/40897#-NI9oOqs-MJh7ktLDM9j:-NI9oOqs-MJh7ktLDM9k:b-3o09ca) ([raw file](https://github.com/harness/harness-core/blob/c4ee3fa0d0e0c78942470853dd14b783c3ac3d53/980-commons/src/main/java/io/harness/misc/SystemWrapper.java#L8)):*
> ```Java
>  */
> 
> package io.harness.misc;
> ```

There is already a utils folder - you can creates utils/system and move it there



_Code quote:_
```Java
package io.harness.misc;
```

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/misc/GodInjector.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/40897#-NI9oANy4i4gndzpKty8:-NIEGctY3vW-S6ErQDb-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c4ee3fa0d0e0c78942470853dd14b783c3ac3d53/980-commons/src/main/java/io/harness/misc/GodInjector.java#L8)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

you can move this to the platform service itself. does not look like there are any other consumers.
</blockquote></details>

Done
___
*[`980-commons/src/main/java/io/harness/misc/SystemWrapper.java` line 8 at r1](https://reviewable.io/reviews/harness/harness-core/40897#-NI9oOqs-MJh7ktLDM9j:-NIEGbqx1Fgowx4tNqlf:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c4ee3fa0d0e0c78942470853dd14b783c3ac3d53/980-commons/src/main/java/io/harness/misc/SystemWrapper.java#L8)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

There is already a utils folder - you can creates utils/system and move it there
</blockquote></details>

Done

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by gn-harness — APPROVED** [review]

**Review by gn-harness — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: 8 file(s) to review. 2. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: 2. unresolved discussions.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: 2. unresolved discussions.

**Review by gn-harness — APPROVED** [review]

**Review by gn-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: Some of the checks are too old.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40897)* status: :shipit: complete! ✓

**Pull request merged**
