### PR TITLE
[fix]: [CDS-58930]: rerun migration PopulateYamlField in environment and service

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

Rerunning these migration, Because  after this migration some service/env yamls got set null from v1 type of pipeline, where we were still allowing save without yaml
This v1 pipeline flow got fixed in November last week 2022 (So from no sucn env/svc where modifiedAt > Dec 5, 2022)
Since then there is no such entities, These migrations rerun will populate yaml in those older entities.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46555)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/46555#-NTNNzMvBEiTpkWs5qFx:-NTNNzMvBEiTpkWs5qFy:bzcvb9y) ([raw file](https://github.com/harness/harness-core/blob/96971e9b6af1e0b9e1b81a9a9c66c81c03fb9429/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L70)):*
> ```Java
>                   mongoTemplate.findAndModify(
>                       query, update, new FindAndModifyOptions().returnNew(true), Environment.class);
>                 } catch (Exception e) {
> ```

we are not logging the exception here ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46555)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46555)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/46555#-NTNNzMvBEiTpkWs5qFx:-NTY5TNB1HgAVINdGCRb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/96971e9b6af1e0b9e1b81a9a9c66c81c03fb9429/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L70)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we are not logging the exception here ?
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
Can we update the PR description ?

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46555)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46555)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
trigger review

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Pull request merged**
