### PR TITLE
feat: [CDS-38469]: hard delete for services entity

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
1. Added hard delete for services behind FF
2. Provide methods for hard delete single entity and batch delete (can be used for outbox services)
3. Cascading delete when project/org is deleted. 

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [X] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34184)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34184)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 199 at r1](https://reviewable.io/reviews/harness/harness-core/34184#-N4B6qXY59QetVbnfs-V:-N4B6qXZ7taWH3pDxwuj:b-ckoswd) ([raw file](https://github.com/harness/harness-core/blob/1440eb2dfff6b03f7a2f1d5da43f31cefc6ff11a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L199)):*
> ```Java
> 
>   @Override
>   @DefaultOrganization
> ```

what. is the purpose of this annotation ?  



_Code quote:_
```Java
 @DefaultOrganization
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 214 at r1](https://reviewable.io/reviews/harness/harness-core/34184#-N4B7a9_ElB4i0wTEWKQ:-N4B7a9aAGvq8l04_ZM0:b-l173jt) ([raw file](https://github.com/harness/harness-core/blob/1440eb2dfff6b03f7a2f1d5da43f31cefc6ff11a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L214)):*
> ```Java
>         get(accountId, orgIdentifier, projectIdentifier, serviceIdentifier, false);
> 
>     if (serviceEntityOptional.isPresent()) {
> ```

We should get rid of the Get and delete paradigm. Mongo can do both with one command, find and delete. 
https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndDelete/
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 352 at r1](https://reviewable.io/reviews/harness/harness-core/34184#-N4B8Q3b8AxX22hTBLQg:-N4B8Q3b8AxX22hTBLQh:b2nhswy) ([raw file](https://github.com/harness/harness-core/blob/1440eb2dfff6b03f7a2f1d5da43f31cefc6ff11a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L352)):*
> ```Java
>   @Override
>   public boolean forceDeleteAllInProject(String accountId, String orgIdentifier, String projectIdentifier) {
>     // delete both soft deleted services and existing?
> ```

Yes



_Code quote:_
```Java
// delete both soft deleted services and existing?
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustom.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/34184#-N4B7u0r6xk7nEEoAtb5:-N4B7u0r6xk7nEEoAtb6:b3ja32n) ([raw file](https://github.com/harness/harness-core/blob/1440eb2dfff6b03f7a2f1d5da43f31cefc6ff11a/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustom.java#L27)):*
> ```Java
>   ServiceEntity update(Criteria criteria, ServiceEntity serviceEntity);
>   UpdateResult delete(Criteria criteria);
>   DeleteResult hardDelete(Criteria criteria);
> ```

since hardDelete is going to be the default behaviour, better to call it Delete and rename the existing method to soft delete
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/34184#-N4B89Va8KEkABcIZ7nj:-N4B89Va8KEkABcIZ7nk:b9pjxq5) ([raw file](https://github.com/harness/harness-core/blob/1440eb2dfff6b03f7a2f1d5da43f31cefc6ff11a/127-cd-nextgen-entities/src/main/java/io/harness/repositories/service/custom/ServiceRepositoryCustomImpl.java#L98)):*
> ```Java
>   @Override
>   public List<ServiceEntity> hardDeleteMany(Criteria criteria) {
>     // to implement outbox service event in case of batch delete
> ```

We should write // ToDo or // Todo so that Intellij can also recognize these if someone wishes to see all todos. Lets create a ticket for the todo

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34184)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/34184#-N4DD96gC_6U9mymvETZ:-N4DD96gC_6U9mymvET_:b-ph62br) ([raw file](https://github.com/harness/harness-core/blob/c9c446c3b45dd48b3822152166763c434d172573/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L198)):*
> ```Java
> 
>   @Override
>   public boolean delete(String accountId, @OrgIdentifier String orgIdentifier,
> ```

lets remove these annotations also

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r2, 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34184)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34184)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]

**Pull request merged**
