### PR TITLE
feat: [CDS-39662]: Unit tests for processInstanceSyncForNewDeployment

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Describe your changes
Added unit tests to cover processInstanceSyncForNewDeployment and processInstanceSyncByPerpetualTask

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35154)

### CODE REVIEW

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Comment by vikyathharekal** [comment]
trigger codebasehash

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35154)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/35154#-N7KSx-J1MtTMFcIoqfF:-N7KSx-J1MtTMFcIoqfG:b-7qxol5) ([raw file](https://github.com/harness/harness-core/blob/78ae7dd0d178c36eeee97670939902123ef0cb88/126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java#L79)):*
> ```Java
>   AutoCloseable openMocks;
>   private static final String TEST_INFRA_MAPPING_ID = "62b9a965c202de6a4a1a7728";
>   private static final String TEST_ACCOUNT_ID = "BgiA4-xETamKNVAz-wQRjw";
> ```

let's use a dummy accountId, and also the org_id
___
*[`126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java` line 421 at r1](https://reviewable.io/reviews/harness/harness-core/35154#-N7KU-i9BVAF4jCs6hMc:-N7KU-i9BVAF4jCs6hMd:b-60uy5y) ([raw file](https://github.com/harness/harness-core/blob/78ae7dd0d178c36eeee97670939902123ef0cb88/126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java#L421)):*
> ```Java
>     assertEquals(0, instancesToBeModified.get(OperationsOnInstances.UPDATE).size());
>     assertEquals(1, instancesToBeModified.get(OperationsOnInstances.ADD).size());
>     InstanceDTO instanceToBeAdded = instancesToBeModified.get(OperationsOnInstances.ADD).get(0);
> ```

let's add validations on the details of the Instance (to be added to DB) as well.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35154)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/35154#-N7KSx-J1MtTMFcIoqfF:-N7L5tS1DBCpwzAns7zw:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/78ae7dd0d178c36eeee97670939902123ef0cb88/126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java#L79)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's use a dummy accountId, and also the org_id
</blockquote></details>

Done



_Code quote:_
```Java
InstanceSyncServiceTest
```
___
*[`126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java` line 421 at r1](https://reviewable.io/reviews/harness/harness-core/35154#-N7KU-i9BVAF4jCs6hMc:-N7Kyjg843h9NB83pYi-:b-xz55v0) ([raw file](https://github.com/harness/harness-core/blob/78ae7dd0d178c36eeee97670939902123ef0cb88/126-instance/src/test/java/io/harness/service/instancesync/InstanceSyncServiceTest.java#L421)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's add validations on the details of the Instance (to be added to DB) as well.
</blockquote></details>

I am validating the instance sync key and infra mapping id for the instance using the argument captor already.
Are you looking for any more validations?

**Review by shubham-in10se — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35154)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35154)* status: :shipit: complete! ✓

**Pull request merged**
