### PR TITLE
fix: [CDS-42269]: Use GitClientV2 downloadfiles for copying repo files to WorkingDir in NG

### PR DESCRIPTION
**Pull request by namantalaycha10**
…WorkingDir in NG

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37842)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37842)

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37842)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/37842#-NCdFZp6DDG_s8Ie65uX:-NCdFZp6DDG_s8Ie65uY:b6duhme) ([raw file](https://github.com/harness/harness-core/blob/b46eb706fa215c97a00bd44c0d0a6559b5dc2396/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L649)):*
> ```Java
>   }
> 
>   public String fetchConfigFileAndPrepareScriptDir(GitBaseRequest gitBaseRequestForConfigFile, String accountId,
> ```

lets add a test for this method to cover new changes

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37842)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/37842#-NCdFZp6DDG_s8Ie65uX:-NCdxp0S5zrrnVSOA9KA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b46eb706fa215c97a00bd44c0d0a6559b5dc2396/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L649)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

lets add a test for this method to cover new changes
</blockquote></details>

Done.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37842)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 655 at r2](https://reviewable.io/reviews/harness/harness-core/37842#-NCe-FVKAsJwNZgvD2zu:-NCe-FVL4ZGpb_axN0mi:b-kuy77g) ([raw file](https://github.com/harness/harness-core/blob/20c7b5f8bd94617a00f63abb8be9425c1b8fa36f/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L655)):*
> ```Java
>                                 .branch(gitStoreDelegateConfig.getBranch())
>                                 .commitId(gitStoreDelegateConfig.getCommitId())
>                                 .filePaths(Collections.singletonList(""))
> ```

Why a list of empty path?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37842)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 655 at r2](https://reviewable.io/reviews/harness/harness-core/37842#-NCe-FVKAsJwNZgvD2zu:-NCe0tfJ9DPxPqRA4UXK:bipgv2a) ([raw file](https://github.com/harness/harness-core/blob/20c7b5f8bd94617a00f63abb8be9425c1b8fa36f/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L655)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Why a list of empty path?
</blockquote></details>

By making this file path empty we will download everything present in the root of the repo, which is helpful in case when config files have reference outside the config folder 
Same is also we are doing in CG

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37842)* status: :shipit: complete! ✓

**Pull request merged**
