### PR TITLE
fix: [BT-1733]: Support updating existing BUILD.bazel files

### PR DESCRIPTION
**Pull request by hemanthmantri**
This change adds support for editing existing BUILD.bazel files with newly determined dependencies by build-cleaner tool.
The tool by default doesn't override existing BUILD files unless `--updateExistingBuildFiles` is specified. When the flag is specified, the corresponding BUILD.bazel file is overwritten with new values for `deps` and `runtime_deps` fields of `java_library` and `java_binary` rules. The flag assumes the BUILD file only has at most of `java_library` and `java_binary` rules in the build file and also have empty deps explicitly populated as `deps = []` or `runtime_deps = []`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36713)

**Comment by hemanthmantri** [comment]
> 

Done

**Review by hemanthmantri — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713#-:-NANs8m-4KW9icVXDVv0:b-896fix)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/36713#-NAEf2tpB4jazjhpEW3n:-NANsDVfAX11xY-yqczd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abcb2e9892cafbcbe04b3b0d3920082d78f4d7bc/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L89)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You shouldn't pass the logger around, create a new one for this class. This one will have wrong context (e.g. class name). Also, you would probably want to turn some of those logs into debug level. 
</blockquote></details>

Done.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/36713#-NAEzvwK8LvAnOOX7F3R:-NANsEwb78Soxmcgyblv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/abcb2e9892cafbcbe04b3b0d3920082d78f4d7bc/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L98)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This method is way too complex. You should break it down into at least 3-4 different methods. E.g. getNewDeps, replaceDeps etc...
</blockquote></details>

Done.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/36713#-NAF-TUb3rRkR01hsaUc:-NANsLRU7pjVh5Uh6d_2:b-3xiy93) ([raw file](https://github.com/harness/harness-core/blob/abcb2e9892cafbcbe04b3b0d3920082d78f4d7bc/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java#L23)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I'm guessing that deps section is printed out the same regardles if it's runtime_deps/deps and library/binary. You should extract it into an abstract class or a default interface, or just a separate class that does that. 
</blockquote></details>

Keeping it for now as is unless you think this is a must-do.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NAR_FZwEdiYYY91eHOs:-NAR_FZwEdiYYY91eHOt:b7b0ueg) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L102)):*
> ```Java
>               // - The BUILD file has at most one java_binary rule.
>               // - Empty dependencies are explicitly mentioned in the rules: Eg: deps = [] and runtime_deps = []
>               if (options.hasOption("updateExistingBuildFiles")) {
> ```

update existing build files should be default.

By default, if the build file exists, we would update dependencies, else we would create one. Only if someone explicitly requests overwrite the entire file, then we would need a flag, something like "overwriteExistingBuildFiles"



_Code quote:_
```Java
updateExistingBuildFiles
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARdiqzEcKyBdjgbDC_:-NARdiqzEcKyBdjgbDCa:b-hfpv1m) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L136)):*
> ```Java
>   // updateField: Accepted values are "deps" and "runtime_deps"
>   private void updateDepsHelper(Path buildFilePath,  String buildRule, String updateField) throws IOException {
>     //List<JavaLibrary> javaLibraryList = getJavaLibraryList();
> ```

remove?



_Code quote:_
```Java
    //List<JavaLibrary> javaLibraryList = getJavaLibraryList();
    //List<JavaBinary> javaBinaryList = getJavaBinaryList();
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 157 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARdyjE-bPWaUTQYq96:-NARdyjE-bPWaUTQYq97:b-wxgq6m) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L157)):*
> ```Java
>     }
> 
>     Pattern pattern = Pattern.compile(regexPattern.toString(), Pattern.MULTILINE);
> ```

nit: Not even required to do here, but just FYI these can be statically compiled variables, which can be used across calls.



_Code quote:_
```Java
 Pattern pattern = Pattern.compile(regexPattern.toString(), Pattern.MULTILINE);
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/36713#-NAF-TUb3rRkR01hsaUc:-NARdDR36cI_tXOrBu3I:b-hz9wm9) ([raw file](https://github.com/harness/harness-core/blob/abcb2e9892cafbcbe04b3b0d3920082d78f4d7bc/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java#L23)):*
<details><summary><i>Previously, hemanthmantri (Hemanth Mantri) wrote…</i></summary><blockquote>

Keeping it for now as is unless you think this is a must-do.
</blockquote></details>

I can take this one separately
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARcyUw8Kesqu82xNiC:-NARcyUw8Kesqu82xNiD:bdixi5f) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java#L41)):*
> ```Java
>   public String getRunTimeDepsSection() {
>     StringBuilder response = new StringBuilder();
>     WriteUtil.updateResponseWithSet(this.runTimeDeps, "runtime_deps", response, false);
> ```

nit:  WriteUtil.updateResponseWithSet(this.runTimeDeps, "runtime_deps", response, /*leadingIndent=*/false);



_Code quote:_
```Java
WriteUtil.updateResponseWithSet(this.runTimeDeps, "runtime_deps", response, false);
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARcuANBFUOxEM2Qtbf:-NARcuANBFUOxEM2Qtbg:bvduk4h) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java#L63)):*
> ```Java
> 
>     // Add deps.
>     WriteUtil.updateResponseWithSet(deps, "deps", response, true);
> ```

nit:  WriteUtil.updateResponseWithSet(deps, "deps", response, /*leadingIntent=*/true);



_Code quote:_
```Java
WriteUtil.updateResponseWithSet(deps, "deps", response, true);
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/WriteUtil.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARcfs0AsC3R784F_Rn:-NARcfs0AsC3R784F_Ro:byukuv7) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/WriteUtil.java#L43)):*
> ```Java
>   public static void writeUpdatedFile(Path filePath, String update) throws IOException {
>     Files.writeString(filePath, update, TRUNCATE_EXISTING);
>   }
> ```

nit: just inline Files.writeString -- function not adding much



_Code quote:_
```Java
  public static void writeUpdatedFile(Path filePath, String update) throws IOException {
    Files.writeString(filePath, update, TRUNCATE_EXISTING);
  }
```

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARePtW1h6n8Kl8UqtL:-NARePtW1h6n8Kl8UqtM:b47kapf) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L92)):*
> ```Java
> 
>   // Update deps and runtime_deps in a BUILD.bazel file.
>   public void updateDependencies(Path buildFilePath) throws IOException {
> ```

Please unit test this. 



_Code quote:_
```Java
public void updateDependencies(Path buildFilePath) throws IOException {
```

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: Some of the checks are too old. 1 change requests. 3. unresolved discussions. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NAdXaMtBUakxagU-MFk:-NAdXaMtBUakxagU-MFl:bcj71f) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L94)):*
> ```Java
>             Path packagePath = workspace().resolve(path);
>             Path buildFilePath = Paths.get(packagePath.toString(), "/BUILD.bazel");
>             logger.info(String.format("ModulePath: %s ; PackagePath: %s ; BuildFilePath: %s", modulePath, packagePath, buildFilePath.toString()));
> ```

Sorry for not being clear enough. SLF4J (the logging API library we use, and logback logging implementation library), support logging variable placeholders. So you should have something like below instead.
You would use `{}` as a placeholder for any variable that you need to print out, and just use String message, avoiding String format. You should do this on all logs. 



_Code snippet:_
```Java
logger.info("Module {}; PackagePath {}; BuildFilePath {};", modulePath, packagePath, buildFilePath);
```
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NAdZVsPBGgQi5d0BoPt:-NAdZVsPBGgQi5d0BoPu:b-jhcdqw) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L146)):*
> ```Java
>         break;
>       case "java_binary":
>         newDeps = getNewBinaryDeps(updateField);
> ```

Even though not really needed here, it's good to always have break in each case clause. Otherwise your future self will have tough time figuring out the issue when you add a new case or default value. 
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 157 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARdyjE-bPWaUTQYq96:-NAdZrVB54rzWyooN0hp:bl602yh) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L157)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: Not even required to do here, but just FYI these can be statically compiled variables, which can be used across calls.
</blockquote></details>

Agree, compiling regex pattern is actually the most time intensive part of the regex operations. You could potentially feel the performance impact if you run the tool on all packages. Definitely turn it into static variable. 
Just FYI same goes for various JSON mappers if we ever have them. Always create them statically.

**Review by hemanthmantri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NAdXaMtBUakxagU-MFk:-NAmKri78y4Wh4MZtIyB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L94)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Sorry for not being clear enough. SLF4J (the logging API library we use, and logback logging implementation library), support logging variable placeholders. So you should have something like below instead.
You would use `{}` as a placeholder for any variable that you need to print out, and just use String message, avoiding String format. You should do this on all logs. 
</blockquote></details>

Done.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NAR_FZwEdiYYY91eHOs:-NAmKuJt7gvbmT6in8Ii:b-1rbj6r) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/BuildCleaner.java#L102)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

update existing build files should be default.

By default, if the build file exists, we would update dependencies, else we would create one. Only if someone explicitly requests overwrite the entire file, then we would need a flag, something like "overwriteExistingBuildFiles"
</blockquote></details>

Keeping this now and will remove it later. I tried making default to true but seems there's no direct way.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARePtW1h6n8Kl8UqtL:-NAmL43P3Ocrng23UKF1:b-62vc3y) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L92)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

Please unit test this. 
</blockquote></details>

Will do in a follow up.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARdiqzEcKyBdjgbDC_:-NAmL85w5tVGCNa-qM-g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L136)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 157 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARdyjE-bPWaUTQYq96:-NAmLCGh1eO-oaIfMDFb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L157)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Agree, compiling regex pattern is actually the most time intensive part of the regex operations. You could potentially feel the performance impact if you run the tool on all packages. Definitely turn it into static variable. 
Just FYI same goes for various JSON mappers if we ever have them. Always create them statically. 
</blockquote></details>

Done
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARcyUw8Kesqu82xNiC:-NAmLG0E8yA-zA_qbojM:b-g394az) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java#L41)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit:  WriteUtil.updateResponseWithSet(this.runTimeDeps, "runtime_deps", response, /*leadingIndent=*/false);
</blockquote></details>

This wasn't working for me. IDE is showing the named arguments but adding this caused some issues. Didn't debug more. Can take up in the followup patch.
___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARcuANBFUOxEM2Qtbf:-NAmLTqb8inSi6_i15qB:b-89a4l7) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/JavaLibrary.java#L63)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit:  WriteUtil.updateResponseWithSet(deps, "deps", response, /*leadingIntent=*/true);
</blockquote></details>

Ditto

**Review by hemanthmantri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 3 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/36713#-NARePtW1h6n8Kl8UqtL:-NAmLaP71ElAzr2v6rtY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1af7761606cb4487b573414a65bef3015f86951e/tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/BuildFile.java#L92)):*
<details><summary><i>Previously, hemanthmantri (Hemanth Mantri) wrote…</i></summary><blockquote>

Will do in a follow up.
</blockquote></details>

Done.

**Comment by hemanthmantri** [comment]
trigger codeformat

**Review by gn-harness — COMMENTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 1 change requests. 6. unresolved discussions. 0 of 1 approvals obtained.

**Review by mdmilic — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 5. unresolved discussions.

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 5. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713#-:-NAtwxRH-FOfXOy0XTvL:bnfp4nl)* status: 5. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: 2. unresolved discussions.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36713)* status: :shipit: complete! ✓

**Pull request merged**
