### PR TITLE
fix: [DEL-4246]: Always scan for client tools regardles of install flags

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
We want delegate to scan for existing client tools regardless of the download or background flags. The download flag will take effect during installation procedure and if set to false, delegate will only skip download if the tool is not present (but still find it if present). 
If customer only has some tools on the delegate, we don't have a good way to detect that. This means that delegate will continue scanning in the background hoping more tools will be discovered and only give up after 5 tries. Though unnecessary, this should have a major downside.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35488)

### CODE REVIEW

**Comment by mdmilic** [comment]
trigger codebasehash

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35488)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 671 at r2](https://reviewable.io/reviews/harness/harness-core/35488#-N7QAP566P0e47EPBaRS:-N7QQ0Ds9WJNE3n98jJX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/274a12165f351cfdc4fd4695d8ce6633b93adb8b/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L671)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Now this will run irrespective of isInstallClientToolsInBackground true or false, may be you can move  above if condition here
      if (!delegateConfiguration.isInstallClientToolsInBackground()) {
        log.info("Client tools will be setup synchronously, before delegate registers");
        setupClientTools(delegateConfiguration);
      } else {
        log.info("Client tools will be setup in the background, while delegate registers");
        // perform submit on  backgroundexecutor
      }

</blockquote></details>

Done.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35488)* status: :shipit: complete! ✓

**Pull request merged**
