### PR TITLE
feat: [IDP-1667]: Total Components mismatch in Scorecard stats API

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55479)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55479)* status: 1 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/55479#-NjMEApb8thPojCkkZZn:-NjMEApb8thPojCkkZZo:b-57ys3) ([raw file](https://github.com/harness/harness-core/blob/285d342995f53e7f8f54c665bdc625079d714d41/idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java#L78)):*
> ```Java
>                             .in(scorecardIdentifiers)
>                             .and(ScoreEntity.ScoreKeys.lastComputedTimestamp)
>                             .gt(yesterdayInMilliseconds());
> ```

This might still return more than one score. How about having a limit query instead?



_Code quote:_
```Java
esterdayInMilliseconds());
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55479)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/55479#-NjMEApb8thPojCkkZZn:-NjMFPfIEtY_fIjJfyq_:b-uceivk) ([raw file](https://github.com/harness/harness-core/blob/285d342995f53e7f8f54c665bdc625079d714d41/idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java#L78)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

This might still return more than one score. How about having a limit query instead?
</blockquote></details>

We are already selecting only one score in group stage after sorting lastComputedTimestamp in desc order



_Code snippet:_
```Java
    Aggregation aggregation = Aggregation.newAggregation(Aggregation.match(criteria),
        Aggregation.sort(Sort.Direction.DESC, ScoreEntity.ScoreKeys.lastComputedTimestamp),
        Aggregation.group(ScoreEntity.ScoreKeys.scorecardIdentifier, ScoreEntity.ScoreKeys.entityIdentifier)
            .first(Constants.SCORE_KEY)
            .as(Constants.SCORE_KEY),
        Aggregation.group(Constants.ID_KEY + DOT_SEPARATOR + Constants.SCORECARD_IDENTIFIER_KEY)
            .count()
            .as(Constants.COUNT_KEY)
            .sum(ConditionalOperators.when(Criteria.where(Constants.SCORE_KEY).gt(75)).then(1).otherwise(0))
            .as(Constants.SCORES_GREATER_THAN_75_KEY),
        projectionOperation);
```

**Review by sandeepa-kv-jois — APPROVED** [review]

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55479)* status: 1 file(s) to review.

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
