### PR TITLE
feat: [PIE-9288]: Adding expression support for selected stages

### PR DESCRIPTION
**Pull request by ankittiwari-harness**
## Describe your changes
Added changes to access input Set and Selected stages via expressions

<+pipeline.selectedStages> -> returns list of stages up for execution. Returns for parallel, and matrix and repeat strategy too.

<+inputSet> returns inputSetYaml as map, can be used accordingly.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)

### CODE REVIEW

**Comment by ankittiwari-harness** [comment]
trigger ut5, ut6, ut7, messagecheck

**Comment by ankittiwari-harness** [comment]
trigger ut0, ut1, ut2, ut3, ut4, ut8, ut9

**Comment by ankittiwari-harness** [comment]
trigger ut2, messagecheck

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/46661#-NTV0iPS15e4aYsrGK1c:-NTV0iPS15e4aYsrGK1d:bn5ztt9) ([raw file](https://github.com/harness/harness-core/blob/900bb153552eeed92f5d893aa219b68708c5cfd5/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java#L72)):*
> ```Java
>     try {
>       if (planExecutionMetadata.isPresent()) {
>         List<YamlNode> stages = YamlUtils.extractPipelineField(planExecutionMetadata.get().getYaml())
> ```

We should check `planExecutionMetadata.stagesExecutionMetadata` first. If stagesExecutionMetadata is not null then selective stage execution is triggered. And we can get stageIdentifiers from stagesExecutionMetadata.getStageIdentifiers.
if stagesExecutionMetadatais null then we can return all stages.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java` line 70 at r5](https://reviewable.io/reviews/harness/harness-core/46661#-NTXg-YxA5RCuQ6lSCky:-NTXg-YxA5RCuQ6lSCkz:bx9ilok) ([raw file](https://github.com/harness/harness-core/blob/4af7cd6baab465e7a7462c556f90c3e2865426fa/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java#L70)):*
> ```Java
>     try {
>       // If Selective stage execution is allowed, add from StagesExecutionMetadata
>       if (pipelineExecutionSummaryEntity.getAllowStagesExecution()) {
> ```

I think even if this condition is true, stageIdentifiers might come as empty when users executed the complete pipeline and not selective stages. We should check `pipelineExecutionSummaryEntity.getStagesExecutionMetadata()!=null` as well.



_Code quote:_
```Java
pipelineExecutionSummaryEntity.getAllowStagesExecution()
```

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/46661#-NTXj2BbC2NnpNRw9OMF:-NTXj2BbC2NnpNRw9OMG:b-rhuq1w) ([raw file](https://github.com/harness/harness-core/blob/ad729b78d02b93e6b015972ea3db55849e5d667c/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java#L25)):*
> ```Java
> 
> @OwnedBy(PIPELINE)
> ```

nit: extra space
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java` line 45 at r6](https://reviewable.io/reviews/harness/harness-core/46661#-NTXj5226Z_pnmCZUnMI:-NTXj5226Z_pnmCZUnMJ:bz5xd0q) ([raw file](https://github.com/harness/harness-core/blob/ad729b78d02b93e6b015972ea3db55849e5d667c/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java#L45)):*
> ```Java
>       return YamlUtils.read(pipelineExecutionSummaryEntity.getInputSetYaml(), HashMap.class);
>     } catch (IOException e) {
>       throw new InvalidRequestException("Input Set Yaml could not be converted to a hashmap");
> ```

internalServerException
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java` line 98 at r6](https://reviewable.io/reviews/harness/harness-core/46661#-NTXjFwV5gJ3vjfaCWyp:-NTXjFwV5gJ3vjfaCWyq:b-dqp984) ([raw file](https://github.com/harness/harness-core/blob/ad729b78d02b93e6b015972ea3db55849e5d667c/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java#L98)):*
> ```Java
>           List<String> stageIdentifiers =
>               stageFields.stream()
>                   .map(stageField -> stageField.getNode().getField("identifier").getNode().asText())
> ```

can we extract this into another method? and put into util to get stageIdentifier from a yaml, or something should exist already



_Code quote:_
```Java
        Optional<PlanExecutionMetadata> planExecutionMetadata =
            planExecutionMetadataService.findByPlanExecutionId(ambiance.getPlanExecutionId());

        if (planExecutionMetadata.isPresent()) {
          List<YamlNode> stages = YamlUtils.extractPipelineField(planExecutionMetadata.get().getYaml())
                                      .fromYamlPath("stages")
                                      .getNode()
                                      .asArray();
          List<YamlField> stageFields = new LinkedList<>();

          stages.forEach(yamlNode -> {
            YamlField stageField = yamlNode.getField("stage");
            YamlField parallelStageField = yamlNode.getField("parallel");
            if (stageField != null) {
              stageFields.add(stageField);
            } else if (parallelStageField != null) {
              // in case of parallel, we fetch the stage node array again
              List<YamlNode> parallelStages = parallelStageField.getNode().asArray();
              parallelStages.forEach(parallelStage -> { stageFields.add(parallelStage.getField("stage")); });
            }
          });
          List<String> stageIdentifiers =
              stageFields.stream()
                  .map(stageField -> stageField.getNode().getField("identifier").getNode().asText())
                  .collect(Collectors.toList());
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java` line 25 at r6](https://reviewable.io/reviews/harness/harness-core/46661#-NTXj2BbC2NnpNRw9OMF:-NTmPlxp8Hutxdg83acL:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ad729b78d02b93e6b015972ea3db55849e5d667c/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: extra space
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java` line 45 at r6](https://reviewable.io/reviews/harness/harness-core/46661#-NTXj5226Z_pnmCZUnMI:-NTmQT275ZIkL6fASx9Y:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ad729b78d02b93e6b015972ea3db55849e5d667c/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

internalServerException
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java` line 98 at r6](https://reviewable.io/reviews/harness/harness-core/46661#-NTXjFwV5gJ3vjfaCWyp:-NTmQihJ1pFxfV-qCfXQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ad729b78d02b93e6b015972ea3db55849e5d667c/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we extract this into another method? and put into util to get stageIdentifier from a yaml, or something should exist already
</blockquote></details>

done

**Comment by ankittiwari-harness** [comment]
trigger ut3, ut4, ut5, ut7, ut8

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java` line 38 at r8](https://reviewable.io/reviews/harness/harness-core/46661#-NTmdr6-C8P0lODfXGFw:-NTmdr6-C8P0lODfXGFx:b-61ri6m) ([raw file](https://github.com/harness/harness-core/blob/703e82230232a1fde3b08c898df0ba3e9d28f38b/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputSetFunctor.java#L38)):*
> ```Java
>     try {
>       PipelineExecutionSummaryEntity pipelineExecutionSummaryEntity =
>           pmsExecutionService.getPipelineExecutionSummaryEntity(AmbianceUtils.getAccountId(ambiance),
> ```

nit, can we use projections over here?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java` line 74 at r8](https://reviewable.io/reviews/harness/harness-core/46661#-NTmdxYICjD1kaSjMs5q:-NTmdxYICjD1kaSjMs5r:bzhskjh) ([raw file](https://github.com/harness/harness-core/blob/703e82230232a1fde3b08c898df0ba3e9d28f38b/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/PipelineExecutionFunctor.java#L74)):*
> ```Java
>       } else {
>         Optional<PlanExecutionMetadata> planExecutionMetadata =
>             planExecutionMetadataService.findByPlanExecutionId(ambiance.getPlanExecutionId());
> ```

nit: get only yaml from db.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46661)* status: :shipit: complete! ✓

**Comment by ankittiwari-harness** [comment]
trigger review

**Pull request merged**
