### PR TITLE
feat: [CDS-40996]: Create new custom webhook trigger URL for returning data similar to CG's trigger response 

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes

This PR creates a new URL for triggering custom webhooks (`/webhook/custom/v2` ), and sets it as default for all new created webhooks.

When webhooks are triggered via this new URL, the `data` field in the response contains the following 4 fields:
- `eventCorrelationId`: This is the ID of the trigger event.
- `apiUrl`: This is the API URL to be used for fetching trigger execution details.
- `uiUrl`: This points to the UI where the user can see the pipeline's execution details.
- `uiSetupUrl`: This points to the UI where the user can configure the executed pipeline.

The previous trigger URL returned only a string containing the `eventCorrelationId` of the trigger.

This PR makes custom webhook trigger responses similar to CG's.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger ti3

**Review by Fernando-Dourado — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/webhook/WebhookHelper.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/36173#-N9H9pUw3bnMq4LG9wVx:-N9H9pUw3bnMq4LG9wVy:bt76l1b) ([raw file](https://github.com/harness/harness-core/blob/71cb7a4c7623a7993a60f7472e4745c67ebfe33b/970-ng-commons/src/main/java/io/harness/webhook/WebhookHelper.java#L69)):*
> ```Java
> 
>     // This will change to common endpoint that will be used by all
>     urlBuilder.append("webhook/custom/v2?accountIdentifier=")
> ```

The v1 endpoint is disabled at all or do we keep both active?
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/36173#-N9H8hAr7iJW3ohZkOv7:-N9H8hAr7iJW3ohZkOv8:bbobpdl) ([raw file](https://github.com/harness/harness-core/blob/71cb7a4c7623a7993a60f7472e4745c67ebfe33b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L24)):*
> ```Java
> @Singleton
> @Slf4j
> @OwnedBy(HarnessTeam.CI)
> ```

Minor. Not sure if CI is the right value here.
___
*[`pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/mapper/NGTriggerElementMapperV2Test.java` line 1075 at r4](https://reviewable.io/reviews/harness/harness-core/36173#-N9H8CZD5ydt8fjKOyYl:-N9H8CZD5ydt8fjKOyYm:b34ceej) ([raw file](https://github.com/harness/harness-core/blob/71cb7a4c7623a7993a60f7472e4745c67ebfe33b/pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/mapper/NGTriggerElementMapperV2Test.java#L1075)):*
> ```Java
>     assertThat(ngTriggerDetailsResponseDTO.getWebhookUrl())
>         .isEqualTo(
>             "https://app.harness.io/pipeline/api/webhook/custom/v2?accountIdentifier=accId&orgIdentifier=org&projectIdentifier=proj&pipelineIdentifier=pipeline&triggerIdentifier=first_trigger");
> ```

The original endpoint is disabled at all or do we keep both active? I mean, instead of changing the unit test, should be good to add a new one to cover the v2 scenario and keep v1 working.

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: 6 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/webhook/WebhookHelper.java` line 69 at r4](https://reviewable.io/reviews/harness/harness-core/36173#-N9H9pUw3bnMq4LG9wVx:-N9HTWMg7xZ8_8m8aVYz:b-d28elb) ([raw file](https://github.com/harness/harness-core/blob/71cb7a4c7623a7993a60f7472e4745c67ebfe33b/970-ng-commons/src/main/java/io/harness/webhook/WebhookHelper.java#L69)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

The v1 endpoint is disabled at all or do we keep both active?
</blockquote></details>

The original endpoint is still active, but all new generated webhooks will point to the v2 endpoint. The user can trigger any custom webhooks (old or new) with either the original or v2 endpoints, the only difference is the "v2/" in the URL and the format of the `data` field that comes in the response.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/36173#-N9H8hAr7iJW3ohZkOv7:-N9HTU6vAcXw4RV66RGT:bw8ysvv) ([raw file](https://github.com/harness/harness-core/blob/71cb7a4c7623a7993a60f7472e4745c67ebfe33b/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/UrlHelper.java#L24)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

Minor. Not sure if CI is the right value here.
</blockquote></details>

Fixed, thank you!
___
*[`pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/mapper/NGTriggerElementMapperV2Test.java` line 1075 at r4](https://reviewable.io/reviews/harness/harness-core/36173#-N9H8CZD5ydt8fjKOyYl:-N9HRrN12E2xG3XXYcCV:b-wa9jfg) ([raw file](https://github.com/harness/harness-core/blob/71cb7a4c7623a7993a60f7472e4745c67ebfe33b/pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/mapper/NGTriggerElementMapperV2Test.java#L1075)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

The original endpoint is disabled at all or do we keep both active? I mean, instead of changing the unit test, should be good to add a new one to cover the v2 scenario and keep v1 working.
</blockquote></details>

The plan is to keep the original endpoint (`/webhook/custom/`) still active, because we don't want to break users who already built automation that depends on the original response format.

When a user creates a new custom webhook, the trigger URL that will be generated will point to the new `/webhook/custom/v2` API, and this unit test is just for checking this URL. If the user wants he can stil trigger with the old API too by just deleting the "/v2" in the generated URL.

I added a new unit test in NGTriggerWebhookResourceImplTest to check if the original endpoint is working as expected. Thank you for the suggestion!

**Comment by vcalasansh** [comment]
trigger ti0

**Review by Fernando-Dourado — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 2 of 4 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: :shipit: complete! ✓

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: Some of the checks are too old. 1 change requests. 

___
*[`pipeline-service/modules/ng-triggers/BUILD.bazel` line 15 at r5](https://reviewable.io/reviews/harness/harness-core/36173#-N9aDj_GDfYYn5gMWW3j:-N9aDj_GDfYYn5gMWW3k:bivxn42) ([raw file](https://github.com/harness/harness-core/blob/472bc7db682314e26b60b33f4f76f992d86292ff/pipeline-service/modules/ng-triggers/BUILD.bazel#L15)):*
> ```Starlark
>         "//890-sm-core:module",
>         "//930-ng-core-clients:module",
>         "//945-account-mgmt:module",
> ```

why do we need this dependency?

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/BUILD.bazel` line 15 at r5](https://reviewable.io/reviews/harness/harness-core/36173#-N9aDj_GDfYYn5gMWW3j:-N9bKawt2h6Udm3f0-E4:b-4gqksa) ([raw file](https://github.com/harness/harness-core/blob/472bc7db682314e26b60b33f4f76f992d86292ff/pipeline-service/modules/ng-triggers/BUILD.bazel#L15)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

why do we need this dependency?
</blockquote></details>

I added it because we are importing AccountClient, from 945-account-mgmt, in the new class UrlHelper that I'm adding. It is for getting the base UI URL for building links. Is there a better way to do this? Thank you!
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/NGProcessWebhookResponseDTO.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/36173#-N9_phtW9wIm0WN6eRfL:-N9amOajDqaeHgAa1c2x:bb5rwpx) ([raw file](https://github.com/harness/harness-core/blob/472bc7db682314e26b60b33f4f76f992d86292ff/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto/NGProcessWebhookResponseDTO.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@Schema annotation as this response is exposed to customer, this is for openapispec
</blockquote></details>

Done, thank you for the suggestion!
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 268 at r5](https://reviewable.io/reviews/harness/harness-core/36173#-N9_px9E5FqvRr05eLwg:-N9amRCm0VkdTsqO3LRn:br5u6en) ([raw file](https://github.com/harness/harness-core/blob/472bc7db682314e26b60b33f4f76f992d86292ff/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L268)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@Parameter annotations with description on each field
</blockquote></details>

 Done, thank you for the suggestion!

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 268 at r5](https://reviewable.io/reviews/harness/harness-core/36173#-N9_px9E5FqvRr05eLwg:-N9eE3Xv0GuQjTJ-v9Lp:b-rlhhli) ([raw file](https://github.com/harness/harness-core/blob/472bc7db682314e26b60b33f4f76f992d86292ff/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L268)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

 Done, thank you for the suggestion!
</blockquote></details>

Another suggestion, PipelineResource check this, we already have discussed with product on what this description for some existing fields look like, so we should use those constants only.

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java` line 268 at r5](https://reviewable.io/reviews/harness/harness-core/36173#-N9_px9E5FqvRr05eLwg:-N9gIVT3E0T9LnsTMtpZ:bde075n) ([raw file](https://github.com/harness/harness-core/blob/472bc7db682314e26b60b33f4f76f992d86292ff/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerWebhookConfigResource.java#L268)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Another suggestion, PipelineResource check this, we already have discussed with product on what this description for some existing fields look like, so we should use those constants only.
</blockquote></details>

Updated to use the constants as descriptions, thank you for the suggestion!

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: 1. unresolved discussions.

**Review by vcalasansh — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173#-:-N9gMENnDHHB_5jh2vsc:bnfp4nl)* status: 1. unresolved discussions.

**Review by vcalasansh — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: 1. unresolved discussions.

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36173)* status: :shipit: complete! ✓

**Pull request merged**
