### PR TITLE
[fix]: [PL-43759]: Fixing scope info helper and removing redundant remote call

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
This PR takes care below changes
- Avoid remote call in AccountOrgProjectValidator [Done]
- `io.harness.ng.core.impl.ScopeInfoHelper#populateScopeInfo` This method is currently error prone. If we pass scope level as ACCOUNT and also pass non null values for org and project then scope info will have org and project identifiers as well. Since the method is public, using the scope info returned by this method can result into unexpected results. [Done]
- Added comment in code - As part of ScopeFilter improvement to cater combinations of API structure added comment for what api patterns supported and whats not, . [Done]

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57122)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger ut6

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57122)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoHelper.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/57122#-Nmf21fc-ja_UBjwE8Ik:-Nmf21fc-ja_UBjwE8Il:b-ruf61c) ([raw file](https://github.com/harness/harness-core/blob/f78d019f79883f3413810dd277e1ef3ce8602a97/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoHelper.java#L20)):*
> ```Java
> public class ScopeInfoHelper {
>   private static final String SCOPE_INFO_CACHE_KEY_DELIMITER = "/";
>   public ScopeInfo populateScopeInfo(final ScopeLevel scopeType, final String uniqueId, final String accountIdentifier,
> ```

Lets make this method package-private
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoHelper.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/57122#-Nmf24BF8RRrNFmJ3TPk:-Nmf24BF8RRrNFmJ3TPl:b-ruf61c) ([raw file](https://github.com/harness/harness-core/blob/f78d019f79883f3413810dd277e1ef3ce8602a97/120-ng-manager/src/main/java/io/harness/ng/core/impl/ScopeInfoHelper.java#L33)):*
> ```Java
>   }
> 
>   public String getScopeInfoCacheKey(
> ```

Lets make this method package-private

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57122)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
