### PR TITLE
[fix]: [CDS-38488]: fix error summary and logging

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes

Passing CommandUnit progress across delegates tasks.
Fix error summary message

Is it new task type?   -  NO

Did you add a new class which is added in kryo serialization?   -   NO

Did you make changes to the code in a backward-compatible manner?  -  YES

will the new version of the delegate receive old version task and process?  -  YES

If new version of the manager receives response for the old task will it be able to handle it successfully?  -  YES

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager.  -  YES

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay.  -  YES

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay.  -  YES

Did you remove an enum →  NO

Did you add an enum →   NO

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33973)

### CODE REVIEW

**Review by nassergonzalez — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33973)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33973)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFilesTaskParams.java` line 36 at r5](https://reviewable.io/reviews/harness/harness-core/33973#-N3thfKp2K8bzBY0G8BT:-N3thfKp2K8bzBY0G8BU:b-3dwf46) ([raw file](https://github.com/harness/harness-core/blob/f39a5f55585c8021c105669a4957f86bae0411f1/950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/aws/s3/AwsS3FetchFilesTaskParams.java#L36)):*
> ```Java
>   @Builder.Default private boolean shouldOpenLogStream = true;
>   private boolean closeLogStream;
>   private CommandUnitsProgress commandUnitsProgress;
> ```

questions

1. what happens if delegate doesn't has this field but manager sends it
2. have you tested this code flow with older version of delegate and newer version of manager?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33973)* status: 0 of 1 approvals obtained.

**Pull request closed without merging**
