### PR TITLE
feat: [PIE-3094]: Create rbac permission for environment group

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)

### CODE REVIEW

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, line 282 at r1](https://reviewable.io/reviews/harness/harness-core/31781#-MzDzwPQECkw76l1WywU:-MzDzwPQECkw76l1WywV:brspc1j) ([raw file](https://github.com/harness/harness-core/blob/dd004e9b6920d57375cf82fd92583c3b7236b81a/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L282)):*
> ```YAML
>       - account
>       - organization
>       - project
> ```

Update the version

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, line 282 at r1](https://reviewable.io/reviews/harness/harness-core/31781#-MzDzwPQECkw76l1WywU:-MzE6tIE3fjaQsV-q9MJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dd004e9b6920d57375cf82fd92583c3b7236b81a/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L282)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Update the version
</blockquote></details>

Done.

**Review by karansiwach360 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml, line 25 at r3](https://reviewable.io/reviews/harness/harness-core/31781#-MzEElTg7pEvhEH9Td6B:-MzEElTg7pEvhEH9Td6C:b-tofikt) ([raw file](https://github.com/harness/harness-core/blob/6844feb61c951bb34e7eacea8d72d446563d7392/access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml#L25)):*
> ```YAML
>   - identifier: ENVIRONMENT
>     permissionKey: environment
>   - identifier: ENVIRONMENT_GROUP
> ```

version
___
*[access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml, line 18 at r2](https://reviewable.io/reviews/harness/harness-core/31781#-MzEEmgzE7Fv1w2ZKl72:-MzEEmgzE7Fv1w2ZKl73:b-tofikt) ([raw file](https://github.com/harness/harness-core/blob/cec2414ce26666391075dbdc1cb03d0e42640ea7/access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml#L18)):*
> ```YAML
>       - core_service_view
>       - core_environment_view
>       - core_environmentgroup_view
> ```

version

**Review by karansiwach360 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namanvermah — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 6 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/rbac/CDNGRbacPermissions.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/31781#-MzEIMRBDhBmXtREjAPI:-MzEIMRBDhBmXtREjAPJ:b-vov1vx) ([raw file](https://github.com/harness/harness-core/blob/1263b21e6cb8004bd288ca7adf0f9786e36c94bf/125-cd-nextgen/src/main/java/io/harness/rbac/CDNGRbacPermissions.java#L35)):*
> ```Java
>   public final String ENVIRONMENT_GROUP_UPDATE_PERMISSION = "core_environmentgroup_edit";
>   public final String ENVIRONMENT_GROUP_VIEW_PERMISSION = "core_environmentgroup_view";
>   public final String ENVIRONMENT_GROUP_DELETE_PERMISSION = "core_environmentgroup_delete";
> ```

Add runtime access permission as well.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 6 file(s) to review. 2 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/rbac/CDNGRbacPermissions.java, line 35 at r4](https://reviewable.io/reviews/harness/harness-core/31781#-MzEIMRBDhBmXtREjAPI:-MzEIeNQ0kOxsJ6zG4gV:b-2l6pgi) ([raw file](https://github.com/harness/harness-core/blob/1263b21e6cb8004bd288ca7adf0f9786e36c94bf/125-cd-nextgen/src/main/java/io/harness/rbac/CDNGRbacPermissions.java#L35)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Add runtime access permission as well.
</blockquote></details>

As per @juhi - we won't be having runtime access permission for env group. During runtime, we will be checking access permission of individual environments of env group. Here is the doc for the same. 
https://harness.atlassian.net/wiki/spaces/PIPE/pages/21041676772/Tech+Spec+Multi+Environment+And+Multi+Infra+Support+NG#RBAC-for-envGroup-apis

**Review by gupta-utkarsh — APPROVED** [review]
Please make sure Access Control is released before you start using these permissions.

> Reviewed 2 of 6 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781#-:-MzEPldO7xaeO81XyMis:b2wx2ap)* status: 2 change requests. 2. unresolved discussions.

**Review by reetika04 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: 2 change requests. 2. unresolved discussions.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781#-:-MzETlsS-DBVrGPkI-RA:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31781)* status: :shipit: complete! ✓

**Pull request merged**
