### PR TITLE
[feat]: [PIE-5616]: Added additional validations on remote entities for being Pipeline Yaml

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: While fetching remote entities: 
User creates an entity <id: x, type: pipeline, filePath: abc.yaml>  in non  default branch.
User creates an entity <id: y, type: template, filePath: abc.yaml>  in  default branch.
Now whenever we will try to fetch <id: x, type: pipeline>  from remote then  by default,  BE is fetching same file from default branch and we will end up getting <id: y, type: template> .

Change: Added additional check for that entity to be the required entity(Pipeline).

Testing: Expected experience was reproduced on local. Also Automation test: PipelineCRUDGitExperienceTest passed against it.
Screenshot 2022-11-21 at 10 10 08 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 279 at r3](https://reviewable.io/reviews/harness/harness-core/39687#-NGLvArd0UJ43whH8w7i:-NGLvArd0UJ43whH8w7j:ba0agb) ([raw file](https://github.com/harness/harness-core/blob/5d855758ff9319582c644871a32fefda8fad3e75/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L279)):*
> ```Java
>     String resolveTemplateRefsInPipeline = templateMergeResponseDTO.getMergedPipelineYaml();
> 
>     validatePipelineExistence(pipelineEntity.getYaml());
> ```

can this be a generic method in some helper? Basically, it can be a boolean method which just checks if given yaml is of pipeline or not. Then we can use this method here and do our logic on top of it. Or the method can also throw exception explaining the reason why its not pipeline yaml etc.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 279 at r3](https://reviewable.io/reviews/harness/harness-core/39687#-NGLvArd0UJ43whH8w7i:-NGLvVAm6UgMB_DbAtIZ:b-587dd1) ([raw file](https://github.com/harness/harness-core/blob/5d855758ff9319582c644871a32fefda8fad3e75/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L279)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can this be a generic method in some helper? Basically, it can be a boolean method which just checks if given yaml is of pipeline or not. Then we can use this method here and do our logic on top of it. Or the method can also throw exception explaining the reason why its not pipeline yaml etc.
</blockquote></details>

I see its already inside helper. We can later make it public if required. Please ignore my comment.

Can we just rename this method a bit better eg: checkIfPipelineYaml() etc?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 279 at r3](https://reviewable.io/reviews/harness/harness-core/39687#-NGLvArd0UJ43whH8w7i:-NGLyofaDIj5RZnfWqZ9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5d855758ff9319582c644871a32fefda8fad3e75/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L279)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see its already inside helper. We can later make it public if required. Please ignore my comment.

Can we just rename this method a bit better eg: checkIfPipelineYaml() etc? 
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 285 at r5](https://reviewable.io/reviews/harness/harness-core/39687#-NHNi6rICV4RKDZzn3qY:-NHNi6rICV4RKDZzn3qZ:b-d134u0) ([raw file](https://github.com/harness/harness-core/blob/70eaa6991d3321bf56d5301a849892874abfef53/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L285)):*
> ```Java
> 
>   @VisibleForTesting
>   void checkIfRootNodeIsPipeline(String pipelineYaml) {
> ```

@sahilhindwani-harness can we move this method to your single validation file? easier to move all validation there now rather than later?
cc: @senjucanon2 



_Code quote:_
```Java
void checkIfRootNodeIsPipeline
```

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: Some of the checks are too old. 1 change requests.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 285 at r5](https://reviewable.io/reviews/harness/harness-core/39687#-NHNi6rICV4RKDZzn3qY:-NHO4L3U4riOkppV0QcB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70eaa6991d3321bf56d5301a849892874abfef53/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L285)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sahilhindwani-harness can we move this method to your single validation file? easier to move all validation there now rather than later?
cc: @senjucanon2 
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39687)* status: :shipit: complete! ✓

**Pull request merged**
