### PR TITLE
[feat]: [CDS-72746]: Integrated the new setting with repo-list-Apis

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: AXA was impressed with one of the feature of Old-git-sync feature that was we can restrict user to work only in specific repositories, but in new GitX if user had an account level connector then it is not possible to restrict activities to a specified repos.

Changes: We now use a setting : GitX RepoAllowList which will restrict activities to only specified repos. This PR applies that setting to list-repo API, only allowed repos will be filtered.

Impact: List-repo API and related feature are impacted by this.

Testing: Various use case with null, empty and valid repoNames and repoNames having org/ in it have been tested.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYra1X11wmgdXnZFYfN:-NYra1X11wmgdXnZFYfO:b-w7l33v) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L27)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class GitRepoAllowlistHelper {
>   @Inject private GitXSettingsHelper gitXSettingsHelper;
> ```

blank line

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraDhi4LJBQq2_LtfO:-NYraDhi4LJBQq2_LtfP:b-4918fh) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L28)):*
> ```Java
> public class GitRepoAllowlistHelper {
>   @Inject private GitXSettingsHelper gitXSettingsHelper;
>   public GetUserReposResponse filterAllowedReposInResponse(
> ```

can't we make this method agnostic of its caller? The method should simply take some input and return output such a way that any caller can use it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraSjhDLFAgBxbasjD:-NYraSjhDLFAgBxbasjE:b-9p26h7) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L51)):*
> ```Java
>   }
> 
>   private static boolean validateIfCurrentRepoIsAllowed(List<String> repoAllowlist, String repoName) {
> ```

why is this static method?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrakpu8fhf7cMyQYbv:-NYrakpu8fhf7cMyQYbw:b-shyqnk) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L69)):*
> ```Java
>   }
> 
>   private static boolean validatePresenceOfOrgInAllowedRepo(String repoAllowlistElem) {
> ```

"Org" is just a keyword for Github, for others the semantic could be project or something totally random. So, we should choose a better function name here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraz5r8Y4WsyO7MI8c:-NYraz5r8Y4WsyO7MI8d:b-byp5zy) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L64)):*
> ```Java
>   }
> 
>   @NotNull
> ```

why notNull?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrb0ov1JLInGjLkt_4:-NYrb0ov1JLInGjLkt_5:b-e9h698) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L65)):*
> ```Java
> 
>   @NotNull
>   private static String getRepoNameFromAllowedRepo(String repoAllowlistElem) {
> ```

why static?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrb3600l44RlXb_6j_:-NYrb3600l44RlXb_6ja:b-e9h698) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L69)):*
> ```Java
>   }
> 
>   private static boolean validatePresenceOfOrgInAllowedRepo(String repoAllowlistElem) {
> ```

why static?

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrbjab3D0xNqNkadX6:-NYrbjab3D0xNqNkadX7:bf81j6m) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L119)):*
> ```Java
>   }
> 
>   public List<String> getGitRepoAllowlist(String accountIdentifier, String orgIdentifier, String projIdentifier) {
> ```

How much time and effort did you save by not writing "ect"?

PS: Lets use proper conventional argument names for keywords such as project or org or account etc. just to keep up with consistent codebase.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 5 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 27 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYra1X11wmgdXnZFYfN:-NYsTuO43k_y0zrQLEUT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraDhi4LJBQq2_LtfO:-NYsVwVr-yGU3cOsCwsa:b-sp4zme) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can't we make this method agnostic of its caller? The method should simply take some input and return output such a way that any caller can use it.
</blockquote></details>

will try more on this, Maybe will need your inputs here.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraSjhDLFAgBxbasjD:-NYsU5kz8rsqLwl35SCI:bg6q23k) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is this static method?
</blockquote></details>

It was default impl of Intellij extract method, removed .
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraz5r8Y4WsyO7MI8c:-NYsUMaF7Cybp7aRbgz4:b-a0v06c) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why notNull?
</blockquote></details>

It basically indicates that method's param shouldn't not be null as the impl requires. It serves as a form of documentation to communicate the developer's intention and to enforce non-nullability i thougth it was good to have it, anyway removed.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrb0ov1JLInGjLkt_4:-NYsV05REkk2vhUnO-w6:brpmqc3) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L65)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why static?
</blockquote></details>

removed.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrb3600l44RlXb_6j_:-NYsV9-e-vmGhBuEKqAa:bss4a2b) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L69)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why static?
</blockquote></details>

Removed.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrakpu8fhf7cMyQYbv:-NYsVeGDCAPkJNmGXmit:b-zfa8pb) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L69)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

"Org" is just a keyword for Github, for others the semantic could be project or something totally random. So, we should choose a better function name here.
</blockquote></details>

Changed method name to: "validateIfRepoNameContainsParentDirectoryReference"
___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrbjab3D0xNqNkadX6:-NYsVm6B62dWe851DBXM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L119)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

How much time and effort did you save by not writing "ect"?

PS: Lets use proper conventional argument names for keywords such as project or org or account etc. just to keep up with consistent codebase.
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrakpu8fhf7cMyQYbv:-NYvzb442KTf6eo9O66h:b-vv7u1x) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L69)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Changed method name to: "validateIfRepoNameContainsParentDirectoryReference"
</blockquote></details>

A better name could be : "isAbsoluteRepo". Absolute is synonymous to general terminology which means is it just the exact thing you're talking about eg: absolute value etc.
I'm fine with keeping the current name as well, lets just add some comment on it to better describe what we are trying to do here.

Also, please change argument name to : "String repo". This method in its own sense doesn't care about its caller, it should just depend on its particular job that it does.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 134 at r5](https://reviewable.io/reviews/harness/harness-core/49699#-NYw-N1lCVI_c5-ysajI:-NYw-N1lCVI_c5-ysajJ:bd16ibs) ([raw file](https://github.com/harness/harness-core/blob/b954634af50166f621d481d8aa590a53ae46e448/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L134)):*
> ```Java
> 
>     List<String> listOfRepos = List.of(repoAllowlist.split(","));
>     List<String> sanitisedListOfRepos = new ArrayList<>();
> ```

please can you check if this sanitisation can be moved to a proper util. Its a very basic job where a list of input string is passed and output is list of trimmed strings.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYrakpu8fhf7cMyQYbv:-NYw1A471dSb9o0-VFgp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L69)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

A better name could be : "isAbsoluteRepo". Absolute is synonymous to general terminology which means is it just the exact thing you're talking about eg: absolute value etc.
I'm fine with keeping the current name as well, lets just add some comment on it to better describe what we are trying to do here.

Also, please change argument name to : "String repo". This method in its own sense doesn't care about its caller, it should just depend on its particular job that it does.
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/49699#-NYraDhi4LJBQq2_LtfO:-NYwe-w53cD6-dEeBGnh:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/381422087755f9fae1d214d126100d83000f5864/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L28)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

will try more on this, Maybe will need your inputs here.
</blockquote></details>

Done

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 30 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx6zbc2Og8bLiu17l1:-NYx6zbc2Og8bLiu17l2:bjqezu1) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L30)):*
> ```Java
>   public Set<String> filterRepoList(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, Set<String> repoList) {
>     List<String> repoAllowlist =
> ```

if repo list is empty, return right away.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 36 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7Npn7I2tApXhH_ZP:-NYx7Npn7I2tApXhH_ZQ:bvxqtg1) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L36)):*
> ```Java
>       Set<String> filterRepoList = new HashSet<>();
>       for (String repo : repoList) {
>         if (validateIfCurrentRepoIsAllowed(repoAllowlist, repo)) {
> ```

instead of passing repo list, we should pass repo set.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 59 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7XLW5OL7IGjZY_MX:-NYx7XLW5OL7IGjZY_MY:bxybpb4) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L59)):*
> ```Java
>   }
> 
>   private String getAbsoluteRepoNameFromFullRepoPath(String repoAllowlistElem) {
> ```

lets keep it simply : "getAbsoluteRepoName", it will be on same lines as our other method which is "isAbsoluteRepo"

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 63 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7yNbClOOipJFVmL-:-NYx7yNbClOOipJFVmL0:b-a8ah8m) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L63)):*
> ```Java
>   }
> 
>   private boolean isAbsoluteRepo(String repo) {
> ```

Lets add comments on this method so that there's no confusion at all.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 36 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7Npn7I2tApXhH_ZP:-NYx8cC-0xZe7kraN3rb:b2dvwad) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L36)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

instead of passing repo list, we should pass repo set.
</blockquote></details>

If its big effort, we can ignore this considering the size of list are going to be pretty small.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 30 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx6zbc2Og8bLiu17l1:-NYx9euc8xAtF12XCX8F:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L30)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

if repo list is empty, return right away.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 36 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7Npn7I2tApXhH_ZP:-NYxAAiZ1wQuQyWXDjdZ:btdda2v) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L36)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

If its big effort, we can ignore this considering the size of list are going to be pretty small.
</blockquote></details>

Skipping this for now.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 52 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7l4g5wCEmoaMsZpZ:-NYxAY32-HAMjJCAd-36:bcgeg3y) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L52)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

complete repo name should also be compared in the list. eg: if input-list has "org/vivek" as repo and my filter list also has the same, it won't give me correct results right now. Ideally, it should give me that repo name.
</blockquote></details>

if there is / in the allowListElem which is fetched from setting, then we always compare full name.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 59 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7XLW5OL7IGjZY_MX:-NYxAppE4cNamnYLudBQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L59)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets keep it simply : "getAbsoluteRepoName", it will be on same lines as our other method which is "isAbsoluteRepo"
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 63 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7yNbClOOipJFVmL-:-NYxBv8XDVl9qtNAUCiV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets add comments on this method so that there's no confusion at all.
</blockquote></details>

Done.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 52 at r12](https://reviewable.io/reviews/harness/harness-core/49699#-NYx7l4g5wCEmoaMsZpZ:-NYxWJ0RCrAFiM28Dpxa:b7tyod9) ([raw file](https://github.com/harness/harness-core/blob/993232e991e3721a5f99aa157d692cf0be446408/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L52)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

if there is / in the allowListElem which is fetched from setting, then we always compare full name.
</blockquote></details>

This case is already tested, will give correct result. There's already a UT in the PR testing that case.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java` line 65 at r13](https://reviewable.io/reviews/harness/harness-core/49699#-NYx_Z7R6JViyE6-rO5o:-NYx_Z7R6JViyE6-rO5p:b-tegsxw) ([raw file](https://github.com/harness/harness-core/blob/f4a5a23cd71c9146cf9db8d634799e95206d32ab/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoAllowlistHelper.java#L65)):*
> ```Java
> 
>   private String getAbsoluteRepoName(String repoAllowlistElem) {
>     return repoAllowlistElem.substring(repoAllowlistElem.lastIndexOf('/') + 1);
> ```

qq: what if repoAllowListElem is "/" or "abc/"? Make sure it works fine and doesn't lead to some NPE possibility

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 4 files at r2, 1 of 3 files at r10, 1 of 4 files at r11, 5 of 6 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49699)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
