### PR TITLE
fix: [PL-38448]: When processing RBAC entities, creating ACLs in batches.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
When processing RBAC entities, creating ACLs in batches. This is needed because when some role assignments have resource groups with specific resource selectors and many scopes selected it leads to ACLs created in millions and that is held in memory. This leads to memory spike and Pod going out of memory.
The batch size is 50000.
Also, abstracted batching and creation of ACLs in ChangeConsumerService. This is avoid spreading logic to batch ACL creation in each change consumer.

Test cases:
Created Role Assignment with OOB roles and resource groups. 
Created custom roles and resource groups and performed CRUD operations.
Verified ACLs created in batches.

<google-sheets-html-origin><style type="text/css"></style>

  | Local |   | PreQA
-- | -- | -- | --
Permissions | 90 |   | 90
Resources | 17 |   | 17
Users | 7 |   | 7
Scopes | 9 | (that includes 8 Orgs and Account) | 9
  |   |   |  
Total Resource selectors | 153 |   | 153
ACLs | 96390 |   | 96390
Implicit ACLs/user | 17 | 8 for Project, 8 for Org, 1 for Account |  
Implicit ACLs | 119 |   |  
Total ACLs Created | 96509 | Inlcudes implicit ACLs | 96509
  |   |   |  
Add One User to the User Group |   |   |  
Total ACLs Created | 13787 |   | 13787
  |   |   |  
Remove one Org from RG |   |   |  
Total ACLs Deleted | 12344 |   | 12344
Add one Org to RG |   |   |  
Total ACLs Created | 12344 |   | 12344
  |   |   |  
Removed 3 permissions from Role |   |   |  
Total ACLs Deleted | 2856 |   | 2856
  |   |   |  
Added 2 permissions to Role |   |   |  
Total ACLs Created | 1904 |   | 1904

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47405)

### CODE REVIEW

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47405)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerService.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/47405#-NUfrsvv5NaOyN45Q0_d:-NUfwNx55UoDsxY7aIP7:b-6pdufh) ([raw file](https://github.com/harness/harness-core/blob/57cf48793ba17d7ee85fb9e87b0fed20f903be06/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerService.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Do we need getMethods anymore in this interface?
Also, should we change the name of this interface?
</blockquote></details>

Yes will remove get Methods. right I was thinking same. This interface should be ACLGeneratorService.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47405)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/47405#-NUfvGY_0Qvz49DGkv9D:-NUfxTJN2SUcvVkpAKPC:bbx9huj) ([raw file](https://github.com/harness/harness-core/blob/57cf48793ba17d7ee85fb9e87b0fed20f903be06/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L122)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can this logic be simplified. 

We keep a list of ACLs. While generating ACLs, we add them to list, if list exceeds a certain size lets say 50K, we persist ACLs to disk, clear the list and continue the iteration.
</blockquote></details>

sounds good. will change it.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47405)* status: 16 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerService.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/47405#-NUfrsvv5NaOyN45Q0_d:-NUk6J9REpkCW9aCQLJz:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/57cf48793ba17d7ee85fb9e87b0fed20f903be06/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerService.java#L20)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Yes will remove get Methods. right I was thinking same. This interface should be ACLGeneratorService.
</blockquote></details>

Changed
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/47405#-NUfvGY_0Qvz49DGkv9D:-NUk6RdE8kmusuvIjSNZ:b499q7j) ([raw file](https://github.com/harness/harness-core/blob/57cf48793ba17d7ee85fb9e87b0fed20f903be06/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L122)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

sounds good. will change it.
</blockquote></details>

Changed
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java` line 150 at r2](https://reviewable.io/reviews/harness/harness-core/47405#-NUful0k4J_njHAXr09d:-NUk6Mq25ci7KDhJ5Jfj:b-v6s1o3) ([raw file](https://github.com/harness/harness-core/blob/57cf48793ba17d7ee85fb9e87b0fed20f903be06/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/ChangeConsumerServiceImpl.java#L150)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Logic is not clear
</blockquote></details>

Removed.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47405#-:-NV-uW2PD4lfuEK7bXvR:bnfp4nl)* status: 1 of 2 approvals obtained.

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47405#-:-NV0NPHgAxixlvu90t1E:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
