### PR TITLE
[feat]: [CDS-39649] support azure webApps basic deployment rollback

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
Support azure webApps basic deployment rollback

Is it new task type?   -   NO

Did you add a new class which is added in kryo serialization.  -  NO

Did you make changes to the code in a backward-compatible manner?   -   YES

will the new version of the delegate receive old version task and process?  -   YES

If new version of the manager receives response for the old task will it be able to handle it successfully?  -  YES

Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager.   -   NO

If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay.  -  YES

if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay.  -   YES

Did you remove an enum →.   NO
Did you add an enum →   NO

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35277)

### CODE REVIEW

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35277#-:-N6qLvv91Zi3KoILkm4G:bnfp4nl)* status: :shipit: complete! ✓

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35277)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger codebasehash

**Review by gaurav-jain1 — APPROVED** [review]

**Comment by tmacari-harness** [comment]
trigger codebasehash

**Pull request merged**
