### PR TITLE
[feat]:[PL-27345]: When a user is present in NG but on a diff Account. SCIM Get and Search should return him. 

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37076)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37076)

**Comment by mohitg0795** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/37076#-NAyShvl6T4JMKCiaVxf:-NAyShvl6T4JMKCiaVxg:b-mx5erc) ([raw file](https://github.com/harness/harness-core/blob/bf2f59d884fccbd0526911595ac744f39031cd39/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java#L110)):*
> ```Java
>   boolean verifyHarnessSupportGroupUser();
> 
>   boolean checkUserPartOfAccountInNg(String accountId, Optional<UserMetadataDTO> userOptional);
> ```

Any specific reason to take optional user argument? The method clearly means to check if user is part of ng or not, so we it would be better to just do that and take in user as an argument rather than optional.
Also, better conventional method name would be : "isUserPartOfAccountInNg"

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/37076#-NAyTsO59N8jrkxlPVjk:-NAyTsO59N8jrkxlPVjl:b-qh46gy) ([raw file](https://github.com/harness/harness-core/blob/bf2f59d884fccbd0526911595ac744f39031cd39/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L149)):*
> ```Java
>         return userInfo.map(this::buildUserResponse).get();
>       } else {
>         throw new InvalidRequestException("User does not exist in NG");
> ```

Suggestion: it will return same exception in both cases when either the user doesn't exist or when user isn't a part of account in NG. Better would be to have 2 different error messages in these cases as it can help to understand better about the context in case of any issues.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/37076#-NAyTsO59N8jrkxlPVjk:-NAy_D_m0AMfL3Va_CuS:b-1jtbin) ([raw file](https://github.com/harness/harness-core/blob/bf2f59d884fccbd0526911595ac744f39031cd39/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L149)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Suggestion: it will return same exception in both cases when either the user doesn't exist or when user isn't a part of account in NG. Better would be to have 2 different error messages in these cases as it can help to understand better about the context in case of any issues.
</blockquote></details>

Have made that change

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java` line 110 at r1](https://reviewable.io/reviews/harness/harness-core/37076#-NAyShvl6T4JMKCiaVxf:-NAy_K_7EFzX1RKCJj7T:bdna5bu) ([raw file](https://github.com/harness/harness-core/blob/bf2f59d884fccbd0526911595ac744f39031cd39/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java#L110)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Any specific reason to take optional user argument? The method clearly means to check if user is part of ng or not, so we it would be better to just do that and take in user as an argument rather than optional.
Also, better conventional method name would be : "isUserPartOfAccountInNg"
</blockquote></details>

Used an internal function instead.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37076)* status: 4 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/37076#-NAynKiu8n-PaOADzOPL:-NAynKiv9DoYZIXf9K-E:bbs3jxf) ([raw file](https://github.com/harness/harness-core/blob/ce267f9cf208f3e6f9f2eec35cdd2978a774987f/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L176)):*
> ```Java
>       if (!userOptional.isPresent()) {
>         usersNotinNG.add(scimUser);
>       } else if (!ngUserService.isUserAtScope(
> ```

why is it an else condition? Can't we combine both the conditions into single if? Its doing the exact same operation on both if and else blocks
Also typo in the variable name, it should be "usersNotInNG"

**Review by shashank-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37076)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/37076#-NAynKiu8n-PaOADzOPL:-NB5haFw4pGqsCD9W-Wn:b6w8hok) ([raw file](https://github.com/harness/harness-core/blob/ce267f9cf208f3e6f9f2eec35cdd2978a774987f/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L176)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it an else condition? Can't we combine both the conditions into single if? Its doing the exact same operation on both if and else blocks
Also typo in the variable name, it should be "usersNotInNG"
</blockquote></details>

If says this user is not present in ng in any account.
Else says this user might be present in ng but as part of this account at this this scope.
Typo has been corrected.

**Pull request merged**
