### PR TITLE
[feat]: [CDS-80682]: Update and Get Flow for GitX-ENV

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Change: Added support for update and get flow for a remote env.
Testing: Yaml was updated on github and DB as well.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger messagecheck, uts

**Comment by adivishy1** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 254 at r2](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy2yTX9HwGgWq7pDPR:-Nfy2yTX9HwGgWq7pDPS:berywxd) ([raw file](https://github.com/harness/harness-core/blob/f435cc93fd7b53a232a1c1649ccd30f120634b42/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L254)):*
> ```Java
>     Optional<Environment> environment = environmentService.get(accountId, orgIdentifier, projectIdentifier,
>         environmentIdentifier, deleted, GitXUtils.parseLoadFromCacheHeaderParam(loadFromCache), loadFromFallbackBranch);
>     if (environment.isPresent()) {
> ```

why are changing the api contract for the get api? 
can you pls update the pr heading/description if we are modifying contract for get as well

**Comment by adivishy1** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy4SXM4O8JLK_EfQcR:-Nfy4SXM4O8JLK_EfQcS:b-fbxbzp) ([raw file](https://github.com/harness/harness-core/blob/f435cc93fd7b53a232a1c1649ccd30f120634b42/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java#L40)):*
> ```Java
>    */
>   Optional<Environment> getMetadata(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String environmentIdentifier, boolean deleted);
> ```

why do we need a new method for fetching the metadata? why not pass another filed which says getMetadataOnly? 
in the impl, we are anyways passing the value as true for getMetadataOnly for the method getEnvironmentByRef

**Review by adivishy1 — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 8 file(s) to review. 0 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 8 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 254 at r2](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy2yTX9HwGgWq7pDPR:-NfyEMf95lXbc_bZeUBo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f435cc93fd7b53a232a1c1649ccd30f120634b42/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L254)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

why are changing the api contract for the get api? 
can you pls update the pr heading/description if we are modifying contract for get as well
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy4SXM4O8JLK_EfQcR:-NfyEPXZ7IZskAgRAfiM:b-u6mjoe) ([raw file](https://github.com/harness/harness-core/blob/f435cc93fd7b53a232a1c1649ccd30f120634b42/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java#L40)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

why do we need a new method for fetching the metadata? why not pass another filed which says getMetadataOnly? 
in the impl, we are anyways passing the value as true for getMetadataOnly for the method getEnvironmentByRef
</blockquote></details>

It was done to be in sync with the impl of GitX-Services.

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy_PiqCTN-8kmybL5L:-Nfy_PiqCTN-8kmybL5M:b-l9rlmc) ([raw file](https://github.com/harness/harness-core/blob/9ee70a39b7548ed108aa1b2defeb3006b7d36f35/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L127)):*
> ```Java
>       Update update = EnvironmentFilterHelper.getUpdateOperations(environment);
>       RetryPolicy<Object> retryPolicy = getRetryPolicy(
>           "[Retrying]: Failed updating Service; attempt: {}", "[Failed]: Failed updating Service; attempt: {}");
> ```

"Environment"
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy_fUZE1ZQ2F4ZVPZE:-Nfy_fUZE1ZQ2F4ZVPZF:b-l9rlmc) ([raw file](https://github.com/harness/harness-core/blob/9ee70a39b7548ed108aa1b2defeb3006b7d36f35/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L150)):*
> ```Java
>       return updateEnvironmentEntityInMongo(query, update, retryPolicy);
>     } catch (ExplanationException | HintException | ScmException e) {
>       log.error(String.format("Error while updating service [%s]", environment.getIdentifier()), e);
> ```

"Environment"
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 296 at r3](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy_lMb4RHkmzkf4G4Y:-Nfy_lMb4RHkmzkf4G4Z:b-l9rlmc) ([raw file](https://github.com/harness/harness-core/blob/9ee70a39b7548ed108aa1b2defeb3006b7d36f35/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L296)):*
> ```Java
>       if (shouldRetryWithFallBackBranch(GitXUtils.getScmExceptionIfExists(ex), branch, fallBackBranch)) {
>         log.info(String.format(
>             "Retrieving service [%s] from fall back branch [%s] ", savedEntity.getIdentifier(), fallBackBranch));
> ```

"Environment"

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 6 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 127 at r3](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy_PiqCTN-8kmybL5L:-Nfyagz17TMrBC7C6DJA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ee70a39b7548ed108aa1b2defeb3006b7d36f35/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L127)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

"Environment"
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 150 at r3](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy_fUZE1ZQ2F4ZVPZE:-NfyagZaEkeuFWSjIsbR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ee70a39b7548ed108aa1b2defeb3006b7d36f35/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L150)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

"Environment"
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 296 at r3](https://reviewable.io/reviews/harness/harness-core/53635#-Nfy_lMb4RHkmzkf4G4Y:-NfyagET9EF0QnDS6jva:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ee70a39b7548ed108aa1b2defeb3006b7d36f35/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L296)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

"Environment"
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger ut9

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz4YLaEyiIxZyZ7D99:-Nfz4YLaEyiIxZyZ7D9A:b-lancjg) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java#L34)):*
> ```Java
> 
>   /**
>    * this method will return the service entity as stored in the MongoDB
> ```

"Environment" here
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 215 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz5ZBA4earBVezqM4N:-Nfz5ZBA4earBVezqM4O:b-u2t93k) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L215)):*
> ```Java
>       String environmentRef, boolean deleted) {
>     // default behavior to not load from cache and fallback branch
>     return getEnvironmentByRef(
> ```

This would bypass the non null check, better would be to call just get method which does that check.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz4jX76O-2OB2jO3vM:-Nfz4jX76O-2OB2jO3vN:b-7f1q9n) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L230)):*
> ```Java
>   @Override
>   public Optional<Environment> getMetadata(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String serviceRef, boolean deleted) {
> ```

environmentRef
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 261 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz6LZsDs5tCdjaTdif:-Nfz6LZsDs5tCdjaTdig:btj46rg) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L261)):*
> ```Java
>     Set<EntityDetailProtoDTO> referredEntities = getAndValidateReferredEntities(requestEnvironment);
>     Optional<Environment> environmentOptional =
>         get(requestEnvironment.getAccountId(), requestEnvironment.getOrgIdentifier(),
> ```

we should get metadata only here since YAML we're getting from UI. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 270 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz6SEz4btd3vOa9fX_:-Nfz6SEz4btd3vOa9fXa:b-i41bzt) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L270)):*
> ```Java
>                                             .withName(requestEnvironment.getName())
>                                             .withTags(requestEnvironment.getTags())
>                                             .withType(requestEnvironment.getType());
> ```

Please confirm there are no other fields in the entity once. Also test the Update on Pipeline page as well for Inline entities. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustom.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz4t0Q-U1yrPAdMf1a:-Nfz4t0Q-U1yrPAdMf1b:b-j8k19r) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustom.java#L42)):*
> ```Java
> 
>   Optional<Environment> findByAccountIdAndOrgIdentifierAndProjectIdentifierAndIdentifierAndDeletedNot(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String serviceIdentifier,
> ```

envIdentifier
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz6rS41YwI_TqO5LJl:-Nfz6rS54s9mWZ4QQvVF:bupzzsy) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L127)):*
> ```Java
>       Update update = EnvironmentFilterHelper.getUpdateOperations(environment);
>       RetryPolicy<Object> retryPolicy = getRetryPolicy(
>           "[Retrying]: Failed updating Environment; attempt: {}", "[Failed]: Failed updating Service; attempt: {}");
> ```

Environment here
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7Ed47GxL-SXO6BtX:-Nfz7Ed47GxL-SXO6BtY:b2ni214) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L245)):*
> ```Java
>       boolean notDeleted, boolean loadFromCache, boolean loadFromFallbackBranch, boolean getMetadataOnly) {
>     Query query = new Query(buildCriteriaForEnvironmentIdentifier(
>         accountIdentifier, orgIdentifier, projectIdentifier, serviceIdentifier, !notDeleted));
> ```

env
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 257 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7NBc-BOS8lgzkzXY:-Nfz7NBc-BOS8lgzkzXZ:bjwx2zo) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L257)):*
> ```Java
>     }
> 
>     if (savedEntity.getStoreType() == StoreType.REMOTE) {
> ```

let's create a separate method for getting remote YAMLs. We can re use that at other places. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 281 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7W-C3z0QRWqjx7dk:-Nfz7W-C3z0QRWqjx7dl:behtosu) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L281)):*
> ```Java
>             .filePath(savedEntity.getFilePath())
>             .repoName(savedEntity.getRepo())
>             .entityType(EntityType.SERVICE)
> ```

ENVIRONMENT
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 306 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7Zey4WN52EjIMZTw:-Nfz7Zey4WN52EjIMZTx:b1957pk) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L306)):*
> ```Java
>   }
> 
>   boolean shouldRetryWithFallBackBranch(ScmException scmException, String branchTried, String serviceFallbackBranch) {
> ```

env here
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 332 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7bHC7pEoQzfbromF:-Nfz7bHC7pEoQzfbromG:b2ni214) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L332)):*
> ```Java
>         .is(projectIdentifier)
>         .and(EnvironmentKeys.identifier)
>         .is(serviceIdentifier)
> ```

env

**Comment by senjucanon2** [comment]
trigger uts

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 5 file(s) to review. 1 change requests. 10. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz4YLaEyiIxZyZ7D99:-NfzIOW7EWdMs_cI1b5c:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/EnvironmentService.java#L34)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

"Environment" here
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 230 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz4jX76O-2OB2jO3vM:-NfzITRs816G2AGKi7A-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L230)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

environmentRef
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustom.java` line 42 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz4t0Q-U1yrPAdMf1a:-NfzIXDnEY1orI2FAgVX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustom.java#L42)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

envIdentifier
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 127 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz6rS41YwI_TqO5LJl:-NfzIaAYCOXIi-WZR_kK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L127)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Environment here
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 245 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7Ed47GxL-SXO6BtX:-NfzIcnX8dakDpoxWp7f:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L245)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

env
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 281 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7W-C3z0QRWqjx7dk:-NfzIhXrBNJaLdxCqTKp:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L281)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

ENVIRONMENT
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 306 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7Zey4WN52EjIMZTw:-NfzIjdx16bKCj1N2DtN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L306)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

env here
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 332 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7bHC7pEoQzfbromF:-NfzIkn5-YYSecXkPX_s:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L332)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

env
</blockquote></details>

Done.

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger ut8

**Review by hingerabhinav — DISMISSED** [review]
> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 271 at r6](https://reviewable.io/reviews/harness/harness-core/53635#-Ng-fyOrCZcUigHjP27I:-Ng-fyOrCZcUigHjP27J:b-gaazc1) ([raw file](https://github.com/harness/harness-core/blob/60060fd51fa96b80c1319310d551ed3250b9c048/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L271)):*
> ```Java
>                                             .withName(requestEnvironment.getName())
>                                             .withTags(requestEnvironment.getTags())
>                                             .withType(requestEnvironment.getType());
> ```

why this change is needed ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 8 files at r2, 1 of 2 files at r3, 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 215 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz5ZBA4earBVezqM4N:-NfzJqb9EMRW8Jg19r_B:b9zompy) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L215)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

This would bypass the non null check, better would be to call just get method which does that check.
</blockquote></details>

As this method had many usages, have added null check in this too.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 261 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz6LZsDs5tCdjaTdif:-NfzKtgF0GQVAHFnlNHi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L261)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

we should get metadata only here since YAML we're getting from UI.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 271 at r6](https://reviewable.io/reviews/harness/harness-core/53635#-Ng-fyOrCZcUigHjP27I:-Ng-gXCJ1_dqqQ_mpAVw:b-3txs3h) ([raw file](https://github.com/harness/harness-core/blob/60060fd51fa96b80c1319310d551ed3250b9c048/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L271)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

why this change is needed ?
</blockquote></details>

This prevents a GIT call to fetch yaml from remote, hence reducing the response time. We just get metadata from DB and use commitID and objectId to keep track of changes at remote. Then we set the updated value of yaml and other fields sent by UI.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java` line 257 at r4](https://reviewable.io/reviews/harness/harness-core/53635#-Nfz7NBc-BOS8lgzkzXY:-NfzKydD8OtOjQR9m4Ip:b-n2k55c) ([raw file](https://github.com/harness/harness-core/blob/2d4ae90c1173e312f6fbabdeaa95513cfb55d88b/127-cd-nextgen-entities/src/main/java/io/harness/repositories/environment/custom/EnvironmentRepositoryCustomImpl.java#L257)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

let's create a separate method for getting remote YAMLs. We can re use that at other places.
</blockquote></details>

I can do that in next PR ,lets merge this.

**Comment by senjucanon2** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53635)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
