### PR TITLE
[fix]: [PIE-1952]: Throwing relevant exceptions in create/update calls for InputSets

### PR DESCRIPTION
**Pull request by vtxorxwitty**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30192)

### CODE REVIEW

**Review by namanvermah — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30192#-:-MuOyu26EuJTXktYrIOL:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30192)* status: :shipit: complete! ✓

**Review by namanvermah — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30192#-:-Mvccm2u8p5W59amQp40:bnfp4nl)* status: 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30192#-:-MvqQnKS8dNx0IilCqS2:bnfp4nl)* status: Some of the checks are too old.

**Pull request merged**
