### PR TITLE
[feat]: [PL-27274]: fetch idpUrl from SamlSettings if empty or NULL

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
1. fetch idpUrl from SamlSettings if empty or NULL
2. while uploading/updating SamlSettings add full idpUrl rather than just the host
3. remove URI().getHost() while querying SamlSettings collection

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36687)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36687)

**Comment by kapil-harness** [comment]
trigger ti4

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36687)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36687)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/36687#-NAJIRSTCvd6wsntszQC:-NAJIRSTCvd6wsntszQD:b-nc1yy3) ([raw file](https://github.com/harness/harness-core/blob/56347d02be07834d395de3abcc9a4dc628e0327b/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L131)):*
> ```Java
>         SamlSettings samlSettings = ssoSettingService.getSamlSettingsByAccountId(accountId);
>         idpUrl = samlSettings.getOrigin();
>         if (!idpUrl.toLowerCase().matches(HTTPS_REGEX)) {
> ```

Minor possible NPE case if 'idpUrl' comes null. 



_Code quote:_
```Java
!idpUrl.toLowerCase()
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36687)* status: :shipit: complete! ✓

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36687)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 131 at r2](https://reviewable.io/reviews/harness/harness-core/36687#-NAJIRSTCvd6wsntszQC:-NAJLgYS9LmCKKGwzi3S:bd0kc6b) ([raw file](https://github.com/harness/harness-core/blob/56347d02be07834d395de3abcc9a4dc628e0327b/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L131)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Minor possible NPE case if 'idpUrl' comes null. 
</blockquote></details>

once we know idpUrl isEmpty() then idpUrl = samlSettings.getOrigin();
and origin cannot be null, so this case will not occur

code quote:
public class SamlSettings extends SSOSettings implements EncryptableSetting {
  @JsonIgnore @NotNull private String metaDataFile;
  @NotNull private String accountId;
  @NotNull private String origin;

**Review by kapil-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36687#-:-NAJN2dqB9QZZ1O4w72B:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
