### PR TITLE
[feat]: [CDS-69299]: Add execution mode in execution summary response

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47711)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47711)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47711)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
