### PR TITLE
feat: [IDP-1666]: Bug fix in harness datapoint parsers

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Bug fix in harness datapoint parsers

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55473)

### CODE REVIEW

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55473)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55473)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/harness/PipelineIsPolicyEvaluationSuccessfulParser.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/55473#-NjLx2r4EUDHqcO3csfE:-NjLx2r4EUDHqcO3csfF:b92rly5) ([raw file](https://github.com/harness/harness-core/blob/d3f52917764e311a87e9943e6242c19a9aa0ed52/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/harness/PipelineIsPolicyEvaluationSuccessfulParser.java#L22)):*
> ```Java
>   public Object parseDataPoint(Map<String, Object> data, DataFetchDTO dataFetchDTO) {
>     return Map.of(dataFetchDTO.getRuleIdentifier(),
>         ((Map<String, Object>) data.get(dataFetchDTO.getRuleIdentifier()))
> ```

Can we return the data directly? If it already has <ruleIdentifier, requriedData>

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55473)* status: 4 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/harness/PipelineIsPolicyEvaluationSuccessfulParser.java` line 22 at r1](https://reviewable.io/reviews/harness/harness-core/55473#-NjLx2r4EUDHqcO3csfE:-NjLyIwGA3IBiXHnT2hB:bpz0djn) ([raw file](https://github.com/harness/harness-core/blob/d3f52917764e311a87e9943e6242c19a9aa0ed52/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/harness/PipelineIsPolicyEvaluationSuccessfulParser.java#L22)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we return the data directly? If it already has <ruleIdentifier, requriedData>
</blockquote></details>

Never mind. Data is stored against the key dataFetchDTO.getDataPoint().getIdentifier()

**Comment by devesh-harness** [comment]
LGTM

**Review by devesh-harness — APPROVED** [review]

**Comment by sathish-soundarapandian** [comment]
trigger review

**Pull request merged**
