### PR TITLE
feat: [CDS-81257]: Template v1 Individual static schema parser 

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Template v1 Individual static schema parser

Tested with following templates for autosuggestions - 
* Http Step template
* Shell script template
* Custom stage template
* Deployment template
* Pipeline template

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-NhedVU-EWDJ12qeX7q5:-NhedVU-EWDJ12qeX7q6:b-fe09bw) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L93)):*
> ```Java
>   @Override
>   public ObjectNode getIndividualStaticSchema(String nodeGroup, String nodeType, String version) {
>     AbstractStaticSchemaParser templateSchemaParser = templateSchemaParserFactory.getTemplateSchemaParser("v1");
> ```

Why hardcoding the version?

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-Nhee-mH4AD6GR8H_LcF:-Nhee-mH4AD6GR8H_LcG:bsbpepd) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java#L26)):*
> ```Java
>   @Inject TemplateSchemaParserV1 templateSchemaParserV1;
>   private final String TEMPLATE_VERSION_V0 = "v0";
>   private final String TEMPLATE_VERSION_V1 = "v1";
> ```

Can we use the `PipelineVersionConstants` and rename that to YamlVersionConstants?
I am more inclined towards using the HarnessYamlVersion.V0 and HarnessYamlVersion.V1 only whose values are "0" and "1".  No need to have the new constant(PipelineVersionConstants) and mapping between these constants.

**Comment by brijeshdhakar** [comment]
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java` line 49 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-NheerSp5dh_t7RHRsUh:-NheerSp5dh_t7RHRsUi:bp8ior9) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java#L49)):*
> ```Java
>   static final String PIPELINE_TEMPLATE = "pipeline";
>   static final String STEPGROUP_TEMPLATE = "stepgroup";
>   static final String SECRET_MANAGER_TEMPLATE = "secretmanager";
> ```

We must have these constants somewhere else as well. Can you use those instead of creating new constants here?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java` line 93 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-NhedVU-EWDJ12qeX7q5:-Nhej1k10yjjOEZ119mT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/template/services/NGTemplateSchemaServiceImpl.java#L93)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Why hardcoding the version?
</blockquote></details>

Done.
___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-Nhee-mH4AD6GR8H_LcF:-Nhej2SD39bF3uBwHMKj:b-osxcd1) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java#L26)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Can we use the `PipelineVersionConstants` and rename that to YamlVersionConstants?
I am more inclined towards using the HarnessYamlVersion.V0 and HarnessYamlVersion.V1 only whose values are "0" and "1".  No need to have the new constant(PipelineVersionConstants) and mapping between these constants.
</blockquote></details>

PipelineVersionConstants this is inside pipeline service therefore Had created new ones
currently in all the APIs we v0/v1

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 4 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-Nhee-mH4AD6GR8H_LcF:-Nhejg8I5R0wdnw7EhuJ:b-qgm0zd) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java#L26)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

PipelineVersionConstants this is inside pipeline service therefore Had created new ones
currently in all the APIs we v0/v1
</blockquote></details>

@brijeshdhakar this I quarter we already have the plan to merge pipeline and template service, this can be done than

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-Nhee-mH4AD6GR8H_LcF:-NhfeSz67RFDb23K1r4x:bsowjnw) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java#L26)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

@brijeshdhakar this I quarter we already have the plan to merge pipeline and template service, this can be done than
</blockquote></details>

Cool. We can revisit using the HarnessYamlVersion constants itself instead of the new constants.(Values differs so it would be better to tackle it separately)
cc: @archit-harness 
___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java` line 108 at r5](https://reviewable.io/reviews/harness/harness-core/54433#-Nhfirrd0bEKncW1YFzd:-Nhfirrd0bEKncW1YFze:b-fqc7a4) ([raw file](https://github.com/harness/harness-core/blob/981112d9072d8a5223318e0b64a515599715a999/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java#L108)):*
> ```Java
>     finalSchema.remove(DEFINITIONS_NODE);
>     ObjectNode propertiesNode = rootSchemaJsonNode.get("properties").deepCopy();
>     propertiesNode.set(SPEC_NODE, individualSchemaNode.get(individualSchemaNode.fieldNames().next()));
> ```

Since we already have the  getSpecPath method. Can we use the individualSchemaNode.get(getSpecPath(nodeGroup)) instead of individualSchemaNode.get(individualSchemaNode.fieldNames().next())?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java` line 108 at r5](https://reviewable.io/reviews/harness/harness-core/54433#-Nhfirrd0bEKncW1YFzd:-NhfqcVc6zIw-zdTyRAw:ba6uso3) ([raw file](https://github.com/harness/harness-core/blob/981112d9072d8a5223318e0b64a515599715a999/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java#L108)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Since we already have the  getSpecPath method. Can we use the individualSchemaNode.get(getSpecPath(nodeGroup)) instead of individualSchemaNode.get(individualSchemaNode.fieldNames().next())?
</blockquote></details>

Done.
this is other level spec, that was inner spec

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java` line 232 at r5](https://reviewable.io/reviews/harness/harness-core/54433#-NhgI_3P9CgqYts1DXGV:-NhgI_3P9CgqYts1DXGW:b3hftlj) ([raw file](https://github.com/harness/harness-core/blob/981112d9072d8a5223318e0b64a515599715a999/953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java#L232)):*
> ```Java
>           jsonNode = jsonNode.get(Integer.parseInt(pathComponents[i]));
>         } catch (NumberFormatException ex) {
>           log.warn("Unable to convert to INT", ex);
> ```

wouldnt this will come a lot of time? as you are ignoring and returning null
___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/54433#-Nhee-mH4AD6GR8H_LcF:-NhgIis_5wzx-Dazvvno:bg0zqe7) ([raw file](https://github.com/harness/harness-core/blob/f6e5188c5b82ef953d2b36b4b722b516ec6bc3b7/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserFactory.java#L26)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

Cool. We can revisit using the HarnessYamlVersion constants itself instead of the new constants.(Values differs so it would be better to tackle it separately)
cc: @archit-harness
</blockquote></details>

yes use common constants for v1 and not rely on merging
___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java` line 116 at r5](https://reviewable.io/reviews/harness/harness-core/54433#-NhgIphn-bSC2orcSW_5:-NhgIphn-bSC2orcSW_6:b-un29yg) ([raw file](https://github.com/harness/harness-core/blob/981112d9072d8a5223318e0b64a515599715a999/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java#L116)):*
> ```Java
>     // using if-else over switch-case as we need to pass constant value in case.
>     if (TemplateEntityType.STEP_TEMPLATE.getNodeGroup().equals(nodeGroup)) {
>       return String.format(SPEC_PATH, "StepTemplate");
> ```

why we are not using exisitng const for this?

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java` line 232 at r5](https://reviewable.io/reviews/harness/harness-core/54433#-NhgI_3P9CgqYts1DXGV:-Nhgy5DL0uDVhjAD6EBC:b-lqjs3k) ([raw file](https://github.com/harness/harness-core/blob/981112d9072d8a5223318e0b64a515599715a999/953-yaml-commons/src/main/java/io/harness/yaml/utils/JsonPipelineUtils.java#L232)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

wouldnt this will come a lot of time? as you are ignoring and returning null
</blockquote></details>

This will come only when we expect an index for the arrayNode but the path component can not be converted to integer. In that case the value would be null only because nothing exists at the given path. 
Earlier also. null was being returned anyhow. only thing is that now we are handling the index as well in case of arrayNode(Earlier it was null)

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54433)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java` line 116 at r5](https://reviewable.io/reviews/harness/harness-core/54433#-NhgIphn-bSC2orcSW_5:-Nhja0z59kqttVhoX1RY:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/981112d9072d8a5223318e0b64a515599715a999/template-service/service/src/main/java/io/harness/yaml/individualschema/TemplateSchemaParserV1.java#L116)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we are not using exisitng const for this?
</blockquote></details>

done

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by vtxorxwitty — APPROVED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
