### PR TITLE
fix: [DEL-3491]: Make watcher logic of watching delegate process synchronous

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31366)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 510 at r1](https://reviewable.io/reviews/harness/harness-core/31366#-Mxpjdyy2ke15IQ9s8AN:-Mxpjdyy2ke15IQ9s8AO:buwgotv) ([raw file](https://github.com/harness/harness-core/blob/9ab9e2497bbcfe12b0868773e2a84ab88552dc26/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L510)):*
> ```Java
>       try {
>         if (!working.get()) {
>           HTimeLimiter.callInterruptible21(watcherTimeLimter, ofMinutes(10), () -> watchDelegate());
> ```

don't think we should do this, rather just make sure that there is no indefinite waiting anywhere in the logic

**Comment by raghuAtWings** [comment]
___
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 517 at r1](https://reviewable.io/reviews/harness/harness-core/31366#-MxpjmWf7IYIaRO0HrbH:-MxpjmWgEQHaOM7NR_Vj:b-9qawr7) ([raw file](https://github.com/harness/harness-core/blob/9ab9e2497bbcfe12b0868773e2a84ab88552dc26/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L517)):*
> ```Java
>         log.error("Error watching delegate process", e);
>       } finally {
>         watchExecutor.schedule(
> ```

don't understand why do we need this schedule call

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31366)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 507 at r1](https://reviewable.io/reviews/harness/harness-core/31366#-MxrD_lS-6ZE6IIF753F:-MxrD_lS-6ZE6IIF753G:b7ghtd7) ([raw file](https://github.com/harness/harness-core/blob/9ab9e2497bbcfe12b0868773e2a84ab88552dc26/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L507)):*
> ```Java
>   private void syncWatchDelegate() {
>     synchronized (this) {
>       log.info("calling watcher scheduler");
> ```

Plz ignore this, for local testing
___
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 510 at r1](https://reviewable.io/reviews/harness/harness-core/31366#-Mxpjdyy2ke15IQ9s8AN:-MxrDeqeAZefpgo_bTEV:bpk03s6) ([raw file](https://github.com/harness/harness-core/blob/9ab9e2497bbcfe12b0868773e2a84ab88552dc26/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L510)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't think we should do this, rather just make sure that there is no indefinite waiting anywhere in the logic
</blockquote></details>

Not just wait, we are also doing couple of system calls, which might also result in wait internally. So IMO better to have time bound on entire method.
___
*[960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, line 517 at r1](https://reviewable.io/reviews/harness/harness-core/31366#-MxpjmWf7IYIaRO0HrbH:-MxrEBzLD2fI5cX1ffMu:b24x9tt) ([raw file](https://github.com/harness/harness-core/blob/9ab9e2497bbcfe12b0868773e2a84ab88552dc26/960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java#L517)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

don't understand why do we need this schedule call
</blockquote></details>

If 'watchDelegate' took around 10 mins to finish, previously, 'scheduleWithFixedDelay' will end up scheduling 60 executions (10 * 60 / 10 (frequency)), which are useless since we know nothing will change till delegate process gets started. 
Hence this will make sure to start the scheduling only after we start the delegate process.

**Comment by gaurav-jain1** [comment]
This fix is no longer needed

**Pull request closed without merging**
