### PR TITLE
[feat]: [CDS-69835]: Added Default branch cache document

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have added a new document which will be used for storing default branch details.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48802)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchCache.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/48802#-NXKIN6SBnetwZnNdVY_:-NXKIN6T2C90pv6UxStR:byf15iu) ([raw file](https://github.com/harness/harness-core/blob/a70fcb6d60d33479c2681ed48ed229228b61ee97/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchCache.java#L56)):*
> ```Java
>   String repoUrl;
>   GitDefaultBranchObject gitDefaultBranchObject;
>   long createdAt;
> ```

@archit-harness there was some recommendation on timestamp field right whether it should be Long or long?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchObject.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/48802#-NXKIUtm9q6QdNaFyybZ:-NXKIUtm9q6QdNaFyyb_:b-rixn40) ([raw file](https://github.com/harness/harness-core/blob/a70fcb6d60d33479c2681ed48ed229228b61ee97/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchObject.java#L27)):*
> ```Java
> @TypeAlias("io.harness.gitsync.caching.entity.gitDefaultBranchObject")
> @OwnedBy(PIPELINE)
> public class GitDefaultBranchObject {
> ```

why separate object?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48802)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchCache.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/48802#-NXKIN6SBnetwZnNdVY_:-NXKMRhMDL7fUsb1op4E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a70fcb6d60d33479c2681ed48ed229228b61ee97/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchCache.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@archit-harness there was some recommendation on timestamp field right whether it should be Long or long?
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchObject.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/48802#-NXKIUtm9q6QdNaFyybZ:-NXKJuw39TEAg3j1RjGy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a70fcb6d60d33479c2681ed48ed229228b61ee97/136-git-sync-manager/src/main/java/io/harness/gitsync/caching/entity/GitDefaultBranchObject.java#L27)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why separate object?
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48802)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
