### PR TITLE
[fix]: [CDS-71032]: Rollback not working on Approval rejection

### PR DESCRIPTION
**Pull request by vtxorxwitty**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)

### CODE REVIEW

**Comment by vtxorxwitty** [comment]
trigger messagecheck

**Comment by vtxorxwitty** [comment]
trigger ut0

**Comment by rohitk-h** [comment]
@vtxorxwitty can you add a description comment about the change and reason of the issue. Thanks! cc @archit-harness

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 715 at r1](https://reviewable.io/reviews/harness/harness-core/48823#-NXDlN7zD7fP6U0g6O8_:-NXDlN7zD7fP6U0g6O8a:bg7dnr9) ([raw file](https://github.com/harness/harness-core/blob/e6087ea9bf96d1e1ee2dcbeedfc37c5e7d09a8a1/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L715)):*
> ```Java
>         "<+stage.currentStatus> == \"FAILED\" || <+stage.currentStatus> == \"ERRORED\" || <+stage.currentStatus> == \"EXPIRED\" || <+stage.currentStatus> == \"APPROVAL_REJECTED\"");
>     aliases.put(OrchestrationConstants.PIPELINE_FAILURE,
>         "<+pipeline.currentStatus> == \"FAILED\" || <+pipeline.currentStatus> == \"ERRORED\" || <+pipeline.currentStatus> == \"EXPIRED\"");
> ```

add to pipeline status as well

Plus don't merge until automation for this is created as well

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 715 at r1](https://reviewable.io/reviews/harness/harness-core/48823#-NXDlN7zD7fP6U0g6O8_:-NXFOABUEbJW6vm6EUQ8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e6087ea9bf96d1e1ee2dcbeedfc37c5e7d09a8a1/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L715)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add to pipeline status as well

Plus don't merge until automation for this is created as well
</blockquote></details>

done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 715 at r2](https://reviewable.io/reviews/harness/harness-core/48823#-NXFP8XtBATu3dnYvxsv:-NXFP8XuDJGK2s4Eh-vC:bvlrphp) ([raw file](https://github.com/harness/harness-core/blob/498cd076024cbaa0371f37c546a8bd74f5f1fbc7/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L715)):*
> ```Java
>         "<+stage.currentStatus> == \"FAILED\" || <+stage.currentStatus> == \"ERRORED\" || <+stage.currentStatus> == \"EXPIRED\" || <+stage.currentStatus> == \"APPROVAL_REJECTED\"");
>     aliases.put(OrchestrationConstants.PIPELINE_FAILURE,
>         "<+pipeline.currentStatus> == \"FAILED\" || <+pipeline.currentStatus> == \"ERRORED\" || <+pipeline.currentStatus> == \"EXPIRED\" || <+stage.currentStatus> == \"APPROVAL_REJECTED\"");
> ```

I think you meant pipeline here?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by vtxorxwitty** [comment]
trigger uts

**Comment by vtxorxwitty** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java` line 715 at r2](https://reviewable.io/reviews/harness/harness-core/48823#-NXFP8XtBATu3dnYvxsv:-NXFW-Ax2m6X6dVmS9S0:bd30ifx) ([raw file](https://github.com/harness/harness-core/blob/498cd076024cbaa0371f37c546a8bd74f5f1fbc7/pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java#L715)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think you meant pipeline here?
</blockquote></details>

good catch

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)* status: 1 change requests. 1. unresolved discussions.

**Comment by vtxorxwitty** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48823)* status: :shipit: complete! ✓

**Pull request merged**
