### PR TITLE
fix: [SRM-12138] added to authorList and introduced RiskCategory entity and resource.

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37896)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37896)

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37896)* status: 13 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/RiskProfile.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8HNAT55XVsKYGkcKS:-ND8HNAT55XVsKYGkcKT:bvb67hm) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/RiskProfile.java#L25)):*
> ```Java
> @Builder
> public class RiskProfile {
>     @Getter(AccessLevel.NONE)
> ```

We dont need to add @Getter here. The code overrides the annotations automatically.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/RiskCategoryDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8JGG583j0SjhaB6Dp:-ND8JGG583j0SjhaB6Dq:bjn5t3b) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/RiskCategoryDTO.java#L26)):*
> ```Java
> @JsonIgnoreProperties(ignoreUnknown = true)
> public class RiskCategoryDTO implements YamlDTO {
>     RiskCategory riskCategoryIdentifier;
> ```

By convention, we use "identifier" in DTO.
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8IvI-4dAScuCVbvJG:-ND8IvI-4dAScuCVbvJH:b-4jb11t) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java#L51)):*
> ```Java
>   String MONITORED_SERVICE_YAML_ROOT = "monitoredService";
> 
>    String PERFORMANCE_RESPONSE_TIME_IDENTIFIER = "Performance_Response_Time";
> ```

you dont need to keep it here, as it might not be used any other place. You use string directly in @JsonProperty. If keeping here make it more obvious ERFORMANCE_RESPONSE_TIME_RISK_CATEGORY_IDENTIFIER



_Code quote:_
```Java
ERFORMANCE_RESPONSE_TIME_IDENTIFIER
```

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37896)* status: 13 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @AbhijithHarness)

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/RiskProfile.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8HNAT55XVsKYGkcKS:-ND8iect9F6Pl1hEc-AU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/RiskProfile.java#L25)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We dont need to add @Getter here. The code overrides the annotations automatically.
</blockquote></details>

Done.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/RiskCategoryDTO.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8JGG583j0SjhaB6Dp:-ND8iiu-ErsvwUAfeinH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/monitoredService/RiskCategoryDTO.java#L26)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

By convention, we use "identifier" in DTO.
</blockquote></details>

Done.
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8ILuU4zt5AJnp_Qkt:-ND8ikfkCKICvQz7T5qb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java#L51)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Performance_ResponseTime
</blockquote></details>

Done.
___
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/37896#-ND8IvI-4dAScuCVbvJG:-ND8il3D45MTMgHKRgOX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/41714aa3361383dfb90f3d17724861c269c8d8bb/948-cv-nextgen-beans/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java#L51)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

you dont need to keep it here, as it might not be used any other place. You use string directly in @JsonProperty. If keeping here make it more obvious ERFORMANCE_RESPONSE_TIME_RISK_CATEGORY_IDENTIFIER
</blockquote></details>

Done.

**Comment by n00bitax** [comment]
trigger authorcheck

**Review by AbhijithHarness — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, 5 of 10 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37896)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.  (waiting on @AbhijithHarness)

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37896)* status: :shipit: complete! ✓

**Pull request merged**
