### PR TITLE
fix: [CDS-79817]: Add handling for casting string value to enum in parameterField

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Add handling for casting string value to enum in the parameter field.

**Testing:** Tested the user scenario locally where their enum value was getting converted to string in step parameters in the plugin step. Also added unit tests.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53176)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53176)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/53176#-Nf9ZSI56dYTVC4K-oj2:-Nf9ZSI56dYTVC4K-oj3:bazjej) ([raw file](https://github.com/harness/harness-core/blob/139353be80c924d6e15e14f39b0be55925daa100/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java#L35)):*
> ```Java
>       if ((ClassUtils.isPrimitiveOrWrapper(fieldClass) || fieldClass.equals(Timeout.class) || fieldClass.isEnum())
>           && !fieldClass.isAssignableFrom(finalValue.getClass())) {
>         if (fieldClass.equals(Integer.class)) {
> ```

Please convert this to switch case
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/53176#-Nf9ZV3DEwxehHa8aVu-:-Nf9ZV3DEwxehHa8aVu0:b-d0zbz5) ([raw file](https://github.com/harness/harness-core/blob/139353be80c924d6e15e14f39b0be55925daa100/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java#L68)):*
> ```Java
>   }
> 
>   private Object getDoubleValue(Object finalValue) {
> ```

convert this and below to switch case
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/53176#-Nf9ZeVG0f5taTOls6ic:-Nf9ZeVG0f5taTOls6id:btkb32g) ([raw file](https://github.com/harness/harness-core/blob/139353be80c924d6e15e14f39b0be55925daa100/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java#L95)):*
> ```Java
> 
>   private Object getEnumValue(Object finalValue, Class<?> fieldClass) {
>     if (finalValue.getClass().equals(String.class)) {
> ```

i think here we should use .toString() on object just like EnumRecastTransformer and use Enum.valueOf(targetClass, fromDBObject.toString());

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53176)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/53176#-Nf9ZSI56dYTVC4K-oj2:-Nf9c35O-cu76a9VNh5V:bg0foff) ([raw file](https://github.com/harness/harness-core/blob/139353be80c924d6e15e14f39b0be55925daa100/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Please convert this to switch case
</blockquote></details>

in the switch case we can only have 'char, byte, short, int, Character, Byte, Short, Integer, String, or an enum' in switch(), Class<?> is not allowed
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java` line 68 at r2](https://reviewable.io/reviews/harness/harness-core/53176#-Nf9ZV3DEwxehHa8aVu-:-Nf9cFbyD_3HnOMv2k81:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/139353be80c924d6e15e14f39b0be55925daa100/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java#L68)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

convert this and below to switch case
</blockquote></details>

same as above
___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/53176#-Nf9ZeVG0f5taTOls6ic:-Nf9cIz8-Y2epFAkwh9p:b-6g2i44) ([raw file](https://github.com/harness/harness-core/blob/139353be80c924d6e15e14f39b0be55925daa100/953-yaml-commons/src/main/java/io/harness/pms/yaml/ParameterFieldUtils.java#L95)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think here we should use .toString() on object just like EnumRecastTransformer and use Enum.valueOf(targetClass, fromDBObject.toString());
</blockquote></details>

if we do that it will only convert the strings that match the exact case defined in the enum class. For eg: if the enum class has an enum ALWAYS, then if given a string 'Always' it won't be converted to an enum. This is the case for the CD plugin step as reported by Tudor, so, this needs to be handled

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53176)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53176)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
