### PR TITLE
fix: [CDS-39386]: moving aggregate and read queries for CG dashboard and instance stats related collections to secondary node

### PR DESCRIPTION
**Pull request by shubham-in10se**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37919)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/37919#-NCxSuUz2pZCyf6PUpOl:-NCxSuUz2pZCyf6PUpOm:b3n7dit) ([raw file](https://github.com/harness/harness-core/blob/441b8f0dde43a24cd168858981b7187e422bc258/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L112)):*
> ```Java
>                .orElseGet(() -> DEFAULT_STORE));
> 
>     // only if the request is for cg db, get from analytics node
> ```

the comment says that it already was working for cg db, but according to the new change, it was not ( that is why we had to add the second condition here). Am I correct here ?

**Review by shubham-in10se — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37919)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/37919#-NCxSuUz2pZCyf6PUpOl:-NCxUNW24zc4SwaBD-zy:b-6k44am) ([raw file](https://github.com/harness/harness-core/blob/441b8f0dde43a24cd168858981b7187e422bc258/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L112)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

the comment says that it already was working for cg db, but according to the new change, it was not ( that is why we had to add the second condition here). Am I correct here ?
</blockquote></details>

recently the CG Entity classes were also annotated with the `@StoreIn` annotation. The existing logic here was assuming that none of the CG entities are annotated with that, which was causing it to pick the primary DB only, for entities residing in mongo CG DB. Hence the change.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37919)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37919)* status: :shipit: complete! ✓

**Pull request merged**
