### PR TITLE
[feat]: [PL-42032] : Create, delete, Get, update org service using ScopeInfo

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Handle CREATE, DELETE, RESTORE, GET and UPDATE Org service operation using ScopeInfo from request Context. The ScopeInfo has parentId and ScopeLevel details.

Testing scenario:

- Tested for Org create scenario
- Tested for Org Delete scenario
- Tested for Org Update scenario
- Tested for Org Get, and Aggregate Org Get

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56381)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger checkstylecodeformat

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 29 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56381)* status: 30 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/AggregateOrganizationService.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1LCAD9dH5YtozjIih:-Nl1LCAD9dH5YtozjIii:bwushlu) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/api/AggregateOrganizationService.java#L24)):*
> ```Java
>   OrganizationAggregateDTO getOrganizationAggregateDTO(String accountIdentifier, ScopeInfo scopeInfo, String identifier);
> 
>   Page<OrganizationAggregateDTO> listOrganizationAggregateDTO(
> ```

No change needed in this method?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1OyV34GM3wT6XFHiC:-Nl1OyV34GM3wT6XFHiD:b-i1ja18) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L143)):*
> ```Java
>       setupOrganization(Scope.of(accountIdentifier, savedOrganization.getIdentifier(), null));
>       log.info(String.format(
>           "Scope- [accountIdentifier: %s]. Organization with identifier [%s] and uniqueId [%s] successfully created",
> ```

We probably don't need Scope- [accountIdentifier: %s] in the log messages from this class as its implicit.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 460 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1Olrf-QsqoQbm-2ZV:-Nl1Olrf-QsqoQbm-2ZW:b-2qxyv1) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L460)):*
> ```Java
>       return Optional.of(scopeInfoCache.get(cacheKey));
>     }
>     Optional<Organization> org = getConsideringCase(accountIdentifier, orgIdentifier);
> ```

Whats this change?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 783 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1LY2-6yzp1XAM64bD:-Nl1LY2-6yzp1XAM64bE:b-2qxyv1) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L783)):*
> ```Java
>       return Optional.of(scopeInfoCache.get(cacheKey));
>     }
>     Optional<Project> project = getConsideringCase(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

Whats this change?
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 105 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1MLnKENN78sTKI8pG:-Nl1MLnKENN78sTKI8pH:b851uhm) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L105)):*
> ```Java
>                      Collation.builder().locale(CollationLocale.ENGLISH).strength(CollationStrength.PRIMARY).build())
>                  .build())
>         .add(CompoundMongoIndex.builder()
> ```

This index is redundant if we are creating accountIdentifierParentIdIdentifierDeletedIdx
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/OrganizationService.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1NSAA-JvKJ73nuZVo:-Nl1NSAB9WvBf1k8QfuN:bejljb4) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/OrganizationService.java#L63)):*
> ```Java
>   Long countOrgs(String accountIdentifier);
> 
>   Set<String> getPermittedOrganizations(@NotNull String accountIdentifier, String orgIdentifier);
> ```

Should this method and other remaining methods in OrganizationServiceImpl also have ScopeInfo

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 460 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1Olrf-QsqoQbm-2ZV:-Nl5BzpM3avZfQB35sdh:bfiimv0) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L460)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats this change?
</blockquote></details>

This was a change handled for case sensitive issue, which was reported by customer, thanks

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 783 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1LY2-6yzp1XAM64bD:-Nl5C6UrE8rOZSGnKdB1:b-4xngmk) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L783)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats this change?
</blockquote></details>

Same! This was reported in a CFD https://harness.atlassian.net/browse/PL-40897

**Comment by pbarapatre10** [comment]
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/OrganizationService.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1NSAA-JvKJ73nuZVo:-Nl5CLXwAHq_VFACpeKu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services/OrganizationService.java#L63)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this method and other remaining methods in OrganizationServiceImpl also have ScopeInfo
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r2, 9 of 9 files at r4, 4 of 4 files at r6, 1 of 1 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56381)* status: 37 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1OyV34GM3wT6XFHiC:-NlDF4vA6cGDa6MoB4Yo:b-njb2ka) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L143)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Its not yet removed it seems
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 119 at r9](https://reviewable.io/reviews/harness/harness-core/56381#-NlDFgWbBiYGR6ygU_0J:-NlDFgWbBiYGR6ygU_0K:brekaq3) ([raw file](https://github.com/harness/harness-core/blob/469b2f5f4c618612e09e34d94833fa1b174e5d0a/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L119)):*
> ```Java
>                  .build())
>         .add(CompoundMongoIndex.builder()
>                  .name("accountIdentifierParentUniqueIdIdentifierIdx")
> ```

This index is redundant if we are creating accountIdentifierParentUniqueIdIdentifierDeletedIdx
___
*[`965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java` line 52 at r9](https://reviewable.io/reviews/harness/harness-core/56381#-NlDG1h77ht4-P5Gr_Pp:-NlDG1h77ht4-P5Gr_Pq:b-t1b8tu) ([raw file](https://github.com/harness/harness-core/blob/469b2f5f4c618612e09e34d94833fa1b174e5d0a/965-ng-filter/src/main/java/io/harness/security/ScopeInfoFilter.java#L52)):*
> ```Java
> public class ScopeInfoFilter implements ContainerRequestFilter, ContainerResponseFilter {
>   private static final String SCOPE_INFO_FILTER_LOG = "SCOPE_INFO_FILTER: ";
>   public static final Set<String> matchingPathRequests =
> ```

/projects also should be added as I see changes in ProjectResource
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 380 at r9](https://reviewable.io/reviews/harness/harness-core/56381#-NlDEtGF1wCHd-V2Tl9C:-NlDEtGF1wCHd-V2Tl9D:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/469b2f5f4c618612e09e34d94833fa1b174e5d0a/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L380)):*
> ```Java
> 
>   @PATCH
>   @Hidden
> ```

Why this change?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-NlDF13SDj37L4BfH346:-NlDF13SDj37L4BfH347:biffa3a) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java#L49)):*
> ```Java
>       }
>     } else if (isEmpty(projectIdentifier)) {
>       return organizationService.get(accountIdentifier, ScopeInfo.builder().accountIdentifier(accountIdentifier).scopeType(ScopeLevel.ACCOUNT).uniqueId(accountIdentifier).build(), orgIdentifier).isPresent();
> ```

Why this revert?

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56381)* status: 37 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/AggregateOrganizationService.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1LCAD9dH5YtozjIih:-NlDLYY-2yFQfLSSUzDJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/api/AggregateOrganizationService.java#L24)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No change needed in this method?
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java` line 143 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-Nl1OyV34GM3wT6XFHiC:-NlDKgpE5dnMILlGMW8-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/impl/OrganizationServiceImpl.java#L143)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Its not yet removed it seems
</blockquote></details>

Done.
___
*[`950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java` line 119 at r9](https://reviewable.io/reviews/harness/harness-core/56381#-NlDFgWbBiYGR6ygU_0J:-NlDLV0SC-8873L-AS_w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/469b2f5f4c618612e09e34d94833fa1b174e5d0a/950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities/Organization.java#L119)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This index is redundant if we are creating accountIdentifierParentUniqueIdIdentifierDeletedIdx
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/56381#-NlDF13SDj37L4BfH346:-NlDLa2hE1u7bm07oSKQ:bx0dfj6) ([raw file](https://github.com/harness/harness-core/blob/ab554b3950c8dbb1e8d5c1d900205396c4f12b76/120-ng-manager/src/main/java/io/harness/ng/core/AccountOrgProjectValidator.java#L49)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this revert?
</blockquote></details>

This is the actual ScopeInfoResolver part which uses the user identifiers to resolve Scope, so we won't take ScopeInfo here as input, thanks

**Comment by pbarapatre10** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 380 at r9](https://reviewable.io/reviews/harness/harness-core/56381#-NlDEtGF1wCHd-V2Tl9C:-NlDMV0EEC0hpOriXJ0R:b-e780r7) ([raw file](https://github.com/harness/harness-core/blob/469b2f5f4c618612e09e34d94833fa1b174e5d0a/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L380)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

This is because `PipelineServiceComponentTest` is failing even in develop, so fixing it

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56381#-:-NlD_-YN8jgD5C1e4Uju:bnfp4nl)* status: 37 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56381#-:-NlD_1DM4bmGrbUxtcDq:bnfp4nl)* status: 37 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56381)* status: 37 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger uts

**Review by sahibaHarness — APPROVED** [review]

**Pull request merged**
