### PR TITLE
feat: [PL-22401]:  Added Account Setting Resources

### PR DESCRIPTION
**Pull request by meenakshi-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)

### CODE REVIEW

**Comment by shashank-harness** [comment]
___
*[950-ng-core/src/main/java/io/harness/repositories/accountsetting/AccountSettingRepository.java, line 16 at r3](https://reviewable.io/reviews/harness/harness-core/30487#-Mv2C17d0FamemSDlNt1:-Mv2C17d0FamemSDlNt2:bxc05vs) ([raw file](https://github.com/harness/harness-core/blob/9d4c444eebac77ac53802932b7fe026a164429a8/950-ng-core/src/main/java/io/harness/repositories/accountsetting/AccountSettingRepository.java#L16)):*
> ```Java
> 
> @HarnessRepo
> public interface AccountSettingRepository extends Repository<AccountSettings, String>, AccountSettingCustomRepository {}
> ```

Extend CrudRepository as discussed

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 28 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/repositories/accountsetting/AccountSettingRepository.java, line 16 at r3](https://reviewable.io/reviews/harness/harness-core/30487#-Mv2C17d0FamemSDlNt1:-Mv8KNKi7ki0uy96WYbF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9d4c444eebac77ac53802932b7fe026a164429a8/950-ng-core/src/main/java/io/harness/repositories/accountsetting/AccountSettingRepository.java#L16)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Extend CrudRepository as discussed
</blockquote></details>

Done.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 29 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/BUILD.bazel, line 34 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTT-SB0xrT_fNAtBMn:-MvTT-SCAM4xncNljXpx:bgh0wrg) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/BUILD.bazel#L34)):*
> ```Starlark
>     "//947-scim-core:module",
>     "//948-access-control-admin-client:module",
>     "//950-ng-core:module",
> ```

This would already be an indirect dependancy. Do we really need to add this?
___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/AccountSettingType.java, line 38 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTY1vj3ESt5BDL-rGN:-MvTY1vk4blFeu-SRIVk:b-lbf1oi) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/AccountSettingType.java#L38)):*
> ```Java
>     this.supplier = supplier;
>   }
>   public AccountSettingConfig getInstance() {
> ```

Method name `getInstance` is too generic. Can we rename it to `getSettingConfig`?
___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java, line 42 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTZ2da-GSkrCXA1ZK5:-MvTZ2da-GSkrCXA1ZK6:b-stxs0k) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java#L42)):*
> ```Java
>       updatedAccountSetting = accountSettingRepository.updateAccountSetting(accountSettings, accountIdentifier);
>     } catch (Exception ex) {
>       throw new NotFoundException(
> ```

Throwing NotFoundException in case of any exception caught can be misleading. Have separate catch blocks for different type of exception.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvT_HRQDUcY2by5Q-TA:-MvT_HRQDUcY2by5Q-TB:bklra9n) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java#L89)):*
> ```Java
>       @NotNull @QueryParam(TYPE_KEY) AccountSettingType type) {
>     return ResponseDTO.newResponse(
>         accountSettingService.get(accountIdentifier, orgIdentifier, projectIdentifier, type));
> ```

Should we throw exception when not found?

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 29 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/BUILD.bazel, line 34 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTT-SB0xrT_fNAtBMn:-MvTuPuQ-7SYJ3wS5pim:bdrlpq1) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/BUILD.bazel#L34)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This would already be an indirect dependancy. Do we really need to add this?
</blockquote></details>

Yes I got a error while restarting NG App. Hence added this.
___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/AccountSettingType.java, line 38 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTY1vj3ESt5BDL-rGN:-MvTv0Fh7pWI8hXKEfyw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/AccountSettingType.java#L38)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Method name `getInstance` is too generic. Can we rename it to `getSettingConfig`?
</blockquote></details>

Done.
___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java, line 42 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTZ2da-GSkrCXA1ZK5:-MvTv14P2JOUTAjstmUZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Throwing NotFoundException in case of any exception caught can be misleading. Have separate catch blocks for different type of exception.
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvT_HRQDUcY2by5Q-TA:-MvTuZ9BCFxJSWHjmIwq:bcuibbc) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java#L89)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should we throw exception when not found?
</blockquote></details>

Already added at Service layer.

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Comment by meenakshi-harness** [comment]
trigger messagecheck

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 29 file(s) to review. 1 change requests. 4. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 29 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java, line 42 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTZ2da-GSkrCXA1ZK5:-MvWswLZ9MjXwhixuajt:brgsjgu) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java#L42)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The original cause is suppressed. Can we just log it and then throw InvalidRequestException.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvT_HRQDUcY2by5Q-TA:-MvWtffk9Y-7BnjA5HHo:bl44hdi) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java#L89)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Already added at Service layer.
</blockquote></details>

`get` method in `NGAccountSettingService` doesn't address this.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 29 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java, line 42 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvTZ2da-GSkrCXA1ZK5:-MvXMzxc2yMskzn_HCD8:b-atmo01) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services/NGAccountSettingServiceImpl.java#L42)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

The original cause is suppressed. Can we just log it and then throw InvalidRequestException.
</blockquote></details>

Instead of logging I added the original exception in Invalid exception itself. Let me know if that works.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvT_HRQDUcY2by5Q-TA:-MvXNH-s4wQHuKK0FwO8:b-9co4q2) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java#L89)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

`get` method in `NGAccountSettingService` doesn't address this.
</blockquote></details>

Have thrown from Repository. Do we again need to catch and re-throw at service?

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 6 of 22 files at r2, 5 of 16 files at r3, 3 of 10 files at r4, 12 of 15 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 29 file(s) to review. 1 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java, line 89 at r5](https://reviewable.io/reviews/harness/harness-core/30487#-MvT_HRQDUcY2by5Q-TA:-MvXSHiVDeCmI7gw6R7L:b-6v65iw) ([raw file](https://github.com/harness/harness-core/blob/93880424123a906605700c841ee228c524b44345/120-ng-manager/src/main/java/io/harness/ng/core/accountsetting/resources/AccountSettingResource.java#L89)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

Have thrown from Repository. Do we again need to catch and re-throw at service?
</blockquote></details>

No. This is fine.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 22 files at r2, 4 of 16 files at r3, 3 of 10 files at r4, 12 of 15 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 6 file(s) to review.

**Comment by shashank-harness** [comment]
:lgtm:

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487)* status: 6 file(s) to review.

**Comment by shashank-harness** [comment]
:lgtm:

**Review by shashank-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 22 files at r2, 1 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30487#-:-MvY71151sQL3hwVyVkV:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
