### PR TITLE
techdebt: [PIE-2745]: Added Mongo Offset Backing store

### PR DESCRIPTION
**Pull request by shalini-agr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger messagecheck

**Review by hextechpal — CHANGES_REQUESTED** [review]
Add tests

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092#-:-Mx3Z_pPDTO0fW0CIxk8:b-5i6aoz)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java, line 41 at r2](https://reviewable.io/reviews/harness/harness-core/31092#-Mx986zX1eBaYJCQix0f:-Mx986zZAurTVEE_yCk3:bezo0z0) ([raw file](https://github.com/harness/harness-core/blob/a327c8e4b11726117f33eb49e472fb8e3a3c0dee/958-debezium-engine/src/main/java/io/harness/debezium/DebeziumConfiguration.java#L41)):*
> ```Java
>   public Properties getDebeziumProperties(DebeziumConfig debeziumConfig) {
>     Properties props = new Properties();
>     String offsetCollection = "debeziumOffset";
> ```

nit, use DebeziumOffset class static field instead of duplicating

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 34 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEG9QJ59lfz-ofDk0e:-MxEG9QJ59lfz-ofDk0f:b-l6ste1) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L34)):*
> ```Java
>   private String collectionName;
>   private boolean foundOffsets;
>   private boolean savedOffset;
> ```

don't add fields for tests
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 36 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGJNv6y33_oyvQQoW:-MxEGJNv6y33_oyvQQoX:b8h4lmc) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L36)):*
> ```Java
>   private boolean savedOffset;
> 
>   public void setCollectionName(String collectionName) {
> ```

Use Data/Value Lombok annotation, no need to write getters/setters yourself
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 72 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGXpB-n7MtQfKtQnw:-MxEGXpB-n7MtQfKtQnx:b-eneqdl) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L72)):*
> ```Java
>     mongoClient = new MongoClient(uri);
>     mongoTemplate = new MongoTemplate(mongoClient, Objects.requireNonNull(uri.getDatabase()));
>     this.data = new HashMap<>();
> ```

is this done for UT? if yes, then remove. We can directly set in UT
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 83 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGcMd3ijtDT_Xq5-s:-MxEGcMd3ijtDT_Xq5-t:b-107rb8) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L83)):*
> ```Java
> 
>   @VisibleForTesting
>   public void load() {
> ```

make package private
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 113 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGf3R5g_t0a6prTbm:-MxEGf3R5g_t0a6prTbn:b7i3dxz) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L113)):*
> ```Java
>   @Override
>   @VisibleForTesting
>   public void save() {
> ```

package-private
___
*[958-debezium-engine/src/test/java/io/harness/debezium/DebeziumConfigurationTest.java, line 13 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGoR82vhh9kMc-YeC:-MxEGoR82vhh9kMc-YeD:b-dihtos) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/test/java/io/harness/debezium/DebeziumConfigurationTest.java#L13)):*
> ```Java
> 
> public class DebeziumConfigurationTest {
>   private static final String MONGO_DB_CONNECTOR = "io.debezium.connector.mongodb.MongoDbConnector";
> ```

you can directly use these constants from debeziumConfiguratiion class, no need to re-write here
___
*[958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java, line 27 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEHfEj7OOxB-z_l3Jt:-MxEHfEj7OOxB-z_l3Ju:b-xo7fj) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java#L27)):*
> ```Java
> 
>   @Test
>   @Owner(developers = PRASHANT)
> ```

write your name :P as owner
___
*[958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java, line 31 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEHVqx3r-oiJKXMMmp:-MxEHVqx3r-oiJKXMMmq:bd5eg6m) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java#L31)):*
> ```Java
>   public void testLoad() {
>     MockitoAnnotations.initMocks(this);
>     mongoOffsetBackingStore.setCollectionName(collectionName);
> ```

nit, you can use constructor for these initilizations

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: 8 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 34 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEG9QJ59lfz-ofDk0e:-MxEcUge0Nm25YFDm6E-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L34)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

don't add fields for tests
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 36 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGJNv6y33_oyvQQoW:-MxEcVv1BqEu8qHdmdED:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L36)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Use Data/Value Lombok annotation, no need to write getters/setters yourself
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 72 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGXpB-n7MtQfKtQnw:-MxEcWtHC0fWWKcBp9E5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L72)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

is this done for UT? if yes, then remove. We can directly set in UT
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 83 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGcMd3ijtDT_Xq5-s:-MxEcXgaD0uMOyVrZMZC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L83)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

make package private
</blockquote></details>

Done.
___
*[958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java, line 113 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGf3R5g_t0a6prTbm:-MxEcYKD-cl-2x2uhbTa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/main/java/io/harness/debezium/MongoOffsetBackingStore.java#L113)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

package-private
</blockquote></details>

Done.
___
*[958-debezium-engine/src/test/java/io/harness/debezium/DebeziumConfigurationTest.java, line 13 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEGoR82vhh9kMc-YeC:-MxEcZcY0YmToN1WcdiA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/test/java/io/harness/debezium/DebeziumConfigurationTest.java#L13)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

you can directly use these constants from debeziumConfiguratiion class, no need to re-write here
</blockquote></details>

Done.
___
*[958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java, line 27 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEHfEj7OOxB-z_l3Jt:-MxEc_MA25a2T_J9rGFA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java#L27)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

write your name :P as owner
</blockquote></details>

Done.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java, line 27 at r4](https://reviewable.io/reviews/harness/harness-core/31092#-MxEHfEj7OOxB-z_l3Jt:-MxEndEVEILJfOg3hu_L:b5mp0hq) ([raw file](https://github.com/harness/harness-core/blob/6537384e4b60c9bfa1a4e631c652b47c8ea3b613/958-debezium-engine/src/test/java/io/harness/debezium/MongoOffsetBackingStoreTest.java#L27)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see PP's name

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31092)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
