### PR TITLE
techdebt: [SRM-14760]: Using GCP Memory server Redis for locking and caching

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
We were using Enterprise Redis for all our use cases, from now on we will just be using that for events, for locking and caching we will start using GCP Memory server Redis

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47968)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by AbhijithHarness — APPROVED** [review]
Please merge only after Manifest changes are merged

**Comment by Varsha-lalwani** [comment]
trigger ut4

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47968)* status: :shipit: complete! ✓

___
*[`srm-service/build/container/scripts/replace_configs.sh` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/47968#-NVhdDKiA-tf2bqM6Ao_:-NVhdDKiA-tf2bqM6Aoa:b65dl62) ([raw file](https://github.com/harness/harness-core/blob/08f66673164547b86f6b2c07c8748edcf8f862f4/srm-service/build/container/scripts/replace_configs.sh#L161)):*
> ```Shell
> replace_key_value redisLockConfig.userName "$LOCK_CONFIG_REDIS_USERNAME"
> replace_key_value redisLockConfig.password "$LOCK_CONFIG_REDIS_PASSWORD"
> replace_key_value redisLockConfig.nettyThreads "$REDIS_NETTY_THREADS"
> ```

nit: Do we really need to maintain them at env level? generally we hardcode them

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47968)* status: 1. unresolved discussions. 

___
*[`srm-service/build/container/scripts/replace_configs.sh` line 161 at r2](https://reviewable.io/reviews/harness/harness-core/47968#-NVhdDKiA-tf2bqM6Ao_:-NVheMyH5NvPn8bgPAUD:b-hzodhv) ([raw file](https://github.com/harness/harness-core/blob/08f66673164547b86f6b2c07c8748edcf8f862f4/srm-service/build/container/scripts/replace_configs.sh#L161)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

nit: Do we really need to maintain them at env level? generally we hardcode them
</blockquote></details>

this doesn't mean we need to maintain these at env level, but if someday we need to, we can just add the value in the env configs, we don't need to come and add this part as well

**Pull request merged**
