### PR TITLE
feat: [CDS-75839]: Skip Steps inside Stepgroup from Execution Graph for UI Rendering

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Skip Steps inside Stepgroup from Execution Graph for UI Rendering

Q. What was the issue ?
A. StepGroup has child nodeExecution **_steps_** and this _**steps**_  in turn has child nodeExecutions of the children of the stepGroup, But in UI component it was expecting the child of stepGroup to be direct children ( the **_steps_** should have been skipped here, like pipelineExecutionSummary Api) 

Q. What was the fix ?
A. We already have vertexSkipperService in place and there's a method to remove **_removeSkippedVertices_** , we are directly consuming this method, this same method was used in pipelineExecutionSummary Api as well 

Q. What local testing was done ?
A. Listed Below -

Setup :
Stepgroup Stg1 which is having RetryStepGroup FS, and it has 1 shellScript sh1 step and also has a child stepGroup stg2 which was also having RetryStepGroup FS)

Previously on the response in **_nodeAdjacencyListMap_** we were having **_steps_** as direct child of stg1 and stg2, now stepGroup has child of **_steps_** as direct child and _**steps**_ is skipped

New nodeAdjacencyListMap Map :- 

> 
```
            "nodeAdjacencyListMap": {
                "2OX1WVrbSzK0p4ZJk0YWlw": {
                    "children": [],
                    "nextIds": [
                        "U3WGdcR7TkCx2pd-wUg8bQ"
                    ]
                },
                "O6KoZ5LpRoCRjUGPPYvp4w": {
                    "children": [],
                    "nextIds": []
                },
                "U3WGdcR7TkCx2pd-wUg8bQ": {
                    "children": [
                        "O6KoZ5LpRoCRjUGPPYvp4w"
                    ],
                    "nextIds": []
                },
                "Qi-UxaxGRZG2SCsAXC6YrA": {
                    "children": [
                        "2OX1WVrbSzK0p4ZJk0YWlw"
                    ],
                    "nextIds": []
                }
            },
``` 

Previous nodeAdjacencyListMap Response :-
```
            "nodeAdjacencyListMap": {
                "2OX1WVrbSzK0p4ZJk0YWlw": {
                    "children": [],
                    "nextIds": [
                        "U3WGdcR7TkCx2pd-wUg8bQ"
                    ]
                },
                "dxazF7EXSuqkYhM8JyrDgQ": {
                    "children": [
                        "O6KoZ5LpRoCRjUGPPYvp4w"
                    ],
                    "nextIds": []
                },
                "O6KoZ5LpRoCRjUGPPYvp4w": {
                    "children": [],
                    "nextIds": []
                },
                "U3WGdcR7TkCx2pd-wUg8bQ": {
                    "children": [
                        "dxazF7EXSuqkYhM8JyrDgQ"
                    ],
                    "nextIds": []
                },
                "Qi-UxaxGRZG2SCsAXC6YrA": {
                    "children": [
                        "2gImTa07S1S5tQJL3usBKQ"
                    ],
                    "nextIds": []
                },
                "2gImTa07S1S5tQJL3usBKQ": {
                    "children": [
                        "2OX1WVrbSzK0p4ZJk0YWlw"
                    ],
                    "nextIds": []
                }
            },
``` 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51165)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
Please add the following in PR description:
What was the issue?
How did we fix that issue?
Local Testing done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExecutionGraphServiceImpl.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/51165#-Naey_lw68P3IecWX37t:-Naey_lw68P3IecWX37u:bb6hnum) ([raw file](https://github.com/harness/harness-core/blob/bf4eeaff72df0d35fcfed81bb4e99bcd342c7e92/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/ExecutionGraphServiceImpl.java#L54)):*
> ```Java
>     OrchestrationGraph graph = graphGenerationService.buildOrchestrationGraphForNodeExecution(
>         planExecutionId, nodeExecutionId, nodeExecutions);
>     OrchestrationGraphDTO orchestrationGraphDTO = OrchestrationGraphDTOConverter.convertFrom(graph);
> ```

If this function is ununsed, please delete it.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51165)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51165)* status: :shipit: complete! ✓

**Pull request merged**
