### PR TITLE
feat: [CHAOS-3]: Add CHAOS as a valid JIRA project and HCE authors

### PR DESCRIPTION
**Pull request by rajdas24**
Signed-off-by: Raj Das <rajbabu.das@harness.io>

Ticket- https://harness.atlassian.net/browse/CHAOS-3

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33363)

### CODE REVIEW

**Comment by rajdas98** [comment]
trigger compile

**Review by mbatchelor — CHANGES_REQUESTED** [review]
Please also update jira-projects.txt in the root.

**Comment by rajdas98** [comment]
> Please also update jira-projects.txt in the root.

Done @mbatchelor

**Review by mbatchelor — APPROVED** [review]

**Comment by rajdas98** [comment]
trigger messagecheck

**Comment by rajdas98** [comment]
trigger ti2

**Comment by rajdas24** [comment]
trigger authorcheck

**Review by mbatchelor — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33363)* status: :shipit: complete! ✓

**Comment by rajdas24** [comment]
trigger authorcheck

**Review by hemanthmantri — APPROVED** [review]

**Review by hemanthmantri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33363)* status: 1 file(s) to review.

**Review by hemanthmantri — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33363)* status: :shipit: complete! ✓

**Pull request merged**
