### PR TITLE
feat: [CDS-51133]: Added API for schedule jobs and migration script

### PR DESCRIPTION
**Pull request by ivan-83**
The issue is missing the quartz job in DB for the Arlo account and due to this missing service history and also we cannot generate SI reports because the timescale instance_stats table is empty. 

To fix the above issues, 
- Added account API to create InstanceStats and create missing quartz job and trigger.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43562)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddInstanceStatsSnapshotToAccount.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/43562#-NNcEnBIANQdhyZ3G70i:-NNcEnBIANQdhyZ3G70j:bm87834) ([raw file](https://github.com/harness/harness-core/blob/6530c7b964106a53c8b6bda4177ecda41193924a/390-db-migration/src/main/java/io/harness/migrations/all/AddInstanceStatsSnapshotToAccount.java#L41)):*
> ```Java
> 
>   @Override
>   public void migrate() {
> ```

@ivan-83 do you think instead of such a migration, we should simply expose an API that hits "createStats" for a given account id? That way we will always be in control of the system. We just clear existing snapshots and hit our API and it will automatically start the reconciliation process.

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43562)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddInstanceStatsSnapshotToAccount.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/43562#-NNcEnBIANQdhyZ3G70i:-NNi7KayArTS_9_ToNZ7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6530c7b964106a53c8b6bda4177ecda41193924a/390-db-migration/src/main/java/io/harness/migrations/all/AddInstanceStatsSnapshotToAccount.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@ivan-83 do you think instead of such a migration, we should simply expose an API that hits "createStats" for a given account id? That way we will always be in control of the system. We just clear existing snapshots and hit our API and it will automatically start the reconciliation process.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 9 of 11 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43562)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43562)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Comment by ivan-83** [comment]
trigger ti2

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 8 of 11 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43562)* status: :shipit: complete! ✓

**Pull request merged**
