### PR TITLE
fix: [CI-5622]: refactored retry logic

### PR DESCRIPTION
**Pull request by devkimittal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38902)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtD3DT2ZXRW1W2KBgf:-NEtD3DT2ZXRW1W2KBgg:b-i7uu92) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L165)):*
> ```Java
>   }
> 
>   public RetryPolicy<Object> createRetryPolicy(int maxRetries) {
> ```

why is this public? Also, this seems too generic functionality, shouldn't be in this layer.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 139 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDL4FCCQexKnwpBGK:-NEtDL4FCCQexKnwpBGL:bi4ihso) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L139)):*
> ```Java
>     }
>     // Adding retry only on manager as delegate already has retry logic
>     if (!executeOnDelegate) {
> ```

can we move this complete code into a more logical unit, something like "isExecuteOnDelegate()" and it does everything and returns boolean result. Then you can simply just use this method in a if condition and mark retries accordingly.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDeBW-0HxOTk1IRKh:-NEtDeBW-0HxOTk1IRKi:b62wjpr) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L128)):*
> ```Java
> 
>   @Override
>   public List<UserRepoResponse> listAllReposByRefConnector(
> ```

also as short term fix, lets just rename this method to suit what it does actually. Ideally it should be moved from here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 182 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDp0PBstPIvtlEcXT:-NEtDp0PBstPIvtlEcXU:bpx2gmv) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L182)):*
> ```Java
>             testConnectionResult.getStatus(), accountIdentifier));
>       } catch (Exception ex) {
>         log.info(format("failed to test connection for %s Connector for account %s",
> ```

should be error log

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDeBW-0HxOTk1IRKh:-NEtV-bK6WDrs0XdzbcE:bkzpwe6) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L128)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

also as short term fix, lets just rename this method to suit what it does actually. Ideally it should be moved from here.
</blockquote></details>

it lists all repos for a given connector, I think the name is fine

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDeBW-0HxOTk1IRKh:-NEtZ-f08iQyo1c8BlWI:b-lya7me) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L128)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

it lists all repos for a given connector, I think the name is fine
</blockquote></details>

It would've been correct if it had done only that. Currently, its quite customized method only for CI purpose.

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDeBW-0HxOTk1IRKh:-NEt_DP0-C5cKk3akG-b:b-wgd75f) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L128)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It would've been correct if it had done only that. Currently, its quite customized method only for CI purpose.
</blockquote></details>

How about i add a comment saying, this method is called during fetching all the repos for a connector in CI onboarding flow? Or we can change it to something like listAllReposOnboardingFlow or listAllReposForCIOnboarding



_Code quote:_
```Java
listAllReposByRefConnector
```

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDeBW-0HxOTk1IRKh:-NEtdazwAxXpIjxYL690:b-lolcf3) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L128)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

How about i add a comment saying, this method is called during fetching all the repos for a connector in CI onboarding flow? Or we can change it to something like listAllReposOnboardingFlow or listAllReposForCIOnboarding
</blockquote></details>

I just checked, This api is being used by cd as well, https://github.com/harness/harness-core-ui/blob/f6676387c49f0b078b5dbef70f458b7535465712/src/modules/75-cd/pages/get-started-with-cd/SelectArtifact/SelectRepository.tsx#L64
Let's not change it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr4AGANVtH8Zb5czu:-NEtr4AGANVtH8Zb5czv:b-c3483e) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L319)):*
> ```Java
>       try {
>         ConnectorValidationResult testConnectionResult =
>             connectorService.testConnection(accountIdentifier, null, null, NGCommonEntityConstants.HARNESS_IMAGE);
> ```

what is it actually doing? Its not even returning anything here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr9zl2KfOInLGYSIP:-NEtr9zl2KfOInLGYSIQ:b96m090) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L315)):*
> ```Java
>   }
> 
>   public void testDockerConnectivity(String accountIdentifier) {
> ```

why is it named dockerConnectivity? Its test connection on any connector right?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 316 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtrGV0720Tb6d3tgbC:-NEtrGV0720Tb6d3tgbD:b-47fkni) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L316)):*
> ```Java
> 
>   public void testDockerConnectivity(String accountIdentifier) {
>     CompletableFuture.runAsync(() -> {
> ```

As its async call, can we name the method also accordingly.

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr9zl2KfOInLGYSIP:-NEtrdKS-AH4-qe8ATDZ:bpflb5i) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L315)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why is it named dockerConnectivity? Its test connection on any connector right?
</blockquote></details>

will change the name to testDockerConnection

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 316 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtrGV0720Tb6d3tgbC:-NEtrk5ZCvO0gXGCCNnG:bb7oryy) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L316)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

As its async call, can we name the method also accordingly.
</blockquote></details>

sure

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 330 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtrN1W1vAOpju99aBf:-NEtrN1W1vAOpju99aBg:bjksgmr) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L330)):*
> ```Java
>   }
> 
>   public boolean isExecuteOnDelegate(ScmConnector scmConnector) {
> ```

This doesn't belong here, its git sync connector helper class. Please put it as private method inside facilitator service or you can add it into GitSyncUtils class

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr4AGANVtH8Zb5czu:-NEtrlY27KaD0k5HR0i7:b-13u03j) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L319)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what is it actually doing? Its not even returning anything here.
</blockquote></details>

in the onboarding flow, we found out that docker connection was failing while running the pipeline in preflight check. This is to test connection before we reach that step.
@aman-harness correct me if im worng.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr9zl2KfOInLGYSIP:-NEu28PuEgEeTsi4wQ6O:b52r5h2) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L315)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

will change the name to testDockerConnection
</blockquote></details>

I'm actually not getting it. It seems too generic method while functionality is too specific. Can we somehow make it generic enough to comply with the class it is in. It should simply do whats expected out of it. Currently, I don't think its doing it generically enough. Otherwise, this will again need to be moved out of here to some highly common or specific utils for your use-case.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 319 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr4AGANVtH8Zb5czu:-NEu2TL2066mq3sKVph2:bm606ux) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L319)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

in the onboarding flow, we found out that docker connection was failing while running the pipeline in preflight check. This is to test connection before we reach that step.
@aman-harness correct me if im worng.
</blockquote></details>

What help does it do? If we don't do it, whats the issue?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/38902#-NEtDeBW-0HxOTk1IRKh:-NEu2bs276bkC9RXKe8u:b-9kpyer) ([raw file](https://github.com/harness/harness-core/blob/a9fae88b41cdafcd36e4724b47cd46507227d1f5/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L128)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

I just checked, This api is being used by cd as well, https://github.com/harness/harness-core-ui/blob/f6676387c49f0b078b5dbef70f458b7535465712/src/modules/75-cd/pages/get-started-with-cd/SelectArtifact/SelectRepository.tsx#L64
Let's not change it.
</blockquote></details>

I don't want to keep it like this. Its very specific to a use-case and doesn't belong in this class. Ideally it should be moved out of here right away. If that seems big ask, for now its name should be too specific to imply what it does. It cannot have a very generic name.

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/utils/RetryUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38902#-NEu36yh7qXvaO73chxJ:-NEu36yh7qXvaO73chxK:b-j8setu) ([raw file](https://github.com/harness/harness-core/blob/fef194a8be24e63892989e4b51dac8d09ec97af2/980-commons/src/main/java/io/harness/utils/RetryUtils.java#L39)):*
> ```Java
>   public RetryPolicy<Object> createRetryPolicy(int maxRetries, Logger log) {
>     return new RetryPolicy<>()
>         .withDelay(Duration.ofMillis(750))
> ```

we are putting a hard constant inside a common utils class. Please take it as argument.

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/utils/RetryUtils.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/38902#-NEu3DbkAa_P3ghB7qUl:-NEu3Dbl2hZqzdwhbyh1:b9ypain) ([raw file](https://github.com/harness/harness-core/blob/fef194a8be24e63892989e4b51dac8d09ec97af2/980-commons/src/main/java/io/harness/utils/RetryUtils.java#L42)):*
> ```Java
>         .withMaxAttempts(maxRetries)
>         .onFailedAttempt(event
>             -> log.warn(String.format("Scm grpc retry attempt: %d", event.getAttemptCount()), event.getLastFailure()))
> ```

This is a common utility. It shouldn't mention anything specific to a use-case eg: "scm grpc"

**Comment by devkimittal** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 315 at r2](https://reviewable.io/reviews/harness/harness-core/38902#-NEtr9zl2KfOInLGYSIP:-NEu9Y2e45Qcw6VAb8aq:bg5soa3) ([raw file](https://github.com/harness/harness-core/blob/c20511e855d9afff4b024877a7214e4baf63a2c2/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L315)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I'm actually not getting it. It seems too generic method while functionality is too specific. Can we somehow make it generic enough to comply with the class it is in. It should simply do whats expected out of it. Currently, I don't think its doing it generically enough. Otherwise, this will again need to be moved out of here to some highly common or specific utils for your use-case.
</blockquote></details>

makes sense, generalised it to testConnectionAsync

**Comment by devkimittal** [comment]
*[`980-commons/src/main/java/io/harness/utils/RetryUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38902#-NEu36yh7qXvaO73chxJ:-NEu9nLs1SYAgdTWWGbj:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fef194a8be24e63892989e4b51dac8d09ec97af2/980-commons/src/main/java/io/harness/utils/RetryUtils.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we are putting a hard constant inside a common utils class. Please take it as argument.
</blockquote></details>

done

**Comment by mohitg0795** [comment]
*[`980-commons/src/main/java/io/harness/utils/RetryUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38902#-NEu36yh7qXvaO73chxJ:-NEytK2l43UE-4uFVXbi:bnffty9) ([raw file](https://github.com/harness/harness-core/blob/fef194a8be24e63892989e4b51dac8d09ec97af2/980-commons/src/main/java/io/harness/utils/RetryUtils.java#L39)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

done
</blockquote></details>

Whats the fix done here?

**Comment by devkimittal** [comment]
*[`980-commons/src/main/java/io/harness/utils/RetryUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38902#-NEu36yh7qXvaO73chxJ:-NEywFeb6eom_dyWg9-S:bnfo1z9) ([raw file](https://github.com/harness/harness-core/blob/fef194a8be24e63892989e4b51dac8d09ec97af2/980-commons/src/main/java/io/harness/utils/RetryUtils.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Whats the fix done here?
</blockquote></details>

oops, I thought you commented about the failure message. I'll take the duration as argument.

**Comment by devkimittal** [comment]
*[`980-commons/src/main/java/io/harness/utils/RetryUtils.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/38902#-NEu36yh7qXvaO73chxJ:-NEyx2mn2ogmrFB8z2DB:bc8boik) ([raw file](https://github.com/harness/harness-core/blob/fef194a8be24e63892989e4b51dac8d09ec97af2/980-commons/src/main/java/io/harness/utils/RetryUtils.java#L39)):*
<details><summary><i>Previously, devkimittal (Dev Mittal) wrote…</i></summary><blockquote>

oops, I thought you commented about the failure message. I'll take the duration as argument.
</blockquote></details>

changed it

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 3 of 6 files at r2, 1 of 3 files at r3, 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38902)* status: :shipit: complete! ✓

**Pull request merged**
