### PR TITLE
feat: [PIE-3019]: Creation of env group entity in db ng-harness

### PR DESCRIPTION
**Pull request by prashantsharma04**
…nts to them

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31265)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31265)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/envGroup/beans/BasicEnvironmentGroup.java, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/31265#-MxdCr4a3Ny5E0g9U3MW:-MxdCr4a3Ny5E0g9U3MX:bc1mele) ([raw file](https://github.com/harness/harness-core/blob/771fe55bb088318c0e129b2957e23b5801513303/950-ng-core/src/main/java/io/harness/ng/core/envGroup/beans/BasicEnvironmentGroup.java#L17)):*
> ```Java
> @Data
> @Builder
> public class BasicEnvironmentGroup {
> ```

Add recaster alias, why we added basic keyword? any more env groups will be there? EnvironmentGroupConfig?



_Code quote:_
```Java
BasicEnvironmentGroup
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31265)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/envGroup/beans/BasicEnvironmentGroup.java, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/31265#-MxdCr4a3Ny5E0g9U3MW:-MxdNJOK3Xqpnjlb0_gg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/771fe55bb088318c0e129b2957e23b5801513303/950-ng-core/src/main/java/io/harness/ng/core/envGroup/beans/BasicEnvironmentGroup.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Add recaster alias, why we added basic keyword? any more env groups will be there? EnvironmentGroupConfig?
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31265)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by namanvermah — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31265)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31265#-:-MxhUMh8AvMq20XXeh7s:bnfp4nl)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31265)* status: :shipit: complete! ✓

**Pull request merged**
