### PR TITLE
[fix]: [CDS-35609]: Get pipeline api try-catch added

### PR DESCRIPTION
**Pull request by vtxorxwitty**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)

### CODE REVIEW

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 244 at r1](https://reviewable.io/reviews/harness/harness-core/31837#-MzJzrdw1RCJypEygb8H:-MzJzrdw1RCJypEygb8I:b-sybtjb) ([raw file](https://github.com/harness/harness-core/blob/b59059b65b0d70df2e4d11e361943db404156a15/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L244)):*
> ```Java
>       @Parameter(description = PipelineResourceConstants.PIPELINE_ID_PARAM_MESSAGE, required = true) @PathParam(
>           NGCommonEntityConstants.PIPELINE_KEY) @ResourceIdentifier String pipelineId,
>       @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo, @DefaultValue("false") boolean getTemplatesResolvedPipeline) {
> ```

Please add queryParam and parameter annotations
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 269 at r1](https://reviewable.io/reviews/harness/harness-core/31837#-MzJziMA444KMJjPjTGS:-MzJziMA444KMJjPjTGT:bs0kg6g) ([raw file](https://github.com/harness/harness-core/blob/b59059b65b0d70df2e4d11e361943db404156a15/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L269)):*
> ```Java
>       }
>     }
>     pipeline.setResolvedTemplatesPipelineYaml(templateResolvedPipelineYaml);
> ```

This should be in if condition.

**Review by vtxorxwitty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 244 at r1](https://reviewable.io/reviews/harness/harness-core/31837#-MzJzrdw1RCJypEygb8H:-MzK5KMT0p-BzPFUVnrx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b59059b65b0d70df2e4d11e361943db404156a15/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L244)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Please add queryParam and parameter annotations
</blockquote></details>

Done.
___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 269 at r1](https://reviewable.io/reviews/harness/harness-core/31837#-MzJziMA444KMJjPjTGS:-MzK5KykChmvUtixBfhF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b59059b65b0d70df2e4d11e361943db404156a15/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L269)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

This should be in if condition.
</blockquote></details>

Done.

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: 1 change requests. 2. unresolved discussions.

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: 1 change requests. 2. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: :shipit: complete! ✓

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: :shipit: complete! ✓

___
*[800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, line 247 at r3](https://reviewable.io/reviews/harness/harness-core/31837#-MzKZx3M3jlSrWD_K-6k:-MzKZx3N-O05Evb__yVu:b-6q0v4v) ([raw file](https://github.com/harness/harness-core/blob/a52678225b23b2bc909f13e6aa586c9339ab8292/800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L247)):*
> ```Java
>       @Parameter(
>           description =
>               "This is a boolean value. If true, returns Templates resolved Pipeline YAML in the response else returns null.")
> ```

Boolean to get Templates resolved Pipeline YAML in the response



_Code quote:_
```Java
getTemplatesResolvedPipeline
```

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31837)* status: :shipit: complete! ✓

**Pull request merged**
