### PR TITLE
feat: [CDS-41514]: Implement new approach for having ConnectorRef for runtime inputs

### PR DESCRIPTION
**Pull request by bojanmicovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36260)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 4 Code issues 
* Anti-pattern 3 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36260)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/36260#-N9BM1xS34hFwY3bvonp:-N9BM1xS34hFwY3bvonq:b-z6eiv) ([raw file](https://github.com/harness/harness-core/blob/7aa03c4a8cd98597cf9042422e18f9c9d8fb4752/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L195)):*
> ```Java
> 
>   @GET
>   @Path("clustersV2")
> ```

better to use v2/clusters

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/36260#-N9BLv8BBjrP5xEypmNV:-N9BLv8C03_s5sT9GY48:b29yz7m) ([raw file](https://github.com/harness/harness-core/blob/7aa03c4a8cd98597cf9042422e18f9c9d8fb4752/120-ng-manager/src/main/java/io/harness/ng/core/resources/azure/AzureResource.java#L146)):*
> ```Java
> 
>   @GET
>   @Path("resourceGroupsV2")
> ```

better to use v2/resourceGroups

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36260)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger feature-build

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36260)* status: :shipit: complete! ✓

**Comment by bojanmicovic** [comment]
trigger feature-build

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36260)* status: :shipit: complete! ✓

**Pull request merged**
