### PR TITLE
feat: [CDS-46126]: support CRUD of env and children entities at org/account level

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Validation of Env/Services based on scope
Fix query params for Env Group resource

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40603)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 228 at r1](https://reviewable.io/reviews/harness/harness-core/40603#-NHxUy-h54HIoLjBh-sL:-NHxUy-iAbgTzaJe0cft:bfk3yhw) ([raw file](https://github.com/harness/harness-core/blob/cfadc2a3685b6e52b23d479a8c303d39a5355f61/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L228)):*
> ```Java
>       @Parameter(description = "Details of the Environment to be created")
>       @Valid EnvironmentRequestDTO environmentRequestDTO) {
>     throwExceptionForNoRequestDTO(environmentRequestDTO);
> ```

we need to do validations like
if project is specified, then org must be specified also

**Comment by yogesh-chauhan** [comment]
I think we should put API changes behind our FF

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/40603#-NIBkTLv1bn2-31CTTV3:-NIBkTLv1bn2-31CTTV4:b-ngwrvl) ([raw file](https://github.com/harness/harness-core/blob/960bf828fc0aec81001825d5ec1c2c65e2bb3aee/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L237)):*
> ```Java
>     } else {
>       mustBeAtProjectLevel(environmentRequestDTO);
>     }
> ```

we should extract this things out also as a method

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40603)* status: 3 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/40603#-NI1enOZ9f0F0K5nxe-y:-NIHpMLp-eOxx7oSFS-o:b-896fix) (no related file):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think we should put API changes behind our FF 
</blockquote></details>

Done.

___
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 228 at r1](https://reviewable.io/reviews/harness/harness-core/40603#-NHxUy-h54HIoLjBh-sL:-NIHpN6a4aUxZOXU0-Pv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cfadc2a3685b6e52b23d479a8c303d39a5355f61/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L228)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we need to do validations like
if project is specified, then org must be specified also
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 237 at r4](https://reviewable.io/reviews/harness/harness-core/40603#-NIBkTLv1bn2-31CTTV3:-NIHpNTR5aPHf3aY6E-m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/960bf828fc0aec81001825d5ec1c2c65e2bb3aee/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L237)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should extract this things out also as a method
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40603)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40603)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by vivekkarnatiharness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40603)* status: :shipit: complete! ✓

**Pull request merged**
