### PR TITLE
feat: [PL-43365]: OIDC Support in Delegate for CD Tasks

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

This PR adds support for OIDC in CD GCR Tasks in the Delegate side. In this PR the final Service Account Access Token will be retrieved and passed as Auth token for all the GCR API requests.

Tested this in local test environment and it works as expected.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57115)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57115)* status: 14 file(s) to review. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma-PZq6bGL4BFRqdNy:-Nma-PZq6bGL4BFRqdNz:bb22rch) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java#L92)):*
> ```Java
>       throws IOException {
>     // GCP service account email
>     String serviceAccountEmail = "harness-pl-automation@pl-play.iam.gserviceaccount.com";
> ```

Can you recheck this method if SA and other hardcoded values should be hardcoded or configurable?
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma-IlFDasYxFQ6WPQC:-Nma-IlFDasYxFQ6WPQD:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java#L117)):*
> ```Java
>       // Extract the access token from the response
>       String generatedAccessToken = response.getAccessToken();
>       System.out.println("Generated Access Token: " + generatedAccessToken);
> ```

remove
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/constants/GcpOidcServiceAccountAccessTokenResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma-fs-43FmtaiuXbje:-Nma-fs-43FmtaiuXbjf:be6z5iu) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/constants/GcpOidcServiceAccountAccessTokenResponse.java#L21)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PL)
> @Data
> ```

remove builder both fields are required. Just use ctor.
Also, make them final - makes it immutable and @Data doesn't generate setters.
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma01tB7Tdqdh6Btig2:-Nma01tB7Tdqdh6Btig3:b70itsx) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java#L67)):*
> ```Java
>           .expireTime(generateAccessTokenResponse.getExpireTime().getSeconds())
>           .build();
>     } catch (IOException ex) {
> ```

You should handle the exception. 
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma04xN8kE6Xbi0-iJh:-Nma04xN8kE6Xbi0-iJi:b-xyu0vp) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java#L72)):*
> ```Java
>     }
> 
>     return null;
> ```

Usually it's not a great idea to return nulls (just causes null pointers or makes your life harder because now you need to track if it's handled properly). probably need to throw exception in this case.

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57115)* status: 14 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java` line 92 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma-PZq6bGL4BFRqdNy:-NmdngQJ69NyMMvsHlHp:b71vxw2) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java#L92)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Can you recheck this method if SA and other hardcoded values should be hardcoded or configurable?
</blockquote></details>

Ah yes. I had it there for a quick test. It won't be hardcoded, will update it.
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma-IlFDasYxFQ6WPQC:-NmdpskeBNURkpdjcLvq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/accesstoken/GcpOidcAccessTokenUtility.java#L117)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/constants/GcpOidcServiceAccountAccessTokenResponse.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma-fs-43FmtaiuXbje:-NmdriNyBureViKaSk90:bgbn95h) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/constants/GcpOidcServiceAccountAccessTokenResponse.java#L21)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

remove builder both fields are required. Just use ctor.
Also, make them final - makes it immutable and @Data doesn't generate setters.
</blockquote></details>

Done, thanks :) 
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma01tB7Tdqdh6Btig2:-NmdxBBS-hdY6tTYM2Jl:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java#L67)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You should handle the exception.
</blockquote></details>

Done
___
*[`oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/57115#-Nma04xN8kE6Xbi0-iJh:-NmdxBvrEvrxuKJzJHuv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/cb689d82b6d4596f9e62c7b71d9643edafd4d81f/oidc-core/src/main/java/io/harness/oidc/gcp/delegate/GcpOidcTokenExchangeDetailsForDelegate.java#L72)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Usually it's not a great idea to return nulls (just causes null pointers or makes your life harder because now you need to track if it's handled properly). probably need to throw exception in this case.
</blockquote></details>

Done

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by mdmilic — DISMISSED** [review]
> Reviewed 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57115)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57115)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by TarunUba1 — APPROVED** [review]

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger commonchecks, gitleaks

**Comment by Raghav-Murali** [comment]
trigger review

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger ut8

**Comment by Raghav-Murali** [comment]
trigger codebasehash, pmd

**Comment by Raghav-Murali** [comment]
trigger ut8

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger uts

**Comment by Raghav-Murali** [comment]
trigger uts

**Review by jennyjames21 — APPROVED** [review]

**Pull request merged**
