### PR TITLE
feat: [CDS-43839]: Implementing the Dry Run Manifest Step Delegate Side Changes

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Implementing a New Dry Run Manifest step for Kubernetes and Native Helm swimlanes. The customers could not retrieve the rendered Kubernetes Manifest with the Harness variables templated in and leverage it before the Harness K8s apply. Now they store the rendered manifest yaml file as this variable "<+pipeline.stages.{Stage_Name}.spec.execution.steps.{Dry_Run_Manifest_id}.k8s.manifestDryRun>".

Tech Spec: https://harness.atlassian.net/wiki/spaces/CDP/pages/21231601335/Tech+Spec+for+Kubernetes+Dry+Run+Step+NG

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)

### CODE REVIEW

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)* status: 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeAaipA4bUuMUqni_d:-NLeAaipA4bUuMUqni_e:b-jivbim) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L85)):*
> ```Java
>     K8sDryRunManifestRequest k8sDryRunManifestRequest = (K8sDryRunManifestRequest) k8sDeployRequest;
> 
>     releaseName = k8sDryRunManifestRequest.getReleaseName();
> ```

nit: for readability please use this.releaseName, same for other fields
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeByK6AmKrqmg-UwVU:-NLeByK6AmKrqmg-UwVV:b-seut0v) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L92)):*
> ```Java
>         k8sDryRunManifestRequest.isShouldOpenFetchFilesLogStream(), commandUnitsProgress);
> 
>     logCallback.saveExecutionLog(color("\nStarting Kubernetes Rolling Deployment", LogColor.White, LogWeight.Bold));
> ```

Should be Kubernetes Dry Run
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLe95172fN_TXEs5PYU:-NLe95172fN_TXEs5PYV:bbxd626) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L96)):*
> ```Java
>         manifestFilesDirectory, logCallback, steadyStateTimeoutInMillis, k8sDryRunManifestRequest.getAccountId());
> 
>     String dryRunManifestYaml = manifestDryRunYaml(k8sDryRunManifestRequest, k8sDelegateTaskParams,
> ```

Please make sure that this dryRunManifestYaml will not exceed a size limit of 5 mb as a starting point. Let's discuss with Rohan if he has in mind a different limit
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeDiI21Xt2rMDIeS3f:-NLeDiI21Xt2rMDIeS3g:b-7hsa4z) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L104)):*
> ```Java
>   }
> 
>   String manifestDryRunYaml(K8sDryRunManifestRequest request, K8sDelegateTaskParams k8sDelegateTaskParams,
> ```

Let's check if we can share this code with K8sRollingRequestHandler
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 148 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeBLrk8eXUusUzhJTr:-NLeBLrk8eXUusUzhJTs:b-pouzsa) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L148)):*
> ```Java
>   }
> 
>   public String dryRunManifests(Kubectl client, List<KubernetesResource> resources,
> ```

any reason for this to be public?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 154 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeEAc-ATTeIlAtqay_:-NLeEAc-ATTeIlAtqaya:b-6y263y) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L154)):*
> ```Java
>       executionLogCallback.saveExecutionLog(color("\nValidating manifests with Dry Run", White, Bold), INFO);
>       FileIo.writeUtf8StringToFile(
>           k8sDelegateTaskParams.getWorkingDirectory() + "/manifests-dry-run.yaml", ManifestHelper.toYaml(resources));
> ```

Let's make this constant
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandlerTest.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeERw2EI1qzIcZlxs1:-NLeERw2EI1qzIcZlxs2:bpmodfm) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandlerTest.java#L58)):*
> ```Java
> @OwnedBy(CDP)
> @FieldDefaults(level = AccessLevel.PRIVATE)
> public class K8sDryRunManifestRequestHandlerTest extends CategoryTest {
> ```

Please make sure to add some UTs

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)* status: 8 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 85 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeAaipA4bUuMUqni_d:-NLfNSGL1rcK6Log6HUD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L85)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: for readability please use this.releaseName, same for other fields
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 92 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeByK6AmKrqmg-UwVU:-NLfNSxyBWpDpzhz1Nte:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L92)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Should be Kubernetes Dry Run
</blockquote></details>

Done
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLe95172fN_TXEs5PYU:-NLfNUdcAiurcmxqjdPs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L96)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please make sure that this dryRunManifestYaml will not exceed a size limit of 5 mb as a starting point. Let's discuss with Rohan if he has in mind a different limit
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeDiI21Xt2rMDIeS3f:-NLfNVxA8cA7dCMdISl_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L104)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's check if we can share this code with K8sRollingRequestHandler
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 148 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeBLrk8eXUusUzhJTr:-NLfNWo_9FkpFxCA-h7G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L148)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

any reason for this to be public?
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 154 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeEAc-ATTeIlAtqay_:-NLfNYmh0zQePPZ1drms:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L154)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's make this constant
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandlerTest.java` line 58 at r3](https://reviewable.io/reviews/harness/harness-core/42362#-NLeERw2EI1qzIcZlxs1:-NLfN_cJ8NF9O9OauX2b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a5f2cb18a4dee805f08a0db4ea64d4090bc224b/930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandlerTest.java#L58)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please make sure to add some UTs
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 140 at r5](https://reviewable.io/reviews/harness/harness-core/42362#-NLfSZ247LXLTdXMZ6Cr:-NLfSZ247LXLTdXMZ6Cs:b61zz5n) ([raw file](https://github.com/harness/harness-core/blob/7144a35ff9182d5dd0a7c354193bd05361665029/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L140)):*
> ```Java
>       executionLogCallback.saveExecutionLog("\nDone.", INFO, SUCCESS);
>       String dryRunManifestYaml = ManifestHelper.toYamlForLogs(this.resources);
>       return dryRunManifestYaml.getBytes(StandardCharsets.UTF_8).length < MAX_VARIABLE_SIZE ? dryRunManifestYaml : "";
> ```

Let's add some warning logs if it exceeds max size (don't forget to move Done log at the end, before return

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java` line 140 at r5](https://reviewable.io/reviews/harness/harness-core/42362#-NLfSZ247LXLTdXMZ6Cr:-NLfXYjwE2Pl6KwdyNII:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7144a35ff9182d5dd0a7c354193bd05361665029/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sDryRunManifestRequestHandler.java#L140)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add some warning logs if it exceeds max size (don't forget to move Done log at the end, before return
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362)* status: 8 file(s) to review.

**Review by puthrayaharness — APPROVED** [review]

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 3 of 4 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42362#-:-NLg2TSY30JfUhD8dDXI:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
