### PR TITLE
feat: [PIE-6046]: NG - Add support for github webhook release event in scm-service

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR adds support for Github Release event on scm-service. Support for this event was added in go-scm package here: https://github.com/drone/go-scm/pull/229

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41831)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`product/ci/scm/repo/repo.go` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCj751L7donvc9MGU:-NJlCj76CPUEBwLdjNuM:b-r8llav) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/repo/repo.go#L29)):*
> ```Go
> 	"pull_request_review": pb.GithubWebhookEvent_GITHUB_PULL_REQUEST_REVIEW,
> 	"push":                pb.GithubWebhookEvent_GITHUB_PUSH,
>         "release":             pb.GithubWebhookEvent_GITHUB_RELEASE,
> ```

indentation looks off here

**Comment by mohitg0795** [comment]
*[`product/ci/scm/proto/scm.proto` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCrfpAMt7pWRo3DDx:-NJlCrfpAMt7pWRo3DDy:b-1mn45k) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/proto/scm.proto#L138)):*
> ```protobuf
>   string link = 3;
>   string tag = 4;
>   string commitish = 5;
> ```

whats "commitish"?

**Comment by mohitg0795** [comment]
*[`product/ci/scm/proto/scm.proto` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCw2-DRGVTB45IZsz:-NJlCw2-DRGVTB45IZt-:bs74lea) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/proto/scm.proto#L141)):*
> ```protobuf
>   bool draft = 6;
>   bool prerelease = 7;
>   google.protobuf.Timestamp created = 8;
> ```

general convention for timestamps is to use something like "createdAt" or "publishedAt". [Not a blocking comment]

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41831)* status: 12 file(s) to review. 0 of 2 approvals obtained.

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41831)* status: 12 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/proto/scm.proto` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCrfpAMt7pWRo3DDx:-NJlJeKL-rJ8SNVkawB4:b-rxub09) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/proto/scm.proto#L138)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats "commitish"?
</blockquote></details>

From Github docs: "Specifies the commitish value that determines where the Git tag is created from.". It is supposed to contain a reference to where the tag was created (branch name, commit ID). I kept it in because I thought maybe could be useful for some customer in filtering webhook payload, etc. I can remove it if you think its best. 
___
*[`product/ci/scm/proto/scm.proto` line 141 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCw2-DRGVTB45IZsz:-NJlKVLx5rJNUZfqhlcX:b-mg0v4n) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/proto/scm.proto#L141)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

general convention for timestamps is to use something like "createdAt" or "publishedAt". [Not a blocking comment]
</blockquote></details>

I'm following the way these timestamp fields are named in the other entities defined in this same file.
___
*[`product/ci/scm/repo/repo.go` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCj751L7donvc9MGU:-NJlM5pdC4okMsOgqjY3:b-1jl013) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/repo/repo.go#L29)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

indentation looks off here
</blockquote></details>

Fixed. Thank you!

**Comment by mohitg0795** [comment]
*[`product/ci/scm/proto/scm.proto` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCrfpAMt7pWRo3DDx:-NJnKAgp7-OMKfQ8Pl4e:bmqyee2) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/proto/scm.proto#L138)):*
<details><summary><i>Previously, vcalasansh (Vinícius Calasans) wrote…</i></summary><blockquote>

From Github docs: "Specifies the commitish value that determines where the Git tag is created from.". It is supposed to contain a reference to where the tag was created (branch name, commit ID). I kept it in because I thought maybe could be useful for some customer in filtering webhook payload, etc. I can remove it if you think its best. 
</blockquote></details>

My concern is that this will be an internal field and no one understands it much, so it may become confusing with time. Also, what about other git providers? Is it same meaning for all?

**Review by vcalasansh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41831)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`product/ci/scm/proto/scm.proto` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/41831#-NJlCrfpAMt7pWRo3DDx:-NJpAIKA-hftbyIGMcLK:b-w9lxmh) ([raw file](https://github.com/harness/harness-core/blob/01ca453e3e154a99c51b46b07a43227b27f8412f/product/ci/scm/proto/scm.proto#L138)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

My concern is that this will be an internal field and no one understands it much, so it may become confusing with time. Also, what about other git providers? Is it same meaning for all? 
</blockquote></details>

 I checked other git provider’s documentation and there is no mention to this kind of commitish field. GitLab also has a “Release” webhook event and it doesn’t have this field. So I removed it from this PR, I don’t think its very useful anyway. Thank you!

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41831)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41831)* status: :shipit: complete! ✓

**Pull request merged**
