### PR TITLE
feat: [CET-1184]: Add commitID to GitSync GetFile request

### PR DESCRIPTION
**Pull request by David-Kreiner**
## Describe your changes
Added commitId to GRPC getFile implementation to allow Error Tracking to use this functionality.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46141)

### CODE REVIEW

**Comment by David-Kreiner** [comment]
trigger utAll

**Comment by David-Kreiner** [comment]
trigger utAll

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 115 at r2](https://reviewable.io/reviews/harness/harness-core/46141#-NTJZvFF9FhKK_a-PjBc:-NTJZvFF9FhKK_a-PjBd:b-5i9kbb) ([raw file](https://github.com/harness/harness-core/blob/dd4cf35b0c73d6ed8b57d347b2218c5f614404f4/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L115)):*
> ```protobuf
>   string branchName = 2;
>   string filePath = 3;
>   string commitId = 4;
> ```

idk how 4 index got missed. Any idea if adding the index-4 now can cause any backward incompatibility? IIRC grpc works on indexed values, so if other indexes are untouched, it shouldn't cause any issue.

**Comment by David-Kreiner** [comment]
trigger ut7

**Review by adivishy1 — APPROVED** [review]
> Reviewed 16 of 18 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46141)* status: :shipit: complete! ✓

**Comment by David-Kreiner** [comment]
trigger ut6

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46141)* status: :shipit: complete! ✓

**Review by sathish-soundarapandian — DISMISSED** [review]

**Review by vikyathharekal — DISMISSED** [review]

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46141)* status: :shipit: complete! ✓

**Comment by David-Kreiner** [comment]
trigger utAll

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 18 files at r1, 1 of 8 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46141)* status: :shipit: complete! ✓

**Review by vikyathharekal — APPROVED** [review]

**Pull request merged**
