### PR TITLE
fix: [CDS-35470]: NG manager side changes

### PR DESCRIPTION
**Pull request by TarunUba1**
## Describe your changes
NG manager side changes for command flags. This feature allows user to specify command flags w.r.t. their needs
## Testing
Checked for old delegate with FF on and off. New delegate with FF on and Off
PR: https://cd.pr.harness.io/cds-35470-final/ng/#/account/kmpySmUISimoRrJL6NL73w/cd/orgs/default/projects/defaultproject/pipelines

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)

### CODE REVIEW

**Comment by TarunUba1** [comment]
trigger featurenamecheck

**Comment by TarunUba1** [comment]
trigger featurenamecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 12 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: Some of the checks are too old. 46 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 633 at r2](https://reviewable.io/reviews/harness/harness-core/41338#-NJ50vQF1XvVCuOFvlfv:-NJ50vQF1XvVCuOFvlfw:b-k03nq8) ([raw file](https://github.com/harness/harness-core/blob/4ac43c8d571b99e5fb1a581f0256f2b739f390c9/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L633)):*
> ```Java
>   @Path("/k8s/command-flags")
>   @ApiOperation(value = "Get Command flags for K8s", nickname = "k8sCmdFlags")
>   @Operation(operationId = "k8sCmdFlags", summary = "Gets Service Access list",
> ```

Is this summary and ApiResponse.description accurate? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyBaseStepInfo.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/41338#-NJ51GiD1hBhsduvn3Fh:-NJ51GiD1hBhsduvn3Fi:b-bo3z0t) ([raw file](https://github.com/harness/harness-core/blob/4ac43c8d571b99e5fb1a581f0256f2b739f390c9/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyBaseStepInfo.java#L52)):*
> ```Java
>   @JsonProperty("overrides") List<ManifestConfigWrapper> overrides;
>   @ApiModelProperty(dataType = BOOLEAN_CLASSPATH) @YamlSchemaTypes({string}) ParameterField<Boolean> skipRendering;
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_CLASSPATH) ParameterField<String> commandFlags;
> ```

Is it safe to assume that we will not support other types of commands flags?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 521 at r2](https://reviewable.io/reviews/harness/harness-core/41338#-NJ52-fx1x01s5sbS2FU:-NJ52-fy0lIqHPnN9kET:buytwwn) ([raw file](https://github.com/harness/harness-core/blob/4ac43c8d571b99e5fb1a581f0256f2b739f390c9/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L521)):*
> ```Java
>       HarnessTeam.CDP),
>   PURGE_DANGLING_APP_ENV_REFS("Explicitly purge dangling references of app/env", HarnessTeam.SPG),
>   NG_K8_COMMAND_FLAGS("Added Support for adding Command flags to commands", HarnessTeam.CDP);
> ```

Please review FF name and description with Rohan

**Comment by TarunUba1** [comment]
trigger ss

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 43 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java` line 633 at r2](https://reviewable.io/reviews/harness/harness-core/41338#-NJ50vQF1XvVCuOFvlfv:-NJFRGiKAVQxQd0lS0W1:b-pflk75) ([raw file](https://github.com/harness/harness-core/blob/4ac43c8d571b99e5fb1a581f0256f2b739f390c9/120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java#L633)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is this summary and ApiResponse.description accurate? 
</blockquote></details>

Got reviewed by Rohan
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyBaseStepInfo.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/41338#-NJ51GiD1hBhsduvn3Fh:-NJFRKBu1j5VhhXpO0s3:b-73bset) ([raw file](https://github.com/harness/harness-core/blob/4ac43c8d571b99e5fb1a581f0256f2b739f390c9/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sApplyBaseStepInfo.java#L52)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is it safe to assume that we will not support other types of commands flags?
</blockquote></details>

Got reviewed by Rohan
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 521 at r2](https://reviewable.io/reviews/harness/harness-core/41338#-NJ52-fx1x01s5sbS2FU:-NJFRMnO-7Z6c8T6kcre:b-pflk75) ([raw file](https://github.com/harness/harness-core/blob/4ac43c8d571b99e5fb1a581f0256f2b739f390c9/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L521)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please review FF name and description with Rohan
</blockquote></details>

Got reviewed by Rohan

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 46 files at r1, 17 of 20 files at r3, 6 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 43 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 964 at r5](https://reviewable.io/reviews/harness/harness-core/41338#-NJFTsJs7tRCMCm0KJXT:-NJFTsJs7tRCMCm0KJXU:b-r1x4u6) ([raw file](https://github.com/harness/harness-core/blob/42b68f0baf1b6efcbe6b04f932bcf755a0374dbb/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L964)):*
> ```Java
>     Map<String, String> commandsValueMap = new HashMap<>();
>     for (K8sStepCommandFlag commandFlag : commandFlags) {
>       commandsValueMap.put(commandFlag.getCommandType().getSubCommandType(), commandFlag.getFlag().getValue());
> ```

Is see that you're using @SkipAutoEvaluation of the flag value. Don't we need then to render it manually here?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 43 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 964 at r5](https://reviewable.io/reviews/harness/harness-core/41338#-NJFTsJs7tRCMCm0KJXT:-NJJdzdW9yG2rkLH6QSm:b-bfmmem) ([raw file](https://github.com/harness/harness-core/blob/42b68f0baf1b6efcbe6b04f932bcf755a0374dbb/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L964)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Is see that you're using @SkipAutoEvaluation of the flag value. Don't we need then to render it manually here?
</blockquote></details>

There is one use case that I've discussed with Rohan. Since the input here is a list, use can have something like:
- Apply : --flag1
- Apply : --flag2

The issue here is that we will end up in using only --flag2 and not --flag1. What we should do here is to check if key already exists in map then we should merge it and not overwrite. Something like --flag2 + " " + flag1
As well please make sure that getFlag actually exists you can use ParameterField.isNull.

**Review by TarunUba1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 43 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 964 at r5](https://reviewable.io/reviews/harness/harness-core/41338#-NJFTsJs7tRCMCm0KJXT:-NJJQmyQ4c-g9z1bF1m_:b1u8hnu) ([raw file](https://github.com/harness/harness-core/blob/42b68f0baf1b6efcbe6b04f932bcf755a0374dbb/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L964)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

There is one use case that I've discussed with Rohan. Since the input here is a list, use can have something like:
- Apply : --flag1
- Apply : --flag2

The issue here is that we will end up in using only --flag2 and not --flag1. What we should do here is to check if key already exists in map then we should merge it and not overwrite. Something like --flag2 + " " + flag1
As well please make sure that getFlag actually exists you can use ParameterField.isNull.  
</blockquote></details>

Oh, The customer can provide command flags as space separated in the option. Currently in Helm thats the way its been approached. For a specific type of step there is only one string and there user can enter space separated commandFlags. as the string is appended at the end of the command it will automatically be applied

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 18 of 46 files at r1, 3 of 20 files at r3, 4 of 7 files at r4, 1 of 5 files at r5, 20 of 20 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sApplyStepTest.java` line 75 at r6](https://reviewable.io/reviews/harness/harness-core/41338#-NJokghRCA6qT3ucevVH:-NJokghRCA6qT3ucevVI:b-ytzfe) ([raw file](https://github.com/harness/harness-core/blob/bfdb910bd078570548feb2432e67ad9f61294b59/125-cd-nextgen/src/test/java/io/harness/cdng/k8s/K8sApplyStepTest.java#L75)):*
> ```Java
>   @Category(UnitTests.class)
>   public void testExecuteTask() {
>     when(cdFeatureFlagHelper.isEnabled(any(), any())).thenReturn(true);
> ```

nit: better to add the FF name instead of any(). This would return true for any FF we add in the future.

**Review by TarunUba1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338#-:-NJpnBE91fPAFh-gh6Pq:bnfp4nl)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by TarunUba1** [comment]
trigger smartchecks

**Comment by TarunUba1** [comment]
trigger ti3

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
An unrelated test is failing. You might have to rebase once it's fixed in develop.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338#-:-NJsdZ4XEOe4CFD8xi6E:bpf66mb)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 16 of 20 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: :shipit: complete! ✓

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 17 of 46 files at r1, 3 of 20 files at r3, 4 of 7 files at r4, 6 of 20 files at r6, 2 of 4 files at r7, 1 of 1 files at r8, 1 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41338)* status: :shipit: complete! ✓

**Pull request merged**
