### PR TITLE
[feat]: [CDS-43098]: service-env migration api

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
Added an API for service-env migration that will take stage yaml (referring to old service) as input, will update/create service v2 and infra entities and return updated stage yaml  as output
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)

### CODE REVIEW

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHsj6Wf5WF3OtFpgk-b:-NHsj6WgEbqdS3OmtTbs:b-z63vuf) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L88)):*
> ```Java
>   }
> 
>   public String createServiceInfraV2(StageRequestDto stageRequestDto, String accountId) {
> ```

lets call this migrate(..) and pull NotNull annotations on StageRequestDTO and accountID

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHtUHg003gmQoo82Opa:-NHtUHg003gmQoo82Opb:b1x87o0) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L209)):*
> ```Java
>         throw new InvalidRequestException(
>             "Infrastructure yaml is not valid, template variables and infra variables doesn't match");
>       }
> ```

why do we need this check here ? shouldn't `infrastructureEntityService` take care of it

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: Some of the checks are too old. 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHsj0J1BuoMiTVagozd:-NHsj0J1BuoMiTVagoze:b-oeshck) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L62)):*
> ```Java
>   @Data
>   @Builder
>   public static class StageSchema {
> ```

this can be a private class

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/40545#-NI3cCTk0-wNTTGdPybq:-NI3cCTk0-wNTTGdPybr:bdp1qro) ([raw file](https://github.com/harness/harness-core/blob/f5d150ef53384ce0e66fc5c18ddfd2f103766215/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L138)):*
> ```Java
>     String migratedPipelineYaml = YamlPipelineUtils.writeYamlString(pipelineParentNode);
>     if(requestDto.isUpdatePipeline()) {
>       NGRestUtils.getResponse(pipelineServiceClient.updatePipeline(null,
> ```

This might not forward the USER principal to pipeline service so it does not check if the user does not have pipeline update permission

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 132 at r6](https://reviewable.io/reviews/harness/harness-core/40545#-NI3h5RpDJOrpeSB374w:-NI3h5Rq4cMehA2vU4yj:bf7hqb6) ([raw file](https://github.com/harness/harness-core/blob/819bf301936b1ad7b28354a707f02339eca4e968/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L132)):*
> ```Java
>     for (int currentIndex = 0; currentIndex < stageArrayNode.size(); currentIndex++) {
>       JsonNode stageNode = stageArrayNode.get(currentIndex);
>       YamlNode stageYamlNode = new YamlNode(stageNode);
> ```

We should check if the stage is of type "Deployment"

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 132 at r6](https://reviewable.io/reviews/harness/harness-core/40545#-NI3h5RpDJOrpeSB374w:-NI3h5Rq4cMehA2vU4yj:bf7hqb6) ([raw file](https://github.com/harness/harness-core/blob/819bf301936b1ad7b28354a707f02339eca4e968/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L132)):_
> 
> > ```java
> >     for (int currentIndex = 0; currentIndex < stageArrayNode.size(); currentIndex++) {
> >       JsonNode stageNode = stageArrayNode.get(currentIndex);
> >       YamlNode stageYamlNode = new YamlNode(stageNode);
> > ```
> 
> We should check if the stage is of type "Deployment"

Done

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 138 at r3](https://reviewable.io/reviews/harness/harness-core/40545#-NI3cCTk0-wNTTGdPybq:-NI3cCTk0-wNTTGdPybr:bdp1qro) ([raw file](https://github.com/harness/harness-core/blob/f5d150ef53384ce0e66fc5c18ddfd2f103766215/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L138)):_
> 
> > ```java
> >     String migratedPipelineYaml = YamlPipelineUtils.writeYamlString(pipelineParentNode);
> >     if(requestDto.isUpdatePipeline()) {
> >       NGRestUtils.getResponse(pipelineServiceClient.updatePipeline(null,
> > ```
> 
> This might not forward the USER principal to pipeline service so it does not check if the user does not have pipeline update permission

yes, I missed this check. I think you already added it now.

**Comment by PragyeshMishra01** [comment]
> > Reviewed 4 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)_ status: Some of the checks are too old. 2 file(s) to review. 0 of 1 approvals obtained.
> 
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHsj0J1BuoMiTVagozd:-NHsj0J1BuoMiTVagoze:b-oeshck) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L62)):_
> 
> > ```java
> >   @Data
> >   @Builder
> >   public static class StageSchema {
> > ```
> 
> this can be a private class

done

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 88 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHsj6Wf5WF3OtFpgk-b:-NHsj6WgEbqdS3OmtTbs:b-z63vuf) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L88)):_
> 
> > ```java
> >   }
> > 
> >   public String createServiceInfraV2(StageRequestDto stageRequestDto, String accountId) {
> > ```
> 
> lets call this migrate(..) and pull NotNull annotations on StageRequestDTO and accountID

done

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHtUHg003gmQoo82Opa:-NHtUHg003gmQoo82Opb:b1x87o0) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L209)):_
> 
> > ```java
> >         throw new InvalidRequestException(
> >             "Infrastructure yaml is not valid, template variables and infra variables doesn't match");
> >       }
> > ```
> 
> why do we need this check here ? shouldn't `infrastructureEntityService` take care of it

I see that this logic is present in infrastructureResource class, that's why I added it for safety.
Ref: io.harness.ng.core.infrastructure.resource.InfrastructureResource#create

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHtUHg003gmQoo82Opa:-NI6nz8q2F6yiDCPp2pM:b3mx6oo) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L209)):*
<details><summary><i>Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…</i></summary><blockquote>

I see that this logic is present in infrastructureResource class, that's why I added it for safety.
Ref: io.harness.ng.core.infrastructure.resource.InfrastructureResource#create

</blockquote></details>

isNotValidInfrastructureYaml this internally calls template service as well. Lets remove it from here and let the infra service take care of this



_Code quote:_
```Java
isNotValidInfrastructureYaml
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: 12 file(s) to review. 0 of 2 approvals obtained.

**Comment by PragyeshMishra01** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/40545#-NHtUHg003gmQoo82Opa:-NI6nz8q2F6yiDCPp2pM:b3mx6oo) ([raw file](https://github.com/harness/harness-core/blob/00dddf5ef5c2a2e2fbf0773790b0115835bbd8f7/120-ng-manager/src/main/java/io/harness/ng/core/migration/serviceenvmigrationv2/ServiceEnvironmentV2MigrationService.java#L209)):_
> 
> Previously, PragyeshMishra01 (Pragyesh Mishra) wrote…
> isNotValidInfrastructureYaml this internally calls template service as well. Lets remove it from here and let the infra service take care of this
> 
> _Code quote:_
> 
> ```java
> isNotValidInfrastructureYaml
> ```

done

**Review by yogesh-chauhan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545#-:-NI7MsZ398ocs0KCOh20:bnfp4nl)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Comment by PragyeshMishra01** [comment]
trigger smartchecks

**Comment by PragyeshMishra01** [comment]
trigger smartchecks

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 3 of 11 files at r5, 2 of 6 files at r7, 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: 3 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40545)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
