### PR TITLE
fix: [CDS-53038]: adding cleanup logic for v2 perpetual task

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
- This Cleanup Logic will help to cleanup the not required InstanceSyncTaskDetails and Perpetual Task of Instance Sync v2

## Delegate Changes Checklist
- delegate change are backward compatible and behind FF

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
# Changes Inprogress

**Review by abosii-harness — CHANGES_REQUESTED** [review]

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/43719#-NNow1gCG7Ns4rUSQ0zY-r2-70:-NNtiKeW0DWc_IFmoDoI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7d4e58e8065670f0e50704287a132af69c29bb29/400-rest/src/main/java/software/wings/instancesyncv2/handler/K8sInstanceSyncV2DeploymentHelperCg.java#L70)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please revert
</blockquote></details>

Done.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 243 at r6](https://reviewable.io/reviews/harness/harness-core/43719#-NNu9FkWCUorU6xZ6AWf:-NNu9FkWCUorU6xZ6AWg:b9x9zb2) ([raw file](https://github.com/harness/harness-core/blob/29d9224b103d93c85f4c4b54d3da85560aca5216/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L243)):*
> ```Java
> 
>     // Cleaning up th Unused instanceSyncTaskDetails and Perpetual Task if Present
>     instanceSyncV2CleanupIfPresent(perpetualTaskId, result);
> ```

This logic is not safe in my opinion and will be time consuming since we're doing it always. What if perpetualTask this time was successful? And what if the perpetual task is not successful then weren't going to do this clean up. This logic should be done in the next way:
1. If perpetual task is not successful then we should start going over the instanceSyncTaskDetails and delete the one that were failing for more than n time (basically the logic that you have implemented here)
2. If a response for a instance task detail is not successful for a N time then delete it and if there is no more task details then delete perpetual task
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 263 at r6](https://reviewable.io/reviews/harness/harness-core/43719#-NNuAO351sxC2PIF4uQ1:-NNuAO351sxC2PIF4uQ2:b-cmlhd9) ([raw file](https://github.com/harness/harness-core/blob/29d9224b103d93c85f4c4b54d3da85560aca5216/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L263)):*
> ```Java
>   }
> 
>   private void instanceSyncV2CleanupIfPresent(String perpetualTaskId, CgInstanceSyncResponse result) {
> ```

This operation should be synced, otherwise it could end up in a wrong behavior

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 243 at r6](https://reviewable.io/reviews/harness/harness-core/43719#-NNu9FkWCUorU6xZ6AWf:-NNvDRsc9sRuCgVr1Ol0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29d9224b103d93c85f4c4b54d3da85560aca5216/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L243)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This logic is not safe in my opinion and will be time consuming since we're doing it always. What if perpetualTask this time was successful? And what if the perpetual task is not successful then weren't going to do this clean up. This logic should be done in the next way:
1. If perpetual task is not successful then we should start going over the instanceSyncTaskDetails and delete the one that were failing for more than n time (basically the logic that you have implemented here)
2. If a response for a instance task detail is not successful for a N time then delete it and if there is no more task details then delete perpetual task
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 263 at r6](https://reviewable.io/reviews/harness/harness-core/43719#-NNuAO351sxC2PIF4uQ1:-NNvDTlZCmAqYH5X5u4y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29d9224b103d93c85f4c4b54d3da85560aca5216/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L263)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This operation should be synced, otherwise it could end up in a wrong behavior
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 3 files at r5, 2 of 3 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 345 at r10](https://reviewable.io/reviews/harness/harness-core/43719#-NNvIb031crGHvSzjTFK:-NNw8Enr1g_q9T7eprkj:bx68tni) ([raw file](https://github.com/harness/harness-core/blob/90118a85cadbafccef0898eb022d44f21d596434/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L345)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

ExceptionUtils.getMessage() wouldn't do this better?
</blockquote></details>

Tested this is not working as expected

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: 4 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 2 of 3 files at r9, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43719)* status: Waiting on team(s): del-team.

**Pull request merged**
