### PR TITLE
[fix]: [CDS-78621]: Get calculate status only for direct children

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

**Changes** - Added Calculate planExecution status update during execution only accounting non-flowing statuses and non final statuses, this will reduce DB query result.

Also, now we will be calculating planExecutionStatus update in resume event -> only if planExecution is not running, as non-flowing statuses have impact on planExecution, so if planExecution is already in Running -> there is no need to update planExecution or calculate even.

**Why we are doing it**
We are calling calculate status on each Resume node event -> thus for very big executions -> we unnecessary getting all nodes statuses to update.

Its needed for cases like approval, wait steps to update planExecutions, thus it can be optimised to call calculatestatus smartly.
Plus also to fetch nodes statuses -> we only care about if non-final and non-flowing (running statuses) are present -> else always update to running status of planExecutions.

Plus we have updated our query that it will use projection covered index, thus optimised DB query.

https://github.com/harness/harness-core/pull/42817/files#diff-b2a30acd875ab475b434cd4e7ed047af4c2c80e20ef2495d4c71b00ba644b298 -> this is the PR where we added this calculate plan Execution status on each resume, which we optimised in this PR

**Impact** -
a) PlanExecution get and updates are reduced
b) NodeExecution db queries are reduced.
c) Even in case of nodeExecution query -> records are reduced as we get only non-flowing and non-final statuses.
d) Updating planExecution status under lock so as to avoid race conditions

**Testing** -
1. Added unit tests for impl
2. Aborting a running executions
3. Matrix pipeline executions
4. Wait step and approval step testing pipeline where after these waiting step there is a shell step with sleep 30, planExecution status is updating correctly
5. Checked mongo query added is using projection covered or not. Its using intended index with projection covered.

Screenshot 2023-09-04 at 1 38 12 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52386)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1, 1 of 3 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52386)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java` line 251 at r3](https://reviewable.io/reviews/harness/harness-core/52386#-NdVAyr_06WbXdpWV2XO:-NdVAyr_06WbXdpWV2XP:b-f320vk) ([raw file](https://github.com/harness/harness-core/blob/e29b7a6453049dd4bcf7e934659a304a54e6955a/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java#L251)):*
> ```Java
>     try (AcquiredLock<?> lock =
>              persistentLocker.waitToAcquireLockOptional(lockName, Duration.ofSeconds(10), Duration.ofSeconds(30))) {
>       if (lock == null) {
> ```

What should we do if we fail to acquire just proceed?

**Comment by archit-harness** [comment]
trigger ut6

**Review by hextechpal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52386)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 3 of 14 files at r1, 1 of 3 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52386)* status: :shipit: complete! ✓

**Comment by archit-harness** [comment]
trigger review

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 3 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52386)* status: :shipit: complete! ✓

**Pull request merged**
