### PR TITLE
[fix]: [CDS-78225]: update layoutNodeMap for post prod rollback

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
## Describe your changes
update layoutNodeMap for post prod rollback
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53023)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/53023#-NekpDfdAFskhSM8P9sk:-NekpDfdAFskhSM8P9sl:bo241o7) ([raw file](https://github.com/harness/harness-core/blob/2e7a2ac555ba0de36f701590638b63599ed31bd7/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L73)):*
> ```Java
>       updated = performUpdatesOnBarrierNode(update, nodeExecution);
>     }
>     if (RunInfoUtilsV1.isRollbackMode(nodeExecution.getAmbiance().getMetadata().getExecutionMode())) {
> ```

This condition should be ```if (ambiance.getMetadata().getExecutionMode() == ExecutionMode.POST\_EXECUTION\_ROLLBACK) {```

We don't want this for pipeline rollback but only post prod rollback.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/53023#-NekpmZC1JaEOUA55NXe:-NekpmZC1JaEOUA55NXf:b-jig2mt) ([raw file](https://github.com/harness/harness-core/blob/2e7a2ac555ba0de36f701590638b63599ed31bd7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L80)):*
> ```Java
>                 : pipelineExecutionSummaryEntity.getModules())
>         .gitDetails(entityGitDetails)
>         .canRetry((pipelineExecutionSummaryEntity.getExecutionMode() != ExecutionMode.POST_EXECUTION_ROLLBACK)
> ```

ExecutionModeUtils has a function similar to this, can we ruse that?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/ExecutionSummaryCreateEventHandler.java` line 173 at r1](https://reviewable.io/reviews/harness/harness-core/53023#-NekpuNV-tyEl5bL-_el:-NekpuNV-tyEl5bL-_em:b5lcsd0) ([raw file](https://github.com/harness/harness-core/blob/2e7a2ac555ba0de36f701590638b63599ed31bd7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/ExecutionSummaryCreateEventHandler.java#L173)):*
> ```Java
>                       .build())
>               .build());
>       layoutNodeMap = modifiedLayoutNodeMap;
> ```

Could you please test it using a deploy stage with multi-service/environment?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53023)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/53023#-Neq4Hjl3fCc-jtZctJJ:-Neq4Hjl3fCc-jtZctJK:b4pdhlr) ([raw file](https://github.com/harness/harness-core/blob/f8465780dfc2aa46956cf16e05ff875edc4a964c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java#L37)):*
> ```Java
>   String ROLLBACK_MODE_EXECUTION = "OnRollbackModeExecution";
> 
>   public boolean isPostExecutionRollbackMode(ExecutionMode executionMode) {
> ```

Please add this in ExecutionModeUtils

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/53023#-Neq4RecBZh2fJaAlOd-:-Neq4RecBZh2fJaAlOd0:buq9jon) ([raw file](https://github.com/harness/harness-core/blob/f8465780dfc2aa46956cf16e05ff875edc4a964c/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L84)):*
> ```Java
>         }
>       }
>       if (Objects.equals(nodeExecution.getNodeId(), startingNodeId)) {
> ```

I think above for loop should be enough, why do we need this?
We will get the given id in levels already.

**Comment by rathodmeetsatish** [comment]
trigger uts

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53023)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/53023#-NekpDfdAFskhSM8P9sk:-Neqvjwq1xCJW5FcMYbC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e7a2ac555ba0de36f701590638b63599ed31bd7/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L73)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This condition should be ```if (ambiance.getMetadata().getExecutionMode() == ExecutionMode.POST\_EXECUTION\_ROLLBACK) {```

We don't want this for pipeline rollback but only post prod rollback.
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/53023#-Neq4RecBZh2fJaAlOd-:-NeqvkOb7sQaMWoNA2PY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8465780dfc2aa46956cf16e05ff875edc4a964c/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L84)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I think above for loop should be enough, why do we need this?
We will get the given id in levels already.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/53023#-NekpmZC1JaEOUA55NXe:-Neqvlxa8w1udE_eihSo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e7a2ac555ba0de36f701590638b63599ed31bd7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L80)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

ExecutionModeUtils has a function similar to this, can we ruse that?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/ExecutionSummaryCreateEventHandler.java` line 173 at r1](https://reviewable.io/reviews/harness/harness-core/53023#-NekpuNV-tyEl5bL-_el:-NeqvmZfBhtlUl-QvV93:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2e7a2ac555ba0de36f701590638b63599ed31bd7/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/ExecutionSummaryCreateEventHandler.java#L173)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Could you please test it using a deploy stage with multi-service/environment?
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/53023#-Neq4Hjl3fCc-jtZctJJ:-NeqvmuX-Vb2B-gfmwlL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f8465780dfc2aa46956cf16e05ff875edc4a964c/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/v1/RunInfoUtilsV1.java#L37)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please add this in ExecutionModeUtils
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 78 at r3](https://reviewable.io/reviews/harness/harness-core/53023#-NeqyVnbBLDu7LaM8yzv:-NeqyVnbBLDu7LaM8yzw:b-6zhe6r) ([raw file](https://github.com/harness/harness-core/blob/c961fd2dd6c6216d1217166d0a7729a8d79da29b/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L78)):*
> ```Java
>       for (Level nodeLevel : nodeExecution.getAmbiance().getLevelsList()) {
>         if (Objects.equals(nodeLevel.getSetupId(), startingNodeId)) {
>           if (OrchestrationUtils.isStageNode(nodeExecution)) {
> ```

Can we move this condition at the top and loop only if this is true?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53023)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by rathodmeetsatish** [comment]
trigger uts

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53023)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 78 at r3](https://reviewable.io/reviews/harness/harness-core/53023#-NeqyVnbBLDu7LaM8yzv:-NerFTvnBEqebmiAstmE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c961fd2dd6c6216d1217166d0a7729a8d79da29b/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L78)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we move this condition at the top and loop only if this is true?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53023)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by karansaraswat19 — APPROVED** [review]

**Comment by rathodmeetsatish** [comment]
trigger review

**Pull request merged**
