### PR TITLE
feat: [SRM-15247]: Map Analyze Deployment report  to the deployment event

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Describe your changes

While registering deployment activity, will use stageId as well to find if the activity is unique or not

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51564)

### CODE REVIEW

**Comment by karansaraswat19** [comment]
trigger uts

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51564)* status: Some of the checks are too old. 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/51564#-NcQft_b8b8UtccxXNGG:-NcQft_b8b8UtccxXNGH:b-kvskyn) ([raw file](https://github.com/harness/harness-core/blob/8acf5ea46797e310d67f732702a89bc5e1647183/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java#L62)):*
> ```Java
>       Instant endTime);
> 
>   void mapSRMAnalysisExecutionToDeploymentActivities(
> ```

there will be single deployment activity right?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java` line 427 at r1](https://reviewable.io/reviews/harness/harness-core/51564#-NcQgX3I8wAfBz7hp6Bc:-NcQgX3I8wAfBz7hp6Bd:b-doabjt) ([raw file](https://github.com/harness/harness-core/blob/8acf5ea46797e310d67f732702a89bc5e1647183/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java#L427)):*
> ```Java
>             .filter(ActivityKeys.type, ActivityType.DEPLOYMENT)
>             .asList();
>     if (isNotEmpty(deploymentActivities)) {
> ```

Just have a common method for both. where you pass the analysis entity and activity.(fetching of deployment activity or analysis entity can be inside these methods).

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51564)* status: Some of the checks are too old. 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/51564#-NcQft_b8b8UtccxXNGG:-NcQp07t5fBGXt2uQr-w:b-jfrgpn) ([raw file](https://github.com/harness/harness-core/blob/8acf5ea46797e310d67f732702a89bc5e1647183/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java#L62)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

there will be single deployment activity right?
</blockquote></details>

there can be multiple in case of two sequential deployments and then analysis step

**Comment by karansaraswat19** [comment]
trigger uts

**Comment by karansaraswat19** [comment]
trigger uts

**Review by Varsha-lalwani — APPROVED** [review]

**Pull request merged**
