### PR TITLE
fix: [CDS-25579]: Fix Azure Download Artifacts

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30596)

### CODE REVIEW

**Comment by puthrayaharness** [comment]
trigger messagecheck

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30596#-:-MvNV1qt6okrH9Gfw8U1:bnfp4nl)* status: :shipit: complete! ✓

**Review by jelenaHarness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30596)* status: :shipit: complete! ✓

**Review by jelenaHarness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30596)* status: :shipit: complete! ✓

**Review by ivan-83 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30596)* status: :shipit: complete! ✓

**Review by jelenaHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30596)* status: :shipit: complete! ✓

**Pull request merged**
