### PR TITLE
[fix]: [PIE-6746]: Fixing ste-strategy node coming in layoutNodeMap for above graph and crashing UI

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40952)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40952)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/build.properties` line 4 at r2](https://reviewable.io/reviews/harness/harness-core/40952#-NICtfyU4saa5ba7jpAH:-NICtfyU4saa5ba7jpAI:b-avtqls) ([raw file](https://github.com/harness/harness-core/blob/6453469b5b32df51a48c100f55c1b6f110de85f0/pipeline-service/build.properties#L4)):*
> ```INI
> build.minorVersion=16
> build.number=77200
> build.patch=001
> ```

wrong version updated, its below one
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/40952#-NICtieK5-wCcV_4of7n:-NICtieK5-wCcV_4of7o:b-wgk70b) ([raw file](https://github.com/harness/harness-core/blob/6453469b5b32df51a48c100f55c1b6f110de85f0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L36)):*
> ```Java
> public class ExecutionSummaryUpdateUtils {
>   public static boolean addStageUpdateCriteria(Update update, NodeExecution nodeExecution) {
>     if (!OrchestrationUtils.isStageNode(nodeExecution)) {
> ```

add comment why stage check is there

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/build.properties` line 4 at r2](https://reviewable.io/reviews/harness/harness-core/40952#-NICtfyU4saa5ba7jpAH:-NICuXYd0Jmc5bmMGgBL:b-ql4yjp) ([raw file](https://github.com/harness/harness-core/blob/6453469b5b32df51a48c100f55c1b6f110de85f0/pipeline-service/build.properties#L4)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

wrong version updated, its below one
</blockquote></details>

I updated the below one only. The buildNumber matadata PR checks is checking for patch. So updated both now. patch to pass the check and patchNumber to increase the version.

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40952)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/40952#-NICtieK5-wCcV_4of7n:-NICvJ1U9-seUpB1bNql:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6453469b5b32df51a48c100f55c1b6f110de85f0/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/ExecutionSummaryUpdateUtils.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comment why stage check is there
</blockquote></details>

Done.

**Review by ankittiwari-harness — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40952#-:-NICtzDGEgzZyYS5Uk-l:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40952)* status: 2 file(s) to review.

**Pull request closed without merging**
