### PR TITLE
fix: [CDS-73695]: Added handling for expire events to send interrupt events for proper handling and closing of streams

### PR DESCRIPTION
**Pull request by Y0709**
Context -- The logs for the shell script step were not retaining after the step got expired. This was happening as were not sending the event to close all open streams after the step was getting expired. We have fixed that issue here by pulishing expire event to interrupt event publisher and created a callback for step response.

Also fixed 2 more small issues as in abort handler we were not marking the interrupt to be processed successfully or unsucessfully after interrupt is processed and for user marked failure interrupt were not updating interrupt history in node execution.
Screenshot 2023-07-19 at 4 11 36 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 14 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptCallback.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_hlMdJ7UxnO_O117BB:-N_hlMdJ7UxnO_O117BC:b-qmysyh) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptCallback.java#L25)):*
> ```Java
> 
> @OwnedBy(CDC)
> public class ExpireAllInterruptCallback implements OldNotifyCallback {
> ```

@archit-harness shall we use only one callback for different *AllInterruptCallbacks? We have multiple callbacks like  `AbortAllInterruptCallback`, `UserMarkedFailAllInterruptCallback` and now one more this `ExpireAllInterruptCallback`. And all these have same work to do. Simply mark the interrupt Successful or Unsuccessful.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_i3dqH2Ucx2-5y_Fmo:-N_i3dqIDs69xpHjvsqd:b-ihlva8) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L67)):*
> ```Java
> 
>   void expireNode(Map<String, ResponseData> response) {
>     NodeExecution nodeExecution = nodeExecutionService.get(nodeExecutionId);
> ```

should use projection to get unit progresses and id only
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptCallback.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_hlMdJ7UxnO_O117BB:-N_i3sORCObz0uiVpJ4l:b-hm7gtq) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptCallback.java#L25)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness shall we use only one callback for different *AllInterruptCallbacks? We have multiple callbacks like  `AbortAllInterruptCallback`, `UserMarkedFailAllInterruptCallback` and now one more this `ExpireAllInterruptCallback`. And all these have same work to do. Simply mark the interrupt Successful or Unsuccessful.
</blockquote></details>

Yes @yuvrajharness can you make the same change? renmae to AllInterruptCallback and add comments to top of it what does it do?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_iGem95h-dU4JTZkKC:-N_iGem95h-dU4JTZkKD:b-wmxko1) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java#L50)):*
> ```Java
> @OwnedBy(PIPELINE)
> @Slf4j
> public class ExpiryHelper {
> ```

create abstract class out of it and use in abort, expire, and user marked failure

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 13 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_i3dqH2Ucx2-5y_Fmo:-N_mJiD4AGYt2LUiDTDu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

should use projection to get unit progresses and id only
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_iGem95h-dU4JTZkKC:-N_mJkMkAihH-DxQnFK7:bz93xqw) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java#L50)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

create abstract class out of it and use in abort, expire, and user marked failure
</blockquote></details>

Can we do that in a seperate pr for refactoring this part of code.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptCallback.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/50694#-N_hlMdJ7UxnO_O117BB:-N_mJs1EBktjSRVw0L4L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1e3652c5392c22ff68001aa39005d210cf0f70f4/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptCallback.java#L25)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Yes @yuvrajharness can you make the same change? renmae to AllInterruptCallback and add comments to top of it what does it do?
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 13 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/kryo/OrchestrationKryoRegistrar.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/50694#-N_mNoU76Kj-kVprNNOK:-N_mNoU76Kj-kVprNNOL:bsizq72) ([raw file](https://github.com/harness/harness-core/blob/fe960050f6f2b637f5edc37bb55aa571d02e7966/pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/kryo/OrchestrationKryoRegistrar.java#L56)):*
> ```Java
>     kryo.register(InterruptProcessingFailedException.class, 87019);
>     kryo.register(ExpiryInterruptCallback.class, 87020);
>     kryo.register(ExpireAllInterruptCallback.class, 87021);
> ```

lets not delete registration

**Comment by Y0709** [comment]
trigger uts

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 15 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/kryo/OrchestrationKryoRegistrar.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/50694#-N_mNoU76Kj-kVprNNOK:-N_mzZK7BX4yCv9I6lLR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fe960050f6f2b637f5edc37bb55aa571d02e7966/pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/kryo/OrchestrationKryoRegistrar.java#L56)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

lets not delete registration
</blockquote></details>

Done.

**Comment by Y0709** [comment]
trigger uts

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n72Z92nJHdiVjOSWA:-N_n72Z92nJHdiVjOSWB:byp35bf) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L58)):*
> ```Java
>   @Override
>   public void notifyTimeout(Map<String, ResponseData> responseMap) {
>     log.error("Expire event timed out for nodeExecutionId {} and interrupt {}", nodeExecutionId, interruptId);
> ```

shouldn't this be "info" log? We should put error log only if its an error for us or some use-case which couldn't be handled as expected.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7Aoi0D2tXmYUfnH3:-N_n7Aoi0D2tXmYUfnH4:byp35bf) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L64)):*
> ```Java
>   @Override
>   public void notifyError(Map<String, ResponseData> response) {
>     log.error("Expire event failed for nodeExecutionId {} and interrupt {}", nodeExecutionId, interruptId);
> ```

shouldn't this be "info" log? We should put error log only if its an error for us or some use-case which couldn't be handled as expected.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortInterruptHandler.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7LxP2UdvH99Q6b3a:-N_n7LxP2UdvH99Q6b3b:bkw8sgb) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortInterruptHandler.java#L71)):*
> ```Java
> 
>     } catch (Exception ex) {
>       interruptService.markProcessed(interrupt.getUuid(), PROCESSED_UNSUCCESSFULLY);
> ```

not logging exception here?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java` line 130 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7ZwU0GFzu9C_pxCq:-N_n7ZwU0GFzu9C_pxCr:bm4vq08) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java#L130)):*
> ```Java
> 
>     } catch (Exception ex) {
>       log.info("Exception occurred while expiring instance marking interrupt as PROCESSED_UNSUCCESSFULLY");
> ```

should be error log?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java` line 126 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7cSj11sC6Zz9rwDn:-N_n7cSj11sC6Zz9rwDo:b-kkxq2y) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java#L126)):*
> ```Java
>         log.info("Trying to expire discontinuing instance {}", discontinuingNodeExecution.getUuid());
>         handleMarkedInstance(discontinuingNodeExecution, updatedInterrupt);
>         notifyIds.add(discontinuingNodeExecution.getUuid() + "|" + updatedInterrupt.getUuid());
> ```

This way of creating a id seems to be used at many places. Shouldn't this come from a util?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java` line 88 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n89mlCpH9LPn_wIkl:-N_n89mlCpH9LPn_wIkm:b1q1xbv) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java#L88)):*
> ```Java
>           InterruptType.MARK_EXPIRED, "Expiry failed for NodeExecutionId: " + nodeExecution.getUuid(), ex);
>     } catch (Exception e) {
>       log.error("Error in discontinuing", e);
> ```

seems pretty vague log, shouldn't we add more info message to the log for better interpretation?

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 16 file(s) to review. 1 change requests. 5. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n72Z92nJHdiVjOSWA:-N_nBUoj4Ke0zgjRObm1:b5w18rb) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L58)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't this be "info" log? We should put error log only if its an error for us or some use-case which couldn't be handled as expected.
</blockquote></details>

Will be creating another pr for refactoring code around this part. Will fix this in that.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7Aoi0D2tXmYUfnH3:-N_nBbAY3mSwfOwlEoc6:b-usfwdf) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/ExpiryInterruptCallback.java#L64)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't this be "info" log? We should put error log only if its an error for us or some use-case which couldn't be handled as expected.
</blockquote></details>

This should fine as we are notifying error only.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortInterruptHandler.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7LxP2UdvH99Q6b3a:-N_nBiNCEYYgXr7l7LTi:b-lh3n6u) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/AbortInterruptHandler.java#L71)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

not logging exception here?
</blockquote></details>

We are throwing the ex again which will come ti UI so no need here
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java` line 126 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7cSj11sC6Zz9rwDn:-N_nBmu-6jcFpgoomS9s:b5w18rb) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java#L126)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This way of creating a id seems to be used at many places. Shouldn't this come from a util?
</blockquote></details>

Will be creating another pr for refactoring code around this part. Will fix this in that.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java` line 130 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n7ZwU0GFzu9C_pxCq:-N_nBnpeEKi0Xy7ZbAY0:b5w18rb) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/ExpireAllInterruptHandler.java#L130)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

should be error log?
</blockquote></details>

Will be creating another pr for refactoring code around this part. Will fix this in that.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java` line 88 at r5](https://reviewable.io/reviews/harness/harness-core/50694#-N_n89mlCpH9LPn_wIkl:-N_nBolf3K_L7ECygZne:b5w18rb) ([raw file](https://github.com/harness/harness-core/blob/df3318bcc3e885c5d2ce3e99c83a3789afe692b2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/ExpiryHelper.java#L88)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

seems pretty vague log, shouldn't we add more info message to the log for better interpretation?
</blockquote></details>

Will be creating another pr for refactoring code around this part. Will fix this in that.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 6 of 13 files at r3, 7 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50694)* status: 4. unresolved discussions.

**Comment by Y0709** [comment]
trigger review

**Comment by Y0709** [comment]
trigger messagecheck

**Pull request merged**
