### PR TITLE
fix: [CDS-85746]: adds null handling for looping strategy

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
fix: [CDS-85746]: adds handling for looping strategy for stage node

Issue: when looping strategy was sent as null, it was being converted to `<+input>` resulting into NPE.

Changes: check for null added on the UUID.

Testing: Done on local.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-85746]: https://harness.atlassian.net/browse/CDS-85746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)

### CODE REVIEW

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 86 at r3](https://reviewable.io/reviews/harness/harness-core/56292#-NlPx0wj3i2JmOcA1AHi:-NlPx0wj3i2JmOcA1AHj:b-c1nlkv) ([raw file](https://github.com/harness/harness-core/blob/af1f3bb3879f91841e975df303d1a9a943dff2ab/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L86)):*
> ```Java
>   public boolean isWrappedUnderStrategy(YamlField yamlField) {
>     YamlField strategyField = yamlField.getNode().getField(YAMLFieldNameConstants.STRATEGY);
>     return strategyField != null && strategyField.getNode().getUuid() != null;
> ```

what if ".getNode()" is null?

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 86 at r3](https://reviewable.io/reviews/harness/harness-core/56292#-NlPx0wj3i2JmOcA1AHi:-NlWpnGU35651MdAEtCr:b-y00dlo) ([raw file](https://github.com/harness/harness-core/blob/af1f3bb3879f91841e975df303d1a9a943dff2ab/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L86)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I would recommend to have a util method to fetch / validate uuid from it. Then simply we call YamlUtils.getUUID(strategyField) or .isUUIDPresent(strategyField) and it automatically does all null checks and returns expected value.
We could also take Field argument instead of making specific methods. That makes it much more scalable.
cc @sahilhindwani-harness
</blockquote></details>

Added check for ".getNode()" within a new method inside YamlUtils.

**Review by sandeshsalunkhegh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 86 at r3](https://reviewable.io/reviews/harness/harness-core/56292#-NlPx0wj3i2JmOcA1AHi:-NlWq1HL6ODKxEYhXmbe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/af1f3bb3879f91841e975df303d1a9a943dff2ab/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L86)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

Added check for ".getNode()" within a new method inside YamlUtils.
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 336 at r4](https://reviewable.io/reviews/harness/harness-core/56292#-NlgVlJEAj7LAQj7ISHI:-NlgVlJEAj7LAQj7ISHJ:b-lo6rxz) ([raw file](https://github.com/harness/harness-core/blob/9327bdd2c441ea08506ec8b441c76eb91bba1620/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L336)):*
> ```Java
>   }
> 
>   public boolean isUUIDPresent(YamlField strategyField) {
> ```

Please add test for this function.

**Review by sandeshsalunkhegh — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: 5 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 336 at r4](https://reviewable.io/reviews/harness/harness-core/56292#-NlgVlJEAj7LAQj7ISHI:-Nm5vx7G6Y3gFkeeFchr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9327bdd2c441ea08506ec8b441c76eb91bba1620/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L336)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Please add test for this function.
</blockquote></details>

Done.

**Comment by sandeshsalunkhegh** [comment]
trigger ut0, ut5, ut6, ut7, ut8, ut9

**Comment by sandeshsalunkhegh** [comment]
trigger ut7, ut9

**Comment by sahilhindwani-harness** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java` line 91 at r5](https://reviewable.io/reviews/harness/harness-core/56292#-NmA44MW7dfw-cfWpZs9:-NmA44MW7dfw-cfWpZsA:bqush97) ([raw file](https://github.com/harness/harness-core/blob/f9edb61903bf62c2e447e4769e718a00b10dabce/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy/StrategyUtils.java#L91)):*
> ```Java
>   public boolean isWrappedUnderStrategy(YamlNode yamlField) {
>     YamlField strategyField = yamlField.getField(YAMLFieldNameConstants.STRATEGY);
>     return YamlUtils.isUUIDPresent(strategyField);
> ```

should'nt this be kept the same?  Why to change this

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56292)* status: <span>:shipit:</span> complete! ✓

**Pull request merged**
