### PR TITLE
techdebt: [CDS-77999]: Add a bulk ack API for events framework

### PR DESCRIPTION
**Pull request by hextechpal**
## Describe your changes
Modified the acknowledge method from the vents framework to take a list of messageIds rather than a single messageId. This helps us avoid multiple API calls to redis. Adopted the same for graph consumer

Test

Ran Complete pipeline executions and checked if messages are getting acknowledged for multiple stream using (bulk/not bulk)

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)

### CODE REVIEW

**Comment by hextechpal** [comment]
trigger uts

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-NcuEdyT7cLNN4M96rnU:bo8sdgf) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
> ```Java
>     } finally {
>       if (EmptyPredicate.isNotEmpty(readResult.tobeAcked)) {
>         log.info("Bulk acknowledging Details: {}", readResult);
> ```

can we bulk ack before submitting to the executor service? as those events waiting is not giving any benefit

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 8 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by hextechpal** [comment]
trigger uts

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-NcvEbJd80aqMceT2l4c:bryui) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we bulk ack before submitting to the executor service? as those events waiting is not giving any benefit
</blockquote></details>

The main code is just submitting to executor service which should be fast, This also leaves room for error handling if anything fails.

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095#-:-NcvhMPIBfVlrUvT8s4t:bnfp4nl)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 6 file(s) to review. 1 change requests. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-Ncw4pYjBclKtNm1E8_N:b8luc9i) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

The main code is just submitting to executor service which should be fast, This also leaves room for error handling if anything fails.
</blockquote></details>

When we implement fixed queues -> then even though we have read graph events -> they will be waiting unnecessary, and would be reclaimed by other consumers.

so at a time 2 consumers would be consuming if queue limit is reached

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-NcwT_2j1aAw6deWOfkw:bdlhhsb) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

When we implement fixed queues -> then even though we have read graph events -> they will be waiting unnecessary, and would be reclaimed by other consumers.

so at a time 2 consumers would be consuming if queue limit is reached
</blockquote></details>

PP wouldnt this issue still come if we are bulk ack first thing in executor service, as still this is submitted to executor service?

**Review by piyush-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by rohitk-h — DISMISSED** [review]

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-NczeYGS93AahOOEhb7O:b6dj5b7) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

PP wouldnt this issue still come if we are bulk ack first thing in executor service, as still this is submitted to executor service?
</blockquote></details>

Have changed this impl

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/graph/GraphUpdateRedisConsumer.java` line 119 at r3](https://reviewable.io/reviews/harness/harness-core/52095#-NczmMJB3RH4CZXKfwlF:-NczmMJB3RH4CZXKfwlG:b-azph02) ([raw file](https://github.com/harness/harness-core/blob/d80ea51165369a7f52a7eb2512ac41cc35f604e7/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/graph/GraphUpdateRedisConsumer.java#L119)):*
> ```Java
>     executorService.submit(() -> {
>       try {
>         if (EmptyPredicate.isNotEmpty(readResult.tobeAcked)) {
> ```

PP if we still ack the messages inside executor service, wouldn't the same issue occur for fixed queue

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-NczooeLDGdlegMUDWPT:ba9uanw) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

Have changed this impl
</blockquote></details>

What if you fail to ack in main thread ?

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52095)* status: 1 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/52095#-NcuEdyS0eZL8WnLk6Z5:-Nczp5Wl5gNADu9ZKiF9:b-9ydev9) ([raw file](https://github.com/harness/harness-core/blob/a31451a06bc6067b217c0d731a8ac2de37ecaf59/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateRedisConsumer.java#L128)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

What if you fail to ack in main thread ?
</blockquote></details>

Also if threads are occupied then we wait to ack this is exactly similar to we wait to process

**Comment by hextechpal** [comment]
trigger uts

**Comment by hextechpal** [comment]
trigger ut0

**Comment by hextechpal** [comment]
trigger review

**Pull request merged**
