### PR TITLE
feat: [IDP-1816][IDP-1817]: Adding two steps in IDP stage - create ca…

### PR DESCRIPTION
**Pull request by devesh-harness**
…talog and slack notify

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56638)

### CODE REVIEW

**Comment by devesh-harness** [comment]
trigger smartchecks

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut0, ut6

**Comment by devesh-harness** [comment]
trigger uts

**Review by harshjain12 — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger uts

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56638)* status: 34 file(s) to review. 1 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/idp/utils/IDPStepUtils.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/56638#-NlTiST5EaHi9z41I0e4:-NlTiST5EaHi9z41I0e5:b-96ur3j) ([raw file](https://github.com/harness/harness-core/blob/0feeb97b25af3a5fd2d63d19bf3c2ca8f4446461/332-ci-manager/service/src/main/java/io/harness/idp/utils/IDPStepUtils.java#L215)):*
> ```Java
> 
>     PluginServiceImpl.setMandatoryEnvironmentVariable(envVarMap, SLACK_ID,
>         resolveStringParameterV2("channelId", Constants.SLACK_NOTIFY, identifier, stepInfo.getSlackId(), true));
> ```

Should we have this as slackId instead? to keep it consistent with stepInfo



_Code quote:_
```Java
channelId
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56638)* status: 34 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/idp/utils/IDPStepUtils.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/56638#-NlTiST5EaHi9z41I0e4:-NlTjT2f17Kg3N9vdNSO:b-hqz1fe) ([raw file](https://github.com/harness/harness-core/blob/0feeb97b25af3a5fd2d63d19bf3c2ca8f4446461/332-ci-manager/service/src/main/java/io/harness/idp/utils/IDPStepUtils.java#L215)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Should we have this as slackId instead? to keep it consistent with stepInfo
</blockquote></details>

yes i think this got missed while updating it, this will not cause any issue will fix in next PR.

**Review by vikyathharekal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56638#-:-NlTlCMU58oHIMYxe85f:bnfp4nl)* status: 34 file(s) to review. 1. unresolved discussions.

**Comment by devesh-harness** [comment]
trigger ut4, ut5

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
