### PR TITLE
[fix]: [pl-28198] HashiCorpVault - Throw an exception if secret delet…

### PR DESCRIPTION
**Pull request by Raghav-Murali**
…ion fails

## Describe your changes

This PR handles the `HashiCorpVaultRuntimeException` that is thrown while deleting a secret from the HashiCorp Vault.

While deleting the secret in HashiCorp vault if HashiCorpVaultRuntimeException is thrown due to invalid vault configuration then the handler catches the exception and logs it but doesn’t propagate it back to the manager. Thus the UI is unaware of the deletion failure and assumes that the deletion of secret succeeded and removes the secret from the UI.

Test Scenario -

1. Create a HashiCorp secret manager connector (with Root token) and add a secret in HashiCorp Vault.

2. Update the HashiCorp secret manager with invalid token which will cause the connection validation to fail.

3. Now delete the previously stored secret in HashiCorp Vault. The delegate secrets management won’t be able to delete the secret due to the invalid token and throws an HashiCorpVaultRuntimeException

4. However, since this exception is just logged and not propagated back to the NG Manager from the delegate. The UI assumes that the secret was deleted and removes it however its not deleted in Hashicorp Vault.

The expected outcome is the secret not being removed from the UI since deletion of secret failed. Thus, rather than logging the exception it needs to be propagated back to the UI.

## Checklist
- [ Yes ] I've documented the changes in the PR description. - [PL-28198](https://harness.atlassian.net/browse/PL-28198) contains the detailed info on the issue.
- [ Yes ] I've tested this change either in PR or local environment. - Tested in local test environment.
- [ N/A ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37554)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37554)

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37554)* status: :shipit: complete! ✓

**Review by gn-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37554)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 504 at r4](https://reviewable.io/reviews/harness/harness-core/37554#-ND1Xl5G39oxcd0gIDn9:-ND1Xl5H2bOzBdZohlSt:b-hr493j) ([raw file](https://github.com/harness/harness-core/blob/b09500969334a451dd3dc62430675d490b072f72/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L504)):*
> ```Java
>     // Note - Ideally the return below should be a logical AND of whether secret was deleted
>     // in remote vault in deleteSecretInSecretManager and deletion in encrypted data DAO below.
>     // But for now to ensure local deletion of record goes through just returning the boolean
> ```

nit: add some punctuation

"But for now to ensure local deletion of record goes through, just returning the boolean.."
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 522 at r4](https://reviewable.io/reviews/harness/harness-core/37554#-ND1Y9XzEeYnZQpPu27Q:-ND1Y9XzEeYnZQpPu27R:bfncb35) ([raw file](https://github.com/harness/harness-core/blob/b09500969334a451dd3dc62430675d490b072f72/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L522)):*
> ```Java
>         if (!vaultEncryptorsRegistry.getVaultEncryptor(secretManagerConfig.getEncryptionType())
>                  .deleteSecret(accountIdentifier, encryptedData, secretManagerConfig)) {
>           log.error("Secret was not deleted on the remote vault");
> ```

add some details like account/secret config etc



_Code quote:_
```Java
ecret was not deleted on the remote vault
```

**Review by Raghav-Murali — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37554)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 504 at r4](https://reviewable.io/reviews/harness/harness-core/37554#-ND1Xl5G39oxcd0gIDn9:-ND4yi5Z7uUxmplOtT69:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b09500969334a451dd3dc62430675d490b072f72/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L504)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: add some punctuation

"But for now to ensure local deletion of record goes through, just returning the boolean.."
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 522 at r4](https://reviewable.io/reviews/harness/harness-core/37554#-ND1Y9XzEeYnZQpPu27Q:-ND4yoOB8xhWzzUmxXy6:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b09500969334a451dd3dc62430675d490b072f72/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L522)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

add some details like account/secret config etc
</blockquote></details>

Done

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37554)* status: :shipit: complete! ✓

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37554)* status: :shipit: complete! ✓

**Pull request merged**
