### PR TITLE
feat: [CDS-36237]: Add variable creator for K8s, Helm, Tf steps integration test changes

### PR DESCRIPTION
**Pull request by abosii-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32365)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger ft2

**Review by archit-harness — COMMENTED** [review]
> Reviewed 57 of 91 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32365)* status: 34 file(s) to review. 0 of 1 approvals obtained.

**Comment by abosii-harness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
Add uuid hidden field in all pojos of your step

> Reviewed 31 of 91 files at r1, 9 of 14 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32365#-:-N0_nZ8UDnD9XbL5ZhF7:b-noxurk)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformVarFileWrapper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/32365#-N0_nWHmCN-umINZ-Bqd:-N0_nWHn3mbJ3tdHp8Mp:bn7p7w4) ([raw file](https://github.com/harness/harness-core/blob/662d81bbcc1f14dfb7cbdac67cac8121410e0e26/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformVarFileWrapper.java#L25)):*
> ```Java
> public class TerraformVarFileWrapper {
>   @Getter(onMethod_ = { @ApiModelProperty(hidden = true) }) @ApiModelProperty(hidden = true) String uuid;
> ```

this should be added back



_Code quote:_
```Java
  @Getter(onMethod_ = { @ApiModelProperty(hidden = true) }) @ApiModelProperty(hidden = true) String uuid;
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32365)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32365)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 76 of 91 files at r1, 12 of 14 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32365)* status: :shipit: complete! ✓

**Pull request merged**
