### PR TITLE
[feat]: [PL-28189]: Adds implementation for connectors resource using spec first

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37501)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 34 Issues 
* Code issue 11 Code issues 
* Anti-pattern 23 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37501)

**Comment by ashishsanodia-harness** [comment]
trigger ti4

**Comment by ashishsanodia-harness** [comment]
trigger ti4

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger ti0

**Comment by ashishsanodia-harness** [comment]
trigger ti1

**Comment by ashishsanodia-harness** [comment]
trigger ti2

**Comment by ashishsanodia-harness** [comment]
trigger ti2

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 47 files at r1, 4 of 43 files at r2, 37 of 58 files at r3, 29 of 37 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37501)* status: 90 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java` line 113 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSY4lS4w-Wu2RbjYYL:-NDSY4lS4w-Wu2RbjYYM:b-cvefzu) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java#L113)):*
> ```Java
>   public Response getAccountScopedConnectors(
>       Boolean recursive, String searchTerm, Integer page, Integer limit, String account) {
>     accessControlClient.checkForAccessOrThrow(
> ```

Can use annotation in place of this call.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java` line 154 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSbkcP295bi3O8A0Y9:-NDSbkcQ57PkVE8aYg6d:b8sukif) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java#L154)):*
> ```Java
>     }
>     if (nonNull(connectorRequest.getConnector().getOrg()) || nonNull(connectorRequest.getConnector().getProject())) {
>       throw new InvalidRequestException("Account scoped request is having non null org or project", USER);
> ```

This message is generic and will be applicable for a lot of account scope API. Can be defined as constant.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java` line 78 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSnHJQ-bbfg_dZ3hQB:-NDSnHJQ-bbfg_dZ3hQC:b-dxnymc) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java#L78)):*
> ```Java
>   @Override
>   public Response deleteProjectScopedConnector(@OrgIdentifier String org, @ProjectIdentifier String project,
>       @ResourceIdentifier String connector, @AccountIdentifier String account) {
> ```

Where is not empty/blank condition checked for scope parameters (acc, org, proj)?
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java` line 86 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSkQY24CpEhPD4aRU4:-NDSkQY24CpEhPD4aRU5:bfdnkkr) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java#L86)):*
> ```Java
>       throw new NotFoundException(String.format("Connector with identifier [%s] not found", connector));
>     }
>     boolean deleted = connectorService.delete(account, org, null, connector);
> ```

Project not passed here.
Looks like UT could not catch it.

**Comment by ashishsanodia-harness** [comment]
trigger authorcheck

**Comment by ashishsanodia-harness** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java` line 113 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSY4lS4w-Wu2RbjYYL:-NDVg-Fp1HtrNN-TBRjD:bx9lz04) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java#L113)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Can use annotation in place of this call.
</blockquote></details>

Added annotation

**Comment by ashishsanodia-harness** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java` line 154 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSbkcP295bi3O8A0Y9:-NDVg4GR3HSOAaj-0bqB:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/AccountConnectorApiImpl.java#L154)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

This message is generic and will be applicable for a lot of account scope API. Can be defined as constant.
</blockquote></details>

Done

**Comment by ashishsanodia-harness** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java` line 78 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSnHJQ-bbfg_dZ3hQB:-NDVg6Tw5PhkUwQiJ7jW:b-rd07ox) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java#L78)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Where is not empty/blank condition checked for scope parameters (acc, org, proj)?
</blockquote></details>

It's already coming as part of path param so not needed

**Comment by ashishsanodia-harness** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java` line 86 at r5](https://reviewable.io/reviews/harness/harness-core/37501#-NDSkQY24CpEhPD4aRU4:-NDVgGf04h4QUyajl_dV:b-12sm0b) ([raw file](https://github.com/harness/harness-core/blob/2679e992e193f842ac4119a1de0227bc46eaad5c/440-connector-nextgen/src/main/java/io/harness/connector/apis/resource/ProjectConnectorApiImpl.java#L86)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Project not passed here.
Looks like UT could not catch it.
</blockquote></details>

Done, Added unit tests as well for this.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37501)* status: 91 file(s) to review. 1 of 2 approvals obtained.

**Review by mankrit-singh — APPROVED** [review]
> Reviewed 12 of 47 files at r1, 4 of 43 files at r2, 36 of 58 files at r3, 29 of 37 files at r4, 2 of 8 files at r5, 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37501)* status: :shipit: complete! ✓

**Pull request merged**
