### PR TITLE
[feat]: [CI-5801]: Security fixes for CI-SCM service

### PR DESCRIPTION
**Pull request by anuragmadnawat**
This commit upgrades the base image and go version for CI-SCM service.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40161)

### CODE REVIEW

**Review by hemanthmantri — APPROVED** [review]

**Comment by vistaarjuneja** [comment]
Curious how this gets reflected since we use bazelisk to build the binaries. Wouldn't we have to change the go version in the bazel workspace file as well?

**Comment by anuragmadnawat** [comment]
> Curious how this gets reflected since we use bazelisk to build the binaries. Wouldn't we have to change the go version in the bazel workspace file as well?

I saw this in the bazel workspace file 
`go_register_toolchains(version = "1.18.1")`

How was the scm service able to build and run if it has a higher version?

**Comment by vistaarjuneja** [comment]
@anuragmadnawat my guess is it's not using that version at all, since it relies on the bazelisk version. @shubham149 can you confirm which version would be used here?

**Comment by anuragmadnawat** [comment]
@shubham149 @vistaarjuneja @hemanthmantri 
So what is the exact ask from these tickets: https://harness.atlassian.net/browse/CI-5801, https://harness.atlassian.net/browse/CI-5802?

**Comment by USB-05** [comment]
trigger sswc

**Review by hemanthmantri — APPROVED** [review]

**Review by shubham149 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40161#-:-NH83ddw1OlU_72gLTC9:bnfp4nl)* status: :shipit: complete! ✓

**Comment by shubham149** [comment]
Make sure that docker build is working or not on the scm image

**Comment by anuragmadnawat** [comment]
> Make sure that docker build is working or not on the scm image

Yes it is working

**Pull request merged**
