### PR TITLE
[feat]: [CDS-70098]: Add required info for PPRB to service dashboard API

### PR DESCRIPTION
**Pull request by namanvermah**
Stage execution details and rollback status will be used to check whether the new rollback button is to be disabled or not. 
The instance key and infra mapping ID will be used in the check and trigger APIs for PPRB

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48282)

### CODE REVIEW

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48282)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48282)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger uts

**Comment by namanvermah** [comment]
trigger uts

**Comment by namanvermah** [comment]
trigger uts

**Comment by namanvermah** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
