### PR TITLE
[fix]: [CDP-19915]: handling ClientToolsDownloadDisabled case for custom kustomize binary

### PR DESCRIPTION
**Pull request by namantalaycha10**
…tomize binary

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 658 at r3](https://reviewable.io/reviews/harness/harness-core/30552#-Mv3WUpL72sFuD972UwD:-Mv3WUpL72sFuD972UwE:brdsi1z) ([raw file](https://github.com/harness/harness-core/blob/2a983f74c567f6d82f8c46edcabe24a018789288/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L658)):*
> ```Java
>         startProfileCheck();
>       }
>       if (isClientToolsInstallationFinished()) {
> ```

Can we check just for delegateConfiguration.isClientToolsDownloadDisabled()?
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 759 at r3](https://reviewable.io/reviews/harness/harness-core/30552#-Mv3WO-mEK5vJ2JppQRY:-Mv3WO-mEK5vJ2JppQRZ:b-27mgks) ([raw file](https://github.com/harness/harness-core/blob/2a983f74c567f6d82f8c46edcabe24a018789288/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L759)):*
> ```Java
>     }
>   }
>   private void setupUp(DelegateConfiguration delegateConfiguration) {
> ```

Can we rename this method to setupDefaultPaths and move it to InstallUtils?

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 658 at r3](https://reviewable.io/reviews/harness/harness-core/30552#-Mv3WUpL72sFuD972UwD:-Mv3ZBts4ARHoczmdt3d:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a983f74c567f6d82f8c46edcabe24a018789288/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L658)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we check just for delegateConfiguration.isClientToolsDownloadDisabled()?
</blockquote></details>

Done.

**Comment by namantalaycha10** [comment]
> _[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 1212 at r4](https://reviewable.io/reviews/harness/harness-core/30552#-Mv3moPe5wgHIGho6el1:-Mv3moPg8cFcTLUqPomz:b5r4kkb) ([raw file](https://github.com/harness/harness-core/blob/4f6291cf95b5ed559c5d9be963866002623f1178/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L1212)):_
> 
> > ```java
> >   }
> > 
> >   public static void setupDefaultPaths(DelegateConfiguration delegateConfiguration) {
> > ```
> 
> Are we only handling Kustomize now? won't customer come again to use with issue of other custom binary not picked later?
> 
> _Code quote (from 260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java):_
> 
> ```java
> setupDefaultPaths(delegateConfiguration);
> ```

@tchaurasiya yes, current we are only doing this for Kustomize binary to unblock customer as soon as possible 
we can plan our effort for rest for the binaries after this i will raise a ticket for that

**Comment by tchaurasiya** [comment]
___
*[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 195 at r4](https://reviewable.io/reviews/harness/harness-core/30552#-Mv3snwGBzmIvX9bW8Pe:-Mv3snwH4pyjlb5eCd7C:b-7yr0r6) ([raw file](https://github.com/harness/harness-core/blob/4f6291cf95b5ed559c5d9be963866002623f1178/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L195)):*
> ```Java
>   }
> 
>   public static String getKustomizePath() {
> ```

can we remove this. Seems like its of no use now.
 But can be confusing for future.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 3 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, line 195 at r4](https://reviewable.io/reviews/harness/harness-core/30552#-Mv3snwGBzmIvX9bW8Pe:-Mv4-yO98PqIjyhGwn67:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4f6291cf95b5ed559c5d9be963866002623f1178/960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java#L195)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

can we remove this. Seems like its of no use now.
 But can be confusing for future.
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30552)* status: 2. unresolved discussions. 1 of 2 approvals obtained.

**Pull request merged**
