### PR TITLE
fix: [SRM-12014]: fixed verification job instance api error

### PR DESCRIPTION
**Pull request by karansaraswat19**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38147)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38147)

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38147)* status: 7 file(s) to review. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/automation/resources/AutomationResource.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/38147#-NDCJtQ43JmTqLhyF9hw:-NDCJtQ43JmTqLhyF9hx:b-7d7meu) ([raw file](https://github.com/harness/harness-core/blob/7c3d576a1ac013c531d357f8b0b5a26dedd2ae4a/300-cv-nextgen/src/main/java/io/harness/cvng/automation/resources/AutomationResource.java#L33)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @ApiOperation(value = "get verification job instance", nickname = "getVerificationJobInstance", hidden = true)
> ```

why is this marked hidden?



_Code quote:_
```Java
hidden = true)
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CVConfig.java` line 155 at r3](https://reviewable.io/reviews/harness/harness-core/38147#-NDCJy7D50tHxXdORb-y:-NDCJy7D50tHxXdORb-z:bowjlsd) ([raw file](https://github.com/harness/harness-core/blob/7c3d576a1ac013c531d357f8b0b5a26dedd2ae4a/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/CVConfig.java#L155)):*
> ```Java
>   @JsonIgnore
>   public Instant getFirstTimeDataCollectionStartTime() {
>     Preconditions.checkState(getCreatedAt() != 0, "CreatedAt needs to be set to get the baseline");
> ```

why did this check exist in the first place?



_Code quote:_
```Java
  public Instant getFirstTimeDataCollectionStartTime() {
    Preconditions.checkState(getCreatedAt() != 0, "CreatedAt needs to be set to get the baseline");
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/MetricCVConfig.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/38147#-NDCK2cfE0NNFbDGyZ3m:-NDCK2cfE0NNFbDGyZ3n:baw1hy1) ([raw file](https://github.com/harness/harness-core/blob/7c3d576a1ac013c531d357f8b0b5a26dedd2ae4a/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/MetricCVConfig.java#L66)):*
> ```Java
>   @JsonIgnore
>   public TimeRange getFirstTimeDataCollectionTimeRange() {
>     Instant endTime = DateTimeUtils.roundDownTo5MinBoundary(getFirstTimeDataCollectionStartTime());
> ```

why are we ignoring this?



_Code quote:_
```Java
  public TimeRange getFirstTimeDataCollectionTimeRange() {
    Instant endTime = DateTimeUtils.roundDownTo5MinBoundary(getFirstTimeDataCollectionStartTime());
```

**Review by karansaraswat19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38147)* status: 7 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/automation/resources/AutomationResource.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/38147#-NDCJtQ43JmTqLhyF9hw:-NDDHsMBAjLAAfQCKZqF:b-7ivl66) ([raw file](https://github.com/harness/harness-core/blob/7c3d576a1ac013c531d357f8b0b5a26dedd2ae4a/300-cv-nextgen/src/main/java/io/harness/cvng/automation/resources/AutomationResource.java#L33)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why is this marked hidden?
</blockquote></details>

this API will only be used for test automation purposes. Therefore, we do not want to expose this to swagger.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/MetricCVConfig.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/38147#-NDCK2cfE0NNFbDGyZ3m:-NDDI8WH6bFWLVibPCgJ:b-84b507) ([raw file](https://github.com/harness/harness-core/blob/7c3d576a1ac013c531d357f8b0b5a26dedd2ae4a/300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/MetricCVConfig.java#L66)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

why are we ignoring this?
</blockquote></details>

there is some error which is being thrown if we are calculating this value, and we do not need it for the testing, therefore ignored it.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38147)* status: 2. unresolved discussions.

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38147)* status: 2. unresolved discussions.

**Review by Varsha-lalwani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38147)* status: :shipit: complete! ✓

**Pull request merged**
