### PR TITLE
fix: [CDS-47340]: update instance image from k8s pod if image suffix matches

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes
There may be cases when customers have defined a particular artifact source and build in their service, where as they have hardcoded a slightly different one in their manifest (i.e. the image & build is same, but source is different)

In this case we ensure that the service dashboard reflects the image which is actually deployed/present in the pod

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1282 at r3](https://reviewable.io/reviews/harness/harness-core/41557#-NJFPhXwBBLzUAEzhfPl:-NJFPhY51FShZC6cXLkh:b-fbdn64) ([raw file](https://github.com/harness/harness-core/blob/1a6c285f16785a8c9ab7fd5112d0a4e52b0391e7/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1282)):*
> ```Java
>         String buildNoFromPod = splitImageToGetBuildNum(image);
>         artifact =
>             findArtifactWithBuildNum(deploymentSummary.getArtifactStreamId(), infraMapping.getAppId(), buildNoFromPod);
> ```

We can use build number from deployment summary and we should then validate if image suffix matches from artifact & container 
Artifact artifact = findArtifactWithBuildNum(deploymentSummary.getArtifactStreamId(), infraMapping.getAppId(), deploymentSummary.getArtifactBuildNum());

if (artifact != null && isImageSuffixMatches(artifact.getImage(), k8sContainer.getImage())) {
  ...
}
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1317 at r3](https://reviewable.io/reviews/harness/harness-core/41557#-NJFPoBw4asd8M9KSAVG:-NJFPoBw4asd8M9KSAVH:b-l7uvht) ([raw file](https://github.com/harness/harness-core/blob/1a6c285f16785a8c9ab7fd5112d0a4e52b0391e7/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1317)):*
> ```Java
> 
>   private String splitImageToGetBuildNum(String image) {
>     String lastPart = image.substring(image.lastIndexOf('/') + 1);
> ```

What if image is is just nginx:latest? Similar for lastIndexOf(':'), not aware if this is a case but we should have a safe check anyway
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 532 at r3](https://reviewable.io/reviews/harness/harness-core/41557#-NJFQ9oN0ipC1kwlNct-:-NJFQ9oO8S4vfJn8oYfT:b-fol1b5) ([raw file](https://github.com/harness/harness-core/blob/1a6c285f16785a8c9ab7fd5112d0a4e52b0391e7/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L532)):*
> ```Java
>   CDC_SEND_NOTIFICATION_FOR_FREEZE("Send notifications for deployment freeze", HarnessTeam.CDC),
>   CCM_INSTANCE_DATA_CLUSTERID_FILTER("Query from instanceData collection based on clusterId", HarnessTeam.CE),
>   UPDATE_INSTANCE_DETAILS_BASED_ON_BUILD_NUM("Update instance details if build number matches", HarnessTeam.CDP);
> ```

Please make sure that FF name and description was reviewed with Rohan

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1282 at r3](https://reviewable.io/reviews/harness/harness-core/41557#-NJFPhXwBBLzUAEzhfPl:-NJJ73oA81dDY0xn2QOQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a6c285f16785a8c9ab7fd5112d0a4e52b0391e7/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1282)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We can use build number from deployment summary and we should then validate if image suffix matches from artifact & container 
Artifact artifact = findArtifactWithBuildNum(deploymentSummary.getArtifactStreamId(), infraMapping.getAppId(), deploymentSummary.getArtifactBuildNum());

if (artifact != null && isImageSuffixMatches(artifact.getImage(), k8sContainer.getImage())) {
  ...
}
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1317 at r3](https://reviewable.io/reviews/harness/harness-core/41557#-NJFPoBw4asd8M9KSAVG:-NJJFWQU6H7GtX4AXVoD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a6c285f16785a8c9ab7fd5112d0a4e52b0391e7/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1317)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What if image is is just nginx:latest? Similar for lastIndexOf(':'), not aware if this is a case but we should have a safe check anyway
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 532 at r3](https://reviewable.io/reviews/harness/harness-core/41557#-NJFQ9oN0ipC1kwlNct-:-NJJFXwaCJXPlz_VbEI8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1a6c285f16785a8c9ab7fd5112d0a4e52b0391e7/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L532)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please make sure that FF name and description was reviewed with Rohan
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1281 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJL7KIuCgM6SMrMekd2:-NJL7KIv88755-nwcnIJ:b-cs9mij) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1281)):*
> ```Java
>                      UPDATE_INSTANCE_DETAILS_BASED_ON_BUILD_NUM, deploymentSummary.getAccountId())) {
>         int lastIndexOfSlash = image.lastIndexOf('/');
>         String lastPart = lastIndexOfSlash == -1 ? image : image.substring(lastIndexOfSlash + 1);
> ```

nit: I believe imageSuffix may be a better name here
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1289 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJL6ndKAjMqZ6RySt0E:-NJL6ndL9obWV7c-txcu:be0ye72) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1289)):*
> ```Java
>             firstValidImage = image;
>           }
>           if (isNotEmpty(artifact.getMetadata().get("image"))
> ```

Can we move this and 
 int lastIndexOfSlash = image.lastIndexOf('/');
 String lastPart = lastIndexOfSlash == -1 ? image : image.substring(lastIndexOfSlash + 1);

to a different method?

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1281 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJOJW_939f7ZPA1_Ox6:-NJOJW_939f7ZPA1_Ox7:b-enve1n) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1281)):*
> ```Java
>                      UPDATE_INSTANCE_DETAILS_BASED_ON_BUILD_NUM, deploymentSummary.getAccountId())) {
>         int lastIndexOfSlash = image.lastIndexOf('/');
>         String lastPart = lastIndexOfSlash == -1 ? image : image.substring(lastIndexOfSlash + 1);
> ```

Wouldn't just `image.substring(lastIndexOfSlash + 1)` be enough?
Even if lastIndexOfSlash is -1, we'll be getting the whole string as the call would be image.substring(0);



_Code quote:_
```Java
lastIndexOfSlash == -1 ?
```
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1281 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJL7KIuCgM6SMrMekd2:-NJOJz7BAMqurpFGoiyh:b32v57) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1281)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: I believe imageSuffix may be a better name here
</blockquote></details>

+1
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1289 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJL6ndKAjMqZ6RySt0E:-NJOK2wn0nnw83MoPblu:b32v57) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1289)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we move this and 
 int lastIndexOfSlash = image.lastIndexOf('/');
 String lastPart = lastIndexOfSlash == -1 ? image : image.substring(lastIndexOfSlash + 1);

to a different method? 
</blockquote></details>

+1

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1281 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJL7KIuCgM6SMrMekd2:-NJOVE-46x0xA45G6H56:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1281)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1281 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJOJW_939f7ZPA1_Ox6:-NJOVFCmC-yrKPh7ueqZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1281)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Wouldn't just `image.substring(lastIndexOfSlash + 1)` be enough?
Even if lastIndexOfSlash is -1, we'll be getting the whole string as the call would be image.substring(0);
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1289 at r5](https://reviewable.io/reviews/harness/harness-core/41557#-NJL6ndKAjMqZ6RySt0E:-NJOVGQb1zfzjG4nkHl-:b-wq0lu8) ([raw file](https://github.com/harness/harness-core/blob/9a940abe9afe3ea2a7ba1e500ab1a5bdb56d2a3f/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1289)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

+1
</blockquote></details>

As it's just a single line now, have kept it as is. If reqd lmk, will move to a difft method

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41557)* status: :shipit: complete! ✓

**Pull request merged**
