### PR TITLE
feat: [CI-6531]: Added InputSet V1 CRUD support for Yaml Simplification

### PR DESCRIPTION
**Pull request by raghavharness**
## Describe your changes
Added InputSet V1 CRUD support for Yaml Simplification
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41941)

### CODE REVIEW

**Comment by raghavharness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41941)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetYamlHelper.java` line 103 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq20ot69AhXCefLsf2:-NKq20ouD-CdoIDF_E0H:b-f8bb8z) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetYamlHelper.java#L103)):*
> ```Java
>     }
>     return field.asText().equals("") ? null : field.asText();
>   }
> ```

i think JsonNodeUtils has this? can you verify?



_Code quote:_
```Java
  public String getStringField(JsonNode node, String fieldName) {
    if (node == null) {
      return null;
    }
    JsonNode field = node.get(fieldName);
    if (field == null) {
      return null;
    }
    return field.asText().equals("") ? null : field.asText();
  }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 92 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq2CTU-yiPRbmC3vbt:-NKq2CTU-yiPRbmC3vbu:b-o4w6ar) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L92)):*
> ```Java
>       default:
>         throw new IllegalStateException("version not supported");
>     }
> ```

above and below changes seems common, can we extract into a method?



_Code quote:_
```Java
    InputSetEntity entity;
    switch (inputSetVersion) {
      case PipelineVersion.V1:
        entity = PMSInputSetElementMapper.toInputSetEntityV1(
            InputSetsApiUtils.mapCreateToRequestInfoDTO(requestBody), account, org, project, pipeline);
        break;
      case PipelineVersion.V0:
        String yaml = removeRuntimeInputFromYaml(pipelineYaml, requestBody.getInputSetYaml());
        entity = PMSInputSetElementMapper.toInputSetEntity(
            InputSetsApiUtils.mapCreateToRequestInfoDTO(requestBody), account, org, project, pipeline, yaml);
        break;
      default:
        throw new IllegalStateException("version not supported");
    }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq2OY665u6AVe9ddSl:-NKq2OY665u6AVe9ddSm:b9hefnn) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java#L219)):*
> ```Java
>   }
> 
>   public String inputSetVersion(String accountId, String yaml) {
> ```

same method we have in pmsPipelineServiceImpl, i think we should have common method as no different impl per entity we will have, if in future then we can separate that time 



_Code quote:_
```Java
FeatureName.CI_YAML_VERSIONING
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq3avy8g-1mYMiIbRx:-NKq3avzBWOdVq9nLUQG:bxxos8z) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L151)):*
> ```Java
>     final String pipelineYaml = inputSetsApiUtils.getPipelineYaml(accountId, orgIdentifier, projectIdentifier,
>         pipelineIdentifier, pipelineBranch, pipelineRepoID, pipelineService, gitSyncSdkService);
>     String inputSetVersion = inputSetsApiUtils.inputSetVersion(accountId, yaml);
> ```

same as above comment

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41941)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 165 at r5](https://reviewable.io/reviews/harness/harness-core/41941#-NKqhb4WEPX7kwC3Tmnl:-NKqhb4l4IhJ4H3RQdQN:b-ao398x) ([raw file](https://github.com/harness/harness-core/blob/b9e7d2f8e668e6c13626f20c662e231cf68f922b/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L165)):*
> ```Java
>     final String pipelineYaml = inputSetsApiUtils.getPipelineYaml(
>         account, org, project, pipeline, null, null, pipelineService, gitSyncSdkService);
>     String inputSetVersion = inputSetsApiUtils.inputSetVersion(account, requestBody.getInputSetYaml());
> ```

why. dowe need to inject this utils class? shouldn't this be @UtilityClass
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetYamlHelper.java` line 103 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq20ot69AhXCefLsf2:-NKqhk8mAWna615rhl_U:b-5v1xv3) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetYamlHelper.java#L103)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think JsonNodeUtils has this? can you verify?
</blockquote></details>

was this verified?

**Comment by raghavharness** [comment]
> why. dowe need to inject this utils class? shouldn't this be @UtilityClass
@archit-harness This is not defined as a Utility class, it's already injected.

> was this verified?
Yes, JsonNodeUtils has that method. I'm using it now.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41941)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 92 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq2CTU-yiPRbmC3vbt:-NKr_bP80fIrFrxz5R2C:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

above and below changes seems common, can we extract into a method?
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 165 at r5](https://reviewable.io/reviews/harness/harness-core/41941#-NKqhb4WEPX7kwC3Tmnl:-NKr_awQ35TkqWavPpys:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b9e7d2f8e668e6c13626f20c662e231cf68f922b/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L165)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why. dowe need to inject this utils class? shouldn't this be @UtilityClass
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java` line 219 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq2OY665u6AVe9ddSl:-NKr_cl_7N5RvlSFqEzj:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiUtils.java#L219)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same method we have in pmsPipelineServiceImpl, i think we should have common method as no different impl per entity we will have, if in future then we can separate that time 
</blockquote></details>

done
___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetYamlHelper.java` line 103 at r4](https://reviewable.io/reviews/harness/harness-core/41941#-NKq20ot69AhXCefLsf2:-NKr_der8bQ0XoZImWHE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/fefaf0367143cbfee67da899ff8b0dd4770712ba/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetYamlHelper.java#L103)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

was this verified?
</blockquote></details>

done

**Pull request merged**
