### PR TITLE
[fix]: [CDS-37073]: create different base dir based on workflow execution id

### PR DESCRIPTION
**Pull request by tchaurasiya**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33326)

### CODE REVIEW

**Review by gitNavV — COMMENTED** [review]
First look seems fine to me.

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33326)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 447 at r1](https://reviewable.io/reviews/harness/harness-core/33326#-N2UyhfnEZZTV0Wrlooy:-N2UyhfnEZZTV0Wrlooz:bz5dy0w) ([raw file](https://github.com/harness/harness-core/blob/a2a6f33a099da6db4f35f7f7c3f8185b95a087f3/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L447)):*
> ```Java
>   public String executionIdBasedBaseDir(String accountId, String entityId, String executionId) {
>     return EXECUTION_ID_BASED_TF_BASE_DIR.replace("${ACCOUNT_ID}", accountId)
>         .replace("${ENTITY_ID}", entityId)
> ```

do we need ENTITY_ID here ?

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 447 at r1](https://reviewable.io/reviews/harness/harness-core/33326#-N2UyhfnEZZTV0Wrlooy:-N2VAFo4B5C83FOjRaY6:b-2iek0c) ([raw file](https://github.com/harness/harness-core/blob/a2a6f33a099da6db4f35f7f7c3f8185b95a087f3/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L447)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need ENTITY_ID here ? 
</blockquote></details>

Actually what i was thinking ,Lets something bad happened around clean up and all process, entityId would be grouping filter and narrow it down.

**Comment by tchaurasiya** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 447 at r1](https://reviewable.io/reviews/harness/harness-core/33326#-N2UyhfnEZZTV0Wrlooy:-N2VHA4k0U7N5I6XgTpl:b-tgpgfh) ([raw file](https://github.com/harness/harness-core/blob/a2a6f33a099da6db4f35f7f7c3f8185b95a087f3/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L447)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Actually what i was thinking ,Lets something bad happened around clean up and all process, entityId would be grouping filter and narrow it down.
</blockquote></details>

Done.Discussed Offline.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33326)* status: 1 change requests. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1046 at r2](https://reviewable.io/reviews/harness/harness-core/33326#-N2VGpMF8yMO5wTWArVk:-N2VGpMF8yMO5wTWArVl:b7vmsvg) ([raw file](https://github.com/harness/harness-core/blob/a4e37cfd5ea2199d4b36bd43b1fd795eb72781ec/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1046)):*
> ```Java
>             .useExecutionIdBasedTfBaseDir(
>                 featureFlagService.isEnabled(EXECUTION_ID_BASED_TF_BASE_DIR, context.getAccountId()))
>             .workflowExecutionId(context.getWorkflowExecutionId());
> ```

As a suggestion, maybe activity Id will be more useful here. While I don't think we do support multiple terraform plans with the same type in a workflow, and basically entity Id + workflow execution id should solve this, but activity id will ensure this uniqueness per step based on principle how it is generated

**Comment by gitNavV** [comment]
> > Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/33326)_ status: 1 change requests. 1. unresolved discussions.
> 
> _[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1046 at r2](https://reviewable.io/reviews/harness/harness-core/33326#-N2VGpMF8yMO5wTWArVk:-N2VGpMF8yMO5wTWArVl:b7vmsvg) ([raw file](https://github.com/harness/harness-core/blob/a4e37cfd5ea2199d4b36bd43b1fd795eb72781ec/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1046)):_
> 
> > ```java
> >             .useExecutionIdBasedTfBaseDir(
> >                 featureFlagService.isEnabled(EXECUTION_ID_BASED_TF_BASE_DIR, context.getAccountId()))
> >             .workflowExecutionId(context.getWorkflowExecutionId());
> > ```
> 
> As a suggestion, maybe activity Id will be more useful here. While I don't think we do support multiple terraform plans with the same type in a workflow, and basically entity Id + workflow execution id should solve this, but activity id will ensure this uniqueness per step based on principle how it is generated

Seconded.

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33326)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33326)* status: :shipit: complete! ✓

**Pull request merged**
