### PR TITLE
[feat]: [CDS-70830]: Passed PipelineEntity and branch from requests for addition in expandedPipelineJson

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: last week there was a P1 issue in QA, where we didn't have gitDetails in expanded pipelineJson due to a featureFlag not enabled. That featureFlag was for a feature to improvise GitCalls. Hence we concluded that we used wrong methods to fetch filePath, repoName. Instead we should ideally get the above 2 from the pipelineEntity itself.

Changes: have passed branch and pipeline entity to Governance Service so that filePath and repoName can be added to expandedPipelineJson.

Impact: This will impact the addition of gitDetails in expandedPipelineJson during save, run and asyncValidationFlows.

Testing: Correct value of branch was observed in save, run and asyncValidation flow. Incase of Null or empty branch as GitCall is already made in above 3 flows, we have it already handled. Incase of triggers an already existing bug was found and a ticket is raised for it, but this change remains independent of the fix which will be implemented later.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49189)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — DISMISSED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49189)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by naidu-harness** [comment]
@senjucanon2 Please follow this template for your description

Issue: ??

Changes: ??

Impact: ??

Testing: ??

**Comment by senjucanon2** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 5 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49189)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 5 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49189)* status: :shipit: complete! ✓

**Comment by senjucanon2** [comment]
trigger review

**Pull request merged**
