### PR TITLE
[feat]: [PL-25623]: Added Audit Trails for NG Auth Settings

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
Added Audit Trails for NG Auth Settings:
1. SAML 
2. OAuth 
3. Two Factor Authentication

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36862)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36862)

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsSAMLCreateEvent.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc3Pf-2YQ9z5LTLy5o:-NAc3Pf-2YQ9z5LTLy5p:b-kmzxde) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsSAMLCreateEvent.java#L28)):*
> ```Java
>   @Override
>   public String getEventType() {
>     return SAML_SSO_CREATED;
> ```

can we be consistent? Sometimes we have used the direct reference to the constant, sometimes we have used it via class reference.



_Code quote (from 400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsOAuthUpdateEvent.java):_
```Java
LoginSettingsConstants.OAUTH_PROVIDER_UPDATED
```

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/TwoFactorAuthenticationManager.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc44qF2GZSZz7R7fUD:-NAc44qF2GZSZz7R7fUE:bjlybto) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/security/authentication/TwoFactorAuthenticationManager.java#L154)):*
> ```Java
>                              .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for Two Factor Authentication Update event failed with exception: ", ex);
> ```

will we get to know account identifier for this log statement by any means? If not, then we should add account id here.

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 205 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4DeT39kpb8b4_2MR:-NAc4DeT39kpb8b4_2MS:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L205)):*
> ```Java
>               .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for SAML SSO upload event failed with exception: ", ex);
> ```

same as above

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4GI74xLhk3v24F0S:-NAc4GI74xLhk3v24F0T:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L218)):*
> ```Java
>               .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for SAML SSO update event failed with exception: ", ex);
> ```

same as above

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 230 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4I99ClLTlIXEcxA6:-NAc4I99ClLTlIXEcxA7:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L230)):*
> ```Java
>               .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for SAML SSO delete event failed with exception: ", ex);
> ```

same as above

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 268 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4KWjBwKdxFsfRpmq:-NAc4KWjBwKdxFsfRpmr:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L268)):*
> ```Java
>               .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for OAuth Provider Upload event failed with exception: ", ex);
> ```

same as above

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36862)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 282 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4LFrDa_UI2GO-1nd:-NAc4LFrDa_UI2GO-1ne:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L282)):*
> ```Java
>               .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for OAuth Provider Update event failed with exception: ", ex);
> ```

same as above
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4LvCAySkivx_ZmIS:-NAc4LvCAySkivx_ZmIT:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L294)):*
> ```Java
>               .build());
>     } catch (Exception ex) {
>       log.error("Audit trails for OAuth Provider Delete event failed with exception: ", ex);
> ```

same as above

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractOAuthConfigurationEvent.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc7G8DEzZdRrA_-WXO:-NAc7G8DEzZdRrA_-WXP:b-bc11hr) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractOAuthConfigurationEvent.java#L24)):*
> ```Java
> import lombok.NoArgsConstructor;
> import lombok.experimental.SuperBuilder;
> ```

minor `OwnedBy` tag missing, thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc7LzzDsaSelm1B2Ay:-NAc7LzzDsaSelm1B2Az:b-6x7hko) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java#L24)):*
> ```Java
> import lombok.NoArgsConstructor;
> import lombok.experimental.SuperBuilder;
> ```

minor  same as above`OwnedBy` tag missing, thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc7QVx3hHfty4omnkE:-NAc7QVx3hHfty4omnkF:bv4ryn3) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java#L46)):*
> ```Java
>         .labels(labels)
>         .type(ResourceTypeConstants.NG_LOGIN_SETTINGS)
>         .build();
> ```

nit these lines of code seem repeated at 3 places, if it is possible to extract them to a common place and use one, it will be good. Thanks



_Code quote:_
```Java
    Map<String, String> labels = new HashMap<>();
    labels.put(ResourceConstants.LABEL_KEY_RESOURCE_NAME, RESOURCE_NAME);
    return Resource.builder()
        .identifier(accountIdentifier)
        .labels(labels)
        .type(ResourceTypeConstants.NG_LOGIN_SETTINGS)
        .build();
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 173 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc8NHaECXz0rkv90Cb:-NAc8NHaECXz0rkv90Cc:bokblxh) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L173)):*
> ```Java
>                                 .insertId(outboxEvent.getId())
>                                 .build();
>     return auditClientService.publishAudit(auditEntry, globalContext);
> ```

minor lets extract the common code at one place thanks



_Code quote:_
```Java
                                .resource(ResourceDTO.fromResource(outboxEvent.getResource()))
                                .resourceScope(ResourceScopeDTO.fromResourceScope(outboxEvent.getResourceScope()))
                                .insertId(outboxEvent.getId())
                                .build();
    return auditClientService.publishAudit(auditEntry, globalContext);
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36862)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36862)* status: 24 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractOAuthConfigurationEvent.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc7G8DEzZdRrA_-WXO:-NAdcS9i42rCMxvFQeNw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractOAuthConfigurationEvent.java#L24)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor `OwnedBy` tag missing, thanks
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc7LzzDsaSelm1B2Ay:-NAdcgWN7A6dBnK4klft:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java#L24)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor  same as above`OwnedBy` tag missing, thanks
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java` line 46 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc7QVx3hHfty4omnkE:-NAeinwG7bsoh8kf1BEq:b-vcz6he) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsAbstractSAMLConfigurationEvent.java#L46)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit these lines of code seem repeated at 3 places, if it is possible to extract them to a common place and use one, it will be good. Thanks
</blockquote></details>

done, created a parent abstract class LoginSettingsAbstractEvent
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsSAMLCreateEvent.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc3Pf-2YQ9z5LTLy5o:-NAddnxK-Vc8joa42kPy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/events/LoginSettingsSAMLCreateEvent.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we be consistent? Sometimes we have used the direct reference to the constant, sometimes we have used it via class reference.
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java` line 173 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc8NHaECXz0rkv90Cb:-NAdjOiV1uhX1lLY3smZ:bazahek) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/beans/loginSettings/outbox/LoginSettingsOutboxEventHandler.java#L173)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor lets extract the common code at one place thanks
</blockquote></details>

done, really good catch.
___
*[`400-rest/src/main/java/software/wings/security/authentication/TwoFactorAuthenticationManager.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc44qF2GZSZz7R7fUD:-NAdevt11Tz-TiqLMcbK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/security/authentication/TwoFactorAuthenticationManager.java#L154)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

will we get to know account identifier for this log statement by any means? If not, then we should add account id here.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 205 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4DeT39kpb8b4_2MR:-NAdfDRO1zy8J9XpyJV5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L205)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4GI74xLhk3v24F0S:-NAdfSRD-M68nFVfqPws:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L218)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 230 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4I99ClLTlIXEcxA6:-NAdfT5h7QDJtF7ofiKa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L230)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 268 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4KWjBwKdxFsfRpmq:-NAdff__12U5YoZxKqBD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L268)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 282 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4LFrDa_UI2GO-1nd:-NAdfgCM1AAc0hqx5Xo4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L282)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java` line 294 at r2](https://reviewable.io/reviews/harness/harness-core/36862#-NAc4LvCAySkivx_ZmIS:-NAdfh2R-bAHhpo4m-Qy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aeceb95ad1ae18737e8dad0dc4bdb031d6696c08/400-rest/src/main/java/software/wings/service/impl/SSOSettingServiceImpl.java#L294)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by pbarapatre10 — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36862#-:-NAeoVimDpHgYNcHyi97:bnfp4nl)* status: 24 file(s) to review. 1 change requests. 8. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 2 of 11 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36862#-:-NAex7Xh7m0QFOTm9i3W:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
