### PR TITLE
fix: [PL-38595]: Avoiding processing duplicate RBAC Update events in batch.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Avoiding processing duplicate RBAC Update events in batch.
We get lot of updates to the same user group using SCIM/external integrations and currently each of those events are processed. We can avoid processing update events to the same entity.
Also, removed code for null checks in Change consumers as are dedupping and reducing n updates to 1 and if the first event didn't have items for instance if User Group didn't have users but subsequent updates did have users then those events will also get skipped. So removed null checks.

Test Cases:
1) Skip duplicate RBAC entity update events in batch.
2) Unique RBAC events should get processed.
3) Tested all RBAC Create, Update and Delete operations.

image

image

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47733)

### CODE REVIEW

**Review by ankit-harness — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47733)* status: Some of the checks are too old. 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/47733#-NVEwhEd8--KxorqYjQN:-NVEwhEd8--KxorqYjQO:botx3sd) ([raw file](https://github.com/harness/harness-core/blob/b88e2452a70ecd89c7dca8348aa256fa4b94251d/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java#L79)):*
> ```Java
>       if (opType.get() == UPDATE) {
>         if (updateEventsSeen.contains(id)) {
>           log.info("Skipping UPDATE event for entity: {}.{}", collectionName.get(), id);
> ```

Lets add the reason for skipping in the log line
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/47733#-NVEwV8zD1H4LFkcseW4:-NVEwV8zD1H4LFkcseW5:b5vfx7y) ([raw file](https://github.com/harness/harness-core/blob/b88e2452a70ecd89c7dca8348aa256fa4b94251d/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java#L82)):*
> ```Java
>           return true;
>         } else {
>           updateEventsSeen.add(id);
> ```

Let's add it after the successful processing

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47733)* status: Some of the checks are too old. 8 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/47733#-NVEwhEd8--KxorqYjQN:-NWHevaf--TA5Lo5lN1L:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b88e2452a70ecd89c7dca8348aa256fa4b94251d/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java#L79)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets add the reason for skipping in the log line
</blockquote></details>

done
___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/47733#-NVEwV8zD1H4LFkcseW4:-NWHewysD1IIMwSYHg7k:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b88e2452a70ecd89c7dca8348aa256fa4b94251d/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/AccessControlDebeziumChangeConsumer.java#L82)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Let's add it after the successful processing
</blockquote></details>

done

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47733)* status: Some of the checks are too old. 8 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47733)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Review by ashishsanodia-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 6 of 7 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47733)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47733#-:-NWLShon2di4-R7V7glD:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
