### PR TITLE
[feat]:[CDS-71091]: adding telemetry in template service

### PR DESCRIPTION
**Pull request by RajBaviskar**
## Describe your changes
* adding telemetry in template service

Screen Shot 2023-06-22 at 1 27 56 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)

### CODE REVIEW

**Comment by RajBaviskar** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/49631#-NYaeeJq5K1Qg7nOLJO5:-NYaeeJq5K1Qg7nOLJO6:b-5m1778) ([raw file](https://github.com/harness/harness-core/blob/20d979a9c2597b66c24353b1c2801e0f0853fbcb/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L291)):*
> ```Java
>       }
> 
>       templateServiceHelper.sendTemplatesSaveTelemetryEvent(template, CREATING_TEMPLATE);
> ```

can you submit this event in async thread?

**Comment by sahilhindwani-harness** [comment]
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/49631#-NYaeeJq5K1Qg7nOLJO5:-NYaf_go0czqmVs28LjC:b2ngthb) ([raw file](https://github.com/harness/harness-core/blob/20d979a9c2597b66c24353b1c2801e0f0853fbcb/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L291)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you submit this event in async thread?
</blockquote></details>

+1

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/49631#-NYaeeJq5K1Qg7nOLJO5:-NYb2ymqDPzjN3nGi1RZ:b3swj3b) ([raw file](https://github.com/harness/harness-core/blob/20d979a9c2597b66c24353b1c2801e0f0853fbcb/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L291)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

any reference I can follow?

**Review by RajBaviskar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 2 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 291 at r2](https://reviewable.io/reviews/harness/harness-core/49631#-NYaeeJq5K1Qg7nOLJO5:-NYd7Uvq8O23sjM9iv5a:b-agp0xy) ([raw file](https://github.com/harness/harness-core/blob/20d979a9c2597b66c24353b1c2801e0f0853fbcb/template-service/service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L291)):*
<details><summary><i>Previously, RajBaviskar wrote…</i></summary><blockquote>

any reference I can follow? 
</blockquote></details>

added the async.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 1 change requests. 1. unresolved discussions.

**Comment by RajBaviskar** [comment]
trigger review

**Review by RajBaviskar — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49631)* status: 1. unresolved discussions.

**Pull request merged**
