### PR TITLE
fix: [PIE-8116]: update log debezium service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`debezium-service/build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/43591#-NNeFPDyEfzDDXh-qhC0:-NNeFPDyEfzDDXh-qhC1:b8kapwm) ([raw file](https://github.com/harness/harness-core/blob/ed2bdc8cd394807566704df5e9628ee9c68c41bf/debezium-service/build.properties#L3)):*
> ```INI
> build.majorVersion=1
> build.minorVersion=5
> build.number=400
> ```

Lets verify this by deploying this pr build in any of the env

**Comment by shalini-agr** [comment]
*[`debezium-service/build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/43591#-NNeFPDyEfzDDXh-qhC0:-NNeGABS-TZoE-daAzTY:bfoas84) ([raw file](https://github.com/harness/harness-core/blob/ed2bdc8cd394807566704df5e9628ee9c68c41bf/debezium-service/build.properties#L3)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

Lets verify this by deploying this pr build in any of the env
</blockquote></details>

sure, will do in preqa to test

**Comment by shalini-agr** [comment]
*[`debezium-service/build.properties` line 3 at r1](https://reviewable.io/reviews/harness/harness-core/43591#-NNeFPDyEfzDDXh-qhC0:-NNeLp5G8C1aTGBv0fBu:b-73egqv) ([raw file](https://github.com/harness/harness-core/blob/ed2bdc8cd394807566704df5e9628ee9c68c41bf/debezium-service/build.properties#L3)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

sure, will do in preqa to test
</blockquote></details>

verified after deploying in pre-qa

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/43591#-NNehN601WGopHsbVrGa:-NNehN601WGopHsbVrGb:bq6jfbs) ([raw file](https://github.com/harness/harness-core/blob/7c93d512cc415321e4281765510437b119214147/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java#L44)):*
> ```Java
>       } else if (!success) {
>         resetOffset(JsonUtils.asObject(redisConfigJson, RedisConfig.class), redisKey);
>         log.error(String.format("Offset reset for key: %s because of exception: %s, at %s", redisKey, error,
> ```

We are logging exception twice here. We should avoid it.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java` line 44 at r1](https://reviewable.io/reviews/harness/harness-core/43591#-NNehN601WGopHsbVrGa:-NNfA6BQDJvXHcrKHb8P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7c93d512cc415321e4281765510437b119214147/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumUtils.java#L44)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

We are logging exception twice here. We should avoid it.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)* status: 2 file(s) to review.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43591)* status: :shipit: complete! ✓

**Pull request merged**
