### PR TITLE
feat: [CDS-49654] add terargrunt error handler

### PR DESCRIPTION
**Pull request by vlica-harness**
## Describe your changes
The new terragrunt error handler has been added, this terragrunt handler also uses the terraform error handler.
The existing terraform error handler has been moved into a utility helper class so it can be reused into terragrunt error handler. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, 8 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientFactory.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6qtTb1Nsu7EBO-fCh:-NL6qtTb1Nsu7EBO-fCi:baj8q7) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientFactory.java#L47)):*
> ```Java
>   private static final Version MIN_FALLBACK_VERSION = Version.parse("0.0.1");
>   private static final String TERRAFORM_BINARY_VALUE = "terraform";
>   private TerragruntCommandErrorOutput terragruntCommandErrorOutput;
> ```

This is a singleton, you should not store any state to it as class instance is shared between multiple threads
___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6r7mOEQ96WUJM34gk:-NL6r7mOEQ96WUJM34gl:b-xbt51c) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java#L75)):*
> ```Java
>   private Version terraformVersion;
>   private CliHelper cliHelper;
>   private TerragruntCommandErrorOutput TerragruntCommandErrorOutput;
> ```

variable name should be camel case
___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java` line 202 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6rDmA6Ax9r8Lq7ami:-NL6rDmA6Ax9r8Lq7amj:b-u4vs3c) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java#L202)):*
> ```Java
>       return JsonUtils.jsonPath(terragruntInfoJson, "WorkingDir");
>     } catch (Exception e) {
>       if (TerragruntCommandErrorOutput != null) {
> ```

I would suggest instead of storing only error output without any context, instead refactor String terragruntInfoJson to a structure where you would have all required details:
infoJson
errorOutput

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 17 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientFactory.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6qtTb1Nsu7EBO-fCh:-NL76Sa6EUc21jayRNAF:bs3xcbz) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientFactory.java#L47)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This is a singleton, you should not store any state to it as class instance is shared between multiple threads
</blockquote></details>

eagle eye catch, refactored, and throwing exception right away when we find out the result of command !=0, and it won't carry any stat
___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6r7mOEQ96WUJM34gk:-NL76N-IE4OhqjDieuhN:bwpwsbv) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java#L75)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

variable name should be camel case
</blockquote></details>

thanks, updated the class as I got rid of this variable.
___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java` line 202 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6rDmA6Ax9r8Lq7ami:-NL76lEuDM7GSB7ZrTsI:b-cjf6ki) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java#L202)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I would suggest instead of storing only error output without any context, instead refactor String terragruntInfoJson to a structure where you would have all required details:
infoJson
errorOutput
</blockquote></details>

I think in case we won't carry any info and output, would be more correct to throw exception where we find of the command !=0 and therefore the handler will handle the error.

**Comment by vlica-harness** [comment]
trigger ft1

**Comment by vlica-harness** [comment]
trigger ft2

**Comment by akhilpandey1** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/42313#-NLKqCxm7M7I2pDmf2_8:-NLKqCxm7M7I2pDmf2_9:b-onlbos) ([raw file](https://github.com/harness/harness-core/blob/25932fba52afd494b1151f7068c6893a9a827670/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java#L66)):*
> ```Java
>       Pattern.compile("on\\s(.+?)\\sline\\s(\\d+),\\sin\\s(.+?):\\s+\\d+:(.*)");
>   private static final Pattern ERROR_ARGUMENT_PATTERN = Pattern.compile(".+?\\s\".+?\"");
>   private static final int ERROR_MAX_CHARACTERS_LIMIT = 512;
> ```

How do we decide the ERROR_MAX_CHARACTERS_LIMIT to be 512?

**Review by akhilpandey1 — COMMENTED** [review]
> Reviewed 6 of 13 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java` line 66 at r4](https://reviewable.io/reviews/harness/harness-core/42313#-NLKqCxm7M7I2pDmf2_8:-NLKrt4K37uSaIQapdx4:b6e5a95) ([raw file](https://github.com/harness/harness-core/blob/25932fba52afd494b1151f7068c6893a9a827670/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java#L66)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

How do we decide the ERROR_MAX_CHARACTERS_LIMIT to be 512?
</blockquote></details>

this is existing logic from terraform handler which has been moved to this new utility class.
I believe when it was decided the 512 there was an issue, I'm not sure that was the context.

**Review by akhilpandey1 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1, 7 of 10 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 1 file(s) to review. 2 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/42313#-NLLk0mwCBhiKgMxCWpk:-NLLk0mwCBhiKgMxCWpl:b4zfjtj) ([raw file](https://github.com/harness/harness-core/blob/25932fba52afd494b1151f7068c6893a9a827670/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java#L59)):*
> ```Java
> @Slf4j
> @OwnedBy(CDP)
> public class ProvisionerExceptionHelper {
> ```

Too generic name.... If it's only for terragrunt - class name should reflect it.
___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6r7mOEQ96WUJM34gk:-NLLpkYhA7duV3KxvQsi:brwlbc3) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java#L75)):*
<details><summary><i>Previously, vlica-harness (Vasile Lica) wrote…</i></summary><blockquote>

thanks, updated the class as I got rid of this variable.
</blockquote></details>

terragruntCommandErrorOutput



_Code quote:_
```Java
TerragruntCommandErrorOutput
```
___
*[`980-commons/src/main/java/io/harness/exception/TerragruntCommandExecutionException.java` line 15 at r4](https://reviewable.io/reviews/harness/harness-core/42313#-NLLq7W61An0EWvpuAc2:-NLLq7W61An0EWvpuAc3:b-qw0d4v) ([raw file](https://github.com/harness/harness-core/blob/25932fba52afd494b1151f7068c6893a9a827670/980-commons/src/main/java/io/harness/exception/TerragruntCommandExecutionException.java#L15)):*
> ```Java
> 
> import java.util.EnumSet;
> ```

@OwnedBy

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/42313#-NL6r7mOEQ96WUJM34gk:-NLLuO4DAgS4l3nTiHV2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/09e45fd633dcbf87565d902c9762b07f1ad8817e/960-api-services/src/main/java/io/harness/terragrunt/v2/TerragruntClientImpl.java#L75)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

terragruntCommandErrorOutput
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/42313#-NLLk0mwCBhiKgMxCWpk:-NLLuQUYAtsFlgcs9HqC:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/25932fba52afd494b1151f7068c6893a9a827670/930-delegate-tasks/src/main/java/io/harness/delegate/exceptionhandler/handler/ProvisionerExceptionHelper.java#L59)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Too generic name.... If it's only for terragrunt - class name should reflect it.
</blockquote></details>

done

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 1 of 10 files at r2, 1 of 2 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger smartchecks

**Review by akhilpandey1 — APPROVED** [review]
> Reviewed 5 of 7 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 2 of 10 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 5 of 7 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42313)* status: :shipit: complete! ✓

**Pull request merged**
