### PR TITLE
feat: [CDS-83333]: Fix Not getting ENTITY_REFERENCE_EXCEPTION for child pipeline

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Fix Not getting ENTITY_REFERENCE_EXCEPTION for child pipeline

Tests done - 
* Tested that we are getting ENTITY_REFERENCE_EXCEPTION for inline pipelines
* For child remote pipeline we are not getting ENTITY_REFERENCE_EXCEPTION ( Same as PROD )

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55044)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55044)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/55044#-NiZKqeQ4vlNqw4UyGQy:-NiZKqeQ4vlNqw4UyGQz:bla9eeo) ([raw file](https://github.com/harness/harness-core/blob/e376584ba78f1f64550702659b7c0e1e064e949f/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L64)):*
> ```Java
>             SecurityContextBuilder.setContext(new ServicePrincipal(PIPELINE_SERVICE.getServiceId()));
>             SourcePrincipalContextBuilder.setSourcePrincipal(new ServicePrincipal(PIPELINE_SERVICE.getServiceId()));
>             PipelineGitXHelper.setupGitParentEntityDetails(pipelineEntity.get().getAccountIdentifier(),
> ```

Should we add a UT for the same?

**Review by sribalij — DISMISSED** [review]

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger ut8

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by adivishy1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55044)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55044#-:-NidGxWH52S0zjdKutfT:bnfp4nl)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java` line 64 at r1](https://reviewable.io/reviews/harness/harness-core/55044#-NiZKqeQ4vlNqw4UyGQy:-NidGw6h948ma_jTh11U:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e376584ba78f1f64550702659b7c0e1e064e949f/pipeline-service/service/src/main/java/io/harness/pms/event/filter/AsyncFilterCreationDispatcher.java#L64)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we add a UT for the same?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55044)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger uts

**Comment by utkarshchoubey-harness** [comment]
trigger review

**Pull request merged**
