### PR TITLE
[fix]: [CDS-46496]: Minimize quotes for converting objects to yaml in TemplateYamlUtils and CDYamlUtils

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
This change is behind FF `CDS_ENTITY_REFRESH_DO_NOT_QUOTE_STRINGS` 

## Describe your changes
Whenever we convert an object for eg. Map to yaml using yaml utils, it ends up adding double quotes to each string value by default. For eg. 

if the take this yaml
```
key: value
````

then converting this to a map and converting that map to yaml, changes it to as follows
```
key: "value"
```

This is not clean and causes confusions when these changes get pushed to Git. For eg. when a user reconciles a template, the diff shown on the UI does not match what is shown on Git side because every line ends up showing a change as below
image

However, after this change, the diffs are shown correctly as below
image

We achieve this by using the **MINIMIZE QUOTES** feature of Jackson Yaml Generator. Ref: https://www.javadoc.io/doc/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.7.5/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#MINIMIZE_QUOTES. It quotes strings only when its multi line

This also fixes the issue where a multi line string used to be converted to a single line string with \n as below
image

This also indents arrays to be in line with what our UI also does
```
steps:
  - step:
```
as opposed to earlier
```
steps:
- step:
```

We are also using the **ALWAYS_QUOTE_NUMBERS_AS_STRINGS**. This applies only to numbers present as text nodes i.e number should be quotes in the original yaml. If a number is present without quotes, its treated as an IntNode and the above option does not apply to it

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44080)

### CODE REVIEW

**Review by utkarshchoubey-harness — DISMISSED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44080)* status: 36 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by tchaurasiya — DISMISSED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44080)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44080#-:-NOtkzcuA2KGZOc61t2n:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44080)* status: 1 file(s) to review.

**Review by utkarshchoubey-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44080)* status: :shipit: complete! ✓

**Pull request merged**
