### PR TITLE
[feat]: [CODE-255]: Resource group for code repo

### PR DESCRIPTION
**Pull request by hitesharinga**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46789)

### CODE REVIEW

**Review by johannesHarness — APPROVED** [review]

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46789)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/46789#gh-1176798794:-NTtPOw-74vwjRqnAjXy:b-e6eygn) ([raw file](https://github.com/harness/harness-core/blob/238e37d6d1ab056f74f418ccff86d3a44de21f93/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java#L50)):*
<details><summary><i>Previously, johannesHarness (Johannes Batzill) wrote…</i></summary><blockquote>

Does this imply that a repo can exist on account level (which it doesn't as of now), or just that we allow selecting all repos across a whole account?
</blockquote></details>

yes @johannesHarness  that should be the case. You can verify it as well.
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/46789#-NTtOwLL1yKRu9ooKavz:-NTtOwLL1yKRu9ooKaw-:b88vyic) ([raw file](https://github.com/harness/harness-core/blob/238e37d6d1ab056f74f418ccff86d3a44de21f93/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java#L60)):*
> ```Java
>   @Override
>   public ResourceInfo getResourceInfoFromEvent(Message message) {
>     return null;
> ```

If Resource selection BY_RESOURCE_IDENTIFIER is to be supported then please implement getEventFrameworkEntityType and getResourceInfoFromEvent.
Please refer:
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812876/Onboarding+Resources+for+ResourceGroup

**Review by hitesharinga — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46789)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 2. unresolved discussions. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/46789#gh-1176798794:-NTtwWgG7iTF5pqGo8FB:bjzwpb7) ([raw file](https://github.com/harness/harness-core/blob/238e37d6d1ab056f74f418ccff86d3a44de21f93/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java#L50)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

yes @johannesHarness  that should be the case. You can verify it as well.
</blockquote></details>

Hey @Jimit09Gandhi , repo exists only at project, so should we keep only project in getSelectorKind and getValidScopeLevels. I was looking at pipeline resource group, it returns all 3 but pipeline exists only at project. 
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/46789#-NTtOwLL1yKRu9ooKavz:-NTtwR2M92_rTeQrpMdM:b-22phkb) ([raw file](https://github.com/harness/harness-core/blob/238e37d6d1ab056f74f418ccff86d3a44de21f93/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java#L60)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

If Resource selection BY_RESOURCE_IDENTIFIER is to be supported then please implement getEventFrameworkEntityType and getResourceInfoFromEvent.
Please refer:
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21060812876/Onboarding+Resources+for+ResourceGroup
</blockquote></details>

Right now we don't have resource selection.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46789)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeRepositoryResourceImpl.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/46789#-NTwVQ1L2n73y1L1qn0w:-NTwVQ1L2n73y1L1qn0x:b-rbiwrm) ([raw file](https://github.com/harness/harness-core/blob/c5ce0630214e2e73feae59214756bc16db5702e1/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeRepositoryResourceImpl.java#L72)):*
> ```Java
>     return ImmutableMap.of(ScopeLevel.ACCOUNT, EnumSet.of(BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES),
>         ScopeLevel.ORGANIZATION, EnumSet.of(BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES), ScopeLevel.PROJECT,
>         EnumSet.of(BY_RESOURCE_IDENTIFIER, BY_RESOURCE_TYPE));
> ```

If resource selection is not to be supported then remove BY_RESOURCE_IDENTIFIER.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46789)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/46789#gh-1176798794:-NTwVhit47Vl-DlQ7anR:bgf35yy) ([raw file](https://github.com/harness/harness-core/blob/238e37d6d1ab056f74f418ccff86d3a44de21f93/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/code/CodeResourceImpl.java#L50)):*
>  just that we allow selecting all repos across a whole account?
right so if we want user to allow access to all repos of all projects in Org or Account, then way to achieve it is by having support in Resource group by specifying in entries in getSelectorKind and getValidScopeLevels for org and account. It doesn't imply resource should exist at account, org.

**Pull request closed without merging**
