### PR TITLE
feat: [DEL-5058]: save some delegate logging costs:

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
This pr is just to save some logging cost related to delegate.

Nothing has been tested as part of this pr. No need of testing.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40495)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40495)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHTkGrb3-nZiNG4BRpl:-NHTkGrb3-nZiNG4BRpm:bm1d4zc) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java#L99)):*
> ```Java
>       }
>       // Question for Gaurav? What does this log means, and should we mark it as debug log for cost cutting
>       log.warn("Expression evaluation is being processed synchronously");
> ```

 we can get rid of this. This is no longer needed.



_Code quote:_
```Java
 log.warn("Expression evaluation is being processed synchronously");
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2673 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHU1r4Z9mXoWA5cymcB:-NHU1r4Z9mXoWA5cymcC:b-vwh6ji) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2673)):*
> ```Java
>     final String delegateProfileId = delegateParams.getDelegateProfileId();
> 
>     if (!delegateParams.isNg()) {
> ```

were we getting logs here because of NG delegates ?



_Code quote:_
```Java
 (!delegateParams.isNg()) 
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2970 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHTm3p87tCN7HbVYh2f:-NHTm3p87tCN7HbVYh2g:b-dmst3n) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2970)):*
> ```Java
> 
>     if (profileId != null) {
>       log.info("Checking delegate profile. Previous profile [{}] updated at {}", profileId, lastUpdatedAt);
> ```

we don't need this log here, instead put the logs in failure path i.e. before returning null below



_Code quote:_
```Java
    if (profileId != null) {
      log.info("Checking delegate profile. Previous profile [{}] updated at {}", profileId, lastUpdatedAt);
    }
```
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2975 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHTmB0y0qHN9lVfdmek:-NHTmB0y0qHN9lVfdmel:bdoz2f5) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2975)):*
> ```Java
> 
>     if (delegate == null || DelegateInstanceStatus.ENABLED != delegate.getStatus()) {
>       return null;
> ```

put a log warn here and below
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4549 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHU3eJZAnYBmdfPHjaY:-NHU3eJZAnYBmdfPHjaZ:bbfrizg) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4549)):*
> ```Java
>       return Optional.ofNullable(delegateTokenGlobalContextData.getTokenName());
>     }
>     log.warn("Delegate token name not found in Global Context Data. Please verify manually.");
> ```

This log also showing up a lot, do we need this ?



_Code quote:_
```Java
log.warn("Delegate token name not found in Global Context Data. Please verify manually.");
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40495)* status: 7 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHTkGrb3-nZiNG4BRpl:-NHY5ArkCvew4E-qmpKW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java#L99)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

 we can get rid of this. This is no longer needed.
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2673 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHU1r4Z9mXoWA5cymcB:-NHY93RCBh9T1CgwRvRN:b-4yg4me) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2673)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

were we getting logs here because of NG delegates ?
</blockquote></details>

Not always. There are some delegates which are referencing a deleted profile. So for cg we should have a fallback mechanism (created a jira for that DEL-5429). And atleast for ng we can disable this.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2970 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHTm3p87tCN7HbVYh2f:-NHYBn8HEww6kFXMit2E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2970)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

we don't need this log here, instead put the logs in failure path i.e. before returning null below
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2975 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHTmB0y0qHN9lVfdmek:-NHYBrZT14e8AyjmsN4Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2975)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

put a log warn here and below
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 4549 at r1](https://reviewable.io/reviews/harness/harness-core/40495#-NHU3eJZAnYBmdfPHjaY:-NHYBzeEDJNblxMrYWSR:b-d6frfh) ([raw file](https://github.com/harness/harness-core/blob/9787b719296eaa9bff32ef889259c66c0abd4e49/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L4549)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

This log also showing up a lot, do we need this ?
</blockquote></details>

Yes for the time being we need this, this is a serious log and we need to look into in depth. Have created a jira for this (DEL-5405).

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40495)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2977 at r2](https://reviewable.io/reviews/harness/harness-core/40495#-NHYt8CN3-yVV0GTMcw5:-NHYt8CN3-yVV0GTMcw6:b-hc6v65) ([raw file](https://github.com/harness/harness-core/blob/1a843af4b4baaf1a2109504d5bbc127edbec47fa/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2977)):*
> ```Java
> 
>     if (isNotBlank(profileId) && isBlank(delegate.getDelegateProfileId())) {
>       return DelegateProfileParams.builder().profileId("NONE").build();
> ```

should we put a log warn here before return statement ?
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2983 at r2](https://reviewable.io/reviews/harness/harness-core/40495#-NHYszpcB7wytlfVaX5J:-NHYszpcB7wytlfVaX5K:bwoqdbg) ([raw file](https://github.com/harness/harness-core/blob/1a843af4b4baaf1a2109504d5bbc127edbec47fa/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2983)):*
> ```Java
>       DelegateProfile profile = delegateProfileService.get(accountId, delegate.getDelegateProfileId());
>       if (profile != null && (!profile.getUuid().equals(profileId) || profile.getLastUpdatedAt() > lastUpdatedAt)) {
>         log.info("Checking delegate profile. Previous profile [{}] updated at {}", profileId, lastUpdatedAt);
> ```

we can skip this logging imo



_Code quote:_
```Java
 log.info("Checking delegate profile. Previous profile [{}] updated at {}", profileId, lastUpdatedAt);
```

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40495)* status: 7 file(s) to review.

**Comment by arpit3107** [comment]
trigger messagecheck

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40495)* status: :shipit: complete! ✓

**Pull request merged**
