### PR TITLE
feat: [PL-29018]: UserGroup V2 API with emails

### PR DESCRIPTION
**Pull request by reetika04**
## Describe your changes
Added V2 api's to support addition of users via email in user group. This has been a blocker for terraform https://harness.atlassian.net/browse/PL-29018
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGoklQi1bQz_PX-whP-:-NGoklQi1bQz_PX-whP0:b-yep5t9) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java#L100)):*
> ```Java
>         ApiResponse(description = "Returns the successfully created User Group")
>       })
>   public ResponseDTO<ResponseUserGroupV2DTO>
> ```

UserGroupResponseV2DTO
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGokjAP47ZSD9k_OQTJ:-NGokjAQEmjv6yQGWuGI:besusjn) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java#L107)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @RequestBody(description = "User Group entity to be created",
>           required = true) @NotNull @Valid UserGroupV2DTO userGroupDTO) {
> ```

UserGroupRequestV2DTO
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolN9PBJ0AL8c6jj4g:-NGolN9PBJ0AL8c6jj4h:bx4odm3) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L58)):*
> ```Java
>   UserGroup updateWithCheckThatSCIMFieldsAreNotModified(UserGroupDTO userGroupDTO);
> 
>   List<UserData> getUserMetaDataFromIds(List<String> uuids);
> ```

getUserMetadata
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolLjq57HMIJkc_vxc:-NGolLjq57HMIJkc_vxd:b-8u16ro) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L60)):*
> ```Java
>   List<UserData> getUserMetaDataFromIds(List<String> uuids);
> 
>   List<String> getUserIdsFromEmail(List<String> emails);
> ```

getUserIds
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolOzT28P-psT9pdLe:-NGolOzT28P-psT9pdLf:b-deafvx) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L62)):*
> ```Java
>   List<String> getUserIdsFromEmail(List<String> emails);
> 
>   List<String> getUserEmailsFromIds(List<String> uuids);
> ```

getUserEmails
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolWee23ffTc3hqpOa:-NGolWee23ffTc3hqpOb:bx4odm3) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java#L78)):*
> ```Java
>       String serviceAccountId, Scope scope, RoleBinding roleBinding, UserMembershipUpdateSource source);
> 
>   List<UserMetadataDTO> getUserMetadataByEmails(List<String> emailIds);
> ```

getUserMetadata
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/ResponseUserGroupV2DTO.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGollGz4i-4d50jXdbm:-NGollH-A2dxlSpSd5A2:boavquh) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/ResponseUserGroupV2DTO.java#L43)):*
> ```Java
> 
>   @Schema(description = "Name of the UserGroup.") @NotNull @NGEntityName String name;
>   @Schema(description = "List of users emails in the UserGroup.") List<UserData> users;
> ```

Can we call it UserInfo instead of UserData
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserData.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolq6s823Nbb7PKSef:-NGolq6s823Nbb7PKSeg:b-7r2rex) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserData.java#L21)):*
> ```Java
> public class UserData {
>   String id;
>   String emailId;
> ```

email

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 9 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolN9PBJ0AL8c6jj4g:-NGopINT2BnPFeuiN-9X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L58)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getUserMetadata
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolLjq57HMIJkc_vxc:-NGopIv3AMUAVCKYYBum:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L60)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getUserIds
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolOzT28P-psT9pdLe:-NGopJCs-wr4Hkvqomkd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java#L62)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getUserEmails
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolWee23ffTc3hqpOa:-NGopK3O2fVeGHu9AQ6J:b-24le5v) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/NgUserService.java#L78)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

getUserMetadata
</blockquote></details>

getUserMetaData already exists with list of user id's cannot rename this.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/ResponseUserGroupV2DTO.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGollGz4i-4d50jXdbm:-NGopQaW1xoEStL4qzSm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/ResponseUserGroupV2DTO.java#L43)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Can we call it UserInfo instead of UserData
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserData.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGolq6s823Nbb7PKSef:-NGopR4c5RGmF-UKIOWP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/960-ng-core-beans/src/main/java/io/harness/ng/core/dto/UserData.java#L21)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

email
</blockquote></details>

Done.

**Comment by reetika04** [comment]
trigger messagecheck

**Comment by abhayganvir** [comment]
trigger checkstylecodeformat

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863#-:-NGqZEktAqeVB3dR6Cf5:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 264 at r2](https://reviewable.io/reviews/harness/harness-core/39863#-NGukAtE6t59QK4IKhEl:-NGukAtE6t59QK4IKhEm:b-ljm3c3) ([raw file](https://github.com/harness/harness-core/blob/1c727a3bc7540a1428e4ef15f2feb2d33987c0b9/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L264)):*
> ```Java
>     return ngUserService.getUserMetadata(uuids)
>         .stream()
>         .map(user -> UserInfo.builder().id(user.getUuid()).email(user.getUuid()).build())
> ```

Please change to populated with  email Id.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java` line 107 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGokjAP47ZSD9k_OQTJ:-NGulZZp4HttHT9bX8P_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java#L107)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

UserGroupRequestV2DTO
</blockquote></details>

Done.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java` line 264 at r2](https://reviewable.io/reviews/harness/harness-core/39863#-NGukAtE6t59QK4IKhEl:-NGul_DO2uCyyY3uscYt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c727a3bc7540a1428e4ef15f2feb2d33987c0b9/123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java#L264)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Please change to populated with  email Id.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863#-:-NGv-kt7AwlCtb-1pBhU:bnfp4nl)* status: 1 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863#-:-NGvMSpoAM5eB_VsLUiA:bnfp4nl)* status: 2. unresolved discussions.

**Review by ankit-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863#-:-NGvMZi88wImTSP2-Zct:bnfp4nl)* status: 1. unresolved discussions.

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 2. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/39863#-NGoklQi1bQz_PX-whP-:-NGvMhZK-krs7aIDmiIV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/020d09164d3fc9b71584ff7a6a06172f3f642783/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java#L100)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

UserGroupResponseV2DTO
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 1. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: 1. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863#-:-NGvNme3Cgegpo2WStos:bnfp4nl)* status: 1. unresolved discussions.

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39863)* status: :shipit: complete! ✓

**Pull request merged**
