### PR TITLE
[feat]: [PIE-4653]: Integrate the expression mode with evaluateExpression flow in expression engine

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38372)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38372)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38372)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java` line 365 at r2](https://reviewable.io/reviews/harness/harness-core/38372#-NDaJ6T844CjtAmiAdAq:-NDaJ6T844CjtAmiAdAr:bdumde5) ([raw file](https://github.com/harness/harness-core/blob/12b90b3e1cb108601d3f5fc70a382f22fbe88d75/980-commons/src/test/java/io/harness/expression/EngineExpressionEvaluatorTest.java#L365)):*
> ```Java
>             new HashMap<>(ImmutableMap.of("a", "<+a> + <+<+a> + <+e>>", "b", "<+a> + <+<+b> + <+e>>"))));
>     EngineExpressionEvaluator.PartialEvaluateResult result =
>         evaluator.partialResolve(m, ExpressionMode.RETURN_NULL_IF_UNRESOLVED);
> ```

Can you please add tests for other expression modes
___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/expression/AmbianceExpressionEvaluatorTest.java` line 415 at r2](https://reviewable.io/reviews/harness/harness-core/38372#-NDaLucu5ZLbZH5clArB:-NDaLucu5ZLbZH5clArC:b-mv8s64) ([raw file](https://github.com/harness/harness-core/blob/12b90b3e1cb108601d3f5fc70a382f22fbe88d75/pipeline-service/modules/orchestration/src/test/java/io/harness/expression/AmbianceExpressionEvaluatorTest.java#L415)):*
> ```Java
>     // expression will not be evaluated, and mode is RETURN_NULL_IF_UNRESOLVED, so null value would be returned.
>     assertThat(expressionEvaluator.evaluateExpression("<+invalidKey>", ExpressionMode.RETURN_NULL_IF_UNRESOLVED))
>         .isEqualTo(null);
> ```

Can you add test for exception as well?

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38372)* status: 10 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/test/java/io/harness/expression/AmbianceExpressionEvaluatorTest.java` line 415 at r2](https://reviewable.io/reviews/harness/harness-core/38372#-NDaLucu5ZLbZH5clArB:-NDb1TDV2yyWulQBMgpl:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/12b90b3e1cb108601d3f5fc70a382f22fbe88d75/pipeline-service/modules/orchestration/src/test/java/io/harness/expression/AmbianceExpressionEvaluatorTest.java#L415)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you add test for exception as well?
</blockquote></details>

done

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38372)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38372)* status: :shipit: complete! ✓

**Pull request merged**
