### PR TITLE
feat: [DEL-4971]: Marking PPT with no heartbeat to status TASK_TO_REBALANCE

### PR DESCRIPTION
**Pull request by Vbhatia20**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38087)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* Code issue 1 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38087)

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/38087#-ND5IdoDCDop5xwbFfGU:-ND5IdoDCDop5xwbFfGV:brptkfm) ([raw file](https://github.com/harness/harness-core/blob/dce4ea5c2a9edccd2ed68d7e84193a858875e75f/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L216)):*
> ```Java
> 
>   public List<PerpetualTaskRecord> listBatchOfPerpetualTasksToRebalanceForAccount(String accountId) {
>     markBatchOfPerpetualTasksWithNoHeartBeatToRebalanceForAccount(accountId);
> ```

 listBatchOfPerpetualTasksToRebalanceForAccount called every 5 seconds, this query seems expensive. 



_Code quote:_
```Java
 listBatchOfPerpetualTasksToRebalanceForAccount(
```

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/38087#-ND5JzdcECTPYYz4Q85T:-ND5Jzdd2vmmCus0hycM:bol3q0z) ([raw file](https://github.com/harness/harness-core/blob/dce4ea5c2a9edccd2ed68d7e84193a858875e75f/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L224)):*
> ```Java
>     return query.asList(new FindOptions().limit(BATCH_SIZE_FOR_PERPETUAL_TASK_TO_REBALANCE));
>   }
> ```

i would recommend add as part of DelegateTaskExpiryCheckIterator, if we don't receive HB more than 8 mins we mark regular task as expired., You can add logic here to mark PT's to rebalance

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38087)* status: 0 of 1 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/38087#-ND5IdoDCDop5xwbFfGU:-ND9gWFjCx8ii5laWT4m:b-2jqgtg) ([raw file](https://github.com/harness/harness-core/blob/dce4ea5c2a9edccd2ed68d7e84193a858875e75f/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L216)):*
> listBatchOfPerpetualTasksToRebalanceForAccount
@jennyjames21 how is it called every five seconds?

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 224 at r1](https://reviewable.io/reviews/harness/harness-core/38087#-ND5JzdcECTPYYz4Q85T:-ND9gq7A171uEBDGH2di:b-zhmx5l) ([raw file](https://github.com/harness/harness-core/blob/dce4ea5c2a9edccd2ed68d7e84193a858875e75f/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L224)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i would recommend add as part of DelegateTaskExpiryCheckIterator, if we don't receive HB more than 8 mins we mark regular task as expired., You can add logic here to mark PT's to rebalance
</blockquote></details>

we can not hard code this time, i think @jennyjames21's approach is better. We need to check what was the target interval for the task and if we don't hear a heartbeat for 3 times of that time, we mark that task to be rebalanced.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38087)* status: 2. unresolved discussions.

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java` line 216 at r1](https://reviewable.io/reviews/harness/harness-core/38087#-ND5IdoDCDop5xwbFfGU:-NDA7EtE3TUYj2u2Tfpg:bazel11) ([raw file](https://github.com/harness/harness-core/blob/dce4ea5c2a9edccd2ed68d7e84193a858875e75f/420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java#L216)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

> listBatchOfPerpetualTasksToRebalanceForAccount
@jennyjames21 how is it called every five seconds? 
</blockquote></details>

this is called from account-based iterator on interval on 30s, in prod2 we have 104,017 accounts which means every iteration per account 
Every 30 seconds, we run this query 104,017 times

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38087)* status: 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38087)* status: :shipit: complete! ✓

**Comment by Vbhatia20** [comment]
trigger messagecheck

**Pull request closed without merging**
