### PR TITLE
feat: [CDS-46605]: Pojos for run step

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)

### CODE REVIEW

**Comment by abhinav-harness** [comment]
trigger checkstylecodeformat

**Review by vaibhav-si — COMMENTED** [review]
This step needs to be available in all the stages?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145#-:-NGuWpJx9QAU5XsYhKeU:bfj7my2)* status: 18 file(s) to review. 0 of 1 approvals obtained.

**Comment by abhinav-harness** [comment]
@vaibhav-si yes its a common step - maybe we can skip in CI or FF

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 8 of 12 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)* status: :shipit: complete! ✓

**Review by hextechpal — CHANGES_REQUESTED** [review]
@abhinav-harness why the plugin step first step we need to implement is container step

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145#-:-NGuu6K4B_4WC7jbL7Sw:b-cqypu2)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PmsPluginStepInfoVisitorHelper.java` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/40145#-NGubkqFDXGySsD9eCD5:-NGubkqFDXGySsD9eCD6:b-mchm1z) ([raw file](https://github.com/harness/harness-core/blob/b892c79e8ffd5bda821961cd3cd241ff8a1d7490/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PmsPluginStepInfoVisitorHelper.java#L6)):*
> ```Java
> import io.harness.walktree.visitor.validation.ValidationVisitor;
> 
> public class PmsPluginStepInfoVisitorHelper implements ConfigValidator {
> ```

do we need this?

**Comment by abhinav-harness** [comment]
trigger smartchecks

**Review by hextechpal — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by abhinav-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PmsPluginStepInfoVisitorHelper.java` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/40145#-NGubkqFDXGySsD9eCD5:-NGyiBsA8y0KEBnCFdbF:b-nb1r9) ([raw file](https://github.com/harness/harness-core/blob/b892c79e8ffd5bda821961cd3cd241ff8a1d7490/pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/plugin/PmsPluginStepInfoVisitorHelper.java#L6)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

Will do in followup

**Review by hextechpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145#-:-NGyiKGW-mSc2tWVy9tI:bnfp4nl)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)* status: :shipit: complete! ✓

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 10 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/steps/pluginstep/PmsPluginStepResponse.java` line 12 at r3](https://reviewable.io/reviews/harness/harness-core/40145#-NGykq602oWQ_9ADX1wU:-NGykq602oWQ_9ADX1wV:b-36x4cs) ([raw file](https://github.com/harness/harness-core/blob/957266de1a9dec2948b87864c999eb00aedef4b5/950-delegate-tasks-beans/src/main/java/io/harness/steps/pluginstep/PmsPluginStepResponse.java#L12)):*
> ```Java
> @Data
> @Builder
> public class PmsPluginStepResponse implements DelegateTaskNotifyResponseData {
> ```

Can you please add owner annotation on all classes?

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40145)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/steps/pluginstep/PmsPluginStepResponse.java` line 12 at r3](https://reviewable.io/reviews/harness/harness-core/40145#-NGykq602oWQ_9ADX1wU:-NGyssx46tctnQGjxGzf:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/957266de1a9dec2948b87864c999eb00aedef4b5/950-delegate-tasks-beans/src/main/java/io/harness/steps/pluginstep/PmsPluginStepResponse.java#L12)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can you please add owner annotation on all classes?
</blockquote></details>

discussed offline

**Pull request merged**
