### PR TITLE
[feat]: [PL-29055]: create new NG account settings category, group and individual settings for JWT token. Also completes PL-29866.

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Create new NG default account settings Category (`SCIM`), Group (`scim_jwt_token_configuration_g1`) and 4 different individual settings: `scim_jwt_token_key_field` , `scim_jwt_token_value_field` , `scim_jwt_token_jwks_keys_url` , `scim_jwt_token_service_account_id` 

API endpoint to get all these settings - curl --location --request GET 'http://localdev.harness.io/gateway/ng/api/settings?accountIdentifier=kmpySmUISimoRrJL6NL73w&category=SCIM&group=scim_jwt_token_configuration_g1' 

API endpoint to update these settings in one Go: 
curl --location --request PUT 'http://localdev.harness.io/gateway/ng/api/settings?accountIdentifier=kmpySmUISimoRrJL6NL73w' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "identifier": "scim_jwt_token_jwks_keys_url",
        "value": "https://test.harness.com/adfs/discovery/keys",
        "allowOverrides": false,
        "updateType": "UPDATE"
    },
    {
        "identifier": "scim_jwt_token_key_field",
        "value": "sub",
        "allowOverrides": false,
        "updateType": "UPDATE"
    },
    {
        "identifier": "scim_jwt_token_value_field",
        "value": "TEST098H0000",
        "allowOverrides": false,
        "updateType": "UPDATE"
    },
    {
        "identifier": "scim_jwt_token_service_account_id",
        "value": "PTSA01",
        "allowOverrides": false,
        "updateType": "UPDATE"
    }
]'

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)

### CODE REVIEW

**Review by tiwaritejas — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/40377#-NHQDpP2BSQAtWXXFgkZ:-NHQDpP2BSQAtWXXFgk_:bhi18ef) ([raw file](https://github.com/harness/harness-core/blob/59366ecbf2b3abbef9d39226bbae60039176b22f/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java#L27)):*
> ```Java
>   GOVERNANCE,
>   CHAOS,
>   SCIM
> ```

Have you confirmed this new setting category with the product manager?

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java` line 27 at r2](https://reviewable.io/reviews/harness/harness-core/40377#-NHQDpP2BSQAtWXXFgkZ:-NHSSFif6E_ZL4MKdXZy:bo54hg5) ([raw file](https://github.com/harness/harness-core/blob/59366ecbf2b3abbef9d39226bbae60039176b22f/120-ng-manager/modules/ng-settings/contracts/src/main/java/io/harness/ngsettings/SettingCategory.java#L27)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Have you confirmed this new setting category with the product manager?
</blockquote></details>

Yes, this has been confirmed with PMs and agreed upon, thanks

**Comment by pbarapatre10** [comment]
trigger ti2

**Comment by pbarapatre10** [comment]
trigger ti2

**Review by tiwaritejas — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: :shipit: complete! ✓

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`.github/CODEOWNERS` line 102 at r3](https://reviewable.io/reviews/harness/harness-core/40377#-NHUmMxQ1ZWFV7zdIfrk:-NHUmMxQ1ZWFV7zdIfrl:b-m5q78i) ([raw file](https://github.com/harness/harness-core/blob/7ca108ddada71edd59588545bf99977be9159da6/.github/CODEOWNERS#L102)):*
> ```CODEOWNERS
> /tools/build-cleaner/ gaurav.nanda@harness.io
> 
> /100-migrator/ deepak.puthraya@harness.io manjunatha.etagi@harness.io prabu.rajendran@harness.io
> ```

Looks like you removed this by mistake



_Code quote:_
```CODEOWNERS
prabu.rajendran@harness.io
```

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40377)* status: :shipit: complete! ✓

**Pull request merged**
