### PR TITLE
fix: [CDS-55703]: merging indexes in one to avoid high document scan

### PR DESCRIPTION
**Pull request by lasdox**
## Describe your changes
We have 2 similar queries and 2 indexes to address these queries:
{ accountId, pipelineExecutionId, createdAt }
{ appId, pipelineExecutionId, createdAt }

Sometimes mongo was doing a bad selection for index, leading to a high document scan, slowing down the fetching.
So now we are merging index to be one with all fields:
{ accountId, pipelineExecutionId, createdAt, appId }
This will be a good enough index for both scenarios and avoid the high document scanning
Also this will decrease one index for WFE, which is a problematic collection

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47262)

### CODE REVIEW

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47262)* status: 7 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 134 at r1](https://reviewable.io/reviews/harness/harness-core/47262#-NUUmN_a2GzG9WNjRzB3:-NUUmN_a2GzG9WNjRzB4:b6il6t1) ([raw file](https://github.com/harness/harness-core/blob/ab6255b35b94a691399edde2a216dfba62719a0f/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L134)):*
> ```Java
>                  .build())
>         .add(SortCompoundMongoIndex.builder()
>                  .name(ACCOUNT_ID_PIP_EXECUTIONID_CREATEDAT_APP_ID)
> ```

nit, shouldn't the order be - 

accountId - appid - executionId - createdAt?

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47262)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by lasdox** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/47262)_ status: 7 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 134 at r1](https://reviewable.io/reviews/harness/harness-core/47262#-NUUmN_a2GzG9WNjRzB3:-NUUmN_a2GzG9WNjRzB4:b6il6t1) ([raw file](https://github.com/harness/harness-core/blob/ab6255b35b94a691399edde2a216dfba62719a0f/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L134)):_
> 
> > ```java
> >                  .build())
> >         .add(SortCompoundMongoIndex.builder()
> >                  .name(ACCOUNT_ID_PIP_EXECUTIONID_CREATEDAT_APP_ID)
> > ```
> 
> nit, shouldn't the order be -
> 
> accountId - appid - executionId - createdAt?

That would work only for queries that have appId field.
But we have queries that will only use:   accountId - executionId - createdAt

So to make a single index that both queries can use, we need to set appId as a range field.
Normally I would not do that, but the performance hit is small and WFE has more than 30 indexes, we really need to make it lower.

**Comment by lasdox** [comment]
trigger messagecheck

**Review by vaibhav-si — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47262)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/WorkflowExecution.java` line 134 at r1](https://reviewable.io/reviews/harness/harness-core/47262#-NUUmN_a2GzG9WNjRzB3:-NUWdYTW241jyuqkdoLh:bawaoxh) ([raw file](https://github.com/harness/harness-core/blob/ab6255b35b94a691399edde2a216dfba62719a0f/400-rest/src/main/java/software/wings/beans/WorkflowExecution.java#L134)):*
<details><summary><i>Previously, lasdox (Lucas Sales) wrote…</i></summary><blockquote>

That would work only for queries that have appId field.
But we have queries that will only use:   accountId - executionId - createdAt

So to make a single index that both queries can use, we need to set appId as a range field.
Normally I would not do that, but the performance hit is small and WFE has more than 30 indexes, we really need to make it lower.

</blockquote></details>

Why queries don't use appId? Do you know how many queries are there that don't use appId?

And Mongo query optimizer, won't it still use the same index even if appdId is not in a query?

**Review by rafaelmart1ns — APPROVED** [review]

**Comment by lasdox** [comment]
trigger utAll

**Comment by lasdox** [comment]
trigger utAll

**Comment by lasdox** [comment]
trigger uts

**Pull request merged**
