### PR TITLE
feat: [CDS-50320]: new deployment in Instance sync v2 Migration Logic CG

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)

### CODE REVIEW

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/42521#-NL_cY9qAupSTGKOe9UH:-NLyKaVWC5bGxR3dYhcY:bmjclqb) ([raw file](https://github.com/harness/harness-core/blob/b4a8b1a90dd015d9fb5247a18d0e08a0139aaf24/400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java#L248)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Seems like this query does a call to db for fetching each and every perpertual task, we need to use batching over here incase the number of V1 PT's for a given infraMapping is large.
@namantalaycha10 , please check with db as to how many are there are at max for a given infraMapping. 
</blockquote></details>

this is now changed to get existing PerpetualTaskRecords from the backup collection

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz4vhkC16WsiJ0EOu_:-NLz4vhkC16WsiJ0EOua:bqup8yi) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L118)):*
> ```Java
>     isSupportedCloudProvider(infrastructureMapping.getComputeProviderType());
>     try (AcquiredLock lock = persistentLocker.waitToAcquireLock(
>              InfrastructureMapping.class, infraMappingId, Duration.ofSeconds(200), Duration.ofSeconds(220))) {
> ```

What will happen if we aren't able to acquire lock in 220 seconds? Are we going to lose track of deployment?
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 194 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2Lar8iSkIbuOFxbz:-NLz2Lar8iSkIbuOFxc-:bzamblg) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L194)):*
> ```Java
>     Set<ContainerMetadata> existingContainersMetadata =
>         existingPerpetualTasks.stream()
>             .map(record
> ```

Can we use getContainerMetadataFromPT instead? Are we doing something different here?
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 219 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2Xo259BNeXDt8GpC:-NLz2Xo259BNeXDt8GpD:b-u7cbdg) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L219)):*
> ```Java
>     return containersMetadataToExamine.stream()
>         .map(containerMetadata
>             -> ContainerInstanceSyncPerpetualTaskClientParams.builder()
> ```

Are we doing something different in case of V1 flow? Can we extract in a different method if this logic is same?
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 288 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2qb6AObvGZDgOlhF:-NLz2qb6AObvGZDgOlhG:b-b5fp1l) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L288)):*
> ```Java
>   private PerpetualTaskRecord createForBackup(
>       ContainerInstanceSyncPerpetualTaskClientParams clientParams, InfrastructureMapping infraMapping) {
>     Map<String, String> clientParamMap = new HashMap<>();
> ```

Can we extract common logic between createForBackup and create method in separate methods?
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 315 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2gOJ8g4kDUohzf6l:-NLz2gOJ8g4kDUohzf6m:bqgnd57) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L315)):*
> ```Java
> 
>       PerpetualTaskClientContext clientContext, PerpetualTaskSchedule schedule, String taskDescription) {
>     try (AutoLogContext ignore0 = new AccountLogContext(accountId, OVERRIDE_ERROR)) {
> ```

Not required, not logging anything 
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java` line 246 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz46wK89dYJ44KLg27:-NLz46wK89dYJ44KLg28:b-fayovk) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java#L246)):*
> ```Java
>                                                              .map(id -> perpetualTaskService.getTaskRecord(id))
>                                                              .filter(Objects::nonNull)
>                                                              .collect(Collectors.toList()))
> ```

Please check this documentation https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toList--
As you mutate this list later, Collectors.toList() doesn't guarantee that output collection is mutable. Either follow the doc recommendation, either wrap it new array list
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz4_Y_B3sYSp-VqPoJ:-NLz4_Y_B3sYSp-VqPoK:b-lbjgm) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L42)):*
> ```Java
>       instanceSyncPTBackup.setPerpetualTaskRecordId(perpetualTaskRecord.getUuid());
>     } else {
>       instanceSyncPTBackup.setPerpetualTaskRecordId(UUIDGenerator.generateUuid());
> ```

Then there is no point of NEW_PERPETUAL_TASK_RECORD_ID, you can setup it right away

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)* status: 7 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 194 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2Lar8iSkIbuOFxbz:-NM2BcdaB29EG5HQFmyc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L194)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we use getContainerMetadataFromPT instead? Are we doing something different here?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 219 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2Xo259BNeXDt8GpC:-NM2ICbnEw6l96SXDJPl:bssew63) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L219)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Are we doing something different in case of V1 flow? Can we extract in a different method if this logic is same?
</blockquote></details>

yes in V1 we are actually saving this perpetualTaskRecord but in case of backup we are not,
but now I moved the common code in a separate method and using that
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 288 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2qb6AObvGZDgOlhF:-NM2N2oX-PhdxtCHMUZr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L288)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we extract common logic between createForBackup and create method in separate methods?
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java` line 315 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz2gOJ8g4kDUohzf6l:-NM2NWmYECu8K13S_IPM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/ContainerInstanceSyncPerpetualTaskCreator.java#L315)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Not required, not logging anything 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz4_Y_B3sYSp-VqPoJ:-NM2O-aRCzSjXmvaGLG0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/impl/instance/backup/InstanceSyncPTBackupServiceImpl.java#L42)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Then there is no point of NEW_PERPETUAL_TASK_RECORD_ID, you can setup it right away
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz4vhkC16WsiJ0EOu_:-NM3iSIs83167o9EZNfR:b-ft3zhd) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L118)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

What will happen if we aren't able to acquire lock in 220 seconds? Are we going to lose track of deployment?
</blockquote></details>

As per the code I think, yes we will lose track of deployment. Should we add a retry mechanism here?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)* status: 10 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 86 at r9](https://reviewable.io/reviews/harness/harness-core/42521#-NMDJVfR2KvjOoxWgo6Z:-NMDJVfR2KvjOoxWgo6_:b-pa9iel) ([raw file](https://github.com/harness/harness-core/blob/ebb374efa61d6bee5b022a1ccc9b8faf673f143c/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L86)):*
> ```Java
>   public static final int PERPETUAL_TASK_INTERVAL = 10;
>   public static final int PERPETUAL_TASK_TIMEOUT = 5;
>   public static final int TOTAL_RETRIES = 3;
> ```

let's rename it to HANDLE_NEW_DEPLOYMENT_MAX_RETRIES
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 141 at r9](https://reviewable.io/reviews/harness/harness-core/42521#-NMDJIGZ728_vP_0d1Yb:-NMDJIGZ728_vP_0d1Yc:b-rlmww5) ([raw file](https://github.com/harness/harness-core/blob/ebb374efa61d6bee5b022a1ccc9b8faf673f143c/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L141)):*
> ```Java
>       }
>     }
>     if (retryCount == TOTAL_RETRIES) {
> ```

Let's move this under catch (Exception ex) block, where you'll have something like:
if (retryCount >= TOTAL_RETRIES) {
 throw the exception
}

**Review by namantalaycha10 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521#-:-NMDQ6GQ1rIFsAnhNYZi:bnfp4nl)* status: 10 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 118 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz4vhkC16WsiJ0EOu_:-NMDQ3sL9mTWbvox7OK5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L118)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

As per the code I think, yes we will lose track of deployment. Should we add a retry mechanism here? 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 86 at r9](https://reviewable.io/reviews/harness/harness-core/42521#-NMDJVfR2KvjOoxWgo6Z:-NMDQ0g8DTPxuXwOiAUk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebb374efa61d6bee5b022a1ccc9b8faf673f143c/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L86)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's rename it to HANDLE_NEW_DEPLOYMENT_MAX_RETRIES
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java` line 141 at r9](https://reviewable.io/reviews/harness/harness-core/42521#-NMDJIGZ728_vP_0d1Yb:-NMDQ2-F3pV8xyErAndP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebb374efa61d6bee5b022a1ccc9b8faf673f143c/400-rest/src/main/java/software/wings/instancesyncv2/CgInstanceSyncServiceV2.java#L141)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's move this under catch (Exception ex) block, where you'll have something like:
if (retryCount >= TOTAL_RETRIES) {
 throw the exception
}
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java` line 246 at r3](https://reviewable.io/reviews/harness/harness-core/42521#-NLz46wK89dYJ44KLg27:-NM3JgvF3GF-bh6iqHoK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e5528376604b454f9fda124d006302cab9a1a59b/400-rest/src/main/java/software/wings/service/impl/instance/InstanceSyncPerpetualTaskServiceImpl.java#L246)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Please check this documentation https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toList--
As you mutate this list later, Collectors.toList() doesn't guarantee that output collection is mutable. Either follow the doc recommendation, either wrap it new array list
</blockquote></details>

Done.

**Comment by namantalaycha10** [comment]
trigger ti3

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 9 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42521)* status: :shipit: complete! ✓

**Pull request merged**
