### PR TITLE
feat: [PL-24528]: added scm api for create pull request and get file branch

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33646)

### CODE REVIEW

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33646)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/33646#-N36MSSjCK_qlNGRGwFu:-N36MSSjCK_qlNGRGwFv:bf4zckn) ([raw file](https://github.com/harness/harness-core/blob/74becbbcafd89d391944af40fbda626a5f4c577e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L283)):*
> ```Java
>       @Parameter(description = "File Path") @QueryParam(YamlConstants.FILE_PATH) @NotBlank @NotNull String filePath,
>       @Parameter(description = "Commit Id") @QueryParam(YamlConstants.BRANCH) @NotBlank String branch,
>       @Parameter(description = "Connector Ref") @QueryParam("ConnectorRef") @NotBlank String connectorRef) {
> ```

Use all git related query params from GitSycApiConstants, also these query params do not start with capital letters.

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33646)* status: 4 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/33646#-N36MSSjCK_qlNGRGwFu:-N38mfFnAV_LO4lq_Mr1:bg0b2xn) ([raw file](https://github.com/harness/harness-core/blob/74becbbcafd89d391944af40fbda626a5f4c577e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L283)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Use all git related query params from GitSycApiConstants, also these query params do not start with capital letters.
</blockquote></details>

This API isn't exposed on OpenAPI 3.0 thus you see such inconsistencies. But anyways, let me put it according to the convention just for the sake of it.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/33646#-N36MSSjCK_qlNGRGwFu:-N38ndq33XvR8BBcblo5:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/74becbbcafd89d391944af40fbda626a5f4c577e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L283)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This API isn't exposed on OpenAPI 3.0 thus you see such inconsistencies. But anyways, let me put it according to the convention just for the sake of it.
</blockquote></details>

done

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33646)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/33646#-N36MSSjCK_qlNGRGwFu:-N39Roq90s2mVpgXjLKt:bmlxlym) ([raw file](https://github.com/harness/harness-core/blob/74becbbcafd89d391944af40fbda626a5f4c577e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L283)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

done
</blockquote></details>

Not parameter decriptions, I am asking about queryParam, it should ne "connectorRef" not "ConnectorRef", this will be required by UI for integration, that's why I am asking it for correction.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33646)* status: 5 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33646)* status: :shipit: complete! ✓

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/33646#-N36MSSjCK_qlNGRGwFu:-N3ANBk02NAEBBCIl8Ux:b-3vzg62) ([raw file](https://github.com/harness/harness-core/blob/74becbbcafd89d391944af40fbda626a5f4c577e/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L283)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Not parameter decriptions, I am asking about queryParam, it should ne "connectorRef" not "ConnectorRef", this will be required by UI for integration, that's why I am asking it for correction.
</blockquote></details>

resolving it for now, fix this another ticket

**Pull request merged**
