### PR TITLE
feat: [CDS-40095]: Added UTs for custom remote manifest and fixed bug bash …

### PR DESCRIPTION
**Pull request by GoelPratyush99**
…requests.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35752)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Review by achyuth-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35752)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 447 at r2](https://reviewable.io/reviews/harness/harness-core/35752#-N82D7AAAdf28sdQE6b-:-N82D7AAAdf28sdQE6b0:b-qyjaoq) ([raw file](https://github.com/harness/harness-core/blob/afa6f583adf58dffb4b08d33138f1456b10e15ca/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L447)):*
> ```Java
> 
>   public TaskChainResponse executeK8sTask(Ambiance ambiance, StepElementParameters stepElementParameters,
>       NativeHelmStepExecutor nativeHelmStepExecutor, K8sStepPassThroughData k8sStepPassThroughData,
> ```

why have we newly added this method?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35752)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java` line 447 at r2](https://reviewable.io/reviews/harness/harness-core/35752#-N82D7AAAdf28sdQE6b-:-N82HO8nBAWiDv2R_gTU:b-lf9q6a) ([raw file](https://github.com/harness/harness-core/blob/afa6f583adf58dffb4b08d33138f1456b10e15ca/125-cd-nextgen/src/main/java/io/harness/cdng/helm/NativeHelmStepHelper.java#L447)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

why have we newly added this method?
</blockquote></details>

Earlier even when we didn't had any git type stores in aggregate values manifest we were calling for a Git Fetch Task. Now we will skip it if its not required. Part of Bug Bash discussion.

**Review by achyuth-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35752)* status: :shipit: complete! ✓

**Pull request merged**
