### PR TITLE
[feat]: [PIE-8378]: Introduce rollback execution mode

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPajk401cowBnf2Cxyw:-NPajk401cowBnf2Cxyx:bc2piyp) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L485)):*
> ```Java
>       log.info("[PMS_PLAN] Time taken to complete plan: {}ms ", endTs - startTs);
>       if (isRetry) {
>         Plan newPlan = retryExecutionHelper.transformPlan(
> ```

we should define a method which handle modifying plan rather than in this method, as now there are types of plan modification
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 490 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPajQlT7H57MrAFd2Q1:-NPajQlU6GnXYh17W8ow:b-xfptyl) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L490)):*
> ```Java
>       }
>       ExecutionMode executionMode = executionMetadata.getExecutionMode();
>       if (executionMode.equals(ExecutionMode.POST_EXECUTION_ROLLBACK)) {
> ```

what if executionMode is null?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPajw9IA-CLS6nnVZco:-NPajw9IA-CLS6nnVZcp:b-pmenqe) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L155)):*
> ```Java
>   }
> 
>   // todo: check if we need to take notifyOnlyUser and isDebug
> ```

check with CI team
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPamFZ45NoYlk1U0GK4:-NPamFZ45NoYlk1U0GK5:bmta1a9) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L67)):*
> ```Java
>     return planExecutionMetadata.withPlanExecutionId(planExecutionID)
>         .withProcessedYaml(transformProcessedYaml(planExecutionMetadata.getProcessedYaml()))
>         .withUuid(null); // this uuid is the mongo uuid
> ```

so why null?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPamJbw2T_j8kouzcQb:-NPamJbw2T_j8kouzcQc:b6nqfir) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L70)):*
> ```Java
>   }
> 
>   private String transformProcessedYaml(String processedYaml) {
> ```

add comments what we are doing

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 490 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPajQlT7H57MrAFd2Q1:-NPan4qy4t0nzX8-sstF:bngj1k1) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L490)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what if executionMode is null?
</blockquote></details>

It cant be null as is in a proto object
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPajw9IA-CLS6nnVZco:-NPan8HxDXiLOBxDfkgQ:bm1f58q) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java#L155)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check with CI team
</blockquote></details>

Will check and update in a separate PR if needed

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPamFZ45NoYlk1U0GK4:-NPaoITF1c7WuoUVxeaE:b-bttoee) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L67)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

so why null?
</blockquote></details>

Added comment
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPamJbw2T_j8kouzcQb:-NPaoKOQAkdZ96kxJ4Od:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L70)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments what we are doing 
</blockquote></details>

Done.

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 10 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 485 at r2](https://reviewable.io/reviews/harness/harness-core/44670#-NPajk401cowBnf2Cxyw:-NPb21Gg5TWx3DfxCOr8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2eccc32e2b54aa702a095143825a0f1d87fa8026/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L485)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should define a method which handle modifying plan rather than in this method, as now there are types of plan modification
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 491 at r4](https://reviewable.io/reviews/harness/harness-core/44670#-NPcMdV62cczCxdtj_6J:-NPcMdV62cczCxdtj_6K:bwos1e9) ([raw file](https://github.com/harness/harness-core/blob/32b00296f95773be31b91d701437797baedae826/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L491)):*
> ```Java
>   }
> 
>   Plan transformPlan(PlanCreationBlobResponse resp, Plan plan, boolean isRetry, List<String> identifierOfSkipStages,
> ```

Shall we create a factory for this? Based on mode, we can bind the implementation which would transform plan to us. This way we will reduce a lot of ifs

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 491 at r4](https://reviewable.io/reviews/harness/harness-core/44670#-NPcMdV62cczCxdtj_6J:-NPcMrkd1ldka2qEA8x9:bbupkdq) ([raw file](https://github.com/harness/harness-core/blob/32b00296f95773be31b91d701437797baedae826/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L491)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Shall we create a factory for this? Based on mode, we can bind the implementation which would transform plan to us. This way we will reduce a lot of ifs 
</blockquote></details>

transformPlan can be one function in a base interface which both retryHelper and rollbackModeExecutionHelper can implement. 
If no implementation, then this would do a no op.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java` line 103 at r4](https://reviewable.io/reviews/harness/harness-core/44670#-NPcNAmu4chMLlfRM_k2:-NPcNAmu4chMLlfRM_k3:bbie2yv) ([raw file](https://github.com/harness/harness-core/blob/32b00296f95773be31b91d701437797baedae826/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResourceImpl.java#L103)):*
> ```Java
>     // pipelineIdentifier needed for access control check
>     PlanExecution planExecution =
>         pipelineExecutor.startPostExecutionRollback(accountId, orgIdentifier, projectIdentifier, planExecutionId);
> ```

not sure but will a new class help us not clutter the pipelineExecutor?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 491 at r4](https://reviewable.io/reviews/harness/harness-core/44670#-NPcMdV62cczCxdtj_6J:-NPpc_0d55_wfvlN2ZW_:b884wiw) ([raw file](https://github.com/harness/harness-core/blob/32b00296f95773be31b91d701437797baedae826/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L491)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

transformPlan can be one function in a base interface which both retryHelper and rollbackModeExecutionHelper can implement. 
If no implementation, then this would do a no op.
</blockquote></details>

As discussed, please create tickets for this.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44670)* status: :shipit: complete! ✓

**Pull request merged**
