### PR TITLE
feat: [PL-23035]: added new git sync setting account level

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30827)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30827)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/GitSyncSettings.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30827#-Mw4R7U80tlqbPm7LvQa:-Mw4R7U80tlqbPm7LvQb:b-xms8v7) ([raw file](https://github.com/harness/harness-core/blob/a89da00b16623a60408d4f4d79fbda767a9cd59d/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/GitSyncSettings.java#L25)):*
> ```Java
> @NoArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> @TypeAlias("io.harness.ng.core.accountsetting.dto.GitSyncSettings")
> ```

TypeAlias should not be package name. It becomes difficult to do refactoring later on when we have to move the classes around.

**Comment by mohitg0795** [comment]
___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/GitSyncSettings.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30827#-Mw4R7U80tlqbPm7LvQa:-Mw5N7ZlDXiAbTWdKYjJ:bxh88x3) ([raw file](https://github.com/harness/harness-core/blob/a89da00b16623a60408d4f4d79fbda767a9cd59d/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/GitSyncSettings.java#L25)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

TypeAlias should not be package name. It becomes difficult to do refactoring later on when we have to move the classes around.
</blockquote></details>

This is in accordance to the earlier dtos for accountSettingsConfig. We will need to change those as well if we change here.

**Comment by mohitg0795** [comment]
___
*[950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/GitSyncSettings.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30827#-Mw4R7U80tlqbPm7LvQa:-Mw5N7ZlDXiAbTWdKYjJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/a89da00b16623a60408d4f4d79fbda767a9cd59d/950-ng-core/src/main/java/io/harness/ng/core/accountsetting/dto/GitSyncSettings.java#L25)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

TypeAlias should not be package name. It becomes difficult to do refactoring later on when we have to move the classes around.
</blockquote></details>

done

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30827)* status: :shipit: complete! ✓

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30827#-:-Mw6O08g9TbJuvMqOUWs:bnfp4nl)* status: :shipit: complete! ✓

**Comment by mohitg0795** [comment]
trigger codeformat

**Comment by mohitg0795** [comment]
trigger messagecheck

**Review by meenakshi-harness — APPROVED** [review]

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/30827)

**Pull request closed without merging**
