### PR TITLE
[feat]: [CDS-69450]: Added the revert API for migration for Overrides V2 Feature 

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
This API reverts the migration done for Overrides V1 to V2. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48218)

### CODE REVIEW

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 341 at r2](https://reviewable.io/reviews/harness/harness-core/48218#-NWCFjCX4B3-o_2_M-q8:-NWCFjCX4B3-o_2_M-q9:b9mw8p0) ([raw file](https://github.com/harness/harness-core/blob/23afec84a63637176a67ab827bf5c85f77758600/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L341)):*
> ```Java
> 
>   @POST
>   @Path("/revertMigrate")
> ```

Lets call it "revertMigration"

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 343 at r2](https://reviewable.io/reviews/harness/harness-core/48218#-NWCKakp276TkOwHpx-a:-NWCKakp276TkOwHpx-b:b92uv91) ([raw file](https://github.com/harness/harness-core/blob/23afec84a63637176a67ab827bf5c85f77758600/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L343)):*
> ```Java
>   @Path("/revertMigrate")
>   @Hidden
>   @ApiOperation(value = "Revert Migrate ServiceOverride to V2", nickname = "revertMigrateServiceOverride")
> ```

"to V2" seems confusing.
"Revert ServiceOverride V2 Migration" would be good enough

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverrideV2MigrationServiceImpl.java` line 436 at r2](https://reviewable.io/reviews/harness/harness-core/48218#-NWCki3L0CyLIxjnVukQ:-NWCki3L0CyLIxjnVukR:b-f3jvcq) ([raw file](https://github.com/harness/harness-core/blob/23afec84a63637176a67ab827bf5c85f77758600/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverrideV2MigrationServiceImpl.java#L436)):*
> ```Java
>   }
> 
>   @NotNull
> ```

Lets not use jetbrains annotations. instead use lombok @NonNull

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverrideV2MigrationServiceImpl.java` line 633 at r3](https://reviewable.io/reviews/harness/harness-core/48218#-NWHhcRUCnDLb7O6A8HA:-NWHhcRUCnDLb7O6A8HB:b-s8wz1f) ([raw file](https://github.com/harness/harness-core/blob/babd457f493c8223545b58fc767f0a0789ff532f/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/helpers/serviceoverridesv2/services/ServiceOverrideV2MigrationServiceImpl.java#L633)):*
> ```Java
>         if (isNotEmpty(overridesEntitiesAlreadyPresent)) {
>           for (NGServiceOverridesEntity entity : overridesEntitiesAlreadyPresent) {
>             Query query2 = new Query(Criteria.where(NGServiceOverridesEntityKeys.id).is(entity.getId()));
> ```

our override entity is not coming from DB, We need to use accountId + identifier  criteria.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48218)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Comment by lovish1999** [comment]
trigger uts

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48218)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48218)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger ut2

**Comment by lovish1999** [comment]
trigger ut2

**Comment by harshjain12** [comment]
trigger ut2

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48218)* status: :shipit: complete! ✓

**Comment by lovish1999** [comment]
trigger review

**Pull request merged**
