### PR TITLE
feat: [CCM-9682]: API changes for ec2 recommendations

### PR DESCRIPTION
**Pull request by divyanshuchaubisa**
## Describe your changes
* Changes related to the ec2 recommendation apis and utilisation data api.
* Helper classes to fetch the data from dao classess.
* Used Converter pattern to convert the entity response to DTO to return back to the UI layer.
Design doc: https://harness.atlassian.net/wiki/spaces/CE/pages/21188444200/Design+Doc+EC2+Recommendation

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39889)

### CODE REVIEW

**Comment by divyanshuchaubisa** [comment]
trigger messagecheck

**Review by svmav — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 8 of 12 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39889)* status: Some of the checks are too old. 9 file(s) to review. 0 of 1 approvals obtained.

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39889)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/recommendation/RESTWrapperRecommendationDetails.java` line 223 at r4](https://reviewable.io/reviews/harness/harness-core/39889#-NGp1UKHBDaFMVJE_sgE:-NGp1UKHBDaFMVJE_sgF:b-mt0wo3) ([raw file](https://github.com/harness/harness-core/blob/80fb2c709c7250159ad2700bddd5702866e1c8ea/ce-nextgen/service/src/main/java/io/harness/ccm/remote/resources/recommendation/RESTWrapperRecommendationDetails.java#L223)):*
> ```Java
>             content = { @Content(mediaType = MediaType.APPLICATION_JSON) })
>       })
>   public ResponseDTO<EC2RecommendationDTO>
> ```

Add Schema and description on the response objects

**Review by svmav — DISMISSED** [review]
> Reviewed 3 of 6 files at r2, 3 of 12 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39889)* status: Some of the checks are too old.

**Review by svmav — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39889)* status: :shipit: complete! ✓

**Pull request merged**
