### PR TITLE
fix: [PIE-4727]: Add try/catch around pipeline service call

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- When the pipeline service throws a runtime exception it was propagated and the UI did not receive the updates as expected. The user guess that execution was stuck but it is not.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36310)

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36310#-N9GB6z7B525rVVUm6oW:-N9GB6z7B525rVVUm6oX:baqmey7) ([raw file](https://github.com/harness/harness-core/blob/6e6724f4da7c257f2159f47ba3c478535c92f727/pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L147)):*
> ```Java
>   private PipelineEntity getPipelineEntity(
>       String accountId, String orgIdentifier, String projectIdentifier, String pipelineIdentifier) {
>     try {
> ```

can you put try with auto log context?



_Code quote:_
```Java
try {
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36310#-N9GB6z7B525rVVUm6oW:-N9GKFjC-SDDwCEbMbIF:b32v57) ([raw file](https://github.com/harness/harness-core/blob/6e6724f4da7c257f2159f47ba3c478535c92f727/pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L147)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you put try with auto log context?
</blockquote></details>

+1

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)* status: Some of the checks are too old. 1 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)* status: Some of the checks are too old. 1 file(s) to review. 2 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36310#-N9GB6z7B525rVVUm6oW:-N9aPStYAMuNkUt5iqam:b8ktdho) ([raw file](https://github.com/harness/harness-core/blob/6e6724f4da7c257f2159f47ba3c478535c92f727/pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service/PMSResourceConstraintServiceImpl.java#L147)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

both auto log context can be combined together

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36310)* status: :shipit: complete! ✓

**Pull request merged**
