### PR TITLE
[fix]:[CCM-9950]: Added accountId filter in query in instanceData Collection

### PR DESCRIPTION
**Pull request by abhinavsingh-ccm**
## Describe your changes

Index Creation: 

`db.getCollection("instanceData").createIndex({ "accountId": 1, "instanceId": 1 }, {"name": "accountId_instanceId", background: true } )`

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40457)

### CODE REVIEW

**Review by svmav — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40457)* status: :shipit: complete! ✓

**Review by hitesharinga — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 13 of 14 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40457)* status: Some of the checks are too old.

**Comment by abhinavsingh-ccm** [comment]
trigger tin0, tin1, ti2, tin3, tin4

**Comment by abhinavsingh-ccm** [comment]
trigger smartchecks

**Comment by abhinavsingh-ccm** [comment]
trigger messagecheck

**Comment by abhinavsingh-ccm** [comment]
trigger ti3

**Review by trunapushpa — APPROVED** [review]

**Pull request merged**
