### PR TITLE
[feat]: [SRM-13725]: refactored deeplink URL to seperate service.

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)

### CODE REVIEW

**Review by dhruv-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: :shipit: complete! ✓

**Review by dhruv-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: :shipit: complete! ✓

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNG-7rV74eB9WAdz7KC:-NNG-7rV74eB9WAdz7KD:by4y2eb) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L37)):*
> ```Java
>     if (cvConfig instanceof PrometheusCVConfig) {
>       PrometheusCVConfig prometheusCVConfig = (PrometheusCVConfig) cvConfig;
>       if (prometheusCVConfig.getMetricInfos() != null) {
> ```

nit: CollectionUtils.emptyIfNull() a cleaner option that null check if using streams.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNG0Tvq6_VT5RB8E5VG:-NNG0Tvq6_VT5RB8E5VH:baa1yuk) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L48)):*
> ```Java
>         if (connectorInfoDTO.isPresent() && metricInfo.isPresent()) {
>           PrometheusConnectorDTO connectorConfigDTO =
>               (PrometheusConnectorDTO) connectorInfoDTO.get().getConnectorConfig();
> ```

All this will be common for all healthSources no? Then this shouldn't be inside Prometheus if condition



_Code quote:_
```Java
    if (cvConfig instanceof PrometheusCVConfig) {
      PrometheusCVConfig prometheusCVConfig = (PrometheusCVConfig) cvConfig;
      if (prometheusCVConfig.getMetricInfos() != null) {
        Optional<PrometheusCVConfig.MetricInfo> metricInfo =
            prometheusCVConfig.getMetricInfos()
                .stream()
                .filter(metricInfoInList -> metricIdentifier.equals(metricInfoInList.getIdentifier()))
                .findFirst();
        Optional<ConnectorInfoDTO> connectorInfoDTO =
            nextGenService.get(prometheusCVConfig.getAccountId(), prometheusCVConfig.getConnectorIdentifier(),
                prometheusCVConfig.getOrgIdentifier(), prometheusCVConfig.getProjectIdentifier());
        if (connectorInfoDTO.isPresent() && metricInfo.isPresent()) {
          PrometheusConnectorDTO connectorConfigDTO =
              (PrometheusConnectorDTO) connectorInfoDTO.get().getConnectorConfig();
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNFzO2ZAAOCFvzWmE_6:-NNFzO2ZAAOCFvzWmE_7:bml6lff) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L61)):*
> ```Java
>             uriBuilder.addParameter("g0.g0.end_input", endTime.format(formatter)); // eg. YYYY-MM-DD HH:MM
>             deeplinkURL = Optional.ofNullable(uriBuilder.build().toString());
>           } catch (URISyntaxException ignored) {
> ```

Log the caught exception



_Code quote:_
```Java
deeplinkURL;
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImplTest.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNFz9dd3vRPfEuqHi4M:-NNFz9dd3vRPfEuqHi4N:b-bv6gcc) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImplTest.java#L73)):*
> ```Java
>         + "\n"
>         + "}";
>     CVConfig prometheusCVConfig = PrometheusCVConfig.builder()
> ```

nit: Please use from Builder Factory

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: 1 change requests. 4. unresolved discussions. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 37 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNG-7rV74eB9WAdz7KC:-NNG75Dl0IlG6ezmXmcI:bn29mqr) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L37)):*
> will address 
will address 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNG0Tvq6_VT5RB8E5VG:-NNG2aXl9eHldHwyGfFx:b-ulu2ok) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L48)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

All this will be common for all healthSources no? Then this shouldn't be inside Prometheus if condition
</blockquote></details>

no the metric info is different for all classes PrometheusCVConfig.MetricInfo , same goes for PrometheusConnectorDTO
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNFzO2ZAAOCFvzWmE_6:-NNG2mlU6RmdkIxqzTbP:b-hh3s17) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L61)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Log the caught exception
</blockquote></details>

will address 
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImplTest.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNFz9dd3vRPfEuqHi4M:-NNG76X88N9xXhESzIwX:b-hh3s17) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImplTest.java#L73)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: Please use from Builder Factory
</blockquote></details>

will address

**Review by n00bitax — COMMENTED** [review]
fixed all issues, please check again

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198#-:-NNGmJ2f10rcgGUIHudb:bacutao)* status: 3 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained.

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/43198#-NNG0Tvq6_VT5RB8E5VG:-NNKZ_KQDLr8-SkAP7x8:b-ehyykx) ([raw file](https://github.com/harness/harness-core/blob/0aae215d9410b1b515d00e53969938d32390f7bc/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L48)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

no the metric info is different for all classes PrometheusCVConfig.MetricInfo , same goes for PrometheusConnectorDTO
</blockquote></details>

Yes but all MetricCVConfigs have getMetricInfos(), and the above methods could have been common and doesnt need to be repeated for all metricCVConfigs
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java` line 50 at r5](https://reviewable.io/reviews/harness/harness-core/43198#-NNKZEt0D1CzfuHCK6dF:-NNKZEt0D1CzfuHCK6dG:bsk348y) ([raw file](https://github.com/harness/harness-core/blob/a3d3971eaa8afb04965c2418e2325e113ed75cd6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DeeplinkURLServiceImpl.java#L50)):*
> ```Java
>     Optional<String> deeplinkURL = Optional.empty();
>     String baseUrl;
>     if (cvConfig instanceof PrometheusCVConfig) {
> ```

This should have been cvConfig instance of MetricCVConfig

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java` line 400 at r9](https://reviewable.io/reviews/harness/harness-core/43198#-NN_oHRj4Kis2wDWtxx-:-NN_oHRl0iYmalK959w2:b6nfn2c) ([raw file](https://github.com/harness/harness-core/blob/2dac19fbb98d5073054297f77a88c450747b09f6/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L400)):*
> ```Java
>         continue;
>       }
>       Instant startTime = VerifyStepMetricsAnalysisUtils.getStartTimeForDeeplinkURL(verificationJobInstance);
> ```

We can reuse the testDataTimeRange

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r7, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java` line 494 at r10](https://reviewable.io/reviews/harness/harness-core/43198#-NNaxvXsEPEeeKhSe5sq:-NNaxvXt9hoAVV0XP46r:b-z57bev) ([raw file](https://github.com/harness/harness-core/blob/a5bccaa70e7e6ae44ee68abae77ccfcb604872bf/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java#L494)):*
> ```Java
>         .filter(MetricDefinition::isIncluded)
>         .map(metricDefinition -> {
>           return MetricsAnalysis.builder()
> ```

nit: code block with return is redundant

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43198)* status: :shipit: complete! ✓

**Pull request merged**
