### PR TITLE
feat: [PIE-3853]: Changes in engine to support matrix

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33653)

### CODE REVIEW

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33653)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33653)* status: 24 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33653)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/33653#-N3JvOs58O94k1KQIP6P:-N3JvOs6E5vPU4DrQKCe:b-xgz960) ([raw file](https://github.com/harness/harness-core/blob/2b06166032c9537d72edec4ba9de528d3ab48e91/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L54)):*
> ```Java
>       if (checkForStrategy && isWrappedUnderStrategy(stageField)) {
>         return adviserObtainments;
>       }
> ```

shouldnt this be given preference than parallel one?



_Code quote:_
```Java
      if (checkForStrategy && isWrappedUnderStrategy(stageField)) {
        return adviserObtainments;
      }
```

**Comment by sahilhindwani-harness** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/33653#-N3JvOs58O94k1KQIP6P:-N3K2nUn7m4JzRYAjthg:bkbvskt) ([raw file](https://github.com/harness/harness-core/blob/2b06166032c9537d72edec4ba9de528d3ab48e91/878-ng-common-utilities/src/main/java/io/harness/plancreator/strategy/StageStrategyUtils.java#L54)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt this be given preference than parallel one?
</blockquote></details>

I did not get the question. Both of them are independent so it should not matter as to what gets checked first?

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33653)* status: :shipit: complete! ✓

**Pull request merged**
