### PR TITLE
[feat]: [CDS-72699]: Added setting for Repo based Filtering.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49623)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 386 at r1](https://reviewable.io/reviews/harness/harness-core/49623#-NYq3MG0AvIWukU31GGQ:-NYq3MG0AvIWukU31GGR:bid9wfu) ([raw file](https://github.com/harness/harness-core/blob/9d2ee5f27716b015a28936f50d8c06a8b4c77f27/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L386)):*
> ```YAML
>       - ORGANIZATION
>       - PROJECT
>   - identifier: git_experience_repo_allowlist
> ```

Can we add a comment explaining what this setting does so that other devs if working on it might know what it is doing?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49623)* status: 1 file(s) to review.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49623)* status: 1 file(s) to review. 1. unresolved discussions. 

___
*[`120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml` line 386 at r1](https://reviewable.io/reviews/harness/harness-core/49623#-NYq3MG0AvIWukU31GGQ:-NYq5sG5D7497JhLj633:bjh2cih) ([raw file](https://github.com/harness/harness-core/blob/9d2ee5f27716b015a28936f50d8c06a8b4c77f27/120-ng-manager/modules/ng-settings/src/main/resources/io/harness/ngsettings/settings.yml#L386)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a comment explaining what this setting does so that other devs if working on it might know what it is doing?
</blockquote></details>

Comments in settings.yml is generally avoided i would add some comments in the service layers and constants file. Will include in the next PR, have some PR lined up for this feature.

**Comment by senjucanon2** [comment]
trigger review

**Review by nishantsaini20 — APPROVED** [review]

**Pull request merged**
