### PR TITLE
[fix]: [PIE-6574]: Fixing all strategy stages coming in retry-failed-pipeline even of the stage was skipped

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Fixing all strategy-stages coming in stages list for retry-failed-pipeline from which we can start the retry even when the the stages were skipped. Only the success stages should come.

What is fix: Currently when the stages inside strategy are skipped, we mark the strategy status as success. Now making a fix in strategy-step so that it will be marked as SKIPPED if all stages inside it was skipped.
Check the below screen-shot, the strategy status was coming success and the pipeline failed before that. Later ss is after the fix.
Screenshot 2022-11-28 at 1 18 38 PM

Screenshot 2022-11-28 at 1 20 00 PM

Testing: Ran some basic strategy pipeline to test the normal flows. Tested the retry-failed-pipeline flow and verified that the underlying issue is fixed and strategy status is set to SKIPPED.
Added unit-test for the method i made a change in.

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40712)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40712)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/40712#-NHxDOfAEpJ-bgT5ERQv:-NHxDOfAEpJ-bgT5ERQw:bsjhsnv) ([raw file](https://github.com/harness/harness-core/blob/823065b25dad5079e038ff296d16af87fed11701/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java#L154)):*
> ```Java
>                 .filter(o -> ((StepResponseNotifyData) o).getStatus() == Status.SKIPPED)
>                 .count()
>             == responseDataMap.size()) {
> ```

Shouldnt we use calculate status method here?



_Code quote:_
```Java
        || responseDataMap.values()
                .stream()
                .filter(o -> ((StepResponseNotifyData) o).getStatus() == Status.SKIPPED)
                .count()
            == responseDataMap.size()) {
```

**Comment by brijeshdhakar** [comment]
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java` line 154 at r1](https://reviewable.io/reviews/harness/harness-core/40712#-NHxDOfAEpJ-bgT5ERQv:-NHxRCmP-LXFFplqfhcg:bm87z3u) ([raw file](https://github.com/harness/harness-core/blob/823065b25dad5079e038ff296d16af87fed11701/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/steps/matrix/StrategyStep.java#L154)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Shouldnt we use calculate status method here?
</blockquote></details>

CalculateStatus does not include the skipped statuses. And here we are calculating the strategy status from its children stages/steps. if all skipped then skipped else, the calculateStatus flow will be called for other statuses.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40712)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger codebasehash

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40712)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40712)* status: :shipit: complete! ✓

**Comment by abhayganvir** [comment]
trigger testcopyrightcheck

**Comment by abhayganvir** [comment]
trigger testcopyrightcheck

**Pull request merged**
