### PR TITLE
[feat]: [CCM-5534]: Perspective Notification Setting APIs

### PR DESCRIPTION
**Pull request by svmav**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31663)

### CODE REVIEW

**Review by hitesharinga — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31663)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31663#-MzFM4EuA5bVPEr_-jY6:-MzFM4EuA5bVPEr_-jY7:b8zcgbc) (no related file):*
We need to add Unit Test coverage for this. 

And Can we delete all the notification settings & budgets when we delete perspective? 

---

**Review by svmav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31663)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31663#-MzFM4EuA5bVPEr_-jY6:-MzQbMfl2k-bGzJRntSL:b-896fix) (no related file):*
<details><summary><i>Previously, hitesharinga (Hitesh Aringa) wrote…</i></summary><blockquote>

We need to add Unit Test coverage for this. 

And Can we delete all the notification settings & budgets when we delete perspective? 
</blockquote></details>

Done.

---

**Review by hitesharinga — DISMISSED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31663)* status: :shipit: complete! ✓

**Review by hitesharinga — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31663#-:-MzZ8zfE1Dw4bULoMF2C:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
