### PR TITLE
[feat]: [CDS-42716]: Deployment freeze RBAC with Global Freeze CRUD

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38097)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 15 Issues 
* Code issue 9 Code issues 
* Anti-pattern 6 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38097)

**Review by reetika04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38097)* status: 15 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1227 at r2](https://reviewable.io/reviews/harness/harness-core/38097#-NDW988uBjivxf5z7oId:-NDW988uBjivxf5z7oIe:b-buolwp) ([raw file](https://github.com/harness/harness-core/blob/dba9022c8a18d086ec74921e61580d8a32711146/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1227)):*
> ```YAML
>     name: View CCM Overview page
>     status: ACTIVE
>     includedInAllRoles: false
> ```

Please update the version of the file

**Comment by Abhishek-CDC** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1227 at r2](https://reviewable.io/reviews/harness/harness-core/38097#-NDW988uBjivxf5z7oId:-NDWkDy07F5kTO6NxaDp:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/dba9022c8a18d086ec74921e61580d8a32711146/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1227)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

Please update the version of the file
</blockquote></details>

Done

**Review by reetika04 — APPROVED** [review]
> Reviewed 4 of 13 files at r1, 8 of 11 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38097)* status: :shipit: complete! ✓

**Pull request merged**
