### PR TITLE
feat: [SSCA-636]: SLSA Verification step execution changes

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52679)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger uts

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52679)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SlsaVerificationStep.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/52679#-Ne1vE1LC0EbxV_hkR9o:-Ne1vE1LC0EbxV_hkR9p:b-akvw5i) ([raw file](https://github.com/harness/harness-core/blob/fa74888ad876d43e6c1b2f63aaea6e2c45a40c5d/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SlsaVerificationStep.java#L36)):*
> ```Java
> public class SlsaVerificationStep extends AbstractStepExecutable {
>   public static final StepType STEP_TYPE = SscaConstants.SLSA_VERIFICATION_STEP_TYPE;
>   private static final String PREDICATE_TYPE = "https://slsa.dev/provenance/v1";
> ```

nit: let's move this to SscaConstants. It's being used in multiple places now.
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SlsaVerificationStep.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/52679#-Ne1vUjL6C69bhv_6oov:-Ne1vUjL6C69bhv_6oow:bq6h70e) ([raw file](https://github.com/harness/harness-core/blob/fa74888ad876d43e6c1b2f63aaea6e2c45a40c5d/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SlsaVerificationStep.java#L68)):*
> ```Java
>     if (slsaVerificationStepInfo != null && slsaVerificationStepInfo.getSource() != null) {
>       String identifier = stepParameters.getIdentifier();
>       SlsaDockerSourceSpec slsaDockerSourceSpec = (SlsaDockerSourceSpec) slsaVerificationStepInfo.getSource().getSpec();
> ```

Check the type before casting to SlsaDockerSourceSpec

**Comment by reetika04** [comment]
trigger uts

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52679)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SlsaVerificationStep.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/52679#-Ne1vUjL6C69bhv_6oov:-Ne20AWl3sMay2y4MydT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa74888ad876d43e6c1b2f63aaea6e2c45a40c5d/332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SlsaVerificationStep.java#L68)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Check the type before casting to SlsaDockerSourceSpec
</blockquote></details>

Done.

**Comment by reetika04** [comment]
trigger uts

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52679)* status: Waiting on team(s): sto.

**Review by harshjain12 — APPROVED** [review]

**Pull request merged**
