### PR TITLE
[fix]: [PL-40491]: Upgrades debezium version to 1.9.7 to work with mongo 5

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Current version of debezium 1.7.2 not working with mongo 5.0, getting below error
```
2023-08-04 10:40:26,745 [aggregator-PRIMARY-1] ERROR io.debezium.embedded.EmbeddedEngine - Stopping connector after error in the application's handler method: Unable to process Mongo Operation, a '$set' or '$unset' is necessary for partial updates or '_id' is expected for full Document replaces.  
org.apache.kafka.connect.errors.ConnectException: Unable to process Mongo Operation, a '$set' or '$unset' is necessary for partial updates or '_id' is expected for full Document replaces.
```
Upgrading debezium version to 1.9.7 to work with mongo 5
- After upgrade observed issue where ACL not being deleted after role-assignment delete
- found issue that it is not deserializing mongo document _id to id field mentioned in Java entity. Possible breaking change https://debezium.io/releases/1.8/release-notes#breaking_changes_2
- Tried to change configuration of JsonSerDe being used by debezium for deserialization but it did not work. https://debezium.io/documentation/reference/1.9/integrations/serdes.html#_json_serde

Finally It started working after adding @JsonProperty on Java entities id field as below. This is to explicitly deserialize _id field to id
```
public class RoleAssignmentDBO implements PersistentEntity, AccessControlEntity {
  @JsonProperty("_id")
  @Setter @Id @dev.morphia.annotations.Id String id;
```
Tests: 
- Verified in local and it was able to deserialize _id from change event correctly
- Role-assignment creation/deletion working fine
- Verified changes with mongo 4 and 5. It's working 
- QA Automation ran successfully for both mongo 4 and 5 with this change 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51370)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger ut2, ut6, ut7

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
trigger messagecheck

**Comment by ashishsanodia-harness** [comment]
trigger ut9

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51370#-:-NbIc8Hi4NE3Kaehe6aQ:bnfp4nl)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51370#-:-NbIss8o7ncY6pyUOTTR:bnfp4nl)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/privileged/persistence/PrivilegedRoleAssignmentDBO.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/51370#-NbIt2ONCi6Ro7BDmC4H:-NbIt2ONCi6Ro7BDmC4I:b1tulys) ([raw file](https://github.com/harness/harness-core/blob/9cb00c1fea6a67371054715fcc9f56733b941b1a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/privileged/persistence/PrivilegedRoleAssignmentDBO.java#L64)):*
> ```Java
> public class PrivilegedRoleAssignmentDBO implements PersistentEntity, AccessControlEntity {
>   public static final String COLLECTION_NAME = "privilegedRoleAssignments";
>   @JsonProperty("_id") @Setter @Id @dev.morphia.annotations.Id String id;
> ```

Is this issue with Deserialization for Debezium only or with any Java entity with Mongo-5? If issue only with Debezium then we dont need to add for PrivilegedRoleAssignmentDBO?

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/privileged/persistence/PrivilegedRoleAssignmentDBO.java` line 64 at r2](https://reviewable.io/reviews/harness/harness-core/51370#-NbIt2ONCi6Ro7BDmC4H:-NbJRiFM7kXJlFqE3Pee:bwbxwrm) ([raw file](https://github.com/harness/harness-core/blob/9cb00c1fea6a67371054715fcc9f56733b941b1a/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/privileged/persistence/PrivilegedRoleAssignmentDBO.java#L64)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Is this issue with Deserialization for Debezium only or with any Java entity with Mongo-5? If issue only with Debezium then we dont need to add for PrivilegedRoleAssignmentDBO?
</blockquote></details>

Fixed. Keeping _id in entities for which we are consuming change events.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51370)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger ut7

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Pull request merged**
