### PR TITLE
feat: [CDS-56625]: Introduce new Exception AlreadyExistingTemplates for isNewTemplate case

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
```
{
    "status": "ERROR",
    "code": "TEMPLATE_ALREADY_EXISTS_EXCEPTION",
    "message": "The template with identifier er3b45 already exists in account kmpySmUISimoRrJL6NL73w, org default, project njh, if you want to create a new version rwerdsdasdtreterew of this template then use save as new version option from the given template or if you want to create a new Template then use a different identifier.",
    "correlationId": "409ea308-5f7b-44d9-9064-0a263125010d",
    "detailedMessage": null,
    "responseMessages": [
        {
            "code": "TEMPLATE_ALREADY_EXISTS_EXCEPTION",
            "level": "ERROR",
            "message": "The template with identifier er3b45 already exists in account kmpySmUISimoRrJL6NL73w, org default, project njh, if you want to create a new version rwerdsdasdtreterew of this template then use save as new version option from the given template or if you want to create a new Template then use a different identifier.",
            "exception": null,
            "failureTypes": []
        }
    ],
    "metadata": null
}
```

Added new exception for isNewTemplate case

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45218)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45218)* status: Some of the checks are too old. 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45218)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
we have added a new error code thats why backward compatiblity check is failing, it will not have any impact with the customers, we have just introduced a new exception only for UI

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45218)* status: :shipit: complete! ✓

**Pull request merged**
