### PR TITLE
[feat]: [CDS-82749]: Implementing the exports in planCreator and publishing as outcome on ending node-execution

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55844)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55844)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/mappers/PlanNodeProtoMapper.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/55844#-Njv4C2FERgXtFRUCwxP:-Njv4C2FERgXtFRUCwxQ:b7bzajh) ([raw file](https://github.com/harness/harness-core/blob/5e635c557bd5c1cdd09e34cfc975efe8e69e4343/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/mappers/PlanNodeProtoMapper.java#L140)):*
> ```Java
>     if (value instanceof String) {
>       return ExportValue.newBuilder().setStringValue((String) value).build();
>     } else if (value instanceof Integer) {
> ```

why cant we put or condition here? will expression always print double now?



_Code quote:_
```Java
else if (value instanceof Integer
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55844)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 107 at r4](https://reviewable.io/reviews/harness/harness-core/55844#-NjvD6aw48bXednVegNv:-NjvD6aw48bXednVegNw:bxy8yhq) ([raw file](https://github.com/harness/harness-core/blob/5e635c557bd5c1cdd09e34cfc975efe8e69e4343/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L107)):*
> ```Java
>     // exports is empty or not is unnecessary for step and other nodes.
>     if (currentLevel.getStepType().getStepCategory() == StepCategory.STAGE
>         || currentLevel.getStepType().getStepCategory() == StepCategory.STEP_GROUP) {
> ```

nit: can be combined or not



_Code quote:_
```Java
    Level currentLevel = AmbianceUtils.obtainCurrentLevel(ambiance);
    // Since we will have the exports at only Stage and stepGroup level. So fetching the planNode and checking if
    // exports is empty or not is unnecessary for step and other nodes.
    if (currentLevel.getStepType().getStepCategory() == StepCategory.STAGE
        || currentLevel.getStepType().getStepCategory() == StepCategory.STEP_GROUP) {
```
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/55844#-NjvDAnWBjig53RWy4z-:-NjvDAnWBjig53RWy4z0:bmqhuka) ([raw file](https://github.com/harness/harness-core/blob/5e635c557bd5c1cdd09e34cfc975efe8e69e4343/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L108)):*
> ```Java
>     if (currentLevel.getStepType().getStepCategory() == StepCategory.STAGE
>         || currentLevel.getStepType().getStepCategory() == StepCategory.STEP_GROUP) {
>       PlanNode planNode = planService.fetchNode(ambiance.getPlanId(), AmbianceUtils.obtainCurrentSetupId(ambiance));
> ```

can we use projection?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 121 at r4](https://reviewable.io/reviews/harness/harness-core/55844#-NjvDWzF9IO5ME6yY4vV:-NjvDWzF9IO5ME6yY4vW:bd5w5s1) ([raw file](https://github.com/harness/harness-core/blob/5e635c557bd5c1cdd09e34cfc975efe8e69e4343/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L121)):*
> ```Java
>   private String getResolvedJsonForExports(Ambiance ambiance, Map<String, ExportConfig> exportConfigMap) {
>     pmsEngineExpressionService.resolve(
>         ambiance, exportConfigMap, ExpressionMode.RETURN_ORIGINAL_EXPRESSION_IF_UNRESOLVED);
> ```

nit: move conversion to map<string, string> first then resolve

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/55844#-NjvDAnWBjig53RWy4z-:-NjvQVCQEtezbPcRItAy:b-yrcp8h) ([raw file](https://github.com/harness/harness-core/blob/5e635c557bd5c1cdd09e34cfc975efe8e69e4343/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L108)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we use projection?
</blockquote></details>

Can we do introduce the projections in planService::fetchNode separately? fetchNode is a little big method and might need some refactoring instead of duplicating the code. So we can do it separately.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 12 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55844)* status: 13 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java` line 121 at r4](https://reviewable.io/reviews/harness/harness-core/55844#-NjvDWzF9IO5ME6yY4vV:-NjvwGEtAchMALq2bHSM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/5e635c557bd5c1cdd09e34cfc975efe8e69e4343/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/EndNodeExecutionHelper.java#L121)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: move conversion to map<string, string> first then resolve
</blockquote></details>

done

**Comment by brijeshdhakar** [comment]
trigger ut5 ut6 ut7 ut8 ut9

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut5

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55844)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 9 of 12 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55844)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
