### PR TITLE
feat: [DEL-3455]: Add delegate selectors to yaml, pipeline, stage, stepGroup

### PR DESCRIPTION
**Pull request by jennyjames21**
…step group

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java, line 80 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJF2kE-EwbNFmHXjWy:-MzJF2kE-EwbNFmHXjWz:bohfhnh) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java#L80)):*
> ```Java
>   boolean allowStageExecutions;
> 
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) ParameterField<List<String>> delegateSelectors;
> ```

Can use TaskSelectorYaml directly



_Code quote:_
```Java
String
```
___
*[878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java, line 64 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJExtt4ru_DDkhaDhJ:-MzJExtuE09w8rZNxLZZ:bohfhnh) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java#L64)):*
> ```Java
>   @NotNull @Size(min = 1) List<ExecutionWrapperConfig> steps;
> 
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) ParameterField<List<String>> delegateSelectors;
> ```

Can use TaskSelectorYaml directly



_Code quote:_
```Java
String
```
___
*[889-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java, line 65 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJF91YDTbLgxWALtdt:-MzJF91YDTbLgxWALtdu:bohfhnh) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/889-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java#L65)):*
> ```Java
>   Map<String, String> tags;
> 
>   @ApiModelProperty(dataType = SwaggerConstants.STRING_LIST_CLASSPATH) ParameterField<List<String>> delegateSelectors;
> ```

Can use TaskSelectorYaml directly



_Code quote:_
```Java
String
```

**Comment by jennyjames21** [comment]
*[860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java, line 80 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJF2kE-EwbNFmHXjWy:-Mzs2uYtAUjvTn0uq7fj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java#L80)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can use TaskSelectorYaml directly
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java, line 64 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJExtt4ru_DDkhaDhJ:-Mzs2xwh9GHAeJ6_LdjA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can use TaskSelectorYaml directly
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 20 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java, line 64 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJExtt4ru_DDkhaDhJ:-Mzs4ITI0QjV5-0WEEmM:b-yyox5t) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/StepGroupElementConfig.java#L64)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

its still showing me String instead of TaskSelectorYaml
___
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 448 at r2](https://reviewable.io/reviews/harness/harness-core/31787#-MzsDYBY5NnyYjpkEJDF:-MzsDYBZAB42ATXy3MZn:buv9lw1) ([raw file](https://github.com/harness/harness-core/blob/839003d9ceca48126295ef9438e8172e428deecc/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L448)):*
> ```Java
>       if (delegateSelectorFieldValue != null) {
>         return specParameters;
>       }
> ```

Can be avoided by introducing WithDelegateSelectors interface and exposing get and set method



_Code quote:_
```Java
      Field field = ReflectionUtils.getFieldByName(specParameters.getClass(), DELEGATE_SELECTORS);
      if (field == null) {
        return specParameters;
      }
      // if delegate selector value available at step level, then it gets precedence,
      Object delegateSelectorFieldValue = ReflectionUtils.getFieldValue(specParameters, field);
      if (delegateSelectorFieldValue != null) {
        return specParameters;
      }
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 17 of 18 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 448 at r2](https://reviewable.io/reviews/harness/harness-core/31787#-MzsDYBY5NnyYjpkEJDF:-MzyZXr-C2yu4GaKuikB:bamgya9) ([raw file](https://github.com/harness/harness-core/blob/839003d9ceca48126295ef9438e8172e428deecc/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L448)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can be avoided by introducing WithDelegateSelectors interface and exposing get and set method
</blockquote></details>

@jennyjames21 are we still taking reflection route and not introducing an interface?
___
*[889-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java, line 65 at r1](https://reviewable.io/reviews/harness/harness-core/31787#-MzJF91YDTbLgxWALtdt:-MzyZI0e9-v3EZRPEtLI:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/967084bdf34ff2806fb4a8c50dbe4d6da36dcb71/889-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can use TaskSelectorYaml directly
</blockquote></details>

Done

**Comment by jennyjames21** [comment]
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 448 at r2](https://reviewable.io/reviews/harness/harness-core/31787#-MzsDYBY5NnyYjpkEJDF:-N-Lk6O799XlW5ppAYcO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/839003d9ceca48126295ef9438e8172e428deecc/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L448)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@jennyjames21 are we still taking reflection route and not introducing an interface?
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
trigger authorcheck

**Comment by jennyjames21** [comment]
trigger authorcheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 40 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 37 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStepInfo.java, line 44 at r7](https://reviewable.io/reviews/harness/harness-core/31787#-N-MUB1G0e4hVp4vIo_G:-N-MUB1G0e4hVp4vIo_H:b-48b0e5) ([raw file](https://github.com/harness/harness-core/blob/086e7aaa8e9d0ce21154e9884c317046bf2577ef/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStepInfo.java#L44)):*
> ```Java
> @TypeAlias("k8sBGSwapServicesStepInfo")
> @RecasterAlias("io.harness.cdng.k8s.K8sBGSwapServicesStepInfo")
> public class K8sBGSwapServicesStepInfo implements CDStepInfo, Visitable, WithDelegateSelector {
> ```

all cd steps have delegate selectors, please add this interface at CDStepInfo



_Code quote:_
```Java
K8sBGSwapServicesStepInfo implements CDStepInfo, Visitable, WithDelegateSelector
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 37 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 451 at r7](https://reviewable.io/reviews/harness/harness-core/31787#-N-MUiHq-7Qcpdb2RZLT:-N-MUiHq-7Qcpdb2RZLU:b7gqy62) ([raw file](https://github.com/harness/harness-core/blob/086e7aaa8e9d0ce21154e9884c317046bf2577ef/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L451)):*
> ```Java
>           withDelegateSelector.setDelegateSelectors(delegateSelectors);
>           return;
>         }
> ```

can be created a private util for repeated code



_Code quote:_
```Java
        if (!ParameterField.isNull(delegateSelectors)) {
          delegateSelectors.getValue().forEach(selector -> selector.setOrigin(STEP_GROUP));
          withDelegateSelector.setDelegateSelectors(delegateSelectors);
          return;
        }
```

**Comment by jennyjames21** [comment]
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 451 at r7](https://reviewable.io/reviews/harness/harness-core/31787#-N-MUiHq-7Qcpdb2RZLT:-N-MXdOj1BnJEgBUvvru:bhkvy37) ([raw file](https://github.com/harness/harness-core/blob/086e7aaa8e9d0ce21154e9884c317046bf2577ef/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L451)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can be created a private util for repeated code
</blockquote></details>

that's only 2 lines of code, doesn't make sense to create private

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 22 of 40 files at r5, 1 of 1 files at r6, 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStepInfo.java, line 44 at r7](https://reviewable.io/reviews/harness/harness-core/31787#-N-MUB1G0e4hVp4vIo_G:-N-MWxvz5wb13NvUor2W:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/086e7aaa8e9d0ce21154e9884c317046bf2577ef/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sBGSwapServicesStepInfo.java#L44)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

all cd steps have delegate selectors, please add this interface at CDStepInfo
</blockquote></details>

Done
___
*[330-ci-beans/src/test/resources/schema/IntegrationStage/all.json, line 1902 at r2](https://reviewable.io/reviews/harness/harness-core/31787#-N-MXvGg-ApqKXQRzSxq:-N-MXvGg-ApqKXQRzSxr:bn9399a) ([raw file](https://github.com/harness/harness-core/blob/839003d9ceca48126295ef9438e8172e428deecc/330-ci-beans/src/test/resources/schema/IntegrationStage/all.json#L1902)):*
> ```JSON
>         }
>       ],
>       "$schema": "http://json-schema.org/draft-07/schema#"
> ```

why this change was required?



_Suggestion:_
```JSON
$schema": "http://json-schema.org/draft-07/schema#
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 451 at r7](https://reviewable.io/reviews/harness/harness-core/31787#-N-MUiHq-7Qcpdb2RZLT:-N-MYgSv-7J0r2xXvVSA:br9z8nf) ([raw file](https://github.com/harness/harness-core/blob/086e7aaa8e9d0ce21154e9884c317046bf2577ef/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L451)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

that's only 2 lines of code, doesn't make sense to create private 
</blockquote></details>

the reason for util method in same class is as its used at many places like in stage section below, repetitive code thus a util should be created so to keep the code consistent

**Review by jennyjames21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 451 at r7](https://reviewable.io/reviews/harness/harness-core/31787#-N-MUiHq-7Qcpdb2RZLT:-N-MZajf5h_nUaUo5VMh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/086e7aaa8e9d0ce21154e9884c317046bf2577ef/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L451)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

the reason for util method in same class is as its used at many places like in stage section below, repetitive code thus a util should be created so to keep the code consistent
</blockquote></details>

Done.

**Comment by jennyjames21** [comment]
*[330-ci-beans/src/test/resources/schema/IntegrationStage/all.json, line 1902 at r2](https://reviewable.io/reviews/harness/harness-core/31787#-N-MXvGg-ApqKXQRzSxq:-N-MbL1JC6hKRnODFm5J:b-lzd1gf) ([raw file](https://github.com/harness/harness-core/blob/839003d9ceca48126295ef9438e8172e428deecc/330-ci-beans/src/test/resources/schema/IntegrationStage/all.json#L1902)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this change was required?
</blockquote></details>

**Comment by jennyjames21** [comment]
*[330-ci-beans/src/test/resources/schema/IntegrationStage/all.json, line 1902 at r2](https://reviewable.io/reviews/harness/harness-core/31787#-N-MXvGg-ApqKXQRzSxq:-N-MbSLz2Y8qWuqInC07:bpj5iw3) ([raw file](https://github.com/harness/harness-core/blob/839003d9ceca48126295ef9438e8172e428deecc/330-ci-beans/src/test/resources/schema/IntegrationStage/all.json#L1902)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>


</blockquote></details>

it's showing with quote 1896

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 40 files at r5, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, line 452 at r10](https://reviewable.io/reviews/harness/harness-core/31787#-N-McoNy7rRPMVbwbtq0:-N-McoNy7rRPMVbwbtq1:b65fkso) ([raw file](https://github.com/harness/harness-core/blob/7f48cea05d191e9353a08dee4754b232d555e80e/878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java#L452)):*
> ```Java
> 
>         delegateSelectors = delegateSelectorsFromFqn(ctx, STAGE);
>         if (!ParameterField.isNull(delegateSelectors)) {
> ```

if (!ParameterField.isNull(delegateSelectors)) { 
can be part of new util



_Code quote:_
```Java
if (!ParameterField.isNull(delegateSelectors)) {
```

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: :shipit: complete! ✓

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger ti0

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 8 of 18 files at r2, 20 of 40 files at r5, 4 of 16 files at r8, 1 of 1 files at r9, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31787)* status: :shipit: complete! ✓

**Pull request merged**
