### PR TITLE
[feat]: [CCM-7650]: Azure Connector Validations

### PR DESCRIPTION
**Pull request by abhijeet-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)

### CODE REVIEW

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`WORKSPACE` line 5267 at r2](https://reviewable.io/reviews/harness/harness-core/35798#-N82MI0m3M2ZBOdJNPnV:-N82MI0m3M2ZBOdJNPnW:bt4o6e5) ([raw file](https://github.com/harness/harness-core/blob/f4709e03d731079c52caf4d8588a708cb8235cd1/WORKSPACE#L5267)):*
> ```Starlark
>         "com.azure.resourcemanager:azure-resourcemanager:2.14.0",
>         "com.azure.resourcemanager:azure-resourcemanager-authorization:2.14.0",
>         "com.azure.resourcemanager:azure-resourcemanager-resources:2.14.0",
> ```

1. Lets add the libs in WORKSPACE only for ce-nextgen. We want to avoid issues w.r.t libs for any other module.
2. Also, make sure the lib version is compatible with Azure core / Azure identity lib versions if the  resource manager lib is using them

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java` line 320 at r2](https://reviewable.io/reviews/harness/harness-core/35798#-N82NtdiCH-EmE5ngb48:-N82NtdiCH-EmE5ngb49:b61hyh9) ([raw file](https://github.com/harness/harness-core/blob/f4709e03d731079c52caf4d8588a708cb8235cd1/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java#L320)):*
> ```Java
>       String reason = "";
>       for (String requiredRole : requiredRoles) {
>         reason += String.format("Missing required %s role in service principal.%n", requiredRole);
> ```

'Required  role "" is not assigned to service principal.'

**Review by nikunj-badjatya — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Comment by abhijeet-harness** [comment]
Added following versions of new dependencies:
- [azure-resourcemanager/2.12.0](https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager/2.12.0/jar) uses [azure-core-http-netty/1.11.7](https://search.maven.org/artifact/com.azure/azure-core-http-netty/1.11.7/jar) - which uses azure-core/1.25.0
- [azure-core-management/1.5.2](https://search.maven.org/artifact/com.azure/azure-core-management/1.5.2/jar) uses azure-core/1.25.0

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35798)

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old.

**Review by nikunj-badjatya — APPROVED** [review]

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old.

**Review by abhijeet-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`WORKSPACE` line 5267 at r2](https://reviewable.io/reviews/harness/harness-core/35798#-N82MI0m3M2ZBOdJNPnV:-N8cIgBO8RHSnjIoIObV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4709e03d731079c52caf4d8588a708cb8235cd1/WORKSPACE#L5267)):*
<details><summary><i>Previously, nikunj-badjatya (Nikunj Badjatya) wrote…</i></summary><blockquote>

1. Lets add the libs in WORKSPACE only for ce-nextgen. We want to avoid issues w.r.t libs for any other module.
2. Also, make sure the lib version is compatible with Azure core / Azure identity lib versions if the  resource manager lib is using them
</blockquote></details>

Done.

**Review by abhijeet-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java` line 320 at r2](https://reviewable.io/reviews/harness/harness-core/35798#-N82NtdiCH-EmE5ngb48:-N8cJ1nq4UdGDGjRDwPl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f4709e03d731079c52caf4d8588a708cb8235cd1/340-ce-nextgen/src/main/java/io/harness/ccm/connectors/CEAzureConnectorValidator.java#L320)):*
<details><summary><i>Previously, nikunj-badjatya (Nikunj Badjatya) wrote…</i></summary><blockquote>

'Required  role "" is not assigned to service principal.'
</blockquote></details>

Done.

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old.

**Review by nikunj-badjatya — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798#-:-N8cJBzD8_gR2D6AOm7-:bnfp4nl)* status: Some of the checks are too old.

**Review by abhijeet-harness — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: 1 file(s) to review.

**Review by abhijeet-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798#-:-N8eUNBiEHfpXWyFWa9X:bnfp4nl)* status: 1 file(s) to review.

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old.

**Review by nikunj-badjatya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: Some of the checks are too old.

**Review by abhijeet-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798#-:-N8wMDFbBTGdaL2E9EtS:bnfp4nl)* status: 1 file(s) to review.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35798)* status: :shipit: complete! ✓

**Pull request merged**
