### PR TITLE
feat: [CDS-80453]: add Http step outcome as per v1 structure

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** add Http step outcome as per v1 structure
**Testing:** Tested locally with v1 pipeline with http step.
**Backward compatibility test:** Ran a pipeline with
2 stages (on develop)
first stage success and second fail (the first stage is producing some http outcome)

(on this branch)
resume failed stage from 2nd stage
refer outcome in 2nd stage and it should print

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — DISMISSED** [review]
> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 187 at r4](https://reviewable.io/reviews/harness/harness-core/54329#-NhQV3QK2LsCGLsqzdUv:-NhQV3QK2LsCGLsqzdUw:b3yuf8b) ([raw file](https://github.com/harness/harness-core/blob/409ce03902194e6644074971e026e9da4e075e64/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L187)):*
> ```Java
>     if (stepParameters.getSpec() instanceof HttpStepParameters) {
>       httpStepParameters = (HttpStepParameters) stepParameters.getSpec();
>     } else {
> ```

should be else-if ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: :shipit: complete! ✓

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/54329#-NhQWCz8CI3xQj0dV2yZ:-NhQWCz8CI3xQj0dV2y_:b-rp382j) ([raw file](https://github.com/harness/harness-core/blob/409ce03902194e6644074971e026e9da4e075e64/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L221)):*
> ```Java
>       default:
>         log.info("Version {} not supported", version);
>     }
> ```

also, have we added tests for this class ?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 222 at r4](https://reviewable.io/reviews/harness/harness-core/54329#-NhQVCVQ5f6G_yfkKPEP:-NhQVCVQ5f6G_yfkKPEQ:by1nabb) ([raw file](https://github.com/harness/harness-core/blob/409ce03902194e6644074971e026e9da4e075e64/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L222)):*
> ```Java
>         log.info("Version {} not supported", version);
>     }
>     return null;
> ```

should this throw exception instead since we never want this to happen ?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 187 at r4](https://reviewable.io/reviews/harness/harness-core/54329#-NhQV3QK2LsCGLsqzdUv:-NhQY5Cp23jKsvbjWemc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/409ce03902194e6644074971e026e9da4e075e64/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L187)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should be else-if ?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 221 at r4](https://reviewable.io/reviews/harness/harness-core/54329#-NhQWCz8CI3xQj0dV2yZ:-NhQYLNp883EuMyLj5ZE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/409ce03902194e6644074971e026e9da4e075e64/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L221)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

also, have we added tests for this class ?
</blockquote></details>

done
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 222 at r4](https://reviewable.io/reviews/harness/harness-core/54329#-NhQVCVQ5f6G_yfkKPEP:-NhQY9ql4vna5s0BlCMc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/409ce03902194e6644074971e026e9da4e075e64/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L222)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should this throw exception instead since we never want this to happen ?
</blockquote></details>

done

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/54329#-NhQsaCuDuUkh1sg5Afj:-NhQsaCuDuUkh1sg5Afk:btlq3sw) ([raw file](https://github.com/harness/harness-core/blob/c45bcb620e23125cce402ff4a991211faf9cd2a4/953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java#L30)):*
> ```Java
>   }
> 
>   default String getVersion() {
> ```

we are not using this method ?

**Comment by shalini-agr** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/54329#-NhQsaCuDuUkh1sg5Afj:-NhQsvuA2j0Eax4g7Z-g:b-u169hd) ([raw file](https://github.com/harness/harness-core/blob/c45bcb620e23125cce402ff4a991211faf9cd2a4/953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java#L30)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we are not using this method ?
</blockquote></details>

we are using this in HttpStepUtils where we were earlier using instanceOf

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/54329#-NhQsaCuDuUkh1sg5Afj:-NhR-9ZQ5fNjzfAj7E4a:b990439) ([raw file](https://github.com/harness/harness-core/blob/c45bcb620e23125cce402ff4a991211faf9cd2a4/953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java#L30)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

we are using this in HttpStepUtils where we were earlier using instanceOf
</blockquote></details>

have you pushed that change ?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java` line 30 at r7](https://reviewable.io/reviews/harness/harness-core/54329#-NhQsaCuDuUkh1sg5Afj:-NhR-j247kgBanWL6usK:b2nign6) ([raw file](https://github.com/harness/harness-core/blob/c45bcb620e23125cce402ff4a991211faf9cd2a4/953-yaml-commons/src/main/java/io/harness/plancreator/steps/common/SpecParameters.java#L30)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

have you pushed that change ?
</blockquote></details>

yes
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java` line 184 at r7](https://reviewable.io/reviews/harness/harness-core/54329#-NhR-lS17rgT-LXhAzA_:-NhR-lS17rgT-LXhAzAa:b91vb7) ([raw file](https://github.com/harness/harness-core/blob/c45bcb620e23125cce402ff4a991211faf9cd2a4/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/HttpStepUtils.java#L184)):*
> ```Java
>   // rfc
>   HttpStepParameters getHttpStepParameters(StepBaseParameters stepParameters) {
>     String version = stepParameters.getSpec().getVersion();
> ```

@yogesh-chauhan here we are using the version from spec

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54329)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
