### PR TITLE
fix: [PL-31276]: Avoid setting 2fa metadata when new user is invited to NG

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
**Problem:**
Currently, when a new user is invited to a Harness account with 2FA enforced, we set 2FA secret for them while sending the invite. This flow fails as the user entity is not yet created. Hence, although the invite gets sent, we see an unknown error on the UI.

**Solution:**
We will not set 2FA secret for the user while sending the invite. Instead, it will be set once the user accepts the invite. Once, the user completes the NG signup by setting their username and password, we will set the 2FA secret for them and send the email with 2FA QR code.

**Testing:**
The following 2 scenarios have been tested in local-dev environment:

**- Invite new user to an account with 2FA enabled:**
1. Invite new user to Harness into an account where 2FA is enforced at account level.
3. Invite gets sent successfully without any error on UI.
4. User accepts invite -> sets their username and password on signup page.
5. Post this, 2FA prompt should come up, and at this point user should get an email with 2FA code.
6. Login should succeed after entering this 2FA code.

**- Invite existing user to an account with 2FA enabled:**
1. Invite an existing Harness user to an account with 2FA enabled at account level.
2. User should get an email to accept the invite.
3. On accepting the invite, a 2FA reset email should be sent.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/44664#-NPpGHIM4DLQoprhb_Oi:-NPpGHIM4DLQoprhb_Oj:b-4pumfz) ([raw file](https://github.com/harness/harness-core/blob/515ead929804a65fb7e93490046ecba7b412c3df/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L351)):*
> ```Java
>             getTwoFactorAuthSettingsInfo(accountIdentifier, userInfo.getEmail());
>         updateUserTwoFactorAuthInfo(userInfo.getEmail(), twoFactorAuthSettingsInfo);
>         CGRestUtils.getResponse(
> ```

just checking, can there be any downside if updateUserTwoFactorAuthInfo() succeeds but userClient.sendTwoFactorAuthenticationResetEmail() fails?

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/44664#-NPpGXeA48Ukb7l6YleY:-NPpGXeB2U02LfXfVJXS:b9sys9a) ([raw file](https://github.com/harness/harness-core/blob/515ead929804a65fb7e93490046ecba7b412c3df/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L351)):*
> ```Java
>             getTwoFactorAuthSettingsInfo(accountIdentifier, userInfo.getEmail());
>         updateUserTwoFactorAuthInfo(userInfo.getEmail(), twoFactorAuthSettingsInfo);
>         CGRestUtils.getResponse(
> ```

Also, I think we should have a wrapper on this CG REST Call where we can catch any REST exception and throw a better exception saying "failed to send..."

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/44664#-NPpGHIM4DLQoprhb_Oi:-NQTS2lMBEFz9BNWKwSd:bvxztsu) ([raw file](https://github.com/harness/harness-core/blob/515ead929804a65fb7e93490046ecba7b412c3df/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L351)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

just checking, can there be any downside if updateUserTwoFactorAuthInfo() succeeds but userClient.sendTwoFactorAuthenticationResetEmail() fails?
</blockquote></details>

@mohitg0795 The client call will take care of creating the user's two factor auth settings. Hence, I've removed the pdateUserTwoFactorAuthInfo() call from this flow.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 351 at r1](https://reviewable.io/reviews/harness/harness-core/44664#-NPpGXeA48Ukb7l6YleY:-NQTSI4e0e3e0X4bsVx1:bzbnhgm) ([raw file](https://github.com/harness/harness-core/blob/515ead929804a65fb7e93490046ecba7b412c3df/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L351)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also, I think we should have a wrapper on this CG REST Call where we can catch any REST exception and throw a better exception saying "failed to send..."
</blockquote></details>

I have provided an error message to make it clearer, please check. However, internally the CGRestUtils.getResponse() maps any exception to InvalidRequestException. So, I don't think we can do error handling for it.

**Comment by tiwaritejas** [comment]
trigger ut0

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: 2 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: :shipit: complete! ✓

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/44664#-NQTnBecEwd6VPlywScQ:-NQTnBecEwd6VPlywScR:b-g7v3o0) ([raw file](https://github.com/harness/harness-core/blob/3c435818810e79b9e08c6b6d37b0ee0ce1f73c72/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L348)):*
> ```Java
>         Optional<Invite> inviteOpt = getInviteFromToken(jwtToken, false);
>         completeInvite(inviteOpt);
>         CGRestUtils.getResponse(userClient.sendTwoFactorAuthenticationResetEmail(userInfo.getUuid(), accountIdentifier),
> ```

add UT for this case.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/44664#-NQTnBecEwd6VPlywScQ:-NQUZu3n5KacyEjUj_XR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3c435818810e79b9e08c6b6d37b0ee0ce1f73c72/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L348)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

add UT for this case.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44664)* status: :shipit: complete! ✓

**Pull request merged**
