### PR TITLE
fix: [CDS-48994]: Using git connector ID instead of connector name during git Fetch files

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
Issue is happening when connector name contains ".git" , because of that containing this connector name got filter(please refer the below SS)
Screenshot 2023-01-03 at 4 08 55 PM

## Before Fix:
Although Patches are being added in the manifest , still they are not being used
Screenshot 2023-01-03 at 4 12 38 PM

## After Fix:
Patches applied successfully
Screenshot 2023-01-03 at 4 14 20 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42146)

### CODE REVIEW

**Review by acasian-harness — CHANGES_REQUESTED** [review]
@namantalaycha10 please update the PR description and add screen examples to the PR. Also UT is missing. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42146#-:-NKqbsL0B64CMcXY8Bq2:bhoswsl)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 462 at r1](https://reviewable.io/reviews/harness/harness-core/42146#-NKqc0i1BhDCcACRPAJ9:-NKqc0i1BhDCcACRPAJA:b-90ogav) ([raw file](https://github.com/harness/harness-core/blob/309b265116cb8df198f22303b3670c1d61a67ce0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L462)):*
> ```Java
>         .commitId(trim(getParameterFieldValue(gitstoreConfig.getCommitId())))
>         .paths(trimStrings(paths))
>         .connectorName(connectorDTO.getIdentifier())
> ```

shall we provide a connectorId property instead?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42146)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 462 at r1](https://reviewable.io/reviews/harness/harness-core/42146#-NKqc0i1BhDCcACRPAJ9:-NKrBnW40fcOqwFMvLsS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/309b265116cb8df198f22303b3670c1d61a67ce0/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L462)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

shall we provide a connectorId property instead?
</blockquote></details>

Done.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 9 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42146)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 6 of 9 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42146)* status: 2 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42146#-:-NL1Hp43DN2mUlONy-cs:bnfp4nl)* status: 2 file(s) to review.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42146)* status: :shipit: complete! ✓

**Pull request merged**
