### PR TITLE
[feat]: [CCM-8560]: CCM RBAC role migration

### PR DESCRIPTION
**Pull request by svmav**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36321)

### CODE REVIEW

**Comment by USB-05** [comment]
trigger feature-build

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 3 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36321)

**Comment by svmav** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36321)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java` line 266 at r5](https://reviewable.io/reviews/harness/harness-core/36321#-N9lAUm605Jos2u7e_w4:-N9lAUm605Jos2u7e_w5:b3rigua) ([raw file](https://github.com/harness/harness-core/blob/bbef9a9cc5a602debb9e6f330d4b6410af1fea78/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java#L266)):*
> ```Java
> 
>     install(NgLicenseHttpClientModule.getInstance(config.getNgManagerServiceConfiguration().getNgManagerServiceConfig(),
>         config.getNgManagerServiceConfiguration().getNgManagerServiceSecret(), MANAGER.getServiceId()));
> ```

The getServiceId is of Manager, whereas configuration is of NgManager. Is this intended?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java` line 86 at r5](https://reviewable.io/reviews/harness/harness-core/36321#-N9lnnyCD-b3N0XpXcyP:-N9lnnyCD-b3N0XpXcyQ:b-xl9zbb) ([raw file](https://github.com/harness/harness-core/blob/bbef9a9cc5a602debb9e6f330d4b6410af1fea78/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java#L86)):*
> ```Java
>               log.error("Corresponding ccm admin was already created {}", newRoleAssignmentDBO.toString(), e);
>             }
>             roleAssignmentRepository.updateById(roleAssignment.getId(), update(RoleAssignmentDBOKeys.managed, false));
> ```

Why making existing Account Viewer role assignments as unmanaged? 
This can result in Account Viewer role binding be removable from users and if removed, they won't be able access the Harness app.

**Review by svmav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36321)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java` line 266 at r5](https://reviewable.io/reviews/harness/harness-core/36321#-N9lAUm605Jos2u7e_w4:-NA4_jeeCheJtj4ErUbk:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbef9a9cc5a602debb9e6f330d4b6410af1fea78/access-control/service/src/main/java/io/harness/accesscontrol/AccessControlModule.java#L266)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

The getServiceId is of Manager, whereas configuration is of NgManager. Is this intended?
</blockquote></details>

Done.
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java` line 86 at r5](https://reviewable.io/reviews/harness/harness-core/36321#-N9lnnyCD-b3N0XpXcyP:-NA4_m394nXoB1SIaUi0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bbef9a9cc5a602debb9e6f330d4b6410af1fea78/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java#L86)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why making existing Account Viewer role assignments as unmanaged? 
This can result in Account Viewer role binding be removable from users and if removed, they won't be able access the Harness app.
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36321)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/36321#-NA4vS4j8K4EFvheHeVC:-NA4vS4j8K4EFvheHeVD:bgjby72) ([raw file](https://github.com/harness/harness-core/blob/e520c0c48c4df6b503ac60a67df97dc71462f365/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java#L31)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.CE)
> public class CCMAdminRoleAssignmentAdditionMigration implements NGMigration {
> ```

Why this migration is inside access control service. This migration should be in CCM service

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36321)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java` line 31 at r6](https://reviewable.io/reviews/harness/harness-core/36321#-NA4vS4j8K4EFvheHeVC:-NA4v_clA-FLHZe-rN9l:b-9ofnhi) ([raw file](https://github.com/harness/harness-core/blob/e520c0c48c4df6b503ac60a67df97dc71462f365/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/migration/CCMAdminRoleAssignmentAdditionMigration.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this migration is inside access control service. This migration should be in CCM service
</blockquote></details>

Access Control Service is a Platform Service. It doesn't deal with module specific migrations. APIs exposed by Access Control should be used to do this migration from CCM service

**Pull request closed without merging**
