### PR TITLE
[fix]: [CDS-36839]: Improved Error Message

### PR DESCRIPTION
**Pull request by Abhishek-CDC**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34353)

### CODE REVIEW

**Review by vtxorxwitty — DISMISSED** [review]

**Review by vtxorxwitty — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34353)* status: :shipit: complete! ✓

**Review by vtxorxwitty — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34353)* status: :shipit: complete! ✓

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34353)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 352 at r4](https://reviewable.io/reviews/harness/harness-core/34353#-N4bbiVe0b90U8u9GwOu:-N4bbiVe0b90U8u9GwOv:bq45nkq) ([raw file](https://github.com/harness/harness-core/blob/e426b6124fd73f6254e8c2b88dea3525572d741a/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L352)):*
> ```Java
> 
>   private String getMessageHelper(String accountId, String orgIdentifier, String projectIdentifier) {
>     if (projectIdentifier != null) {
> ```

Use EmptyPredicate.isEmpty() where ever you can. This will cover empty string checks as well.

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34353)* status: :shipit: complete! ✓

**Comment by Abhishek-CDC** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 352 at r4](https://reviewable.io/reviews/harness/harness-core/34353#-N4bbiVe0b90U8u9GwOu:-N4esN5F8LznjNkpBT77:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e426b6124fd73f6254e8c2b88dea3525572d741a/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L352)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Use EmptyPredicate.isEmpty() where ever you can. This will cover empty string checks as well.
</blockquote></details>

Done.

**Review by Abhishek-CDC — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34353#-:-N4etfg6EDeRoIax7bxJ:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34353)* status: :shipit: complete! ✓

**Pull request merged**
