### PR TITLE
feat: [IDP-911]: IDP Service - Score APIs

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51485)

### CODE REVIEW

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51485)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/51485#-NbOTtjV-rbKnAd_0r0k:-NbOTtjV-rbKnAd_0r0l:berngvq) ([raw file](https://github.com/harness/harness-core/blob/298da96b02731511bbbb6dc0340ac808d3d44f4d/idp-service/src/main/java/io/harness/idp/scorecard/scores/resources/ScoreApiImpl.java#L62)):*
> ```Java
>       String entityIdentifier, String scorecardIdentifier, String harnessAccount) {
>     try {
>       ScorecardRecalibrateInfo scorecardRecalibrateInfo =
> ```

Do we need a separate DTO for this? Or can we use any of the existing ones?
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java` line 66 at r2](https://reviewable.io/reviews/harness/harness-core/51485#-NbOUrLF6jbVnxop43yo:-NbOUrLF6jbVnxop43yp:b-kmggfc) ([raw file](https://github.com/harness/harness-core/blob/298da96b02731511bbbb6dc0340ac808d3d44f4d/idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java#L66)):*
> ```Java
>         .map(scoreEntity
>             -> ScorecardSummaryInfoMapper.toDTO(scoreEntity,
>                 scorecardService.getScorecardDetails(accountIdentifier, scoreEntity.getScorecardIdentifier())
> ```

Can we make just one call and get a list of required scorecard details instead?
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/51485#-NbOV1WpAxdMLgPKKYvK:-NbOV1WpAxdMLgPKKYvL:bbxgkzp) ([raw file](https://github.com/harness/harness-core/blob/298da96b02731511bbbb6dc0340ac808d3d44f4d/idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java#L89)):*
> ```Java
>     return scoreEntities.stream()
>         .map(scoreEntity -> {
>           ScorecardDetailsResponse scorecardDetailsResponse =
> ```

Same comment as above

**Review by mankrit-singh — APPROVED** [review]

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51485)* status: 13 file(s) to review.

**Comment by devesh-harness** [comment]
trigger uts, review

**Comment by devesh-harness** [comment]
trigger uts

**Comment by devesh-harness** [comment]
trigger ut7

**Pull request merged**
