### PR TITLE
[feat]:[pl-28109]: NPE for saving commit message

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
NPE for saving commit message as comment for remote templates, have tested out for inline templates

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/38956#-NEisOCGBt07VIHj6ryv:-NEisOCGBt07VIHj6ryw:b-hnwor0) ([raw file](https://github.com/harness/harness-core/blob/bd1a433c75eb40d4cecd258aee2f112d17e779bb/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L245)):*
> ```Java
>     log.info(String.format("Creating Template with identifier %s with label %s in project %s, org %s, account %s",
>         templateEntity.getIdentifier(), templateEntity.getVersionLabel(), projectId, orgId, accountId));
>     if (comments != null && comments.isEmpty() && gitEntityCreateInfo != null
> ```

lets use "isEmpty(comments)" instead of 2 separate commands

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/38956#-NEisOCGBt07VIHj6ryv:-NEitx_VCwuhBZzbMVAM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/bd1a433c75eb40d4cecd258aee2f112d17e779bb/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L245)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets use "isEmpty(comments)" instead of 2 separate commands
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: :shipit: complete! ✓

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 247 at r3](https://reviewable.io/reviews/harness/harness-core/38956#-NEj0YNG0uRHSKK8Hz-6:-NEj6dY480_CavD8g7B1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e223358486ce8288a07eed2a8b8006c9ef3a9085/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L247)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to check "comments" in case of REMOTE?
</blockquote></details>

Done.

**Review by inderschera — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: 1. unresolved discussions.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 247 at r4](https://reviewable.io/reviews/harness/harness-core/38956#-NEo6LFUCxhKPuZ0YzMu:-NEo6LFUCxhKPuZ0YzMv:b-kjoji) ([raw file](https://github.com/harness/harness-core/blob/3e551bb0faa4aa8710c1d3d7b0d3e9aaae8a7c47/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L247)):*
> ```Java
>         templateEntity.getIdentifier(), templateEntity.getVersionLabel(), projectId, orgId, accountId));
>     if (gitEntityCreateInfo != null && StoreType.REMOTE.equals(gitEntityCreateInfo.getStoreType())
>         && gitEntityCreateInfo.getCommitMsg() != null) {
> ```

if its empty commit message, we should put a default commit message here. Ignoring it here means we respect "comments" field in the request which is wrong for REMOTE entities.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 550 at r5](https://reviewable.io/reviews/harness/harness-core/38956#-NEoHNhm7yQPprNQL6Aw:-NEoHNhm7yQPprNQL6Ax:b3fxzo9) ([raw file](https://github.com/harness/harness-core/blob/e9dd3a72cfe7e17429b03b14824d9bd3ffee06a8/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L550)):*
> ```Java
>       if (isNotEmpty(projectIdentifier)) {
>         return String.format(
>             "[HARNESS]: creating template with identifier [%s] in account [%s] org [%s] in project [%s]",
> ```

its not always creating template. It can be "updating" also.

Its fine if we aren't that specific about the commit message. I mean if it doesn't have proper ids, then also it works. We just need to come up with basic default message thats descriptive enough

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: :shipit: complete! ✓

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java` line 548 at r6](https://reviewable.io/reviews/harness/harness-core/38956#-NEoY4PL9563kOKkQ_eD:-NEoY4PL9563kOKkQ_eE:b-ncw8fw) ([raw file](https://github.com/harness/harness-core/blob/4b8ed971e352137f0ce6e255c31455fc95033c74/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java#L548)):*
> ```Java
>     } else {
>       return String.format(
>           "[HARNESS]: Template with template identifier [%s] has been [%s]", templateIdentifier, operationType);
> ```

Let's add versionLabel as well here?

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38956)* status: :shipit: complete! ✓

**Pull request merged**
