### PR TITLE
feat: [PIE-9505]: expose grpc endpoint to get user details via scm using token

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut0, ut1

**Comment by shalini-agr** [comment]
trigger ut7

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 874 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIsoSg2-FGGWqEJ-W4:-NTIsoSg2-FGGWqEJ-W5:bojci7o) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L874)):*
> ```Java
> 
>   @Override
>   public GetAuthenticatedUserResponse getAuthenticatedUser(GetAuthenticatedUserRequest request) {
> ```

we decided to change the name of the method right?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIt-I6Cn4YwQeAhwSV:-NTIt-I6Cn4YwQeAhwSW:bxuolt7) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L181)):*
> ```Java
>       io.grpc.stub.StreamObserver<io.harness.gitsync.GetAuthenticatedUserResponse> responseObserver) {
>     GetAuthenticatedUserResponse getAuthenticatedUserResponse;
>     try (GlobalContextManager.GlobalContextGuard guard = GlobalContextManager.ensureGlobalContextGuard()) {
> ```

please check how we pass context as well into the try block in other methods to facilitate logging.

**Comment by shalini-agr** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 874 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIsoSg2-FGGWqEJ-W4:-NTJ73K03L9Y3nDE5YzI:b-euvga2) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L874)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we decided to change the name of the method right?
</blockquote></details>

yes, guess i missed to change here, done now

**Comment by shalini-agr** [comment]
trigger ut5

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIt-I6Cn4YwQeAhwSV:-NTJRzcX42h9trgA5Bnr:bmap82i) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L181)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please check how we pass context as well into the try block in other methods to facilitate logging.
</blockquote></details>

done.
adding request.toString() directly into the map as our request object is a complex object having different impls for all git providers

**Comment by shalini-agr** [comment]
trigger ut0

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 2 of 32 files at r2, 33 of 33 files at r3, 4 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIt-I6Cn4YwQeAhwSV:-NTNBO8J6a_ARrjDtDxY:b7794mx) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L181)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

done.
adding request.toString() directly into the map as our request object is a complex object having different impls for all git providers
</blockquote></details>

you may even build an autolog context for your specific flows.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/46223#-NTNuYEyALX2a0Fh7eNM:-NTNuYEyALX2a0Fh7eNN:bjcudh8) ([raw file](https://github.com/harness/harness-core/blob/d3037831bd0e518101413b0379694d777306e7d9/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L18)):*
> ```protobuf
> 
> option java_multiple_files = true;
> ```

We use grpc when we want a faster communication between services at the expense of flexibility. Did you check why only grpc not rest calls not used in your case. Would be helpful if you state it here.

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 874 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIsoSg2-FGGWqEJ-W4:-NTNynX5BFnLs2nHZs-I:b-9fyn9x) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L874)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

yes, guess i missed to change here, done now
</blockquote></details>

Please use blank lines in methods so as to improve readability.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIt-I6Cn4YwQeAhwSV:-NTNyzN59WYuFRWn23BY:b-bk5ajf) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L181)):*
> Please use blank lines in methods so as to improve readability. Code in this file is very congested use blank lines

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/46223#-NTNuYEyALX2a0Fh7eNM:-NTO1EP77ZE1_jjM-MoP:b-41hr5w) ([raw file](https://github.com/harness/harness-core/blob/d3037831bd0e518101413b0379694d777306e7d9/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L18)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

We use grpc when we want a faster communication between services at the expense of flexibility. Did you check why only grpc not rest calls not used in your case. Would be helpful if you state it here.
</blockquote></details>

I would think we would have made this call while implementing gitX considering the advantages we get with grpc over rest client. @mohitg0795 can elaborate here i guess.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 181 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIt-I6Cn4YwQeAhwSV:-NTODQZn6b9s9LEaMgCr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L181)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

> Please use blank lines in methods so as to improve readability. Code in this file is very congested use blank lines
</blockquote></details>

Done.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 41 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java` line 874 at r3](https://reviewable.io/reviews/harness/harness-core/46223#-NTIsoSg2-FGGWqEJ-W4:-NTODTUR9Yn92wCFofvX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7a6d7c1d81be0dd33e2e58d92d5e67e0f81ee58a/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/HarnessToGitHelperServiceImpl.java#L874)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Please use blank lines in methods so as to improve readability.
</blockquote></details>

Done.

**Comment by shalini-agr** [comment]
trigger ut0

**Comment by shalini-agr** [comment]
trigger utAll

**Comment by mohitg0795** [comment]
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/46223#-NTNuYEyALX2a0Fh7eNM:-NTPzHnSA49DalIv9nyT:b-i13yty) ([raw file](https://github.com/harness/harness-core/blob/d3037831bd0e518101413b0379694d777306e7d9/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L18)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

I would think we would have made this call while implementing gitX considering the advantages we get with grpc over rest client. @mohitg0795 can elaborate here i guess.
</blockquote></details>

All intra-system calls should be GRPC if possible as its faster as you correctly mentioned @senjucanon2. I didn't get your ques : you're justifying GRPC calls and then asking why not REST calls used here :-p 

Also, lets keep up such questions coming, but mark them "discussing" while commenting on PRs. These are good for discussions but just want to avoid getting PR blocked on it. Lets discuss more offline if required. Thanks.

**Review by mohitg0795 — COMMENTED** [review]
> Reviewed 2 of 32 files at r2, 33 of 33 files at r3, 3 of 5 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 184 at r6](https://reviewable.io/reviews/harness/harness-core/46223#-NTPyGrS1FQyTvuz4_cr:-NTR_ERl5Op5r5eNE5KZ:b-mkqtbr) ([raw file](https://github.com/harness/harness-core/blob/c5dcd623b3244f4d829d81f3c823e4a8dc1e1498/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L184)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This looks untidy using blank hardcoded strings and somewhere using null. Can we do better here?
eg:
1) Best thing that I can think is to create such methods in the helper class such that we are able to use something like builder methods here as well. eg: I will say ".setContextMap().accountIdentifier("xyz")" and this should initiate a map and set the account identifier. I can keep on adding further fields to it the same way how we use builders.

2) Initialize some constant in the file eg: EMPTY_STRING = "" or similar and use it everywhere. 
</blockquote></details>

1. We already have a field contextMap in this method which we can use to enter the custom information. We can just keep on adding key-value pairs here and they will be added in the context. Not sure how we could have builder-like behavior here.
2. done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java` line 184 at r6](https://reviewable.io/reviews/harness/harness-core/46223#-NTPyGrS1FQyTvuz4_cr:-NTSDlx5Efwv0Xm8RFsF:b-n0uk5i) ([raw file](https://github.com/harness/harness-core/blob/c5dcd623b3244f4d829d81f3c823e4a8dc1e1498/136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java#L184)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

1. We already have a field contextMap in this method which we can use to enter the custom information. We can just keep on adding key-value pairs here and they will be added in the context. Not sure how we could have builder-like behavior here.
2. done.
</blockquote></details>

Think about 1. Consider it as a side hustle for now. We will discuss once you're able to come up with something. cc @senjucanon2 also think about it.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by senjucanon2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/46223#-NTNuYEyALX2a0Fh7eNM:-NTT3CeIEpkUsd8PfmEl:bosbuyx) ([raw file](https://github.com/harness/harness-core/blob/d3037831bd0e518101413b0379694d777306e7d9/953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto#L18)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

All intra-system calls should be GRPC if possible as its faster as you correctly mentioned @senjucanon2. I didn't get your ques : you're justifying GRPC calls and then asking why not REST calls used here :-p 

Also, lets keep up such questions coming, but mark them "discussing" while commenting on PRs. These are good for discussions but just want to avoid getting PR blocked on it. Lets discuss more offline if required. Thanks.
</blockquote></details>

As discussed with Shaloni grpc is a faster mode of communincation and we didn't require some high level of flexibility here, thats why grpc is preferred over normal rest api calls.

**Review by senjucanon2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46223)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
