### PR TITLE
fix: [CDS-50388]: "Null Pointer Exception" during SSH "Command Script…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…s" - no referential integrity check/surfacing of Secret File used by SSH secret

## Describe your changes
Adding null checks after decrypting secret references and displaying HintException.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42650)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Comment by abhayganvir** [comment]
trigger messagecheck

**Comment by acasian-harness** [comment]
trigger gitleaks

**Review by acasian-harness — COMMENTED** [review]
@bojanmicovic let's consider adding UT covering this use case.

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42650#-:-NLzqEkZ75cfDIw56LZZ:b8wik0f)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Comment by USB-05** [comment]
trigger gl

**Comment by USB-05** [comment]
trigger gl

**Review by ivan-83 — APPROVED** [review]
Just add UT, the other looks good to me.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42650#-:-NM3X5A0BCfU5Qfd709V:b7scdt4)* status: 7 file(s) to review. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/utils/SecretUtils.java` line 26 at r3](https://reviewable.io/reviews/harness/harness-core/42650#-NM3XHED4Hn-8CIUWfmh:-NM3XHEE2u9f42AMadrP:bxuywjp) ([raw file](https://github.com/harness/harness-core/blob/0e8d635f8c1095331d2954e56049059d796ca310/980-commons/src/main/java/io/harness/utils/SecretUtils.java#L26)):*
> ```Java
>     if (decryptedValue == null) {
>       throw hintWithExplanationException(String.format(HINT_DECRYPTED_SECRET_VALUE, identifier),
>           SECRET_DECRYPTED_VALUE_INVALID, new InvalidRequestException("Decrypted value of the secret is null."));
> ```

We could add an identifier to the exception error msg.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42650)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
