### PR TITLE
feat: [CDS-78524]: add adviser for retry failure strategy

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Added a field manualInterventionActionConfigPostRetry in RetryAdviserRollbackParameters which can replace retryActionConfig as we only need the spec of manual intervention from this field. And we have also added the retry failure strategy advisers. With these changes, we have retry failure strategy working with v1 yaml.

**Testing:** Tested that retry failure strategies is working correctly at stage, step, and step group level. Also tested that the changes are backward compatible. To verify backward compatibility, we first started a pipeline on develop build and then reran the pipeline service on this branch, and verified that the retry happened as expected.

https://github.com/harness/harness-core/assets/97503816/170d1ff4-b1e5-4950-8aaa-fa9e4d600b27

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52406)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52406)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 3026 at r2](https://reviewable.io/reviews/harness/harness-core/52406#-Ndiq49N7R_CXNoiQ0Bx:-Ndiq49N7R_CXNoiQ0By:b8k0taa) ([raw file](https://github.com/harness/harness-core/blob/519796de8a42df9cc349d48e235164db2f04dea6/400-rest/src/test/resources/manager-kryo-registrations.txt#L3026)):*
> ```help
> 878050:io.harness.yaml.core.failurestrategy.retry.v1.RetryFailureSpecConfigV1
> 878051:io.harness.yaml.core.failurestrategy.retry.v1.RetryStepGroupFailureSpecConfigV1
> 878052:io.harness.advisers.retry.ManualInterventionActionConfigPostRetry
> ```

which test is failing we dont add it here?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/ActionConfigPostRetry.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/52406#-Ndiq89n3FOl7dSRJcUd:-Ndiq89n3FOl7dSRJcUe:bz9l6gq) ([raw file](https://github.com/harness/harness-core/blob/519796de8a42df9cc349d48e235164db2f04dea6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/ActionConfigPostRetry.java#L14)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.PIPELINE)
> public interface ActionConfigPostRetry {}
> ```

add codepulse to all new classes
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserRollbackParameters.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/52406#-NdiqAZT8wGA7Zdtk0Tv:-NdiqAZT8wGA7Zdtk0Tw:byz3cmk) ([raw file](https://github.com/harness/harness-core/blob/519796de8a42df9cc349d48e235164db2f04dea6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserRollbackParameters.java#L35)):*
> ```Java
>   int retryCount;
>   RepairActionCode repairActionCodeAfterRetry;
>   FailureStrategyActionConfig retryActionConfig; // used only in case of manual intervention action type (will be
> ```

use @deprecated annotation, then comment is not required

**Comment by shalini-agr** [comment]
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 3026 at r2](https://reviewable.io/reviews/harness/harness-core/52406#-Ndiq49N7R_CXNoiQ0Bx:-NdixEYx5t0l-qk4ahCv:bkg9jli) ([raw file](https://github.com/harness/harness-core/blob/519796de8a42df9cc349d48e235164db2f04dea6/400-rest/src/test/resources/manager-kryo-registrations.txt#L3026)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

which test is failing we dont add it here?
</blockquote></details>

ManagerKryoRegistrationTest is failing, this is also testing PmsSdkCoreKryoRegistrar

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52406)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/ActionConfigPostRetry.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/52406#-Ndiq89n3FOl7dSRJcUd:-NdixQCq2NYSNo04IrC4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/519796de8a42df9cc349d48e235164db2f04dea6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/ActionConfigPostRetry.java#L14)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add codepulse to all new classes
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserRollbackParameters.java` line 35 at r2](https://reviewable.io/reviews/harness/harness-core/52406#-NdiqAZT8wGA7Zdtk0Tv:-NdixQr96gb_ubWfNpsj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/519796de8a42df9cc349d48e235164db2f04dea6/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/retry/RetryAdviserRollbackParameters.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

use @deprecated annotation, then comment is not required
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52406)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52406)* status: :shipit: complete! ✓

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
