### PR TITLE
feat: [IDP-1313]: Scorecard improvements

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
Scorecard improvements
1. Evaluate code duplication in Dsl and move to common place
2. Streamline DSL layer
3. Streamline provider code
4. Streamline parser code
5. Misc bug fixes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 53 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Niixo21-JIcacWSVRbx:-Niixo21-JIcacWSVRby:b9xaz5c) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java#L47)):*
> ```Java
>       DataPointEntity dataPoint, List<InputValue> inputValues, BackstageCatalogEntity backstageCatalogEntity);
> 
>   protected abstract boolean validate(DataFetchDTO dataFetchDTO, Map<String, Object> data,
> ```

validate returning true would mean that validation was successful. But here it's the other way round. 
Could we switch the meaning? Otherwise, we could call this method something else? IsNotValid() maybe



_Code quote:_
```Java
validate
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij-OxE6VJeNDRdrQOv:-Nij-OxE6VJeNDRdrQOw:b-uzhmye) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java#L138)):*
> ```Java
>           (List<Map<String, Object>>) GsonUtils.convertJsonStringToObject(response.getEntity().toString(), Map.class)
>               .get(ERRORS);
>       ruleData.put(ERROR_MESSAGE_KEY, errors.get(0).get(MESSAGE_KEY));
> ```

This part is common in both fetchData() methods. Could we move it to a common method?



_Code quote:_
```Java
    String requestBody = constructRequestBody(
        apiRequestDetails, possibleReplaceableRequestBodyPairs, dataPoint, inputValues, backstageCatalogEntity);
    apiRequestDetails.setRequestBody(requestBody);
    DslClient dslClient = dslClientFactory.getClient(accountIdentifier, getHost(possibleReplaceableRequestBodyPairs));
    Response response = getResponse(apiRequestDetails, dslClient, accountIdentifier);
    Map<String, Object> ruleData = new HashMap<>();
    if (response.getStatus() == 200) {
      ruleData.put(DSL_RESPONSE, GsonUtils.convertJsonStringToObject(response.getEntity().toString(), Map.class));
    } else if (response.getStatus() == 500) {
      ruleData.put(ERROR_MESSAGE_KEY, ((ResponseMessage) response.getEntity()).getMessage());
    } else {
      List<Map<String, Object>> errors =
          (List<Map<String, Object>>) GsonUtils.convertJsonStringToObject(response.getEntity().toString(), Map.class)
              .get(ERRORS);
      ruleData.put(ERROR_MESSAGE_KEY, errors.get(0).get(MESSAGE_KEY));
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1YSyAzUFF8ieNtqT:-Nij1YSyAzUFF8ieNtqU:bty4a1q) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java#L172)):*
> ```Java
> 
>     String requestBody = constructRequestBody(
>         apiRequestDetails, possibleReplaceableRequestBodyPairs, dataPoint, inputValues, backstageCatalogEntity);
> ```

Won't the data point be null here?



_Code quote:_
```Java
dataPoint
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/github/GithubOpenSecretScanningAlertsDsl.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij0ZDDBtxn0Pwoz_Pi:-Nij0ZDEB5KwT9TPun9J:bx4ogk1) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/github/GithubOpenSecretScanningAlertsDsl.java#L54)):*
> ```Java
>       return true;
>     }
>     return false;
> ```

All the Github DSLs have this. Should we move this to common? Or do you think it might be an overkill?



_Code quote:_
```Java
    if (isEmpty(possibleReplaceableRequestBodyPairs.get(REPO_SCM))
        || isEmpty(possibleReplaceableRequestBodyPairs.get(REPOSITORY_OWNER))
        || isEmpty(possibleReplaceableRequestBodyPairs.get(REPOSITORY_NAME))) {
      data.put(dataFetchDTO.getRuleIdentifier(), Map.of(ERROR_MESSAGE_KEY, SOURCE_LOCATION_ANNOTATION_ERROR));
      return true;
    }
    return false;
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1yIl3UQqE3pejCXX:-Nij1yIl3UQqE3pejCXY:b-f6vacw) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java#L60)):*
> ```Java
>   @Override
>   protected String getHost(Map<String, String> data) {
>     return null;
> ```

this should return the host from the URL right? 



_Code quote:_
```Java
return null;
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/BitbucketProvider.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij2fhQD49CYsoPm1rw:-Nij2fhQD49CYsoPm1rx:b-g1dbm7) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/BitbucketProvider.java#L54)):*
> ```Java
>   public Map<String, Map<String, Object>> fetchData(String accountIdentifier, BackstageCatalogEntity entity,
>       List<DataFetchDTO> dataPointsAndInputValues, String configs) {
>     Map<String, String> authHeaders = this.getAuthHeaders(accountIdentifier, configs);
> ```

Intellij is suggesting couple of blocks that's common across Github, Bitbucket and Gitlab providers. Could we check once if something needs to be done here?



_Code quote:_
```Java
Map
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/DataSourceProvider.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-NiizZCw1llNjnQMLGQm:-NiizZCw1llNjnQMLGQn:bvdqgr3) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/DataSourceProvider.java#L114)):*
> ```Java
>       if (Objects.equals(identifier, KUBERNETES_IDENTIFIER) || Objects.equals(identifier, HARNESS_IDENTIFIER)
>           || Objects.equals(identifier, PAGERDUTY_IDENTIFIER)) {
>         try {
> ```

workflowsCount, openSecretScanningAlerts. These don't take any inputs.
So within a DS, each DSL can either have inputs or not have. Should we have this kind of check somewhere in DSL layer?



_Code quote:_
```Java
      if (Objects.equals(identifier, KUBERNETES_IDENTIFIER) || Objects.equals(identifier, HARNESS_IDENTIFIER)
          || Objects.equals(identifier, PAGERDUTY_IDENTIFIER)) {
        try {
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/KubernetesProvider.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij3EsHArtrcUeHcjJB:-Nij3EsHArtrcUeHcjJC:bjz1isd) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/KubernetesProvider.java#L83)):*
> ```Java
> 
>   @Override
>   protected Map<String, String> prepareUrlReplaceablePairs(String... keysValues) {
> ```

We are doing the same in harness provider. Could we move it to a common place?



_Code quote:_
```Java
prepareUrlReplaceablePairs
```

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 62 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/github/GithubOpenSecretScanningAlertsDsl.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij0ZDDBtxn0Pwoz_Pi:-Nis2zFh2ZwFNz8JYFLs:bb1gv0t) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/github/GithubOpenSecretScanningAlertsDsl.java#L54)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

All the Github DSLs have this. Should we move this to common? Or do you think it might be an overkill?
</blockquote></details>

Done. Makes sense. Now we have SCM base DSL
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/BitbucketProvider.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij2fhQD49CYsoPm1rw:-Nis3Dvo9S90QYdzmCrI:b-k1knbg) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/BitbucketProvider.java#L54)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Intellij is suggesting couple of blocks that's common across Github, Bitbucket and Gitlab providers. Could we check once if something needs to be done here?
</blockquote></details>

Done. Now we have Scm Base Provider

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 63 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Niixo21-JIcacWSVRbx:-NisEyWd-Zfpz4-h1iGA:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java#L47)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

validate returning true would mean that validation was successful. But here it's the other way round. 
Could we switch the meaning? Otherwise, we could call this method something else? IsNotValid() maybe
</blockquote></details>

Done
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/KubernetesProvider.java` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij3EsHArtrcUeHcjJB:-NisF1UtEUdMUm5EF3Dp:bdlsw86) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/KubernetesProvider.java#L83)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We are doing the same in harness provider. Could we move it to a common place?
</blockquote></details>

Done. Moved it to common utils and using it from there. We cannot normalize at DataProvider layer as it doesn't share other things in common.

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 63 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1yIl3UQqE3pejCXX:-NisFe9UCgNnDzeuLVjA:b-a79jsq) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java#L60)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

this should return the host from the URL right?
</blockquote></details>

No. This host is used to determine direct or delegate client. Previously also we were passing null in the function call.
Now with generic layer, each DSL will override this getHost method

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 101 file(s) to review. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java` line 138 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij-OxE6VJeNDRdrQOv:-Nit_C8zCDzNrOQCQB5U:bmfnl46) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java#L138)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

This part is common in both fetchData() methods. Could we move it to a common method?
</blockquote></details>

Done. Handled it.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1YSyAzUFF8ieNtqT:-Nit_5qH0g22hj0uH9nI:bmfnl46) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocation.java#L172)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Won't the data point be null here?
</blockquote></details>

Done. Handled it.

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Review by vigneswara-propelo — DISMISSED** [review]
> Reviewed 6 of 53 files at r1, 1 of 30 files at r2, 42 of 81 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 95 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocationNoLoop.java` line 66 at r5](https://reviewable.io/reviews/harness/harness-core/55131#-NiyFwj07nb6qsnHZdZ0:-NiyFwj07nb6qsnHZdZ1:b-mbj2wa) ([raw file](https://github.com/harness/harness-core/blob/451dcbb47b9772d29df00d03707515d7bd07fefb/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocationNoLoop.java#L66)):*
> ```Java
>       List<Map<String, Object>> errors =
>           (List<Map<String, Object>>) GsonUtils.convertJsonStringToObject(response.getEntity().toString(), Map.class)
>               .get(ERRORS);
> ```

Error response for each data source varies. They may return List or just Map and the "ERROR" key also varies. 

GitHub -> Map, MESSAGE_KEY
Jira -> Map, ERROR_MESSAGES_KEY
GitLab -> List, ERRORS

We will have to include these as well.



_Code quote:_
```Java
      List<Map<String, Object>> errors =
          (List<Map<String, Object>>) GsonUtils.convertJsonStringToObject(response.getEntity().toString(), Map.class)
              .get(ERRORS);
```

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 10 of 30 files at r2, 72 of 81 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 52 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1yIl3UQqE3pejCXX:-NizBmj38YWdAeQ_RqKp:b-7vj68h) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java#L60)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

No. This host is used to determine direct or delegate client. Previously also we were passing null in the function call.
Now with generic layer, each DSL will override this getHost method
</blockquote></details>

Ok. Just wondering if the PagerDuty plugin is configured to go through the delegate, scorecard data fetch also should go through the delegate right? Here it will always use direct client.

**Comment by sathish-soundarapandian** [comment]
> > Reviewed 10 of 30 files at r2, 72 of 81 files at r4, 9 of 9 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)_ status: 52 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1yIl3UQqE3pejCXX:-NizBmj38YWdAeQ_RqKp:b-7vj68h) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java#L60)):_
> 
> Previously, sathish-soundarapandian (Sathish) wrote…
> Ok. Just wondering if the PagerDuty plugin is configured to go through the delegate, scorecard data fetch also should go through the delegate right? Here it will always use direct client.

Seems to be an existing issue then.
When I did these changes, I first compared each DSL logic and moved it to common place one by one. Previously also, pager-duty DSLs were passing it as null.
Let me check again and fix it with the right data.

**Review by sathish-soundarapandian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 57 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocationNoLoop.java` line 66 at r5](https://reviewable.io/reviews/harness/harness-core/55131#-NiyFwj07nb6qsnHZdZ0:-NjHSZyY3VGesTPtyrB-:bwsvmh4) ([raw file](https://github.com/harness/harness-core/blob/451dcbb47b9772d29df00d03707515d7bd07fefb/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/DataSourceLocationNoLoop.java#L66)):*
<details><summary><i>Previously, vigneswara-propelo (Vigneswara) wrote…</i></summary><blockquote>

Error response for each data source varies. They may return List or just Map and the "error" also varies. 

GitHub -> Map, MESSAGE_KEY
Jira -> Map, ERROR_MESSAGES_KEY
GitLab -> List, ERRORS

We will have to include these as well.
</blockquote></details>

Done. Handled it
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java` line 60 at r1](https://reviewable.io/reviews/harness/harness-core/55131#-Nij1yIl3UQqE3pejCXX:-NjHSegZ7eopTfK6Yxkq:bsy8sge) ([raw file](https://github.com/harness/harness-core/blob/e560a592f8e30b89fb30df03c44c049086d902e7/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/pagerduty/PagerDutyServiceDirectory.java#L60)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Seems to be an existing issue then.
When I did these changes, I first compared each DSL logic and moved it to common place one by one. Previously also, pager-duty DSLs were passing it as null.
Let me check again and fix it with the right data.

</blockquote></details>

Done. Existing issue. Will take it up in separate PR

**Review by vigneswara-propelo — APPROVED** [review]

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 26 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55131)* status: 57 file(s) to review. 1. unresolved discussions.

**Comment by vikyathharekal** [comment]
trigger review

**Comment by sathish-soundarapandian** [comment]
trigger uts

**Pull request merged**
