### PR TITLE
fix: [PL-29541]: Removed logging error in exceptionMappers

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40022)

### CODE REVIEW

**Comment by AnshuH** [comment]
trigger codeformat

**Comment by AnshuH** [comment]
trigger codeformat

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40022)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/exception/BadRequestExceptionMapper.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4F0yzA7zuLfNFFSfK:-NH4F0yzA7zuLfNFFSfL:b7llk2g) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/300-cv-nextgen/src/main/java/io/harness/cvng/exception/BadRequestExceptionMapper.java#L29)):*
> ```Java
>   @Override
>   public Response toResponse(BadRequestException exception) {
>     // removed logging of the above exception here as this exception is being added in the error message that is
> ```

No need of this msg
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotAllowedExceptionMapper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4EzwF9FxiJt8ToLZD:-NH4EzwF9FxiJt8ToLZE:b7llk2g) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotAllowedExceptionMapper.java#L24)):*
> ```Java
>   @Override
>   public Response toResponse(NotAllowedException exception) {
>     // removed logging of the above exception here as this exception is being added in the error message that is
> ```

No need of this msg
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotFoundExceptionMapper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4Ey4GDoP4MHXQFSYA:-NH4Ey4GDoP4MHXQFSYB:b7llk2g) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotFoundExceptionMapper.java#L24)):*
> ```Java
>   @Override
>   public Response toResponse(NotFoundException exception) {
>     // removed logging of the above exception here as this exception is being added in the error message that is
> ```

No need of this msg
___
*[`980-commons/src/main/java/io/harness/exception/ConstraintViolationExceptionMapper.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4EsAI0tIYTMaPvQ2q:-NH4EsAI0tIYTMaPvQ2r:b-pdujfc) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/980-commons/src/main/java/io/harness/exception/ConstraintViolationExceptionMapper.java#L34)):*
> ```Java
>   @Override
>   public Response toResponse(ConstraintViolationException exception) {
>     // removed logging of the above exception here as this exception is being added in the error message that is
> ```

No need of these msgs
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4FI3yDkr1khv9WiTo:-NH4FI3yDkr1khv9WiTp:btjj3gg) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java#L68)):*
> ```Java
>         jsonNodeMap.put(cacheKey, expansionResponse);
>         expansionResponseBatchBuilder.addExpansionResponseProto(convertToResponseProto(jsonNodeMap.get(cacheKey), fqn));
>       } catch (Exception ex) {
> ```

Pls get changes in Pipeline Service Client reviewed from Archit 
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 179 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4F9jL5rRC7NIbJo6n:-NH4F9jL5rRC7NIbJo6o:btjj3gg) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L179)):*
> ```Java
>       return PlanCreatorServiceHelper.handlePlanCreationResponses(
>           planCreationResponses, finalResponse, currentYaml, dependencies, dependenciesList);
>     } catch (Exception ex) {
> ```

Pls get changes in Pipeline Service Client reviewed from Archit 
___
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/exception/NotificationExceptionMapper.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4ElV0CqbT1ejc2A6y:-NH4ElV0CqbT1ejc2A6z:b-pdujfc) ([raw file](https://github.com/harness/harness-core/blob/32187c0b280b7a970c6cb14a6acb7a0c88bf1618/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/exception/NotificationExceptionMapper.java#L23)):*
> ```Java
>   @Override
>   public Response toResponse(NotificationException exception) {
>     // removed logging of the above exception here as this exception is being added in the error message that is
> ```

No need of these msgs

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40022)* status: 13 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/exception/BadRequestExceptionMapper.java` line 29 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4F0yzA7zuLfNFFSfK:-NHNgIU1DCNgF5dZVyqu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/300-cv-nextgen/src/main/java/io/harness/cvng/exception/BadRequestExceptionMapper.java#L29)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need of this msg
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotAllowedExceptionMapper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4EzwF9FxiJt8ToLZD:-NHNgJ842SgJth5S7IZA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotAllowedExceptionMapper.java#L24)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need of this msg
</blockquote></details>

Done.
___
*[`960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotFoundExceptionMapper.java` line 24 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4Ey4GDoP4MHXQFSYA:-NHNgJk_6OwaF4QbJLzA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers/NotFoundExceptionMapper.java#L24)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need of this msg
</blockquote></details>

Done.
___
*[`980-commons/src/main/java/io/harness/exception/ConstraintViolationExceptionMapper.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4EsAI0tIYTMaPvQ2q:-NHNgKFR2qqyzpbYDIcx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/980-commons/src/main/java/io/harness/exception/ConstraintViolationExceptionMapper.java#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need of these msgs
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java` line 68 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4FI3yDkr1khv9WiTo:-NHNgLpXBMvoB-Hgc2mJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance/JsonExpansionService.java#L68)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Pls get changes in Pipeline Service Client reviewed from Archit 
</blockquote></details>

Done.
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java` line 179 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4F9jL5rRC7NIbJo6n:-NHNgMYC55FGsxfJm8ZJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorService.java#L179)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Pls get changes in Pipeline Service Client reviewed from Archit 
</blockquote></details>

Done.
___
*[`platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/exception/NotificationExceptionMapper.java` line 23 at r4](https://reviewable.io/reviews/harness/harness-core/40022#-NH4ElV0CqbT1ejc2A6y:-NHNgNES28Upf9dXH1Jw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ee784903af0374fc49a52eba710655c88271df8d/platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/exception/NotificationExceptionMapper.java#L23)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need of these msgs
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40022#-:-NHO0K5-9Tk5d0dyoAls:bnfp4nl)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`980-commons/src/main/java/io/harness/logging/ExceptionLogger.java` line 101 at r5](https://reviewable.io/reviews/harness/harness-core/40022#-NHOUdxE0sRumSkp-jNs:-NHOUdxFEtTEHPUFKQm4:b-lqf87j) ([raw file](https://github.com/harness/harness-core/blob/332f7aeefee487b72f4aac274bafa36e259d1a92/980-commons/src/main/java/io/harness/logging/ExceptionLogger.java#L101)):*
> ```Java
>       }
> 
>       List<ResponseMessage> responseMessages = getResponseMessageList(exception, target);
> ```

Add null check for responseMessages

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40022)* status: 13 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/logging/ExceptionLogger.java` line 101 at r5](https://reviewable.io/reviews/harness/harness-core/40022#-NHOUdxE0sRumSkp-jNs:-NHOVf39CXB3FIrhMHbL:b-i56dnd) ([raw file](https://github.com/harness/harness-core/blob/332f7aeefee487b72f4aac274bafa36e259d1a92/980-commons/src/main/java/io/harness/logging/ExceptionLogger.java#L101)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Add null check for responseMessages
</blockquote></details>

This responseMessages cannot be null. We will send an empty list if no messages are found

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40022)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40022)* status: :shipit: complete! ✓

**Pull request merged**
