### PR TITLE
feat: [CDS-71627]: Added stage execution entity service

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added stage execution entity service, to save the stage execution info to mongo db.
Added syncing data for Custom stage
Also added event handler to update the status and endts when the stage execution ends

Tested locally if the data sync is happening

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49925)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49925)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStageExecutionUpdateEventHandler.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/49925#-NZUJ4OlDa4HcokQIqmw:-NZUJ4OlDa4HcokQIqmx:b-kepkvz) ([raw file](https://github.com/harness/harness-core/blob/da293a7fc03c36ceb7d70b4a8ce93527aaaeef66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStageExecutionUpdateEventHandler.java#L45)):*
> ```Java
>       return;
>     }
>     if (!pmsFeatureFlagService.isEnabled(
> ```

Can we check terminal status also before FF check, as this will reduce calls to FF and checking terminal status is O(1)
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/stage/StageExecutionEntityServiceImpl.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/49925#-NZUJygl0oM-4dPhFiRC:-NZUJygl0oM-4dPhFiRD:bhswxbi) ([raw file](https://github.com/harness/harness-core/blob/da293a7fc03c36ceb7d70b4a8ce93527aaaeef66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/stage/StageExecutionEntityServiceImpl.java#L139)):*
> ```Java
>   }
> 
>   private void getUpdatesFromStageExecutionEntityUpdateDTO(StageExecutionEntity currentStageExecutionEntity,
> ```

cant we update complete object at one go, what if new field is added in future and we forget to add to this updates?
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageStep.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/49925#-NZUKK6G9ydlvjGCV1wo:-NZUKK6G9ydlvjGCV1wp:boxnuvr) ([raw file](https://github.com/harness/harness-core/blob/da293a7fc03c36ceb7d70b4a8ce93527aaaeef66/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageStep.java#L72)):*
> ```Java
>     log.info("Executed custom stage [{}]", stepParameters);
>     StepResponse stepResponse = createStepResponseFromChildResponse(responseDataMap);
>     if (pmsFeatureFlagHelper.isEnabled(
> ```

this we discussed we can do via status handler isn't?

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageStep.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/49925#-NZUKK6G9ydlvjGCV1wo:-NZUN-On1ADby3XUnkOF:bsib2rv) ([raw file](https://github.com/harness/harness-core/blob/da293a7fc03c36ceb7d70b4a8ce93527aaaeef66/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageStep.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this we discussed we can do via status handler isn't?
</blockquote></details>

we wanted the failure info, that's why added it here

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/stage/StageExecutionEntityServiceImpl.java` line 139 at r2](https://reviewable.io/reviews/harness/harness-core/49925#-NZUJygl0oM-4dPhFiRC:-NZUNJGAAv0atr7Q9IsL:b-rpe4rz) ([raw file](https://github.com/harness/harness-core/blob/da293a7fc03c36ceb7d70b4a8ce93527aaaeef66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/stage/StageExecutionEntityServiceImpl.java#L139)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

cant we update complete object at one go, what if new field is added in future and we forget to add to this updates?
</blockquote></details>

I added like this, as when we are updating the entity, it might be that we are only updating a part of it, as we might not have the full info. For e.g. the end status event handler would have endts, but won't have the failure info. Similarly at the start of the step it won't have the step response(if req. in future) and endts.

**Comment by RishabhGupta34** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStageExecutionUpdateEventHandler.java` line 45 at r2](https://reviewable.io/reviews/harness/harness-core/49925#-NZUJ4OlDa4HcokQIqmw:-NZUNvYGD9L1wH4GXL3D:b-m3k5ej) ([raw file](https://github.com/harness/harness-core/blob/da293a7fc03c36ceb7d70b4a8ce93527aaaeef66/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events/PipelineStageExecutionUpdateEventHandler.java#L45)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we check terminal status also before FF check, as this will reduce calls to FF and checking terminal status is O(1)
</blockquote></details>

sure, let me change

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49925)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49925)* status: :shipit: complete! ✓

**Comment by RishabhGupta34** [comment]
trigger review

**Pull request merged**
