### PR TITLE
[feat]: [PL-24883]: FF eval

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
Sending account name along with account id when evaluating feature flag. This change also adds caching layer, which will ensure that we don't make repeated rest calls. 
Cache used - Caffeine with expiryAfterWrite as 1 hr and max size as 200. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36929)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36929)

**Comment by shreyas-harness** [comment]
trigger ti3

**Comment by shreyas-harness** [comment]
trigger ti1

**Comment by shreyas-harness** [comment]
trigger ti2

**Comment by shreyas-harness** [comment]
trigger ti4

**Comment by shreyas-harness** [comment]
trigger ti1

**Comment by mohitg0795** [comment]
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 240 at r3](https://reviewable.io/reviews/harness/harness-core/36929#-NAp6x8vEogWI9TAplWc:-NAp6x8vEogWI9TAplWd:b-5ntd6h) ([raw file](https://github.com/harness/harness-core/blob/cef4a15fc260da0f293c11b4be0615bbf66fff1a/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L240)):*
> ```Java
>         log.info(String.format("Account Id passed is empty when evaluating for feature %s ", featureName.name()));
>       }
>       accountId = FeatureFlagConstants.STATIC_ACCOUNT_ID;
> ```

Shouldn't this be inside the isEmpty() check? If yes, I think we have missed a UT to ensure it, lets add that also.

**Comment by mohitg0795** [comment]
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 231 at r3](https://reviewable.io/reviews/harness/harness-core/36929#-NAp7Ir4DKz1AP-rXa2d:-NAp7Ir50iEjIRL-9tvb:b-mqipw1) ([raw file](https://github.com/harness/harness-core/blob/cef4a15fc260da0f293c11b4be0615bbf66fff1a/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L231)):*
> ```Java
> 
>   private boolean cfFeatureFlagEvaluation(@NonNull FeatureName featureName, String accountId) {
>     String name;
> ```

what does name represent here? Can we rename it to something better? From what I understand, its accountName, so lets name it "accountName" itself.

**Comment by mohitg0795** [comment]
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 252 at r3](https://reviewable.io/reviews/harness/harness-core/36929#-NAp8GXG1qPKSh4cAjUF:-NAp8GXG1qPKSh4cAjUG:bhgvm) ([raw file](https://github.com/harness/harness-core/blob/cef4a15fc260da0f293c11b4be0615bbf66fff1a/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L252)):*
> ```Java
>         if (optionalAccountClient.isPresent()) {
>           // Use account client
>           AccountDTO accountDTO = RestClientUtils.getResponse(optionalAccountClient.get().getAccountDTO(accountId));
> ```

what if there's a connection error during this REST call? Are we handling it the expected way?



_Code quote:_
```Java
RestClientUtils.getResponse
```

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36929)* status: 15 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 231 at r3](https://reviewable.io/reviews/harness/harness-core/36929#-NAp7Ir4DKz1AP-rXa2d:-NAtzVZqBxIfbIB4NX0I:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/cef4a15fc260da0f293c11b4be0615bbf66fff1a/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L231)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what does name represent here? Can we rename it to something better? From what I understand, its accountName, so lets name it "accountName" itself.
</blockquote></details>

Done
___
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 240 at r3](https://reviewable.io/reviews/harness/harness-core/36929#-NAp6x8vEogWI9TAplWc:-NAtzXsO7J-vQaLQp_ak:b-r2qgng) ([raw file](https://github.com/harness/harness-core/blob/cef4a15fc260da0f293c11b4be0615bbf66fff1a/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L240)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Shouldn't this be inside the isEmpty() check? If yes, I think we have missed a UT to ensure it, lets add that also.
</blockquote></details>

This was more for logging. 
This function was doing too many things, have broken it into pieces now.
___
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 252 at r3](https://reviewable.io/reviews/harness/harness-core/36929#-NAp8GXG1qPKSh4cAjUF:-NAtzhPF8eIml85FzgNk:b-u4zrzy) ([raw file](https://github.com/harness/harness-core/blob/cef4a15fc260da0f293c11b4be0615bbf66fff1a/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L252)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if there's a connection error during this REST call? Are we handling it the expected way?
</blockquote></details>

Addressed, by having failsafe way of retrying. Also, added default value to use, as last means.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36929)* status: Some of the checks are too old. 15 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/36929#-NBBEp2i1H8M0v7oTNzh:-NBBEp2j2SEE1QR89oUK:b8k2p58) ([raw file](https://github.com/harness/harness-core/blob/e0112fdf4eb5f8b8b984c57875209acd49ede094/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L82)):*
> ```Java
>   // Caffeine cache
>   private final Cache<String, String> accountIdToAccountNameCache =
>       Caffeine.newBuilder().initialCapacity(10).maximumSize(200).expireAfterWrite(1, TimeUnit.HOURS).build();
> ```

Shouldn't the maximum size be on higher side? Why have we chosen 200 as max size?
___
*[`940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java` line 86 at r4](https://reviewable.io/reviews/harness/harness-core/36929#-NBBEMtn0n8CQE34CqhY:-NBBEMtn0n8CQE34CqhZ:bpj6cj7) ([raw file](https://github.com/harness/harness-core/blob/e0112fdf4eb5f8b8b984c57875209acd49ede094/940-feature-flag/src/main/java/io/harness/ff/FeatureFlagServiceImpl.java#L86)):*
> ```Java
>   private static final RetryPolicy<Object> fetchAccountNameRetryPolicy =
>       RetryUtils.getRetryPolicy("Failed attempt: Could not fetch account name", "Failure: Could not fetch account name",
>           Lists.newArrayList(InvalidRequestException.class), Duration.ofSeconds(5), 3, log);
> ```

What is the reason to introduce a delay of 5 sec between attempts? Also what is the reason to introduce retry? This can potentially increase the time of FF evaluation drastically.

**Pull request closed without merging**
