### PR TITLE
feat: [CDS-84032]: Return 4xx when OPA validation fails for pipeline

### PR DESCRIPTION
**Pull request by meenaravichandran1**
## Describe your changes
Current behavior is that when a pipeline creation/updation fails with OPA validation failures, status 200 is returned, in other words, when the deny field is true from OPA.
This change is to make the response return 4xx.

This flow is being called in a few other places, no impact on the existing flows so far. PipelineEntityGitSyncHelper - this is yet to be tested. Will update it here once I do.

Also, v1 APIs looks to be deprecated, so I’m not touching that. And made this change for clonePipeline as well.

Update:
Checked with @mohitg0795,  the file PipelineEntityGitSyncHelper is used for old git sync only and can be ignored.

## Response

> {
    "status": "ERROR",
    "code": "POLICY_EVALUATION_FAILURE",
    "message": "Pipeline does not follow the Policies in these Policy Sets: [new_policy_set_12_11_18_35]",
    "correlationId": "5612eb63-b8fd-4d4f-ac6d-8d17418f8838",
    "detailedMessage": null,
    "responseMessages": [
        {
            "code": "POLICY_EVALUATION_FAILURE",
            "level": "ERROR",
            "message": "Pipeline does not follow the Policies in these Policy Sets: [new_policy_set_12_11_18_35]",
            "exception": null,
            "failureTypes": []
        }
    ],
    "metadata": {
        "type": "GovernanceMetadataErrorDTO",
        "governanceMetadata": {
            "id": "44",
            "deny": true,
            "details": [
                {
                    "policySetId": "",
                    "deny": true,
                    "policyMetadata": [
                        {
                            "policyId": "",
                            "policyName": "CustomStageApprovalSave",
                            "severity": "error",
                            "denyMessages": [
                                "Custom stage \u0027f\u0027 does not have a HarnessApproval step"
                            ],
                            "status": "error",
                            "identifier": "new_policy_12_11_18_35",
                            "accountId": "kmpySmUISimoRrJL6NL73w",
                            "orgId": "default",
                            "projectId": "meenalocal",
                            "created": "1702337719603",
                            "updated": "1702337735780",
                            "error": ""
                        },
                        {
                            "policyId": "",
                            "policyName": "dummy",
                            "severity": "warning",
                            "denyMessages": [
                                "custom stage \u0027f\u0027 is missing required step \u0027Http\u0027"
                            ],
                            "status": "warning",
                            "identifier": "dummy",
                            "accountId": "kmpySmUISimoRrJL6NL73w",
                            "orgId": "default",
                            "projectId": "meenalocal",
                            "created": "1702340968910",
                            "updated": "1702341138754",
                            "error": ""
                        }
                    ],
                    "policySetName": "New Policy Set - 12/11 - 18:35",
                    "status": "error",
                    "identifier": "new_policy_set_12_11_18_35",
                    "created": "1702337719615",
                    "accountId": "kmpySmUISimoRrJL6NL73w",
                    "orgId": "default",
                    "projectId": "meenalocal",
                    "description": ""
                }
            ],
            "message": "",
            "timestamp": "1702423699482",
            "status": "error",
            "accountId": "kmpySmUISimoRrJL6NL73w",
            "orgId": "default",
            "projectId": "meenalocal",
            "entity": "ere",
            "type": "pipeline",
            "action": "onsave",
            "created": "1702423699463"
        },
        "type": "GovernanceMetadataErrorDTO"
    }
}

## Test cases - Error code
1. Warnings on save - 200
2. Success on save - 200
3. Atleast one failure on save - 400
4. All the above for remote pipeline
5. Create a pipeline; create policy; note that the previously created pipeline doesn't obey the policy; Clone pipeline - 400

## Notes
This change is to be enabled only after UI is merged, there is no special handling for error type POLICY_EVALUATION_FAILURE yet. Currently it is behind FF CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)

### CODE REVIEW

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
This seems like a change in behaviour, should we implement new api altogether?

**Comment by meenaravichandran1** [comment]
trigger feature-build

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger ut0

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
> This seems like a change in behaviour, should we implement new api altogether?

Added a FF

**Comment by rohitk-h** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 154 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm2HoN_AH4HbtsYZ5iu:-Nm2HoN_AH4HbtsYZ5iv:b-ebfive) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L154)):*
> ```Java
>     PipelineCRUDResult pipelineCRUDResult;
>     if (featureFlagService.isGlobalEnabled(FeatureName.CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE)) {
>       pipelineCRUDResult = pmsPipelineService.validateAndCreatePipeline(pipelineEntity, true);
> ```

@sahilhindwani-harness what is the reason for having this boolean variable for policyValidations, I see the only difference is that downstream we call `validateYamlAndGovernanceRules` or `validateYamlAndGetGovernanceMetadata` where the later throws an exception but former doesn't. What is the use case where we do not want to throw this exception?

**Review by rohitk-h — APPROVED** [review]
> Reviewed 10 of 15 files at r2, 1 of 6 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
Verified all new code is wrapped behind FF

**Comment by meenaravichandran1** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 154 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm2HoN_AH4HbtsYZ5iu:-Nm2HoN_AH4HbtsYZ5iv:b-ebfive) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L154)):_
> 
> > ```java
> >     PipelineCRUDResult pipelineCRUDResult;
> >     if (featureFlagService.isGlobalEnabled(FeatureName.CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE)) {
> >       pipelineCRUDResult = pmsPipelineService.validateAndCreatePipeline(pipelineEntity, true);
> > ```
> 
> @sahilhindwani-harness what is the reason for having this boolean variable for policyValidations, I see the only difference is that downstream we call `validateYamlAndGovernanceRules` or `validateYamlAndGetGovernanceMetadata` where the later throws an exception but former doesn't. What is the use case where we do not want to throw this exception?

One thing I noticed was that all V1 APIs threw an exception whereas V2 APIs didn't throw an exception but returned 200 with all the error data when policy eval failed. And subsequently, the caller was returning when the policy evaluation failed.
example: https://github.com/harness/harness-core/blob/develop/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L209

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 154 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm2HoN_AH4HbtsYZ5iu:-Nm4_YJu0ry2p0oOQIxc:b6ck8xh) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L154)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

Not sure if it's relevant, but one thing I noticed was that all V1 APIs threw an exception whereas V2 APIs didn't throw an exception but returned 200 with all the error data when policy eval failed. And subsequently, the caller was returning when the policy evaluation failed.
example: https://github.com/harness/harness-core/blob/develop/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L209

</blockquote></details>

@rohitk-h , we don't want to throw the exception I think because of the information we want to show in the UI. We are able to save the pipeline even when governance rule fails, giving an exception would mean that the create did not happen therefore we are passing this boolean so that we know whether to throw the exception or just return the response.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 381 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm4_rrB0Q-JpeUoaWc-:-Nm4_rrCDJKEfE4w9jgk:bner1j) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L381)):*
> ```Java
> 
>     PipelineCRUDResult pipelineCRUDResult;
>     if (featureFlagService.isGlobalEnabled(FeatureName.CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE)) {
> ```

Why are we checking for GlobalEnabled? What if we want to disable this FF for one single account because of any reason?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java` line 87 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm4a-_e7lUgQXrYfrlv:-Nm4a-_e7lUgQXrYfrlw:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service/PipelineGovernanceServiceImpl.java#L87)):*
> ```Java
>                                              .map(PolicySetMetadata::getIdentifier)
>                                              .collect(Collectors.toList());
>       if (featureFlagService.isGlobalEnabled(FeatureName.CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE)) {
> ```

same as above

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 15 files at r2, 1 of 6 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by meenaravichandran1** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 381 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm4_rrB0Q-JpeUoaWc-:-Nm4_rrCDJKEfE4w9jgk:bner1j) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L381)):_
> 
> > ```java
> >     PipelineCRUDResult pipelineCRUDResult;
> >     if (featureFlagService.isGlobalEnabled(FeatureName.CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE)) {
> > ```
> 
> Why are we checking for GlobalEnabled? What if we want to disable this FF for one single account because of any reason?

The intent is to have the changes behind FF only until UI is merged. After UI is merged, we'll be cleaning this up. So, we don't need to check it at accountlevel.

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 381 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm4_rrB0Q-JpeUoaWc-:-NmEliDw-F3UREx2i1TZ:b-unrs0x) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L381)):*
<details><summary><i>Previously, meenaravichandran1 (Meena Ravichandran) wrote…</i></summary><blockquote>

The intent is to have the changes behind FF only until UI is merged. After UI is merged, we'll be cleaning this up. So, we don't need to check it at accountlevel.
</blockquote></details>

I would say to add still at account level because I think we have account level handy. Let us say we break something and we quickly need to unblock that account or there is a particular account who is impacted but would require some time to make the changes then we can disable for them.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 307 at r9](https://reviewable.io/reviews/harness/harness-core/56683#-NmEmEiRD8W7C4tmHfCq:-NmEmEiRD8W7C4tmHfCr:b26wdol) ([raw file](https://github.com/harness/harness-core/blob/eea44bfeee3503af7b95a26ce79a77b38669af08/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L307)):*
> ```Java
>     PipelineCRUDResult pipelineCRUDResult;
>     if (featureFlagService.isGlobalEnabled(FeatureName.CDS_SAVE_PIPELINE_OPA_RESPONSE_CODE_CHANGE)) {
>       pipelineCRUDResult = validateAndCreatePipeline(destPipelineEntity, true);
> ```

nit: why do we need if here, why not just pass the FF here?
validateAndCreatePipeline(featureFlagService.isEnabled....

**Comment by meenaravichandran1** [comment]
trigger uts

**Comment by meenaravichandran1** [comment]
trigger featurenamecheck, messagecheck, compile, codebasehash, pmd, checkstylecodeformat

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 381 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm4_rrB0Q-JpeUoaWc-:-NmZnvJz7ou3SUjViwgx:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L381)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

I would say to add still at account level because I think we have account level handy. Let us say we break something and we quickly need to unblock that account or there is a particular account who is impacted but would require some time to make the changes then we can disable for them.
</blockquote></details>

Done

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — DISMISSED** [review]
> Reviewed 1 of 3 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)* status: Some of the checks are too old. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java` line 154 at r8](https://reviewable.io/reviews/harness/harness-core/56683#-Nm2HoN_AH4HbtsYZ5iu:-Nmi8f8o4Wlg65MNJT9-:b-ygj73o) ([raw file](https://github.com/harness/harness-core/blob/3ec2bae1e70c242b05e41f9b1a123b7f5129057d/pipeline-service/service/src/main/java/io/harness/pms/pipeline/PipelineResourceImpl.java#L154)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@rohitk-h , we don't want to throw the exception I think because of the information we want to show in the UI. We are able to save the pipeline even when governance rule fails, giving an exception would mean that the create did not happen therefore we are passing this boolean so that we know whether to throw the exception or just return the response.
</blockquote></details>

For `warn and continue` policy evalutaions we don't allow creation but for `error and exit` we block creation.

**Comment by meenaravichandran1** [comment]
trigger featurenamecheck, messagecheck, compile, codebasehash, pmd, checkstylecodeformat, uts

**Comment by meenaravichandran1** [comment]
trigger featurenamecheck, messagecheck, compile, codebasehash, pmd, checkstylecodeformat, uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 3 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56683)* status: <span>:shipit:</span> complete! ✓

**Comment by rohitk-h** [comment]
trigger review

**Pull request merged**
