### PR TITLE
[fix]: [PL-00000]: update CG LDAP group sync logic if FF enabled or not

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
Restrict CG LDAP sync to not trigger when FF `PL_RESTRICT_CG_LDAP_SYNC_ON_GROUP_LINK` is turned ON. The downside of this change is for customer's whose FF is turned ON, they will only see the users being populated in User group in the next regular sync cycle (and not immediately). So this do involve an intimation to customer of this behaviour.

Testing Done:
- Tested in Local. When FF is ON (true), the LDAP sync doesn't get triggered.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53089)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 1067 at r1](https://reviewable.io/reviews/harness/harness-core/53089#-Netnjax-V7GUcS55MAx:-Netnjax-V7GUcS55MAy:b1wdr6g) ([raw file](https://github.com/harness/harness-core/blob/ffa393882dfd8dc459f1ab2cde30caf900b90505/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L1067)):*
> ```Java
> 
>     if (ssoType == SSOType.LDAP
>         && !featureFlagService.isEnabled(FeatureName.PL_RESTRICT_CG_LDAP_SYNC_ON_GROUP_LINK, accountId)) {
> ```

can we not just call individual group sync code from here in a async manner?

**Comment by piyush-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 1067 at r1](https://reviewable.io/reviews/harness/harness-core/53089#-Netnjax-V7GUcS55MAx:-NetnrKH14Ygu51V2a8G:b-lgaqel) ([raw file](https://github.com/harness/harness-core/blob/ffa393882dfd8dc459f1ab2cde30caf900b90505/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L1067)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

can we not just call individual group sync code from here in a async manner?
</blockquote></details>

Also this FF looks like a permanent one why not just make changes directly?

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53089)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
Closing this PR as we are going ahead with approach to sync only the linked group https://github.com/harness/harness-core/pull/53515

**Pull request closed without merging**
