### PR TITLE
techdebt: [PL-21980]: upgrade java mongo driver, [CCM-7955]: upgrade minidev_json-smart, [PL-21199]: upgrade jetty libraries

### PR DESCRIPTION
**Pull request by shivagowda**
## Describe your changes

with mongo driver upgrade, the springframework started throwing DataIntegrityViolationException instead of DuplicateKeyException
with the same error message. DataIntegrityViolationException is baseclass of DuplicateKeyException
So, replaced it.
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

PR build: https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/OpenJDKPortalWithPatch/executions/pRSLUx1WR6iVDbIeZHiTFw/artifacts?stage=nWRCgeWBTaWO-67auqhQSQ

PR deployment:
https://app.harness.io/#/account/wFHXHD0RRQWoO8tIZT5YVw/app/-jRbnwPZRoOLj2NEhrbJnQ/pipeline-execution/nythFEw5T3u3NnlgowmleQ/workflow-execution/gSdDgfBETF6se3jTyVAbCw/details

Automation test in PR:
https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/QE_Team/projects/Quality_Assurence/pipelines/QE_Automation_CI_Api_Suite_PR/executions/X9kiO-_cQxO-wlw9-_i9ww/pipeline

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34438)

### CODE REVIEW

**Comment by shivagowda** [comment]
trigger messagecheck

**Review by reetika04 — APPROVED** [review]
> Reviewed 81 of 81 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34438)* status: 81 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 17 of 81 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34438#-:-N4zk6-05wnMe4x6A_Bv:bnfp4nl)* status: 64 file(s) to review.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/34438)

**Pull request closed without merging**
