### PR TITLE
fix: [CDS-41819]: PDC connector host capability check is always check…

### PR DESCRIPTION
**Pull request by bojanmicovic**
…ed with default port 22

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36468)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36468)

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36468)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java` line 133 at r1](https://reviewable.io/reviews/harness/harness-core/36468#-N9flDta7SOliyTe79Go:-N9flDtb9MxXMcVhxDEU:bojwf7i) ([raw file](https://github.com/harness/harness-core/blob/e9bcca3cc89dc990387cd099351ea37a0314d81b/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/utils/CommandStepUtils.java#L133)):*
> ```Java
>     String host = ParameterFieldHelper.getParameterFieldValue(commandStepParameters.getHost());
>     return PhysicalDataCenterUtils.extractHostnameFromHost(host).orElseThrow(
>         () -> new InvalidArgumentsException(format("Not found hostName, host: %s", host)));
> ```

can we rephrase the error message to something. like: `Failed to resolve hostname: %s`

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36468)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36468)* status: :shipit: complete! ✓

**Pull request merged**
