### PR TITLE
fix: [DEL-3913]: add TTL to delegate group entity

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes

1. Have delegateGroup validUntil so that entity can be auto-deleted from mongo.
2. Update validity when delegate heartbeats.

Tests done:
1. Installed k8s cg legacy delegate.
2. Installed k8s cg immutable delegate.
3. Installed k8s ng legacy delegate.
4. Installed k8s ng immutable delegate.
5. First deployed a latest manager and installed k8s cg immutable delegate and then upgraded manager to my version.

Everything was working fine as expected.
Delegate group validity: (19-Dec + 7 days)
Screenshot 2022-12-21 at 12 39 27 PM

Delegate validtiy:

Screenshot 2022-12-21 at 12 39 52 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/41737#-NJdoHGTAv7bShezBs2A:-NJdoHGTAv7bShezBs2B:b9fck1u) ([raw file](https://github.com/harness/harness-core/blob/6b1288ead01b64cd3f9b32d02a142c4a00e41546/390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java#L62)):*
> ```Java
> import io.harness.migrations.all.AddRingsToAccountMigration;
> import io.harness.migrations.all.AddStateMachineToWorkflowExecutions;
> import io.harness.migrations.all.AddValidUntilToDelegateGroupMigration;
> ```

Do we need migration ? since subsequent heartbeat from delegate will insert it anyway.



_Code quote:_
```Java
AddValidUntilToDelegateGroupMigration;
```

**Review by arpit3107 — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Review by xingchi-jin — CHANGES_REQUESTED** [review]
Thank you for the work ! 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737#-:-NJfa0LwE_BDtzOWWz_J:b-kqg5v8)* status: 7 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJf_hb68I0eaft_749j:-NJf_hb68I0eaft_749k:b910uv8) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L66)):*
> ```Java
>     delegateTaskService.touchExecutingTasks(existingDelegate.getAccountId(), existingDelegate.getUuid(),
>         existingDelegate.getCurrentlyExecutingDelegateTasks());
>     if (existingDelegate.getDelegateGroupId() != null) {
> ```

i m not a big fan of this way of updating group, because one delegate group contains multiple delegates.
But also aware that we don't have actual delegate group lifecycle built in our system.
pl. add a FIXME to document this caveat in a comment
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJf_A3BA0m--bDYNpsI:-NJf_A3BA0m--bDYNpsJ:b-7esaw1) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java#L49)):*
> ```Java
> @OwnedBy(HarnessTeam.DEL)
> public class DelegateGroup implements PersistentEntity, UuidAware {
>   public static final Duration TTL = ofDays(7);
> ```

where does the delete of the delegate group happen? 
i guess it needs an TTL index to be created.

**Comment by raghuAtWings** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddValidUntilToDelegateGroupMigration.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJguiK2Af1TP5XM1jan:-NJguiK2Af1TP5XM1jao:bncviqs) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/390-db-migration/src/main/java/io/harness/migrations/all/AddValidUntilToDelegateGroupMigration.java#L35)):*
> ```Java
>       Query<DelegateGroup> delegateGroupQuery = persistence.createQuery(DelegateGroup.class, excludeAuthority)
>                                                     .field(DelegateGroupKeys.validUntil)
>                                                     .doesNotExist();
> ```

whats the current value of it? do we not need to update that as well?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2824 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJgv0WO492tuTxbZmeg:-NJgv0WO492tuTxbZmeh:b-na1m99) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2824)):*
> ```Java
>         updateDelegateWithConfigFromGroup(delegate);
>       }
>       delegateSetupService.updateDelegateGroupValidity(delegate.getAccountId(), delegate.getDelegateGroupId());
> ```

for cd delegate with groupId both of the steps will be executed, is it intentional?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 2 change requests. 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 1 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddValidUntilToDelegateGroupMigration.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJguiK2Af1TP5XM1jan:-NJi-7rX79HriQWJisVk:bysj5mj) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/390-db-migration/src/main/java/io/harness/migrations/all/AddValidUntilToDelegateGroupMigration.java#L35)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

whats the current value of it? do we not need to update that as well?
</blockquote></details>

8k delegateGroups are there. And all of them dont have validUntil field. We need to update inactive delegateGroups also. Those which dont have any active delegates and are polluting the UI.
___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 66 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJf_hb68I0eaft_749j:-NJi-kQTANupdRnB9uij:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L66)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

i m not a big fan of this way of updating group, because one delegate group contains multiple delegates.
But also aware that we don't have actual delegate group lifecycle built in our system.
pl. add a FIXME to document this caveat in a comment
</blockquote></details>

Done
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2824 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJgv0WO492tuTxbZmeg:-NJi0-7SAXfGyVFArFxx:b8vdzlh) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2824)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

for cd delegate with groupId both of the steps will be executed, is it intentional?
</blockquote></details>

Yes, just modified the existing if-else to include this condition also
___
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/41737#-NJf_A3BA0m--bDYNpsI:-NJi0BAL-nt6e8EJfqIS:b-du35ix) ([raw file](https://github.com/harness/harness-core/blob/0ea720ae5e4eb07d3102583f4b095894c63e6134/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateGroup.java#L49)):*
<details><summary><i>Previously, xingchi-jin (Xingchi Jin) wrote…</i></summary><blockquote>

where does the delete of the delegate group happen? 
i guess it needs an TTL index to be created. 
</blockquote></details>

validUntil was already there. Just that no-one was updating that.



_Code quote:_
```Java
@FdTtlIndex private Date validUntil;
```

**Review by xingchi-jin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 3. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: 1. unresolved discussions.

**Comment by arpit3107** [comment]
trigger pmd

**Review by xingchi-jin — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: :shipit: complete! ✓

**Review by AnupamIO — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41737)* status: :shipit: complete! ✓

**Pull request merged**
