### PR TITLE
[fix]: [CDS-24447]: terminate powershell processes

### PR DESCRIPTION
**Pull request by prabu-kr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32192)

### CODE REVIEW

**Comment by prabu-kr** [comment]
trigger portal_build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger feature-build

**Comment by prabu-kr** [comment]
trigger messagecheck

**Review by inderschera — DISMISSED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32192)* status: :shipit: complete! ✓

___
*[`960-api-services/src/main/java/io/harness/shell/ChildProcessStopper.java` line 65 at r6](https://reviewable.io/reviews/harness/harness-core/32192#-N1nRH55EEs0ADn2uthu:-N1nRH55EEs0ADn2uthv:br2dyjn) ([raw file](https://github.com/harness/harness-core/blob/2665d63202e58ac7cc13605cb6e7f6e2cd0d718c/960-api-services/src/main/java/io/harness/shell/ChildProcessStopper.java#L65)):*
> ```Java
>       log.error("Exception in script execution ", e);
>     }
>     process.destroy();
> ```

Just confirm that since process is already destroyed, will calling this cause any issue? Else, we should remove this.

**Comment by prabu-kr** [comment]
trigger unit-tests

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32192)* status: 1. unresolved discussions. 

___
*[`960-api-services/src/main/java/io/harness/shell/ChildProcessStopper.java` line 65 at r6](https://reviewable.io/reviews/harness/harness-core/32192#-N1nRH55EEs0ADn2uthu:-N1oF1es5cDJQgWNsQSi:bnjnqr4) ([raw file](https://github.com/harness/harness-core/blob/2665d63202e58ac7cc13605cb6e7f6e2cd0d718c/960-api-services/src/main/java/io/harness/shell/ChildProcessStopper.java#L65)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Just confirm that since process is already destroyed, will calling this cause any issue? Else, we should remove this.
</blockquote></details>

I checked the implementation of destroy, we are checking if it has exited before destroying. So we should be good. It didn't cause any problem in local and pr testing either. I just included the line since it was present in default implementation too



_Code snippet:_
```Java
synchronized (this) {
                    if (!hasExited)
                        destroyProcess(pid, force);
                }
```

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32192)* status: :shipit: complete! ✓

**Pull request merged**
