### PR TITLE
fix: [DEL-3784]: Set proper default tool paths

### PR DESCRIPTION
**Pull request by mdmilic**
This PR doesn't fix all the tools for immutable delegate but was the smallest change possible to unblock current customers who are working with kubectl, go-templates, kustomize etc... 
More significant changes are needed to fix CF, chartmuseum & helm. Also, with this PR paths are set even for images that don't have any client tools, but this should not break them. Those delegate should still not be capable of running e.g. kubectl tasks.
Immutable delegates don't have (easy) option to set custom tool paths yet. 

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32271)

### CODE REVIEW

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32271)* status: :shipit: complete! ✓

**Comment by mdmilic** [comment]
trigger publish-delegate

**Comment by mdmilic** [comment]
trigger publish delegate

**Comment by mdmilic** [comment]
trigger publish-delegate

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32271)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32271)* status: :shipit: complete! ✓

**Pull request merged**
