### PR TITLE
[feat]:[pl-27462]: Use parentConnectorRef and parentRepoName

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Use parentConnectorRef and parentRepoName to resolve parentEntityRepoURL, have tested out the following:
 1. getTemplate with and without the parentConnectorRef and parentRepoName
 2. v2/applyTemplates with and without the parentConnectorRef and parentRepoName

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* Code issue 1 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36466)

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hSgA32L8QfYRj7IJV:-N9hSgA32L8QfYRj7IJW:bhu1ifd) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L32)):*
> ```Java
>   }
> 
>   public String getRepoUrl(Scope scope) {
> ```

this should be private?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hSolv6XpLCk8vG7ob:-N9hSolv6XpLCk8vG7oc:bj598yp) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L26)):*
> ```Java
>     String branchName = gitEntityInfo.getBranch();
>     String parentEntityRepoUrl = getRepoUrl(scope);
>     if (!GitAwareContextHelper.isNullOrDefault(parentEntityRepoUrl) && !parentEntityRepoUrl.equals(entityRepoURL)) {
> ```

why are we checking context again here?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTJdz3BKT2dzeXo2f:-N9hTJdz3BKT2dzeXo2g:b-ijvb6y) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L39)):*
> ```Java
>     String parentEntityRepoUrl;
>     if (GitAwareContextHelper.isNullOrDefault(gitEntityInfo.getParentEntityRepoName())
>         && GitAwareContextHelper.isNullOrDefault(gitEntityInfo.getParentEntityConnectorRef())) {
> ```

Can we create a logical method combining this check? Currently, it just appears to be a random check and difficult to understand what does it represent

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTXhJ8eyMJI2A26DW:-N9hTXhJ8eyMJI2A26DX:bm5y60d) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L53)):*
> ```Java
>   }
> 
>   private void setupGitContext(GitEntityInfo branchInfo) {
> ```

isn't such a method available in GitAwareContextHelper? Also, if not, then we should add this method to that class, what do you think?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTvoY4vEHq6f9vcLz:-N9hTvoZDH5JnmpQScPI:b-l77lsu) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L48)):*
> ```Java
> 
>       gitEntityInfo.setParentEntityRepoUrl(parentEntityRepoUrl);
>       setupGitContext(gitEntityInfo);
> ```

method name seems inappropriate

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: 12 file(s) to review. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/36466#-N9jarQ9C4xMis12b7wR:-N9jarQA26Wn-qZ5HJ6Z:b-59zlk9) ([raw file](https://github.com/harness/harness-core/blob/310285fb31ee75ce40fa7c5d7db72e4f60a63f82/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L44)):*
> ```Java
> 
>       gitEntityInfo.setParentEntityRepoUrl(parentEntityRepoUrl);
>       GitAwareContextHelper.setupGitEntityContext(gitEntityInfo);
> ```

I am not able to find any method in GitAwareContextHelper with this, can you point to method implementation.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: 12 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 26 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hSolv6XpLCk8vG7ob:-N9jEl5Z-J_8oti1SDDl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L26)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we checking context again here?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hSgA32L8QfYRj7IJV:-N9jDa9p-8ihE0L8ZRyB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L32)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this should be private?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTJdz3BKT2dzeXo2f:-N9jDd-K6-0Y1eMVLg7i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L39)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we create a logical method combining this check? Currently, it just appears to be a random check and difficult to understand what does it represent
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTvoY4vEHq6f9vcLz:-N9jF2VM3JnhBXeVvuuW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

method name seems inappropriate
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTXhJ8eyMJI2A26DW:-N9jE9lw2yB4WHV01oJr:b-ti4op1) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L53)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

isn't such a method available in GitAwareContextHelper? Also, if not, then we should add this method to that class, what do you think?
</blockquote></details>

Yes, i agree adding it in GitAwareContextHelper is better.



_Code quote:_
```Java
GlobalContextManager.upsertGlobalContextRecord
```
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/36466#-N9jarQ9C4xMis12b7wR:-N9jdqopBFlCiUSghWHb:b-f850wx) ([raw file](https://github.com/harness/harness-core/blob/310285fb31ee75ce40fa7c5d7db72e4f60a63f82/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L44)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I am not able to find any method in GitAwareContextHelper with this, can you point to method implementation.
</blockquote></details>

https://github.com/harness/harness-core/pull/36466/files#diff-2042e3772b14be17220e841cd3c64469ca0f0c2e8e56aff5021ed8dcb2f09114

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTvoY4vEHq6f9vcLz:-N9jqaxA4ZMIitonmvIX:b-ipxwyk) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L48)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why is it named "setupGit.."? It appears as if we are doing an initial setup. But rather its more of an update right?

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/36466#-N9jpIL81LGZJtT2ZZYW:-N9jpIL81LGZJtT2ZZYX:bby3yzi) ([raw file](https://github.com/harness/harness-core/blob/310285fb31ee75ce40fa7c5d7db72e4f60a63f82/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L23)):*
> ```Java
>     String branchName = gitEntityInfo.getBranch();
>     String parentEntityRepoUrl = getRepoUrl(scope);
>     if (!parentEntityRepoUrl.equals(entityRepoURL)) {
> ```

what if parentEntityRepoURL is null?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/36466#-N9hTvoY4vEHq6f9vcLz:-N9jv9xh4ZT7DL2gUafx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02e0f12006bec25bc00ce2a34dcbe75044431bcd/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is it named "setupGit.."? It appears as if we are doing an initial setup. But rather its more of an update right?
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/36466#-N9jpIL81LGZJtT2ZZYW:-N9jvAbgBEYnS4_lSowp:b-91jldh) ([raw file](https://github.com/harness/harness-core/blob/310285fb31ee75ce40fa7c5d7db72e4f60a63f82/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L23)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if parentEntityRepoURL is null?
</blockquote></details>

by the time if condition is executed, the parentEntityRepoUrl will not be null, it will either be empty string or an actual repo url
but its always good to do that, so will go ahead and it null check before that

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/36466#-N9jpIL81LGZJtT2ZZYW:-N9jxJo-3hXSmLo8TGs2:bxvijlv) ([raw file](https://github.com/harness/harness-core/blob/310285fb31ee75ce40fa7c5d7db72e4f60a63f82/840-template-service/src/main/java/io/harness/template/helpers/TemplateGitXHelper.java#L23)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

by the time if condition is executed, the parentEntityRepoUrl will not be null, it will either be empty string or an actual repo url
but its always good to do that, so will go ahead and it null check before that
</blockquote></details>

Yes, I agree with you that it won't come up, but its better to use null checks as practice wherever there's slightest of chances of it happening.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466#-:-N9jxWjs8_rJ6sCFJiRW:bnfp4nl)* status: 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: 1. unresolved discussions.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466#-:-N9kFbjs2BF0pP0tMJCe:bnfp4nl)* status: 1. unresolved discussions.

**Comment by adivishy1** [comment]
trigger codebasehash

**Review by bhavya181 — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36466)* status: :shipit: complete! ✓

**Pull request merged**
