### PR TITLE
feat: [CDS-44109]: Handle instance stats publisher for GitOps separately

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38183)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 2 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38183)

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38183)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/38183#-NDCU2-NAq7QA8r9Ruo4:-NDCU2-NAq7QA8r9Ruo5:b-5wod3h) ([raw file](https://github.com/harness/harness-core/blob/e1cec01689f56467d031c76f2677e3f50300fd7d/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L60)):*
> ```Java
>               orgInstancesMap.get(orgIdentifier).stream().collect(groupingBy(InstanceDTO::getProjectIdentifier));
>           for (String projectIdentifier : projectInstancesMap.keySet()) {
>             collectInstanceStats(dataPointList, projectInstancesMap.get(projectIdentifier));
> ```

lets have the methods return a list of <DataPoint> each, and we add the response of the methods to our `dataPointList` here.
Try to avoid modifying the parameters sent to a method, and make our methods as pure functions.



_Code quote:_
```Java
            collectInstanceStats(dataPointList, projectInstancesMap.get(projectIdentifier));
            collectInstanceStatsForGitOps(dataPointList, projectInstancesMap.get(projectIdentifier));
```
___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/38183#-NDCUTSLB9bVQZCyIEm0:-NDCUTSLB9bVQZCyIEm1:bsu72ju) ([raw file](https://github.com/harness/harness-core/blob/e1cec01689f56467d031c76f2677e3f50300fd7d/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L80)):*
> ```Java
>       eventProducer.send(Message.newBuilder()
>                              .putAllMetadata(ImmutableMap.of(
>                                  "accountId", accountId, EventsFrameworkMetadataConstants.ENTITY_TYPE, INSTANCE_STATS))
> ```

remove the magic string



_Code quote:_
```Java
"accountId"
```

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38183)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/38183#-NDCU2-NAq7QA8r9Ruo4:-NDCaQK_Ch_CkPmFPMDu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e1cec01689f56467d031c76f2677e3f50300fd7d/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L60)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

lets have the methods return a list of <DataPoint> each, and we add the response of the methods to our `dataPointList` here.
Try to avoid modifying the parameters sent to a method, and make our methods as pure functions.
</blockquote></details>

Done
___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/38183#-NDCUTSLB9bVQZCyIEm0:-NDCaOsOE2S1mfW6uauq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e1cec01689f56467d031c76f2677e3f50300fd7d/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L80)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

remove the magic string
</blockquote></details>

Done

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38183)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/38183#-NDCwTWA00fz4e7zW2AY:-NDCwTWA00fz4e7zW2AZ:b-qboowl) ([raw file](https://github.com/harness/harness-core/blob/89c95ad26736aca2dec574c9244d37e70929c3ab/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L106)):*
> ```Java
>       InstanceDTO instance = instanceList.get(0);
>       Map<String, String> data = populateInstanceData(instance, size);
>       log.info("Adding the GitOps instance record {} to the list", instance);
> ```

it'll be better to log the `data` map, rather than the instance here.
___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 128 at r3](https://reviewable.io/reviews/harness/harness-core/38183#-NDCwY5J9Oj_QrQOlgFp:-NDCwY5J9Oj_QrQOlgFq:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/89c95ad26736aca2dec574c9244d37e70929c3ab/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L128)):*
> ```Java
>       InstanceDTO instance = instanceList.get(0);
>       Map<String, String> data = populateInstanceData(instance, size);
>       log.info("Adding the instance record {} to the list", instance);
> ```

same as above.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38183)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 106 at r3](https://reviewable.io/reviews/harness/harness-core/38183#-NDCwTWA00fz4e7zW2AY:-NDCzQEL-EhMQjT56SKJ:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/89c95ad26736aca2dec574c9244d37e70929c3ab/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L106)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

it'll be better to log the `data` map, rather than the instance here.
</blockquote></details>

Done
___
*[`126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java` line 128 at r3](https://reviewable.io/reviews/harness/harness-core/38183#-NDCwY5J9Oj_QrQOlgFp:-NDCzRX9-DO_XNUq7-Wq:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/89c95ad26736aca2dec574c9244d37e70929c3ab/126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventpublisher/UsageMetricsEventPublisherImpl.java#L128)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done

**Pull request merged**
