### PR TITLE
feat: [CDS-42712]: Deployment freeze

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
… bulk migration framework

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 36 Issues 
* Code issue 25 Code issues 
* Anti-pattern 11 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37520)

**Review by inderschera — CHANGES_REQUESTED** [review]
> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJn8i7AeVteMz-BWDY:-NCJn8i7AeVteMz-BWDZ:b6vm6jx) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L97)):*
> ```Java
>     })
> @Slf4j
> public class FreezeCRUDResource {
> ```

Let's hide all the apis from customer. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJqm0B4szaZEKzpH5e:-NCJqm0B4szaZEKzpH5f:b88aoi5) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L108)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns the created Freeze Config")
>       })
>   public ResponseDTO<FreezeResponse>
> ```

nit: check if interfaces work in response dto.
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJnho8A7G1cbxvjfNh:-NCJnho8A7G1cbxvjfNi:b-syyt1f) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L136)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId,
>       @Parameter(description = "Freeze Identifier.") @PathParam("freezeIdentifier")
>       @ProjectIdentifier String freezeIdentifier, @Parameter(description = "Freeze YAML") @NotNull String freezeYaml) {
> ```

not required.



_Code quote:_
```Java
 @ProjectIdentifier
```
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJpfhc0MaP1LseFVsn:-NCJpfhc0MaP1LseFVso:bjp9zui) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L172)):*
> ```Java
>         ApiResponse(responseCode = "default", description = "Returns the created Freeze Config")
>       })
>   public ResponseDTO<String>
> ```

nit: check if we should send boolean or void response.
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJpOTQ0RaURB5yJRne:-NCJpOTQ0RaURB5yJRnf:bu8vcgl) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L201)):*
> ```Java
>       @Parameter(description = NGCommonEntityConstants.PROJECT_PARAM_MESSAGE) @QueryParam(
>           NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId,
>       @Parameter(description = "Comma seperated List of Freeze Identifiers") String freezeIdentifiers) {
> ```

let's have it as list of freezeIdentifiers.
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJq7m3B5AUPpy09GAl:-NCJq7m3B5AUPpy09GAm:bspv0o6) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L208)):*
> ```Java
>   @GET
>   @Path("{freezeIdentifier}")
>   @ApiOperation(value = "Creates a Freeze", nickname = "createFreeze")
> ```

nit: change description
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJrC8y2Hf6n_-z3djO:-NCJrC8y2Hf6n_-z3djP:bvj1vwg) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L253)):*
> ```Java
>               "Specifies the sorting criteria of the list. Like sorting based on the last updated entity, alphabetical sorting in an ascending or descending order")
>       @QueryParam("sort") List<String> sort,
>       @QueryParam("type") FreezeType type, @QueryParam("status") FreezeStatus freezeStatus) {
> ```

nit: maybe have most of these query params as request body.
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJwZst6YLRYPXRKiwm:-NCJwZst6YLRYPXRKiwn:bcr7j5i) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java#L14)):*
> ```Java
> import lombok.Data;
> 
> @Data
> ```

nit: we need oneOf here for tags, expression and entityReference
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJwkly3-BLS5kPIuB4:-NCJwkly3-BLS5kPIuB5:b-ig5t30) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java#L16)):*
> ```Java
> @Data
> public class EntityConfig {
>   @JsonProperty("type") FreezeEntityType freezeEntityType;
> ```

nit: should be @notnull
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJwo75DzZm3k80bE_T:-NCJwo75DzZm3k80bE_U:b-ig5t30) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java#L24)):*
> ```Java
>   String expression;
> 
>   FilterType filterType;
> ```

nit: should be @notnull
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntity.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJxPpCC4jUsrzECllx:-NCJxPpD34wBmI1W1TeC:b-ssn2zd) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntity.java#L14)):*
> ```Java
> 
> @Data
> public class FreezeEntity {
> ```

nit: looks redundant
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityReference.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJxSlTEc-q2LB3NOHU:-NCJxSlTEc-q2LB3NOHV:b-ssn2zd) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityReference.java#L14)):*
> ```Java
> 
> @Data
> public class FreezeEntityReference {
> ```

nit: looks redundant
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityRule.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJxnzUAv6jjAR75t_b:-NCJxnzUAv6jjAR75t_c:b-e83vxn) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityRule.java#L16)):*
> ```Java
> @Data
> public class FreezeEntityRule {
>   @JsonProperty("entityConfig") List<EntityConfig> entityConfigList;
> ```

nit: should it be @notnull
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseDTO.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK-YHf1-IdnWI6H_8_:-NCK-YHf1-IdnWI6H_8a:bzgol5) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseDTO.java#L54)):*
> ```Java
> 
>   @With @NotEmpty @EntityIdentifier String identifier;
>   @NotEmpty String yaml;
> ```

nitL should we remove @notempty for global freeze configs
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK0B_t7JyjZ8TeCs6K:-NCK0B_t7JyjZ8TeCs6L:b-ihfjh7) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java#L17)):*
> ```Java
> @Builder
> public class FreezeResponseWrapperDTO implements FreezeResponse {
>   int success;
> ```

nit: should we change to numOfSuccess?
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK02-v1pGkp4dbnd-f:-NCK02-w-WA4ll5IB-EV:b-c97cp7) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java#L25)):*
> ```Java
>   List<FreezeErrorResponseDTO> freezeErrorResponseDTOList;
> 
>   String errorMessage;
> ```

nit: not required, ui can combine error messages from freezeErrorResponse
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK0ziC0qGTldJcWItB:-NCK0ziC0qGTldJcWItC:b-q3f4rw) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java#L42)):*
> ```Java
> 
>   String orgIdentifier;
>   String projectIdentifier;
> ```

nit: check if we can remove such metadata from yaml.
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK1AzrC9zJxK9lfoQT:-NCK1AzrC9zJxK9lfoQU:b-liwsjk) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java#L50)):*
> ```Java
>   @JsonProperty("entityConfigs") List<FreezeEntityRule> rules;
> 
>   FreezeNotifications notifications;
> ```

nit: Add @jsonIgnore for now
___
*[`125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK1L5l5g7Wj3pwS8EN:-NCK1L5l5g7Wj3pwS8EO:b-ta1cyf) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java#L82)):*
> ```Java
> 
>   @NotEmpty @EntityIdentifier String identifier;
>   @NotEmpty String yaml;
> ```

nit: check if we can keep it empty for global configs..
___
*[`125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeCRUDServiceImpl.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK3vvl5zZ3eSNv0VAG:-NCK3vvl5zZ3eSNv0VAH:b-3n15nw) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeCRUDServiceImpl.java#L185)):*
> ```Java
>       FreezeConfig freezeConfig = NGFreezeDtoMapper.toFreezeConfig(deploymentFreezeYaml);
>       freezeConfig.getFreezeInfoConfig().setActive(freezeStatus);
>       freezeConfigEntity.setYaml(NGFreezeDtoMapper.toYaml(freezeConfig));
> ```

check if converting bean back to yaml works.
___
*[`125-freeze/src/main/proto/io/harness/freeze/freeze.proto` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK4KVZ1a6m4cr2ks0p:-NCK4KVZ1a6m4cr2ks0q:b-r1by4y) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/proto/io/harness/freeze/freeze.proto#L16)):*
> ```protobuf
>   string optype = 3;
>   int64 timestamp = 4;
> }
> ```

nit: to be removed

**Comment by abhinavmittal-harness** [comment]
tigger messageCheck

**Comment by abhinavmittal-harness** [comment]
trigger messagecheck

**Review by inderschera — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by abhinavmittal-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJqm0B4szaZEKzpH5e:-NCLj1hWCReItKv69DGK:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L108)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: check if interfaces work in response dto.
</blockquote></details>

TO be done seperately

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)* status: 1 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJn8i7AeVteMz-BWDY:-NCLjPgtBXHFLrXgl2fv:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L97)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

Let's hide all the apis from customer. 
</blockquote></details>

Done
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 136 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJnho8A7G1cbxvjfNh:-NCLj8I8CKK7VENQnvzG:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L136)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

not required.
</blockquote></details>

TO be done seperately
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 172 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJpfhc0MaP1LseFVsn:-NCLj9egEi4BZGnuzXSO:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L172)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: check if we should send boolean or void response.
</blockquote></details>

TO be done seperately
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJpOTQ0RaURB5yJRne:-NCLjACr21kOf1ZIBJuK:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L201)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

let's have it as list of freezeIdentifiers.
</blockquote></details>

TO be done seperately
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 208 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJq7m3B5AUPpy09GAl:-NCLjAjL4D0CLKpUNXbP:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L208)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: change description
</blockquote></details>

TO be done seperately
___
*[`120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java` line 253 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJrC8y2Hf6n_-z3djO:-NCLjBIWA6gcioJMSB_q:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java#L253)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: maybe have most of these query params as request body.
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJwZst6YLRYPXRKiwm:-NCLjBzN08XR0-jmWjZa:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java#L14)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: we need oneOf here for tags, expression and entityReference
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJwkly3-BLS5kPIuB4:-NCLjCRL2BjpLEszJmPA:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java#L16)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: should be @notnull
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java` line 24 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJwo75DzZm3k80bE_T:-NCLjCsh699a52JgZI6E:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/EntityConfig.java#L24)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: should be @notnull
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntity.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJxPpCC4jUsrzECllx:-NCLjDMc59LkUcEX1LMI:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntity.java#L14)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: looks redundant
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityReference.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJxSlTEc-q2LB3NOHU:-NCLjDrp3QO6fl-_r-Q3:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityReference.java#L14)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: looks redundant
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityRule.java` line 16 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCJxnzUAv6jjAR75t_b:-NCLjENl1i5myTH6RICp:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityRule.java#L16)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: should it be @notnull
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseDTO.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK-YHf1-IdnWI6H_8_:-NCLjEsCEPn0Ixs7dieC:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseDTO.java#L54)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nitL should we remove @notempty for global freeze configs
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK0B_t7JyjZ8TeCs6K:-NCLjFQp52u3lf-f3Cvq:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java#L17)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: should we change to numOfSuccess?
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK02-v1pGkp4dbnd-f:-NCLjFtG-btsNGirMeq7:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/FreezeResponseWrapperDTO.java#L25)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: not required, ui can combine error messages from freezeErrorResponse
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK0ziC0qGTldJcWItB:-NCLjGNR6gG30XEvWpTI:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java#L42)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: check if we can remove such metadata from yaml.
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK1AzrC9zJxK9lfoQT:-NCLjGtX5blcSbDwC-BR:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java#L50)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: Add @jsonIgnore for now
</blockquote></details>

TO be done seperately
___
*[`125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK1L5l5g7Wj3pwS8EN:-NCLjHL4Ax-J-OrfC8vu:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/entity/FreezeConfigEntity.java#L82)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

nit: check if we can keep it empty for global configs..
</blockquote></details>

TO be done seperately

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)* status: 1 change requests. 19. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeCRUDServiceImpl.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/37520#-NCK3vvl5zZ3eSNv0VAG:-NCLjSPCD0G-pV0AMmoo:b-lzwywb) ([raw file](https://github.com/harness/harness-core/blob/a5d18d6c29b452d8ebdd0c6e6f0754e48d7225ff/125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeCRUDServiceImpl.java#L185)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

check if converting bean back to yaml works.
</blockquote></details>

TO be done seperately

**Review by inderschera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)* status: 5. unresolved discussions.

**Review by abhinavmittal-harness — COMMENTED** [review]
> Reviewed 39 of 43 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520)* status: 5. unresolved discussions.

**Review by abhinavmittal-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37520#-:-NCLlLhvCUZ2ESPNqOO-:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
