### PR TITLE
fix: [CDS-2895]: Add unique cache file for kerberos authentication

### PR DESCRIPTION
**Pull request by abosii-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31842)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31842)* status: 11 file(s) to review. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java, line 79 at r1](https://reviewable.io/reviews/harness/harness-core/31842#-MzQO8Ug3m_3u1l_EdAB:-MzQO8Ug3m_3u1l_EdAC:bmyrebd) ([raw file](https://github.com/harness/harness-core/blob/937706e5b0ba03c6ea587fb2f2c445b75f80574e/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/WinRmSession.java#L79)):*
> ```Java
>         String cache = String.format("%s:%s", FILE_CACHE_TYPE, cacheFilePath);
>         logCallback.saveExecutionLog(String.format("Using kerberos cache: %s", cache));
>         processedEnvironmentMap.put(KERBEROS_CACHE_NAME_ENV, cache);
> ```

should we create a new map here and pass to genTGT instead of using ```processedEnvironmentMap``` to avoid any unwanted behaviour change ?

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31842)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31842)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31842#-:-MzZRs_62b8ppFfy3FRi:bnfp4nl)* status: :shipit: complete! ✓

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 8 of 11 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31842)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31842)* status: :shipit: complete! ✓

**Pull request merged**
