### PR TITLE
feat:[CDS-73838]: support for Github app authentication for cloudformation and azure

### PR DESCRIPTION
**Pull request by sourabh-awashti**
## Describe your changes

Changes are regarding adding support for Github App authentication for cloudformation and azure tasks. Changes include both manager side changes as delegate changes are already done.
Tests done:
https://docs.google.com/spreadsheets/d/1xACyF9YSLQ7bIIzIYVp17CsmynD_0ofQf4HCwlq8pBc/edit#gid=1092161727

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51159)

### CODE REVIEW

**Comment by sourabh-awashti** [comment]
trigger uts

**Comment by sourabh-awashti** [comment]
trigger ut3

**Comment by sourabh-awashti** [comment]
trigger ut5

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51159)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/51159#-NafS5rW4c71jaazbA-A:-NafS5rW4c71jaazbA-B:bq5upc3) ([raw file](https://github.com/harness/harness-core/blob/6264d72ed6b8ef0bf8ef28a3eea644e30ef22908/125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L117)):*
> ```Java
>         gitConfigAuthenticationInfoHelper.getEncryptedDataDetails(scmConnector, sshKeySpecDTO, basicNGAccessObject);
>     GitStoreDelegateConfigBuilder builder = GitStoreDelegateConfig.builder();
>     builder.gitConfigDTO(scmConnector)
> ```

let's review this logic as discussed.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/51159#-NafSQfe896f9wIBgDG-:-NafSQfe896f9wIBgDG0:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/6264d72ed6b8ef0bf8ef28a3eea644e30ef22908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L82)):*
> ```Java
>     List<EncryptedDataDetail> encryptedDataDetails =
>         gitConfigAuthenticationInfoHelper.getEncryptedDataDetails(scmConnector, sshKeySpecDTO, ngAccess);
>     return GitStoreDelegateConfig.builder()
> ```

same here
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java` line 679 at r1](https://reviewable.io/reviews/harness/harness-core/51159#-NafSak969J_GdX4_Hrj:-NafSak969J_GdX4_Hrk:bji28bi) ([raw file](https://github.com/harness/harness-core/blob/6264d72ed6b8ef0bf8ef28a3eea644e30ef22908/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L679)):*
> ```Java
>     List<EncryptedDataDetail> encryptedDataDetails =
>         gitConfigAuthenticationInfoHelper.getEncryptedDataDetails(scmConnector, sshKeySpecDTO, basicNGAccessObject);
>     return GitStoreDelegateConfig.builder()
> ```

and here

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java` line 117 at r1](https://reviewable.io/reviews/harness/harness-core/51159#-NafS5rW4c71jaazbA-A:-Naf_8MiBMhlQO0P9vJt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6264d72ed6b8ef0bf8ef28a3eea644e30ef22908/125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java#L117)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's review this logic as discussed.
</blockquote></details>

Done.

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java` line 82 at r1](https://reviewable.io/reviews/harness/harness-core/51159#-NafSQfe896f9wIBgDG-:-Naf_9u1-24MiiciiL_n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6264d72ed6b8ef0bf8ef28a3eea644e30ef22908/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java#L82)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Comment by sourabh-awashti** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java` line 679 at r1](https://reviewable.io/reviews/harness/harness-core/51159#-NafSak969J_GdX4_Hrj:-Naf_AbbBVy2PT62dxaw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6264d72ed6b8ef0bf8ef28a3eea644e30ef22908/125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java#L679)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

**Comment by sourabh-awashti** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51159)* status: 14 file(s) to review.

**Comment by sourabh-awashti** [comment]
trigger review

**Pull request merged**
