### PR TITLE
feat: [PL-23159]: Add support for snapshot batch size

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30993)

### CODE REVIEW

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Comment by gupta-utkarsh** [comment]
trigger messagecheck

**Review by mohitg0795 — COMMENTED** [review]
We had to expire some of our tokens that were used in integration tests in SCM due to security vulnerability. Thus, some tests have started to fail. Please comment those tests for now, those will be taken up and fixed soon. Ideally, we didn't expect TI to pick those tests, but for now, we can comment and move ahead.
If not commented, let me know. I will raise a PR tomorrow to comment them out for time being and get it merged. Thanks.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30993#-:-Mwhgd_F6J8EsFsWJMJd:b-4780td)* status: 3 file(s) to review. 0 of 2 approvals obtained.

**Comment by gupta-utkarsh** [comment]
More tests started failing after I commented a few of them. Will wait for this to get fixed in develop branch.

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30993)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
> More tests started failing after I commented a few of them. Will wait for this to get fixed in develop branch.

Ok, but those should be unrelated to this issue. These are independent integration tests that just fail coz token is invalid now. It doesn't hamper any other test. If you remember any other test that also failed, please do let me know. Meanwhile I will create a PR to comment them for now.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30993#-:-MwjVtnA2vn3pmzhEZb4:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
