### PR TITLE
feat: [CDS-45586]: Support environment group

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
Add support for multiservice/ multiinfra for gitops flows. With this case a gitops stage will allow users to deploy to multiple services across multiple environments or environment groups. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2xOhJDsEwnOFnMePS:-NG2xOhJDsEwnOFnMePT:b-77qdn6) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java#L148)):*
> ```Java
>       EnvClusterRefs envClusterRefs = EnvClusterRefs.builder()
>                                           .envRef(envRef)
>                                           .envName(envRef)
> ```

envName and envRef are set to same value

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2xWvqBQdBdQq9bhVj:-NG2xWvqBQdBdQq9bhVk:b-2ba09z) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java#L149)):*
> ```Java
>                                           .envRef(envRef)
>                                           .envName(envRef)
>                                           .deployToAll(clusterRefs.isEmpty())
> ```

do we have a first class field to determine this ? this looks risky determining it based on whether cluster list is empty

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2z72L6ytdMk4dTMfn:-NG2z72L6ytdMk4dTMfo:b-3pwxs8) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L115)):*
> ```Java
>   }
> 
>   @org.jetbrains.annotations.NotNull
> ```

notnull from jetbrains, is it intentional ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 236 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2zmrr1lOMiDkrYSlR:-NG2zmrr1lOMiDkrYSlS:b-ch15lv) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L236)):*
> ```Java
>       YamlField executionField = specField.getNode().getField(YAMLFieldNameConstants.EXECUTION);
>       if (executionField == null) {
>         throw new InvalidRequestException("Execution section cannot be absent in a pipeline");
> ```

we should say "cannot be absent in a deploy stage"

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2zweK4_AIkrVP0Yrc:-NG2zweK4_AIkrVP0Yrd:b-wwqm5q) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L245)):*
> ```Java
>           // GitOps flow doesn't fork on environments, so handling it in this function.
>           return buildPlanCreationResponse(ctx, planCreationResponseMap, stageNode, specField, executionField);
>         } else {
> ```

advisorsObtains can just be defined here just to avoid it being used for gitops in the future by mistake

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2zweK4_AIkrVP0Yrc:-NG3-4mGAgsdruqCoSW8:bghw21r) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L245)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

advisorsObtains can just be defined here just to avoid it being used for gitops in the future by mistake
</blockquote></details>

adviserObtainments*



_Code quote:_
```Java
adviserObtainments
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG3-ZI02Epn7_yoMLDm:-NG3-ZI02Epn7_yoMLDn:b-vla2hu) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L623)):*
> ```Java
>       YamlField executionUuid) {
>     PlanNode gitopsNode;
>     final String postServiceStepUuid = "service-" + UUIDGenerator.generateUuid();
> ```

this name is a bit confusing, we can just call it "gitopsClusters + uuid

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 286 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG3-weO1al_6wqDZRQy:-NG3-weO1al_6wqDZRQz:b7wehu) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L286)):*
> ```Java
> 
>     addCDExecutionDependencies(planCreationResponseMap, executionField);
>     addMultiDeploymentDependencyForGitOps(planCreationResponseMap, stageNode, ctx);
> ```

can we let these methods be called similarily in both flows ?
at line 264 in DeploymentStagePmsPlanCreatorV2

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 644 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG31qrp5UUUFctkXyNU:-NG31qrp5UUUFctkXyNV:b-yn5uah) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L644)):*
> ```Java
>           executionUuid, postServiceStepUuid, environmentsPlanCreatorConfig, kryoSerializer);
>     }
> ```

are we not handling single environment here ?

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: 15 file(s) to review. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java` line 148 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2xOhJDsEwnOFnMePS:-NG7s4dX1Wmi3viZDkN5:b-wjb6ye) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java#L148)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

envName and envRef are set to same value
</blockquote></details>

good catch, updated
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java` line 149 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2xWvqBQdBdQq9bhVj:-NG7XHCjAN8ZxT4lmK9J:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java#L149)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we have a first class field to determine this ? this looks risky determining it based on whether cluster list is empty
</blockquote></details>

updated
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 115 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2z72L6ytdMk4dTMfn:-NG7XJ8X9AhpUkKdmg04:bnz99tx) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L115)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

notnull from jetbrains, is it intentional ?
</blockquote></details>

unintentional , removed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 236 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2zmrr1lOMiDkrYSlR:-NG7XLkX79V53EfcAPaJ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L236)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should say "cannot be absent in a deploy stage"
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 245 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG2zweK4_AIkrVP0Yrc:-NG7XNsU7nyYsvxXq-hy:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L245)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

adviserObtainments*
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 286 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG3-weO1al_6wqDZRQy:-NG7XOoa8vFcM929Sth2:beoo7nc) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L286)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we let these methods be called similarily in both flows ?
at line 264 in DeploymentStagePmsPlanCreatorV2
</blockquote></details>

The multiDeploymentDependency is different for gitops hence they are called here, we can put them in the if block instead. I prefer keeping them in the gitops function. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 623 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG3-ZI02Epn7_yoMLDm:-NG7XPfC1aGXi6BuPnQK:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L623)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this name is a bit confusing, we can just call it "gitopsClusters + uuid
</blockquote></details>

updated

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 644 at r1](https://reviewable.io/reviews/harness/harness-core/39528#-NG31qrp5UUUFctkXyNU:-NG83zojBxgWt4efbKjX:b-v9o28y) ([raw file](https://github.com/harness/harness-core/blob/38b201234f33464af26f85b2b6e5290bea38e0a4/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L644)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

are we not handling single environment here ?
</blockquote></details>

Good catch, added support

**Comment by rohitk-h** [comment]
trigger checkstyle

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: 14 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained.

**Comment by rohitk-h** [comment]
trigger compile

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 601 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFmcNREBpw-gpok3b9:-NGFmcNREBpw-gpok3bA:bsqt93o) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L601)):*
> ```Java
>           specField, kryoSerializer, service, null, serviceNodeId, nextNodeId, deploymentType, true));
>     } else if (stageNode.deploymentStageConfig.getEnvironment() != null) {
>       planCreationResponseMap.putAll(ServiceAllInOnePlanCreatorUtils.addServiceNode(specField, kryoSerializer, service,
> ```

I think its better to create a separate function 
```ServiceAllInOnePlanCreatorUtils.addServiceNode``` that accepts an ```environments``` yaml

**Comment by yogesh-chauhan** [comment]
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFr7yB6ukZazf7iPMP:-NGFr7yB6ukZazf7iPMQ:blfyzc8) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L151)):*
> ```Java
>             RETRY_SLEEP_DURATION);
>         sleep(RETRY_SLEEP_DURATION);
>       }
> ```

is this expected ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 143 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFqw_lCfmYUtI743Dh:-NGFqw_lCfmYUtI743Di:bdthlgm) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L143)):*
> ```Java
>               && stepParameters.getEnvGroupRef().getValue() != null)
>           || (ParameterField.isNotNull(stepParameters.getGitOpsMultiSvcEnvEnabled())
>               && stepParameters.getGitOpsMultiSvcEnvEnabled().getValue())) {
> ```

should getGitopsMultiSvcEnvEnabled not always be true for this to happen ? i.e using AND instead of OR

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentsPlanCreatorHelper.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFruM6C_g4KvUHcP3E:-NGFruM6C_g4KvUHcP3F:b77moif) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentsPlanCreatorHelper.java#L52)):*
> ```Java
> 
>     List<String> envRefs =
>         environmentYamlV2s.stream().map(e -> e.getEnvironmentRef().getValue()).collect(Collectors.toList());
> ```

here if some environment ref is an expression, this might fail, IMO we should create a separate ticket for that and see if that needs to be handled

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 5 of 12 files at r1, 2 of 9 files at r2, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: 3 file(s) to review. 0 of 1 approvals obtained.

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 601 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFmcNREBpw-gpok3b9:-NGHsTlKE8WLBAl4Ro96:b79e20w) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L601)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think its better to create a separate function 
```ServiceAllInOnePlanCreatorUtils.addServiceNode``` that accepts an ```environments``` yaml
</blockquote></details>

updated to use new function, 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 143 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFqw_lCfmYUtI743Dh:-NGHsowy5qRrznVezTmh:bfzc9l2) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L143)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should getGitopsMultiSvcEnvEnabled not always be true for this to happen ? i.e using AND instead of OR
</blockquote></details>

Updated, only checking for gitops and this will be only different for envgroup/enviroments, single environments `getGitOpsMultiSvcEnvEnabled` is not set and will go though same flow. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentsPlanCreatorHelper.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFruM6C_g4KvUHcP3E:-NGHtPeY96c96ISpZ17y:b-yknpow) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentsPlanCreatorHelper.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

here if some environment ref is an expression, this might fail, IMO we should create a separate ticket for that and see if that needs to be handled
</blockquote></details>

Make sense. Ticket: https://harness.atlassian.net/browse/CDS-46064
___
*[`960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java` line 151 at r4](https://reviewable.io/reviews/harness/harness-core/39528#-NGFr7yB6ukZazf7iPMP:-NGHtRUP-g2QJxm4Gbov:bemw8yr) ([raw file](https://github.com/harness/harness-core/blob/5279595576ca9d53f40e63be61e08daf5186a052/960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java#L151)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this expected ?
</blockquote></details>

Yes, the mergePR API fails if two request for different files go at the same time for merging. 405 is `Base branch modified error so added retry logic.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 139 at r5](https://reviewable.io/reviews/harness/harness-core/39528#-NGI8ph14T97jEkhu_pM:-NGI8ph2BLJmZWYMIEiE:b-u7qnc7) ([raw file](https://github.com/harness/harness-core/blob/27c6d676d161811a44304803f6bbcdd72c00939a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L139)):*
> ```Java
>             .childrenNodeIds(childrenNodeIds)
>             .deploymentType(serviceType)
>             .gitOpsMultiSvcEnvEnabled(ParameterField.<Boolean>builder().value(true).build())
> ```

nit: you can create ParameterField.createValueField(..) method here

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 139 at r5](https://reviewable.io/reviews/harness/harness-core/39528#-NGI8ph14T97jEkhu_pM:-NGILOHj3Woz-F82_rS6:b-ciybss) ([raw file](https://github.com/harness/harness-core/blob/27c6d676d161811a44304803f6bbcdd72c00939a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L139)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: you can create ParameterField.createValueField(..) method here
</blockquote></details>

sure, will update in followup PR.

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 2 of 9 files at r2, 5 of 6 files at r4, 2 of 4 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: 5 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39528)* status: :shipit: complete! ✓

**Pull request merged**
