### PR TITLE
feat: [IDP-231]: Cron job to sync secrets periodically

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)

### CODE REVIEW

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Review by devesh-harness — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by sarthakkasat** [comment]
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/45148#-NQfO3Jj3KnqM2F8bn6B:-NQhaQEB2OJiH9mc1frj:b-rfpjbt) ([raw file](https://github.com/harness/harness-core/blob/aa680b0370b9355e1443eee445499dc933a06849/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L62)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Intentional change ?
</blockquote></details>

Backstage does not allow empty string in app-config.yaml, hence replacing it with a space

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/secret/jobs/EnvironmentSecretsSyncJob.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/45148#-NQfOgTYE9rkc-R4p9Xh:-NQi7Sef3HEef3BFzCju:btdncde) ([raw file](https://github.com/harness/harness-core/blob/aa680b0370b9355e1443eee445499dc933a06849/idp-service/src/main/java/io/harness/idp/secret/jobs/EnvironmentSecretsSyncJob.java#L32)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

Should we externalise the following to configs ?
1/ whether to run the SyncJob - boolean true or false
2/ Interval to run
</blockquote></details>

As discussed offline, we would revisit this post-beta. As for beta, we should be good with just a few accounts.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 6 file(s) to review. 

___
*[`idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/45148#-NQfO3Jj3KnqM2F8bn6B:-NQi8DLUBEo2mxU82snY:b-batsl3) ([raw file](https://github.com/harness/harness-core/blob/aa680b0370b9355e1443eee445499dc933a06849/idp-service/src/main/java/io/harness/idp/provision/service/ProvisionServiceImpl.java#L62)):*
> Backstage does not allow empty string in app-config.yaml, hence replacing it with a space
Please validate it once. I don't think replacing with a space is the correct approach. Let's deep dive into it.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: :shipit: complete! ✓

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: :shipit: complete! ✓

___
*[`idp-service/src/main/java/io/harness/idp/secret/jobs/EnvironmentSecretsSyncJob.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/45148#-NQiCMKP7BqTDqufeLB3:-NQiCMKP7BqTDqufeLB4:byzs99z) ([raw file](https://github.com/harness/harness-core/blob/aa680b0370b9355e1443eee445499dc933a06849/idp-service/src/main/java/io/harness/idp/secret/jobs/EnvironmentSecretsSyncJob.java#L65)):*
> ```Java
>       accountIds.forEach(account -> {
>         List<EnvironmentSecret> secrets = environmentSecretService.findByAccountIdentifier(account);
>         environmentSecretService.syncK8sSecret(secrets, account);
> ```

can we run separate sync per account ? if sync secret fails for 1 account rest of the account will not be synced right ?

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/secret/jobs/EnvironmentSecretsSyncJob.java` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/45148#-NQiCMKP7BqTDqufeLB3:-NQiK-rUEX_3zlGbDR6g:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/aa680b0370b9355e1443eee445499dc933a06849/idp-service/src/main/java/io/harness/idp/secret/jobs/EnvironmentSecretsSyncJob.java#L65)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

can we run separate sync per account ? if sync secret fails for 1 account rest of the account will not be synced right ?
</blockquote></details>

Done.

**Review by deepharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sathish-soundarapandian — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 2 file(s) to review.

**Review by sathish-soundarapandian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 2 file(s) to review.

**Review by sathish-soundarapandian — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148#-:-NQiNRwj0DnK-VfEn3sJ:bnfp4nl)* status: 2 file(s) to review.

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148)* status: 2 file(s) to review.

**Review by devesh-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45148#-:-NQiOKyo6vB3tG2Ral0q:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
