### PR TITLE
feat: [PL-31030]: added 2fa field in user metadata

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
We are going to support resending of 2FA emails from NG. For that, we need the data for whether or not 2FA is enabled for a user to display the option to resend emails on the UI accordingly. This PR adds a new field- "isTwoFactorAuthenticationEnabled" to the userMetadata collection in NG, and the code to populate and update it in all the relevant scenarios as listed below in the test scenarios.

This will also include a one-time migration of this field for existing NG users who have 2FA enabled.

### Testing:
The following scenarios have been tested in localdev:

**Testing UserMetadata update on toggling 2FA for a user:**
1. Enable 2FA for user from CG -> User **sees** the option to resend 2FA on NG users page
2. Disable 2FA for user from CG -> User **does not see** the option to resend 2FA on NG users page
3. Enable 2FA for user from NG -> User **sees** the option to resend 2FA on NG users page
4. Disable 2FA for user from NG -> User **does not see** the option to resend 2FA on NG users page

**Testing UserMetadata update on toggling 2FA at account level:**
1. Enable 2FA at account level -> All users in the account **see** the option to resend 2FA on NG users page
2. Disable 2FA at account level -> All users in the account **see** the option to resend 2FA on NG users page

**Testing whether UserMetadata is correctly populated when users are added to an account where 2FA is enforced at account level:**
1. Invite **new Harness user** to account via **user invite** -> User **sees** the option to resend 2FA on NG users page
2. Invite **existing Harness user** to account via **user invite**:
          a. User has 2FA enabled already -> User **sees** the option to resend 2FA on NG users page
          b. User does not have 2FA enabled already -> User **does not see** the option to resend 2FA on NG users page
3. Invite **new Harness user** to account via **SCIM** -> User **sees** the option to resend 2FA on NG users page
4. Invite **existing Harness user** to account via **SCIM**:
          a. User has 2FA enabled already -> User **sees** the option to resend 2FA on NG users page
          b. User does not have 2FA enabled already -> User **does not see** the option to resend 2FA on NG users page

**Testing UserMetadata migration for the new field- "twoFactorAuthenticationEnabled"**:
1. Enable 2FA for some users. Run the migration added in this PR. These users **see** the option to resend 2FA on NG users page.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UserMetadataTwoFactorAuthenticationMigration.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJnO1F8SNBTEQzDx3o:-NOJnO1F8SNBTEQzDx3p:b-t341w) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UserMetadataTwoFactorAuthenticationMigration.java#L61)):*
> ```Java
> 
>   private boolean get2FAStatus(String userId) {
>     Optional<UserInfo> userInfoOptional = CGRestUtils.getResponse(userClient.getUserById(userId));
> ```

minor : @tiwaritejas  confirming that this is a onet-time migration? and we would be running it during off hours to have minimal load impact on the manager pods? 
otherwise we should have to use batch API to get List<UserInfo> and update in metadata. Thanks



_Code quote:_
```Java
CGRestUtils.getResponse(userClient.getUserById(userId));
```

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 566 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJoHCl9_z93rOP4teN:-NOJoHCl9_z93rOP4teO:b-v9yq4c) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L566)):*
> ```Java
>   public RestResponse<Boolean>
>   reset2fa(@PathParam("userId") @NotEmpty String userId,
>       @AccountIdentifier @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) @NotEmpty String accountIdentifier) {
> ```

BTW why is this needed? Adding this may add feature/license enforcements, we should check this, thanks



_Code quote:_
```Java
@AccountIdentifier 
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 341 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJrGRB5btzQbkm01qW:-NOJrGRB5btzQbkm01qX:bt3ft0j) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L341)):*
> ```Java
>     userGroups.forEach(userGroup -> {
>       List<String> memberIds = userGroup.getMemberIds();
>       log.info("User group: {}, has member IDs: {}", userGroup, memberIds);
> ```

nit: lets change it to `[SSO_SYNC]` from SAML_SYNC, if this flow is triggered for SSO(LDAP/SAML) scenarios



_Code quote:_
```Java
log.info("
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 13 file(s) to review. 0 of 2 approvals obtained.

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 13 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UserMetadataTwoFactorAuthenticationMigration.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJnO1F8SNBTEQzDx3o:-NOLi2fiD-ApGtdAEGgD:b-e3nh3e) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UserMetadataTwoFactorAuthenticationMigration.java#L61)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor : @tiwaritejas  confirming that this is a onet-time migration? and we would be running it during off hours to have minimal load impact on the manager pods? 
otherwise we should have to use batch API to get List<UserInfo> and update in metadata. Thanks
</blockquote></details>

As discussed, we can continue using this approach as this is a one time migration only. @ankit-harness any thoughts here?
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java` line 566 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJoHCl9_z93rOP4teN:-NOLiFtY3CDQqi4At3c6:b5cpc0v) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java#L566)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

BTW why is this needed? Adding this may add feature/license enforcements, we should check this, thanks
</blockquote></details>

Two factor authentication as a feature is governed by enforcement framework. Hence, I have added the annotation for enforcement check.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 341 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJrGRB5btzQbkm01qW:-NOLiV897qtGfpMYs32g:b-9jy2b) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L341)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

nit: lets change it to `[SSO_SYNC]` from SAML_SYNC, if this flow is triggered for SSO(LDAP/SAML) scenarios
</blockquote></details>

Optimised this as well as the other logs in the file.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 13 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by gn-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 13 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 769 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NP1G9c7CoxLFO7lPFU2:-NP1G9c7CoxLFO7lPFU3:b-mgq3mn) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L769)):*
> ```Java
>       update.set(UserMetadataKeys.externallyManaged, user.isExternallyManaged());
>       update.set(UserMetadataKeys.twoFactorAuthenticationEnabled, user.isTwoFactorAuthenticationEnabled());
>     }
> ```

nit: Is there a performance benefit of writing it this way?

Why not just set all the fields in the update, without these if-statements?



_Code quote:_
```Java
      update.set(UserMetadataKeys.twoFactorAuthenticationEnabled, user.isTwoFactorAuthenticationEnabled());
    }
    if (!isBlank(user.getEmail()) && !user.getEmail().equals(savedUserOpt.get().getEmail())) {
      update.set(UserMetadataKeys.email, user.getEmail());
      update.set(UserMetadataKeys.locked, user.isLocked());
      update.set(UserMetadataKeys.disabled, user.isDisabled());
      update.set(UserMetadataKeys.externallyManaged, user.isExternallyManaged());
      update.set(UserMetadataKeys.twoFactorAuthenticationEnabled, user.isTwoFactorAuthenticationEnabled());
    }
    if (user.isTwoFactorAuthenticationEnabled() != savedUserOpt.get().isTwoFactorAuthenticationEnabled()) {
      update.set(UserMetadataKeys.locked, user.isLocked());
      update.set(UserMetadataKeys.disabled, user.isDisabled());
      update.set(UserMetadataKeys.externallyManaged, user.isExternallyManaged());
      update.set(UserMetadataKeys.twoFactorAuthenticationEnabled, user.isTwoFactorAuthenticationEnabled());
    }
```
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3113 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NP1GuZDBN3lzRWGeEdh:-NP1GuZDBN3lzRWGeEdi:b-ibhxi9) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3113)):*
> ```Java
>     userDTOBuilder.setName(updatedUser != null ? updatedUser.getName() : oldUser.getName());
>     userDTOBuilder.setEmail(updatedUser != null ? updatedUser.getEmail() : oldUser.getEmail());
>     userDTOBuilder.setLocked(updatedUser != null ? updatedUser.isUserLocked() : oldUser.isUserLocked());
> ```

nit: this again seems very wasteful. just check once and create DTO from non-null one. like:

UserDTO.Builder userDTOBuilder = UserDTO.newBuilder();
if (updateUser == null) {
  updateUserDTOFromUser(oldUser, userDTOBuilder);
} else {
  updateUserDTOFromUser(updatedUser, userDTOBuilder);
}



_Code quote:_
```Java
    userDTOBuilder.setUserId(updatedUser != null ? updatedUser.getUuid() : oldUser.getUuid());
    userDTOBuilder.setName(updatedUser != null ? updatedUser.getName() : oldUser.getName());
    userDTOBuilder.setEmail(updatedUser != null ? updatedUser.getEmail() : oldUser.getEmail());
    userDTOBuilder.setLocked(updatedUser != null ? updatedUser.isUserLocked() : oldUser.isUserLocked());
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 344 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NPG6dm56XQ4lpE8A8X8:-NPG6dm7-ODqSGsqimX_:b-jfz50g) ([raw file](https://github.com/harness/harness-core/blob/e61ebdb01fd1a6f460f446eb3f787e0bf470178c/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L344)):*
> ```Java
>       if (isEmpty(memberIds)) {
>         userGroup.setMembers(new ArrayList<>());
>         log.info("[SAML_SYNC]: User group has empty memberIDs: {}", userGroup);
> ```

why did you remove this log?

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2591 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NPG6rA61f--kQGWqyem:-NPG6rA61f--kQGWqyen:bo6twny) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2591)):*
> ```Java
>             log.info("Sending 2FA reset email to user {}", updatedUser.getEmail());
>             totpAuthHandler.sendTwoFactorAuthenticationResetEmail(updatedUser);
>             publishUserEvent(user, updatedUser);
> ```

Has this been tested in audits?

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3113 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NP1GuZDBN3lzRWGeEdh:-NPG7CjuBqjkFd1h4jfH:b32v57) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3113)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: this again seems very wasteful. just check once and create DTO from non-null one. like:

UserDTO.Builder userDTOBuilder = UserDTO.newBuilder();
if (updateUser == null) {
  updateUserDTOFromUser(oldUser, userDTOBuilder);
} else {
  updateUserDTOFromUser(updatedUser, userDTOBuilder);
}


</blockquote></details>

+1

**Comment by shashank-harness** [comment]
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/user/user.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NPG7GyfDgWArsKUWRYw:-NPG7GyfDgWArsKUWRYx:b6j5jr3) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/user/user.proto#L18)):*
> ```protobuf
>   string email = 6;
>   bool locked = 7;
>   bool isTwoFactorAuthenticationEnabled = 8;
> ```

Is this class used in any delegate task If yes, won't this impact backward compatibility?
cc: @pbarapatre10

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 13 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java` line 769 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NP1G9c7CoxLFO7lPFU2:-NPGE_sE8Q3YLt9iEdu3:b-8wzbhl) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java#L769)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: Is there a performance benefit of writing it this way?

Why not just set all the fields in the update, without these if-statements?
</blockquote></details>

Noted. Will take this up in a separate PR to avoid any further impact in this one.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 344 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NPG6dm56XQ4lpE8A8X8:-NPGDhs6DgnIrwjooJLW:b-3so9ns) ([raw file](https://github.com/harness/harness-core/blob/e61ebdb01fd1a6f460f446eb3f787e0bf470178c/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L344)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

why did you remove this log?
</blockquote></details>

It's a redundant log, we have another log before this to capture this detail.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2591 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NPG6rA61f--kQGWqyem:-NPGDpSM8zCkBVBuSwyw:b2bpqcf) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2591)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Has this been tested in audits?
</blockquote></details>

This event is for sending user update event from CG. This will be handled by NG user service to set/unset 2fa in UserMetadata when it is done on CG side.
___
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 3113 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NP1GuZDBN3lzRWGeEdh:-NPGE7W42H5R2lpGYnkH:bi9g3xt) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L3113)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Yes, I've noted this. Will pick this in a separate PR so as to keep impact minimal in this PR.
___
*[`953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/user/user.proto` line 18 at r6](https://reviewable.io/reviews/harness/harness-core/43975#-NPG7GyfDgWArsKUWRYw:-NPGERYG1TaIPvGp-aye:b-si9yzt) ([raw file](https://github.com/harness/harness-core/blob/b76157c6b456b4010be23eeefa83ae4938326a1d/953-events-api/src/main/proto/io/harness/eventsframework/schemas/entity_crud/user/user.proto#L18)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Is this class used in any delegate task If yes, won't this impact backward compatibility?
cc: @pbarapatre10 
</blockquote></details>

This is only used in events framework to send publish and listen for data.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 1 of 1 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 5 file(s) to review. 2. unresolved discussions.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UserMetadataTwoFactorAuthenticationMigration.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/43975#-NOJnO1F8SNBTEQzDx3o:-NPGKH_300uejwsNJsWA:b-q7ddvh) ([raw file](https://github.com/harness/harness-core/blob/2a510db8bbda6d0a2fc6ab977c804e198d64edf7/120-ng-manager/src/main/java/io/harness/ng/core/migration/background/UserMetadataTwoFactorAuthenticationMigration.java#L61)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

As discussed, we can continue using this approach as this is a one time migration only. @ankit-harness any thoughts here?
</blockquote></details>

As discussed please provide 10 sec sleep in between batches

**Review by shashank-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 7 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 2 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43975)* status: 1. unresolved discussions.

**Pull request merged**
