### PR TITLE
[fix]: [PL-32246]: In JWTAuthenticationFilter, added log for invalid claim exception.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Currently, when InvalidClaimException is thrown while validating token, we don't get the cause in the logs.
So in JWTAuthenticationFilter, added log to get actual invalid claim information.
This HF is targetted for CGManager.

Getting the cause now:

ERROR io.harness.security.JWTAuthenticationFilter - sourceServiceId: Bearer  
io.harness.exception.InvalidRequestException: Token expired
	at io.harness.security.JWTTokenServiceUtils.verifyJWTToken(JWTTokenServiceUtils.java:75)
	at io.harness.security.JWTTokenServiceUtils.isServiceAuthorizationValid(JWTTokenServiceUtils.java:53)
	at io.harness.security.JWTAuthenticationFilter.getIsServiceAuthorizationValid(JWTAuthenticationFilter.java:93)
	at io.harness.security.JWTAuthenticationFilter.lambda$filter$1(JWTAuthenticationFilter.java:109)
	at io.harness.security.JWTAuthenticationFilter.filter(JWTAuthenticationFilter.java:110)
	at io.harness.security.JWTAuthenticationFilter.filter(JWTAuthenticationFilter.java:55)
	at io.harness.security.NextGenAuthenticationFilter.filter(NextGenAuthenticationFilter.java:107)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:247)

	skipping stacktrace for brevity.

	at java.base/java.lang.Thread.run(Thread.java:829)
	
**Caused by: com.auth0.jwt.exceptions.InvalidClaimException: The Token has expired on Wed Dec 22 15:47:53 IST 2021.**
	at com.auth0.jwt.JWTVerifier.assertValidDateClaim(JWTVerifier.java:434)
	at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:366)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:342)
	at io.harness.security.JWTTokenServiceUtils.verifyJWTToken(JWTTokenServiceUtils.java:69)
	... 70 common frames omitted

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45835)

### CODE REVIEW

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45835)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45835)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/JWTAuthenticationFilter.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/45835#-NRhlGMoA5Oc72mr5E4f:-NRhlGMoA5Oc72mr5E4g:b-lgytk8) ([raw file](https://github.com/harness/harness-core/blob/829a536c7717298300aa89bbeef09e8ae8c0399b/980-commons/src/main/java/io/harness/security/JWTAuthenticationFilter.java#L95)):*
> ```Java
>       return JWTTokenServiceUtils.isServiceAuthorizationValid(serviceToken, serviceSecret);
>     } catch (InvalidRequestException ex) {
>       log.error("sourceServiceId: " + sourceServiceId, ex);
> ```

Shouldn't we print ex.getCause()?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45835)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/security/JWTAuthenticationFilter.java` line 95 at r1](https://reviewable.io/reviews/harness/harness-core/45835#-NRhlGMoA5Oc72mr5E4f:-NRhmiJC2ftBg-rtGs_C:bs2pcaj) ([raw file](https://github.com/harness/harness-core/blob/829a536c7717298300aa89bbeef09e8ae8c0399b/980-commons/src/main/java/io/harness/security/JWTAuthenticationFilter.java#L95)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't we print ex.getCause()?
</blockquote></details>

Now getting following cause in the log. Added stacktrace in PR description.

Caused by: com.auth0.jwt.exceptions.InvalidClaimException: The Token has expired on Wed Dec 22 15:47:53 IST 2021.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45835#-:-NRhqGdHCzrm4lBqd8mP:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
