### PR TITLE
[fix]: [PL-22244]: Added logs to identify cause of intermittent User not authorized exception

### PR DESCRIPTION
**Pull request by nishantsaini20**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31158)

### CODE REVIEW

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Comment by nishantsaini20** [comment]
trigger messagecheck

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31158)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java, line 1964 at r1](https://reviewable.io/reviews/harness/harness-core/31158#-MxJE-qeAvSKlAEX7_Q7:-MxJE-qeAvSKlAEX7_Q8:b-vuprqn) ([raw file](https://github.com/harness/harness-core/blob/e4c6508696ba964b031a8156f4242a746d42ee48/400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java#L1964)):*
> ```Java
>     if (!isAuthorized(requiredPermissionAttributes, accountPermissions)) {
>       log.info("{} : required => {} | permissions => {}", USER_NOT_AUTHORIZED,
>           requiredPermissionAttributes.stream()
> ```

Can we add a Null check on requiredPermissionAttribute to be safe in case thats the actual issue.

**Review by piyush-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31158)* status: 1 of 2 approvals obtained.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31158)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java, line 1964 at r1](https://reviewable.io/reviews/harness/harness-core/31158#-MxJE-qeAvSKlAEX7_Q7:-MxJExH1DpNjTMLIJXgk:byz06o4) ([raw file](https://github.com/harness/harness-core/blob/e4c6508696ba964b031a8156f4242a746d42ee48/400-rest/src/main/java/software/wings/service/impl/security/auth/AuthHandler.java#L1964)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we add a Null check on requiredPermissionAttribute to be safe in case thats the actual issue.
</blockquote></details>

isAuthorized method in the if condition has requiredPermissionAttributes as an argument. If it is null then usage in isAuthorized method would have already thrown null pointer exception.

**Review by piyush-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31158)* status: :shipit: complete! ✓

**Pull request merged**
